### PR TITLE
Fixes missing firelocks around Icebox

### PR DESCRIPTION
**Pull request by Ical92**
## About The Pull Request
Adds in firelocks to multiple Security Outposts (Specifically ones with a front desk), Bridge, Medical, and a few other places around the map where a fire alarm could be fit, and where a firelock may be needed.
## Why It's Good For The Game
Firelocks are always nice, especially on IceBox and where other maps have firelocks.
## Changelog
:cl:
fix: adds a few firelocks and alarms around IceBox
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
If you want bonus points, the middle-right airlock is also missing a firedoor

image

**Comment by Ical92** [comment]
Let me know if this is _too_ many firelocks

**Comment by MrMelbert** [comment]
I can't precisely see via MDB where you all placed them but please ensure rooms you added firelocks too have fire alarms - so people can actually get out

**Comment by MrMelbert** [comment]
Also bear in mind some rooms intentionally don't have firedoors, because they're too small or get exposed to space too often that it'd always trigger, or they just intentionally decided that room shouldn't have a fire alarm.

**Comment by Ical92** [comment]
Yeah I got a bit firelock happy with that last commit, went back and removed some / added fire alarms.

**Review by Ghommie — APPROVED** [review]

**Comment by Maurukas** [comment]
I'm not sure why this isn't showing merge conflict correctly.

**Comment by Maurukas** [comment]
Fix your conflicts please.

**Pull request merged**
