### PR TITLE
Adds the Moffra wing pattern (and antennae)

### PR DESCRIPTION
**Pull request by Bluedino1025**
## About The Pull Request
Adds the moffra wing pattern and antennae based off of mothra.
FFFFFFFFFFFFFCapture
FFFFFFCapture
FFFFFFFCapture
FFFFFFFFFFCapture
FFFFFFFFFFFFCapture

## Why It's Good For The Game
New choices to express yourself is always good and it seems like a fun reference.
image
Maintainer approval

## Changelog

:cl:
imageadd: Adds Moffra wing and antennae sprites
/:cl:

### CODE REVIEW

**Comment by dalmationer** [comment]
so cute!

**Comment by SmoSmoSmoSmok** [comment]
this its an amazing it look like a cute rabit its my favorite mofra skin 👍

**Comment by Elli-Skala** [comment]
What about with a flight potion?

**Comment by Bluedino1025** [comment]
> What about with a flight potion?

There are only two moth wing sprites for flight potions so its already a drastic change with any other wings.

**Comment by Bluedino1025** [comment]
The code's all good just waiting for review or if I should edit the sprites any.

**Review by Imaginos16 — APPROVED** [review]
Its... Fine.

**Comment by optimumtact** [comment]
Me when I don't like species PR's but nobody else will look at them.
maintainers add this

**Pull request merged**
