### PR TITLE
You can do revival surgery on Ian

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Allows you to perform revival surgery on any mob which is organic or looks humanoid.
This means yes: Corgis, Goliaths, ~~Syndicate mobs~~ not those because they spawn human corpses and delete themselves.
No: Slimes, Ghosts, General Beepsky.

Splits revival surgery into a subtype used for "mobs" and a subtype for "mobs with brains" as the former don't have any brains to damage.

Additionally by special request, Ian can now wear an eyepatch and will automatically put one on if he is brought back from death.
image

## Why It's Good For The Game

Currently you revive dead pets either by creating a magical reagent out of holy water or by buying a mining item which also brainwashes them, however reasonably our skilled medical team should be able to put a dog back together and now can.
When you fuck up one of the stages of Tend Wounds on a kitten and stab it to death with your scalpel, now you can fix it.
Expands the possibilities of vetinerary roleplay.

## Changelog

:cl:
add: Many kinds of mobs can now be brought back to life through revival surgery.
add: Dogs can wear eyepatches.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
would need to get Ian and other persistence pets to handle their memory write of them dying upon round end and body destruction, since right now any death will reset their rounds survived streak even if you bring them back i think

**Comment by AtomTheProphet** [comment]
Does this apply to xenomorphs as well?

**Comment by Jacquerel** [comment]
> Does this let us revive xenomorphs?

player-controlled xenomorphs would require the normal revival surgery because they are "carbon" mobs, if that currently doesn't work it still wouldn't
you can use it on the xeno npc mobs from ruins if you want

**Comment by FlufflesTheDog** [comment]
All the surgery steps refer to ...'s **chest**,  despite supposedly operating on their brain
image

Someone bringing a dead pet to medbay and being told, at best, to go ask a miner is one of my oldest space station memories.
Very glad to see this change

**Comment by RedBaronFlyer** [comment]
I've been hoping for something like this for a long time. The tedium of getting a miner to buy a lazarus was super annoying since seemingly 2/3rds of miners don't respond to common/supply radio/PDA messages, are SSD, or got turned into a fine red paste trying to boss rush.

> this makes killing ian much less of a big deal which is sad

Eh, I somewhat agree, but progtot being the way it is has made killing pets basically meaningless. I barely see anyone care when pets get killed, even on Manuel, because it happens so often. I'm unphased by people unwrenching the ORM or abusing paramedic access to run off with Paperwork/Citrus and kill them, or coming back from the kitchen just to see Paperwork/Citrus dead on the floor because it happens almost every round. Runtime/McGruff are the only pets I see that still get a reaction from people when they're killed (even then it's only like, 20% of the time) which I presume is because they're department pets that are also common real-life pets as well.

I've seen people get more mad about the ORM, the autolathe, or a department lathe getting bombed simply because it has an actual game impact (even if you rebuild the ORM and relink it with a multitool after scanning the ore silo)

something something dynamic procedurally generated Skyrim quests something something re-add old tot

**Pull request merged**
