### PR TITLE
Powercreeps the powercrepe

### PR DESCRIPTION
**Pull request by Niknakflak**
## About The Pull Request
Buffs the powercrepe
Honestly, Never seen anyone make or use this ever, it's finally time to powercreep the powercrepe again.

## Why It's Good For The Game
More incentive to encourage traitors/captains/HoS to make this thing because having people beat/kill other people with a jelly filled pancake tortilla thing is hilarious

## Changelog
:cl: NikNak
balance: The powercrepe has been buffed
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
classic

**Comment by Fikou** [comment]
powercreep

**Comment by Tharcoonvagh** [comment]
thanks, now it does equal damage to an esword

**Comment by knacker48** [comment]
Wait, I wasn't suppose to eat it? Damn I've been using that thing all wrong

**Comment by ATH1909** [comment]
tbh, I'd be more comfortable with a buff that merely increases the powercrepe's force to 21 (so that it can break down doors) but doesn't buff anything else. It's supposed to be powerCREEP, not powerblitzkreig.

Still, I'm fine with this being merged.

**Comment by Spepbuthewranglesgithub** [comment]
ah yes, edible energy sword.

**Comment by trollbreeder** [comment]
why the fuck does it have the same force as an esword
and the cakehat doesn't

**Comment by Niknakflak** [comment]
> why the fuck does it have the same force as an esword
> and the cakehat doesn't

INB4 POWERCREPE

**Comment by trollbreeder** [comment]
> INB4 POWERCREPE

I blame tangerine of the color orange for closing the PR that buffed the energy cake

**Comment by Tumesuo** [comment]
powercrepe powercrepe
assistant gaming

**Comment by Shadowflame909** [comment]
Who knew you could make such an overpowered snack

**Comment by cacogen** [comment]
why

**Comment by deathslayer2481** [comment]
But can it be grindstoned?

**Pull request merged**
