### PR TITLE
Creates turf type space/openspace

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Alternative to https://github.com/tgstation/tgstation/pull/63255

## Changelog
:cl:
code: space/openspace turfs now exist to make multi-z space turfs act more space-like.
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
Don't forget to include it here:

https://github.com/tgstation/tgstation/blob/9f9f633ebd322596cccfd05ab19793ce03e46af3/code/__DEFINES/is_helpers.dm#L15-L21

and here:

https://github.com/tgstation/tgstation/blob/9f9f633ebd322596cccfd05ab19793ce03e46af3/code/__DEFINES/is_helpers.dm#L29

**Comment by tf-4** [comment]
> Don't forget to include it here:
> 
> https://github.com/tgstation/tgstation/blob/9f9f633ebd322596cccfd05ab19793ce03e46af3/code/__DEFINES/is_helpers.dm#L15-L21
> 
> and here:
> 
> https://github.com/tgstation/tgstation/blob/9f9f633ebd322596cccfd05ab19793ce03e46af3/code/__DEFINES/is_helpers.dm#L29

Do typecaches not include subtypes?

**Comment by LemonInTheDark** [comment]
> Do typecaches not include subtypes?
> 
> .. actually don't they _both_ include subtypes?

typecaches run on typesof, which uses subtypes. so does istype.

Shouldn't be needed I don't think

**Comment by timothymtorres** [comment]
Sorry I had no idea.  Was just trying to make sure this is compatible with my PR.

**Comment by LemonInTheDark** [comment]
Sall good

**Pull request merged**
