### PR TITLE
Byond donator ghost directional sprites

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Adds directional sprites to all byond membership ghost options

A few examples since diff bot is dead
ghostking
ghostian
ghostcat
multi
the first 3 pictures are the unique ones and the last image is only showing a couple options since theres 20+ ghosts that are basically just recolors of the original sprite and i really dont want to take a million pictures of it

## Why It's Good For The Game

People who help fund the engine deserve to show off their snowflake ghosts in all their glory

## Changelog
:cl:
imageadd: Byond membership ghosts now have directional sprites
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
Pictures? I think icondiffbot is on vacation

**Comment by Twaticus** [comment]
> Pictures? I think icondiffbot is on vacation

pictures added

**Comment by MrDoomBringer** [comment]
based and directionpilled

**Comment by ATH1909** [comment]
ptw content smh

In all seriousness, though, nice work!

**Pull request merged**
