### PR TITLE
Lizards X Autohiss: Ecks', Z's and Kss's. 

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

Iterates upon ideas established in #50698 and makes general improvements.

## Why It's Good For The Game

While lizards hissing on X is an understandable and welcome addition to the lizard autohiss mechanic, this made it harder to understand lizardhiss when using certain words containing X. By utilizing the powers of regex, phonetic intent can be determined and actualized. Simply put, lizards will now properly enunciate their X's properly. No more "Kssenomporhs", and "xray" will be said as "ecksray". This will make lizards understandable at a glance while maintaining the hiss-feeling.

image

We can jumble speech all we like and still understand it while maintaining phonetic similarities.

## Changelog
:cl:
tweak: Added Regex to account for variations on X within the English language
tweak: Added The ability for lizards to use the word X at the beginning of a word again.
tweak: Doesn't make every" X" into "KSS"
tweak: Adjusts lizard Autohissing on "X" to be more phonetically accurate.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
the regex proliferation is getting tedious and unnecessary.

What benefit does this add for the processing cost of running extra regexes on every lizard chat message?

**Comment by Qustinnus** [comment]
why dont lizards just type like lizards if they want to roleplay like lizards

**Comment by Zytolg** [comment]
> why dont lizards just type like lizards if they want to roleplay like lizards

Lizards have hissed for a long time. While we could simply remove autohiss, I doubt that many lizard players would actively try to manually hiss. Authohiss is a feature that helps build out the idea that lizards struggle to integrate with their coworkers, and despite having learned most of Galactic Common, there is still that inherent barrier due to languages and biology. We have plenty of real-world examples to back this up (see broken English).

This commit is about making improvements to a previous commit. If given two options, players will generally pick the option which requires them to do the least. Currently, that option generates text that results in phrases like "Kssenomorphs" or "Kss-Ray". Originally the plan was to turn those phrases into "Zenomorphs", but it was decided against for 2 reasons. 1) while X and Z can be phonetically different, the regex to determine against the two is an added layer of complexity, and for surprisingly few use cases. This is also works in favor of Oranges "Regex Proliferation" statement. I've already made the change to remove it indefinitely because it won't add anything compared to the other changes. 

This still leaves 2 cases of a soft "kss" sound found commonly in words containing "ix" sounds and a hard "ecks" which is found which X is either standalone or found following E. While we certainly won't be able to capture every sound of X, the point is to do enough to make it believable. By also accounting for cases of "ecks", we can do that, and at a minimal addition.

I firmly believe however it's in the interests of both lizard and non-lizard players alike that lizards don't go around butchering some of the more frequently used words in the game. 

Finally, a better change in regards towards regex proliferation wound't be getting rid of the regex. Instead, we should have something that so that we don't have to use regex to check for case-sensitive statement variations, because that would cut out half the regex's we have in here.

**Comment by optimumtact** [comment]
http://www.byond.com/docs/ref/index.html#/regex/var/flags
```
Flag | Meaning
--   |     --
i    | **Case-insensitive matching**
g    | Global: In Find() subsequent calls will start where this left off, and in Replace() all matches are replaced.
m    | Multi-line: ^ and $ refer to the beginning and end of a line, respectively.

```

**Pull request merged**
