### PR TITLE
Fixes BAD Windows At IceBox Departures (and the stuff on said windows)

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

Take a look at this photograph:

image

RRRAGH. THAT'S SUPPOSED TO BE PLATING UNDER THOSE WINDOWS, NOT SNOW! THAT CAUSES DEPRESSURIZATION THAT'S NOT GOOD GRRRRRRRR-

I also moved the lights off the windows and placed them a bit around departures (had to replace some windows with walls) to ensure everyone still gets some light. I also replaced some windows with walls to accommodate for other light fixtures while I was in the area.

## Why It's Good For The Game

image

Lights on windows look ugly. Having snow under reinforced window spawners makes me cry, because I think it's wasteful to not have it be plating (since it's being covered most the time anyways)..

## Changelog

:cl:
fix: Nanotrasen will now stop placing reinforced window spawners right on top of snow at IceBox Departures.
/:cl:

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]
the snow tiles underneath the windows are safe snow and won't cause depressurization when deconstructed 

replace them with directional windows if they are upsetting you extensively please

**Comment by san7890** [comment]
> the snow tiles underneath the windows are safe snow and won't cause depressurization when deconstructed
> 
> replace them with directional windows if they are upsetting you extensively please

updated

**Comment by MrMelbert** [comment]
ty

**Comment by MrMelbert** [comment]
It would be pretty neat if you removed that duplicate beacon from the departures lounge, too
image

**Comment by MrMelbert** [comment]
image

**Pull request merged**
