### PR TITLE
fixes up some toy sword checks

### PR DESCRIPTION
**Pull request by PKPenguin321**
removes broken check.
Fixes https://github.com/tgstation/tgstation/issues/18248

adds a missing return to account for nodrop items. changes an else if to just an if to account for removed check.

### CODE REVIEW

**Comment by xxalpha** [comment]
You don't need to create an issue to get tokens.

**Comment by PKPenguin321** [comment]
i actually made the issue since i wasnt sure if i could fix the check or if it should just be removed but now i know

**Comment by xxalpha** [comment]
:tangerine:

**Comment by PKPenguin321** [comment]
good 2 merge

**Pull request merged**
