### PR TITLE
Revert "Give blood brothers traitor HUD (#45295)"

### LINKED ISSUE #46427: Lost own rev hud icon on cloning
Round ID: 118248

Was rev, got killed and cloned, was still rev but myself and other revs could not see a red R above me.

### PR DESCRIPTION
**Pull request by sohpeach**
Fixes https://github.com/tgstation/tgstation/issues/46427

## About The Pull Request
@Akrilla  mentioned not wanting to fix this, it causes problems with antag HUDs being reset when minds are transferred to new bodies and I'm also concerned about how it adds mobs to both a `/datum/antag_hud` and a `/datum/antag_hud/team` instance when both use the ANTAG_HUD icon.

I think there's probably some issues with the HUDs on dynamic, especially if you were converted to a role and then deconverted, but this had nothing to do with it.

## Changelog
:cl:
fix: Revs/Cult no longer lose their antag HUD when transferred to other bodies
del: Blood brothers no longer have team antag HUDs
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Also fixes #45935

**Comment by ATH1909** [comment]
Aw, but these blood brother HUDs are really, really nice to have as a blood brother. It SUCKS to be accidentally killed by your own blood brother because they didn't realize that you were their ally, and the blood brother HUDs give blood brothers a much-needed edge in a fight against non-blood brothers.

**Comment by willox** [comment]
> Aw, but these blood brother HUDs are really, really nice to have as a blood brother. It SUCKS to be accidentally killed by your own blood brother because they didn't realize that you were their ally, and the blood brother HUDs give blood brothers a much-needed edge in a fight against non-blood brothers.
> 
> Isn't there SOME way to fix this that won't involve removing the blood brother HUD(s)?

I'd like to work on re-adding it, but any approach I make would involve reverting this first and I don't think the broken code should be left in.

**Comment by ATH1909** [comment]
> > Isn't there SOME way to fix this that won't involve removing the blood brother HUD(s)?
> 
> I'd like to work on re-adding it, but any approach I make would involve reverting the original PR first and I don't think the broken code should be left in.

IMO, you should make your fix for this issue (that keeps blood brother HUDs) FIRST, _then_ revert #54295 to implement your fix. Right now, blood brother HUDs seem to help things more than they hurt them (correct me if I'm wrong, though).

**Comment by Akrilla** [comment]
HUD code is gross and not actively coding for tg for a while, so not something I'm too interested in picking up. I mentioned it was best to revert to fix issues, though I guess it comes down to if the blood bro HUD is better than the other issues it can come with.

**Comment by wesoda25** [comment]
Giving blood buddies a HUD is hugbox anyways, the role is fun due to the unknown and difficulty.

**Pull request merged**
