### PR TITLE
Revert "Move some stuff from different layers to different planes"

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Reverts tgstation/-tg-station#17086

Gotta test merge this at the very least, everything is invisible

### CODE REVIEW

**Comment by Jalleo** [comment]
Welp is this because it only works on byond 510 clients or it is literally broken?

**Comment by KorPhaeron** [comment]
Broken

**Comment by Incoming5643** [comment]
I still think we shouldn't be merging 510 feature pulls until it goes stable.

**Comment by Jalleo** [comment]
@Incoming5643 we already have the server running 510

**Comment by Incoming5643** [comment]
I'm just saying that feature behavior in 510 might change before it goes stable. It'd be poor form if it did, but I'm a <s>pessimist</s> realist

**Comment by optimumtact** [comment]
Begone thrice cursed @Incoming5643 
we banish thee, 510 is the future

**Comment by MrPerson** [comment]
Planes are a 509 feature, not 510

**Comment by Incoming5643** [comment]
I was never here

:8ball:

**Comment by Jordie0608** [comment]
<MrPerson> There's some issues that can't be solved right now

**Pull request merged**
