### PR TITLE
Revert "Fixes grenade launchers reporting incorrect live rounds"

### PR DESCRIPTION
**Pull request by DaxDupont**
Reverts tgstation/tgstation#40371

OH GOD 
dreamseeker_2018-09-23_13-48-06

### CODE REVIEW

**Comment by Jordie0608** [comment]
@SpaceManiac 
Occurred across two rounds at roundstart.
717bfb4

**Comment by ma44** [comment]
149.9 hours of testing

**Comment by SpaceManiac** [comment]
erf

**Comment by DaxDupont** [comment]
Make sure to close this when it gets fixed

**Pull request closed without merging**
