### PR TITLE
Gives slime potions unique sprites.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Available in 9 designer colours.

Fuck Fuck  Fuck Fuck Fuck Fuck Fuck Fuck Fuck

### CODE REVIEW

**Comment by WJohn** [comment]
These look pretty flat, honestly.

**Comment by TechnoAlchemisto** [comment]
gg

**Comment by KorPhaeron** [comment]
I like them

**Comment by Xhuis** [comment]
The branch name is a :+1: alone tbh

**Comment by Bawhoppen** [comment]
which side to pick oh god the pressure

**Comment by PKPenguin321** [comment]
they look like skyrim potions

**Comment by optimumtact** [comment]
I forgot to comment but these should have not been merged without a decent shading applied.

**Comment by TechnoAlchemisto** [comment]
GG

**Pull request merged**
