### PR TITLE
Brings Back Bagulo

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Putting a Bag of Holding into another Bag of Holding now creates a stage 1 singularity.
Removes the BoH singularity subtype.

## Why It's Good For The Game

Bags of Holding have been nerfed to require anomaly cores, which makes them much much rarer, especially to get 2 of them, previously also before the tear in reality bohbombs made stage 2 singularities which automoved and would suck things up strongly, stage 1 doesnt move, requires about 4 people to jump in to advance to the second stage while it decays, so you can create big chaos or not do anything at all, this makes bohbombs satisfying and funny things to do with their rarity, creating a force that can wreck the round but also can just be stopped by people avoiding it
also nostalgic

## Changelog
:cl:
add: Brings back putting a Bag of Holding inside another Bag of Holding creating a gravitational singularity.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Has that change even hit a server yet?

Until we see the change play out I'm unwilling to green light this, especially in light of the rework of anomaly cores that's being iterated upon.

**Comment by Fikou** [comment]
> Has that change even hit a server yet?

yeah i might have rushed this a bit, lets just wait and see if bohs become rare enough
(although stage 1 singulos are really not that strong until they start growing)

**Comment by Spepbuthewranglesgithub** [comment]
considering there can only be one bluespace anomaly per round im sure its fiiiiiiine, not like BoH bombs are going to happen at all either way.

_yes, seriously._

**Comment by optimumtact** [comment]
https://hackmd.io/jjLi8Nl3Th6_NnLnycYRbg FYI

**Comment by TheVekter** [comment]
> considering there can only be one bluespace anomaly per round im sure its fiiiiiiine, not like BoH bombs are going to happen at all either way.
> 
> _yes, seriously._

Objectively untrue. The odds on them are a bit low right now but there's no system that prevents them from spawning multiple times.

**Comment by necromanceranne** [comment]
Also there is a BoH in space so there actually can be two BoH's in a given round.

**Comment by Spepbuthewranglesgithub** [comment]
> > considering there can only be one bluespace anomaly per round im sure its fiiiiiiine, not like BoH bombs are going to happen at all either way.
> > _yes, seriously._
> 
> Objectively untrue. The odds on them are a bit low right now but there's no system that prevents them from spawning multiple times.

```
/datum/round_event_control/anomaly/anomaly_bluespace
	name = "Anomaly: Bluespace"
	typepath = /datum/round_event/anomaly/anomaly_bluespace

	max_occurrences = 1
	weight = 15
```

**Comment by anconfuzedrock** [comment]
ok does rarer make it fairer though

**Comment by Fikou** [comment]
> ok does rarer make it fairer though

yes

**Comment by Fikou** [comment]
> ok does rarer make it fairer though

it seems more fair to me, rare thing that wont do shit unless 4 people jump into it and wont kill you if you run away since it doesnt move but it has potential to be roundending if nobody stops it and lots of people jump in vs just random instakill for all people in a room

**Comment by TheVekter** [comment]
> 
> 
> > > considering there can only be one bluespace anomaly per round im sure its fiiiiiiine, not like BoH bombs are going to happen at all either way.
> > > _yes, seriously._
> > 
> > 
> > Objectively untrue. The odds on them are a bit low right now but there's no system that prevents them from spawning multiple times.
> 
> ```
> /datum/round_event_control/anomaly/anomaly_bluespace
> 	name = "Anomaly: Bluespace"
> 	typepath = /datum/round_event/anomaly/anomaly_bluespace
> 
> 	max_occurrences = 1
> 	weight = 15
> ```

Oh fuck that. I'll fix it.

**Comment by AtlasRules** [comment]
how about, get this, removing it entirely because it's fucking retarded, just gib the person who did it

**Comment by TheVekter** [comment]
Why was this blocked?

**Comment by TheVekter** [comment]
Makes sense. I didn't know if that was still the case since the nerf was merged.

**Comment by optimumtact** [comment]
I dont' want to change this in light of the forthcoming anomaly rework

**Pull request closed without merging**
