### PR TITLE
Removes food and pills becoming dirty

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

food and pills and whatever else may not become dirty

## Why It's Good For The Game

there are so many instances where the food becoming dirty becomes a massive headache because having to go to dorms or medbay or engineering to wash a burger to not catch a sickness is just shitty gameplay

## Changelog
:cl:
del: food and pills may not become dirty
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
thankyouthankyouthankyou

Wasting a harvest of a plant because you lag click with hand and now the entire harvest is on the floor and are all dirty sucks so much.

**Comment by Jacquerel** [comment]
I will miss this feature but not enough to block the PR

**Comment by Helg2** [comment]
There was some unique illnesses for the dirty food iirc

**Comment by Time-Green** [comment]
> There was some unique illnesses for the dirty food iirc

Illnesses could probably be moved to the disease events, and maybe buffed a bit

**Comment by DaCoolBoss** [comment]
The food virus symptoms arent special enough to not just be regular symptoms, the only reason they aren't is to force uniqueness on food virus types. Possible exception is the carp virus symptom that forces teleports/attacks on random people near you. That one's kind of idiotic and I wouldn't mind it vanishing.

**Comment by GPeckman** [comment]
The dirty food was also a major source of framerate drop. Having dozens of plants all emitting stink lines on the screen at once noticeably tanked my FPS.

**Comment by Exester509** [comment]
Would you look at that, this is what I said would happen when the PR was merged

**Comment by jughu** [comment]
> The dirty food was also a major source of framerate drop. Having dozens of plants all emitting stink lines on the screen at once noticeably tanked my FPS.



> The dirty food was also a major source of framerate drop. Having dozens of plants all emitting stink lines on the screen at once noticeably tanked my FPS.

that wasn't related to that at all that was just natural decaying

**Comment by mc-oofert** [comment]
> The dirty food was also a major source of framerate drop. Having dozens of plants all emitting stink lines on the screen at once noticeably tanked my FPS.

thats still in we are removing food getting dirty and giving you aids

**Comment by Stoopler** [comment]
instead of outright removing it, can we have like a 5 second rule?  it doesn't make sense to be able to eat something that was sitting on the floor for however long and not get sick (potentially) from it

**Comment by Pickle-Coding** [comment]
Why do you want people to eat food from the floor?

**Comment by mc-oofert** [comment]
> Why do you want people to eat food from the floor?

I'm pretty sure this is some kind of fallacy

**Comment by zoomachina** [comment]
> instead of outright removing it, can we have like a 5 second rule? it doesn't make sense to be able to eat something that was sitting on the floor for however long and not get sick (potentially) from it

The 5 second rule is already in place, it has been that way from the moment this feature was added.

**Comment by the-orange-cow** [comment]
> > Why do you want people to eat food from the floor?
> 
> I'm pretty sure this is some kind of fallacy

It's called a loaded question.

Answering it realistically though, it's not that anyone wants people to eat off the floor.  It's that the way the game engine works makes it a relatively common occurrence for things to have contact with designated floor surfaces when moving things around unless an excess of precaution is taken.  By removing this anti-feature, it increases the quality of life for people by not punishing them for the shortcomings of the game engine.  Furthermore, the addition of this anti-feature seems to be regarded as and addition irritating busywork rather than actual rewarding depth.

**Comment by FlufflesTheDog** [comment]
Worth noting that *plants* being dirty isn't generally a problem. Processing them into meals removes the chance of sickness, so it only matters if you plan on eating the crops directly. Also and food that you craft will automatically be moved to nearby tables, which is nice.

I don't have a particularly strong opinion on the change, but I do think discouraging people from using the floor as food/pill storage is a good thing.

**Comment by LSommers** [comment]
Your pizza shouldn't be on the floor to begin with.
Nor your pills.
Yell at MDs to not do that, then find the syndie who bombed something near service and made all the shit fly off the tables and beat him to death. Then give him to the chef for new burgers.

(Raw produce getting dirty isn't a big issue as others said above, as it loses that when cooked.)

**Comment by the-orange-cow** [comment]
I frequently make things for the crew to eat as a botanist, such as medicine, so it is kinda pertinent for me to not have to use the plant bag literally every time I harvest something meant to be directly consumed.  It also helps because dipsticks will grab something off my counter then drop it on the ground, then someone else will put it back, leaving tainted produce for people to eat.

**Comment by Loafin34** [comment]
this is dumb. just let spray cleaner wash food/pills that it covers so u can wash ur plants/pills in bulk if u lag on clicking them. (also change corgi pinata to not become dirty, please)

**Comment by norsvenska** [comment]
yeah, i hate having to haul my load of pills over to a shower and back because someone deconstructed the table they were on for the extra 2 iron. good change.

**Comment by Bibarra** [comment]
As a chef player I appreciate this whenever a grav anomaly/space wind drags all my food off the table, ruining it. On the other hand, I don't appreciate this because it takes away my excuse to valid people who drop food on the floor.

**Comment by GuillaumePrata** [comment]
This feature is a push for people to act like believable human beings that don't go eating pills from the pills pile on the corner of medbay foyer.

Most of the complains about it being annoying can be fixed by themselves if someone argues for it, or it is just part of the game, like grav anomalies.

As Pickle said, I don't know why we would want people to go back to eating things from the floor, it was always such an ugly meta...

**Comment by Metekillot** [comment]
You can wash food with a fire extinguisher spray. You don't need to run to a sink to wash it.

**Comment by Dawnseer** [comment]
Also is it really THAT HARD to get 1 scrap of cloth to make a rag to clean with? You can literally just take a pen to one singular bandage and you have cloth for it. Or as mentioned, use a fire extinguisher. We have loads of water containers for refills anyway

**Comment by Exester509** [comment]
> Also is it really THAT HARD to get 1 scrap of cloth to make a rag to clean with? You can literally just take a pen to one singular bandage and you have cloth for it. Or as mentioned, use a fire extinguisher. We have loads of water containers for refills anyway

That's exactly the issue. There's an annoying mechanic that's neither engaging nor limiting, so it's unfun and irrelevant to balance, with its only justification being RP flavor that can be achieved by actually RPing instead of cramming dull, repetitive features in.

**Comment by GuillaumePrata** [comment]
> There's an annoying mechanic that's neither engaging nor limiting

And yet it killed the meta of pile of pills on the floor.

Successful PR IMO, changes the players into behaving better with the smallest of sticks that doesn't even punish anyone that will bother to spend a few seconds cleaning it up before consuming.

**Comment by DaCoolBoss** [comment]
I hate this trend of punishing players via code for doing things that are deemed 'wrong'. Who cares if people are letting pills touch floor tiles. People stopped letting them touch the floor not because it's super engaging and fun, they just don't want to deal with a heavy handed "you misbehaved so now you get to sit in medbay lobby for 15 minutes begging for carpet to cure your unfun disease". That's not a victory for the feature.

**Comment by Exester509** [comment]
> > There's an annoying mechanic that's neither engaging nor limiting
> 
> And yet it killed the meta of pile of pills on the floor.
> 
> Successful PR IMO, changes the players into behaving better with the smallest of sticks that doesn't even punish anyone that will bother to spend a few seconds cleaning it up before consuming.

The pills on the floor meta? Yeah, I guess. It's not like it was a big deal justifying the addition of an obnoxious mechanic that feels like a chore, though.

A much better implementation would have been a small mood debuff for consuming something from the floor. That makes sense, and is slightly punishing (as punishing as you'd expect from something so incredibly minor). Instead, we got space aids from eating a medicine pill that ended on the floor for god knows what reason.

And besides, if we're getting into "realism" why can we use the surgery tools more than once? That's even more gross and disgusting procedure than eating from the floor, and so is using monkey blood mixed with radioactive, mutagenic goo for transfusions. Realism should not, and has never been a justification for balance changes of that magnitude.

**Comment by GuillaumePrata** [comment]
I never brought up realism as I don't care and agree it is not a good angle.

Now professionalism of the employees is a good angle for me, ever since we had the PR I have seen the fridge and tables for pills be used a lot more.

With how diseases work right now, they are not even punishing, and mood debuffs are not a balance lever and will never be.

Outside of the character refusing, gagging or vomiting floor food/pills back, minor diseases are the only good balance lever we have, but I would take the above suggestions but when I code it moment.

**Comment by Exester509** [comment]
Indeed mood debuffs are not a balance lever and should never be. My point is that something so inherently related to how you RP in the game should not carry significant consequence, or else it can feel a lot like a chore.

My point about surgery gear still stands with professionalism. Using the same hemostat to pull out a rotting heart from a corpse and to heal someone's open wounds is very unprofessional and unhealthy, yet it would make medical a nightmare if it carried an actual consequence like floorpills do.

Having some way of telling eating a food or a pill from the floor is gross and unprofessional is something I'm all for, but I still think players, especially in LRP environments, should have the final say in whether or not they want to override that feeling for the sake of gameplay. Enforcing RP via code is just not my cup of tea.

**Comment by the-orange-cow** [comment]
> My point about surgery gear still stands with professionalism. Using the same hemostat to pull out a rotting heart from a corpse and to heal someone's open wounds is very unprofessional and unhealthy, yet it would make medical a nightmare if it carried an actual consequence like floorpills do.

Please don't give c*ders ideas, med has been beaten down enough.

**Comment by PKPenguin321** [comment]
Good PR, played botanist yesterday and it's really stupid that everything I grew got stinklines within seconds of being harvested

**Comment by Loafin34** [comment]
> I hate this trend of punishing players via code for doing things that are deemed 'wrong'. Who cares if people are letting pills touch floor tiles. People stopped letting them touch the floor not because it's super engaging and fun, they just don't want to deal with a heavy handed "you misbehaved so now you get to sit in medbay lobby for 15 minutes begging for carpet to cure your unfun disease". That's not a victory for the feature.

how else are you gonna make people not dump a pile of pills on the ground instead of the smartfridge? literally nobody changes minor things even if SOP says so because barely anyone follows SOP. just buff or nerf shit that would guide people to do things that are deemed "alright". don't dump your chembag of pills, just have pill bottles on the ground, or pill bags.

**Comment by GuillaumePrata** [comment]
> Enforcing RP via code is just not my cup of tea.

But sadly or not, this is the most efficient way to uphold good player behavior.

Think of how much effort it would take for the administration to uphold not leaving pills and food on the floor, for the crew to strive to be professionals, for admins to uphold the rules in an equal manner for everyone that breaks this new RP rule.

Instead we added a minor annoyance code wise and the problem was gone, and new players that joined never had to even see the old ugly meta so they are more likely to repeat the good behavior.

Coding RP into the game might not be liked by everyone, but it is certainly the most efficient way to push us into better behavior.

**Comment by Exester509** [comment]
> > Enforcing RP via code is just not my cup of tea.
> 
> But sadly or not, this is the most efficient way to uphold good player behavior.
> 
> Think of how much effort it would take for the administration to uphold not leaving pills and food on the floor, for the crew to strive to be professionals, for admins to uphold the rules in an equal manner for everyone that breaks this new RP rule.
> 
> Instead we added a minor annoyance code wise and the problem was gone, and new players that joined never had to even see the old ugly meta so they are more likely to repeat the good behavior.
> 
> Coding RP into the game might not be liked by everyone, but it is certainly the most efficient way to push us into better behavior.

There is no need to force people not to drop pills on the floor. If you need them in the smartfridge (say, it's an important medicine that needs to be available to the crew) you have the most useful mechanic in the game, the "say" verb.

That aside, SOP is not important to the game and has never been, enforcing it through code is massive overkill.

**Comment by GuillaumePrata** [comment]
> There is no need to force people not to drop pills on the floor. If you need them in the smartfridge (say, it's an important medicine that needs to be available to the crew) you have the most useful mechanic in the game, the "say" verb.

So because some players are too lazy to spend 5 seconds cleaning food that accidentally touched the floor through in game accidents like grav anomalies, we have to go use the "say verb" to beg people to act professional instead of using the smallest code sticks.

Tell me, which one takes more effort?

It feels like people just want to smooth out the smallest edge they have to deal with.

**Comment by PKPenguin321** [comment]
2019 code had stink lines but for people instead of food and it got removed for being terrible and its striking how similar the discussion is here

**Comment by GPeckman** [comment]
> So because some players are too lazy to spend 5 seconds cleaning food that accidentally touched the floor through in game accidents like grav anomalies, we have to go use the "say verb" to beg people to act professional instead of using the smallest code sticks.
> 
> Tell me, which one takes more effort?
> 
> It feels like people just want to smooth out the smallest edge they have to deal with.

Whether or not the players are lazy is irrelevant if this isn't a good feature in the first place. And it's not. It's pointless busywork that adds nothing to the game, just like the surgery tool example that you've ignored.

**Comment by Dawnseer** [comment]
There's only busywork if you can't be arsed to place the goods on a table. 'Muh grav anomaly' the point of a grav anomaly is to mess up items near it. If you're so allergic to it, babyproof your room with windoors or railings or something. As for if it's pointless and if it's good, that's subjective, and in my eyes there's a point and it's good.

**Comment by GuillaumePrata** [comment]
> Whether or not the players are lazy is irrelevant if this isn't a good feature in the first place. And it's not. It's pointless busywork that adds nothing to the game

I already brought up that this feature, which is the smallest stick we could use to push for better behavior, worked.

If the goal of the feature was to kill the ugly pile of food/pills on the floor, it achieved that and that was a really good goal to strive for.

> just like the surgery tool example that you've ignored.

I completely ignored this because this is not a feature in game, I doubt it will be added and it is not a good comparison to this PR as they would have complete different goals. If you want this to be discussed, go make a PR about it so I can say how it would affect the game negatively.

**Comment by GPeckman** [comment]
> There's only busywork if you can't be arsed to place the goods on a table. 'Muh grav anomaly' the point of a grav anomaly is to mess up items near it. If you're so allergic to it, babyproof your room with windoors or railings or something. As for if it's pointless and if it's good, that's subjective, and in my eyes there's a point and it's good.

Grav anomalies aren't a minor annoyance, they're meant to be a lethal hazard if you get too close to them. And anyways, it's much more impactful for botanists, who often like to cross-breed plants with special chems and then put them out for the station to use. They have to be extra careful when trying to harvest the plants, in addition to making sure that atmos/grav anomalies/whatever don't move the items around. 

> I already brought up that this feature, which is the smallest stick we could use to push for better behavior, worked.
> 
> If the goal of the feature was to kill the ugly pile of food/pills on the floor, it achieved that and that was a really good goal to strive for.

People don't care about piles of pills on the ground. It's the same as people not caring that everyone does surgery without anesthetic, or not caring that their characters never need to sleep. Realism (or 'professionalism' if you want to call it that instead) is not in and of itself fun, and this is a case where it very much isn't.

> I completely ignored this because this is not a feature in game, I doubt it will be added and it is not a good comparison to this PR as they would have complete different goals. If you want this to be discussed, go make a PR about it so I can say how it would affect the game negatively.

Let's use another example, then. PKPenguin mentioned the old hygiene mechanic, where if you didn't shower frequently enough your character would get the stink overlay and start emitting miasma gas. You can make the same 'professionalism' argument in favor of hygiene mechanics, but it was removed for being unfun and rather unpopular with the playerbase.

**Comment by GuillaumePrata** [comment]
> People don't care about piles of pills on the ground. It's the same as people not caring that everyone does surgery without anesthetic, or not caring that their characters never need to sleep. Realism (or 'professionalism' if you want to call it that instead) is not in and of itself fun, and this is a case where it very much isn't.

But people do, look at all the people defending keeping the feature here.

The goal doesn't need to be realism, another good effect of this PR is that people check the chem fridge a lot now, it is the standard for public medicine to be there, how many times have you seen people complain that the vaccine was done and in the fridge, but people still broke into the pharmacy because they didn't see a pile of pills anywhere and "Doctors are not doing their job!!"

We literally punished players that acted in a profisional manner before this change and we inversed that.

> Let's use another example, then. PKPenguin mentioned the old hygiene mechanic, where if you didn't shower frequently enough your character would get the stink overlay and start emitting miasma gas.

What was the goal of that feature? They don't align with this one in any way, shape or form.

You are guys are just mixing 2 features with the word hygiene by that alone, not for their goals or the impact it has in the game.

It is like bringing emitters into a conversation about laser carbine balance because the emitters shoot lasers too ignoring that the uses are so far from one another.

**Comment by CCC23** [comment]
> Why do you want people to eat food from the floor?

hongry

**Comment by CCC23** [comment]
Please can we just make the floor pill viruses non transmissable PLEASE I dont want to be catching super aids cause billy ate 30 dirty floor pills and has given me a disease that someone thought would be funny to add

**Comment by GPeckman** [comment]
> But people do, look at all the people defending keeping the feature here.
> 
> The goal doesn't need to be realism, another good effect of this PR is that people check the chem fridge a lot now, it is the standard for public medicine to be there, how many times have you seen people complain that the vaccine was done and in the fridge, but people still broke into the pharmacy because they didn't see a pile of pills anywhere and "Doctors are not doing their job!!"
> 
> We literally punished players that acted in a profisional manner before this change and we inversed that.

The chem fridge thing is a better argument, and I might be able to see the merits of a pill-only version of floor stuff. But like I said, it affects botanists just as much if not more than it affects medbay. There isn't a public smart-fridge mapped in on most stations as far as I'm aware, and even if there was it wouldn't work nearly as well. Unlike with vaccines, most people will spot the plants by chance while passing by, and putting them in a smart-fridge would make the plants far less visible even if there was one mapped in.

> What was the goal of that feature? They don't align with this one in any way, shape or form.
> 
> You are guys are just mixing 2 features with the word hygiene by that alone, not for their goals or the impact it has in the game.
> 
> It is like bringing emitters into a conversation about laser carbine balance because the emitters shoot lasers too, while ignoring that the uses are so far from one another.

The hygiene similarity is pure coincidence. No, I'm drawing a similarity between the two based on your own professionalism argument:

> Now professionalism of the employees is a good angle for me, ever since we had the PR I have seen the fridge and tables for pills be used a lot more.

Putting stuff on tables or in fridges instead of on the floor is good because it's professional. Is making your character shower regularly not also professional?

**Comment by ExcessiveUseOfCobblestone** [comment]
> I hate this trend of punishing players via code for doing things that are deemed 'wrong'. Who cares if people are letting pills touch floor tiles. People stopped letting them touch the floor not because it's super engaging and fun, they just don't want to deal with a heavy handed "you misbehaved so now you get to sit in medbay lobby for 15 minutes begging for carpet to cure your unfun disease". That's not a victory for the feature.

the punishment being heavyhanded is a worthwhile discussion point, the idea that code isnt suppose to punish/reward behavior they want to reinforce is silly.

**Comment by MrMelbert** [comment]
FTR I'm against outright removal but I would really like for the grace period to be upped (30 seconds, 1 minute maybe) and also for it to be less stupid (a fire extinguisher is literally all you need to make it redundant)

**Comment by Jacquerel** [comment]
Enough maintainers have said "don't do this, but you can change it some other way" that I don't want someone to merge it by accident

**Comment by GuillaumePrata** [comment]
> Putting stuff on tables or in fridges instead of on the floor is good because it's professional. Is making your character shower regularly not also professional

You're mixing what I meant by professional as it is a word with multiple meanings.

What I mean by professional was from the "be a believable human being" angle as I also said above, dropping pills and food on the floor because clicking the bag takes a whole second less than click dragging the bag into a table is something that only happens in our game and would make no sense IRL.

So people optimize the RP out of the game to save a second, which I think is a bad look for a RP game.

If we added that shower PR back now, why would it be good for the game? I bet you can't make an argument that aligns with the goals of this feature outside of "Hygiene == professional".

**Comment by iamcooldan** [comment]
I feel that it ISN'T optimizing to remove rp, the leaving of pills and patches on the floor is a so that people can identify that useful chems have been made in a fast and obvious manner, so someone with a lot of bruising doesn't have to deal with the guesswork of chem actually being useful and doing their job. In much the same way that people in actual jobs have visible tables for promotions, or signs. This is to improve the experience of those coming in to medbay to both ensure the work you made is used properly and that medbay isn't overwhelmed by people who are hurt but not dead, who only need a quick top up from the stuff you made readily available.

**Comment by mc-oofert** [comment]
honestly fuck this "believable human being" bullshit this is simply an annoying feature that shouldn't be been added in in the first place because mini fridges remain unused and people just dump pills on the floor regardless and by god are there a lot of fallacies being used here

**Comment by ExcessiveUseOfCobblestone** [comment]
> I feel that it ISN'T optimizing to remove rp, the leaving of pills and patches on the floor is a so that people can identify that useful chems have been made in a fast and obvious manner, so someone with a lot of bruising doesn't have to deal with the guesswork of chem actually being useful and doing their job. In much the same way that people in actual jobs have visible tables for promotions, or signs. This is to improve the experience of those coming in to medbay to both ensure the work you made is used properly and that medbay isn't overwhelmed by people who are hurt but not dead, who only need a quick top up from the stuff you made readily available.

you can still "floor pill" it just has to be on a table though, no?

**Comment by DaCoolBoss** [comment]
When dirty food was added two things stuck out to me.

1. Players don't always read things on the floor as "on the floor" if that makes sense. When you're playing Gauntlet or Nethack, a roast chicken lying in an unoccupied tile isn't just lying on the ground it's vaguely "in this area".
2. We already *have* this system. Food rots on the ground and dissolves into ants. The only thing the five seconds rule does is punish you almost immediately instead of in a minute or two.

**Comment by Dawnseer** [comment]
> you can still "floor pill" it just has to be on a table though, no?

... So not a floor pill?

**Comment by GuillaumePrata** [comment]
> I feel that it ISN'T optimizing to remove rp, the leaving of pills and patches on the floor is a so that people can identify that useful chems have been made in a fast and obvious manner

They can do the same but just placing it on a table, most medbay lobbies have a table that could be used for that, and so most places that you would give food away.

Just a bit ahead you comment yourself about people using tables to get others' attention...

The only benefit of floor pills instead of tables (which you yourself said tables are good for visibility) is lazy chemists/doctors saving a few seconds.

**Comment by GuillaumePrata** [comment]
> honestly fuck this "believable human being"

Imagine striving to improve ourselves and others to act better in the Multiplayer Roleplaying Game.

>  because mini fridges remain unused and people just dump pills on the floor regardless

Disagree, I see them used a lot more for the pharmacy, but without data this argument branch is pointless anyway.

**Comment by iamcooldan** [comment]
"improve ourselves" my god dude, you really don't accept anyone else having a different playstyle, huh.

**Comment by GuillaumePrata** [comment]
> you really don't accept anyone else having a different playstyle

If it is a playstyle, sure, it is part of the experience.

Now if you think that optimizing yourself a few seconds by throwing pills on the floor is worth being called a playstyle... okay?

**Comment by iamcooldan** [comment]
again, its not always about convenience. its about visibility, a different form of organization, or even with people from other codebases, habit. Just because people are not changing their experience to the experience YOU want doesn't mean that it is a BAD experience. This is a good pr, you just want to force people to play the game as you want to see it.

**Comment by GuillaumePrata** [comment]
> its not always about convenience. its about visibility, a different form of organization

And you said above that people use tables to call attention. We can just have both, you don't need to floor pill to be organized...

> This is a good pr, you just want to force people to play the game as you want to see it

Then I can argue the same, you want people to leave pills on the floor!!1!

This is not a point of discussion of the PR anymore, just trying to paint me as a bad guy that wants to force his view on others.

**Comment by iamcooldan** [comment]
if you want people to leave things on tables, ask them, or do it yourself. no need to defend a genuinely abysmal decision to lower the quality of peoples playing experiences with arbitrary punishment.

**Comment by ExcessiveUseOfCobblestone** [comment]
> > you can still "floor pill" it just has to be on a table though, no?
> 
> ... So not a floor pill?

"floor pill" being code for pill you can see as an item in the world and not a text entry in a fridge, thats why there's quotes you stinker

**Comment by Dawnseer** [comment]
But that's just a pill

**Comment by GPeckman** [comment]
> What I mean by professional was from the "be a believable human being" angle as I also said above, dropping pills and food on the floor because clicking the bag takes a whole second less than click dragging the bag into a table is something that only happens in our game and would make no sense IRL.

That... doesn't actually change my argument at all. None of the characters ever showering is just as unbelievable as floor pills are, if not moreso.

> If we added that shower PR back now, why would it be good for the game? I bet you can't make an argument that aligns with the goals of this feature outside of "Hygiene == professional".

It would be bad for the game because it would add nothing but pointless busywork. You know, the same thing I said about the floor pill PR!

**Comment by ExcessiveUseOfCobblestone** [comment]
> But that's just a pill

i hate you

**Comment by ExcessiveUseOfCobblestone** [comment]
Think really this mechanic should be a midway point for ants to let you know the food is approaching becoming a real nuisance, rather than an imminent frick you if you forgot your plant/pill bag.

**Comment by GuillaumePrata** [comment]
> None of the characters ever showering is just as unbelievable as floor pills are

This is going nowhere so I will just say it a last time, pill floors exist because people optimize the RP out of the game to save a few seconds, because they legit don't know you can click drag a chem bag into a table or because "no one uses the fridge".

The PR this is trying to revert pushed us to fix all these 3 issues and was quite successful in my experience.

> It would be bad for the game because it would add nothing but pointless busywork. You know, the same thing I said about the floor pill PR!

What I brought up above, and not for the first time either.

**Comment by MTandi** [comment]
What's the fuss? I just thought that it would make some funny interaction, when someone ate shit from the floor and then started vomiting stars. Cleaning mechanic is there mostly for RP, as the diseases are harmless. Isn't it fun that you can wash a burger in a sink to sanitize it?

The chance that you even get sick is 1/10 afaik. The vomit doesn't stun, tritium volume is minor and if many find carpellosis annoying, then just make it non-transmissive via blood (biting).

**Comment by MTandi** [comment]
> What's the fuss? I just thought that it would make some funny interaction, when someone ate shit from the floor and then started vomiting stars. Cleaning mechanic is there mostly for RP, as the diseases are harmless. Isn't it fun that you can wash a burger in a sink to sanitize it?
> 
> The chance that you even get sick is 1/10 afaik. The vomit doesn't stun, tritium volume is minor and if many find carpellosis annoying, then just make it non-transmissive via blood (biting) and/or remove the teleportation.

**Comment by MTandi** [comment]
I believe this PR also removes the food decomposition (stink lines) since germ sensitive component is used for both floor diseases and decomposition.

**Comment by Jacquerel** [comment]
> What's the fuss? I just thought that it would make some funny interaction, when someone ate shit from the floor and then started vomiting stars. Cleaning mechanic is there mostly for RP, as the diseases are harmless. Isn't it fun that you can wash a burger in a sink to sanitize it?
> 
> The chance that you even get sick is 1/10 afaik. The vomit doesn't stun, tritium volume is minor and if many find carpellosis annoying, then just make it non-transmissive via blood (biting) and/or remove the teleportation.

Yeah it's fun and most of these reactions are incredibly overblown.

**Comment by iamcooldan** [comment]
jacquerel, I can confidently say that the floor diseases pr is one of my most hated prs, right after stuff on walls falling down when deconstructed. It adds nothing of value to the game, it isn't fun, and its a massive sidequest to get the most common one cured because it requires the rarest mineral crushed up which has its own annoying negative effects, coughing up tritium for something as simple as eating food you forgot to check is basically codergrief in my eyes, and carpellosis? having to straight up eat carpet is disgusting for non-moth players. It's not overblown, this lowers the enjoyment of the game for both me and others who strongly agree it should be removed. Just look at the votes up top, 31 for the revert, only 9 against.

**Comment by MTandi** [comment]
Wouldn't making the cures something more common resolve your issue?

These cures were based on just puns. You vomit space - drink bluespace. Need to tame your inner carp - carp-pet.

**Comment by DaydreamIQ** [comment]
This mechanic has always made cooking a pain in the ass, if you're holding a beaker and you want to say...make bread. The second it mixes together it'll output the dough directly on the floor below you which if you aren't quick enough means you can probably end up contaminating your food. As a chef this isn't too bad but as a service borg its not even remotely fun to deal with. That and when it comes to floorpills people just use patches now to circumvent that issue

**Comment by iamcooldan** [comment]
> These cures were based on just puns. You vomit space - drink bluespace. Can replace with **Space Cleaner**. Need to tame your inner carp - carp-pet. Can change this to **Carpotoxin**. Gastritium's cure - firefighting foam can be replaced with **Milk**. The fat in milk can aggravate acid reflux and is good against heartburn.
so drinking soap is disgusting and bad for you, that one is literal poison, and it doesnt change the fact you cough up literal tritium. still awful, this isn't something that needs to be FIXED, when a lot of people are more than happy to just see it outright REMOVED. if its overall detrimental to the game experience there are not enough reasons i'm seeing here to keep it, modified or not.

**Comment by ElGitificador** [comment]
this feature is annoying and doesnt add nothing positive to the actual gameplay. never felt needed, never liked it

**Comment by Jacquerel** [comment]
Nobody wants to merge this and we made floor diseases easier to cure instead

**Pull request closed without merging**
