### PR TITLE
GOONCHEM 6 PART 1: Nuke Ops and Bioterrorism

### PR DESCRIPTION
**Pull request by Iamgoofball**
DNM

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Basically the dealio with this is this is from that goonchem pr that cheridan requested I make atomic

**Comment by PKPenguin321** [comment]
despite me not knowing what a single one of the new chems in the chemsprayer are, this still looks cool and mustard gas looks cool :+1:

**Comment by Dorsisdwarf** [comment]
Issue: mustard gas is not a neurotoxin, it works by screwing with your DNA and causing PCD, not by interfering with nerves.

Oh, and mustard gas is horrific in the eyes, and should blind you.

**Comment by Profakos** [comment]
Forcing screams like "MAKE IT END" into the player's mouth is a bit obnoxious.

**Comment by Miauw62** [comment]
>feature freeze

**Comment by Iamgoofball** [comment]
@Miauw62 i recall asking cheridan if it was okay to do this back when the freeze got announced, as I didn't have time to split it up

if anything i'll be putting up the other 2-3 parts regardless and I'll have them just be reopened when the freeze ends

**Comment by Miauw62** [comment]
man do i have to ping @cheridan about everything

**Comment by RemieRichards** [comment]
@Miauw62 Cheri doesn't respond to github notifications.

**Comment by Cheridan** [comment]
hi

**Pull request closed without merging**
