### PR TITLE
Eris air alarm sprites

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
imageadd: Ports eris air alarm sprites
/:cl:

rotated1
rotated2

unrotated1
unrotated2

If you want, I can remove the rotated sprites.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
These are... not good.

**Comment by Bluespace** [comment]
These aren't good at all. They're awful.

**Comment by MoreRobustThanYou** [comment]
@ChangelingRain any way to make them better?

**Comment by Bluespace** [comment]
The current sprites are both well done and fit incredibly well to the visual design of the game, I don't see any reason to replace them, sorry.

**Comment by MoreRobustThanYou** [comment]
How come the APCs were changed, then?

**Comment by Bluespace** [comment]
I assume not a lot of people saw the PR. There was even some pushback in the PR until oranges merged it. I've opened a thread on the forums to discuss the APC changes and hopefully something comes of that.

**Comment by lzimann** [comment]
These managed to be even worst than chairs and apcs, holy shit this is ugly.

**Comment by MoreRobustThanYou** [comment]
Yeah, honestly. They are. I'd just rather see the air alarms that already exist restyled to the APCs style/colors.

**Pull request closed without merging**
