### PR TITLE
*snap* this emoij pr is going in my cringe comp

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
add: many emojis
/:cl:

Reason: emojis are cute and pizzaz your deadchat/ooc

iconbot is to do the magic

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
where'd you get them

**Comment by ExcessiveUseOfCobblestone** [comment]
I edited current sprites to the emoji size.

**Comment by ExcessiveUseOfCobblestone** [comment]
> merge conflicts on my pr

https://www.youtube.com/watch?v=Ffytnbix07U

**Comment by Qustinnus** [comment]
keep your master branch updated you loony

**Comment by ExcessiveUseOfCobblestone** [comment]
let me fix this stupid thing and reee PR

**Pull request closed without merging**
