### PR TITLE
Remove stray debug message in coin suicide

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by CitrusGender** [comment]
> ADMIN LOG: coinflip landed on heads which is 1 in sideslist


thanks debug logs

**Review by SpaceManiac — APPROVED** [review]

**Comment by MrDoomBringer** [comment]
wtf
literally why tf did i write that line

**Comment by Nabski89** [comment]
For testing purposes then forgot to remove it?

**Comment by MrDoomBringer** [comment]
@Nabski89 shit u prolly right

**Pull request merged**
