### PR TITLE
Removes Gasp Noises

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

title

## Why It's Good For The Game

It might be me, but other people have said so too, the new gasp noises are incredibly obnoxious. 

## Changelog
:cl:
sounddel: gasp noises are no longer a thing
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
i'd rather have it so that gasps only happened above 30 oxygen damage or so

**Comment by wesoda25** [comment]
I mean its less about the frequency or ease of occurrence and more the fact that they make me want to play with no sound.

**Comment by carlarctg** [comment]
that's fair, i grew used to them but they never stopped being more than a nuisance too

**Comment by Dorsisdwarf** [comment]
God finally

**Comment by MMMiracles** [comment]
>making women have the only audible gasp

🤔

**Comment by wesoda25** [comment]
😈

**Comment by Mickyan** [comment]
I think this is a good opportunity to point out that sound design needs to go hand in hand with the rest of the game's presentation

Which is to say, don't pair overly detailed and realistic sound effects with a crudely drawn pixel art aesthetic, it's going to be jarring and awkward

**Comment by wesoda25** [comment]
This PR is actually a political commentary on cobby chem

**Comment by spessbandit** [comment]
this pr turns it into fetish content

**Comment by HomocidlePancakes** [comment]
>TG gasps

OH GOD I AM GONNA COOM, I AM COOOOOMING AAAAAAAAAAAAAAAAAAA. 

Good change. They sound more like fake orgasms.

**Comment by Ty-the-Smonk** [comment]
Add a option to mute them

**Comment by OverlyGeneric** [comment]
i'm pretty sure some of them are from stock sound websites but some of them do sound like they are from pornographic films.

**Comment by fludd12** [comment]
In the future all gasps will be taken from random 0.3 second samples of this video: https://youtu.be/fSM_SO0GIBc

**Comment by wesoda25** [comment]
Better than what we have now tbh

**Comment by Detective-Google** [comment]
Might as well remove them entirely rather than leaving in only one

**Comment by dee-dubya** [comment]
Get rid of all of them or don't bother. Seems silly to just leave one in for one gender only.

**Comment by wesoda25** [comment]
done

**Comment by ayebee123** [comment]
> In the future all gasps will be taken from random 0.3 second samples of this video: https://youtu.be/fSM_SO0GIBc

the fact that this feels like it would be pretty decent for gasp sounds terrifies me

**Comment by PKPenguin321** [comment]
Yeah that youtube video is unironically a good resource for gasping sounds

**Pull request merged**
