### PR TITLE
Adds devil spawning event.

### PR DESCRIPTION
**Pull request by lordpidey**
This adds a new event, which will b̶e̶ ̶i̶n̶c̶r̶e̶d̶i̶b̶l̶y̶ ̶r̶a̶r̶e̶ ̶o̶n̶ ̶i̶t̶'̶s̶ ̶o̶w̶n̶ ̶(̶n̶a̶p̶k̶i̶n̶ ̶m̶a̶t̶h̶ ̶s̶a̶y̶s̶ ̶a̶b̶o̶u̶t̶ ̶o̶n̶c̶e̶ ̶e̶v̶e̶r̶y̶ ̶4̶8̶ ̶h̶o̶u̶r̶s̶)̶,̶ ̶b̶u̶t̶ ̶w̶i̶l̶l̶ ̶a̶l̶s̶o̶ add a more fair way for admins to create devils.

C̶o̶n̶s̶i̶d̶e̶r̶ ̶t̶h̶i̶s̶ ̶a̶s̶ ̶D̶N̶M̶ ̶u̶n̶t̶i̶l̶ ̶#̶1̶8̶5̶2̶0̶ ̶i̶s̶ ̶m̶e̶r̶g̶e̶d̶,̶ ̶a̶s̶ ̶1̶8̶5̶2̶0̶ ̶c̶o̶n̶t̶a̶i̶n̶s̶ ̶n̶u̶m̶e̶r̶o̶u̶s̶ ̶d̶e̶v̶i̶l̶ ̶f̶i̶x̶e̶s̶,̶ ̶a̶n̶d̶ ̶u̶n̶t̶i̶l̶ ̶t̶h̶a̶t̶ ̶t̶i̶m̶e̶,̶ ̶d̶e̶v̶i̶l̶s̶ ̶s̶h̶o̶u̶l̶d̶ ̶r̶e̶m̶a̶i̶n̶ ̶P̶U̶R̶E̶L̶Y̶ ̶a̶d̶m̶i̶n̶f̶u̶c̶k̶e̶r̶y̶ ̶o̶n̶l̶y̶.̶
18520 is merged.

Merge token:  #18143

### CODE REVIEW

**Comment by Boredone** [comment]
Since it can happen as soon as the round starts, it'll actually happen more often, as very few other events can happen that early.
However the most notable one has a weight of 200 and is mostly so things arn't guaranteed to be event filled, so will still be rare.

**Comment by lordpidey** [comment]
Huh.  Well even if there's just it and one other event with 200 weight, it would still be 21 hours between runs on average.

**Comment by Core0verload** [comment]
Don't like it. Devil is better as rare admin spawn.

**Comment by Shadowlight213** [comment]
This is an absolutely terrible idea. Other random event antags that can completely hijack the round like xeno or swarmer have a lengthy delay. Hell, those antags don't force a round end like devil does either. (since ascending triggers a 1 minute shuttle.)
Imagine nuke ops reaching the station and everyone has spells/devil has ascended and forced an early shuttle letting the crew escape.

**Comment by lordpidey** [comment]
Aright, I'll remove the random chance of it happening, You have a good point Shadow.

I thought that blobs could force a shuttlecall?

**Comment by Core0verload** [comment]
Set `max_occurrences = 0` to remove it from random spawn. Weight = 0 for some reason doesn't do this.

**Pull request merged**
