### PR TITLE
Refactors lizard fake canned food into real canned food

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

/obj/item/food/canned_jellyfish, /obj/item/food/desert_snails, and /obj/item/food/larvae are now all /canned subtypes. All this means is that to eat them, you use them once, and now they drop an empty tin rubbish item.

## Why It's Good For The Game

Making fake false versions of real types that exist is such a pet peeve of mine, we recently had a bug from it where the snails would go bad. But even with that fixed you're just chomping the container of snails and it's not the same behavior as all the other cans
grumgrugmrg I FIXED IT.

## Changelog
:cl:
refactor: Lizard related canned food now acts like canned food
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
and for those who are wondering...
1. doesn't change any steps to recipes
2. it looks like this when opened
image

**Comment by Pumpkinoe** [comment]
Food

**Review by san7890 — CHANGES_REQUESTED** [review]
image

lolwut

**Comment by tralezab** [comment]
> image
> 
> lolwut

oh yea my bad

**Comment by coiax** [comment]
Thank you for doing what I couldn't. 🙇

**Pull request merged**
