### PR TITLE
Removes gender restrictions from socks

### PR DESCRIPTION
**Pull request by Incoming5643**
Player request. Privilege checked thoroughly. They were pretty damn arbitrary to begin with.

:cl:
tweak: Removed gender restrictions from socks.
/:cl:

### CODE REVIEW

**Comment by Cebasiz** [comment]
t-thanks

**Comment by Bawhoppen** [comment]
~

**Comment by MMMiracles** [comment]
Remove gender restrictions on underwear so I can roleplay as the burly HoS in lingerie.
.

**Comment by Incoming5643** [comment]
I can see why there's gender restrictions on roundstart underwear, randomly rolling a character only to find out he's wearing a babydoll under his shirt is a little silly.

For the record you can already use the dresser to put on normally unavailable underwear.

**Comment by MMMiracles** [comment]
Its the 26th century, we allow lizards in the work place. No place to judge if a man feels the need come to work in silk.

**Comment by Bawhoppen** [comment]
fucking still cant believe we legalized those fucking liggers

**Comment by tkdrg** [comment]
Now I can finally make a cute trap character

**Comment by Anonmare** [comment]
I MEAN
C'MON PEOPLE
IT'S 2015

**Comment by Chocobro** [comment]
@tkdrg i already made one years ago friend
get with the program

**Pull request merged**
