### PR TITLE
adds a new wire to mecha wires + fixes mecha shock wire

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

the shock wire if cut shocks you
adds a new wire that if cut makes the mecha pick a random weapon that it will shoot you with, or punch if no weapons were attached
if pulsed, it will do the same if you pulsed it yourself with a multitool but with a signaler it will pick a target in range
also this wire doesnt work if piloted no powergaming for you

## Why It's Good For The Game

stealing a mecha right now is extremely easy, mauler included, all you need is a wirecutter and screwdriver you dont even need insuls
theres little risk to that even if the shock wire actually worked
with the additional risk of getting shot you now should think twice before you should try your luck stealing an efficient killing tool

## Changelog
:cl:
add: mecha wire that shoots you or anyone nearby if pulsed or cut
fix: mecha shock wire shocks you
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
The launch wire won't allow mechs to shoot behind themselves (Clarke excluded), right?

**Comment by mc-oofert** [comment]
> The launch wire won't allow mechs to shoot behind themselves (Clarke excluded), right?

it does allow them to fire behind themselves, however this wire only works if the mecha is not piloted

**Comment by SmArtKar** [comment]
Does this respect weapon cooldowns or can you spam the wire to turn shotguns into miniguns?

**Comment by Eronymun** [comment]
I like how this effectively lets you turn your mech into a stationary turret.

**Comment by mc-oofert** [comment]
> Does this respect weapon cooldowns or can you spam the wire to turn shotguns into miniguns?

It should

**Comment by githubuser4141** [comment]
Shouldn't the shooting respect mecha direction?  There's no reason it should violate directional rules as it can't do that while active, and mechs stationary have a code set direction which is supposed to resemble the sprite but hasn't been updated in a while - the original gygax sprite had the stationary sprite pointing backwards.

**Comment by zxaber** [comment]
> Shouldn't the shooting respect mecha direction? There's no reason it should violate directional rules as it can't do that while active, and mechs stationary have a code set direction which is supposed to resemble the sprite but hasn't been updated in a while - the original gygax sprite had the stationary sprite pointing backwards.

Unpiloted mechs only have one direction sprite, and thus always point south.

**Comment by githubuser4141** [comment]
> > Shouldn't the shooting respect mecha direction? There's no reason it should violate directional rules as it can't do that while active, and mechs stationary have a code set direction which is supposed to resemble the sprite but hasn't been updated in a while - the original gygax sprite had the stationary sprite pointing backwards.
> 
> Unpiloted mechs only have one direction sprite, and thus always point south. So you'd just game the system by hacking mechs from any other side. I think wirehacking to steal a mech remains dumb, but if we're going to have it, some extra risk is a good idea.

Yeah, the direction is set to what it is.... That'd be the idea, because having a mech magically hone in on the person hacking makes no sense, it should require some effort from the pilot, by parking the mech in a way that it's only accessible from one side.

**Comment by zxaber** [comment]
If you could just cheese the direction, the feature would be meaningless.

**Comment by githubuser4141** [comment]
> If you could just cheese the direction, the feature would be meaningless.

Nope, the pilot would have to coax the direction by parking against a wall or build walls near the parked mech

**Pull request merged**
