### PR TITLE
Hotfix for Blob mulligan rounds not ending | Nuke codes being given in times of peace | AI desiring to blow up the station

### PR DESCRIPTION
**Pull request by Incoming5643**
WHOOOOOPS :fried_shrimp: 

For those keeping track, I already fixed this, but blob was broken twice for extra security

### CODE REVIEW

**Comment by RandomMarine** [comment]
Does the automatic nuke code message still happen long after the blob's dead?

**Comment by Incoming5643** [comment]
Nice catch I had forgot about that feature

**Comment by Incoming5643** [comment]
Hahaha, wow this is a bigger problem than I thought

**Comment by AndroidSFV** [comment]
Another small issue, which isn't directly tied to your PR, is that send_intercept(2) for blob changed the station's nuke's code. Not that it wouldn't be an edge case where this would become an issue, but the potential for a consistency issue within a round does exist.

**Pull request merged**
