### PR TITLE
Honk staff now lube slips.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

The honk staff no longer stuns. It now slips people on hit.

## Why It's Good For The Game

It's one of the best lavaland items and there is absolutely no challenge in getting it. And it has the same unfun components as tasers.

## Changelog
:cl:
balance: The staff of the honkmother now slips people. Honk.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
The staff of the honkmother is good, but also can't be put away without giving up your backpack slot and also paints a giant "robust me and steal my cool staff" sign on your back. It's fine as it is.

**Comment by 4dplanner** [comment]
I don't know why you think a 300 range taser that self recharges and goes through walls is overpowered, unnecessary PR

**Comment by Daxxed** [comment]
Just remove the garbage ruin with it wew
Or lock it behind a difficult boss
Don't really like this solution

**Comment by datorangebottle** [comment]
This is a good change. I like it.



> Just remove the garbage ruin with it wew
> Or lock it behind a difficult boss
> Don't really like this solution

You were literally JUST complaining about it in another PR buddy. This change makes it into the meme item it was meant to be while not removing it from the game outside of admin intervention, while also not giving the c*ders an excuse to add those super fucking creepy clown megafauna sprites to the actual game.

**Comment by Shadowflame909** [comment]
add an admin only version that still stuns

Admin only versions of items are bretty cool

**Comment by Daxxed** [comment]
> You were literally JUST complaining about it in another PR buddy. This change makes it into the meme item it was meant to be while not removing it from the game outside of admin intervention, while also not giving the c*ders an excuse to add those super fucking creepy clown megafauna sprites to the actual game.

I would much rather fight a fancy boss for fancy stick.
Although the staff is overpowered, my main issue is that one can get it simply by marching in there and that the ruin takes up half of lavaland.
After this PR we will have yet another pointless HUGE ruin that will be simply walked past like most.
Would much rather fight the drake that would have spawned instead of the ruin, and then MAYBE get lucky and have fun, assuming I survive the fight.

I asked to remove the garbage ruins, not make them worse

As you think hierophant is so hard, why don't we make hiero drop it on top of the other staff ? /s

**Comment by datorangebottle** [comment]
> Although the staff is overpowered, my main issue is that one can get it simply by marching in there and that the ruin takes up half of lavaland.

Except the clown ruin isn't nearly as big as some of the other ruins- the xeno, cult, and sloth especially. There are larger ruins that are way less fun than what the HONK ruin provides. Also, making the staff not overpowered in the slightest minimizes the problem of it being easy to get.

> After this PR we will have yet another pointless HUGE ruin that will be simply walked past like most.
> Would much rather fight the drake that would have spawned instead of the ruin, and then MAYBE get lucky and have fun, assuming I survive the fight.

Yet another? This change isn't adding another ruin you dingus, and most miners i know of enter the ruin for the gamer gear at the very least, if not the bananium.

**Comment by actioninja** [comment]
I was going to make this spacelube slip where it would fling you off in the direction you were facing but I couldn't get it to work right.

**Comment by FloranOtten** [comment]
I think the crawling really fucked this ruin. It was at least gated for people who could remember the routes to not slide into lava. Now you can literally just crawl up and grab it. Not fun.

**Comment by nemvar** [comment]
For the record, this thing now does a spacelube slip.

**Comment by ExcessiveUseOfCobblestone** [comment]
why did you edit the arguments' positions and, more importantly, will that impact any subtype's overwrite?

**Comment by nemvar** [comment]
It won't impact the subtypes. I edited it to be in line WITH the subtypes. This proc must have missed a slip refactor or two.

**Comment by ExcessiveUseOfCobblestone** [comment]
I trust you I just didn't want to codedive for the answer myself huhuhu

**Pull request merged**
