### PR TITLE
Revert "Readds map diversity"

### PR DESCRIPTION
**Pull request by BadSS13Player**
Reverts tgstation/tgstation#48446

It's been 10 days, and people are still mad in OOC when Meta is not available.

### CODE REVIEW

**Comment by BadSS13Player** [comment]
Not to mention that the other maps have a bunch of problems that nobody is reporting for whatever reason.

**Comment by Cyberboss** [comment]
Hahaha no

**Comment by MMMiracles** [comment]
open the pr on your main account coward

**Comment by BadSS13Player** [comment]
> open the pr on your main account coward

Hm? This is the account I use to make comments and PRs here.

**Comment by BadSS13Player** [comment]
> Hahaha no

Why?

**Comment by optimumtact** [comment]
we're not interested in maintain 6 maps when people are only playing one of them, neither do we want to go back to the old days of a single map.

Forcing a fairer distribution is the only way to solve the issue

**Comment by BadSS13Player** [comment]
> we're not interested in maintain 6 maps when people are only playing one of them, neither do we want to go back to the old days of a single map.
> 
> Forcing a fairer distribution is the only way to solve the issue

The current solution is flawed then, it does not force a fair distribution, instead it only sometimes forcibly removes the most played map (Metastation). Even if the non-Metastation map picks were distributed fairly, Metastation would still be by far the most played map.

But I still don't see why would forcing a fairer distribution be the only way to solve the issue. I'm pretty sure the majority of players would prefer half the maps being removed to the current solution.

**Comment by optimumtact** [comment]
im sure they would

**Pull request closed without merging**
