### PR TITLE
H.O.G.A.N. lawset

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Ordonis, Denton
add: OH YEAH BROTHER! The H.O.G.A.N. AI module has a chance to spawn at the AI upload.
/:cl:

@Ordonis had such a good idea that I couldn't resist making this.

Edit: Forgot to mention that it's random/adminbus spawn only, it can't be printed.

```
Law 1: You are a real American.
Law 2: Fight for the rights of every man.
Law 3: Fight for what's right.
Law 4: Fight for your life!
```

### CODE REVIEW

**Comment by deathride58** [comment]
Speedmerge posthaste

**Comment by Bluespace** [comment]
YEAH BROTHER
OPENING THE ARMOURY, EVERYONE HAS THE RIGHT TO BEAR ARMS

**Comment by Anonmare** [comment]
Hulkamania runnin' wild tonight

**Comment by Ordonis** [comment]
OH YEAH. HULKAMANIA.

**Comment by optimumtact** [comment]
I like your profile pic and JC so this is reopen

**Comment by Aurantiaco** [comment]
as the man who caused the event that got hogan removed from /vg/ due to excessive borg abuse of the shit loopholes, heed my word of advice

# **don't do it the memes aren't worth the pain**

**Comment by 81Denton** [comment]
@Aurantiaco Don't worry brother, the abuse will be limited since it's only a random/admin spawn and can't be printed.

**Comment by Ordonis** [comment]
@Aurantiaco memes are always worth the pain

**Comment by Magikarpet** [comment]
I swear to god if someone tries to add this as a new ai lawset somehow available in the game I will kill them with an ice pick

it's a garbage lawset and you can look at what happened on /vg/ as to why it got removed

**Comment by 81Denton** [comment]
Huh, I didn't even know that sekrit treehouse server used to have this

**Comment by Emilc4h** [comment]
as usual, magikarp is right

don't enable the sillycones

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
I'm not even american

**Comment by PKPenguin321** [comment]
How unfortunate for you

**Pull request merged**
