### PR TITLE
Makes the Icebox Bridge look beter

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

Exactly what it says in the tin: The icebox bridge now looks much better. No items were added, removed or moved between rooms; all items are still the same and in the same room so no balance is affected.

## Why It's Good For The Game

Mapping pretty.

## Changelog

:cl:
qol: The icebox bridge had its items rearanged to be prettier (and less 2010ish).
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
image
did u mean to do this

**Comment by EuSouAFazer** [comment]
merge conflict moment 😔 (that was not intentional)

**Comment by DATA-xPUNGED** [comment]
No pictures :(

**Comment by EuSouAFazer** [comment]
one second i need a moment

**Pull request closed without merging**
