### PR TITLE
Nerfs human & ethereal nutrition moodlets

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
tweak: Humans and ethereals are less affected by nutritional requirements.
/:cl:

better than Wesoda's PR because the actual sanity-drain class these moodlets put you in are the same as his PR but are still actually punishing for what hunger was.

as comparision, the worst sanity level has less slowdown than hunger used to do before the mood system. so this entire issue is already redundant.

### CODE REVIEW

**Comment by wesoda25** [comment]
It doesn't make sense to me that food punishment was consolidated into mood, there should be a slowdown added back to hunger and a milder punishment for mood.

**Comment by Qustinnus** [comment]
why would we have so many seperate systems it just makes it more confusing

**Comment by ExcessiveUseOfCobblestone** [comment]
So you can ignore the systems you don't like :^)

**Comment by wesoda25** [comment]
I mean gameplay wise it wouldn't be confusing or have much of a difference, nor could you ignore it. If you don't eat, hunger gives you a slowdown. If you aren't happy, that gives you slowdown (or increased stun times and all the small shit mood does). Making it one system doesn't make much sense to me.

**Comment by ExcessiveUseOfCobblestone** [comment]
would be cool if needs were a unique subsystem of the overarching mood system where they all contribute (and have specific ways of maintaining) but that's not a hill I want to die on enough to push through.

**Review by ExcessiveUseOfCobblestone — COMMENTED** [review]
I know they're different pre-PR but are the numbers suppose to be the same?

Just wondering if it should be defined/subtyped

**Comment by Qustinnus** [comment]
Nah the numbers should be different, also the needs thing is something I could consider

**Pull request merged**
