### PR TITLE
Revert "Require Node 16"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#63314

breaks tgs, process just hangs.

make it atomic so we can figure out which change it is.

@stylemistake 

image

### CODE REVIEW

**Comment by stylemistake** [comment]
Better solution #63358

**Comment by MrStonedOne** [comment]
@tgstation/commit-access 
image

**Comment by optimumtact** [comment]
@MrStonedOne Would that not be better served by having an issue filed to track the issue?

We have a work around that is likely to suit, as it's very unlikely we are going to change tgfont in the near term.

I get that it's not a perfect solution but i'm not convinced keeping this PR open is the best way to signal we have outstanding work.

**Comment by optimumtact** [comment]
@MrStonedOne hello?

**Pull request closed without merging**
