### PR TITLE
North Star QOL Updates

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
Just a routine, well-past-due, update to the North Star map.
This PR does a number of things, everything is tested and functional.
The list of full changes is below:

<details>
<summary> List of Changes! </summary>

Sec outpost on 1st floor moved
Central elevator can now access all floors
New maint door in 1st aft hall
New maint door in workout room
Chaplain has lesser smoke book
Chaplain starts in bed (they eeby)
Chaplain has more wallmounts
Shuffled some pipes & wires around in robotics
Renamed doors by psych & science
Fixed disposals above bitrunner's den
Replaced the central staircase with a sturdy ladder
Decorated the central ladder area
Rearranged loot in starboard dorms maint
Renamed the name of the floor in xenobio's pen
Replaced windoors at arrivals with proper subtype and gave them hydroponics access to prevent animals from escaping early
Change the design on the floor outside of Robotics
Gave Robotics & Science a roundstart quantum pad for easy access to eachother.
Updated some decals inside robotics
Added more windows to maint
Added more unrestricted helpers to all floor maints
Added more lights on the path to the gravgen from engineering
Security offices now have their cells replaced with a disposals tube leading to security's "drunk tank"
Security's drunk tank now has wall mounted flashers
Added more landmine spawners
Added DNA disks and a geneticist outfit vendor to genetics

</details>

## Why It's Good For The Game
The map needed some polish, and this PR addresses some concerns and suggestions in the feedback thread on the forums!
[https://tgstation13.org/phpBB/viewtopic.php?f=11&t=35536](url)
## Changelog
:cl:
fix: The North Star's disposals are now functional!
qol: The North Star has had a staggering amount of quality of life changes.
add: Nanotrasen has now supplied North Star security outposts with a disposals line leading directly to the drunk tank.
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
You misspelled eepy, a b instead of a p

Your right to gaming, making PRs, breathing, and fingers has been revoked. Please visit your nearest reeducation chamber for punishment

**Comment by LemonInTheDark** [comment]
user above me is eepby

**Comment by Cheshify** [comment]
> You misspelled eepy, a b instead of a p
> 
> Your right to gaming, making PRs, breathing, and fingers has been revoked. Please visit your nearest reeducation chamber for punishment

sounds like someone is eeby and needs a nap

**Comment by Cheshify** [comment]
fucker

**Comment by Admiral-Gigaton** [comment]
Can you add a quicker entrance/exit to mining? Being lazy is hard, and walking from mining, to cargo dock, then to the cargo lobby, all while dodging bullets from cargonians and securishits, as well as beating the shit out of the clown for terrorizing you and breaking in, is hard enough

**Comment by Cheshify** [comment]
I don't want to do that, I like mining how it is.

**Comment by Admiral-Gigaton** [comment]
> I don't want to do that, I like mining how it is.

Time to make a PR after this one where I put quantum pads in the cargo lobby and mining

**Comment by Cheshify** [comment]
> > I don't want to do that, I like mining how it is.
> 
> Time to make a PR after this one where I put quantum pads in the cargo lobby and mining

Very cool of you to be a dick, thanks.

**Comment by Admiral-Gigaton** [comment]
> > > I don't want to do that, I like mining how it is.
> > 
> > 
> > Time to make a PR after this one where I put quantum pads in the cargo lobby and mining
> 
> Very cool of you to be a dick, thanks.

wasnt meant to be a dick, was supposed to be a joke, but hey, i can understand how you could see it as being a dick

**Comment by Cheshify** [comment]
> > > > I don't want to do that, I like mining how it is.
> > > 
> > > 
> > > Time to make a PR after this one where I put quantum pads in the cargo lobby and mining
> > 
> > 
> > Very cool of you to be a dick, thanks.
> 
> wasnt meant to be a dick, was supposed to be a joke, but hey, i can understand how you could see it as being a dick

I apologize for calling you one then.

**Comment by MMMiracles** [comment]
Changes look fine, have a few things that need fixed before I can go ahead though:

- Floating camera in the Engineering Lobby, top-right.
image

- Bottom floor of the central elevator seems to be missing a way to call it back down once moved.
image

- A supply security spawner is still in the cargo lobby, I assume this isn't intended since you put 6 of them in the new office.
image

- Bottom floor of the ladder access has two stacked ladders.
image

- The BZ floors in Xenobio should be their own preset instead of var-edited for a custom gas mix. I got yelled at for this so now I yell at you for it.

- Not sure I see the arrival window changes you listed? Mapdiff bot doesn't see any changes near the area relating to the animals and I don't see any changes either when looking in the editor.

Resolve these issues and I don't see any issue with merging this.

**Comment by Cheshify** [comment]
That's weird because I changed the access on the windoors to be hydroponics so the critters don't get out

**Pull request merged**
