### PR TITLE
Added some layers so mutantrace sprites actually make sense

### PR DESCRIPTION
**Pull request by Incoming5643**
Added some layers to allow for accurate "3D" placement of otherwise obtrusive/improperly shown mob features like tails or weirdly shaped heads. In addition exosuits that hide the uniform will now also hide a lizards tail, and masks that hide the face will push a poor lizards nose in so we don't see it clipping out the front of the damn thing. This also allows you to properly see the lizards tail while it faces north.

d10_icon

> taking screenshot with stretch to fit on

### CODE REVIEW

**Comment by paprka** [comment]
This is good, especially if I play lizard I want a way to conceal that I am a lizard scum.

**Comment by Incoming5643** [comment]
Also weird bug I'm still resolving: if you take the exosuit off while the mask is still on, the mask disappears off your face. Will fix of course

**Comment by WJohn** [comment]
Yeah because things like labcoats shouldn't be hiding tails, it probably should be a case-by-case basis.

**Comment by Incoming5643** [comment]
We'll see, but I'd like to see if hideuniform does the job well enough by itself first because if I see it live on the server I can quickly figure out which, if any, exosuits aren't displaying the tail in a way that makes sense, whereas if I do it right NOW i have to manually review every single suit myself.

Also labcoats don't hide tails, outside of bomb/virus/fire/space suits I don't know of many suits that would hide the tail, because if you can see the uniform sprite at ALL through the suit, it won't have the flag.

**Comment by Incoming5643** [comment]
Also if anyone enjoys a challenge try to isolate the little fly wings on the back of the flyperson sprite so I can have them poking out of uniforms. I'd have done it already, but since they're semi transparent properly isolating it from the flys back is hard, not to mention recreating that transparency in byond.

**Comment by Miauw62** [comment]
Very nice :+1:

I guess tails disappearing doesn't make much sense, but gameplay-wise this is probably more fun than lizards not being able to hide the fact that they are lizard scum.

**Comment by Incoming5643** [comment]
the deep lore is that they're stuffing them up the back of the suits.

 Half considered giving a message for putting on "ill fitting" clothing like that, but figured it'd get really old really fast.

**Pull request merged**
