### PR TITLE
New OOC emotes

### PR DESCRIPTION
**Pull request by silicons**
:cl:
rscadd: Some new emojis have been added to OOC for your enjoyment. Try them out.
rscadd: New emojis are : coffee, trophy, tea, gear, supermatter, forceweapon, gift, kudzu, dosh, chrono, nya, and tophat. Type :nameofemoji: in OOC to use.
/:cl:
Adds several new emojis to OOC as listed in the changelog
New Emojis
EDIT: PEPE REMOVED BECAUSE NO ONE LIKES FUN ;^)

### CODE REVIEW

**Comment by Bawhoppen** [comment]
but some of these aren't even actual ingame sprites (ignoring pepe ofc)

**Comment by kevinz000** [comment]
Every sprite is from the game code.

**Comment by Bawhoppen** [comment]
then you must have the worst resolution image capturing software

**Comment by optimumtact** [comment]
and you must be unaware of all the icons in our codebase

**Comment by Bawhoppen** [comment]
I'm talking about the kudzu

**Comment by bgobandit** [comment]
we should have dosh already

**Comment by Niknakflak** [comment]
NYA :cat:

**Comment by kevinz000** [comment]
dosh duplicate removed. sorry.

**Comment by Shapsy** [comment]
Can we not add the pepe

**Comment by jughu** [comment]
Its rare and shoukd have 1% to trigger

**Comment by Aloraydrel** [comment]
:pepe:

**Comment by ChangelingRain** [comment]
The kudzu sprite is horribly outdated, where'd you even find it?

**Comment by Bawhoppen** [comment]
SEE EVEN JOAN AGREES

**Comment by AlexCrimson** [comment]
please no fucking meme bullshit

**Comment by bobdobbington** [comment]
:kudzu:

**Comment by lzimann** [comment]
DRINK THE FUCKING COFFEE

**Comment by Dorsisdwarf** [comment]
no pepes

even if you like the meme, it wont be rare for long

**Comment by kevinz000** [comment]
o-ok

**Comment by optimumtact** [comment]
Ignore them, pepes are fine

**Comment by KorPhaeron** [comment]
most of these seem pointless and will never be used other than the dumb meme

**Comment by optimumtact** [comment]
You mean just like all the existing ones?

**Comment by KorPhaeron** [comment]
yes

**Comment by kevinz000** [comment]
pepe has been removed ;_;

**Comment by AnturK** [comment]
While you're at it remove pepe from the clockwork file

**Comment by Thunder12345** [comment]
Get the removed ones outta the changelog

**Comment by Iamgoofball** [comment]
@AnturK No, it's the debug "shit is fucked" crap

**Comment by Aloraydrel** [comment]
bring back pepe

**Comment by Armhulen** [comment]
can we make it so when you emote you have a 1% chance for a pepe?

**Pull request merged**
