### PR TITLE
Made borgs and AI able to use research queue [NO GBP]

### LINKED ISSUE #85049: Borgs cannot use the research queue system
Reporting client version: 515.1641

## Issue Summary

Borgs cannot queue research nodes or cancel queued research nodes.

## Round ID:
[232245](https://scrubby.melonmesa.com/round/232245)

## Testmerges:
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

## Reproduction:

1. Be a borg
2. Try pressing the queue button on an un-queued node
3. Try cancelling a queued node
4. Hope really hard that this is indeed a bug and not something someone actually intended

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Interaction with the queue didn't work for mobs of a type different from `/mob/living/carbon/human`

Fixed this.

## Why It's Good For The Game

Fixes #85049 

## Changelog

:cl:
fix: Borgs and AI can now use research queue
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Nonhumans (lizards, moths, etc) could already use the machine. You might want to clarify you mostly mean "cyborgs" 😅

**Comment by Sadboysuss** [comment]
don't forget to edit CL too

**Comment by L0pz** [comment]
THANK YOU THANK YOU THANK YOU

**Comment by Maximal08** [comment]
Should it have been fixed? Because research for Borg modules is not cheap, and they cannot significantly influence the round, honestly it would be better to rework the Borg research altogether and add improvements for them to the appropriate areas for people. For example, with the opening of limb grower for doctors to give a defibrillator for medical Borg or the opening of the details of a shooting range to give Borg rped.

**Comment by Sadboysuss** [comment]
> Should it have been fixed? Because research for Borg modules is not cheap, and they cannot significantly influence the round, honestly it would be better to rework the Borg research altogether and add improvements for them to the appropriate areas for people. For example, with the opening of limb grower for doctors to give a defibrillator for medical Borg or the opening of the details of a shooting range to give Borg rped.

This is an unexpected behavior that arose from another feature, if you want to bring this back then it should be a balance pr

**Comment by Maximal08** [comment]
> > Должно ли это было быть исправлено? Поскольку исследования для модулей Borg стоят недешево, и они не могут существенно повлиять на раунд, честно говоря, было бы лучше полностью переработать исследования Borg и добавить улучшения для них в соответствующие области для людей. Например, с открытием устройства для выращивания конечностей, чтобы врачи могли выдавать дефибриллятор для медицинского Borg, или с открытием сведений о стрельбище, чтобы выдавать Borg rped.
> 
> Это неожиданное поведение, возникшее из-за другой функции, если вы хотите вернуть это, то это должен быть баланс pr

It's just a mistake that, in my opinion, made the game better, because the study for bork will go to a small number of players on the station, which will deprive the crew members, who are the majority.

**Comment by MTandi** [comment]
> It's just a mistake that, in my opinion, made the game better, because the study for borg will go to a small number of players on the station, which will deprive the crew members, who are the majority.

This is unrelated to this PR, I've added the queue for all players, just didn't test it on silicons.

And your statement is true for any tech. Implants won't be used by the majority of the crew. Combat mechs won't be used by everyone. Experimental tools will be used by two engineers. And it is not related to the recent techweb change of mine either.

**Comment by Maximal08** [comment]
> > It's just a mistake that, in my opinion, made the game better, because the study for borg will go to a small number of players on the station, which will deprive the crew members, who are the majority.
> 
> This is unrelated to this PR, I've added the queue for all players, just didn't test it on silicons. I did not intend to segregate borgs .
> 
> And your statement is true for any tech. Implants won't be used by the majority of the crew. Combat mechs won't be used by everyone. Experimental tools will be used by two engineers. And it is not related to the recent techweb change of mine either.

The very idea of the research queue is good, let's see what happens to it in the rounds

**Pull request merged**
