### PR TITLE
[s] Fix bobby tables

### PR DESCRIPTION
**Pull request by Cyberboss**
Nothing interesting in commit history at all

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
!

**Comment by Jordie0608** [comment]
`mode_result` is never user-input.

**Comment by Cyberboss** [comment]
It is admin input though

**Comment by Jordie0608** [comment]
I trust our admins.

**Comment by Cyberboss** [comment]
Yeah but its a clear vector for privilege escalation and should be removed

**Comment by optimumtact** [comment]
@Jordie0608 I had this exact argument with cyberboss and somepotatoe in irc

**Pull request merged**
