### PR TITLE
MetaStation External Overhaul

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This PR completely redoes the space-side sections of MetaStation including solars with a few objectives in mind:
1. Minimize the use of meteor shielding unless it's absolutely necessary. Budget cuts are needed
2. Use latticework and related materials realistically and remove random placements
3. Create reasonable anchor points for objects that would need them so they're realistically attached to the station
4. Add character and variance to outside sections of the map that can also contribute to gameplay
5. Change the way that players think about solars, making them varied, have stories, and (for some sections) take more to set up.

I tried to minimize touching recent external designs like the new toxins testing area, xenobio sat, and space hut, but did touch up on some of the latticework outside. The only other notable change that touches the interior is that I replaced the transit tube with an auto transit tube variant and moved the AI satellite up one tile to align with the tubes to engineering better.

There are now some areas that utilize EVA railings to push off of, an idea originally designed by Paxilmaniac. The way that the exterior latticework is set up, space combat has the potential to be more nuanced and situational depending on the area instead of having guaranteed maneuverability practically everywhere.

The following is a showcase of some of the work done (Note this will probably look different in the final product based on feedback):

NW Solars:
image

BSA Construction and part of Arrivals:
image

SW Solars: (forgot to add the creates for the supplies here. Oops!)
image

SE Solars and parts of the testing range:
image

Xenobio Sat featuring some of those new EVA railings (That girder shouldn't be deconned):
image

AI Sat Connection (not pictured is the other anchor point which looks similar to the one pictured:
image

NE Solars including the charging dock and makeshift expansion:
image

Budget-Friendly Meteor Shielding:
image

## Why It's Good For The Game

While the external layout might not seem consequential to most, having a better setup that properly utilizes latticework and meteor shielding creates a better environment for players to play in and gives them more choices. I also want to show that even the little things can have more personality and depth than we might think. Moving away from generic exterior designs on our main map should give people inspiration to do similar things with other current and future maps.

Solars in their current state are very generic, easy to set up, and can power the entire station indefinitely. Adding some variance to how they're done to show more potential combinations and also give players the opportunity to set up solars themselves can be a good opportunity to both teach newer players how to set up machinery and also put a little bit more effort into setting up consistent power generation.

## Changelog
:cl:
add: Completely redid MetaStation's exterior layout
balance: Some of the solars on MetaStation weren't set up last shift. You'll have to build them yourselves.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Son-of-Space** [comment]
Things left to do:
Some playtesting on local to make sure the solars work correctly
playtesting for the new transit tube
debugging for active turfs and other issues
feedback on layouts

**Comment by TemporalOroboros** [comment]
Have you checked whether the new solar arrays actually work?

**Comment by Son-of-Space** [comment]
> 
> 
> Have you checked whether the new solar arrays actually work?

see previous comment

**Comment by CRITAWAKETS** [comment]
add meteor shielding around the atmos tanks otherwise if meteors ever roll as an event its a guarenteed shuttle call since you wont be able to repressurize areas

**Comment by Son-of-Space** [comment]
> 
> 
> add meteor shielding around the atmos tanks otherwise if meteors ever roll as an event its a guarenteed shuttle call since you wont be able to repressurize areas

image


I think there's plenty of meteor shielding

**Comment by RaveRadbury** [comment]
I like the current BSA area more than the one you're suggesting. The new one feels kinda restricting, the old one was sprawling and therefore felt more flexible.

**Comment by Son-of-Space** [comment]
> 
> 
> I like the current BSA area more than the one you're suggesting. The new one feels kinda restricting, the old one was sprawling and therefore felt more flexible.

It was a little too sprawling, like someone just randomly placed plating around and thought it was good enough.

**Comment by RaveRadbury** [comment]
tbh I didn't even know it was *meant* for the BSA until you labelled it as such here. I just thought it was *incredibly* unfinished construction.

**Comment by Son-of-Space** [comment]
> 
> 
> tbh I didn't even know it was _meant_ for the BSA until you labelled it as such here. I just thought it was _incredibly_ unfinished construction.

mhm, from what I understand that was the intention, it's just not really known, especially since there was no indication.

**Comment by Dorsisdwarf** [comment]
> 
> 
> > add meteor shielding around the atmos tanks otherwise if meteors ever roll as an event its a guarenteed shuttle call since you wont be able to repressurize areas
> 
> 
> I think there's plenty of meteor shielding.
> 
> Plus, RCDs are way better now. You can definitely patch a hole in one of the tanks if it gets hit.

This is a weird reply given the areas you've highlighted on the right arent meteor shielded at all by the new PR, but more importantly the actually needed tanks (N2, O2, and Air) are shielded by the new Xenobio so there's not really a problem here

**Comment by Son-of-Space** [comment]
> 
> 
> > > add meteor shielding around the atmos tanks otherwise if meteors ever roll as an event its a guarenteed shuttle call since you wont be able to repressurize areas
> > 
> > 
> > I think there's plenty of meteor shielding.
> > Plus, RCDs are way better now. You can definitely patch a hole in one of the tanks if it gets hit.
> 
> This is a weird reply given the areas you've highlighted on the right arent meteor shielded at all by the new PR, but more importantly the actually needed tanks (N2, O2, and Air) are shielded by the new Xenobio so there's not really a problem here

This is a good point. The right side is partially shielded, but not completely shielded. There's a good 15 degree zone that meteors could theoretically sneak their way in from.

**Comment by Son-of-Space** [comment]
Tested. Everything works. Significant changes were made to most Solars sites.

**Comment by Son-of-Space** [comment]
Oh, another big change is that I removed all of the EVA railings from XenobioSat. Zytolg didn't like the southern ones or the way I did the shielding, so I swapped them around. I then decided that I didn't want the ones on the top side either.

**Comment by Son-of-Space** [comment]
Sorry, had to drive across the country on short notice! This should be good.

**Comment by Son-of-Space** [comment]
@EOBGames please review this.

**Comment by nightred** [comment]
The changes look great, I see some issues with a pipe here and there but it is hard to tell if that is caused by this or not.
The actual changes are good and I see nothing that makes me back at this PR.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-12). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by EOBGames** [comment]
Sorry for leaving this so long, by the way- I clearly need to get a better balance of Valheim and maptainance

**Comment by KathrinBailey** [comment]
@Son-of-Space Hi, did you use the near space area for the parts circled in red? There's also similar parts that don't look like open space area has been used in other images.
image
It doesn't look like it, but that might just be some artifact with whatever you're doing to get the image.

**Comment by Son-of-Space** [comment]
> 
> 
> @Son-of-Space Hi, did you use the near space area for the parts circled in red? There's also similar parts that don't look like open space area has been used in other images.
> image
> It doesn't look like it, but that might just be some artifact with whatever you're doing to get the image.

@KathrinBailey What you see pictured isn't in the final draft. Nearstation was used for anything that is grabable, I didn't use it for the railings as they are structures and already grabable thus would have caused issues. Otherwise if there's space they use the default space area.

**Pull request merged**
