### PR TITLE
grass resprite/icon fixes, take 2

### PR DESCRIPTION
**Pull request by pudl**
#7919

### CODE REVIEW

**Comment by paprka** [comment]
:-1: Grass looks bad without siding borders against normal tiles.

**Comment by Iamgoofball** [comment]
:-1: grass doesn't blend with the general "sharp" atheistic of every other tile in the game

**Comment by Cheridan** [comment]
Your sprites are good but the border needs to stay, yo

**Comment by pudl** [comment]
no

**Comment by RemieRichards** [comment]
>disagreeing with a headcoder

it's like you want your PR to be closed.

Also wherever the grass tile came from it's ugly, I don't even think sidings will fix it.

**Comment by pudl** [comment]
im still waiting for @Nienhaus to say what he thinks since wj liked it

**Comment by WJohn** [comment]
I've never liked having grass borders, personally. Mainly because it becomes completely unusable for any sort of forests or grassland areas (on top of our current grass sprites being hideous and way too bright).

This PR gets a :+1: if only for the better grass and dead grass sprites.

**Comment by paprka** [comment]
Why not make a child of astroturf without the borders for forests you ponce

**Comment by pudl** [comment]
because borders are ugly

**Comment by pudl** [comment]
i'm not going to maintain this shit if i keep getting merge errors over something so fucking simple

**Pull request closed without merging**
