### PR TITLE
Fixes the ghost sheet's broken icon

### PR DESCRIPTION
**Pull request by Winterous**
I just renamed the item_state and the icon the DMI to ghost_sheet instead of ghost_sheet_item, and that worked for some reason. No idea why it was broken, no idea why this is any different, but it's fixed now so whatever.
Also it now has the same aerodynamics as a normal bedsheet.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
By way of explanation, `icon_state` is the name used for the item's icon, and `item_state` is the name used for in-hand and on-mob visuals. So you had them backwards.

**Review by SpaceManiac — APPROVED** [review]

**Comment by Winterous** [comment]
Then why did the mob sprites work fine with the wrong name, before? O_o

**Comment by Bawhoppen** [comment]
@SpaceManiac I believe that icon_state is both the on-mob and item, while item_state is just inhands.

**Comment by ShizCalev** [comment]
item_state is only inhands.

**Comment by SpaceManiac** [comment]
got it

**Pull request merged**
