### PR TITLE
Organ Update [Cloning isn't broken edition]

### LINKED ISSUE #29200: Cloning is broken
It's currently auto ejecting people as they're getting cloned, I believe it might be related to the new organs update.

note: no outside factors are affecting this (I.E powerloss/someone with access ejecting people)
They might be dying to toxin damage mid-cloning due to not having livers, however I cannot confirm this.

### PR DESCRIPTION
**Pull request by Tacolizard**
🆑 Tacolizard and Cyberboss
add: Added two new organs, the liver and stomach. Without them, you won't metabolize chemicals.
add: The liver is responsible for processing all chemicals except nutrients. If your liver is removed, you will be unable to metabolize any drugs and will slowly die of toxin damage.
add: Drinking too much alcohol or having too many toxins in you will damage your liver, if it becomes too damaged, it will undergo liver failure and you will slowly die of toxin damage. Your liver naturally heals a small amount of its damage. However, it doesn't heal enough to offset stronger alcohols or large amounts of toxins, at least until they are metabolized out of your body.
add: to conduct a liver transplant, inject corazone into the patient. Corazone will prevent the patient from taking damage due to either not having a liver or undergoing liver failure. Corazone will metabolize out of the patient quickly, so at least 50u is recommended.
add: The stomach is responsible for metabolizing nutrients. Without a stomach, you will be unable to get fat, but you will also be unable to process any nutrients, meaning you will eventually starve to death.
/🆑

see #28913 for more details

was not able to reproduce #29214. I think they just made a stealthy virus. I was infected fine by a number of different viruses.

fixes #29200

### CODE REVIEW

**Comment by Tacolizard** [comment]
speedmerge pls? this is the same exact PR with just one extra commit and the longer this stays open the higher the odds of merge conflicts that I really don't wanna deal with

**Comment by Tacolizard** [comment]
see my later comments on #29200 for specific details on the nature of this bug and how it was fixed.

**Comment by Mark9013100** [comment]
this is the change we needed remove cloning hardmode lifeweb fuck the system fuck quality of life

**Review by Cyberboss — APPROVED** [review]

**Comment by Tacolizard** [comment]
@Cyberboss 24 hours up!

**Comment by FuryMcFlurry** [comment]
Not sure but will this also contain a mechanical liver or something to transplant into someone with a busted liver

**Comment by Tacolizard** [comment]
@FuryMcFlurry no, those are coming in a later PR

**Pull request merged**
