### PR TITLE
Removes Horseheading from Summon Magic

### PR DESCRIPTION
**Pull request by SconesC**
Do I even need to explain this? Stupid griff spell, contributes nothing of value, extremely annoying and can only be treated by Chemistry. Also has a hilarious habit of producing undroppable masks if someone afflicted by the curse gets transformed.

EVERY summon magic round there is someone doing this. Unfunny old as fuck joke spell that should go. Nothing of value will be lost.

### CODE REVIEW

**Comment by Anonus** [comment]
NEIGH :-1:

**Comment by tedward1337** [comment]
Yis

**Comment by Incoming5643** [comment]
Live by the :horse: die by the :horse:

**Comment by Iamgoofball** [comment]
:-1:

i horse pls nerf

**Comment by xxalpha** [comment]
Both Summon Magic and Summon Guns are more shitty than horsehead could ever be.

:-1:

**Comment by daman997** [comment]
NEEEEEEIIGHHHHHH :-1:

**Comment by ike709** [comment]
NEIGH :-1:

**Comment by stapler2025** [comment]
NEIGN :-1:

**Comment by Xhuis** [comment]
:horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing:

**Comment by GunHog** [comment]
:-1:

**Comment by optimumtact** [comment]
:horse: 
:-1:

**Comment by Jalleo** [comment]
:+1: chemists never help stop the maskarade

**Comment by Iamgoofball** [comment]
@Jalleo we don't fix player incompetency with code

**Comment by Jalleo** [comment]
No but we could add a different way to remove masks or make the masks like the pierrets throat virus.
Having only one method is awful.

**Comment by SconesC** [comment]
You would not believe how many ahelps I get about the nodrop masks

**Comment by Jacquerel** [comment]
@Jalleo ok but neither of those suggestions you made are "removes horse from summon magic", which is what this is a PR for

**Comment by Dorsisdwarf** [comment]
:-1: :horse: :horse:  :horse: :horse: :horse: :horse: :horse: :horse: :horse: :horse: :horse: :horse: :horse_racing:

**Comment by Jalleo** [comment]
I said those for alternatives if you really want to keep the masks. While they are funny after a while it is just awful.

**Comment by Cheridan** [comment]
It looks like the NEIGHS have it

**Comment by optimumtact** [comment]
Laughed myself horse

**Comment by Miauw62** [comment]
It's a wizard round, there should be chaos
Op 18-jul.-2015 08:06 schreef "Orange Borg" <notifications@github.com>:

**Comment by GunHog** [comment]
>Posting on a dead, horse-related PR

I see what you did there!

**Comment by optimumtact** [comment]
Thats enough horsing around

**Pull request closed without merging**
