### PR TITLE
Adds *slowclap for silicons

### PR DESCRIPTION
**Pull request by Niknakflak**
## About The Pull Request
Adds a new emote for silicons.  The slowclap.  Silicons cant clap normally and I have always wanted to clap as a silicon.  It makes sense to give them slowclap as a dank reference to a certain game!  Sound effect is taken from a youtube sound effect video and then modified by me in audacity so...  fair use?

## Why It's Good For The Game
dank gaben game reference.  more silicon sounds why not

EDIT: new Sound file preview: https://file.house/lKWh.ogg

## Changelog
:cl:
add: Silicons can now slowclap by doing *slowclap
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
I don't get it

**Comment by tralezab** [comment]
Nevermind I read your branch name

**Comment by maxymax13** [comment]
this pr empowers more annoying smug borgs that get in the way of arresting dangerous antags, push you away when trying to escape, and seethe when you rightfully flash and fireaxe them, do not merge

**Comment by Niknakflak** [comment]
> this pr empowers more annoying smug borgs that get in the way of arresting dangerous antags, push you away when trying to escape, and seethe when you rightfully flash and fireaxe them, do not merge
> 
> > Sound effect is taken from a youtube sound effect video and then modified by me in audacity so... fair use?
> 
> you'll need a bit more than that to please license memes

I'll wait for an actual maintainer to tell me otherwise.  I'll record it my damn self if I have to, I have a really good Mic.  
https://www.youtube.com/channel/UC1WdEBvHfx-vPQbEkxD2Tcg/about
The channel where it came from.  No licensing information and I already modified the sound myself.  If I really have to do the above, I will.

**Comment by JJRcop** [comment]
Failed linting, please fix
Screenshot_20210421_000829

**Comment by ATH1909** [comment]
it'd be nice if everyone could do this, not just silicons, tbh

maybe we could even let silicons use the normal *clap emote as well, with the same excuse?

**Comment by notfrying1pans** [comment]
portal 2 type beat

**Comment by Niknakflak** [comment]
> it'd be nice if everyone could do this, not just silicons, tbh
> 
> maybe we could even let silicons use the normal *clap emote as well, with the same excuse?

sounds like you should play silicon

**Comment by Niknakflak** [comment]
Mothblocks said I would probably have a problem with using that youtube sound effect even modified so I fuckin did it and just clapped for my mic.  The new sound effect is now my actual clap, cleaned up and pitch modulated.

https://file.house/lKWh.ogg

are you happy now

**Comment by notfrying1pans** [comment]
if you ripped the audio from the game files wouldnt it count as some copyright violation or smth?

**Comment by Niknakflak** [comment]
> if you ripped the audio from the game files wouldnt it count as some copyright violation or smth?

I wasn't able to find a single clean version of the actual portal2 clapping and we would probably not want to use it anyway hence the whole not using them, and now it's literally a sound I created myself

**Comment by notfrying1pans** [comment]
i could rip it for you if you want

**Comment by notfrying1pans** [comment]
it's pak01_dir.vpk/sound/vo/glados/potatos_sp_a3_00_fall18.wav

**Comment by Niknakflak** [comment]
We won't use it anyway and I said that like 3 times....

**Comment by ATH1909** [comment]
> > it'd be nice if everyone could do this, not just silicons, tbh
> > maybe we could even let silicons use the normal *clap emote as well, with the same excuse?
> 
> sounds like you should play silicon

I do

**Pull request merged**
