### PR TITLE
[MDB IGNORE] Improves status display even more, makes the brig door timers based on status displays

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

This PR was originally just going to be a re-factor of brig doors to be based on status displays, as a big chunk of their code was duplicating the exact same appearance, but then I realized "Cell 1" would have marqueed for being 6 characters and ended up doing the second half of the status display overhaul I meant to do a while back.

So firstly:
- Yes, brig doors are now subtypes of status displays.
- The main improvement out of that refactor, other than a lot of code trimming, is that the on-screen timer updates its readout as you set it, which looks nice.
- Also handled various states in a more consistent way in some edge cases.
- The timer now also displays the cell's actual name instead of the internal ID on the top line.

Now for status displays:
- Long ago, I wanted the marquee to be continuous but the math required knowing the actual measured text width, though without a user that is impossible.
  - I recently realized the scope of the text usable on status displays (no formatting, or icons) is so narrow, I can cheat it like crazy into a small lookup table and a looping function.
  - No, this method can't possibly extend to runetext.
  - So now the marquees loop seemlessly without any gaps! In fact behind the scenes they loop the very first pixel possible, and still done as a one-and-done animate() sequence as before. (click the preview below if you want to see it smoother)
[Marquee](https://gyazo.com/319b8322694249820f7f6ec65b901d91)
- I also added some color:
  - Headings following the standard "-TITLE-" format that also fit without marquee-ing are now highlighted to stand out over just 2 rows of general text.
Countdown
  - Note that people with the status display app can also use this. I consider this fine as people have always been able to cap a line with dashes.
[McRib](https://gyazo.com/9b856765bb6aff2e554a7b1b4fe99782)
  - There was a historical problem of different countdowns feeling the need to break formatting to stand out from the escape shuttle  countdown, such as with the supply shuttle, at the cost of not saying which the shuttle status. Less of an issue because now different subtypes of status display are a different color.
    - Supply shuttle is yellow-orange
[Supply)](https://gyazo.com/568f1a66de1d88be54e9256796ee8036)
    - Kept CARGO / DOCKED the same as I think the marquee nicely grabs CT's attention.
[Supply 2](https://gyazo.com/6fa85b4325dd6cfa239334f799584927)
    - Specialized /shuttle subtype is green for your weird labor camp or whatever needs.
    - Seperately, the brig timer is red. (note it doesn't use the header feature as then "Cell 1", "Cell 2" etc wouldn't fit.
[Brig Timer](https://gyazo.com/dff5f13d1f0e266ad9dca2294c39da87)

## Why It's Good For The Game

Brig timer code much more maintainable.

Pretty colors and marquee text.

## Changelog

:cl:
add: Status displays are now a bit more colorful and have gapless marquee text.
refactor: Brig door timers were massively refactored behind the scenes. Door control should still work as before but be mindful.
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
Note I trimmed so much fat from brigdoor, the net line count is still negative lmao

**Comment by Tastyfish** [comment]
Waiting on first pass review

**Review by AnturK — APPROVED** [review]
Looks good, though you might want to write down somewhere how it detects headers since it might not be obvious for the user

**Comment by Tastyfish** [comment]
> Looks good, though you might want to write down somewhere how it detects headers since it might not be obvious for the user

Huh, we don't have a dedicated wiki page for status displays, do we? hmm

**Comment by san7890** [comment]
> Huh, we don't have a dedicated wiki page for status displays, do we? hmm

https://tgstation13.org/wiki/Machines might work for here? i know there's no construction steps for status displays but it's good to have it somewhere

**Comment by Tastyfish** [comment]
> > Huh, we don't have a dedicated wiki page for status displays, do we? hmm
> 
> https://tgstation13.org/wiki/Machines might work for here? i know there's no construction steps for status displays but it's good to have it somewhere

Yeah, that would work. Could also suggest appropriate use of the other statuses (like please set it to ETA if the emergency shuttle is coming)

**Comment by san7890** [comment]
anyways maps look good so

**Comment by Tastyfish** [comment]
Documented here, as it's a wallmount https://tgstation13.org/wiki/Guide_to_construction#Status_Display

**Pull request merged**
