### PR TITLE
racial dormant mutation changes

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

strength is now the default racial dormant mutation, not dwarfism. what this effectively means is that lizards can now roll dwarfism as one of their dormant mutations (they couldn't before this PR), but they (and moths and ethereals due to the changes further down the list) now can't roll strength as one of their dormant mutations.

ethereals now have shock touch as a racial dormant mutation (you can still craft it the normal way, of course; I just thought that it was in-flavor for them).

moths now have far sight as their racial dormant mutation. it lets you adjust your vision range.

to be clear, not every moth is going to have far sight as a dormant mutation, just as how not every lizard has firebreath as a dormant mutation. it's just in the pool of possible dormant mutations for them.

## Why It's Good For The Game

it's kind of weird that lizards can't roll dwarfism as one of their dormant mutations, but they CAN roll strength as one of their dormant mutations, even though strength's only purpose is to be a component for a mutation that lizards can't even use.

## Changelog
:cl: ATHATH
balance: Strength is now the default racial dormant mutation, not dwarfism.
balance: Ethereals now have shock touch as a racial dormant mutation (you can still craft it the normal way, of course).
add: The far sight mutation has been added to the game as a moth racial dormant mutation-exclusive mutation. It gives you a button that lets you adjust how far you can see.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
This seems pretty nice. Thanks ath

**Comment by necromanceranne** [comment]
>Endless lasers for the race he plays

Go home ATHATH good lord.

**Comment by ATH1909** [comment]
To be absolutely, 100%, CRYSTAL CLEAR:
In order to get the laser eyes mutation from a moth under this PR, you have to:
1. Find a mothperson (monkeys from monkey cubes or from your pen are of the human species, so they won't work for this).
2. Convince that mothperson to sit (probably) SSD or catatonic in your scanner for several minutes as you solve their DNA sequence.
3. Hope and pray that that mothperson even has laser eyes as a dormant mutation in their DNA (as far as I'm aware, the odds of rolling laser eyes in your DNA sequence as a mothperson or firebreath in your DNA sequence as a lizardperson are approximately the same as rolling, say, thermal vision in your DNA sequence as a human).
4. Print mutators that have the same instability cost as the hulk mutation.

**Comment by ATH1909** [comment]
> > Endless lasers for the race he plays
> 
> Go home ATHATH good lord.

But you can't sequence your own DNA unless you brainswap out or something; I'd have to find someone ELSE who plays a moth and convince them to not play the game for a couple of minutes.

Also, to be clear, non-moths can use mutators of this mutation, just as non-lizards can use firebreath mutators (and breathe fire with them).

You rarely see genetics hand out firebreath; this shouldn't be much of a problem.

**Comment by necromanceranne** [comment]
I literally don't even know what to say to you that would convince you that what you are wanting to add is fucking stupid and a bad look from you in particular, as a moth player, to be adding what is arguably the strongest mutation in the game as both a meme and a fucking wizard spell.

The fact it is possible to acquire at all is the issue while already in other prs it is established the current suite of powers are bad for more reasons than 'downright meme material'. Going hard in the other direction is not the solution.

**Comment by anconfuzedrock** [comment]
if this happens I will have to kidnap moths when I Get antag so I can get laser eyes
I don't think you understand how good laser eyes are! Wizard has a spell that TEMPORARILY gives him hulk and laser eyes and you don't do it for the hulk, you do it for the laser eyes.

More importantly, we once had a bug-ish _thing_ where you could get laser eyes as a result of radiation. People tried for laser eyes tons of times and this is easier. Laser eyes are RIDICULOUSLY GOOD. especially compared to other racial mutations!

**Comment by ATH1909** [comment]
> I literally don't even know what to say to you that would convince you that what you are wanting to add is fucking stupid and a bad look from you in particular, as a moth player, to be adding what is arguably the strongest mutation in the game as both a meme and a fucking wizard spell.

I'd argue that firebreath from lizards is stronger, and that got added to the game. Figured I might as well try with laser eyes+moths as well, since I've finally set up a way to make non-webedit PRs again (and this has been on my PR wishlist for a while).

> The fact it is possible to acquire at all is the issue while already in other prs it is established the current suite of powers are bad for more reasons than 'downright meme material'. Going hard in the other direction is not the solution.
> 
> Also, wouldn't insulated be a better idea for ethereals so you're not handing them a craftable mutation?

The problem is that, as far as I'm aware, the mutation has to be locked out of the normal pool to be a racial dormant mutation.



> if this happens I will have to kidnap moths when I Get antag so I can get laser eyes
> I don't think you understand how good laser eyes are! Wizard has a spell that TEMPORARILY gives him hulk and laser eyes and you don't do it for the hulk, you do it for the laser eyes.
> 
> More importantly, we once had a bug-ish _thing_ where you could get laser eyes as a result of radiation. People tried for laser eyes tons of times and this is easier. Laser eyes are RIDICULOUSLY GOOD. especially compared to other racial mutations!

Which is why I've put them at the same instability cost as hulk.

**Comment by ATH1909** [comment]
> **Edit** And before you argue that lizardpeople get fire breath, I should point out goof's explosion changes has buffed firebreath out the arse and it was never meant to be this strong. It was supposed to be closer to an IED but even weaker on the actual damaging force.

How did goof's changes buff firebreath? Just the flinging thing?

**Comment by necromanceranne** [comment]
It's a knockdown

**Comment by anconfuzedrock** [comment]
hulk is peanuts to laser eyes. if you want to give moths a mutation make it so it zooms out their view range by an extra tile or something. fire breath is crappy since you can only use it once in a while. infinite spammable lasers is nuts especially since the main downside to lasers is that they run out of ammo fast and you can't reload them. infinite spammable lasers that don't require your hands!

**Comment by ATH1909** [comment]
> It's a knockdown

Explosions have knocked down for quite a while now, since months before goof's explosion changes

**Comment by ATH1909** [comment]
> hulk is peanuts to laser eyes. if you want to give moths a mutation make it so it zooms out their view range by an extra tile or something. fire breath is crappy since you can only use it once in a while. infinite spammable lasers is nuts especially since the main downside to lasers is that they run out of ammo fast and you can't reload them. infinite spammable lasers that don't require your hands!

I could make the genetics version of the mutation have a longer cooldown between shots, if you'd like.

I'd add the zoom-out thing, but aren't different view settings really buggy right now?

**Comment by anconfuzedrock** [comment]
yeah, they are. All I'm saying is that if laser eyes had 99 genetic instability I would STILL take it.

**Comment by ATH1909** [comment]
> yeah, they are. All I'm saying is that if laser eyes had 99 genetic instability I would STILL take it.

Alright, I'll double the click cooldown for the genetics version of the mutation.

**Comment by LemonInTheDark** [comment]
> I'd add the zoom-out thing, but aren't different view settings really buggy right now?

Nope not at all. The zoom code is currently pretty robust. There are no current bugs that I know of, there were a slew of them when I made the datum change, but past that things are clean.

**Comment by necromanceranne** [comment]
It also isn't RESTRICTED to moths. It is discovered in moths, but literally anyone with the injector will be able to acquire the laser eyes. Which means this is basically a laser gun nobody can disarm of you (without mutadone), that you can distribute to literally everyone so long as you have the dna consoles open to keep printing out more injectors.

I think firebreath might have had some flags missing, or maybe goofs changes removed the nuiance necessary to stop it from flooring targets, but I don't find fire breath right now to be good either. It wasn't bad before but it wasn't particularly overwhelming, it'd be no different getting molotov'd. But now....it's really questionable.

**Comment by ATH1909** [comment]
bam, added lesser laser eyes

**Comment by ATH1909** [comment]
> It also isn't RESTRICTED to moths. It is discovered in moths, but literally anyone with the injector will be able to acquire the laser eyes. Which means this is basically a laser gun nobody can disarm of you (without mutadone), that you can distribute to literally everyone so long as you have the dna consoles open to keep printing out more injectors.

So, basically just hulk, but for anyone, not just the dominant species on the station? And it's harder to get? Sounds okay to me.

> I think firebreath might have had some flags missing, or maybe goofs changes removed the nuiance necessary to stop it from flooring targets, but I don't find fire breath right now to be good either. It wasn't bad before but it wasn't particularly overwhelming, it'd be no different getting molotov'd. But now....it's really questionable.

Note that, IIRC, firebreath is drastically more effective if you have the power chromosome for it and hit your target dead-on.

**Comment by ATH1909** [comment]
> > I'd add the zoom-out thing, but aren't different view settings really buggy right now?
> 
> Nope not at all. The zoom code is currently pretty robust. There are no current bugs that I know of, there were a slew of them when I made the datum change, but past that things are clean.

Hey, yeah, (a subtype of) the zoom spell from the knowledge devil contract looks like it might do. I'll replace lesser laser eyes with that; thanks.

**Comment by Iamgoofball** [comment]
why do fire breaths call explosion code?????????

**Comment by ATH1909** [comment]
alright, I cut out all of the (lesser) laser eyes stuff and added Far Sight to the game

**Comment by anconfuzedrock** [comment]
holy shit he actually did it the absolute madman I tried to give moths that mutation a long time ago and I Gave up but you did it in seconds and made it more nuanced than my attempt was even if this isn't merged you're incredible

**Comment by necromanceranne** [comment]
@iamgoofball you still willing to do that cone spell stuff? Firebreath would be epic for it.

**Comment by necromanceranne** [comment]
@ATH1909 Cool looks like you managed to salvage this pr very epic.

**Comment by ATH1909** [comment]
> holy shit he actually did it the absolute madman I tried to give moths that mutation a long time ago and I Gave up but you did it in seconds and made it more nuanced than my attempt was even if this isn't merged you're incredible

I mean I just copied the one from devils

**Comment by anconfuzedrock** [comment]
BRUHHH I DIDN'T KNOW THAT EXISTED

**Comment by LemonInTheDark** [comment]
F. It used to be kinda hellish trust me.

**Comment by Angustmeta** [comment]
Been instacrit before by a human geneticist using fireball. The explosion triggers all carried nades/C4. Laser seems less dangerous if the cooldown becomes low enough.

**Comment by Shadowflame909** [comment]
>
>Farsight is literally the Admin-Only view changer

>Combine that with X-ray and ill literally be able to see what everyone is doing on station

muhahaha antags btfo

**Comment by kriskog** [comment]
No. Increased view range is extremely strong in this game.  Adding that to genetics, particularly in the form of the devil spell, is a terrible idea. Not as bad as laser eyes, but not something I would like added.

Feel free to separate out the other stuff though.

**Pull request closed without merging**
