### PR TITLE
Makes ladders craftable

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Allows people to craft ladders using 15 metal rods. You need to build them on each z level you wish to get up and down from, on the same tile.

## Why It's Good For The Game

Part 1 of multi z qol. Makes chasms and what not a bit more tolerable, and easier for people to get up and down, assuming they planned it out. 

Once the json map stuff is merged I'd also like to add some sort of digging tool to people's emergency kits on icebox. 

## Changelog
:cl:
add: You can now craft ladders using 15 rods. Note: crafted ladders can only be connected to other crafter ladders.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
does this work inbetween the station and space because that could be a really stup- amazing way to space travel

**Comment by wesoda25** [comment]
Since icebox is the only current multi z, this won't work anywhere with space.

**Comment by Dennok** [comment]
> does this work inbetween the station and space because that could be a really stup- amazing way to space travel

We have jacob's ladder, necropolis chest loot. It build ladder that pierce reality and allow you move lavaland>space>station>space>>>

**Comment by ATH1909** [comment]
let people also craft 16 ladders out of 7 wooden planks as a minecraft reference

**Comment by Mickyan** [comment]
These are ridiculously cheap for what they do and may break map flow in many unforeseen ways, whenever someone puts a ladder in their map layout they are going to need to know exactly what's above and under them so that a random assistant can't just build a ladder in the middle of a hallway to gain access to a secure area

**Comment by wesoda25** [comment]
> These are ridiculously cheap for what they do and may break map flow in many unforeseen ways, whenever someone puts a ladder in their map layout they are going to need to know exactly what's above and under them so that a random assistant can't just build a ladder in the middle of a hallway to gain access to a secure area

Don’t let them get into the secure area in the first place (and stand still for 15 seconds).

**Comment by wesoda25** [comment]
Currently nothing on icebox where ladders could do such a thing (I think, I'll check later), and should the issue ever arise we could just make crafted ladders limited to connecting with other crafted ladders.

**Comment by Dennok** [comment]
> These are ridiculously cheap for what they do and may break map flow in many unforeseen ways, whenever someone puts a ladder in their map layout they are going to need to know exactly what's above and under them so that a random assistant can't just build a ladder in the middle of a hallway to gain access to a secure area

To build ladder to secure area you need place ladder IN secure area and UNDER secure area. Just some better than RCD floor and jump down.

**Comment by wesoda25** [comment]
Dennok I think they are referring to the possibility of people abusing this with existing ladders. Like back when we still had donut, it used ladders for it’s armory. With these changes someone could have gone above or below these ladders (in space) and infiltrated the armory relatively pain free. 

I’ll look into making crafted ladders linked to one another tomorrow.

**Comment by Dennok** [comment]
I dont understand what wrong in actual variant?
Ladders connects to ladders upper and lower. And you need build ladder on every level to be able use it.
Now you can't make hole from down to up. Build ladder and climb up.
And as i memorise, armory placed on top most level and you can't climb over on roof, make hole in floor and jump down.

**Comment by Dennok** [comment]
Oh. I think I understood something.
Make ladders work only on open space.

**Comment by wesoda25** [comment]
Ok crafted ladders can only connect to other crafted ladders now.

**Comment by cacogen** [comment]
So when I fall into a chasm on icebox I still have to play cave explorer to get out?

**Comment by wesoda25** [comment]
Unless someone above you is there to help or you planted one before falling, yeah

**Comment by Fikou** [comment]
whats the point if you cant connect to existing ladders

**Comment by Dennok** [comment]
Create new ladders.

We dont connect exist ladders since this can make easy way to acces restricted areas.

**Comment by wesoda25** [comment]
Mods please only you can make chasms less shit

**Pull request merged**
