### PR TITLE
Coffee Shop DLC - complete rebranding edition

### PR DESCRIPTION
**Pull request by disappointedButNotSuprised**
## About The Pull Request

After the triumphant success of its coffeemakers #68178 on NT stations Piccionaia Home Appliances rushes with another offensive to conquer the coffee market on the frontier!

new cafe

This pr remodels the meta station cafe, adds new coffee related items and puts new coffeemakers in some breakrooms on other stations. All added content is described below:

### The Impressa Modello 5 Coffemaker
obraz
Finally spess men can enjoy coffee made from **_fresh whole beans_** thanks to the Piccionaia coffeemaker premium product line. The machine is almost exactly the same as the old coffeemaker except it takes dried coffee beans instead of cartridges. Bags containing dried whole beans have also been added along.

### Syrup bottles
obraz
They function like a item version of a reagent dispenser and add sweet syrups directly to the coffee cup, they also have a nice pumping animation. The bottles are non-refillable and are cargo order-able only. There are now 3 (or 4) flavors available:
 - caramel syrup 
 - korta nuts syrup
 - coffee liqueur syrup
 - <sub>laughter syrup (only available as cargo contraband)</sub>

### Coffee condiments display
obraz
Its essentially a wooden box that displays the items inside, holds all the coffee extras:
 - coffee creamer
 - sugar packets
 - chocolate sprinkle
 - zero calorie sweetener

The sprite overlay changes according to the fullness of the box.

Then all the items are put to use in a renovated version of the corner cafe on meta station, complete with a new menu sign

last but not least, the coffeemakers have been swapped out for the new one at engi and cargo break rooms on tram station and added to the engi break room on delta station.
 
## Why It's Good For The Game

The cafe on meta station was sadly made little use of, new stuff gives a hope to revive the interest at least a little, It may also inspire some enthusiastic bartenders/cooks to become baristas. A few break rooms have also been outfitted with new coffeemakers to make then feel a little more unique.

## Changelog
:cl:
add: After a massive success of the Modello 3 series, Piccionaia Home Appliances rolls out a completely new coffeemaker and renovates the meta station cafe for free in a promotional campaign!
add: Syrup bottles, condiment displays, and more, to make the spess coffee experience even better
/:cl:

### CODE REVIEW

**Comment by calliophis-maculiceps** [comment]
this is adorable

**Comment by timothymtorres** [comment]
Suggestions:
- Add a shaker
- Add comfy sofas
- Remove the pill bottles (wtf are those even for?)

Other than that, this looks amazing! +1

**Comment by Wallemations** [comment]
I feel like the condiment box would work best if it had a radial menu to select what you want to take out.

**Review by Twaticus — APPROVED** [review]

**Comment by optimumtact** [comment]
This branch is totally fubar, you appear to have done a git rebase and rewritten the entire source history or something

**Pull request closed without merging**
