### PR TITLE
Tones down values for a lot of different hotspot_expose calls

### PR DESCRIPTION
**Pull request by deathride58**
Closes #38222 (It resolves the issue that it tried to hide via snowflake arg)
Reverts #38217 (Requested by Naksu)

:cl: deathride58
balance: Sparks, using welding tools, using igniters, etc, will no longer cause an instant fireless inferno in small rooms.
tweak: The revert of the original hotspot_expose() PR has been reverted, since the reason as to why it was reverted was resolved with this change.
/:cl:

See the diff for details. For reference, the first argument of the hotspot_expose() var is the target temperature of the exposure, and the second argument is the volume of gas that will be set to that target temperature.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
can you test with like charging shitcells with an inducers and rcds

**Comment by deathride58** [comment]
@Tlaltecuhtli  Already did. With this PR, they have a minor impact on atmos temp, but unrelentingly spamming them for a prolonged period of time on the same exact tile does eventually heat a room up. Heat being generated from minor heat sources, such as things that generate sparks, is realistic, since the station doesn't have thermostats or any other form of temperature control system, and seems to have perfectly insulated walls.

For cases like robotics, the heat generated from constantly welding things over prolonged periods of time in a single room can be counteracted by simply keeping a space heater in the room set to cool, but with these adjustments, it'll only be necessary to do so on downstreams like Citadel, which run 2 hour long rounds.

**Comment by Winterous** [comment]
I feel like there's no reason sparks should heat up the air, sparks have so little energy that it's hard for them to scorch PAPER. This just adds an arbitrary thing to worry about for a particle effect that only does this so that it can light fires.
Just a reminder that sparks do hotspot_expose when they spawn, every step they take, and when they die; a LOT of sparks will still cause significant heat, slowly, and for something so spammable why even have it heat the air at all?

And the reason I thought it would be a bad idea to go this route of tweaking the hotspot values of things is that it could have a major impact on how easy or difficult it is to light fires with some of these.
If that's not the case then there's no problem with doing it this way, I'm not sure honestly.

**Comment by Tlaltecuhtli** [comment]
^ 
also add the original pr to fuck up of the year 2018

**Comment by Jalleo** [comment]
#38224

**Comment by deathride58** [comment]
I've reverted the revert of the hotspot_expose() PR at the request of @vuonojenmustaturska 
image

@Winterous Sparks are pretty damn hot IRL. There's good reason as to why welders have to keep flammable materials as far away from things they're welding as possible, as one single spark is all it takes to set something flammable ablaze. Since that heat has to come from *somewhere*, applying the heating effect to sparks is realistic behavior, even if the heat is minor. IRL, in an area with ventilation, sparks and such won't really have any sort of effect on the room's ambient temperature unless there's a metric shitload of them in a short timespan, but in a space station with near-perfect insulation, sparks being able to heat rooms is realistic behavior, as the heat from the white-hot sparks is gonna be radiating into the air. The hotspot_expose values were previously 100% arbitrary values, even before the PR that made the proc heat up air, since calling hotspot_expose will cause a fire no matter the values used.

**Comment by KorPhaeron** [comment]
Our sparks are generally infinite and aesthetic though, they should just be 0 unless someone is willing to rework the sources of all sparks in the game

Realism arguments fall apart because sparks are generated from nowhere so the most basic laws of conversion of energy are violated

**Comment by Winterous** [comment]
^

And yeah if you're welding there's a lot of sparks produced (Why isn't that a thing in game by the way? That'd look cool.), and it can set dry, flammable materials on fire. And yes, sparks are very very hot, but the particles are so small that the amount of energy carried to make them that hot is negligible; the only reason they set things on fire is because they heat up a very small area.

Yes, it's realistic for sparks to have a very small effect on temperature, but considering the massive volume in which they can be produced with such incredible ease, and the fact that they're mostly aesthetic particles thrown around like confetti, I don't think it's a good idea for them to heat the air.

**Comment by Cyprex** [comment]
@deathride58 >downstreams like Citadel, which run 2 hour long rounds.
We regularly run 3-4h rounds on terry, 1 hour is short by our standards

**Comment by vuonojenmustaturska** [comment]
let's try this again

**Comment by vuonojenmustaturska** [comment]
"expose_hotspot values being absolutely bonkers and killing people" is not really a balance issue, you need not pay the GBP for it.

**Comment by 81Denton** [comment]
This looks much better than before. Spamming RCD sparks in the theater backstage for a minute only increased temp by ~10°C and door sparks no longer turn rooms into ovens.

**Pull request merged**
