### PR TITLE
Fixes being able to vote for maps which are outside their configured population range

### LINKED ISSUE #64618: Map population limits are being ignored/non-functioning
Reporting client version: 514.1561

## Round ID:
[177701](https://scrubby.melonmesa.com/round/177701)

## Testmerges:
- [Improves proccall admin circuit component. Adds the option to not resolve weakrefs for set variables and proccall admin circuit components.](https://www.github.com/tgstation/tgstation/pull/64564)
- [Adds moveloop bucketing, uses queues for the singulo rather then sleeps](https://www.github.com/tgstation/tgstation/pull/64418)

## Reproduction:
* Get over 40 people on the server
* Have them vote for a map
* Kilo is still on the list despite being disabled at higher populations

@Mothblocks says the variable is set, it just... doesn't work, for some reason. This should probably get fixed since high population on Kilo is absolute fucking hell.

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Fixes #64618 
Adds an alert for if a map with a set when it's population range is unsuitable for the current player count

Config pop range (From maps.txt.) was only ever checked for automated map rotation.
For map votes, it NEVER checked the supplied config's population range vs current population. 

## Why It's Good For The Game

Makes a config work as anticipated?

## Changelog

:cl: Melbert
fix: Fixes being able to vote for maps which are outside their configured population range (Such as Kilostation).
/:cl:

### CODE REVIEW

**Comment by Nexofas** [comment]
I tried to codedive but failed to inderstand what are the indended pop limits for each map.
It would good to see kilo on its intended pop anyways.

**Comment by TheVekter** [comment]
Based

**Comment by MrMelbert** [comment]
Test merge candidate to make sure the default configs don't make mapvoting actually impossible. They'll likely need to be updated.

**Comment by LemonInTheDark** [comment]
Why didn't this work exactly?

**Comment by MrMelbert** [comment]
> Why didn't this work exactly?

The loop that set up the map vote list just never checked pop limits, at all

**Comment by LemonInTheDark** [comment]
> > Why didn't this work exactly?
> 
> The loop that set up the map vote list just never checked pop limits, at all

so you're telling me the config values did literally nothing?

**Comment by MrMelbert** [comment]
> so you're telling me the config values did literally nothing?

The DID do something, they were only used for deciding which map to change to for automated map rotation.

**Comment by LemonInTheDark** [comment]
depression

**Comment by Ryll-Ryll** [comment]
this kills the kilo

**Comment by drIcepop** [comment]
> this kills the kilo

good

**Pull request merged**
