### PR TITLE
You know what I'm too lazy to fix map change conflicts someone else make RDS office not shit.

### LINKED ISSUE #23540: [Metastation] Modular computer in meta's RD office blocks off request console and AI restore console
low effort implementation to be honest.

### PR DESCRIPTION
**Pull request by silicons**
Showing  1 changed file  with 26,522 additions and 29,892 deletions.
26,522 additions, 29,892 deletions not shown because the diff is too large. Please use a local Git client to view these changes.
:cl:
rscadd: The modular console on Metastation has been moved so the RD can use their requests announcement console again!
/:cl:
new RD office
New RD office

Fixes #23540

### CODE REVIEW

**Comment by optimumtact** [comment]
For anyone wondering it's due to the map merger cleaning out the tile keys, which can happen from time to time.

**Comment by kevinz000** [comment]
K.

**Comment by jughu** [comment]
@kevinz000 just replace the ai restore console with the modular computer since like this it would look ugly and modular computer can download ai restorer soo

**Comment by kevinz000** [comment]
don't see how it would be any worse.

**Comment by jughu** [comment]
Theres a thing called design style then having consoles in your trophy room

**Comment by xxalpha** [comment]
The trimming threshold for unused map keys is 300, if this proves too low a number in the future feel free to give feedback.

**Comment by Arianya** [comment]
Why not leave the consoles as is and just pixeloffset the console so its reachable from the spot currently marked with a red X? Thats what we seem to do consistently with other wall mounted devices behind tables/dense objects/etc.

**Comment by jughu** [comment]
@arianya it be better if the ai interigery console gets removed and replaced with the modular computer since the modular had that function to restore ai's then just adding basically useless consoles to offices and have like 5 in them when a modular computer can function use their functions anyways

**Comment by Arianya** [comment]
@jughu This makes sabotaging the RDs office much easier though, all you have to do is smash one screen or steal one board and the RD now has to fetch a new one, which depending on the state of the round & R&D is easy to insane.

**Comment by jughu** [comment]
@arianya idk man they both basically the same replacing the ai intergery restorer with a modular computer wouldnt make a difference the only difference there be that there isnt like 5 computers in the office clustered as modular computers do the same as ai intergory console

**Comment by RandomMarine** [comment]
@Arianya But anyone can already go in and swipe the board? Only difference is that modular computers need more effort to rebuild from scratch if someone steals all the parts. Which, if you're RD and you're having problems assembling a goddamn computer then something's fucking wrong.

**Comment by Arianya** [comment]
Deconstructing/destroying 5 individual consoles is always going to be more time consuming and noisier then doing so to one modular console.

**Comment by jughu** [comment]
but who ever said you have to destroy all 5?

**Comment by Militaires** [comment]
@arianya how are the 4 other computers relevant

just assemble the fucking console you have parts out the ass if it gets sabotaged

**Comment by PKPenguin321** [comment]
>not censoring names from ahelps

**Comment by kevinz000** [comment]
How do I fix conflicts with maps?

**Comment by xxalpha** [comment]
You use the upstream file as a base and make all your changes from scratch.

Or you can use the map conflict fixer.

**Pull request closed without merging**
