### PR TITLE
Syndie Ebow Resprite

### PR DESCRIPTION
**Pull request by KingkumaArt**
## About The Pull Request

Changes the Syndie Miniature E-Crossbow sprite to look less flat

## Why It's Good For The Game

The Miniature E-Crossbow's sprites have always looked off to me, mainly because the shaft of the bow doesn't actually have any perspective to it, and is just a bunch of diagonal pixels. I decided to fix it by making the bow actually have a curved shape, and added shading to make it look like it was "behind" the main stock, instead of being vertical. It's a very minor change, but given the rest of the syndie weapon sprites look quite nice, I felt the Ebow deserved an update.

## Changelog

:cl:
imageadd: New Syindie ebow sprites
imagedel: deleted old syndie ebow sprites
/:cl:

### CODE REVIEW

**Comment by KingkumaArt** [comment]
Here's a comparison of the PR to the old sprite
bows

**Comment by Jackal-boop** [comment]
The new sprite looks more like a glock with a arch attached to it

**Comment by KingkumaArt** [comment]
> The new sprite looks more like a glock with a arch attached to it

Given it's an actual weapon I felt like the old version was a bit chunky and rounded so I put some more straight edges on it. I always imagined it being held in one hand, so a pistol was what I was going for.

**Comment by Wallemations** [comment]
> Here's a comparison of the PR to the old sprite, sorry that the image is a bit fuzzy.
> 
> bows
> 
> 

Apologies for being a bit daft but is the new one on the left or right?

**Comment by necromanceranne** [comment]
Left

**Comment by KingkumaArt** [comment]
> > Here's a comparison of the PR to the old sprite, sorry that the image is a bit fuzzy.
> > bows
> 
> Apologies for being a bit daft but is the new one on the left or right?

haha yeah, was originally going to clarify that, but the image didnt want to embed in the PR itself, so when I went to add a comment I forgot.

**Comment by Wallemations** [comment]
In that case, I like the bow but I don't like the handle. I think the handle could definitely use some work.

**Comment by LarissaMayrink** [comment]
The outline is too dark, its inconsistent with tg style

**Comment by YakumoChen** [comment]
Where is the sprite for the unloaded state

**Comment by KingkumaArt** [comment]
> 



> Where is the sprite for the unloaded state

I have it, I just didnt put it in the image. On the topic of the outline thing, the old ebow had an outline so I didn't want to change too much about it as a first PR, so I kept the colors the same. I'll change the outline colors if that would be best.

**Comment by KingkumaArt** [comment]
image
Update: New version without outlines on top, middle is old version with outlines, bottom is current IG sprites (wiki was out of date)

**Comment by YakumoChen** [comment]
honestly I kinda prefer the current sprites?

**Comment by Wallemations** [comment]
I don't think removing the outline from most of the sprite was the right move either, as the limbs of the bow have outlines but the body doesn't.
Another thing this made me realize is that your sprite doesn't show the full dart, just the tip, while the older sprite technically does.

**Comment by KingkumaArt** [comment]
> Another thing this made me realize is that your sprite doesn't show the full dart, just the tip, while the older sprite technically does.
Yeah, the sprite from the wiki didn't have the full dart which is what I based it on. Here's my fix I made, thoughts?
image

**Comment by Wallemations** [comment]
Certainly more interesting of a look, but you've also lost the texture on the body of the crossbow in the process

**Comment by RuneQuester** [comment]
> The new sprite looks more like a glock with a arch attached to it

So does the old lmao

**Comment by Mothblocks** [comment]
@tgstation/sprite-team please look

**Pull request closed without merging**
