### PR TITLE
Adds a new derelict to space ruins

### PR DESCRIPTION
**Pull request by Core0verload**
This PR adds a new derelict to space ruins rotation.
onehalf
It was a Syndicate plasma mining ship. Unlike NT, Syndicate was playing it safe, using small ships equipped with mining drones to mine plasma-rich asteroids. This ship was attacked by someone, probably NT, and now only one half of it is still around.

Loot:
- 1 blood-red hardsuit with syndicate mask (in the bridge floor safe)
- 1 folder with Syndicate documents (in the bridge floor safe)
- 2 diamond ores.
- 1600 credits in cash and coins
- 5 various first aid kits

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Pretty neato :+1:

**Comment by RemieRichards** [comment]
Should probably use ship turfs.

**Comment by PKPenguin321** [comment]
No, I think it is fine. It is an outpost, not a ship. Likely at some point a ship connected to it.

**Comment by RemieRichards** [comment]
@PKPenguin321 >It was a Syndicate plasma mining ship

sure sounds like THIS is the ship, which means ship turfs.

**Comment by coiax** [comment]
Problem is, shuttle turfs don't have much variation in style, you've got like 4 colours, and they're all VERY garish.

**Comment by FantasticFwoosh** [comment]
Looks like a nice place to patch up as drone.

**Comment by Core0verload** [comment]
NSV Luna was a ship, and this was Luna's mini derelict, back in the days when Animus was running a modified version of it. The point is, you don't have to use shuttle turfs to make something a ship, especially when you talk about cheap mining droneships mass produced by Syndicate.

The ship's engine, engineering and cargo bay were left on another half, which isn't included. I actually have a full layout of it, but it isn't much left if you remove all the turfs that were destroyed by the impact.

**Comment by Supermichael777** [comment]
the documents should be fakes marked "outdated documents" with the discription "Looks like theirs a nuclear attack happening in..... six months ago!"

**Comment by RemieRichards** [comment]
@Core0verload the point is the only way people know things are ships is because they use ship turfs and have ship equipment, you've already exploded the ship equipment off. this just looks like a station at present.

**Comment by Core0verload** [comment]
If the players want to think it was a station, I'll let them.

**Comment by KazeEspada** [comment]
Only issue i have with this is its too intact. This implies nt would show restraint destroying their enemies.

**Comment by optimumtact** [comment]
@KazeEspada there's nothing interesting about a few grilles and broken walls, so we have to take some liberties

**Comment by ChangelingRain** [comment]
I'd suggest using dark tiles instead of grey, or using the dark red tiles and having dark red be the main color. Syndicate stuff looks best in dark black and red.

**Comment by Bawhoppen** [comment]
Oh look more content without original assets.
The same exact walls, floors, computers, furniture, vending machines, chairs, lockers etc. and etc.
Listen I don't blame you for not being able to get original sprites for stuff, getting sprites is tough especially with WJ being temporarily absent, but we really need to keep making things have variety sprite wise. In real life if you go into a building, you don't see the same exact boring walls and floors.
This is why things like the alien saucer and survival pod are really nice, since they look unique and not from the exact same source.
I am at fault for doing this similar thing before, but I am planning to help fix up the already existing ruins. Next time you do something like this please try and get some variety to them.

(also cables on lattice?)

**Comment by Core0verload** [comment]
Give me some sprites and I'll add them. If you can't, go fuck youself, you cunt.

If we would have to do a new set of sprites for each locker, bed and floor tile to add any derelict/ruin, we would have none.

**Comment by Bawhoppen** [comment]
not every single part of one but you can't just have everything look the goddamn same but you need some variety
I'm probably going to have to change this one up too later on anyways I don't have sprites for something like this either right now

**Comment by coiax** [comment]
@Core0verload not taking sides on anything except this, @Bawhoppen is right, normal design language is to put the laid cables on catwalks rather than lattice. Given that you can't actually legally lay cable on lattice in game.

**Comment by KorPhaeron** [comment]
I don't think /tg/ players will care all that much either way about whether it's a ship/station whatever, but the downstream this map is intended for will likely appreciate it being an accurate recreation

**Comment by coiax** [comment]
The pool of "shuttle" tiles is really small, you have like 5 colours to choose from, and they're all INCREDIBLY garish. If it's a mining ship, stick some heaters and engines on the end. ENGINES == SHIP.

**Comment by RemieRichards** [comment]
It's a syndie ship though, so use the syndie colours.

**Comment by Bawhoppen** [comment]
I did say I was going to fix it even if he didn't himself did I not

**Comment by coiax** [comment]
I'm not sure if I know that much about syndicate design choices, but aren't they more a collection of different groups united by opposition to Nanotrasen? Why does every syndicate ship always have to be BRIGHT RED?

**Comment by RemieRichards** [comment]
@coiax red and grey, and it's a branding thing.

**Comment by Bawhoppen** [comment]
>ignoring my comment entirely

ree

**Comment by Core0verload** [comment]
Some of Syndicate's companies even work with NT, keeping their involvement secret. See Donk Co and Waffle Co.

The problem with painting the ship in Syndicate colors is that we don't have any Syndicate colors at all. Except the ones for shuttles, and the reason why they are not used is obvious: they suck.

**Comment by Dorsisdwarf** [comment]
I will totally sprite you a syndicate glass airlock and a syndicate sleeper

**Comment by Core0verload** [comment]
Thanks @Dorsisdwarf, it surely would help. But I think shuttle windows will look completely out of place.

**Comment by Bawhoppen** [comment]
I'm going to fucking murder all of you holy shit

**Comment by optimumtact** [comment]
You need to stop projecting so hard about a space ruin that will show up occasionally

**Comment by Core0verload** [comment]
@optimumtact, you ruined the joke by not ignoring Bawhoppen's comments.

**Comment by Dorsisdwarf** [comment]
sleeper

**Comment by Core0verload** [comment]
No open state?

**Comment by Dorsisdwarf** [comment]
I'll do that now.

**Comment by Dorsisdwarf** [comment]
sleepod

**Comment by Dorsisdwarf** [comment]
syndivend

Have a consolatory replacement BODA

**Comment by PKPenguin321** [comment]
Add those syndie sleeper sprites to the sleeper on the syndie shuttle please

**Comment by Core0verload** [comment]
Not sure. Those sprites don't look very good, especially poster ones. Maybe I'll use the sleeper.

**Comment by Dorsisdwarf** [comment]
D: Muh photoshop Hydra

**Comment by KorPhaeron** [comment]
>I don't think /tg/ players will care all that much either way about whether it's a ship/station whatever, but the downstream this map is intended for will likely appreciate it being an accurate recreation

**Comment by Core0verload** [comment]
I added Syndicate sleeper. It even has a special function: you can control it from the inside. Useful for self-healing.

**Comment by Razharas** [comment]
Ok

**Pull request merged**
