### PR TITLE
Inhand sprites for bedsheets

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Unique bedsheets now have their own unique inhand sprites. Moved bedsheet inhands into their own file.

## Why It's Good For The Game

Bedsheets good.

## Changelog
:cl:
imageadd: inhand bedsheet sprites
/:cl:

### CODE REVIEW

**Comment by Twaticus** [comment]
real talk how do i get rid of these fuckin old merge commits

**Comment by optimumtact** [comment]
start your next branch off upstream master instead
```
git fetch upstream
git checkout -b newcoolbranch upstream/master
```

**Comment by optimumtact** [comment]
or you know reset your own master to be the same as upstream/master
```
git checkout master
git fetch upstream
git reset --hard upstream/master
git push -u origin -f force
```

**Comment by optimumtact** [comment]
motivational_sloth

**Comment by wesoda25** [comment]
sheet

**Comment by ShizCalev** [comment]
#30081

**Comment by actioninja** [comment]
I squash before merge anyways

**Pull request merged**
