### PR TITLE
 Adds the Ligament Hook and Ligament Reinforcement bioware surgeries 

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Added two new surgery procedures, under the Experimental Surgery techweb node.
add: Ligament Hook makes it so you can attach limbs manually (like skeletons) but makes dismemberment more likely as well.
add: Ligament Reinforcement prevents dismemberment, but makes limbs easier to disable through damage.
tweak: Golem limbs can now be disabled, although they are still undismemberable.
/:cl:

The surgeries are mutually exclusive, of course.

### CODE REVIEW

**Comment by tralezab** [comment]
Does it make sense for golem limbs to be able to be disabled?

**Comment by XDTM** [comment]
They are limbs, break the right bits and they don't work

**Comment by Ratvar** [comment]
Can ligament hook be used to attach robotic limbs? Sounds... really nice.

**Comment by XDTM** [comment]
Yeah, you can do that. The weakness to dismemberment still applies, and it won't replace chest or head.

**Comment by AdamElTablawy** [comment]
Experimental surgery to add *more* limbs so that abductors can create nightmarish spider-people when?

**Comment by Ratvar** [comment]
Only when changelings can do it first

**Comment by Swiftkor** [comment]
Essential feature: if you are decapitated and you have this surgery your body stays alive and you can carry your head around, dullahan style

**Comment by Barhandar** [comment]
> tweak: Golem limbs can now be disabled, although they are still undismemberable.

>slowpokes that can't use ranged weaponry already  
>lets make them get fucked up by limb damage too!

**Comment by XDTM** [comment]
They still have internal organs. Although you do have a point there, it would probably make more sense the other way around with no disabling but potential dismemberment. Sadly we don't have a dismemberment resistance variable yet, or they'd be very-resistant-but-not-fully-immune to dismemberment.

**Comment by improvedname** [comment]
All these surgeries yet no power surgery tools...

**Comment by BebeYoshi** [comment]
I like it, but I think the golem thing is a little out of the scope of the PR, isn't it? (Even if I agree that they should be getting disabled)

**Comment by XDTM** [comment]
It's a byproduct of a refactor of dismemberment traits

**Pull request merged**
