### PR TITLE
ayys are more likely to visit the station

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Mothership Epsilon
tweak: All your base are belong to us.
/:cl:

why: ayy lmao

to put this in perspective, the blob's weight is 5 and things like vent clogs are weighted 100. weight 10 is equal to the mice migration event.

### CODE REVIEW

**Comment by kevinz000** [comment]
Oh yes let's make one of the most highly disruptive and indirectly destructive antags more common!

**Comment by lzimann** [comment]
Edit the title to match pr's content.

**Comment by Tacolizard** [comment]
kevinz they're still super rare. also wtf ayys are the least harmful antag in existence

**Comment by Iamgoofball** [comment]
@kevinz000 It's almost like that's it's purpose?

**Comment by factoryman942** [comment]
ayyy lmao

**Comment by Tacolizard** [comment]
previously, an ayy invasion was just as common as a random bleb, which seems overkill

**Comment by kevinz000** [comment]
@Tacolizard not really for a role that generates antags?

**Comment by Iamgoofball** [comment]
you didn't answer or refute my point

**Comment by PKPenguin321** [comment]
Does Kevin really think ayys are on par with blobs

**Comment by lzimann** [comment]
Abductors are nowhere as destructive as many other common events/antags, heck, they don't/shouldn't cause any kind of destruction besides make a person disappear for 5 minutes. That being said, not sure if this change is needed.

**Comment by Tacolizard** [comment]
@lzimann all this change is doing is accepting the fact that ayys ≠ blebs.

also ayys shouldn't spawn when there are only 5 people on station

**Comment by lzimann** [comment]
Editing the min players is ok, probably reasonable, don't really agree with the weight change though.

**Comment by Armhulen** [comment]
y

**Comment by Tacolizard** [comment]
because ayys are not blebs

**Review by Cyberboss — APPROVED** [review]

**Comment by FantasticFwoosh** [comment]
No, @kevinz000 do you EVEN KNOW **how powerful a tech boost ayy tools are**?

Say the ayy is more common and completely blows their chance, ultimately they might drop a abductor toolbelt with super advanced ayy tech going all the way up to ayy level 5 and to which it will allow you to print of superior ayy tools. 

This change might make very rare tools too common.

**Comment by Tacolizard** [comment]
Fwoosh this is only weighting it 5 higher than before.

**Comment by optimumtact** [comment]
It's a no from me :-1: These are antags and all mid round antags have very very low weight

**Comment by kevinz000** [comment]
@PKPenguin321 their objectives can generate pseudo antags and you know how wild players get in interpreting them...

**Comment by kevinz000** [comment]
@FantasticFwoosh that's not the point at all.
@Iamgoofball exactly why I don't like this.

**Comment by Tacolizard** [comment]
@optimumtact well ayys are pretty much the least destructive midround antag

**Comment by PKPenguin321** [comment]
@kevinz000 blobs just delete things and kill everyone...

**Comment by DoctoreMad** [comment]
Is it too late to say I agree with this?
Though Coiax's advice is better _though it makes me cry a bit because short rounds are a myth_

**Comment by lzimann** [comment]
It depends what you consider long. The average round is about 45 minutes nowadays.

**Comment by DoctoreMad** [comment]
I consider long when it passes the 1 hour mark.
Rounds lately have been full of murderboners and shuttle often has to be called the moment the refuelling ends because otherwise you have some 20 or so ghosts watching the game instead of playing it.

**Pull request merged**
