### PR TITLE
makes it impossible to add udders to carbons

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
udder component now returns COMPONENT_INCOMPATIBLE if parent is a carbon

## Why It's Good For The Game
possible moth milking vector destroyed

### CODE REVIEW

**Comment by optimumtact** [comment]
no justification given

**Comment by tralezab** [comment]
image

**Comment by Kylerace** [comment]
image

**Review by JohnFulpWillard — APPROVED** [review]

**Comment by Kylerace** [comment]
Alas, conflicts

**Pull request closed without merging**
