### PR TITLE
adds alternate medborg sprites

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds alternate medborg sprites

## Why It's Good For The Game

https://www.youtube.com/watch?v=bJMeQQBbd8Y

## Changelog
:cl:
imageadd: adds alternate medborg sprites
/:cl:

### CODE REVIEW

**Comment by trerri** [comment]
Does this use the mining borg skin picker or the service borg one? Since you're here, you could flatten them into one system.
Are you sure the two tile sprite won't cause issues? Will we be seeing variants like this for the other borg types?
As a silicon main, I'm pretty glad to see this since the tg borg skins have always been lacking compared to the excellent catalogue of unique and well-crafted sprites for servers like bay. I didn't know you were that good at spriting though, so keep it up!

**Comment by Jared-Fogle** [comment]
looks good unless someone wants to say anything otherwise

**Comment by Jared-Fogle** [comment]
you know in case theres some sort of issue with this anyone wants to bring up

**Comment by actioninja** [comment]
Oh cool I love wide robots

**Comment by Jared-Fogle** [comment]
i guess nobody had any issues with it

**Comment by LemonInTheDark** [comment]
speedmerge, someone open a revert

**Comment by TiviPlus** [comment]
awstp

**Comment by ShibaInuLord** [comment]
based

**Comment by MrDoomBringer** [comment]
Current Admins:
Adminhelps are also sent through TGS to services like IRC and Discord. If no admins are available in game adminhelp anyways and an admin will see it and respond.

**Comment by Jared-Fogle** [comment]
geez i havent seen people this worked up over a speed merge in a long time. whats so special about this pr

**Comment by ATH1909** [comment]
based

**Comment by dondonpow** [comment]
what is going on

**Comment by TheVekter** [comment]
You crazy bastard.




Keep it.

**Comment by Serxule** [comment]
unironically i want this to actually stay added since borgs haven't had new sprites in such a long time, and any new sprites are usually just revamped, not new ones. (if we get this far there's really no point in not merging medihound code too)

**Comment by LemonInTheDark** [comment]
no

**Comment by MrDoomBringer** [comment]
no

**Comment by katebishop49** [comment]
yes finally, a reason to erase my eyeballs.

**Pull request merged**
