### PR TITLE
Cogscarabs have a faster proselytizer but are worse at guns

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Servants of Ratvar can now reactivate Cogscarabs with a screwdriver.
tweak: Cogscarab proselytizers proselytize things twice as fast.
tweak: Cogscarabs now have 1.6 seconds of delay when firing guns, as much as an unmodded kinetic accelerator.
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
What's the point of being a cog scarab without being able to shoot people

**Comment by coiax** [comment]
Instead of nerfing cogscarabs, why not just make them Application level instead

**Comment by ChangelingRain** [comment]
That's a nerf, you dimwit.

**Comment by ChangelingRain** [comment]
They're not supposed to be super good at combat, they're supposed to \~build~

**Comment by coiax** [comment]
They're already solid non-ventcrawling drones with no access, and now they can't shoot guns? Just make a Clockwork artificer, it'll be super boring and non-OP.

**Comment by ChangelingRain** [comment]
"Can't shoot guns" is an exaggeration, they're just really, really slow shooters.

**Comment by collinxchu** [comment]
Being able to be brought back to life with a damn screwdriver is a great tradeoff for being shit at guns.

Silicons with guns are the worst thing in the game to begin with.

**Comment by coiax** [comment]
Drones and cogscarabs aren't silicons in the slightest.

**Comment by coiax** [comment]
Also, a repeated assumption that all ghost roles are only taken by killed people from the round, when actually there's a decently sized minority that just observe from the start.

**Comment by ChangelingRain** [comment]
They're "not silicons" except for the laws, the damage from EMPs, you know.

Also that last comment about 'ghost roles are only taken by killed people' is just kind of disjointed and unrelated???

**Comment by ShadowDeath6** [comment]
I never liked cogscarabs being combat, I'd prefer them unable to use weapons entirely and letting them use a slab from the start. Doesn't make sense for a cogscarab, which is intended to build/corrupt/whatever you call proselytizer-ing, to be used as stunprod cuff or taser cuff or laser whatever on people. This is a step in the right direction.

**Comment by coiax** [comment]
Making them able to use slabs is a HUGE power spike, and in SS13 _everything_ is a weapon.

**Comment by optimumtact** [comment]
Yes coaix everyone already knows you observe at roundstart so you can erp as a drone.

**Comment by Archie700** [comment]
Drones are much more dangerous with guns than silicons you dronelover.

There's a reason why F R E E D R O N Es are fucking terrifying to face.

**Comment by coiax** [comment]
Drones ARE more dangerous with weapons than silicons. But cogscarabs are dense, and hit by projectiles.

**Comment by anconfuzedrock** [comment]
why are they "worse at" why not unable to use?

**Pull request merged**
