### PR TITLE
Updates bucket flavor text.

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

I noticed how dull the flavor text for buckets is at the moment, this should make it a bit better.

## Why It's Good For The Game

It's not bad for the game.

## Changelog

:cl:
add: Updated the flavor text for the bucket.
/:cl:

### CODE REVIEW

**Comment by CoiledLamb** [comment]
what does this flavor text mean, though?
also isn't there like, an IC company you could reference? we have like 3 varieties of TCG that aren't copyrighted by real world companies

**Comment by Y0SH1M4S73R** [comment]
Honestly I think a better fluff description would be "Dear God."

**Comment by Jacquerel** [comment]
> what does this flavor text mean, though? also isn't there like, an IC company you could reference? we have like 3 varieties of TCG that aren't copyrighted by real world companies e: also you should probably put spellcheck rather than feature? unless you've got gbp to burn lol

wpcwqirqjijx

**Comment by Farquaar** [comment]
> Honestly I think a better fluff description would be "Dear God."

"There's more."

**Comment by Y0SH1M4S73R** [comment]
> > Honestly I think a better fluff description would be "Dear God."
> 
> "There's more."

NO!

**Comment by Time-Green** [comment]
This is weird

**Comment by carshalash** [comment]
> This is weird

It's for the best.

**Pull request closed without merging**
