### PR TITLE
Fixes drake fire breath multihitting

### LINKED ISSUE #20393: You can get hit multiple times by drake fire breath
How did I get from 100 to red health by getting hit with fire breath like 4 times in a row? ;-;

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #20393

### CODE REVIEW

**Comment by lzimann** [comment]
hugbox

**Comment by TechnoAlchemisto** [comment]
imho it makes sense that walking into more fire will hurt you more, you gotta get out of that shit quick or else you will burn to death, y'know?

**Comment by Ergovisavi** [comment]
On the one hand, I like this because it's a very unintuitive aspect of fighting ash drakes and has poor readability :+1: 

On the other hand, I dislike this because the ash drake probably doesn't need to be wimpier :-1: 

I don't know an actual good solution so complaining in the comments is the best option at the moment

**Comment by RemieRichards** [comment]
I disagree with this, there's no bug here.
this can only trigger from walking into YET MORE FIRE, you deserve what you're getting.
:-1:

**Comment by ChangelingRain** [comment]
It only triggers from running away from the fire breath, it's very not intuitive that you're going to randomly take double/triple/even more damage.

If this makes drakes too weak, it'd be a good idea to buff them; I don't think that any megafauna's power should come from something as unintuitive as this.

**Comment by TechnoAlchemisto** [comment]
Well this is pretty intuitive balancing IMO, it's like most MMOs where if something has a line AOE, you run to the side not backwards or forwards. It's pretty standard to boss fights to read their moves and switch directions to be out of the trajectory as soon as possible.

**Comment by ChangelingRain** [comment]
It's not intuitive that you'd take more damage running away as compared to running at it or standing still.
And unless kor says otherwise, I'm going to assume this was unintended, and we probably shouldn't balance around unintended, unintuitive things.

**Comment by KorPhaeron** [comment]
You take extra damage running back towards it as well because you get more fire stacks in each hotspot.

**Comment by Ergovisavi** [comment]
@KorPhaeron 

No, we're talking about receiving L.adjustFireLoss(20) multiple times because you're moving away from the dragon. This has nothing to do with fire stacks or hotspots.

**Comment by Kromgar** [comment]
It has to do with getting hit with 20 burn damage multiple times. Not being on fire

**Comment by PKPenguin321** [comment]
How is running out of the fire to escape it less intuitive than running into more fire

**Comment by Ergovisavi** [comment]
Because moving into fire in one direction is five hundred times deadlier than moving into fire in the opposite direction

**Comment by kevinz000** [comment]
>Runs towards gigantic fire spewing dragon while its spewing fire
>Only gets more firestacks which doesn't even immediately damage you (You DID bring an extingusiher, right?)
>Runs AWAY from fire blast
>Hit multiple times, GGNORE ;-;

**Comment by optimumtact** [comment]
Yeah the problem is that breath stream weapons do not actually work how they should (it's a wave that propagates out instead of a constant damage delivery over an area)

**Comment by Cheridan** [comment]
bosses probably shouldn't rely on weird/buggy behavior to be hard so

**Comment by lzimann** [comment]
don't run into fire if you don't want to get burned :^)

**Pull request merged**
