### PR TITLE
Resprites the Administrative/Debug modsuit.

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Tin, resprites the admin only suits cause it was using an old sprite. A really old sprite.

Admin suit spin

## Why It's Good For The Game

Resprites.

## Changelog

:cl:
imageadd: Administrative Modsuits have been resprited.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
yea

**Comment by Iamgoofball** [comment]
this doesn't look like the combine super soldier

**Comment by Wallemations** [comment]
I said it in the discord but I'll put it in here too for posterity; 
I like the design but I think that the heavy desaturation has lost some of the identity the original had. Not saying you should use the same colors as the original, but a more saturated blue would be nice.

**Comment by Ebin-Halcyon** [comment]
Converting to draft to give a second pass for the design after asking around.

**Comment by VladinXXV** [comment]
ive promoted myself to headcoder to block this pr until you bring the real flightsuit back as payment

flightsuit funny

**Comment by CRITAWAKETS** [comment]
sprite needs a lot more contrast and saturation on its own

it also doesn't really fit the admin suit, though it looks like it'd be good as some sort of command suit or an alternative skin for the sec modsuit (when made red or greyscaled)

**Comment by optimumtact** [comment]
venom suit when

**Comment by Ebin-Halcyon** [comment]
Closing this while i'm busy with real life stuff and have no time to sprite.

**Pull request closed without merging**
