### PR TITLE
lowers kilo's bombcap multiplier

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

uses the map json system to set kilo's bombcap multiplier to 0.7
maptainer approval:
image

## Why It's Good For The Game

i think it's a creative way to nerf bombs a little on kilo

## Changelog

:cl:
balance: lowers kilo's bombcap multiplier
/:cl:

### CODE REVIEW

**Comment by Sparkezel** [comment]
While its extremally hillarious I don't think that changing the balance of explosives is the right call to justify revelancy for kilo as an actual map. I understand that it was a lot of work to return Kilo back to more modern versions of tg, it might be the time to let it go.

**Comment by IndieanaJones** [comment]
I'd rather have Kilo than Tram.

**Comment by Pickle-Coding** [comment]
I think it would be interesting if the bombcap multiplier was raised instead, because the station looks like it will crumble any second now.

**Comment by moocowswag** [comment]
Kilo has a lot of (bigger) issues and changing the balance of explosives on a single map will go wildly against consistency.

Also, will this only effect TTVs? Will it affect bomb assemblies bought from uplink? Will it affect large chemical bombs?

**Comment by EOBGames** [comment]
> Based on this being tagged in so many issues, I'm assuming this is TM'd and actively being tested. Give me a ping when there's feedback.

It is being actively testmerged, I coordinated that with the keyholders prior to my current community break. I also had planned to personally observe rounds but my present situation somewhat precludes that. @Maurukas on second thought however I do wonder if this PR might be something we can't gather reasonable data on from testmerges, given its targeting quite a specific issue and will need a good sample size, and there's no guarantee we're getting Kilo running, or bombs being detonated on station, during the testmerge period. I'm thinking a full merge with a review period in a few months (let's call it 2 months from merge just for the sake of saying something concrete, with potential for extension if we've not got enough data by that point), where we can properly comb logs and quiz admins and the playerbase on whether they think it's had a positive effect might be a better way forward for this change. Your input welcomed, of course.

**Pull request merged**
