### PR TITLE
Fixes cargotech jumpsuit onmob sprite 

### LINKED ISSUE #7205: Cargo technician jumpsuit onmob sprites are missing
@paprika

### PR DESCRIPTION
**Pull request by phil235**
Fixes #7205 (by reverting paprka's changes to cargo tech jumpsuit)
Revert the cargotech jumpsuit sprite to the old grey+lightbrown shorts.

Fixes a couple jumpsuit not having the wrong or no inhand sprite. (captain jumpsuit had no inhand sprite for 2+ years and nobody reported it....)

Fixes Ian's armor sprite not showing.

### CODE REVIEW

**Comment by paprka** [comment]
My bad

**Comment by paprka** [comment]
Can you fix security jumpsuits rolling as well, apparently they break when rolled

**Comment by paprka** [comment]
Alternatively just like, close this PR since we have an icon freeze and I can't really do anything until this is merged

**Comment by phil235** [comment]
will do

**Pull request merged**
