### PR TITLE
Adds a random weapon spawn on the armory

### PR DESCRIPTION
**Pull request by BeeSting12**
I'm going to work a lot more on this once I get home tonight, this is just framework so far. I wanted the beginnings of it up on github to get maintainer/design lead feedback, because at the end of the day, as much as forum goers may like it, the maintainers decide whether it gets in the game or not.

What this will add:
- [x] Burst laser gun
- [ ] Laser sniper rifle 
- [ ] Bayonet. (code should be there made by kevinz, just need to make an item to put on regular guns)
- [ ] A spawner in the armory that will spawn a random weapon off a list, found [here](https://tgstation13.org/phpBB/viewtopic.php?f=9&t=13228)
- [ ] Removes DRAGnet and security temperature gun, puts them on the random gun list.

Why: Adds variety to security gameplay/new tactics. Gives a way for meme guns that aren't OP to see some use.

### CODE REVIEW

**Comment by Robustin** [comment]
I can't see this ending well, I wouldn't be thrilled about the HOS dunking my shit because some OP weapon was just sitting the armory.

Still DRAGnet and the temp gun are just stupid (for opposite reasons) so maybe it nets out.

**Comment by BeeSting12** [comment]
@Robustin 
The general plan is not to have OP stuff in the armory. I plan on having a burst laser which will fire lasers that do less damage in three shot bursts, a laser sniper rifle, which is double laser gun damage but has a considerable cooldown and a scope, leaving you vulnerable to people around you. Frankly the riot shotgun is better than both of these. 

My other plan is a bayonet, no real issue there. Temp gun/DRAGnet both will be removed as a constant spawn and placed on the table as well as a clusterflashbang, meteor shot, and a grenade launcher(?).

Absolutely none of this is OP and most of the time traitors have far better gear, not trying to turn this into an arms race or anything, just pointing out the fact. In a 1v1 with any of these weapons against a traitor at worst it's a whoever clicks the other first and at best it makes the fight more interesting

**Comment by Armhulen** [comment]
oh boy, my favvvvvorite 👁 👁

**Comment by BeeSting12** [comment]
This is the only part of the game they will be used at the moment. If maintainers want me to atomize I will but I don't see the point right now.

**Comment by ExcessiveUseOfCobblestone** [comment]
jumping in headfirst I see

**Comment by SyruseEln** [comment]
>removes tempgun
Into the trash it goes.

**Comment by Qbopper** [comment]
it would be a good idea to split them because not everyone who thinks "adds random weapons to armory" is a good idea also thinks "add more weapons" is a good idea

I get what you're saying but that's how people will interpret it

**Comment by deathride58** [comment]
Tempgun and dragnet are actually pretty damn robust. Making their spawns 100% RNG based is nothing but a bad idea.

**Comment by BeeSting12** [comment]
The point is to vary security's gameplay. I could leave them in the armory and add a random spawn but it feels kinda like a straight buff at that point and I'd like to avoid making it look like I'm the new steelpoint sec buffs only guy

**Comment by BeeSting12** [comment]
Scoping in is apparently broken so probably a no on the scoped laser rifle for now.

**Comment by BeeSting12** [comment]
Burst laser's done codewise, I'll apply sprites later on. Laser rifle would work if not for the scope-in breaking, which isn't my fault, this occurs with scope guns. Also need to lower the cell size or make it consume more energy. The latter would make more sense I guess.

**Comment by BeeSting12** [comment]
If removing the security temperature gun and dragnet is so unpopular I can leave both and add this as an additional spawn.

**Comment by AnonymousNow** [comment]
It'll add some variety and chaos to security, and encourage them to get out of the mire of thinking that currently plagues it.

**Comment by Steelpoint** [comment]
Don't remove the Temp Gun and DragNET, they are both good weapons in the right circumstances

**Comment by BeeSting12** [comment]
okay the people have decided, ill just add this random spawn without taking out the temp gun and dragnet

**Comment by DoctoreMad** [comment]
If you leave both this is a security buff isn't it
Not that that's bad but choices choices

**Comment by BeeSting12** [comment]
Yeah I know wasn't trying to make it look like a sec buff, just a fun little thing for sec to have to add variety

**Comment by Bawhoppen** [comment]
This is a poor execution of an okay idea.

Ideally you'd want to add a lot of new types of guns with differing unique aspects to them, rather than just cheaply reusing crap we already have.

**Comment by BeeSting12** [comment]
Don't feel like this is popular enough to get merged, nor do I feel like arguing over every damage point of every gun that I add into the armory.

**Pull request closed without merging**
