### PR TITLE
Pixel Projectiles 3.0: Electric Boogaloo

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Paprika, Crystalwarrior, RemieRichards
experimental: Changes projectile pathing to follow a direct line, also known as pixel projectiles.
/:cl:

credit to original hippie PR and Crystalwarrior
https://github.com/HippieStationCode/HippieStation13/pull/1100
credit to paprika for fixing it up to work for modern tg audiences

Reflectors are commented out for now due to problems with not having the mathmatical equations to calculate where the laser needs to reflect to. If someone can supply the proper math that'd be rad.

This PR changes projectiles from flying on a terrible precalculated path that we all know and love to using proper collision. It would be easier to show than explain, so see below: 
awxz8ya

Furthermore, this PR changes no projectile sprites and adds sounds for collisions with walls (misses). These projectiles add dynamic spread for automatic (burst) weapons (such as the mech LMG) and shotguns.

This PR also tweaks the Marauder zoom to work better on different scales. Credit to CrystalWarrior.

Some gifs:
epic
meme

### CODE REVIEW

**Comment by Iamgoofball** [comment]
paprika said to do @phil235

**Comment by duncathan** [comment]
Can we see a gif of reflector behavior?

**Comment by WJohn** [comment]
So to clarify, are projectiles still going to hit based on the tile they're on or whether they actually hit the tip of your sprite? Would being a bigger/smaller sprite make it easier/harder to get hit?

**Comment by Delimusca** [comment]
@WJohn pretty sure projectiles still move by x/y locs under the vector they travel, so that mspaint comparison with the triangles pointing to crossed tiles should still be accurate.

**Comment by PKPenguin321** [comment]
SS13 GLOBAL OFFENSIVE :man: :gun: HEADSHOTS WHEN

**Comment by MrPerson** [comment]
Why exactly is goofball pring this?

**Comment by Iamgoofball** [comment]
@MrPerson paprika can't, but I want pixel projs, so it works out

**Comment by MrPerson** [comment]
What do you mean can't? Like we're blocking him for some reason?

**Comment by Iamgoofball** [comment]
@MrPerson Someone emailed github and had him repo banned. He literally can't comment or open PRs.

**Comment by PKPenguin321** [comment]
paprka's ban is kinda pointless considering hes unbanned on even the forums now

**Comment by Iamgoofball** [comment]
this isn't what the PR is about, keep comments to the PR only

**Comment by PKPenguin321** [comment]
true

but yeah anyways as long as this still has about the same level of accuracy as the current system and doesnt require pixel-perfect HIGH SKILL INTENSIVE PRECISION xX_360_Xx then it's fine

i'll still joke about headshots tho

**Comment by Niknakflak** [comment]
In both other versions of this PR
>We tested this already and it was garbage, what changed

**Comment by Bawhoppen** [comment]
>attempt 3

>electric boogaloo

**Comment by Jazaen** [comment]
Fusion powered boogaloo!
Also, this will mess with SM engine on birdboat.

**Comment by Dorsisdwarf** [comment]
Paprika is GTFObanned from github on the basis that he single-handedly caused the player/coder divide to become an actual thing with his shitty changes, arrogant dismissal of non-coders, and a complete refusal to listen to feedback. 

I presume this PR is a sort of olive leaf from him to Cheridan (Who had him repo-banned)

**Comment by Fox-McCloud** [comment]
>but yeah anyways as long as this still has about the same level of accuracy as the current system and doesnt require pixel-perfect HIGH SKILL INTENSIVE PRECISION xX_360_Xx then it's fine

Projectile *collision* is still the same, meaning that if it's even remotely on the same tile as the person you're on, it's going to hit them; @CrystalWarrior even made a comment that pixel-perfect accuracy would be a *bad* thing and result in a lot of really strange behaviors.

**Comment by Iamgoofball** [comment]
@Dorsisdwarf we aren't discussing that in this PR

**Comment by Razharas** [comment]
This proxy coding thingie needs to stop really
@Cheridan unban paprika already

**Comment by Anonus** [comment]
How does this work with juggernaut beam reflection?

**Comment by Fox-McCloud** [comment]
@Anonus 

More or less the same; it can reflect it right back, or it can reflect it in a random direction--just like energy shields and the abalative armor.

**Comment by Iamgoofball** [comment]
@optimumtact need a defib

**Comment by optimumtact** [comment]
https://github.com/optimumtact/-tg-station/tree/pixelprox

**Comment by Iamgoofball** [comment]
Thanks fam, I'll reopen this and health doll on that soon (tm)

**Comment by Razharas** [comment]
@MrStonedOne 
This needs live testing before it can get in

**Comment by Iamgoofball** [comment]
we did do testing

**Comment by MrStonedOne** [comment]
Well... Lets do some more.

Test merge in process.

**Comment by Razharas** [comment]
How are the results?
@Iamgoofball 
@MrStonedOne

**Comment by MrStonedOne** [comment]
Fix reflectors and it should be good to go

**Comment by Razharas** [comment]
@Iamgoofball 
You heard him fam

**Comment by Iamgoofball** [comment]
1. i can't make commits to this, unless @oranges wants to do the reflector changes on his branch and we speedmerge that one
2. trying to fix this was BYOND me, I tried 3 different methods of fixing the reflector code and it didn't work
3. fuck

**Comment by Razharas** [comment]
So you made a pull request of a code that was made by paprika and that is only accable to oranges
Aight
Fine
I see
I get this

**Comment by Razharas** [comment]
http://www.youtube.com/watch?v=IdhPB2Ow6p4

**Comment by optimumtact** [comment]
you were supposed to fork my branch to your own repo, not just reuse it

**Comment by Iamgoofball** [comment]
oh

**Comment by KorPhaeron** [comment]
I am willing to let reflectors die to get better guns

**Comment by JJRcop** [comment]
it would be sweet to use this so that a projectile may be able to bounce off any wall :)

**Comment by tkdrg** [comment]
@Iamgoofball @optimumtact @paprka fix this shit

**Comment by optimumtact** [comment]
not my problem

**Comment by Iamgoofball** [comment]
Real life happened, dont expect updates till the weekend

**Comment by optimumtact** [comment]
update to latest master
git rebase -Xignore-all-space upstream/master

**Comment by tkdrg** [comment]
@Iamgoofball weekend was 1 week ago

**Comment by optimumtact** [comment]
stop being so needy

**Comment by tkdrg** [comment]
I'm sorry for being annoyed at stale prs cluttering the list

**Comment by Fox-McCloud** [comment]
Don't let this die, @Iamgoofball

**Comment by Iamgoofball** [comment]
Objectives takes priority

**Pull request closed without merging**
