### PR TITLE
fixes sodium thiopental bottle

### PR DESCRIPTION
**Pull request by Iamgoofball**
you saw nothing

### CODE REVIEW

**Comment by Cheridan** [comment]
:cop: :e-mail: :spaghetti:

**Comment by Xhuis** [comment]
one job

**Comment by RemieRichards** [comment]
copy spaghetti, as cheri said.

**Comment by Iamgoofball** [comment]
3===============================================================================D

**Comment by Xhuis** [comment]
goofball is a mature and quality coder who contributes so much to /tg/

**Comment by Thunder12345** [comment]
Nothing to see here, move along

**Pull request merged**
