### PR TITLE
Makes box Atmospherics a little less awful.

### PR DESCRIPTION
**Pull request by theOperand**
- Added some r-walls instead of ALL FULLTILE WINDOWS ALL DAY.
- Added an external airlock so atmos techs dont have to ask the AI to let them into engineering to use their airlock.
- stretches atmos by one tile to make it VERY SLIGHTLY less cramped.

seriously box atmos is awful as shit, especially when compared to GLORIOUS LUXURIOUS SPACIOUS META ATMOS.
2015-04-17 19_43_26-tgstation _maps_map_files_tgstation_tgstation 2 1 3 dmm - dream maker

### CODE REVIEW

**Comment by PKPenguin321** [comment]
i'll miss the windows if only because whenever there was a bluespace anomaly in atmos it would cause a giant wall of windows to appear somewhere on the station
this is okay though since it just makes the giant wall only a teeny bit less giant
:+1:

**Comment by Saegrimr** [comment]
Looks great, that airlock was desperately needed. I ended up just building my own most of the time.

**Comment by Ikarrus** [comment]
>seriously box atmos is awful as shit

It was the one room that I couldn't be assed to remap because mapping atmos is suffering

**Comment by Miauw62** [comment]
the biggest issue is that it is just sooooo cramped. it's stuck between medbay and the incinerator on one side and engineering on the other side, so you can't expand it, whereas on meta it's exposed to space proper and has as much space as is needed to the west and south.

**Comment by xxalpha** [comment]
:+1:

**Pull request merged**
