### PR TITLE
Revert "Smooth movement"

### PR DESCRIPTION
**Pull request by lzimann**
Reverts tgstation/-tg-station#16570

I was going to wait a bit, but lots of people didn't like it so I decided to push the button.

[Feedback thread about it](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=6341)

### CODE REVIEW

**Comment by optimumtact** [comment]
We're not going to unmerge this for at least a month and a poll after that point.

This will require you to adjust

**Comment by Zilenan91** [comment]
I enjoy our new movement overlords

**Comment by ChangelingRain** [comment]
I dislike it!

**Comment by RemieRichards** [comment]
It really just does NOT feel good.

**Comment by Lexorion** [comment]
It's terrible in my opinion,I really dislike it.

**Comment by Cebasiz** [comment]
i don't know man i never thought movement was bad before

????

**Comment by Fox-McCloud** [comment]
Give it a try first--any major changes like this inevitably generate controversy and are hated, at first (need I mention the movement speed nerfs and universal stun reduction nerfs)---but, over time, people's opinions change on it.

Personally, :+1: to smooth movement--doesn't feel like I'm playing on some grid-based dungeon scroller.

**Comment by Shapsy** [comment]
Your speed constantly fluctuates, people constantly jitter and jaunt forwards and backwards, and it's almost impossible to round corners without coming to a complete stop first. Movement was fine as is, this is gross

**Comment by KorPhaeron** [comment]
>Give it a try first

We did that's why we're upset

**Comment by Incoming5643** [comment]
You've heard my opinions on this, please stop trying to break then game on the most basic of levels for obtuse future benefits no one cares about.

**Comment by bgobandit** [comment]
This literally gives me nausea and motion sickness.

**Comment by TechnoAlchemisto** [comment]
Yeah I've also had some issues with motion sickness, and eye pain. 

Reminds me of that niknak event where he made himself a hobbling old man. It was certainly worth testing, but I don't think I can do a month of this.

**Comment by Cebasiz** [comment]
this new movement is literally terrible who even thinks this was desirable at all what the hell even are the advantages it's like i'm playing in constant lag 

W 
H
Y

**Comment by Durkel** [comment]
It's Jarring on the eyes and just awful in general. Honestly one of the reasons I don't even play on other servers is because of this movement type.

**Comment by Cebasiz** [comment]
DID YOU GUYS EVEN TEST WHAT THIS DOES TO AI EYE OH MY GOD THERE'S LIKE WORLD POP-IN IN A TWODEE SPACEMAN GAME WHAT THE HELL GODDAMN FUCK REVERT IMMEDIATELY THANKS

**Comment by PKPenguin321** [comment]
this shit gives me a migraine

**Comment by F-OS** [comment]
kill smooth movement with fire!!

**Comment by Incomptinence** [comment]
Sheesh what won't oranges suck up to.

**Comment by Aloraydrel** [comment]
How do people play with this shitty movement? Everything jitters when you run and looks terrible. Remove post haste

**Comment by optimumtact** [comment]
@Incomptinence how exactly would you classify that as sucking up?

**Comment by Incoming5643** [comment]
For the record this is now test merged, so if anyone says they can't tell the difference between normal movement and smooth movement, it's because smooth movement isn't on

**Comment by ChangelingRain** [comment]
IT'S TESTMERGED BUT IT'S THE SAAAAME AUGH

**Comment by lzimann** [comment]
@ChangelingRain Probably because the fps is set at 24 for some reason

**Comment by optimumtact** [comment]
our base fps has always been 24 as far as I know

**Comment by lzimann** [comment]
It was 20 before this if I'm not mistaken

**Comment by optimumtact** [comment]
I'll bow to your superior admin knowledge

**Comment by topham1** [comment]
it's like playing my 2d spess mens game with a migraine and only one contact in

**Comment by Incoming5643** [comment]
I seem to  remember at some recent point that MSO said the "normal" fps before he started futzing with it was 17

**Comment by MrStonedOne** [comment]
ya, when i merged smooth movement, I also raised the fps to 24, it was 20 on sybil and 17 on bagil, it used to be 17 on both before april fools when i raised it on sybil for kicks. could it maybe be that the higher fps is the cause? I could try lowering it back to 20 or 17 with smooth movement to see.

The normal fps is 11fps, that's how it was before i became host and started fucking with it. I will point out that if i raised it up to 20 when it was 11, people would bitch, but when i slowly did it, one fps at a time, over days, nobody cared, and they like the new fps rate, as its better then the 11fps you will see if you run a test server.

Honestly, the jitter is a client side byond bug that should hopefully be fixed, a report is up,

The issues with rounding a corner isn't actually anything this changes, as all this changes is changing how your client handles gliding mobs between tiles when they move, it allows for more flexibility by the client in that regard. all game code around movement is the same.

How ever I have a better idea, if 11 fps is good for 8px glide_size, lets make it 4px glide_size at 22fps.

**Comment by Iamgoofball** [comment]
@MrStonedOne you motherfucker I thought the FPS clamper was triggering on test for some reason, I didnt know we left the default at 11

we better fix that

**Comment by Dorsisdwarf** [comment]
Smooth-move looks like garbage and makes ghosts virutally unusable

**Comment by Bawhoppen** [comment]
:+1:x:100: the smooth movement really was truly awful

**Comment by KorPhaeron** [comment]
@MrStonedOne 

Can we revert this until the byond fix is done then? Very easy to change back and forth until it works right

**Comment by MrStonedOne** [comment]
Ya, that works

**Comment by KorPhaeron** [comment]
Alright, Cheridan is UPVOTING it, MSO okays it, it's bugged and we'll try again once the the bug is fixed. I hope I have covered my bases for avoiding a stupid revert war or something.

**Pull request merged**
