### PR TITLE
Demontest pr

### PR DESCRIPTION
**Pull request by lordpidey**
This is the branch I'm using to TEST demon related things.
See #15794 for the main PR.
Probably conflicts with #16061 and #16026

Demons are still adminfuckery only (use the traitor panel to turn someone into a demon)
The anti-demon tools are only on box and meta.  Don't make demons on other maps, the crew won't be able to properly combat the demon.

:cl:
rscadd: Infernal demons have been seen onboard our spacestations, offering great boons in exchange for souls.
rscadd: Employees are reminded that their souls already belong to nanotransen.  If you have sold your soul in error, a lawyer or head of personnel can help return your soul to Nanotransen by hitting you with your employment contract.
rscadd: Nanotransen headquarters will be bluespacing employment contracts into the Lawyer's office filing cabinet when a new arrival reaches the station.  It is recommended that the lawyer create copies of some of these for safe keeping.
rscadd: Due to the recent demonic incursions, the station library has been equipped with a demonomicon to help research demonic weaknesses.  Please note that reading this book may have unintended side effects.  Also note, you must spell the demon's name exactly, as there are countless demons with similar names.
rscadd: When a demon dies, if the proper banishment ritual is not performed on it's remains, the demon will revive itself at the cost of some of it's power.  The banishment ritual is described in the demonomicon.
rscadd: When a demon gains enough souls, It's form will mutate to a more demonic looking form.  The Arch-demon form is known to be on par with an ascended shadowling in power.
/:cl:

### CODE REVIEW

**Comment by lordpidey** [comment]
Closing this until it's ready.  True-demon form's UI is refusing to work, and somehow it's also made true-demons immortal.

**Comment by TrustyGun** [comment]
wew lad, i'm not ready?

**Comment by lordpidey** [comment]
Aright, I've fixed the hud and death errors.  It should work now.

As far as balance, well, that's up in the air.

**Comment by duncathan** [comment]
PRs don't need to be open for test-merge; so I'll just close this

**Comment by lordpidey** [comment]
oh, right, thank you for closing it.

**Pull request closed without merging**
