### PR TITLE
Fixes grilles.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Zilenan91** [comment]
Is this a reference to something

**Comment by PKPenguin321** [comment]
There are no grilles on the internet? Or is this a different meme

**Comment by KorPhaeron** [comment]
sign me the FUCK up 👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌th 👌 ere👌👌👌 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by KorPhaeron** [comment]
Okay goof wants more attention so I'm reopening this so you can appreciate his joke

**Comment by Supermichael777** [comment]
HEH @Cheridan

**Comment by TehZombehz** [comment]
We need deep discussion to determine the joke in this meme PR.

**Comment by Niknakflak** [comment]
:-1:

**Comment by Bawhoppen** [comment]
@Niknakflak :-1:

**Pull request closed without merging**
