### PR TITLE
Adds techpriest robes and adds them to the RoboDrobe

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus, Arathian
 Add: The robotocist now has robe to show his love for toasters
/:cl:
 
https://cdn.discordapp.com/attachments/588270796477169674/602861473332592650/75ea685ca60dad15f632e02da5d54dc5.png

### CODE REVIEW

**Comment by nemvar** [comment]
Should be in hacked items

**Comment by dr-bee** [comment]
Add it to the Chaplain vendor as well, it is honestly in their wheelhouse as well.

**Comment by Qustinnus** [comment]
i dont think it has to be hacked to spawn an aesthetic item only

**Comment by nemvar** [comment]
There's precedent for hacked vendors having cosmetic items. I also think that by default, more *serious* job should not have any such immersion-breaking reference items, it makes no sense for NT to supply robos with techpriest robes. Hacking creates the perception of this item being more rare, thus it fullfills it purpose as a funny reference better.

Also techpriest skirts.

**Comment by Arathianen** [comment]
If people strongly agree with it being in hacked items, I got no problem with it, although I saw it more as a small reference cosmetic item to grab at round start if you want.

I mean, robos can easily hack their vendor so it's not a big deal either way.

**Comment by GuyonBroadway** [comment]
[](https://youtu.be/P_ov7QSm4Kc)

Option to start as a heavily augmented chaplain wearing these robes when?

**Comment by nemvar** [comment]
dab on them conflicts

**Comment by GuyonBroadway** [comment]
Recite the litany of git fetch!

**Comment by MrFluffster** [comment]
I too think it works better as a hacked item. It's a neat reference but we already have boatloads of those and I think it's better to try and keep future ones a bit more out of the way. It's not like hacking vendors is even hard.

**Comment by AcapitalA** [comment]
I do like the fact that roboticists get this outfit added to their drobe, but then again doesn't this fit the chaplain too? I mean, seems weird since it would really fit with both.

**Comment by gamefreak2998** [comment]
Cyber dongs when?

**Comment by PKPenguin321** [comment]
looks vaguely like a secborg 👎 👎 👎 👎 👎 👎 👎

**Comment by Arathianen** [comment]
By the way, it was changed to require hacking the wardrobe now.

We could technically add it to the chaplain wardrobe too, but not sure about this one personally. Toaster worship is more in the realm of science and robotics than a "proper" chaplain.

**Comment by GuyonBroadway** [comment]
Sorry, they're adding a tech*priest* and you think that this ISN'T something a chaplain might find interesting?

**Comment by Qustinnus** [comment]
chaplain has 10k outfits he can smd

**Pull request merged**
