### PR TITLE
The MULE's "run your dumb ass over" attack now respects armor

### PR DESCRIPTION
**Pull request by Incoming5643**
This attack does between 40 and <b>120</b> damage. Previously this damage was assured no matter what sort of armor you were wearing. This at least gives people a chance to survive if they meet with the terror that is a player MULEbot.

Keep in note that this attack is also a chainstun in the hands of a player MULEbot, so any "fighting chance at survival" here is strictly theoretical unless you have access to some sort of teleport.

### CODE REVIEW

**Comment by Zilenan91** [comment]
Wait wait wait, this did fucking RnG damage?!?!?!

Holy shit why do people not hack these every round.

**Comment by GunHog** [comment]
It is also insane that no one discovered the Rogue AI MULE botcall trick.

**Comment by MMMiracles** [comment]
@GunHog 
reveal your SECRETS

**Comment by kevinz000** [comment]
Make it respect telearmor too. :)

**Comment by Cebasiz** [comment]
what it really needs is the ability to pick up mekhi and slam him down on a table repeatedly.

**Comment by tkdrg** [comment]
i killed incoming with this so that's why he's nerfing it

**Pull request merged**
