### PR TITLE
Makes flashes, & flashbangs flash

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
fix: Flashbangs will now make a sound if nobody is around to see them. (honk)
tweak: Flashbangs now come with sparks and will also light things up around them on detonation!
tweak: Flashes, flashers, flash powder, and cameras also now produce lighting! Woo!
fix: Cameras will no longer give you a prompt when alt-clicking them while not adjacent to them.
/:cl:

[why]: #
because it just makes sense

Flashbangs (ignore the lighting on the sparks, that's from a different fix PR):
https://gfycat.com/NeglectedWeepyAmethystinepython

Flashes / flashers (they can also have their lighting effects vareditted for badminery):
https://gfycat.com/GrayConsiderateBrahmanbull

(Flash powder is essentially the same as a flash, but scales depending on the amount of powder consumed.)

### CODE REVIEW

**Comment by Mickyan** [comment]
could you add this to the camera as well

**Comment by davethwave** [comment]
Welp, stealth revs no more.

**Comment by ShizCalev** [comment]
@Mickyan What camera?

**Comment by PKPenguin321** [comment]
Haven't checked the code but does this fix https://github.com/tgstation/tgstation/issues/40144 ?

**Comment by ShizCalev** [comment]
@PKPenguin321 no, this only adds visual FX.

**Review by Cyberboss — APPROVED** [review]

**Comment by Poojawa** [comment]
Cyberboss breaking 24 hour rule reee 📯

**Comment by Cyberboss** [comment]
So fire me

**Comment by Poojawa** [comment]
`if(world.time <= 24 HOURS)`
       `qdel(Cyberboss)`

**Pull request merged**
