### PR TITLE
Fixes lavaland atmos

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I mean sort of. Maybe I should just remove afterchange? I dont know how else to do this please send help

### CODE REVIEW

**Comment by optimumtact** [comment]
@duncathan can you cast your experienced eye over the issue here.

**Comment by optimumtact** [comment]
Irregardless I'm not sure this is the correct fix

**Comment by duncathan** [comment]
this is not the correct fix but I'll need a while to remember what is correct
DNM

**Comment by pudl** [comment]
@optimumtact irregardless.........

**Comment by PKPenguin321** [comment]
kid................

**Comment by KorPhaeron** [comment]
This isn't the right way but it's currently the only solution offered

**Comment by optimumtact** [comment]
Hey, it's your fun eral

**Pull request merged**
