### PR TITLE
Add pissy shitties, the classic American movie theater snack

### PR DESCRIPTION
**Pull request by OnlineGirlfriend**
## About The Pull Request

As we all know, pissy shitties is a delicious movie theater snack from America. All Normal people have combined popcorn and cola at some point, and as such, I've introduced this delicacy to the game. You can now enjoy a sugary, soda-soaked bag of microwaved corn. Yum.

## Why It's Good For The Game

For the luls. But seriously, I'd like to see more toppings on popcorn in the future (but of course, pissy shitties is THE classic combination). Also, check out that sprite!

## Changelog
:cl:
add: pissy shitties popcorn snack
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I'm declaring this a european server

**Comment by OnlineGirlfriend** [comment]
it was good while it lasted

**Comment by bluetshirtguy** [comment]
I'm utterly perturbed good sir, **pissy shitties** is a cultural icon and I beg you to reconsider.

**Comment by vkalls** [comment]
I'm American and I LOVE pissy shitties, I eat them along with my daily steak and 5 gallon bucket of soda. I even feed some to my pet eagle sometimes.

**Comment by Memedoktor** [comment]
Fucking thank you oranges this shit is not real and i refuse to accept that its even feasibly possible. This is an affront to god and america itself.

**Comment by interestingusernam3** [comment]
>I'm declaring this a european server

Does this mean I can finally say the N word

**Pull request closed without merging**
