### PR TITLE
Branches Syndicate Bundle into A and B Categories, adds Mr Freeze Bundle

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Separates Syndicate Bundles into two different categories, A and B, selling for 20 TC each. Category A focuses on strategical bundles, which consist of certain items which push for a certain play style, but are still reasonable to obtain green text with. Category B focuses on gimmicky item matchups, with the flavor text/lore of it being the gear of famous syndicate agents of the past. 

## Why It's Good For The Game

I feel its better to separate the two since different people choose the bundles for different reasons, and now this helps them select easier what they actually want. 

## Changelog
:cl: wesoda25
tweak: diverts Syndicate Bundle into two categories, A and B
add: Syndicate bundle A (Syndi-kit Tactical), featuring strategical item mashups
add: Syndicate bundle B (Syndi-kit Special), featuring gimmicky item mashups
add: Mr Freeze bundle, props to ATHATH for the idea
tweak: moves bee, bond, white whale holy grail, dark lord and ninja bundles to Syndicate Bundle B
add: DNA injectors for already existing Mutations; Cryokinesis and Geladikinesis 
:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
yo why is this a merge conflict, worked fine for me?

**Comment by SpaceManiac** [comment]
You initially started work on a week-old copy of the repo, you changed some stuff that someone else changed in that time, you need to reconcile those differences

**Comment by ATH1909** [comment]
Oh man, thank you so much for making my Mr. Freeze bundle idea be a thing.

**Comment by actioninja** [comment]
You should rename them from Syndicate Bundles to SyndiKits. Call the A type "SyndiKit Tactical" and the B Type "SyndiKit Special"

**Comment by wesoda25** [comment]
> You should rename them from Syndicate Bundles to SyndiKits. Call the A type "SyndiKit Tactical" and the B Type "SyndiKit Special"

yeah that rolls of the tongue a bit easier than Syndicate Bundle A/B, one sec

**Comment by necromanceranne** [comment]
I am just a bit worried about the weighting of certain bundles in B (AKA ninja good lord is that a good bundle) but it's probably fine.

**Comment by wesoda25** [comment]
Ninja has the lowest chance of spawning. Its basically just a super strong esword (katana) plus adrenals plus half a throwing kit. 

Besides I’m not changing or adding content for anything aside from mr freeze bundle.

**Comment by Shadowflame909** [comment]
I'm waiting for 10 more meme bundles to get added, so the perfect RNG of Thriftstore wizard can finally come to fruition.

**Comment by wesoda25** [comment]
> I'm waiting for 10 more meme bundles to get added, so the perfect RNG of Thriftstore wizard can finally come to fruition.

never

**Comment by ExcessiveUseOfCobblestone** [comment]
> type A and B

I hate you

**Pull request merged**
