### PR TITLE
Finally adds an item to the end of the sloth ruin

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR replaces the note saying that Sloth will eventually get around to adding a cursed item to their ruin with the mushpunch item (an "odd mushroom" in-game) that can teach a single person the "mushpunch" martial art.

This martial art contains a single move: If you click on someone with an empty hand on harm intent, you'll start winding up a punch. If your target allows you to stand motionless next to them for a whole 2.5 seconds, you'll punch them across the room, stunning them for 2 seconds (not enough time for you to finish lining up another punch) and dealing a moderate amount of damage to them (they'll be stunned for longer and take more damage if they're flung into a wall (airlocks and windows do NOT count) or another person, but good luck lining THAT up).

## Why It's Good For The Game

The sloth ruin is kind of just a waste of space/a waste of ruin points currently. Yeah, I get that the joke is that it's unfinished, but still, it's a bit lame.

There shouldn't be any balance concerns regarding this PR, since the mushpunch martial art is incredibly bad. It removes your ability to do normal harm intent punches/kicks, making you arguably WORSE at straight up unarmed vs. unarmed combat against a skilled opponent than someone who doesn't know the mushpunch martial art (which is the "curse" of the item, I guess)!

Also, in true Sloth fashion, this is a one line change PR that replaces the note with a currently mostly-unused item that already exists in the game's code (what, you thought that Sloth would put EFFORT into making a unique cursed item?).

## Changelog
:cl:
add: Sloth has finally added a "cursed" item to the end of their Lavaland ruin.
/:cl:

### CODE REVIEW

**Comment by Ty-the-Smonk** [comment]
how is this cursed

**Comment by ATH1909** [comment]
also, inB4 the review/merging of this PR gets delayed a long time because "haha funny sloth joke"

**Comment by AnonymousNow** [comment]
I think the several years that the Sloth ruin has been present in its current form warrants this eventual change to an appropriate item.

Keep the orange.

**Comment by ATH1909** [comment]
> how is this cursed

it makes you worse at unarmed combat than someone who knows no martial arts at all, since it replaces your harm intent attack

also shut up, sloth is lazy and this is a sloth-themed martial art, which is close enough. the pride knife doesn't have a downside, so why should sloth's item have a (significant) downside, especially since getting to the end of the sloth ruin is an incredible pain in the ass?

**Comment by Ty-the-Smonk** [comment]
> > how is this cursed
> 
> it makes you worse at unarmed combat than someone who knows no martial arts at all, since it replaces your harm intent attack
> 
> also shut up, sloth is lazy and this is a sloth-themed martial art, which is close enough. the pride knife doesn't have a downside, so why should sloth's item have a (significant) downside, especially since getting to the end of the sloth ruin is an incredible pain in the ass?

cant you just crowbar the sepia tiles?

**Comment by ATH1909** [comment]
> I think the several years that the Sloth ruin has been present in its current form warrants this eventual change to an appropriate item.
> 
> Keep the orange.

This PR doesn't remove the orange; it just removes the note from the ruin (and adds the mushpunch item to the ruin in its place).

Perhaps I should remove the sloth note's data from the game as well? Nah, I don't feel like finding it again.

**Comment by ATH1909** [comment]
> > > how is this cursed
> > 
> > 
> > it makes you worse at unarmed combat than someone who knows no martial arts at all, since it replaces your harm intent attack
> > also shut up, sloth is lazy and this is a sloth-themed martial art, which is close enough. the pride knife doesn't have a downside, so why should sloth's item have a (significant) downside, especially since getting to the end of the sloth ruin is an incredible pain in the ass?
> 
> cant you just crowbar the sepia tiles?

yeah, but it's still a long and winding path and the mushpunch item is pretty bad

again, the pride ruin has the pride knife just sitting out in the open, why do I have to justify having a worse item be hidden at the back of a long, winding path?

**Comment by Dawson1917** [comment]
Mushroom punch isn't thematically fitting for the ruin at all. It's just a random meme item thrown in so people can feel "rewarded" when the ruin is meant to be unrewarding.

**Comment by optimumtact** [comment]
it's not meant to be anything, the original author was literally too lazy to finish it, so it just became a meme.

If youw ant to pretend someone was too lazyt o finish it, there shouldn't be a ruin at all, just a sign saying this is where the sloth temple will be later, and maybe some random building material scattered about on the ground

**Comment by MCterra10** [comment]
Orange man is right, the entire joke around the ruin is that sloth was too lazy to finish it, also now it won't be a waste of time for new miners that I get to laugh at later

**Comment by ATH1909** [comment]
> Mushroom punch isn't thematically fitting for the ruin at all. It's just a random meme item thrown in so people can feel "rewarded" when the ruin is meant to be unrewarding.

The whole gimmick of the mushroom punch martial art is that charging up your punches takes an unreasonably long amount of time, which Ii think _is_, in fact, fitting for a sloth ruin.

**Comment by ATH1909** [comment]
travis whyyyyyyyyyyy

**Comment by kriskog** [comment]
Sloth ruin best cult base though, noone will ever find it

**Comment by Dawson1917** [comment]
> The whole gimmick of the mushroom punch martial art is that charging up your punches takes an unreasonably long amount of time, which Ii think _is_, in fact, fitting for a sloth ruin.

"It's slow" isn't enough reason to throw in an admin-only mushroom people meme item into a random ruin. Not everything in this game has to reward you. Can we not have **one** ruin that's just there for a joke.

**Comment by NoxVS** [comment]
> > The whole gimmick of the mushroom punch martial art is that charging up your punches takes an unreasonably long amount of time, which Ii think _is_, in fact, fitting for a sloth ruin.
> 
> "It's slow" isn't enough reason to throw in an admin-only mushroom people meme item into a random ruin. Not everything in this game has to reward you. Can we not have **one** ruin that's just there for a joke.

Its a one time joke that just keeps getting repeated even though you know the punchline

Also why not just straight up some form of mushroom mutation toxin? So you also have the slow walking to deal with, further adding to sloth.

**Comment by Dawson1917** [comment]
Make a mushroom ruin if you want mushroom people gimmicks in the game...

**Comment by IndieanaJones** [comment]
> "It's slow" isn't enough reason to throw in an admin-only mushroom people meme item into a random ruin. Not everything in this game has to reward you. Can we not have **one** ruin that's just there for a joke.

Considering how much space this specific ruin takes up, I'd rather not have it be worthless.  I'd rather have Orange's unfinished building idea than nothing for this massive wall of a ruin.

**Comment by Shadowflame909** [comment]
I thought the reward was that orange that had a chance to turn you into a sloth.

Or maybe that was adminbus somehow. Something was up with that orange.

Also coder reference!1!1!1

**Comment by optimumtact** [comment]
Please stop calling it my building, I didn't make it

**Comment by 81Denton** [comment]
Some left over Planetstation junk doesn't really fit into a ruin that's about "hheh this thing was never finished very funny".
Like oranges said:
>there shouldn't be a ruin at all, just a sign saying this is where the sloth temple will be later, and maybe some random building material scattered about on the ground

**Pull request closed without merging**
