### PR TITLE
New Ore Box Sprite

### PR DESCRIPTION
**Pull request by ghost**
New ore box sprite from Oracle, a 3/4 version of the original Bay sprite

:cl:
imageadd: Ore boxes have a new sprite
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
Very nice! 👍

**Review by WJohn — APPROVED** [review]

**Comment by GunHog** [comment]
This is how spite conversion to 3/4 (ew) should go! This is a clear improvement over the other.

**Comment by Tlaltecuhtli** [comment]
make the new one 3/4

**Comment by WJohn** [comment]
The new one IS 3/4th ya goof.

**Pull request merged**
