### PR TITLE
Resprites the meat pie and some cakes

### PR DESCRIPTION
**Pull request by Sheits**
## About The Pull Request

Pastries

## Changelog

:cl:
imageadd: Resprites the meat pie and some cakes
/:cl:

### CODE REVIEW

**Comment by AdipemDragon** [comment]
well neat to see that i'm not the only one workin on respritin' the cakes and their associates, and we sort of had the sameish idea for the berry cake too
unsure what to think of the others, though

**Comment by Twaticus** [comment]
these looks lovely especially the berry cake awesome job. though im sad to see the classic birthday cake design change so drastically. and the cakehat would need to be changed aswell :(

**Comment by Sheits** [comment]
Thanks for the feedback, I guess I'll close it then lol

**Comment by MetalClone** [comment]
These sprites look bangin.

**Pull request closed without merging**
