### PR TITLE
Scared of the Spooky Circus Man? Wear a tinfoil hat! Mental resistance protects from some heretic abilities (mostly Moon effects)

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Several effects that target the mind now are blocked by the presence of MAGIC_RESISTANCE_MIND, which is only found (currently) on tinfoil hats. 

Affected abilities and items include;

Moon Path Powers (like, pretty much every single thing the path gets)
Eldritch Paintings
Mask of Madness (oh, and normal magic resistance also applies because...it's fucking magic?)
Mindswap
Terrorize (the nightmare ability)
Abyssal Gaze (completely unused, used to be a rune golem spell I think)

## Why It's Good For The Game

Tinfoil hats horribly debilitate you and render you pretty terrible at actually validhunting. But it is exceptionally funny for someone to willingly subject themselves to wearing it in fear of being attacked by a Moon heretic.  And then get blinded and stunned by their mere presence because they are now scared of heretic's tools, alongside most of the station's various roles.

Since this doesn't stop a heretic from A) hitting you with the ol' Mansus Grasp the old fashioned way and B) stabbing the shit out of you after this, I don't anticipate it being TOO effective when it doesn't stop the heretic's bread and butter abilities, as well as causing automatic debuffs just from them being on the screen.

If heretics giving out a phobia targeting them specifically wasn't tolerable, then someone willingly subjecting themselves to that same effect to stop a moon heretic is maybe unlikely, or just really funny and sandboxy.

Oh, and it makes them scared of, like, security and command and stuff so this is NOT a viable option for those roles at all unless they really want to suffer constantly for it. But maybe that's funnier as a result.

## Changelog
:cl:
balance: Some mind altering effects of heretics (predominantly Path of the Moon heretic abilities) are nullified using...a tinfoil hat. But awareness of the mind altering psychotropic eldritch brain wizards has spread amongst the conspiracy theorists. They could be anyone! Even YOU.
balance: Some additional spells (mindswap, nightmare's terrorize) are also blocked. 
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
foiled again

**Comment by moocowswag** [comment]
"and stuff" it makes you afraid of lizards that's the best part about it. It's one of the best weapons lizards have for dealing with anti lizards.

Security and command could potentially dress as tiders and abuse tinfoil hats because the fear isnt based on job its the actual items themselves, but there is no hiding the sight of a happy reptile wagging their tail.

**Comment by carlarctg** [comment]
i would look into wiz spells like mindswap too

**Comment by necromanceranne** [comment]
> i would look into wiz spells like mindswap too

Oh, I figured you were doing that in your own PR. Yeah, easy enough.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
