### PR TITLE
Moths can now scream.

### PR DESCRIPTION
**Pull request by Buggy123**
:cl: :
add: After learning about the existence of moth-eating lizards, all moths now know how to scream
/:cl:

OKAY WAIT HEAR ME OUT:

 - If you scream 3 times in a short period, you pass out for 30 seconds.

 - If you somehow keep screaming and reach 5 times in a short period, you go mute for 5 minutes.

 - If you _still_ somehow keep screaming, you fucking explode once you reach 7.

 - Your "scream counter" decreases once every 30 seconds.

Ignore the roundstart moth changes, it has no effects serverside, it's only useful for local testing (and it should be changed anyway now that moths are roundstart available).

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
>you fucking explode once you reach 7.
my sides

**Comment by MoreRobustThanYou** [comment]
Might wanna make it so the scream counter doesn't go up while unconscious, so you can't gib moths by spamming styptic patches on them. Maybe make it so screaming constantly exponentially deals more and more oxy damage?

**Comment by WJohn** [comment]
i personally think the screaming is fine with no downsides whatsoever but i also personally think that it sounds fucking hilarious

**Comment by MoreRobustThanYou** [comment]
QUICK LET'S ALL MAKE A PROTECTIVE BARRIER TO KEEP **LeoZ** OUT!

**Comment by Buggy123** [comment]
I also think the scream is alright with no downsides but i'm fairly certain it was removed the first time because of spam.

**Comment by Buggy123** [comment]
WAIT NO DON'T CLOSE IT

**Comment by lzimann** [comment]
the scream was already denied in the original moth pr

**Comment by MoreRobustThanYou** [comment]
fuck you @lzimann

**Comment by Buggy123** [comment]
Everyone wants the scream!

**Comment by Kromgar** [comment]
@lzimann 24 hours

**Comment by Buggy123** [comment]
Yes, 24 hours.


Also does anyone know how i might differentiate between manual screams and screams from pepper spray, etc so pepper spray doesn't gib moths?

**Comment by kevinz000** [comment]
fuck off buggy

**Comment by FantasticFwoosh** [comment]
You scream for icecream.

**Comment by Hatfish** [comment]
fuck you shitty admin
fuck myself

**Pull request closed without merging**
