### PR TITLE
Merges power subsystem into machine subsystem.

### LINKED ISSUE #9309: Occasional massive power drain in all grids.
I'm not sure how to reproduce this but a round happened earlier where everywhere started losing power. SMES were outputting, APCs said they had a grid connection but wouldn't charge. During this round, the admins were spammed with a lot of emitters lost power messages, more-so than usual.

The power usage on SMES outputs were showing red as if it was hitting their set maximum. Mining and the AI sat APCs ran out of power and shut off. By the time it was reported the round ended before I had a change to investigate.

### LINKED ISSUE #9350: Radiation collectors aren't providing constant power.
Radiation collectors don't provide constant power to and connected powernet.
It appears to act like a "burst" of power, going from full output, half output, then to nothing and then back up to full. This cycling is roughly every 2-4 seconds IIRC.

This means the SMES's don't get constant power and fail to charge properly.

To reproduce, get singlo to stage 3 or 4 and with all radiation collectors fully topped up and on. Then hit the output cable with a multitool, spam click and watch it fluctuate.

Could this be anything to do with the recent radiation re-work?

### LINKED ISSUE #9388: Singularities are occasionally getting released for no reason percievable by admins.
Every few rounds or so the singularity containment just decides "Fuck it I give up" and the singularity gets loose early in the round.

SMES are still charged.

Wires appear to be intact (although someone was cutting some on the other side of the station at the time).

Singularity was only 5x5

We really have no idea how it got loose other than bugs. It's been observed at least a few times already by server admins.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This is to avoid issues from when they fire out of sync, since powernets assume machine's subsystem will fire directly after power's does.

fixes #9388 Singularities are occasionally getting released for no reason percievable by admins.
fixes #9350 Radiation collectors aren't providing constant power.
fixes #9309 Occasional massive power drain in all grids.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Priority merge

**Comment by Cheridan** [comment]
>I haven't tested jack shit, so hold off on the quick merge

**Comment by MrStonedOne** [comment]
Forgot to remove that =P

**Comment by RemieRichards** [comment]
@Cheridan he asked in IRC, ya butt

**Pull request merged**
