### PR TITLE
tgui-next: Remote signalers

### PR DESCRIPTION
**Pull request by SteelSlayer**
## About The Pull Request
Updates remote signalers to use tgui-next, and also removes `var/delay` in the signaler file. This var was completely unused.

e

And in `radio.dm`, I noticed a bit of an issue. The code was assigning `.` to a rounded frequency. However on line 5, it uses the still non-rounded frequency in a clamp and assigns it to `.` once again. This meant that the `round()` actually did nothing and you could still have frequencies like 1455.5 which should have been rounded to 1455. This change properly rounds the frequency.

## Changelog
:cl:
add: Remote signalers now use tgui-next
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
FINALLY!!

**Comment by Iatots** [comment]
Is this new UI removing all the +- arrows from every interface? I liked those arrows.

**Comment by SteelSlayer** [comment]
Well.. the arrows were already gone when I started this project, otherwise I would have probably included them :smile:

**Comment by stylemistake** [comment]
@latots this number field allows moving the value up and down, without the help of buttons, just saying in case you didn't know.

@SteelSlayer make this UI a little bit smaller, it's a little bit assymmetrical.

**Comment by SteelSlayer** [comment]
@stylemistake I reduced the width and bit and updated the original post with a new picture. It can got a tad bit smaller if you want, but any more and the "X" button can start to cut into the window title.

**Comment by stylemistake** [comment]
Maybe use a `buttons` prop on LabeledList.Item, reset button will stick to the right, and you can expand the activator button to a full width of the window.

**Review by stylemistake — DISMISSED** [review]
No technicalities detected.

**Comment by SteelSlayer** [comment]
I tried what you suggested, and I like the look, but now the number inputs look a bit out of place. Using `ml` to reposition them doesn't seem to work. What would be the best way to nudge them over to the right a bit more? Or perhaps you think this looks fine?

52b1fe212c760d1e849a71649278f6c7

**Comment by kriskog** [comment]
Merge conflict

**Comment by stylemistake** [comment]
I think it looks fine. Tou can put those number inputs into the button prop, like this:

```
buttons={(
  <Fragment>
    <NumberInput ... />
    <Button ... />
  </Fragment>
)}
```

but it's kinda bad semantically. You can also use tables, with tables you can do whatever the fuck you want, and `color="label"` for labels.

**Comment by SteelSlayer** [comment]
@stylemistake Alright sorry to keep changing the code around so much. I'm still learning about all the different options available in tgui.

Ultimately I settled on using `Grid`s and I've updated the picture in the PR description to how the UI currently looks. Provided I didn't screw up somewhere, I'm going to say this ready for merging.

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
