### PR TITLE
[Tested] supplypod sound update

### PR DESCRIPTION
**Pull request by MrDoomBringer**
### [take a listen to this dank shit (turn that sound up its a bit quiet)](https://youtu.be/eXhxjNPqmVk)
instead of just BOOM now its nnnneeoowwBOOM

:cl: MrDoomBringer
soundadd: Supplypods sound a bit nicer as the land now.
admin: admins can now adjust the animation duration for centcom-launched supplypods 
admin: admins can adjust any sounds that are played as the supplypod lands
/:cl:

Never bothered me until I noticed that the supplypods are silent right until they land. Now theres a nice little "woosh" as they fall. 

---
edit; added a way for admins (when using the centcom pod launcher) to set animation duration (for slomo falling pod fun) and a custom falling pod sound (@DaxDupont). 

edit2: the sound is now a little bit longer than in the video by default

Note that the falling pod sound is different than the sound played when the pod lands, the sound played when the pod opens, and the sound played when the pod leaves.

### CODE REVIEW

**Comment by DaxDupont** [comment]
Can you make it so we can set the sound like the others

**Comment by MrDoomBringer** [comment]
@DaxDupont uuuuuuuh i need to figure out if theres a way to get a sound file's length, otherwise it'll overlap weirdly with the landing explosion etc (cus the woosh sound currently always starts 0.3seconds before landing)

**Comment by Arianya** [comment]
Noice

**Comment by ShizCalev** [comment]
conflict

**Comment by ShizCalev** [comment]
conflict.

**Comment by optimumtact** [comment]
you fucked this whole thing

**Comment by MrDoomBringer** [comment]
AH FUCK

**Comment by MrDoomBringer** [comment]
i unfucked the whole thing 💪

**Comment by MrDoomBringer** [comment]
should b good to go

**Pull request merged**
