### PR TITLE
Ensure deploy.sh is +x before running it in PostCompile.sh

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by SpaceManiac** [comment]
can't we just +x deploy.sh in the repo

**Comment by SpaceManiac** [comment]
Is TGS4 dropping file modes?

```sh
$ find . -name '*.sh' | xargs ls -l
-rwxr-xr-x 1 user user  468 Oct 12 12:43 ./dependencies.sh
-rwxr-xr-x 1 user user  340 Sep 13 22:57 ./tgui/build.sh
-rwxr-xr-x 1 user user  211 Sep 13 22:57 ./tools/appveyor/download_byond.sh
-rw-r--r-- 1 user user  377 Sep 25  2017 ./tools/CreditsTool/UpdateCreditsDMI.sh
-rwxr-xr-x 1 user user  955 Sep 13 22:57 ./tools/deploy.sh
-rw-r--r-- 1 user user  191 Sep 25  2017 ./tools/dmitool/dmimerge.sh
-rwxr-xr-x 1 user user  173 Sep 25  2017 ./tools/dmitool/git_merge_installer.sh
-rwxr-xr-x 1 user user  412 Jun 30 20:57 ./tools/hooks/install.sh
-rwxr-xr-x 1 user user  363 Sep 19 11:28 ./tools/hooks/python.sh
-rwxr-xr-x 1 user user 2352 Oct 12 12:43 ./tools/tgs4_scripts/PostCompile.sh
-rwxr-xr-x 1 user user  896 Oct 12 12:43 ./tools/tgs4_scripts/PreSynchronize.sh
-rwxr-xr-x 1 user user  779 Sep 13 22:57 ./tools/travis/before_build_byond.sh
-rwxr-xr-x 1 user user  120 Sep 25  2017 ./tools/travis/before_build_tools.sh
-rwxr-xr-x 1 user user 2533 Sep 13 22:57 ./tools/travis/build_byond.sh
-rwxr-xr-x 1 user user 2229 Sep 13 22:57 ./tools/travis/build_dependencies.sh
-rwxr-xr-x 1 user user  620 Sep 19 11:53 ./tools/travis/build_tools.sh
-rwxr-xr-x 1 user user  328 Sep 25  2017 ./tools/travis/check_filedirs.sh
-rwxr-xr-x 1 user user 1526 May  9 15:07 ./tools/travis/dm.sh
-rwxr-xr-x 1 user user  360 Sep 19 11:53 ./tools/travis/install_build_tools.sh

```

**Comment by Cyberboss** [comment]
Yes it is because it doesn't deal with more when copying files

**Comment by SpaceManiac** [comment]
Then this is a TGS4 bug

**Comment by optimumtact** [comment]
hes' kinda not wrong

**Comment by Cyberboss** [comment]
I know but it's either this or add overhead to every file in the bulk repo
copy operation

**Comment by SpaceManiac** [comment]
What copy primitive are you calling that ignores file modes anyways

**Comment by Cyberboss** [comment]
It's currently an oversight in the async file copy API and I'd rather not wait for MS to fix it

**Pull request merged**
