### PR TITLE
PDA Interface color is now a preference.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 

:cl: Dax Dupont
add: PDA Interface color is now a preference.
fix: Fixed PDA font style not applying at round start.
/:cl:

[why]: I really got tired of having to change the baby shit green color to something else every round start. Arguably people are more likely to change color than font in preferences.
Also changed PDA to pda_style to make it more sensible in the code and distinguish it from color.

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
someone needs to remove the butt-ugly fonts first

**Comment by DaxDupont** [comment]
I have not touched the butt ugly fonts, aside from them now respecting which butt ugly font you want to choose.

**Comment by MoreRobustThanYou** [comment]
readd pre-#30613 font reeeeeeeeeeee

**Comment by DaxDupont** [comment]
out of scope

**Pull request merged**
