### PR TITLE
Removes the terrible "Recoil" mechanic

### PR DESCRIPTION
**Pull request by Supermichael777**
Unintuitive and horrible, dropping your weapon is a death sentence. yes yes " i died"

:cl: optional name here
del: The terrible recoil mechanic has been removed. Salt to salt, ashes to ashes.
tweak: The L6 Saw's price is up to 35.
/:cl:

### CODE REVIEW

**Comment by Shapsy** [comment]
Honestly it really should be gone since there's no hint that you can't fire an LMG one handed while firing a rifle/carbine laser or riot shotgun one handed is okay

**Comment by kevinz000** [comment]
This might be uh a balance thing.

**Comment by optimumtact** [comment]
Yes it is.

Just improve the code so the RECOIL guns won't fire at all if you don't have an empty hand.

It was meant to be a risk vs reward thing but clearly that's too involved for your simple player minds to grasp.

**Comment by Delimusca** [comment]
i only added the heavy weapon thing to make the turret cannon less of a free egun back in the stun removal days, ideally to be replaced with a proper twohanded gun system i never finished.

now it just makes me cringe and i want it  incinerated. :fire:

**Comment by Bawhoppen** [comment]
Remove it properly by making it require 2hands, also talk to remie they had some involvement I think

**Comment by Bawhoppen** [comment]
Alternatively, don't then we could classify this as balance instead and have cool situations with people dualwielding LMGs

**Comment by lzimann** [comment]
the problem is someone using a lmg + shield, shit is strong

**Comment by Supermichael777** [comment]
guns with two hands are terrible how are you supposed to reload it?

**Comment by Bawhoppen** [comment]
Then there is no solution

**Comment by Bawhoppen** [comment]
>35

That's an insane amount noone will ever buy one

**Comment by nullbear** [comment]
make it only fire-able when weilded in both hands + weildable, rather than force two-handed behaviour like gibtonite, and then your ammo-loading solution is solved.

**Comment by ExcessiveUseOfCobblestone** [comment]
or just have it warn you that whenever you start shooting it with  the other hand filled you run the risk of dropping it?

**Comment by KorPhaeron** [comment]
@optimumtact 

I already added a weapon weight that lets you do that

**Comment by optimumtact** [comment]
Don't change the price, any weapon implementing this recoil mechanic at medium weight ust instead be classed as requiring two hands to maintain game balance.

Pricing changes and other attempts will not work.

**Comment by optimumtact** [comment]
Like just to be absolutely clear here we will not allow the LMG to be a onehanded weapon with zero downsides other than an slight increase in price.

That's just not happening period.

**Comment by lzimann** [comment]
Just change the lmg's weight to heavy and it won't be able to fire with the other hand occupied. No bad recoil.

**Comment by Kraseo** [comment]
>35 TC from 18

good job now absolutely nobody will buy one

**Pull request closed without merging**
