### PR TITLE
Iron Rods no Longer Say They Take Energy for Cyborgs

### PR DESCRIPTION
**Pull request by Vect0r2**
## About The Pull Request

Removes the "enough energy" description from when borgs look at their materials

## Why It's Good For The Game

They don't use energy anymore.

## Changelog
:cl: Vect0r
spellcheck: fixed a few typos
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
What did i miss?

**Comment by Vect0r2** [comment]
> What did i miss?

Just some grammer checks

**Comment by zxaber** [comment]
~~Technically they never took power and this was just a flufftext about converting rods between matter and energy for storage~~

Anyway the prior text is dumb and this is better.

**Comment by Vect0r2** [comment]
Also I want my grammar and formatting tag for gbp

**Pull request merged**
