### PR TITLE
Revert "Adds exotic and talking corgi crates"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#38276

We dont' need this meme human crate and shitty outfit

### CODE REVIEW

**Comment by Shadowflame909** [comment]
I personally don't care about this but you will inflict the wraith of hop-mains. prepare yourself!

**Comment by ShizCalev** [comment]
missed your commentary on that.

why not just remove the talking human part and leave the exotic corgi crate though?

**Comment by nichlas0010** [comment]
n o k n e e j e r k s

**Comment by CitrusGender** [comment]
Every day we stray further from the light. *Bark*

**Comment by iskyp** [comment]
wait cheese got a pr merged?
we've failed guys

**Comment by Jared-Fogle** [comment]
whats wrong with talking corgis

**Comment by CitrusGender** [comment]
oh shit IT IS. IT'S JUST A CONTAINER WITH A FURRY IN IT

**Comment by Jared-Fogle** [comment]
it's an intoxicated bald neckbeard thats so delusional he thinks he's a dog

what about this needs reverting

**Comment by AlexTheSysop42** [comment]
I think one of the possible names for the talking corgi is 'chesse'

**Comment by PKPenguin321** [comment]
wowww

**Comment by GuppyLaxx** [comment]
the codebase is ruined

**Comment by chesse20** [comment]
so sad for corgi 😢

**Comment by Iamgoofball** [comment]
the talking corgi is hillarious

**Comment by Jared-Fogle** [comment]
@Iamgoofball add it back

**Comment by epochayur** [comment]
oranges PR gets speedmerged within a day of it opening despite player outcry and more downvotes than upvotes

🤔

**Comment by iskyp** [comment]
yeah

**Comment by optimumtact** [comment]
I'm overwhelmingly evil

**Comment by SpaceManiac** [comment]
the funniest part about this PR is that hippie didn't downstream it

**Comment by Iamgoofball** [comment]
Time to be a hero

**Pull request merged**
