### PR TITLE
Adds Chainsaws

### PR DESCRIPTION
**Pull request by tkdrg**
~~Happy Halloween~~ ~~Merry Christmas~~ ~~Happy New Year, I guess.~~ fuck it

Sprites by WalterJe.
Currently obtained by tablecrafting chain of command and circular saw.
Needs two hands (gibtonite style), does 20 damage when on, 10 when off.
Also adds the mob proc update_inv_current_hand()

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@RemieRichards 
# TONIGHT

**Comment by Cheridan** [comment]
With tkdrg vanishing and dismemberment still being done SOON :tm: I'l gonna go ahead and close this.

**Comment by Iamgoofball** [comment]
:tm:

**Comment by paprka** [comment]
the dream is dead

**Comment by Nienhaus** [comment]
@tkdrg Vanished? That's a shame.

**Pull request closed without merging**
