### PR TITLE
adds a new janiborg sprite!

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds a new janiborg sprite, viewable here
image
image
(the hud issues were fixed)
allowance:
image
sprites by theOOZ

## Why It's Good For The Game

its cute!

## Changelog

:cl: Fikou, theOOZ
imageadd: adds a new janiborg sprite!
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
oh cool i love tall robots

**Comment by thgvr** [comment]
Finally, some silicon content! Thank you Fikou 😄

**Comment by CitrusGender** [comment]
it's a christmas miracle

**Comment by SamDDBS** [comment]
is this why modsuits have been taking so long?

**Pull request merged**
