### PR TITLE
Fixes cable merging, changes merging code just a little bit

### LINKED ISSUE #60825: Cables from Techfabs and Autolathes are different and thus cannot stack
## Reproduction:
https://puu.sh/I3fsB/5f4514ba51.png

aaaaaaaaa

reproduce:
print cable coil from autolathe
print cable coil from tech fab (and use some of it, they only print in 30 stacks)
try to mix the piles
cry

### PR DESCRIPTION
**Pull request by Colovorat**
## About The Pull Request

changes how stacks merging works. i am very sorry if it's really shitty code but i have no other idea how to do it
closes: https://github.com/tgstation/tgstation/issues/60825

## Why It's Good For The Game

fixes good

## Changelog
:cl: Colovorat
fix: Cables from protolathe and autolathe should merge just fine now
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
merge conflict on maps??????? or am i retarded

**Comment by Couls** [comment]
> merge conflict on maps??????? or am i retarded

merge conflict on the stack code file

**Comment by Colovorat** [comment]
i am retarded, it got updated shit tone of time ago

**Comment by Colovorat** [comment]
FUCK I AM RETARDED HOLY SHIT

**Pull request closed without merging**
