### PR TITLE
Adding paper-attaching to wrapped packages

### PR DESCRIPTION
**Pull request by Dingo-Dongler**
## About The Pull Request
This lets people attach paper to wrapped packages that can be read on the package and comes off when the package is ripped open. This works almost exactly like airlocks. This is my first time spriting so feel free to criticize.

mailservice

## Why It's Good For The Game
Makes the mail service system more useful by allowing information about packages to be directly attached to those packages.

## Changelog
:cl:
add: Paper can now be attached to wrapped packages.
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Nice, now I can label the Locker with the Clown that I mailed to HoS Office "a Bomb"

**Comment by Ty-the-Smonk** [comment]
The sprites look really nice

**Comment by TheChosenEvilOne** [comment]
Is the DMI file wrong? The extension is .dmi.tmp

**Comment by Dingo-Dongler** [comment]
oh god damnit i took a tumble with git and tried to fix it but i guess i fucked up

**Pull request merged**
