### PR TITLE
Spess Mahreen armor. [Close this]

### PR DESCRIPTION
**Pull request by ishitbyabullet**
steel rehn

This adds three different versions of the original beserker/champion's hardsuit.

:cl: Opt Ional Station Thirteen
add: Added three new reskins of the champion's hardsuit. Enjoy a different shade of paint while praising a god.
/:cl:

This could allow for space marine wars or other space marine related events. It also fits the name of the station since this is Traditional Gaming station.

EDIT: Also, credit to Ausops for making the original champion's hardsuit.

### CODE REVIEW

**Comment by Okand37** [comment]
You might want to edit your changelog to your changes, ie; "add: Added three new reskins of the beserker/champion's hardsuit!" as that will be what appears in the ingame changelog for people to view.

**Comment by Iamgoofball** [comment]
👮 📧 ➡️

**Comment by ishitbyabullet** [comment]
@Okand37 Oh. Thank you for that.

@Iamgoofball Goofball, please speak in something that isn't a cop that looks like a nazi sending some email.

I can't even tell if you're calling it trash or that it doesn't fit.

**Comment by Armhulen** [comment]
something worries me that these are plaugewalker sprites

**Comment by ShizCalev** [comment]
inb4 games workshop gets angry

**Comment by ishitbyabullet** [comment]
@Armhulen While I don't know who that is and I was told it was made by Ausops, if it's a problem then I understand.

@ShizCalev would probably be the names of the hardsuits that do it in. rip

**Comment by Armhulen** [comment]
@ishitbyabullet if that's the case this is just fine

**Comment by FantasticFwoosh** [comment]
I mean, i like 40k but im not sold on this reskin of the assets we already have, one dedicated suit _felt_ like enough but im open minded to more if its done well.

At one point i was hoping to do my own 40k set of armor and drop it somewhere that actually made sense, but not accentuating the armor respectively (the actual models do have difference) to the source material in favor of color respriting & not leaving it to be basically a admin spawnable item.

- Nurgle's champion set (left) is ok, typical world-eater black chaos marine (center) is easily the best of the three, i know from spriting a entire chaos defiler in byond format that the gold lines is difficult but im confused on the third.

- In my own opinion, besides the inquisitor clothing (which works better aesthetically) if you were going to add more armors you should have made them unique set pieces, nurgles armor for instance having extreme bio-protection, if i was for example going to drop a REAL khornate bezerker armor, i might well have added a cooldown spell to the armor or something to set it apart.

### Of course if there's going to be a slaneesh champion armor, it needs to have fur, cat ears & a tail.

**Comment by AnturK** [comment]
Oh look another reference for the sake of reference.

**Comment by The-clown-known-as-Pepe** [comment]
its fun to get a

D M C A

its fun to get a

D M C A

**Comment by jughu** [comment]
Just make it able to skin your champ hardsuit in thise variations like how you can skin a bartenders shotgun with alt click

**Comment by ishitbyabullet** [comment]
@FantasticFwoosh you gave me a great idea incase I have to redo these.

Anyways, you're right that this is kinda half-baked, but from my lack of knowledge on how to code, I can't really do the idea that Kor gave me which is
- 25/25/25/25 for the champion hardsuit drop aka if you land on that then you gotta do another rng roll on WHICH armor piece you get.
Also, while armor difference would be cool, keep in mind that if I do that and this gets added to lavaland then people will probably powergame the fuck out of the 'oh this one has rad resistance' armor or 'oh this one is immune to the fucking bubonic plague' armor.

@jughu maybe that would be a cool idea, but I don't know how to do that. I had to be guided on how the fuck making a PR even works so I doubt my ability to just code a 'reskin' button.

@The-clown-known-as-Pepe ree

**Comment by FantasticFwoosh** [comment]
@ishitbyabullet in all respects the lavaland loot is put there to be used, contrary to their strength which forms a seperate discussion on lavaland loot strength in general, given that there's the ability to summon storms & lava tiles, magic ghost swords, dragon armor etc and most of these are not even from wholly difficult bosses. 

- I do think that a extended line of armors should not be something that is dropped from a tendril chest and instead earned from a boss or a similar experience to the player that should be ideally repeatable so you can earn all the armors by going through milling it for suit drops until its loot table is complete.

- Tzneech cobalt blue armor (hopefully distinct enough to differentiate it from a ultramarine) useful perk would be a spell cooldown to allow you to phase through walls & incoming projectiles and damage at a small cost of brain damage or keeping the cooldown relatively long enough to only use infrequently.

**Comment by ishitbyabullet** [comment]
@FantasticFwoosh Interesting ideas, to be honest.
- I actually made an ultramarine armor set for my own memes so it's easy for me to tell if it looks like ultramarine armor by simply comparing my previous armor
- Ever since that 'give a slaanesh champion cat ears, leather, and a tail' comment you made, I actually made one. I don't have a way to communicate with you to ask if it's cool, though, so I guess this is the only way.
- Making the armor have special abilities would be cool, but what would drop the loot or give the loot? I was working on a space ruin way before I did any of this, but it wouldn't fit. I had one idea for the slaanesh armor if it would be added, which is a space ruin, but I'm not sure about an armor that can phase through walls. If Nurgle armor was made then it would basically be the 'immune to the virologist's shitty disease PLUS spaceproof' which is a really big advantage if dealing with an AI and disease.
- I have no fucking idea how to code any of that. Maybe I can try, though.
I sadly can't close this and try to make it better, though.

**Comment by ishitbyabullet** [comment]
Please close this PR. I feel like more work should be done for it.

**Comment by DoctoreMad** [comment]
>I actually made an ultramarine armor set

Thank you, Spiritual Liege.

**Comment by ishitbyabullet** [comment]
@DoctoreMad yes, why do you think i asked 'pls close'

**Comment by ChangelingRain** [comment]
If you want it closed, close it yourself. It's your PR.

Besides that, I see no reason to close this PR.

**Comment by ishitbyabullet** [comment]
@ChangelingRain How do you close your own PR?

**Comment by Cyberboss** [comment]
It's literally right next to the comment button...

**Comment by ishitbyabullet** [comment]
@Cyberboss sorry my character in real life new vegas has 1 int

Thanks, though.

**Pull request closed without merging**
