### PR TITLE
Move_Pulled around corners

### PR DESCRIPTION
**Pull request by norill**
Can now move dense objects around corners in a non-gimmicky way. You just click the destination turf.

### CODE REVIEW

**Comment by optimumtact** [comment]
:+1:

**Comment by Metacide** [comment]
:+1:  very much, thanks.

**Comment by Miauw62** [comment]
This is one of those features that should've been added ages ago. :+1:
Op 8-apr.-2015 16:28 schreef "Metacide" <notifications@github.com>:

**Comment by Fox-McCloud** [comment]
Why isn't diagonal clicking a thing again?

ie:

OX
XA

If you're standing at A and there's two dense, but otherwise non-wall objects at X, you can't click on O.

**Comment by RemieRichards** [comment]
same reason diagonal moves aren't a thing

**Comment by Miauw62** [comment]
Diagonal clicking is dumb, this is just to make dragging stuff through
maint not ass
Op 9-apr.-2015 08:00 schreef "Remie Richards" <notifications@github.com>:

**Comment by MrStonedOne** [comment]
there already exists code that does this for when you don't have dense objects near you, shouldn't this be integrated into that, other wise it would run twice.

**Comment by Fox-McCloud** [comment]
@RemieRichards 

Dunno about that; half the time you can diagonal click--other half of the time you can't.

**Pull request merged**
