### PR TITLE
Emergency Shuttle - Hug-Cage Relaxation Evacuation System

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
Adds this emergency shuttle

Is a hug-cage because someone couldnt handle a ragecage shuttle
Has a sentience balloon to make cute animals sentient
Plenty of plushies, pillows, and beds.

## Why It's Good For The Game
variety is coolio
## Changelog
:cl:
add: Added the Hug-Cage Relaxation Evacuation System emergency shuttle
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Coder pissbaby moment

**Comment by ZephyrTFA** [comment]
Is this a late April fools PR

**Comment by mc-oofert** [comment]
> Is this a late April fools PR

what the fuck

**Comment by krimmity** [comment]
lmfao

**Comment by Rex9001** [comment]
Fun shuttle, shame it got closed. I'd consider buying this over the snapop shuttle

**Comment by Livrah** [comment]
Based.

**Pull request closed without merging**
