### PR TITLE
Makes the atmos table accessible in MetaStation

### LINKED ISSUE #32105: You can't touch a table in atmos (MetaStation)

### PR DESCRIPTION
**Pull request by naltronix**
:cl: naltronix
fix: fixes that table that wasnt accessible in Metastation
/:cl:
tryna get them GoodBoyPoints™
(i fucked the previous pr, plsnokillme)
Fixes #32105

### CODE REVIEW

**Comment by praisenarsie** [comment]
you do not need a changelog

also picture?

**Comment by naltronix** [comment]
[https://gyazo.com/e8ee25bc3d9f631eade6e7295e84c412.jpg](url)
i removed the mask+tank because everyone has one in their bag.

**Comment by Cyberboss** [comment]
This is the kind of stuff that should have a changelog @praisenarsie

**Review by ShizCalev — APPROVED** [review]

**Comment by Bawhoppen** [comment]
@Cyberboss This kind of minor fix doesn't need a changelog, what are you talking about?

**Comment by Cyberboss** [comment]
@Bawhoppen If a new revision fixes a bug that is known to players it absolutely should be changelog'd

**Pull request merged**
