### PR TITLE
March into Mapness: Makes the Meta Kitchen area slightly more spacious

### PR DESCRIPTION
**Pull request by Draggeru**
## About The Pull Request

As the title says, moves the kitchen counter up and reorganizes stuff so the meta kitchen doesn't feel like such a cramped stuffy hell hole. Adds an extra griddle and oven as well.

### Mapping March
This is mostly for mapping march, I now had a reason to stop being lazy.

Ckey to receive rewards: Thedragmeme

## Why It's Good For The Game

Cramped workspaces are bad, and it cures my OCD by making the counters line up. Doubles the number of griddles and ovens, more machines to do stuff = good. Especially since two people can be chefs at a time by default.

meta

## Changelog

:cl: Thedragmeme
qol: Makes the Meta station kitchen not cramped anymore
:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Hard to fix without removing counter space but I kind of hate that little divot where the front door is following this change.
Also a little odd for it to expose a crew-facing grill?

**Comment by Draggeru** [comment]
> Hard to fix without removing counter space but I kind of hate that little divot where the front door is following this change. Also a little odd for it to expose a crew-facing grill?

Hibachi grills are a vibe. I know I like doing them if I do a sushi menu

**Comment by Draggeru** [comment]
new meta for real

Guh

**Comment by Jolly-66** [comment]
You should specify what map this is for, your CL is vague for players to understand.

**Comment by Jacquerel** [comment]
> Why is it failing run the integration test AAAAAAAAAAAAAA

It thinks you have added a space turf somewhere in the kitchen.
Coordinates [137, 127, 2]; looks like that would be underneath that grill.

**Comment by Draggeru** [comment]
> You should specify what map this is for, your CL is vague for players to understand.

Am I wrong in thinking people should read the title of a PR before they read the changelog of a pr?

**Comment by Draggeru** [comment]
> > Am I wrong in thinking people should read the title of a PR before they read the changelog of a pr?
> 
> The CL will be compiled and be seen in game. This is beyond GitHub and making PRs at that point. Players will see what you have there in game.

Ahhh

**Comment by coiax** [comment]
While I understand and share your feeling that Meta kitchen is very cramped, this doesn't really add more _kitchen space_, and just really adds more walking space.

There's like one more table (actually, it's net zero on tables, we've lost one because the grinder got moved to the main T-tables) another oven and another griddle, and to pay for this we've moved the whole kitchen up two whole turfs? 😕 

It reminds me of the much larger, and yet somehow not particularly more effective kitchen on Tram.

**Comment by DATA-xPUNGED** [comment]
> While I understand and share your feeling that Meta kitchen is very cramped, this doesn't really add more _kitchen space_, and just really adds more walking space.
> 
> There's like one more table (actually, it's net zero on tables, we've lost one because the grinder got moved to the main T-tables) another oven and another griddle, and to pay for this we've moved the whole kitchen up two whole turfs? 😕
> 
> It reminds me of the much larger, and yet somehow not particularly more effective kitchen on Tram.

Agree with coiax, the more tables, the bigger the kitchen _feels_, you can easily fit 3 extra tables in that design

**Comment by Draggeru** [comment]
> > While I understand and share your feeling that Meta kitchen is very cramped, this doesn't really add more _kitchen space_, and just really adds more walking space.
> > There's like one more table (actually, it's net zero on tables, we've lost one because the grinder got moved to the main T-tables) another oven and another griddle, and to pay for this we've moved the whole kitchen up two whole turfs? 😕
> > It reminds me of the much larger, and yet somehow not particularly more effective kitchen on Tram.
> 
> Agree with coiax, the more tables, the bigger the kitchen _feels_, you can easily fit 3 extra tables in that design

kitchn

?

**Comment by Draggeru** [comment]
Final design and I decided to add action figures to the rest of the station.

Mostly because the prospect of putting the warden action figure behind the secway was very amusing to me

warden

meta

**Comment by coiax** [comment]
> Final design and I decided to add action figures to the rest of the station.
Seperate MRs please, separate MRs makes changes easier to understand the context in, and also more GBP points for you.

**Comment by Draggeru** [comment]
> > Final design and I decided to add action figures to the rest of the station.
> 
> Seperate MRs please, separate MRs makes changes easier to understand the context in, ensures that changes that aren't tightly coupled can be approved/disapproved separetely, and also more GBP points for you.

Oh that is a good point, will fix when I can

**Comment by Wallemations** [comment]
Can you show a screenshot with how this looks with the whole atrium in view? You've moved the chef's counter up but didn't show how that affected the rest of the atrium.

**Comment by Draggeru** [comment]
> Can you show a screenshot with how this looks with the whole atrium in view? You've moved the chef's counter up but didn't show how that affected the rest of the atrium.

There were very minimal changes to the atrium, four whole tables were removed to accommodate space for the counter and that's about it, that and I added a different kind of wood floor tile to give the floor a bit more of a dynamic look

atrium

**Comment by Draggeru** [comment]
> This wrecks theater.
> 
> Do you expect the clown to play piano looking at a steak grilled on the next tile?

That's literally what they did before, though.

**Comment by Draggeru** [comment]
Why does this have merge conflicts SCREEEE

**Comment by Draggeru** [comment]
Oh that just deleted the whole damn map, whoops.

**Comment by Draggeru** [comment]
Oh god fucking damnit

**Comment by Draggeru** [comment]
Fuck this Im starting over on a fresh branch.

**Pull request closed without merging**
