### PR TITLE
Places missing wire leading to the radiation collector [Metastation]

### LINKED ISSUE #25613: [Metastation] engine collectors missing a wire
The north-easter collector is not connected to the grid.

### PR DESCRIPTION
**Pull request by BeeSting12**
Self explanatory. Places a wire so that the radiation collector is connected to the grid.
:cl: BeeSting12
fix: Metastation's northeast radiation collector is now connected to the grid. Nanotrasen would like to apologize for any inconvenience caused to engineers, but copper is expensive.
/:cl:

Why: Fixes #25613

### CODE REVIEW

**Comment by optimumtact** [comment]
[](https://file.house/mlcI.png)

**Comment by BeeSting12** [comment]
yes please explain as if you are talking to an idiot (because you are) how to fix this

**Comment by optimumtact** [comment]
you can't it's just the way you're doing the merges to keep your branches up to date, I'm just poking some slight fun at it.

**Comment by BeeSting12** [comment]
is it okay to do that though? i can foresee this getting annoying in a few months when i have like thirty update commits and then the commit for the actual PR.

**Comment by optimumtact** [comment]
well you can reset your master branch to match upstream/master from the git cli\

    git fetch --all
    git checkout master
    git reset --hard upstream/master 
    git push -f

and then make branches off it, but might be harder for you if you're using a git gui

**Comment by AnturK** [comment]
You seem to have replaced the shutter instead of adding to it.

**Comment by BeeSting12** [comment]
@AnturK 
I think I put the shutter back in the most recent commit since I noticed in dreammaker but had already PRed it. I'll do a bit of testing to make sure that I actually put it back

**Pull request merged**
