### PR TITLE
Removes step throwers from cult altar

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It's just an invisible newbie trap that kills you for walking towards it and admins are in the habit of just warping people out when they ahelp about it at this point

### CODE REVIEW

**Comment by Repukan** [comment]
Whatever happened to rule 10

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
@Repukan 

Other newbie traps generally give you something to learn from or overcome, the only way you can deal with this ruin is to never go anywhere near it and it may as well not exist in that case

**Comment by ChangelingRain** [comment]
Might as well remove it since all the loot is useless

**Comment by Repukan** [comment]
Sure you learn something.

Don't walk into a bloody blood cult giant rune to try and get goodies in the inside.

**Comment by Repukan** [comment]
And you can reliably escape if you have a medipen since the fire won't kill you fast enough and you can roll it off (even easier if you carry a fire extinguisher in the lava planet)

**Comment by ExcessiveUseOfCobblestone** [comment]
not using the wand to get you across is your fault.

The lesson to be had is to always bring a fire extinguisher.

**Comment by ChangelingRain** [comment]
You can't use the wand to get out if you're not a cultist.

**Comment by ExcessiveUseOfCobblestone** [comment]
wtffffffffffffffffffff

**Comment by ChangelingRain** [comment]
The entire ruin is a trap full of loot you can't actually use unless you're a cultist.

**Comment by ExcessiveUseOfCobblestone** [comment]
the robes are cool tho

**Pull request merged**
