### PR TITLE
Corrects 200+ instances of "it's" where it should've been "its" instead

### PR DESCRIPTION
**Pull request by norsvenska**
## About The Pull Request

it's - conjunction of "it" and "is"
its - possessive form of "it"

grammar is hard, and there were a lot of places where "it's" was used where it shouldn't have been. i went and painstakingly searched the entire repository for these instances, spending a few hours on it. i completely ignored the changelog archive, and i may have missed some outliers. most player-facing ones should be corrected, though
## Why It's Good For The Game
proper grammar is good

## Changelog
🆑
spellcheck: Numerous instances of "it's" have been properly replaced with "its"
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
Changelog is for player facing content only. Read the helpful comments in the template 😢

**Review by Cyberboss — APPROVED** [review]
I'd dying of semantic satiation, but it's good. Speed-merging because fuck conflicts.

**Comment by Cyberboss** [comment]
> Changelog is for player facing content only. Read the helpful comments in the template 😢

There are some player facing grammar corrections

**Comment by norsvenska** [comment]
all checks passing

**Pull request merged**
