### PR TITLE
Adds a new hat for seasoned fishermen

### PR DESCRIPTION
**Pull request by Bytube**
## About The Pull Request
Adds a new hat to ClothesMate vending machines, perfect for the inner angler in you!

## Why It's Good For The Game
Adds a cool new hat

## Changelog
:cl:
add: Adds fishing cap to ClothesMates
imageadd: adds fishing cap sprites
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
image

**Comment by ChungusGamer666** [comment]
relatable

**Comment by LemonInTheDark** [comment]
I don't like this. The joke feels like a meme of the month, similar to other past mistakes like the drip outfit

**Comment by RaveRadbury** [comment]
> I don't like this. The joke feels like a meme of the month, similar to other past mistakes like the drip outfit

Haven't these hats been around forever? I feel like the picture of the otter wearing one of these has been around for ***years***.

**Comment by Farquaar** [comment]
Screenshot? I don't want to open the dmi file.

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/pull/60373/checks?check_run_id=3128117199
We have tools for this 4head

**Comment by Farquaar** [comment]
> 
> 
> https://github.com/tgstation/tgstation/pull/60373/checks?check_run_id=3128117199
> We have tools for this 4head

Cool

**Comment by ATH1909** [comment]
> I don't like this. The joke feels like a meme of the month, similar to other past mistakes like the drip outfit

the drip outfit was not a mistake

**Comment by Bytube** [comment]
I'm fairly new to git and, as you can see here, I think it can be really dumb

**Comment by godspeedfunnyman** [comment]
image

**Comment by Bytube** [comment]
y'know what I'll make another pull request once I fix this shit

**Pull request closed without merging**
