### PR TITLE
Firealarms can no longer be cancelled if the area it's protecting is still on fire

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl: Cyberboss
tweak: A firealarm can no longer be cancelled if the area it's protecting is still on fire
/:cl:

Before, if you cancelled the alarm it would just immediately trigger again.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:-1: At least before gives you a brief window to escape.

**Comment by ChangelingRain** [comment]
This means people in areas with fire can't get out unless they have a crowbar, where currently they can toggle the alarm and run through the doors before they reclose.

**Comment by Cyberboss** [comment]
Yeah, I realize that. I'm trying to think of a way to make firedoors easier for people to get by and harder for actual environmental hazards.

**Comment by Kromgar** [comment]
This is a death sentence for anyone without a crowbar

**Comment by CPTANT** [comment]
Rather odd to say this isn't a balance change when the difference being burned to death because you can't get past an airlock and turning the alarm off and escaping is rather big.

**Comment by ChangelingRain** [comment]
Just a note; I like this. If you're not prepared for shit, surviving should be significantly more difficult.

**Comment by Shapsy** [comment]
yeah if you dont grab the same gear every round whether or not it makes sense to have it on hand, you should just die, gear checks 4 life

**Comment by TehZombehz** [comment]
Just more reason to do roundly powergaming by grabbing a full toolkit roundstart regardless of occupation.

**Comment by CPTANT** [comment]
No being able to pry them open by hand just makes everything hugbox.

**Comment by BeeSting12** [comment]
its fine as it is, give the people with no tools room to escape

**Comment by Cyberboss** [comment]
I honestly think firedoors get a lot of hate because of fucking Central Primary Hallway. It really needs to be sectioned off better. But that would involve adding a lot more areas and apcs

**Comment by KorPhaeron** [comment]
This is how you get through fires though

**Comment by optimumtact** [comment]
I don't like this

**Comment by optimumtact** [comment]
I still don't like this

**Comment by kevinz000** [comment]
this is bad.

**Pull request closed without merging**
