### PR TITLE
Makes all objects that can be constructed on floor tiles also constructable on shuttles, mining station.

### PR DESCRIPTION
**Pull request by as334**
... or any simulated turf.

### CODE REVIEW

**Comment by Razharas** [comment]
Walls, asteroid walls, shuttle walls
Also making walls on the shuttle

**Comment by PKPenguin321** [comment]
>r-walls in the pods
>teleporters in the cargo shuttle

**Comment by Lumipharon** [comment]
Assuming that girders work like every other wrenchable object, you can already build them on the shuttle/pods if you want to.

The main point I want to know however is: I ws under the impression that due to REASONS only shuttle turfs and shit would actually move when the shuttle moves, which is why they're made specifically out of those objects.
If that's currently correct, then walls and shit would just magically get left behind.
If that's in correct, then isn't there no (coding) reason to not have the shuttle/white ship made out of normal constructable tiles etc?

**Comment by FalseIncarnate** [comment]
I'm not entirely sure how things work for you guys, but I know on Paradise you can't build more chairs or tables on the shuttle.

I've built reinforced windows on our shuttle and they seemed to come along for the ride just fine, so I'd assume walls would work the same.

**Comment by Miauw62** [comment]
girders can't be built on shuttle turfs because that lets you make walls which lets you erase the turf underneath.

**Comment by as334** [comment]
yeah it seems this won't really work without some other changes to how the various non-floor turfs work, so i'll close the PR for now.

**Pull request closed without merging**
