### PR TITLE
3/4ths-ify some wall mount sprites (by Kryson and Viro)

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Adds some wallening sprites to the main game. (And splits storage.dmi because I couldn't help myself.) Posters are now MAXIMUM 24px tall except for the blood geometer one because it was added after Viro made all the existing ones shorter.

These do NOT include the directional variants of each sprite. Those will still need to be added later, because they don't make sense right now. 

Ticket machine:
image

Nanomed:
image

Posters:
image

Emergency Safes:
image

TODO:
- [x] Make wall safes actually show the right sprites

## Why It's Good For The Game
Less to review when wallening rolls around. Plus they look pretty good on our current walls anyway. 

## Changelog
:cl: Kryson, Viro, Tattle
imageadd: posters are now 24px tall
imageadd: new sprites for nanomeds, emergency safes, and ticket machines (by Kryson)!
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Sprites are good, for very obvious reasons. 2 years of great sprites, what more could one ask for?

**Comment by san7890** [comment]
man we gotta get those ticket machines off those windows

not really in scope of this PR but they do look exceptionally more ugly being mounted on GLASS

**Comment by optimumtact** [comment]
this PR is completely fucked

**Comment by dragomagol** [comment]
Still have to fix those icons failing tests

**Pull request merged**
