### PR TITLE
Adds medal for the Summer Ball of 2020

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
 add: new medal for the summer ball. it hasn't happend yet so you cant get it. dummy.
/:cl:

prep for summer ball.

### CODE REVIEW

**Comment by optimumtact** [comment]
why on earth would we add this?

**Comment by wesoda25** [comment]
So is this just something people get just for the ball, or something persistent afterwards as a reward for going?

**Comment by Iatots** [comment]
What is this a skinnerbox MMO?

**Comment by Qustinnus** [comment]
whats wrong with having a memorabilia for going to an event? it doesn't affect you in any negative way, it does't change balance. so what possible problem can you have with this?

**Comment by Fikou** [comment]
> whats wrong with having a memorabilia for going to an event? it doesn't affect you in any negative way, it does't change balance. so what possible problem can you have with this?

if a person tries to collect all the achievements (pretty much imposible because of helbitaljanken and pulse rifle arcade but still) they will be unable to do so

**Comment by Tlaltecuhtli** [comment]
why does one have to ERP to get an achievement?

**Comment by Qustinnus** [comment]
lol tlalt go cringe post somewhere else.

**Comment by wesoda25** [comment]
Why are you downvoting that it’s literally just a question

**Comment by optimumtact** [comment]
A) there are a lot of events
B) you can't meaningfully earn these

I just don't' really understand the draw of this, the people going to the events will have the stories and pictures they take from them as well as recordings.

I don't see a good compelling reason to add an achieviement for it as well

**Comment by Qustinnus** [comment]
citrus liked it and I don't see an issue with it either. If you really think its a detriment you can close the PR but I think there's no problems with simple bi-annual holiday event badges.

**Comment by PKPenguin321** [comment]
ah yes, finally osmething persistent i can have on my prfoile that others cannot ever get that i can wank to

**Comment by optimumtact** [comment]
I think if the best justification you can come up with is citrus and I liked it, you're not exactly exceeding expectations

**Comment by Qustinnus** [comment]
if you think it doesnt warrant being added im okay with it being closed. thats up to you (or any other maintainer) comrade

**Pull request closed without merging**
