### PR TITLE
Improve and extend `fieldset_block` and `examine_block`

### PR DESCRIPTION
**Pull request by AyIong**
## About The Pull Request
Maked `fieldset_block` and `examine_block` more stylish and neat, also `fieldset_block` no longer has a centred title.
Renamed `examine_block` to `boxed_message` and adds `custom_boxed_message` which can be colored.

- AdminPMs, admin tickets and vote results has been wrapped into `fieldset_block` for comfort and visibility
- Health Analyzer results painted to blue
- Vote notice and tips of the round wrapped to purple  `custom_boxed_message`
- Tooltip text border color, now uses text color, not just white

## Why It's Good For The Game
Demonstration in both themes

<details><summary>Dark</summary>

image
image
image

</details>

<details><summary>Light</summary>

image
image
image

</details>

## Changelog

:cl:
qol: AdminPMs, admin tickets, vote results and started vote notification are now much more visible in the chat.
qol: Boxed messages in chat (like examine), has been restyled.
/:cl:

### CODE REVIEW

**Review by SmArtKar — CHANGES_REQUESTED** [review]
I like the bar on the left side, but I feel like corner rounding is far too aggressive. Also, really not a fan of how the box curves under the text - maybe try just breaking the line, like we're doing right now? Else it looks really off.

**Comment by AyIong** [comment]
> I like the bar on the left side, but I feel like corner rounding is far too aggressive. Also, really not a fan of how the box curves under the text - maybe try just breaking the line, like we're doing right now? Else it looks really off.

I can change border-radius from 0.5em to 0.33em, which will be less agressive, but breaking the line look's more odd imo, and less sTyLiSh

Also, on 516 it will be all rounded, not only title
image

**Comment by SmArtKar** [comment]
> > I like the bar on the left side, but I feel like corner rounding is far too aggressive. Also, really not a fan of how the box curves under the text - maybe try just breaking the line, like we're doing right now? Else it looks really off.
> 
> I can change border-radius from 0.5em to 0.33em, which will be less agressive, but breaking the line look's more odd imo, and less sTyLiSh
> 

Rounding is nice on bigger blobs but looks really jarring on anything smaller than a human examine, especially on the examine_more you showed here. I'm ***really*** not a fan of how it looks there.

**Comment by AyIong** [comment]
> Rounding is nice on bigger blobs but looks really jarring on anything smaller than a human examine, especially on the examine_more you showed here. I'm _**really**_ not a fan of how it looks there.

Well... then choose border-radius you like
All screenshots from 516, and there are some little issues, but it'll be fixed after 516 got stable

| 0.5em | 0.33em | 0.25em |
| - | - | - |
| image | image | image |

**Comment by SmArtKar** [comment]
> > Rounding is nice on bigger blobs but looks really jarring on anything smaller than a human examine, especially on the examine_more you showed here. I'm _**really**_ not a fan of how it looks there.
> 
> Well... then choose border-radius you like All screenshots from 516, and there are some little issues, but it'll be fixed after 516 got stable P.S. I think 0.33em look's nice

Yeah 0.33em is banging, you should use that one

**Comment by jlsnow301** [comment]
looks good

**Comment by Justice12354** [comment]
Regarding the Admin Tickets/PMs, the buttons (PP, VV, SM, FLW, TP, etc.) are waaay too small to click comfortably on an ever-moving chat. Is it possible to make them slightly bigger, maybe the same size as the rest of the text?

**Pull request merged**
