### PR TITLE
Overhaul contribution guide and enforce snake case for proc and var

### PR DESCRIPTION
**Pull request by optimumtact**
names

This thing was a huge list of stuff, so I'm trying to break it out
further into categorised areas

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I really like this. Isolated files for stuff that requires a lot of context is very nice

**Comment by Mothblocks** [comment]
I'm happy at splitting up our contributing guide, and it's something I've wanted for a bit, but "tips" should probably be "guidelines" or similar, to make it clear they are enforced rules.

**Comment by optimumtact** [comment]
I don't think I have the motivation to finish this.

**Comment by LemonInTheDark** [comment]
I'm going to steal the rehaul part of this and it's too late to stop me

**Comment by optimumtact** [comment]
ok

**Pull request closed without merging**
