### PR TITLE
tgui: Refactor Asset Delivery

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

**Needs testing on IE8!**

This refactor unifies loading of scripts and stylesheets under a single API, which looks like this:

```js
Byond.loadJs(url);
Byond.loadCss(url);
```

These functions are not only used in tgui bundle to load dynamic assets (like font-awesome icons), but also in `tgui.html`, where bundles themselves are loaded.

Both functions have a little bit of network resilience, and will keep trying to load for 10 seconds. If they still fail to load, user will see a blue screen of death instead of a white screen, so this is a definite improvement.

Bluescreen stylesheet is also included directly in `tgui.html`, to make sure it's properly functioning even when scripts/stylesheets fail to load.

I did not notice any slowdown from using `Byond.loadJs(url)` instead of `<script src="url"></script>` which is pretty nice.

## Miscellaneous

- Updated VSCode configuration and installed a few Yarn Berry SDKs to improve intellisense and re-enable eslint.
- Fixed printing of an initial update payload in tgui-dev-server.

## Changelog
:cl:
refactor: TGUI will keep trying to load for 10 seconds in case of a network problem and will show a bluescreen if it completely fails.
fix: This hopefully fixes the whitescreen problem.
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Whitescreen on IE 8 with disabled CDN in all tgui interfaces. Non-Tgui works fine.
Not disabling CDN gives me a whitescreen as per #53997
Round 149971 on Manuel

**Comment by stylemistake** [comment]
Ok, I'll manually debug this on my IE8 VM, it's probably because on IE8 document.body is not yet ready to insert nodes when writing this stuff inline. Thanks for checking.

**Review by Cyberboss — COMMENTED** [review]
👀

**Comment by stylemistake** [comment]
Bug was stupider than I thought, I've slipped a `let` keyword in tgui.html, which is invalid syntax in IE8, but is surprisingly valid in IE11.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
