### PR TITLE
Winter Wonderland holodeck no longer has freon, and it's no longer restricted

### PR DESCRIPTION
**Pull request by lzimann**
Infinite freon is dumb and should not be a thing.
Closes #26716

### CODE REVIEW

**Comment by Robustin** [comment]
Isn't the wildfire simulation infinite plasma?

**Comment by duncathan** [comment]
plasma is a functional gas

**Comment by Robustin** [comment]
Yea functional at the same thing freon is, making the station uninhabitable.

Just saying, if infinite holodeck gas is a bad thing, then look at the Wildfire sim. If this is just freon hate, then at least say so.

**Comment by lzimann** [comment]
The plasma fire breaks the holodeck at least.

**Comment by kevinz000** [comment]
@Robustin atleast plasma doesn't brick servers lmao.

**Comment by Robustin** [comment]
Fine but the trick used by players to flood infinite gas seems like it would work with the Wildfire simulation too.

**Comment by Iamgoofball** [comment]
@kevinz000 prove it's freon with actual factss

**Comment by Kromgar** [comment]
@iamgoofball 

Every fucking time freon gets flooded filation foes from 7 to 20%

**Comment by Cheridan** [comment]
@Robustin infinite freon is way more problematic than infinite plasma. It's basically instant death unless you're already wearing a space suit.

**Comment by Iamgoofball** [comment]
Sounds like a coincidence

**Comment by duncathan** [comment]
@iamgoofball I want you to know how much I hate you

**Comment by Thunder12345** [comment]
Also infinite plasma is already possible through atmos. Infinite freon is bad because there's supposed to be like one can of it on the entire station.

**Comment by Iamgoofball** [comment]
@duncathan not my or your fault they can't prove the connection

**Pull request merged**
