### PR TITLE
Add Croissants & Traitorous Baking Techniques

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

This is my Christmas present to mimes everywhere.

First of all this adds Croissants, because I thought they already existed and was shocked to learn that they did not.
image
Here's a croissant and an unbaked croissant.
In terms of food they are GRAIN, DAIRY, and BREAKFAST and made fairly simply from sugar, dough, and butter.

Secondly it adds this pack of traitor gear, exclusively for Mimes and Chefs.
image
The contents of this pack are:
- One combat baguette, indistinguishable from a regular baguette. If wielded as a sword it gains a 50% block chance (equal to the Captain's sabre) and does 20 damage.
- Two throwing croissants, which do 20 throwing damage and return to your hand like boomerangs.
- A cookbook which teaches you the secret to turning croissaints into deadly boomerang weapons.

You make a croissant into a throwing croissant simply by inserting an expertly bent iron rod into it.
The chef can't make any use of the baguette unless they also gain the ability to mime, but they can use it to make food.

https://user-images.githubusercontent.com/7483112/209454703-feafcf4c-6d0a-4e9a-ac4a-d3e2fc7c0ffb.mp4

Watch me here struggle to use them to kill an ape (they don't return to your hands if thrown at an adjacent tile).

## Why It's Good For The Game

It's insane that croissants aren't already in the game.
This gives mimes an "invisible" sword to go with their invisible gun (it announces to everyone nearby when you're about to use it, but they can't know if it's just a _regular_ baguette).
It's funny to throw bread at people.

## Changelog

:cl:
add: You can now bake croissants to add to your breakfast.
add: Traitorous chefs can bake dangerous throwing croissants, Mimes can do this and gain the additional benefit of a deadly combat baguette.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Where's the evidence?

Chef: Wait eight hours, it'll show up again

**Comment by Oranggu** [comment]
Cant wait for bread sword 👍

**Comment by ATH1909** [comment]
> Watch me here struggle to use them to kill an ape (they don't return to your hands if thrown at an adjacent tile).

this is your brain on non-hotkeyed gameplay

**Comment by Helg2** [comment]
image
It looks just like your croissant.

**Comment by Troxonater** [comment]
Incredible PR. This needs to be merged immediately.

**Pull request merged**
