### PR TITLE
Adds ambience for Reebe.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
soundadd: Reebe now has ambience sounds
/:cl:

found these online, they're pretty neat.

1 and 2 are always active, 3 gets added once the ark activates.

1 - https://vocaroo.com/i/s1S6hnKtxzCb
2 - https://vocaroo.com/i/s0MZyaYukBf0
3 - https://vocaroo.com/i/s0smMYG541r7

### CODE REVIEW

**Comment by Niknakflak** [comment]
These sound like there's one big filter over them which makes them sound shitty and muted.

**Comment by Qustinnus** [comment]
.ogg

**Comment by ChangelingRain** [comment]
These sound too little like the actual in-game description of what reebe sounds like: `You hear the whooshing steam and clanging cogs of a billion billion machines, and all at once it comes to you.`
They also don't match up with the sounds clockcultists hear when converted, which are the sounds of reebe.

**Comment by Qustinnus** [comment]
i asked Xhuis and he said they sound fitting enough.

**Comment by Qustinnus** [comment]
also it's easier to change some flavor text than it is to create perfect ambience.

**Comment by Xhuis** [comment]
I typically viewed the flavor text as your character experiencing a euphoric haze as the brainwashing (since that's what conversion is!) sets in. In the same way that blood cultists see the "veil of reality being torn away", servants see the perceived power of Ratvar. It was also different from that before you changed it some time ago.

I think this is fine; it's muted and dull rumbling, which is what I would imagine Reebe would have, especially given that the playable area has no machinery so anything you *would* hear would be through walls.

**Comment by Iamgoofball** [comment]
>euphoric haze

3i9kjmk
tenor 1
llub55k
tenor 2
vagueconventionalbarracuda-size_restricted

**Comment by Xhuis** [comment]
m'cultist

**Comment by ninjanomnom** [comment]
1 doesn't sound so much like industrial or steampunk machinery and sounds more like underwater fantasy sounds.

2 Just feels empty.

3 Also feels like emptiness. Why is this locked behind the gateway activating?

Just grabbing random music and playing it isn't necessarily good ambience

**Comment by Qustinnus** [comment]
xhuis requested it

**Comment by Qustinnus** [comment]
also it feels empty because you're in a void. any extra steampunk noise could potentially be done by adding sound loops to ratvarian structures.

**Comment by ninjanomnom** [comment]
Then make a soundscape with machinery sounds, not ill fitting music

**Comment by Qustinnus** [comment]
/shrug I asked some people first if they thought it fit, and they said yes. I also think it fits, as once again, Reebe is inside a void.

**Comment by Qustinnus** [comment]
also lot of upvotes

**Comment by Bawhoppen** [comment]
I think it fits pretty well, and I'm not just saying that based on the fact any sound is better than none

**Comment by ChangelingRain** [comment]
There shouldn't be a specific sound for the gateway activating, anyway, since the gateway produces its own sound.

**Review by Cyberboss — DISMISSED** [review]

**Comment by Qustinnus** [comment]
I can also just play all 3 ambiences in general instead of making the third only play when the ark activates, I just listened to a suggestion I got from someone :)

**Pull request merged**
