### PR TITLE
Forensic scanners can now scan storage objs

### LINKED ISSUE #24671: No way to scan held /storage objs with a forensic scanner

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #24671

:cl: Cyberboss
fix: You can now scan storage items with the forensic scanner
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
You already could, just had to be from a distance

**Comment by jughu** [comment]
But that requires you dropping it and scan it from a distance while a greytider can grab it
Also make sure this totally doesnt prevent you from putting a scanner in storages

**Comment by Poojawa** [comment]
Why not just have the scanner have an on/off. on doing the scanning of everything, off allowing you to put it away.

like E-swords.

**Comment by coiax** [comment]
Okay, but can you put it in your backpack

**Pull request merged**
