### PR TITLE
You need to be able to speak to use Hierophant Network/Broadcast

### PR DESCRIPTION
**Pull request by ChangelingRain**
You need to be able to speak to use most scripture, and Hierophant Network/Broadcast is supposed to behave like scripture(but free)

### CODE REVIEW

**Comment by Cheridan** [comment]
you missed the 'why'

**Comment by ChangelingRain** [comment]
Hierophant Network/Broadcast is supposed to behave like scripture(but free)

**Comment by coiax** [comment]
Is this just about mime nerfs to appease goof? Can't bloodcultist mimes talk on cultchat?

**Comment by ChangelingRain** [comment]
yes but I think that's dumb and shouldn't be true but I don't touch cult

**Comment by jughu** [comment]
Cult should be removed replace it with cult of cthulu :)

**Comment by coiax** [comment]
Can mimes be cultists of cthulu

**Comment by jughu** [comment]
No mimes allowed to my bookclub

**Pull request merged**
