### PR TITLE
Adds large metal boxes

### PR DESCRIPTION
**Pull request by Incoming5643**
Like the normal ones, except:

*can fit five people
*can take a lot of punishment before breaking
*slow as garbage to move in
*only exist near the syndicate drop pods
*became utterly required once STEEL RAIN was added

:cl: incoming5643
rscadd: Nuke ops can now harness the power of METAL BOXES: special versions of cardboard boxes that can take a lot of abuse and can fit the whole team if need be. They're not nearly as light as their cardboard brothers though...
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
0/10

also changelog is even worse

**Comment by Anonus** [comment]
METAL BAWKSES

**Comment by Jordie0608** [comment]
#14018

**Comment by Incoming5643** [comment]
He said it wasn't an issue.

**Comment by Man-Shroom-** [comment]
:+1:

**Comment by Iamgoofball** [comment]
BUT CAN THEY FIRE OUT OF IT

**Comment by Incoming5643** [comment]
Not while the box is closed and offering cover, no. But an op can pop out of the top to fire then duck back inside to shield from enemy fire.

Keep in mind if there's more than one guy in the bawks they move said box as a team, If one guy wants to go left and the other wants to go right, they end up shaking back and forth pointlessly.

**Comment by Cebasiz** [comment]
need one of them for tc that has a grenade launcher, please.

**Comment by Cebasiz** [comment]
wait is that even possible

in fact why aren't there tanks in this game fug

**Comment by Alek2ander** [comment]
Time to start selling keys

**Comment by Jalleo** [comment]
Imagine a syndi pid filled with metal boxes of viceoraptors.

**Comment by KorPhaeron** [comment]
THE FOOLS, THE COWARDS

**Comment by phil235** [comment]
Please make a better changelog. Also, the idea is meh...

**Comment by Incoming5643** [comment]
changelog dememed

**Comment by YotaXP** [comment]
Just need to be able to weld it shut to trap them, and gift wrap them for Nanotrasen.

**Comment by Incoming5643** [comment]
metalboard

**Comment by tkdrg** [comment]
I dunno, I like memes but I feel like giving this for free to any ops is a bit too memey. I'd say make it admin spawn but then nobody would spawn it. Maybe make it spawn as a bonus if you buy the pod? Just so we don't see these literally every round.

**Comment by Incoming5643** [comment]
>make dumb joke item
>actually extremely practical and desirable item that's probably too good to be given away for free


SPESS MEHRENS WE HAVE FEHLED THE EMPRA

**Comment by Iamgoofball** [comment]
switch to vehicles system and call it a day

**Comment by Kromgar** [comment]
Wot

**Comment by Incoming5643** [comment]
B Y  R E Q U E S T

**Comment by Kromgar** [comment]
https://www.youtube.com/watch?v=cO3MttgvHUY

OUR ENEMIES HIDE IN METAL BAWXES THE COWARDS!

**Comment by Incoming5643** [comment]
I don't know how the fuck new map mergers work please end the tgm meme or at least add a goddamn readme

**Comment by KorPhaeron** [comment]
tgm was a mistake

**Comment by Incoming5643** [comment]
literally not made a single map edit that wasn't manually changing things in notepad since the change.

**Comment by Incoming5643** [comment]
Nope, it's fucked.

Rest in reeses pieces

**Pull request closed without merging**
