### PR TITLE
Adds foxkin and canid species

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Adds these creatures

## Why It's Good For The Game
It is not
## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Worst timeline

**Comment by Time-Green** [comment]
low effort

**Comment by MoonDeer728** [comment]
dude you're on the wrong server

**Comment by DrDiasyl** [comment]
Literally 1984, speed close of the 80000th PR on this repo SMH

**Pull request closed without merging**
