### PR TITLE
[s] adds plasmaman erp verbs

### PR DESCRIPTION
**Pull request by Supermichael777**
Guns now have safeties. toggle with alt and break/ fix with wiercuters
:cl: Supermichael777
rscadd: After famous clown rapper Big Johnson accidentally shot himself in the crotch local firearms suppliers have started adding safeties to their products.
rcsadd: instructions on how to use these should have been provided to you if you needed to know.
/:cl:

### CODE REVIEW

**Comment by Supermichael777** [comment]
fucking realy

**Comment by Bluespace** [comment]
lmao

**Comment by Bawhoppen** [comment]
YOU WERE SUPPOSED TO USE [s]

**Comment by Bawhoppen** [comment]
pls I beg you stop this

**Comment by Bawhoppen** [comment]
ok well you should have waited for people to forget about it

**Comment by Supermichael777** [comment]
chaf

**Comment by Niknakflak** [comment]
shit pr

**Comment by KorPhaeron** [comment]
You completely fucked this commit

**Comment by Supermichael777** [comment]
yeah I'll redo it proprly

**Pull request closed without merging**
