### PR TITLE
adds wizard gloves

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds enchanted gloves, they are reskinned combat gloves that you get instead of purple gloves with the wizard hardsuit and the battlemage suit
the wizard hardsuit also now gets an oxygen tank and battlemage suit gets wizard sandals

## Why It's Good For The Game

purple gloves are there to finish the outfit but they arent even the same shade of purple
also if wiz actually uses his points on armor i think he should get protection from an ai altclicking a door

## Changelog
:cl:
add: Enchanted gloves! they are reskinned to be cooler combat gloves, you get them for free if you buy a wizard hardsuit or battlesuit
tweak: if you buy a wizard hardsuit you get an oxygen tank, if you buy a wizard battlesuit you get sandals
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
won't the wizard need a mask to use that oxygen tank?

What if, instead of an oxygen tank, you gave them that special oxygen mask from xenobio that doesn't need a tank? It's /obj/item/clothing/mask/nobreath, and I think that it'd be much more wizard-y than a mundane oxygen tank.

While you're at it, could you just go the ninja suit route with the wizard hardsuit and make it not need a cell to protect you from the cold? It's kind of weird that a magical, gem-encrusted suit is battery-operated.

**Comment by Tharcoonvagh** [comment]
Can you tackle people with the gloves?

**Comment by Fikou** [comment]
>Won't the wizard need a mask to breathe from that oxygen tank?

they get a mask in their box already or should at least

> What if, instead of an oxygen tank, you gave them that special oxygen mask from xenobio that doesn't need a tank? It's /obj/item/clothing/mask/nobreath, and I think that it'd be much more wizard-y than a mundane oxygen tank.

no

> While you're at it, could you make the wizard hardsuit not need a cell to protect you from the cold (sort of like how the ninja hardsuit also protects you from the cold without needing to consume any cell charge to do so)? It's kind of weird that a magical, gem-encrusted suit is battery-operated.

wizard hardsuit will be changed in my hardsuit rework

**Comment by actioninja** [comment]
conflict

**Pull request merged**
