### PR TITLE
Unload / Loading mags into firearms SFX ||Hippie Station 13 Port

### PR DESCRIPTION
**Pull request by Weisyl**
Every gun that uses magazines have been given their very own sound
effects which play when the magazine is loaded into or unloaded out of
the gun! In addition, chambering (removing) a round from the gun with no
magazine in also plays its own sound. Credits to Insurgency (standalone)
and Receiver for the sounds.
Additionally, shotguns which load via a tube now also play a SFX when a
shell is loaded. The mosin rifle also has its own sounsd for when the
bolt is moved forward, backward, or when a round is inserted.

This feature was ported from Hippie Station 13.

### CODE REVIEW

**Comment by Anonus** [comment]
Where'd you get the sounds/what is the license on the sounds?

**Comment by DerptheStewpidGoat** [comment]
Sounds come from the standalone version of Insurgency by New World Interactive and Receiver by Wolfire Games. Not sure on the licensing for Insurgency, I can email them on that. I got permission in the past to use sounds from Receiver, over an email.
Also, the folder with all these new sounds is 199 KB. Here's the dropbox which contains them all: https://www.dropbox.com/sh/er9najfvxmx7jay/AADEzaa0oV7hf_Z-eVg8Odl1a?dl=0 
They're all in .ogg format of course.

**Comment by RemieRichards** [comment]
DNM'd until licensing can be confirmed.

**Comment by Bawhoppen** [comment]
We need more sounds overall. I still want footstep noises.

**Comment by Memendia** [comment]
@Bawhoppen we tried that.. It was -okay- but bad

**Comment by optimumtact** [comment]
sound aside, the framework itself would be nice to have for our own sound peeps to use

**Comment by DerptheStewpidGoat** [comment]
Still waiting on a response from the people at New World Interactive. If I don't get a response, then at the very least I can remove the sounds themselves and allow the code to be kept in as a framework.

**Comment by bustygoku** [comment]
Killing floor 1's sounds are fair use now non-commercially, if that helps

Also the source engine's half life 2 sounds but those are all stock now for the most part and sound like shit.

**Comment by DerptheStewpidGoat** [comment]
I could look into that, perhaps this weekend.

**Comment by Dorsisdwarf** [comment]
@DerptheStewpidGoat 

weekend is gone, and you are conflicting

**Comment by duncathan** [comment]
@DerpTheStewpidGoat
Fix conflicts and be absolutely certain about licensing

**Comment by duncathan** [comment]
conflicts + licensing uncertainty + no response from author for 9 days = closed PR

ping me if you wanna reopen it, @DerptheStewpidGoat

**Pull request closed without merging**
