### PR TITLE
Removes vorecode refrence.

### PR DESCRIPTION
**Pull request by Wilchenx**
:cl: Wilchen
tweak: Removed vorecode refrence.
/:cl:

Why: Vore is bad and floyd should feel bad

### CODE REVIEW

**Comment by kevinz000** [comment]
:+1:

**Comment by Wilchenx** [comment]
If you have any other suggestions what to replace "round and full belly" with, go ahead.

**Comment by Armhulen** [comment]
?????????????????????????????????????????????????????????????????

how did "i'm full" translate to vore for you, are you some kind of sicko

**Comment by ExcessiveUseOfCobblestone** [comment]
Did floyd eat one of the "e"s in your PR title as well?

**Comment by CitrusGender** [comment]
is anyone else here full and round

**Comment by Wilchenx** [comment]
@ExcessiveUseOfCobblestone yes, his belly is round and full now.

**Comment by Spaceinaba** [comment]
YEAAA HAAAAA IT'S A **VORE** KINDA DAY

**Comment by Aloraydrel** [comment]
My belly is round and full

I should be more careful next time..

**Comment by ExcessiveUseOfCobblestone** [comment]
^ rarest dorf

**Comment by MMMiracles** [comment]
the moodlet is from eating enough to be full, not from eating a good meal. the replacement message makes no sense in this context.

also you should blame yourself if you automatically connect being full with vore, you closet-fetishist.

**Comment by JJRcop** [comment]
I think it's the *round* belly that is associated with vore.

**Comment by Armhulen** [comment]
?????

**Comment by Wilchenx** [comment]
@MMMiracles 
image

**Comment by Repukan** [comment]
Sheekos

**Comment by cyclowns** [comment]
why not just "I feel full after that meal" or some shit

**Comment by Repukan** [comment]
I'm stuffed! Feels good.

**Comment by Wilchenx** [comment]
Actually this is not worth my coder good boy points and moodlets are disabled anyway

**Comment by Repukan** [comment]
God protects me

**Comment by iskyp** [comment]
>caring about gbp

nice

**Comment by PKPenguin321** [comment]
Wowie~ My big round tummy sure is *stuffed~* after that one..!

**Comment by Wilchenx** [comment]
10 likes and subscribes = i'll reopen

**Comment by Euphausiacea** [comment]
Reopen it shezza

**Comment by Wilchenx** [comment]
image

**Pull request closed without merging**
