### PR TITLE
Sanity Rebalancing

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
 tweak: The Nanotrasen Physological department has realized that working at a metal deathbox is more stressful than it currently is. Mood has been slightly rebalanced
/:cl:

This PR is mostly a rebalance of various variables that exist withing the system. The system is now more likely to skew one of two ways instead of always hanging at neutral unless you're hungry, I plan to make it more likely to skew to one side from other things as well, and nerfed various low effort and non interesting interactions such as reading books while buffing the ones that have gameplay like drinking good bartender drinks or winning arcade games.

I also plan to add a moodlet for being in the bar; this will reinforce players to visit these areas if things get bad, or if they just want to refuel for a bit.

### CODE REVIEW

**Comment by bobbahbrown** [comment]
i have an idea for rebalancing moods you just have to delete them

**Comment by Qustinnus** [comment]
and people act surprised when I ignore specific peoples complaints when all they do is post in bad faith like this

**Comment by ishitbyabullet** [comment]
Insanity was cool when I saw it happen once.

I just wish it didn't slow you down. Really kills the insanity vibe when you're basically a unarmored tank.

**Comment by Qustinnus** [comment]
original insanity was removed because people got mad about the sounds/hallucinations. Then again; it used to be almost instant with low mood.

**Comment by Qustinnus** [comment]
I'm nerfing the slowdown in favor of looking for more interesting debuffs. If anyone has ideas feel free to post them.

**Comment by ishitbyabullet** [comment]
Aw. I wish there was an item to trigger it or something. It seemed cool for potential memes.

**Comment by Qustinnus** [comment]
If @optimumtact is up for it I'd be down with re-implementing low-sanity hallucinations tbf.

**Comment by ATH1909** [comment]
> If @optimumtact is up for it I'd be down with re-implementing low-sanity hallucinations tbf.

You might wanna add a bunch of new hallucinations then, so the old ones don't start to get stale.

**Comment by Detective-Google** [comment]
Tbh I would like low mood hallucinations but the current hallucinations get boring p. Quick

**Comment by XDTM** [comment]
Maybe deep insanity could cause certain brain traumas, which can be healed by becoming sane again

**Comment by ishitbyabullet** [comment]
okay can the brain traumas not be stuff like _"HAH LOOK AT YOU DUMBASS YOU WANTED TO BE INSANE BUT NOPE YOU'RE **P A R A L Y Z E D**"_ or something like that? Being insane shouldn't be **GET FUCKED** tier. It should atleast be interesting.

**Comment by MMMiracles** [comment]
just steal the dont starve sanity mechanic where the illusions turn real for you

**Comment by Dawson1917** [comment]
Hallucinations would be ok if they happen at the lowest level, where your mood meter constantly flips around. Unlike the ridiculously stupid slowdown whenever you feel a bit hungry and slip, you only reach the lowest mood level when things have actually gone horribly wrong. Nothing about mood is fun in its current state because you either guzzle 3 donuts / warm donks at shift start and never worry about it again or you get a shitty slowdown and have to stop what you're doing to fix the debuff before you can continue playing the game. I personally don't think mood will ever work well as a system because you will either powergame it for buffs or, if there are little to no buffs, you'll just do the minimal amount of effort to avoid the debuffs that come as a result of your character getting depressed over things that you really don't care about while playing, but if you want to expand on the mood system you should add effects that are more unique and interesting than objectively weakening you for little reason. Hallucinations are somewhat alright at extreme levels but the current pool of hallucinations are very obvious and repetitive. Some things that play on paranoia might be good, like people sometimes coughing, sniffling or so on at low moods because right now that causes any experienced player to immediately scream disease and get their blood checked.

**Comment by Dawson1917** [comment]
Also I don't think nerfing the antag mood bonus to a third of its original strength is a good idea. You've increased the power of a lot of negative moodlets and lowered the requirements for negative mood levels and now just being hungry is enough to make you the first level of negative mood and only one point above the second level of negative mood, if I'm reading this right. Antags benefit from the mood buff in not having their round stalled whenever they get hungry or a little sad, even if you're slightly nerfing the slowdown in this PR

**Comment by Qustinnus** [comment]
A lot of people feel like the mood buff prevents antags from having to slow down and I think thats a fair point so I nerfed it.

**Comment by kriskog** [comment]
>
> nerfed various low effort and non interesting interactions such as reading books

Why exactly? Isn't forcing people to take the time to do RP stuff the entire point of this mood system? You can call them low effort all you want, but if people bother reading books to improve their mood they deserve a reward for their troubles.

**Comment by wesoda25** [comment]
> I'm nerfing the slowdown in favor of looking for more interesting debuffs. If anyone has ideas feel free to post them.

Might be cool if it acted similar to the brain trauma which causes you to randomly lash out at people. Just make it have hallucinations, and the chance to randomly punch someone next to you. Just please God not the static

**Comment by Qustinnus** [comment]
@kriskog books have barely any player interaction and thus don't offer much interesting roleplay. Things like getting a great drink from the bartender do offer interesting roleplay.

**Comment by kriskog** [comment]
Picking up a glass off bar desk offers more roleplay than picking up a book in library?

**Comment by Qustinnus** [comment]
there's another player involved so yes

**Comment by kriskog** [comment]
And the curator is not a person? In a heavy roleplay job?

**Comment by Qustinnus** [comment]
okay this is a bit of a semantical discussion by now but are you seriously implying that bars, and interactions in the bar, are equally as common as interactions with the curator in the library?  all you need to do is grab one book and put it somewhere and you get an easy +3 moodlet for no actual involvement

**Comment by kriskog** [comment]
You can store drinks in your backpack too. Are you saying RP with the bartender and bar patrons should be worth more than RP with the curator and the book nerds? Because that is dumb.

Now note that I usually don't interact much with mood outside of eating now and then, but you are presenting some flawed logic. It is also highlighting one of my big issues with the mood system in the first place, which is getting told by someone else what I am supposed to be enjoying instead of deciding that for myself.

**Comment by Tlaltecuhtli** [comment]
make the drink check for bartenders in the view field to work

**Comment by Tlaltecuhtli** [comment]
@Qustinnus if you want to improve sanity add rimworld style making reaching 100 insanity give you a trauma and resetting it back to neutral ( by a mood event)

**Comment by Qustinnus** [comment]
I'll do that in the next PR; I'm gonna do mats rework first

**Pull request merged**
