### PR TITLE
Removes most roundstart belts with a exception on medical, engineering and Hos

### PR DESCRIPTION
**Pull request by jughu**
This is mostly a test because kor said we dont really need belts with the new storage system altough this pr doesnt remove belts entirely you can get them from the biogenerator requiring you to do departmental cooperation or just do it yourself at the public garden 

engineering of course keep their belts for quick access to tools same with medical
and hos keeps his belt for better management

:cl: hyena
tweak: Removes some roundstart belts
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)Because i think this atleast worth a try to lower the storagecreep

### CODE REVIEW

**Comment by Cyberboss** [comment]
What the actual fuck? :-1:

**Comment by jughu** [comment]
T E S T M E R G E

**Comment by Grazyn** [comment]
What is the "new storage system"? This sounds like a nerf to assistants and nothing else

**Comment by jughu** [comment]
image

my words of wisdom

**Comment by Grazyn** [comment]
Oh now I get it it's an overreaction PR because Kor dared criticize your botany belt PR. Carry on

**Comment by Cyberboss** [comment]
This is literally just sec, janitor, and bartender nerfs

**Comment by CPTANT** [comment]
I like the part where you say you can just get belts from the bio generator and then nerf the bio generator by increasing belt costs.

**Comment by jughu** [comment]
image

**Comment by Grazyn** [comment]
>"here's a buff for this job"
>"I think we have given enough buffs to jobs, that's getting close to powercreep"
>"Alright I'm gonna nerf all jobs then"

Can't tell if it's an overreaction or if it was your plan from the start

**Comment by PKPenguin321** [comment]
Honesty, doctors probably don't need belts (they have medkits) either unless they're carrying a defib. Maybe put one medical belt per defib in the closets.

**Comment by jughu** [comment]
@PKPenguin321 that should already be the case

**Comment by PKPenguin321** [comment]
Oh nice

**Comment by Buggy123** [comment]
>implying carrying a bunch of shit is easy to accomplish and all you need to be a 1 man army.

**Comment by jughu** [comment]
it is easy i done it plenty of times

**Comment by Buggy123** [comment]
There are so many ways to be robust in almost any given situation that I'm not even going to start to describe them. Its all about being clever and thinking on your feet, carrying tools around in a belt is at best a supplement.

If you are robust you'll probably figure out some other way to handle whatever situation would need 7 slots worth of small items, if you aren't robust then you're fucked anyway. I don't see how removing belts is going to change this.

**Comment by jughu** [comment]
im not removing belts im just removing belts from roundstart equipment since you dont really need it

**Comment by Buggy123** [comment]
In practice though that removes access to belts for a lot of people.

**Comment by jughu** [comment]
Public garden exists farm here if you really want a belt

**Comment by Buggy123** [comment]
So the assistants can spend 10 minutes farming for a belt instead of scouring maintenance/getting into EVA/participating in a ritualistic death match for the entertainment of engineering?

I still think it'd make it at least a fair amount harder to get a belt, and all the while the slated reason is "it makes people into one man armies", when the thing that _actually_ makes people into one man armies is robustness. A idiot can die with a pulse rifle and armor, while a person who has earned the title of **ROBUST** can murder all of security with a bar of soap.

And I don't see how needlessly changing one part of the game in the name of "powercreep" is gonna change this. If anything it gives the unrobust masses a leg up.

**Comment by CPTANT** [comment]
Seriously, if you want people to farm for their belt then why did you increase belt cost?

**Comment by jughu** [comment]
Right

**Comment by Durkel** [comment]
Imagining someone whose job is construction having to constantly wear a backpack that has a small cardboard box that holds all their tools instead of just wearing a tool belt like a normal person is fucking stupid.

**Comment by jughu** [comment]
Years ago we did fine with stuf in our backpacks i dont see why that would be a problem considering we now have a exact storage then just 7 slots

**Comment by Buggy123** [comment]
^^ that too. Mah RP.

@ the changes you just made - why just remove secbelts and the janitor's belt?

The janitor is probably one of the few people who _need_ a belt.

Sec gets tasers, handcuffs, disablers, potential access to the armory (lasers, guns, armor), and # **BELTS** OH GOD NERF IT NOW.

**Comment by jughu** [comment]
Because i have vietnaam flaashbacks of a janitor stuffing 5 slip items in there without taking real space

**Comment by Buggy123** [comment]
Janitor is the baron of slips, second only to **GOD EMPEROR OF ALL THINGS YELLOW AND SLIPPERY, _HONKERS THE RUTHLESS_**. If he manages to find 5 slip items then fine, let him have 5 slips. A real robuster would get by with 1 anyway.

**Comment by jughu** [comment]
Its not hard finding 5 spraybottles or soap

**Comment by Buggy123** [comment]
But you don't usually really need 5 spraybottles or bars of soap, outside of certain situations like being chased by a lot of people.

And if you have gone through the effort to get 5 bars of soap, and have the robustness to use 5 bars of soap, and encounter a situation where you need 5 bars of soap, then you should be allowed to use 5 bars of soap.

Its not like 5 bars of soap are gonna help you in every conceivable situation anyway, if you prepare for a given situation which you may or may not encounter, you are taking time that you could be using to do something else useful instead. I fail to see the problem here.

5 bars of soap

**Comment by CPTANT** [comment]
can't we just close this already?

**Comment by Buggy123** [comment]
Yes, lets close it please. I'm pretty sure the feedback here has been resoundingly negative.

**Comment by jughu** [comment]
This is atleast worth a testmerge

**Comment by jughu** [comment]
You guys are only saying this because you dont like change we did fine years ago with backpacks so why shouldnt it be now the case with the new way storage is handled

**Comment by Buggy123** [comment]
okay sure

**Comment by FlattestGuitar** [comment]
Adds nuance to the game; less hugbox.

I don't see why not, to be fair.

**Comment by BeeSting12** [comment]
Security needs belts more than medical

**Comment by jughu** [comment]
They never needee them the year 2010-2012 security was fine we didnt even had secbelts we all managed fine but then everything got hugbox and now people dont like change

**Comment by DesolateG** [comment]
>belts are hugbox

lol wut

**Comment by CPTANT** [comment]
*claims people don't like change.*

*Wants things to return to how they were in 2010 because everything was better then.*

**Comment by Buggy123** [comment]
Things always change over time, people like change and they don't like change and this changes too, change changes and changing changes changes so that changing changes changes into a desired change to changes, except when it changes so changing changes changes changes. So changes changing and changing reactions to changes changing are unchanging, except when they change.

wait what were we talking about? i think the topic changed

**Comment by Grazyn** [comment]
@jughu If you really miss the good old days of no belts why do you have an open PR to add another type of belts for botany? Man you sure change your mind quite fast

**Comment by BeeSting12** [comment]
@jughu 
I wasn't around in 2010, but I will say that I've played security without sec belts and that it's a lot less enjoyable. Birdboat doesn't have secbelts in the lockers, so you're forced to carry all that crap in your bag. Not fun, at all.

**Comment by Jalleo** [comment]
Trust me belts are there for sec engineering medical and janitor to prioritise their equipment in the belt and everything else in the backpack. If you are all complaining about boxes being the issue deal with those.

**Comment by PKPenguin321** [comment]
Don't know how long you guys have been around so I'll try to break down why this is okay.

It used to be (only a year or two ago) that backpack storage didn't scale with the size of the items placed in it. You could hold 7 energy guns or 7 cigarette butts, and both would take the same effective amount of space. Storage was very scarce and I found myself having to drop stuff to carry other stuff on a fairly regular basis, and this was just how it was. It also used to be that if you had a container in your backpack (a box, a medkit, etc) you had to take it all the way out of your bag before you could get to the stuff inside of it, so things like a box in your bag with tools in it was impractical. This means that belts like toolbelts not only saved precious backpack space but also let you get out your tools quickly without 15 seconds minimum of inventory fumbling. 
Now both of those things have changed. Now you can hold 3 or 4 rows of stuff in your backpack if they're all small sized. You can hold six guns plus an energy sword, ebow, and emag. You can take stuff out of your medkit in your backpack without having to hold it in your hand first, making it effectively like a toolbelt.

Before, things like the janibelt were basically necessary: He needs to carry like 7 different small tools at the minimum, which in the past would completely fill your backpack space. Now it would take maybe a third of it tops. The same goes for security belts. Handcuffs, flashes, pepper spray, flashbangs, all small items. Before that would leave you with one or two slots left in your backpack, so a belt was needed. Now that would only take maybe a fourth of your backpack space, tops, and that's assuming the rest of the items you put in your bag are all regular sized.

None of this even accounts for stuff like duffelbags or pockets in clothing.

So yeah. Belts used to be pretty much absolutely necessary for a couple of jobs, but now they only rarely are.

**Comment by Hatfish** [comment]
who the fuck sticks a bunch of tools that they intend to use in a box inside their backpack?
and what the fuck is this about storagecreep?  must be some fucking glacial action here because I haven't seen any PRs trying to buff belts since yours a few days ago.

**Comment by PKPenguin321** [comment]
You've failed to read my post. Also, we use fancy boxes for stuff like that already in a couple of ways: Toolboxes, medkits.

**Comment by Hatfish** [comment]
Fair enough.
I still think this is dumb since it's fueled by jughu's salt over his other PR being denied.

**Comment by ExcessiveUseOfCobblestone** [comment]
remove all the belts and force people to use the disgusting fanny packs

**Comment by kevinz000** [comment]
is this another jughu is salty episode?

**Comment by Haevacht** [comment]
Jughu, stop.

**Comment by jughu** [comment]
image

it wouldnt affect you badly plenty of room in here

**Comment by jughu** [comment]
Those are in my box bro with the exception on the donut and evidence bag

**Comment by Grazyn** [comment]
You know what, I thought about it and I changed my mind. I think it should be merged, for 3 reasons:

1. Anything that nerfs security can't be that bad
2. It solves to problem of sec officers turning into walking pinatas. You can still carry essential equipment without the belt but at least you won't give a crate worth of gear to the first rev who stuns you
3. Salty PRs should always be merged, as long as they're reasonable. After all, that's what you would do with a child throwing a tantrum in the same way

**Comment by Arianya** [comment]
> Back in the day we had polio and we *liked* it. None of this fancy vaccine stuff. What you think you're too good for polio!? Remove vaccines
- jughu, 2017

Nerfing security storage is never good, because either you'll push them to wearing dufflebags (woo woo here comes the slowpolice) or they'll simply not take things that aren't the kind of loot that cult/revs want anyway. The main items (stuns, cuffs) will still be carried and still be loot pinata'd

**Comment by jughu** [comment]
You can carry your stuff perfectly taser baton on belt/suit flashbang/handcuffs in your pockets and flashes/peppersprat fits in backpacks easily dont even take a big slot since its a tiny item and if it isnt that enough you can fit it in your box

**Comment by jughu** [comment]
Its not even close to a real nerf it just removes 4 slots where you basically could fit batons in or flashbangs n stuff when it all can be perfectly fitted in your inventory without trouble

**Comment by jughu** [comment]
What belts really do is beepsky just not arresting you for a baton when unauthorized

**Comment by AdamElTablawy** [comment]
this is some grade-A concentrated autism right here

**Comment by ExcessiveUseOfCobblestone** [comment]
can someone provide a better argument that is actually an argument as to why you /need/ so many slots on your persona?

Not being able to carry everything you need in a hard-to-counter way [i'm thinking acid] is a GOOD thing

**Comment by Arianya** [comment]
Well, for one thing the bandolier is solely aimed at carrying ammo, is cool looking and having a backpack/box in a backpack full of shotgun shells is unwieldy.

For another, for security a belt is giving up a holster slot that could have a gun in it ready for quick access, and the exosuit holster slot is able to hold more interesting stuff (like riot shotguns) compared to it.

For a third, are janitors really in need of a nerf? Maybe its just me but I've yet to see the slipmaster traitor janitor murdering the whole station with his ~expanded storage~

**Comment by jughu** [comment]
@arianya its not like you can backpack the taser for riot gun but it isnt really needed since you mostly need 1 stun to finish them anyways and the belt auctally increases baton capiticy by putting in 4 batons in a belt since its mostly a medium object aka basically extending your recharge time between patrols

Bandoliers were mostly combat shotgun tier since you couldnt suit storage or put in your backpack AKA why it was added to put it in your belt for easier reloading with combat shotguns when the bartender can easily open his backpack drag the box to himself for quick access

Janitprs also can carry everything easily in their backpacks since the wet sign projector got added then sacraficing 3-4 slots to wet signs

**Comment by Haevacht** [comment]
Come on let's reach 20 downthumbs we can do it.

**Comment by GunHog** [comment]
beltnerfpr

Looks like we did it!

**Comment by KorPhaeron** [comment]
This PR is a great example of how everyone will talk big about hating hugbox and wanting paranoia but they'll always cling to "quality of life" in the end.

This PR is too much of a bandaid solution though, better to save the angst for a full inventory overhaul

**Comment by KorPhaeron** [comment]
@PKPenguin321 

Explained this very well though, we've gone to carrying 7 accessible items in our backpacks to carrying 30+ items, and then toolbelts, pockets on clothes (mostly reverted), etc

**Comment by Militaires** [comment]
@korphaeron just merge it tbh fam.

@BeeSting12 sec doesnt even need belts other than to be a human armories, look at goon for example, they're a-ok and they're not pussies about storage.

@AdamElTablawy good job at detecting it, you must be experienced faggot.

@Hatfish yeah totally realism is a good argument yeah tg should really be realistic totally

@Haevacht yeah 20 reddit downboats nobody gives a shit about.

give me 20 valid points and ill refute all 20, belts are as shit as the points seen here.

# if you faggots like belts so much how about i whip your ass with one.

**Comment by BeeSting12** [comment]
@Militaires 
You don't understand much about this game if you think that carrying a flashbang, flash, stunbaton, pepperspray, and spare cuffs makes you a walking human armory.

**Comment by Militaires** [comment]
@beesting12

what you mentioned is shit you can already carry WITHOUT a belt, what im talking about is using all of the unnecessary slots.

taser, riot shotgun, stunbaton, strobe shield/riot shield, flash, pepper, cuffs and zipties, and ammo for the various ballistic weapons they might have on themselves u what mate.

^^^^^^^^ you can already carry all of that using a backpack why do you need a belt other than for cosmetics

you can probably carry more thanks to the fact that we grew to 300 fucking slots man not counting snowflake shit like boot storage

edit: 
>fuck goon what do they have to do with us

"YOU CANT USE SOMETHING THAT HAS A BETTER SYSTEM AS AN EXAMPLE GO TO THEIR SERVER WHAT DO THEY HAVE TO DO WITH US" nice autism

**Comment by BeeSting12** [comment]
I feel like our system is fine. It works okay already, I have not once heard someone say "WELL IF ONLY THAT OFFICER DIDN'T HAVE A SECURITY BELT I WOULDN'T HAVE BEEN ROBUSTED" or anything like it. If there hasn't been a balance issue for the 6 (?) years we've had belts, I wouldn't think there is one now.

**Comment by KorPhaeron** [comment]
We haven't had super backpacks for 6 years though.

Belts used to server an organizational and storage purpose, now it's just extra.

**Comment by Militaires** [comment]
@BeeSting12 because it's useless.

and what kor said.

**Comment by CPTANT** [comment]
the "super" backpacks usually allow for only 1 or 2 extra small items in the first place.

Basically the "super" backpacks mean you don't have to carry another box around.

**Comment by optimumtact** [comment]
you're like a flaming rocketship that's spinning out of control and I want to see what happens when you crash

**Comment by jughu** [comment]
Crashing this world no survivors

**Pull request closed without merging**
