### PR TITLE
Living heart shows an arrow in direction of scanned target.

### PR DESCRIPTION
**Pull request by Xackii**
## About The Pull Request

Снимок экрана 2024-11-03 173359

Arrow points to the target for 5 seconds and then disappears.
Also fixed pinpointer breaks and give runtime if scanned target moved in nullspace.

## Why It's Good For The Game

A few conveniences for heretic.

## Changelog

:cl:
qol: heretic living heart now points to the target with an arrow.
fix: pinpointer no longer breaks if scanned target disappears from our reality.
/:cl:

### CODE REVIEW

**Comment by Holinka4ever** [comment]
Finally, days of googling compass are numbered!

**Comment by Xackii** [comment]
> Finally, days of googling compass are numbered!

yes me too

**Review by SmArtKar — CHANGES_REQUESTED** [review]
I dislike how the status bar looks, maybe make it a radial pointer around your character instead? Think beestation's hardsuit beacon pointers.

**Comment by Xackii** [comment]
> I dislike how the status bar looks, maybe make it a radial pointer around your character instead? Think beestation's hardsuit beacon pointers.

This will be annoying and inconvenient for those who look at the description of the compass because this text also appears in the center

**Comment by carlarctg** [comment]
> Finally, days of googling compass are numbered!

bro if you dont know the compass directions..............................bro

**Comment by SmArtKar** [comment]
> > I dislike how the status bar looks, maybe make it a radial pointer around your character instead? Think beestation's hardsuit beacon pointers.
> 
> This will be annoying and inconvenient for those who look at the description of the compass because this text also appears in the center

Then do the compass separate from the status effect, by passing an image of the pointer to the user's client

**Comment by Xackii** [comment]
> > > I dislike how the status bar looks, maybe make it a radial pointer around your character instead? Think beestation's hardsuit beacon pointers.
> > 
> > 
> > This will be annoying and inconvenient for those who look at the description of the compass because this text also appears in the center
> 
> Then do the compass separate from the status effect, by passing an image of the pointer to the user's client

don't understand

**Comment by MrMelbert** [comment]
Agree w/ Smartkar, in fact you could(should) replace the text entirely and just have it be an arrow that points from you to your target, size scaling on distance

image

**Comment by Loafin34** [comment]
i would look at the harvester code for tracking objects if you want it to be detailed like that

**Comment by Xackii** [comment]
smthing like this
https://github.com/user-attachments/assets/3c87f926-2763-4ed1-8686-28ab1c20a69a

**Review by Wallemations — CHANGES_REQUESTED** [review]
> Agree w/ Smartkar, in fact you could(should) replace the text entirely and just have it be an arrow that points from you to your target, size scaling on distance
> 
> 
> 
> image
> 
> 
> 
> 

Seconded, though it could be color depending on distance instead, though we still also need to keep in mind for colorblind folk

**Comment by Xackii** [comment]
https://github.com/user-attachments/assets/da9c42d1-2b08-4b34-ae2c-3cef57e39b1e

**Review by Wallemations — APPROVED** [review]
Seeing that arrow gave me ideas on using filters to make the arrow smaller the further you are from someone (like in #87435) _**BUT**_ I'm not about to make you change this when it works well enough to merge as-is
I won't make you add that unless you wanted to

**Comment by Xackii** [comment]
> Seeing that arrow gave me ideas on using filters to make the arrow smaller the further you are from someone (like in #87435) _**BUT**_ I'm not about to make you change this when it works well enough to merge as-is I won't make you add that unless you wanted to

I can do this with transform, but I'm afraid that the arrow will become even more pixelated what happens when arrow points at 45 degrees.

**Comment by Wallemations** [comment]
> > Seeing that arrow gave me ideas on using filters to make the arrow smaller the further you are from someone (like in #87435) _**BUT**_ I'm not about to make you change this when it works well enough to merge as-is I won't make you add that unless you wanted to
> 
> 
> 
> I can do this with transform, but I'm afraid that the arrow will become even more pixelated what happens when arrow points at 45 degrees.

That's why I suggested the filter, and why I said I wouldn't force you to do it lol

**Pull request merged**
