### PR TITLE
Renames Guvax to Geis

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
spellcheck: Renamed Guvax to Geis. This also applies to the component, which has been similarly renamed.
/:cl:

God, this was just a PUN. `Hold your slab in your hand and Guvax` translates to `Hold your slab in your hand and Think` and holy shit why xhuis, why.

Geis is generally better because it has associations; if you see "Guvax" without knowing anything about ratvar cult, it's meaningless, but if you see "Geis" there's at least a decent chance you'll know that means some sort of magical binding.

And I think the brief confusion of the people who are already good at the mode is worth new players sometimes going "oh it's called Geis that's probably conversion".

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Really makes you think

**Comment by Militaires** [comment]
did you think before making this PR

**Comment by KorPhaeron** [comment]
Is it worth the confusion of changing names in an already complicated mode to fix a sentence nobody but you and xhuis understand?

**Comment by RemieRichards** [comment]
Hey, I understand it too! I wrote the conversion proc for the language.

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't get the joke 😢

**Comment by ChangelingRain** [comment]
It's a dumb joke, a DUMB joke, and I hate it enough that it's worth it.

**Comment by optimumtact** [comment]
Remove that whole stupid language

**Comment by ShadowDeath6** [comment]
Guvax sounds nicer imo

**Comment by PKPenguin321** [comment]
Dumb pr :-1:

**Comment by Xhuis** [comment]
nooo 😞

**Comment by ChangelingRain** [comment]
But no really this pr isn't a meme; if you see "Guvax" without knowing anything about ratvar cult, it's meaningless, but if you see "Geis" there's at least a decent chance you'll know that means some sort of magical binding.

The association is worth it.

**Comment by RemieRichards** [comment]
well geis is irish for taboo.
so it doesn't really mean magical binding.

**Comment by ChangelingRain** [comment]
It's often used to mean a magical binding, though.

**Comment by ChangelingRain** [comment]
Also I think the brief confusion of the people who are already good at the mode is worth new players sometimes going "oh it's called Geis that's probably conversion".

If I was willing to sacrifice theme for usability this wouldn't be a problem, but theme can be the difference between people enjoying something and thinking it's shit.

**Comment by Thunder12345** [comment]
How many people actually know what Geis means though? Guvax superior lrn2gitgud

**Comment by ChangelingRain** [comment]
GUVAX DOESN'T MEAN ANYTHING UNLESS TRANSLATED SO THE NUMBER OF PEOPLE WHO KNOW WHAT GEIS MEANS IS GREATER THAN THE NUMBER OF PEOPLE WHO KNOW WHAT GUVAX MEANS

**Comment by Thunder12345** [comment]
GIT GUD

**Comment by KingPhilipIII** [comment]
GUVAX 2016. DOWN WITH GEIS

**Comment by Cheridan** [comment]
this pr is really gei

**Comment by xxalpha** [comment]
They're both meaningless to me.

**Comment by KorPhaeron** [comment]
I don't really care but it's Joan's mode so ???

**Comment by Xhuis** [comment]
\>1 thumbs-up
\>7 thumbs-down
you've really outdone yourself this time, kor, excellent work

**Comment by KorPhaeron** [comment]
not an argument

**Pull request merged**
