### PR TITLE
Corrects the HoS not having a spare gun fabr- I mean, departmental protolathe board.

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by ACCount12** [comment]
No one else has one, why HoS should?

**Comment by CPTANT** [comment]
CE has one....

**Comment by 81Denton** [comment]
The CMO, QM, RD, HoP and CE have spare protolathe boards in their lockers. Maybe you were thinking of a different server?

**Comment by juanototo2** [comment]
## **Insert powercreep "but muh consistency" meme here**

**Comment by DoctoreMad** [comment]
@juanototo2 It seems he was always meant to have one on his locker so how is this "powercreep"?

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
