### PR TITLE
Replaces some obnoxious ambient sounds

### PR DESCRIPTION
**Pull request by winterboekje**
## About The Pull Request
There were a couple of space ambient sounds that were just full like 1-2 minute songs that I've always hated, so I removed them from the list and made 3 new much less intrusive ambient sounds to fill the void.
## Why It's Good For The Game
It's really annoying, they're almost constant and the only way to stop them is to manually turn off ambience and turn it back on or to trigger another such as going on the station.
## Changelog
:cl:
sounddel: Removed obnoxious ambient sounds from space and a few other places.
soundadd: Added less obnoxious ambient sounds to space.
/:cl:

### CODE REVIEW

**Review by Mothblocks — CHANGES_REQUESTED** [review]
people got mad the last time we tried to remove title2 from space ambience. also i like the music. havent listened to your ambience but just add yours without removing the music

**Comment by Mothblocks** [comment]
also its a feature freeze so do this next month

**Comment by winterboekje** [comment]
Alright, I'll go ahead and add them back and merge them when the freeze is over. Thought do you think it would be cool to make some of them a little quieter? Like, the entire thing with space is it's really quiet usually

**Comment by Mothblocks** [comment]
You can try but I'm like nearly deaf so I'm not the right person to judge

**Pull request closed without merging**
