### PR TITLE
Adds camera to Medbay Surgery B

### PR DESCRIPTION
**Pull request by Archanial**
Adds new camera to surgery b eliminating some blind spots.

:cl: Archanial
add: Added new camera to Medbay Surgery B

/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
did you mapmerge
https://tgstation13.org/wiki/Map_Merger

**Comment by nemvar** [comment]
yep, mapmerge pls

**Comment by Tlaltecuhtli** [comment]
add one to incinerator for some reason it doesnt have any

**Comment by Dorsisdwarf** [comment]
maybe its not meant to

**Comment by nemvar** [comment]
incinerator is part of maint on some maps, so it makes sense that there is no camera

**Comment by Tlaltecuhtli** [comment]
it doesnt anymore now that incinerator is a high danger place as armory and toxins

**Pull request merged**
