### PR TITLE
Nuke Op AI card is single use as described

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

This item was supposed to allow the purchaser to put an AI into their mod suit, however as written nothing except available ghost count stopped you from using it over and over again so that every op on the team had an AI suit.
Now we just destroy the item if you successfully transfer the AI into anything so you can't reuse it.

Also I moved it to its own file rather than having the definition of this item be above every other proc definition in the file, including some it was using.

## Changelog

:cl:
fix: The Nuke Op MODsuit AI downloader only works once per purchase, as intended.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
I'm so confused. I *know* I did that. I know I added a one use check. But.. it's not here. I don't know what happened, but I'm sorry you had to scoop up my garbage twice in a row.

**Comment by Jacquerel** [comment]
> I'm so confused. I _know_ I did that. I know I added a one use check. But.. it's not here. I don't know what happened, but I'm sorry you had to scoop up my garbage twice in a row.

its easily possible that _I_ removed it by accident when making my other changes

**Comment by carlarctg** [comment]
> > I'm so confused. I _know_ I did that. I know I added a one use check. But.. it's not here. I don't know what happened, but I'm sorry you had to scoop up my garbage twice in a row.
> 
> its easily possible that _I_ removed it by accident when making my other changes

image

Oh hey you did lol. 👍

**Comment by san7890** [comment]
conflicts

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
