### PR TITLE
Drying Rack Sprite

### PR DESCRIPTION
**Pull request by ghost**
drying rack nienhaus
Sprites by Nienhaus based on Bay's current drying rack sprites.
:cl: Nienhaus
add: Drying racks have new sprites.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Nice

**Comment by WJohn** [comment]
Pretty much anything is an improvement so 👍

**Comment by Xhuis** [comment]
> visions of toolbox...

( :+1: )

**Comment by PKPenguin321** [comment]
I hate this meme
Nobody cares about drying racks but toolboxes being incredibly robust was one of the first things I ever heard about this game
Reeeeeeee toolbox sprite memes trigger me

**Comment by dannno** [comment]
You probably don't want to which is understandable but we're starting to move away from the weird pseudo-3D stuff and it would help if you would consider doing it in a more head on 3/4 style eg.

**Comment by Xhuis** [comment]
Holy shit I need those in my life

**Comment by Nienhaus** [comment]
unknown
I have some vendors similar to that.

**Comment by Nienhaus** [comment]
If you want to keep with the style that's moving forward currently.
ejwfwdenhcamanbdgiawuhddhibbc0ojrfhjcrvfe1_zzmts5ladsghspxseuxxlmvu1jbldny9tboebsmoux127cvgqoyncf1igiqvz4jnbcamnn3bjmbdh6z_ob7ejn_p7awy2iti
https://www.dropbox.com/s/9q40lubuftvn58c/Drying%20rack.dmi?dl=0

**Comment by Kromgar** [comment]
@Danno HNNNNNNNNNNNNNNNG

**Comment by dannno** [comment]
there aren't side sprites
those are attempts at just computers 
i am still working on it

**Comment by WJohn** [comment]
Use the ones suggested by nienhaus, since they follow the 3/4th perspective we've been moving towards.

**Pull request merged**
