### PR TITLE
Changelings opening airlocks with armblades now produce a sound

### PR DESCRIPTION
**Pull request by ChangelingRain**
Changelings opening powered airlocks now produce a sound. The airlock being opened now always produces the grinding open airlock noise.

### CODE REVIEW

**Comment by LanCartwright** [comment]
please consider my alternative:
lings can use acid to melt the weld away, then they can rip it open with armblade.

**Comment by optimumtact** [comment]
No I dislike this immensely

**Comment by TechnoAlchemisto** [comment]
I liked the thing where eswords could cut the weld but armblades are just like, bone swords it don't maek sense

**Comment by ChangelingRain** [comment]
changelings are ferocious assholes and you can do anything if you have enough time

**Comment by Razharas** [comment]
Proper welder stitch is harder than the surrounding material due to on-creation tempering
Even hollow stitches hold as much strains as the 3d structure they are made on, and i assume in the future they invented a method to make planar stitches(full depth contact surfaces melt) which should be much harder that the rest of the construction unless all of the construction is finish-tempered(calculating the thermal stress distribution of the complex shape so the after-temper dimentions are exactly as needed is quite a task)
Anyway since welding tool can take down walls and ling armblade has as much power as the welder apparently it would only be logical to allow lings to take down walls too

**Comment by ChangelingRain** [comment]
Removing the weld takes an entire minute, applying/removing it with a welder takes 4~ seconds.
Thus, the arm blade is not nearly as powerful as the welder because that's like a 1400% increase in time taken

**Comment by KorPhaeron** [comment]
Not sure removing improvised solutions to dealing with changelings in the absence of a gibber/crematorium is a good thing.

**Comment by TechnoAlchemisto** [comment]
Not every antag needs a way out of rooms

**Comment by Jalleo** [comment]
Changelings have lessor form already

**Comment by optimumtact** [comment]
@KorPhaeron @Cheridan needs a final decision.

**Comment by KorPhaeron** [comment]
It's just a sound now

**Pull request merged**
