### PR TITLE
Fixes appearance bans and changes to logout message in check antags

### LINKED ISSUE #17550: Check Antagonist panel shows disconnected players as having ghosted
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
This is understandably kind of a problem, it should only show *actually ghosted* players as having ghosted, not players who have actually disconnected.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Fixes appearance bans
Removes the entire APPEARANCE_PERMABAN type in favor of making it a jobban.
SQL changes included in the changelog.
Changes check antag (ghost) to (no client)
fixes #17550

### CODE REVIEW

**Comment by ChangelingRain** [comment]
it'd be nice if you could see at a glance if the guy's actually ghosted/in another mob or just disconnected

**Comment by Shadowlight213** [comment]
Closing because oranges is working on this already.

**Comment by Shadowlight213** [comment]
Reopened because oranges didn't end up doing the refactor.

**Comment by optimumtact** [comment]
Ready?

**Comment by Shadowlight213** [comment]
Not quite actually. I wanna triple check and run this through my local db to make sure it's working correctly.

**Comment by Shadowlight213** [comment]
Yeah. testing failed. not ready yet. Gimme a bit.

**Comment by Shadowlight213** [comment]
Now it's ready.

**Comment by Shadowlight213** [comment]
Lmao all the people suddenly ahelping about identity bans from like 2013.

**Pull request merged**
