### PR TITLE
Fixes being unable to build rice hats

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix:now you can build rice hats again
/:cl:

### CODE REVIEW

**Comment by zaracka** [comment]
How about adding a separate category for clothing?

**Comment by ExcessiveUseOfCobblestone** [comment]
that touches tgui and touching tgui is not fun

**Comment by AnturK** [comment]
What's the problem here ?

**Comment by Cyprex** [comment]
Needs PRB: No Update, and yeah please use a descriptive title.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
