### PR TITLE
Fixes clockcult's overreliance on Replicant Alloy

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
experiment: Clockwork Proselytizers no longer require Replicant Alloy to function; instead, they gradually charge themselves with power, which is used more or less the same as alloy.
tweak: Clockwork Proselytizers now produce brass sheets when used in-hand, instead of Replicant Alloy.
rscdel: Tinkerer's Caches can no longer have Replicant Alloy removed from them; using an empty hand on them will simply check when they'll next produce a component.
rscdel: Mending Motors can no longer use Replicant Alloy in place of power.
/:cl:

Is this a good idea/the right way to go?
It'll probably result in another round of component generation balance/slowdown, given that you won't LITERALLY BE USING ALL OF ONE COMPONENT FOREVER and really fucking with generation chances.
Updated the tips config so it's still full of true information.

### CODE REVIEW

**Comment by Armhulen** [comment]
praise

**Comment by KingPhilipIII** [comment]
I think that will definitely alleviate some of the problem without tearing apart the delicate balance.

**Comment by Anonmare** [comment]
Much better tbh.
Alloy proselytisers are incredibly inefficient and it's much more worthwhile to convert an engine Borg to do it since their proselytiser isn't constrained by alloy.

**Comment by coiax** [comment]
@optimumtact please explain how this isn't feature frozen

**Pull request merged**
