### PR TITLE
Fixes sentience potion lore

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:tada:

### CODE REVIEW

**Comment by coiax** [comment]
KorPhaeron  wants to merge 1 commit into tgstation:master from KorPhaeron:cyborg_tools

**Comment by HankMoodyExperience** [comment]
so they're smarter than liggers

**Comment by optimumtact** [comment]
Yes

**Comment by KorPhaeron** [comment]
Using a sentience potion on lizards should offer control to ghosts, give them a normal name, and eliminate their hissing

**Comment by PKPenguin321** [comment]
do it

**Pull request merged**
