### PR TITLE
Makes beakers craftable

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard
add: You can now craft beakers using a sheet of glass and a welder.
/:cl:

This was a long-needed feature. This limitation prevented grenade building from being even remotely practical.

### CODE REVIEW

**Comment by GunHog** [comment]
Autolathe.

**Comment by Dorsisdwarf** [comment]
Use an autolathe like the rest of the station heathen

**Comment by Tacolizard** [comment]
autolathes (on box) are locked behind a door guarded by cranky glorified greytiders. It makes no sense for beakers to be such a rare item.

**Comment by FantasticFwoosh** [comment]
This is confusing when you have the option to make a bowl out of mushroom shavings on lavaland, but somehow you must weld glass explicitly to make a beaker of a certain shape & capacity and probably blind yourself & waste fuel in the process.

50 unit glass beakers & 50 unit glass cups are literally the same except 1's sprite changes when you pour alcohol into it, the same goes for using a flour bag which is really a re-sprited beaker.

> not to be overtly critical, but beakers are all around you if you recognise the subtle differences.

**Comment by lzimann** [comment]
@Tacolizard so talk with cargo people to prink beakers for you.

**Comment by Jordie0608** [comment]
You can even already craft papercups with cardboard; use an autolathe.

**Pull request closed without merging**
