### PR TITLE
offstation vending is free again

### LINKED ISSUE #48437: Unable to use Charlie Station vendors
## Round ID:
126812

## Reproduction:
Cannot retrieve anything from the kitchen vendor on charlie station as a charlie station spawned player. No account ID is connected to the ID card, and player doesn't appear to start with one.

### LINKED ISSUE #48475: Life bringers cant vend seeds, dont have money or ID card
## Reproduction: Play as a life bringer

The life bringer eco system on lavaland has a seed vendor, but these vendors need both valid ID card and money. As a life bringer you have neither so you cant vend seeds so you cant really do much

Maby add a ID card with money on request until this is fixed?

### LINKED ISSUE #48478: Sentient Ecosystems Lavaland cant buy Items Vendor
Issue reported from  Round ID: 126958 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1464

"No registered ID card!
Please contact your local HoP!"

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request
Adds an offstation check I initially missed.

closes #48437
closes #48475 
closes #48478

## Changelog
:cl:
fix: Offstation vending machines are free again
/:cl:

### CODE REVIEW

**Comment by swindly** [comment]
reopens https://github.com/tgstation/tgstation/issues/41349?

**Comment by cacogen** [comment]
yeah being able to pull vendors to mining, vend their contents, then sell what you don't want on the cargo shuttle means free money
i'd just make it so roundstart vending machines that are off-station set their prices to 0

**Comment by actioninja** [comment]
This uses the same variable as was used to previously fixed that closed issue. This doesn't make it an issue again, it just corrects an oversight.

**Comment by BadSS13Player** [comment]
Closes #48509

**Pull request merged**
