### PR TITLE
Removes stun and item drop from all slips. They will instead knock people down (force crawling) for their duration.

### PR DESCRIPTION
**Pull request by silicons**
image
I originally was going to cut stun/paralyze duration instead but since none of them will now hard stun I think it's fair for them to keep their original duration/power as knockdown.

### CODE REVIEW

**Comment by Arianya** [comment]
Make people slip again if they try to crawl on wet tiles with their move mode set to run.

**Comment by Arianya** [comment]
Make people slip again if they try to crawl on wet tiles with their move mode set to run.

**Comment by HydroFloric** [comment]
So the slippocolypes cluster bang is useless now then? I would suggest maybe keep the item throw in for slips so they can still be used offensively.

**Comment by Therapist1** [comment]
Thumbs down from me, reason being that every time you slip someone as clown, they’ll just grab your peel/PDA for free.

**Comment by Kierany9** [comment]
Being able to act immediately after faceplanting onto the floor because you didn't look where you were going is dumb. No stun disarms were bad, no stun slips are gonna be bad too. Not saying they can't be nerfed (Force crawl for original duration and stun for half sounds pretty good tbh) but still...

**Comment by Hathkar** [comment]
I'm a little unsure about this. I definitely think a test merge is needed to see how it plays out.

**Comment by XDTM** [comment]
I wonder if being knocked down could be sorta like being cuffed, where you can stay that way (crawling slowly, not moving with items in hand) or you can stand still for a bit to get up and running. That would remove customizing slip duration, but it never made much sense in the first place.

**Comment by Durkel** [comment]
It's very much possible to fall and have the wind knocked out of you. I'd like to see anyone hold on to their shit or continue to crawl when this happens.

**Comment by XDTM** [comment]
Yeah but that depends more on how you fall or how heavy you are than on the slipperiness of the surface. The only thing it would affect would be the chance of slipping, if it was an rng-based system.

**Comment by ExcessiveUseOfCobblestone** [comment]
So basically slips are just really terrible slows now?

They should retain their stun component but make it less than it takes to put on cablecuffs. That's really all they ever needed.

**Comment by XDTM** [comment]
Alternatively you could add a system to hold down crawling people by grabbing them (with the same effect of cuffs), so you could keep them down to apply handcuffs or whatever, but you couldn't otherwise move if you don't want them to go free.

This would be a pretty big thing since you could, for example, disarm someone and then hold them on the ground for a kill, so perhaps there could be a chance to resist out of it.

**Comment by anconfuzedrock** [comment]
Oranges is making me sad, earlier he said slips would retain dropping stuff I thought..

**Comment by evsey9** [comment]
@ExcessiveUseOfCobblestone last time I tried to Nerf slips ( soap slips at least ) people became *so* angry

**Comment by YakumoChen** [comment]
Keep lube as a stun or softlock at least

**Comment by MrDoomBringer** [comment]
Syndie soap should still stun

**Comment by ExcessiveUseOfCobblestone** [comment]
Soap is a powerful stealth item, people just prefer to gunz a blazing

**Comment by anconfuzedrock** [comment]
I guess this will make sense later, right now crawling is just “walking but you slow and fit under flaps” But I’m sure that will change.

**Comment by Ziiro** [comment]
Soft falls(Slips that don't stun)
Water, Water vapor, non-syndie soap, banana peel with <X potency
Hard falls(Slips that stun):
Space Lube, syndie soap, Clown PDA, banana peel with >=X potency

**Comment by optimumtact** [comment]
we're gonna try this first, then think about adding some stuns back

**Comment by subject217** [comment]
grey shit apocalypse soon

**Comment by XDTM** [comment]
Just break their arms while they're down

**Comment by kingoftheautism** [comment]
i ded, RIP

**Comment by optimumtact** [comment]
Kevin is simply doing the changes I requested, he has no stake in this either way

**Pull request merged**
