### PR TITLE
Dinnerware Vendor now only accepts IDs with Kitchen access

### PR DESCRIPTION
**Pull request by Iamgoofball**
Get a job, hippie.

Fixes #20610

### CODE REVIEW

**Comment by Ninja137** [comment]
Or you could just make the whetstones craftable.

**Comment by Iamgoofball** [comment]
Or we could not make people able to upgrade the force on every weapon.

**Comment by Ninja137** [comment]
Melee is objectively worse than range, and having a way to sharpen shit makes a fair bit of sense. If you're going to lock it to kitchen IDs only, then at least provide more than two, or let it actually be restocked properly.

**Comment by Iamgoofball** [comment]
Do you really think I don't see through your bullshit? You just want to abuse the whetstone more.

**Comment by TechnoAlchemisto** [comment]
The only downside of this PR is that I can't steal glasses from the kitchen vendor when there is no bartender, so I can make myself a drink. 

However, it's long overdue that the chef has control over their own vending machine and goods. Good PR.

**Comment by PKPenguin321** [comment]
No reason this and the other PR can't both be merged

**Comment by Bawhoppen** [comment]
@Ninja137 I cannot believe you're actually worse than kilkun for balance ideas

**Comment by Cheridan** [comment]
i think the other fix is adequate without making it impossible for people to get bowls and junk.

**Pull request closed without merging**
