### PR TITLE
Clockcult component generation will automatically focus on components needed to activate the Ark

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Clockcult component generation will automatically focus on components needed to activate the Ark if it exists.
/:cl:

If the ark is up, stuff should automatically focus on what needs to be made for it because not doing that can make stuff, uh, weird, and really slow the clockcult down.
And by weird I mean having 8 geis capacitors and still needing 3 of each other type.

### CODE REVIEW

**Comment by octareenroon91** [comment]
I am curious why you are using `.` the way you're using it here.

**Comment by optimumtact** [comment]
. is a list of things to be returned by the proc

**Comment by octareenroon91** [comment]
Until `. = pickweight(.)` makes it a type, I take it. It works, it saves on defining variables, but I'm curious if it also has efficiency implications or if the technique is called something.

**Comment by optimumtact** [comment]
I think . is slightly faster than normal variables but I don't recall the specifics

**Comment by AnturK** [comment]
Freeze

**Comment by RemieRichards** [comment]
```.```'s speed vs ```return```'s is VERY varied, it'll win in some situations, and lose in others, and the difference is very very very minute anyway, so it's purely preference at this point. (plus ```.``` is quicker to type)

**Comment by KorPhaeron** [comment]
Please follow the freeze rules as a maintainer

**Comment by KorPhaeron** [comment]
PRs that violated the freeze have to wait a week longer to be PRd or else people will keep opening their feature PRs during freezes

**Comment by Cyberboss** [comment]
`cogscarab (486) alarms: CEASE COMPONENT USE!!!`

**Comment by Robustin** [comment]
Really should just think about changing the whole system because the current resource mechanic needs about 50 snowflakey changes like this one until its viable.

**Comment by GunHog** [comment]
Remove components, require power?

**Pull request merged**
