### PR TITLE
Reinvigorates the disco inferno

### PR DESCRIPTION
**Pull request by ShizCalev**
Noticed a billion runtimes coming from them. This was due to them setting light_range to non-hex values, which is no bueno when update_lights is expecting it to be a hex value.

Also randomized the range of the lights since they were all static values. (Purple was larger than all the others, red was tiny, ect.)

https://imgur.com/a/UaH1k

### CODE REVIEW

**Comment by DaxDupont** [comment]
I was worried my shuttle was fucked but it's just the dance machine code.

**Comment by ShizCalev** [comment]
It could probably be cleaned up and improved a fair bit more, but this fixes it for the time being.

**Comment by DaxDupont** [comment]
Yeah I only touched a tiny part of it.

**Comment by Robustin** [comment]
Thank you for doing this but you do have a knack for assuming my intentional choices were accidents.

The light ranges were different because certain colors were "stronger" than others in our light code so I had to compensate or else red would dominate the scheme and purple would get eaten. It looks good in your .gif though so maybe its not as much of a problem now (though your gif is running in a pitch black environment, im hoping it doesn't run into the same issues I saw in a well lit one).

**Pull request merged**
