### PR TITLE
Makes noslip floors speed movement up.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Because you can run faster in high traction... right....

:cl:
add: noslip floors make you slightly faster
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
:+1: Now just change the color to go faster red

**Comment by Lumipharon** [comment]
We literally have bluespace tiles for this exact thing.
This just invalidates those, which are somewhat difficult to get, as opposed to high traction which is orderable at cargo.

Also how does high traction make you run faster?

**Comment by GunHog** [comment]
Bluespace tiles? Those exist? How do you get them?

**Comment by tkdrg** [comment]
sepia slimes in xenobio

**Comment by Dorsisdwarf** [comment]
Yeah, tell us so we can rename them something not completely retarded. STOP ADDING BLUESPACE TO THE BEGINNING OF ANYTHING SLIGHTLY BETTER DAMNIT

**Comment by Iamgoofball** [comment]
Yeah @MrStonedOne this already exists in bluespace flooring,

**Comment by KorPhaeron** [comment]
They're named bluespace floors because they come from bluespace slimes duh.

That said the bluespace floor is from a high end slime, a huge pain to put down, and the sprite is an eyesore so I wouldn't mind if they were replaced or reworked.

**Comment by MrStonedOne** [comment]
this only adds a minor speed up compared to bluespace tiles

I see people adding nonslip floors all the time, and i always varedit them to have slowdown = -0.3 (if not -1) so i wanted to add them here...

**Comment by KorPhaeron** [comment]
Doesnt our slowdown system round up/down?

**Comment by MrStonedOne** [comment]
it shouldn't... i've had bagil on 0.8 instead of 1 for run delay and it's still slower then 0...

It might round to the tick, but i don't think so..

**Comment by WJohn** [comment]
Now if only these tiles didn't look absolutely hideous.

They little dotted pattern on it is plenty enough indication that they have higher traction, I guess I'll make grey versions when the time comes.

**Comment by MrStonedOne** [comment]
I actually love the sprites, you can create gold walkways.

**Comment by xxalpha** [comment]
Why does everyone hate the sprites? FCKH8

**Comment by GunHog** [comment]
I like the sprites...MSO likes the sprites.

**Pull request merged**
