### PR TITLE
Puts RND consoles back into RND roundstart

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

After, what, 2 or 3 years? Puts RND consoles back into RND labs roundstart. 

## Why It's Good For The Game

The supposed RND rework that was preceded by moving RND to the bridge / RD's office never came to fruition and was supplanted by expericsci. As such there doesn't really exist a reason to keep them locked away, _especially_ as scientists kinda need them to do expericsi. 

Also Lemon told me "no balls".
image

## Changelog

:cl: Melbert
expansion: RND labs now have RND consoles again. 
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
lets see what happens

**Comment by Cheshify** [comment]
Good PR based on the discussions during the coder meeting

**Comment by derekhearst** [comment]
finally, the days of bugging the rd to sign into the civ console or just building a new one are done

**Comment by Farquaar** [comment]
Good change. The song and dance that came from no roundstart R&D console never created any interesting interactions, in my experience.

**Comment by bluetshirtguy** [comment]
better a cake not baked then one half.

**Comment by zxaber** [comment]
You can't currently launch the science hub app without head of staff access.

If this PR goes through, I've been given the go-ahead to make the science app downloadable and usable by either heads of staff *or* science (and add functionality to support such).

**Comment by moocowswag** [comment]
>it mostly brings backs the randoms breaking in to do research themselves instead of interacting with other players.

Brings back? 99% of the time the rnd console is built in the rnd lab very early in the round, most non research staff either ask on radio or in person and the ones that do break in don`t cause a fuss or anything, they just want their job related tech so they can move on with their lives. And this is coming from the perspective of a scientist that is fed up with people`s crap, I almost never have issues with someone who tries to force their way in to get a tech they need.

**Comment by GuillaumePrata** [comment]
> Or you could just try to avoid merging the pr to your downstream instead of trying to argue against it in an upstream with a playerbase that you don`t know or care to know.

This has nothing to do with Fulp so I don't know why you are trying to bring this up to defend your point, not only do I contribute to TG codewise but I also play on the server enough to know the player mentality.

The science department doesn't have a solid role on the station, they mostly powergame by themselves, sometimes share the loot with others. From my understanding Experisci's goal was to give them something more interesting to interact with the crew (and no, talking with the random that broke in isn't interacting within this goal) as both side work together on experiments to achieve their goals on unlocking tech.

Now there are multiple ways to achieve that, cutting on crew just breaking the windoor, hoping the desk and doing it themselves is a valid point IMO.

And bring back, yes. I played enough on TG to know that people often build a console but what is there roundstart tells us what the maintainers see as scientists' job. If you give them a console roundstart they will go and do research by themselves, when I play science I still ask the RD about research instead of doing it myself because I think that is more engaging to have someone controlling research than 10 people fighting over it.

**Comment by moocowswag** [comment]
> The science department doesn't have a solid role on the station

Probably off topic but thats because science in general is very broad. It can be improvement or innovation in any other field. It could be taking biology (xenobio/genetics) or machines (robotics/circuits/oldnanites) and trying to trying to make something functional or useful out of it. (The thing is xenobio/genetics/robotics already have a useful foundation of provided equipment and your experimentation is just left to seeing what combines well)

Jobs like chemistry and virology and botany also fall under this and while they might not have experimentation in their core gameplay loop us individual players experiment and learn across multiple rounds.


> The science department doesn't have a solid role on the station, they mostly powergame by themselves, sometimes share the loot with others. From my understanding Experisci's goal was to give them something more interesting to interact with the crew

I believe experisci was just another iteration/attempt to give sci in general a more experimental gameplay loop where you try to discover new things. (and it ended up becoming basic fetch quests)

It might not be the ic experimentation/gameplay loop that coders have tried to implement like with experisci (which turned out to just be fetch quests), but it is at least present from a metagame/ooc perspective. Its fun to log back on and experiment with a combination of chemicals or plant genes or whatever the fuck you can make with circuits.


And I believe that is what the science department is, a sandbox full of different tools and elements that players can try to put together to make something useful even if it might be impractical or silly.

**Comment by ilikesaying** [comment]
> From my understanding Experisci's goal was to give them something more interesting to interact with the crew

Seeing a plasmafire in RND because plasma walls were made will always give crew interaction with science, yes

**Comment by GuillaumePrata** [comment]
> Seeing a plasmafire in RND because plasma walls were made will always give crew interaction with science, yes

I'm an atmos main, I live for this moments.

**Comment by bruhlookatthisdood** [comment]
the great man indeed has...
"the balls"

**Comment by SoreYew** [comment]
Make them able to access the tablet program instead of reintegration of old STUPID COMPUTERS.

**Pull request merged**
