### PR TITLE
Gang tools no longer beep.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
It's been causing issues, and asking people not to meta is too much.

### CODE REVIEW

**Comment by yackemflam** [comment]
If this was about me
I was a warden ganghead

**Comment by Cheridan** [comment]
You can change it to 
mob << sound('sound/machines/twobeep.ogg')

so that only the user can hear it

**Comment by Supermichael777** [comment]
stealth antag beeping

**Comment by Shadowlight213** [comment]
Beep

**Comment by KorPhaeron** [comment]
@TechnoAlchemisto 

Are you gonna change it to what Cheridan said?

**Comment by TechnoAlchemisto** [comment]
I wasn't planning on it a sound is unnecessary but if that's what it takes to get it merged I have no qualms with it

**Comment by Cheridan** [comment]
it's fine then i guess

**Pull request merged**
