### PR TITLE
Makes the radio circuit component able to send data

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

See title

## Why It's Good For The Game

More advanced communications between shells has been a long time coming. Though this needs to be moved to ntnet sometime in the future.

## Changelog
:cl:
expansion: Radio circuit components can now send and receive lists.
/:cl:

### CODE REVIEW

**Comment by TheSmallBlue** [comment]
I love this, was planning on making something similar myself. Though I've been wondering, is it possible to send any type of object instead of just strings? I'd love to be able to, say, get the entity from a voice activator component somewhere far away then send it to a bot shell or a server shell for it to be processed since the shell has more space for components

**Comment by PrefabQuasar** [comment]
having made a module that can (painfully) send data using only a sequence of normal radio signals, i cannot recommend this change enough, holy shit, its so painful to do this the hard way

**Comment by moocowswag** [comment]
This is a really massive buff to bcis being used with bluespace launchers because they required you to speak over a private station bounced radio and could be countered by things that disrupt your ability to speak.

Just pointing that out.

**Comment by Watermelon914** [comment]
> This is a really massive buff to bcis being used with bluespace launchers because they required forcing you to speak over a private station bounced radio channel to send coordinate data and could be countered by things that disrupt your ability to speak. (After this you can probably send coords without anyone being able to stop you)
> 
> Just pointing that out, its a really big buff to one of the current main uses for circuits.

This is why if you read the description, you'd see that the aim overall was to bring this over to the ntnet system, which can be taken down by taking down tcomms, completely thwarting your communications.

**Comment by Lauwma** [comment]
This is an enormous buff but I like it. You could send data before by using a binary system but well, it took a lot of time to setup.

**Comment by Mothblocks** [comment]
Blocking unless #60557 falls flat.

**Comment by Mothblocks** [comment]
Going to close this for now for the sake of the tracker but I'll reopen if NTNet doesn't come in.

**Pull request closed without merging**
