### PR TITLE
Mania Motors are overall less effective and only affect people who can see the motor

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Mania Motors are overall less effective and only affect people who can see the motor.
tweak: Mania Motors have slightly more health; 100, from 80.
/:cl:

These were, uh, actually way too strong still.

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
But muh massive brain damage from nowhere.

**Comment by MimicFaux** [comment]
What about people who purposefully inhibit their vision? Like with welding helmets? does the motor have to see the person? Or does the person have to see the motor?

**Comment by ExcessiveUseOfCobblestone** [comment]
@MimicFaux it's who the motor can see

**Comment by KingPhilipIII** [comment]
I remember a time where I terrorized the crew on Meta. Built a mania motor and interdiction lense in that tiny room next to the bridge. Converted AI locked it down and was subtle about it. Hallucinations and lights blowing out, it was glorious.

**Comment by Shadowlight213** [comment]
I recall using it as part of a minefield away mission gimmick I and another admin did. Put it behind indestructible walls so it didn't convert anyone. A way to re-enable that would be nice.

**Comment by ChangelingRain** [comment]
Use fake indestructible windows?

**Pull request merged**
