### PR TITLE
Frog masks moved to contraband

### PR DESCRIPTION
**Pull request by Mercenaryblue**
[Changelogs]: 
:cl: Frogmask McRee
tweak: After a night of REEEEEEEE!! in the REEEEEEEEEE!! channel, Central REEEEEEEEE!!-mand decided to REEEEEE!! the Frog REEEEEEEE!! contREEEEEEEband. LuckilREEEEEEEE!!, a syndREEEEEcate agent restocked them. 
/:cl:

[why]:  They can get very annoying quickly, especially when a station suddenly have 3 frog masks constantly spamming security and/or command channel with REEEEE!! Making them contraband makes them harder to reach, and gives employees a valid reason to destroy them asap.

### CODE REVIEW

**Comment by kevinz000** [comment]
I'm going to wear it as security.

**Comment by SyruseEln** [comment]
theres only one on box, 2 on meta, and 3 on delta.
I look forward to hacking all the machines to get them all. you cant stop the ree.

**Comment by calibraptor** [comment]
People will just hack the machines to get the meme masks, but I do agree a mask that lets you audibly REEE should be locked behind a little hacking.

**Comment by Mercenaryblue** [comment]
Yeah, that's the point. Not impossible, not too easy either.

**Comment by sawrge** [comment]
classic homestuck ref

**Comment by Mercenaryblue** [comment]
No

**Pull request closed without merging**
