### PR TITLE
Changes the DNA console icons to be less awful

### PR DESCRIPTION
**Pull request by Sanator**
## About The Pull Request

Made some better (still placeholder) icons for the DNA Machine/Genetic Sequencer

## Why It's Good For The Game

Makes the DNA Machine UI less jarring to look at 

## Changelog
:cl:
imageadd: Added new, better DNA icons, also animated
/:cl:

### CODE REVIEW

**Comment by Angustmeta** [comment]
Is the blinking pixel intended?

**Comment by Sanator** [comment]
I don't see a blinking pixel. Where do you see it?

**Review by actioninja — APPROVED** [review]

**Comment by PKPenguin321** [comment]
Post pics?

**Comment by Sanator** [comment]
> Post pics?
 You can look at them in "Files Changed -> View File", but I'll post them anyway

dna_discovered
dna_extra
dna_undiscovered

**Comment by ExcessiveUseOfCobblestone** [comment]
Technically not sprites but that's the closest thing I got.

**Pull request merged**
