### PR TITLE
Gold slime extract buff

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
The friendly version will now spawn 3 mobs instead of 1.

### CODE REVIEW

**Comment by WJohn** [comment]
Should put Fixes #12037 in the OP.

**Comment by Incoming5643** [comment]
The reason sentience'd mobs lose their neutral faction is because being neutral means that a statue mob can move freely in front of humans, and becomes utterly horrifying.

**Comment by KorPhaeron** [comment]
@Incoming5643 

Oh. Hm.

**Comment by Incoming5643** [comment]
You can either blacklist statue mobs (which would make people sad) or you can code in a specific check to remove the faction specifically from statues (which would make coders sad) or you can rewrite statues to respect human vision some other way (which isn't a quick fix)

**Comment by KorPhaeron** [comment]
I could give them two factions (gold slime, neutral) and just remove the neutral when they get sentience, would probably be cleanest

**Comment by bgobandit** [comment]
wh-what about actual friendly mobs, i.e. water reaction

**Comment by KorPhaeron** [comment]
@bgobandit 

Literally never seen it used

**Comment by bgobandit** [comment]
I use it all the time ._.

**Comment by KorPhaeron** [comment]
@Incoming5643 

Is there any reason why statues check for faction at all?

Weeping angels getting stuck looking at weeping angels is a thing thats supposed to happen I thought

**Comment by Incoming5643** [comment]
it was never mechanically coded like that. They check for faction so they don't get caught on each other or the wizard or other items the wizard animates.

They aren't weeping angels™

**Pull request merged**
