### PR TITLE
Fixes catpeople not being able to STOP WAGGING THEIR TAIL

### LINKED ISSUE #31702: I CANT STOP WAGGING MY TAIL
1. *wag as catperson
2. *wag to stop
3. Wait I AM STILL WAGGING MY TAIL!!

### PR DESCRIPTION
**Pull request by silicons**
Fixes #31702

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
not a bug

**Comment by Qustinnus** [comment]
you could have just gotten your tail removed :^)

**Comment by Aloraydrel** [comment]
.tailDESTROY kevinz00p

**Comment by kevinz000** [comment]
.pluck aloraydrel

**Pull request merged**
