### PR TITLE
Allows Non-Holy created Holy Water 

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
Currently to acquire Holy Water to make Strange Reagent for your non cloneable species "Plasmaman" you require Holy Water. But to get it requires a Chaplain if they aren't off validhunting or sacrificing monkies to their Pray verb, or hope to God Cargo actually orders your holy materials crate.

🆑 
add: You can now make Holy Water; required for Strange Reagent, with Mercury, Water, and Wine. Finally Plasmaman and others will no longer stay dead forever.
/🆑

### CODE REVIEW

**Comment by Anonmare** [comment]
I know you stole this meme from Oraclestation

**Comment by Armhulen** [comment]
:wheelchair: - Today at 8:55 PM
powergaming gets merged while in tg we can barely add webbing to mining voucher https://github.com/OracleStation/OracleStation/pull/955


:wheelchair: - Today at 8:56 PM
what if i make the eaxcly same pr
but i merge to tg
social experiment


:wheelchair: - Today at 9:00 PM
done https://github.com/tgstation/tgstation/pull/38571


BAD FAITH PR DETECTED

**Comment by Repukan** [comment]
Buy it from cargo

**Comment by Repukan** [comment]
Make Holy Melons

**Comment by improvedname** [comment]
Plasmamans are cloneable though!

**Comment by Therapist1** [comment]
^

**Comment by Therapist1** [comment]
Holy melons are real man

**Comment by YakumoChen** [comment]
>messing with cult balance

But you're not robustin??

**Comment by Grazyn** [comment]
Pointless powercreep

**Comment by fludd12** [comment]
Hooooly meloooons

**Comment by XDTM** [comment]
Make holy melons they even make you immune to magic while they're at it

**Comment by Bawhoppen** [comment]
Bad change and you know it

**Comment by Arianya** [comment]
```
p o w e r c r e e p
o                 o
w                 w
e                 e
r                 r
c                 c
r                 r
e                 e
e                 e
p o w e r c r e e p
```

**Comment by ExcessiveUseOfCobblestone** [comment]
Could you explain your thought process for making a PR? You seem to have a habit of making unwelcomed PRs.

**Comment by GuppyLaxx** [comment]
this shit ain't from oracle it's from paradise, just, fyi

**Pull request closed without merging**
