### PR TITLE
Fix: Blood Deficiency removing more blood than intended

### PR DESCRIPTION
**Pull request by Floofies**
## About The Pull Request
This PR fixes a rare bug in the Blood Deficiency quirk which causes it to drain more blood than intended. The bug only affects high-population servers. Players on high-jitter high-population servers reported that their characters sustained excess damage and suddenly "dropped dead" when using the Blood Deficiency quirk or subclasses of it. Upon investigation I found they had lost more blood than the quirk is supposed to remove. The fix is straightforward, we just have to use the `max` proc.

The calculation Blood Deficiency uses to reduce blood volume is highly vulnerable to scheduling delays, although it appears to be fool-proof at first glance: `carbon_target.blood_volume -= 0.275 * delta_time`. On very high-pop servers, and during times when the processing subsystem may wait to execute `process` for extended periods, the critical `delta_time` variable becomes excessively large. The subsequent blood loss caused by the quirk may continue far below `BLOOD_VOLUME_SAFE` and cause the mob to gain excess damage or instantly die. The bug is not specific to the Blood Deficiency quirk, and affects all quirks which utilize processing and `process(delta_time)` to perform time-based stats changes if they don't use `max`, `min`, or similar. For example, the Brain Tumor quirk is also noticeably affected by highly loaded servers with long wait times.

## Why It's Good For The Game 
This PR fixes a rare issue which causes the Blood Deficiency quirk to drain blood past its programmed minimums, which sometimes kills players much earlier than the quirk was intended to. This PR mostly benefits high-pop servers and big (laggy) downstream repos, and I can't imagine this bug ever impacting a TG server unless it had a large amount of players and CPU load.

## Changelog

:cl:
fix: Fixed a bug causing Blood Deficiency to remove more blood than intended.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
> On very high-pop servers, and during times when the quirk subsystem may wait to execute process for extended periods, the critical delta_time variable becomes excessively large. 

Is this true? It's not true for everything else, I thought `delta_time` for all of those was fixed for this exact reason

**Comment by Floofies** [comment]
@Mothblocks 
> ...What

I'll clarify this a little better: we couldn't reproduce this bug unless the server was overloaded. That's the only instance in which `delta_time` will increase to an unrealistic value.

> Is this true? It's not true for everything else,

I think so! A lot of other functions use `min` and `max` or some other number-clamping scheme, so those functions are immune to this bug. Furthermore, when testing for this bug we couldn't reproduce it on a lag-free server. When there was enough lag during testing (populated server, we'd get around 5 big lag hiccups per round) we found the quirk was draining too much blood or even almost depleting blood, regardless of what we set the minimum to. Reading the code, I can see that `delta_time` doesn't even have to be that big in order for the quirk to over-drain blood, or for Brain Tumor to over-damage brains, and there is currently nothing in the code to stop that from happening.

> I thought `delta_time` for all of those was fixed for this exact reason

Maybe so, but I don't think that's a factor in this case. I think this bug has existed unnoticed for quite some time. The quirk does _look_ fool-proof, I'll give it that. What's important to note is that StonedMC and `delta_time` are not silver-bullets for lag... they help smooth lag out in our calculations, rather, all `delta_time` really does is allow us to make frame-independent stats changes consistently. In other words, If you add more CPU-bound work to StonedMC, it will increase `delta_time` as is the intended behavior.

**Comment by Mothblocks** [comment]
What I mean is as far as I'm aware `delta_time` isn't actually any delta time, it's just subsystem wait * 10, which is fixed.

**Comment by Floofies** [comment]
@Mothblocks Yes, and now you're seeing why this bug was so confusing to find.

It starts out with a default value, and the processing subsystem does indeed just do `thing.process(wait * 0.1)`, but it is not that simple. In addition to and as a result of `next_process` increasing naturally, the wait setting of a subsystem can be changed at any time and directly ties into such scheduling delays.

**Comment by Floofies** [comment]
Er.. yeah, it's not perfect and my explanation isn't it either. I think you're focused too much on that one variable.

If I had to clarify even more: The "processing quirks" (as these are called) co-exist with everything else queued in the processing subsystem's scheduler slot. As in, a lot! Processing is supposed to be executed once every 1 second but that's overshot by a long shot with high CPU usage. As for priority, it's a linked list with shuffling, and little actual re-prioritizing. Only the additions are prioritized, which allows a lot of scheduling information to go stale/become invalid.

Why? Again I'm not exactly sure, but lets take a closer look. The processing subsystem has a priority of `FIRE_PRIORITY_PROCESS`, or 25, which is somewhat low. However it also has a flag `SS_BACKGROUND` which causes it to be skipped often, and then it runs literally randomly:

`timer += world.tick_lag * rand(1, 5)
SS.next_fire = timer`

That's fucking brutal. So I'm not debugging it, I just want to fix the quirk!

**Comment by Mothblocks** [comment]
I don't think it's a mistake to focus so hard on this, my understanding of delta_time suggests this fix is wrong and I want to make sure I'm right

**Comment by Mothblocks** [comment]
Basically if the fix is just the `max`, that's fine, but the talk about delta_time confuses the hell out of me

**Comment by Iamgoofball** [comment]
the tl;dr is our deltatime doesn't work how you'd think deltatime would work and this caused problems on high lag environments

**Comment by Mothblocks** [comment]
@Floofies So is the fix just the max or does delta time hold relevance here?

**Comment by Floofies** [comment]
Hi @Mothblocks the fix consists entirely of the `max`. In regard to the contents of the PR I would say `delta_time` holds relatively little significance. If anything I boiled it down too hard and all that belongs in its own thread, I'm sorry for the confusion I caused.

**Comment by MrStonedOne** [comment]
> Why? Again I'm not exactly sure, but lets take a closer look. The processing subsystem has a priority of `FIRE_PRIORITY_PROCESS`, or 25, which is somewhat low. However it also has a flag `SS_BACKGROUND` which causes it to be skipped often and execute randomly:
> 
> `timer += world.tick_lag * rand(1, 5)` `SS.next_fire = timer`
> 
> That's f***ing brutal and it doesn't look like a correct way to schedule the processing subsystem in particular. So I'm not debugging it, I just want to fix the quirk!

you are misreading that code. (this is why you shouldn't post code without linking to it on github so it can be seen context. as not everybody knows the mc as well as i knew to the point they not recognized the short code snippet enough to know you misread it, but also which version of that same code pattern you linked)

That code only runs at round start or if code stops and restarts a subsystem, it even applies to all subsystems. (actually, the version of the code you posted only happens on the first tick of the mc (loop() is only called once and never returns unless the mc errors out), and the `if ticker|background = ticker` check actually _excludes_ background subsystems, it only applies to non-background ticker subsystems.)

It's designed so that all say, 20ds wait subsystems that start at the same tick (like round start), don't all fire on the same tick with each other for the rest of the round. (if out of the 40 ticks in a 20ds cycle, all 20ds subsystems fired on the same tick because they all started at the same time, then the other 39 ticks would be used inefficiently, so it produces a random tick offset once)

Background however does mean that the mc won't reserve time in the tick for it, it just gets what non background subsystems don't use, and that remainder gets split between all background subsystems that need to fire that tick.

You can set its priority to anything higher then ssatmos to ensure it runs before ssatmos. priority is a weight used when splitting up the remaining game tick, so setting it to 10% higher then ssatmos should mean it gets 10% more of a time allocation too compared to atmos.

***

I checked that delta_time is getting set correctly based off of wait and that nothing is coded to edit ssquirks's wait.

This fixes **A** bug, but i suspect it's not fixing the bug you had reports of.

**Review by MrsTonedOne — APPROVED** [review]

**Comment by Mothblocks** [comment]
@MrStonedOne Thanks for looking into it

**Comment by Floofies** [comment]
@MrStonedOne Ah, so I wasn't even in the right spot when I was looking at that `rand`, that is embarrassing. Thank you for the advice as well, I am certainly in need of it if the mess that is this PR indicates anything. Coincidentally, I had also checked the code extensively before this PR, to see if anything else could change `wait`, and I didn't find anything either. Even with my level of comprehension of the code, I am basically clueless as to why any of those variables would change.

**Pull request merged**
