### PR TITLE
inb4 powercrepe

### LINKED ISSUE #20667: There are food recipes that dont use food subtype of crafting recipes
Food have a special recipe subtype made by me on phils request to accomodate his food overhaul
Without using it classic food system doesnt work like intended
Someone however added food recipes to the basic recipe datums, i can not guarantee it will work in any way
Someone please fix it

### PR DESCRIPTION
**Pull request by Niknakflak**
Adds the powercrepe

image
Nienhaus's Sprite (as usual, big thanks to him of course, where would I be without his sprites?)

A weapon of great force and pancake of deliciousness that requires
Flat dough, milk, a super cell, and the officer saber to make.  

Packs quite a punch.

Fixes #20667

### CODE REVIEW

**Comment by Durkel** [comment]
Nice meme.

**Comment by PKPenguin321** [comment]
Is it actually possible to attack people with this or will you just feed it to them

Funny joke btw

**Comment by ChangelingRain** [comment]
this crepe is too weak you need to buff it

**Comment by Niknakflak** [comment]
You can attack people with it yea, it doesn't dismember anymore but has no in-hand sprite.  Just gotta be on harm intent.  Willing to just drop that functionality and change the recipe if this PR won't get merged otherwise.

**Comment by Iamgoofball** [comment]
fuck you i want a crepe now

**Comment by Kraseo** [comment]
It's trash son.

**Review by Razharas — CHANGES_REQUESTED** [review]
Recipes that result in food should use food subtype of crafting recipes
There is a whole little system behind it to make it all work

**Comment by TechnoAlchemisto** [comment]
even for a meme food, should be stronger put some omnizine or stimulant in this bitch

**Comment by optimumtact** [comment]
>People already arguing for powercrepe buffs

lizard tries to wake up but his world is crashing down in flames and he gives in to the darkness

**Comment by Niknakflak** [comment]
>even for a meme food, should be stronger put some omnizine or stimulant in this bitch

Yea I'm not doing this.

**Review by Razharas — APPROVED** [review]
Now thats good

**Comment by XDTM** [comment]
buff this monthly

**Comment by ChangelingRain** [comment]
anyway a more powerful crepe would use chocolate this crepe is too weak

**Comment by AdamElTablawy** [comment]
add 1 vitamin monthly to the powercrepe.

**Comment by Kromgar** [comment]
You shouldn't need to cook a powercrepe

because it's rare

**Comment by phil235** [comment]
mixing a fix with a feature. :-1:

**Comment by Iamgoofball** [comment]
@phil235 pot meets kettle

**Comment by Niknakflak** [comment]
Raz made me do that phil, blame him.

**Pull request merged**
