### PR TITLE
Improves the debug hardsuit.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR improves the debug hardsuit by removing the slowdown from its EVA mode, giving it an infinite power cell and giving it 100% armor to everything.

It also gives it a name of Jannie Hardsuit and improves the syndicate hardsuit code by removing a useless hardcoded variable.

## Why It's Good For The Game

Now i dont have to dangle around with hardsuit modes when testing things.

## Changelog
:cl:
tweak: The Debug Hardsuit now has no slowdown and full armor.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
added a very high strip delay and the flag which makes shove knockdowns not a thing

no more plapatin moments, sorry

**Comment by ATH1909** [comment]
christmas present buff smh my head my head

**Comment by kriskog** [comment]
I understand where you are coming from, but keep in mind that the debug hardsuit should be useful for testing hardsuit/EVA related stuff too. Bypassing all the hardsuit/EVA mechanics makes it useless for testing a lot of stuff, and might cause issues where people who are unaware of the differences make assumptions that their code is working or an issue cannot be reproduced. It is an outfit meant for testing code, not convenience in spawning yourself in to play with admin tools.
That's also the reason I shut off the radiation warning instead of giving it 100% radiation armor and didn't make these changes in past iterations of the debug outfit.

If you want to make an admin outfit, make an admin outfit instead of perverting the debug outfit.

**Comment by Jared-Fogle** [comment]
+1 for @kriskog--I'd rather just see an admin outfit, I'm a bit surprised if one doesn't exist already.

**Pull request closed without merging**
