### PR TITLE
Fixes containment field CanPass

### LINKED ISSUE #30468: [Downstream] rapidly examining an object while ghosted can randomly throw the object even anchored
So we discovered this on Citadel tonight whilst on Pubby with a properly set Tesla engine. 

In a report to me, some chucklefuck decided to spam shift click a mini tesla ball, and it managed to delete the ball and a containment field section, thereby loosing the Tesla into the station.

They apparantly also quickly tested it offline and were able to reproduce the bug.

When I tested it, I couldn't click enough myself on the Tesla, but while doing it to a field generator, it did suddenly act as if thrown, sparking against its own containment field, but not breaking it or the field.

@kevinz000 was mentioned for a similar case tested on live TG as well, though a quick search didn't bring up any issue with this sort of title already reported.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #30468 

This whole file makes me want to rip my eyes out but i don't have the time to refactor it right now.

### CODE REVIEW

**Comment by RemieRichards** [comment]
why is this the fix for #30468 ?

**Comment by AnturK** [comment]
Examine checked for Adjacent that calls CrossClick which calls CanPass with itself that throws the atom aka field throwing itself on examine.

**Comment by RemieRichards** [comment]
🤦‍♀️

**Comment by Poojawa** [comment]
Wew

I'm glad it was a relatively easy find/fix, though.

**Review by Cyberboss — APPROVED** [review]
Yesus

**Comment by Supermichael777** [comment]
AH

HA

HA

HA
HA
fuck

**Comment by optimumtact** [comment]
Who did it

**Comment by AnturK** [comment]
It's 4y+ old code.

**Pull request merged**
