### PR TITLE
Updates the readme.md of the repo by changing the links to have https://

### PR DESCRIPTION
**Pull request by praisenarsie**
I like security.

### CODE REVIEW

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by praisenarsie** [comment]
I have done so.

**Comment by Cyberboss** [comment]
>Not using HTTPS Everywhere

**Comment by Supermichael777** [comment]
Http should be globally depreciated. literally 80's tech

**Comment by DaxDupont** [comment]
Tell that to bgp @Supermichael777

**Comment by MrStonedOne** [comment]
byond's https support is hacky at best, and i think they only serve https certs from secure.byond.com but all links hard code byond's domain as byond.com with a hardcoded http protocol so changing those to https is futile

**Comment by optimumtact** [comment]
@praisenarsie there are no https links for byond

**Comment by lzimann** [comment]
There is `https://secure.byond.com` for byond.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
