### PR TITLE
Drone Shell Cargo Crate

### PR DESCRIPTION
**Pull request by BananaCreamPie**
droneshellcrate

Added a Drone Shell Crate to the cargo supply request console. Its a secure robotics crate with 6 drone shells. Reasonably cost and fast way to get drone shells if research is behind or no roboticist.

### CODE REVIEW

**Comment by Miauw62** [comment]
i dont really see the point of this tbh

**Comment by Dorsisdwarf** [comment]
To explain what Miauw said:
#9789 adds a drone fabricator which poops out shells when you add metal/glass

**Comment by Miauw62** [comment]
didnt really mean that at all actually but vov

**Comment by Jalleo** [comment]
I would rather the cost be slightly higher than 20 it is kinda low in my opinion.
Although this does negate robotics making them which may be iffy time will tell.

**Comment by Cheridan** [comment]
Yeah lets just have a bot and a cyborg crate and a mech crate and we can remove robotics entirely

:hankey:

**Pull request closed without merging**
