### PR TITLE
Fixes Cortex Folding Surgery

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

It was using the same step as cortex imprint.

## Changelog
:cl: XDTM
fix: Fixed Cortex Folding surgery having the same effect as Cortex Imprint.
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
Why are there random GPS changes?

**Comment by XDTM** [comment]
wait what, something must've gone wrong with git

**Comment by ExcessiveUseOfCobblestone** [comment]
git machine br....

**Comment by Pumpkinoe** [comment]
speedmerge plox

**Pull request merged**
