### PR TITLE
Adds round id linking action

### PR DESCRIPTION
**Pull request by AnturK**
Simple action that turns [Round ID] : xxxx into links to scrubby.

### CODE REVIEW

**Comment by nfreader** [comment]
> scrubby
oof.

**Comment by kriskog** [comment]
Could append links to both statbus and scrubby? I tend to use statbus and parsed/raw logs more personally.

**Comment by AnturK** [comment]
I guess i could do both, i didn't want to change the actual text just linkify though.

**Comment by kriskog** [comment]
Since scrubby links to statbus, scrubby it is :man_shrugging:

**Pull request merged**
