### PR TITLE
Rearranges the antagonist panel: now with 150 more hours of testing

### PR DESCRIPTION
**Pull request by ghost**
I'm not sure why this happened, but the changes are beneficial enough that I want to debug it and figure out what caused the problems, so I'm gonna work on them and find out the issue.

@Cyberboss What were the circumstances of the crash? i.e. who was it used on, what role, mob...?

### CODE REVIEW

**Comment by Cyberboss** [comment]
The main issue really is assuming `current` exists. If you just add sanity checks when you use it, it should be fine. Error was on a ghost mob who had his body destroyed I think.

**Comment by Xhuis** [comment]
The only reason that that should be happening is if the mind is somehow deleted, meaning that my PR didn't actually break that and whatever happened would have also caused issues with the old version. Nonetheless, let me put some sanity check code in, then it should be completely fine.

**Review by Cyberboss — APPROVED** [review]

**Comment by Xhuis** [comment]
Now nobody will notice that I snuck in my crash! FEHEHEHEH!

**Comment by AnturK** [comment]
Uh. Isn't a ghost completely valid target for a traitor panel. Why would it stop the whole thing from working.

**Comment by Xhuis** [comment]
It shouldn't, and it doesn't in testing, so I have no idea.

**Pull request merged**
