### PR TITLE
Polishes the glass tables

### PR DESCRIPTION
**Pull request by Expletive**
:cl:
imageadd: Glass tables are shinier
/:cl:

I used the abductor tables as a template and made the glass tables shinier.
shinytableingame

### CODE REVIEW

**Comment by optimumtact** [comment]
too shiny, abort

**Comment by ShizCalev** [comment]
no laser engraved nanotrasen symbol
3/10

**Comment by Bawhoppen** [comment]
Add an r-glass variant that isn't shiny!

**Comment by xxalpha** [comment]
Those have to be slippery.

**Pull request merged**
