### PR TITLE
Adds admin notice and game log entry to the grief (lava) staff

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by Supermichael777** [comment]
seems kind of spammy. If its getting that out of hand it might be considered making it a limited use wand to tone down the total grief.

**Comment by coiax** [comment]
Might I suggest instead of a message on use, make a message when it is picked up or dropped. Lava staves used by traitors are used a LOT.

**Comment by optimumtact** [comment]
This was by request

**Comment by lzimann** [comment]
this is going to be a hell of spam

**Comment by Saegrimr** [comment]
Note that we already get a notice every time some shitass with a spray bottle sprays lube, and that's considerably less deadly.

This really wouldn't be any more spammy than that.

**Comment by coiax** [comment]
Spray bottles have a limited capacity, lava staves do not. Could we consider just informing admins when someone uses a lavastaff for the first time, and store who "made" the lavaturf in the secret admin only vars on the lavaturf somewhere?

**Comment by anconfuzedrock** [comment]
its 10 seconds in between shots on the lava staff

**Pull request merged**
