### PR TITLE
[metastation] changes firing range into the experimentor/bepis room and slight changes to genetics

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
tweak: sci firing range is now experimentor/bepis room
tweak: genetic room has been remodeled
fix: disposals mailing now sends to genetics
/:cl:

new experimentor lab:
has blast doors on the doors
has the experimentor with rnd console

genetics: 
added a cool monkey pen instead of weird roller bed corridor
added shower for monkey cubes
added functional delivery system to there (it didnt have sorting pipe)
added mutadone pill bottle
removed 8 tile long glass table
removed random rad locker
removed random dupe stuff ( gloves, spare radios)
removed "decorative" hazard lines around the whole room

sci:
changed disposals pipes around to actually work

i m not gonna edit the giant morgue because there is the psych pr that may use that place for psych room

Image

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
hmmm not sure why it merge conflicts, its a fresh master

**Comment by trollbreeder** [comment]
Make the experimentor chamber's floor reinforced please.

**Comment by GunHog** [comment]
> Make the experimentor chamber's floor reinforced please.

Yes, proper containment is a must, because that thing can explode, shoot fireballs, release acid, etc. Relics (aka "strange objects") are usually tested here as well, which can spawn bees, bears (petspray relic), and of course, explode. That is why the E.X.P.E.R.I-MENTOR was kept in heavy containment on most maps.

**Comment by Tlaltecuhtli** [comment]
thats why the room has blast doors so you run out and seal whatever got spawned by the strange object

**Comment by GunHog** [comment]
My bad, I did not notice the buttons by the door.

**Comment by RaveRadbury** [comment]
Isn't the firing range supposed to act as a kind of holdout room where you can lethally fire the lasers at people who enter into it? It would be a shame to lose such a space.

**Comment by GunHog** [comment]
> Isn't the firing range supposed to act as a kind of holdout room where you can lethally fire the lasers at people who enter into it? It would be a shame to lose such a space.

Those were just practice lasers. Back in the Golden Age, I used the range to perfect the reliability of the advanced energy gun (back when reliability was a thing), which could then be safely handed off to the Security department. It was also a safe place to use the ion carbine to break open secure crates. 

Since Sci cannot print weapons any more, there is no reason for the range to exist in Science. It is just a place for a scientist to quietly do antag things now.

**Comment by MCterra10** [comment]
Thankyou. I was getting ahelps from people going "REE WHERE EXPERIMENTER"

**Comment by actioninja** [comment]
conflict

**Pull request closed without merging**
