### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by spessman-007**
## About The Pull Request

Just removed some unused files

## Why It's Good For The Game

Less confusion.

## Changelog
:cl:NewSta
del: Removed unused files
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
the actual sprites in this pr should probably be moved to the sprite repo so they arent lost

**Comment by Qustinnus** [comment]
(particularly the mob and jungleplanet sprites, not as much the duplicate sprites like the one for the orbital cannon)

**Comment by spessman-007** [comment]
Could you please link to the sprite repo?

**Comment by Qustinnus** [comment]
https://github.com/tgstation/SS13-sprites

**Comment by RaveRadbury** [comment]
I suppose this might be part of the confusion, but, you're removing mouse in-hands? That's a thing that you can do.

**Comment by spessman-007** [comment]
Yes, as I do not see the file being used anywhere in the code.

**Comment by Neo1w** [comment]
you are deleting the taskbar window /tg/ icon

**Comment by spessman-007** [comment]
The taskbar one is tg_32.png
ss13_32 and ss13_64 are not used anywhere in the code.

**Comment by actioninja** [comment]
Conflict

**Comment by spessman-007** [comment]
Conflict? Not anymore.

**Pull request merged**
