### PR TITLE
Metabottles

### PR DESCRIPTION
**Pull request by cedarbridge**
:cl: Cedarbridge
add: Added two boxes of pill bottles to Metastation Chemistry.
/:cl:

Added two to the chemistry lab locker so MDs and EMTs can carry more than a handful of individual pills with them in their belts and without having to empty the pill bottles that spawn pre-filled.

### CODE REVIEW

**Comment by jughu** [comment]
I think having the chemists the pill bottles enough

**Comment by SgtxRootbeer** [comment]
try again, jughu

**Comment by Iamgoofball** [comment]
>I think having the chemists the pill bottles enough

do we need to contact an EMT

**Comment by jughu** [comment]
You can carry patches in pill bottles this surely womt end up in medkits being emptied

**Comment by jughu** [comment]
@sgtxrootbeer if all pill bottles should be orderable at caro probaly with some syringes and empty bottles

**Comment by cedarbridge** [comment]
Edited the description.  Does what it says on the tin.  There were no empty pill bottles in the chemistry lab.  Now there are two boxes.

**Comment by jughu** [comment]
Not even in the chemistry locker the medicine one?

**Comment by jughu** [comment]
`/obj/structure/closet/secure_closet/chemical
	name = "chemical closet"
	desc = "Store dangerous chemicals in here."
	icon_door = "chemical"

/obj/structure/closet/secure_closet/chemical/New()
	..()
	new /obj/item/weapon/storage/box/pillbottles(src)
	new /obj/item/weapon/storage/box/pillbottles(src)`

**Comment by cedarbridge** [comment]
I'm seeing them now but they weren't visible on the editor for some reason until I added them.  Did I get rused?

**Comment by cedarbridge** [comment]
Looked over things again.  Apparently these already exist and I just didn't see them for some reason.  Closing.

**Pull request closed without merging**
