### PR TITLE
Revised CMO hardsuit sprite

### PR DESCRIPTION
**Pull request by Haevacht**
Only changes the sprite. It's still bad but not abhorrent.

Conforms to WJ's pallette, the inhands arent off a pixel, the right colour cross in on all of them, some shading improvements.
Changes are mostly minor, it's only slightly less terrible.

New ones:

### CODE REVIEW

**Comment by kevinz000** [comment]
🏷 needs pictures

**Comment by kevinz000** [comment]
:3c

**Comment by Grazyn** [comment]
The palette is a joke since we have that shitty VG lightning overalys

**Comment by Haevacht** [comment]
Even so, it's a significantly less abhorrent sprite.

Who added it nayway seriously the inhands have been off by a pixel for YEARS.

**Comment by WJohn** [comment]
Already a big improvement, but not hard to do given how incredibly bright and ugly our current one is.

**Comment by lzimann** [comment]
conflicts

**Comment by WJohn** [comment]
I'll be adding these changes in my own PR in a minute, as haevacht has asked, so this PR will be obsolete.

**Pull request closed without merging**
