### PR TITLE
Remove the chemistry README (and "DO NOT PORT LIST") that we are not enforcing

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
This is no longer relevant and we are not enforcing it, just like how Liquid Electricity was already in the game and we do not care about ants.

### CODE REVIEW

**Review by Kylerace — APPROVED** [review]

**Comment by Mothblocks** [comment]
anturk wants me to remove the whole thing and i agree

**Review by AnturK — APPROVED** [review]

**Review by Timberpoes — APPROVED** [review]

**Review by EOBGames — APPROVED** [review]
I'm helping!

**Comment by Iamgoofball** [comment]
liquid electricity != goon liquid electricity, they just share a name and not any mechanics or design goals or overarching gameplay design

**Comment by Iamgoofball** [comment]
how many times do i have to say it before you understand

**Comment by LemonInTheDark** [comment]
You think the rest of the documentation is far enough out of date that we can nuke it?

**Review by LemonInTheDark — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
> 
> 
> liquid electricity != goon liquid electricity, they just share a name and not any mechanics or design goals or overarching gameplay design

He's right you know

**Review by coiax — APPROVED** [review]

**Comment by Mothblocks** [comment]
image

**Review by 81Denton — APPROVED** [review]

**Pull request merged**
