### PR TITLE
Adds additional equipment for Silverscales.

### PR DESCRIPTION
**Pull request by Toastgoats**
## About The Pull Request

This PR adds a few notable changes to the Silverscale pirates:

- Replaces the old nanotrasen branded hardsuit with the designer EVA suit, an armored hardsuit equivalent in protection to that of the standard pirates. 
silverscale

- Silverscales all start with satchels

- The airlocks on the shuttle can now be locked from the inside

- The shuttle now has a robot butler (medibot) named Mortimer, along with a burn kit.

- Increased the amount of C4 on the shuttle to 3, and added a 1.30 damage modifier paywalled laser gun to justify having the recharger, the silverscales will need to supply the card themselves

- Adds explosive implants to the Silverscales' outfit. They're greedy lizards, did you think they'd let their gear fall into the hands of the poors so easily?

- The mosins now get phasic rounds to offset the disadvantages of low DPS compared to lasers.

## Why It's Good For The Game

As it stands, it can be argued that the Silverscales are the weakest pirate faction, On paper, they sound as though they would be well-equipped elites, but are left with clunky, unarmored space suits, a bright dead-giveaway glow, and single shot guns that leave them extremely vulnerable to being rushed and stunned. As such, they've become somewhat of a joke amongst players for the past few years.

This pr doesn't necessarily aim to negate their weakness, but I'd like to give them more of a safety net that puts them on equal to slightly better footing with standard pirates in terms of their access to armor, healing, and options.

The addition of the explosive implant also serves to reinforce their theming of being rich, evil lizards, but is mostly meant to make them more entertaining.
## Changelog
:cl:
add: Added the designer EVA suit, a unique pirate hardsuit for Silverscales.
balance: Increased the equipment available to Silverscales
image: Sprites for the designer EVA suit
/:cl:

### CODE REVIEW

**Comment by Profakos** [comment]
I love the space suits, and thebpaywalled gun is very funny. 

Although, i think silverscales are pierce immune for some reason. Can the medibot heal through that? I have a sad memory of  a round where i was badly burned and the regenerative threads did not work on me, so was forcefed tomato juice without much success.

**Comment by uaioy** [comment]
we're so silverscaleback

**Comment by dalmationer** [comment]
Might I also suggest adding some medicine patches. At present, they have medkits on their ship that they can't actually use, because they have thick skin, so they're syringe immune. I've got a funny memory of having to use the drink dispenser aboard the silverscale ship to slowly heal an injured pirate back to life because the sutures didn't work.

**Comment by dalmationer** [comment]
> I love the space suits, and thebpaywalled gun is very funny.
> 
> Although, i think silverscales are pierce immune for some reason. Can the medibot heal through that? I have a sad memory of a round where i was badly burned and the regenerative threads did not work on me, so was forcefed tomato juice without much success.

oh same hat lol

**Comment by Loafin34** [comment]
it's gonna be fucking IMPOSSIBLE to get the obrez moderna now... also give silverscales phasic .310 strilka, it's weird that they get the same ammunition as an illegal black market russian warehouse crate. phasic rounds grant them a new ability to wallbang, which combined with their scopes should be decent enough to qualify as hunting big game.

**Comment by Toastgoats** [comment]
> it's gonna be fucking IMPOSSIBLE to get the obrez moderna now... also give silverscales phasic .310 strilka, it's weird that they get the same ammunition as an illegal black market russian warehouse crate. phasic rounds grant them a new ability to wallbang, which combined with their scopes should be decent enough to qualify as hunting big game.

Phasic strika? I don't remember seeing that in strongdmm, where is that?

**Pull request merged**
