### PR TITLE
Fixes a bug where shuttles would not function

### PR DESCRIPTION
**Pull request by coiax**
Okay, so @Cyberboss walked me through this, I've tested it, and it fixes
shuttles working, it sets the master controller runlevel to 3, like it's
supposed to?

I don't really know that much about how this actually works internally.
But it does fix the bug.

@MrStonedOne

### CODE REVIEW

**Comment by MrStonedOne** [comment]
You should explain how this is related to shuttles.

I can't tell you if this fixes the bug if you don't explain the logic on how you decided that this fixes the bug

**Comment by Cyberboss** [comment]
NOW I can reply. Runlevel in the MC was being set to the bitflag version,
but it requires the index version to access the right SS list. Throwing it
through a log gets the right version.

**Comment by MrStonedOne** [comment]
@tgstation/commit-access this fixes a bug that breaks the entire MC merge please

**Comment by Iamgoofball** [comment]
does this fix custom shuttles too?

**Pull request merged**
