### PR TITLE
Changelings are now unable to revive while on fire

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Changelings are now unable to revive while on fire.
/:cl:

Why: Changelings often smash the gibber and crematorium right away and then the crew is stuck dealing with a whole team of monsters that are constantly unstunning, healing, coming back to life on a 40 second timer with very few reliable ways to restrain them temporarily never mind eliminating them for good.

This seemed like a lore friendly way to give people a backup option for delaying a changelings respawn without completely nullifying their ability to do so (fire is gonna go out eventually, unless maintained)

I'm not 100% sold on this so arguments as to why this is awful are welcome

### CODE REVIEW

**Comment by chaoko99** [comment]
There's a world of difference between clothes on fire, and literally rolling around in liquid plasma. 👎

**Comment by KorPhaeron** [comment]
@chaoko99 there is yeah, which is why the clothing fire will go out within seconds and you'll be free to revive

**Comment by Xhuis** [comment]
I think there's a threshold for where icons make it clear that you're *really* on fire and not just a single bit of flame; if it seems strange to you, that might be a nice compromise, since it makes a lot more sense then a small patch of fire on someone's arm preventing them from reviving at all

**Comment by ChangelingRain** [comment]
Makes lava, and the lava staff, a source of mostly-permanent ling removal.

**Comment by kevinz000** [comment]
use shuttles or wall blocking

**Comment by kevinz000** [comment]
also 8-16 sheets of metal and a canister of n2o they might as well ghost tbh.

**Comment by Armhulen** [comment]
"port horror form!!"

**Comment by KorPhaeron** [comment]
hi frog!

**Comment by FantasticFwoosh** [comment]
Pity, i would have liked to have seen this go through, its both easy to implement from both perspectives of the changeling and the crew (crew spashes beaker or smashes bottle & ignites) and is a guranteed way to starve off the common complaint that changelings just endlessly pop up and make it a battle of resources & attrition.

@KorPhaeron a alternative suggestion could be to have fire damage affect & lower the changelings internal chemicals count so torching a downed ling stops them rising, then have lings go into automatic statis shock for temporal invunerability when they reach 0 chemicals so they can plea for help from their ling team-mates to offer them a share of their own chemicals or a sip of the changeling sting.

- A tentative alliance, will the other ling eat you or share just enough of its energy (special ling sting to share/deposit their chemicals into containers & people with certain effects) to let you regenerate & move to safety?

- With you unable to regenerate your chemicals whilst in statis shock mode, the crew might attempt to scoop out your brains & borg you, space you or otherwise dispose of you, being stranded in space with 0 chems is a viable option as you endlessly float the stars. You will appear dead to rudimentary tests like zombie powder, but can be confirmed using a mass-spectrometer for a toxin in the lings blood whilst in shock.

- On the other hand the ling can never die until its actually destroyed, with a emergency saving throw of dumping all your remaining chems into forcing a automatic regular statis in the case of being killed to determine how fast you regenerate.

**Pull request closed without merging**
