### PR TITLE
Time to use this broken glass on Cyberboss!

### LINKED ISSUE #25832: Welding shards into glass is broken
Welding shards doesn't produce glass sheets like it did previously.  Welding still works on ores and similar items.

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
!!!

fixes #25832

### CODE REVIEW

**Comment by optimumtact** [comment]
. = ..()

**Comment by Jalleo** [comment]
Does this fix welding to glass sheets?

**Comment by ExcessiveUseOfCobblestone** [comment]
probably

**Comment by Cyberboss** [comment]
Yes

**Comment by Cyberboss** [comment]
#25832

**Pull request merged**
