### PR TITLE
Revert "Turf decals + path update helper"

### PR DESCRIPTION
**Pull request by lzimann**
Reverts tgstation/tgstation#22887

Some pics by @ChangelingRain

### CODE REVIEW

**Comment by Cyberboss** [comment]
Fucking wew

**Comment by Cheridan** [comment]
Well it looks like it MOSTLY works, can we not just fix the bugs instead of reverting 100+ files?

**Comment by Bill-Luxe** [comment]
Lulz

**Comment by AnturK** [comment]
Hmm, weird. Must have made a typo somewhere in update file

**Pull request merged**
