### PR TITLE
Obliterates item color

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request
untested

Completely removes item_color and the clusterfuck of bad programming it caused.
Unfortunately the washing machine was a casualty of this, because it relied on item_color existing, but the washing machine was some really godawful messy code anyways and I didn't feel like heavily refactoring something that I've seen used maybe three times.

In places where item_color was used for entirely unique purposes it was split off and renamed to a new var on that typepath only, or refactored so it wasn't needed

In places where item_color was used as a dye color, it was just removed

In places where item_color was used as the worn overlay it was replaced with a new var named "clothing_overlay_state"

A new var named "clothing_overlay_icon" was added to allow custom overrides just for the clothing icon, the old one with a confusing name was replaced with this one.

Also refactors human and mob overlay code a good amount to properly prioritize having the different state vars set as well as be able to have custom icons for the mob overlay.

Moved some mob overlay files relating to clothing to their own directory as well for organization purposes.

## Why It's Good For The Game

It's been 4 years since the "this should be deprecated soonish" comment was added, and this var is a shitpile of confusion if you just trace the usage of it.

## Changelog
:cl:
del: removed the washing machine for technical reasons
refactor: refactored clothing overlay code
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
oh god dmi conflicts

**Comment by Hyacinth-OR** [comment]
recoloring gloves with the washing machine is used far more often than you'd think

**Comment by Farquaar** [comment]
Didn't really make much sense to have laundry rooms when people could rinse the stains out of their gore-soaked clothing in a sink. I mean, I'd be down for most clothes being only washable in machines. But the code would need to be fixed for that.

**Comment by carshalash** [comment]
No more fake insuls to torture the greytide?

**Comment by PKPenguin321** [comment]
Washing machine code was absolutely terrible but yeah it shouldn't be removed

**Comment by actioninja** [comment]
I would prefer to see it stay but it's seldom used except for a couple of very specific things that could be brought back in other ways.
There has been some precedent in the past for removing features for code quality reasons, and I thought the washing machine was a sacrifice that could be made here considering how fucking bad the code was.

**Comment by wesoda25** [comment]
Bro I want washing machine stuff to stay, but fuck spray can shit (and eating crayons). I’m sick and tired of seeing the same players do that shit.

**Comment by CRITAWAKETS** [comment]
maybe add a replacement instead of just removing it like a lazy person

**Comment by actioninja** [comment]
why don't you recode it from scratch then.

**Comment by Krysonism** [comment]
How will I prevent shitsec from robbing my insuls now?

**Comment by nemvar** [comment]
Don't worry, just code a new washing machine without the shitcode, looks simple enough.

**Comment by Difrit** [comment]
This means I can't put dogs in the washing machine, bad pr pls reject

**Comment by SkeletalElite** [comment]
I'm completely against the removal of washing machines, I never don't recolor insuls to black so that people don't know I have insuls.

**Comment by Akrilla** [comment]
removing features because you don't want to refactor/fix the code doesn't feel very fair.

**Comment by Borisvanmemes** [comment]
Eight out of ten rounds i end up using a washing machine to recolour gloves

**Comment by ExcessiveUseOfCobblestone** [comment]
Covering your insuls as normal black gloves so people won't try to steal them will be a very much missed usecase :(

**Comment by TerraGS** [comment]
If you are not interested in re-coding washing machines yourself then at least communicate this idea to someone who might rather than deciding it has to be removed. I understand relying on others is a difficult ask but sometimes it is necessary to get the best results.

**Comment by ExcessiveUseOfCobblestone** [comment]
This is a pretty widespread way of saying "Fix or remove" tbf.

**Comment by FloranOtten** [comment]
Don't remove washing machines. Engi gang cannot go a single brig sentence without losing their insuls.

**Comment by TerraGS** [comment]
> 
> 
> This is a pretty widespread way of saying "Fix or remove" tbf.

Actually, it's a widespread way of me saying "I'd be willing to help in this regard, if you'd be willing to make the request."

**Comment by ike709** [comment]
Don't remove washing machines. I need my stealth insuls. Also it's used to gib Ian.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Actually, it's a widespread way of me saying "I'd be willing to help in this regard, if you'd be willing to make the request."

The PR acts as both the request and proposes _a_ solution should no one take on the request. I'm not sure what you're getting at here like you can still fix it right now and have your PR close this one...

**Comment by Mickyan** [comment]
it seems unnecessary to remove washing machines altogether, why not just nuke the code for coloring

**Comment by TerraGS** [comment]
> 
> 
> > Actually, it's a widespread way of me saying "I'd be willing to help in this regard, if you'd be willing to make the request."
> 
> The PR acts as both the request and proposes _a_ solution should no one take on the request. I'm not sure what you're getting at here like you can still fix it right now and have your PR close this one...

Now you seem to be misreading my message. I'm saying that there are a number of pieces this PR is touching and more collaboration could prevent a more complicated situation.

**Comment by bgobandit** [comment]
how am I going to kill Ian by throwing him in the washing machine

**Comment by Twaticus** [comment]
ian needs a bath

**Comment by actioninja** [comment]
apparently people actually care about dying shit with the washing machine

**Comment by PKPenguin321** [comment]
:/ Really a shame since item_color code is still horrendous

**Pull request closed without merging**
