### PR TITLE
New Tree Sprites

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Ausops made them maybe he has a picture

### CODE REVIEW

**Comment by WJohn** [comment]
These look incredible 👍

**Comment by ChangelingRain** [comment]
tree ahead
tree!

**Comment by kevinz000** [comment]
kor is a tree

**Comment by Cheridan** [comment]
>Make 3 trees
>Flip em so it looks like you made twice as many

 Shenanigans!

**Comment by Ausops** [comment]
>shenanigans

;^3333333333333333333333333333333333333c

**Comment by Aloraydrel** [comment]
"He"

**Comment by GunHog** [comment]
The male pronoun (He/Him) is typically the default for those who dislike or do not otherwise accept the application of a genderless plural pronoun (They/Them) to a singular subject.

**Comment by Bawhoppen** [comment]
@GunHog They

**Comment by Militaires** [comment]
but those looks like forest trees :(

**Pull request merged**
