### PR TITLE
[EXTRAREADY][AAAAAA] Hey revolver, don't mothers make good fathers?

### PR DESCRIPTION
**Pull request by actioninja**
no title fuckery going on here
:cl: actioninja
tweak: Suppressed and dry fire sounds are now stored as a variable, and can be edited on a per gun basis.
sounddel: The standard gun dry fire sound was collapsed to one sound instead of 4. They were all just pitch variations anyways, which is now covered by built in sound pitch variation.
soundadd: Revolvers now have a unique gunshot sound that is slightly different for 357 and 38.
soundadd: Revolvers now have a unique dry fire sound.
soundadd: Revolvers now make a unique noise when emptying them besides just the sound of shells falling out.
soundadd: Spinning a revolver such as the Russian Revolver now makes a sound.
spellcheck: Syndicate sniper kit now includes a suppressor instead of a "supressor."
/:cl:

Take number 2: Less shit of samples edition.

gunshots: https://www.youtube.com/watch?v=D89Du_xO0yw
spin that chamber: www.youtube.com/watch?v=WuxXM1q2TrM
click click: www.youtube.com/watch?v=1xavQs6U2GQ

BLAT BLAT BLAT MORE SHOOTERONIS COMING THIS WAY

Again some more sounds mixed from BBC archive stuff since it's high quality and easily available. I'll have a video recorded tomorrow, it's super late and I'm lazy.
Now the gunshots themselves are mixed from a variety of fully public domain sounds. Actually a couple of things are public domain, if they aren't attributed that's why.

### CODE REVIEW

**Comment by Qustinnus** [comment]
https://gamesounds.xyz/ you should use this, it includes the BBC library but also a lot of other libraries released by development organizations and other groups. It includes some sounds that we have had in TG for years.

**Comment by actioninja** [comment]
Alright I just tweaked them a little and I'm liking it better now. Also video in the PR text now.

**Comment by actioninja** [comment]
Cause of how fucked up the soundscape is of this game overall, it's hard to make shit loud because there's already a shitload of stuff that's way too loud happening.
But yeah, these aren't very good still, I'm still not really happy with them and am probably going to start over.

**Comment by nicbn** [comment]
that fire sound is bad

**Comment by actioninja** [comment]
I made a new sound with different original samples that I'm liking way better than the first ones. I'd say this is ready now.

**Comment by subject217** [comment]
IMO - more audible variety is always good, even if the sound isn't FANTASTIC.

**Comment by actioninja** [comment]
Since this is still sitting open, I added some more functionality. To both guns in general and to the revolver.
Now:
- Dry fire sounds are a var
- Suppressed sounds are a var
- Revolvers make a noise besides just the shells falling when you empty them.
- Revolvers have a unique dry fire sound.

**Comment by actioninja** [comment]
Actually this is going to need a hold again. The built in pitch variation on play sound seems to be bugged. Testing it, it always plays sound effects lower than they should be and never higher.

**Comment by actioninja** [comment]
So it's not a fucking bug it's literally just that the pitch variation assumes the audio file has a sample rate of 41k khz.
Who designed this shit.

**Comment by actioninja** [comment]
Alright we got a bit better of a dry fire sound along with actually fixing the issue with pitch.

**Pull request merged**
