### PR TITLE
Adds player preference to hide irrelevant tablecraft recipes

### PR DESCRIPTION
**Pull request by nullbear**
Adds a player-preference to hide recipes if there are no matching components. Very good for depopulating the tablecrafting recipe list.

Ready for merge.

:cl: nullbear
rscadd: Adds a preference option, allowing players to toggle whether recipes with no matching components should be hidden. 
/:cl:

### CODE REVIEW

**Comment by Mercenaryblue** [comment]
I like this. Some recipes should be common. Some recipes should be hard to learn. This adds some discovery factor to tablecrafting

**Comment by nullbear** [comment]
Could even toss recipes onto the maintenance lootlist as a way to find the recipes in-game and promote tablecrafting, as opposed to having to go code-delving.

**Comment by Fox-McCloud** [comment]
This is just intentional inconvenience when the recipes are all listed (or will be, eventually) on the wiki anyway. Not a fan, at all.

**Comment by PKPenguin321** [comment]
I think this would work better as a var for individual recipes rather than a coverall config option

**Comment by nullbear** [comment]
Fox, check the player preference portion. It toggles whether recipes you do not have ANY components for will be hidden, greatly shortening the tablecrafting list.

PKPenguin321. It is a var for individual recipes. The config option just chooses whether it uses it, or shows all recipes by default.

**Comment by WJohn** [comment]
No. The entire reason why we undid this retarded-ass system is because it made table crafting completely unusuable. It was the same as not having table crafting for these items at all, don't enable this shitty inconvenience design.

**Comment by nullbear** [comment]
-sigh- i mucked this up, im gunna have to redo the pr.

**Comment by ChangelingRain** [comment]
This should also be a button in the tablecrafting menu.

**Comment by nullbear** [comment]
I'm doing a bit of other work with tablecrafting, and the menu will have some changes. This will be one of them, but not as part of this PR

**Comment by MrPerson** [comment]
As I said in IRC, I think this should be a checkbox on the tablecrafting menu itself.

**Comment by nullbear** [comment]
idk how to checkbox ui

**Comment by Dorsisdwarf** [comment]
:-1: 

The preference window is an unsorted mess as it is. We don't need moar.

**Comment by Razharas** [comment]
Checkbox would be good but even i dont know how to do in so i wouldnt expect someone else to do it
SO it goes in UI gurus can add checkbox later

**Comment by nullbear** [comment]
ohshit i was actually trying to add this as a tablecraft button...

Probably gunna be some issues.

Might wanna revert this.

**Comment by nullbear** [comment]
or maybe not issues.

I dunno someone said something about tablecraft being buggy. But that was before this was merged.

**Pull request merged**
