### PR TITLE
we dont need this (feleneid remov

### PR DESCRIPTION
**Pull request by boodaliboo**
## About The Pull Request

these cause angry community we dont want we remove
## Why It's Good For The Game
happy players make everyone more happy
## Changelog
:cl:
del: Removed obselete code
code: changed some code
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
inb4

**Comment by nemvar** [comment]
also please be more original next time

**Comment by FancyCyclops** [comment]
>all checks failed.

**Comment by HomocidlePancakes** [comment]
If only it was that simple...

**Comment by wesoda25** [comment]
tg mods silencing brave God fearing gamers

**Pull request closed without merging**
