### PR TITLE
Fixes building unminified tgui

### PR DESCRIPTION
**Pull request by AnturK**
As if anyone will seriously debug this.

### CODE REVIEW

**Comment by optimumtact** [comment]
are you like, hand modifying the css parser in gulp?

**Comment by AnturK** [comment]
Not sure what you mean ? This is our css pipeline definition, it's nothing generated or internal to gulp.

**Comment by SpaceManiac** [comment]
`tgui/gulp/` folder is "our" scripts responsible for configuring gulp, gulp itself is not in-tree.

**Review by SpaceManiac — APPROVED** [review]
I broke this in #44588, for w/e reason I thought docs indicated that `false` would work but this looks like it will actually work, so LGTM.

**Pull request merged**
