### PR TITLE
Changes the stairs near arrivals on Nebula

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Changes the stairs on nebula near arrivals so they only go down one way instead of having stairs to both north and south

## Why It's Good For The Game

Going between Z levels creates huge lag, and it frequently led to you going up the stairs >>> lag >>> right back down to the other stairs. This fixes that by stopping you with a wall

## Changelog

:cl:
map: Nebula Arrivals stairs are now easier to go up on.
/:cl:

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]
You put stuff in the middle of the space area

image

**Review by MrMelbert — COMMENTED** [review]
Left floor decals floating

image

Left decals under the stairs

image

**Review by MrMelbert — COMMENTED** [review]
Stylistic thing, these should be straight lines, not warning lines. Goes for both sides

image

**Comment by MrMelbert** [comment]
Also if it were me I'd make one stairs go north and one stairs go south, rather than both going south

**Comment by DATA-xPUNGED** [comment]
> Stylistic thing, these should be straight lines, not warning lines. Goes for both sides
> 
> image

I didn't touch these at all but sure i'll change the

**Comment by KikoWen0** [comment]
It looks sparse and monotonous, the number of stairs with handrails will be terribly inconvenient for movement. Judging by the number of things that were mentioned above, everything was done carelessly and in a hurry. The problem with the stairs has already been discussed with _koi___ and is already being solved at the moment

**Comment by DATA-xPUNGED** [comment]
> It looks sparse and monotonous, the number of stairs with handrails will be terribly inconvenient for movement. Judging by the number of things that were mentioned above, everything was done carelessly and in a hurry. The problem with the stairs has already been discussed with _koi___ and is already being solved at the moment

Those are really mean things to say, but I digress, if a PR comes up with better stairs than these I'll close this one.

**Comment by LemonInTheDark** [comment]
> It looks sparse and monotonous, the number of stairs with handrails will be terribly inconvenient for movement. Judging by the number of things that were mentioned above, everything was done carelessly and in a hurry. The problem with the stairs has already been discussed with _koi___ and is already being solved at the moment

Please do not be rude to people trying to improve your map, them not meeting your style does not mean they're being lazy/bad at this.

**Pull request closed without merging**
