### PR TITLE
Blob Minor Buffs

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

Tweaks the blob antagonist with some slight buffs/changes.  The changes made were:

- Special blob structures (core, node, factory, etc...) are no longer damaged by lava, preventing cheesing them with the lava staff.
- The blob now announces itself once it reaches a certain size threshold (currently 75 tiles) or 10 minutes passes since the spawning of the core, whichever happens first (up from 3 minutes from when the core spawns regardless of progress)
- Blob Zombies (when a spore takes over a corpse) are now ghost controllable.
- Zombifying Spores has been rebranded as Distributed Neurons, and allows ghosts to control factory-spawned spores along with its previous effects.
- Spores and blobbernauts can no longer understand or speak any languages, and talking makes them talk on the hivemind chat.  Removed the effects of .b messages, since all messages are now in hivemind chat.

## Why It's Good For The Game

Removes a cheese tactic of killing blobs using the lava staff from Lavaland, which I think everyone can agree is a good change.  Also slightly buffs blob by allowing for ghosts to control blob zombies, which allows more ghosts to participate and makes blob zombies a little more interesting.  Also buffs Zombifying Spores to a new status, hopefully making it a more desirable reagent.  Along with this, blobbernauts and spores no longer need to use .b to talk on the hivemind chat.

## Changelog
:cl: Indie-ana Jones
balance: Reports show Hazard-5 entities have mutated to keep their important cells protected from lava.  Reports also indicate that these Hazard-5 entities are now take longer to detect from Central Command, among other things.
/:cl:

### CODE REVIEW

**Comment by tmtmtl30** [comment]
aww, i like the silly taunting blobbernauts

**Comment by IndieanaJones** [comment]
> aww, i like the silly taunting blobbernauts

Me emotes still function as they did before, so any rude gestures are entirely on the table.

**Comment by trollbreeder** [comment]
The blobbernaut (571) shows everyone the middle finger!

**Comment by HomocidlePancakes** [comment]
The blobbernaut (321) signals that it fucked your mum.

**Comment by HomocidlePancakes** [comment]
> Blob mobs spawned from xenobio can no longer speak or understand anything due to this change.

Remove them from xenobio then. Not much use if you can’t even order them.

**Comment by Iatots** [comment]
Genetics is RnD now, I am sure they can share a telepathy injector.

**Comment by ATH1909** [comment]
> > Blob mobs spawned from xenobio can no longer speak or understand anything due to this change.
> 
> Remove them from xenobio then. Not much use if you can’t even order them.

Nah, just let the xenobio ones understand speech (or let all kinds of blobbernauts understand speech, I don't think much harm could come from that).

**Comment by IndieanaJones** [comment]
I forgot xenobio sentience gives mobs the ability to speak common unless they're barred from it.  Xenobio mobs aren't affected in any way, then.

**Comment by IndieanaJones** [comment]
Blobs were able to command sentient blobs spore and zombies to move to different places using middle click, so I added a check on the rally command to make sure they weren't sentient before sending them somewhere.

**Comment by PKPenguin321** [comment]
There isn't even a single QoL change in this PR. If you're using that term jokingly then not funny didn't laugh

**Comment by IndieanaJones** [comment]
> There isn't even a single QoL change in this PR. If you're using that term jokingly then not funny didn't laugh

The announcement time change is sort of a QoL instead of a straight buff, but to make you happy

**Comment by Shadowflame909** [comment]
Less Cheese. Always Good memes.

**Comment by IndieanaJones** [comment]
> Less Cheese. More power of friendship like blob was intended.
> 
> Edit: Just hope you account for rogue sentient blob spore minions trying to attack the main blob. If you made sure they couldn't do that just like blobbernauts. This PR becomes epic.

It's not mentioned above, but they can't attack the main blob.

**Comment by necromanceranne** [comment]
More ghost spawns in a blob fight is good enough for me.

**Comment by Tlaltecuhtli** [comment]
can the spores pull and do they get over time damage for being too far from blob? else i ll see spores welderbombing or tunnel visioning important shit they knew when being a ghost

**Comment by AdamElTablawy** [comment]
Does this notify ghosts that a new spore was created? Otherwise people won't know they can click to pilot a spore.

Also, how does rally spores react with this? Because I found a lot of use in rally spores to act as temporary meatshields and if it's all piloted by meme blob spores then they  might not respond.

Do spores die slowly if off a blob tile, or can they basically just zip away and break APCs?

**Comment by IndieanaJones** [comment]
> can the spores pull and do they get over time damage for being too far from blob? else i ll see spores welderbombing or tunnel visioning important shit they knew when being a ghost

I just removed pulling from them, will update in a second.  They aren't damaged form being too far from the blob, but the regular spores (not zombies) have pretty low health and object damage, so it should be fine.



> 
> 
> Does this notify ghosts that a new spore was created? Otherwise people won't know they can click to pilot a spore.
> 
> Also, how does rally spores react with this? Because I found a lot of use in rally spores to act as temporary meatshields and if it's all piloted by meme blob spores then they might not respond.

It currently does not, but I can also add that.  They don't react to rally spores, but remember sentient regular spores only comes from Distributed Neurons (Zombifying Spores), and weak spores can't be player controlled, so you'll always have spores to send places in that case.

**Comment by jtroopa** [comment]
I was under the impression that blob zombies and blobbernauts were already ghost-controlled. Guess that makes all the times I was murdered by them all the more embarrassing.

**Comment by IndieanaJones** [comment]
> I was under the impression that blob zombies and blobbernauts were already ghost-controlled. Guess that makes all the times I was murdered by them all the more embarrassing.

Blobbernauts are always ghost controlled as it is right now, and blob zombies, unless sentienced by xenobio, are never sentient.

**Review by kriskog — DISMISSED** [review]
Codewise seems fine, but I want a testmerge to gauge new strength with extended timer before merging.

**Comment by kriskog** [comment]
Its testmerged on bagil for now, I didnt get around to doing much with it because conflicting gamemodes. Maybe tomorrow.

**Comment by ishitbyabullet** [comment]
This is not a slight buff at all. Simplemobs that can come back from the dead repeatedly do not suffer a battle of attrition like carbon mobs (players) do. **God forbid if you face distributing neurons though. that shit may as well be impossible unless everyone is a hardcore powergamer that never dies.**

Why do people keep thinking that if the blob can't easily end the round 99% of times then it's too fucking weak?

**Comment by kriskog** [comment]
Spawned late round with about 30 players alive, trashed them with the new strain. Seems a bit overtuned, you should probably reduce the amount of spores active per factory at a time, and the respawn delay. Otherwise, seems okay. 75 size seems like a well balanced point for the announcement.

**Comment by IndieanaJones** [comment]
After watching this play out a few time, I think the major issue is how many extra spores this thing generates.  It makes spores when expanding, when attacked, etc...  And it piles up.  So, I feel the best way to solve the issue is make it generate less of those extra spores, requiring a higher reliance on the spores from the factory.  Should have an update in a bit.

**Pull request merged**
