### PR TITLE
Constructble Navigation Computer

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

Add Navigation Computer circuitboard
Add circuitboard to techweb

Better add after #54274 since it has some auto connect code improvements.

## Why It's Good For The Game

Navigation Computer is great

## Changelog
:cl:
add: Navigation Computer circuitboard to techweb
/:cl:

### CODE REVIEW

**Comment by justinbooj9** [comment]
So what does this navigation computer do? Does this mean I can make a public shuttle that goes to derelict if I happen to desire so?

**Comment by Dennok** [comment]
Yes. But you need Bluespace Navigation Gigabeacon on derelict.

**Comment by justinbooj9** [comment]
I am realizing this now that you can just make a private whiteship of some sorts. I thought it was going to be something to the likes of the mining shuttle.

**Comment by Dennok** [comment]
You can send it to Lavaland too.

**Comment by Iatots** [comment]
I still don't know how mapping shuttles in works. I don't think you can make a *new* shuttle but you should be able to add this to any movable ship and give them the precise tile placement ability that the nukeops/pirate shuttle/whiteships(?) have.

Don't know how this will interact with the escape shuttle.

**Comment by Dennok** [comment]
Yes.
But you need shuttle console to fly to designated port. So you cant hijack escape pod/shuttle, cargo, arrival shuttle.

**Comment by Dennok** [comment]
I think about t like replacement console, since now you cant rebuild it if lost mapped.
Constructed console don't has all that has mapped in consoles initially, but it collect docked port to jump_to ports when you use console.

**Comment by Timberpoes** [comment]
https://github.com/tgstation/tgstation/pull/54284#issuecomment-706785234

Again, no. These consoles are restricted to very specific ships and are irreplaceable. I intend to keep them that way.

I don't want to see these being built. Having the ability to scan an entire z-level with meson vision is cause enough to keep these limited to very specific shuttles and out of the hands of ordinary players.

As a side note, the console type you're attempting cannot be used to select docking locations and the console changes you made in #54274 have rendered nav computers unusable, so no matter what way you look at it this isn't tested either.

**Pull request closed without merging**
