### PR TITLE
Adds a crew monitoring console to the warden's office in BoxStation

### LINKED ISSUE #29137: Warden's office on box doesn't have crew monitoring console.
Every other big station has it.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: The BoxStation warden's office now has a crew monitoring console.
/:cl:

All the other big stations have a crew monitor in the warden's office, so I made Box consistent with the rest of the game's maps. This replaces the table with an intercom to the right of the front desk.

Closes #29137.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Repukan** [comment]
>Buffing sec

**Comment by improvedname** [comment]
>big station box is compared mini against delta

**Comment by ShizCalev** [comment]
Can we get the intercom back though? :(

**Comment by Steelpoint** [comment]
I tried this half a year ago and I got shat on for the idea.

Still a good idea I think.

**Comment by PKPenguin321** [comment]
Should be removed from the other maps imo

**Comment by Steelpoint** [comment]
Considering medbay has a ton of portable Crew Monitoring Consoles I don't see this being an issue at all. 

Virtually all other SS13 maps have a crew monitoring console somewhere in security, the only reason Boxstation is the exemption is due to the fact I was the one to propose its addition, and anything security related from me is heavily scrutinised.

Gives a good Warden more to do.

**Comment by PKPenguin321** [comment]
Still should be removed from the other maps imo

**Comment by Xhuis** [comment]
Hey, that's not up to me to decide. This is just more consistent.

**Comment by ShizCalev** [comment]
Would you mind readding the intercom you deleted to the other table please?

**Comment by Cyberboss** [comment]
That's for a different PR

**Pull request merged**
