### PR TITLE
Revert "Revert "Adds some file helpers for working with byond file references…"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#54085

Not my fault valid code doesn't pass lint because the lint doesn't accept valid code.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
@SpaceManiac

**Comment by SpaceManiac** [comment]
1. change `I.icon` to `UNLINT(I.icon)`
2. fix the unit test failures

**Comment by optimumtact** [comment]
did you just finally try to use these helpers

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
as described above

**Comment by MrStonedOne** [comment]
> did you just finally try to use these helpers

I was trying to help goof setup the 15 stuff to use the cdn and went looking here for the temp folder proc and ya.

**Comment by optimumtact** [comment]
you need to fix the tests and LINT issue

**Pull request closed without merging**
