### PR TITLE
Fixes ERT ion rifle and z2 floating areas

### PR DESCRIPTION
**Pull request by ghost**
Trash cleaned from ERT edits

Added a pin to the ion rifle for ERTs

### CODE REVIEW

**Comment by Cheridan** [comment]
We should probably do something about ion rifles... Them being an R&D item that's also placed on the map is inconsistent both code-wise and fluff-wise.

**Comment by paprka** [comment]
They were added to R&D post-armory, IIRC.

**Comment by Nyvrem** [comment]
There are multiple things R&D can not produce at roundstart that are on the map, such as the majority of the circuitry, high-capacity power cells, intellicards, MMIs, healthscanners HUDs, beacons and magboots.

**Comment by GunHog** [comment]
I will code the Ion Carbine if you get me a sexy enough sprite.

**Comment by paprka** [comment]
clip 2015-02-08 at 04 13 37

**Comment by dannno** [comment]
jesus christ

**Comment by paprka** [comment]
someone please merge this though

**Pull request merged**
