### PR TITLE
Add air alarm and atmos machinery to kilo server room + meta tcommsat air alarm pixel shift

### LINKED ISSUE #69562: Kilo station server room air alarm set incorrectly
Reporting client version: 514.1585

## Round ID:
[189509](https://scrubby.melonmesa.com/round/189509)

## Reproduction:
Start round on Kilo. Check alert console. Immediately see alert for atmo in Research Division Server Room due to being too cold.

### PR DESCRIPTION
**Pull request by msgerbs**
## About The Pull Request
Replaces the intercom in the Kilo Research Department Server Room with an Air Alarm and adds a vent and scrubber. Also removes the air alarm from the server/cold side of the room which was going off constantly and making atmos techs mad.

Also, I shifted the tcommsat air alarm on metastation 2 pixels to the left because it didn't match the rest of the air alarms. Yes, really.

## Why It's Good For The Game
Makes it consistent with other server rooms, removes an annoying roundstart atmo alarm.

Fixes #69562

## Changelog

:cl: VexingRaven
add: The Research Department Server Room on Kilo Station now has an air alarm and ventilation.
fix: The Research Department Server Room on Kilo Station no longer has an atmosphere alert at start of shift.
/:cl:

### CODE REVIEW

**Comment by msgerbs** [comment]
MapDiffBot still hasn't run?

**Comment by san7890** [comment]
> MapDiffBot still hasn't run?

it's brokey

**Comment by msgerbs** [comment]
> > MapDiffBot still hasn't run?
> 
> it's brokey

How fix?

**Comment by san7890** [comment]
> > > MapDiffBot still hasn't run?
> > 
> > 
> > it's brokey
> 
> How fix?

ask AffectedArc07/Asd/CoffeeKat/Tigercat2000 or whoever in the coderbus discord

**Comment by msgerbs** [comment]
YAY FINALLY

**Pull request merged**
