### PR TITLE
Fixes being able to ignore weather effects (Ash Storms / Rad Storms) by sitting in lockers and other nonsense

### PR DESCRIPTION
**Pull request by Ergovisavi**
:cl:
fix: Fixes lockers, bodybags, etc, giving you ash storm / radiation storm protection
/:cl:

The last Indiana Jones movie was bullshit, so here's a fix

### CODE REVIEW

**Comment by PKPenguin321** [comment]
throwback to https://github.com/tgstation/tgstation/pull/16112

**Comment by Bawhoppen** [comment]
:+1: for making you vulnerable in radstorm, but  :-1: for ashstorm

**Comment by Ergovisavi** [comment]
How is this a balance or rebalance? This is a fix. Whoever refactored weather broke this in the first place.

**Comment by francinum** [comment]
While a fix, this is also a change to how hard it is to survive these events.

**Comment by lzimann** [comment]
but indiana jones wouldn't lie to me, would he?

**Comment by optimumtact** [comment]
I think logically you could avoid an ashstorm by hiding in a closet, maybe make it a toggle on the weather datum?

**Pull request merged**
