### PR TITLE
Flash Buff

### PR DESCRIPTION
**Pull request by yackemflam**
Flash buff because a lot people are complaining about unstoppable borgs.

### CODE REVIEW

**Comment by jughu** [comment]
first they complain it being OP as fuck
now they complain it be weak as fuck
make up your minds reee

**Comment by Dorsisdwarf** [comment]
You missed the step where it was super-nerfed you turbonerd

**Comment by Supermichael777** [comment]
maby borgs need new softer counters? insted of 3 gg turbocounters

**Comment by Zilenan91** [comment]
Gotta make it so borgs have human weaknesses like slowdown to damage and shit first. You can't make it so borgs are as strong as they are while giving them weak counters because there's nothing else that balances them out than their stuns.

**Comment by Davdichan** [comment]
Truly some based and logical Zil comments.

Oh waits he's full of fucking shit. Borgs have no stuns of their owns and can't just pick up a fucking weapon to kill people, and if they are emagged they need to actually be lethal to the crew.

If you want this PR to be balanced, make flashes stun humans again. Since that's obviously not going to happen, stop pretending borgs are OP because you got dunked for being shit-tier shooting spree antag and got dunked for it.

**Comment by InsaneHyena** [comment]
> Borgs have no stuns of their owns
AHAHAHAHAHAHAHAHAHAHAHHAHA

**Comment by jughu** [comment]
Standard - spray bottle
Engineering miner - electric arm
Service - lol who even uses this
Peacekeeper - gimme a hug!

**Comment by Davdichan** [comment]
Hyena you're about as dumb as Zil sometimes

All thos eonly apply to emag/malf borgs. Which are rare as is. AND all of those borgs are still vulnerable to 

EMP
Laser Pointers
Robotics Terminal

So,  I as again why do ALL borgs need a LOLFLASHGGNORE option when most of them don't even have the ability to stun/disarm opponents on their own, none of them have ranged options, and each and everyone one of them can be shutdown instantly.

**Comment by Zilenan91** [comment]
please leave because you have no idea what you're talking about david

**Comment by jughu** [comment]
The smart choose here is not being able to use shit

**Comment by jughu** [comment]
David has a point here borgs got shitted on masivly because poeple couldnt plan their shit out for example poeple say secborg always fucked their plans up but a plan wouldnt be a plan if it wasnt foolproof thats why you think out the obstacles that might come your way if theres a secborg you take it out before your real mission so it can fuck you up later and this is just why borgs get nerfed to the ground

**Comment by YakumoChen** [comment]
I just want a way to make it so it's not an instant GGNORE the moment a borg decides to come to my AI sat to fuck up my day.

At least the wallflash used to be able to stall for time.

Having such a critical and glaring weakness for the AI, which already finds itself hard to defend under normal circumstances (or, and especially abnormal ones)

I don't think we need to bring the 15 second flash stun back however, that's just hilariously crippling to cyborgs, at least now with flash you actually have a proper chance of getting away. Maybe lower the cooldown to wall flashes?

The main problem is that you NEED to be malf as borg to really do any damage, aside from engi borg who has the tools to do so anyway. The other main problem is that the crew will ALWAYS go nuclear regardless of situation, but that's a player problem.

**Comment by Davdichan** [comment]
@Zilenan91 >please leave because you have no idea what you're talking about david

I think we have a new sig quote

The fact that you think borgs in their current state are over powered or even balanced at all speaks volumes of your ignorance of silicon play and how things actually go down.

@YakumoChen 

Wall and Portable flashers (the security ones that wrench into place) haven't been touched in years. You can still trigger them and  stun borgs just the same as they still stun people. The only problem is they only have about a 3x3 radius from the bulb so you need to time it, but if you keep clicking it every 3-5 seconds the borg can't move till help arrives, hopefully before the bulb runs out.

**Comment by yackemflam** [comment]
@Davdichan 
That is like a 15 second stall.
Any rogue borg is able to kill the ai with no problem

**Comment by kevinz000** [comment]
Daily reminder that peacekeeper borgs have an AOE flashbangesque stun because it was coded by someone who loves those.

**Comment by Anonmare** [comment]
It didn't used to be a problem since all non-synced borgs belonged to the malfunctioning AI.
Metastation's shutter is helpful against rogue borgs when you know there's one running around but if if it's engie it'll force it's way in - but at least you'll have warning. Though that only works if you're either an antag AI or you have proof of a subverted borg first else that's metagaming.

Only thing I can really suggest is a malf module that has the effect of emagging a borg to make it loyal to you.
Or an expensive, one-use per buy ability that gives all unsynced borgs with an active Law Sync the old Malfunctioning law.

**Comment by Davdichan** [comment]
@yackemflam 15 can be ages for people who know what they are doing. If you don't have a camera bookmark in the RD's office for quick locks and destructs of borgs than what are you doing?

Overall I'd much rather see non-synced borgs be targetable by laser turrets than have some OP buff to flashes that can stun borgs for 10+ seconds at a time. 

The only thing this PR does is make it so the unrobust can half ass their way through a Malf round or kill an emagged borg without trying, and it's not even like we have laser gun sec borgs who can counter flashes anymore.

**Comment by Bawhoppen** [comment]
AS I KEEP SUGGESTING, MAKE WATER SPRAYED FROM BOTTLES DAMAGE BORGS, AND LET BORGS SLIP ON LUBE/WATER AND OVERLOAD THEIR SENSORS TEMPORARILY

**Comment by yackemflam** [comment]
@Davdichan 
Here's the problem
Borgs don't much crowd control against them
Humans on the other hand has 
stamina damage
health damage
flash
normal stuns
bolas
slips (banana, water, lube, etc.)
ranged stuns
loud shit that makes you deaf (Big deal if you can't communicate quickly)
cuffs of different kinds
spess
low body temp
chems
and more that I can't name off the top of my head

Meanwhile borgs have
flash
emp
lockdowns

Flash is already rare enough
Emp is stupid rare outside of antags
and the lockdown computer can be easily countered by breaking the screen.

Also, you can't blow non-emagged antag borgs.

**Comment by Davdichan** [comment]
Borgs have power issues, not stamina.
Borgs have health damage, it completely removes their ability to use their modules
Flashes don't stun humans, just confuse them. This is what previously had been done to flashes but people got dunked so REEEEE back to square one.
Regular stuns like prods and batons may not work, but borgs don't even have access to these outside of emagged modules. It's like complaining you can't disarm a borg, when the borg equally can't disarm you.
Bolas can be removed with a minor delay. Again, not something a borg can use against people.
most slips can be negated by walking, magboots or galoshes.
Disablers still hurt borgs last I checked, draining power.
Loud stuff that stuns humans does the same to borgs, be it a flash bang or a transfer bomb. Usually the borg is stunned for longer too and can't talk during that stun either, where as a human can scream over the radio.
Borgs can be locked down at will by anyone with the console, power cells removed or their wire just cut, this can't be resisted out of or fixed by the borg no matter how long it's left alone
Spess is just as dangerous to a borg, it might night kill them outright but not every module has the means to navigate, if a borg gets pushed out an airlock they don't have the luxury of tossing their shoes to get back to the station
Body temp is rare enough that it's happened during a breach or atmos grief, fire suits are common enough that most greytides can get one.
Chems are a two way street. Borgs can't be hit with a neurotoxin true, but they also can't take meth or  slap a patch on themselves to instantly heal every wound they have.

Non-emagged antag borgs should be balanced seperately if they don't have lockdown terminal access, such as ratvar and nuke ops borgs. Nerfing all borgs because of this is about as dumb as making flashes effect everyone because a changling can render itself stun/cuff immune in the right conditions.

**Comment by yackemflam** [comment]
>Emag engineering borg/mining borg
>they can repair themselves
>Charging stations placed throughout the station
>Stun anyone, includining other borgs, and then beat them to death

'Most slips can be negated by walking.'
Only water does that, all other slips will still stun you.

Disablers deal minimal power damage to borgs

Only those with RD acces can actually use the computer itself.

Space deals no damage to a borg and you can just push yourself off a wall once you hit something.
Engi borgs also can use the fire extenguisher

Atmos greif is extremely common

Chems don't effect borgs.
Two borgs can repair themselves from what I know, engi and mining

**Comment by yackemflam** [comment]
You also need robotics access for the console, so no, not everyone can use it.

**Comment by yackemflam** [comment]
The main problem is just that it's pretty broken for a rogue silicon be able to murder anyone without a flash and doing so alone is really bad.

Also, sec has a counter to everything.

**Comment by jughu** [comment]
Because you cant stun it doesnt mean you cant stop it

**Comment by yackemflam** [comment]
In a game where stuns are king of combat, yes I am buffing flashes to even the field.

**Comment by jughu** [comment]
Dude flashes are meant to be a short stun if you want a long stun just get a ion rifle or let rnd make one or order from cargo lol

**Comment by PKPenguin321** [comment]
haha what the fuck is going on here

**Comment by optimumtact** [comment]
>The main problem is just that it's pretty broken for a rogue silicon be able to murder anyone without a flash and doing so alone is really bad.

But this PR doesn't help or change that at all?

**Comment by Zilenan91** [comment]
It can't be changed without giving borgs slowdown to damage and stuff like that that humans have already. If we don't move away from borgs being the way they are right now they're totally unfun to fight against without having a hard counter.

To put it more simply, if borgs are hard to counter, they must be hard countered
If borgs are easy to counter, they must be soft countered

Oh also david is sperging the fuck out for some reason.

**Comment by jughu** [comment]
Zile shoo you cant beat a borg

**Comment by jughu** [comment]
Or unless we ditch em sprites port goonborgs where you can knock the borg limbs off after some damage leg limb knocked off? Slowdown! Arm knocked off? A module less!

**Comment by Fox-McCloud** [comment]
You can always tells who the borg players are.

**Comment by Cheridan** [comment]
If rogue borgs not having a counter is an issue, maybe only have flashes work on rogue borgs? Just throwing out ideas.

**Comment by Zilenan91** [comment]
How do you define rogue borgs though. Checking for borgs under a traitor AI would be easy, but what about Ion law borgs or borgs who were manually subverted with laws. How would you check for one-human laws and not other laws and that sort of thing.

This would also cause some stupid stuff to happen, like people demanding borgs be flashed in order to determine if they're evil or not and we don't really need more checks like that in the game.

**Comment by InsaneHyena** [comment]
> Zilenan talking sense
Holy shit, what is going on?

**Comment by jughu** [comment]
You check them the same way you find traitors seeing them doing suspicous shit simple

**Comment by optimumtact** [comment]
Majority positive opinion, nobody I could get my hands on had a strong feelings either way, so in it goes

**Comment by jughu** [comment]
Pfff powercreeps

**Comment by Zilenan91** [comment]
Flashes used to be much better than this

**Comment by demonfiren** [comment]
Bayborgs with modules that break if you spit on them when?

**Comment by Dorsisdwarf** [comment]
>If rogue borgs not having a counter is an issue, maybe only have flashes stun on rogue borgs? Just throwing out ideas.

That seems like a really bad idea. Monumentally bad. Instant is-the-ai-rogue antagcheck

**Comment by Cheridan** [comment]
Just don't hack them until you're ready to get murdering?

**Pull request merged**
