### PR TITLE
Reflector vest buffed, covers arms and groin

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request
Revives #44267.
Title, reflect chance going from 40 to 50.

## Why It's Good For The Game
Reflective armor is vastly underused, owing to the fact that if you need it, you're either facing threats that don't fire energy weaponry (security against nukies, cult, traitors, etcetera), or are an antagonist that is most threatened by non-energy weaponry (any antag against shotguns). On the offchance that you DO need it, the random limb hitting chance makes the armor still an awkward choice, with half the shots not hitting the armor at all. This PR slightly helps with that

## Changelog
:cl: Nemvar, Carlarc, and Bobbahbrown
balance: reflector vest covers arms, reflect chance from 40 to 50
imageadd: reflector vest has ARM BANDS
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
add the helmets

**Comment by Dorsisdwarf** [comment]
grumble grumble spriting

**Comment by knacker48** [comment]
If you're covering the arms is it even a vest anymore? You'd probably need to adjust the name to something like reflective armor or something like that

**Comment by carlarctg** [comment]
> If you're covering the arms is it even a vest anymore? You'd probably need to adjust the name to something like reflective armor or something like that

it's a vest with armbands so

**Comment by GuyonBroadway** [comment]
@knacker48 

https://payday.fandom.com/wiki/Armors#Combined%20Tactical%20Vest

**Comment by PKPenguin321** [comment]
What happened to these being called ablative armor

**Comment by GuyonBroadway** [comment]
They don't ablate is why, but they do have a reflect chance.

**Comment by carlarctg** [comment]
im working on replacing this with a full-body trenchcoat instead

**Comment by Learner10** [comment]
Why replace when you can add a trenchcoat alongside. Call it a _Titan-Fiber Trenchcoat_. We all know that titanium walls can reflect projectiles, and the name doesn't sound too awful.

**Comment by nemvar** [comment]
Trenchcoats make everything better.

**Comment by GuyonBroadway** [comment]
If yer 14yrs old and also like gasmasks, katanas and linkin park maybe...

**Comment by 81Denton** [comment]
waiting on the reflector trenchcoat and reflector fedora

**Pull request merged**
