### PR TITLE
Build SpacemanDMM from source

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
Incoming purity/sleep lints

also private/protected and unreachable code detection

### CODE REVIEW

**Comment by spookydonut** [comment]
shits fucked

**Comment by spookydonut** [comment]
muahahahaha

**Comment by Cyberboss** [comment]
Y tho

**Comment by optimumtact** [comment]
To get new lints faster than spacemaniac releases new versions of spacemanDMM obviously

**Review by ninjanomnom — APPROVED** [review]

**Comment by SpaceManiac** [comment]
This should not have been merged.

Master has been failing Travis because dmdoc builds still rely on `install_spaceman_dmm.sh`.

Additionally, the new lints have been raising errors in VSC because a new release of the language server had not been made.

**Pull request merged**
