### PR TITLE
Birdshot Ordnance Igniter Fix

### LINKED ISSUE #83505: Birdshot's ordinance burn chamber has no APC
## Issue Summary

The area is ordinance burn chamber

/area/station/science/ordnance/burnchamber

This is next to the lab, but has no APC, so the igniter does not work in the chamber.

### PR DESCRIPTION
**Pull request by GremlinSeeker**
Fixes https://github.com/tgstation/tgstation/issues/83505

### CODE REVIEW

**Comment by SyncIt21** [comment]
This is the wrong fix. You should merge the burn chamber with the main lab as suggested in #83505  so they share the same apc, not add an additional one.

**Comment by GremlinSeeker** [comment]
> This is the wrong fix. You should merge the burn chamber with the main lab as suggested in #83505 so they share the same apc, not add an additional one.

Should be simple enough. I'll do that right now.

**Comment by GremlinSeeker** [comment]
Before: 
ChamberFlagsBefore

After:
ChamberFlags

**Comment by SyncIt21** [comment]
Good

Edit your PR body and type

Fixes #83505 

To link and close the issue

**Review by Maurukas — COMMENTED** [review]
Please push an empty commit or merge master and push to force Mapdiffbot to rerun. It has been fixed.

**Pull request closed without merging**
