### PR TITLE
Adds info about schema versioning to head of db changelog file

### PR DESCRIPTION
**Pull request by Jordie0608**
This is to remind anyone modifying the file (and thus the schema) to also change the current schema revision and provide a bit of information about the system.

Also by keeping a query to insert new rows to the table here we don't have to end up putting it in every entry made to this file which I think is better.

The lack of past numbering might be a niggle but it'd be easy to add them for the previous and then on future entries.

This also changes the code checking the schema version to grab the latest row by date so it works with inserts rather than updates.

I also fiddled with the query name and fault message, removing reference explicitly to tg since downstreams and all may not have the same schema.

@MrStonedOne @optimumtact

### CODE REVIEW

**Review by optimumtact — APPROVED** [review]

**Comment by ninjanomnom** [comment]
It might be best if the versioning style was chosen now. [Semantic versioning](http://semver.org/) is what I'm preferential towards personally as it conveys useful information in the version number rather than being up to the whim of the updater.

**Comment by MrStonedOne** [comment]
This is more about a code based way to control database versioning, Semantic versioning is nice, but it's a bit overkill

**Comment by MrStonedOne** [comment]
No, this should be inserts, no updates.

The whole point is to allow you to keep track of when each version was applied.

**Comment by optimumtact** [comment]
there's no date column though

**Comment by optimumtact** [comment]
err wait, I think I forgot to add a where date is latest to the schema query

**Comment by MrStonedOne** [comment]
Am I high then? I was sure we agreed on adding a automatically updating date column

**Comment by Jordie0608** [comment]
The current system would only work with updates; it finds only the first row.

**Comment by MrStonedOne** [comment]
Well, then fix that!

**Comment by MrStonedOne** [comment]
It should find the latest row by date.

**Comment by Jordie0608** [comment]
I resisted the urge to update the primary key index even though it might save whole milliseconds over the span of several years.

**Pull request merged**
