### PR TITLE
Enables disemboweling/cranial fissures when outside of hardcrit for cursed individuals

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title.

Slightly rewrites cranial fissure weight code because I spent like 20 minutes trying to keep only one ..() and it seriously confused me.
## Why It's Good For The Game

Frankly, masochism.
Most times when you suffer a disembowelment, or a cranial fissure, by the time you get back up it's fixed. This is because they can only really happen in hardcrit. However, if you get disemboweled or suffer a cranial fissure while ALIVE, it can potentially make some very silly scenarios. Such as:

Getting hit by his grace, walking away with a cranial fissure.
Getting your lungs shot out, picking them up, and throwing them at a medical doctor to get them put back in. 

Also, it just feels weird to have these arbitrary restrictions in place from a character perspective. I get why on a balance perspective, but why can my guts only spill out in hardcirt? Realistically speaking, I could get shot by a sniper and just have my guts instantly spill out.

## Changelog
:cl:
add: Being cursed now enables disembowlements/cranial fissures outside of hardcrit
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Can you put a bit more explanation into what this is and why it should be in the game please

**Comment by uaioy** [comment]
mortal kombat quirk

**Comment by nikothedude** [comment]
> Can you put a bit more explanation into what this is and why it should be in the game please I think we already have too many arbitrary medical quirks which are just there to fill space and you haven't tried to explain why this one should exist or what it adds to the story of your character

okay, sure

**Comment by nikothedude** [comment]
ok, added more elaboration on my thoughts, but if its not enough thats fine, this isnt a particuarly important pr

**Comment by Jacquerel** [comment]
OK so your new justification is a reason for these things being possible outside of crit. Why should it be tied to the quirk system instead?

**Comment by nikothedude** [comment]
> OK so your new justification is a reason for these things being possible outside of crit. Why should it be tied to the quirk system instead?
> 
> To me this doesn't seem like a good quirk. It is entirely mechanical, abstract, and says absolutely nothing about the character. If you want this feature, shouldn't it just be in the game rather than an obscure and strange character option?

Are you implying if I want to go down this path, I should do something like just applying this to all humans? Or something like a mutation that does this? The first is probably ab ad idea, by the way, this was done for a reason

**Comment by Metekillot** [comment]
> > OK so your new justification is a reason for these things being possible outside of crit. Why should it be tied to the quirk system instead?
> > To me this doesn't seem like a good quirk. It is entirely mechanical, abstract, and says absolutely nothing about the character. If you want this feature, shouldn't it just be in the game rather than an obscure and strange character option?
> 
> Are you implying if I want to go down this path, I should do something like just applying this to all humans? Or something like a mutation that does this? The first is probably ab ad idea, by the way, this was done for a reason

Just because someone did something for a reason doesn't mean it was a good reason or that that it had the intended effect.

**Comment by Loafin34** [comment]
> OK so your new justification is a reason for these things being possible outside of crit. Why should it be tied to the quirk system instead?
> 
> To me this doesn't seem like a good quirk. It is entirely mechanical, abstract, and says absolutely nothing about the character. If you want this feature, shouldn't it just be in the game rather than an obscure and strange character option?

it's a fun way to be injured that is silly and purposefully gives you a small disadvantage against high damage weapons (where you already were gonna be messed up) that is better for comedic scenarios (getting your head split open and looking casually at the other guy "hey, does it look bad?" "yeah, it's pretty bad." "shit!" *dies* )

**Comment by SomeoneYouProbablyKnow** [comment]
Could be rolled up into the cursed quirk or maybe the frail quirk instead. We already have way too many quirks but this is a very fun interaction.

**Comment by Pickle-Coding** [comment]
Cranial fissures don't instantly cause the user to die, so I don't see why that's still locked behind crit. Could easily remove the crit requirement without any changes. Right now disemboweling causes all of the organs to instantly fall to the floor, which causes the victim to instantly be unconcious. Will probably need to rework how disemboweling works if the crit requirement for that will be removed outside the quirk.

**Comment by Jacquerel** [comment]
> Are you implying if I want to go down this path, I should do something like just applying this to all humans? Or something like a mutation that does this? The first is probably ab ad idea, by the way, this was done for a reason

I don't think quirks as a place for "I want to opt into a mechanic" unless it can be accompanied by adding to the story of your character. The only justification you have made so far is for "this should be able to happen", but none for "as part of the quirk system".
If you don't have any justification for it being a quirk other than "I want it to be opt-in" I guess I don't think that alone is good enough.

**Comment by nikothedude** [comment]
> > Are you implying if I want to go down this path, I should do something like just applying this to all humans? Or something like a mutation that does this? The first is probably ab ad idea, by the way, this was done for a reason
> 
> I don't think quirks as a place for "I want to opt into a mechanic" unless it can be accompanied by adding to the story of your character. The only justification you have made so far is for "this should be able to happen", but none for "as part of the quirk system". If you don't have any justification for it being a quirk other than "I want it to be opt-in" I guess I don't think that alone is good enough.

Fair enough. What if we instead wrapped it into the cursed quirk/component, as someone suggested? It's thematically appropiate for being cursed.

**Comment by moocowswag** [comment]
Its less than a quality about the character and more of a mechanic that the character is able to experience, just like the bad luck quirk that randomly GETS you.

**Comment by Jacquerel** [comment]
I'd be perfectly happy for it to get rolled into the bad luck quik

**Comment by Loafin34** [comment]
disemboweling should leave your heart inside (because thats what makes you go into hardcrit) and let people pull it out mortal kombat style with their bare hands or another cut with the knife

**Comment by nikothedude** [comment]
> disemboweling should leave your heart inside (because thats what makes you go into hardcrit) and let people pull it out mortal kombat style with their bare hands or another cut with the knife

not a bad idea but thats a separate thing i'd have to justify, maybe in another pr

**Comment by carlarctg** [comment]
there's a whole quirk about being easier to wound why isn't it there

**Comment by ExcessiveUseOfCobblestone** [comment]
should be base with rarity tbh, whats the allure behind keeping this quirkbound?

If you wanna up the chances or something okay, but I think it would be fine with it happening without the quirk and don't necessarily understand why this has to be locked behind a quirk.

**Comment by nikothedude** [comment]
> should be base with rarity tbh, whats the allure behind keeping this quirkbound?
> 
> If you wanna up the chances or something okay, but I think it would be fine with it happening without the quirk and don't necessarily understand why this has to be locked behind a quirk.

the allure is that i feel like i would invoke some serious wrath if i just enabled it by itself and i dont feel like justifying that

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
