### PR TITLE
Fixes custom ticker logic (#36792)

### PR DESCRIPTION
**Pull request by robbym**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: robbym
fix: Fixed an error with integrated circuit tickers where they would sometimes fail to tick.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Fixes a bug.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
CL doesn't need to be that specific, players only need to know what changed gameplay wise. And you put your name after the first :cl:
Good PR

**Comment by robbym** [comment]
Like so?

**Comment by PKPenguin321** [comment]
Yes. Personally I would make it a tiny bit more specific though, like "Fixed an error with integrated circuit tickers where they would sometimes fail to tick."

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Thanks for contributing and welcome to /tg/station 13!

**Pull request merged**
