### PR TITLE
Don't give up, skeleton

### LINKED ISSUE #40672: skeletons cant be hugged :(
how to reproduce:
1. find skeleton
2. try to hug skeleton
3. fail your veiled attempt at preforming CPR on them

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: QualityVan
fix: Hugging skeletons is now possible
/:cl:

Fixes #40672 
The if not in crit checks in human_defense and carbon_defense could be removed because they should only be reached when they're either true or irrelevant.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
❤️ 💀

**Comment by XDTM** [comment]
Check if clicking on a lying skeleton initiates cpr or helps them up, it should be the former so they can lie down to spook people

**Comment by QualityVan** [comment]
Tested for that, it reports them as dead and doesn't start cpr same as a regular corpse.

**Comment by QualityVan** [comment]
oh god dammit

**Pull request closed without merging**
