### PR TITLE
Remove the hyphen from the default value of the github url string (no longer -tg-station)

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

this hyphen bugged me

## Why It's Good For The Game

its the old repo url (it works but we could deprecate it)

### CODE REVIEW

**Comment by maxymax13** [comment]
ok -bobbah-brown

**Comment by Iamgoofball** [comment]
:-1: this kills soul and /tg/station history

**Comment by cacogen** [comment]
The transition into transgender station is almost complete

**Review by Mothblocks — APPROVED** [review]
skewered

**Pull request merged**
