### PR TITLE
Removes ways to ERP + removes Felinids

### PR DESCRIPTION
**Pull request by GawdDamn**
## About The Pull Request
We remove methods of ERP + A species which has the MOST ERP SESSIONS ever recorded

Step 1)

The simple step, Laying down. Yeah we removed resting.

step 2)

The good old suckie. Your sprite will never be nude now meaning no immersive ERP

step 3)

Sexy poses? BWAHAH! we removed the species sprites and replaced them with stick figures. Good luck looking sexy now

step 4) we removed pronouns. Simple. No gay sex, straight sex. ANYTHING. 

step 5) we removed sex all together. your welcome

## Why It's Good For The Game

I have effectively STOPPED all ERP! I should be a DEVELOPER!! We can remove the rule for ERP. cause i have stopped all methods of it. I have even added a way so you cant even say ERP. I have removed SEX

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
very funny

**Comment by GawdDamn** [comment]
John, You like ERP?? wtf bro

**Comment by JohnFulpWillard** [comment]
im the creator of sex 2.1

**Comment by GawdDamn** [comment]
NOT SEX 2.1!!!!!!!! MY MORTAL ENEMY. I WILL CRUSH YOU, JOHNNIE!!!!!


CURSE YOUUUUU!!!!

**Comment by LemonInTheDark** [comment]
haha real funny

**Pull request closed without merging**
