### PR TITLE
Donates part of my gbp

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
965441894-kid_20stirring_20pot

## Why It's Good For The Game
I don't have a valid use for my GBP that will affect the game

### CODE REVIEW

**Comment by Kylerace** [comment]
no

**Comment by Kylerace** [comment]
Screenshot_2027
we dont want to deal with these prs sorry

**Comment by LemonInTheDark** [comment]
sucks to suck

**Comment by jlsnow301** [comment]
i'm going to become the joker

**Pull request closed without merging**
