### PR TITLE
Omega

### PR DESCRIPTION
**Pull request by Okand37**
Omega Station, contrary to the latest Delta Station, is a lowpop map intended for crowds between 20-to-30, give or take.
Full-scale map : https://drive.google.com/file/d/0B67Y0cE3wQneMWx0M2REOGxxbTQ/view
Forum thread : https://tgstation13.org/phpBB/viewtopic.php?f=11&t=8916&view=unread#unread

Bugs, issues, oversights and ideas are more than welcome to be posted on the forum thread or below, let me know what you think!

### CODE REVIEW

**Comment by Iamgoofball** [comment]
NO MORE LOWPOP MAPS

**Comment by Okand37** [comment]
I'd agree with you, but neither birdboat nor ministation are maintained and quite possibly could be chopped/replaced. Do you have anything against the map in itself at all, or do you just have an aversion to lowpopulation maps? If you have any criticism, I'd love to hear it! : )

**Comment by Iamgoofball** [comment]
If we had 1 solid LOWPOP map it'd be bae but we have like three and this codebase doesn't do harems

**Comment by lzimann** [comment]
Before anyone yells: "FEATURE FREEZE", this was opened before the freeze started(#22438), but had to be reopened.

**Comment by Jordie0608** [comment]
And maps are generally exempt anyway.

**Comment by optimumtact** [comment]
You're on the wrong side of the code freeze

**Comment by optimumtact** [comment]
Remove mini or bird if you want this merged.

**Comment by Okand37** [comment]
I don't mean to be rude, but did you actually bother reading the feature freeze thread, or even the posts in this? I don't really think its up to me to remove mini or birdboat.

**Comment by optimumtact** [comment]
Letting people merge maps without justifying them against existing ones is how we ended up with dream and eff in the first place. Pick one of the two to remove that you think your map is better than and therefore worth the overhead of maintaining.

on top of that you need to define this as a map in the maps config and add it to the travis yaml as a build target. (side note you also need to do that for Dream)

**Comment by KorPhaeron** [comment]
Kill mini

**Comment by Jordie0608** [comment]
I don't think a map should be removed in the same PR, that sounds like it'll just cause PR to be swamped in a conversation of \~opinions\~ that'll greatly distract from the actual purpose here. It could also lead to messy merge issues between trying to add and remove files which I'm sure Okand won't want to deal with as a new contributor. Plus as we recently saw in #22307, it seems the general preference is for birdboat anyway.

**Comment by calzilla1** [comment]
Kill burb. Mini meme is too fun

**Comment by ChangelingRain** [comment]
I have no idea how the fuck you're conflicting, but you are.

**Comment by lzimann** [comment]
\>conflicting with the file that is being added

nice

**Comment by Okand37** [comment]
Huh! I guess I must've forgot to rewrite something on the omegastation.dm, I'll take a look at it later today!

**Comment by kyrahabattoir** [comment]
How does this replace mini in any way?

Oh right, it doesn't.

**Comment by optimumtact** [comment]
Thanks for your snarky comment. Feel free to maintain ministation in your own repo

**Comment by kyrahabattoir** [comment]
What else am i supposed to say? "thank you for removing the only map that works with less than 10 people?"

**Comment by Okand37** [comment]
I apologise if you feel its unfit as a low population map, but it is fairly snug and compacted, as well as quite easy to get around! The centre atrium makes moving through the map a lot easier as you can move straight through the middle to get from point A to point C, without having to go around through point B or D! (aka, without having to go around the halls!)

It can comfortably work with a small number of players, as navigating the halls is both easy and quick, especially as the halls are two wide instead of three, the time it takes to get places is most certainly at comfortable ease for low populations.

I do apologise if you feel offended by the action of this map taking ministation's place, however, while it may not be worth much you have my condolences and you're more than welcome to help with maintaining omega!

**Comment by Direthoughts** [comment]
@Okand37 Hi, big fan of omegastation (still got a ministation branch as my own repo for old times sake), and I can report it does actually play fairly well with ~ 6-9 players (yeah, small server.) albeit as long as there's an engineer. I assume that the fairly limited camera network is something that's just WIP — slightly limiting for AI. Also: is there any consideration of adding a gateway somewhere?

**Comment by Iamgoofball** [comment]
We obsoleted gateways with Ruins in Space.

**Comment by Direthoughts** [comment]
Oh, TIL. Fair enough.

**Comment by Okand37** [comment]
@direthoughts The camera network and bot navigation systems were something I hadn't finished implementing yet, but otherwise the map was ripe enough for testing. I'll go ahead and add a small room for the gateway for other servers that still have it active or want to use it.

**Pull request merged**
