### PR TITLE
Fixes mortar not deleting contents when grinding

### LINKED ISSUE #69966: Some material put in a mortar and pestle can be ground indefinitely
Reporting client version: 514.1588

## Round ID:
[190630](https://scrubby.melonmesa.com/round/190630)

## Testmerges:
- [Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)](https://www.github.com/tgstation/tgstation/pull/69115)
- [Tramstation: Modular Maintenance Insanity](https://www.github.com/tgstation/tgstation/pull/69000)

## Reproduction: Get a mortar and pestle, put in a bluespace crystal, continually grind it.
In testing I got like 60u of bluespace powder before i stopped. then i put a crystal in a grinder and grinding it gives me 40u.
As far as i know you can grind it forever to get rare chemicals like ground bluespace or whatever you could from grinding.

### PR DESCRIPTION
**Pull request by msgerbs**
## About The Pull Request
#69186 removed an if check and caused a runtime which prevents the mortar from deleting the grinded item if the grinded item doesn't have reagents inside:

`[03:01:54] Cannot read null.total_volume
Thrown by attackby (/obj/item/reagent_containers/cup/mortar/attackby) at _cup.dm, line 440`

This readds the check, preventing the runtime and restoring intended behavior.

## Why It's Good For The Game
Fixes #69966

## Changelog

:cl: VexingRaven
fix: Mortar and pestle no longer create infinite reagents
/:cl:

### CODE REVIEW

**Comment by calliophis-maculiceps** [comment]
close this shit man the mortar already sucks don't make it worse

**Comment by msgerbs** [comment]
>Literally infinite reagents for free
>This shut sucks

lmao

**Comment by Time-Green** [comment]
> close this shit man the mortar already sucks don't make it worse

jealous the mortar is grinding more bitches than you?

**Comment by calliophis-maculiceps** [comment]
i'm sorry but none of you have used the mortar ever, theres like 5 base chems that are "easy" to get with it in pityful quantities, its for example almost impossible to get carbon easily or oxygen/hydrogen since most things only give like 5 units of it AND additionally everytime you use it it drains a third of your stamina bar and takes like a whole second to grind the items in it so yeah it sucks "ohh infinite chems" wow great I can get some useless chems that can be found anywhere in 15 minutes of looking for stuff and grinding then waiting for stamina to regenerate so who the fuck cares about balance while this is already the weakest and most annoying way to get "chems"

**Comment by msgerbs** [comment]
> i'm sorry but none of you have used the mortar ever, theres like 5 base chems that are "easy" to get with it in pityful quantities, its for example almost impossible to get carbon easily or oxygen/hydrogen since most things only give like 5 units of it AND additionally everytime you use it it drains a third of your stamina bar and takes like a whole second to grind the items in it so yeah it sucks "ohh infinite chems" wow great I can get some useless chems that can be found anywhere in 15 minutes of looking for stuff and grinding then waiting for stamina to regenerate so who the fuck cares about balance while this is already the weakest and most annoying way to get "chems"

You realize it's literally just the reagent grinder from chemistry except you can craft it, right? It's not meant to be your replacement for a chem dispenser. None of your complaints are made any worse by this fix anyway. And it's not just base chems... You can get large amounts of plasma and bluespace with this, among other things.

**Comment by calliophis-maculiceps** [comment]
the main use of this is for ghetto chem, just make it break stuff on mats and mats only

**Pull request merged**
