### PR TITLE
Adds Ending Cinematic for Gang Dominations

### PR DESCRIPTION
**Pull request by Ikarrus**
hacket

### CODE REVIEW

**Comment by WJohn** [comment]
Sure, why not.

**Comment by Anonus** [comment]
It'd be even cooler if the screen was the color of the dominating gang, but ho god that'd be tons of work.

**Comment by optimumtact** [comment]
Hack the planet!

**Comment by GunHog** [comment]
The Malf APC screen? Come on, Ikky, put a little work into it! :(

**Comment by Cebasiz** [comment]
needs some gangster lingo or something

maybe some of the screens flash should be jargon or bragging

or something

**Comment by SconesC** [comment]
I guess?

**Comment by Aranclanos** [comment]
i don't like it ¯\_(ツ)_/¯

**Comment by vista-** [comment]
It'd be perfect if the screen had some sort of gang tag / graffiti sprayed on it.

**Comment by Iamgoofball** [comment]
>Hack the planet!

It needs to say this.

**Comment by CPTANT** [comment]
It would be so cool if the ending showed the station becoming a gangster paradise in some way.

**Comment by tedward1337** [comment]
https://www.youtube.com/watch?v=cpGbzYlnz7c ^

**Pull request merged**
