### PR TITLE
Adds logging of shuttle request reasons.

### PR DESCRIPTION
**Pull request by AnturK**
So we can have a list of dumbest reasons to call the shuttle somewhere.

### CODE REVIEW

**Comment by lzimann** [comment]
Add it to the feedback table instead, maybe.

**Comment by AnonymousNow** [comment]
I heartily endorse this message and/or product.

**Comment by nfreader** [comment]
I second feedbacking it! :D

**Comment by AnturK** [comment]
Done

**Comment by nfreader** [comment]
I don't wanna open a new issue for this, but these need to be concatenated better now that #29598 has been merged.

**Pull request merged**
