### PR TITLE
Tries to make Donut Station pretty alright maybe.

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

Does a whole bunch of things.

- Makes the ugly difficult to repair directional windows actually fulltile ones. Not quite sure if I got them all but I most definitely got most of them.
- Gives the map an actual cargo mail office rather than depositing people directly in to the recycling room.
3f40dd092b248f7f2f2ffbf9dfa66c9a
_If you get disposals shoved you're dropped here rather than some where in maintenance where you have to pray some one can come and rescue you should you not have access._
- Makes the recycling room actually escapable.
06a249e7d26fe063fb07246deb91208a
_The recycler was nudged over to make it actually possible to dive out of the way in event it's emagged rather than simply dying and the stacking machine has been moved out of the way to allow you to exit the loop with out breaking things down._
- Gave some civilian areas normal windows rather than the indestructible reinforced windows.
- Moved the AI upload out from maintenance.
c9dc63bdf3333bbe8a6fb27e41351e21
_Probably the most radical change was to rip the AI upload out from above the Captain's office in maintenance. Other than it the old vacant commissary was axed to make room for the primary tool storage room after the AI upload was moved out wards from maintenance. Don't get your hopes up though the yellow gloves are all fakes._
- Axed the vacant commissary but it was already sort of shoehorned in there and might as well not have been there in the first place.
- Shuffled many things around.
_Most notably the chapel is one tile taller to allow you to stand in the middle of the altar properly._
- A couple of maintenance oddities to find and explore.
_Make security panic with a plush Nar'Sie and a crayon rune._
- Birdboat lives where the old AI upload did.
d513ed3510e4754131d219ce6da7cd55
_Side note but we have a maintenance bar after the change._
- Gave all the heads privacy shutters.
- Replaced the patient's rooms with the secondary operating theatre.
64d4ce4893aa794dff1a05365aec57fd
_All the windows are shutterable and stuff for the privacy's sake when you're brain washing a person at the secondary operating theatre._
- There isn't a tile open to spess below a vault door any more.
- The internal Engineering ring is slightly harder to break in to with shocked grilles.
- ~~Some other things which you can probably see in the bot.~~ fuck you broken bot never ever working when i need you to.

~~((((Pictures soon maybe))))~~

## Why It's Good For The Game

Donut station's in a pretty unlikeable state with how radically different it is compared to all the other stations with it's lack of most basic necessities and feeling of rushed map design so I've decided to try and make it very slightly better.

## Changelog
:cl:
add: A whole bunch of things to make Donut Station a slightly more like able station.
del: The useless vacant commissary disguised as an empty room on Donut Station.
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
@MMMiracles

**Comment by zeroisthebiggay** [comment]
where the fuck the bot at i am too lazy to post pictures aaaa.

**Comment by actioninja** [comment]
broken right now

**Comment by zeroisthebiggay** [comment]
> broken right now

time to take pictures.

**Comment by MMMiracles** [comment]
- nope
- nope
- nope
- fine
- n o p e
- wasn't even hurting anybody why the hell would you just remove it?
- vague
- vague
- angry
- fine
- fine
- fine
- fine
- fine

the bigger changes (recycler, upload, ect) are things I'm pretty adamant on not changing. The recycler room has a comms to ask for help and the upload lacks any dangerous board.

**Comment by zeroisthebiggay** [comment]
> * nope
i still don't get the design behind the directional windows aside from "old spacemen feels for old spacemen map" as pretty much everyone i've talked to says they don't like them especially with the fact it's impossible to fix them perfectly unless you have a hand teleporter to escape
> * nope
you say it's quite literally designed to be inconvenient
but why though
> * nope
you literally need to be able to deconstruct a window and/or the stacking machine to leave and you're deposited directly in to the recycler _(conveyor belts don't even need to be on you're straight up tossed in to it)_ so if it's emagged you simply get to die with zero protest to it
> * n o p e
why is it even there though, one of the most secure sections of command guarded with an airlock or locked behind the bridge/ai core on every single map, just sitting in maintenance where a random assistant could waltz in to get tazed
> * wasn't even hurting anybody why the hell would you just remove it?
had to make room for primary tool storage after moving the ai core need to get pictures because the map bot is **fat**
> * vague
uhhhh a wire in maintenance is now straight and an apc isn't floating and the chapel is one tile larger to allow you to stand in the middle lane
> * vague
there's a crayon rune next to a narsie plush somewhere in maintenance
> * angry
**n o  y o u**
> the bigger changes (recycler, upload, ect) are things I'm pretty adamant on not changing. 
but why, it's literally consistent among every mainstream station, what's the purpose of having it so different for the sake of inconvenience?
even god damn pubby station with the big fuck off meteor sized chapel has these things right
> and the upload lacks any dangerous board.
isn't it like part of the fun to have the clown waltz in to the upload and upload tyrant/antimov/overlord? i think it's pretty lame that he has to yeet in to the vault to grab the one board he's looking for that isn't the basic freeform/quarantine/reset. i experimented taking the dangerous boards _(even the nondangerous ones were in there)_ out of the vault but if it really makes you happy i can toss them back in to there.

**Comment by MMMiracles** [comment]
you're trying to make the map like every other map and the whole point of the map is not to be the cookie cutter redesign of meta/box

stop

**Comment by CRITAWAKETS** [comment]
MMMiracles, just because something is standardized because its more convenient doesnt mean you have to be a deviant and just get rid of it.

You come from the Blockland School of MERP and DM design, where people make stuff inconvenient just to be different.

**Comment by zeroisthebiggay** [comment]
> you're trying to make the map like every other map and the whole point of the map is not to be the cookie cutter redesign of meta/box
> 
> stop

am i trying to make the map more in line with the maps people like? yes
do people enjoy playing on donut station because of how radically different in it's own funky way it is? judging by how fast people rush to i bored call shuttle and make the engine go scrungulo for the meme, admins running meme rounds when ever the map picker decides it's donut station time, and generally the loud **"AH FUCK IT'S DONUT STATION"** over common as soon as the round starts i'm going to have to hit you with a hard _"people aren't enjoying the map in it's current state"_
you can have a unique map design with the ring shaping and department layout, look at kilo station, it had all the marks of a "cookie cutter meta box redesign" but kept it unique and interesting with it's layout and core design philosophy

people like meta, box, delta, and pubby because they're **good maps by design**
people **don't** like donut, because of how radically different for the sake of being different it is from the maps people regularly play
i as a person really want to like donut like the rest of the maps in the pool but when the map is designed to be annoying just because it wants to be different from the regular rotation there's a point where it's just time to stop.

**Comment by MMMiracles** [comment]
when the community roundtable came up for the section on donut, the two main complaints were "i don't know the map so I don't like it" and "admins fuck with the round when the map gets chosen so i don't care to learn it". do you know how annoying it is to maintain a map that rarely gets chosen out of the meta swarm just to get memed on by admins because the few vocal shitheads feel the need to constantly voice their distate for the map they have to play for one round before going back to meta?

not fun, for me or those who actually enjoy the change of scenery once in awhile.

also every fucking time i've seen someone over comms go "oh NO DONUT" they've been an assistant every god damn time those fucking graySHITS

**Comment by zeroisthebiggay** [comment]
> when the community roundtable came up for the section on donut, the two main complaints were "i don't know the map so I don't like it" and "admins fuck with the round when the map gets chosen so i don't care to learn it". do you know how annoying it is to maintain a map that rarely gets chosen out of the meta swarm just to get memed on by admins because the few vocal shitheads feel the need to constantly voice their distate for the map they have to play for one round before going back to meta?
> 
> not fun, for me or those who actually enjoy the change of scenery once in awhile.
> 
> also every fucking time i've seen someone over comms go "oh NO DONUT" they've been an assistant every god damn time those fucking graySHITS

there was a roundtable?
perhaps consider sitting in on more when it actually rolls to see how many people both alive and dead actually dislike the map.
i think there's been one or two times i've seen the map not get completely and utterly demolished by round end due to mass bombings or engine loose even on _(secret)_extended rounds when admemes just spawn six wizards to end the round faster so people can go back to the liked maps.
there was one time where the round ended in peace i recall but it was because it was like on a dead pop presseth tide sybil but it also might just be because of how little it rolls, again, it's a very unpopular opinion to vote for the "unliked" map because of how much these "vocal" people have hated on it.
if people don't like a map they're going to cry and shout, then people are going to go in to the map with a bad first impression, see how different it is compared when compared to the maps they probably have played on most of their life time, and then promptly dismiss it, turning in to one of the "i don't like this map" people
i'm going to say it again but the layout is unintuitive, uninspired, and the station was born out of a meme for "lmao singulo station" and if you want people to start liking it at the very least make the map design purposefully likable rather than purposefully inconvenient for the sake of being different. it ain't fun to play on a map when the creator has designed it to be unlike every commonly accepted "good" map.

**Comment by MMMiracles** [comment]
i sit in whenever i see a round of the map active and i'm not busy, i'll actively ask deadchat about their criticism/comments on the map and what they might want to see changed. i even go as far as linking the feedback thread in ooc post-round, writing down comments to look at later since most people don't bother voicing their opinion outside of the game itself.

if you genuinely struggle with the map layout of a giant circle with every relevant department lining each other with directional signs at each major corner, then i honestly don't know what to tell you.

**Comment by Jessen21** [comment]
MMMiracles, dude, I've heard enough people saying they'd rather go to birdhouse than Donut, and Birdhouse doesn't even have ALL the facilities. They believe they can at LEAST build the place how they want there. We really shouldn't be trying to cling to how things are and embrace change if people really dislike it that much. If it continues to feel wrong, then we can readdress it and maybe revert some changes. and try something different.

No one ever got hurt trying to actually fix a situation like this.

**Comment by nicbn** [comment]
Only thing I disagree with mmm is the windows thing, the fulltile ones look nicer, have overlays for damage and are easier to build.

Other than that, yeah, you shouldn't tweak the design of all maps so that they play out the same.

**Comment by MMMiracles** [comment]
as long as i roam these 3-tile wide hallways i will not allow you to besmirch my precious donut

**Comment by MMMiracles** [comment]
the exact same thing can happen with like 30 seconds of prep work on every other map so i dont see the issue

**Comment by optimumtact** [comment]
conflicts

**Comment by optimumtact** [comment]
you have to do merge of tgstation master to remove conflicts, you can't just update your map

**Comment by zeroisthebiggay** [comment]
> you have to do merge of tgstation master to remove conflicts, you can't just update your map

hold on i'm being a r word and must accquire the chaos emeralds to increase my knowledge powers.

**Comment by zeroisthebiggay** [comment]
big brain moment i did it.

**Comment by zeroisthebiggay** [comment]
i'm a retard.

**Comment by zeroisthebiggay** [comment]
think i've unfucked all my mistakes but i'm fat.

**Pull request merged**
