### PR TITLE
Revert "Plane master handling + new chemical Rotatium"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#20707

### CODE REVIEW

**Comment by MrPerson** [comment]
I'm not making a case for doing or not doing this, but I would very much like to know which way you guys want to go before working more on using this feature.

**Comment by optimumtact** [comment]
I want to keep it in, but we can't if it's causing major visual bugs for the players. like #21099

**Comment by optimumtact** [comment]
I'd prefer to wait till we can confirm if a 511 latest client fixes the issue or not.

**Comment by ChangelingRain** [comment]
Planes have a bunch of neat uses but if they're causing hideous issues for some people we sssshouldn't use them.

**Comment by MrStonedOne** [comment]
For anybody affected: Open pager/hub (the main byond application where you log in) And click the white gear/cog icon in the top right and go to preferences (or press control+p). Go to games then make sure that "Use graphics hardware for displaying maps" is checked.

Reconnect to the game and that SHOULD fix it

**Comment by Dorsisdwarf** [comment]
rotatium is pretty trippy but that effect should definitely be applied to the Confused state instead

**Comment by MrStonedOne** [comment]
https://tgstation13.org/phpBB/viewtopic.php?p=220316#p220316 3 potention fixes to try.

**Pull request closed without merging**
