### PR TITLE
Replaces space ninja with a chrono-legionnaire

### PR DESCRIPTION
**Pull request by ghost**
(Thanks to Steelpoint for linking this image; the gun is not used however)

Sprites courtesy of Spheretech, from https://tgstation13.org/phpBB/viewtopic.php?f=11&t=2472&p=56862.

Replaces the space ninja's fluff, lore, and sprites with a Chrono Legionnaire. I'm not strong on the original plot of the game this references (that being, Red Alert 2 and 3), so I was purposefully vague. This 'legionnaire' has been transported in time (and subsequently gained amnesia) and recruited by the tech-loving Fadria Corporation who act much the same as the Spider Clan in their technology-loving and working for cash.

All relevant ninja icons have been replaced with Spheretech's legionnaire icons. The verb tabs are Chrono Equip and Chrono Ability rather than being the Ninja versions. SpiderOS is now ChronOS (a reference to mythology). There is no Eraser Gun, but rather the chronopack is an oxygen jetpack that the legionnaire starts off equipped with. It fits in the legionnaire's suit storage.

If one was to look at it from a purely mechanical standpoint, this PR is _no different_ from the original ninja except for giving them an oxygen jetpack instead of a CO2 one and removing the emergency tank from their suit storage, as well as giving them some new aesthetics and backstory. Also, some bugs in the code might have been fixed as I went through the files. Finally, the suit fully protects against radiation, both to be realistic and fit the backstory.

This has been thoroughly tested and is merge-ready. The only thing that I could not determine the status of was the energy net; however, the only change in this was the sprite. The memory, while it looks like it wouldn't work, it works fine.

This was primarily made to add some variety to the ninja as well as to use some of the sprites that Spheretech made.

Here's a few in-game images of the legionnaire.
http://imgur.com/a/jaOb7#0

If there's any problems with this let me know. I figured copyright isn't an issue because of the xenomorphs, but that's a can of worms I don't want to open here.

On a final note, I kept all the file paths as they were so I didn't have to edit 10000% more code.

### CODE REVIEW

**Comment by Steelpoint** [comment]
I doubt :cop: :e-mail: :arrow_right: will be a issue considering these are unique sprites.

Technically Chrono Legionnaires can only move around by teleporting, but they can still teleport so its a non-issue.

I found some good, easier to see, sprites from the thread here: http://i.imgur.com/Wrce3bA.png

**Comment by Xhuis** [comment]
I put those sprites in the original note, thank you for linking them.

**Comment by ike709** [comment]
>Also, some bugs in the code might have been fixed as I went through the files.

I don't see how any bugs could have been fixed, but I still like this PR. :+1: 

Also nice job on the Doctor Who reference in there, whether intentional or not. Extra :+1:

**Comment by Alek2ander** [comment]
What about the secrit speshul mode?

**Comment by Xhuis** [comment]
Kamikaze? That works too.
The super OP mode? That should work as well but I'm not sure how to trigger it (or kamikaze).

**Comment by paprka** [comment]
What about ninjas being connected to the spider clan and all that

**Comment by TZK13** [comment]
:-1: I prefer the aesthetic of space ninjas myself and that's all this really comes down to. I don't see how this provides any "variety" to the ninja when all it does is replace it, especially considering how space ninjas are certainly more unique to SS13 than this is. Also the Xenomorph copyright argument doesn't work here because the coderbus policy regarding that is the Xenomorphs were in the code that /tg/station built itself upon thus the onus isn't on them.

**Comment by Anonus** [comment]
This is bleh, it doesn't fix the problem of ninja being not actually that good at all, it just reskins it into a different, but still shit, suit.
:-1:

**Comment by optimumtact** [comment]
Why not both :dancers:

**Comment by Anonus** [comment]
This is bleh, it doesn't fix the problem of ninja being not actually that good at all, it just reskins it into a different, but still shit, suit.
:-1:

**Comment by tkdrg** [comment]
Yeah, the big issue with ninja isn't aesthetics, it's the implementation itself. I don't see how this addresses that problem.

**Comment by paprka** [comment]
NEW IDEA THAT I'VE HAD FOR 2 YEARS:

MAKE NINJA MODULAR, SO YOU CAN CHOOSE WHAT YOU SPAWN AS IN YOUR PREFERENCES, LIKE IF YOU WANT TO BE A SPIDER CLAN NINJA, A RED ALERT REFERENCE, OR A SPACE COWBOY BOUNTY HUNTER WITH SICK ASS DUAL REVOLVERS

**Comment by dannno** [comment]
^yeah

**Comment by Xhuis** [comment]
This is simply a reskin of the ninja. The modular thing is certainly a great idea, and the implementation certainly needs improvement. This just isn't the PR for those things.

Spider Clan gift event remains the same because I'm not eliminating the Spider Clan entirely. I have quite a few ideas for ninjas in mind but like I said this is not the PR for them.

**Comment by Nyvrem** [comment]
What I don't understand is that if they are highly advanced commandos from the future then why do they travel to the present to steal our technology?

**Comment by optimumtact** [comment]
I doubt this will get in if it's just a reskin. Maintainers only barely tolerate ninja as is

**Comment by Xhuis** [comment]
@Nyvrem In the fluff, this legionnaire is from the past that got sent into the future after a malfunction. It's left deliberately vague in itself. The only reason he's there is because the Fadria Corporation asked him to go there.

**Comment by pudl** [comment]
mmw this pr will lead to a huge argument and end in ninja's removal

**Comment by PKPenguin321** [comment]
holy shit what pap said we need space cowboys
other than that i disagree with this change because space ninja has lore and stuff backing it (which is all pretty cool) and this kinda kneecaps it
if the thing pap said with choosing what you are as a ninja gets coded then merge this into that

**Comment by Cheridan** [comment]
Closed for reasons brought up in comments

**Comment by JJRcop** [comment]
chronos legion may return in another form, but not related to ninja

**Comment by Steelpoint** [comment]
It would be interesting to allow people to pick one of several "ninja" subtypes and have unique aspects to them.

For example, making the Chrono Legionnaire be only able to move around by teleporting.

**Comment by Iamgoofball** [comment]
I demand rocketeers @JJRcop @Xhuis

**Pull request closed without merging**
