### PR TITLE
Fixed cooling in the Ice Box RD Server Room

### PR DESCRIPTION
**Pull request by jaw-sh**
## About The Pull Request
The RD server room on Ice Box was unique in being the only one that didn't really work. Meta and Delta use two vents (one set to scrub) to continually cool air. Ice Box used a single passive vent, which was not very effective.

This PR cools the RD servers by exposing the secure area to the mine. Instead of copying Delta/Meta, I've taken advantage of the Z-level gimmick of Ice to get natural cooling.

room1
underground

The underground area is empty, but the walls directly north and west are dangerous tiles, so there's a chance of something spawning directly next to it with no wall of protection.

## Why It's Good For The Game
The RD Server Room is the most important area of the map and it must work as expected.

## Changelog
:cl:
fixed: The RD Server Room on Ice Box now properly cools by exposing its floor to the outside.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
please note that if we ever make servers produce heat, this will cause untold amounts of atmos lag
but icebox already has this issue with the sm, so it's a minor concern on the overall

**Comment by TemporalOroboros** [comment]
@LemonInTheDark Didn't you fix that or did the PR stale out?

**Comment by LemonInTheDark** [comment]
Both #52493

**Comment by jaw-sh** [comment]
> please note that if we ever make servers produce heat, this will cause untold amounts of atmos lag
> but icebox already has this issue with the sm, so it's a minor concern on the overall
It's been live on my server since this PR came in and I've not had any noticeable issues. The servers do also create heat.

**Comment by LemonInTheDark** [comment]
What does the ms/active turf count of the atmos ss look like?

**Comment by jaw-sh** [comment]
This is on Ice Box 30 minutes in with 13 players and an active SM.
image

This is 2 minutes in with a single player.
image

**Comment by LemonInTheDark** [comment]
My life is a lie

**Comment by Cartographer-D** [comment]
I'm worried this PR will conflict with #54946 .

**Comment by jaw-sh** [comment]
If there's a merge issue I'll help with it. Shouldn't be a significant channel, as I didn't touch wiring at all.

**Pull request merged**
