### PR TITLE
removes free cargo items

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

cargo items except the spare crate thing now all cost at least 750 so you cant just get free money

## Why It's Good For The Game

https://www.youtube.com/watch?v=6-XrJHCLiHE

## Changelog
:cl:
balance: fixes cargo items that directly give you money when you sell them back/dont cost anything at all if you sell them back
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
make the crate subtype for these items worth 100 lol how hard is it

**Comment by Fikou** [comment]
> make the crate subtype for these items worth 100 instead of 500 lol how hard is it

really hard bro its imposibel

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/add74bee56cfde91602eb8ee28e3cae5959bc4f6/code/modules/shuttle/supply.dm#L130

to
/obj/structure/closet/crate/secure/reallycheapsubtype/

**Comment by ATH1909** [comment]
> make the crate subtype for these items worth 100 instead of 500 lol how hard is it

Make them worth 0, and also make them not drop any metal when destroyed.

**Comment by Tlaltecuhtli** [comment]
remove the 500$ barrier, up the handling fee to 15% so its easier to buy cheap items

**Comment by TheMidnightRose** [comment]
You could just make sealed wodden crates with access restrictions, it gets opened and falls to pieces into wood.

**Comment by Cartographer-D** [comment]
> 
> 
> You could just make sealed wodden crates with access restrictions, it gets opened and falls to pieces into wood.

Wood is expensive in space!

**Comment by Ryll-Ryll** [comment]
#51216 is an alternative to this

**Pull request closed without merging**
