### PR TITLE
Add holodeck map: Kitchen

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-adds a kitchen holodeck map
-adds holodeck map datum for kitchen

## Why It's Good For The Game
-people will be encouraged to use the food systems more, and they can also practice here
-also a clean kitchen to use if the normal kitchen explodes like medbay has, or to use if the chefs of the shift are just bad

## Changelog

:cl:
add: Added a holodeck map: Kitchen
/:cl:

Pics outdated, will update tomorrow
In mapper:
image

### CODE REVIEW

**Review by tralezab — CHANGES_REQUESTED** [review]
You need to at least make it so the ingredients are gone, because you're letting people spawn holographic ingredients and make real food from them, only to despawn and respawn the ingredients to do again

**Comment by tralezab** [comment]
My non review stance is that I don't like the idea of spawning a kitchen, it really devalues the chef when anyone can head to dorms and cook their own food. We have maintenance rooms that have kitchen machinery and I liked that as an alternative more than loading up a new kitchen

I have this creeping feeling that I'm overreacting and it won't see as much use when you remove ingredients so I'm not blocking it or anything, just voicing my concerns

**Comment by Farquaar** [comment]
> 
> 
> My non review stance is that I don't like the idea of spawning a kitchen, it really devalues the chef when anyone can head to dorms and cook their own food. We have maintenance rooms that have kitchen machinery and I liked that as an alternative more than loading up a new kitchen
> 
> I have this creeping feeling that I'm overreacting and it won't see as much use when you remove ingredients so I'm not blocking it or anything, just voicing my concerns

As a fairly experienced chef player, I'm curious to see if anything interesting comes of it. Personally, I don't see what how this takes away from the chef's value any more than the existence of vending machines or microwaves/donk-pockets in department break rooms. 

If chef devaluation ends up being a problem, I'm sure it can be removed without much fuss.

**Comment by Farquaar** [comment]
Unrelated question: Can you explode the holo-microwaves by putting metal in them?

**Comment by Mooshimi** [comment]
> Unrelated question: Can you explode the holo-microwaves by putting metal in them? If so, is there any chance of breaching a window on certain maps?

I put a fork in both and they didn't explode, just busted with a spark effect.

**Comment by Farquaar** [comment]
Second question: When you removed ingredients, did you also remove the oil in the deep fryer? The deep fryer adds reagents to everything it fries, so it could unintentionally act an infinite source of nourishment.

**Comment by Mooshimi** [comment]
> Another question: When you removed ingredients, did you also remove the oil in the deep fryer? The deep fryer adds reagents to everything it fries, so it could unintentionally act an infinite source of nourishment.

No, but I also don't think this is an issue. If it makes any sense how I say it, I don't think people will specifically come to this fryer just to fry things to eat for the infinite grease. Deep fryers are mostly unused in the normal kitchen, especially with the addition of things like the oven and the deep frying not being tasty anymore. It actually downright gives a mood debuff because it's gross to eat random deepfried items, I think.

**Comment by Fikou** [comment]
people being able to ignore the chef and getting a full non-ghetto kitchen loadout without any effort as long as they have ingredients seems dumb to me

**Comment by Farquaar** [comment]
> 
> 
> > Another question: When you removed ingredients, did you also remove the oil in the deep fryer? The deep fryer adds reagents to everything it fries, so it could unintentionally act an infinite source of nourishment.
> 
> No, but I also don't think this is an issue. If it makes any sense how I say it, I don't think people will specifically come to this fryer just to fry things to eat for the infinite grease. 

You'd be surprised.

>
>Deep fryers are mostly unused in the normal kitchen, especially with the addition of things like the oven and the deep frying not being tasty anymore. 

That's not what I see in-game. The other week I saw a chef exclusively serving up fried iron and rebar.
>
>It actually downright gives a mood debuff because it's gross to eat random deepfried items, I think.

Gameplay issues aside, it doesn't make sense from a logical perspective. How come you can create virtual holo-oil out of thin-air, add it to a piece of food, and then take it with you outside the holodeck? No other matter in the holodeck works that way.

**Comment by Mooshimi** [comment]
> > Deep fryers are mostly unused in the normal kitchen, especially with the addition of things like the oven and the deep frying not being tasty anymore.
> 
> That's not what I see in-game. The other week I saw a chef exclusively serving up fried iron and rebar.
> 
"The other week" kind of supports my point, but
> > It actually downright gives a mood debuff because it's gross to eat random deepfried items, I think.
> 
> Gameplay issues aside, it doesn't make sense from a logical perspective. How come you can create virtual holo-oil out of thin-air, add it to a piece of food, and then take it with you outside the holodeck? No other matter in the holodeck works that way.

I get what you mean with this, so I changed it.

**Comment by wesoda25** [comment]
image
God PLEASE make this happen

**Comment by wesoda25** [comment]
By that I mean give them holographic ingredients, make all food created holographic and worth 0 nutrition. THE FUTURE IS NOW

**Review by tralezab — APPROVED** [review]
my complaints were handled, if a maptainer approves they can slap the merge

**Comment by ExcessiveUseOfCobblestone** [comment]
I’m not a fan of holodeck being used to act as second departments that can be used to have effects outside the holodeck.

Machinery in the holodeck is free from any sort of forensics if needed and it displaces the original department by encouraging people to just do X themselves in the holodeck, be it medical and now chef.

**Comment by tralezab** [comment]
kinda what i said too

**Comment by Zytolg** [comment]
> I’m not a fan of holodeck being used to act as second departments that can be used to have effects outside the holodeck.
> 
> Machinery in the holodeck is free from any sort of forensics if needed and it displaces the original department by encouraging people to just do X themselves in the holodeck, be it medical and now chef.

On account of this being a valid point, if this PR doesn't make it in as is due to this reason, then I think there is merit in splitting this up into 2 smaller competition themed kitchens with a judge tasting area. Cook-offs are a thing and I believe that enabling that at the click of a button instead of the intricacies of construction would be of benefit to the station and crew. 

I'm already a fan of the current PR and Expanding the Holodeck to include useful amenities is not at all a bad idea (as long as things aren't stepping over what's already a holodeck thing).

**Comment by tralezab** [comment]
...amenities that jobs already offer, just without the pesky person actually doing the job. that's the nagging feeling behind the pr

**Comment by Maurukas** [comment]
I'm feeling Cobby and Arm here. If this were to add a maint kitchen this well equipped, the answer would be no. This sort of goes even further than that, in that the holodeck isn't even behind maint access, it's a public area, accessible from the start of the round.

The kitchen is already a de-facto AA zone unless the chef closes it off, and we have the entire CQC mechanic around intrusions into it. I don't think we should map with a 'well what if the department is incompetent' mindset.

**Pull request closed without merging**
