### PR TITLE
Resprites the police baton

### PR DESCRIPTION
**Pull request by JosephJomama**
## About The Pull Request

De-souls the detective's baton from a puny little twig into the THICK whackin' stick that it always deserved to be. 

Old:
image

New: 
image

On floor:
image

In-hand:
image

In bag: 
image

Mid-whackin':
image

## Why It's Good For The Game

Replaces an old, low-quality sprite. Bonus: now you can actually click on the baton when it's on the ground.

## Changelog

:cl:
imageadd: The police baton has been resprited into a handsome beatin' stick worthy for a lone-wolf detective who doesn't play by the rules to whack perps with.
/:cl:

### CODE REVIEW

**Comment by KittyNoodle** [comment]
it looks too bright

**Comment by DrDiasyl** [comment]
You stole it, you

**Review by Imaginos16 — APPROVED** [review]
Getting out of my break a little earlier than usual to approve this! Absolutely excellent work!

**Comment by notfrying1pans** [comment]
i liked it darker

**Comment by Serxule** [comment]
a bit too bright, looks like a stick

**Comment by Twaticus** [comment]
i wouldnt say too bright, its more of an orange tinted wood rather than the dark wood from before. but thats fine. if it ends up being too insanely tinted in gameplay for some reason then it can always be revisited again and toned down. but as of right now its perfectly fine.

**Comment by PKPenguin321** [comment]
top outline is too dark, looks like pillow shading

**Comment by JosephJomama** [comment]
Due to popular demand, I have made the baton a bit darker. Updating the PR body now

**Pull request merged**
