### PR TITLE
Makes wizards nyanbinary

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
It's april in New Zealand.

## Why It's Bad For The Game
Clearly requested by MSO
MSOposting

## Changelog
:cl:
fix: wizards are now nyanbinary
/:cl:

### CODE REVIEW

**Comment by interestingusernam3** [comment]
/tg/station speedclose any%

**Comment by Kylerace** [comment]
i do nyat like that

**Comment by notfrying1pans** [comment]
😳

**Comment by interestingusernam3** [comment]
😳

**Pull request closed without merging**
