### PR TITLE
Sanguirite (coagulant) recipe!

### PR DESCRIPTION
**Pull request by SSensum13**
## About The Pull Request

This PR adds Sanguirite (coagulant) recipe. The recipe is not too easy and not too hard.
Also Sanguirite (coagulant) overdose threshold has been changed to 10 units, so people will not be able to pump themselfs with it.

## Why It's Good For The Game

It would be nice if players will be able to obtain Sanguirite (coagulant) without medipens.

## Changelog

:cl:
add: Added a recipe for Sanguirite (coagulant)!
balance: Sanguirite (coagulant) overdose threshold has been changed to 10 units.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
I'd recommend making the overdose treshhold something like 8 to prevent 100% purity sanguirite from triggering the overdose treshhold at just 5u.

**Comment by carlarctg** [comment]
Epipens aren't meant to risk overdoses if two are injected into someone simultaneously, to prevent epipenning from harming someone. This looks like it'll screw that up.

**Comment by HWSensum** [comment]
i changed overdose threshold to 10 units, so it should be good now.

**Comment by ATH1909** [comment]
doesn't this kind of obsolete the weaker kind of sangiurite that you can get from a recipe involving banana peels?

**Comment by ZephyrTFA** [comment]
Sanguirite is not intended to be player producable due to its ability to seal all wounds almost instantly due to its incredibly high wound heal factor.
I am not interested in the PR at this point in time; if in the future the chem becomes less powerful it may be considerable.

Use banana peels for a wound healing chem.

**Pull request closed without merging**
