### PR TITLE
Removes fetish content from the autodrobe

### PR DESCRIPTION
**Pull request by Iamgoofball**
come on

you can't be more obvious than this

just go elsewhere for your fucking fetish porn

there's a server for this shit

just go to citadel, we don't want or need you to be doing this shit here

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
good pr, speedmerge

**Comment by Armhulen** [comment]
jabroni can stay though it's only ironic fetish material

**Comment by KorPhaeron** [comment]
These actually have some level of gameplay function though

**Comment by Armhulen** [comment]
^^ wizards cannot cast spells with these on you could in theory use it to arrest a wizard.

**Comment by Iamgoofball** [comment]
ballgagging the wizard hasn't been a viable tactic for years

**Comment by sawrge** [comment]
lol

**Comment by MoreRobustThanYou** [comment]
@Iamgoofball you do realize, wizards cannot cast spells if they can't talk, right?

**Comment by kevinz000** [comment]
lol goof mad is best goof

**Comment by Kraseo** [comment]
lol

**Comment by Iamgoofball** [comment]
>when people corrupt the game and justify it in post as "makes goof mad"

**Comment by The-clown-known-as-Pepe** [comment]
image

**Comment by optimumtact** [comment]
If you keep this up we will take action.

**Comment by Iamgoofball** [comment]
Keep what up? Removing fetish shit? Can you chill?

**Comment by optimumtact** [comment]
You are on thin fucking ice my friend

**Comment by Iamgoofball** [comment]
Someone tried to use the fact these were in the autodrobe to add fetish collars to the autodrobe. Don't be dumb.

**Comment by Firecage** [comment]
I suspect oranges™ might be referring to you repeatedly making Meme PRs and Joke PRs. And attention seeking PR's like this one.

**Comment by Iamgoofball** [comment]
Thin ice for doing what? Running a headmin campaign on trump jokes, arguing with remie about cat ears until she exploded at cheridan then attempted a literal coup? Or is it because I helped reveal literal admin abuse that a maintainer was performing?

**Comment by Iamgoofball** [comment]
Oh, don't forget stealing memos, such a horrible act, not like we have @memostats or anything

You people are being childish as fuck over a video game. I make PRs like this because I honestly believe the blindfold and muzzle shouldn't be in the autodrobe. Of course people get mad. Everyone gets mad over balance.

**Comment by Iamgoofball** [comment]
I've done nothing to the point you have to invent reasons to get rid of me, because you'd catch flak for the real reason, which is you don't agree with my vision of game design and aesthetic.

**Comment by optimumtact** [comment]
Your vision of game design and aesthetic is irrelevant, it doesn't match ours, and you continually make pr's that attract only negative attention.

You haven't contributed anything decent that got finished in a long long time, to the point where you represent a net negative drag on this codebase and I will push to have you removed.

**Comment by Iamgoofball** [comment]
I haven't finished projects like dwarves, goap, and animal farm because they would of been shit in the long term. Don't bring closed features into this. And you act like banning me would change anything, when in fact someone will just replace me. 

Of course negative attention occurs when you nerf shit like Hulk. We didn't ban hornygranny for lowering move speed.

**Comment by optimumtact** [comment]
That's because he consulted with the maintainers first before doing it.

**Comment by Iamgoofball** [comment]
Shoving problems under the rug doesn't make them disappear and you know it. Disappearing people who reveal these problems and publicize them after repeatedly being ignored when trying to handle issue quietly is awful.

**Comment by Iamgoofball** [comment]
I don't get to consult with the maintainers and you know it.

**Comment by optimumtact** [comment]
There isn't a problem, you're making a storm in a teacup and it's frankly disappointing.

Also you know perfectly well you can pm the maintainers both in irc, on the forum and chat to them in discord.

DOnt' act lik you have no avenues just cause joan banned you from irc.

**Comment by RemieRichards** [comment]
keep up the good work fruitboi

**Comment by Iamgoofball** [comment]
Do you really think they'd actually reply? Because I seriously doubt it.

**Comment by Iamgoofball** [comment]
Oh hey, the coup master is here.

**Comment by Firecage** [comment]
Perhaps if they don't reply, that might actually point towards a different problem. Towards yourself. Perhaps you should take a break from Github for a few months, possibly a year, and only play on the server without repeatedly shitposting in OOC about donations and your new server. Perhaps then you might cool down and be less toxic to the community.

**Comment by RemieRichards** [comment]
@Iamgoofball considering I'm getting/got what I wanted, top lols.
- Cheridan to not be headcoder - CHECK
- You gone/on a tighter leash - I smell citrus

**Comment by Iamgoofball** [comment]
>repeatedly shitposting in OOC about donations and your new server.

what new server lmao

**Comment by Iamgoofball** [comment]
cheridan isn't gone though remie, check the org

**Comment by Thunder12345** [comment]
He's no longer headcoder though

**Comment by Bawhoppen** [comment]
Goof-"I posted goatse on the github"ball

**Comment by Iamgoofball** [comment]
goatse is art

**Pull request closed without merging**
