### PR TITLE
Tesla now dusts people on tile it jumps to

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
fix: The tesla now dusts all carbon mobs on the turf that it moves to,
grounding rod or no.
/:cl:

Remember, the tesla already dusts you if you walk into it, this just makes it more consistent.
- Also made the miniball spawn a timer.

### CODE REVIEW

**Comment by InsaneHyena** [comment]
Finally, baby's first engine is now less horrible. Should be removed alltogether, though.

**Comment by InsaneHyena** [comment]
And Gun Hog thumbsdown as if on cue.

**Comment by optimumtact** [comment]
Dust to dust, ashes to ashes

**Comment by Iamgoofball** [comment]
@InsaneHyena no

**Pull request merged**
