### PR TITLE
Adds batting

### PR DESCRIPTION
**Pull request by JJRcop**
:cl: JJRcop
add: You can now hit someone with a bat while aiming at the head, eyes or mouth to give them a friendly bat
/:cl:

Hitting a person with a bat while aiming at the head, eyes or mouth will not give them a bat instead

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
I was fucking hoping this would involve ghosts betting shit but you let me down you let us all down

**Comment by Cheridan** [comment]
i don't get the joke? this would hamper usability a lot

**Comment by Thunder12345** [comment]
It's a meme response to oranges closing my headpat PR

**Comment by Kraseo** [comment]
>i don't get the joke? this would hamper usability a lot

who the fuck fights with help intent

**Comment by ChangelingRain** [comment]
Denied
bats aren't friendly

**Pull request closed without merging**
