### PR TITLE
catgirl claws :)

### PR DESCRIPTION
**Pull request by imsxz**
About The Pull Request

Felinid only genetic trait that gives the user extendable and retractable claws.

someone should add a sprite lol
Why It's Good For The Game

Felinids get a bit more ways to stand out without it being some garbage people are going to pointlessly argue over like chocolate, claws are super dope
Changelog

🆑
add: New mutation: claws!
/🆑

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Suds
Here's some soap, clean off all that sin

**Comment by Jared-Fogle** [comment]
did you get maintainer approval for this

**Comment by IndieanaJones** [comment]
Felinids should be made a human cosmetic subrace as they're cosmetically extremely similar to humans and don't have a unique enough design to warrant development time.

**Comment by imsxz** [comment]
ive hit a bit of a roadbump i dont have write access to the branch so i cant fix the merge conflicts

**Comment by imsxz** [comment]
> 
> 
> Opinion: Felinids should be made a human cosmetic subrace as they're cosmetically extremely similar to humans and don't have a unique enough design to warrant development time.

they literally were like this in the past you fucking zoomer guess what change sucks bitch

**Comment by tralezab** [comment]
Well I guess I'll fix that merge conflict you gave ME imsxz 🤥

**Comment by imsxz** [comment]
i knew you'd be there for me love you babe

**Comment by ArcaneDefence** [comment]
expressive-cat-nana-1-12-5f16cffd63d99__700

**Comment by Jared-Fogle** [comment]
did you get maintainer approval for this

**Comment by imsxz** [comment]
@Twaticus hey can i add catgirl claws to /tg/station

**Comment by imsxz** [comment]
@kriskog @ExcessiveUseOfCobblestone hey can i add catgirl claws to tgstation

**Comment by TheFakeElon** [comment]
didn't this get PRd a few months ago

**Comment by tralezab** [comment]
>Opinion: Felinids should be made a human cosmetic subrace as they're cosmetically extremely similar to humans and don't have a unique enough design to warrant development time.

IM SORRY, DID YOU SAY WARRANTING DEVELOPMENT TIME ON AN OPEN CONTRIBUTION REPOSITORY?

**Comment by imsxz** [comment]
> 
> 
> didn't this get PRd a few months ago
no this is original content

**Comment by optimumtact** [comment]
> 
> Opinion: Felinids should be made a human cosmetic subrace as they're cosmetically extremely similar to humans and don't have a unique enough design to warrant development time.

Uh, they are? The only reason they have a species datum is for code cleanliness

**Comment by MrDoomBringer** [comment]
Hmm, let me go ahead and get my friend Cobby to weigh in on this

**Comment by ExcessiveUseOfCobbIestone** [comment]
Hi @MrDoomBringer! Yes, I completely approve of the PR. Good work on this @imsxz

**Comment by MrDoomBringer** [comment]
Wow that's really good to hear. Oranges can we go ahead and get a merge now?

**Comment by optimumtact** [comment]
sage

**Comment by tralezab** [comment]
@MrDoomBringer Hey, friend! Give me a second, I want to help my good friend @imsxz (Who, may I add, perhaps forgotten to let me know he was going to revive this) resolve his merge conflicterinos! :)

**Comment by Pugie** [comment]
16 brute.
I assume they can be whetstoned.
Merge and add multi use whetstone to uplink also add foxgirls.

**Comment by MrDoomBringer** [comment]
@optimumtact i don't think that's how you're supposed to use 'sage'

**Comment by optimumtact** [comment]
sage

**Comment by ExcessiveUseOfCobblestone** [comment]
> Hi @MrDoomBringer! Yes, I completely approve of the PR. Good work on this @imsxz

lol

**Comment by wesoda25** [comment]
Honestly make up your minds, either remove catgirls or make them a unique species. Take them out of this stupid fucking state of limbo which only justifies further arguments for removal.

**Comment by MrDoomBringer** [comment]
Honestly make up your minds, either remove catgirls or make them a unique species. Take them out of this stupid fucking state of limbo which only justifies further arguments for removal.

**Comment by optimumtact** [comment]
no

**Comment by wesoda25** [comment]
lame baby coward

**Pull request closed without merging**
