### PR TITLE
Adds a communication remote that can send custom messages to some nanite programs

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Adds a new device, the nanite communication remote, which can be built from any protolathe once Basic Nanite Research is completed.
The Skull Echo, Forced Speech, and Hallucination programs can now be signaled by this new device to receive custom messages, instead of having to set them manually every time.
To do so, these programs must be set with a Comm Code, which will have to be signaled by a comm remote with the same Comm Code. A Comm Code of 0 is not signalable by remotes and will only work in the old way. If instead you want the program to be only activatable by remote, you must set the trigger code to 0.

## Why It's Good For The Game

Makes these programs more elastic in use, allowing for example nanite-delivered private communication via Skull Echo, or actively messing up conversations with forced speech.

## Changelog
:cl:XDTM
add: Added a new device, the nanite communication remote, which can be used to send custom messages to message-based nanite programs.
add: Comm remotes use separate Comm Codes: for a message to be received, the signal's comm code must be the same as the program's.
/:cl:

### CODE REVIEW

**Comment by XDTM** [comment]
I can't tell why the test is failing

**Comment by optimumtact** [comment]
Power Crepe

**Comment by RaveRadbury** [comment]
Add it to modular PC's rather than making it it's own device.

**Comment by XDTM** [comment]
I didnt get a notification about the conflict, if you reopen it i'll fix it

**Comment by XDTM** [comment]
Conflict fixed

**Pull request merged**
