### PR TITLE
ethereal cell is now stored in contents instead of nullspace

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

ethereal cell is now stored in contents instead of nullspace

## Why It's Good For The Game

i mostly made this because i realized that the recharging function of relics doesn't actually work on these, and i found out it's because this isnt in contents but nullspace

seems kind of lame for a cool interaction i hoped for (ethereal charging via relic) and possibly other interactions in the future as well

it might cause a disaster somehow. but let's yolo it and revert if it causes anything awful

## Changelog

:cl:
fix: The recharging relics now work on ethereal cells.
balance: EMP now affects ethereal's hunger.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
It's worth noting that emps would starve ethereals with this. I don't know the biology of ethereals so I don't know whether this would make sense or not. Might want to make the cell emp proof if you don't want that behaviour.

**Comment by MrMelbert** [comment]
Solvable by giving Ethereal hearts EMP protect contents element

**Comment by carlarctg** [comment]
losing nutrition to emp makes so much sense why would wr want that

**Comment by CRITAWAKETS** [comment]
reminder explosions can just destroy some stuff sometimes. you might wanna test to see if getting nuked in the face won't cause weird null issues

**Pull request merged**
