### PR TITLE
Add a config option for allowing buying shuttles

### PR DESCRIPTION
**Pull request by Cyberboss**
@coiax

### CODE REVIEW

**Comment by coiax** [comment]
Also make an admin verb to toggle it.

**Comment by KorPhaeron** [comment]
This is pretty redundant. We already have a config for this

**Comment by Cyberboss** [comment]
Wait, then why is this a problem @coiax? Just varedit the config.

**Comment by coiax** [comment]
No, there's a config for disabling individual shuttles, not disabling the whole system...

**Comment by KorPhaeron** [comment]
So just turn of all the shuttles? Config file and admin verbs are both bloated already

**Comment by Cheridan** [comment]
kors right, you can just emulate this by disabling them all

**Pull request closed without merging**
