### PR TITLE
Adds proto-nitrate and anti-noblium gas experiments. Experimental tools will require proto-nitrate experiment. Advanced weapons will require anti-noblium experiment.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
Adds proto-nitrate and anti-noblium gas experiments. Engineering partner will accept proto-nitrate gas experiment. Experimental tools will require proto-nitrate gas experiment. Advanced weapons will require anti-noblium gas experiment.

Moves botany gene shears to botanical engineering node, so it isn't restricted by the experiments.

## Why It's Good For The Game
Experimental tools has a massive impact on the round once researched. They make construction, deconstruction, and breaking into areas significantly easier, enabling greytiders to get into restricted areas without any effort. Due to the high impact to the round, and since they're upgrades to regular tools, people that aren't doing toxins shouldn't be able to get them so consistently.

Advanced weapons are an advanced luxury, so it might as well require an advanced gas experiment.

## Changelog

:cl:
add: Adds proto-nitrate and anti-noblium gas experiments.
balance: Engineering partner will also accept proto-nitrate gas experiment.
balance: Experimental tools will require proto-nitrate gas experiment.
balance: Advanced weapons will require anti-noblium gas experiment.
balance: Botany gene shears will require botanical engineering tech node instead of advanced tools.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
are you fucking kidding me right now ***this makes the problem worse***

congrats you've gated even more of the station behind atmos

**Comment by Pickle-Coding** [comment]
What does it gate? Experimental tools are just better tools that do the job faster, and advanced weapons are just tools to kill faster.

**Comment by Sylphet** [comment]
Restricting experimentals is cool and good, but oh my god not behind atmos please. It is such a minority of the playerbase that even knows how to do atmos, and its content is already painfully boring. It would be better gated by deconstructing an industrial slime, fitting making tools better thematically than... gas magic, and still achieving the end goal of making experimentals more rare.

**Comment by Pickle-Coding** [comment]
I have moved the gene shears to botanical engineering tech node, as it does something that can not be replicated by basic tools, and would not want to gatekeep that behind an atmos experiment.

**Comment by Muffindrake** [comment]
In the weeks since T4 lasers were locked behind a HN experiment, the experiment was done, according to my generous estimate, three times. Enough is enough.

**Comment by Pickle-Coding** [comment]
Should I put the med nodes into a separate new tech node?

**Comment by Nistishere** [comment]
If people don't to the T4 lasers experiment, what makes you think they will do this experiment that is even more annoying to do? What's the end-goal here?

**Comment by Pickle-Coding** [comment]
To make experimental tools more rare.

**Comment by Nistishere** [comment]
> To make experimental tools more rare.

There is a wide gap between "rarer" and "practically non-existant".

**Comment by CuteTuret** [comment]
I seen assistants hack doors open faster than the jaws can pry them, one could argue that this would make deconstructing r-walls somewhat faster, but not nearly enough to grant a tider a huge window of opportunity, not only that, they are tiders, they'll just find another way (thermite?). This change would only hurt engineers, y'know the people that have an actual use for the advanced tools.

**Comment by necromanceranne** [comment]
> On that note, what node gates advanced medical tools and if they're gated behind atmos stuff would it make more sense to gate them behind something more medical in nature?

Advanced tools also include the medical tools.

**Comment by Pickle-Coding** [comment]
Engineers can make the gas and bring it to toxins.

**Comment by CMDR-Gungnir** [comment]
> Engineers can make the gas and bring it to toxins.

We've already seen with the Hyper-Nob that they won't.

**Comment by D4C-420** [comment]
> Engineers can make the gas and bring it to toxins.

Atmos does gasses. Engineering does not actually have access to atmos and vice verse (still won't stop players from just hacking their way into both but still). Also making proto-nitrate at the moment is pretty much only viable via HFR which is a whole project in of itself. Also I'm aware that there is a pr to make it so making anti nob can be done via electrolyer but unless that is merged the only way to do it is with an HFR which is again a hole project unto itself and getting antinob in any real amounts can be a challenge. 

Finally its just boring to make the same gasses over and over again escpeiclly when they can take upwards of 30-40 minutes to make assuming you do nothing else.

**Comment by Draggeru** [comment]
Stop putting shit behind Atmos.

**Comment by Fryzzie** [comment]
locking science behind high end gases that can take newer atmos players multiple rounds just to understand and obtain is not exactly friendly to people trying something new

**Comment by Pickle-Coding** [comment]
I'm going to clear up some confusion.

Experimental tools aren't a mandatory thing scientists have to go for every round, and isn't expected for a new player. New people doing toxins can start of with the simpler experiments like bz before trying to unlock the goodies.

**Comment by CMDR-Gungnir** [comment]
> I'm going to clear up some confusion.
> 
> Experimental tools aren't a mandatory thing scientists have to go for every round, and isn't expected for a new player. New people doing toxins can start of with the simpler experiments like bz before trying to unlock the goodies.
> 
> Experimental tools and advanced weapons do have a high impact on the round, but are not necessary to do your job. They allow you to do it faster, but are not required. Experimental tools will make construction more efficient, but you do not need them to build a shuttle, repair a department, or make a maintenance fortress. Not much actual gameplay gets gatekeeped behind these tools, they just make it a little more covenient and faster.
> 
> The high impact in the round is mostly the jaws of life causing tiders to break into areas easier.

Yes, and Tiders will always find a way to Tide. If they can't Jaws, they'll just keep hacking (which they CAN do faster than Jaws, mind you) or they'll make Thermite.

**Comment by LemonInTheDark** [comment]
I don't want to hide more things behind the more complex gases right now. The reason to do it would be to force a test of atmos's usability, but we've accomplished that already. Perhaps in future, but not at the moment.

I'd be alright with less complex gases and less impactful nodes though. If you're interested in that, you should talk to vin, I think he has a few picked out.

Insert rant about CE's tools here. End rant.

**Comment by nikothedude** [comment]
If the problem is with jaws of life, why restrict everything else? Just seperate jaws of life into it's own tech node or something, or nerf the prying further. 

Not like it really matters. You can do what the jaws can do faster with a screwdriver, multitool, crowbar, and a bit of luck. Not to mention jaws of life actually damage airlocks, while hacking doesn't.

**Pull request closed without merging**
