### PR TITLE
Converts personal crafting to a TGUI interface.

### PR DESCRIPTION
**Pull request by RemieRichards**
## Showcase:

<B>All recipes:</B>
all_recipes
<B>Craftable only:</B>
craftable_only
<B>Search Filter:</B>
filter
<B>Busy Page because how else am I to display this nicely:</B>
busy_page
## CURRENT ISSUES:
- <del>The "Food" tab of recipes causes an error within tgui:</del>
- <del>Conflicts with the crayon tgui PR that was recently merged, fixing this in a moment.</del>
- <del>Conflicts with the ChemMaster tgui PR that was recently merged</del>

### CODE REVIEW

**Comment by Bawhoppen** [comment]
idk it seems like too much, the old one was just fine
what would be cool is if you showed images of the items though

**Comment by ike709** [comment]
images of the items would be cool but definitely isn't necessary

this is some good shit

**Comment by GunHog** [comment]
Green/Red fonts for present/missing items for a select recipe would also be helpful, if you that is possible, RR!

**Comment by Iamgoofball** [comment]
This is a big request but can you make it show icons of the finished product, and icons for the recipe components? Just make reagents use their reagent color or a beaker with a colored filling for that

**Comment by RemieRichards** [comment]
@GunHog the way data is passed around currently would require me to colour it on the DM side, which I'm not 100% sure how to do correctly (I could do spans, but most of our coloured ones come bundles with other effects, might be ok to use DANGER though, I could also use <font> but that's deprecated and shouldn't be used) I'll have a look, but no promises.

**Comment by optimumtact** [comment]
You probably need to do some encoding/url_necoding on the recipe names before they're sent to the tab, as that's likely what's killin the js

**Comment by neersighted** [comment]
Hmm I'm hesitant to sign off on this if the backend hasn't been majorly refactored. Also you're using some more advanced, undocumented features of tgui, so ping me on IRC if you have questions. I'll take a look tomorrow when I have a little more time. 

Looks really good though! :+1:

**Comment by xxalpha** [comment]
Does the search look in all tabs or just the one you're in?

**Comment by pudl** [comment]
tgui blows!

**Comment by pudl** [comment]
is it pronounced t-gooey or t g u i

**Comment by neersighted** [comment]
Tee Gee You Eye in my head, but I officially allow you to pronounce it however you like.

**Comment by RemieRichards** [comment]
@xxalpha same tab only.

**Comment by RemieRichards** [comment]
I found the offending character, a non-ascii A letter used to spell Mammi exactly as the finnish would, but it killed tgui so I had to remove it.

Sadly I couldn't sanitize any of this on the tgui/crafting side, so this might happen again in the future, but we don't technically support such characters already.

**Comment by neersighted** [comment]
It's actually not tgui, as far as I can tell, rather, byond serializes the character invalidly and UTF-8 shits the bed. Regardless, glad you solved it.

**Comment by RemieRichards** [comment]
@neersighted "tgui shits itself" is simpler to say than "the internet explorer framework Byond is built on is not very favourable towards non-ascii characters" :P

**Comment by TrustyGun** [comment]
you should decrease the size of the crafting entries, they are way too big right now. :+1:

**Comment by Bawhoppen** [comment]
thats what I have been saying

**Comment by Iamgoofball** [comment]
@neersighted how do you load an image/sprite in tgui

**Comment by PKPenguin321** [comment]
is it possible to make all the categories show at the top instead of having two scroll buttons?

**Comment by RemieRichards** [comment]
@tgstation/commit-access

**Comment by PKPenguin321** [comment]
rip the chef

**Pull request merged**
