### PR TITLE
Host Change. End of an era.

### PR DESCRIPTION
**Pull request by AndrewL97**
This commit hands the reigns over from Oranges to Gomble.

Gomble is a very experienced developer, and has brought many great changes in his time managing TG's upstream repo (Mojave Sun).

### CODE REVIEW

**Comment by Fikou** [comment]
Thanks Gomble!

**Comment by AndrewL97** [comment]
Hey @optimumtact 

@MrStonedOne  sent me this commit to PR on his behalf, it was too emotional for him.

Let me know the server login details and send me patreon access when you're free.

Thanks mate!

**Comment by Iamgoofball** [comment]
Looks legit to me, :shipit:

**Comment by optimumtact** [comment]
Approved

**Comment by ProfessorPopoff** [comment]
I don't get it- Why was it closed? Can we get a re-open over here.

**Pull request closed without merging**
