### PR TITLE
Remaps Metastation's kitchen for about the tenth time

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

The way the connector between the kitchen and bar looks right now has been bugging the shit out of me.

Before:

image

Eugh. Looks not great.

After:

image

Significantly better IMO. Still keeps the fridges publicly accessible and the glass airlock feels more at home with the colors on the fridge sprites. I also took the opportunity to give a bit more table space and put things in a bit more of a sane place in general.

Ups to @MTandi for doing most of the tile placing, I just changed the airlocks around a little to look nicer.

## Why It's Good For The Game

Thing looks better now. More space for what to put food so it stays clean.

## Changelog

:cl: Vekter
add: Remapped the Metastation kitchen for about the tenth time.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Yeah, bite me, I'll do some fixes this weekend.

**Comment by AdipemDragon** [comment]
Grats on creating the funny scenario of someone sitting down at the mess hall right in front of the fridge instead of at the table (avoiding this sitch being why, I'm guessing, the tables were like that to begin with)

**Comment by Jezzared** [comment]
With every PR, the bar and kitchen move ever closer to the back wall. Eventually, the maltese falcon will consume the entire station. One PR at a time.

**Comment by zeroisthebiggay** [comment]
bros with the stools facing into the fridges
what are they going to sit and order

**Comment by newfren** [comment]
that door's always looked dumb, good change

**Comment by TheVekter** [comment]
> Grats on creating the funny scenario of someone sitting down at the mess hall right in front of the fridge instead of at the table (avoiding this sitch being why, I'm guessing, the tables were like that to begin with)

What I get for mapping late at night. I fixed it. Looks a lot nicer now.

**Comment by AdipemDragon** [comment]
Only thing now is that, with the addition of glass doors, the kitchen shutters don't... really do their privacy job anymore, huh. Like, they're nice, but beauty clashes with practicality there. (plus i see no shutter on the fidge itself too, like the last iteration.)

**Comment by TheVekter** [comment]
> Only thing now is that, with the addition of glass doors, the kitchen shutters don't... really do their privacy job anymore, huh. Like, they're nice, but beauty clashes with practicality there. (plus i see no shutter on the fidge itself too, like the last iteration.)

image

Eh, I don't hate it. If you think that privacy is important I can keep it like this.

**Comment by AdipemDragon** [comment]
the barkeep's door does still allow some peeping, but that's already much better there (also sorry for being such a nagging nancy for this, cheffing is important to me)

**Comment by TheVekter** [comment]
> the barkeep's door does still allow some peeping, but that's already much better there (also sorry for being such a nagging nancy for this, cheffing is important to me)

I'm not concerned with it tbh.

**Pull request merged**
