### PR TITLE
Improves chair and stool inhands.

### PR DESCRIPTION
**Pull request by WJohn**
Because the current ones are baaaaaaaaaaaaaaad.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
why does the chair use a nearly black outline what are you doing use the chair sprite as reference for that
the stool looks pretty good but the legs use a nearly black outline too???

**Comment by PKPenguin321** [comment]
Fixes https://github.com/tgstation/-tg-station/issues/15618

**Comment by WJohn** [comment]
I am using the chair sprite as a reference, yes. Same color palette.

**Comment by GunHog** [comment]
It looks a lot better than before!!

**Comment by KazeEspada** [comment]
I need wood ones, office chairs, and <.< >.> armchairs wouldn't hurt.

**Comment by Ultimate-Chimera** [comment]
Looks really nice WJohn. :+1:

**Comment by GunHog** [comment]
You have failed to resolve conflicts, WJ :P

**Comment by WJohn** [comment]
I don't understand you, git. These have the exact same icons as the latest code, plus my changes. Why won't you recognize that!?

**Pull request merged**
