### PR TITLE
[Touching all the maps oh god] The reason for the season

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds christmas stuff to <b>all seven maps</b>

This means two xmas trees per map, one in/near the bar and the other in/near the chapel. There's also a festivus pole in/near the RD's office. In a few cases a clearing of space in the bar for the tree came at the expense of a few chairs/tables, but if there were anything on said tables they've been moved to empty tables nearby.

Bird and Ministation only get the one tree though, as they either are missing the bar or the church and neither has a RD office.

Also adds a christmas tree to the centcom disembark (thank god that's generic now) and the magic robe compatible santa hat/suit to the wizards den.

### CODE REVIEW

**Comment by Anonus** [comment]
Pictures, please.

**Comment by Supermichael777** [comment]
change log or id didn't happen.\

**Comment by swankcookie** [comment]
Feel free too use my fancy-shmancey new snowmen costumes as well. 
(/obj/item/clothing/head/snowman), (/obj/item/clothing/suit/snowman)

**Comment by Incoming5643** [comment]
I am not taking 17 pictures. I'm sorry, I'm just not. I've done everything to make sure these trees don't block critical things like apcs/doors with their bulk.

Also something weird going on here

**Comment by swankcookie** [comment]
Will do

**Comment by swankcookie** [comment]
@Incoming5643 are giftboxes already implemented?

**Comment by Incoming5643** [comment]
yep, under the very uninspired typepath of /obj/item/weapon/a_gift

**Comment by swankcookie** [comment]
hokay

**Comment by AnturK** [comment]
Can't you make these landmarks, so we don't need to revert/recommit this every year.

**Comment by swankcookie** [comment]
@Incoming5643 i created a PR for your branch

**Comment by Incoming5643** [comment]
Two issues:

1.) Christmas "season" isn't formally defined, and currently if we wanted to do that it'd mean the game would announce it at round start every dang round all month.

2.) It'd require us to clear a 3x3 square for the tree at all times of the year.

Can't we just solve this in mid January like normal people

**Comment by Incoming5643** [comment]
I don't know if it's great idea to tack that onto this, considering map changes are so conflictastic. I usually keep map and non map stuff very separate.

**Comment by Niknakflak** [comment]
Ohboyherewego

**Comment by Incoming5643** [comment]
I swear to god if this languishes and you force me to solve like 20 merge conflicts over the course of three weeks...

**Comment by swankcookie** [comment]
@Incoming5643 i just feel wierd shooting a PR with 2 additions too a list

**Comment by Incoming5643** [comment]
Fine I added it manually.

**Comment by swankcookie** [comment]
great, thanks.

**Comment by Jordie0608** [comment]
Recompile with Birdboat/Mini set as the included map before opening them with dream maker to avoid the exceptions.

**Comment by Incoming5643** [comment]
my god that's a pain

**Comment by Anonus** [comment]
You can also tick the included files for them before opening them, which gives about the same effect.

**Comment by Incoming5643** [comment]
That didn't seem to work when I tried it.

**Comment by Anonus** [comment]
It works if you rebuild the object tree.

**Comment by optimumtact** [comment]
snowflake detected

I'm not angry I'm just disappointed, it would be nice for event code to grow spawn landmarks though.

**Comment by Incoming5643** [comment]
I promise I'll give an honest smack at it when it comes time to remove these things

**Comment by Incoming5643** [comment]
Alright, mini and bird have been taken care of.

**Comment by Metacide** [comment]
Thanks :+1:

**Comment by duncathan** [comment]
>45 minutes early

I'M A FUCKIN MANIAC

**Comment by HankMoodyExperience** [comment]
OY VEY IM SPACE JEWISH THIS OFFENDS ME

**Comment by optimumtact** [comment]
sorry we only allow christians on this server, please give us your ckey so we can permaban you.

**Pull request merged**
