### PR TITLE
Replace firing pins with test range pins in the RD's locker

### PR DESCRIPTION
**Pull request by yackemflam**
Makes science too much of a target during gangs/revs
Makes science too strong of a antag choice.
Balance more please

### CODE REVIEW

**Comment by Bawhoppen** [comment]
RD getting pins is just dumb and counter-RP

**Comment by yackemflam** [comment]
Can someone who gives a thumbs down on why it's a bad idea?

**Comment by Bawhoppen** [comment]
they're just powergamers who want science to be OP without relying on other people

**Comment by Bawhoppen** [comment]
give him a box of test pins actually that will slightly appease the nerds

**Comment by yackemflam** [comment]
Done

**Comment by KorPhaeron** [comment]
"""""""testing"""""" by firing 5 tiles into a dumb metal target is not fun though

**Comment by Bawhoppen** [comment]
then they should go ask security for real firing pins instead of the RESEARCH DIRECTOR getting the things that allow extremely hightech and dangerous guns to work

**Comment by yackemflam** [comment]
Scientists running around with powerful as shit guns 20 mins in isn't fun for the crew either. Steal the pins if you REALLY want the super guns.

Also, team antag balance reasons too.

**Comment by yackemflam** [comment]
Damn it, what went wrong?

**Comment by Bawhoppen** [comment]
just compile it locally and see, I have yet to figure out travis' mysterious interface

**Comment by Aloraydrel** [comment]
Why bother since you can print test range pins anyway

**Comment by yackemflam** [comment]
Good point

**Comment by kevinz000** [comment]
@KorPhaeron Didn't you say to choose between science firing pins and Prototype SMGs?
Well I think that by removing pins we should be allowed to have our SMGs back :)

**Comment by PKPenguin321** [comment]
Give lockboxes remove firing pins from R&D thank you

**Comment by Fox-McCloud** [comment]
Should probably happen, but yeah, the whole "shoot target within 3 vision range of you" is boring as hell.

**Comment by yackemflam** [comment]
Well, get the pins from sec like you guys have always done.
Or get loyalty implants and get implant pins.

**Comment by Thunder12345** [comment]
@Fox-McCloud 
Ask atmos to build you a disposal pipe into the target area, barricade it off with windows. Pipe in pre-stripped trespassers to use as targets

**Comment by optimumtact** [comment]
Negative response and downthumbs from design lead.

**Pull request closed without merging**
