### PR TITLE
North Star AI SAT rework

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request

Redoes the AI SAT so the AI is better protected and command can actually access it.
aisat

## Why It's Good For The Game
AI is as protected as it is on other maps + fair to malf AI + command can reach SAT
## Changelog
:cl:
fix: Command can actually enter the AI SAT on the North Star.
add: The North Star AI SAT has been redone.
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
> You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

pls ban he

**Comment by MTandi** [comment]
Is it really ok to leave all SMES unprotected?

**Comment by Cheshify** [comment]
> Is it really ok to leave all SMES unprotected?

Y'know, looking at it. It's probably fine? I think I'd need more info in the future to see if it's an actual issue.

**Comment by MTandi** [comment]
> Y'know, looking at it. It's probably fine? I think I'd need more info in the future to see if it's an actual issue.

Really? Imagine if you're malf. Then all they need to do is to come break those SMES and wait until your APC discharges. And turrets won't help you.

**Comment by Cheshify** [comment]
> > Y'know, looking at it. It's probably fine? I think I'd need more info in the future to see if it's an actual issue.
> 
> Really? Imagine if you're malf. Then all they need to do is to come break those SMES and wait until your APC discharges. And turrets won't help you.

Good point, updated.

**Comment by Cheshify** [comment]
redid power so it only has an input and a power sink can't murder the AI

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
