### PR TITLE
Egg changes

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Eggs now contain 5u of egg yolk. Breaking an egg in a glass
container adds all reagents inside to the container. If you're laying
abductor gland eggs, then you'll get 5u of egg yolk and 10u of random reagent.
Egg glands now make you act like a chicken while laying eggs. Egg laying
makes you use the aliennotice span.
/:cl:

- coloured eggs no longer have "taste_desc", as that only applies to the
nutrient reagent, which eggs no longer have.
- Gland eggs are now coloured according to the colour mix of the reagents inside them.

This makes eggs more consistent in their contents and behaviour, and
prevents you from using eggs laid by abductor egg glands in cooking
without removal of the acid first.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Egg, Egg changes

**Comment by MoreRobustThanYou** [comment]
new meta: forcefeeding eggs to monkeys

**Comment by praisenarsie** [comment]
no eggshells?

**Comment by newfren** [comment]
I believe this won't require you to remove the acid from the eggs to use them in cooking - break the eggs into a glass, craft something that requires egg yolk, it will magically suck the egg yolk out of the glass without touching the acid. And unless acid interacts with flour or sugar it also won't stop you from using them for cake batter.

**Comment by coiax** [comment]
@newfren You are correct, but my PR is better than just magically losing the acid/whatever (if #35282 is merged).

**Comment by coiax** [comment]
@XDTM I included your now merged PR.

**Comment by XDTM** [comment]
Cool, can't wait to see what people do with this

**Pull request merged**
