### PR TITLE
Makes spawn point icons more obvious when mapping

### PR DESCRIPTION
**Pull request by Thunder12345**
Should be easier to spot spawn points on the map now, see icon diff for details.

No changelog because there should be no visible effect for anybody except mappers.

### CODE REVIEW

**Comment by coiax** [comment]
You need to add these brackets to the proc that generates these icons. So when there's an outfit update to a job, you can just run the proc again and update the icons to be FRESH.

**Comment by Thunder12345** [comment]
Are these actually generated? I assumed somebody just put them together manually

**Comment by lzimann** [comment]
the job icons are generated automatically with [this proc](https://github.com/tgstation/tgstation/blob/master/code/modules/admin/verbs/mapping.dm#L271)

**Comment by Thunder12345** [comment]
I'll be back when I think of a neat way to do this

**Comment by Cyberboss** [comment]
Just add an overlay before flattening the icon

**Pull request closed without merging**
