### PR TITLE
Fails travis on common mapping mistakes

### PR DESCRIPTION
**Pull request by ShizCalev**
Also fixes a number of said mistakes that are currently present, as well as resolving a number of conflicting vareditted areas, making all maps conformant to CONTRIBUTING.md

### CODE REVIEW

**Comment by WJohn** [comment]
Could you make a list on the wiki or someplace to detail all of these so I can go through this checklist whenever I finish my map?

**Comment by ShizCalev** [comment]
Sure

**Comment by ShizCalev** [comment]
Actually these ones are specifically mentioned in https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#mapping-standards
(Aside from the d1 & d2 var for cables which are deprecated on maps since they are generated off iconstate.)

**Comment by AnturK** [comment]
Technically pixel_x/y = 0 may be correct if you use a subtype that defaults to non-zero. Bit unlikely but still

**Comment by Cyberboss** [comment]
A quick search shows antur is right

**Comment by ShizCalev** [comment]
The only types that come to mind / I can see are ones that have icons larger than 32x32, which shouldn't be vareditted in that case anyway since it'll fuck with their hitboxes iirc.

**Comment by ShizCalev** [comment]
Removed the exit, but kept the echo to make it more obvious during review. That seem fine?

**Comment by Cyberboss** [comment]
Sure

**Comment by optimumtact** [comment]
Ready?

**Pull request merged**
