### PR TITLE
space bears won't attack through anti-bear circles

### PR DESCRIPTION
**Pull request by Iamgoofball**
https://www.dropbox.com/s/bgaldnvo18mmq9n/space%20bears.webm?dl=0

### CODE REVIEW

**Comment by duncathan** [comment]
:+1: x :100:

**Comment by MrPerson** [comment]
Obviously no

**Comment by Aranclanos** [comment]
of course this is really unimportant so I expect huge controversy 
and i hate it because its stupid as fuck and makes no sense, just a reference for some gay shit

**Comment by Miauw62** [comment]
erro's law holds true still

**Comment by daman997** [comment]
perfect :+1:

**Comment by Core0verload** [comment]
Better use circles to protect from revenants and maybe slaughter demons.

**Comment by CPTANT** [comment]
Elbereth grafiti respected by mobs when?

**Comment by oisin100** [comment]
:+1:  Nerf Doe spess beers way to 0p

**Comment by Dorsisdwarf** [comment]
I'd prefer elbereth to a circle.

Also the bear very clearly beats the shit out of the guy in the video while on the circle, is that intended?

**Comment by Iamgoofball** [comment]
@Dorsisdwarf Actually, he falls over from damage ticking over from the last time he got hit. He wasn't hit while he was on the circle.

**Comment by Dorsisdwarf** [comment]
Alright, good to know that works.

**Comment by Cheridan** [comment]
>checking icon_state 
>ever

:angry:

**Comment by Iamgoofball** [comment]
@Cheridan for some retarded reason crayons don't keep a var with what it is supposed to be that isn't icon state

**Comment by WJohn** [comment]
THE NEW META.

**Comment by optimumtact** [comment]
@Iamgoofball well then make it so it does, don’t' just hack it, it's not like you're under time pressure or anything

**Comment by bgobandit** [comment]
add elbereth pls

**Comment by PKPenguin321** [comment]
this is insanely inconsequential, will probably never be used ingame, and is a cute and fun reference that only takes 5 lines of code

why not? :+1:

**Comment by Miauw62** [comment]
because it does a string comparison whenever space bears attack somebody

**Comment by MrPerson** [comment]
@PKPenguin321 Then why even have it? If it's 'never' used ingame, it's code complexity increases for literally no gain.

**Comment by PKPenguin321** [comment]
true, but at the same time it's just five lines of code and there's still a chance that someone, somewhere, will gain fun from this
is that really so catastrophic

**Pull request closed without merging**
