### PR TITLE
Action Buttons and fixes for minebots

### PR DESCRIPTION
**Pull request by Cruix**
:cl:
add: Sentient minebots can now toggle meson vision, a flashlight, their mode, and dump their stored ore.
fix: Sentient minebots can now be repaired if they were made sentient while the AI was active.
fix: Healing minebots will no longer switch them to attack mode.
tweak: Sentient minebots can now shoot at humans.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
I was literally coding this same thing, kudos for being faster, lol

**Comment by Ergovisavi** [comment]
So the reason the minebot has two different modes is to prevent one from seeking ore when it's supposed to be fighting enemies (And to prevent immortality via repeatedly healing the drone while it's in the middle of combat, but still keep repairing it responsive).

If you're going to make playing a mining drone a more natural experience I highly suggest removing the modal state while it's controlled by a player and just making it a single state, then fix the repair problem via a delay on weld or something.

**Comment by lzimann** [comment]
While you are at mining bots, do you mind adding a number generation for the name? Like drones/constructs have

**Comment by optimumtact** [comment]
The verbs will need to be moved to the action buttons system before we can consider merging this.

We're trying to avoid phasing in new verbs.

**Comment by Cruix** [comment]
untitled
Mostly recycled action button icons.

**Comment by optimumtact** [comment]
That was quick :+1:

**Pull request merged**
