### PR TITLE
Removes a message from the Major Dust event for sounding like admin abuse

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by kevinz000** [comment]
If you build the BSA for teh station objective, you should be able to fire on the other station to cause like 1  medium meteor to hit them at an angle you set.

**Comment by Niknakflak** [comment]
No, I like this one

**Comment by optimumtact** [comment]
I see no reason to remove this

**Comment by Iamgoofball** [comment]
@optimumtact the way it's phrased implies the other station is somehow triggering an event to fuck with your station

**Pull request closed without merging**
