### PR TITLE
Limits gold core magicarps to wizard rounds

### PR DESCRIPTION
**Pull request by ohnopigeons**
:cl:
tweak: After a series of litigations, the Space Wizard Federation has managed to successfully patent troll Nanotrasen. Nanotrasen now has a legal agreement with the Space Wizard Federation to not engage in magicarp research.
/:cl:

Let's keep magical shenanigans to wizard rounds please.

### CODE REVIEW

**Comment by 81Denton** [comment]
This is the third removal PR in four days about carps, and unlike the previous ones this one doesn't even provide a reason why. 

I'd prefer having a discussion on the forums first instead of kneejerk opening a new removal PR as soon as the previous one gets closed.

**Comment by XDTM** [comment]
Magicarps have the potential to be very gamebreaking, in the sense that it trivializes or replaces a lot of gameplay mechanics. Healing is literally on par with admin heals. Death is, well, pretty much the best ranged weapon. Animation means chaos and destruction. Doors means free resources/chaos. Teleport is pretty tame. Changing means access to some mobs (like syndiborgs) that aren't taken into account when balancing the game. Fireballs are rocket launchers, when we normally would need to mount them on combat mechs.

**Comment by Barhandar** [comment]
@XDTM all these options are accessible at roughly same time as xenobio _can_ get sentient magicarp. Much earlier in the case of healing.

**Comment by Shadowflame909** [comment]
Will I ever get a break trying to defend another xenobio gold core Nerf pr.

**Comment by pigeonsk** [comment]
As hard as it is to believe, there is more to this game than clicking on someone until their health goes to 0 and their sprite turns horizontal.

**Comment by Shadowflame909** [comment]
As hard as it is to believe, there is more to a game then ignoring the opinions of the masses and making Nerf prs every day. Also an in game mob being repurposed isn't an argument. Light geists were collosus only and now you can make them. No other mob brings as much variety to xenobio then magicarps. The fireball spell  is a dangerous meme equivalent to a dice role that can explode on yourself and literally do nothing to your opponent. Please look at all the arguments from that thread. Late game medbay can make romerol zombies, why can't late game science revive you from death and turn you into different mobs. If you have a problem with a mob individually from staff of change make a removal pr singleing it out
But I believe there's no problem with the design. Nothings not hard to defeat, and the only time this can be "powergamed" is when you're an antagonist. This would be the least of your worries then.

**Comment by ExcessiveUseOfCobblestone** [comment]
Crossbreeding will open new situations that isn't going into the realm of Wizard Territory.

**Comment by pigeonsk** [comment]
It is entirely a design problem. Magic is very broken and intended to be so; chaos and nonsense is the entire point of wizards and wizard rounds. Magicarps were added as a wizard event spell to be carps but worse. To then refocus design, balance, and usage of magicarps entirely around its xenobio spawn is an absurdity to me. Its use case as a wizard antag tool as is much more interesting than as a xenobio tool. The latter detracts from the former, and this is why this PR exists.

**Comment by Shadowflame909** [comment]
1. There's only one carp that appears during wizard rounds and it's a lame chaos carp. 2. You literally cannot get regular sentient magicarps during wizard rounds. Lastly, you're blowing magicarps out of porportion, I can make such absurd claims with no evidence as well but the problem with that is, there's no evidence! Where is your proof that every round with magicarps in xenobio causes chaos and destruction like a wizard round. It doesn't. An hour and 30 minutes into a shift when you get a magicarp that can be as useless as a bolt of nothing to as dangerous as a bolt of death. I firmly believe that magicarps are a appropriate late round reward that shows your dedication to get them. As they're pretty rare to spawn and take at least 10 gold slime cores. Regular magicarps aren't as much of a wizard antag tool as if the wizard caused the random possessing ghosts event. Golden slime magicarps are the route you take when you want simple fun, ghosts being re-added to the game and happiness for the entire crew. You haven't refuted that all the other departments can get as powerful as science during an hour long shift. So, I feel like your vendetta against magicarps is unwarranted. Especially because you feel like items shouldn't exist out of there respective modes. When the server is leaning towards more random mode shenanigans via datumizing antagonists so we could very well end up with cult wizard rounds on the future!

**Comment by RogueSteampunker** [comment]
Oh boy, here we go again

Let's see:

magicarp are hard as hell to get, being a rare spawn in gold slimes, which you have to breed with light-pinks to get

Most other departmental roles have an endgame that can rival such power, and is a lot more consistent and faster.

When the argument of "they can mess with rounds" is blown out of the water in the last two threads with the same goal, you honestly can't try to use it as the same reasoning.

And no, crossbreeding isn't an excuse to make another slime type useless and undesirable. It's a nice change, and should be appealing to keep people from mass-spamming carps in the 1 outta 10 rounds they can, not an excuse to make another pyrite slime.

**Comment by Shadowflame909** [comment]
When your argument stops being "things shouldn't exist out of there respective modes" Then I would like you to realize how many features go against what you just said! (Romerol zombies being able to made in medbay, prides mirror, morph, chameleon items, head slugs, statues, emp grenades, shurikens and reinforced bolas, smuggler satchels with items from the previous round) Then you'll truly have an argument that makes sense.

**Comment by Shadowflame909** [comment]
Is a magicarp really as odd and totally wild as a miner being an Ash Drake? Or a miner with collosus voice? Or a space proof hulk who kills people from space with x-ray and telekinesis? Or a miner getting a Holoparasite from lavaland? If the argument changes into "b-but not enough danger" well, then you have an entirely different issue to tackle. That has already been solved on another /tg/ base!

**Comment by Shadowflame909** [comment]
Or even the staff of storms or a lava staff that's as late game as magicarps!!!

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think it being spammed/not spam has any bearing on the fact it admin-heals (or something very close to it) and instakills, and when it doesn't give you/your 100% loyal servant the desired effect, you/your 100% loyal servant can just wait a second and try again because there are no charges associated with it and a very low cooldown.

Carp,along with the normal simplemob gripes, can spacewalk too.

@Shadowflame909 it is misleading to intermingle the ability to spawning a magicarp with the ability to spawn mobs at all with g/p combo. Should this go through, there are still plenty of useful mobs that can be summoned and used for ghost shenanigans.

There are also plenty of ways to get back into the round even if that was to be removed (I hope it never does).

Also the whole "going into the pen is dangerous haha balance!" is silly.

And uh none of those things instant kill/instant revive w low cooldown...

**Comment by XDTM** [comment]
By the way gold + light pink is definitely not 1 hour and a half, it's closer to 30-40 minutes.

**Comment by pigeonsk** [comment]
Your point about how much of a diminished role magicarps play in wizard rounds only proves my point of much focus and use-case of magicarps has shifted. And, in this case at least, it is not a good thing.

Ghost roles are plenty and are a privilege, not a right.

My point wasn't "things shouldn't exist out of there respective modes" it was "wizard magic and spells shouldn't exist outside of wizard rounds because of the nature of wizard magic and spells and their incompatibility with the rest of the game on a regular basis". Things like lavaland loot was specifically designed as rewards for miners to bring back to the station. This is not true of wizard spells, which are antag features and designed to really mess up the station and round.

Xenobiology balance is one aspect of this PR, which seems to inspire a lot of vigorous debate and arguing. But this is not the sole aspect and all of you seem to be focusing too much on that. Please consider the overarching game design.

**Comment by Iamgoofball** [comment]
can you guys just admit that you guys only use xenobio for the free antag already lmao

**Comment by Shadowflame909** [comment]
So it seems I'm on my last legs. I can't really agree that wizard magic is out of place, it fits the scope of the zanyness of shifts near there end, but I can sing it's praises. Magicarps of change may not be perfect, but they are beloved and make the community happy. Cyborgs become syndicate medical Borg's who Inject the crew with nanites and beam guns instead of bicaradine. They become meth speed xenos, who vore the shit out of rogue ling's. Lastly, after 1000 shots they become ash Drake's, looking ridiculous and scaring the shot out of tiders who realize they're fucked when the shuttle lands. Magicarps are the only way staff of changes get used to there full potential. It's real easy to one shot a friendly wizard with one and end the round. I won't deny, it may be xenobios endgane but it might be the strongest out of all the end games. But I say that depends how you see it. Robotics get phazon mechs fast hardsuits and weapons of all calliber. Medbay can revive you nearly instantly and can instantly produce all chems in a oddeyuses that also functions as a jail. Security gets sniper rifle flame thrower, and cargo...cargo gets everything. Now, I feel like removing this instead of finding ways to balance it is disappointing. That wouldn't be in the name of end game balance. It's in the name of anti fun. There are tons of things that can be abused. This isn't one of them as there are number of counters that can do what xenobio does. Lastly, have you seen anyone complain about a staff of change in game? Hell, the shuttle with one is the most popular of all. So, think about the end game dreams. The overarching game design that is, Literally everything is OP and that's alright. You can spawn a singulo in a second. But, can you really cause mass chaos as a non antag with a magicarp of change? Also, if you have any problem with how unbalanced they are. I say the notion they are unbalanced is false! Maybe they can be made a bit more rare and longer to get to. But as I've said 40-50 minutes into the shift, you can get along things more chaotic then this...

**Comment by Shadowflame909** [comment]
I don't care for magicarps of death. We have light geists and autocloners to be a replacement magicarp of life. But everything in between is fine and fun. And would be pretty saddening to get locked behind such a rare and quick mode.

**Comment by 81Denton** [comment]
>free antag
What did he mean by this

**Comment by Shadowflame909** [comment]
I'm not saying I want magicarps every round. They should be hard to get to, which is why it's good to have as many types of them as you can. But, it's so rewarding when nearly an hour of hard work pays off and you can prank people by ash Drake jaunting behind them and going "hi"

**Comment by Shadowflame909** [comment]
Alright I've regained some steam. Rebuttal! Saying "it doesn't fit in xenobio, should be wizard only" Isn't an argument, It's an empty claim. Where's your evidence? The removal of magicarps of change bring the most sadness, otherwise your pro would have at least 1 upvote!

**Comment by praisenarsie** [comment]
@Shadowflame909 calm down

[it's only game](https://www.youtube.com/watch?v=xzpndHtdl9A)

**Comment by YakumoChen** [comment]
I think this PR is a little ridiculous and basically makes magicarp unusable by xenobio. Most wizard rounds don't actually last long enough for xenobio to get anything done, especially on this scale, so it's no better then removal. I don't actually see what the big deal is? Considering how much RNG you have to sit through to even get a carp, much less one with the spell you want, takes considerable effort and you can become a ling easier then you can get a death carp.

**Comment by Shadowflame909** [comment]
I'm not saying don't nerf magicarps at all. You should make them rarer, well if you really insist on nerfing them. Push them even farther endgame, but don't essentially remove them. That's not very nice to the community who look foward to them!

**Comment by XDTM** [comment]
I'd say they don't fit xenobio at all. Although i'm generally against gold core mobs, since they're just a hodgepodge of mobs taken from code made for ruins, away missions, and abandoned content.

I'd much rather go the way i did for slime species and make a custom, exclusive mob pool for gold slimes. Not necessarily slime themed, but for god's sake not a trashcan of unused mobs.

**Comment by DaxDupont** [comment]
Now you can predict the mode!

Sneaky wizards are kill

**Comment by Shadowflame909** [comment]
Agree to disagree. I enjoy them, and not because the dumb "free antag" which is not true. But mainly because I like spooking people as an ash drake. I'd trade 20 tc to turn into an ash drake with his attack variable set to 0 and i'd hillariously set people on fire as they realize my flames did no damage. Chomp them, and crush them all with no damage.

**Comment by improvedname** [comment]
@daxdupont

Worst part when they are not valid on sight too cuz dumb admins protect them and whe you do realise they are evil you just get shot by death bolt bullcrap carp

**Comment by YakumoChen** [comment]
I have never seen admins defend a xenobio mob, especially a non antagonist spawned one

**Comment by 81Denton** [comment]
>they are not valid on sight

They are on /tg/, are you maybe playing on different servers

**Comment by Kraseo** [comment]
@XDTM legion cores are literally admin heals and are far more common but i don't see anyone complaining about them

**Comment by Kraseo** [comment]
also this is a stupid PR because there are only like 2-3 types of magicarp ever used

**Comment by pigeonsk** [comment]
It's clear no one cares for this particular attempt at a compromise solution. Maybe you all will find something you like better.

**Pull request closed without merging**
