### PR TITLE
Ports more oracle's sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: # 
:cl:
imageadd: Updates floor and big safe sprites. (by Quantum-M)
imageadd: Updates the radiation collector sprites. (by Quantum-M)
imageadd: Updates the book uploader sprites. (by Quantum-M)
imageadd: Updates the sheet bin sprite (by Quantum-M)
imageadd: Updates the drone dispenser machine sprite. (by Quantum-M)
/:cl:

Stolen from https://github.com/OracleStation/OracleStation/pull/1112

### CODE REVIEW

**Comment by nicbn** [comment]
oh shit give me a minute

**Comment by vuonojenmustaturska** [comment]
you'll probably want to cherry pick the perspective-changed sprites from library.dmi, the other modifications/deletions don't look correct. ditto for structures

**Comment by Militaires** [comment]
nigga... add images jesus christ

**Comment by Qustinnus** [comment]
ew no

**Comment by Militaires** [comment]
icons on their own != icons on the station. against its grey palette, with active lighting

**Comment by Militaires** [comment]
i dont think lighting will help this sprite anyways though 
image

**Comment by nicbn** [comment]
I'm porting the icons I didn't test them locally
You can test them by observing a round in Oracle anyway

**Comment by Militaires** [comment]
>expecting people to visit another server and download their rsc to check out some sprites

**Comment by nicbn** [comment]
Oof

**Comment by WJohn** [comment]
these just change it to 3/4th without any improvement made to them whatsoever.

**Pull request closed without merging**
