### PR TITLE
you can now get burned by very hot tanks if you dont wear heat insulated gloves

### PR DESCRIPTION
**Pull request by Timonkeyn**
## About The Pull Request

you now get 5 burn damage and wounds depending on how hot the tank is

## Why It's Good For The Game

CEO of atmos code aka ghilker said it was a good idea

## Changelog
:cl:
tweak: to minimize expenses, centcom removed the heat insulation from all tanks.
/:cl:

also im committing from the browser because i hate vscode source control

### CODE REVIEW

**Comment by Timonkeyn** [comment]
dont mind the other commits, its complicated

**Comment by Angustmeta** [comment]
More downsides to wearing yellow insuls are good. Death nettles and such could use similar tweaks.

**Comment by kriskog** [comment]
According to https://tgstation13.org/phpBB/viewtopic.php?f=5&t=18660 you are still banned from contributing to our repository. If you wish to appeal this, follow the procedure in the thread.

@optimumtact another alt for the list.

**Comment by optimumtact** [comment]
lol

**Pull request closed without merging**
