### PR TITLE
Fixes the stupid beesword thing

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Explaining the issue: The belt sprite and base icon didn't work. It was a subtype of the rapier for no real reason, meaning it fit into the sabre sheath which looks really retarded. The articles were all messed up because it's a unique item but not capitalized. Basically, it's a mess.

All of that has been fixed.

Since it lost the sabre suicide, I gave it a new *unique* suicide. It's basic stuff, nothing big.

## Why It's Good For The Game

Invisible icons are bad.
Bad articles bad.
Making already existing snowflake content less special bad.

## Changelog
:cl:
add: The bee sabre now has it's own suicide and no longer uses the one of the captains rapier.
fix: The bee sabre uses the correct articles and actually has icons now.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Not related to your change, but why does the bee sword inject histamine instead of the generic toxin reagent like actual SS13 bees do?

**Comment by Fikou** [comment]
> Not related to your change, but why does the bee sword inject histamine instead of the generic toxin reagent like actual SS13 bees do?

yes

**Comment by wesoda25** [comment]
tbh im considering removing bee sword, the kit is robust enough with just beenades

**Comment by FantasticFwoosh** [comment]
Where was quality assurance?

**Pull request merged**
