### PR TITLE
Adds smooth lava

### LINKED ISSUE #13256: Lava can be burned/damaged to look like plating
Reminder for myself to fix this

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
With sprites from @WJohn 

Old lava is still in because this stuff only really looks good with lavaworld asteroid tiles

http://i.imgur.com/3WBwBv0.png

Fixes #13256

### CODE REVIEW

**Comment by Anonus** [comment]
Pictures, etc, etc.
I've seen it before but do it anyway

**Comment by WJohn** [comment]
Uh, these are designed specifically to fit with basalt flooring and nothing else. It wouldn't be that hard to remove some of the excess stuff on them, but they also cause additional cracks and crevices near them, all in the basalt floor style/colors.

**Comment by KorPhaeron** [comment]
@WJohn 

He uses the basalt flooring in his mission

**Comment by WJohn** [comment]
Very nice, then.

**Comment by KorPhaeron** [comment]
He uses normal asteroid walls though

**Comment by MMMiracles** [comment]
I tried using the basalt rocks but I kept messing up the border offsets and it looked bad so I just decided to keep using the regular asteroid walls.

If you make a subvariant for basalt it'll be an easy change in that regard.

**Comment by KorPhaeron** [comment]
@MMMiracles 

I am going to attempt to do so tonight

**Comment by Aranclanos** [comment]
post the sprites in the OP

**Comment by WJohn** [comment]
This is basically what volcano world would look like, and these are the lava sprites.

**Comment by KorPhaeron** [comment]
Bundling this in with the rest of the mining turf updates

**Pull request closed without merging**
