### PR TITLE
Optimizes Life() processing by separating simple mobs into a background SS and removing lavaland mobs from the loop if no players can see them. also breathing

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
this pr:
1. separates SSmobs into SSmobs and SSsimple_mobs. all simple mobs go into the second. the new subsystem has a wait of 3 seconds and is background. carbons and whatnot stay in SSmobs. since we dont care about simple mobs as much as players this is fine, and now simple mobs will have their life loop yield more than player mobs. 
2. makes hostile simple mobs turn off their ai differently. currently on master when no player is on the z level the 250 some odd mobs on lavaland set their AIStatus to AI_Z_OFF and wont do any processing at all until a single player enters the z level in which case all of them will have their ai processed by SSidlenpcpool. now what happens is that when a hostile mob disables itself due to no nearby players it registers to players entering spatial grid cells near the mob. if a player enters those cells the mob will then set itself to idle mode and start processing. this drastically reduces the number of mobs processing if even a single miner is on lavaland, since only a few of them will actually be processing. i did this so i could then:
3. make some simple mobs remove themselves from Life() processing completely when their ai is turned off due to no players within interaction distance. there is absolutely 0 reason why we need to be constantly processing hundreds of lavaland mobs like this when no player could possibly interact with them. megafauna do not remove themselves from the process loop since theyre important
4. optimizes breathing, because it takes up a surprisingly high percentage of human/Life(). now 2000 calls of lungs/proc/check_breath() has gone from taking 0.486 seconds of total cpu to 0.188 under ideal conditions. the old check_breath() worked by putting 0 moles of air into every gas type it did work with but didnt exist, and then checking the amount of that gas later on and doing x functionality with it. however this is wasteful, its putting gas into the gas list and then garbage collecting it to remove it after its done. now what it does is loop through the unchanged gas list and do positive functionality based on what exists, and then after the loop is done go through all gases that didnt exist and do functionality performed when the gas isnt found (the loop didnt find this gas, so since we need that gas to live deal damage. or the loop didnt find this gas, so since we dont want that gas clear any effects from it, etc). now humans will scale the cost of Life() a little less

## Why It's Good For The Game
the state of SSmobs is pain. and has been so for years. its a constant drain on our cpu that scales up with playercount and its just due to 18 years of bloat. potato focused on the cost of human Life(), i focused (mainly) on the generally static cost of simple mob Life(). together we can make mob processing bearable.

### CODE REVIEW

**Comment by SmArtKar** [comment]
you madman, you actually did it

**Comment by Kylerace** [comment]
Screenshot_1955

**Comment by ATH1909** [comment]
how does this affect lavaland swarmers, if they're enabled? is the code for them even still around?

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
> makes hostile simple mobs turn off their ai differently. currently on master when no player is on the z level the 250 some odd mobs on lavaland set their AIStatus to AI_Z_OFF and wont do any processing at all until a single player enters the z level in which case all of them will have their ai processed by SSidlenpcpool. now what happens is that when a hostile mob disables itself due to no nearby players it registers to players entering spatial grid cells near the mob. if a player enters those cells the mob will then set itself to idle mode and start processing. this drastically reduces the number of mobs processing if even a single miner is on lavaland, since only a few of them will actually be processing. i did this so i could then:

This whole feature needs better (as in existing) methods for disabling in local test before it can be expanded like you are doing.

Trying to test my blob mob pathing pr was fucking pain, in part because the blob camera mob doesn't count as a player.

This PR is blocked untill this objective is met.

**Comment by Kylerace** [comment]
too many prs ill redo this later

**Pull request closed without merging**
