### PR TITLE
Improves unique gun renaming/reskinning, adds bartender shotgun reskinning

### PR DESCRIPTION
**Pull request by ghost**
- Removed 'rename gun' and 'reskin gun' object verbs for detective revolver.
- Adds parent proc for renaming. You can now rename any gun if their unique_rename var is set to 1 by hitting them with a pen.
- Adds parent proc for reskinning. You can now reskin any gun by clicking it with an open empty hand, but you can only reskin it once. You can cancel or set it to default if you don't want to reskin your gun, but it's an alternative to roundstart reskin proc which is bad and object verbs which are even more bad.
- You can rename miner shotguns (kinetic accelerators) because miners are NEET and need a friend out there on the cold asteroid if they don't have a drone.

### CODE REVIEW

**Comment by Lumipharon** [comment]
Neat. Time for PUNK BUSTER sawn off.

**Comment by dannno** [comment]
way better than what we had actually :+1:

**Comment by RandomMarine** [comment]
Yeah there we go object verb destroyed mission accomplished.

**Comment by dannno** [comment]
i'll do this at some point because it's pretty stupid that all these PRs get closed, they're good

**Comment by paprka** [comment]
you have my blessing, object verbs are bad

**Comment by TZK13** [comment]
Too late, #7997 ;^)

Why's he a hypocrite cunt though, he even thanked you~

**Comment by TheVekter** [comment]
Nah it's cool, I'll repost this either tonight or tomorrow after I have a chance to read it and make sure I know how it works.

**Comment by TheVekter** [comment]
That works.

**Comment by Miauw62** [comment]
conflicts ;-;

**Comment by dannno** [comment]
if pap really can't fix them i'll maybe make a PR for this laterrrrrrrrrrrrr

**Pull request merged**
