### PR TITLE
Armpits have smell

### PR DESCRIPTION
**Pull request by BreadBurner**
Armpits now have a "taste" similar to when you eat something you can describe the aroma, this is done by selecting an arm and double clicking on the person on help intent while grabbing.
The text can be something like "Akoro Malo smells Harold Robinson armpits, they smell like metal and sweat" This will imply that harold was moving recently and was on robotics or working with metal.

### CODE REVIEW

**Comment by Armhulen** [comment]
hey, wait a sec...

**Comment by qbmax32** [comment]
why

**Comment by ninjanomnom** [comment]
I take back what I said about #29129 , this is an amazing git history

**Comment by TrustyGun** [comment]
i cant tell if you even added it

**Comment by ninjanomnom** [comment]
Unless they somehow committed to master before making a pr to... multiz? Then no, this has none of the code they wanted.

**Comment by ExcessiveUseOfCobblestone** [comment]
is there a NTR-hut equivalent for github?

**Comment by Cyberboss** [comment]
Fix your git

**Comment by MoreRobustThanYou** [comment]
Just delete your fork and refork it

**Pull request closed without merging**
