### PR TITLE
Removes cancerous mass detected in the codebase.

### PR DESCRIPTION
**Pull request by Iamgoofball**
savefile.dm doesn't even exist anymore wtf

### CODE REVIEW

**Comment by Cheridan** [comment]
ur still around tho

**Comment by optimumtact** [comment]
goof status
rekt [x]
btfo [x]

**Comment by Iamgoofball** [comment]
@Cheridan 
unfortunately, not like your mom

**Comment by PKPenguin321** [comment]
shitstorm inbound
dis gun b gud

**Comment by Incoming5643** [comment]
uhhh

**Comment by Incoming5643** [comment]
(PR actually removes floor length braid for no raisin)

**Comment by phil235** [comment]
:-1:

**Comment by AnturK** [comment]
Doesn't even remove the sprite 0/10 :-1:

**Pull request closed without merging**
