### PR TITLE
Updated antenna sprite

### PR DESCRIPTION
**Pull request by PKPenguin321**
## About The Pull Request

A sprite request I made in the thread on the forums was answered, so now we can use these instead of the placeholders I made way back.

## Why It's Good For The Game

image

## Changelog
:cl: CaptainZorg
imageadd: Fancier on-mob antenna sprites for antenna and mind reader mutations
/:cl:

### CODE REVIEW

**Comment by Winterous** [comment]
How does this stack with the anglerfish lizard decoration? Probably looks less silly than the old antenna, but still something worth considering.

**Comment by PKPenguin321** [comment]
>How does this stack with the anglerfish lizard decoration?

Better than the placeholder antenna does, assumedly.

**Comment by wesoda25** [comment]
It’s so derpy, I love it

**Comment by nemvar** [comment]
unicorn mutation

**Pull request merged**
