### PR TITLE
Tests the roulette wheel for 150 hours (fixes it)

### PR DESCRIPTION
**Pull request by ghost**
:cl: qustinnus
fix: roullete wheel beacon now works
fix: can now cut roulette wheel wires
fix: roulette wheel can now be attacked
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
``return ..()`` in line 111

**Comment by Qustinnus** [comment]
then u'll accidently hit it when its playing thats not epic

**Comment by Krysonism** [comment]
Speedmerge and update Terry so I can play with this when I get off work.

**Comment by kriskog** [comment]
You also can't make a bet with your exact remaining balance, and having to swipe it with your ID to play is mentioned nowhere. Make a button to spin instead, literally nothing else requires you to swipe your ID to pay.

**Comment by Qustinnus** [comment]
up to @Krysonism

**Pull request merged**
