### PR TITLE
{ready} adds a new critter contraband crate

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
add:The NanoTransen Animal Right Association report missing  animals from the research reserve, they may have been smuggled in the local black market. NT reminds you that these creatures are dangerous and their possession is illegal.
/:cl:

### CODE REVIEW

**Comment by Therapist1** [comment]
Don’t you think the Leaper is a little much?

**Comment by Tlaltecuhtli** [comment]
it has only 300 hp

**Comment by Shadowflame909** [comment]
You can melee a leaper to death really easily, they're super slow as well. It's just a slower goliath that can gib.

**Comment by Therapist1** [comment]
lemme just buy 10 of these crates and open them all at once

**Comment by pubby** [comment]
Do the animals attack each other?

**Comment by Tlaltecuhtli** [comment]
they do have different factions so they should fight each other

**Comment by Armhulen** [comment]
You should just make it pick any random hostile mob in the game, save for BOSS_SPAWNS (megafauna, my fuckin ruin don't you touch it)

**Comment by Tlaltecuhtli** [comment]
how?

**Comment by PKPenguin321** [comment]
where the penguin crate @

**Comment by Shadowflame909** [comment]
Eh, not that bad. I like it how it is though! A statue would be interesting, as there's only one way to obtain them currently, also that one way makes them temporary.

**Comment by Tlaltecuhtli** [comment]
gold slime pool is garbage

**Comment by ExcessiveUseOfCobblestone** [comment]
then expand upon it :^))))

**Comment by Kromgar** [comment]
Shiiit hivelords havnt thought about those in ages

**Comment by MimicFaux** [comment]
"//he fell into the crate"
10/10

**Comment by Tlaltecuhtli** [comment]
how do i remove wip tag

**Comment by AlexTheSysop42** [comment]
Change title to not wip

**Comment by ExcessiveUseOfCobblestone** [comment]
I know >realism 
but I don't think these mobs would be in the same crate and not harm each other. Could it pick a "theme" (Jungle, Mining Asteroid, etc.) then spawn mobs related to the theme instead

**Comment by ExcessiveUseOfCobblestone** [comment]
you made a var and don't use it?

**Comment by KorPhaeron** [comment]
Don't think we need another source of hostile mob spam right now

**Pull request closed without merging**
