### PR TITLE
Prevents traitorlings from being created

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Ling powers+traitor PDA = ridiculous murderspree

### CODE REVIEW

**Comment by Amemelius** [comment]
Literally fun removal. It happens once in a blue moon, allows you to trade for stuff a regular tator/ling round wouldn't, stems meta (they have traitor gear -> they can't be a ling and vice versa), and is just !FUN! to go up against. They count as two antags anyway, so there's one fewer antagonist ingame.

Not even a problem or something that people complain about.

**Comment by MMMiracles** [comment]
I've never seen people complain about this and it rarely happens to begin with.

literal run removal :-1:

**Comment by Niknakflak** [comment]
:-1: Decently rare, fun removal, Kor is on a roll with a bunch of bad PRs again

**Comment by Incoming5643** [comment]
:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: 

Aw fuck, I can't believe you've done this

**Comment by CPTANT** [comment]
:-1: 

why?

**Comment by Iamgoofball** [comment]
:-1: nah

**Comment by MatthewWork** [comment]
:-1:

**Comment by KorPhaeron** [comment]
Guess not then

**Pull request closed without merging**
