### PR TITLE
NT Party Kit! Change your color on the go!

### PR DESCRIPTION
**Pull request by remuluson2**
## About The Pull Request
Add a small handhelp machine that will permamently change your skintone and/or hair color.
Embarrass a chameleon!
Now with 70% less chemical burns and horrible DNA damage from the usage(flavor text only, it won't actually harm you on use).]
Easily printable from any autolathe. Due to 28th amendment to WPE(Workplace Ethics) the Protolathe design is not available.

## Why It's Good For The Game
We have borgs, AIs, huge blackhole power generators and yet there is no way to permamently change your color. I tried to use spraycan to change my color but its face only and even then a bit of water is going to ruin all the work and dont get me started on janiborgs.
I want to give more freedom to folks like me that like to go overboard with stylizing and changing their look without worry about losing all the progress due to other mechanics.

## Changelog

:cl:
add: Added NT Party Kit to Autolathe that will allow you to change your color permamently.
/:cl:

### CODE REVIEW

**Comment by remuluson2** [comment]
I think about giving it an option to recolor items but I see the potential for griefing if you changed all the suits on the station grey.
Maybe some kind of durable paint that takes a bit to wash off would work but I want to get the base functionality of changing skintone working.

**Comment by remuluson2** [comment]
Also I plan to add a component for temporary skintone change as well so you can use the Party Kit to change your color for a tiny bit instead of permament.

**Comment by remuluson2** [comment]
> 
> 
> It seems your PR is currently not adding nor removing any line of code. You ought to change the code in some way.

Its just a base for the PR. I am gonna work on it in a bit but I just wanted to make the PR so i can put my changes somewhere safe.

**Comment by AlinaStarkova** [comment]
> > 
> > 
> > It seems your PR is currently not adding nor removing any line of code. You ought to change the code in some way.
> 
> Its just a base for the PR. I am gonna work on it in a bit but I just wanted to make the PR so i can put my changes somewhere safe.

all changes are safe on your branch if you commit it and push it, it doesnt need to be a PR to be safe. github tracks all changes and every commit pushed automatically and you can easily view and revert changes if need be

**Comment by itseasytosee** [comment]
I think this hurts the stylistic atmosphere.

**Comment by Krysonism** [comment]
https://youtu.be/BTtF7gzieN4

**Comment by ProfessorSniff** [comment]
I'm not sure if it's just me being incapable of reading, but what exactly would this PR do?

**Comment by Fryzzie** [comment]
changing your appearance to this degree is already possible using genetics, doesn't this cross over into changling/chamelon suit territory in terms of hiding who you are? It really looks like this would have balance implications beyond just looking stylish.

**Comment by AndroidMK2** [comment]
Add  a gold color paint please ;-;

**Comment by remuluson2** [comment]
> 
> 
> Add a gold color paint please ;-;

You can select any Hex color you want so I think it covers that.



> 
> 
> changing your appearance to this degree is already possible using genetics, doesn't this cross over into changling/chamelon suit territory in terms of hiding who you are? It really looks like this would have balance implications beyond just looking stylish.

That's why I opened up this PR. So I can have people point such stuff out. Can you please tell me how would one use genetics to change the skintone? I am not aware of such a way but I dont know if its because I never dabbled in artistic genetics or if its not possible.
Also yes. I am worried that it might upset balance and this is the reason I am holding off. Changing skintone for style would really be fun for me since I had no clue genetics were able to do it already. Sadly wiki is down atm so I cant verify if genetics can change skintone so can you please tell me how it is possible?

**Comment by Fryzzie** [comment]
changing things like skintone and body shape is done with the enzymes and features tab in the genetics console, Exactly HOW, is kinda arcane, I believe there was something on the wiki for it, but we'll have to wait for that to come back

**Comment by VladinXXV** [comment]
>Sadly wiki is down atm so I cant verify if genetics can change skintone so can you please tell me how it is possible?

1 - hair color
2 - facial hair color
3 - skin tone
4 - eye color
5 - gender
6 - facial hairstyle
7 - hairstyle

It's somewhat RNG (unless you copy/paste someone else's appearance exactly). IIIRC the 3 digits refer to simplified hex code or some shit like that (for the color segments, anyway). It's only possible to have /actual/ skintones as far as I can attest, you cannot become purple guy.
image

**Pull request closed without merging**
