### PR TITLE
cult has a minimum population of 35 to roll

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
cult has a minimum population of 35 to roll

## Why It's Good For The Game

we had a cult round on 19/29 pop shit sucked bad this shouldnt happen to anyone

## Changelog
:cl:
balance: cult has a minimum population of 45 to roll
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
absolutely never

**Comment by CCC23** [comment]
thank god no longer will I be punished with 20 pop cult

**Comment by Sadboysuss** [comment]
I'm surprised this wasn't already a thing, also this should probably be config?

**Comment by Striders13** [comment]
45 is ridiculous as this only counts people that ready up roundstart. I only see 45 people ready on Terry when it's above 60 pop. 30 would work.

**Comment by davethwave** [comment]
Have to agree with Strider. A 45 pop limit would make this almost never appear on sybil unless it's like a peak hour on a strangely good day.

**Comment by Mothblocks** [comment]
45 is overkill

**Comment by Deultus** [comment]
bro. just write a request to remove cult

**Comment by Jacquerel** [comment]
> This should probably be config?

AFAIK it is and this will only have any effect if not already overridden in the live config.
It's not terribly unlikely that the config in use is using default values for this field though.

**Comment by SimplySmiley123** [comment]
Hell yeah, hated getting cult on low-pop, shit's _miserable_ to try and play.

**Comment by mc-oofert** [comment]
it is now 35

**Comment by Loafin34** [comment]
nice.

**Comment by Singul0** [comment]
30 players sounds reasonable tbh, since there would likely be 5+ latejoiners, with 35 it's 40 if you include the usual number of latejoiners

**Comment by san7890** [comment]
i don't forsee this getting merged, especially since anyone can just say "tough nuts" and crank it down/up. if people really want this to be changed then i advise contacting your server's config operators and having a dialogue with them on what would work best for that server's rule and desired experience.

**Pull request closed without merging**
