### PR TITLE
Syndicate infiltrator update

### LINKED ISSUE #22522: The syndicate shuttle is in the main map files
For some reason the syndicate shuttle is in the main .dmm for the various maps we have available instead of being a shuttle template defined in  [_maps/shuttles](https://github.com/tgstation/tgstation/tree/e4053877ad6d29d80cf4a77f57db8359021d7080/_maps/shuttles). This means we have to modify every map if we want to touch the shuttle.

### LINKED ISSUE #31303: Shuttle corners rotate the wrong direction when the shuttle rotates.
What it says on the tin. Most noticeable with the syndicate infiltrator since now you can set its location and also rotate it, so the smoothed corners all stick out the wrong way.

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: WJohnston & ninjanomnom
add: Plastitanium walls smooth, fancier syndicate shuttles!
fix: Infiltrator shuttles have been moved out of the station maps and made into a multi-area shuttle.
balance: Titanium and plastitanium have explosion resistance (requested by Wjohn)
/:cl:

fixes #31303 
fixes #22522

infiltrator

### CODE REVIEW

**Comment by WJohn** [comment]
Thank you for this. Really appreciate it!

**Comment by uraniummeltdown** [comment]
What about a grey/black version of the smooth shuttle wall sprites? Also Paradise has sprites for syndicate/black shuttle windows

**Comment by Anonmare** [comment]
Might need to do some smoothing with the windows as well, the central airlocks with windows look weird

**Comment by ChangelingRain** [comment]
It should A: smooth into engine pieces, and B: have some corner version for those inside windows.

**Comment by WJohn** [comment]
Like I said, they're getting plastitanium-styled shuttle walls soon. They're already sprited, and simple need to be mapped.

**Comment by ExcessiveUseOfCobblestone** [comment]
Why is the smoothing of the walls and bomb resistance in the same pr???

**Comment by KorPhaeron** [comment]
@ExcessiveUseOfCobblestone Gotta bundle your PRs now to save on GBP

**Comment by AuroranAI** [comment]
>not just making issues so you can get GBP each pr

**Comment by ninjanomnom** [comment]
it's based on tags not issues

**Comment by DoctoreMad** [comment]
Where are the the turrets? Is it just not in the image?

**Comment by ninjanomnom** [comment]
They exist, it's just a bit dark

**Comment by MoreRobustThanYou** [comment]
I'D HAVE SEX WITH THAT SHUTTLE

**Comment by Anonmare** [comment]
Man smooth plastitanium looks great, a shame it ain't used anywhere else

**Comment by ExcessiveUseOfCobblestone** [comment]
@KorPhaeron can I get feature coupons next

**Comment by DoctoreMad** [comment]
@Anonmare They would if they had the same decon path as platsteel walls.

**Comment by Mercenaryblue** [comment]
Smooth walls looks great!

**Pull request merged**
