### PR TITLE
Finally completes the title saga.  The last puzzle piece, the suspenseful.

### PR DESCRIPTION
**Pull request by Niknakflak**
Adds title4.ogg to the game.  The final title music to complete the saga.  You have the original, the jazzy, the exciting/rock, and finally, the suspenseful.  Also known as traitor.ogg in some codebases.  
Trimmed slightly to 4 minutes for size.  Sits at a nice 3mb with good quality and ends nicely since I faded it and trimmed it nicely.

Actual file: https://file.house/wQ0G.ogg

The original: https://www.youtube.com/watch?v=QoUC23vl0y8

The song's license: https://creativecommons.org/licenses/by-nc-sa/3.0/
Tell me if I need to do anything.

### CODE REVIEW

**Comment by pudl** [comment]
I don't like this song.

**Comment by Incoming5643** [comment]
Doesn't really match the tone of the game

**Comment by Iamgoofball** [comment]
so THATS where bay got the song

Its good

**Comment by PKPenguin321** [comment]
I was skeptical at first but after sitting through the whole thing I think it's alright

Does it really need to be 4 minutes if lobby setup is roughly only 2, though?

**Comment by WJohn** [comment]
Yeah, I don't think it fits TG specifically. Works well enough on bay branches or elsewhere because it's more serious about its tone than here.

**Comment by Niknakflak** [comment]
Fits my paranoia game tbh

**Comment by KingDairy** [comment]
wait there's paranoia in this game?

**Comment by Kraseo** [comment]
Wait, what? You mean firefox_2016-10-11_17-19-30 WASN'T a meme word?

**Comment by xxalpha** [comment]
Do we really need another 4MB title song.

**Comment by Cuboos** [comment]
I was skeptical at first, but the NickNack's idea of "Original", "Jazzy", "rock", and now "Paranoia" kinda fits...

**Pull request merged**
