### PR TITLE
Removes clockcult from the game entirely.

### PR DESCRIPTION
**Pull request by Iamgoofball**
# WHY
No one likes it. It's boring, it's obnoxiously complex, it's filled with loads of shitty fucking shoehorned edgelord lore including it's own language and translator like some kind of shitty LOTR fanfiction.

We have too many shit conversion modes. Axing this and Gang will help.

Xhuis's PR isn't merged yet.

### CODE REVIEW

**Comment by InsaneHyena** [comment]
Every day until this shitpile is removed from the code.

**Comment by GunHog** [comment]
https://github.com/tgstation/tgstation/pull/30151

**Comment by Qbopper** [comment]
>he +1's his own PRs

**Comment by Iamgoofball** [comment]
Who doesn't?

**Comment by kevinz000** [comment]
good coders

**Comment by kevinz000** [comment]
goof will you drop it and stop mkaing PR-PRs (lol, public relations pull requests) for the sake of your campaign?

**Comment by Iamgoofball** [comment]
Prove it?

**Comment by Iamgoofball** [comment]
I love how the admins are last minute scrambling to defame and slander me. Real clean.

**Comment by optimumtact** [comment]
it's actively being reworked

**Comment by Iamgoofball** [comment]
@optimumtact As I stated in the last pull request, I'll close this when Xhuis's PR is merged so Joan doesn't steal it or close it.

**Comment by optimumtact** [comment]
that doesn't make any sense, stop shitting up the tracker with your crappy memes

**Pull request closed without merging**
