### PR TITLE
 Adds a new damage type, Internal Damage 

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Added a new damage type: Internal Damage, representing non-superficial brute damage to internal tissues and organs.
add: Internal damage is not externally visible, but can cause blood vomiting in high amounts.
add: Internal damage can be caused by: Heavy brute hits that hit the chest (15+ force), some toxins, ingesting acid, viral necrosis, explosion damage, being in crit, blood vomiting, admins.
add: Internal damage can be healed by: Cryo; Mending/Reconstruction surgery; Saline-Glucose (slowly) or Viscosine (faster) while also resting; Regenerative Jelly, Earthsblood or Pyroxadone without necessarily resting; some healing disease symptoms; the bio-reconstruction nanite program; most "heal-all" special or magical healing also includes internal damage.
add: Added Viscosine, made from 1 Synthflesh, 2 Carbon, and 1 Bicaridine. Rapidly heals internal damage (and only that) while the patient is in a resting position.
add: Added Mending surgery, made to rapidly heal internal damage. Reconstruction surgery also heals internal damage.
balance: Brute damage over 15 to the chest now deals a third of the damage as internal damage. The total is unchanged.
balance: Explosions now deal a percentage of their damage as internal damage. Bomb armor reduces this percentage (as well as total damage). Base value is 75%.
balance: Crit now also deals 0.5 internal damage per life tick (2 seconds). Non-breathing species that used to take brute damage in crit now only get the internal damage instead.
balance: Flesh-eating diseases now deal a portion of their damage as internal damage. Some thresholds have changed to interact with this.
balance: The symptoms Starlight Condensation and Tissue Hydration (with threshold) can now heal internal damage.
/:cl:

A new damage type serving as middle ground between toxin and clone damage in healing difficulty, making the medical system a bit more complex than drinking tricordrazine, and making the doctor role a bit more relevant. Self-healing is still possible with cryo or sal-glu, having a chem dispenser lets you heal faster, and more esoteric healing methods can skip the resting requirements (at the usual price of effort and/or risk).
The brute-to-internal conversion on chest hits allows for long-term damage as a counter against hit-and-run patch hoarders (_\*cough\*wizards\*cough\*_), since healing internal damage requires being stationary and somewhat vulnerable unless you have rarer chems.

**Since damage types are _everywhere_, i probably missed a few spots where internal damage should be considered or used instead of brute. Let me know if you find any.**

### CODE REVIEW

**Comment by Time-Green** [comment]
How does this affect organ damage?

**Comment by XDTM** [comment]
It is not related (yet) to organ damage, although it definitely could affect or be affected by actual organs once we standardize it a bit

**Comment by Steelpoint** [comment]
Not to disparage this but wouldn't a system where certain attacks that have the capability of dealing internal organ damage make more sense?

Smashing someone in the chest with a wrench is unlikely to cause major organ damage, stabbing a long spear through someone's chest is far more likely, or shooting someone with a high calibre bullet round.

**Comment by XDTM** [comment]
Technically it works exactly like you mentioned in my system, since wrenches are below the threshold while bullets and spears are. In any case any of our over-15 damage, whether it is by stabbing with a knife or being crushed by a hammer, is likely to mess up internal organs a bit.

**Comment by Steelpoint** [comment]
But then suddenly the Null Rod is causing internal damage, or any other item that deals the magical 15 brute damage.

The most complex system I know (SS13 wise) is in Lifeweb where spears, high calibre bullets, gut stabs, etc, etc, can damage the internal organs located there (can being the operative word, being shot in the chest won't always damage a organ).

I just feel 'internal damage' would be very arbuitary of a damage system.

**Comment by XDTM** [comment]
Thing is, the magical 15 damage already means it deals serious amount of harm, and it's not a stretch to say that it also deals some organ damage along with it. Since we have almost nothing that deals uneven (11-14) amounts of damage the cutoff is not too weird; and stuff that doesn't seem able to cause organ damage is either deceptively powerful or should not have 15 damage in the first place. The null rod is probably the former in this case.
Also worth noting is that this is _chest_ damage; 15 distributed damage is not going to cause internal damage by itself.

**Comment by anconfuzedrock** [comment]
Woo, this fixes disemboweling people on the first esword cut
I always wanted more blood loss, paprka knows we need it. Where would we be without a wizard nerf that just makes them take lich or healing staff or something? Probably banging together rocks in a cave where medbay is still just as fast but assistants would have less incentive to raid chemistry when doctors suck.

**Comment by coiax** [comment]
Why do we have both Reconstruction _and_ Mending surgery? Seems kind of redundant.

**Comment by Swiftkor** [comment]
I’d like to see this used in a way that promotes organ harvesting/organ transplants. Instead of adding a new surgery, maybe add some way to make replacing damaged organs heal the damage.

**Comment by XDTM** [comment]
Reconstruction also heals brute/burn and is mostly useful to prep corpses for defibbing or revival, since it's one of the few methods to cure corpses; but it has to be researched first.
Mending can be used from roundstart but cannot heal corpses.

**Comment by Mickyan** [comment]
Does this show up on medical analyzers?

**Comment by XDTM** [comment]
It does, like the classic damage types.

**Comment by PKPenguin321** [comment]
>The brute-to-internal conversion on chest hits allows for long-term damage as a counter against hit-and-run patch hoarders (*cough*wizards*cough*)

This is a bad thing and will just slow down wiz rounds
Also certain species shouldnt take this damage, like skeletons or golems

**Comment by Ratvar** [comment]
"Making the medical system a bit more complex"
=>Self-healing is still possible with cryo or sal-glu/chug mannitol 2.0 to heal braindamage 2.0
Good precursor for future PR's, no complexity added yet

**Comment by Ziiro** [comment]
Not sure I agree with this, even from the standpoint of someone who supports more in-depth damage and medical systems. I think that just calling it "Internal damage" is an abstraction too far.

Plus I feel like it kind of throws the naming convention out of whack. If Internal = Internal, then Brute = External? Wouldn't that technically make burns an external wound, rather than it's own damage type? etc etc.

From a technical standpoint I do agree there should be some kind of `TRAIT_` that makes a mob immune to this.

Couple things you should checkbox, as well:
* Miner's Survival Pen
* Legion Core
* Cursed Heart
* Admin rejuv
* Does the damage show up on the sleeper/cryotube

**Comment by Ratvar** [comment]
I think epipens should stop crit automatic internal damage increase. Or maybe not?

**Comment by k-k-karma** [comment]
no this is fucking gay and ruins combat

**Comment by Nickvr628** [comment]
This is really cool and I want to see this added, however I have some concerns.

1. Like others have said, I dislike the magic 15 number for dealing internal damage. Maybe instead have it check for weapons with the Sharp flag, since those would be the ones stabbing into you? Then do something similar for bullets, etc.

2. Very few people will want to do the surgery so this makes cryo even more of a magic fix-all solution, which I dislike. Cryo is a crutch and I think it would be neat if this gave a purpose to the surgical center so it does not go unused most rounds. 

3. This is a buff to bombs in general, not necessarily a pro or con on its own, but something to note.

**Comment by Anonymous583** [comment]
This does not sound good.

**Comment by Adanps** [comment]
I do want medical personnel to exist and I like the idea of being able to deal longer lasting damage that you can't just fix with a slap a bandaid on. However, on the other side, being completely crippled by injuries for extended periods of time can make for a miserable round. I think this is definitely worth testing to see if this makes for more interesting gameplay. I'd definitely rather have this instead of being disemboweled, which is essentially a death sentence.

**Comment by anconfuzedrock** [comment]
This doesn’t make the medical system deeper or more complex, just broader. This makes med more complex in the same way that adding 2 more legs to a table would. I don’t think that adding toxin damage 2.0 will do anything but dissuade anyone who would want to add an actually interesting form of internal damage, and this makes targetting the chest even more overpowered. 
Just adding another damage type to cause assistants to steal a new kind of healing chem won’t fix a thing, and blood loss is ass enough already.

**Comment by GravitronBlue** [comment]
Can't really agree with the point of this PR when blood already fulfills the idea of a long lasting and harder to treat medical condition. If blood mechanics aren't punishing enough why not make players lose a significant amount of blood from heavy hitting sharp weapons?

In terms of support:
 +1 for nerfing disembowelment
 -1 for having the proper fix be to drink another type of chem
_(PR sin for saying "making the medical system a bit more complex than drinking tricordrazine")_
 -1 for also requiring the standard ways to heal internal damage be methods that force the player to just sit and wait.
 -1 apparent stealth buff for .357 revolvers

Regardless I'd like to see viscosine or Saline-Glucose pills added to brute first aid kits if his PR ends up being merged.

...
Three years after #7239
>The baymed port has begun. Run for the hills.
Looks like we're all stuck on TG's wild HRP slippery slope ride now.

**Comment by anconfuzedrock** [comment]
I really can't stress enough that this awkward step between having an actual medical system and lacking one is just awkward and too simple, and it doesn't sync well with shit like organ damage, disemboweling, dismemberment, and embedding (I swear to fuck I think I'm the only person in history to try the remove embedded object surgery it's way too many fucking steps just to remove a rod from someone who is rapidly dying). I also can't see any reason for this byond to.. nerf wizards? which it isn't going to be able to do. This is just gonna lead to assistants stealing saline glucose for the wounds, or a new wave of shitty assistants tapping people with autolathe made circular saws so they now have to get internal damage fixed. I don't think this will be a good change, and I'd say it's a step down if anyone wants to improve the medical system further- I think of it as filling up a pothole with dirt. If anything, that will just draw attention away from the pothole and stop people trying to fix it.

**Comment by Vidiveni** [comment]
Regenerative crossbreeds should probably cure internal danage as well.

**Comment by Cyprex** [comment]
>Self-healing is still possible with cryo [or sal-glu]
I don't see how you can use cryo without someone else turning it on for you.
>Crit now also deals 0.5 internal damage per life tick (2 seconds).
I'm not very fond of this change. Crit is already often a death sentence without external help, making it more deadly seems bad to me. Barely hanging on and miraculously surviving is good, and should be kept in the game.

**Comment by anconfuzedrock** [comment]
Cryoxadone works with showers and space etc, and it's not the only way to heal internal damage.
Really though we do not need more sources of blood loss internal damage is just shitty blood loss and we don't need both and we definitely don't need them working in unison if internal damage is so shallow

**Comment by XDTM** [comment]
@adameltablawy The example with the HoS taking several shotgun hits and expecting to be back at 100% after ducking into a corner and slapping a patch is one of the main reasons for the concept of internal damage.

Also, blood vomiting happens at 50 internal damage, aka 150 normal damage (assuming you always get hit in the chest with >15 hits).

**Comment by BeeSting12** [comment]
I'd like this a lot better if it did damage to specific organs rather than just vaguely being called internal damage.

**Comment by optimumtact** [comment]
I just want to leave a note saying that I really appreciate the detailed conversations people are having here.

Those of you who left low effort comments (you know who you are) you have been dealt with accordingly.

**Comment by Steelpoint** [comment]
I feel the issue is that the more complex injuries and treatment become, the slower the game will need to be in terms of combat and movement.

**Comment by XDTM** [comment]
@BeeSting i actually agree, but i think this can be a partial step towards that, since currently only the brain and the liver have any sort of damage counter. As i said before, once organs are standardized all we'd have to do is swap the internal damage var for a random organ to bruise.

**Comment by XDTM** [comment]
Species with no organic internal organs are now immune to internal damage. This means golems, jellypeople (it's all jelly), skeletons, zombies (they don't really need them), androids and synths (artificial).

The lavaland extract in miner pens now heals internal damage. Legion hearts already do so as well since they cause an admin fullheal, so miners have options to keep going in the field.

**Comment by duckay** [comment]
I don't think we should have another damage system, I only see this as another layer to healing as a whole and I'm a simple man.
get hit, heal brute then heal internal organs
get virus, vaccine virus then heal internal organs
healed out of crit, oops internal organs

**Comment by XDTM** [comment]
Another layer of healing is a pretty good description of it all things considered.
If you keep getting poked by spears and healing back, you'll accumulate internal damage. From there you can:

- Get cryo'd - Pros: Simple, always there, heals other damage as well Cons: Leaves you extremely vulnerable, requires another person
- Get salglu and lie down for a bit - Pros: Easy to accomplish Cons: Slow and leaves you vulnerable
- Get viscosine and lie down for a bit - Pros: Faster than salglu Cons: Requires a chem dispenser, and still leaves you vulnerable
- Get surgery - Pros: Very fast Cons: Needs trust in another person as well as surgical tools/table
- Get advanced chems - Pros: Does not require standing still Cons: Hard to acquire without cooperation of the relative department (botany, xenobio)
- Get an internal healing virus - Pros: Always available, can be done on the move Cons: Usual risks about getting viruses
- Get internal healing nanites - Pros: Always available, can be done on the move  Cons: Usual risks about getting nanites

Long story short, the idea is that there is a spectrum of treatments that let you pick one or two between safe, fast, and easy to do.

**Comment by duckay** [comment]
what I mean is that it adds another layer to medical and makes medical a even more potentially dangerous place. Also fucks up nuke ops provided you chip away at their health with spears

**Comment by duckay** [comment]
what I mean is that it adds another layer to medical and makes medical a even more potentially dangerous place. Also fucks up nuke ops provided you chip away at their health with spears

**Comment by duckay** [comment]
that they can't do Anything about

**Comment by Steelpoint** [comment]
Well, Ops could have a easy fix in making their 'tactical medkit' combat hypospray have a medicine that also heals internal damage, it'd incentives Ops to buy the medkit (its better now) and if we do ever transition to a proper organ damage based system it'd be easy to swap the chems again.

Wizards are also not as horribly affected, if they took a Staff or Healing or a Wand Belt then internal damage is a non-issue thanks to the on command full heals.

**Comment by Steelpoint** [comment]
I'd imagine, in the future, that mechanical organs should be more resistant to damage, such as taking less damage (0.5) when they are hurt, or akin.

**Comment by XDTM** [comment]
Yes to both, antags who don't do stealth are supposed to have their own solutions to internal damage, and mechanical organs will eventually be resistant to damage (although that will have to wait for actual organ damage).

As a side note, you don't have to necessarily stay in medbay for your sal-glu recovery, you could lock yourself in a dorm or in a locker somewhere until you're healthy.

**Comment by XDTM** [comment]
Ops can now use medical cyborgs, combat medkits, or medbeams to heal internal damage. If they skip all their medical options it's probably likely that they'll die to more conventional forms of damage before having to worry about internal damage.

**Comment by Therapist1** [comment]
This leaves me with a question. Say you have a spear or some other fairly robust weapon that deals 15 damage, and you attack someone in the chest, but they are wearing some amount of armor (regular armor, sec jumpsuit, golem etc). What is considered first, splitting into internal damage, or the armor value?

**Comment by XDTM** [comment]
As it is coded right now, it checks at the end of the calculations, meaning that armor does prevent internal damage if the result is below 15. I did not consider that, and it does complicate things since 1% armor prevents a whole subset of melee weapons from dealing internal damage. I'm open to suggestions, but otherwise my best idea is to lower it to 13 to give it a bit of a threshold.

**Comment by anconfuzedrock** [comment]
Hnnngh, yet again, hivelord cores and  survival pens outclass medical in every way- this time, With healing medbay literally cannot reproduce with any chemicals short of cryoxadone + frost oil + hyperzine to get even a slower healing effect.
Does this actually effect disemboweling? If it doesn’t,  I think it should require an internal damage threshold before disembowling becomes possible, but what do I know, I’m going to hate this pr no matter what, not because it’s too complex, but because it’s too simple.

**Comment by JMoldy** [comment]
As someone who plays chemist fairly regularly, this isn't going to add anything to the jobs of poor medical doctors and is just going to be one more pill or patch I dump in batches of 30 into the fridge at roundstart. 

Also I have to say I just do not like earthsblood being a standing fix. Earthsblood is already a ridiculous chemical that basically renders medical bay obsolete save for a few niche things.

**Comment by Ratvar** [comment]
Medbay is obsolete because everything is better then medbay: premade chems, maint autocloner, antaghealing, botany, mining (and because medbay is "get dumped into cryo if you don't raid it for stuff")

**Comment by XDTM** [comment]
Having a chemist ensures that the recovery rate is six times faster by making viscosine. This does not change the chemist's job particularly but it makes having one more advantageous. Without one, the only non-assisted option you can get at roundstart is sal-glu and patience. Having a doctor in medbay enables the cryo or surgery options, virology enables regen viruses and so on. It's not about skill but resources.

**Comment by k-k-karma** [comment]
ok so basically if you get damaged as an antag you're fucked and out of the round? this discourages murderbone by a lot

**Comment by davethwave** [comment]
Only if they use a spear or something that deals 15+ brute.

**Comment by JMoldy** [comment]
It also screws over anyone who gets attacked by a murderboning antag on a lowpop round. Often there's just no choice but to patch yourself up.

**Comment by davethwave** [comment]
Just saying, but if your face to face with a murderboning antag or something similar, you are pretty much dead already. They have to kill quite a few people to get that title in the first place.

**Comment by XDTM** [comment]
For internal damage to matter you need to take more than 100 brute damage in the first place (minimum). If that happens you are either already dead or constantly getting hurt (which incidentally is why mining has some extra countermeasures). 

Another thing this adds is a reason to target the chest: the head causes brain damage, limbs get disabled/dismembered, chest is what you target if you want to cause some lasting damage.

**Comment by coiax** [comment]
> ok so basically if you get damaged as an antag you're fucked and out of the round? this discourages murderbone by a lot

You're saying that like it's a bad thing

**Comment by anconfuzedrock** [comment]
This doesn't stop antags at all though, multitude of ways to fix it by yourself. maybe slow but that doesn't matter if you're spam recalling. Murderbone is plenty discouraged by corpse tosses.

**Comment by AdamElTablawy** [comment]
I'm still mostly concerned by the changes to venom and the fact that this is untreatable damage to *crew* in fast paced rounds, for the most part.

Nuke ops being able to shrug off internal damage is nice if they prepare accordingly, but the HOS eating two stetchkins to the chest and patching himself up and still being useless for the rest of the shift because he can't be cryo'd and the chemists are useless as usual means that anything where the crew are going to be fighting one or several groups en masse and taking serious damage means their efficiency will drop much faster than normal and they'll be easier to steamroll.

I just don't like the change to venom going from 'enormous amounts of brute damage' to 'enormous amounts of seriously hard to treat damage', and the change for necrosis viruses to be even stronger than they already were when a properly made brute virus was already almost certain death and the main reason you'd take it over the axyphation virus is that it was harder to treat but not THAT much harder.

**Comment by XDTM** [comment]
Regarding venom: the traitor poison kit, its only source as far as i know, is already deadly enough for a near instakill when hitting someone with a syringe gun with the right mix of poisons. I can't see many situations where one only relies on venom for a kill when they can use everything else, so i figured it wasn't a balance concern in the first place.

As for necrosis viruses, i already lowered the total values to adjust for the presence of internal damage, but i might as well make them even slower, keeping the long term injury aspect but giving much more time for countering it. Would give it more of a niche, where asphyxiation would be better for a quick kill but necrosis stays until cured.

**Comment by anconfuzedrock** [comment]
Any set of poisons can be fuckhugelethal, sec already starts with murder syringes. One poison being stronger is a pretty small issue of this pr. Plasma was once one of the most lethal poisons, but a deathmix is already easily possible, venom or no.

**Comment by subject217** [comment]
Shower cryo isn't hard. Everything you need to do it spawns in medical and there's more of those supplies readily available.

**Comment by coiax** [comment]
Only Centcom would have showers so cold that you freeze to death in minutes.

**Comment by Bawhoppen** [comment]
I believe this is a positive step to fixing the absentee medical system we have, but I don't think it goes far enough. 
Having there still be options to self-heal like the saline glucose/cryo just means people will switch to using those instead of what they use now. We need to have a system that requires those who have taken serious damage, to need assistance from other players in order to heal that damage. So maybe, for example, instead of saline glucose just autonomously healing internal damage, it could somehow help the doctor doing the healing surgery to do it more quickly/efficiently (or something)?

Also, I feel this change is trying to conform to the existing balance structure far too much. 
Discussing changes about how this will specifically affect nukeops, for example, and how to mitigate that effect, is the wrong way to go about this. 
With a significant change like this, it will heavily impact every aspect of how the game functions and just generally how things play out. It's okay for these things to change though. It's really just a sideways-step; some things will be different, but not necessarily be any better or worse.
People's lives might start being viewed as more sacred, and situations overall as more risky. Security might suddenly be alot more powerful of a force, since they can publicly go to medbay for treatment, whereas antags can only slurk around in maint tunnels by their lonesome selves. But sec may also be weaker in other ways, such as revolutions, where they're vastly outnumbered. Ops, for instance, may start having to go back to their ships to give each other surgery mid-combat (well, maybe not this specific case, but you get my point). Who knows. There's lots of different new elements of gameplay that will end up emerging. Ultimately, we just have to try it out, and then adjust things to make sense within that new framework of gameplay accordingly.

**Comment by necromanceranne** [comment]
Oh no, we need to rely on chemistry and doctors to heal physical injury.

_How dreadful._

In all seriousness, this does give purpose to cyrotubes which they’ve sorely lacked for some time. With the presence of perfect cloners otherwise rendering them pointless, and the only threat of clone damage on the station also having access to the means to cure clone damage in department (xenobio), and the role that would be most negatively affected by the change having compensatory changes themselves (mining), what this basically changes is how we approach damage in every other instance.

The concerns raised so far has largely been ‘gee, I can’t be an entirely solo powerhouse anymore because I’ll die, this sucks’. Such a change is honestly a good one. You should never have been able to completely invalidate a department using some brute patches you picked up early in the round, and putting a hard limit on your ability to survive a fight makes prolong and extended conflicts a losing battle unless you prep for internal damage. This IS an anti-murderbone change but nobody enjoys those anyway so the only people who would complain are those who are shook to their core thinking they’ll need to use their talk key for once.

It also makes non-stun weaponry actually a threat. Who knew taking a bullet to the chest would be something you should be worried about?

**Comment by AdamElTablawy** [comment]
@necromanceranne The condescension is hardly necessary, especially when 'we need to rely on doctors and medbay to do their jobs how painful' is a valid fucking concern outright.

The reaction hasn't been 'I can't be an entirely solo powerhouse anymore', the reaction has been _every fucking gamemode we have relies on people being able to take a beating and get up if they don't die_. That's the problem with broken bones, and internal bleeding, and whatever-the-hell else people keep wanting to add. It's a nice idea in theory and works well on slower servers with less combat and less intense gamemodes and falls through badly when it comes to something like cult or rev because then the hos takes one hit from a juggernaut and it's just no longer viable to treat him when the treatment takes time and is somewhat intense.

Cryo is all well and good, but if nuke ops show up and you take two shots from a shitty c-20 to the chest and now you have internal damage, chances are, you don't have the time to go into cryo, because by the time you do the fight will be over one way or the other.

So no, it's not 'just people who want to murderbone' who are not fond of this change, because chances are murderboners don't really care if they die or not as long as they kill a ton of people and ruin a ton of rounds-the problem lies in that this is a dangerous damage type to add on to brute damage for the same reason that arbitrarily changing a laser from 20 burn damage to 10 burn damage and ten clone damage is a problem-because now the damage is untreatable, and so it's significantly more dangerous.

There is a reason the Decloner isn't a gun that's available with any amount of ease, and why things that do clone damage are so powerful-not only can it not be treated on the go, which also applies to tox damage, not nearly as dangerous-but it can't be treated with any amount of ease at all, so taking any of it means that you're going to be out of commission for a while.

Simplifying things to 'good change anyone who dislikes is just upset they can't murderbone' is fucking stupid. I'm in favor of making medbay more involved and complex but there's not really a way to go about it with /tg/ in its current state because _easily accrued untreatable damage_ does not mesh well with a group antag round where anyone involved in a fight is likely going to constantly be taking a beating.

**Comment by Vidiveni** [comment]
'Consuming purple' crossbreed cookies and all 'regenerative' crossbreeds should heal internal.

**Comment by necromanceranne** [comment]
@XDTM So by the way, would you allow bible smacks to heal internal damage? As it stands bibles are already very good for the healing they provide though comes with the issue of brain damage. Internal damage might weaken that considerably.

**Comment by XDTM** [comment]
Probably not, it seems too easily available to let it heal internal damage.

**Comment by AdamElTablawy** [comment]
Bible beating should absolutely fix internal damage, considering brain damage is horrible now.

**Comment by SpaceManiac** [comment]
Merge conflict for nearly two weeks, closing as stale

**Pull request closed without merging**
