### PR TITLE
Refactors Suicide Verb + Basic Mobs (actually all (most) living mobs) Can Now Suicide

### LINKED ISSUE #72903: Basic mobs do not implement `verb/suicide`
Also everything implements it differently and I hate it

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

On the tin. There was a lot of needless copy-paste and a lot of single-letter vars and weird indentation and... well just all of it was at least eight years old. So, I decided to "abstract" as much as I could of it out instead of piling onto the big copypaste clusterfuck for implementing basic mob suicide.
## Why It's Good For The Game

Fixes #72903

Having more procs that can be easily repeatably called to the same results is much better than having to transplant the same exact three lines everywhere. It's also a good first step to further in-depth behavior by allowing sub-type overrides of certain procs (which is quite nice). Just feels more extensible overall for the next guy who wants to add funny suicide behavior whenever they might come around.

There's probably a few better ways to do what I did, but I wrote code comments explaining why I did what I did. I think there's a few ways to make it more agnostic, but I think that'll be another can of worms that will bloat out an already quite large PR. Let's just get the framework set.

(this refactor should also make it quite easy to unit test suicide actions :eyes:)
## Changelog
:cl:
fix: All Mobs (including Basic mobs) are now able to suicide. (warning: some exclusions remain)
/:cl:

### CODE REVIEW

**Comment by Zytolg** [comment]
No! Not Ian!!

**Comment by san7890** [comment]
test merging on sybil/manuel to just really make sure i didn't screw anything up

**Comment by san7890** [comment]
idea for the future would be moving it out of the "message tree" proc that i put here and moving it to procs that rest in the mob's code file and return a string but holy shit it's already massive

**Comment by Mothblocks** [comment]
Can we put the verb on living itself?

**Comment by san7890** [comment]
> Can we put the verb on living itself?

yeah. it's in now

**Pull request merged**
