### PR TITLE
Removes an old blob tip

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ike709** [comment]
>sillytips.txt

>Occasionally the tip of the round might lie to you. Don't panic, this is normal.

**Review by Cyberboss — APPROVED** [review]

**Comment by praisenarsie** [comment]
``strings/sillytips.txt``

morty: 🤔 💭 silly... tip...?

morty: 🤷‍ ah well better remove it then

**Comment by MoreRobustThanYou** [comment]
better dislike #34214 too

**Comment by DaxDupont** [comment]
Keep the salt to your own pr

**Comment by optimumtact** [comment]
These silly tips being slightly misleading are on purpose /shrug

**Comment by Cyberboss** [comment]
Considering that these are seemlessly mixed in with the regular tips, isn't it a bit wrong tell a straight lie?

**Pull request closed without merging**
