### PR TITLE
Makes the xeno nest ruin harder to cheese.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
balance: Makes the xeno nest ruin harder to cheese.
/:cl:

[why]: Removing a single wall to spawn a round ending antagonist seems kinda silly, this should stifle that, but not make it impossible to unleash the xeno.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
looks like all you're doing is adding a layer, why not shift the queen into the center of the ruin?

**Comment by 81Denton** [comment]
@mapdiffbot

**Comment by DaxDupont** [comment]
@ExcessiveUseOfCobblestone I also added a layer of lava

**Comment by DaxDupont** [comment]
Can't really take those back walls down with lava unless you're lavaproof.

**Comment by ExcessiveUseOfCobblestone** [comment]
A random bit of lava seems really low-effort though :(

**Review by ShizCalev — APPROVED** [review]

**Comment by Ratvar** [comment]
Ashwalkers/miners rcd lava, plants cherrybomb lava and fill cjasm in

**Comment by DaxDupont** [comment]
Do ashwalkers spawn with an event?

**Comment by SpaceManiac** [comment]
>Do ashwalkers spawn with an rcd?

Yes.

**Comment by Shadowflame909** [comment]
This is a godsend. Yet it's still cheesable by ash lizards. I'd just remove the eggs and make the alien queen spawn an egg sac on gibbing. As xeno mobs dont have organs.

**Comment by Kromgar** [comment]
Jokes on you now i csn kill the xenos by making them path into lava

**Comment by Kromgar** [comment]
@shadowflame909 So you want miners to get instantly facehugged fof braving the nest?

**Pull request merged**
