### PR TITLE
Removes the lizard mamaries

### PR DESCRIPTION
**Pull request by WJohn**
At some point this got undone, not sure how or why.

Shitty anatomy and realism reasons etc.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
CONTROVERSIAL TAG

**Comment by daman997** [comment]
make the lizards realistic again :+1:

**Comment by Iamgoofball** [comment]
do i need to go find the catboobs BS12 argument thread

**Comment by Anonmare** [comment]
Leave the lizard tits in tbh

**Comment by Bawhoppen** [comment]
:frog: :ghost:bs

**Comment by Bawhoppen** [comment]
ok maybe that one was a little too abstract but still

**Comment by Cebasiz** [comment]
why

why would you remove tits from a game

tits are love, tits are life

any tits in any game should be protected

decoder wjohn

**Comment by KazeEspada** [comment]
:+1:  Those damn ERPers distracting from the might that is the TRUE LIZARD MASTER RACE! YOU FURFAG HUMANS ARE NOTHING MORE THAN PREY ANIMALS.

**Comment by Aranclanos** [comment]
retarded shit after the freeze please where i ignore everything

**Comment by okaw** [comment]
Realism in a game like SS13? Especially realism on an "anthro" race?
Please

**Pull request closed without merging**
