### PR TITLE
Extends the IC chat filter to be checked in two major renaming procs

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Honestly, I'm not sure this is the... Correct solution? But people more familiar with this will likely show me da wae.

Prohibits creating names that can't actually be spoken in-character due to chat filters by adding CHAT_FILTER_CHECKs to the procs that handle sanitising them.

For admin-utilised renaming procs, they'll be given a simple alert box to warn them their chosen name contains words prohibited by the IC chat filter and be allowed to confirm or cancel out.

## Why It's Good For The Game

If you can't speak the name IC, chances are the name shouldn't be allowed at all. Players may occasionally be forced to ahelp certain names because they contain words prohibited in chat filters.

## Changelog
:cl:
fix: Names that don't pass the IC chat filter are now more prohibited from being set in various locations including pet name tags and the character preferences menu.
admin: You will now be warned when using VV auto-renaming features if the name you've chosen is blocked by the IC chat filter for any reason and will be allowed to confirm or cancel it.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
👎 this kills Uranus XD

**Comment by MrStonedOne** [comment]
Fully replace character name is used by admin renaming tools and should not be filtered, instead everything that calls it should check reject_bad_name OR! the proc can just get an argument to check the name with reject_bad_name and admin rename can skip it.

**Comment by optimumtact** [comment]
This only further encodes the mistake that is the chat filter

**Comment by Timberpoes** [comment]
I will address MSO's concerns later on today or tomorrow. This is not forgotten about, but the admin proc is used all over and there may be room for improvement.

**Comment by Timberpoes** [comment]
Removed the check from `fully_replace_character_name` and added additional checks in 2 admin places giving a simple alert box telling the admin their proposed new name doesn't pass the IC chat filter - But still allowing them to go ahead and rename anyway if you they wish.

Covered a couple of other edge cases where name inputs weren't run through filters - Cyborg renaming boards and pet name collars.

**Comment by optimumtact** [comment]
Lord forgive me for my crimes

**Pull request merged**
