### PR TITLE
Makes t-rays detect mobs in pipes

### PR DESCRIPTION
**Pull request by AnturK**
What it says on the tin.

space station 13 2015-10-13 213041

### CODE REVIEW

**Comment by bgobandit** [comment]
:+1:

**Comment by RemieRichards** [comment]
:+1:

**Comment by WJohn** [comment]
Sprites are pretty bad, but it's a neat feature.

**Comment by AnturK** [comment]
I just recolored shield effect. I suck at spriting.

**Comment by KorPhaeron** [comment]
Finally we can re-enact Aliens

**Comment by Lumipharon** [comment]
Very good idea, bad coder sprites though.

**Comment by Core0verload** [comment]
:+1:

**Comment by duncathan** [comment]
:+1:

**Comment by duncathan** [comment]
Is this only on the normal t-rays, not the goggles? I'd suggest you leave it off the goggles; it's nice to have reason to use the real scanner.

**Comment by AnturK** [comment]
Yeah that works for the handheld version only now.

**Comment by Fox-McCloud** [comment]
very nice. :+1:

**Comment by CPTANT** [comment]
Atmos t-ray goggles should detect though, they have the same power as the handheld ones.

**Comment by tuypo1** [comment]
yeah same power but it would be to op if the goggles detected things

**Comment by SweaterKittens** [comment]
There's no reason that the goggles shouldn't do the same thing, both occupy a slot on your person that isn't your hands. It just seems unintuitive that the goggles don't work, given that they serve the same function and just use a different slot. Any job that has access to the goggles generally starts with the scanner anyway.

Overall I really like the idea though.

**Comment by duncathan** [comment]
For what little it's worth, as the guy who added the t-ray goggles I'd prefer for this functionality to be left off of them.

**Comment by Razharas** [comment]
Make it transparentish

**Comment by Bawhoppen** [comment]
fuck yes pls merge soon

**Comment by AnturK** [comment]
I'm not sure on the goggles. I'll go with path of least work for me and leave it handheld only for now.
I'll add changelog in a moment.

**Pull request merged**
