### PR TITLE
Adds explorer belt to mining vendor.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Adds an explorer belt to the mining, will definitely be useful now that mob drops on mining are desirable to carry back to use for crafting. 
:cl:
rscadd: Miners can now select explorer belts from the mining vendor using their vouchers, or mining points. 
/:cl:

@KorPhaeron 
Merge all TechnoAlchemisto PRs
Hooray all TechnoAlchemisto PRs
Support all TechnoAlchemisto PRs

### CODE REVIEW

**Comment by coiax** [comment]
WILL YOU CHOOSE THE EXPLORER BELT OR THE LIFEBELT JAUNTER?

I bet you'll regret one of those when you're falling in a chasm!

**Comment by Bawhoppen** [comment]
>letting it hold pickaxes

excuse me?

**Comment by coiax** [comment]
SOON: Pocket pickaxe.

**Comment by TechnoAlchemisto** [comment]
Pickaxes go into the loops!

**Comment by Zilenan91** [comment]
Can you get one of these with a voucher

**Comment by KorPhaeron** [comment]
Maybe replace the 2 spare capsules with a spare capsule+belt

**Comment by TechnoAlchemisto** [comment]
Hm that wouldn't be a bad idea, let me look into that.

**Comment by TechnoAlchemisto** [comment]
It Is Done

**Comment by coiax** [comment]
Will you be able to put this belt in a backpack?

**Comment by PKPenguin321** [comment]
looks like it.
this needs to have a higher w_class so it cant be stored in backpacks

**Comment by Zilenan91** [comment]
Why though? It can only hold whitelisted items

**Comment by KazeEspada** [comment]
Put Pickaxe on belt, put belt in bag.

**Comment by TechnoAlchemisto** [comment]
kk

**Pull request merged**
