### PR TITLE
Ports TGMC smartfridge sprites, remakes security TV and Booze-o-Mat sprites!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin! It gives a face lift to mildly old sprites and keeps it in line with the 3/4ths perspective we're currently trying to keep. Extra credits go to @maxymax13 for improving on the shading of the security TV, and @Krysonism for giving it the finishing touches on all the sprites, and adding an awesome antenna of the security TV!

Image:
image

## Why It's Good For The Game
More consistent spritework, makes the rather bad looking security TV look absolutely gorgeous!

## Changelog
:cl: PositiveEntropy, Kryson, maxymax13
imageadd: The Security TV, Smartfridge, and Booze-o-Mat now have new updated sprites!
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
how do they look on their side? can they be rotated? we have a number of fridges that are accessed from left/right especially in chemistry which can be accessed from both sides and may even have a door under it, does it look wierd like that? (especially having a door right under one, or it being on a bottom wall, it would look like its facing into the door or wall)

**Comment by Imaginos16** [comment]
> how do they look on their side? can they be rotated? we have a number of fridges that are accessed from left/right especially in chemistry which can be accessed from both sides and may even have a door under it, does it look wierd like that? (especially having a door right under one, or it being on a bottom wall, it would look like its facing into the door or wall)

To answer the first question, this doesn't have directionals yet unfortunately, as any other vending machine currently. TGMC sort of remedies this by having them close to a desk or the sort, but I understand the issues it may cause.

**Comment by AlinaStarkova** [comment]
> 
> 
> > how do they look on their side? can they be rotated? we have a number of fridges that are accessed from left/right especially in chemistry which can be accessed from both sides and may even have a door under it, does it look wierd like that? (especially having a door right under one, or it being on a bottom wall, it would look like its facing into the door or wall)
> 
> To answer the question, this doesn't have directionals yet unfortunately, as any other vending machine currently. TGMC sort of remedies this by having them close to a desk or the sort, but I understand the issues it may cause.

its fine, if its really an issue for at the very least we can probably manually rotate the icons in sdmm for any area where these face a wall or door, wont look the best but will be better than facing a wall. we used to do that for the robotics fabricators since you couldnt rotate those in game either

**Comment by maxymax13** [comment]
fridges have 0 shading and look bad, they're supposed to be parts of wall,s, not thin panels near walls. doesn't fit any wall design, either new or current

**Comment by AlinaStarkova** [comment]
> 
> 
> fridges have 0 shading and look bad, they're supposed to be parts of wall,s, not thin panels near walls. doesn't fit any wall design, either new or current

these would fit 2/3rds walls when we get them, even more if they could rotate, but admittedly yes, currently they dont really fit since fridges arent technically supposed to be their own unit, they are actually merged with a wall (specifically a girder)

hence why these wont really work on any wall except the north wall, since left/right/bottom walls will have the sprite facing the wrong way, granted again, in sdmm we can rotate the sprite if we have to but its better if the machines actually have the built in ability to rotate

**Comment by maxymax13** [comment]
> these would fit 2/3rds walls when we get them, even more if they could rotate, but admittedly yes, currently they dont really fit since fridges arent technically supposed to be their own unit, they are actually merged with a wall (specifically a girder)
> 
> hence why these wont really work on any wall except the north wall, since left/right/bottom walls will have the sprite facing the wrong way, granted again, in sdmm we can rotate the sprite if we have to but its better if the machines actually have the built in ability to rotate

wrong, and also that's not what 3/4 is called. these would look like there's a hole in the wall where a much thinner and shorter slab is on 32x48 walls

**Comment by Imaginos16** [comment]
Updated the smartfridge and booze-o-mat sprites with the help of @Krysonism.

**Comment by Krysonism** [comment]
I personally think the smartfridge on top of wall design makes no sense and should be done away with.

While the lack of directionals might look strange in some cases, it is not worth investing energy in making dirs for the smartfridge at this time, since we already have a new smartfridge sprite on the wall branch.

bild

In the meantime, i think benefit from having 3/4th projection smartfridges outweighs the negatives.

**Pull request merged**
