### PR TITLE
Sec Resprite Fixes

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Initially meant to be a quick fix for the black splotches on the sec resprite. Upon further inspection found multiple consistency issues, missing inhand resprites, awkward designs, and poor quality assurance. This PR fixes those issue.
dreamseeker_8Bq1ehS6CJ
Sec helmets have been slightly reduced in size.
Normal sec helmet chin strap has returned.
Alt sec helmet will keep the no-chinstrap look.
Sec wintercoat hood now looks like a hood for a wintercoat.
New sec armor has been slightly reduced in size.
Black splotches on sec pants have been removed.
All sec personnel shoulder patches are now on both arms.
Sec uniform belt buckle is now black for a better distinction between sec and warden.
Fixes secskirt skirt size.
Fixes gold trim on hos uniforms.
Adds sec helmet inhands to match the new sprites.
Adds sec wintercoat inhands to match the new sprites.
Adds sec helmet obj icons to match the new sprites.
Fixes squished secskirt obj icon.
Things i probably forgot.

## Why It's Good For The Game

Department uniforms, especially sec, should be clear and concise. Red and black chaps are overcomplicated and unnecessary. Consistency is all things good and pure.

## Changelog

:cl:
imageadd: fixes previous sec resprite issues, replaces sec helmet and sec wintercoat inhands, replaces sec helmet obj icon
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
For the record, and as the original spriter of this stuff. I don't approve this PR.

The red and black pants were a conscious design decision because pure black or red pants are boring. The patch only being one arm is intentional. The sec vest is supposed to be big. No chin-strap is intentional because it looks bad.

I'm incredibly disappointed in this PR, and in all honest, kinda fucking annoyed by it. It's neutering down my original creative vision as the creator of these sprites. All these "fixes" are poorly chosen design changes hidden behind a veneer of "quality assurance".

Whilst this is an open-source codebase, and people _are_ allowed to change things, this PR is a downgrade to the originals besides from the minor bug fixes. All the design changes just make it worse. 👎

**Comment by tralezab** [comment]
the compromistitution strikes again

**Comment by VladinXXV** [comment]
Could we consider a bronze colored belt buckle for basic secoff? It's just a thought. The black belt buckle doesn't really translate into a belt buckle, it ends up looking like the jumpsuit has this awkward black upside-down T thing going on. Having a distinct belt buckle _slightly_ helps mitigate this effect, but the black belt with a black belt buckle just doesn't have enough contrast.

**Comment by CRITAWAKETS** [comment]
Most of the changes are good but the black-and-red pants were cool.

**Comment by realthomas69** [comment]
definite improvement

**Comment by bruhman8ghughug** [comment]
this fixes most my issues with the re sprite besides the new small as fuck for some reason HOS cap, 👍

**Comment by OrionTheFox** [comment]
There's a few other small fixes that were missed for the sec resprite, if you're already here and it's not too much...
- Sec Wardrobe still sells `shoes/jackboots` instead of `shoes/jackboots/sec`
- Sec Locker still holds `suit/armor/vest` instead of `suit/armor/vest/alt/sec`
- ~~`head/hooded/winterhood/security`'s description calls it red, it is now grey~~ you changed it to have red in this PR
- `head/hooded/winterhood/security` has an outdated Obj icon
- (Unimportant) Mafia security doesn't have the new boots nor vest

**Comment by ShizCalev** [comment]
Make the updated inhands a new sprite please, there are things that shouldn't have the red color that use it.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Make the updated inhands a new sprite please, there are things that shouldn't have the red color that use it.

**Review by axietheaxolotl — CHANGES_REQUESTED** [review]
Okay, I've cooled down a bit, and apologized on discord. But I still would like my own personal pass-over on this, at least, as the original sprite's creator.

- If you're deadset on removing the blobs from the pants (which I still don't think is a good idea, but whatever), I'd _much_ prefer they be black instead of pure red. Black was the primary colour of the pants, I just added the red part in later.
- Why was the sec vest trimmed? It was supposed to look bulky, and now well, it doesn't. I'd prefer it be brought back to the original state, or at the very least have it's "collar" return.
- Remove the chin-straps again. I deleted them completely intentionally because I felt they clashed with the vest. Pixel overlay and layers and all the jazz. It's such a minor thing anyway that I feel like it's re-inclusion is just kinda pointless.
- Why is the patch now on both arms? It was completely intentional to be a one-armed thing, asymmetry is nice and adds to designs.
- Return the sec-helmets back to how they looked before. You've made them less angular now, and more homogeneous with the bulletproof, something I didn't really want. I liked the angular/bulky/edgy look, now it just looks like a normal smooth helmet with some dents added.

My tone to this PR has softened, and I do thank you for the numerous actual fixes in this PR, that I didn't do in my original one. However, I'm not entirely sold on these design changes, whilst I'd prefer to just keep the original designs, if this is a must change, I'd appreciate _some_ input, as I was the original creator.

But, your the boss and all that. Here's my input, I must go now, my planet needs me.

**Comment by dalmationer** [comment]
I much prefer the more chunky and toyetic sec vests that Axie initially drew, I've gotta say. They're so SATISFYING to look at... The trimmed down versions just don't feel bulky enough to meaningfully alter the silhouette, which was one of the big things I liked. It's cool when you can tell by a silhouette that someone's a security guard.

**Comment by ShizCalev** [comment]
Just a heads up, bulletproof helmets have the wrong color visor when worn.

**Review by Imaginos16 — APPROVED** [review]
Wow! What a good PR!

**Pull request merged**
