### PR TITLE
Emagged Airlocks Are Easier To Deconstruct

### PR DESCRIPTION
**Pull request by ghost**
You can emag many airlocks very quickly and it's a lot of work waiting first for a minute to elapse (so the airlock regains power), fiddling with the wires and finally welding + crowbarring. I know you can use an RCD but it should not be this tedious without one.
Changed it to be like Baycode servers where all you need to do is crowbar the airlock when the panel is open to deconstruct it if it's emagged

:cl:
tweak: Emagged airlocks can now be deconstructed simply by crowbarring when the panel is open
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
Thank god for this, fixing emagged doors is just not practical when it takes ages.

**Comment by DaedalusGame** [comment]
fucking yes finding the goddamn bolt wire took the greater part of 15 minutes for one airlock and i had to get a new airlock electronic to boot can fixing things please be easier than rebuilding them from scratch

**Review by Cyberboss — APPROVED** [review]

**Review by Jalleo — CHANGES_REQUESTED** [review]
It would be even better if instead you could just switch out the airlock circuit completely if emagged. That would make it much more appropriate for the shorter round times. Also our airlock circuits dont stack which makes it more of a hassle of managing them (I think Bay's stack)

**Comment by Cyberboss** [comment]
Feel free to PR that @Jalleo, in the meantime this is a much needed QoL

**Pull request merged**
