### PR TITLE
Revert "[Fuck Shotties] Makes shotguns specialist weaponry." Because the PR was literally untested before merge

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#55663
Code was literally untested before it was merged to master.
103144231-43e95480-46fc-11eb-95d9-791b17eae1f5

Come on, guys. Test your code before you ask maintainers to merge it to master. At the bare minimum just compile it locally and test things you changed.

I make a video of each change I do and post it in coderbus to demonstrate I tested my change under the basics. Y'all should too.

### CODE REVIEW

**Comment by wesoda25** [comment]
The merge felt very reactionary. But because of that this will probably get closes too, although I hope not.

**Comment by necromanceranne** [comment]
Why not fix the broken stuff instead.

**Comment by MrDoomBringer** [comment]
make a patch PR then in what world do you think this will get merged uwu

**Comment by ExcessiveUseOfCobblestone** [comment]
Is this the only bug, and is that bug breaking the game so bad we need a revert? It’s dumb but not worth reverting.

I don’t like kneejerk reverts so I’m gonna close this unless there’s something else.

**Comment by Iamgoofball** [comment]
@ExcessiveUseOfCobblestone I figure on the offchance more serious bugs get discovered, we have this open in the tracker with a number so the testmerge machine can go brrr

**Comment by ExcessiveUseOfCobblestone** [comment]
Smart

**Comment by interestingusernam3** [comment]
Name

**Pull request closed without merging**
