### PR TITLE
You run faster with the knife

### PR DESCRIPTION
**Pull request by Incoming5643**
You now run very slightly faster holding a knife in your hand.

This applies to:
Kitchen Knives
Butcher's Cleavers
Ritual Knives
Switch Blades
Energy Daggers (only when on)

:cl: Incoming5643
rscadd: As a balance for its poor range and relatively low killing power, you now run ever so slightly faster with a knife
/:cl:

And yes, the effect is doubled if you dual wield.

### CODE REVIEW

**Comment by optimumtact** [comment]
:+1:

**Comment by Bawhoppen** [comment]
Best :+1: :me

**Comment by duncathan** [comment]
Fascinating :+1:
This is a very neat way to balance things

**Comment by lzimann** [comment]
we cs now

**Comment by Anonus** [comment]
ACTUALLY REALLY INTERESTING BALANCEWISE YET SOMEHOW ALSO A MEME
:+1:

**Comment by GunHog** [comment]
I have an idea as to the inspiration for this PR...
serveimage

**Comment by swankcookie** [comment]
very :+1:

**Comment by MMMiracles** [comment]
knife skins when?

**Comment by Fox-McCloud** [comment]
:-1: 

The way movement speed works, this will either have no effect or be very noticeable.

**Comment by Zilenan91** [comment]
So how much faster do you move exactly

**Comment by swankcookie** [comment]
0.2 faster

**Comment by swankcookie** [comment]
0.2 speed 
https://i.imgur.com/E1YRsXQ.jpg

**Comment by PKPenguin321** [comment]
it's almost like you *want* me to post "SS13: Global Offensive" memes
but yeah :+1: good joke

**Comment by Zilenan91** [comment]
Now all we need is a 1 TC revolver for nuke ops that one shots people that has infinite projectile speed and to make it so bulldogs shoot one tile away from where you were aiming randomly

**Comment by PKPenguin321** [comment]
zilenan, you almost forgot to make the bullets pierce for multi one-hit kills! fucking plebeian

**Comment by Zilenan91** [comment]
Oh yeah I forgot that this gun shouldn't even need headshots to oneshot people. I feel it's very balanced at one TC merge immediately playtesting is for nerds

@Incoming5643 Do you mind buffing kitchen knife brute to 12 while you're at it?

**Comment by Fox-McCloud** [comment]
normally it takes 6.6 seconds to go from the wall at central primary (above the bridge) to the airlock doors straight to the west of this.

With a SINGLE knife, this time goes from 6.6 seconds dwon to a mere 3.5 seconds---nearly doubling your movement speed.

You just can't have fine grained control of movement in SS13 like this--factional numbers end up getting rounded because of how movement speed works in relation to tickrate/FPS.

Literally everyone and their brother will carry around knives 24/7 with this change and just run around with it willy nilly because of the insane speedboost this give.

Baddd badddd idea.

**Comment by Incoming5643** [comment]
I've heard from multiple sources that decimal speed changes are a functional thing. Did you actually test this PR or are you just quoting form memory?

**Comment by Fox-McCloud** [comment]
No, I actually tested it because -0.2 is oddly specific.

Decimal numbers *do* work to a degree, but it's still VERY stairstepped and the speed increase from one tier to the next can be *very* dramatic.

I really do wish SS13 had non-tier precise movement speed, because you could do thing like "5% faster" and such, instead of working with nebulous "slowdown" which is very difficult to fine tune.

**Comment by Incoming5643** [comment]
Alright well since this isn't supposed to be a dramatic benefit and I'm not looking to refactor movement code to make sense. I'll have to test smaller numbers to see if there's anything practical.

**Comment by Incoming5643** [comment]
alright yeah there's still no real gap between default runspeed and max speed here. Until movement code is less terrible this is one meme/decent idea that will have to wait.

**Comment by Fox-McCloud** [comment]
Yeah, I should clarify--if movement speed was very fine-tuned and you could add tiny tiny little values, then this would be a great addition...but sadly, the system just isn't there =(

**Pull request closed without merging**
