### PR TITLE
Fixes the AI upload being exposed to space

### LINKED ISSUE #9642: Chunk of AI upload is missing due to map conflicts.
WHY.

### PR DESCRIPTION
**Pull request by ghost**
space station 13 2015-05-25 114804

Despite the screenshots, the turret control is set to Stun by default. Also re-adds the "PACKETS" plaque.
Also fixes Toxins Lab incinerator airlocks not being heat-proof.
Fixes #9642

### CODE REVIEW

**Comment by Miauw62** [comment]
stop making feature PRs during the freeze, this is intended behavior and should have been discussed in IRC.

**Comment by Iamgoofball** [comment]
add the plaque anyways

PS. WHAT HAPPENED TO THE PACKETS PLAQUE

**Comment by Incoming5643** [comment]
hey don't forget the phone

**Comment by AnturK** [comment]
Could you Meta too ? No hurry since it's not space this here.
basil delivery edition sigma 2015-05-25 183114

**Comment by Incoming5643** [comment]
oh damn, I didn't know they had two logo on meta

**Comment by SconesC** [comment]
i dont understand this packets meme

**Comment by Incoming5643** [comment]
A good long while ago there was a very salty banned player who claimed he would destroy the server with "packets" of data (like in a DDOS most likely).

While some lag did follow, he obviously failed to destroy the server and the jeers and jokes followed.

**Comment by Cheridan** [comment]
nothing to see here folks

**Comment by GunHog** [comment]
You forgot to add the motion cameras back.

**Pull request merged**
