### PR TITLE
Improves colossus code

### PR DESCRIPTION
**Pull request by ChangelingRain**
Like #19670 but without the balance stuff.

Still prevents wavedashing, though.

### CODE REVIEW

**Comment by Core0verload** [comment]
+BALANCE

**Comment by Kromgar** [comment]
What the fuck is wavedashing

**Comment by PKPenguin321** [comment]
im glad wavedashing is finally reaching meme status

**Comment by LaharlMontogmmery** [comment]
> What the fuck is wavedashing

**Comment by PKPenguin321** [comment]
it's the forbidden technique

**Pull request merged**
