### PR TITLE
Fixes lava burning unconstructed HE-pipes

### PR DESCRIPTION
**Pull request by DaedalusGame**
:cl: 
fix: fixes lava and fire burning HE-pipes
/:cl:

They don't burn in plasma fires and they don't burn if they're placed on lava. And they exchange heat with the lava. You just can't properly build them on lava. Now you can.

### CODE REVIEW

**Review by Tlaltecuhtli — APPROVED** [review]
this is an atomic fix pr, tested and works fine

**Comment by arsserpentarium** [comment]
now needs power transfer module to send energy from lava to station

**Comment by Anonmare** [comment]
>Make TEG
>Get Staff that makes Lava tiles
>Put one loop of H/E pipes in space
>Put the other loop on lava tiles
>Create a perpetual energy machine

**Comment by DaedalusGame** [comment]
>Make TEG (oh wait you can't)
>Make a heater and a cooler
>Upgrade to pico tier
>Perpetual energy machine

**Comment by Anonmare** [comment]
>>Make TEG (oh wait you can't)

STOP HURTING ME

**Pull request merged**
