### PR TITLE
Buffs Crowbar

### PR DESCRIPTION
**Pull request by Bawhoppen**
The crowbar was a complete disgrace before
This buffs it to be slightly higher force than extinguishers which are super common

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
yeah the crowbar being weak didn't really make sense

**Comment by Cheridan** [comment]
they're pocket crowbars

**Comment by Bawhoppen** [comment]
@Cheridan make america great again

**Comment by RandomMarine** [comment]
It's a tiny pocket crowbar. Jesus Christ you're making it the same force as the crowbar/large read the rest of the file you're touching.

**Comment by Bawhoppen** [comment]
I did, I specifically made them all equal???

**Comment by Zilenan91** [comment]
Make the red crowbar 13

**Comment by optimumtact** [comment]
Oppossed for the same reasons cheridan is.

Pocket crowbars are meant to balance ease of use, so should not be a strong weapon.

**Comment by Bawhoppen** [comment]
fine now they're only 10 which is the exact same as extinguishers which are super common

**Comment by TechnoAlchemisto** [comment]
why not just make big crowbars stronger than small ones

**Comment by Bawhoppen** [comment]
they are

**Comment by Zilenan91** [comment]
The red crowbar should still be stronger than the regular one because of the reference

**Comment by KazeEspada** [comment]
Ive never seen a large crowbar tbh

**Comment by bear1ake** [comment]
Agree with @Cheridan. 10 is OP for small tool.

**Comment by Iamgoofball** [comment]
Guys, before you say this is op, welders do 15 burn when on, fit in pockets, and welding fuel isnt used up by hitting people.

**Comment by Cheridan** [comment]
no knockdown tho

**Comment by Saegrimr** [comment]
If you're going to do this, just remove pocket crowbars and replace with the normal ones. Why the fuck have a pocket and a regular do the exact same thing.

Or the other way around I don't fucking know but seriously don't have two items that do literally the exact same thing.

**Comment by Bawhoppen** [comment]
honestly I don't see the problem with these doing 10 force, extinguishers which are way more common do the same amount, and while you can't fit them in your pockets you can still easily fit them in your backpack which makes that very minor

**Comment by KorPhaeron** [comment]
10 is probably fine, your fists do 5-9

**Comment by Zilenan91** [comment]
12 would be better, crowbars could probably kill someone as good as a plant hatchet can irl.

**Comment by Bawhoppen** [comment]
@Zilenan91 people don't want anything to be lethal in this game it seems like

**Comment by PKPenguin321** [comment]
>12 would be better, crowbars could probably kill someone as good as a plant hatchet can irl.

better make shit like metal rods do 50 because blunt trauma from something that heavy can definitely kill you quick irl. axe should do straight up 200 or something.

but >muh realism aside, if 10 is too much for maintainers then 8 might be a good compromise

**Comment by Zilenan91** [comment]
There would be zero opposition from anyone but maintainers to crowbars doing 12 damage, I can guarantee that if a poll was made it'd be universally in favor of it from players.

**Comment by RandomMarine** [comment]
The issue is that people are mistaking POCKET CROWBARS, which are like these.
http://g03.a.alicdn.com/kf/HTB1kNwEHFXXXXa9XVXXq6xXFXXXN/Multifunction-EDC-Mini-Crowbar-Survival-Hand-Tools-Pocket-Wire-Winder-Nail-Puller-Scraper-Stainless-Steel-Gear.jpg

For actual, full-sized crowbars. Which are like these
http://thumbs.dreamstime.com/x/angry-man-holding-crowbar-18193464.jpg
These already exist in the code, and are placed in the map at certain places, such as engineering.

If anything POCKET CROWBARS should just get a new sprite that more accurately reflects what they are.

**Comment by Bawhoppen** [comment]
@RandomMarine are you retarded, our pocket crowbars are just normal sized ones you slip into your pocket

**Comment by PKPenguin321** [comment]
yeah, maybe the *sprites* are, smartass

**Comment by Bawhoppen** [comment]
no they're intended to just be slightly smaller crowbars that stick into you pocket and lean against your body

**Comment by callanrocks** [comment]
> Is that a crowbar in your pocket or are you happy to robust me?

**Comment by Dorsisdwarf** [comment]
Dont big crowbars have a different sprite now?

**Comment by Bawhoppen** [comment]
@Dorsisdwarf yes its a slightly larger one of the small crowbar, implying that the small crowbar sprite is correct

**Comment by KorPhaeron** [comment]
Just make the pocket crowbar do less

**Comment by Bawhoppen** [comment]
it does do less

**Comment by Bawhoppen** [comment]
seriously though what is everyone's problem with this? fire extinguisher DO THE EXACT SAME FORCE and are way more common anyways

**Comment by PKPenguin321** [comment]
We should make every item in the game do 10 brute because that's what fire extinguishers do and they're way common anyways

**Comment by Bawhoppen** [comment]
you've never played half life have you this is a disgrace

**Comment by Zilenan91** [comment]
Actually yeah don't metal rods do 12? Why not make most things do 10 brute, the game will be way more lethal and that's generally a good thing for low-ish brute values on weapons because it won't lead to antags snowballing and turning the game into a joke.

**Comment by PKPenguin321** [comment]
metal rods do 9, stop pretending you know things you normie

**Comment by Zilenan91** [comment]
Same as a broken bottle so it's still good

Also >table leg doing 9 brute
It does more damage than a giant metal chair hitting someone

**Comment by PKPenguin321** [comment]
yeah damage values aren't realistic, they're more gamey than most other things
like for instance if a rod does 9 damage and 1 metal sheet is 2 rods of material, and you can have 50 metal sheets in your hand at once, then logically with a stack of 50 sheets you'd have a weapon of instant death and mass destruction, but actually it does 10 damage

**Pull request closed without merging**
