### PR TITLE
Get your rocks out of my snowballs

### PR DESCRIPTION
**Pull request by silicons**
Ruined an event gimmick.

### CODE REVIEW

**Comment by kilkun** [comment]
Var edit exists for a reason.

It's a cheeky reference and makes them equivalent to floor tiles. Don't get rid of it because admins don't know how to use their tools.

**Comment by TrustyGun** [comment]
Firstly, what is it a cheeky reference to? Legitimate question, because I have no clue. Secondly, he did add an alternative snowball that has the same force as the original.

**Comment by kilkun** [comment]
Dwarf Fortress snowballs are highly lethal weapons and are known for blowing heads to gorey bits, most likely.

Also there's literally 0 point to this PR. It just adds child bloat. It's easily done by any admin via the var panel.

**Comment by kevinz000** [comment]
@kilkun You try spawning in 500 snowballs and varediting them all with mass modify before anyone throws one. Here's a tip, you won't have time. This still lets you spawn the high throwforce varient, it's just it's not there by default. There's no reason not to add 2 lines of code that allows admins to spawn snowballs or to make them makable because they won't do shittons of damage by default.

**Comment by jughu** [comment]
Var editing them all takes litteraly 5 seconds and if somoene throws a snowball or 2-5 it really isnt that a big of a problem because you edited them later to do none

**Comment by jughu** [comment]
Altough sense wise this is a logical PR i rather want snowballs makeble from snow turfs which are 0 damage and maybe you can also add a feature to combine rocks and snowballs for the 12 brute snowballs

**Comment by lzimann** [comment]
can you even get snowballs without an admin spawning

**Comment by TechnoAlchemisto** [comment]
You can use the duplicate build mode function to spawn large amounts of snowballs with the vars you want

**Comment by optimumtact** [comment]
Jesus christ learn the admin tools before you shit up our codebase with compile time wasting

**Comment by jughu** [comment]
B-but democracy!

**Comment by optimumtact** [comment]
That is a good point.

Remove the subtype

**Comment by kilkun** [comment]
a one time event that you were too incompetant to execute properly with the robust tools at your disposal isn't an excuse to shit up the codebase.

@lzimann im like 50% sure you can get them from snow tiles, but that might be a /vg/ feature.

**Comment by kevinz000** [comment]
@kilkun You can go remove your corporate agents that I've never seen a single admin use then. It contains nothing snowflake and everything can be varedited, why is it even in the game?!

**Comment by PKPenguin321** [comment]
VV snowball, throwforce = 0, mark, game panel, duplicate marked object

It isn't hard

**Comment by kevinz000** [comment]
But is there a reason for a snowball to do more than twice a floor tile's throwing damage?

**Comment by PKPenguin321** [comment]
12 is not more than 20

**Comment by jughu** [comment]
Floortiles do 7 tho

**Comment by PKPenguin321** [comment]
In melee, yeah
Floor tile throwforce is and always has been 10 though, how do people not know this?

**Comment by KorPhaeron** [comment]
Just use VV

**Pull request closed without merging**
