### PR TITLE
Fix everything

### PR DESCRIPTION
**Pull request by ghost**
This changes fixes **all** the bugs!

### CODE REVIEW

**Comment by YulianR** [comment]
Merge it now, do not wait until someone will steal it

**Comment by MrStonedOne** [comment]
2.6 million lines of code (including maps)

Nice

**Comment by Gyaviste** [comment]
I did a lot of work

**Comment by igigin** [comment]
Such a rip-off of my ideas, https://github.com/TauCetiStation/TauCetiClassic/pull/806.

**Pull request closed without merging**
