### PR TITLE
Fixes timestop interaction with antimagic

### PR DESCRIPTION
**Pull request by 4dplanner**
## About The Pull Request
only one of these is my fault

## Changelog
:cl:
fix: timestop is properly defeated by antimagic.
fix: timestop only checks antimagic once
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
epic

**Comment by Barhandar** [comment]
But m-muh chemical reaction not magic!

**Comment by 4dplanner** [comment]
> But m-muh chemical reaction not magic!

nothing to do with this, this is the wizard one lol

**Comment by nicbn** [comment]
JOTARO

**Pull request merged**
