### PR TITLE
adds cup of coffe. does nothing. handed out by gms at random

### PR DESCRIPTION
**Pull request by Apogate**
adds cup of coffe. does nothing. handed out by gms at random

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
please add this is my second time asking i need this please

### CODE REVIEW

**Comment by xxalpha** [comment]
Are you drunk, guy

**Comment by Shapsy** [comment]
Better fucking drink it

**Comment by Cheridan** [comment]
i dont get it
we already have coffee??

**Comment by Chocobro** [comment]
since this apparently needs to be said it is a Bro Team Pill reference

**Pull request closed without merging**
