### PR TITLE
Fixes plasmaman wizards instantly igniting

### LINKED ISSUE #16094: Plasmaman Wizards start off on fire
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
Wizards of players who have race set to plasmaman start as a plasmaman
### Why is it a problem, or what should have happened?
They start on fire and die
### How can the problem be reproduced?
Set race to plasmaman, get wizard, die
### What revision did the problem happen on? (Helpful, but not required)
[If you're including this]: # (Type find-server-revision ingame to find it. "Current" isn't helpful.)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #16094

This just sets the wizard to a human - this both ensures that future races that have special requirements aren't at risk and also has little impact because of the magic mirror in the den that they can use to change their race to whatever the want.

### CODE REVIEW

**Comment by Zilenan91** [comment]
:+1:  Now I don't have to set myself to human from lizard so that I can use mutate

**Comment by coiax** [comment]
This is fixing a bug in the wrong way, plasmamen should be spawning with the correct setup, not enforcing humanbasic.

**Comment by Zilenan91** [comment]
They can be a plasmaman if they spawn their rune armor. Otherwise the fix would be making the wizard robes immune to fire.

**Comment by Xhuis** [comment]
@coiax I could make plasmaman variants of the wizard robes, but they'd have to be heat- and space-proof, which I feel is overkill.

**Comment by Dorsisdwarf** [comment]
The space wizard federation will not train plasmapeople.

Deep lore

**Comment by Xhuis** [comment]
We need a `VERY CANON` label stat

**Comment by coiax** [comment]
Plasmamen just need a special jumpsuit and a tank and helmet. Just make a special wizard plasmaman helmet.

**Comment by Xhuis** [comment]
Fine.

**Comment by Supermichael777** [comment]
Plasma-man jumpsuits and helmets are actually great disguises because you cant see the face. throw in a voice changer and no one can tell(excluding "features" of examine).

**Comment by coiax** [comment]
> wizard
> voice changer

Plasmamen don't get heat immunity, they take damage from being on fire, that's why they try to avoid it. In exchange they need internals all the time. And a wizard plasmaman will never be space worthy, and thus unable to gain syringe immunity.

**Comment by Dorsisdwarf** [comment]
Yeah, but they can _be_ plasmamen for the fireproof suit, then switch races to something less explosive.

**Comment by coiax** [comment]
If plasmamen suits are so OP then why don't we see them used more by powergamers? And are these advantages more than inhumanity?

**Comment by Xhuis** [comment]
Probably because, in a normal scenario, plasmamen are forced to wear the suits and can't, at any point, take them off. While this would also be true for the wizards, they have the advantage of spells and potential mobility.

I'm not saying that plasmaman suits are overpowered. I'm saying that, if a wizard got them for free, the benefits provided would outweigh the drawbacks.

**Comment by PKPenguin321** [comment]
>If plasmamen suits are so OP then why don't we see them used more by powergamers?

because if you go on the server you might see one or two plasmamen very rarely. the suits hardly exist in the first place.

**Pull request merged**
