### PR TITLE
removes the amber focus from the game 

### PR DESCRIPTION
**Pull request by ANAME593**
## About The Pull Request
heretics no longer need the amber focus to use spells

## Why It's Good For The Game
heretic spells while useful are not strong enough to require a item that outs you as a antagonist to anybody that sees you.  

## Changelog

:cl:
del: amber focuses have been removed from the game
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
There's no way this compiles I'm gonna laugh so hard

**Comment by ANAME593** [comment]
There's no way this compiles I'm gonna laugh so hard

im a idiot can you explain what ive done wrong

**Comment by LemonInTheDark** [comment]
You've removed the element that tracks focuses, but not any uses of the element, or any checks for the trait the element applies 
Also you're webediting, which means you have no way of testing your code, so you're essentially doomed to making mistakes like this.

**Comment by LemonInTheDark** [comment]
Mistakes like this (except more subtle) are why we typically don't allow webediting for anything larger then like value changes, because we essentially rely on the half hope that people will test their work to maintain some level of quality.

I'm leaving this pr open because I honestly don't understand amber focuses at all, and I assume melbert could better have the "do these need to exist" conversation (also I don't wanna slam you into the dirt you seem nice), but we typically close large webedits like this, for the above reason.

**Comment by ANAME593** [comment]
im gonna go ahead and close this since i've fucked up too hard

**Comment by LemonInTheDark** [comment]
o7

**Pull request closed without merging**
