### PR TITLE
Halved Psyker echolocation cooldown

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Default psyker refresh rate has gone from '2 seconds' to '1 second'

## Why It's Good For The Game

I tried playing Psyker a few rounds ago. Oh my god. It was so bad. Genuinely, I spent more time looking at the fadeout screen than actually seeing things. It was horrible and most importantly extremely nauseating. I wasn't even able to make my way to the station nor find where my guns even were.

I had just eaten lunch and literally had to stop and suicide just so I didn't throw up. In real life. I injected the 2 gore injectors and noticed there was another meat cube with nearby expended gore injectors next to me. Someone else joined as Psyker and did the same thing after noticing how unplayable it was.

While testing in local I was shocked by how much better it felt. Trying to compare the two experiences made me realize that there is a HUGE diference between the 'real' cooldown in local and on live. 

Due to that, I'm just going ahead and shortening the cooldown, which will hopefully bring Echocolocation into its INTENDED design, rather than the UNINTENDED slower, laggier version.

I think the main reason it was nauseating on live, unlike local, is that in local, I spend more time being able to see things. In live, I spent more time looking at the black fading screen.

While I labeled it as balance, this is probably closer to a qol or fix than anything else imo. It brings Psyker into its intended design and tries to stop it causing real life nausea.

## Changelog

:cl:
balance: Halved Psyker echolocation cooldown. This will hopefully make it actually usable.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
How the fuck i get a conflict on a 1 character pr

**Comment by carlarctg** [comment]
Bro changed the cd from 2 seconds to 1.8 seconds. What the shit

**Comment by SimplySmiley123** [comment]
Yeah, psyker's vision is extremely laggy, last time I played psyker I got 2 other psykers with me and all of us got disconnected by the time the 4th guy on the ship that could see at all got the ship docked to the station, after rejoining we pretty much couldn't walk around at all and had to be dragged aroundby the guy who could see, not because of being unable to see, but because of how delayed our inputs were and how often we would just get booted off mid-walk.

**Comment by Jacquerel** [comment]
If it works fine on local, making the cooldown shorter on live for an "expected" level of lag doesn't really qualify as a fix; it's just throwing spaghetti at a wall.
You will need to find a way to force it to be consistent.

**Comment by carlarctg** [comment]
> If it works fine on local, making the cooldown shorter on live for an "expected" level of lag doesn't really qualify as a fix; it's just throwing spaghetti at a wall. You haven't even tested this (because you cannot).
> You will need to find a way to force it to be consistent.

If this isn't an acceptable solution, there isn't one. Echolocation should be removed from the game until a rework that DOESN'T CAUSE NAUSEA and is actually fun to play is made. As is Psykers are a wasted fugitive slot.

**Comment by uaioy** [comment]
could it be possible to make psyker vision always visible instead of the whole blinking thing?

**Comment by CCC23** [comment]
just making it so that psyker vision only PINGS when you see a living creature it could make it actually USEABLE and still go along with the echolocation ping but having to wait for the ping on walls and very basic things as well as not having the stupid purple overview where you cant see anything as its all purple and black

**Comment by FlufflesTheDog** [comment]
iirc the code relies on expiry time + fade out time not exceeding the cooldown time, else the lag gets much worse. Be sure to adjust those as well.

**Comment by jlsnow301** [comment]
We just keep lowering the cooldown

Do they really need to have one for the theme to stay intact

image

**Pull request merged**
