### PR TITLE
New Abductor Uniforms Try #2

### PR DESCRIPTION
**Pull request by Metroidlover**
:cl: MetroidLover
add: New Abductor uniforms
/:cl:

~Try 2 due to horrendous incompetence on my part.~

Saw these over on Oracle before it's plug got pulled, and I thought they looked nice and would be better than grey jumpsuits

Art by Quantum-M
forward
left
right
up

Let me know if you want any more pictures of different equipment,background, or pose.

### CODE REVIEW

**Review by lilacrhododendron — APPROVED** [review]
Looks good now. I like how the uniform looks as well.

**Comment by Borisvanmemes** [comment]
These look painfuly good and i wish i could have them as a normal assistant.

**Comment by subject217** [comment]
Maybe someone could add a slightly edited parody version as an arcade machine reward or something like that.

**Comment by Metroidlover** [comment]
Hmm, maybe like a 'Rave Suit" of various highlights as an arcade prize.

**Comment by Steelpoint** [comment]
The sprites are only cool and unique so long as they remain rare. Making them easier to acquire through the arcade or a autodrobe would make them far less valuable and unique.

Just because something is cool does not mean we should proliferate them more. These are great for Abductor only uniforms.

**Pull request merged**
