### PR TITLE
[MDB Ignore] Mapping directional helpers for signs + sign naming conventions

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
This PR is twofold: 
1) Gives directional helpers for signs (warning signs, department signs, and direction signs)
2) Puts the sign names into snake_case (+ bonus updatepaths file)

## Why It's Good For The Game
Signs are one wall mount that was missed when directional helpers were going out, and object names should be in camel_case. Also what's a mait? 

## Changelog

:cl:
qol: department signs have directional variants
code: sign paths are now in snake_case
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
image

**Comment by tralezab** [comment]
conflict

**Comment by tralezab** [comment]
hohohoho you know what i'm boutta say CONFLICT

**Comment by dragomagol** [comment]
BEGONE DEMON!

**Pull request merged**
