### PR TITLE
Revert some admin button moves

### PR DESCRIPTION
**Pull request by Cyberboss**
- Moves "Start Now" and "Delay Pre-Game" back to Server tab

### CODE REVIEW

**Comment by itseasytosee** [comment]
Speedmerge please

**Comment by PKPenguin321** [comment]
literally just type "start " in the command line and hit enter
dont even click a tab
you fool

**Comment by peoplearestrange** [comment]
Agree. That was a mistake, I was being a bit too categorical.

**Comment by cacogen** [comment]
thank you friend

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
