### PR TITLE
Nerfs L6 SAW Hollow Point Bullets from -10 armour penetration to -60 armour penetration.

### PR DESCRIPTION
**Pull request by ghost**
nerfs and fixes hollowpoint for the l6

c20r hollow bullets have -50 ap
l6 hollow bullets have -10 ap
i think you can tell the problem here.

:cl: FrozenGuy5/PraiseRatvar
balance: Nerfs L6 SAW Hollow Point Bullets from -10 armour penetration to -60 armour penetration.
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
Freeze

**Comment by kevinz000** [comment]
U ded?

**Comment by PraiseRatvar** [comment]
@lzimann this is a fix too considering c20r hollow bullets have -50 AP while l6 hollow bullets have -10

but im not gonna haggle with you much more

**Comment by PraiseRatvar** [comment]
@kevinz000 ^^^^

im in a different country, smh!!

**Comment by PraiseRatvar** [comment]
@lzimann i request a reopen

**Comment by optimumtact** [comment]
HP should be weak against armour, so on that basis

**Pull request merged**
