### PR TITLE
Maybe fixes podpeople cloning not properly working for objectives

### LINKED ISSUE #64133: Blood Brothers got an objective to kill a borg
## Round ID:
176630

## Testmerges:
N/A

## Reproduction:
Target got themselves borged, which should count as dead

Screenshot_3

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

uses fully_replace_character_name() instead of just real_name

Also:
image

## Why It's Good For The Game

Not entirely sure, but this might fix https://github.com/tgstation/tgstation/issues/64133 (because the objective should update to say their podperson name, not that the round ended with them as the goal)

## Changelog

I am quite scared of adding 'fix' here since I don't know if this actually fixes the maroon objective. At most I think this is just 'code improvement'.

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
This won't fix the maroon objective

**Comment by JohnFulpWillard** [comment]
> This won't fix the maroon objective, pod people are still considered alive

Podpeople are supposed to be considered alive they are living, i want objectives to reflect it

**Comment by SuperNovaa41** [comment]
ohh i see whoops! (fix your compile issues freak)

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Tested this and it kinda breaks pod cloning.
Being pod cloned doesn't grab your ghost, but does set it as your body.

**Comment by MrMelbert** [comment]
Actually I'm just gonna close this PR since it doesn't fix the bug, just causes a different one. 
Someone should validate that comment at the top of `transfer_to`. It's literally 9 years old and I'm not sure if any of the bugs it talks about still applies.

**Pull request closed without merging**
