### PR TITLE
Temperature control unit

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
This PR changes how freezers/heaters work by adding a button in the GUI that allow the users to switch between cooling and heating without the need to deconstruct the machine. 
Circuitboards now will build the freezer and can't be changed by screwdriving the board.
Mapping isn't touched, all other functionalities are still there

## Why It's Good For The Game
No more painful construct-realize mistake-deconstruct-screw-construct

## Changelog
:cl:
add: added GUI button to freezer/heater that allow the players to change setting on the fly without the need to deconstruct the machine
tweak: changed the name to Temperature control unit
tweak: freezer/heater circuitboards will build the machine starting with the freezer, no longer allow a screw to be used (you can still setup the piping layer)
/:cl:

### CODE REVIEW

**Comment by stylemistake** [comment]
Nice QoL feature, worth -10 GBP.

**Comment by Ghilker** [comment]
Cool! now i'm at -10!

**Comment by brotherbeyondd** [comment]
Poggers

**Review by Mothblocks — COMMENTED** [review]
Note to maintainers: Please don't merge with the Unit Tests label applied, as its just a tiny change.

(note to self: consider removing the webhook part entirely 😬)

**Comment by Misdoubtful** [comment]
Considering I mindlessly make this mistake every couple of days, thanks.

**Review by stylemistake — DISMISSED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-13). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
