### PR TITLE
Storage Item Click Usability Improvement

### LINKED ISSUE #7927: Feature request: no more pixel-accurate clicking in inventory
When you take something out of your pocket-slot, you don't need to click on the object, just the slot, the corner of it or anywhere on the slot.

When you take something out of your backpack or belt, you have to click precisely on the item, which can be difficult (and confusing because inconsistent), especially with some very small objects like screwdrivers, telescopic batons, micro manipulators, etc.

Could it please be made possible that backpack-slots work like other intentory-slots like pockets?

### PR DESCRIPTION
**Pull request by RemieRichards**
## Feature
- Clicking anywhere around an item in a storage item (Backpack, Box) now acts as if you clicked the item, correctly grabbing it from the storage item.
- Clicking anywhere around an item in a cyborg module now acts as if you clicked the item, correctly equipping it.
## Code
- Sets `mouse_opacity = 2` when an item is added to storage, to simulate clicking around it without hacks.
- Sets `mouse_opacity = 2` when orienting the screen objects, so backpacks/boxes etc. that spawn with contents also have this feature.
- Sets `mouse_opacity = initial(mouse_opacity)` when an item is removed from storage, to reset it back to normal.
- Sets `mouse_opacity = 2` in cyborg `fix_modules()` so Cyborg inventories also have this feature.

My initial version was so hacky lol, Store an assoc list of screen_coords of items in the storage UI element and jury-rig the player's click to the closest one, rofl.

Fixes #7927

### CODE REVIEW

**Comment by phil235** [comment]
Wait, does this fixes #7927 ?

**Comment by RemieRichards** [comment]
@phil235 Yep!

**Comment by Core0verload** [comment]
Is it Storage Usability Week?

**Comment by PKPenguin321** [comment]
REMIE DID IT

IT'S DONE

IT'S FINALLY HERE

THE BEST PR OF ALL TIME

**Comment by GunHog** [comment]
WE LOVE YOU, RR!!!!!

**Comment by xxalpha** [comment]
Wasn't this already a thing at some point? Because I could swear someone did it.

**Comment by Killbasa** [comment]
Awesome, I hope this gets merged soon.

**Comment by Madjura** [comment]
This is amazing, thanks.

Could the same be implemented for floor tiles / tables please? Where, if you click a floor/table, it picks up the item that is on top, or the second/third whatever highest if the top one cannot be picked up (clown pulling a locker over a banana peel for example)

**Comment by Nanotransistor** [comment]
Thank god. Now my nemesis the stunprod will be more usable.

**Comment by PKPenguin321** [comment]
WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Invisty** [comment]
>Clicking anywhere around an item in a cyborg module now acts as if you clicked the item, correctly equipping it.

Praise be to Remie, most based of coders.

**Pull request merged**
