### PR TITLE
Embedded Item Balancing. Also fixes #8029

### LINKED ISSUE #8005: Rods OP, please nerf
So it turns out you can throw metal rods now, and impale the shit out of people. While hilarious, it's pretty bizarre, and rather strong. It's the new floortiles of ghetto combat.

### LINKED ISSUE #8029: admin rejuvenate verb doesn't fix embedded items
Tested on a local server with a build downloaded just minutes ago. Rejuvenated a target with several throwing stars in them, and they got back up, but immediately began taking massive damage from the throwing stars again. Maybe make embedded objects get thrown onto the ground out of the subject upon rejuvenating?

### PR DESCRIPTION
**Pull request by RemieRichards**
- Exposes all embedding related multipliers as variables and definitions
- The multiplier for Impact damage has been lowered from 5 to 4 (what can I say? I'm nice :) )
- Throwing star pain damage multiplier increased from 2 to 4, meaning it does 8 damage at a 15% pain chance.
- Spear pain damage multiplier increased from 2 to 3.
- Only items of throw_speed 4 and above can embed now (By default, just throwing stars and spears)
- Explosions ALWAYS throw their items around at throw_speed 4, and reset to their normal values after they land to prevent griff, changing nothing gameplay wise.
- The throw_speed threshold is ON TOP of needing to be a can_embed() object, changing nothing gameplay wise.

If you throw all 5 throwing stars from the box into 1 person you will do 45 damage to them (Not counting the damage over time from pain) I believe this is fine since throwing all 5 into one person means you no longer have them anymore. (This is technically a nerf from 50 damage with all 5 stars to 45 with all 5, with the pain damage being increased to compensate)

Fixes #8005 
Fixes #8029

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Spears should probbably embed when thrown by a person.

**Comment by RemieRichards** [comment]
Eh sure, I'll mess with their values too so it's not OP.

**Comment by pudl** [comment]
since spears can impale, glass shards should impale but probably at low damage just so it's an annoyance

**Comment by RemieRichards** [comment]
@pudl shards already do get with the system god.
:P

**Comment by pudl** [comment]
it says that only spears and stars embed?

**Comment by RemieRichards** [comment]
No it doesn't.

**Comment by Lumipharon** [comment]
>Only items of throw_speed 4 and above can embed now (By default, just throwing stars and spears)

That sounds like it's only spears and stars to me.

**Comment by RemieRichards** [comment]
I love how 2 people have decided that that bullet point is the be all and end all, and decided to discard the information in the next bullet point
> Explosions ALWAYS throw their items around at throw_speed 4, and reset to their normal values after they land to prevent griff, changing nothing gameplay wise.

**Comment by Lumipharon** [comment]
I am specifically talking about throwing things. Yes I can read, I realise explosive will lodge everything and it's mother into my skull.

That said, it seems more then plausible that I can throw a cleaver or hatchet at someone and have it embed in them, which as far as I can tell, will not be possible.

**Comment by RemieRichards** [comment]
Yes, but @pudl comment is the generic concept of embedding. IF as you say, yours is instead focused on the concept of Thrown Embedding then yes, you're correct.

**Comment by pudl** [comment]
i meant thrown

**Comment by RemieRichards** [comment]
>since spears can impale, glass shards should impale but probably at low damage just so it's an annoyance

>it says that only spears and stars embed?

Apologies, but you were nowhere close to specific enough.

**Comment by mikecari** [comment]
How do you remove embedded objects from yourself? Besides moving around that is.

**Comment by RemieRichards** [comment]
Click yourself with an empty hand to show the self examine thing

**Comment by Atskadan** [comment]
r i p rods :skull:

**Comment by Jordie0608** [comment]
http://keepachangelog.com/

**Comment by Dorsisdwarf** [comment]
The adminspawn kinetic speargun should have an embed chance

**Comment by Jordie0608** [comment]
=(

**Pull request merged**
