### PR TITLE
Fixes for icebox service

### PR DESCRIPTION
**Pull request by AlinaStarkova**
## About The Pull Request
gotta love GBP

many many fixes, ill list them all out

1. this freezer needs to use a layer adapter, not directy connect to the scrubber network, all freezers use adaptors to connect
image

2. this is a disposals infinate loop, fixed (i redid ALL of service disposals so it works properly now)
image

3. this pipe leads nowhere
image

4. this puts kitchen deliverys in service hallways
image

5. this was going the wrong direction and is just ugly made
image

**6. I have redid all of service disposals to actually work properly!!!**
image
image

7. weird flex on this diagnal area
image

8. kitchen freezer didnt use kitchen coldroom area, fixed, and gave it an APC
image

9. added a service access door so you can enter lower bar from service hallway
image

10. lower bar maint APC wasnt connected 
image

11. i got rid of this ugly butt piping through holodeck walls, connected it from rightside maint instead
image

12. service maint upper level had a diagnal wall, fixed
image

13. service hallway had a double thick wall, increased the size of service hallway by one row to remove that thick boi
image

## Why It's Good For The Game
map nice

## Changelog
:cl: Nari Harimoto
fix: Icebox service disposals has now been professionally connected
fix: Icebox service has now been tweaked to be up to NT standards
fix: Pete has now been assigned to icebox freezer again
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
Can you move the freezer in a way that the pipe doesn't go trough a wall
I remember maps never have any pipes going trough the walls

**Comment by jughu** [comment]
Also the frying oil can't be reached from the corner

**Comment by AlinaStarkova** [comment]
> 
> 
> Can you move the freezer in a way that the pipe doesn't go trough a wall
> I remember maps never have any pipes going trough the walls

cannot no, because theres already pipes going through that door and we arent putting the freezer in the middle of the floor
layer adaptors have an exception with being through a wall since you rarely ever need to touch it


> 
> Also the frying oil can't be reached from the corner

are you sure?? im fairly sure the meat hooks are not solid objects and should allow you to walk on them, which includes messing with things behind them

**Comment by jughu** [comment]
Meat hooks are solid objects so you cant pass it to reach the frying oil

The proccessor in the cold room technically doesnt need tables cuz food doesnt rot in the cold room i feel like the tables take unnecasary amount of room(especially the one infront the smartfridge)

Theoriticly if you remove the sandstone airlock with just a wall you can move the proccesor above the freezer then the 2 lockers above it, then you can move the meathooks above the gibber and then everything is Accessible with a little more breathing room

**Comment by jughu** [comment]
Because  i dont think kitchen needs 3 million ways to enter trough the cold room and 2 airlocks should just suffice since the second connects to the service hall

**Comment by AlinaStarkova** [comment]
> Meat hooks are solid objects so you cant pass it to reach the frying oil

image

**Comment by NanoCats** [comment]
Engineer Engihere by the way, can you please make it so that one APC doesn't govern two different Z levels, it's very scream worthy in game sometimes when you're trying to find the bastard.

**Comment by AlinaStarkova** [comment]
> 
> 
> Engineer Engihere by the way, can you please make it so that one APC doesn't govern two different Z levels, it's very scream worthy in game sometimes when you're trying to find the bastard.

you can only have one APC per area iirc, and despite being two different z levels, all non-unique flagged areas will always be considered one area (its how on meta the toxins APC controls both toxins, and the launch room, despite the two rooms being disconnected)

fairly certain there will be issues if you map two APCs into the same area because they are hardcoded to only have one exist per area

**Comment by jughu** [comment]
image
i still think the cold room would look nice with arranging things without this airlock it looks so out of place

**Comment by Zytolg** [comment]
> image
> i still think the cold room would look nice with arranging things without this airlock it looks so out of place

Icebox Rework Mapper here. I'll insist that this door is kept since without it, chefs are unable to enter the kitchen proper. I wanted to ensure that chefs had adequate access to their customers away from the serving table, think of it as a proper diner where the waiters/waitresses fly through those double doors from the kitchen. 

> Engineer Engihere by the way, can you please make it so that one APC doesn't govern two different Z levels, it's very scream worthy in game sometimes when you're trying to find the bastard.

Unfortunately this is an impossible ask. No doubt as you've heard already, APC's may only govern one area at a time. Multiple APC's are out of the question as well. As a general rule of thumb, APC's tend to end up in one of two places. Either they're available in the best position to draw a power line to them, or they're located out of the way so that the walls may be used for more important things, like posters.

**Comment by jughu** [comment]
Can the door atleast made solid instead of glass
Also cant you just enter the kitcen from service hall ?

**Comment by AlinaStarkova** [comment]
> 
> 
> Can the door atleast made solid instead of glass
> Also cant you just enter the kitcen from service hall ?

if @Zytolg is fine with a non-glass sandstone door there ill swap it out, if not then im not going to touch it, my PR is only to fix issues, wether that door is glass or not isnt an issue, its just mapping design preference, and im not going to override another mappers design preference

**Comment by NanoCats** [comment]
> Unfortunately this is an impossible ask. No doubt as you've heard already, APC's may only govern one area at a time. Multiple APC's are out of the question as well. As a general rule of thumb, APC's tend to end up in one of two places. Either they're available in the best position to draw a power line to them, or they're located out of the way so that the walls may be used for more important things, like posters.


Yeaah but, couldn't downstairs simply be a different "area"?

**Comment by Zytolg** [comment]
> > Can the door atleast made solid instead of glass
> > Also cant you just enter the kitcen from service hall ?
> 
> if @Zytolg is fine with a non-glass sandstone door there ill swap it out, if not then im not going to touch it, my PR is only to fix issues, wether that door is glass or not isnt an issue, its just mapping design preference, and im not going to override another mappers design preference

That's a tricky one. I was about to say that I didn't mind, but then I remembered why they are glass in the first place. It's all about visibility here and I don't think players would realize where that door leads right off the bat. Furthermore, it was inspired by those saloon style diner doors with the portholes on them, but I don't think removing them would ruin the feel exactly. In this case I'd be more worried about chefs not knowing that this door is their Diner Room access. And in this case, you can completely close off the Basement Kitchen to do your traitoring so it's not like the chefs lack a place to murder. 

I do notice that the goat is missing, so we do need that. I'll be happy to cede the glass door provided a maptainer decides that chefs don't need the Diner Visibility.

**Comment by AlinaStarkova** [comment]
> 
> 
> > Unfortunately this is an impossible ask. No doubt as you've heard already, APC's may only govern one area at a time. Multiple APC's are out of the question as well. As a general rule of thumb, APC's tend to end up in one of two places. Either they're available in the best position to draw a power line to them, or they're located out of the way so that the walls may be used for more important things, like posters.
> 
> Yeaah but, couldn't downstairs simply be a different "area"?

no, we cant just make an infinate amount of areas, areas in byond are predefined in code and we have a limited amount of them, im not going to just assign it some random unused maintnence area just so you can get snowflaked in 2 apcs for the same hallway because your too lazy to walk downstairs to access it, sorry

**Pull request merged**
