### PR TITLE
Makes botany a "Hard" job in terms of wages.

### PR DESCRIPTION
**Pull request by Shadowflame909**
## About The Pull Request
Botany has been boosted from an easy job to a hard job. It was a simple one-line change that I believe will ease the tensions botany experiences during the rounds. With forced "departmental cooperation". It is in reaction to #48856 and should only be merged if that PR gets merged. Otherwise, botany isn't at a tipping point in terms of costs.

## Why It's Good For The Game
There are three very good reasons why this change is necessary. Firstly, botany has no disposable income. All that income is used on items that are necessary for the department's function. Botany spawns with 500 bucks, and they get 250 every paygrade.  With the linked change a multitool would take 90% of their roundstart income because of its 450 bucks. Excluding the other tools, they would basically have to scavenge around for. Those tools are meant to be bought by some department if it's in the public tool storage. The most required being botany.

Secondly, Botany is the hardest job on the station. No contest. How could it be the hardest job, if all you have to do is watch plants and prevent them from dying? Exactly, because you can never stop watching those plants or else they'll die. As every botanist player has experienced, if you ever go to HoP for more access to dual chemistry and botany. You'll find that when you come back, your plants are already rotted and dead. Or are on the verge of death if things went speedy. 

The ways to counteract this near-death is with ammonia and diethylamine. Which you need to hack the vendor for, with a price of 1k+ if you bought all the tools legitimately. Then pay an extra 300 - 200 depending on which one you bought. As you can see, I am completely ignoring the entire seed vendor in terms of the costs of botany. Because they stack up so high, it'll take twenty pay-grades to pay for them all. 

The end-game for botany is Gaia, which is the freedom to leave botany since it keeps them alive and self-sustaining.  Thus, I'm not asking for much. I'm just asking for the ability to go AFK and not come back to my dead plants or my plants being on the verge of death and nothing I can do about it.

Lastly, this PR is necessary because departmental cooperation is not a fleshed-out concept we can rely on. Similar to chemistry, any negatively effecting PR to botany always has an alternative upon which it relies on another department. But, the majority of those times those departments aren't interested and want to have no part to do with you. Mostly due to their grand design of the shift they don't want to be taken away from, or simple distrust and paranoia.

**The only way** a botanist gets what they need in this circumstance is to find a borg on asimov, and command them to give them what they want. So quite literally, departmental cooperation only works when the rules are barred upon such a job, to force them into giving them what they want. 

Also, your plants are most likely dead from all this begging and scavenging for the items you could quite obtain rapidly beforehand. You're also most likely arrested for running out options, and breaking in somewhere for one of these items. Better cough up some cash to revive your dead round. Ay botanist?

## Changelog
:cl:
balance: Botany now has more funds to buy the roundstart equipment they need. Gonna have to still wait for everything you need though.
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
A tl;dr for your sanity, dear reader

Screenshot_3

**Comment by 4dplanner** [comment]
don't need multitool to hack botany machines :^)

**Comment by ExcessiveUseOfCobblestone** [comment]
when will shadowflame learn that the end game for a department with many branches is not limited to one item, but in fact the compounding of the many different items within their disposal and their synergies.

**Comment by PKPenguin321** [comment]
cad-20110114-66943

**Comment by Farquaar** [comment]
I play a lot of botany. They don't need a pay raise. If you need extra money as a botanist, you could easily take tips from other crewmembers in exchange for some nice plants.

**Comment by wesoda25** [comment]
this isn’t the proper way

what this game lacks is crew content

murderboners are rewarded by the code and admins 

you might be right, but it stands

**Comment by Tharcoonvagh** [comment]
Chadowflame

**Comment by wesoda25** [comment]
image

**Comment by itseasytosee** [comment]
You could have said.
Hey, botany is a job that requires a lot of time investment and they usably buy a lot of for their job.
So I think they should not have one of the worst paydays.
What you said is a bunch of words that when translated to Sanskrit summon Nyarlathotep himself

**Comment by Shadowflame909** [comment]
> 
> 
> image

I don't know what he meant by this I'm confused



> 
> 
> You could have said.
> Hey, botany is a job that requires a lot of time investment and they usably buy a lot of for their job.
> So I think they should not have one of the worst paydays.
> What you said is a bunch of words that when translated to Sanskrit summon Nyarlathotep himself

This is the true TLDR this is my tldr

**Comment by Krysonism** [comment]
>shadowflame doesn't know about the paper bin plant healing technique.

**Comment by Teepeepee** [comment]
you can use a pair of remote-signallers as ghetto multitools and the cost goes way down, since no-one grabs those

**Comment by Fikou** [comment]
> Secondly, Botany is the hardest job on the station. No contest. How could it be the hardest job, if all you have to do is watch plants and prevent them from dying? Exactly, because you can never stop watching those plants or else they'll die. As every botanist player has experienced, if you ever go to HoP for more access to dual chemistry and botany. You'll find that when you come back, your plants are already rotted and dead. Or are on the verge of death if things went speedy.

lol

**Comment by ArcaneMusic** [comment]
> > image
> 
> I don't know what he meant by this I'm confused



We prefer that the PR is made off of a branch, and not off of your master, because things can become fucky awful quickly that way 👀

**Comment by ExcessiveUseOfCobblestone** [comment]
If it's vital to the job (it isn't) it should be made to not have a cost instead of raising their overall paycheck.

This is an improper fix to an "issue" I don't think needs fixing, at least in this way. This is regardless of the less tool access being merged or not.

I could see making traits exportable similar to how plants are in that you get money for the trait once, rarer ones offering a bit more.

**Pull request closed without merging**
