### PR TITLE
Fake moustaches are now poorly slapped on top of what you're wearing

### PR DESCRIPTION
**Pull request by Likteer**
Another "+1 line changed" banger
moustache

## About The Pull Request
Bumps up the worn layer of fake moustache and it's italian subtype to 4.
Note that NOMASK inv flag will still prevent them from appearing.
## Why It's Good For The Game
- Paper-thin disguises amuse me
- Chef fashion
- Groucho maxxing
- A victory for good taste
obraz
## Changelog
:cl:
add: Fake moustaches are now poorly slapped on top of what you're wearing
/:cl:

### CODE REVIEW

**Comment by Likteer** [comment]
>negative Fix/Feature pull request delta of -10.

Dammit, I could've sworn uncle oranges gave some out a christmas or two ago

**Comment by DATA-xPUNGED** [comment]
holy sweet mother of sovl

**Comment by Flurrieon** [comment]
coded in DreamMaker 💪

**Review by ArcaneMusic — APPROVED** [review]
LGTM 🧔

**Pull request merged**
