### PR TITLE
adds delinquent hat

### PR DESCRIPTION
**Pull request by nervere**
closes #45424 
## About The Pull Request

This is a reskin of the basic cap item, made to look like a certain Crusader of Stardust.
It is sold by the Costume Vendor.

## Why It's Good For The Game

We already have holoparasites, i believe it'd go along nicely with them.

## Changelog
:cl: Cephur sprites, Tralezab code
add: Added a new hat to the costume vendor
/:cl:

### CODE REVIEW

**Comment by Rowelll** [comment]
now i'll wait for "deliquent jacket", so i can make a jojo reference syndie kit

**Comment by nervere** [comment]
To be clear, this is hornedmoth/Cephur's PR, I've remade it for him since his PR was committed to master on an old revision which made fixing a conflict with a spritesheet really tedious.

**Comment by hornedmoth** [comment]
> now i'll wait for "deliquent jacket", so i can make a jojo reference syndie kit

I'm on it.

**Comment by Ordonis** [comment]
何か？JoJoの引用ですか？！

**Comment by Difrit** [comment]
This hat should replace tarot decks from Lavaland lootchests, and when worn should create a stand ghostrole and become unremovable. Should also use the same force speech the luchador masks do, to make you occasionally end sentences with "good grief" and "bitch".

**Comment by wesoda25** [comment]
OOOOOHHHHHH MYYYYYYY GOOOOOODDDDD

**Comment by hornedmoth** [comment]
> This hat should replace tarot decks from Lavaland lootchests, and when worn should create a stand ghostrole and become unremovable. Should also use the same force speech the luchador masks do, to make you occasionally end sentences with "good grief" and "bitch".

I so fucking wish I knew how to implement that last part

**Comment by Ordonis** [comment]
> > This hat should replace tarot decks from Lavaland lootchests, and when worn should create a stand ghostrole and become unremovable. Should also use the same force speech the luchador masks do, to make you occasionally end sentences with "good grief" and "bitch".
> 
> I so fucking wish I knew how to implement that last part

You'd basically just need to do something like the code from the Italian Moustache and French Beret, if you want examples to work from

**Comment by CPTANT** [comment]
Come on, show us the sprites.

**Comment by Rowelll** [comment]
can't you check icon diff

**Comment by MadoFrog** [comment]
how do I say this... I had a boner...

**Review by 81Denton — APPROVED** [review]
yare yare daze

**Pull request merged**
