### PR TITLE
Emergency Shuttle - Rage-Cage Victimizing Evacuation System

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

Adds in the Rage-Cage Victimizing Evacuation System, which costs like 3600 credits
The vast majority of its interior is filled with a ragecage, its power supplied by a RTG, has a jukebox on bar access
The emergency shuttle console is in the middle of the ragecage, along with an express supply console

## Why It's Good For The Game

ragecage shuttles are cool

## Changelog
:cl:
add: Added a new emergency shuttle: Rage-Cage Victimizing Evacuation System
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
its kinda beautiful for being a boring box shape. weirdly works well

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Gonna have to be spoilsport and say this needs to be emag locked

**Comment by mc-oofert** [comment]
> Gonna have to be spoilsport and say this needs to be emag locked

1984

**Comment by mc-oofert** [comment]
> Gonna have to be spoilsport and say this needs to be emag locked

i dont think it should be emag locked considering all the emag-locked shuttles are all somehow dangerous or overpowered
but it cant possibly be dangerous to anyone if they arent actually inside the rage cages or deconstruct the protective windows against the grilles

**Comment by mc-oofert** [comment]
> > it cant possibly be dangerous to anyone if they arent actually inside the rage cages
> 
> you and me both know this is a joke and I guarantee this will cause major administrative headaches as someone accidentally falls in / gets thrown in / etc and gets bonked
> 
> Emag lock or no go

if you die in the ragecage skill issue

**Comment by Helg2** [comment]
> you and me both know this is a joke and I guarantee this will cause major administrative headaches as someone accidentally falls in / gets thrown in / etc and gets bonked
> 
> Emag lock or no go

Considering shuttle named "Asteroid with strapped engines to it" isn't hidden behind the emag and is absolutely griefy piece of shit, why should it be behind the emag?

**Comment by mc-oofert** [comment]
I will literally not lock it behind an emag based on _mere hypotheticals_ where in you can simply walk out of the fucking rage cage provided the shutters arent closed or you just ask whoever is currently controlling the ragecage to open for you? Regardless, if someone is trying to beat you to death while you are trying to exit this ragecage is usually a turboshitter or an antagonist.

Locking it behind an emag makes it even more rarer than it is because shuttles get purchased like 35% of the time on sybil, more less emagged shuttles. This also not resemble any emagged shuttle, where as emagged shuttles endanger the crew, have horribly overpowered tomfoolery in it, or destroy the station,  This shuttle does none of that. No crew is endangered lest they enter the ragecage themselves, and if they are forced in then they can just talk their way out or walk out of the shutters if theyre opened. If they cant do that then they got cucked by a traitor.

**Comment by mc-oofert** [comment]
well fuck you then, its emag only now

**Comment by mc-oofert** [comment]
would you be happy and let me make it not emag-only if i add reinforced windoors over the chutes

**Comment by mc-oofert** [comment]
also the arena shuttle isnt even emag-only and it takes the concept of a ragecage way further than this by forcing everyone to kill eachother

**Comment by Addust** [comment]
add extra RTGs and make sure they're advanced to cause as much torment as possible, hell add a small area with EXTRA zap options (mini-SM??? turbine???) to cause pain

**Comment by mc-oofert** [comment]
> add extra RTGs and make sure they're advanced to cause as much torment as possible, hell add a small area with EXTRA zap options (mini-SM??? turbine???) to cause pain

i would and could make a zappy shuttle but this is not in the scope of this one

also the rtg generates 5500 of some units

every floodlight consumes 750 at max

i think 2500 in the grilles is good enough

**Comment by TheVekter** [comment]
> also the arena shuttle isnt even emag-only and it takes the concept of a ragecage way further than this by forcing everyone to kill eachother

Don't you have to do some specific Lavaland stuff to unlock the arena shuttle?

**Comment by mc-oofert** [comment]
> > also the arena shuttle isnt even emag-only and it takes the concept of a ragecage way further than this by forcing everyone to kill eachother
> 
> Don't you have to do some specific Lavaland stuff to unlock the arena shuttle?

it takes 1 miner to kill bubblegum to unlock it

**Comment by TheVekter** [comment]
> > > also the arena shuttle isnt even emag-only and it takes the concept of a ragecage way further than this by forcing everyone to kill eachother
> > 
> > 
> > Don't you have to do some specific Lavaland stuff to unlock the arena shuttle?
> 
> it takes 1 miner to kill bubblegum to unlock it

Still requires something to be done to unlock it as opposed to it just being available.

You'd probably have a better chance getting this approved without an emag if you made the windows on the outside of the cage full windows, or if you moved the bridge consoles out of the middle of it. Otherwise, the odds you're getting this merged without it being emag only are pretty much zero.

**Comment by mc-oofert** [comment]
> > > > also the arena shuttle isnt even emag-only and it takes the concept of a ragecage way further than this by forcing everyone to kill eachother
> > > 
> > > 
> > > Don't you have to do some specific Lavaland stuff to unlock the arena shuttle?
> > 
> > 
> > it takes 1 miner to kill bubblegum to unlock it
> 
> Still requires something to be done to unlock it as opposed to it just being available.
> 
> You'd probably have a better chance getting this approved without an emag if you made the windows on the outside of the cage full windows, or if you moved the bridge consoles out of the middle of it. Otherwise, the odds you're getting this merged without it being emag only are pretty much zero.

maintainer pissbaby moment

**Comment by mc-oofert** [comment]
image
i have added babyproofing, you cant be shoved in because 1 tile wide, very low chance of accidental entry

**Comment by TheVekter** [comment]
> Also it'd totally fine if you made it even more deadly rather than less deadly

I think it's important to note this; it's not inherently a negative that your shuttle needs to be emag only. You can make it even more of a screaming metal deathtrap, lean really fucking hard into it if you want to.

**Comment by mc-oofert** [comment]
> > Also it'd totally fine if you made it even more deadly rather than less deadly
> 
> I think it's important to note this; it's not inherently a negative that your shuttle needs to be emag only. You can make it even more of a screaming metal deathtrap, lean really fucking hard into it if you want to.

the entire schtick of this shuttle is that its based off the livrah ragecage viddi

**Comment by TheVekter** [comment]
> the entire schtick of this shuttle is that its based off the livrah ragecage video

We don't typically implement direct references to community members. You'd do better to make this your own instead of it just being "that thing that one guy did one time".

**Comment by mc-oofert** [comment]
> > the entire schtick of this shuttle is that its based off the livrah ragecage video
> 
> We don't typically implement direct references to community members. You'd do better to make this your own instead of it just being "that thing that one guy did one time".

no

**Comment by mc-oofert** [comment]
image
further babyproofing so its impossible to fall in if the entry shutters are closed

**Comment by mc-oofert** [comment]
> * Extremely easy to get people knocked in (somewhat resolved)
> * Very flimsy barriers between fully electrified grilles
i would call these two resolved

**Comment by mc-oofert** [comment]
> * Literally has high powered explosives present (express supply pods)

they cost cargor money and barely deal explosion damage

**Comment by EOBGames** [comment]
We're rapidly getting to a point where we have too many evac shuttles, and as such, I'd like to see any newer shuttles going in having something unique to bring to the table. Given this doesn't do much aesthetically, and its gameplay is already covered by both the arena shuttle and BYOS, I just don't think this is doing anything unique enough to meaningfully expand the shuttle roster.,

**Comment by mc-oofert** [comment]
> We're rapidly getting to a point where we have too many evac shuttles, and as such, I'd like to see any newer shuttles going in having something unique to bring to the table. Given this doesn't do much aesthetically, and its gameplay is already covered by both the arena shuttle and BYOS, I just don't think this is doing anything unique enough to meaningfully expand the shuttle roster.,

damn
got 1984ed again

**Pull request closed without merging**
