### PR TITLE
Fixes the lack of Plumbing on MetaStation :)

### PR DESCRIPTION
**Pull request by Helianthus00**
## About The Pull Request

This does **not** cause the runtime error stated in issue #58623

I've added some plumbed water tanks and a couple of the storage tanks around Meta, particularly in areas that consume a lot of water. I'd like to do this for the other maps as well, but I wanted to see how this was received before I put all my time into that. All tested and work fine. Below are images of my changes with arrows showing what will be supplied by the tanks: 
medbay
Medbay
engineering
Engineering
kitchen
Kitchen/Coldroom/Botany
chem lab
Chem Lab
bathroom
Bathroom

## Why It's Good For The Game
The plumbing feature is very cool and is underused, in my opinion. Hopefully, this will familiarize people a bit more with it. 

## Changelog
:cl:
add: MetaStation now has some plumbing water tanks scattered around in high-demand areas for water
add: MetaStation chem lab now has two empty plumbing storage tanks
/:cl:

### CODE REVIEW

**Comment by nightred** [comment]
what happens when one person bumps any of the water tanks out of position? how do we know what tanks are plumbed or not?

**Comment by Helianthus00** [comment]
> what happens when one person bumps any of the water tanks out of position? how do we know what tanks are plumbed or not?

The tanks are anchored. They are a different object with a different description and sprite. They are pretty similar, so it'll take a bit of getting used to, but I don't think it'll cause any issues.

**Comment by Helianthus00** [comment]
Could someone please remove the Feature tag from this pr?

**Review by 81Denton — APPROVED** [review]
Looks good to me, thanks for including screenshots that show the underfloor piping.
@EOBGames Any objections?

**Pull request merged**
