### PR TITLE
Raises the cap for organ damage to 999.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Organs can now take up to 999 damage, they will still cease to function and naturally heal if damage exceeds maxHealth.
applyOrganDamage has been renamed to adjustOrganDamage and is now better at healing organ damage.
adjustOrganDamage can now take a minimum value, as well as a maximum one.
Minimum only matters if damage is negative, maximum only when positive.

## Why It's Good For The Game

Previously, you only needed a single tick of healing to restore an organs functionality. Now, an organ can get fucked up so much more. If someone really makes sure that an organ is damaged beyond (almost) all repair, it shouldn't be possible to restore it with a single healing tick.

I decided to use 999 as a cap because it is the highest 3 digit number. Might be relevant when displaying it somewhere.

## Changelog
:cl:
balance: Organ damage can now exceed the damage it takes for the organ to fail. The cap is 999.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
hyphema symptom go brrrrrrrrrrrrrrrr

Also, how does this interact with strange reagent? Does this make it nearly pointless to apply excess amounts of strange reagent in order to heal organ damage, since that organ healing won't possibly be able to compare with 300 or so organ damage on each organ?

**Comment by ATH1909** [comment]
> If someone really makes sure that an organ is damaged beyond (almost) all repair, it shouldn't be possible to restore it with a single healing tick.

don't most of our current organ repair surgeries just set organ damage to a certain value? this doesn't really make them that much harder to repair (unless you're trying to use strange reagent, in which case you're screwed).

**Comment by Krysonism** [comment]
In principle this is a good thing but as ATH1909 pointed out, currently this is just a huge nerf to the already unused strange reagent.

**Comment by Mickyan** [comment]
I don't like the balance implications of this change, healing people that have been dead for a long time does not need to be any more complicated than it currently is

You should add an upper threshold to restore an organ's functionality, afaik limbs work exactly this way to prevent this exact situation (i.e. organ is disabled at 100 damage, needs to reach at least 75 to be restored)

**Pull request closed without merging**
