### PR TITLE
Redesigns the pirate event ship

### PR DESCRIPTION
**Pull request by WJohn**
It was my first ship where I started to delve into shuttle atmos and power and it really, really showed.

...So this one's a lot less shit! 

RIP prolapsed anus fuckin' turbine coming out the back, wasted space, and fucking atmosia(??) room that had no place on a pirate event ship. 

Armory equipment is unchanged. Turrets are syndicate laser type (on pirate faction). They do less damage, but have the option to stun and there are two that cover the front as well, now, should hopefully feel about the same in terms of protection.

EDIT: Added a med wall vendor to the armory.

:cl: WJohnston
add: Redesigned the pirate event ship to be much prettier and better fitting what it was meant to do.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
As with the current pirate shuttle, there are blind spots that can be broken into, and this ship is actually *more* secure than our current one and has better turret coverage.

And making the armory bigger is... not exactly possible? At least not within the constraints of this ship's shape.

**Comment by Borisvanmemes** [comment]
Needs turrets on the side imo, breaking into the pirate shuttle should be at least kinda hard, right now it'll just be weld into side of ship and walk in

**Comment by IllotAFV** [comment]
Ship looks alright, but I don’t like the vault concept. Money and goodies must be in their vault to be considered towards objective. Crew can just blow up that wall to deny greentext for them because of space wind/fast crew/whatever really. When vault was in the middle of that ship, it was somewhat protected. At least it took more time to get into it.

**Comment by Tlaltecuhtli** [comment]
can you turn those computer console things into emitters?

**Comment by WJohn** [comment]
I agree that the vault is a bad idea. Frankly loot being anywhere on the ship should count towards their objective. I'll ask antur about it.

I also added two more turrets on the bottom left/right of the ship (not pictured there), so there should be no more blind spots.

**Comment by MrDoomBringer** [comment]
@WJohn just switch the vault room with the break room, seems easy enough and solves issues with the vault being too small.

**Comment by Kagus** [comment]
Digging the replacement of the turbine engine, as it... Didn't really work. I mean, yes, I've had great times with incinerating mutinous crewmembers in the combustion chamber, but aside from the setup being awful for producing an actual burn mix, the gases also were a teensy bit wonky when you happen to move the ship anywhere.

Plus someone could just steal your engine out from under you, as was the case with me.

---
As has been mentioned, booty storage is a little skimpy. I'm not sure I'm hip with making the vault the central intersection room that everyone needs to walk through, as MrDoomBringer suggested, but that would at least make it slightly less vulnerable.

While the extra turret functionality and coverage are greatly appreciated (like, WOOHOO), this does make my pipe dream of kidnapping someone onto the shuttle and then ransoming them back to the station a bit trickier, although I suppose you could always just weld them into crate. I'd honestly like to see pirates with more stun-related weaponry to facilitate something like that, but chances of that *not* getting abused to stun-ecutlass people and robust the station are pretty much zero.

Do the turrets use ID-based tracking or infallible NPC tracking? I'm asking because of the time I got captured and had to escape back to my ship with the detective's ID.

**Comment by WJohn** [comment]
@Kagus they track based on your faction. If you have the "pirate" faction they will never shoot at you. I'm not entirely sure if it's possible to make them track according to your ID.

I've also looked into making a centralized vault, it *would* be possible though it would offer no more room for any activity as the current set up.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
