### PR TITLE
Mechs' contents are no longer EMP immune

### PR DESCRIPTION
**Pull request by Sealed101**
## About The Pull Request
~~Required for changes requested for #71392 to actually mean anything.~~ not really, the camera EMP is handled as a cell drain charge and it works fine

This PR makes EMPs affect mechs' contents, mostly comprehensive list of those contents is here:

<details>
<summary>Click for what gets affected</summary>

 - pilot(s)
   - *EXCLUDING* AIs. They are an exception because their `emp_act` will try to kick them out of their borg shell (which they are not piloting when in a mecha), or either try reset the AI's camera to it's core (that is technically inside the mech already) or try to call the evac shuttle. Two of these do basically nothing, and the shuttle call just seems stupid.
 - mech's internal radio (it resets after 20 seconds)
 - any installed stock parts
   - an exception is made for the power cell in case the mech gets `EMP_PROTECT_CONTENTS` flag in some way (adminbus or any future additions). The power cell's drain is handled regardless of the process of EMPing the contents
 - any installed modules, be it weapons, armor, utility (including the camera from the aforementioned mech camera PR)
 - any installed tracking beacons
 - any objects picked up by a Ripley clamp
   - ores picked up by Clarke are not affected, as they go into the internal ore box

</details>

Since this hasn't been working in god-knows-how-long, some issues came up, so I am also addressing them:
- mecha trackers have had an `emp_act` that would simply qdel them. This is wacky, but I made them at least not delete themselves and any other tracker beacons installed when their remote EMP is used
- AI tracking beacon was made EMP-proof so the AI won't get instantly kicked out of control of the mech
  - note: AIs do not actually get kicked out when this happens, will fix a bit later
- tracking beacon HUD image would never hide itself when a beacon was destroyed/removed. this was not known since there was previously no precedent in which a tracker beacon would be removed out of the mech

This is in theory a fix to an oversight(?) but it's been a thing for ages now, so I'm putting the balance label on it.

## Why It's Good For The Game
Consistency. It is now possible to make some specific `emp_act`s to mech component parts and they will actually work. ~~Will contribute to #71392 working~~
I did not get the green light (no response anyway) to move this EMP shielding to a separate armor module, but if maintainers approve it, I can do that. For now, your best bet at protecting yourself from the EMP while in a mech would me a modsuit with an EMP shield, I guess? Could be a good leeway for making a mech operator modsuit.

## Changelog
:cl:
balance: mechs' contents are no longer magically EMP proof. this means that when a mech is EMP'd, everything inside it including the pilot(s), any stock parts, any installed modules and any tracking beacons gets zapped as well
balance: AI mech tracking beacon is now EMP proof
fix: since mechs' contents are now actually affected by EMPs, fixed mech tracking beacons being able to EMP themselves and thus delete themselves
fix: fixed mech tracking beacon HUD image not updating when a beacon is removed/destroyed
/:cl:

### CODE REVIEW

**Comment by Overuseddart** [comment]
I feel as this might screw over nukies who buy a mech and also an implant like reviver or thermal eyes, mechs are already expensive and most nukies like having implants like thermal eyes and reviver. EMP shield is expensive and would leave the nukie without a rifle most likely.  Maybe you can make it so nukie mech pilots aren’t affected?

**Comment by necromanceranne** [comment]
That's what they get for putting all their eggs into one emp vulnerable basket

**Comment by Sealed101** [comment]
I mean yeah, getting EMPd and fried from inside out by all of your implants while in a mech sucks, but having to choose what gear you bring with you sounds like normal nukeops gameplay. 

Nukie (ERT) mechs can get a flag to protect their contents from EMPs, but that's up to maintainers. An alternative could be adding an EMP shield module to the mech support kit (which by the way is still a duffel when we have modsuits) for a price increase, while also screaming at mech buyers that they are not protected from EMPs while inside their mech. Another way could be the EMP shielding armor module that I've mentioned in the PR body, but that also needs a good-to-go from maints.

We could also just ignore the pilot(s) entirely, but that's very unlikely to pass.

**Comment by Shadowflame909** [comment]
if nukie suits come with basic emp shielding. their expensive 125+ tc mechs should too!

It's already a waste of tc to buy a mech at a non-discount. we dont want speedy rounds where we accidentally give the pilot a heart attack roundstart

**Comment by Sealed101** [comment]
well i found a way for the mech camera to not have to rely on getting empd directly, so that's handled in that PR and it works well enough. 
i'm not too fond of this PR though, i think it could use more time in the oven and should come with several ways to achieve emp protection in the mech for at least the pilot. i'll leave it up for a while in case there is interest for it now instead of later

**Pull request closed without merging**
