### PR TITLE
Necropolis Beautification

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: The Necropolis gate now looks as regal as it should. Credit goes to KorPhaeron for turf and wall sprites.
/:cl:
- Added comment headers in the megafauna files detailing their attacks, difficulty, and loot
- Added drake statues and necropolis turf  to the necropolis entrance
- Repathed `/obj/structure/lavaland_door` to `/obj/structure/necropolis_gate`
- Fixed necropolis turfs not having the correct icons

### CODE REVIEW

**Comment by ChangelingRain** [comment]
>legion no longer splits
>all the buildup and flashy animations for a boss that no longer does anything and is actually the weakest boss now

:-1:

**Comment by Xhuis** [comment]
@ChangelingRain That's actually a placeholder until I can figure out how to make the fight more interesting than "split three times and wow he's suddenly bombarding you with 1092134u2189752138571823751238756 legion skulls".

**Comment by Boredone** [comment]
A semi-easy one would be to make em summon NORMAL legions maybe? Much easier to take out, but still a threat.

**Comment by Armhulen** [comment]
cool idea bore

**Comment by Xhuis** [comment]
I'm not sure that's a good idea... imagine having three legion skulls on you at all times, plus infinite legion souls.

**Comment by Armhulen** [comment]
but it's a cool one. Maybe lesser legion or something? I don't know. Also, they don't die in a flash of crimson light. they die in a flash of light. Cool though

**Comment by Bawhoppen** [comment]
save the legion nerf for a different pr :-1:

**Comment by Armhulen** [comment]
yeah this PR would basically have no resistance but you had to include the Legion nerf

**Comment by Xhuis** [comment]
_sigh_

**Comment by Xhuis** [comment]
There's a picture in the PR, doofus.

**Comment by optimumtact** [comment]
Huh it didn't load for me previously

**Comment by KorPhaeron** [comment]
atomize your prs please

**Comment by Xhuis** [comment]
For the third time,
___I DON'T KNOW WHAT THAT MEANS.___

**Comment by optimumtact** [comment]
Having balance changes in your pr like:
Removed Legion's ability to split but buffed him (1250 max health from 800, 40 melee damage from 25)

is a pain because now the merge is delayed as we have to give time for everyone to see and discuss the balance changes

**Comment by optimumtact** [comment]
As a rule of thumb try to keep these things in seperate pr's
quality of life/tweaks
balance/rebalance
features

**Comment by Xhuis** [comment]
Thanks for explaining it to me. I'll remove the balance changes, but I'll also have to cut out the death animation because of how much smaller the sprites get when Legion splits.

**Comment by Xhuis** [comment]
Balance changes are gone. You can remove your angry :-1:s now.

**Comment by AlexCrimson** [comment]
He isnt THAT impossible. Yesterday one of the metafriend lizards almost killed him with base mining gear and a legion soul implant. The only reason he didnt kill it was because the round ended.

Would be nice if people stopped using the shitty AI for boss mobs and instead did some kind of bullet hell/static boss.

**Comment by KorPhaeron** [comment]
There actually is a bullet hell boss

**Comment by Jazaen** [comment]
All of the people who want bullet hell bosses should fight colossi more.

**Comment by Xhuis** [comment]
If colossi aren't bullet hell than nothing is. Those fuckers can one'shot you with the shotgun blast.

**Comment by Armhulen** [comment]
I'd like a broken down facility with an AI that shoots out bullet hell stuff, but it can't move

**Comment by KorPhaeron** [comment]
>2k differences

**Comment by Armhulen** [comment]
Maybe a bit carried away. Maybe.

**Comment by Xhuis** [comment]
Not at all, ideas are fine - just not for this PR.

**Comment by AlexCrimson** [comment]
Colossus still follows the normal AI in that it chases you is that silly direct way. Im talking more about the danger coming from large AoE or homing projectiles like in an MMO raid or bullet hell game, not from a mob chasing you. I guess the Colossus is halfway there though.

**Comment by optimumtact** [comment]
Are you sure that there are no pickaxes in the lavaland map?

**Comment by KorPhaeron** [comment]
I am annoyed in a petty manner that people are gonna think he made the sprites based on the changelog someone call me stupid please

**Comment by KorPhaeron** [comment]
As a serious note though I think it should be more assyemtrical/organic looking in its spread but I guess I can do that later

**Comment by Xhuis** [comment]
@optimumtact There's always pickaxes behind you. You just can't see them.
@KorPhaeron Changelog updated.

**Pull request merged**
