### PR TITLE
New necrostone and demon vial sprites

### PR DESCRIPTION
**Pull request by ChangelingRain**
OLD - STOP PASSIVE AGGRESSIVELY MEMING ALL OVER MY SPRITE NERD - RR - IT WAS A RECOLORED GLASS SHARD I'LL MEME WHAT I WANT - I'M NO SPRITER STOP JUDGING ME
OLD!
NEW
NEW!

INCLUDES NECRO-MAGIC PULSING ANIMATION, WHICH I HAVEN'T BOTHERED TO GIF.
NOT A GIF

BONUS SPRITE, NEW DEMON VIAL WITH MORE SUBTLE PULSE ANIMATION
YEAH
IT'S SUBTLE ENOUGH I'M NOT SCREENSHOTTING IT

### CODE REVIEW

**Comment by PKPenguin321** [comment]
yaaay

**Comment by Ergovisavi** [comment]
The new necrostone sprite, while unique, is also significantly less sinister looking. I don't know how I feel about that.

**Comment by WJohn** [comment]
I'll come up with something tomorrow.

**Comment by WJohn** [comment]
How's this for the necrostone?

**Comment by Anonus** [comment]
I have personal opinions that it should be an orb and have a sickly green color as cult's kind of got red-black already.

**Comment by WJohn** [comment]
Up to you to take it, it's in temple.dmi if you want it.
http://www.mediafire.com/download/c4y6u1x45k49wri/VOLCANO_LAND_1.1.2.rar

**Comment by Razharas** [comment]
WJs word is the highest priority in sprite changes @Anonus

**Comment by Razharas** [comment]
@Anonus goddamn make wj happy already dont be that guy

**Comment by WJohn** [comment]
Whatever, I'll live with this for now.

**Pull request merged**
