### PR TITLE
Mech rocket replacement

### PR DESCRIPTION
**Pull request by ghost**
The mech missile rack is exceptionally powerful, and has little counterplay, being able to instantly crit and often remove limbs. This PR replaces the missile rack tech with a new weapon: a CLF3 grenade launcher.

The grenade splashes 1u of ClF3, creating a very brief radius 4 flash of fire. This ignites a light fire on everyone in the radius. The fire deals damage rapidly, but can be easily be countered with a fire extinguisher. As it is ClF3, it does not heat up the air.

:cl:
add: You can now research a ClF3  grenade launcher for mechs.
del: You can no longer research a missile rack for mechs.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Epic

**Comment by zxaber** [comment]
Isn't the rocket launcher like the go-to weapon for fighting other mechs?

I wonder if there's a way to re-balance it to make it worse for fighting people on foot? Maybe like if the rocket hits a person (rather than a wall or mech), it just sorta beans them and doesn't explode, doing a small bit of brute?

**Comment by py01** [comment]
The missile rack actually has rather mediocre DPS being outclassed by the scattershot and lmg, the issue is that it has the spike damage to oneshot humans and some mechs. However, for mechs that cannot be oneshot, other weapons deal damage at a faster rate.

**Comment by PKPenguin321** [comment]
Maybe some things SHOULD instacrit and blow you up

**Comment by Angustmeta** [comment]
You are using the proper chemical name, ClF3, but I think it looks confusing with a lowercase L. People will start calling it "siff-launcher" in their inner headcanon voices. 

Would rather have it called flame grenade launcher or some made up fancy name.

**Comment by Suicidalpickles** [comment]
mecha battles are super unfun when the other dude can just click the other pilot with a missile and get a hard explosion knockout on them to follow up with like another missile or whatever
also worth noting they're stupidly cheap to produce, literally just gold and silver for missile racks, could see changing the material requirements as another good alternative.

**Comment by Barhandar** [comment]
Instead of just deleting fun (for the mech pilot who has it) features, lock them behind illegal tech node, considering IIRC you now need actual traitor items to unlock it, and make it do two-click launcher (i.e. one click to shoot, delay, click to load next rocket) or at the very least have noticeable feedback about being ready to shoot so people can GTF behind obstacles.

**Comment by py01** [comment]
probably a better solution actually

**Comment by Barhandar** [comment]
Oh and have duck and cover actually work for dodging the rocket (i.e. slow said rocket down a bit and if target `rest`-ed or otherwise went horizontal after rocket launched, redirect it to pass over them instead of hitting; but still hit them if they were prone _before_ it launched to prevent the "crawl makes you reverse crab" thing rework had at first).

**Comment by necromanceranne** [comment]
Honestly just nuke this weapon from orbit. It's outrageous this kind of power can be added to mechs who are already very powerful. Even if they have the lowest DPS they are still able to ex_act everything it hits with one click. At least with any and all other mech weapons they're able to be survived more than a single click.

Yes, they're good against other mechs. But rare is the instance two mechs are fighting one another, because often mechs are made in exactly one place and that's robotics, and becaue of such they can do some sneaky stuff to prevent other mechs from being made in response.

**Pull request closed without merging**
