### PR TITLE
PopulateContents refactor 

### PR DESCRIPTION
**Pull request by ghost**
Confirmed by cobby this is much better than what it is now!

Null crates will suck we'll get to that when we do

### CODE REVIEW

**Comment by optimumtact** [comment]
\>initing a whole bunch of lists at compile time on every storage item

This is bad

**Comment by ExcessiveUseOfCobblestone** [comment]
I told him to null it

**Comment by ExcessiveUseOfCobblestone** [comment]
mfw he doesn't understand the PR process this far into the game.

**Comment by Armhulen** [comment]
LIKE 5 MINUTES DUDES

**Comment by optimumtact** [comment]
use the lazy list macros

**Comment by Cyberboss** [comment]
I see zero advantage over the current system other than knowing what was initially in a container. Which is dubious info at best

**Comment by Cyberboss** [comment]
This ALSO means that you can't have random probability contents anymore

**Comment by ExcessiveUseOfCobblestone** [comment]
The Idea was to generalize the common function of spawning objects as-is with a singular list that changes per crate rather than having to override the proc literally every crate.

Obviously oddities would not fall under this and would have to retain their original popcontents proc.

**Comment by Armhulen** [comment]
i plan to actually do this but like, after crypt and armor values and coven

**Pull request closed without merging**
