### PR TITLE
Kilo mapping fixes

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Some minor Kilo mapping fixes: 
- adds one missing length of disposals to mech bay
- warden's office disposals now connects to the loop properly
- lawyers still have access to the brig infirmary but can't get to the meeting room through it

## Why It's Good For The Game
Fixing some small oversights

## Changelog
:cl:
fix: kilo: added a missing length of disposals in mech bay
fix: kilo: warden's disposals now enter the loop properly
fix: kilo: lawyers can no longer get into the meeting room through the infirmary
/:cl:

### CODE REVIEW

**Comment by Cartographer-D** [comment]
Disposals is also messed up in sec, it reroutes to the Warden's office. Could you fix that and fix the access on the medical post there so they lawyer can't get into the meeting room?

**Comment by dragomagol** [comment]
Sure thing, I can take a look at that tomorrow.

**Comment by Jared-Fogle** [comment]
Your changelog is inadequate, please update it.

**Comment by dragomagol** [comment]
Oh whoops, forgot to fill in the template

**Pull request merged**
