### PR TITLE
The Tomb of the Unknown Employee is now indestructible

### PR DESCRIPTION
**Pull request by coiax**
I don't think having it being in a state where it can be vandalised is particularly
polite.

### CODE REVIEW

**Comment by Niknakflak** [comment]
Change the line " This memorial has been designed for him and any future coders to perish."
to
"This memorial has been designed for him and any future contributors to perish."

While you are at it since goofball forgot to

**Comment by lzimann** [comment]
You know, it being destructible is so ss13 spirited that I don't really agree with this change.

**Comment by RandomMarine** [comment]
What Izimann said. It'll be back next round, anyway.

**Comment by Cyberboss** [comment]
>Implying half of centcomm's structure isn't already indestructible

**Comment by optimumtact** [comment]
Move it up into the grassy area that has windows into the shuttle arrival from the top and put it behind some unbreakable windows.

so it's like a shrine you look into on the way into centcomm

**Comment by coiax** [comment]
That's out of scope for this PR.

**Comment by optimumtact** [comment]
I'm making it in scope, if you don’t' want to do it just close your pr.

**Comment by Iamgoofball** [comment]
Please leave it where it is, I want people to see it when they undock

**Comment by Niknakflak** [comment]
they will see it in both places.

**Pull request closed without merging**
