### PR TITLE
Adds the eyepatch to the Autodrobe

### PR DESCRIPTION
**Pull request by SerenHighwater**
## About The Pull Request
Adds the eyepatch to the Autodrobe costume vendor. 

https://user-images.githubusercontent.com/102489377/212571492-a8f7f747-3ad7-4623-a546-f62cdae9bbdf.mp4
## Why It's Good For The Game
The eyepatch was previously only available on Metastation and Kilostation, this change will allow people to stylize their characters and bug the admins less.
## Changelog 
🆑 
add: Added the eyepatch to the Autodrobe.
/🆑

### CODE REVIEW

**Comment by Farquaar** [comment]
Regarding the video- is it possible to put monkeys and other small-ish simplemobs in washing machines? If not, why not?

**Comment by VladinXXV** [comment]
👍

**Comment by Serxule** [comment]
hasnt it always been in the costume vendor? im 99% sure i've bought it multiple times before

**Comment by Slurge00** [comment]
> hasnt it always been in the costume vendor? im 99% sure i've bought it multiple times before

theres other pirate clothes, but no eyepatch there.

**Pull request merged**
