### PR TITLE
Tweaks some prices of cargo exports

### PR DESCRIPTION
**Pull request by jughu**
I tweaked the exports for the following reasons

-Alien organs:i buffed the price since alien organs arent in NPC alien mobs and auctally are rare and need effort to get them
-Alien Hide:nerfed to 3000 because its kinda stupid how they are worth 15000 points which would make a alien hive at mining make up for points for 13 supermatters without really any effort since NPC mobs are weak
-Alien Alloy:nerfed from 10000 to 5000 since science can pretty much mass produce them for cargo when they get alien tools (which is quite common at mining since theres a ruin that gives the tools) alien alloy required 5 plasma which is 2500 points so i nerfed the price just a little above that so they still give profit just not horrible amounts of it

:cl:
tweak: Changes some cargo export prices
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)
image

### CODE REVIEW

**Comment by Kromgar** [comment]
>Doesnt touch the biggest offender tech disks

**Comment by jughu** [comment]
@kromgar tech disks are supposed to go for once and not infinitly

**Comment by calzilla1** [comment]
And yet 99% of the time cargo usually has >1000 credits. ALSO MAKE CRATES WORTHLESS AND DE/CONSTRUCTABLE HOLY SHIT ITS A PAIN TO EXPORT THOSE FUCKERS

**Comment by jughu** [comment]
@korphaeron what you think about this is this reasonable changes to lower the infinite points things

**Pull request merged**
