### PR TITLE
Ausops Sprites for Air Tanks

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Ausops
add: Air tanks and plasma tanks have been resprited.
/:cl:

tanks

### CODE REVIEW

**Comment by Ausops** [comment]
thanks kor

**Comment by Kromgar** [comment]
Das some pretty shit

**Comment by Steelpoint** [comment]
The only problem with these sprites is that they are too detailed in comparison to everything else. I wonder how much a commission to get Ausops to resprite everything in the game would cost?

On topic, these seem, at face value, to be well done and high quality sprites.

However, what's the story with the duel extended emergency tanks? Also why do we have two different extended emergency oxy tanks, one with and without a stripe?

**Comment by GunHog** [comment]
**ALL GLORY TO AUSOPS**

**Comment by RemieRichards** [comment]
@Ausops what palete did you use? (since we're in a unified palette push atm)

**Comment by Ausops** [comment]
they replace similar sprites in the dmi that are currently not used, it was just simple to update them with the rest

my own """"""""""""palette""""""""""""""""""""""""" and a few oranges I think from danno's palette

**Comment by Militaires** [comment]
rogue white pixel in the double yellow extended tank

**Comment by RemieRichards** [comment]
we need to sort this palette nonsense out.

**Comment by GunHog** [comment]
I sincerely hope that palette enforcement does not result in discouraging spriters. We have so few sources for new art that I do not believe we can afford losing anyone.

**Comment by Ausops** [comment]
mili- thats just an error with the screenshot, there should be no rogue pixel in the dmi

remie I simply don't have the skill, experience, or dedication to make a palette that I can guarantee won't need updating moments after it comes out.

**Comment by RemieRichards** [comment]
I hope the spaceman palette works out then.

**Comment by Cyberboss** [comment]
I came

**Comment by Kromgar** [comment]
@Ausops you are the fucking best.

**Comment by Aloraydrel** [comment]
Hnnnnnnnnng

**Comment by ChemicalRascal** [comment]
I'm particularly confused by the weird double-tank things as well

also something something something ttv sprites are going to now look trash by comparison

**Comment by Nienhaus** [comment]
All sprites will look like trash till there updated, but I don't see a problem with waiting.

**Comment by ChemicalRascal** [comment]
but how can our trash be real if our sprites aren't real

**Comment by calzilla1** [comment]
Make the plasma canister bigger and it'll be :+1:

**Review by ghost — APPROVED** [review]

**Comment by Niknakflak** [comment]
we could just not have a pallete

**Comment by dannno** [comment]
why would we not
what is this delusion that having a palette would discourage anyone from making things
"hmmm I can't use a gradient of 33 different shades of the same color? guess I won't be contributing to THIS game."

oh no, what a loss!

**Comment by chanoc1** [comment]
oh wow , these look miles better than mine. do you make tutorials?
@Niknakflak i dont see why people dont want a palette. the colors are chosen for you! It also gives everything a unified look

**Comment by erwgd** [comment]
I don't like the look of the new plasma tank, as it doesn't keep the style of a fuel can.  

The old one is easy to recognize as some kind of fuel can: 

- It has a nozzle on the top 
- The markings look like indentations on metal, a bit like the ones seen on jerry cans. 
- It stands upright, which matches with ideal visualizations of fuel cans. 
- The handle is near the center of the tank, which would make it easy to carry while keeping it upright (this doesn't matter much because spacemen don't carry plasma tanks by the handle).

**Comment by dannno** [comment]
The only thing that scares me about these tank sprites is that they are such a radical change and increase in quality when my original plan was to improve most of the sprites already in game just by changing the colors on them and the way they are used, so everything would still be familiar.
With these looking so different and far above your standard spacemen sprite, the pressure is really going to be on to make everything look like this

**Comment by CosmicScientist** [comment]
Nice detail.

My eyes catch on the dark outline though.

**Comment by WJohn** [comment]
my _god_

**Comment by Ausops** [comment]
i've done mine with a fuel cell/battery in mind, since they get used in collectors, which will make more sense later hopefully

its a very noticeable outline compared to the existing ones, its part of a larger attempt to try out a new way of redoing sprites

**Comment by optimumtact** [comment]
wow these are ugly and pillow shaded, which noob did these? denied

**Comment by chanoc1** [comment]
damn nukkuh

**Comment by optimumtact** [comment]
there's just no good bait left anymore

**Comment by Qbopper** [comment]
they look amazing but I need to complain about muh nostalgia

I don't know what to do

**Comment by chanoc1** [comment]
fuck YOU with your "nostalgia" BULLSHIT

**Comment by Haevacht** [comment]
Fucking hell ausops i preferred when you were a ghost who made only grass.

**Comment by jughu** [comment]
687474703a2f2f692e696d6775722e636f6d2f7253556965335a2e706e67

**Comment by dannno** [comment]
to be fair these are going to look super out of place in contrast to every single other thing in the game

**Comment by dannno** [comment]
although that could just be the fact that I'm used to how things are???? weird

**Comment by Davdichan** [comment]
Literally all of the lavaland fauna, bluespace shelters and ayyductor ship sprites look out of place next to the old sprites.

**Comment by dannno** [comment]
I don't see that tbh

**Comment by RemieRichards** [comment]
@Davdichan 
>an alien world looks out of place
>an alien spacecraft looks out of place

These are the only reasons those are really allowed to slide, same with Ausops' slaughter demons, they're demons! eventually, if something more common and "intended to be normal" like airtanks were changed then maybe things would get a bit weird. oh, wait...

**Comment by Davdichan** [comment]
I never said these were bad, just that the general art style is expected to change after nearly a decade and new spriters on the job. Plus if Aus continues to update sprites it'll be pretty cool to see SS13 get a face lift item by item.

**Comment by GunHog** [comment]
I am perfectly willing to accept Ausops sprites even if they seem out of place! It is like resisting a home grilled, perfectly cooked, perfectly season hamburger because the fast food burgers you eat every day taste awful in comparison!

**Comment by optimumtact** [comment]
We dont' do consistency, we just do art that works, that's how our content pipeline keeps going.

**Comment by Thunder12345** [comment]
Agreed, we can update other sprites over time when people are willing

**Comment by CosmicScientist** [comment]
rip old tanks.
Allo new tanks.

I hope someone gets an idea for using the spares and maybe the green light on it gets used too.

**Comment by jughu** [comment]
Green light should the tank containing a minimum amount of oxygen you able to breathe without suffocation and red light empty

**Comment by Iatots** [comment]
Maybe when people decide on a palette these can be revisited, they are so dull for pressurized steel containers.

**Pull request merged**
