### PR TITLE
Gives peacekeeper cyborgs an aggressive security hailer

### PR DESCRIPTION
**Pull request by silicons**
Requested by @YakumoChen

### CODE REVIEW

**Comment by Mark9013100** [comment]
You have the right to shut the fuck up.

**Comment by Bawhoppen** [comment]
This defeats the joke of peacekeepers entirely

**Comment by Qustinnus** [comment]
it wasnt a funny joke anyway

**Comment by Armhulen** [comment]
We should really get around to removing them

**Comment by BeeSting12** [comment]
The meme has gone too far

**Comment by Cyberboss** [comment]
>Can't equip

>No fucking point

**Pull request closed without merging**
