### PR TITLE
Adds the Angel AI Core sprite to the game

### PR DESCRIPTION
**Pull request by Niknakflak**
Adds a new AI sprite to pick.  The Angel AI.  Turns into a pseudo devil skelly wings thing on death.

Angel Core Sprite:

Angel Death Sprite: 

Sprites by Nienhaus

### CODE REVIEW

**Comment by Zilenan91** [comment]
If the AI is dead how does it have the power to keep something on its screen like that

**Comment by PKPenguin321** [comment]
yeah i always thought dead AI should have like a busted open screen sprite that sparks occasionally or something

**Comment by Niknakflak** [comment]
Tons of AI sprites have a dead sprite that isn't a "blank screen" or what not, they go along with the theme of the AI cores most of the time.  Have you looked in the AI folder recently?

**Comment by coiax** [comment]
Because the AI core is damaged enough to have the personality be dead but not damaged enough that it's pieces. And/or because it looks cool.

**Comment by Niknakflak** [comment]
I dont understand what you are even trying to say

**Comment by optimumtact** [comment]
They're supporting you

**Comment by Dorsisdwarf** [comment]
"dead" ais aren't really dead, remember. They've just been damaged enough that they cannot function.

Thats why you can rez them in the Integrity Restorer.

**Comment by coiax** [comment]
Just like humans! Pop them in a cloning machine to grow them a new body, and then they're good as new!

**Comment by Miauw62** [comment]
rip avacyn ;_________;7

**Comment by Supermichael777** [comment]
technically the ai doesn't die it crashes and needs to be reset in its specal reboot thing

**Pull request merged**
