### PR TITLE
Server_maint now clears nulls from client list

### PR DESCRIPTION
**Pull request by Cyberboss**
BYOND is stupid and doesn't always call client/Del

### CODE REVIEW

**Comment by optimumtact** [comment]
This seems like a bit of a hack to work around this, is there a byond bug report up? IF so can you add ac omment with the link?

I dont' want to merge this without a bug report being made either.

**Comment by Cyberboss** [comment]
I'm basing this off what @MrStonedOne said in #26489

**Comment by AnturK** [comment]
Maybe we should move the data to some local client datum then just link/delete/access that instead of built-in client. Might be overkill and lot of work.

**Comment by MrStonedOne** [comment]
Before we can justify making a byond bug report, we would have to move https://github.com/tgstation/tgstation/pull/26489/files#diff-93858377afdcb549a0ac8990f3c96e22L337 to the top of the proc to eliminate the possiability of runtimes in client/Del.

**Comment by Cyberboss** [comment]
Yeah, I'll try that out first

**Pull request closed without merging**
