### PR TITLE
Roundstart AIs are positronic

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

If you disassemble an AI which was in the round from the start it will produce a Positronic Cube rather than an MMI with the brain of that player's usual human character in it.

Also I made changes to a couple of feedback balloon alerts which would always trigger a runtime when constructing or deconstructing an AI, this was because balloon alerts have a small time delay before executing and we deleted the AI mob or structure after trying to show a balloon alert on them, so they'd never appear.

## Why It's Good For The Game

Honestly this is _mostly_ about vibes, it has annoyed me since AI deconstruction was added that Nanotrasen AIs tend to actually be brains in jars rather than AIs. Now they're artifical.
It does also mean that you can't deconstruct the AI and then put its brain into a human body, which is similarly mostly bad because of vibes: If you sign up as an AI I think you should be an AI or a cyborg even after deconstruction.

It also universally looks really stupid when you deconstruct an AI and it says it has the brain of Penelope Dreadful in there, like should I expect them to start RPing as their normal character instead of the AI they have been playing all round now?

## Changelog

:cl:
balance: Roundstart AIs are now made of positronic cubes, rather than brains inside MMIs
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
i should have added the brain blender

**Comment by DaydreamIQ** [comment]
What about borgs? Its been a hot minute since I saw a roundstart borg get deconstructed but as far as I know they get the same issue of an MMI popping out when they should just be a full AI

**Comment by Jacquerel** [comment]
> What about borgs? Its been a hot minute since I saw a roundstart borg get deconstructed but as far as I know they get the same issue of an MMI popping out when they should just be a Posi

This bothers me less because they are called "Cyborgs" which implies the presence of at least one organic part (although they should probably have random names to avoid the "oh yeah I know that static" issue)

**Comment by Jacquerel** [comment]
> Why not make this a player preference?

Because I know better than them
Also a toggle for this feels like bloat until AI has its own separate page (which it probably isn't ever going to have)

**Comment by projectkepler-ru** [comment]
> Why not make this a player preference?

the only server that need it are ERP server smh

**Comment by JohnFulpWillard** [comment]
> (although they should probably have random names to avoid the "oh yeah I know that static" issue)

SO FACTUAL

**Review by Mothblocks — APPROVED** [review]
cool idea

**Comment by xzero314** [comment]
This makes me sad as I have a head canon for my ai static that relies on it being a real brain. It probably wont matter at all though

**Comment by Dorsisdwarf** [comment]
Oh thank you. Great change, finally.

**Comment by FlufflesTheDog** [comment]
I kind of liked the lore of some character ending up as the AI, either by choice or not. It's cool to have the occasional AI that plays into being the remnants of some characters personality.
Though for the people that don't do that I agree it could be pretty awkward

**Comment by ATH1909** [comment]
for what it's worth, skyrat has a preferences setting for this that takes up like one line. I really don't think an MMI vs. posibrain toggle switch put next to, say, the place where you select your borg name would be bloat.

Whether or not your silicon is human-derived is actually a significant thing for RP/character consistency, and it's awkward to have this disconnect between what you say your character's background is and what it's actually revealed to be whenever they die.

**Comment by tralezab** [comment]
LORE SANCTIONED PR
LETS GO JACQUEREL!!!!

**Comment by tralezab** [comment]
> for what it's worth, skyrat has a preferences setting for this that takes up like one line. I really don't think an MMI vs. posibrain toggle switch put next to, say, the place where you select your borg name would be bloat.
> 
> Whether or not your silicon is human-derived is actually a significant thing for RP/character consistency, and it's awkward to have this disconnect between what you say your character's background is and what it's actually revealed to be whenever they die.

this might be an interesting ai preference, yeah

**Comment by ATH1909** [comment]
> this might be an interesting ai preference, yeah

borg preference too

**Comment by DATA-xPUNGED** [comment]
Ideally, the process of making an AI would involve uploading a real brain or a posi into an intellicard, and uploading that to the core. Doing so would let your statics be either without adding a preference. But I'm just ideasguying here

**Comment by Fikou** [comment]
> Ideally, the process of making an AI would involve uploading a real brain or a posi into an intellicard, and uploading that to the core. Doing so would let your statics be either without adding a preference. But I'm just ideasguying here

im telling you guys we replace mmis with brain blender

**Comment by DATA-xPUNGED** [comment]
> > Ideally, the process of making an AI would involve uploading a real brain or a posi into an intellicard, and uploading that to the core. Doing so would let your statics be either without adding a preference. But I'm just ideasguying here
> 
> im telling you guys we replace mmis with brain blender

We should also be able to put the brain in a grinder and drink the juice that comes out to get an imaginary friend, but y'all ain't ready for that conversation

**Pull request merged**
