### PR TITLE
Removes Mindless mobs from Orbit list.

### PR DESCRIPTION
**Pull request by AnturK**
Jump-To-Mob left untouched if you want to watch some mindless mob.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Thanks

**Comment by YotaXP** [comment]
What about the singulo?  Can we still doubleclick anything to orbit?

**Comment by AnturK** [comment]
All non-mobs still on the list. And yes everything is still orbitable by double click.

**Comment by MrStonedOne** [comment]
Ghosts that observed from lobby have no mind.

It would be better to check ckey.

Also this should still have bots once simple animal bots is done, as orbiting a bot is still something people might want to do.

**Comment by Bawhoppen** [comment]
>when simple animal bots is done

I'm glad you have faith

**Comment by AnturK** [comment]
Good point about roundstart observers, i'll change this a bit.

**Comment by Aranclanos** [comment]
well this removes ian, punpun and other lovely pets from the list in a pretty awful way.
If you want to separate them, make an interface for the orbit, that gives you two lists in a window, mindless and with mind, instead of just lazyremoving

**Comment by AnturK** [comment]
Use jump-to-mob if you want to observe boring animals. Removal of things that are usually boring to watch from the orbit list is the whole point of this.

**Comment by tkdrg** [comment]
Sure I guess. You can always Jump to Mob and then doubleclick either way, which isn't that much of a difference.

**Pull request merged**
