### PR TITLE
MULTI-Z IceBoxStation Locker Room (Laundromat Diplomat)

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

This PR, among other things, enchants the locker room section (near arrivals) on IceBox Station to further reflect it's tunneled in planet status. The locker room/toilet/maintenance section has not seen some love for a good while, and this should help rejuvenate and bring parts of it up to speed. For your reference, here is the old IceBox Dormitories:

image

It's old, has the obtuse line of scrubbers/pumps (they show up as errors but they do work in game, i don't know how or why i blame sdmm). But now, let's take a ponder at the new locker room!

image

Very swag, and epic, no? I touched up some bits here and there, added some variety with random spawners, and just overall pushed some stuff that wasn't really necessary. If you're concerned about me straightening out the maint tunnels, I made it obtuse in other location (in the screenshot). When I did Science on Ice Box last year, I tried to honor the name by making it "boxy", and I think this also follows that same "box" shape. But... where's the laundry room?

image

Brilliant, there it is. I wanted to give the laundry room a sort of tunneled away feel, as if it was just dug and slapped down. It's homely, but it's creation wasn't borne out of love. It also has an airlock to progress onto the rest of the empty ice planet, as well as a balcony with some ~stellar~ views, as well as a small bridge out to the left that spans the distance between the airlock and the rest of the ice planet. I originally wanted the laundry room to be a pit (and that's just it), but I think this adds something more to the blank chasms you normally see.

The GENTURFS on the devil's tooth there (that's what I'm calling it) is intentional, you really aren't supposed to be out here because a wolf could maul you. You still have the option of making the precarious trek down and about the bridge to access the views. Splendid.

I'm going to add the overlays of both the upper and lower sections, just in case I fucked up somewhere and someone can say **YOU FUCKED UP SOMEWHERE!!!**

image

image

## Why It's Good For The Game

This change is another addition into the Multi-Z nature of IceBox Station, and I believe it's a good fit for the game since no one's really showed that locker room more love than the place it is to just shove a tider on some tables, and I hope these changes reflect that in their own way. It's still a room that could still be skipped over (hence what looks like an extreme amount of space), but everything between the old version and the new version is retained.

## Changelog

:cl:
expansion: What's this? Nanotrasen tunneled out a grand hole into the ice planet that Ice Box Station currently rests on! There's a new laundry room! For your clothes! What d'you mean, Ian?
add: You can also exit this laundry room onto a caringly, yet sloppily placed bridge to explore the ice planet (if you really want to). Watch your step, and watch for wolves.
add: To accommodate the grand new laundry room, the locker room (and surrounding maintenance tunnels) have been shuffled around. 
/:cl:

_Feedback is appreciated, as always. Thank you for your time._

### CODE REVIEW

**Comment by timothymtorres** [comment]
Loving the usage of the random spawners.  Good work!

**Comment by MrMelbert** [comment]
Honestly, I wish *more* was done than just this. It's nice (and I like it), but it could be even cooler (no pun intended). 

Some fancy decal work around the stairs and around the place would be swell as well.

**Comment by Bawhoppen** [comment]
Looks good to me, even if it is sad to see the classic design go. 👍 
I would maybe shrink the stairs opening a bit though. Feels a bit too open in this (atrium-esque) which doesn't make sense for a stairways to a laundry basement. 

@MrMelbert We shouldn't discourage incremental changes. I think some people already feel like they need to touch everything all at once any time they make a change, but doing one thing at a time is a perfectly good way to contribute (I think it's maybe better in some ways).

**Comment by san7890** [comment]
I have updated the upper part of the locker room. The images have been updated to the latest commit.

**Review by Twaticus — APPROVED** [review]

**Review by Maurukas — CHANGES_REQUESTED** [review]
Couple of minor issues popping up. 

Duplicate catwalk here:
image
image

image

Lattice under a catwalks here. This runtimes:
image


These firelocks are fairly ineffective. I'm not sure firelocks are needed to separate these two areas to be honest. I would either move themm to the lower floor or remove them entirely:
image

**Comment by san7890** [comment]
> Couple of minor issues popping up.
> 
> -snip-

Firelocks yeeted, catwalks should be gone.

**Pull request merged**
