### PR TITLE
CANCER HAS SPREAD TOO FAR: Locks catpeople to BYOND donators only

### PR DESCRIPTION
**Pull request by Iamgoofball**
>[05:40:49]OOC: Darkbitt/Darkbitt : i&#39;m guessing I got BSA&#39;d because I read the worst cat p**n I could find in the library over comms

I told you this would attract creeps and weirdos BUT YOU DIDN'T LISTEN

now you gotta pay money to get your creep on, support BYOND today

### CODE REVIEW

**Comment by Incoming5643** [comment]
Locking any previously unlimited content behind a paywall is not good.

**Comment by Kevak** [comment]
No.

**Comment by anconfuzedrock** [comment]
thats your excuse, mr maker of the digitigrade pr?

**Comment by Iamgoofball** [comment]
@Incoming5643 @kevak

>[18:01:31]OOC: Darkbitt/Darkbitt : kitttyttytytytytytytytytt
>[18:02:28]OOC: Darkbitt/Darkbitt : like calling your stick a &#39;pee dispenser&#39;
>[18:02:53]OOC: Darkbitt/Darkbitt : FEAR MY PEE-DISPENSER, LOYAL-DOER!

**Comment by ExcessiveUseOfCobblestone** [comment]
would this also put the upcoming elf ears behind a paywall 😢

**Comment by ma44** [comment]
Dear god why did i give iamgoofball the logs

**Comment by Iamgoofball** [comment]
@ExcessiveUseOfCobblestone not if it's its own alien race

**Comment by Arianya** [comment]
As this was subjected to a player vote and reinstated by the latest batch of headmins, this is probably a server issue rather then a coding one.

**Comment by Earthykiller127** [comment]
High priority. Speed merge this. Another glorious quality PR, these are rare to come by.

Already tested this on my own private dream daemon server. Flawless. Absolutely incredible. No bugs, performant and very efficient.

**Comment by Iamgoofball** [comment]
@Arianya you see, cancer spreads through the body

the cancer originated from somewhere though

in this case, it originated from the codebase

consider this chemotherapy

**Comment by BeeSting12** [comment]
werent you banned from making PRs

**Comment by Iamgoofball** [comment]
@BeeSting12 a long long time ago

**Comment by FantasticFwoosh** [comment]
Go big or go home.

**Comment by ShadowDeath6** [comment]
I'm more angry about the fact that goof thumbs-upped his own OP

**Comment by Arianya** [comment]
@Iamgoofball Making cancer analogies doesn't change that this is a server-sided topic (and one that is seemingly settled) that you're trying to change through the codebase.

Or if I devolve to shitposting: "Goof is trying to subvert democratically elected leaders. Catmain means Catmain, traitor!"

**Comment by Earthykiller127** [comment]
You have an anime avatar therefore your arguments are invalid

**Comment by Archie700** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=34&t=8776#p232635

guy got permabanned

**Comment by Iamgoofball** [comment]
@Archie700 i'm aware, we can't allow for any more repeats

**Comment by ExcessiveUseOfCobblestone** [comment]
Nya!

**Comment by KorPhaeron** [comment]
>allow for any more repeats

Repeats of what though? Someone acting dumb and then promptly getting banned? Seemed like things worked out fine

**Comment by Iamgoofball** [comment]
@KorPhaeron player should not have been baited to join in the first place

by adding this crap we pander to them intentionally or unintentionally

if we're stuck with it we might as well turn a buck off of it

**Comment by Arianya** [comment]
@Iamgoofball Wheres your PR to remove lizards so we don't get scalies

**Comment by Iamgoofball** [comment]
i would of done that too but these sorts of things are best done slowly

**Comment by Thunder12345** [comment]
Goof you do realise that admins will almost certainly still hand out cat mode on request, just lik when they were disabled?

**Comment by Iamgoofball** [comment]
@Thunder12345 you missed the last commit where I made it so you can't do that

**Comment by Cebasiz** [comment]
goof why does this shit trigger you so badly

it's just sentient cats who cares

did you have some sort of childhood trauma or something my man

**Comment by Thunder12345** [comment]
You should still be able to varedit them in manually

Or just his mass purrbation

**Comment by Iamgoofball** [comment]
@Thunder12345 I'll be scanning logs for that and if I catch you doing that I'll be reporting you to MSO with evidence of you bypassing our donation rewards, as we'll be moving this over to a merged BYOND/Server donation system

**Comment by Earthykiller127** [comment]
@Cebasiz why do you care about the removal of a virtual ingame furry race that everybody hate anyways

**Comment by Thunder12345** [comment]
@Earthykiller127 Because only a tiny minority actually get this mad about them existing?

**Comment by Iamgoofball** [comment]
@Thunder12345 As I've stated, I see an opportunity to fund both the servers and BYOND off of the sorts of people who are vain enough about their characters to stick this sort of snowflake crap on them.

**Comment by Spacedong** [comment]
sounds good to me personally I want to port it to hippie

**Comment by Arianya** [comment]
Can we content gate freon behind donating so we can inevitably replace the server hardware when freon lags them to death.

**Comment by Earthykiller127** [comment]
@Thunder12345 why do you care about locking it as a donation reward?

**Comment by Iamgoofball** [comment]
@Arianya i removed freon from active duty ages ago but I guess someone added it back, contact @optimumtact about his slip rewrite which will fix the lag

**Comment by FantasticFwoosh** [comment]
@Earthykiller127 they are literally purely cosmetic human mutations, in gameplay terms it raises a lot of issues for policy as to whether they are human, their own race or not. Such is the case for silicons being divided whether to listen to a concealed cat-person who's listed on IC records as human.

> Not to mention cat ears being a aesthetic item

The alternative is to push them into sprited full furry anthro race in order to make them distinct but many people i imagine wouldn't want to even take a single step in that direction for the same objections they find catbeasts appalling now.

**Comment by Arianya** [comment]
@FantasticFwoosh Its already been ruled by headmins that they're mutants akin to hulks, i.e. non-human

https://tgstation13.org/phpBB/viewtopic.php?f=33&t=8660&start=150#p231011

**Comment by Spacedong** [comment]
ill send you the sprites and then we can introduce dragon dildos for byond members too

**Comment by Spacedong** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
thanks fam 🍆

**Comment by oprayx73** [comment]
pass this shit bruh fuck them furry ass nigas

**Comment by Earthykiller127** [comment]
@FantasticFwoosh Yeah and why do people care

Cats have shit sprites and serves as amazing target practice for me due to them carrying the "chattiboxus disease" which causes the infected individuals to only look at their chat window and never the actual game itself

**Comment by Iamgoofball** [comment]
>chattiboxus disease

you know if ascii mode still worked I'd add this

**Comment by Spacedong** [comment]
add *poo emote but let it only be for donators who have donated $50 or more

**Comment by Earthykiller127** [comment]
@Iamgoofball force toggle text mode on catbeasts

**Comment by Iamgoofball** [comment]
that is ascii mode, it broke around 506 I think

**Comment by FantasticFwoosh** [comment]
@Arianya the reason i pick it out is that its very minor body details, perhaps it may be so, but through a suit you would never know because there are no factors that give it away.

Tails & Ears are fully cosmetic super concealable with basic clothing items & at-least tail-less fully suited lizards have a give away lisp.

**Comment by optimumtact** [comment]
Did we get posted on reddit? include me in the screencap

**Comment by Earthykiller127** [comment]
It works fine, it's just that the letters are never updated even if you move so it's impossible to play. Very realistic HRP simulation

**Comment by Spacedong** [comment]
dragon dicks

**Comment by KorPhaeron** [comment]
http://i.imgur.com/xHwCbGl.png

I care because having a week long vote and then telling 200+ people "haha nevermind pay up" is poor behavior no matter how minor or silly the feature

Also I can't speak for @Ricotez but it feels a bit weird to restrict and sell content that he created for free and committed to be used by anyone when he'll never see a dime of it.

**Comment by Arianya** [comment]
@FantasticFwoosh What I'm hearing is that you want catmutants to append sentences with "Nya"

**Comment by Earthykiller127** [comment]
@KorPhaeron I'm confused. What exactly is the problem here? They are still enabled with this pr.

**Comment by optimumtact** [comment]
@KorPhaeron nobody but byond will see a dime of it

**Comment by FantasticFwoosh** [comment]
@Arianya i detest the prospect but if it has to be done, so be it.

**Comment by KorPhaeron** [comment]
@optimumtact 

There are people with other similar plans

http://www.byond.com/forum/?post=2182467

**Comment by Earthykiller127** [comment]
classic lummox immediately answering to the call of duty in less than 20 minutes when there's money to be made

**Comment by optimumtact** [comment]
Guys gotta eat

**Comment by Iamgoofball** [comment]
don't you love capitalism i sure do

**Comment by Iamgoofball** [comment]
>http://i.imgur.com/u1Q8TcH.png

they're sending agents to censor us

**Comment by Earthykiller127** [comment]
damn liberals

**Comment by Anonmare** [comment]
Saltsphere does it again

**Comment by Hatfish** [comment]
didn't someone try to do this exact same thing ages ago for lizards?

**Comment by Earthykiller127** [comment]
Has nobody noticed the eastee egg yet???
????????

**Comment by ShadowDeath6** [comment]
>implying locking a race with no advantages or disadvantages and are almost completely associated with fur fetish behind a paywall that's directly benefiting the creators of the engine that runs the game will turn into a slip slop

**Comment by kevinz000** [comment]
The issue was Darkbitt being a dipshit. The solution is that he is banned. It isn't limiting more cosmetics to BYOND donators

**Comment by TechnoAlchemisto** [comment]
This is a pretty funny thread

**Comment by lzimann** [comment]
what is bad about giving money to byond and the server(like it should be instead of just byond membership) so you can be a special furflake!

**Comment by Haevacht** [comment]
Why is goof still allowed to make PRs.

**Comment by Supermichael777** [comment]
Don't do this shit goofball; some of us don't have job's.

Income should never make players unequal and i personally resent the current donator only content.

Find a better hill to die on; preferably one we don't have to listen to you from.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm pretty sure the headmins explicitly said being a donator feature down the road....

**Comment by Iamgoofball** [comment]
@Supermichael777 there's no gameplay benefit you're buying here, do you think I'm dumb enough to make this pay to win

if you want to go down that route it's actually paying to lose because you get a bigger hitbox

**Comment by YakumoChen** [comment]
Catpeople aren't even furry though

**Comment by YakumoChen** [comment]
All the current donator benefits are explicitly non-gameplay related. Custom ghosts and OOC colors have nothing to do with a round and have no effect. Locking a race behind a paywall WILL have in-game consequences (as it actually is gameplay related) and allowing this will allow coders to do more things down the line in a similar sort. Next we'll have custom items for donators and other things that will have effects on the round.

Not only this but it allows people to in-game discriminate against people who have donated because they will possess donator-only benefits that normal crew will not have.

**Comment by PKPenguin321** [comment]
>All the current donator benefits are explicitly non-gameplay related.

Wrong, xeno queen maid skin

**Comment by ShadowDeath6** [comment]
since when was erp a gameplay feature

**Comment by PKPenguin321** [comment]
I don't know but neither are cat ears

**Comment by YakumoChen** [comment]
Cat ears make you nonhuman and leave a giant 'I AM A DONATOR' beacon if this is merged. It becomes game play relevant when people have an in-game way of telling that you may or may not be a group of certain players, and can act on it.

The xeno maid thing I could argue isn't the same, since Xenos aren't a roundtype and are a rare enough antag that I've only ever actually seen the Xeno Queen Maid skin once, and doesn't have an impact on gameplay since all xenos are required to follow the queen regardless - no discrimination is possible.

**Comment by Ultimate-Chimera** [comment]
The only goof pr I support. 👍

**Comment by GunHog** [comment]
Why do we continue to allow Goof to do things like this?

**Comment by Cebasiz** [comment]
who knows

**Comment by Arianya** [comment]
@lzimann Nothing wrong with giving money to the server and byond.

What is wrong is creating a political PR to try and backdoor isolate content goof dislikes, and pretending its all about "the server" when really its all about "goof dislikes x". Doubly so when its content thats been subjected to a player vote and a decision made by the headmins.

Whats also wrong is paygating existing, available content behind a donationgate. If goof or anyone wants to make cosmetics that go behind a donationgate to help support the server, all the more power to them, but doing so with content already in the game is a kick right in the teeth to players.

Though, I do like that if you implement a change goof dislikes its "Why are you forcing your ways on players who don't want this" but when he does the same its "No guys this is totally not a political PR, its to help ~the server~"

**Comment by jughu** [comment]
Make making prs for byond members only

**Comment by FantasticFwoosh** [comment]
@YakumoChen catpeople are not a race. 

For all purposes of definition they are a 'mutation' of humans, (like hulk, or the equivalent of lizard horns etc)

**Comment by Earthykiller127** [comment]
You're right, catpeople aren't a race. They're a problem.

**Comment by AnturK** [comment]
You know this could actually be discussed on it's merits if you just presented the change instead of forcing some agenda with it. Now it's just another pissing match that goes nowhere.

**Comment by kevinz000** [comment]
@Earthykiller127 Probably because most of the 200 people who voted yes aren't donators. All you've been doing is spewing hate without rational thought to what just happened with the latest server vote.

**Comment by jughu** [comment]
How 4 extra pixels triggers people

**Comment by Earthykiller127** [comment]
@kevinz000 server had a poll to allow erp and everyone voted yes overwhelmingly then the change was reverted. And you complain about the disregard of server votes?

**Comment by Arianya** [comment]
@AnturK You're making the mistaken assumption that Goof cares about the server upkeep and isn't just using it as an excuse to enact changes.

@kevinz000 That rshoe, probably not worth trying to have a serious discussion with him

**Comment by Earthykiller127** [comment]
@Arianya https://youtu.be/qbeEO58Hlfo

**Comment by TehZombehz** [comment]
By adding only 5 lines of code, goof succeeds in starting another shitfest as revenge for being triggered recently.

**Comment by Earthykiller127** [comment]
if(config.mutant_humans && unlock_content) // rshoe is pretty cool and I'm in love with Earthy

**Comment by kevinz000** [comment]
@Arianya  HONK I didn't notice.

**Comment by Firecage** [comment]
Didn't we go over this entire thing previously when some ass tried to make Lizardmen locked behind being as Byond Member?

If you want to lock content behind then, then make original content to lock behind it. Don't do it for existing content.

Besides, I also disagree, like with the Lizardman one, that this is a byond member lock which isn't something which doesn't influence anything IC'ly at all.

**Comment by Owegno** [comment]
I'm not even going to read all 92 comments so if someone already said this go ahead and fuck me. Putting anything in-game behind a paywall is shitty and stupid for a free game that people have always had 100% access to its content (At least content that actually matters in any capacity in-game). The xeno-maid sprites should either not be in the game or be for everyone, any donation benefit should be things like being able to change your ghost sprite, ghost orbit pattern, OOC color or giving you a little sprite next to your name in OOC. Nothing that is ever visible in-game should be behind a paywall, this is not micro-transaction bullshit simulator 5000.

**Comment by Archie700** [comment]
Let's face it, putting catears behind a paywall will not help in donations because no one except those who really want to be catears would pay money for it.

And considering you lose silicon protection for a bunch of permanent catears, there is absolutely no benefit so there's no incentive to donate so it will not change much.

Locking content that already exists behind a paywall will just result in complaints and no one getting what they want. It's just as Kor and Owegno said. 

Just make new cosmetic content like, Iunno, a /tg/ supporter undershirt or a supporter backpack if you really want incentives.

**Comment by jughu** [comment]
Catears do have a adventage its called easier dying trough robots 
 Now put those catears behind the paywall
Its not pay 4 win after all its all just CosMETIC

**Comment by Earthykiller127** [comment]
@Archie700 what kind of faggot WOULDN'T DONATE FOR CATEARS? It's essential and part of their faggotry. $$$

**Comment by RemieRichards** [comment]
No.

**Pull request closed without merging**
