### PR TITLE
CMO Belt

### PR DESCRIPTION
**Pull request by Hoolny**
## About The Pull Request
After many years of jealousy and sorrow the CMO will finally have an advance version of their underworkers belts fully equipped with the advanced tools they need to perform their job as the CE does

Gives CMO a specialized belt with advance medical tools as they should to put them on pair with CE's shift start belt
## Why It's Good For The Game
Its a bit odd that CE gets a belt full of advance tools and CMO dosent they should both have them as they are both chiefs and its generally good to add an incentive to play those rolls by giving them tools to perform their job faster than their underlings.

image
image
dreamseeker_JzQC4xGzkB
## Changelog
:cl:
add: Added a new CMO medical belt for shiftstart CMO with advanced tools
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
The CMO already has a unique belt-slot item, which is a portable defibrilator.

**Comment by EuSouAFazer** [comment]
Also, the CMO has a bit of a problem with being just MD+ and not actually doing leadership stuff within medbay. This change would put even more pressure on them to do the job of a MD and not the leadership and organization job of it. I don't really like this change tbh.

**Comment by ZephyrTFA** [comment]
Also we've discussed not even giving the CE a filled belt on shift start

**Comment by SethLafuente** [comment]
> The CMO already has a unique belt-slot item, which is a portable defibrilator.

A bunch of CMOs dont use the portable defibrillator personally I find it unnecessary as toolbelts are more efficient to get the job done anyways if a CMO wants to use the defibrillator which is also another advance tool at their disposals they can simply stash their tools into their medbox and such it shouldnt be a reason to prevent this from happening out of the random chance that somebody added that into their locker

**Comment by SethLafuente** [comment]
> Also, the CMO has a bit of a problem with being just MD+ and not actually doing leadership stuff within medbay. This change would put even more pressure on them to do the job of a MD and not the leadership and organization job of it. I don't really like this change tbh.

Its the exact same thing as CE they should both have these tools at their reach im play CMO all the time and CE and I fidn it annoying how I get to have the tools to do my job efficeintly as CE and command my deparment but as CMO im lacking either they both have it or they both dont have it

**Comment by YakumoChen** [comment]
How many times in my life am I going to get to see a closed PR with this title?

**Comment by SethLafuente** [comment]
> How many times in my life am I going to get to see a closed PR with this title?

If this gets closed I will also remove CEs belt its only fair

**Comment by JohnFulpWillard** [comment]
The CE is a bad example of a head of staff and i don’t want the CMO to follow suit of it 

Same reasoning as why I closed https://github.com/tgstation/tgstation/pull/67510 really

**Comment by SethLafuente** [comment]
> The CE is a bad example of a head of staff and i don’t want the CMO to follow suit of it
> 
> Same reasoning as why I closed #67510 really

This is your personal opinion I disagree I think the CE is a good example as ahead of staff and all CMO players would benefit from this change there is no reason behind not adding this other than thinking somehow giving the CMO better tools will make them worse which isnt reallly true

**Comment by JohnFulpWillard** [comment]
@Mothblocks you had interest in the last PR, dunno if you have any thoughts on it this time around too

**Comment by SethLafuente** [comment]
We all know it would be an objectively bad change to remove the advance tools from CE and the same logic applies to CMO but if your logic is that the CMO shouldnt have these tools the same logic applies to CE 

So tell me would you like the CEs tools also being removed?

**Comment by YakumoChen** [comment]
> > How many times in my life am I going to get to see a closed PR with this title?
> 
> If this gets closed I will also remove CEs belt its only fair

Unlike the CMO the CE needs his belt to make sure the SM stays on fire before he inevitably dies in that spot behind the AI sat in the wall next to where the SMES is

**Comment by SethLafuente** [comment]
> > > How many times in my life am I going to get to see a closed PR with this title?
> > 
> > 
> > If this gets closed I will also remove CEs belt its only fair
> 
> Unlike the CMO the CE needs his belt to make sure the SM stays on fire before he inevitably dies in that spot behind the AI sat in the wall next to where the SMES is

This isnt remotely true setting up the SM without his tools isnt any harder

**Comment by JohnFulpWillard** [comment]
> > The CMO already has a unique belt-slot item, which is a portable defibrilator.
> 
> 
> 
> its not unique, it can be printed from research afaik

So can advanced medical and engineering tools.

**Comment by SethLafuente** [comment]
> > > The CMO already has a unique belt-slot item, which is a portable defibrilator.
> > 
> > 
> > its not unique, it can be printed from research afaik
> 
> So can advanced medical and engineering tools.

The point is portable defibrillator dosent have a special zone to be put in its just some item some advance item someone gave CMO to let them do their job better than their underlings because thats what all heads have from the HoS to the CE this isnt any different than giving the HoS a riot shield or the CE having the jaws of life

Also the Belt looks much better with CMOs fit more clean current medical belts do not go with CMOs drip

**Comment by Jolly-66** [comment]
> > > The CMO already has a unique belt-slot item, which is a portable defibrilator.
> > 
> > 
> > its not unique, it can be printed from research afaik
> 
> So can advanced medical and engineering tools.

I thought the CEs tools were "slightly better" than advanced. That's what I've heard in the past.

**Comment by SethLafuente** [comment]
> 

I shouldve just let the duplicates be ill rever that someone can fix it later 
image
image

I mean this they are in main code not my fault

**Comment by SethLafuente** [comment]
> > > > The CMO already has a unique belt-slot item, which is a portable defibrilator.
> > > 
> > > 
> > > its not unique, it can be printed from research afaik
> > 
> > 
> > So can advanced medical and engineering tools.
> 
> I thought the CEs tools were "slightly better" than advanced. That's what I've heard in the past.

well their 2 tools in one and their significantly faster

**Comment by JohnFulpWillard** [comment]
> We all know it would be an objectively bad change to remove the advance tools from CE and the same logic applies to CMO but if your logic is that the CMO shouldnt have these tools the same logic applies to CE 
> 
> 
> 
> So tell me would you like the CEs tools also being removed?

This isn't a PR removing CE's tools so I am not here to argue for its removal. I just believe that objectively the CE is the worst head of staff. QM/HoP/HoS/RD gets their authority over players through their unique position and/or ability to manage their departments. The CE instead is just given a bunch of tools and expected to not use them, and I think CMO is currently on the side of being a good head of staff (they can do their job just as well as an MD if they need to), and don't want to go against that goal.

**Comment by Serxule** [comment]
> > > The CMO already has a unique belt-slot item, which is a portable defibrilator.
> > 
> > 
> > its not unique, it can be printed from research afaik
> 
> So can advanced medical and engineering tools.

the belt is the unique item if you arent paying attention

**Comment by SethLafuente** [comment]
> > We all know it would be an objectively bad change to remove the advance tools from CE and the same logic applies to CMO but if your logic is that the CMO shouldnt have these tools the same logic applies to CE
> > So tell me would you like the CEs tools also being removed?
> 
> This isn't a PR removing CE's tools so I am not here to argue for its removal. I just believe that objectively the CE is the worst head of staff. QM/HoP/HoS/RD gets their authority over players through their unique position and/or ability to manage their departments. The CE instead is just given a bunch of tools and expected to not use them, and I think CMO is currently on the side of being a good head of staff (they can do their job just as well as an MD if they need to), and don't want to go against that goal.

How would giving the CMO more tools make them a less effective head

Also this is more of a player issue I do play CE and I do use the tools to keep all the stations on nominal the reason CEs dont do shit is because engineers dont do their job this isnt code related whatsoever 

medics job is to keep people alive so their more attentive to their job since other players relly on them it should be the same with engineers since without them the station is fucked but players dont have enough braincells to realize how important their job is,

What I mean is CE isnt the worst head and CMO isnt always good there are constant rounds where newbies pick CMOs and they manage medical horribly unable to even heal a persons bloodloss and leaving them in stasis more more than 30 minutes which like CE not using their tools to do their job is a player issue

**Comment by GuillaumePrata** [comment]
Players should opt into a role for their gameplay, not their gamer gear.
Most heads of staff suffer from the issue of people playing it because it is "Insert basic department job here" with better gear.

CE is definitely the worst offender on this issue, the HoP is the outliner since they are the only head with an actual job and don't even have gamer gear.

Using the CE as reference for other heads is a mistake, we should all use the HoP instead and give Heads of Staff their own unique management job.

**Comment by SethLafuente** [comment]
> Players should opt into a role for their gameplay, not their gamer gear. Most heads of staff suffer from the issue of people playing it because it is "Insert basic department job here" with better gear.
> 
> CE is definitely the worst offender on this issue, the HoP is the outliner since they are the only head with an actual job and don't even have gamer gear.
> 
> Using the CE as reference for other heads is a mistake, we should all use the HoP instead and give Heads of Staff their own unique management job.

You are missing the point this change wont make people opt into being CMO for the loot it will make already CMO players be able to do their job better every tiem I sign up there isnt an issue of people opting into CE for CEs gear thats a made up probllem

Im simply leveling the field between CE and CMO

**Comment by SethLafuente** [comment]
> Players should opt into a role for their gameplay, not their gamer gear. Most heads of staff suffer from the issue of people playing it because it is "Insert basic department job here" with better gear.
> 
> CE is definitely the worst offender on this issue, the HoP is the outliner since they are the only head with an actual job and don't even have gamer gear.
> 
> Using the CE as reference for other heads is a mistake, we should all use the HoP instead and give Heads of Staff their own unique management job.

HoPs job is bureaucracy and they rule a list of jobs mostly composed of RP and they are also RP they dont need specially tools becuase there are no tools to do what they are meant to do

meanwhile CMO and CE have actual jobs and they need tools to do their job

CE and CMO are the best parallels to each other HoP is a parallel to QM at best

**Comment by GuillaumePrata** [comment]
> You are missing the point this change 

I'm not, I just fundamentaly disagree with your goal as being good for the game.

The more gamer gear a head of staff has, the more people will play it for their gear and not the core job, even more because most heads of staff do not have a job, just make-believe authority that is not even respected that often.

> meanwhile CMO and CE have actual jobs and they need tools to do their job

They do not have a job and that is the core issue, they just play as their underlings, but with more gamer gear.

**Comment by SethLafuente** [comment]
> > You are missing the point this change
> 
> I'm not, I just fundamentaly disagree with your goal as being good for the game.
> 
> The more gamer gear a head of staff has, the more people will play it for their gear and not the core job, even more because most heads of staff do not have a job, just make-believe authority that is not even respected that often.
> 
> > meanwhile CMO and CE have actual jobs and they need tools to do their job
> 
> They do not have a job and that is the core issue, they just play as their underlings, but with more gamer gear.

Ive played CE and CMO a lot and I have seen CMO and CEs play and they dont also you can say the same thing about RD and HoS this is a player by player cases doing this wont change how players think

**Comment by YakumoChen** [comment]
HoP belt filled with pre-made forms and that stamp machine from Papers, Please

**Comment by SethLafuente** [comment]
> HoP belt filled with pre-made forms and that stamp machine from Papers, Please

every time I do that people call me an asshole or try to kill me and honestly its kind of a waste of time although I still do it becuase I enjoy writting paper work

**Comment by SethLafuente** [comment]
> 

what does this mean why is there a moth CMO

**Comment by GuillaumePrata** [comment]
> you can say the same thing about RD and HoS

The RD has their little job that is managing Silicons and mainly the AI.
The HoS is just a sec officer ++.

>  this is a player by player cases doing this wont change how players think

What we add to the game change how players act.
If we give more gamer gear to a head of staff, people will play for the gear and not the job content (there is none).

**Comment by SethLafuente** [comment]
> > you can say the same thing about RD and HoS
> 
> The RD has their little job that is managing Silicons and mainly the AI. The HoS is just a sec officer ++.
> 
> > this is a player by player cases doing this wont change how players think
> 
> What we add to the game change how players act. If we give more gamer gear to a head of staff, people will play for the gear and not the job content (there is none).

You are identifying tools to heal others as gamer gear people play medical to help others and heal them not for gamer gear no one will play CMO more because of their gear as currently nobody plays CE more because of their gear

**Comment by SethLafuente** [comment]
> > you can say the same thing about RD and HoS
> 
> The RD has their little job that is managing Silicons and mainly the AI. The HoS is just a sec officer ++.
> 
> > this is a player by player cases doing this wont change how players think
> 
> What we add to the game change how players act. If we give more gamer gear to a head of staff, people will play for the gear and not the job content (there is none).

Anyways we are just going on circles I will open another PR that will remove the CEs toolbelt since according to two maintainers this will somehow improve the CE as a head role I dont believe it will but I will trust your word

**Comment by YakumoChen** [comment]
add the HoP belt first

**Comment by SethLafuente** [comment]
> add the HoP belt first

for what?

unless we get specially energy based bureaucratic gear I wont

**Comment by YakumoChen** [comment]
I want to support the Papers, Please playstyle because it makes gamers babyrage

**Comment by SethLafuente** [comment]
> I want to support the Papers, Please playstyle because it makes gamers babyrage

I dont do it to annoy people I do ti to document it on a folder and keep track of it I will have a folder full of ss13 useless paperwork I can proudly show around

**Comment by moocowswag** [comment]
Heads of staff are more like organizers that fill in unfinished jobs of a department and due to their authority within a department they can force cooperation within the same department to finish a specific task like cure a virus and get vaccines rolling out or reorientating the department to work towards actively countering a threat to the station (such as frontline healing to deal with blob)

CMO just being a better medical doctor encourages them to just be that. (Thats not to say they arnt actually just a better chemist due to their instant injection hypospray)

**Comment by Mothblocks** [comment]
> @Mothblocks you had interest in the last PR, dunno if you have any thoughts on it this time around too

It's more that I wasn't really rooting against it but even in the last PR I deferred to you because I don't particularly care about this

**Comment by Mothblocks** [comment]
Closing because John doesn't want it

**Comment by SimplySmiley123** [comment]
> Also, the CMO has a bit of a problem with being just MD+ and not actually doing leadership stuff within medbay. This change would put even more pressure on them to do the job of a MD and not the leadership and organization job of it. I don't really like this change tbh.

I mean... CE has same issue though, they are jsut an Engineer+ with a fireproof and rad proof suit and better magboots to boot to be the one to do SM isntead of Engineers.
HoS is pretty much treated as Officer+ with his laser gun, hell even Captain is often treated as Officer+ with his infinite ammo lasergun.

**Pull request closed without merging**
