### PR TITLE
Adds Pax to the Peacekeeper Borg's "Peace Hypospray"

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
add: The Peacekeeper Borg's "Peace Hypospray" now includes the "Pax" reagent, which prevents the subject from carrying out many forms of direct harm.
/:cl:

I don't even like PK borgs but thematically speaking this just made too much sense.

### CODE REVIEW

**Comment by Repukan** [comment]
I expect to see their death rate to skyrocket knowing Borg players.

**Comment by factoryman942** [comment]
100% going to pax sec officers chasing people
always

**Comment by Robustin** [comment]
@factoryman942 

That should be fine. The Peacekeeper has special flavor text about how they're 100% about harm-prevention and 0% about space law. Pax is basically "harm prevention - the chem" but it won't prevent an officer from conducting a standard stun + cuff + drag.

**Review by Cyberboss — APPROVED** [review]

**Comment by BeeSting12** [comment]
what does pax do

**Comment by Robustin** [comment]
It prevents direct harm like harm intent or hitting someone with an object that has FORCE.

You can still fire weapons, choke people out, cuff them, etc.

**Comment by BeeSting12** [comment]
well i kill any nonmed borg that pricks me so this changes nothing tbh

**Comment by XDTM** [comment]
You cannot fire guns under Pax, nor throw items with force. Also no grabs beyond passive. Basically cuts off most direct means of harm.

Good luck killing what you can't hit i guess, although you can flash em

**Comment by ExcessiveUseOfCobblestone** [comment]
fear the flash

**Comment by kevinz000** [comment]
ok uhh let me just say this: this is hilarious, and this is actually an effective way of peacekeeping
although a one click method of neutering someone who doesn't have a flash is just way, way, way, way too powerful.
:-1: sorry.

**Comment by XDTM** [comment]
What if it was a robotics upgrade

**Comment by factoryman942** [comment]
also
this would allow paxing someone then beating them over the head with an extinguisher
make it apply a pax-like effect to the borg too or something
anti-harm beam!

**Comment by Robustin** [comment]
Could work as a robo upgrade I suppose, ive barely touched cyborg code before so im not even  sure how to handle that, plus there's the matter of adding the techweb design and exosuit schematic.

I wasn't aware it stopped gunfire, that honestly seems like an oversight since you could check if it was a projectile weapon and then confirm that the projectile had the nodamage var so you could still use tasers and ion guns. 

On the other hand the effect is limited and the borg only gets 30, which can only be regenerated at the recharging. Plus peace hypo and literally "Peace in Another Language - The Reagent" seem meant for each other.

**Comment by XDTM** [comment]
There is a very similar medborg upgrade you could copy for this. Also yeah, name and purpose both fit but it's strong for roundstart

**Comment by kevinz000** [comment]
pax is one of the most op chemicals you can inject someone and beat them to death and htey won't be able to retaliate.

**Comment by XDTM** [comment]
I mean there's neurotoxin too, and disarming is still possible

**Comment by coiax** [comment]
What if you gave PK borgs a LIMITED SUPPLY of Pax. And they'd need to get a "refill cartridge" from Robotics when they ran out?

**Comment by Robustin** [comment]
Still not sure what your argument is Kev, I hate these sort of "theoretical in a sterile environment" balance scenarios.

A peacekeeper borg has a fire extinguisher as their only "harmful" weapon. So they have to first inject you, then get out an extinguisher, then chase you around as they slowly try to melee you to death before the Pax finishes metabolizing? All the while a flash will still work, as will intervention from any crew who will inevitably be attracted to a borg trying to slowly beat someone to death. 

I'll look at the medborg upgrade and see if I can't add this as an upgrade too.

**Comment by Incomptinence** [comment]
Beating a borg back in melee isn't going to save you kevinz they have a higher health pool and don't suffer random knock outs and I don't think pax will stop you shooting or flashing it anways.

**Comment by davethwave** [comment]
If you can't find out how to add it via robotics upgrade perhaps make it a emag feature for it?

**Pull request merged**
