### PR TITLE
Improve player medbot

### PR DESCRIPTION
**Pull request by octareenroon91**
:cl:
rscadd: Player-controlled medibots can examine a patient to know what chems are in the patient's body.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Test to make sure the MedHUD works for pAI users, and that they can speak on medical channel.

**Comment by octareenroon91** [comment]
That sounds like playtesting for the pAI medbot PR. Not that I'm unwilling to, it just seems like a scope issue.

**Comment by RemieRichards** [comment]
@octareenroon91 that PR was merged, so it's on your head as the person adding new functionality to test that it works with (now) existing functionality.

**Comment by octareenroon91** [comment]
Fair enough.

**Comment by octareenroon91** [comment]
>radio

Works.

>medical HUD

Not working with a pAI, nor can I see how my change would do it. Any HUD the pAI had downloaded also becomes disabled.

**Pull request merged**
