### PR TITLE
Add configuration consistency tests

### PR DESCRIPTION
**Pull request by Cyberboss**
Checks for missing and non-existant config entries.

Tests good.

### CODE REVIEW

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
doesn't pass tests

**Comment by SpaceManiac** [comment]
nobody is going to merge a PR that adds tests that don't pass

**Comment by Cyberboss** [comment]
Debugging is a pain

**Comment by Cyberboss** [comment]
Oh wait, I'm getting screwed over by how we destroy the config on travis

```
Loading config file config.txt...
{"sql_enabled":null,"address":"127.0.0.1","port":"3306","feedback_database":"tg_travis","feedback_tableprefix":null,"feedback_login":"root","feedback_password":null,"lavaland_budget":"0","space_budget":"0"}
```

**Comment by Cyberboss** [comment]
Pinging this PR because I accidentally deleted it from my notifications

**Comment by vuonojenmustaturska** [comment]
image

**Comment by AffectedArc07** [comment]
image

**Comment by Tennessee116** [comment]
Coming from the discord. You asked for this, Cyber. Initiating grug scan...

Grug no understand. 10/10

**Comment by Cyprex** [comment]
Hello there

**Comment by Cyberboss** [comment]
bumping for my inbox

**Comment by alexkar598** [comment]
.

**Comment by AffectedArc07** [comment]
Sorry what github? 
image

**Comment by Jared-Fogle** [comment]
it still doesnt pass

**Comment by Cyberboss** [comment]
Working on it.

**Pull request closed without merging**
