### PR TITLE
Removes "floor-length" hairstyles from the game.

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Removes the floor-length bedhead, and floor-length braid from the game.
## Why It's Good For The Game

they look dumb. and besides, hair that long on a fucking space ship seems like a horrendously bad idea.
## Changelog
:cl:
del: Pending class-action lawsuits from the government of the SSC, regarding hair getting caught in airlocks. Nantorasen has begun acting stricter grooming policies on their employees. Please abide by these ordinances.
/:cl:

### CODE REVIEW

**Comment by castawaynont** [comment]
SOVL REMOVAL

**Comment by san7890** [comment]
I think on a station where members are allowed to have tails (lizard, felinid) and wings (moths)- hair length is not the largest of concerns

**Comment by WinterDarkraven** [comment]
Remove being bald.

**Comment by UntoldTactics** [comment]
What's Nantorasen?

**Comment by gonenoculer5** [comment]
Rent free.

**Comment by JohnFulpWillard** [comment]
I don't agree with your reasoning and san does bring up a good counterargument anyways. Our goal isn't realism in the first place

**Comment by calliophis-maculiceps** [comment]
> I think on a station where members are allowed to have tails (lizard, felinid) and wings (moths)- hair length is not the largest of concerns

😬not a good look buddy

**Comment by githubuser4141** [comment]
> I think on a station where members are allowed to have tails (lizard, felinid) and wings (moths)- hair length is not the largest of concerns

Except those are (by lore) biological traits, not sytlistic choice so it's really not the same? It'd obviously be a lot more immoral and unpopular to say "you must mutilate part of your body to get a job" then "you can't wear your hair in this style on-duty".

**Pull request closed without merging**
