### PR TITLE
Replaces umbras with revenants

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Umbras have been removed.
rscadd: Revenants have been readded, though they are now vulnerable to salt piles.
/:cl:

Merge token; #18997

### CODE REVIEW

**Comment by Xhuis** [comment]
Probably for the best.

**Comment by Repukan** [comment]
Fuck Umbras

**Comment by Core0verload** [comment]
No. Grief ghosts suck.

**Comment by ChangelingRain** [comment]
Umbras are literally worse. If you thought a validhunting revenant was bad imagine a basically invulnerable antag with a foolproof antag detection method that also stuns, and a method of communicating with people.

That's literally it.

**Comment by Xhuis** [comment]
I intended to do more with umbras, but initial feedback has been so overwhelmingly negative that I think revenants should be restored.

**Comment by GunHog** [comment]
Kor asked me to do this, but I am lazy and took too long XD

**Comment by ShadowDeath6** [comment]
bring back mind spike revenant and see if people whine about the current one being op

**Comment by coiax** [comment]
Kor told me that umbras were useless and pointless, and we're removing them for fucking lightning-bolt-from-lightbulbs griefghosts?

**Comment by AlexCrimson** [comment]
Why is this happening? I get that Umbra were useless and all, but people hated Revenants just as much. The whole antag has been poorly implemented, we shouldnt just add the thing back in.

The Mind Spike version was the best one, but it was way too strong and had virtually no counter. It needs to not be some no-clip invisible antag. The entire thing needs to be redesigned.

Someone needs to go play Ghost Master and implement something like that. Rather than letting the ghost zip around the station, force it bind itself to rooms to use its abilities, or moving through walls takes resources.

**Comment by Zilenan91** [comment]
I liked revenants

**Comment by Niknakflak** [comment]
me too

**Comment by Bawhoppen** [comment]
me and niknak agree on something? what is this black sorcery

**Comment by Bawhoppen** [comment]
AND ZILENAN TOO WAIT A FUCKING MINUTEI DONT SEE ANY PIGS FLYING

**Pull request merged**
