### PR TITLE
Many typo fixes

### LINKED ISSUE #6582: Mech and Area renames can result in "mproper <name>"
Kingofcosmos reported that an area was named "mproper Main Homie office" on the alerts console, Cedarbridge mentioned that this also happens with mech names.

### LINKED ISSUE #6694: Grammar mistake in crate shock message
>Character Name was shocked by the the engineering gear crate !

The is repeated and there's a space between the exclamation mark and the end of the sentence.

### LINKED ISSUE #6704: Spacing mistake in mulebot crate drop-off message
>[Supply] Mulebot (#2) beeps, "Destination [destination] reached. Unloading the virus crate ."

There's a space between the name of the crate and the full stop at the end of the sentence.

### PR DESCRIPTION
**Pull request by phil235**
Fixes typos in crate names from the cargo shuttle.
Fixes "mproper" in area and mech names when renaming them. (Removing the initial name appearing in the input window that was causing the typo when it was accepted as new name)
Fixes typo in shock message.

Fixes #6582
Fixes #6704
Fixes #6694

### CODE REVIEW

**Comment by Boggart** [comment]
Also fixes #6414.

**Comment by tkdrg** [comment]
Supply shuttle edit conflicts with the MC rewrite. Putting this on hold until carn's done.

**Comment by psykzz** [comment]
So i did this https://github.com/tgstation/-tg-station/pull/6774 without noticing to fix the RCD. Should i cancel my PR or would you mind removing its from yours?

**Comment by phil235** [comment]
@psykzz If your PR is ready to go before this one then go ahead. I'll update my PR accordingly.

**Pull request merged**
