### PR TITLE
Faster disposals construction

### PR DESCRIPTION
**Pull request by CPTANT**
Buildings disposals is fun and is something that should be promoted, but currently building a pipe of any length takes a rather serious amount of time. This PR greatly reduces the delays on the RPD laying the pipe and the time needed to weld the pipe in place. 

Disposals delays were re-added to prevent spam of dense objects such as bins to block movement. Since unanchored disposals objects were made not dense ages ago the delays can be  removed.

:cl: 

tweak:  Building disposal pipes is now faster

/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
Wait why do my old commits, show up on this PR....

**Comment by XDTM** [comment]
Did you branch off of another branch?

**Comment by CPTANT** [comment]
No, but for some reason my fork seems 4 commits ahead of tgstation:master despite updating and having no file differences.

My guess is I fucked something up with my master branch in 2016

**Comment by optimumtact** [comment]
sur elooks like it

**Comment by CPTANT** [comment]
Ok ill close this and try to clean it up.

How do I get a clean master branch again?

**Comment by optimumtact** [comment]
git fetch upstream
    git checkout master
    git reset --hard upstream/master
    git push -u origin master

**Comment by CPTANT** [comment]
Yes, had to push -f but it worked.

**Pull request closed without merging**
