### PR TITLE
Da great meat resprite PR.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR resprites many existing meat sprites and adds a few new sprites for meats who previously used generic sprites.

I've added meat product steak, lizard steak and synthsteak types to facilitate giving them unique sprites.

meatcomp_pr

The rotten meat is animated.
meat_rotten_64

## Why It's Good For The Game

Many of the old sprites are pretty bad and sad.

## Changelog
:cl:
imageadd: Many meats have had their sprites replaced.
add: lizard meat, meat product & synthmeat have their own steaks now.
/:cl:

### CODE REVIEW

**Comment by uomo91** [comment]
This is awesome!
Any chance you can do fish/carp too?

**Comment by LemonInTheDark** [comment]
It's been so long, and they're so good

**Review by Twaticus — APPROVED** [review]
they look lovely

**Comment by BootlegBow** [comment]
we need this

**Comment by Qustinnus** [comment]
Awesome stuff as always. Still secretly think you should be art lead

**Comment by itseasytosee** [comment]
Holy shit what a godsend.

**Comment by Qustinnus** [comment]
especially new meatwheat is great, old sprite looks like a fuzzy blood clot atm lmao

**Pull request merged**
