### PR TITLE
Prevent creampie overlays from stacking.

### PR DESCRIPTION
**Pull request by Mercenaryblue**
[Changelogs]: 
:cl:
balance: it should be far easier to clean out your face from multiple cream pies.
/:cl:

[why]: 1.  Because your face can only hold so much cream.
2. Because the pie cannon made stacking that overlay far easier.
3. And it takes forever to clean it all one at a time.

This PR will make it so cream pies only applies the overlay once per person, until it is cleansed.
As a result, you only need to wash your face once to remove the cream.
It doesn't change anything else but the washing process, in the end.

### CODE REVIEW

**Comment by XDTM** [comment]
making it a component would avoid adding another single-use var to mobs

**Comment by Mercenaryblue** [comment]
I've tried checking for the overlay first. I think that would make more sense, honestly.

**Review by ghost — APPROVED** [review]
yersss

**Comment by Supermichael777** [comment]
take of all headgear and shower

**Comment by Noahnoah55** [comment]
Implement more sprites for multiple pies on one face, eventually turning you into a pie.

**Comment by juanototo2** [comment]
Stop nerfing clowns you fuck

**Comment by Mercenaryblue** [comment]
> stop fixing bugs.
I do it because I love the clown.

**Pull request merged**
