### PR TITLE
Marginal washing machine improvements

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Activated by altclick instead of an object verb. Removes unused vars. I didn't want to go any further into this nonsense though.

:cl: Kor
rscadd: Washing machines are activated via alt+click rather than a right click verb.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Add the altclick-activate to examine.

**Comment by xxalpha** [comment]
Is there more to the washing machine that I am not aware of? Empty -> Do nothing, Clothes -> Close and wash, Finished washing -> drop clothes. Don't need to use AltClick when the basic click suffices.

**Comment by Supermichael777** [comment]
clicking just opens it when its full you turn it on with an object verb(this is bad).

**Comment by Shadowlight213** [comment]
But washing machine code is our most sacred of shitcode...

**Comment by tkdrg** [comment]
#13135 reminder

**Comment by tkdrg** [comment]
@KorPhaeron changelog

**Comment by KorPhaeron** [comment]
@tkdrg 

Okay

**Pull request merged**
