### PR TITLE
Makes it so you can't puke up ONE THOUSAND UNITS OF KETCHUP in one go.

### LINKED ISSUE #46236: Vomiting purges all food reagents in you reagrdless of volume
Tested only on a local compile but server revision should be current.

Add any amount of /datum/reagent/consumable to a mob, vomit and it's ALL gone. 

This is not true of other reagent types.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
fix: You no longer purge your entire system of food in a single puke
/:cl:

this could be considered a tweak but... eeeehhh this is stoopid and doesn't sound right.

CLOSES:https://github.com/tgstation/tgstation/issues/46236

### CODE REVIEW

**Comment by adamkad1** [comment]
add a trait that lets you vomit out everythig you ate

**Comment by PKPenguin321** [comment]
Might be an interesting mutation...

**Comment by ExcessiveUseOfCobblestone** [comment]
ULTRA PUKE

**Comment by Ty-the-Smonk** [comment]
All of this to nerf felenids fucking based

**Comment by GuyonBroadway** [comment]
I'd consider adding some kind of puke based mutation later but for now lets just fix this bug.

**Comment by adamkad1** [comment]
> I'd consider adding some kind of puke based mutation later but for now lets just fix this bug.

goons got that

**Comment by wesoda25** [comment]
Feature. Vomiting 1000 units of ketchup is intentional.

**Comment by GuyonBroadway** [comment]
@wesoda25 I could make a joke virus or abductor gland that makes you vomit up ever increasing amounts of ketchup. But that would have to be for another time.

**Comment by wesoda25** [comment]
lol I was memeing anyways but that’d be funny

**Comment by AnturK** [comment]
Could probably do with a define.

**Review by SpaceManiac — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
If a maintainer requests I'll make this a define or variable when I get home from work tomorrow.

And a variable if only so I can make a ketchup puking organ or something.

**Comment by ExcessiveUseOfCobblestone** [comment]
sounds more like a proc arg so it's malleable.

I can see instances like chems that induce puking would want to have more efficacy in their pukes than the generic "me sick" puke (i can't believe i just wrote that)

**Pull request merged**
