### PR TITLE
Ratvarian Spears have new, better inhands

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
imageadd: Ratvarian Spears have new inhand icons.
/:cl:

Old:
old
New:
new

It's not a dinky stabby thing it's a big swingy slashy thing. Fact.

### CODE REVIEW

**Comment by RemieRichards** [comment]
looks like a shovel

**Comment by FantasticFwoosh** [comment]
Did the same summoning spell of lizard speak drama revive you too @RemieRichards?

**Comment by PKPenguin321** [comment]
It does look like a shovel though

**Comment by RemieRichards** [comment]
@FantasticFwoosh no I was just on break, was going for a month but 3 weeks seems good enough (coming back proper from tomorrow/the weekend)

**Comment by GunHog** [comment]
The Chinese Military has proven that shovels are viable combat tools, as well as having many other uses! https://www.youtube.com/watch?v=6ryyAenmzHM

**Comment by KorPhaeron** [comment]
Common file for conflicts

**Pull request merged**
