### PR TITLE
Add passive vent. 

### PR DESCRIPTION
**Pull request by TheChosenEvilOne**
## About The Pull Request
Adds a passive vent, think of it as an open pipe to the turf atmosphere.
The icon is just a vent pump/unary vent without the fan.

## Why It's Good For The Game
Right now there is no way to input or output gas to turf without use of power, so you can't for example make SM setups that require no to very little power.

## Changelog
:cl:
add: added passive vent to the arsenal of atmospheric devices.
/:cl:

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
> 
> 
> Nice, the only way to do this before afaik was to place a connector and wrench an open canister to it

that or portable scrubber/pump but those can't be in high heat.

**Comment by Shirbu** [comment]
I am happy. this good PR. Big brain.

**Comment by nicbn** [comment]
Will it take air in if the external pressure is greater than internal pressure?

**Comment by TheChosenEvilOne** [comment]
> 
> 
> Will it take air in if the external pressure is greater than internal pressure?

Yes, it is an open pipe to atmosphere basically.

**Comment by Shirbu** [comment]
Which should have existed in the code a long time ago if atoms weren’t the weirdest and most awkward thing in tg code.

**Pull request merged**
