### PR TITLE
Removes cursed code, SOMETHING SOMETHING SPIRITS OF THE COMPUTER

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request
wHY
## Why It's Good For The Game
It must be purged

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
you will never catch me alive

**Comment by GoldenAlpharex** [comment]
`attack_basic_mob` my beloved..........

**Comment by interestingusernam3** [comment]
e

**Comment by Time-Green** [comment]
return the code
or suffer my curse

**Pull request merged**
