### PR TITLE
[GITHUB WHOOPS] mirroring the wrong direction

### PR DESCRIPTION
**Pull request by CliffracerX**
```
> Tried to mirror TGStation PR to my server.
> Mirrored my server to TGStation instead.
> dies of shame
```
I'm so sorry to everyone who just got pinged for this.

### CODE REVIEW

**Comment by CliffracerX** [comment]
Hoo boy, github.

**Comment by JohnFulpWillard** [comment]
thequestiondialogue

**Comment by CliffracerX** [comment]
> thequestiondialogue

My degree is in insomnia
This is why you don't GitHub at 3:00 AM half-asleep

**Comment by LemonInTheDark** [comment]
Happens once a month brother you get numb to it given time

**Pull request closed without merging**
