### PR TITLE
Diagnostic HUD eyes

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
Adds diagnostic hud eyes

## Why It's Good For The Game

Gives another HUD eye to complete the collection

## Changelog
:cl:
add: Diagnostic HUD eyes, now printable at your local Medical Lathe/Exosuit Fabricator!
/:cl:

### CODE REVIEW

**Comment by Rowelll** [comment]
why not, I like this change

**Comment by Tlaltecuhtli** [comment]
hos needs their glasses anyway to be flash proof and rd already has loads of good items

**Comment by MrFluffster** [comment]
You can just put the item on the same tile as the locker in the map editor and it will be inside of it.

**Comment by Fikou** [comment]
> You can just put the item on the same tile as the locker in the map editor and it will be inside of it.

ye but i look at dream maker and all the lockers with specific non randomized stuff are empty so theres probably some file that defines the contents of those lockers across all maps

**Comment by Tlaltecuhtli** [comment]
head closets are here https://github.com/tgstation/tgstation/tree/617880080ce06bcfb28a305f017453a2786adcce/code/game/objects/structures/crates_lockers/closets/secure

**Comment by Fikou** [comment]
> head closets are here https://github.com/tgstation/tgstation/tree/617880080ce06bcfb28a305f017453a2786adcce/code/game/objects/structures/crates_lockers/closets/secure

yes i said i found it

**Comment by Tlaltecuhtli** [comment]
well i didnt see your edit

**Comment by Fikou** [comment]
wait can medlathe/exosuit fabricator print medhud eyes if yes i should probably edit that too but i cant find where the damn augment designs are

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/2e227d11ee7b375bba8abb023e4aa8fc89d4f23a/code/modules/research/designs/medical_designs.dm

edit the techweb node to include the design

**Comment by Fikou** [comment]
ok thank you for help this should be workin correctly now

**Comment by ExcessiveUseOfCobblestone** [comment]
> put cool stuff in research
> people just add it to roundstart

rip

**Comment by Fikou** [comment]
> > put cool stuff in research
> > people just add it to roundstart
> 
> rip

its for CONSISTANCY with the cmos autosurgeon

**Comment by ExcessiveUseOfCobblestone** [comment]
> put cool stuff in research
>> give it to 1 job because just 1 instance won't hurt right?
>>> used as justification for adding it to literally every other job

if you give a man an inch...

**Comment by Fikou** [comment]
lies and slander i havent given speshal eyes to ce or hop

**Comment by ExcessiveUseOfCobblestone** [comment]
sorry i fixed it lol

**Comment by Fikou** [comment]
ok thank u

**Comment by necromanceranne** [comment]
Meson eyes for the CE

The HoP gets uh...uh...laser stamping eye beams?

**Comment by dr-bee** [comment]
Its a good addition, but adding it roundstart is lame. 

It does open up the ability to add diagnostic sunglasses if someone codes it however.

**Comment by necromanceranne** [comment]
There is already diagnostic sunglasses.

**Comment by ATH1909** [comment]
> Meson eyes for the CE  

This, but unironically.

**Comment by Fikou** [comment]
> > Meson eyes for the CE
> 
> This, but unironically.

i actually was planning this but it depends on if this pr gets merged

**Comment by Shapsy** [comment]
proving cobby right

**Comment by Fikou** [comment]
> proving cobby right

shut up :(

**Comment by PKPenguin321** [comment]
As the guy that added autosurgeons,

**STOP GIVING THEM TO THE CREW THE CMO IS THE SOLE EXCEPTION BECAUSE HE IS THE HEAD OF THE DEPARTMENT THAT ACTUALLY DOES SURGERY**

cooltext323109292677828

image

cooltext323109508747003

**Comment by Fikou** [comment]
> As the guy that added autosurgeons,
> 
> **STOP GIVING THEM TO THE CREW THE CMO IS THE SOLE EXCEPTION BECAUSE HE IS THE HEAD OF THE DEPARTMENT THAT ACTUALLY DOES SURGERY**

OK i guess after that they will be REMOVED
sad!

**Comment by ExcessiveUseOfCobblestone** [comment]
verified lol

**Pull request merged**
