### PR TITLE
Less spam from stabilized yellow extracts

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes the chat log message from yellow stabilized extracts that normally writes every pulse.

Balloon alerts and examine text are left intact.

## Why It's Good For The Game

image

While this does reduce the visibility of the effect, there is still a balloon alert for when a player loses it, and a line in examine text while it is active. I don't think knowing the exact time of every pulse is significant information and so it would be better to not have constant spam when using this item.

(But if I'm wrong and people like it more than they're annoyed by it, I'll close this)

## Changelog

:cl:
qol: Stabilized yellow slime extracts no longer spam a message every charge pulse (but examining characters will still show that it's active).
/:cl:

### CODE REVIEW

**Comment by mikederkan** [comment]
Why not convert it to a balloon alert?

**Comment by YehnBeep** [comment]
> Why not convert it to a balloon alert?

I thought about it but - do you really want to get them _constantly_, every few seconds? Less clutter than spamming the log sure - but to me it still seems a nuisance that doesn't really add value.

That said it's an option if it's desired.

**Comment by nukularpower** [comment]
great change

**Comment by trerri** [comment]
an alternative could be a little noise that plays and isnt too invasive

**Pull request merged**
