### PR TITLE
Recolors the computer circuit boards and machine circuit boards into department-based colors.

### PR DESCRIPTION
**Pull request by Nickkoranda**
## About The Pull Request

image

image
Also reorganizes the computer_circuits.dm and machine_circuitboard.dm based on an alphabetical order divided by department.
Sprites by @Onule 
## Why It's Good For The Game

Allows you to distinguish a circuit board almost much more quickly, also adds flavor to boards. Improves the readability of the computer_circuits.dm and machine_circuitboard.dm 
In the most minor way possible it helps people with colorblindness. 
## Changelog
:cl: blargety, Onule
add: Added departmental sprites for circuit boards commonly used within a department. For example, a SMES will have a orange base.
imageadd: Adds 8 new icons for circuit boards, based on department colors.
refactor: Reorganizes computer_circuits.dm and machine_circuitboard.dm based on an alphabetical order divided by department.
/:cl:

### CODE REVIEW

**Comment by Ty-the-Smonk** [comment]
Can't wait for assistants with red boards in their backpacks to be instantly lynched

**Comment by HomocidlePancakes** [comment]
Ugly, but makes telling apart circuit boards easier. Good

**Comment by daklj** [comment]
you are ugly

**Comment by zxaber** [comment]
>add: Added departmental sprites for sprites commonly used within a department. For example, a SMES will have a orange base.

>sprites for sprites

Anyway, good change.

**Comment by Nickkoranda** [comment]
> ## About The Pull Request
> image
> 
> image
> Also reorganizes the computer_circuits.dm and machine_circuitboard.dm based on an alphabetical order divided by department.
> Sprites by @Onule
> 
> ## Why It's Good For The Game
> Allows you to distinguish a circuit board almost much more quickly, also adds flavor to boards. Improves the readability of the computer_circuits.dm and machine_circuitboard.dm
> In the most minor way possible it helps people with colorblindness.
> 
> ## Changelog
>  blargety, Onule
> add: Added departmental sprites for circuit boards commonly used within a department. For example, a SMES will have a orange base.
> imageadd: Adds 8 new icons for circuit boards, based on department colors.
> refactor: Reorganizes computer_circuits.dm and machine_circuitboard.dm based on an alphabetical order divided by department.
> /

**Comment by Nickkoranda** [comment]
> > add: Added departmental sprites for sprites commonly used within a department. For example, a SMES will have a orange base.
> 
> > sprites for sprites
> 
> Anyway, good change.

Fix'd

**Comment by PKPenguin321** [comment]
Would be cool if you could repaint circuit boards to disguise them as other boards

**Comment by ATH1909** [comment]
*an SMES

**Comment by Nickkoranda** [comment]
> Would be cool if you could repaint circuit boards to disguise them as other boards

Universal paint tool soon:tm:

**Comment by habader** [comment]
ugly

**Comment by habader** [comment]
ugly

**Comment by optimumtact** [comment]
If your feedback is one word, express it with an emojii

**Comment by Time-Green** [comment]
🌈👍😎

**Comment by Detective-Google** [comment]
Lovely PR, can't wait for this to be implemented

-side note, does this affect the circuits during machine construction? (once being placed in the machine frame/computer frame, but before completing the machine) The machines have a pretty large green circuitry mass, so if those could have the corresponding colors too that would be neat (and would prevent plopping an orange circuit into a machine and turning green)

**Comment by ShizCalev** [comment]
conflicts.

**Comment by pireamaineach** [comment]
I think you probably should've resprited the black parts on the boards rather than the boards themselves, but eh. Good addition.

**Comment by Dennok** [comment]
Main black part is a chip. Border black part is too small.

**Comment by pireamaineach** [comment]
Main black part could realistically be coloured if you look at a real board. Rest is almost always green.

**Comment by Dennok** [comment]
> Main black part could realistically be coloured if you look at a real board. Rest is almost always green.

or black

or blue

or red


and chips mostly black

**Comment by Dennok** [comment]
Idea to add transparent glass/crystal boards for alien machines

**Pull request merged**
