### PR TITLE
Resprites the mass driver

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Resprites the mass driver

neutral
pUMP2

## Changelog

:cl: Wallem
imageadd: Resprites the mass driver
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Good sprite, even better branch name

**Comment by Wallemations** [comment]
Fixed something that was bothering me
The south sprite used to not have an outline at the top, I moved it down a pixel and fixed that.

**Comment by nianjiilical** [comment]
theres a bunch of things that use mass driver sprites for visual effects like the "photon torpedos" in the star trek holodeck

might be worth making sure they still look okay but its probably fine

**Comment by Wallemations** [comment]
> 

I couldn't find any star trek holodeck in the files, but if it's there I'm sure it's fine.

**Comment by Wallemations** [comment]
Hold on, I wanna update the mass driver controller button too. That one's already in 3/4ths, I just want the colors to look better.
image

**Comment by interestingusernam3** [comment]
>I couldn't find any star trek holodeck in the files, but if it's there I'm sure it's fine.

datum/map_template/holodeck/kobayashi

**Comment by Wallemations** [comment]
> > I couldn't find any star trek holodeck in the files, but if it's there I'm sure it's fine.
> 
> datum/map_template/holodeck/kobayashi


Looks fine to me

**Comment by Imaginos16** [comment]
Since its fine, I'll give it a merge.

**Pull request merged**
