### PR TITLE
Makes SM's radiation behave correctly

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

So, uh unless I have gone insane, rad output is broken currently.
You know how plasma, o2, and bz are meant to effect rads?
They don't.
They just don't anymore.

Here's the relevant line.
`radiation_pulse(src, power * (1 + (tritiumcomp * TRITIUM_RADIOACTIVITY_MODIFIER) + ((pluoxiumcomp * PLUOXIUM_RADIOACTIVITY_MODIFIER) * pluoxiumbonus) * (power_transmission_bonus/(10-(bzcomp * BZ_RADIOACTIVITY_MODIFIER))))) // Rad Modifiers BZ(500%), Tritium(300%), and Pluoxium(-200%)`
It's line 467 of supermatter.dm

Here it is cleaned up a bit
`radiation_pulse(src, power * (1 + (tritrads) + (pluxrads) * (power_transmission_bonus/(10-(bzrads))))) // Rad Modifiers BZ(500%), Tritium(300%), and Pluoxium(-200%)`

See the problem?
We're multiplying pluox with power transmission bonus, which is just this same line but done elsewhere.
`power_transmission_bonus = max((plasmacomp * PLASMA_TRANSMIT_MODIFIER) + (o2comp * OXYGEN_TRANSMIT_MODIFIER) + (bzcomp * BZ_TRANSMIT_MODIFIER), 0)`

The guy who added the pluox, trit, and bz reactions did this on accident I think?
Here's the pr. #45676

I've merged the two messes and modded the values of trit and ploux, so they should behave identically.
Here are the graphs of the negative aspects, they all cap above 0, so we shouldn't get negative rads,
unless the negative temp bug also effects gas proportions, but that's a headache for another time.
Gonna max it at 0 for now until I can figure out that hellspawn.
[Graph](https://www.desmos.com/calculator/sfszniqsa7)

## Why It's Good For The Game

This should make pluox even more of a safety gas, and actually give a good reason to run a 100% plasma engine, aside from bragging rights.
Also unreported bug man bad, yadeyadeyah.
 
## Changelog
:cl:TheFinalPotato
balance: See the below, optimal power setups may have changed, try out those 100% plasma hell setups of yours, it should actually give you a power benefit now. Oh and Pluoxium should be a bit more of a safety gas now.
fix: Fixed the SM not increasing/decreasing rad output with most gasses.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Lemon very slowly unfucking the SM, one PR at a time.

**Comment by LemonInTheDark** [comment]
[Relevant](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fhappinesz.com%2Fwp-content%2Fuploads%2F2016%2F01%2F1538362_838993506138736_1038199525_n.jpg&f=1&nofb=1)

**Comment by LemonInTheDark** [comment]
On a somewhat related note, this makes relative rad values consistent, so we can look at trit and go holy shit that's more then 6x plasma.

**Comment by JMoldy** [comment]
Nice. Thanks for organizing that to work more consistently.

The component percentage of the gasses shouldn't be affected by temperature because it's all checking only the moles.

**Comment by LemonInTheDark** [comment]
Of course, lord knows sm code needs all the help it can get.
When I say negative temp, it's in reference to this issue #48533, which let's be honest, I also need to fix.
Basically space fucks everything up, and I'm worried it's causing the gas percentage numbers the sm produces to go haywire.

**Pull request merged**
