### PR TITLE
Makes all gasses invis (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request
Cyber wanted to testmerge this for maptick memes, might as well do it proper
## Why It's Good For The Game

mood

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
It is done

**Comment by hermitec** [comment]
merge

**Comment by Dennok** [comment]
What results?

**Comment by LemonInTheDark** [comment]
Nothing measurable

**Pull request closed without merging**
