### PR TITLE
Removes the fake error texture floor tiles.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Removes the fake error texture floor tiles.

## Why It's Good For The Game

The error texture is intended to be a debugging feature to allow players and coders to identify items with missing textures and make issue reports or fix them.

When the fake error texture is used intentionally, it creates error fatigue so players are less likely to report issues and causes players to report issues that don't exist.

## Changelog
:cl:
del: Removed the fake error texture floor tiles.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Should remove the icon states too, at least the fake ones

**Comment by LemonInTheDark** [comment]
The tiles too? or is that one intended

**Comment by TemporalOroboros** [comment]
> Should remove the icon states too, at least the fake ones

You should probably also remove the inhands or repurpose them to actual error states.

**Comment by Timberpoes** [comment]
Inhands have been repurposed to actual error states.

**Pull request merged**
