### PR TITLE
Adds five new blob chemicals again

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Replicating Foam has a lower chance to expand when hit.
tweak: Penetrating Spines is now purple instead of sea green.
imageadd: Blobbernauts now have a brief animation when produced.
experiment: Adds five new blob chemicals. This is a total of 25 blob chemicals. Will it ever stop?
rscadd: Draining Spikes, which is reddish pink and does medium brute damage, and drains blood from targets.
rscadd: Shifting Fragments, which is tan and does medium brute damage, and shifts position when attacked.
rscadd: Flammable Goo, which is reddish orange and does low burn and toxin damage, and when hit with burn damage, emits a burst of flame. It takes more damage from burn, though.
rscadd: Poisonous Strands, which is lavender and does burn, fire, and toxin damage over a few seconds, instead of instantly.
rscadd: Adaptive Nexuses, which is dark blue and does medium brute damage, and reaps 5-10 resources from unconscious humans, killing them in the process.
wip: Confused about what the chemical you're fighting does? Look at https://tgstation13.org/wiki/Blob#Blob_Chemicals
/:cl:

no really 25 chemicals good god
Literally 25, all of which have a gimmick or slightly different damage setups.

### CODE REVIEW

**Comment by Zilenan91** [comment]
Are there checks preventing people from being teleported on top of the blob core where they can't be killed?

**Comment by ChangelingRain** [comment]
No, but I could probably add some.

**Comment by Zilenan91** [comment]
That's probably for the best so the blob doesn't have people getting teleported into its strong blobs and core start killing it while it can't kill them.

**Comment by KazeEspada** [comment]
Fungal Pods? Burst into fungal TB laced blood puddles?

**Comment by Zilenan91** [comment]
Kudzu Blob : Whenever a strong blob dies kudzu is spawned under it.

**Comment by GunHog** [comment]
Good lord, not even @Iamgoofball has ever gone this far! :+1:

**Comment by Zilenan91** [comment]
What would you think about a buff for shield blobs?

**Comment by Robustin** [comment]
So flammable goo is constantly emitting flames? How much blood gets removed? 

Blubbernauts that drain blood have got to be even more of a PITA than EMP ones. 

Also reduce blubbernaut HP. It needs to happen. With regen blubbernauts are stupid OP for 30 power.

**Comment by ChangelingRain** [comment]
Flammable Goo releases flames whenever you hit it with burn damage, so welders/etc. This doesn't apply to blobbernauts.
Draining Spikes removes 25 blood on blob attacks, 20 on blobbernaut attacks. It'd kill you with brute damage before the blood loss would really start to matter, but if you're getting dragged back and keep fighting it will start to matter.

**Comment by Zilenan91** [comment]
Blobbernauts could hit all the dead bodies and make them undefibbable due to instanly dying

**Comment by ChangelingRain** [comment]
Not anymore, they can't.
It'll only drain blood from living humans now.

**Comment by AdamElTablawy** [comment]
question

why do we need 24 blob chemicals

ALSO

blood loss is a hell of a lot harder to fight than almost anything because of the limited amount of bruise packs and how fucking obscenely lethal it is past a certain point with permaKO

so

the blooddrain blob will probably be cancer on the level of old 40 damage a hit lexorin jelly

**Comment by ChangelingRain** [comment]
It's only lethal if it get revived; it's intended to be absolute butts to fight if you keep getting healed, if you just get critted/die to it, it's pretty much the same as any other blob.

**Comment by GunHog** [comment]
Good lord, you have surpassed Goof, now!

**Pull request merged**
