### PR TITLE
Fixes the dview runtimes

### PR DESCRIPTION
**Pull request by Cyberboss**
I literally can't understand it and it hurts me to fix it this way

### CODE REVIEW

**Comment by AnturK** [comment]
Explain.

**Comment by Cyberboss** [comment]
Something about how /mob/dead initializes fucks with it and I have no idea
why it happens send help.

**Comment by optimumtact** [comment]
is there a better way to do dview

**Comment by AnturK** [comment]
I suppose asking lummox for it, but i have suspicion it was already done

**Comment by RemieRichards** [comment]
it was asked for, he said no, as is common.

**Comment by optimumtact** [comment]
above not below.

**Pull request merged**
