### PR TITLE
Reduce the threat level required for the Hacked AI Law Upload Module

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Reduces the threat requirement of the hacked AI law module to 50 threat. (5 minutes)

## Why It's Good For The Game
Right now the hacked law module is in an awkward spot where its useless most of the time cause of sci having AI upload boards and laws researched most of the time which make OneHuman and Freeform modules available rendering the hacked law module useless.

## Changelog
:cl:
balance: The Hacked AI Law Upload Module now only requires a threat level of 50 on the traitor uplink.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
For what its worth, hacked modules trump freeform ones, as due to law order you can ignore the human/Asimov/whatever aspects entirely.

**Comment by starrm4nn** [comment]
> you've reduced it by like 600% which is insane as a tweak and makes me think you're not being particularly serious about it.
> 
> do you have any data about when freeform or onehuman modules become available or just your reckons.

The research for it isn't locked behind any experiments, All the nodes are relatively cheap ,There's nothing stopping any human antagonist from asking the AI to download the R&D app on a laptop from the vendor near Sci and opening it for them to hoard points, The only hard wall they can hit while doing this is mats.

**Comment by starrm4nn** [comment]
> For what its worth, hacked modules trump freeform ones, as due to law order you can ignore the human/Asimov/whatever aspects entirely.
> 
> Edit: that is to say, hacked modules have considerably increased value over the ones sci can produce.

Yeah but that value is trumped over considering the fact that you can save 4TC by purging the AI and giving it custom laws with a freeform core or hit it with a onehuman then asimov just to make sure.

**Comment by SomeoneYouProbablyKnow** [comment]
> Right now the hacked law module is in an awkward spot where its useless most of the time cause of sci having AI upload boards and laws researched most of the time which make OneHuman and Freeform modules available rendering the hacked law module useless.

That can be said for most uplink items. The point of it is not to get literally inaccessible loot but to get a leg up on the station and fast. With this logic you might wanna buff the syndicate explosives because you can make atmos bombs and buff guns because you can make chemistry death rifles and buff everything else because with enough time you can just steal stuff that's similar.

If you want to buff the ai module at least make a compelling argument for it. Like "AIs need time to do anything even when subverted as any malf ai needs to maintain some level of stealth for a while at least. So there is no need for a reputation based timer"

**Pull request closed without merging**
