### PR TITLE
Da carpskin tailoring expansion: New luxurious carpskin suit and fedora.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This PR adds:
 a carpskin fedora; craftable with 2 carp scale.
As well as a carpskin suit; craftable with 3 carp scale.

bild

## Why It's Good For The Game

Having more exclusive clothing options facilitates trade, economical activity and departmental cooperation.

It also helps makes space carp hunting or growing more attractive to players, which helps provide space carp products such as carpotoxin and carp meat to medical and kitchen respectively.

## Changelog

:cl:
expansion: Carpskin suits and fedoras can now be crafted using carp scales.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
It's the dither salesman! It sells you dithering!

**Comment by Zytolg** [comment]
This is some swagger. I'm sorry Cayanne, but it's for the Meme.

**Comment by D4C-420** [comment]
Carpfia (carp mafia).

**Review by tralezab — APPROVED** [review]
waiting on spritetainer to take a look

**Pull request merged**
