### PR TITLE
Arachne Borgs

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Adds a resprited version of Arachne from /vg/station, done by me and 1glitchycent#1762. Comes with medical, mining, engineering, service, clown, and janitor models.

image

Spritetainer approval: (:trollface:)

image

## Why It's Good For The Game

We don't have any enough borg models for player to choose from, allows more player choice.

:trollface: 

## Changelog

:cl: axietheaxolotl, glitchy1cent
imageadd: Brand new Arachne cyborg skins.
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
woah cool 👍 i love spider robots

**Comment by Striders13** [comment]
so brave

**Comment by JoshAdamPowell** [comment]
I preffered dogborg

**Comment by ninjanomnom** [comment]
Spider themed content like this is laser targeted to appeal to me and I don't like it.

Very nice, reminds me of why I like vg's MoMMI sprite as well.

**Comment by DemoCrack** [comment]
lmao

**Comment by 13spacemen** [comment]
great sprites 👍 
also could lead to interesting RP, something which borg gameplay is severely lacking

**Comment by Time-Green** [comment]
I don’t think borgs should have humanoid shapes

**Comment by Time-Green** [comment]
Cool sprites, but I don’t think borgs should have humanoid shapes

**Review by Imaginos16 — APPROVED** [review]
And I looked, and behold a pale horse: and his name that sat on him was Death, and Hell followed with him.

**Comment by Shadowflame909** [comment]
I think clown borgs would shift to the top of science's research priority list

**Comment by Pandarsenic** [comment]
Merge it cowards, no balls

**Comment by MMMiracles** [comment]
where's the picture of that one guy ahelping asking if the sexy borgs were still in and when an admin responded yes, he immediately sent a radio message asking to be borged immediately

**Comment by bluetshirtguy** [comment]
against god and nature indeed, up there with one of the worst renditions of borgs ive seen, up there with dog borgs and erp borgs.

**Comment by chemistrymain2** [comment]
i was hoping for spiders, not spidergirls

**Comment by TymurShatillo** [comment]
Fetish content

**Comment by necromanceranne** [comment]
I think they're neat. I think yall are thinking too much with your respective junk.

**Comment by Twaticus** [comment]
i just remembered you can TM closed prs goodbye

**Comment by tommysalami3** [comment]
silhouettes
you should address the main issue with these sprites in the resprite, which is that they are incredibly difficult for players to tell apart. more distinct silhouettes would really help with recognition..

also, i understand the maid outfit idea for the janiborg, but it just makes it look out of place next to the other cyborgs and seem more like a syndieborg. i recommend that you go for lighter colors.

other than that these seem to not mesh with the type of sci-fi TG is going for, but these are intended for VG and this is a joke PR, so whatever.

**Comment by chesse20** [comment]
why'd this get closed?

**Pull request closed without merging**
