### PR TITLE
Buffs Anatomic Panacea and makes it depend less on reagents

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

The Anatomic Panacea changeling power no longer injects its user with pentetic acid, antihol, and mannitol. It still injects them with mutadone, however.

When used, the Anatomic Panacea power now does the following things:
* Causes you to vomit up any parasitic organs that are inside of you (it did this before).
* Cures all brain traumas of the lobotomy resilience tier or lower (it did this before) and immediately heals 200 brain damage.
* Sets the following values to 0: drunkenness, silent, radiation, dizziness, drowsyness [sic], stuttering, jitteriness, hallucination, slurring, cultslurring, derpspeech, confusion, drugginess, and disgust.
* **Purges all reagents from your body and stomach immediately.** I believe that most changeling players thought that old!Anatomic Panacea already did this, but it turns out that no, the chem-removal (and rad-removal) part of Anatomic Panacea actually came from the pentetic acid it gave you.
* Adds 10u of mutadone to your system. I'd really have loved to replace this with a direct mutation-clearing effect, but I fear that doing so could cause bugs with changelings who pop this power as a monkey or something.
* Clears all addictions.
* Heals 50 toxin damage, even if you have TRAIT_TOXINLOVER (before, changelings who popped Anatomic Panacea as a slime person would accidentally kill themselves with their own pentetic acid if they didn't change form, outheal the tox damage, or purge the pentetic acid somehow).
* Cures all non-positive diseases (and things that are technically treated as diseases by the game) that you're infected with (it did this before).

The Regenerate power was also slightly buffed to cover some of the things that Anatomic Panacea doesn't:
* Regenerate now sets the damage of all of your organs to 0.
* Regenerate now cures all brain traumas of the lobotomy resilience tier or lower. Yes, this makes Anatomic Panacea's ability to cure brain traumas somewhat redundant, but I believe that the ability to heal brain traumas could fall under the portfolio of either ability, and I'd rather not confuse or frustrate a new changeling player who activates an ability that logicially should heal their brain traumas, but doesn't because that actually falls under the domain of another ability. I'm considering adding Regenerate's wound healing to Fleshmend as well for a similar reason, but I'm stretching the scope of this PR already.
* Regenerate now cures blindness, deafness, and eye blurriness. I'm considering giving Anatomic Panacea the ability to cure eye blurriness as well, since it can come from multiple sources other than eye damage, but I'm still on the fence about that.
* Regenerate's blood restoration and embedded object removal functions now work on any carbon user of them, not just humanoids.

Adminordrazine is now self-consuming (skeletons and such can metabolize it and be healed by it now) and now cures cultslurring, deafness, and derpspeech. I think I also might have fixed a possible situation with the chem that could cause it to runtime when used by a non-carbon, but that was mostly an edge case anyway.

Antihol can now lower the drunkenness of monkeys and other nonhumanoid carbons.

The generic carbon regenerate_organs() proc now adds a stomach. Humans and such use a pseudo-override of the proc anyway, but monkey-form changelings should now be able to use the Regenerate to get their stomachs back (or heal their existing stomachs).

## Why It's Good For The Game

Making Anatomic Panacea less reliant on our medical chems means that we can rebalance or tweak those chems later without breaking/affecting the balance of Anatomic Panacea.

Anatomic Panacea is generally known as a "get that shit out of my body" ability, and especially as a "purge my body of reagents right now" ability, yet fails to fully deliver on either of those two fronts. This PR rectifies that issue and makes the power cover more things that it logically should cover.

## Changelog
:cl: ATHATH
balance: The Anatomic Panacea changeling power no longer injects its user with pentetic acid, antihol, or mannitol (it still injects them with mutadone, though), but treats MANY more ailments now (and treats the ailments it treated before much more immediately).
balance: The Anatomic Panacea changeling power now purges all chems from your body and your stomach immediately upon being used.
balance: The Anatomic Panacea changeling power now heals 50 toxin damage immediately upon being used.
balance: The Regenerate changeling power, like Anatomic Panacea, can now heal brain damage and cure brain traumas. In addition, it can cure some forms of blindness, eye blurriness, and some forms of deafness.
fix: The Regenerate changeling power's blood-restoring and embedded object-removal functions now affect monkeys and other nonhumanoid carbon users of the power.
fix: Adminordrazine is now self-consuming (skeletons and such can metabolize it and be healed by it now) and now cures cultslurring, deafness, and derpspeech.
fix: Antihol can now lower the drunkenness of monkeys and other nonhumanoid carbons.
fix: Regenerate can now give changelings in monkey form a replacement stomach (or heal a stomach that they already have).
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Why the hell did it mess up my indentation?

**Comment by ATH1909** [comment]
Looks like something had converted an indentation into some spaces.

**Comment by wesoda25** [comment]
Can we _not_ make lings even more OP?

**Comment by necromanceranne** [comment]
> Can we _not_ make lings even more OP?

This is honestly a functionality improvement, since the way it worked before was silly. Why have this power be reliant on chems when it should be wholly detached from them. This isn't a buff, since most of what it does now it did before, and lings haven't had much in the way of improvement despite various changes to medical stuff over time.

Not sure if regenerate is healing wounds as well, but if it isn't, it should. This is an area that lings are likely expected to be very good in. Most bodily issues are nonissues for them. The thematic part of lings being able to quickly restore bodily injuries and ailments is sensible given they already do this by dying and reviving themselves. The bit that is an actual problem, core to lings in their entirety, is that their chemical resource isn't as restriction as it probably could be, and that they're incapable of suffering attrition through damage ore resource usage, unlike many antagonists.

They rub shoulders with the likes of cultists and wizards in this regard, actually.

**Comment by ATH1909** [comment]
> Not sure if regenerate is healing wounds as well, but if it isn't, it should. 

Regenerate is indeed already able to heal wounds.

**Comment by ATH1909** [comment]
Okay, what the _hell_ is going on with my indentation here? Any indentation issues I correct just cause more to spring up- is there something wrong with the basic indentation of the entire file?

**Comment by wesoda25** [comment]
This is just making them invincible to everything as opposed to almost everything. I believe panacea was intentionally limited in it's effects, although if these things are just oversights or whatever then yeah this is fine.

**Comment by Sparkezel** [comment]
Panacea is cure for all, so something with that name really should be able to fix everything. Also making it independent from chemistry is good idea seeing what is happening around it lately and that there are going to be larger changes soon-ish™ but those are my 2 cents.

**Comment by necromanceranne** [comment]
I don't think most of the limitations were deliberate. Like I said, lings have a tendency, when their mechanics are using other game elements wholly detached from them solely, to be basically shafted or forgotten about because most other antagonists just don't work like that. Lings inject various chems into people as well, but why are they using mute toxin and frost oil? Why are their stings not just applying some kind of status effect? Because it's ancient, and probably the only reasonable way to do it at the time.

At one stage, mannitol was what fixed brain traumas. Then brain traumas were changed to require varying degrees of surgery or differing chems to fix them, but lings saw no changes whatsoever, even if the previous functionality was due to the thematically established justification of 'their brains are vestigal, so they can fix this'. This is a mechanic they already have in the form of being unable to be MMI'd and literally capable of surviving without a head. But because no updates happened to panacea, this mechanic was still affecting them even while it made no sense for them to be affected by it. This resulted in a massive inconsistency with their established mechanics and other game elements acting upon them.

The vast majority of these problems is just neglect and oversight. I even just discovered that likely, ridden vehicles have been broken for years because of stun changes that kevinz did. Hell, ryll reverted a pr by armhulen that nerfed tabling in their wounds update that has gone largely overlooked as well. Sometimes shit just gets forgotten about, and since the game is ever evolving, much of it is just believed to be a deliberate part of game balance when most of it is just accidental. There are just so many moving parts, how could you not miss one or two bits that are mostly inconsequential in the grander scheme of each change, like traumas and wounds?

I think wounds were added to regenerate mostly due to the fact that ryll was exceptionally thorough about their changes with regards to wound treatment and healing, and because people told them it's something worth considering with those changes. Likely nobody did the same with the trauma changes, so that just was nerfed for lings quietly with nobody looking to fix it, and has probably been so for only about two years.

**Review by Timberpoes — CHANGES_REQUESTED** [review]

**Comment by ATH1909** [comment]
> At one stage, mannitol was what fixed brain traumas. Then brain traumas were changed to require varying degrees of surgery or differing chems to fix them, but lings saw no changes whatsoever, even if the previous functionality was due to the thematically established justification of 'their brains are vestigal, so they can fix this'. This is a mechanic they already have in the form of being unable to be MMI'd and literally capable of surviving without a head. But because no updates happened to panacea, this mechanic was still affecting them even while it made no sense for them to be affected by it. This resulted in a massive inconsistency with their established mechanics and other game elements acting upon them.

To be clear, Anatomic Panacea currently already heals brain traumas, even without this PR.

**Comment by necromanceranne** [comment]
Then more accurately that likely was broken for at least a year because I remember Eagleandia grumbling about it at least a year ago in admin chatter, and I don't think their attempt at this very same idea you're doing actually was merged.

**Comment by tmtmtl30** [comment]
For the record, I think it's good for Mute Sting / Cryo Sting to inject reagents. Interesting connections between different mechanics like that allow for unique strategies, high skill ceilings, and memorable surprises. Interconnected systems are harder to maintain, but they're a core component of SS13.

(this change is totally fine, though, since _why would you think that the anatomic panacea power injects you with reagents if it's supposed to purge them?_ THAT is dumb; the abilities changelings have that inject things to cause debuffs actually injecting reagents is sensible.)

**Comment by Winterous** [comment]
Interestingly in its current state, I don't think Panacea actually purges reagents from the stomach at all; chemicals won't purge reagent from your stomach, because they aren't IN the mob, but in a container inside them.

Also I think that it should forcibly cure ANY disease, not just non-positive ones. The whole idea is an anatomical reboot, foreign infections would be rejected no matter what. Also it adds interesting counterplay in using viruses to detect changelings; if they don't have it, they likely are one.

**Comment by Jared-Fogle** [comment]
>  fix: The Regenerate changeling power's blood-restoring and embedded object-removal functions now affect monkeys and other nonhumanoid carbon users of the power.
fix: Adminordrazine is now self-consuming (skeletons and such can metabolize it and be healed by it now) and now cures cultslurring, deafness, and derpspeech.
fix: Antihol can now lower the drunkenness of monkeys and other nonhumanoid carbons.
fix: Regenerate can now give changelings in monkey form a replacement stomach (or heal a stomach that they already have).

Can these be made separate (except perhaps the two regenerate fixes) PRs? Easy to merge these right away rather than mull on the balance parts.

**Pull request closed without merging**
