### PR TITLE
Crystal monsters sprites

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
New sprites for the crystal invasion mobs
image

## Why It's Good For The Game
better sprites

## Changelog
:cl: Stewydeadmike#0068, Ghilker
imageadd: new crystal invasion mob sprites
imagedel: old crystal invasion mob sprites
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
Finally, no more mustard skelletons

**Comment by Farquaar** [comment]
The big guy looks fantastic.

**Comment by Qustinnus** [comment]
they look like skeletons with bad toenail growth

**Comment by wesoda25** [comment]
Damn now I wanna see some art on this event

**Comment by Pugie** [comment]
Big guy looks extremely painful and badass

**Comment by Winterous** [comment]
Thank god, now you can actually tell which is the one that'll rip your limbs off.

**Comment by OverlyGeneric** [comment]
They are far better than the original sprites. Something still feels off about the new sprites.

**Comment by Doosteroni** [comment]
The middles one sucks. The rest look good though

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
