### PR TITLE
Paramedic, are Assistants edible?

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Nilons
experimental: Adds CQC to traitors.
/:cl:

### CODE REVIEW

**Comment by Firecage** [comment]
Well, considering I previously tried to do this. For once I fully support your PR goof, and hope it does get merged. (It honestly does a non-meme PR title though).

**Comment by Iamgoofball** [comment]
psyche it's actually @Nilons pr

**Comment by GunHog** [comment]
Please fix your title to be acceptable, because I am actually interested in seeing this be merged!

**Review by Cyberboss — APPROVED** [review]

**Comment by Firecage** [comment]
@Iamgoofball Edit: One thing though. CQC is already listed in the uplink, but restricted for traitors only. Instead of adding a second listing for it, which clutters the code more. Wouldn't it be better to just remove the restriction to Nuke Ops from the current listing, and perhaps increase its cost from 13 to whatever?(Well, 13 is prob okay though. It doesnt have projectile immunity like Carp.)

**Review by lordpidey — CHANGES_REQUESTED** [review]
Goof, don't fucking steal PRs from newbies.

**Comment by Nilons** [comment]
bad pr close it pls

**Comment by lordpidey** [comment]
Just a heads up, this is @Nilons 's work.  Goof literally made this PR while I was trying to teach Nilon how to open a PR.

**Comment by Firecage** [comment]
@lordpidey Are you fucking serious? ...Okay, I take back muh support of this PR. And...now that I look at it, it literally is Nilons PR which Goof stole... Wow, just wow.

**Comment by ChangelingRain** [comment]
>goof literally steal's somebody's pr

no, fuck off, do your own work

**Comment by Iamgoofball** [comment]
yes I stated it was Nilons, I was planning to close it myself when he opened it but I went to take a shit and got sidetracked

**Comment by Firecage** [comment]
Doesn't matter. This is still an extremely vile thing to do. I honestly didn't expect you to sink THIS low.

**Comment by Iamgoofball** [comment]
it was a pure meme, of course I wasn't going to actually let this get merged

i was going to keep it open if Nilons had difficulty with his PR and all but he got it working so there you go

**Comment by lordpidey** [comment]
The reason he was having difficulty is BECAUSE this PR is open.

You cannot have multiple PRs from the same branch open at once.  I tried to open one while this one was open as a test, and it didn't work.

I specifically brought this up this potential problem in IRC, but you stated that this isn't an issue.  Well, it happened.

**Comment by Iamgoofball** [comment]
Yes you can?

**Comment by Iamgoofball** [comment]
I've opened the same PR at the same time before

**Comment by Iamgoofball** [comment]
Watch I'll do it

**Comment by Iamgoofball** [comment]
>they fucking fixed it

Goddamn it github

**Pull request closed without merging**
