### PR TITLE
Catgirls 2015

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds a catgirl version of cursed items

Fixes #10209

:cat2:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
GODDAMN IT

**Comment by duncathan** [comment]
10/10 :+1:

**Comment by Xhuis** [comment]
nyaa~

**Comment by xxalpha** [comment]
Noooooo :-1:

**Comment by WJohn** [comment]
Apparently this is the next meme in line. It may even succeed rare pepe and normies n shit.

**Comment by RemieRichards** [comment]
@Incoming5643 you should regenerate icons after the gender force, so that it properly updates.

**Comment by KorPhaeron** [comment]
I demand you re-add the Japanese animes button as well

**Comment by RemieRichards** [comment]
^^^^^^

yes! bring it back!

**Comment by Incoming5643** [comment]
@RemieRichards I don't have to, kitty ears regenerates icons on equip already.

I'll have to see what killed the japanese animes button

**Comment by Kromgar** [comment]
If its only during Wizard i have no problem with this

**Comment by Durkel** [comment]
Someone get me off this furry ride.

**Comment by Miauw62** [comment]
*THE RIDE NEVER ENDS*

**Comment by Dorsisdwarf** [comment]
Heads up: This itemset deletes spacesuits and the wizard's headgear when it fires in order to add the ears.

Just thought that might not be obvious to everyone

**Comment by Incoming5643** [comment]
That's what var/ruins_spaceworthiness and var/ruins_wizard_loadout are for. It flags the set to not affect the currently spacewalking or wizards.

**Comment by Cheridan** [comment]
What about the *@Incoming5643 you should regenerate icons after the gender force, so that it properly updates.* part?

**Comment by Incoming5643** [comment]
https://github.com/tgstation/-tg-station/pull/10238#issuecomment-116333803

**Comment by Cheridan** [comment]
OH OK IT WOULD HELP IF I COULD READ

**Comment by Incoming5643** [comment]
https://www.youtube.com/watch?v=YgtXAD6-RiY

**Comment by Xhuis** [comment]
BibleThump

**Pull request merged**
