### PR TITLE
Circuit Spellbooks: The Successor (and possible replacement) to SDQL Spells

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
## About The Pull Request

SDQL spells were made before circuits, and were extremely janky due to working off of the already janky system that was SDQL. With the addition of circuits - particularly admin-only circuits - circuit spellbooks became an option. An option that I only just now decided to implement.

Each of the main spell types (self, aoe, targeted, pointed, aimed, cone, staggered cone, and touch) have their corresponding circuit spellbooks, each coming with a component that allows you to set the relevant vars and control the on-cast behavior of the spell using circuits. The info tab on each component will tell you what output ports get set at the same time as which output signals, along with other useful information. A demonstration of what circuit spellbooks can do is shown below:

https://user-images.githubusercontent.com/12720844/156099595-12b6f323-d504-4bfd-b3d1-bdbf18c01074.mp4

A removal of SDQL spells is out-of-scope, but can be done later down the line if maintainers desire.
As a little side-addition, I added a string to icon component, which is useful for setting variables that expect an icon file.

## Why It's Good For The Game

Gives a slightly easier alternative method for admins to create spells with custom logic for the purposes of events or other memery.

## Changelog

:cl:
admin: Added circuit spellbooks, allowing admins to program custom spells using integrated circuits.
admin: Added the string to icon component as a helper for assigning icons to variables.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I'm not really a fan of this or the SDQL component spells.

We should be developing a proper scripting language for admins if this level of configuration is desired.

**Comment by Y0SH1M4S73R** [comment]
> We should be developing a proper scripting language for admins if this level of configuration is desired.
Funny you should mention that - I've made a couple attempts at trying to add LUA integration through an auxtools library. I might return to that at some point, but perhaps with a different language, or even a CST that mimics DM syntax as closely as reasonably possible within Rust.

**Comment by timothymtorres** [comment]
> > We should be developing a proper scripting language for admins if this level of configuration is desired.
> 
> Funny you should mention that - I've made a couple attempts at trying to add LUA integration through an auxtools library. I might return to that at some point, but perhaps with a different language, or even a CST that mimics DM syntax as closely as reasonably possible within Rust.

You should talk to @Mothblocks since he's doing some Lua-DM stuff.  I'm also a Lua developer and could probably help with this project if you guys need an extra pair of hands.

**Comment by Mothblocks** [comment]
oranges the last time i mentioned this exact thing

image

**Comment by Y0SH1M4S73R** [comment]
I'm working on the thing oranges said he would prefer to this, so yeah, closing...

**Pull request closed without merging**
