### PR TITLE
[WIP] Techwebs update - Bluespace material delivery, protolathe/circuitimprinter combined into departmental techfabs! And misc. refactors

### PR DESCRIPTION
**Pull request by silicons**
- [x] Fully refactor protolathes/circuit imprinters into machinery/rnd/production with shared procs and cross-machine support
- [x] Combine protolathes-imprinters for techfabs 
- [ ] Map in said techfabs - wow it would be done but mapmerge2 fucked me up!
- [x] Refactor UIs of departmental machines into unified UI code on machinery/rnd/production

Bluespace material delivery system:

# CHANGE OF PLANS: WORKING ON A NETWORK BASED SIMULATED SERVICE TO CONTROL MULEBOT AUTOMATED DELIVERIES. NTNET WILL FINALLY HAVE A USE!

- [ ] Special ORM
- [ ] Head of staff/QM approval system
- [ ] Cargo profit integration
- [ ] map in delivery system
- [ ] WIP: Changelog

- [ ] And integrate clownborgs while I'm at it.

:cl:
experimental: Techfabs have replaced and combined departmental protolathes and circuit imprinters on every map.
rscadd: [WIP ENTRY FOR CLOWNBORGS]
experimental: Bluespace mineral delivery system added. [WIP ENTRY FOR MINERAL DELIVERY]
experimental: [WIP ENTRY FOR CARGO PROFIT FROM DELIVERY]
code: RND production machines unified and code cleaned up.
/:cl:

@KorPhaeron

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
where are the clownborgs

**Comment by Buggy123** [comment]
:+1: its about damn time

**Comment by kevinz000** [comment]
Please disregard @MapDiffBot as maps aren't done yet.

**Comment by Buggy123** [comment]
Though, i still think we should do a shared resource system as well, where all lathes take material from a universal bluespace pool or some shit.

**Comment by kevinz000** [comment]
@The-clown-known-as-Pepe added to list.

**Comment by DaedalusGame** [comment]
Hey instead of making everything bluespace bullshit how about doing a minimal amount of work to integrate request consoles and mulebots, which have been dead in the water for years now?

**Comment by Qustinnus** [comment]
FloydWebs when?

**Comment by kevinz000** [comment]
@DaedalusGame techwebs forum thread kor asked for @Robustin's bluespace system, go post with your idea and i'll see about mulebot automation.

**Comment by awesine** [comment]
make mulebots useful

**Comment by Tlaltecuhtli** [comment]
can you put a better interface like the old protolathe for these

**Comment by DaedalusGame** [comment]
you're banned you're making me look bad if you agree with me

**Comment by Spaceinaba** [comment]
an interesting idea would be to allow departments to trade the materials they currently have so if they run out they can bug other departments because all the miners died to colossus/are still mining

**Comment by imsxz** [comment]
wtf I actually like Kev now

**Comment by Robustin** [comment]
@kevinz000 

How will the PANDEMIC and Exosuit Fab get worked into this?

**Comment by epochayur** [comment]
I'll be glad to see bluespace mat delivery, although I'll miss those tense runs between cargo and sci, trying to keep the mime from popping open your locker

RIP mules

**Comment by arsserpentarium** [comment]
No,fuck!make mineral delivery with mulebots!

**Comment by epochayur** [comment]
horse & buggy when

**Comment by DaedalusGame** [comment]
wtf i like kevin now

**Comment by Cyberboss** [comment]
Have to say I REALLY dislike bluespace delivery. It should use disposals.

**Comment by davethwave** [comment]
Perhaps in a later pr it would be good to add a item of some type to upgrade mulebots or to have cargo be able to buy a mulebot of different tiers that may have such things as extra health/armor so you won't have to hack them for them to be competent.

**Comment by Iamgoofball** [comment]
@Cyberboss Disposals is a laggy snowflake piece of shit system.

**Comment by Bawhoppen** [comment]
Not true in really any regard

**Comment by MoreRobustThanYou** [comment]
ffs just adopt goon's mail system or mass driver delivery

**Comment by SpaceManiac** [comment]
>but mapmerge2

I can't fix it if you don't make bug reports

**Comment by Robustin** [comment]
Bluespace was to prevent abuse from Cargo getting a "cut" for shipping its minerals out to departments. 

I suppose the solution for a delivery system is to just delay the payment until it actually arrives and gets delivered. Physical delivery is has cool points but I can't help but marvel at all the potential problems it might have and the extra time its going to take while techwebs languish.

**Comment by KorPhaeron** [comment]
robustin is right

**Comment by Bawhoppen** [comment]
Also it adds to the fun if people can be corrupt and embezzle resources that are supposed to be used for the station's good. Human stuff like that is what makes this game great.

**Comment by KorPhaeron** [comment]
Stale please finish this @robustin

**Comment by Robustin** [comment]
god damnit @kevinz000 

Once my box update is over.

**Comment by DaedalusGame** [comment]
I'm watching you

**Pull request closed without merging**
