### PR TITLE
Some clothing changes

### PR DESCRIPTION
**Pull request by ghost**
ss 2015-02-03 at 08 30 42

Sec jumpsuits are not unzipped by default now like the colored 'assistant' jumpsuit, so they don't show  your undershirt unless adjusted/rolled sleeves.

Added a turtleneck for the HoS to fill the void of the jensen jumpsuit.

Added the blue warden formal clothes to the warden's locker to go along with his dark blue police jacket.

Added flash protection to the HoS' eyepatch for quality of life. It doesn't necessarily make sense, but it's better than it being completely worse than the HUDshades he starts with. Better than rubbing our noses in bloody aft maint dirt.

Changed descriptions and names around on the jumpsuits to match the update steelpoint did away from mappcopsec.

### CODE REVIEW

**Comment by Steelpoint** [comment]
All good stuff.

:+1:

**Comment by paprka** [comment]
- Removed civilian armor (it just looked like a waistcoat anyway, the bartender/hop look better with normal armor)
- Fixed object sprites for the helmets (bulletproof and normal) being swapped
- Added a name for the alt (bulletproof) helmet

**Comment by Jordie0608** [comment]
Changelog.

**Comment by paprka** [comment]
Changelog.

**Comment by paprka** [comment]
Conflicts fixed here. Added the ability for the detective to store his two speedloaders in his holster along with his pistol. Also added the ability for the holster to store traitor revolvers and ammo, if that's your thing.

Added the holster to the biogen for 400 points. Traitors can be classy fuckers now.

**Pull request merged**
