### PR TITLE
Lowers explorer suit bullet & laser armor

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Lowers the mining explorer suit's bullet and laser armor values from 20% to 10%

## Why It's Good For The Game
Lavaland has no sources of bullet or laser damage sans one side of the Syndicate base. The explorer suit already provides identical melee armor to the riot suit, an armory item, while even outclassing it with superior defense against guns. Having only 10% less bullet and laser protection than security's body armor, while also covering the entire body instead of just the chest, and providing 30% greater melee protection, is excessive for a job whose only sources of damage come from fire, ash storms and melee.

## Changelog
:cl:
balance: Mining explorer suits have less defense against lasers and bullets.
/:cl:

### CODE REVIEW

**Comment by Repukan** [comment]
Make it 0

**Comment by Dawson1917** [comment]
> 
> 
> Make it 0

You would expect the suit being so heavily padded for softening melee impacts to at least confer some miniscule amount of protection against projectiles

**Comment by Qustinnus** [comment]
this is a game, just yeet it to 0.

**Comment by Shadowflame909** [comment]
Damn. All these armor nerfs.

The suffering is real

**Comment by Dawson1917** [comment]
> 
> 
> Damn. All these armor nerfs.
> 
> The suffering is real

The reskinned ERT suits from tendrils are going to get a passover too

**Comment by Shadowflame909** [comment]
Aw, what are you doing Dawson... Don't nerf that.

We don't need shitty defense armor bloat. If you really want to nerf them just remove them. So everyone can enjoy the other facits of the tendrils that aren't armor.

We don't need weaksauce armor in our tendrils mang. Especially so you don't noob-bait someone into using them to kill megafauna.

**Comment by Dawson1917** [comment]
The tendril suits aren't better for fighting megafauna, sans the fire immunity while fighting ash drakes, because their melee resist is actually slightly lower than the explorer suit's. It's the 50% bullet and laser resistance and free spaceproofing without slowdown that bugs me. I'd keep the no slowdown so they don't become useless for mining but I'd like to adjust their defences at some point. Tendrils aren't hard to loot and the gamer gear they can dispense can be pretty ridiculous on the station.

**Comment by 81Denton** [comment]
@Dawson1917 No point in rebalancing the ERT hardsuits that appear in lavaland since they're used by paranormal ERTs. Same with the cult hardsuit.
Just replace them with something else, or remove them from the spawn list.

**Comment by zamolxius** [comment]
instead buff the monsters

**Comment by SkeletalElite** [comment]
> instead buff the monsters

Lavaland should be less of a private land where everything is so stat bloated miners need stuff thats OP on station to survive, not more.

**Comment by zamolxius** [comment]
thats one way to put it,  i see your point yes,  but what about lavaland mobs having a special armor type that miner gear is well equipped to deal with?  lavaland is basically a deathworld,  and a large enough part of the game that a new armor type would be justified.

**Comment by nemvar** [comment]
>Lavaland has no sources of bullet or laser damage sans one side of the Syndicate base.
Not 100% correct. New legion uses laser armor for one of its attacks.

**Comment by Qustinnus** [comment]
just dont get hit bro

**Comment by MCterra10** [comment]
inb4 Dawson nerfs more than the orange man... Oh why did I show him how to work github PRs

**Comment by ATH1909** [comment]
> this is a game, just yeet it to 0.

What would be GAINED by dropping it to 0 instead of 10? That just seems unnecessary; dropping it to 10 feels better/more intuitive.

**Comment by necromanceranne** [comment]
Even hardsuits have some protection from bullets and lasers. No reason why the 'basically stalker suits but not' can't be even mildly bullet/laser proof. At 20% it's not that much different to just going and getting an armor vest out of a locker.

And melee armor means fucking nothing so even if this is a mix of high melee to okay bullet/laser it still is only useful against fauna.

**Comment by Dawson1917** [comment]
You can and should be getting your explorer's suit fully upgraded before the first ash storm hits. Goliaths are jokes after you learn to kill one. Anyone who runs to sec asking for armory loot so they don't have to ~~do their jobs~~ kill some goliaths is cringe and should be flashbanged for cringe.

Miners need many rebalances across the board because they get some of the best gear in the game from fighting simplemobs and chasing tendrils with GPS coordinates. Which is silly. The suit being less suitable for gunfights is of no loss to miners who do their jobs instead of validhunting once they get their hands on tendril gear

**Pull request merged**
