### PR TITLE
The laser carbine, a full-auto sidegrade to the normal laser gun

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

This PR adds the laser carbine, a new fully-automatic laser weapon that can be ordered from cargo. A crate of 3 can be ordered from cargo for 1800 credits, locked behind armory access. Here is a video demonstration:

https://github.com/tgstation/tgstation/assets/21979502/6f7fecec-ccb6-4a65-8027-21ab887fb91d

Now, I'm sure people are very concerned about the balance implications of this new weapon. Let me give you some hard numbers:

The gun deals 10 damage per shot, and has a capacity of 40 shots with a fully charged cell. This means that it has, at most, 400 damage per charge, which is exactly the same as a normal laser gun.

In terms of DPS, it can put an unarmored human in crit roughly as fast a laser gun. It is meant to be a sidegrade, not an upgrade to the normal laser gun. 

It also has considerably lower wound bonus. During testing, when all 40 shots were fired into an unarmored human, it dealt tier 1 burn wounds with the occasional tier 2. I never observed a single tier 3 burn wound during any of my tests.

Here's a picture of the different sprites (The last one is animated just like the normal laser gun): 

laser_carbines

## Why It's Good For The Game

For a long time, there has been a strong push to make crew-available weapons almost entirely energy based. This trend has been contentious, to say the least. Many people prefer ballistic weapons over energy weapons. After spending some time on a different codebase, one where autorifles are still completely available to order from cargo, no emag needed, I think I might know why (or at least part of the reason). Part of what I find satisfying about some ballistics is the fact that they fire quickly and automatically. Energy weapons might be more enjoyable to use if automatic energy weapons are also an option.

## Changelog

:cl:
add: The laser carbine, a weak but fully automatic sidegrade to the normal laser gun, can now be ordered from cargo.
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
I feel like the projectile should have some sort of tell on its sprite to know at a glance that it is weaker. Maybe make it thinner?

**Review by Wallemations — CHANGES_REQUESTED** [review]
the sprites look a bit more like a potato launcher than an energy weapon, though I can appreciate  the unique approach to a light-up magazine
To improve it, I'd recommend looking at palettes other energy weapons use as a starting point, as I feel the colors are a bit lacking.
Also, what's with the single-pixel line going around the bottom? Is that some sort of trigger guard? Why is it so big?

**Comment by GPeckman** [comment]
> I feel like the projectile should have some sort of tell on its sprite to know at a glance that it is weaker. Maybe make it thinner?

Something like that seems doable.

> the sprites look a bit more like a potato launcher than an energy weapon, though I can appreciate the unique approach to a light-up magazine 

I did my best, but I'm really not a spriter.

> To improve it, I'd recommend looking at palettes other energy weapons use as a starting point, as I feel the colors are a bit lacking.

I tried to base it off of the normal laser gun palette, I'll go back and give it a second pass.

> Also, what's with the single-pixel line going around the bottom? Is that some sort of trigger guard? Why is it so big?

Yeah, it's supposed to be a trigger guard. I'll see about making it smaller, if that's possible. For reference, aside from the normal laser gun, I also used [this image](https://cdn.britannica.com/12/130712-004-3A7FDDF8/Maschinenpistole-German-submachine-gun-World-War-II.jpg?s=1500x700&q=85) as a reference.

**Comment by DaydreamIQ** [comment]
This is pretty damn cool, the sprite needs some work but I'd be pretty pumped to see it in action

**Comment by carlarctg** [comment]
I'm fairly sure I recall some sort of chunky laser cannon sprite somewhere that can work for this. Not the red and white one that accelerators use.

Look into the gun.dmi files of bay, vg, yog, etc and you'll surely find a perfect fit. Just credit the station afterwards.

**Comment by Wallemations** [comment]
> I also used [this image](https://cdn.britannica.com/12/130712-004-3A7FDDF8/Maschinenpistole-German-submachine-gun-World-War-II.jpg?s=1500x700&q=85) as a reference.

Some of the weaker parts of your gun visually, looking at it closer, would be the handle & stock(?).
The MP40 you used as reference has that long thin stock, but perhaps you'd want to use something closer to your own design as a reference. Here's an example of an MP40 with the stock folded in, which is closer to the silhouette of what you're going for.

image

I'd say focus on that trigger/handle & decide what you want to do with that stock.

**Comment by EricZilla** [comment]
Could use another color for the beams like the wind up guns do, like a green or orange. I was thinking green since the mag glows that color

**Comment by GPeckman** [comment]
> > I also used [this image](https://cdn.britannica.com/12/130712-004-3A7FDDF8/Maschinenpistole-German-submachine-gun-World-War-II.jpg?s=1500x700&q=85) as a reference.
> 
> Some of the weaker parts of your gun visually, looking at it closer, would be the handle & stock(?). The MP40 you used as reference has that long thin stock, but perhaps you'd want to use something closer to your own design as a reference. Here's an example of an MP40 with the stock folded in, which is closer to the silhouette of what you're going for.
> 
> I'd say focus on that trigger/handle & decide what you want to do with that stock.

This is what I've got now:

laser_carbine

And I also touched up the battery overlays. I don't think it's done yet, but I think its an improvement.

> Could use another color for the beams like the wind up guns do, like a green or orange. I was thinking green since the mag glows that color

I made the beams thinner and gave them a yellow-orange color. Green is already taken by the x-ray lasers.

**Comment by Wallemations** [comment]
> This is what I've got now:
> 
> laser_carbine

certainly an improvement!
Another thing you could do to improve further on it is think about your outlines. Right now they're just single, solid colors. That's wasting a lot of surface area. Here's an example of another far newer gun sprite;

12342342141234-export

See how the outlines are used as an extension of the main colors used, while still remaining darker than the color inside? 
A lot of our newer sprites do this, which is something the original energy guns lack since they're honestly pretty old. 
If you want a simple way of doing it, you could simply make the outline one shade darker than the color it's outlining.


I'm by no means expecting you to output something of this level without practice, so don't worry about that. I'm just trying to get you to think a little about outline composition & colors.

**Comment by D4C-420** [comment]
Finally a counter to nukies shielded hardsuits and blade heretic knives

**Comment by SimplySmiley123** [comment]
To me it never was about "being an automatic weapon" with ballistics.
It's about the punch of them. Shotguns, revolvers, even pistols and the autorifles felt differently to how you shot foam darts with laser guns.
There is no _oomph_ to laser guns. No satisfaction. Even damage wise you'll get shafted by traitors and nukies being able to easly hard counter them with only really the wounds being anything threatening about them, which even then I rarely seen anyone go beyond tier 2 burn wounds.

**Comment by moocowswag** [comment]
Does it fire faster in emitters too?

**Comment by CCC23** [comment]
finally the atf has allowed us to purchase automatics

**Comment by BlueMemesauce** [comment]
This is also a counter to regal rats and maybe space carp

**Comment by EricZilla** [comment]
Guys go easy on him it's a codersprite

**Comment by GPeckman** [comment]
Alright, here's what I've got for the sprite now:

laser_carbine

Here's what it looks like in-game:

laser_carbines

And I've also updated the PR body itself with those and with a new video, which showcases the orange lasers.

**Review by Wallemations — APPROVED** [review]
Still not perfect but a large improvement from your starting position.

While I'm approving this based off that, I still implore you to ask around the spriting channels and see if anyone would be willing to polish it further.

**Review by optimumtact — APPROVED** [review]
orange lasers

**Comment by DrDiasyl** [comment]
I would name this huge QoL for people with bad aim 😆

**Comment by GPeckman** [comment]
> Does it fire faster in emitters and turrets too?

Just realized that I forget to respond to this. Due to the way the code works, no, it does not fire faster in a laser turret, and that functionality would probably need to be coded from the ground up. However, I don't think any weapons fire _slower_ in a turret, so you could just build a turret with hellfire lasers for that extra damage and wound chance.

**Comment by Shadowflame909** [comment]
Stormtrooper time

**Review by Jacquerel — CHANGES_REQUESTED** [review]

**Comment by GPeckman** [comment]
No idea why the transformation sting unit test failed, it worked fine just now on local. With luck it'll work this time.

**Pull request merged**
