### PR TITLE
forks now contain silver

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

forks now grind into silver

## Why It's Good For The Game

fun for ghetto chemistry

## Changelog
:cl:
tweak: forks now grind into silver
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
can u even grind things like forks

**Comment by Fikou** [comment]
> can u even grind things like forks

uhh maybe

**Comment by Dawson1917** [comment]
Goes against lore; Nanotrasen would never shell out the funds for silver cutlery. We eat with plastic here.

**Comment by Qustinnus** [comment]
i dont think so

**Comment by spessbro** [comment]
> 
> 
> Goes against lore; Nanotrasen would never shell out the funds for silver cutlery. We eat with plastic here.

actually a genuine reason

**Comment by Shadowflame909** [comment]
honestly if it grinded down into plastic too that would be pretty epic for my plastic beakers and water bottles.

Now how do we get a 50/50 chance of it being silver cutlery and plastic cutlery

**Comment by Potato-Masher** [comment]
Better yet, make the current ones plastic and have a new spirte for actual silverware made with silver, made from autolathes and service techfabs. Let the chef upgrade his customer's dining experience with premium wares.

**Comment by Fox-McCloud** [comment]
This makes me wonder if there's an ulterior motive here.

Gather up just enough forks for the silver to rush a particular item ASAP.

This is also dumb from a balance perspective, too.

Stick metal in an autolathe, print out forks, get silver back.....uhh, what?

Alternatively, rush the chef vendor and dispense a ton of them (That he'll never use anyway) to get some free silver.

**Comment by Fikou** [comment]
> This makes me wonder if there's an ulterior motive here.
> 
> Gather up just enough forks for the silver to rush a particular item ASAP.
> 
> This is also dumb from a balance perspective, too.
> 
> Stick metal in an autolathe, print out forks, get silver back.....uhh, what?
> 
> Alternatively, rush the chef vendor and dispense a ton of them (That he'll never use anyway) to get some free silver.

wait you can print forks from autolathe?
oops haha

**Comment by fludd12** [comment]
Datumized material forks when?

**Comment by carlarctg** [comment]
why is this pr open if you reverted the only change it had

**Comment by Fikou** [comment]
> why is this pr open if you reverted the only change it had

i didnt revert the main reason for the pr existing

**Comment by optimumtact** [comment]
Nt doesn't waste money putting silver in forks, add fancy silverware to the heads break room if you want

**Pull request closed without merging**
