### PR TITLE
Canonical Movement

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request

- https://github.com/DaedalusDock/daedalusdock/pull/892
Currently, TG's movement chain is not canonical, meaning movement can resolve in an order that doesn't actually represent what it going on. For example, if something inside of an Entered() call would move the currently moving object, it resolves in this order:

1. Original Move
2. Intercepted Move
3. Intercepted Moved
4. Original Moved

This makes Moved() unreliable at tracking things like spatial grid locations. This is a massive problem.

This PR introduces `active_movement`, a list containing arguments for `Moved()`. At the start of `Move()` and `doMove()`, if the list is present, it will call Moved(), concluding the original movement, before proceeding. The original `Move()` call will not end in `Moved()`, due to `active_movement` being null.

This is touching some of the most important code in the game and needs extensive testing.

### CODE REVIEW

**Comment by san7890** [comment]
people were complaining about a bug that would "lock people up" transiently for a few seconds on Sybil Round 225755- I pulled the pull request and demanded they make an issue report regarding it (some maintainers were on, hopefully they can collect good data i hope)

**Comment by JohnFulpWillard** [comment]
It's been testmerged on sybil for 2 rounds (one still ongoing) and both times apparently movement just seemed to stop. Even observing I find myself unable to move, trying to move instead just types in my chat bar and tabbing doesn't swap to move mode. arrow keys also don't work and instead just moves where I'm typing.
Vid (me using WASD to move, trying to tab out, trying to click my screen, trying to use arrow keys):

https://github.com/tgstation/tgstation/assets/53777086/3b55d203-db5c-4c46-b81b-d829adac06f9

Runtimes that might be related (ID 225755):
image
image
image
image
image

**Comment by Kapu1178** [comment]
I have changed the code such that `active_movement` is nulled before performing the `Moved()` call, as Kyler's theory is that it's caused by a `Moved()` subscriber causing another movement. 

The `mob_movement.dm` runtimes Willard posted are unrelated, that's just shitcode. Check out the lines and you should immediately notice what the issue is with that.

**Comment by san7890** [comment]
No complaints about this over the last two days of dual-server test merges, you think it's ready to ship?

**Comment by Kapu1178** [comment]
> No complaints about this over the last two days of dual-server test merges, you think it's ready to ship?

@Kylerace

**Pull request merged**
