### PR TITLE
Medkits-- resprited-- AGAIN.

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

wow look, medkits have been resprited again!!!

image

image
## Why It's Good For The Game

idk, is it? it is. it looks better.
## Changelog
:cl: axietheaxolotl / viro
image: new medkit sprites, again.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
The damage type graphics look weird.

**Comment by orthography** [comment]
> The damage type graphics look out-of-place.

Your nose is going to look out of place when I make it crooked.

(You have no soul)

**Comment by atlasle** [comment]
why not resprites thing that look bad instead, like most simplemobs for example

**Comment by Helg2** [comment]
Can you show how it looks in context of medbay (the storage of medkits). It's kinda hard to comper properly

**Comment by Profakos** [comment]
Will medibots be updated soon? The disparity between their components and their finished look is increasing.

**Comment by CRITAWAKETS** [comment]
What's with the shading on the top? Is the top of the medkits meant to be like a peel-off sticker or something?

**Comment by ChungusGamer666** [comment]
next medkit resprite i'm committing vehicular manslaughter

**Comment by Fikou** [comment]
you made the largest medkit in the game look like the smallest one

**Comment by orthography** [comment]
> why not resprites thing that look bad instead, like most simplemobs for example

I don't see contributor next to your name, peanut poster.

When you sprite it yourself, 4head.

**Review by Imaginos16 — APPROVED** [review]

**Comment by TheVekter** [comment]
If you're respriting these again, you're going to need to resprite the medibots, too.

**Comment by Wallemations** [comment]
While I personally prefer the look of the current ones, these are still very good enough where I don't really care if they get replaced or not.

However, the scissor icon looks like it could be lifted a pixel imo.

**Comment by Al-1ce** [comment]
These look great but they're a little too sterile for the current artscheme. I'd still take them over our current stuff any day, though.

**Comment by EricZilla** [comment]
Love the colors on these. The small ones feel a tiny bit weird but I'm not sure why so this comment is mostly useless sorry lmao

**Comment by Profakos** [comment]
Only now i realize, the way the latches are placed would mean that the icons would be upside down while you are carrying them around.

**Comment by milktao** [comment]
I suggest changing the colours of some of these kits, there are 4 with similar colours. Most notably, the Medkit and Oxygen Deprivation Kits in the current version are easier to distinguish in an emergency. The only difference in these are the symbols in the center, which are hidden when stacked.
Perhaps make the Medkits a lighter blue or have more white as per the current medkits?
Overall though, the perspective makes more sense on these. I just think it would be even better if there was an easier way to tell those two kits apart.

**Pull request merged**
