### PR TITLE
Randomized Exotic Seeds Crate

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Adds some missing seeds to the seed_rare spawner and adds a cargo crate containing 5 of these seeds for 1000 credits.

## Why It's Good For The Game

Because current exotic seed crates are very boring and unrewarding, also makes botanists less likely to go maintenance looting for seeds and instead do their jobs.

## Changelog
:cl:
add: adds a new random exotic seeds crate for 1000 credits (5 seeds)
add: adds recently merged rare seeds to the rare seed spawner
/:cl:

### CODE REVIEW

**Comment by yorii** [comment]
Oops I edited the wrong datum lmao

**Comment by yorii** [comment]
Open to suggestions for different seed selections/roll weights

**Comment by timothymtorres** [comment]
You may want to consider using the exotic random seed spawner instead:

https://github.com/tgstation/tgstation/blob/efbb25f471e21c229bcc7a3e356a78dee1a92b4d/code/game/objects/effects/spawners/random/food_or_drink.dm#L51-L70

**Comment by yorii** [comment]
I see... I wonder why there seems to be already be spawners that are direct duplicates of the lists on cargo crates... maybe I should just refactor the whole thing...

**Comment by the-orange-cow** [comment]
As far as i know, the exotic seed crate is the only way to obtain seedlings, hedges, and rainbow bunch at this time.  I don't see the benefit of removing a constant method of obtaining these seeds in a round.

I think it would be better to add a random seed crate instead of replace the exotic seed crate.

**Comment by yorii** [comment]
Changed it to a completely new crate, using the rare seeds spawner, also added all new seeds recently merged to said spawner.

**Comment by Time-Green** [comment]
Sorry but I’m gonna be anti-fun here. The point of a lot of these seeds is that they have their own method of being obtained, putting them all in cargo is lazy (odious puffball and kronkus being maint only, not sure about the rest)

I agree exotic seeds crate could be more worthwile. Why not add some new exotic seeds?

**Comment by yorii** [comment]
> Sorry but I’m gonna be anti-fun here. The point of a lot of these seeds is that they have their own method of being obtained, putting them all in cargo is lazy (odious puffball and kronkus being maint only, not sure about the rest)
> 
> I agree exotic seeds crate could be more worthwile. Why not add some new exotic seeds?

But why is odious puffballs and kronkus maint only? Doesn't that encourage botanists to not do their job?

**Comment by Time-Green** [comment]
> > Sorry but I’m gonna be anti-fun here. The point of a lot of these seeds is that they have their own method of being obtained, putting them all in cargo is lazy (odious puffball and kronkus being maint only, not sure about the rest)
> > I agree exotic seeds crate could be more worthwile. Why not add some new exotic seeds?
> 
> But why is odious puffballs and kronkus maint only? Doesn't that encourage botanists to not do their job?

You don’t need to be able to get everything every round. If you want it, ask an assistant, ask the HoP for maint acces or accept not everything is within your control and hope someone just brings it to you

**Comment by Time-Green** [comment]
I’m going to free you from uncertainty and close this. But feel free to add some cool new plants to exotic crates!

**Comment by yorii** [comment]
> I’m going to free you from uncertainty and close this. But feel free to add some cool new plants to exotic crates!

Thanks, I'll just ship this downstream as originally intended instead.

**Pull request closed without merging**
