### PR TITLE
Repathed Metastation floors to use proper subtypes.

### PR DESCRIPTION
**Pull request by xxalpha**
And cleaned up Box, Lavaland, z2, z3 and z5.

No new airless subtypes were created.

Compiled locally just to make sure, since travis had some problems detecting bad paths.

http://pastebin.com/raw/cZQP2trT

### CODE REVIEW

**Comment by vulpineryth** [comment]
Does this fix those instances where Gibonite explosions causes no pressure areas in Lavaland?

**Comment by xxalpha** [comment]
No that's completely irrelevant.

**Comment by pudl** [comment]
ITS NOT EVEN YOUR MAP LEAVE IT ALONE

**Comment by xxalpha** [comment]
Every map is going to be repathed.

**Comment by optimumtact** [comment]
>since travis had some problems detecting bad paths.
Can you elaborate more on this?

**Comment by xxalpha** [comment]
This https://github.com/tgstation/tgstation/pull/18206

**Comment by xxalpha** [comment]
This is ready to be merged.

**Pull request merged**
