### PR TITLE
Fixed natural temperature stabilization when on fire

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

Natural body temp stabilization fix is so stronk that it made some fire less dangerous.
This will make fire scary again. 

## Why It's Good For The Game

You should not be able survive being on fire without a fire suit, or massive amounts of insulation.

## Changelog
:cl:
fix: Being on fire causes damage as expected in all situations.
/:cl:

### CODE REVIEW

**Comment by nightred** [comment]
Or we could make fire worse to overcome natural healing...

**Comment by XDTM** [comment]
natural temperature stabilization is way too aggressive in general, it makes fevers completely ineffective

**Comment by trollbreeder** [comment]
> natural temperature stabilization is way too aggressive in general, it makes fevers completely ineffective

I, as a lizard main, agree with that, because i have no natural temperature stabilization and going in a cold area for 10 seconds is enough to kill me after 20. Pesky humans have it easy.

**Comment by nightred** [comment]
I am thinking of slowing down body temp stabilization so that a fever, and fire both play better. Please wait on an update.

**Comment by nightred** [comment]
This makes fire hurt more at room temperatures, the fever fix needs something completely different and will be on a different PR.

**Comment by PKPenguin321** [comment]
This explains it... I found a naked dude in maint who had lit himself on fire as a suicide attempt, made it all the way to the medbay with him not even notably damaged

**Comment by nightred** [comment]
I am closing this PR as the fever fix I am pushing contains this fix, and is needed for fever to work.

**Pull request closed without merging**
