### PR TITLE
Freon Removal

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
From cargo, xenobio, and the holodeck

Things that crash the game shouldn't be accessible

### CODE REVIEW

**Comment by Cyberboss** [comment]
I JUST SAID I WAS HANDLING THIS!!

**Comment by dannno** [comment]
LOL

**Comment by Nabski89** [comment]
So handle it then add it back in. For now it still crashes the server.

**Comment by FantasticFwoosh** [comment]
How salty could you be, the canisters aren't even 

Leave it in xenobio and make scientists exert themselves to create it for long-/end game would be more balanced. Holodeck probably a good choice, cargo price could probably be pushed further up or arrive in 50 ounce plasma canisters rather than a full canister.

> There are better ways to crash the server

Feels like a very ("I/I had to ahelp someone ded please nerf") kneejerk reaction rather than a logicial move.

Where's a popular vote/forum discussion before going through with this change?

**Comment by optimumtact** [comment]
Excuse me? Freon exposes a bug in slip code that causes crashes, you can have it back after it's fixed

**Comment by KorPhaeron** [comment]
@optimumtact 

Don't take the bait

**Pull request merged**
