### PR TITLE
Tints the screen for halloween

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Adds a color matrix to the game plate on halloween that greyscales slightly and dims/drops dim colors for a harsher dropoff
I'm not sure the dropoff is strong enough, can't decide.

## Why It's Good For The Game

276023326-205a3068-4f6c-4531-bc19-a3bb1f9f3a5e

## Changelog
:cl:
add: Screen is now more grungy for halloween
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Why not add some sort of soft desaturation for that old Halloween type vibe

**Comment by lessthnthree** [comment]
I've wanted to know how to do this for so long, thanks!

**Comment by san7890** [comment]
looks a bit deepfried but spooky enough ig

**Comment by carlarctg** [comment]
Lower the saturation of all colors except orange and maybe purple for a spookier effect.

**Comment by LemonInTheDark** [comment]
> Why not add some sort of soft desaturation for that old Halloween type vibe

> looks a bit deepfried but spooky enough ig

image

How's this?

**Comment by LemonInTheDark** [comment]
> Lower the saturation of all colors except orange and maybe purple for a spookier effect.

Can't go that detailed I don't think (tho maybe if I was using hsv or something? need to build tooling for that)

**Comment by Jolly-66** [comment]
> Lemons image

Very swag 👍

**Comment by BlueMemesauce** [comment]
Looks much better i love it

**Comment by Striders13** [comment]
you should make space glow in spooky purple too

**Review by Ghommie — APPROVED** [review]

**Comment by Googles-Hands** [comment]
Way too dark, congratulations, looks like shit.

**Comment by LemonInTheDark** [comment]
> Way too dark, congratulations, it reminds me of the Lifeweb darkness/tint but worse.

Thanks!

**Comment by Eastwardrope** [comment]
This causes my eyes physical pain during a round. I can not play the game due to this filter. IDK Why it causes me such pain but I can't look at the station at all running this.

**Comment by Googles-Hands** [comment]
> > Way too dark, congratulations, it reminds me of the Lifeweb darkness/tint but worse.
> 
> Thanks!

That was not a compliment. I'm just not playing the game during Halloween thanks to this.

**Comment by Sk1Wass3r** [comment]
Even with night vision or mesons on, you cannot see anything in areas with dark tiles or that are unlit

**Comment by LemonInTheDark** [comment]
I have a pr up for this rn #79340

**Pull request merged**
