### PR TITLE
Removes renameable flag from Death Sandwich

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Removes the flag from the Death Sandwich which allows you to rename it (and change its description) using a pen.

## Why It's Good For The Game

This sandwich kills you.
This is fine if it is called "Death Sandwich" and has the description "Eat it wrong, or you die!" because people eating it know what they are getting into.
It's less fine if someone has renamed it to "yummy sandwich" and it has the description "mmm yummy tasty".
Memorising sandwich sprites to avoid being killed by a disease (as punishment for not having a mullet and wearing jorts) should not be an important knowledge check.

## Changelog

:cl:
balance: The Death Sandwich can no longer be renamed
/:cl:

### CODE REVIEW

**Review by san7890 — APPROVED** [review]

**Review by MrMelbert — APPROVED** [review]

**Comment by Cyberboss** [comment]
okay, this is epic

**Comment by Wallemations** [comment]
I didn't even think about this when I made it, have people been renaming the sandwich???

**Comment by ATH1909** [comment]
okay but the sandwich isn't actually that lethal

like, if this was a "you fall over dead once you hit stage 3" sort of disease (or an uncurable one), I'd get it, but death sandwich-ism seems very... treatable, with a sluggish kill time. is it invisible to medhuds?

**Comment by Comxy** [comment]
Will this cause a chain reaction for all the other lethal food items like gondola steak, arnold pizza or borger. What about food in general since they are pretty easy to poison?

**Comment by Jacquerel** [comment]
> Will this cause a chain reaction for all the other lethal food items like gondola steak, arnold pizza or borger. What about food in general since they are pretty easy to poison?

No, it won't.

**Pull request merged**
