### PR TITLE
Makes drag/drop that dont have any use call click

### PR DESCRIPTION
**Pull request by Razharas**
Makes drag/drop that dont have any particular defined behaviour be treated as just click on the dragged object
:cl: Razharas
tweak: Makes clicking something in heat of battle a bit easier by making drag&drops that dont have any effect be counted as clicks
/:cl:

Makes drag/drop that dont have any use call click

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this kills tactical drags

**Comment by ChangelingRain** [comment]
this makes tactical dragging super op because you can drag someone, run at them and release for instant attack
at least, if I understand the code right~

**Comment by optimumtact** [comment]
@Razharas @ChangelingRain is it going to be super unbalanced?

**Comment by PKPenguin321** [comment]
Testmerge it and find out

**Comment by PKPenguin321** [comment]
I will say that this is definitely a massive buff to any melee weapon that stuns on hit IE stunbatons, prods, telebatons, etc. though

**Comment by nullbear** [comment]
Yeah this can be used to reduce pixel-hunting in combat. It doesnt seem to me to be very unbalanced, relying on pixel-hunting for balance is bad anyways. It's about as bad as alt-clicking a tile, standing still, and hitting clicking your target whenever they run through the tile. (ie. it's a 100% chance to hit. At the cost of your own mobility) this one sacrifices multiple-hits for a better chance to hit.

**Comment by Razharas** [comment]
Testmerging didnt show any extremely powergamy consequences

**Pull request merged**
