### PR TITLE
Reworked Icebox Service   -= M u l t i - Z =-

### PR DESCRIPTION
**Pull request by Zytolg**
**Icebox is a Multi-Z station.**

Icebox S Bot 21
IceBox S Top 21

## Changelog
:cl:
add: Makes Icebox Service Multi-Z through retroaction. 
add: The first Multi-Z kitchen on /tgstation/
fix: Tosses out the non Multi-Z aspects of the previous service
qol: You can now use stairs to visit the various areas of Icebox Service

fix: This should force ruin spawns out and away from the center of the station. Next step is to actually add icebox ruins that are small but help force that spawn condition. 
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Could the buffer of safe area between randomly generated iceland and hydroponics be expanded, to stop the wolf / bear raid on lower botany meme?

**Comment by GuillaumePrata** [comment]
Only having 1 set of airlocks between the outside and botany is asking for Atmos issue, even with a heater 2 tiles from it.

**Comment by Livrah** [comment]
Bar on another Z level is a bad idea. Unless its in middle of main hallway like meta/current box, it will be abandoned like Tram's bar.
Bunker Z level is better for something like sci/atmos, but I dont like multi Z in general so please no.

**Comment by Greniza** [comment]
It’s kind of a long walk to Botany from the kitchen, and once you get there, you don’t have access to the biogenerator.

**Comment by maxymax13** [comment]
bar on lower z means nobody vising bar ever like on tram, also muh iconic box bar 😢

**Comment by Capsandi** [comment]
image
Nobody will go out of their way to use an auxiliary botany setup when the public garden near arrivals has more and wont be bolted/walled off on most shifts, just fill the space with portable atmos equipment or something easy to repurpose.

Great work on the lower tunnels, and I like those engineering ladder rooms

**Review by Maurukas — CHANGES_REQUESTED** [review]
I believe you're already aware of missing intercoms. Before I get into the review laundry list. I like this a lot. There's a good feel to the lower bar in particular. If I have one complaint, it is that the bar feels _ever_ so slightly too small. Extending it upward a couple tiles (where the service corridor is) might allow you to fit in some additional booths or tables.



<details>
<summary>Extra plumbing pipes under the sinks like so. They contain their own pipe: </summary>

image
</details>

<details>
<summary>The ladder in the utility room is not working. The tile on the upper level is two tiles north of the one on the lower: </summary>

image
</details>

<details>
<summary>Disposal pipes are overlaying hazard stripes. Are you dead set on bare plating here? </summary>

image
</details>

<details>
<summary>It would be really nice if this sign were visible from the main hall. As it stands, you don't see it when walking past outside: </summary>

image
</details>

<details>
<summary>There are three air alarms in the downstairs bar area, and an additional one upstairs. There are atmos devices in the theater area, but that does not have an air alarm. The back hallway on the lower level has two air alarms. Lower Botany has two air alarms.</summary>

image
image
image

</details>

<details>
<summary>Some clipping issues:</summary>

image
</details>

<details>
<summary>You added a second APC to starboard primary. The original is in front of the morgue. Please remove one: </summary>

image
</details>
<details>
<summary> This pipe junction is open ended and there does not appear to be any way to get a cooling gas into the freezer loop:</summary>

image
</details>

<details>
<summary>There are some big walls of nothing, with no decorations or windows. Particularly the back of the diner, the starboard hallway (where Botany's entrance used to be), and this one along the primary loop. Posters, wall doodads, art and windows would all be appreciated to break up this expanse of grey.</summary>

image

</details>

<details>
<summary> The lower kitchen tables are very empty. Some clutter would go well here: </summary>

image
</details>

**Comment by Zytolg** [comment]
> I believe you're already aware of missing intercoms. Before I get into the review laundry list. I like this a lot. There's a good feel to the lower bar in particular. If I have one complaint, it is that the bar feels _ever_ so slightly too small. Extending it upward a couple tiles (where the service corridor is) might allow you to fit in some additional booths or tables.

Alterations have been made and committed.

**Comment by Mickyan** [comment]
I can't help to notice there's no "why is this good for the game" section, this layout puts another nail in the bartender's proverbial coffin but at least botany gets a hallway-facing double-backdoor, a front desk hidden behind two airlocks and the kitchen gets a cramped choke point at the entrance? Nothing about this layout makes any practical sense

**Comment by Maurukas** [comment]
Looks great. The little extra bit of room at the back of the bar is perfect.

Just fix your complimentary 7 AM merge conflict.

**Comment by bluetshirtguy** [comment]
many moons later and this is still a prime example of terrible kitchen design.

**Pull request merged**
