### PR TITLE
GPS Personalizations [Post TGPSUI]

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
🆑 Cobby
tweak: The GPS set tag has gone from a limit of 5 characters to 20.
add: The GPS can now be personalized in both name and description using a pen.
/🆑

Allows players to rename GPS's and their tags because the automatic renaming was going to be really long and probably obnoxious, and for labelling, which allows them to better describe what is at that particular location or lure them to an area with false promises. Consequently, this will also help alleviate the problem of finding your tag within the mess of many GPSs since you can type more than the 5 character code which nearly every other GPS has.

GPS tag setting is no longer all uppercase for the same reason.

ONE DAY I'LL BE GOOD AT GITHUB I PROMISE

### CODE REVIEW

**Comment by GunHog** [comment]
You do not have to search the list to find your own tag, it is displayed on the tag edit button. Your own signal is not included in the GPS list, but under "Current Location".

**Comment by ExcessiveUseOfCobblestone** [comment]
Neato, I still like the idea of renaming the tag to "Eerie Signal" to lure people into DEATH VALLEY

**Comment by PKPenguin321** [comment]
back in ye olde days of telesci I would have my partner in crime at the console hold and constantly refresh a GPS and tell him to warp me back when I set my GPS tag to HELP

this would be funny to see people communicating over

**Comment by Bawhoppen** [comment]
I kind of like the idea of the name being more restrictive, It feels more immersive that way

**Comment by ExcessiveUseOfCobblestone** [comment]
My argument around immersion is "They've had scrolling text on small digital devices since I was born, I think they'll have that in 2557 too"

**Comment by Bawhoppen** [comment]
space dark ages

**Comment by Repukan** [comment]
But now people will write Stranded or Spaced instead of SHIT

👎

**Comment by ExcessiveUseOfCobblestone** [comment]
did someone delete my earlier post!

THEY (whoever they are) WILL NOT DIVIDE US!

**Pull request merged**
