### PR TITLE
Makes admin midis great again.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
fixes them not queuing.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
OOPS. It worked on goon I swear.

**Comment by MrStonedOne** [comment]
We use datum sounds, they use sound(). sound() overrides all the other sound settings in the datum when it re-creates it, so you have to do it this way.

**Comment by Incoming5643** [comment]
Latest version of this pull I can't hear anything, even self uploaded sounds. This happens with pref on and the volume maxed

**Comment by Dorsisdwarf** [comment]
I never found any bugs or problems with sounds not queing yesterday, is this new?

**Comment by Incoming5643** [comment]
ADMIN LOG: Incoming/(Incoming) played sound html>

**Pull request closed without merging**
