### PR TITLE
Cloaks are now cosmetic neck slot items

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Cloaks are now cosmetic items that can be worn in the neck slot, allowing you to wear them over armour.
/:cl:

Backpacks and hair now layer over neck items, which I think makes sense anyway.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@TechnoAlchemisto 

Is this okay with you, someone kept requesting it in OOC but I don't have very strong feelings on it either way

**Comment by KorPhaeron** [comment]
I do think it looks kinda cool with a cloak+hardsuit though just like one of my english wargames

**Comment by TechnoAlchemisto** [comment]
yes, although this will make implementing hoods harder but I honestly was probably not going to get around to it

**Comment by KorPhaeron** [comment]
You could just make it toggle the icon to include a hood on alt click now since it's cosmetic only

**Comment by PKPenguin321** [comment]
It isn't cosmetic only, it has armor values

**Comment by KorPhaeron** [comment]
I forgot to delete them also they don't mean anything since nothing checks for neck armour

**Comment by PKPenguin321** [comment]
Unless that got scrapped in the transition from jumpsuit attachment to neck slot, it does indeed check for armor. It was added not too long ago

**Comment by kevinz000** [comment]
@PKPenguin321 feature

**Comment by jughu** [comment]
Finnaly we can use jetpacks with cloaks IN STYLE

**Comment by jughu** [comment]
Also what about bedsheets

**Comment by phil235** [comment]
Are neck items shown above suits? above backpack?

**Comment by KorPhaeron** [comment]
@phil235 

Yes to both, but come to think of it I didn't remember to see how they interacted with belts

**Comment by phil235** [comment]
code/_DEFINES folder

**Comment by jughu** [comment]
@KorPhaeron can you do this for bedsheets too?

**Comment by WJohn** [comment]
Shouldn't capes be these, too?

**Comment by KorPhaeron** [comment]
@phil235 

Not sure why they were in misc.dm instead of layers.dm, but thanks

**Comment by KorPhaeron** [comment]
@jughu 

Someone else can do that in another PR if they want to

**Comment by ExcessiveUseOfCobblestone** [comment]
Are you able to `HIDE_HAIR` and whatnot with neck slot items? Hooded cloaks and similar items may need this.

**Comment by RemieRichards** [comment]
@ExcessiveUseOfCobblestone the hood is a hat, a separate item.

**Comment by Supermichael777** [comment]
the fun thing with clothing flags is that you can do anything with anything

This can lead to madness(shoes hiding hair).

**Pull request merged**
