### PR TITLE
Gives everyone some cake and a balloon for my birthday tomorrow :)

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
[Tin](https://youtu.be/gi0LpboLdCg)
## Why It's Good For The Game
mario-birthday
## Changelog
:cl: Wallem
add: You're all invited to my birthday party :)
/:cl:

### CODE REVIEW

**Comment by krimmity** [comment]
merge this immediately

**Comment by tralezab** [comment]
## Wallemations can't afford this Birthday unfortunately

image

**Comment by Wallemations** [comment]
maxresdefault

**Comment by ZephyrTFA** [comment]
@tralezab I will cover part of the cost

**Pull request closed without merging**
