### PR TITLE
Buildable Rechargers!

### PR DESCRIPTION
**Pull request by GunHog**
- Rechargers can now be constructed/deconstructed as a machine. Requires
  the board and a capacitor.
- Rechargers can now be upgraded with superior capacitors to increase
  recharge rates!

Panel open state sprite by @WJohn!

### CODE REVIEW

**Comment by Razharas** [comment]
CL

**Comment by KorPhaeron** [comment]
I'd consider making the board cost some kind of mining material so you cant just churn 30 out as soon as a blob is spotted.

Cool stuff though

**Comment by Lumipharon** [comment]
rechargers will be rediculously good with t4 parts, eh.

**Comment by GunHog** [comment]
If it is really a concern, I could go for gold. But I cannot see this comparing to the rapid-fire emitters, which would be considered a superior alternative if blobs strike.

**Comment by AnonymousNow** [comment]
Neat.

**Comment by bgobandit** [comment]
emitters are a superior alternative but good luck getting a crew competent to set it up, whereas any chucklefuck can pick up a gun and find a recharger

mining mat pls

**Comment by kevinz000** [comment]
Finally.
I was getting sick of the recharger bugs.
Now if one breaks I can just get another made
Gunhog is the best :^)

**Comment by GunHog** [comment]
The design now requires gold, tech requirement and origin adjusted to be consistent with the other circuits that take gold.

**Comment by Iamgoofball** [comment]
>requires gold

no

ps. add a Matter Bin upgrade that increases the amount of things you can recharge at once

**Comment by Razharas** [comment]
Changelog @GunHog

**Comment by GunHog** [comment]
Added. @Iamgoofball I personally would prefer it that way, but I do not want people yelling at me! If you want to change it after this is merged, I will not have any objection. As for the matter bin idea, I would want to have a UI for that so I can select the gun I want to remove, but that sort of extends outside this PR. It is a fun idea though!

**Comment by GunHog** [comment]
<b>I would like a consensus here.</b>

Should the board require gold? Only AI modules have this cost, and it might not make sense here. I will decide on a combination of response count and quality of argument.

**Comment by Lumipharon** [comment]
the only time where being able to make them without gold can really be abused is blob.

**Comment by Razharas** [comment]
Im consensusing this

**Pull request merged**
