### PR TITLE
tgui 4.0

### PR DESCRIPTION
**Pull request by stylemistake**
> Continuation of #50912

Let's go step by step.

## Window Pooling

> Originally written by @actioninja

Avoids closing browser windows in favor of hiding them and later injecting new interfaces into them.

Why?

Setting windows to visible/invisible is much faster than loading new browser windows for a variety of reasons including caching and also just that byond browse calls as slow as hell.

The practical effect of this is that windows now open and fully render *much* faster. Initial open can take 1-3 frames while full render can take 5-10 frames. This is a significant speedup from previously and makes windows feel like the open nearly instantly.

On top of that, the lack of browse calls results in no client hitching on close, and very minimal client hitching on open.

Video demo: https://file.house/EhO6.mp4

The initial open looks as before because that is creating a new window. All subsequent opens use the recycled window and are much faster as a result.

Caveats:
- Windows closed via Alt+F4 do not hide and fully destroy, preventing them from being recycled.
- Users of simple/non-fancy mode largely cannot make use of this because we can't override the close button functionality. Auto-close due to distance still will, however.

## Client-side window metadata

Window title and width/height are now defined on the client-side, which enables usage of hot reload to experiment on different window sizes, which is far quicker than recompiling and restarting the server. You can also compute them based on the data 

```js
<Window
  title="Turret Control"
  width={800}
  height={600} />
```

## Client-side window geometry management

Previously, this was the domain of BYOND skin code, which automatically saved window position and size based on the window id. But now it's useless, because windows are pooled and reused. BYOND no longer can automatically do these things for us.

Solution was a complete client-side reimplementation of these things, and well, it just works!

### `ui_interact()`

**Before:**

```dm
/obj/machinery/porta_turret/ui_interact(mob/user, ui_key = "main", datum/tgui/ui = null,
		force_open = FALSE, datum/tgui/master_ui = null, datum/ui_state/state = GLOB.default_state)
	ui = SStgui.try_update_ui(user, src, ui_key, ui, force_open)
	if(!ui)
		ui = new(user, src, ui_key, "PortableTurret", name, ui_x, ui_y, master_ui, state)
		ui.open()
```

**After:**

```dm
/obj/machinery/porta_turret/ui_interact(mob/user, datum/tgui/ui)
	ui = SStgui.try_update_ui(user, src, ui)
	if(!ui)
		ui = new(user, src, "PortableTurret")
		ui.open()
```

Constructor for `/datum/tgui` still accepts `title`, `ui_x` and `ui_y` parameters, but now they are optional.

Parameters `ui_x`, `ui_y` are now **deprecated**, but will remain in the function signature for backwards compatibility with the older codebases. This should make the transition a little bit smoother for tg downstreams.

### `ui_assets()`

This new proc simplifies the process of sending assets (such as spritesheets) to tgui.

This is all you have to do now to deliver a spritesheet datum to tgui:

```dm
/obj/item/paper/ui_assets(mob/user)
	return list(
		get_asset_datum(/datum/asset/spritesheet/simple/paper),
	)
```

This removes the need to inject stylesheets via `ui_base_html` and to manually send assets in `ui_interact` proc.

### `ui_state()`

This proc can be used to specify the default tgui state, since we removed this functionality from `ui_interact`.

```dm
/obj/item/paper/ui_state(mob/user)
	return GLOB.default_state
```

## `act(action, payload = {})` is now json-encoded.

Yes, you can send full-blown data structures in the payload, and they deserialize into DM lists as you would expect.

```js
act('setFilter', {
  name,
  resources: ['iron', 'plasma'],
  flags: {
    giant_meatball: false,
  },
});
```

## `/datum/tgui_window`

> TBD

> Fixes the "whitescreen" and "stuck tgui" problems.

## Web Storage abstraction

> TBD

> Web Storage abstraction in located in `common/storage`.

## New Hotkey API

> TBD

**Changed hotkeys:**

- **F11** - Toggle debug layout
- **F12** - Toggle KitchenSink

## New development build indicator

This green icon now makes it clear which build you're currently using, and functions as a kitchen sink toggle.

image

## Other Changes

- Logging Redux middleware, which allows seeing what actions are being dispatched while in `--debug` mode.
- Fixed some bugs in PaperSheet UI.

## Changelog
:cl:
refactor: tgui windows should load faster after an initial load, if using the fancy mode. Please report any breakages.
/:cl:

### CODE REVIEW

**Comment by stylemistake** [comment]
Tomorrow I will make it ready for testmerge, I'm pretty positive it will go well this time.

**Comment by ike709** [comment]
image

you lied

**Comment by PowerfulBacon** [comment]
good stuff

**Comment by ShizCalev** [comment]
```
[xxxxx] Runtime in bounty_board.dm, line 89: bad index
proc name: ui act (/obj/machinery/bounty_board/ui_act)
usr: XXXXXXXX/(XXXXXXXXX)
usr.loc: (XXXXXXXXX)
src: the bounty board (/obj/machinery/bounty_board)
src.loc: the floor (151,117,4) (/turf/open/floor/plasteel/white)
call stack:
the bounty board (/obj/machinery/bounty_board): ui act("createBounty", null, /datum/tgui (/datum/tgui), /datum/ui_state/default (/datum/ui_state/default))
/datum/tgui (/datum/tgui): on message("createBounty", null, /list (/list))
/datum/tgui_window (/datum/tgui_window): on message("createBounty", null, /list (/list))
tgui Topic("tgui=1&window_id=tgui-window-1...", /list (/list), null)
Jaredfogle (/client): Topic("tgui=1&window_id=tgui-window-1...", /list (/list), null)
```

**Comment by ShizCalev** [comment]
```
[xx:xx:xx] Runtime in airalarm.dm, line 379: bad index
proc name: ui act (/obj/machinery/airalarm/ui_act)
usr: xxxxx/(xxxxx)
usr.loc: (AI Chamber (150,32,4))
src: Kitchen Air Alarm (/obj/machinery/airalarm)
src.loc: the floor (152,138,4) (/turf/open/floor/plasteel/cafeteria)
call stack:
Kitchen Air Alarm (/obj/machinery/airalarm): ui act("reset", null, /datum/tgui (/datum/tgui), /datum/ui_state/default (/datum/ui_state/default))
/datum/tgui (/datum/tgui): on message("reset", null, /list (/list))
/datum/tgui_window (/datum/tgui_window): on message("reset", null, /list (/list))
tgui Topic("tgui=1&window_id=tgui-window-1...", /list (/list), null)
xxxxx (/client): Topic("tgui=1&window_id=tgui-window-1...", /list (/list), null)
```

**Comment by Arkatos1** [comment]
Just a heads up - I noticed that ui width and height were accidentally switched up for PortableTurret.js and TurretControl.js, resulting in quite a funny view of them not fitting window at all.

**Comment by san7890** [comment]
Comes up whenever I try to stamp paper.

> TypeError: Object expected
>    at n.findStampPosition (http://127.0.0.1:51923/tmp83872/tgui.bundle.js:1:611884)
>    at n.handleMouseMove (http://127.0.0.1:51923/tmp83872/tgui.bundle.js:1:612073)
>    at q (http://127.0.0.1:51923/tmp83872/tgui.bundle.js:1:202177)
>    at Anonymous function (http://127.0.0.1:51923/tmp83872/tgui.bundle.js:1:201843)
> User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)

**Comment by kriskog** [comment]
#52203
#52190

Removed the testmerge for now, as it has issues and conflicts.

**Comment by actioninja** [comment]
@ike709 there's potentially going to be ANOTHER big refactor depending on what happens with inferno hooks and if their performance viability improves.

get dabbed on downstreams

**Comment by ZeWaka** [comment]
Would the CDN improvements be attached to this PR, or a tgui 4.x PR?

**Comment by Tlaltecuhtli** [comment]
on the test merge i m still getting the good ol windows disappearing either first time opening or second time

**Comment by ShizCalev** [comment]
this was a day or so ago, forgot to press comment, so not sure if you fixed it already
```
[06:34:21] Runtime in tgui.dm, line 146: Cannot execute "main".process status().
proc name: try update ui (/datum/controller/subsystem/tgui/proc/try_update_ui)
usr: RainyEyes/(Lord Willie Dustice)
usr.loc: (Genetics Lab (138,101,2))
src: tgui (/datum/controller/subsystem/tgui)
call stack:
tgui (/datum/controller/subsystem/tgui): try update ui(Lord Willie Dustice (/mob/living/carbon/human), the internal antenna (/obj/item/radio), "main")
the internal antenna (/obj/item/radio): ui interact(Lord Willie Dustice (/mob/living/carbon/human), "main", null, 0, null, /datum/ui_state/deep_inventory... (/datum/ui_state/deep_inventory_state))
the internal antenna organ (/obj/item/implant/radio/antenna): activate("action_button")
the internal antenna organ (/obj/item/implant/radio/antenna): ui action click(Lord Willie Dustice (/mob/living/carbon/human), Activate (/datum/action/item_action/hands_free/activate))
Activate (/datum/action/item_action/hands_free/activate): Trigger()
Activate (/obj/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=15;icon-y=18;left=1;scr...")
RainyEyes (/client): Click(Activate (/obj/screen/movable/action_button), null, "mapwindow.map", "icon-x=15;icon-y=18;left=1;scr...")
```

**Comment by stylemistake** [comment]
@ShizCalev good catch, that's been fixed.

**Pull request merged**
