### PR TITLE
Remove tiered canister construction

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

In https://github.com/tgstation/tgstation/pull/66210 we removed canister tiers, but didn't change the construction code. Currently you still have to build an unfinished frame with 5 iron, 'upgrade' it to tier 1 with another 5 iron, then complete it.

This combines it all into a single 10 iron recipe.

## Why It's Good For The Game

Eliminates the extra steps in canister construction, since you can't upgrade above tier 1 any more anyways.

## Changelog

:cl: LT3
qol: Canisters can now be built in one step, no upgrading required
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Thanks for leaving the broken canister as a fluff. I assume it provides an iron sheet on deconstruction.

**Comment by MTandi** [comment]
There is a couple of other "pointless" recipes - that have an unnecessary intermediate step. Maybe we should also remove those if we remove it for canister.

- Hygienebot Assembly
- Scooter frame

**Review by Maurukas — APPROVED** [review]
Maps good. Excellent use of fluff.

**Comment by Wallemations** [comment]
_THIS_ should be a QOL change

**Comment by lessthnthree** [comment]
> Thanks for leaving the broken canister as a fluff. I assume it provides an iron sheet on deconstruction.

Yeah, the fluff provides an iron sheet on decon.

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
