### PR TITLE
buffs aggressive grabs by a small amount

### PR DESCRIPTION
**Pull request by saprasam**
## About The Pull Request

i decided to decrease the aggressive grab breakout chance by 20%, making it more viable and making slight adjustments, as aggressive grabs are now completely useless unless you are extremely lucky and it heavily stunts the (already) weak hand to hand combat as aggressive grabs
also lowers the stamina decrease and CD reduction

## Why It's Good For The Game

makes aggressive grabs useful again, but still makes it easier to break out of, as the current state of aggressive grabs is sad and pathetic.
i absolutely hope this doesn't break anything

## Changelog
:cl:
balance: makes aggressive grabs slightly harder to break out of.
/:cl:

### CODE REVIEW

**Comment by XDTM** [comment]
You should probably also mention the resist CD reduction and the stamina damage reduction in the PR body

**Comment by necromanceranne** [comment]
Also, it's not ideal but the 60% was mostly so it doesn't get weird with numbers. Remember, the altered_grab_state is a division. So when they're on the floor it's a 13.34%. Which is the kind of weird probability values I wanted to avoid.

Quite honestly, make it 30% just so the numbers are clean and I don't feel so anxious about it. The difference is literally a 3.34%, rounded, when you've put them at killgrab (or an aggressive grab on the floor, a neckgrab). It barely matters.

You could also maybe just kill off the heightened grabstate from the target of the grab being prone, which could also help justify having the lower resist chance and also fix what is a glaring issue already in the grab system, which is that neckgrabs effectively just upgrade to killgrabs.

Also boy grabs suck as an rng based system.

**Comment by Fikou** [comment]
> Also boy grabs suck as an rng based system.

make it so you have to wiggle around in a certain pattern to get out of grabs

**Comment by ATH1909** [comment]
> You could also maybe just kill off the heightened grabstate from the target of the grab being prone

again, are you sure that that's even a thing? being prone != resting

**Comment by necromanceranne** [comment]
I am pretty sure and if it wasn't that'd be a really dumb mechanic since you need to deliberately rest. @ATH1909

**Comment by ExcessiveUseOfCobblestone** [comment]
what is useful? I don't want a witty oneline like "not current iteration", I'd like someone to explain what they want grab to be relative to the rest of combat balance from a design POV.

I don't want to spaghetti test, and even more I don't want grabs to be a practical GBJ like they were before the nerf.

**Comment by ATH1909** [comment]
> I am pretty sure and if it wasn't that'd be a really dumb mechanic since you need to deliberately rest. @ATH1909

I'm pretty sure about my interpretation as well.

**Comment by necromanceranne** [comment]
Big shrug, it sucks if it is working, and if it isn't...why keep it?

**Pull request closed without merging**
