### PR TITLE
Ion storm improvements

### PR DESCRIPTION
**Pull request by MrPerson**
Ion storms are boring as shit. Let's make them more exciting and chaotic instead of just "welp better reset the AI".

:cl:
experiment: Ion storms have several new additions:
add: 25% chance to flatly replace the AI's core lawset with something random in the config. Suddenly the AI is Corporate, deal w/ it.
add: 10% chance to delete one of the AI's core or supplied laws. Hope you treated the AI well without its precious law 1 to protect your sorry ass.
add: 10% chance that, instead of adding a random law, it will instead replace one of the AI's existing core or supplied laws with the ion law. Otherwise, it adds the generated law as normal. There's still a 100% chance of getting a generated ion law.
add: 10% chance afterwards to shuffle all the AI's laws.
/:cl:

All of these stack so you could wind up going from Asimov to Paladin w/o the first law and w/ the last law replaced with THE SHUTTLE CANNOT BE CALLED DUE TO FIVE NINJAS. All the values are easy to tweak if you guys want them higher or lower or whatever.

Custom admin-sent and other fake ion storms (devils) will just add the law and have no chance of doing any of the bonus stuff.

Removed the admin verb to send an ion storm since you can just use the events panel.

Cleaned up some of the law-adding backend. Hopefully there's no double showing of the AI's laws after a lawchange as a result of this.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Doesn't the admin verb allow custom law adding, though?

**Comment by MrPerson** [comment]
That's a different verb

**Comment by PKPenguin321** [comment]
Oh, cool

**Comment by ChangelingRain** [comment]
How about also randomly shifting law priority?
So, with asimov, you could end up with

**Comment by TehZombehz** [comment]
This'll probably just increase the frequency of rogue AIs, people killing an AI instead of resetting it, or both. But it's cool!

**Comment by MrPerson** [comment]
I like that shuffle idea, I'm gonna do that

**Comment by AnturK** [comment]
So, assuming merging this should wait ?

**Comment by RemieRichards** [comment]
yes

**Comment by MrPerson** [comment]
Added shuffling at a 10% chance

**Comment by ChangelingRain** [comment]
I think it might be good to reduce the chance of an actual ion law happening because holy fuck this could very quickly make the AI a terrifying murderer.

**Comment by MrPerson** [comment]
I could do that. I could also make it only pick one thing to do at a time. I need to see how chaotic this shit actually is though.

**Comment by AnturK** [comment]
Chaos from events is fine. We don't have enough meaningful ones.

**Pull request merged**
