### PR TITLE
Stepping on horns now invokes the proper experience

### PR DESCRIPTION
**Pull request by Incoming5643**
Now the clown can honk even if you disable its hands.
# NotDeadJustBusy
# ThisIsOverADecadeTooLate

### CODE REVIEW

**Comment by bgobandit** [comment]
https://www.youtube.com/watch?v=_FWMAIZdxdY

**Comment by Incoming5643** [comment]
You've messed with the natural order

**Comment by Dorsisdwarf** [comment]
https://www.youtube.com/watch?v=PcRyjkYdDxM

**Comment by Dorsisdwarf** [comment]
Why are those buttons so *near* each other

**Comment by Shapsy** [comment]
Maybe it was your subconscious trying to kill it

**Comment by Miauw62** [comment]
:postal_horn:

**Comment by Jalleo** [comment]
:horse: :gun: :guardsman: :anguished:

**Comment by Anonus** [comment]
Horn pile? Horn pile.

**Comment by RandomMarine** [comment]
Better yet. Airhorn pile.

**Comment by CPTANT** [comment]
ohw god we need tuned bike horns

**Comment by JJRcop** [comment]
bike horns-as-an-instrument! why didn't we think of this before?!

**Comment by Incoming5643** [comment]
https://www.youtube.com/watch?v=2sIKYlxDxwE

**Pull request merged**
