### PR TITLE
Final Solution for one shitty meme

### PR DESCRIPTION
**Pull request by Core0verload**
This PR removes skub.

I'm not really anti-skub, but i'm totally anti-shitty-meme. We need more references to sci-fi, not to internet culture.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
yea this meme really didn't actually have a place tbh

**Comment by Cheridan** [comment]
someone get this anti-skubber out of my face

**Comment by MrPerson** [comment]
You should probably remove the sprite from the dmi.

**Comment by Core0verload** [comment]
Done.

**Comment by PKPenguin321** [comment]
:sob:

**Comment by Zilenan91** [comment]
:+1: 

Unless someone gives it a function (like it making a mess if you throw it at someone) there's no reason to have it in the game

**Comment by Core0verload** [comment]
Yes.

**Comment by TankNut** [comment]
:+1: I didn't mind the whole skub thing at first, but then I had to deal with security and everyone else beating the shit out of each other because of it.

**Comment by drynwyn** [comment]
that's the goddamn point of skub you filthy anti-skubber

PROSKUB PRIDE

**Comment by lzimann** [comment]
dead meme

**Comment by ike709** [comment]
>I'm not really anti-skub

That's exactly what an anti-skubber would say

**Comment by Core0verload** [comment]
Conflicts resolved. Ready to merge.

**Comment by PKPenguin321** [comment]
this is like the holocaust but worse

**Comment by Chocobro** [comment]
we'll never forget you, skub

**Pull request merged**
