### PR TITLE
Makes create antags check for on station.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
admin: Create antags now checks for people being on station before applying.
/:cl:

All others check for it, you don't want people on charlie station or syndicate lavaland base get antag out of nowhere.

I'm aware this applies to miners on mining as well but that's usually one or two people, this is the cleanest solution.

### CODE REVIEW

**Comment by Repukan** [comment]
Doesn't this mean you can meta miners not getting survivalist during wizard or antag after a mulligan?

**Comment by DaxDupont** [comment]
@Repukan this is for the create antag panel, not mulligan.

**Comment by Cyprex** [comment]
>All others check for it, you don't want people on charlie station or syndicate lavaland base get antag out of nowhere.
You don't?

**Comment by Cyberboss** [comment]
Nah, this is removing options. Admins have one job

**Comment by optimumtact** [comment]
what about changelings and the rest?

**Comment by optimumtact** [comment]
also this is really lazy bugfixing, we know the list of station vs non station roles and can easily limit the candidates list to be station roles only, not leaving people who space explore high and dry on the antag front for no reason

**Pull request merged**
