### PR TITLE
Remove detain mode as a toggleable switch for end user

### PR DESCRIPTION
**Pull request by ghost**
:cl: Chunkr
del: Removed detain mode from Securitrons & ED-209 Security Robots
/:cl:

Stunning people permanently is terrible, you can find the previous discussion over at #10282

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Is it possible to have detain mode arrest and "pull" the player at the cost of making it so beepsky can't stun or move while they're pulling someone?

**Comment by PKPenguin321** [comment]
Please no, Armsky locking people down in the armory is funny as fuck every time

**Comment by Fox-McCloud** [comment]
Terrible feature, IMO; good riddance.

**Comment by YakumoChen** [comment]
Makes it easier to deal with clearly harmful people and armoury looters as AI. Detain mode is useful.

**Comment by Chnkr** [comment]
@PKPenguin321 Detain mode is still available trough var-editing, this just removes the setting for end users.

@ExcessiveUseOfCobblestone That would be nice, but I'd rather do that in a future PR as that requires more work, and the sectrons could use a rewrite tbh.

**Comment by KorPhaeron** [comment]
But it was a good PR

**Comment by Chnkr** [comment]
I'm no longer interested in contributing to /tg/station, feel free to copy the PR and submit it as your own.

**Comment by PKPenguin321** [comment]
RIP

**Pull request closed without merging**
