### PR TITLE
Once again overhauls revenants

### LINKED ISSUE #12065: Revenant ability costs are wrong
Defile lists as 20 to unlock and 10 to cast but it isn't either of those

### PR DESCRIPTION
**Pull request by ChangelingRain**
> Instead of supporting health and essence, with health being three times essence, essence is tripled and now acts as revenant health AND ability costs.
> Draining a target is slightly shorter, but if the target is dragged away while you are draining, the drain will fail.
> If you get exceptionally lucky, you can gain a higher essence regen cap from draining - this requires the target mob to have a ckey, be alive, and for RNG to favor you.
> You can no longer abuse the spawns in reveal and stun to be invisible or move while draining a target(this is really awful I want a better way to do it)
> Revenant ectoplasm has a new icon.
> Overload lights now has a wider range, but only shocks people adjacent to lights.
> Overload lights now has purple lightning and a new icon.
> Defile damages windows slightly less, rusts walls, and makes lights flicker for somewhat longer.
> Defile has a new icon.
> Malfunction no longer disables bots after emagging them.
> Malfunction has a new icon and causes purple sparkles on emagged machines and bots.
> Fixes #12065

SHOCKING
If I got anything wrong just punch me in the face because I should know better by now.

### CODE REVIEW

**Comment by Niknakflak** [comment]
Overload lights is still pretty useless with this

**Comment by Anonus** [comment]
This may or may not fix revenants randomly dying, if it gets merged we'll find out, but the bug is impossible to replicate consistently.

**Comment by Metacide** [comment]
Just as a vaguely related question, are revenants meant to be able to emag/EMP cloners, bursting the people cloning and removing their soul from any body in the round? Think I saw that earlier today, and it looked like a really stupid and irritating way to be killed permanently, and is pretty much uncounterable.

**Comment by Anonus** [comment]
It's not really intended, no. I'll make it not EMP clone pods.
Holy water is a good way to keep revenants away from stuff, yes.

**Comment by Metacide** [comment]
Oh great, thanks. :+1:

**Comment by Xhuis** [comment]
Neat! :+1:

**Comment by Zilenan91** [comment]
Can you give them night vision?

**Comment by TehPear** [comment]
They can really use night vision as they can not see anything in the dark.

**Comment by Anonus** [comment]
They HAVE night vision already, someone added it.

**Pull request merged**
