### PR TITLE
Revert "[s]Revert "Revert "Revert "Revert "Revert "Revert "Typos in syndicate uplink descriptions"""""""

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Reverts tgstation/tgstation#27998

### CODE REVIEW

**Comment by kevinz000** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by ChangelingRain** [comment]
kor no, bad.

**Comment by RemieRichards** [comment]
Who's a good Kor, you are! yes you are!

**Comment by KorPhaeron** [comment]
RULE BRITANNIA

**Pull request merged**
