### PR TITLE
[s] [testmerge only please] Temporarily reverts goonchat while the js loading problem is solved

### PR DESCRIPTION
**Pull request by Iamgoofball**
See title

### CODE REVIEW

**Comment by randomperson777** [comment]
Dear goofball,  you have my deepest thanks

**Comment by MrStonedOne** [comment]
What js loading problem?

**Comment by Supermichael777** [comment]
one would presume that goof ported this javascript implementation directly from goon and that its outdated

**Comment by Tacolizard** [comment]
What js loading problem?

**Comment by lzimann** [comment]
Should be fixed with MSO's no asset cache verify.

**Pull request closed without merging**
