### PR TITLE
adds directional helpers for empty fire axe and mech removal crowbar cabinets

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
title. it's mostly so they can be used conveniently in areas you don't want to put fireaxes, but do want an empty cabinet for reasons.
## Why It's Good For The Game
more flexible options for mappers, more convenient than making directional variants yourself. it's what the helper is for
## Changelog
:cl:
qol: gives empty fireaxe and mech removal crowbars cabinets directional helpers
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
could you try doing an updatepaths that fixes all of these? you can look at something here if you would like an idea on what might need to be written (beware it's a slight doozy) https://github.com/tgstation/tgstation/pull/70277/files#diff-f6487fd7c82785c315e0425887c51803d825a5b131a372de8e206bd37af0f57f

**Comment by CoiledLamb** [comment]
> could you try doing an updatepaths that fixes all of these? you can look at something here if you would like an idea on what might need to be written (beware it's a slight doozy) https://github.com/tgstation/tgstation/pull/70277/files#diff-f6487fd7c82785c315e0425887c51803d825a5b131a372de8e206bd37af0f57f

oooh that is a bit messy. i can see about it though, it is interesting.
i think it might be faster to just check every example that exists already, because i doubt many empty frames are mapped in. most every map uses a full frame, iirc? same for mech removal crowbars

**Comment by san7890** [comment]
> i think it might be faster to just check every example that exists already, because i doubt many empty frames are mapped in. most every map uses a full frame, iirc? same for mech removal crowbars

it's only messy because it has all the lights, you only need a few lines tops. you could do a manual audit but it's better to do an updatepaths because
A) it's faster (it might be slow to start since this is probably your first time doing an updatepaths, but a machine doing this menial task will always be faster than schlopping around StrongDMM for every instance of these paths (i speak from experience for when I manually audited every poster (it was a mistake)))
B) it's more resilient in case your map conflicts (very important since this is very likely when you edit major station maps (you can revert the commit with the updatepaths change and try again when you merge master))
C) it's kinder to downstreams
D) it's kinder to people working on out of rotation maps

**Comment by CoiledLamb** [comment]
> > i think it might be faster to just check every example that exists already, because i doubt many empty frames are mapped in. most every map uses a full frame, iirc? same for mech removal crowbars
> 
> the example I gave messy because it has _all_ the lights, you only need a few lines tops. there's likely better examples (i think I did one for signs a while ago) in the updatepaths folder that might work better for you, or give you a better idea on what needs to be done.
> 
> you could do a manual audit but it's better to do an updatepaths because
> 
> A) it's faster (it might be slow to start since this is probably your first time doing an updatepaths, but a machine doing this menial task will always be faster than schlopping around StrongDMM for every instance of these paths (i speak from experience for when I manually audited every poster (it was a mistake))) B) it's more resilient in case your map conflicts (very important since this is very likely when you edit major station maps (you can revert the commit with the updatepaths change and try again when you merge master)) C) it's kinder to downstreams D) it's kinder to people working on out of rotation maps

oh okay this reasoning is based. it's my second time doing updatepaths (did em for surgery trays cause it was 100% the right call), i've just never done a wallmount. my confusion is mostly how the path would know which directional to use. i'll bug you on discord about it 👍

**Comment by san7890** [comment]
>  my confusion is mostly how the path would know which directional to use

you mean how the UpdatePaths Script would know which directional to replace an instance of an item with? You just sorta have to write for all the major cases and it's no big deal if it misses some, just a nicety for the lowest common denominators

**Comment by CoiledLamb** [comment]
i overcomplicated it. done now, thanks san!

**Pull request merged**
