### PR TITLE
New door PR that totally isn't a grudge on another's PR, i swear!

### PR DESCRIPTION
**Pull request by Cuboos**
This isn't in any way made to spite another PR that was made by some sort of salty cactus fellow. This was my idea all along and you can't prove it wasn't!

Also the sounds for you to preview: 
[Door Open](https://dl.dropboxusercontent.com/u/9654207/New%20door/AirlockOpen.ogg)
[Door Close](https://dl.dropboxusercontent.com/u/9654207/New%20door/AirlockClose.ogg)
[Denied Beep](https://dl.dropboxusercontent.com/u/9654207/New%20door/DeniedBeep.ogg)
[Bolts up](https://dl.dropboxusercontent.com/u/9654207/New%20door/BoltsUp.ogg)
[Bolts Down](https://dl.dropboxusercontent.com/u/9654207/New%20door/BoltsDown.ogg)
[Unused click sound](https://dl.dropboxusercontent.com/u/9654207/New%20door/DoorClick.ogg)
EDIT: fixed the link to the Bolt Up.

### CODE REVIEW

**Comment by Buggy123** [comment]
:+1: no salt detected

**Comment by xxalpha** [comment]
You pasted bolts down twice.

**Comment by Metacide** [comment]
Close one seems very nice.

Beep at the beginning of open is a bit piercing but the rest seems neat. :+1:

**Comment by Cuboos** [comment]
It's not as bad in game, sounds get compressed just a bit so quality goes down.

**Comment by callanrocks** [comment]
It sounds too 'good' for the deathtrap hellhole.

**Comment by KorPhaeron** [comment]
That beep for the open one will be very annoying in medbay/other high traffic areas. Sounds cool though.

**Comment by xxalpha** [comment]
The denied sound is fine, but could do without that initial 'tss' or tsh' or whatever it is. The closing airlock is fine too. The rest I don't really like. I always imagined the airlock bolts going down with sort of a metallic stomp.

**Comment by Incoming5643** [comment]
As I said before, I don't think changing one of the most heard sounds in the station is something that ever really needs to be done.

**Comment by Niknakflak** [comment]
I like door close and denied beep.  The bolts one sounds like a car door and the beep at the door open seems needles.

**Comment by Cuboos** [comment]
Alright, reverted the open sound back to the original airlock open sound. I kinda liked the beep but oh well... Leaving the bolt sounds they way they are since feedback for them is slightly more positive than negative.

**Comment by duncathan** [comment]
Personally, I'd rather leave close as is too, but that's just me. 
:+1: for sure for bolts and denied though; the extra feedback is great

**Comment by Steelpoint** [comment]
This is a good change, especially the bolt sounds.

**Comment by Cheridan** [comment]
@Incoming5643 sacred calves were meant to be slaughtered

**Comment by Incoming5643** [comment]
oh lawd

**Pull request merged**
