### PR TITLE
Posibrain possession fix

### LINKED ISSUE #11331: Multiple brains entering a positronic brain
Witnessed a player who did in this in-game multiple times.
Apparently you get the prompt, wait until someone else takes over the brain and gets placed in a cyborg (or potentially an AI?) and then hit yes to become the brain which shoves you inside the newly made cyborg where the previous player was.  They can talk and such but not interact.

### PR DESCRIPTION
**Pull request by GunHog**
- Ghosts can no longer take the posibrain of another player, even if
  that player ghosts.
- Fixes a bug in which androids can gain additional players in the same
  body.
- Fixes #11331.

_100% player reference free PR_

<b>Probably works as intended. Probably.</b>

### CODE REVIEW

**Comment by Shadowlight213** [comment]
@GunHog a better way to fix the bug, would probably have the used var be reset if there is no one in the posibrain and the robotocist used it inhand, since it would allow the posibrain to be reused, but it wont be possible for the split personality bug to occur as the reset could not be performed if the posibrain is in a borg.

**Comment by GunHog** [comment]
Sorry I had not touched this in a while. Posibrains now be reset if used in-hand. (still untested because testing posibrains alone is a major pain)

**Comment by Shadowlight213** [comment]
@GunHog Just use the dummy client trick. Join your test game while signed in, then sign out of the byond pager and hit the join button again. You can then have two clients running on the same machine, with one being a guest. It works perfectly fine for testing things that need two clients.

**Comment by duncathan** [comment]
@GunHog status on this?

**Comment by GunHog** [comment]
It seems to be working okay. I cannot find any *obvious* problem with it, other than maybe having a use for a feedback message for ghosts trying to enter a used posibrain.

**Pull request merged**
