### PR TITLE
Minor syndicate tweaks

### PR DESCRIPTION
**Pull request by kilkun**
same as last PR but with the stuff removed

:cl:
add: The Syndicate raided an automaton factory and made off with a bunch of rejected GR3Y.T1D3 model androids.
tweak: Syndicate soft suit now has no slowdown
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
:+1: to first
:-1: to second as there's a hardsuit with no slowdown :^)

**Comment by kilkun** [comment]
there is not a hardsuit with no slowdown

you can turn the blood red hardsuit into a retarded useless mode with no slowdown but you lose space protection.

this makes the soft suit actually relevant

**Comment by ma44** [comment]
👍

**Comment by ExcessiveUseOfCobblestone** [comment]
Syndicate Blood-Red: `armor = list(melee = 40, bullet = 50, laser = 30, energy = 15, bomb = 35, bio = 100, rad = 50, fire = 50, acid = 90)`

Syndicate Normal: `armor = list(melee = 40, bullet = 50, laser = 30,energy = 15, bomb = 30, bio = 30, rad = 30, fire = 80, acid = 85)`

So basically your trade off is you don't have to micro the suit at all, get to have the best of both worlds [speed and space], and gain fire armor but you lose some radiation and acid protection? 

That doesn't just make it relevant, that makes it a direct upgrade [I would daresay the loss of 20 rad and 5 acid outweigh the other 3] AND gives normal traitors this benefit as well. I'm not sure how much they cost in the nuke uplink [or if you can even buy it] but I know they get at least one freebie on the shuttle. To be fair though you'll probably still just opt for the Elite so really my only concern is with Traitors who now have a slowdown-free spaceworthy outfit.

Also SNPCS are a roll of the dice [especially in multitudes]. You REALLY take a gamble with those.

**Comment by kevinz000** [comment]
>kilkun >balance
pick one

**Comment by AdamElTablawy** [comment]
SNPCs are extremely robust now

at least these aren't traitor SNPCs because the grenadespam on those things is a nightmare, but four or five SNPC greytiders can basically kick the shit out of one guy too fast for him to fight back

**Comment by PKPenguin321** [comment]
Dehydrated assistants with this will still be named "carp plushie," will still have the animation of a carp when they expand, will still have the same description, will still make a carp noise when used in-hand

SNPCs (carbon/human/interactive) are still in development and are not ready for implementation in the game. Just spawning something like five of them causes them to completely stop processing everything. As of right now, they are only useful for the occasional admin gimmick.

:-1:

**Comment by Kromgar** [comment]
Kor already made it so you can only bring megafauna by shuttle. Also he added a patch so megafauna don't heal on station so you can fuck right off with that shit.

**Comment by francinum** [comment]
@PKPenguin321 they're used already in the body-snatcher abductor organ.

**Comment by PKPenguin321** [comment]
Has that been used literally ever?

**Comment by anconfuzedrock** [comment]
remove armor first

**Comment by kilkun** [comment]
@PKPenguin321 I will address those issues in the next commit, thanks for the heads up. Also yes, synth organs are pretty common.

@ExcessiveUseOfCobblestone no insulation (this is an important aspect, I have been tesla'd to death 5 seconds after exiting the ship as an op wearing a soft suit), can't install a jetpack (don't underestimate how big saving back space is), etc. but I see your point, I don't know why the blh is nerfed the way it is, that makes 0 sense. will address in the next commit. also traitors can buy hardsuits anyways for more money.

the real question is why did ops get shafted so hard with their gear? starting with stetchies instead of 357s, blh nerfs (or red space suit buffs?), having to shell out for NOSLIPs. i can appreciate the fact that it might be a jab at capitalism with ops getting "microtransactioned" with their gear, but something tells me that isn't the case.

the real question is how i want to go about balancing one or the other without fucking up ops.

ALSO it should be a tactical choice between the two. Maybe soft suit offering better laser and stun protection while the hardsuit offers better bullet and melee protection?

**Comment by PKPenguin321** [comment]
That organ should probably be removed.

**Comment by kilkun** [comment]
no its fun and snpcs are great

just write off their bugginess as having poorly fabbed cpus or something.

**Comment by PKPenguin321** [comment]
maintaiiinerrrrrrs

**Comment by kilkun** [comment]
it'll be _fine_

**Comment by kilkun** [comment]
consider that if they weren't bugged to shit they would be worth a lot more than 15 tc because holy shit they can do a fuckton of damage if you get lucky.

**Comment by Haevacht** [comment]
The greytide snpcs are shitty, probably bug-ridden and IIRC they could attack at unrealistic speeds.

This is fucking stupid.

**Comment by KorPhaeron** [comment]
Atomic PRs please

**Comment by KorPhaeron** [comment]
Split it up

**Comment by kilkun** [comment]
reee

**Pull request closed without merging**
