### PR TITLE
Makes to_chat queue messages rather than immediately sending them

### LINKED ISSUE #38863: freezing and lags when many  messages happens
stuff like examinating someone with many traits, health analyzers causes freezes on client, someone clogging in disposal pipe can cause even  crashes from too much spam

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: ninjanomnom
fix: Chat spam should no longer lag or freeze the client
/:cl:

fixes #38863

Someone more experienced with the chat browser should really take a look at this

### CODE REVIEW

**Comment by deathride58** [comment]
A better way to reduce clientside lag from goonchat would be to reduce the maximum amount of messages that can be stored at once. The current limit is 2053 total messages, which is a metric fuckton of text for something with javascript being handled by Internet Explorer, which is known to have severe optimization issues. When goonchat adds in new messages, Internet Explorer has to re-enumerate the entire list of messages, which can cause severe lag if it's done too often, and if it's done after hitting the message cap, the list of messages has to be re-enumerated twice. Reducing the goonchat message limit to 100 should improve performance by a lot since IE won't have to re-enumerate as many messages, but if that option is taken, it might be wise to add in a way to configure the clientside message limit for those that want to be able to scroll through an hour's worth of chat history.

**Comment by ninjanomnom** [comment]
The issue isn't from goonchat, sending chat messages to the client individually has lagged the client when there are too many since long before goonchat.

**Comment by kevinz000** [comment]
apparently people get lagged out when you point blank them with buckshot :^)

**Comment by Dennok** [comment]
or when it step on the pile of the shards.

**Comment by Cyprex** [comment]
Dance machine is(was?) also laggy, presumably due to this.

**Comment by ninjanomnom** [comment]
You don't need to be listing all the possible ways to spam the chat

**Comment by factoryman942** [comment]
testmerged on bagil
pro: it stopped chatspam
con: it also stopped about half of all chat messages, including some from ooc

**Comment by ninjanomnom** [comment]
Naksu testmerged this without asking, it's not really ready for that

**Pull request closed without merging**
