### PR TITLE
Nukeop Outfits,Uplink gamemode override, Lone Operative event.

### PR DESCRIPTION
**Pull request by AnturK**
One PR because i got no time to split it right now.

Probably should make some kind of common spawn event  for all these spawn and forget ones.

### CODE REVIEW

**Comment by tuypo1** [comment]
lone operative would be cool

**Comment by Steelpoint** [comment]
So how does Lone Operative work?

I see its a Admin Only event, but what about mechanics?

Is it just spawning one person as a Op, with about 40+ TC's?

If you wanted to go full Solo Operater you could look into making a unique starting area for a solo op, with a more scaled down ship. To better fit the theme.

Otherwise I like the idea.

**Comment by AnturK** [comment]
Right now it's nothing fancy, spawns one person in full nukeop equipment, 20 TC and nuke code in station space. Will probably change the values/equipment a bit. Maybe i'll add some extraction device/microshuttle for getaways later.

**Comment by Steelpoint** [comment]
I took a look.

Overall its a neat and cool concept and idea, one that needs refinement, but a good one.

I do think making the Op start in small base, or inside a scaled down one man ship, would help in allowing them to ease into their equipment and get their bearings. But one step at a time.

**Comment by Dorsisdwarf** [comment]
So this event gives the nuke a definite code when it procs?

I like the idea of an assistant torturing an op for the nuke code so they can blow it to kingdom come themselves.

**Comment by Shadowlight213** [comment]
Fixes #6018

**Comment by PKPenguin321** [comment]
not sure how i feel about a side antag that can instantly end the entire round
sometimes it might be cool to see a really robust guy powering through all of sec by himself but if the crew doesn't realize he's there and they just kind of blow up for no reason and the round instantly ends, it might be kinda shitty
maybe make an announcement 10~ minutes after the lone op arrives?

**Comment by Steelpoint** [comment]
If being able to blow up the station, for a side antag, is too much perhaps look to making their objectives not focus on detonating the nuke.

**Comment by Dorsisdwarf** [comment]
Make the minimum time on the station nuke set to 10 minutes while he's alive.

**Comment by AnturK** [comment]
That's why it's just admin button for now, random event causing nuke-ending would be pretty bad.

**Comment by Shadowlight213** [comment]
@AnturK put it under the create antagonist button then. Having it be an event is going to cause someone to do rebalancing

**Comment by Razharas** [comment]
@AnturK 
This needs changelog and its good to go

**Comment by AnturK** [comment]
Bamp

**Pull request merged**
