### PR TITLE
Add the hos hat to ian

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl: 
imageadd: The Ian (and his lesser brethren) can now wear the HoS's cap.
/:cl:

Head of Bark

### CODE REVIEW

**Comment by F-OS** [comment]
you broke the code, first of all, do not change icon names, it fucks up a lot. 

second of all, you fucked up adding it. you need to define the dog fashion in /code/modules/clothing/head/ or something like that

third of all, if the bugs are fixed i want this to be merged, because i love ian.

**Comment by Niknakflak** [comment]
That screenshot is broke.  Side facing ian has the hat underneath his head.

**Comment by Supermichael777** [comment]
That's actually a special trick Nicnak the sprite has ear-holes

**Comment by Niknakflak** [comment]
It looks like shit

**Comment by Supermichael777** [comment]
so does the hos hat.
Do you want to start the sec sprite wars again?

**Comment by Supermichael777** [comment]
ACTUALLY
In the interest of holy shit what the fucks up with the hos cap I have resprited it.
In the interest of not raping the dm I'm gonna repr it

**Pull request closed without merging**
