### PR TITLE
Revert "Adds the jukebox to every active map."

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
They're having issues with lag and I'm unlikely to fix that within the next 24 hours so best if they're not messing up the game in the mean time

### CODE REVIEW

**Comment by deathride58** [comment]
What are the lag issues? You can probably fix the lag issues pretty easily by compressing the OGGs for the jukebox. Keeping the files below 4MB should keep things running mostly smooth.

**Comment by Repukan** [comment]
>unlikely to fix that within the next 24 hours so best if they're not messing up the game in the mean time

**Comment by KorPhaeron** [comment]
I checked the play list and 9 minute+ songs were added so that might be part of the issue

**Comment by Iamgoofball** [comment]
Tell the admins to stop stuffing in uncompressed weeb shit too

**Comment by ma44** [comment]
Should probably have a 1024 KB file restriction, it seems like there's no existing check (unless I'm dumb and haven't noticed and/or it's not working)

**Comment by pigeonsk** [comment]
1 MB is a little too small, but compression is needed. I'd go with 5 MB.

**Comment by KorPhaeron** [comment]
I think I figured it out maybe

**Comment by Cyberboss** [comment]
you can't size file in dm iirc

**Pull request merged**
