### PR TITLE
Fixes Tramstation department sign arrows

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Title & see mapdiff, or not if the multi-z does not play nice with the renders ☹️

## Why It's Good For The Game

Provides more accurate directions via IC signage.

## Changelog

:cl:
fix: Fixed many Tramstation department sign arrows pointing to upload and vault.
/:cl:

### CODE REVIEW

**Comment by Zytolg** [comment]
If you're going to fix the signs, could you fix all of them? These haven't been addressed since the Tramstation Department Swap at #61430 was merged. The images below are of how it currently looks.

Bad Tram Signs A
Bad Tram Signs B

Obviously Bridge should point to Bridge and Sec should point to Sec, and that should be pretty easy to do there. Just make sure all the signs are pointed at their respective destinations! :)

**Comment by Wayland-Smithy** [comment]
Yeah I'll take a look, was just going to add these screenshots since it looks like mapdiffbot is having a hard time the poor thing.
So just for the medbay sign for now then.
Before:
image
Afrer:
dreamseeker_38CXktvYK5

**Comment by MrMelbert** [comment]
#61781 appears to be doing the same fix, maybe

**Comment by Wayland-Smithy** [comment]
Thanks for the heads up Melbert good catch, so I'll just double check they got them all and then close this.

Pretty funny I have had this on my todo for like over a month now too and all of sudden we both go to fix in the span of a day. Kindred spirits perhaps.

**Comment by Wayland-Smithy** [comment]
Found several vault signs and one upload sign still pointing the wrong way after #61781, so I went ahead and fixed those, but I dare not claim they are all 100% correct just in case.

**Pull request merged**
