### PR TITLE
Removes Guardian Spirit from necropolis tendril drop list as requested by Calzilla1

### PR DESCRIPTION
**Pull request by Buggy123**
why:
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=15095
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=15095

Real miners know that holoparasites are a dangerous trap that will get you killed 9/10 times anyway. Hell, I usually don't even kill _tendrils_, let alone use the tarot cards. If this tiny sacrifice will stop the constant "REE NERF MINERS THEY THEORETICALLY GET AWESOME SHIT BUT ACTUALLY JUST GET GIBBED 9/10 TIMES" then by all means fucking do it.

Though, if he doesn't close the thread as promised within 30 hours I'm closing this. @calzilla1

🆑
remove: Necropolis Tendrils have begun digesting any cardboard-based material. Unfortunately, this means that Tarot Cards can no longer be found in their remains.
/🆑

### CODE REVIEW

**Comment by Chocodaemon** [comment]
Is this "salt coding"?

**Comment by Buggy123** [comment]
Yes.

**Comment by Potato-Masher** [comment]
>"What the fuck holoparas aren't even that fucking strong the only op one is the explosive one and only if you have time to set up traps." 
"Seriously miners are no more OP than some robust lad with an ecombo or noslip desword."

_- kevinz000_

**Comment by Buggy123** [comment]
I agree 100%, IMO guardian spirits are a _liability_ more often than not. If the loss of holos shuts up even one of the mindless "NERF MINING REE" then its worth it a thousand times over.

Technically Calzilla promised to close the thread if anyone even _made_ a PR for this but closing this immediately would be in bad faith, so I won't do it unless he fails his end of the bargain.

**Comment by ChuckTheSheep** [comment]
Holy that's an ugly loot table.

Can you have a list of types and use pick since they're all even chances anyway? I know you didn't originally write it but Fuck.

**Comment by Tlaltecuhtli** [comment]
its an 1/27 chance

**Comment by ChuckTheSheep** [comment]
Yeah, so that multi lined shit can all be reduced to a list if type paths (without new) and pick(list)

**Comment by KorPhaeron** [comment]
Making a pr you disagree with to win an internet argument with a random person is not a good justification for your PR

**Comment by Buggy123** [comment]
Fine by me, I held to my end of the bargain.

**Pull request closed without merging**
