### PR TITLE
Changes all dmis to be lowercase

### PR DESCRIPTION
**Pull request by lzimann**
Just a few this time.

@tgstation/commit-access 
Should all code files also be lowercase? And actually enforce adding new files to be lowercase?

edit: Also fix the `badass` icon for nuke ops not showing in goonchat

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Most of us observe the code well enough to do it anyway, but you'll have to rope in loose cannons and spaghetti code.

Searching literally every file of the coderbase for obscure DMI's & references.

**Comment by nicbn** [comment]
If it works... Do it. Please.

**Comment by Cyberboss** [comment]
I warn you once again, this will fuck with git on windows

**Comment by KorPhaeron** [comment]
@lzimann 

Why does this matter/is it worth the risks @Cyberboss is talking about

**Comment by lzimann** [comment]
This has no risk nor fuck up with git on windows. The only thing is that windows doesn't care about file's case and sometimes it might not recognize/change by itself, but it matters on linux. This is mainly for @MrStonedOne byond-cdn.

**Comment by MrStonedOne** [comment]
@KorPhaeron https://github.com/tgstation/tgstation/issues/28329

Linux gets confused if you mess up the case, so to prevent this, the rule in the repo's specs states that all non-code files have to be all lowercase, and all references to them in code has to also be all lowercase.

**Pull request merged**
