### PR TITLE
Removing Pointless Flasher in Holding Cell (Metastation) 

### LINKED ISSUE #50046: Pointless flasher button in meta
obraz
Can you even use it? If so what's the point of having 2 button for holding cell?

### PR DESCRIPTION
**Pull request by RiskySikh**
## About The Pull Request
Fixes #50046 
image

The issue was that in metastation, the holding cell in brig which hold's prisoners had two flasher buttons. As you can see above. After some investigation, it was shown that both of the flashers were used in the holding cell, and it was seemed the flasher button in the window was useless since you couldn't use it unless you broke the window.  I went on dream maker, located the flasher and removed the unnecessary flasher button in the window. Which leaves us with two flashers on the wall. One for the brig entrance, and one for the holding cell. As shown below.
image
 

## Why It's Good For The Game

Well, it seems that the flasher button in the window was pointless, and it had no benefit at all as there was one flasher used for the holding cell already on the wall. 

## Changelog
:cl:
del: removes flasher button in metastation holding cell window
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
obraz
oof

**Comment by RiskySikh** [comment]
> 
> 
> obraz
> oof

I know the issue, I forgot to map merge, I am new to the mapping thing.

**Comment by ShizCalev** [comment]
Poke me on discord if you need assistance with fixing this.

**Comment by RiskySikh** [comment]
> 
> 
> Poke me on discord if you need assistance with fixing this.

thanks man

**Pull request closed without merging**
