### PR TITLE
Fixes meters on the RPD

### LINKED ISSUE #32920: Meters created by the RPD are invisible
Create a meter with the RPD, looks like nothing happens, right click the tile, a "fitting" has been created with examine being:` That's fitting. A pipe. It is a normal-sized item. Alt-click to rotate it clockwise.`
image

Round ID: 79000

Server revision compiled on:  2017-11-19 
The following pull requests are currently test merged: 
#31727: '[Pls No Forget] Complete rework of brain damage' by XDTM at commit b2c039 
Based off origin/master commit: ef21d9 
Server tools version: /tg/station 13 Server v3.2.0.11 
Server tools API version: 3.2.0.1

### LINKED ISSUE #36189: The RPD can't print meters.
Meter buton dont set "mode" var  to METER_MODE

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 

:cl: Dax Dupont
fix: You can now lay meters again with the RPD.
/:cl:

[why]: I removed METER_MODE since mode used the screen settings. Which doesn't have a seperate meter one.
Instead it checks if the recipe type is a meter. 
Fixes https://github.com/tgstation/tgstation/issues/36189 
Fixes https://github.com/tgstation/tgstation/issues/32920

### CODE REVIEW

**Comment by DaxDupont** [comment]
I personally think this works better

**Comment by ShizCalev** [comment]
conflict.

**Comment by DaxDupont** [comment]
Oh boy I sure wish travis would generate these automatically generated files so they won't conflict every time someone touches an UI.

**Comment by DaxDupont** [comment]
@ShizCalev done

**Pull request merged**
