### PR TITLE
Dualsabers will now make you flip only twice, instead of up to twelve times.

### PR DESCRIPTION
**Pull request by ChangelingRain**
KOR, PLEASE

### CODE REVIEW

**Comment by KorPhaeron** [comment]
It's treason, then

**Comment by duncathan** [comment]
@KorPhaeron fuck off, RNG is shit and you know it. this should've been flipping for every dir from the beginning. 

that said, :-1: to this PR

**Comment by Zilenan91** [comment]
this sounds amazing

**Comment by Shadowlight213** [comment]
:-1: best feature don't remove.

**Comment by Jordie0608** [comment]
Fun is illegal
This looked pretty silly when it happened.

**Pull request merged**
