### PR TITLE
Revert "Adds New Shuttle Chairs (#38539)"

### PR DESCRIPTION
**Pull request by cacogen**
This reverts commit 9f564d539bfecf1f73174d9741aa4b50272fbb56.

#38539
@fludd12 
@Cyberboss 

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: cacogen
del: Removes shuttle chairs
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

They look bad.

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=18255

### CODE REVIEW

**Comment by Cyberboss** [comment]
I'm not welcoming a revert when the issue could be fixed by PRing better sprites.

Old chairs have been placeholders for shuttle chairs since shuttles were added

**Comment by Repukan** [comment]
Old chairs don't obscure the whole person when facing up.

Seems like a shit hand to deal with "deal with these fugly chairs or do better" when the fugly chairs could have just not been merged in the first place.

**Comment by fludd12** [comment]
:shrug: Not my sprite, talk to memager.

**Comment by Iamgoofball** [comment]
Get over yourself.

**Comment by GuppyLaxx** [comment]
Seriously why were these fucking slapped on in the first place, they look out of place and like absolute shit. Sure, shuttles could maybe use some nicer chairs or something, but this garbage that covers 70% of the fucking sprite and looks like a gaming chair that's trying too hard is ridiculous

**Comment by MrDoomBringer** [comment]
https://cdn.discordapp.com/attachments/458092860701540352/458751333244076043/unknown.png
how about these chairs can i get a thumbs up/thumbs down
image
its basically an airplane chair

**Comment by cacogen** [comment]
there are these from FTL13

**Comment by MrDoomBringer** [comment]
those are better jesus^

**Comment by GunHog** [comment]
The FTL 13 ones look quite nice. Perhaps the shuttle chairs could be placed in Head of Staff offices or something like that? They look like gamer chairs.

**Comment by Cyberboss** [comment]
Someone can PR doombringer or ftls

**Comment by cacogen** [comment]
lamo

**Comment by JohnOxford** [comment]
>codersprites
>ment to fix legacy sprites
>"fix"
>just made it impossible to touch people in north facing chairs

your chair is bad, the old chairs are far better than this chair, forced icon improvements are bad

**Comment by AlexTheSysop42** [comment]
Tactical chairs.

**Pull request closed without merging**
