### PR TITLE
Creates /turf/open/openspace/space

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Creates `/turf/open/openspace/space`.

The immutable gas mix (empty) from `/turf/open/space` has been moved onto SSair as `space_gas` and made non-static, then the `air` var on both `open/space` and `openspace/space` set equal to `SSair.space_gas` - achieving identical behaviour on regular space turfs but allowing openspace space turfs to use the same mix.

A few behaviours from regular space turfs have then been copied onto `openspace/space` turfs, to achieve the same functionality on an openspace space tile.

For example, opening a gas canister on an `openspace/space` turf will simply delete the gas, the same as `open/space`, instead of spreading like on an airless openspace turf.

Replaces all `openspace/airless/planetary` turfs on tramstation with `openspace/space`.

I've written "space" so many times it no longer looks like a real word.

## Why It's Good For The Game

A performance improvement when using this over the previous openspace turf type, as well as better consistency in behaviour between types of space.

Running Tramstation on a fresh boot of dream daemon, task manager reported memory usage about:
`1 217 000 K` without this change
`1 142 000 K` with this change

## Changelog
:cl: tf4, Azarak
code: openspace turfs used for space have been replaced with proper openspace space, making space more like space!
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
> The immutable gas mix (empty) from /turf/open/space has been moved onto SSair as space_gas and made non-static, then the air var on both open/space and openspace/space set equal to SSair.space_gas - achieving identical behaviour on regular space turfs but allowing openspace space turfs to use the same mix.

I would like this profiled, the space turf inits more then pretty much anything in the game, it being as lightweight as possible is useful.

That said:
Why `/turf/open/openspace/space` instead of /turf/open/space/openspace`? it seems like a space tile has a lot more logic/restrictions then an open space tile, why do the parenting like this?

Of course optimally all the logic would just be based on the element and we wouldn't need to care, but if I recall there's some stupid typechecks lying around. May be some for space too, which is part of the worry

**Comment by tf-4** [comment]
Help maintainers my PR is dying and I need your charity

image

**Comment by LemonInTheDark** [comment]
ah. right

**Comment by LemonInTheDark** [comment]
Testing now, on another note:

I'm sure you mentioned this on discord, but I've forgotten. 
Why space like open space and not open space like space?

**Comment by LemonInTheDark** [comment]
Profiled. It's moderately slower, but not significantly even at scale. Doesn't get rid of the "why not just make it space" question, but at least I know it's not gonna be a gutpunch
image

**Comment by tf-4** [comment]
> Testing now, on another note:
> 
> I'm sure you mentioned this on discord, but I've forgotten. Why space like open space and not open space like space?

I think there was a reason. But this was a few weeks ago and I've since forgotten, and testing it out doesn't seem to raise any issues.

**Comment by tf-4** [comment]
Hm, on second thought I'd probably prefer `space/openspace`. I'll open that as an alternative PR.

**Comment by LemonInTheDark** [comment]
Preferred the alternative, rest in peace sweet child

**Pull request closed without merging**
