### PR TITLE
Changes N2O sprite

### LINKED ISSUE #41045: The new N2O gas overlays heavily degrade its' visual fidelity and make it nearly impossible to see at low concentrations unless you stare intently at it
At concentration of just over and around 5 mols in any turf, there's enough gas to knock someone out but not enough for it to be readily obvious what is happening, ESPECIALLY if you're running. This is functionally equivalent to trying to play with N2O when the gas overlays were broken except you'll notice the gotcha if you stare intently at the space around you afterwards. Old N2O was way more visible even when it just stunned you and didn't put you to sleep. When N2O is at around this level it'd help tremendously if it was a LOT more visually obvious.

As a side note, N2O at high concentrations just looks foggy. Aesthetically it's a lot worse than old N2O.

### PR DESCRIPTION
**Pull request by nicbn**
Fixes #41045

[Changelogs]: # 
:cl:
imageadd: N2O is now more visible
/:cl:

Uses a modified plasma sprite, with less glitter and slower.

https://youtu.be/mrL_8lm2kgM

I think it's uglier than what we have now, but the sprite we have now has some gameplay and balance drawbacks, as the alpha contrast is low and, therefore, it's hard to see it.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
n2o usually knocks you out for like 10 s and then gives you 5 s to set up internals, which is enough time to notice something is wrong in the air

**Comment by wesoda25** [comment]
Um the n2o knockout level still wasn’t visible soooo.

**Comment by subject217** [comment]
Something I forgot to mention: while this DOES somewhat improve the visual fidelity of N2O, the ACTUAL problem is scaling alpha by gas contents in a tile. I understand that it's supposed to be a feature but it's what makes N2O broken.

**Comment by nicbn** [comment]
The scaling alpha alone isn't the problem. The problem is both it beind white and having low alpha contrast. By increasing the alpha contrast like the PR does the problem goes away.

**Comment by Barhandar** [comment]
The plasma is just as not visible as N2O, it's a weird, barely noticeable (moreso in the dark = maint, nightshift, broken lights) purple tint.

**Comment by nicbn** [comment]
One can increase the alpha for low concentrations by making the gradient curve steeper and lower the minimum amount to trigger the icon by adjusting some defines.

I may do this later in another PR.

**Comment by Cyberboss** [comment]
Ehh, let's fix this a different way

**Pull request closed without merging**
