### PR TITLE
Chef now spawns with a whetstone instead of being sold by the kitchen's vending machine

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
:tweak: Instead of being sold by kitchen's vending machine, the whetstone now spawns in chef's backpack!
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
As the guy who added these, :+1:

**Comment by Ergovisavi** [comment]
I like the idea of the whetstone (As a weapon upgrade mechanic) but could we actually add a useful function for chefs for this thing instead of it being a glorified weapon upgrade on a civilian job

**Comment by Jalleo** [comment]
I agree with Ergo's statement.

**Comment by PKPenguin321** [comment]
I have a little bit of an idea for that that I can push later

**Comment by nullbear** [comment]
You could make it also affect the knife butchering speed, if it doesnt already/

**Comment by pubby** [comment]
I'd rather have whetstones be cargo/syndicate only.

**Comment by Firecage** [comment]
So, why exactly is the whetstone amount reduced from 2 to 1?

**Comment by lzimann** [comment]
there's two chef slots

**Comment by WJohn** [comment]
Whetstones should be craftable with sandstone.

**Comment by optimumtact** [comment]
The answer is to remove the whetsone

**Comment by Durkel** [comment]
Whetstones were a mistake.

**Comment by TehZombehz** [comment]
The new meta will be to kill/arrest the chef roundstart before they get a chance to use their whetstone and take it for your meme weapon.

**Comment by lzimann** [comment]
then they get banned for being a dick, honestly we should just remove/rework whetstones completly, it's pretty much an useless thing that people kill each other for

**Comment by optimumtact** [comment]
They should never have updated damage, they should have affected butchering speed or other non combat related attributes

**Pull request merged**
