### PR TITLE
Salicylic acid & Oxandrolone now care about purity.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
Just makes salicylic acid and oxandrolone scale with purity (so they're consistent with libital & aiuri scaling)
## Why It's Good For The Game
Now mass producing good salicylic acid / oxandrolone with a chem factory takes some effort.

## Changelog

:cl:
balance: Oxandrolone now scales with purity. Its default purity is 100%
balance: Salicylic acid now scales with purity. Its default purity is 100%
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
nyok

**Comment by Higgin** [comment]
we're coming back, fermibros

**Comment by ZephyrTFA** [comment]
I thought we agreed that fermichem was unfun and should be phased out

**Comment by ZephyrTFA** [comment]
am I hallucinating

**Comment by MLGTASTICa** [comment]
> I thought we agreed that fermichem was unfun and should be phased out

the agreement was that having medicine with impurities deal damage / side effects was unfun, not that reducing their potency.

**Comment by TJatPBnJ** [comment]
this is actually a buff because sali and oxa are really easy to make pure

**Comment by ExcessiveUseOfCobblestone** [comment]
how is it a buff if the range here is 0-1? at 1 youre breaking even?

**Comment by ExcessiveUseOfCobblestone** [comment]
> I thought we agreed that fermichem was unfun and should be phased out

its been too long i remember mothblocks liked fermi or something

**Comment by MLGTASTICa** [comment]
> > I thought we agreed that fermichem was unfun and should be phased out
> 
> its been too long i remember mothblocks liked fermi or something

it can go above 1, since its purity / default_purity , if its 1 it will be 1 / 0.75 which will be a buff of 1.33x

**Comment by Deadgebert** [comment]
please correct me if i'm wrong, but isn't default medicine purity 1? if you're not overriding it in oxan or saly, your default purity is 1. 
if you call proc normalise_creation_purity() on oxan or saly in game, it'll return current purity. 

`
/// A single reagent
/datum/reagent
	var/purity = 1
	var/creation_purity = 1
`

`
/datum/reagent/medicine
	taste_description = "bitterness"
`

`
/datum/reagent/medicine/oxandrolone
	name = "Oxandrolone"
	description = "Stimulates the healing of severe burns. Extremely rapidly heals severe burns and slowly heals minor ones. Overdose will worsen existing burns."
	reagent_state = LIQUID
	color = "#1E8BFF"
	metabolization_rate = 0.5 * REAGENTS_METABOLISM
	overdose_threshold = 25
	ph = 10.7
	chemical_flags = REAGENT_CAN_BE_SYNTHESIZED
	inverse_chem_val = 0.3
	inverse_chem = /datum/reagent/inverse/oxandrolone
`

purity is not overwritten anywhere.

again, might be missing something, looking over this at 4am because someone linked it to me.

**Comment by CCC23** [comment]
:(

**Comment by DrAmazing343** [comment]
I've always felt as though Salicylic and Oxandrolone were the "easy chems" for noobs with the caveat/trap that they're not so good at healing minor wounds, encouraging chemists to branch out to Aiuri and Libital that depend on purity. This change making Sali and Oxy purity-dependent will likely hurt noob chemists.

**Comment by ExcessiveUseOfCobblestone** [comment]
Worst case you get less healing so you have to use more, both chems use an intermediate (phenol) so its not as easy to make.

A noob is going to see the simple recipe and do that, the veteran would be the one who would know that these chems arent affected by purity so they are strong.

**Comment by ATH1909** [comment]
> imagine i post a baby having a tantrum in gif form, as that is me right now.
> 
> both of these chems are very strong as is and purity is not hard to achieve, please make it so that the pure values are the equivalent strength to what it currently is.

both of these chems are in luxury survival pens; would this affect miners?

**Comment by MLGTASTICa** [comment]
> please correct me if i'm wrong, but isn't default medicine purity 1? if you're not overriding it in oxan or saly, your default purity is 1. if you call proc normalise_creation_purity() on oxan or saly in game, it'll return current purity instead of purity / 0.75.
> 
> ```
> /// A single reagent
> /datum/reagent
> 	var/purity = 1
> 	var/creation_purity = 1
> ```
> 
> ```
> /datum/reagent/medicine
> 	taste_description = "bitterness"
> ```
> 
> ```
> /datum/reagent/medicine/oxandrolone
> 	name = "Oxandrolone"
> 	description = "Stimulates the healing of severe burns. Extremely rapidly heals severe burns and slowly heals minor ones. Overdose will worsen existing burns."
> 	reagent_state = LIQUID
> 	color = "#1E8BFF"
> 	metabolization_rate = 0.5 * REAGENTS_METABOLISM
> 	overdose_threshold = 25
> 	ph = 10.7
> 	chemical_flags = REAGENT_CAN_BE_SYNTHESIZED
> 	inverse_chem_val = 0.3
> 	inverse_chem = /datum/reagent/inverse/oxandrolone
> ```
> 
> purity is not overwritten anywhere.
> 
> again, might be missing something, looking over this at 4am because someone linked it to me.

you are right. I looked at the wrong parent when checking for purity

**Comment by Deadgebert** [comment]
i'm a supporter of 75% default purity. making healing chems less powerful because of purity feels kinda bad

**Comment by moocowswag** [comment]
Salicylic acid and Oxandrolone arn't very powerful at all actually, chem healing in general doesnt work against taking alot of damage in a short amount of time and chems really shine when you are weaving in and out of combat.

Salicylic and Oxandrolone start to really kick off their healing near the threshold where you take a damage slowdown.

Basically their healing is only good when youre in a situation that you arnt doing well in to begin with, they are a "lose less" chem and often id use libital and just powergame burn resistance instead.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
> both of these chems are in luxury survival pens; would this affect miners?

speak to this before merge

**Comment by MLGTASTICa** [comment]
> > imagine i post a baby having a tantrum in gif form, as that is me right now.
> > both of these chems are very strong as is and purity is not hard to achieve, please make it so that the pure values are the equivalent strength to what it currently is.
> 
> both of these chems are in luxury survival pens; would this affect miners?

No effect, they start with a purity of 100% as that is their default for being spawned in.

**Pull request merged**
