### PR TITLE
Removes duplicate goonchat font-awesome

### PR DESCRIPTION
**Pull request by Cyberboss**
TGUI already has one

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Certain font awesome markers are versioned, so you would need to update the usage as well

**Comment by Cyberboss** [comment]
I honestly don't even know what version the goonchat one is

**Comment by MrStonedOne** [comment]
I mean you would really just need to confirm they work properly and if not, change the div class to what ever tgui's version wants.

**Comment by nicbn** [comment]
`code/modules/client/asset_cache.dm:344:error: 'tgui/assets/fonts/font-awesome.min.css': cannot find file`

**Pull request merged**
