### PR TITLE
Remove birdboat station again

### PR DESCRIPTION
**Pull request by optimumtact**
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=4223&start=50#p252288

I agree with the creator on all of their points and I should have stuck
to my guns on the original removal

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
It is contaminated with bird flu, do the right thing

**Comment by Cyberboss** [comment]
The only reason it stayed last time was cause we had no omega. Now there is no reason 👍

**Comment by KorPhaeron** [comment]
Just because a handful of admins dislike a map and make it the butt of a joke doesn't mean we need to remove something that has been actively maintained

**Comment by KorPhaeron** [comment]
This is the only map in the code base willing to take risks in design and actually function as a metal deathtrap instead of just being a safer, more overstocked, or more colourful boxstation

**Comment by Shadowlight213** [comment]
@KorPhaeron what are you talking about? Bird isn't maintained at all.

**Comment by Armhulen** [comment]
1. I have not maintained the map in years and I do not plan on doing this again. A few people have pushed some updates but the point is that the map is awfully outdated and broken, even disregarding the balancing problems. There are even potential server crashes with the mess the TEG is and I fear that it may even break configs since the job screen is just...broken.

yeah man it's totally maintained :ok_hand:

**Comment by KorPhaeron** [comment]
@Shadowlight213 

There is only a single open issue for birdboat for something that is buggy on all maps. Other issues have been fixed as they've been opened.

Does a map need a quota of arbitrary balance changes to make you consider it maintained?

**Comment by ChangelingRain** [comment]
>birdboat maker says "yes remove this"

i don't think there's any real argument

**Comment by PKPenguin321** [comment]
Objectivity the most fun map to play nuke ops on. :-1:

**Comment by Hatfish** [comment]
No player I've seen has ever actually been happy to see BirdBoat come up on map rotation, they almost always beg admins to change the map and, if none do, proceed to spend the whole round doing everything they can to end the round.

**Comment by OtherDalfite** [comment]
I don't enjoy the map hardly at all. Sorry to the original maker of the map I just do not enjoy playing on it and neither does most of the server's playerbase from what I've seen. Now if only we could get double agent removed...

**Comment by coiax** [comment]
Birdboat is a special precious flower, and its removal would leave a gap in my heart.

**Comment by Niknakflak** [comment]
Good

**Comment by PKPenguin321** [comment]
Good night, sweet birb

**Pull request merged**
