### PR TITLE
New bitflag CLEAN_ON_MOVE

### PR DESCRIPTION
**Pull request by coiax**
Time to use those highspeed bitflag slots.

If an atom/movable has CLEAN_ON_MOVE set, it will behave like a janitor
cyborg when moving.

Current owners of the CLEAN_ON_MOVE flag are janitor cyborgs and the
janitor's pimping ride (when upgraded).

This has the side effect of slightly buffing janitor's pimping ride cleaning
to also clean people's faces and clothes.

- Also moves BLOCK_GAS_SMOKE_EFFECT and THICKMATERIAL to separate flags.
- You can no longer upgrade a pimping ride more than once.
- New typepath for an already upgraded pimping ride.

### CODE REVIEW

**Comment by kevinz000** [comment]
why is this not a secondary flag? speed?

**Comment by Iamgoofball** [comment]
Stop wasting bitflag slots

**Comment by ChangelingRain** [comment]
Why is this a bitflag and not a secondary flag? You added secondary flags specifically for this, right?

**Comment by coiax** [comment]
It's a check done on every single Moved(), I figured we'd want the speed.

**Comment by XDTM** [comment]
I think that performance ranks higher than avoiding copypaste in this case, you're adding a check to all atoms on every move.

**Comment by coiax** [comment]
It's a fast check though.

**Comment by Supermichael777** [comment]
seems like a waste tbh unless you plan to add more functonality

**Comment by coiax** [comment]
I'm not getting a universal feedback message here.

**Comment by xxalpha** [comment]
You're not optimizing anything if the proc still looks like that, tbh.

**Comment by PKPenguin321** [comment]
Oh this is excellent I've wanted to apply this to soaps for ages

**Comment by coiax** [comment]
Will a maintainer please clarify whether we can put a secondary flag check into every Moved() or we use a bitflag for this?

**Comment by Cyberboss** [comment]
Why not just call `clean_on_move` in `Moved` for the types that do it?

**Comment by coiax** [comment]
@Cyberboss then you wouldn't... be able to do it with var editing?

**Comment by optimumtact** [comment]
I'll happily clarify that there is no way a secondary flag is getting into every moved.

**Pull request merged**
