### PR TITLE
Moves tips from config to strings tree

### PR DESCRIPTION
**Pull request by Cyberboss**
Related #26687 

>Expecting server operators to maintain massive string lists

They should be handled on a per codebase basis. Except maybe stealthmin nicks, debate that one

### CODE REVIEW

**Comment by lzimann** [comment]
The stealthmin should be a per server basis.

**Comment by Jordie0608** [comment]
Stealthmin should stay config like the rest of the admins config.

**Comment by Shadowlight213** [comment]
Stealthmin definitely.
If you look at the codebase version it's literally just an example name.

I'd like to at least keep meme tips as a config. It's nice to have surprise rare tips that people don't expect.

**Comment by lzimann** [comment]
Actually yea, meme tips is fine to stay as a config aswell. The tip is nice since right now adding more tips to the codebase doesn't matter since it won't update at the server, and this way encourages people to put more tips there.

**Comment by coiax** [comment]
1) do we actually have any meme tips other than "use fire on blobs lol"

2) Maybe have an "additional tips" config, while maintaining the official tips in strings.

**Comment by duncathan** [comment]
this is ok for now, if someone really cares that much about meme tips they can make another pr

**Pull request merged**
