### PR TITLE
Gives the warden a cycler shotgun

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Gives the warden the dual magazine shotgun from https://github.com/tgstation/tgstation/pull/17118

> Has two tubes, which you can toggle between by using the gun inhand. For example, you could fill one tube with riot ammo, and another with buckshot. Basically the UTS 15

Replaces his gloves because

1) I'd feel guilty just piling more gear into sec for no reason

2) I feel a shotgun is more thematically appropriate to the Warden based on some vague criteria I just made up

3) The gloves are very situational as you'll usually have a baton/gun/flashbang anyway.

4) The gloves are basically stungloves if you recolour them or hide them under a suit.

If people really want the gloves though I guess I can just close this or give him both or a choice or something 

:cl: Kor
add: The Warden has a new dual magazine shotgun.  Click to toggle tubes, alt+click to pump.
del: The Warden no longer has martial arts gloves.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>del: The Warden no longer has martial arts gloves.

o7

**Comment by Iamgoofball** [comment]
STOP REMOVING KRAV MAGA

ADD IT TO OFFICERS

**Comment by optimumtact** [comment]
Martial arts are dumb and poorly implemented.

**Comment by KorPhaeron** [comment]
Poorly recieved so far

**Comment by Durkel** [comment]
Could always make the gloves a random spawn in the sec starting lockers, that way it may actually get used instead of sitting on a fat fuck who does nothing all round.

Also, The warden starts with a steelpoint memerifle on meta in his locker, so he would have two guns there or what?

**Comment by Banana-Fist** [comment]
Merge it!

**Comment by Shapsy** [comment]
It's not like the cycler is super OP, it's still bulky like the other shotguns and can't even be sawed off, if anything this is a slight nerf

**Comment by GunHog** [comment]
Aww. I wanted to give it to Science, so they would have a shotgun to go with the unlargely used tech shells (I would have to remove the ability to make any other completed shells from protolathe).

Oh, well. A shotgun for the warden makes more sense.

**Comment by Hatfish** [comment]
Doesn't the warden already get an autorifle courtesy of steelmemes?  Can't we replace that with this?

**Comment by GunHog** [comment]
The warden is not provided an autorifle on the Box map.

**Comment by PKPenguin321** [comment]
if you're gonna remove krav you might wanna consider mentioning it in the forums or at least in the title of the PR

since it's been in the game so long i don't know how players would react to it being removed

**Comment by optimumtact** [comment]
I'm taking over

**Comment by Saegrimr** [comment]
i gave u smiley faces kor i know u like smilememes

**Comment by jughu** [comment]
>cycler shotgun
>not a buff
>two ammo slots
>Fill tube a with instant deathmix darts
>Fill tube b with buckshots

**Comment by Shapsy** [comment]
yeah you know all those instant deathmix darts that sec has just laying around and uses with their normal shotguns they already have

**Comment by jughu** [comment]
They are just not creative tbh
New security players sucks

**Comment by MMMiracles** [comment]
I remember the hell of going through as a warden just to get decent death mixes for a single chem implant, yet you think it'd be that easy to get multiple dart shell's worth of deathmix chems?

Something something theorycrafting.

**Comment by yackemflam** [comment]
As a warden player who uses a riot shotgun, I have no clue on how to make of this.

**Comment by PKPenguin321** [comment]
>Also I'm against adding the shotgun because maga krav gloves are cooler than shotguns but I'm just saying

this is true

**Comment by Bawhoppen** [comment]
krav maga is so fucked right now its not in a suitable state to be used in game so I guess this is good but powercreep memes and all that

**Comment by Iamgoofball** [comment]
You don't know what you're talking about, baw. As usual please hang yourself and die.

**Comment by Bawhoppen** [comment]
And what do I not know what I'm talking about? If it's about the krav maga, then no, I have played with it and it is broken in several key ways

**Comment by Iamgoofball** [comment]
are we going to play the "bawhoppen says its 'broken' but refuses to elaborate" game because i sure do love that game

**Comment by Bawhoppen** [comment]
are we going to play the "goof says I'm not elaborating yet have many previous times" game too

**Comment by PKPenguin321** [comment]
you literally did not elaborate

**Comment by Bawhoppen** [comment]
I didn't on this PR

**Comment by Davdichan** [comment]
@iamgoofball what about the 'bawhoppen is convinced something does something and is too damn lazy to check his facts before opening a PR' game. Thats always a fun one too, great for parties.

**Comment by MMMiracles** [comment]
@Bawhoppen 
"I said my reasons somewhere, I mean i'm not gonna find them for you or restate them i'm just gonna say I did at one point and get upset when people keep asking to elaborate."

my fucking sides.

**Comment by Bawhoppen** [comment]
>mmmiracles trying to memearrow me (without actually using a meme arrow)

**Comment by KorPhaeron** [comment]
I really don't want to break pkpenguin's heart he's always been a loyal shitposter to my various causes

**Comment by PKPenguin321** [comment]
aw thanks bud

**Pull request closed without merging**
