### PR TITLE
Makes drying racks dry leather

### PR DESCRIPTION
**Pull request by swindly**
:cl: Swindly
add: Wet leather can be dried by putting it on a drying rack.
/:cl:

So that this entirely useless item can actually be produced.

### CODE REVIEW

**Comment by Earthykiller127** [comment]
useless pr

**Comment by swankcookie** [comment]
@Earthykiller127 to be fair, that's an apt description of the last year and a half of tg development

**Comment by Niknakflak** [comment]
Earthykiller is the rshoe guy, just ignore him.

**Comment by Supermichael777** [comment]
hey i added tesla to grills

that changed a bunch of assitant meta(and i got to watch a bunch of on and offers shock themselves in front of me 😄 )

**Comment by swankcookie** [comment]
rshoe?

**Comment by PKPenguin321** [comment]
Resident ban evader

**Comment by Cyberboss** [comment]
@Supermichael777 ...?

**Comment by PKPenguin321** [comment]
why microwaves why not drying racks

**Comment by PKPenguin321** [comment]
or possibly both

**Comment by FantasticFwoosh** [comment]
PK peng has a good point there.

**Comment by swindly** [comment]
Drying racks now dry leather.

**Comment by FantasticFwoosh** [comment]
There's no need to rename the entire PR to the newest feature  you just put in, besides you also now have excluded the microwaving of the original commit thats STILL in this PR from the changelog and any mention in the OP.

A name like "Leather can be dried now" or something along those lines would be more sufficient to cover both methods of drying.

**Pull request merged**
