### PR TITLE
Adds a new lobby song, it's actually free of any copyright.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Please give it a listen!

### CODE REVIEW

**Comment by Cyberboss** [comment]
lyrics: :-1:
10x longer than the lobby timer: :-1:

**Comment by Durkel** [comment]
That was fucking trash and I want my four and half minutes I wasted listening to this back.

**Comment by PKPenguin321** [comment]
holy shit it's so bad lmao

**Comment by Jordie0608** [comment]
I'm interested to know what genre this falls under so I can never listen to it again.

**Pull request closed without merging**
