### PR TITLE
Gives some upsides to the toxolysis symptom

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

See the changelog.

## Why It's Good For The Game

Currently, toxolysis is pretty much just a grief/meme symptom that's used either to make the lives of Medbay's staff more difficult or to purge your virus's cure from its hosts' bloodstreams (although the toxolysis symptom has bad enough stats that it isn't really worth being used for either of those purposes). This PR gives it ways to be helpful instead of annoying/negative.

## Changelog
:cl: ATHATH
balance: The toxolysis symptom now slowly heals toxin damage.
balance: The toxolysis symptom's resistance 7 threshold effect now is the threshold effect that causes the toxolysis symptom to feed its virus's host while it purges chems. Said feeding has been massively buffed in potency, but can no longer make a host fat (on its own).
balance: The toxolysis symptom's stage speed 6 threshold effect now increases the speed at which the toxolysis symptom purges chems (this used to be what the resistance 7 threshold did) and the speed at which the toxolysis symptom heals toxin damage.
add: Adds a new stealth 3 threshold to the toxolysis symptom that causes it to only purge toxins (instead of all kinds of chems). You might want to avoid meeting this threshold if your virus's cure isn't a toxin!
/:cl:

### CODE REVIEW

**Comment by dr-bee** [comment]
Viruses with passive healing are typically frowned upon. Consider having it heal toxin damage only when it is purging chems. That way you actually have to do something to activate the healing instead of it being a passive buff.

**Comment by optimumtact** [comment]
dr bee is right

**Comment by ATH1909** [comment]
> Viruses with passive healing are typically frowned upon. Consider having it heal toxin damage only when it is purging chems. That way you actually have to do something to activate the healing instead of it being a passive buff.

This is passive healing, but with a pretty big downside (purging chems from your body, including healing chems).

We already have self-respiration as a passive healing symptom; why not make toxolysis be a passive healing symptom (with a big downside unless you invest in the stats needed to negate it) as well?

**Comment by ExcessiveUseOfCobblestone** [comment]
I won't merge this while it has an always active passive healing mechanic.

Self-Resp is an exception (not to thrilled but whatever for now), not an example.

**Comment by KetasDotepasto** [comment]
Why are viruses with passive healing frowned upon?

**Comment by optimumtact** [comment]
power creep

**Comment by KetasDotepasto** [comment]
@optimumtact Thanks for your reply. Why is self-respiration the exception?

**Comment by ExcessiveUseOfCobblestone** [comment]
because no one has bothered to nerf it yet.

**Pull request closed without merging**
