### PR TITLE
Adds a single roundend sound

### PR DESCRIPTION
**Pull request by 2-room-apartment-in-Bydgoszcz-Poland**
## About The Pull Request

[Holy Jesus! What is that? What FUCK is that? What is that, Private Pyle?!](https://www.youtube.com/watch?v=mCQRYWLUo_Y)

## Why It's Good For The Game

It's a good movie, come on

## Changelog
:cl: david the barkeep
soundadd: New roundend FMJ sound.
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
you didn't even add it to the list of roundend sounds

**Comment by optimumtact** [comment]
these are also a server config, if you want to hear roundend or lobby sounds on /tg/, make a policy thread and ask the headadmins.

Bundling it with the codebase does nothing

**Comment by trollbreeder** [comment]
Once you've asked the headmins and they give the okay, modify this file with the new roundend sound.
code/controllers/subsystem/ticker.dm (Around line 620)
Else the game won't recognize it as existing and won't pick it.

**Comment by optimumtact** [comment]
that implies there isn't a config though.

**Comment by Jordie0608** [comment]
There is only a config for title sounds, not round end.

**Comment by PKPenguin321** [comment]
I don't like it, don't add things just for the sake of adding them like this.

**Comment by Cyanshitcoder** [comment]
fair enough, case closed.

сб, 25 янв. 2020 г. в 12:51, PKPenguin321 <notifications@github.com>:

**Comment by cacogen** [comment]
this was good

**Comment by Couls** [comment]
i liked this too

**Pull request closed without merging**
