### PR TITLE
Cult spell buttons will no longer hold an empty slot in the regular action bar

### PR DESCRIPTION
**Pull request by Robustin**
@neersighted just for u

### CODE REVIEW

**Comment by francinum** [comment]
Alternatively, could we get an option to NOT use the strange entirely non standard placement of buttons that only bloodcult enforces?

**Comment by francinum** [comment]
Except the standard action button system.

**Comment by Robustin** [comment]
Which would've been a disaster having to juggle spells that you constantly gain/expend alongside your flashlight and "nominate yourself to lead the cult" button.

I basically took a cue from the awful Clock Cult UI that has so much potential with its custom buttons that was ruined by having them in the default action bar.

**Comment by Supermichael777** [comment]
Except that the buttons jump back to default position if you ever put the knife into your bag or hide it in a locker.

**Comment by ExcessiveUseOfCobblestone** [comment]
Using buttons as a pseudo hud has already been an established poor move.

**Comment by Robustin** [comment]
@ExcessiveUseOfCobblestone 

A large majority of the feedback has been positive. A constantly re-ordering list in the upper-left that competes with flashlights and mask adjustments was hell during testing and there is NO way to control where new action buttons show up without this system.

**Comment by optimumtact** [comment]
it's a shit HUD but this is a fix for a problem itcauses

**Pull request merged**
