### PR TITLE
Nerf TK holy shit its OP I ded nerf it now, Now, NOW!!!!

### PR DESCRIPTION
**Pull request by Robustin**

### CODE REVIEW

**Comment by optimumtact** [comment]
lmao

**Comment by Anonus** [comment]
TK is very silly, though.

**Comment by Shapsy** [comment]
what

**Comment by Durkel** [comment]
We did it reddit

**Comment by PKPenguin321** [comment]
what the fuck is this

**Comment by duncathan** [comment]
>PR from the Byond509 branch

**Pull request closed without merging**
