### PR TITLE
BYOND_MINOR travis.yml

### PR DESCRIPTION
**Pull request by JJRcop**
whoa we've been testing with an older version this whole time

what's going on?
where is my family?
HEY, WHAT DOES 511 EVEN MEAN? ANSWER ME!

JUST LET ME HAVE MY LIFE BACK

### CODE REVIEW

**Comment by Jordie0608** [comment]
Well this won't change anything, but there's also no reason to not merge it.

**Comment by JJRcop** [comment]
b-b-but.... 
...

what if, bug??

!!!
http://www.byond.com/docs/notes/510.html
[❗️ ❗️ ❕ ](http://www.byond.com/docs/notes/510.html)

**Comment by Jordie0608** [comment]
gifmovie

**Comment by JJRcop** [comment]
so does this really fall into the 24 hr limit

**Comment by Jordie0608** [comment]
I'm sure nobody will mind.

**Pull request merged**
