### PR TITLE
Removes Space Dragon Final Objective

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

See title
I left the item in and removed the antagonist checks from it just in case an admin wants to fuck around with it, but I can delete that too if preferred.

## Why It's Good For The Game

This is both our least interesting and least impactful objective.
Turning into a (nerfed) space dragon sort of looks cool maybe the first time you do it and then after that it isn't. It is sort of disappointing to see it pop up in the uplink, in my experience.
This Space Dragon generally speaking isn't going to cause significant death or destruction except on lowpop (where a traitor can just do that anyway) or if they play in the cheesiest possible manner, it simply isn't that dangerous by itself.
It is also simply less versatile than just _being a traitor with a lot of TC_, something you already are when you get it.

Turning into a big animal also just doesn't feel much like something a traitor should be doing, that's a changeling or possibly wizard sort of objective.

It also sort of cheapens "real" space dragons by making them show up this way.

Finally; I just don't like it.
We have enough final objectives now that we don't need to keep this one just to fill the pool, in my opinion.

## Changelog

:cl:
balance: Traitors can no longer turn themselves into dragons.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
I originally added it because I wanted as many ghost roles to have a human equivalent of it, I didn't like the idea that people playing the game were being exempt from being able to play certain antagonists and thought Traitor final objectives as an end-all thing would be a good spot for an antagonist as Space Dragon. I think we should try to find some alternative way to get Space Dragon without being a ghost to replace this.

**Comment by Xackii** [comment]
Maybe then add a traitor item that allows you to become a dragon?

**Comment by MrMelbert** [comment]
Frankly I just don't think Dragon is an interesting enough mob to be worthy of being able to turn yourself into.

It doesn't have cool abilities and it's not very flashy, it just runs at people.

**Comment by Xackii** [comment]
> Frankly I just don't think Dragon is an interesting enough mob to be worthy of being able to turn yourself into.
> 
> It doesn't have cool abilities and it's not very flashy, it just runs at people.


It would be cool if the player could choose which final goal he wants to achieve. Then everyone will be able to choose for themselves what they like, what they want to strive for, and not hope that they will get Romerol and not a sm cascade

**Comment by Jacquerel** [comment]
> I originally added it because I wanted as many ghost roles to have a human equivalent of it, I didn't like the idea that people playing the game were being exempt from being able to play certain antagonists and thought Traitor final objectives as an end-all thing would be a good spot for an antagonist as Space Dragon. I think we should try to find some alternative way to get Space Dragon without being a ghost to replace this.

I kind of get that in theory but I'm not sure it's a worthwhile goal to strive for in practice. 
The only way to become a wizard is the die of fate, You can't become a sentient disease or revenant or space ninja in any way, and I am not sure the game would be improved if you could.

**Comment by ExcessiveUseOfCobblestone** [comment]
> It would be cool if the player could choose which final goal he wants to achieve. Then everyone will be able to choose for themselves what they like, what they want to strive for, and not hope that they will get Romerol and not a sm cascade

I agree with the sentiment but not as it applies to space dragon, turning yourself into a dragon leans more to the magic realm instead of "shoddy" technology corporate espionage syndicate one.

**Comment by Jacquerel** [comment]
> > Frankly I just don't think Dragon is an interesting enough mob to be worthy of being able to turn yourself into.
> > It doesn't have cool abilities and it's not very flashy, it just runs at people.
> 
> It would be cool if the player could choose which final goal he wants to achieve. Then everyone will be able to choose for themselves what they like, what they want to strive for, and not hope that they will get Romerol and not a sm cascade

Watermelon and me I think both had separate plans related to this, but I am not sure either of us will get around to it for a while (his was more extensive and interesting than mine but I have a different large antagonist change I want to take on instead of just implementing his idea).

**Pull request merged**
