### PR TITLE
"IT'S ONLY LOGGING, WHAT'S THE WORST THAT COULD HAPPEN???"

### PR DESCRIPTION
**Pull request by Iamgoofball**
famous last words

### CODE REVIEW

**Comment by optimumtact** [comment]
>modify a type path they said
>don't kill me they said

**Comment by RemieRichards** [comment]
>goof "improves" something
>it breaks horribly

**Comment by Cheridan** [comment]
https://www.youtube.com/watch?v=uDIgS-Soo9Q goofball_improves_the_game.webm

**Comment by OhEmGee** [comment]
f u n r e m o v e r b o y s
what do I do without my mech legions and diamond-plated escape

**Comment by OhEmGee** [comment]
seriously though this has improved the game a lot

**Comment by palpatine213** [comment]
Remove the runtimes, keep the infinite ores.

**Comment by freerealestate** [comment]
>seriously though this has improved the game a lot

kind of indicates ore scarcity is too much right now (haven't we known that for years though?)

**Pull request merged**
