### PR TITLE
Adds Squall Walkers

### PR DESCRIPTION
**Pull request by swankcookie**
Re-do of a PR from a long time ago.  
Old Discussion: #15029
suit and helmet
http://puu.sh/mOkB4/7153e5b6b0.png
Whats better then a bad meme?
A 2 month-old stale bad meme.

### CODE REVIEW

**Comment by Cheridan** [comment]
star wars is for losers

**Comment by Supermichael777** [comment]
>rip not getting sued by Disney. we would lose aliens too.

**Comment by swankcookie** [comment]
@Cheridan You are for losers

**Comment by swankcookie** [comment]
tbh only brought it back because people asked me about it.

**Comment by Zilenan91** [comment]
Can you add the xeno suit to the AutoDrobe contraband too since you did on the last one?

**Comment by swankcookie** [comment]
I got a lot of comments in the PR and on IRC berating me for doing that. sorry :confused:

**Comment by Thunder12345** [comment]
Brace yourself, Disney's going in dry

**Comment by Cheridan** [comment]
Sorry but this is in violation of our reference policy.

**Pull request closed without merging**
