### PR TITLE
Added documentation to the changelog

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request
Documentation brings 5 gbp making well documented features half off. This is subject to change but documentation definitely be rewarded with gbp as we critically needed. 

## Why It's Good For The Game
I know gbp serves the codebase not the other way around but having features documented as we go would be helpful.

## Changelog
:cl:
code: made documentation prs give gbp
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Yasssssss

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Changelogs are only for what players actually see. If your documentation PR somehow changes the behavior of the game, you have seriously messed up.

**Comment by Mothblocks** [comment]
Having GBP for this is fine (though I'd ask @Cyberboss on the reward value), but the changelog part isn't.

You can auto detect it just by searching for "document" in the body or something.

**Comment by spessbro** [comment]
> You can auto detect it just by searching for "document" in the body or something.

should code in the changelog be removed aswell by that logic?

**Comment by tralezab** [comment]
Yes.

**Comment by Cyberboss** [comment]
2 GBP

**Pull request closed without merging**
