### PR TITLE
Adds 3 new space ruins, touches another one

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request
This adds 3 new space ruins and a unpowered apc to derelict4.dmm
The apc has been added to stop the ruin from being magically powered/unpowered

## Why It's Good For The Game

Spoilers: One of them is an asteroid, we haven't gotten a new roid since 2016. We have been suffering a roid famine for 5 years

If we add enough of these, we can start tossing some of the bad ones (clownplanet)

## Changelog

:cl:
add: 3 new space ruins, 2 chunks of a blown up space station and a NEW asteroid!
/:cl:

### CODE REVIEW

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Write what the ruins are in the changelog please

**Comment by axietheaxolotl** [comment]
Removing Gas the Lizards isn't about being "woke", it's about removing an unfunny, edgy space ruin, that serves no real purpose besides "haha funny anti-semitism". Don't mistake not finding edgy shit funny for being "woke", whatever that means.

**Comment by optimumtact** [comment]
I almost closed your PR reflexively, but instead i've just removed the cringe present in your OP, keep it from returning and lose the weird attitude

**Review by Maurukas — APPROVED** [review]
All issues appear addressed.

@MrStonedOne Non-urgent config update of the ruins blacklist. I'm told this is mostly for downstreams.

**Pull request merged**
