### PR TITLE
No access restrictions on crematorium button

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It's more or less a requirement to use during changeling (other than using the kitchen) and there are few ways to dispose of bodies in general now that space loops back so much.

So no ID lock on the machine.

### CODE REVIEW

**Comment by Anonus** [comment]
How about no, okay?

**Comment by optimumtact** [comment]
:-1: against this

**Comment by SweaterKittens** [comment]
Now that we have flesh disguises and ling armor is so common, the gibber is almost completely out of the question as an option for ling removal. Combine that with what Kor mentioned about space looping, we're down several options for removing lings. I'm for this.

**Comment by PKPenguin321** [comment]
:+1: i enjoy this level of violence

**Comment by KorPhaeron** [comment]
@PKPenguin321 

It is emaggable but that doesn't help much with burning lings.

And you shouldn't have to buy an emag to get rid of bodies its already the best at everything else

**Comment by WJohn** [comment]
:+1: 
The chef's gibber, an equally low access place that has the same round-removal properties, is like 30 tiles away and doesn't have access restrictions to use. Seems odd that this ever had any restrictions in the first place considering that.

**Comment by Supermichael777** [comment]
should at least be mourge restricted. cremotorium should become a part of the mourge.

**Comment by Steelpoint** [comment]
:+1:

**Comment by Jalleo** [comment]
This whole concept is flawed red alert should change access restriction to sec on crematorium button.

**Pull request merged**
