### PR TITLE
Removes range from ebow bolts + price revert + bugfix

### PR DESCRIPTION
**Pull request by ghost**
Now that ebows have to be hand-cranked between each shot, which is a significant nerf and requires more xXx420robustskillxXx i feel the range limit is too hard of a nerf.

I removed the range from ebows, and increased the price back to 12tc (i nerfed it to 10tc when i changed it to use 'reusable' shots)

For comparison:

Revolver - 13tc (DAT DAMAGE THO)
Ebow - 12tc (DAT INFINITE AMMO AND STUN THO)
Esword - 8tc (DAT EBOW + ESWORD THO)

Open to discussion.

### CODE REVIEW

**Comment by Miauw62** [comment]
>paprika buffing things

there are changelings on the station

**Comment by Cheridan** [comment]
I've seen people complain about the crank's message & sound diminishing it's value as a stealth weapon, might want to address that here too.

**Comment by paprka** [comment]
The sound should only be playing to the user, though. the ebow is suppressed and there's a check for that when reloading it.

**Comment by paprka** [comment]
Fixed ebow sound.

**Comment by Jordie0608** [comment]
Changelog.

**Comment by Fox-McCloud** [comment]
:+1: 

Dunno why this hasn't been merged yet.

**Pull request merged**
