### PR TITLE
Eternal Youth/Sentient Disease Fix [WEBBIT WARNING]

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request

Removes both old symptoms, adds a new one with middle-ground pricing.

Also removed random double lines and made it formatted consistently through the file.

## Why It's Good For The Game
It's a fix

## Changelog
:cl:
fix: Removed the 2 Eternal Youth Symptoms in Sentient Disease
balance: Added a new EY symptom that has middle-ground pricing of the 2 old ones.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
I hate web editors

**Comment by Dawson1917** [comment]
Does this increase the price of eternal youth in the symptom shop? Huge nerf to sentient disease if it does because every sentient disease has to rush a handful of people and get eternal youth as their first symptom to not get instantly spotted on medhuds and cured in their first 3 minutes

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes and No considering one was "medium" and the other was a "powerful heal".

**Comment by Dawson1917** [comment]
> 
> 
> Yes and No considering one was "medium" and the other was a "powerful heal".

As in is the Eternal Youth symptom you can buy on infecting 8(?) people more expensive or requiring more hosts in any way? The only viable way to play sentient disease currently is to get eternal youth while praying not a single member of medical department walks in _eyesight_ of even one of your hosts, then to rush viral adaption, and only then can you pick your first harmful symptom on infecting 16 people. EY requiring more points or hosts is a big nerf to a rare and already very weak antag

**Comment by ExcessiveUseOfCobblestone** [comment]
Requiring you build stealth to not get BTFO'd seems like an overarching issue that I don't think bandaiding by making the stealth symptoms cheap appropriately fixes.

**Comment by Dawson1917** [comment]
> 
> 
> Requiring you build stealth to not get BTFO'd seems like an overarching issue that I don't think bandaiding by making the stealth symptoms cheap appropriately fixes.

Sentient disease is in a horrible state right now but until someone reworks it there's no way to survive without taking stealth. Keeping Eternal Youth at its current cost (8 hosts, 4 points) while fixing the random duplicate symptom will at least not further gimp sentient disease until a PR is made completely changing how SE works. I have never in my life seen someone get enough hosts to afford the duplicate symptom or last tier of symptoms anyway

**Comment by ExcessiveUseOfCobblestone** [comment]
It's not it's current cost though, it's current is both the low and high hence why I made it in between because when I initially added them I don't remember the rationale to determine which is the "correct" one.

Bandaiding something is not the way to go because no one will fix it properly if you did it. I'm not going to use the lower cost one for that reason. That issue will just need to be fixed.

**Comment by Fikou** [comment]
just keep the medium one without the 16 point one uwu owo

**Comment by ExcessiveUseOfCobblestone** [comment]
It's a great buff symptom, I don't see why it should be just "medium".

**Comment by Fikou** [comment]
because you need that bandaid, that buff to stealth, usually with 4 people there wont be a person that instantly rushes the health analyzer if they cough/sneeze, but usually theres gonna be someone in that 8 that goes "oh boy i coughed once time to cure myself from a disease", stealth is a godsend

**Comment by ExcessiveUseOfCobblestone** [comment]
No, you need to fix it properly.

**Comment by MimicFaux** [comment]
> Sentient disease is in a horrible state right now but until someone reworks it there's no way to survive without taking stealth. Keeping Eternal Youth at its current cost (8 hosts, 4 points) while fixing the random duplicate symptom will at least not further gimp sentient disease until a PR is made completely changing how SE works. I have never in my life seen someone get enough hosts to afford the duplicate symptom or last tier of symptoms anyway

I have once managed to get my sentient disease to the end game where I was able to rot people eyeballs out. It was awful, mostly luck based, and the overall experience definitely highlighted some under-the-hood tweaks need to be made to smooth out the progression. A wider variety of symptoms, possibly even some more custom ones would be the place to start

**Pull request merged**
