### PR TITLE
Penetrator rounds for sniper rifle

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
They do a bit less damage than the normal rounds, and they don't stun, but they can pass through walls/mobs like an xray beam.

@RemieRichards do you have objections this since its your thing

This could serve as an alternate AI kill without having to buy a syndiborg

:cl: Kor
rscadd: Nuke Ops can now purchase penetrator rounds for their sniper rifles.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
SS13 GLOBAL MEMEFENSIVE

**Comment by Zilenan91** [comment]
WALLBANG AI DESTROYED MISSION ACCOMPLISHED

**Comment by KorPhaeron** [comment]
>damage = 60

**Comment by Cebasiz** [comment]
how many walls can it pass through and is there any damage reduction for each object it passes through

can i shoot the captain from space?

also when are we getting an instacrit sniper rifle for Xx360fullscopecaptainsnipesxX

**Comment by KorPhaeron** [comment]
>how many walls can it pass through and is there any damage reduction for each object it passes through

Forever and no

>can i shoot the captain from space?

Yeah if he's standing close enough to space for you to see him and doesn't move after you shoot him

**Comment by Cebasiz** [comment]
how many TC is a magazine of this stuff
i mean, if it goes forever it'll probably go into the spaceloop and just keep going right

if i were just to shoot this shit into the middle of the station could i kill lots of people by just magdumping hundreds of rounds into the station structure

so wait, does it go through R-wall?

can i literally buy this thing and just shoot the AI like 5 times from the shuttle and kill it?

>hey guys we need to nerf syndiborg it's too good at killing the AI

>here's an infinite range artillery X-ray weapon

man this shit is getting fucking weird fast

**Comment by KorPhaeron** [comment]
>how many TC is a magazine of this stuff

5. It costs 1tc to fire a single bullet.

>i mean, if it goes forever it'll probably go into the spaceloop and just keep going right

All bullets decay after 50 tiles

>so wait, does it go through R-wall?

Yes

>can i literally buy this thing and just shoot the AI like 5 times from the shuttle and kill it?

Yes.

>hey guys we need to nerf syndiborg it's too good at killing the AI

Syndiborg is silent AI kill+all access (comms dead as well)+incredibly robust infinite ammo extra team mate

This is just an AI kill.

**Comment by Cebasiz** [comment]
syndiborg is actually counterable by the AI. it trips motion sensors and even if it depowers you can shout on binary you're being killed at least

this isn't counterable at all. it's even lower effort, and you stand to lose even less considering many syndiborgs die on the way out to the borg brigade coming to the rescue.

this seems even worse than what you're replacing, which i get killed by all the time. it's actually impossible to counter, unlike the syndiborg which at least can be stopped if you're quick or lucky.

pls no merge, or at least limit it's ability/damage through R-wall.

**Comment by RemieRichards** [comment]
:+1:

**Comment by Steelpoint** [comment]
If you just want to kill the AI then give the Ops a button that just kills the AI.

**Comment by KorPhaeron** [comment]
A button to kill the AI wouldnt let me use thermals+zoom to take out people through walls

**Comment by Steelpoint** [comment]
Ehh you do have a point.

What is the rate of fire for the sniper per chance?

**Comment by Jalleo** [comment]
Remember to have a max limit of tiles that it can go or we will forever have rifle rounds going in a loop sometimes.

**Comment by RemieRichards** [comment]
@Jalleo all projectiles die after 50 tiles unless revived (like reflectors, reflectors revive projectiles so if you set up a bunch of Box reflectors in space facing the same way you could keep a projectile alive)

**Comment by KorPhaeron** [comment]
@Steelpoint 

I think there is a 4 second delay @RemieRichards can correct me if I'm wrong

**Comment by RemieRichards** [comment]
Yep, 4 seconds

**Comment by Steelpoint** [comment]
Overall I think the ammunition gives it some utility, the low rate of fire does hamper it but I think it somewhat balances out the ability to fire through anything. However it's effectiveness against the Head of Security and the Captain are a bit more questionable, while the (pathetic) resistance of a stock Officers armour won't make a difference, the HoS's armour will require three shot's to crit, however the Captain will still only be a two shot crit unless somehow the Op only hits the Captain's chest (Hat offers minor protection to the carapace).

**Comment by Steelpoint** [comment]
Disregard last part of my post I forgot the sniper has 50 AP so fuck HoS and Captain its a two shot crit.

**Comment by KorPhaeron** [comment]
I think AP on sniper rounds means its flat out 2 shots 2 crit on just about anyone but death squad.

They already have those ridiculous bulldogs that do the same thing though and the ammo for that is incredibly cheap/spammable

Keep in mind the sniper requires two hands to fire as well so you'll have to ditch your bag or jetpack.

Will be interesting to see how effective this is outside of AI killing, with its slow rate of fire.

**Comment by Steelpoint** [comment]
While I still think someone with armour should have double the survivability than your average joe, instead of being able to take only a single more bullet before dying, but I digress.

The Sniper's going to be a support item, one guy's going to take it to snipe the AI and then just lug it around in his backpack (can it fit in the pack?). Maybe he'll use it if the situation presents itself but otherwise he'll be back to his good old Bulldog/C20/M90.

**Comment by KorPhaeron** [comment]
>can it fit in the pack?

Nope

Even if it never gets used outside the AI kill though at least this might free up telecrystals to try other thans rather than the obligatory syndiborg which has a stranglehold on the meta

**Comment by WJohn** [comment]
I think they should probably be called bluespace rounds, penetrator round sounds like something that could go through a person/armor, not a wall.

**Comment by Steelpoint** [comment]
Reminds me a bit of that one Star Trek DS9 episode where a "individual" was using a (spoiler) unique ballistic sniper rifle that teleports a bullet into any room the instant it fires, allowing the sniper to be at any position they chose when operating the weapon and giving no trace as to the origin of the bullet.

**Comment by KorPhaeron** [comment]
Yeah but bluespace is nanotrasen tech and the syndies are trying to steal it all the time (hand tele, teleport armour). Would be kinda anti thematic to give them bluespace bullets.

**Comment by Steelpoint** [comment]
Well all these years of Traitors stealing bluespace technology has got to yield some benefit to the Syndicate Special Forces eventually? 

Historically its clear someone already stole NT Cyborg blueprints and similar technology in sufficient numbers to allow the Syndicate to produce knock off Assault Cyborgs en mass, so why not simply state that these bullets are the result of years of theft and research application by the Syndicate.

**Comment by Steelpoint** [comment]
I mean, if we going for the approach of the syndi's having no NT tech then we crossed that bridge a very long time ago.

**Comment by Dorsisdwarf** [comment]
Make it leave a big hole sprite on the wall and have a limit of 4 things

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

I'm not spriting walls with holes in them+coding those walls+coding a new bullet var for limited object passing

**Comment by Robustin** [comment]
Now this is fun and actually makes the sniper useful for operatives at something besides teamkilling.

Penetrating R_walls is super duper questionable though. Its necessary to make it rek the AI, but I'm not too comfortable with the strongest obstacle in the game getting pierced like paper mache.

A single gun+penetration is probably fine balance wise but I see massive problems with taking two or more at a time. Combine it with a scope and thermals and the ops are one shotting people from space. 

However, if the ammo is sufficiently high cost I think it would still be ok. I love the idea of operatives critting the warden from space and entering the armory without the mandatory "WOAH OPERATIVES ARMORY OH GOD".

**Comment by KorPhaeron** [comment]
2 thermals (12) points plus 2 snipers (32 points) plus 2 magazines of penetrator ammo (10) points would be quite the investment

**Comment by Steelpoint** [comment]
The only way you could get a reliable crit shot on the Warden is if you have two Pen Snipers in position, though only one of them would need a set of Thermals as the other could take a alternative position and call the position out for the other sniper.

**Comment by Shapsy** [comment]
Even then, getting critted out of nowhere with no warning and literally no way to fight back sounds awful. I don't see how doing a full tacticool breach of the armory and having a massive shootout with the warden/other security is less fun than clicking on him from the other side of a wall twice before he can react (and saying that you need 2 rifles to crit the warden quickly is silly, since I really doubt most players would be able to realize they've been shot, realize where they've been shot from, realize they've probably been shot by a nuke op with a sniper rifle, and then run away [at reduced movespeed because you just got shot] out of the extended range of the sniper rifle all within the four seconds it takes to chamber another shot, or even just calling for help in that time). 

>However, if the ammo is sufficiently high cost I think it would still be ok. I love the idea of operatives critting the warden from space and entering the armory without the mandatory "WOAH OPERATIVES ARMORY OH GOD".

You mean the whole "giving the warden a fair chance to fight back" or "breaking into the highest security part of the station through brute force raising alarms" part?

**Comment by Robustin** [comment]
Yea my example was implying the existence of... A SECOND SHOOTER! (never forget the grass knoll).

Realistically Shapsy my example and your concerns are probably irrelevant, NukeOps aren't on Teamspeak together, they can barely use the red button without accidentally gibbing a couple teammates, coordinating sniper fire is a challenge that few teams would rise to meet. There's plenty of ways to fuck with people as operatives in a way that gives them no realistic chance to fight back.

Double snipe from space I could at least respect the coordination and investment it takes to pull that off, compared to say, a borg emagging the secpod, ops flood in and blow your PDA right before rushing the armory and executing you while you lie on the ground. Just give the penetrators a highly visible tracer and a sufficiently identifiable noise and most of my balance concerns would be resolved.

**Comment by Lumipharon** [comment]
54 tc for 2 sets of snipers, thermals and pen mags isn't that much considering you can use it to ggnore people through walls, off screen (does the sniper scope thing work with thermals?)

In general the idea seems neat, but being able to just burn a hole through half the station and 30 r-walls seems a bit much.

**Comment by Robustin** [comment]
Yea it will probably silly, but the more I think about it - this has to be one of those combinations that produces absurd results or its simply not worth the massive investment and effort it takes to get a sniper fire team up and running.

Just like all the other gimmicky nukeop gear it will be resigned to misclicks and flukeops if it doesn't have some OP aspects to it. Once people are aware of nukeop snipers (with loud noise + identifiable tracer it won't take more than a few shots) it will be easy to move away from the edge of the station and keep moving, plus if the snipers don't have protection then one nerd with a prod can sneak up on you and dunk you (on that note remove syndie firing pin bullshit I want to snipe ops in their shuttle).

**Comment by Zilenan91** [comment]
How much health does the AI have btw because if this thing doesn't 2 shot the AI it's not very good. 4 seconds is a long time for the AI to notice it's dying.

**Comment by Stenthus** [comment]
I'm not entirely sure it would be clear to people first seeing the name "penetrator round" that it literally goes through EVERYTHING.
I know personally when I read the title I thought it would just be like a 75 damage super high armor piercing shot or something.

The AI killing aspect makes sense but it's a bit awkward that you will likely get people who meta know stuff like "oh go to this area of space and stand on this exact tile and shoot right and the AI will die" which sounds pretty lame.

Tentative +++ but I'd watch how people use it so it isn't TOO lame to be on the receiving end of.

**Comment by Dorsisdwarf** [comment]
Suggested rename: "Ghost rounds".

**Comment by optimumtact** [comment]
update to latest master
git rebase -Xignore-all-whitespace upstream/master

**Pull request closed without merging**
