### PR TITLE
Changes what appears for urgent ahelps to supportmins.

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

It now looks like this instead. You can ignore the 'Description' above the headers because I forgot to remove that when I tested it
image
Includes round time (time in the round for which the ahelp was made) and round ID. Admins are recommended to suggest other information that could be useful

## Why It's Good For The Game

Looks better, can fit more information without it becoming harder to read.

## Changelog

:cl:
admin: Urgent ahelps will now send more information to admins to assist with handling your ahelp.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
As a Supportmin, I think more information is also useful.

Two things that I've mentioned in the past (although I am unsure on feasibility) would be the BYOND link to quickly join the server (save me like ten seconds of effort, so maybe not so important), as well as current round status (i.e. if the shuttle is called or on the way to Centcomm)

**Comment by Watermelon914** [comment]
> As a Supportmin, I think more information is also useful.
> 
> Two things that I've mentioned in the past (although I am unsure on feasibility) would be the BYOND link to quickly join the server (save me like ten seconds of effort, so maybe not so important), as well as current round status (i.e. if the shuttle is called or on the way to Centcomm)

yes I was planning to do this

**Comment by Mothblocks** [comment]
Can you include any stealthed admins? Urgent ahelps are offered if admins are online, but stealthed (which is good), but it's a bit funky to log on and have someone already dealing with the ticket.

**Comment by Watermelon914** [comment]
> Can you include any stealthed admins? Urgent ahelps are offered if admins are online, but stealthed (which is good), but it's a bit funky to log on and have someone already dealing with the ticket.

ok

**Pull request merged**
