### PR TITLE
[WIP] Mafia New Roles and Changeling Team Nerfs, And Achievement Png Cleanup

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

image

### Three new roles, all of which can kill as that is what security is for 😎 :
"Security Officer"
"You can protect a single person each night. If they are attacked, you will retaliate, killing yourself and the attacker."

"Head of Security"
"You can decide to execute during the night, killing and revealing them. If they are innocent, you will die at the start of the next night."

"Warden"
"You can decide to lock down during the night, twice per game. Anyone who visits you during this time will be killed."

Notice how I didn't do Jailor. Jailor is a bad role that hijacks games and i'm avoiding adding it

### Removed roles

Removes mafia's special role thoughtfeeder from normal rotation for the time being. Explanation in the Why section. Ignore Parastingling, it's derelict code and will be gone soon.

### Role Balanace

Nightmare now cannot be attacked by roles that they flickered. They needed this, they're so pitiful and I just removed one of the two roles they countered

### Achievement stuff

Along with new achievements, I've made each team's win achievement generic. This should stop me from needing to make a new PNG with each new role, which is a terrible idea. They're also like, readable now?

## Why It's Good For The Game

Surprisingly, giving town killing roles is a huge shift in favor of town. Right now as mafia, it matters very little who you kill since you're just giving a clock towards endgame. With the knowledge that there are now night dangers and revealing too much during the day can get you killed at night by the head of security, this may lead changelings to put more thought into who to kill.

### "You're removing thoughtfeeder?"

While I love you thoughtfeeder, the informed minority just don't need a power role right now. It's really cool to see changelings egging on clowns or obsessed to screw town, but they can do it too easily and too safely. Right now, obsessed and clown are some of the easiest roles to win as. (It was this or bump mafia down to 2, which is boring)

I plan on readding them + Parastingling as a different minority power role to shake things up, but I need to decide on whether refactoring how revealing works so every kill reveals would be a better idea or not. I love how our current reveal system makes people wear their true clothing, and I love how we have unique-to-ss13 roles because of our reveal system.

## Changelog
:cl:
add: MAFIA: Watch out, changelings! The Head of Security and his Security Officers are here as new roles!
del: Removes thoughtfeeder for now. They're still possible in admin games, and will be back in the main roster when I can balance it
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
you didnt add a warden medal

**Review by Twaticus — APPROVED** [review]

**Comment by tralezab** [comment]
I haven't added warden at all yet, I've been removing Parastingling role until this point

**Comment by Gamer025** [comment]
Good PR

**Comment by SpaceManiac** [comment]
This PR has been marked "Work In Progress" for almost 2 weeks. I'm closing it as stale.

**Pull request closed without merging**
