### PR TITLE
THERE IS NO OGG! I LIED!

### PR DESCRIPTION
**Pull request by Kapu1178**
Fixes mislabeled audio files. @francinum and I found this while working on https://github.com/tgstation/rust-g/pull/192

image
https://www.youtube.com/watch?v=plrlrGtoiik

### CODE REVIEW

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Would rather you reformat them to ogg--these would be the only mp3 files in the entire codebase

Also it's surprising to me that symphonia or whatever library cares about the file extension instead of figuring it out from the data? But whatever

**Comment by Kapu1178** [comment]
> Would rather you reformat them to ogg--these would be the only mp3 files in the entire codebase
> 
> Also it's surprising to me that symphonia or whatever library cares about the file extension instead of figuring it out from the data? But whatever

The issue with symphonia was I forgot to actually turn on the mpa decoder feature, so it was not able to decode the ogg file.

**Comment by Sadboysuss** [comment]
Holy shit this is why optivorbis nuked them

**Comment by Ghommie** [comment]
🤯

**Pull request merged**
