### PR TITLE
Omegstation SM engine mapfix

### PR DESCRIPTION
**Pull request by Shuffl3**
Whangjangles some pipes and filters around the engine to make it
functional

http://i.imgur.com/NgAZr7M.jpg

Bleh, mapmerge issues. edited with fastdmm...

tweaked the arraignments of the south fridgeline to reflect the corrected flow.

http://i.imgur.com/e7H51Tw.jpg

### CODE REVIEW

**Comment by Shuffl3** [comment]
lol, fuck if I know whats up. compiles fine for me.

**Comment by optimumtact** [comment]
you need to remove the _maps/map_files/OmegaStation/OmegaStation.dmm:	step_x = 0 in omega station.

this var can cause movement ot break by activating pixel movement mode.

**Comment by voneiden** [comment]
While you're at it, would it be a good idea to swap those air scrubbers into empty plasma containers?

**Comment by Shuffl3** [comment]
I think the intent of the mapmaker was to replicate the Deltastation layout. This just corrects a mirroring error from having the core pumps on the north side instead of the sound. So I feel that making actual changes falls outside the scope of this PR.

**Comment by Shuffl3** [comment]
http://i.imgur.com/Cr7CDKv.jpg

**Comment by optimumtact** [comment]
Thanks

**Pull request merged**
