### PR TITLE
Formaldehyde now consumes only 0.05 units of silver for 1 unit of production

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
Read Title

Now only 0.05 units of silver is required to create 1 unit of formaldehyde OR 1 unit of silver can produce 20 units of formaldehyde i.e. you can now make more with less silver

## Why It's Good For The Game
1. Silver is a rare metal that requires miners. 1 slab/ore of silver gives 2000 worth of material, but grinding one slab of silver only gives 20 units of liquid silver. So consuming 2000 units of precious silver to create just one vile of formaldehyde is a huge waste of material for all departments.

2. In the event say all stasis beds in medbay are destroyed and the station is very low on materials(say silver) and everyone is either dead/injured, Formaldehyde is a life saver in this situation as it can preserve dead bodies for revival and can also heal injured crew members via [medical suture](https://tgstation13.org/wiki/Guide_to_chemistry#Medicated_Suture). So mass producing formaldehyde without consuming too much silver will allow other departments to use more for their purposes.

3. Formaldehyde has a large variety of applications such as in the creation of Herapin, Pentaerythritol, Acetaldehyde, and Pentetic Acid And medicated sutures so large amounts of formaldehyde will get consumed per shift, so its good to conserve silver

## Changelog
:cl:
balance: formaldehyde now consumes only 0.05 units of silver to create 1 unit
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
> In the event say all stasis beds in medbay are destroyed and the station is very low on materials(say silver) and everyone is either dead/injured, Formaldehyde is a life saver in this situation as it can preserve dead bodies for revival

Cryostylane already fills this niche and does in a better way as it even colors the corpses to blue, you instantly know "This guy's organs are safe" without having to double check every corpse.

**Comment by SyncIt21** [comment]
> > In the event say all stasis beds in medbay are destroyed and the station is very low on materials(say silver) and everyone is either dead/injured, Formaldehyde is a life saver in this situation as it can preserve dead bodies for revival
> 
> Cryostylane already fills this niche and does in a better way as it even colors the corpses to blue, you instantly know "This guy's organs are safe" without having to double check every corpse.
> 
> Honestly, Formaldehyde is one of the many medbay noob traps.

It's good to have options, if not for preserving corpses then for creating medical suture formaldehyde is still important and shoudn't consume silver.

**Comment by RikuTheKiller** [comment]
> > In the event say all stasis beds in medbay are destroyed and the station is very low on materials(say silver) and everyone is either dead/injured, Formaldehyde is a life saver in this situation as it can preserve dead bodies for revival
> 
> Cryostylane already fills this niche and does in a better way as it even colors the corpses to blue, you instantly know "This guy's organs are safe" without having to double check every corpse.
> 
> Honestly, Formaldehyde is one of the many medbay noob traps.

As long as you keep in mind that cryostylane slows down surgery by quite a bit, especially if it's impure.
This is a pain in the ass while reviving, so formaldehyde, in the end, is better if you can get a hold of it.

I still like this change because it would make pentaerythritol much less of a pain to make since it takes a fuckton of formaldehyde to make a small amount of it.

**Comment by GuillaumePrata** [comment]
> As long as you keep in mind that cryostylane slows down surgery by quite a bit, especially if it's impure.
This is a pain in the ass while reviving, so formaldehyde, in the end, is better if you can get a hold of it.

Synthflesh exists and makes revival without dealing with surgery times possible and easy.
Formaldehyde is not better, it is an option, and is the worst one because you need to manually check every corpse for it or some might decay without it, wasting even more time with replacement surgery while Cryostylane instantly tells everyone that the corpse is safe and don't need to be in a stasis bed either.

Instant medbay communication between doctors >>>>> 30-60 seconds wasted doing slower surgery (if opted in).

**Comment by EOBGames** [comment]
Just to note: this has been attempted before, and was closed due to the reasoning of it making formaldehyde too readily available (see here: https://github.com/tgstation/tgstation/pull/54412 and https://github.com/tgstation/tgstation/pull/54327 for details).

**Comment by YakumoChen** [comment]
> Silver is a rare metal that requires miners. 

False, silver is a default chem dispenser item.

**Comment by ATH1909** [comment]
> Cryostylane already fills this niche and does in a better way as it even colors the corpses to blue, you instantly know "This guy's organs are safe" without having to double check every corpse.
> 
> Honestly, Formaldehyde is one of the many medbay noob traps.

or you could just... mark the corpses in a way that doesn't impede surgery and slowly decay over time?

**Comment by GuillaumePrata** [comment]
> or you could just... mark the corpses in a way that doesn't impede surgery and slowly decay over time?

Good luck making an universal mark IC that is instantly understood like how cryostylane works between the people that know how the chemical exists.

If you can use your time IC to mark corpses that are safe, you can use your time IC to improve the speed of the surgery and counter the only issue with cryostylane over formal, as the decay rate is so slow it should never be an issue.

Cryostylane was well designed as a organ protection chem, formaldehyde was added in a simple way and never improved in any way to help medbay more, instead it was constantly nerfed because of secondary reasons like Pentic Acid being the fix everything chem.

It is really a shame that the chemical with good UX is unused over the chemical that has no feedback to players.

**Comment by YakumoChen** [comment]
Just add a medhud overlay if the corpse has a preservation chem in it, its not an impossible challenge.

**Comment by Draggeru** [comment]
> Honestly, Formaldehyde is one of the many medbay noob traps.

As a medbay main this is completely incorrect.

Formaldehyde is one of two reasons why I'm a medipen goblin. Dead body? Epi-pen them. Someone bleeding? Epi-pen them.

Formaldehyde being "too readily available" is a really dumb take, and is one of the only other counters medical has at their disposal to prevent organ rot.

If you're a tot trying to revive another tot and you have a lot of heat on you, it's a blessing to be able to leave the corpse for any length of time and come back to it in the same condition you left it in.

**Comment by GuillaumePrata** [comment]
> As a medbay main this is completely incorrect.

You missed my point, is Formaldehyde effective, yes, it is quite effective.
But it is a noob trap compared to Cryostylane as Cryostylane makes things a lot smoother on a medbay shift when you have a pile of corpses that you know are safe in a glimpse.

This is not the first PR trying to make it easier to create, and it won't be the last if it is closed.

People are fixated on making Formal easier to use because they don't like to be dependent on miners to deal with organ rot, they also don't want to deal with the minor side effects like Cryostylane or ask for cooperation with other departments like Strange Reagent or Pluoxium.

Making things easier to do by yourself independently is often a step backwards into making rounds interesting.

**Comment by Fikou** [comment]
> So #54412 had 26 people upvote and was closed because one maintainer disagreed

yeah thats how prs work

**Comment by san7890** [comment]
do catalysts "degrade" (i.e. lose overall units) the more reactions they assist in?

**Comment by SyncIt21** [comment]
No they don't degrade when infact they should. That would be a huge PR to make where we need a sheet
 of standard values for all reactions and a huge wiki update as well.

The sheet should be per unit of reagent created in a reaction,  how many units of catalyst should be consumed.

If you could provide said sheet then I could draft this PR till I or someone else implements it which I'm fine with.

**Comment by san7890** [comment]
doesn't universal enzyme lose some volume every time you use it for a reaction? i recall that being a thing when i played chef. that's the only reason why i asked is because universal enzyme is a catalyst (yea duh) and it did that from my recollection of the game a few years back

**Comment by SyncIt21** [comment]
A few years back? Is that still the case though? Silver isn't consumed in formaldehyde creation,  just tested it now, maybe there is a variable I'm not aware of?

**Comment by san7890** [comment]
i don't know if it's still the case or not that's why i was asking here

**Comment by SyncIt21** [comment]
Ok so i looked at the code and it turns out consuming catalyst per reaction is quit easy to do actually but like you said its out of scope for this PR and we would have to change existing reaction values because the current values would consume the catalyst very quickly.

Also you were right about universal enzyme, it did get consumed as a catalyst at one point until #56019 removed it

But even though its possible , this creates a question, if we make catalysts get consumed slowly per reaction then what makes it any different than regular reagents that gets consumed in a reaction?

Sure from a coding perspective when the catalyst gets fully consumed the subsystem early returns, saving processing time but from a player perspective the catalyst has become just like a regular reagent.

The solution? Let's just reduce the amount of silver consumed so we can make more with less. 0.05 units of silver sounds good, Why? because with this multiplier 1 unit of silver can now produce 20 units of formaldehyde(together with 20 units of ethanol and water that is) and 20 units of formaldehyde can now be used to make 1 medical suture, 

Another comparison if you grind 1 silver bar you get 20 units of silver and with that much silver you can now make 400 units of formaldehyde or 4 full beakers of formaldehyde or 1 bluespace beaker(300 units) + 1 beaker of formaldehyde. That's a lot you might ask and yes that is true but given how rare silver is and given how many applications formaldehyde has (Herapin, Pentaerythritol, Acetaldehyde, and Pentetic Acid, And medicated sutures) formaldehyde will get used pretty quickly so its good to produce large amounts

**Comment by JohnFulpWillard** [comment]
I don't think I want to add this. 1 bar of silver is 60 patches of Formal, it's already kind of absurd.

**Comment by DustanHache** [comment]
> I don't think I want to add this. 1 bar of silver is 60 patches of Formal, it's already kind of absurd. As brought up in my [sentient disease PR](https://github.com/tgstation/tgstation/pull/74343), you can get silver from deconstructing operating tables if it's very much required, however you can also be asking Paramedics to give what they spawn with to make patches out of those instead.
> 
> There's a lot of alternatives, and I don't see "it uses mats" as a problem, we WANT the station to be using materials.

then for the love of god willard, give us a way of sustainably replacing the rarer materials that isn’t xenobio! 

resource scarcity only encourages people *not* to make consumables because there are tools and other reusable items that provide more value overall for the material in question compared to chems like lenturi and formaldehyde. this includes: 

- path of blades heretics, who consume a ton of silver making/replacing their weapons
- tier 3/4 stock parts
- advanced/alien surgical tools
- virology uranium gels for the two tier 8 symptoms
- advanced organs and cybernetics
- modsuit modules

We either need more silver, or we need to consume less of it to encourage more exotic chem production.

**Comment by SyncIt21** [comment]
> I don't think I want to add this. 1 bar of silver is 60 patches of Formal, it's already kind of absurd. As brought up in my [sentient disease PR](https://github.com/tgstation/tgstation/pull/74343), you can get silver from deconstructing operating tables if it's very much required, however you can also be asking Paramedics to give what they spawn with to make patches out of those instead.
> 
> There's a lot of alternatives, and I don't see "it uses mats" as a problem, we WANT the station to be using materials.

60 patches of formadehyde, whats so great about that? what about the other applications of formaldehyde, read the PR body, its also used for
- Herapin
- Pentaerythritol
- Acetaldehyde
- Pentetic Acid 
- medicated sutures

These all require a great amount of formaldehyde, also the fact you are saying deconstructing operating tables to get silver is just normal and that's how we should be making formaldehyde like what the hell? The whole point of this PR is too stop players from doing that on a regular basis , in the event there are no miners if they do end up destroying a table it should atleast last sufficiently long, because with the current system you have to destroy 2 tables to get enough formaldehyde to full up just 1 beaker. 

Paramedics can provide formaldehyde only for round start, so what happens after that supply runs out cause it will very quickly based on the above specified applications. 

What you are suggesting are methods on how to scavenge & beg for formaldehyde and not how to produce atleast an reasonable amount till we absolutely have no choice

**Comment by YakumoChen** [comment]
You can order crates of medipens for free from cargo if you're a paramedic 

Why it isn't the first thing ordered from the console would be an interesting question

**Comment by JohnFulpWillard** [comment]
> resource scarcity only encourages people not to make consumables because there are tools and other reusable items that provide more value overall for the material in question compared to chems like lenturi and formaldehyde.

This is not a bad thing, if miners are not bringing up enough materials for everyone to get what they want, then some sacrifices should be made.

> These all require a great amount of formaldehyde, also the fact you are saying deconstructing operating tables to get silver is just normal and that's how we should be making formaldehyde like what the hell?

I said if it's required. 1 table = 40 units of Silver, at the cost of not having a table until miners bring more materials up.

> Paramedics can provide formaldehyde only for round start

Which gives you room to wait for miners to do their job.

I still do not see the problem with the reliance on materials for advanced things like medicated sutures.

**Comment by SyncIt21** [comment]
> 1 table = 40 units of Silver

Wrong 1 table gives you a silver bar which when grinded gives only 20 units not 40

> Which gives you room to wait for miners to do their job.

Miners are not guaranteed to bring back silver reliably because of its rareness, so in the event they do bring some back we should use it sparingly because other departments also require it!!!. Like i said in the PR one silver bar is 2000 units of material and we have to grind that to produce just 20 units of formaldehyde, this is a huge waste for all departments so we should be considerate for everyone else and make our silver supply last longer

> In the https://github.com/tgstation/tgstation/pull/54412, this was brought up by the guy who removed Silver from the dispensers in the first place:
 "This is a crypto-revert of a PR merged just 3 hours ago since it removes the increase scarcity which was the maint point of the PR."

Silver as a catalyst isn't consumed at all and so you could reuse that infinite amount of times to create formaldehyde, sure i agree that is power gaming but this PR is different, here we consume very small amounts of silver and make it last longer till we need to get some more. I changed this entire PR after reading that comment

**Comment by YakumoChen** [comment]
Is silver scarcity even a real problem beyond 15 minutes in the round? It's the second most common ore on lavaland.

**Comment by JohnFulpWillard** [comment]
I still disagree with this PR, if other chems are too strong then maybe those chems should be rebalanced.

**Comment by DustanHache** [comment]
> Is silver scarcity even a real problem beyond 15 minutes in the round? It's the second most common ore on lavaland.
> 
> Almost never see a shortage of it unless all the miners die early.

it happens more often than you might think, especially when your miners are more interested in megafauna hunting than material hoarding. also, it is isn’t as common as you claim it to be, with iron, plasma, titanium and gold being more common by far (and in the case of plasma, diamond, uranium and gold, having alternative sources for generation as well.)
Also as a reminder, it is consumed by numerous jobs in numerous applications. heck, even bluespace RPEDs eat a sheet of silver right after being unlocked.

> The only argument I see being made that the main point of this PR is for is keeping bodies iced, and again, medipen crates are your friend.

You completely ignored the other chems that used formaldehyde (which was brought up) and the fact that medipens are single use (with that use either being extracted by syringe or dumped into someone’s body in a pinch all at one time.) your argument is “hurr duur just source through cargo” while ignoring the fact that cargo isn’t able to solve the problem.



> I still disagree with this PR, if other chems are too strong then maybe those chems should be rebalanced.

oh *please*, by all means nerf aiuri, the *direct competitor and second most commonly used chem after fucking libital*. that will *clearly* fix the issue of chems being unused, obviously! /s
I’ve already told you why people won’t make these chems. you’ve just flat out ignored it because scarcity for the sake of scarcity was pushed and somehow upheld previously. just put lenturi and formaldehyde out of their misery already if you want to be a buzzkill, and remove the recipes for them from the game.

**Comment by Xander3359** [comment]
Bro just go to public mining, this isn't yog station.

**Comment by YakumoChen** [comment]
> it happens more often than you might think, especially when your miners are more interested in megafauna hunting than material hoarding. also, it is isn’t as common as you claim it to be, with iron, plasma, titanium and gold being more common by far (and in the case of plasma, diamond, uranium and gold, having alternative sources for generation as well.)
Also as a reminder, it is consumed by numerous jobs in numerous applications. heck, even bluespace RPEDs eat a sheet of silver right after being unlocked.

https://github.com/tgstation/tgstation/blob/1d8af08e13ea72a01f8891dbffad745db6f1b860/code/game/turfs/closed/minerals.dm#L202

Definitively not true, silver is the third* (I forgot plasma) most common ore on lavaland, and in some cases (in high-mineral enviroments) tied with plasma at #2

Mineral scarcity stops being a thing the moment plasma cutters are researched, as it allows miners to get ore much faster (or die trying, but it's rare all miners die early)

**Comment by DustanHache** [comment]
> Mineral scarcity stops being a thing the moment plasma cutters are researched, as it allows miners to get ore much faster (or die trying, but it's rare all miners die early)
> 
> It's used in a lot of applications sure, but it's hardly rare enough to burn through it past the second or so miner drop-off.

I don’t know what reality you’re living in then, but from personal experience miners usually don’t go back for a “second load” once they get their megafauna hunting equipment. they might come back to the station after they get as much loot as they can/survive the bosses, but after that they don’t go back down. that’s assuming you’re lucky enough to have them come back at all. this is in spite of the absurdity that is the plasma cutter, the buffed resonator mining, *and* AOE mining blast PKA.

> 
> The main (and only really important) use of it is for body preservation. Medipens are everywhere in medbay, finding more is a very low level issue and you don't need huge bottles of it early in the round, so I don't agree with your opinion.
> 
> Other chems to make with it aren't so important you need near-infinite volumes before silver scarcity stops. Most of them aren't notable, Pentetic Acid is the one exception and Multiver + Siever does the same job absolutely fine. Heparin I guess if you want to murder, but I wouldn't consider that a beneficial reason for this PR.

sutures are far more valuable than you would believe, along with medicated mesh. firstly, they are one of the only healing sources that can affect simplemobs and basicmobs (which is huge since the only other thing that can do that is strange reagent, and it only works if the mob is dead.) additionally, most crew who aren’t using chems will default to using sutures for healing their brute damage, and for treating bleeding wounds.

these consume 20u of formaldehyde *per stack*, which in case you haven’t guessed is not a trifling amount by any metric. Pentetic acid has thankfully become less problematic with the newly added ammoniated mercury, but it’s still invaluable for purging toxin heavy patients when lung damage is a concern or an allergy is in play.

> > Pentaerythritol, Acetaldehyde
> 
> I have never heard of these chems and I had to look them up only to find one was only useful for making a worthlessly niche chem and suicide explosives (not a good reason for this PR) and the other is literally unused. Very important chems, I'm sure.

Penthrite and it’s inverse nooartium are extremely valuable to medical for fixing up patients in a hurry, since one of the effects penthrite has is a healing factor like atropine (and nooartium literally prevents a patient from dying until 500 damage has been sustained, which is downright absurd when you are in a high stress situation with people trying to murder your patient.) However, it consumes a massive 3.3 u formaldehyde just to get it refined into the precursor chems. additionally it requires wittel, which is obscure to the point of stupidity because it too is sourced from lavaland. also, unlike silver, miners *dont* hunt for geysers.

**Comment by RikuTheKiller** [comment]
> > Mineral scarcity stops being a thing the moment plasma cutters are researched, as it allows miners to get ore much faster (or die trying, but it's rare all miners die early)
> > It's used in a lot of applications sure, but it's hardly rare enough to burn through it past the second or so miner drop-off.
> 
> I don’t know what reality you’re living in then, but from personal experience miners usually don’t go back for a “second load” once they get their megafauna hunting equipment. they might come back to the station after they get as much loot as they can/survive the bosses, but after that they don’t go back down. that’s assuming you’re lucky enough to have them come back at all. this is in spite of the absurdity that is the plasma cutter, the buffed resonator mining, _and_ AOE mining blast PKA.
> 
> > The main (and only really important) use of it is for body preservation. Medipens are everywhere in medbay, finding more is a very low level issue and you don't need huge bottles of it early in the round, so I don't agree with your opinion.
> > Other chems to make with it aren't so important you need near-infinite volumes before silver scarcity stops. Most of them aren't notable, Pentetic Acid is the one exception and Multiver + Siever does the same job absolutely fine. Heparin I guess if you want to murder, but I wouldn't consider that a beneficial reason for this PR.
> 
> sutures are far more valuable than you would believe, along with medicated mesh. firstly, they are one of the only healing sources that can affect simplemobs and basicmobs (which is huge since the only other thing that can do that is strange reagent, and it only works if the mob is dead.) additionally, most crew who aren’t using chems will default to using sutures for healing their brute damage, and for treating bleeding wounds.
> 
> these consume 20u of formaldehyde _per stack_, which in case you haven’t guessed is not a trifling amount by any metric. Pentetic acid has thankfully become less problematic with the newly added ammoniated mercury, but it’s still invaluable for purging toxin heavy patients when lung damage is a concern or an allergy is in play.
> 
> > > Pentaerythritol, Acetaldehyde
> > 
> > 
> > I have never heard of these chems and I had to look them up only to find one was only useful for making a worthlessly niche chem and suicide explosives (not a good reason for this PR) and the other is literally unused. Very important chems, I'm sure.
> 
> Penthrite and it’s inverse nooartium are extremely valuable to medical for fixing up patients in a hurry, since one of the effects penthrite has is a healing factor like atropine (and nooartium literally prevents a patient from dying until 500 damage has been sustained, which is downright absurd when you are in a high stress situation with people trying to murder your patient.) However, it consumes a massive 3.3 u formaldehyde just to get it refined into the precursor chems. additionally it requires wittel, which is obscure to the point of stupidity because it too is sourced from lavaland. also, unlike silver, miners _dont_ hunt for geysers.

Nooartrium is immortality, not 500 damage. Your heart explodes once it finishes metabolizing if you reach 500, though.

**Comment by YakumoChen** [comment]
Skill issue, make do with less or go mine it yourself.

**Pull request closed without merging**
