### PR TITLE
Updates Lava Sprites

### PR DESCRIPTION
**Pull request by WJohn**
Updates lavaland's lava sprites. These always bothered me and I said I'd do this eventually so here we are.

Full pics would be too big a pain in the ass so here's a consolation prize(?)

:cl: WJohnston
imageadd: Lavaland lava probably sorta looks better I guess.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
picture where

**Comment by RemieRichards** [comment]
@WJohn gotta include ```.png``` (I did it for you)

**Comment by WJohn** [comment]
Ah, was wondering about that. Thanks.

**Comment by ChangelingRain** [comment]
This does look rather nice.
how'd you get those pics lung

**Comment by KorPhaeron** [comment]
Thanks

**Pull request merged**
