### PR TITLE
Anomalous Medical Machinery -- The Purge-O-Matic 3000

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

Introducing: The Purge-O-Matic 3000 -- Your one-stop shop for drug/poisoning recovery!

purgema

This ingenious device absorbs chemicals from its occupant's body, and releases it as a localized cloud of chemical gas. During this process, it also reduces addiction points and slowly heals the user's liver. It only purges until there are 5 units of whatever left, but it makes up for it with SPEED and EFFORTLESSNESS.

Comes with part upgrade effects (faster chemical purging/addiction point removal) and a pretty gnarly emag effect.

balls

It is locked behind **biotech research**, and requires a **bioscrambler anomaly core** as a construction component. The board can be printed at circuit imprinters or medical techfabs.

_I came up with "Purge-O-Matic 3000" because just calling it the "Purger" felt a bit too on-the-nose. The plan was to come up with a better name but now it's grown on me and I can't part ways with it._

## Why It's Good For The Game

Allows medical to automate the low-priority task of dealing with drunkards and junkies. Allows those drunkards and junkies to get back to drinking and/or junking faster.

Gives a use for bioscrambler cores other than just the reactive armor. The anomalous thermomachine PR made me realize how few uses some anomaly types actually have, so I thought I'd try my hand at making something for another neglected core type.

## Changelog

:cl: Rhials
add: The Purge-O-Matic 3000, a chemical purging medical machine powered by a bioscrambler anomaly core.
imageadd: Some screen overlays for the implantchair.dmi machine sprites.
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
love seeing more anomaly cores being used! this and that thermomachine one will make toxins more on the lookout for rare cores!

**Comment by ExcessiveUseOfCobblestone** [comment]
just note when you use an existing core you cut down the overall amount of those items one can produce duplicates of in a single round.

**Comment by moocowswag** [comment]
it probably needs a stronger / more impactful effect if its gonna use an anomaly core but i cant think of one.

**Comment by moocowswag** [comment]
also keep in mind, we have a similar method of chem purging that is actively available to lumi slime people, if they can have it on the go it should be fine to add it to a machine without the use of an anomaly core.

**Comment by ExcessiveUseOfCobblestone** [comment]
purging is p strong but idk if anyone ever fixed the Kh2o meme

**Comment by DaydreamIQ** [comment]
Seems a little pricey for something that's just better penetic acid. It'd probably see much more use without the core imo.

**Comment by chemistrymain2** [comment]
> purging is p strong but idk if anyone ever fixed the Kh2o meme

nobody ever fixed kh2o and blood filters are pretty common too so removing chems is not an issue

the main advantage this has is reducing addiction points and healing livers

**Comment by ExcessiveUseOfCobblestone** [comment]
The only part i dislike about this is that doctors have zero involvement outside of building the machine.

I dont mind the idea that at a research threshold they get a nice boost to purging and a way to more directly impact addictions, I just am not a fan that THEY dont actually get that here, its a machine that does it for them.

**Comment by ATH1909** [comment]
feels more like a bepis tech than an anomaly core reward tbh

**Comment by Pickle-Coding** [comment]
Way too powerful to be a bepis tech. This is perfect use of a bioscrambler anomaly core.

**Comment by moocowswag** [comment]
> Way too powerful to be a bepis tech. This is perfect use of a bioscrambler anomaly core.

Way to weak for an anomaly core but a bioscrambler  core isnt nearly as valuable as a bluespace or gravity or vortex one so i guess this is where we start to solidify those lines and define bioscrambler and possibly flux as their own weaker tiers

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
This will need involvement from someone else, like a doctor.

Generally speaking I do not agree with offloading "lower end" work to machines when it helps break up the dead times. I do however agree we can have better purging methods and addiction tackling.

**Comment by Rhials** [comment]
> This will need involvement from someone else, like a doctor.

Alright, I'm a bit torn here. I get the sentiment and wouldn't be impartial to adding some form of doctor involvement, but the no-strings-attached automation was what I considered the aspect that made it worth an anomaly core. 

Would making it require a doctor to activate it for the occupant (like cryo) be sufficient, or are you thinking something more directly involved?

**Comment by ExcessiveUseOfCobblestone** [comment]
Ideally the process would be something doctors can utilize. I personally do not like fire and forget type machines because they often disregard the doctor. Sleepers and Cryo when the guy bringing them in did your job for you etc.

The price can be adjusted to compensate, i like the idea of being able to tackle issues better/you couldnt really neatly address before, but id like that to be a tool doctors utilize vs. having an assistant and his mate force their way in to do the computer mashing and the doctor just rolls their eyes. I would still make this not a roundstart tool.

**Comment by RealityOverseer** [comment]
First off, I am unimaginably happy people are giving more love to lesser used anomaly cores. Secondly, I disagree with it being apart of Advanced Biotechnology research and it would fit better with Anomaly Research or maybe even adding a new tier of anomaly research Anomalous Machinery.

**Comment by CRITAWAKETS** [comment]
Not really sure about the balance of this thing. It's not that it's OP or whatever, quite the opposite, it's that this thing is pretty much obsolete via the injection of some rather common medicines since as multiver or even worse, pentetic. Only use case I can see where this would be better than other methods would be slimepeople and that's about it. For an anomaly core, being obsoleted by multiver seems kind of pathetic.

**Comment by YehnBeep** [comment]
> Not really sure about the balance of this thing. It's not that it's OP or whatever, quite the opposite, it's that this thing is pretty much obsolete via the injection of some rather common medicines since as multiver or even worse, pentetic. Only use case I can see where this would be better than other methods would be slimepeople and that's about it. For an anomaly core, being obsoleted by multiver seems kind of pathetic.

1. There are some things that can't be purged by multiver (and can even sabotage attempts to use multiver).
2. Antitox meds don't help with addiction, which this does
3. Pentetic requires silver and blocks all other medications until it's been metabolized - the downside to it purging absolutely everything.

That's not to say that I really have an opinion on the balance, but it's not 1:1 with antitox meds.

**Comment by Rhials** [comment]
With the requested design change and lessons learned from the comments (I don't play medical lmao), I'd rather handle this in a new PR when I have the time to properly sit down and redo this.

**Comment by EricZilla** [comment]
I'm like a month late but I was looking through past PRs for my own amusement, and have a suggestion, perhaps have it be a machine that is similar to the IV, but instead of draining blood it drains chems into a bottle or something so it could even be reused at a 3:1 recycling ratio or something like that. So you can inject someone with like 20 of chemical X and get around 5 back while getting all 20 out of them fast.
I sort of picture it being like those plasma donation machines that suck your blood in, grab the plasma, and then put it back. Require the patient to be laying down to have it hooked up so they cant do it to themself, and then have it kill them to death if you do it while they are low on blood

**Pull request closed without merging**
