### PR TITLE
Misc clockcult grammar and fixes

### PR DESCRIPTION
**Pull request by ChangelingRain**
Floor(x, y) function!
Taunting Tirade is now fancybright instead of dark
Some grammarformatting bullshit

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@leoz

Does this conflict?

**Comment by optimumtact** [comment]
Doesn't round already take a second parameter to handle this?

**Comment by ChangelingRain** [comment]
uh, oranges, you *do* know what floor does, right? Floor() and round() are not the same thing, even if round without a second argument acts like Floor(x, 1)
specifically, inputting 1.6 into Floor(1.6, 1) returns 1, while doing round(1.6, 1) returns 2

**Comment by optimumtact** [comment]
The sarcasm isn't necessary, I thought round floored when you gave it a second argument

**Pull request merged**
