### PR TITLE
RPD device separation and tooltips

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Separate the RPD devices into two parts, the "Basic Devices" and the "Advanced Devices".
The former are the most used ones and the simplest to understand.
The latter are either a direct upgrade to the first ones or they are less useful for normal setups.

The PR also adds tooltips to all atmos devices to help understand what the device is for (some of them will need improvements).

image

## Why It's Good For The Game
Better feedback for players

## Changelog

:cl:
qol: RPD atmos devices are separated into two categories, basic and advanced. 
qol: atmos devices all have tooltips on the UI.
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
> Fix the layout, man, it overlaps in weird ways. Restore the original height.

I'll restore the height, but i have no idea why the layout clips, it does that on master too so i don't know what happened there

**Comment by Ghilker** [comment]
Adjusted tooltips, restored the height of the UI, increased the width of it and fixed a weird stack issue
image

**Comment by Ghilker** [comment]
> Just wanted to post and say I really like the tooltips. Less of a fan of the concept of advanced devices, in a perfect world I'd like it if each component did one general thing decently well to the point that we don't need sidegrades, but I recognize image
> 
> so what can you do. Still want to murder the heat pump in its sleep though

what if we add technology upgrades for the RPD that you research in science that unlocks more advanced devices that are either the direct upgrade of the base ones (like a pressure pump that instead of going to max 4500 kPa it goes to 9000 kPa) or a sidegrade that does something better but with a downside on other parts?

**Comment by stylemistake** [comment]
I don't like this PR because this separates tools into new tabs, but it doesn't make the UI more compact. In fact, it is now 1.5x larger.

😕

**Comment by LemonInTheDark** [comment]
Just the tooltips then? I'm kinda eh on the separation myself

**Comment by Ghilker** [comment]
Requiring an extra click is a dumb reason to dislike the PR, the UI being a bit bigger is eh, i don't see it as an issue. The goal wasn't to make the UI compact, a lot of informations in a bigger UI are far more readable.

Having the devices separated means that people will know that there are basic tools to deal with atmos and more advanced ones for complex logic and setups.

**Pull request closed without merging**
