### PR TITLE
Changes dispenser, heater and smoke machine sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]:
:cl: nicbn
imageadd: New sprites for chemistry machines.
/:cl:

imgs

### CODE REVIEW

**Comment by Bawhoppen** [comment]
I can notice that some of these definitely require some work, but I'm sure WJohn will critique them in depth.

Though, for all I know these are perfect sprites and I'm a dummy

**Comment by nicbn** [comment]
I'm not sure how to make dispensers look better but I think they're better this way than they are now.

**Comment by PKPenguin321** [comment]
Beer dispenser looks kind of nasty and I'm thinking it's because of inconsistent outlining with the rest of the sprites
Not really a fan of the bumps on the sides of the chem dispensers but because it's le 3/4ths there's no way to fix this without making it look like a generic 3/4ths rectangle sprite

**Comment by ExcessiveUseOfCobblestone** [comment]
Stop. Stop right there.

These are not bad but the 3/4th obsession is lame and gay and when you don't actually change the sprite but just make it 3/4th's I get ill!

**Comment by GunHog** [comment]
Please actually _improve_ the sprite! Do not just make it 3/4th!

**Comment by WJohn** [comment]
The chem heater is a fairly nice improvement, though I think it could be better. Everything else should pretty much be redone if it's to be moved to 3/4th. Beer/soda dispensers especially. Just moving to 3/4th isn't enough, I feel. People throw enough of a tantrum any time it's even mentioned, though I am in favor of it.

**Comment by nicbn** [comment]
The chem smoke machine is actually what I think is the best improvement. I'll PR the heater and smoke machine only then.

**Pull request closed without merging**
