### PR TITLE
Rotates stools to face tables

### LINKED ISSUE #59357: funny double bar stool in delta
## Round ID:
[163048](https://scrubby.melonmesa.com/round/163048)

## Testmerges:
#58991

## Reproduction:
hey this stool looks kinda sus
dreamseeker_LN32xa6HLZ
imposter found
dreamseeker_GKTdt0SwpI

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Rotates stools, barstools, and some forward-facing arcade machines to face each other.

## Why It's Good For The Game
Before stools had 1 direction, now they have 4! Getting the most use out of all 4. 
Fixes #59357

## Changelog
:cl:
qol: newly-resprited stools and barstools are now facing tables
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
poor mapdiffbot

**Comment by dragomagol** [comment]
😔

**Comment by maxymax13** [comment]
@AffectedArc07 owned

**Comment by LemonInTheDark** [comment]
Please don't blacklist us forever k thanks

**Comment by maxymax13** [comment]
shouldnt they be preset subtypes instead of 5 million varedits, dear god

**Comment by dragomagol** [comment]
> 
> 
> shouldnt they be preset subtypes instead of 5 million varedits, dear god

**Comment by cacogen** [comment]
Did you somehow use a script for this or was this a ton of work?

**Comment by Hamurlik** [comment]
Screenshots please?

**Comment by dragomagol** [comment]
> 
> 
> Did you somehow use a script for this or was this a ton of work?

Varediting them was manual, replacing the varedits with presets was mostly automatic (some stools were shifted so I missed them in my first pass). I can safely say this was not even half as deranged as the wall mount PRs.

>
>
> Screenshots please?

image
image

**Pull request merged**
