### PR TITLE
Adds retractor to medical first aid kit

### PR DESCRIPTION
**Pull request by OnlineGirlfriend**
## About The Pull Request

Adds a retractor to the first aid kit for medical personnel.

## Why It's Good For The Game

It makes sense. These kits contained everything needed for basic surgery except a retractor. This saves doctors from awkwardly running to the lathe mid-surgery when they realize they don't have a retractor.

## Changelog
:cl:
tweak: added retractor to medical first aid kit
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
Why not also add a saw at this point?

**Comment by Time-Green** [comment]
> The medikit has basic surgerical tools, basically everything needed to do the wound surgeries. 

Isn't the most basic surgery tend wounds? Why the retractor and not the saw? Also consider that all the surgery rooms are fully equipped. Kinds feels like a half measure. I think it's fine the way it is.

**Comment by OnlineGirlfriend** [comment]
> > The medikit has basic surgerical tools, basically everything needed to do the wound surgeries.
> 
> Isn't the most basic surgery tend wounds? Why the retractor and not the saw? Also consider that all the surgery rooms are fully equipped. Kinds feels like a half measure. I think it's fine the way it is.

The scalpel can be used in place of the saw with reduced success. It just makes sense to me to include the retractor if common surgical tools are to be included in first aid kits at all.

**Comment by nemvar** [comment]
Why not give doctors a filled surgery belt instead and remove the tools from the medkit? I never liked those to begin with.

**Comment by SomeoneYouProbablyKnow** [comment]
A) Can you use a scalpel instead of the saw. Wasn't that removed. I'll test it and get back to you
B) I think there is some design idea behind belts (all belts) not being a roundstart crewmember spawn. So that probably won't happen

**Comment by ExcessiveUseOfCobblestone** [comment]
the current set is specifically to perform TW, not to support full-fledged surgeries.

**Comment by necromanceranne** [comment]
It won't matter either way given the protolathe is right there and you can just print off a new set of retractors when needed. Unless we want to entirely remove printing surgery tools from the protolathe, any doctor is going to end up with a full suite of tools on their person to perform on the spot surgeries as needed.

I already do it as paramedic, and frankly it baffles me why don't have the tools for tend wounds themselves given they are the most likely to be doing emergency triage and not medical doctors, who are probably doing more complicated medical procedures only reasonably done via stasis bed/surgery table.

**Comment by ExcessiveUseOfCobblestone** [comment]
I would be okay with removing MD's starting kits in favor of a set of surgical tools if the idea is that they should focus on more serious ailments while paramedics are more geared towards triage (or taking them to the doc if it requires something further).

I just print them off roundstart anyways lol.

**Comment by OnlineGirlfriend** [comment]
Logic seems sound, I’d rather work on a paramedic kit then.

**Pull request closed without merging**
