### PR TITLE
ninja stungloves nerf + quirks

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
the ninja stungloves are no longer a knockdown + shove in one click (not a stun). clicking on people now first does the shove and THEN knocks someone down for 3 seconds after a 0.3 second delay. this means you need to click on them twice
ninja's stealth module now gives you the silent footsteps trait when active
all ninjas now have the light step and freerunning quirks

## Why It's Good For The Game
ninjas really cool but he doesn't really need 1 click stuns in addition to all his other tools, he can escape pretty much anything and has a sword for melee encounters, and knocking someone down instantly is still really powerful
ninjas getting quirks that fit them is cute i think, makes sense and is useful

## Changelog
:cl:
balance: ninja's stealth module gives silent footsteps when active
balance: all ninjas now have the light step and freerunning quirks
balance: ninja's hacker module shove no longer stuns in 1 hit. first shove knocks down and pushes away, second one stuns
fix: fixes ninja shoves not causing sparks
qol: the person in an energy net is now reasonable to hit, the dark part of the sprite is now an underlay, so you can click the person inside the net pretty easily and if you wanna hit the net you click the green part or the darker sides that the human sprite doesnt cover
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
they should get spider faction

**Comment by AtomTheProphet** [comment]
> they should get spider faction

I am once again asking you to elaborate.

**Comment by Fikou** [comment]
> they should get spider faction

so true

**Comment by Vincent983** [comment]
turn spider bomb into bomb with spider legs

**Comment by SimplySmiley123** [comment]
Kinda wish ninja got more to his objectives.
Stun felt kinda necessary when security can just camp ninja's objectives.

**Comment by Singul0** [comment]
> Kinda wish ninja got more to his objectives. Stun felt kinda necessary when security can just camp ninja's objectives.

it's super useful for energynet objective

**Comment by Fikou** [comment]
> Kinda wish ninja got more to his objectives. Stun felt kinda necessary when security can just camp ninja's objectives.

youre doing a bad job as ninja if youre letting security camp every area where you can possibly be and don't use your 20 other abilities that either can deal with them at range or make one of their weapons not work and then you still need a 1 hit stun because clicking twice (once on a target that's already knocked down) is too hard

**Comment by Singul0** [comment]
> > > Kinda wish ninja got more to his objectives. Stun felt kinda necessary when security can just camp ninja's objectives.
> > 
> > 
> > it's super useful for energynet objective
> 
> you mean the objective that got removed like 2 years ago? have you actually played ninja?

coders dont play the game so.. ¯\_(ツ)_/¯

**Comment by SimplySmiley123** [comment]
> > Kinda wish ninja got more to his objectives. Stun felt kinda necessary when security can just camp ninja's objectives.
> 
> youre doing a bad job as ninja if youre letting security camp every area where you can possibly be and don't use your 20 other abilities that either can deal with them at range or make their weapons not work or let you get to them stealthily and then you still need a 1 hit stun because clicking twice (once on a target that's already knocked down and disarmed) is too hard

It's not even a bad job. It's just doing your job *at all.*
AI will know that you're doing one of your 3 nigh guaranteed objectives and all it takes is other 2 being camped.
It's not whole station. But specific areas where *they* have the advantage over you simply by knowing about you because of your objectives announcing your presence and how your objectives are always the same no matter what.
*They* need just 1 hit on you. You can use your adrenaline, sure, but pretty sure it's single use. While EMP still doesn't remove the issue of stun combat being a pain in the ass.

**Comment by Vincent983** [comment]
you can refill the adrenaline with radium, but yeah it's functionally 1 use per encounter

**Comment by Fikou** [comment]
> It's not even a bad job. It's just doing your job _at all._ AI will know that you're doing one of your 3 nigh guaranteed objectives and all it takes is other 2 being camped. It's not whole station. But specific areas where _they_ have the advantage over you simply by knowing about you because of your objectives announcing your presence and how your objectives are always the same no matter what. _They_ need just 1 hit on you. You can use your adrenaline, sure, but pretty sure it's single use. While EMP still doesn't remove the issue of stun combat being a pain in the ass.

you have 4 different tools to disengage
emp to fuck up their baton/disabler
stars to give them stamina and damage as they move
energy net to literally stop them from moving
literally just run away with invisibility, teleports and/or speed boosts

i think your option of "ignore all of those and just come up close and 1shot them" shouldnt be the perfect one every single time. if you hit first you still knock them down and they lose your baton. even if they hit you they lose their baton if you hit them back, and you should get the shove knockdown before they can hit you with a baton again and before you fall down

other than the rnd server, all of these objectives have several locations from which they can be completed anyway

**Comment by nukularpower** [comment]
emp does practically nothing to batons anymore, it is literally useless - just 2 days ago I emp'd a secoff FOUR times and he still was able to baton me down.  Maybe something is bugged with it or something but it seems way less effective than people like to pretend

**Comment by Vincent983** [comment]
EMPs drain cells of like, 10% of their charge, but drain lasers and disablers of 100% of their charge

**Pull request merged**
