### PR TITLE
Updates the look of the miner's jumpboots

### PR DESCRIPTION
**Pull request by EricZilla**
## About The Pull Request

I will be honest I saw the pinksec boots and said "Hey mining boots should look like that" and then I did that. I know the current boots aren't very well liked by their creator, and so here we are!
bootch
dislike farming
Animation

OKAY I caved and animated them they look cool

## Why It's Good For The Game

I just don't like the old ones. They didn't look like they'd be very secure either, and hey these match the current style of footwear we have better.

## Changelog

:cl:
image: Someone broke their ankle using the jumpboots in the vendor so we had to buy new ones
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]

**Comment by CRITAWAKETS** [comment]
I feel as if the glowy part should be made brighter, and less shaded. Right now it looks a little like silver which isn't quite right.

**Comment by EricZilla** [comment]
> I feel as if the glowy part should be made brighter, and less shaded. Right now it looks a little like silver which isn't quite right.

I did consider making them strobe a little like the new bluespace syringes

**Comment by CRITAWAKETS** [comment]
> I did consider making them strobe a little like the new bluespace syringes

now that'd be really cool to see.

**Comment by EricZilla** [comment]
OKAY NOW THEY REALLY GLOW

**Pull request merged**
