### PR TITLE
Makes the srm-8 rocket pods have a bit more oomph

### PR DESCRIPTION
**Pull request by ghost**
So, this really changes the way the rocket pods work now. So now they're proper projectiles, which means they keep going until they hit something, then they go boom. Downside of this, the sprite looks really silly now, as rockets spin about like a discoball in flight. I have no idea how to fix that. When they hit a non living target, they explode with 0 1 2, if it hits a living target, it explodes with 0 0 2. and the projectile now does 30 brute damage as well, meaning direct hits on mobs do 60 brute damage, plus a 50% chance to knock out and 7% chance to sever a limb. Should actually buff that considering you can only fire a rocket once every 2 seconds it seems like. But, this is good for now.

:cl: vcordie
tweak: The SRM-8 Rocket Pods have been loaded with new explosives designed to do maximum damage to terrain. These explosives are less effective on people, however.
/:cl:

### CODE REVIEW

**Comment by kilkun** [comment]
why is it so weak in the first place?

can robotics print it? i thought they were mauler/marauder/seraph only?

**Comment by vcordie** [comment]
robotics can print it if you get to combat 6.

**Comment by Supermichael777** [comment]
its spinning because projectile code transforms a static icon. cut it down to just its north state. also move it to icon/obj/projectiles.dmi

**Comment by kevinz000** [comment]
This is the only mech PR you've made that isn't absolutely crappy.

**Comment by Militaires** [comment]
@supermichael777 @vcordie spinnin rockets is FUNNY AS FUCK please please keep it it's for the best

**Pull request merged**
