### PR TITLE
More items hurt you now if you walk on them barefoot

### PR DESCRIPTION
**Pull request by OneAsianTortoise**
## About The Pull Request
**Edit: Syringe is removed from the list.**
Have you ever stepped on a sharp object as a kid before? I stepped on a broken tea cup when I was a kid, and I could tell you that it hurt like hell.

Light tube and glass shard already hurt you in-game if you step on them barefoot. The PR changes that **broken drinking/alcohol glass and broken plate shard** will also hurt you now if you step on them barefoot.
I was planning to add knives too but I thought that would be too much.

I hope this works.

## Why It's Good For The Game
Having only light tube, glass shard, and D4 dice considered as sharp items that can hurt barefoot you is weird, and players suffer more consequences if they lose their shoes(HONK), or they decide not to wear ones.
It also makes Light Step quirk slightly more useful.

## Changelog

:cl:
balance: broken drinking/alcohol glass and broken plate shard now hurt you if you step on them barefoot.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
not a fan of syringes counting for this- they're usually gonna be laying on their sides, no?

**Comment by OneAsianTortoise** [comment]
> not a fan of syringes counting for this- they're usually gonna be laying on their sides, no?

Yeah, I was considering to keep syringe or not, but let's see what others say. Probably would just keep broken bottle and plate in the end.

**Comment by chizzyyyy** [comment]
what about other sharp items?

**Comment by OneAsianTortoise** [comment]
> what about other sharp items?

I mentioned it that I was about to add knives (and even other sharp objects), but I thought it would be too much.

**Comment by Valorium-RB** [comment]
If you don't cut syringes from the list, them potentially injecting small amounts of their contents when stepped on would be kinda funny

**Comment by MrDoomBringer** [comment]
> If you don't cut syringes from the list, them potentially injecting small amounts of their contents when stepped on would be kinda funny

\> take off someone's shoes
\> drag them ontop of my pile of 20 special surprise syringes
\> watch as they simultaneous turn into a cat, suffer 14 heart attacks, and explode

**Comment by Valorium-RB** [comment]
> > If you don't cut syringes from the list, them potentially injecting small amounts of their contents when stepped on would be kinda funny
> 
> > take off someone's shoes > drag them ontop of my pile of 20 special surprise syringes > watch as they simultaneously turn into a cat, suffer 14 heart attacks, and explode

Yes, actually

**Comment by Shadowflame909** [comment]
Upside 
>Ash Lizards btfo'd by vending machines going rogue
>Janitor is more inclined to clean up glass messes
Downside
>Glass foot stun (ow)

**Comment by bluetshirtguy** [comment]
Please don't make the game more frustrating

**Comment by Bawhoppen** [comment]
> > If you don't cut syringes from the list, them potentially injecting small amounts of their contents when stepped on would be kinda funny
> 
> > take off someone's shoes > drag them ontop of my pile of 20 special surprise syringes > watch as they simultaneously turn into a cat, suffer 14 heart attacks, and explode

Emergent gameplay, make it so

**Comment by IndieanaJones** [comment]
monkey nerf
i want the spray-on shoes from cloudy with a chance of meatballs

**Comment by githubuser4141** [comment]
it's a shame there's no pain system so 'hurting like hell' equals 5-10 damage which is absolutely lethal according to TG. would be funnier if there was differentiation between a lethal wound and 'owwwww'.

**Comment by optimumtact** [comment]
> Please don't make the game more frustrating

I hear farmville is a fun game for more casual users.

**Comment by ExcessiveUseOfCobblestone** [comment]
syringes/beakers/bottles/glasses on the ground should break turning them into shards and spilling their contents on the ground when you step on them >:)

**Comment by Shadowflame909** [comment]
> > Please don't make the game more frustrating
> 
> I hear farmville is a fun game for more casual users.

This is expected but still upsetting.

**Comment by Serxule** [comment]
if you want this, the least you can do is add the hardened soles perk on most of the downstreams. like med-high cost positive perk that makes you immune to stepping sharp stuff shoeless (lizards buffed?? !???!?? !??/1111/!!1/)

**Comment by OneAsianTortoise** [comment]
>

**Comment by OneAsianTortoise** [comment]
FUCK MISCLICK

**Comment by Serxule** [comment]
> Light Step Quirk is a thing.

light step only affects damage and walking sound, which is completely different than what hardened soles is

**Pull request merged**
