### PR TITLE
Lowercased computer names

### PR DESCRIPTION
**Pull request by ShizCalev**

### CODE REVIEW

**Comment by Tacolizard** [comment]
shouldn't you remove the `\improper`s because they're lowercase?

**Comment by ShizCalev** [comment]
Is that all that it means? Wasn't sure if that was there for another reason

**Comment by Tacolizard** [comment]
I don't know for sure, but I thought it was so that it isn't referred to with a "the" in the text outputs of other items.

**Comment by Cyberboss** [comment]
\improper can stay

**Review by Cyberboss — APPROVED** [review]

**Comment by ChangelingRain** [comment]
It can stay, but it should go.

**Pull request merged**
