### PR TITLE
Fixes hands missing

### PR DESCRIPTION
**Pull request by nicbn**

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by nicbn** [comment]
OOPS

**Comment by Cyberboss** [comment]
??????????

**Comment by nicbn** [comment]
Not working, one sec

**Comment by nicbn** [comment]
Ok I did something wrong here

**Comment by nicbn** [comment]
@Cyberboss now it works

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
