### PR TITLE
Reverts new APC sprites

### PR DESCRIPTION
**Pull request by lzimann**
The new sprites really don't fit the game at all and in my opinion they are really awful looking, they would honestly fit more as an intercom with video than an APC. Even if you consider the old one ugly, they are honestly better looking and more fitting than the new one. Will post a pic comparing both soon.

Reverts #29809

Old:

New: 

Closes #29901 
Closes #29922

### CODE REVIEW

**Comment by Bluespace** [comment]
Thank you.

**Comment by nicbn** [comment]
Yes please

**Comment by PKPenguin321** [comment]
didnt hear a single good thing about these in ooc when they were live for the first time, cant say im a fan of them either
👍

**Comment by Armhulen** [comment]
I would have to see it but it really feels like everything would be fixed if they faced off the wall instead of always facing south

**Comment by WJohn** [comment]
That was fast.

Also rotating them would be a nightmare for readability, APCs are covered in tons of indicators to tell you what status they have regarding each function on it (locked, not charging/charging/full, auto/manual/auto-nopower/off on equipment, lighting, and environment). Flipping these would make it much, much worse.

**Comment by MoreRobustThanYou** [comment]
I prefer #29901

**Comment by WJohn** [comment]
As do I.

**Comment by MoreRobustThanYou** [comment]
like the saying is, "Improve, don't remove"

**Comment by PKPenguin321** [comment]
not applicable, this is an improvement and not a removal

**Comment by Repukan** [comment]
Not applicable because more contract doesnt make it looks less shitty

**Comment by BeeSting12** [comment]
Polishing poop and putting it between two pieces of bread doesn't make it any better than regular poop between to pieces of bread. It's still a poop sandwich.

**Comment by Chronitonity** [comment]
if they were rotated properly _maybe_ they wouldnt look so awful

**Comment by YakumoChen** [comment]
Honestly I don't like the new sprites, the power indicators (Machines, Lights, Doors) are too hard to read at a glance, too much sprite real estate is taken up by sprite fluff that doesn't serve a function. The old ones were much more readable by contrast and everything sort of bleeds together with the new sprites.

**Comment by Dorsisdwarf** [comment]
I just dont like how these APCs look blurred and smeary. Theres no hard edges anywhere on them so it looks like you took the photoshop blur tool and mashed it a few times

**Comment by Bawhoppen** [comment]
wj went mad with power

**Comment by optimumtact** [comment]
#29931 is the blessed version

**Pull request closed without merging**
