### PR TITLE
The Tales of Syndi Maids. 

### PR DESCRIPTION
**Pull request by MiiyaBox**
## About The Pull Request

https://youtu.be/A3omYY5ZwP0
Welcome to hell, but now with lost legends trying to kill you! (Or at least their copy cats!)
We're porting SYNDICATE MAID FITS! for all the crew to ENJOY!(Or hate!)

image
image
imageimageimage

[Sprites not made by me, but ported from shiptest.]
[This was made as a promise to a friend, and a learning experience in more in deep modding.]
[Any grammatical errors may or may not be intentional here, but in game I would like to know.]

## Why It's Good For The Game

A Conflict of stories! A fun outfit for the most quirky agents and crew alike!
Both versions of the outfit look the same, but their text and proprieties are different!

Whilst Centcom's Autodrobe contraband is the idea that they've been used as a punishment for a invading... and is made of cheap materials, providing no defense... probably shoved in there secretly by the most _**Unique**_ Assistant with nothing to do...

Syndicate acts in it's "Said value" and honors it by adding it to the badass bundle!
Coming with the qualities of the basic syndicate outfit! Like combat gloves and it's normal defenses against fire and acid...
Perfect for cleaning up after said murder on station! (Packed with sun glasses for extra cool factor as you don't look at explosions.)
and a being overall cheaper than the normal outfits! (at a 2 TC price!) [That can be returned to 4, or any desired value]

[Joke Lore Writing, I am not a proper writer, so expect it to be cringe.]
---
[PDA of John ■■■■■■■ ■■■■/■■/■■■■ at ■■:■■:■■]

> I cannot beave this! your kidding me right?
> I Managed to give the funky caps the slick and get inside the armory! All the GUMS I could use and sell! 
> BUT SYNDICATE TRAHS BLEW IT UP WHILE I WAS ABOUT TO TAKE ANY! THIS WON'T GO UNPUNISHED!
> HE DID NOT ESPECT THAT CHEM GRAMDE UP THEIR FACE! THAT SHIT SENT HIM FLINGING INTO A L SHAPED KABOOM
> SOMEHOW THAT BROKE THE BOMB IN HIM??? HE IS INTACT! AS WELL THEIR STUFF IS NOW MINE!
> BUT THEIR RUILED MY PLANS! THEY'LL PAY! THESE SYNDI WILL PAY! WITH THE MOST HUMILIATION MY GRANDPA JOE TAUGHT ME! IT WILL FIT THEM PERFECTLY AS I WILL DISPLAY THEM STRAPPED TO HONK BOT WHO WILL GRAG THEM ALL AROUND THE STATION! THE CHLOW WILL LOVE IT! I'LL KEEP THIS APRON I MADE BECAUSE IT LOOKS COOL AS A FACEMASK.

---

Encrypted File #■■■■■

[2■XX/■■/■■]

> Today's reporting on the assigned mission #■■■■■ 
> Doe ■■■■■■■■■ who's shown great capabilities of commanding and training has persevered once again in the destruction of another centcom station. But, In further inspection and data recovered stored at #■■■■■■■■■ of the recordings at his home... he did not even went. while it is possible that the station might have blown up by itself due to incompetency we've questioned him further about it; Doe Informed us that he just "Didn't feel like going", "would've missed mom's birthday! She's turning 104!", and that he sent his maid to do the job for him whilst he went to do "unrelated businesses". 
> While a capable man himself in teaching others in various ways turning even the most fool unrobust assistant into a capable warrior, for a mysterious maid to have exploded such a heavily armed station is close to ridiculous... but the maid is nowhere to be seen during and after said events... so it is not sure rather they did so as they said, or the lie worked though pure luck.
> Doe Say he laments the loss of his special maid, and has offered us "clothes" to use in memory of them, while such request would've been denied, we've decided to push it forward for now... as the only thing found in the event zone is a burnt apron, similar to his maid's own. hopefully in the future and with this act he get himself together and continue to train new agents to fight.

---
## Changelog

:cl: MiiyaBot
add: Funky New outfits and badassery selection!
add: Even more hatred towards quirky dressed people!
add: Love from said quirky dressed people!
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
😐 i literally can't even decipher what this PR is saying

**Comment by MiiyaBox** [comment]
> 😐 i literally can't even decipher what this PR is saying

_Here without quirky text!_ ( I probably went too deep in the jokes and such.)

SYNDICATE MAID FITS! for all the crew to ENJOY!(Or hate!)

image
image
imageimageimage

[Sprites not made by me, but ported from shiptest.]
[This was made as a promise to a friend, and a learning experience in more in deep modding.]
[Any grammatical errors may or may not be intentional here, but in game I would like to know.]

## Why It's Good For The Game

Outfits from Shiptest for people to wear, or use as badassery 
both fake and real versions have small differences.
fake ones provide no protection, while real ones provide the same protection as normal generic Nuke Ops outfit
(The ones they spawn with like combat gloves)
They lost a little less than the usual badass items (2 tc instead of 4) Comes with sunglasses too.

## Changelog

:cl: MiiyaBot
add: Funky New outfits and badassery selection!
/:cl:

**Comment by Ebin-Halcyon** [comment]
One of the PRs of all time.

**Comment by JohnFulpWillard** [comment]
what the hell

**Comment by MiiyaBox** [comment]
> Sorry but the code doesn't fit our quality standards
That I can 100% understand because I personally don't know how to! this is pretty much me experimenting and trying to understand it. Either way, what ever happens... Was fun!

**Comment by JohnFulpWillard** [comment]
For a more serious answer:

This item adds nothing to Traitors and gives them no benefit, other kits give some benefit or silly side effect such as nukie's Clown costumes, chameleon kit disguising as any clothing item and faking your voice, and centcom suit's ability to fake being central command.

This suit however is just a maid outfit that takes 110 minutes to unlock.

I also don't know who "It does not come with the skill and grace of the former legendary agents." is referencing but I don't think I'd like player references anyways.

**Comment by Wallemations** [comment]
> > 😐 i literally can't even decipher what this PR is saying
> 
> 
> 
> 
> 
> _Here without quirky text!_ ( I probably went too deep in the jokes and such... and was thinking of more creative PR's with lore attached.) (Also Moved around some things for easier reading)

I don't think I've ever seen a PR with lore _attached_. I've seen PRs with lore, but not stapled to the end like this one.

**Comment by MiiyaBox** [comment]
> For a more serious answer:
> 
> This item adds nothing to Traitors and gives them no benefit, other kits give some benefit or silly side effect such as nukie's Clown costumes, chameleon kit disguising as any clothing item and faking your voice, and centcom suit's ability to fake being central command.
> 
> This suit however is just a maid outfit that takes 110 minutes to unlock.

I GOT a bit concerned with the "what the hell." But good to see that something came next.
That's reasonable! I went over my head a little bit in this experiment with messing with bunch of things when I should've only done the basic "add this to autodrobe". Ended up skipping some parts like discussing with people and seeing what they think, what to change, etc. Which well, at least this did it! (Even if in a kinda awkward way)
In hindsight "Stop and breathe" was needed.

Now to some small comments...
Things like the "110 hour to unlock" was a mistake actually! I was using working code as reference and what came to mind was the Centcom Supplies! So I used that as reference to learn everything related to traitor items. But I didn't get the 110 hours to unlock and didn't give it some needed thought.

---
> I also don't know who "It does not come with the skill and grace of the former legendary agents." is referencing but I don't think I'd like player references anyways.

Actually it ain't referencing anything but the messy lore I thought about, not referencing players/events. 
but now that you said it... it can be seen as that, so indeed a bad description.

> I don't think I've ever seen a PR with lore attached. I've seen PRs with lore, but not stapled to the end like this one.

It might have be me just imagining things due to lack of sleep and mixed with going over my head about the experiment.
Bad mix up when doing things.

---
I do hope I've not angered anyone with this or caused trouble, as that was not my intention.
Even if I knew a little bit in me that It would likely have a negative reception.
But since we are here... would like to add questions to that while we're here...

Were I make it simpler, like, simply add the costume to a autodrobe in the future. 
would there be any concerning trouble? Such as copyrights, ownership, etc. of said Shiptest sprites?
I guessed If there were trouble I would just be denied and that is that but since the issue is different from said thing...
I might as well drop the question!

**Comment by Ebin-Halcyon** [comment]
> would there be any concerning trouble? Such as copyrights, ownership, etc. of said Shiptest sprites?

Shiptest is an open source repo like most SS13 codebases, there's no legal problems or copyright issues if you port things without asking. That being said, it's a nice courtesy and never hurt to ask the original artist for their blessing.

**Comment by calliophis-maculiceps** [comment]
> Hi, thanks for making the pr!
> 
> Sorry but the code doesn't fit our quality standards and the idea itself is not an exceptional one, just a syndie vest and combat gloves with different sprites that take two hours to get, stuff like that kinda bloats the uplink and I doubt many people would use it.
> 
> I'll be closing in 24 hours if someone has something to add.
> 
> cute pr description though

how do i react with a 🔥 and a 💯 emoji

**Pull request closed without merging**
