### PR TITLE
Changes alien pounce sprites to V2

### PR DESCRIPTION
**Pull request by WJohn**
image

Less cougar like, way more aggressive. Better proportions in general. Aliens are really small in ss13 for some reason? They're like 5 feet tall or something.

### CODE REVIEW

**Comment by paprka** [comment]
They looked like cute bunnies before it was adorable

**Comment by paprka** [comment]
who cares about the height we have tiny mechs

**Comment by WJohn** [comment]
Yeah they were way too friendly looking.

**Comment by Fox-McCloud** [comment]
@WJohn 

Hey, you're the one that added that sleeping sprite! =p

**Comment by WJohn** [comment]
Yes but they were supposed to look cute there. Here they're not.

**Comment by Fox-McCloud** [comment]
@WJohn 

I know, I'm just giving you a hard time. In any event; this is really minor in the context of things, but at a glance, it does help.

**Pull request merged**
