### PR TITLE
budget cards that are good

### PR DESCRIPTION
**Pull request by maxymax13**
## About The Pull Request
soulless

Replaces angled budget card sprites with ones that are flat.

**The cargo budget card is still a very real item that exists.** I'm not sure if the ones other than the cargo one are actually ever used, but I made them in case a gamma ray hits your computer and turns your cargo budget card into some other budget card, and you see a diagonal sprite, killing you of shock instantly.

## Why It's Good For The Game

This game will only be good when all charmingly bad sprites are replaced with flat sterile soulless sprites.

## Changelog
:cl:
imageadd: Issued new design for budget cards
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
torn between making the generic one budgettest3 or budgettest3 alt, i can't tell if that hyeroglyph is supposed to be "DC" or "¢" (does this even matter??)

**Comment by actioninja** [comment]
None of them are used

**Comment by XRandomXManX** [comment]
> None of them are used

then make the useful, mr.maintainer. smh my head

**Comment by maxymax13** [comment]
isn't the cargo supposed to spawn in the quartermaster's locker?

**Comment by TheBonded** [comment]
with the new changes to economy and vending machines, these might actually end up getting used. nice

**Comment by cacogen** [comment]
I got the cargo one out of the QM's locker like 4 days ago I'm gonna say so unless that new economy PR killed access to the cargo budget with it it should be in use. Either way, nice sprites

**Comment by TheBonded** [comment]
> I got the cargo one out of the QM's locker like 4 days ago I'm gonna say so unless that new economy PR killed access to the cargo budget with it it should be in use. Either way, nice sprites

hopefully we get to see more than just the cargo budget card working at some point.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
