### PR TITLE
lowers swarmer beacon hp

### PR DESCRIPTION
**Pull request by PKPenguin321**
:cl:
tweak: Swarmer beacons now have 750 health, down from 3000.
/:cl:

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=8766&p=232658

Wasn't sure exactly how much to lower it so if this value is bad suggest a better one and I'll change it

If it ever gets loot it can probably be raised again but for now it's too nutty to justify

### CODE REVIEW

**Comment by GunHog** [comment]
Supporting this due to Swarmers being worthless to fight (They do have some worth now that they drop natrual BS crystals, but that is still pretty weak). Until RR gets around to coding some loot for the thing, the swarmer beacon is not worthy of being the highest health boss.

**Comment by Kromgar** [comment]
Hell by the time your hitting the fucking thing the swarmers are all dead. It's not like your zerg rushing that shit

**Comment by jughu** [comment]
>nerfing swarmers not affong normal tendril loot to it and later change it

**Comment by kilkun** [comment]
we need to expand swarmer lore.

are they in cahoots with abductors? who's pulling the strings of the two races? is it an x-com like situation?

**Pull request merged**
