### PR TITLE
[s] My best friend is a holocarp, RELOADED, GONE WRONG

### PR DESCRIPTION
**Pull request by coiax**
So you know what would be better than boring holoparasites? HOLOCARP!

Just put the holocarp fishsticks in your mouth, and you'll be able to catch your own holocarp!

Sure, you can't pick the type of them, but you can have more than one to compensate. Is this balanced? Who knows?

Bonus points if you recognise the fish name list.

NOW WITH ADDED MERGE INTO APRIL FOOLS BRANCH

### CODE REVIEW

**Comment by coiax** [comment]
200 commits? Ooooooo noooooo!

**Comment by coiax** [comment]
I appear to be updating the april fools branch with all of the normal stuff that happened since it was frozen for April Fools.

**Comment by TankNut** [comment]
And that is why you don't branch from master when pushing to the april fools branch

**Comment by coiax** [comment]
nooooooooo. I suppose I can rebase my holocarp changes onto the april fools branch. Not that hard.

**Pull request closed without merging**
