### PR TITLE
Adds a Centcomm reply admin link to the station charter

### PR DESCRIPTION
**Pull request by harmonyn**
bugs me that this doesn't have one, all other CentComm communications do, plus sometimes you want to mock people for their terrible station names but not BSA

### CODE REVIEW

**Comment by Thunder12345** [comment]
While you're add a button to do CentComm messages at any point like the SM button

**Comment by Iamgoofball** [comment]
We don't support fetishes thunder

**Comment by PKPenguin321** [comment]
Do what thunder said please

**Comment by PKPenguin321** [comment]
If it's not too hard I mean. At least add a button to centcomm message to the PP if adding them to every admin alert is too much work.

**Pull request merged**
