### PR TITLE
toy talking is an audible message instead of a visible message (i blind pr)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Talking toys display their icon and speech audibly, not visibly

## Why It's Good For The Game

it's literally TALKING why is it a VISIBLE MESSAGE oh my god

## Changelog

:cl: Melbert
qol: blind people can hear talking toys
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
make it use the say() proc

**Comment by MrMelbert** [comment]
okay shitpost pr done might as well put effort into it now

**Comment by MrMelbert** [comment]
image

nvm the image that it displays doesn't work with say

**Comment by Mothblocks** [comment]
i think thats fine. the images are an old-ish artifact and you can hardly see them anyway

**Pull request merged**
