### PR TITLE
Revert "Ore Stacking"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#33062

Please make a system where the tile has to have a certain amount of a given type on a tile **before** stacking.

Then i'll remove this test merge.

Atm this is immersion breaking (as all stacking is, but even more so here) and it feels like more "cheap game design tricks" intruding on reality.

### CODE REVIEW

**Comment by optimumtact** [comment]
You're being unreasonable

It doesn't make sense to stack literally everything, it only makes sense for some low interactivity objects.

This shouldn't break immersion if done properly.

**Comment by optimumtact** [comment]
I just spoke with MSO and I misunderstood how the stacking works.

I agree, it should only stack when a pile goes > a certain size on the tile.

I assumed it worked that way already, not like the existing metal/glass stacks

**Comment by optimumtact** [comment]
a first cut of the envisioned API

name: piles (to distinguish from stacks)

for pile supporting objects, when the count of those items on a tile goes > some value of N it should pull and delete all those objects, merging them into an abstract "ore" pile type that contains the count of each type of ore.

This then responds to the attackby of mine satchels and their crossed, preventing the lag coming from crossing a tile with 600 ores in it and getting 600 crossed calls on each ore item. Instead you can just pick up until either the pile is gone, or the bag is full, at which point the pile may turn into ores again.

**Comment by optimumtact** [comment]
quite a few things will have to be updated to gain pile support, ore stacker, mine bots and a few others off the top of my head.

atm I can only think of ores as the only pressing obj needing to support this system

**Comment by Bawhoppen** [comment]
I told Kevinz

**Comment by lzimann** [comment]
well i'm sure someone can go and do this properly one day

**Pull request merged**
