### PR TITLE
Adds weather protection to things inside disposals pipes

### PR DESCRIPTION
**Pull request by ShizCalev**
Being inside of a massive pipe lined with lead should protect you from ashstorms, rad storms, ect n stuff. 

:cl: ShizCalev
balance: Things inside disposals pipes are now protected from weather (ashstorms, radstorms, ect.)
/:cl:

### CODE REVIEW

**Comment by hannahscript** [comment]
is this too op? miners will just carry an RPD instead of a shelter capsule now

**Comment by JohnFulpWillard** [comment]
This is very niche but also pretty funny, though I don't see how people would realistically be able to do this outside of a disposal loop.
I was thinking of adding these to crates too, so people can hide in necropolis chests

**Comment by private-tristan** [comment]
> is this too op? miners will just carry an RPD instead of a shelter capsule now

you can already make an area completely ash proof with 10 seconds of work  now that #69781 is merged, simply carry a pickaxe, grab some volcanic ash (10 will be enough) convert it to sandstone, use a PKA on a hole in rock and place a sandstone door infront of the rock so that it makes a 1x1 room with a door out, and make an area

or you can carry a RPD and make an infinite pipe loop to survive but be unable to escape

or you can use the environment bags that you can get from emergency pods iirc

**Comment by ShizCalev** [comment]
> This is very niche but also pretty funny, though I don't see how people would realistically be able to do this outside of a disposal loop.

the intent was infact to give people an "oh shit self flush" option to try to escape from radstorms. that said, even the longest disposals loop trip atm doesn't outlast a radstorm's duration

**Pull request merged**
