### PR TITLE
Fixes families announcement loop

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Basically, the wanted level is checked and the annoucement for upping/lowering it is sent, but wanted level is never actually updated on process. Cue an hour of ATTENTION!!! every two seconds.

## Why It's Good For The Game
ATTENTION!!! ATTENTION!!! ATTENTION!!! ATTENTION!!!

## Changelog
:cl: Skoglol
fix: Families demand slightly less of your attention now.
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Extremely annoying to everyone

**Comment by trollbreeder** [comment]
ATTENTION

**Comment by CRITAWAKETS** [comment]
https://www.youtube.com/watch?v=NxVpuMBywwE

**Comment by interestingusernam3** [comment]
http://starecat.com/content/wp-content/uploads/attention-thanks-for-your-attention-trolling-poster.jpg

**Comment by interestingusernam3** [comment]
https://bit.ly/39QzDEA

**Comment by Iamgoofball** [comment]
overtime

**Pull request closed without merging**
