### PR TITLE
Decrease blood drunk miner move_force

### PR DESCRIPTION
**Pull request by Gamer025**
## About The Pull Request
Blood drunk miner can no longer move stuff like bolted windows or even doors
EDIT:
Blood drunk miner attacking with this PR merged:
https://streamable.com/a5srhr

Miner attacking without this PR:
https://streamable.com/a2i1t9

As you can see nothing changes how the miner fights (on the station which is already rare enough)
The only thing his PR fixes is this:
https://streamable.com/me1j85

And this only happens if well either some player controlled miner walks into the stuff (which I did for the video)
Or if the miner idles and just walks in random directions occasionally
The only reason why I even discovered this was because someone brought the miner to the station on a lowpop Terry round and it walked around in idle mode for some time and started moving airlocks

## Why It's Good For The Game
It seems kinda strange that some mad miner would have the force to just move bolted down doors or windows (or structures in general)

## Changelog
:cl:
tweak: Blood drunk miner megafauna can no longer move structures like bolted down doors / windows
/:cl:

### CODE REVIEW

**Comment by ShibaInuLord** [comment]
just makes the weak BDM weaker.

**Comment by Pumpkinoe** [comment]
to be honest "pushing objects around" never seems to come into combat anyways, hardly a nerf

**Comment by Tlaltecuhtli** [comment]
dumb "lore" excuse which might make this megafauna even more cheesable

**Comment by Gamer025** [comment]
@ShibaInuLord @Tlaltecuhtli I edited the PR description to show that this PR should not make the miner weaker

**Comment by IndieanaJones** [comment]
He teleports anyway, this doesn't really change anything.
BDM is the shittiest "megafauna" anyway, just a poorly-placed Bloodborne reference

**Comment by TheMidnightRose** [comment]
Then extend his vision range a little since now he cannot push doors and windows

**Comment by Gamer025** [comment]
> Then extend his vision range a little since now he cannot push doors and windows

This would probably boost BDM quite a bit since a BDM idling around the station is a rather rare occurrence.
However boosting his vision would also make him a stronger lavaland megafauna, the situation in which you will normally encounter him.
If people really thing BDM is too easy maybe he should completely be rebalanced (move speed, damage, vision etc.)
This is however out of the scope of this PR.

**Comment by IndieanaJones** [comment]
Replace BDM with something actually thematic

Bloodborne reference is shitty, chances are the guy who made him couldn't sprite and just settled for what he could do

**Comment by Doosteroni** [comment]
What if we like........made the blood drunk blood sober and he just chills at a like....desk or something doing like....taxes and stuff

**Comment by Gamer025** [comment]
> What if we like........made the blood drunk blood sober and he just chills at a like....desk or something doing like....taxes and stuff

Did you watch the videos in the PR?
Its attack pattern is literally the same, it only changes the fact that he can't just idle walk into a door and the door magically gets moved into the direction he walked.

**Comment by Doosteroni** [comment]
> Did you watch the videos in the PR?
> Its attack pattern is literally the same, it only changes the fact that he can't just idle walk into a door and the door magically gets moved into the direction he walked.

You ARE aware that was complete satire I literally just suggested making the blood drunk sit at a desk doing taxes

**Comment by Gamer025** [comment]
> > Did you watch the videos in the PR?
> > Its attack pattern is literally the same, it only changes the fact that he can't just idle walk into a door and the door magically gets moved into the direction he walked.
> 
> You ARE aware that was complete satire I literally just suggested making the blood drunk sit at a desk doing taxes

Well I understood it as complaint about nerfing the BDM even more so that you can literally just make it some tax worker because he is so easy. Sorry if that was not the intend.

**Comment by Doosteroni** [comment]
> Well I understood it as complaint about nerfing the BDM even more so that you can literally just make it some tax worker because he is so easy. Sorry if that was not the intend.

No I just got really smashed and shitposted on git I don’t really care about the nerf.

**Pull request merged**
