### PR TITLE
A christmas miracle! Adds english fruitcake. 

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR adds the ability to craft english fruitcakes using:
* 1 plain cake
* 1 raisin
* 1 cherry
* 5u rum

bild

Permission:
bild

## Why It's Good For The Game
It is an absolute holiday classic and quite different than most of our other cakes which are more sponge style cakes.

## Changelog

:cl:
expansion: Added a new cake, the english fruitcake.
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
Cute!

**Comment by SuperNovaa41** [comment]
:face_with_raised_eyebrow:

**Comment by LemonInTheDark** [comment]
Imagine not liking fruitcake

**Comment by optimumtact** [comment]
i detest fruitcake

**Comment by LemonInTheDark** [comment]
I love it

**Pull request merged**
