### PR TITLE
Adds ability to open firelocks with an empty hand

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

If you have an empty hand and walk into or click a firelock you can open it with a five second do_after. Firelocks have an examine message that explains this.

## Why It's Good For The Game

Fastmos often triggers firelocks across the station. This creates a great deal of frustration on behalf of the players and can lead to shuttle calls. Getting a crowbar roundstart is basically mandatory now, but not enough people have them to alleviate the issue.

This reduces the frustration of mass firelocks and the amount of resulting shuttle calls. 

## Changelog
:cl: cacogen
balance: Firelocks can be opened with an empty hand after five seconds by walking into or clicking them now 
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -11. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Time-Green** [comment]
This is a godsend. So many people die from firelocks because they didn’t happen to have a crowbar, this is especially bad with coldmos critting within 15 seconds. 

I’d honestly go as far as making it take way less then 5 seconds, because that’s usually all someone has before they just fall over and die

**Comment by cacogen** [comment]
Thank you for sharing the problems you've seen. I picked five seconds because I thought it was more likely to be merged with a somewhat conservative number. I wouldn't mind it being less than that. Just needs not to be instant like crowbars.

**Comment by zxaber** [comment]
Firelocks are (presumably) meant to section off areas to save the rest of the station. If we make them too easy to open, do they even serve their purpose? Normal airlocks already block air when closed but allow crew to flee danger.

To be honest, firelocks closing from excessive cold is the root cause and I think we should just revert that.

**Comment by Tlaltecuhtli** [comment]
>Firelocks are (presumably) meant to section off areas to save the rest of the station. If we make them too easy to open, do they even serve their purpose? Normal airlocks already block air when closed but allow crew to flee danger.

people without crowbar will reset firelocks with the alarm making it whatever coldmos effect spread even faster

and yes firelocks had only purpose of killing people, whats the point of firelocking when the plasma fire comes from inside the vents?

**Comment by Megamaw** [comment]
recently had a round where i was trapped in a room where disabling the fire alarm momentarily would only give me access to doors that i had no access to. the hall was right next to me, and i was stuck waiting there for like eight minutes slowly waiting to die until the round ended.

listen, i get the idea behind firelocks, or what people say it is. frankly, in the last decade or so, it's become apparent they do little for safety in emergencies and are in most scenarios a deathtrap for players who didn't grab a crowbar roundstart.

a lot of stuff in ss13 is 'built to fail' or be sabatoged. but, there's a difference between dying and basically just waiting to die. it's not fun, or interesting.

this would still reward a savvy player expecting to deal with this situation by bringing a crowbar without just saying 'whoops you didn't pick a crowbar up roundstart, looks like you just either ghost or just wait for someone else to be nice'. 

it doesn't remove the danger. which is good! but it also keeps the danger in a much less uninteractive way.

**Comment by Farquaar** [comment]
I think the answer is to fix the underlying issues with firelocks closing when they shouldn't, not this.
Airlocks are interesting as they are. Sometimes they save lives, sometimes they trap/kill people. This creates interesting situations where players get involved in rescue. It's a rewarding experience to pry open a firelock, triage the survivors, and carry a barely-conscious sap back to the shuttle.

Firelocks, as they are, add an interesting layer of gameplay when the station is heavily damaged, and I think that making firelocks openable without tools is a mistake.

**Comment by Mothblocks** [comment]
> I think the answer is to fix the underlying issues with firelocks closing when they shouldn't, not this.

:+1:

**Comment by PKPenguin321** [comment]
Definitely agree with the two above me, maybe it could work like if you manually open firelocks via the alarm button they'll be forced to stay open for 10 seconds so they don't insta-close again from fastmos

**Comment by Megamaw** [comment]
You know what? Yeah, my take is probably just colored by a particularly frustrating recent experience that might have just been an issue with map design.

**Comment by Mothblocks** [comment]
CC @LemonInTheDark, but I don't really like this one.

**Comment by Tlaltecuhtli** [comment]
mapdesign fix would be splitting all giga areas like hallways into room sized ones or have firelock alarms trigger shit in view instead of area based grabage

**Comment by itseasytosee** [comment]
there has to be a better solution.

**Comment by TheBonded** [comment]
What if we replace firelocks with smaller variants like the windoors on the HoPline, so when one side opens the other side closes, so people can move out of dangerous areas without venting the next room they go into?

**Comment by cacogen** [comment]
>I think the answer is to fix the underlying issues with firelocks closing when they shouldn't, not this.

Yeah, I anticipated this type of thinking. I originally addressed it in the PR body but thought I'd leave it for if I actually had to deal with it.

People have been complaining about firelocks since fastmos was added. Are there any other PRs up dealing with the issue? If firelocks are made to trigger less often and this is no longer seen as necessary then it can be reverted.

**Comment by PKPenguin321** [comment]
>That would just undermine the entire point of firelocks.

well it's more or less how they worked before fastmos though right? maybe not 10 whole seconds but some amount of buffer

**Comment by LemonInTheDark** [comment]
That buffer was the delay between hotspot processes.

Not really sure why this was closed, but I agree with jared. I'd prefer firelocks be less area based when reacting to heat/cold, rather then just patching over that issue

**Comment by cacogen** [comment]
Gonna reopen this because these things are triggered nearly every round and whatever is causing it usually isn't fixed. Even having a crowbar doesn't solve the problem of trying to climb a table covered by a firelock. The firelock recloses too quickly. If the issue is resolved properly and this is no longer considered necessary it can be reverted. That looks like it's going to be far off to me. This is hardly neutering the atmospherics system, though.

**Comment by Cyprex** [comment]
> well it's more or less how they worked before fastmos though right? maybe not 10 whole seconds but some amount of buffer

I've recently come back to the game and I'm pretty sure firelocks were quick beforef fastmos too, I haven't noticed them shut quicker after being manually opened at all.

**Comment by LemonInTheDark** [comment]
@cacogen I'm not interested in this as it currently is, do you plan on changing it? Or am I wrong.

**Comment by Tlaltecuhtli** [comment]
would this for people with basic engi access (atmos tech, engi tech and paramedic) be fine??

**Comment by cacogen** [comment]
@LemonInTheDark
>Not really sure why you closed this cacogen

This lead me to believe you were fine with this. I'm not sure what changes you want. I'm surprised you'd think this needed them. Five seconds to open a firelock barehanded is not much of a boon. It certainly doesn't neuter the atmospherics system.

It's a weak nerf to firelocks because:

1. Mass lockdowns occur over and over again across a huge area, so 5 seconds to open makes it impractical to cover large distances without a crowbar
2. If you're dying in a firelocked area, 5 seconds to open is a long time (especially if the next "cell" isn't safe either)

I wouldn't mind this being closed if it seemed like there was going to be a proper fix for this issue anytime soon. But you seem to not take the problems the players are complaining about seriously. It makes me wonder how often you play.

>I'd prefer firelocks be less area based when reacting to heat/cold

So do that. I don't know how and I'm not the one who created the issue. In the meantime, you could merge this as something that temporarily eases the problem. I see it serving your interests by easing player negativity towards fastmos and by extension you as a coder.

**Comment by LemonInTheDark** [comment]
> This lead me to believe you were fine with this. I'm not sure what changes you want. I'm surprised you'd think this needed them. Five seconds to open a firelock barehanded is not much of a boon. It certainly doesn't neuter the atmospherics system.

I was confused about why this got closed with no mention of why. I'm sorry if I mislead you.

> I wouldn't mind this being closed if it seemed like there was going to be a proper fix for this issue anytime soon. But you seem to not take the problems the players are complaining about seriously. It makes me wonder how often you play.

> So do that. I don't know how and I'm not the one who created the issue. In the meantime, you could merge this as something that temporarily eases the problem. I see it serving your interests by easing player negativity towards fastmos and by extension you as a coder.

There's someone working on unhooking firelocks from areas, we'll see how that works out. I've got hope.
I don't play often, but I observe a good deal. I'm not blind to the issues you're describing, I just disagree with how you want to fix them. 
On that note, I don't want to end up in a position where I'm merging things for a short period of time to replace it later, especially if the fix for this doesn't end up being "make space not code/firelocks not drop when cold", in which case what matters isn't that it's happening, but that it's still a painpoint.

As for serving my interests, I'm coding for the future. My concern is how the game plays when I'm done bringing atmos tech into ability parity with LINDA, and making the game loop of fixing things engaging/fun. I don't care if you're mad at me, or if other people are. I did at one point, but that's gone.

**Pull request closed without merging**
