### PR TITLE
Umbra hotfixes (please merge ASAP)

### PR DESCRIPTION
**Pull request by ghost**
- Umbra notifications now play a sound and can be clicked to take control of the umbra.
- Strange umbra behaviors with movement and collision have been fixed.
- Thoughtsteal can no longer be used while possessing someone.
- Umbra objective numbers are now properly assigned via bandaid fix.

### CODE REVIEW

**Comment by Kromgar** [comment]
Its fuckign invisible... and why is Umbra on a first come first serve basis?

**Comment by lzimann** [comment]
why is it still named umbra

**Comment by Xhuis** [comment]
@Kromgar Because I didn't want to make yet another preference and ghost role selection code seems to change every fucking microsecond
@Izimann Because you touch yourself at night

**Comment by Thunder12345** [comment]
@Xhuis Why not make it a lottery like most other random events are?

**Comment by Cheridan** [comment]
>the code standard gets changed a lot so i made my own standard

:expressionless:

**Comment by Xhuis** [comment]
huh?
@Thunder12345 Reasons mentioned above. Once these fixes get merged I can see about changing it.

**Pull request merged**
