### PR TITLE
Breathing sounds remake

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Sounds made by me and edited by Beeblie
- reduced volume of the looping sound from 12 to 7
- removed previous breathing sound
- added 8 variants of breathing
- put more time between the sounds in the loop
- enabled vary

https://github.com/user-attachments/assets/60e5c034-5656-49a9-8bd7-8390ac97e6ac

## Why It's Good For The Game
Previously there was only one sound which very quickly got repetetive, having 8 different sounds (even if they're largely similar) should help cut down on the ear fatigue.
## Changelog
:cl: grungussuss and Beeblie
sound: internals breathing sound has received more variance and had its volume reduced
/:cl:

### CODE REVIEW

**Comment by AMyriad** [comment]
Not sure if you noticed but there is some static!
It's very noticeable since people will be hearing this constantly out in the nigh-silent vacuum of space.

**Comment by Artemchik542** [comment]
> Not sure if you noticed but there is some static! It's very noticeable since people will be hearing this constantly out in the nigh-silent vacuum of space.

I personally disabled this breathing sound because after it I started hearing phantom sounds of the same breathing even after turning off the tank. It's a bit annoying. (or maybe the sound continued to play, but because of a bug)

**Comment by Sadboysuss** [comment]
> Not sure if you noticed but there is some static!
> It's very noticeable since people will be hearing this constantly out in the nigh-silent vacuum of space.

Yeah I can hear it, FUCK

**Comment by Sadboysuss** [comment]
for some reason I could hear it on my phone but not on my computer where I have really good headphones, really odd.

**Pull request merged**
