### PR TITLE
Replaces the weed sprites, and removes the /goon folder.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

This replaces all the weed sprites with ones that aren't from Goon, made by myself.

Screenshot_311

This also removes the /goon folder.

## Why It's Good For The Game

The old sprites looked pretty crusty, and i think the new ones look better.

Also, it gets rid of the last icons in the /goon folder, so i went ahead and deleted it.

If it's ever needed again, it can always be added back in.

## Changelog

:cl:
imageadd: Cannabis plants have recieved some new sprites.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
I'm not feeling the sprites, personally, these are a lot more flat and less well defined. Plus, the item sprites are much larger, so 100% potency versions of those plants are going to look huge in-game.

Photo reference says that cannabis leaves are waxy, so adding some shine to the sprites might help. That's just me, though.

**Comment by bruhlookatthisdood** [comment]
why do all the omega cannabis have a little white dot that flashes topleft during the animation?
hrmm

**Comment by ArcaneMusic** [comment]
> why do all the omega cannabis have a little white dot that flashes topleft during the animation? (or icon diff bot is broke) hrmm

(That's just IconDiffBot, it's fine)

**Comment by JohnFulpWillard** [comment]
NOOOOOOOOO

**Comment by Imaginos16** [comment]
After much deliberation, I'll merge it until a suitable alternative replaces the sprites. I want my mandate to be completed at this point.

**Pull request merged**
