### PR TITLE
Makes belts clickable in their centers

### LINKED ISSUE #21327: belts (clothing) have an annoying one pixel wide line hole at the center
You try to click the belt but you fail because you clicked the floor below it instead, congratulations!

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #21327
untitled

### CODE REVIEW

**Comment by Cyberboss** [comment]
Shit i fucked up whats the special alpha value?

**Comment by Kraseo** [comment]
There's a slider when editing sprites in dreammaker on the left that lets you control the alpha.

**Comment by ChangelingRain** [comment]
Generally people just use 1 alpha black pixels for this, nobody really notices.

**Comment by Cyberboss** [comment]
Yeah thats what I did just now

**Comment by optimumtact** [comment]
yeah that's what I mean

**Pull request merged**
