### PR TITLE
Moved food_reagents.dm,drink_reagents.dm and alcohol_reagents.dm to food&drinks folder in modules.

### PR DESCRIPTION
**Pull request by Firecage**
As it says on the tin.

Moves food_reagents.dm from code/modules/reagents/chemistry/reagents/chemistry/reagents to code/modules/food&drinks/food

Moved drink_reagents.dm and alcohol_reagents.dm from code/modules/reagents/chemistry/reagents/chemistry/reagents to code/modules/food&drinks/drinks

Put a notice for the moved files in reagents.dm.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:

Keep reagents in reagents.

**Comment by Firecage** [comment]
@Iamgoofball Well, I do believe that the ones involving drinks, should be at the drinks certain, and the ones involving food, should be at the foods section. Before I made this PR, I did first ask in coderbus and Cheridan if it would be okay if I did this PR, and the answer was yes.

**Comment by Iamgoofball** [comment]
@phil235 was the guy who did the current reagent organization. His call.

**Comment by Firecage** [comment]
Well, if @phil235 says they should stay where they were, then I'le close the PR. Will wait for his response.

**Comment by phil235** [comment]
I'm with goof, I don't see the point of this change. Having all reagents together is more intuitive.

**Comment by Firecage** [comment]
Okay, it was Phil's call.

**Pull request closed without merging**
