### PR TITLE
Adds new collector sprites

### PR DESCRIPTION
**Pull request by CakeQ**
:cl: Cakey
imageadd: Added new radiation collector sprites
/:cl:

SICK!!!! new collector sprites

radcolle

### CODE REVIEW

**Comment by chanoc1** [comment]
the shading could use some work. also, are you using a palette?

**Comment by CakeQ** [comment]
Sprites were made by a friend of mine for our server and @Iamgoofball told me to PR it here.

**Comment by chanoc1** [comment]
O. well tell him to make them better :^)))

**Comment by optimumtact** [comment]
Can you show these in game?

**Comment by PKPenguin321** [comment]
no offense but these are kinda bad

**Comment by CakeQ** [comment]
radcolle

**Comment by Niknakflak** [comment]
Kinda weird

**Comment by PKPenguin321** [comment]
well i guess they're not as bad in game

would be cool to have a side by side comparison with old sprites

**Comment by optimumtact** [comment]
I like them

**Comment by MrPerson** [comment]
I hate them. You can't tell if there's a plasma canister inside already or not. I mean you can, but it's a tiny black box turning dark grey.

**Comment by Metallusions** [comment]
The tiny black box that turns grey should turn orange instead to show a plasma tank inside.

I don't know, the actual collector array seems a bit small.

**Comment by Kromgar** [comment]
Add in the orange bit and it should be fine

**Comment by CakeQ** [comment]
orange bit added 👌

**Comment by WJohn** [comment]
From a perspective standpoint, these things are a complete mess. I can't tell if they're flat-in-front for the pole, top down for the plate at the bottom, or some bizzare mishmash in 3/4th that doesn't work.

The pole is not aligned in the center of the plate, the little extending collector pads just seem to hide behind the pole, then swing in front to connect??

I'm really not a fan of these sprites at all. Our current ones are bad, yes, but I think these may be worse.

**Comment by optimumtact** [comment]
How can you say that? the current sprites for collectors are garbage

**Comment by Kromgar** [comment]
I imagined that these things extend out and create a kind of Circular energy barrier full of plasma that then collects the radiation

**Comment by WJohn** [comment]
Yeah I can't visualize that happening at all. That doesn't even really make much sense as a way to collect radiation. Why make a circular energy barrier when the radiation is coming from one direction??

**Comment by TrustyGun** [comment]
I have to agree with WJ. These sprites look worse than our current ones; sorry.

**Comment by Iamgoofball** [comment]
Ignore these retards these are awesome sprites

**Comment by CakeQ** [comment]
It's more venus flytrap shaped except the two sides are stored compacted then extend out when in use

**Comment by Ausops** [comment]
the animation is really well done but wj is right about confusing perspective, especially if you get told about it and stare for a while

a plasma tank being inserted and turning purple from orange is a bit odd also

**Comment by WJohn** [comment]
I'm gonna have to deny this in its current state. There's too many problems and as a whole it's not an improvement on what we have right now. If I had to choose between two equally bad sprites, I'd pick the one we have now if for no other reason than familiarity.

Let me know if you have some new sprites in mind, and I'll see about reopening this.

**Comment by Iamgoofball** [comment]
Fuck you Wj I'm reopening this

**Comment by Iamgoofball** [comment]
Fuck you Wj I'm reopening this

Like oh my god "for familiarity"

Stop being a retard, why are you allowed to force through your own sprites that players dislike for similarity not being there but then whine about a direct quality increase?

**Comment by dannno** [comment]
WJohnston is the guy in charge of art. Stop being a child.

**Comment by chanoc1** [comment]
rekt

**Pull request closed without merging**
