### PR TITLE
Removes the hot variants of necropolis tiles and walls

### PR DESCRIPTION
**Pull request by ChangelingRain**
@FuryMcFlurry isn't spriting more things in this palette and I don't think it's practical to have both palettes since they don't blend well with each other, so, accordingly...

### CODE REVIEW

**Comment by Xhuis** [comment]
I'm actually in the progress of making the stone tiles, at least, have a function for mapping. If it isn't too much to ask, may you keep those in, and just remove the turfs?

**Comment by ChangelingRain** [comment]
Honestly I'd rather not since that palette won't be properly supported

**Comment by Xhuis** [comment]
Well, alright. I should be able to keep the same effect by using color matrices, at any rate, so it's not the end of the world.

**Review by Cyberboss — APPROVED** [review]

**Comment by FuryMcFlurry** [comment]
Could you not var-edit the color of the tiles? it would look shitty however.

**Comment by Tacolizard** [comment]
@FuryMcFlurry afaik varediting things in maps isn't really allowed.

**Comment by FuryMcFlurry** [comment]
@Tacolizard Oh, was not familiar with that rule.

I doubt anyone would miss the red tiles. I could post my sprite sheet after it has been completed so people can shift the hues for hot pink hell tiles or whatever.

**Comment by Xhuis** [comment]
The thingy in question was #29042. I wanted to use the red tiles as an obvious indicator that they were different; however, for now, I simply won't replace existing stuff with them; no great loss!

**Comment by FuryMcFlurry** [comment]
@Xhuis  I do have some sunk tiles you could use 
image if you want it of course.

**Comment by ChangelingRain** [comment]
Those are already in!

**Comment by FuryMcFlurry** [comment]
See. The world is a better place already. You just have to realise it.

**Comment by Xhuis** [comment]
Hmm. I might have to do that! Currently they just fade out.

**Pull request merged**
