### PR TITLE
Allows bucklecuffing to tables

### PR DESCRIPTION
**Pull request by silicons**
:^)

### CODE REVIEW

**Comment by TehZombehz** [comment]
The next age of table combat has arrived.

**Comment by calzilla1** [comment]
MEHKI

**Comment by jughu** [comment]
Only if comes with reactive buckle armour

**Comment by FantasticFwoosh** [comment]
Only tables with legs please *excluding ayy & reinforced), and it should shift the sprite slightly to the side facing the way so it looks like they are slightly off the table rather than strapped into it fnr.

> For consistency in a 3x3 square you can't tablecuff someone in the middle of it, but can cuff them to the table legs of everywhere around.

**Comment by Pascal125** [comment]
Fetish code.

**Comment by Qbopper** [comment]
-1 because >how are they being strapped to the table

I like @FantasticFwoosh 's idea though

**Comment by KorPhaeron** [comment]
OP included no justification for how this improves the game so I'll assume its a joke

**Comment by evsey9** [comment]
It makes our combat system even more robust

**Pull request closed without merging**
