### PR TITLE
[s] Attempts to add hidden finger print logging for telekinesis actions

### LINKED ISSUE #26571: Throwing a thing or using machinery via telekinesis doesn't leave behind fingerprints for admin
https://i.gyazo.com/123bf43a6c7e73e01512086c1a50d34b.gif

Telekinesis should leave a fingerprint behind (for admin reasons)

Also pretty sure that telekinesis doesn't leave fingerprints *anywhere*, which can lead to certain situations where it's hard to prove theres a tele grief if there's only one witness reporting it and the admin didn't see it.

### PR DESCRIPTION
**Pull request by ma44**
[s] tag is used because it can be used to grief something (emitters, messing up machinery or some other creative thing) without leaving behind evidence for admins to see who did it

Fixes #26571 

_time to test this later or something and hope it compiles k for now_

### CODE REVIEW

**Comment by Cyberboss** [comment]
I already tried to do this, but you're making the same mistake I did apparently #26072

**Comment by ExcessiveUseOfCobblestone** [comment]
which is odd because in reality I'd much rather have a bunch of procs because the proc name

1) tells me what it does
2) allows me to easily find it because I can search "proc/ProcIWantToFind"

**Comment by ma44** [comment]
Note: not ready to merge yet, don't feel like cyberbossing the server

**Comment by optimumtact** [comment]
You're still missing the things raised in cyberbosses pr's

**Pull request closed without merging**
