### PR TITLE
Converts all maps to TGM.

### PR DESCRIPTION
**Pull request by Iamgoofball**
# OVER 2 MILLION CHANGED LINES

STEP ASIDE NEERSIGHTED

THERE'S A NEW LINE KING IN TOWN

### CODE REVIEW

**Comment by Incoming5643** [comment]
What is the benefit of this

**Comment by KazeEspada** [comment]
All the benefits of the TGM format.
More git friendly, and the dmm parser in dream daemon can read it just fine.

**Comment by Iamgoofball** [comment]
Yeah, this cuts down on conflicts because now you have to touch the exact same object and the exact same variable on that object to cause conflicts. This was going to end up being done eventually because the map merger we have now automatically TGMizes files.

**Comment by xxalpha** [comment]
You need to modify the exact same tile to hope for conflicts to happen with the expanded format.

**Comment by JJRcop** [comment]
Travis is OK on all maps except for asteroidstation, disregard the X
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by WJohn** [comment]
Oh dear god.

**Comment by xxalpha** [comment]
This will break things. Convert only the maps that are not loaded at runtime. Away missions and templates will not load if they are in this format.

**Comment by PKPenguin321** [comment]
>2 million line changes

the absolute madman

**Comment by tkdrg** [comment]
> *** glibc detected *** DreamMaker: realloc(): invalid old size: 0x0e85ed38 ***

Does this mean the new asteroid map exceeds the maximum memory size for maps? Can you compile it locally?

**Comment by xxalpha** [comment]
No, the problem is with the z5.dmm map of asteroid.

**Comment by tedward1337** [comment]
I like this
I believe in you goofball

**Comment by KorPhaeron** [comment]
Dead PR, dunc is going to change every map anyway so you'll have to redo this

**Pull request closed without merging**
