### PR TITLE
Adds skub to the game.

### PR DESCRIPTION
**Pull request by lzimann**
Turns out I'm a skrub.
Sprite by Nienhaus: 

skub

:cl: Lzimann
:rscadd: Skub added to the game. You can find it in your local clown's backpack.
/:cl:

### CODE REVIEW

**Comment by KazeEspada** [comment]
Remove skub you fucking scrub.

**Comment by Supermichael777** [comment]
wrong branch freindo

**Comment by lzimann** [comment]
it is the right one

**Comment by TheRealGLH** [comment]
Trying to add this shit again after the previous PR was closed?
How typical of pro-skub """""people"""""

**Comment by CPTANT** [comment]
BOOOOO, down with skub.

**Comment by Iamgoofball** [comment]
skub forever

**Comment by Archie700** [comment]
>MSO upvoted anti-skub

Give it up pro-skubber

**Comment by optimumtact** [comment]
SKUB 4 LYFE

**Comment by KorPhaeron** [comment]
Remake of another PR, it has been over 24 hours

**Comment by Archie700** [comment]
why would you do this

**Comment by optimumtact** [comment]
skub wins!

**Comment by Iamgoofball** [comment]
SKUB FOREVER

**Pull request merged**
