### PR TITLE
Disables minimum account age for TRAITORS and TRAITORS ONLY

### PR DESCRIPTION
**Pull request by Iamgoofball**
Traitor is the basic gamemode for new players. It doesn't matter if they're bad or good, there's 7 other traitors if they fuck it up.

I can understand locks on cult, nuke ops, etc., but on traitor? This is a great learning experience for new players. They can kill shit and not get in trouble.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Should probably be a config option for solo and team antags.

**Comment by Armhulen** [comment]
I really agree with this, thank you for non meme pr

**Comment by Dorsisdwarf** [comment]
Yeah, its nice to have bumbling traitors amongst the hyperpro memelords

**Comment by optimumtact** [comment]
no

**Comment by Robustin** [comment]
I don't see a reason for it. People should at least know how to move items around and learn the basics before being thrown into a traitor role. 

Then again the age requirement is so low, by the time people even learn about job preferences they're qualified for all antags.

**Comment by KorPhaeron** [comment]
Because retaining new players is difficult in any game

Because we are a tiny niche game that has even more difficulty retaining players.

Because its ridiculous that new players or players coming from other servers are expected to wait 2 weeks to play what is arguably the most fun part of the game.

**Comment by ChangelingRain** [comment]
Make it one day of waiting, so you can be reasonably sure they have at least basic skill

**Comment by Iamgoofball** [comment]
1 day is about as long as someone has to get hooked innto the game

if they dont roll antag at all that first day they'll get bored and never come back

**Pull request merged**
