### PR TITLE
[DNM] Adds hydrogen

### PR DESCRIPTION
**Pull request by ghost**
so i played on bay12 for a bit, and after finding how fun of a gas hydrogen is as a traitor, i decided to port it here!

:cl: More Robust Than You
add: Hydrogen.
/:cl:

- [x]  Initial gas
- [ ]  SM interactions
- [ ] Canisters/tanks

### CODE REVIEW

**Comment by Buggy123** [comment]
Okay.

What does it do?

**Comment by MoreRobustThanYou** [comment]
catch on fire. i plan to make it do shit with the SM later

**Comment by nicbn** [comment]
Please make it explosive on high amounts

**Comment by Buggy123** [comment]
Can it burn to produce water vapor? Because I was thinking of adding a water vapor reaction, and this would be perfect because this is how water is made.

**Comment by MoreRobustThanYou** [comment]
@Buggy123 Would 1 Hydrogen + 2 Oxygen = 3 Water Vapor? heh. that's pretty much how reactions are in the code

**Comment by nicbn** [comment]
No. 2 hydrogen + 1 oxygen = 2 water vapor

**Comment by MoreRobustThanYou** [comment]
Ok. How much heat?

**Comment by nicbn** [comment]
Same heat as regular fire. But if there's a lot of hydrogen, it explodes.

**Comment by DaedalusGame** [comment]
Make dumping hydrogen reagent produce this gas
Make tritium decompose into minor radiation and hydrogen under specific conditions that hopefully don't include pressure or heat.

**Comment by MoreRobustThanYou** [comment]
@nicbn which is?

**Comment by MoreRobustThanYou** [comment]
i don't understand gas math

**Comment by DaedalusGame** [comment]
ok fuck you i'll do it you coward

**Comment by Buggy123** [comment]
Technically 2 moles of hydrogen + 1 mole of oxygen = 1 mole of water but this is SS13 we don't need to keep to strict mole ratios.

The real amount of heat is uh...
1 mole of H2+1/2 mole of O2 reacted with absolutely nothing else would end up at 3211 Kelvin, plus whatever temp it started at aaaaaaaand while i was doing this math the pr was closed great.

**Comment by DaedalusGame** [comment]
calculate specific heat from this and we're golden

**Comment by nicbn** [comment]
2 H2(g) + O2(g) → 2 H2O(l) + 572 kJ (286 kJ/mol)

**Comment by Buggy123** [comment]
Ironically I calculated(actually googled because CBA) both of those to find the temperature it'd end up at.

**Comment by DaedalusGame** [comment]
ok i will produce this but not without memes

**Comment by Buggy123** [comment]
Specific heat for hydrogen: 28.84896 joule per mole per degree kelvin
heat of combustion for hydrogen:
>2 H2(g) + O2(g) → 2 H2O(l) + 572 kJ (286 kJ/mol)

**Comment by DaedalusGame** [comment]
500000 that's like 5 times the combustion energy of carbon

**Comment by nicbn** [comment]
Yes it is

**Comment by Buggy123** [comment]
Low molar mass does weird shit

**Comment by nicbn** [comment]
Who wins
Tetravalent main component of everything that is organic
Or
One thicc proton

**Pull request closed without merging**
