### PR TITLE
Fixes an unreported bug in paper.dm

### PR DESCRIPTION
**Pull request by TheVekter**
Mandurrh removed some text re: being unable to use the stamp as a clown, but forgot to remove the clown definition. Was causing warnings. Fixed it!

E: I yoinked 8k from @Iamgoofball he's so salty rn

### CODE REVIEW

**Comment by optimumtact** [comment]
Check those digits baby

**Comment by TheVekter** [comment]
I'll squash this later when I'm not busy.

**Comment by Jordie0608** [comment]
#7977
????

**Comment by dannno** [comment]
you stole 8000 for something that was already fixed
nice

**Comment by TheVekter** [comment]
How the fuck was my branch 100% up-to-date yet this fix wasn't in mine?

**Comment by Razharas** [comment]
>Fake code pr to steal dat get

Paprika is gone, hail new paprika

**Comment by TheVekter** [comment]
Legit 100% was not fixed on my end, I've NEVER had that warning come up before, what the fuck git

**Comment by Jordie0608** [comment]
https://github.com/tgstation/-tg-station/compare/master...TheVekter:clownthingfixyoink8k

It makes no sense.

**Comment by JJRcop** [comment]
And I had [this branch](https://github.com/JJRcop/-tg-station/tree/orange-orange) prepared in advance, guess I missed it, oh well.

**Comment by Chocobro** [comment]
that fucking label hahahaha

**Comment by Niknakflak** [comment]
Well, theres always 9000 everyone.

**Comment by Miauw62** [comment]
```
                                                                                      
                                                                                      
                                          ,--,             ____                       
                                        ,--.'|           ,'  , `.                     
                                        |  | :        ,-+-,.' _ |             ,---.   
                                        :  : '     ,-+-. ;   , ||            '   ,'\  
   ,--.--.        .--,     .--,         |  ' |    ,--.'|'   |  || ,--.--.   /   /   | 
  /       \     /_ ./|   /_ ./|         '  | |   |   |  ,', |  |,/       \ .   ; ,. : 
 .--.  .-. | , ' , ' :, ' , ' :         |  | :   |   | /  | |--'.--.  .-. |'   | |: : 
  \__\/: . ./___/ \: /___/ \: |         '  : |__ |   : |  | ,    \__\/: . .'   | .; : 
  ," .--.; | .  \  ' |.  \  ' |         |  | '.'||   : |  |/     ," .--.; ||   :    | 
 /  /  ,.  |  \  ;   : \  ;   :         ;  :    ;|   | |`-'     /  /  ,.  | \   \  /  
;  :   .'   \  \  \  ;  \  \  ;         |  ,   / |   ;/        ;  :   .'   \ `----'   
|  ,     .-./   :  \  \  :  \  \         ---`-'  '---'         |  ,     .-./          
 `--`---'        \  ' ;   \  ' ;                                `--`---'              
                  `--`     `--`                                                       
          _____                _____                _____                            _____            _____                    _____                   _______         
         /\    \              |\    \              |\    \                          /\    \          /\    \                  /\    \                 /::\    \        
        /::\    \             |:\____\             |:\____\                        /::\____\        /::\____\                /::\    \               /::::\    \       
       /::::\    \            |::|   |             |::|   |                       /:::/    /       /::::|   |               /::::\    \             /::::::\    \      
      /::::::\    \           |::|   |             |::|   |                      /:::/    /       /:::::|   |              /::::::\    \           /::::::::\    \     
     /:::/\:::\    \          |::|   |             |::|   |                     /:::/    /       /::::::|   |             /:::/\:::\    \         /:::/~~\:::\    \    
    /:::/__\:::\    \         |::|   |             |::|   |                    /:::/    /       /:::/|::|   |            /:::/__\:::\    \       /:::/    \:::\    \   
   /::::\   \:::\    \        |::|   |             |::|   |                   /:::/    /       /:::/ |::|   |           /::::\   \:::\    \     /:::/    / \:::\    \  
  /::::::\   \:::\    \       |::|___|______       |::|___|______            /:::/    /       /:::/  |::|___|______    /::::::\   \:::\    \   /:::/____/   \:::\____\ 
 /:::/\:::\   \:::\    \      /::::::::\    \      /::::::::\    \          /:::/    /       /:::/   |::::::::\    \  /:::/\:::\   \:::\    \ |:::|    |     |:::|    |
/:::/  \:::\   \:::\____\    /::::::::::\____\    /::::::::::\____\        /:::/____/       /:::/    |:::::::::\____\/:::/  \:::\   \:::\____\|:::|____|     |:::|    |
\::/    \:::\  /:::/    /   /:::/~~~~/~~         /:::/~~~~/~~              \:::\    \       \::/    / ~~~~~/:::/    /\::/    \:::\  /:::/    / \:::\    \   /:::/    / 
 \/____/ \:::\/:::/    /   /:::/    /           /:::/    /                  \:::\    \       \/____/      /:::/    /  \/____/ \:::\/:::/    /   \:::\    \ /:::/    /  
          \::::::/    /   /:::/    /           /:::/    /                    \:::\    \                  /:::/    /            \::::::/    /     \:::\    /:::/    /   
           \::::/    /   /:::/    /           /:::/    /                      \:::\    \                /:::/    /              \::::/    /       \:::\__/:::/    /    
           /:::/    /    \::/    /            \::/    /                        \:::\    \              /:::/    /               /:::/    /         \::::::::/    /     
          /:::/    /      \/____/              \/____/                          \:::\    \            /:::/    /               /:::/    /           \::::::/    /      
         /:::/    /                                                              \:::\    \          /:::/    /               /:::/    /             \::::/    /       
        /:::/    /                                                                \:::\____\        /:::/    /               /:::/    /               \::/____/        
        \::/    /                                                                  \::/    /        \::/    /                \::/    /                 ~~              
         \/____/                                                                    \/____/          \/____/                  \/____/                                  
                                                                                                                                                                       
                                           o                                             
                                          <|>                                            
                                          / \                                            
    o__ __o/   o      o    o      o       \o/  \o__ __o__ __o      o__ __o/    o__ __o   
   /v     |   <|>    <|>  <|>    <|>       |    |     |     |>    /v     |    /v     v\  
  />     / \  < >    < >  < >    < >      / \  / \   / \   / \   />     / \  />       <\ 
  \      \o/   \o    o/    \o    o/       \o/  \o/   \o/   \o/   \      \o/  \         / 
   o      |     v\  /v      v\  /v         |    |     |     |     o      |    o       o  
   <\__  / \     <\/>        <\/>         / \  / \   / \   / \    <\__  / \   <\__ __/>  
                  /           /                                                          
                 o           o                                                           
              __/>        __/>                                                           
 ____ ___  ____  _   _     _      ____  ____ 
/  _ \\  \//\  \//  / \   / \__/|/  _ \/  _ \
| / \| \  /  \  /   | |   | |\/||| / \|| / \|
| |-|| / /   / /    | |_/\| |  ||| |-||| \_/|
\_/ \|/_/   /_/     \____/\_/  \|\_/ \|\____/
                                             
                                                                                                                                        
                                                                                                                                        
                                                                      lllllll                                                           
                                                                      l:::::l                                                           
                                                                      l:::::l                                                           
                                                                      l:::::l                                                           
  aaaaaaaaaaaaayyyyyyy           yyyyyyyyyyyyyy           yyyyyyy      l::::l    mmmmmmm    mmmmmmm     aaaaaaaaaaaaa     ooooooooooo   
  a::::::::::::ay:::::y         y:::::y  y:::::y         y:::::y       l::::l  mm:::::::m  m:::::::mm   a::::::::::::a  oo:::::::::::oo 
  aaaaaaaaa:::::ay:::::y       y:::::y    y:::::y       y:::::y        l::::l m::::::::::mm::::::::::m  aaaaaaaaa:::::ao:::::::::::::::o
           a::::a y:::::y     y:::::y      y:::::y     y:::::y         l::::l m::::::::::::::::::::::m           a::::ao:::::ooooo:::::o
    aaaaaaa:::::a  y:::::y   y:::::y        y:::::y   y:::::y          l::::l m:::::mmm::::::mmm:::::m    aaaaaaa:::::ao::::o     o::::o
  aa::::::::::::a   y:::::y y:::::y          y:::::y y:::::y           l::::l m::::m   m::::m   m::::m  aa::::::::::::ao::::o     o::::o
 a::::aaaa::::::a    y:::::y:::::y            y:::::y:::::y            l::::l m::::m   m::::m   m::::m a::::aaaa::::::ao::::o     o::::o
a::::a    a:::::a     y:::::::::y              y:::::::::y             l::::l m::::m   m::::m   m::::ma::::a    a:::::ao::::o     o::::o
a::::a    a:::::a      y:::::::y                y:::::::y             l::::::lm::::m   m::::m   m::::ma::::a    a:::::ao:::::ooooo:::::o
a:::::aaaa::::::a       y:::::y                  y:::::y              l::::::lm::::m   m::::m   m::::ma:::::aaaa::::::ao:::::::::::::::o
 a::::::::::aa:::a     y:::::y                  y:::::y               l::::::lm::::m   m::::m   m::::m a::::::::::aa:::aoo:::::::::::oo 
  aaaaaaaaaa  aaaa    y:::::y                  y:::::y                llllllllmmmmmm   mmmmmm   mmmmmm  aaaaaaaaaa  aaaa  ooooooooooo   
                     y:::::y                  y:::::y                                                                                   
                    y:::::y                  y:::::y                                                                                    
                   y:::::y                  y:::::y                                                                                     
                  y:::::y                  y:::::y                                                                                      
                 yyyyyyy                  yyyyyyy                                                                                       
                                                                                                                                        
                                                                                                                                        
```

**Comment by RemieRichards** [comment]
omfg.

**Comment by TheVekter** [comment]
Lmao "FUCK"

**Comment by Mandurrrh** [comment]
Awww

**Pull request closed without merging**
