### PR TITLE
Makes the detective's flask more noir-noire-noided

### PR DESCRIPTION
**Pull request by Repukan**
Changes detective contents from hearty punch to a more appropriately noire drink

:cl: Repukan
add: Whiskey to the flask
del: Hearty Punch from the flask
/:cl:

This could make you drunk enough to console you from the nerf it is.

### CODE REVIEW

**Comment by juanototo2** [comment]
Repukan nerfing his own role? It's the end times

**Comment by Repukan** [comment]
Who's gonna tell him, I don't have the heart

**Comment by Xhuis** [comment]
It was like this originally, I'm not sure who put hearty punch in it. That change was the thing that caused all of HP's balance issues to begin with because it was balanced around being numbingly difficult to make in high amounts.

**Comment by Repukan** [comment]
Same

**Comment by ExcessiveUseOfCobblestone** [comment]
HP was still dumb, just no one used it except a few people (myself included).

should have banned people who brought it up hehe secrits

**Comment by Repukan** [comment]
Can't ban me anymore bucko

**Comment by Cyberboss** [comment]
Excuse me?

untitled

**Comment by Repukan** [comment]
Haha what a story Mark

**Comment by BeeSting12** [comment]
mfw constantly punching the captain while in space and hes taken eight stetchkin bullets and he still keeps getting up

**Comment by ExcessiveUseOfCobblestone** [comment]
only sissies don't post the ban reason operative

**Comment by Iamgoofball** [comment]
Who put hearty punch in the fucking flask

**Comment by ShizCalev** [comment]
@Iamgoofball #28178

**Pull request merged**
