### PR TITLE
I do the dirty controversial work so nobody else gets the hate (#truth)

### PR DESCRIPTION
**Pull request by Bawhoppen**
:cl:
tweak: Officers now spawn with HUDsunglasses on.
tweak: Sec lockers no longer have HUDsunglasses but now have basic security HUDs.
add: Robos now spawn with diaghuds.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
All this stuff looks great to me.

**Comment by KorPhaeron** [comment]
Too much of a sec buff sorry

Doubling the number of huds they get is actually a huge deal when you are building a militia in rev or gang

**Comment by GunHog** [comment]
Geez, Kor, why not at least give him the chance to change it?

**Comment by Bawhoppen** [comment]
I thought people would get more mad if I didn't give them the HUDs in the lockers

**Comment by AnonymousNow** [comment]
I wouldn't be adverse to having HUD roles starting with their HUDs.

**Comment by ike709** [comment]
I... I actually like this PR...

**Pull request closed without merging**
