### PR TITLE
Fix broken mech delay

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

This seems to have been supposed to be a delay for god knows what reason
I assume it was supposed to slow you down or something but its not needed or useful and currently breaks changes your speed 

## Changelog
:cl:
fix: patched mechs being slow randomly after phasing
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
https://github.com/tgstation/tgstation/issues/59932
is this fixed?

**Comment by TiviPlus** [comment]
Yes and no it fixes the issue but does not fix the cause, insofar that phasing will bump() glass for some unknown reason

**Comment by Fikou** [comment]
> Yes and no it fixes the issue but does not fix the cause, insofar that phasing will bump() glass for some unknown reason

its because of connect loc stuff with border objects

**Comment by TiviPlus** [comment]
idk i didnt debug bumpcode fully

**Pull request merged**
