### PR TITLE
Fixed typo in suit.dmi

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
hardsquit-inq changed to hardsuit-inq

### CODE REVIEW

**Comment by PKPenguin321** [comment]
just fuck my squit up fam

**Comment by GunHog** [comment]
_testing_

**Comment by KorPhaeron** [comment]
never ever

**Comment by phil235** [comment]
will conflict with #15504

**Comment by KorPhaeron** [comment]
@phil235 could you add mine to yours please if it isnt too much hassle? Or I can just redo it after

**Comment by phil235** [comment]
will do

**Comment by KorPhaeron** [comment]
Thank you

**Pull request closed without merging**
