### PR TITLE
Fixes ORM alloy material consumption

### LINKED ISSUE #28155: The ORM doesn't actually properly use plasma and iron when making plasteel
Instead of using one iron and one plasma for one plasteel, it uses 0.5 iron and 0.5 plasma for one plasteel. Since it can accept plasteel again, this means infinite plasteel.

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: QualityVan
fix: The ORM now uses the intended amount of resources when making alloys
/:cl:

Fixes #28155

### CODE REVIEW

**Comment by Expletive** [comment]
Would it not be preferable to make the amount of material in plasteel sheets match the recipe, rather than vice versa?

**Comment by DoctoreMad** [comment]
**RUSH MERGE**

**Comment by ChangelingRain** [comment]
plasteel used to always use 1 of each sheet, though

**Comment by Profakos** [comment]
Entirely my fault for making assumptions about how many minerals is in a plasteel sheet. Sorry.

**Pull request merged**
