### PR TITLE
Pride Ruin Remap

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
Honestly this one was pretty fine. I just made it smaller, got rid of the 3x5 block of diamond walls, and added some nice cosmetic loot
- hair dye
- chameleon jumpsuit (no armor, totally ok with removing this if maintainers dislike it)
- lavalandified. begone diamond-and-silver blight

one2

## Why It's Good For The Game

Smaller ruin, less grating on the eyes with the massive hall of silver floors, remains consistent with theming

## Changelog

:cl:
add: Remapped the Pride's Mirror ruin
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
I feel like purple carpets might look nicer than the red ones

**Comment by TheBonded** [comment]
post lavalandification this just looks like a better envy ruin now

**Comment by Cheshify** [comment]
> post lavalandification this just looks like a better envy ruin now

I agreed, how's post lavalandification part 2?

**Comment by TheBonded** [comment]
> > post lavalandification this just looks like a better envy ruin now
> 
> I agreed, how's post lavalandification part 2?

7 days late sorry, looks still very similar to the envy ruin since its got the cult walls and cooler floors

**Pull request merged**
