### PR TITLE
Icebox Security Remap Part 1: The Preparation

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

Icebox's Mining Area used to be a Copy-Paste of the Lavaland Labour Camp. While this immediately solved the short-term issue of Icebox not having a labour camp at the time, it ultimately fails to take advantage of icebox's unique opportunities. 

This change relocates the Labour Camp to under the Prison, and redoes a significant portion of the Icebox Terrain on Z-2. 
This change also removes the remaining traces of the Lavaland Mining Base from Icebox. Gulag is all that remains, but not for long.

This is a 2 parter PR.

## Why It's Good For The Game

Icebox Benefits from having more interesting mapped Terrain in the form of Openspace Canyons. 

TheGreatIceboxEarthquake!

Security has the unique opportunity here to connect straight to Gulag. If a shuttle must be used, it should be a Tram. However, a shuttle should not transport prisoners short distances across the same map. It's a waste of the system. In the upcoming part 2 of this, expect a full security rework, giving Gulag 3-Z's of mining space, and providing Security Players with some Icebox-Unique gameplay features. Please look forwards to it!

ThatsANeatoPlasmemeLake

Same Gulag New Closet

## Changelog

:cl:
expansion: Condition Orange! Severe Seismic Activity Detected! New Gulag Position Registered!
del: The remnants of the Old Mining Base are gone. We've always had the crater observatory. 
qol: New Icebox Terrain
/:cl:

### CODE REVIEW

**Review by Maurukas — CHANGES_REQUESTED** [review]
Sorry this took so long to review. Every time I check out this PR something seems to come up.

Big pile of Active Turfs in the replacement left side of the mining base. Not sure of the origin, it's not getting out from above:
image


Air tank needs a dir var set to connect to the pump:
image

**Comment by LemonInTheDark** [comment]
I'm willing to bet at least some of them are getting out from above. should check their initial gas mix

**Comment by Maurukas** [comment]
It genned snowturfs on the z-above when I tested locally, so I don't think it's getting out upwards. I agree, this is probably some initial gas mix nonsense.

**Comment by Maurukas** [comment]
Think this might've gotten introduced - 6 tiles in the wrong area here on the chasm in Icemoon Above causing genturf fails and active turfs:
image

**Pull request merged**
