### PR TITLE
Adds a second boom wire to payload bombs.

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request

Adds a second detonation wire onto payload bombs, bringing the total number of wires to 6.

## Why It's Good For The Game

As it stands, there are two wires capable of neutralizing the bomb in most circumstances and one detonation wire. Unbolting a bomb from the floor and spacing it is as effective a solution to a bomb as defusing it until the explosion is imminent (You can tell by the lack of defusals which are performed once the bomb can be moved). Even unbolting it with 10 seconds to spare gives the crew a great deal of control over where the explosion occurs. This itself isn't an issue because shoving a bomb out into space and hearing it explode off screen is pretty badass.
The issue is that with 2 wires capable of more or less defusing the bomb and 1 which causes the explosion, you have a 2/3 chance to save the day while blindly cutting wires. A second wire brings these odds to a thrilling 50/50!
The proceed wire used to detonate the bomb when cut but will now disable the examinable countdown timer, leaving only the beeping to indicate how close the bomb is to exploding. This is reset once the defusal wire is cut.

## Changelog

:cl:
balance: There's a second detonation wire on payload bombs now.
balance: Cutting the proceed wire no longer detonates the bomb but instead deactivates the countdown timer on examine. This is reset once the bomb is defused
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Very fair reasoning, and after the bomb core nerf there should be a good buff towards syndie bomb being used as intended

**Comment by VladinXXV** [comment]
The odds are already at a "thrilling 50/50" when cutting wires, which I feel is good enough. Few people bother trying to defuse as is. Your odds are better if you're using a multitool, yes, but you're still looking at a 20% chance of instant death and a 20% chance of death in a few seconds (depends on timer). 
image

This is just how I see it.

**Comment by Capsandi** [comment]
Yea I'm changing the proceed wire to something else when cut, just forgot how to draft an open pr again.

**Comment by SomeoneYouProbablyKnow** [comment]
> The odds are already at a "thrilling 50/50" when cutting wires, which I feel is good enough. Few people bother trying to defuse as is. Your odds are better if you're using a multitool, yes, but you're still looking at a 20%

Everyone who has wirecutters has a multitool. So it's basically always 20%

**Comment by VladinXXV** [comment]
> > The odds are already at a "thrilling 50/50" when cutting wires, which I feel is good enough. Few people bother trying to defuse as is. Your odds are better if you're using a multitool, yes, but you're still looking at a 20%
> 
> Everyone who has wirecutters has a multitool. So it's basically always 20%

This simply is not true.

**Comment by improvedname** [comment]
normally i'd agree but i don't think this is needed since you can already rig the bomb yourself to explode instantly

**Comment by SomeoneYouProbablyKnow** [comment]
> > Everyone who has wirecutters has a multitool. So it's basically always 20%
> 
> This simply is not true.

In my experience it is but even then if you want to leave wirecutter odds at 50 and bump up multitool odds you mess with multitool functionality, make it less useful in defusal. 

Why does carrying one small item you can print at lathes, an item you already want to have gives you a 30% increase in defusal odds.

**Comment by improvedname** [comment]
bombs do not need an extra wire if somoene got a multitooo thats good on them let them have the 30% defusal chance, if you really wanted the bomb to explode so badly you'd rig it yourself and attach a signaller to the explosion wire bombs should be easy to defuse when prepared for it and not harder this discourages trying to defuse the bomb in the first place especially for engineers cause they have to fix the breach.

**Pull request merged**
