### PR TITLE
Couple donut fixes

### LINKED ISSUE #46595: donut station floor apc
https://monosnap.com/file/RBZFMEDHeFmzs8vlR1ysyICDOKcMsp

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
fixes  #46595

## Why It's Good For The Game
bug fix

## Changelog
:cl: Skoglol
fix: Donut floor apc put back on wall. Vault door now has a floor.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
can u fix the hole in the floor below the vault doors too

**Comment by kriskog** [comment]
Sure, why not

**Comment by Tharcoonvagh** [comment]
delet donut

**Comment by Ty-the-Smonk** [comment]
Singulonut

**Comment by Fhaxaris** [comment]
The absent floors that
are under vault doors are the
core of this station.

**Pull request merged**
