### PR TITLE
Syndicate Shuttle Console cannot be deconstructed via tools

### PR DESCRIPTION
**Pull request by bloons3**
## About The Pull Request

reference https://github.com/tgstation/tgstation/issues/56577#issuecomment-771414614

Doesn't fix the rest of the borg stuff

## Changelog
:cl:
fix: The already indestructible Syndicate Shuttle Terminal now cannot be deconstructed with tools
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Putting "Fixes" like that will cause the issue to be autoclosed if the pr is merged, which I don't think is applicable

**Comment by Fikou** [comment]
dont say the pr fixes an issue if the issue will still be a thing

**Comment by bloons3** [comment]
> Putting "Fixes" like that will cause the issue to be autoclosed if the pr is merged, which I don't think is applicable



> dont say the pr fixes an issue if the issue will still be a thing

Fixed

**Comment by LemonInTheDark** [comment]
:)

**Comment by Fikou** [comment]
:)

**Comment by Colovorat** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by YakumoChen** [comment]
Make it require a thin tip screwdriver like the nuke instead.

**Pull request merged**
