### PR TITLE
SABR Bug Fix

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR fixes a bug with the SABR gun not showing properly.

### CODE REVIEW

**Comment by Shapsy** [comment]
30 is still really really high considering they're tiny and you can stuff 10 in your bag no problem

**Comment by GunHog** [comment]
30 is fine, hate that he shoves it with a bugfix though.

**Comment by Steelpoint** [comment]
I'm not littering this up with 20 PR's to fix the same thing where if one gets merged the other conflicts.

**Comment by PKPenguin321** [comment]
you can't really litter PRs since we have literally infinite slots for PRs

**Comment by Lumipharon** [comment]
Just put it back to fucking 20 shots.

There was no reason to buff what is already an extremely powerful weapon.

**Comment by GunHog** [comment]
This is why you do not combine nerfs and bugfixes, Steelpoint. People argue over the changes, holding up the fix. Right now, the guns are invisible except for a little pixel strip. This is a reminder that earmarking things to fix PR is bad form, and should be disallowed for this reason.

That being said, just merge this one already so I can find my gun when I drop it!

**Comment by Steelpoint** [comment]
I pushed a update so this PR only has the bug fix.

Let me just fix the merge conflict.

**Comment by Steelpoint** [comment]
That should do it, I'll leave any further SABR changes until AFTER the auto rifle poll is finished tomorrow.

**Comment by Steelpoint** [comment]
Thanks.

**Pull request merged**
