### PR TITLE
I might HAVE accidently made dualwielding hilariously OP again so have a nerf!

### PR DESCRIPTION
**Pull request by silicons**
WOOPS

NUMBERS UP TO DEBATE!

### CODE REVIEW

**Comment by dannno** [comment]
MIGHT, HAVE.

HAVE.
NOT OF.

HAVE.

**Comment by dannno** [comment]
HAVE.

**Comment by dannno** [comment]
YOU MIGHT HAVE ACCIDENTALLY MADE DUAL WIELDING HILARIOUSLY OP.

**Comment by dannno** [comment]
HAVE, KEVIN

**Comment by kevinz000** [comment]
FUCK

**Comment by dannno** [comment]
North Korea seriously needs to get up to par with their English classes

**Comment by kevinz000** [comment]
=|

**Comment by Repukan** [comment]
150 HOURS

**Comment by DoctoreMad** [comment]
Wow, this Kevinz000 guy is always getting some bugs in his PRs. That's way too much trouble for the maintainers to keep checking! What if we just grabbed kevinz000 PRs and put them on the bottom of the maintainer priority list so they could get other PRs merged before his?

**Comment by kevinz000** [comment]
@DoctoreMad lol who are you again?

**Comment by WJohn** [comment]
They do feel a tad powerful in game. A slight nerf would be good, some of them do miss target already at long range (maybe only 20% of the time). Raising that to 40% or 50% would be better. I think it'd be best if it can be used well in close range but not much outside of that.

**Comment by kevinz000** [comment]
@WJohn hopefully this will be enough if it isn't I could add a system to have a minimum spread instead of just maximum and minimum of 0.

**Comment by Tacolizard** [comment]
how about this: 2 guns = the power of having 2 guns

why is using two guns at once without nerfs op.

**Comment by Repukan** [comment]
Are you fucking retarded

**Comment by Tacolizard** [comment]
you tell me

**Comment by dannno** [comment]
Yes

**Comment by Iamgoofball** [comment]
oh no @kevinz000 deployed the "literally who" argument which somehow makes all valid criticism irrelevant

**Pull request merged**
