### PR TITLE
Revert "Refactors riding to a datum and applies it to vehicles, allowing for mobs to be ridden."

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#22420

\>4gb runtime logs

Please.

@Militaires 

I have other runtimes i'm trying to track down and i can't even open the runtime file because it's so fucking big.

````
runtime error:
[22:51:28]Cannot execute null.handle vehicle layer().
[22:51:28]proc name: Move (/mob/living/simple_animal/Move)
[22:51:28]  source file: simple_animal.dm,550
[22:51:28]  usr: null
[22:51:28]  src: the bee (/mob/living/simple_animal/hostile/poison/bees)
[22:51:28]  src.loc: the grass patch (167,117,6) (/turf/open/floor/grass)
[22:51:28]  call stack:
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Move(the grass patch (167,117,6) (/turf/open/floor/grass), 2, 0, 0)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): handle automated movement()
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]Mobs (/datum/subsystem/mobs): fire(1)
[22:51:28]Master (/datum/controller/master): RunQueue()
[22:51:28]Master (/datum/controller/master): Loop()
[22:51:28]Master (/datum/controller/master): StartProcessing()
runtime error:
[22:51:28]Cannot execute null.handle vehicle layer().
[22:51:28]proc name: Move (/mob/living/simple_animal/Move)
[22:51:28]  source file: simple_animal.dm,550
[22:51:28]  usr: null
[22:51:28]  src: the bee (/mob/living/simple_animal/hostile/poison/bees)
[22:51:28]  src.loc: the grass patch (165,118,6) (/turf/open/floor/grass)
[22:51:28]  call stack:
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Move(the grass patch (165,118,6) (/turf/open/floor/grass), 1, 0, 0)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): handle automated movement()
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]Mobs (/datum/subsystem/mobs): fire(1)
[22:51:28]Master (/datum/controller/master): RunQueue()
[22:51:28]Master (/datum/controller/master): Loop()
[22:51:28]Master (/datum/controller/master): StartProcessing()
runtime error:
[22:51:28]Cannot execute null.handle vehicle layer().
[22:51:28]proc name: Move (/mob/living/simple_animal/Move)
[22:51:28]  source file: simple_animal.dm,550
[22:51:28]  usr: null
[22:51:28]  src: the bee (/mob/living/simple_animal/hostile/poison/bees)
[22:51:28]  src.loc: the grass patch (165,116,6) (/turf/open/floor/grass)
[22:51:28]  call stack:
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Move(the grass patch (165,116,6) (/turf/open/floor/grass), 4, 0, 0)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): handle automated movement()
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]Mobs (/datum/subsystem/mobs): fire(1)
[22:51:28]Master (/datum/controller/master): RunQueue()
[22:51:28]Master (/datum/controller/master): Loop()
[22:51:28]Master (/datum/controller/master): StartProcessing()
runtime error:
[22:51:28]Cannot execute null.handle vehicle layer().
[22:51:28]proc name: Move (/mob/living/simple_animal/Move)
[22:51:28]  source file: simple_animal.dm,550
[22:51:28]  usr: null
[22:51:28]  src: the bee (/mob/living/simple_animal/hostile/poison/bees)
[22:51:28]  src.loc: the grass patch (165,118,6) (/turf/open/floor/grass)
[22:51:28]  call stack:
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Move(the grass patch (165,118,6) (/turf/open/floor/grass), 2, 0, 0)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): handle automated movement()
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]Mobs (/datum/subsystem/mobs): fire(1)
[22:51:28]Master (/datum/controller/master): RunQueue()
[22:51:28]Master (/datum/controller/master): Loop()
[22:51:28]Master (/datum/controller/master): StartProcessing()
runtime error:
[22:51:28]Cannot execute null.handle vehicle layer().
[22:51:28]proc name: Move (/mob/living/simple_animal/Move)
[22:51:28]  source file: simple_animal.dm,550
[22:51:28]  usr: null
[22:51:28]  src: the bee (/mob/living/simple_animal/hostile/poison/bees)
[22:51:28]  src.loc: the grass patch (164,117,6) (/turf/open/floor/grass)
[22:51:28]  call stack:
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Move(the grass patch (164,117,6) (/turf/open/floor/grass), 8, 0, 0)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): handle automated movement()
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]the bee (/mob/living/simple_animal/hostile/poison/bees): Life(2)
[22:51:28]Mobs (/datum/subsystem/mobs): fire(1)
[22:51:28]Master (/datum/controller/master): RunQueue()
[22:51:28]Master (/datum/controller/master): Loop()
[22:51:28]Master (/datum/controller/master): StartProcessing()
runtime error:
[22:51:28]Cannot execute null.handle vehicle layer().
[22:51:28]proc name: Move (/mob/living/simple_animal/Move)
[22:51:28]  source file: simple_animal.dm,550
[22:51:28]  usr: null
[22:51:28]  src: the ash drake (/mob/living/simple_animal/hostile/megafauna/dragon)
[22:51:28]  src.loc: the volcanic floor (143,178,5) (/turf/open/floor/plating/asteroid/basalt/lava_land_surface)
[22:51:28]  call stack:
[22:51:28]the ash drake (/mob/living/simple_animal/hostile/megafauna/dragon): Move(the volcanic floor (143,178,5) (/turf/open/floor/plating/asteroid/basalt/lava_land_surface), 4, 0, 0)
[22:51:28]the ash drake (/mob/living/simple_animal/hostile/megafauna/dragon): Move(the volcanic floor (143,178,5) (/turf/open/floor/plating/asteroid/basalt/lava_land_surface), 4)
[22:51:28]the ash drake (/mob/living/simple_animal/hostile/megafauna/dragon): handle automated movement()
[22:51:28]the ash drake (/mob/living/simple_animal/hostile/megafauna/dragon): Life(2)
[22:51:28]the ash drake (/mob/living/simple_animal/hostile/megafauna/dragon): Life(2)
[22:51:28]Mobs (/datum/subsystem/mobs): fire(1)
[22:51:28]Master (/datum/controller/master): RunQueue()
[22:51:28]Master (/datum/controller/master): Loop()
[22:51:28]Master (/datum/controller/master): StartProcessing()
runtime error:
[22:51:28]Cannot execute null.handle vehicle layer().
[22:51:28]proc name: Move (/mob/living/simple_animal/Move)
[22:51:28]  source file: simple_animal.dm,550
[22:51:28]  usr: (src)
[22:51:28]  src: Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky)
[22:51:28]  src.loc: the floor (121,141,1) (/turf/open/floor/plasteel)
[22:51:28]  call stack:
[22:51:28]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): Move(the floor (121,141,1) (/turf/open/floor/plasteel), 8, 0, 0)
[22:51:28]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): bot step(the floor (114,141,1) (/turf/open/floor/plasteel))
[22:51:28]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): bot move(the floor (114,141,1) (/turf/open/floor/plasteel), null)
runtime error:
[22:51:28]Cannot execute null.handle vehicle layer().
[22:51:28]proc name: Move (/mob/living/simple_animal/Move)
[22:51:28]  source file: simple_animal.dm,550
[22:51:28]  usr: (src)
[22:51:28]  src: Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky)
[22:51:28]  src.loc: the floor (120,141,1) (/turf/open/floor/plasteel)
[22:51:28]  call stack:
[22:51:28]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): Move(the floor (120,141,1) (/turf/open/floor/plasteel), 8, 0, 0)
[22:51:28]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): bot step(the floor (114,141,1) (/turf/open/floor/plasteel))
[22:51:28]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): bot move(the floor (114,141,1) (/turf/open/floor/plasteel), null)
runtime error:
[22:51:29]Cannot execute null.handle vehicle layer().
[22:51:29]proc name: Move (/mob/living/simple_animal/Move)
[22:51:29]  source file: simple_animal.dm,550
[22:51:29]  usr: (src)
[22:51:29]  src: Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky)
[22:51:29]  src.loc: the floor (119,141,1) (/turf/open/floor/plasteel)
[22:51:29]  call stack:
[22:51:29]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): Move(the floor (119,141,1) (/turf/open/floor/plasteel), 8, 0, 0)
[22:51:29]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): bot step(the floor (114,141,1) (/turf/open/floor/plasteel))
[22:51:29]Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky): bot move(the floor (114,141,1) (/turf/open/floor/plasteel), null)
````

### CODE REVIEW

**Comment by kevinz000** [comment]
good job bagilman :^)
not testing your code :^)

**Comment by MrStonedOne** [comment]
\>runtimes are happening so quickly its actually lagging byond from having to write them to disk

**Comment by RemieRichards** [comment]
refer to "this is a mess"

**Comment by MrStonedOne** [comment]
Ya, nothing checks to make sure ridingdatum isn't null, but nothing actually ensures it's ever set.

This is something that would have came out if @Militaires had tested non-ridable mobs moving, as it would have runtimed then.

**Comment by Militaires** [comment]
My code is as **solid** as **_steel_** and **impossible** to break.

but fuck, sorry.

@MrStonedOne cant it be fixed by checking if it's not null, instead of revertin the whole thing

**Comment by MrStonedOne** [comment]
Thats for you to do, I made this pr mainly so i could test merge it to undo your code before my log files got any bigger.

**Comment by Militaires** [comment]
i have a pr up by now 

thanks for letting me know in any case

**Pull request closed without merging**
