### PR TITLE
[Cere] Typos + other fixes

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes 
https://github.com/tgstation/tgstation/issues/27404
https://github.com/tgstation/tgstation/issues/27411
https://github.com/tgstation/tgstation/issues/27413

### CODE REVIEW

**Comment by ShizCalev** [comment]
Last commit is a bigger one. All of the maintenance areas in the upper half of the station were one massive area, and there were about 8 APC's spread throughout them. Broke them up into their own areas so they don't all run off one APC and rape it mercilessly.

Also increased the starting power of the Northern APC to 80%. It was at 50% before which gave the station roughly around 15~16 minutes to get the power on before the entire command / security / North asteroid lost power completely. It's should be closer to 30 minutes or so now.

**Comment by Bawhoppen** [comment]
this doesn't fix #27411 because that's supposed to be a broader issue report for the tons of minor issue that don't warrant their own reports

**Comment by Cyberboss** [comment]
@Bawhoppen That's not how we do issues

**Comment by Bawhoppen** [comment]
nobody is going to spend the effort to make a full issue report for a super minor thing, but those minor things add up

**Comment by ShizCalev** [comment]
Noticed more powernet issues with the hallways. Will fix later tonight.

**Comment by Penguaro** [comment]
@ShizCalev You need to put 'fixes' in front of each issue number in order to autoclose them, otherwise you're just referencing them.

**Comment by Penguaro** [comment]
I would add that an alternative that I find works (though why I don't do it always with my TG stuff is beyond me) is to start the commit comment with fixes #issue -message so that it's built in since the commit message will also auto-close the issue.

**Comment by lzimann** [comment]
Also yes, please put `Fixes #issue_number` in the op so it auto closes the issues. I missed this one.

**Pull request merged**
