### PR TITLE
Tile Remover DLC

### PR DESCRIPTION
**Pull request by Comxy**
## About The Pull Request
Details:
This pr adds a new wrench that can wrench floor plating out of the ground. The wrench is very big and makes you slow. The wrench can be acquired from the tile remover cabinet. You can find it in engineering only areas. Removing the plating will drop the tile on the ground and will leave you with the lattice. For more details see the code.
## Why It's Good For The Game
Adds a RCD alternative that doesn't use up full matter cartridges just to remove a single tile. The wrench makes you slow so it should be balanced. More giant tools are cool. This way people can build cool things in the station or with the byos without having the use countless amounts of RCDs.
promo
## Changelog
:cl:
add: Adds a new tile remover which removes floor plating.
imageadd: Adds tile remover sprites along with a cabinet for it.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
I already dislike the RCD's ability to make breaches wherever it wants by just drilling a hole into the floor, can you explain why we want it to be more common?

**Comment by dragomagol** [comment]
Please don't make this a wall mount, we're trying to clear up wall space.

**Comment by Comxy** [comment]
> I already dislike the RCD's ability to make breaches wherever it wants by just drilling a hole into the floor, can you explain why we want it to be more common?

That is something people could do I suppose

**Comment by Comxy** [comment]
> Please don't make this a wall mount, we're trying to clear up wall space.

I don't see a good way to add it outside of a wall mount.

**Comment by NamelessFairy** [comment]
If this is going to work on reinforced plating make sure that it calls the screw dropping proc.

**Comment by JohnFulpWillard** [comment]
> That is something people could do I suppose

What does this mean? My comment was "we dont like the already-existing ability to do it, why do you want to make more items do the thing"

**Comment by necromanceranne** [comment]
You say 'create breaches' like as though there isn't sometimes a need to remove plating for actual practical reasons. The only alternative to RCDs is high explosives, Willard.

**Comment by Comxy** [comment]
> If this is going to work on reinforced plating make sure that it calls the screw dropping proc. Edit: I'd personally prefer if it didn't work on r-plates however

It made it still works but slower on r-plates

**Comment by optimumtact** [comment]
image
bro what is this

**Comment by Comxy** [comment]
> What does this mean? My comment was "we dont like the already-existing ability to do it, why do you want to make more items do the thing"

The reason I created this is, I have found myself wanting to remove tiles in the past for projects in the game, but to use it on a larger scale I have always had to transport countless RCDs to create a larger space area to the byos through pods, and it is hardly accessible. This tool seeks to make it easier for players to destroy tiles for it to be used for fun projects mainly. But you are right in the fact people could very well use this to create space holes for no reason. However people can do that through other means either way like using a fireaxe to break all windows around the station for example. I thought the best way to make sure people cannot grief with it a whole lot is making someone who is holding a tile remover very slow.

**Comment by Comxy** [comment]
> bro what is this

Its supposed to be a giant shovel wrench that can suck up tiles

**Comment by optimumtact** [comment]
it looks like a wire roll with a spiky end

**Comment by JohnFulpWillard** [comment]
Using fireaxes to break windows is the intent of the fireaxe as atmospherics equipment, I don't understand what projects requires you to drill holes into the station though?

Up until now the only time I've seen the feature used has been to space supermatters to stop delams, and https://github.com/tgstation/tgstation/pull/53725 was made to counter that (I don't know if it actually helped though, I still see it done sometimes).

**Comment by zxaber** [comment]
For what it's worth, I use strategic breaching to combat plasma fires. Though you usually only need a few.

**Comment by EuclidianGeometer** [comment]
I've seen people do it for some little construction projects. Someone made a space chapel with catwalks on the last round I was in.

**Comment by calliophis-maculiceps** [comment]
22 hours before this gets closed

**Comment by necromanceranne** [comment]
> Using fireaxes to break windows is the intent of the fireaxe as atmospherics equipment, I don't understand what projects requires you to drill holes into the station though?

The installation of space windows and altered shapes for rooms. Just general station rearranging. Like, say we take that wall island in Meta. Maybe I want it to be open to space with some windows around it instead. I feel like this is an alteration we shouldn't keep out of the hands of players even if the immediate need for these alterations have no obvious direct practical value.

This is maybe more valuable the further we utilize multi-z as well, and I can think of one actually. If we have someone put down plating in front of the tram, for instance, we would want to let engineers fix that before it becomes a health hazard, because that makes getting hit by the tram more dangerous.

**Comment by Comxy** [comment]
> Using fireaxes to break windows is the intent of the fireaxe as atmospherics equipment, I don't understand what projects requires you to drill holes into the station though?

To create cool space areas with glass tiling and a nice lounge. It is a sandbox game after all so it creates more options for building stuff.

> Up until now the only time I've seen the feature used has been to space supermatters to stop delams, and #53725 was made to counter that (I don't know if it actually helped though, I still see it done sometimes).

I see, it can be used for more though.

> You also put the wrench in Engineering storage room, the place Atmos techs don't have access to, despite spacing a room being directly related to Atmos.

If atmos techs want to use this item they can go roleplay their way to ask an engineer to get it, which would add great role play potential for the few instances someone would ask for it. It is intended to be a building tool hence the engineers got it.

**Comment by dalmationer** [comment]
I think if you hit something with this thing it should make this noise https://youtu.be/066yvq6vRUw?t=7

**Comment by Serxule** [comment]
> > Using fireaxes to break windows is the intent of the fireaxe as atmospherics equipment, I don't understand what projects requires you to drill holes into the station though?
> 
> To create cool space areas with glass tiling and a nice lounge. It is a sandbox game after all so it creates more options for building stuff.

glass tiles dont need plating removed to place them, just floor tiles like every other tile in the game

**Comment by optimumtact** [comment]
also, if the fireax was supposed to be for fires why not just let it pry up tiles lol

**Comment by OrionTheFox** [comment]
> image bro what is this

Just a tilefull
image

**Comment by moocowswag** [comment]
the inhand sprite looks okay but the on floor sprite is funny. 


Yes we do need more ways to pry up floor tiles and this one is as healthy for the game as possible...

**Comment by Serxule** [comment]
to talk about the sprites: the cabinet sprites look like an oversized spatula (or an aquarium with glass), the in-hand sprites look like a fryer basket, and the ground sprites look like an among us vent with a bent rod attached. also i want to ask something

>This way people can build cool things in the station or with the byos without having the use countless amounts of RCDs.

you do realize RCDs can be refilled with virtually any building material, and arent a one use item, right? you only need a single RCD for the entire round

**Comment by Comxy** [comment]
Guess I'll try to split up this PR in the future since people don't seem to like one.

I do want to say though, that this tool being able to make breaches is not a bad thing and people probably won't do it, just like not everyround all antags are trying to plasmaflood the station, I think it is a bad one sighted argument. Just because it has grief potential doesn't mean every single antag is trying to smash every window open with a fireaxe every round.

**Comment by Comxy** [comment]
> fun fact: its usually non-antags who smash all the windows, antags doing it will get themselves fucked by sec

If you think so, I am not here to argue with you

**Comment by Farquaar** [comment]
>>Like, say we take that wall island in Meta's departures. Maybe I want it to be open to space with some windows around it instead. I feel like this is an alteration we shouldn't keep out of the hands of players even if the immediate need for these alterations have no obvious direct practical value.

As someone who loves renovating departments and doing construction projects as non-engineers, I think that if you're going to be drilling a hole into departures you should probably have engineering equipment like an RCD.

**Comment by Pickle-Coding** [comment]
> >Like, say we take that wall island in Meta's departures. Maybe I want it to be open to space with some windows around it instead. I feel like this is an alteration we shouldn't keep out of the hands of players even if the immediate need for these alterations have no obvious direct practical value.
> 
> 
> 
> As someone who loves renovating departments and doing construction projects as non-engineers, I think that if you're going to be drilling a hole into departures you should probably have engineering equipment like an RCD.

Deconstructing plating is 11 times more expensive than constructing it via RCD, which is probably why people don't like using it.

**Pull request closed without merging**
