### PR TITLE
Cleans up mood_events from deciseconds into MINUTES and SECONDS

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request
We have defines for times to save us from the horrid decisecond. Inspired by the singular use of defines for the "clean laundry" moodlet I have converted all other mood_event timeouts from deciseconds to appropriate MINUTES and SECONDS.

## Why It's Good For The Game
It hurts to look at raw time outputs. Code is now a little less maddening to look at.

## Changelog
:cl:
refactor: mood_event timeouts are now in MINUTES and SECONDS
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I don't really trust those defines tbh

**Comment by RaveRadbury** [comment]
These defines from time.dm?

`#define SECONDS *10

#define MINUTES SECONDS*60

#define HOURS MINUTES*60`

**Comment by Tlaltecuhtli** [comment]
why not define minutes 600

**Comment by ExcessiveUseOfCobblestone** [comment]
These should be fine assuming add_timer is based on true time, unlike say `life` iterations.

> why not define minutes 600

just how they decided to format it, it doesn't make any difference in the end.

**Comment by Militaires** [comment]
shrinking the second value to accelerate time ingame when

**Comment by ExcessiveUseOfCobblestone** [comment]
> ingame

>> not shrinking the second define to make time faster irl

**Comment by RaveRadbury** [comment]
All these defines to do condense values, they don't determine whether or not something is ``add_timer`` or ``life``

**Comment by Razharas** [comment]
Decimal systems are better than the retrograde decihexal measurements of time

**Comment by ExcessiveUseOfCobblestone** [comment]
> All these defines do is condense values, they don't determine whether or not something is `add_timer` or `life`

It's the same as setting something `TRUE` vs `1`, we don't want to call something `TRUE` if it's not a boo. Likewise, If it's not a true time (like something nested in life iterations), we don't want to say it's 60 seconds when it's not _actually_ 60 seconds.

add_timer I think is based on worldtime so it's ok.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
