### PR TITLE
[NO GBP] fixes spurious unit test fail for prosthetic limbs

### LINKED ISSUE #87663: Flaky hard delete: /obj/item/bodypart/arm/right
Flaky tests were detected in [this test run](https://github.com/tgstation/tgstation/actions/runs/11646496163/attempts/1). This means that there was a failure that was cleared when the tests were simply restarted.
Failures:
```
create_and_destroy: /obj/item/bodypart/arm/right hard deleted 1 times out of a total del count of 1692 at code/modules/unit_tests/create_and_destroy.dm:99
```

### LINKED ISSUE #87669: Flaky hard delete: /obj/item/bodypart/arm/left
Flaky tests were detected in [this test run](https://github.com/tgstation/tgstation/actions/runs/11649625087/attempts/1). This means that there was a failure that was cleared when the tests were simply restarted.
Failures:
```
create_and_destroy: /obj/item/bodypart/arm/left hard deleted 1 times out of a total del count of 1734 at code/modules/unit_tests/create_and_destroy.dm:99
```

### PR DESCRIPTION
**Pull request by Time-Green**
Yeah I really don't get why this happens. I went through it on local, and it goes
try delete human > delete quirks > delete the nullspaced original limb from proslimb > delete the rest of limbs
Still the unit test fails because it's getting qdelled twice? It doesn't qdel twice on local so idfk

This is caused by morgue bodies with proslimbs being spawned and deleted, so uh just stop morgue bodies from getting proslimbs. idk man its a bad fix but it'll get our unit tests running again

Fixes https://github.com/tgstation/tgstation/issues/87663
Fixes https://github.com/tgstation/tgstation/issues/87669

### CODE REVIEW

**Comment by Sealed101** [comment]
so #87484 and #87485?

**Comment by Time-Green** [comment]
> so #87484 and #87485?

Afraid not ☹️, this one was merged just this morning

**Comment by Sealed101** [comment]
#87663

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/issues/87669

**Comment by Time-Green** [comment]
> #87669

This is gonna keep growing huh

**Pull request merged**
