### PR TITLE
KEEP YOUR HOES IN LINE

### PR DESCRIPTION
**Pull request by Cheridan**
Hoe Identification Guide:

Hoe:
hoe-1

Not A Hoe:
hand-cultivator-sneeboer-img-155-w308-h308

### CODE REVIEW

**Comment by Aranclanos** [comment]
nice commit log

hoe

**Comment by Man-Shroom** [comment]
NIGGA DEY BOF HOES

**Comment by Cheridan** [comment]
@Man-Shroom Sometimes hoes don't think they're good enough so they get cultivator implants
31rwfjw5fql _sx300_
but that shit ain't natural. You just gotta be who you is.

**Comment by Aranclanos** [comment]
keeping it real

**Comment by Miauw62** [comment]
:tractor: :corn: :corn: :corn: :corn:

**Comment by SconesC** [comment]
Don't forget to update the wiki so that people aren't looking for hoes

**Comment by Chocobro** [comment]
i'm laughing a lot

**Pull request merged**
