### PR TITLE
adds bridge and supply directional signs

### PR DESCRIPTION
**Pull request by ghost**
Yep

### CODE REVIEW

**Comment by GunHog** [comment]
That should have been done with the first PR! :+1:

**Comment by TZK13** [comment]
:+1:

**Comment by Dorsisdwarf** [comment]
I thought we had cargo, not supply?

**Comment by Deantwo** [comment]
The TCOMM channel is called "Supply". But that channel include Bar, Kitchen and Hydroponics I think.

**Comment by GunHog** [comment]
You are thinking of the "Service" channel (Bartender, Chef, Botany, Janitor). "Supply" is Cargo and Mining. "Supply" is a better name than "Cargo" anyway, as "Cargo" implies freight. The department is a logistics center.

**Comment by Deantwo** [comment]
Ah sorry.

**Comment by paprka** [comment]
Cargo is a sub-department of supply. There are two sub-departments of supply, mining and cargo. They are both overseen by the quartermaster who is meant to make sure cargo techs don't order stupid shit but hey who's judging :alien:

**Comment by Dorsisdwarf** [comment]
Thanks for clearing the cargo/supply/etcetera thingy up.
That reminds me, GunHog.

It's hilarious as hell when people turn the auto-lengthener on MAGNI's scripts on and it replaces 'cargo' with 'logistics'. The entire crew goes up in arms until the AI turns it off again.

**Comment by GunHog** [comment]
HOOOOOOOOOOONK(); I am glad someone likes that :package:

**Pull request merged**
