### PR TITLE
GOOF'S HOT SPICY MEME OF THE DAY: Dabbing

### PR DESCRIPTION
**Pull request by Iamgoofball**
zu0et

:cl: here com DAT BOIIIIII
fix: Adds #dab to the game
experimental: YO CHECK MY TWITTER https://twitter.com/iamgoofball?lang=en
/:cl:

### CODE REVIEW

**Comment by BeeSting12** [comment]
kill yourself

**Comment by kevinz000** [comment]
you know what?
:+1: fuck it.

**Comment by Anonmare** [comment]
Rare goofPR collected! I can't wait to play it in Shitposters!

**Comment by BeeSting12** [comment]
YOU TOO KEVINZ? OH GOD WHAT IS THE WORLD COMING TO

**Comment by ShadowDeath6** [comment]
no no no no no no no no no no no no no no no no no no no no no no no no no no no
please no goof you're better than this

**Comment by Armhulen** [comment]
IS HE?

**Comment by Supermichael777** [comment]
make anyone too white fail

**Comment by optimumtact** [comment]
I like this

**Comment by KorPhaeron** [comment]
what did he mean by this

**Comment by lzimann** [comment]
i dont like this

**Comment by Bawhoppen** [comment]
S L I P P E R Y   S L O P E

**Comment by ExcessiveUseOfCobblestone** [comment]
you can honestly /me this already though.

**Comment by optimumtact** [comment]
can be replicated with the *me emote, closing this as it adds no special functionality worthy of existing.

**Comment by mattroks101** [comment]
>not making the text "does a sick as fuck dab"

**Comment by extramrdo** [comment]
But with this, you can handcuff people to stop them from dabbing.

**Comment by Iamgoofball** [comment]
^

**Comment by ShadowDeath6** [comment]
But even if you do cuff them they can still do me"dabs", can't they

**Comment by Anonmare** [comment]
If you cuff your enemies, they win

**Comment by optimumtact** [comment]
making dabbing while wearing a fedora cause a molotov explosion at your body

**Comment by ShadowDeath6** [comment]
Add a nukeop only fedora that maxcaps your body when you dab, it'd be balanced because you lose your op helmet for it

**Pull request closed without merging**
