### PR TITLE
Adds National Hot Dog Day to the holidays list

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

Hot dogs are rad so here's the holiday for it

## Why It's Good For The Game

Google "Windows 3.1 Hot Dog Stand".

## Changelog
:cl:
add: Added "National Hot Dog Day" to the list of holidays, to be celebrated on July 17th.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
H o t d o g s t a n d

**Comment by nemvar** [comment]
Hot dog theme for github when?

**Comment by TheVekter** [comment]
> Hot dog theme for github when?

There's a couple for VB Code and they're all appropriately horrendous.

**Comment by cacogen** [comment]
i'm not necessarily against this change but we had sausage sizzles at school as a kid and i always thought the "hot dogs" were shit
what do you think @optimumtact did they give you a shitty little pinto with it at school

**Pull request merged**
