### PR TITLE
Adds head-only target hotkey

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Reopen of #80804 post-embargo

Adds a new optional hotkey that targets only the head and does not cycle to eyes or mouth.

Currently the way the numpad hotkeys work on /tg/ is every key targets one body part... except 8. Numpad 8 Currently cycles through head-eyes-mouth, despite _**numpad 7 already handling mouth and numpad 9 already handling eyes**_. There's no head-only key.

image

## Why It's Good For The Game

More way to control input good

## Changelog
:cl:
qol: Added a new head-only target hotkey, unbound by default. 
/:cl:

### CODE REVIEW

**Review by MrMelbert — COMMENTED** [review]
Why change the existing hotkey? 

Why not add a second hotkey that defaults to unbound which only targets head?

**Comment by Swiftfeather** [comment]
> Why change the existing hotkey?
> 
> Why not add a second hotkey that defaults to unbound which only targets head?

Existing hot key changed to bring the default layout to one that honestly makes more sense, but I can see how people who have the cycle key bound to a different button without a numpad may want to keep it around. 

I'll put the cycle function back in but I still don't think it should be the default key bind for numpad 8.

**Comment by Higgin** [comment]
i use cycle and like it for doing surgeries, please don't get rid of it - if anything i wish we also had a cycle for torso/groin since the attacks catch onto the same bodypart but the zones are different for surgeries

**Comment by CoffeeDragon16** [comment]
oh, i added this a while ago in #55299, this was originally what i wanted for the PR but people say otherwise. i was thinking after a while people would get better used to it and it could be made like this, so thank you! 
i think you should probably leave head cycle in the game but unbound for the stubborn docs

**Comment by Swiftfeather** [comment]
I made the changes @MrMelbert suggested.

**Pull request merged**
