### PR TITLE
Energy gunfire sound pitch now varies based on how much ammo is left. Ballistic guns now have bolt sounds for low ammo.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

https://user-images.githubusercontent.com/4081722/172725708-20a6d790-a480-486d-8688-349da17e03db.mp4

## Why It's Good For The Game

Breaks up the monotony of firearm sounds, makes them actually useful in a gameplay context. Energy gun effects inspired by Cruelty Squad.

## Changelog

:cl:
soundadd: Energy and Magic gunfire sound pitch now varies based on how much ammo is left.
soundadd: Ballistic gunfire now has a low-ammo click sound.
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
The pitch probably goes down a little bit too much when the gun is really low but this is super duper cool. I love it.

**Comment by Mothblocks** [comment]
could you not have recorded this without the very loud music

**Comment by Iamgoofball** [comment]
no

**Comment by zxaber** [comment]
The click effect on ballistics is cool.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
>makes pr changing how sounds work on guns
>Records a video demonstrating the change
>Have rap music blasting louder than the guns in the video

Mind doing a demo without any music please? Kind of important to be able to judge the gun changes over your taste in jams. :P

**Comment by optimumtact** [comment]
I find it very hard to distinguish on the ballistics, but it's definitely clear on the lasers.

**Pull request merged**
