### PR TITLE
saving private cerestation

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]:

🆑 
added: cerestation and it's code
/🆑 

[why]:

because me and some others liked the map. also its a very popular meme map on hippie and a normal map on citadel and im too lazy to change it

### CODE REVIEW

**Comment by praisenarsie** [comment]
OOORAH

**Comment by deranging** [comment]
merge or not to merge? that is the question

**Comment by BeeSting12** [comment]
PR it on hippie and cit then, leave us out of it!

**Comment by deranging** [comment]
ok fine thots

**Comment by ShizCalev** [comment]
How the fuck does this even compile? It's missing items like `/obj/item/paper/fluff/stations/cere/*`, `/obj/structure/sign/map/left/ceres`, `/obj/item/paper/crumpled/stations/cere/*`

**Comment by ShizCalev** [comment]
Oh I see how, you didn't even put it in the config right, so it's not even loading it. kek

**Comment by deranging** [comment]
DONT DO IT IT WONT WORK I SUCK

**Comment by ChangelingRain** [comment]
This will not be accepted unless you are willing to maintain ceres for the main \/tg\/ branch.

**Comment by Anonymous583** [comment]
Don't fucking do this.

There's a reason it was voted off, stop trying to polish a turd. If you enjoy shit, that's on you, but don't make everyone else have to go through it.

**Comment by Bawhoppen** [comment]
@Anonymous583 separation dude

**Comment by kevinz000** [comment]
# CITADEL DOES NOT REGULARLY RUN THIS MAP.

**Comment by kevinz000** [comment]
@deranging https://github.com/Citadel-Station-13/Citadel-Station-13/pull/2509 check your facts dumbo

**Comment by MMMiracles** [comment]
sTOP

**Comment by Cyberboss** [comment]
Just PR it on your fork, maintaining maps that don't exist upstream is easy-ish

**Comment by Qbopper** [comment]
just nuke downstream servers lol

**Comment by pantherpusher** [comment]
I like the concept but it just wont work without a TON of players

**Comment by Hatfish** [comment]
bring back mini first

**Comment by Bawhoppen** [comment]
@Hatfish that is not happening in any of our lifetimes

**Pull request closed without merging**
