### PR TITLE
Nerfs hyperglycaemic shock

### PR DESCRIPTION
**Pull request by Higgin**
## About The Pull Request

salt is the superior white powder

Sugar OD was an immediate 60 second sleep followed by refreshing/adding 4 seconds of sleep every tick on OD with no cap.

This makes sugar OD an immediate 20 second sleep followed by continually pushing up drowsiness to a maximum of 60 seconds, which has an RNG 1/20 chance to put you out every tick while active. It also makes sugar metabolize faster (we love simple carbs.) 

You can get rid of the drowsiness faster by resting or consuming/using things that reduce drowsiness.

## Why It's Good For The Game

cheap and easy perma-sleeps that kick in instantly are not good, this shit is way too effective. Making sugar leave the body faster also makes it less effective as an additive to foods except in higher quantities likelier to make you fat or push you closer to the lowered OD (at one point it was 200.) 

## Changelog

:cl:
balance: Diabetics rejoice! Nerfed sugar OD/hyperglycaemic shock to be an immediate KO followed by drowsiness afterwards until the OD is gone.
/:cl:

### CODE REVIEW

**Comment by Borisvanmemes** [comment]
Ow, my esoteric powergaming strat is being killed. This is definitely for the best though.

**Comment by Pickle-Coding** [comment]
I think the point of the OD being strong is to discourage sugar pills from being used as a minmaxed way to stay satent. With the OD threshold being 100u, how are people using this as an easy way to knock people unconcious?

The vastly increased metabolism rate might also make it easier to use sugar pills as a source of food without ODing, combined with the OD threshold getting raised to 120u.

There was a food PR recently. I don't know what it really did, but if that makes sugar pills a bad way to get nutrients on its own, then I guess my concerns would be invalidated.

**Comment by YehnBeep** [comment]
> I think the point of the OD being strong is to discourage sugar pills from being used as a minmaxed way to stay sated. With the OD threshold being 100u, how are people using this as an easy way to knock people unconcious?

Even before the OD was lowered it was not hard to use honey (via bee stings or otherwise) to coma people with sugar OD. And then when the OD was halved, it got a _lot_ easier.

I raised that concern in the alluded to food PR but I don't think anyone there really cared...

**Comment by Borisvanmemes** [comment]
@Pickle-Coding Foam.
Put 10 carbon, 10 florine, 5 sulfuric in the first beaker, then fill it with sugar.
Then put 25 water in the second beaker, and fill that one with sugar too.

Put both beakers into a chemical grenade, and you've made a coma bomb in a stupidly short amount of time. Assuming that whoever you're using this doesn't get out of the foam as fast as possible, they're going to be knocked out for a VERY long time.

**Comment by improvedname** [comment]
Just keep a lower required overdose for ingest and any other method a higher threshold

**Comment by iwishforducks** [comment]
> I think the point of the OD being strong is to discourage sugar pills from being used as a minmaxed way to stay sated. With the OD threshold being 100u, how are people using this as an easy way to knock people unconcious?
> 
> The vastly increased metabolism rate might also make it easier to use sugar pills as a source of food without ODing, combined with the OD threshold getting raised to 120u.
> 
> There was a food PR recently. I don't know what it really did, but if that makes sugar pills a bad way to get nutrients on its own, then I guess my concerns would be invalidated.

how are people supposed to be punished for using sugar pills if the OD is 100u in the first place?

**Comment by moocowswag** [comment]
Roleplay value is being lost

And you know what else, Hector? I put you in that tube. Oh, yeah. Your happy virus vaccine? I switched them for sugar pills. You were crit and in maint, and I had to watch this space asshole bring you back. So when you are sitting in your shitty cryotube and you're sucking down on your cryoxadone night after night for the rest of your life, you think of MeeEeEEeeeE

**Comment by ExcessiveUseOfCobblestone** [comment]
Why not just make the sugar OD a little more sane so its still not great to get your sweet tooth on but it doesnt ruin your life when you hit a magic number most people dont have access to?

a +20 to OD threshold doesnt really change the fact that a 20s (from 60s but still) sleep fricken sucks.

**Comment by Higgin** [comment]
> Why not just make the sugar OD a little more sane so its still not great to get your sweet tooth on but it doesnt ruin your life when you hit a magic number most people dont have access to?
> 
> a +20 to OD threshold doesnt really change the fact that a 20s (from 60s but still) sleep fricken sucks.

it does suck, but it's also a lot harder to do easily, and we accept some hard shutdowns if you're willing to put the work into them (i.e. cryogelidia or zombie powder) - moving from 100->120u makes doing it with a foam grenade without upgraded beakers substantially harder, and bees/honey as a way to hit the 120u are a lot more situational or require a lot more work in advance

the bigger change here, imo, is making the overdose process itself not constantly refresh sleep - even if they get you with the initial OD, it means they have to follow it up for it to be useful. 20s might be a bit long still, but idk - what would you suggest for that?

**Comment by moocowswag** [comment]
just do 2 grenades at the same time one sugar with stabilized smoke (since sugar is a part of the smoke recipe i think you have to do stabilized) the other being foam, both with really high amounts of sugar 75%+ 

the aoe might be a bit small but to people who dont initially have their internals on when it hits theyll have a very short window to not get dumped with alot of chems.


foam and smoke stack over eachother and its one of the reasons why i use grenade stacking so much.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
