### PR TITLE
"hey cheech" "what chong" "lets add a 14k credit crate that gives you 20tc of traitor items for a one time deposit of 6 TC" "whoa thats trippy dude lets do it"

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl:
add: Here I was
add: alone in the codebase
del: completely twisted on BYOND
tweak: no IDE
fix: no commit logs for the repo
wip: and on top of everything else
experiment: a gigantic fucking cancerous mass someone added to cargo code
/:cl:

As your attorney, I advise you to merge at top speed, it'll be a god damn miracle if we can get there before you turn into a wild maintainer.

ha ha emags allowing you to order infinite traitor items is a good idea right guys?????????????????💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩

### CODE REVIEW

**Comment by Armhulen** [comment]
i'm laughing way too hard at this

**Comment by ma44** [comment]
if you don't want people ordering NULL crates, then just unemag the computer.

All you need is a screwdriver and that's it ;-;

**Comment by KorPhaeron** [comment]
Maybe instead you shouldnt have broken cargo to have infinite points via exports and stock market

**Comment by Iamgoofball** [comment]
@KorPhaeron thats not the problem man the problem is the fact everything now costs 6 tc

**Comment by callanrocks** [comment]
maybe remove stock market since thats the broken thing?

**Comment by Iamgoofball** [comment]
we dont need to remove one of the only creative ways to get money because you cant handle not having infinite TC

**Comment by xxalpha** [comment]
You need to stop making PRs under influence.

**Comment by Firecage** [comment]
@Iamgoofball Just removing this is fairly shitty fix

This never used to be a problem at all. It used to be that, compared to the ways to get more cargo points, the crate was expensive, and people could never order to many of them.

This PR just fixes a symptom, and not the issue. It is currently way to easy to get a fuckload of cargo points, compared to the prices of the crates. A mediocre Botanist can easily give cargo 200k cargo points. A good one can give them 2 million cargo points.

We can now sell any type of mineral for points, not just plasma.

Due to stocks sometimes going....nutty(not gonna say goofy), Cargo can also get a fuckload of points(or if they are unlucky, go so deep into the red they can never recover).

So no, as I said. This PR only fixes a symptom, and not the issue itself, since this crate never used to be a huge issue, since it was expensive, and there was no good way to get a lot of points easily, and since it had the possibility of being a trash bundle, it wasn't always worth it.

A better fix would be to take the time to look at all the ways cargo can get alot of points currently, and either adjust the amount of points they give, or remove it if it is to easily abusable. And perhaps fix stocks suddenly jumping to a few million credits in value.

**Comment by MMMiracles** [comment]
I used to order a fuck-ton of these as cargo before the stock update because all you had to do was tell the miners "hey bring in plasma and i'll give you a bunch of traitor shit", that was enough motivation for them to mine out the asteroid of all of its plasma.

Stock just made it not require bribing miners for their plasma.

**Comment by Shapsy** [comment]
spamming traitor items everywhere is lots of fun to do as a traitor QM/cargo tech/person who made a deal with cargo, especially if you spam them to the point where the entire department is loaded with blatantly illegal goods. It's not like it happens every round, leave it be

**Comment by MMMiracles** [comment]
Should at least remove the uplink crate because giving people literally every traitor implant including a free 20TC uplink is so hilariously overpowered like oh my god.

**Comment by PKPenguin321** [comment]
fun removal

**Comment by Shadowlight213** [comment]
@callanrocks It's not the stock market though.
I see people get way more credits just from exports.

**Comment by optimumtact** [comment]
This had to happen at some point and I am going to merge this in the absence of any thing resembling balance in cargo.

**Comment by KorPhaeron** [comment]
Can we force the people who broke cargo to fix it instead of letting them take the easy way out

**Comment by optimumtact** [comment]
I'm not going to leave cargo in a broken state while we spend 3 years arguing about how to balance it.

**Comment by KorPhaeron** [comment]
It will still be broken after this and they'll move on to buying 3000 autorifles or some shit.

Next time we do a freeze it should be a "make our resource systems make any sort of sense" theme.

**Comment by jughu** [comment]
Wheres the communism tag

**Comment by ike709** [comment]
Wheres the citrusy tyranny tag

**Comment by Archie700** [comment]
This is the exact same pr as #19813.

>Keep the title readable and i'll reopen it.

The fact that you decided to make the exact same pr with a different shitty title AND changed it back when maintainers tried to make it readable means that you don't even respect the people in charge.

**Comment by Shadowlight213** [comment]
@KorPhaeron maybe we should fix cargo balance by undoing goofconomy?
Things seemed perfectly balanced in the old cargo system. 
And if goofball continues to blame everything but his own system and won't fix it, maybe the system isn't worth havung.

**Comment by optimumtact** [comment]
I'm not going to defend your memes goof

**Comment by AnonymousNow** [comment]
Fun removal update. 
At most, change the crate that people get so it's not likely to have the best Syndicate shit, if it's a problem.

**Comment by callanrocks** [comment]
No but seriously just nerf cash dolla botany spam a bit. All you have to do is make them give you less points instead of remove a fun feature because goof gonna goof and refuses to fix his shit.

**Pull request closed without merging**
