### PR TITLE
Tiny bit better splitting on add_details

### PR DESCRIPTION
**Pull request by AnturK**
` "meme"|"meme2" ` Instead of `meme meme2 `

@nfreader

### CODE REVIEW

**Comment by Cyberboss** [comment]
Should add a check for `|`s in `text` and drop a warning if it finds one

**Comment by nfreader** [comment]
Yay! 👍

**Comment by optimumtact** [comment]
@AnturK why is this DNM?

**Comment by Cyberboss** [comment]
@AnturK pls

**Comment by AnturK** [comment]
I'll just close it until i can get in touch with @nfreader

**Comment by AnturK** [comment]
Still DNM since this is testmerge only code right now.

**Comment by nfreader** [comment]
Alright, I've got some test data to play around with and at first glance, this looks like it's waaaaaaaaaaay easier to use. I'll keep poking things and get back to you :)

**Comment by nfreader** [comment]
1st Addendum: Once we merge this and drop the `test_` var_name prefix, I will ABSOLUTELY need to know when that change was made. Older feedback will need to be parsed with the current statbus code, while stats created after this PR is merged will need to use the new statbus code. 

This is imperative for downstream support as well.

**Comment by optimumtact** [comment]
time to add a schema version stamp to the stat table columns

**Comment by Jordie0608** [comment]
Or just like, look at the feedback data and see when the format changes.

**Comment by Cyberboss** [comment]
So is this ready?

**Comment by AnturK** [comment]
Yes.

**Comment by optimumtact** [comment]
@nfreader you ready?

**Comment by nfreader** [comment]
Yea. Please try to let me know what round IDs/dates mark the starting point for this being active. Thanks!

**Comment by Cyberboss** [comment]
@nfreader First round to have this active will be #74703

**Pull request merged**
