### PR TITLE
Sanity is now capped.

### LINKED ISSUE #45391: mood seems to be broken
113823

i was with low mood for most of the round (2 big negative events) but somehow i had maxed sanity

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Fixies a fuckie wuckie caused by Floyd-chan bweing a baka. Sanaties is naow cappied at 150.

## Why It's Good For The Game

Infinite perfect sanity bad. Actual maximum sanity is up to debate if anyone has strong feeling on this.
Fixes #45391

## Changelog
:cl:
balance: Sanity is no longer uncapped. It's now capped at 150, whatever that means.
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
No more "You haven't eaten in 10 minutes since round start, time to go crazy."?

**Comment by nemvar** [comment]
Unrelated to that.

**Comment by optimumtact** [comment]
@SynnGraffkin that's more of a messaging issue where the users hunger level can range almost 100 points before the moody changes, so you can be 20 points from actually starving but the moodlet (which is what most people judge their hunger by, is still showing the generic you are hungry moodlet)

People need to pay closer attention to their hunger alert.

**Comment by ExcessiveUseOfCobblestone** [comment]
w-w-what are we gonna do on the PR, oniichan?

**Pull request merged**
