### PR TITLE
Adds Log Message When Player Dies

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request
Logs a message upon player with with name, location, and damage. I elected to put this in game over attack as it feels more relevant to game.

ex: `[2019-06-27 22:25:41.936] GAME: Guest-3461400476/(Dumb Retard Ecksdee) has died (BRUTE: 52.8, BURN: 0, TOX: 0, OXY: 0, CLONE: 0) (Brig Control (115, 174, 2))`

## Why It's Good For The Game
Hey, vsauce, michael here. I died... or did I? *deathgasp

## Changelog
:cl: bobbahbrown
tweak: Deaths are now logged to the game log.
/:cl:

### CODE REVIEW

**Comment by Shapsy** [comment]
Kinda fascinating that it took until 2019 for this to finally happen

**Comment by bobbahbrown** [comment]
h

**Comment by PKPenguin321** [comment]
Nothing's stopping you from putting it in both game and attack logs

**Comment by optimumtact** [comment]
this shit is already logged somewhere, like the db?

**Comment by nfreader** [comment]
It is logged in the DB but only a few people have access to it. I’m not a fan of duplicating data but this seems like something that should be in the logs.

**Comment by bobbahbrown** [comment]
> this shit is already logged somewhere, like the db?

aside from db there is no way to definitively say that someone died in a round afaik

**Review by SpaceManiac — APPROVED** [review]
looks good enough to me

**Pull request merged**
