### PR TITLE
Adds roblox themed brain damage statements

### PR DESCRIPTION
**Pull request by chesse20**
Added some stuff kids say on roblox, and also added yelling pickle rick
:cl:
add: Added 4 new brain damage statements
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I feel like we're approaching some kind of limit to how far we can stretch this mechanic and honestly it's probably my fault for starting the whole thing in the first place

**Comment by MMMiracles** [comment]
the only thing that could really fit is the 'oof' and you don't even have that here

c'mon man

**Comment by PKPenguin321** [comment]
Oof isn't even a brain damage thing it's like an primal gutteral instinct that resides in all of us on some level

**Comment by Iamgoofball** [comment]
is it time for me to take brain damage lines out behind the barn

**Comment by Bluespace** [comment]
These are dumb.

**Comment by optimumtact** [comment]
oof

**Pull request closed without merging**
