### PR TITLE
Removes stunprods and cablecuffs, makes spears uncraftable [DNM for now]

### PR DESCRIPTION
**Pull request by MrPerson**
The spear crafting I'm not sure about but cablecuffs and stunprods just encouraged valid-hunting behavior and making them "just in case".

### CODE REVIEW

**Comment by Sometinyprick** [comment]
you monster

**Comment by killerfgs** [comment]
muh fun

**Comment by AnturK** [comment]
Not sure if this is a joke PR but i believe cablecuffs are too essential for non-murder antagging to just throw away.

**Comment by Bluespace** [comment]
if this is merged i'm leaving. :-1:

**Comment by Jalleo** [comment]
Make the cuffs a config.
Spear needs a better sprite then. maybe roman?
I agree with stun prod since it was essentially a resprited baton.

**Comment by WJohn** [comment]
I can't say I'm in support of straight up removal of items "because it causes valid hunting". The kind of hell we'll get from literally everyone (not just valid hunter) is not at all worth it. I'm really not even seeing anyone against these items anyway.

**Comment by phil235** [comment]
This means antags won't be able to easily get cuffs which will severely affect non-lethal play. I'm not entirely against making improvised cuffs less accessible but this is too much. :-1:

**Comment by AlexCrimson** [comment]
This is stupid. Assuming you are serious and it isnt a really late April Fools joke.

If you intend to remove these then make sure you remove everything else that people keep on their person "just in case". Including weapons, spray bottles, healing items(when at full health), armor, flashes etc.

**Comment by Kromgar** [comment]
This is ltierally fucking retarded. This removes gameplay elements. Nothing is even wrong with stun prods. Stun gloves were op and replaced with stun prods

**Comment by demonfiren** [comment]
You're late for April Fools.

**Comment by Incomptinence** [comment]
But then who was ling?

**Comment by QuartzCrystal** [comment]
Nonononononononononononononononononono

**Comment by Man-Shroom** [comment]
If you do this revolutionaries and changelings and gang members will have LITERALLY no equipment to take down people. Did you even consider what would happen if you remove this? :-1: :x: :100:

**Comment by xxalpha** [comment]
Just make stunprods too big to fit in backpacks and don't remove anything.

**Comment by vista-** [comment]
I agree with this PR somewhat, stun prods at the moment are still a really easy "gg no re" solution. Either make them unconcealable like @WJohn suggested, or make them consume a LOT of power. 9k would make for a nice compromise, I think (they consume power while turned on, 10k wouldn't make sense). One use only with a high-capacity (aka the stuff that's always lying around) power cell, 2 with a super-capacity power cell, 3 with a hyper-capacity power cell.

**Comment by AlexCrimson** [comment]
Id say making them one-use with a high cap cell would work. No reason for them to have a bunch of charges. Hell, seeing as they are improvised weapons, maybe give them a chance of inflicting minor burn damage on the user?

**Comment by dannno** [comment]
not really sure why you thought this would be a good idea
or if this is a joke or something
:-1:

**Comment by Steelpoint** [comment]
I disagree with these proposed changes.

Make them harder to produce if we're really concerned about "valid-hunting", right now these materials are relativity easy to come by even if toolstorage is cleaned out. Prehaps reduce the Spears damage down somewhat (It deals around 20ish Brute if wielded) and make the Stun Prod harder to produce.

**Comment by dannno** [comment]
spears aren't even the best option for validhunters by far.
they're actually somewhat infamously mediocre, so I don't know what the worry is.

**Comment by Steelpoint** [comment]
I think at some point someone slightly buffed spears to deal higher damage, here are the damage values that I dug up..

Unwielded (One Hand Attack) =  10 Brute Damage
Wielded = 18 Brute Damage
Thrown = 20 Brute Damage

**Comment by dannno** [comment]
they're strong but they're not practical at all
to carry it around without you constantly having it in your hands you need to lose your backpack
need two hands for it to be worth something in combat as well

**Comment by Steelpoint** [comment]
Don't worry I agree with you in that the spear is balanced as it stands, its a very obvious item that you cannot hide on your person.

I can, however, see what MrPerson is getting at with the stun prod.

If any change has to be made, why not do it akin to the spear in that you cannot put the stun prod in your backpack, make it a large item you have to either hold or drag with you.

**Comment by dannno** [comment]
yeah, the only real tangible issue here is stun prods. forget spears and cablecuffs.

**Comment by AlexCrimson** [comment]
Not being able to place a Stun Prod in your backpack would defeat the whole point of using one. Its a stealthy weapon. Nobody is going to use it otherwise. You might as well just remove it.

**Comment by Xhuis** [comment]
Cablecuffs are too essential for antagonists who don't have access to normal methods of restraining people.

The spear is already very obvious and can't fit in backpacks. Most security teams at least keep an eye out on people with spears if not just straight-up confiscating them.

I strongly disagree with stunprod removal. Stunprods are balanced out by their small amount of force as well as the fact that they drain their power cells extremely fast (a high-cap will only last four roughly 3-4 hits).

Overall, :-1:

**Comment by dannno** [comment]
>it's a stealthy weapon

?????

**Comment by AlexCrimson** [comment]
As in you keep it hidden in your backpack, then pull it out when close to your victim and give em a whack with it.

**Comment by SconesC** [comment]
Just remove cablecuffs. We sort of agreed that THOSE were a huge source of problems, moreso than the actual initial CC.

**Comment by dannno** [comment]
who agreed lmao
they aren't problematic at all

**Comment by Sometinyprick** [comment]
cablecuffs reduce problems
it makes it easier for people to deal with stuff without resorting to violence

**Comment by KorPhaeron** [comment]
Why is "validhunting" bad? If some guy is running around eswording everyone and he gets stun prodded, whats wrong with that? They're called "valid" for a reason.

This is tg, where the clown can slip a nuke op and axe him to death, not bay where you get banned for robusting as the wrong job.

**Comment by MrStonedOne** [comment]
Coderbus is separate from the servers.

This is an administrative issue, let us handle it.

Either that, or make it a config option.

**Comment by ACCount12** [comment]
:-1: no

**Comment by chimersable** [comment]
Stupid, critting people is a far easier way of dealing with hostile people than trying to do stuns or cable cuffs, these things are in the game for the sake of mercy so civilians can take hostile people alive.

**Comment by AndroidSFV** [comment]
:-1:

**Comment by stapler2025** [comment]
MrP you barely even play, stop doing stupid shit that nobody wants but you.

**Comment by PKPenguin321** [comment]
:-1: :-1: :-1: :-1: 
1f44e

**Comment by ike709** [comment]
April Fools was a couple days ago. :-1:

**Comment by Lumipharon** [comment]
This is really dumb. They are tools (not the spear, it's literally never an issue ever, seriously) that can be used by shitters.
However they also have actual use.
Cuffs aren't easy to get, you either get them from sec, or a hacked autolathe. Without cable cuffs, non sec literally can't subdue people without beating them to crit or something.

Stun prods are in severely limited supply - they need high cap power cells, there are like, 2? available in public spaces, otherwise you need to access science or engineering to get more.

I seriously can't fathom the logic behind this - they're both used extensively for genuine reasons (like antags using them, or people using them on antags/shitters), just because they CAN in turn be used by shitters, why the hell would you remove something that's genuinely useful if not needed for game balance because of the lack of alternatives?

This is going to be like when the stun nerf first happened, and cuffs took so long to apply to someone compared to stun duration, that people were just critting people instead. Only with this, they won't be able to cuff them AT ALL.

What is wrong with a ghetto stun weapon that's MELEE RANGE.

**Comment by AnonymousNow** [comment]
Is this real?

It sounds like functionality is being removed for all because some mean people use it badly.

**Comment by ZomgPonies** [comment]
For stunprods just do what we did. Just make their weight class bigger.

**Comment by MrPerson** [comment]
But then what purpose do stunprods serve? Yes, right now, the stuns they provide are needed, but frankly it shouldn't be necessary. Figuring out these problems is why I tagged this DNM for now.

Specifically, I have so far:

- [ ]  Security armor is too good
- [ ]  Random weapons on the station don't do enough damage to be viable for killing security, even with mob action (rev)
- [ ]  It's not possible to detain people without handcuffs, but once they are handcuffed you can kill them trivially
- [ ]  Changelings aren't good at killing people without stunprods. (debatable)

**Comment by babinsquared** [comment]
I don't see why nonlethal detainment is an issue. If the clown is breaking into my office and being a shitler, and security is not responding, and critting him will probably get me boinked, how else am I supposed to handle him?

This is a common situation, not some once-in-a-lifetime occurence.

**Comment by stapler2025** [comment]
its almost as if coderbus is actively trying to sabotage the /tg/ code and kill off the community that uses it.

**Comment by Fox-McCloud** [comment]
:-1: 

Big thumbs down. If these are removed, then security literally has the means to walk over anyone any time of the day (which they debtably already do)---only now with zero counterplay unless you're a full out and out blatantly obvious traitor. 

Removal of the stunprod effectively means the only people with *any* access to stun weapons are security members and the bartender--heck, traitors *now* only have access to a single stun weapon that has a super long recharge time.

**Comment by PKPenguin321** [comment]
>Figuring out these problems is why I tagged this DNM for now.

if you wanted feedback on stunprods, well guess what we have a whole forum for
don't hold stunprods, cuffs, and spears hostage
this isn't a personal attack, i'm just kind of offended that you feel the best way to get feedback is try to remove fully functioning features outright which nobody wants removed

**Comment by Uqualm** [comment]
good idea
remove it.

fucking tired of those shitters catching me while i'm antag with cable cuffs

should be able to go and murder everyone with no problem. got a problem bitch? take it up with my ebow and esword 

the unbeatable combo :^) can't fight that
can't beat that
i'm a one man army

no cable cuffs keep a nigga down

**Comment by Cheridan** [comment]
This really won't solve anything. People have hunted antags on /tg/station since it's existed, only then they did it with acid spray or tabling. I'm not the biggest fan of cablecuffs but it's entirely true that if you take them out then the people who are playing vigilantes now will just beat to death the people they would have otherwise arrested.

**Comment by Uqualm** [comment]
shut the fuck up cheridan.

**Comment by Aranclanos** [comment]
rekt

**Comment by Jalleo** [comment]
This needs a discussion with the headmins. This is both a code and policy issue.

**Comment by Lumipharon** [comment]
It's really not. Lets go through them item by item.

Spear: Does ANYONE genuinely think this item is an issue? It's a bulky item, that's shit in melee, and is reasonable as a ONE USE ranged weapon. If you feel this item is an issue, please elaborate.

Cablecuffs: No way to restrain people without themas non sec, which ass fucks traitors and normal crew - vigilantees are more likely to just murder valid people anyway - that doesn't change anything.

Stunprod: The only item among the three that is even worth discussion, but the fact is in terms of public access, the entire crew can only make a couple - otherwise you need access to science, engineering, or a few odd ones like eva etc. Either way though, I don't understand how you can argue that these should be removed, when we have stun batons and telescopic batons in the game.

**Comment by Jalleo** [comment]
I agree on the spear statement the cuffs and stunprod should be discussed though because the admins and headadmins would know very well how much they are used if at all.
Its more this should be discussed to remove myths between coders and reality on how powergaming is currently at.

This PR is really a public statement by mrperson on wanting to deal with the stupid gimmick weapons there is.

I dont like the stun prod only because you can hide it. Apart from that it works better than the gloves ever did at trying to balance. 

The cable cuffs should stay though that is why i am saying config because then it can be decided by the servers if they want it. But i would rather it stay.

I personally dont like this PR but I dont think @MrPerson will close it.

**Comment by Sometinyprick** [comment]
@Jalleo If cablecuffs were removed I would have to tell people to just crit whoever breaks in or decides to be a pain. If they are really belligerent there is no easy way to deal with them without cablecuffs if security isn't around to help.

**Comment by Cheridan** [comment]
Calling this a server administration issue is kind of disingenuous. /tg/station has a history of solving issues of poor player behavior with code-based solutions, because otherwise it wouldn't get fixed at all.

How many people have been banned for validhunting/vigilantism here? I can only think of a single example.

(note that I still don't agree with this PR, I just felt the need to address that argument)

**Comment by MrPerson** [comment]
If the entire combat system is predicated on stunprods, that implies the combat system is shit and should be fixed.

Cablecuffs are not a viable way to detain someone in 100% of circumstances

**Comment by dannno** [comment]
seriously spears/cablecuffs shouldn't be touched here unless you have some incredible idea for improving them.
stun prods is another matter.

**Comment by AlexCrimson** [comment]
What would you prefer? Asking them nicely to not run away? Giving people an easily accessible way to restrain other players tends to lead to interesting situations. Yeah they are used by validhunters, but removing them sure as hell will not stop that kind of behavior.

**Comment by Sometinyprick** [comment]
@MrPerson What? of course they are viable, if you want to be non-lethal they are pretty much the only way to deal with someone unless you have access to actual handcuffs or  which most of the time you don't. I mean sure you could use a welded locker but they are just problematic when you need to let him out.
Security are rarely around to deal with conflicts quickly so having ghetto cuffs allows players to keep people down long enough for security to come take them away.

**Comment by MrPerson** [comment]
No I mean not everyone has cables lying around their workplace

**Comment by Sometinyprick** [comment]
Yea but they are easily accessible.

**Comment by drynwyn** [comment]
Yeah- there are a half-dozen cable rolls in Art Storage and 10 in the Tool Storage vendor, plus another half-dozen or so lying around in Tool Storage. And those are just the publicly accessible ones. Engineering and Science both have cables out the ass.

**Comment by Miauw62** [comment]
Stunprods and cable cuffs are part of how our combat works right now, like
it or not. You could remove them in a complete rework, but don't remove
them and then spend a month writing a new combat system because everything
will be fucked in the meantime. And spears are really not OP.

Large maintainer opposition and headcoder dislike mean that this PR should
probably be closed.
Op 6-apr.-2015 18:10 schreef "drynwyn" <notifications@github.com>:

**Comment by hornygranny** [comment]
@MrPerson we would accept making cablecuffs consume an entire coil of cable, and making the stunprod spear-sized.

**Pull request closed without merging**
