### PR TITLE
You can now proselytize false walls + glow fixes

### PR DESCRIPTION
**Pull request by ChangelingRain**
Wall gears and false brass walls now have glows.
All of the ratvarian glows will no longer appear to 'linger' until deleted; this should make the proselytization from the clockwork gateway less weird-looking(it'll still be a little weird, though).
The proselytization and Ratvar will once again fully convert turfs instead of sometimes only converting objects on the turf.
The proselytization and Ratvar will also convert false walls and girders.

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Even though this is small, having to deconstruct the false wall into my cult maint base, make it a normal wall, proselytize it, then deconstruct that, the make that a fake wall, was always a hassle in my opinion. Now stylish walls can be mine with minimal effort. 

Also is it possible to convert computers? I've seen Ratvar do it, but I haven't actually tried to with a proselytizer.

**Comment by ChangelingRain** [comment]
Nope; it's also just cosmetic.

**Comment by Anonmare** [comment]
I genuinely thought Clock Cultists could convert computers to gain control of them whilst lockign out everyone else.

**Comment by KingPhilipIII** [comment]
Wait. Can they use the proselytizer or not on computers? It's not a matter of can they lock others out, I just want sweet computers. (RD once asked a cultist to come proselytize his officer because he thought it looked cool.)

**Comment by ChangelingRain** [comment]
They can't, no.

**Pull request merged**
