### PR TITLE
Duffelbag Resprite!

### PR DESCRIPTION
**Pull request by CliffracerX**
## About The Pull Request

Reworks the duffelbag inventory, inhand, and worn icons to match the palette & visual style of the post-rework backpacks and satchels.  No longer are they as dorktastic and crusty as pre-rework R&D, and they even look nice in your hands as the last thing some poor Assistant sees before getting walloped*!

```* Disclaimer: duffelbags are not, in fact, weapons.  Attempt to wallop at your own discretion.```

image

## Why It's Good For The Game

Visual consistency is nice, and with people actually using duffelbags more after the zipper rework, it's the perfect time to give them a glow-up.

## Changelog

:cl:
image: resprited all duffelbags, including worn and inhand variants to match modern storage.
/:cl:

### CODE REVIEW

**Comment by DaydreamIQ** [comment]
Is the cursed duffelbag not included in this?

**Comment by CliffracerX** [comment]
> Is the cursed duffelbag not included in this?

It is not at present; given it's *meant* to be creepy and grungy I think it's fine to leave it as is.  All the more reason to not want one on your back!  (That said, I can still change it if maints want; it shouldn't be too hard an update)

**Comment by EricZilla** [comment]
Love these

**Comment by DATA-xPUNGED** [comment]
Captain's seems to use a different shade of blue than the clothings
Also, do you *also* use your static to test stuff?

**Comment by CliffracerX** [comment]
> Captain's seems to use a different shade of blue than the clothings Also, do you _also_ use your static to test stuff?

Cappy's backpacks and satchels are on a different palette to begin with!  I'd probably actually extend that theme to all the storage items, as I don't super dig how the medical/sci packs are literally the same colors as the labcoats/jumpsuits, but- that's a bit beyond the scope of this PR.

And aye- I started with a module on my server, but still wanted to get proper pics in-engine on unmodified TGcode to do things properly.  I don't wanna peeve the maints anymore than they already were when I accidentally submitted a nuke in PR form the other day!

**Comment by GoldenAlpharex** [comment]
My only question with this is, why the zipper on the side? Isn't the traditional duffel bag design to have the zipper between the two handles at the top?

**Comment by VladinXXV** [comment]
Not a big fan of the reddish-brown for syndie duffels; black and red is really the way to go.

I think it might be better to omit visually representing the zippers, especially given how well they blend in on the white duffelbags (and being in the wrong spot).

I'm curious about the source/inspiration for the symbols on the viro, chem, and sci duffels. Nothing wrong with them, just curious.

That all aside, very nice looking. Particularly like the mining duffel for reasons unknown to me.

**Comment by CliffracerX** [comment]
> My only question with this is, why the zipper on the side? Isn't the traditional duffel bag design to have the zipper between the two handles at the top?

The side zipper is a left-over design element of the original duffel design, as is the little metal greeble in the upper-left of the inventory sprite.  I *assume* the intention is to signify that it has Tacti-Cool Side Pockets or something, but realistically it would make sense to move to the top.

> Not a big fan of the reddish-brown for syndie duffels; black and red is really the way to go.
> 
> I think it might be better to omit visually representing the zippers, especially given how well they blend in on the white duffelbags (and being in the wrong spot).
> 
> I'm curious about the source/inspiration for the symbols on the viro, chem, and sci duffels. Nothing wrong with them, just curious.

For what it's worth, the reddish-brown and maroon is pulled exactly from the color palettes of the bloodred MOD; I wanted to make them pop a little more as *eeeevil* & tied to the Syndicate's overall stylings.  Just redoing red-on-black also wouldn't be ideal, as the baseline syndie suffelbag would end up near-indistinguishable from Sec's bags unless using a *very* dark black or *very* bright red.

See above; I'm not opposed to moving/removing the zipper sprites at this point.  The only thing I can think of to justify keeping them there would be making an unzipped variant for the inventory for that extra bit of visual flair and indication that your bag is open & slowing you down.

Finally, the symbols for the various med/sci duffels are my best attempts at crunching the versions seen on backpacks down into roughly a 3x3 space; I wanted to keep the size of the "department patches" consistent, as they're all about 5x5 on backpacks and 5x4 on satchels IIRC, and 3x3 was the best to make them recognizable but not scrungled from curvature (or lack there-of.)

**Comment by Serxule** [comment]
i agree that the syndiduffle should stay black and red, red and brown do not mix at all and looks very ugly imo

**Comment by DATA-xPUNGED** [comment]
> > Captain's seems to use a different shade of blue than the clothings Also, do you _also_ use your static to test stuff?
> 
> Cappy's backpacks and satchels are on a different palette to begin with! I'd probably actually extend that theme to all the storage items, as I don't super dig how the medical/sci packs are literally the same colors as the labcoats/jumpsuits, but- that's a bit beyond the scope of this PR.
> 
> And aye- I started with a module on my server, but still wanted to get proper pics in-engine on unmodified TGcode to do things properly. I don't wanna peeve the maints anymore than they already were when I accidentally submitted a nuke in PR form the other day!

i said about the static because i'm guilty, too :>

**Comment by Serxule** [comment]
also iirc the captain bag sprites still have the old color palette that captain used to have before the resprite

**Comment by CliffracerX** [comment]
> also iirc the captain bag sprites still have the old color palette that captain used to have before the resprite

The held cappy packs still use the old colors.  Their inventory and worn icons are using the new standard captain palette, though; that's where I pulled the palette for the cappy duffel from.

**Comment by CliffracerX** [comment]
So, per popular request: the syndie bags in a more traditional black and red.

image

Not gonna put these in the PR 'till I get feedback so I don't spam commits, but- this is more like the original black-and-red, while still only using colors from syndie equipment (red from the Bloodred MOD, black from the Tacticool Turtleneck) - and dark enough to be distinguishable from Sec.

And equally, since it's been such a common ask: meduffel that ditches the zipper, just to see if people like it better.

image

IMO, it feels a little less recognizable without it, but that may just be the fact I'm an old fart who's only ever seen SS13 duffels with big ol' zippers.

**Comment by VladinXXV** [comment]
> (new syndie duffel colors)
> (med duffel w/o zipper)

very nice.

for the record, wallem didn't notice there were possible changes pending. if you have any interest in getting those changes in still i think you'd  just make another pr.

"spamming commits" isn't something to worry about too much because commits get squashed in the end anyway (i am parroting what i was told)

**Comment by CliffracerX** [comment]
I don't plan to do the zipperless duffels since they were a distinct visual downgrade, but if peeps holler at me I'll gladly shove the black-and-red syndie ones in as a separate PR.  As it is, I'm just glad it got accepted!

**Pull request merged**
