### PR TITLE
ghost sprite fixes for #9944

### LINKED ISSUE #9944: Some of the new ghost sprites have errors
Tthe fire ghost is shifted two pixels down, and the pinkserbet ghost is shifted a pixel up.
The camo ghost is also awful but that's not actually an error~

### PR DESCRIPTION
**Pull request by BananaCreamPie**
Fixes #9944 the pixel placement being off and edited the camo version/funkypurp. 

ss 2015-06-13 at 09 02 18
(regular ghosts for placement reference)

### CODE REVIEW

**Comment by PKPenguin321** [comment]
conflicts with #9948 or nah?

**Comment by francinum** [comment]
Exactly the same thing, except this also modifies camo.

**Comment by BananaCreamPie** [comment]
and the funky purple sorry franc I had already started respriting and didn't see your pr

**Comment by phil235** [comment]
@BananaCreamPie merge conflict

**Pull request closed without merging**
