### PR TITLE
Fixing projectile sprites

### PR DESCRIPTION
**Pull request by TZK13**
If you're going to edit sprites with the built-in editor in a dmi file please make sure you don't fuck a bunch of other sprites in doing so, in greyscaling the spark sprites one colour that was shared with a bunch of other red projectile sprites was made grey for all of them thus causing bits of grey to appear in the red projectile sprites.

Basically the same thing had to be fixed in #5603.

### CODE REVIEW

**Comment by Perakp** [comment]
Swapping colors in one 32x32 icon within a dmi also swaps the colors in the entire dmi? Didn't know that.

**Comment by WJohn** [comment]
Ooooh so that's what screwed up so many sprites. People were editing the colors on the little "all colors used in the entire .dmi" tab to the right. Editing that edits all of them in the same .dmi (which can be beneficial but is usually bad).

**Comment by paprka** [comment]
Yep, this is how the nuke got fucked. We need to put out a PSA on dmi editing. I've known this for a while but I made the mistake before and fucked up a whole file, it's messy.

**Comment by Jordie0608** [comment]
Doesn't it pop a warning about this when you try to edit them?

**Comment by Anonus** [comment]
Nope! Warnings are for scrubs, apparently.

**Pull request merged**
