### PR TITLE
Adds a brain damage line

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by Supermichael777** [comment]
I was about to say no Nazi jokes but then i got the joke

No Nazi jokes

**Comment by Kromgar** [comment]
What the hell is this joke?

**Comment by Jordie0608** [comment]
https://github.com/tgstation/tgstation/blob/master/CONTRIBUTING.md#banned-content

**Comment by PKPenguin321** [comment]
pretty funny and i'd say do it if it wasn't so OOC sounding for an IC line

**Comment by FantasticFwoosh** [comment]
Sounds like _someone trying to sound retarded_ rather than a actual line. Unnatural & forced unfunny phrase baiting content on a policy we shouldn't be exploring

**Reeeeeeeejected.**

**Comment by Militaires** [comment]
@fantasticfwoosh

kind of like you

**Comment by Cyberboss** [comment]
Alright, fiiinnnnneeee

**Pull request closed without merging**
