### PR TITLE
Fixes stale data when a user performs a refresh of a TGUI page

### PR DESCRIPTION
**Pull request by raffclar**
## About The Pull Request

We should send a full update when a user refreshes a TGUI web page. Refreshes can be performed by pressing F5 while focused within a TGUI window.

## Why It's Good For The Game

A user expects a refresh to give them the latest application data.

## Changelog

:cl:
fix: When a TGUI web page is refreshed, send new data to that page.
/:cl:

### CODE REVIEW

**Comment by stylemistake** [comment]
Very nice. This should fix some UIs bluescreening due to missing static_data on the fresh page. I don't remember which ones bluescreen, but cargo, rnd and techfab can't function without static data.

**Review by stylemistake — APPROVED** [review]

**Comment by raffclar** [comment]
> 
> 
> Very nice. This should fix some UIs bluescreening due to missing static_data on the fresh page. I don't remember which ones bluescreen, but cargo, rnd and techfab can't function without static data. I assume you have tested?

It does a fix odd cases with no state. I also tested manually by stepping through a debugger with some consoles.

After refreshing before my change:
image
After refreshing with my change:
image

**Comment by optimumtact** [comment]
does this introduce a vector for DOS from tgui's with large amounts of static data?

**Comment by stylemistake** [comment]
Yes.

**Comment by optimumtact** [comment]
anything we can do to detect excessive f5's and hit them with a loading page and a long timer cooldown?

**Comment by stylemistake** [comment]
> anything we can do

Yes, if they're not admin, they shall get infinite cooldown.

**Comment by optimumtact** [comment]
I accidentaly ctrl + r a few ui's occasionally though.

**Comment by stylemistake** [comment]
Ok, a basic cooldown will do. Once triggered, UIs will load in broken state, but not any more broken than they currently are, when pressing F5.

**Comment by raffclar** [comment]
@stylemistake @optimumtact 5 second cooldown added to prevent abuse. Tested and debugged it. Let me know if this is ok

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
