### PR TITLE
Nerf Stun Batons because Terry keeps votekicking me

### PR DESCRIPTION
**Pull request by Iamgoofball**
i told them I'd do it if they votekicked me again and THEY DID IT AGAIN IVE BEEN VOTEKICKED 10 TIMES NOW

:cl: Iamgoofball
fix: Nerf Stun Batons because Terry keeps votekicking me, they now 4 hit stamcrit now
/:cl:

### CODE REVIEW

**Comment by Rex9001** [comment]
Damn, I got kicked pr.....

**Comment by SovietJenga** [comment]
ikick pr

**Comment by rellyreri** [comment]
Your issue has been determined by an administrator to be an issue of skill and does NOT require administrator intervention at this time. For further resolution you should pursue skill related options, such as improving at the game.

**Comment by Helg2** [comment]
Your issue has been determined by an administrator to be an issue of skill and does NOT require administrator intervention at this time. For further resolution you should pursue skill related options, such as improving at the game.

**Comment by Vect0r2** [comment]
Honestly thou, 20? I would go with 35 if we are gonna nerf at all. Also, this is getting closed once the maintainers see it lol.

**Pull request closed without merging**
