### PR TITLE
More floors, exterior hull sprites, exterior hull with oxygen.

### PR DESCRIPTION
**Pull request by YesterdaysPromise**
## About The Pull Request

I have been requested to do exterior hull sprites a couple times, went quite lazy on them but done them. Also took it as an oppurtunity to get the floors I made for wallening expansion in: adamantine, metal hydrogen and runite, plus some bones for mappers utility, I am sure someone eventually will sprite dead space whale and they will come in handy. Either way, I have also done walls and doors for these, but those will come after wallening, along tables, which I haven't done and don't have power in me for at the moment. Also have done some alien-flooring, but again, those after wallening. In short:
Adamantine, Metal Hydrogen, Runite, Bones, Exterior Hull.
image
hope

## Why It's Good For The Game
For the hull - well, mappers requested it of me.
For the others, if you are gonna use a rare material to make a floor, it should at least be suitably cool floor, you know?

## Changelog

:cl:
add: Added floors for adamantine, runite and metal hydrogen.
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
ok but how does it look ingame

**Comment by Wallemations** [comment]
I want to see how well these tile, not just singular snapshots.

**Comment by SimplySmiley123** [comment]
Well, but how do these look in-game?

**Comment by YesterdaysPromise** [comment]
> ok but how does it look ingame

hmh?

**Review by Ghommie — CHANGES_REQUESTED** [review]
You're accidentally removing quite a few icons from `floors.dmi`. You should totally check the icondiffbot in the checks tab and fix that.

The pattern alt metal hydrogen tiles looks a bit disconnected in the screenshot, which undermines the pleasant aesthetics... though, in hindsight, it may be simply because you haven't manually placed them "correctly". This bit is but a comment.

Furthermore, check the unit tests.

**Comment by Wallemations** [comment]
Metal hydrogen does _not_ look great tbh

**Pull request closed without merging**
