### PR TITLE
Removes door shocking from EMP's

### PR DESCRIPTION
**Pull request by Robustin**
1) Not intuitive to have a device that's supposed to disable electronics instead ramp-up the electric effects of nearby eletronics.

2) Bad design in general. We need EMP's to beat electronics, not turn them against us.

### CODE REVIEW

**Comment by GunHog** [comment]
Yep, another Robustin salt PR removing something that killed him.

**Comment by Robustin** [comment]
I haven't touched AOE-EMP in weeks kiddo. Was just thinking about how lings might make a comeback and remembered how incredibly shit EMP is.

**Comment by GunHog** [comment]
Heaven forbid screwing with the electronics have a risk to the antag. Of course, gloves are not hard to get (Pay 1TC for toolbox or steal gloves from the many sources). As for changelings, they have an anti-stun and healing ability - the risk to them is minimal. Besides, Changelings have a lot of actually significant problems, this is not one of them.

**Comment by Robustin** [comment]
If you have to buy items as a traitor to counteract the effects of one of your own traitor items, it's not good. The flashlight was cut from the EMP kit precisely because the kit is absolute trash.

**Comment by Dorsisdwarf** [comment]
You mean like buying a space suit to counteract the effects of bombing escape at ETA 00:10?

**Comment by Aloraydrel** [comment]
>EMP kit is trash

I dunno aoe emping big red meme borgs swarming on you seems pretty good. plus disabling headsets

**Comment by KazeEspada** [comment]
:+1:  Buffs EMPs so that the first option isn't to just emag everything.

**Comment by Robustin** [comment]
Going to close this until I sort out my fork commits and gobbledy goop, merge PR #15690 so I can start a new fork nerds.

**Pull request closed without merging**
