### PR TITLE
Electronic firing pins are now printable at a hacked autolathe.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
You can now craft basic firing pins under the security section of a hacked autolathe for 2000 metal and 500 glass.

## Why It's Good For The Game

There is currently no way to make normal firing pins and they can not be removed from guns without them breaking. Many weapons do not come pre-equipped with a firing pin when they are printed, requiring whoever wants to use that gun to acquire a mindshield implant and a mindshield firing pin.

## Changelog
:cl:
add: Electronic firing pins are now printable at a hacked autolathe.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Ahhh first PR

**Comment by wesoda25** [comment]
its so that you need to go through security in order to obtain your gamer guns

**Comment by ma44** [comment]
You can get 10 standard firing pins for 2000 points at cargo

**Comment by optimumtact** [comment]
there is no way on heaven or earth I want to *increase* the amount of weapons the crew currently has access to as non antags

**Comment by itseasytosee** [comment]
rip

**Pull request closed without merging**
