### PR TITLE
[READY] New portal textures.

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

@Nebulacrity made some portal sprites, and "convinced" _read forced_ me to pr em for em.

Here's a look:
PortalBlue
PortalOrange

Closer and slower [look](https://i.imgur.com/zwar2Kh.mp4)
## Why It's Good For The Game

Adds some nicer sprites for default portals, @Twaticus please evaluate.

## Changelog
:cl: LemonInTheDark, Heather Shadelight
imageadd: Changed some portal sprites, hope ya like em :)
/:cl:

### CODE REVIEW

**Comment by Nebulacrity** [comment]
::::)

**Comment by TheWiznard** [comment]
now you're thinking

**Comment by PKPenguin321** [comment]
we could grayscale these and have hand teleporters make randomly colored portals for added fun

**Comment by Nebulacrity** [comment]
Feel free to make a separate grayscale version when this gets in, but grayscale limits palettes and thus visuals too.

**Comment by LemonInTheDark** [comment]
....... One sec

**Comment by Nebulacrity** [comment]
Is Lemon actually gonna bother doing that? Come on, this was supposed to be just a simple texture update PR.

**Comment by LemonInTheDark** [comment]
Just takin a look at the idea, I don't intend to do anything else here

**Comment by LemonInTheDark** [comment]
Aight I've done some playing around, @PKPenguin321 it seems like you could do it, you'd need to make a colormap of the image, which isn't hard, the tricky bit is the well art, since you've gotta pick good combos, and generating it on the fly seems like it would be more bigbrain then I'm up for.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
