### PR TITLE
hopefully fixes the snow legion thing

### LINKED ISSUE #51335: Ice legion skull raises lavaland legions on contact with a dead body
tgStation Terry  EU   100% LAG FREE   New-Dedi  Fatguy Warehouse Theta 2020-05-27 202629
Issue reported from  Round ID: [138145](https://scrubby.melonmesa.com/round/138145) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1517

### PR DESCRIPTION
**Pull request by TotallyNotTimonk**
fixes #51335

note that i never got around to fix this because stupid byond compiler refused to cooperate

also point out any flaws if you want while i sleep
## Changelog
:cl:
fix: Nanotrasen Sensors indicate that Snow Legions are no longer unable to reproduce themselves.
/:cl:

### CODE REVIEW

**Comment by TotallyNotTimonk** [comment]
i HATE appveyor

**Comment by TotallyNotTimonk** [comment]
no i need sleep its 1.46am tomorrow is another day

**Comment by TotallyNotTimonk** [comment]
oh yes look at how dumb i am as i push a commit twice

**Comment by TotallyNotTimonk** [comment]
travis why

**Comment by TotallyNotTimonk** [comment]
i really dont know what to do anymore

**Comment by Kaffe-work** [comment]
now this is a journey into the deprivation of a coder

**Comment by Tharcoonvagh** [comment]
thank god it's not timonk, he never would have given up

**Pull request closed without merging**
