### PR TITLE
Boxstation Brig Mapping Changes

### PR DESCRIPTION
**Pull request by Steelpoint**
This is a split up of my prior PR (https://github.com/tgstation/tgstation/pull/41608), this PR focuses on the brig oriented changes. 

I'll be working on the other PR's that contain the rest of the mapping proposals. The idea is to avoid bogging PR changes with controversial changes. 

* Surgical tools in the 'prisoner transfer centre' are now inside a surgical dufflebag.

* Sergeant-at-Armsky has been posted to the armoury.

* External armoury now has a security camera placed there.

* HoS Office has been electrified and now has privacy shutters

* The oft unused 'cell 4' is now a communal holding cell (pic below)

* Security entrance now has a window in between the doors.

screenshot 2018-11-21 09 05 44
Security Entrance and Common Cell

:cl: Steelpoint
add: The Nanotrasen Corps of Engineers has begun a series of alterations to NTSS Boxstation, the first stage of changes were aimed at altering the Brig design, with minor improvements and alterations. 
/:cl:

### CODE REVIEW

**Comment by Steelpoint** [comment]
Fixing that travis

**Comment by Steelpoint** [comment]
Something is funky with this, I'll have to see what's going on.

**Comment by 81Denton** [comment]
Dream Maker snuck in some step_x and step_y, you just gotta replace them with pixel_x and pixel_y

**Comment by Steelpoint** [comment]
Ah, good observation

**Comment by Steelpoint** [comment]
Yes

**Review by ShizCalev — CHANGES_REQUESTED** [review]
How exactly do you enter the witness stand in the courtroom?

**Comment by Steelpoint** [comment]
I'll have to remedy that.

**Comment by ShizCalev** [comment]
image

**Comment by Steelpoint** [comment]
Should be good.

**Comment by ExcessiveUseOfCobblestone** [comment]
Witness stand?

**Comment by ShizCalev** [comment]
image

**Comment by Steelpoint** [comment]
As god intended.

I'll fix it up

**Comment by miniusAreas** [comment]
Is this still stale?

**Comment by Steelpoint** [comment]
Slipped away from me.

**Comment by Steelpoint** [comment]
Up to date.

**Comment by ExcessiveUseOfCobblestone** [comment]
That space above the witness chair is useless :(

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
There's an empty space above the witness chair. If it's 1tile then make the "cell" 1tile OR move the chair back to the black space.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'll fix this later if no one else does, not going to close this pr over a chair.

**Pull request merged**
