### PR TITLE
Adds ambience to the SM and portable generators

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: ninjanomnom
soundadd: Portable generators have a sound while active.
soundadd: The supermatter has a sound that scales with stored energy.
/:cl:

The sounds mid loop play randomly but here's an example of each:
https://puu.sh/y2zl8/6f9d23326c.ogg Supermatter
https://puu.sh/y2y0M/c5e75769b7.ogg Generator

### CODE REVIEW

**Comment by Jordie0608** [comment]
The supermatter is quite shrill, could it be reduced a bit?

**Comment by ninjanomnom** [comment]
the sound is scaled in game according to the power var and I tested the volume

**Comment by Jordie0608** [comment]
The volume doesn't stop it being high-pitched.

**Comment by WJohn** [comment]
Cool. Is the generator sound only for portable generators, or is it used for the turbine/TEG too?

**Comment by ShizCalev** [comment]
https://www.dropbox.com/sh/lcfdzg2l91mzmdb/AAAQlG91EiBqTL7bpEzGnISAa?dl=0

Corrected the fade in / out on the generator sounds to fix the crackling issue.

**Comment by ninjanomnom** [comment]
Only portable, the turbine and TEG should sound different and I'm probably going to end up doing a bigger TEG update on it's own

**Comment by ShizCalev** [comment]
If you have volume normalization turned on in Windows & an audio file ends or starts abruptly (ie doesn't fade in from/out to exactly 0db) it will crackle since it confuses the normalization algorithm due to the sudden spike. Since the files are intended to loop, you only have to worry about the end and start of the loop respectively in this case.

image
image

Just brought the very start/end of them to 0db.

**Pull request merged**
