### PR TITLE
Gives all borgs extinguishers

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

what title says, gives security and assault cyborgs extinguishers

## Why It's Good For The Game

lets security and assault borgs use slips to their advantage to get away from a bad situation, or to help with fighting a flashproof enemy for assault boys

## Changelog
:cl:
tweak: all borgs now have fire extinguishers
/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
Ion thrusters redundant now

**Comment by Shadowflame909** [comment]
fuck ion thrusters. They literally kill a bluespace battery in a minute

**Comment by PKPenguin321** [comment]
I really really hate how this just gives them a free jetpack and also a slip

**Comment by Fikou** [comment]
> I really really hate how this just gives them a free jetpack and also a slip

secborgs have a disabler (also admin only but eh)
assault borgs have a jetpack,

**Comment by PKPenguin321** [comment]
ok? youre giving this to every borg though

**Comment by Fikou** [comment]
> ok? youre giving this to every borg though

every other borg had an extinguisher

**Comment by PKPenguin321** [comment]
ah

**Comment by ATH1909** [comment]
These should be emergency fire extinguishers, not "proper" ones.

**Comment by Fikou** [comment]
> These should be emergency/"mini" fire extinguishers (/obj/item/extinguisher/mini), like what medical and clown borgs (and probably a few other borg types) have, not "proper" ones.

ok sure

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
