### PR TITLE
Resprites the implant pad for that one guy who demanded it

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Resprites the implant pad

old
case-export
case_g-export

new
bigs
bigg

## Why It's Good For The Game

You heard the man

## Changelog

:cl: Wallem
imageadd: Resprites the implant pad
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
nice.

**Review by Imaginos16 — APPROVED** [review]
Amazing.

**Comment by itseasytosee** [comment]
This actually adds soul I'm pretty sure

**Comment by cacogen** [comment]
This is an actual improvement on the sprite you're replacing! Congrats! I just hope you'll learn the lesson here and only replace sprites that need it in future, and preferably ones that are so old it's physically impossible for you to make them worse.

**Comment by necromanceranne** [comment]
> This is an actual improvement on the sprite you're replacing! Congrats! I just hope you'll learn the lesson here and only replace sprites that need it in future, and preferably ones that are so old it's physically impossible for you to make them worse.

Has anyone told you that you sound like the code equivalent of a Karen?

**Comment by Miczu555PL** [comment]
> This is an actual improvement on the sprite you're replacing! Congrats! I just hope you'll learn the lesson here and only replace sprites that need it in future, and preferably ones that are so old it's physically impossible for you to make them worse.

Damn, this is a roast not a compliment.

**Pull request merged**
