### PR TITLE
Tweaks to light fixtures' sprites

### PR DESCRIPTION
**Pull request by Sealed101**
## About The Pull Request

implements onule's edits to the new light fixtures' sprites and overlays

byeah

byeah

## Changelog

:cl: Onule
image: modified light fixtures' sprites and overlays to be more pronounced
/:cl:

### CODE REVIEW

**Comment by AdipemDragon** [comment]
nice
there's only 1 thing I don't like, which is the use of the lighter shade in the floor light's "corners", highlighted here in red 
image
it might look alright in regular gray iron floors but literally shown where it is, on wood? something feels off, makes it feel jagged, maybe due to it making shapes with the lighter shade it's connected to 
image

**Comment by lessthnthree** [comment]
One day, greyscale.

**Comment by Sealed101** [comment]
feedback (thanks @AdipemDragon) has been integrated (thanks Onule)

изображение

**Comment by Paxilmaniac** [comment]
image

**Comment by Likteer** [comment]
@Sealed101 Hello. 2 days since merge.
I am loving these. Thank you

**Comment by Sealed101** [comment]
please direct all your thanks to Onule

**Pull request merged**
