### PR TITLE
Atom/Destroy now operates on non-turf contents

### PR DESCRIPTION
**Pull request by Cyberboss**
NOTHING BAD HAPPENED DON'T TALK ABOUT IT

### CODE REVIEW

**Comment by Jalleo** [comment]
REDACTED REDACTED REDACTED 
:+1:

**Comment by Iamgoofball** [comment]
what if i dismantle a locker with someone in it

**Comment by optimumtact** [comment]
Like I said

**Comment by MrStonedOne** [comment]
Uhh, why would you put this here, in atom destroy, and override in turf destroy, when you could put this in atom/movable destroy?

**Comment by lzimann** [comment]
What MSO said

**Comment by Cyberboss** [comment]
WE ALREADY FUCKING DO THIS WHY DOES THIS HAPPEN TT https://github.com/tgstation/tgstation/blob/master/code/game/atoms_movable.dm#L170

**Comment by optimumtact** [comment]
lol

**Pull request closed without merging**
