### PR TITLE
I hear Okand quit, removes maps that aren't being maintained anymore

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

no point in keeping unmaintained maps around

### CODE REVIEW

**Comment by optimumtact** [comment]
:+1: unmaintained maps need to go

**Comment by jughu** [comment]
NO NOT DELTA EVERYTHING BUT DELTA

**Comment by MimicFaux** [comment]
I don't see metacide around much these days.

**Comment by jughu** [comment]
I cry

**Comment by jughu** [comment]
Why isnt there a :sob: emoji for reactions

**Comment by TehZombehz** [comment]
👍 It's a shame, these are both quality maps (though Omega needs work badly), but we can't leave any maps in that are out of the maintenance loop.

**Comment by optimumtact** [comment]
@MimicFaux meta is an actually finished and ready map

**Comment by jughu** [comment]
Cant somoene basically take it over and "finish" it and make a readd pr later

**Comment by dannno** [comment]
you could find someone to maintain them
it's not like it's DNA locked to Okand

**Comment by optimumtact** [comment]
This pr will sure dig them out of the wood work if they exist.

**Comment by dannno** [comment]
if anyone decides to maintain this;

add a fucking mass driver for fucks sake

**Comment by jughu** [comment]
I could maintain it i just wouldnt be very active mapping wise

**Comment by jughu** [comment]
Cant not let a qaulity map go to waste

**Comment by Anonmare** [comment]
Jesus Goof, do you kick down the doors of a place holding a Wake for the recently deceased and tell them to get off your property too? At least let someone else have a chance to claim the map, Ministation hung in the aether for a literal decade

**Comment by optimumtact** [comment]
they were in the codebase for far too long

**Comment by ChangelingRain** [comment]
MAPS ARE NOT DNA LOCKED TO CREATORS, CREATORS DO GET A SAY IN CHANGES BUT ONLY IF THEY HAPPEN TO BE AROUND
anyway this just an excuse for goof to not have to try and shove animal farm into two more maps and my response to that is 'get gud'

**Comment by Xhuis** [comment]
git*
casual

**Comment by Haevacht** [comment]
Tofa has been adding shit to delta tofa now delta maintainer.

**Comment by KorPhaeron** [comment]
Literally PRs open for both those maps

**Comment by Hatfish** [comment]
Just remove omega and readd mini

**Pull request closed without merging**
