### PR TITLE
Fixes unbuckling while dead

### LINKED ISSUE #12775: You can click the resist button to unbuckle out of a chair while dead.
What it says on the tin. Clicking on the action button or the chair won't unbuckle you, but clicking the resist button or typing in resist will.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes #12775

### CODE REVIEW

**Comment by Aranclanos** [comment]
adding if(stat) checks is something from three years ago, use the proper procs now.

**Comment by KorPhaeron** [comment]
Which proc is that?

**Comment by phil235** [comment]
The check should be done in /mob/living/verb/resist() instead, since it already handles similar checks.

**Comment by Aranclanos** [comment]
canusetopic but since you want people with handcuffs to use it, you'll have to be somewhat creative

**Comment by KorPhaeron** [comment]
There was already a check in resist(), but for some reason it only applied to grabs. I just moved it up a bit to apply to everything.

**Comment by KorPhaeron** [comment]
@Aranclanos

**Comment by Aranclanos** [comment]
canusetopic canusetopic canusetopic canusetopic canusetopic canusetopic canusetopic canusetopic canusetopic canusetopic canusetopic

**Comment by KorPhaeron** [comment]
Never touched that code in my life so I'll let someone else do it

**Pull request closed without merging**
