### PR TITLE
Adds a Minecraft reference to eggs

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Thrown eggs now have a 13% chance (roughly a 1/8 chance) to spawn a chick upon impact (provided that the egg is not caught, of course).

## Why It's Good For The Game

I was saddened to discover that this reference hadn't already been made, so I decided to add it in myself.

## Changelog
:cl: ATHATH
add: Thrown eggs now have a 13% chance (roughly a 1/8 chance) to spawn a chick upon impact (provided that the egg is not caught, of course).
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Just to check: there IS a cap for the number of cats, cows, chicks, etc. in the game, right? I know we have one for monkeys, and I think that there was one for the petsplosion event, but I'd like to be absolutely sure that people aren't going to flood the station with chicks to the point of lagging the game out or something like that.

**Comment by ATH1909** [comment]
There, I added a check to keep this from getting out of hand. Smashed eggs can only spawn up to 50 chickens per game.

**Comment by carlarctg** [comment]
up it to 64 and double the reference

**Comment by nicbn** [comment]
I think that chance is too high

**Comment by Fikou** [comment]
> I think that chance is too high

i never get chicks from eggs in minecraft its ok

**Comment by Yttriums** [comment]
Looking forward to growing perfect 'egg'plants and flooding the kitchen every round.

**Comment by fludd12** [comment]
Actually, if you could have it work similarly to the monkeycap and make it refund the cap when a chicken corpse is butchered, this makes for a nice "natural" method of meat production.

**Comment by ATH1909** [comment]
> Actually, if you could have it work similarly to the monkeycap and make it refund the cap when a chicken corpse is butchered, this makes for a nice "natural" method of meat production.

The problem here is that, like with chickens, the variable I'm using to count the number of thrown egg hatching is tied to the eggs themselves, so chicks can't access it. There's probably a really simple way around that, but I don't quite know exactly how to do it.

**Comment by fludd12** [comment]
> The problem here is that, like with chickens, the variable I'm using to count the number of thrown egg hatching is tied to the eggs themselves, so chicks can't access it.

>Also, you could butcher chicks that hatched "naturally" from non-thrown eggs to lower the thrown egg chick cap

It might be a bit difficult, but you could probably consolidate both systems into a global variable that keeps track of the number of chicks/chickens, and increments/decrements as these are created or destroyed.

Of course, if you don't want to do that, this is already an excellent change!

**Comment by bgobandit** [comment]
please jesus do not make another monkeycap, the existing one is bad enough

**Comment by kriskog** [comment]
What do you mean bgo, do you not enjoy it when the clown makes a gang of monkeys on station and you are no longer able to do xenobio?

**Comment by anconfuzedrock** [comment]
pro tip for minecraft gamers: you can rig up chickens with hoppers and dispensers to automatically shoot eggs at walls, spawning chicks. hook that up with some half slabs so when the chicks grow up they instantly die from lava bim boom bam cooked chicken feather farm fully automatic bold and self sufficient

**Pull request merged**
