### PR TITLE
Alternative Baton PR to #46065

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Completely removes pump up. In exchange adrenals have been buffed to get rid of more stamina damage upon activation (so that spam batonning isn't that big an issue or adrenal cucker anymore). Similar to #46065, stun batons apply a knockdown as opposed to paralyze, along with stamina damage. However, this PR applies an instant knockdown as opposed to delayed. The cooldown has been raised to 3 seconds, leaving the victim a larger amount of time to react (compensation for pump up removal). Police baton and its variants effectively mirror stun batons, but are weaker in both cooldown, knockdown time, and adrenal damage done. Borg stun arm has also been updated to be the same as stun batons. 

## Why It's Good For The Game

I've made my position pretty clear in #46053 and #46065. I'll still address any arguments though. 

## Changelog
:cl:
del: Removes pump up. This means no more ghetto counters to stun batons can be found, or created. Invest in adrenals if you wanna shrug off a baton!
balance: Stun batons, police batons, borg stun arms, and telescopic batons now deal stamina damage and instantly knockdown. Cooldowns have been added/extended for borg stun arms and stun batons.
balance: Adrenal implant now heals more stamina damage upon activation. 
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Right now I'm up to discussion for cooldown length, knockdown duration, and stamina damage healed by adrenals. I think these values are good, in testing they are at least, but am not certain they are the best they could possibly be.

**Comment by Fikou** [comment]
borgs dont have any shoving module, you sure that knockdown for stunarm is good?

**Comment by wesoda25** [comment]
> borgs dont have any shoving module, you sure that knockdown for stunarm is good?

Its simply updating a stun baton based weapon that was looked over in the original PR. I see no issue with it hard stun > knockdown so its not exactly OP or anything. Its just what batons do now.

**Comment by necromanceranne** [comment]
I feel engineering borgs kinda need something different entirely. It's always been really weird how the other borgs have thematic tools to their emag inventories but engineering and mining (kind of a subset of engineering) are just given a weird stun baton.

**Comment by Fikou** [comment]
> Its simply updating a stun baton based weapon that was looked over in the original PR. I see no issue with it hard stun > knockdown so its not exactly OP or anything. Its just what batons do now.

you can still shove a knocked down person as a human to stun them, you cant as a borg

**Comment by wesoda25** [comment]
> I feel engineering borgs kinda need something different entirely. It's always been really weird how the other borgs have thematic tools to their emag inventories but engineering and mining (kind of a subset of engineering) are just given a weird stun baton.

bro I have many issues with both borgs in general and engineering borgs specifically but all im trying to do here is maintain consistency for baton type weapons

**Comment by wesoda25** [comment]
> > Its simply updating a stun baton based weapon that was looked over in the original PR. I see no issue with it hard stun > knockdown so its not exactly OP or anything. Its just what batons do now.
> 
> you can still shove a knocked down person as a human to stun them, you cant as a borg

What? You can just stun again as borg to get them into stamina crit

**Comment by Fikou** [comment]
> What? You can just stun again as borg to get them into stamina crit

ok sshhh

**Comment by ExcessiveUseOfCobblestone** [comment]
I really want adrenals phased out rather than continuing to be a hardcounter to things that aren't even needing a hardcounter anymore.

**Comment by ExcessiveUseOfCobblestone** [comment]
Other than that though I might can get behind this PR.

**Comment by wesoda25** [comment]
> I really want adrenals phased out rather than continuing to be a hardcounter to things that aren't even needing a hardcounter anymore.

I get where you’re coming from but I still think they have a role in the game. Fortunately through the baton PR and taser removal PR, hard stuns are gone, meaning adrenals are no longer a necessity. However, since the weapons evolved into stamina damage, which can be stacked, a counter for a person trapped in stamina crit is necessary.

**Comment by ATH1909** [comment]
Honestly, I'm torn between your two PRs. Yours has the problem of removing pump up (a pretty cool chem), while Akrilla's PR has the issue of making the knockdown from stun batons be DELAYED.

**Comment by Akrilla** [comment]
Making ghetto chem more of a thing, or providing more of those sorts of combat augments is what this PR lacks. I want to see at least a little more depth than just "we have a baton that knocks down and does stamina damage". The interaction with pump-up at least for me is important, and the reason for the delay. 

I'm behind anything that's better for the overall game though - and most people have been against the chem stuff from the start, so it's up to maintainers I suppose to see what they're wanting.

**Comment by Akrilla** [comment]
> Honestly, I'm torn between your two PRs. Yours has the problem of removing pump up (a pretty cool chem), while Akrilla's PR has the issue of making the knockdown from stun batons be DELAYED.

Delay might be less important now with the knockdown (and in fact I shortened it in my PR),, perhaps an outright removal? I still feel that having a small window of time where you're standing is a good way of doing things, and also works well with the chem/other possible interactions in that time.

**Comment by wesoda25** [comment]
> Honestly, I'm torn between your two PRs. Yours has the problem of removing pump up (a pretty cool chem), while Akrilla's PR has the issue of making the knockdown from stun batons be DELAYED.

Just do what i did and make a new pr preserving the elements you like and removing those you dislike lol

**Comment by ATH1909** [comment]
> > Honestly, I'm torn between your two PRs. Yours has the problem of removing pump up (a pretty cool chem), while Akrilla's PR has the issue of making the knockdown from stun batons be DELAYED.
> 
> Delay might be less important now with the knockdown (and in fact I shortened it in my PR), perhaps an outright removal? I still feel that having a small window of time where you're standing is a good way of doing things, and also works well with the chem/other possible interactions in that time. I think I'm pretty open to changing this though.

Ironically, the small window of time before you get knocked down might be WORSE for the victim than just an instant knockdown, as if they react fast enough to get a weapon out but too slowly to (properly) use it before they fall down, they'll drop it.

In short, people can react while knocked down well enough already, and I think that a "grace period" might actually hurt them more than it'd help them.

**Comment by Akrilla** [comment]
I'll remove delay when I get home I think

**Comment by ExcessiveUseOfCobblestone** [comment]
> > I really want adrenals phased out rather than continuing to be a hardcounter to things that aren't even needing a hardcounter anymore.
> 
> I get where you’re coming from but I still think they have a role in the game. Fortunately through the baton PR and taser removal PR, hard stuns are gone, meaning adrenals are no longer a necessity. However, since the weapons evolved into stamina damage, which can be stacked, a counter for a person trapped in stamina crit is necessary.

No it's not.

I don't mind something that assist's in lowering stamina damage so you can tank more hits and get out of the slow faster, but you should never just de-facto 0 out stamina. Consequently, we shouldn't have anything that 1shots you with stamina damage.

Don't get shot multiple times if you don't want to get into stam.

**Comment by wesoda25** [comment]
When you say something that assists, you mean a traitor weapon, something as common as pump up, or a semi hard to make chem like meth?

**Comment by wesoda25** [comment]
that doesnt really make sense to me but I guess thats that. I just legit thought they would function much better with my changes, delayed knockdown seems strange to me and I tested this stuff and it was fun and left a counter, but whatever : (

**Pull request closed without merging**
