### PR TITLE
IceBox

### PR DESCRIPTION
**Pull request by san7890**
## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
awesome new map

**Comment by Kylerace** [comment]
this will never replace box station

**Comment by Imaginos16** [comment]
Quite honestly incredible

**Comment by san7890** [comment]
FUCK

**Comment by san7890** [comment]
This is properly done in #64055.

**Pull request closed without merging**
