### PR TITLE
Adds a new combat drug, Last Wish

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Added Last Wish, a new combat drug made from ghoul powder, ephedrine, and corazone, with strange reagent as catalyst.
add: This drug makes the user immune to crit and death, effectively making them shrug off any amount of damage. However, if it runs out (after it's been in the system for a bit) the user will instantly die. Prolonged use may result in unclonability or the body outright exploding into gore. Use with caution.
add: Prolonged use may also result in side effects of ramping severity due to the body's internal decay.
/:cl:

This drug can keep you up and running through anything (except gibbing, dusting, or other instakills) for up to five minutes before complete paralysis (and also beyond, if you have someone else keeping you supplied). It does not prevent conventional stuns and restraints, so all you have to do in return is keep them locked up until the drug expires.

Has potential uses for last-minute survival, blackmail, or a roaring rampage of revenge, especially if paired with bath salts or hulk for the antistun. The ingredients are fairly hard to obtain, so it shouldn't be abused easily, but it might make for some cool moments if someone manages to do so.

### CODE REVIEW

**Comment by swindly** [comment]
Last Wish in Odysseus new meta

**Comment by Ratvar** [comment]
Make it suck all blood and deal braindamage on death to prevent other methods of revival? Also makes it into "husking" fakeling poison.

**Comment by XDTM** [comment]
Husking will prevent drawing blood with #41819, and NOCLONE spreads to the brain unless the brain is implanted in a new body, which i consider fair game.

**Comment by Tlaltecuhtli** [comment]
what happens when you smoke it

**Comment by ExcessiveUseOfCobblestone** [comment]
first memento now last wish, why does xdtm keep dying???

**Comment by XDTM** [comment]
Don't forget zombies!

**Comment by Ratvar** [comment]
Would making people with robotic limbs ignore "stunned 5mins" debuff be balanced (and make vague sense, as your organic bodyparts collapse instead), as you need to do long surgery and EMP makes you nugget?
Can you walk around in bombsuit as gib machine?
Does it prevent dismembering, or "spear his legs off/throw spearnades" is the way to go?
Can changelings shrug off negatives?
Would it be funnier if overuse made you collapse into pile of dust someone else can scoop up and sniff for all last wish you had at the moment? Probably not, probably dumb

**Comment by XDTM** [comment]
Robotic Limbs: i don't think so, it's more like the nervous system finally collapses here. Robotic limbs shouldn't matter. Balance-wise it's the hard stop to prevent perma-last wishing, so i'd avoid common ways to get around it.
Bombsuit has no effect, you don't actually explode, just gib.
Does not prevent dismembering nor stuns so that's a viable counter.
Changelings suffer from all of the negatives, but can revive from death provided they do not reach the gib stage.
Dust is probably a bit too neat for a drug-induced complete organic failure.

**Comment by necromanceranne** [comment]
I'd be more concerned what you could do with this and slimepeople.

5 minutes of invulnerability per body? While huffing energized jelly along with it, which is basically stims for slimepeople that you can make in shop? Sign me the fuck up.

**Comment by SpookyWitch** [comment]
this is pretty cool, i'd go for it, 5 minutes of mass murder before the shuttle arrives and then becoming a vegetable.

**Comment by Cyprex** [comment]
If only there was a bug that resulted in on_mob_add being called, without calling on_mob_delete or on_mob_life...
Unless that was fixed in the last few months.

**Comment by Adanps** [comment]
One thing to note is that it will also be an instant death poison with a short delay if delivered at the right dose. Kinda like a beefier, but not stealthy amanitin.

**Comment by kingoftheautism** [comment]
You still need ghoul powder, corazone and ephedrine, and they are relatively hard to obtain, plus in small doses victims will be clonable

**Comment by XDTM** [comment]
4 units and 20 seconds, plus with the production cost it's justifiable to let such a poison be this deadly

**Comment by Tlaltecuhtli** [comment]
problem is someone making 15 u syringes of gib water and going on a killing spree

**Comment by davethwave** [comment]
15u wouldn't gib someone. You would merely die or get husked. And even if so, take some charcoal and you wouldn't be gibbed if your fast enough.

**Comment by swindly** [comment]
Remember to give yourself liver failure so that the last wish doesn't metabolize.

**Comment by davethwave** [comment]
How do you get/make corazone? Can't find anything on it in the Chem wiki.

**Comment by swindly** [comment]
https://tgstation13.org/wiki/Guide_to_chemistry#Corazone

**Comment by wesoda25** [comment]
Its luciferum but the withdrawal is more fun.

**Comment by Shadowflame909** [comment]
I'm more imagining the potential traitoring you can do with this. Put 0.1 units of this into a smoke machine or into pills labeled "Tricadorazine" and watch as people instantly collapse.

**Comment by XDTM** [comment]
that won't work, you need at least 20 seconds of continuous use to kill someone with it

**Comment by Shadowflame909** [comment]
How many units would you need for a 20 second death? You can tell me! You can yse5 botany to kill in 5!

**Comment by XDTM** [comment]
4, a bit more if you want to be sure

**Comment by XDTM** [comment]
it's worth noting that people killed with this can easily be revived with a defib unless they die after a significantly longer period.

**Comment by XDTM** [comment]
Before you close this, would it be acceptable if instead of nodeath it gave fast regeneration?

**Comment by optimumtact** [comment]
Im leaving it open to see if any other maintainers have an opinion.

**Comment by ExcessiveUseOfCobblestone** [comment]
What's the endgoal of this PR?

**Comment by XDTM** [comment]
Adding a new element in the toolbox of creative players allowing for potential interesting strategies or cool moments. 

Also since it requires several hard-to-get ingredients it serves as something to make for bragging rights even if unused, sorta like a phazon.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm personally okay with it if the OD is extremely low (I'm thinking like 5) so you HAVE to constantly dripfeed into your system (but not too dilute because then you'll die!), otherwise this just isn't going to be fun to deal with even considering it takes botany's help to make.

Part of me just wants to close this because our medical system is so braindead that we've resorted to adding "you literally cannot die" chems for doctors/chemist to strive towards. Kinda sad tbh.

**Comment by XDTM** [comment]
I'd say the opposite, we have different enough types of damage that an immortality chem does not in any way guarantee success. You can still break your arms and legs and be useless even if you cannot die. Or you can go with the zombie/ling treatment and outright behead/gib them. The slow from damage stacked with the slow from continued usage makes the user vulnerable to attacks, and the user can be hit by stuns and restrained until the drug runs out.

**Comment by XDTM** [comment]
Since the issues would persist even if it was converted into a healing chem, it's probably not salvageable then. I'll think of something else.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'll try to come up with some ideas as well.

**Pull request closed without merging**
