### PR TITLE
Changes F7 and F8 to more useful hotkeys for admins

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
tweak: Changed two admin hotkeys: f7 is now stealth-mode and f8 to toggle-build-mode-self.
/:cl:

~~i'm not sure if i was supposed to change skin.dmf like that so it has almost 1k changes...~~ 
byond is dumb

### CODE REVIEW

**Comment by PKPenguin321** [comment]
isnt there already a stealthmin key

**Comment by lzimann** [comment]
only a verb, f8 is invisimin, which sets your mob invisible(different from stealth-mode)

**Comment by Shadowlight213** [comment]
@lzimann not super sure if it's there, but could you make sure the stealth mode dialog box has a cancel button? Last I checked it didn't have one. Since it messes with your ghost name it could be annoying.

**Comment by lzimann** [comment]
it does have a cancel button, and if you want to restore your ghost name just delete yourself(not optimal but oh well, it has a solution at least).

**Comment by peoplearestrange** [comment]
Why the heck did you remove Invismin? Having an easy toggle button to go invisible is incredibly useful in game. Having a button for stealth min (as in ckey/adminwho verb) does not need to be a key.

**Comment by optimumtact** [comment]
PAS admits to powergaming with invisiblity

**Pull request merged**
