### PR TITLE
Revert "Dual wielding guns"

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Reverts tgstation/-tg-station#13831

While this is cool as hell, it is also completely, totally, and utterly unbalanced.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Wheres my controversy everyone said this would have controversy

**Comment by Thunder12345** [comment]
No

**Comment by KazeEspada** [comment]
A lot of guns need to be made two handers like laser rifles and kinetic accelerator. Possibly make third group of guns that are too heavy to shoot akimbo but light enough to just hold an offhand.

**Comment by WJohn** [comment]
I agree with more guns taking up multiple slots, we already have things like the ion gun, laser cannon, and shotguns which all need to fit on your back. Why not require two hands to fire them?

Perhaps having robo arms should allow you to fire them with one hand, too.

**Comment by KazeEspada** [comment]
Pistols, submacine guns, and wands are one handed. Rifles, staves (more for balance), machine guns, some large submachine guns, etc need to be two hands but not nessarily require an empty offhand.

**Comment by Fox-McCloud** [comment]
Yeahhhhh, I'm not shocked that this ended up problematic, especially when revolvers do 60 damage--it's an instantaneous one-shot crit.

**Comment by KorPhaeron** [comment]
Could make guns have spread when dual wielding

Could lock dual wielding to people with the right gear/var (DUALWIELDER)

Could restrict it to pistols only

Could make all humans have a dualwielder count (default 10 or whatever) and add up the dual_wield value of the guns in question (default for stetchkins is 5 or whatever), and if your two guns are over the dual wield limit you can't fire the second one. Adding robot limbs, special gloves, hardsuits?, etc would increase your dual wield limit, while RD could decrease the dual wield value of guns.

Or yeah just revert it and I'll come back to it eventually maybe, I mostly coded this as a thought exercise anyway

**Comment by Fox-McCloud** [comment]
@KorPhaeron 

Perhaps a dual-wielding implant that requires syndicate tech?

**Comment by Robustin** [comment]
Who the hell is dual wielding revolvers? 

I don't see the issue for most antags, the cost and hassle of keeping two firearms fully loaded is not that practical. 

On the other hand my biggest concern would be security running around like turbohitlers with dual wield lasers 3-shotting anything that moves without having to fret over ammo.

**Comment by KorPhaeron** [comment]
>On the other hand my biggest concern would be security running around like turbohitlers with dual wield lasers 3-shotting anything that moves without having to fret over ammo.

That's pretty much what happened yeah

**Comment by Cebasiz** [comment]
dual wield is cool

just make rifle+ sized weapons require two hands to shoot accurately ezpz solved

**Comment by Zilenan91** [comment]
Also blobs all died in 5 minutes because sec could burst down their special blobs like no other

**Comment by optimumtact** [comment]
:-1:

**Comment by TheNightingale** [comment]
If both weapons are Small or Tiny, allow dual-wielding. Otherwise, don't.
You can't fire two revolvers because only cowboys can do that, and you're not a cowboy, son. You -can- fire two Stetchkins or pulse pistols, though... or two meteor pens, if you're into that sort of thing.

**Comment by kevinz000** [comment]
NO.

**Comment by Anonus** [comment]
>kor breaks blob mode super fucking absolutely

Why, kor, why.

**Comment by LanCartwright** [comment]
kor i can't balance this without breaking arms and legs in terms of balance.

**Comment by MMMiracles** [comment]
it was a good idea in theory.

so was communism.

**Comment by Zilenan91** [comment]
this kills the xenos

**Comment by JJRcop** [comment]
i ded

**Pull request closed without merging**
