### PR TITLE
Replace most islist calls in components with length()

### PR DESCRIPTION
**Pull request by Cyberboss**
islist was used to check if a thing was

A. A list of things
B. 1 thing

length was profiled to be faster

### CODE REVIEW

**Comment by optimumtact** [comment]
what if it's not a list

**Comment by Cyberboss** [comment]
It returns 0

**Comment by MrStonedOne** [comment]
unless its a string

**Comment by Cyberboss** [comment]
Which it should never be or God help us all

**Comment by optimumtact** [comment]
how much faster

**Comment by optimumtact** [comment]
it would be even better to just refactor it to not require an islist call at all and then avoid all checks

**Comment by Cyberboss** [comment]
It was designed like this so components wouldn't create a large amount of unnecessary lists

**Comment by MrStonedOne** [comment]
Suppressing the truth! cyberboss trying to hide icon changes!

**Pull request merged**
