### PR TITLE
Applies the Felinid reaction to Hot Coco too because its inconsistent otherwise.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
Coco refactor to come later.

:cl: GuyonBroadway
fix: Turns out making chocolate hot or mixing it with milk does not make it any less lethal to cats.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
choco milk too

**Comment by GuyonBroadway** [comment]
done

**Comment by 81Denton** [comment]
@GuyonBroadway asked for permission in advance btw

**Review by 81Denton — APPROVED** [review]

**Comment by FloranOtten** [comment]
Finally, a felinid change that actually affects balance.

**Comment by Tharcoonvagh** [comment]
Chocolate cake?

**Comment by GuyonBroadway** [comment]
Chocolate cake should contain coco.

**Comment by PKPenguin321** [comment]
CHOCO flag for foods and reagents :V

**Comment by Ty-the-Smonk** [comment]
Felenid stealth nerfs are always accepted

**Comment by GuyonBroadway** [comment]
Ideally I'd code a proper allergies system but for now fuck felinids in particular.

**Pull request merged**
