### PR TITLE
Allows timed actions to be performed while drifting (Winter Thaw 2017)

### PR DESCRIPTION
**Pull request by ghost**
_This feature was created as part of the [Winter Thaw of 2017](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=9307) regardless of consensus or if it gets merged._

:cl: Xhuis
tweak: Some timed actions are no longer interrupted while drifting through space.
/:cl:

Video demo

Specifically, actions where the target is yourself or an object that you're holding aren't interrupted. You can't perform actions on other things while you're drifting.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
what if it is something you are pulling

**Comment by Xhuis** [comment]
Won't work.

**Comment by MrStonedOne** [comment]
This isn't a feature, its a bug it ever stopped working like that.

**Comment by Xhuis** [comment]
This was in the game originally? Neat.

**Comment by MrStonedOne** [comment]
Maybe not: #14187 it looks like i was rather limited in what i let it apply to.

**Comment by dannno** [comment]
Thanks man

**Comment by Cyberboss** [comment]
Does this work with do_mob and do_after_mob

Disclaimer: I don't know the difference between any of these procs

**Comment by Xhuis** [comment]
@Cyberboss I don't think so. `do_mob` checks if two mobs interact in some way.

**Comment by Haevacht** [comment]
do_after had code for space drift last I saw so yeah. This used to work, probably.

**Pull request merged**
