### PR TITLE
Stops Nintendo from Cease & Desisting our codebase.

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Removes content that would fall under copyright of Nintendo®™ and their intellectual property, a series named Metroid®™.

## Why It's Good For The Game

image

## Changelog
:cl:
imagedel: Removes content that would fall under copyright of Nintendo®™.
/:cl:

### CODE REVIEW

**Comment by MrPerson** [comment]
This shouldn't have a changelog. Changelogs are for players-facing changes and this sprite is unused.

**Comment by D4C-420** [comment]
>opens emails: sees pm-to-tgstation.
>opens email
>hears bwoink sound resonate in head
>hey got a moment and a few grand?

**Comment by Cyberboss** [comment]
Bait title

**Comment by optimumtact** [comment]
I don't like OP's image so I'm closing this PR for my mental sanity

**Pull request closed without merging**
