### PR TITLE
Removes Removes public autolathes.

### PR DESCRIPTION
**Pull request by carshalash**
Reverts tgstation/tgstation#41937

There are already greyshits murdering engineering over this.

### CODE REVIEW

**Comment by nicbn** [comment]
Removes Removes Removes public autolathes

Also this sounds like administration issue (murderboning or whatever)

**Comment by 4dplanner** [comment]
Greyshirt-led game design

**Comment by Teepeepee** [comment]
just ban them if not antag or escalation lmao

**Comment by tuypo1** [comment]
It should be reverted but not because of greyshirts.
Also yeah the caps locker should probably be wrenched down.

**Comment by Tlaltecuhtli** [comment]
how will a wrench prevent anything? idea: hitting stuff with plasteel means things need to be unwelded before moving/deconstructing, like reinforced doors do

**Comment by subject217** [comment]
Anyone who breaks into the Captain's office has a full set of tools. Making the Captain's locker anchored solves literally nothing. The only reason Rock even mentioned it is because he used it to make a shitty straw man argument.

**Comment by imsxz** [comment]
why dont we just remove assistants since all of them are just gonna suicide or be useless anyways? for QOL, ya know.

**Comment by Cyberboss** [comment]
I like watching the world burn

**Comment by carshalash** [comment]
Greytide thrown in the sm it is then!

**Comment by miniusAreas** [comment]
AAAAAAA

On Dec 25, 2018 7:52 PM, "carshalash" <notifications@github.com> wrote:

Greytide thrown in the sm it is then!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/42068#issuecomment-449882395>,
or mute the thread

**Pull request closed without merging**
