### PR TITLE
stylistic alterations of galoshes icons

### PR DESCRIPTION
**Pull request by Chlorotrifluoride**
## About The Pull Request
updates the galoshes icons to make them stylistically similar to the work boots and jackboots, with the palate of the insulated gloves. also similarly modified the absorbent galoshes, but used color palate of the purple hat.
this includes the item's inventory icon, the worn icon and the in hand icons.

## Why It's Good For The Game

it is much more aesthetically pleasing than the flat shaded, neon curry colored ones. also, it makes me feel pretty when I wear them with insulated gloves on.
image

## Changelog

:cl:

imageadd: added prettier icons for the normal and absorbent galoshes

/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
what's up with the other two sprite changes
image

**Comment by Chlorotrifluoride** [comment]
> what's up with the other two sprite changes image

I honestly have no clue, I wasn't even aware they where altered. can you delete those changes?

**Comment by Chlorotrifluoride** [comment]
alright, I removed the two other changes. I must have copied them from the wrong repository. woops.

**Comment by VladinXXV** [comment]
> how did you get that comparative view?

https://github.com/tgstation/tgstation/pull/73688/checks?check_run_id=11642670155

Include absorbent galoshes picture in PR body please? Long overdue, good PR.

**Comment by Chlorotrifluoride** [comment]
> Include absorbent galoshes picture in PR body please? Long overdue, good PR.

ah, good point. and thanks! 
I want to clean up a bunch of the older looking sprites (especially the mundane ones) to bring them up to par with some of the newer ones. this PR is hopefully just the start.

**Review by Imaginos16 — APPROVED** [review]
Looks perfect!

**Pull request merged**
