### PR TITLE
amogus

### PR DESCRIPTION
**Pull request by dexmoh**
## About The Pull Request
amogus

## Why It's Good For The Game
https://youtu.be/_UmvTeeJtno

## Changelog
:cl: Dex
soundadd: amogus
/:cl:

### CODE REVIEW

**Comment by ArcaneDefence** [comment]
repost of bababooey https://github.com/tgstation/tgstation/pull/51466

**Comment by MrMelbert** [comment]
actionninja bait?

**Comment by Rohesie** [comment]
Sus.

**Comment by Capsandi** [comment]
babafooey

**Comment by CoffeeDragon16** [comment]
bring this back for April fools I beg

**Pull request closed without merging**
