### PR TITLE
Makes assembly tank bombs not have devastation

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

Makes em not have devastation

## Why It's Good For The Game

gibbing people with easy to massproduce explosives is pretty shitty

## Changelog
:cl:
balance: Tank Assembly Bombs now dont have devastation
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Brother if you want me to not just instaclose something could you please like, justify it 
I get that you don't trust me to take your attempts seriously but just throwing up a pr without anything past "this thing sucks lets make it unused" doesn't help the case you're trying to make, outside of convince me that people are (perhaps over) using these things now, instead of the forgotten uselessness they sat in before

**Comment by mc-oofert** [comment]
> Brother if you want me to not just instaclose something could you please like, justify it I get that you don't trust me to take your attempts seriously but just throwing up a pr without anything past "this thing sucks lets make it unused" doesn't help the case you're trying to make, outside of convince me that people are (perhaps over) using these things now, instead of the forgotten uselessness they sat in before

with a bit of a gamble you can instakill someone or take at best 9 seconds

**Comment by Jackal-boop** [comment]
Just tweak the explosion sizes if you really hate Single tanks. Giving them a chance to not explode is fucking stupid.

**Comment by Jackal-boop** [comment]
Also atmos stuff shouldn't be randomized period

**Comment by rageguy505** [comment]
The random fuse is fine if you wanna nerf its use as a grenade you toss. It still works as a bomb for a mass bombing/abandoned duffle bag bomb.

**Comment by NamelessFairy** [comment]
This feels a bit too overkill to me, while I'm not a fan on randomness mechanics for antagonist items this feels less like making an item more RNG based and ore just making it more consistently worse. in 11/12 cases the new tank bombs would be worse than the existing ones due to the increase of the standard time from 1 to 1.5 seconds, depending on the usecase even the instant detonation could be bad. Also, having the selected time reroll every time a signal is sent seems dumb, it should probably be set on construction so duds remain duds until remade.

**Comment by mc-oofert** [comment]
atmos mains strike again

**Comment by mc-oofert** [comment]
yeah actually second thought

> Just tweak the explosion sizes if you really hate Single tanks. Giving them a chance to not explode is fucking stupid.

**Comment by mc-oofert** [comment]
actually

**Comment by Jackal-boop** [comment]
> atmos mains strike again

Take a break man. Your clearly mad at the game

**Comment by moocowswag** [comment]
> with a bit of a gamble you can instakill someone or take at worst 5 seconds

or you can just use pot water nades, i think youre just targeting a flavor of the month thing.

**Comment by KittyNoodle** [comment]
> gibbing people with easy to massproduce explosives is pretty shitty

grenades

**Comment by KittyNoodle** [comment]
Allow me to quote a rule I think applies here: 

> Your character will frequently die, sometimes without even a possibility of avoiding it. Events will often be out of your control. No matter how good or prepared you are, sometimes you just lose.

Every single department has some way of “mass producing” bombs, be it chemistry with n20 grenades to botany with whatever bullshit they concocted today. It’s always been possible to create methods to make devastation level explosives and depending on the knowledge/willpower of the player, to mass produce them.    If you take away one method to make (honestly tame) bombs, people who have a desire to make them will still do it, just through other methods. If you were to follow the logical end point of this you would end up removing all non-antagonist methods of making effective bombs, which incidentally prevents actual antagonists from being creative and working outside of their provided toolset to do objectives/whatever they feel like doing instread of using minibombs and other (traitor only) explosives. If someone is greifing with singletanks, it’s an administrative issue, not a code issue.

**Comment by mc-oofert** [comment]
bro you fuckers are shifty as hell one of you just said to nerf the explosion range and yall are still complaining

**Comment by Jackal-boop** [comment]
Nades, gibtonite, high cap welders, bluespace cell, botany. All of this stuff can produce heavily devastating explosions, why are you removing them from single tanks

**Comment by Livrah** [comment]
I wanted to say something reasonable, but I can aswell just copypaste from prev PR comments.

**Comment by moocowswag** [comment]
> bluespace cell with plasma dont gib

We will see about that baby girl

**Comment by BlueMemesauce** [comment]
Since there's all these soruces to make gibbing bombs, perhaps a better solution would be to allow wizards and nuke ops to have a defense against bombs? These bombs need to be removed because as soon as a loud antag gets annouced, atmos and other departments are given full permission to mass produce as many bombs as they want. Bombs are really shit to fight against as nuke ops, you're supposed to have a massive advantage over the crew yet they can mass produce bombs that are more powerful than your mini bombs! They suck for wizards too, but they technically teleport away if they see like 2 pixels of an assembly sprite in a guys hands. It's just bad for the loud antagonists and the game to have bombs able to be mass produced by the crew.

**Comment by moocowswag** [comment]
Currently the best counter to bombs is just staying mobile, something wizards already should have already and are usually punished in other ways if they dont have mobility spells.

Although nukies do not have explicit access to mobility they have counters to other things that would abuse this shortcoming (shielded modsuit + desword, anti slips, being a relatively decent size team antag, decent access to explosives of their own for indirect damage/kills)

Although none of these things really help against explosives (except for being a decent sized team) they do a lot against stuff that would abuse someone who lacks mobility.

**Comment by Jackal-boop** [comment]
> Since there's all these soruces to make gibbing These bombs need to be removed because as soon as a loud antag gets annouced, atmos and other departments are given full permission to mass produce as many bombs as they want. Bombs are really shit to fight against as nuke ops, you're supposed to have a massive advantage over the crew yet they can mass produce bombs that are more powerful than your mini bombs! They suck for wizards too, but they technically teleport away if they see like 2 pixels of an assembly sprite in a guys hands. It's just bad for the loud antagonists and the game to have bombs able to be mass produced by the crew.
> 
> bombs, perhaps a better solution would be to allow wizards and nuke ops to have a defense against bombs? Otherwise players are just going to move on to a new source of mass produced bombs that they can use against antags and the problem won't be fully solved.

if players are immidetely preparing for a threat not facing them with heavy ordanance, you should ahelp, this isnt a code issue

**Comment by mc-oofert** [comment]
> > Since there's all these soruces to make gibbing These bombs need to be removed because as soon as a loud antag gets annouced, atmos and other departments are given full permission to mass produce as many bombs as they want. Bombs are really shit to fight against as nuke ops, you're supposed to have a massive advantage over the crew yet they can mass produce bombs that are more powerful than your mini bombs! They suck for wizards too, but they technically teleport away if they see like 2 pixels of an assembly sprite in a guys hands. It's just bad for the loud antagonists and the game to have bombs able to be mass produced by the crew.
> > bombs, perhaps a better solution would be to allow wizards and nuke ops to have a defense against bombs? Otherwise players are just going to move on to a new source of mass produced bombs that they can use against antags and the problem won't be fully solved.
> 
> if players are immidetely preparing for a threat not facing them with heavy ordanance, you should ahelp, this isnt a code issue

as if admins are ever on

**Comment by moocowswag** [comment]
> bluespace cell with plasma dont gib
hyper cell, 0/2/5, bs cell 0/3/6,  crossbreed slimecore cell, 0/3/7

they dont gib but they certainly did oneshot everything in the heavy radius.

**Comment by Jackal-boop** [comment]
oil slime extracts can gib people if they have them on their person. i watched a scientist use them to win a revolution

**Comment by BlueMemesauce** [comment]
> if players are immidetely preparing for a threat not facing them with heavy ordanance, you should ahelp, this isnt a code issue

Nuke ops and wizards do face them with heavy ordanance, gearing up against those is pretty much allowed on all the servers

**Comment by Jackal-boop** [comment]
> > if players are immidetely preparing for a threat not facing them with heavy ordanance, you should ahelp, this isnt a code issue
> 
> Nuke ops and wizards do face them with heavy ordanance, gearing up against those is pretty much allowed on all the servers

Thought you were talking about traitors and heretics. If you as a wizard or op die to a single tank that's a skill issue

**Comment by BlueMemesauce** [comment]
But if you actually read my post you would see that wizards and nuke ops don't have much chance to fight against it either. Wizards just have to hope that they teleport around enough that they won't get hit by a bomb and nuke ops just have to use their numbers and hope they don't all die to bombs.

**Comment by Jackal-boop** [comment]
This is a flavor of the month thing. Wait a week and you'll see much less single tanks being used because the people abusing them got banned or bored

**Comment by mc-oofert** [comment]
> This is a flavor of the month thing. Wait a week

im reopening in a week

**Pull request closed without merging**
