### PR TITLE
Reverse bear trap resprite

### PR DESCRIPTION
**Pull request by Greniza**
## About The Pull Request

Full resprite of the reverse bear trap, including an animated sprite when the reverse bear trap is equipped and proper inhand sprites.

## Why It's Good For The Game

This monstrosity is the old reverse bear trap sprite. It appears to be a compressed .PNG file, which not only breaks from the game's artstyle, but also just generally looks bad.
reverse_bear_trap_old

This is what, if this PR goes through, will be replacing it. When active on a victim's head, the yellowish clock is animated, and ticks once per second (under current configuration, which can be changed by following the instructions in the comment in the new update_overlays() function).
image

The worn sprites were revamped to match the color scheme and style of the new sprite, and inhands were properly added (it was set to rack_parts before).

## Changelog
:cl:
imageadd: added new icons for reverse bear trap: inhand, worn, and item icons.
imageadd: added minor animation to the reverse bear trap sprite
imageadd: added update_overlays() function to /obj/item/reverse_bear_trap/
imagedel: deleted old icons for reverse bear trap.
/:cl:

note: I'm not 100% certain that my update_overlays() is properly implemented. check before merging.

### CODE REVIEW

**Comment by Greniza** [comment]
^ removes a colon which was causing a linter to fail.

**Comment by maxymax13** [comment]
still can't tell what the fuck it's supposed to be

**Comment by Greniza** [comment]
> still can't tell what the fuck it's supposed to be

if you don't know what a reverse bear trap is, you won't really recognize it. it's in saw 2, I think

**Comment by tommysalami3** [comment]
Even if you dont like the new sprite literally anything is better than the old. You could replace the old sprite with an animated png of the Chuck E Cheese logo spinning and it would be better.

**Comment by Greniza** [comment]
> Even if you dont like the new sprite literally anything is better than the old. You could replace the old sprite with an animated png of the Chuck E Cheese logo spinning and it would be better.

I mean, I _tried_ to make it decent

**Comment by Greniza** [comment]
For reference:

New inhand from front:
image

Old inhand from front:
image

**Comment by Fikou** [comment]
it looks better for everything except the equipment sprite, even that old crusty jpg was readable, this is really hard to read

**Comment by Greniza** [comment]
> it looks better for everything except the equipment sprite, even that old crusty jpg was readable, this is really hard to read

@Fikou Is it more readable with a dark background?
image

**Comment by OceanFish1** [comment]
Totally agree current icon state of reverse bear trap looks like shit and needs a replacement

**Review by Twaticus — CHANGES_REQUESTED** [review]
/clothing/head: right/left directionals offset
/inhands/items_lefthand: back directional covers body
/inhands/items_righthand: back directional covers body

**Comment by Greniza** [comment]
god, resolving merge problems in sprite files is literal hell...

**Review by LemonInTheDark — APPROVED** [review]
code's fine

**Comment by Twaticus** [comment]
looks good just gotta fix the deleted icons

**Comment by Greniza** [comment]
> looks good just gotta fix the deleted icons

Which ones?

**Comment by Greniza** [comment]
...I don't understand... It's not pulling the sprites downstream properly...

**Comment by Greniza** [comment]
I don't know what I'm doing...

**Comment by Greniza** [comment]
And there we are! We are done. I think. I hope.

**Pull request merged**
