### PR TITLE
Restores security bombsuit & white bombsuit

### LINKED ISSUE #28971: A bunch of suit sprites are broken
so far I found that the paper mache wizard robes are broken, so are a few of the lesser used chameleon gear armor items.

### PR DESCRIPTION
**Pull request by ShizCalev**
🆑 ShizCalev
imageadd: The security bombsuit's sprite has been updated!
/🆑

The security bombsuit's sprite was deleted by accident back in 2013 and nobody noticed. This restores with with an updated sprite.

Also restores the white bombsuit variant (which could be used for the RD or something, since it fits his color scheme.) It's sprites were never actually deleted, it was just removed from the code.

Closes #28971

Also fixes hair sticking through the bombsuit helmet.

image

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by WJohn** [comment]
Huh. Nice catch. Can't say I'm huge on the color scheme, though. A muddy red/brown looks kind of ugly.

**Comment by ShizCalev** [comment]
image

**Comment by ShizCalev** [comment]
@WJohn How's that feel?

**Comment by WJohn** [comment]
Much much better like that! 👍

**Review by WJohn — APPROVED** [review]

**Pull request merged**
