### PR TITLE
you can now make extendohands with a right and left arm

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

what the title says, for some reason we dont have recipes where you can choose between 2 ingredients so its 2 separate recipes

## Why It's Good For The Game

its really dumb that you specifically need a right to create this

## Changelog
:cl:
add: you can now make extendohands with a right and left arm
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
powercreep

**Comment by Drackzo** [comment]
Over the counter cqc go brrr

**Comment by ArcaneMusic** [comment]
This is also an issue with the crafting menu and simple robots, where they all only accept one type of arm. Crafting menu datums should probably be able to accept a list of potential parts for a single recipe part, but this works for this issue.

**Comment by brotherbeyondd** [comment]
It's because left isn't right.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
