### PR TITLE
Fixed a missed case of renaming `notify_ghost_cloning`

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request

@distributivgesetz You forgot to rename this in #80096. I'm so confused how did the all the tests pass?. I literarily can't compile my code without this change so somebody please speed merge

## Changelog
N/A

### CODE REVIEW

**Comment by distributivgesetz** [comment]
Semantic conflict? Wtf

**Comment by SyncIt21** [comment]
Actually the tests did fail after it got merged???
Screenshot (364)
Github moment

**Comment by distributivgesetz** [comment]
https://github.com/tgstation/tgstation/commit/835ca9200792b54481da1ddfc21b975c6e263e48 yup, semantic conflict

**Comment by distributivgesetz** [comment]
cc @ZephyrTFA

**Pull request merged**
