### PR TITLE
Adds binds for targeting the eyes and mouth

### PR DESCRIPTION
**Pull request by CoffeeDragon16**
## About The Pull Request

Having all of the targeting hotkeys target one area each while having only the head cycle through 3 others, while having none for eyes or mouth, is unintuitive. This gets helps make that more concise, changing there to be 2 new binds, one for the eyes and mouth. This leaves the cycle head bind unchanged. Also adds descriptions for the hotkeys.

## Why It's Good For The Game

Makes more sense, and is faster and easier to use, while not harming the experience of those who prefer the old cycle head.

## Changelog
:cl:
tweak: Two new binds for targeting eyes and mouth, number pad 7 and number pad 9.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
why not both 👀

**Comment by CoffeeDragon16** [comment]
I think keeping the original cycle bind would just be even more confusing when you have the individual targeting binds, no?

**Comment by ShadeAware** [comment]
This is just adding more buttons for the sake of adding more buttons. If anything, this is far more confusing than the previous system, which was nice, compact and intuitive.

**Comment by CoffeeDragon16** [comment]
Good to hear the feedback, I'll keep the head swap bind, as it would functionally work the same as my intent, unless you want to use the old way. Will do tomorrow or so, though.

**Comment by Jared-Fogle** [comment]
You don't need to have both bound automatically, you can keep the current cycle but have the option to rebind it to those keys specifically.

**Comment by CoffeeDragon16** [comment]
I think it would be clearer for new players, and I don't see a reason why not to have it there. And, I went and fixed those issues. Cycle head now has no changes, and the PR is simply now the addition of two new binds, I'll change the PR description to update that.

**Comment by Tlaltecuhtli** [comment]
there is no keybind for specific targetting of the  head (only the cycle one)

**Comment by CoffeeDragon16** [comment]
Cycle head will always start targeting the head. This means that it can as a specific target head, save for if you want to cycle with it.

**Comment by LemonInTheDark** [comment]
@Jared-Fogle you got any thoughts on this?

**Comment by Jared-Fogle** [comment]
Not really one way or the other.

**Pull request merged**
