### PR TITLE
Removes lavaland

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Until the network lag is fixed, because it's literally unplayable right now.

### CODE REVIEW

**Comment by TrustyGun** [comment]
I don't really get it. The asteroid will be JUST as unplayable, but more boring.

**Comment by RandomMarine** [comment]
:finnadie: RIP Lavaland :finnadie:

**Comment by MMMiracles** [comment]
pls no

the only difference this'd make is instead of being laggy and dead, is that it'd be laggy and boring.

**Comment by PKPenguin321** [comment]
:(

**Comment by KorPhaeron** [comment]
Asteroid has a safe zone, slower goliaths, and less mobs in general

**Comment by PKPenguin321** [comment]
:::(((

**Comment by RemieRichards** [comment]
People want lavaland to have a little bit of a safer zone anyway, so just add that now and people can chill there during the lag.

Other parts of the game must be just as infuriating as lavaland with the lag, are we removing those? No we're not.

**Comment by TechnoAlchemisto** [comment]
remove antags because i can't fight against them with this lag

**Comment by Razharas** [comment]
What is lagging in lavaland even?
@KorPhaeron

**Comment by RandomMarine** [comment]
@Razharas The servers have been fucked with regular disconnects and latency issues up the ass.
Miners keep getting fucked by ash storms and the like during these.

**Comment by KorPhaeron** [comment]
I don't need this open to testmerge it anyway you guys can't stop me

**Pull request closed without merging**
