### PR TITLE
Revert "Removed anti-drop implant from NukeOps uplink."

### PR DESCRIPTION
**Pull request by Thunder12345**
Reverts tgstation/-tg-station#10826
Can we really not stop making undeclared changes?

### CODE REVIEW

**Comment by optimumtact** [comment]
:+1: all changes should be declared or no merge

**Comment by Thunder12345** [comment]
And if a lazy maintainer (Miauw) doesn't notice, a revert

**Comment by xxalpha** [comment]
lol is this serious

**Comment by Lumipharon** [comment]
The pr made 2 changes.
1) Removed no drops, which horribly break nuke op balance.
2) Decrease the cost of the nutriment implant, which has literally zero use to a nuke op unless they are planning to be on station for an hour.

Why the fuck did you revert instead of just undoing the nutriment change, or better yet, just removing the nutriment implant from ops too?

**Comment by optimumtact** [comment]
because we're not gonna do the pr creators work for them

**Pull request merged**
