### PR TITLE
Multi-Z International Space Station

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Adds a votable map to rotation, which is more or less a recreation of the real life international space station, including no gravity and three z-levels.

The top level:
image
The middle level:
image
The bottom level:
image

It also comes with three new shuttles to fit the international space station theme:
A SpaceX Cargo Dragon themed cargo shuttle:
image
A mining shuttle themed after the Boeing Starliner:
image
And finally, the evac shuttle(s), two Soyuz capsule themed escape pods, which make up the entire evacuation ability of the station:
image

## Why It's Good For The Game
It absolutely is not

## Changelog
:cl:
add: multi-z international space station map, gravity sold separately
add: three new shuttles to fit the iss theme
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
You have doomed me to never be able to update my own pr again

**Comment by Mothblocks** [comment]
my last sentence in that comment shouldve clued you in that its still possible but it also would apepar that i was actually just wrong

**Comment by Mothblocks** [comment]
paxil gets one reopen for this

**Comment by MrDoomBringer** [comment]
>one

**Comment by Mothblocks** [comment]
one from me anyway

**Comment by NanoCats** [comment]
Replace Metastation with this for variety

**Pull request closed without merging**
