### PR TITLE
Changes lower action icons to be text based

### PR DESCRIPTION
**Pull request by nicbn**
:cl:
imageadd: Changed the drop, throw, pull and resist icons.
/:cl:

Old:

image

New:

mainb

It's hard for new players to understand what the old icons mean, so this is better to them.
Text is easier and cleaner, and most veteran players use hotkeys anyways.

### CODE REVIEW

**Comment by lzimann** [comment]
post the picture of the other huds aswell please

**Comment by nicbn** [comment]
plasma
slimecore
clock
op

**Comment by ChangelingRain** [comment]
You missed some of the small details on the clockwork one, so here's fixed versions http://puu.sh/xQcCt/96307b4f2e.dmi

**Comment by JJRcop** [comment]
Did you check that this works for drones as well?

**Comment by WJohn** [comment]
Sure. Better UI is something I can always get behind.

**Comment by Bawhoppen** [comment]
Probably should change the dragging and resist too then.

**Comment by nicbn** [comment]
> Probably should change the dragging and resist too then.

Will do in another PR

**Comment by nicbn** [comment]
> Probably should change the dragging and resist too then.

OK, I'll do this

**Comment by nicbn** [comment]
New icons for alternative uis:

newicons

**Comment by ChangelingRain** [comment]
Whoop, I messed up on the selection border so here's some fixed icons for that http://puu.sh/xQKEk/74be51b73b.dmi

**Comment by Cyberboss** [comment]
Have you tried clicking them? I'm just surprised this was doable without touching any .dm files

**Comment by nicbn** [comment]
The click collision checks for the icon collision box. It works just fine.

**Pull request merged**
