### PR TITLE
Changes closet_open.ogg and closet_close.ogg to something much better

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

Vastly improves the metal closet open and close sounds using sounds created by @actioninja.

Not a knock on the original PR creator as new sound effects are always great and it's very hard to find decent free, creative commons sound effects. Most of us don't have the equipment or know-how to create our own.
### Old
[Open](https://sndup.net/2gr4/closet_open_old.ogg)
[Close](https://sndup.net/33bf/closet_close_old.ogg)

### New
[Open](https://sndup.net/974y/closet_open.ogg)
[Close](https://sndup.net/7y4c/closet_close.ogg)

## Why It's Good For The Game
I've seen players in OOC complain about some of the new container opening sounds and these are a great improvement to the metal locker ones

## Changelog
:cl: actionninja and cacogen
soundadd: Metal closet open and close sounds changed to great sounds created by actionninja
/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
Could you change the close sound as well so that it matches?

**Comment by cacogen** [comment]
They match fairly well. Your closing sound is better than the one I was planning on using from the effect I sampled so I decided to leave it as it is.

**Comment by ninjanomnom** [comment]
I dont see how this is related

**Comment by actioninja** [comment]
I don't like merging stuff that has things I worked on in it for obvious implication reasons but nobody else likes touching sounds.

**Pull request merged**
