### PR TITLE
Drake swooping is smoother and more dangerous

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Ash Drake swoops no longer teleport the Ash Drake to your position.
balance: Some other tweaks to Ash Drake attacks and patterns; discover these yourself!
/:cl:

Swoop spam is veeeery frustrating because that's often all it'll do, but not actually particularly dangerous most of the time.

So, changes:
For a very small period when the drake starts a swoop, it's still vulnerable to damage.
The drake will no longer produce "was hit" messages if it didn't take damage.
Swooping actually physically moves the drake; it will chase you the fuck down and has a visible shadow.
The drake will immediately try to slam down on you when it reaches you, instead of after a set time, but it slamming down is MUCH faster.
The drake will no longer use the rain fire ability while busy swooping, and the swoop that would automatically cause the drake to rain fire as it landed now causes it to breathe fire during the swoop.
Fire rain is now centered on you and can no longer knock you out, but will set you on fire and do enough damage to immediately slow you.
The visuals for swooping and fire rain are improved and should be more accurate, timingwise.

### CODE REVIEW

**Comment by Repukan** [comment]
Can you nerf the advanced plasma cutters too please.

**Comment by ChangelingRain** [comment]
Maybe but not in this PR

**Comment by Repukan** [comment]
Based

**Comment by KorPhaeron** [comment]
Do you have a webm or something of the new attack

**Comment by Repukan** [comment]
How does this affect player drakes?

**Comment by ChangelingRain** [comment]
Player drakes will do the fire breath swoop, which I will have a video of.... probably tomorrow, given the upload speed.

**Comment by ChangelingRain** [comment]
Actually today, what a surprise.
https://puu.sh/vvkUU/e9c1ac65fa.mp4
Speed is easy to tune, by the way.

**Comment by Repukan** [comment]
Awesome, make it a bit faster though

**Comment by ShadowDeath6** [comment]
could you make the shadow a big oval, since realistically the dragon wouldn't be flying sideways over you

on the other hand... what's causing the drake to cast the shadow in the first place?

**Comment by Thunder12345** [comment]
The lava

**Comment by Core0verload** [comment]
Looks like slowdowns are now even deadlier. I wish getting one in a boss fight wouldn't be a quick death.

**Comment by ChangelingRain** [comment]
It's not really practical to make slowdowns not deadly, as mechanics that don't involve dodging aren't really easy to do.

Also an oval shadow would be more realistic but I don't have a sprite for it and this looks pretty good as-is.

**Comment by Kromgar** [comment]
Man sure wish miners had stims so that slow down wouldnt be instadeath

**Comment by Repukan** [comment]
Why do you worry about slowdowns if you just use double advanced laser cutters to shoot them a screen away lmao

**Comment by Robustin** [comment]
I overall think this is a better mechanic, I think its important that:

1) The first "tier" of slowdowns not be lethal under this PR. Shit happens and I already think megafauna fights are a little too punishing for injured players. Currently you can dodge swoops with moderate injuries, I hope that doesn't change here. 

2) The chain fireball while its swooping is just kind of meh. It looks a little silly. Ideally it would be a new attack like a fire "breath" instead of a fireball, and the fire wouldn't deal brute on impact, but simply create a "burning" tile for X seconds that would force players to improvise more with their movement instead of just running in a circle for 5 minutes. That would require new animation/icons to convey that its a different type of attack though.

**Comment by Repukan** [comment]
Why should huge bulking monsters be tweaked so unpreparedness doesn't kill you?

Of course you'll die if you're injured, you're expected to. We shouldn't coddle people not fighting in their prime. If anything being able to dodge swoops even with third tier of damage slowdown is imba as fuck. Makes the whole fight a walk in the park.

**Comment by ChangelingRain** [comment]
Robustin, frankly, I don't think we can make megafauna balanced for every speed level, especially given that we can't really do stuff that isn't reflex-based for combat.
Given the above, we have to balance for the fastest speed level normally available to players, because if we balance for a slower speed the faster players will literally run circles around the enemy.

**Comment by Kromgar** [comment]
@Repukan have you never when killing a drake with a ka had that shit where it lands and teleports right next you and bites you? Had that shit happen multiple times might be fixed now but it was a bitch to deal with

**Comment by Repukan** [comment]
No because I keep a huge distance and close the gap myself.

If the Drake is using King Crimson esque powers to teleport next to you it doesn't really matter how fast you are then, does it?

And you just use plasma cutters and keep a bigger range so why're you worried?

**Comment by Poojawa** [comment]
How does the drake handle doors/walls/being on station with the new swooping?

**Comment by ChangelingRain** [comment]
it swoops over them. it's like magic because it literally is magic and we don't have ceilings.

**Comment by KorPhaeron** [comment]
inb4 five followup prs

**Pull request merged**
