### PR TITLE
upgrades potty's status

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

potty the potted plant in metastation's bar now has a custom sprite

## Why It's Good For The Game

the hero and guardian of the cakehat, potty, has been forgotten by many, he deserves a rank up

## Changelog
:cl:
imageadd: a new sprite for potty the potted plant
/:cl:

### CODE REVIEW

**Comment by Cartographer-D** [comment]
Why is Potty wearing the thing he's supposed to protect?

**Comment by trollbreeder** [comment]
image
PLANTY THE POTTED PLANT?!

**Comment by nemvar** [comment]
It's a reminder of why we can't have nice things.
This is nice.
We can't have it.

**Review by Twaticus — APPROVED** [review]
:smile:

**Pull request merged**
