### PR TITLE
[EVENT] GAMESHOW (ACTUAL) TESTMERGE

### PR DESCRIPTION
**Pull request by CitrusGender**
RIGHT ABOUT DONE, THIS IS THE LAST TEST MERGE, WILL SHUT OFF AFTER TOURNAMENT.

Last one was made since we had to merge two branches into one, but this will be the final test merge.

DO NOT MERGE

### CODE REVIEW

**Comment by tralezab** [comment]
first for pogging out of my gourd x2

**Comment by tralezab** [comment]
<details>
  <summary>Spoiler warning</summary>
  
  tenor
  
  
</details>

**Comment by Mothblocks** [comment]
u guys know you can just have tgs use your own repo right

**Comment by CitrusGender** [comment]
> 
> 
> u guys know you can just have tgs use your own repo right

testmerging is a lot easier and how i've done it for 3 years now
but yeah we probably could just i'm under time constraints and can't particularly learn anything new atm

**Comment by Mothblocks** [comment]
alright whateva

**Comment by optimumtact** [comment]
>could just i'm under time constraints and can't particularly learn anything new atm

maybe one of these times you'll learn time management

**Comment by CitrusGender** [comment]
> 
> 
> > could just i'm under time constraints and can't particularly learn anything new atm
> 
> maybe one of these times you'll learn time management

lmao

**Comment by CitrusGender** [comment]
of fucking course

**Comment by CitrusGender** [comment]
ok

**Pull request closed without merging**
