### PR TITLE
Adds the ability to inject chemicals into the atmospherics pipeline thro...

### PR DESCRIPTION
**Pull request by sawu-tg**
...ugh the following methods:
- Inject into canister and release
- Inject into canister and hook into a loop
- Inject into canister and transfer into an internals tank
- Inject into canister and share between canisters
- Pouring a container (beaker, bottle etc) into an OFF vent

Adds an industrial sized 'injector' to the atmospherics closets to facilitate dispersion of chemicals into the air-stream.

Plasma, Fuel and Thermite in the air will add to the flammability of the air, but not neccesarily ignite it.

99.5% of chemicals can be dispersed, and will react as intended, including viruses, acid, slime toxin, alcohol etc.
- A known "issue", but not exactly an issue, is that explosive reactions (EMP,Potassium etc) will be small.

Here are some previews:
airmeat
sparkles
slimeterrorism

### CODE REVIEW

**Comment by sawu-tg** [comment]
Latest merge from master has made this extremely laggy, Do not merge until I fix it.

**Comment by GunHog** [comment]
This feature is amaaaaazing. Only things I would have you add is a way of determining what reagents are in a gas cloud, and that there should be a dedicated machine for adding reagents into a pipeline at Atmospherics! Think along the lines of the machine from Fallout 3 used to inject the FEV virus into the water purifier near the end of the game.

**Comment by sawu-tg** [comment]
See #6666 Instead.

**Comment by d3athrow** [comment]
If nexis' 420 polyaerosol errday stuff was any example enjoy your lag.

**Comment by tkdrg** [comment]
Apparently sawu closed this because he couldn't make it not laggy, so that's that.

**Pull request closed without merging**
