### PR TITLE
Gives AI a shell if there is no roundstart cyborgs

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Gives AI a shell if there is no roundstart cyborgs. 

Ports https://github.com/yogstation13/Yogstation/pull/10397

## Why It's Good For The Game

Gives AI's, especially malf AI's, some way to directly interact with the outside world if they didn't weren't lucky to get a roundstart borg. They will be still weaker then if they would be with a borg, since you can't do most of AI things while piloting your shell.

## Changelog

:cl: TheGamerdk, ported by SuperSlayer
add: AI now gets a shell if there is no roundstart cyborgs
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
i prefer https://github.com/tgstation/tgstation/pull/65083

**Comment by Jackal-boop** [comment]
I like this

**Comment by ATH1909** [comment]
not quite sure I'm on board with this, I kind of like the borgless AI dynamic on some rounds

this does make starting borgless screw over malf AIs far less, though, so I'm giving it an upthumb

**Comment by tralezab** [comment]
But maybe the above just branches from my dissatisfaction i've talked about in picrel. Just generally AI being encouraged mechanically to not play their unique playstyle because it is weaker than hopping into AI shells a lot of the time. And that's not a problem this pr is making, that's a problem with the overall existence of AI shells
image

**Comment by zxaber** [comment]
Yeah, I'm with Ath. I play quite a lot of AI nowadays, and borgless rounds are common during lowpop. It's usually not hard to get someone to make a shell if you need it, and truth be told you don't always. One of the downsides to having a shell is having to stop AI tasks constantly to respond to human harm with the shell (where normally your ability is limited to just complaining on the radio and maybe bolting doors).

Even for Malf, there are ways to get your kills in. For situations where you really could use a shell, maybe the ability to spend 20 malfbux on a placed robo factory to produce a one?

**Comment by SuperSlayer0** [comment]
> I don't like this because I think being a useless machine ineffectually saying "please stop hitting each other or I'll need to close some doors for a few minutes" is funny but if I always have arms I'll actually have to do something about it.

Borg's don't have arms, and mostly can't do anything to someone if they have flash protection

**Comment by tralezab** [comment]
> I don't like this because I think being a useless machine ineffectually saying "please stop hitting each other or I'll need to close some doors for a few minutes" is funny but if I always have arms I'll actually have to do something about it.

AI is now just a role where you play borg with a camera that sees the whole station

**Comment by LemonInTheDark** [comment]
I already don't like ai shells, I think they detract from the role. If they exist to fill downtime at lowpop something else should be filling that void, not just "AI but it also has a body". It seems like a lazy solution to a problem.
Expanding it to push this further sucks. If lowpop is boring we should give the ai more stuff to do during it, rather then just making them borg 2.0s

**Comment by Kubisopplay** [comment]
Shell is the only borg you can rely on, and is usually the only borg you can get on lowpop. It's really not cool to say "Yeah, add something to do for AI on lowpop" without even asking if there is a such thing.

**Comment by LemonInTheDark** [comment]
What? I know it's the only borg you can rely on/get on lowpop. What do you mean about if there's something for them to do on lowpop?

**Comment by Kubisopplay** [comment]
I mean that there really is no spot that AI can do something on lowpop without a shell. There is no spot to make anything like that, unless you want to make it a minigame that wont matter in the slightest.

**Comment by Kubisopplay** [comment]
I had a single idea that would fit, but it was already said "no" to it from a different maintainer, so as AI main, I can say that I don't see any spot where you could give AI on lowpop a job without a shell, or unusually great cooperation from people.

**Comment by LemonInTheDark** [comment]
Ah ok you disagree with the idea that something else to fill the void is possible, was confused

**Pull request closed without merging**
