### PR TITLE
Sniper set now doesn't suck as much

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: yackemflam
add: The syndicate realizes that you can't print more ammo and only having 10 shots sucks. So have some more.
/:cl:

### CODE REVIEW

**Comment by Ninja137** [comment]
I dunno if this'd fit well, but seeing something like a Fabber from eclipse phase for ammo would be interesting. Put materials in, it fabricates ammo occasionally, and lets you refill. Probably something like CMCs and Gunpowder needed.

**Comment by TechnoAlchemisto** [comment]
you're not supposed to be able to take on the whole crew as a sniper, ten shots is more than plenty if you're trying to be an assassin.

**Comment by Banana-Fist** [comment]
>you're not supposed to be able to take on the whole crew as a sniper, ten shots is more than plenty if you're trying to be an assassin.

**Comment by AdamElTablawy** [comment]
guys guys here's an idea

let the autolathe print more ammo for sniper when hacked thus adding the need to resupply at cargo instead of running around playing quickscope mcgee until someone stunprods you

**Comment by Banana-Fist** [comment]
I see nothing wrong with being able to print more ammo. That's the same mechanic as the two shot wonder .357

**Comment by Banana-Fist** [comment]
What prevents the autolathe from making a .50 round if it can already fabricate the casing, bullet, and payload for a .357? More of a lore thing than a technical thing, really.

**Comment by KorPhaeron** [comment]
It can theoretically create anything that uses metal and glass, but that design was never uploaded to the autolathe.

**Comment by TechnoAlchemisto** [comment]
There's no reason the auto lathe should be able to fabricate the gun powder in the rounds it produces

**Comment by Banana-Fist** [comment]
True.

Let's remove .357 rounds from it imo.

**Comment by AdamElTablawy** [comment]
The autolathe doesn't fabricate anything.

The metal and glass is actually a sacrifice-the inside of the autolathe is really a portal to hell filled with miniature enslaved forge demons.

When you feed them metal and glass the mini-demons gain enough power to manipulate the fabric of reality to put things that they don't have the materials ro make in created objects, such as paint for spraycans or gunpowder for bullets. Or well I guess everything uses nitroglycerin today or something but still.

That's the official autolathe lore, right there.

More to the point giving the guy with the sniper a shitton of ammo  for no effort is probably worse than theoretically infinite ammo out of a hacked autolathe that has somehow been secured somewhere safe at a very expensive cost at a slow rate. One requires time to stop and refill on ammo, the other is bang bang start to finish before an abrupt end.

**Comment by Banana-Fist** [comment]
@AdamElTablawy That was my train of thought.

**Comment by PKPenguin321** [comment]
The autolathe is an antique from an era when this game wasn't filled with realism-obsessed autists

**Comment by Bawhoppen** [comment]
did you know that a sniper mag spawns on one of the space ruins

**Comment by Cheridan** [comment]
Doesn't seem like a popular change, closing

**Comment by KorPhaeron** [comment]
maybe it should get a couple different kinds of magazines instead of all penetrator

**Pull request closed without merging**
