### PR TITLE
Adds a preference for postround credits

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: There's now a preference in your game preferences for if you'd like to see postround credits.
/:cl:

The public outcry in response to #30000 has been very... *mixed*, to put it lightly. A lot of people have clamored for its removal. Because I like the change, however, and other people want it to stay, I've gone for the middle-ground and made it a preference (on by default) - so if you don't like to see the credits, you can disable them.

### CODE REVIEW

**Comment by AnturK** [comment]
You can probably drop the verb if you're adding this.

**Comment by Xhuis** [comment]
Eh, I think it has a place. I like the credits most of the time but on some rounds I decide on a whim as they start that I don't want to watch them, and by that point disabling the pref would do nothing.

**Comment by Iamgoofball** [comment]
@Xhuis 
Fuck you. We contributed, a few whiny bitches don't get to throw our credits away. They can suck it up.

**Comment by Armhulen** [comment]
If you want to feel good about credits then just have the pref enabled lol

**Comment by Iamgoofball** [comment]
No. You don't get to remove the credits at the end of a movie because you don't like them.

**Comment by Xhuis** [comment]
I contributed too, goof. I've done a monumental amount to contribute to /tg/station and SS13 in the time I've been here. I code to further the cause of the game, not for the recognition it brings. I should hope that others who work for free on a volunteer project expecting nothing in return should feel the same.

**Comment by ExcessiveUseOfCobblestone** [comment]
Of all the people to get mad, it's goof? He already gets enough lip service with his features, although that isn't always a positive thing.

**Comment by Iamgoofball** [comment]
i'd rather that the rest of the developers get credit for their work instead of everything being Goof(tm)

**Comment by Militaires** [comment]
>this man isnt headmin

darkest timeline.

**Comment by outbools** [comment]
you guys have no experience in making credit rolls.

learn 2 git gud:
https://dl.dropboxusercontent.com/s/57y0g94sjkym0r2/2017-08-24_18-47-50.mp4

**Comment by Xhuis** [comment]
I *did* make [this](https://www.dropbox.com/s/p08w4kj08b72f6n/2017-09-05%2003-24-04.mp4?dl=0) but right now I have no plans to implement it.

**Comment by outbools** [comment]
Isn't it actually from baystation made by comma?
image

**Comment by Xhuis** [comment]
***HEAVILY*** inspired but I wrote the code from scratch. 😛

**Comment by outbools** [comment]
okay good job then

**Comment by outbools** [comment]
But you need to think about "Fin." though. It's a thing from first half of 20 century so all title roll should be stylized in '30 aesthetics.

**Comment by outbools** [comment]
https://archive.org/details/Closing_Credits
for reference

**Comment by optimumtact** [comment]
it's a 👎 from me

**Comment by KorPhaeron** [comment]
It'd make more sense to just remove the credits than to add a preference so that the credits are never seen again

**Comment by Armhulen** [comment]
Okay then remove them. They're really buggy sometimes and it's really annoying to turn them every round!

**Comment by Armhulen** [comment]
I'm not sure if they're still extending the round but it really feels like it

**Comment by optimumtact** [comment]
They're not

**Comment by AnturK** [comment]
I don't really care if they are in or not, but right now they are just ugly,distracting, too long and start during the round end animations which looks even worse. So either change them /remove them/ or stop forcing me to type the hide verb every time.

**Comment by Cyberboss** [comment]
The only bug with them is it's relying on timing to stagger their spacing and when the server gets overloaded it upsets the tracking. I can fix that much

**Comment by optimumtact** [comment]
I warned MSO about check tick

**Comment by Armhulen** [comment]
http://i.imgur.com/UsEHcdT.png nice B)

**Comment by Bawhoppen** [comment]
@outbools SS13 isn't some stage play. The credits roll is for the people who actually made the game.

**Comment by optimumtact** [comment]
It's obvious people don't like this so kick it touch and rework it to look like film credits or something else.

**Comment by PraiseRatvar** [comment]
why do people don't like it, i don't understand. you only see them for 90 seconds which is the timer it takes to reboot the server, on roundend people just kill eachother so what even is the problem here.

yes i am on the credits list before you ask.

**Comment by optimumtact** [comment]
nearly everyone here is

**Comment by Iamgoofball** [comment]
@optimumtact I refuse to allow them to replace credits of us with credits of people in the round. They don't get fucking good boy points for playing the game when we busted our asses working on it

**Comment by optimumtact** [comment]
fine whatever, all of you can go jump

**Comment by optimumtact** [comment]
don't reopen this unless you can justify why we shouldn't reward contributors hard work with the right to have their name displayed at the end of the round.

**Comment by AnturK** [comment]
They managed for years without garish text.

**Comment by Xhuis** [comment]
As contributors, I would hope that we're working on the game because we're passionate it about it and want it to be fun, not for our own gain. Because I respect that recognition is appreciated and nice to have, I'm adding a preference that's on by default so that we can still *get* recognition, and I know of several people who *do* want the credits to stay even as non-contributors. Ultimately, the game changes based on who plays it; this is a middle-ground that makes both sides happy.

I don't know why the illusion of this going away entirely is continued and perpetuated. "Nobody will turn it on" is completely unfounded, and factually incorrect because the preference starts as on by default and I myself will be leaving it that way.

**Comment by optimumtact** [comment]
I'm not happy with the continued preference bloat, providing 50 billion toggles because we're too willing to compromise is not a way to ensure people are getting a consistent experience, not to mention it's yet one more button on the already extremely crowded game preferences screen.

From my perspective we either toss it out or keep it

**Comment by Bawhoppen** [comment]
I don't see any reason why there needs to be a preference though honestly. 
Are people so invested in "proving their skills" that they need to win the end of round shuttle dock brawl or something???

**Comment by Bawhoppen** [comment]
Like not be distracted from it with credits I meant

**Comment by Shadowlight213** [comment]
I've pointed out before that we have a contributors list in the changelog. I think the credits should either be axed or changed so that it's the players and their characters instead of the coders, as it's the players who really make a round be what it is, not mechanics.

**Comment by Bawhoppen** [comment]
The changelog's contributor list is old, horribly incomplete, and will always be too limited of space to ever cover everyone who's worked on the game.

**Comment by Shadowlight213** [comment]
@remierichards A chatroom with a bunch of other people seems more fun than playing the game by yourself.
If the game mechanics was all that mattered, and not the community, then any random hub server that's updated often enough would have a roughly equal player distribution with the big servers.

**Comment by YakumoChen** [comment]
credits are literally in the changelog, what even is the point

**Comment by Bawhoppen** [comment]
Do you not understand that it only includes a few old classic coders?

**Comment by Shadowlight213** [comment]
The real question is why we don't just update those.

**Pull request closed without merging**
