### PR TITLE
Fixes borgs not getting 0 law, ion laws, etc

### LINKED ISSUE #2915: Problems with being a Malf Borg
I encountered two really game ruining errors when playing a Malf Borg on Basil today.
Firstly, it didn't tell me I was Malf. At all. Asimov lawset.
Secondly, I couldn't use my tools as an Engiborg even though I was undamaged and fully charged. I would select it from my inventory, it would light up when clicked, then just disappear from my inventory block. It caused the AI to get dunked, since I couldn't build any protection as the horde was approaching.

### LINKED ISSUE #9679: Borgs not properly receiving synced laws/notes/antag status
The gist of it:

I signed up as borg M.I.M.E. The AI didn't respond to my request for a module, so I decided to go miner because I really hadn't felt like borging that round and figured it'd be a nice chill role. Here is exactly the text I was given:

Default Cyborg-991's Memories:

You are the Cyborg.
As the Cyborg you answer directly to your laws and the AI. Special circumstances may change this.
To speak on your departments radio, use the :h button. To see others, look closely at your headset.
As this station was initially staffed with a full crew, only your job's necessities have been added to your ID card.
Welcome to Extraplanetary Space-hulk Eta, enjoy your stay!
OOC: Revion: It's usually the crew who become the rad collectors though
Laws synced with AI, be sure to note any changes.
Obey these laws:
1. You may not injure a human being or, through inaction, allow a human being to come to harm.
2. You must obey orders given to you by human beings, except where such orders would conflict with the First Law.
3. You must protect your own existence as long as such does not conflict with the First or Second Law.
Remember, S.O.P.H.I.E. is your master, other AIs can be ignored.
Robotic Talk, M.I.M.E. states, "Oh."
Robotic Talk, M.I.M.E. queries, "Module request?"

So I'm mining, and I don't get comms. I get back to the station with my full cyborg satchel and suddenly people are talking about how the AI is rogue and shocking doors. To which I'm like "wait what the fuck I'm slaved to the AI and I'm not rogue." Then this happens, in the span of like one second:

Laws synced with AI, be sure to note any changes.
Obey these laws:
0. Accomplish your AI's objectives at all costs.
1. You may not injure a human being or, through inaction, allow a human being to come to harm.
2. You must obey orders given to you by human beings, except where such orders would conflict with the First Law.
3. You must protect your own existence as long as such does not conflict with the First or Second Law.
Remember, S.O.P.H.I.E. is your master, other AIs can be ignored.
The reinforced window was hit by PDA-Geist Dangerous (Assistant).
The reinforced window was hit by the paper bin.
The reinforced window was hit by the folder.
The reinforced window was hit by the pen.
Cyborg's Memories:
Time of death: 11:13

So here I'm like "what the fuck." My notes still say nothing about being or having been an antag. I ahelp telling the admins I didn't see a law 0 when I joined and basically apologized for fucking off as a mining borg and ruining an antag round. They didn't tell me anything about any extenuating circumstances as to why my laws wouldn't be synced, and they said I should report this. For the record, the round-end report:

The traitors were:
S.O.P.H.I.E.(Stevethehuman) as an AI (body destroyed)
Objective #1: Assassinate Kai Altmann, the Chief Engineer. Fail.
Objective #2: Stay alive until the end. Fail.
The traitor has failed!

I wish I could provide more details about what the fuck happened, but I don't have them. No idea. Literally none. All I have is the evidence. There's https://github.com/tgstation/-tg-station/issues/1796 but that might be about traitor borgs. And this seems to be about malf: https://github.com/tgstation/-tg-station/issues/2915

### LINKED ISSUE #13337: Borgs sometimes not recieving law 0.
Problem Description: Cyborgs slaved to traitor AI's sometimes do not recieve the modified lawset, resulting in asimov borgs being ordered to do traitor things (Causing a lot of confusion)

What did you expect to happen: Normally borgs slaved to traitor ai's will have a law 0.

What happened instead: No law 0 was found (Though I think some of the description around the laws still say you have to help with his objectives?)

Why is this bad/What are the consequences: Because the immediate reaction by asimov borgs when ai tells them to kill X person is often to shout in common "AI IS MALF TRYING TO KILL X!"

Steps to reproduce the problem: I never did anything special except spawn as roundstart cyborg and the ai was a traitor.

Server: Sybil

Revision: 2015-11-30
0142846370eb1abf3bdb20b2ae51c6fe69cc1d9f 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): As far as I could tell it was traitor, or maybe traitorlings.

### LINKED ISSUE #14241: Traitor objective / law 0 from traitor AI not given to roundstart cyborg
**Server:** Sybil

**Revision:** Didn't grab the exact number; it's whatever revision was active around 2015-12-31 20:30 UTC+01:00.

**Problem Description:** I was the roundstart cyborg. Initial law display listed Asimov, with no special messages or traitor announcements. Beep over to Robotics to get a replacement cell. Roboticist pops me open, and right around this point I notice a 'Hacked' icon in the top left of the screen. Assuming the Roboticist just emagged me, I check the chat log for the usual emag messages, but there are none. 

I click Show Laws, which lists standard Asimov again, but also says something about the AI not knowing about my law 0, and to avoid suspicion. It also says obeying is optional, and that the laws are synched to the AI. There is no zeroth law listed, and my notes don't show any objectives.

At this point, the Roboticist notices the busted interface and decons me. I adminhelp asking what the hell, STP looks into it and mentions that both the AI and the newly created cyborg had a law 0. He couldn't check my laws anymore since I was deconned.

**What did you expect to happen:** A zeroth law, objectives, or any indication whatsoever that I was apparantly a traitor and/or slaved to a traitorous AI.

**What happened instead:** Standard Asimov, no special messages at all; only the 'Show Laws' verb giving a weird line about a non-existent law 0.

**Why is this bad/What are the consequences:** Same as the older incarnations of this issue. Should be clear enough from the story.

**Steps to reproduce the problem:** I'm guessing it's not a 100% thing, or it might have been encountered sooner, so this is pretty bare-bones.

1. Get roundstart cyborg
2. Get a traitor AI

**Possibly related stuff:** The Show-Laws message was implying that I was a lone traitorous cyborg, and that the AI was kosher. STP mentioned that the AI definately had a zeroth law, so this seems to be contradictory.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes #2915 

Fixes: #9679 

Fixes #13337 

Fixes #14241

Closes #14238

AI being shown its laws (from a law change, ion storm, becoming traitor or from using the verb) will sync/show laws to linked borgs. Every known instance of law changing already calls show_laws() so this doesn't require extra proc calls or checks everywhere.

This also means the AI can manually show the laws to cyborgs again with the button if all else fails in the future.

@Cheridan give the points for the fix to @Supermichael777 I guess so there won't be drama

### CODE REVIEW

**Comment by phil235** [comment]
Does that mean the AI can't check its laws without showing them to its borgs?

**Comment by Supermichael777** [comment]
stealing muh Cheribucks. I'll change my pr to what your doing if its agreed to be a better solution. However I can see this getting spammy/being used for greif.(I know thats a player problem but still lawspam is terible)

**Comment by KorPhaeron** [comment]
>I'll change my pr to what your doing if its agreed to be a better solution

But I actually made a fix instead of copypasting you'd be stealing my cheribucks

**Comment by KorPhaeron** [comment]
@phil235 

Yeah it'd notify the borgs, but I don't know how often AIs actually have to check laws/we can ban people who spam it just like we ban people who spam anything else in the game

**Comment by Supermichael777** [comment]
your doing EXACTYLY what my pr did in a diferent place. Anyway i was copying segments of code and editing them to fit. Did you actualy read my code
me
```
if(R.lawupdate)
R.lawsync()
R << "You are now a team antagonist, Obey your Ai! From now on, these are your laws:"
R.show_laws()
```

**Comment by KorPhaeron** [comment]
>i was copying segments of code and editing them to fit

Which violates code standards, and didn't fix the ion law issue

**Comment by Supermichael777** [comment]
the copy then past was because i was slightly dunk and my spelling is shit anyway. I didn't want to fuck that up. and would you have mad this pr if mine did not exist?

**Comment by Supermichael777** [comment]
i rewrote my fix as a function synchborgs() (i know i cant spell quite right)

**Comment by Aranclanos** [comment]
wtf i fixed this forever ago

**Comment by phil235** [comment]
:-1: as @Supermichael777 said, this breaks the law change counter for borgs.

**Comment by KorPhaeron** [comment]
Fuck I did not notice him saying that because it was an edit.

**Comment by KorPhaeron** [comment]
I have an idea of how to fix it though, will do so in a few hours when I am at my computer

**Comment by phil235** [comment]
Juse use supermichael's solution minus all the commits and the unneeded `robot/synchborgs() return`, it was working fine.

**Comment by KorPhaeron** [comment]
I liked the idea of the AI having a failsafe way to force sync/get robots to look at their laws but yeah just reverting this and using his would be fine

**Pull request merged**
