### PR TITLE
fixes the lava not burning thins inside problem

### LINKED ISSUE #23473: Crate contents are unharmed when a crate is burned by lava
See title

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: lava burns stuff inside stuff containers
/:cl:

closes #23473

### CODE REVIEW

**Comment by Fikou** [comment]
closes #54128 ?

**Comment by zxaber** [comment]
Does this destroy borg tools if they're on top of lava? What about mech tools and parts?

**Comment by ATH1909** [comment]
> Does this destroy borg tools if they're on top of lava? What about mech tools and parts?

And what about cells inside of laser guns?

**Comment by Tlaltecuhtli** [comment]
>borg tools and cells

this only affects closets subtypes which gives them 1 level of recursion, do these things have bugs? if so report them

**Comment by zxaber** [comment]
TBH I hadn't looked at the code when I wrote that, and didn't realize this wasn't being set for all atoms that contain things.

**Pull request merged**
