### PR TITLE
Centcom Expansion

### PR DESCRIPTION
**Pull request by Fayrik**
Changes z2's centcom area to be a little more functional, making the checkpoint lead to an active area instead of a dead and, and adding a cargo bay to allow access to the cargo shuttle.

### CODE REVIEW

**Comment by Fayrik** [comment]
Alright, so, forgot a screenshot to go with it. [Here's the full thing, in glorious 1:1.](http://imgur.com/Mm5IZqf)
*The screenshot was taken in dream maker, so you can see the spawn points and shuttle docking points.*
Since this is my first time making a release worthy change to the game, I'm not expecting it to be entirely smooth.
There shouldn't be any game breaking bugs in it however, since a majority of the work was just cutting and pasting things from place to place.

I'm curious to have some feedback on the autodrobe and clothing vendor placement in the dressing room. That room is usually used by inspectors before they arrive on the station, so it seemed logical to give them access to things like jackboots and eyepatches. I didn't think of the implication that it could give the deathsquad access to bunny ears.

**Comment by Jordie0608** [comment]
Changelog

**Comment by pudl** [comment]
what the fuck

**Comment by Chocobro** [comment]
centcomm was like this some time ago, but was simplified down due to lag via atmos systems. are we sure this is fine now? i'm sure the server has been upgraded.

**Comment by Dorsisdwarf** [comment]
This is very different to the huge centcomm Z we used to have, which was removed more due to people glitching into it every round and looting it than atmos woes.

**Comment by Deantwo** [comment]
Looks nice and simple.

One question though.
What is the pinpointer doing on the cargo shuttle?
Or is that a DreamMaker thing/bug?

**Comment by RemieRichards** [comment]
@Chocobro it has nothing to do with atmos systems, the Centcom Z level has no atmos, every tile that isn't space is considered breathable, and any space tile not breathable.

It was the fact that centcom used to contain real machines, as opposed to the fake ones you see on some centcom maps these days.

**Comment by Dorsisdwarf** [comment]
deantwo, that's how shuttles work now - it's a docking beacon

**Comment by Fayrik** [comment]
@Jordie0608 Added a changelog. One day I'll learn to git gud too, and wouldn't need a whole seperate commit.

Also, if people can still glitch through, do let me know if I've added anything that shouldn't be obtainable. Pretty sure cargo/QM lockers don't really count as game-breaking loot though.

@RemieRichards That shuttle console there is real, since it's the only way of manipulating the cargo shuttle at this point. Should that be changed to a fake machine?

**Comment by RemieRichards** [comment]
@Fayrik shuttle consoles are as always, an exception, they do no work unless interacted with.

**Comment by Fayrik** [comment]
Okay, merge conflict solved and -- it looks like my rebase broke the commit history. Ugh.
If anyone's got a suggestion on how to fix, would be appreciated.

**Comment by Miauw62** [comment]
You tried force push?
Op 16-mrt.-2015 10:49 schreef "Fayrik" <notifications@github.com>:

**Comment by Fayrik** [comment]
@Miauw62 That was what was needed. I've done it now so hopefully everything's in order again.

**Pull request merged**
