### PR TITLE
Fix royal moth face marking not being saved

### LINKED ISSUE #46914: royal moth facial marking resetting
if you play a moth with the "royal" facial marking, after the round ends, your facial marking will be reset to "plain"

### PR DESCRIPTION
**Pull request by Names-Are-Hard**
## About The Pull Request

Fixes #46914
Properly initializes GLOB.moth_markings_list so that the sanitation check at character load works properly. Again, probably works.
## Why It's Good For The Game
Moths can look less boring properly

## Changelog
:cl:
fix: Fixed moth markings not saving properly
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Phobias have a similar issue where they dont save between rounds, same thing?

**Comment by Names-Are-Hard** [comment]
Different cause, but somewhat similar. With phobias it was because the chosen phobia wasn't ever saved in the character prefs file.

**Comment by Names-Are-Hard** [comment]
Ah fuck

**Comment by Fikou** [comment]
good fix

**Comment by Names-Are-Hard** [comment]
No idea why the check failed.

**Comment by kriskog** [comment]
Cool, good catch. The travis failure was unrelated, good now.

**Comment by tmtmtl30** [comment]
thanks, i added these aaaaaaaages ago and couldn't figure out why they weren't persistent between rounds. i have no idea how this shit actually works, i must have missed the section in the moth wings PR that added this line

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
