### PR TITLE
Stamina damage can hurt simple mobs.

### PR DESCRIPTION
**Pull request by KazeEspada**
Stamina damage can now do damage to simple_animals. Defaults to a modifier of 0 so simple_animals are immune. Carp and Spiders take 1/3 damage from stamina, which is about 10 damage from a disabler.
:cl: Eaglendia and KazeEspada
add: The cutting edge in self-defense technology, Nanotrasen's disabler beams are thought to operate by causing a psychosomatic effect that catalyzes the buildup of fatigue toxins in target tissue. While most complex organisms are capable of quickly recovering from this sudden stress, organisms with open circulatory systems have less capacity to eliminate high concentrations of these compounds - often, this has life-threatening consequences for the organism in question.
add: Carp and Spiders now take damage from disablers and other source of stamina damage.
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
Interesting idea

**Comment by KazeEspada** [comment]
Based on #16505

**Comment by xxalpha** [comment]
This might help stop player controlled spider supremacy.
:+1:

**Comment by Eaglendia** [comment]
:+1:
I was working on this but thanks for getting it done. As I said, the best thing about the now-reverted taser overhaul was the addition of a ranged option for dealing with things like carp and spiders for Security Officers in a standard loadout - it was the only thing I found the light laser useful for in the few rounds I played with the change.

This amount of damage will kill carp in three hits, which may or may not be too few for a disabler's charge capacity. I ended up adjusting it down to a four-hit kill just because it felt wrong when testing it.

**Comment by Fox-McCloud** [comment]
I like this; it allows hybrid tasers to deal with simple mobs (which was a legit thing, IMO, about the taser rework PR) without really increasing sec's power vs antags/crew in most cases.

**Comment by PKPenguin321** [comment]
Stealth blob/cult/slaughter demon/morph/holoparasite nerf

**Comment by Eaglendia** [comment]
Holoparasites, constructs, and blobs already have specific lists of damage resistances. When I originally PR'd this I only had carp and spiders in mind - disabler bolts still won't deal damage to most things.

**Comment by PKPenguin321** [comment]
Oh right

Also this is only vaguely relevant to this pr but that changelog has given me a brain tumor

**Comment by Eaglendia** [comment]
It was some _deep lore_ I threw into the last PR that I probably wasn't going to shove into a changelog in whole

**Comment by KorPhaeron** [comment]
>Defaults to a modifier of 0 so simple_animals are immune.

Dont think this is good. Having an arbitary number of mobs that are weak to disablers while the others immune is bad. 0 way to tell if the monster you are fighting is weak to disablers or not

**Comment by GunHog** [comment]
Please make sure that bots and swarmers remain immune to stamina damage. Simple mobs that are machines do not have tissue to be damaged by them. Especially make sure that Swarmers are immune, because they are specifically designed to use them, and their barriers allow disablers through while blocking other projectiles.

**Comment by Eaglendia** [comment]
The goal was to give Security Officers a way to deal with some of the simple, persistent organic threats with the standard taser. Bots, stands, constructs, et cetera are currently and will remain immune to stamina damage.

If this is merged, affected mobs should have an additional combat message or something to make the effect visible. Something like "... [mob] looks totally drained!" or "The effect was lethal!"

**Comment by KorPhaeron** [comment]
Right now our rules for tasers/disablers are seemingly arbitrary, but they are easy to understand IC Works on humans/monkeys, but not robots or monsters. OOC the split is even easier to understand (carbons only).

This PR just makes the rules even more arbitrary and actually confusing. Why does my disabler work on a spider but not a bear? A fish but not a dog? There is no rhyme or reason or any IC indiciation of what will work and what wont.

Needs a clearer ruleset, or some IC messages indicating whether your weapon is working or not.

**Comment by KazeEspada** [comment]
I can extend it to all living simple animals

**Comment by KazeEspada** [comment]
Okay, added a message.

**Comment by Fox-McCloud** [comment]
To be honest, this should either impact all simple mobs or it shouldn't, otherwise, it's purely arbitrary.

**Comment by KazeEspada** [comment]
It can done on a per animal basis like all the other dam types.

**Comment by octareenroon91** [comment]
How does the "it does nothing!" message look in context? Could it be made more informative? Will bots in a fire spam that?

Adjust*Loss don't have any way to know what the source of damage is, do they?

**Comment by Robustin** [comment]
Costs > Benefits

**Comment by KazeEspada** [comment]
Its little black text. Also, no, because the damage calculations occur and pass nothing about anything except maybe src or usr.

**Comment by KazeEspada** [comment]
God damn this just a minor QOL thing.

**Pull request closed without merging**
