### PR TITLE
berets no longs cut off half of your hair or something to that effect

### LINKED ISSUE #30433: "Hair sprite substitution when hats are worn" system results in bald lines when hats are too small
When hats are too small E.G berets they result in a line of baldness under them because they don't cover the newly substituted cropped out hair completely.

edit: im reeing but ok

### LINKED ISSUE #31926: officers beret from special ops officer kit (select equipment) makes hair look retarded
https://file.house/KKCf.png

### PR DESCRIPTION
**Pull request by ghost**
fixes #31926 

if i was amazing i'd add a billion hair sprites for heads that would fi x #30433 as well but i'm only human and i'm a little on the rough with tokens right now so this ends up with a much better look (i think)

### CODE REVIEW

**Comment by DoctoreMad** [comment]
If this PR is closed then #30433 will also be closed because of the OP description.

**Comment by ShizCalev** [comment]
Take a pic with a fro?

I'll see what I can do about making a few extension sprites Sunday.

**Comment by Armhulen** [comment]
Imagine this but with the beret



This is my solution,

**Comment by KorPhaeron** [comment]
Your solution creates another bug though

**Comment by RemieRichards** [comment]
The original bug that was lived with since the inception of those hats.
I'm sure you can cope.

**Comment by Cyberboss** [comment]
This isn't a proper fix

**Pull request closed without merging**
