### PR TITLE
Fixes conscription kit encryption key

### PR DESCRIPTION
**Pull request by Swagile**
## About The Pull Request

Replaced the cargo encryption key in conscript kit with a mining encryption key, which has science radio just like normal miners.

## Why It's Good For The Game

Allows conscript miners to bitch to science about the lack of research or begging for a BoH.

## Changelog
:cl:
tweak: Cargo key in mining conscript kit is now a mining key.
/:cl:

### CODE REVIEW

**Comment by Swagile** [comment]
Not sure whats causing the conflict, since I tested this on my own server before pushing it and it compiled just fine.

???

**Comment by Tlaltecuhtli** [comment]
is there still a reason miners need sci radio? like the epic miner brings minerals to rnd and rnd gives cutter + boh has been removed 1 year ago

**Comment by Swagile** [comment]
> 
> 
> is there still a reason miners need sci radio? like the epic miner brings minerals to rnd and rnd gives cutter + boh has been removed 1 year ago

BoH still needs to be gotten from science, and communicating with science is how miners + conscript miners know if ORM is upgraded, and if research is being done while they are at lavaland, and also lets Science know that miners are actually still alive and doing their job.

**Comment by YakumoChen** [comment]
It's because mining and science have a deeply symbiotic relationship, the primary source of mining upgrades are from science, not cargo (not even from mining itself) and science is deeply reliant on mining to print anything more advanced then "larger bowl" or "tinier robot arm"

**Comment by Tlaltecuhtli** [comment]
yeah but do they need sci radio for "miner pls mine diamonds " or "pls research adv mining"?
botanists dont get med radio and both know what they need to do without having a shared channel

**Comment by ATH1909** [comment]
> yeah but do they need sci radio for "miner pls mine diamonds " or "pls research adv mining"?
> botanists dont get med radio and both know what they need to do without having a shared channel

Maybe we should give botanists access to medcomms, then?

**Pull request merged**
