### PR TITLE
brief CC power patch - removes stargazers, adds a power cap of 50 kW, lowers tier unlock thresholds to compensate

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
balance: Stargazers have been removed.
balance: The clockwork cult now has a power cap of 50 kW.
balance: Script scripture is now unlocked at 25 kW, and Application at 40 kW, instead of 50 kW and 100 kW.
tweak: Important scriptures are now displayed with italicized names.
/:cl:

stargazers have been a balance hell since they were introduced, and it seems like there's no real way to balance them without either making them useless or not addressing the problem at large, so I removed them

integration cogs should be used for all power generation going forward; each cog produces 5 W of power per second, which is about a quarter of one stargazer; however, the massive amount of APCs on the station ensure that you'll still not run short on power if you ensure that they're cogged well

this also provides opportunities for ambushes through unexpected attacks on people busy removing integration cogs in maintenance, but makes it more feasible to disrupt the cult by attacking the heart of their operations, thus providing an ability to counterplay where none otherwise exists

### CODE REVIEW

**Comment by Jalleo** [comment]
This may not be balanced for smaller/larger stations.

**Comment by Xhuis** [comment]
for smaller stations, there are likely fewer tools, weapons, armor etc. available to the crew; and conservation of power will still make them useful - and if there's not enough power, the cult can do some interesting shenanigans with building new APCs for the sole purpose of farming power

even so, I think there's enough APCs on even the smallest stations to provide adequate power generation, as the lower density will allow recogging faster in the event of disruption

**Comment by Repukan** [comment]
Does this work on space apcs?

**Comment by Xhuis** [comment]
it will drain the power from space apcs and then proceed to be useless because it drains from the APC's cell which needs to be replaced. if you run a power line all the way out into space it would work but it's a lot more obvious than stargazers and can be countered by just snipping a single wire

**Comment by Repukan** [comment]
Just asking because you could make a small cuck shed and change batteries periodically.

**Comment by Xhuis** [comment]
it's theoretically possible but easily patchable

**Comment by uraniummeltdown** [comment]
Please bring old clockcult back, Reebecult is too one-sided

**Comment by Xhuis** [comment]
I don't
components were implemented very strangely and suffered from the incredible feast/famine problem that current CC power does, where you either have massive surplus or none at all. AI sat fights were samey each time and lacked the potential for expansive defenses that the current clockcult does. summoning the ark was one of the interesting aspects of it but enough design and balance problems plagued it to a degree that there were several annual polls as to whether or not the mode should stay. the rework suffers from problems too but it's more coherent as a mode and designed around the same goal instead of a great deal of scripture suffering from dissonance as to the purpose

if you look at the geis situation near the end of old clockcult's lifetime and tell me it was fun gameplay to use geis on someone and then not be able to take *any other actions* without dragging them to a sigil you had to be expected to put down in advance before using the scripture at all, then you're entitled to it, but i and a lot of people i spoke with at the time respectfully disagree

**Comment by ExcessiveUseOfCobblestone** [comment]
what is the 'problem at large'?

**Comment by calzilla1** [comment]
:+1: for gazer removal
:-1: for cap addition

**Comment by Xhuis** [comment]
without any kind of cap the feast/famine problem will be completely unsolvable because conservation and clever use will allow the cult to amass gigantic amounts of power which counteracts the lower generation rate; having a cap allows the cult to focus on other things once power generation is established and punishes spam

**Comment by Spaceinaba** [comment]
the cap also lets you get all your powers faster because the unlock threshold is lower

**Comment by Buggy123** [comment]
This... I... I don't even know what this will do to the balance/meta...

This is like if you made a blob chem that turned people into monkies and on hit spawned pulse rifles, except half the time you get hit it teleports your blob core to a random spot on the station and has a 10% chance of spawning a random antagonist.

Not even that is accurate, I... I cannot think of any comparison nearly as strange as this. This is just bizarre, incomprehensible, incalculable.

Fuck it, might as well merge it and see what happens.

**Comment by Xhuis** [comment]
i'll merge u

**Comment by Spaceinaba** [comment]
buggy that analogy works about as well as trying to fix a barn with a m16

**Comment by Xhuis** [comment]
shit does that mean I've been doing it wrong this whole time

**Comment by Spaceinaba** [comment]
it's okay my strategy of defibbing hearts with a staple gun isn't much better

**Comment by Buggy123** [comment]
**EXACTLY!** I don't know WHAT the actual fuck this will do, this is a larger change than even things like the cult rebalance that's still open.

To put it simply, as is, integration cogs don't exist. I have never, ever, even once seen them used in any situation ever at any point in time in _months_. This _forces_ the cult to use them, and they function radically differently to stargazers and require different kinds of gameplay, and they produce less power on top of the reduced power cap.

This changes everything. This changes how many defenses the cult can build and when it can built them, this changes what they can use in combat and how many mauraders they can make and how many sigils they can use and it changes what they need to be doing when and it changes the entire stealth vs war mechanic and it changes the stationside-response and it changes...

Jesus fuck this turns the meta into a eldritch abomination and I don't know if its a good thing or a bad thing but
# PH'NGLUI MGLW'NAFH CTHULHU R'LYEH WGAH'NAGL FHTAGN!

**Comment by Spaceinaba** [comment]
get good lol

**Comment by Buggy123** [comment]
I'm scared

**Comment by Spaceinaba** [comment]
xhuis when can I steal the engine as a clockwork cultist and set it up on reebe to make powere

**Comment by Xhuis** [comment]
that sounds amusing but in practice would likely end up with the station being depowered the whole round because the average engineer is a chungus who hasn't stepped foot onto the solar panels in his life except when he's chasing an antagonist into space

**Comment by Robustin** [comment]
50kw seems a bit low for a cap, they should be able to maintain a little more of a float IMO.  

Cog income should go up somewhat. It's kind of confusing how Gazer ticks work compared to Cog ticks but the very nature of cogs makes them much slower to utilize. There's a whole world of difference between having to install a new cog for each APC and APC's generally being spread out and isolated from one another compared to pooping out a gazer every 5 seconds. Yet Gazers pulled in 20w/tick while Cogs apparently pulled in 1w. Gazers were way too strong but Cogs conversely are too weak. Also once the Cog meta is established people will be a lot better about removing them. 

Bump cogs power generation up to 2 and see how that plays.

**Comment by Xhuis** [comment]
power generation is currently 5 W per second; I did try bumping them to 10 W but it felt too excessive. a lot of maintenance hallways have a good chunk of APCs in one place; cargo maint on box has at least 5, for instance. them being spread out makes undoing the cogs slower than smashing a gazer nest too; it's overall a nerf to power generation but makes tearing down that power generation more arduous

as always, if it were to become a problem, then I could easily buff cogs, add different power generation methods, etc. as for the cap, I'm not sure what a good one would be, but with power generation set well it should not fall below it often; it is primarily intended to limit the cult's strength to a ceiling so that they can't amass functionally infinite power

**Comment by davethwave** [comment]
So lets just see this get merged. See how the playerbase reacts after a few rounds of CC then who knows. Perhaps it will turn out better than we expect.

**Comment by Noahnoah55** [comment]
I like the removal of stargazers, but the cap feels like it should be upgradable if not removed. Maybe have a building in reebee that allows it to take in more power from the station at the cost of a shit ton of power stored up, or link it to the number of converted crewmembers.

**Comment by Potato-Masher** [comment]
**NEW CC POWER GENERATOR:** Clockwork Hand Crank.

For when you are _REALLY_ desperate.

**Comment by Robustin** [comment]
I had the same issue with my PR, just resolve the conflicts using "yours", took me just a few minutes

**Comment by AnturK** [comment]
Is this ready numbers wise ? Code is fine.

**Comment by AlexTheSysop42** [comment]
can't you just use transmission sigils to steal power or something?

**Comment by Xhuis** [comment]
@AnturK ye
@AlexTheSysop42 nup, that was removed

**Comment by davethwave** [comment]
Another idea I can think of is by converting walls/floors and the like to clockcult one they would speed up the efficiency or draining speed of the clockwork gears by a small percent. The effect would only happen if they are on the same z-zone of the apc and the effect would be something like a 1% or so increase to speed per floor and wall you add and it would also increase the draw of power from the apc's draining it faster. with the ick reason for this is something like this. (The increase of structures fueled by the power of ratvar weakens the dimensional bonds between Reebee and the Station allowing for easier and more efficient power draw from APC cogs.)

**Comment by Robustin** [comment]
You still need to increase Cog income IMO.

I just don't see a scenario where the cult can sustain enough power to be effective right now. Even if you have people aggressively cogging APC's, a single cogscarab pulling a modest amount of brass could easily starve the entire cult even if theyve got a lot of APCs under their control. I don't see any reason to go from feast to famine on CC power balance. Up the tick amount to 2 and then see how things pan out.

**Comment by Xhuis** [comment]
i don't see why i can't see how things pan out with the tick rate at 1 either.

**Comment by Xhuis** [comment]
if it ends up being a problem, robustin, it's a single number change to buff it.

**Comment by Mey-Ha-Zah** [comment]
Xhuis, people have resorted to, once cult declares war, sabotaging all forms of generating power for the station, and keeping an eye on areas that have active power. Clock can't create anything.

**Comment by Xhuis** [comment]
i'm aware

**Pull request merged**
