### PR TITLE
[WIP]Adds grace period before admins are notified of emitter power loss

### LINKED ISSUE #4777: Erronous Emitter Admin Notices
ADMIN LOG: Emitter lost power in (104,57,1 - JMP)
ADMIN LOG: Emitter lost power in (122,57,1 - JMP)
ADMIN LOG: Emitter lost power in (122,65,1 - JMP)

These occasionally spam asay, but it's not true at all. Something else must be triggering these, because a lot of the time the emitters are perfectly fine when investigated.

### PR DESCRIPTION
**Pull request by silicons**
Fixes #4777
Might cause issues...

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Just remove the emitter power loss notice, it's all logged in the singulo investigate tab if it actually results in a singularity getting loose

**Comment by MrStonedOne** [comment]
or you can use addtimer() then deltimer() if power comes back.

**Comment by kevinz000** [comment]
wew, time to look up how deltimer works.

**Comment by MrStonedOne** [comment]
````

**Comment by MrStonedOne** [comment]
var/timer = addtimer() ... if (timer) deltimer(timer)

**Comment by kevinz000** [comment]
Actually @MrStonedOne I didn't use timers on purpose, as someone could, with extremely good timing, time emitter pulses to make it not log, by giving it power on the ticks it won't fire. That's why I made it clear its powerloss counting when it fires a beam. Thoughts?

**Comment by MrStonedOne** [comment]
Make it only delete the timer when it fires a beam

**Comment by Supermichael777** [comment]
Just make it check if it has power when it tries to fire a beam and then check again when it next tries to fire if it missed the previous firing .  Once is a accident, twice is a problem.

**Comment by kevinz000** [comment]
K

**Pull request closed without merging**
