### PR TITLE
revert "bababooey"

### PR DESCRIPTION
**Pull request by tralezab**
Reverts tgstation/tgstation#51466

# Why?
intense sound spam, merger said it was a joke merge and the revert is approved

bababooey

### CODE REVIEW

**Review by nemvar — APPROVED** [review]

**Comment by ATH1909** [comment]
so you're saying that I won't be able to play a single round with bababooey, since I've been busy with my internship these past few nights?

sad...

**Comment by Doosteroni** [comment]
Please do not merge I have not been graced by the sweet song of bababooey because real life

**Comment by Eskjjlj** [comment]
Wait 48h before merging

**Comment by optimumtact** [comment]
I will grant you a stay of 48 hours

**Comment by NopemanMcHalt** [comment]
> I regret nothing.

**Comment by Cyberboss** [comment]
Bad PR.

**Comment by tmtmtl30** [comment]
you can take the bababooey from the assistant but you can never take the assistant from the bababooey

**Comment by evilcyborgmrt** [comment]
Turn it into a mutation that makes you go bababooey

**Comment by TheSpaghetti** [comment]
bababooey

**Comment by nemvar** [comment]
It's been 48 hours

**Comment by Cyberboss** [comment]
List:

- @nemvar

**Pull request merged**
