### PR TITLE
Removes 10mm ammo variants

### PR DESCRIPTION
**Pull request by ghost**
Kor was right it's bloat, nobody buys this crap
speedo merge

:cl:
del: Removed 10mm ammo variants from the game and uplink
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
Removals are okay during freeze was a mistake.

Also, you don't get speed merges for balance changes.

**Comment by MMMiracles** [comment]
Over the last 2 months according to game stats:

- Generic 10mm magazine bought 524 times.
- AP 10mm magazine bought 77 times.
- HP 10mm magazine bought 67 times.
- Fire 10mm magazine bought 68 times.

Saying nobody buys them is dumb, as obviously some people are finding use for them still when they go with the Stechkin.

**Comment by factoryman942** [comment]
does the game stats thing count times when the items show up as part of nullcrates/surplus crates, or only when directly bought through the uplink?

**Comment by factoryman942** [comment]
also it probably doesn't help that they cost 2-3x as much per magazine, for little benefit

**Comment by MMMiracles** [comment]
There's two stats tracked, traitor items directly bought via uplink and traitor items obtained randomly. I assume the random stat includes 'choose a random item' and surplus crates.

**Comment by Bawhoppen** [comment]
I never understood the bloat argument, considering they take up very little extra file size, and don't make anything harder to maintain.
If they have any use at all (which they do), they're worth keeping.

**Comment by RandomMarine** [comment]
Removing something mid-freeze should only be valid if doing so actually fixes an issue.

**Comment by WJohn** [comment]
If you're removing ammo types, don't remove 10mm (which is 30 damage), remove 4.9x30mm, which is IDENTICAL to 9mm (20 damage per shot) except that the autolathe cannot print it. The whole point of its existence is to prevent reloading sec rifles. In that case, just make the magazines non-reloadable with more bullets.

**Comment by Iamgoofball** [comment]
what if we added

# guncrafting

so we didnt need to bloat with 3 items per ammo type

**Comment by MMMiracles** [comment]
remove 'bloat' of 3 items by adding an entire system solely for specialized guns

i wonder how that'd go....

**Comment by WJohn** [comment]
While you're at it, if you ARE removing redundant or useless ammo types (ones that are ACTUALLY useless), then remove 5.56x45mm specifically, as it is a dupe of 5.56 that does 10 more brute, even though both are 3-hit-kill bullet types as detailed in #26514

**Comment by optimumtact** [comment]
Did you enjoy this public roasting?

**Comment by FantasticFwoosh** [comment]
I've put out a memo to kor, but if more than just traitors via stetchkin's & very broad loot got regular use out of it then we may see it used more often.

If there was a supply of lower quality 10mm guns in security to use (where the stetch is still more powerful) in a situation like lowpop or in a briefcase within armory there might be more excuse to use modified ammo as a traitor because you don't have to buy the stretch for TC to necessarily to use it.

**Comment by uraniummeltdown** [comment]
🔥

**Pull request closed without merging**
