### PR TITLE
Removal of empty file

### PR DESCRIPTION
**Pull request by Jalleo**
@phil235 
thanks for helping on working out how to do this for my second PR.
edit: I had to sync my master to local to push to my removal branch......

### CODE REVIEW

**Comment by phil235** [comment]
You forgot to remove it from tgstation.dme

**Comment by Jalleo** [comment]
okay so this is a time when I have to include tgstation.dme?

**Comment by MrPerson** [comment]
This is how you do it boyo

**Comment by Cheridan** [comment]
y0L0

**Pull request merged**
