### PR TITLE
Mobs polymorphed into silicons are lawless

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Any silicons created by bolts of change have no laws.
add: Cyborgs are immune to polymorph while changing module.
/:cl:

We already make polymorphee drones lawless, this is the next step. Also, it makes wizards making a syndicate cyborg that more dangerous. And to be honest, it just formalises that the syndiborgs, generally weren't assholes

### CODE REVIEW

**Comment by XDTM** [comment]
It's already true for drones, i guess it makes sense

**Comment by lzimann** [comment]
Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding

**Comment by coiax** [comment]
> We already make polymorphee drones lawless, this is the next step. Also, it makes wizards making a syndicate cyborg that more dangerous. And to be honest, it just formalises that the syndiborgs, generally weren't assholes

**Comment by bgobandit** [comment]
It makes things a fuckton easier on the admins because staff of changed people constantly ahelp about what laws they follow and when and do they still have to follow them when X

**Comment by lordpidey** [comment]
Would it be possible to add a message explicitly stating that you have no laws?

**Comment by GunHog** [comment]
Your laws are given to you upon transformation.

**Comment by KorPhaeron** [comment]
I think this actually makes it harder on admins because lawless borgs are a trickier rules area than "follow your laws"

**Comment by coiax** [comment]
It puts them on equal footing with all the other polymorphed stuff, rather than the pretence of trying to find a "syndicate agent", and either ignoring that or shooting up the station.

**Comment by coiax** [comment]
@ChangelingRain conflict fixed.

**Pull request merged**
