### PR TITLE
New green slime mutation toxins

### PR DESCRIPTION
**Pull request by Time-Green**
Commision by @Arathian
:cl:
add: Adds new green slime mutation toxins. Teslium for ethereal, Bad food for fly, Pax for moths, happines and salt for felinids.
/:cl:

### CODE REVIEW

**Comment by Arathianen** [comment]
Hey guys, I code bountied this PR!

A couple notes:

I decided against adding a plasmaman mutation toxin. I initially discussed adding a delay to it but, even with that, it could be put in a smoke machine to cause massive, near unavoidable grief. So unfortunately plasmemes get left out in this PR.

The other races are either roundstart or common enough. I won't pretend I am unaware some people might have...objections to adding a way to make felinids. If that is a make or break thing, I wouldn't be opposed to removing the felinid toxin from the PR. Still though, I think keeping a way to change your race in the green slime with 2 chemicals in a somewhat obscure department isn't going overboard with it.

Other than that, the mutation toxins should work exactly like the lizard mutation toxin works now!

**Comment by optimumtact** [comment]
this is a violation of the contribution guidelines about asking first for species related PR's and as such, is rejected.

**Comment by actioninja** [comment]
These have been closed quickly in the past.

**Comment by actioninja** [comment]
wew

**Comment by Arathianen** [comment]
Hey @optimumtact Do I ask on discord?

**Comment by optimumtact** [comment]
there's no point in asking because I have zero interest in adding these mutation toxins, but for future reference yes you ask in discord

**Pull request closed without merging**
