### PR TITLE
makes felinid mutation toxin obtainable

### PR DESCRIPTION
**Pull request by Cw3040**
you know what this is

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this doesn't improve the game at all and is obviously just being PR'd to piss people off

**Comment by Iamgoofball** [comment]
https://github.com/tgstation/tgstation/pull/39098#issuecomment-414144540

>comments on known shitpost PR

yeah no

go home

**Comment by Cw3040** [comment]
and anonmare definitely didn't
https://github.com/tgstation/tgstation/pull/39098#issuecomment-404962651

**Comment by Zaffinomlb** [comment]
I dont like it, but if we allow cats already, they atleast need plasma men, and moths. I dont care about how fucked up it would be as plasma man but It needs to be added because cats are.

**Comment by Cw3040** [comment]
Will add Plasmaman and Moth mutation toxins soon(tm) iff this pr gets merged

**Comment by Wilchenx** [comment]
>plasma men

Plasmamen mutation toxin is literally too fucking strong

Moths are okay

**Comment by PKPenguin321** [comment]
dude cats lmao

**Comment by Therapist1** [comment]
didn’t we just do this?

**Comment by Wilchenx** [comment]
Deja vu
I've just been in this place before

**Pull request closed without merging**
