### PR TITLE
GIANT INTENT REFACTOR (separates it into 4 different harm, help, disarm and grab procs)

### PR DESCRIPTION
**Pull request by Militaires**
now we have

- harm(user, target, attacker_style)
- help(user, target, attacker_style)
- disarm(user, target, attacker_style)
- grab(user, target, attacker_style) 

procs for each action instead of the previous blob.
attacker_style is var/datum/martial

thanks razharas for helping me with dis.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
what's this suppose to do / purpose?

**Comment by Razharas** [comment]
Dividing big procs into smaller more managable ones

**Comment by Razharas** [comment]
Also with this we can make grab use hotkey like pull does so its also nearing the future of pulls death

**Comment by Iamgoofball** [comment]
:-1: make them datums

**Comment by Razharas** [comment]
They are already in datum species

**Comment by Iamgoofball** [comment]
I want intent datums

**Comment by Razharas** [comment]
Thats a bit too much to ask from someones first pr

**Comment by Militaires** [comment]
@Razharas  it third or fourth

my first one was just a removal of a file (space worm code)

**Comment by pudl** [comment]
GIVE US DATUM INTENTS

**Comment by nullbear** [comment]
i prefer 2 intents instead of 4.

1: Disarm and Grab intents aren't used very much. Grabbing is done now using Ctrl+Click anyways. Expand on it.

2: It's much faster, players can toggle between two intents faster with hotkeys, as opposed to having to cycle through them / move their cursor to the bottom of the screen and click the desired intent mid-combat / most players do not use, or even know about 1-2-3-4 hotkey intent switching, and it's much less intuitive to use than a toggle.

**Comment by Militaires** [comment]
@nullbear 
>disarm is not very used much.

the base of tiding, cancerously disarming member of security is crucial to every greysuit.

**Comment by Militaires** [comment]
also these are in the datum path ReEEEeEEeeEe

**Comment by MrPerson** [comment]
They can be datumized/removed later. This just makes it much easier to do one or both of those

**Comment by Xhuis** [comment]
Was about to slam that :-1: harder than a hydraulic press but then I saw you didn't include the stupid-ass Sleeping Carp -> CQC thing.
:+1:

**Comment by Militaires** [comment]
@Xhuis dont insult my memes

im actually just doing this so i can continue that meme

also there's fucking 3 martial arts, plasma fist, wrestling and sleeping carp, sleeping carp was not the first and none of the others are derivative paths.

**Comment by Xhuis** [comment]
That's... not related. I just don't want Sleeping Carp to be reflavored into generic CQC. There's no reason for it and I don't want yet another unique thing to go to the scrap heap.

**Comment by Militaires** [comment]
@Xhuis my point was that I'm not "reflavoring" sleeping carp, there's already 2 other martial arts and they're not "reflavours" of carp just cause they're in datum/martial, it's just adding another martial art of which the name happens to be a game reference.

**Comment by nullbear** [comment]
> > disarm is not very used much.
> the base of tiding, cancerously disarming members of security is crucial to every greysuit.

i mean in the sense of the code checking whether or not you're in disarm/grab intent. Usually it's if(user.intent == "help" or "harm") only.

**Pull request merged**
