### PR TITLE
Revert "Improves bee lore"

### PR DESCRIPTION
**Pull request by Shadowlight213**
Reverts tgstation/tgstation#29970
Original pr was merged before 24 hours.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
What are you talking about?

**Comment by Iamgoofball** [comment]
chrome_2017-08-16_22-23-17

**Comment by Shadowlight213** [comment]
Pr was speed merged without qualifications.

**Comment by Iamgoofball** [comment]
I don't recall that being a rule?

**Comment by MrStonedOne** [comment]
Goof's photo is clearly shopped. This is what it really says:

**Comment by Iamgoofball** [comment]
How i it shopped when I have video evidence??????

**Comment by Iamgoofball** [comment]
https://file.house/RvSF.webm Check 'em

**Comment by Shadowlight213** [comment]
Actual image
http://puu.sh/xc99p/a827ed42c5.jpg

**Comment by MrStonedOne** [comment]
That looks too blurry to be real. must be a shop.

**Comment by Iamgoofball** [comment]
Agreed, that looks really weird

**Comment by Shadowlight213** [comment]
Your face looks too blurry to be real tbqh

**Comment by MrStonedOne** [comment]
You're right, I have no face. Now that you know the truth I'm afraid i'm going to have to kill you and steal your face.

**Comment by Shadowlight213** [comment]
https://web.archive.org/web/20170817053238/https://github.com/tgstation/tgstation/pull/29970

My face is unknown. Niknak is the the only one who has seen my real face I think.

**Comment by Iamgoofball** [comment]
https://file.house/-Pty.webm

Even the MSM backed falsechive.org backs me up

**Comment by meeeeme** [comment]
Thumbs down because better lore encourages more roleplay, and we need some more.

**Comment by loqoman** [comment]
A host, design lead, and head coder walk into a bar...

**Comment by Iamgoofball** [comment]
Hey buddy, I think you got the wrong PR.

**Comment by RemieRichards** [comment]
Fuck off I already told you no last time.

**Pull request merged**
