### PR TITLE
[MAP] Derelict Update

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR see's some minor updates to the Derelict, mainly quality of life.

---

I'm half tempted to do a one over of the Derelict as its horribly designed to say the least, but that's kinda the charm. Nonetheless there's some things that need updating and fixing, thus here they are.

First: I've added a Gravity Generator room to the Derelict. We never got around to adding one in so here it is. This room is not airless thus its one of the few "safe zones".

screenshot 2015-02-14 21 57 23

Secondly: I updated both of the solar array's since they were horrifyingly designed, I also added a solar tracker.

screenshot 2015-02-14 21 57 33

screenshot 2015-02-14 21 57 50

---

I'm open to any further suggestions, thanks.

### CODE REVIEW

**Comment by xxalpha** [comment]
:-1:

It's a nuked station, that looks way too neat.

**Comment by Steelpoint** [comment]
What's too neat? 

If its the arrays, I only changed the bottom tiles and fixed the broken wiring and lack of a solar array, if its the grav gen, its behind a bunch of Rwalls so it was secure in the explosion.

**Comment by xxalpha** [comment]
Grav gen should not be online, second picture looks better than Box's solars, third picture's only damage is it's missing three arrays and the grilles barrier has gaps. It should look much more devastated, in my opinion.

**Comment by Miauw62** [comment]
yeah, these look far too neat. the grav gen should be offline and the room should be partially bombed or hazardous.

**Comment by Steelpoint** [comment]
I'll look into it.

**Comment by Miauw62** [comment]
also, the solars being horrifyingly designed is the entire POINT. the derelict is a fucked-up version of oldstation, you might as well try to turn the pantheon in rome into a sensible modern architecture building with central heating.

**Comment by Steelpoint** [comment]
Except I don't think they even worked properly due to the design.

Anyway, here's a update Grav Gen.

screenshot 2015-02-14 22 25 49

**Comment by Miauw62** [comment]
you should be able to repair the grav gen, the room around it should just start out blown up. Remove the SMES and make sure the APC is dead, then make the doors broken or something. So it's smashed up like the rest of the derelict.

**Comment by Steelpoint** [comment]
Grav Gen room starts with the generator offline, with both the APC and SMES cell's deconed as well.

screenshot 2015-02-14 22 38 21

Most of the supplies needed to get the basic equipment working can be found in engineering secure storage on the other side of the station.

screenshot 2015-02-14 22 38 19

**Comment by xxalpha** [comment]
The grav gen does not need to start completely BTFO, just offline and needing repairs (need plasteel to be slapped on it). Then one would have to get it powered. That would be enough obstacles.

**Comment by pudl** [comment]
this has got to be the most retarded thing i've ever seen. derelict doesn't have a grav gen because it was pre-grav gen. no one ever even bothers trying to repair the derelict, adding a grav gen both makes the derelict more inaccurate (exadv1 actually made fun of us for our derelict) and it'll be ultimately fucking pointless. puh lease

**Comment by Apogate** [comment]
muh lore

By adding a gravgen and unfucking the solars, it actually makes it feasible to fix & adds potential for more interesting traitor/cult/pet project rounds

**Comment by Lumipharon** [comment]
I think what you mean is no one tries to repair the derelict ANYMORE, because no grav fucking sucks a load of dick.

Literally nothing is lost by adding an offline one to the derelict, so I don't see the problem.

**Comment by Jalleo** [comment]
This really shows we should make the grav gen constructable and deconstructable.

**Comment by Steelpoint** [comment]
I've been going over a image I have of Oldstation and I'm going to do some more changes to better match the apperance of Oldstation, I'm also going to get atmo back on the station, but it will need to be repaired.

**Comment by Miauw62** [comment]
no, you're going too far.
do that in another PR.

**Comment by Steelpoint** [comment]
This is the "derelict update", I'm not doing a full remap I'm just adding in a few minor things such as placing a computer frame where a computer used to exist and whatnot, its the little things.

**Comment by Steelpoint** [comment]
Some additional work I've been doing, I've touched up all over but here's three of the biggest changes I've got so far.

---
NE Solar's + New Arrivals

screenshot 2015-02-15 22 01 47

Fully updated the NE area to be in line with the original design of that area of the station.

---
Updated Chapel + Teleporter Room+ Medbay

screenshot 2015-02-15 22 01 51

Slightly updated these areas as well as added in the (bombed out) teleporter room.

---

New Atmo + Security

screenshot 2015-02-15 22 02 02

Added in atmo back to the station, will form the backbone of a new atmo system if some engineers are ready to put some elbow grease into it, also slightly touched up Sec.

---

**Comment by xxalpha** [comment]
Why are the NE power cables under the wall, don't do that.

**Comment by Steelpoint** [comment]
I'm essentially copying Oldstation 1:1 on these designs, that's why.

**Comment by Miauw62** [comment]
* yeah dont put them under the wall.
* less working computers pls
* NE solars are too neat, mash them up a little
* add some lattices to the NE solars

**Comment by Steelpoint** [comment]
The computers start offline, I'm showing this via DM and not in game.

I haven't touched NE solars into making them mashed up cause they are used as the primary power source, the SE one's are mashed up, tho I could do that to both.

**Comment by Miauw62** [comment]
you're still supposed to repair them, just smash them up, it adds to the atmosphere.

**Comment by Steelpoint** [comment]
I've smashed up the solar array's, you'll need more wires to finish it as well. Some extra Solar Array's might be useful.

---

Oldstation's arrival shuttle reimagined.

screenshot 2015-02-16 00 05 10

Of course that's how it was then, this is how it appears now on the Derelict.

screenshot 2015-02-16 00 15 27

**Comment by Miauw62** [comment]
It looks weird when segmented like that, TBH. Probably because we have no broken shuttle tiles.
If you're going with the broken shuttle look, you should probably move some parts a bit further back so they're not next to the station, and use decals/broken platings to make it seem broken rathe than glitchy.

**Comment by Steelpoint** [comment]
Yeah I'm still working on it, worst case I'll sprite my own broken tiles.

**Comment by xxalpha** [comment]
Yeah not having broken shuttle tiles will make it hard for you. See if you can get some sprites done.

**Comment by Steelpoint** [comment]
My brilliant sprites at work.

screenshot 2015-02-16 14 19 58

**Comment by RemieRichards** [comment]
>not square

WRONG UNIVERSE, WE ARE GLORIOUS 4 SIDED SHAPE UNIVERSE.

**Comment by Miauw62** [comment]
i'm sorry but those sprites look really awful.

just make them look like broken plating or something :V

**Comment by Steelpoint** [comment]
Full map of the Derelict as of the recent update.

screenshot 2015-02-16 18 43 50

**Comment by Miauw62** [comment]
aren't all APCs aboard the derelict supposed to be broken?

**Comment by Steelpoint** [comment]
They've always worked, they just tend to run out of power quickly since there's no power source to charge them.

**Comment by Lumipharon** [comment]
All I see in that image is 
A: Dodgy cropping around the chapel storage area
and
B: Up to 10 free lasers, or whatever those turrets use.

**Comment by Steelpoint** [comment]
Again, the turrets are turrets in appearance. I'll have to double check but its not going to be a full turret.

**Comment by Niknakflak** [comment]
I'll be honest.  I think it looks disgustingly terrible and would prefer to just keep the derelict as it is now.  Specifically the shuttle.

**Comment by Steelpoint** [comment]
It's meant to be horrible, its the derelict, its never looked good before and saying that "it looks terrible" is not really something to be held against a Derelict PR because at its core, it is a  horrible station. I did the shuttle like that as a experiment though.

**Comment by dannno** [comment]
dude those messily eraser'd sprites are... awful. I don't even know what you were thinking.
There's looking like a horrible, dirty, abandoned derelict station (cool)
And then there's looking like a horrible, sloppily done mspaint edit (not cool)

**Comment by Jalleo** [comment]
Domt try to replicate it fully use ya imagination and get better damaged shuttle sprites.
That bit top left could be made to look like people were surviving on the station for a while modify what was working and then a meteor hit. Gives a better feel than a long hallway with turrets.

Atmos should really be more parts but all damaged looking than a empty if you want this added.
Empty not used right can be bad.

**Comment by Jordie0608** [comment]
Changelog

**Comment by pudl** [comment]
it shit

**Comment by Steelpoint** [comment]
Allura you hate absolutly everything and half your comments get deleted, try having more of a opinion that is different from "shit".

**Comment by xxalpha** [comment]
The shuttle isn't staying like that, right?

**Comment by xxalpha** [comment]
Are the floor tiles on the solars plasteel tiles? Maybe make them dirty or damaged or something. They look awfully clean while things around them are blown up.

**Comment by dannno** [comment]
allura isn't wrong though
this looks dreadful

**Comment by Steelpoint** [comment]
Jesus fucking Christ how many times do I have too say this to get it through your thick skulls but THE WHOLE FUCKING STATION IS SHIT. That's the point.

What the fuck are you expecting me to do? I'm copying Oldstation in its design I am not designing a entirely new station from scratch.

If this is your ""feedback"" I may as well delate the whole Derelict cause its "dreadful".

**Comment by dannno** [comment]
>dude those messily eraser'd sprites are... awful. I don't even know what you were thinking.
>There's looking like a horrible, dirty, abandoned derelict station (cool)
>And then there's looking like a horrible, sloppily done mspaint edit (not cool)
>You can't just bevel off the edges and expect it to look alright.

you're a big baby

**Comment by Steelpoint** [comment]
Your a idiot, if your going to criticise a very specifc aspect of the station then SAY so instead of making a generic catch-all statement that "its shit".

Besides, I already commited to remove the shuttle not only on the forums but on coderbus, which I did.

**Comment by xxalpha** [comment]
Calm down. Now about those solars floor tiles, can you make them scorched and such, around the damaged arrays?

**Comment by dannno** [comment]
>if your going to criticise a very specifc aspect of the station then SAY so instead of making a generic catch-all statement that "its shit".

That comment where I did that was a week ago you autist.

**Comment by Steelpoint** [comment]
I'm finished with the design, take it or leave it. I want to work on other map changes that will actually get merged.

**Comment by Steelpoint** [comment]
> That comment where I did that was a week ago you autist.

I was replying to the comment you made about half an hour ago saying "this looks dreadful" which gave no context as to why you were criticising.

**Comment by dannno** [comment]
And my point is that I already gave more detailed criticism that was ignored

**Comment by Steelpoint** [comment]
I already responded to shuttle feedback on the forums and already committed to removing them about five or six days ago.

Again, I was responding to your more recent feedback which was implied to be criticising the entire design and not only the shuttle.

There's no other way to interpret it.

**Comment by Steelpoint** [comment]
Added in blown up tiles/platings to the solar arrays.

**Comment by Steelpoint** [comment]
This is good to merge, the shuttle is gone.

**Comment by Apogate** [comment]
DERELICT 2.0 2k15

**Comment by Steelpoint** [comment]
Still good to merge.

**Comment by Jalleo** [comment]
Ill try and ping a maintainer on IRC later when I am at home.

**Comment by Halcyon-** [comment]
where are the merges Jaelleo you said there would be merges

**Comment by Steelpoint** [comment]
I'm lucky this is a PR that only alters a z-level that no one touches, otherwise I would have has to close this due to the map being out of date.

Can this get merged please?

**Comment by Jalleo** [comment]
I said I would ask a maintainer about it I did and i dont know what happened after just go on irc and ask if its suitable for merge. Make sure to update op to most current image. Of the whole thing.

**Comment by Apogate** [comment]
did you changelog, SP?

**Comment by Razharas** [comment]
Shuttle got removed right?

**Comment by Razharas** [comment]
Also yes make changelog PR sleetpoint

**Pull request merged**
