### PR TITLE
Cleaner,Blob transformation,Camera fixes

### LINKED ISSUE #10355: Space cleaner can make genetic powers invisble.
I was working on powers in genetics when a drone came in and sprayed me with some cleaner to clean my bloody lab coat.This made all the powers I currently had (hulk and cold resistance) invisible. Possible you could use the shower to same effect as well.

### LINKED ISSUE #11294: Transforming into blob is broken.
In order to turn someone into a blob, you need to make them a human, then in their player panel click the "make blob" button. The problem is that it doesn't actually make them a blob, but rather spawns one on there. What's more, it tries to pull a ghost not from your character, but someone else in the ghost pool, and then FAILS to do that because they immediately get booted out of control of the blob as ghosts, so it's mindless.

This is kinda annoying because I want to test some blob related stuff.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes space cleaner removing mutation overlays (Fixes #10355)
Fixes camera runtime (also might speed up camera processing a bit)
Fixes Make Blob button using random ghost (Fixes #11294)

### CODE REVIEW

**Comment by phil235** [comment]
This doesn't really fix the underlying issue with mutation overlays.

**Comment by AnturK** [comment]
Yeah it really only fixes this one case, would have to add some mutation hooks threre for full fix.  But update call wasnt needed there anyway so might as well remove it.

**Comment by Razharas** [comment]
The code is committed, the github doesnt want to close it so i close

**Comment by optimumtact** [comment]
@Razharas this didn't close the linked issues, are you able to close them?

**Pull request closed without merging**
