### PR TITLE
Unit tests for stuff accidentally placed in space by mappers

### PR DESCRIPTION
**Pull request by ShizCalev**
This unit test detects all turfs & other movables that aren't in a lit area (ie area/space/nearspace) on station zlevels

The grep detects movables placed on shuttles that do not have the correct area assigned, which caused those atoms to break off of the shuttle & literally get launched into random parts of space (usually on station z-levels; the only reason I found this issue was cause the unit test was detecting random shit ending up on station maps lol)

Minor fix for the mapload_space_verification unit test - it was falsely detecting turfs that shuttle grids (that were template_noop) were parked ontop of, which aren't effected by the shuttle in any way. This allowed the following fix

Fixed a number of shuttles having atoms in /area/template_noop areas. Atoms in these areas are treated as not actually part of the shuttle itself & were launched off into random space tiles across all z-levels via dump_in_space(). Corrected those grids to have the correct area, and as such, shuttles now stay together properly. 

:cl: ShizCalev
fix: Fixed a number of shuttles having parts (such as lattices) completely disappearing.
fix: Fixed the ceilings above shuttles on station maps being full-bright.
fix: Fixed lattices sometimes appearing at random locations in space on station maps.
fix: Cleaned up a number of accidentally placed objects in space across all station maps.
fix: Fixed a false positive with the mapload_space_verification unit test failing on turfs that weren't actually part of shuttles.
code: Added a unit test that automatically finds all base space turfs with objects on them, as well as non-space turfs that are set to space areas (meaning that these squares weren't lit properly.)
/:cl:

Shuttle Ceiling Fix:
Before
2024-06-30_23-15-18-dreamseeker-Doctor_s_Spess_Junk_Eta
Fixed
Screenshot 2024-06-30 231528

Shuttle Fix:
Before
image
Fixed (look at the lattices in the middle. the stuff in the shuttle are randomized / not part of this)
image

### CODE REVIEW

**Comment by san7890** [comment]
Thanks!

**Comment by ShizCalev** [comment]
at a ready state, just improving the documentation now.

**Comment by ShizCalev** [comment]
at a ready state, just improving the documentation

**Comment by ZephyrTFA** [comment]
stop adding to check grep I beg.
make something better

**Comment by LemonInTheDark** [comment]
Powerlessly he screams into the void 
Also ideally placing a turf in space would convert the turf's area to nearstation and vis versa to avoid this issue, but whatevs for now.

**Pull request merged**
