### PR TITLE
Revert "Barticles for bonfires 2021"

### PR DESCRIPTION
**Pull request by Mothblocks**
Reverts tgstation/tgstation#59869

Forced everyone to go on the latest beta version. Should probably wait until we have particles for something impactful first.

### CODE REVIEW

**Comment by tralezab** [comment]
*soft sobbing noises from the other room*

**Comment by ArcaneMusic** [comment]
Can we at least keep bonfires in their own separate file?

**Comment by optimumtact** [comment]
This can be re merged once we warn people to update their clients it's not permanent

**Comment by Mothblocks** [comment]
id rather just wait until clients have 514 and then just re-merge the pr

**Pull request merged**
