### PR TITLE
Hides worn PDAs

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

PDAs no longer have a visible appearance on your character when equipped in the belt or ID slot.

image
image

Pictured:
image
Me uh... not visibly wearing a PDA?

## Why It's Good For The Game

There's virtually no game advantage gained by knowing whether someone is or is not wearing a PDA, and even if there were they could just as easily have it in a pocket or other storage slot.
They create visual noise on your sprite and are an accessory that virtually everyone always has, making the game look worse.
When ID card sprites were restored as part of a bug fix when introducing missing worn icon unit testing, they were intentionally hidden again for similar reasons.

## Changelog

:cl:
imagedel: you can no longer tell if someone is wearing a PDA by looking at them
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Isn't there a sprite on carbons for id and you just making it invisible if someone wears pda?

**Comment by timothymtorres** [comment]
Just add a bitflag that lets certain uniforms hide PDAs.  They have this for hats, just do the same thing.

**Comment by ArcaneMusic** [comment]
So, this bares mentioning: Even though the icon_state is missing (set to "nothing"), we're still sending assets to the client every time we do so, despite is being an empty sprite. This is part of the reason why we went through [Spritemageddon](https://github.com/tgstation/tgstation/milestone/57). 

To my understanding, this is currently no way to avoid sending an asset if the icon_state doesn't match that of the `icon` file. I don't know if we can hit that here, but as a general practice this is something we'd like to avoid doing.

**Comment by Mothblocks** [comment]
i was going to be sad but i literally can't tell the difference in any of those screenshot test comparisons

**Comment by thgvr** [comment]
Thank god. I don't think anyone will miss this.

**Comment by theOOZ** [comment]
> Thank god. I don't think anyone will miss this.

me :(

**Pull request merged**
