### PR TITLE
Ethereals can now scream

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
soundadd: Ethereals can now scream
/:cl:

When speech sounds were added, I was thinking of what ethereals would sound like and decided theremin-sounds would fit them, I made some samples but seeing as the pr never  got merged I didn't end up getting them in, however, Ethereals missed out on being able to scream, so I got some theremin samples and used them to make scream sounds for em.

Here's all 3 samples:
https://vocaroo.com/1DxzTeUCSdT9

### CODE REVIEW

**Comment by Ratvar** [comment]
Will this be available irl?

**Comment by ModDownloading** [comment]
Now I'm tempted to merge the lizard screams super12pl made here too.

**Comment by necromanceranne** [comment]
Theremin scream, nice.

**Review by Mothblocks — APPROVED** [review]
if you were a theremin i wouldn't know where to begin my hand would stay here on my chin with a hum that never ends

**Comment by ATH1909** [comment]
the next mothscream.ogg???

**Pull request merged**
