### PR TITLE
Syndicate Lavabase Ruin

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Players expressed interest in another "tutorial" ruin like the botany one, where they could learn jobs after death. This ruin includes a viro and chemistry lab staffed by syndicate agents.

There is also a comms array, for spying/griffing the station radio.

The agents get some nice bold DON'T ABANDON THE BASE text on spawning, and the entire base is surrounded by lava, not to mention they lack picks of any sort, so hopefully they take the hint not to run off FNR. The base is also wired to explode should the syndicate feel like they're going to be overrun.

http://i.imgur.com/1MtNgPN.png

### CODE REVIEW

**Comment by Chnkr** [comment]
`and the entire base is surrounded by lava`

This does nothing, as you can simply replace the lava with all the items you have at hand inside the base.

**Comment by KorPhaeron** [comment]
They don't have an items that let them build over lava, but yes they could probably throw themselves across it with enough chemistry and viro powergaming. That's why they also get the "don't do that" message.

**Comment by KorPhaeron** [comment]
Going to add a snowflake self destruct device at antur's suggestion to avoid people stealing the bombs

**Comment by Dorsisdwarf** [comment]
Mining has no bombcap, so just make a single central bomb (usemyspritesmakestationgreatagain) for the self-destruct but make it massive

**Comment by KingPhilipIII** [comment]
I approve wholly. From the Lifebringers I've learned to botany like a pro, the golems to research/mine efficiently, and melee combat from the Ashwalkers. Now I just need somewhere to cook food.

**Comment by GunHog** [comment]
Maybe there should be some type of Engineering ruin....

**Comment by Niknakflak** [comment]
I can tell you, that people will leave the base just like the hotel staff did.  It is inevitable

**Comment by KingPhilipIII** [comment]
Problem with the hotel is unless the station comes to visit it ultimately has very little for you to do. Atleast here you can make memesprays to incinerate each other, then revive, or blow up monkeys with super viruses.

**Comment by scoopscoop** [comment]
Perhaps put in a security camera console somewhere near the intercoms? Encryption key syndies could get intel and advice on stationside matters.

**Comment by KorPhaeron** [comment]
@Niknakflak 

Eventually we'll just have to ban people yeah

**Comment by KorPhaeron** [comment]
@scoopscoop 

Good idea

**Comment by KingPhilipIII** [comment]
Do the Syndicakes in the base receive stetchkins or some other weapon? You mentioned a bomb if they are overrun, but overrun implies they can defend themselves to begin with. 

Might want to be careful too. I can see a shitler Syndie scientist(They are basically scientists) using the intercoms to reveal an agent. Because there are plenty of sore losers in SS13

**Comment by ExcessiveUseOfCobblestone** [comment]
>Might want to be careful too. I can see a shitler Syndie scientist(They are basically scientists) using the intercoms to reveal an agent. Because there are plenty of sore losers in SS13

you can do the same thing with the hotel though, and with the hotel you get direct access to metagrudge someone [aka teleporter].

**Comment by Fox-McCloud** [comment]
Might I recommend adding 1-2 self-use syndicate sleepers?

**Comment by KingPhilipIII** [comment]
That would probably be smart, in the likely event someone blows themselves up. Maybe add a surgical room and some cadavers to dissect. Or to reattach blown off limbs.

**Comment by ExcessiveUseOfCobblestone** [comment]
call it tutorial island and have some subtle runescape references.

**Comment by GunHog** [comment]
Make sure the base has uranium! The high level stuff requires it!

**Comment by SgtxRootbeer** [comment]
You should add uranium as a regent to the Chem dispensers so the agents can get top-tier stuffs for their virus.

**Comment by KorPhaeron** [comment]
I added uranium and made sure they couldn't steal the bomb

**Comment by jughu** [comment]
Add a turret outside that shoots foam to show they mean bussiness

**Comment by FantasticFwoosh** [comment]
I can see metarushers being a problem armed with welding tools and RCD's to grab some quick syndie loot after cruising around the empty lava sea in boats.

Alternatively why not make this a Ayylmao base instead? It'd help counter rushers because the walls can only be regularly deconned with plasma advanced tech to get inside this spooky base full of human experiments (scanned humans grown in tanks?) and scientists studying human behavior for some kind of ulterior purpose.

(If ayy walls can be deconned we really need to PR that out, i forget)

**Comment by calzilla1** [comment]
Should be able to send death viruses to the station

**Comment by AdamElTablawy** [comment]
meanwhile on 'barren as fuck' news network, local syndicate base is emptier than hornygranny's soul

**Comment by Armhulen** [comment]
SNOW OPS WHAT DID THEY DO TO YOU

**Comment by anconfuzedrock** [comment]
make a lizard gassing one to teach security and atmos next

**Comment by Bawhoppen** [comment]
we have a lizard gassing spaceruin just add some sleepers

**Comment by KingPhilipIII** [comment]
Didn't know where to go to comment on this, but a few important things are missing. Notably fans to keep air from getting sucked out, monkeys can open the virology door themselves, no virus food dispenser.

**Comment by FantasticFwoosh** [comment]
Between being armed to the teeth (sniper rifles are the only pro-active defense against miners hanging outside our derp doors leading to lava) , and the limited tree of viruses you'll probably fall victim to & eventually the voice switching on the pirate radio will get a bit tired over time on non-syndicate based rounds where you can't really be helpful in a limited capacity, a bit light on engaging till round end content and playability.

> A camera station would be really useful for the comms since without seeing them, the context is lost and its easy to pick out. Also you can only interface with general comms, the space content syndie base is more detailed in this regard for the same function

> People have pointed out the lack of a (custom?) virus food dispenser

> Its laughably easy to escape apparently using carpet to convert the lava (though this is a edge case being investigated) or stealing a miner's boat with your superior firepower despite risk of being punished for leaving.

Its a bit thin at the moment but for alpha just merged that's to be expected though i wish there was more playability in it. As to be constructively critical, its a less detailed animal hospital with comms that imprisons you in one place until you suicide from boredom.

> I honestly did not expect there to be 'front doors' on the base, and why is there a construction room (reinforced floors) with no content or instruction to build anything other than to store supplies?

This is all from 1 game round observation as myself in a syndie comms technician role playing alone.

**Pull request merged**
