### PR TITLE
Adds Race banning

### PR DESCRIPTION
**Pull request by Shadowlight213**
Race banned players will be restricted to human only.
No snowflake allowed.

### CODE REVIEW

**Comment by Niknakflak** [comment]
Is that some kind of joke

**Comment by Zilenan91** [comment]
Bot is best coder

**Comment by Cheridan** [comment]
do we seriously need individual ban systems for each and every little pissy thing?

if someone is doing something to an extent that it is a problem, then tell them that it is a problem and warn them to cut it out. if they continue, apply a normal ban. this works for every situation, resolving the need for crap like OOC / appearance / race / bloodtype / bans. 

are we seriously going to do this every time an individual or select group is being annoying with a single thing?
it's just offloading admin responsibilities onto the system.

**Comment by PKPenguin321** [comment]
the bot is summoning the ancient paprika

**Comment by Shadowlight213** [comment]
@Cheridan I think sweaterkittens asked me to implement this for plasmamen. Race bans are going to be needed if we implement more non simply cosmetic species I feel.

**Comment by Zilenan91** [comment]
That's probably for the best in the occurrence that someone accidentally or otherwise takes off their plasmamen jumpsuits and causes problems

**Comment by Cheridan** [comment]
Admins don't ban for accidents, though. If someone intentionally griefs with plasmamen I don't see how it's any different than griefing with a toolbox or lube or whatever.

Honestly sure this is probably a thing that should exist but i guess i'm just riled up since this is so close to the recent addition of individual OOC bans which were literally just because of 1-2 people who were being obnoxious.

**Comment by GunHog** [comment]
Race bans should include humans. I.E. for players that start 'race wars' and grief lizards deserve to lose their right to be a human.

**Comment by Zilenan91** [comment]
:+1:  :100:  ^^^^^

If people abuse their skin rights they deserve to lose their skin rights

**Comment by Iamgoofball** [comment]
@Cheridan 
>bloodtype ban

i'm coding this

**Comment by Shadowlight213** [comment]
@GunHog How would that even work? what the hell would they play as? The raceban is just for any non human race.

**Comment by Zilenan91** [comment]
I think a human race ban would be for people who were a bit overzealous in their human racism.

**Comment by Incoming5643** [comment]
Age ban, can't play anyone under the age of 50

**Comment by SweaterKittens** [comment]
It was requested that we have race bans as part of Plasmamen getting added, I did not personally request them, although I do feel like they could have their uses. I do tend to have the sentiment that being shit while you're one race doesn't mean that you're not going to be shit as another race - but the same concept applies to jobbans and those are used frequently. I'm not an admin, and I know at least one admin requested the ability to raceban when I was pushing for Plasmamen, so it seems like it would get used.

@Cheridan : The reason those specific ban types (like OOC) were added were because people were being awful in that specific aspect. Punnches never really did anything aside from start shit in OOC, and banning him from the server just served to cause a large amount of problems as there wasn't (at the time) enough to really justify a full server ban. It of course reached that point eventually, but it's much easier for the admins to look at a problem player and say "He's being exclusively awful in this aspect" and remove that, then try to reach for a more general ban and then deal with the ensuing, inevitable, ban appeal.

**Comment by Cheridan** [comment]
> it's much easier for the admins to look at a problem player and say "He's being exclusively awful in this aspect" and remove that

exactly
our admins have gotten used to taking the easy way because they don't have the gumption to deal with the fallout of making deserved rule 0 bans.

**Comment by Cheridan** [comment]
this isn't drama, it's mostly just me yelling at clouds

**Comment by optimumtact** [comment]
I'm not sure why you're getting too upset at this cheri? Having the ability to surgically fuck someones day up rather than hitting them with the biggest hammer you have is probably good. It's not like it costs us too much either.

**Comment by Aranclanos** [comment]
cheri is right they are retards

**Comment by optimumtact** [comment]
This has zero overhead and value for the admins, why are you in such a bad mood today?

**Comment by Iamgoofball** [comment]
i think we should remove lizard and catpeople anyways

**Pull request closed without merging**
