### PR TITLE
Revert "Bloody footprints!"

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/-tg-station#11531
The feedback for this is almost entirely negative and janitors can't keep up with the mess even with the best tools they have.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Trigger happy much?
Lower the values instead of reverting it jeez.

**Comment by Iamgoofball** [comment]
Maybe instead we should consider buffing the janitor?

**Comment by Aranclanos** [comment]
give it some time before doing this

**Comment by Nienhaus** [comment]
Buff janitor by adding 4 more and a 
sweeper3

**Comment by Lumipharon** [comment]
They're super ugly in game, and you just end up with a mess of boot prints absolutely everywhere.

**Comment by Iamgoofball** [comment]
We can just lower values guys. It'll be an easy fix.

**Pull request closed without merging**
