### PR TITLE
[April Fools] Makes the multitool into a multimeter like god intended

### PR DESCRIPTION
**Pull request by EricZilla**
## About The Pull Request

The damn thing should be SQUARE and should have a wire for interacting and pulsing and such, its obvious

## Why It's Good For The Game
image
I just want to give soulposters a quick heart attack honestly. Though really its been a lot better lately.

## Changelog

:cl:
image: added/modified/removed some icons or images
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
This but remove the april fools tag

**Comment by JohnFulpWillard** [comment]
odd april fools choice

**Comment by Dorsisdwarf** [comment]
its a nice sprite

**Review by Wallemations — APPROVED** [review]

**Comment by Skebulba** [comment]
The joke is that it's actually a good resprite

**Comment by Acer202** [comment]
Wait, this is awesome put it back!

**Pull request closed without merging**
