### PR TITLE
Fixes sleeping carp wave kick dealing insane damage + wounds, fixes neckgrab throws not being harder

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Back when I made being thrown into walls/structures/whatever extra fast do extra damage to you in #55383, I missed out on the fact that the sleeping carp wave kick move apparently launches you at an insane 14 speed for some reason, compared to the standard throw's 2 speed. Thankfully, I had capped the amount of extra speed you can take damage from to 5, but even with this cap, this still meant being wave kicked into a wall (not even counting the 10-15 brute from the first punch) dealt 50 brute, with

15 damage from the kick itself, and 35 damage from the impact (10 base + 25 from the extra speed, *with* +25 wound bonus from the speed too). That 35 damage impact + 25 wound bonus gives you a whopping **38%** chance to suffer a critical bone break at full health. Here's a handy chart to show the percentage outcomes:
[](https://i.imgur.com/JVcBB16.png)

I'm merciful and left in 2 points of extra speed, so you still deal 20 damage on the impact + 10 wound bonus. Since wound rolling scales exponentially with damage, going from 35 -> 20 damage is extremely significant, and brings the odds to this:
[](https://i.imgur.com/XPkYUNX.png)

I also realized while testing this that neckgrab throwing people doesn't actually throw them harder as originally intended, and fixed that, so throwing someone from a neckgrab deals a bit more damage. 

## Why It's Good For The Game
An infinitely repeatable 2 step attack combo should not be able to cause outright compound fractures

I'd count this as fixing an oversight that I just became aware of, but to sidestep the GBP question from maints, I'll mark it as balance in the CL

## Changelog

:cl: Ryll/Shaps
balance: Being launched into a solid atom by Sleeping Carp's Wave Kick has been fixed to no longer deal far more damage and wounding power than originally intended, and can no longer cause outright compound fractures in healthy targets.
fix: Throwing someone you have in a neckgrab or are choking will now properly throw them harder than normal.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
It's the same speed as CQC's launch. It only mattered for speed, and only your change gave it meaning.

also CQC does the same thing, just an FYI.

**Comment by KittyNoodle** [comment]
While I do agree on the wound stuff, I do think the damage should stay at where it is, for something twice the cost of an esword i expect good

**Comment by Coastfront** [comment]
as someone else mentioned, the wounds can skidaddle but i do think the damage should stay relatively where it was at being alot.

Yes, it hits extremely hard unarmed, Carp also costs the majority of a traitors tc, locks them out of every ranged weapon in the game, while retaining vulnerability to thrown weapons (cough throwing a bola at someone and then pelting them to death with floortiles/spears/whatever) in addition to ousting them from just punching someone.

For comparison, on a cheaper weapon, with none of the previous downsides. The powerfist, is relatively concealable (fits in bags), 6tc, so carp is already more than double this, doesent restrict any of your weapon options, and makes you an arguably more devastating force at melee. The powerfist, on its max power, at the cost of an airtank. The thing you can find abundantly, pre filled, everywhere. deals 60 fucking damage at melee range, knockdowns, etc.  Not counting that it also sends your opponent flying away from you at mach V, so its a fuckoff button aswell.

Carp, where it currently is, is more of a gimmick weapon compared to every other traitor item, which i think is fine, unarmed that is technically the most concealable it can be if sec doesent vibecheck you by forcing you to grab or punch them. and as a gimmick weapon, makes sense that its not "better" than such weapons as the powerfist, which consume "ammo", and also are extremely fucking loud. However i do think that as an item that eats up most of a traitors tc, it should definetly still atleast have high damage options, since, unlike the powerfist. The funny kick doesent let you insta win most fights. Carp objectively, has a longer time to kill a single enemy, meanwhile powerfist kills someone in 2 hits, and makes them mostly irrelevent for the next 10 or so seconds if you just bitchslap them offscreen.

I agree with the wounds but chopping the damage is just gonna make carp even more pathetic than it already is for a 13tc item that severely cripples your combat options.

**Comment by Ryll-Ryll** [comment]
65 damage for hitting someone twice is insane and anyone arguing in favor of it is just damaging their own credibility

**Comment by necromanceranne** [comment]
> 65 damage for hitting someone twice is insane and anyone arguing in favor of it is just damaging their own credibility

Should I bother mentioning the powerfist as well or is this specifically a problem with Scarp?

**Comment by KittyNoodle** [comment]
Two sword hits also do 60 damage and cause bleed what’s your point

> 65 damage for hitting someone twice is insane and anyone arguing in favor of it is just damaging their own credibility

**Comment by KittyNoodle** [comment]
Esword is a three hit crit on a unarmored target, while sleeping carp which costs 12 tc is a two (technically 4) hit crit on unarmored targets AND greatly limits you to only melee.

The esword is a good point to balance around and does 30 damage, something that costs almost twice a esword should be better than a esword.

**Comment by iwishforducks** [comment]
You're missing a key component in scarp which is the fact that it doesn't need to be holstered, nor can it be knocked away from your hands. Anyone can disarm a esworder- but no one can disarm a scarp user.

**Comment by drIcepop** [comment]
> You're missing a key component in scarp which is the fact that it doesn't need to be holstered, nor can it be knocked away from your hands. Anyone can disarm a esworder- but no one can disarm a scarp user.

And that's why it costs more

**Comment by Coastfront** [comment]
> You're missing a key component in scarp which is the fact that it doesn't need to be holstered, nor can it be knocked away from your hands. Anyone can disarm a esworder- but no one can disarm a scarp user.

even though carp cant be disarmed and has those advantages, it costs more than double some other traitor items that can dish out 60 damage, just as fast. Even though its no disarm, It locks you out of ever using any ranged weapon, mostly removes your ability to fight back from just random people attacking you without ousting yourself as traitor (different punch chat messages.) and the powerfist, while it can be disarmed, is literally the same thing as wave kick but ultra spammable, cheaper, aswell as eswords while cheaper, still dish out the EXACT SAME if not greater damage than scarp, dont limit you, are arguably more concealable, and half the time people either wont react fast enough to disarm you, or you'll be killing someone in maint making disarming a non issue.

Carp is literally just a gimmick weapon, and everytime its damage goes down it just pushes it further into the territory of "gimmick weapon nobody should buy"

**Comment by Livrah** [comment]
Understandable, but carp already weak enough. 
Still gonna use it for style points.

**Comment by SuperNovaa41** [comment]
Carp was already nerfed into the ground, let it have something

**Comment by rdragan** [comment]
Wounds have no place on LRP.
@Ryll-Ryll You basically created this issue yourself, along with many others.

**Comment by JosephJomama** [comment]
> 65 damage for hitting someone twice is insane and anyone arguing in favor of it is just damaging their own credibility

Power fist, esword, makarov are all cheaper and do the same damage in the same amount of hits or less. Hell, you can buy a makarov/one magazine, print 9mm by the boxful and have like 8 magazines in your backpack to do 30 damage per bullet with no melee cooldown. Don't get me started on the revolver, which you can print ammo for at any hacked autolathe and does so much damage per hit with NO COOLDOWN that people consider it cheap to use. I get what your PR is trying to achieve but this "damaging credibility" line is embarrassing.

**Comment by KittyNoodle** [comment]
Also, what has mattered and always will matter more in combat is how many hits it takes to crit, not the amount of raw damage. The stun baton is a two hit crit weapon, sleeping carp is a four hit crit weapon, a desword is a three hit crit weapon. If anything antag gear needs a major buff, not a nerf, as engaging in melee with security in any way is not worth it, as a stun baton outdoes most antag gear in hits to crit someone

**Comment by Coastfront** [comment]
> Also, what has mattered and always will matter more in combat is how many hits it takes to crit, not the amount of raw damage. The stun baton is a two hit crit weapon, sleeping carp is a four hit crit weapon, a desword is a three hit crit weapon. If anything antag gear needs a major buff, not a nerf, as engaging in melee with security in any way is not worth it, as a stun baton outdoes most antag gear in hits to crit someone

Not to mention that not only are antag melee weapons almost always outmatched by the wrath of the stun batong (there are very few of them that can crit at the same speed as a batong) carp forces you into melee, against an opponent who will be stronger at melee than you.

**Comment by Mothblocks** [comment]
> Wounds have no place on LRP.

Terry players be like

**Comment by KittyNoodle** [comment]
What have you done, the game is supposed to be balanced around one antag being stronger than 1 security officer not the other way around, the stun baton stamcrits in two hits, and once you are in stamcrit you are dead, meanwhile carp USED to crit in 4 hits, also restricting you to melee and security does its best in melee. For something that costs 12 tc it is now worse than an esword. Stop buffing security and nerfing antag gear, one sec officer should not beat a traitor roundstart. We already have a problem with sec eliminating all antags within the first 20 minutes we do not need an antag nerf anytime soon

**Comment by drIcepop** [comment]
This was like the one thing that scarp had going for it, it's almost pointless to buy now.

**Comment by Mothblocks** [comment]
> What have you done

That's in the changelog

**Pull request merged**
