### PR TITLE
1 more shuttle curse, curses now delay by 30 more seconds

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
tweak: Nar-Sie cult can now delay the shuttle 3 times, up from 2
tweak: Nar-Sie cult shuttle delays are now 3 minutes, up from 2.5
/:cl:

After cult lost the ability to meme on other z-levels, their win rate is down to the mid 30's. I'm seeing a pattern of rapid Code Red + Shuttle stuff going on at the 20 minute mark even if the cult is barely hanging on. This gives them a better shot at overcoming early shuttle calls and forcing security to go on the offensive if they want to leave unhindered.

### CODE REVIEW

**Comment by kevinz000** [comment]
>Bait cult to curse 4 times
>Recall shuttle
>Call shuttle immediately as recall timer will be at max 2.5 minutes for red alert
>5 minute shuttle
You should probably fix that
But I'd call it
Emergent gameplay :^)

**Comment by KorPhaeron** [comment]
>their win rate is down to the mid 30's

Not sure what time period you are referring to when it was higher.

It's 37 now, it was 39 the month before the change. In the months leading up to it, it was far lower (11, 21, etc)

-From a sec point of view, I call the shuttle because hanging around for 40 minutes waiting to be stunpapered or get rolled by an army of laserproof juggernauts is miserable

-From a cult point of view this wont help cultists who were "barely hanging on" but it would be undeniably nice for competent cultists with an established base (the kind sec really wants to run from)

And maybe red alert shuttles should be reconsidered if basically every antag needs a shuttle cancel power.

**Comment by ChangelingRain** [comment]
This is a pretty bad solution in general, if the cult is having trouble they may simply not have access to these, especially if they've been found 20 minutes in(and wasn't the original intent of the plasteel cult stuff to be secondary instead of literally needing it to win? hmmmmmmmm.)

**Comment by Robustin** [comment]
If the cult is having trouble and can't get access to these, then its probably dead regardless.

This isn't a complete solution, but I've seen too many rounds where the crew just bails and these shuttle delays only buy a single recall and a couple minutes of progress. I'd be willing to cut it down to 3 curses but the shuttle curse rarely gets used as it is, I see no reason why we can't try this to see if the cult can use it to buy enough time now.

**Comment by lordpidey** [comment]
You might want to change the curse flavor text too.  They all say two minutes.

**Comment by ChangelingRain** [comment]
The cult not being able to access shuttle curses doesn't mean it's dying, it just means it has no access to plasteel, which is not the same thing.

**Comment by Shadowlight213** [comment]
needs merge token

**Comment by Metacide** [comment]
Cult is a horrible gamemode, and even if cults rarely win outright they usually manage to kill vast numbers of people in particularly dull and uninteresting ways. That's why it usually gets called, and adding more shuttle ping pong doesn't sound like it'll make things much better.

**Comment by Robustin** [comment]
I'll reduce the curses to 3 as a compromise, and update the text.

**Comment by Robustin** [comment]
@ChangelingRain 

Yea its obviously not the exact same thing, but if the cult is spread so thin that nobody can access EVA/Robotics/Engineering/Mining, then that usually means its not in a position that would let them win before the shuttle arrives anyway.

**Comment by ChangelingRain** [comment]
Frankly, this isn't a particularly good solution.
It's more shuttle ping pong, it may not actually be accessable, which means it may not even solve the problem it's trying to solve, and it's definitely more useful to an already established cult than the cult that would theoretically need it to establish or keep a foothold.
also shuttle recall mechanics are bad and these should never have been added get fucked

**Comment by Robustin** [comment]
So glad I fought for months to prove I had the better vision for cult just so we'd end up here anyway.

**Pull request closed without merging**
