### PR TITLE
Changes the roller bed sprites to be wider and darker for easier clicking

### PR DESCRIPTION
**Pull request by phil235**
I asked on the sprite request thread but didn't get any response so here's my half-decent attempt at making roller beds easier to click (especially to unbuckle people).

### CODE REVIEW

**Comment by Deantwo** [comment]
Awesome! :+1:

**Comment by WJohn** [comment]
Huge :+1: from me, these things have always sucked to use.

**Comment by Lumipharon** [comment]
>try drag a roller bed with someone on it
>click in the gaps between the bed legs

Every. Fucking. TIme

**Comment by phil235** [comment]
>try drag a roller bed with someone on it
click in the gaps between the bed legs

Oh don't worry, that infuriating gap is still there just tinier, so it will still happen but less often I hope.

**Comment by WJohn** [comment]
Speaking of that: Could you change it so there's a tiny bit of alpha in between the bed leg gaps so clicking on it still counts as the roller bed?

**Pull request merged**
