### PR TITLE
New card and wallet sprites

### PR DESCRIPTION
**Pull request by JStheguy**
## About The Pull Request
The current ID cards are just kind of ugly, so I've totally re-done them in the style of the old ID cards. To maintain the existing feature set, though, means that wallets have a totally new look to them.
Additionally, the emag is back to using it's classic design and budget cards have been given a facelift to match the style of the new-old IDs while looking more immediately distinct from them.
ss13_ids
All the new sprites.

ss13_wallet
Some of them in game.

## Why It's Good For The Game
Makes ID cards look (hopefully) better while maintaining their current functionality.

## Changelog
:cl:
imageadd: ID cards, budget cards, and wallets have new sprites. Emags have been reverted to their old look.
/:cl:

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
This is great, no more brick IDs.

**Comment by Fikou** [comment]
why is the centcom id logo not rotated

**Comment by TheChosenEvilOne** [comment]
> 
> 
> why is the centcom id logo not rotated

security IDs have the same thing actually, probably just don't look that great when rotated.

**Comment by JStheguy** [comment]
Exactly that, same thing with the mime ID (and actually the mining ID, but the pickaxe is already at an angle so it's harder to notice), their general shape just doesn't take toangling well when dealing with babby-sized spaces.

**Comment by RaveRadbury** [comment]
Lawyers aren't sec. Take the red off or inexperienced HoP's will think that Lawyers report to the HoS and will cite the ID as evidence.

**Comment by MCterra10** [comment]
Surely I can't be the only one who liked the new (old?) ID style. The edges and icons looked way more smooth and defined when the ID was flat

**Comment by Agameofscones** [comment]
Aliasing is kind of out of place, but there's really no other way 😔 

👍

**Comment by HomocidlePancakes** [comment]
Oh boy, another reskin of a *recently* reskined item. Dumb, but nothing will be lost

**Comment by francinum** [comment]
Soulful.

**Comment by zxaber** [comment]
>Robo icon looks like shoe prints

Is it time for a robo icon redesign?

**Comment by carlarctg** [comment]
they look good they are good whatever

wheres the emag

**Comment by Detective-Google** [comment]
Tbh I like the current ids better because you can actually recognize the job easier, but if you're gonna change them to sprites that are worse on a technical level why not just use the old ones

Not to mention the inconsistency of some icons being rotated some not is bad
Also these look like vg sprites to me tbh

**Comment by anconfuzedrock** [comment]
hurghh my nostalgiaboner

**Comment by Fhaxaris** [comment]
I like the old tilted look, but the fact that some of the icons are not tilted will bug me eternally.

**Comment by SkeletalElite** [comment]
Not a fan of the tilted look TBH

**Comment by dee-dubya** [comment]
The tilted look honestly looks too noisy compared to the clean horizontal look we have now. Add onto the inconsistency(for technical reasons) of the job icons not all being tilted, and I don't see this sprite working out.

The overall concept of the cards themselves are visually appealing, though. I think the current horizontal sprites would benefit from adapting the design of these cards.

**Comment by plapatin** [comment]
you know it just occurred to me that these sprites look similar to the openss13 ID card sprites
image

**Comment by actioninja** [comment]
What is old becomes the new

**Comment by optimumtact** [comment]
why would you make these diagonal? they look awful and jaggy

**Comment by FloranOtten** [comment]
these look horrid, why are they diagonal

**Pull request merged**
