### PR TITLE
Bumps min compiler version to 1621 / adds min compiler version to alternate_byond_versions

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Min compiler version is something we should probably test to make sure it actually works.

Case in point: Our current min version (1609) cannot compile as of #81152 due to a byond bug fixed in version 515.1621.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
we should bump it then no?

**Comment by MrMelbert** [comment]
Yes

**Comment by LemonInTheDark** [comment]
errors handled by #81185, feel free to redo here if you want I just thought I should clean up my BS

**Comment by MrMelbert** [comment]
This Is So Sad

**Comment by LemonInTheDark** [comment]
In immediate retrospect this should have had a ci entry about it bumping min version for server owners

**Pull request merged**
