### PR TITLE
Surgery Bed Resprite

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Goonstation had licensing issues with the recent changes to the Surgery Bed so me and https://github.com/Mey-Ha-Zah put our heads together to make this new sprite.

Up Close Sprite
Screenshot 2023-07-03 145653

Sprite Example in a Test Session
Screenshot 2023-07-03 150836
## Why It's Good For The Game

Resolves some licensing problems with Goonstation before the drama hits.
## Changelog
:cl:
image: Added new Surgery Bed sprite
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
Didn't they just get resprited in https://github.com/tgstation/tgstation/pull/76334?

**Comment by DATA-xPUNGED** [comment]
> Didn't they just get resprited in #76334?

That resprite copies goon's so it's being resprited again

**Comment by Wallemations** [comment]
I preferred the less thin variant

**Comment by kinneb** [comment]
for reference, heres a comparison between the old bed, new bed and goon bed: 
image

**Comment by Imaginos16** [comment]
I still much rather prefer the current version, The human silhouette in the proposal looks unnaturally weird.

**Comment by kinneb** [comment]
> I still much rather prefer the current version, The human silhouette in the proposal looks unnaturally weird.

id agree if goon didnt want it changed or removed

**Comment by ChungusGamer666** [comment]
I like this sprite better regardless of licensing memes tbh

**Comment by Imaginos16** [comment]
I fucking hate licenses man.

**Comment by Youtubeboy139** [comment]
Screenshot 2023-07-03 161355

**Review by Imaginos16 — APPROVED** [review]

**Comment by Cheshify** [comment]
Fuck licensing honestly

**Comment by SomeoneYouProbablyKnow** [comment]
And this is why ingame pictures are so important the outline looks so silly up close but in an actual room it fits in very nicely

**Comment by Youtubeboy139** [comment]
Screenshot_2023-07-03_185714

**Comment by notfrying1pans** [comment]
this changes the top of the sprite, the bottom is still from goon

**Comment by Jacquerel** [comment]
> this changes the top of the sprite, the bottom is still from goon

No it isn't.

**Comment by Cheshify** [comment]
> And this is why ingame pictures are so important the outline looks so silly up close but in an actual room it fits in very nicely

I personally disagree, it still looks silly

**Comment by san7890** [comment]
mmmm sweat marks

**Comment by optimumtact** [comment]
I have been informed that this is still a derivative of a goon sprite and has simply been edited, this is not acceptable and does not resolve the problem because if you do this it remains under the goon license.

Therefore this issue is not resolved.

You cannot make a sprite that is a derivative, you must make one from scratch, or from another codebase.

**Pull request merged**
