### PR TITLE
Adds several sprites for ghostform

### PR DESCRIPTION
**Pull request by BananaCreamPie**
ghostpreview

### CODE REVIEW

**Comment by Iamgoofball** [comment]
can we make this enabled for everyone yet

**Comment by optimumtact** [comment]
Pay your byond subscription goof

**Comment by Kromgar** [comment]
>still shittty ghosts sprites

Why the fuck are  we not using the totally awesome ghost system /vg/ has? You look like you do on death

**Comment by Fox-McCloud** [comment]
Second what @Kromgar  said; we use that system and it's way better for identifying people on the fly.

**Pull request merged**
