### PR TITLE
[MAP] Readds Firing Pins To Armoury

### PR DESCRIPTION
**Pull request by Steelpoint**
In my recent armoury revision PR I accidently forgot to place the firing pins down, this PR corrects that.

Link to relevant PR here: https://github.com/tgstation/-tg-station/pull/12336

Fixes https://github.com/tgstation/-tg-station/issues/12529

### CODE REVIEW

**Comment by freerealestate** [comment]
omg hes touchin the overy

**Comment by Nanotransistor** [comment]
Why not just put them in the HoS's locker? You will want to ask him for pins anyways.

**Comment by tuypo1** [comment]
this is the perfect opportunity to get rid of firing pings though

**Comment by Steelpoint** [comment]
Firing Pins still exsit in virtually all weapons in the game and in RnD, this is just correcting a minor mistake I made when I forgot to put the Pins in the armoury.

**Pull request merged**
