### PR TITLE
Adds black market organs crate

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
add: Unapproved merchants have recently started peddling organs in NT space.
/:cl:

Might as well buy it through cargo

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Nice OP

**Comment by Cheridan** [comment]
isn't it even more grim though if this doesn't exist and people have to farm organs themselves from station crew?

**Comment by lzimann** [comment]
that never actually happens though @Cheridan

**Comment by Anonmare** [comment]
@Cheridan I try to do this and blood harvesting with clones and I get disarm-spammed/tased by security because nobody ever bothers to check if the body is a catatonic or not

**Comment by FantasticFwoosh** [comment]
Literally why reject this? Kor already removed the capacity to print off limbs from the limb grower after it was reverted.

In a emergency it may very well be needed if there aren't any suicides/soul-less deaths to harvest.

**Comment by lzimann** [comment]
Hm but no one rejected... author was the one that closed.

**Pull request closed without merging**
