### PR TITLE
Adds the vox race.

### PR DESCRIPTION
**Pull request by praisenarsie**
Icons are from [baystation](https://github.com/Baystation12/Baystation12/pull/2982/commits/83aa5c3eefbbd3e1f14d57b7b5c62c22912981d3).

- [ ] Add special organs for them

- [ ] Figure out a lore because why not

- [ ] ?

Doing this because @lzimann says he's lazy. Might as well work on this.

Original PR; #34335

### CODE REVIEW

**Comment by imsxz** [comment]
Kiki yaya

**Comment by evsey9** [comment]
no

**Comment by epochayur** [comment]
what the fuck is a vox

**Comment by praisenarsie** [comment]
i talked to a friend about this and he brought up some good points about this being a bad idea due to the fact that we don't need this as **tg isn't paradise.** if you want to play as this race, go gladly play paradise, bay or any bay codebase for that matter.

**Pull request closed without merging**
