### PR TITLE
Stun batons respect shields on hit

### LINKED ISSUE #13760: Stun batons/telebatons don't respect shields
This has been true since the dawn of time. Batons will stun you even if your shields (or previously armour) fully blocked the hit.

### PR DESCRIPTION
**Pull request by ghost**
Successfully blocked hits will not deduct charge from the aggressor's baton/prod.
Fixes #13760

### CODE REVIEW

**Comment by Zilenan91** [comment]
Wait why would they not deduct charge? They still hit the shield so you'd think there'd be an electric charge going into it even if it's nullified.

**Comment by Xhuis** [comment]
@Zilenan91 Stun batons don't take charge while active, so I assumed that it automatically triggered an electrical shock when it hit something organic or robotic. You can hit windows and whatnot, too, and that won't deduct charge.

**Comment by Zilenan91** [comment]
Ah ok

**Comment by Thunder12345** [comment]
All hail King Eshield Ops, the Unkillable One

**Comment by Xhuis** [comment]
@Thunder12345 The way I see it, it's a worthy tradeoff. Energy shields are already quite expensive, and getting a whole team outfitted with them is a whopping 80 telecrystals.

**Comment by Supermichael777** [comment]
MURDER-BONER INTENSIFIES.

**Comment by tkdrg** [comment]
This works out well with #13785

**Pull request merged**
