### PR TITLE
Nerfs changeling augmented eyesight

### PR DESCRIPTION
**Pull request by ghost**
Currently, augmented eyesight is _extremely_ overpowered. Infinite night + thermal vision with zero downsides was a mistake. To remedy that, I've made some changes.

First and foremost, it has an examine text that's fairly obvious, similar to digital camo. Second, anything that can be used for even partial blinding has an enhanced effect on changelings using this ability. Flashbanging a changeling with the ability on will cripple them for quite some time, and even flashlights at the eyes can stunlock them.

This gives an incentive not to keep the ability on all the time in addition to making changelings more vulnerable when using it.

### CODE REVIEW

**Comment by Incoming5643** [comment]
Why

We finally had a power that was worth taking

Whyyyy

**Comment by Atskadan** [comment]
its not that hard to cope with, really, just switch it on and off every once in a while to get your bearings

**Comment by xxalpha** [comment]
Why not use SEE_MOB as that is essentially what thermals is?

**Comment by Xhuis** [comment]
I _do_ use seemobs. The variable thermalvision is just for stuff like blinding.

**Comment by PKPenguin321** [comment]
imo, either make their eyes super vulnerable or add examine text but not both
the examine text is the heavier nerf here as this ability is now only useful when literally nobody's around, essentially meaning it's lost 90% of it's use. i'd prefer if we didn't have this

**Comment by Xhuis** [comment]
I do agree that the examine text might be too much considering how much the flashes affect them. I commented out the examine text code but it's still there.

**Comment by PKPenguin321** [comment]
i love you so much xhuis

**Comment by Xhuis** [comment]
This conflicts now because of that flashing refactor, please do not merge until I work this out

**Comment by Xhuis** [comment]
Conflicts should be fixed now

**Comment by Xhuis** [comment]
Anything stopping this from being merged?

**Pull request merged**
