### PR TITLE
Nightmares now have pockets and a belt slots

### PR DESCRIPTION
**Pull request by Buggy123**
Why:
Most other species that can't equip a jumpsuit has natural pockets/belt slot (golems, mushroom people). This puts nightmares on par with them.

:cl:
tweak: Nanotrasen has sent out a Code-Dark Alert! Beware of power failures, as nightmares have evolved natural pockets and belt loops. If you thought assistants were bad, wait until you see a nightmare with a tool belt and captain's spare.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
You quite literally describe why this is a bad idea in your changelog.

**Comment by Shadowflame909** [comment]
Just let em wear jumpsuits.

The downside of them wearing jumpsuits is that they lose their innate camouflage.

**Comment by optimumtact** [comment]
you didn't even attempt to justify this

**Comment by adamkad1** [comment]
He did justify that, other species with blocked slots have acess to those slots

**Pull request closed without merging**
