### PR TITLE
High latin for command staff, config option for command channel

### PR DESCRIPTION
**Pull request by ghost**
:cl: CosmicScientist
add: Centcom would like to remind heads to brush up on corporate language to greet inspectors properly
tweak: Centcom would also like to mention the command channel is no longer guaranteed in the budget
/:cl:

Adds high ~~gothic~~ latin for commands staff and all Centcom personnel. Adds a config option for both the language being assigned and for the command channel being available on all headsets.

Encryption keys modified whilst I was there to be less of a copy/paste job for their descriptions to avoid divergence. Headsets modified to, on creation, pull their channel access description directly from their primary encryption key.

By default I've set high latin to be turned on and the command channel to be turned off because the intention of this addition is to replace the command channel. Players will get to see their command staff talking to one another either on their department channels or over common so they can assume either they're active or they're talking about when to call security to push you out of the airlock. Then when an armed ERT comes in, you can be nervous as to if they mean "There's a survivor, help them!" or "There's a survivor, shoot them!"

Anyone who has the language will speak it before they speak galcommon unless they change their default language. This should apply to all carbon human species so shouldn't work oddly with any downstreams that enable nonhuman command staff or any future staffing changes at Centcom (e.g. synths/androids).

Here are two options for the language icon:
high latin symbol comparison blown up 800

This was a test run in game using the latter icon,
High latin and command channel turned off:
test screenshot 1
Both still turned off:
test screenshot 2
Both turned on:
test screenshot 3

I have no clue what it looks like on the receiving end because I don't know how to play two clients at once. I wasn't sure if just having latin syllables was fine but I didn't know how to search for syllables in the first place.

### CODE REVIEW

**Comment by optimumtact** [comment]
you go too far in beating this horse

**Comment by CosmicScientist** [comment]
It's my horse. I'm allowed to beat it.
when you code it

**Comment by Slignerd** [comment]
The second icon looks way better.

**Comment by Jazaen** [comment]
Someone remind me, do lings steal languages? If not, this would pretty much make any infiltration of command staff impossible by default.

**Comment by KorPhaeron** [comment]
How can I disguise as a head of staff (or be promoted to one?)

How does a parody of the church make sense thematically for the power structure of our silly (still vaguely retrofuture) space corporation?

**Comment by GunHog** [comment]
1. Please do not disable the Command channel. It is quite an important channel, especially during Revolution.

2. Please remember to program silicons to know High Latin, as it is only logical (and consistent) that they know any language spoken by Nanotrasen crew.

**Comment by WJohn** [comment]
While a cute reference to warhammer 40k, this *does* have pretty significant effects on the command channel and heads of staff. Being able to communicate only among themselves is a pretty big deal, and also screws over promotions from regular crew to heads of staff being unable to understand what the others are saying (which could be considered RP, but again, revs and traitors would be at a disadvantage here).

**Review by WJohn — APPROVED** [review]
Sprite looks fine enough.

**Comment by Slignerd** [comment]
The command channel should be on by default.

**Comment by Nilons** [comment]
Maybe if there was a way to learn it?  It would require changing the flavour text a bit though

**Comment by CosmicScientist** [comment]
@Jazaen I'll look into making sure 'lings inherit languages in a different PR - that's something that needs to be in the game without considering this PR unless you want to know which lizards or brain damaged individuals are valid.

@KorPhaeron if you want to disguise as a head of staff, either be a 'ling, wear their clothes or buy a disguise kit. I don't know if the disguise kit's essential mask still erases your hair/beard/glasses for metagamers to out you - no-one trusts a Captain/HoP/HoS without glasses. Then try not to be noticed, or rather, don't bother saying anything because that's standard procedure for any role, disguise or not. If you're a lizard, fly person, moth person, plasmaman or other species, then you have bigger problems than your tongue... or rather lisps and bzzzing are one of many of your problems, especially if you're trying to disguise as one of these species. There are already too many flaws with current disguising methods that anything more than fleeting glances, no eye contact, no verbal contact, loyalty implant, low ranking position no-one cares about, will require a backup plan. I could include a cheap language book to uplinks that lets you learn one language of your choice.

If you want me to, I can add an expensive ID locked crate to cargo with a one use instruction manual for the language but if you want to play a head of staff, you should be queuing up as one in the lobby. Does setting someone to being a head prevent another one from signing up later on or do new HoSes still walk in whilst I'm halfway through equipping their gear?

It's not a parody of the church, it's a parody of stuffy modern politicians and a reference to 40K. Modern politicians try to get brownie points by speaking in latin, I thought it'd be fun if Nanotrasen decided to ape that and enforce it on higher staff as an in-group language. Though if you want it to be a parody of the church, I can give the language to the crusader armour garbed chaplain so they can shout deus vult whilst spreading space jesus to the ashlizards. Maybe it'd make more sense to be called Neo Latin because corporations like new things but then I would cry over spilt milk of a 40K reference lost.

@GunHog high latin fulfils the same role and if you want to be worried about something, it works when tcomms is down and over bounced radios or in the same room, unlike the command channel.

I didn't know silicons understood all current crew languages. Why is it logical to add this one besides consistency? I doubt corporate heads would like an AI being in their in-group. Concerning balance rather than my mental fluff, I'm not sure what would be gained from that besides an easier way for silicons to side with the heads against valids.

**Comment by Kromgar** [comment]
FOR THE GLORY OF THE IMPERIUM OF NANOTRASNE

**Comment by factoryman942** [comment]
this syllable list is almost entirely prefixes and endings and has no ability to create words even vaguely like latin
very good 👍

**Comment by Kraseo** [comment]
-Si ego auferam hanc, moriemini?
-Foret doloribus asperiores repellat...
-Tu es magnus guido.
-...tibi.

**Comment by Kraseo** [comment]
translation: this is a great PR and if you really want to listen into what command's chatting about you should just grab the curator, he's there exactly for that

**Comment by PKPenguin321** [comment]
don't like how this affects disguises but the icons and such are cool

how to test locally with 2 clients
- open Dream Daemon (has an icon that looks like the regular byond icon but green. comes with byond so you should have it)
- run the server through dream daemon
- log in to your byond client and connect via dream daemon
- log out of your byond client (do not close the ss13 window) and connect again via dream daemon
- you will now have 2 ss13 windows, one with the guest client and one with your account's client

**Comment by ExcessiveUseOfCobblestone** [comment]
Ling tests....

**Comment by Armhulen** [comment]
If lings don't copy the languages of creatures they absorb, they should

**Comment by KorPhaeron** [comment]
>its not a parody of the church
>its a 40k reference

And 40k does it because a parody of the church fits the theme of their crumbling gothic super religious empire

**Comment by optimumtact** [comment]
it's me, your local evil maintainer, closing your pr for being bad for the game balance and playability

**Comment by CosmicScientist** [comment]
@factoryman942 a success for literacy!

@PKPenguin321 thanks! I hope my laptop doesn't cry more than normal when running spessmen because that means a lot!

@KorPhaeron we have plenty of anime references. Do I need to go down a list starting with gar glasses and ending with catgrilles that absolutely scream future dystopian megacorp employees and their equipment?

If you want to be pedantic, the name is a reference to 40K because 40K, I've made it high *latin* because old fuddy duddies in a megacorp would want to use an old language of prestige and I never learned of an equivalent that would be fun. Another way to keep the 40K reference would just to be call it high common but that doesn't make it sound special. I'm open to calling it anything but high latin if it being a 40K reference is bugging you.

@optimumtact reee I'll make a checklist and annoy you to reopen it another day.

**Comment by CosmicScientist** [comment]
- [ ] 'lings must steal languages (external PR)
 - [ ] a spare one use high latin language book and/or an expensive ID locked cargo item of the same should be available (in this PR)
 - [ ] traitor uplinks must contain a cheap one use language book because we have enough languages already to warrant this, it could come free in the disguise kit (external PR)
 - [ ] ask Kor what remaining is bad before asking oranges to reopen this
 - [ ] find out if it's better if silicons can understand the language, I have concerns over universal access to perfect & gated information but I can't say a malf shouldn't know

**Comment by CosmicScientist** [comment]
#33651 'lings can already steal languages and are only limited by tongue though looking in tongue.dm that means only xenomorphs have language restrictions but I think a 'ling would have other concerns, or rather the crew would, if a 'ling can turn into one of them.

**Pull request closed without merging**
