### PR TITLE
Makes baton resistance trait more robust against knockdowns

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR makes that batons will not apply their knockdown, if the target has a baton resistance trait.

It will not encourage security for more executions, because it mostly comes from:
1. Heretic ascensions - no one will try to get them alive, because they are to dangerous for that
2. Changeling adrenaline - same as with heretic ascensions
3. Stimpacks - provide stamina regeneration, so you can't immobilize their user in order to cuff and detain
4. Non antag meds(Pump-Up and Ephedrine) - don't give stamina regeneration. So you can just beat the dude untill they will go into stamcrit.

## Why It's Good For The Game

Basically police batons and telescopic batons are very hard to counter, because unlike security batons they are immune to EMP's, and their effect is instant. And even more, taking stimpacks or getting baton resistance trait from any other source will not really help you, because getting knockdowned, even if the knockdown duration is 0.1 from original duration, will make you drop your active held items, and then you can be killed with your own weapon very fast. With this PR this trait will no be useless and would be able to save you from such uncool situations.

## Changelog

:cl: SuperSlayer
balance: Baton resistance trait now prevents getting knockdowned by batons, instead of just shortening knockdown duration
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Very much needed. Telescopic Batons are supposed to have a shorter stun duration. But when you can spam the stun while your already stunned the duration is really infinite in practice.

Hopefully this makes head of staff not so reliant on that OP win stick thing!

**Comment by Colovorat** [comment]
What are the sources for this trait? stimpack, i believe there's also some gene trait right?

**Comment by TymurShatillo** [comment]
> Your "Why It's Good For The Game" says "More balance" and nothing else
> 
> Reorder your description a bit please--Generally your "about" should be the objective description of the change and your "Why it's good for the game" includes the justifications. It makes pull requests like this easier to scan through for sanity.

Ready

**Comment by TymurShatillo** [comment]
> What are the sources for this trait? stimpack, i believe there's also some gene trait right?

I wrote about it in the PR description

**Comment by Mothblocks** [comment]
Ya that's good thanks

**Comment by tuckerorchistra** [comment]
based

**Comment by optimumtact** [comment]
@Mothblocks there are explicitly not supposed to be chems with anti stun resistance

**Pull request merged**
