### PR TITLE
Adds a Nar-Sie summonning theme

### PR DESCRIPTION
**Pull request by ViktorKoL**
https://user-images.githubusercontent.com/44502667/152998126-9c9f6396-0d8a-41e7-98e7-c6fa203cda02.mp4

## About The Pull Request
Attempts at summonning Nar-Sie now play a music track, if it's the first summonning attempt in the past 5 minutes.

## Why It's Good For The Game
Nar-Sie's summonning is an important event and I think it deserves a bit more than just an announcement that doesn't even have a unique voiceline.

## Changelog

:cl:
soundadd: the ritual of dimensional rending now has its own theme
/:cl:

### CODE REVIEW

**Comment by StoneMason** [comment]
super cool

**Comment by Watermelon914** [comment]
I think it's way too long, you should try shortening it down to 8-10 seconds

**Comment by cacogen** [comment]
make it the microsoft sound

**Comment by MrDoomBringer** [comment]
make it the waterphone

**Comment by ViktorKoL** [comment]
To be honest, I wouldn't be very happy with shortening the track, and would like to first think about other possible solutions before resorting to that.

> You have to realise that players will have to listen to a 1 minute music clip every time someone tries to create the nar'sie rune, if one hasn't been attempted in the last 5 minutes. That'll get annoying very fast.

I agree that 5 minutes can be too low, maybe I could even make it only play once per round as I intended originally? I think that could help with this issue.

> I had the same issues with progression traitors and when a traitor unlocked a final objective. Originally, it was around 30-40 seconds long, but it became obvious that it was way too long to be played whenever a final objective was unlocked. 

The main difference I think is that unlocking the final objective is instant - it just happens, and having music play for a while after that when nothing dramatic is happening anymore would understandably feel wrong. Drawing the rune takes almost a minute (intentionally approximately the length of the track) and I feel like it would feel wrong for the music to end quickly while the cultist still stands there not even halfway done with the scribing. I agree though that this can sound bad if they are interrupted early and the music still plays.

> It'll just end up interfering with other sounds and things you are doing and become really annoying; it doesn't need to be this long.

I don't really see that much issue with an eldritch deity coming to devour everything making a disruptive sound. The situation is urgent and I don't think the players should be allowed to do anything in peace in this scenario.

**Comment by Serxule** [comment]
maybe have it so this only plays when nar'sie is summoned? instead of from the rune

**Comment by catrock31** [comment]
> maybe have it so this only plays when nar'sie is summoned? instead of from the rune

nah that point you've ether lost or already one no there's no point in actually play a tension building peace so this plays and signifies we're down to the wire

**Comment by Watermelon914** [comment]
> I agree that 5 minutes can be too low, maybe I could even make it only play once per round as I intended originally? I think that could help with this issue.

The problem isn't the delay, it's just too long of a track. It needs to be shortened to 10-15 seconds maximum.

> I don't really see that much issue with an eldritch deity coming to devour everything making a disruptive sound. The situation is urgent and I don't think the players should be allowed to do anything in peace in this scenario.

It isn't a roleplay concern. It's a gameplay one, it's not going to be nice hearing a minute long music clip every time nar'sie is attempted to be summoned, especially if something quickly goes wrong.

**Comment by ViktorKoL** [comment]
There are a few tracks longer than that already in the game though:

- title2.ogg has 2 minutes, and commonly plays in space
- ambidet1.ogg, which has 30 seconds, playing often in the detective's office

Why is it that these tracks are suitable despite being comparatively long? I don't really see why this case would be much different...

**Comment by MrDoomBringer** [comment]
because they're either lobby music or ambience that automatically stops when you exit certain environments

**Comment by ViktorKoL** [comment]
Last I remember, ambience always played in its entirety even after exiting the area. Maybe it was changed since?

**Comment by SethLafuente** [comment]
Honestly I wouldnt want this song being only at max 10 seconds long thats to short I think keeping its current length would be fine. A sound that goes with the song when the summoning stops would be good instead of it fully stopping probably a whisper sound of narsie or something like that

**Comment by MrDoomBringer** [comment]
Alternatively, you could just have this track only happen after narsie is summoned

**Comment by Bawhoppen** [comment]
I do remember how frustrating the clock cult noises were

**Comment by Serxule** [comment]
> I do remember how frustrating the clock cult noises were

although the clock cult noises were loud as all shit, this I doubt would be, would be much closer to how ambience music sounds imo

**Comment by ViktorKoL** [comment]
Ambience still forces players to listen to a sound though... Is it really that different? Does what caused that sound matter? What if you're doing something sound-sensitive when a longer ambient sound suddenly plays?

About the ritual ending soon: this is a very valid concern that I agree with. I already considered some ideas and I could put more work into the code and make it so that the theme stops when the ritual is interrupted, probably playing a simpler and subtler version of the theme on repeated rituals to not get too annoying?

**Comment by Watermelon914** [comment]
> Ambience still forces players to listen to a sound though... Is it really that different? Does what caused that sound matter? What if you're doing something sound-sensitive when a longer ambient sound suddenly plays?
> 
> About the ritual ending soon: this is a very valid concern that I agree with. I already considered some ideas and I could put more work into the code and make it so that the theme stops when the ritual is interrupted, probably playing a simpler and subtler version of the theme on repeated rituals to not get too annoying?

Just change it to something 10-20 seconds long, it's way too long right now. Ambience is an exception because it can be turned off and gets overriden when you hear new ambience sounds.
The difference, again, is that ambience is ambience and this is an event occuring

**Comment by ViktorKoL** [comment]
I can attempt to create a short version then, but I have doubts it will work well. If I manage to make something I am happy with, I will make a new PR because most of the code will not be necessary anymore. Or I will make an entirely new cultist ambient theme instead or something.

Thanks for patience anyway.

**Pull request closed without merging**
