### PR TITLE
Removes the hat whitelist from the hat stabilizer mod

### PR DESCRIPTION
**Pull request by Momo8289**
## About The Pull Request
This PR allows you to use any hat with the hat stabilizer module. Before, it was limited to a pretty small, very arbitrary list of hats (captain's hats, centcom hats, and a few gimmicky hats), making it disappointingly limited to both the captain, and anyone who finds the thing in maints. I'm guessing this limit was put in place to avoid janky looking hats, but plasmamen get the exact same thing without the restriction, and there haven't really been any complaints there. While I did not test this with every single hat, I *did* test it with every hat currently in the autodrobe, and there wasn't any jank there, even with things like wigs, and hats that cover the entire head.
There was also a bug/oversight where the MOD eating apparatus module didn't properly disable pepper spray protection like it was supposed to. It was literally just a matter of missing parentheses, so i fixed that too.

Not super sure what to mark this change as btw (qol? balance? removal?) so if I should change it, let me know.

## Why It's Good For The Game
Allows both the captain and anyone who finds/steals the module to actually wear the hats they want to wear, instead of being limited to a small, mostly arbitrary list of hats, and having less outfit choice that a plasmaman. 
## Changelog
:cl:
qol: You can now use any hat with the hat stabilizer MOD
fix: The MOD eating apparatus module now properly disables pepper spray protection
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
The hat is cosmetic right? We're not gonna end up with people putting helmets with straps on top of their modsuit helmets for armour?

**Comment by OrionTheFox** [comment]
> I'm guessing this limit was put in place to avoid janky looking hats

As the person who added it that's pretty much why yeah lol

I **personally** think berets should be blacklisted but that's just out of spite :trollface:. I want them to fall off and make people feel foolish.

**Comment by Momo8289** [comment]
> The hat is cosmetic right? We're not gonna end up with people putting helmets with straps on top of their modsuit helmets for armour?

Correct, you get no armour from the hat. However, I don't think it makes much sense if it doesn't cover your face if its supposed to (like the eva helmet), so I'm going to implement that.

**Comment by Momo8289** [comment]
> I **personally** think berets should be blacklisted but that's just out of spite :trollface:. I want them to fall off and make people feel foolish.

Funnily enough, someone talking about how they weren't able to use it with a beret was what brought my attention to this and made me make the PR lol

**Comment by Time-Green** [comment]
I think it's fine, and the original creator doesn't seem opposed to it (which I think is pretty important)

**Pull request merged**
