### PR TITLE
Tones down footprints

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
tweak: Footprints have been toned down
/:cl:

footprints

### CODE REVIEW

**Comment by bigfatbananacyclops** [comment]
yeah its pretty laggy too, please.

**Comment by CitrusGender** [comment]
image
not binding since it's obviously not a serverwide poll, but I've noticed that shit has been looking really bad recently. If not remove them, then make them lose less blood on step since this it's really been shitting up the station.

**Comment by ninjanomnom** [comment]
Just disabling something because it breaks is not something I want to be encouraging. The problem needs to be fixed not shoved under the rug.

**Comment by octareenroon91** [comment]
Maybe _TESTMERGE ONLY_ ?

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Fix the issue instead of just disabling it.

**Comment by CosmicScientist** [comment]
Remove the code. Leaving broken code results in more bugs, wasted processing and confused readers. e.g. this doesn't fix the decal stacking problem stated by comments on your issue that was supposedly a problem back with #13805

The last one to touch footprint code, #32056, left it more confusing than necessary (two types of bloodloss, step and spread).

**Comment by CosmicScientist** [comment]
Looking back on the footprint code I'm not sure what's up. Decal stacking shouldn't happen unless
[human_movement.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/human/human_movement.dm#L52)
```var/obj/effect/decal/cleanable/blood/footprints/oldFP = locate(/obj/effect/decal/cleanable/blood/footprints) in T
if(oldFP && oldFP.blood_state == S.blood_state)
	return````
is wonky but I assume it works as (true) AND (blood/xeno/oil == blood/xeno/oil)

This all looks like it should work as it is.

**Comment by Mickyan** [comment]
Whatever. I changed the defines so at least they won't cover the entire station 5 minutes into the round although I suspect they will still make your game lock up all the same when there's too many in the same place.

Comparison on top of the page

**Comment by CosmicScientist** [comment]
@SpaceManiac I'll plug in a PR that rectifies that if I don't see a fix when I'm next on.

@Mickyan don't feel persecuted, I assume the maintainers feel the same as ninja: fix, don't disable, and I assume removal would fit under fix.

**Comment by Mickyan** [comment]
The vibe I've got was like being accused that this was a kneejerk reaction and I was too lazy to even try doing anything about it and that annoyed me, is all.

**Comment by optimumtact** [comment]
you are lazy though

**Comment by Mickyan** [comment]
What have you done to fix this in the past 20 days

**Comment by ninjanomnom** [comment]
No one is obligated to code anything, however, you have taken action here to deal with the issue in some fashion. It clearly shows you care enough that you want the problem dealt with, but the method you chose is lazy.

**Comment by Tlaltecuhtli** [comment]
the problem is that footprints turn into pools of blood too so every time someone walks into a footprint he is gonna generate a new trail of foot prints and so on

**Comment by Mickyan** [comment]
@ninjanomnom You're assuming I didn't try to fix it properly beforehand and just went straight for this. Well I tried, it didn't work out. As you say I can't force anyone to code anything but this has been a pain in the ass long enough and something had to be done about it.

Whatever, arguing about this is a waste of time, I already changed the PR. It doesn't fix everything but it's an improvement.

**Comment by Anonmare** [comment]
I hate footprints, I think they don't add anything to the game except to make the janitor annoyed and upset my need for order

**Comment by Doppeltongue** [comment]
Footprints are great for tracking down dead bodies into maint so that you can become one yourself though.

**Comment by ninjanomnom** [comment]
I assumed nothing, this method is just lazy

**Comment by nicbn** [comment]
This is not fixing the issue, only bandaiding it

**Comment by CosmicScientist** [comment]
:cry:

**Pull request closed without merging**
