### PR TITLE
Gang domination now uses world.time

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
tweak: Gang domination now uses the same timing method as shuttles, making
their domination times more accurate.
/:cl:

~~I am currently unable to test this, if someone could that would be
great.~~

### CODE REVIEW

**Comment by Bawhoppen** [comment]
do nukes still use fake time

**Comment by coiax** [comment]
yes

**Comment by Bawhoppen** [comment]
can we fix that in this pr

**Comment by JJRcop** [comment]
Concluded testing. ghosts see counter okay, round ends okay if dominator reaches 0, it is based off of world.time

**Comment by MrStonedOne** [comment]
I should point out that world.time is not real time, its the true game time. (its incremented by world.tick_lag every byond tick and does not increase while the server has no connected players).

How ever, this is more proper, using a real time (like world.timeofday) is bad as the time is suppose to slow down when lag gets bad enough to slow down movement, and using your own incrementing timer (like it used to do) is just all sorts of bad form

**Pull request merged**
