### PR TITLE
fixes all the bugs you probably didnt know about

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

As mentioned in codebus with the recent patch for circuits being able to produce any item (see https://github.com/BeeStation/BeeStation-Hornet/pull/345), people often make a mistake in attempting to check if a collection does not contain an element. The proper execution of such a check, following the attempted formatting, would be...

`!(x in y)`

But instead we have lots of

`!x in y`

In other words, 1 or 0 in collection y, not good!

## Why It's Good For The Game

Fixes a lot of bugs that likely nobody has ever noticed, probably introduces features that were intended but incorrectly coded. I have attempted to summarize what are probably the effects of this change below. I've moved interesting fixes to the top of this list.

- Dynamic mode ruleset should no longer ignore player preferences when selecting antagonist candidates.
- Pet carriers should now properly cancel callbacks for a mob escaping the carrier if they are no longer an occupant of it.
- Eightballs should now prevent ghosts from voting on answers that are not expected by the eightball.
- Modifying variables in view variables should now prevent you from adding a non-existent variable to a datum.
- The Herald's Beacon should no longer attempt to remove a non-existent voter from its list of users who need to vote. (Likely prevents a runtime)

## Changelog
:cl: bobbahbrown
fix: Dynamic mode ruleset will now respect your player preferences when selecting antag candidates
code: Fixed 9 instances of incorrect not-in-list expressions.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
If I know about any of these bugs im going to be so mad

**Comment by bobbahbrown** [comment]
> If I know about any of these bugs im going to be so mad
> 
> > Stepping onto a space-exposed lattice in the transit z-level will no longer throw you into space. You can safely walk on lattices on the emergency shuttle, for example.
> 
> im so mad

im so sorry, cobby

**Comment by ATH1909** [comment]
> If I know about any of these bugs im going to be so mad
> 
> > Stepping onto a space-exposed lattice in the transit z-level will no longer throw you into space. You can safely walk on lattices on the emergency shuttle, for example.
> 
> im so mad

uh, what does that bug have to do with this PR?

**Comment by bobbahbrown** [comment]
> > If I know about any of these bugs im going to be so mad
> > > Stepping onto a space-exposed lattice in the transit z-level will no longer throw you into space. You can safely walk on lattices on the emergency shuttle, for example.
> > 
> > 
> > im so mad
> 
> uh, what does that bug have to do with this PR?

was something that i thought i fixed but in reality it wasn't broken because !(x in y) is different when looking at !locate(thing) in Y as from what i understand from AnturK the [locate(thing) in Y] is actually executed first

**Comment by TheChosenEvilOne** [comment]
You missed one in dynamic. line 47 in midround rulesets.

**Comment by bobbahbrown** [comment]
@TheChosenEvilOne thanks

**Comment by optimumtact** [comment]
im glad this was not as many changes as I expected

**Comment by wesoda25** [comment]
There are still bugs I probably don't know about that weren't fixed by this 👎

**Pull request merged**
