### PR TITLE
Medbay Changes (Box)

### PR DESCRIPTION
**Pull request by ghost**
medbay

Replaced a few windows with walls, (top windows, windows next to cryo), added windows to the lobby desk with a windoor. Replaced the cell charger with a desk lamp. Removed the left table (the items are on the cryo tables now), and added  Medbay Emergency Entrance airlocks. Replaced the Medical Records console with a Crew Monitoring console.

(There is only 1 commit because I forgot to mapmerge and so started over with --force, I have made the changes)

:cl:
tweak: Side entrance to Box Medbay, a few layout changes.
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
Really don't like the side entrance :-1:

**Comment by FantasticFwoosh** [comment]
Ehh, you could remove the windoor and have a 2 wide entrance at the top and windows on just the left hand corner. It'd look better and more open plan, swap places with the desk lamp and the paper bin

(move the mug down a touch so it isn't colliding with the window if you can)

**Comment by PKPenguin321** [comment]
:+1: Obscured cryo tubes means less wide open viewing spots means more openings to do sneaky traitor stuff means paranoia. Side airlocks are kinda cool but might be bad, worth trying. Front desk windows are pretty much inconsequential.
When you removed the desks under chem, did you put the stuff on them (stethoscope, box of gloves, etc) anywhere else?

**Comment by Iamgoofball** [comment]
Remove the side entrance or remove the MD job

**Comment by uraniummeltdown** [comment]
@FantasticFwoosh Will move the mug down and swap lamp and bin in next commit
@PKPenguin321 The items are on the tables next to the cryo tubes now

**Comment by CPTANT** [comment]
@Iamgoofball 

Merge the MD job with chemist

**Comment by ExcessiveUseOfCobblestone** [comment]
medbaychanges just make me want to strip out a majority of medbay's free stuff and force people to make their own meds.

good changes, although the cell charger is for the defibs...

**Comment by Fox-McCloud** [comment]
👍 Really like the side entrance a lot.

**Comment by Iamgoofball** [comment]
also yeah re-add the cell charger, it's to keep the defib charged

**Comment by Supermichael777** [comment]
the cell charger is still at cryo the one at the desk looks to be gone

**Comment by lzimann** [comment]
:-1: for side entrance

**Comment by Incoming5643** [comment]
Most of these changes have been attempted before and denied before and the situation hasn't really changed. It takes a really good argument to change boxstation.

**Comment by Iamgoofball** [comment]
All airlocks are all access given enough time and tools.

**Comment by PKPenguin321** [comment]
Sure but so are the windows

**Comment by Iamgoofball** [comment]
Same there, they should go too tbh

**Comment by Firecage** [comment]
Goof, so are walls.

**Comment by Armhulen** [comment]
Same there, they should go too tbh

**Comment by uraniummeltdown** [comment]
Alright swapped around the lamp and paper bin, also repositioned one of the pairs of beakers near cryo tubes as it was a bit off.

**Comment by Cyberboss** [comment]
D..did you force push!? REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE!!

**Comment by Iamgoofball** [comment]
@Firecage Walls are way harder to get through than airlocks and windows and a hell of a lot more obvious.

**Comment by CPTANT** [comment]
@Iamgoofball 

No it's not, welder + wrench is piss easy. Meanwhile hacking doors without gloves has a significant chance of electrocuting you.

**Comment by jughu** [comment]
How can a hacked glass door not be more obvious then a wall

**Comment by Firecage** [comment]
@Iamgoofball Well, if you know the wires beforehand. Then sure, hacking in is easy. Though if you don't? That normal wall is piss easy and quick to take down.

**Comment by Iamgoofball** [comment]
Welding's super loud, requires protection, obvious as fuck, with a forced timer delay.

If I hack a door elsewhere to figure out the wires, walk up to the door, screw it open, run off, run by with crowbar and wirecutters, slam down on those buttons then my crowbar hotkey, I can get through the door way faster on the fly

**Comment by jughu** [comment]
Welding isnt that loud and not thwt obvious whrn you hear it it could be a pipe being welded and such
While a door being hacked sound obvious and when crowbarred open also makes a loud sound

**Comment by ExcessiveUseOfCobblestone** [comment]
Goof that's why we have a security airlock feature where, with like 2 clicks, you can make an airlock obnoxiously difficult to hack :)

**Comment by Cyberboss** [comment]
I actually wanna see stats for how many times that feature has been used.
It has to be close to zero.

**Comment by XDTM** [comment]
I used it twice, once with plasteel and once with iron. No hacking attempts yet but i'm sure it will pay off one day.

**Comment by optimumtact** [comment]
@Jordie0608 @MrStonedOne @lzimann @Shadowlight213 @KorPhaeron 
test merge please

**Comment by optimumtact** [comment]
Well I couldnt' get a test merge and the general reaction has been dislike.

**Comment by jughu** [comment]
I auctally like the side entrace it spared me out a longer walk normally and could heal a patient faster

**Comment by Cyberboss** [comment]
Because healing patients fast is totally a docs no 1 priority

**Comment by Supermichael777** [comment]
it usually is

most players have been conditioned not to trust other players because muh pvp

**Comment by ShadowDeath6** [comment]
>healing patients fast is totally a doc's no 1 priority

**Comment by optimumtact** [comment]
I'll teach the admins not to run a poll when I ask

**Comment by Cyberboss** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

On Dec 14, 2016 2:37 AM, "oranges" <notifications@github.com> wrote:

Merged #21971 <https://github.com/tgstation/tgstation/pull/21971>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/21971#event-893211903>, or mute
the thread

**Comment by Incoming5643** [comment]
haha, you know what's cool?

Not merging things out of spite.

**Pull request merged**
