### PR TITLE
Fixes Rapid Mitosis Blob

### PR DESCRIPTION
**Pull request by Iamgoofball**
you were right remie

playtests showed this cut blob rounds down to about 5 minutes with a massive amount of blobs from all the splitting

### CODE REVIEW

**Comment by optimumtact** [comment]
Who would've though that exponential growth would've been bad

:frog:

**Comment by Iamgoofball** [comment]
:^)

**Comment by Incoming5643** [comment]
you could also limit this verb to the "alpha blob"

**Comment by paprka** [comment]
I wish blob wasn't reliant on how many tiles it consumes and instead had a timer or something, blob rounds can go on for hours

**Comment by RemieRichards** [comment]
@Incoming5643 it's limited to all blobs that were not formed from another, which is fine and what I originally intended.

**Pull request merged**
