### PR TITLE
Adds another unused ashplanet turf

### PR DESCRIPTION
**Pull request by ChangelingRain**
It's the watery rock turfs from this pic except the holes don't exist except as sprites at the moment.
this pic

Also fixes mineral turfs not smoothing with indestructible walls.

### CODE REVIEW

**Comment by Kromgar** [comment]
Making lavaland multiple zlevels wide could be interesting

**Comment by TechnoAlchemisto** [comment]
where are my fungi

**Comment by ChangelingRain** [comment]
fungi exist I have the sprites for them right here
http://puu.sh/r2lsX/884498f342.dmi
Rocks, though. Rocks don't appear to exist.

**Comment by TechnoAlchemisto** [comment]
rocks are for chumps bring on the mushrooms

**Comment by ToadStar** [comment]
Ay I gotchu for the rocks @ChangelingRain:

https://dl.dropboxusercontent.com/u/8968392/VHOO.dmi

**Comment by ChangelingRain** [comment]
Oh woo more variations for the turfs~

**Comment by WJohn** [comment]
i need to do more lavaland sprites at some point to do the underground, but thats assuming that kor is actually going to work on that part

**Comment by ToadStar** [comment]
Would it be at all possible to replace the surface rock wall with the other rock wall that's in the game? Since imo it fits the atmosphere a tad bit better imo.

http://i.imgur.com/WozA5ak.png

(Outdated lava sprites are due to this being from a month or two ago, but they still look pretty good.)

All you'd have to do is change a variable in the base mineralturf path and copypaste the ore icons into the dmi for it iirc.

**Comment by ChangelingRain** [comment]
Possible but a shit idea because it's absolutely the wrong fucking palette and meshes badly with lavaland.

**Comment by ToadStar** [comment]
Eh, figured it wouldn't hurt to ask.

**Pull request merged**
