### PR TITLE
Adds a few new types of admin lipsticks/kisses

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
This PR expands on the types of lipsticks available to admins, adding a few new kinds of kiss projectiles based on ideas of my own and from other admins. They are:

- Kiss of Obliteration: The former Kiss of Death has been changed to this, still causes instant heart failure by applying 999 damage to the target's heart.
- Kiss of Death: Now just causes 35 brute and a really bad piercing wound instead of actual instant death, so you can hurt someone without basically removing them from the round.
- Kiss of Life: Provides the target a 15 second buff that slowly heals them and gives them damage slowdown immunity as long as they stay within sight of the person who blew the kiss at them.
- Kiss of Rebirth: Basically a rethemed bolt of healing, full revive.

## Why It's Good For The Game
Adds new content for a fun feature

## Changelog
:cl: Ryll/Shaps
add: Centcom's hybrid fashion/armaments division has released a few new prototype lipstick formulas to select Centcom staff, embued with the powers to harm or heal. Just make sure you don't mix them up!
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
I get the feeling that this feature will, after a month or two, be generally unused by admins - which sucks because it's an unironically interesting/unique weapon-type that IMO should be player-attainable. 

Death and rebirth should probably be Wizard only (if at all) tho.

**Comment by Ryll-Ryll** [comment]
I've been pretty surprised with how much use they've been seeing in general, even four months after they were initially added. I started this PR because enough people asked a funny kiss of death that did damage but didn't instantly round remove the person being hit by breaking their heart organ, then I threw in the healing ones cause I figured why not. I think there's room in the future for player obtainable versions with weaker effects and maybe limited uses before wearing off, though I guess the specifics of how those are balanced would matter quite a bit.

Either way, I figured the amount of use kisses see so long after they were added meant it was worth trying something new with them.

**Comment by legoscape** [comment]
Big Sexy Wizard with big sexy lips doing sexy mage things? Yes.

**Comment by Ryll-Ryll** [comment]
That has nothing to do with this PR and is unnecessary

**Comment by Farquaar** [comment]
Fetish content

**Comment by LazennG** [comment]
lol tg gay fr fr

**Comment by real-thoman** [comment]
some of these would make cool wiz items

**Comment by MrDoomBringer** [comment]
why the close?

**Comment by Ryll-Ryll** [comment]
Not sure what direction I wanna go in with this

**Pull request closed without merging**
