### PR TITLE
>there's already a global list named uplink items

### PR DESCRIPTION
**Pull request by Iamgoofball**
this should fix the meme crate

### CODE REVIEW

**Comment by optimumtact** [comment]
Learn to code

**Comment by AnturK** [comment]
As i said on irc make this use only traitor items.

**Comment by TechnoAlchemisto** [comment]
It's cool if it uses nuke ops too

**Comment by optimumtact** [comment]
except antur is a maintainer and you are not

**Comment by TechnoAlchemisto** [comment]
i am well aware

**Comment by evsey9** [comment]
just fix the fucking crate already
or revert it so it gives bundles
i NEED THEM

**Comment by optimumtact** [comment]
This does actually need to be merged as a fix though

**Comment by AnturK** [comment]
When cargo gets nuke op replacements to spawn that's on you.

**Comment by evsey9** [comment]
Wait does this actually include any item from the nuke op and traitor uplink?
Including reinforcements?

**Comment by evsey9** [comment]
Do you even test your PRs, goof.

**Comment by evsey9** [comment]
Its fucking BROKEN.

**Comment by evsey9** [comment]
There is nothing in null crates.

**Comment by evsey9** [comment]
N O T H I N G

**Comment by evsey9** [comment]
Goof, there is NOTHING in null crates.
Fucking FIX THEM!!!!

**Comment by AnturK** [comment]
OOC Tab > Show Server Revision. Will show last commit on the server.

**Comment by evsey9** [comment]
Oh, thanks.
Well, that doesn't really matter since the server that i updated a hour ago still had empty null crates.

**Pull request merged**
