### PR TITLE
Adds toilet water

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Water from toilets now makes you vomit.
/:cl:

note: the toilet water vomit DOESN'T stun you

### CODE REVIEW

**Comment by swindly** [comment]
Why not make it a subtype of water?

**Comment by KomradeSpectre** [comment]
>inb4 new meta where poisoned individuals drink toilet water to purge toxins

**Comment by Anonmare** [comment]
Toilet swirlie meta powercreep

**Comment by Iamgoofball** [comment]
>tries to add pee and poo at hippie

>gets told to fugg off

>tries to add """toilet water""" to tg

🤔 

i'd ping coiax and his ""'waste product""" PR but I'm still blocked by him over saying it was a shit idea

**Comment by coiax** [comment]
That's not why you were blocked, goofsy.

**Comment by arsserpentarium** [comment]
So toilet water so special,that it won't explode with potassium?
Also what if I'll make dough with this water?

**Comment by Anonmare** [comment]
I want a toilet burg

**Comment by arsserpentarium** [comment]
I don't want,but feature isn't finished.

**Comment by MoreRobustThanYou** [comment]
Even if I made it a subtype of water, the recipes wouldn't work, as recipes use reagent IDs, not types

**Comment by arsserpentarium** [comment]
maybe reactions needs little tweaks.

**Comment by JJRcop** [comment]
Toilet water is on the wrong side of the line between human waste and not human waste.

**Comment by MoreRobustThanYou** [comment]
even _paradise_ has toilet water

**Comment by jughu** [comment]
MRTY "permabanned player and port all paradise features to tg"

**Comment by MoreRobustThanYou** [comment]
i thought about the times as a Clown on paradise where I swiped a syringe then injected toilet water into all of the chef's creations. I think that made an Admin laugh.

let's not mention the time I read the Bee Movie script over a stolen security headset, being bwoinked "OH GOD I DIDN'T THINK YOU WERE GONNA DO IT", having my tongue removed, then ending up in a surgery room with Command and Medical trying to replace my limbs with carrots.

**Comment by Iamgoofball** [comment]
>even paradise has X

paradise also has dog/wolf furries yet you dont see us adding those

**Comment by MoreRobustThanYou** [comment]
@Iamgoofball didn't you try to add them a few times

**Comment by MoreRobustThanYou** [comment]
HMMMM, [let's](https://github.com/tgstation/tgstation/pull/24080) [see](https://github.com/tgstation/tgstation/pull/22799) [how](https://github.com/tgstation/tgstation/pull/22802) [many](https://github.com/tgstation/tgstation/pull/22115) [times](https://github.com/tgstation/tgstation/pull/13171)

**Comment by Iamgoofball** [comment]
;)

**Comment by Iamgoofball** [comment]
regardless, why you be adding pee and poo

**Comment by MoreRobustThanYou** [comment]
@Iamgoofball it's just nasty water from the toilet that makes you vomit, what's not to love

**Comment by kevinz000** [comment]
I dunno, maybe the toilet part? Go back to hippie.

**Comment by Armhulen** [comment]
perhaps every part this is dumb

**Comment by ShiggyDiggyDo** [comment]
SLIPPERY
SLOPE
What's next? Farting? Shitting? Furries? ERP verbs?

**Comment by JStheguy** [comment]
This is dumb, everyone knows spacemen don't shit, the toilets are just there for decoration and to hide space drugs. Spacemen toilet water is perfectly safe.

**Comment by Cyberboss** [comment]
Yeah, this seems unecessary

**Pull request closed without merging**
