### PR TITLE
removes stable plasma and plasma solidification

### PR DESCRIPTION
**Pull request by pudl**
-removes all instances of stable plasma, replacing it with normal plasma
-removes plasma solidification to prevent plasma cloning, as well as a certain unreported glitch that allows for infinite cargo points
-nerfs plasma to 1 tox damage instead of 3
-plasma no longer creates gas when it touches the ground

### CODE REVIEW

**Comment by pudl** [comment]
changelog included

**Comment by Fox-McCloud** [comment]
big :+1:

Would also recommend nerfing plasma to +2 TOX instead of 3, as well. There's really no point to the solidification recipe; botany has no need for it, and Xenobiology can just make plasma sheets directly.

**Comment by pudl** [comment]
@Fox-McCloud done

**Comment by as334** [comment]
While i think removing the stable plasma is a smart plan, I think nerfing it's toxic potential and it's ability to create gas is pretty stupid. I get that it makes sense if you have it in the Chem dispenser, but could you not just replace the solid plasma in recipes with some other chemical and keep the plasma reagent with the same properties? Since when has plasma been over-powered or unbalanced? The dupe glitch makes sense to remove, but the other changes are just sort of silly.

**Comment by Fox-McCloud** [comment]
Eh, Tox amount of 2 would be best; it's still going to be pretty deadly when inhaled or injected, just not lexorin levels of powerful.

As for spawning toxins in the room? I generally agree that that should go, as well just because people can start dumping it everywhere to spawn plasma in rooms.

**Comment by pudl** [comment]
plasma at tox 2 is basically pointless. regardless of whatever you do, in order to make plasma a viable weapon you'd have to do a rather large code rewrite to design it specifically as a poison.
with toxpwr of 3, it would be useless as a poison (hence why no one uses it as a poison post goonchem) because it doesn't have the devastating effects of most other poisons.
regardless of plasma's toxpwr, it will never be a good toxin. there's no reason to give it the potential if it'll be wasted anyway.

**Comment by Fox-McCloud** [comment]
@pudl 
There's still stacking multiple poisons together.

**Comment by Iamgoofball** [comment]
i'd say just go with 2 TOX for now.

**Comment by Cheridan** [comment]
pudl you don't get why it's at tox 3. when you breathe plasma gas, plasma reagent is added to your bloodstream. that's why it hurts you. this makes plasma gas 3 times less deadly to breathe. 

plasma reagent making plasma gas when spilled is interesting. 
if something's bugged then fix the bug, not the whole feature. The point of solidifying plasma is so that there's a method of conversion between the 3 states of plasma, solid/liquid/gas.

None of these changes are for the better.

**Comment by Iamgoofball** [comment]
@Cheridan does anyone even use plasma solidification?

**Comment by pudl** [comment]
it's up to 2 now

**Comment by Lumipharon** [comment]
It doesn't matter if it gets used infrequently, there is no reason to remove it.
It's like removing the iced beer recipe that used frost oil. Sure it's rare, but it makes perfectly reasonable sense and nothing was gained by removing it.

And why remove the plasma spill thing? This just makes plasma dumb and safe, hell spilling a beaker of plasma generates BARELY ANY plasma gas, normal spills in chemistry won't even fill a third of the room. It's ONLY an issue with plasma smoke because smoke is shit code.

**Comment by pudl** [comment]
cryox isn't going to use plasma forever, it's going to be changed to space fungus once goof gets to it

**Comment by Fox-McCloud** [comment]
@Lumipharon 

Plasma is in the dispenser itself, so you can't "lose' it; that's why the plasma solidification recipe is being removed; with frost oil getting axed and replaced with cryostylane, chemists WILL make cryostylane+plasma = plasma sheet all day long (or R&D for phazons...).

**Comment by xxalpha** [comment]
No reason to nerf plasma or remove a feature. Don't fix this by removing things, please.

**Comment by Lumipharon** [comment]
Fox what are you talking about? This PR is getting rid of stable plasma. That's the new shit that's available from the dispenser. The solidification recipe uses normal plasma, which you get from grinding plasma sheets.

>-removes all instances of stable plasma, replacing it with normal plasma
Means that things that require stable plasma now (like cryox) will require real plasma which is a limited resource.

**Comment by Fox-McCloud** [comment]
I think you missed it.

Stable plasma is getting replaced with regular plasma in the dispenser, so you have an unlimited supply of plasma.

Furthermore, frost oil is getting replaced with cryostylane (which has a recipe that can be made from the dispenser), which necessitates this change.

'stable plasma' was an extraneous reagent created PURELY because of the plasma solidification recipe; with its removal there's no need for this useless reagent anymore.

**Comment by Thunder12345** [comment]
It was also safer to handle than normal plasma, as it doesn't turn into a potential inferno when spilled.

**Comment by pudl** [comment]
napalm's recipe is being changed with goonchem, just wait for goof to do it

**Comment by Thunder12345** [comment]
So why not wait for goof to mess with plasma too?

**Comment by pudl** [comment]
because i had a personal convo with him and we agreed that this should be a totally separate pr as opposed to being bundled with other changes. im not going to touch napalm because goof is going to rewrite it completely so i dont want merge conflicts

**Comment by Thunder12345** [comment]
Also, how was the plasma cloning bug meant to work, couldn't see any way to do it from looking at the code

**Comment by pudl** [comment]
can i tell you after this is merged since the bug lead to infinite cargo points and i dont want it being abused

**Comment by babinsquared** [comment]
It involves cargo and plasma solidification. It's technically been around for a long time but required botany's help. Or a changeling's help if you wanted to get ridiculous.

**Comment by babinsquared** [comment]
I'd like plasma smoke to be a thing because it's an effective tool for traitors.

New poisons are mostly irrelevant when the most potent toxin is literally all of them at once.

**Comment by Iamgoofball** [comment]
@babinsquared oh, they have way way way more effective toxins soon.

**Comment by babinsquared** [comment]
Plasma+cyanide will always kill faster than straight cyanide. The same goes for adding in sul.acid, fl.acid, lexorin, fluorine, welding fuel, chlorine, thermite, toxin, weed killer, plant killer, pest spray, bad food, formaldehyde, and whatever else I'm forgetting.

**Comment by pudl** [comment]
that's why i wanted to nerf it down to 1 tox instead of 2

**Comment by Cheridan** [comment]
How about just don't replace plasma in the dispenser?

It makes no sense that we'd be researching this shit on a dangerous station, that NT would pay cargo for stacks of it if you can just make an infinite amount of it with a machine.

**Pull request closed without merging**
