### PR TITLE
Fix auto genned changelog for med changes

### PR DESCRIPTION
**Pull request by optimumtact**
MERGE QUICK BEFORE ALL THE BUILDS FAIL AND EVERYONE SEES.

### CODE REVIEW

**Comment by optimumtact** [comment]
AHHHHHHHH it was always too late

**Comment by Durkel** [comment]
It's too late, it was always too late.

**Comment by JJRcop** [comment]
@MrStonedOne

**Comment by duncathan** [comment]
Speedmerge for critical medical attention to Travis

**Pull request merged**
