### PR TITLE
Powersink Tc change

### PR DESCRIPTION
**Pull request by davethwave**
For an item that can cripple the entire station it's awfully cheap... So I decided to raise the price to 12tc instead.

:cl: davethwave
balance: changed price of powersink to 12tc
/:cl:

### CODE REVIEW

**Comment by Poojawa** [comment]
Powersinks should really be reworked to basically popping APC breakers instead of acting like a syndicate bomb. Gathers charge, then dumps it into the network popping all APCs in the grid to 'off' like the power failure event. Then it starts getting power again to dump until it's found and disabled.

**Comment by kriskog** [comment]
They are already rarely used as is. Most of the times I've seen them, they've come from surplus crates. If station power is crippled by a power sink, engineering has not done a good enough job of setting up power. You only need to supply more than 2MW, which is easily done with 3 upgraded smes. If it happens early round, well you just gotta go find it I guess.

While 6tc is relatively cheap, power sinks really are quite trivial to locate and shut off. This change just utterly kills them off. May as well just remove it instead.

**Comment by subject217** [comment]
Power sinks are already niche and not used that much, mostly because they're not very fun. Unless someone is using one of the really good power sink spots they pretty much always get found too. I don't think price nerfing this item accomplishes much, it should probably just be reworked instead.

**Comment by PKPenguin321** [comment]
this makes them absolutely useless

**Comment by Bawhoppen** [comment]
I think I changed it *from* 12 to 6 because it was never used once.

**Comment by GuyonBroadway** [comment]
When was the last time you legit saw a powersink?

Usually powering down the station is as much a mallus to the antag as it is to the crew.

**Comment by davethwave** [comment]
If you want to know, I've actually experienced two rounds in a row yesterday with them crippling the entire station until we had to leave...

**Comment by PKPenguin321** [comment]
your crew was full of morons then
either search for the sink (should be easy since you dont need access to open any doors just crowbars)
or bypass the SMESes in engineering and wire the engine straight to the grid to overload the sink

**Comment by ma44** [comment]
https://github.com/tgstation/tgstation/pull/17056 @Bawhoppen

**Comment by Bawhoppen** [comment]
@ma44 So it was at 10TC before I lowered it to 6TC. At 10TC is basically never saw much use iirc.

**Comment by Barhandar** [comment]
>your crew was full of morons then

Bonus: it's a catch-22 because if powersink is nerfed to ridiculous price of 12TC nobody is going to buy it -> nobody is going to get the experience necessary for fighting a powersink -> people will try and justify it being OP.

Seriously, just wire more power into the grid and go around maint.

**Comment by Cyberboss** [comment]
This isn't necessary

**Pull request closed without merging**
