### PR TITLE
Derelict Restoration Drive [WIP-ish]

### PR DESCRIPTION
**Pull request by ghost**
Tired of trying to restore the derelict, to no avail? Frustrated about being a drone on the derelict with no materials to rebuild your glorious Communist station with?

**_No longer!**_

This pull request adds several things to the derelict station that make both restoration and expansion possible and not out of reach (although challenging). First and foremost, below the chapel, there is a crashed cargo ship containing emitters, radiation collectors, plasma tanks, and a hefty supply of metal, glass, and tools. Near this ship are two tiny iron-rich asteroids and a furnace for smelting ores. Finally, a particle accelerator has been added above the singularity generator ruin (which also now has a gaping hole in the side).

Screenshots:
_Warning: Dream Maker screenshots ahead!_

**Asteroids**

**Crashed Cargo Shuttle**

**Singularity Room (field generators and emitters are around as well)**

### CODE REVIEW

**Comment by GunHog** [comment]
Decided not to go with supermatter?

**Comment by Xhuis** [comment]
Naah

**Comment by ike709** [comment]
Restoration badmin events just got way better.

**Comment by Cheridan** [comment]
You'll need to reupdate this with the new shuttle turf types

**Comment by AlexanderUlanH** [comment]
The gravity generator requires 10 plasteel to repair.  You can get that eventually by stripping rwalls, but it would be a nice quality of life improvement if there were some plasma on that asteroid as well.

**Comment by pudl** [comment]
sure to everything except the singulo

**Comment by KorPhaeron** [comment]
Should probably be a suppermatter just because of how laggy the singulo is

**Comment by SconesC** [comment]
if you do keep the sing you should scatter the PA around the room

**Comment by pudl** [comment]
@korphaerom the singulo doesnt lag anymore, the supermatter sure as fuck does since the port still isnt perfect.
lets stop undermining the fantastic amount of work that hg did to save the singulo and give us a good engine.

@sconesc that sounds interesting, but in reality whenever the singulo wasnt set up on asteroid and efficiency 1, it was annoying and pissed everyone off. even if it's supposed to be an abandoned derelict!!

**Comment by pudl** [comment]
whoops @korphaeron

**Comment by SconesC** [comment]
yes also im pretty sure a supermatter radblasts across z levels when it fails

**Comment by pudl** [comment]
that still hasnt been fixed? ayy lmao

**Comment by SconesC** [comment]
it hit me during the 8 hour round a while back so idk

**Comment by pudl** [comment]
seriously i hate the sm as an engine. the teg and the singulo are two engines that are perfect, both on opposite sides of the engine spectrum. the singulo is the ultimate, simplest and nicest to use of all of the "set and forget" engines while the teg is the best engine for ones that require maintenance and attention. the sm is a way over-my-head super-scifi shitengine that falls somewhere awkward on the spectrum and is enjoyed by no one in the game for more than couple gimmick rounds, only people who either have a boner for bay or havent actually used the engine and want to use it for the cool aspect.

**Comment by SconesC** [comment]
The SM is really fun if you know how to do it, but the way it operates is silly and is honestly way more complex than anything else Engineering will EVER be doing.

**Comment by pudl** [comment]
i know how to do the sm, and it isn't fun to me. it feels, more than anything, like a half-assed rehash of the teg that removes everything charming about it in favor of the shitty delamination gimmick and a super deadly crystal that's just an op macguffin

**Comment by xxalpha** [comment]
Solars instead of singulo.

**Comment by xxalpha** [comment]
The pristine PA looks really out of place.

**Comment by Xhuis** [comment]
Will do this later when I have less to work on.

**Pull request closed without merging**
