### PR TITLE
Add tagging of a pr as Approved for Merge

### PR DESCRIPTION
**Pull request by optimumtact**
This is applied when at least one maintainer has approved a PR via the
reviews functionality

The label does not exist because I want to build some consensus about if this is sensible or not

### CODE REVIEW

**Comment by optimumtact** [comment]
@tgstation/commit-access 

To expand on my thinking somewhat

I want an approved PR by a reviewer to stand out to the rest of the team, but I dont' want to enforce the strictness of requiring an approved review to merge a pr, since I think we should always be flexible

**Comment by lzimann** [comment]
How about "code approved" as opposed to approved for merge? Sometimes the code is fine but doesn't necessarily mean it will be merged(mainly balance changes)

**Comment by Arianya** [comment]
Yeah, lzi said what I was thinking, sometimes maintainers are just saying "This code looks fine and doesn't break anything" with an approve, but Kor will weigh in as design lead, for example.

**Comment by optimumtact** [comment]
you can upvote with emojii's gamer

**Comment by Cyberboss** [comment]
I don't see the difference between this and a regular approved review?
Contributor reviews don't trigger anything, while maintainer reviews add a
check to the status box and add the approved notice below the title in the
PR list. This just seems redundant.

Also, code indentation is messed up

**Comment by Cyberboss** [comment]
e.g. 
untitled

**Review by Arianya — APPROVED** [review]

**Comment by Cyberboss** [comment]
^ That approval doesn't do anything I mentioned maintainer reviews do

**Comment by Arianya** [comment]
Yeah I was just testing that myself.

**Review by praisenarsie — APPROVED** [review]

**Comment by optimumtact** [comment]
@Cyberboss I keep missing it, that's why I wanted the label, it can be bright orange

**Comment by KorPhaeron** [comment]
I know cyberboss at least will approve PRs even if he dislikes them to sign off on the code quality, I think this tag might be confusing

**Pull request closed without merging**
