### PR TITLE
Delta drone bay + starboard bow maint changes

### PR DESCRIPTION
**Pull request by manofpepsi**
## About The Pull Request

moves the drone bay to the warehouse to give delta its old starboard bow maint back.
image
*glowstick not included
**ai camera moved
## Why It's Good For The Game

gives delta its original maint back for more consistent maint

## Changelog
:cl:
add: The old delta maint is back! (with minor changes), the delta warehouse is now split into two for the drone bay.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
I just wanna say I approve of the map change, but what the fuck does "more consistent maint" even mean lol just say this is better because it is

**Comment by manofpepsi** [comment]
> I just wanna say I approve of the map change, but what the fuck does "more consistent maint" even mean lol just say this is better because it is

consistent as in the current starboard bow maint areas dont have dirt or missing tiles, basically doesnt go well with the other delta maint areas.

**Comment by RaveRadbury** [comment]
Hero

**Comment by 81Denton** [comment]
@EOBGames @ShizCalev This has been sitting for a while

**Comment by EOBGames** [comment]
> @EOBGames @ShizCalev This has been sitting for a while

Yeah, it has been- sorry about that. Anyway, what I was trying to do with the Delta drone bay didn't end up really justifying what happened to the maint, so this all looks good to me.

**Pull request merged**
