### PR TITLE
Modify Diamond Syringe Requirements

### PR DESCRIPTION
**Pull request by ghost**
Engineering 7 Material 5 Combat 3 Makes very little sense. It's not an
engineering problem, its a materials problem. Plus, Sci shouldn't need
to track down a vortex anomaly for piercing syringes. This modifies it
to be Mat 7 (diamond sheet level), Engineering 5, Combat 3.

### CODE REVIEW

**Comment by WJohn** [comment]
I wasn't aware we even HAD diamond syringes.

**Comment by XDTM** [comment]
Engi 7 is one of the hardest research levels to get and this syringe is not more powerful than BoHs or portal guns.

**Comment by Cebasiz** [comment]
>more science buffs

**Comment by BeeSting12** [comment]
wouldnt it make sense for syringes to have a bio requirement too?

**Pull request merged**
