### PR TITLE
Assistants do it for free.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Assistants don't actually have a job, so now they do it for free.

## Why It's Good For The Game

Play something other than assistant.

## Changelog
:cl:
del: Assistants do it for free.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
https://github.com/tgstation/tgstation/pull/54733

**Comment by LemonInTheDark** [comment]
Balance change, wait till november

**Comment by Iamgoofball** [comment]
this is a bugfix for assistant spam

**Comment by LemonInTheDark** [comment]
wait fuck

**Comment by Jared-Fogle** [comment]
thanks lemon

**Comment by LemonInTheDark** [comment]
no problem

**Comment by itseasytosee** [comment]
The money nanotrasen gives isn't real anyways. It's just monopoly money for the vending machines.

**Pull request closed without merging**
