### PR TITLE
Fixes chair backs hiding players

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
tweak: the backs of some kinds of chair can no longer be used to conceal you.
/:cl:

Tactical chairs is the silliest meme.  R. I. P.
New normal Old normal New electric Old electric

### CODE REVIEW

**Comment by dannno** [comment]
comparative pics

**Comment by bgobandit** [comment]
this kills tactical chairs

**Comment by Cyberboss** [comment]
I remember I almost killed someone as an asimov AI because of tactical chairs. It's dumb

**Comment by Supermichael777** [comment]
Fixed an artifact of my file editing as well as making the boarders ~30% lighter.

**Comment by coiax** [comment]
@Cyberboss how does tactical chairs lead you to killing someone as an AI

**Comment by Cyberboss** [comment]
**BECAUSE THE BIRD HAS TO FUCKING DIE!!!**

**Comment by PKPenguin321** [comment]
I feel like this won't help the issue very much since there's not that much new emptyspace on the sprite, and the chair just looks grosser for it

Can we not just have humans render over it even when it's facing up, then when buckled set the chair's layer higher? Hold on I'll make this

**Comment by PKPenguin321** [comment]
Don't merge this my PR does the same fix but without butchering the sprites

**Comment by Supermichael777** [comment]
PKP has a better fix. Common sprites (tables, walls, chairs, and floors) need a polish pass but my ideas of quality and style aren't so popular.

**Pull request closed without merging**
