### PR TITLE
Adds feedback tracking to SDQL button

### PR DESCRIPTION
**Pull request by silicons**
:joy:

### CODE REVIEW

**Comment by optimumtact** [comment]
You should track something useful, like the queries executed, this is entirely useless statistics

**Comment by obscolene** [comment]
if it wasn't entirely useless it wouldn't be a kevinz pr

**Comment by kevinz000** [comment]
@obscolene as can be said for your opinions!

**Comment by Cyberboss** [comment]
Idk, it's better than logging the query text, imo

**Comment by Shadowlight213** [comment]
Just remove kevinz debug.

**Comment by lzimann** [comment]
This is pretty much useless

**Pull request closed without merging**
