### PR TITLE
[WIP] Lavaland Reforged : The Crystal Comet has struck

### PR DESCRIPTION
**Pull request by Djiq**
**IF YOU ARE A SPRITER WILLING TO SEND SOME SPRITES DONT HESITATE~!**

## Setting
An unknown comet has struck the lavaland leaving a huge crator and swallowing the ruins in another layer of compressed ash. The comet contained ancient force of unknown, scientists predict it may be rouge nanites reconstructing themselves into crystalline structures feeding on organic materials causing debilitating deadly illness, psychologist might explain this as a hoax, product of madness, the truth is yet to be unraveled... One thing is known, this mysterious comet has caused a transformation of fauna on lower levels to something maddening, crystals twisting and corrupting into unseen before shapes, the beasts have become more agile, they are stronger, they are deadlier...

## About The Pull Request

This pr reworks lavaland, I'm just starting to work on it but i want to recieve feedback so im opening a draft pr, yay.

What this pr is trying to acomplish is: make loot a lot harder to achieve, add harder enemies, and generally more lategame contents for the most depraved souls that want to be the best miner, while also adding a safe haven for mining with mechs since the top layer doesnt have megafauna except for legion , tendrils nor ruins, just ore, tunnels and randomly spawned monsters.

At roundstart miners will only have access to top level of lavaland, and will have to create ropes to desend into the the crater left by the comet , with each level being more and more challenging but bringing more and more treasure. 

## TODO

- [x] Finish Crystal Goliath     SEE HERE : https://youtu.be/6KUWvYRoxDw

- [x] Finish Disfigured Legion

- [x] Finish Forgotten Watcher

- [x] Remove Roundstart PKA's

- [x] Adds a new Mech and make it spawn on lavaland roundstart

- [x] Add Mech PKA's

- [ ] Finish Crystal Drake

- [ ] Finish Crystal Worm

- [ ] Finish Silenced Collosus

- [ ] Cracked Hierophant

- [ ] Finish Crystalline Anomaly

- [ ] Finish Crystalline Bubblegum

- [ ] Finish The Thing From The Stars

- [ ] Add more z levels

- [ ] Add more ruins

- [ ] Remove random unthematic ruins like 7 sins ruins in favor of somthing with more taste for the setting

- [ ] Move tendril loot to be megafauna drop, add randomization to the pool and some exculsivity of the items.

- [ ] Add Bossrush

- [ ] Move too op items to admin spawn only / Boss rush rewards

## Map Edits 
Other than the massive crater i changed how the mining base looks to acommodate for the mech mining.

image

The mechs you see in this photo are called 10-CNT (tencent reference). They have no niche and their lore is that they are space-chinese ripley knockoff. They are slightly faster than ripley, but lack internal compartment , have lower health and lower armor values. 

## Why It's Good For The Game

Making OP loot actually hard to aquire is a good step forward to making mining an actually interesting job. This pr resolves the catch 22 situation in the best way possible. Before we couldnt make mining more interesting since it was op, but we also couldnt make it less op since mining ore is not intereting. So i'm planning on making the OP loot very hard to get and in limited quantities, while also leaving room for making mining more interesting.

## Changelog
todo: finish this
:cl:
/:cl:

If you see any errors it is cause im writing this while kinda drunk sio yeah.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
still no proper firewall, but it's something

**Comment by TheMidnightRose** [comment]
I honestly cannot wait. This was something realized in a similar vein to Icemoon. where the upper level are safer than the lower levels. Having all the megafauna on the lower level but Legion makes it even better as it will decrease the possibility of people pulling Bubbles or an Drake to the station.

**Comment by MrDoomBringer** [comment]
is this compatible with the lavaland hackmd design doc?

**Comment by necromanceranne** [comment]
Glittering gold, trinkets abs baubles. Paid for in blood.

**Comment by IndieanaJones** [comment]
I'll remain skeptical until I actually see what design choices you're going to make.

**Comment by tralezab** [comment]
MrDoomBringer commented 4 hours ago
is this compatible with the lavaland hackmd design doc?

**Comment by XDTM** [comment]
More content is nice, but if it's only making things harder it won't do anything to solve the core issues of lavaland.

**Comment by LemonInTheDark** [comment]
I agree with XDTM, if all you do is make it harder, we don't solve the inherent miner loot station side issue.

**Comment by Pugie** [comment]
> will have to create ropes to desend into the the crater left by the comet

NOOOO I DONT WANNA GO TO BRAZIL NOOOO STOP AHHH

**Comment by Dorsisdwarf** [comment]
*crater

**Comment by EdgeLordExe** [comment]
Main problem with lavaland is how easy the loot is to get, since best shit comes from tendrils, and tendrils are just damage sponges.

**Comment by EdgeLordExe** [comment]
so im fixing that

**Comment by interestingusernam3** [comment]
>MrDoomBringer commented 4 hours ago
is this compatible with the lavaland hackmd design doc?

The echoes of his mindless tittering reverberate maddeningly...

**Comment by RuneQuester** [comment]
lavaland is now dungeon

**Comment by XDTM** [comment]
> 
> 
> Main problem with lavaland is how easy the loot is to get, since best shit comes from tendrils, and tendrils are just damage sponges.

The problem is more that the loot is too strong when interacting with the station.
By tweaking the difficulty you're mostly only altering the percentage of miner players that get the loot.
If the loot is causing problems, then the loot should be changed, or made inaccessible until a certain condition is satisfied.

**Comment by EdgeLordExe** [comment]
> > Main problem with lavaland is how easy the loot is to get, since best shit comes from tendrils, and tendrils are just damage sponges.
> 
> The problem is more that the loot is too strong when interacting with the station.
> By tweaking the difficulty you're mostly only altering the percentage of miner players that get the loot.
> If the loot is causing problems, then the loot should be changed, or made inaccessible until a certain condition is satisfied.

Im gonna adress that too in the pr, im not just moving loot i will rework a lot of it too

**Comment by GuillaumePrata** [comment]
Are you planing to add station 'rewards' for miners doing their work other than ores?
One issue I always had with mining is that they cant do much for the station other than get ores and the occasional lavaland RNG loot like healing staff or doing security job later in the shift with powerful gear...
One silly thing I looked into coding myself in the past was station rewards over killing megafauna, so the station is pushed to buff miners with Nanites, Chemicals, Surgery and others to make it more likely they can achieve that, cooperation instead of pure skill like it is right now.
You killed a megafauna, here choose one of these prizes to be delivered to the station Captain, and then command can talk around which ones would be more useful that shift.

**Comment by TheMidnightRose** [comment]
Possibility to add Tech disks as rewards in the possible loot drops, All crystal themed. Tools, materials, power generation, weapons(at risk to infect station with mutagenetic crystals), Shuttles, exports, Bepis items.

**Comment by JebHawkins** [comment]
While you have utterly shafted mining with some of the nerfs. I actually do quite like this idea of adding layers of mining. I'll give this a chance and I can't wait to see what you do.

**Comment by IndieanaJones** [comment]
Oh cool, random shotgun-esque blasts given to the "harder" basic mob variants.  Taking some of the finest design concepts from the Colossus, because everyone loves his epic random spread attacks

**Comment by EdgeLordExe** [comment]
> Oh cool, random shotgun-esque blasts given to the "harder" basic mob variants. Taking some of the finest design concepts from the Colossus, because everyone loves his epic random spread attacks. If you want my advice, giving trash mobs random shottie spread isn't a good idea, giving them an attack which you can use skill to combat would be better design.

actually yeah i will change it to something more dodgeable

**Comment by wesoda25** [comment]
image
Finally

**Comment by LemonInTheDark** [comment]
would this be compatible with mech mining/hunting?

**Comment by MrDoomBringer** [comment]
fuck its not a lavaland design doc its a mech design doc
anyways yeah is this compatible with https://hackmd.io/@tgstation/HyzY1TDw8
also
image
is this still a thing or

**Comment by Couls** [comment]
yeah I don't think this would pass as a rework to existing content, considering it plans to add a brand new theme and multiple new fauna and megafauna

**Comment by Pugie** [comment]
Don't worry the easy fix is removing the design doc

**Comment by EdgeLordExe** [comment]
the main part of the rework is locking the gear behind admin only content /or moving it to a lot harder enemies, this qualifies itself to be a rework since it moves the op part of lavaland to either admin fuckery or extreme skill.

**Comment by Couls** [comment]
I think this fits more in the overhaul category than it does a rework and it’s kind of a stretch to say this tweaks and improves on existing content but does not add anything new but I won’t step on your toes here and if this is really what you want to do I wish you luck my man

**Comment by wesoda25** [comment]
Is restricting lavaland loot to robust players really a good solution? I’d much rather the loot be overall weaker, while not as difficult to obtain, as opposed to restricting it to the best. 

That being said, making it take more time to be able to acquire said loot is very good.

**Comment by EdgeLordExe** [comment]
> Is restricting lavaland loot to robust players really a good solution? I’d much rather the loot be overall weaker, while not as difficult to obtain, as opposed to restricting it to the best.
> 
> That being said, making it take more time to be able to acquire said loot is very good.

it will also be weaker. not just restricted, but also weaker. god

**Comment by IndieanaJones** [comment]
> it will also be weaker. not just restricted, but also weaker. god

You're going to have to make some cool loot if you want people to risk even more than they do now for weaker items.

**Comment by TheMidnightRose** [comment]
@MrDoomBringer Far as I know, PRs modifying offstation content can continue with Maintainer approval, The Lavadwarves PR was continued past Testmerging though it never was completed fully and was removed from testmerge. It was approved by a maintainer.

**Comment by Spepbuthewranglesgithub** [comment]
got to love the color of madness influence / actual mining progression. on the other hand the loot nerfs/relocation and ruin removal worry me.

 
i really do _not_ want to fight bubblegum just to get the concussive gauntlets nor lose my memento mori to the admin pit.

**Comment by TheMidnightRose** [comment]
As much as I love the Mech PKA and Mech idea. You might want to split them from this PR for now or ensure that you get the Maintainer behind the Mech hackmed to approve it

**Comment by optimumtact** [comment]
if you implement the firewall of mechs on lavaland, and rebalance so that high level combat loot applies to the mechs, not to the miner, you are free to add Mech PKA's and whatever else you want to them and you're free to rework lavaland however you see fit.

**Comment by optimumtact** [comment]
also have you considered making the first z level entirely free of mobs? that way someone who just wants to mine can do that.

**Comment by Couls** [comment]
it was nice knowing you

**Pull request closed without merging**
