### PR TITLE
Hoop, Shoot, Ball. A New Emergency Shuttle For All.

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Heya there,

Given the recent hype around basketball (no idea what that's about), I decided to try my hand at making a new emergency shuttle built around a full(ish) scale replication of a basketball stadium! Check it out!

Pretty nifty, eh? I'm fond of it. I spent a while doing the decalling, and I found it to be rather fun. Do keep in mind that the rest of the shuttle is rather "shitty" but it's social commentary don't worry about it.

image

## Why It's Good For The Game

New shuttles are always nice to have, especially now that we're having a conformational rework to how b-balling and dunking works in game (with #66960 on the horizon), it'll be rather good to have something for people to work for (training up for the big game on the shuttle).

## Changelog

:cl:
add: There's a new shuttle! You can now purchase "Basketballer's Stadium" from your station's communications console in order to get some good time in bouncing around a ball and making those sneakers squeak against the well-polished floors. Enjoy!
/:cl:

### CODE REVIEW

**Comment by notfrying1pans** [comment]
balls

**Comment by tralezab** [comment]
is this really a real engine setup on a shuttle in the year of our lord and savior plus 2022?

**Comment by tralezab** [comment]
image
i just cannot forgive this

**Comment by san7890** [comment]
> image i just cannot forgive this

it's fine don't worry abou tit

**Comment by Jolly-66** [comment]
San the thrusters is the most cursed thing I've ever seen you map I will strangle you

**Comment by san7890** [comment]
> San the thrusters is the most cursed thing I've ever seen you map I will strangle you

don't worry about it

**Comment by dragomagol** [comment]
image

You might want to throw a `can_buckle` on here like the escape bar does (or better yet, make a bucklable subtype of the barstool), so sec can buckle cuffed prisoners here. Also probably too small, since if people are buckled to the seats you can't move past them.

image

Could use a fence or divider of some kind to prevent interference?

This shuttle is also really square. Which is not always a bad thing, but it makes the shuttle a little uninteresting to look at overall. 

That being said I really like the concept, and you did a good job with the decals in the middle.

**Comment by GuillaumePrata** [comment]
Adding some red/blue clothing in a corner would be a nice touch, help organizing the teams.
Yes, people will almost never be capable of having a proper match there but trying is the fun part.

**Comment by san7890** [comment]
@dragomagol Thank you for the advice.

I added can_buckle to the seats, thanks for that. It's really cramped by design because I'm a filthy slob who liked the social commentary I was going for and the juxtaposition between the nice-looking basketball stadium with intricate designs and the totally dogshit "shuttle" facilities.  I might come back and give the brig more space... but I think I like the design of it being just a place for any "referee's" to slam people in for a period of time, while also disintentivizing people to pass through. It's a small, cramped brig... and I kinda also want people to feel "bad" about locking people in such poor conditions while the rest of the station has fun.

I thought about having a fence or other divider in, but I didn't want to inhibit free-flow, and also if people want to get invested in the roleplay, they can play the ball again when it goes Out-of-Bounds rather easily.

I don't really see any feasible way to make the shuttle "less square". I am also strongly resistant to changing the engine placement _precisely because_ it's very ridiculous... a theme I'm trying to keep intact.

---

@GuillaumePrata There's nothing in game that really screams "jersey" or something similar, unfortunately.

**Comment by san7890** [comment]
I actually reneged on the brig and updated the layout, the new version is in the PR description.

**Comment by GuillaumePrata** [comment]
> There's nothing in game that really screams "jersey" or something similar, unfortunately.

Time to keep saying that the spriters aren't ballers until this situation gets fixed

**Comment by Farquaar** [comment]
There needs to be a tile between the court and the seats. Otherwise the ball can't go out of bounds and people can't do throw-ins.

**Comment by wesoda25** [comment]
Hoopin on the shuttle!

Some railings or something would be welcome tho

**Comment by san7890** [comment]
> There needs to be a tile between the court and the seats. Otherwise the ball can't go out of bounds and people can't do throw-ins.

That's a good criticism assuming that we were doing this in real life... but we aren't. Chairs aren't dense objects, you can freely move through them or kick them away for the purposes of playing a game. The environment is mutable, and I don't think it would look rather great if I were to open up the shuttle by that margin...

I might play around with the concept. If you don't see another commit labelled "DAMMIT", I probably couldn't make it work.

**Comment by VladinXXV** [comment]
>There's nothing in game that really screams "jersey" or something similar, unfortunately.

How about some colored hazard vests? Can't you change colors using Mapper Magic:tm:?

**Comment by fippefi** [comment]
ok, with that amount of thrusters I expect everyone to be slammed into the wall when the shuttle leaves instead of just being knocked prone. otherwise, sick shuttle. ballin, even.

**Comment by san7890** [comment]
> > There's nothing in game that really screams "jersey" or something similar, unfortunately.
> 
> How about some colored hazard vests? Can't you change colors using Mapper Magic™️?

That's not really how that works, unfortunately. If there were code functionality (and even more so, sprite functionality), it would be feasible yes.

> Hoopin on the shuttle!
> 
> Some railings or something would be welcome tho

Fine balance between drop-in and drop-out that I don't really want to tamper with, i might play around with it some more but I don't really think there's a great way to address it without other considerations. I don't want to inhibit the flow or inhibit potential chaos that could erupt on the shuttle. 

> ok, with that amount of thrusters I expect everyone to be slammed into the wall when the shuttle leaves instead of just being knocked prone. otherwise, sick shuttle. ballin, even.

I was thinking of adding the knockback variables to this shuttle but I decided against it due to the limited time people get to enjoy the shuttle for.

**Comment by bruhlookatthisdood** [comment]
rename the security portion to the penalty box

**Comment by san7890** [comment]
> rename the security portion to the penalty box

It is!

> We could use generic red and blue jumpsuits potentially. Edit: It is a space themed basketball court of course!

I'll look into that but I'm not sure how many people will spring for a jumpsuit change since that dumps everything in your inventory aside from your backpack (and maybe suit storage slot)

**Comment by Likteer** [comment]
> There's nothing in game that really screams "jersey" or something similar, unfortunately.

I have a weird solution for team outfits: showers attached via plumbing to tanks with red and blue dye. Need to be pre-multitooled to turn off the water recycler which would otherwise instantly undo the coloring.
obraz

**Comment by Jezzared** [comment]
> I don't really see any feasible way to make the shuttle "less square". I understand the complaint that it's uninteresting- but it's built around a basketball court (which is always rectangular). There's no real great fantastic solution without keeping the themes I'm trying to retain (that I can think of). 

Perhaps try to make the shuttle ball-shaped? You can still have the rectangular court in the middle, but it'll provide more space on the top and bottom for stuff. More space for facilities (or at least more interesting room designs), and maybe on the bottom even locker rooms?

**Review by SuperNovaa41 — APPROVED** [review]
codes fine (obviously)

**Comment by Son-of-Space** [comment]
If you're going to have the directional windows anyways why not have reinforced windoors instead of airlocks? Would look a lot better
image

I hate to dogpile but everyone who has mentioned it is right that the engines are a sin against nature.

IF you're going to be ballin', may I present a better solution to your ship design than a rectangle?
image

**Comment by san7890** [comment]
> If you're going to have the directional windows anyways why not have reinforced windoors instead of airlocks? Would look a lot better

It may look a lot better, but the design principles of this shuttle state: "All is shit, except for the court. All hail the court." The people who manufactured this shuttle aren't excessively concerned with the finest materials for the non-court stuff (or the structures used to propel the court)- they just take whatever sounds passable-at-best (while still keeping costs high).

That's pretty much what I approached this whole build with, I did toy around with windoors after I did the current configuration you see... but I think it adds that extra level of "wow, this shuttle is dogshit! nice court though."

**Comment by ArcaneMusic** [comment]
Why not a wooden court?

**Comment by san7890** [comment]
> Why not a wooden court?

We don't really have the "lighter" wood colors that you could use for basketball courts (or at least how I view them). Also, all the decalling inserted was made to be used with base iron flooring, and it looks worse on normal wood (just checked).

image

I'll stick to the more "pavement" style of basketball.

**Review by Maurukas — APPROVED** [review]
I've been convinced of the 'artistic merits' of the engine. Tests good locally, so let's go.

**Pull request merged**
