### PR TITLE
Remove poisoned apple

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
This thing is unused and unusable in its current state. Completely worthless to keep around, admins can VV it if they need it.

:cl: Naksu
code: removed unused poisoned apple variant
/:cl:

### CODE REVIEW

**Comment by QualityVan** [comment]
*removes posioned apple

**Comment by Buggy123** [comment]
Don't play botany, but isn't this a pretty much the exclusive source for botanists to get zombie powder?

**Comment by ChangelingRain** [comment]
If it was obtainable by anything but xenobio, then yes.
Practically this is literally impossible to get and really, really not something we'd want botany able to easy access.

**Comment by arsserpentarium** [comment]
Well,at second thought, better to leave them as it is. Because it obtainable with xenobio, but extermely difficult. and has very potent reagent.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Buggy123 that's partially true. Botany can mass produce the limiting reagent of zombiepowder (and now with the morphine recipe they may even be able to make it entirely inhouse)

**Comment by Buggy123** [comment]
Wait, so... should i just put it back to zombie powder?

Because I'm thinking that the brass apples should probably be a new one anyway.

**Comment by ExcessiveUseOfCobblestone** [comment]
zombie powder hasn't really seen the stun-duration nerfs (to my knowledge) that other chems have since it has widely been underused since it's removal from the parapen.

as it is now they still have to get the other reagents, copper (almost certainly inhouse) and morphine (MAYBE inhouse but certainly medical), which imo is alright considering the above.

With that said though, botany could just skip the stun part and send you to crit just as rapidly if they know what they're doing (thankfully most don't).

**Comment by Buggy123** [comment]
Can't they make contact grenade tomatoes which crit you in 1-2 hits?

**Comment by Buggy123** [comment]
Oh i just realized i'm on the wrong fucking PR

**Comment by ExcessiveUseOfCobblestone** [comment]
I got hit with some plant this weekend that was like acid and lex and I went from like light green to crit then death with most of my stuff perma-deleted in a few seconds lol.

**Comment by Xhuis** [comment]
[too bad I'll never get a chance to recreate this](https://www.youtube.com/watch?v=qN80_7rNmcE)

**Comment by ExcessiveUseOfCobblestone** [comment]
w-w-w-why not

**Pull request merged**
