### PR TITLE
Blue Security: Not a prank this time

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
Changes security from Red to Blue.
Soon: Changes Command from Blue to Red, once I get the sprites done.

## Why It's Good For The Game

Red is an aggressive color for people who are supposed to be the peacekeepers of the station, and I'm very tired of shitty behavior out of security because they believe they are the ONLY authority on the station.

It is well proven both IRL and in video games that color makes a difference. I'm not going to bother googling for you because only people with no basic thinking skills don't understand this. People act differently based on the outfit they're wearing, this is also a proven IRL thing, talk to any clothing designer. If you don't get out much I can see why you wouldn't have a way to talk to a clothing designer.

Blue is friendly and peacekeeping.
Red is authoritative and important.

Therefore, Command should be Red and Security should be Blue.

126111067-1a4ada91-360c-4a55-9b92-7d9196e4d107
126116475-64dc6c91-a797-4e75-84b8-13fc07b4e6c4

## Changelog
:cl: Paxilmaniac, Iamgoofball
imageadd: Security is now Blue.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
image

**Comment by YakumoChen** [comment]
Years of culture and security imagery ruined because someone decided to quote a research paper for a fucking spaceman videogame is really an immense big think.

Honestly the blue uniforms are immensely ugly and nothing will change my mind for this.

image
Just look at this, it's a blob of grey and blueish grey pixels. they look more like a trash bag than a law officer.

Contrast this man
image
He is instantly recognizable as the guy who wants to ruin your day by shoving a prod baton up your ass.

**Comment by optimumtact** [comment]
giphy

**Comment by Iamgoofball** [comment]
whats ur beef with bluesec, it looks good

**Comment by Iamgoofball** [comment]
>He is instantly recognizable as the guy who wants to ruin your day by shoving a prod baton up your ass.

we don't want security to be the guys who "ruin your day", thats just bad gameplay

**Comment by YakumoChen** [comment]
goof completely misses the point yet again

**Comment by AlinaStarkova** [comment]
> 
> 
> Years of culture and security imagery ruined because someone decided to quote a research paper for a fucking spaceman videogame is really an immense big think. Consider that security's color has less to do with color theory and more to do with actual game design and recognizably of threats.
> 
> Honestly the blue uniforms are immensely ugly and nothing will change my mind for this.
> 
> image
> Just look at this, it's a blob of grey and blueish grey desaturated pixels. they look more like a trash bag than a law officer.
> 
> Contrast this man
> image
> He is instantly recognizable as the guy who wants to ruin your day by shoving a prod baton up your ass.

while i agree with your premise, i will point out, there are ways to make blue work, such as change securities armour and helmets from black to beige, or green, something which contrasts the dark blue. it wont even look out of place since beige and green are military colors which areguably sec is closer to than a police force (military police)

 ... actually, shit make sec a green dept, and make service a beige pepega

**Pull request closed without merging**
