### PR TITLE
Drinking Glass sprite updates

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
This was meant to be just fixing the missing pixel... then it turned to redoing all the glasses in all the basic sprites so they'd match... then redoing sprites that were outdated...
And THEN I realized that drinking glasses can be using the same auto-sprite system beakers have and oh man it's spiraling.

As for the (hopefully) full list of changes:
- Removes all `glass_[color]` icons. Any drink that fell under these will now use the fill_icon and their reagent color. As such, a lot of reagent colors have been tweaked for readability/realism/lemons don't have red juice what the hell man
(Some colors shown are outdated. It is very annoying to tweak these. I don't know how to in-game, if I even can. Relaunching several times is painful.)
image

- Resprites the base `glass_empty`; now it is very visibly empty. The overlay being slightly transparent actually works pretty well with this.  
(Old / New)
image

- Full resprite of Curaçao (now it's actually its beautiful blue instead of gray)
image

- Minor resprites Beer/Green Beer/Iced Beer/Ale
(Yes, Beer/Green Beer have little animated bubbles)
dreamseeker_Z1U2qBxRlx
image
- Minor resprite of Monkey Energy
(It's animated now too but otherwise about the same sprite)
dreammaker_lSqopANAXX

- Minor resprites to Pina Olivida, Banana Juice, Lemon Juice, Carrot Juice - mostly just color tweaks so that they look more believable and the banana juice is less green
- Fixes small nits in the sodas so that they are all consistent
## Why It's Good For The Game
Sprite maintenance and (hopefully) improvements - we've got a lot of drinks in the Bars and the base foundation of that  whole system deserves a bit of love as well 
## Changelog
:cl:
image: redid most basic drinking glass sprites, and moved several drinks to use the same color system as beakers. Please bug report any incorrect colored drinks or juices!
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
If it fixes #87753 then link it in your PR body

**Comment by Loafin34** [comment]
can you add sprites for Candy Corn Liquor, Kong, and pruno? these are all crafted-only drinks, and they deserve some love!

**Comment by OrionTheFox** [comment]
> If it fixes #87753 then link it in your PR body

It does not.

**Comment by OrionTheFox** [comment]
> can you add sprites for Candy Corn Liquor, Kong, and pruno? these are all crafted-only drinks, and they deserve some love!

I'd like to keep this PR to the non-mixed drinks, though another PR to do these might be a good idea. I'll definitely need to update some of the mixed drink sprites that are inconsistent glass-wise anyways...

**Pull request merged**
