### PR TITLE
Fixes the ERP problem.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Adds a camera to dorms 4

## Why It's Good For The Game

If you have nothing to hide, you have nothing to fear.

## Changelog
:cl:
add: Added a camera to metastation dorms 4
/:cl:

### CODE REVIEW

**Comment by Ty-the-Smonk** [comment]
Well shit I was going to do this

**Comment by HomocidlePancakes** [comment]
Everybody knows dorm 2 is the designated ERP location.

**Comment by trollbreeder** [comment]
Oh dear, now i have to bring wirecutters and a screwdriver!
On a more serious note, do this for all dorms rooms for consistency, not just dorm 4.

**Comment by HomocidlePancakes** [comment]
@trollbreeder 
Bruh

**Comment by PKPenguin321** [comment]
Aren't the dorms cameras supposed to start with xray upgrades anyways

**Comment by nemvar** [comment]
Orange man got something to hide :eyes:

**Pull request closed without merging**
