### PR TITLE
Re-Adds Advanced Mop, Adds in Bluespace Trashbag, and Suds up the Janitor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
I really don't understand why this was removed to begin with, but Paprka removed it when he updated the janicart/janiwagon.

In any event, just think this should be re-added; it has an amazing sprite that @nienhaus made, it's a fairly unique item for R&D to make, and it helps out the janitor---and since only one janitor can use the janicart, this would be an excellent alternative for the one who's on foot. Not only that, but the reference is awesome, too.

Pic, from the original PR (the sprite is still in the janitorial icons file):

advmop

This also adds in the bluespace trashbag.

It's functionally the same as a regular trashbag only it can hold double the amount of trash---can be made at R&D: requires bluespace 3 and materials 5; costs plasma, uranium, and gold.

I opted to make this double the amount of things stored in it as opposed to increasing the max_w_class ...for one reason: I didn't want scientists printing these off to use it as a belt that can hold just about anything/everything (it would be functionally superior to military belts...) Maybe someone could make a "Belt of Holding" in the future.

Pics (big thanks to @Nienhaus for the sprite!)

bluetrash

Lastly, this has the janitor start off with a bar of soap in his locker---no idea why he didn't, before--it's logical, makes sense, and helps him be all that much more of a slipmaster.

### CODE REVIEW

**Comment by Jalleo** [comment]
:+1:

**Comment by GunHog** [comment]
Paprika coded it, and removed it in favor of the scrubber upgrade. Janitors were slipping people like crazy with this thing. Add it back :+1:

**Comment by Xhuis** [comment]
While you're at it, a trash bag that could hold normal-sized items would be nice. If you play janitor often, you'll notice shoes and jumpsuits that can't be picked up.

**Comment by GunHog** [comment]
A Trash Bag of Holding would be the best storage item in the game. Did you know that the normal trashbag is <b>the best belt in the game?</b>

**Comment by Miauw62** [comment]
as a regular janitor player, this item allows me to clean up more while not defeating the point of being the janitor.

:+1:

**Comment by PKPenguin321** [comment]
wait, this got removed?
why?
:+1:

**Comment by Fox-McCloud** [comment]
@PKPenguin321 

Because:
>the upgrade would be high research and basically replace the 'advanced mop' which is pretty much useless compared to this

Which I strongly disagree with; both janitors can't have a janicart, and this still can clean areas that a floor-buffer janicart cannot.

**Comment by Fox-McCloud** [comment]
I would need sprites for a bluespace trashbag. If @nienhaus or @WJohn would be willing to make one, then I'd be willing to add in bluespace trash bags.

**Comment by Nienhaus** [comment]
I sent the sprites to Fox.

**Comment by Fox-McCloud** [comment]
Added in the bluespace trashbag.

**Comment by tuypo1** [comment]
it was wise to make the bluespace trashbag based on quantity instead of weight indeed good thinkingfox

**Comment by Xhuis** [comment]
Might be a good idea to let the bluespace trash bag hold items with a w_class greater than 2. Might be overpowered, though.

**Comment by Fox-McCloud** [comment]
@Xhuis 

I specifically don't want to do that because it's effectively giving science the ability to print off toolbelts that can hold *10* w_class 3 objects; while I think the idea/concept of a "Toolbelt of Holding" is a great idea, I think that should be specifically reserved for a toolbelt and not a garbage bag.

**Comment by Xhuis** [comment]
Damn. So much for garbage bags holding shoes.

**Comment by tuypo1** [comment]
Shoes shouldn't be chucked in the trash anyway take them To the locker room or something

**Comment by Jalleo** [comment]
I think you can order more actual rideable carts.

**Comment by Fox-McCloud** [comment]
since this seems to be a janitor PR--went ahead and gave the janitor a bar of soap in his job closet---dunno why he never had one before; it fits his theme, function, and helps him be all that much more of a slipmaster.

**Comment by Niknakflak** [comment]
Belt of holding already existed once on the dead NT branch.  Some nice sprites exist somewhere.

**Comment by GunHog** [comment]
Yes, the Belt of Holding is actually my pull. Obviously not my sprite, but I did enjoy having that item.

**Comment by Fox-McCloud** [comment]
Requesting a review of this, please.

**Comment by GunHog** [comment]
I wanted to stay quiet about this, so I could have access to the <b>best belt in the game</b>, but every Scientist walking around with a *trash bag for a belt* would be just plain sad. They should just have a proper belt of holding instead.

The trash bag is IN FACT THE BEST BELT IN THE GAME. Superior to military belts and genetic belts. 
image

**Comment by Dorsisdwarf** [comment]
Also the Bluespace trashbag looks uglu.

**Comment by Fox-McCloud** [comment]
It's a trash bag---it's not going to be fancy schmancy; it follows the same pattern as the bluespace body bag.

**Comment by GunHog** [comment]
It does not HAVE to be a cyan recolor of the original item. That is the lazy way out. Bluespace body bag sets a bad precedent which should not be continued.

**Comment by Nienhaus** [comment]
I made that for Fox for Paradise, if you guys want a different one have fun
and make a new one.

**Comment by Razharas** [comment]
Not sure about the BS bag
Seems like BS to me
Ayyyyy
But seriously though
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
@Razharas 

Not sure what you're referring to--the bag, in general, or the sprite. If it's the sprite, then someone is going to have to make it, as I'm not even remotely a spriter.

**Comment by Lumipharon** [comment]
This trashbag is super OP considering how OP the normal trashbag is.

The big difference of course is the normal trash bag is extremely rare, where as this is x2 as powerful, and R&D can just pump them out.

Time to carry 100 mags of spare ammo.

**Comment by GunHog** [comment]
I wanted you....

**Pull request merged**
