### PR TITLE
Space Parallax Tweak

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
Upped the contrast on layer 1.
Tweaked the saturation to layer 2.

Current:

version before:
x

Proposed:
xx xx xx

:cl: ChuckTheSheep
tweak: Adjusted the space parallax's contrast to be less vibrant.
/:cl:

[why]: As pretty as it is it's way too vibrant against the station and in general. Maybe this is a personal opinion, maybe it's resistance to change. 🤷‍♂️

### CODE REVIEW

**Comment by Bawhoppen** [comment]
I feel like everyone would get used to it

**Comment by Qustinnus** [comment]
that just makes it look shit again.

**Review by WJohn — DISMISSED** [review]

**Comment by WJohn** [comment]
Thank you. I appreciate the removal of the rainbow colored stars in the background. Those were just nonsensical.

**Comment by ChuckTheSheep** [comment]
Some time to allow for opinions would be ideal.

**Comment by Potato-Masher** [comment]
Good change. It was pretty, sure, but I can only have so much purple in deep space (unless SS13 is in a nebula).

Looking at the new one, however, I almost feel like it could be tuned up just _slightly_. Might just be me being picky though.

**Comment by Iamgoofball** [comment]
@KorPhaeron can we put sprites under the kneejerk revert rule

**Comment by praisenarsie** [comment]
can we get the old parallax back as a preference please

**Comment by WJohn** [comment]
@Iamgoofball just as either kor or I get fucking notified of these major visual changes seen absolutely everywhere *before* they are merged. I didn't even know about the original PR before it was tweaked, and would certainly have said the same thing.

**Comment by ChuckTheSheep** [comment]
@praisenarsie 
x

**Comment by ChuckTheSheep** [comment]
Tweaked it a bit. Not much more is doable, I tried to maintain the colorfulness but not have it be so overbearing.

**Comment by Bawhoppen** [comment]
After seeing it ingame, while it isn't perfect by any stretch, people totally are just being anti-change on this one

**Comment by ike709** [comment]
I like the new one in this PR.

**Comment by ChuckTheSheep** [comment]
New attempt. Took the original clouds and made them "patchy", toned them down a slight bit. Desaturated the stars a bit as well.

**Review by WJohn — APPROVED** [review]

**Pull request merged**
