### PR TITLE
Cyborgs have a reset module wire

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Cyborgs now have a reset module wire, that when pulsed, triggers
the cyborg's reset module hardware.
add: Cyborgs now eject all upgrades when reset, rather than the upgrades being destroyed.
del: Removed redundant reset module.
/:cl:

Because they can't touch it themselves for software reasons. Now you can
ask random assistants to reset you in a pinch, or do it on the FRONTIER.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Doesn't this make the module change board redundant

**Comment by Supermichael777** [comment]
clawing anything out of the autism fort is truly the greatest challenge

**Comment by coiax** [comment]
Yes, it does make the module change board redundant.

**Comment by TechnoAlchemisto** [comment]
Remove the reset board if you're going to make it a waste of materials

**Comment by ExcessiveUseOfCobblestone** [comment]
Engiborg buff?

**Comment by Archie700** [comment]
@TechnoAlchemisto some people are too lazy to do it this way

**Comment by Anonmare** [comment]
Make it a cut instead of a pulse. You might accidentally trigger it while pulsing to find something like the camera wire or the AI sync and, unless something's changed, resetting removes module upgrades.

**Comment by Cheridan** [comment]
@TechnoAlchemisto is right, we shouldn't have redundant stuff, esp. if one way is more costly since it just serves as a newbie trap.

**Comment by GunHog** [comment]
What if the "reset" board made the borg drop all its upgrade chips instead of deleting them? Also, I am worried about this hurting upgraded borgs that are undergoing maintence. The Robo has to pulse all the borg's wires to find what he needs, and may end up destroying upgrades. 

Example: Borg that has been locked remotely, and a Robo needs to unlock it manually. There is now a risk of deleting that borg's upgrades. At the very least, make it a cut function instead, else you might hurt an upgraded borg player that may need help of some sort.

**Comment by Shapsy** [comment]
Leave robotics to the roboticists

**Comment by coiax** [comment]
Changes: Upgrades are now ejected, and the reset board has been removed.

**Comment by GunHog** [comment]
Awesome! :D

**Comment by AdamElTablawy** [comment]
Why are we so against reset boards

**Comment by jughu** [comment]
Nerfing cyborgs to the ground

**Comment by optimumtact** [comment]
Lets give it a go

**Pull request merged**
