### PR TITLE
Makes urinal cakes more realistic

### PR DESCRIPTION
**Pull request by ghost**
urinal cakes are blue irl, they look weird otherwise

:cl: More Robust Than You
spriteadd: Urinal Cakes are now realistically colored
add: You can now squish urinal cakes
/:cl:

### CODE REVIEW

**Comment by Buggy123** [comment]
Wait, what?

1: There's a urinal cake?

2: You can eat it?

3: You can _squish_ it?

**Comment by DaedalusGame** [comment]
screwdriver the urinal

**Comment by MoreRobustThanYou** [comment]
yes but blue makes it look less like a tiny skub

**Comment by RandomMarine** [comment]
@MoreRobustThanYou is anti-skub
CONFIRMED

**Comment by Iatots** [comment]
Now make the operating theather pastel blue.

**Comment by Wilchenx** [comment]
this is disgusting

if you want it on your downstream you play at @MoreRobustThanYou you can PR it there because i'm closing this PR

**Comment by DaxDupont** [comment]
fetish bait

**Review by WJohn — APPROVED** [review]

**Comment by awesine** [comment]
these existed?
how long ago were these added?

**Comment by MoreRobustThanYou** [comment]
@awesine 2016

**Comment by improvedname** [comment]
Make urinal cakes greyscale

**Review by Cyberboss — APPROVED** [review]

**Comment by Belsima** [comment]
im incredibly upset youve done this

**Pull request merged**
