### PR TITLE
Ghosts may now examine silicons to read their laws.

### PR DESCRIPTION
**Pull request by GunHog**
:cl: Gun Hog
add: Ghosts may now read an AI or Cyborg's laws by examining them.
/:cl:

image

### CODE REVIEW

**Comment by Sj212** [comment]
This is pretty awesome.

**Comment by XDTM** [comment]
Finally ghosts will get to witness the meme laws i upload

**Comment by Bawhoppen** [comment]
>inb4 someone says that ghosts will use this to meta with

**Comment by Shadowlight213** [comment]
I'm eh on this, but I think it should be relatively fine probably. Knowing AI laws is relatively harmless for ghosts, but o hope this doesn't escalate into you using this to justify adding full blown ghost antag huds.
Worst case scenario is someone decides to "randomly" reset the AI after they get cloned. I guess the main difference for adminning would be, unless you made this specifically logged, which might be spammy, to have to assume tha every ghost has checked the AI's laws so you better have a damn good IC reason for resetting it.

**Comment by GunHog** [comment]
Would you like it to be saved to the game logs using the `log_game()` proc? Or perhaps another method?

**Comment by KorPhaeron** [comment]
Ghosts can already hear binary

**Comment by KorPhaeron** [comment]
By which I mean they can already meta very easily, probably doesnt matter

**Comment by Shadowlight213** [comment]
@KorPhaeron that was my thinking. Also actually logging it every time would get spammy.
Also KorpPhaeron I swear there was some weird ban at some point where in the appeal the guy argued they never heard the AI say rogue stuff over binary while they were dead or something.

**Comment by GunHog** [comment]
Alrighty. I will leave it as is, then!

**Pull request merged**
