### PR TITLE
Gives Deltastation's and Metastation's armory one more riot shotty

### PR DESCRIPTION
**Pull request by BeeSting12**
Makes it consistent with boxstation, which has three. Both maps are meant for pops higher than box anyways so it makes sense. 

:cl: BeeSting12
balance: Deltastation's and Metastation's armory now starts with three riot shotguns!
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
the new steelpoint

**Comment by BeeSting12** [comment]
actually for some reason meta doesnt have three riot shotguns. maybe im thinking of box or maybe im a fucking idiot.

**Comment by BeeSting12** [comment]
yeah box has three so ill just give every map three for consistency of course

**Comment by BeeSting12** [comment]
wew ok so first i have never died to a lack of riot shotgun i always rush the armory roundstart getting mine first but then i feel guilty about only leaving one

**Comment by optimumtact** [comment]
it's a meme you dip

**Comment by Arianya** [comment]
> i always rush the armory roundstart

`warden vibrates angrily`

**Comment by Supermichael777** [comment]
can we make deltas brig 3 or 4 cells like every other map? its pretty cancerous at the tiny size it has now.
even fucking pubby has a bigger brig and its a lowpop map

**Comment by Bawhoppen** [comment]
Not every map needs to be the exact same :-1: 
Just because one station has something another doesn't, doesn't necessarily justify you adding it to the other

**Comment by Supermichael777** [comment]
delta needs an brig overhaul though its fucking awful, only saving grace is its mercifully small maint exposure

**Comment by ExcessiveUseOfCobblestone** [comment]
>Not every map needs to be the exact same 👎
Just because one station has something another doesn't, doesn't necessarily justify you adding it to the other

Clearly the exception here is with security. Does toxins still not have a mixing room in delta?

**Comment by Arianya** [comment]
I believe the original intent behind Delta's smaller then normal brig was that departmental sec officers would detain offenders in the various departmental brigs, but the low population of sec officers and the low adherence to departmental security has meant that its not really been used that way.

**Review by Cyberboss — APPROVED** [review]

**Comment by BeeSting12** [comment]
@Bawhoppen 
This is more of a "hey it makes no sense that two high pop maps have less of an armory than a med-pop map" than a "all maps must be the same" thing.

@Supermichael777 
Supposedly this is offset by it's departmental cells, which noone uses.

**Pull request merged**
