### PR TITLE
Halves advanced disease symptom cap from 6 to 3

### PR DESCRIPTION
**Pull request by Time-Green**
## About The Pull Request
Reduces the symptom cap from 6 to 3

## Why It's Good For The Game
Symptom overstacking is a big problem of what causes virology to be overly negative or positive. Virology was originally limited to 3-4 symptoms, which was raised overtime as more symptoms got added. I think moving it back truly makes virology not super shitty to deal with.

I realize this severely limits what you can do with virology, but we no longer have to worry about keeping the virologist happy. This makes diseases a lot more enjoyable for the average crewman, even if less people feel motivated to touch virology. I think it's overal okay if it's touched less

This also makes it significantly harder to hit thresholds. I'll remove it afterwards if we get that far

Here's a roadmap for what's next: https://hackmd.io/@O4g2O7RHRN-GPst4jkW46A/r1HpGZp7R, but obviously no promises and I can die or get distracted at any point. Virology will be a little side-project you can do in the meantime, and that's okay. I think full removal would've given more certainty to everyone, but these were the requests MSO laid out

## Changelog
:cl:
balance: Halves the disease symptom cap
/:cl:

### CODE REVIEW

**Comment by zoomachina** [comment]
This doesn't sound particularly bad, but keep in mind that a lot of the symptom thresholds will be completely unachievable as a result. With only 3 symptoms, you'd struggle to put any particular stat above 10,  and you can just look at the [table](https://tgstation13.org/wiki/Infections#Symptoms_Table) to see which ones will be cut (example: supercharged sneezes with stage speed 17). No comment on whether this is good or not, but at the very least unachievable thresholds should be removed from the game(and the wiki) as well.

**Comment by DaCoolBoss** [comment]
I think it's worth keeping in mind that when the symptoms cap was this low, it was possible to have multiple viruses on a single person at the same time.

**Comment by Time-Green** [comment]
> This doesn't sound particularly bad, but keep in mind that a lot of the symptom thresholds will be completely unachievable as a result. With only 3 symptoms, you'd struggle to put any particular stat above 10, and you can just look at the [table](https://tgstation13.org/wiki/Infections#Symptoms_Table) to see which ones don't make it into the cut (example: supercharged sneezes with stage speed 17). No comment on whether this is good or not, but at the very least unachievable thresholds should be removed from the game(and the wiki) as well.

I know, I’ll remove thresholds as well in the neuter removal PR

**Comment by Higgin** [comment]
This has unintended consequences with the viro rework because severity is a function of symptoms/max symptoms.

I'd rather not see it go through as-is without a massive rebalancing of symptoms and stats. It's worth a shot and a lever we can pull on; but it's a lever connected to a lot of other systems that at this time I think should be tweaked elsewhere to avoid the costs of oversights and lost depth that comes from having six symptoms to work with. 

Similar concerns with removing neutering #83454 - it will unequivocally break some things if done in isolation and also raise a lot of policy problems as people adjust.

**Comment by Time-Green** [comment]
> This has unintended consequences with the viro rework because severity is a function of symptoms/max symptoms.
> 
> I'd rather not see it go through as-is without a massive rebalancing of symptoms and stats. It's worth a shot and a lever we can pull on; but it's a lever connected to a lot of other systems that at this time I think should be tweaked elsewhere to avoid the costs of oversights and lost depth that comes from having six symptoms to work with.
> 
> Similar concerns with removing neutering #83454 - it will unequivocally break some things if done in isolation and also raise a lot of policy problems as people adjust.

Í think your PR might be a fair compromise? I'd rather move to 

> This has unintended consequences with the viro rework because severity is a function of symptoms/max symptoms.
> 
> I'd rather not see it go through as-is without a massive rebalancing of symptoms and stats. It's worth a shot and a lever we can pull on; but it's a lever connected to a lot of other systems that at this time I think should be tweaked elsewhere to avoid the costs of oversights and lost depth that comes from having six symptoms to work with.
> 
> Similar concerns with removing neutering #83454 - it will unequivocally break some things if done in isolation and also raise a lot of policy problems as people adjust.

I think your PR is also a fair nerf. I still think the ridiculous complexity you can stuff in diseases is awful, but speeding up the immunity gain also helps a lot in counteracting this

**Comment by Time-Green** [comment]
I like #83459 , wanna see how that plays first. If I come back with this change, I'll merge it with #83454 to also properly remove thresholds

**Comment by Time-Green** [comment]
Leaving open for a few more hours

**Comment by Chocodaemon** [comment]
This is extremely late but virology symptoms used to be a lot stronger/unconditional without thresholds (at least several years ago), thus the limit of 3-4 symptoms. I remember the meta then being something like stacking the basic and advanced brute and burn healing symptoms for double healing which was quite strong. With the current weakened symptoms and threshold system, a 3-4 cap is unnecessary and essentially would kill off the entire mechanic or would require a readjustment of thresholds & stats, as previously mentioned by others.

**Pull request closed without merging**
