### PR TITLE
Cats can have a little salami. (sausage is now slice-able)

### PR DESCRIPTION
**Pull request by OnlineGirlfriend**
## About The Pull Request

Just as it states, sausage can now be sliced into six pieces of salami.

## Why It's Good For The Game

It's cute, it's meme-worthy. Also, salami is one of the best depression foods in the world. Think of the possibilities!

## Changelog
:cl:
add: Sausages can be sliced into salami
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
I demand pepperoni pizza

**Comment by Kraseo** [comment]
little a*

**Comment by ArcaneMusic** [comment]
> I demand pepperoni pizza

If this gets merged I'll get right on it

**Comment by fludd12** [comment]
please let me feed it to runtime

they're good cats, brent

**Comment by OnlineGirlfriend** [comment]
> > I demand pepperoni pizza
> 
> If this gets merged I'll get right on it

Technically Arnold pizza is pepperoni pizza, isn't it?

**Comment by ArcaneMusic** [comment]
> > > I demand pepperoni pizza
> > 
> > 
> > If this gets merged I'll get right on it
> 
> Technically Arnold pizza is pepperoni pizza, isn't it?

Not falling for that one again.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
