### PR TITLE
Felinids like meat.

### PR DESCRIPTION
**Pull request by HoodMilk**
## About The Pull Request

Makes meat a liked food for felinids

## Why It's Good For The Game

Makes them a little different from humans and lets them enjoy meat

## Changelog
:cl:
balance: Felinids now like meat
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
this does not let them eat rats

**Comment by HoodMilk** [comment]
changed the wording to say raw meat instead of rats

**Comment by Qustinnus** [comment]
they can't eat raw meat with this change either

**Comment by Mothblocks** [comment]
Did you get maintainer approval for this change?

> Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

**Comment by maxymax13** [comment]
the unapproved species change has arrived

**Comment by HoodMilk** [comment]
so is it closed purely because I didn't ask somebody or because its actually a bad idea

**Comment by LemonInTheDark** [comment]
Well I'm not sure if it would actually work in the way you're doing, but you need permission for these things

**Comment by Mothblocks** [comment]
you also need to test ur code and not just web edit

**Pull request closed without merging**
