### PR TITLE
Inhands for photo albums

### PR DESCRIPTION
**Pull request by Mickyan**
Adds inhands for photo albums and fixes a grammar mistake with the photographer quirk's albums

:cl:
imageadd: Added inhand sprites for photo albums
spellcheck: Fixed a grammar mistake with the photographer quirk's photo albums
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
the bot is hitler

**Comment by Mickyan** [comment]
1000 hours in ms paint

Screenshot_4

also in case you're wondering the removal tag is because I accidentally used imagedel in the changelog

**Comment by Mickyan** [comment]
actually I just realized that doesn't even make sense give me a minute

**Comment by Mickyan** [comment]
Just removed the corner protectors where they shouldn't be

zzzzz

**Pull request merged**
