### PR TITLE
Replaces "console screen" stock part with glass sheets

### PR DESCRIPTION
**Pull request by ACCount12**
"Console screen": a weird non-upgradeable stock part, not even used in construction of actual consoles, can't be produced by anything but autolathe. Makes building makeshift machines unnecessary hard.

Glass sheet: a common and useful construction material, used as the screen for actual consoles, can be found anywhere and applied to anything.

I think this was an obvious solution.

:cl: ACCount
del: Removed "console screen" stock part. Just use glass sheets instead.
/:cl:

### CODE REVIEW

**Comment by calibraptor** [comment]
Merge this please.

**Comment by WJohn** [comment]
I could have SWORN it was used in more things than the autolathe.

Still though, major 👍 because this has been an annoying thorn in everyone's side for far too long.

Not to mention they're very hard to see, to boot.

**Comment by ACCount12** [comment]
They were used in the construction of many machines, but autolathe was the only way to produce them.

**Comment by WJohn** [comment]
Ah, right.

**Review by ninjanomnom — DISMISSED** [review]

**Comment by Bawhoppen** [comment]
Why not just remove every type of part and replace them all with one?
Or skip that and just go straight to using directly the minerals used to make them? Why make anything have any variation and have a limit on acquiring them, and just make anything buildable any time. 
You make think I'm exaggerating, but these kind of moronic removals are definitely leading us towards that path.

**Comment by WJohn** [comment]
oh fuck off with keeping shitty console screens that are hard to see, almost impossible to make, and inconsistent with what we have already, baw. keeping useless shitty bloat for the sake of useless shitty bloat is useless and shitty

this is not the compacting of all tools and parts in the game, but some are clearly pointless and could stand to be merged or removed. we have four different sets of incompatible part systems. machine parts, telecomm parts, NTcomputer parts, and now device parts, and it's immensely bloated and annoying to sift through. it could stand to be made consistent so that we have item that have more than literally one single purpose in the entire game.

**Comment by ACCount12** [comment]
I'm against removing complexity, but I'm all for removing inconsistent shit that only exists to be an inconvenience to people. If one thing may be merged into another without losing any functionality, it really should be.

**Comment by Bawhoppen** [comment]
How does this not remove complexity? Now you don't have to do anything but welding tool some sand to make this machine part. Limiting the ability for any old random person to be able to build something is watch we should be trying to encourage. (Though it would be reasonable to make it so consoles HAD to use these instead of glass)

**Comment by ACCount12** [comment]
Complexity is one thing. Discouraging people from doing anything complex is another. Complex things may be convenient.

**Comment by kevinz000** [comment]
wtf i like account12 now?!

**Comment by GuyonBroadway** [comment]
Console screens are weird and inconsistently used. For example no console uses them but autolathes and Exosuit fabricators do, so you might think its for any machine that does not need an external console to use but nope. Chem machines do not need them. Most vendors don;t need them but the mining equipemnt one does.

Pick one or the other, in this case I agree with cutting out the needless snowflake and trimming the fat.

**Comment by Qbopper** [comment]
@Bawhoppen keeping snowflake stuff in for literally no reason other than it's a pain in the ass isn't encouraging complexity in any kind of meaningful way

**Comment by Bawhoppen** [comment]
>Anything that isn't perfectly streamlined convenient mechanic is a bad snowflakey pointless "pain in the ass" 

Go home you QoL-babies

**Comment by Qbopper** [comment]
\>if you disagree with me you're a child

opinion discarded

**Comment by Bawhoppen** [comment]
You were the one who started flinging stuff, not me

**Comment by GuyonBroadway** [comment]
So break it down as to why taking two glass sheets, running them through an autolathe to make it into a screen and putting it on a machine is better than just applying the two sheets directly?

It serves no mechanical benefit so why does it add to gameplay in any meaningful way? You cannot upgrade the screen and its not like its material gating like a bluespace crystal. Why would machine construction be any worse without the glass sheets. Its just an unnecessary step for no reason, its not even a delay its just there.

**Comment by Bawhoppen** [comment]
Aside from the fact that it adds the requirement to have access to an autolathe to build something, 
I see things like this, as another one of those changes that degrades anything meaningful interactions and mechanics from the game, under the guise of "bloat", "snowflakiness", and "QoL"

I hate to use the slippery slope argument, but I think it really applies here. If we start doing stuff like this, how long until we decide to just merge scihuds and medhuds? Extended welders are just as pointless to exist, merge them together with regular ones. What's the point of vents and scrubbers being different? Also what about other little annoyances, like robotics not starting with ability to make flashes? And the engine not being set up right away. It couldn't hurt to give R&D a couple sheets of minerals round-start, too.

You may call that a ridiculous leap from removing just a console screen, but I have seen time and time again people try and propose those things in PRs (thankfully usually getting shut down), but that is the path we take when we try and remove anything that is a gameplay road bump like this.

If this were the only change of this nature ever, I'd really not care, but it isn't, so that's why we have to make sure not to go down this route.

**Comment by arsserpentarium** [comment]
I like it. But how about to add all autolathe menu into protolathe? Just for logic sake.

**Comment by ninjanomnom** [comment]
I'm a huge supporter of complexity in the base mechanics being used to improve gameplay, I've fought with @ACCount12 and others to make simulationist style design choices like where it comes to radiation, so don't take this as blindly agreeing to something without thought.

Engineer repair/construction has been in need of QoL improvements for a long time now, the destruction of the station is far far easier than repair ever is. Gameplay wise that means most of the pressure is on preventative action not reactive action. Changes to allow more reactive play which is partially the niche of engineering is good in my book.

The end opinion on this resides in @KorPhaeron but this isn't a slippery slope that's easy to fall down while we have a large amount of the team in favor of more complex systems.

**Comment by KorPhaeron** [comment]
Seems like a reasonable PR

**Comment by CPTANT** [comment]
The stupid part is that actual consoles already use glass sheets in their construction.

**Comment by Aloraydrel** [comment]
Complexity for the sake of complexity is dumb

**Comment by Hatfish** [comment]
what is a console screen even supposed to represent?  screens for real consoles are just glass, so what does the console screen do that those don't?

**Comment by jughu** [comment]
Console screen is touch screen duh!

**Comment by DoctoreMad** [comment]
@Bawhoppen What are you smoking? Pure discontent?

**Comment by imsxz** [comment]
this is bad, and adding even more inconsistency. for starters, this is a HUGE nerf. console screens only cost 200 glass in an un-upgraded autolathe, glass sheets are worth 2000.

additionally, it makes machine construction more difficult. glass sheets can't be stored in an RPED, and take up more space overall, and it will be noticeably more tedious constructing multiple machines using glass sheets instead of console screens, especially if it requires multiple.

delet this

**Comment by jughu** [comment]
Fun fact a stack of 20 glass sheets can be fit in a pocket

**Comment by imsxz** [comment]
20 sheets of glass could have been used for 200 console screens though. Making a machine component cost 10x more, not because it is OP or something, but because it "weird" and only produced in autolathe, is not very good balance. God forbid you go use the public autolathe, or, even worse, *socially interact* with cargo workers to get your console screen.

**Comment by CPTANT** [comment]
O no, the astronomical cost of dismantling a single fulltile window to build your machine.

**Comment by imsxz** [comment]
the astronomical effort of using the public autolathe.

**Comment by KorPhaeron** [comment]
Glass is by far the cheapest and easiest resource to mine I sincerely doubt the station will run out of glass over this change

**Comment by imsxz** [comment]
you say that, and it's true, but some miners often forget/ignore to bring glass back because it doesn't drop out of rocks and they need to bring a shovel for it. they'll come back with 300 metal and 10 glass. if we lived in a perfect world, your argument would have a fair point.

I frequently have to scavenge glass from the windows or other machinery due to minings often neglect when I play as science.

When I play as mining, I always bring the compact picaxe on my first run and dig a couple 3x3 pits of sand, and the station is set for the rest of the shift. Sadly, such a simple task is often ignored or forgotten.

**Review by ChangelingRain — APPROVED** [review]

**Comment by DaxDupont** [comment]
@imsxz do you not intentionally trigger gibtonite? I often do. Drops fuckloads of sand.

**Pull request merged**
