### PR TITLE
MODsuit Self-injector module

### PR DESCRIPTION
**Pull request by Vincent983**
## About The Pull Request

Adds a self-injector module in the medical modsuit node to modsuits, you fill it up with reagents before installation, and when you activate it, it injects all of it's contents into you.
Nuclear operatives are also able to buy these for 1 TC.

## Why It's Good For The Game

If you have a MODsuit AI, this will allow them to do more than just move your body around and open doors, plus if the syndicate AI card PR is merged, it will allow the modsuit AI to actually do things.
## Changelog
:cl:
add: Deforrest Medical Corporation presents their new MODsuit self-injector. It functions similarly to the BCI reagent injector, but triggered within your modsuit.
add: Nuclear operatives are able to buy a self-injector module for 1 TC.
/:cl:

### CODE REVIEW

**Comment by Vincent983** [comment]
oh yeah also uhhh, testing, I put 50u of ephedrine in it on a private server, injected it in varying quantities and it worked, then mixed in water with the ephedrine and it injected equal amounts of each reagent

**Comment by YakumoChen** [comment]
#36021

Gonna be honest, I don't think we can be trusted with this kind of power again...

**Comment by Vincent983** [comment]
it's probably faster to just get a pill of whatever gamer mix implanted than wait for medical modsuit research and then beg robo for the module

**Comment by zxaber** [comment]
I look forward to prisoners being given a modsuit with a deathchem injector and an AI ready to administer it.

**Comment by Vincent983** [comment]
correction: 5 injectors filled with clf3 and gunpowder @zxaber

**Comment by Jackal-boop** [comment]
we already have a MODsuit injector module though

**Comment by Vincent983** [comment]
@Jackal-boop that just works as a deployable piercing syringe, modsuit AI's can't use it

**Comment by YakumoChen** [comment]
Have you considered just changing the injector?

**Comment by Jackal-boop** [comment]
yeah. you should probably just add more function to the existing injector instead of making a new one

**Comment by Vincent983** [comment]
I don't know if there's a way to switch a module between being active and being usable, as the normal injector module is active

**Comment by Vincent983** [comment]
ok I changed it at mothblocks request, but MERGE CONFLICT, i'll redo the PR with the changes mothblocks requested

**Pull request closed without merging**
