### PR TITLE
Desouls the legion

### PR DESCRIPTION
**Pull request by Sheits**
## About The Pull Request

I really hope I didnt fuck the pr up lol
also big thanks to SgtHunk and JohnWillard for code help

https://user-images.githubusercontent.com/81964183/149705898-75180bc4-681f-42cd-ba5c-97e5947df9eb.mp4

Legiontest
Middle
Legion
Legionright
Legion1

Core1
Legion1
Legion2
Legion3
Legion4

## Why It's Good For The Game

I feel like the current "skull mitosis" in the legion fight is just a lazy way to avoid adding more sprites. With the introduction of more subtypes with different sprites, this opens the possibility of adding more attacks or phases to the boss.

## Changelog

:cl:
imageadd: Resprites the mega legion and all legion related mobs
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
sick

**Comment by remove32** [comment]
fantastic bit of cosmic/body horror

**Comment by TemporalOroboros** [comment]
Very nice sprites.
Did you manage to get the big legion as well? I know it's _somewhere_ in the larger icon files. I'll see if I can track I'd down.

**Comment by Sheits** [comment]
> Very nice sprites. Did you manage to get the big legion as well? I know it's _somewhere_ in the larger icon files. I'll see if I can track it down.
> 
> EDIT: Found it https://github.com/tgstation/tgstation/blob/master/icons/mob/lavaland/64x64megafauna.dmi legion It's not actually used so if you want to I think you could just remove it. Otherwise it might need sprites, lest it remain soulful.

idk im not respriting it so the soul can stay lol

**Comment by Shadowflame909** [comment]
> > Very nice sprites. Did you manage to get the big legion as well? I know it's _somewhere_ in the larger icon files. I'll see if I can track it down.
> > EDIT: Found it https://github.com/tgstation/tgstation/blob/master/icons/mob/lavaland/64x64megafauna.dmi legion It's not actually used so if you want to I think you could just remove it. Otherwise it might need sprites, lest it remain soulful.

Dwarf Legions could use it!

Also these sprites make me feel sick. Now I know what the miners feel like! 10/10 PR. Im immersed

**Comment by D4C-420** [comment]
The skull trophy that drops from legion and their cores should also probably be changed to match these sick new sprites.

**Comment by SmArtKar** [comment]
Core effect alert also needs to be changed, it's located in icons/hud/screen_alert.dmi

**Comment by Sheits** [comment]
> Core effect alert also needs to be changed, it's located in icons/hud/screen_alert.dmi

iirc its the same icon for another status effect when you take lots of damage so the icon shouldnt be the same as the core imo, but thx for bringing it up ill look into it

**Comment by SmArtKar** [comment]
> > Core effect alert also needs to be changed, it's located in icons/hud/screen_alert.dmi
> 
> iirc its the same icon for another status effect when you take lots of damage so the icon shouldnt be the same as the core imo, but thx for bringing it up ill look into it

I think it would be nicer if you changed it(the alert) to the core instead of the skull sprite

**Comment by SgtHunk** [comment]
Soulless

**Comment by Sheits** [comment]
> I think it would be nicer if you changed it(the alert) to the core instead of the skull sprite

reasoning behind doing so was because the same sprite is used for determination which happens when youre close to death or somethin idk

**Review by Fikou — CHANGES_REQUESTED** [review]
it seems you fucked up the legionnaire's icons

**Comment by IndieanaJones** [comment]
While I am relatively fond of how legionnaire looks right now, if you're completely changing legions into these more "cartoony" style it would be best if legionnaire was changed to fit alongside the others.

**Comment by Sheits** [comment]
> it seems you fucked up the legionnaire's icons

good catch lmao

**Comment by Coastfront** [comment]
and maybe oneday we'll be closer to making the legion more than a glorified gank fight

**Comment by theta006** [comment]
nice it looks like terrarias crimson

**Review by Twaticus — APPROVED** [review]

**Comment by SweetBlueSylveon** [comment]
> Very nice sprites. Did you manage to get the big legion as well? I know it's _somewhere_ in the larger icon files. I'll see if I can track it down.
> 
> EDIT: Found it https://github.com/tgstation/tgstation/blob/master/icons/mob/lavaland/64x64megafauna.dmi legion It's not actually used so if you want to I think you could just remove it. Otherwise it might need sprites, lest it remain soulful.

Every single legion mob is in use currently. Except the legion boss fight. Otherwise you can find the legate oooover here:
https://github.com/shiptest-ss13/Shiptest/pull/765

**Pull request merged**
