### PR TITLE
Adds low drop chance kinetic crusher trophies for base mining mobs

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Goliaths, Watchers, and Legions have a small chance of dropping a kinetic crusher trophy item when killed with a kinetic crusher. Like the boss trophy items, these give various effects.
tweak: Kinetic crushers recharge very slightly slower.
/:cl:

The goliath trophy gives 2 more mark damage per every 10 missing health you have.
The watcher trophy puts hostile mob ranged attacks on cooldown for 0.8 seconds; if they're already on cooldown, it increases their cooldown by 0.8 seconds.
The legion trophy decreases recharge speed by 3 deciseconds. This is 2 deciseconds faster than the current time, since I'm slightly increasing the recharge speed; 14 deciseconds to 15, dropped to 12 with the legion trophy.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
@Repukan @Kromgar @KorPhaeron

**Comment by Repukan** [comment]
Nah

**Comment by Repukan** [comment]
Make them random drops from megafauna so you don't get repeats.

**Comment by ChangelingRain** [comment]
You can't actually use repeats besides like, giving them to another miner, tho

**Comment by Repukan** [comment]
Even a better reason to include these among megafauna drops then.

**Comment by ChangelingRain** [comment]
Do you mean as a normal drop or as a crusher drop? Because all megafauna but legion and the swarmer beacon have a unique crusher drop already, and I'd rather not have these show up in the normal pool, because that sucks.

**Comment by Repukan** [comment]
Crusher drop.

It defeats the whole purpose of having a gimmick weapon that can be upgraded by just killing normal mobs. I know you're trying to make it viable but seriously, only those that want the extra challenge will use it. No need to make it fill the wrong niche and then have to nerf it to shit.

**Comment by ChangelingRain** [comment]
These aren't really intended to be anything other than incredibly paltry bonuses, as opposed to the boss drops, which are.
Plus these have like a 10% chance of dropping, and I can drop both that and their effect power if they're still too much.

**Comment by Repukan** [comment]
10% is not a low drop chance lmao.

Make it 1

**Comment by ChangelingRain** [comment]
I think 4% is probably low enough, since 1% would make it what I'd consider far too rare.

**Comment by Repukan** [comment]
It's supposed to be a self imposed challenge. It'd kinda lose that if it can reliably get upgrades.

**Comment by ChangelingRain** [comment]
This is not exactly a reliable method of getting upgrades. Actually, I should probably make tendril-spawned mobs usually not have the drop instead of lowering it so much overall, since I suspect that's your concern.

**Comment by Repukan** [comment]
I mean it makes it so much better if it's that rare, you know?

Makes it feel better if it drops.  "Oh shit I got a rare drop"

**Comment by ChangelingRain** [comment]
Actually, increased it to 5%.
I want it to be common enough that a miner who really wants one can get it if they're pretty dedicated to trying to get the item or end up being lucky.
5% is still pretty dang low since you don't tend to kill a whole lot of mobs when mining. A good amount, sure, but not usually as many as you'll need, on average, to get these.

**Comment by Repukan** [comment]
Make it a 10% chance that decreases by .50% every 5 minutes.

**Comment by octareenroon91** [comment]
Self imposed challenges can be grindy instead of glass-cannony

**Comment by Repukan** [comment]
Pls respond

**Comment by ChangelingRain** [comment]
I mean that's basically a higher chance than it is currently for, like, a pretty big chunk of the time an average miner using it will actually be alive?
Do you want this to be rare or not?

**Comment by Repukan** [comment]
Make it start at 5 and drop from there then.

Reasoning being that later in the game they can more easily kill/weaken monsters

I was just wondering if it's possible codewise but you're the genius in that area not me

**Comment by ChangelingRain** [comment]
also it's possible but it'd suck to do and I think keeping it at a static chance is better anyway

**Comment by Repukan** [comment]
5 seems good then.

Although I still think 1 is the magic ticket.

**Comment by ChangelingRain** [comment]
Relevant question; how many creatures of each type do you kill per round with the KA? With the crusher?

**Comment by KorPhaeron** [comment]
There are stats for that

**Comment by Repukan** [comment]
It depends on the tendrils I find I guess? But around 14 Goliaths and legion and half for watchers, never really counted so this is a so so average

**Comment by ChangelingRain** [comment]
Kor please there are only stats for total kills, which are useless for me.

Okay so, 14 means you'll have gotten the trophy about 70% of the time, and 7 means you'll have gotten the trophy 35% of the time. Not accounting for RNG, but that's about how often you'll have gotten it.

**Comment by KorPhaeron** [comment]
@ChangelingRain 

Can do per round and divide by 3 for a rough count per miner though

**Pull request merged**
