### PR TITLE
Redesigns Boxstation's white ship.

### PR DESCRIPTION
**Pull request by WJohn**
Redesigned the boxstation white ship, like I did delta. Because sharing meta and box's ship is a bit lazy, and I'm getting real sore of seeing those god damned white/blue/yellow/red shuttle floors. 

This one's a hospital ship, with a full blown cryo/sleeper bay, recovery rooms, first aid storage and more. It doesn't have any weaponry on it, but it does have some blast doors for "quarantine" purposes.

**This ship is supposed to have simple animal zombies on it, but I'm currently waiting on antur to add them. They may have to be added in a future PR if this gets merged first.**

I also barely shifted around the medals because they were not aligned with eachother and it was bothering me while I was putting them in a locker.

:cl: WJohnston
add: Return of the boxstation white ship, with a complete makeover! Box and meta no longer share the same ship.
/:cl:

### CODE REVIEW

**Comment by yoyobatty** [comment]
This looks very good and seems to follow a proper shuttle design. Feeling excited to know that this could be in game soon.

**Comment by MrDoomBringer** [comment]
can he be stopped?

**Comment by XDTM** [comment]
Just wondering, do we still need to have one specific whiteship per map? IMO it would probably be nicer to have them as a random selection regardless of map if there aren't any constraints

**Comment by Mickyan** [comment]
the tail airlocks should be facing outwards so they can be used for docking

**Comment by Mark9013100** [comment]
The SW engine is missing a heater.

**Comment by Bawhoppen** [comment]
I would be very sad to see the guitar ship go. That thing is a relic.

**Pull request merged**
