### PR TITLE
5 layers H/E Pipes

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
image

## Why It's Good For The Game
More layers, more fun

## Changelog
:cl:
add: H/E pipes and devices have 5 layers now
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Mirino97** [comment]
HARD PIPESSS

**Comment by CRITAWAKETS** [comment]
>improving the codebase

this does improve the codebase you dumb bot

**Comment by optimumtact** [comment]
earn some GBP

**Comment by Ghilker** [comment]
image

**Comment by NotRanged** [comment]
Why DNM?

**Comment by MrPerson** [comment]
They're awfully dark. You should consider using a different sprite or coloring technique.

**Comment by nightred** [comment]
If more then 3 layers of pipes are HE it should cause movement to be blocked/slowed massively. that is a lot of pipe in one tile.

**Comment by Ghilker** [comment]
Closing this since I'm working on smart pipes

**Pull request closed without merging**
