### PR TITLE
Evil crab resprite!

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This PR resprites the evil crab in preparation for my evil crab rework.

## Why It's Good For The Game

The evil crab now has walking animation and a new fresh look.

evil_crab_animated96

## Changelog
:cl:
imageadd: The evil crab has a new look.
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
bro upload pics to the PR

**Comment by optimumtact** [comment]
@AlinaStarkova it's right there in the OP

**Comment by AlinaStarkova** [comment]
> 
> 
> @AlinaStarkova it's right there in the OP

it wasnt when i commented, he edited it at the exact same time i commented

**Comment by IndieanaJones** [comment]
Make it walk sideways.

**Comment by Rohesie** [comment]
Remove the old sprite if unused.

**Comment by Farquaar** [comment]
Looks great!

**Comment by Rohesie** [comment]
What;s `evilcrab-2` and what it is for? Seems unused.

**Comment by Krysonism** [comment]
> 
> 
> What;s `evilcrab-2` and what it is for? Seems unused.

That is the movement state. 

It is called evilcrab(M) in the editor.

**Comment by Twaticus** [comment]
shouldnt evilcrab and evilcrab-2(with directionals) icons be switched then? unless im misunderstanding

**Comment by Krysonism** [comment]
> 
> 
> shouldnt evilcrab and evilcrab-2(with directionals) icons be switched then? unless im misunderstanding

I just forgot to add directionals to the stationary state. After that this should be good to go.

**Comment by Krysonism** [comment]
image

Proof that it is a movement state and not a gosh darn duplicate.

**Review by Twaticus — APPROVED** [review]

**Comment by Rohesie** [comment]
You can unset it from draft when it's ready for review again.

**Pull request merged**
