### PR TITLE
Adds an issue template

### PR DESCRIPTION
**Pull request by duncathan**
Just as a thought. This isn't set in stone or anything. 
I think I've done this correctly...

### CODE REVIEW

**Comment by duncathan** [comment]
@tgstation/commit-access feedback would be great.

**Comment by KorPhaeron** [comment]
Seems straight forward enough

**Comment by MrPerson** [comment]
Might want to mention how to get the revision hash

**Comment by AnturK** [comment]
This is mostly personal preference but 
### headers :
seem an overkill just 
**bold :**
makes it easier to read.

**Comment by MrStonedOne** [comment]
The issue we had with templates before is that people would put the answers on the same line as the question, making it harder to read.

**Comment by WJohn** [comment]
Most people didn't even use the template in the past, and as long as your issue report isn't misleading, wrong, or empty, I don't think it's really necessary.

**Comment by Shadowlight213** [comment]
In game interface for bug reports that the server then makes into an issue report when?

**Comment by optimumtact** [comment]
What anturk said

**Comment by Iamgoofball** [comment]
_**SUPPOSEDLY**_ github is supposed to be making it so we have literal issue fields that we can define that can then be compiled into the actual issue report, but that hasn't happened yet.

**Comment by optimumtact** [comment]
This is literally what this PR is about goof you beam

**Comment by Iamgoofball** [comment]
no you nerd, like separate text boxes entirely, not preset lines

**Pull request merged**
