### PR TITLE
makes /turf/Enter() faster, and also makes CollidedWith async

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
image

This is the "NewNewEnter" one. ~~While testing this, I've had trouble getting good numbers from the real time tab in the profiler. There seems to be a lot of variance, sometimes my new procs are below the old one as they should, sometimes the NewEnter proc has double the real time cost of the others for reasons unknown, there's barely any change in it at all.~~

^ Disregard all this, it was fucking windoors sleeping

Small(er) beans, maybe, but this does get its share of cycles on higher-pop rounds.

Things I did:
1. Same as last time, did some popularity contest on the various return return paths and based on that:
2. Moved the "incoming" turf check before incoming border objects, as hitting solid turfs is far far far more likelier than hitting windoors or windows which seem to be the only border objects that matter.
3. Removed the (!mover) check as i could not get it to fire even once, there's probably not much cost to it but why keep dead code around?
4. Combined the loop that checks for border objects and creates a list of nonpassable objects on the "incoming" turf with the next one that goes over the list and picks the one on the topmost layer

Bonus: Also made CollidedWith async so that windoor sleeps etc don't mess up real time profiling of movement procs

### CODE REVIEW

**Comment by MrStonedOne** [comment]
We will likely need to find what is sleeping in this call chain and remove that.

Sleeps in movement procs need to stop as they are likely creating unneeded delays in processing of stuff, and they muddy up the waters on profiling because only some of their cost is recorded in a profile.

**Comment by vuonojenmustaturska** [comment]
This does change a hypothetical scenario where a windoor is installed on a solid turf, before you would bump the window, now you bump the turf. Given the extreme unlikeliness of this happening and mattering, I personally think the performance gains are worth it.

Oh yeah, more importantly this PR also contains a typofix (tompost -> topmost).

**Comment by MrStonedOne** [comment]
Calls:

`obstacle.CheckExit()`

`mover.Collide()`

`obstacle.CanPass()`

**Comment by vuonojenmustaturska** [comment]
This is probably not the cause of my problems, but here's a 35% chance to sleep 60 seconds in /area/Entered: 
https://github.com/tgstation/tgstation/blob/4178c209f139ad9d78eda609d539f2b24af94565/code/game/area/areas.dm#L453

**Comment by vuonojenmustaturska** [comment]
seems to be windoor collidedwith, want me to throw the waitfor = false thing into this PR? it seems to work in testing

**Comment by vuonojenmustaturska** [comment]
^ This prevents the sleeps in windoors' CollidedWith from breaking the real time profiles of movement procs

**Comment by optimumtact** [comment]
uh did you make sure everything that calls CollideWith is expecting to be called async? You can't just run around turning procs from non async to async without at least a basic review of what the subprocs are doing

**Comment by MrStonedOne** [comment]
Only Collide calls CollideWith, and Collide is called from movement, and movement should not be synchronous.

I suggested the change because shit sleeping in movement procs creates more issues then it solves, and because of how many layers to movement procs exists, and because of how many things call movement procs, it's next to impossible to figure out how dependant anything is on the code flow.

And with set waitfor = 0, it only converts to async if there is a sleep, other wise code flow remains unchanged.

**Comment by AnturK** [comment]
Blanket fix is fine, but finding the cause first would be better.

**Comment by vuonojenmustaturska** [comment]
This has been testmerged on Sybil and after asking about it, no-one claims to have noticed any movement-related weirdness.

**Pull request merged**
