### PR TITLE
Adds player engagement to do_afters

### PR DESCRIPTION
**Pull request by MrDoomBringer**
image
## About The Pull Request
This PR adds support for Focus, a system for do_afters that rewards accuracy, reaction time, and just paying attention with _slightly_ sped up action progress. 

It creates an object only visible to the owner of the do_after. Whenever the object gets clicked, it increases the progress of the bar by a certain amount, then moves to a random pixel_x and pixel_y

To start, I've added this system to mining rocks, constructing/deconstructing normal wall plating, and medical packs. These were were just the most frequent and monotonous tasks that came to mind at the time. 

## Why It's Good For The Game
Standing around and doing nothing while you're healing or mining through a wall can get really boring. A small change like this adds a lot to the enjoyability of some monotonous actions without making them flat-out faster or stronger.

Obviously, this comes with balance implications. I'm super open to hearing any discussion or suggestions about this. 

## Changelog
:cl:
add: Players can now focus on certain time-consuming actions to speed up their progress a little!
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
Some additional examples
[pickaxes](https://i.imgur.com/AkQWmhv.gif)
[sutures](https://i.imgur.com/nOHXH1g.gif)

**Comment by wesoda25** [comment]
We're fortnite now boys

**Review by ghost — CHANGES_REQUESTED** [review]
1. The vars have weird names that dont really explain what they do and you havnt updated the comments above the procs.
2. The amounts of progress it adds are too much IMHO, It should be engagement, not a way to avoid the balance of do_afters. Especially because people will 100% make PRs to apply this to other things
3. The fact that these icons appear outside of the sprite you're clicking on mean you can misclick and accidentaly perform the wrong action. You can say git gud but it'll inevitably cause problems.

**Comment by CRITAWAKETS** [comment]
this looks like murder on your hands

**Comment by MrDoomBringer** [comment]
@Qustinnus good points good points
1. oop
2. Yup, right now if you click really well you can get about 1.5x the normal do_after speed. What would you say would be a good number to bring this down to?
3. Honestly I see what you mean, but I think it encourages actual careful aim instead of mashing the mouse as hard as possible to get sweet sweet bonus time, which would kinda defeat the point. Happy accident? If you're really set on it though I can look into making the sprite only appear in a certain area.

@CRITAWAKETS Doing this is totally optional, thankfully

**Comment by Jared-Fogle** [comment]
:-1: I don't like this, since it's something we now have to consider for every do_after we create. Consider this scenario:

I want to add a new feature, and I want a small time gate of 5 seconds. Simple enough, I do `do_after(5 SECONDS)`. Uh oh, now people who do the minigame complete it in 3 seconds. That's not what I want, and it can be detrimental to what I'm trying to create. Err, alright, I'll make it `do_after(7 SECONDS)`. That way people who do the minigame do it in 5 seconds, my *actual* desired time. Now, people who *don't* do the minigame complete it in 7 seconds. It's a losing situation.

This is optional to do_after's, yes, but assuredly down the line we're going to get people making PRs to put this on more things (and there's a good chance the original designer isn't there or doesn't notice), or we're going to get players to ask people to put this in their own do_after's, and blagh. It's a headache.

It may seem like a silly thing to get upset about, but whoever made welding down walls wanted it to take 4 seconds, not an unknown amount of time *up to* 4 seconds.

To maintainers: I'm not blocking this, but I don't like it.

**Comment by CRITAWAKETS** [comment]
wait this affects construction, in its entirety, when you are going to do it for possibly hours, constantly and on multiple turfs

oh god no

**Comment by MrDoomBringer** [comment]
@Jared-Fogle and I discussed this a bit in discord, putting a copy here for everyone else

Those are some very valid points. My immediate reaction to that would be to 
- Implement a simple click cooldown,
- Potentially punish spam clicking by adding a minor time reduction when a player clicks too quickly or misses (would be more difficult to figure out how to implement this in a sane way, but I think I could do it reasonably well)
- Add either a local or global cap to how much bonus time you can get, probably limiting the total number of sparkles you can get (per your suggestion)

**Comment by MrDoomBringer** [comment]
@Armhulen also mentioned a good idea about adding stonewall criteria for when it's reasonable to add these in the future, as some people had concerns about this getting added to everything and causing headache because players want to do everything fast

**Comment by Iamgoofball** [comment]
@MrDoomBringer Ignore anyone talking about "potential lag issues" until they present you with benchmarked stats.

Ignore anyone complaining about balance on every do_after, just make it something you have to toggle on so the people who do like do_after(5) don't have skill checks.

This is a good PR and should be merged. Ignore any boomers who don't like change.

**Comment by Iamgoofball** [comment]
@Jared-Fogle 
>Simple enough, I do do_after(5 SECONDS). Uh oh, now people who do the minigame complete it in 3 seconds. That's not what I want, and it can be detrimental to what I'm trying to create. Err, alright, I'll make it do_after(7 SECONDS). That way people who do the minigame do it in 5 seconds, my actual desired time. Now, people who don't do the minigame complete it in 7 seconds. 

Or, you just, don't enable the minigame on your do_after. It's that easy.

**Comment by Mickyan** [comment]
I would personally put this in on fixed intervals I.E. you get one thing to click every second rather than as soon as you click the previous

Few reasons:
1. Level playing field - lag is drastically less of a factor if there's a grace period to still achieve the fastest result
2. Far less reasons for people to resort to botting if a human can reliably get the best time assuming they don't screw up
3. Consistent times - in regards to one of Jared's points, you will be able to tell exactly the min/max duration of a do_after I.E. if click decreases duration by 1 and do_after is 10 seconds = max is 10 seconds, min is 5 seconds

**Comment by Iamgoofball** [comment]
>(and there's a good chance the original designer isn't there or doesn't notice)
If the original designer isn't there, it doesn't matter.

**Comment by Qustinnus** [comment]
I like swanni's feedback. I think there's still the risk of people adding the focus shit to literaly every do after though. And yes maintainers can just stop those from going in but they will be missed because do afters have tons of args, and some maints wont know its a thing.  (and if you tell me maints should all know about this you're basically pulling a "Oh you're a maintainer? Name every code file")

I think increasing player engagement is good though, I'm just not sure if adding more RSI inducing interactions is the right way though.

**Comment by Iamgoofball** [comment]
Yeah, changing the minigame could be good, but to what? We've tried dbd style skill checks, they don't work in byond.

**Comment by Qustinnus** [comment]
no we didnt

**Comment by MrDoomBringer** [comment]
> wait this affects construction, in its entirety, when you are going to do it for possibly hours, constantly and on multiple turfs

no it only affects adding or taking away plating from default walls.....

**Comment by MrDoomBringer** [comment]
> @MrDoomBringer Ignore anyone talking about...

I really appreciate the support for the PR, but I won't be ignoring maintainers who are voicing their feedback (performance issues or otherwise), even if it is non-blocking. In general, I like to try and address concerns or at least see other people's perspective where possible. 

This feature is in no sense perfect yet, and I've heard a number of suggestions that I'm interested in pursuing at this time.

**Comment by optimumtact** [comment]
` A small change like this adds a lot to the enjoyability of some monotonous actions without making them flat-out faster or stronger.`

yeah cause adding clickspam to grind definitely makes me like RPG's more

**Comment by MrDoomBringer** [comment]
After speaking with @Jared-Fogle and a few others, I've made two changes:
1. Spamclicking was an issue. I went ahead and added an invisible hitbox around the sparkles that, when clicked, slow down the do_after's progress. This means that players will actually have to aim a little - while still leaving enough space that it doesn't become pixel-hunting. In testing this seemed to work quite well, both with an autoclicker script and manual button-mashing.
image

2. The system now uses a consistent number of "sparkles" per second. I've set it at 1.5, which in testing seems like a very good middle ground between too easy and too annoying. This has also made balancing simple, with do_afters now being able to control the exact amount of bonus time available to players.

**Comment by MrDoomBringer** [comment]
And to copy some of the discussion I had into this thread:
In terms of punishing players for not taking part in this system, I get that it's a shift in perspective, but realistically it makes sense to gain something small for interacting more with the game, and be slightly penalized for playing the game on autopilot. However...

Obviously this doesn't mean that this should get added to everything, because of course in the end this is essentially just point-and-clicking. It would get old if players had to continually interact with this - it's not crazy fun or exciting, but it's not meant to be either. This is a little mentally-stimulating addition for a system that, in some cases, involves idling around and doing nothing for minutes at a time.

**Comment by Dorsisdwarf** [comment]
This is a neat system but I really don't see how a pixelhunting clickspam challenge is supposed to make things *less* monotonous.

**Comment by RaveRadbury** [comment]
I'd much rather see keypresses over mouse clicks. I can feel my hands and eyes straining just thinking about this.

**Comment by MrDoomBringer** [comment]
@Dorsisdwarf there are things in this game that are pixel-hunty and there are things that are click-spammy, this is neither

**Comment by Iamgoofball** [comment]
We should do DBD skill checks instead.

**Comment by Cyprex** [comment]
Not sure how enjoyable this would even be in the long run. I'm against this but if you want to go through with it I suggest the following: Optional, if turned on do_afters default to 1.1x times as long(not sure about this number), down to 0.95x if you hit everything. This feature really shouldn't be impactful so as not to put players that do not want to engage with it at a disadvantage(RSI concerns etc.).

**Comment by optimumtact** [comment]
it's a bad idea :-1: from me

**Comment by MrDoomBringer** [comment]
@optimumtact appreciate the feedback - just to clarify, when you say bad idea do you mean:
- do_after time being affected by skill checks is a bad idea
- this particular implementation (clickspamming, pixel-hunting, still kinda boring) is a bad idea
- all of the above or something else

**Comment by cacogen** [comment]
Hate this semi-interactive quick time event like non-gameplay replacement for actually doing the thing in games

**Comment by MrDoomBringer** [comment]
@cacogen this is not like any of those things luckily

**Comment by ExcessiveUseOfCobblestone** [comment]
Big 👎 from me, any system that otherwise speeds up progress should assume the hard-coded time is the **best** case scenario instead of the worst one. If it wasnt a time-sensitive task it wouldn't take X seconds to perform (if that time is shit we should review that directly instead of adding an underlying system to address it).

Every do_after needing to be accounted for "what if someone speeds it up with epic clicks" and the balance implications seems very unenjoyable.

**Comment by MrDoomBringer** [comment]
@ExcessiveUseOfCobblestone sure that's fair, I can change that pretty easily - any other concerns?

**Comment by cacogen** [comment]
@MrDoomBringer It's an abstract minigame meant to represent the skill required to perform a task. Not unlike quick time events. And like quick time events the minigame sucks and only makes dummies feel like they're actually doing the thing.

**Comment by cacogen** [comment]
Alternatively: this is like CAPTCHA for mining rocks.

**Comment by optimumtact** [comment]
this will never work, I don't want to see it again.

**Comment by MrDoomBringer** [comment]
the sad truth

**Pull request closed without merging**
