### PR TITLE
Adds spam prevention to clients

### PR DESCRIPTION
**Pull request by optimumtact**
The current limit is 10 messages in 5 seconds, with 20 messages in 5
seconds muting you

### CODE REVIEW

**Comment by Ty-the-Smonk** [comment]
I like this better than 1 message every 5 seconds

**Comment by qwertyquerty** [comment]
Make the properties configurable.

**Comment by optimumtact** [comment]
This path is too hot to be configurable outside of changing the defines

**Comment by optimumtact** [comment]
well that's probably not 100% true, but im lazy

**Comment by imsxz** [comment]
Chip tha ripper
S.L.A.B.

Now baby I'm Tha Rippeeerrrrrr your baby daddy's worst nightmare
Catch me by the Clair I'll be right there
Niggas copy everything we say
Louie frames, eyes lower than my GPA
Ridin and swervin, kush I'm blown
Doors wide, my trunk bump like Eddy Road
I don't cake hoes I never tip tha stripper
I'm rich bitch, but you can call me cheap tha ripper
Shell toes? Yes
P.R.P.S
Theres a man riding a horse on top of my chest
Polo fresh, I am z' man
I be slam dunkin and Tanqueray shots wit LeBron
I told niggas to keep it Carmelo ok?
Rolled past Dave told him hello and hey
Me and Cash on somthin' old on 23's ho
Back windows says MAMA MEL BICHO
Skateboarders grind, I grind too
Thats why you can catch me in DC shoes
I quit the team, but believe im ballin'
Want a verse? Put up a stack or quit callin'
30's on my Chevorlete call me supa dupa
Garage like Roots I got more whips than Kunta
Riviera sitting on the Bulls best hooper
Y'all still riding 20's, y'all some oompa loompas
Doors swang on niggas that got bad behavior
My four 15's woke up the neighbors
Interior croc-a-dile alli-ga-tor
I drive a Chevrolet movie theater

**Comment by optimumtact** [comment]
Interior croc-a-dile alli-ga-tor

**Comment by optimumtact** [comment]
@tgstation/commit-access

**Comment by PKPenguin321** [comment]
HOLY MOLY YOU SAID THE N WORD 🚨🚨🚨 GITHUB POLICE ARE COMING GET DOWN 🚔 👮 🚓

**Comment by imsxz** [comment]
i have deleted my post as it has come to my attention that there were words that should not be typed on this lovely christian website, i just copypasted it from someone else my apologies my fellow christians

**Comment by Ziiro** [comment]
can't believe imsxz is going to join goof in the github shadow realm smdh

**Comment by Detective-Google** [comment]
After seeing the guy abusing a bot earlier today and an admin having to panic bunker to keep them off I 100% support this

Question, does this affect emotes like *flip?

**Comment by Dawson1917** [comment]
Do emotes count? *deathgasp spam as borg or alien is ICONIC and I would like to still be able to queue up 20 suicides with the nuke disk and trigger them all at once

**Comment by optimumtact** [comment]
I think this check happens before emotes

**Comment by optimumtact** [comment]
just checked, emotes happen first (otherwise a lot of people would have gotten banned for repetitive spam anyway)

**Comment by gardenBanter** [comment]
/tg/ powerless against a single person, this is funny

**Comment by Dorsisdwarf** [comment]
This doesnt apply to forced speech like stands, right?

**Comment by SkeletalElite** [comment]
> This doesnt apply to forced speech like stands, right?

Also north star gloves could be a problem in terms of forced speech.

**Comment by Shadowflame909** [comment]
Chip Da Rippa can go eat a spicy pepper.

**Comment by coolsurf6** [comment]
I would absolutely agree. They have not only been targeting TG, but they have also targeted Fulpstation and possibly other stations, including those with less than 10 players. Without this change, most servers are being forced to panic bunker or have an admin on with a decent enough reaction time and computer to mute someone before they get overwhelmed (certainly not me on a laptop :P )

**Comment by coolsurf6** [comment]
Could you also add a way to give an ADMIN LOG: User has sent more than X (or just 10) messages in 10 (or changable variable time) seconds. As well as a second one that is more serious, ADMIN LOG: User has been automatically muted for chat spam (perhaps list how many they spammed or even list some, one, or all the messages they sent)

**Comment by optimumtact** [comment]
I can, but this currently doesn't work and I don't know when I'll next find any motivation to contribute to tg right now

**Comment by optimumtact** [comment]
@coolsurf6 turns out it already does, the automute function will leave a log entry and an admin announce.
(Ignore the numbers debug output)

**Comment by coolsurf6** [comment]
Oh shit lad, that seems to work well. One issue I think may circumvent this is getting either 9 or 19 but instead have very long blocks of text. As far as I've seen most of the boys used one sentences but having massive blocks of test spamming right under the threshold may be an issue.

I assume this will be tweaked and fixed and is more of an admin issue if it isn't crashing the server. I would ask if it could scale depending on how much is said (characters/letters) but that may be difficult and take too much to adjust to be right.

**Comment by optimumtact** [comment]
Yeah we'll definitely be looking at improvements as well (perhaps something based on a combination of charactercount * lines per 5 seconds

**Pull request merged**
