### PR TITLE
Removes fetish content

### PR DESCRIPTION
**Pull request by jughu**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Improvedname
del: Removes fetish content from abandoned crates
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by jughu** [comment]
Ok dad

**Comment by jughu** [comment]
I HAVE MADE A FATAL MISTAKE WHEN KEVIN DEGREES ON A FETISH PR INVOLVING CAT EARS IN A RANDOM LOOT CRATE IT MUST MEAN BAD THINGS

**Comment by Daturix** [comment]
So you make it easier for you to meme these crates? go away

**Comment by FantasticFwoosh** [comment]
Only a admin would even understand how to decode those things normally to open their sweet side stash of ad-meme cat ear sardines.

**Comment by Anonmare** [comment]
Abandoned crates kinda suck in terms of loot tbh

**Comment by banthebantz** [comment]
reopen this

**Pull request closed without merging**
