### PR TITLE
Fixes Jumpboots breaking

### LINKED ISSUE #34432: jumpboots broken
Issue reported from Round ID: 81883 (/tg/Station Terry [EU] [100% LAG FREE])

jump boots stop working after a few uses

### PR DESCRIPTION
**Pull request by Caiggas**
## About The Pull Request

This PR changes some of the code of jumpboots to fix some faulty logic that resulted in jump boots sometimes becoming nonfunctional. 

Basically, if the throw_at function completed in one tick, it would call the callback (in this case, hop_end) BEFORE the if statement that called throw_at evaluated to true. This would cause the "jumping" var to be set to TRUE after hop_end ran. This caused the "if (jumping)" check to always interrupt the attempt to jump. 
_The throw_at function completes in one tick if you hit an object one or zero tiles away._

## Why It's Good For The Game

Fixes  [#34432](https://github.com/tgstation/tgstation/issues/34432)

_I also confirmed that it does not reintroduce a previous bug in which jump boots would break if you used them while in a sleeper._

## Changelog
:cl:
fix: Fixed jump-boots breaking after colliding with things at close range.
/:cl:

### CODE REVIEW

**Comment by Daxxed** [comment]
Never noticed the issue and I use these daily, maybe stop using them as a grief stun or stop slapping yourself into a wall... They are made to explore space or cross chasms.
Nonetheless thanks alot for the fix <3

**Comment by Caiggas** [comment]
> Never noticed the issue and I use these daily, maybe stop using them as a grief stun or stop slapping yourself into a wall... They are made to explore space or cross chasms.
> Nonetheless thanks alot for the fix <3

I mean, how they are used isn't my concern. All I was doing is fixing a bug.

Your welcome though! Have fun!

**Comment by SpaceManiac** [comment]
Seems like the `var/jumping` could be removed as well?

**Comment by Caiggas** [comment]
> Seems like the `var/jumping` could be removed as well?

Thanks, good catch. I fixed it. I have never edited a pull request with more changes, but I _think_ I got it right. Someone lemme know if I messed up, thanks.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
