### PR TITLE
Legion mob uses forceMove()

### PR DESCRIPTION
**Pull request by coiax**
This might fix some of the issues we've been having with people dying
inside legions and then being nullspaced. Maybe.

### CODE REVIEW

**Comment by GunHog** [comment]
Dark Lord Jordie will be enraged by your abuse of the changelog!

**Comment by coiax** [comment]
I don't know if it fixes the bug or not.

**Comment by Core0verload** [comment]
I think not. Issue was caused by death being called twice, that's why mob was dropped in nullspace.

**Comment by ChangelingRain** [comment]
Forcemove would fix it, because forceMove(null) fails.

**Pull request merged**
