### PR TITLE
light replacer tweaks

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: 
tweak: light replacer is now WEIGHT_CLASS_SMALL, can be fit in a toolbelt and printed from engilathe
/:cl:

the light replacer had the same weight class as the box of replacement lights making it pretty much not any better

when an explosion happens it usually means the light bulbs also broke and i dont see why engineers shouldnt be able to replace a light bulb
cobby pre approved this pr will show proof if you email me

### CODE REVIEW

**Comment by optimumtact** [comment]
I don't believe cobby approved this, if you can't provide proof I will close this pr

**Comment by YakumoChen** [comment]
How many engineers does it take to screw in a lightbulb?
-One to design the bulb
-One to ensure it's within fault tolerance
-One to review the safety codes
-One to hire a janitor to replace the lightbulb

**Comment by Tlaltecuhtli** [comment]
http://take.ms/m3NOY

**Comment by YakumoChen** [comment]
doesn't this already fit in the janibelt?

**Comment by ExcessiveUseOfCobblestone** [comment]
lol

**Comment by ExcessiveUseOfCobblestone** [comment]
idk if I approved of the other changes but whatever.

**Pull request merged**
