### PR TITLE
New Cleanbot and Bucket sprites (No GAGS)

### PR DESCRIPTION
**Pull request by MTandi**
qpQKWKPyiS

## About The Pull Request

Adds a new cleanbot and bucket sprites, removes colored buckets.

## Why It's Good For The Game

The sprites were outdated, colored buckets and cleanbots made of those were ugly.

## Changelog

:cl:
image: New cleanbot sprites
image: New bucket sprites
del: All buckets and cleanbots are back to being blue
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Drafting for now because the recent refactor if cleanbots broke my usage of flick animation.

**Comment by excalisword** [comment]
Do you have sprites for when a clean bot is given a knife or one of the other cutting implements it can be given?

**Comment by MTandi** [comment]
> Do you have sprites for when a clean bot is given a knife or one of the other cutting implements it can be given?

image

**Comment by CRITAWAKETS** [comment]
I feel like the buckets are a little too dark. Aside from that, they look great.

**Review by Wallemations — CHANGES_REQUESTED** [review]
Definitely brighten the plastic bucket.

Mind showing what the buckets look like next to a large beaker too? I'd say that would be a good thing to compare them to. Not saying to change it in that front yet, but just seeing them next to each other can help us see how they'll fit into the game since at the moment I'm not 100% sold this is matching

Don't get me wrong they're beautiful sprites, just want to make sure they fit in

**Comment by MTandi** [comment]
image

**Review by Wallemations — APPROVED** [review]
Better

**Pull request merged**
