### PR TITLE
SEVERAL mask sprite fixes

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
many masks (mostly clown masks) are now the same height all around, woo

## Why It's Good For The Game
many more masks are now acceptable

## Changelog
:cl:
fix: many masks, mostly clown masks, are now the same height all around
/:cl:

### CODE REVIEW

**Comment by SpinnerMaster** [comment]
You get what you fucking deserve.

**Comment by cacogen** [comment]
that was part of the madness

**Comment by Fikou** [comment]
jomker

**Comment by Paxilmaniac** [comment]
sociemty moment

**Comment by trollbreeder** [comment]
Why do we have so many clown masks?

**Comment by HomocidlePancakes** [comment]
You can change how clown mask looks by using it in hamd.

**Pull request merged**
