### PR TITLE
Nukie Update 3: Uplink Spring Cleaning (I hit delete and call myself a developer)

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Removes from the nuclear operative uplink:
Riot Darts and Toy Guns (from Nuclear Ops, not Clown Ops)
Camera Bug
Combat Gloves Plus (they were removed from the leader already)
FRAME disc
Guerrilla Gloves
Radioactive Microlaser
Blood-Red Magboots (the standalone ones)
Power Beacon
Bioterror everything (including the bundle)
Stechkin APS machine pistol
AI Detector

## Why It's Good For The Game

These items are either really bad, entirely useless, done better by other items or truly just broken.

We know there are a lot of bundles with a few of these items still in. We're not dealing with the bundles entirely just yet. Bioterror bundle just happened to have quite literally only items I was already removing, so I feel pretty confident getting rid of it here.

<details>
<summary>Overwritten explanations inside</summary>

**Donksoft weaponry:** It's really weird that nukies can get these. They're meant to be the lethal variety of the two operative groups we have, and I think Pacifist is no longer able to be kept as an operative. Let's keep the toy guns to the clowns. Just kill people.

**Camera Bug:** Actually pretty nonfunctional right now, and generally not especially useful to ops, who possess an advanced camera aboard their ship. They also cannot really go around bugging cameras very easily, nor do they get very much use from it. They simply have better tools and options.

**FRAME Disc:** A method of acquiring a normal traitor uplink as a nuclear operative. This doesn't do much good for them, as most of the truly spicy items are at least 30 minutes deep and they can't use the FRAME uplink to do objectives. Still, better to resolve this oversight while we're here, they certainly can't do much with this item.

**Radioactive Microlaser:** Just use CQC.

**Power Beacon:** I question why this is even available to anyone who isn't a station engineer or atmospheric technician traitor. But ops definitely have even less business causing a singularity unless they're using a saboteur borg, and even then, they're potentially screwing themselves over massively by doing so as a singularity is entirely indiscriminate. Better to just not let newer players confuse this for the actually useful item, the power sink.

**The Bioterror Line:** These are extremely outdated items, using fairly neutered chems by this point. The dart pistol and chemical sprayer in a previous PR are both bundled with their respective labs, so operatives wanting to make use of chemical mischief can now just kinda do that without much unnecessary expense. Additionally, while they can still totally make good use of chemical kits thanks to this, they don't get a whole lot out of the bioterror prepackaged items to begin with. Their mixes are kind of dreadful, since they're usually fairly small dosages, so they get processed out of the body almost immediately. In the case of the bioterror grenades, someone thought mute toxin, itching powder and spore toxin in a foam reaction would do something worth a damn for ops. Ops can make their own grenade mixes, so we can just let them make their own killer concoctions using the available kit and the chem dispenser.

**AI Detector:** Ops have quite a lot of anti-AI tech right from the moment they spawn. No suit sensors, agent cards prevent tracking, and ops can just blow up AIs using explosives if they really want. Ops can also send in borgs to execute the AI. They usually move pretty damn fast through the station, so most AIs can't easily lock down the entire force, nor can they keep them locked down. They don't get much out of knowing an AI is watching them. Additionally, this items been pretty significantly reworked to the point that I think it has fairly dubious value inherently, but even before that, this wasn't a particularly useful item.

**Stechkin APS machine pistol:** I kind of wish this had a place, but we have so many automatic weapons for ops already and this one is the most superfluous. I brought it into the world, I'm taking it out. There just isn't any noticable benefits to this over the c20-r. Pyro bundle still comes with the APS if you want it.

**Guerrilla Gloves:** Fikou already got rid of the Krav gloves from Nukies with the promise we'd look at maybe reintroducing them or rethinking their presence in the arsenal, as gloves are overridden by modsuits. The same can also be said of tackler gloves to some degree, but neither of us are making promises of a return. I think as a standard, op equipment should be a little more reliable than a pure RNG stun, and they certainly have plenty of that already. 
</details>

## Changelog

:cl:
balance: Toy guns are only available to clown operatives.
del: Removes from both operative uplinks: Camera Bug, Combat Gloves Plus (already removed from leaders), Guerrilla Gloves, FRAME disc, Radioactive Microlaser, Blood-Red Magboots (the standalone ones, not the modules), Power Beacon, Bioterror everything (including the bundle), Stechkin APS machine pistol and ammo, AI Detector.
/:cl:

### CODE REVIEW

**Comment by RegJackson** [comment]
The machine pistol??? Bad??? Because of the free ammo around for stetchkins and the fact that you can reload the mags, you get practically infinite ammo for the thing, plus it's concealable. Shit homie I've seen entire stations wiped with that fucking thing. Let the kid stay. 
Also, while I won't argue with most of the points here I generally don't think restricting ops and pigeonholing them into a gameplay style so I'm going to take umbrage with the removal of the donksofts. Donksofts loaded with riot darts are robust as hell if for some godforsaken reason you wanted to do pacifist ops (and one of the few options you'd have for doing so), and I think if someone wants to do that then by god we should let them. Just my two cents.

**Comment by necromanceranne** [comment]
Just ask to be made into clown ops if you want to play pacifist ops.

> The machine pistol??? Bad??? Because of the free ammo around for stetchkins and the fact that you can reload the mags, you get practically infinite ammo for the thing, plus it's concealable. Shit homie I've seen entire stations wiped with that fucking thing. 

Me and fikou have some plans for ammo, so don't stress about the APS' good ammo availability as an upside, it might not matter soon.

As a result, the c20r really just is better than it. More damage, same concealability, same burst. There isn't much value in having two guns be near identical, just one being pistol shaped and one being...tacticool I guess.

**Comment by TymurShatillo** [comment]
Don't remove things that can be usefull for stealth nukies(like AI detector or radioactive microlaser)

**Comment by Shadowflame909** [comment]
Donk soft stuff pairs well with stealth ops or hypno flash as a combo

I'd keep it

**Comment by Striders13** [comment]
Forcing nukies to need admin for any gimmick they want to do is bad. Keep non-lethal nukie dream alive.

**Comment by Shadowflame909** [comment]
the elephant in the room is that Cqc KO seems to have broken in the rework. It requires you to grab twice. But your grab is already upgraded to an aggressive one so you can't KO.

**Comment by Spookuni** [comment]
> nobody has ever used the ai detector in the history of ss13. nuke ops already can't use sleepy pens and the microlaser is basically that. just use cqc if you want to kill someone unarmed
I have in fact made use of the AI detector as a standard traitor - it's current functionality of showing you what the AI is actively looking at is honestly quite useful, since a lot of AIs will kinda casually watch people they're interested in (for good or ill)

You are otherwise correct that the thing is basically entirely useless for nukies though, for whom stealth and pre-emptive awareness of incoming AI malice are either entirely redundant (you're nukies) or otherwise unavoidable anyway (you're nukies)

**Comment by Fikou** [comment]
> words from spookuni

yeah i more meant nukies, thats why its still available for traitors

also shadowflame why is there no issue report you bitch

**Comment by necromanceranne** [comment]
> the elephant in the room is that Cqc KO seems to have broken in the rework. It requires you to grab twice. But your grab is already upgraded to an aggressive one so you can't KO.

In the meantime while fikou looks at the bug, unless all martial arts are fucked, CQC's headkick knocks people out if they're prone.

**Comment by RegJackson** [comment]
> Just ask to be made into clown ops if you want to play pacifist ops.

Ehh... asking admins for things has always been a tossup to me. Ideally admins are on every round and are always willing to help but... it's iffy.

**Comment by necromanceranne** [comment]
I'm going to be pretty blunt. I'm not sure I actually believe the people who claim they buy the microlaser during stealth ops, because I can't tell why they would use it over anything else. I'm entirely open to being proven wrong by purchase statistics, but I think this is unlikely anything but an item taken in ignorance. 

Assuming this isn't hypotheticals people are arguing from, what goals are you achieving with the microlaser? In these situations, wouldn't it be better to just shoot people dead if there are so many people that CQC alone can't deal with the problem? You can buy suppressors, and killing people for ops is very quick too. You can even mess up comms in a number of ways to stop an alert.

Is it kidnapping people? Why not just use isolated targets and CQC? 
Is it kidnapping the captain? Why not use the overwhelming number of ops you have to just slamdunk the group of opponents you're fighting. Or just shoot anyone but your target dead? Do you need everyone alive?
Are you kidnapping everybody in a large group? To what ends? Have you actually convinced the whole team to go along with this before rather than just laying down a wall of flak?

**Comment by necromanceranne** [comment]
I should note, it's not inefficiency as the only problem with a lot of these. It's redundancy. That's the issue with about 90% of these items. If there is something any of these items can do that what the list left over can't do, and isn't basically an oversight (in the case of the FRAME), that actually means something to ops, we're all ears.

**Comment by VladinXXV** [comment]
You've neglected to mention the removal of combat gloves plus from the uplink (though I completely understand why they're going, as it's been explained twice now). You've also neglected to mention the removal of the blood-red magboots. There isn't really any explanation for this. I would assume that you assume all operatives live inside their smelly little suits and would have magboot modules. I think this is pretty restrictive. Unlikely? Maybe, but I don't think it's impossible that a team might prefer to take their suits off in favor of traditional armor. At the very least, I'd add the two of these to your changelog and such. Combat gloves plus =/= guerilla gloves, and the magboots weren't mentioned at all.

**Comment by necromanceranne** [comment]
Combat Gloves were removed in another PR, not this one. I did forget about magboots yes.

The answer is that they just get replaced by modsuits currently. Modsuits have a module for magboots and they're _blood-red_ so they're not stealthy and can't really be used as part of a disguise. They're also not particularly useful compared to actual noslips and never have been. They're even a bit outclassed by modsuit ion thrusters for zero grav movement. Entirely pointless as a standalone option, you would even be better off raiding engineering to be able to disguise yourself, since they're identical to standard magboots.

Combat Gloves Plus suffered the same fate. They just get overridden. We're gonna work out what to do with them. Pretty much, we saw no value in either currently as they are both not wearable in a disguise and we don't really give a shit to encourage ops exiting their modsuits outside of that context, because what reason do you have? Where are you getting this traditional armor? Why use that over armor mode? By all means, do what you like, but that seems like a purely personal decision and we're trying to clean up this mode for the average player who hasn't got much experience under their belt. For them, these items are traps because they don't know the pitfalls.

**Comment by VladinXXV** [comment]
I'm thinking along the lines of the Starfury ops. I remember seeing a good two or three of them sporting armor rather than MODsuits back during one of two times I actually saw them. I couldn't tell you exactly where the armor came from, but I do think the magboots offer a niche yet very real functionality. As for CG+, I was just pointing out they are in fact removed here. I don't argue in favor of them as I do magboots because you can get better results using CQC either way.

All in all, magboots was a bit of a nitpick and I don't care enough to die on this hill. The main concern was that these changes weren't mentioned, and that's been resolved. The rest is probably just personal preference. Also I forgot the magboots come in one of the bundles (medical I think it was?)

**Comment by necromanceranne** [comment]
yeah, bundles we'll get too later, we've got some bigger plans for ops as a whole which might make the bundles largely obsolete.

It's fine yo, but I figured I would explain why we removed them. I'm pretty sure there are actually Starfury crew that dont get uplinks, so they're probably the ones you see running around without suits. I suspect there might be magboots on the Starfury, and if not, I'm sure that's a reasonable addition to make.

**Comment by chemistrymain2** [comment]
Why not just make the bioterror kits not shit instead of removing em?

**Comment by necromanceranne** [comment]
They didn't have anything particularly unique, premixes date themselves over time (just like these have), and since ops can make their own chemical mixes with the lab, the people who care enough about chemicals can do the legwork themselves.

**Comment by Redrover1760** [comment]
Sounds like this was not accounting for stealth ops at all. AI detector is definitely a useful item for it. In addition, nonlethal takedowns are actually useful for nuke ops, when you can follow up with a hypnoflash to make more syndicates, so removing the toy gun is dumb.

Krav maga gloves are really good for stealth ops type stuff, although they are outshined by cqc, they still have some purpose.

I dont see why removing sketchkin APS is needed. Its not used much cause its in a weird spot between free pistols and guns, but at the same time maybe its a useful sidearm for a desworder or something who wants to invest into something they can hide. But whatever I have never seen it in use yeah.

Removing the radioactive microlaser is bad. Cqc costs a lot, while the microlaser is cheap. Its different.

**Comment by anclandor** [comment]
- Krav maga gloves are still very useful, even if the bug with modsuits currently hampers them.  A couple weeks ago I was able to use them as a reinforcement to secure the disk 
- AI detector could have a use with stealth ops
- Radioactive microlaser is cheaper than CQC, and it doesn't make punching noises, its an interesting choice for stealth ops that is better for stealthy takedowns but worse for actually combat.  
- Camera bug 
- Pistol, interesting weapon, gives nuke ops a side grade
- Donksoft weaponry - gandi ops rise up.  One day we will have a deathless nukie run, and it will be glorious (and your microlaser and donk removal is getting in the way of it)

What is the point of removing these things.  They all have their uses, and its not like there 8 or si items are causing such incomprehensible bloat that no nukies can find anything in their uplink.

**Comment by necromanceranne** [comment]
There is no bug with the gloves. It's just not compatible and there is no intent to make gloves work through modsuits. The best concession is making a krav maga module, which is fine and all but not really for this PR.

You do bring up a point with CQC sounds, but I'm not sure those even go through walls currently. The solution to that is either double checking if they do, or alternatively just making them generic kick sounds (the sound rips are kinda not good anyway).

When people talk about 'stealth ops', what exactly _is_ your definition of stealth ops? Because it seems there is a bit of uncertainty as to what even the end goal of that style even is. 

To me, stealth is speed and leaving most of the station unaware of your presence before its too late. How you do that is open ended, but definitionally, you can interpret the blitz style as a stealth tactic.

Is stealth a long con kind of operation for a goal beyond simply setting the nuke? I can understand wanting to be geared for that, for sure. And I can even agree with the perspective of using microlaser to help. Thats a sound enough argument for me to reconsider its place. Though if you want an instant sleeping tool for hypnoflash, soporific ammo for sniper rifles is an instant knockout and you can use it even point blank, and comes in the sniper bundle. I might also talk to Fikou about soporific ammo for the other guns, like a 10mm bullet that does only stamina damage but puts people to sleep at a certain stamina value. That might help those looking to make use of the hypnoflash and actually worth the value for ops. Moreso, it might even enable the 'Ghandi Ops', because I kinda love civ jokes.

Donksoft (unless something is bugged) does not help in of itself for hypnoflash stuff, and fikou already mentioned the states that you should require for hypnoflash. I just think we can do better.

Alternatively, is stealth 'blitz but you're dressed as an assistant while using the microlaser and drivebying the captain'? In that case, didn't we remove sleepy pen years ago for exactly this reason?

**Comment by anclandor** [comment]
>There is no bug with the gloves. It's just not compatible and there is no intent to make gloves work through modsuits. The best concession is making a krav maga module, which is fine and all but not really for this PR.
> 
I didn't realize that the gloves getting overridden by having modsuit gloves on was intentional.  
> You do bring up a point with CQC sounds, but I'm not sure those even go through walls currently. The solution to that is either double checking if they do, or alternatively just making them generic kick sounds (the sound rips are kinda not good anyway).
>
CQC sounds probably arn't that large of an issue in actuality, but they make me feel worried.   
> When people talk about 'stealth ops', what exactly _is_ your definition of stealth ops? Because it seems there is a bit of uncertainty as to what even the end goal of that style even is.
To me, stealth is speed and leaving most of the station unaware of your presence before its too late. How you do that is open ended, but definitionally, you can interpret the blitz style as a stealth tactic.
> 
I think of stealth as plainclothes ops who grab jumpsuits, get stealth modsuit mods, and then walk up to the diskholder before pulling out their weapons of choice.  Of course it never actually works that way and the best stealth option is to have one op go plainclothes with a gasmask well the others blitz or war.  
> Is stealth a long con kind of operation for a goal beyond simply setting the nuke? I can understand wanting to be geared for that, for sure. And I can even agree with the perspective of using microlaser to help. Thats a sound enough argument for me to reconsider its place. Though if you want an instant sleeping tool for hypnoflash, soporific ammo for sniper rifles is an instant knockout and you can use it even point blank, and comes in the sniper bundle. I might also talk to Fikou about soporific ammo for the other guns, like a 10mm bullet that does only stamina damage but puts people to sleep at a certain stamina value. That might help those looking to make use of the hypnoflash and actually worth the value for ops. Moreso, it might even enable the 'Ghandi Ops', because I kinda love civ jokes.
> 
Soporific sniper is highly expensive, and as far as I am aware, once the sniper is removed from the case it cannot be put back in, making it hard for a truly stealthy infiltration.  Further soporific options would be cool and also fill the niche that donksoft is in, but better.  
> Alternatively, is stealth 'blitz but you're dressed as an assistant while using the microlaser and drivebying the captain'? In that case, didn't we remove sleepy pen years ago for exactly this reason?
Good point. At the same time, microlazer doesn't contain mute toxin or slow the target before it activates.  An op could also dress as an assistant, pull a rocket launcher out of a holster module in a cham modsuit, and driveby the cap, or use 2 click kill confirmed with cqc on the cap, all having somewhat similar outcomes.  Why, an op can go into maint near the cap and come out with a mauler.  The possibilities for cheese are endless when you have a device that can teleport weapons of mass destruction into your hands instantly!

**Comment by ShizCalev** [comment]
normally i'd close this with just this picture.
image

personally i'm not a fan of removing playstyle options for players, especially when it comes to antagonist roles. 

anclandor's description of plainclothes stealth ops is a tactic I have successfully utilized before several times (albeit it's been a long time since I was last a nukie, I DO love hidden traitor/long con playstyles myself.)

**Comment by necromanceranne** [comment]
> normally i'd close this with just this picture. image
> 
> personally i'm not a fan of removing playstyle options for players, especially when it comes to antagonist roles.
> 
> anclandor's description of plainclothes stealth ops is a tactic I have successfully utilized before several times (albeit it's been a long time since I was last a nukie, I DO love hidden traitor/long con playstyles myself.)

We don't want to remove tactics, but these are strictly inferior tools or they're just straight redundant. And, technically, none of this actually prevents you from utilizing plain clothes tactics at all, so I don't know where anyone is getting that from, even you. The microlaser might hurt one specific gimmick, but not stealth as a whole.

I do think there is maybe something to consider with some nonlethal/sleeping weaponry to be implemented that isn't as terrible as donksoft, but I'll do that in a separate PR once I put it past fikou.

We need to trim the fact somewhere. The op uplink is bloated and outdated, and if we want to see the role to be modernized, some things need to get changed. I'd wait on fikou to chime in, he's on holiday right now.

**Comment by necromanceranne** [comment]
If there is any concession, the items being free in some capacity is maybe fairer than forcing them to pay. They seemingly just don't gel well with current nukie purchasing habits.

**Review by JohnFulpWillard — COMMENTED** [review]
I disagree with the 'just use CQC' argument for radioactive micrcolaser. Nukies have the option to not declare war if they want, and I think it should be a viable option if they choose so.

Removing all abilities to go stealthy by saying "just use this other item instead lol" is pretty boring. I'd like a better explanation on why they shouldn't be allowed to have it (which is probably very easy for you), or to just keep it.

**Comment by necromanceranne** [comment]
Microlasers main usage is putting people to sleep after a certain amount seconds for a set amount of seconds, both determined by changing the frequency and strength of the wave. This is pretty much the only use, but it always has a delay, and some savvy players will know what is happening if they see someone with a medscanner out in the halls.

The reason you should just use CQC is because Restrain also just puts people to sleep, stuns to boot, and lasts for an immense amount of time. A plain clothes op has no outward indicators that they have it. Retaliation against someone with CQC is also immensely hard, and it is actually fairly good against a 2v1 due to defense mode, so it helps when things go poorly.

Statistically the microlaser isn't purchased at all. Meanwhile, ops almost always buy CQC. The problem isn't that microlaser is bad. Its that CQC does it all.

**Pull request merged**
