### PR TITLE
Cogscarabs can no longer be worn as hats

### LINKED ISSUE #20460: Cogscarabs worn as hats are invisible
@ChangelingRain

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Cogscarabs can no longer be worn as hats. This means you can instead attack them if on harm intent.
/:cl:

Cogscarabs have no hat sprite there's no reason to wear them as hats aaaaa
Fixes #20460

### CODE REVIEW

**Comment by KorPhaeron** [comment]
not canon

**Comment by ChangelingRain** [comment]
you are allowed to complain once there's a cogscarab hat sprite

**Comment by FantasticFwoosh** [comment]
Mmm, i want my pillar man Egyptian themed wammu hat already. Better wait for the sprite.

**Comment by ike709** [comment]
no just annoy spriters until one of them gives you a sprite

**Comment by RemieRichards** [comment]
almost all drone hat sprites are just the Drone's south sprite, with it's legs hunched up.
yes up close they look kinda crappy, but ingame (32x32 displayed at 64x64) they look good enough, about the equivalent of most inhands-quality.

**Comment by KorPhaeron** [comment]
Everyone hates it sorry

**Pull request closed without merging**
