### PR TITLE
Adds a carrot satchel for easter

### PR DESCRIPTION
**Pull request by improvedname**
Adds a carrot satchel for easter! you can get them by cracking open easter eggs!
Carrotbag
Bag directionals

## Changelog
:cl: Improvedname
add: Adds Carrot satchel to easter prizes
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
Merge conflict already?!

**Comment by improvedname** [comment]
NNoonnnooo my easter pr! 😭

**Comment by Tlaltecuhtli** [comment]
can you remove the carrot icon in the bunny suit then?

**Comment by improvedname** [comment]
I rather not remove the icon from the suit but then again your not forced to wear it all together you can wear it with the suit or without the suit

**Comment by HomocidlePancakes** [comment]
>I rather not remove the icon from the suit but then again your not forced to wear it all together you can wear it with the suit or without the suit

Yeah, that’s cool and all, but they are clearly a part of the same set. Items in the same set should compliment each other instead of cucking.

**Comment by improvedname** [comment]
I'll make an toggle for it once i figure how to resolve this conflict

**Comment by TheVekter** [comment]
🥕🐡

**Pull request closed without merging**
