### PR TITLE
Capitalize all Is

### PR DESCRIPTION
**Pull request by nicbn**
All words `I` are capitalized automatically.

### CODE REVIEW

**Comment by tortellinitony** [comment]
i like it

**Comment by nicbn** [comment]
That's what I call capital-Is-m

**Comment by tortellinitony** [comment]
Lots of salty thumbs downs, but no actual arguments against this, because there isn't one :(

**Comment by BeeSting12** [comment]
what if i am spelling a word such as idiot i say "i-d-i-o-t" and the i's capitalize to IdIot. it would look stupid and its all your fault

**Comment by tortellinitony** [comment]
> what if i am spelling a word such as idiot i say "i-d-i-o-t" and the i's capitalize to IdIot. it would look stupid and its all your fault

This checks for spaces not hyphens,  and if you're spelling out letters like that, then they should all be capitalized to be grammatically correct.

**Comment by optimumtact** [comment]
Yeah we're gonna leave this up to the players

**Comment by nicbn** [comment]
If you want I can make it check for spaces only.

**Pull request closed without merging**
