### PR TITLE
Reduces the required amount of players for his grace ascension to 15

### PR DESCRIPTION
**Pull request by Cyberboss**
I like to watch the world burn

:cl:
balance: His grace now only requires 15 souls to ascend
/:cl:

Roast me reddit

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
It should scale with pop

**Comment by Kagus** [comment]
Terry ascension with one kill, after having successfully murdered 35% of the entire stationpop.

**Comment by ExcessiveUseOfCobblestone** [comment]
The real joke is choosing chaplain when cobby isn't online

**Comment by granpawalton** [comment]
it could be made to have a lower limit of 5-10 and implement the pop scale should it be higher than that

**Pull request closed without merging**
