### PR TITLE
Traitorbro fixes

### LINKED ISSUE #30850: need antag hud for traitorbros

### PR DESCRIPTION
**Pull request by pubby**
Adds an antag hud icon fixes #30850

Goes back to using `[bro.key] (ckey)` because key_name was returning `*Unknown*` on the mobless mind. `.key` is how the other gamemodes do it so its probably ok.

### CODE REVIEW

**Comment by lordpidey** [comment]
While you're here, could you add a generate_report() to it?  Seeing as it's a subtype of traitor, right now it's just generating the normal traitor text.

**Comment by pubby** [comment]
Yeah sure

**Comment by Armhulen** [comment]
Remember don't give the traitors the hud, give admins the hud

**Comment by pubby** [comment]
Yep.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
