### PR TITLE
splits gun.dmi up into multiple files

### PR DESCRIPTION
**Pull request by ghost**
icons/guns/energy.dmi
icons/guns/projectile.dmi
icons/guns/magic.dmi

### CODE REVIEW

**Comment by TZK13** [comment]
Shouldn't the pulse M1911 and stun revolver be in energy.dmi? Also wouldn't it make more sense for the syringe guns to be in projectile.dmi?

**Comment by paprka** [comment]
some of them are likely mixed up since i did this by hand so yeah thanks for pointing them out

**Comment by paprka** [comment]
Fixed syringe guns, pulse m1911, and stun revolvers.

**Comment by paprka** [comment]
Please merge

**Pull request merged**
