### PR TITLE
Adds three useful PDA programs to Cyborg's default PDA loadout

### PR DESCRIPTION
**Pull request by GregariousJB**
## About The Pull Request

overview
For a long time borgs have only had two PDA programs: `filemanager` and `robotact`, but there are other simple programs with useful information for gameplay. This PR remedies this by including three other programs to borgs by default: `borg_monitor`, `atmosscan`, and `crew_manifest`. In the interest of transparency, I've included possible negatives in the form of disclaimers below.

`borg_monitor`: 
monitor 
This is the "SiliConnect" program in-game, and allows showing a brief overview to cyborg players who else is connected as a cyborg and what their model is, which allows for informed decisions on which module to choose for themselves, among other minor useful data.

**_Disclaimer: I'm pretty sure the "Send message" button on this program is unusable for borgs due to how it's coded [here](https://github.com/tgstation/tgstation/blob/ab222330ef3b05f512d9b0a87c3292377ce91271/code/modules/modular_computers/file_system/programs/borg_monitor.dm#L116), but I'm unable to test it with another player. Looks like it requires an ID, which borgs don't have, so I'm assuming this is a non-issue._**

`atmosscan`: 
atmos 
The AtmoZsphere program, which shows local oxygen/nitrogen data to help make informed decisions on protecting humans.

`crew_manifest`: 
crew 
The Plexagon Crew List - A simple window that shows an updated list of current crew members and their jobs.

**_Disclaimer: The "print" button on this program allows borgs to spam printed crew manifests on the ground if they choose to do so, which may have the potential to be overused, however they've also had the ability to spam-print photos using the Robotact program and I don't know of any issues this has caused (correct me if I'm mistaken)._**
## Why It's Good For The Game / Potential additional changes

Currently cyborg gameplay can become a walking simulator if they need simple information that a crew manifest computer would have, or an air alarm (which might've just been blown up, disabled, or out of power), or if they just got borgified at a Roboticist and would like to know which other cyborgs are currently in play but don't want to pick  a model already being used. All humans have this data and more on their handheld PDAs. Cyborgs should at least have these three as a bare minimum.

There are other useful programs: `records/medical`, `records/security`, `custodial_locator`, and `supermatter_monitor` (NT CIMS), which could go into Mediborgs, Peacekeepers, Janiborgs, and Engiborgs respectively. I've tested these and am unable to change these records as a borg, only view them, so this is purely informational data that could be useful for various RP reasons. It could be fun for a cyborg buddy to patrol with a Sec officer (or Paramedic) and give them up-to-date info on a crew member's status just by having the human ask about them. Or, Engiborgs are given the ability to keep an eye on the Supermatter using NT CIMS and can inform engineers out in the field of its status. 

Just having this general information available only to humans feels a bit silly when cyborgs are meant to be connected to the station in a way that allows them to interact with doors from a distance but not something simpler like viewing a crew manifest. This still keeps the power in human's hands since this data cannot be manipulated by borgs, only humans (ID required).
## Changelog
:cl:
add: Added three programs to cyborg PDAs: SiliConnect, AtmoZphere, and Crew Manifest
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
You can login multiple times in your localhost by running it on Dream Daemon, logging in as your main account and then again as a guest

**Comment by GuillaumePrata** [comment]
Borgs already have a way to check Atmos/Power/Fire alarms with their built in alarm checker, but that thing breaks to often to be a useful source of info for borgs.

Would be nice to just give them Canary while you are at it, it feels to be a lot more consistent than their built in version and parity between borg/crew equipment makes it a lot easier for new players to understand and to find/fix future bugs in the future.

**Comment by GregariousJB** [comment]
> Borgs already have a way to check Atmos/Power/Fire alarms with their built in alarm checker, but that thing breaks to often to be a useful source of info for borgs.
> 
> Would be nice to just give them Canary while you are at it, it feels to be a lot more consistent than their built in version and parity between borg/crew equipment makes it a lot easier for new players to understand and to find/fix future bugs in the future.

I am also in favor of Canary. While testing as a borg I had both windows open - Canary and the alarm checker UI button - and the alarm checker frequently never showed any problems while Canary accurately updated itself in real-time whenever something got better or worse. Canary is objectively superior. 

I figured Canary is a touchy subject because "we already have Canary at home", but I'm glad you pointed it out. Suppose there's two options - either try to fix the borg's alarm checker, or just replace it with Canary so there's only one alarm checker system thingy. The latter makes more sense to me. Could maybe have the alarm UI button simply open a Canary window instead.

**Comment by GuillaumePrata** [comment]
There is a third option which is to turn the alarm checker into "silicanary" which is a better version with the extra alarms the alarm checker has like motion sensors.

**Comment by ju45he** [comment]
You can leave the other PDA programs for different modules to the heads of staff with those PDA programs disks to give to the borgs. Not like the heads of staff are going to use those disks on anyone else.

**Comment by zxaber** [comment]
I disagree with Siliconnect being auto-installed. Keeping track of other borgs is not the intended function of borgs (that would be a job for the AI, the RD, and robotics). If a need arises, borgs can download Siliconnect to any modular console, and that's more interesting narratively than if borgs could just check whenever. It's also a bit scuffed for unusable features of an app to still be visible, so even if we did want to include it, it should be a trimmed down version without the ID-related features or download log tab.

The Plexigon Crew List is more reasonable, and AtmoZphere is a good idea.

**Comment by GregariousJB** [comment]
> I disagree with Siliconnect being auto-installed. Keeping track of other borgs is not the intended function of borgs (that would be a job for the AI, the RD, and robotics). If a need arises, borgs can download Siliconnect to any modular console, and that's more interesting narratively than if borgs could just check whenever. It's also a bit scuffed for unusable features of an app to still be visible, so even if we did want to include it, it should be a trimmed down version without the ID-related features or download log tab.
> 
> The Plexigon Crew List is more reasonable, and AtmoZphere is a good idea.

I agree that it's not the intended function of cyborgs to keep track of other cyborgs, but is that because they shouldn't, or simply can't? 

I believe borgs have been unable to see other borgs on the network for so long that it's just become the norm. We figure, 'Well, the AI or RD has a function for that, so who cares?' But why not also borgs themselves? Is it really so detrimental while an AI is busy or an RD is dead for a borg to think, 'I'd like to know how Cyborg-X is doing because I had to repair them earlier', or 'I just got borg'd and the Roboticist ran off, so I'll just open up the Siliconnect app and take a look what borgs already exist to pick something that isn't already being used.' 

I personally don't see any issue with these scenarios that isn't manufactured by the same thought process as the [5 monkeys experiment](https://intersol.ca/news/organizational-culture-and-the-5-monkeys-experiment/) (not meaning that to be offensive, just attempting to approach this from a neutral perspective). If it does cause the Conjunction of the Spheres and monsters from other dimensions to pour into our reality, we can just delete one line to revert it 🙂👍

That being said, I agree that a trimmed-down version that doesn't show that "Stored log file" tab could be a reasonable compromise (perhaps make it a button in the Robotact app?), but I've never coded anything in TGUI so I'd be a poor choice for that. Overall, though, I think just adding Siliconnect to borgs by default is simpler for everyone, which is the same argument for using Canary above - no need to continue keeping a second similar window up-to-date over time as the codebase changes. When Siliconnect does update in the future, so will the borg version, and borgs can't mess with it because it requires an ID. It's just read-only data with a bit extra useless fluff.

**Comment by zxaber** [comment]
>I agree that it's not the intended function of cyborgs to keep track of other cyborgs, but is that because they shouldn't, or simply can't?

Shouldn't. You wouldn't expect the six-axis production robots in an assembly line to keep tabs on eachother. You wouldn't expect warehouse logistical robots to be running constant diagnostics checks on the rest of the fleet. Not because they're not sentient, but because it's outside of their scope. You have a maintenence team and a robotics control server to do this.

Cyborgs, if they really want to, can already check Siliconnect from any modular console. Every map has one in robotics, you can download Siliconnect to it and check. (And if you *really* want it, you could have a human use a floppy disk to install the program into your borg PDA.) It should not be a default program.

**Comment by GregariousJB** [comment]
@Ghommie 👍 Any chance you have an opinion on the other stuff mentioned - 

* The Canary app added to all borgs to supplement the alarm checker UI button
* Job-specific apps like NT CIMS for Engiborgs

These are something I could take a look at, if you approve.

**Comment by Ghommie** [comment]
Go ahead and take a look into it.

**Pull request merged**
