### PR TITLE
Fixes nuke rounds not ending when nuke was disarmed.

### PR DESCRIPTION
**Pull request by AnturK**
What it says on the tin.

### CODE REVIEW

**Comment by Iatots** [comment]
Like, after docking?

**Comment by AnturK** [comment]
Yes, if all ops are dead it should end as soon as it's disarmed (and no sideantags are present)

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
I feel like `bomb_set` being a static var is gonna open us up to some weird behavior, how hard would it be to change that?

**Comment by AnturK** [comment]
Probably not very hard, let me take a look how it's used.

**Comment by AnturK** [comment]
Turns out it's completely redundant variable. Also added a quick check so beer bombs don't count. (I guess if someone is blowing up beer bombs during that's already an achievement)

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
