### PR TITLE
Blender, food processor and gibber shaking when processing.

### PR DESCRIPTION
**Pull request by kingofkosmos**
Updated video: http://webmshare.com/play/0gbLg

Made the blender, food processor and gibber shake sideways when they're processing to indicate that something's happening. Code-wise very simple and looks cool imo, especially with the gibber.

Tell me what do you think, what other things could this kind of visual indicator be used with?

### CODE REVIEW

**Comment by hornygranny** [comment]
just to be incredibly nitpicky i think it would look better if it was a little faster

**Comment by RemieRichards** [comment]
Yeah it needs to be faster

**Comment by Dorsisdwarf** [comment]
Webm skips to the end after 4 seconds?

**Comment by RemieRichards** [comment]
@Dorsisdwarf it doesn't, that's just you.

**Comment by kingofkosmos** [comment]
I thought I made it as fast as possible by having time = 1?

**Comment by RemieRichards** [comment]
@kingofkosmos time is in tenths of seconds, so I'm sure it'll allow decimals also
0.5, maybe 0.2

**Comment by pavelheer** [comment]
It's not just him, I have the same problem.

**Comment by RemieRichards** [comment]
By "it's you" I mean it's a local issue and nothing wrong with the WebM.

**Comment by Dorsisdwarf** [comment]
This could also go on the monkey processor

**Comment by kingofkosmos** [comment]
Implemented HG's idea with RR's help, the shaking is now faster! Also implemented to the monkey recycler. I couldn't help but notice that the monkey recycler had juicer.ogg when it grinded the monkeys, so I added it to the gibber itself. Hope there wasn't any specific reason why it wasn't already there.

**Comment by RemieRichards** [comment]
Ok so, another complaint (sorry!)
it should random between +2 and -2, since going all the way right and then back to the center and /never going left/ is jarring.

**Comment by kingofkosmos** [comment]
[Video updated] (http://webmshare.com/play/0gbLg) (in desc as well)

**Comment by WJohn** [comment]
This is a very cute and neat little feature :+1: 

I approve.

**Comment by kingofkosmos** [comment]
Says "code\modules\admin\admin_verbs.dm:124:error: /proc/machine_upgrade: undefined type path" when compiling... how is this possible I have not touched that file.

**Pull request merged**
