### PR TITLE
Silences var_edited runtimes

### PR DESCRIPTION
**Pull request by Cyberboss**
Warranty void if seal is broken

### CODE REVIEW

**Comment by kevinz000** [comment]
When coding, assume the players AND admins are both trying their best to break your code :^)

**Comment by AnturK** [comment]
Should probably still show in view runtimes but not log to persistent log. So if _certain people_ mess up you can actually tell.

**Comment by RemieRichards** [comment]
It shouldn't silence it, it should HIGHLIGHT it so we can all laugh (make var_edited'd contain the person who did it's ckey so it can say world << "[e_src.var_editor] is a dummy!")

**Comment by MrStonedOne** [comment]
No, I want all runtimes logged because other wise it is a bitch to see what the fuck happened to the server when it crashes.

end of story that is the most important thing about runtime logs and if i have to take away public runtime logs to remind you of that i will.

**Pull request closed without merging**
