### PR TITLE
Lets you untie peoples shoelaces

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
This PR adds some extra hijinx opportunities to the game. By laying down next to someone and opening their equipment stripping menu, you can untie their shoelaces. Once their shoelaces are untied, you can then knot them together. Moving with untied shoelaces has a very low chance to cause you to stumble and drop what you're holding, while moving with knotted together laces makes you trip and fall over. Luckily, you can unknot and retie them by clicking them on your equipment panel!

Messing with someone's laces, like pickpocketing, produces no tell unless you fail the do_after (like if the target moves), at which point the shoe-wearer stamps on your hand and deals some damage. If you don't notice the clown (or whoever) crawling up next to you and laying still for ~10-20 seconds though, then you probably deserved to get stunted on.

Clumsy mutation makes you 33% faster (most shoes are 5 seconds to lace/unlace/knot/unknot, while boots are 9-10 seconds). Sandals and flip-flops are, obviously, exempt from this nonsense.

## Why It's Good For The Game
Pranks are fun and funny

## Changelog
:cl: Ryll/Shaps
add: You can now untie and knot up people's shoelaces! You can do so by laying down next to the person, dragging their sprite onto yours, then clicking "untie/knot shoes" next to their shoes.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
do jackboots even have shoelaces?

**Comment by Ryll-Ryll** [comment]
These ones do

**Comment by Fikou** [comment]
a lot of shoes that can be untied shouldnt even have ties, like cowboy boots, clockwork treads, jackboots, griffin, combat boots. why even have a var if it can be untied if practically everything can be untied

**Comment by Ryll-Ryll** [comment]
Because I don't fawn over fascist boots and didn't know jackboots had no laces. I'll make a second pass later today

**Comment by trollbreeder** [comment]
Imagine powergamers rushing sandals to not get bamboozled by the clown

**Comment by cacogen** [comment]
you have to play twister just to know this feature exists

**Comment by ATH1909** [comment]
Why not just make this feature only be usable on subtypes (and types) of /obj/item/clothing/shoes/laceup ?

**Comment by Ryll-Ryll** [comment]
Followers of spessmenart know that the standard sneakers are Converse all-stars

**Comment by kriskog** [comment]
merge conflict

**Comment by optimumtact** [comment]
should really have been an element

**Pull request merged**
