### PR TITLE
Microwaves now produce light!

### PR DESCRIPTION
**Pull request by ShizCalev**
my immersion

:cl: ShizCalev
tweak: Microwaves now produce light when running.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
To clarify for people who might not be able to read the commit (its a little tough to read with your one line interjections at different places), this turns the light on & off when its being used?

**Comment by Qustinnus** [comment]
On when used, off when broken or destroyed

**Comment by ExcessiveUseOfCobblestone** [comment]
fwoosh please lol just press the blue button that looks like it's expanding.

**Comment by SouDescolado** [comment]
You could add so the lamps inside can be replaced and if you put that rigged lamp it explodes

**Comment by ShizCalev** [comment]
@SouDescolado good idea, i'll add that to my to-do list.

**Pull request merged**
