### PR TITLE
MOAR BADGES FOR THE BADGE GOD.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
[forthebadge](http://forthebadge.com) [forinfinityandbyond](https://www.reddit.com/r/SS13/comments/5oplxp/what_is_the_main_problem_with_byond_as_an_engine/dclbu1a)

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
god damnit

**Review by Cyberboss — APPROVED** [review]

**Comment by nfreader** [comment]
I need a badge for all the technical debt I found in the stats DB.

**Comment by JJRcop** [comment]
MrStonedOne/tgstation#25
[forinfinityandbyond](https://www.reddit.com/r/SS13/comments/5oplxp/what_is_the_main_problem_with_byond_as_an_engine/dclbu1a)

**Comment by Cyberboss** [comment]
REEEE

**Comment by AnturK** [comment]
Stop

**Comment by optimumtact** [comment]
okay but no more after this seriously

**Pull request merged**
