### PR TITLE
Throwing with help intent no longer stuns/damages. Also applies to borg spin throws.

### PR DESCRIPTION
**Pull request by blessedmulligan**
## About The Pull Request
Grabbing and throwing someone will only paralyze/damage them (and anyone they hit) if you threw them off of help intent. Help intent throws are noted in logs.

Spinning as a cyborg will only paralyze/damage/apply knockdown when in harm intent. Previously, knockdown was always applied, and whether or not damage was applied was dependent only on whether or not the borg was emagged, for some reason.

## Why It's Good For The Game

Sometimes you need to throw someone but don't necessarily want them to eat shit. Now you can! Also, the way borg throwing works currently is really janky. What if you want to teach that greytiding lizard a lesson? What if you throw someone and they take damage, revealing the fact that you're emagged? Having it be intent based is just cleaner and more intuitive.

## Changelog
:cl:
add: Throwing someone with help intent will no longer damage or stun them.
Tweak: When a cyborg *spins someone off of them, whether or not they are damaged and stunned depends on the cyborg's intent.
/:cl:

### CODE REVIEW

**Comment by blessedmulligan** [comment]
There might be some more presentation changes to make but I can't come up with much

**Comment by Ryll-Ryll** [comment]
Why do we need to have a separate mischiefless version of chucking someone across a room, which it's an inherently mischievious thing? If you don't want people to think you're a jerk when you throw them across a room, just apologize to them or find another way to move them, coding around minor IC misunderstandings seems lame

**Comment by blessedmulligan** [comment]
> Why do we need to have a separate mischiefless version of chucking someone across a room, which it's an inherently mischievious thing? If you don't want people to think you're a jerk when you throw them across a room, just apologize to them or find another way to move them, coding around minor IC misunderstandings seems lame

that wasn't the motivation for this change. I agree that there aren't a ton of important use cases for the people-throwing-people part, so if other people think this is extraneous I'll cut it. It was mostly a bonus change on top of the change to cyborg throwing, which I think really does need tweaking.

**Comment by necromanceranne** [comment]
I like this. Means I can toss people/bodies without any risks associated with it.

**Comment by Fikou** [comment]
so now i have to grab someone twice with grab intent, then turn on throwmode and then switch to help intent and then throw them? seems like a cqc move or somehting

**Comment by ATH1909** [comment]
As a borg main, I don't like this. To strap someone to yourself, you need to be on help intent, but to knock them down (or stun them if you're emagged) would require you to switch to harm intent after buckling your target to you but before spinning (if this PR goes through). It's... finicky.

Plus, borgs already have a way to unbuckle people from themselves safely/without throwing them halfway across the room.

> so now i have to grab someone twice with grab intent, then turn on throwmode and then switch to help intent and then throw them? seems like a cqc move or somehting
They get stunned if you throw them into something while NOT on help intent (if this PR goes through, that is).

**Comment by HomocidlePancakes** [comment]
This just makes things unnecessarily confusing, both for borgs and humans. Also, I have a feeling you forgot about allowing pacifists to throw.

**Comment by blessedmulligan** [comment]
> so now i have to grab someone twice with grab intent, then turn on throwmode and then switch to help intent and then throw them? seems like a cqc move or somehting

Well, no. Unless you specifically want to take advantage of the ability to not stun someone, grabbing and throwing from grab mode is unchanged. People who normally throw people from help intent might be confused, but I don't think preserving the ability to get into fights on help intent is that critical a design imperative.

>To strap someone to yourself, you need to be on help intent, but to knock them down (or stun them if you're emagged) would require you to switch to harm intent after buckling your target to you but before spinning

I don't play borg very much, how common a technique is it to buckle someone to you and immediately spin them off? That was something I didn't have in mind making this and it would be negatively affected.

**Comment by blessedmulligan** [comment]
As this is two related but still different changes, I will be closing this PR and putting up one that's more atomic and hopefully less controversial.

**Pull request closed without merging**
