### PR TITLE
Decluttering security closets

### PR DESCRIPTION
**Pull request by pudl**
Security lockers have been heavily reorganized to be consistent and less cluttered.
HoS:
- Standard HoS armor
- Normal and alt HoS headsets
- Aggressive swat mask
- Pepper spray
- Flash
- Box of flashbangs
- Security belt
- Sechud
- Security tapeproj
- Security megaphone
- Telescopic shield
- Telescopic baton
- HoS gun

Warden:
- Standard warden armor
- Normal and alt sec headsets
- Swat mask
- Pepper spray
- Flash
- Box of flashbangs
- Security belt
- Sechud
- Secway key
- Security tapeproj

Security officer:
- Standard armor
- Normal and alt sec headsets
- Swat mask
- Pepper spray
- Flash
- Flashbang
- Security belt
- Sechud

All alt-outfits have been put in wardrobes.
HoS:
- Standard HoS beret
- Eyepatch sechud
- Gars sechud
- Trenchcoat
- Male and female parade uniforms
- Standard HoS uniform
- Alt HoS uniform

Warden:
- Standard warden hat
- Navy warden beret
- Alternate warden armor
- Standard warden jumpsuit
- Navy warden jumpsuit

Security officer:
- Security backpack
- Security satchel
- Security dufflebag
- 3 standard security jumpsuits
- 3 jackboots
- 3 security berets
- 3 security softcaps
- 3 security bandanas
- 3 sechailers

As a TL;DR, codewise/mapwise the following were added or removed:
- 2 new wardrobes
- The swat mask has been readded, with the aggressive HoS one as a child of it
- Warden and HoS now spawn with stunbatons
- HoS' telescopic baton is now in his locker
- Warden's secway key now spawns in his locker
- 1 security locker was removed from the map
- 1 security wardrobe was added to the map
- 1 dufflebag was removed from the security wardrobe
- 1 bandana was added to the security wardrobe
- 3 sechailers were changed into swat masks on Boxstation

NOTE: Because of the original nature of the PR, all alt-outfits (if they're the current default or not) are in wardrobes, while primaries are in the normal locker.

### CODE REVIEW

**Comment by JJRcop** [comment]
Pap's ghost will haunt you and yell at you from the dead

**Comment by Cheridan** [comment]
stop with the sec sprite wars already

**Comment by pudl** [comment]
@Cheridan This has absolutely no sprite changes at all, the biggest change was to make the security lockers less cluttered.
Sorry, but you put forth zero effort into reading the pr and just closed it based on "security" being in the title.

**Comment by WJohn** [comment]
Thank you. This is something that bothered me for a long time :+1:

**Comment by Lumipharon** [comment]
I'm not opposed to this, but WE USED TO HAVE THESE. But then they got removed because someone said that have two lockers was dumb.

Actually I think it was pap.

**Comment by Steelpoint** [comment]
Many things can be traced to Pap.

I like this, I always thought having you core equipment in one locker and your fluff equipment in another was a good idea, makes things less cluttered.

**Comment by pudl** [comment]
@Lumipharon No, /tg/station never had HoS/Warden wardrobes. The HoS had a wardrobe on NTStation, but that's it. Paprika didn't do anything.

**Comment by Steelpoint** [comment]
The HoS did have a wardrobe in his office on Boxstation for a very long time until Paprika removed it.

I don't think the Warden had one however, all misc clothing was simply put in his main locker.

**Comment by Ikarrus** [comment]
I added the HoS wardrobe. It was perfect to declutter the massively overstuffed HoS locker.

**Comment by freerealestate** [comment]
This problem isn't just limited to security. The other heads have it, too.

**Comment by pudl** [comment]
@freerealestate I can do it one department at a time.

**Comment by Firecage** [comment]
But, can the swat masks do the sec announcements?

**Comment by pudl** [comment]
WHO THE FUCK MADE THESE FUCKING CONFLICTS FUCK

**Comment by Ikarrus** [comment]
IT WAS ME, DIO!

**Comment by pudl** [comment]
Well, I refuse to ever fix merge conflicts because it's stupid, so.

**Comment by WJohn** [comment]
RIP cleanly organized lockers.

**Pull request closed without merging**
