### PR TITLE
Fixes a minor, widespread, project critical grammatical error.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Your spellcheckers must all be broken or something.

## Why It's Good For The Game

❕ ❔ 

## Changelog
:cl:
spellcheck: It's spelled gray goddamnit.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
nobody calls it graytide that sounds dumb shut the FUCK up

**Comment by TiviPlus** [comment]
A) https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#enforced-not-enforced
B) Ur PR sux and I hope you step on a grey lego

**Comment by Tlaltecuhtli** [comment]
grey isnt a error

**Comment by ArcaneMusic** [comment]
Hold on I'm heading out for lunch, I'm gonna be right back gang 👍

**Pull request closed without merging**
