### PR TITLE
Blobbernnauts can now see in the dark.

### LINKED ISSUE #14683: Blobbernauts cannot see in the dark

### PR DESCRIPTION
**Pull request by Buggy123**
Fixes #14683 

Lemme know if I fucked the flags up, I think    see_invisible = SEE_INVISIBLE_MINIMUM should have the desired effect but I'm not sure.

### CODE REVIEW

**Comment by GunHog** [comment]
The flags are the same as used on NVG equipment, and you set the see distance correctly, I think you are good to go. I am glad you are doing this. :+1:

**Comment by tkdrg** [comment]
Looks fine-ish to me code-wise. not reaaally sure about buffing blobbernauts during the freeze but eeeeh

**Comment by GunHog** [comment]
I wish they could smash certain things, even if you removed walls, they should be able to break weaker things at least...

**Comment by KorPhaeron** [comment]
Blobbernauts can see if they stay around nodes/the core, which provide light

**Pull request merged**
