### PR TITLE
Pixel Projectiles 4: Reloaded [DNM]

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Once more, with feeling

:cl: Paprika, Crystalwarrior, RemieRichards
experimental: Changes projectile pathing to follow a direct line, also known as pixel projectiles.
/:cl:

Mechs dont seem to be working though

runtime error: Cannot read "icon-x=31;icon-y=30;left=1;scr...".loc
proc name: preparePixelProjectile (/obj/item/projectile/proc/preparePixelProjectile)
  source file: firing.dm,61
  usr: Laura Briner (/mob/living/carbon/human)
  src: the bullet (/obj/item/projectile/bullet/weakbullet3)
  call stack:
the bullet (/obj/item/projectile/bullet/weakbullet3): preparePixelProjectile(the floor (142,129,1) (/turf/simulated/floor/plasteel), Laura Briner (/mob/living/carbon/human), "icon-x=31;icon-y=30;left=1;scr...", -1, null)
the Ultra AC 2 (/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/lmg): action(the floor (142,129,1) (/turf/simulated/floor/plasteel), "icon-x=31;icon-y=30;left=1;scr...")
the Ultra AC 2 (/obj/item/mecha_parts/mecha_equipment/weapon/ballistic/lmg): action(the floor (142,129,1) (/turf/simulated/floor/plasteel), "icon-x=31;icon-y=30;left=1;scr...")
the Mauler (/obj/mecha/combat/marauder/mauler/loaded): click action(the floor (142,129,1) (/turf/simulated/floor/plasteel), Laura Briner (/mob/living/carbon/human), "icon-x=31;icon-y=30;left=1;scr...")
Laura Briner (/mob/living/carbon/human): ClickOn(the floor (142,129,1) (/turf/simulated/floor/plasteel), "icon-x=31;icon-y=30;left=1;scr...")
the floor (142,129,1) (/turf/simulated/floor/plasteel): Click(the floor (142,129,1) (/turf/simulated/floor/plasteel), "mapwindow.map", "icon-x=31;icon-y=30;left=1;scr...")

### CODE REVIEW

**Comment by Supermichael777** [comment]
To be clear as always This is only the visual effect and not actual pixel precision. also THE ABSOLUTE MADMAN

**Comment by WJohn** [comment]
Ride never ends etc.

**Comment by Shapsy** [comment]
I want this so bad so that buckshot won't be impossible to comprehend

**Comment by WJohn** [comment]
I hope this at least fixes the whole cone width issue with buckshot/rubber shells, because right now you literally become more accurate the further away you aim.

**Comment by Bawhoppen** [comment]
shields how do they work

**Comment by Jordie0608** [comment]
Changelog

**Comment by KorPhaeron** [comment]
@Jordie0608 

Okay

**Comment by KorPhaeron** [comment]
Dream is dead

**Pull request closed without merging**
