### PR TITLE
Machinery clears it's occupant var if removed

### LINKED ISSUE #28651: Cultist summoning doesn't properly remove them form cryo
\>Place cultist in cryo, turn it on
\>Summon them with a rune
\>They remain asleep, build up cryox, and heal as if they're still in the cryotube
\>Doesn't turn off only when fully healed
Occupant var on the cryotube is still set to them, even though they were pulled out, and the sprite isn't updated

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #28651

### CODE REVIEW

**Comment by MrPerson** [comment]
What exactly would want to reference the occupant despite the "occupant" no longer being in the tube anyway? I mean why are you waiting until the end of the tick to clear occupant?

**Comment by Cyberboss** [comment]
I've seen code do something like thing

```
occupant.forceMove(get_turf(src))
occupant.fuck_my_shit_up()
occupant = null
```

Would cause runtimes if we immediately nulled the occupant

**Comment by MrPerson** [comment]
Those things should be changed to store a local ref to occupant.

Buuuut I can understand that doing that isn't worth the effort so :+1:

**Comment by AnturK** [comment]
Quick search to see if this is prevalent shown nothing similar ? Did you actually check this or this is from memory.

**Comment by Cyberboss** [comment]
Memory, I suppose if anything does runtime from it, we can fix it soon
enough

**Pull request merged**
