### PR TITLE
north star's asylum no longer spawns with prisoners

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
the asylum on the north star no longer spawns prisoners, only the permabrig does
the computer in the asylum is rotated correctly

## Why It's Good For The Game
on the paper, it seems like a cool concept, but theres a few issues here
the psychologist isnt designed to handle prisoners in the first place. this is fine on mrp but it gets kinda muddy when prisoners on lrp like beating people up
prisoners are recommended as a new player role by the wiki (very stupid), this role starting in an asylum without anything to do while being asked some stuff by a psychologist seems like itd add onto confusion
players dont know what jobs are spawning with them, there very well may not be a cmo or psychologist. if theres no one in sec you can deal with that because you have a small botany and kitchen, and can possibly escape. this aint a thing here, only thing you have is reading books and maybe pen and paper rpgs if another prisoner spawns, while being stuck in an extremely tiny space

this can work in the future i think, but it requires code support we currently dont have, so it better to cut its

## Changelog
:cl:
del: prisoner spawns from the north star asylum
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
Very sad. I'd like to keep the prisoner spawns personally, but I can't overlook the current glaring issues. I think having future code support to make this more reasonable is a goal to keep in mind.

**Comment by DrDiasyl** [comment]
> Very sad. I'd like to keep the prisoner spawns personally, but I can't overlook the current glaring issues. I think having future code support to make this more reasonable is a goal to keep in mind.

Maybe give prisoners a choice somehow? A preference where they would like to spawn

**Comment by Cheshify** [comment]
> > Very sad. I'd like to keep the prisoner spawns personally, but I can't overlook the current glaring issues. I think having future code support to make this more reasonable is a goal to keep in mind.
> 
> Maybe give prisoners a choice somehow? A preference where they would like to spawn

While I like this, it's incredibly map specific and I'm not sure if it would be accepted

**Comment by DrDiasyl** [comment]
> > > Very sad. I'd like to keep the prisoner spawns personally, but I can't overlook the current glaring issues. I think having future code support to make this more reasonable is a goal to keep in mind.
> > 
> > Maybe give prisoners a choice somehow? A preference where they would like to spawn
> 
> While I like this, it's incredibly map specific and I'm not sure if it would be accepted

If we implement the spawn selection on the other maps it will be not specific.
As, there is always several map spawns around the station and give people choice between them.

Maybe also allow every job to select a generic spawn position (assistant spawn positions), to like if they want to spawn at the closet room to get drip asap.

So the selection would be just a list of locations, the player will spawn on the spawn at the location he selected.

**Pull request merged**
