### PR TITLE
unkevinz the station maps

### LINKED ISSUE #33105: Metastation missing Engineering wardrobe (not the secure lockers)
The Metastation Engineering department is missing an '**engineering wardrobe**' (/obj/structure/closet/wardrobe/engineering_yellow) - containing jumpsuits, backpacks, hazard vests etc.

Please note that the wardrobe is **different** from the two available '**engineer's lockers**' (/obj/structure/closet/secure_closet/engineering_personal) which contain tools.

https://i.imgur.com/SLayzsC.jpg

I assume that this is an oversight, as Atmospherics has their own 'atmospherics wardrobe' available (/obj/structure/closet/wardrobe/atmospherics_yellow). 
Metastation seems to be the only map with this issue.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes shit like 
image
by making it pretty like
image

Fixes a bunch of spawn points being located ontop of lathes by relocating the lathes to more sane locations (ie not in the middle of a hallway or a room, and nestled nicely against walls.)
Fixes #33105

### CODE REVIEW

**Comment by praisenarsie** [comment]
accurate title

**Comment by Xhuis** [comment]
kev cannot code well
kev cannot sprite well
and now we see that kev cannot map well
what **can** kev do well, one must wonder... 🤔

**Comment by kevinz000** [comment]
:joy:

**Comment by The-clown-known-as-Pepe** [comment]
kevinz can erp well

**Pull request merged**
