### PR TITLE
Changes cult escape objective population scaling

### PR DESCRIPTION
**Pull request by ghost**
The required scale is now 1 cultist per 3 people. This still scales to a maximum of 15.

### CODE REVIEW

**Comment by Supermichael777** [comment]
this is a massive nerf. is this really necsicary

**Comment by Jalleo** [comment]
I would have the upper limit scale upwards a tad for really high pops. E.g. For every 5 pop after 45 you have another cultist added to the check. It makes it fairer for really high pops as a example 70-75 pop would need 20 cultists. Which is just over a quater of the pop

**Comment by Xhuis** [comment]
@Supermichael777, yes, it is necessary. I recently played a cult round with 50 players where the cult needed ___4___ acolytes to escape. That's almost nothing. A third of the players isn't nearly as bad - 90 players = 30 acolytes. It also supports lower populations; 15 players = 5 acolytes.

This is merge-ready unless anyone has any extreme gripes.

**Comment by Cheridan** [comment]
@Xhuis A 50 person station should need to convert 10 people. The thing is that the convert amount doesn't account for latejoiners, so you get that 4. Meaning that the station started with 20 people, and then 30 joined. I don't think that this is a common enough case to be balancing the objective around.

**Comment by Xhuis** [comment]
All right then.

**Pull request closed without merging**
