### PR TITLE
[Deleted]

### PR DESCRIPTION
**Pull request by Spess-Rando**

### CODE REVIEW

**Comment by coiax** [comment]
You messed up the map merge.

**Comment by kevinz000** [comment]
No, no, no.
This means if there's no captain or HoP the crew is fucked.
Come on Slig...

**Comment by Sligneris** [comment]
Actually, this means you gotta wait for captain or HoP to arrive rather than ransack captain's office within the round's first 5 minutes.

**Comment by MMMiracles** [comment]
And if they don't?

**Comment by Haevacht** [comment]
Is Slig the next goof? This shitpost suggests so, more at 11.

**Comment by Sligneris** [comment]
Then you don't get access.

Much like if captain doesn't arrive, you don't get to name the station, or if a chef doesn't arrive, you don't get to use whetstones, or if a bartender doesn't arrive you don't get to have anyone throwing beakers without spilling contents, or if a mime doesn't arrive, you don't get to make invisible walls...

**Comment by jughu** [comment]
you dont need a chaplain to survive just steal his null rod

**Comment by coiax** [comment]
@Sligneris wait, what can the bartender do?

**Comment by Cyberboss** [comment]
Freeze

**Comment by Sligneris** [comment]
Removals aren't covered under the freeze.

**Comment by lzimann** [comment]
Give a reason on why you think this will improve the game.

**Comment by Sligneris** [comment]
Tiders will no regularly longer ransack captain's office 5 minutes into the shift and then give out all access to all other assistants who then walk everyone and steal things, becoming an uncontainable problem.

**Comment by GunHog** [comment]
This. This right here is why the freeze should cover **ALL** balance changes, including removals.

Addressing the PR itself now, how exactly is a head of staff supposed to gain command as acting captain without the spare? The heads usually need not break in because they ask a silicon if available. There does need to be a way for someone to take over if there is no Captain/HoP, especially when the Chain of Command dictates that a head is next in line after the HoP and Captain.

**Comment by Sligneris** [comment]
It's not a serious PR.

One serious suggestion that I can present is to put captain's spare ID inside captain's locker, where it can be either smashed open with a fireaxe (easily available at the Bridge) or opened by a borg.

This would help mitigate the greytide problem, now that the ID would be no longer on a table waiting for whoever picks it up first.

**Comment by lzimann** [comment]
"It's not a serious pr", so why did you open it? Anyway, this is not liked, by me included, if you wanted discussion, open a thread in the forums.

**Comment by GunHog** [comment]
>One genuine suggestion that I can present is to put captain's spare ID inside captain's locker, where it can be either smashed open with a fireaxe (readily available at the Bridge) or opened by a cyborg.

I would support this, however. This might simply mean that greyscum will steal the whole locker to smash it open later, potentially compounding the issue.

**Comment by Cyberboss** [comment]
Borg's can't open lockers

**Comment by Sligneris** [comment]
They can. They are able to alt-click like anyone else with access

**Comment by PKPenguin321** [comment]
Lol this pr
Please stop killing our server

**Comment by Sligneris** [comment]
> meme PR kills a server somehow

ok then

**Comment by PKPenguin321** [comment]
>Making sweeping balance PRs without the foresight to see that it might not be good and trying to justify it with salty buzzwords like greytide all during a feature freeze

Thanks quality player, please take my headmin spot you clearly are the most wise

**Pull request closed without merging**
