### PR TITLE
Shuttles are no longer more powerful than gods and the singularity

### LINKED ISSUE #18763: Docking shuttles defeat lord singulo
If a singularity is in the shadow of a docking shuttle, it's deleted.

This is so not canon

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #18763

please stop killing literal gods with bluespace shuttle attacks

### CODE REVIEW

**Comment by lzimann** [comment]
NO

**Comment by KorPhaeron** [comment]
Have you never read The Call of Cthulu? Running an eldtritch god over with a ship is the preferred method of combating them

**Comment by Man-Shroom-** [comment]
c a n o n

**Comment by lollerderby** [comment]
s h i t  c h a n g e
h
i
t

c
h
a
n
g
e

**Comment by optimumtact** [comment]
Not canon

**Comment by PKPenguin321** [comment]
good now revert https://github.com/tgstation/tgstation/pull/7099

**Pull request closed without merging**
