### PR TITLE
Adds var to disable Tick checking in the MC for subsystems.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Mainly for debug purposes to see how tick checking affects atmos and stuff.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
you shouldn't add it to the subsystems, add it to the MC_TICK_CHECK define.

**Comment by MrStonedOne** [comment]
That being said, I know the cause the of the bug, and how to fix it.

**Comment by Shadowlight213** [comment]
@MrStonedOne Remie said that too, and I tried to do that, but it wouldn't compile, saying it was missing a parenthesis when everything was closed.

**Comment by MrStonedOne** [comment]
add it to subsystem's pause() and make it return 0

**Comment by Shadowlight213** [comment]
What?

**Comment by MrStonedOne** [comment]
go to the pause() proc in subsystem.dm and add if(!McTickCheck) return 0

**Comment by Shadowlight213** [comment]
Oh. ok

**Pull request merged**
