### PR TITLE
Peacekeeper Borgs [Needs sprites] [NOT-A-MEME]

### PR DESCRIPTION
**Pull request by silicons**
Peacekeeper borgs, as detailed in https://tgstation13.org/phpBB/viewtopic.php?f=9&t=6247
It has the following modules: Flash, "Harm Alarm" that confuses in normal use, cookie dispenser (That does not have to be on the borg, as it can work outside of a borg", a energy bola launcher that has its shots slow anyone hit but wear off after a few seconds, can inject chems to confuse but not outright stun people. It can also make fragile energy barriers (Goes down in 1 hit, might be too fragile, but we'll see)
Because I'm a TERRIBLE spriter, I need sprites for the borg itself, the cookie dispenser which is right now a RCD sprite, and some other stuff like MAYBE the energy bola projectile..?
When emagged:
Energy barriers electrocute on touch
Chem injector gets knockout/knockdown drugs
"Harm Alarm" becomes a stunning changeling shriek.. .only it also stuns changelings!
And it gets an engiborg stun arm

Thoughts comments concerns? 
:cl:
rscadd: Peacekeeper borgs: Security borgs but without any stuns or restraints!
rscadd: Cookie Synthesizer: Self recharging RCD that prints out cookies!
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
why are my commits so fucked up

**Comment by nullbear** [comment]
needs meme tag

**Comment by Niknakflak** [comment]
ya fucked it

**Comment by kevinz000** [comment]
FUCK

**Comment by RemieRichards** [comment]
> I need sprites for the borg itself

no you don't!!

**Pull request closed without merging**
