### PR TITLE
Fixes smuggler's satchels not being visible with t-ray

### LINKED ISSUE #42296: Smugglers satchels are not visible from t-ray scanners
Present on f48e3a9dea3be4f48ca657f4a906e0a46a28f448

1) Have hidden smuggler's satchel
2) Look at t-ray scans
3) You can't see it.

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
fix: Smuggler's satchels can now be found with t-ray scanners, as
intended.
balance: Smuggler's satchels now cost 1 TC, down from 2 TC.
/:cl:

Fixes #42296.

I used a trait because currently this is the only object that I'm aware
of that uses partial invisibility (because it wants to be visible to
ghosts), and it seems a waste to dedicate an entire obj_flag to one
item, or put a hardcoded typepath.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
I'm never gonna buy a smuggler's satchel if one t ray scanner on can completely fuck it, and I'm definitely never EVER gonna buy a smuggler's satchel if one t ray scanner can probably find me one if I just wander around for a few minutes and get me one

**Comment by Angustmeta** [comment]
Probably shouldn't be visible to ghosts. At least not without t-ray on. They are very tempting.

**Comment by davethwave** [comment]
Perhaps increase the price by a few tc instead to compensate for the fact that it doesn't show up in t ray scans instead? It feels like it would improve the function and want to buy it if it keeps that ability.

**Comment by coiax** [comment]
This is a bugfix, smuggler's satchels originally showed up on t-ray scans, and no behavioral changes were intended when I re-added them shortly after their removal.

**Comment by Shardj** [comment]
Its not a bug if people like it, its a feature. Maybe add fluff that t-ray can only detect metallic entities (Wires and pipes) through tiles.

**Comment by subject217** [comment]
lol implying anyone actually walks around with t-rays on

**Comment by Shardj** [comment]
> lol implying anyone actually walks around with t-rays on

When I play as atmos tech I do

**Comment by tuypo1** [comment]
Why would any engineer not have one in their pocket? It's their job.

**Comment by subject217** [comment]
You have them equipped, you don't leave them on 24/7.

**Comment by tuypo1** [comment]
You know optical scanners are not the only type. You put one in your pocket.

**Comment by subject217** [comment]
Yes, I'm well aware of it. You still don't leave it turned on 24/7.

**Comment by tuypo1** [comment]
I do.
Why the hell wouldn't you. The whole point is to be able to notice when something is wrong.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
I don't like the idea of satchels being bullet proof, but they'll also need a TC reduction to compensate for this. Bring it down to one.

**Comment by coiax** [comment]
No complaints from me, I felt that 2 TC was too high for them anyway.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
