### PR TITLE
KA Pressure Mods are now a traitor miner item

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan, Repukan
rscadd: Traitor miners can now buy up to 2 KA Pressure Mods for 5 TC each.
balance: KA Pressure Mods now only take up 35 mod capacity each, allowing traitor miners to use 2 and have space for 1 other mod.
rscdel: R&D can no longer build KA Pressure Mods.
/:cl:

@Repukan suggested this and it sounded appropriate, given that the pressure mods are basically murderbone tools.

### CODE REVIEW

**Comment by Repukan** [comment]
Keep it at 40, it basically is a infinite ammo revolver.

**Comment by Repukan** [comment]
Also thank you for adding me to the screenshot

**Comment by VeryRealAccount** [comment]
Why are you doing your best to screw mining?

**Comment by Armhulen** [comment]
Give it a nice ass syndicate description you non-memer

**Comment by ma44** [comment]
>2 tile range weapon that does 40 damage

"infinite ammo revolver"

(or just spend 3 tc less for a actual revolver then go camp a autolathe while recycling ammo)

**Comment by Repukan** [comment]
Pressure mods suck ass in lavaland honey

**Comment by ChangelingRain** [comment]
>Why are you doing your best to screw mining?

there is no legitimate mining use of these

**Comment by ma44** [comment]
It's called being a tator by asking science to make them

**Comment by VeryRealAccount** [comment]
Dude, just quit messing with mining.  It's obvious you have no idea what you are doing.

**Comment by ChangelingRain** [comment]
>Why are you doing your best to screw mining?

What's a use of the pressure mods in mining, sir?

**Comment by Repukan** [comment]
Oh no my free murderbone weapon boohoo ;-;

**Comment by SgtxRootbeer** [comment]
newsflash @ChangelingRain 
antagonists other than traitors exist. in fact, this is like the perfect weapon for a revolution
we have cultists, gangs, revolutionaries, changelings...

**Comment by VeryRealAccount** [comment]
So that Miners can be active members of the station when they return without needing someone to blow a hole in the station?  Every change you make to Mining is god awful, and yet it keeps being merged because you are a Headmin.

**Comment by lzimann** [comment]
what kind of miner returns to the station other than leave minerals/collect rnd goods?

**Comment by ChangelingRain** [comment]
>So that Miners can be active members of the station when they return without needing someone to blow a hole in the station?

How does having a 40 damage gun make then an active member of the station? A validhunter? An antagonist murderboner?

**Comment by VeryRealAccount** [comment]
Gee, it's almost like there are situations where the station gets fucked up, people can't get access to guns, and having more people there to help combat the antagonists would help.  Being a miner doesn't mean you can completely ignore the station, you still should help out in times of extreme crisis.  Not everyone is a validhunter.

**Comment by Repukan** [comment]
Why get non pressure damage when RnD can do better guns.

Like tasers and lasers.

**Comment by Qustinnus** [comment]
with that logic why not just have 1 superior gun, right? why even have multiple guns because there should be only 1 meta option for best gun because that's fun.

**Comment by Armhulen** [comment]
Give it a nice ass syndicate description you non-memer

**Comment by VeryRealAccount** [comment]
Because half the time R&D never gets done.  Or did you forget R&D needs minerals to do their research, which is made harder by all the other changes Changeling is trying to push.

**Comment by Repukan** [comment]
>Calls me out for "validhunting" and "powergame"
>Objects to removing a module that is used in station killing and doesn't help in any way mining.

**Comment by VeryRealAccount** [comment]
For the reasons I stated, in case they are needed for the station's defense.  Not everyone is looking to validhunt with them, some people want them for legitimate reasons.

**Comment by fludd12** [comment]
@VeryRealAccount I'd love to see the statistics on how many times KAs are used as murder weapons by miners, especially when confronted with the variety of other weapons available to antagonists. Also, in "times of extreme crisis," wouldn't a super short range revolver be irrelevant or redundant...?

**Comment by VeryRealAccount** [comment]
Redundant compared to what, exactly?  A toolbox?  If the Head IDs are lost (which happens pretty often) then they can't get into the armory or weapon crates.

**Comment by octareenroon91** [comment]
>they can't get into the armory or weapon crates.

Steal an emitter.

**Comment by Hatfish** [comment]
As someone said earlier, why not just buy a much cheaper revolver which is far more useful both on and off station since you have the autolathe to print unlimited revolver ammo?
If we're locking "murderbone tools" up behind telecrystal barriers why not add meat cleavers and half of R&D to the list?

**Comment by FantasticFwoosh** [comment]
@VeryRealAccount you didn't reply to changelingrain's question so i guess we can reply to the response as "No there is no reason to have a pressure-mod in mining" because the chances you will be fighting mobs in non pressurized environments is slim to none.

All the rest of the modifications are unchanged, if you want to grief the station real good, use a sonic jackhammer which beats down walls in two hits into scrap metal. Or your other syndicate weaponry.

> Though saying that @ChangelingRain could you please make the other small tweaks transparent & mention them under ("supply tweaks"), in regards to the pie cannon & haunted 8 ball in the first commit.

**Comment by jughu** [comment]
Pressure mods help against megafauna like the hierophant so you can do max damage in the area and be safe from storms or ash walkers that invaded your mining base and forcing you to fight there

**Comment by KorPhaeron** [comment]
Do we have any stat tracking on these? I have never personally seen them

**Comment by Kraseo** [comment]
i've literally never seen anyone use a maxed out pressure-worthy KA as a murder weapon and this is an issue now???

**Comment by ChangelingRain** [comment]
>Pressure mods help against megafauna like the hierophant

No, they don't, the hierophant's arena is low pressure.

They're a murder tool, whether the murder happens to be on antags or if it happens to be on hapless crew.

**Comment by kevinz000** [comment]
:-1: - scientist/miner

**Comment by Hatfish** [comment]
Pressure mods aren't anywhere near a problem right now, this is a nerf for the sake of nerfing.

**Comment by Repukan** [comment]
Are you mad you can't have an infinite ammo 40 damage ranged weapon with your bullshit armor now kevinz?

**Comment by XDTM** [comment]
>unironically thumbing down PRs that disrupt your powergame

**Comment by 4dplanner** [comment]
The only mining thing I can see this legitimately interfering with is the wish granter ruin, honestly. Further, this makes miner KA murderer _more_ interesting, because you have to set up a situation in which your target is in low pressure instead of just taking the brainless route of adding a mod to remove a gun's characterising downside.

**Comment by ChangelingRain** [comment]
The wish granter ruin got removed( #26484) so...

**Comment by 4dplanner** [comment]
Well then.

**Comment by KorPhaeron** [comment]
Surprise I didn't get my replacement ruin like promised from that PR

**Comment by Durkel** [comment]
Rather see these removed than turned into a traitor item. No reason for them even exist in the first place when KAs were made just for lavaland.

**Comment by jughu** [comment]
Just make it tendril loot and replace the mining 3x3 upgrade one i mean you already can get a fireball wand from ash drakes which is ten times better then pressure

**Comment by BeeSting12** [comment]
I feel like this is an "i ded" thing. Has anyone been murderboned recently by one of these?

**Comment by jughu** [comment]
I never seen anyone use them when i tried 2x pressure mods and that was a year ago

**Comment by Repukan** [comment]
I murderbone often with these and I always see them in flightsuit loadouts

**Comment by Hatfish** [comment]
I haven't seen anyone murderbone with pressure mods since they were added.  Sometimes people print them to valid wizards or ops or whatever but I've never seen a traitor use pressure modkits when they could just buy a better weapon from their uplink.

**Comment by lzimann** [comment]
Let's see how it goes.

**Comment by ma44** [comment]
VIVA AGAINST THE DICTATORS

**Pull request merged**
