### PR TITLE
Visual Indicator for Bad Touch Quirk

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
## About The Pull Request

Adds a visual indicator for when you trigger someone's Bad Touch quirk. Feel free to give me a better icon for the effect.

## Why It's Good For The Game

Players who have this quirk may not have the time to convey that they do when hugged, as the hugger may be off-screen by the time the quirk holder has finished typing a say or emote. This provides a clear indicator that the quirk holder gets a negative moodlet from hugs.

## Changelog
:cl:
tweak: There is now a visual indicator for when you touch someone that has the Bad Touch quirk.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Could you elaborate on the good for the game aspect? Bad Touch is a negative quirk right? Isn't it better to force the player to convey this stuff?

**Comment by RaveRadbury** [comment]
Could you do a to_chat similar to when someone is overheating when you hug them?

**Comment by itseasytosee** [comment]
This nullifies the quirk. Why is having to explain you don't want to get hugged such a bad thing?

**Comment by RaveRadbury** [comment]
I think the feedback is good, getting feedback from the game is a part of what quirks are about in the first place, otherwise we are just running around pretending things to ourselves constantly.

>This nullifies the quirk.

If you're measuring the quirk in terms of it's actual activation then yeah I guess, but it's not about getting wrecked by the moodlet, it's about crew getting negative feedback from hugging someone. Now that I'm saying it out loud, there should be a negative moodlet for the one giving the hug as well, maybe just for empath?

**Comment by RaveRadbury** [comment]
If this let you know beforehand that they didn't like hugs, then yeah, it would nullify the quirk. But people mindlessly and casually hug, and they ignore to_chat and visual indicators constantly. People are still going to get randomly hugged by a bunch of people, and those people will not remember who doesn't like hugs.

This seems like worthwhile texture. "It's not a negative quirk if you don't have `Sorry I don't like hugs` in your clipboard" doesn't seem like a great design philosophy.

**Comment by Y0SH1M4S73R** [comment]
> Now that I'm saying it out loud, there should be a negative moodlet for the one giving the hug as well, maybe just for empath?
Would that be better suited as its own atomized PR, or could it reasonably be added to this one?

**Comment by RaveRadbury** [comment]
> > Now that I'm saying it out loud, there should be a negative moodlet for the one giving the hug as well, maybe just for empath?
> 
> Would that be better suited as its own atomized PR, or could it reasonably be added to this one?

Atomize for sure, that's something that should be added separately.

**Comment by MrMelbert** [comment]
(As the original author) I got recommend to have a visual indicator like friendly for the quirk but I didn't do it because I can't sprite. So +1 from me.

**Comment by Fikou** [comment]
lame ass, this makes the quirk only bad if someone is hugging you maliciously

**Comment by Fikou** [comment]
> Now that I'm saying it out loud, there should be a negative moodlet for the one giving the hug as well, maybe just for empath?

??? why should a negative quirk give someone else a shit mood??

**Review by Twaticus — APPROVED** [review]

**Comment by coiax** [comment]
> 
> 
> lame ass, this makes the quirk only bad if someone is hugging you maliciously

I think it's fair to say that actually visual indication of applying a bad mood to someone is actually likely to make some people even more prone to do it.

**Comment by RaveRadbury** [comment]
> ??? why should a negative quirk give someone else a shit mood??

`Why should seeing someone else upset make me upset?`
image

**Comment by itseasytosee** [comment]
I think he means from a mechanical sense.

**Comment by RaveRadbury** [comment]
> I think he means from a mechanical sense.

I did say `maybe just for empath` when I made the suggestion, but also from a mechanical sense, to keep people from spam hugging the person who doesn't want the hugs? He makes a good point that it makes less mechanical sense for any random crew member to get a mood debuff from it. Would be nice to see on empath, maybe social anxiety, too.

**Comment by cacogen** [comment]
Why does this quirk even exist

**Pull request merged**
