### PR TITLE
Adds a single D4 to Lavaland mining base

### PR DESCRIPTION
**Pull request by LanCartwright**
:cl: optional name here
add: 1D4 into Lavaland Mining base crate.
/:cl:

[why]: # 
What could POSSIBLY go wrong?
>Roll it with your buddies to decide who gets the loot!
>Roll for KA, Plasma cutter, Crusher, or Reso!
>Play D4 games whilst the ash storm rages on!
>So many great, wacky and wonderful things to do!
>Use it as a caltrop against native shoeless wildlife.

A useful defense against native wildlife.

### CODE REVIEW

**Comment by DoctoreMad** [comment]
D4 deals damage to barefooted players and stuns them
This means ash ligger invasions are going to be fucking terminated the moment a smart miner realizes this change is in

**Comment by PKPenguin321** [comment]
It's a worse soap that only works on barefoots, yes. I think that's the point.

**Comment by DoctoreMad** [comment]
Yeah.

**Comment by LanCartwright** [comment]
I mean you can already buy soap or smash windows. I think this will be pretty humorous.

**Comment by Kraseo** [comment]
good fuck ashlizards who metaknowledge their way into the base

**Comment by Repukan** [comment]
Gud change

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
