### PR TITLE
pubby map changes

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
🆑
tweak: expands cargo
tweak: adds some minor maint rooms
tweak: adds maint shipyard
tweak: adds trading area near cargo
/🆑

images in the map diff bot

### CODE REVIEW

**Comment by uomo91** [comment]
You have some leftover cargo maint area tiles, down by science.
Also, the bazaar just kinda feels like a second commissary... Seems like you could do something more interesting with that space.
Looks cool otherwise.

**Comment by Fikou** [comment]
i think that supplypod you placed there will be an untouchable object

**Comment by LemonInTheDark** [comment]
Feels like powercreep but you added airlocks so I don't even care

**Comment by Tlaltecuhtli** [comment]
> i think that supplypod you placed there will be an untouchable object

tested its interactable

**Comment by actioninja** [comment]
conflict

**Pull request closed without merging**
