### PR TITLE
Tidies up the vacant office airlocks on all maps with vacant offices.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

All vacant office airlocks on all maps are now public access.

I also changed the color of the vacant office airlock on Ice Box to reflect the fact it no longer needs engineering access, as well as changed its name from "Vacant Office A" to just "Vacant Office" due to the fact that Vacant Office B no longer exists.

The vacant office airlock on Meta didn't have a name at all, and that has been fixed too.

## Why It's Good For The Game

The vacant offices have no reason to be access restricted, and i think this might invite more people to do interesting things with them.

## Changelog
:cl:
add: The vacant offices on Ice Box and Delta are now public access.
add: The Ice Box vacant office airlock has been turned into a plain airlock to reflect the fact it no longer needs engineering access to open. It has also been renamed to reflect the fact that Vacant Office B no longer exists.
tweak: The Meta vacant office airlock has a name now when it was unnamed before.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
the rooms being engi only access makes them interesting and usable as cult bases etc, as they didnt have any loot for tiders and  you had to hack in as sec, this makes them just another dumb maint room

**Comment by sergeirocks100** [comment]
The vacant office is incredibly easy to get access to.

If not through the HoP, then by taking a welder and a wrench to one of the walls.

Not to mention, there are plenty of other maintenance areas throughout the station for cultists or similar to set up their bases.

All the current access restrictions do is deter people who may want to do something interesting with the vacant office.

**Comment by interestingusernam3** [comment]
>If not through the HoP, then by taking a welder and a wrench to one of the walls.

But noone actually needs the access unless they want do do something cool with the vacant office. This makes the change unnecessary.

Also the office is a great hiding spot for the people who have access because of the restricted access. For absorbing people as ling and the like. If the access restrictions are removed, it will be worse than toilets for that purpose because people will go through it to access maint.

**Comment by RaveRadbury** [comment]
Worth noting that currently Metastation's vacant office is publicly accessible.

**Pull request merged**
