### PR TITLE
species changes part 2: adds colored blood

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

makes blood types into datums instead of strings, the datum handles the name, other safe bloodtypes and the color
blood is now greyscale
lizard blood is now teal
image

todos:
- [ ] make blood element a component and not a subtype of the decal element so it has proper duping support
- [ ] make blood mix together colors instead of using the latest added one

## Why It's Good For The Game

it looks neat

## Changelog

:cl: Fikou, Icons from OracleStation
expansion: Blood is now greyscale. Make sure to report any suspiciously white stains on GitHub.
expansion: Lizards have teal blood.
/:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
I think this might be okay if 1-2 species gets their own blood colour.

However, if you give too many races unique blood colours you end up with the horrid clown vomit look like on paradise station.

**Comment by AMonkeyThatCodes** [comment]
I mean ethereals are tons of colors and have bio luminescent blood soo

**Comment by Krysonism** [comment]
> 
> 
> I mean ethereals are tons of colors and have bio luminescent blood soo

emissive blood would actually be really cool though.

**Comment by necromanceranne** [comment]
well this will certainly make fixing ethereal blood easier, cool beans.

**Comment by Time-Green** [comment]
Amazing work 👍

**Comment by KittyNoodle** [comment]
Can you make ethereals actually show the fact that they are bleeding just make it light green like the reagent

**Comment by KittyNoodle** [comment]
Because we are here and regular le does nothing and has bugs because of that let’s just refactor LE into a blood type

**Comment by Fikou** [comment]
lol

**Comment by Time-Green** [comment]
Wait what why 🥺

**Comment by optimumtact** [comment]
fikou finish this one

**Comment by dragomagol** [comment]
[[https://cdn.discordapp.com/emojis/771494770937036811.webp?size=96&quality=lossless]]

**Pull request closed without merging**
