### PR TITLE
Removes Stray Space in Species_type in an effort to save the world.

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Removed a stray space that was associated with TOXINLOVER on the off chance that it is creating issues.

For those that aren't aware, zombies can't currently spacewalk despite their flags.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
They're not actually flags, they're a list, don't make them look like flags; there's too many of them for them to work as a bitflag thing anyway

**Comment by optimumtact** [comment]
yeah this isn't the issue

**Comment by optimumtact** [comment]
also what do you mean by spacewalk? Zombies are not immune to pressure it still affects them

**Comment by ExcessiveUseOfCobblestone** [comment]
so what tag gives the skeletons pressure immunity that the zombie doesn't have? Looking at species_types, I was under the impression that the zombie should be able to space walk just as well. i'll revert the defines as well

**Comment by optimumtact** [comment]
What exactly is affecting the zombies?

**Comment by ExcessiveUseOfCobblestone** [comment]
errrr i can check after i eat dinner.

**Review by phil235 — APPROVED** [review]
:+1:

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact just checked, zombies die from space because of all the normal reasons a human would die from space, such as:

O2 Dep
Pressure
Cold

so I'm assuming it probably has something to do with the stray space.

**Comment by XDTM** [comment]
There's a type of zombie which has no special flags, for krokodil addicts. I think you might've used that one when testing.

**Comment by optimumtact** [comment]
#21287 may be affecting admin verbs to specie switch people.

**Comment by ExcessiveUseOfCobblestone** [comment]
maybe, I'll just close this and see if your fix actually does it

**Comment by ExcessiveUseOfCobblestone** [comment]
actually wait i want this to happen anyways because muh consistency

**Pull request merged**
