### PR TITLE
Terror in the Toybox: The Rouny Plushie

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Adds a Rouny plushie to the game, from TGMC. Perfect for cuddling, unlike the real thing. Sprites by domitius.
image

## Why It's Good For The Game
Cute, cuddly, and a neat nod to TGMC, which is linked in the lore- not that you'd know it by looking at what's in the game, hence why little anchors like this are nice.

## Changelog
:cl:
add: To celebrate the 100th anniversary of the Battle of LV-426, TerraGov have teamed up with everyone's favourite toy manufacturer, Cuddles Corporation, to produce a limited edition (not really) Runner plushie. Get yours today from Cargo, or your nearest arcade machine!
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
SOMEONE TELL ME I'M NOT GOING CRAZY I SWEAR THIS WAS ALREADY PR'D

**Comment by EOBGames** [comment]
> SOMEONE TELL ME I'M NOT GOING CRAZY I SWEAR THIS WAS ALREADY PR'D

https://www.youtube.com/watch?v=dv13gl0a-FA

**Comment by Kylerace** [comment]
THAT 👉
is a rouny

**Comment by SplinterGP** [comment]
Absolutely blessed

**Pull request merged**
