### PR TITLE
Abduction Fixes & Tweaks

### PR DESCRIPTION
**Pull request by AnturK**
- Fixes observers not seeing abductor hivemind
- Fixes humans without glands getting added to experiment history
- Makes science tool marking more intuitive (Just one click to mark anything now)
- Adds small storage space with standard cuffs
- Adds Advanced Baton - Stun,Sleep,Cuff in one tool
- Makes console landmarks search for nearby machine/pad instead of spawning them next to it for mappers - temporary way of doing this 
- Adds Vest Cameras for abductor agents
- Fixes only one team spawning
- Fixes roundend report
- Fixes adding more teams to the round

More to come

### CODE REVIEW

**Comment by Xhuis** [comment]
:alien: :alien: :alien:

:+1:

**Comment by AnturK** [comment]
Goddamit mapmerge what is it this time

**Comment by AlexCrimson** [comment]
Might want to add the ability for admins to custom spawn Aliens. Right now they are limited to the "create antagonist" button which pulls random ghosts.

**Comment by RemieRichards** [comment]
@AnturK Sexy as fuck sprites courtesy of Imblyings:
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3392&p=82315#p82282

Implement them <i>now</i>

**Comment by AnturK** [comment]
Yeah just saw them, putting them in a moment.

**Comment by RemieRichards** [comment]
I know you saw, I saw you saw but I posted after I saw which was before you saw :P

**Comment by AnturK** [comment]
Will add helmet/specific glands later.

**Comment by AnturK** [comment]
Alright i believe all the worst bugs are fixed so this ready to go. The next changes will come in another PR.

**Comment by AnturK** [comment]
Conflicts solved

**Comment by peoplearestrange** [comment]
:+1: 

Also I would suggest making the syndicate/abductor headsets immune to the Silencer device. It seems to mute all headsets with in a small AOE rather than directly the target (which is fine), but you always end up muting your own headset as well.

**Pull request merged**
