### PR TITLE
Gives shamebrero penguin a chance to appear in the holodeck

### PR DESCRIPTION
**Pull request by Cyberboss**
Closes #38491 

This gives shamebrero penguin a chance to appear in the holodeck simulation

                     /_-_-_\
             _______|-_-_-_-|________
            (________________________)
             ! ! ! ! ! ! ! ! ! ! ! ! !

### CODE REVIEW

**Comment by fluffe9911** [comment]
Suprised no ones made a penguin crate yet for cargo

**Comment by improvedname** [comment]
When will all penguins walk away from the shamebrero penguin because shame on him

**Comment by pubby** [comment]
dumb

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by cyclowns** [comment]
could make it a gold core spawn

**Comment by KingPhilipIII** [comment]
Other penguins should definitely avoid the shambrero penguin. It'll also make it more complex than just a penguin with a hat.

**Pull request merged**
