### PR TITLE
Creates short-lived foam (and applies it to the Scrubber Overflow)

### LINKED ISSUE #69689: Scrubber Overflow foam still takes ages to dissappate
## Round ID:

[189754](https://scrubby.melonmesa.com/round/189754)

## Reproduction:
 
Scrubber Overflow triggered at station time ~1:25
And only JUST began to dissipate at station time ~1:32

The foam lasted for seven minutes

This is why it was removed in the first place and it's still an issue it seems #53549

### LINKED ISSUE #71830: Foam Grief event
## Round ID:
This has gone to the point of being a legitimate neglectful to the general game it slows everything down it takes far to long to disappear nobody likes it nobody wants it make it leave faster because this is a legitimate issue

## Reproduction:
Have the random even misfortune to have scrubbers overflow and throw rainbow vomit over everything as you see the foam slip and they on the ground for legitimate 10's of minutes on end as you see it start to disappear being minutes apart for tile

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Creates a short-lived foam with a lifetime of 1 SECOND instead of the default 8 SECONDS to address some complaints about the scrubber overflow event overstaying its welcome. 

## Why It's Good For The Game
Fixes #69689 
Fixes #71830

## Changelog
:cl: Tattle
balance: the foam used in the scrubber overflow has a lifetime of 1s instead of 8s
/:cl:

### CODE REVIEW

**Comment by DaydreamIQ** [comment]
> Nah, it doesn't overstay it's welcome. It happens a bit often, but when an event happens, it should matter. 1s is practically nothing and also the event can have some... fun effects.
> 
> Don't massively nerf one of our most unique events, please...? Like, by 8 times?

In its current state the foam literally lasts for five minutes and does nothing but make people groan and do nothing until it very slowly goes away. Nerfing it by 8 times is the bare minium

**Comment by dragomagol** [comment]
> Nah, it doesn't overstay it's welcome. It happens a bit often, but when an event happens, it should matter. 1s is practically nothing and also the event can have some... fun effects.
> 
> Don't massively nerf one of our most unique events, please...? Like, by 8 times?

This is 1 second lifespan with a massive asterisk. If the 8 second foam lasts for 10 minutes, this will make the foam last for 1.25 minutes. If it's between nerfing it and removing it, I would prefer to keep it around.

**Comment by TheBoondock** [comment]
We shouldve brought back scrubber overflow with atmos instead of foam :)

**Comment by optimumtact** [comment]
This makes no sense? Just change the foam system to spawn only 1 tile of foam and spread it?

at most then it will last 30 seconds.

**Comment by optimumtact** [comment]
in fact
why does the lifetime change this at all? Is the foam lifetime actually defined by the reagent amount?

**Comment by dragomagol** [comment]
The foam lifetime is defined in `/obj/effect/particle_effect/fluid/foam` as `/// The amount of time this foam stick around for before it dissipates.` Once it goes past its lifetime the foam effect starts to delete itself. The reagent amount seems unrelated to the lifetime of the foam.

**Comment by Pickle-Coding** [comment]
Would servers with different performance have the foam last at different durations? I don't really like the idea that every second of foam duration is over a minute of foam duration for the event.

**Comment by private-tristan** [comment]
> Would servers with different performance have the foam last at different durations? I don't really like the idea that every second of foam duration is over a minute of foam duration for the event.

Yes, servers with higher time dia will have it for much longer than those without, on high time dia servers the entire station floods with foam for 10 minutes, with this change it'll hopefully only last 30 seconds to a minute on highpop while it'll only last a few seconds on lowpop

**Comment by RikuTheKiller** [comment]
> > Nah, it doesn't overstay it's welcome. It happens a bit often, but when an event happens, it should matter. 1s is practically nothing and also the event can have some... fun effects.
> > Don't massively nerf one of our most unique events, please...? Like, by 8 times?
> 
> In its current state the foam literally lasts for five minutes and does nothing but make people groan and do nothing until it very slowly goes away. Nerfing it by 8 times is the bare minimum

Okay fair it doesn't really last 8 seconds anyways.

**Pull request merged**
