### PR TITLE
Fixes gatfruit and ghost chili names

### PR DESCRIPTION
**Pull request by MisterTikva**
Title

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Critical priority

**Comment by ma44** [comment]
A tree?!

**Comment by MisterTikva** [comment]
> A tree?!
Yep it's a tree with revolvers

**Comment by ShadowDeath6** [comment]
botany finally getting the lore it needs, I see

**Comment by KingPhilipIII** [comment]
Some day four lifebringers armed with revolvers and an army of tomatoes will slay Legion.

**Pull request merged**
