### PR TITLE
New Item Sprites

### PR DESCRIPTION
**Pull request by CameronWoof**
Updates several existing sprites and adds new ones.

- Updated first aid kits (all variants)
- ~~New mini first aid kit sprites~~
- Updated briefcase and secure briefcase (with in-hands)
- Updated mounted intercom sprites

Preview of all new sprites:
https://i.imgur.com/VAab9dV.png
(mini kits no longer included)

EDIT: New first aid sprites below. Other sprites are still the same.
https://cdn.discordapp.com/attachments/326849939240124419/374982121250488322/unknown.png

### CODE REVIEW

**Comment by optimumtact** [comment]
Welcome to the repository, just to check, are you sure you meant to open this PR to tgstation and not one of the downstreams?

**Comment by DoctoreMad** [comment]
This reverts the clownbox change, which was merged. Bad, bad.

>radiation-small

We don't have any item that uses this.

I do like the inhands though.

**Comment by praisenarsie** [comment]
@optimumtact it is for this repo, i talked to him.

**Comment by ACCount12** [comment]
First aids are too small, they don't look like first aids at all. Same with intercomms.

**Comment by deathride58** [comment]
Merge conflicts need fixing, but these new sprites fit TG's newer artstyle pretty well.

It shouldn't be too hard to code in something that uses the small variants of the sprites in the future when this gets merged. Perhaps small medkits that only contain 1 half bruisepack, 1 half ointment?

**Comment by CameronWoof** [comment]
Fixed the clown box thing. Really not sure how that happened, unless clown boxes were updated since I copied the repo like an hour ago.

**Comment by DoctoreMad** [comment]
They were, actually.

**Comment by deathride58** [comment]
To fix the merge conflict, you need to update the branch to match with upstream. You can do this in github desktop with the "Update from tgstation/master" button.

**Comment by CameronWoof** [comment]
Alright, horrible conflicts episode is over. It should be proper and correct-style now.

**Comment by duncathan** [comment]
@Wjohn

**Comment by MoreRobustThanYou** [comment]
HOLY FUCK THAT'S SEXY AF

**Comment by nicbn** [comment]
39b66455fbc67bc69aeda856763ca858--spider-man-funny-spider-meme

**Comment by XDTM** [comment]
Good sprites, and the rounded edges convey that first aid boxes are not good weapons, since they could be interpreted as metal boxes currently

**Comment by PKPenguin321** [comment]
Only one I don't like is the wall mounted station radio, doesn't really look like a radio at all

**Comment by WJohn** [comment]
Yeah I don't like the wall mounted radio at all, it looks more like a terminal than it does, you know, a speaker/microphone. Would probably need to be started from scratch from what you've shown.

As for the suitcase, They need a more vivid color with an appropriately brighter strip of lighting, as it looks a bit dreary there. New inhands are pretty neat, but yeah you could give em the same new coloring pass after you do this.

The medkits I'm not huge on, they're pretty tiny -- smaller than regular boxes actually -- and could be given additional details if made bigger.

**Comment by Arianya** [comment]
Basically agree with PKP, like everything except the wall radio

**Comment by Jalleo** [comment]
Slightly bigger to have better detail I would agree with. Also maybe we should add emergency first aid lockers for those mini kits?

**Comment by CameronWoof** [comment]
New, larger first aid kit sprites.
https://i.imgur.com/ZAAEYBW.png

**Comment by Bawhoppen** [comment]
I am just a novice but something looks off about those to me

**Comment by CameronWoof** [comment]
As far as the radio goes, this sprite was my attempt to incorporate the elements present in the current sprite; a speaker/microphone, a screen (the round light-blue thing is a screen, I think?) and a keypad to enter frequencies rather than what appears to be two buttons for manual tuning. 

It looks different, but the intention was to create something made up of easily identifiable elements that form an intercom, since the current sprite verges on unrecognizable unless you already know what it is.

**Comment by Arianya** [comment]
I believe the blue area is meant to be a radio frequency selector as opposed to a true screen.

The issue with the new radio is that it looks very much like a computer terminal with a little attached bit.

**Comment by Supermichael777** [comment]
Your first shot at the first aid kits was good, those huge flat ugly suitcases belong in the trash

**Comment by CameronWoof** [comment]
https://cdn.discordapp.com/attachments/326849939240124419/374982121250488322/unknown.png current iteration

**Comment by MoreRobustThanYou** [comment]
@CameronWoof keep up the nice work!

**Comment by Jalleo** [comment]
Yeah that third version is better. I did like the mini first aid kits though. They just needed to be a tiny bit better.

**Comment by ACCount12** [comment]
First aids are better now, but intercom is still shit.

**Comment by optimumtact** [comment]
I must be the only person who likes the new intercom sprite

**Comment by MoreRobustThanYou** [comment]
@optimumtact nope,I like it too

**Comment by Jalleo** [comment]
Changing the green screen to a more old fashioned radio look might work

**Comment by WJohn** [comment]
Still needs updating of intercomm and other sprites, don't merge until then.

**Pull request closed without merging**
