### PR TITLE
Swarmers think the deep fryer is too tasty to eat

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Swarmers no longer consume the deep fryer, since they have too much
respect for the potential fried foods it can produce.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by PKPenguin321** [comment]
Wait is there an actual reason for this or is it just supposed to be funny because I laughed

**Comment by bgobandit** [comment]
funny meme but there's no actual reason for it

**Comment by Kromgar** [comment]
Rib at joan for making the srk invincible to swarmers

**Comment by ShadowDeath6** [comment]
Same reason it can't eat the chem dispenser, it has dangerous substances in it.

**Comment by optimumtact** [comment]
Swarmers are not allowed to eat lots of stuff so this is fine

**Comment by Armhulen** [comment]
YES

**Pull request merged**
