### PR TITLE
Lowers Nuka Cola Speed by 25% & Increases Soda Premium Drink Costs

### PR DESCRIPTION
**Pull request by wesoda25**
:cl: 
balance: slows nuka cola a bit
balance: premium drinks now cost $30
:cl:

Basically a dupe PR, I was dumb and couldn't edit the last one when necessary, forcing me to create this. Refer to past PR for all arguments and such: #42091

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Are people making this in bulk as well as buying it? If the issue is the reagent then nerf the reagent, but if the issue is the availability then nerf the availability. I don't think it's wise to shotgun approach it unless it actually warrants such.

**Comment by wesoda25** [comment]
No, it’s because nuka cola makes you go insanely fast. In theory nuka cola would scale, however I don’t think it did that quite as well as we hoped. The nuka cola is simply too fast considering the ease to acquire it. 

Maybe I’m wrong, but the speed difference feels even larger with movement speed changes. 

I legitimately feel this makes nuka cola a better, more balanced reagent. Its not a huge change anyways, just -0.25 (+0.25 really).

**Comment by ExcessiveUseOfCobblestone** [comment]
this PR nerfs both the reagent **and** the availability which is my concern.

**Comment by Cyberboss** [comment]
Pick one

**Comment by wesoda25** [comment]
Alright now it retains its speed but is replaced in vending machines.

**Comment by RogueSteampunker** [comment]
So instead of just lowering nuka-cola speedup a tad to keep it in line with basically being as simple as a bar of uranium and a cola, we're replacing it with a drink whose only purpose is to either stop being fat, make the chef want to end his own existence, or take a neat spin on "tie someone up and poison them"?

Seems pretty silly to me

**Comment by wesoda25** [comment]
> So instead of just lowering nuka-cola speedup a tad to keep it in line with basically being as simple as a bar of uranium and a cola, we're replacing it with a drink whose only purpose is to either stop being fat, make the chef want to end his own existence, or take a neat spin on "tie someone up and poison them"?
> 
> Seems pretty silly to me

You know what, you're right. I'd much rather prefer to see nuka cola actually have some sort of slowdown as opposed to making it slightly harder to acquire. That being said, don't diss Fernet, shits more deserving of premium status than Nuka Cola. However, I would also like to put this beyond assistant roundstart price range. So I think I'll bump premium drink prices up $5? Now assistants have to work a little to go speedy.

**Comment by ExcessiveUseOfCobblestone** [comment]
just uh let someone know when this is ready lol

**Comment by wesoda25** [comment]
It works fine I just tested it.

**Comment by ExcessiveUseOfCobblestone** [comment]
Looks alright, if it's still wild we can look at boosting the price for the drink specifically since I don't want to devalue the reagent too much (it does take uranium).

**Comment by wesoda25** [comment]
Just a little follow up, the speed is a LOT better now.

**Comment by ExcessiveUseOfCobblestone** [comment]
good to hear, thanks for PRing that!

**Pull request merged**
