### PR TITLE
Drastic Lag Mitigation Subsystem: SSlag_switch

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Requested by oranges and inspired by the upcoming event. A new subsyetem, non-processing (for now), aimed at providing some toggle switches that can be flipped as a last ditch effort to save some CPU cycles by sacrificing some non-critical mechanics. Below you can see each individual toggle.

Screenshot of the admin panel:
image
Surely there are more opportunities for toggles I missed, but adding new ones is not very difficult at all.

## Why It's Good For The Game

Better performance during extreme pop, I hope. 

## Changelog
:cl:
code: Introduces the Lag Switch subsystem for when a smoother experience is worth trading a few bells and whistles for. Performance enhancement measures can be togged by admins with the Show Lag Switches admin verb or enabled automatically at a pop amount set via config.
config: Added a new config var: number/auto_lag_switch_pop
/:cl:

### CODE REVIEW

**Comment by MrStonedOne** [comment]
ideas:
trait overridden talk/say block
disable deadchat
disable hard deletes

**Comment by Wayland-Smithy** [comment]
I tried to avoid mass curtailing of the ability to send chat altogether since it'll probably quickly overflow into OOC resulting in a mute of that followed by ahelps and bans I'd imagine.

Thoughts on a "slowmode" type solution instead maybe using cooldowns? With a input for the seconds between messages changeable by admins. I bet tgchat could even be setup without too much trouble to show a progress bar or a countdown timer type deal after you send a message.

**Comment by Wayland-Smithy** [comment]
Slowmode added, but I gave up trying to do a `Loader` style progress bar on the tgchat panel since it required periodic updates from the server to keep in sync with any possible time dilation in effect and while that works fine for alert and list pick dialog timeouts sending it all the time for chat to be used only with slowmode seems a non-starter.

Also if someone could remove the code tag and add perf that'd be much appreciated.

**Comment by Cyprex** [comment]
>Disable deadmob keyloop
This is rather unclear, if it does what I think it does here's a suggestion:
Disable Ghost Movement

**Comment by Wayland-Smithy** [comment]
It does not just affect Ghosts or their Movement though? Yes in practice it does disable ghosts from flying around with movement inputs like WASD, but they can still Teleport, Orbit, and Jump with double click as my large dchat notice states to existing dead when the measure is enabled and also mobs that die after it is enabled.

In my opinion the wording is fine for a, hopefully seldom used, admin control panel. If an admin does not understand what disabling the keyLoop means then they need not press the button and let someone else or the auto trigger do it, but you seemed to sus it out easy enough.

**Comment by Cyprex** [comment]
I'm a very technical person, certainly not representative of the admin team

**Comment by Wayland-Smithy** [comment]
Still `+ADMIN` ranks do have dchat ears so they too will see the obnoxiously large "informs dchat" announcement when the keyLoop measure turns on describing the effect on ghosts in more detail. Plus you or anyone else who would like to are welcome to PR tweaks to the language and grammar for the UI since it's free game after merge and I'm only interested it getting it ready for the event.

**Comment by optimumtact** [comment]
I think we should probably do a test merge of this and enable it at least once just to be sure.

**Comment by optimumtact** [comment]
I will try to arrange this weekend

**Comment by Wayland-Smithy** [comment]
Got some testing done during the event too and the switches that were used performed excellently just as advertised: runechat, examine icons, and ghost view range. 

Therefore I'm considering making the auto trigger only enable that sub-set since it feels like a good tradeoff while avoiding the more draconian measures right off the bat.

Lastly I noticed a verb under the server tab for "Toggle Entering" does already exist, but adds notice text to the byond pager server info instead of in the admin jobs manager and on the late join jobs list like my double negative "Disable non-obs joining" so I'll probably remove the old verb or have it toggle that specific switch instead.

**Pull request merged**
