### PR TITLE
Fixes nuke op reinforcements spawning naked

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
whoops

### CODE REVIEW

**Comment by yackemflam** [comment]
Why isn't this merged yet?

**Comment by PKPenguin321** [comment]
not every fix needs to be quickmerged

**Comment by yackemflam** [comment]
>Next time ops start
>Someone buys a reinforcement
>Guy is naked
>No admin on
>FUCK

**Comment by ma44** [comment]
>implying there's never an admin on

**Comment by evsey9** [comment]
f e a t u r e

**Comment by yackemflam** [comment]
ma44, I play during times when there's no admins.

**Pull request merged**
