### PR TITLE
Chembomb and grenades

### PR DESCRIPTION
**Pull request by nullbear**
Continuation of https://github.com/tgstation/-tg-station/pull/16626

Fixed two runtime errors i came across while testing. Got rid of accident with atoms.dm

### CODE REVIEW

**Comment by nullbear** [comment]
@GunHog I'm a git noob. If there's anything fishy that catches your eye, let me know.

**Comment by phil235** [comment]
What's the point of chembombs when we already have chem grenades? In what kind of scenarios would someone prefer to use a chembomb?

**Comment by nullbear** [comment]
what do you mean? There's nothing wrong with my commits.

And when you want to mix 3+ beakers, whether it's for reactions that dont work with only two beakers, or with bigger blasts.

As well, the grenades have some unique effects in and of themselves, which can be added to the bomb if used in the crafting recipe. Pyro self ignites, eliminating the need for an 'igniter' chemical in many mixes, and the advanced release grenade allows for area denial, or more intensified effects, such as using a flash powder mixture to keep an area down for upwards of a minute if you use bluespace beakers.

Typically, the bomb is intended to be used as a less tactical alternative, but more effective. Good for if you're not really in a time-sensitive area, and you want to do some serious damage or even just annoying affects, and is really just 2-3 times better than a grenade casing, barring the fact that it takes 1-2 minutes, and is very high profile. Using a smoke+chloral mix while testing, i was able to get the mix to spread 3x as far as a normal grenade, which managed to flood the entirety of the primary central hallway. Typically, with grenades, smoke grenades especially, they are easily able to be outran before they have any effect. Bigger radius means you prevent that, for longer.

And cause it's a feature, it adds flavour, makes use of existing bomb systems, is very dynamic, and people will want to play with it. it's fun.

**Comment by GunHog** [comment]
By "Fix your commits", he likely means that he wants you to "squash" them into a single commit, as it looks as if you have many. **IF THIS IS YOUR FIRST TIME DOING THIS, MAKE A COPY OF THIS BRANCH AS A BACKUP BEFORE YOU PROCEEED.** You will be fine if you have good instructions, but based on personal experience, it is a _very_ good idea to have a backup. I suppose you have your old PRs to use if you screw up the rebase attempt.

**Comment by nullbear** [comment]
any link to good instructions? Every attempt i've made before just results in hundreds of merge conflicts.

**Comment by GunHog** [comment]
I do not recommend you attempt this on your own. If I were you, I would ask @phil235  in coderbus for a walk-through. He is one of the best maintainers we have, and he will guide you well. Still, make sure you have a backup before you begin either way.

**Comment by nullbear** [comment]
i think i did it?

**Comment by nullbear** [comment]
Okay, how's that?

**Comment by phil235** [comment]
@GunHog Don't ask me how to squash commits, I still don't know how, lol. I'd suggest just starting a new branch from your master.

**Pull request closed without merging**
