### PR TITLE
Combat Shotgun Price Increase

### PR DESCRIPTION
**Pull request by Robustin**
Not a complete solution, but its at least a step towards better balance. 

Price is now 8,000 up from 4,000. 

Next Step: Balancing exports.

### CODE REVIEW

**Comment by Kromgar** [comment]
make it 10000!

**Comment by jughu** [comment]
@Robustin you mean next step balancing tech disks

**Comment by ExcessiveUseOfCobblestone** [comment]
!img[1million](https://media.giphy.com/media/13B1WmJg7HwjGU/giphy.gif)

**Comment by Robustin** [comment]
That would be part of it Jughu but there's quite a bit that needs to be looked at for exports.

**Comment by ExcessiveUseOfCobblestone** [comment]
@jughu tech disks [at least on sybil] rarely exist. Most of the money there comes from Minerals from mining since RND needs so little after one set.

**Comment by Cheridan** [comment]
Needed to happen, War Ops is pointless when there's a combat shotgun for each crewman.

**Comment by Repukan** [comment]
Two shotguns per crate should be the norm too.

**Comment by jughu** [comment]
Auctally in a sense stuff like disablers 
Disablers are currently 1500 units
They come in pairs of 3 the crate itself is worth 500 credits so practically the cost -500 = result

**Comment by Robustin** [comment]
Yea I'm going to need more input from coders and cargo nerds before I attempt to fix exports. But exports aside, weapon prices should reflect power and it doesnt get much more powerful than a combat shotty.

**Comment by KorPhaeron** [comment]
Bandaid fix for cargo having too much money

**Comment by Robustin** [comment]
Except its not a "bandaid fix", even once exports are balanced there's still the issue of "why would anyone buy anything but combat shotguns when it comes to weapon choices". A high price is something that will persuade some cargo players to go for other options instead.

**Comment by optimumtact** [comment]
This wont' matter because war ops will always lose against a population > 30

**Comment by GunHog** [comment]
Make the crate come with fewer guns instead, these are needed for Combat 7!

**Comment by ExcessiveUseOfCobblestone** [comment]
If you remove all exports and have them focus on stocks [progression-based moneymaking] then cargonia will be cured.

**Comment by Iamgoofball** [comment]
>>>taking away cargo's guns

**Comment by Repukan** [comment]
Are you being retarded again

**Comment by jughu** [comment]
Certain crates unlocking on certain levels when

**Comment by ExcessiveUseOfCobblestone** [comment]
I may play cargo for a few days and just tweak numbers on how that goes, as I don't think running an arms race between money-making and prices of crates will do much good in the long run.

**Comment by Robustin** [comment]
Yea I'm torn. On one hand I like the cargo kind of has a designated mineral to export, I don't think it will be healthy if you start having multiple dept's fighting over diamonds either. Plasma will almost certainly need a tweak but I don't it already has a low redemption value and I don't want the miners to start ignoring it either.

**Comment by PKPenguin321** [comment]
>I don't think it will be healthy if you start having multiple dept's fighting over diamonds either

What do you mean by this?

**Comment by Robustin** [comment]
I mean if we nerf plasma exports and make it so the rarest minerals are also worth the most points, then pretty soon you have cargo techs and scientists killing each other outside the ORM because both desperately want diamonds so they can get [insert powerful weapon here]. 

Right now cargo collects plasma from the ORM and science collects everything else, so things are more harmonious.

**Comment by PKPenguin321** [comment]
I'd actually love an genuinely valuable mineral that's so desired it creates non antag conflict

**Comment by Repukan** [comment]
Bananium?

**Comment by jughu** [comment]
Lets add mythril :thinking:

**Comment by GunHog** [comment]
I have gotten into fights with the QM after I discovered that he took ALL the minerals to sell, even though I offered him tech disks instead. I am not against having to share the minerals, and PKP's point is valid here. 

Even so, I would rather not see these guns be harder to obtain as there are few viable options for acquiring combat 7. Bananium does not spawn as an ore, it comes from the clown ruin or the crashed ship in space (if that still exists even)

**Comment by bgobandit** [comment]
>I mean if we nerf plasma exports and make it so the rarest minerals are also worth the most points, then pretty soon you have cargo techs and scientists killing each other outside the ORM because both desperately want diamonds so they can get [insert powerful weapon here].

I see no problem with this, minerals are supposed to be a source of potential departmental conflict/scarcity, they just aren't at the moment because the only people who ever want them are scientists/robos

**Comment by Hatfish** [comment]
Why not just make plasma rarer instead of making the one thing the station exists to collect worthless?

**Comment by Dorsisdwarf** [comment]
Why are the science players here acting like this is deleting them from the game entirely instead of making them more expensive to reflect their power? 


If anything "but they're a gateway to all the high-power R&D shit" is an argument *for* buffing the price to 8k.

**Comment by XDTM** [comment]
Indeed, and the only thing that even requires combat shotguns specifically are x-ray lasers. If you want to go gun-rnd, pay the price.

**Comment by ExcessiveUseOfCobblestone** [comment]
Wait people unironically need more minerals after first run? It's not hard to poop out tons of weaponry after you get T4 parts in your proto lmao.

**Comment by Kromgar** [comment]
I play quite a bit of RND and i'm surprised people are so uppity. They aren't unobtainable at 8k

**Comment by Robustin** [comment]
@Hatfish 

Lets debate that in another PR. Believe it or not there are quite a few numbers between "Plasma Exports worthless" and "Plasma Exports let me buy everything on the cargo menu twice".

**Comment by RandomMarine** [comment]
@Hatfish The station exists to research plasma, not sell it.

I think that's more than justification to cut down the export value.

**Comment by ExcessiveUseOfCobblestone** [comment]
wait why did I downvote this hmmmmmmmmmmm

**Pull request merged**
