### PR TITLE
Make triple citrus recipe make sense

### PR DESCRIPTION
**Pull request by SingingSpock**
## About The Pull Request

Triple citrus now takes 3u of ingredients and gives 3u of product, not 5u

## Why It's Good For The Game

Triple citrus is genuinely frustrating to work with as a barkeep since it makes more than it reasonably should. Why does 3u of juices become 5u when mixed? This makes things make sense, and makes it easier to mix drinks that include triple citrus as an ingredient.

## Changelog

:cl:
fix: Changed triple citrus recipe to make 3u instead of 5u
/:cl:

### CODE REVIEW

**Comment by SingingSpock** [comment]
I don't know what to tag this as 🤷

**Comment by JohnFulpWillard** [comment]
looks like its just inconsistent, so I'd consider it a fix.

**Comment by SingingSpock** [comment]
how... is the Kilostation test failing? I have no clue.

**Comment by Jolly-66** [comment]
> how... is the Kilostation test failing? I have no clue.

CI isn't fool proof and has the tendency to fail on, from what I can gather, hard deletes more times than not.
So long it isn't more than majority, you should be fine and shouldn't have to worry too much, unless maints scream at you.
Then when you run.

**Comment by Son-of-Space** [comment]
While you're at it can you make lemon-lime a valid ingredient for the recipe?

**Comment by SingingSpock** [comment]
> While you're at it can you make lemon-lime a valid ingredient for the recipe? i.e. 1 part orange 2 parts lemon-lime = 3 triple citrus

Lemon-lime isn't a mixture of lemon juice and lime juice (hence why you can't make it by mixing them), it's lemon-lime soft drink, e.g. Sprite. So no, that wouldn't make sense.

**Pull request merged**
