### PR TITLE
Gives syndicate combat borgs wire EMP protection

### PR DESCRIPTION
**Pull request by ghost**
Alternative to #38091 

:cl: CosmicScientist
balance: Syndiborgs no longer get their wires pulsed by EMPs
/:cl:

@optimumtact 
>As far as I am concerned borgs shouldn't be in combat unless they're syndicate borgs, so it's 👎 from me

This just gives a different option ~~to make life difficult~~. I assume I did removal of the component right for the edge case where a syndiborg is turned into anything but itself.

I assume this doesn't cover syndi mediborgs from looking at the code, which if I'm right means those are on the normal silicon faction so AI turrets don't shoot them?

This is less I want this instead but more I want to give the option so no-one has to decide between all or nothing (hooray, the third flavour of ice cream after virologist vanilla & centcom chocolate; syndicate strawberry!) since it's not a hard to code change.

### CODE REVIEW

**Comment by Shadowflame909** [comment]
I can dig it.

**Comment by ExcessiveUseOfCobblestone** [comment]
This will NOT affect syndicate medborgs, you're correct.

As for the AI question, yes the turrets won't shoot bad mediborgs.

It's an oversight because I thought it was a subtype of syndicate but i'm going to pretend it's intended!

**Comment by CosmicScientist** [comment]
I'll see if I can fix that in another PR.

**Comment by CosmicScientist** [comment]
Oh god, so many options.

**Comment by Togopalis** [comment]
Good compromise

**Comment by kevinz000** [comment]
I don't see how making syndicate cyborgs more resistant than normal cyborgs is fixing the problem.

**Comment by optimumtact** [comment]
it's not an issue but this is

**Pull request closed without merging**
