### PR TITLE
Fixes overzealous bomb defusals

### LINKED ISSUE #44078: Training Bomb is Buggy
Round ID: 108921

bomb

just randomly walked up, no one was touching it, it kept going and going

caused by: #43996 im sure

### PR DESCRIPTION
**Pull request by Incoming5643**
fixes #44078

In the few years I was mostly inactive I had forgotten that for machines like the syndicate bomb toggle between fastprocess and process, and not fastprocess and not processing. My bad.

Might want to rush a little on this one because right now every bomb is being defused every process tick.

### CODE REVIEW

**Comment by AnturK** [comment]
This is some nonsense, machines don't switch between these two.

**Comment by Incoming5643** [comment]
It seems like when someone implemented SSfastprocess for these bombs they forgot to do that.

**Comment by AnturK** [comment]
Yeah that sounds like same issue, it's processing on both while it's supposed to only do fast one.

**Comment by Incoming5643** [comment]
So as it turns out the bomb was double processed, but due to some safeguard elsewhere it wasn't actually double timed, so it still takes the approx. 90 seconds to explode that it should take.

**Pull request merged**
