### PR TITLE
multiz movement refactor redux

### LINKED ISSUE #47376: Descending to a lower z-level and dragging something breaks grab.
Imagine, not testing the both ways. Honk

### LINKED ISSUE #49686: Can't push dead borgs down stairs
## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49579: '[READY]Return of the dwarves Mk.2 : Oranges approved - ashlizards removed ' by EdgeLordExe at commit 1d517bd8b5
#49476: 'Adds tackling (VIDEO INSIDE)' by Ryll-Ryll at commit 32fad5b299

## Reproduction:
If a borg dies on an upper level, you can't push them down the stairs and seem to have to shove them over the side of a ledge. Players inform me that borgs can't push other borgs at all, and I'm not sure if you can do the ctrl+click thing to move them off a ledge, so it's extra problematic for them

### LINKED ISSUE #49968: Can't fireman carry someone upstairs
Issue reported from  Round ID: [132255](https://scrubby.melonmesa.com/round/132255) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

You leave them at the top of the stairs, but the offhand symbol remains in your hand slot until you drop it.

### LINKED ISSUE #50739: magboots work like a jetpack in multi z
## Reproduction:

1. spawn on multi z donut or other multi z stations
2. go to second floor
3. space yourself
4. turn on magboots
5. wow now you walk on open space like regular floor
also im disappointed magboots dont make you plummet into the first floor :(

### LINKED ISSUE #53713: Ice-Botany is not wheelchair accessible
## Round ID:
Any round after the updated botany on Icebox

## Reproduction:
Not entirely sure if this would be a "bug", but more so an oversight. The new Ice-botany doesn't allow those in wheelchairs to access the bottom level, without painfully having to hurl themselves down the stairs, or having the engineers wire up a quantumpad. 
Honestly, this may not even be a super big issue considering how little others play with the paraplegic trait, at least, seriously, that is.

### LINKED ISSUE #56563: Open Space is not treated as Space.
## Reproduction:

Tramstation revealed that Open Space turfs are not treated as Space. A group of Engiborgs was able to walk across them as if they were any other corporeal turf (without ion thrusters) like they were ordinary plating turfs, as well as Z-move up and down through the IC tab's movement verbs.

[Edit]
I could walk across with magboots.

It also overly excites atmos.

### LINKED ISSUE #57711: You can't drag people "up" or "down" in space
## Reproduction:

If you've got a body on a lower z level of space, and you're using a jetpack to go "up" or "down", you can't drag the body upwards in any way.

### LINKED ISSUE #59319: Camera Eyes fall through open space
## Reproduction:
use xenobiology console on tramstation or icebox
move camera over open space
camera will fall in
attempting to move up floors will instantly cause it to fall down again

this issue also applies for abductor consoles, though i'm unsure if it applies to AI as well.

### LINKED ISSUE #61708: You can spacewalk on tram upper z level with nothing below you using mag boots
Reporting client version: 514.1561

## Round ID:
[170256](https://scrubby.melonmesa.com/round/170256)

## Testmerges:
- [species changes part 1: lizards](https://www.github.com/tgstation/tgstation/pull/61440)
- [Festival Sect, a revival of an unfinished Music-based sect by cobby](https://www.github.com/tgstation/tgstation/pull/61629)

## Reproduction:
what it says on da tin, player had nothing below them yet when their magboots were enabled could walk around. When they were off could not. 
image

### LINKED ISSUE #62274: Dropping monkeys with xenobio console drops non-existent body parts of people
## Reproduction: 
as shown in [this video](https://i.imgur.com/alSCeZu.mp4): pressing the "feed slimes" button causes the game to display that body parts are falling through open space. 

(Note that the camera appears to be malfunctioning in the video, I'm not sure if that is also connected to this.)

### LINKED ISSUE #62980: Roller Beds are immune to falling
Reporting client version: 514.1567

## Round ID:
[173394](https://scrubby.melonmesa.com/round/173394)

## Testmerges:
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)
- [[DNM] Log zero pickweights, fix current consumers](https://www.github.com/tgstation/tgstation/pull/62940)
- [Fixing parallax plane above blackness ](https://www.github.com/tgstation/tgstation/pull/62902)
- [Revert "Fixes emptied shot glasses having the drinking glass filling icon."](https://www.github.com/tgstation/tgstation/pull/62975)
(Though I highly doubt it was caused by any of these testmerges)

## Reproduction:
- Go next to a chasm that leads to a z-level below;
- Get a roller bed and buckle something to it;
- Try to push the roller bed off the chasm;
- Roller bed goes BRRRRRRRR

image

https://user-images.githubusercontent.com/42555530/142748498-f9ed34ec-d7b8-43d7-9055-ede1d54efb2f.mp4

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This is a remake of an older PR that I had left go stale as I focused on irl matters. #57793
This is more or less the same but with the silly falling conga lines feature removed (I found it quite messy and difficult to maintain, also too hacky) and some of the remaining code improved. It's not too pretty but it's about as standardized as it can get. I have also done some documentation but it's probably filled with typos and a bit dry.

Basically, this is a refactor multiz movement that also fixes some issues around it. Originally made because of my contempt against TramStation, it took me an awful lot of trial and error to get things right due to movement code being nightmarish.
Tested and working. My objective here is simplify multiz movement and definitely make it more robust and less irksome for players.

## Why It's Good For The Game
Will fix #49968, fix #47376, fix #57711, fix #53713, fix #62274, fix #59319, fix #61708, fix #62980, fix #50739, fix #56563, fix #49686 (and possibly even more issues with multi z movement) while improving the code a bit.

## Changelog

:cl:
refactor: Refactored and standardized multiz movement code. This should fix some issues about it.
qol: You can now drag movables, ride vehicles and fireman carry mobs upstairs and downstairs.
/:cl:

### CODE REVIEW

**Review by Kylerace — CHANGES_REQUESTED** [review]

**Comment by Kylerace** [comment]
>resolving my reviews when theyre not resolved at all

**Comment by Ghommie** [comment]
@Kylerace I'm waiting.

**Comment by MrMelbert** [comment]
Testmerge issue noticed: If you're dragging something and you climb a ladder, it no longer follows you up or down the ladder.

**Comment by Ghommie** [comment]
Thanks. I'll fix that soon.

**Comment by timothymtorres** [comment]
Please include that this fixes #50739 and #56563 since these are basically a dupe of #61708

With that said, I do think that mobs shouldn't fall through multi-z if there is no gravity. (if grav gen is damaged OR if they are off the station)  You cannot fall without gravity present.

**Comment by Ghommie** [comment]
> With that said, I do think that mobs shouldn't fall through multi-z if there is no gravity. (if grav gen is damaged OR if they are off the station) You cannot fall without gravity present.

Wait, are you saying mobs are falling down even in zero g right now?

**Comment by timothymtorres** [comment]
> Wait, are you saying mobs are falling down even in zero g right now? I hope not.

Nevermind, there was some confusion with one of those issues.  I thought people were complaining that mobs weren't falling in zero g but they were talking about magboots.  

Also does this solve #49686?

**Comment by Ghommie** [comment]
I don't exactly remember if dead borgs can be pushed at all, but going downstairs doesn't break grabs anymore so it shouldn't be a multi-z issue, so yes.

**Pull request merged**
