### PR TITLE
MMI-in-mecha can use the mecha tools again

### LINKED ISSUE #24422: MMIs can't use ripley tools when theyre placed inside the mech.
Server revision compiled on: 2017-02-24
a50fd64440c3a0a178bd95fd1c694d182fbc2508 

MMIs can't use ripley tools when theyre placed inside the mech. I replicated it with the person who initially had the issue and then PKP and I replicated it in thunderdome. It's definitely not working.

### LINKED ISSUE #28268: MMI's dont work in mechs
Server revision compiled on:  2017-06-08 

6f5157 

When you put an mmi in a mech its able to move it but not able to use any equipment or other functions of the mech.  Its only able to walk.  Multiple people have experience this bug and I will link a forum thread regarding it towards the bottom.

https://tgstation13.org/phpBB/viewtopic.php?f=2&t=11564

### PR DESCRIPTION
**Pull request by octareenroon91**
Fixes  #28268
Fixes  #24422

:cl:
fix: Mecha tools now respond to MMI control signals as intended.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
You're a hero

**Comment by InsaneHyena** [comment]
EVEN IN DEATH, I STILL SERVE

**Comment by octareenroon91** [comment]
Credit to @GunHog for finding the cause of this bug.

**Comment by GunHog** [comment]
It may work better if you make a child of the this proc in the brain-mob, call and handle the parent first, then check if the MMI object's `mecha` var is set. If the var is set, then you can forward the click that way.

The way you have this now, _every_ mob's click is checked for an MMI object, when you need only do this for brain-mobs. 

_Disclaimer: I am not a maintainer. My suggestions may not reflect optimal /tg/ and/or OOP coding standards. Use me at your own risk._

**Comment by octareenroon91** [comment]
That would make at least as much sense, now that you mention it.

I'll open a competing PR if requested since that change would touch entirely different files.

**Comment by GunHog** [comment]
There is no need for that, just change the other file and revert the changes to the first.

**Comment by Nilons** [comment]
Just goes to show if you whine at a coder long enough he'll fix your stupid meme bug, thanks gunhog

**Pull request merged**
