### PR TITLE
Switches organ activation on legion regenerative core from HEAL_ALL to HEAL_DAMAGE

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
## About The Pull Request

What it says on the title. Implanted legion cores will instead HEAL_DAMAGE instead of a sudo aheal. 

## Why It's Good For The Game

Feel free to place your input on this.

Legion cores are obviously extremely easy of an item to obtain, and the ability to organ implant them is equally as easy provided you find someone whose willing to do the very basic surgery required. While inherently I don't find this entirely a bad thing, I'm in the opinion that practically free, easy to obtain, second chance aheals with no downsides should have a bit more requirement than what essentially is running north for a minute on lavaland and killing one of the easiest to kill fauna. I feel there's a little bit of an inconsistancy, especially when other aheal sources that are much harder to obtain (Godslayer Armor) turn you into a shadow if triggered and xenobiology obviously requires cross-breeding. I'm not going to remove or severely punish all aheal sources in the game.

Would this effect you, fighting a megafauna, getting your second chance? Not really. Nothing on lavaland inflicts wounds, blood loss, and other negative afflictions that would otherwise give you, the crewmember, the war of attrition where wounds do matter in a fight. I may be corrected, but I feel there is a direction of mining to slowly ensure that there's a few mechanical barriers to using some of the best healing in the game on station. Granted, this is still an extremely powerful item. I just aim to tone it down slightly onboard the station. ``HEAL_ALL`` heals everything, afterall. Whether it be organs, traumas, and limbs. The only thing going for it is that it requires someone to be alive to activate ``HEAL_ALL``

I don't think this item needs to some sort soft lock to it, but there will be a very negligable diffrence on lavaland, fighting fauna normally while making things like wounds and blood loss require a bit more

## Changelog

:cl:
balance: Implanted legion cores only heal damage instead of being a psuedo aheal. 
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Makes sense to me, ideally Legion Cores should primarily heal... damage you get on Lavaland.
Which generally speaking doesn't inflict wounds, damage organs, or cause brain trauma.

**Comment by StrangeWeirdKitten** [comment]
> Makes sense to me, ideally Legion Cores should primarily heal... damage you get on Lavaland. Which generally speaking doesn't inflict wounds, damage organs, or cause brain trauma.

Miners who roll in dead only need a heart and a brain to be revived. If they have a legion core on them, I as a skilled and robust medical doctor can use their core, defib, and watch them immedietly pop up brand new

**Comment by Jacquerel** [comment]
> > Makes sense to me, ideally Legion Cores should primarily heal... damage you get on Lavaland. Which generally speaking doesn't inflict wounds, damage organs, or cause brain trauma.
> 
> Miners who roll in dead only need a heart and a brain to be revived. If they have a legion core on them, I as a skilled and robust medical doctor can implant their core, defib, and watch them immedietly pop up brand new

If they didn't have the legion core pre-implanted that's their problem.

**Comment by necromanceranne** [comment]
Actually, you can get wounds on lavaland and icebox. Bears cause lacerations, fires in general cause burns and brimdemons can sometimes even cause third degree burns.

**Comment by StrangeWeirdKitten** [comment]
> Actually, you can get wounds on lavaland and icebox. Bears cause lacerations, fires in general cause burns and brimdemons can sometimes even cause third degree burns. The former two aren't very common, but brimdemons are real fuckers because of the burns and particularly since vents started spewing out brimdemons in twos and threes.

Burns in this game are really non-urgent, but there's still a wide option of healing to solve these all still. These didn't much come to my mind since I've personally never suffered from wounds on lavaland versus raw damage numbers. I don't think this changes much, if anything, to justify keeping the ability to heal them.

**Comment by Jacquerel** [comment]
Bears and Brimdemons causing wounds is probably an oversight I'd personally be fine with someone rectifying if they wanted to, but I stand corrected.
I care somewhat less about lava/fire giving you burns because if you caught fire it reasonably likely means you should probably go back to the station to take a break anyway.

**Comment by Deadgebert** [comment]
it's interdepartmental cooperation and is one of the only ways to reliably cure permanent traumas.
you can only have one implanted at a time, you need another person to add it. I think the power on it is fine

**Comment by KateAnbolho** [comment]
> Burns in this game are really non-urgent, but there's still a wide option of healing to solve these all still. These didn't much come to my mind since I've personally never suffered from wounds on lavaland versus raw damage numbers. I don't think this changes much, if anything, to justify keeping the ability to have a pseudo on demand aheal

Hey heads up, burns *aren't* non-urgent. T2 and above deal burn damage, and t3 will lock up limbs. You arguably need cores to unfuck yourself if you goof it with lava, or even with fighting a brimdemon. Along with the whole laceration issue found on icebox.

**Comment by StrangeWeirdKitten** [comment]
The bear's lacerations, wearing the standard explorer suit, is extremely negligable wound wise. Mostly due to armor, it only rarely happens and I doubt you'll die from the bloodloss. I am only capable of getting a rough (moderate) abrasion with no armor. 

Brimdemons don't give you T3 burns, and I you have leeway when it comes to neglecting a moderate T2 burn. While the chance to be burnt by brimdemons is higher, you basically need to be inside the beam the full time. You're basically dead at this point unless you have some healing. It's the burn itself that will kill you, not the wounds. But this could also be fixed, the brimdemons at a higher priority, but if you standing beams of three, you're most likely dead anyway. As a miner, I would never pop a legion core over a T2 burn personally

**Comment by JohnFulpWillard** [comment]
I know legion cores are quite strong but it is also one of the only things from lavaland that requires a second player to implant into you for it to have effects (on top of being one time use each time), which to me makes balance irrelevant to the item. I say let them keep it and survive their penthrite heart attacks.

**Comment by StrangeWeirdKitten** [comment]
> I know legion cores are quite strong but it is also one of the only things from lavaland that requires a second player to implant into you for it to have effects (on top of being one time use each time), which to me makes balance irrelevant to the item. I say let them keep it and survive their penthrite heart attacks.

I don't think a cooperative aspect, while making the strength of certain things much more tolorable, entirely justifies something. Like I said, anyone can implant one whether it be medical or the cargo tech printing surgical tools. It's neither something that extends purely to mining, since lavaland is free and accessable. But an alternative could be to add a communicative aspect to the legion core where you can gain some easy insight that someone will take twice as much punishment. Take genetics and certain implants as an example of mechanics, powers, which are communicated with sprite indicators. An examine text being added, or I can cook up a small overlay in clip studio.

**Comment by Deadgebert** [comment]
> alternative could be to add a communicative aspect to the legion core where you can gain some easy insight that someone will take twice as much punishment. Take genetics and certain implants as an example of mechanics, powers, which are communicated with sprite indicators. An examine text being added, or I can cook up a small overlay in clip studio.

The alternate solution of adding a visible effect is very good. Showing power lets the other players know what they're going to be dealing with and can prepare accordingly

**Comment by GPeckman** [comment]
> Makes sense to me, ideally Legion Cores should primarily heal... damage you get on Lavaland. Which generally speaking doesn't inflict wounds, damage organs, or cause brain trauma.

Brimdemons can cause burn wounds and friendly fire with certain tools (e.g. the resonator) will very often break bones. But it is still less common than on-station wounds.

**Comment by moocowswag** [comment]
Add an examine text similar to stabilized extracts?

**Comment by 2whatever2** [comment]
As someone who has been experimenting with aheal treatments (Nooartium + crossbreeds/legion core implants)
there's a current interaction that may be relevant to this PR

https://streamable.com/8qz7vk

Legion tumors are given in a 75% chance to infested victims, and come from legion corpses, even the skeleton versions.
They are considered an organ and can be stored in a freezer.
When used on a dead mob like showed on this video, it spawns a legion head, then infests the corpse, which heals their damage, and drops a core, letting you use the core for an aheal.
Afterwards, you can remove the tumour if it appears, then repeat the process infinitely if you are lucky, or just have a good stockpile of it.

**Comment by JohnFulpWillard** [comment]
> https://streamable.com/8qz7vk

You play like this???

**Comment by SinfulBliss** [comment]
Don’t think I have ever seen these actually abused in combat, mainly because it would require hacking into mining, stealing a PKA/crusher/mesons etc, going to lavaland, looking for legions, getting a core and then either mining for the stabilization potion or panhandling a miner for one. THEN bringing it back and having someone implant you. No one does all that shit not even the most insane powergamer.

Where I _have_ seen them used though is in medbay to revive the completely gigafucked husked remains of someone that otherwise would never get revived. And as mentioned one of the only ways to heal permanent trauma. Seems good for the game to me.. If all it did was heal damage I think it would remove most of its use in med.

**Comment by Hatterhat** [comment]
> I know legion cores are quite strong but it is also one of the only things from lavaland that requires a second player to implant into you for it to have effects (on top of being one time use each time), which to me makes balance irrelevant to the item. I say let them keep it and survive their penthrite heart attacks. 

seconding this

personal opinion, in PvE i don't think balance matters all too much, esp. if it requires the act of "Interacting With Another Player In A(n Ostensibly) Roleplaying Game" so letting a guy get a full heal off some preparation is fine - i'm pretty sure a legion core burst also clears your bloodstream so you have to pop another luxpen if you're actively trying not to die in the case of a mega fight.

in a PvP context if you manage to burn a guy down once and he pops a legion core, i'd say it's likely that you can just burn him down again; he got a second chance but you can make sure he doesn't get a third (by killing him)

in a medbay context, it gives miners something that they could donate that could be a lot more useful on-station than their luxpens or something (which have a pressure lock making them kinda painful to use)

**Comment by JohnFulpWillard** [comment]
> But an alternative could be to add a communicative aspect to the legion core where you can gain some easy insight that someone will take twice as much punishment. Take genetics and certain implants as an example of mechanics, powers, which are communicated with sprite indicators. An examine text being added, or I can cook up a small overlay in clip studio.

How we have it right now, things that are from Genetics give visuals either for larger hitboxes as "balance" and because it's something one person gets. We have one (1) mutation that would require a second player (or at the very least, telekinesis) and that's fire breath which doesn't have a visual to show it exists unless you consider the fire itself. Compared to implants from Robotics/Medical, nearly nothing is actually visibly shown. Only things I can think of are the augmented limbs themselves and eyes. We don't really have any set standard but generally it's fine for things to be unbalanced if it requires a second player, and for the case of legion cores it's also limited to being something you have to get from Lavaland as well, and usually also a stabilizing core. I know mining point balance is all wack now with ArcMining but it will be fixed (eventually... hopefully..) but it's still work we are expecting has to be put in place to get this item, which compared to implants requires you to be re-implanted after every use.

**Comment by StrangeWeirdKitten** [comment]
> Where I _have_ seen them used though is in medbay to revive the completely gigafucked husked remains of someone that otherwise would never get revived. And as mentioned one of the only ways to heal permanent trauma. Seems good for the game to me.. If all it did was heal damage I think it would remove most of its use in med.

You know, this is a good point. These revivals are possibly, if not extremely impossible on a mechanical standpoint and might take upwards to 20 minutes. Like pulling someone whose been sitting in the plasma lake will do this. I'm going to go with option two later

**Comment by 2whatever2** [comment]
> You play like this???

Unfortunately.

**Pull request closed without merging**
