### PR TITLE
Implant with abductor's tools

### PR DESCRIPTION
**Pull request by MrROBUST**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)

:cl:
add: surgical implant with abductor's tools
balance: some implants can require limb augmentation for balance
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
We got some neat tools and power of RnD. Why we can't put it together? Ayys gonna be jealous.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
Say it with me: R&D doesn't need more stuff!~

**Comment by Ratvar** [comment]
Give it to abductor scientist, maybe? Dissect the issecter to have his power. Allow them to pierce clothing.
And...R&D doesn't need more stuff!~

**Comment by bgobandit** [comment]
This stuff actually makes sense for R&D though, you are researching technology

**Comment by Ratvar** [comment]
Makes sense and Makes balance are not the same, the problem is.

**Comment by GuyonBroadway** [comment]
The implant itself sounds fun if only for admins to be able to create a star trek style borg with built in efficient tools and shit.

**Comment by Repukan** [comment]
Powercreep.

RnD already has augmented surgery tools, they don't need the almost automatic speed ones too.

**Comment by XDTM** [comment]
This requires a specific antag to be spawned and beaten to happen, don't pretend that rnd would get this huge power boost with it

**Comment by jughu** [comment]
Unless you get the miner ruin

**Comment by Repukan** [comment]
Miner ruin isn't even that rare so yeah there's a huge chance this would be a high power boost.

**Comment by Anonmare** [comment]
Raise the abductor tech level to 4 to satisfy everyone. That would require actual abductors to appear in order to produce the design since the miner ruin can only take you to level at maximum.

**Comment by Repukan** [comment]
Does RnD *need* this though?

Or is it powercreep for the sake of powercreeping

**Comment by MrROBUST** [comment]
I was thinking it is a cool thing. And it just _fits_ to RnD.
As far as I understand generality it's too powerful for RnD. Any ideas for balansing, or just remove this design?

Is implant ok by itself? What about arm augmentation requirement?

**Comment by Bawhoppen** [comment]
It's more of the principle that R&D is a mess that shouldn't be further inflated than the actual content of this PR.

**Comment by optimumtact** [comment]
I agree with other people, there needs to be a gulag for people who take other roles special gear and put it in RnD

stop it, just stop, if you want to add things to RnD try thinking up a new item for once.

**Comment by optimumtact** [comment]
oh wait, this isn't 24 hours yet my bad

**Comment by MrROBUST** [comment]
OK, let's leave until better times.

**Pull request closed without merging**
