### PR TITLE
Deceased and asleep humanoids now close their eyes (except those with special eyes like Moths)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

image

## Why It's Good For The Game

A little bit of added immersion, mainly.

Also doesn't mess with people faking death (not ling fake death, *deathgasp shenanigans) because you can literally just wear glasses or turn your body over and people can't see your eyes

Also doesn't necessarily *hide* the eyes, so if you examine a dead cultist you'll still see `They have glowing red eyes`.

Also yes fakedeath (ling fake death) counts as deceased so your eyes close

## Changelog

:cl: Melbert
qol: Deceased and asleep humanoids will now close their eyes
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
blinking animation????????????

**Comment by TheSmallBlue** [comment]
I feel that it'd be neat if corpses kept their eyes open while sleeping people didn't, as a way to tell at a glance whether someone is dead or not (and it'll make deathgasping more believable)

**Comment by carlarctg** [comment]
being sleeping should close but being unconscious not necessarily - its your brain temporarily being knocked out of processing, it's not willing

eyes dont close when ur ded cuz muscles

**Comment by githubuser4141** [comment]
> being sleeping should close but being unconscious not necessarily - its your brain temporarily being knocked out of processing, it's not willing
> 
> eyes dont close when ur ded cuz muscles

Yeah I don't know why this is quality of life, or immersive it's actually the opposite of immersion because it's doing the opposite of what one would expect, if you're killing a dude who closes his eyes you'd probably think he needs a bit more killing if you didn't see this PR.

**Comment by Loafin34** [comment]
can u put this on mobs who are blinded by some object (blind spell, watcher blind, statue blind, welder blind)

**Comment by MrMelbert** [comment]
> Yeah I don't know why this is quality of life, or immersive it's actually the opposite of immersion because it's doing the opposite of what one would expect, if you're killing a dude who closes his eyes you'd probably think he needs a bit more killing if you didn't see this PR.

image

**Comment by Getonus** [comment]
NO WAY SPESSMEN GETTING ANIMATIONS AND SPRITE VARIETY? WE'RE NOT SO FAR FROM WALK ANIM

**Comment by nikothedude** [comment]
> it would be badass if dying DIDNT close the eyes so you could do the whole
> 
> *me swears revenge as i pass my hands over my buddy's eyes, marking their death

of course that would require ethe ability to close someones eyes if theyre dead

**Comment by MrMelbert** [comment]
i've thought at lengths about doing that trope in some form but ultimately my feelings on it are "feel free to do it yourself (if this is merged)"

**Comment by ninjanomnom** [comment]
It is a bit strange that every dead person has their eyes closed. Ideally it would be something like slower deaths causing your eyes to close, and fast deaths you die before closing your eyes.

**Comment by MrMelbert** [comment]
i miss the tweak tag

**Comment by Ghommie** [comment]
Good idea behind the PR, however eyes actually open up upon death because of muscle relaxation, usually and in a half-lidded way. Not an argument for realism, but media plays so many stupid tropes around death.

**Comment by MrMelbert** [comment]
unfortunately there's not enough pixels to do half open

**Comment by Ghommie** [comment]
> unfortunately there's not enough pixels to do half open

Then just keep them open. :P
 Bonus points if you add the possibility of closing their eyes post-mortem, though it would be a pretty useless feature.

**Comment by MrMelbert** [comment]
feel free to close it then, I just don't think it looks as good going open-close-open 🤷‍♂️

**Comment by Ghommie** [comment]
As you wish.

**Comment by DrDiasyl** [comment]
Realism is a bad argument to use when it goes against the design.

This PR is designed to make it more clear if the person is dead/unconscious, and for this they get their _eyes closed_. By making dead still have their eyes open it will go against the design made by Melbert, making this PR half-useless.

**Comment by Ghommie** [comment]
> Realism is a bad argument.

This wasn't really an argument for realism but a small complain. I'm not actually blocking or closing  this PR for real, I'm not seeking to have an argument against a concept I agree with, even though I'm slightly conflicted over it in this case. Let's all get over it.

**Comment by ninjanomnom** [comment]
Why did you change the labels back and forth while merging?

**Comment by Time-Green** [comment]
> Why did you change the labels back and forth while merging?

I don’t think visual improvements/immersion like this deserve the full gbp slap

**Pull request merged**
