### PR TITLE
Replaces Hearty Punch's sprite

### PR DESCRIPTION
**Pull request by ghost**
:cl: Lexorion
imageadd: Hearty Punch has a new, fancier sprite.
/:cl:

### Credit goes to @Lexorion for the sprite.

Old:

New:

### CODE REVIEW

**Comment by RemieRichards** [comment]
Lighting is coming from the topright, it should come from the topleft.

**Comment by Xhuis** [comment]
I'm not super concerned about which direction it's coming from (it was the top right in the inspiration image) so I really don't care too much about making it come from the left.

**Comment by PraiseRatvar** [comment]
you can just flip it and make remie feel happy

**Comment by Xhuis** [comment]
I did.

**Comment by PraiseRatvar** [comment]
HNNNNNNNGH

**Comment by Xhuis** [comment]
@RemieRichards Why the downthumb? It comes from the left now.

**Review by Cyberboss — APPROVED** [review]

**Comment by Xhuis** [comment]
@Lexorion has graciously provided a very high-quality sprite to replace the existing one. I've updated the PR to use that one instead.

**Comment by CosmicScientist** [comment]
Teensy question. We use black outline sprites?
_Nit picking intensifies_

**Comment by Xhuis** [comment]
There's not really a standard for outlines other than "it's gotta be dark" so I'm not concerned about it.

**Pull request merged**
