### PR TITLE
[READY]syriniver nerfix /  syringe projectile fix + various fixes requested by maintainer

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR makes syringe projectiles call the trans_to proj in the correct way.

Because syriniver is the only chem left in the game that has an on_transfer effect on injection after the removal of charcoal, this is effectively a nerf to the lethality of the syriniver / syringe gun strategy.

With this change in effect, a syriniver syringe or dart shot at someone will partially convert the syriniver into musiver, depending on liver health.

This means the target won't overdose from a single syringe, unless they have already sustained substantial liver damage.

Shotgun darts will still overdose the target however, if filled with enough of the reagent.

This is an oversight on my part from when i first added these types of reagents and i have been too lazy to correct.

## Why It's Good For The Game
The primary reason is because the syriniver syringe-gun strategy has gone from a seldom used and obscure to extremely popular.

This does not sit well with me because it is not how i intended for this reagent to work and its overdose effect is too powerful (intermittant vomiting + lethal organ damage) for a reagent that is found prepackaged in a syringe at round start.

## Changelog
:cl:
fix: Syringe & dart projectiles now handle reagent transfer effects as intended.
fix: Also fixes reagent transfers from various other sources such as sleepy pens, cryo tubes and drink bottles.
balance: As a result of the fix; Standard sized syriniver filled syringe projectiles no longer overdose the victim in one hit, unless they already have poor liver health.
/:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
I am not sure how easy to read this PR description is but i am happy to explain my reasoning further in the comments.

**Comment by Krysonism** [comment]
This being the anniversary of syriniver being merged(as thializid), is a complete coincidence.

**Comment by Nabski89** [comment]
I guess I'll need to find a new strat, but I feel cool for having made this popular.

**Comment by ATH1909** [comment]
Ah, that's what was causing it. Good job finding the cause of this (and fixing it)!

**Review by ShizCalev — CHANGES_REQUESTED** [review]
https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/modules/paperwork/pen.dm#L183-L184

hit this too

**Comment by ShizCalev** [comment]
actually, is there any reason for anything to call expose before trans_to at all if it's handled by trans_to anyway?

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/4809e6ebaa063e50005be79e16fd097b3e74995b/code/modules/surgery/dental_implant.dm#L40-L42

https://github.com/tgstation/tgstation/blob/00b4c14c5675ed2df7ce12830c22156fd1cfd008/code/modules/reagents/reagent_containers/hypospray.dm#L43-L50

https://github.com/tgstation/tgstation/blob/0646f4e21a656700561036c1f41b038db0e47ff7/code/modules/hydroponics/plant_genes.dm#L441-L442

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/modules/food_and_drinks/food/snacks_other.dm#L489-L491

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/modules/food_and_drinks/food/condiment.dm#L95-L96

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/modules/food_and_drinks/drinks/drinks.dm#L50-L51

https://github.com/tgstation/tgstation/blob/ac5674b6a6d83a1f04f32151fdf9a86fe9fbd5e5/code/modules/atmospherics/machinery/components/unary_devices/cryo.dm#L239-L240

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/game/objects/items/tanks/watertank.dm#L413-L414

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/game/objects/items/crayons.dm#L748-L749

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/game/objects/items/crayons.dm#L672-L673

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/game/objects/items/crayons.dm#L428-L429

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/game/objects/items/crayons.dm#L449-L450

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/game/mecha/equipment/tools/medical_tools.dm#L333-L334

https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/game/machinery/Sleeper.dm#L313-L314

other spots with similar usage

**Comment by kriskog** [comment]
@Krysonism are you planning to make the requested changes?

Also, merge conflict

**Comment by Krysonism** [comment]
> 
> 
> @Krysonism are you planning to make the requested changes?
> 
> Also, merge conflict

I might try and do it tonight.

**Comment by Krysonism** [comment]
>other spots with similar usage

resolved

**Pull request merged**
