### PR TITLE
Reduces AB overlay updates

### PR DESCRIPTION
**Pull request by AnturK**
#22492 
Can't test, work etc.

### CODE REVIEW

**Comment by MrPerson** [comment]
To answer your question on IRC, I don't know if appearance equality works

**Comment by MrPerson** [comment]
Addendum: Don't rely on it just yet, it's buggy

**Comment by MrStonedOne** [comment]
if you used a dummy object aligned with the button, and set it's appearance value to the item's appearance, it might be cheaper then adding the overlay.

**Comment by Cyberboss** [comment]
>Fixes #22492

**Comment by AnturK** [comment]
I'll see about adding dummy for these.

**Comment by AnturK** [comment]
I tried the dummy objects a bit but couldn't tell if there's actual improvement for 100 buttons blinking and the code would get bit ugly so i'll wait with that for 511 and visual contents.

**Comment by optimumtact** [comment]
Did you test this?

**Comment by AnturK** [comment]
Yea, the appearance comparison in this case is fine even if it's not perfect since we only care about false positives anyway.

**Pull request merged**
