### PR TITLE
moves misc food to newfood code

### PR DESCRIPTION
**Pull request by ghost**
:cl:
 code: misc food is now using newfood code
/:cl:

i hate doing these

### CODE REVIEW

**Review by stylemistake — DISMISSED** [review]
Revert changes to yarn executable.

**Comment by Qustinnus** [comment]
how is it even changed

**Comment by Qustinnus** [comment]
what the fuck

**Comment by LemonInTheDark** [comment]
Linters fail? I think?

**Comment by Qustinnus** [comment]
re-opening this after november.

**Comment by Qustinnus** [comment]
i lied

**Comment by LemonInTheDark** [comment]
Soul

**Pull request merged**
