### PR TITLE
Fixes a typo in the blobbernaut spawn text

### PR DESCRIPTION
**Pull request by ghost**
glob.overminds -> overminds

:cl: More Robust Than You
fix: Fixes a typo in the blobbernaut spawn text
/:cl:

### CODE REVIEW

**Comment by Mark9013100** [comment]
GLOB

**Comment by MoreRobustThanYou** [comment]
OH MY GLOB

**Comment by banthebantz** [comment]
rename to glob pls

**Comment by MoreRobustThanYou** [comment]
https://www.youtube.com/watch?v=RNCJIW1lTSU

**Pull request merged**
