### PR TITLE
Get your protein fix here (for monkey meat).

### LINKED ISSUE #60148: monkey meat doesn't have any protein in it
Round ID: [165678](https://scrubby.melonmesa.com/round/165678)
BYOND Version: 514.1556
Server revision compiled on: 
Master commit: 99dc0fe5f6f70e3279c345b000d492b175365b9a
The following pull requests are currently test merged:
#60066: 'fucking SEXTUPLES ALL TURF DECALS to test for if they affect maptick (like what i did before but more)' by Kylerace at commit 3aa910c8d8

step 1 grind monkey meat
step 2 there's no protein in it
step 3 cry in cytology tears

### LINKED ISSUE #60352: Butchering carbons with reagents in their bloodstream doesn't put the reagents in the meat.
I've noticed that whenever you gib any carbon with reagents or chems in their bloodstream or stomach via butchering, the chems are not put into the meat when you butcher that carbon. I'm not sure if this is a bug or if this is intentional, but i think this might be a bug, i put penthrite in the monkey's bloodstream before butchering it. When i butchered the monkey with penthrite in it's system via combat knife, it didn't transfer reagents, but when i put the monkey in the gibber, it transfered the reagents.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Meat steaks now have the material flag to un-link from from material effects, meaning that monkey meat will now have the proper nutrients and reagents it was intended to, primarily that monkey meat will have protein for cytology purposes.

## Why It's Good For The Game

Fixes #60148. 
Apparently does NOT do #60352, as I can now tell..

## Changelog
:cl:
fix: Meat steaks now have protein as expected.
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
This seems like a bad way to go about this but the most obvious alternative is making edible components have a list of sources so...

**Comment by Livrah** [comment]
Gondola meat fix when

**Comment by MrMelbert** [comment]
i wonder if this pr will break the fix from #59855 since it that PR removed `material_no_effects` from meat slabs

**Comment by TemporalOroboros** [comment]
> why the fuck does meat keep breaking?

It's at the intersection of at least three different systems that don't like each other.

**Comment by ArcaneMusic** [comment]
Ah, I see. I'm going to assign "Do not merge" on this for the moment until I can confirm that this doesn't revert the previous fixes. Hopefully there's a solution that won't keep breaking everything else.

**Comment by ArcaneMusic** [comment]
image

**Review by ghost — CHANGES_REQUESTED** [review]
You need to make material_no_effects prevent removal effects and you need to apply this to all food

**Pull request merged**
