### PR TITLE
Commit hash in rev data is now shortened

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by coiax** [comment]
Why?

**Comment by Cyberboss** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1

**Comment by Jordie0608** [comment]
Well ok, but still why? It does the exact same except now when SS13 is still being run in a few trillion years someone will have to come back and fix this causing a mismatch amongst the undecillion commit hashes.

**Comment by Cyberboss** [comment]
It always links to the full commit, this shortens the DISPLAYED commit

**Comment by Jordie0608** [comment]
I know but why Mr Cyberboss why?

Jokes aside yeah w/e, there's not really any reason against this.

**Comment by MrStonedOne** [comment]
268,435,456 commits can fit in 7 hex numbers. at about 1/1000 of that collision stops being statically improbable. so 200k commits. we are at 45k commits, most over 5 years, meaning this change has a lifespan of about 20 years in the worst case, and about 100,000 years in the best case

Thats more lifespan then 99% of the changes made.

**Comment by coiax** [comment]
Except people copy and paste it anyway? So why are we shortening it?

**Comment by MrStonedOne** [comment]
Because it is standard practice to do so.

**Comment by Cyberboss** [comment]
Also pasting shortened commits into GitHub will automatically expand them

**Pull request merged**
