### PR TITLE
Distinguishes law types by colour

### PR DESCRIPTION
**Pull request by Jordie0608**
When laws are shown to an AI or cyborg they are colored depending on their type.
Devil laws are [burnt orange](https://www.colorhexa.com/cc5500)
Zeroth law is [bold red](https://www.colorhexa.com/ff0000)
Ion laws are [cyan](https://www.colorhexa.com/00ffff)
Hacked laws are [blood red](https://www.colorhexa.com/660000)
Standard laws are unchanged
Freeform laws are [purple](https://www.colorhexa.com/990099)

capture

I also added handling for cyborgs inheriting devil laws from AIs, even though it shouldn't happen, because >badmins

For @TribeOfBeavers

### CODE REVIEW

**Comment by AlexTheSysop42** [comment]
Devil laws?

**Comment by GunHog** [comment]
Cyborgs can be devils, I believe.

**Comment by Anonmare** [comment]
I feel the Ratvar law should be brass even though it is Law 0

if only for thematic reasons

**Comment by TribeOfBeavers** [comment]
Awesome, thanks ^_^

**Comment by MMMiracles** [comment]
This kills the meme of stating fake laws.

**Comment by Jordie0608** [comment]
Hacked laws are no longer part of Ion laws and have their own blood red color. The backend for handling of laws is kinda horrid and filled with copypaste; I don't want to refactor that in this PR but it should be done sometime.

**Comment by Dorsisdwarf** [comment]
Are a traitor's hacked laws that they spend like 13 TC on meant to be lower in priority than "YOU MUST EXECUTE THIRTY SYNDICATE CLOWNS"?

**Comment by Anonmare** [comment]
They usually come first after ion laws, outside of admin shenanigans

**Comment by Jordie0608** [comment]
Yes, but I'll switch them.

**Comment by Qustinnus** [comment]
cyan on white is painful for me to look at.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Make ion laws a touch darker for legibility please.

**Pull request merged**
