### PR TITLE
Revert "Energy Guns Overlays"

### PR DESCRIPTION
**Pull request by ChangelingRain**
#10628

This is pretty ugly and it only saved 15 kb.
memes
Top is new, bottom is old.

### CODE REVIEW

**Comment by optimumtact** [comment]
The PR itself contained some useful structural code overhaul changes that should be retained if your problem is with the sprites themself.

**Comment by Anonus** [comment]
I don't actually know how to do that.
Fun fact, the picture is named memes.

**Comment by optimumtact** [comment]
Ah well

:pensive:

**Comment by freerealestate** [comment]
I like that the laser gun is flipped to match the other guns, and think its ammo read-out looks better than it used to (that ugly-ass orange). The captain's laser's charge meter looks better now that's it's segmented too, imo. However, the HoS' gun looked fancier how it was. The regular energy gun is as ugly as ever.

All subjective observations, obviously. It could be put to a vote?

**Comment by optimumtact** [comment]
@WJohn any potential thoughts on these sprites?

**Comment by MrStonedOne** [comment]
Your image is blurry and it sucks.

Please set your screen to 32x32 or 64x64, take the screen with snipping tool for pixel perfect without compression, then save as png with no compression.

**Comment by Anonus** [comment]
The pull that changed the sprites, at minimum, definitely didn't show the new sprites off well enough(showing the dmi doesn't count, no)

**Comment by Cheridan** [comment]
There's virtually no difference between the sprites, you are crazy

**Comment by Aranclanos** [comment]
go liberate france joan

**Comment by SconesC** [comment]
The only change here that was good was the laser direction 

The new charge meters look universally bad

**Comment by WJohn** [comment]
I don't mind these. I'll have to get used to the laser gun's new direction but it being more consistent is nice.

**Comment by Jordie0608** [comment]
A feedback thread was made here https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4220; feel free to gather more opinons via votes if you're able, I'll probably do so myself as well.

If reverted I'll likely be coming back to this with some of the code changes I made and had planned that'll improve handling a bit without affecting the visuals at all.

I'd request that a decision to keep or revert this is made quickly as there are naturally a couple of bugs that I'd prefer to not start fixing if it turns out to be in vain.

**Comment by Jordie0608** [comment]
Here's a better comparison of the guns that had significant sprite changes, all others guns look essentially the same as previous.

Before
capture2

After (The floral's charge bar is bugged, it should be shorter than that)
capture

**Comment by freerealestate** [comment]
I made a strawpoll - the *most scientific* of polling techniques.

http://strawpoll.me/4983907

**Comment by Cheridan** [comment]
>I'd request that a decision to keep or revert this is made quickly as there are naturally a couple of bugs that I'd prefer to not start fixing if it turns out to be in vain.

A full revert shouldn't be done, the overlays/code are a great improvement and don't need to get wiped out because of sprite nitpicking. The sprites can get changed later. (Anonus was told this but claimed not to know how to edit sprites, so instead tried to do a full revert.) I'll go ahead and close this.

@freerealestate Eguns are 100% the same, so your poll's a bit skewed.

**Pull request closed without merging**
