### PR TITLE
Adds a new AI Core Sprite

### PR DESCRIPTION
**Pull request by TheWiznard**
:cl: Adds an AI Core Sprite
imageadd: Added an AI Core Sprite
/:cl:

[why]: Sprited by me forever ago and figured might as well try, probably not good enough or whatever but here goes. 
-- Also like second pr ever hope this works can't look at guides the wiki is down. Great time to make a pr I guess.
ai-gondla_128

### CODE REVIEW

**Comment by Militaires** [comment]
very cool and good whoever denied this last time needs to posterize themselves

**Comment by TheWiznard** [comment]
> very cool and good whoever denied this last time needs to posterize themselves
there was no lawste time this is like xsonbe pr evr done besizesds pr about txt ai chaines changes

**Review by Cyberboss — APPROVED** [review]

**Comment by Militaires** [comment]
really but i saw this sprite before

**Comment by davethwave** [comment]
Nice sprite

**Comment by TheDreamweaver** [comment]
Speed merge

**Comment by zombiegums** [comment]
Based.

**Pull request merged**
