### PR TITLE
Expands our worst rule

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Don't need 300 moth/lizard language/fire resistance/eye weakness/scream/wings/no wings PRs a month either, same people get attracted to use as a proxy for the same insane drama

### CODE REVIEW

**Comment by yorii** [comment]
Quick, add a revert PR for the moth language removal before this gets merged.

**Comment by Iamgoofball** [comment]
can you just let me make all races 100% cosmetic instead

**Comment by praisenarsie** [comment]
@KorPhaeron will my pr be reverted y/n

**Comment by DaedalusGame** [comment]
rules don't apply retroactively

**Comment by KorPhaeron** [comment]
>rules don't apply retroactively

**Comment by ChangelingRain** [comment]
except when they do, but we don't have any of those yet!

**Comment by KorPhaeron** [comment]
rules apply when we want them to*

**Comment by ExcessiveUseOfCobblestone** [comment]
we need a special rank that is the equivalent to contributor but if the "race discussion" label is added they're unable to comment on the PR.

**Comment by Shadowlight213** [comment]
Going to be a pain, since at least for me, most of my coding is done when inspiration hits me.
By the time I wait for approval, I probably won't feel like coding anymore.

**Comment by optimumtact** [comment]
@Shadowlight213 code it ahead of time, that's the same as what happened already
\>you code it
\>it might get in

now there's just an extra step where you have to ask first

**Pull request merged**
