### PR TITLE
Spacepods!

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
add: Spacepods have been added, which can be built via a spacepod fabricator. Spacepods can be equipped with many things, including lasers, disablers, kinetic accelerators, and plasma cutters!
/:cl:

see https://nanotrasen.se/wiki/index.php/Space_Pods for how they work

yooray

**Podbays mapped in**
All podbays have a pod fabricator, the materials to build a basic pod, tools, a spacepod tracking computer, and an research server for syncing with RnD. Also, armories now have two pieces of security spacepod armor and two pod lock busters.

## Box podbay
box
## Meta podbay
meta
## Delta podbay
delta

**Credits:**
@GunHog - fixing tgui and being a good beta tester!
@ShizCalev - mapping podbays onto delta
@pubby - mapping podbays onto box and meta
"not dichard but rick" on the Hippie discord for spriting the action buttons
and everyone on #coderbus for helping me do this!

### CODE REVIEW

**Comment by steamp0rt** [comment]
Sorry accidentally did wrong branch  lol

**Comment by ExcessiveUseOfCobblestone** [comment]
MRTY?

**Comment by steamp0rt** [comment]
@ExcessiveUseOfCobblestone ssshhhh i'm trying not to let Orange McOrangeFace ruin my PR. also i just decided to make my username consistent

**Comment by steamp0rt** [comment]
also yes i'm fixing conflicts

**Comment by Tlaltecuhtli** [comment]
:eggplant:

**Comment by Aloraydrel** [comment]
Closed lol

**Comment by steamp0rt** [comment]
I'll reopen this when I bother to fix the conflicts and make it compile.

**Comment by ExcessiveUseOfCobblestone** [comment]
what is that?

Have you heard of a book series called "Warrior Cats"? My sister likes those books but i'm afraid it's a gateway furry series and I figured you'd be the best person to contact about a book regarding cats.

**Comment by steamp0rt** [comment]
@ExcessiveUseOfCobblestone it's an anime. Also, it's not furry. It's about a bunch of stray cats in "clans". It's really good.

**Comment by improvedname** [comment]
@optimumtact

**Comment by KorPhaeron** [comment]
No alt accounts

**Pull request closed without merging**
