### PR TITLE
Removes Rad immunity from Plasmamen

### PR DESCRIPTION
**Pull request by carshalash**
The days of the walking nuclear reactors are gone! With this plasmemes will be able to safely wear a rad suit and do their fusion and such, BUT will not be able to fuck with the crew with it

## Why It's Good For The Game

Moving chernobyl isn't fun and won't be missed

## Changelog
:cl:
add: Adds ran immunity to plasmamen helmets!
del: Removes their rad_immune trait
balance: Balances a very annoying race
/:cl:

### CODE REVIEW

**Comment by pireamaineach** [comment]
This exact same PR has been disapproved many, many times. 

Rads are no longer very annoying to deal with.

You're dumb.

**Comment by HomocidlePancakes** [comment]
Add tritiummen or PR bad.

**Comment by pireamaineach** [comment]
Also you only added rad immunity to two of the helmets, which would mean unless you spawn as those two roles you're shit out of luck.

**Comment by Spepbuthewranglesgithub** [comment]
ah, now only _one_ spessman can run through the halls, irradiated can of fuck you being dragged behind, giving the entire station a case of the dead, truly, the problem is solved.

**Comment by carshalash** [comment]
> Also you only added rad immunity to two of the helmets, which would mean unless you spawn as those two roles you're shit out of luck.

Don't worry bip! I remembered plasmemes cant be heads.

**Comment by pireamaineach** [comment]
> ah, now only _one_ spessman can run through the halls, irradiated can of fuck you being dragged behind, giving the entire station a case of the dead, truly, the problem is solved.

No longer a massive problem, easily able to be handled with some knowledge of how radiation works.

**Comment by pireamaineach** [comment]
Isn't this just a pathetic rehash of https://github.com/tgstation/tgstation/pull/48671

**Comment by carshalash** [comment]
> Isn't this just a pathetic rehash of #48671

Sure is fam, I made sure to add that mitigation jordie asked for :)

**Comment by pireamaineach** [comment]
Except you really didn't. People've already addressed this issue in far more fair, impartial ways than I think you ever plan do.
When are you just going to move on?

It's hardly even a problem anymore, what's the point?

**Comment by FancyCyclops** [comment]
Oh no, now my equipment can't be contaminated! This is awful, this is terrible!

Why even play plasmaman anymore?

**Comment by TheVekter** [comment]
ided

**Comment by TetraK1** [comment]
Reminder that even borgs take rad damage.

**Comment by tmtmtl30** [comment]
regardless of how i feel about this, making the same PR repeatedly until it gets accepted without changing much significant leaves a sour taste in my mouth.

**Comment by carshalash** [comment]
> regardless of how i feel about this, making the same PR repeatedly until it gets accepted without changing much significant leaves a sour taste in my mouth.

First iteration was just shitty trait removal, this updates rad immunity on helmets allowing them to use the radsuit.

**Comment by improvedname** [comment]
Lets turn them into uman -

**Comment by improvedname** [comment]
Human -* because why even have unique species with drawbacks and positives why woulda skeleton fucking take rad damage lol

**Comment by Ghilker** [comment]
oh look another weak attempt to nerf an already weak race! 
please tell me more on how you died in the middle of your work because you forgot to replenish your plasma canister; 
or when the doctors refused to heal you because you are too much of an hassle to fix because of your burning; 
or when you almost died for 2 hit with a welder
you removing this is as much ided as the other, just lower effort. Rads got fixed ages ago, there is no reason to have this now

**Comment by carshalash** [comment]
Ghilker you personally have abused this mechanic and everything else rad related more than anyone else.

**Comment by Ghilker** [comment]
lol what when? i never irradiated the station, only once i tryed to use a glitch on the SM and was banned for that

**Comment by Nistishere** [comment]
big ided energy in this pr

**Comment by trollbreeder** [comment]
Deja vu.
#48671

**Comment by FancyCyclops** [comment]
Just wear protection.

**Comment by pireamaineach** [comment]
Even if, "just wear protection" was at all a logical justification for this, this PR makes it literally impossible to get protection unless you spawn as atmos or engineer. Not that it matters, it's a braindead P.R. anyway.

**Comment by CRITAWAKETS** [comment]
Just give the immunity to all plasmaman helmets (like i did in my earlier rad immunity removal PR) or go the bee route and make envirosuits in vending machines

**Comment by pireamaineach** [comment]
Better route, what if we didn't remove the only notable advantage plasmamen have because of whinging crybabies.

**Comment by FancyCyclops** [comment]
Because it's an issue.

**Comment by pireamaineach** [comment]
It's not though, it's long been nerfed and I never see anyone pull it anymore. God forbid good balancing happens without direct nerfs to a species, that doesn't let you make salt P.R.s.

**Comment by Ghilker** [comment]
Where I the issue? Rad contamination got nerfed and got worked out. Rad damage is nerfed and easy to deal. I haven't see a plasmaman irradiating the station on purpose in a long time

**Comment by FancyCyclops** [comment]
Just wear the protective equipment.

**Comment by 81Denton** [comment]
When you're planning to open a race related PR, please check with maintainers first since these require prior approval.

Regardless, you opened almost exactly the same PR (#48671) less than two months ago, not to mention the prequel #47138. 
Just giving plasmeme helmets rad immunity is lazy and far from `I made sure to add that mitigation jordie asked for :)`

**Comment by carshalash** [comment]
It allows plasma engineers to do their jobs, doesnt it?

**Comment by pireamaineach** [comment]
It doesn't allow plasmamen to do engineer period unless they spawned as that role.

Completely unneccessary nerf.

**Comment by carshalash** [comment]
image
Cringe incarnate

**Comment by FancyCyclops** [comment]
It is not Felinids that are the problem.

Plasmamen are.

**Comment by triplezeta** [comment]
There is no plasmaman metagang. All allegations of a plasmaman metagang are completely false.

**Pull request closed without merging**
