### PR TITLE
emergency welder fits now in wallets

### PR DESCRIPTION
**Pull request by jughu**
Makes emergency welders be able to fit in wallets

:cl:
tweak: Emergency welders fits now in wallets
/:cl:

### CODE REVIEW

**Comment by Firecage** [comment]
I don't actually like this myself.

**Comment by jughu** [comment]
I mean  screwdriver fits and a emergency welder is a tiny object why wouldnt it fit?!

**Comment by Firecage** [comment]
I know that IRL is usually a bad argument. But with small screwdrivers IRL, I know how small they can actually be. But with even small welding tools? They seem a bit to large to fit into a wallet.

**Comment by jughu** [comment]
I know but the mini welding tool says its a tiny item so i assume its big as your idd card or a dropper and the wallet text says that it hold small things and tiny is small

**Comment by ExcessiveUseOfCobblestone** [comment]
is this a new form of shitposting?

**Comment by optimumtact** [comment]
Cheridan doesn't like storage bloat.

**Pull request closed without merging**
