### PR TITLE
Resprites most of Chaplain's  choice beacon outfits

### PR DESCRIPTION
**Pull request by CoffeeDragon16**
## About The Pull Request
image

Resprites much of the Chaplain's suits and helmets. Sprites done by @Mey-Ha-Zah, unfortunately their computer cannot run the tools required to make the PR themself.

## Why It's Good For The Game

They look nice.

## Changelog

:cl: Meyhazah
imageadd: new sprites for the Chaplain's crusader, ancient, profane and follower outfits.
/:cl:

### CODE REVIEW

**Comment by ArcaneDefence** [comment]
The student uniform and mensis cage are painfully vibrant, I'd rather they be more de-saturated/distressed to remain in line with the source material.
Kinda disappointed the leader hoodie lost the crown-like hood too.

**Comment by VladinXXV** [comment]
can we get screenshots just using plain old humans? i appreciate the... diversity... but the etheral glow and moth wings and such make it harder to judge the appearance of the outfits

**Comment by Mey-Ha-Zah** [comment]
To address the concerns about the leader robe, this PR is JUST the base sprites for each suit. No code changes, no additions, just an update.

For the Leader Robe, I plan for the crown to be an option on the suit in a future update, as well as some golden mask styles as well.

Preview: 
image

**Comment by CoffeeDragon16** [comment]
Updated the preview image.

**Comment by VladinXXV** [comment]
Yeah, I'm a fan of these. I'd never wear the leader robes before because I didn't like the crown, and the cross necklace threw me off. I like having more ambiguous religious outfits, it gives a little more freedom to the chaplain. They also just look Sick.

**Comment by Livrah** [comment]
Finally Stone Sentinel resprite, and a good one.
But Scholar set was reference to Bloodborne - Micolash boss, and new bright colours looks wierd.
Screenshot_36

**Review by Twaticus — CHANGES_REQUESTED** [review]
icons/mob/clothing/head
knight_greyscale was fixed in a pr recently, needs updating on your branch

icons/mob/clothing/suit
knight_templar side sprites & knight_ancient back sprite, looks like theyre accidently using some pixels from the old sprite. super minor especially the knight ancient one
eaae


i dont know the student reference very well but it does seem to be way more saturated than its intended to be, the cage especially. though i know meyha is planning to do a follow-up pr to add some stuff so if theyd like to see it in action for a bit to gather feedback and save the tweaking until then, thats fine.

**Pull request merged**
