### PR TITLE
Makes flightsuits far more vulnerable to EMPs

### PR DESCRIPTION
**Pull request by silicons**
keeping in line with the rnd "anything powergamey here will get hard countered by an emp"!

### CODE REVIEW

**Comment by Hatterhat** [comment]
@kevinz000 nice job

**Comment by praisenarsie** [comment]
stop buffing rnd you shitmin

**Comment by DoctoreMad** [comment]
Flightsuit comes form RnD and armory has a ion rifle roundstart.

**Comment by Ratvar** [comment]
Make skeletons, golems and slimes die from EMP when

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
