### PR TITLE
Spill Oxygen / Obtain Atmosphere

### PR DESCRIPTION
**Pull request by octareenroon91**
Give oxygen and nitrogen reaction_obj and reaction_turf functions, which produce their respective gases.

:cl:
rscadd: Spilling oxygen or nitrogen will obtain a release of the corresponding atmospheric gas in the effected tile.
rscadd: Carbon Dioxide has been added as a reagent.  Recipe: 2:1 carbon:oxygen, heated to 777K.
rscadd: Spilling CO2 will produce CO2 gas.
/:cl:

### CODE REVIEW

**Comment by Anonus** [comment]
CANNED ATMOS GRENADES, FOR REFILLING AREAS INSTANTLY AND OR CUCKING THE PLASMAMEN'S PLASMA-FILLED HIDEOUT

**Comment by PKPenguin321** [comment]
lmao this will be fun

**Comment by lordpidey** [comment]
I've looked at the changes, and it's an easy enough manual merge.  Just keep all changes past line 400, and discard all changes before that.

Specifically, it's godblood's addition that's causing the conflict.

**Comment by PKPenguin321** [comment]
can confirm, i did in fact edit other-reagents.dm to add godblood and the PR was just merged, so this would technically conflict (even though all you have to change is the line numbering)

**Comment by Incoming5643** [comment]
strictly speaking since oxygen is a liquid when it comes out of the reagent machine that atmos should be unbelievably cold

**Comment by bgobandit** [comment]
goddamnit I was expecting this to be about carbon dioxide

**Comment by duncathan** [comment]
Is that a reagent yet
It probably should be if this is happening

**Comment by octareenroon91** [comment]
Don't think there's a CO2 reagent.
Not sure what a good recipe would be, since there are lots of realistic possibilities. Also I'd expect chem CO2 to be pretty bad news if ingested, giving the CO2 stun or blood acidosis...

**Comment by duncathan** [comment]
We could be lazy and make it two parts oxygen to one part carbon

**Comment by phil235** [comment]
I'm worried this will be two overpowered when used in smoke and foam. Especially since it spawns air for every turf AND every object on that turf.

**Comment by as334** [comment]
@phil235 How is being able to do that with the non-dangerous gases worse than being able to do that with plasma?

**Comment by phil235** [comment]
@as334 Good point, I just tested liquid plasma smoke grenade and it's pretty OP. With 20u of plasma (one sheet) and 45u of smoke my grenade thrown in front of the kitchen covered the kitchen, the medbay entrance the starboard hallway section from the bar to botany, and half of the bar. Then burning that plasma basically burned the entire area I mentionned. Compare this with burning a plasma sheet with a welding tool which only burns 7 tiles.

Edit: and with 5 sheets of plasma and 90u of smoke I managed to cover arrival+port hallway+restroom+centralhallway in visible purple toxin.

**Comment by Cheridan** [comment]
@Incoming5643 >reagent_state = GAS

it's oxygen gas.
how do you pour it into a soda can, then? idk a wizard did it

**Comment by Jordie0608** [comment]
Obviously oxygen is heavier than air.

**Comment by octareenroon91** [comment]
CO2 recipe soon

**Comment by octareenroon91** [comment]
Carbon Dioxide added.  It has no function other than spawning CO2 gas on contact with turfs/objects.

**Comment by bgobandit** [comment]
what the fuck did you just add

**Comment by octareenroon91** [comment]
A disappointment to chemists.

**Comment by duncathan** [comment]
She's just memeing on you, don't worry

**Pull request merged**
