### PR TITLE
Adjusts medical techweb nodes

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Swaps 'advanced medbay equipment' and 'cryostasis' on the medbay tech tree, adjusting the required experiments and prerequisites as necessary.

## Why It's Good For The Game

Items like health analyzers, pinpointers, defibs and medical beds are lower tech, commonly used items and should come before  advanced cryo technology, not the other way around.

## Changelog

:cl: LT3
balance: Advanced Medbay Equipment research node lowered to tier 3
balance: Advanced Medbay Equipment now requires haloperidol scan experiment
balance: Haloperidol and cryostylane experiments can be performed roundstart
balance: Cryostasis research node raised to tier 4
balance: Cryostasis now has Fusion instead of Controlled Plasma as a prerequisite
balance: Cryostasis cryostylane scan is now a discount experiment
balance: Crystallizer moved from Controlled Plasma to Fusion
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Required experiments shouldn't be at the beginning of a tree and at the end. Please add some other required experiment for tier 3  and turn Cryostylane scan into a full discount experiment.

Nodes should require only the tech from one tear below from the neighbour trees. Please make Cryostasis require Fusion and move the Crystallizer into Fusion.

**Comment by lessthnthree** [comment]
> Thank you for the help with the balance of the tech tree.
> 
> Required experiments shouldn't be for the first and the last nodes in a tree. Please add some other required experiment for tier 3 and turn Cryostylane scan into a full discount experiment.
> 
> I can suggest a chemical scan, like of some advanced medicine(s). Since it's the medbay/chemistry tree.
> 
> Nodes should require only the tech from one tear below from the neighbour trees. Please make Cryostasis require Fusion and move the Crystallizer into Fusion. The idea is that the medbay repurposes the Crystallizers for Cryo pods.

Can do, thanks for the info on how the tree is set up.

**Comment by lessthnthree** [comment]
@MTandi how's that look.

**Comment by GPeckman** [comment]
Well if you added new experiments then you should probably update the changelog to reflect that

**Comment by lessthnthree** [comment]
Yeah I gotta update it with all the changes.

**Comment by MTandi** [comment]
Awesome, thank you!

**Comment by lessthnthree** [comment]
> experiments_to_unlock = list(
> 		/datum/experiment/autopsy/human,
> 		/datum/experiment/autopsy/nonhuman,
> 		/datum/experiment/autopsy/xenomorph,
> 		/datum/experiment/scanning/reagent/haloperidol,
> 		/datum/experiment/scanning/reagent/cryostylane,
> 	)

Ah yes, done!

**Pull request merged**
