### PR TITLE
demos config

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Adds a config value for whether or not the demos SS gets initialized and runs.
Off by default for development purposes.

If this gets merged keyholders need to be notified to fix it.

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
This needs to do more. i.e. prevent objects from getting added to the queues, otherwise they are just going to blow up in size and crash the game.

**Comment by actioninja** [comment]
good point

**Comment by spookydonut** [comment]
see travis:
```
[10:18:52] Runtime in configuration.dm,196: bad index
  proc name: Get (/datum/controller/configuration/proc/Get)
  usr: *no key*/(INTERNAL DVIEW MOB)
  src: Configuration (/datum/controller/configuration)
  call stack:
  Configuration (/datum/controller/configuration): Get(/datum/config_entry/flag/demos... (/datum/config_entry/flag/demos_enabled))
  Demo (/datum/controller/subsystem/demo): mark new(INTERNAL DVIEW MOB (/mob/dview))
  INTERNAL DVIEW MOB (/mob/dview): New(null)
  Global Variables (/datum/controller/global_vars): InitGlobaldview mob()
  Global Variables (/datum/controller/global_vars): Initialize()
  Global Variables (/datum/controller/global_vars): New()
  Master (/datum/controller/master): New()
  world: ()
```

**Comment by Cyberboss** [comment]
It should be using the subsystem variables not the config

**Comment by actioninja** [comment]
Hmm, not as simple as that because the marked lists keep getting filled and consuming memory up until byond restarts due to not having enough memory.
Going to have to thonk on this one a bit, I'll figure something else.

**Pull request merged**
