### PR TITLE
Updating Traumas to the Present Day

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
The trauma string file needed a couple of changes to account for stuff that's changed in the last year or so.

## Why It's Good For The Game
Makes the references in the file more up to date.

## Changelog
:cl:
tweak: modernised the brain damage strings
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
these are all great but unfortunately you have referred to antegs therefore this will get murderized by the antagonist freeze

**Comment by trollbreeder** [comment]
Just want you to know what clock cult has been removed from the code since a looong time.

**Comment by RaveRadbury** [comment]
> Just want you to know what clock cult has been removed from the code since a looong time.

#47057 Clock cult was removed in October.

**Comment by EOBGames** [comment]
> > Just want you to know what clock cult has been removed from the code since a looong time.
> 
> #47057 Clock cult was removed in October.

Yeah, I just added that one because I thought it was funny.

**Review by kriskog — APPROVED** [review]

**Comment by trollbreeder** [comment]
Oh, by the way, while i was experimenting in my personal closed-source downstream, i made a bunch of retard lines specifically for one of my reagents' ODs based on the plasmafire that is the comments on various cobbychems PRs. Have fun cadet!
"REVET COBCHEM!!", "TREK DI NO WRON!!", "GOOF WAS RIGHT", "GOnCHEM FROeVEr!!", ";WHAt the FUCK is rhigosan????", "OMZINE NEF PLES INTERDEPTAL COOPATOn?",  ":m GIB CLOMEL", ":m GIB PENTET ACOD", ":m CEMO PLAS GAVE PAITAN NOORAN", ";CHaRCOL FOR CRISdMAS", "ORANGE MAN BAD", "KOR YOu CUNT", "WI NED TROPHOL"

**Pull request merged**
