### PR TITLE
Make free golem hazardous area numbers configs

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Makes the slowdown, movespeed, etc configs, as well as the ability to toggle this on at all.

It's not something I cared about at first, but I figured later down the line that just because this is in the codebase doesn't make it not a policy issue, so head admins might as well have the knobs for this.

### CODE REVIEW

**Comment by optimumtact** [comment]
insane

**Comment by Mothblocks** [comment]
@optimumtact u didnt let coders touch these without a policy discussion bro :(

**Comment by optimumtact** [comment]
I didn't let them prevent golems coming on statio without headadmin approval, that doesn't mean every single variable needs to be configurable for some insane headadmin in the future who thinks they know better.

**Comment by Mothblocks** [comment]
works for me

**Pull request closed without merging**
