### PR TITLE
Ports oracle's food cart sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #

:cl:
imageadd: New food cart sprites (by Quantum-M)
/:cl:

Stolen from https://github.com/OracleStation/OracleStation/pull/1138

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
i think you touched the palette there

**Comment by nicbn** [comment]
oops

**Comment by WJohn** [comment]
Aww, I'll miss the giant wheel and goofy little parasol. Added some real character to it. Nothing much else to say, these don't really add much other than 3/4th.

**Comment by Iatots** [comment]
parasol is non-negotiable :gun:

**Comment by epochayur** [comment]
I understand the desire to move to 3/4 but these look like shit tbh

**Pull request closed without merging**
