### PR TITLE
Adds the recipe for the felinid mutation toxin

### PR DESCRIPTION
**Pull request by Pandolphina**
## About The Pull Request

The title. I want to die. End me.

## Why It's Good For The Game

It isn't. May god have mercy on our souls.

## Changelog
:cl: Pandolphina
add: Adds a recipe for the felinid mutation toxin. May god have mercy on our souls.
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
Unless you asked for prior approval, this PR violates part of our CONTRIBUTING.md:
>Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

If you received prior approval, please post a comment that includes it. Otherwise, I will be closing this PR at the 24 hour mark.

**Comment by Tlaltecuhtli** [comment]
begone

**Comment by Pandolphina** [comment]
I’m sorry I needed my 3 karma

**Comment by 81Denton** [comment]
h-he's fast!

**Pull request closed without merging**
