### PR TITLE
Validate committed tgui build in Travis

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

Since we use Yarn, we can in theory guarantee that all dependencies are locked, therefore builds are deterministic and will match 100% on Travis.

This PR is also accompanied by a change in `.gitattributes` to use `tgui-merge-bundle` strategy, to automatically throw away your builds when rebasing.

Merge this if you like breaking things.

~~Suggest a good way to autoinstall these dummy merge drivers. Should we just document it in README?~~

Install merge driver by running this once:
```
bin/tgui --install-git-hooks
```

### CODE REVIEW

**Comment by actioninja** [comment]
I haven't looked into git hooks much but is it possible to have a run on clone hook

**Comment by actioninja** [comment]
Looked into it and no, hooks aren't even stored in the repo and you'd need a template for it, which has to be specified at clone time which defeats the whole purpose.

**Comment by SpaceManiac** [comment]
> Suggest a good way to autoinstall these dummy merge drivers. Should we just document it in README?

There is existing infrastructure for this in `tools/hooks`

**Comment by stylemistake** [comment]
> There is existing infrastructure for this in `tools/hooks`

Well, there are some dmi hooks requiring to have python and some packages, but if that's no problem for windows users, I guess we can use that.

> This is incorrect, creating such a driver acts like "ours" rather than like "theirs".

What are you saying? That ours == theirs? They both require this kind of setup in order to work, they are mirrored versions of the same merge driver, and we want "theirs" specifically because that would make it throw away local builds and prefer upstream builds, which is cleaner when developing a PR.

**Comment by SpaceManiac** [comment]
> Well, there are some dmi hooks requiring to have python and some packages, but if that's no problem for windows users, I guess we can use that.

They work in Git for Windows (aka Git Bash), GitKraken, and TortoiseGit, but not GitHub Desktop.

> What are you saying?

I mean that `git config merge.foo.driver true` creates a driver named `foo` which resolves all conflicts by taking the version already in the working tree

**Comment by stylemistake** [comment]
Ok, I have figured out how to write custom merge drivers, and added some infrastructure directly into `bin/tgui` script. I did not touch the existing infrastructure, because it was doing a lot of stuff I didn't want, and I like the way it works with `bin/tgui` because it's completely optional.

How it works:

- You run `bin/tgui --install-git-hooks` once.
- Any time you rebase/merge, conflicts will be resolved by an `tgui-merge-bundle` strategy (which currently works like `ours`).

I left this merge driver open-ended to allow for different behaviour in the future. We can for example run a full rebuild when rebasing.

```bash
## Bundle merge driver
task-merge-bundle() {
  local file_ancestor="${1}"
  local file_current="${2}"
  local file_other="${3}"
  local conflict_marker_size="${4}"
  echo "tgui: Discarding a local tgui build"
  ## Do nothing (file_current will be merged and is what we want to keep).
  exit 0
}
```

I believe we are good for merging this right now. Only time will tell whether the builds are in fact deteministic.

**Comment by SpaceManiac** [comment]
I don't like having two separate infrastructures for git hooks

If you don't like the current one let's talk about it

**Comment by stylemistake** [comment]
Well, if thinking of tgui as a subproject, it makes sense to put related merge tools and hooks into that subproject, keeping it all contained and self-sufficient (gitattributes and the script are all in the same subproject). This will also make it easier for downstream users of tgui-next to inherit this feature.

Reasons why I don't like existing infrastructure:

- Its location and script name implies this is what you want to have installed by default, and I personally don't care about dmimerge and mapdiff when working with UI
- It breaks because I don't have a full Python installation, and I don't want it.
- I could add selective installation of hooks, and reference this tool in tgui README, but that would count as an outside tool, breaking containment of that subproject.
- Make that merge tool generically called "ours" and now it completely loses its context, because so far only tgui will use it and you need to exactly know why you need to install this exact merge tool.
- `"%P"` is super badly placed in that `install.sh` script, because it is sometimes defined, and sometimes it is empty, shifting all arguments by 1, and I have no idea how to fix that without breaking other merge tools. I just genuinely don't want to touch it.

**Comment by SpaceManiac** [comment]
> Well, if thinking of tgui as a subproject, it makes sense to put related merge tools and hooks into that subproject

the extractable subproject angle makes sense, I think I'd be satisfied if tools/hooks/install.sh just ran `tgui-next/bin/tgui --install-git-hooks` at the end

> It breaks because I don't have a full Python installation, and I don't want it.

well I'm not writing a DMM/DMI suite in sed and awk I'm telling you that much

> Make that merge tool generically called "ours" and now it completely loses its context

I have nothing against a well-named merge driver

> "%P" is super badly placed in that install.sh script,

pretty sure this isn't a real problem

**Comment by stylemistake** [comment]
> I think I'd be satisfied if tools/hooks/install.sh just ran tgui-next/bin/tgui --install-git-hooks at the end

Well, I can do that.

**Comment by actioninja** [comment]
Scripts look good, time to pray this works.

**Pull request merged**
