### PR TITLE
Juke Build 0.8.1

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

With this PR, I have decided to move some build, test and lint related tasks to `build.js`.

Here is a full list of targets/parameters, to get a taste of what you can run with this thing:

```
$ tools/build/build --help
:: Juke Build version 0.8.1
:: Available targets:
 - all
 - build
 - clean
 - dist-clean
 - dm-maps-include
 - dm
 - dm-test
 - lint
 - server
 - test
 - tg-font
 - tgs
 - tgui-analyze
 - tgui-dev
 - tgui-eslint
 - tgui-lint
 - tgui
 - tgui-test
 - tgui-tsc
 - yarn
:: Available parameters:
 --ci (type: boolean)
 --define, -D (type: string[])
 --port, -p (type: string)
```

- `server` compiles and hosts the server in one go.
  - `tools/build/build server --port 10050`
- `test` runs DM unit tests.
- `all` runs all of the above in the most efficient manner.

Updated the CI pipeline to reflect this change, removed the python script to generate a list of map includes (because build.js now does it automatically based on provided defines). Added restoring of Yarn cache in CI, which saves about a minute.

A lot of small improvements to Juke, detailed changelog is [here](https://github.com/stylemistake/juke-build/blob/master/CHANGELOG.md).

Changed `.mdme` extension to `.m.dme` because it results in a more organized set of files, i.e. `.m.dme`, `.m.dmb`, `.m.rsc`.

Bumped node version because earlier versions do not support ES modules without extra experimental flags.

**Added THREE new bat files for dummies:**
- `CLEAN.bat` (for fixing random issues)
- `RUN_TESTS.bat` for an offline CI run.
- `RUN_SERVER.bat` for running the server, very simple (default port is 1337).

### CODE REVIEW

**Comment by stylemistake** [comment]
```
:: bash('tools/ci/check_grep.sh')
```
`dm-test` task for some reason dies on this command, and it just never finishes, and somehow the whole thing returns a non-zero exit code. :eyes:

**Comment by stylemistake** [comment]
I will have to convert this to a draft until I find some time to fix this.

**Review by Mothblocks — APPROVED** [review]
Looked over the parts that touched and transferred CI, all looks good.

**Comment by stylemistake** [comment]
Looks like it's ready for merge again.

**Pull request merged**
