### PR TITLE
Unbreaks Tgui for people running < IE11 by reverting dependencies update

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
fix: Fixes TGUI not working for people without IE11
/:cl:

Hopefully I did everything corretly(I have no way of testing if it works for < IE11). The "no frills" version worked fine with this.

### CODE REVIEW

**Comment by lzimann** [comment]
@Mervill

**Comment by MrStonedOne** [comment]
Works on ie8.

**Comment by Mervill** [comment]
Looks like you did everything right! Sorry about putting this off, when you've got a pile of fixes on your TODO list and one of them is "revert your own work" it tends to get left at the bottom.

Next time I have to fix my own mistakes I'll be a bit quicker on the draw, promise

**Comment by Tacolizard** [comment]
soooo would this mabye allow spess thru wine to work again?

**Comment by lzimann** [comment]
It should, yea.

**Comment by Tacolizard** [comment]
@lzimann in that case this should be merged asap. i'm making a wineskin wrapper for BYOND that includes the dx2010 graphics fix and shit. ie is the final barrier to wine byond.

**Comment by Incoming5643** [comment]
Thank you.

**Pull request merged**
