### PR TITLE
Doubled the frequency of Icon Smoothing SS firing.

### PR DESCRIPTION
**Pull request by xxalpha**
Closes https://github.com/tgstation/tgstation/issues/18467

### CODE REVIEW

**Comment by Core0verload** [comment]
This doesn't resolve the problem, and the problem is that `queue_smooth` is a thing.

Well, I don't mind it handling pre-round turf smoothening, but when I play the game, I want my smoothing to be instant. Not two times faster than slow as fuck.

**Comment by xxalpha** [comment]
No.

**Comment by Core0verload** [comment]
Why.

**Comment by Core0verload** [comment]
And isn't MC/SS currently feature ~~stoned~~ frozen?

**Comment by xxalpha** [comment]
I left the procs to smooth the old way, but it uses ``spawn()`` which is the devil.

This is fast enough so that you don't notice it smoothing, unless of course it is under a heavy load, which doesn't happen outside of admin fuckery and map initiation.

**Comment by MrStonedOne** [comment]
Ya, this would conflict with my stonedmc pr, and we are on a SS freeze

also, I already did this in my pr. https://github.com/tgstation/tgstation/pull/17987/files#diff-1be91a201a8e2678c4c01310288f8052R6

**Comment by Core0verload** [comment]
I tested another solution - just made `queue_smooth` fall back to old smoothing if game state = 3 (round in progress). Nothing went wrong so far. What's wrong with doing it that way?

**Comment by xxalpha** [comment]
It was already done, then.

**Comment by Core0verload** [comment]
If lava undergoes smoothing before round start, it wouldn't affect it.

**Comment by MrStonedOne** [comment]
here's the thing, using the queue keeps a turf from smoothing twice if something like an explosion or singulo happens and removes both walls around a turf.

**Comment by Core0verload** [comment]
Does this happen often enough to have noticeable impact on performance? I think (possible) double load on smoothing is worth not having that noticeable delay on wall/mining turf destruction.

I tested the lava. No freezes.

**Comment by MrStonedOne** [comment]
I'll take a look, but its most likely i could just shunt smoothing to a ticker process, running every 2 byond ticks isn't noticeable

**Comment by Core0verload** [comment]
I'll make a PR for instant smooth walls in the meantime.

**Comment by MrStonedOne** [comment]
I'll most likely have stonedmc finished and merged before any pr you make hits 24 hours =P

**Comment by xxalpha** [comment]
@Core0verload the entire reason behind this SS was the propagating lava freezing the game because of the smoothing.

**Comment by Core0verload** [comment]
Good luck with MC then.

**Pull request closed without merging**
