### PR TITLE
maked energy cakehat better :)

### PR DESCRIPTION
**Pull request by imsxz**
## About The Pull Request

Makes energy cakehat have the same damage properties of energy swords.
## Why It's Good For The Game

Energy cakehats are made from energy swords but the damage is halved???? and it cant dismember???? the time has come to do the energy cakehat justice
## Changelog
:cl: imsxz
balance: energy cakehat does more damage and can cut peoples limbs off
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
make it a desword damage and wound instead

**Comment by Sparkezel** [comment]
> make it a desword damage and wound instead

You know that to delimb you gotta use wounds now right?

**Comment by MrDoomBringer** [comment]
imsxz is back

**Comment by D4C-420** [comment]
this is a xenobio buff as they can produce energy cakes from silver slime extracts. they will mass produce esword level melee weapons if this is merged.

**Comment by Paxilmaniac** [comment]
Add the removal of roundstart xenobio to this

**Comment by Serxule** [comment]
> this is a xenobio buff as they can produce energy cakes from silver slime extracts. they will mass produce esword level melee weapons if this is merged.

i don't think I've ever seen xenobio have a energy cake

**Comment by D4C-420** [comment]
> i don't think I've ever seen xenobio have a energy cake

silver extracts can get spawn just about any food or drink from gatfruit, roboburgers, and of course energy cakes. They would be more terrifying if xenobio did not have much worse than what's in the food list.

**Pull request closed without merging**
