### PR TITLE
Intercom examine tells you about :i

### PR DESCRIPTION
**Pull request by JJRcop**
## Why It's Good For The Game
I'm not sure how many people know about this feature, can help out when comms are down if you're inquisitive.

## Changelog
:cl: JJRcop
add: Intercom description tells you about the :i radio key.
/:cl:

### CODE REVIEW

**Comment by Iatots** [comment]
Why the distance requirement? Most things do not work like that, and since the problem is not enough people knowing about it, why gate the info behind a mechanic the great majority of items do not use?

**Comment by JJRcop** [comment]
What do y'all think about the message always being available, but adding "if you get closer." to the end if you're out of range?

**Comment by JJRcop** [comment]
Done that

**Comment by XDTM** [comment]
No need for variable text, just clarify in the description that it only works while adjacent to it; the point is to teach a mechanic. Players aren't going to examine the same thing multiple times expecting different instructions.

**Comment by Anonmare** [comment]
I have a suggestion, Station Bounced Radios can be talked into using :L or :R when you're halding them in the appropiate hand. Would it be possible to see the same done for them?

**Review by Cyberboss — APPROVED** [review]
Bunny is right, but that can be a different PR

**Pull request merged**
