### PR TITLE
New Cryosleeper and Space Suit sprites from Shiptest!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Ports the resprite of the old space suits and cryosleepers!

Credit to: @zestybastard for creating the space suit sprites in PR: [#1024](https://github.com/shiptest-ss13/Shiptest/pull/1024) of Shiptest with modified helmet object sprites to fit our codebase
image

And @SomeAngryMiner for creating the cryopod sprites in PR: [#779](https://github.com/shiptest-ss13/Shiptest/pull/779) of shiptest, of which I modified into sleepers!
image

## Why It's Good For The Game
Better sprites for arguably incredibly old and badly neglected sprites!

## Changelog

:cl: Zestybastard, Azlan and PositiveEntropy
imageadd: Resprites the old space suits!
imageadd: Resprites the sleepers!
del: Removes unused orange and black engi light attachment helmet sprites.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Very sleek. Love 'em.

**Review by Fikou — CHANGES_REQUESTED** [review]
you removed a couple of the helmet sprites with light please fix

**Comment by Fikou** [comment]
can we keep the red visor of the syndie suit 🥺 

also the emergency space suit which is supposed to look shitty will look cool now

**Comment by Imaginos16** [comment]
> you removed a couple of the helmet sprites with light please fix

When I investigated it with @GoldenAlpharex I am almost certain its unused.

I tested it in the thunderdome to make sure and I couldn't attach a light to the specific helmets listed in the PR. I will specify I will be deleting them however, so thank you for pointing it out.

**Comment by SmArtKar** [comment]
> > you removed a couple of the helmet sprites with light please fix
> 
> When I investigated it with @GoldenAlpharex I am almost certain its unused.
> 
> I tested it in the thunderdome to make sure and I couldn't attach a light to the specific helmets listed in the PR. I will specify I will be deleting them however, so thank you for pointing it out.

>attach a light
you know, they are supposed to be inbuilt so try wearing them and check again if they dont have a light

**Pull request merged**
