### PR TITLE
Nerf surgeries speed in stasis(S)

### PR DESCRIPTION
**Pull request by Axidyuwu**
## About The Pull Request
Applies 5X surgery speed while the patient is in stasis.
## Why It's Good For The Game
Stasis beds are no more "perfect" bed for everything.
## Changelog
:cl:
balance: surgeries speed in stasis is nerfed
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
Why do people keep naming duration variables speed? This is so stupid.

**Comment by Sadboysuss** [comment]
Also how do you operate on plasmamen?

**Comment by GPeckman** [comment]
If you want people to use surgery tables more, perhaps you should consider making surgery tables better instead of making the alternatives worse?

**Comment by tramontanao** [comment]
making stasis beds worse doesn't fix any perceived issue you have with their balance. make surgery tables better or just don't touch it. as it is, stasis beds are already limited by only having basic surgeries available unless you're a borg with the surgical processor or you have the modsuit module. if a doctor is trying to be as efficient as possible, they're not going to rely entirely on stasis beds. it's up to personal preference, but if you're sticking with stasis beds the whole time, you're going to have a lower throughput on patients which makes the argument that stasis beds are "perfect" null and void. this is a worthless change and a blight on the honor of the medical community.

**Comment by GuillaumePrata** [comment]
People talking about improving the surgery tables need to remember that powercreep is a thing and we can already revive people stupidly fast.

The issue with stasis, personally at least, is that it has a noble goal of giving new players all the time they need to not be overwhelmed with a corpse, take their time to learn, etc.

But in reality it just centralized everything in medbay around it and took away a lot of the interesting challenges of medbay like plasmamen revival, everyone goes into stasis surgery because why not? The pros are miles ahead of the cons, and that takes away a fun side of the department, which is spinning multiple plates at the same time trying to get everyone fixed.

Now I don't think a flat speed decrease is the proper way to go, stasis should do a "deep scan" of the patient that takes 1 minute, and then give a chunk of information about the patient to help the new doctor.

This way it is a chore for experienced players to need to wait for the deep scan, while new players get even more help from stasis.

**Comment by Formerxboxgamer** [comment]
> > 5x feels like it'd be untenably and needlessly high. Why not make it something like 140% instead of 500% and provide a larger buff to the surgery table's speed boost?
> 
> 140% won't stop doctors from putting you on stasis and doing basic tend wounds, and you can still stack up surgery speed buffs with it like gloves, tools, chems and etc. Kinda experimented with surgery speeds, and with 500% it is still posible to fully heal someone with only basic tools.

This isn’t what stasis surgery is used for by good doctors. Realistically this is going to make revival of plasma people and husked idiots with a body temp of the sun nearly impossible to revive. Yeah doctors who tend on stasis are bad, but this will hurt experienced doctors who know how and when it’s appropriate to tend on stasis

**Comment by SomeoneYouProbablyKnow** [comment]
5x is insane, 3x would be at the edge of reasonable and 2x would make sense but making it 5x without outright removing the option is just creating a weird knowledge check trap for doctors. (Frankly I'd be fine with surgery just not working on a stasised person that way they'd get some feedback at least)

> 140% won't stop doctors from putting you on stasis and doing basic tend wounds, and you can still stack up surgery speed buffs with it like gloves, tools, chems and etc.
Kinda experimented with surgery speeds, and with 500% it is still posible to fully heal someone with only basic tools.

You gotta remember that players arent always making the best decisions, most people arent stacking speed bonuses, most won't even be aware of the change. And the players who care are already using the surgery tables. Think of the patient who came to medbay only for an unware doc to do the longest tends on them cos of the stasis, 2x is annoying but fair, 5x is literal torture.

> If you want people to use surgery tables more, perhaps you should consider making surgery tables better instead of making the alternatives worse?

Power creep is a very real thing, sometimes nerfs are the best choice. You buff everything and you'll end up with penlights ahealing on use, given enough time.

**Comment by SomeoneYouProbablyKnow** [comment]
2x is honestly fine, although i'd much prefer something other than a speed debuff you can miss if you aren't paying attention. Like surgery not starting at all or internal stasis powercells or whatever else with better UX

**Comment by Dawnseer** [comment]
This doesn't really make sense. Stasis just halts all processes, it's not like you become a block of ice or an immovable rod or something stupid like that. The body can still be manipulated. People can use their hands. Why would surgery for some reason go slower? Also can we please stop using the slippery slope for 'power creep'?

**Comment by Exester509** [comment]
Forgot to mention that plasmemes will now take two years to revive

**Comment by zoomachina** [comment]
> Stasis beds are no more "perfect" bed for everything. 
So why is this good for the game?

**Comment by SomeoneYouProbablyKnow** [comment]
> Stasis just halts all processes, it's not like you become a block of ice or an immovable rod or something stupid like that. The body can still be manipulated. People can use their hands. Why would surgery for some reason go slower?

Lore is subservient to gameplay. You can justify most changes since stasis is sci fi handwave tech to begin with. Just say that... the body's natural processes in stasis it's very hard to judge how the surgery is going so you have to be much slower or someshit.

> Also can we please stop using the slippery slope for 'power creep'?

As soon as people's kneejerk to any nerf stops being "we should just buff everything else". 

And not like bufffing it would solve the issue. There are two kinds of people, those who actually use surgery tables and everyone else. Buffing surgery tables isn't gonna turn many stasis table docs into surgery table users, if they cared/knew they'd be doing that already. Nerfing stasis table might forcefully "convince" more, easier to switch FROM an inconvenient option than TO a better one. Frankly i think removing the choice would be prefferable. Make stasis prevent any surgery and let people unbuckle instead of letting them fuck themselves (and the patient) over.

**Comment by Majorkite** [comment]
So lets say we add this and we have a very long, annoying adjustment process where people refuse to change their behaviors because it will STILL be the surefire way to make sure nothing goes wrong or their organs dont rot out or they dont catch on fire cause they're a plasmeme.

in service to...what? Making you use a surgery table? If you know what you're doing it takes about a minute to revive people that are under 250 damage of any one type, less if they're below threshold. otherwise they should be going on the table anyway. All this does is make procedures where you NEED the stasis bed more annoying. And also it just wastes my time as an MD player. I'm already spending half my shift watching a progress bar fill over and over again, why does that need to be even LONGER? 

Another one sentence justification to change a major aspect of the game, using an arbitrary number. Hard pass.

**Comment by TJatPBnJ** [comment]
didn't stasis bed surgery slowdown already get merged like 2 years ago

**Comment by Mothblocks** [comment]
No

**Comment by Mothblocks** [comment]
Not with any number

**Pull request closed without merging**
