### PR TITLE
Science Channel for Shaft Miners

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Shaft miners now have access to the science channel.
/:cl:

Scientists are complaining that miners often vanish without bringing minerals and miners complain RD isn't doing research, maybe they'll both get their side done if they're able to verify the other guy is alive and working.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
papa bless

**Comment by GunHog** [comment]
REMOTE MOONLIGHTING IS **NOT OKAY!!** (Good change)

**Comment by Crushtoe** [comment]
Can you have it be off by default, like the channels on the Captain's headset?

**Comment by KorPhaeron** [comment]
I could but then I feel like we'd run into the same problem if nobody ever turned it on

**Comment by jughu** [comment]
Just give science supply channel not the other way around ok

**Comment by XDTM** [comment]
Not all of cargo is tied to science as much as miners.

**Comment by jughu** [comment]
If miners are tied to science why dont give them science access?

**Comment by XDTM** [comment]
I could see them having basic science access. On box, though, it means that they'd have access to the RnD lab as well. Which could be good since it gives miners an option if nobody did RnD, but it also would make mining a position with a lot of power.

**Comment by jughu** [comment]
Its not like scientists will let them inside anyways or hop gives miners science tbh

**Comment by FantasticFwoosh** [comment]
@XDTM 

Well technically you can lock the consoles and close the shutters if you don't want filthy miners abusing the consoles with their precise amount of minerals then running away with the printed toys, from something meta like that, science wouldn't be getting minerals at all.

**Comment by XDTM** [comment]
If they get science access they can bring minerals in, put them in the lathe, print their stuff and go away happy without me needing to open doors every time, which suits me just fine.

**Comment by Dorsisdwarf** [comment]
If they get science access they can invalidate half the job of scientists, and will inevitably get in fights, win fights, and cause !drama!

**Comment by jughu** [comment]
dont worry it is the scientist's autism that matters

**Comment by FantasticFwoosh** [comment]
> *COUGH*  @Dorsisdwarf : My concerns on moonlighting and robbing experience from R&D

**Comment by Hatfish** [comment]
Perhaps science access should be added to miners who are on lowpop, and vice versa for scientists?

**Comment by XDTM** [comment]
Sounds good to me

**Comment by Anonmare** [comment]
Let's not give miners default access to the science department. Let's not start causing miner power creep

**Comment by demonfiren** [comment]
@Anonmare "start"

**Comment by BrokenCycle** [comment]
No, please, give miners the science access, its not like we'll take a bunch of equipment boards, do their jobs better than them, and point and laugh when the singularity is released.

:^)

**Comment by soulgamer** [comment]
Why not just give Research its own wall radio with access to the cargo channel instead. That way they still have a way to check up on the miners but the miners and R&D dont walk around with access to a radio channel they dont need for their job.

**Comment by jughu** [comment]
@Anonmare but lavaland is already powercreep land

**Comment by Cheridan** [comment]
powercreep

**Pull request merged**
