### PR TITLE
Freeze notification for the Month of august

### PR DESCRIPTION
**Pull request by optimumtact**
We will be doing a feature freeze for the month of August, to give maintainers a break from design discussions and to give some space for a few projects to maybe reach fruition.

This is your early notification PR.

### CODE REVIEW

**Comment by tralezab** [comment]
make it july. right now. do it. pussy.

**Comment by Fikou** [comment]
make it july. right now. do it. github word.

**Comment by Urumasi** [comment]
Is this going to be enforced to the level of the last antag freeze we had or will Fikou be able to do work on MODsuits (coming in 2021) in august?

**Comment by ArcaneMusic** [comment]
General freeze rules are as follows, so that our good friend OptimumTact need not repeat himself, are as follows:

- New PRs under either Context Expansion or Mechanics tags (Features) are subject to closure during the period of the freeze. 
    -   Any Pull requests opened before the freeze begins are not subject to closure, allowing for longer term projects to get the scrutiny they require.
- Pull requests that are not labeled as a feature, but function as a feature in their solution is up to maintainer's to decide to close or allow.
- As always, everything can be super ultra double exempted from these by headcoder decision.
- All other PRs are allowed in the meantime.

**Comment by MrDoomBringer** [comment]
So that our good friends the maintainers [need not repeat themselves](https://github.com/tgstation/tgstation/pull/54033):
image
image
I'm assuming the same is applying this freeze

**Comment by Fikou** [comment]
does balance count as a feature

**Comment by optimumtact** [comment]
You're goddamn right it does

**Comment by ShizCalev** [comment]
merged

**Pull request closed without merging**
