### PR TITLE
Reactions no longer give double the product

### LINKED ISSUE #68508: Chemical reactions double the results
Reporting client version: 514.1585

## Round ID:
[186775](https://scrubby.melonmesa.com/round/186775)

## Testmerges:
- [Arachne Borgs](https://www.github.com/tgstation/tgstation/pull/68444)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)

## Reproduction:

Likely related to #68385

React 5u Hydrogen/Carbon/Welding fuel.
Notice it produces 30u oil rather than 15.

Also thanks for making this change =)

### PR DESCRIPTION
**Pull request by Justice12354**
## About The Pull Request
The times of making infinite water by freezing and melting it have come to an end.

Someone decided that copy-pasting a line because there was an empty space would be a good idea. Spoiler: it wasn't. 
I deleted that repeated line :)

Fixes #68508 

## Why It's Good For The Game
I want to go back to making my chems in peace, please.

## Changelog

:cl:
fix: Chemical reactions no longer give you double the product
/:cl:

### CODE REVIEW

**Comment by Justice12354** [comment]
Please don't flame me for the number of commits! I'm not that good at this, okay? :(

**Comment by LemonInTheDark** [comment]
Bro your master's rotten

**Review by LemonInTheDark — APPROVED** [review]

**Comment by Justice12354** [comment]
> Bro your master's rotten

I wish I knew how to fix it!

**Review by Kylerace — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
(assuming there's nothing on it you want to keep, and upstream points to the tg repo)
`git checkout master`
`git reset upstream/master --hard`

**Comment by Justice12354** [comment]
> (assuming there's nothing on it you want to keep, and upstream points to the tg repo) `git checkout master` `git reset upstream/master --hard`

Will it reset all my branches?

**Comment by LemonInTheDark** [comment]
`git reset {target} --hard` will reset just the branch that's checked into when it's used, so no

**Pull request merged**
