### PR TITLE
[APRIL FOOLS] The sus is gone

### PR DESCRIPTION
**Pull request by notfrying1pans**
## About The Pull Request
The game is no longer suspicious

## Why It's Good For The Game
We are now avoiding legal action

## Changelog
:cl: deranging
del: Removed suspicious activity from the game
fix: fixes our legal status
/:cl:

### CODE REVIEW

**Comment by EdgeLordExe** [comment]
?????????????????????????????????????????????????????????????????????

**Comment by Kylerace** [comment]
damn i cant believe InnerSloth LLC trademarked all uses of the word imposter

**Comment by Serxule** [comment]
i mean the devs are literally ok with fan games and shit I don't think we have to worry

**Comment by notfrying1pans** [comment]
:trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:

**Comment by JohnFulpWillard** [comment]
when the doppelganger begins to display potentially misleading activities

**Comment by Kylerace** [comment]
:suspect:

**Comment by D4C-420** [comment]
I saw the PR  vent.

**Comment by notfrying1pans** [comment]
> 
> 
> I saw the PR vent.

NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by maxymax13** [comment]
image

**Pull request closed without merging**
