### PR TITLE
Clicking item slot now clicks the item in it

### PR DESCRIPTION
**Pull request by Core0verload**
95% less pixel hunting with tiny sprite items in pockets.

It also includes a rider commit with small path consistency change.

:cl: CoreOverload
tweak: Clicking item slot now clicks the item in it.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Infinite love for this! One concern though, clicking the item slot moves the item from that slot to the active hand. Have you provided a suitable replacement for this?

**Comment by XDTM** [comment]
Finally i can activate eswords without hunting for those two pixels

**Comment by anconfuzedrock** [comment]
am i the only one who puts the item that is more useful in the right pocket because  it is easier to quickly click that pocket than the left one

**Comment by dannno** [comment]
@XDTM did you seriously not just like press the use button
like even non-hotkey mode has one

**Comment by Core0verload** [comment]
>One concern though, clicking the item slot moves the item from that slot to the active hand. 

Never noticed this TBH. Clicking the item itself moves the item to the active hand too, unless it's a storage item. And storages support click-drag.

**Pull request merged**
