### PR TITLE
Adds logging to anomalous crystals

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
k e k

**Comment by Ergovisavi** [comment]
"Why don't you put the whole WORLD in a log, kevinz000?"

**Comment by Repukan** [comment]
Did you get clowned again.

**Comment by ExcessiveUseOfCobblestone** [comment]
he did

**Comment by Repukan** [comment]
Kev stop being a fucking baby and nerfing or making everything that kills you logged so you can shitcan the people that do it.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's literally just a log tho

**Comment by Repukan** [comment]
Slippery slope to make bringing crystals with less than desirable effects on station count as ooc grief.

I'll bet money on it too

**Comment by Armhulen** [comment]
>admin logging is a slippery slope to nerfing it

HAHAHAHHAHAHAHAHAHAHAHAHA

**Comment by KorPhaeron** [comment]
It is though

Why else would you send a big PLAYER DID A THING to admins if you dont expect admins to act on it?

**Comment by KorPhaeron** [comment]
And once admins routinely act on something to the point that people cant use it without bans, that thing will often be nerfed or removed

**Comment by ExcessiveUseOfCobblestone** [comment]
You get in trouble right now if you get caught doing it, I don't see how the doomsay of "ITS GONNA BE NERFED" is warranted when we've had the policy of "using boss items to grief as nonantag is still grief as nonantag" for a while now without nerfs that I know of going to the worst offenders like blood contract and mayhem.

"Sorry I couldn't catch the guy who turned you into a clown that ended up with you getting killed because guys on the code thought letting me know that was going to cause a nerf to it" ???

**Comment by KorPhaeron** [comment]
>you're gonna get in trouble if you put clown clothes on someone

The real slippery slope in /tg/ has always been finding more and more minor things to qualify as an OOC issue

Why do you play SS13 if you cant handle the stress of a clown mask being put on you?

**Comment by Repukan** [comment]
I've literally never been bwoinked for bringing the crystal clowning on station

**Comment by KorPhaeron** [comment]
https://atlantaned.space/newSS13tools/stats/monthlyStats.php?year=2017&month=07&stat=megafauna_kills

For reference the colossus died 6 times last month and has a 50% chance of the crystal and an even lower chance of it having the clown effect.

Something silly and non lethal that happens less than once a month is not something we should be trying to stamp out, its one of those weird quirky things that make the game what it is

**Comment by Kromgar** [comment]
I have

**Comment by KorPhaeron** [comment]
@Kromgar 

lmao by who

**Comment by Kromgar** [comment]
@Kor it was like a month or two ago i got bwoinked asking what was i doing with an anomaly in the halls. Told them i was taking if to the clown. Really i was just dragging it theough the halls to clien people who talked

**Comment by KorPhaeron** [comment]
If headmins want this merged I will reopen but otherwise I dont think we should be sending the message that admins should stop this

**Pull request closed without merging**
