### PR TITLE
Ports Crew Transfer

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Ports [#1855](https://github.com/BeeStation/BeeStation-Hornet/pull/1855)
This starts a player vote at the 90 minutes to call the evac shuttle.
If the vote fails, it will ask every 30 minutes after. 
Non-votes are weighted based on round time.
This has been made toggleable via config options.
The crew transfer shuttle [cannot be recalled](https://github.com/BeeStation/BeeStation-Hornet/pull/3891).

### Images:
Imgur img
Imgur img

## Why It's Good For The Game
- CentCom doesn't pay overtime
- Rounds can get pretty stale after a while
- Great for low pop: No heads needed
- Democracy 

## Changelog
:cl:
add: In order to contribute to overall crew "health" and "well-being", CentCom will now start a shuttle vote at the 1:30 mark and every 30 minutes thereafter.
/:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
Is it that hard to request the shuttle normally?

**Comment by spessbro** [comment]
i could've sworn we already had this

**Comment by Timberpoes** [comment]
If I'm correct, this kind of system was proposed in the past and has been blocked in the past.

I do not believe we have any intent to allow OOC votes on whether the shuttle should be called or not and the shift ended.

Players are, as always, encouraged to use IC means to call and recall the shuttle while admins can accomplish the same through ahelps if needed.

Unless another maintainer steps up to the plate to support this, I will be closing this PR in 24 hours. You may, of course, get the permission of another maintainer but that doesn't mean it won't THEN get blocked by any of the headcoders.

**Comment by TiviPlus** [comment]
https://github.com/tgstation/tgstation/pull/53584

**Comment by LemonInTheDark** [comment]
It has in fact been tried before, it died due to a lack of interest from headmins and dislike from maintainers relating to the low timer and well, pretty much what timber said.

**Comment by jlsnow301** [comment]
> It has in fact been tried before, it died due to a lack of interest from headmins and dislike from maintainers relating to the low timer and well, pretty much what timber said.

timer is easily changeable in config here

**Comment by Cyberboss** [comment]
denied

**Comment by Serxule** [comment]
you do realize only manuel goes on for long enough for this to even happen right

**Comment by ShibaInuLord** [comment]
> 
> 
> you do realize only manuel goes on for long enough for this to even happen right

huh what

**Comment by LemonInTheDark** [comment]
it's nice that you feel that way

**Pull request closed without merging**
