### PR TITLE
TDM map for Deathmatch

### PR DESCRIPTION
**Pull request by EEASAS**
## About The Pull Request
adds a team deathmatch map for deathmatch gamemode
image
russian team(left) gets
1 infantry, 1 medic
marine team(right) gets
1 infantry, 1 gygax
they all also have different gear based on their loadout and team
step on the landmines in the center on the bridge to explode the map and win
## Why It's Good For The Game
maybe the real deaths were the friends we made along the way
## Changelog
:cl:
add: Added a team deathmatch map for the deathmatch gamemode
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
the design feels very busy
it's 
1. a team thing
2. a class thing
3. asymmetrical 
4. Point capture ish
5. Sort of an attrition thing with the river and encampments

I mean it's gonna be fine either way but could use some focus.

**Comment by Eronymun** [comment]
I'm actually a big fan of the idea of implementing team modes for all maps. I kinda wanted to do little tournaments with people on the server whom can set up premade teams.

**Comment by mc-oofert** [comment]
there's nothing team based about this they can immediately shoot their ""team"" and the other team can just not spawn

**Comment by EEASAS** [comment]
> there's nothing team based about this they can immediately shoot their ""team"" and the other team can just not spawn

you can only play the map if you have 4 players, that is the max and minimum
also your not meant to team kill...

**Comment by Admiral-Gigaton** [comment]
> > there's nothing team based about this they can immediately shoot their ""team"" and the other team can just not spawn
> 
> you can only play the map if you have 4 players, that is the max and minimum also your not meant to team kill...

But it's going to happen.

Maybe you could varedit some laser tag shit for this?

**Pull request closed without merging**
