### PR TITLE
NEW TRAIT JOB: Telecommunication Dispatcher

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Telecommunication Dispatcher, or simply Dispatcher, specializes in organizing communication between departments, coordinating crew responses to emergencies, and maintaining situational awareness. Additionally, the role involves maintaining and defending telecommunications systems. Dispatchers do not have real authority over anyone; their words are merely strong suggestions, while department heads retain ultimate authority. **Only appears a STATION TRAIT JOB.**

You can think of them as an IT/SYSAdmin guy with the side job of relaying messages. Some servers have this kind of role as a full-time job.
<details>
<summary>Images</summary>

dispatcher1

dispatcher2
</details>

They are equipped with a Deluxe Radio which can be set to any frequency and has loud-volume mode, **this way they can send messages to specific channels when even comms are down!**
Their PDA and Laptop have a hyper and high energy cell from the start because they are expected to use those extensively.

They are part of the Service and Engineering department and respond to HoP and CE. They have access to every radio channel on the station.

Adds a Blue Hazard Vest which is only worn by Dispatcher.
## Why It's Good For The Game
After my PR for making the Security Dispatcher a full-time role was denied due to concerns about it overlapping with the Warden's responsibilities, one of the comments suggested creating a general Dispatcher role, not limited to Security. Introducing this as an occasional Trait Job would add more depth to station interactions. Heads of departments often struggle with effective communication, and a Telecommunication Dispatcher could alleviate this issue by relaying useful information and messages.

Additionally, the Telecommunication control room is usually unmanned, despite the consoles being useful for monitoring station activities. A Telecommunication Dispatcher could assist the Detective in identifying traitors by monitoring secret communications and retrieving radio logs to confirm suspicions. By overseeing telecommunications, Dispatchers would also present a minor challenge for antagonists attempting to sabotage them. **However, since this is a Trait Job, it wouldn't be a constant obstacle, maintaining a balance in gameplay dynamics.**
## Changelog
:cl:
add: NEW TRAIT JOB: Telecommunication Dispatcher tasked with overseeing tcomms, and helping with interdepartmental communication
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
feels very similar to human ai trait

**Comment by mc-oofert** [comment]
people will play this for like 5 minutes get bored and leave tcomms to play assistant

**Comment by DrDiasyl** [comment]
> feels very similar to human ai trait

I can't disagree, but Human AI does the job of well AI, while this is solely focused on Tcomms. Some servers do have a specialized Telecommunications Technician role.

**Comment by DrDiasyl** [comment]
> people will play this for like 5 minutes get bored and leave tcomms to play assistant

This can be said about other Trait Jobs

- Veteran Security Advisor? Get bored and just be Security (but on a wheelchair)
- Bridge Assistant? Get bored of sitting in Bridge and be Assistant

**Comment by Jacquerel** [comment]
I'm gonna be honest I don't think this has enough juice, it's like essentially a less exciting version of bridge officer

**Comment by DrDiasyl** [comment]
> I'm gonna be honest I don't think this has enough juice, it's like essentially a less exciting version of bridge officer

What kind of juice it can have? And, shouldn't Trait Job have nil maintenance cost as those are like very rare and not everyday content

**Comment by Jacquerel** [comment]
> > I'm gonna be honest I don't think this has enough juice, it's like essentially a less exciting version of bridge officer
> 
> What kind of juice it can have? And, shouldn't Trait Job have nil maintenance cost as those are like very rare and not everyday content

IDK because making it exciting is your job but there's no point adding a rare job if it isn't inherently exciting to see, especially of it has significant role overlap with two others we already have

**Comment by DrDiasyl** [comment]
> > > I'm gonna be honest I don't think this has enough juice, it's like essentially a less exciting version of bridge officer
> > 
> > 
> > What kind of juice it can have? And, shouldn't Trait Job have nil maintenance cost as those are like very rare and not everyday content
> 
> IDK because making it exciting is your job but there's no point adding a rare job if it isn't inherently exciting to see, especially if it has significant role overlap with two others we already have



> > > I'm gonna be honest I don't think this has enough juice, it's like essentially a less exciting version of bridge officer
> > 
> > 
> > What kind of juice it can have? And, shouldn't Trait Job have nil maintenance cost as those are like very rare and not everyday content
> 
> IDK because making it exciting is your job but there's no point adding a rare job if it isn't inherently exciting to see, especially if it has significant role overlap with two others we already have
Basically it is taking a niche that no one does (Telecommunications) and giving someone to do only it. Engineers only ever touch tcomms when those blow up.

**Comment by DrDiasyl** [comment]
Also their special radio allows them to send messages to specific channels even when comms are down, to keep opsec if they want to.

**Comment by DaydreamIQ** [comment]
I like this idea but it feels wholly unnecessary. It's basically comms agent without its own base and doesn't really add much more than what an engineer with the password could do

**Comment by DrDiasyl** [comment]
> I like this idea but it feels wholly unnecessary. It's basically comms agent without its own base and doesn't really add much more than what an engineer with the password could do

That's why it is a **TRAIT JOB**

**Comment by Sadboysuss** [comment]
cool concept but it will be wholly ignored by everyone, maybe would have some kind of interaction on mrp but I feel like they need more impact to be able fun or viable, plus AI already fills this role by being able to use the intercomms near them.

**Comment by DaydreamIQ** [comment]
Being a trait job doesn't excuse it being boring. Look at human AI, its a job that already exists but it changes it up in a way that's actually interesting. Vet and Bridge assistant are mostly just joke roles at this point but if all the station trait jobs are for is jobs with zero unique content what's the point?

**Comment by DrDiasyl** [comment]
> Being a trait job doesn't excuse it being boring. Look at human AI, its a job that already exists but it changes it up in a way that's actually interesting. Vet and Bridge assistant are mostly just joke roles at this point but if all the station trait jobs are for is jobs with zero unique content what's the point?

Interesting doesn't always mean unique. I would say this job would be fun as it is about a niche (tcomms) not a lot of people do because they have better things to do as Engineer.

**Comment by Higgin** [comment]
cool trait job, like it as someone who likes to do this as a head

**Comment by TheVekter** [comment]
I can finally do my actual IRL job in my digital fake job

**Comment by MrMelbert** [comment]
> organizing communication between departments, coordinating crew responses to emergencies, and maintaining situational awareness

We have a full time job for this, it's called the Captain

**Comment by DrDiasyl** [comment]
> > organizing communication between departments, coordinating crew responses to emergencies, and maintaining situational awareness
> 
> We have a full time job for this, it's called the Captain

Sorry, I'm too busy flexing my all-access ID with my self-recharging pewpew to kill valids.

**Comment by SomeoneYouProbablyKnow** [comment]
I do agree that this job doesn't have enough oomph to it. But i think there's a very simple way to fix it, when this trait is rolled disable common radio (Or make it one way, you can talk but you can't hear the channel unless the dispatcher is speaking). Now suddenly you REALLY need someone to coordinate everything that's happening and one captain is not enough. 

The crew is also not completely crippled, you can still manually adjust radios to specific frequencies if you want to have a chat with a friend, holopads are greatly underused, secuirty has department officers and they can talk on department radio and heads have their own head channel.

I know we have a headcoder proclamation (mothblocks' i think) that common radio has to stay but this is a trait and traits should be impactful and changing the nature of communication can really shake a round up.

**Comment by DrDiasyl** [comment]
> I do agree that this job doesn't have enough oomph to it. But i think there's a very simple way to fix it, when this trait is rolled disable common radio (Or make it one way, you can talk but you can't hear the channel unless the dispatcher is speaking). Now suddenly you REALLY need someone to coordinate everything that's happening and one captain is not enough. 
> 
> The crew is also not completely crippled, you can still manually adjust radios to specific frequencies if you want to have a chat with a friend, holopads are greatly underused, secuirty has department officers and they can talk on department radio and heads have their own head channel.
> 
> I know we have a headcoder proclamation (mothblocks' i think) that common radio has to stay but this is a trait and traits should be impactful and changing the nature of communication can really shake a round up.

Sounds like a fine idea but this would really go out of my original scope, I should first find out if maints are okay with this

**Comment by DrDiasyl** [comment]
Also, as a Dispatcher you can kind go and turn off Common yourself lol. Not like people will like it, but try to gaslight them that it always was this way.

**Comment by totalglyphiddeath** [comment]
Cool trait job, but is it assigned to a department? Bridge Assistant is Command, Veteran Security Advisor is Security, Cargorilla is Cargo, Human AI is synthetic, ect. Is Telecommunications Dispatcher assigned to engineering?

**Comment by DrDiasyl** [comment]
> Cool trait job, but is it assigned to a department? Bridge Assistant is Command, Veteran Security Advisor is Security, Cargorilla is Cargo, Human AI is synthetic, ect. Is Telecommunications Dispatcher assigned to engineering?

Service-Engineering. Kinda like how Psychologist is Service-Medical

**Comment by totalglyphiddeath** [comment]
I think it should be assigned to engineering for clarity and consistency sake.

**Comment by DrDiasyl** [comment]
> I think it should be assigned to engineering for clarity and consistency sake.
> 

Telecommunication part of the job is about Engineering, Dispatch is about Service. Simple as that.

**Comment by SciDragon** [comment]
A shame. I think this is even a good enough niche to be a permanent engineering role in M/HRP servers/downstreams.

**Comment by Loafin34** [comment]
i don't like it.. the radio and kit are fine if you just map them into tcomms, as then any one assistant can choose to become dispatcher instead of having to stick with it as a trait.  It feels like putting a hat on a hat; there's at least two people using comms to "dispatch" people as their job (warden with their camera console, AI with their magic ability of being a camera console), and it's far more dynamic for someone to just yell in common "HELP MED MAINT" than for them to go :m "HELP MED MAINT" and the dispatcher (who may or may not be even paying attention) to go :s "someone's in trouble in medical maintenance!"

**Comment by DrAmazing343** [comment]
@00-Steven

**Comment by tralezab** [comment]
> I do agree that this job doesn't have enough oomph to it. But i think there's a very simple way to fix it, when this trait is rolled disable common radio (Or make it one way, you can talk but you can't hear the channel unless the dispatcher is speaking). Now suddenly you REALLY need someone to coordinate everything that's happening and one captain is not enough.
> 
> The crew is also not completely crippled, you can still manually adjust radios to specific frequencies if you want to have a chat with a friend, holopads are greatly underused, secuirty has department officers and they can talk on department radio and heads have their own head channel.
> 
> I know we have a headcoder proclamation (mothblocks' i think) that common radio has to stay but this is a trait and traits should be impactful and changing the nature of communication can really shake a round up.

i like this idea quite a lot, good post 👍

**Comment by Fikou** [comment]
didnt one of the headcoders also say we dont want a station trait that turns off common

**Comment by DrDiasyl** [comment]
> didnt one of the headcoders also say we dont want a station trait that turns off common

Yeah, so this doesn't turn off common. But I think it meant more of that we cannot permanently delete common forever

**Comment by Jacquerel** [comment]
Reopen this if you find someone who will merge it

**Pull request closed without merging**
