### PR TITLE
Boxstation - new break room, cryo moved, larger treatment area

### PR DESCRIPTION
**Pull request by Sylphet**
## About The Pull Request

This PR expands the stasis area on Boxstation. It moves cryo to what used to be Surgery B, turns the ward into a break room, and adds a crew monitoring console to the stasis area.

## Why It's Good For The Game

Boxstation's medical treatment area is really, really small, and it's terrible to work in. This fixes that by making the area larger, and using what used to be the ward, which went entirely unused.

## Changelog
:cl:
del: Removed boxstation medbay ward
add: new break room
add: crew monitoring console
tweak: moved cryo
tweak: expanded treatment area
/:cl:

## Stasis

boxstation 1

## Break Room

boxstation 2

## Cryo

boxstation 3

### CODE REVIEW

**Comment by GunHog** [comment]
It looks like you may have based this off an old map, or screwed up your map merge. You deleted the new Psychologist's office, reverted the Incinerator room change, and something odd is happening with the gateway.

**Comment by Sylphet** [comment]
yeahhhh already noticed that - not sure how it happened, but i'm working on it. this is why it's a draft!

**Comment by uomo91** [comment]
I like the idea of the expanded treatment room, but it looks like you'd still have plenty of room for cryo inside it. Also replacing the ward with a break room is a nice idea.

**Comment by SpinnerMaster** [comment]
Free roundstart tub of skub is unbalanced.

**Comment by uomo91** [comment]
I still think you have more than enough room to keep cryo in the general treatment area without overwriting surgery B.

**Comment by uomo91** [comment]
And I think you could avoid the awkward 1 tile wide hallway leading in and out of chemistry if you scooched the airlocks back one tile, on the left side of the expanded treatment area.

**Comment by cacogen** [comment]
skub isn't overpowered

**Comment by nicbn** [comment]
skub is indeed overpowered

**Comment by Twaticus** [comment]
free BEPIS reward rolling tables :flushed:

**Comment by Dennok** [comment]
> free BEPIS reward rolling tables

Now BEPIS on removing, or removed or in planes to remove, and tabble in researtch node (or in planes to move ot to node).

**Comment by Angustmeta** [comment]
Break room should have non-see through door and windows imo, to make it comfy (for antags)

**Comment by Tlaltecuhtli** [comment]
it looks ugly and crappy but it in the end it does fit the boxstation theme

**Comment by Sylphet** [comment]
thanks, it's my first time mapping

**Pull request closed without merging**
