### PR TITLE
Adds travis.yml + bug fixes/oversights

### PR DESCRIPTION
**Pull request by Okand37**
Accidentally pushed this to my master branch, was going to fix but korphaeron said they'd just merge it from the master.

Adds deltastation to .travis.yml along with fixing bugs, oversights, and other related issues regarding Delta Station.

### CODE REVIEW

**Comment by Cyberboss** [comment]
Map diff is bad

**Comment by xxalpha** [comment]
You converted the map to dmm, was that intentional?

**Comment by optimumtact** [comment]
lern to map merge

**Comment by Okand37** [comment]
I was going to fix it, but kor said I should just pull request it anyway. I guess I'll go fix it.

**Comment by xxalpha** [comment]
What, you know you can just push another commit.

**Pull request closed without merging**
