### PR TITLE
Removes outdated science airlock from RCD.

### LINKED ISSUE #34375: paint job is wrong on doors
image

one of these was made with the rcd the other was already there

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request
Closes #34375. 
This removes the science airlock from the RCD, while keeping the research airlock in it. The difference between the two is that the science airlock has a brighter purple and is used in space ruins (Which is why I didn't remove it, someone else is welcome to do that), and the research one is what's used in all the current stations.

This is my first PR on tg, and about my fourth in general, so even though I compiled and checked ingame, please doublecheck in case I somehow fucked up deleting 4 lines of code from the .dm.

## Why It's Good For The Game
Removes some possible confusion on what airlock to pick and possible mismatched airlocks, as seen in the issue's image:

image
The right one's the science one, and on the left the default research one.

## Changelog
:cl:
del: Removed duplicate science airlock from RCD.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Eh, good effort but honestly I don't see the reason why we can't just have both airlock types.

**Comment by Rinoka** [comment]
it's just updating the RCD to output the modern door style. probably an oversight from when the redesign was implemented.

**Comment by cacogen** [comment]
Currently it has the option for either. The science airlock is ugly though and this'll make the RCD menu slightly less long.

**Comment by actioninja** [comment]
SOUL
image
SOULLESS
image

**Comment by Ty-the-Smonk** [comment]
Coder removing SOUL from MY Spessmen smh

**Comment by optimumtact** [comment]
@ShizCalev why on earth did you thumb this down?

**Comment by actioninja** [comment]
the quest to forcibly remove all soul from the game continue

**Pull request merged**
