### PR TITLE
Adds space cleaner spray to the kitchen

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Adds space cleaner spray to the kitchen

## Why It's Good For The Game

No more dirty kitchen. Lets you keep on top of the blood everywhere a little easier.

## Changelog
:cl:
add: Gives the chef a spraybottle of space cleaner.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
cringe PR just call the janitor over

**Comment by RaveRadbury** [comment]
Power creep, damp rags are in most service halls and can be used to clean the microwave, janitor has rags in their vendor. You can go to dorms and take a bedsheet and cut it with your knife to make damp rags, the biogenerator makes cloth for damp rags.

**Comment by ThatGuyFromThatPlace** [comment]
> Power creep, damp rags are in most service halls or the bar and can be used to clean the microwave and floor, bartender has rags in their vendor. You can go to dorms and take a bedsheet and cut it with your knife to make damp rags, the biogenerator makes cloth for damp rags.
> 
> You can also print a bucket and mop from the service lathe. Spray bottles are scarce for a reason.

"Convenience OP, plz nurf."
Because, letting the chef have something to clean microwaves is bad, but the chemist having one is fine?
Only on TG would anyone think that a spray bottle is OP powercreep. The fact that you said that is high-key cringe.

**Comment by MrDoomBringer** [comment]
why are skyrat coders coming into this post to support this or
just make the PR on your own codebase

**Comment by MrDoomBringer** [comment]
also yes this is powercreep

**Comment by RaveRadbury** [comment]
> why are skyrat coders coming into this post to support this pr
> just make the PR on your own codebase

They inherit our maps, they have no choice but to make map PRs here if they want them downstream.

>Because, letting the chef have something to clean microwaves is bad, but the chemist having one is fine?

Janitor spray bottles aren't found in the jani vendor. Most maps only allot one for the janitor's closet, even though two janitors are allowed (Delta being the exception). Medbay gets one on some maps, this is due to the issue of slips in a high-traffic medbay being a terrible experience. The chemist spray bottles are far less efficient with how they use reagents.

Rags, mops, and buckets are all easily within reach for the cook. I play janitor and cook a lot, I am very familiar with these spaces and their balance.

**Comment by RaveRadbury** [comment]
@tf-4 if you want to make this change without having to go through us I would recommend adding the space cleaner bottle the chef vendor. This way you won't have to make a map edit to get what you want.

**Comment by Cyberboss** [comment]
> They inherit our maps, they have no choice but to make map PRs here if they want them downstream.

What? You guys are fully autonomous. You can have different maps than us.

**Comment by Cyberboss** [comment]
Also, I too disagree with this PR

**Comment by tf-4** [comment]
> 
> 
>The number of cleaner spray bottles is intentionally kept limited, they can't even be printed from the servicelathe.

They can with the Advanced Sanitation Technology tech. But I agree, would be easier all round just to add it to the vending machine.

**Comment by ilikesaying** [comment]
**why is this convenience considered powercreep i just want to clean up the gibs faster please the crew are trying to break in**

**Comment by Losenis** [comment]
I'm more concerned as to why even a spray rather than something like a soap. Spray doesn't even clean the microwave, does it?

**Comment by RaveRadbury** [comment]
@Cyberboss 
image

**Comment by Cyberboss** [comment]
This is still SkyRat's problem, not ours.

**Comment by zxaber** [comment]
You should at least have to go out of your way if you want to take work from the janitor. A free spray bottle just to avoid player interaction is lame.

**Comment by optimumtact** [comment]
adios, **friend**

**Comment by MrDoomBringer** [comment]
based
another example of how the protections of the 24-hour no-close rule do not apply to non-citizens

**Pull request closed without merging**
