### PR TITLE
Extinguisher cabinet resprite

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Extinguisher cabinets are now Extinguisher racks, which serve the same function but are much, much easier to see.

image
image

## Why It's Good For The Game

Visual clarity is nice, a featureless grey box, is not.

## Changelog

:cl:
sprite: Extinguisher cabinets are now extinguisher racks, which are much easier to see.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Some in-game pictures would be nice too 🙂

**Comment by Wallemations** [comment]
It needs pictures _in the PR_

**Comment by Ghommie** [comment]
> It needs pictures _in the PR_

github actions removed the pictures for some reason. Check the edits.

**Comment by DATA-xPUNGED** [comment]
> > It needs pictures _in the PR_
> 
> github actions removed the pictures for some reason. Check the edits.

Github actions stole my images, can't have shit in tgstation

**Comment by CPTANT** [comment]
The idea is awesome but can it go a bit lower? To me it now reads like it is above the wall, which would mean it is poking through the ceiling.

**Comment by necromanceranne** [comment]
Perfect, I can actually tell there is a fire extinguisher there now.

**Review by Twaticus — APPROVED** [review]

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
