### PR TITLE
Buffs granibitaluri

### PR DESCRIPTION
**Pull request by googobbug**
## About The Pull Request

Buffs granibitaluri to be a worthwhile top-off healer

## Why It's Good For The Game

Granibitaluri was intended to be a slow but convenient top-off chem for healing small injuries. Unfortunately, it's useless. The 8 units you get from a bruise patch will heal, at most, 4 brute OR burn (and only if you're under 10 brute/burn, which you probably aren't until the last couple cycles). It's also a pain to make (low yield and requires heating) so I've gone and reworked it into a new drug that I think fits the role better.

Granibitaluri now heals a small amount of brute and burn each cycle. The maximum healing you can get is 0.5 per cycle, and this decreases by 0.1 for every 10 combined brute and burn you have. At 50 or more combined damage, it heals nothing. I believe this is fast enough to be an attractive option for topping off your health (as well as something to add alongside C2s) while being slow enough that it won't overshadow C2s. The overdose was changed to deal toxin and liver damage, since I thought it fit better. Also, the recipe was changed to be easier to make and resemble a medicine more than sterilizer mixed with water.

## Changelog
:cl: Bumtickley00
balance: Buffed granibitaluri to be a better top-off healer
tweak: Changed granibitaluri's recipe to be easier to make
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
all medicines should be converted to the new naming scheme, it's not exclusive to C2s specifically.

**Comment by AdmiralPancakes1** [comment]
Oh whoops. I'll change the name back then.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's a shit name I need to give combos a unique suffix instead of "MASH THEM TOGETHER".

you can make your own suffix if you want and i'll have that use for combo's going forward.

**Comment by HomocidlePancakes** [comment]
These names make me fucking puke.

**Comment by Farquaar** [comment]
Please, save us from the "-uri"

**Comment by FloranOtten** [comment]
Turns out cobby is into Uri, who knew?

Great PR. The current medical patches are worth fuckall, and it being a low yield heated chem means that it's about as worth making as milk.

**Comment by carlarctg** [comment]
i don't like the name changes

granibitaluri -> aceminatophen is bad because granibitaluri tells you what it does (heals very little, like a grain), while aceminatophen just makes my brain turn off with a medicalish name, it sounds more like a drug than medicine

instabitaluri -> syniphen is really bad because, again, 'insta' means it works instantly, and having 'syn' at the start makes me think it needs to be injected with a syringe (syriniver) when that's obviously very wrong

i like the current suffixes and don't see a need to change them into -phen but the prefix for the chemicals telling you what it does is something that definitely should be kept

**Comment by AdmiralPancakes1** [comment]
yeah I forgot about the prefix thing when coming up with the names
I chose acetaminophen because it's a real drug (tylenol) and used as a filler for other meds so I thought it fit
syniphen is dumb yeah

I am actually going to hold off on changing names until a later PR and have this one just be the gran buff / recipe change

**Comment by Shadowflame909** [comment]
considering nanotransen is run by greedy corporations who clone their employees every shift

Makes me wish the names sounded more "Consumery" like Scratch-Away

**Comment by Tlaltecuhtli** [comment]
whats the point of making this which has pretty much the same stats of saline glucose solution?

**Comment by TheVekter** [comment]
:-1: until you change the name. It's *so bad* @ExcessiveUseOfCobblestone why did you think this name was a good idea

**Comment by Krysonism** [comment]
Syniphen was a good name.

**Comment by optimumtact** [comment]
Knock it off with the goddamn bikeshedding about the name. I swear to god you people.

Next person gets a 24 hour timeout.

**Comment by CPTANT** [comment]
Just remove the chemical and replace everything it is used in with saline glucose.

**Pull request merged**
