### PR TITLE
[s] Makes winning a pulse rifle little more noticable

### PR DESCRIPTION
**Pull request by coiax**
When someone wins a pulse rifle via arcade games, everyone dead
and all admins are notified. Also it comes with a firing pin now.

### CODE REVIEW

**Comment by Incoming5643** [comment]
Please don't changelog the miracle.

**Comment by PKPenguin321** [comment]
yeah remove the changelog this is a sekrit feature

**Comment by bgobandit** [comment]
probably should add [s] then

**Comment by RandomMarine** [comment]
The damage is already done @bgobandit

**Pull request merged**
