### PR TITLE
Automated announcement systems now announce researched nodes.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
The idea was born from a small conversation about bepis nodes having low visibility, which somehow degressed into the idea of announcing researched nodes to the channels of the interested departments thru the announcement system machine, which is what I'm doing here, while also adding documentation, defines and purging some, not all, instances of camel cases from announcement_system.dm.

Oh, by the by, like the arrival and new head arrival messages, it can be customized or disabled by interacting with the announcement system.

## Why It's Good For The Game
I think it's helpful to let players know when the research of their dept is researched, and I think it's kinda interesting to announce bepis tech on common like it's some hot stuff while it actually isn't just because it's often missed out and miscellaneous.

## Changelog

:cl:
add: Automated announcement systems now announce researched nodes to their respective departments. You can stop this by either disabling the announcement systems or by using a multitool on the circuitboard of the console you're researching nodes from.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
In general I like the idea.  The only problem I see with this is that everyone on station will know the instant AI upload boards are available for printing.

Perhaps it would only be announced over Sci comms?  Just an idea.

**Comment by Ghommie** [comment]
> In general I like the idea. The only problem I see with this is that everyone on station will know the instant AI upload boards are available for printing.
> 
> Perhaps it would only be announced over Sci comms? Just an idea.

Read the PR, it's only announced to command and science. The only nodes that are announced to the whole station are bepis and that's over on the common channel.

**Comment by Dorsisdwarf** [comment]
VERY nice feature. Love that it interacts with the announcement machine so it can be customised.

**Comment by SmArtKar** [comment]
This prevents stealthy research of illegal tech for traitors (in rare scenarios where its useful), maybe allow to multitool the board akin to how you do it with cargo to prevent nodes researched from that console from being announced?

**Comment by Ghommie** [comment]
Done, you can now disable the announcements with a multitool.

**Pull request merged**
