### PR TITLE
Signals for tool acts.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

This PR adds signals for all basic tool acts.
Replaced signals places where it's appropriate.

## Why It's Good For The Game

It's kinda dirty how we used to do attackby and then check for tool behaviour. Since we now have stuff like plumbing and possibly that one laser PR, we need signals that directly relate to tool behaviour.

## Changelog
:cl:
code: Added signals for all basic tool acts.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Did you really need to remove all the stray spaces

**Comment by nemvar** [comment]
Sorry, forgot the turn that off in my editor.

**Comment by optimumtact** [comment]
tested now I assume?

**Comment by nemvar** [comment]
Yes this is tested.

**Pull request merged**
