### PR TITLE
Clockwork marauders will now die when their host does

### PR DESCRIPTION
**Pull request by ChangelingRain**
Kill bugs before they get reported today.

Fixes failing to emerge if recovering when dying.
Fixes marauders not dying ever and being able to just drag their dead host corpse around murderboning.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
no stand ripoffs sorry remove them

**Comment by ChangelingRain** [comment]
denied

**Comment by KorPhaeron** [comment]
anime doesnt fit my design vision

**Comment by ChangelingRain** [comment]
it's a shame you keep adding anime things then

**Comment by KorPhaeron** [comment]
someone please stop me

**Comment by Bawhoppen** [comment]
make these things work as replacements for holos so you can't have both at the same time

**Comment by Man-Shroom-** [comment]
Why weren't these a child of holoparasites from the beginning

**Comment by ChangelingRain** [comment]
Because they actually do stuff annoying differently than holoparasites and it'd be more pain than it's worth to try and merge them, even though logically they SHOULD be.

**Pull request merged**
