### PR TITLE
[RED LABEL] Allows badmins to launch shit in from orbit without it looking like its in a pod [activates standing tall for tatorfall]

### PR DESCRIPTION
**Pull request by MrDoomBringer**
# [Leaked Titanfall three gameplay video (read: demonstration video) ](https://streamable.com/cvxnc)

## About The Pull Request

Allows admins to make shit enter the station without pussy supplypods, instead they can just fucking flying in from the heavans

## Why It's Good For The Game

Cus it looks badass as fuck watching mechs just yeet in, also admins can spawn themselves in by literally falling from the sky which is funny

## Changelog
:cl: MrDoomBringer
admin: Admins can now use the Centcom Podlauncher to launch things without the things looking like they're being sent inside a pod.
/:cl:

### CODE REVIEW

**Comment by Jordie0608** [comment]
\>Opened with merge conflicts

I was going to delete this label but looks like it's time for another

**Comment by VileBeggar** [comment]
image
jordie strikes yet again

**Comment by MrDoomBringer** [comment]
image

**Comment by wesoda25** [comment]
Epic

**Comment by tralezab** [comment]
alright someone make the titanfall gamemode now please

**Comment by Dorsisdwarf** [comment]
I thought the supplypod menu was just broken for me because I didnt update byond, is it actually MEANT to be that stupid awful list now?

**Comment by MrDoomBringer** [comment]
@Dorsisdwarf its more compact and the tooptips dont hide other buttons any more ree

if you have better suggestions lmk smh

**Comment by MrDoomBringer** [comment]
@Dorsisdwarf the tooptips dont hide other buttons any more with this format ree

if you have better suggestions lmk smh

**Pull request merged**
