### PR TITLE
[APRIL FOOLS] Assistants lately have been so incompetent, that syndicate, changeling church and the old ones no longer accept their job applications.

### PR DESCRIPTION
**Pull request by Sparkezel**
## About The Pull Request
Dear syndicate brothers and sisters, for too long we have allowed assistants to be enrolled in our ranks. But now because that they are getting more and more incompetent, I urge you all to look for new hires amongst security members in nanotrasen, I bet atleast few of them will want their revenge.

## Why It's Good For The Game
Greyshits will now need an actual job to be bad.

## Changelog
:cl:
fix: Assistants are now a protected role :)
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
what's the joke this is a good idea

**Comment by Sparkezel** [comment]
Why nobody thought of it yet though then? Also security can get antag now :)

**Comment by Krysonism** [comment]
NOOOOOOOOOOO

**Comment by rdragan** [comment]
We unironically need this but without a fallback if you do roll antag. Simply enabling assistant should disable antag rolling.

**Comment by Mothblocks** [comment]
For the benefit of the maintainers, April Fools PRs will be labeled and closed. Key Holders are still able to test merge PRs that are closed, so this makes no difference to you, the author, assuming you were able to find a Key Holder to merge this PR in the first place.

**Pull request closed without merging**
