### PR TITLE
zombies can eat brains (claw zombies will need some help!)

### LINKED ISSUE #43702: Zombies can't eat brains
## Reproduction:

Be a zombie, romerol or otherwise
Acquire brain, soul-inhabitated or otherwise
Attempt to click on/eat brain
Fail

Clearly this is gamebreaking and of crucial importance to maintain muh immersions.

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Zombies... can eat BRAAAIIINNSSS...

closes #43702 

## Why It's Good For The Game

Zombies as a Brains... species do not have... that much of a role right now and this... is a unique upside for assassinations...

## Changelog
:cl:
add: zombies can eat brains now
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
A real zombeing, and a real hero.

**Comment by OverlyGeneric** [comment]
https://www.youtube.com/watch?v=y44TUPr3zBc

**Comment by HomocidlePancakes** [comment]
Romerol zombies won’t be able to it brains

**Comment by ATH1909** [comment]
Oh nice, an actual non-fluff reason to intentionally become a krokodil zombie (this is an interaction that I am perfectly okay with/actively support, in case it wasn't clear).



> Romerol zombies won’t be able to eat brains. I an disappointed by this PR

Oh, right, they can't pick up the brains. Maybe add something to their zombie claws (but then armless zombies wouldn't be able to stick their faces into brains and eat them that way...)?

**Comment by tralezab** [comment]
krokodil addicts aren't technically zombies, so they cannot eat brains.

I can make the romerol claws prepare brains into food and bite them on attack, but I haven't checked if that's a good idea codewise yet

**Comment by ATH1909** [comment]
> krokodil addicts aren't technically zombies, so they cannot eat brains.
> 
> I can make the romerol claws prepare brains into food and bite them on attack, but I haven't checked if that's a good idea codewise yet
> 
> -- okay so since the black goo "controls" the brain it means zombies eating each other would end up ruining the convert. someone has to retheme the infectious zombies to turn their vital organ into the infection and make the brain vital, so zombies can eat the brains out of humans and still have them come back as a zombie.

If the old brain is eaten, the tumor becomes the new brain? Maybe let clawing a corpse allow you to rip that corpse's brain out and replace it with a fully-grown tumor?

**Comment by tralezab** [comment]
Maybe I'm a future pr I'd make the brain a decoy and the tumor vital (on zombification) and place the tumor in the chest instead of head

Krokodil addicts are not zombies just look like them, see the zombie species file

**Comment by IllotAFV** [comment]
Placing tumor in the chest makes dezombifying a very easy action to perform,you need to just cut victim's organs out,which is easier to do than cutting off the head,because it has lower damage threshold.

**Comment by tralezab** [comment]
yeah the entire thing is balance hell so i'm staying out of it

**Comment by MegaEmpirical** [comment]
Making romerol zombies be able to eat brains would technically be a nerf but it might work out due to changing the meta/dynamics. 

People simplely attacked by the zombies get a tumor that slowly kills them. Those that fail to flee, risk being zombie food and thus being removed from the round so they've incentive to flee.

Additionally there may be less zombies so the station may become less of a shit show than it usually does with zombies but will likely still have it rough. 

Since there would be less zombies, you could make eating brains heal them or give them a buff or something.

**Comment by ExcessiveUseOfCobblestone** [comment]
you can't eat brains as romerol zombie since your claws stop you from picking up hands.

A bad person could theoretically forcefeed it to you

**Pull request merged**
