### PR TITLE
adds a skeleton ghost for byond supporters

### PR DESCRIPTION
**Pull request by ghost**
ss 2015-02-01 at 10 58 25

### CODE REVIEW

**Comment by Deantwo** [comment]
I thought BYOND supporters had colored ghosts?
Then again that is what I remember from one or two years ago.

**Comment by Jalleo** [comment]
Yes @Deantwo but we also give them special sprite ghosts because why not?

**Comment by Deantwo** [comment]
Ok, was just making sure.

**Comment by paprka** [comment]
They have corgi and king ghosts as well

**Pull request merged**
