### PR TITLE
Ends the Sprite War

### PR DESCRIPTION
**Pull request by PKPenguin321**
While I have no strong opinion on sec sprites, they are for whatever reason a strong point of contention. There was no debate over them before #17280, but now there is. This PR is for the sake of removing unnecessary drama from the community and providing the option of "just going back" to those that disliked the changes made in #17280.

Sprites added to the .dmi files were left untouched, this PR just removes their actual applications to items.

### CODE REVIEW

**Comment by optimumtact** [comment]
NO, YOU'RE the ONE MAKING THIS A WAR, STOP

stop

**Comment by Iamgoofball** [comment]
i'm gonna make sec outfits be dispensed from a machine that lets the HoS pick the outfit theme for the round

**Comment by coiax** [comment]
Why are you trying to remove drama

HUGBOX

**Comment by GunHog** [comment]
Goof has the best idea, just as gang leaders choose the uniform for rest.

**Comment by PKPenguin321** [comment]
Goof's idea will never get to full fruition, because the keywords in this sentence are "goof" and "idea"

**Comment by Impisi** [comment]
#goofdidnothingwrong

**Comment by Nienhaus** [comment]
Isn't this the art directors job to handle?

**Comment by ExcessiveUseOfCobblestone** [comment]
> start as naked sec officer so you can roleplay the HoS' fantasy

:+1: goof

**Comment by TechnoAlchemisto** [comment]
On the topic of alternates: whatever you spawn wearing will be used 99% of the time because switching jumpsuits is a pain.

**Comment by MMMiracles** [comment]
what if we just remove sec jumpsuits all together

**Comment by Man-Shroom-** [comment]
SEC SHOULD BE RED EEEEEEEEEEE

**Comment by Supermichael777** [comment]
Make the hos have a theme picker that globally sets sprites. have emaging it set it to Nazi mode

**Comment by Bawhoppen** [comment]
@Supermichael777 thats a horrible idea

**Comment by Zilenan91** [comment]
It's just a fucking color who cares this much

**Comment by ChangelingRain** [comment]
# NO SPRITE WAR

**Comment by PKPenguin321** [comment]
Sprite tyranny confirmed

**Comment by Cheridan** [comment]
it doesn't matter

sec won't have to worry about jumpsuits soon

:speak_no_evil:

**Comment by YakumoChen** [comment]
sec should be red

**Comment by Mercenaryblue** [comment]
Sec should be red

**Comment by KorPhaeron** [comment]
oh it doesnt work nevermind

**Comment by PKPenguin321** [comment]
no no i can fix the conflict calm down

**Comment by Man-Shroom-** [comment]
my hands are practically rubbing themselves

**Comment by PKPenguin321** [comment]
ok so some changes:

by kor's request we're gonna keep the new vest sprites, other stuff is getting reverted though

**Comment by Man-Shroom-** [comment]
can you alter the in-hand/on the floor/whatever it is called sprite that looks like a black pear

**Comment by TechnoAlchemisto** [comment]
Adios greysec!

**Comment by PKPenguin321** [comment]
ok so turns out technoalchemist fucked everything up becaues they changed the icon state names in the .dmis and its fucking annoying as shit to fix so i'm giving up for now and letting iamgoofball do his weird thing, and when it inevitably fails i'll reopen this ok? bye bye

**Comment by Man-Shroom-** [comment]
eeeeeeeee

**Comment by TechnoAlchemisto** [comment]
Another victory! God Is Good!

**Pull request closed without merging**
