### PR TITLE
Cult runes now appear above blood and gibs

### PR DESCRIPTION
**Pull request by ChangelingRain**
I like being able to click things don't you

### CODE REVIEW

**Comment by Cyberboss** [comment]
>Joan touching bloodcult

It has begun

**Comment by Kromgar** [comment]
>Joan touching blood cult

Its a nerf.


Oh boy

**Comment by XDTM** [comment]
>Joan touching bloodcult

I'm just here for the blue planets

**Comment by Robustin** [comment]
I'll allow it 

:^)

**Comment by ChangelingRain** [comment]
>implying you have any power here

**Comment by Cyberboss** [comment]
I could be a maintainer. But, I respect myself too much to run this autism circus 😄

**Comment by KorPhaeron** [comment]
This is going to look weird

**Pull request merged**
