### PR TITLE
Removes Physically Obstructive Quirk

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Removes physically obstructive quirk. 

## Why It's Good For The Game

It puts other at more of a disadvantage than you. Its only used to grief. Because of this, its basically a free point you can use since it won't ever really effect you, just others around you. I'm open to the idea of making it cost nothing, or cost points tho. 

## Changelog
:cl: wesoda123555
del: physically obstructive quirk
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Just make it cost points, if people want to troll with it. I didn't expect the asteroid shuttle dilemma to be made into a quirk.

**Comment by wesoda25** [comment]
See I was gonna make it cost points but like I feel in general its just inviting a world of shitty traits. I don't think the trait system was a good idea in the first place, and making stuff which actually impacts others is just sort of lame.

**Comment by Teepeepee** [comment]
I enjoy this quirk a lot and I just use it to prevent losing prisoners by swapping places, I'd rather have it cost points than see it go
besides, you know you can just rest to slip below fatties, right?

**Comment by wesoda25** [comment]
> I enjoy this quirk a lot and I just use it to prevent losing prisoners by swapping places, I'd rather have it cost points than see it go

Hmm, I suppose if people actually find utility out of it it’d be best to make it costs points. Do you think it should cost 1 or 2 points?

**Comment by kriskog** [comment]
This perk gets me killed fairly often, since I am unable to swap places with people in a runaway situation. Thats not to mention the amount of times I get pushed, punched or whatever for being in the way. It's definitely not a positive quirk, all things told.

That said, I have also never seen it used to intentionally grief. People being obstructive so you cant pass them in maint isnt the same as them griefing you.

**Comment by ike709** [comment]
I _really_ hate this quirk.

**Comment by PKPenguin321** [comment]
FUCK people who run around the hallways on harm intent and FUCK this quirk for enabling and encouraging that awful behavior
👍👍👍👍👍

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
i ded plz nerf

**Comment by wesoda25** [comment]
> i ded plz nerf

I cant tell if this is ironic or not

**Comment by optimumtact** [comment]
the hardest choices require the strongest wills

**Pull request merged**
