### PR TITLE
[NO GBP] NumberInput patches

### LINKED ISSUE #81995: clicking and dragging to adjust number input on chem heater spams with too many actions
## Issue Summary

clicking and dragging the numerical input spams the server with requests and you receive a ton of 'Your previous action was ignored because you've done too many in a minute.' for a long period of time.

Before a recent change, we were able to click and drag upwards or downwards to adjust the temperature of chem heaters, thermo machines, etc. but It looks like there was a refactor done on the number input and that functionality may have been overlooked.

## Round ID:

[225506](https://scrubby.melonmesa.com/round/225506)

## Testmerges:

[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:

Click the input of a chem heater and drag upwards or downwards. You can try adjusting the value numerically after but it'll remain stuck until it is done with its fit

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
1. Removes event parameter (`e`) from `onChange()` & `onDrag()` for 2 reasons
    -  The event cannot be statically typed because it's called when you both either hit the enter key(it's a keyboard event) & during dragging (now it's a mouse event). Currently there is no code that depends on this object and even if it did type checking for which type of event is a pain so this isn't the right way to provide that data
    - The event is stale/has wrong data when dragging has started. This is because when dragging begins it calls `setInterval()` which keeps reusing the event object from that 1 time click and not the event data while dragging thus the data is stale and should be discarded & not passed to user

2. Removed `suppressFlickering` from Number Input. This was only used by Atmos monitoring console and the comment explaining why it was used was also wrong (there is no such asynchronous call in the back end). What this var did was difficult to understand anyway and after removing its only 1 use we can clean it up with no side effects.

3. Removed `updateRate`. Not used anywhere and a constant of 400ms should be sufficient for most purposes anyway

4. Fixes #81995. Dragging the Number Input will only send data to the back end if that value changes & not send the same value every 400ms. Simple logic (compare old value with the new) and yet efficient results, This applies when you hit enter or click outside of the field as well

5. You can once again drag your mouse anywhere in the window outside the number input field to vary the value by large amounts
 
## Changelog
:cl:
fix: number input dragging will only send payload to backend when its value changes, Same applies when you hit enter or click outside the field, the value must have changed to trigger the back end
fix: You can once again drag your mouse anywhere in the window outside the number input field to vary the value by large amounts
code: removed unnecessary variables(suppressFlickering, updateRate & event object param for handlers) from Number Input
/:cl:

### CODE REVIEW

**Comment by FlufflesTheDog** [comment]
this is not working in a pleasant way

https://github.com/tgstation/tgstation/assets/25628932/30910e0f-05fe-46ed-8f35-6cb4b7564cd9

**Comment by newfren** [comment]
does this mean you can't hold your mouse down over the temp while moving up and down to precisely control temperature during reactions?

**Comment by SyncIt21** [comment]
> does this mean you can't hold your mouse down over the temp while moving up and down to precisely control temperature during reactions?

You can, sorry i didn't realize the dragging was still imperfect. Anyway @FlufflesTheDog can you retest now, it should all working

**Comment by FlufflesTheDog** [comment]
Much better, but still has some weirdness. Some inputs will randomly lock up and not react to scrolls (If you go out of range? If you hover for too long?), and there's a small unresponsiveness; if you go very quickly, it'll select the text instead of scrolling

https://github.com/tgstation/tgstation/assets/25628932/1c7b091b-58f5-4438-a2a6-97436e0b7960

**Comment by SyncIt21** [comment]
> if you go very quickly, it'll select the text instead of scrolling

This is intended and was the old behavior. If you quickly press and release/move the mouse within a duration of 250ms then it is considered as a click and will go into edit mode. 

Holding the button longer than 250ms will be considered as dragging.

The delay is required to differentiate between when   the user wants to manually edit or drag so you can't be too quick with your mouse events.

> and there's a small unresponsiveness

As for slight unresponsives (like in chem heater) the temps change every process ticks I.e. 2 seconds and depends on your chem heater tier so it isn't the fault of the number input.

Overall I have restored all the code changes from before my NumberInput refactor PR to restore original behavior si there is nothing more for me to add back here. Just slow down your mouse movements by a little and it should be fine

**Comment by SyncIt21** [comment]
I think I improved drag responsiveness by a little. Do let me know if it helped

**Comment by FlufflesTheDog** [comment]
That's **much** better. Though the locking up thing is still sort of there. It seems to happen a ton more with the chem master than anything else, so not sure if it's strictly related?
Also, there's literally a single pixel per number on the chem master slider, so it's somewhat difficultl to use for anything other than 1 or 50

https://github.com/tgstation/tgstation/assets/25628932/afc8443a-58ae-4245-929c-278de07f5084

**Comment by RikuTheKiller** [comment]
The "locking up" thing is the main bug I figure.
Dragging itself somewhat works but sometimes it just decides to lock it.
Don't know what caused it but it certainly was not that way in the past.

**Comment by SyncIt21** [comment]
Ok this should finally fix everything. No more locking up of the value & stuff.

Can you please retest to verify?

**Comment by jlsnow301** [comment]
Bad juju

**Comment by jlsnow301** [comment]
I don't disagree with point 1, just update the component ref docs   to reflect this change pls

**Comment by FlufflesTheDog** [comment]
> Ok this should finally fix everything. No more locking up of the value & stuff.
> 
> Can you please retest to verify?

Seems solid now, haven't gotten any locking up so far.

**Pull request merged**
