### PR TITLE
Implements dynamic scaling for spies

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Implements dynamic scaling for spies. 

TL;DR On average less spawn, but there is a chance it scales up to add even more. 

Old

image

New

image

## Why It's Good For The Game

Maybe more dynamic rounds? Just for testing really

## Changelog

:cl: Melbert
qol: Spies may spawn in less numbers, but rarely may also spawn in more numbers. 
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
I think 10 spies, even for 100 is too much

**Comment by MrMelbert** [comment]
> I think 10 spies, even for 100 is too much

Is 5 spies for 50 players too much? It's the same percentage

**Comment by Sadboysuss** [comment]
> > I think 10 spies, even for 100 is too much
> 
> Is 5 spies for 50 players too much? It's the same percentage

in this case 5 spies seems ok but don't forget that sec slots don't go higher with more players, it's always 5 sec officer, 1 warden, 1 hos, 1 det and no more unless the HoP raises the slots, which is quite unlikely.

**Comment by Sadboysuss** [comment]
> > in this case 5 spies seems ok but don't forget that sec slots don't go higher with more players, it's always 5 sec officer, 1 warden, 1 hos, 1 det and no more unless the HoP raises the slots, which is quite unlikely.
> 
> I mean I don't know if some head admin has disabled it but we definitely have code to scale security officer job slots with population and our codebase is config-agnostic. Defaults to one for every 8 players, minimum of 5 and maximum of 12.

I've played on Manuel with over 40 players and it's always 5, so idk

**Comment by MrMelbert** [comment]
ok in testing seems pretty... ok. headmins can tweak it further if they want

**Comment by delaron** [comment]
I caution going much higher than 5. The pool of objectives being what it is might not functionally support 10 spies in a round. The degree of missing equipment can get annoyingly problematic when compared to security staffing and even engineering staff to build replacements. More than 5 likely would need a reduction in other threats generated.

**Pull request merged**
