### PR TITLE
Variety of Area Turf Sprite Fixes

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

These three sprites all show up next to each other:

image

So, since they were all ugly, off centered, non-standard, and maybe even a bit obtuse, I fixed all of them:

## Why It's Good For The Game

image

Tres bon!

## Changelog

:cl:
imageadd: Cytology Lab and two different variations of the Central Hall have had their sprites corrected into splendidly new ones.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
I misspelled Cytology, gimme a second

**Comment by Imaginos16** [comment]
It should be written "Cytology", not

"Cytolgy"

**Comment by Imaginos16** [comment]
Ah it changed, I’ll purse my lips then.

**Comment by san7890** [comment]
> Ah it changed, I’ll purse my lips then.

This puppy is going to merge conflict like five more times (unless I make more PRs) so best of luck

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
