### PR TITLE
Adds support for simple mobs changing intents

### PR DESCRIPTION
**Pull request by Core0verload**
This PR refactors action intent selectors to make them more flexible.

New mob var: `possible_a_intents`, defaults to `null`. 

When set to a list of possible intents, it allows said mob to use listed intents, both by selecting directly and in cycling mode. The var itself doesn't add intent selector to HUD, but "dexterous simple animal" HUD now supports it. It will display appropriate intent selector if the mob has `possible_a_intents` var at HUD creation.

### CODE REVIEW

**Comment by AnturK** [comment]
Would you mind adding on_vv update to ui so you can take away greytiders disarm rights.

**Comment by Core0verload** [comment]
When an intent is removed from list, it will be unselectable even without UI updates. If assistant was already on "disarm", you will have to change it to other intent manually.

There is no special icon for segmented selector with intents disabled, simple mobs who have less than 4 intents use non-segmented cycler.

**Comment by dannno** [comment]
it's about time

**Comment by optimumtact** [comment]
simple mobs are becoming fucking mobs reee stop it

**Comment by XDTM** [comment]
complicated mobs

**Pull request merged**
