### PR TITLE
TED and Chronosuit tweaks

### PR DESCRIPTION
**Pull request by JJRcop**
Changes based on feedback:
- TED time to kill has been halved (possibly controversial)
- TED now continually warps you back in if you manage to escape, instead of killing you
- TED field is no longer dense
- Chronosuit now does not carry items with you if they are outside the suit, which is the belt, back, and hands.
  - The TED is an exception

### CODE REVIEW

**Comment by WJohn** [comment]
I still feel as though this is the worst possible kind of antag. A stealthy, uncatchable killer that sits completely still to kill a victim over a long period of time with no way to yell for help or do anything but hope to be found. This is like wizard ei nath but worse.

**Comment by AlexCrimson** [comment]
Its an extremely rare antag that is spawned by admins. I dont think it really needs to be super balanced.

**Comment by GunHog** [comment]
I have never seen one live. I do not have a strong opinion because of this.

**Comment by JJRcop** [comment]
At the moment the TEA is not specifically defined as an antag. Also @AlexCrimson it may be admin spawn now, but I'd like to be able to prepare it to be implemented at some point in the future.

**Comment by JJRcop** [comment]
I don't think discussing the """antag""" is appropriate for this PR. I have a forum post where you can post suggestions on what kind of mode/event they should be, and generally give feedback on the concept in general.
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=2818

**Pull request merged**
