### PR TITLE
Mech melee attacks can now be blocked

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Mech melee attacks now will have a check_shields() check when attacking humans

## Why It's Good For The Game

Makes fighting mechs more epic and makes mech be less OP in annihilating cults and other antagonists dependent on melee weapons

## Changelog

:cl:
balance: You can now block mech melee attacks
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
mecha mounted melee weapons required to reenact your favourite MGR moments

**Comment by Serxule** [comment]
ok but like.... you cant block a massive hunk of metal going straight towards you, especially since they can break reinforced walls in a few hits

**Comment by LikesGreen** [comment]
What about making it that shield will block dmg and knocking you down but you will be still pushed back ? (can also break normal shield on hit since like Serxule say its a massive hunk of metal going on you with high speed, hard to just eat it all)

**Comment by githubuser4141** [comment]
> 

If it's logical for a Gygax to have less default armor (25-20-30) vs (30-30-30) then a security vest, and less IRL protection then a level 3A plate carrier it's logical for a mech's melee attack to be blocked by a shield, I guess

**Comment by necromanceranne** [comment]
> ok but like.... you cant block a massive hunk of metal going straight towards you, especially since they can break reinforced walls in a few hits

Look at their PFP, that should probably answer this question for you.

**Comment by blackdav123** [comment]
just wondering, were mech attacks going through things like shielded hardsuits or blade heretic's shield or is this only about block chance on items?

**Comment by SuperSlayer0** [comment]
> just wondering, were mech attacks going through things like shielded hardsuits or blade heretic's knife spell or is this only about block chance on items?

Mech attacks were going through shielded hardsuits and blade heretic knifes, this PR makes it work for items AND for them.

**Pull request closed without merging**
