### PR TITLE
Resprites escape pod Safes

### PR DESCRIPTION
**Pull request by CoffeeDragon16**
## About The Pull Request

Resprites the safes seen in escape pod lockers and DeltaStation. Has some fancy overlays that change based on the alert level and whether it's locked. The sprite was modeled off of the wall locker from Shiptest, which is taken from Whitesands, which is taken from Oasis, which is taken from Goon. Credits to Retlaw for making the most recent incarnation.
imageimageimage
wtqw0D1TVb

I changed the path name and name/description because I found them to be nondescript and outdated.

## Why It's Good For The Game

The safes on DeltaStation tend to go very underused. Most players don't know they exist, and I think it's because they have an old, crunchy sprite. Hopefully, something flashier will have people using the safes more. Hopefully, this will step towards alert level mattering more.

## Changelog

:cl:
imageadd: the alert-level locked safes seen in escape pods and on DeltaStation have been resprited
/:cl:

### CODE REVIEW

**Comment by Edelor68** [comment]
I like the new look, but I think it may be a bit big. 
Personally, I also think the slight from the top view makes it look a bit out of place because all other stuff that is on/in walls normally directly faces the camera, but that could just be me.

**Comment by CoffeeDragon16** [comment]
I tried condensing it in two pixels vertically, and I like it. I'll put that in.
image

The perspective is a compromise of sorts. It's kind of impossible to have side-mounted (wallened) sprites with this while keeping any information on it, so I thought I'd try to add a little perspective.

**Comment by 13spacemen** [comment]
It's way too big, I think the middle portion of the sprite should be removed. That would make it more similar to the current sprite's shape. And maybe change the color to grey/white/black/blue to fit in with the shuttle walls and console? Looks out of place

**Comment by CoffeeDragon16** [comment]
I've tried the shuttle color pallete a bit and can't settle on something I like more. You're welcome to download the .dmi and try. The point of the PR is to make it flashy and responsive to Alert Level so people will use them more on Red Alert, so the middle part can't be removed.

**Comment by CursedBirb** [comment]
You can always use a one line of color flashing(in respective alert color) instead of letters. That would also allow to reduce sprite as its way too big

**Comment by CoffeeDragon16** [comment]
image
How are we feeling about this? Personally I like it a lot less but I'm willing to compromise.

**Comment by 13spacemen** [comment]
👍 Much better than before, I still think that crimson/red color looks out of place though. But the shape and size is an improvement

**Comment by Farquaar** [comment]
Shouldn't the text be facing inward? Or am I misremembering the typical orientation for wall signs?

**Comment by CoffeeDragon16** [comment]
You're right, it should, but it's more important that you can read the current alert level. I tried a bit to see if I can figure out directionals, but I couldn't find anything that looked good while still having the alert display. The point is to make it feel less like alert level is just something in your chat box.

**Comment by CoffeeDragon16** [comment]
ah rats
i'll fix that later this week, having some difficulty with git

**Review by Twaticus — APPROVED** [review]

**Comment by optimumtact** [comment]
map conflict sorry

**Comment by DrDiasyl** [comment]
> The sprite was modeled off of the wall locker from Shiptest, which is taken from Whitesands, which is taken from Oasis, **which is taken from Goon.**

For a second I thought you wanted to return the goon folder, _we don't have it anymore, right?_

**Comment by DrDiasyl** [comment]
> You're right, it should, but it's more important that you can read the current alert level. I tried a bit to see if I can figure out directionals, but I couldn't find anything that looked good while still having the alert display. The point is to make it feel less like alert level is just something in your chat box.

Just make it a color of the alert level, not text.

**Comment by Ekaterina-von-Russland** [comment]
> Just make it a color of the alert level, not text.

But what colour is delta?

**Comment by DrDiasyl** [comment]
> > Just make it a color of the alert level, not text.
> 
> But what colour is delta?
> Perhaps flashing red like the disk pinpointer?

On fire alarms it's flashing red and yellow

**Comment by SuperNovaa41** [comment]
They do not have the time to fix this, they'll come back to it (i hope)

**Pull request closed without merging**
