### PR TITLE
Swaps boh and ooc confirm dialog button positions

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
image
This is the old one. Given that most dialog boxes like this have the OK / Cancel order, this one that also has custom button names is particularly scary. I have mistakenly hit the wrong one at least once, and I know others have as well.

Same for the "are you sure this is ooc" warning.

## Why It's Good For The Game
UI consistency

## Changelog
:cl: Skoglol
tweak: OOC and Boh bomb confirmation buttons swapped around, now in the OK / Cancel order.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Yep. Was there, did that. Racked up 7 kills and noone AH’d, thankfully.

**Comment by NoxVS** [comment]
Same thing applies to the OOC warning (Saying things like “;hello” in OOC). Have accidentally ick ocked because of that a couple times

**Comment by Tlaltecuhtli** [comment]
can you make the bottons colored, reading text is hard

**Comment by Ryll-Ryll** [comment]
Remember kids, after this gets merged you'll only have a few days to use "oh I was used to how they were before" as an excuse, so get your "accidents" in fast!

**Review by Cyberboss — APPROVED** [review]

**Comment by Ratvar** [comment]
Make it a config

**Comment by Ziiro** [comment]
Buttons definitely need colors

**Comment by NoxVS** [comment]
They should be colored but only if the colors make it more confusing. Red for yes, green for no.

**Comment by HomocidlePancakes** [comment]
Just color them both red.

**Comment by PKPenguin321** [comment]
Weren't they ordered this way so that the default selected button was the Cancel button?

**Comment by blessedmulligan** [comment]
> 
> 
> Weren't they ordered this way so that the default selected button was the Cancel button?

I think having the 'default' option be first is less important than having the prompt box be congruent with every other confirm/cancel prompt on the planet

**Comment by spessbandit** [comment]
can you force focus in byond

**Comment by Cyberboss** [comment]
No reason for this not to be consistent with the reset of the game. Messing with players' implicit bias like that would result in more accidents IMO.

**Pull request merged**
