### PR TITLE
Fixes a very broken mapping error

### PR DESCRIPTION
**Pull request by Red-byte3D**
## About The Pull Request
Fixes a fire extuingisher who has left his post
i do not know why he has done this
image
fixes this

## Why It's Good For The Game
literally  unplayable

## Changelog
:cl:
fix: fixes the misplaced fire extuingisher in the quiet room of delta.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
soul

**Comment by KathrinBailey** [comment]
image
you put it in the wall though :(

**Comment by cacogen** [comment]
SOUL

**Comment by LemonInTheDark** [comment]
god damn it cacogen

**Pull request merged**
