### PR TITLE
Revert "Makes Grills ZAP things when shit gets tossed at them."

### PR DESCRIPTION
**Pull request by lzimann**
Reverts tgstation/-tg-station#16487

Because it is stupid

### CODE REVIEW

**Comment by PKPenguin321** [comment]
LAME :-1: 
FUN REMOVAL

**Comment by Supermichael777** [comment]
i will not oppose this or support this.

**Comment by CosmicScientist** [comment]
:+1: Because I a salty sourpuss.

**Comment by bgobandit** [comment]
leo "clown" z strikes again

**Comment by MrStonedOne** [comment]
Postby PKPenguin321 » Today, 6:24 pm

>chemist on metastation
>pax comes into medbay
>starts bashing window to CMO office with fire extinguisher
>disarm him
>"Pax no"
>he pulls out another one
>disarm again
>and anotha one
>disarm again
>happens like 5 more times
>on the fifth one i whiff the disarm
>he hits the grill
>suddenly BZZAMBPPT
>i'm in crit, pax is dead
>realize what just happened
>laugh my ass off irl for like 5 minutes while a doctor fixes me up

**Comment by Supermichael777** [comment]
hold on i just realized that the shock() proc structures use has a different scaling then Tesla zap based on power. Its probably more leathal then intended

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Shadowlight213** [comment]
:-1: ways to die that aren't directly caused by an antag are great and lead to funny moments like what mso described.

**Comment by Durkel** [comment]
This is being used by people to griff, it's not fun to be instant crit because someone threw a paper at grille and killed four people.

**Comment by Iamgoofball** [comment]
Try banning the griefers.

**Comment by Cheridan** [comment]
so many thumbs pointing down~

**Comment by Zilenan91** [comment]
We should re-open this, the range on grilles is ridiculous and probably needs a nerf.

**Pull request closed without merging**
