### PR TITLE
[DNM] Removes Cat Ears/Tail mutant parts, adds Tattoos to the game as a replacement

### PR DESCRIPTION
**Pull request by Iamgoofball**
comes with 2 tattoos for legs and chest each

death to cattebeest snowflake

dont merge, right now the retarded bullshit for making the tattoos show up isn't working and it's pissing me off

there arent any fucking runtimes

it's granting the shit properly

the tattoos just dont render

the other mutant parts render tho

i want to murder things because of it

### CODE REVIEW

**Comment by Core0verload** [comment]
:-1: No. Cat people are perfect for annoying you.

**Comment by Iamgoofball** [comment]
@Core0verload fuck you they're going bye-bye and instead we get tattoos and stuff that will actually show up in a round other than bored admins

**Comment by Core0verload** [comment]
Stuff that's not even working because somebody can't into debug?

**Comment by Iamgoofball** [comment]
You try removing shitcode that's mixed with dna that's mixed with sprites that's mixed with save files and see how well you do, dipshit

**Comment by Incoming5643** [comment]
You repurposed a config option that defaults to off, make sure you're turning it on.

**Comment by Iamgoofball** [comment]
It is indeed on

**Comment by Shadowlight213** [comment]
:+1: death to snowflake

**Comment by Niknakflak** [comment]
I would rather have cat ears and tails than tattoos.  Tattoos are icky.

**Comment by optimumtact** [comment]
lol goof, you would get way more code in the game if you could restrain yourself

**Comment by Dorsisdwarf** [comment]
I wonder if we could use the mutant bodypart system in combination with genetics to make negative mutations better than "Now you're catatonic" or "Now you're on goonstation" or "Now you're epileptic, have fun spazzing around forver"

**Comment by Bawhoppen** [comment]
fuck you goof and your meme prs cause MUH PURITY

**Comment by WJohn** [comment]
Can you stop grudgecoding please, this is like the 3rd PR in a row.

**Comment by Iamgoofball** [comment]
Grudgecoding now means "pr I disagree with" right

**Comment by Bawhoppen** [comment]
'Cept this is most definitely grudgecoding for real.

**Comment by Jacquerel** [comment]
if you split this into two PRs for "tattoos" and "removes cat ears" I bet at least one of them would get merged 
(once it isn't broken)

**Comment by Shapsy** [comment]
le funny catbeest is valid meme is cancer and should stay in the cesspool of hippie

**Comment by Bawhoppen** [comment]
I propose we make catbeast playable race but keep them valid and rename into catMONSTER

**Comment by RemieRichards** [comment]
>Grudgecoding now means "pr I disagree with" right

No, @Iamgoofball grudgecoding is removing things JUST because you personally disagree with them, which has kind of been the theme with you lately.

If you're INSISTENT on removing the things you hate, atleast make them separate PRs.

**Comment by Miauw62** [comment]
deez memes

**Comment by Iamgoofball** [comment]
Why the fuck did you close this other than the "lol goofball meme pr"

I flat out can't fit tattoos and the other shit I intend to add on the menu  with catbeast there, and the snowflake required to work around it existing would be insanre.

**Comment by Bawhoppen** [comment]
dont add memetattoos then

**Comment by Saegrimr** [comment]
Need to bring back catgirl ERP specifically for how mad it gets goof

**Comment by Niknakflak** [comment]
The tattoos are pretty bad, I looked at the sprites and they shouldn't conflict in anyway with catbeasts, nice try goofy

**Comment by Iamgoofball** [comment]
@Niknakflak 
did you miss the part where I was talking about the menu

and yes the sprites are p. shit right now, I'm waiting on our only active spriter to stop spriting xenomorph asses and make some tattoos

**Comment by Ricotez** [comment]
you would have to edit a few HTML table tags here and there to change the layout of the table that builds the character setup window, but instead you completely rip out a config-locked feature spread over multiple files

**Comment by Aliannera** [comment]
nyaa

**Comment by PKPenguin321** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Pull request closed without merging**
