### PR TITLE
kills xenobio changelings once and for all

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
2024-02-20 19_47_05-Window

you may not use the consciousness transfer potion on headslugs
## Why It's Good For The Game

everytime a way to access headslugs is added someone makes a PR to fix this source of free antag powers probably after it gets abused to shit
with this PR you cant even get into a headslug via xenobio so no more PRs literally everytime something themed about changelings is touched

## Changelog
:cl:
balance: the consciousness transfer potion does not work on headslugs
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
From the PR you link in your 'why its good'

> The way that I've gone about this in particular avoids nerfing any of the more interesting interactions in xenobio as well. Something like the mind swap potion, or just gold slime core reactions as they currently work, could have gone away entirely. But this is probably the lesser evil.

Why does this change make Xenobiology any more interesting? Especially with the current requirement of a Changeling existing, headslugging, then being killed, why is it better to remove this interaction?

**Comment by mc-oofert** [comment]
the point moreso is so we dont open PRs removing sources of self-ling literally everytime something related to lings is added

**Comment by Admiral-Gigaton** [comment]
what if we just turned dead headslugs into the beakless kind, so powergaming assholes get just deserts? (joke)

**Comment by jughu** [comment]
he saw xenobiology spawning headslugs with xenobiology and making it sentient/mind transfering so he thought it was the perfect day to ruin the fun of the players(theres already a pr up that removes the mythril)

**Comment by ATH1909** [comment]
it should be noted that non-lings that possess headslugs and infect a corpse currently become a nerfed, half-power version of changelings, not full-power ones

**Comment by bigfatbananacyclops** [comment]
suggestion, why not just remove the entirety of xenobio instead? the effort put into it is not worth for the rewards. :)

**Comment by moocowswag** [comment]
At this point I suggest moving the consciousness transfer to a machine of some sort because its vastly inferior to sentience anyway.

Which you dont appear to be nerfing by the way according to the pr body.

**Comment by jughu** [comment]
in the long run its super situational for this scenario to happen but the time this PR was made just happened when people got headslug summoning with mythril

**Comment by Ghommie** [comment]
People have made several points against this PR, and I personally am against pre-emptively curbing little cheeky things that'll be on the chopping block at some point anyway. What's the fun of that? Other maints, feel free to reopen if you disagree and want this merged.

**Comment by mc-oofert** [comment]
atleast i guess i can spare 6 gbp

**Pull request closed without merging**
