### PR TITLE
NEW JOB: Security Dispatch (and some Security drip)

### PR DESCRIPTION
**Pull request by DrDiasyl**
# DESIGN DOC - https://hackmd.io/@drtuxedo/BJw3A6rI6 READ IT, ALL OF THE INFO IS HERE
## About The Pull Request
Adds new Security department job - Security Dispatch. (Also new Security clothing piece)
Dispatch

Security Dispatcher is a new security job that will enhance teamwork by delegating part of the Warden’s duties, which are usually overlooked (even by the HoS), to a new role specifically designed for this purpose. This entails functioning as a dispatcher, coordinating officers, reporting crimes, and monitoring sensors and cameras to provide auxiliary support to officers.

Has access smaller than of the Officer, no baton, no access to lockers.

<details>
  <summary>The screenshots of his office across all maps</summary>

- TramStation
image
- NorthStar
image
- MetaStation
image
- IceBox
image
- DeltaStation
image
- BirdShot
image

</details>

It also adds a Security high-vis jacket. Has a unique variation for the Security Dispatch.
<details>
  <summary>New drip</summary>

Security Jacket (light)

</details>

# **[READ MORE IN DESIGN DOCUMENT](https://hackmd.io/@drtuxedo/BJw3A6rI6)**
## Why It's Good For The Game
The primary responsibilities of the Security Dispatcher include:
- Coordinating Security Officers in response to distress calls, incidents, and crime reports.
- Keeping Security Officers informed about situations through camera feeds and suit sensors.
- Facilitating communication among Security Officers and between departments (e.g., contacting Paramedics, Engineers, etc.).
- Accepting crime reports from crew members.

These responsibilities were previously secondary duties of the Warden, but they often get neglected due to the Warden being busier with their primary task of protecting the Brig and processing prisoners. The HoS is also occupied with preventing officers from turning into “Shitcurity,” dealing with conflicts within the command, and directly involving themselves in all the fighting, making them too busy to be bothered. Consequently, this often neglected responsibility now has a dedicated job to ensure it is not overlooked when someone takes on the role.

Dispatch would increase teamwork in the Security department.

# **[READ MORE IN DESIGN DOCUMENT](https://hackmd.io/@drtuxedo/BJw3A6rI6)**
## Changelog
:cl:
add: New Security job: Security Dispatch! Tasked with coordinating Security on distress calls, and monitoring situations with cameras and sensors
add: Security now has their unique high-vis jacket in their wardrobe
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
This is just the warden's job, making it a new job won't make it overlooked any less

**Comment by DrDiasyl** [comment]
> This is just the warden's job, making it a new job won't make it overlooked any less

Just Warden has a range of responsibilities that I have listed, mostly related to processing criminals and defending Brig which are more important than the dispatching.
By having a dedicated job to it whose sole job is to dispatch - there will be dispatching.

**Comment by EuSouAFazer** [comment]
Really cool idea!

**Comment by xzero314** [comment]
> This is just the warden's job, making it a new job won't make it overlooked any less

I feel the same way. I have a decent amount of Warden shifts under my belt and I very rarely find myself too busy for cams. This is the Wardens main thing when they aren't handling prisoners. 

All I foresee with this is wardens going ssd from boredom of having no job and sec comms bloat. 

If the situation really calls for it, just order a sec officer or the detective to handle comms overwatch while warden is brigging people.

The average Warden shift dosent involve a-lot of action. The "Eye in the sky" moments of calling people out on camms or sensors are usually the most interesting thing to happen to you

**Comment by DrDiasyl** [comment]
> > This is just the warden's job, making it a new job won't make it overlooked any less
> 
> I feel the same way. I have a decent amount of Warden shifts under my belt and I very rarely find myself too busy for cams. This is the Wardens main thing when they aren't handling prisoners.
> 
> All I foresee with this is wardens going ssd from boredom of having no job and sec comms bloat.
> 
> If the situation really calls for it, just order a sec officer or the detective to handle comms overwatch while warden is brigging people.
> 
> The average Warden shift dosent involve a-lot of action. The "Eye in the sky" moments of calling people out on camms or sensors are usually the most interesting thing to happen to you

As non-goal 1 of my Design Doc states, the Warden still retains his authority and all of his consoles.
If the Warden wants to he can do the Dispatch job, talk out with the Dispatcher and take certain Officers under your order. But this is only happening on rather calm/lame shifts.

If it's a high-threat shift Warden will always have something to do from his main duties of processing criminals and defending Brig, so extra hands like Dispatcher would be handy.

**Comment by distributivgesetz** [comment]
Spitballing an idea since people are arguing about dispatch job content...

What if security dispatch was an antag-restricted service role - like an emergency dispatch - that had radio access to security, engineering and medical, whose job is to keep an eye out for *any* station emergencies and keep departments informed?

**Comment by DrDiasyl** [comment]
> Spitballing an idea since people are arguing about dispatch job content...
> 
> What if security dispatch was an antag-restricted service role - like an emergency dispatch - that had radio access to security, engineering and medical, whose job is to keep an eye out for *any* station emergencies and keep departments informed?
> 
> Emergent team coordination in emergencies in this game is the best fucking shit in the world imo and I wish there was more of it. Not only in security, but in other departments as well

Very good idea! 
I will write this down in the alternatives section of my design doc

**Comment by HerCoyote23** [comment]
> Spitballing an idea since people are arguing about dispatch job content...
> 
> What if security dispatch was an antag-restricted service role - like an emergency dispatch - that had radio access to security, engineering and medical, whose job is to keep an eye out for _any_ station emergencies and keep departments informed?
> 
> Emergent team coordination in emergencies in this game is the best fucking shit in the world imo and I wish there was more of it. Not only in security, but in other departments as well

I like this a lot more than having just sec dispatch. Though I think sec dispatch would be cool, it does run into some conflict with the warden/too many commanders in security/too little to do as a role. A general dispatcher would have enough to do, and wouldn't really conflict with anyone else's job. My only concern would be that they might overlap with the AI a bit.

**Comment by distributivgesetz** [comment]
> My only concern would be that they might overlap with the AI a bit.

AIs are busy people, I don't think they would someone taking the load off their shoulder every now and then

**Comment by NoeSilent2** [comment]
Before the rest of the big text block I made, and in support of what some other people before me said, I think it'd be nice to have dispatch get medical and even engineering comms, and perhaps not be so security specific as to be a little less direct with stepping on wardens toes. Differentiation is valuable-- if you're going to cut a piece off a finished painting, might as well add some new color to make it something special. Now, on to the rest.

I am personally a fan of trying this out.
This gives great opportunities for new players to ease into the functions of more mechanically / socially complex parts of the security (or depending on the changes, maybe some other) department.
Additionally, it seems like a pretty fun roleplay role to take up whenever I'm too tired to be on my toes the entire time but still want to hang out and be helpful.
I don't believe it'll take a whole lot away from the warden or AI: the players who play warden exclusively watching sensors and cameras are wardens who would do great in the dispatcher role! Wardens already have plenty of stuff to do, after all they are the second in command of the entire security team, single overseer of that entire departmental space, and handler of all captured criminals. If you come into the round wanting to watch cams/sensors + chat with people and not really interested in processing criminals or managing armory, that's perfectly reasonable and this job would be great for that, or if that's not your sole interest and you still want to process criminals, I bet you can still do both on warden without much trouble. AI is just simply too busy to fully devote themselves to overseeing the crew and won't complain with a little help here and there.

From a crew sided approach this is beneficial too. If you're experiencing an emergency that needs security present, the station is falling apart and you can't do your job because of it, or somebody is dying and you can't help them yourself, its nice to have a role who is always around to listen and keep the round on track rather than mixed up between a whole lot of other time sensitive tasks. It'll hopefully support more actual roleplay interactions between the crew and emergency departments (security, medical, engineering).

And (I know I mentioned this earlier but it bears saying like one more time), if the warden or AI or whatnot has absolutely nothing to do, they can still cruise around their equipment and help out with surveillance in the meantime. One set of eyes is only bolstered by two, and then once that criminal or whatever you've been calling out on radio gets dealt with and- say- the warden goes to process them, there isn't an overwhelming need for the warden to get back to their console ASAP-- they can spend time with that criminal getting everything sorted out rather than rushing to stick their eyes back on the sensors.

To conclude, its definitely not a breathtaking cure-all role, its just a low stress spot you can hang out in when you don't want to be in the rat race so much. If you're a warden and you feel like the dispatch is stealing your thunder, just talk to them and work something out between the two of you, or next round play dispatch instead. Its neat enough to try out, and with some tweaks could be a pretty fun role even for people who don't normally like playing security.

Or, this could all be wrong. Can't say I have any experience playing /tg/ with this role seeing as it hasn't been testmerged yet.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
this just seems... really boring? you stare at cameras like an AI and you call out over radio? so you just take the "do in downtime" job of the warden leaving the warden with nothing to do in quiet moments while creating basically a second lawyer except they can't even be an antagonist

**Comment by SimplySmiley123** [comment]
Honestly would love to see this in-game.
Warden's from my personal experience gets way too much stuff to handle as a sole man, or rather too much ground to keep an eye on alone, would be nice to have a role dedicated to helping you out that signed up for it instead of bothering an officer that likely doesn't care about brig at all and just wants to smash the skull of whoever's valid enough.
Maybe this would even allow for more construction projects in brig.

**Comment by HoodMilk** [comment]
Like people were saying before, a med/sci/sec "emergency dispatch" sounds a lot more interesting as a job.

**Comment by optimumtact** [comment]
this sounds like an MRP job that escaped from containment somehow.

**Comment by SomeoneYouProbablyKnow** [comment]
This is a neat job,  but..

1) How is the dispatcher gonna make themselves seen in the chaos that is sec radio? Maybe give em a special font Megaphone? Else no one is gonna listen to them.

2) Very often they are going to be overshadowed by the AI. I think you should promote the dispatcher using the records more. Make bounty posters, figure out who went missing off sensors etc. Idk how you'd mechanically nudge people towards that tho.

3) I dislike how many wardens already hug the sensors console looking for a sniff of valid. But that's more an issue with the whole suit sensor system (and how it has no delay whatsoever).
The camera interface is also ass but that's out of scope so who cares.

Also, there's nothing wrong with a dispatcher taking up arms when shit really hits the fan. It's not like they get anything that can make them into an Officer+. Gamers will just not roll for this job. 
And if you really gut the tools this job gets it'll become customary to get stuff from the warden every shift.

I think General Dispatch is also a good direction for this job.

**Comment by SomeoneYouProbablyKnow** [comment]
> this sounds like an MRP job that escaped from containment somehow.

I thought you were always saying we are an MRP codebase? Or am i thinking of someone else?

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Move the vent from underneath the computer here
image

Rotate these shutter's dir to face outwards
image

Rotate these shutter's dirs to face left
image

(Nittiest of picks) Put two caution sprites underneath this door like every other door on Delta
image

Fix this wall mount stacking
image

Fix this wall mount stacking
image

**Comment by optimumtact** [comment]
> I thought you were always saying we are an MRP codebase? Or am i thinking of someone else?

I didnt' say where it escaped containment from

**Review by MrMelbert — COMMENTED** [review]
For opinions, the only one I don't really like is Metastation's, not only is it rather far from the front but it also makes it a lot harder to break into the Armory from space. 

Delta's can probably afford to reclaim some space from sec-dorms maint. 

Also don't forget to leave some decorations on empty tables - stuff like clipboards, folders, lamps, maybe a space law book or action figure (did you add a Dispatch action figure?).

**Comment by Fikou** [comment]
i dont think the warden is ever really overwhelmed to the point where his job needs to be split up into warden, dispatch (and brig medic, though thats not in this pr). dispatches are usually done in your spare time, when you dealt with prisoners and provides some downtime that antags can take advantage of. usually if the warden needs to protect the brig youve come to a point where all of security is focused on the brig and they will not answer dispatches to other places really

**Comment by ATH1909** [comment]
this is literally the warden's job description, barring handling prisoners, which can already be delegated to the HoS or the officers bringing those prisoners in if the warden is overwhelmed.

this also has a huge overlap with the AI's job, who does it better in literally every way (better camera monitoring, access to all comms channels, bigger text, better control over secbots, better defenses for your squishy body, ability to directly intervene in the crimes you're witnessing).

**Comment by SomeoneYouProbablyKnow** [comment]
> this is literally the warden's job description,

We wrote the job description, we made it the fuck up.

**Comment by DaCoolBoss** [comment]
You want to stop dispatchers from acting like security officers and having officer level equipment, and honestly I don't see why. It's not like detective where there's some unique gear and gameplay going on, any security officer can act as a dispatcher from pretty much any unvandalised departmental sec outpost. The wiki even recommends seccies combing through camera consoles for intel when there's nothing urgent that needs dealt with.

It's a big problem in my eyes if someone wants to join a game as a member of the security team, and they have to choose between Officer or Officer But Worse. Dispatchers NEED some kind of special sauce so it's not just half of another job.

**Comment by projectkepler-ru** [comment]
@DrDiasyl do you have a dispatch officer figure yet? if not I'll make one ^^

**Comment by JupiterJaeden** [comment]
I'd be fine with a test merge to try it, but not really a huge fan. The HOS should be dispatching officers and just personally that is a lot of the fun I have when playing HOS - radioing and dispatching officers in the field. I would hate to have to clash with a 'dispatcher' for that part of the job when playing HOS. Although on the flipside I could still see it being useful, with the right player that knows how to cooperate with a chatty HOS like myself.

**Comment by Mothblocks** [comment]
> > This is just the warden's job, making it a new job won't make it overlooked any less
> 
> Just Warden has a range of responsibilities that I have listed, mostly related to processing criminals and defending Brig which are more important than the dispatching. (Something I already told in the design doc) By having a dedicated job to it whose sole job is to dispatch - there will be dispatching.

> Rendering the Warden obsolete or incapable of performing their duties. The Security Dispatcher has lower access than even a Security Officer (limited to skeleton crew shifts), specifically preventing them from assuming the Warden’s role of protecting the brig. The Warden’s consoles remain untouched, and they can still undertake the duties of a Dispatcher if they choose to do so.

Processing criminals and defending the brig is **not** enough of a job for warden. Wardens have the massive disadvantage of being pseudo-required to stay in the brig, cutting them off from an entire facet of interaction. Trying to move one of their very few opportunities to engage with the rest of the station at large gets a massive :-1: from me.

> Address the issue of dispatch responsibilities being overlooked due to the Warden’s constant influx of criminals and tiders, and the HoS being occupied with confrontations and clashes. Instead, establish a dedicated role for dispatch duties.

I don't know if I'm just blind but I've been playing Sybil for the past month and have just not seen this "constant influx" other than on actual revs rounds.

Looking through your design doc, I also disagree with all your alternatives as they still all in essence take away from the gameplay of the sole warden, whom I don't believe is overwhelmed. If your goal is to "enhance teamwork within security", I think it's a lot smarter to make the Warden themselves better suited for it. I always wanted to try out the ideas of body cameras on officers that the warden can see through in order to spread information that way, for example.

I'm leaving this up for a bit because I think the discussion on this PR is interesting and would like to see more ideas from people on how they would improve communication between security.

**Comment by GuillaumePrata** [comment]
We have 2.5 leadership roles at Security (HoS/Warden and a sliver of the Captain)

It feels really weird to add a new role focused on coordination instead of expanding on the ones we have already.
Specially the HoS, Warden and Captain have their other duties, but the HoS is often left to be a frontline officer with better gear as there isn't any unique mechanic to the job outside of the authority it holds.

**Comment by EricZilla** [comment]
Honestly I'd say like, why not make this a sec officer department option? When you choose your preferred secondary department, you could just pick "Dispatch" and get the neat alt outfit, keep the cool little side nook in sec for when random officers wanna do this.

I feel like the cargo operates this best, there are a bunch of small jobs you can choose to do as a cargo tech, with some clothing options to solidify yourself as the mailman or etc

**Comment by projectkepler-ru** [comment]
> Honestly I'd say like, why not make this a sec officer department option? When you choose your preferred secondary department, you could just pick "Dispatch" and get the neat alt outfit, keep the cool little side nook in sec for when random officers wanna do this.
> 
> I feel like the cargo operates this best, there are a bunch of small jobs you can choose to do as a cargo tech, with some clothing options to solidify yourself as the mailman or etc



This might be the best way to do it
@DrDiasyl  since that way you still get what you wanna do without having to bloat anything and would be addressing the lack of dispatch issue

**Comment by DrDiasyl** [comment]
Okay as Mothblocks bricked this PR, I will make a new one.

Basically make just a Dispatch job which is part of Service department tasking with coordinating all of the emergency services.
And it will be using the gimmick job system, so it will only be seen occasionally, and also that we lack more gimmick jobs.

**Comment by MrDoomBringer** [comment]
Give this role an actual innate feature or implant or ID-locked-console that makes it different from anyone bothering to access a cam console/sensors. 

Maybe a cool UI that shows locations and health of security officers overlaid on a map of the station. Maybe something that allows you to ping a location, with an arrow pointing to it appearing on all secHUD glasses. Something, anything, that makes this person a high value target for antags, rather than just a shittier security officer.

**Comment by DrDiasyl** [comment]
> Why does the Dispatcher, a role defined by not going out and doing things, have a special unique hi-vis jacket?

Because I needed a excuse to make a security high-vis vest.

Actually this entire PR was made just for the jacket frfr

**Comment by Dorsisdwarf** [comment]
>  I always wanted to try out the ideas of body cameras on officers that the warden can see through in order to spread information that way, for example.

Didn't we use to have this for sec officers? I could swear that helmet cams were a thing for a while, but got canned because perfect overwatch of the sec team was REALLY strong.

**Comment by wesoda25** [comment]
As warden I too often have too much downtime and typically have to search for ways to keep the round engaging, big -1 from me.

**Pull request closed without merging**
