### PR TITLE
Updated MetaStation.v40C to MetaStation.v40D.dmm, added MetaStation/z3.dmm

### PR DESCRIPTION
**Pull request by Metacide**
-Added a new NT recovery ship in deep space, which replaces most functionality of the white ship which is now an immobile derelict. The new recovery ship is stocked with some helpful but relatively innocuous gear, and has machine frames with some machine boards allowing it to be more easily decked out with useful machinery for, as an example, colonising the derelict. The retro laser has been moved here as well.
-Added a firing range to research, made robotics/mech bay more compact
-Added protective gear and some more tables to the experimentation lab
-Added an extra airlock to space just east of the holodeck in maint
-Added more fruit variety to the garden
-Adjusted area designations so that emergency maintenance access works better
-Adjusted carp spawns - they're fewer and further away from the station
-Adjusted layout of xenobiology to make it look a little better
-Fixed missing disposals pipe and scrubber outlet in virology
-Fixed missing privacy shutters in medbay examination rooms
-Fixed missing target control in security's firing range
-Fixed missing tables in telecomms
-Fixed missing law office shutters
-Fixed extra glass stack on floor of engineering
-Fixed some cargo conveyor units being assigned to the wrong control stick
-Fixed extra corner pipe under manifold in the incinerator room
-Fixed invisible chairs at the arrivals lounge
-Fixed left cryo tube appearing under the window behind it when open
-Changed access level of space airlock adjacent to security pod to security only
-Includes soda and booze dispenser additions to the bar, courtesy of Mandurrrh
-Includes modifiable bar sign, also courtesy of Mandurrrh

[Full Station Image](https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-02-23%2016-22%20MSv40D%20Full.png)
[Recovery Ship Image](https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-02-23%2016-27%20Recovery%20Ship.png)
[Feedback Thread](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=399)
[Wiki Page](http://tgstation13.org/wiki/index.php/MetaStation)

Dropbox seems down at the moment, so have some direct uploads instead:
15-02-23 16-22 msv40d full
15-02-23 16-27 recovery ship

### CODE REVIEW

**Comment by Miauw62** [comment]
The recovery ship is far too tidy imo, it should feature some more broken walls and such.
Anyway, that's for later.

**Comment by Metacide** [comment]
Thanks very much :+1: 

Will see what I can do with the shuttle in the next update next weekend.

**Comment by Dorsisdwarf** [comment]
Broken shuttle walls really don't work, especially since you can't rebuild walls on shuttles now.

**Comment by Metacide** [comment]
Tried to make a few of the ship doors start welded, but couldn't get the icons to work. And building tables or racks or chairs on the ship doesn't work, so I can't leave them partially constructed. Lots of dirt was the best I could really do - I'm open to any ideas people have.

**Comment by ClumsyAlcoholic** [comment]
Gigant spider cobwebs woud be nice, and maybe a few remains and cocoons.

**Comment by Metacide** [comment]
Spiders sound good, will see what I can do.  Could certainly add some fine supplies to botany, and a cigar somewhere. The ship should be good for alcohol, though - it's got a built Booze-O-Mat already.

**Comment by ClumsyAlcoholic** [comment]
Nice.

**Comment by Dark-Star88** [comment]
It is YEARS past time that something was done to update or replace the White Ship. The wiki hasn't even been updated since sometime way back it was indeed possible to repair the thing and fly it to the station. I made it there exactly once in weeks of trying on various servers, and there was jack to do there.

It does indeed look too neat for a supposedly abandoned ship - we need buildable shuttle walls IMHO - but that can be addressed. How about locking some of the gear in crates requiring high-level access?

**Comment by Miauw62** [comment]
Shuttle walls are supposed to be indestructible (except by singulo), so you
obviously can't build them either. Letting you expand the white ship would
lead to disappointment as your shuttle walls are cut off beyond a certain
point, because that's how the new shuttle system works.

**Pull request merged**
