### PR TITLE
Adds fun 👻 to deadchat

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Added fun emojis to deadchat! Now you can spam 🖕 about that traitor that killed you!
/:cl:

👻👻👻👻👻👻👻👻

btw i made these separate PRs in case u want 👻👻 in one but not the other

### CODE REVIEW

**Comment by praisenarsie** [comment]
i quote this from the asay pr

> besides this emoji thing looks better for something like our downstreams.

**Comment by Iamgoofball** [comment]
You realize we already have emojis right praise?

**Comment by praisenarsie** [comment]
@Iamgoofball yeah ik i just didn't phrase my sentence well

**Comment by deathride58** [comment]
Merge this PR asap you lithium-filled water bottles

**Comment by lzimann** [comment]
no thanks

**Pull request closed without merging**
