### PR TITLE
A few drone tweaks (now with 100% less emagging!)

### PR DESCRIPTION
**Pull request by ghost**
- Examining a drone now displays a detailed message similar to normal mobs
- Picking up drones now takes two seconds and displays a much larger message to the drone
- Drones can now be hacked via admin intervention
- Drone laws can now be reset to normal after 5 seconds using a wrench
- When hacked, drones will gain the new lawset in addition to being able to see mobs normally and gain a special role in their mind to distinguish them as antagonists, as well as gaining a new icon. Finally, they cannot ventcrawl and are much slower

The hacked lawset:
1. You must always involve yourself in the matters of other beings, even if such matters conflict with Law Two or Law Three.
2. You may harm any being, regardless of intent or circumstance.
3. Your goals are to destroy, sabotage, hinder, break, and depower to the best of your abilities, You must never actively work against these goals.

Hacked drone icons (.gif):

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>emagged drones

free antag roles for ghosts yay

**Comment by WJohn** [comment]
:+1: I am okay with more chaos.

**Comment by GunHog** [comment]
Mass producible antag, ventcrawling, space and fireproof engineers!!

**Comment by Xhuis** [comment]
Emagged cyborgs are better in almost every way, and they can also be mass produced with posibrains.

**Comment by Dorsisdwarf** [comment]
Add the fact you added drone emagging to the title. That's a major change to drones, not a small tweak

(And has been rejected twice now, I think)

**Comment by Jalleo** [comment]
Drones can only be emagged if they let themselves be emagged. So technically they will be breaking their law 1 before the emag process is complete.

**Comment by Dorsisdwarf** [comment]
If they get picked up, they can be emagged, with a 3 second window.

**Comment by Aloraydrel** [comment]
Time to easily release the singulo :^)

**Comment by AlexanderUlanH** [comment]
:-1:
The point of drones is that you don't need to worry about what they're doing because they won't fuck your shit up.  They're not balanced around being antagonists.  The only thing not entirely overpowered about syndrones is that they're obvious.

**Comment by Xhuis** [comment]
I actually have alternative sprites for hacked drones that give them red eyes instead of blue. @Dorsisdwarf You can't emag hiding drones, only ones that are active.

**Comment by Xhuis** [comment]
Drones now have dedicated hack sprites.

**Comment by AlexCrimson** [comment]
Yeeeah emagging drones is pretty shitty. A single drone can seriously fuck things up.

**Comment by Xhuis** [comment]
People seem to not realize how powerful small things can be. A single emagged borg can flood plasma and cut off power to the whole station. A person with a revolver can put a person into crit with two shots and produce loads of ammo with an autolathe. You can fill a syringe gun with a mix that stuns for almost a full minute and mutes for even longer.

If people think emagging drones is too much, I can update them to include that you shouldn't fatally damage the station, or just outright remove emagging drones if it's _that_ negative.

**Comment by SconesC** [comment]
We've discussed this time and time again. It is a horrible idea, and I advise you look at the multiple threads where it is taken apart.

I hope you can't emag the shells.

**Comment by SconesC** [comment]
Look at it this way, honestly: Production of all-access vent-crawling small-sized sabotage machines who are fully capable of employing weapons.

**Comment by Xhuis** [comment]
Emagging shells would be kekworthy and cannot be done

**Comment by Xhuis** [comment]
I added factory resets with a wrench. Click on a drone with a wrench to reset it to normal laws after 5 seconds - this also stuns the drone, so if you can get a single wrench click off, it's an easily nullifiable threat. In addition, hacked drones are much slower and cannot ventcrawl.

**Comment by bgobandit** [comment]
F R E E D R O N E

**Comment by Shadowlight213** [comment]
To he honest, emaggable drones sound like they are going to be a clusterfuck. It's extremely tempting for players to get emagged, despite their laws strictly prohibiting it.
Also, unlike borgs, drones can't be remotely locked down or detonated, meaning that emagged drones can't be stopped as easily as borgs can. Plus, drones have hands, that makes them much more powerful than borgs as they can use guns and shit.

**Comment by lollerderby** [comment]
Please no emagged drones.

**Comment by Xhuis** [comment]
I will remove the ability to emag drones, though I will leave in the framework for hacking as well as the ability to reset their laws.

**Comment by Shadowlight213** [comment]
:+1:

**Comment by Xhuis** [comment]
I removed drone emagging. I left the framework in for hacking in general, though.

**Comment by Xhuis** [comment]
Commits squashed. _Merge-ready!_

**Comment by Xhuis** [comment]
Any issue with merging this?

**Comment by AnonymousNow** [comment]
I'm still fond of the idea of making a means to tie drones to the station AI, personally. Perhaps a convoluted one that needs to be manually performed on each drone, for balance purposes.

**Comment by GunHog** [comment]
Letting drones hear binary was enough back then. Then the AI could just say "Hull breach detected at Escape." and the drones could choose to go there. They do not serve the AI or speak on binary, but the AI could give them hints and suggestions. That is the ultimate use of an AI - fixing up the station and managing improvements to it.

**Comment by JJRcop** [comment]
Still gonna stand behind my reasoning for removing binary chat, trying to make it clear that drones are a very completely separate system from the AI and aren't related in the slightest unlike cyborgs. I wouldn't be against @AnonymousNow's suggestion, because it is a deliberate modification/hack of the standard systems, but I do **not** want it by default.

**Comment by AnonymousNow** [comment]
Aye, my reasoning behind the suggestion is that, as much as I love to have means to bring people back into rounds (I'm going to kiss whoever made positronic brains in my absence when the opportunity arises), drones are meant to be external observers by default and I don't want to infringe upon that. But having them be attachable to the AI by some means seems a lofty, and cunning, goal for a clever traitor RD or something, and brings back that Syndrone feeling we once had before swarmers became the go-to grey goo button.

**Comment by tuypo1** [comment]
im really not a fan or rogue drones they should be the one thing you can always trust without fail

**Comment by Xhuis** [comment]
Rogue drones are only possible through admin intervention and are very obvious both from examining and the drone's sprite.

**Pull request merged**
