### PR TITLE
Changes contribution guidelines to suggest adding spaces in-between bitwise operators

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Explain

**Comment by MrStonedOne** [comment]
How is `if (flags & DEFINE)` better then `if (flags & DEFINE)`?

**Comment by optimumtact** [comment]
`if(flags & DEFINE)` is the one true way

**Comment by nicbn** [comment]
Yep, bitwise operators should be typed just like arithmetical operators

**Comment by AnturK** [comment]
Another preference war, oh boy. <sup><sup>I agree with this PR</sup></sup>

**Comment by RemieRichards** [comment]
I agree with ```&``` but disagree with ```|```, for example, ```NORTH|WEST``` is the union of ```NORTH``` and ```WEST```, I like that it joins them together, same for when it's used with lists ```list_a|list_b``` it better symbolises that they are now one value.

**Comment by RemieRichards** [comment]
Also I doubt this will work out so just move that line to the "Enforced / Not Enforced" section (like ```if() if ()```)

**Comment by MrStonedOne** [comment]
honestly, we could have both ways.

space for checking, no space for assignment, or just exempt |

**Comment by ChangelingRain** [comment]
Yeah, I agree with Remie here, it should be `NORTH|EAST` and `NORTH & NORTHEAST`

**Comment by ohnopigeons** [comment]
> different spacing rules for two very closely related bitwise functions

This feels wrong
I presume `^` gets lumped in with `&`?

**Comment by ChangelingRain** [comment]
They're related, but their functions are vastly different.
And I don't use ^ enough to care which

**Comment by ohnopigeons** [comment]
The arithmetic equivalent is `+` and `-`, analogy wise this feels similar to saying to add spaces between `-` operands but spacing is optional for `+`

**Comment by optimumtact** [comment]
you could leave it as it is where nobody cares

**Pull request closed without merging**
