### PR TITLE
A watcher sinew Skirt/MANLY KILT accessory

### PR DESCRIPTION
**Pull request by bluetshirtguy**
### About The Pull Request
About The Pull Request
A kilt designed out of monster bits, pretty hardcore right?
It has the same protection as the other tribal accessories. crafted using 2 watcher sinew and one bones. The skirt will show over any clothing or suit. 

### Why It's Good For The Game
There are players that wear skirts often and some of them play shaft miner so giving them the option to wear a skirt(KILT) without having to take of their suits sounded like a good fashionable addition. 

### CHANGELOG
🆑 cybersaber101
add: A new accessory the skilt
imageadd: sprite and icons for skilt
/🆑
Picture of it in game.
https://imgur.com/fb5EXEu

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
As a great American once said:
“SCOTLAND IS NOT A REAL COUNTRY. YOU ARE JUST AN ENGLISHMAN IN A SKIRT!”

**Comment by kriskog** [comment]
Gonna need a screenie of this on a miner :joy:

**Comment by bluetshirtguy** [comment]
> Gonna need a screenie of this on a miner 😂

https://imgur.com/fb5EXEu

**Comment by Shadowflame909** [comment]
I'm tired of these games

Glad be us a death squad skirt or quut trolling

**Pull request merged**
