### PR TITLE
Laser pointers no longer make felinids phase through diagonal gaps

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

Someone forgot the dir argument, making it possible to phase through diagonal gaps.

## Why It's Good For The Game

One less bug. I like my gbp

## Changelog

:cl:
fix: Felinids no longer phase through diagonal gaps upon seeing a laser
/:cl:

### CODE REVIEW

**Comment by Dawnseer** [comment]
I am reminded of gifs of cats seemingly going through almost impossible gaps, like the small gap between a door and the floor.

**Comment by norsvenska** [comment]
nothing stops cat

**Comment by moocowswag** [comment]
hound of tindalos

**Comment by HoodMilk** [comment]
SOUL REMOVED

**Comment by CCC23** [comment]
tg has fallen millions must climb through walls

**Pull request merged**
