### PR TITLE
TURN DOWN THAT FUCKING SUBWOOFER YOU GODDAMN KIDS

### PR DESCRIPTION
**Pull request by actioninja**
:cl: actioninja
tweak: The general station ambiance no longer has an inexplicable 40hz rumble that violates your subwoofers
/:cl:

Any of you who are dumb enough to leave ambient sounds on (like me) know exactly what this is. The ship ambiance has been high-passed so it no longer has a stupid loud rumble that dominates the entire soundscape of the game.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
not 432

**Comment by Tlaltecuhtli** [comment]
not 432

**Comment by k-k-karma** [comment]
NO the ambience is perfect fuck you i love it

**Comment by nicbn** [comment]
just turn it off dude

**Comment by actioninja** [comment]
"just turn it off lol"
That's the whole point, if it sucks so much ass that everyone is just turning it off anyways, why leave it the way it is?

**Comment by Memager** [comment]
how about options to decrease/increase the sound

**Comment by Jordie0608** [comment]
\>660% file size increase

**Comment by actioninja** [comment]
@Memager Feels like options bloat to have an option for "ridiculously loud bass rumble."
@Jordie0608 Ha, didn't even notice that. Likely an artifact of lossy ogg file > daw > lossless > lossy ogg file. It's probably actually lower quality than the original as well, even if not by any noticeable degree.

Since apparently some people actually like the stupid bass rumble, I could compromise and make a version where the rumble is normalized to the same volume as the rest of the frequency spectrum so that way an ambient sound isn't literally one of the single loudest sounds in the entire game.

**Comment by actioninja** [comment]
You know what, fuck it, I'm going to come at this again another time with a different approach. The more I think about it the more I realize this is a total bandaid solution that doesn't address any of the actual major problems with the atmospheric sound design.
I'm going to wait til 513 and see if it has the needed shit for a sound engine rework and then from there harass ninjanomnom to actually do it.

**Pull request closed without merging**
