### PR TITLE
disables telesci

### PR DESCRIPTION
**Pull request by ghost**
Removes the ability to create telepads and telesci consoles at the circuit fabricator.

### CODE REVIEW

**Comment by kilog** [comment]
дщд

**Review by Cyberboss — COMMENTED** [review]
This is the rare case I'd advocate commenting the code instead of deleting it

**Comment by Cyberboss** [comment]
Also your title should be "Disables Telescience" because admins can still use it

**Comment by xxalpha** [comment]
It's a bait title, he knows what he is doing

**Comment by vcordie** [comment]
> It's a bait title, he knows what he is doing

you give me too much credit

**Comment by PKPenguin321** [comment]
Freeze

**Comment by vcordie** [comment]
removals are allowed under the freeze iirc?

**Comment by Jalleo** [comment]
Technically a removal @optimumtact will decide probably.

**Comment by PKPenguin321** [comment]
Removals that aren't entirely balance-based I would guess, otherwise
>"Removes half the max ammo from disablers"
>"Removes the lack of decent armor levels on the HoS jumpsuit"

**Comment by XDTM** [comment]
do we still have the "i ded" tag around

**Comment by kilog** [comment]
we need an "im bant" tag

**Comment by coiax** [comment]
@XDTM it's more that @vcordie got banned for using telescience to snatch the nuke op's nuke.

**Comment by GunHog** [comment]
Freeze, and even so, still a bad PR. Powergamers need to stop damaging the experience for other players. I am truly sick of PRs like this, which degrade the fun of several people for the sake of stopping a few.

**Comment by InsaneHyena** [comment]
I DED

**Comment by optimumtact** [comment]
Low effort and after a ban

**Comment by PKPenguin321** [comment]
This wasn't necessary

**Comment by optimumtact** [comment]
Nobody asked you

**Comment by PKPenguin321** [comment]
Doesn't matter who says it, it's just a fact

**Comment by optimumtact** [comment]
facts are just opinions you agree with

**Comment by TheDreamweaver** [comment]
But oranges... Why?

**Comment by kilog** [comment]
im gay

**Pull request merged**
