### PR TITLE
Revert "Revert "Removes alien driveby""

### PR DESCRIPTION
**Pull request by Aranclanos**
Reverts tgstation/-tg-station#12236

### CODE REVIEW

**Comment by fleure** [comment]
>instamerge

dis gon b gud

**Comment by Miauw62** [comment]
lmao and you called me out on breaking the rules

**Comment by Anonus** [comment]
the drama we've all been waiting for

**Comment by duncathan** [comment]
Aran cannot be cucked

**Comment by Aloraydrel** [comment]
I dont have the tools on me go make the mad man picture

**Comment by Ricotez** [comment]
remember when we had rules for merging

such as "don't merge your own PRs"

or "wait 24 hours before merging"

lipton_kermit

**Comment by Wyzack** [comment]
Realtalk Aran why do you want this in the fucking game so badly? Everyone fucking hates it man

**Comment by Giacom** [comment]
nice meme rico

**Pull request merged**
