### PR TITLE
Fixes being unable to dig plants out of soil

### LINKED ISSUE #28938: You can't dig plants out of dirt, only fancy hydroponic machines
Steps to reproduce:
Step 1.Make a plant area with sandstone and plant something on it
Step 2.Try to shovel it
Step 3.Hit the dirt to no effect

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: You can now properly dig out plants from patches of soil.
/:cl:

It seems that, before the actual digging, the check searched for `unwrenchable`. This doesn't make much sense (digging out plants generally isn't tied to whether or not their container can be moved, if the huge forest outside of my house is any example), and soil had a check in place for it anyway, so I think it was a bug left over from copypasta. This fixes that, so you can now dig out plants to your heart's content.

Fixes #28938

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by octareenroon91** [comment]
Plain shovels worked but spades were useless?

**Comment by FantasticFwoosh** [comment]
The shovel removes the soil tray, because soil trays are unwrenchable.

This PR is problematic because you can use hand-spades to clear away weeds & plants on hydroponics trays/plots, but using a shovel on a soil plot will outright remove it, please test whether this has any difference on occupied soil plots.

**Comment by octareenroon91** [comment]
Should just make spades work again.

**Comment by Xhuis** [comment]
I may be reading wrong. What exactly is the concern here?

**Comment by FantasticFwoosh** [comment]
_**150 hours of testing**_

Shovels **remove** soil trays, and @octareenroon91 is correct, i don't think there's any head-cannon reasoning for it besides the shovel being too large whereas spades are petite and can be used on any hydroplot or soil tray.

Just count shovel interactions into your further testing please.

**Comment by octareenroon91** [comment]
It's fine to merge. There may or may not be good cause to trim the istype down to `/obj/item/weapon/shovel`. That's all.

**Comment by Xhuis** [comment]
@fwoosh You seem to be missing the point here. I knew about that, and it's intentional. I was curious if something had broken.

It isn't spaghetti code at all. I don't think you know what that term means. Shovels were used because they're logically the thing to use to move soil, since they're _shovels._ Spades are built expressly for gardening, and so are not.

**Pull request merged**
