### PR TITLE
The officer's sabre can be used to remove a lizard's tail.

### PR DESCRIPTION
**Pull request by harmonyn**
:cl: bandit
tweak: The officer's sabre standard in Nanotrasen captain rollouts can be used to remove the tails of lizard traitors, or lizards in general.
/:cl:

Why: Because why have an officer's sabre, an incredibly sharp one, if it cannot be used for the most important captain task of all? Also consistent with other surgery.

Also gave it the sharp item check that scalpel incisions have

### CODE REVIEW

**Comment by jaxy15** [comment]
Is this legitimately your fetish?

**Comment by bgobandit** [comment]
rare jaxy collected

**Comment by kevinz000** [comment]
stop trying to detail yourself

**Comment by LanCartwright** [comment]
I like this. It forgoes and skips the basic tail removal process.

Does this include all dismember-able weapons?

**Comment by Iamgoofball** [comment]
:-1: until you refactor surgery code to allow you to just check for the SHARP flag

**Comment by GunHog** [comment]
> :-1: until you refactor surgery code to allow you to just check for the SHARP flag

Read the diff, Goof! (You force me to do this all the time with your PRs)

**Comment by Iamgoofball** [comment]
not done properly, thats hardcoded for just this one

**Comment by octareenroon91** [comment]
>not done properly, thats hardcoded for just this one

So, what, get a series of flags, SHARP, PINCHING, SPREADING, HACKING, CAUTERY?

**Comment by Niknakflak** [comment]
Goof is really not one to talk about things being done properly

**Comment by Iamgoofball** [comment]
fake news

**Comment by Grazyn** [comment]
There should be some consequence for losing the tail, maybe add permanent dizziness effect?

**Comment by octareenroon91** [comment]
>There should be some consequence for losing the tail

Contempt of man and reptile alike.

**Comment by Alek2ander** [comment]
Not being able to *wag

**Pull request merged**
