### PR TITLE
[FUCK] Fixes a proc path error

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
This might magically fix the spaceproof human issue. I'm hoping. I cannot reproduce it locally, its some preference fuckery.

## Changelog

:cl:
balance: Humans aren't spaceproof anymore
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Did this close https://github.com/tgstation/tgstation/issues/65696

**Comment by Kapu1178** [comment]
> Did this close #65696

yes

**Comment by Mothblocks** [comment]
another bug that wouldnt happen if we used relative pathing 😏

**Comment by LemonInTheDark** [comment]
^ traitor

**Pull request merged**
