### PR TITLE
HERES SOME ATOMIZED SHIT THAT NOBODY WILL EVER SEE OR TEST UNTIL SOME FUTURE PR MAKES IT RELEVANT PART 4

### PR DESCRIPTION
**Pull request by Robustin**
OUR CONSISTENCY ON ATOMIZATION IS MINDBLOWING, AS IN IT MAKES ME WANT TO BLOW MY FUCKING BRAINS OUT.

### CODE REVIEW

**Comment by Xhuis** [comment]
why are you acting like a petulant child

**Comment by DaxDupont** [comment]
the salt is real

**Comment by Spaceinaba** [comment]
you wasted trips on this?

**Comment by Iamgoofball** [comment]
Did Joan tell you to atomize?

@KorPhaeron last time atomization was a trick by Joan to delib. Grief robustin. Can we stop letting her do this?

**Comment by Xhuis** [comment]
No, goofball, this was several maintainers asking him to atomize a large and messy PR and him choosing not to.

**Comment by PKPenguin321** [comment]
Disgraceful disregard of gets

**Comment by Iamgoofball** [comment]
@xhuis why you defend Joan so much despite them fucking you over, I don't know. If they're blackmailing you tell Kor.

**Comment by Xhuis** [comment]
If you can cite an instance where I "defended" Joan in the past 6 months, feel free to post it. I highly doubt the majority of people here care about blackmailing other people to do their bidding, and I certainly don't care enough to give into it anyway if it happened.

**Comment by Jordie0608** [comment]
@Iamgoofball Joan had nothing to do with this, read the PR

**Comment by ike709** [comment]
#36000

**Pull request closed without merging**
