### PR TITLE
listen to me, this is all I really wanted all along

### PR DESCRIPTION
**Pull request by Bawhoppen**
:cl: 
tweak: toolboxes fit in backpacks
/:cl:

### CODE REVIEW

**Comment by Niknakflak** [comment]
powercreep

**Comment by Bawhoppen** [comment]
it honestly doesnt matter

**Comment by xxalpha** [comment]
there's a reason toolbelts are so valuable

**Comment by Bawhoppen** [comment]
thats no argument, all the tools fit inside a regular small cardboard box anyways

**Comment by MMMiracles** [comment]
a small box that can hold small tools does not equal a metal toolbox.

**Comment by GeneralGoose** [comment]
i hope you're memeing
i was memeing about it literally 12 hours ago, when i thought medkits shouldn't fit in bakpacks, like toolboxes

**Comment by Davdichan** [comment]
Let me carry 7 toolboxes and dual wield 2 more. I'll be the toolbox ninja like no one was before. COME AT ME BRO

**Comment by KorPhaeron** [comment]
this PR will have absolutely 0 impact on gameplay since you can just cram every tool into a cardboard box and then access that box from your bag anyway.

It'd be a dumb PR if our inventory system wasn't so silly already

**Comment by Bawhoppen** [comment]
thats what I'm saying guys

**Comment by Core0verload** [comment]
It was denied 3-4 times already, I see no reason to not deny this again.

**Comment by xxalpha** [comment]
it's just powercreep

toolboxes have always been too big to fit in a normal backpack, why change this, what is the reason

**Comment by Jalleo** [comment]
Toolboxes have been debuffed from what they used to be. It makes it easier for traitors to suddenly kill with traitor ones.
It reduces the demand for cardboard so tgere is more for meh cardborg.
Nothing lse really.

**Comment by Davdichan** [comment]
Yeah toolboxes have been nerfed from their glorious days of 5 hit crits.

This would be a slight buff to the syndiebox but aside from that who really cares? If a tator wants to spend 5tc to get 5 boxes and chuck them at people like oversized morning stars for 18 damage apiece, let them. It'll be hilarious. Otherwise a surgical saw does as much damage as a syndibox and those fit in your pocket last I saw.

**Comment by Aloraydrel** [comment]
It's a baw meme meme pr episode

**Comment by Bawhoppen** [comment]
>me 
>meme pr

**Comment by jughu** [comment]
Toolbox should take up 3 whole slots since clearly second storage and yes toolboxes fit in backpacks thats realism

**Comment by Davdichan** [comment]
Whats the difference here between a box and a toolbox here? The toolbox does slightly more damage on a hit and cardboard boxes can be broken down into flat cardboard that can be stacked so you have room in your inventory for larger items if things wont fit in boxes?

**Comment by jughu** [comment]
Toolboxes are cooler

**Comment by TechnoAlchemisto** [comment]
Internals box space is valuable that doesn't justify this

**Comment by KorPhaeron** [comment]
I really need to close prs faster

**Comment by optimumtact** [comment]
Please don't merge things that don't have design or headcoder signoff when they've got such a negative response.

**Comment by HankMoodyExperience** [comment]
i really liked being able to carry three times as many items if they were tiny; consider large/bulky items taking additional space(if not all the space) if this gets readded in

**Comment by optimumtact** [comment]
It won't be re-added unless someone does a complete inventory overhaul.

**Comment by Dorsisdwarf** [comment]
Also you're a butt bawhoppen

**Comment by Bawhoppen** [comment]
what is it now for gods sake

**Comment by Dorsisdwarf** [comment]
!(http://puu.sh/qkUdw/ed4888f9da.jpg)

**Comment by Bawhoppen** [comment]
did you enjoy your time aboard the ruse-cruise

**Pull request merged**
