### PR TITLE
emoji update pr

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

cleans up some things about emojis:
most plushie emojis are cleaned up and not resized to hell and back, instead being a snapshot of their face
added bee plush emoji
added slime plush emoji
renamed all plushie emojis to what they are + a p at the start. plushizzard (what the fuck) becomes plizard for example
because plushop becomes pop with this, the pop soda emoji has been named cola after what it is in game
god other things i'm probably forgetting :^(

## Why It's Good For The Game

literally can NOT read what the fuck some of these emojis are in a 16x16 environment

## Changelog
:cl:
tweak: tweaked a few things about emojis. some have more reasonable names, some are no longer blurry, stuff like that.
/:cl:

### CODE REVIEW

**Comment by spessbandit** [comment]
screenshot?

**Comment by tralezab** [comment]
sure, one moment

**Comment by tralezab** [comment]
image

**Comment by Tlaltecuhtli** [comment]
the mouse is called tom

**Comment by ArcaneDefence** [comment]
Moth plush emote maybe? :)

**Pull request merged**
