### PR TITLE
Revert "Moves a rivet wall, corrects typos"

### PR DESCRIPTION
**Pull request by jughu**
NOSTELGIA

### CODE REVIEW

**Comment by optimumtact** [comment]
No

**Comment by Cyberboss** [comment]
what the actual...

**Comment by F-OS** [comment]
:ok_hand: :ok_hand:  :+1: X :100: :ok_hand: :ok_hand:

**Comment by Arianya** [comment]
[THE WALL](https://youtu.be/WnSt2xztmSw)

**Pull request closed without merging**
