### PR TITLE
Implant Icon Resprites

### PR DESCRIPTION
**Pull request by Comxy**
## About The Pull Request
Resprites some of the implant sprites. 

## Why It's Good For The Game
Some of the sprites looked crooked, so it needed a change.

The first three actually got animations.
Freedom Implant:
handcuff
Explosion Implant:
explosion
EMP Implant:
emp
Electricity:
electric
Adrenaline Implant:
running_man
Pill Implant:
pill_v2
Storage Implant:
Bluespace_bag

## Changelog

:cl:
imageadd: Adds better implant icon sprites
imagedel: Removes crooked implant icon sprites
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
we have changelog labels specifically for this, imageadd and imagedel
your changelog also tells players nothing about what is being changed, please change it

**Comment by MrDoomBringer** [comment]
why does the storage implant icon look like very strange flesh organ bag

**Comment by MrMelbert** [comment]
> why does the storage implant icon look like very strange flesh organ bag

where do you think the stored items go?

**Comment by MrDoomBringer** [comment]
a bluespace storage device in my chest cavity neither of which would look like weird flesh mass!

**Comment by Wallemations** [comment]
> a bluespace storage device in my chest cavity neither of which would look like weird flesh mass!

Admittedly the fact that it's injected with a syringe made me think this too

**Comment by Comxy** [comment]
It is a bluespace bag now

**Comment by MrDoomBringer** [comment]
pogged

**Pull request merged**
