### PR TITLE
Revert "Deactivate prescans on suicide"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#36741

Two world loops on suicide is not acceptable

### CODE REVIEW

**Comment by nichlas0010** [comment]
image
🤔

**Comment by george99g** [comment]
...there was an alternative PR which didn't include this.

**Comment by george99g** [comment]
> now that we've removed all the existing examples of this

https://github.com/tgstation/tgstation/blob/838cb9567c867549062dcb83c83f52fd400dfa09/code/modules/mob/living/silicon/ai/login.dm#L3
BYOND's resources recommend the use of this construct and there's nothing about it in the contributing guide. Maybe that should be updated to reflect this?

**Comment by ExcessiveUseOfCobblestone** [comment]
oh my god....

**Pull request merged**
