### PR TITLE
Removes Omnizine from donk pockets.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
Removes omnizine from donk pockets.
## Why It's Good For The Game
Why do they even have it? That shit can heal third degree burns. That's kinda nutty.
## Changelog
:cl:
balance: Donk pockets no longer have omnizine in them.
/:cl:

### CODE REVIEW

**Comment by Boopideedoo** [comment]
I understand where your coming from but the miners are in a super dangerous place.
they might need that in a fight. Just debuff miners while your at it

**Comment by Jacquerel** [comment]
Are omnizine donk pockets causing some kind of actual problem or does it just offend your design sensibilities in some way?
At this point this has been their behaviour for over 8 years so I am going to need some more argument than "vibes" to change it.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Your "why it's good for the game" is incorrect, Omnizine cannot heal third degree burn wounds, please update it

**Comment by Eronymun** [comment]
Has this balance change never been suggested before? I'm honestly surprised, I thought this would be a hot topic thing with tons of closed PRs.

**Comment by Jacquerel** [comment]
> Has this balance change never been suggested before? I'm honestly surprised, I thought this would be a hot topic thing with tons of closed PRs.

No, because generally speaking nobody is using Donk Pockets to do anything particularly crazy and they're not notably more effective than actually going to get medical treatment.
This is why I feel the `Why is it good for the game?` is insufficiently justified here.

**Comment by Pickle-Coding** [comment]
> Are omnizine donk pockets causing some kind of actual problem or does it just offend your design sensibilities in some way?
> 
> At this point this has been their behaviour for over 8 years so I am going to need some more argument than "vibes" to change it.

While testing on local to test if omnizine can heal burn wounds (maybe that was a thing in the past), I overdosed on omnizine while eating a bunch (2 packets) of donk pockets.

**Comment by Jacquerel** [comment]
> While testing on local to test if omnizine can heal burn wounds (maybe that was a thing in the past), I overdosed on omnizine while eating a bunch (2 packets) of donk pockets.
> 
> Also last round I died from a medicine allergy after eating donk pockets.

The fact that you can overdose to and be allergic to chemicals are intended features yes, I'm still not quite seeing what the problem is?

**Comment by Paxilmaniac** [comment]
april fools is over your pr is late

**Comment by Pickle-Coding** [comment]
Eating 12 donk pockets shouldn't kill people in 30 seconds unless they have a food allergy really.

**Comment by Jacquerel** [comment]
If this is the best you got I'm not going to be merging this PR, sorry.

**Comment by necromanceranne** [comment]
_How_ are you eating two packets of donk pockets? I don't think you can eat that many donk pockets, unless maybe you're starving.

**Comment by DaydreamIQ** [comment]
Ever since the great un-donkening its pretty hard to even FIND two packets of donks nevermind consume them all in one sitting.

**Comment by Iamgoofball** [comment]
heating donk pockets to have tricord/omnizine has been a staple of ss13 for over 10 years

**Comment by Watermelon914** [comment]
Disagree with this PR

The justification isn't really all that, and as others have said, this has existed for a long time. I partially know why you're PRing this and it's because you died to omnizine donk pockets because you had the allergies quirk on terry. That's a skill issue bro, you just gotta deal with it.

**Pull request closed without merging**
