### PR TITLE
Adds Prettierx - or how I broke TGUI for the nth time

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
An atomization of #67809. This only does the following:

- Adds [prettierx](https://github.com/brodybits/prettierx) (aliased as prettier)
- Adds [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) / disables many conflicting rules within ESLint
- Sets prettier as a recommended vscode extension
- Sets format on save as default for JS/TS/JSX/TSX files
- Validates the usage of prettier in CI

The rules in place are:
```
arrowParens: always
breakLongMethodChains: true
endOfLine: lf
importFormatting: oneline
jsxBracketSameLine: true
jsxSingleQuote: false
offsetTernaryExpressions: true
printWidth: 80
proseWrap: preserve
quoteProps: preserve
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false
```

## How to import this on your project

<details>
<summary>Read</summary>

It might be much simpler to start from scratch, following the steps, rather than sift through each file diff.
1. Change to your tgui folder
2. `yarn add prettier@npm:prettierx@0.19.0 eslint-config-prettier`
3. Move the included prettierignore, .prettierrc, and .eslintrc file over to
4. Make sure these files are closed, or close and reopen vscode
5. In your TGUI folder, `yarn prettierx --write packages`
This will cover the largest part of the work, but sorting through and finding which files to de-prettier is up to you. Do not forget to add prettier to the remaining files: vscode: settings, extensions, tools: buildjs, and tgui: package.json.

(This is not meant to be exhaustive, use caution)

</details>

## Why It's Good For The Game
~~Finally I can change a line in interfaces without creating a 200 line file diff of spaces and single quotes~~
Prettier is a widely used and great extension that lets developers focus on developing rather than syntactical squabbles
It cleans up after silly mistakes like indentation and forgotten semicolons - all without so much as an afterthought (ctrl S!)

It encourages readability by standardizing code according to its ruleset.
All around, a great tool to have to make code bases uniform and professional

## Changelog

:cl:
code: Prettier is now recommended as an extension for UI development (or just in general!)
refactor: Many, many interfaces have been hit with the prettier stick so please report any issues. There should be zero noticeable differences in how UIs look or function.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
The man behind the broken tgui

**Review by stylemistake — APPROVED** [review]

**Comment by ArcaneMusic** [comment]
Forgive me for not being familiar with the extension, but does prettierx have a visible difference on UIs, and if so, is there a before and after between our in-game UIs?

**Comment by stylemistake** [comment]
It's code aesthetics.

**Comment by Mothblocks** [comment]
@jlsnow301 Can you merge from master just so we know there's no merge skew then ping me when you did and it passes

**Comment by jlsnow301** [comment]
> @jlsnow301 Can you merge from master just so we know there's no merge skew then ping me when you did and it passes

on it

**Comment by Profakos** [comment]
Destination folder is missing in step three...

**Pull request merged**
