### PR TITLE
PDA game log entry contains ckey

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
can you have pda logs as its own thing too, having to cheat with telecoms machinery is LAMEEEE

**Comment by optimumtact** [comment]
I'm not sure what you mean?

**Comment by ExcessiveUseOfCobblestone** [comment]
Now: Say Logs = PDA logs

What I want: Say Logs || PDA Logs

**Comment by optimumtact** [comment]
PDA logs go in the game log, you're still not being clear, are you talking about an in game admin log view, or the logs stored in the round folder

**Comment by ExcessiveUseOfCobblestone** [comment]
.getserverlog > month > day > round > pda.html / pda.log

Yes?

**Comment by optimumtact** [comment]
I am on the same page now, and it can be done

**Comment by ExcessiveUseOfCobblestone** [comment]
thanks beautiful

**Comment by Anonmare** [comment]
Powercreep

**Comment by kevinz000** [comment]
@optimumtact dont forget the "send to everyone" part, and the tcomms message monitor.

**Comment by optimumtact** [comment]
tcomss message monitor uses key_name already, but I did miss send to everyone

**Comment by KorPhaeron** [comment]
If someone wants to do the PDA log file in another PR they can, this is getting stale

**Comment by optimumtact** [comment]
aww man it wasn't ready

**Pull request merged**
