### PR TITLE
Replaces all instances of the tgstation2 map with Box Station

### PR DESCRIPTION
**Pull request by Cyberboss**
The lack of consistency is maddening.

This config line will need updating https://github.com/tgstation/tgstation/pull/28463/files#diff-9245e872f83193dbc6fec80cb08fea16L16

### CODE REVIEW

**Comment by Tacolizard** [comment]
Revisionist history

**Comment by Cyberboss** [comment]
Funnily enough, if headmins don't remember to update the config, games will go like "Unable to load tgstation2.json, defaulting to Box Station!"

**Comment by nicbn** [comment]
Looks ok

**Comment by optimumtact** [comment]
BOX IS TGSTATION DELETE THIS PR AT ONCE

**Comment by PKPenguin321** [comment]
Config hassle :(

**Comment by optimumtact** [comment]
close it

**Comment by Cyberboss** [comment]
Bite the bullet

**Pull request merged**
