### PR TITLE
Protosuit: A new medical hardsuit, which you can get from Lavaland

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

This PR adds a new, dark blue medical hardsuit called "Protosuit". It's based on old Syndicate hardsuits, and features a medical HUD integrated into it's helmet.

## Why It's Good For The Game

Right now miners can only get 2 hardsuits. One is very shitty and other one is just a normal one without any features. 

## Changelog
:cl:
add: Added a new medical hardsuit, Protosuit
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
miners can already get the champions hardsuit and a literal blood red for not that much effort, we don’t need more lavaland powercrepe

**Comment by GunHog** [comment]
Why not modify an existing hardsuit that you can get as Lavaland loot? Also, this medical hardsuit should be obtainable by Medbay somehow, as I do not think miners would bother carrying it back to the station for them to take.

**Comment by Tlaltecuhtli** [comment]
put it in blackmarket uplink if u have nowhere else to put it in

**Comment by Dorsisdwarf** [comment]
Miners can *only* get 2 hardsuits as loot? How crushing. (Also I bet it's more than 2)

**Comment by optimumtact** [comment]
We don't need more hardsuits

**Comment by XRandomXManX** [comment]
Kind of a weird reason to close the PR. Not Miners being overpowered or wanting the Hardsuit to be in a different place. Instead not needing more Hardsuits, like this game is suddenly not about having random useless shit, like it's supposed to only have what it needs. While the Chaplain has a shit ton of Null Rods, the Curator has multiple boxes of gear only they can get. Space Explorations entire existence. All the drinks that exist that serve no real purpose. The Psychologist. I don't think this was something that should have been merged, but something being unnecessary isn't a good reason. People can pour their time into useless shit and be rewarded for adding something new to the game, as long as it didn't harm the game in any way like this PR would. Not having an abundance of barely useless stuff is something for any other server. It's a good design philosophy but it is one that is applied on different servers and one I don't think needs to be on /tg/, which people add to for no benefit to themselves.

**Comment by optimumtact** [comment]
cool story bro

**Comment by XRandomXManX** [comment]
oh shid i got rekd

**Comment by TheBonded** [comment]
> oh shid i got rekd

@XRandomXManX 
I'm pretty sure hardsuit and mining additions are closed until the mining change/modular hardsuits are finished

**Pull request closed without merging**
