### PR TITLE
Meaty Ores will now drop guts in addition to meat

### PR DESCRIPTION
**Pull request by Incoming5643**
Xeno Meaty Ores will drop useful xeno organs. 

Keep in mind that MOST xeno organs also require a plasma vessel and some way to generate weeds to actually function, so this is less unbalancing than you probably think.

### CODE REVIEW

**Comment by Incoming5643** [comment]
have to run, will reactively respond to comments later

**Comment by Zilenan91** [comment]
xeno comms for everyone

**Comment by Core0verload** [comment]
You need more than one for that to be useful. And "xeno meaty ore" event is pretty rare.

**Comment by optimumtact** [comment]
mm on the one-hand we're trying to avoid initializing lists on objects at creation

on the other these items should not be created that often

**Pull request merged**
