### PR TITLE
Disintegrate now disintegrates people

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

The spell named "Disintegrate" now dusts people instead of just gibbing them. The antimagic recoil effect and flesh suit interaction were also altered to match the new effect of the spell.

## Why It's Good For The Game

Disintegrate now does what you'd think it'd do from looking at its name. Also, like the tabletop spell, it also destroys any items that the target has on them, meaning that wizards can no longer one-shot the HoS with this spell without destroying the gamer gear that said HoS had on their person at the time of their disintegration. Also, you can't just clone the head of a victim of a spell that's supposed to (mostly) permakill people.

As an alternative to this PR, I could change the name of Disintegrate to something like "Smite".

EDIT: I've made a PR that does just that: https://github.com/tgstation/tgstation/pull/45786

## Changelog
:cl: ATHATH
balance: The Disintegrate spell now dusts its victims instead of gibbing them.
/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
Digitigrade now disintegrates people

**Comment by ATH1909** [comment]
I had forgotten to update the description of Disintegrate in the spellbook to match its new effect(s), so I just did that now.

**Comment by Ordonis** [comment]
Things doing what things say they do is good.

**Comment by nemvar** [comment]
Very cool. Instant death with no recovery, this is good gameplay and should be encouraged. This is kind of gameplay that is enjoyable and we need more of it.

**Comment by tralezab** [comment]
i get it but maybe you should make it called explode or implode or something because it's much better gameplay for this to gib than to dust and gibbing is way more fun

**Comment by ExcessiveUseOfCobblestone** [comment]
based wizard nerfs

**Comment by MMMiracles** [comment]
I feel bad for the random virologist/xenobiologist that's minding their own business before being irreversibly taken out of the round with no chance of revival by a virgin in a blue robe.

**Comment by nicbn** [comment]
What are you complaining about
Regardless of whether this PR gets merged or not the magic will remove people from round

**Comment by ATH1909** [comment]
> I feel bad for the random virologist/xenobiologist that's minding their own business before being irreversibly taken out of the round with no chance of revival by a virgin in a blue robe.

To be fair, that happens with old!disintegrate too if the wizard bothers to take care of the head left behind by the spell.

**Comment by ATH1909** [comment]
I've made an alternative PR to this one: https://github.com/tgstation/tgstation/pull/45786

**Comment by MMMiracles** [comment]
That at least requires slightly more effort and leaves behind an obvious mess versus a tiny pile of ash.

**Comment by ishitbyabullet** [comment]
@MMMiracles ideally, this pr should use the big ash sprite and not the tiny one.

**Comment by ATH1909** [comment]
> @MMMiracles ideally, this pr should use the big ash sprite and not the tiny one.

Big ash sprite? Do you mean the pile of bones one that's made when a human walks into the SM?

**Comment by Nickvr628** [comment]
This is what it used to be and it was infinitely better. Bring it back please

**Comment by cacogen** [comment]
remember back in the day when disintegrate gibbed with no brain so you were permanently out and it sucked so much they changed it so a brain dropped so at least back then you could be borged

**Comment by SkeletalElite** [comment]
I'm assuming this just uses the sprite that appears when you burn something. It should leave the pile of bones like when you get dusted by the SM so that it's obvious to people who find the mess that someone died.

**Comment by Tlaltecuhtli** [comment]
being insta killed with no recovery and then wiz dies 5 min later but round continues because dynamic or other antags isnt that great at least other game removal like soul sharding, necro stone lets you play as antag for a while

**Comment by FloranOtten** [comment]
>Adding something that can just instantly perma round removal you

thank you, very cool!

Shitposting aside, do we really need this? Gibs were obvious. Your brain could be cloned or borged. A wizard had to take effort to dispose of you instead of just gamer button kill. I like the fact that items are gone, but it's a small consolation for gamer instakill button.

**Comment by fludd12** [comment]
As a compromise to the above complaints, you could make it decapitate the person disintegrate is used on, and drop their head-with-brain-inside on top of the pile of ash. You could even do a neat animate on the head to make it appear to hover in the air for a half-second as the body ashes, before dropping onto the ash pile with proper pixel adjustment. This way, the brain still remains, wizards can still deal with it if they want to spare the time, *and* it works a bit more like the D&D spell, all at the same time.

**Comment by Shapsy** [comment]
All these people who don't realize this is exactly what disintegrate used to do anyway, ei nath dropping a brain was hugbox

**Comment by MMMiracles** [comment]
yeah and parapen+c4 used to be a tactic and welder tanks could gib corpses

things changed

**Comment by ExcessiveUseOfCobblestone** [comment]
do wizards use disintegrate and NOT pickup the brain or take out cloning?

**Comment by qbmax32** [comment]
gone, reduced to atoms

**Comment by carlarctg** [comment]
bad, removes people from the round even BETTER than normal ei'nath, which is a god damn terrible idea

just make normal nath remove clothing too

**Comment by Putnam3145** [comment]
or you could just eject the brain before disintegration, or just make the spell a brain-ejection spell in the first place

**Comment by ShizCalev** [comment]
Closed by #45786

**Comment by adamkad1** [comment]
its not like wizard rounds last that long anyway...

**Pull request closed without merging**
