### PR TITLE
resprites crew monitor

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
resprites the crew monitor! tried to keep the shape and scale similar, while improving some of the parts that haven't aged well - like polishing up the stripe. i also gave it a new screen and animation, seen below!
image
crewmonitor1
## Why It's Good For The Game
cleans up bad/nonsensical shading, gives the crew monitor a much saner palette.
## Changelog
:cl:
image: resprited the crew monitor
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
Neat sprite, isn't it too similar to a medPDA? Especially from far away?

**Comment by CoiledLamb** [comment]
> Neat sprite, isn't it too similar to a medPDA? Especially from far away?

i didn't reference the med PDA at all so it's purely coincidental if so
also, here's a side by side, it's not really that close
image

**Comment by JohnFulpWillard** [comment]
I think the sprite was made to be similar to the crew monitoring computer itself, I dunno if you want to change that so they are similar again (and no longer the same sprite as operating computers) but would be nice.

**Comment by CoiledLamb** [comment]
> I think the sprite was made to be similar to the crew monitoring computer itself, I dunno if you want to change that so they are similar again (and no longer the same sprite as operating computers) but would be nice.

oh hrm. i am actually working on a version of this with scanlines, so if it comes out well i will resprite the crew monitor computer screen as well. i'll draft this until then

**Comment by Helg2** [comment]
Ctrl+F will always help

**Comment by CoiledLamb** [comment]
> Ctrl+F will always help

oh rad, thanks

**Comment by CoiledLamb** [comment]
> I think the sprite was made to be similar to the crew monitoring computer itself, I dunno if you want to change that so they are similar again (and no longer the same sprite as operating computers) but would be nice.
this is looking a little too extensive for this PR, but i will try and get to it eventually. undrafting now

**Comment by CoiledLamb** [comment]
messed up this PR, will reopen shortly! (please wait warmly)

**Pull request closed without merging**
