### PR TITLE
Ash storms will no longer affect people inside mechs and stuff

### LINKED ISSUE #32187: MMIs die inside mechs during ash storms(?)
I have no idea what happened, but I just straight up died as a MMI inside a Ripley.
There was an ash storm happening, but mechs are ash storm proof.
No sounds, no effects, nothing, just badabingbadaboom you're dead.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #32187

:cl: More Robust Than You
fix: Ash storms will no longer affect people inside mechs and stuff
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Like two lines down there is a mech check already, the issue is MMIs and I'd rather not change lockers to make you weather immune to fix this particular issue

**Comment by praisenarsie** [comment]
does it still damage mechs though.

**Comment by YPOQ** [comment]
The mech check doesn't work because the brainmob's loc is the MMI.

**Comment by MoreRobustThanYou** [comment]
@YPOQ i made it check to see if you're on a turf or in a mech/locker/alien's stomach

**Comment by YPOQ** [comment]
Sorry, I was just explaining why the original check didn't work.

**Pull request closed without merging**
