### PR TITLE
[WIP] Toy Figurines (needs sprites) 

### PR DESCRIPTION
**Pull request by blockheads**
Adds figurines to the game, a new type of basic toy which can equip there own custom clothing and stack hats one-on top of the other. Also made it pretty easy to add new clothing options(for the figurines of course).

This is currently a work in progress my first actual contribution, I need sprites because I cannot sprite well and lack any sense of artistic skill as you can see by my added images in toys.dm

ps: I feel like I've done something horribly wrong please help

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
this would require a fuck ton of tiny sprites

**Comment by blockheads** [comment]
How so? I mean really there can be as many sprites as you desire but I'm a little confused why there would have to be so many. There doesn't have to be a lot of clothing options

**Comment by TechnoAlchemisto** [comment]
o i thought you meant for like every outfit in the game my b don't mind me

**Comment by blockheads** [comment]
nono I wanted them to have their own aesthetic but I guess if I really have to I could just scale down sprites in the game pretty easily. I would love it if they had their own sprites just looks nicer overall but whatever works I guess I picture something like this 
image as the base figurine model

**Comment by Shapsy** [comment]
Would it just be possible to make a tiny human-type thing and use their wear-code to handle clothes/sizes?

**Comment by blockheads** [comment]
yes I can scale and move clothes rather easily that would be perfect

**Comment by Jordie0608** [comment]
Dwarf mutation code could be helpful

**Comment by bgobandit** [comment]
we have figurines already, check toys.dm

**Comment by blockheads** [comment]
i assume your mistaking action figures to be  what I made? I mean figures and figurines do have really closely related names but what I am trying to make is something that you dress up not a action figure with a static sprite if that makes any sense.

**Comment by yackemflam** [comment]
Why can't you just make it so that the sprites downscale in size like plants?

**Comment by optimumtact** [comment]
@blockheads is this going to be finished?

**Comment by optimumtact** [comment]
Please ping this if you want it reopened when you have sprites.

**Pull request closed without merging**
