### PR TITLE
nerfs the HP of bushes

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
- Lowered the HP of the "flora" type from 150 (same as reinforced window) to 100
- Trees are still 150 HP
- Gave flora an x4 modifier to burn damage (takes 4 times the burn damage)
## Why It's Good For The Game
Every time you do a project as an engineer on a map with bushes, each bush takes 10 welding tool hits to destroy, overall bushes have way too much HP and shouldn't be this difficult to destroy.
## Changelog
:cl: grungussuss
balance: bushes and other flora have had their HP reduced from 150 to 100. Trees still have 150 HP
balance: flora now has an X4 modifier to damage from burn sources
/:cl:

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]
I think you should just make them take like, 3x-5x damage from burn damage or sharp brute damage

**Comment by MrMelbert** [comment]
Though i'm also fine with bringing it down to 100 with above

**Comment by DaCoolBoss** [comment]
Make sure trees keep a decent amount of health, they're a subtype of flora.

**Comment by Sadboysuss** [comment]
ok all valid feedback

**Pull request merged**
