### PR TITLE
>RESTART VOTE PASSES WITH 46 VOTES >IT DOESNT GO THROUGH

### PR DESCRIPTION
**Pull request by Iamgoofball**
D E M O C R A C Y

### CODE REVIEW

**Comment by Kromgar** [comment]
When the memes are just right

**Comment by optimumtact** [comment]
No.

**Comment by Ultimate-Chimera** [comment]
lmao

**Comment by optimumtact** [comment]
To add, this is an administrative issue where an admin is not respecting or following along with the users wishes and should be handled with an admin complaint.

**Comment by ike709** [comment]
@Iamgoofball For #20000 write a bot that comments " :tangerine: citrusy tyranny :tangerine: " on any PR that oranges closes

**Pull request closed without merging**
