### PR TITLE
Pulls the plug on Cerestation (for real this time)

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
del: Cerestation has been decommissioned. Nanotrasen apologizes for any spikes of suicidal tendencies, sporadic outbursts of primitive anger, and other issues that may of been caused during the station's run.
/:cl:

[why]: # The more I work on remapping the departments to resolve complaints the more I wonder if I'm just better off scrapping it entirely and starting from scratch.

Yeah, probably shouldn't of held up the initial removal PR, but I had some hopes of trying to salvage the time I spent but I've come to the point where I might as well start over with a better base with what I know now instead of several months back. 

The shuttle stays in though because I've only heard positives about it and because having the space titanic as a shuttle is funny.

:pray:

### CODE REVIEW

**Comment by GunHog** [comment]
I will miss you, CereStation :cry: I am one of the few that actually liked the station.

**Comment by MoreRobustThanYou** [comment]
It could do with a complete redo, yes

**Review by ghost — CHANGES_REQUESTED** [review]
Take cere out of _maps/basemap.dm

**Review by ghost — APPROVED** [review]
Press F to pay respects

**Comment by nfreader** [comment]
F

**Comment by PraiseRatvar** [comment]
F

i should've played cere properly

**Comment by MoreRobustThanYou** [comment]
F

**Review by Cyberboss — APPROVED** [review]
F

**Comment by ShizCalev** [comment]
:(

**Comment by BeeSting12** [comment]
f

**Comment by SyruseEln** [comment]
I too like the shuttle. With some modification it could be a cool whiteship for delta, or some other new space ruin.

**Comment by TheVekter** [comment]
F

**Comment by KorPhaeron** [comment]
Don't think this needs any further discussion/rude people dancing on the grave

**Comment by optimumtact** [comment]
this really doesn't need to be locked, also it's conflicting

**Comment by The-clown-known-as-Pepe** [comment]
F

**Comment by Cyberboss** [comment]
Rip space hindenburg

**Comment by QualityVan** [comment]
F

**Comment by BlueNothing** [comment]
F

**Comment by PraiseRatvar** [comment]
24 hours, here comes the purple label

**Pull request merged**
