### PR TITLE
Fixes implant cases being deleted on drop

### LINKED ISSUE #18928: Implant cases are deleting on drop
Probably the same issue as bowman headsets(conflicting flags)

### PR DESCRIPTION
**Pull request by lzimann**
For some reason the implant cases received the implant flags... I don't see any reason why this happened, so hopefully it won't break anything(couldn't find anything related to this)

Fixes #18928

### CODE REVIEW

**Comment by Core0verload** [comment]
It would break implant case's ability to receive chemicals for chemical implants.

**Comment by lzimann** [comment]
God damnit

**Comment by Supermichael777** [comment]
could you make the cases attack by hit the implant it it has one?

**Comment by lzimann** [comment]
I'll take a look at it

**Comment by lzimann** [comment]
I'm not sure if this is the best solution, but it should work(the downside is not being able to examine the implantcase to see the reagents)

**Pull request merged**
