### PR TITLE
[Pretty Pictures!] [map] Makes starlight have far spreading low levels of light rather than near spreading high levels of light.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Adds the ability to set a light source's high end. (This is normally 10)
Makes starlight use new system to have far spreading low levels of light rather then near spreading high levels of light. (by setting this new option to ~~1.5~~1)

Pics **_UPDATED**_ (WITH GIF):

output_hpfdga

Adds a way to make certain areas use dynamic lighting only if starlight is enabled.
Adds a child to /area/space, called /area/space/nearstation, it will use dynamic lighting if starlight is on, normal space 100% lighting other wise. all things on space turfs still have 100% lighting, but other turfs won't be 100% bright, and instead be illuminated by starlight.
This area was added to the "locker in space" room above toolstorage on box, as well as the engine and any areas that had turfs in space like viro's disposals or the 4 plating tiles below mining dock.
Solars, and ai external areas use dynamic lighting if starlight is enabled.

### CODE REVIEW

**Comment by Jalleo** [comment]
Nerf to shadowlings decrease the area of effect a bit or by another means

**Comment by Metacide** [comment]
It is beautiful though

**Comment by AlexanderUlanH** [comment]
Or just increase shadowlings' light tolerance.  Most of that light is the kind of stuff that intuitively looks like it shouldn't damage a sling.

**Comment by WJohn** [comment]
Thank you, thank you thank you thank thank you.

This is what I always wanted starlight to be.

Also, does this fix low light levels being mega bright in general, like xeno weed nodes or computers?

**Comment by Anonus** [comment]
I think that's still way too bright, the hallway below xeno should not be fullbright with spacelight lighting it.

**Comment by xxalpha** [comment]
is beotiful

**Comment by MrStonedOne** [comment]
old version for comparison:

sybil scaredy spess junk uniform 2015-10-30 103032

**Comment by Xhuis** [comment]
As the person who made shadowlings, :+1:! I can address the issues in the upcoming update for shadowlings.

**Comment by PKPenguin321** [comment]
neat
:+1:
those pictures are wonderfully eerie

**Comment by Jordie0608** [comment]
For comparison, could you take some ~pretty pictures~ of what this'd look like if the light was say, half as bright?

**Comment by MrStonedOne** [comment]
ohhh, this is even better...

space station 13 2015-10-30 212139

**Comment by Xhuis** [comment]
Now _that_ is great.

**Comment by MrStonedOne** [comment]
remaking the rest of the pictures so i can do a new commit.

**Comment by MrStonedOne** [comment]
I now strongly recommend somebody make all of the "space" areas near or within the station have starlight instead. like the one near engi on box, or that 3x3 area in the second picture. or the disposals outlet in the 4th picture, Or engineering's singulo area.

somebody should make all of that starlight and not space 100% bright

**Comment by MrStonedOne** [comment]
Old New: space station 13 2015-10-29 221812
space station 13 2015-10-29 222232
space station 13 2015-10-29 222112
space station 13 2015-10-29 222059
space station 13 2015-10-29 221947

**Comment by MrStonedOne** [comment]
output_hpfdga
Starlight gif

**Comment by PKPenguin321** [comment]
hnng

**Comment by optimumtact** [comment]
Can you do anything about this
Hideous picture of super bright space light

**Comment by Jalleo** [comment]
Newer version is better

**Comment by MrStonedOne** [comment]
@optimumtact already working on it, I'm putting in a way for mappers to mark areas such that they act like space areas when starlight is disabled, but like a normal area when starlight is enabled.

I'm gonna map it on box, but leave the rest to their maintainers.

**Comment by Anonus** [comment]
:+1: :+1: :+1: :+1: :+1:
Really, really good now.

**Comment by WJohn** [comment]
Do we have a "PRETTY" tag in hot pink?

**Comment by Cookiesndip** [comment]
Much better. Still, I think slings need some minor light tolerance now given that it's more diffuse.

**Comment by CosmicScientist** [comment]
:+1:

**Comment by MrStonedOne** [comment]
I just checked... almost all of the starlight illuminated maintenance areas in the dimmest version are not bright enough to hurt shadowlings (but they are bright enough to hurt normal shadow people). Most of them will however be bright enough to prevent healing.

Shadow lings brightness values:
below 20%: heal
20 to 40: no heal, no damage
above 40: damage.

Sadly neither damage nor healing scale with the brightness level (like they should).

Only the tiles that are at least two tiles in of single tile wide paths surrounded on both sides with windows to space reach above 40%. Everything else hovers between 17% and 34% (of maintenance areas near a window to space).

**Comment by Razharas** [comment]
@MrStonedOne tell when its ready

**Comment by MrStonedOne** [comment]
I'd say it's ready now.

I might think of more things to fuck with, but those could go in another PR

**Pull request merged**
