### PR TITLE
[MDB Ignore] OH GOD OH FUCK OH SHIT OH LORD - SPACE AND RUINS IS BROKEN

### PR DESCRIPTION
**Pull request by san7890**
OH GOD OH FUCK OH SHIT OH LORD - SPACE WAS BROKEN

So, for the last few days on production, Space Ruin generation has refused to work. Why is this? It's because in #67107 (cfc233052885dd294b2e7e676caaf84a2a37592b), we repathed `/area/space`  to `/area/misc/space` (lol i should have paid attention to that) without updating everything in code to match. I couldn't seem to get `/area/misc/space` to properly work somehow (this could have also been something I was doing wrong), but I worked it back to just making everything vanilla `/area/space` and all of those unwanted behaviors should be squashed out. Let's get the game working again.

Fixes #67283

:cl:
fix: If you haven't been able to see any working space ruins lately, that's our bad. Should be fixed now.
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Did I test my PR?
- [ ] Yes
- [ ] No
- [X] I thought it would've been fine :(

Jokes aside, I will **more** cautious about extensive map PRs like this in the future.

**Comment by LemonInTheDark** [comment]
Fuking lmao

**Comment by LemonInTheDark** [comment]
image

**Comment by Tastyfish** [comment]
Maybe we should have a unit test for all ruins even though that sounds like a pain in the ass.

**Comment by san7890** [comment]
> Maybe we should have a unit test for all ruins even though that sounds like a pain in the ass.

So forcibly attempt to spawn in all ruins during CI? Hm

**Comment by Tastyfish** [comment]
> > Maybe we should have a unit test for all ruins even though that sounds like a pain in the ass.
> 
> So forcibly attempt to spawn in all ruins during CI? Hm

Yep, just like the clothing test, etc. Slightly unusual because all the other ones live inside the unit_test template but you can just spawn on top of that I'm pretty sure (without looking at the code)

**Comment by Zergspower** [comment]
To be honest it makes sense, because some ruins could go unnoticed and not spawn for months before someone goes 'hey i haven't seen x'

**Comment by Jolly-66** [comment]
Have a mapping CI just select a random ruin (or something that always spawns on live, like KS13 or OldStation)

**Pull request merged**
