### PR TITLE
Adds Xanax

### PR DESCRIPTION
**Pull request by HyruDotExe**
:cl: Xanax
add: Xanax
/:cl:

[why]: Xanax is fun    (I'm not too sure on how to have it automatically update so im gonna drop the updated drugs.dm and reagents)

https://github.com/HyruDotExe/HippieStation/blob/master/code/modules/reagents/chemistry/recipes/drugs.dm - recipe

https://github.com/HyruDotExe/HippieStation/blob/master/code/modules/reagents/chemistry/reagents/drug_reagents.dm  - effects

**delete this, wrong codebase**

### CODE REVIEW

**Comment by fludd12** [comment]
You seem to be trying to shove Hippie's entire codebase in here with one PR. I think you might've... gotten something a *little* wrong.

Also, we're on a feature freeze, so even if this was actually what you wanted it to be, it'd unfortunately be closed anyway.

**Comment by HyruDotExe** [comment]
Sorry but I tried submitting something to the Hippie PRs, but their github
was having issues and redirected to tgstation

**Comment by Iamgoofball** [comment]
wrong codebase

**Comment by HyruDotExe** [comment]
Yeah. I meant to cancel this

**Comment by WJohn** [comment]
Incredible.

**Comment by Jalleo** [comment]
Close the PR please.

**Pull request closed without merging**
