### PR TITLE
Outfits janitor cyborgs with a screwdriver, crowbar, and floor tiles

### PR DESCRIPTION
**Pull request by ghost**
:cl: Nanotrasen Robotics Department
add: To aid in general-purpose cleaning and maintaining of station faculties, all janitor cyborgs are now outfitted with a screwdriver, crowbar, and floor tile synthesizer.
/:cl:

Ever found yourself in this situation?

You can clean up the blood, but that's it! The whole place still looks a bit ripped apart with floor tiles pried up and the maintenance panels on airlocks unscrewed. The engineers messed up the supermatter and are busy salvaging it, and nobody else cares enough to bother.

Now janitor cyborgs have a screwdriver, crowbar, and floor tile synthesizer, to make general maintenance and upkeep of the station's looks more feasible for the one-man army of a cleaner that you are. The screwdriver is used to refasten the maintenance panels to doors, and the crowbar and tile synthesizer is used to pry up broken and burned tiles to replace them, as well as putting down tiles in empty spots where a lunatic with a crowbar pried up an entire hallway.

Because you still lack tools other than this, anything other than the intended purpose is very limited; you can do some basic construction, but whoever you're doing it for will more than likely have to have tools of their own in the majority of cases.

Humorously, this PR also unintentionally gives janitor cyborgs a weapon that does more than 3 damage.

### CODE REVIEW

**Comment by QualityVan** [comment]
Does it only have metal tiles, or various sorts?

**Comment by Xhuis** [comment]
Just metal tiles. I might be able to make a chameleon tile swapper thingy, but that seems like it'd be overkill. Your job is just to keep the station looking passable; if the curator is upset that his gorgeous laminated hardwood floors are replaced with cold, emotionless steel, that's his problem, not yours.

**Comment by GunHog** [comment]
Good stuff. :+1:  Btw Xhuis, what is your avatar, and why are you no longer a slime? It is because Kor ate you?

**Comment by Xhuis** [comment]
That'd be Niko from [OneShot](http://store.steampowered.com/app/420530/OneShot/), which I highly recommend to anyone and everyone. I switched off of the slime for a bunch of reasons, but the main one is that I feel like I'm a much different person than when I started my break four months ago and I wanted to change my avatar to reflect that. Silly, I know, but hey!

**Comment by Xhuis** [comment]
@GunHog That's something I can't tell you.

**Comment by Repukan** [comment]
Or just get a reset module from robotics and become an engieborg?

**Comment by Qbopper** [comment]
@Xhuis re: oneshot

is this game overly spooky

**Comment by Xhuis** [comment]
Resetting to become an engiborg changes your entire functionality. These modules aren't being added to support construction; they're being added to supplement their existing goal of making the station look good.

@Qbopper No, not at all. The paranoia warning is kind of inaccurate, at least for me; the game does make you feel very anxious and unnerved, but not for horror reasons.

**Comment by Qbopper** [comment]
so if I was able to handle the creepy parts of "meta" games like Undertale or Stanley Parable I should be okay

I'm a giant fucking pussy and despise horror games

**Comment by Xhuis** [comment]
Oh yeah, for sure. Undertale was more "horror" in regards to the meta aspects; I'm really trying not to spoil much for either game, but I would say that OneShot is moreso meaningful and somber instead of shock-factor like some of the Undertale moments.

**Comment by Repukan** [comment]
Janitor Borg, being based on janitors, are meant to only clean. If the janitor doesn't get floor tiles nor screwdrivers, why should the Borg? Your sole purpose is to clean shit and pick it up with your bag.

Things looking awful due to damage are the work of engineborgs, which are meant to construct and repair, as is the task of engineers.

**Comment by Xhuis** [comment]
In my own perspective, minor maintenance like keeping the doors and floors tidy can be safely filed away in the "Keeping a Clean Station" cabinet. Tiny stuff like a maintenance panel off on a door while all the wires are intact isn't really damage to repair, it's just an annoyance that interferes in a minor way. It also lets actual damages, like a hacked APC or a minor breach, be left to the engineers and engineering cyborgs, while janitor cyborgs can help keep the normal, non-damaged areas looking good.

**Comment by DoctoreMad** [comment]
>if the curator is upset that his gorgeous laminated hardwood floors are replaced with cold, emotionless steel, that's his problem, not yours.

This comment is an ATROCITY to space station 13.
Chameleon tile floors when?

**Comment by Repukan** [comment]
Your own perspective is retarded then. That's basically repairing the station, not keeping it clean.

How can the Borg know the wires are intact? What happens if someone messed with the wires and shocked them? Is the Borg liable for not making sure nothing was touched?

Engineering borgs have nothing else to do but repair, so I don't know why they would need to have a lighter workload. Fixing is their whole shtick and they're equipped enough to not be overworked or overwhelmed in doing so.

**Comment by PKPenguin321** [comment]
Good PR

**Comment by improvedname** [comment]
SLIP N STAB THE EYES OUT THE MEATBAG

**Comment by Iamgoofball** [comment]
@Repukan 
so if I make a dildo out of floor tile patterns the janitor and janitor borg aren't supposed to remove said vandalism?

**Comment by Xhuis** [comment]
@Repukan I don't think my perspective is "retarded." I'm entitled to my opinion, aren't I? You are to yours, and I'm respecting it, even if I don't agree with it.

Borgs can know if the wires are intact because using a door as a silicon from range opens its control panel, where they can see stuff like bolts, electrification, timing, and safety. If they do refasten the control panel without checking that, then yes, I'd say they're liable for that. Although it's technically repairing the station, I still think that it's minor enough to also be tacked as general maintenance and upkeep. If the wires are damaged, of course, they can alert the crew.

**Comment by Repukan** [comment]
No, post modern art sells for a lot and maybe NT will give you a commendation for it.

**Comment by Repukan** [comment]
Engineering in general doesn't have enough to do besides fixing small stuff or breaches. Quality of life-ing this to another module rather than come up with better ways to flesh them out or make cleaning more important seems like a cheap fix, Even worse so because it's stuff that doesn't even fit the job role the module is based in, nor the module itself.

**Comment by Xhuis** [comment]
I think Engineering has plenty to do. They manage power, can do construction projects, repair large breaches, fix sabotage, keep the air pumping, make sure that Telecomms is online, maintain the supermatter, make the air loop more efficient, enable secondary power sources like the solars and turbine, and change existing areas, to name a few. 

The engineering borg can do almost all of this; meanwhile, the janitor borg cleans - that's it! Additionally, because the engineers and atmos techs are usually doing one of the above, having issues like missing floor tiles and open panels usually comes down to hoping that a passerby has enough goodwill to fix it, and nobody does, to just accept that it doesn't look good.

By them getting these modules, it makes them able to fix those minor problems and make the station look a bit nicer, instead of relying on the engineers or passersby, who are usually doing one of the things I mentioned above, or, if they're not, don't care enough to fix the problem anyway.

**Comment by DoctoreMad** [comment]
I guess they have the same problem as Chaplains or Clowns.
If you're not creative you'll never figure out what to do.

**Comment by Bawhoppen** [comment]
QoL is going too far probably

**Comment by YakumoChen** [comment]
@repukan i can spend entire shifts doing supermatter autism as engineer Borg on its own. I think engi Borgs have plenty to do.

**Comment by Repukan** [comment]
Sure, but unless you're on a non Asimov lawset, you'd have to drop everything to fix breaches and the surrounding fallout if it meant human harm/you were ordered to.

**Comment by Jalleo** [comment]
I support this PR. Floor tiles by itself means diddly squat. All it can do max is repair a breach that has lattices still there. The rest of this is ASTHETICS. All it does is make greyscum ripping up floor tiles feel even more pointless. They used to drag bodies around now its floor tiles being ripped up. Next it will be something else.

**Pull request merged**
