### PR TITLE
nerfs toolboxes

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Nerfs toolboxes damage

## Why It's Good For The Game

It killed us in the toolbox tournament and I have to make sure our name is followed.

## Changelog

:cl:
balance: Toolboxes have been nerfed.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
While you're at it can you nerf bears

**Comment by JohnFulpWillard** [comment]
no they didn't kill us

**Review by tralezab — APPROVED** [review]
code looks good 😋

**Comment by Paxilmaniac** [comment]
Understandable

**Comment by qbmax32** [comment]
please remove terry too

**Comment by scriptis** [comment]
looks good to me

**Review by Imaginos16 — APPROVED** [review]
W PR

**Comment by Capsandi** [comment]
Toolboxes have been too powerful for too long, glad they're getting knocked down a peg

**Review by MrMelbert — APPROVED** [review]

**Review by Watermelon914 — APPROVED** [review]

**Comment by RigglePrime** [comment]
Amazing PR

**Comment by LinusMatysiak** [comment]
L

**Comment by bruhman8ghughug** [comment]
you forgot to nerf the throw force by 0.1 aswell

**Comment by Cheshify** [comment]
Good PR

**Comment by DAKKA-WAAAGH** [comment]
Based and QOLpilled

**Comment by tralezab** [comment]
> you forgot to nerf the throw force by 0.1 aswell

when i was playing i didn't ever do that so

**Comment by JohnFulpWillard** [comment]
none of us died to a toolbox throw

**Review by Kylerace — APPROVED** [review]
code compiles 👍

**Comment by Kubisopplay** [comment]
Speedmerge

**Comment by JohnFulpWillard** [comment]
https://github.com/tgstation/tgstation/pull/72552 is the better alternative

**Comment by Zonespace27** [comment]
image
Skyrat stays winning

**Comment by JohnFulpWillard** [comment]
i would hate to be a manuelite right now

**Pull request closed without merging**
