### PR TITLE
No roundstart playable MULEs / Trampling requires hacking

### LINKED ISSUE #76926: Possessed MULEbots can run over living players
I wasn't actually going to post this but I think if I get one more report of "HELP THE MULEBOT JUST RAN ME OVER BAN HIM" I'm going to pop a blood vessel.

To my knowledge, a MULE with a personality is not supposed to be able to run over people, yet here we are. If they are lying on the ground, they can run over them and do just a stupid amount of brute. This probably shouldn't be possible.

To be fair, cleanbots can do something similar, but their knives do like 5-10 brute while driving over someone with a MULE does like 50.

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Prevailing feedback has been:
- The player base cannot be trusted to control MULEbots.
- It should be clearer what bots can and can't do.

The former is easy to fix.
The latter is sort of a matter for policy but I'm going to investigate giving bots a rudimentary laws system. Plus that sounds much more controversial than this so I am going to atomise this outside of that PR.

MULEbots can still be set to allow sentience by cargo technicians, but don't start that way.

ADDITIONALLY this PR just changes it so that MULEbots do not crush people unless:
- They have been emagged.
- Their safety wire has been cut.
Either means works, so it's not too hard to access for nefarious purposes, but hard to do to yourself. 
Otherwise they just slow down for a few seconds instead.

Also fixed an unrelated name bug while I was there.

Closes #76926

## Why It's Good For The Game

Players would take them, not deliver any cargo, and repeatedly ask people to lie down in front of them.
Plus Tram has 5 of the things which is frankly too many to be wandering around the bar.

## Changelog

:cl:
balance: You can't possess a MULE as soon as the round starts, someone will have to give you permission.
balance: MULEbots no longer crush prone characters unless they have been hacked (or emagged).
fix: Bots can put numbers in their names, what with being robots.
admin: Adds attack logging when certain wires are cut (for instance: MULEbot safeties)
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
Base sentient MULEbots should have their crushing significantly nerfed, something closer to clown car flattening. Make it funny and not broken. Unless it's emagged, then you can go wild again.

Here's my ideal table:

MULEbot: No Crush
Sapient MULEbot: No Crush
Sapient Hacked MULEbot: Flatten
Hacked MULEbot: Crush
Emagged MULEbot: Crush
Sapient Emagged MULEbot: Crush

**Comment by SomeoneYouProbablyKnow** [comment]
> Base sentient MULEbots should have their crushing significantly nerfed, something closer to clown car flattening. Make it funny and not broken. Unless it's emagged, then you can go wild again.
> 
> Here's my ideal table:
> 
> MULEbot: No Crush Sapient MULEbot: No Crush Sapient Hacked MULEbot: Flatten Hacked MULEbot: Crush Emagged MULEbot: Crush Sapient Emagged MULEbot: Crush

Occam's razor : it's just easier to make em not sentient shiftstart.
But fear not, any QM worth their salt will activate them all (which conveniently places the blame on them should those bots decide to run people over)

**Comment by carlarctg** [comment]
> > MULEbot: No Crush Sapient MULEbot: No Crush Sapient Hacked MULEbot: Flatten Hacked MULEbot: Crush Emagged MULEbot: Crush Sapient Emagged MULEbot: Crush
> 
> Occam's razor : it's just less complicated to make em not sentient shiftstart.
> 
> But fear not, any QM worth their salt (me obviously) will activate them all (which conveniently places the blame on the QM should those bots decide to run people over)

You are misusing occams razor with you yourself saying that this wouldnt actually solve any problems, just shift blame (which isnt even accurate anyways as those mulebots aren't solo antagonists or beholden to you)

**Comment by ExcessiveUseOfCobblestone** [comment]
if someone wants to be a package transport bot i see no problem with that.

This really should be on the admins to enforce that bots dont just use the role to play as calvary for sec/validhunters if not to be the validhunter themselves.

**Comment by JohnFulpWillard** [comment]
we should remove mules being able to run over people unless emagged or something so they fit in with every other bot, maybe

**Comment by Capsandi** [comment]
> if someone wants to be a package transport bot i see no problem with that.

The thing is that nobody actually wants to be a package transport bot and the only interest in these roles is to grief or to metagrudge. The moment that the policy and code scaffolding is set up to support the popular new(no longer gated behind robotics cooperating so effectively new) bot roles, the people playing it will either leave due to a lack of ability to grief or because the role is knowingly designed to have less impact than even maintenance drones. Separating bots from PAIs was a good move but there's no future in regularly playable bots.

**Comment by Jacquerel** [comment]
> we should remove mules being able to run over people unless emagged or something so they fit in with every other bot, maybe

Probably true, I am still making the initial change on top of that though due to general dereliction of duty by mulebot players.

**Comment by SomeoneYouProbablyKnow** [comment]
> You are misusing occams razor.

Well, i'm slightly twisting it for emphasis but sure. You DO get what i'm saying though.

Honestly running people over is kinda nuts and is an unhealthy ability for a cargo runner bot, but that's out of scope. To fix mulebots causing havoc it's best to first do this then figure out crushing.

If you do decide to change crushing, don't lock it behind an emag so that it's avaliable to other antags (i'm mostly thinking about revs here). Probably not emp tho, we know how defibs turned out.

**Comment by ATH1909** [comment]
> And this is the ONLY thing they have.

mulebots can also strap other bots to themselves to sort of approximate their roles (e.g. picking up a medibot and carrying it to people), which I think is neat

or do deliveries, although I admit that that's not what most players pick mulebot for

**Comment by Jacquerel** [comment]
> If you do decide to change crushing, don't lock it behind an emag so that it's avaliable to other antags (i'm mostly thinking about revs here, mulebots ARE the proletariat). Probably not emp tho, we know how defibs turned out.

I've locked it to emag _or_ the usual wire hacking you would use to remove the safeties, so it is reasonably accessible to any cargo tech who can easily print tools.

**Comment by ExcessiveUseOfCobblestone** [comment]
> The thing is that nobody actually wants to be a package transport bot and the only interest in these roles is to grief or to metagrudge. The moment that the policy and code scaffolding is set up to support the popular new(no longer gated behind robotics cooperating so effectively new) bot roles, the people playing it will either leave due to a lack of ability to grief or because the role is knowingly designed to have less impact than even maintenance drones. Separating bots from PAIs was a good move but there's no future in regularly playable bots.

people used to play cargo tech when it was just package transport, if people rarely take the role thats fine but I dont see a problem with the option being available. Laws and policy around using the role outside of the intent would equally fix this, if it goes largely unused its not a problem since we agree its a very minimal impact role.

**Comment by TheVekter** [comment]
> > If you do decide to change crushing, don't lock it behind an emag so that it's avaliable to other antags (i'm mostly thinking about revs here, mulebots ARE the proletariat). Probably not emp tho, we know how defibs turned out.
> 
> I've locked it to emag _or_ the usual wire hacking you would use to remove the safeties, so it is reasonably accessible to any cargo tech who can easily print tools.

If we're doing this, can we make it explicitly log to admin logs when someone's hacked that wire, assuming it isn't already? It'd make our lives a lot easier.

**Comment by optimumtact** [comment]
I'm blocking this until you remove the emag requirement for trampling.

**Pull request merged**
