### PR TITLE
You can make garbage bags out of plastic

### PR DESCRIPTION
**Pull request by wesoda25**
## Why It's Good For The Game

i was rather disappointed that i couldnt make a garbage bag to keep my weed in as a botanist

## Changelog
:cl:
add: You can now make garbage bags out of plastic
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
put it in the autolathe

**Comment by wesoda25** [comment]
Ok but I want to keep it as plastic buildable too cause its fun

**Comment by Fikou** [comment]
ok dont put it in the autolathe if its still going to be made with hands

**Comment by wesoda25** [comment]
🤷‍♂

**Comment by Tlaltecuhtli** [comment]
2 op

**Comment by trollbreeder** [comment]
Do you ever feel, like a plastic bag?

**Review by kriskog — CHANGES_REQUESTED** [review]
Garbage bags are too useful sadly, they are essentially just better belts. Make them unable to be equipped and I will consider this.

**Comment by wesoda25** [comment]
Ugh why do powergamers have to ruin everything. I’m really not interested in nerfing garbage bags with this PR, I just wanted to make them a bit more accessible. Is there any other compromise you would consider?

**Comment by kriskog** [comment]
The only thing balancing them (badly) right now is availability. Someone needs to do it, might as well be you 🙂

**Comment by Shadowflame909** [comment]
What if garbage bags were like

The duffelbags of belts.

More space but they slow you down

**Comment by Bawhoppen** [comment]
I think the ideal way to nerf garbage bags as a storage container, is to make them be inconvenient as one in the same way they are in real life: organization. Having all the slots be randomized or having it take a few seconds to sort through it before opening it, and closing automatically when you start moving (or both), I think would be the best way to handle them.

**Comment by Fikou** [comment]
> I think the ideal way to nerf garbage bags as a storage container, is to make them be inconvenient as one in the same way they are in real life: organization. Having all the slots be randomized or having it take a few seconds to sort through it before opening it, and closing automatically when you start moving (or both), I think would be the best way to handle them.

randomizing slots doesnt matter when they are all buckshot shells

**Comment by wesoda25** [comment]
> I think the ideal way to nerf garbage bags as a storage container, is to make them be inconvenient as one in the same way they are in real life: organization. Having all the slots be randomized or having it take a few seconds to sort through it before opening it, and closing automatically when you start moving (or both), I think would be the best way to handle them.

I suggested something along these lines but it was turned down. We decided the best compromise would be to just lock the ability to hip weild trash bags behind the scrubbing skill, so that jannies can do it and not other people (without cleaning a lot).

**Comment by Bawhoppen** [comment]
Having it be decided by an arbitrary skill is silly. Just make it not equipable by anyone, since it can go in the janicart anyways...

**Comment by optimumtact** [comment]
agreed with baw

**Comment by wesoda25** [comment]
not interested

**Pull request closed without merging**
