### PR TITLE
Resprites the fork!

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR resprites the fork.

image

## Why It's Good For The Game

The old fork was really tall and black.

Forks are really hard to sprite but i think this is an improvement.

## Changelog
:cl:
imageadd: The fork has a new sprite.
/:cl:

### CODE REVIEW

**Review by Twaticus — APPROVED** [review]
the spork is no more

**Comment by cacogen** [comment]
The size of the head compared to the handle is strange.

**Comment by maxymax13** [comment]
only a.. forkful?
also add a spork item to make up for the loss smh

**Comment by ninjanomnom** [comment]
@Krysonism let a maintainer know when the conflict here is dealt with and they can just merge right away

**Comment by optimumtact** [comment]
@Cyberboss stop marking it as a draft, otherwise I can't see if it conflicts still or not

**Comment by Cyberboss** [comment]
@tgstation-server will remove the merge conflict label once it's fixed

**Comment by Krysonism** [comment]
Totally forgot about this. Will fix conflict tonight

**Comment by Cyberboss** [comment]
I think you made a mistake, now there's no diff at all.

**Comment by Cyberboss** [comment]
Don't know how knowledgeable you are in git, but to get your work back you can run `git checkout 2afa36a`

**Comment by maxymax13** [comment]
22 day pr life cycle.. you got all your gbp, but at what cost

**Pull request merged**
