### PR TITLE
Removes virus DNA Restoration's healing overlay

### PR DESCRIPTION
**Pull request by XDTM**
First off, it was firing every tick since the check for unclean mutations always returned true. And second, i doubt it's very important to convey to everyone around you that you just healed some radiation/brain damage/dna compared to actual healing symptoms.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
Better solution: Remove healing viruses

**Comment by JJRcop** [comment]
It was put in so that way people know you have a healing virus when they fight you.

**Comment by XDTM** [comment]
I am not speaking of normal healing overlays; they're still in there and have a good reason to be. What i'm changing is the DNA restoration, which is not really combat-related unless you're really counting on ratiation or mutations to finish someone off.

**Comment by JJRcop** [comment]
Oh, I see, I wish I read the title...

**Pull request merged**
