### PR TITLE
fixes plastitanium nodiagonal map editor icon walls

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

fixes plastitanium nodiagonal map editor icon walls

## Why It's Good For The Game

fixes plastitanium nodiagonal map editor icon walls

## Changelog
fixes plastitanium nodiagonal map editor icon walls

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
does this fix plastitanium nodiagonal map editor icon walls?

**Comment by Fikou** [comment]
> does this fix plastitanium nodiagonal map editor icon walls?

this fixes plastitanium nodiagonal map editor icon walls

**Comment by Pumpkinoe** [comment]
i'm glad this fixes plastitanium nodiagonal map editor icon walls

**Comment by Rohesie** [comment]
i'm conflicted about this fixing plastitanium nodiagonal map editor icon walls

**Review by Rohesie — APPROVED** [review]

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
