### PR TITLE
Removes telescience entirely

### PR DESCRIPTION
**Pull request by ChangelingRain**
There are no good uses of this thing.
It's got to go!

Additional reasoning as to why it's complete shit is available on request or when someone tries to provide a "good" use of it.

### CODE REVIEW

**Comment by lzimann** [comment]
Good ridance.

**Comment by F-OS** [comment]
Kneejerk pr because some dumb player abused it constantly also freeze :-1: :x: :100:

**Comment by lzimann** [comment]
Removals are freeze friendly.

**Comment by ChangelingRain** [comment]
Removals are allowed during a freeze.

**Comment by F-OS** [comment]
My other point still stands, this is not a codebase issue, removing a feature just because some idiot abused it is highly dumb and sets a bad precedent.

**Comment by GunHog** [comment]
I disagree with the notion that removals are "freeze friendly". It is a balance change, and those are supposed to be forbidden during it.

**Comment by ChangelingRain** [comment]
To clarify, it's being removed because the person who abused it is just one more person in a long line of telescience abusers, all of which had similar issues which nobody has made any headway towards fixing.

And if you think removals aren't freeze-friendly, you'll need to talk to Cheridan, probably.

**Comment by Qbopper** [comment]
I think the question to ask here is "what does telesci add to the game that is positive"

I can't think of any positive uses myself

**Comment by F-OS** [comment]
> To clarify, it's being removed because the person who abused it is just one more person in a long line of telescience abusers, all of which had similar issues which nobody has made any headway towards fixing.

> And if you think removals aren't freeze-friendly, you'll need to talk to Cheridan, probably.

Admin issue, not player issue, clarify the rules/ban abusers, also a positive use is bringing people back into the round by grabbing them from space with the crew monitoring console

**Comment by F-OS** [comment]
also, very simple fix for abusing it to teleport the nuke 'if(istype(A, /area/syndicate_mothership) || (istype(A,/area/shuttle/syndicate)) then 
    telefail()
    temp_msg = "ERROR! Sector is outside known time and space!"
    return'

**Comment by XDTM** [comment]
It's the only teleportation mechanic that doesn't require the player to have visited the target area first. It also works well with space exploration, and can be used to save dead people who use sensors (nobody).

The issues seem to be, as far as i can tell:
- Being able to steal important items without prior coordinate knowledge due to existing coordinate maps.
- Being able to steal something that is standing still without any indication until too late.
- Being able to send something (like a bomb) without any indication until too late.

I can't fix 1, but the others should be mitigated by a channeling period before the teleport, during which there should be an overlay over the target area, giving people time to react. Anti-teleport beacons could be introduced to protect high-security areas like the armory or the nuke shuttle as well.

**Comment by F-OS** [comment]
You could probably blacklist the armory or something

**Comment by XDTM** [comment]
Mechanically i can definitely see that it's clunky as it's based on calculations that are always done through an external program, making it an artificial timer when setting the target rather than an ingame one.

It also give pretty extreme freedom on targeting once upgraded enough. My idea on _those_ issues is to make the targeting immediate (no pointless calculations) but with a wait period ('calculating target...') scaling based on distance. Teleportation back and forth in unhampered until re-swapping locations.

**Comment by Kromgar** [comment]
@Qbopper 

How about retrieving dead bodies out on lavaland? Back when it was actually part of sci there were tons of telesci guys who managed that.


I used it one time to teleport people for conversion

**Comment by Jalleo** [comment]
Sadly telescience is in one of those states where it is useful but abuseable. Solution make it only able to teleport peope with suit sensors fully on or objects with a sensor attached to it.

**Comment by Cyberboss** [comment]
THE OTHER PR WAS 1000000000000000000000000000000 TIMES BETTER

**Comment by XDTM** [comment]
I'll code the stuff i suggested tomorrow if this isn't speedmerged

**Comment by lzimann** [comment]
@XDTM That won't make telesci any better.

**Comment by uraniummeltdown** [comment]
Kneejerk PR after a ban
The players find it fun, it's very very rarely built due to material costs. Great for saving people and exploration. Stop making retarded removal of fun PRs Joan, you rarely play, go buff clockcult some more or fix bugs instead of trashing a beloved feature.

**Comment by ExcessiveUseOfCobblestone** [comment]
Using telesci to tp in bombs to known syndicate shuttle locations is a direct violation of our rules though.

>I can't think of any positive uses myself

It's a teleporter without the requirement of having a beacon, so whatever positive benefits the teleporter has, the telepad has that+

**Comment by ShizCalev** [comment]
@Jalleo "objects with a sensor attached to it."

Did I hear FULTON?

**Comment by Repukan** [comment]
Remember how we had to remove space bar because people would meta and rush telescience by looting that teleporter

**Comment by Iamgoofball** [comment]
Telesci is for space ruins

**Comment by Jordie0608** [comment]
`gps.dm` and `bscrystal.dm` have changed line endings.

**Comment by lzimann** [comment]
@Jordie0608 `gps.dm` had a trailing return removed, while `bscrystal.dm` had no difference

**Comment by Jordie0608** [comment]
gps

bsc

@lzimann I see the same but only with `?w=1`, this indicates eol change.

**Comment by lzimann** [comment]
We don't enforce end of lines, so?

**Comment by Jordie0608** [comment]
It makes for messy history and is easy to rectify.

**Comment by PKPenguin321** [comment]
Pretty lame, telesci has lots of fun moments (or at least had, I remember using it a lot before it was made not-roundstart) and you're just using that ban as an excuse to gut it when that ban really barely had anything to do with telesci

**Comment by vcordie** [comment]
no look, it needed to be gutted. it's terrible. it can't be balanced.

**Comment by PKPenguin321** [comment]
i hate to use this meme but improve dont remove

**Comment by vcordie** [comment]
there is no improving it. at all. there really isn't. either its too nerfed to be useful, or its too powerful. there isnt a middleground, not with this mechanic.

**Comment by PKPenguin321** [comment]
be more creative

**Comment by vcordie** [comment]
many long nights were spent trying to think up ways to balance and fix telesci and...it just can't be done.

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/tgstation/pull/25926

**Comment by Iamgoofball** [comment]
You're mad you got banned I'll make a fix

**Comment by lzimann** [comment]
@tgstation/commit-access Thoughts on this?
Telesci is a mess and the game is honestly better without it.

**Comment by Iamgoofball** [comment]
I'll just make it locked to space ruin z levels

**Comment by Iamgoofball** [comment]
Since it's designed for space shit exploration

**Comment by optimumtact** [comment]
part 1 of 3, accepting telesciences death

**Comment by Durkel** [comment]
The feeling when goof is right for once but everyone ignores him because he's goof.

Telesci was added with the intention of adding space ruins for it explore,  but the original maker got lazy and never finished the job. I think what goof is suggesting about locking it to non station z-levels would be good. You could fluff it as all the shit on the station causes interference and it's impossible to get a good lock on the z-level.

**Comment by optimumtact** [comment]
Telesci was added as a way to get loot from off station, it has no engaging mechanics, it's entirely a way to get items by putting in some numbers into a calculator.

It is completely unredeemable.

**Comment by Iamgoofball** [comment]
it was supposed to be used to beam people over to space ruins and stuff (hence why all the areas for it were added) but it never got implemented

**Comment by ChangelingRain** [comment]
But why would you beam people over if you can just steal the loot?

**Comment by kevinz000** [comment]
improve don't remove.

**Comment by kevinz000** [comment]
alternatively it could be you know, reworked. or just make it work on large objects only and not normal loot because the portal is in the air and not floor level. hell, make only mobs able to use it. outright removal is bad.

**Comment by optimumtact** [comment]
or you know, we could remove it because it's languished for x many months until the threat of removal came up and you suddenly decided it could be saved.

**Comment by IlyaIU** [comment]
inb4:
- PR would got closed
- People who said "improve dont remove" will do nothing
- 0 PR related to telesci in 1 year
- Someone abuses telesci and gets banned
- New remove PR
- "improve dont remove"


Speaking of "improve" part, how often do you improve features considered shitty and abuseble? How much features with bad design you turned into balanced playable stuff?

Fucking stuff which was not being touched in years should be removed. Im suggesting keep this PR open for month or two and wait for some "improve" PRs.

**Comment by IlyaIU** [comment]
@optimumtact, indeed. It means none of them actually cares about telesci, they just want that big list of features in the game and they will yell at anyone who would take anything from said list

**Comment by PKPenguin321** [comment]
>•Someone abuses telesci and gets banned

Not what happened, the ban was for metaing the ops ship, could have happened just as easily with a space suit

>or you know, we could remove it because it's languished for x many months until the threat of removal came up and you suddenly decided it could be saved.

It's not languished, it's still in the game and used a bit. You just don't hear about the not-controversial cases of its use. Confirmation bias

**Comment by Kromgar** [comment]
Or... OR how about we make it so telesci can only teleport carbon mobs?


DID ANYONE THINK OF THAT?

**Comment by ExcessiveUseOfCobblestone** [comment]
> Feature with potential to grief exists.
>> someone grieffed with the feature
>>> said individual got banned

Remove fuel tanks too because of welderbombers.

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation-old/pull/413

possible reference to changing telesci, it gimps a lot of its functionality but it also means people need to leave obvious indicators that they're going to try and use telesci to get to places. This also kills meta with maps but it also means you can't teleport around into space.

**Comment by XDTM** [comment]
>nobody suggesting improve ideas

I made a few, don't ignore those. It fixes stuff disappearing without counterplay and makes isolated areas protected roundstart, since there'd be nobody to keep an eye on them.

>nobody touched it so remove it

Remove fireaxes, nobody changed them in the last year and suddenly i think they have to go

>Adds nothing to the game

It's really fun, it adds a cooperative element, since it works best if you have someone to recall you, can be used for space exploration, corpse/miner recovery or tons of antag gimmicks.

**Comment by Grazyn** [comment]
Vcordie coming here to advocate telescience removal when he's the one who started looting space bar/hotel teleporter at roundstart, constantly used it to break nuke ops rounds with metaknowledge of the possible landing zones etc. etc. is hilarious. That said, he does have a point. If someone wants to abuse telescience, there's no limit on what they can do with it.

Now if coders decide it's worth a rework, please remove the need for an external program/coord maps because that has always reeked of metagaming to me (obviously I'm guilty of that too). Remote telebombing the brig/AI sat/cult base is fun but it can probably be done in a different way, that requires to expose yourself a bit more.

**Comment by jughu** [comment]
>requires you to do math
>requires you need amount of crystals to build
>requires you need amlunt of crystals for increased range
>get cucked by telescience
>telescience op remuv
>people say it requires no work because some nerd made a spreadsheet
This is why we cant have things

**Comment by jughu** [comment]
Also didnt goon had the factor thingy you had to calculate first before you could really start

**Comment by MrPerson** [comment]
There's nothing worth salvaging about telescience. It's not fun to do, it's only interesting in that it's abusable. But hey I tried to warn you guys and remove telescience outright but no dice. Have we learned our lesson yet?

**Comment by XDTM** [comment]
That's just not true, it's like saying that ss13 is not fun because you're just typing on a keyboard and looking at a screen. And it's like saying that virology is abusable because you can make heal viruses; it's a tool that has an effect. If the effect is too strong it can be toned down.

**Comment by Militaires** [comment]
ITT MAN WHO DOESNT UNDERSTAND TELESCIENCE ATTEMPTS TO REMOVE IT.

>There are no good uses of this thing.
>There are no good uses of this thing.
>There are no good uses of this thing.

You're plain wrong @changelingrain, but I don't expect that to change anything cause you'll just ignore the comments disproving your points.

LIST OF THINGS TELESCIENCE IS GOOD FOR:

- Teleporting injured crewmembers to medbay
- 
- Teleporting dead crewmembers to medbay
- 
- Teleporting miners in trouble back to the station
- 
- Teleporting resources back to science immediately
- 
- Teleporting equipment to miners immediately
- 
- Teleporting upgrades to station departments immediately
- 
- Carrying out hard space expeditions using warp-ins and outs
- 
- Teleporting people across the station as the prime mode of transport
- 
- Teleporting criminals to security cells
- 
- Teleporting the clown to lava
- 
- Teleporting the mime to lava

cutting this out entirely because a scientist bombed clock cult bases with it is retarded and you should kill yourself

>BUT BMAN, THEY ARE ABUSING IT REEEEEEEEEEEEE

then add consequences to telescience you dumbfuck, you guys talk big on improve not remove111 then go back and turn the other way.

**Comment by lzimann** [comment]
Telesci is not an engaging mechanic, you type numbers in a calculator, type numbers back in the telesci console, bam! you teleported something to you, that's all.

**Comment by uraniummeltdown** [comment]
So what? What do you expect telesci to do but teleport things to and from places? People like to use it, it's a tool to achieve goals with. Most mechanics in this game are just click click click receive upgrade click click

**Comment by MMMiracles** [comment]
I think the issue stems from the fact the non-antagonistic uses of telesci are rarely actually done. Sure, you can save people and teleport useful stuff around, but I'm pretty sure I could count the amount of times that has actually happened in total on both of my hands.

The point is that while it does have productive use, you're more than likely to see it being used more as a theft device/space-loot grabber.

**Comment by Militaires** [comment]
@lzimann 

Sec is not an engaging mechanic, you assign statues to people, click those people with your taser, bam! you upheld the law something to you, that's all.

RnD is not an engaging mechanic, you click items on the machine, activate the machine with the RnD console, bam! you got levels, that's all.

Cargo is not an engaging mechanic, you click orders in a console, put crates and click SEND SHUTTLE back in the cargo console, bam! you got points something to you, that's all.

Medical is not an engaging mechanic, you click chemical names in a sleeper ,bam! you healed someone, that's all.

Traitor is not an engaging mechanic, you click ebow in your uplink, click the ebow then people until they go horizontal and dont go back up, bam! you traitored someone dead, that's all.

**Comment by duncathan** [comment]
I'm a very strong supporter of the ideal of "remove don't improve". The code remains in the history. It's not like this hasn't been coming, as you can see that several maintainers don't like telescience. This PR does nothing to stop someone down the line coming along and making whatever significant changes are necessary to stop telescience from being completely terrible. Unless you actually go through the effort of improving it yourself, spewing "improve don't remove" is more knee-jerk than this.

Anyone who thinks telescience is not inherently worse than other gameplay is stupid. Telescience is more or less useless without an outside tool, and overpowered with one. How are you supposed to balance that? Don't call a matter of fucking abysmal design a "player/admin" issue.

**Comment by jughu** [comment]
Lets remov belts

**Comment by XDTM** [comment]
How are you supposed to balance that? It's not rocket science, make it a straightforward coordinate and add an ingame timer instead, so there's no disparity between players who have and don't have the tool.
And i don't see many reasons for which it's _bad_, all i see is that they can loot ruins, which due to randomization it's only true for gps-loaded ones, and that it's only good for antags, which first isn't true, and second, see toxins.

**Comment by lzimann** [comment]
Toxins is another department that could just be removed entirely(atmos already does the job, and better) without any loss of gameplay.

**Comment by Kromgar** [comment]
Can we just make telesci a body recovery unit?

**Comment by F-OS** [comment]
First they came for NTSL, and i did not speak out, because i did not use ntsl, then they came for telescience, and i did not speak out, because i did not use telescience, then they came for toxins, and again i did not speak out, then they came for me, and nobody spoke out for me

**Comment by Repukan** [comment]
Are we seriously comparing removal of overpowered and flawed designs to the 'caust victims?

**Comment by F-OS** [comment]
`Are we seriously comparing removal of overpowered and flawed designs to the 'caust victims?`

Yes

**Comment by Repukan** [comment]
Oy vey

**Comment by BeeSting12** [comment]
@Militaires 
Some of those things require player skill. Telescience is plugging numbers into a spreadsheet and bam you're done

**Comment by Robustin** [comment]
There's a long, long list of things that telescience is good for. In reality nobody is going to assemble a telescience setup so they can dispatch supplies to a beleaguered department or to send captures criminals to the brig. It's just a silly way to fuck people over with no warning.

I believe that telescience can be reformed but you know what the best way to do that is? Remove the current abomination so that a telescience lover can step up and come up with a sustainable design.

Otherwise all the people here claiming it can be fixed are going to go back to giving 0 shits once the removal PR is closed and they have no incentive to improve it. 

Also I think removals not related to bugs are silly during a freeze but that aint my call.

**Comment by duncathan** [comment]
if the new system is genuinely good it will be merged. we have no obligation to merge or maintain a shitty system.

**Comment by XDTM** [comment]
I'm fine with that, although i feel that the whole thing is biased towards removal, since the removal can work in the freeze and any possible rebalance prs will instead be closed.

**Comment by duncathan** [comment]
nobody's gonna make anything good enough before the end of the freeze anyway lol

**Comment by Osokorn** [comment]
"I am dead, nerf pls"

**Comment by WJohn** [comment]
I'd say if it's so bad and abusable, at the *very least* make it unbuildable via R&D, but still present for admins or map makers to spawn as SOME sort of sciency equipment to add to maps/ruins/away missions.

**Comment by Cyberboss** [comment]
That's what I'm saying, #25923 is a much better alternative to this

**Comment by Iamgoofball** [comment]
listen

here's what I'm going to do

1. telesci can only transport people
2. telesci can only teleport to space ruin z-levels
3. space ruins get random "faint signal" style markers for use with telesci to flag down ruins
4. ruin budget increased
5. science gets buildable fulton setups for use to pull loot and stuff back to the station

**Comment by Jazaen** [comment]
Goof, make it also work for lavaland.

**Comment by Iamgoofball** [comment]
@KorPhaeron opinion on touching lavaland with new telesci?

**Comment by Iamgoofball** [comment]
i can PR this tonight IF you fucks are okay with it

**Comment by lzimann** [comment]
Not okay and what you are doing just means telesci will be used even less.

**Comment by Jazaen** [comment]
The alternative to limiting it is total removal, which will mean it won't be used at all.

**Comment by Iamgoofball** [comment]
1. Please explain as to why this will make telesci be used less, if it is hooked up to allow you to properly reach the previously unused space ruins now.

2. Please explain why that isn't OK, because it addresses the current core problems of telesci allowing me to focus it on what it was originally intended for.

**Comment by XDTM** [comment]
I'm making the changes i suggested instead, i feel like telesci should still work on items

**Comment by Niknakflak** [comment]
For once, goof's idea isn't terrible.  You can't argue that telescience will be used less lzi, because it's basically not used period right now.

I think trying goof's idea would be good because then it would take two things that nobody ever uses, telescience and space ruins and attempts to make them a single possibly only sorta used thing.  

Also, XDTM is right when he says that basically if this is removed, "git history" or not, who the fuck are you kidding Dunc, it'll probably never get back in.  That is the most slippery slope bullshit argument I've ever heard for saying it's ok to gut stuff more easily.  Once stuff is reverted or merged, it's almost always a complete bitch to either add it back or revert the feature completely.  Stop kidding yourself

**Comment by duncathan** [comment]
@iamgoofball I like the idea but naturally the pr will be closed during the freeze. Please go ahead and make it tho, that sounds much better than the current abomination

**Comment by KorPhaeron** [comment]
Why don't you just remove the boards from the RD console if goof is going to readd it? Would be less work for him putting things back and easier to see what lines he actually changed when reviewing

**Comment by Cyberboss** [comment]
Close this, reopen @xxalpha s disable PR

**Comment by optimumtact** [comment]
Closed in favour of disabling telescience until post freeze

Goof's remake idea is the only one that will be accepted, if it doesn't appear within a month post freeze telesci will go permanently

**Comment by Iamgoofball** [comment]
u got it boss

I should have time to do it post-freeze but if something comes up IRL wise I'll let you know here, in which case yeah go ahead and toss it until I get around to it

**Comment by jughu** [comment]
When our !!FUN!! is in goofs very hands we must hope

**Comment by Kromgar** [comment]
@Iamgoofball I'm pretty sure Telesci being corpse retrieval on lavaland would be fine

**Pull request closed without merging**
