### PR TITLE
Penthrite no longer makes you immune to staminacrit, among other things

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR should fix all of the issues mentioned in https://github.com/tgstation/tgstation/issues/53202.

## Why It's Good For The Game

Last I checked, no miner nerfs have been PR'd to /tg/ in the past week, so we're behind on our quota.

## Changelog
:cl: ATHATH
fix: Penthrite no longer makes you immune to staminacrit.
fix: Penthrite no longer has an effect on people who can't metabolize it.
fix: Spam-buckling and spam-unbuckling someone to/from a stasis bed while they have penthrite in their system will no longer cause their crit_threshold to eventually rise above their maxHealth, effectively trapping them in a permanent state of being in critical condition.
fix: If you regain the ability to metabolize chems while you have penthrite in your system, you'll also regain the special traits that penthrite's supposed to give you.
balance: Penthrite now gives you the TRAIT_NOCRITDAMAGE trait (in addition to the other traits it gives you), so as to better mimic its previous/intended effects.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
Changelogs are written mostly for players, not for coders. Can you try and avoid internal terms like `TRAIT_NOCRITDAMAGE` and `crit_threshold`?

**Comment by ATH1909** [comment]
> Changelogs are written mostly for players, not for coders. Can you try and avoid internal terms like `TRAIT_NOCRITDAMAGE` and `crit_threshold`?

eh, I feel like those names are pretty self-explanatory, no?

**Comment by Jared-Fogle** [comment]
It's just something I try my best to shy away from--you can just as easily say "Penthrite now stops suffocation in crit" or similar.

**Comment by ExcessiveUseOfCobblestone** [comment]
unfortunate that you're banned from webbiting

**Comment by ExcessiveUseOfCobblestone** [comment]
feel free to rePR not webbited and tested.

**Pull request closed without merging**
