### PR TITLE
Revert "Station hardsuits no longer have in-built jetpacks"

### PR DESCRIPTION
**Pull request by Core0verload**
Reverts tgstation/tgstation#18028.

Someone kick @optimumtact in balls for merging this hated, balance meme'd, feature frozen PR.

### CODE REVIEW

**Comment by MMMiracles** [comment]
sorry bub feature-freeze

**Comment by Supermichael777** [comment]
why do we keep him around?

**Comment by lzimann** [comment]
I don't mind this gone, but it's almost like this feature freeze is some sort of joke that no one is caring about

**Comment by Imagebard** [comment]
>PR is merged in the middle a feature freeze
A revert to that PR is then blocked because of the feature freeze

Feature Freezes don't work here either but at least we TRY not to be this blatant.

**Comment by GunHog** [comment]
This is a violation of the feature freeze, @KorPhaeron himself said that balance memes were not allowed. That PR should not have been merged.

**Comment by MMMiracles** [comment]
forreal though this feature freeze probably should of been actually announced and given a start date to prepare instead of just dropping it out of nowhere and half-assedly enforcing it.

**Comment by KorPhaeron** [comment]
probably

**Comment by xxalpha** [comment]
I approve of this revert.

**Comment by Jazaen** [comment]
> I approve of this revert.
Even the person who made the damn thing wants it gone!

**Comment by optimumtact** [comment]
The design lead and a senior headmin have approved this removal, if you don't like it, you may choose to play elsewhere

**Comment by optimumtact** [comment]
Actually that's not quite true, you can convince them of the value of in built jetpacks

**Comment by KorPhaeron** [comment]
I will try and readd hardsuit jetpacks tonight in a way I think is a compromise when I get home

**Pull request closed without merging**
