### PR TITLE
New shuttle chair sprites.

### PR DESCRIPTION
**Pull request by Ausops**
:cl:
imageadd: New shuttle chair sprites.
/:cl:

https://imgur.com/a/zdSppQr

### CODE REVIEW

**Comment by optimumtact** [comment]
stop putting things next to the :cl: you only put something there when you want to change what name appears attached as the creator of that changelog entry

**Review by optimumtact — DISMISSED** [review]

**Comment by zaracka** [comment]
👌

**Comment by AnturK** [comment]
You'll need to swap the icon and state. Since they use the ones from goon directory now.

**Comment by Mark9013100** [comment]
The chairs will need to be a child of the shuttle chairs, like Fludds', lest the armrests won't work.

**Comment by Ausops** [comment]
ok well this will be a learning experience bare with me

**Comment by AnturK** [comment]
Yes, they should.

**Comment by fludd12** [comment]
Basically, make a copy of the chair sprite, and erase every part but the armrests from the side views, and make the other views just blank.

I like the sprite!

**Comment by MrDoomBringer** [comment]
good lord these are sexy sprites
make sure we can click on people when they're facing north!

**Comment by Cyberboss** [comment]
@Ausops the easy way to do this PR is to revert #38636 then commit your new sprites over the other ones

**Comment by zaracka** [comment]
The "armrest" covers your backpack too, so it doesn't stick out weirdly. Not your head/hair though.
ss13 comfy chair armest

**Comment by nicbn** [comment]
Fuckup of the year when

**Comment by praisenarsie** [comment]
@optimumtact write us a new mirrorPRbot

**Comment by Dorsisdwarf** [comment]
yuk

**Comment by AnturK** [comment]
Need help with the code ?

**Comment by Cyberboss** [comment]
You're PR is getting old. Either Travis CI is failing, it is still labelled work in progress (change this by adding `[READY]` to the start of your title), or there are unaddressed change requests. This may be closed soon to free up space on our tracker if it remains idle. In the event that it is, please ask in #coderbus on Rizon for it to be reopened once you have resumed work on it.

**Comment by Cyberboss** [comment]
Someone fix this

**Pull request closed without merging**
