### PR TITLE
Fixes the tesla going nuts if deleted at the wrong moment.

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Define "tesla going nuts if deleted at the wrong moment" I am very curious on what it actually does.

**Comment by neersighted** [comment]
It creates a new tesla in nullspace every 15 seconds.

**Comment by MrStonedOne** [comment]
every 200ds + machine tick, so more 22 seconds

**Comment by Ultimate-Chimera** [comment]
Oh.

**Pull request merged**
