### PR TITLE
Adds pipe layers to freezers/heaters

### PR DESCRIPTION
**Pull request by rdragan**
## About The Pull Request

Allows freezers and heaters to be connected to all atmos layers (right now they only connect on layer 2). Layer selection is done by multitooling the circuitboard, so deconstruction is necessary to switch them.

image

## Why It's Good For The Game

Makes freezers and heaters compatible with the rest of atmos and we can finally stop putting ugly layer manifolds in front of every freezer.

## Changelog
:cl: Thebleh
add: Freezers and Heaters can now connect on multiple layers. Use a multitool on their boards to change layers.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Is there a way to do this that _doesn't_ involve doing something to the circuit board? We already have to switch them from freezer to heater. Can you make it switch when you hit the device with a multitool?

**Comment by kriskog** [comment]
@TheVekter Freezers currently work off an internal buffer, and connects to pipes underneath it as well as next to it. Swapping layers while it's built would be a mess.

**Comment by TheVekter** [comment]
> @TheVekter Freezers currently work off an internal buffer, and connects to pipes underneath it as well as next to it. Swapping layers while it's built would be a mess.

Reeeee muh clicks per minute

This is good, though. Very good. Thank you.

**Comment by nightred** [comment]
Can this be made to fix building a freezer on top of a pipe net and having it connect?
The pipe should only connect to an unconnected pipe end in my opinion, but some atmos will not like this trick removed. I use it but feel it is cheap.

**Comment by kriskog** [comment]
@nightred out of scope, and a much much bigger change probably.

**Pull request merged**
