### PR TITLE
Removed strangely unnoticed pipes in asteroid.

### LINKED ISSUE #7634: Mining Asteroid produces atmos pipes
Current server version
-----
mining atmos pipes

Sometimes when mining a vertical atmos pipe appears. For the life of me I have no idea why this happens. It also only appears to happen in a certain side of the asteroid if that makes sense; or at least I never encounter it unless I'm mining on this specific side of the asteroid. The Blue circle is where I commonly encounter this phenomenon, the yellow circle is another place I've seen it happen /once/.
hyqmlwk

I have no idea what causes this or how to fix it, I've looked over these areas in the map editor and haven't found random atmos pipes in the middle of the asteroid. It probably has something to do with rock tiles in general but, like I said I've only encountered this in those two areas while mining before. 

edit: also I've never found pipes inside of the pregen caves, They seem to spawn out of nowhere in the middle of rock tiles.

### PR DESCRIPTION
**Pull request by Menshin**
Now Atmosia will have to find another source of pipe ore...
Fixes #7634.

### CODE REVIEW

**Comment by Chocobro** [comment]
always thought this was an intended thing, to make that area look more abandoned. the alien outpost is nearby to it after all.
neutral on this being fixed.

**Comment by WJohn** [comment]
No it really doesn't make any sense to have unconnected air pipes randomly appearing inside solid stone.

**Comment by Dorsisdwarf** [comment]
Pipe ore 2015 RIP

**Comment by AnonymousNow** [comment]
I kept running into these things ever since I started mining, but honestly, they seemed so unintrusive and irrelevant that I never bothered to report them.

**Pull request merged**
