### PR TITLE
Makes pacifists able to use .50BMG Soporific Rounds

### PR DESCRIPTION
**Pull request by ghost**
:cl: iksyp
tweak: pacifists can now use .50BMG Soporific Rounds
/:cl:

Soporific rounds are non-lethal but I didn't do this in the original ammo-check PR because of the freeze

### CODE REVIEW

**Comment by improvedname** [comment]
Non lethal but still makes you bleed horribly how pacific

**Comment by evsey9** [comment]
Its not blood its tomato juice

**Comment by 81Denton** [comment]
Oh nvm, they create bloodsplatter because they have NODAMAGE = TRUE instead of damage = 0.
Can be changed easily, but I guess it's nice as a hit indicator.

**Comment by evsey9** [comment]
It's not blood splatter it's just the fact that the soporific agent is tomato juice

**Comment by 81Denton** [comment]
I'd leave NODAME = TRUE in there as well just in case there are some fucky damage procs that aren't determined by damage alone

**Pull request merged**
