### PR TITLE
New Uplink UI

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Changes the layout of uplinks, mostly on the Market tab.

Made it more compact.

Before:

image

After:

image

ARnnJe7Oui

qKq0kM7YxV

## Why It's Good For The Game

Better UX

## Changelog

:cl:
qol: new uplink UI
qol: made it possible to buy a custom amount of TC, instead of bundles with fixed amounts
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
Looks great! Although top bar (objective/market/rep/lock buttons) looks too tall imo

**Comment by Gaxeer** [comment]
@MTandi Just tested your new UI. Looks great, but I have 2 suggestions:
1) remove those 
image
and make actual button (it looks like a button) to dispense any amount of TC
image
2) Replace this with a button too in section header, whatever. Leave item section for items alone.
image

**Comment by MTandi** [comment]
@Gaxeer this PR is only about layout changes. Won't do these, sorry.

Please suggest a better icon from the free set.

**Comment by Gaxeer** [comment]
> @Gaxeer this PR is only about layout changes. Won't do these, sorry.
> 
> Please suggest a better icon from the free set.

What do you think about: compress/expand pair?

**Comment by MrMelbert** [comment]
I'd suggest putting the item descriptions in block quotes, provides some nice contrast to the wall-of-white-text. Looked nice from the sample on the other PR

**Comment by MTandi** [comment]
> I'd suggest putting the item descriptions in block quotes, provides some nice contrast to the wall-of-white-text. Looked nice from the sample on the other PR

Vertical border looks bad.
Made the text less opaque instead.

image

**Comment by Gaxeer** [comment]
> > I'd suggest putting the item descriptions in block quotes, provides some nice contrast to the wall-of-white-text. Looked nice from the sample on the other PR
> 
> Vertical border looks bad. Made the text less opaque instead.
> 
> image

IMO looks less readable than fully opaque white text

**Comment by MTandi** [comment]
> @MTandi Just tested your new UI. Looks great, but I have 2 suggestions:
> 
> 1. Remove those
>    image
>    and make it an actual button (it looks like a button) to dispense any amount of TC
>    image

Implemented this part. Tested briefly, I hope it didn't break anything.

**Comment by K4rlox** [comment]
why was the iconic "welcome agent" removed?

**Comment by MTandi** [comment]
> why was the iconic "welcome agent" removed?

It wasn't.

image

**Comment by Watermelon914** [comment]
sovl...

lgtm though

**Pull request merged**
