### PR TITLE
Updates some outdated malf AI/bot ability icons

### PR DESCRIPTION
**Pull request by AMyriad**
## About The Pull Request
I updated some action icons used by AIs and bots:
- Every icon has been updated to the new sprites used here (where applicable)
-- Redid some icons to look better hopefully
-- Deleted some icons and changed their file paths to avoid duplicates
- Replaced "voice_changer" with the same sprite for "ai_president" in mob/silicon/ai.dmi 
- Recolored "reactivate_cameras" to feature shading and a better green color

### Sprites:
Old
image

New
image
(missing icons brought in from other files)

New gifs used
detonate_rcds override_machine

## Why It's Good For The Game
I just wanted to do the intercom, but I saw some easily fixable outdated stuff so I freshened those up a bit too
And I thought the poor gas-mask AI face and green camera assembly looked awful, so I used another icon that fit for the former and gave the latter some better shades of green. Open to changing or undoing any of this of course!

## Changelog
:cl:
image: Updated the ability icons used by AIs and station bots
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
The RCD is still noticeably using its ancient icon

**Review by MrMelbert — COMMENTED** [review]
Some of the stuff like the intercom should just be drawing from its actual icon if possible rather than have a copy in this file

**Comment by AMyriad** [comment]
> Some of the stuff like the intercom should just be drawing from its actual icon if possible rather than have a copy in this file

sounds good boss, I also updated the rest while I was at it

**Comment by Dorsisdwarf** [comment]
Override losing the little evil smiley face is sad. Good to have these updated though!

**Review by Wallemations — CHANGES_REQUESTED** [review]
Blackout should keep the sparks just because it'll take up more of the button frame, making it easier to read at a glance

**Comment by AMyriad** [comment]
> Blackout should keep the sparks just because it'll take up more of the button frame, making it easier to read at a glance

thought it'd be too similar to detonate_rcds, but aight u da boss

**Comment by Wallemations** [comment]
> thought it'd be too similar to detonate_rcds, but aight u da boss

detonate_rcds has a giant RCD in the middle of it, it'll be fine

**Pull request merged**
