### PR TITLE
<Iamgoofball> stun = dead <sawrge1e9> then remove the stun on disarms

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: Removes stuns on disarm.
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
RECORD TIME

**Comment by GunHog** [comment]
Impressive, Joan

**Comment by optimumtact** [comment]
as per @MrStonedOne's request we can't close things before 24 hours

**Comment by ChangelingRain** [comment]
Goof memes are zero tolerance and should not be humored.

**Comment by Militaires** [comment]
you're zero tolerance.

**Comment by Militaires** [comment]
can we testmerge this and see what happen

**Comment by PKPenguin321** [comment]
Nah

**Pull request closed without merging**
