### PR TITLE
Makes ammonia better for increasing plant yield than diethylamine.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
##  About The Pull Request

This pull request quadruples the yield increase of ammonia, from 100u of ammonia needed for a yield increase to 25u.

## Why It's Good For The Game

Currently diethylamine is easier to produce in large quantities than ammonia and is just stronger. It would be nice to have ammonia have an actual use, especially since if you have ammonia you very probably already are able to make diethylamine.

## Changelog
:cl:
balance: Ammonia now is better than diethylamine for increasing plant yield.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
nowhere in game (or on the wiki) does it say you needed 100u of these chemicals to affect yield, it'd be nice if there was some clue to this in the game while making this change

**Comment by Tlaltecuhtli** [comment]
dieth is 1 ammonia + 1 ethanol
somehow ammonia is harder to make than dieth?

**Comment by CRITAWAKETS** [comment]
Because of the fact that ammonia results in 3 units instead of the 4 units needed to make it, its more economical to make diethylamine and also it generally allows filling a beaker up without having to use a second beaker.

**Comment by carshalash** [comment]
I go peepee on plant to make it grow big.

**Comment by Zenog400** [comment]
> Currently diethylamine is easier to produce in large quantities than ammonia

No it's not, ammonia is an ingredient for diethylamine, so *by definition* it can't be easier to make than its ingredients.

> Currently diethylamine [...] is just stronger.

That's because it's harder to make.

**Comment by bigfatbananacyclops** [comment]
But ammonia is way more easier to make than dieth? Im confused

**Comment by lolman360** [comment]
isn't ammonia a precursor for dieth anyways?

**Comment by ExcessiveUseOfCobblestone** [comment]
He's trying to say that dieth is easier to produce within the 100L beaker (which he's probably right since 100 goes into 3+1 and 100 is divisible by 5, which is always an available resolution).

Can you comment on ammonia and dieth the conversion ratios because my smoothbrain takes way to long to figure out *0.04 = /25

**Comment by CRITAWAKETS** [comment]
Diethylamine uses 50u to make plant yield go up by 1.

**Comment by SkeletalElite** [comment]
There's also the fact that because you only need ethanol to make Diethylamine once you have the ammonia it would be dumb not to turn your ammonia into Diethylamine because not only do you need less Diethylamine than you do ammonia for a yield increase, you also get more Diethylamine than you do ammonia. Say for example you make 100 units ammonia, you can use that to increase your plant yield by 1 or you can turn that 100 units of ammonia into 200 units of Diethylamine which will increase your yield by 4. Not only do you double your amount but you half your requirement for a yield increase, effectively quadrupiling the amount of yield increasing you can do by just adding ethanol to your ammonia.

**Comment by CRITAWAKETS** [comment]
The ammonia is at 0.04 because if you use ethanol you are using extra chem power not for extra yield but for extra of the nutriment and health bonuses. Therefore it is more efficient to use ammonia if your goal is just plant yield.

**Comment by SkeletalElite** [comment]
> The ammonia is at 0.04 because if you use ethanol you are using extra chem power not for extra yield but for extra of the nutriment and health bonuses. Therefore it is more efficient to use ammonia if your goal is just plant yield. Also if you have a tier 4 chem dispenser its even more efficient to use ammonia.

fair

**Comment by ExcessiveUseOfCobblestone** [comment]
Chem energy is a nonexistent issue after they were made constructable, since you can just flip the battery or inducer.

**Comment by Krysonism** [comment]
Power creep but i actually like this PR.

 Even if don't bother building a dispenser i could still increase yield by a bit by buying ammonia from the vendor, making it myself from glowsticks or pestering the chemist.

**Pull request merged**
