### PR TITLE
Reverts the new grey jumpsuit to the good grey jumpsuit

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
tweak: The grey jumpsuit looks good again!
/:cl:

The new grey looks white, why.

### CODE REVIEW

**Comment by dannno** [comment]
thanks for talking to me about it

**Comment by anconfuzedrock** [comment]
danno is actually doing something good fuck you lameziman HA

**Comment by chanoc1** [comment]
meme pr

**Comment by anconfuzedrock** [comment]
fuck you metugly and chugly

**Comment by anconfuzedrock** [comment]
I gotta admit though it is a bit brightly colored

**Comment by dannno** [comment]
And I can fix that
just TALK to me.

**Comment by lzimann** [comment]
why talk when there's a good sprite already made

**Comment by PKPenguin321** [comment]
old sprite is legacy! legacy!!!!

**Comment by dannno** [comment]
Because what I'm doing is a pretty big undertaking and it would be nice not just to have things reverted angrily the moment they happen because you kept your concerns to yourself 

I get "muh legacy", the plan was to add the old grey jumpsuit in alongside the new shit.

**Pull request closed without merging**
