### PR TITLE
Adds an oven and a griddle to the beach biodome

### LINKED ISSUE #60778: Lavaland Beach Dome missing a griddle
Reporting client version: 514.1557

## Round ID:
[167450](https://scrubby.melonmesa.com/round/167450)

## Testmerges:
- [Kitchen expansion part 2: Ovens](https://www.github.com/tgstation/tgstation/pull/60515)
- [large refactor of machine/power code to cut down on processing time and wasted lists](https://www.github.com/tgstation/tgstation/pull/60317)
- [Added component manipulation on objects](https://www.github.com/tgstation/tgstation/pull/60771)
- [Changes the input list in VV add component to tgui_input_list()](https://www.github.com/tgstation/tgstation/pull/60755)

## Explanation:
I recently played as a bartender ghost role in the dome, and I noticed that it lacked a griddle, meaning the fridge full of meat is quite useless to most since you can't _cook_ the meat without a griddle.

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Closes #60778 

## Changelog
:cl:
fix: Beach Biodome now has an oven and a griddle
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
Give them a g r i l l

**Comment by SmArtKar** [comment]
> Give them a g r i l l

they already have it

**Comment by AMonkeyThatCodes** [comment]
if they already have a grill they dont need a griddle

**Comment by AMonkeyThatCodes** [comment]
why they already had a grill bruh

**Pull request merged**
