### PR TITLE
Hypospray Codersprites

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

This PR adds several (terrible) unique sprites for all the combat hypos and medipens that just used the default instead, and tweaks some minor stuff like making descriptions more truthful and moving the one-use gorilla pen and combat holy water injector where they should be.

The new medipens are just recolors of the epipen, since that's the template used for the leporazine pen too (whose icon i deleted since the pen doesn't exist anymore). For example:

image

## Why It's Good For The Game

These changes are intended to make each hypo stand out, so they don't all share the same sprite. It also adds a lot of inhand sprites (equally as bad in quality), so a knowledgeable player can, for example, notice they just got stabbed with a gorilla pen, or just know that they got injected with something healthy and not poison.

## Changelog
:cl:
imageadd: added some icons and images for hyposprays and medipens so they stand out
tweak: tweaked a few descriptions on said hypos so they better describe the contents
/:cl:

these sprites are kind of terrible, but i think they're better than every single pen and combat hypo using the same icon. any new sprites would be highly appreciated, especially for these two

image

image

### CODE REVIEW

**Comment by Borisvanmemes** [comment]
These don't look terrible.

**Comment by carlarctg** [comment]
there's a problem: i keep finding random medipens of stuff that's not in the hypospray dm, and i have no idea how to find them. they're just not in the code anywhere

for example the salbutamol medipen in oxygen medkits doesn't appear anywhere in the code, when i search for it. any help?

**Comment by ATH1909** [comment]
> there's a problem: i keep finding random medipens of stuff that's not in the hypospray dm, and i have no idea how to find them. they're just not in the code anywhere
> 
> for example the salbutamol medipen in oxygen medkits doesn't appear anywhere in the code, when i search for it. any help?

Are you sure that you're looking at master?

**Comment by carlarctg** [comment]
> > there's a problem: i keep finding random medipens of stuff that's not in the hypospray dm, and i have no idea how to find them. they're just not in the code anywhere
> > for example the salbutamol medipen in oxygen medkits doesn't appear anywhere in the code, when i search for it. any help?
> 
> Are you sure that you're looking at master?

yup, just checked on both my branch (up to date) and master, and neither of them have the salbutamol or oxalandrone medipens i distinctly remember seeing. kind of concerning

**Comment by carlarctg** [comment]
SHIT okay then i fucked up somewhere. thanks for the find ath

btw how do i mark this as do not merge

**Comment by Tlaltecuhtli** [comment]
add new ones for pentetic, oxal, sal acid , salbutimol etc

**Comment by carlarctg** [comment]
yeah done. hopefully i didn't screw everything up _this_ time

**Comment by Dorsisdwarf** [comment]
Wasn’t there a special sprite used for the meds in the combat medkit already?

**Comment by carlarctg** [comment]
there's a special sprite for the combat hypo, but the subtype holy water and deathsquad nanite injectors used the same thing, which is kind of confusing (especially since the holy one is meant to be injected on enemies not your squad)

**Comment by optimumtact** [comment]
this user is under a 3 day timeout for offtopic comments and can reapply to have this PR opened in 3 days.

**Comment by ExcessiveUseOfCobblestone** [comment]
PR to the sprite repo if you aren't going to follow up @carlarctg

**Comment by carlarctg** [comment]
> this user is under a 3 day timeout for offtopic comments and can reapply to have this PR opened in 3 days.

@optimumtact sorry, i'll try not to be offtopic in comments anymore. i don't know how to appeal for reopening this pr though

**Comment by ExcessiveUseOfCobblestone** [comment]
just ask

**Comment by carlarctg** [comment]
this is pretty much finished at this point. pls merge i'm bloated in branches

**Pull request merged**
