### PR TITLE
Syndie Lavaland Base - Modular Room Expansion

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Adds two types of modular rooms to the syndicate lavaland base, for no reason other than I am. Probably legally obligated to by this point, or something. I don't know.
I don't.
Also adds items and objects for said modular rooms.

All modules are tested and working in-game, see here with one of the commie variants (This one the budget, brokeback one):
image

## Why It's Good For The Game
Lavaland syndicate is stagnant, we need more modular room ruins and frankly three out of these six modules made me grin devilishly. Plus we can all enjoy it that comms agents will *possibly* have to deal with a regular security camera and chameleon PDA. Just don't forget they have an ideal variant of their room possible, too...

## Changelog

:cl:
expansion: Donk Co. Has finally seen fit to refurbish their lavaland bases - And unlike those /other/ guys, now things aren't standardized across every installation! To.. some executive's amusement.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
image
wow

**Comment by unit0016** [comment]
> wow... you didn't even like doing your own pr?

That's standard operating procedure, innit?

**Comment by tralezab** [comment]
you should definitely not feel obligated to make prs (though i do like yours a lot- enough to ignore your -12 gbp!). do what you enjoy and enjoy what you do, makes for better work in the end anyways

**Comment by LemonInTheDark** [comment]
s not fun, don't do it

**Comment by axietheaxolotl** [comment]
> And unlike those /other/ guys, now things aren't standardized across every installation! To.. some executive's amusement.

amazing

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
