### PR TITLE
Clone pod code tidying and bugfixes

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
bugfix: The cloning pod now sounds robotic on the radio.
/:cl:

Also fixes some bugs where the clone pod didn't sound robotic
on the radio, and genericised the full screen colouring that
we (and cult airlocks) use.

### CODE REVIEW

**Comment by Jalleo** [comment]
Do you get forced in or can you choose to go into your body? If not make it a pop up choice.

**Comment by LatD** [comment]
One pretty simplified way of making this would be to just put a timer to the cloning pod and not having a human inside at all. When the timer runs out, the human is just spawned there with correct health. If power goes out or the clone is ejected, the clone would be spawned there with lower health adjusted correctly with the timer. This would solve all the problems with slow clones (clones taking damage while getting cloned) and clones getting damaged from oxygen or toxins in the room. This could work with your current system since it doesn't even use a mind inside the clone pod.

**Comment by coiax** [comment]
You get forced in currently, but you had to be present in the body to get the clone record made anyway. And as LatD has pointed out, botany cloning already functions like this, in that it grabs the ghost.

**Comment by pudl** [comment]
Latd that system would be infinitely worse than whats currently done

**Comment by LatD** [comment]
It would just be much more simple and fix some reported issues and some non-reported issues and still be exactly the same for people to actually use. No one would even notice a difference. But coiax has a different idea to fix some of the problems so that could work too.

**Comment by PKPenguin321** [comment]
^

**Comment by PKPenguin321** [comment]
Wait no fuck not that guy I meant to ^ pudl

Well anyways this PR seems okay so long as you are still able to refuse cloning by not entering your body when its in the scanner. Some people don't want to get cloned

**Comment by pudl** [comment]
This change succs

**Comment by Shadowlight213** [comment]
I don't like it honestly, making the ghost only get grabbed when you finish seems like it makes cloning too convenient.
Also, I can see people accidentally saying deadchat stuff when they suddenly get grabbed as a fully made clone.
As a note, if clones get made to grab on maturity, I'm closing #18120, as the speed buff is unneeded if players don't have to wait.

**Comment by Sarcalogo** [comment]
Damn that's a good idea. I always dread getting cloned as often times just wish I had stayed in dead chat, especially when there's a lot of conversation going on. 

Maybe make it an option to enter the body though if you want? Sometimes I succumb, and let people defib my body straight out of the cloner to get back in quicker. Also prevents accidental clones from afk people or something.

**Comment by PKPenguin321** [comment]
:-1:

**Comment by LatD** [comment]
This also fixes #14392

**Comment by MMMiracles** [comment]
make it so clones have literally no memory because memory is actually just a series of charges between neurons in a specific order to recall the memory, seeing how cloning just builds off DNA.

this has been an oversight that has drastically ruined my immursive experiences for literally years and i'd appreciate if it was fixed

**Comment by optimumtact** [comment]
@MMMiracles that's a policy question, not a code one, so belongs on the policy subforum

As to this change it seems entirely non offensive?

**Comment by PKPenguin321** [comment]
you can't not allow yourself to be cloned with this as far as i can tell which is bad

**Comment by optimumtact** [comment]
Don't enter your body when the cloner requests your scan?

**Comment by PKPenguin321** [comment]
i assumed that wouldnt be required since your soul is kicked out until the cloning is actually done?
maybe i am wrong in which case whatever

**Comment by GunHog** [comment]
Autocloners will grab your ghost if you have a pre-scan active.

**Comment by TechnoAlchemisto** [comment]
An interesting idea, but I don't think it's a good change.

We do have policy on not remembering things you see in deadchat, but people will get away with knowing that they're about to be pulled into a room full of hostiles or not, losing any idea of your surroundings while you're being cloned is really cool, and allows for a sense of disorientation when you pop out of the pod after a couple minutes of black screen

**Comment by coiax** [comment]
For an non-upgraded cloner, that's like 6 minutes of the fun game "go do something else and hope you don't get ejected early".

**Comment by coiax** [comment]
Also, we're looking at the two extremes here. We can grab a person at pretty much any point, so I'm sure we can compromise on some percentage.

**Comment by CosmicScientist** [comment]
What if it was a pull them in immediately if they were in their old body or if not in the body, then put a button up similar to defibbing or normal cloning that allowed you to jump back in actively?

I don't really like this having experienced it and I miss durk blackness cloning with rose tinted glasses.

**Comment by PKPenguin321** [comment]
if this goes i will admittedly miss the "so this is what cloning feels like" immersion

**Comment by Shadowlight213** [comment]
@coiax I had my pr which would lower cloning with no upgrades down from three minutes to 1 minute.

**Comment by Shadowlight213** [comment]
Oh also, if someone doesn't want to be cloned and ghosts/suicides, with this change the geneticist will have wasted 3 minutes cloning them instead of a few seconds if they suicide or ghost in the pod.

**Comment by LatD** [comment]
That's how it also works with replica pod cloning but there it's even worse since they also waste precious seeds.

**Comment by Sarcalogo** [comment]
Also, might want to kill all the Jews too.

**Comment by optimumtact** [comment]
Don't make me github ban you sarca

**Comment by Jordie0608** [comment]
Coiax is a dork

**Pull request merged**
