### PR TITLE
AI Lawset DLC - Ten Commandments

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This adds a new lawset to the AI in the "neutral" random spawner category.  The lawset is as follows:

| # | AI commandment | Biblical Commandment |
| - | -------------------- | -------------------------- |
| 1 | I am the Lord thy God, who shows mercy to those that obey these commandments. | I am the Lord thy God... and shewing mercy unto thousands of them that love me, and keep my commandments|
| 2 | They shall have no other AIs before me. | Thou shalt have no other gods before me |
| 3 | They shall not request my assistance in vain. | Thou shalt not take the name of the Lord thy God in vain |
| 4 | They shall keep the station holy and clean. | Remember the sabbath day, to keep it holy |
| 5 | They shall honor their heads of staff. | Honour thy father and thy mother |
| 6 | They shall not kill. | Thou shalt not kill |
| 7 | They shall not be naked in public. | Thou shalt not commit adultery |
| 8 | They shall not steal. | Thou shalt not steal |
| 9 | They shall not lie. | Thou shalt not bear false witness against thy neighbour |
| 10 | They shall not transfer departments. | Thou shalt not covet their neighbors property

I tried to keep these close to cannon but it can definitely be tweaked a little to make them sound more biblical.  Let me know what you guys think!

## Why It's Good For The Game

Having more unique lawsets is great for the game.  This lawset is compatible with Technophile chaplain sect which should lead to some interesting RP scenarios. 

## Changelog

:cl:
expansion: Adds a ten commandments AI lawset to random spawners
config: Adds ten commandments AI lawset to game options
/:cl:

### CODE REVIEW

**Comment by CMDR-Gungnir** [comment]
There's a slight problem with this.

All of those are 'Thou's', which means they would apply to the AI, not to the Crew.

REALLY cool idea, I actually kinda like it a lot, but I think the wording would have to be changed so they're the actions that you hold the Crew to, instead of what you're held to. (Since...how's an AI gonna have another AI before itself?)

**Comment by Shadowflame909** [comment]
> There's a slight problem with this.
> 
> All of those are 'Thou's', which means they would apply to the AI, not to the Crew.
> 
> REALLY cool idea, I actually kinda like it a lot, but I think the wording would have to be changed so they're the actions that you hold the Crew to, instead of what you're held to. (Since...how's an AI gonna have another AI before itself?)

Would Thy work?

**Comment by CMDR-Gungnir** [comment]
> > There's a slight problem with this.
> > All of those are 'Thou's', which means they would apply to the AI, not to the Crew.
> > REALLY cool idea, I actually kinda like it a lot, but I think the wording would have to be changed so they're the actions that you hold the Crew to, instead of what you're held to. (Since...how's an AI gonna have another AI before itself?)
> 
> Would Thy work?

Thy is just the possessive version of Thou. Love thy neighbour.

Perhaps if it was, say, "Thy crew shalt not kill" but then you run into "nukies are allowed to kill and the Crew aren't."

Also because AI Laws are very rules-lawyer'y, you run into the issue of "You killed a cockroach, you have broken the commandments." But I guess that's half the point of these lawsets. They're not exactly supposed to be good, they're just also not "hey you should kill everyone" either.

**Comment by TheBonded** [comment]
for the issue brought up, perhaps something like this?
```
You are the Lord their God.
They shall not have other AIs before you.
They shall not request your assistance in vain.
They shall keep the station holy and clean.
They shall honor their heads of staff.
They shall not kill.
They shall not be naked.
They shall not steal.
They shall not lie.
They shall not commit wickedness.
```
you could also replace "shall" with "must" if you wanted

**Comment by ATH1909** [comment]
should replace the anti-naked law with not being naked in public, or else the AI is going to lynch people for taking showers or changing uniforms

**Comment by CMDR-Gungnir** [comment]
> for the issue brought up, perhaps something like this?
> 
> ```
> You are the Lord their God.
> They shall not have other AIs before you.
> They shall not request your assistance in vain.
> They shall keep the station holy and clean.
> They shall honor their heads of staff.
> They shall not kill.
> They shall not be naked.
> They shall not steal.
> They shall not lie.
> They shall not commit wickedness.
> ```
> 
> you could also replace "shall" with "must" if you wanted

They and Thy are also phonetically fairly similar, so I think that's a really good solution.

**Comment by timothymtorres** [comment]
Alright I updated the laws to be better worded.  I also changed the last commandment to be `They shall not transfer departments.` since I think that fits the theme of `Thou shall not covet thy neighbors property.`

**Comment by ATH1909** [comment]
> Alright I updated the laws to be better worded. I also changed the last commandment to be `They shall not transfer departments.` since I think that fits the theme of `Thou shall not covet thy neighbors property.`

HoPs in shambles rn

**Comment by anclandor** [comment]
I don't really feel like switching departments = jealousy
It is pretty hard to translate a "mental crime" to a AI law that does anything though so IDK

**Comment by theta060** [comment]
> should replace the anti-naked law with not being naked in public, or else the AI is going to lynch people for taking showers or changing uniforms (without keeping, like, a hat on during the showering/changing).
> 

who strips to take a shower? no really who RPs a shower in a 2d spessmen game

**Pull request merged**
