### PR TITLE
Adds pod consoles and safes to Dreamstation

### PR DESCRIPTION
**Pull request by ChangelingRain**
See #13186 for details.
Also adds a maint room by escape, thank me later.

### CODE REVIEW

**Comment by francinum** [comment]
Pics

**Comment by Anonus** [comment]
See #13186 for details it's basically the same thing

**Comment by Zilenan91** [comment]
What's the maint room looking like?

**Comment by Anonus** [comment]
That would be telling!
I'll update the map image tomorrow.

**Pull request merged**
