### PR TITLE
removes peacekeeper borgs

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

peacekeeper borgs are probably just going to get slowly buffed to secborg levels over the next few months and their coder quit coding for us so no point in keeping them around until they turn from malignant to life-threatening on the tumor status

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
goofballs a fag

**Comment by calibraptor** [comment]
Fuck you Peacekeeper borgs are adorable

**Comment by SyruseEln** [comment]
its time to stop

**Comment by praisenarsie** [comment]
no u

this pr is gonna get closed anyway unless kor's brain expands and merges this.

**Comment by Pascal125** [comment]
Slippery Slope PR.

**Comment by kevinz000** [comment]
Fuck off they've been nerfed more than buffed and I've specified that they're not meant for chasing people down.

**Comment by Spaceinaba** [comment]
im serious goof just make a pr deleting the entire codebase it will be funnier

**Comment by Iamgoofball** [comment]
@ninjanomnom can you please clean up some of the shitposting here

**Comment by DoctoreMad** [comment]
joke PR

**Comment by kevinz000** [comment]
What do you mean their coder quit coding are you fucking high I coded them.

**Comment by Iamgoofball** [comment]
Remie coded them

**Comment by nicbn** [comment]
Fucking shit stop meme PRing

**Comment by Alecw155** [comment]
there was a point at which this should have stopped and it was 4 PRs ago

**Comment by Pascal125** [comment]
Get out of here you goatse posting motherfucker, you don't even know shit if you can't realize Kevinz coded them.

**Comment by Iamgoofball** [comment]
@optimumtact can some of this hostile shitposting get deleted please?

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/626302c1bf4bb2a37aa6508145751f6c4c78696d/code/modules/mob/living/silicon/robot/robot.dm#L804

**Comment by Iamgoofball** [comment]
Fucking

**Comment by praisenarsie** [comment]
btw i bet many people only pick the peacekeeper module because
a) they don't know it's just a deflated version of the secborg (basically never used the module)
or
b) use it for the """""cute""""" factor

**Comment by Iamgoofball** [comment]
ps. Thanks Shiv

@kevinz000 i swear I recall remie being the original coder

**Comment by Iamgoofball** [comment]
If people are playing borg to be "cute", use Service module

**Comment by praisenarsie** [comment]
git blame points to kevinz to doing it.

**Comment by Iamgoofball** [comment]
Oh right remie did the sprites, not the cold

**Comment by TheDreamweaver** [comment]
What the fuck is going on

**Comment by qbmax32** [comment]
If he makes enough garbo prs one of them is bound to be merged right?!



improve don’t remove how fucking hard is it

**Comment by TheDreamweaver** [comment]
Oh you don't have to tell me that. You should see the rant I left on his remove hulk PR.

**Comment by Alecw155** [comment]
if goof was a plumber he'd remove your toilet and say it's fixed

**Comment by KorPhaeron** [comment]
I have not seen any significant gameplay problems with peacekeepers warranting their removal 

If people try to powercreep them we can block the powercreep, it doesn't require preemptive removal

**Pull request closed without merging**
