### PR TITLE
Adds BWOINK to the dance machine

### PR DESCRIPTION
**Pull request by ghost**
:cl: ShiggyDiggyDo
add: Added BWOINK to the dance machine
/:cl:

dance machine more like heart attack machine

### CODE REVIEW

**Comment by optimumtact** [comment]
This is funny but we don't allow non admins to use this sound for obvious reasons.

I'll leave this open for now but it will not be merged

**Comment by PKPenguin321** [comment]
Funny but I'm imagining a boy who cried wolf scenario

**Comment by ShiggyDiggyDo** [comment]
>what is the banhammer

**Comment by DaxDupont** [comment]
@optimumtact euh you forgot about the ban hammer object

**Comment by lzimann** [comment]
bwoink shall remain purely an ooc sound

**Comment by PKPenguin321** [comment]
banhammer is admin only isn't it?

**Comment by DaxDupont** [comment]
it is not

**Comment by lzimann** [comment]
you can get it by gifts, which is obtainable by that lavaland ruin or xmas events

**Comment by DaxDupont** [comment]
adminbus ruin also spawns it

**Comment by Bawhoppen** [comment]
I mean there's a guaranteed one on the adminbus ruin

**Comment by optimumtact** [comment]
it's the coderbus ruin

**Comment by ShiggyDiggyDo** [comment]
also there's one in the wizard's den

**Pull request closed without merging**
