### PR TITLE
Can't kick racks if weakened, resting or lying

### LINKED ISSUE #12008: Rack kicking while lying down ruins immulsion
https://www.youtube.com/watch?v=3Jmkt0HWZcc

### PR DESCRIPTION
**Pull request by Mervill**
:cl: Mervill
fix: Can't kick racks if weakened, resting or lying
/:cl:

Fixes #12008

### CODE REVIEW

**Comment by Bawhoppen** [comment]
tg culture

**Comment by coiax** [comment]
Probably should check that the person kicking the rack has a leg.

**Comment by ShadowDeath6** [comment]
if you have one leg and kick a rack it should make you fall over

**Comment by XDTM** [comment]
why can you attack_hand stuff while weakened, resting or lying in the first place

**Comment by kilkun** [comment]
because hugbox

**Pull request merged**
