### PR TITLE
Totally doesn't ruin the server.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
All non-byond members are kicked after 15 minutes

### CODE REVIEW

**Comment by GunHog** [comment]
MSO, coding while high is not recommended!

**Comment by optimumtact** [comment]
code/modules/client/client_procs.dm:206:error: inconsistent indentation

**Comment by Qustinnus** [comment]
spaces > tabs

**Comment by MrStonedOne** [comment]
Thats what i get for copypasting from leddit

**Comment by The-clown-known-as-Pepe** [comment]
>mso is a redditor

https://file.house/ElqO.png

**Comment by OneOneThreeEight** [comment]
_I never asked for this._

**Comment by MrStonedOne** [comment]
>mso is a redditor

\>doesn't even know how to green test

Bitch please

**Comment by Qustinnus** [comment]
yes MSO please teach me how to green test

**Comment by DoctoreMad** [comment]
memefield

**Pull request closed without merging**
