### PR TITLE
Summoning Nar'Sie now corrupts the Hard Drive and deletes the BYOND account of all cult players

### PR DESCRIPTION
**Pull request by Robustin**
Fuck gameplay, lore is SUPREME in 2d spessman games. 

Nar'Sie seeks to punish all of its followers for summoning it, or something, so clearly the proper LORE SOLUTION is to make sure cultists endure the shittiest possible outcome.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
SERVER <----------------> LORE

> Separation is absolute.

**Comment by PKPenguin321** [comment]
Iamrobustinball

**Comment by GunHog** [comment]
Deceptive PR titles are spam and we need to crack down on this behavior. I am really sick of this, myself.

**Comment by Tacolizard** [comment]
salt that you fell for obvious bait?

**Comment by GunHog** [comment]
More that I have to click and read the code diff to see what the PR really is. It is bad enough keeping up with all the changes and PRs in this codebase without stupid bait titles forcing me to read minor features or bugfixes that would otherwise be ignored. 

I try to keep up with every significant change, so you can understand why I get "salt" when I am looking through 15+ PRs at once and have to stop and look at code diffs to know what I am actually seeing.

**Comment by Robustin** [comment]
Rest easy GunHog

**Comment by GunHog** [comment]
You did not have to close the PR, simply change the title to mach your change.

**Comment by nullbear** [comment]
wait so checking the code in PR's is bad, and you'd prefer to just ignore it and assume the title is correct?

**Pull request closed without merging**
