### PR TITLE
Adds a link to individual logs to ahelps/prays

### PR DESCRIPTION
**Pull request by lzimann**
An important tool needs an easy way to reach it.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
does this link also show up when you click the ? in a mention?

**Comment by lzimann** [comment]
It does not, but I can change it to use the fullmonty so it's consistent.

**Comment by PKPenguin321** [comment]
Wait, is there an interface for logs outside of VV?

**Comment by PKPenguin321** [comment]
If so I'd add a link to just about anywhere that VV is mentioned, such as the player panel

**Comment by lzimann** [comment]
It is already in player panel, mainly my own fault for not talking much to admins about it

**Pull request merged**
