### PR TITLE
Biodegrade dissolves legcuffs

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
image

Makes biodegrade also dissolve legcuffs. It can already dissolve lockers, straightjackets, cocoons and handcuffs, this seems like an oversight.

## Why It's Good For The Game
I'd argue its a fix, but at the very least makes biodegrade consistent.

## Changelog
:cl: Skoglol
balance: Changeling biodegrade now dissolves legcuffs.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
This is definitely antag freeze I mean come on

**Comment by Whoneedspacee** [comment]
i mean it looks like he has maintainer permission is that not applicable

**Comment by MCterra10** [comment]
Tbh this seems a bit far for what's reasonably allowed during the antag freeze, also do we REALLY need a ling buff at this point, they're already overpowered to shit

**Comment by kriskog** [comment]
Yes, I asked for permission since this is borderline. Since biodegrade already gets rid of all other means of restraints, legcuffs should be part of that and was likely just forgotten somewhere along the way. Biodegrade is a 30 chemical action, it's balanced fine even with this. 
The skill description states:  "Dissolves restraints or other objects preventing free movement."

**Pull request merged**
