### PR TITLE
Adds support for custom showcases on the map

### PR DESCRIPTION
**Pull request by AnturK**
What it says on the tin

### CODE REVIEW

**Comment by xxalpha** [comment]
Neat

**Comment by WJohn** [comment]
Power to the mappers :+1:

**Comment by Shadowlight213** [comment]
Would be nice if showcases were repairable somehow.

**Comment by Razharas** [comment]
@AnturK 
Add changelog and its going in

**Comment by AnturK** [comment]
Added changelog for original pull too since i forgot it back then.
@Razharas

**Comment by Metacide** [comment]
Great. Thanks! :+1:

**Comment by AnonymousNow** [comment]
Showcases? Like the old cyborg modules?

**Pull request merged**
