### PR TITLE
reduces the filesize of title3.ogg

### LINKED ISSUE #9754: title3.ogg is kinda huge compared to the other title tracks
title1.ogg 799 kb
title2.ogg 346 kb
title3.ogg 10298 kb

A matter of server resources, might not be worth fixing if you can't get it down without losing fidelity, but there is probably some rather painless ways to get that filesize down.

### PR DESCRIPTION
**Pull request by Incoming5643**
I was able to get the file down to about a third of its size without any perceptible quality loss to me, can an audiophile listen to this and tell me if anything screams "THIS IS A SHITTY COMPRESSED MESS" cause I don't want to shit all over the funk.

Fixes #9754

This version (3.9 Mb): https://github.com/Incoming5643/-tg-station/raw/wubba_lubba_dub_dub!/sound/ambience/title3.ogg

Current version (9.8 Mb): https://raw.githubusercontent.com/tgstation/-tg-station/master/sound/ambience/title3.ogg

### CODE REVIEW

**Comment by optimumtact** [comment]
https://raw.githubusercontent.com/Incoming5643/-tg-station/wubba_lubba_dub_dub!/sound/ambience/title3.ogg

**Comment by francinum** [comment]
Not a compressed mess :+1:

**Comment by Niknakflak** [comment]
I got it even lower I think..

**Comment by Incoming5643** [comment]
I wouldn't doubt it, all I did was open it in audacity and resaved it. Someone who actually knows what they're doing could probably get it under 2 megs. Wherever it was originally saved was just exceptionally careful about fidelity options, probably to be safe during active projects.

**Comment by MrStonedOne** [comment]
for the record. i got it under 1mb. kinda sorta noticeable, but not that much

**Pull request merged**
