### PR TITLE
Hooch no longer heals assistants.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Hooch no longer heals assistants.

## Why It's Good For The Game

Nerfing assistants is good, actually.

## Changelog

:cl:
del: Hooch no longer heals assistants.
/:cl:

### CODE REVIEW

**Comment by oklews** [comment]
Hooch gets you shitfaced, if getting shitfaced is the cost of healing, it's hardly worth it. Especially considering the potential for a vomit stun.

**Comment by theta006** [comment]
cringe

**Comment by Sealed101** [comment]
lmao

**Comment by Donpedrito** [comment]
“Why is this PR good for the game?”
“Well, because it does a thing that’s good for the game.”
??? That’s not a reason at all. I’m not even sure whether I agree with this change but sarcastic descriptions don’t really help your case.

**Comment by Serxule** [comment]
goof why have you become such a lameo

**Comment by jughu** [comment]
Ok if hooch should stop healing assistants
then banana honk shouldn't heal clowns
then blank paper shouldn't heal mimes
then wizard fizz shouldn't heal wizards
then doctor delight shouldn't heal anyone

**Comment by ExcessiveUseOfCobblestone** [comment]
is there some sort of antihol/hooch combo or something

**Comment by jughu** [comment]
theres a quirk that makes you resistant vs drunkiness

**Comment by ATH1909** [comment]
> theres a quirk that makes you resistant vs drunkiness

but it's shit because it's mutually exclusive with light drinker and makes it harder to bar rp (bc it's harder to get drunk, which is what you're there at the bar for)

**Review by Rohesie — CHANGES_REQUESTED** [review]
Remove `TRAIT_GREYTIDE_METABOLISM` entirely, else it will be dead code besides an examine message.

If no maintainers block this PR I'm merging it.
Assistants shouldn't have any in-game benefits over other jobs.

**Comment by Pickle-Coding** [comment]
Assistants do not do anything to merit a drink that gives them an advantage that other roles won't get.

**Comment by necromanceranne** [comment]
> is there some sort of antihol/hooch combo or something

lf you can get antihol you can get anything more useful. And doubtful given antihol purges alcohol reagents.

**Comment by jughu** [comment]
image

JUst this quirk.

**Comment by Mosslick** [comment]
Ided

**Comment by realthomas69** [comment]
What a fucking loser

**Comment by realthomas69** [comment]
assistants are just going to break into chem to make their powergame heal juice now

**Comment by AlinaStarkova** [comment]
> assistants are just going to break into chem to make their powergame heal juice now

while i do not have any opinions on this PR either way since i never used this feature, your argument here is a really bad one: "greytiders will just break into places to get what they want, so you may as well just give them it by default"..... by this logic we should have assistants spawn with the caps spare since they will just break in and steal it every round anyway, or an egun, or a maxcap, or the CEs power tools and insuls

**Comment by necromanceranne** [comment]
There are a multitude of other ghetto healing options. Hooch is really not one of the better ones.

**Comment by realthomas69** [comment]
> while i do not have any opinions on this PR either way since i never used this feature, your argument here is a really bad one: "greytiders will just break into places to get what they want, so you may as well just give them it by default"..... by this logic we should have assistants spawn with the caps spare since they will just break in and steal it every round anyway, or an egun, or a maxcap, or the CEs power tools and insuls

we do not give it to them by default, assistants do not spawn with hooch, your strawman sucks

**Comment by B00tz** [comment]
> If no maintainers block this PR I'm merging it. Assistants shouldn't have any in-game benefits over other jobs.

Why not? Sec heals from donuts, there's all the other drinks that heal people based on their job why should assistants be denied their roleplay meme buff? Traitors arn't given anything to boost them why not since there is Wizz Fizz and changeling sting?

If you can't think of anything past grey man bad maybe go back to the chalkboard before merging.

**Comment by AlinaStarkova** [comment]
> > while i do not have any opinions on this PR either way since i never used this feature, your argument here is a really bad one: "greytiders will just break into places to get what they want, so you may as well just give them it by default"..... by this logic we should have assistants spawn with the caps spare since they will just break in and steal it every round anyway, or an egun, or a maxcap, or the CEs power tools and insuls
> 
> we do not give it to them by default, assistants do not spawn with hooch, your strawman sucks

its not a strawman, and it doesnt matter if you spawn with hooch or not, the fact assistants have access to a healing chem without the need to actually use any chemistry is itself "having it by default"

engineers dont spawn with insuls, but they have access to them. that other jobs dont. likewise hooch only works on assistants so its unique to them, in fact its worse because insuls can be stolen, healing from hooch cannot. job specific healing is bad, it makes medbay useless and makes actual healing chems pointless. if tiders want healing they should be asking chemist to make a bunch of healing patches or pills

**Comment by AlinaStarkova** [comment]
> > If no maintainers block this PR I'm merging it. Assistants shouldn't have any in-game benefits over other jobs.
> 
> Why not? Sec heals from donuts, there's all the other drinks that heal people based on their job why should assistants be denied their roleplay meme buff? Traitors arn't given anything to boost them why not since there is Wizz Fizz and changeling sting?
> 
> If you can't think of anything past grey man bad maybe go back to the chalkboard before merging.

i think the main difference there is that assistants arent supposed to be a proper job, having perks like that makes people choose assistant over actual jobs, meaning said jobs dont actually get filled. tbh i suggested once having a cap for assistant based on round pop but that was denied, not as big of an issue recently as i havent seen 20 tider rounds recently, but having perks over most other jobs would change that, hooch itself isnt a big enough perk on its own but they add up, at first its just a little perk here and there, the next its one massive list of perks thats too good to pass up (also im only aware of sec having healing foods/drinks, and on that note im against that too, it ruins the point of medbay)

**Comment by catrock31** [comment]
> > > If no maintainers block this PR I'm merging it. Assistants shouldn't have any in-game benefits over other jobs.
> > 
> > 
> > Why not? Sec heals from donuts, there's all the other drinks that heal people based on their job why should assistants be denied their roleplay meme buff? Traitors arn't given anything to boost them why not since there is Wizz Fizz and changeling sting?
> > If you can't think of anything past grey man bad maybe go back to the chalkboard before merging.
> 
> i think the main difference there is that assistants arent supposed to be a proper job, having perks like that makes people choose assistant over actual jobs, meaning said jobs dont actually get filled. tbh i suggested once having a cap for assistant based on round pop but that was denied, not as big of an issue recently as i havent seen 20 tider rounds recently, but having perks over most other jobs would change that, hooch itself isnt a big enough perk on its own but they add up, at first its just a little perk here and there, the next its one massive list of perks thats too good to pass up (also im only aware of sec having healing foods/drinks, and on that note im against that too, it ruins the point of medbay)

what are the other perks of assistants other then this one little thing?

**Comment by Sealed101** [comment]
medbay holds its place in the game loop and it isnt outclassed by drinks in any way. it is still better to use chemicals for healing, as they incur a much faster healing rate as well as bonuses in some cases. drinks can't heal traumas, affix lost limbs or organs, and they can't revive dead crew. healing drinks are useful to treat raw damage, and even in that they have the drawback of getting shitfaced and suffering the effects of that. this is especially true with hooch, which is the strongest job drink out of them all
drinks still require chemistry, and hooch has welding fuel in its recipe. if you don't have any proper methods of purifying your mix of that, you will build up toxins in your body. furthermore, getting ethanol and enzyme either requires biogenerators, or chemistry and cook's help. 
howevee, hooch is the only job drink that has a chance to spawn in the map as a bottle or even several in maint. id say if that was taken out of the equation, it would even hooch out to a degree comparing it to other drinks.

**Comment by AlinaStarkova** [comment]
> medbay holds its place in the game loop and it isnt outclassed by drinks in any way. it is still better to use chemicals for healing, as they incur a much faster healing rate as well as bonuses in some cases. drinks can't heal traumas, affix lost limbs or organs, and they can't revive dead crew. healing drinks are useful to treat raw damage, and even in that they have the drawback of getting shitfaced and suffering the effects of that. this is especially true with hooch, which is the strongest job drink out of them all drinks still require chemistry, and hooch has welding fuel in its recipe. if you don't have any proper methods of purifying your mix of that, you will build up toxins in your body. furthermore, getting ethanol and enzyme either requires biogenerators, or chemistry and cook's help. however, hooch is the only job drink that has a chance to spawn in the map as a bottle or even several in maint. id say if that was taken out of the equation, it would even hooch out to a degree comparing it to other drinks.

id still be against healing from alcohol on principle, it makes no sense, in theory you are still a human, and humans do not heal from alcohol, its literal poison to us. healing from alcohol would make more sense as a unique race perk, we already have race perks such as ethereal self-revive

that said, this is still a game so im not going to call for realism there. however unlike species which anyone can be regardless of job and there is no cap to them, jobs DO have a cap and only a few people can get them (aside from tiders, but we dont want EVERYONE to be a tider)...... so imho, either all job drink healing gets removed, or EVERY job gets a special drink to heal, and they all heal at the same rates. currently i only know of sec and greytide specific healing drinks, if theres a few more that still doesnt matter, as most jobs simply dont have one and this makes sec and tider more appealing just from that fact alone (even if its a 0.0001% more appealing due to how horrendously shitfaced it makes you) ... obviously jobs can never be balanced between each other truely, concessions must be made, such as atmostechs and scientists easily able to make maxcaps, chemists all kinds of poisons etc... but an effort to balance things, especially things which can have combat applications (more talking about secc donuts here, or even having the quirk to make it harder to get drunk so you have less drawback healing that way) should be made here

anyway, as i said earlier, i dont really care one way or the other, i dont use alcohol in game, at all, never have and frankly likely never wont, im allergic to alcohol (as majority of asians sadly are, its genetic *frowns*) so ive never frankly seen the appeal to roleplay get drunk. so this PR really wont bother me either way, i just feel that if we are going to throw a fit about this, the solution is no job gets a healing drink, or they all do, to be fair

**Comment by Farquaar** [comment]
This is yet another goofball PR that attempts to solve a problem that doesn't exist.

**Comment by Sealed101** [comment]
nuking every healing/beneficial job/antag drink would be sad, it's an underappreciated part of bartending, but giving every job a healing drink would also probably be horrendous, as everyone just rushes to the bar and floods the bartender (or lack of thereof) with a request. though this kinda sounds funny idk

**Comment by necromanceranne** [comment]
> nuking every healing/beneficial job/antag drink would be sad, it's an underappreciated part of bartending.

This is not all drinks. This is one drink, and one that typically spawns in specifically maint. You can have a bartender make you hooch, but hooch is going to primarily be acquired from the bottles that spawn on the floor of maint shafts. Come on now, don't make such a sweeping assumption like that.

**Comment by Sealed101** [comment]
it was a reply to the previous comment, not an assumption, im sorry if it came out like this, i cant be bothered to quote from mobile and work simultaneiously

**Comment by jughu** [comment]
> image
> 
> JUst this quirk.

Stacked with hooch

**Comment by necromanceranne** [comment]
> > image
> > JUst this quirk.
> 
> Stacked with hooch

That stacked with dwarf is a quick way to get pretty potent healing off manly dorf in case anyone wants an even better healing combo anyone can get (with help from genetics)

**Comment by catrock31** [comment]
> > what are the other perks of assistants other then this one little thing?
> 
> there are a few small ones, that i cant think off the top of my head rn, but the point isnt that tiders are currently full of perks, its about the mindset: "oh its just a really really tiny perk, we can add this in" and you just keep adding really small perks slowly over time. on their own they are harmless, but once they are added together is when you realize you made a monster. its what happened to silicons, they just kept getting added to overtime, and ever since a few years ago they have been getting nerf after nerf after nerf nonstop to try to balance them out
> 
> > medbay holds its place in the game loop and it isnt outclassed by drinks in any way. it is still better to use chemicals for healing, as they incur a much faster healing rate as well as bonuses in some cases. drinks can't heal traumas, affix lost limbs or organs, and they can't revive dead crew. healing drinks are useful to treat raw damage, and even in that they have the drawback of getting shitfaced and suffering the effects of that. this is especially true with hooch, which is the strongest job drink out of them all drinks still require chemistry, and hooch has welding fuel in its recipe. if you don't have any proper methods of purifying your mix of that, you will build up toxins in your body. furthermore, getting ethanol and enzyme either requires biogenerators, or chemistry and cook's help. however, hooch is the only job drink that has a chance to spawn in the map as a bottle or even several in maint. id say if that was taken out of the equation, it would even hooch out to a degree comparing it to other drinks.
> 
> id still be against healing from alcohol on principle, it makes no sense, in theory you are still a human, and humans do not heal from alcohol, its literal poison to us. healing from alcohol would make more sense as a unique race perk, we already have race perks such as ethereal self-revive
> 
> that said, this is still a game so im not going to call for realism there. however unlike species which anyone can be regardless of job and there is no cap to them, jobs DO have a cap and only a few people can get them (aside from tiders, but we dont want EVERYONE to be a tider)...... so imho, either all job drink healing gets removed, or EVERY job gets a special drink to heal, and they all heal at the same rates. currently i only know of sec and greytide specific healing drinks, if theres a few more that still doesnt matter, as most jobs simply dont have one and this makes sec and tider more appealing just from that fact alone (even if its a 0.0001% more appealing due to how horrendously shitfaced it makes you) ... obviously jobs can never be balanced between each other truely, concessions must be made, such as atmostechs and scientists easily able to make maxcaps, chemists all kinds of poisons etc... but an effort to balance things, especially things which can have combat applications (more talking about secc donuts here, or even having the quirk to make it harder to get drunk so you have less drawback healing that way) should be made here
> 
> anyway, as i said earlier, i dont really care one way or the other, i dont use alcohol in game, at all, never have and frankly likely never wont, im allergic to alcohol (as majority of asians sadly are, its genetic _frowns_) so ive never frankly seen the appeal to roleplay get drunk. so this PR really wont bother me either way, i just feel that if we are going to throw a fit about this, the solution is no job gets a healing drink, or they all do, to be fair

you still didn't name the perks of being an assistant. also it's just funny to let them have this imagine you have a guy come up to your bar take one sip of his drink and the cut and burns he has just disappear. there is no actual benefit to this pr just a removal with nothing else

**Review by Rohesie — APPROVED** [review]
Since this is a controversial change I'll give it 24 hours before merging in case a maintainer wants to block it. Else I'll merge it, as it is a change I want.
I don't think Assistants should have any benefits over any other job. We should not be promoting playing them over actual jobs, and this is actually used by tiders to gain a combat advantage.

**Comment by Ryll-Ryll** [comment]
Personally I prefer crewmembers being able to perform simple low-stakes healing on themselves by scavenging over forcing them to always crowd medbay for surgery. It's not like you can treat wounds or brain traumas or bloodloss with this. I'm not gonna block it but I think the game should have more improvised fixes that encourage people to scavenge rather than removing them

**Comment by Pickle-Coding** [comment]
> Personally I prefer crewmembers being able to perform simple low-stakes healing on themselves by scavenging over forcing them to always crowd medbay for surgery. It's not like you can treat wounds or brain traumas or bloodloss with this. I'm not gonna block it but I think the game should have more improvised fixes that encourage people to scavenge rather than removing them

Doesn't eating food already fill that role?

**Comment by jughu** [comment]
Food/drinks are in the same box

**Comment by drIcepop** [comment]
Please get rid of warm sink pocket omnizine, it's letting assistants heal themselves too easily!!

**Comment by Sealed101** [comment]
if you dont find it amusing that an assistant can grind a spray can with some enzyme and then drink up the resulting """ beverage""" to heal a few scratches while also drinking welding fuel im sorry for your loss

**Comment by SinfulBliss** [comment]
quad sec, mime's silencer, med doc's doctor's delight, engi's screwdriver, clown's banana juice, chaplain's trappist beer - this is by no means some advantage assistants get. it's present for a vast variety of jobs.

**Comment by AlinaStarkova** [comment]
> Please get rid of warm donk pocket omnizine, it's letting assistants heal themselves too easily!!

difference is everyone has access to donk pockets, its not exclusive to tiders, as Rhosie stated, tiders shouldnt have perks over other jobs, even minor ones, because assistant is supposed to be a fall back job, we cant afford to have half the playerbase become greytide mains, else the jobs will never be filled




> quad sec, mime's silencer, med doc's doctor's delight, engi's screwdriver, clown's banana juice, chaplain's trappist beer - this is by no means some advantage assistants get. it's present for a vast variety of jobs.

the real issue is that hooch spawns in maint, its not even a rare or even uncommon spawn from what i understand, usually multiple spawn every round

**Comment by SinfulBliss** [comment]
> the real issue is that hooch spawns in maint, its not even a rare or even uncommon spawn from what i understand, usually multiple spawn every round

it actually _is_ rare and uncommon. don't take my word for it though - go scour maints as assistant and see how long it takes to find. guarantee it will be significantly longer than it takes to make those simple drinks in the bar (unlimited btw)

**Comment by ExcessiveUseOfCobblestone** [comment]
When ATH makes a RP post instead of a mechanical post you know it needs to be removed

**Comment by ExcessiveUseOfCobblestone** [comment]
Also stop full quoting your text walls omg

**Comment by Mickyan** [comment]
Anyone who mentioned drunken resilience as being anywhere equivalent to hooch or manly dorf healing needs to go back to primary school and learn some math, your stupid takes only make me regret making those quirks and now they're going to be on the chopping block because someone is going to take you seriously

**Comment by necromanceranne** [comment]
> I'm not gonna block it but I think the game should have more improvised fixes that encourage people to scavenge rather than removing them

I do think this still exists currently beyond just alcohol based healing. Many vendors provide access to food based healing, light as it is, and there exist places like abandoned bar to scavange bits and pieces for healing drinks/reagents.

Maybe it would be a good idea to look at a reagent like miner's salve and give it bit if a buff. Maybe even make that equivalent to the healing hooch gave assistants.

**Comment by Maurukas** [comment]
Can someone explain why I am being pinged with literal wall of text PRs about Hooch? I'm being asked to consider #64479 as an alternative to this PR, and this PR does not even have have its description filled out completely. What is this trying to accomplish and why?

This looks like a noxious removal of a minor without any justification.

**Comment by thgvr** [comment]
Should also get all of the bar drinks that heal you, and engineer liver traits. :)

**Comment by Rohesie** [comment]
I let this run a little bit longer than I should, merging it now.

To clarify, this is not an attempt to buff medbay as Shaps suggested. Improvised fixes and food medicine are very good in my book (tomato juice, tea, doc's delight, donk pockets and so on).
This is not against drinks having healing or other properties either.
And definitely this is not against the theme of concocting hooch to get some benefits out of it.

The reason I am interested in the PR and see it favorably is because of the firm belief that the Assistant job should have no in-game benefits whatsoever over other jobs. If hooch healed everyone or even another job (that made sense) I'd worry less about it.
Other drinks, food and stuff are fine as well.

Hopefully if something like this is re-added, it comes in a package that works for everyone, and not just Assistants.

**Comment by qbmax32** [comment]
cope assistant shitters

**Comment by SethLafuente** [comment]
I wish goof said more than a meme answer when it comes to "why this is good for the game"

then people would complain less I don't even know why maintainers dont tell him to change it

goof please give an actual reason you are only harming your reputation by giving shit answers like "Nerfing assistants is good, actually."

**Comment by Iamgoofball** [comment]
we recently received a video of greytiders and common tactics they abuse to get an edge in combat over general crewmembers for the purposes of griefing their rounds

changes like the hooch healing removal and the bugfix of spears w/o craft timers are targeted changes to discourage that kind of greytide gameplay in players

**Comment by Iamgoofball** [comment]
ill be honest i figured everyone had seen the video by the point the PR went up and that players were well aware of the greytide problems going on lmao

**Comment by SethLafuente** [comment]
havent seen it maybe you should link the video to the reason why is good and the explanation you just gave me

**Comment by jughu** [comment]
just wait till goof hears about the gamermos internals which doesnt let you get stunned and heals you

**Pull request merged**
