### PR TITLE
>Antag Canadates

### PR DESCRIPTION
**Pull request by silicons**
Canadates --> Candidates.

### CODE REVIEW

**Comment by francinum** [comment]
Canadadates.

**Comment by Haevacht** [comment]
Canadamates.
Also update your PR it also includes a newline!!!!
THE PEOPLE HAVE TO KNOW!!

**Comment by TehZombehz** [comment]
Admin Canadians.

**Comment by kevinz000** [comment]
canadadites

**Comment by francinum** [comment]
:canada:

**Comment by Shadowlight213** [comment]
:canada: :canada: :canada: :canada: :canada: :canada: :maple_leaf: :canada:

**Comment by Thunder12345** [comment]
🍁🍁🍁

**Comment by dannno** [comment]
was this on purpose or was someone actually this stupid

**Comment by ExcessiveUseOfCobblestone** [comment]
https://www.youtube.com/watch?v=zwDvF0NtgdU

**Comment by kilkun** [comment]
@dannno guess

**Pull request merged**
