### PR TITLE
Pyre Sect can now heal with a bible. Candles are now a more reasonable sacrifice method. Shortens some rituals

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Pyre Sect always was not allowed to heal people with the bible, but now it works like any other sect. On top of this, the favour of a lit candle is now 50 from the previous 20, which should make them SOMEWHAT reasonable to be offered, instead of just plain useless. The offering and unmelting protection times have been shortened, as they are meant to be done over and over again, but they're still in line with other sects. 
## Why It's Good For The Game

The original Pyre Sect PR did not allow the bible to heal because "it already has the rites to make it useful". But the only real useful rite is Unmelting Protection, whereas the forever candles are neat, but not really USEFUL, so it's a really unecessary nerf.
## Changelog
:cl:
balance: Pyre Sect can now heal with their bible as normal.
qol: Some of Pyre Sect's rituals have been shortened slightly
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
The breaking into the morgue sect deserves no QOL lmao

**Comment by Helg2** [comment]
Make it heal plasmemes xD

**Comment by Jezzared** [comment]
> The breaking into the morgue sect deserves no QOL lmao

Only cringe chaplains steal for the morgue (which is not technically breaking in, they have access).

Based chaplains get thirty monkey cubes and die to the swarm of monkeys they're trying to light on fire.
(That is to say, monkeys work for the sacrifice, which maybe should be more apparent because people seem to think it has to be humanoids).

**Comment by DATA-xPUNGED** [comment]
> > The breaking into the morgue sect deserves no QOL lmao
> 
> Only cringe chaplains steal from the morgue (which is not technically breaking in, they have access).
> 
> Based chaplains get thirty monkey cubes and die to the swarm of monkeys they're trying to light on fire. (That is to say, monkeys work for the sacrifice, which maybe should be more apparent because people seem to think it has to be humanoids).

Monkeys are not as aesthetically pleasing as humans when burning on the stake

**Comment by Jezzared** [comment]
> Monkeys are not as aesthetically pleasing as humans when burning at the stake

Solution: Mutadone the monkeys.

**Comment by carlarctg** [comment]
> The breaking into the morgue sect deserves no QOL lmao

This is a problem with how bothersome it is to attain corpses (especially nonhuman ones), not chaplain

**Comment by Jezzared** [comment]
> This is a problem with how bothersome it is to attain corpses (especially nonhuman ones), not chaplain

I don't find it bothersome.
Mutadone a monkey for human, don't mutadone it for non-human.

**Comment by TheBoondock** [comment]
Pillow man approved 👍

**Pull request merged**
