### PR TITLE
Sign Language Refactor & Bugfixes

### PR DESCRIPTION
**Pull request by Floofies**
## About The Pull Request
This PR contains an intermediate refactor and a bug-fix for sign language, which was originally from the Tongue Tied quirk/tongue. With helpful advice from @MrMelbert and @LemonInTheDark, I have successfully decoupled sign language from the tongue and ported it into a highly modular DCS component, and then added an Action for toggling it. Big thanks to @Wallemations, the original creator of Tongue Tied, for creating the new Action sprite and helping me to complete this project!

The new sign language component is added to all new Carbon mobs, and incrementally overrides several critical functions, variables, and argument lists relevant to a mob's speech; the component primarily listens for the addition/removal of trait `TRAIT_SIGN_LANG` in order to function.

Additionally, fixed a bug in the original implementation of sign language that caused its say verbs such as "emphatically signs" to stop working. The bug was caused by an unsafe early removal of exclamation points from the input string, causing a conflict with the `say_mod` proc which requires such punctuation points to be present.

Here's a granular list of changes:
- Added a ubiquitous signal to extend the behavior of `/atom/movable/proc/say_quote`.
- Added a ubiquitous signal to extend the behavior of  `/atom/movable/proc/lang_treat`.
- Fixed a bug in the original implementation of sign language that caused its `verb_yell` to stop working.
- Refactored sign language into a Carbon-only DCS component.
- Refactored the Tongue Tied tongue to use `TRAIT_SIGN_LANG` and `TRAIT_MUTE`.
- Removed the Tongue Tied quirk, in favor of two separate quirks.
- Added the Signer quirk for sign language, good, costs 4 points.
- Added the Mute quirk, negative, gives 4 points.
- Added a rare sign language Action granter book to maint and space loot, "Galactic Standard Sign Language".

## Why It's Good For The Game
This PR tactfully re-implements Tongue Tied, re-introducing it as two new quirks: For sign language itself, I added the Signer quirk, which is a good quirk which allows you to use sign language for 4 quirk points. I also added the Mute quirk, which grants 4 quirk points in exchange for your audible voice. There is also a marked improvement in the code health as a result of my changes.

Here's a preview of the sign language Action. If you're also mute, it becomes invisible to reduce clutter:
image

In regard to how useful sign language is, it can be used as:
1. A way to communicate across a vacuum without a radio.
2. An easy way to communicate with deaf people.
3. An easy way to communicate as a Mute person.

## Changelog

:cl: A.C.M.O.
del: Removed the Tongue Tied quirk. The tongue can still be found and used in-game.
refactor: Refactored Tongue Tied's tongue to use the Sign Language and Mute traits.
add: Added Sign Language innate action. Granted by book or quirk.
add: Added the Galactic Common Sign Language book as rare maint and space loot.
add: Added the Signer quirk, which teaches you sign language in exchange for 4 quirk points.
add: Added the Mute quirk, which grants you 4 quirk points in exchange for your voice.
fix: Fixed sign language say_yell verb, which allows you to emphatically sign.
/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
will the signer quirk give you the radio gloves? or do you need to craft your own roundstart?

**Comment by Wallemations** [comment]
> will the signer quirk give you the radio gloves? or do you need to craft your own roundstart?

It does

**Comment by Wallemations** [comment]
My concern, as it was similarly before, is the Mute quirk, and how it's basically free points for mimes.
Without a way to limit that I don't know if this will get far

**Comment by Floofies** [comment]
@Wallemations Well, the system for selecting quirks is at overarchingly at fault here, not the quirks themselves. In regard to who would dare solve the issue, I am. The glaring imbalance with quirks isn't the scope of this PR but one must acknowledge that you can not change quirks without risking more imbalance. In the future, I'm going to work on fixing this type of issue. It has to be fixed via quirk filtering, and isn't within the scope of this PR.

**Comment by Wallemations** [comment]
I understand that I'm just trying to think of what might hold it back as it stands currently. It's outside the PR's scope to refactor quirks with filters but that doesn't mean it won't be considered.
I hope someone gets on that filtering soon at least

**Comment by Floofies** [comment]
@Wallemations I had an idea. What if for Mimes, the Mute quirk was more severe, and also muted their ability to emote/gesture?

**Comment by Time-Green** [comment]
Does everyone still magically understand sign language?

**Comment by Floofies** [comment]
> Does everyone still magically understand sign language?

@Time-Green Yes, based on the selected language. If they understand the spoken language (Common, Spacer, etc), then they can understand when it's signed too.

**Comment by Troxonater** [comment]
Let mimes get free quirk points. Not being able to directly talk is a HUGE disadvantage in every RP scenario. Also, if a mime tries to powergame by taking mute they completely remove their ability to use spells, most commonly acquired being heretic spells, so I think it evens out if someone is trying to powergame.

**Comment by Wallemations** [comment]
> Let mimes get free quirk points. Not being able to directly talk is a HUGE disadvantage in every RP scenario. Also, if a mime tries to powergame by taking mute they completely remove their ability to use spells, most commonly acquired being heretic spells, so I think it evens out if someone is trying to powergame.

What mimes lose in speech they gain in their mime abilities and healing via nothing & silencer

**Comment by Floofies** [comment]
I have worked out a couple of last minute bugs/oversights. My work on this PR is complete. I have ensured that the contents of the PR are Byond version 515 compliant.

Please let me know if you see anything that needs to be tweaked! Thank you.

**Comment by Floofies** [comment]
I have added some requested changes. Now the quirk adds the component, which grants the action, which toggles the trait... This causes a bug when any one of those are removed, because the requested changes tightly couple the action to the component and vice versa. Indeed this eliminates any possibility of other toggles being used, including the Tongue Tied tongue, which I had to remove in order to fix the bug.

**Review by tralezab — APPROVED** [review]
good work

**Pull request merged**
