### PR TITLE
Gang Update: Loyalty Implant Edition

### PR DESCRIPTION
**Pull request by Ikarrus**
Security treating gangs like revs has had a very negative impact on the experience of gang rounds. With an easy and convenient deconversion method, security gets encouraged to take the offensive and start mass implanting. Gangs are then easily stomped as they are not as powerful as revs, and rapidly run out of members to convert.

I'm going to try something different and see how things go if implants in gang mode acted as they are in cult.
- Implants can still prevent conversion, but can no longer deconvert or identify gangsters
- Gang bosses will now know if someone they are trying to recruit is loyalty implanted or an enemy gangster
- Removed tommy guns
- Added 9mm 2-burst 32 mag uzis that costs 40 influence. Unlike tommy guns gangs will be able to purchase ammo for uzis.
- Tommy guns returned to it's original super OP form
- Fixed a bug where announcements were being made for destroying dominators that haven't been turned on

### CODE REVIEW

**Comment by Cheridan** [comment]
:hocho: :baby:

**Comment by Xhuis** [comment]
The loyalty implanting displays a message if they meet the criteria but doesn't return 0, so if I'm not mistaken they'd get implanted anyways.

**Comment by Ikarrus** [comment]
As designed

**Comment by Ikarrus** [comment]
As designed

**Comment by kevinz000** [comment]
Yeah but in the majority of rounds a gang will take over
This will just make it harder for security to fight them

**Comment by Lumipharon** [comment]
Rounds where sec implant heavily are pretty meh. Any nerfs to implants improve this gang mode greatly.

**Comment by CPTANT** [comment]
This will lead to the new sec meta being to simply execute gangsters though.

And if loyalty implanted people can't be trusted sec will be even more outnumbered than they already are.

**Comment by Ikarrus** [comment]
That's fine. Unlike rev, security isn't the focus this time around.

Removing implant deconversions also removes security's antag check tool. They won't be able to go around systematically implanting the entire station. So while executions would be a little more common, gangsters are less likely to be caught.

**Comment by GunHog** [comment]
To be honest, any kind of stealth does not seem fitting to a gamemode named "gang". It seems like something designed to be loud. The name, the territory claiming system, the dominator machine...getting caught does not seem like something that should be a gangster's concern.

**Comment by Ikarrus** [comment]
I know the word gang could mean a lot of things to different people, which is one of the reasons why I avoid establishing what kind of gang it is exactly --It's up to the players how they want to interpret it.

Fluff aside, a gang in this case is simply a faction vying for total control of the station.

**Comment by Ikarrus** [comment]
Hey I ended up with some free time so I added Uzis.
9mm 
2-burst
32 round magazines
40 influence
Can buy more ammo for

**Comment by Saltycut** [comment]
Looks like even more suffering for sec, and you won't be really able to trust anyone anymore since you don't have anything equal to holy water during cult and as I assume head bashing like in revolution doesn't work either. The most reasonable thing in this situation is just executing anyone who will have any gang items on them :(

**Comment by Ikarrus** [comment]
head bashing still works

**Pull request merged**
