### PR TITLE
[READY] tgui-next: Bank Machine & UI tweaks (Gravity Generator, Equipment reclaimer)

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR converts Bank Machine to tgui-next UI with some slight tweaks regarding text and structure.

**BEFORE:**

OldBankUI

**AFTER:**

NewBankUI

Also contains small tweaks for my previous UIs - Gravity Generator and Equipment Reclaimer Console. Gravity Generator got small resize, status is now clearly marked as a breaker and charge mode now shows full charge/discharge without noticebox. Equipment Reclaimer Console got small resize, alignment and code cleanup.

## Why It's Good For The Game

Better UIs.

## Changelog
:cl: Arkatos
add: Bank Machine now uses tgui-next UI.
tweak: Small UI tweaks for Gravity Generator and Equipment Reclaimer Console.
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Merge conflict

**Comment by kriskog** [comment]
Merge conflict again.

tgui lads, how does this look? @stylemistake @actioninja

**Review by kriskog — DISMISSED** [review]
Should be okay, but Im no tgui expert

**Comment by stylemistake** [comment]
Is fine.

**Pull request merged**
