### PR TITLE
EI NATH! now causes a flash of light

### PR DESCRIPTION
**Pull request by ghost**
i've been reading too much harry potter

:cl: More Robust Than You
add: EI NATH! now causes a flash of light
/:cl:

### CODE REVIEW

**Comment by Mercenaryblue** [comment]
Another thing that'll needlessly blind the wizard.

**Comment by MoreRobustThanYou** [comment]
@Mercenaryblue I made it so wizards aren't flashed by it

**Comment by calzilla1** [comment]
Oh boi youre buffing el Nath weeeee

**Review by Cyberboss — APPROVED** [review]

**Comment by duncathan** [comment]
let's see how bad of an idea this is

**Pull request merged**
