### PR TITLE
Buffs the Clarke Mech

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

the clarke mech no longer gives you a diagnostic hud
the clarke mech can now attack in all directions instead of just the ones its facing
the clarke mech now has an ability that lets you pinpoint to the nearest ruin

## Why It's Good For The Game

as the explorer/mining mech, clarke should have cool exploration abilities, not diagnostic huds fit for engineering/science stuff

## Changelog

:cl:
balance: Clarke can now attack in all directions
balance: Clarke can now search for ruins
balance: Clarke no longer gets a diagnostic HUD
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
> the clarke mech can now attack in all directions instead of just the ones its facing
traitor robos with the concealed weapon bay item:
image

**Comment by githubuser4141** [comment]
> > the clarke mech can now attack in all directions instead of just the ones its facing
> 
> traitor robos with the concealed weapon bay item: 

I think it'd still be relatively niche what with the Clarke's low HP, low reliability (crit failures including gear loss start at 60% health) low armor and more importantly the lack of strafe preventing the clarke from actually dodging attacks or keeping it's front armor turned towards the enemy.

**Comment by Coastfront** [comment]
> > the clarke mech can now attack in all directions instead of just the ones its facing
> 
> traitor robos with the concealed weapon bay item: image

The one time i saw a clarke used in combat ever they got instantly killed by 2 guys with eguns

**Review by Krysonism — APPROVED** [review]
Sprites seem cool

**Pull request merged**
