### PR TITLE
Players can take a free 1-point quirk if they have no other point-influencing quirks

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: You can now pick a free 1-point positive quirk if you have no other point-influencing quirk.
add: This quirk will stop being free if you add other non-neutral quirks, so to get two 1-point quirks you still need two points in negative quirks.
/:cl:

Lets players interact with the quirk system without necessarily taking on penalties. 1-point quirks are generally for flavor and shouldn't really be a balance issue by themselves.

### CODE REVIEW

**Comment by Barhandar** [comment]
So you're saying I can take light step for free without getting the downside of being asleep for annoyingly longer?

**Comment by XDTM** [comment]
Tbh light step sounds more on par with 2-point quirks, but rebalancing it is out of scope here

**Comment by kingoftheautism** [comment]
Also sleep may (or may not) save you if you ambushed by carps or bears

**Comment by Cyberboss** [comment]
Are quirk usages logged in feedback? If not, we definitely need them now to properly balance them now that they have no downsides

**Pull request closed without merging**
