### PR TITLE
Admin revive clears suicide status

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
This PR makes admin revives set the mob's `suiciding` var to FALSE. The regular fully_revive() proc is unaffected.

## Why It's Good For The Game
This makes it easier for admins to bring suicided players back into the game, like when someone suicides instead of letting an admin offer their body to ghosts.

## Changelog
:cl: Denton
admin: Admin revives now set the mob's `suiciding` var to FALSE. 
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
Thanks

**Review by SpaceManiac — APPROVED** [review]

**Comment by ATH1909** [comment]
Does this affect staves of healing?

**Comment by 81Denton** [comment]
I think those don't use the admin revive part of the proc

**Comment by MCterra10** [comment]
Tbh healing staves/wands shouldn't revive suicided players.

**Pull request merged**
