### PR TITLE
Skirt update

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Some skirt sprites were offset i dont know how this happened i swear i fixed this before but apparently not. Fixed the assistant skirt necklines being way too high. Added extra details on some skirts. 
Added 5 previously missing skirts including 2 lawyers skirts(like they dont have enough already), rainbow, syndicate and tacticool. Fixed the disorganized mess that was the Lawdrobe.

## Why It's Good For The Game

Updated skirts good. Rainbow skirt good. Skirtleneck good.

## Changelog
:cl:
add: The long lost rainbow jumpskirt has been found
add: Rumor has it that even the syndicate have started producing skirts for their operatives
tweak: Department skirt necklines are more in-line with their jumpsuit counterparts, sprites are no longer offset, added detail
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Tacticool skirts is too much. Stop.

**Comment by tralezab** [comment]
i read that changelog and i knew someone would be mad instantly

**Comment by Twaticus** [comment]
image

**Comment by HomocidlePancakes** [comment]
Oranges has hurt me mentally

**Comment by wesoda25** [comment]
r u dumb?? its well known that the syndicate doesn't hire females.... smh

**Review by actioninja — APPROVED** [review]
thanks, I hate it

**Comment by necromanceranne** [comment]
Skirt ops incoming

**Comment by Tlaltecuhtli** [comment]
NO

**Comment by optimumtact** [comment]
Yes

**Comment by OverlyGeneric** [comment]
LADS, WHERES THE BLOODY TACTICOOL KILT?

image

**Pull request merged**
