### PR TITLE
Redone Metastation Science

### PR DESCRIPTION
**Pull request by AlinaStarkova**
THE MAP FUNCTIONS AND EVERY CHANGE HAS BEEN TESTED AND ALL WORK

(Had to reopen because while working with Conductive Potato to fix conflicts due to my branch being way out of date, updating my branch made github close my old PR because there were no "differences" for a few minutes, since the old PR had a lot of changes to it since it was first opened i figured a new PR wont hurt.... the cytology stuff comes with machines to be placed in science, so merge conflicts would occur if i made the PRs seperate, so i had to combine them, the cytology update is fairly minor, Maptainer man said its ok)

## About The Pull Request

redoing metasci + added a Cytology section to xenobio, Note: Everything changed and added has been tested, everything functions as intended and nothing has been broken 

1. Science has been completely redone on Metastation. (rework by Zytolg, setup of disposals, some bits of atmos, fixing errors and roundstart ATs and some other specific edits to get science connected again done by me)
image

image

2.a. Added a fully connected and functional Cytology Lab *section* to Xenobio.
image

3. Added an Cytology Area, so cameras can observe the area, and sensors can track the location
image

4. Created a new Smart Fridge Variant: Petri Dish Fridge, which can only store Petridishes, Metastation Cytology Lab starts with 5 Dishes in its fridge (currently it stacks all petridishes together no matter what, as petridishes dont get unique names, thats an issue with cytology itself, i was thinking when a new dish is made, its given a random # between 0-1000 after its name, nice and simple, but im having trouble coding that myself)
5055c21833aab7c144e45f5a4ac252eb

5. Added and Sprited Cytology Wikibook
image

## Why It's Good For The Game

Cytology was added to the game as well as plumping for said Cytology, however there currently is not enough space to fully utilize Cytology at the current point in time (especially since Xenobiologists tend to end up creating many extra pens). This update not only adds a dedicated Cytology work lab (only on metastation at the moment) but also updates functionality to act as a quality of life benefit for those wishing to work in Cytology

## Changelog
:cl: Dr. Harimoto + Zytlog
add: Petri Dish Smart Fridge - Nari Harimoto
add: Cytology Area - Nari Harimoto
add: Cytology Lab (Metastation) - Nari Harimoto
tweak: Completly redone Science Department on Metastation - Zytlog + 10% Nari Harimoto
add: Cytology Wikibook - Nari Harimoto
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
inb4 maintainers close this and tell you to atomize

**Comment by AlinaStarkova** [comment]
> 
> 
> inb4 maintainers close this and tell you to atomize

bro what does atomize mean?

**Comment by MrDoomBringer** [comment]
splitting a PR into multiple smaller and easier-to-review PRs

**Comment by AlinaStarkova** [comment]
> 
> 
> splitting a PR into multiple smaller and easier-to-review PRs

well, i explained up top that i actually couldnt, because the cytology changes actually is mostly changes to xenobio, and that obviously has a major conflict with the changes to science, i had no choice but to merge

also i WAS working with Conductive Potato on fixing the conflict for this PR, and hes a maintainer, so i blame him if the other maintainers close it for not being split, since he didnt say anything about it *shrugs*

**Comment by RaveRadbury** [comment]
cytology was made to be under xenobiology, don't rob them of that

**Comment by MrDoomBringer** [comment]
i mean i really doubt a maintainer will actually close this themselves, usually they just ask you to atomize it and let you handle whatever needs to be done

but anyways the only real issue I see is the random metastation science map rework that has nothing to do with the cytology change, as from what i can tell cytology is being done in the xenobio satellite. I don't see why it couldn't be split off into a different pr

**Comment by AlinaStarkova** [comment]
> 
> 
> cytology was made to be under xenobiology, don't rob them of that

it is *literally* still in xenobiology, did you actually look at the screenshot? its literally a dedicated lab connected to xenobiology and has all the same access as xenobiology, its a xenobiology lab, but seperated because slimes and cell growth are still very different things, and you want to keep the two contained seperately incase of a breach

**Comment by AlinaStarkova** [comment]
> but anyways the only real issue I see is the random metastation science map rework that has nothing to do with the cytology change, as from what i can tell cytology is being done in the xenobio satellite. I don't see why it couldn't be split off into a different pr

because both changes modify xenobiology, causing conflicts, the only way to atomize this, literally, is to do the science rework, wait 2 weeks for the average merge time, *if* it even merges, then do ANOTHER map edit to add in the cytology changes

**Comment by Qustinnus** [comment]
yes, it is. So do it.

**Comment by Zytolg** [comment]
You could call this "Metastaiton Redone Science" and it would still be correct. If Cytology hadn't already been being worked on when I redid metasci, I would have added in Cytology Labs myself.

**Comment by AlinaStarkova** [comment]
opened up cytology, has a lockdown, but is otherwise the same room as the rest of xenobio

image

**Comment by bluetshirtguy** [comment]
Metastation continues to be more bloated, more at 11.

**Comment by AlinaStarkova** [comment]
> 
> 
> Metastation continues to be more bloated, more at 11.

a single small area was added to xenobio since xenobio now has a plumbing tool mechanic and requires the extra space for that, i wouldnt call that bloat

**Comment by LemonInTheDark** [comment]
Atomization would help your chances here, do you plan on adding this new machine to other maps?

**Comment by AlinaStarkova** [comment]
> 
> 
> Atomization would help your chances here, do you plan on adding this new machine to other maps?

yes, as well as adding in a cytology lab to every map, problem is other maps have issues with how its designed (delta for example, is completely surrounded by maint, to add a new section to xenobio i have to modify maint itself in that area)

i could atomize if maintainers really want it done, but that would mean i would have to wait for each one to merge before i even open the PR for the other, even though both pertain to modifying the map (albeit a difference in scale)

well, at the very least i can pull off the labcoat and biobag change and make a mini-PR for that but the rest are additions to the map and/or a map change

**Comment by MrDoomBringer** [comment]
@AlinaStarkova 
This isn't terribly complicated
Create PR#1, include science map rework
Create PR#2, branched off 1, with cytology changes, including cytology-specific map alterations if need be
Mention in the second PR that it requires PR#1

**Comment by AlinaStarkova** [comment]
> @AlinaStarkova 
> This isn't terribly complicated
> Create PR#1 with the science map rework
> Create PR#2, branched off 1, with cytology changes, including cytology-specific map alterations if need be
> Mention in the second PR that it requires PR#1
> 
> People make PRs that require other PRs all the time
> 

the issue is that i can't do the PR 2 without PR 1 fully being merged, because the specific cytology alterations is in an entirely different part of the map depending on if thr PR1 is merged or not, hence i cant just make a second PR with just the alterations because the alterations entire location is atleast 50 tiles away or more based on PR1

**Comment by MrDoomBringer** [comment]
I suggest reading up on git and github docs a bit more, then.

> Create PR#2, branched off 1

when i said this, i meant PR#2 should be branched off of the branch you use for PR#1. This means PR2 will have all the changes from PR1 (ie the moved xenobio) as well as whatever additional code you add (ie adding the cytology lab to xenobio)
image

**Comment by AlinaStarkova** [comment]
> 
> 
> I suggest reading up on git and github docs a bit more, then.
> 
> > Create PR#2, branched off 1
> 
> when i said this, i meant PR#2 should be branched off of the branch you use for PR#1. This means PR2 will have all the changes from PR1 (ie the moved xenobio) as well as whatever additional code you add (ie adding the cytology lab to xenobio)
> image

ill try, but im like brand new to github so if i fuck something up im gonna,.... probably cry because this has been a lot of work just to get all this together..

**Comment by AlinaStarkova** [comment]
@MrDoomBringer Maptainer man said this atomization is good, moved the 2 item tweaks to a diff PR, but the items added that get added to the map is ok to stay here, atleast Maptainer man said so :)

**Comment by MrDoomBringer** [comment]
nice, glad it worked out 👍

**Comment by Zytolg** [comment]
Conflict from #55904 is due to an area fix. That location is changed with these Metastation changes (Previous location of Maintbotany becomes space and the Toxins Launch Room).

**Comment by AlinaStarkova** [comment]
> Conflict from #55904 is due to an area fix. That location is changed with these Metastation changes (Previous location of Maintbotany becomes space and the Toxins Launch Room).

should be fixable by just merging the upstream/master into the branch, ill do it when i get home, after saving the map file just in case

**Comment by AlinaStarkova** [comment]
I cannot fix the conflict, i merged from upstream, gave me a bit of trouble from one tile, but for whatever reason its giving me a conflict

the conflict occured after a PR was recently merged that added a single area tile to maint botany, which is modified in my PR (its now a maint wall) and now no matter what i do, the conflict wont go away

**Comment by AlinaStarkova** [comment]
holy shit, i think i fixed it, was massive pain to do, had to paste in the changes in by hand

**Comment by Rohesie** [comment]
This has been open for a long, long time and it's now stale again.
Is Inept alive?
Are you still willing to work on this, @AlinaStarkova ?

**Comment by EOBGames** [comment]
Apologies for the slow response to this PR, once you've smoothed out this last conflict please ping me, either here or on discord, and I'll merge this.

**Comment by AlinaStarkova** [comment]
> This has been open for a long, long time and it's now stale again.
> Is Inept alive?
> Are you still willing to work on this, @AlinaStarkova ?

the PR is done, sadly the merge conflicts keep cropping up out of my control, this is the 7th merge conflict ive had to fix because of how old it is. ill fix it in a bit

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-12). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Zenitheevee** [comment]
so, small issue i noticed from an upstream

https://imgur.com/Ub0y2fw

Is this even usable without gibbing yourself?

**Comment by AlinaStarkova** [comment]
> 
> 
> so, small issue i noticed from an upstream
> 
> https://imgur.com/Ub0y2fw
> 
> Is this even usable without gibbing yourself?
> 
> Edit: To clarify: Mech charging machines are solid, Yes?
> And mechs **Are** Solid.
> While you may have a few seconds to step out of the way, This seems like an extreme hazard and, If i recall correctly, Standing on the mech pad while not in a mech **Will** Gib you.

the image is out of date, sorry, i didnt feel the need to reupload the image from a small edit the maptainer had me do, but rest assured thats moved to the middle of the room and is free of obstruction

**Pull request merged**
