### PR TITLE
Adds a public autolathe to all maps.

### PR DESCRIPTION
**Pull request by AndrewJacksonThe2nd**
The common spaceman has a right to a public autolathe in his station at all times.

The two stations that already had public autolathes, Metastation and Birdstation, were left alone.

Ministation, due to lacking a Primary Tool Storage, had its autolathe placed in the maintenance cubby where the Youtool and other tool storage machines are.

All other stations had a public autolathe placed in its Primary Tool Storage.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:+1:

**Comment by Dawgas** [comment]
only thing to consider is ye olde public autolathe was in its own little room iirc

just consider that your placements may be a little too open for fun stuff

**Comment by Fox-McCloud** [comment]
Mind providing pics of each location?

**Comment by Aranclanos** [comment]
don't make an alt accounts

**Comment by Dawgas** [comment]
but then who was alt?

**Comment by Iamgoofball** [comment]
i was alt

**Pull request closed without merging**
