### PR TITLE
hunter spider now has doubled poison injections

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

hunter spider now has doubled poison injections, up from 5 to 10

## Why It's Good For The Game

hunter spiders are literally just a worse red spider with no reason to pick the purple ones other than speed, they were supposed to have more toxin but someone nerfed that and now both red and purple inject the same amount of toxin

## Changelog
:cl:
balance: hunter spider now has doubled poison injections
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Red injects poison? Fairly certain it does not.

**Comment by ExcessiveUseOfCobblestone** [comment]
it does 5u of toxin (the reagent needed for syrin)

**Comment by ATH1909** [comment]
This is a shapeshift form for wizards, right?

Would it be possible to bump the health of the wizard version up a bit and/or make hunter spiders in general able to move faster than the default running speed? It's a really underwhelming shapeshift form because your victim can just turn around and bonk you before they die to your poison.

**Comment by kriskog** [comment]
Which one is the hunter, purple?

**Comment by HomocidlePancakes** [comment]
@ATH1909 Use the shapeshift in tandem with smoke and force walls.

**Comment by Fikou** [comment]
> Which one is the hunter, purple?

yes

**Review by kriskog — CHANGES_REQUESTED** [review]
Its too much. Viper is 12 and only has 40 health becasue of that. Reduce the baseline poison and up this one slightly instead. Baseline 3, hunter 6 seems okay to me.

**Comment by kriskog** [comment]
It was pointed out to me the viper injects venom, not toxin. Okay then.

**Pull request merged**
