### PR TITLE
Removes soulful sprites of crates from the game

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Ports crate sprites from https://github.com/Citadel-Station-13/Citadel-Station-13/pull/7652, that's it.
Credits to Michiyamenotehifunana for the sprites

image

## Why It's Good For The Game

Our crate sprites are older than dinosaurs, time to replace them

## Changelog
:cl:
imageadd: Ports crate sprites from Citadel
/:cl:

### CODE REVIEW

**Comment by celotajstg** [comment]
screenshots pls

**Comment by SmArtKar** [comment]
image

**Comment by Colovorat** [comment]
Add tag Against God and Nature

**Comment by Fikou** [comment]
not good enough to warrant a change, too small and still missing stuff like the mining carts or necro crates

**Comment by Imaginos16** [comment]
These crates look like Lego. I'd much rather have them be reworked entirely.

**Comment by notfrying1pans** [comment]
this has been tried in the past, and it hasn't gone through. there also isn't any demand to resprite crates currently.

**Comment by Dorsisdwarf** [comment]
I understand you're copying the sprites from citadel, but is there an in universe explanation for why they're ribbed for her pleasure?

**Comment by cacogen** [comment]
Clearly they stack like legos also it doesn't fit the existing artstyle etc

**Comment by bluetshirtguy** [comment]
those are some ugly ugly crates.

**Comment by Farquaar** [comment]
> 
> 
> I understand you're copying the sprites from citadel, but is there an in universe explanation for why they're ribbed for her pleasure?

I'd imagine it's so that they interlock during shipping.
Or something

**Comment by Mothblocks** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title that explains the purpose of the PR.

Your current title does not meet requirements, so please update it.

**Comment by SmArtKar** [comment]
Everybody hates the sprites so I close the PR

**Comment by Hamurlik** [comment]
i dont understand why do we have new chairs and tools if they are in the exact same style, they stick out of place and suck ass. why do they still exist?

**Comment by Twaticus** [comment]
this is a closed crate pr

**Comment by Mothblocks** [comment]
it has sprites for open crates too

**Comment by maxymax13** [comment]
> 
> 
> i dont understand why do we have new chairs and tools if they are in the exact same style, they stick out of place and suck ass. why do they still exist?

how dare you compare these pokemon game boy advance ass sprites to ours

**Pull request closed without merging**
