### PR TITLE
Cult Cove, Neon Flamingo and Slowdive

### PR DESCRIPTION
**Pull request by RigglePrime**
## About The Pull Request

Adds 3 new bar signs from the contest

## Why It's Good For The Game

image

## Screenshots

Screenshot 2023-12-03 052300
Screenshot 2023-12-03 052318

cult
nf
SLOWDIVE

## Changelog

:cl: Chimpston, atlasle and aBlimpfox
image: added Cult Cove, Neon Flamingo and Slowdive bar signs
/🆑

### CODE REVIEW

**Comment by atlasle** [comment]
REAL bar signs made by REAL LISA: The Pointless fans

**Comment by Wallemations** [comment]
What happened to the slow dive sign? Why does it look like it has a crack in it?

**Comment by Chimpston** [comment]
> What happened to the slow dive sign? Why does it look like it has a crack in it?

where in the sprite does it look like there's a crack? i'm a little bit confused and don't really see it myself.

**Comment by atlasle** [comment]
yeah not sure what you mean by that, additionally i didn't make the sign with white pixels in the corner, a bit confused as to why there's some in the screenshot

**Comment by Chimpston** [comment]
> yeah not sure what you mean by that, additionally i didn't make the sign with white pixels in the corner, a bit confused as to why there's some in the screenshot

OH that's more than likely a transparency issue because the sign is a little bit smaller than the initial template.........................

**Comment by Wallemations** [comment]
Are these animated? Could you upload a gif of them? Asprite should let you easily export a resized sprite gif
I'm on mobile so I can't really easily check the icondiffbot

**Comment by RigglePrime** [comment]
Added GIFs

**Comment by Wallemations** [comment]
> Added GIFs

ohhh the "cracks" are whatever is going on in the background

what exactly is going on in the background?

**Comment by atlasle** [comment]
> what exactly is going on in the background?

theyre bubbly waves

**Pull request merged**
