### PR TITLE
Gives suit storage units the ability to remove radiation from mobs

### PR DESCRIPTION
**Pull request by googobbug**
## About The Pull Request

Suit storage units will, in addition to decontaminating items, remove radiation from mobs.

## Why It's Good For The Game

The radiation cleaning machine should clean radiation. This also opens up the ability to perform (extremely painful) ghetto radiation treatment.

## Changelog
:cl: Bumtickley00
tweak: Suit storage units will now also remove radiation from mobs.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
This is the perfect excuse for the CMO to toss the irradiated CE into her personal suit unit as payback for turning Medbay into a wasteland! Showers just do not seem to get the job done otherwise.

**Comment by Shapsy** [comment]
So it that how UV baths work? I thought it'd make you more prone to cancer, not less

**Comment by optimumtact** [comment]
Just add a proper decontamination shower booth that removes contamination at an increased rate

**Comment by AdmiralPancakes1** [comment]
yeah that makes a lot more sense. let me go do that

**Comment by PKPenguin321** [comment]
This should still be open as a ghetto alternative!!

**Comment by AdmiralPancakes1** [comment]
oh right the showers and this aren't mutually exclusive, I'm an idiot

**Comment by Qustinnus** [comment]
This is too strong, do what oranges said instead

**Pull request merged**
