### PR TITLE
Fixes revenant abilities

### PR DESCRIPTION
**Pull request by ghost**
yeah ofc revenants dont have clothes and they aren't humans!

:cl: More Robust Than You
fix: Fixes revenant abilities
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
I'm curious if you tested if they were broken in the first place.

**Comment by ChangelingRain** [comment]
And by curious, I mean I know you didn't, so this doesn't actually fix anything.

**Comment by MoreRobustThanYou** [comment]
I just tried this on a live server (manually VV'd the spells human_req to 0), and it fixed it.

**Comment by ChangelingRain** [comment]
There is nothing to fix.

**Pull request closed without merging**
