### PR TITLE
generalized welding tank explosions

### LINKED ISSUE #14936: Welding fuel tanks explode oddly when hit by a KA blast
When you hit a welding fuel tank with a welder or shoot them with a laser they explode in a piddly little explosion just around the welding tank.

However when you shoot a welding fuel tank with a kinetic accelerator it makes a much larger explosion that blows a hole into the station's floor.

Accordings to K Peculiar it is not logged, whereas the other welding fuel tank explosions are.

@KorPhaeron I assume.

### PR DESCRIPTION
**Pull request by MMMiracles**
Fixes #14936

I guess also a nerf to blob welder-bombs because for whatever reason that did a bigger explosion then just shooting/exploding/setting it on fire?

### CODE REVIEW

**Comment by Cheridan** [comment]
nooo blob nukes are literally the best thing about the game

**Comment by MMMiracles** [comment]
what if i make them all explode like blob nukes

**Comment by Buggy123** [comment]
I think that would be better, no one really bothers to use welder bombing offensively so it'd be interesting to see how buffing it a bit changes things.

**Comment by newfren** [comment]
If they all explode like blobs hitting them then every welding fuel tank can put a hole in the ground which sounds awful.

**Comment by Zilenan91** [comment]
Yeah make them all explode like blob nukes.

**Comment by tkdrg** [comment]
who cares about blob nukes honestly

**Comment by tkdrg** [comment]
ok since @Cheridan is so pushy i guess you should make a "big" arg or something so we can generalize it and keep the segregation

**Comment by tkdrg** [comment]
mso included this in the tesla PR so it's redundant

**Pull request closed without merging**
