### PR TITLE
Phazon construction nerf

### PR DESCRIPTION
**Pull request by ghost**
Simply put, this PR adds an extra step to the construction of Phazon mechs. Rather than armor addition being the final step in their construction, Phazons also require an anomaly core, which can be obtained from randomly-spawning anomalies.

Phazons were originally not intended to be used in-game, and currently they are very powerful for the relatively small amount of resources they require. This is intended to make them a little rarer at the very least, giving people an actual incentive to go through the trouble of deactivating anomalies. There is also a heavy tradeoff; anomaly cores are fairly good for research levels, so you have to choose between a single phazon and higher research.

### CODE REVIEW

**Comment by WJohn** [comment]
Maybe instead make it so they require an anomaly core instead of a bluespace crystal?

**Comment by Xhuis** [comment]
I figured I would leave the bluespace crystal requirement since, fluff-wise, the mech would need a more stable way of bluespace translocation than an unstable anomaly core. Perhaps the stability of the crystal balances out the instability of the anomaly core.

**Comment by Chocobro** [comment]
big fan :+1::+1::+1:

**Comment by chimersable** [comment]
I don't know what an anomally core is,  I've never seen one in game, and the two tg wikis don't know either. So basically you are adding a requirement that is admin spawn only.

 And ontop of that the phazon is pretty junky too, armor sucks, it can be hit while phaseing, phaseing through much more than six objects leaves the battery nearly drained, it has a low amount of hit points, and micro tool array seems broken

**Comment by Miauw62** [comment]
>i dont know it so its not there

ayy lmao
didn't you need to research anomaly cores to build a phazon in the first place?

**Comment by Fayrik** [comment]
:+1: x :100: 
This is a fantastic idea that makes the until-now virtually worthless anomaly core now worth a lot.
Anything that adds extra value to anomaly cores is a definite good change, in my opinion.

@Miauw62 Even if you did need to research them in the first place, now you need one for each phazon. This now means we're not going to see ten phazons in a round, and that's the really important thing here.
(Hell, if someone does manage to make ten phazons with this update the entire crew deserves a medal.)

**Comment by chimersable** [comment]
I don't know what an anomally core is,  I've never seen one in game, and the two tg wikis don't know either. So basically you are adding a requirement that is admin spawn only.

 And ontop of that the phazon is pretty junky too, armor sucks, it can be hit while phaseing, phaseing through much more than six objects leaves the battery nearly drained, it has a low amount of hit points, and micro tool array seems broken

 If you really don't want them built than have some balls an suggest removing them from the fabricator recipe, don't snipe at it by adding unattainable parts  trying to sneak a controversial removal through github.

**Comment by Xhuis** [comment]
@chimersable I don't want them _never_ to be built. Phazons are ridiculously powerful, as most people agree, and I want their construction made harder.

You can ask what an anomaly core is on the OOC channels of both servers, or just over radio, and chances are you'll get an answer.

**Comment by Lumipharon** [comment]
You having a laugh Chim?
Phazons are super fast, their microtools very much work, and I can (from repeated experience) walk from R&D to the armory and back, going through walls 50% of the time, without running low on battery.

This is a neat change that makes phazons actually valuable, rather then just mass producable OP shit.

Now you might see the egg heads swarm anomoly cores to try get them.

**Comment by Miauw62** [comment]
please dont respond to the troll.

**Comment by Xhuis** [comment]
¯\_(ツ)_/¯

**Comment by optimumtact** [comment]
:+1: nice, makes them harder to get, but still feasible with a little teamwork

**Comment by Kromgar** [comment]
Perhaps make only certain anomaly cores have use? 

I mean a pyroclastic anomaly core doesn't seem reasonable to use in a phazon

**Comment by Xhuis** [comment]
Anomalies seem to be based off of bluespace, and that's where the phazon taps from

**Comment by Miauw62** [comment]
making it depend on a specific anomaly would be a bit too much of a nerf, imo.

**Comment by Dorsisdwarf** [comment]
Can you re-buff their armor if they're going to become super rare then?
Currently they have the weakest armor of any combat mech except the HONK due to 'balancing' for making them constructable

**Comment by Xhuis** [comment]
I'm probably not going to buff their armor. The Phazon's ability to hold weapons, plus its phasing capabilities, makes any Roboticist with an upgraded welding tool and some power cells the most dangerous thing on the station.

If the majority of people want an armor buff I can see about it.

**Comment by Lumipharon** [comment]
It's already super strong because of it's high speed and phazing - it doesn't need super strong armor as well, otherwise it just becomes EVEN MORE OP and unbalanced.

**Pull request merged**
