### PR TITLE
American touristbots will now order butter on a stick.

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

My good friendmin mrr.fiish was so delighted about me making his favourite country faire staplein game, that I decided to make it fairly commonly ordered by the American Touristbots.

## Why It's Good For The Game

It makes my good friend mrr.fiish happy, and hopefully other Americans too.

## Changelog

:cl:
balance: Mmmh, butter on a stick. Now for americanbots.
/:cl:

### CODE REVIEW

**Review by Time-Green — APPROVED** [review]

**Comment by carshalash** [comment]
image
Artist depiction of tourist bots ordering their new option.

**Comment by the-orange-cow** [comment]
https://m.youtube.com/watch?v=avAglwPbDnQ&pp=ygUMQnV0dGVyYnVyZ2Vy

**Comment by Jolly-66** [comment]
Truly an all American meal

**Comment by necromanceranne** [comment]
Everyone knows the game is better and more realistic because of this change.

**Pull request merged**
