### PR TITLE
Adds two new Integrated Circuit components: hsv2hex converter and rgb2hex converter.

### PR DESCRIPTION
**Pull request by KomradeSpectre**
[Changelogs]:
:cl: TheMythicGhost
:add: New Integrated Circuit Converter Components: hsv2hex and rgb2hex for smooth color transitions, woo!
:imageadd: Added icons for the new component chips.
/:cl:

[why]: Since the only way colors are handled now in Integrated Circuitry is Hexcode colors, it's not really a possibility to make smooth color shifts with them without having massive chains of arithmetic chips that hog the complexity. This adds two ways of going about smooth color shifts, for things like Health Indicating Flashlights and whatnot.

### CODE REVIEW

**Comment by ACCount12** [comment]
New icons look bad, and I'm not a fan of every single component having its own icon. Other than that - I approve.

**Comment by DaedalusGame** [comment]
pretty sure all the icons in electronic components are subject to change anyway no point in flooding this pr with a complete resprite

**Comment by ACCount12** [comment]
I'm trying to resprite the worst of them, and this PR adds to that problem.

**Comment by KomradeSpectre** [comment]
Well, since your new sprites aren't in yet, think of the ones I added there as placeholder. Also, I only added them because the other converters had sprites similar to it, so I followed the schema.

**Comment by duncathan** [comment]
There should be some mention of valid input ranges

**Comment by GunHog** [comment]
Yay! My Medibots will have <s>Razer Chroma</s> RGB support!

**Comment by KomradeSpectre** [comment]
@duncathan Say no mo fam, I gotchu.

**Comment by JStheguy** [comment]
Does this mean we can finally have gaming cups(tm)?
image

**Comment by Kerbin-Fiber** [comment]
Time to add a nice light show to my Beep Bots™

**Comment by KomradeSpectre** [comment]
Does this need additional reviewing, or is it good to go? Just thought I'd ask since it's been sitting for about a week.

**Pull request merged**
