### PR TITLE
More Map Cleanup

### PR DESCRIPTION
**Pull request by ShizCalev**
Accidentally swapped the solar areas with #27530

Renamed some maintenance tunnels since we have more paths now.

Added new icons for updated area paths.

### CODE REVIEW

**Comment by Metacide** [comment]
There are more maintenance areas?

I'll take a look at fixing a few on Meta soonish too if that's the case.

**Comment by ShizCalev** [comment]
@Metacide I got them all with this PR.

**Comment by ShizCalev** [comment]
@Metacide You're more than welcome to push commits to the branch for the time being if you want to break them down further.

**Comment by Metacide** [comment]
You hero, many thanks.

**Pull request merged**
