### PR TITLE
Printing mops.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Makes mops printable.

## Why It's Bad For The Game

Excuse me, you can't just print out more mops. A mere autolathe could not even begin to understand the advanced science underpinning the mopping marvel you see before you. These super mops utilize GPS positioning to accurately and intelligently wipe away stains with surgical precision. They also incorporate the latest in synergistic machine learning to identify messes from stains to save you time and money. The smart hydration technology found in these sublime mopping units conserves water, minimizing time wasted on wringing, yet at the same time holds huge volumes of water. The ergonomically designed handle doubles as a self-defense tool, because it's a dangerous station out there and Nanotrasen has your back. Even the top of the mop was painstakingly crafted to be compatible with janicarts. Do you have any idea how difficult that was? People have lost there lives in pursuit of better mopping and yet you seem blissfully unaware of the sacrifices required. Frankly you should be thankful to even get these miracles of modern science at all, and now you want a lowly autolathe to print out more of them by claiming they are "just mops"? How dare you. I demand you apologize. Not to me, not to Nanotrasen, not even to the engineers and scientists who spent countless thankless hours developing the latest in mopping technology. No, you must apologize to the mop itself. Once you admit that this mop is a crowning achievement of humanity, truly the pinnacle of all that we are and ever will be, then you will be forgiven and allowed to gaze upon this mop, much less hold or even use one ever again. Repent, sinner.

## Changelog
:cl:
add: Mops can now be printed at the autolathe and protolathe.
/:cl:

### CODE REVIEW

**Review by 81Denton — APPROVED** [review]
while you were out partying, I studied the mop

**Comment by imsxz** [comment]
mops remove cult runes FYI i can think of a few people that grab them for that purpose

**Comment by py01** [comment]
This makes it possible to mass produce rune deleters (also deletes active barrier runes).

**Comment by nemvar** [comment]
Advanced mops already exist. I think cult will survive this 'nerf'

**Comment by anconfuzedrock** [comment]
granny rune deleters spawn in the shower 2 spawn in medbay on most maps
If you're concerned with this pr  because it might be an extremely slight nerf to cult then I'm concerned for your health

**Comment by Krysonism** [comment]
Janitor nerf, 

Limit it to the service lathe so janni can feel important.

**Comment by Angustmeta** [comment]
I can find mop in the service techfab but not not in the autolathe.

**Pull request merged**
