### PR TITLE
The Hulk Buff

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

hulks no longer get slowdown from damage/stamina

## Why It's Good For The Game

crippling a hulk is too easy, you can just use stamina damage, hulk was meant to be taken lethally but now with baton changes to do stamina, combined with disablers doing stamina you can easily dab on one
also makes a sense that a raging monster on steroids wouldnt care about damage until it actually made him go into a critical state
ᴡᴇ ʟɪᴋᴇ ʜᴜʟᴋ ᴡᴇ ʟɪᴋᴇ ʜᴜʟᴋ

## Changelog
:cl:
balance: hulks no longer slow from damage
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
Why It's Good For The Game?

**Comment by Fikou** [comment]
> Why It's Good For The Game?

its good for the game by making the work put into getting hulk which is two mutations useful, instead of getting countered by the two tools that every sec officer has, also makes hulks more valid since now you really have to use lethals

**Comment by 81Denton** [comment]
Weren't disablers always able to take down hulks or am I remembering this wrong

**Comment by wesoda25** [comment]
Make disablers do half as much stamina damage to them but keep the slowdown

**Comment by carlarctg** [comment]
that ruins the entire point of the pr

**Comment by Fikou** [comment]
> Weren't disablers always able to take down hulks or am I remembering this wrong

they were but nobody ever used disablers or stamina damage before taser removal

**Comment by wesoda25** [comment]
> > Weren't disablers always able to take down hulks or am I remembering this wrong
> 
> they were but nobody ever used disablers or stamina damage before taser removal

wrong

**Comment by Shadowflame909** [comment]
Right

**Comment by zxaber** [comment]
Hulks are bullshit. Every round they get handed out like candy, you end up with assholes smashing up all the walls in the station because "lol whacha gonna do about it".

Before we buff them, we should nerf their ability to flatten departments.

**Comment by wesoda25** [comment]
Speaking of hulk nerfs, make them rip their clothes. It makes perfect sense too. At least give them legs like digitrade ones so that they have a clear weakness.

**Comment by ATH1909** [comment]
I'd like to point out that, IIRC, hulks are currently immune to staminacrit.

Basically, this PR would make them immune to most of the effects of stamina (bar arm disabling, I think)... which I think I'm okay with. 👍 from me.

**Comment by Shadowflame909** [comment]
Their weakness is death

Hulk doesnt need a nerf. It needs an overhaul because genetics holy grail is weaker then minings mass dispensable Sonic Jackhammer

**Comment by Fikou** [comment]
> I'd like to point out that, IIRC, hulks are currently immune to staminacrit.

stun immunity is staminacrit immunity, but it still immobilizes them

**Comment by WaterStBlues** [comment]
The genetics system is the problem here. Hulks were fine (and super fucking funny) when they were easier to get and could be handed out once every 90 seconds

**Comment by carshalash** [comment]
> The genetics system is the problem here. Hulks were fine (and super fucking funny) when they were easier to get and could be handed out once every 90 seconds

You mean you don't like 20 random fluff genes that do nothing?

**Pull request merged**
