### PR TITLE
[s] Revert "Revert "Improves bee lore""

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#29972

the revert was merged before 24 hours, big no no

### CODE REVIEW

**Comment by evsey9** [comment]
Yes

**Comment by RemieRichards** [comment]
Nope, I don't consider the first PR to have been merged at all, and thus the revert doesn't exist either.
None of it ever happened.

**Comment by Armhulen** [comment]
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooh boy

**Comment by Armhulen** [comment]
lets go oranges lets go

**Comment by Anonmare** [comment]
One, two, three four. I declare a merge war

**Comment by Firecage** [comment]
No no, this is clearly a maintainer war.

**Comment by Anonmare** [comment]
H-He's fast!

**Comment by Armhulen** [comment]
this is to reopen even further beyond!

**Comment by Anonmare** [comment]
Hey buddy I think you got the wrong PR. The maintainer club is a few blocks down

**Comment by Armhulen** [comment]
he went for the mind game play

**Comment by Jordie0608** [comment]
Stop it you nerds
> <TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact closed pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975
<TheGhostOfWhibyl1> [tgstation] optimumtact reopened pull request #29975: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29975

**Comment by optimumtact** [comment]
sorry about that, I can't beelieve it sent all those messages

**Comment by MrPerson** [comment]
Between the first closing and the last one was 10 minutes. How does it feel to know you can never get those ten minutes back, ever?

**Comment by Jordie0608** [comment]
You didn't see it buzzing away the whole time?

**Comment by MrStonedOne** [comment]
And you thought I was bad.

**Comment by Armhulen** [comment]
that means this will be merged right

**Comment by Armhulen** [comment]
_speeeeeeeedmerged?_

**Comment by optimumtact** [comment]
superceded by #29976

**Pull request closed without merging**
