### PR TITLE
Makes cyborg endoskeleton a roundstart research again

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

Cyborg endoskeletons no longer require a research node to be made, making them possible to create at roundstart.
## Why It's Good For The Game

I feel like placing these behind a node doesn't really do anything that's worth having it there. There's very little to do at roundstart other than making cyborgs or clean/medibots at roundstart, so most of the beginning of a shift turns into "trying to get R&D to research the thing you need to do arguably the most important part of your job". I haven't been able to find a single benefit for doing this. Arguably, it's like this to prevent people from "wasting resources on cyborgs that never get built", but I can't say I've ever been on a round with more than 30-40 people where I didn't build at least two borgs.

What actually ends up happening is one roboticist makes everything but the endoskeleton while the other tries to get access to the R&D computer to research cybernetics so they can finish making a cyborg. It was also argued that augmentation is more often requested at roundstart than borging, which I have seen maybe twice in the last three years.
## Changelog
:cl: Vekter
balance: Removes the research requirement from cyborg endoskeletons, meaning they can be built at roundstart again.
/:cl:

### CODE REVIEW

**Comment by loganuk** [comment]
I now understand why we see less AI shells and cyborgs and why people focus the research points on mechs instead.

**Comment by TheVekter** [comment]
> I now understand why we see less AI shells and cyborgs and why people focus the research points on mechs instead.

I don't necessarily think this is contributing to that; we're seeing fewer cyborgs because of the extra roundstart slot and fewer AIs because the rules make it kind of contentious to build a second AI in most cases (primary station AI can just kill other AIs for free if they think they're a threat).

**Comment by zxaber** [comment]
>...the other tries to get access to the R&D computer...

This doesn't detract from the fact that I do agree with this PR, but for the record, you can just download the R&D app on either your PDA or the robo modular console.

**Comment by btcbuster** [comment]
> > ...the other tries to get access to the R&D computer...
> 
> This doesn't detract from the fact that I do agree with this PR, but for the record, you can just download the R&D app on either your PDA or the robo modular console.

They could be a downstream with heavier restriction to researching

**Comment by TheVekter** [comment]
> > > ...the other tries to get access to the R&D computer...
> > 
> > 
> > This doesn't detract from the fact that I do agree with this PR, but for the record, you can just download the R&D app on either your PDA or the robo modular console.
> 
> They could be a downstream with heavier restriction to researching

No, zxaber is right as far as /tg/ goes (which is where I play) but I still don't think that's a concern in this case.

**Comment by loganuk** [comment]
> > I now understand why we see less AI shells and cyborgs and why people focus the research points on mechs instead.
> 
> I don't necessarily think this is contributing to that; we're seeing fewer cyborgs because of the extra roundstart slot and fewer AIs because the rules make it kind of contentious to build a second AI in most cases (primary station AI can just kill other AIs for free if they think they're a threat).

As an AI player I noticed a lot less AI shells and borgs were being built especially at shift start when it would be most useful but its only anecdotal thoughts.

**Comment by Isratosh** [comment]
The play time requirement for roundstart cyborgs on /tg/ is quite long. When I played more regularly, roundstart was my busiest time as a roboticist as several people usually requested to be borged immediately. Good PR.

**Pull request merged**
