### PR TITLE
Flashbangs no longer pierce ear protection on adjacent tiles.

### PR DESCRIPTION
**Pull request by EnterTheJake**
## About The Pull Request

A Security Flashbang will no longer pierce ear protection on adjacent tiles, only the one where it detonates.

## Why It's Good For The Game

Flashbang grenades are one of the best tools in Security arsenal. they are available roundstart,widely abundant, and part of the reason why they are so strong is how rare ear protection tends to be.

But what tilts the scale from strong to just unfair in my opinion, is the combination of instant detonation and being able to pierce ear protection entirely on adjacent tiles.

This is an hardcoded stun by the way, You could literally have no eyes nor ears and it won't make a difference.

I Recently had a talk with the guy who pushed this change https://github.com/tgstation/tgstation/pull/2970 (10 years ago oooooof) and they also agree this should change.

Flashbangs protection piercing was introduced to avoid officers using them as instant hardstuns instead of....you know...grenades.

Since this is likely going to be a controversial change, and i can already predict what some of counterpoints are going to be, let me address em here.

**Wait, instabangs stun the detonating officer for longer than the adjacent victim**

Security is a department, a confirmed antag is rarely gonna be pursued by a single officer, valid hunters not withstanding, all you need is for somebody else to be there to capitalize on the stun to effectively disarm your opponent or kill them.

**It's actually very hard to catch someone with an instabang, it's high-skill high reward hence good for the game**

Not really? We have a lot of antagonists that rely on melee combat, Heretics,Lings,Desworder tots and Nukies, Cult and so on.

Quick equipping and detonating a flashbang can be done in less than half a second,  is essentially impossible to react, and again nothing short of complete stun immunity will prevent it.

Something taking "skill" shouldn't be an excuse for it being unfair, unintuitive jank garbage and have little to none interactions with the sandbox.

## Changelog

:cl:

balance: Flashbangs detonation no longer void ear protection on the adjacent tiles

/:cl:

### CODE REVIEW

**Comment by SkeletalElite** [comment]
The purpose of adjacency flashbang stuns is to prevent sec offs from dragging a primed flashbang so you can't avoid it

**Comment by EnterTheJake** [comment]
> The purpose of adjacency flashbang stuns is to prevent sec offs from dragging a primed flashbang so you can't avoid it

That's not changing, i'm only removing the stun on adjacent tiles, self detonating a bang will still floor you.

**Comment by SkeletalElite** [comment]
> > The purpose of adjacency flashbang stuns is to prevent sec offs from dragging a primed flashbang so you can't avoid it
> 
> That's not changing, i'm only removing the stun on adjacent tiles, self detonating a bang will still floor you.

does that include if you drop the flashbang and drag it one tile behind you, thus having the grenade not be on the same tile as you.

**Comment by EnterTheJake** [comment]
> > > The purpose of adjacency flashbang stuns is to prevent sec offs from dragging a primed flashbang so you can't avoid it
> > 
> > 
> > That's not changing, i'm only removing the stun on adjacent tiles, self detonating a bang will still floor you.
> 
> does that include if you drop the flashbang and drag it one tile behind you, thus having the grenade not be on the same tile as you.

Honestly I didn't think of that, but again If a seccie manages to prime a flashbang, and managed to get you to stand on it, 
 it's probably warranted.

**Comment by Deadgebert** [comment]
lmao
stop buffing antags. you have so much at your disposal.
this is a horrible, horrible change

**Comment by Formerxboxgamer** [comment]
stunning both yourself and your opponent is a fight reset, its often a last ditch attempt used by a security officer to put both themselves and a heavily armed/armored attacker on the floor. Removing crew tools to deal with people is removing options from the sandbox.

**Comment by JupiterJaeden** [comment]
Foolish coders attempt to nerf flashbangs, unaware of the new glorious era of dragging primed flashbangs they will usher in.

Seriously though I already expressed all the reasons I thought this was a bad change to you on discord. This disarm strategy can be viable but it’s far from a reliable catch-all.

**Comment by EnterTheJake** [comment]
> stunning both yourself and your opponent is a fight reset, its often a last ditch attempt used by a security officer to put both themselves and a heavily armed/armored attacker on the floor. Removing crew tools to deal with people is removing options from the sandbox.
> 
> Editing in here that you have decided to PR this after watching a nukie with an elite suit, energy shield, and ninja katana be disarmed by an insta-bang flash. Without this option, what is the solution there? A bomb?

I already addressed in my WIGFG that's not a valid point, security officers usually go in pairs or have someone nearby to capitalize on the insta-stun, all you need is a buddy to be 2 tiles away from the detonation.

More doesn't necessarily equal better for the sandbox, especially when we are talking about an insta easily available stun that void all kind of protection and defies the very purpose of a grenade.

This is a pr i've been considering for a very long time, I don't think instabangs are good for the game, nor understand why they should void ear protection when it's already so scarcely available.

@JupiterJaeden 

I'm actually completely with with it, It requires timing and gives people a chance to react.

**Comment by JupiterJaeden** [comment]
> I'm actually completely fine with that strategy, It requires timing and gives people a chance to react.

Average fleeing criminal attempting to react as I tail him at 2 tiles with my stone cold stare, watching him flounder helplessly as my pre-armed flashbang ticks behind me

lol jokes aside, I don’t think you’re argument that something is OP holds up very well if you’re essentially agreeing it has to have 2 people to actually be reliably good. 

Normally I wouldn’t really care about stuff like this but I don’t think taking one of security’s last couple reliable (at least mechanically, not always in practice) disarms is a good thing. Ridiculously stacked block chance gear is stupid and there should be counterplay. The only other mechanically reliable disarm sec can practically access is a body throw and even that can get cucked by block chances now.

On the target’s side, you get stunned for like a half second before you can pick your gear back up (or draw other gear) and continue fighting, against an assailant who will be on the floor much longer than you. I’d suggest just removing the short hardstun if that really irks you, but I definitely believe the knockdown should stay.

**Comment by EnterTheJake** [comment]
@JupiterJaeden It holds up because SS13 is not a competitive pvp game, it's a multiplayer immersive sim with a focus on sandbox and roleplay.

Antagonists are by design outnumbered , and they have an entire department, (or, in the case of nukies, the entire station) to stop them.

The stun is 2 seconds, which is plenty of time for someone to walk in and sneak a baton hit or yoink your opponent weapon away.

Also no? baton knockdown is now a guaranteed disarm, that's literally strapped to the most common tool a seccie has.

You do not find me in disagreement that endlessly stacking block chance is stupid and probably needs to go, but that's out of the scope of this pr.

**Comment by optimumtact** [comment]
This exists for very specific reasons all of which you seem to have just ignored, closing at the 24 hour mark.

**Comment by EnterTheJake** [comment]
@optimumtact enlighten me, I did talk to the guy who originally pushed this change, protection being pierced on the officer makes sense, as it avoids spamming instabangs with no consequence.

What purpose does penetrating adjacent tiles serve?

**Comment by ExcessiveUseOfCobblestone** [comment]
> I already addressed in my WIGFG that's not a valid point, security officers usually go in pairs or have someone nearby to capitalize on the insta-stun, all you need is a buddy to be 2 tiles away from the detonation.

You havent really explained why both of them being completely mobile instead is better though. 

I was thinking the use of prime n pull (hence the comment) is a much more likely scenario than an antag getting hit by an adjacent flashbang, it going off immediately, and them having flashbang proof gear to pierce thru it to begin with. The change is much more likely to help security pull off cringe maneuvers where now they dont even need a partner.

**Comment by EnterTheJake** [comment]
@ExcessiveUseOfCobblestone 

Because you need to preprime the grenade then drag it, at the very least you can see it coming.

If it's such a big deal i can make it so the self detonate stun also applies on a drag.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Because you need to preprime the grenade then drag it, at the very least you can see it coming.

Is prepriming the grenade, pressing the drop key, and ctrl+clicking it and following the bad guy with two hands available harder than predicting where the bad guy is going to go, priming the nade (audio cue for bad guy to know to gtfo), and throwing it at the exact second it's going to go off else immobilizing you?

The drag change could be worth a conversation though, I dont think the change was meant to btfo the people on the receiving end but rather the people throwing it (or rather not throwing it and cheesing people who dont have flash protection).

**Comment by EnterTheJake** [comment]
> > Because you need to preprime the grenade then drag it, at the very least you can see it coming.
> 
> Is prepriming the grenade, pressing the drop key, and ctrl+clicking it and following the bad guy with two hands available harder than predicting where the bad guy is going to go, priming the nade (audio cue for bad guy to know to gtfo), and throwing it at the exact second it's going to go off else immobilizing you?
> 
> The drag change could be worth a conversation though, I dont think the change was meant to btfo the people on the receiving end but rather the people throwing it (or rather not throwing it and cheesing people who dont have flash protection).

It doesnt require priming that's the thing, flashbang grenades can be screwdrivered to detonate instantly as soon as you press the button.

It has literally no cue or hint for people to react, so yeah it's a lot less fair in that regard.

**Comment by Ergovisavi** [comment]
Jesus, first time I've commented on github in forever. When I originally made flashbangs pierce protection ten gorillian years ago we had an issue with security officers just priming flashbangs on their person and running at antags to instantly gearcheck people and win a fight. Keep in mind this was also in an era of tasers and combat was even more absurd than it currently is.

What the radius did that whomever added later did was fix one problem (dragging) and introduce another problem (instabanging). Yes, the tactic is obviously not without risk, but given Security generally has a numbers advantage outside of extreme lowpop, the risk is significantly mitigated. Security should always be traveling in numbers anyway when possible because of basic math.

More important than the question of muh balance, it's a question of: Is this interaction fun? I don't think it is. I don't think instabangs fucking people over is an entertaining mechanic.

To those saying "What about high blockchance antags?", let's actually look into that - Sources of blockchance are shields (50%) and things like Deswords (75%), and for the I've never fucking seen someone actually buy it the energy shield which always reflects energy projectiles. Given that security ALSO has access to shields for 50% we're basically only looking at the Desword and Eshield (There's one guy who's going to akshually me about the Adamantium Shield but it's a meme, come on). I suppose there's also the rare occasion that some dude goes into the armory and steals a shield while also having a standard Energy Sword.

So what are the solutions to high blockchance? Bodythrows, Tackles (Yes they work, albeit you need at minimum Gorilla gloves + Riot Suit, ideally you're also a moth), Space Lube / Cooking Oil (No, noslips do not protect against this, I cuck idiot nukies all the time with it), Shock Touch (Forced disarm, unblockable unless you're insulated), Temperature Gun / Cryokinesis (Ice to meet you), You can also beartrap/dragnet most people trying this because they never have a freedom implant, and if they don't have fire protection you could also molly them I suppose, they'll have to drop some amount of protection to extinguish themselves.

But wait, you say, what about the War Ops nukie in an Elite Suit with an Energy Shield and a Desword? Energy shields must be popped for Tackles and the Temperature gun to work (Tackling and bodythrows should really be made consistent), Fire is off the table due to the suit, and even things like the dragnet / beartraps / lube are also potentially off the table if they take a moment and sabotage the gravity generator, leaving you with pretty limited options outside of the tried and true bodythrow.

And so the question basically boils down to: Is the single real use case of using it against the super nukie (And occasional DS, I guess) worth having the instabang gearcheck in the game? I think not. We're losing more than we're gaining. I think people using flashbangs as actual, you know, grenades and cooking them to hit someone to pierce their protection is entirely fine, it's the low effort I run at you, you lose interaction that's shit.

I think the likely best solution is in two parts, 1) If there's a mob on the tile with the flashbang, do not AoE pierce and 2) Do not allow armed grenades to be dragged. Everybody wins.

**Comment by Xackii** [comment]
>So what are the solutions to high blockchance? Bodythrows
>
Bodythrows is also blockable now 🥹

**Comment by Ergovisavi** [comment]
> > So what are the solutions to high blockchance? Bodythrows
> 
> Bodythrows is also blockable now 🥹

At a severe penalty for energy swords (25% chance, even for the dualsaber). Standard shields are more effective at it, but security has those too, so again, moot point.

**Comment by Metekillot** [comment]
I think it should.blow your fingers off if a flashbang goes off in your hand.

**Comment by SimplySmiley123** [comment]
> So what are the solutions to high blockchance? Bodythrows, Tackles (Yes they work, albeit you need at minimum Gorilla gloves + Riot Suit, ideally you're also a moth), Space Lube / Cooking Oil (No, noslips do not protect against this, I cuck idiot nukies all the time with it), Shock Touch (Forced disarm, unblockable unless you're insulated), Temperature Gun / Cryokinesis (Ice to meet you), You can also beartrap/dragnet most people trying this because they never have a freedom implant, and if they don't have fire protection you could also molly them I suppose, they'll have to drop some amount of protection to extinguish themselves.
> 
> But wait, you say, what about the War Ops nukie in an Elite Suit with an Energy Shield and a Desword? Energy shields must be popped for Tackles and the Temperature gun to work (Tackling and bodythrows should really be made consistent), Fire is off the table due to the suit, and even things like the dragnet / beartraps / lube are also potentially off the table if they take a moment and sabotage the gravity generator, leaving you with pretty limited options outside of the tried and true bodythrow.
> 
> And so the question basically boils down to: Is the single real use case of using it against the super nukie (And occasional DS, I guess) worth having the instabang gearcheck in the game? I think not. We're losing more than we're gaining. I think people using flashbangs as actual, you know, grenades and cooking them to hit someone to pierce their protection is entirely fine, it's the low effort I run at you, you lose interaction that's shit.
> 
> I think the likely best solution is in two parts, 1) If there's a mob on the tile with the flashbang, do not AoE pierce and 2) Do not allow armed grenades to be dragged. Everybody wins.

The ideal situation for dealing with block chance heavy traitors, nukies and cultists, without also having a bomb, are slim as fuck now.
Bodythrows *can* be blocked now, tackling can be ignored unless you tackle-max to hell and back yourself, fighting normally is out of the question you're gonna get fucked sideways unles you also maxed out your block chance.
Flashbangs and bombs are the only reliable methods of dealing with bloch chance maxxing players. And one of these often ends up with a hull breach.

**Comment by Dorsisdwarf** [comment]
Why don't we just fix "people are screwdrivering their own grenades to go off instantly and using it as an unstoppable un-preductable stun pulse" by... removing that interaction? Make the interaction "flashbang goes off after a random period" like ieds.

**Comment by EnterTheJake** [comment]
> Why don't we just fix "people are screwdrivering their own grenades to go off instantly and using it as an unstoppable un-predictable stun pulse" by... removing that interaction? Make the interaction "flashbang goes off after a random period" like ieds.

Might be a better solution.

**Comment by EnterTheJake** [comment]
Alright, it seems this is not the way to do it. I'll consider a different approach.

**Comment by TheVekter** [comment]
> Why don't we just fix "people are screwdrivering their own grenades to go off instantly and using it as an unstoppable un-predictable stun pulse" by... removing that interaction? Make the interaction "flashbang goes off after a random period" like ieds.

I like the screwdriver option because it lets you do funny things with different triggering methods, but maybe we make it so you can't do it to the prefab flashbangs you get out of a vending machine?

**Pull request closed without merging**
