### PR TITLE
Quantises liver purging

### PR DESCRIPTION
**Pull request by 4dplanner**
## About The Pull Request

rounds chems before deciding whether liver purges them

## Why It's Good For The Game
floating point bad

## Changelog
:cl:
fix: liver purging is more consistent
fix: chemical recipes are more consistent
tweak: chemical scans only show to 2 d.p
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Could use this in a couple of places with chemistry. I've had chem recipes fail to react despite seemingly being correct due to floating point

**Comment by MrPerson** [comment]
Why not have get_reagent_amount() return a rounded result itself rather than expect every caller to do it?

**Comment by ExcessiveUseOfCobblestone** [comment]
> Why not have get_reagent_amount() return a rounded result itself rather than expect every caller to do it?

🤔 

where is the fun in that?

**Comment by 4dplanner** [comment]
> Why not have get_reagent_amount() return a rounded result itself rather than expect every caller to do it?

probably a good idea tbh, will look into it soonish

**Comment by MrPerson** [comment]
For the record I understand that's a non-trivial request and greatly appreciate the effort it will take if you decide to do it

**Comment by 4dplanner** [comment]
This should now cover chemical recipe issues as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
is this ready

**Comment by 4dplanner** [comment]
As far as I remember, yeah

**Comment by 4dplanner** [comment]
Realised that I should have tweaked health scanners and future-proofed the quantisation, put the tweaks in https://github.com/tgstation/tgstation/pull/43135

**Pull request merged**
