### PR TITLE
Editing machinery's rating has a cancel button and a rights check

### PR DESCRIPTION
**Pull request by lzimann**
Not being able to cancel this when you click on accident is annoying.

### CODE REVIEW

**Comment by Jordie0608** [comment]
I feel this proc could just be removed; it's not difficult to replicate with varedit + atom proc call and it'd be one less button on every right click.

I can't imagine it's used much.

**Comment by RandomMarine** [comment]
I use it all the time for testing @Jordie0608

**Comment by lzimann** [comment]
it is useful for testing some machinery related stuff sometimes

**Comment by Iamgoofball** [comment]
@Jordie0608 It is definitely a bigger pain in the ass to manually var edit everything and force a refresh.

Dropdown menu works though.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Replace this proc with a VV dropdown

**Comment by lzimann** [comment]
i'm not changing in this pr(web editor and all of that), so either close or merge it

**Comment by Cyberboss** [comment]
:/

**Pull request closed without merging**
