### PR TITLE
Swappable energy gun cells

### PR DESCRIPTION
**Pull request by Deadgebert**
## About The Pull Request

Adds new gun cells that can be used for energy weapons.
Existing energy weapons have had their energy cells replaced with this new gun cell and only gun cells can be inserted into energy weapons.
Cells can be removed from most energy weapons.
Gun cells can only be printed at security lathe or scavenged from existing energy weapons.
Adds gun cell design to basic security research
Specialty weapons such as cyborg/captain/HoS/pulse/plasma/retro remain unchanged
Made a very slight adjustment some default energy weapon sprites so I can use that state to show that a gun has no power cell

https://github.com/tgstation/tgstation/assets/109347230/b4f31631-0eb8-4c0c-a7d7-e3aad121f5bb

Thank you so much to @coiledlamb for providing the sprites used.

## Why It's Good For The Game
Making your way back to a recharger to recharge your laser carbine really sucks. You could carry a wrench around and drag the weapon rechargers with you everywhere you go, but that's also very lame! Reloading is far more fun and engaging as a mechanic. I've done my best to adjust the timer on swapping a cell so that it doesn't make energy weapons much more powerful. The swap takes a total of 8 seconds so there is no way you're going to be doing it in the middle of a fire fight. Blob fights don't get significantly easier either, as the time it takes to swap a cell is about the same as plopping it into an upgraded weapon recharger. Shot balance, charge times, damage all remain completely unchanged.

## Changelog
:cl Redbert:
add: New gun cells for energy weapons
balance: Gun cells can now be swapped out of certain energy weapons using right-click with a screwdriver
/:cl:

### CODE REVIEW

**Comment by DaydreamIQ** [comment]
Normally using a screwdriver on the gun removes the firing pin, does this just override that? If so that could be a bit confusing

**Comment by Deadgebert** [comment]
> Normally using a screwdriver on the gun removes the firing pin, does this just override that? If so that could be a bit confusing

firing pin is left click, cell is right click.

**Comment by DaydreamIQ** [comment]
Does that appear on examine?

**Comment by Deadgebert** [comment]
> Does that appear on examine?
it shows whether or not it has a cell, but not instructions. I can include them though, thank you for the suggestion

**Comment by Jacquerel** [comment]
Lack of field reloading is largely speaking intended as the behaviour for crew ranged weaponry, as such this is quite unlikely to meet approval.

**Comment by Deadgebert** [comment]
> Lack of field reloading is largely speaking intended as the behaviour for crew ranged weaponry, as such this is quite unlikely to meet approval.

I understand this and I hoped some tweaking of the cell swapping values could make it a bit more acceptable. Right now the meta is drag an upgraded recharger around. I could argue in its current state, an upgraded recharger is still stronger than this change.

**Comment by Fikou** [comment]
nah

**Comment by Yobrocharlie** [comment]
PR doomed from the start,

**Pull request closed without merging**
