### PR TITLE
partial revert of #20057

### PR DESCRIPTION
**Pull request by PKPenguin321**
this "minor change" pushed deathsquad from being "op but fun to fight" to "op and not fun to fight"

### CODE REVIEW

**Comment by kevinz000** [comment]
Didn't I try to do this and got told to fuck off? GL man. But yeah fuck Kilkun atleast goofball's things can be abused by everyone, not just 5 lucky people per button.

**Comment by optimumtact** [comment]
This is the death squad, it's an ic way to end the round.

It's not meant to be balanced or fun to fight against, you're just meant to die so the admins can wrap up their day and go to the admin bar to circlejerk.

**Comment by PKPenguin321** [comment]
We need an event version of the death squad then since we used this in an event just today and it kinda blew

**Comment by optimumtact** [comment]
it's called ERT you dip

**Comment by KorPhaeron** [comment]
Admins should just set off the nuke then instead of letting people who died earlier run around playing god for ten minutes if they just want an instant round end with no fun for the crew

**Comment by karlnp** [comment]
Yes, they should.

**Comment by PKPenguin321** [comment]
In that case reopen this

**Comment by optimumtact** [comment]
I'm not going to have this argument.

If you want an OP unkillable round ender, use the deathsquad as they are intended.

If you want something that's fun to actually fight, use the ERT.

**Comment by PKPenguin321** [comment]
ERT doesn't have the whole deathsquad feel to it, though.

**Comment by KorPhaeron** [comment]
The ERT isn't supposed to kill people and you're banned for shooting at them though, that causes confusion.

How can you say "as intended" when the deathsquad has varied wildly in power over the years, and the admins are in this PR telling you they can't use it anymore because it stopped being fun

**Pull request closed without merging**
