### PR TITLE
Updates sprites for sunglasses and worn goggles

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

image

Sunglasses have received new sprites. Also updated meson (and meson-adjacent) worn sprites because they got overlooked in the last retexture, making them use the correct color palette and be slightly bulkier

## Why It's Good For The Game

Current sunglasses sprites are quite janky and old, and generally don't look extremely good. Sometimes people even manage to confuse sechuds with cult eyes, somehow.
Mesons and other goggles have been updated for consistency with their item sprites.

## Changelog
:cl:
image: Sunglasses and worn mesons have received a glowup.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
soulless

**Comment by alien3301** [comment]
Looks really weird and out of place to me tbh

**Comment by Loafin34** [comment]
i don't like the security glasses. they're supposed to be like red obsidian, black with a tinge of red, not ORANGE.

**Comment by SmArtKar** [comment]
> i don't like the security glasses. they're supposed to be like red obsidian, black with a tinge of red, not ORANGE.

This is the same color palette used by other security HUDs

**Comment by Loafin34** [comment]
yeah, man, it's a hud hidden BEHIND sunglasses, not sunglasses hidden behind a HUD. they should look foreboding, not like someone used a felt marker on their prescription glasses.

**Comment by Striders13** [comment]
i like it but sechud should be dark

**Comment by kawaiinick** [comment]
old ones at least looked sleek

**Comment by SmArtKar** [comment]
I'll see what I can do with hud palettes

**Comment by Ghostkokos** [comment]
nerds glasses detected 🤓

**Comment by Exester509** [comment]
Beerhuds aren't aviators anymore, which is a straight up downgrade

**Comment by SmArtKar** [comment]
People weren't super happy with the sprites which is fully understandable, I'll make a separate PR later which only updates worn sprites and includes NVGs as turns out they weren't updated either

**Pull request closed without merging**
