### PR TITLE
Mi-go skin that hopefully has nothing to do with copyright and stuff

### PR DESCRIPTION
**Pull request by ghost**
Repukan sat in his longchair by the fire, smoking his pipe. He put his index finger on his chin, and grinned. He then chortled, "Why have an amazing sprite that might be plagiarised, when we can have an amazing sprite that fits the art direction and isn't plagiarised?" He then politely folded his paper and rested it on the arm of his chair, lifted his legs off of the coffee table; and begun to make his way towards @ing armhulen on discord admittedly way too many times about danno's sprite.

also removes blank bodies for the same reason, and i didn't like them anyway so who cares!

### CODE REVIEW

**Comment by deranging** [comment]
dick

**Comment by Armhulen** [comment]
yeah i know, that's why i'm fixing it

**Comment by Repukan** [comment]
Want me to whip out my brain damage rod again?

**Comment by Armhulen** [comment]
i'm sorry, it's a first draft!

**Comment by Supermichael777** [comment]
undocumented change detected, why are you removing blanks?

**Comment by Supermichael777** [comment]
actualy just use the old husk sprites

**Comment by Armhulen** [comment]
i posted that i did.

**Comment by praisenarsie** [comment]
what the fuck is a mi-go

**Comment by Spaceinaba** [comment]
your mom

**Comment by Potato-Masher** [comment]
No really, what the fuck is a mi-go?

**Comment by Potato-Masher** [comment]
I looked the damn thing up just the other day, but found jack shit on it.

**Comment by awesine** [comment]
but the C:DDA sprites are actually much better and actually look like mi-gos

**Comment by Armhulen** [comment]
they don't fit at all with the art style of this game with heavy black bordering

**Comment by Armhulen** [comment]
@ShizCalev why?

**Comment by chaoko99** [comment]
Isn't C:DDA open source anyways?

**Comment by ShizCalev** [comment]
It is open source.

**Comment by ninjanomnom** [comment]
There's no issues with licensing/crediting anymore so the sprite in that sense is fine.

As for a change in how it looks that's up to @WJohn to determine which is better I guess.

**Comment by praisenarsie** [comment]
so this is essentially a reference to some dumb other universe and it's referenced by using our simple_animals (which are dumb too)

then again there are more stupid features

**Comment by WJohn** [comment]
These new sprites look really bad, though with a bit of touching up and some spitshine, I think they could make for some decent monster sprites for other uses (I dunno, giant flying insect monster thingie).

The old ones aren't exactly *good* either, but I think it's safe to wait until some better ones are made.

**Comment by ShizCalev** [comment]
image
the people have spoken.

**Pull request closed without merging**
