### PR TITLE
TGUI-NEXT: THE FINAL RECKONING

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Finishes the final batch of NTOS Interfaces

File Manager:
image
TXT Files and the editor were axed, nobody used them and the way they worked was *terrible*. Doing it properly would be an insane amount of work for something nobody uses. If I ever get around to doing paper tgui-next then readding text files will be pretty trivial from there.

Ai Restorer:
image
Net DOS:
image
Net Monitor:
image
Revelation:
image

NTNet transfer was axed because the way it worked was fucking terrible and the ui was complicated. I might bring it back eventually if I ever do a deep dive on modular computers.

## Why It's Good For The Game

AAAAAAAAAAAAAAAAAAAAA

## Changelog
:cl:
add: tgui-next for NTOS: AI restorer, File Manager, NetDOS, Net Monitor, and Revelation
del: Creation of TXT Files on modular computer has been indefinitely removed 
del: Due to architecture concerns, NTNet Transfer has been indefinitely removed from NTOS hardware.
/:cl:

### CODE REVIEW

**Review by stylemistake — DISMISSED** [review]

**Comment by TheVekter** [comment]
image

**Comment by PKPenguin321** [comment]
>NTNet transfer is gone

Noooo, I liked FTPing restricted programs to my personal laptop when I gained access to the bridge

**Comment by cacogen** [comment]
truly a revelation that those syndicate programs exist

**Comment by Dennok** [comment]
> > NTNet transfer is gone
> 
> Noooo, I liked FTPing restricted programs to my personal laptop when I gained access to the bridge

Now keep data disk, so you can download programs to it.

**Comment by stylemistake** [comment]
Yes, I think file manager will need some love in the future, but I'm not sure if floppy disk I/O it's a pressing issue.

**Comment by Cyberboss** [comment]
REBUILD IT ALREADY DAMN YOU

MY MERGE FINGER HUNGERS

**Pull request merged**
