### PR TITLE
chainsaw is too cumbersome to carry in one hand!

### PR DESCRIPTION
**Pull request by francinum**
To: The chainsaw is too cumbersome to carry in one hand!
Fixes Ergocode.
Chainsaws will retain their name on drop.

### CODE REVIEW

**Comment by GunHog** [comment]
Fix the weird text you get saying you are now carrying it in one had if you placei t on a table.

**Comment by KorPhaeron** [comment]
As long as you're fixing chainsaws can you fix the inhands as well?

**Comment by francinum** [comment]
@KorPhaeron Just correcting the text issues. Someone else has to handle inhands.

**Comment by Dorsisdwarf** [comment]
Should be \the , shouldn't it? 

So that you can call a chainsaw "The Murderfucker" via admagic, and get propa grammas

**Comment by francinum** [comment]
@WJohn How is this balance? This is changing a few text messages.

**Comment by francinum** [comment]
Goddamnit. This will fix Twohanded Required weapons from losing their name on drop.

**Comment by GinjaNinja32** [comment]
Don't need `.name`, just `\The [src]` is enough

**Comment by The-Albinobigfoot** [comment]
https://github.com/Zaers/-tg-station/pull/193/files
Hi /tg/, I have the corrected inhands sprites for the chainsaw. Since the only reason I found those sprites to begin with was due to tkrdg's PR, I thought the least I could do was give you the fixed versions. Cheers.

**Comment by francinum** [comment]
@The-Albinobigfoot I may be wrong, but these appear to be identical.

**Comment by The-Albinobigfoot** [comment]
They are not. Look closely at the item_lefthand files, your chainsaw_on and my chainsaw0. Also, in your item_lefthand file again, when facing north, chainsaw_on moves to the right by one pixel, causing it to shift when turned on.

**Pull request merged**
