### PR TITLE
Gives the curator EVA access

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
tweak: Curators jonesing for space adventures may now find that their ID unlocks the doors to EVA.
/:cl:

For treasure hunting.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by FantasticFwoosh** [comment]
This will just exaggerate greytide, as a assistant level of non-responsibility with auxillary base & EVA access.

- Maintainers need to have a proper chat on the status of curator and how far away from their proposed goals they are when they added it because right now its going nowhere.

**Comment by JStheguy** [comment]
What treasures are there even to hunt?

**Comment by FantasticFwoosh** [comment]
Watch this space, im working on a solution to this PR.

**Comment by 81Denton** [comment]
@deranging That wasn't a headmin but WJohn

Also, the grenade launcher is still in that space ruin. It's just been moved to the syndie shuttle further east where you can't just sneak into a basically unguarded pirate shuttle and grab free loot.

**Comment by Daundra** [comment]
wouldn't it make more sense for a curator to be searching for artifacts on lavaland instead?

just my 2 cents

**Comment by Bawhoppen** [comment]
Why don't we just give the curator their own space suit? Seems much more reasonable.

**Comment by Kagus** [comment]
> Why don't we just give the curator their own space suit? Seems much more reasonable.

With a built-in space fedora.

**Comment by vuonojenmustaturska** [comment]
@Daundra curators already have lavaland access via the aux base

**Comment by FantasticFwoosh** [comment]
@vuonojenmustaturska they have nothing to do with a lack of tools to PVE (obtaining) and the actual lavaland base itself is very resource intensive to build to a nice size. 

Ill raise the stakes to 4 cents all-in to say that Cobby's ground digging datums got removed, but it'd be still feasable to store artifacts seeded underneath lavaland tiles (in the sandy between bit above lava baseturf) on part with the generation tools lavaland already has.

**Comment by subject217** [comment]
this will just make curator into the role people use to rush eva at roundstart except instead of having to hunt down all your armory breaking into gear it's all right there for you in eva and nobody will kick you out

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Is it just me or are `access` and `minimal_access` the wrong way around here? `minimal_access` should have fewer accesses. It seems weird that the Curator should get *extra* access on highpop when everyone else gets reduced access.

**Comment by Cyberboss** [comment]
Just do both, librarian needs shaking up

**Comment by FantasticFwoosh** [comment]
> 
> 
> Just do both, librarian needs shaking up

Sorry, i have it in hand on #40845 for a generalised rework of the curator's access to equipment and reversion to a more librarian orientated sub-standard build.

**Comment by 81Denton** [comment]
@SpaceManiac `access` and `minimal_access` are easy to get mixed up, I think I'll make a PR to rename them later.

**Comment by Farquaar** [comment]
I'm not a fan of this idea. I'm not against allowing curators to leave the library and explore if that's what they find fun, but they don't need more encouragement to abandon the library at round start to go greytiding.

**Pull request closed without merging**
