### PR TITLE
adds new stamps, resprites old ones, various cool stuff

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

the big stamp sprites when they are on paper have been remade by twaticus to be epic and sexy
theres now a mime, syndie, centcom and chaplain stamp
centcom stamp is in centcom official backpacks, chaplain and mime are in theirs
syndie stamp is unused for now
theres now a chaplain bedsheet
cool washing machine recolors that were missing were added
fixes inconsistencies in bedsheet neck sprites
edit: apparently icondiffbot doesnt show pngs so
image

## Why It's Good For The Game

the old stamp sprites use TONS of colors making it very hard to make new ones, and all the head of staff ones look the same, these are simple and very nice
its nice for syndies and centcom to have stamps
people requested me to add a mime stamp so its here
and the chaplain signing papers for his church sounds funny

## Changelog
:cl: Twaticus & Fikou
add: 4 new stamps! centcom, syndicate, mime and chaplain
add: chaplain bedsheet, wash a chaplain stamp with a bedsheet to get it
imageadd: new stamp sprites by Twaticus
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
MIME STAMP

**Comment by Tlaltecuhtli** [comment]
in which alt universe chaplain bedsheet exists?

**Comment by cacogen** [comment]
The sprite isn't shit, which is uncommon for sprites on this repo. Congrats

**Comment by ATH1909** [comment]
> MIME STAMP

Please tell me that the stamp mark made by a mime stamp can be seen if you highlight it, just like invisible mime crayon text can.

**Comment by Twaticus** [comment]
why were the stamps items themselves changed? they looked fine before and now its harder to tell the difference between them at a glance 
dqwdqwd
old on the left, new on the right

**Comment by Fikou** [comment]
> why were the stamps items themselves changed? they looked fine before and now its harder to tell the difference between them at a glance
> dqwdqwd
> old on the left, new on the right

because i wanted to make them colored like the stamps

**Comment by Twaticus** [comment]
but they are colored like the stamps? this is taking the color away and turning them all into the same grey stamp

**Comment by BadSS13Player** [comment]
> because i wanted to make them colored like the stamps

Why not have the handle stamp-colored too? It makes more sense.

**Comment by RaveRadbury** [comment]
> Why not have the handle stamp-colored too? It makes more sense.

Yeah I was hoping for a striped mime stamp.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
