### PR TITLE
Trash bin sprite

### PR DESCRIPTION
**Pull request by MTandi**
image

## About The Pull Request

Resprited trash bin and made it have proper indicator when it map-spawns with contents.

## Why It's Good For The Game

Nice bins.

## Changelog

:cl:
image: new trash bin sprite
fix: trash bin shows correct indicator when spawns non-empty
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the new light looks weird without any contrast to the rest of the bin

**Comment by MTandi** [comment]
> the new light looks weird without any contrast to the rest of the bin

It is supposed to be like magsafe.

image

**Comment by Fikou** [comment]
it can be supposed to look like anything that doesn't change that it looks weird in sprite form

**Review by ShizCalev — APPROVED** [review]

**Comment by MTandi** [comment]
Merge please. @Fikou said that he likes it now.

**Review by Twaticus — APPROVED** [review]

**Comment by Wallemations** [comment]
Twaticus already approved so I'll slap 'em in

**Pull request merged**
