### PR TITLE
Removes Crystal Invasion

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

This is a full revert of the Crystal Invasion event.

## Why It's Good For The Game

ENTER: The most unreasonable, unfair, unfun event to ever grace our server. Nobody likes it. It uses loud and petrifyingly dumb sounds (like the nuke going off, for some reason, which triggers ic in ooc CONSISTENTLY). It's a mob based round ending threat, yet the mobs have no special AI, no telegraphed attacks, nothing. They're basic walk and smack mobs.

I basically implore that this kind of delamination could be cool if done right, but it's done so wrong that It's better off not existing until someone does actually do it justice.

Also don't make them cheese skeletons.

## Changelog
:cl:
del: No more crystal invasion event
/:cl:

### CODE REVIEW

**Comment by theta006** [comment]
a mid pop crew with laser eyes lost to them they are broken

**Comment by Farquaar** [comment]
Did they get changed somehow? Me and the HoS beat a crystal invasion by ourselves once. And I was a clown with stormtrooper aim.

It was a fun time, and I like crystal invasion.

**Comment by Ghilker** [comment]
sad, i had it in the list for a rework, but don't have time for it right now... oh well i'll redo it in a better way

**Review by Twaticus — APPROVED** [review]

**Comment by Twaticus** [comment]
cheese skele

**Comment by wraith-54321** [comment]
I feel like if someone is maybe gonna do a rework at some point it may be better to just archive it instead of a full removal

**Comment by ArcaneMusic** [comment]
> 
> 
> I feel like if someone is maybe gonna do a rework at some point it may be better to just archive it instead of a full removal

Well, that's the thing right, the nature of github and PRs consisting of commits means that all of it's archived here on the site, so if anyone ever wanted to revisit it, it's all here.

**Comment by interestingusernam3** [comment]
cheese skele

**Comment by optimumtact** [comment]
as predicted

**Comment by Jhyrachy** [comment]
I'm a sucker for PvE, so I find it really funny.

But I get it could be made better, like making the skeletons really game ending (On tramstation we could indefinitely cheese them to fall to the lower level) and not just a minor annoyance to survive until shuttle is there

**Pull request merged**
