### PR TITLE
Matter bin description grammar fix

### PR DESCRIPTION
**Pull request by arty23**
made matter bin descriptions more grammatically correct, applies to all research levels

### CODE REVIEW

**Comment by WJohn** [comment]
Please put Fixes #14231 
Wait why'd you close it? And your other PR?

Also, why would you open four separate issue reports for minor grammar? Why open four separate PRs to fix those? Just bunch them up so you don't clog things up

**Comment by arty23** [comment]
woops, sorry. first time actually trying to work on these issues. i'll make sure to take all this to heart from now on. reopening now

**Comment by WJohn** [comment]
I mean you're able to make changes to your PR right now, you can commit and push more changes so as to fix the other issues you reported.

**Comment by swankcookie** [comment]
What troglodyte originally wrote these?

**Pull request merged**
