### PR TITLE
[MAP] Robotics Remap: V2

### PR DESCRIPTION
**Pull request by Steelpoint**
For reference: https://github.com/tgstation/-tg-station/pull/6243

This is the second, updated, attempt at a Robotics revamp. It turns out quite a few people still want me to go ahead with this and I decided to finish it.

Here is the design as it stands, taking into account all feedback given from the last PR.

There are still two Roboticist spawns to account for the two round start Robos, since the current map does not have two spawns.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Can we have a window into the sci corridor at the left end of the surgery bay? For purposes of secrecy, nobody but geneticists or people hiding things in the server room goes down there, and it allays the cramped feeling from it being 2 tiles wide.

**Comment by Incoming5643** [comment]
did you forget to put in the cameras or are they just not in the image?

**Comment by Steelpoint** [comment]
screenshot 2015-02-01 23 42 16

**Comment by Incoming5643** [comment]
yeah my bad, didn't see it in the tool pile

**Comment by GunHog** [comment]
I still think this needs a MULEbot drop point (Ripley/Oddy/Mineral crates). The conveyors could be useful in bringing the crates to and from lab. Other than that, this is great :+1:

**Comment by TZK13** [comment]
I don't see the razor anywhere, it would be fine on the table where the box of body bags is.

**Comment by WJohn** [comment]
Robotics really does not need to be remapped. That surgery area is super cramped, and this is basically more cramped than what we have right now because of the conveyor belts.

**Comment by Perakp** [comment]
Surgery is too cramped, conveyor belts take the space you created. I don't see how this is an improvement.

**Comment by xxalpha** [comment]
This will probably frustrate you, but your previous remap better. Surgery here is too cramped.

Conveyor belts are not necessary and do take up a bit of space, though they're not awful.

If the problem with the other remap was not enough space for the mechbay, then steal space from the morgue which doesn't see much use and takes up a shitload of space.

**Comment by WJohn** [comment]
Mech bay previously had tons of space, if there not isn't enough room then that kind of defeats the whole purpose of this PR.

This PR was meant to reduce the size of mech bay, and increase the size of robotics.
It failed at making robotics bigger, now may need to have mech bay made bigger (against the idea) and also shrank

**Comment by WJohn** [comment]
Whoops

**Comment by paprka** [comment]
Surgery is way too cramped.

**Comment by Steelpoint** [comment]
Surgery is more cramped BECAUSE everyone wants a bigger mech bay, thus its one or the other, that or I cut away at the Library/Main corridor for more space.

I also forgot to mention but there is a MULE drop off point in the middle of the Mech Bay.

Conveyor Belts don't take up any space at all, in fact you can use a crowbar to remove them if they are really getting in the way.

**Comment by paprka** [comment]
Conveyer belts are cool as fuck but I suggest this layout and I also suggest you don't listen to anyone else who whines about mech bay being small or whatever

ss 2015-02-01 at 09 53 40

Also that's an anesthetic closet there for Completely Legitimate Surgeries

**Comment by Steelpoint** [comment]
Indeed, I'll take another look.

**Comment by Jalleo** [comment]
I prefer a tiny mech bay because it will encourage people to build rechargers for mechs elsewhere since they are BUILDABLE!

**Comment by Steelpoint** [comment]
Design updated: I hope this will be the final design.

screenshot 2015-02-02 22 03 01

**Comment by paprka** [comment]
:+1: LONG LIVE OLD BOX, LONG LIVE CONVEYOR ROBOTICS!

**Comment by Jalleo** [comment]
:+1: 
Off topic:
Why does every iteration of robotics have a filing cabinet? I never see it used

**Comment by paprka** [comment]
filing cabinets exist purely for clutter basically

**Comment by xxalpha** [comment]
Disposal pipes directly connected to the morgue (or the chef's cold room) to dump bodies instead of a coffin?

**Comment by Anonus** [comment]
I don't like this because the mech bay's ports aren't in a normal setup for no real good reason.
As a possible mech bay setup, maybe like this mockup would be good.
mockup on an older version
Also, you forgot the air alarm for the mech bay.

**Comment by GunHog** [comment]
The conveyors need to be useful for something. Dumping bodies, moving mechs/crates/borgs. Seems odd to have them just for the sake of nostalgia.

**Comment by Steelpoint** [comment]
I hate map merge conflicts with a passion.

I'll have to close and reopen this PR. I'll do so only once I've got confirmation that this is ready to be merged.

**Comment by pudl** [comment]
dont put forth the effort since this isnt gonna get merged lmao

**Comment by paprka** [comment]
I really like anonus' design when you decide to remake this. Also, robotics could benefit from darker floor tiles, it's a pretty grimdark department.

**Comment by Steelpoint** [comment]
Yeah I like it too, I'll use that design.

Again though, I'll have to make a new PR once this one's been accepted to be merged, due to shitty merge failures.

**Comment by paprka** [comment]
Tbh it's not worth waiting for a maintainer to give hte go ahead to make a new PR, just make it. Or wait for the blood PR to be merged because that took me like an hour to do when it comes to mapping.

**Comment by Alek2ander** [comment]
I think the camera in surgery is missing.

**Comment by Super-neji** [comment]
I like this

**Comment by Steelpoint** [comment]
I'll do some map updating.

**Comment by Steelpoint** [comment]
Anonus design is interesting, but it takes up too much space sadly.

**Comment by Steelpoint** [comment]
This is the best I can do with Anonus mech bay design. I did update Sec Cameras and more lights after this image.

screenshot 2015-02-04 21 46 26

**Comment by xxalpha** [comment]
I don't like that the doors to the mech bay and to the lab are right next to each other in the corner. It looks good, but three shutters aren't needed, so my suggesting is move the mechbay airlock one tile to the left so it's not so close to the lab airlock.

Other than that small thing, looks great.

**Comment by Anonus** [comment]
I mostly went with three shutters because it looks nice with the 5-wide bay, even though the doors being close together doesn't look super nice, because squishing it to two shutters and a wall looks completely awful and one shutter is just too small in general.

No complaints with how this is now, so :+1:

**Comment by Jordie0608** [comment]
Changelog.

**Comment by Steelpoint** [comment]
More merge conflict fixes.

**Comment by Steelpoint** [comment]
Merge conflicts fixed.

**Comment by paprka** [comment]
This is honestly very good

**Comment by Steelpoint** [comment]
I could move a airlock inbetween the shutters, but imo I think its fine unless its really ugly. I just want this out of the way as its blocking things.

**Comment by paprka** [comment]
Remove the airlock. Put a button for the shutters outside robotics. Make both buttons robotics access only.

**Comment by Steelpoint** [comment]
Going to close and redo this, its been open for far too long and removes way to many map changes.

Please merge shit quicker next time.

**Comment by TheVekter** [comment]
@Steelpoint while I'm thinking about it you can leave those toolbelts, but it'd probably be better to stash them in the wardrobe so new hires will go "oh shit toolbelt"

**Comment by pudl** [comment]
no one will merge shitty shit quickly lmao loser

**Comment by TheVekter** [comment]
lmao @pudl throwin' shade and deleting it thinkin' no one saw

**Comment by pudl** [comment]
@TheVekter i didnt delete it, miauw probably did

**Comment by paprka** [comment]
Maybe you should take a hint

**Pull request closed without merging**
