### PR TITLE
Immovable reflectors for admins/mappers

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Also bomb and singulo proof

:cl: Kor
rscadd: Adds immovable and indestructible reflector structures for badmin use. 
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
singulo-proof anything is cancer

**Comment by KorPhaeron** [comment]
Dumping a bag of holding and wiping out someones puzzle/maze would be cancer

**Comment by Bawhoppen** [comment]
I will be appeased if xhuis is convinced to make ascendants singulo-able

**Comment by duncathan** [comment]
I don't really like reflectors but this doesn't make them any worse so

**Pull request merged**
