### PR TITLE
Scotch egg description update.

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

Imagine running a cooking channel but not being able to cook.

## Why It's Good For The Game

Internet culture is funny.

### CODE REVIEW

**Comment by AdipemDragon** [comment]
ah yes, a good ol relevant viddy to torment all chef players with

**Comment by Farquaar** [comment]
Who?

**Comment by Imaginos16** [comment]
This is pretty low effort and I don't exactly enjoy blatant references to internet celebrities, but that's just me personally I suppose.

**Comment by carshalash** [comment]
I have no recollection of making this PR. I think I got bored while drunk and did this while debating making eggs a foodtype instead of being meat.

**Pull request closed without merging**
