### PR TITLE
Doubles cog power generation, and allows them to generate power at half efficiency in uncharged APCs

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
balance: Integration cog power generation has been increased to 10 W per second (up from 5 W per second.) Power consumed from the APC remains at 5 W per second.
balance: Integration cogs will now continue generating power at half-speed when the APC they are in has no energy.
/:cl:

@Robustin, you were right and I should have listened. 😔 

In removing stargazers, I feel like I failed to consider that their power generation was constant and impactful. Because of the way integration cogs work, the station is able to completely shut down the cult's power generation by not setting up the engine, or even by draining power.

Now, the cult can still have power even when the APCs the cogs are in run dry, but the tells (25% power etc.) remain so that the crew aren't completely clueless on which APCs they should remove the cogs from. I also buffed the base power generation due to how lackluster it seems to be from the people I've talked with.

### CODE REVIEW

**Comment by ACCount12** [comment]
Isn't 50% too much of a constant power generation? If station crew is actually smart enough to take countermeasures and sabotage the grid, the cultists should just go and fix at least a part of it.

**Comment by Xhuis** [comment]
From what I'm hearing 5 W per second is very unsubstantial, especially because it stops functioning when the APC runs dry. If the crew sabotage their own power grid to reduce the power the cult has, it'll still heavily impact them, but not completely ruin them, when for the crew it's not *as* much of a downside if they keep important areas powered through manual cell replacement.

Decogging APCs is still the most effective countermeasure, but as this PR evidences, I'll address any outstanding issues that crop up.

**Comment by Tlaltecuhtli** [comment]
cant they like steal tesla engines and set them in reebe or something

**Comment by Ratvar** [comment]
Let clockworks buy their own snowflake engine with roundstart power? Will make them protect some location on station that's not crucial

**Comment by Xhuis** [comment]
@Tlaltecuhtli Cogs drain power from APCs, so technically not.
@Ratvar An engine like that would need to be active, i.e. requiring some sort of fuel that can't just be obtained en masse, and I'm not sure of what could be used as that fuel.

**Comment by Ratvar** [comment]
"Fuel that can't just be obtained en masse"
...will vitality work?

**Comment by Xhuis** [comment]
I only really see vitality used once the assault phase has started as a revival tool. It's not very easy to obtain otherwise (only vitality matrices and Ratvarian spears generate it) which makes it scarce unless the cultists just kill people - something I want to move away from.

**Comment by duncathan** [comment]
sure why not

**Pull request merged**
