### PR TITLE
Partially finished planetstation map

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Okand left and I'm not really interested on working on this right now but several people have asked me for the progress, so here it is in one place where anyone can try and finish it.

The top floor:

Is mostly done. The elevators are not yet coded but should be marked off, and obviously the whole thing is still in space/will need baseturfs set. 

Bottom floor: Not much has been done yet. Underground contains many sections of departments but mostly is a place for an elaborate maint Z level so feel free to get creative with what you put down there.

If you're working on this you need to make the X and Z coordiantes line up between the two Z levels for things like ladders, elevators, etc (and if you bomb a hole in the floor on the surface you will be dropped to the same X and Y in the underground.

Anyway anyone is free to attempt to finish this now, if you get far enough I'll stop being lazy and do my part and finish the elevators/baseturfs/surround this with enough jungle that we can do a test run of it live on the servers.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Pics

**Comment by Cyberboss** [comment]
Was fucking with my VM, diffs will come in a bit

**Comment by ExcessiveUseOfCobblestone** [comment]
Think Transit Space probably.

Can't wait to see how this works. Do Walls on Z1 give you unbreakable floors on Z2?

**Comment by Shadowflame909** [comment]
DUN DUN DUNNNNNNNN

**Comment by Shadowflame909** [comment]
thinglings needs the 1000 years later label

**Comment by TechnoAlchemisto** [comment]
I don't get it, where's the jungle?

**Comment by Mark9013100** [comment]
deforested by NT

**Comment by Aloraydrel** [comment]
Open alpha tonight?

**Comment by ishitbyabullet** [comment]
@TechnoAlchemisto It should be able to work in space first before it can work on a planet.

**Comment by deathride58** [comment]
OH SHIT IT'S HAPPENING

**Comment by CitrusGender** [comment]
image

**Comment by iskyp** [comment]
one day i believe

**Comment by Cyberboss** [comment]
F

**Comment by ExcessiveUseOfCobblestone** [comment]
hitler mods....

**Comment by Fikou** [comment]
h

**Pull request closed without merging**
