### PR TITLE
Boxstation: Moves AI Core back to the bridge, gravity generator to the left of Engineering

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
image

## Why It's Good For The Game
Makes Box less like Meta (even though it was here first.) Builds off the [point MSO made in the Box removal thread](https://tgstation13.org/phpBB/viewtopic.php?p=559686#p559686) since variety seems to be an issue with Box's continued existence. 

## Changelog
:cl: MMMiracles
tweak: Boxstation's AI core was moved back into the original position just below the bridge.
tweak: Boxstation's gravity generator was moved to the left of Engineering, accessed through the main Engineering section.
/:cl:

image
image

### CODE REVIEW

**Comment by wesoda25** [comment]
Pictures

**Comment by ATH1909** [comment]
hm yes today i will subvert the ai at roundstart by using a briefcase launchpad to easily boop its core with a hacked law board

**Comment by duncathan** [comment]
this may conflict with #50726

**Comment by ZeWaka** [comment]
I think this is a good change to differentiate the two maps. I've always liked having the AI core in a more centralized spot anyways.

**Comment by Fikou** [comment]
BASED

**Comment by Tlaltecuhtli** [comment]
good, fuck ais

**Comment by FatCat919** [comment]
no

**Comment by AtlasRules** [comment]
bluespace launchpad called, it said it's gonna make the AI subvertible in less than a minute

spess is secure, this is not

**Comment by Rohesie** [comment]
I like the change.

The bluespace launchpad should be nuked from orbit, to be fair.

**Comment by Rohesie** [comment]
Is it functional and ready for merge?

**Comment by MMMiracles** [comment]
Yeah.

**Comment by ExcessiveUseOfCobblestone** [comment]
@MMMiracles there are 2 wires under the first upload access door, would you mind removing one of them when it is convenient?

**Pull request merged**
