### PR TITLE
Psychologist

### PR DESCRIPTION
**Pull request by uomo91**
## About The Pull Request

primage

This adds a Psychologist job to the station, listed under the service category but subordinate to both the HoP and CMO, and a small office on each map (Meta, Box, Delta, Kilo, Donut, Pubby) located in medbay and accessible only to the Psychologist, CMO, HoP, and Captain.
This adds no mechanical changes to the game.

The Psychologist's inventory consists of:
Depending on jumpsuit/skirt preference, the male or female version of /obj/item/clothing/under/suit/black
Laceup shoes.
A headset with both service and medical frequencies.
A clipboard.
A medical PDA, useful for detecting cerebral traumas.
A medbay backpack/satchel/duffelbag if preferences set to department bag.

The Psychologist's office consists of:
A cool new Psych department sign. (thanks Twaticus)
A medical laptop.
Carbon paper and a filing cabinet to dispense and store doctor's notes and prescriptions.
A secure locker containing a copy of the psychologist's round start items, as well as a straight jacket, muzzle, blindfold, and earmuffs.
A comfy couch and chair for therapy sessions.
A motivational poster.
A moff plushie to comfort those in the midst of reliving childhood traumas.

Psychologist office locations:

- Meta - replacing medbay office.
- Box - replacing part of the ward.
- Delta - replacing abandoned medical.
- Donut - replacing small secondary surgery room
- Kilo - replacing disused genetics.
- Pubby - replacing part of ward/disused genetics.

## Why It's Good For The Game

Question: Isn't this just lawyer 2.0?
Answer: Yes, and that is 100% the intention, for now. This is an RP job any way you slice it. I believe this PR stands both on its own merits purely as an RP job, and also to help lay the foundation for future work from others to flesh out a Psychologist/Psychiatrist job with actual unique mechanics. We have even had prior and ongoing work done to that end. https://github.com/tgstation/tgstation/pull/48403 I've spoken to the author of this and he has expressed approval. With the groundwork laid by this PR in terms of job, access, and area code, as well as standardizing a spot for psych in future mapping, I believe this will make his or anyone else's job infinitely easier and allow them to focus solely or at least mostly on introducing cool mechanics.

Q: But if there are no mechanical changes or additions here, what does the Psychologist DO?
A: Collaborate with the CMO & HoP, other heads of staff, and security to try to diffuse disputes and lend a listening ear to unruly individuals, help integrate criminals back into working society, talk to and provide company to sad, angry, confused, traumatized, or bored crew members, collaborate with the lawyers on perceived injustices and abuses and serve as an expert witness in court, provide patients signed prescriptions to redeem with the chemists/pharmacists/botanists, subtly remind everyone they're ultimately just wageslave cogs in the machine and encourage them to keep on truckin', keep the rarely utilized medical records up to date and add detailed theories on the sexual orientation of the Captain, when traitor hypnoflash people to nefarious ends (NO ERP) under cover of a secluded and safe room. Essentially, use your imagination, be creative, and ROLEPLAY.

Q: Why the service category and not the medical job category?
A: With the recent addition of Paramedic the medical category feels very well rounded at present, and adding a sixth job to the listing seems more out of place than the alternative. Medical already has more slots than any other department. Further, while operating within (doesn't make much sense to locate their office anywhere else) and cooperating with medbay, this job itself currently doesn't really fit in lockstep with most of the normal functions medbay provides.
This can be subject to change based on what direction future changes such as the addition of gameplay mechanics takes psychology/psychiatry in.

## Changelog
:cl:
add: There is now a Psychologist job and a Psychology office in medbay on every map. Help the crew get their head straight!
/:cl:

### CODE REVIEW

**Review by bobbah — APPROVED** [review]

**Comment by HomocidlePancakes** [comment]
Psychologist doesn't get "medicine" to "prescribe" to "paitients" in "deep distress"? Silly.

**Comment by uomo91** [comment]
We have these people called "chemists" and "doctors" and "the CMO" or even "botanists" who the patient can take a signed prescription from the Psychologist to (or the Psychologist on their behalf), to get said medication. And if the Psychologist anticipates needing them he can also ask any of them for a supply preemptively.

**Comment by Fikou** [comment]
please edit the access on the service hall/service lathe doors to allow psychologists in

**Review by Rohesie — DISMISSED** [review]

**Comment by trollbreeder** [comment]
Gonna rush to put the lizard plushie in abandoned storage next to the moth plushie in psychology

**Comment by cacogen** [comment]
Psychologists don't prescribe medicine and aren't medical doctors. Psychiatrists (specialist doctors) do. Psychiatrists can also do therapy. Given this guy is in medbay and you've said he can prescribe medicine if he wants with the help of other medbay staff, you should consider renaming it Psychiatrist. That sounds like a more fun job that creates room for the addition of psychiatric medicines in future, and maybe mental illnesses.

**Comment by trollbreeder** [comment]
> (snip) ...and maybe mental illnesses.

Cerebral trauma system, anyone?

**Comment by ExcessiveUseOfCobblestone** [comment]
After giving this some thought, i'm okay with it.

I think i was just a bit upset it's a great opportunity to enhance gameplay and it's just being marketed as RP (for now), and that will perhaps create pushback for new features going forward that give it more pronounce presence in the world (which I'm of the opinion all jobs should be useful in various ways).

**Comment by ATH1909** [comment]
I like this job/this PR (and the moth plushie placement there is just top tier), but I'm worried about what will come after it. People are gonna want to add some psychology/advanced trauma mechanics for this job to interact with like what #48403 tried to do, and that scares me.

**Comment by tmtmtl30** [comment]
one man's slippery slope is another man's slip-and-slide

**Comment by RaveRadbury** [comment]
Going forward from here I'm of the opinion that if we are going to see the psychologist provide relief from mental trauma that it should be a temporary thing that is also linked to being in their presence while also in the office. So you get some shrink time, then you can go and do okay for like 15 minutes or something before you have to re-up on your mental health.

Now that cloning is gone brain traumas are a bigger deal and I'm not sure if we should add a job that allows them to be easily gotten rid of.

**Comment by Shadowflame909** [comment]
I feel like having it just be an RP job right now, will create another lawyer/curator situation.

Those guys still have NOTHING to do. Leaving them with power-game tools and the such. (Librarian more then the lawyer.)

**Comment by Pumpkinoe** [comment]
isnt the intention for this to be a roleplay job tho shadowflame

**Comment by Shadowflame909** [comment]
Yeah. But I just think the PR author, and any maintainers who are gunning off the "Fleshed out mechanic" future like said here

>This is an RP job any way you slice it. I believe this PR stands both on its own merits purely as an RP job, **and also to help lay the foundation for future work from others to flesh out a Psychologist/Psychiatrist job with actual unique mechanics**.

Should think about previous examples like curator and lawyer, and know that this aint happening. Because it still hasn't happened for them.

**Comment by Hopekz** [comment]
Is this inspired by Yogstation's Psychologist that they've had for years?
It seems exactly like it but I can't find any mention in the descriptions.

**Comment by AdamElTablawy** [comment]
no, hopekz, bay has had psych roles for years too, and the role is an obvious one

**Comment by RiskySikh** [comment]
This is gonna be a good job role

**Comment by Hopekz** [comment]
> no, hopekz, bay has had psych roles for years too, and the role is an obvious one

Are you the co-author or do you just magically know what everything is inspired by just by "feeling" it

**Comment by uomo91** [comment]
> please edit the access on the service hall/service lathe doors to allow psychologists in

Will do.

> Psychologists don't prescribe medicine and aren't medical doctors.

You are correct, however, this IS a game. In real life, the vast majority of doctors do not perform brain surgery in between tending minor boo-boos, the vast majority of engineers do not do routine welding and also troubleshoot reactors that can catastrophically fail; here on TG, they do. I opted for "Psychologist" as a name and hinting at the prescription stuff because I thought it underscores that this role could be played to be social and add RP flavor to rounds.
If in the future somebody or another brings gameplay mechanics to fruition, and they feel "Psychiatrist" fits more, they are free to make that judgement call.

> Is this inspired by Yogstation's Psychologist that they've had for years?
> It seems exactly like it but I can't find any mention in the descriptions.

If you are asking what my _personal_ inspirations to make this job were, I don't spend a ton of time on other codebases or servers, it'd actually be TG roles like Lawyer and CentCom Official, as well as my excitement from seeing the original psych PR.

**Comment by fatted50** [comment]
medical lawyer
medical lawyer

**Comment by evilcyborgmrt** [comment]
How about a HUD or something that let's them see people's mental status?

**Review by 81Denton — APPROVED** [review]
I don't see any issues with this, good job! I also like how this repurposes some of the gaping holes that cloning removal left in medbay.

**Pull request merged**
