### PR TITLE
Updates Centcom (and minor updates to other z2 areas)

### PR DESCRIPTION
**Pull request by Mervill**
:cl: Mervill, Joan
add: Centcom has a new coat of paint
/:cl:

Other updates to z2:
- Laser tag arena moved to the lower right hand corner
- Admin prison moved next to the error room
- Wizard ship moved to the left slightly so that the syndie area can be rectangular
- Syndie area made more rectangular

### CODE REVIEW

**Comment by jughu** [comment]
Be cool if you could do this to syndibase too 👍

**Comment by WJohn** [comment]
This is pretty barren. The current one has more things to look at. I get that it's the end of the round so it doesn't matter much but come on. Add some life and clutter to this.

**Comment by RandomMarine** [comment]
The only thing I dig is the big NT logo, but that can fit in the current centcom dock anyway.

**Comment by Mervill** [comment]
@ChangelingRain looks like we're in the minority here, I'll have to add something to entry area

**Comment by coiax** [comment]
@Mervill I don't like it, I'm sorry. Why are you making these changes?

**Comment by XDTM** [comment]
Is the first set of doors accessible?

**Comment by Okand37** [comment]
I was planning on redoing centcom more in tune of the old 'fuller' centcom. If you want, I could incorporate your awesome idea's such as the nanotrasen N flooring into it? Wouldn't want to step on any toes, of course!

**Comment by Mervill** [comment]
lmao, the whole reason I got this out so early is that i KNEW if I didn't you'd get around too it

I did have the idea for the N originally, Joan was the one who did the final design though

**Comment by Okand37** [comment]
Haha, well its a pretty good idea. Maybe we can try and collaborate on it a bit and make something beautifully awesome?

**Comment by Mervill** [comment]
That sounds like I plan. It was a bit rushed anyway since I was trying to beat you to the punch.

**Comment by Mervill** [comment]
tfw I think I can compete with oakland 🗡 🤕 

(not really that salty, fyi. your centcom looks amaze)

**Pull request closed without merging**
