### PR TITLE
You must be 18 or older to play

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Added more SS13 memes like buff/nerf/[what the fuck is]carbon

Removed distasteful memes.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1: butt, fart, and porn are staples of the stock market economy

**Comment by Fox-McCloud** [comment]
>butt

>distasteful meme

Get out.

**Comment by Iamgoofball** [comment]
emot-frogout

**Comment by MrPerson** [comment]
Stop shitposting goofball

**Comment by Bawhoppen** [comment]
shall I post irrelevant pictures

**Comment by ExcessiveUseOfCobblestone** [comment]
please post pictures of cats to coral the super memers

**Comment by PKPenguin321** [comment]
ppoops & farts

**Comment by Iamgoofball** [comment]
no poop is baned
@ExcessiveUseOfCobblestone can you just re-add butt/fart/porn and combine it with your shit

**Comment by Thunder12345** [comment]
Yeah if not for the removals this is cool, just add the new ones

**Pull request merged**
