### PR TITLE
Fails the build if CENTCOM is misspelled

### PR DESCRIPTION
**Pull request by Cyberboss**
Common error

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Maybe YOU'RE WRONG !!!!

**Comment by yorii** [comment]
lol at the checks failed

**Comment by DaedalusGame** [comment]
*centcomm

**Comment by Cyberboss** [comment]
##34249

**Comment by ExcessiveUseOfCobblestone** [comment]
Comon error*

**Comment by nicbn** [comment]
> Adds a centcommap var
> Travis fails to compile

**Comment by ShizCalev** [comment]
Clearly it works. :^)

**Pull request merged**
