### PR TITLE
Hitting a closet with an item will try to open it

### LINKED ISSUE #16244: Can't open lockers with items in your active hand... again.
### What is the problem?
If you click on a closed locker with something in your active hand, nothing happens.

### Why is it a problem, or what should have happened?
The locker used to open when you did this. At some point this bug occurred, but it got fixed. Dunno why it's happened again, but it's been in for a bit.

### How can the problem be reproduced?
Try open a locker with something in your active hand.

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
bugfix: You can once again hit a closet or crate with an item to open it.
/:cl:

Fixes #16244

### CODE REVIEW

**Comment by xxalpha** [comment]
# MERGE NOW

**Comment by lzimann** [comment]
thanks

**Comment by PKPenguin321** [comment]
goooooood shit homie :+1:

**Comment by TrustyGun** [comment]
praise

**Pull request merged**
