### PR TITLE
Optimizes Kilo, Meta, and Box Grav Gens

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Basically the issue all 3 of these shared was that they were independent from the powernet. Once their SMES and APC's ran out, grav gen was fucked. Station either had to just connect them to the powernet, or set up a generator at this point. 

I'm connecting the SMES to the powernet so that they recieve power, but do not send it. So the grav gens for these stations have their reserves protected if stations power goes down, and recieve power if not. Pubby and Delta already had these features, idk about Donut. 

I'm gonna put pictures in a comment below so that PR body doesn't get too long

## Changelog
:cl:
tweak: Optimizes the gravity generators of Kilo, Box and Meta, so that they receive power from the stations powernet, but do not send power to it.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
box grav
dreamseeker_5V7HlTKZCu
dreamseeker_sECCgEHqRH

**Comment by LordSaladin** [comment]
did you say kilo?

**Comment by wesoda25** [comment]
I hope we might get to see it in rotation again one day, so I updated it

**Comment by Rohesie** [comment]
Very nice.

**Comment by optimumtact** [comment]
This is something engineers can choose to do, I see no reason to take that choice away from them

**Comment by wesoda25** [comment]
How considerate of you to think of the engineers who DON'T want an optimal grav gen set up. This is already a thing on two maps, why should it not be on these maps?

**Comment by optimumtact** [comment]
Because map power creep is real so that isn't an argument frankly.

all you are doing is actively removing work for engineers to do, contributing to it being a boring job and literally degrading the game experience, because you've done this multiple times and no longer want to do it.

**Comment by wesoda25** [comment]
tbf I've never done this as engineer and had to figure this shit out while making the pr. Also, on maps like meta this isnt really possible due to the limited space barring you completely move around the SMES and everything, which is more work than its worth. On all these maps its just legitimately bad design bc it eventually goes out, is it really powercreep to fix that?

**Pull request closed without merging**
