### PR TITLE
Revert math

### PR DESCRIPTION
**Pull request by ninjanomnom**

### CODE REVIEW

**Comment by lordpidey** [comment]
A PR with 178 files changed and no explanation leaves me curious.

**Comment by Armhulen** [comment]
no more math, the title says it all.

**Comment by deathride58** [comment]
Just to be sure, this reverts #32925, #33030, and #33035, yeah?

**Comment by ShizCalev** [comment]
Correct

**Comment by alexkar598** [comment]
All those black tags!!!

**Comment by banthebantz** [comment]
how much did you break?

be honest...

**Comment by duncathan** [comment]
that can't currently be calculated as math is broken

**Comment by Anonmare** [comment]
math is ded

no math

**Pull request merged**
