### PR TITLE
Revert "turns the baseturf var into a part time list (#33705)"

### PR DESCRIPTION
**Pull request by Cyberboss**
This reverts commit 4595c46dca95d148ca46641379f135ac1e4411c0. (#33705)

People say is bork

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
just testmerge it while it's fixed

**Comment by ninjanomnom** [comment]
why is it broken? It was testmerged for a long time and I got no reports of anything broken

**Comment by optimumtact** [comment]
\>people say

would these people like to come forward and offer their surely brilliant insights?

**Comment by duncathan** [comment]
people love to blame changes like this for unrelated bugs. if this is just for test merging then close it

**Comment by ninjanomnom** [comment]
I would definitely not be surprised if there are bugs related to this but it irks me that no one reported them before it got merged.

I had it testmerged for so long for a reason.

**Comment by optimumtact** [comment]
`I think` or `people think` is never enough to test merge revert something, proper investigation should be done

**Comment by Cyberboss** [comment]
It's mostly related to things turning into space when they shouldn't be.
@coiax and someone else reported it.

**Comment by ninjanomnom** [comment]
how? what circumstances? why did they make no issue or post in the pr?

**Pull request closed without merging**
