### PR TITLE
Adds single use autosurgeons for both the RD and HoS to their lockers.

### PR DESCRIPTION
**Pull request by Firecage**
This PR adds two new autosurgeons. One for a security hud, and another for a diagnostics hud. And it adds the security one to the HoS's locker, and the diagnostic one to the RD's locker. I was inspired by the CMO recieving a medical hud autosurgeon.

:cl: Firecage
add: Adds a security autosurgeon to the HoS locker, and a diadnostics autosurgeon to the RD locker. Be warned, only one set of eye augments can be active at a time. Using another will remove the one you had and replace it.
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
Booo

**Comment by Firecage** [comment]
So, why Boooooo exactly Juggle-kun?

**Comment by Mark9013100** [comment]
I never asked for this.

**Comment by KorPhaeron** [comment]
Powercreep

**Comment by MoreRobustThanYou** [comment]
i likei t

**Comment by Bawhoppen** [comment]
This is severe powercreep.
If you had to, add the hud implants but make them actually have to go to medbay.

**Comment by YakumoChen** [comment]
Even I think this is too severe for powercreep.
-t. Powergamer RD main

**Comment by KorPhaeron** [comment]
If you have some compelling argument about why the game needs this PR that will make me merge this leave it here but otherwise I don't think this needs to stay open

**Comment by Pascal125** [comment]
The HoS already has access to Sechuds and a variant of the Sechud.
The RD can easily take a Diagnostics scanner from Robotics.
CMO has access to; and iirc, begins with. A medical hud, yet they get to have an autosurgeon.

It's really just a cosmetic option. Just as the CMO's autosurgeon is. I rarely see it used by CMO's.
The only "Powercreep" thing about is the inability to strip it from them. But that's rarely a problem as Antagonists or anyone predisposed to doing so will unlikely try to, anyways. And the HUDs being permanent until death will not help them much if at all; in the situations where they do.

On top of that; they're head's of staff. They *usually* start off with fancy toys. Like the Syndicate.

RD has a reactive vest.
HoS has a special gun, and an eyepatch HUD.
CMO has a special scanner, hypospray, and autosurgeon.
Captain has their sword, hand-teleporter, and special gun.
CE has a special Hardsuit, Boots, and Keycodes to read everyones PDA logs.

Is a one-use automatic eye implanter really that big of a deal?

**Comment by KorPhaeron** [comment]
>they have X so is adding Y on top really that big of a deal

powercreep

HoS doesn't need to be able to put on mesons or whatever and still have hud vision

**Comment by Pascal125** [comment]
Mesons have been updated and; last i checked, are actually fairly useless nowadays. and aren't/never have been usable as pseudo X-Ray vision.

**Comment by Firecage** [comment]
@KorPhaeron Understandable, and I accept your reasoning that this is probably just to much.

**Comment by jughu** [comment]
i be fine with RD having a autosurgeon with a diagnostics hud but dont forget you can screwdriver the autoimplanter for the implant and then deconstruct it at rnd

**Comment by Firecage** [comment]
Jughu, well, if Kor gives the all clear and opens this PR, I will reduce its bio and engineering tech origin while also removing the HoS autoimplanter.

**Comment by jughu** [comment]
👍

**Comment by PKPenguin321** [comment]
Did I not make it so single use autosurgeons can have a var switched to prevent them from being screwdrivered? Just do that if you add more

The CMO only got one from me because somebody gave him the medical implant in his locker, but it was literally never used and felt like a waste but I couldn't really justify removing it. If people are this shaken up by the CMO having one then I'd rather the CMO's autoimplanter gets removed than more get added, but honestly I think things are fine as-is.

**Comment by GunHog** [comment]
There are two big issues with surgery that make it undesirable and require the autosurgeons to have these implants see usage:

1. Risk vs reward. This is a paranoia heavy game, fueled by the very real danger of being murdered easily by the surgeon. Having an implanted HUD over a worn one is an insignificant reward compared to the risk of being removed from the round by antagonist posing as a surgeon.

2. Inconvenience. Surgery tends to be time consuming (measured from single to double digit minutes) based on if the patient can get someone willing to operate and competent enough to do so in a timely manner.

For the CMO's medical HUD implant, it was simply not worth it considering those two factors. The same would be true for a diagnostic HUD. Security HUDs are a different matter, however.

**Comment by Firecage** [comment]
@KorPhaeron Soooooo

**Pull request closed without merging**
