### PR TITLE
fixes inconsistency  with sec armors and police batons

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: all sec armors can store the police baton / telescopic baton
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Please justify this further

**Comment by Tlaltecuhtli** [comment]
if det uses normal armor or sec space suit he cant store his wooden long cylinder while he can store his orange tipped long cylinder or the short metal cylinder
or you use conversion kit on your baton yo cant  store it on armor anymore

**Comment by ATH1909** [comment]
This is technically a balance change, but it's also a sensible one.

**Comment by LemonInTheDark** [comment]
If you're making a balance change please explain why. Is it only due to consistency, or is there further reasoning.

**Comment by Pugie** [comment]
The reasoning is that batons should be able to fit on armor, I doubt there's an ulterior motive at play.

**Comment by XRandomXManX** [comment]
> The reasoning is that batons should be able to fit on armor, I doubt there's an ulterior motive at play.

nO tHEY're pOwowergaming bY HelpIng seCurity wIth a ProBlem they SHouldn't hAve

**Comment by SkeletalElite** [comment]
> If you're making a balance change please explain why. Is it only due to consistency, or is there further reasoning.

Does it need further explanation. Why should you be able to put stun prods and stun batons on your armor but not regular batons.

**Comment by optimumtact** [comment]
that's not what they have to justify, they have to justify why they chose to fix it by making the regular baton fit, instead of making the stun prod and stun baton not fit.

**Comment by ATH1909** [comment]
> that's not what they have to justify, they have to justify why they chose to fix it by making the regular baton fit, instead of making the stun prod and stun baton not fit.

Because it makes logical sense that a piece of SECURITY GEAR would fit in the exosuit storage slot of a piece of SECURITY ARMOR?

Plenty of of other job-related exosuit items (labcoats, biosuits, etc.) allow you to wear job-related items in them, so I don't see why the same can't be the case for sec armor.

**Comment by Tlaltecuhtli** [comment]
stun baton not being wearable on suit just gives the player less customization (only guns go there) and lack of options ( cant have shift + e keybind to grab /equip baton combined with keybind to grab bola from belt) and causes more consistency problems as for example the contractro baton cant be put in contractor suit, others reasons are already been given by athath, pugie and the redditor in form of comments

**Comment by Tlaltecuhtli** [comment]
@LemonInTheDark  hello?

**Comment by LemonInTheDark** [comment]
To be clear, I'm not blocking this, I don't really see a reason to merge it, but I'm not gonna close it. I think your reasoning is flawed, as most of the time the only source of roundstart batons on the station won't be wearing these things, but I honestly don't think it's a big enough deal to get worked up about.

**Comment by SkeletalElite** [comment]
> To be clear, I'm not blocking this, I don't really see a reason to merge it, but I'm not gonna close it. I think your reasoning is flawed, as most of the time the only source of roundstart batons on the station won't be wearing these things, but I honestly don't think it's a big enough deal to get worked up about.

HoP gets an armor vest
Detective gets a armor vest in their closet
RD Has telearmor, not sure if it's a subtype of the armor vest or not but if it is it's affected by this.
The captain get's armor
the CE and CMO are the only people with batons who DONT have armor

**Comment by Tlaltecuhtli** [comment]
>as most of the time the only source of roundstart batons on the station won't be wearing these things,

thats where the issue is, a source of batons ( constable kit) makes you unable to wear it cause of the wrong armor type (sec with police baton)

**Comment by LemonInTheDark** [comment]
I figured, that's good enough for me

**Pull request merged**
