### PR TITLE
Removes antag hud when deadminning

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I hit accept for a parasite roll and forgot it was on and now Lollerderby is permabanning me so I'll save future admins with this final PR

### CODE REVIEW

**Comment by Aloraydrel** [comment]
adios amigo

**Comment by RemieRichards** [comment]
@KorPhaeron this isn't safe, you'll remove their legit HUDs

**Comment by KorPhaeron** [comment]
I guess the solution is to not be dumb then unless you can think of a way

**Comment by Dicks1** [comment]
Since you're perma banned just remove all your code like every other coder ever did when they left.

**Comment by KorPhaeron** [comment]
@Dicks1 

I remember someone demanding we remove all their sprites but not any drama about code, who did the code thing?

**Comment by tkdrg** [comment]
The admin verb will remove the legit HUDs as well. I guess you could check for all antags when readding it, but there's no easy way to solve this apart from "don't turn it on if you're antag" and "trust your admins".

**Comment by RemieRichards** [comment]
@tkdrg they're /datum/hud/antag, so why not give that an antag flag, and then have the verb check for the antag flag on that antag datum?

**Comment by tkdrg** [comment]
Makes sense. Give it a "admin_hud" var on the admin verb, and check for that on removal. You should do that @KorPhaeron ti's a great solution

**Comment by Alek2ander** [comment]
The way that makes the most sense is to only give the HUD to ghost admins, and reset it when the admin isn't a ghost anymore.

**Comment by KorPhaeron** [comment]
It actually does reset when you switch mobs, because the sequence of events was

>turn hud on
>forget about it and become parasite
>shadowlight PMs me calling me a dirty metagamer
>re-admin, hit toggle hud
>this turns it back on
>assuming that meant that deadminning (not mob switching) turned it off I deadminned again and had it on

Luckily doesn't do shit in a traitor round.

**Comment by MrStonedOne** [comment]
The Antag hud should be limited to ghosts anyways

**Comment by Jordie0608** [comment]
You could make it toggle in client.login()

**Comment by KorPhaeron** [comment]
I have too many PRs have finished and this isnt urgent

**Pull request closed without merging**
