### PR TITLE
This PR actually gives metal hydrogen armor item sprites

### PR DESCRIPTION
**Pull request by dawsonkeyes**
## About The Pull Request

I'm an idiot

## Why It's Good For The Game

no more error

## Changelog
:cl:
fix: elder atmosian armor has item sprites
/:cl:

### CODE REVIEW

**Comment by Twaticus** [comment]
what the. sorry for missing that in the first PR. looks good once the conflicts are fixed

**Comment by dawsonkeyes** [comment]
> what the. sorry for missing that in the first PR. looks good once the conflicts are fixed

Yeah, unsure of what the issue is when I've edited nothing in the code- monkey business at work, probably

**Comment by Twaticus** [comment]
looks like your repo is behind

**Comment by Potato-Masher** [comment]
image

You may have not touched anything code-wise, but it seems your repo is behind. You may not have the recently added coats and CentCom uniforms.

**Comment by ATH1909** [comment]
image

**Pull request closed without merging**
