### PR TITLE
Redesigned the sterile mask sprites, for the mask itself, mob and box

### PR DESCRIPTION
**Pull request by Skrylfrr**
Redesigned the sterile mask sprites, for the mask itself, mob and box overlays. 

Better than small blue rectangles!

## About The Pull Request

Redesigned sprites for the sterile mask (/obj/item/clothing/mask/surgical), including mob and box overlays.

Better than small blue rectangles!
Virologist with masks and box on floor
## Why It's Good For The Game
The texture has been updated to include a more dynamic shape than Rectangle and now more than two colours!

## Changelog

Virologist_with_masks_and_box_on_floor

:cl:
New design for sterile masks. Better than small blue rectangles! Screenshots at https://imgur.com/a/A5BP0yt
tweak: Restyled sterile mask sprites in icons/mob/clothing/mask.dmi
tweak: Restyled sterile mask box overlay sprite in icons/obj/storage.dmi
/:cl:

### CODE REVIEW

**Comment by liilac** [comment]
Hope this gets merged @Skrylfrr! Look forward to seeing the new design in game 😊

~~@optimumtact~~

**Comment by Imaginos16** [comment]
> Hope this gets merged @Skrylfrr! Look forward to seeing the new design in game 😊
> 
> ~@optimumtact~

Why did you ping the head coder????

**Comment by liilac** [comment]
> @liilac why did you ping our headcoder for a sprite change

> > [snip]
> Why did you ping the head coder????

Honestly no good reason, it was meant to be silly. I know them personally and did not expect them to mind.

> technique-wise the sprites look great, only thing is they look weirdly wrinkled. Would be a super cool level of detail if the sprites were perfect rectangles in the box, and crumpled after being worn.

Fair suggestion! Which sprites look weirdly wrinkled, the box overlay and the (unused) masks items? 

I believe the crumpled appearance after use would require some minor code changes. Are there other items that implement a similar mechanic, as a reference?

**Comment by Skrylfrr** [comment]
> technique-wise the sprites look great, only thing is they look weirdly wrinkled. Would be a super cool level of detail if the sprites were perfect rectangles in the box, and crumpled after being worn.

you're violently cramming your fist into the box grasping at it blindly, seizing your target similarly to how a baby clasps onto a small object with its little monkey vicegrip. canon reason for crumples.

(if an option in the code existed to make it crumple only after being put down once ((sounds easy enough-unused texture, detect the change to down state, keep a crumpled texture from then on.)) that'd be epic, I'd texture for all that. I also would like to retexture the mask box a unique design similar to how donuts aren't just in the default grey cardboard box.)

**Comment by MrDoomBringer** [comment]
> the box overlay and the (unused) masks items?

Yep
> you're violently cramming your fist into the box grasping at it blindly

Made me chortle


Honestly I can't think of anything else with a similar mechanic, other than maybe xeno facehuggers. I wouldn't worry about it, seeing that this is your first PR. Welcome to the repo!

**Comment by optimumtact** [comment]
> Hope this gets merged @Skrylfrr! Look forward to seeing the new design in game blush
> 
> ~@optimumtact~

thogarrived

**Comment by Serxule** [comment]
not bad, but it has way too much detail, itd fit on something like cev eris, but not really tg.

**Comment by optimumtact** [comment]
@Serxule what a odd thing to say, if we ever want to get sprites half as good as CEV's then we need to accept Pr's with good quality sprites

**Comment by Skrylfrr** [comment]
> @Serxule what a odd thing to say, if we ever want to get sprites half as good as CEV's then we need to accept Pr's with good quality sprites

I've been noticing a slow increase in sprite upgrades! Especially in mining and tool related textures, and I reckon others can be upgraded as well! It's really cool seeing the game get less eyebleedy - I can show it to friends more easily! 

I'm not active much in the community or anything but I've been playing virologist a lot and I hate how out of place and janky the old two-tone texture is compared to a lot of the much smoother sprites. 

I also go outside every day wearin a sterile mask! I know what they look like hahaha

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Your changelog is not formatted correctly.

1. You want to have `spriteadd: Adds new sprite for such and such` (it might be imageadd, I forgot)
2. Remove your "tweak" entries. Not only does "tweak" not exist anymore, but changelogs are only for player facing changes.

**Comment by Imaginos16** [comment]
> Your changelog is not formatted correctly.
> 
> 1. You want to have `spriteadd: Adds new sprite for such and such` (it might be imageadd, I forgot)
> 2. Remove your "tweak" entries. Not only does "tweak" not exist anymore, but changelogs are only for player facing changes.

It is, in fact, imageadd

**Comment by Skrylfrr** [comment]
> 

Gotcha! I'll fix that when someone in my house who can code wakes up

**Comment by ExcessiveUseOfCobblestone** [comment]
You just edit the top box no code involved?

**Comment by Twaticus** [comment]
i dont really think this looks good sorry. very noisy base and the jaggy bits on top dont help either

**Pull request closed without merging**
