### PR TITLE
Bolted AIs now have TRAIT_NO_TELEPORT while bolted, and their move resist is MOVE_FORCE_OVERPOWERING

### LINKED ISSUE #47331: Launchpads can move anchored AIs
Briefcase Launchpads are especially easy replication for this. Hover the targeting reticle over the AI you wish to have deleted. Press pull. The AI is now on your briefcase. Which likely will be in space and therefore leaving them without a power source.

This is supposedly meant to have been fixed in this PR. https://github.com/tgstation/tgstation/pull/46646

Maybe.

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Does as the title says.

## Why It's Good For The Game
Keeps the launchpad from teleporting AIs, and the new move resist should stop shuttles from knocking them loose.

Specifically, fixes #47331 

Does not change interactions such as dragging the AI (or being unable to when they're bolted).

## Changelog
:cl:
fix: Bolted AIs can no longer be teleported by launchpads.
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Prob fixes #41030 as well.

**Comment by SpaceManiac** [comment]
I'm pretty sure mobs aren't supposed to be anchored anymore

**Comment by zxaber** [comment]
Is there any particular reason we can't use anchored on mobs? It doesn't *actually* lock them down (it just prevents them from being pulled), but for mobs that are locked in place due to other reasons, it seems like a decent way to let other code know that this particular movable atom shouldn't be moved.

**Comment by spookydonut** [comment]
> 
> 
> I'm pretty sure mobs aren't supposed to be anchored anymore

https://github.com/tgstation/tgstation/blob/master/code/modules/unit_tests/anchored_mobs.dm

**Comment by SpaceManiac** [comment]
@kevinz000 but kevinz doesn't check github pings so please get their attention on this

**Comment by TheMidnightRose** [comment]
> Is there any particular reason we can't use anchored on mobs? It doesn't _actually_ lock them down (it just prevents them from being pulled), but for mobs that are locked in place due to other reasons, it seems like a decent way to let other code know that this particular movable atom shouldn't be moved.

Fairly certain that Megafauna use anchored.

**Comment by kriskog** [comment]
Mobs should in general use move_resist to prevent pulling/pushing, but teleports aren't affected by it. Megafauna deals with it by having the no teleport trait, you can add that when the AI is bolted. 

Do increase the bolted move_resist to MOVE_FORCE_OVERPOWERING as well while you are in there, to fix #41030. Emagged shuttle throw is MOVE_FORCE_EXTREMELY_STRONG.

**Comment by zxaber** [comment]
No longer uses anchored variable, and instead uses the no-teleport trait. Also sets move resist to MOVE_FORCE_OVERPOWERING.

**Review by 81Denton — APPROVED** [review]

**Pull request merged**
