### PR TITLE
Fixes firedoors auto-opening/closing without power

### LINKED ISSUE #25655: Fielocks autoclose without power
Guess they have internal batteries.

At the rate of these bug reports we aint ever getting to  600 issues

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #25655 

:cl:
tweak: Firedoors no longer operate automatically without power
/:cl:

### CODE REVIEW

**Comment by Tacolizard** [comment]
balance/rebalance tag?

fires often coincide with power being knocked offline, so this is potentially a major nerf.

**Comment by Cyberboss** [comment]
I believe repo policy is to fix unintended behavior first, then consider rebalancing.

**Comment by optimumtact** [comment]
100% certain this is intended behaviour

**Comment by optimumtact** [comment]
@KorPhaeron

**Comment by ChangelingRain** [comment]
This is something Cyberboss added so I think he knows what he's talking about hey yo

**Comment by KorPhaeron** [comment]
Cyberboss didn't add firedoors what

**Pull request merged**
