### PR TITLE
Kicks now inform you who kicked you.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by WJohn** [comment]
Wait it didn't do this already? Huh.

**Comment by tedward1337** [comment]
:salt:

**Comment by Niknakflak** [comment]
:salt:

**Comment by Iamgoofball** [comment]
:salt:

**Comment by Saegrimr** [comment]
:salt:

**Comment by optimumtact** [comment]
Sure is a lot of admins projecting in here.

**Comment by Shadowlight213** [comment]
@iamgoofball make it not inform who kicked you if the admin is stealthminned.

**Comment by Bawhoppen** [comment]
salt is one thing but this is actually a good change

**Comment by Cheridan** [comment]
weakens the admin conspiracy :-1:

**Comment by Shadowlight213** [comment]
:salt:

**Comment by Firecage** [comment]
Defnitely shouldn't tell you who kicked you.

**Comment by freerealestate** [comment]
:-1: admins should be masked executioners

**Comment by Niknakflak** [comment]
:salt:

**Comment by Aloraydrel** [comment]
:^)

**Comment by Iamgoofball** [comment]
@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by Shadowlight213** [comment]
You still haven't made any of the suggested changes.

**Comment by Iamgoofball** [comment]
@Shadowlight213 Bans don't hide the name when it's a stealthmin.

@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by Bawhoppen** [comment]
For once I agree with goof

**Comment by Iamgoofball** [comment]
@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by Shadowlight213** [comment]
@Iamgoofball except someone who is banned isn't coming back into the round usually

**Comment by Iamgoofball** [comment]
and?

@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by Shadowlight213** [comment]
@Iamgoofball There's a difference there as if they come back then they know exactly who the stealthmin is. That info is shown to bans so they can make an appeal.

**Comment by Iamgoofball** [comment]
What if I wanted to make an admin complaint because an admin kicked me intentionally during combat so that I would lose? If he was stealthminned then I can't complain due to having no name.

@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by Bawhoppen** [comment]
To be fair, if an admin kicks you they should have enough of a reason that they shouldn't need to worry about being identified.

**Comment by optimumtact** [comment]
This absolutely should go through.

**Comment by Iamgoofball** [comment]
@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by Iamgoofball** [comment]
@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by Iamgoofball** [comment]
@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by Jordie0608** [comment]
Stop spamming mentions and do the suggested change you nob.

**Comment by Bawhoppen** [comment]
No. Thats a dumb suggested change.

**Comment by Iamgoofball** [comment]
@Jordie0608 the suggested change completely undermines the entire point of doing this, so no

@Razharas @hornygranny @bs12-bot @Cheridan @RemieRichards @Shadowlight213 @MrPerson @MrStonedOne @paprka @paprika @god

**Comment by MrStonedOne** [comment]
No, Stealthmins are as stealthmin does.

Bans don't show it because they aren't coming back, but kicks should.

Make the change.

**Comment by Iamgoofball** [comment]
The entire point of this is so that you can't get kicked(which forces you to REDOWNLOAD THE RSC 90% OF THE TIME, AND WATCH AN AD TOO) without knowing who to bitch at.

**Comment by MrStonedOne** [comment]
Well. @Iamgoofball you can remain stickybanned until you fix that.

**Comment by optimumtact** [comment]
Thats a terrible way to act and I've revoked my patreon donation in protest.

**Comment by RemieRichards** [comment]
Gonna just say (said in the IRC) that I didn't read @MrStonedOne's commented right, looking at it in relation to the comments around it it actually looks Inverted, I only merged it because the code is ok, it's tagged as ready (ffs) AND I thought MSO was ok with it, when he was actually the opposite.

**Comment by Krutchen** [comment]
If you're wanting to meme kick goofball just make a "kick goofball" verb.
Can anyone actually explain though what the problem is with making stealthmin kicking show who the admin is? 
Aren't they stepping out of the stealthmin realm once they deliver the kick? 
By that point they know that there's an admin on, so the stealth part of stealthminning becomes irrelevent. The element of surprise is gone.
Why do those kicks need to be anonymous other than to make the stealthmin not accountable for their actions in that moment?

**Comment by Iamgoofball** [comment]
Did you just stickyban me because I was tired of getting kicked by admins for memes every 5 seconds with no way to figure out who it was so I can report them?

You can't be this petty.

**Comment by Krutchen** [comment]
That's where you're wrong, Goof.

**Comment by Miauw62** [comment]
le admons suk meem xd

**Comment by Shapsy** [comment]
>constantly shill your dumb PR's in ahelps by saying "OH BOY LOOK AT THIS HOT NEW MEME PR THIS IS GONNA BE CONTROVERSIAL"
>complain when you get kicked

**Comment by Bawhoppen** [comment]
I admire goof for how he plays you all like fiddles

**Comment by peoplearestrange** [comment]
:+1: Banned players will/need to find out the banning admins name for ban appeals anyway, this simply speeds up the process.

I don't see an issue.

**Comment by Shadowlight213** [comment]
@peoplearestrange this isn't for bans. This is for kicks. Bans already show the actual name of the admin who banned you.

**Comment by tedward1337** [comment]
@peoplearestrange you're silly

**Comment by peoplearestrange** [comment]
Oh....

**Pull request merged**
