### PR TITLE
Buffs Heretic's Raw Prophet slightly, and gives it a funny lil attack animation 

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

https://user-images.githubusercontent.com/51863163/153793318-2291d21d-81cd-4c91-8814-a72dd7e9ba19.mp4

- Buffed the Raw Prophet's health by 15. 
- Decreased the sight range of the raw prophet, and allows them to toggle between expanded range and normal range. 
- Makes Raw Prophets drop their component parts on death, allowing a Heretic to collect and rebuild them. 
  - Also makes all heretic monsters drop gibs on death instead of vanishing. 
- Raw Prophets now gain an attack bonus for hitting a target consecutively. 

## Why It's Good For The Game

Raw Prophets are the first 'cool' summon Flesh Heretics can do and they're both mediocre and hard to use as a player.

Their massively increased range caused a ton of lag and often got the player killed instead of helping due it being harder to see people close up. 

On top of that, they were veeery fragile - a few laser hits or toolbox hits and they're gone, and you don't get anything in return. 

- Buffing their health a tiny bit should ensure they stick around and help a bit more
- Lowering their range and allowing the user to toggle them should make it less laggy, and more pleasant to use, while not entirely sacrificing its purpose (of being able to see people very far away)
- Dropping their components on death make it a not complete lost cause when it dies
- The attack bonus is a way of encouraging prophets to pick targets and tunnel them down, using blind in conjunction. 

By making them a bit stronger, hopefully heretics have more reasoning to go for them, and ghosts (players) have more reason to want to jump into them when one is made. 

## Changelog

:cl: Melbert
expansion: Raw Prophets now have a funny little attack animation.
balance: Raw Prophets have been adjusted slightly. They now have more max health, a slightly lower sight range (but the ability to toggle it on or off), drop all their component parts on death, and do more damage for every consecutive attack on a target they do. 
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
the path to goonlings

**Comment by carshalash** [comment]
MASSIVE QOL change, good work smellbert.

**Comment by MrMelbert** [comment]
https://streamable.com/jfc9c6
added a walking animation too

**Comment by StoneMason** [comment]
[should have 1% chance on hit to play](https://youtu.be/RYnFIRc0k6E?t=61)

**Review by Twaticus — APPROVED** [review]

**Comment by Toastgoats** [comment]
Speen

**Pull request merged**
