### PR TITLE
You can now craft a singularity hammer using all nine anomaly cores and the supermatter.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

You can now craft a singularity hammer using all nine anomaly cores and the supermatter.

## Why It's Good For The Game

Discord_Rvq2vyhZqR

Also

Discord_ZaKC0N5uAj

## Changelog

:cl:
add: You can now craft a singularity hammer using all nine anomaly cores and the supermatter.
/:cl:

### CODE REVIEW

**Comment by Donglesplonge** [comment]
another out of the park goof PR, speedmerge

**Comment by Striders13** [comment]
doesn't it kinda suck?

**Comment by Holinka4ever** [comment]
Question, how you gonna make it, if every moment sm pulling people and items toward to it?
What about instead of lame crafting menu, you throw cores instead?
They giving funny quotes into chat, and final one removing sm, to turn it into hammer?

**Comment by carlarctg** [comment]
WHAT WOULD YOU MAKE?

- One self-recharging instagibbing singularity rifle (4 cores)

- One bulky hammer coded in 2013 that pulls people near you once every 15 seconds (9 cores and supermatter)

**Comment by YuliceTheDruid** [comment]
Yeah what Carlarc said

**Comment by Iamgoofball** [comment]
I don't question the boss's wisdom

**Comment by zartura** [comment]
I get the joke, but honestly the Supermatter Sword would make more sense.

**Comment by Jacquerel** [comment]
historically merely linking oranges saying something (even in the form of a design document, which this isn't) does not on its own suffice for "is this good for the game" unless he personally is going to step in and merge it so I'm still gonna need you to fill that in

it's not enough that oranges said so you also need to personally believe in the idea and be able to explain why it's good

**Comment by Eronymun** [comment]
I love these chaos emerald calamity crafting recipe super fetch quest items, like the regel condor.
Though it should totally be a super matter sword.

**Comment by CCC23** [comment]
> historically merely linking oranges saying something (even in the form of a design document, which this isn't) does not on its own suffice for "is this good for the game" unless he personally is going to step in and merge it so I'm still gonna need you to fill that in
> 
> it's not enough that oranges said so you also need to personally believe in the idea and be able to explain why it's good, which neither of these images do

this is good for the game because it makes me want to collect all of the chaos emer I mean anomoly cores

**Comment by LSommers** [comment]
Combine all the cores with a toy singulo to get a singularity engine that actually fucking words WHERE IS MY SINGULO CODERS IT'S BEEN YEARS-

**Comment by Loafin34** [comment]
too expensive... just do SM and vortex core and banhammer (as the basis for the rod). banhammer is relatively hard to get, as it's solely from adminbus ruin and abandoned crates. also, funny.

**Comment by adamkad1** [comment]
When are we going to get an item that does not allow cores bought in cargo?

**Comment by Kiromaka** [comment]
A gun that can kill nar-sie costs 4 cores, while a useless hammer that does no damage and pulls people to you, with no real stun and with 19 seconds CD - costs 9 and SM. No one will ever make it, either it should be a more usefull weapon, like SM sword, or cost less, since 9 cores and SM is too big of a price, for a weapon no one ever buys on wiznerd.

**Comment by CRITAWAKETS** [comment]
yeah but have you considered that the hammer is fucking awesome

**Pull request merged**
