### PR TITLE
Removes the shitty Red Faction poster.

### PR DESCRIPTION
**Pull request by theOperand**
What it says on the tin.
Its blurry, it's a shitty reference, it's copyright infringement. R E M O V E

### CODE REVIEW

**Comment by Core0verload** [comment]
Copyright infringement? Why do we care?

**Comment by Anonus** [comment]
It's a crap poster anyway.

**Comment by Supermichael777** [comment]
looks like someone didn't read the code comments

**Comment by bgobandit** [comment]
change the constant too

**Comment by bgobandit** [comment]
you need to either change the constant or add a new poster in its place

**Comment by Nienhaus** [comment]
Here is something to replace it with.
untitled
(Btw I made that shitty RF poster :D)

**Comment by Miauw62** [comment]
>looks like someone didn't read the code comments

\>effort

also nien what do you suggest for name/desc?

**Comment by Miauw62** [comment]
also how the fuck do i change the order of sprites in a dmi

**Comment by Incoming5643** [comment]
d10_icon
-list(name = "- Space Cube", desc = " Ignorant of Nature's Harmonic 6 Side Space Cube Creation, the Spacemen are Dumb, Educated Singularity Stupid and Evil."),

would close #11871 if we used this one, and I get to make a motherfucking Time Cube joke, which is a bonus.

---

I don't think there's any way to easily change the order, that said I'm pretty sure the order affects nothing beyond being a little harder to read for people

**Comment by Miauw62** [comment]
going to make a new pr

**Comment by Iamgoofball** [comment]
@Incoming5643 why cant we have both

**Pull request closed without merging**
