### PR TITLE
Refactors component signals to properly register for specific signals

### PR DESCRIPTION
**Pull request by ninjanomnom**
This changes how signals work so that datums keep track of what components registered for what signals. This means it's easy to tell when a signal would have no one listening and to skip the whole process.

Additionally this means components can register for signals on not just their own parent, making the signal redirect component obsolete for use inside other components. It is still useful for non components which want to listen to a signal. Uses in existing components have been converted.

Global signals are now just signals registered on `SSdcs`.

The amount of `_SendSignal()` calls during init have shot way down as a result of all this.
Before: 180046
After: 27

This whole refactor is basically a cost trade of memory for improved performance and functionality. We do get slightly better memory cost for components which would potentially use many redirect components but we didn't have too many of those.

### CODE REVIEW

**Comment by ninjanomnom** [comment]
It's been testmerged a few rounds and will stay longer but there doesn't seem to be anything wrong.

**Comment by ninjanomnom** [comment]
Apparently not, there's a runtime that fairly reliably comes up in live rounds but I cant duplicate it in local testing. Going to add a commit for debugging where that's coming from.

I was able to be on the server when it happened but it deal with itself in moments so I think it's some qdel issue.

**Comment by ninjanomnom** [comment]
It was an issue with signal registration not checking if it was already registered in cases where it's overriding/getting applied multiple times like in equipment listening for their wearer signals. This should be good to go now.

**Comment by ninjanomnom** [comment]
Ok well, that was *an* issue but apparently either not the one causing the issue or not the only cause of it. I'm keeping the debug in now until it goes for a day without that runtime. I still can't replicate it locally.

**Comment by ninjanomnom** [comment]
Ok I found one reproduction method with the two handed spear and was able to deal withit. Now let's hope that was the last.

**Comment by ninjanomnom** [comment]
There haven't been any runtimes related to this except for one that happened because shuttle throwing was merged and hadn't had its signal registration updated.

**Comment by Jared-Fogle** [comment]
This adds a billion warnings that didn't used to be there

image

**Comment by Jared-Fogle** [comment]
SEND_SIGNAL adds a bunch of warnings that didn't exist before.

image

**Comment by ninjanomnom** [comment]
Wrong pr and also update your byond version

**Comment by Jared-Fogle** [comment]
Downgraded to 1416 to stop the crashing, that's probably why

**Pull request merged**
