### PR TITLE
Fixed santa, more presents

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Santas regen bag didnt work, he could open gifts himself and couldnt see what was in them. All fixed.
The rate of present regen changed from rand(30 SECONDS, 60 SECONDS) to a flat 30 seconds.

## Why It's Good For The Game
Santa

## Changelog
:cl: Skoglol
fix: Santas bag should once again regen gifts. A bit faster than before, too.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
What's with that unused spawn gifts spell though. Ain't santa supposed to have that?

**Comment by boodaliboo** [comment]
here come santa hahah santa pacman funn haha i like pac he eat the gobling hosts and thda pellet

**Comment by kriskog** [comment]
The santa spell was changed to refilling bag, the spell that remains only spawns the toy gifts

**Comment by AnturK** [comment]
That trait could use name change.

**Pull request merged**
