### PR TITLE
Adds Perfectly Ordinary Food Truck

### PR DESCRIPTION
**Pull request by DaCoolBoss**
## About The Pull Request
Adds a food truck.
Food truck map
People wearing stripy shirts get FREE tacos!

Also, adds a team of MI13 fugitive hunters. There's 3 in a team, and one is pre-equipped with a cunning disguise.
## Why It's Good For The Game
So the primary intent here is making a fugitive hunter team that operates stealthily instead of directly. They have less direct combat power than other hunters, but they have a few things that help them infiltrate the crew and assassinate the fugitives.

All agents are issued a makarov, a suppressor, a spare clip of 9mm ammo (20% chance to be a subtype), a random melee weapon (flash, e-dagger or combat knife), and a random low-level syndicate gadget (c4 brick, codespeak manual, freedom implant, etc), and a pair of zipties. Every agent also gets a agent ID.

Shuttle is equipped with surgery tools (good for plastic surgery), clothing vendors (good for getting disguised), and a bunch of computers for cameras and vitals monitors. Spare cyanide pills and 9mm ammo is provided, as is a single space suit. As an added bonus, you're opereating out of the back of an old food truck giving you bulletproof cover for your operations. Spare food is provided, a functional kitchen is not.
## Changelog
:cl:
add: Ghost role food truck merchants may occasionally turn up at the station.
add: Adds a new fugitive hunter type, MI13 secret agents.
/:cl:

### CODE REVIEW

**Comment by dalmationer** [comment]
I like this. Is there a non-'antag' version too, though? I think it would be interesting if you couldn't tell for sure if it was a baddie or not.

**Comment by DaCoolBoss** [comment]
I don't think it's got enough fun in it for a non-antag ghost role, maybe in future a whiteship could be based on the design I suppose.

**Comment by Loafin34** [comment]
what if you could deploy a food portal that can send food to the station? that'd be a nice ghostrole.. and the people aren't compelled to eat the food if it's poisoned or too powerful, so it's dynamic! also, please let it connect to the whiteship airlock, i don't think many people are willing to spacewalk for some tacos.

**Comment by DaCoolBoss** [comment]
It can, same as the other hunter ships. The second screenshot is docked at the aux port of metastation.

**Comment by ATH1909** [comment]
I assume they come with sunglasses?

giving them a camera + an advanced plastic surgery disk would be nice, if you want them to have plastic surgery as a significant gimmick. it would let them imitate specific people.

**Comment by DaCoolBoss** [comment]
Yes, they start with sunglasses. I did think about including that disk, but decided against it because it might be a little too powerful combined with the agent IDs. Same reason is why they don't get chameleon clothes.

If they struggle to be viable in live play however giving them that disk is one of the first buffs they'll get.

**Comment by radarseas** [comment]
giving them an unlimited codespeak book is going to mess with so many syndicate antagonists, especally the unlimited varient, it might be a better idea to do something similar to pirates and just have them inherrently, know it.

Else these guys are getting killed for gamer loot every time they spawn, without even including that they straight use the syndicate channel in their headsets.

**Comment by Rhials** [comment]
Be sure to update your master and give a special arrival message that uses the system implemented with #84148! I'm sure you can come up with something totally-not-suspicious-at-all that fits from a flavor perspective.

**Comment by DaCoolBoss** [comment]
Alright, I got something.

**Pull request merged**
