### PR TITLE
Each nuke (and clown) op now spawns with both a syndicate tablet AND a pinpointer

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Nuke ops now spawn with pinpointers again (their syndicate tablets have been moved to their backpacks).

Clown ops now spawn with syndicate tablets (the pinpointers that they had before this PR will still spawn in their pockets).

The name of the syndicate pinpointer item (that each nuke op and clown op spawns with) has been changed to instead be "nuclear authentication disk pinpointer", so as to make the function of the device more clear. Its description has received some clarifications as well.

## Why It's Good For The Game

image

Listen, zxaber, I get it, tablets are cool and you want people to use them more. FORCING ops to use tablets in order to locate the disk is not the way to go about this, however. Nuke op is a rare role to get to play as, so trying to force the usage of niche (as a crewmember, anyway) mechanics in order to not fail horribly/get laughed at is just making our fluke op rate higher. Even in the future, when tablets become commonplace, I'd still prefer nuke ops to have both a tablet AND a pinpointer, for those newer players who haven't dived into understanding the wonders of modular computing yet (or, worse, for those who assume that nuke ops get tablets just because everyone else (in this future world) gets them, and not because they NEED them to find the disk).

If a nuke op is an experienced player who knows what they're doing, they can decide to use their tablet instead of their pinpointer to save space. For the less-experienced nukies, the pinpointer is much simpler/much more intuitive to use (you just have to press a single button).

## Changelog
:cl:
balance: Each nuke (and clown) op now spawns with both a syndicate tablet AND a pinpointer.
tweak: The name of the syndicate pinpointer item (that each nuke op and clown op spawns with) has been changed to instead be "nuclear authentication disk pinpointer", so as to make the function of the device more clear. Its description has received some clarifications as well.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
choice > forcing things down people's throats

dont want the pinpointer? just ditch it

**Comment by zxaber** [comment]
The point about getting people to use the tablet is that it generates new ideas for ops/syndicate software.

Modular computers have been in a slump for as long as I've been playing. No one uses them except engineering (and, only recently, cargo), because meaningful programs haven't been implemented yet. The syndicate repo has been a ghost town of obscure-as-hell apps that no one ever bothered to use, and the way we fix that is giving people reason to use the tablet in the first place.

**Comment by trexter555** [comment]
just add something to the nukie spawn/flavor text in 50 size bolt font, that their tablet can be used to track the disk once on the station z level

**Comment by ATH1909** [comment]
> The point about getting people to use the tablet is that it generates new ideas for ops/syndicate software.

I'm getting real https://github.com/tgstation/tgstation/pull/49899 vibes from this. That PR was made in March 11th, by the way, and still nobody's gotten up off of their ass to rework techwebs (sure, someone SAID that they would, but it's been months and we still don't have anything). That strategy didn't work/isn't working for techwebs; what makes you think that it'll work for tablets?

> Modular computers have been in a slump for as long as I've been playing. No one uses them except engineering (and, only recently, cargo), because meaningful programs haven't been implemented yet. The syndicate repo has been a ghost town of obscure-as-hell apps that no one ever bothered to use, and the way we fix that is giving people reason to use the tablet in the first place.

That's not mutually exclusive with letting ops have both pinpointers AND syndicate tablets. You can put a bunch of utility stuff (like the cyborg tracker or the (backup) pinpointer program) in the tablets, but something as important as the disk pinpointer should be its own separate item to make it more obvious for newer players/players who just want to shoot people with fancy guns and not worry about using gimmicky tablets.

If anything, making the pinpointer a separate item from the syndicate tablet is going to make syndicate tablet programs even MORE awkward to use, because you can't use them while you're using the pinpointer program (unless you can run the pinpointer program in the background and still have the tablet's sprite display the arrow?).

**Comment by Tharcoonvagh** [comment]
I love yelling at other ops to use their tablets and NOT THROW THEM OUT INTO THE ICE WASTES GOD DAMMIT

**Comment by Angustmeta** [comment]
>Assault pod in

>Spend first seconds making the tablet slowly scan for the disk, with combat happening around me


>Luckily I have 1000 hours and can figure out I need to click "nuclear authentication..."




I don't think having both would be the solution, but the program itself could use tweaks.

**Comment by nemvar** [comment]
I would really prefer if we made the tablet work better instead of returning to the pinpointer. There are some pretty decent suggestions coming from this thread, please implement them instead.

As for visual clarity. Just rename the modular computer to 'Modular Syndicate Pinpointer' and make the screen white in the turned off state so it looks more like the original sprite. Should result in less confusion for the oldf***

**Comment by ExcessiveUseOfCobblestone** [comment]
above

**Pull request closed without merging**
