### PR TITLE
Fix for #4219. Variant 2

### LINKED ISSUE #4219: Gibbing people with an ID in a PDA causes the ID to drop
If you have a PDA with an ID in it on you when you get gibbed, that ID drops. This happens with each PDA with ID.
I think it's intended due to PDA bombs, but it's odd to watch.

### PR DESCRIPTION
**Pull request by bear1ake**
How about fix ID-card dropping by not dropping it when PDA destroyed?
Fixes #4219

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
No, otherwise you can lockdown all access-changing across the station by stealing the Spare ID, then detomaxing the HOP and the Captain

**Comment by bear1ake** [comment]
@Dorsisdwarf, how about wallet?
Deleting/Destroying wallet with ID-card not drop it...

**Comment by RandomMarine** [comment]
Captain's PDA cannot be detonated, Dorsisdwarf.

**Comment by Cheridan** [comment]
This is a cleaner fix than #9655, and Detomaxes are so bad/unused that I don't think this code is necessary any more.

**Pull request merged**
