### PR TITLE
Add liquid dark matter to bluespace bananas

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

Bananas are a nutritious [source of antimatter](https://www.symmetrymagazine.org/2009/07/23/antimatter-from-bananas) in real life and this would be cool to have in game by giving bluespace bananas the `Liquid Dark Matter` reagent. (LDM)

For those not familiar with what LDM does, it has a gravity pull effect that sucks everything to the tile it's used on.  The gravity pull radius is:  

_(T is for tile and u is for units)_
- 2T=8u
- 3T=18u
- 4T=32u
- 5T=50u
- 6T=72u 

Since I gave bluespace bananas 20% LDM, that means at **max** potency it can reach 3 tiles radius.  If you use it with omega weed, then you can boost it to 6 tiles.  LDM will not activate on it's own and needs to be combined with the `Exothermic Activity` trait that needs ~5% nutriment.  This leaves 75% room for other chemicals.

## Why It's Good For The Game

Trivia fact:
> _“The average banana produces a positron roughly once every 75 minutes.”_

So initially I wanted to add this as a meme, but after code diving I realized this would lead to some interesting combos:

- Meth explosions with omega weed
- The `Hypodermic Prickles` trait can be used to inject chems or poison into nearby people
- The `Gaseous Decomposition` trait can be used to gas a room and suck everyone inside

I'm sure other people can come up with more combinations.

## Changelog

:cl:
add: Add liquid dark matter to bluespace bananas.
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
liquid dark matter is made of three things that are in the roundstart chem dispenser so I wouldn't worry too much about balance concerns about production of the chem. Does this detonate on harvest?

**Comment by timothymtorres** [comment]
> Does this detonate on harvest?

https://github.com/tgstation/tgstation/blob/efc11d538287af689cb006785faa1acfe08717b8/code/modules/reagents/chemistry/recipes/pyrotechnics.dm#L259-L280

I'll find someone willing to test it but it should only activate if the plant has the `Exothermic Activity` trait and has enough nutriment available.

**Comment by Iamgoofball** [comment]
liquid dark matter is not, in fact, in the chem dispenser

**Comment by the-orange-cow** [comment]
I could joke about how the true botanists choice would be to add plasma as a reagent so botanists can make LDM the sweaty way, but that actually might lead to balance issues.

**Pull request merged**
