### PR TITLE
The bar shuttle's buckable bar stools are now buckleable bar stools.

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting12
spellcheck: The bar shuttle's buckable bar stools are now buckleable bar stools.
/:cl:
Emergency bar shuttle's buckable bar stools are now buckleable bar stools.

### CODE REVIEW

**Comment by Jalleo** [comment]
squash commits please.

**Comment by BeeSting12** [comment]
how do I do that?

**Comment by MrPerson** [comment]
You don't need to squash, maintainers have a button to do it automatically

**Comment by Bawhoppen** [comment]
The spelling errors are always the best part

**Comment by BeeSting12** [comment]
i kinda wanted to leave it in because it gave me a good laugh every time i saw it

**Comment by Niknakflak** [comment]
as the author of these
Its intentional
its buckable

**Pull request merged**
