### PR TITLE
Forgot to specify files to check in check grep

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

Title
## Why It's Good For The Game

check greps working is good

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
@Mothblocks closing this because of your dmlua pr

**Comment by Mothblocks** [comment]
its not dm-lua :(

**Comment by Mothblocks** [comment]
that one only concerns maps. i will not be doing anything with code for a very long time. please reconsider

**Comment by ZephyrTFA** [comment]
> that one only concerns maps. i will not be doing anything with code for a very long time. please reconsider

making me maintain my checks, smh

**Pull request merged**
