### PR TITLE
Basilisks are now gold core spawnable: Cyberboss likes me this time edition

### PR DESCRIPTION
**Pull request by ghost**
weaker than goliaths, which, okay fair enough that's too strong but these should be fine. Xenobio is here for exotic creatures but the roster is so small it feels like you get the same garbage every time. Lets spice it up, yeah?

### CODE REVIEW

**Comment by KorPhaeron** [comment]
These are pretty powerful to have as a standard xenobio mob, and it kind of cheapens the whole lazarus thing if scientists can just safely farm them at home

**Comment by Armhulen** [comment]
I could cheapen the lazarus if you'd like, they're on the strong side but there are better choices.
xenobio mobs have:
xenos
changelings
giant spiders (i'm you, xenos, but better)

**Comment by KorPhaeron** [comment]
This lets RnD farm its own diamonds as well

**Comment by ExcessiveUseOfCobblestone** [comment]
make a subtype for xenobio that removes the diamond loot.

**Comment by Armhulen** [comment]
if you max out xenobio a small amount of unrefined diamond is fine

**Comment by SgtxRootbeer** [comment]
using gold slimes and walls, one can make a magicarp with a door creation bolt, allowing for infinite materials, of all types. this is fairly lackluster in comparison.

**Comment by XDTM** [comment]
Far easier than getting the right mob _and_ the right spell roll

**Comment by Incomptinence** [comment]
Considering goliaths strong when their stun takes a thousand years and is avoided with any movement.

Thinking a mob with ranged cold based slowdown is a less lethal addition to gold core bombing. 

Jeeze Louise.

**Comment by Armhulen** [comment]
wwwww.    N.      

Incomp, player controlled goliaths are pretty disgusting

**Comment by jughu** [comment]
@KorPhaeron are you stoopid or something THEY CAN ALREADY GET INFINITE MINERALS TROUGH MAGICARP

**Review by Cyberboss — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
"if you max out xenobio a small amount of unrefined diamond is fine"

I'm not really a fan of bypassing different departments being nearly forced to cooperate, especially when this is literally the best material. T3 Xenobio machine + T3 Recycler + T3 Proto turns this into a considerable amount, and that's not including the fact you can just keep spawning them.

If the purpose is to fill the roster, I don't really see why there's such vehement defense against it.

>@KorPhaeron are you stoopid or something THEY CAN ALREADY GET INFINITE MINERALS TROUGH MAGICARP

Do you know how long it takes to hit those higher material doors? FOREVER, and that's with a fireaxe!

But yes magicarp are stupid you aren't telling one anything new :^)

**Comment by jughu** [comment]
barely takes 5 seconds with a AEG

**Comment by Bawhoppen** [comment]
Yea honestly it needs to have that nerfed

**Comment by Armhulen** [comment]
Alright I'll remove it

I'd or removing magicarp from the pool but that was closed

**Comment by jughu** [comment]
because people prefered powercreep

**Comment by XDTM** [comment]
I suggest to expand on spiders, spiders are always cool

**Comment by Supermichael777** [comment]
basiliks will wreck people. their shooting is going to be cancer in the long straight station halls.

**Comment by Armhulen** [comment]
they really aren't THAT strong guys get good

**Comment by jughu** [comment]
HEY MICHEAL YOU KNOW WHAT ELSE WILL WRECK PEOPLE INSTA DEATH BOLT CARPS

**Comment by KorPhaeron** [comment]
@Armhulen don't forget they take half damage from most of securities weapons

And yeah I guess a lot of this is just a gut level sense wrong from me along the lines of what @ExcessiveUseOfCobblestone said

They're getting their own materials, they're getting mining monsters, and they already got minings golems. Everything seems to end up in RnD eventually

**Comment by jughu** [comment]
MAGICARPS ARE ALREADY THE BEST COMBAT UNIT
MAGICARPS ALREADY CAN GET INFINITE MATERIALS
MAGICARPS CAN INSTA HEAL PEOPLE FUCK CLONING
MAGICARP GOD

**Comment by KorPhaeron** [comment]
Yeah and they're the holy grail you can't get elsewhere, outside of the stupid door thing that I think I made an issue report about 2 years ago they're not poaching content from other departments

**Comment by KorPhaeron** [comment]
Maybe you're right though its not a big deal it wouldn't be the end of the world to add them

**Comment by ExcessiveUseOfCobblestone** [comment]
Is a feature _really_ good if it doesn't make its way to science?

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
