### PR TITLE
Toxin Filter symptom no longer heals absurd amounts of damage

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: The Toxin Filter virology symptom now heals 4-8 toxin damage instead of 8-14.
/:cl:

For reference, the damage converter symptom does 1-2 toxin damage whenever it successfully heals, so this was healing between 4 and _14_ times the damage the damage converter symptom could.
This means it'll only heal 2 to 8 times the damage damage converter could do.

With #15963 it'll heal -3 to 8 times the damage damage converter could do(based on number of damaged limbs)

### CODE REVIEW

**Comment by lzimann** [comment]
Sounds better than removing the stacking tbh

**Comment by ChangelingRain** [comment]
As an aside; if #15963 gets merged, I'll increase this to 5-9 damage healed, high enough it'll heal five hurt limbs decently but at 6 it'll be a little overwhelmed.

**Comment by ShadowDeath6** [comment]
I'd be up for lowering it even more, maybe like 2-4 toxin damage so it actually takes time to heal, even with 3 healing virsuses.

**Comment by LanCartwright** [comment]
Please consider this instead: https://github.com/tgstation/-tg-station/pull/15873

**Pull request merged**
