### PR TITLE
Blind people can no longer use computers and newscasters

### LINKED ISSUE #58936: Blind people can use the SecurEye app on modular computers
## Reproduction: Use the SecurEye app while blind 
image

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This was split off of https://github.com/tgstation/tgstation/pull/65668 into its own separate PR.

Fixes https://github.com/tgstation/tgstation/issues/58936

An optional `INTERACT_MACHINE_REQUIRES_LITERACY` bitfield has been added to machinery.  If this is enabled it checks if a person is able to read as a requirement to use the machine.  Right now the `can_read` proc doesn't do much other than check for blindness, but in future PRs it will be more robust to check if someone knows how to read.

Blind people can no longer use:

- All computers
- Newcasters

## Why It's Good For The Game

Blindness has always been one of the most lethal status conditions for a player to have.  

This has been the case since it was implemented sometime [before 2008](https://github.com/Glloyd/Pre-Open-SS13-Host-Files-and-Source/blob/32ba79de7e56ec93f0849e3a4532a5b7c74b59b2/ss13-40.93.2-base/ss13-40.93.2-base/mob.dm) as one of the first disabilities in the game. It is not just a black HUD overlay, there are several existing code checks that restrict a blind character's actions.  These restrictions were made to further punish players severely if they had the _stupidity_ (welding without a mask) or _misfortune_ (stabbed in the eye by the clown) of acquiring the status condition in a variety of ways.  This didn't affect balance too much because... **it was curable**.  There were half a dozen different methods to fix it and nobody seriously was expected to try to play while blind.  It was designed to be temporary!

With that in mind, I thought it would be cool if I could expand the blindness code in my original [Paper DLC PR](https://github.com/tgstation/tgstation/pull/65668) to use for my illiterate quirk.  The problem was that there was a lot of consistency issues with blindness code that I attempted to resolve.  What fun is an illiterate quirk if it only stops you from reading newspapers and books?!  It would be silly and pointless so I set out to make it difficult by restricting more stuff.  People who don't know how to read and people who cannot see, results in the same literacy checks in the code.  Both illiterate and blindness use the same `can_read` proc that is used to read and write which means... 

They are identical!  Surprise surprise!!!

I received an overwhelming positive response for making a new quirk that had ALL the restrictions of blindness EXCEPT the vision loss.  

chrome_W9d5ipPTNk

Yet when I was forced to split my changes into separate blindness PRs they got the opposite reception:

chrome_JhbYoqB5mo

- #66285
- #66287
- #66291
- #66290

The cherry on top is that several people were complaining about restricting certain items to blindness when those items already had blindness restrictions for years. (cough health cough analyzers cough)  This is pretty amusing to me since it shows that:

1. People have a knee jerk negative reaction to anything removed/nerfed
2. People will have the above reaction even if they have never experienced it or used it
3. People will have a positive reaction if you are adding something "new" to the game

## Changelog

:cl: timothymtorres, TheBonded
balance: Blind people can no longer use newscasters or computers. 
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Damn, this PR takes soo much from blind people.

Crew monitors, tram console, cargo console, department orders, chef orders, RND console, genetics, virology, holodeck, slot machines, shuttle consoles... 

Really hurts.

**Comment by Striders13** [comment]
Let blind people have at least SOME gameplay lol

**Comment by Time-Green** [comment]
Have you actually played a round with blindness? Because I've played about 30 from beginning to end
It's already really difficult to function in a job at all with blindness, you're just making sure people can't play with it at all

I'm just going to list a few jobs that you're killing completely that previously still could be played with some creativity: paramedic, chemist, roboticist, scientist (circuits, research), geneticist and bartender. Can't order anymore as cargo tech, you'll have to beat the vendor for seeds as botanist etc

What is your actual plan with this? Because I'm not really convinced by the "Allowing future features to have more depth". I'd rather you add some fun but challenging alternative methods to play these jobs, like Medical Doctors where you can examine people with your hands, can use the little hammer thing to measure braindamage and have an actual decent use for the stethoscope.

**Comment by Zytolg** [comment]
> Damn, this PR takes soo much from blind people.
> 
> Crew monitors, tram console, cargo console, department orders, chef orders, RND console, genetics, virology, holodeck, slot machines, shuttle consoles...
> 
> There goes half the jobs you can do
> 
> Really hurts. Hardcore random will be very unfun with this.

Melbert hits the issue on the head here. To reiterate, **this makes many jobs unplayable.**


> Allowing future features to have more depth.

No. This isn't future proofing. Even if this isn't intended as such, this becomes destroying an aspect or mechanic of the game to the degree that someone in the future has to fix or provide a solution to it. If a future feature is going to alter how Blind People interact with **Profession Critical Aspects** of the game, then this change should be made with that feature instead of before. Until then: there is no reason to do this; there is no benefit from doing this.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
I would much rather you approach this piecemeal than "literally all computers"

Start with newscasters and modular PCs to solve the issues at hand, if any egregious examples come up return later

**Comment by timothymtorres** [comment]
Updated "Why It's Good For The Game" section.

**Pull request closed without merging**
