### PR TITLE
Removes Gender Reassignment Surgery

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Gender swapping can be done in genetics already. Completely redundant and only serves to cause stupid adminhelps.

EDIT: Have any of you clamoring to keep this even used it in the last couple months or even the last year?

### CODE REVIEW

**Comment by Xhuis** [comment]
# ___NO.___

**Comment by as334** [comment]
:-1: I need to be able to head to medbay to become a QT Trap or Futa

**Comment by MMMiracles** [comment]
>removing the ability to turn people into trans with glass shards.
literally awful.

**Comment by Chocobro** [comment]
:-1:
having only one way of doing something really sucks a lot
especially when that one way is super fragile and takes a long time to rebuild

**Comment by WJohn** [comment]
Redundancy is fun! It gives options.

:-1: to this.

**Comment by xxalpha** [comment]
No why :-1:

**Comment by Supermichael777** [comment]
Considering that is is literally a permaban offense in the rules to do this nonconsentualy i think it should be cut. :+1:

**Comment by as334** [comment]
That's a policy problem not a code one.

**Comment by pudl** [comment]
Tbh it should be renamed "Sex Reassignment Surgery"

**Comment by PKPenguin321** [comment]
why

**Comment by Lumipharon** [comment]
being able to do something one way is not justification for removing other ways to do it.

>you can already power the station with singulo, lets remove solars and supermatter

I've literally never used this surgery, but there is absolutely nothing gained by removing it.

**Comment by Niknakflak** [comment]
:-1:

**Comment by Aloraydrel** [comment]
Tfw kor hates traps

**Comment by optimumtact** [comment]
:-1: just because there is two ways to do it doesn't mean it is bad

**Comment by ike709** [comment]
:-1: i must become a quasi-sexual bonsai tree

**Comment by GunHog** [comment]
:-1: Surgery can be done almost anywhere. Genetics can only do it in one place.

**Comment by Nienhaus** [comment]
:-1:

**Comment by Iamgoofball** [comment]
>Completely redundant and only serves to cause stupid adminhelps.

this is why we added Reject Adminhelps

**Comment by kyrahabattoir** [comment]
:-1:

**Comment by Incoming5643** [comment]
I've found changing your gender and then plastic surveying the name away is pretty effect at dodging someone trying to kill you provided you don't have neon green hair that no one else on the station has.

Plus since it doesn't change your genetics you can put yourself in the cloner and get backed up, wreck whatever hell you want, then when you die you'll come back as your original self with none the wiser. I used that tactic once, it was pretty hilarious shit.

**Comment by kyrahabattoir** [comment]
There are things that need to be ditched out of the game, this isn't one of them.

**Comment by bgobandit** [comment]
Gender swapping can be done in genetics but whether it's a bug or a feature you can no longer get UI+UE, just whichever one changes your appearance and not whichever one changes your name.

:-1:

**Comment by Core0verload** [comment]
:-1: I need a non-genetic way to defuse traps and punish traitors.

**Comment by Shadowlight213** [comment]
:-1: Not everyone has access to genetics.

**Pull request closed without merging**
