### PR TITLE
Replaces artificer MM with a projectile

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Artificers no longer have magic missile.
rscadd: Artificers now have a projectile that stuns for slightly longer than a taser and causes cult slurring. The projectile ignores cultists, constructs, and shades, moving through them.
rscadd: Shades can move in space.
rscadd: Artificers can now heal shades.
/:cl:

Projectile CD is 10 seconds, the weaken is 6 life ticks, the clur slur is 15, and it does 5 burn.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
:+1:x:100: on that 3rd thing

**Comment by Dorsisdwarf** [comment]
oo, nerfu

**Comment by Supermichael777** [comment]
rip asaultaficer

**Comment by Robustin** [comment]
>11% cult win rate
>Yea lets go ahead and the only combat ability for artificers with a meme shooter

Change #3 would be awesome but the rest of this would be awful for constructs.

"Yea fucking bullshit constructs OP as fuck" ~Nobody Ever

**Comment by TrustyGun** [comment]
yeah i gotta agree with robustin here, artificers are already really weak

**Comment by Bawhoppen** [comment]
artificiers aren't supposed to be for combat, they're for building up resources

**Comment by TrustyGun** [comment]
yeah but they should be able to defend themselves, 5 burn damage + 15 stamina is puny

**Comment by Zilenan91** [comment]
Make it 20 burn. On a 7 second cooldown this is fine.

**Comment by Robustin** [comment]
They already fit their role perfectly. They aren't build for combat and will die if they try to fight ANYONE, but in combination with other constructs they can play a field support role with stuns+repairs. 

That's why this PR baffles me. If we started having an artificer spam problem I could see it, but we don't.

**Comment by PKPenguin321** [comment]
i like that the new arty bolt charges faster and doesnt hit friendly cult
remove its damage and make the stun comparable to MM and id be ok with it, this is pretty much a nerf tho

**Comment by Lumipharon** [comment]
Artificers aren't designed for straight up combat - which is why they have weak mm to let them escape/support their butt buddies.

What is the point in replacing it with this shitty peashooter? What is the intended purpose of this?

**Comment by ChangelingRain** [comment]
No friendly fire; MM just targets a bunch of random scrubs, including cultists and other constructs, so its ideal use is to rush at groups of enemies, cast it, and run.
Which doesn't make much sense on what is theoretically a support construct, does it?

**Comment by Lumipharon** [comment]
it targets everything - there's no target limit, and constructs are completely immune.
Also stunning all your enemies so your friendly constructs can cuck them is exactly what support is.

**Comment by Robustin** [comment]
Yea but MM doesn't affect the other constructs, and while its annoying when it hits cult, it acts as a crucial "reset" button on fights where security tosses in a flashbang. I've never used artificers to "rush at groups" since they have 50hp and still provide crucial shards/shells, 3 laser blasts ends that. MM give artificers a purpose in combat though, which enhances the round for sacrifices players. Turning them into peashooters that poop out construct material just makes them wish they'd gone braindead.

**Comment by ChangelingRain** [comment]
It has a target limit of 6 targets.

**Comment by ChangelingRain** [comment]
Also, frankly, if your concern is it being too weak, that's really, really easy to fix.

**Comment by optimumtact** [comment]
I hate MM

**Comment by Lumipharon** [comment]
it's weak, and serves a completely different function from MM.
MM does not let artificers murder people (unless there's like 3 of them gangbangin nerds), it helps OTHER constructs murder people.

This proposed replacement is basically just a peashooter that will inconvenience people by making them drop their shit.

**Comment by GunHog** [comment]
If I had succeeded in making aimed projectiles for alien spit and wizard fireball, we could have made something similar for the artificer.

**Comment by ChangelingRain** [comment]
This will eventually return I really should make atomic prs(like I do ever)

**Pull request closed without merging**
