### PR TITLE
Bullied by admins roundend editted together by Hulkamania

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

glorious context: https://clips.twitch.tv/DeadPopularCourgetteOSkomodo-C34M5-tn_idWfH7a

It's a new roundend ogg that plays sometimes, very smol pr

## Why It's Good For The Game

This move from admins was nothing short of tear shedding and as roundends are full of good ss13 times of the past I think this short ogg fits well. If maintainers think otherwise then the pr will die and big sad but that's aight, just wouldn't be right NOT giving it a chance is my take

## Changelog
:cl: BluespaceA for their glorious voice, hulk for editting
add: There's a new roundend sound - bully2.ogg. Will it live longer than gondola bridge??
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
This was fucking hilarious, please merge

**Comment by Jared-Fogle** [comment]
we got permission from the guy btw

**Comment by tralezab** [comment]
He's a good sport
image

**Comment by Dorsisdwarf** [comment]
Don't we need to provide the source somewhere if it's being added to the actual codebase?

**Comment by tralezab** [comment]
I credited him in the changelog, also permission from the voice. Should be good!

**Comment by Dorsisdwarf** [comment]
> 
> 
> I credited him in the changelog, also permission from the voice. Should be good!

Didnt see the changelog because I'm pathologically alleric to reading them, 👍

**Comment by ArcaneMusic** [comment]
Everything lasted longer than gondola bridge.

**Comment by Mothblocks** [comment]
why not

**Pull request merged**
