### PR TITLE
 changed the hos shotgun icon

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About The Pull Request
new icon for the hos shotgun
## Why It's Good For The Game
I didn't like how the compact combat shotgun was just the combat shotgun without a stock so I slapped a grip on it.
## Changelog
:cl:
image: hos shotgun icon is now slightly different
/:cl:
image

to this

image

### CODE REVIEW

**Comment by DrDiasyl** [comment]
I think a more straight grip would've been nicer.

**Comment by projectkepler-ru** [comment]
> I think a more straight grip would've been nicer.

gotcha, I'll try. also feel free to post me any images that you'd like for me to use as reference

**Comment by projectkepler-ru** [comment]
image

**Comment by Wallemations** [comment]
I'll be honest I think it looks gross, kinda ruins the simplicity

**Comment by SomeoneYouProbablyKnow** [comment]
When reading the pr name i thought you were gonna add security colors or something. A grip is.. alright, but it's not like it's gonna make it much easier to idenityity. Still mono colored shotgun shaped thing.

**Comment by JohnFulpWillard** [comment]
bobux spritetainer says no

**Pull request closed without merging**
