### PR TITLE
Readds poutine

### PR DESCRIPTION
**Pull request by ArcaneDefence**
## About The Pull Request
Adds a crafting recipe and food item for poutine, which was mistakenly dropped off in https://github.com/tgstation/tgstation/pull/55160
Updates poutine's icon to no longer have the plate, keeping in line with other similar foods.

## Why It's Good For The Game
Refactors dropping features mistakenly is bad.
Lets me bully my canadian friends by throwing poutine at them in game if I want to

## Changelog
:cl:
expansion: Poutine can be made via the crafting menu in the misc foods category again.
/:cl:

### CODE REVIEW

**Comment by Greniza** [comment]
ought to be fix rather than add, no?

**Comment by ArcaneDefence** [comment]
> 
> 
> ought to be fix rather than add, no?

long hair don't care :dab:

**Comment by Sylphet** [comment]
A true hero of the great white north. Speedmerge ❤️

**Comment by CRITAWAKETS** [comment]
as a dumbass from quebec, i approve

**Comment by bluetshirtguy** [comment]
O Canada! Our home and native land!
True patriot love in all of us command.
With glowing hearts we see thee rise,
The True North strong and free!
From far and wide,
O Canada, we stand on guard for thee.
God keep our land glorious and free!
O Canada, we stand on guard for thee.
O Canada, we stand on guard for thee.

**Comment by Greniza** [comment]
> O Canada! Our home and native land!
> True patriot love in all of us command.
> With glowing hearts we see thee rise,
> The True North strong and free!
> From far and wide,
> O Canada, we stand on guard for thee.
> God keep our land glorious and free!
> O Canada, we stand on guard for thee.
> O Canada, we stand on guard for thee.

canada is not a real country, hippie! You are an AMERICAN!

**Comment by JohnFulpWillard** [comment]
the gravy just floats

**Comment by tralezab** [comment]
you love to see it.

**Comment by TheBonded** [comment]
as a canadian, I approve

as a spessman, I approve

new content good

**Review by Twaticus — APPROVED** [review]

**Comment by JJRcop** [comment]
As an american citizen with canadian heritage and dual citizenship with canada but living mostly in america and having most of his poutine experience in a theme park... I think my opinion doesn't count, but I've only wasted your time as much as all of the other "i'm canadian so this is good" comments. 🙂

**Pull request merged**
