### PR TITLE
Doubles shadowling population scaling

### PR DESCRIPTION
**Pull request by ghost**
This means that instead of a shadowling for every 10 crewmembers, there's a shadowling for every 20 crewmembers. I've seen ridiculous amounts of shadowlings succeeding from sheer number recently and this will hopefully amend the concerns that a lot of the playerbase has given me.

### CODE REVIEW

**Comment by Lijah99** [comment]
I support this balance change, from personal experience as a Shadowling.

**Comment by Zilenan91** [comment]
Wasn't the only reason there were so many slings is because everyone was so awful at the antag that they all just died 2 minutes in not knowing how to play.

**Comment by KorPhaeron** [comment]
@Zilenan91 

They've been buffed since then and (in theory) people have gotten a chance to learn the role a bit.

**Comment by Dorsisdwarf** [comment]
Doesn't this mean an average of 2 shadowlings on a standard 55-crew round, as opposed to the current 5?

**Comment by Lijah99** [comment]
Is 1 per 15 then a reasonable number?

**Pull request merged**
