### PR TITLE
removes confusing bitflag in research.dm

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
code: replaces a confusing bitflag in research code
/:cl:

replaces the DEPARTMENT_FLAG_ALL which existed so designs could be listed as something that works in any machine.

this should probably be checked a bit because I confused myself a bit while trying to fix this because the flag just confused me a ton

### CODE REVIEW

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
`(D.departmental_flags & ALL)` is true for all nonzero values of `D.departmental_flags`

**Comment by Qustinnus** [comment]
Really? Well fiddlesticks, any better way of comparing to check if ALL is on?

**Comment by SpaceManiac** [comment]
Omit the `&ALL` check entirely, leaving only `(D.departmental_flags & allowed_department_flags)`. If `D.departmental_flags` is ALL, this will be nonzero.

**Comment by Qustinnus** [comment]
thanks chad

**Review by Cyberboss — DISMISSED** [review]

**Comment by Qustinnus** [comment]
had me sweating that u merged this, I havnt touched gitkraken since spacemaniacs comment

**Comment by ExcessiveUseOfCobblestone** [comment]
what is this flag lol...

If it's meant to be built in any machine it should just have the `ALL` define or whatever it is.

For ones where it has `ALL | (department)`, have you lost functionality by keeping the department in?

**Comment by SpaceManiac** [comment]
> If it's meant to be built in any machine it should just have the ALL define or whatever it is.

already what this PR does, except for the problem at the places where it's checked

**Comment by Qustinnus** [comment]
github exploded for a good 5 minute when i updated this PR so I remade it lmao

**Pull request closed without merging**
