### PR TITLE
Removal of Kilostation

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Removes Kilostation from the game.
Since I know this is bound to be a touchy subject (the map has its fans, after all), I feel I need to explain the situation and why this decision has been made.

While working on mapping for TGStation, there's an inherent struggle between what's good for mappers, and what's good for coders. On the mapping side, we want as many maps as we reasonably can have in the repo. On the code side, every map added introduces a new layer of complexity for adding new features. While we're attempting to make strides in improving cooperation between the two teams so we can handle both many maps and lots of new features, in the here and now this means that we find ourselves limited in how many maps we can maintain at once.

With this in mind, we find ourselves in a conundrum when new maps come along. While it would be nice to accept everything new without needing to remove anything else, the above problems force us to stick to a limit. Via a fair amount of discussion on the maintainer team, this was set to 6 recently, which we reached when Northstar was merged, and meaning that a removal was required for any new maps.

As for why the decision was made to take Birdshot over Kilo, I believe it is better for us to have a map that has room to grow and an active creator. As much as I was personally a Kilo enjoyer, the map has consistently proven to be problematic for new code additions due to its scale, and it receives little maintenance outside of the bare essentials as a result. With all this in mind, it comes out as the obvious choice for removal in this case. Of course, nothing stops it from coming back in future if any of the above changes.
## Why It's Good For The Game
TL:DR: In order to keep the maintenance budget down, we need to remove a map for the sake of new blood, and in this case Kilo was the simplest choice.
## Changelog
:cl:
del: Kilostation has went back to its home planet. It served us faithfully for nearly 3 and a half years. May it rest in peace.
/:cl:

### CODE REVIEW

**Comment by celulamp** [comment]
No.

**Comment by JohnFulpWillard** [comment]
> No.

did you even have enough time to read the PR body?

**Comment by Slurge00** [comment]
i'd rather play kilo 100 times then play northstar or birdshot ever again. this sucks.

**Comment by DustanHache** [comment]
Icebox and tram can burn in hell. Kilo needs to stay for the sake of lowpop.

**Comment by Slurge00** [comment]
> Icebox and tram can burn in hell. Kilo needs to stay for the sake of lowpop.

real

**Comment by Addust** [comment]
kilo is hell in lowpop. the maint mazes mean that you can't fix when mice chew up the entire grid, and if you want to explore maint and get any maint loot? go fuck yourself. knife russians. spiders. CAT SURGEON, A RUIN MOB.

**Review by Cyberboss — APPROVED** [review]

**Comment by Jolly-66** [comment]
This is Pubby all over again

+1

**Comment by Thunder12345** [comment]
Kilo is old and tired, take it around the back of the barn like a lame horse

**Comment by BlueMemesauce** [comment]
Kilo is the only low pop map, we need it
Remove either meta or delta since they're basically the same map

**Comment by Rex9001** [comment]
Bye kilo, you will be remembered as that one lowpop map. I might miss you, but your successor does your job better

**Comment by Jacquerel** [comment]
The end of an era.

**Comment by Cheshify** [comment]
Didn't really get it at first, but I ended up really enjoying what Kilo had to offer. Sad to see it go, but I'm excited for the new maps and content.

**Comment by PowerfulBacon** [comment]
image
Using recommended github config

**Comment by JohnFulpWillard** [comment]
what is the x axis

**Comment by EOBGames** [comment]
> what is the x axis

looks to be votable pop, meaning birdshot is votable from 0 - 70-ish population

**Comment by Zytolg** [comment]
> [@github-actions ](/apps/github-actions)
> ** CI Suite / Run Linters (pull_request) ** Successful in 3m
> Required
> [Details](/tgstation/tgstation/actions/runs/4840892023/jobs/8626870943?pr=75039)

Yeah, highlights some stuff actually that might be worth talking about during the next community meeting. Kilo going on into infinity didn't exactly do it any favors, and Meta (though I think it's usually votable despite the config) being from 25 might be a little high?

**Comment by EOBGames** [comment]
> Yeah, highlights some stuff actually that might be worth talking about during the next community meeting. Kilo going on into infinity didn't exactly do it any favors, and Meta (though I think it's usually votable despite the config) being from 25 might be a little high?

in this case, we're talking about the codebase base config- they're different on the servers

**Comment by Zytolg** [comment]
> > Yeah, highlights some stuff actually that might be worth talking about during the next community meeting. Kilo going on into infinity didn't exactly do it any favors, and Meta (though I think it's usually votable despite the config) being from 25 might be a little high?
> 
> in this case, we're talking about the codebase base config- they're different on the servers

Figures, especially now that infinity pop is something we run

**Comment by the-orange-cow** [comment]
Ditch tram/birdshot/Northstar instead.

**Comment by Rex9001** [comment]
> All three newest maps should go because they are new

**Comment by MMMiracles** [comment]
if this pr gets enough downvotes we switch to meta

**Comment by CRITAWAKETS** [comment]
honestly? i'd ditch metastation, not only is it the oldest map (yes i know icebox is based on an older map, shut up) but it has been basically on life support and unmaintained (in terms of proper map changes) for a sizeable amount of time. There's so many unfinished reworks that meta's design nowadays is genuinely some of the worst out of the entire rotation.

**Comment by JohnHenryEton** [comment]
Birdshot really seems its too big for lowpop. Kilo is too small for high pop. Not a good problem. I really do think Kilo is better than birdshot for average to high pop. Don't merge Birdshot, please.

**Comment by SylvetteSylph** [comment]
i can't believe we as a society have taken tramstation over kilostation

**Comment by CliffracerX** [comment]
In a world where, as mentioned above, Icebox and Meta are unmaintained, nobody likes Tram except for Tram's creators, and Kilo's the only truly lowpop-focused map- this change does *not* make sense.  At least wait until there's a real successor for lowpop brought to the game- otherwise, you'll just have people rattling around Meta/etc maints and seeing other players maybe once per shift.

**Comment by LemonInTheDark** [comment]
Makes sense in the context of adding a fresh lowpop map in the form of birdshot, like you mention in the pr body.
It does make me sad, in the same way seeing doughnut or box go did. Kilo's a good map, and it had a lot of heart put into it.

That said, I am very thankful that I only need to do a lighting pass over 6 maps, and not 7, or like 12 if we never did stuff like this.
Kilo will rest in peace, he's earned it.

**Review by LemonInTheDark — APPROVED** [review]

**Comment by Youtubeboy139** [comment]
It's none of my business what TG does with its maps, however this affects downstream so here are my two cents. In the Birdshot pr it is explicitly mentioned that Metastation may be removed.

Screenshot_20230430_004712_Chrome

So why remove one that is beloved over one that is hated.

**Comment by san7890** [comment]
just because i jokingly said something (that i don't recall stating and denied stating) doesn't mean i ever wanted to do it. meta is still very valuable for technical reasons to have the ss13 "base" map (runtime is okay, but it's not the full ss13 map that has all the stuff baked in) without any quirky gimmicks, the template, etc. vanilla ice cream is good.

**Comment by san7890** [comment]
to me it was literally never on the table

**Comment by Youtubeboy139** [comment]
I put my two cents in, be I wrong or not, in the end it doesn't matter cause I have literally no power here and all it does is affect downstream which can be fixed by ignoring the Mirror PR popping up. Hate to see it go, but it's clear from the comments what the people want.

**Comment by san7890** [comment]
> > this affects downstream so here are my two cents
> 
> It's incredibly easy to re-add the map for downstream servers, especially since it's in the map depot now. You'll just need to shoulder the maintenance of it yourself. That being said depending on your server's method of updating (1:1 or every few weeks / months) it can definitely be a PITA -
> 
> maybe we should keep a list of every feature that is added that must be mapped in + their date of merge?

we already have this - though it hasn't really been touched lately https://github.com/tgstation/tgstation/milestone/72

**Comment by Addust** [comment]
docking a whiteship to kilo is a pain in the ass and as such i support its _**obliteration**_

**Review by Mothblocks — APPROVED** [review]

**Comment by mc-oofert** [comment]
yeah lads lets replace kilo with a way shittier map

**Comment by Jolly-66** [comment]
For the record the downstream "issue" isn't an issue at all
We mostly keep 1:1 with tg and people share equal ire with Kilo (not to mention one of the two downstreams almost NEVER uses Kilo due to their immense pop sizes)

Plus if it was truly desire, readding maps isn't hard and is fairly easy to do.

**Comment by RikuTheKiller** [comment]
> Icebox and tram can burn in hell. Kilo needs to stay for the sake of lowpop.

Tram and icebox can burn in hell, yes. Especially icebox. The SM, atmos and the grid all have problems. It's somehow even worse than kilo and that's an achievement. We need a better planet map, icebox just isn't it.

**Comment by zxaber** [comment]
> if this pr gets enough downvotes we switch to meta

Bet.

**Comment by DustanHache** [comment]
> > if this pr gets enough downvotes we switch to meta
> 
> Bet.

The current vote is 15:25 out of a total 40 votes against this PR. evidently there's a lot more people who like kilo than people who don't. enough that it's over 2/3ds majority.

**Comment by Jacquerel** [comment]
> The current vote is 15:25 out of a total 40 votes on this PR. evidently there's a lot more people who like kilo than people who don't. enough that it's over 2/3ds majority.

This is a pretty flawed summation, given that:
- Most people don't even read PRs in the first place
- More people are going to vote no than yes for removing virtually any map because they don't like change

**Comment by Thunder12345** [comment]
> 

Map complainers when a new map is added to complain about

**Comment by MMMiracles** [comment]
I'm personally trying to keep myself out of the argument of which maps should be axed since I have my own work in active rotation but Kilo being picked isn't any personal grudge or slight against the map itself or those who have contributed to its multiple times on the repo. The map itself is just rough to maintain due to the compact nature of it and as stated in the OP, there aren't exactly a lot of people jumping to volunteer updating it when actually needed.

I think its healthy to have an active rotation of maps with their own flair to prevent stagnation without making maintainability a struggle for those who volunteer to work on features or fix issues. New stations like Northstar or Birdshot needs time to get tweaked and players to get adjusted to their layouts and lessening the load of general map maintenance helps there. Believe it or not, before Meta got literal years of polish and tweaks between Metacide and countless additional contributors, those initial months of "box or riot" and suicide hoplines existed there too.

**Comment by DustanHache** [comment]
> > The current vote is 15:25 out of a total 40 votes on this PR. evidently there's a lot more people who like kilo than people who don't. enough that it's over 2/3ds majority.
> 
> This is a pretty flawed summation, given that:
> 
> * Most people don't even read PRs in the first place
> * More people are going to vote no than yes for removing virtually any map because they don't like change

let me put it this way. arbitrarily axing a map is a bad idea. take the oldest maps so far (meta, delta, kilo, icebox, and tram) and put them all on a poll for map removal. this will tell you which maps need to be reworked or scrapped, and which ones are actually enjoyed.

**Comment by Rex9001** [comment]
> > > The current vote is 15:25 out of a total 40 votes on this PR. evidently there's a lot more people who like kilo than people who don't. enough that it's over 2/3ds majority.
> > 
> > 
> > This is a pretty flawed summation, given that:
> > 
> > * Most people don't even read PRs in the first place
> > * More people are going to vote no than yes for removing virtually any map because they don't like change
> 
> let me put it this way. arbitrarily axing a map is a bad idea. take the oldest maps so far (meta, delta, kilo, icebox, and tram) and put them all on a poll for map removal. this will tell you which maps need to be reworked or scrapped, and which ones are actually enjoyed. you can even do it in highest to lowest style to get a better idea of which map is most hated overall.

Its not arbitrary, birdshot is lower population than all of those maps, birdshot is 0-70 whilst meta has a higher minimum. Its clear why it was chosen over Kilo in the pr body

**Comment by Jacquerel** [comment]
> let me put it this way. arbitrarily axing a map is a bad idea. take the oldest maps so far (meta, delta, kilo, icebox, and tram) and put them all on a poll for map removal. this will tell you which maps need to be reworked or scrapped, and which ones are actually enjoyed. you can even do it in highest to lowest style to get a better idea of which map is most hated overall.

The PR body quite clearly explains why it is Kilo and not another map.

**Comment by EOBGames** [comment]
So I feel I need to address a few things.

First, I respect that this is controversial- the comments have shown as much. Again, I explained in the PR body as to why Kilo was picked out of the active rotation maps, but I also feel I need to level with everyone: I don't want to remove a map. In an ideal world, we would be able to actively maintain many, many more maps than we currently do with no ill effect to the code side of the game. We don't live in an ideal world. Every new feature that touches maps is essentially required to go to all of them. This places a fair burden on contributors, and that burden is doubled on Kilo specifically where the space is tight and new additions are hard to make. The map was tightly designed when it launched in 2019, but we've had nearly 4 years worth of features by then, which have been hard to fit and are only going to get even harder with each new one.

Ultimately, this is potentially a solvable problem, if we can get a dedicated mapping team going who can assist coders with adding their features, but to again lay some truth bare- our team is very small and we don't have the manpower or organisation for that kind of stuff. This is why we, and I do mean the maintainer team as a whole here including headcoders, decided on a cap on the map pool at 6 maps, which is the threshold we consider to have the best balance of allowing map diversity without making code contributions too hard. If you want to change that, I'd recommend at least directing your anger more towards the system and less towards this PR, or joining the mapping team to help us get those numbers up and make the sort of cooperation we're striving for possible.

Second, with regards to community wishes, since I see the like/dislike ratio brought up as an example of how loved Kilo is- Kilo has consistently placed at the bottom of map polls done up to this point (most recently in June of 2022, unless San has done one since that I missed), scoring an average of roughly 4.5/10:

image

While I enjoy the map, and I gather that everyone here arguing enjoys it, the community as a whole has been much less favourable towards it. This didn't really factor into my decision-making regarding Kilo being the map to go (that was based on the maintainability side of stuff, as noted in the PR body), but it does make a hole in the defense.

Third, to address the lowpop discussion- as much as having a dedicated spot in the rotation for a lowpop map is nice, I don't consider it critical. A larger station can accommodate a lower population, although non-ideally; a smaller station cannot accommodate a higher population without becoming too cramped to function. This one-way relationship means that I generally consider taking a higher pop band station over a lower one desirable. Again, this could change if we had the manpower to keep more maps up to date, but in a situation where we are limited in how many maps we can reasonably maintain, I'd rather take the one that works at those higher population bands where most rounds are taking place.

**Comment by SinfulBliss** [comment]
I disagree that a lowpop map isn't critical. 10 hours every day the serverpop is below 30, and 6~ hours every day it's below even 20. The game is significantly less fun when no one sees each other because of how big the map is, and neither Northstar nor Birdshot are adequate replacements.

I'm surprised Kilo is getting axed for Birdshot, I wouldn't have thought the maptainers think the latter is a better map.

**Comment by BlueMemesauce** [comment]
> > let me put it this way. arbitrarily axing a map is a bad idea. take the oldest maps so far (meta, delta, kilo, icebox, and tram) and put them all on a poll for map removal. this will tell you which maps need to be reworked or scrapped, and which ones are actually enjoyed. you can even do it in highest to lowest style to get a better idea of which map is most hated overall.
> 
> The PR body quite clearly explains why it is Kilo and not another map. "Popularity" is only one of the factors.

It really doesn't though? These are the only two arguments why kilo specifically was chosen "the map has consistently proven to be problematic for new code additions due to its scale, and it receives little maintenance outside of the bare essentials as a result."
Both arguments can apply to delta and meta has as well as kilo. Like someone else said, meta is the oldest map and has received almost no changes for the entire year. So I believe the PR needs more justification as to why kilo specifically rather than meta or delta.

**Comment by Ekaterina-von-Russland** [comment]
> Icebox and tram can burn in hell. Kilo needs to stay for the sake of lowpop.

I concur with the sentiment. Icebox is a better choice for removal than Kilo.

**Comment by BlueMemesauce** [comment]
Icebox serves the purpose of being the map we made tons of new ruins and a planet system for. Doesn't make sense to remove it until Chilledstation comes along to replace it.

Metastation and deltastation both serve the same purpose of being a normal easy to navigate map. I know they're both the most loved maps for that. But we shouldn't have both of them if we can only have a limited amount of maps.

**Comment by Jacquerel** [comment]
> It really doesn't though? These are the only two arguments why kilo specifically was chosen "the map has consistently proven to be problematic for new code additions due to its scale, and it receives little maintenance outside of the bare essentials as a result." Both arguments can apply to delta and meta has as well as kilo. Like someone else said, meta is the oldest map and has received almost no changes for the entire year. So I believe the PR needs more justification as to why kilo specifically rather than meta or delta.

This just isn't true. Meta and Delta are _much_easier to update than Kilo, which is always the hardest of any map to add new features to. The fact that you don't _believe_ the justification isn't really a factor.

**Comment by MMMiracles** [comment]
someone add a feature that requires 2 tiles of space in science and tell him to add it without re-arranging more than 2 rooms.

**Comment by plutori** [comment]
>Literally everyone hates tram
>Icebox has terrible performance issues
>During lowpop people go back and forth between meta and kilo and only take other maps when forced to by rotation requirements
>There are no other dedicated to lowpop maps
>Hey guys lets remove kilo!

Wow hey why isn't this PR popular, it's a mystery.
For real though, please keep in mind that for half the day, we're lucky to break 20pop on Sybil. I don't think the coderbus is fully cognizant of this fact, and is removing the dedicated lowpop map without full and proper consideration of this fact.

**Comment by DustanHache** [comment]
> Icebox serves the purpose of being the map we made tons of new ruins and a planet system for. Doesn't make sense to remove it until Chilledstation comes along to replace it.

sound logic, at least on paper. in practice however there are fewer ghost roles, more issues with ghost roles invading station level (since icebox has no other Z levels aside from the three it’s built on) and more than it’s fair share of issues from the mixing of mining with the rest of the station)  (namely mobs breaching into the station and wrecking house against non-miners)

**Comment by Ekaterina-von-Russland** [comment]
> Icebox serves the purpose of being the map we made tons of new ruins and a planet system for. Doesn't make sense to remove it until Chilledstation comes along to replace it.

This is not a purpose. This is you falling for the sunken cost fallacy.

**Comment by Mothblocks** [comment]
meta works fine as a low pop map

**Comment by Mothblocks** [comment]
> > > let me put it this way. arbitrarily axing a map is a bad idea. take the oldest maps so far (meta, delta, kilo, icebox, and tram) and put them all on a poll for map removal. this will tell you which maps need to be reworked or scrapped, and which ones are actually enjoyed. you can even do it in highest to lowest style to get a better idea of which map is most hated overall.
> > 
> > 
> > The PR body quite clearly explains why it is Kilo and not another map. "Popularity" is only one of the factors.
> 
> It really doesn't though? These are the only two arguments why kilo specifically was chosen "the map has consistently proven to be problematic for new code additions due to its scale, and it receives little maintenance outside of the bare essentials as a result." Both arguments can apply to delta and meta has as well as kilo. Like someone else said, meta is the oldest map and has received almost no changes for the entire year. So I believe the PR needs more justification as to why kilo specifically rather than meta or delta.

Brother we removed an entire feature in science and gained one tile. Kilo is so impossible to work with that Armhulen had to put a computer in maintenance and block off a tunnel just to work with it

**Comment by BlueMemesauce** [comment]
I agree that metastation can be useable as the lowpop map even though it's meant to be a medium sized map. It's not that much bigger than kilostation and the simple layout makes it easy to see other people. 
Maybe we should adjust the config so that meta is the lowpop station then? Because meta makes more sense than birdshot being the new lowpop station. Birdshot is huge

> someone add a feature that requires 2 tiles of space in science and tell him to add it without re-arranging more than 2 rooms.
> 
> bonus points if it requires a wall mount


> Brother we removed an entire feature in science and gained one tile. Kilo is so impossible to work with that Armhulen had to put a computer in maintenance and block off a tunnel just to work with it

I understand but we still need small maps for lowpop even if they're harder to work with.

**Comment by Mothblocks** [comment]
I don't think we need a dedicated low pop map when Meta works fine at low pop. A dedicated low pop map means that anyone who isn't regularly on at dead hours is less likely to because they will be forced onto somewhere they're completely unfamiliar with

**Comment by DustanHache** [comment]
> I don't think we need a dedicated low pop map when Meta works fine at low pop. A dedicated low pop map means that anyone who isn't regularly on at dead hours is less likely to because they will be forced onto somewhere they're completely unfamiliar with

counterpoint: we don't need pop restrictions on our maps to begin with. Locking maps behind highpop has the exact same effect as what you claim making kilo dedicated lowpop does. hell, on bagil we do not ever see tram, delta or northstar unless the admins force the station to change to it. how disorienting do you think that is to people who mainly play low or deadpop?

**Comment by Mothblocks** [comment]
i agree

**Comment by san7890** [comment]
> counterpoint: we don't need pop restrictions on our maps to begin with

headmin issue unfortunately. we should consider having a wide variety of maps to choose from (both that are considerably more compact/spread out/uniquely designed) but the actual population settings are completely out of our hands in a production setting.

**Comment by Ekaterina-von-Russland** [comment]
> headmin issue unfortunately

Should we make a policy discussion thread?

**Comment by DustanHache** [comment]
> > counterpoint: we don't need pop restrictions on our maps to begin with
> 
> headmin issue unfortunately. we should consider having a wide variety of maps to choose from (with a medley of maps that considerably more compact/spread out/uniquely designed) but the actual population settings are completely out of our hands in a production setting.
> 
> headmin terms also do typically solicit maptainers for their thoughts on what should go where as far as lowpop/mediumpop/highpop but the choice is ultimately and finally theirs since it's a config. they could crank meta to 50pop+ for a laugh (and risk alienating their playerbase) but by God they can do it

Just another reason why removing Kilo isn't the answer. If the issue is that other maps aren't getting enough representation (which is one of the excuses why kilo should be removed) Then this needs to be policy discussioned and voted on. If you wanna make birdshot the next kilo, you first gotta let us GO there.

**Comment by plutori** [comment]
At least fix birdshot's issues before you do this.

Add the missing atmos gas chambers and an atmos to sm pipeline, and I could stomach this change, but right now you're removing a working map for a half baked map.

Is that much at least a reasonable request?

**Comment by Jacquerel** [comment]
> At least fix birdshot's issues before you do this.
> 
> Add the missing atmos gas chambers and an atmos to sm pipeline, and I could stomach this change, but right now you're removing a working map for a half baked map.
> 
> Is that much at least a reasonable request?

Birdboat is already merged, feel free to open a PR.

**Comment by plutori** [comment]
> > At least fix birdshot's issues before you do this.
> > Add the missing atmos gas chambers and an atmos to sm pipeline, and I could stomach this change, but right now you're removing a working map for a half baked map.
> > Is that much at least a reasonable request?
> 
> Birdshot is already merged, feel free to open a PR. This PR isn't really the place to discuss whether or not you like Birdshot because it's already part of the map rotation, that ship has sailed.

>Entire argument of this PR is "Hey because we added birdshot to rotation, we need to remove kilo for maintainer budget"
>What, no, don't discuss birdshot at all here!

Are you high?

If you can't fix birdshot, then this PR should be closed or delayed until Birdshot is an actual finished map. You can't claim the need for removing kilo is because of birdshot and then say we can't discuss birdshot.

**Comment by san7890** [comment]
> If you can't fix birdshot, then this PR should be closed or delayed until Birdshot is an actual finished map. You can't claim the need for removing kilo is because of birdshot and then say we can't discuss birdshot.

this is what the issue report list has looked like since it was merged:

image

file an issue report or learn to map here: https://hackmd.io/@tgstation/SyVma0dS5

everything else is counter-productive. there's no stats to back up your claim that it's a broken map because there are absolutely no stats to back up your claim that it's a broken map. file an issue report if something is wonky.

**Comment by MMMiracles** [comment]
image

**Comment by SgtHunk** [comment]
it's jover for kilocels

**Comment by EyEy69** [comment]
Are you telling me Tram+Northstar+Birdshot(based) make sense to keep at the same time but you removed the BEST low pop station in favor of SIX high-mid pop stations?

**Comment by Mothblocks** [comment]
meta works fine on low pop

**Comment by TheVekter** [comment]
> Literally everyone hates tram
I think it's great, I absolutely don't see why people hate it.
> Icebox has terrible performance issues
It's improved a ton over the last few months and rarely, if ever, sees the same lag issues it once did.
> During lowpop people go back and forth between meta and kilo and only take other maps when forced to by rotation requirements
Honestly more of a reason to introduce a new map if we're only bouncing between two of them.

There's valid concerns to removing Kilo for Birdshot (the map generally feels unfinished to me and I prefer how Kilo is laid out) but these aren't them.

**Comment by BlueMemesauce** [comment]
Please explain how removing one of the only two lowpop maps and replacing it with yet another highpop map isn't a valid reason? Nobody has explained this other than saying that meta can serve as the new lowpop map, which I actually do agree with now. But I think we need at least two lowpop maps.

**Comment by JohnFulpWillard** [comment]
Continuing to complain here is not gonna change anything. This is something maptainers have decided on, and this PR is already merged. Please bring this up in the appropriate channels.

**Pull request merged**
