### PR TITLE
Adds separate log for sql errors with no config check

### PR DESCRIPTION
**Pull request by Jordie0608**
This will help to find instances where queries are made without checking for a db connection first, of which there are apparently more than the 0 I assumed there would be.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Thanks

**Comment by Cyberboss** [comment]
I honestly feel like sql should have it's own logfile, because people want JUST that often enough

**Comment by Jordie0608** [comment]
Eh okay.

**Comment by Jordie0608** [comment]
@MrStonedOne I assume this will now require an update to the parser

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
