### PR TITLE
Changes flavor text for NT agents to no longer say the Syndicate provided you with codewords

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

It is kinda strange, when you get an IAA agent with "death to syndicate" in flavor text, and then see that The Syndicate(in which you don't participate) had provided you with some codewords. This PR replaces "The Syndicate" in the codewords part by "your employer", so it will make more sense.

## Why It's Good For The Game

Kinda strange when The Syndicate somehow provides codewords for NT agents.

## Changelog

:cl: SuperSlayer
spellcheck: Traitor codewords are now given by their employer, rather then by The Syndicate
/:cl:

### CODE REVIEW

**Comment by ANAME593** [comment]
i get that but, flavor text isnt respected enough and ever since new tot came out it matters even less now i don't think we should cripple traitors like this since being able to identify other traitors is one of the most important functions as a tot

**Comment by TymurShatillo** [comment]
> i get that but, flavor text isnt respected enough and ever since new tot came out it matters even less now i don't think we should cripple traitors like this since being able to identify other traitors is one of the most important functions as a tot

This PR doesn't make them not get codewords or get different codewords from different organizations, it just changes the text about who does give you codeworss

**Comment by TymurShatillo** [comment]
Screenshot_20220713-085750_Chrome
Why

**Comment by Shadowflame909** [comment]
> This PR doesn't make them not get codewords or get different codewords from different organizations, it just changes the text about who does give you codewords

I like that. We all think its weird that the syndicate higher ups and nanotransen higher ups look the same right???

**Comment by TymurShatillo** [comment]
And how can i run this "Prettier" if the rests aren't run on my computer

**Comment by TymurShatillo** [comment]
Ok

**Comment by ANAME593** [comment]
> > i get that but, flavor text isnt respected enough and ever since new tot came out it matters even less now i don't think we should cripple traitors like this since being able to identify other traitors is one of the most important functions as a tot
> 
> This PR doesn't make them not get codewords or get different codewords from different organizations, it just changes the text about who does give you codewords

there isn't always going to be 2  nanotrasen tots and 2 syndicate tots its completely random you could end up gutting the chances of traitor to traitor cooperation occuring

**Comment by Mothblocks** [comment]
@ANAME593 My brother in Christ this PR literally only changes the description of a UI

**Comment by ANAME593** [comment]
> @ANAME593 My brother in Christ this PR literally only changes the description of a UI

OH

**Pull request merged**
