### PR TITLE
Spruces up Meta circuitry lab, adds mining station restroom

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: Metastation: Spruced up the RnD circuitry lab; no gameplay changes.
tweak: Due to exemplary performance, NanoTrasen has awarded Shaft Miners with their very own bathroom, constructed at the mining station dormitories. Construction costs will be deducted from their salaries.
/:cl:

Metastation's circuitry lab is this drab box, I basically recycled the design of the circuitry lab I did for Pubbystation way back when. 
Are the inner light purple borders maybe a little too much?

autist-containment

The mining station also didn't have a bathroom:

mining-bathroom

### CODE REVIEW

**Comment by Repukan** [comment]
Why would you add a bathroom when there's no shitting mechanics

**Comment by 81Denton** [comment]
I'm sure chesse20 will open a PR for that eventually

**Comment by WJohn** [comment]
If you merged the two tables into one and rotated them by 90 degrees, you could pull this whole fucking lab in by several tiles. It is unnecessarily huge, always has been.

**Comment by Nabski89** [comment]
Nice use of light and dark purple tiles. Pity about that corner in the lower right.

Oh god giving miners their own personal bar of soap. WHY? Admittedly it does make sense to not take an expensive shuttle up to a station just to shower off.

**Comment by Iamgoofball** [comment]
it's supposed to be big, you're supposed to be building full movement robots and vending machines,

**Comment by 81Denton** [comment]
@WJohn I haven't done circuitry myself, but so far I've seen people build lathes and bots with locomotion circuits/pathing that take up a bunch of space every round.
@Nabski89 The soap bar is cosmetic, I don't mind removing it if it's an issue. Soap bars are only 200 miner GBP or something from what I remember.

**Comment by WJohn** [comment]
Even taking that into account you would *still* save around 4 tiles of space AND actually have just as much work area.

**Comment by SpaceManiac** [comment]
@81Denton if you don't want to have to deal with MSVC, use Python 3.6 instead of 3.7, there are not precompiled binaries for pygit2 for 3.7 for whatever reason

**Comment by 81Denton** [comment]
@SpaceManiac Thank you, that was just what I needed. On 3.7 I was unable to compile pygit2 even after a bunch of troubleshooting.

**Comment by 81Denton** [comment]
Lab is now a little smaller and miners no longer get free soap 

autist-containment

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
