### PR TITLE
syndie gasmasks are small

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

syndie gasmasks are small

## Why It's Good For The Game

syndie gasmasks come in emergency boxes, once you take them out you cant put them back in
they offer no functional difference to regular gas masks
the atmos/captain gas masks fit in boxes for some reason but this doesnt

## Changelog
:cl:
tweak: syndie gasmasks are small
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by Sparkezel** [comment]
Doesnt normal gasmask from fire emergency closet not fit into boxes? Also if I remember correctly explorer gasmask is also normal sized, and its in miner box, do you think you could fix that here too?

**Comment by Tlaltecuhtli** [comment]
make all gasmasks small

**Comment by cacogen** [comment]
Yeah, regular gas masks have never fit in boxes for whatever reason. I think they used to be more essential in covering one's face due to a lack of other choices. But they've always been too conspicuous to be worthwhile anyway.

**Comment by Pugie** [comment]
Miner one is shitcode. It's normal sized except when you pull it down to eat, or the other way around.

**Comment by Fikou** [comment]
out of scope

**Pull request merged**
