### PR TITLE
Syndicate surgery bag now has very strong syndicate surgery tools to go with it!

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: syndicate surgery kit now has really good surgery tools!
/:cl:

Surgery kit is woefully underused and this might not be hitting the problem on the head but i feel like special items and the like might encourage some more surgery action

I NEED TO ADD THIS TO THE DUFFEL  hope i don't forget that!

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Armhulen** [comment]
get out of here, bots! Shoo! I don't need or want you!

**Comment by AnturK** [comment]
What the bot said.

**Comment by Anonmare** [comment]
Roasted by a bot

**Comment by calzilla1** [comment]
Arm make an easy grammer fix then merge this

**Comment by calzilla1** [comment]
God damn it someone give arm 100 gbp

**Comment by AnonymousNow** [comment]
This seems like a nice feature, and I would like it to reappear.

**Comment by Qbopper** [comment]
arm just fucking make some fixes

**Comment by Armhulen** [comment]
@Qbopper @AnonymousNow @calzilla1 

sorry the maintainers don't like the idea though so they wouldn't reopen
i do have some fixes in store just in caaaaaase!

**Comment by calzilla1** [comment]
>players like idea
>admins like the idea
>maintainers dont and dont state why
We need a coder purge

**Comment by Qbopper** [comment]
meme, but yeah, where did anyone say they didn't like the idea, in coderbus?

would be nice if a reason was provided when a PR was closed

**Comment by AnonymousNow** [comment]
Chin up, Arm; it's worth pursuing.

**Pull request closed without merging**
