### PR TITLE
Tramstation Modular Maintenance Pass 1

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
Renovates a good chunk of both upper and lower maintenance to use modular room placement for both individual rooms and even some tunnels.

**The main things:**
- Most maintenance rooms themselves have been turned into modules, usually with 1-2 extra variants on top of an additional 1-2 attachment modules if suitable. 
- Maintenance routes like the unfinished tunnel between the main tram tunnel and atmospheric's maintenance can now vary between their abandoned and finalized variant. Each of these routes also have an attachment point with their own room variants as well.

## Why It's Good For The Game
Mixes up static spawns and adds another layer of unique station layouts without adversely effecting station jobs. Also showcases a cool mapping mechanic and shows exactly what can be done with a big of extra work.

## Changelog

:cl: MMMiracles
add: Tramstation's maintenance has taken broken down into more modular segments that will now load in randomly each round.
add: There is now a medical console and crew console in the main medbay treatment room.
/:cl:

[going into a new round of tramstation be like](https://www.youtube.com/watch?v=GZIL-TduEcM)

Example of the 2nd bullet point:
image
image

### CODE REVIEW

**Comment by tohg7** [comment]
neat, we could use more modular maints on more maps.

**Review by Maurukas — CHANGES_REQUESTED** [review]
Okay. Time to stop putting this one off.

<details>
<summary>Bunch of Active Turfs</summary>

image


image


image

image


image

image



</details>

<details>
<summary>Doubled pipes/wires</summary>

image
image

**Comment by MMMiracles** [comment]
i fixed the double layered pipe/cables, assuming it was a weird issue with saving

as for the active turfs, only two of the listed ones actually had an issue with turf differences. the others had no breaches or conflicting gas lists next to each other so i'm wondering if that's an issue with how the modules are loaded

**Comment by Maurukas** [comment]
Let me take another look. This may be a modular issue.

**Comment by Maurukas** [comment]
On this one it's the recharge floor. This turf has air, surrounded by three airless turfs:
image

On all the others, yeah I can find no explanation for where these active turfs are coming from. There are no turfs of different types in the modular pieces.

@Thunder12345 Is this something you could take a look at?

**Comment by Maurukas** [comment]
Found the problem - it's not the templates themselves. It's that the templates extend past the closed turfs above them. Air is getting out upwards:
image

**Comment by Maurukas** [comment]
Looks like they're all covered.

**Pull request merged**
