### PR TITLE
Revert "[READY]Asay and dsay radio keys"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#24341

@Cyberboss 

do it right or not at all.

doesn't include the alt formats like . or #

doesn't remove the key from the message.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
You seem to have a problem with stealth min

**Comment by MrStonedOne** [comment]
what the hell does this have to do with stealthmin?

**Comment by coiax** [comment]
I don't have anything to say, but I wanted to participate in screenshotting comments.

image

**Comment by Thunder12345** [comment]
I have nothing better to do with my time

**Comment by optimumtact** [comment]
stop being so fucking autistic

**Pull request merged**
