### PR TITLE
SM gas healing

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Allows player to fix the SM by using Healium at more than 10% composition

## Why It's Good For The Game
More ways to use gases and to interact with the SM, easier to fix the SM

## Changelog
:cl:
qol: healium now heals the SM
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
image

(≖_≖ )

**Comment by Ghilker** [comment]
image

**Comment by Ghilker** [comment]
since i'm working on more gas interactions for the SM i'll bundle them into one PR

**Comment by interestingusernam3** [comment]
tweak tag

**Comment by interestingusernam3** [comment]
the

**Pull request closed without merging**
