### PR TITLE
Flashes now once again stun borgs

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Flashes will once again stun borgs, but for a much shorter time than they previously did; average stun time is reduced from the previous average of 15 seconds to about 6 seconds. The confusion remains, but it will no longer unequip borg modules.
/:cl:

Note; stun time previously was random between 10-20 seconds.

Pros; borgs can be dealt with more easily, i fixed an unrelated typo

Cons; stun combat, hard counters, people coming out of the woodwork to meme me

### CODE REVIEW

**Comment by coiax** [comment]
How many uses in a normal flash before it burns out?

**Comment by ChangelingRain** [comment]
Infinite unless you use it too many times in a short timespan but I'm not bothering to decipher that code

**Comment by InsaneHyena** [comment]
Make flashes great again

**Comment by coiax** [comment]
If you can still stunlock borgs with a flash, then the confusion aspect will only really apply to a flashbang

**Comment by ChangelingRain** [comment]
Flashbangs were unchanged and still stun borgs.

**Comment by coiax** [comment]
Huh. They should change that.

**Comment by TechnoAlchemisto** [comment]
Good!

**Comment by Cebasiz** [comment]
6 seconds is still going to be instant death

i didn't really like cheri's removal of stun flashes, but at the same time there's no effective difference between this PR and the way it used to be.

if we're going to buff borgs i'd rather it be done another way. their vulnerability to stuns was never the problem t b h

**Comment by Dorsisdwarf** [comment]
It's better because you're stunned, not paralyses, so you can squawk for mom

**Comment by coiax** [comment]
Except I'm pretty sure Weaken for cyborgs is unconsciousness, unless I'm wrong?

**Comment by Cebasiz** [comment]
the original reason that cyborgs became muted/deafened while stunned was so that they could be emagged. 

back in the day there was nothing to preventing you from ; HELP TATOR EMAGGIN ME

which of course once you were done being emagged you'd say ; nevermind lol and then get blown like 2 seconds later forceghosting you which fucking sucked.

also borgs should be maggable so reverting that is not a good idea. 

the original reasoning for it still stands. more resillience is not what borgs need anyway.

**Comment by Cheridan** [comment]
>more resillience is not what borgs need anyway. 
Well you're not going to get what you want (having secborgs back) so you might as well take what you can get.

@ChangelingRain tbh just remove the module unequipping too. if you're already getting stunned then it's just an annoyance

**Comment by Cebasiz** [comment]
i want secborgs back, i don't need them back. what i need is a module that's capable of doing the job that the lawset obligates me to do. 

that means it needs to be good at **preventing** harm. what does this entail exactly? 
it needs to be able to incapacitate a human. not necessarily all humans, but **A** human. 
it needs to be able to block bullets (all borgs can do this but maybe a bit better at it because it's a specialist)

it needs to be able to shut down borgs that are killing humans (flash works)

there is a borg module in the game for all of these tasks, it is called the peacekeeper module. unfortunately it was never actually good enough at these tasks and was made worse* by the removal of the bola

*the bola didn't actually do this either so technically it wasn't really a downgrade

i don't really care about the return of secborgs, i just care that i am actually able to do my job*

*that the lawset assigns me

no other role has it's tools for the thing it is OBLIGATED to do systematically taken away while still being forced to do that role. 

buff peacekeeper hypo solutions, give it a turtle mode for projectile blocking and make it's holoprojector actually achieve something and i'll be 100% fine with it once it is actually capable of achieving something useful.

i do not feel like i am actually asking for much here. why i face this entrenched opposition i have no idea.

**Comment by ChangelingRain** [comment]
I'd just like to note that, because stun procs work off of Life(), there's a variance of up to minus two seconds on stuns depending on when the stun was applied and how stun stuff works, so this is basically between 4 and 6 seconds of stun.

Which is good, but not nearly as good as 8-10 to 18-20 seconds of stun, especially considering that flashes burn out if overused.

**Comment by Zilenan91** [comment]
Flashes should probably do at least 7 like stunbatons do. Especially because borgs never slow down from damage if you can't apply the flash enough they'll get away too easily.

**Pull request merged**
