### PR TITLE
Adds optional population caps

### LINKED ISSUE #7537: Headmin Request: Population Caps set by server config
HG, An0n3, and I unanimously agree that some form of Population Cap is something we can try out some time.

By default it should be off, but should the server operators want to set one in game_options.txt they should be able to.

Also:
- Don't make admins/coders count towards the cap
- Observers shouldn't count towards the cap or be blocked from observing, either

### PR DESCRIPTION
**Pull request by Incoming5643**
For those that want them. These be dark measures, so tread carefully ye who dare enter this place.

There are three "levels" of popcaps, and you can use them in any assortment you like:

-The "soft" cap produces a message on join, and takes no action.
-The "hard" cap disallows joining whilst too many other people are alive and playing in game, but allows observing.
-The "extreme" cap prevents people from joining the server at all while the cap is exceeded. It won't kick out people who failed to qualify during roundstart, but if they leave they won't be able to get back in.

In each case a customizable message option has been given. Admins are also immune to most population caps (they still are hit by the ones in job shuffling, but can late join as normal afterwards). All popcaps default to off, seriously think long and hard about this.

Standard disclaimer: It's really hard to test this on anything else than a legitimate server, so don't be all shocked if a hotfix or two is needed once people see how/if it actually performs.

Fixes #7537

### CODE REVIEW

**Comment by Incoming5643** [comment]
Note that because of how job selection works people who have assistant set to "yes" are more likely to not qualify for a round because that check is performed last. This doesn't effect people who end up as assistants through "be assistant if job unavailable" as badly though.

It can't really be helped unless job selection was overhauled, which is euuuuuugh

**Comment by MrStonedOne** [comment]
Honestly, Assistants being more likely to get capped away is a good thing. I call that a feature.

**Comment by MrStonedOne** [comment]
in the case of the extreme cap, players who are playing should be able to dc, and not worry about being able to come back. How does it handle that?

**Comment by Incoming5643** [comment]
There's no checking for that, but you can create a buffer by having the hardcap be lower than the extreme cap since the hard  cap only applies to players before they join.

If the hard cap is 100, and the extreme cap is 125 up to 25 players could disconnect at once and be able to come back. By the same token the effective player cap will hover a little bit above the hard cap in practice because of people joining whilst other players are temporarily disconnected or waiting to be cloned. Events that create new mobs from ghosts also allow for a little pushing past the hard cap.

**Comment by Incoming5643** [comment]
also for the record there's 59 job slots availible at roundstart, and two more (two scientists) at latejoin. So a 60 player limit would be a bit rough, as it means a server is apt to never be "fully staffed".

**Comment by Jordie0608** [comment]
Changelog.

**Comment by phil235** [comment]
@Incoming5643 changelog please.

**Comment by Miauw62** [comment]
changelog ;_;

**Comment by Incoming5643** [comment]
I'd be lying if I didn't say I'm probably procrastinating on this one intentionally.

Soon though.

**Comment by Ikarrus** [comment]
Changelog added, merge he

**Pull request merged**
