### PR TITLE
Wilhelm screams.

### PR DESCRIPTION
**Pull request by KazeEspada**
When ever a spacemen screams, it will play the wilhelm scream sound. This includes when they are being crushed by airlocks and applying healing patches. Also, with the emote.

### CODE REVIEW

**Comment by optimumtact** [comment]
:-1: I fucking hate this scream, ever since someone mentioned it to me I fucking notice it in every fucking video film and movie ever and it ruins the moment.

:-1:  I CANNOT UNDERSTATE HOW MUCH I FUCKING HATE THIS THING

**Comment by Chocobro** [comment]
>also, with the emote.

spamming soon

**Comment by KazeEspada** [comment]
*PING *PING *PING *PING *PING *PING

**Comment by RemieRichards** [comment]
:-1: :x: :100:

**Comment by KorPhaeron** [comment]
Puke Chunks screams!
Puke Chunks screams!
Puke Chunks screams!
Puke Chunks screams!
Puke Chunks screams!

**Comment by PKPenguin321** [comment]
on the ropes with this one
it feels like something we'd implement for april fools

**Comment by Chocobro** [comment]
the difference is it's emote spam with a sound that's 2 seconds long
whereas ping is maybe 0.4 seconds long

**Comment by PKPenguin321** [comment]
@Chocobro clearly you've never seen sad trombone borg spam

**Comment by Chocobro** [comment]
are you supporting this pr @PKPenguin321 
fuckin throwing shade get at me fam

**Comment by MMMiracles** [comment]
make it a rare occurrence as an easter egg, goon has sound screaming and its legit awful.

**Comment by KazeEspada** [comment]
I can work on an emote cooldown in another PR.

**Comment by TrustyGun** [comment]
b-but muh *flip spam!

**Comment by MrPerson** [comment]
The Wilhelm scream is copyrighted material of Warner Brothers.

**Comment by KazeEspada** [comment]
Actually, it's public domain.

**Comment by MrPerson** [comment]
Source?

**Comment by KazeEspada** [comment]
https://en.wikipedia.org/wiki/Wilhelm_scream

**Comment by MrPerson** [comment]
> This was its first use from the Warner Bros. stock sound library

Uhhh try again

**Comment by KazeEspada** [comment]
Second link

**Comment by xxalpha** [comment]
I agree with oranges.

**Comment by Incoming5643** [comment]
maybe as a prob(.01) chance, but nothing more.

**Comment by Zilenan91** [comment]
Sound screaming is nice if it's more than one sound. Can you make the scream alternate in pitch Kaze?

**Comment by Anonmare** [comment]
If it pissess off oranges then merge this post-haste

**Comment by xxalpha** [comment]
This is literally worse than those helmets for kids with special needs that made a loud sound. That was removed, why should this be added?

**Comment by CosmicScientist** [comment]
Not even a good meme. :-1:

**Comment by Bawhoppen** [comment]
:neckbeard:

**Comment by newfren** [comment]
:-1:

**Comment by PKPenguin321** [comment]
>This is literally worse than those helmets for kids with special needs that made a loud sound. That was removed, why should this be added?

if you mean justice hats, those were not removed

**Comment by Supermichael777** [comment]
they just turned from obnoxious ear rape to tolerable ear rape. so shitheads lost interest the moment people could ignore it

**Comment by WJohn** [comment]
:-1: x :100:

**Comment by Fox-McCloud** [comment]
:+1: to the idea of a scream sound, if and only if there's a cooldown to it.

If that was done, then this could be an amusing joke (ie: 1-5% chance of it happening).

Just straight up adding a scream sound and making it this though? Ewwww :-1:

**Comment by kyrahabattoir** [comment]
Scream sound? Yes
Wilhelm screan? NO NO GOD NO PLEASE NO.

**Comment by ike709** [comment]
:-1: until it's like a 1% chance

then you get a :+1:

**Comment by duncathan** [comment]
Strong :-1:

**Comment by SkowronX** [comment]
why not make it work only when someone screams in actual pain?

**Comment by Alek2ander** [comment]
:-1: to any scream sounds. Because that's the only sound you'll hear for most of the round. Although compared to goon there is less stuff that forces you to scream, players will definitely make up for it.

**Comment by Steelpoint** [comment]
I support this as its hilarious.

**Comment by phil235** [comment]
:-1:

**Comment by duncathan** [comment]
yea clearly this isn't wanted

**Comment by Iamgoofball** [comment]
will remake with goon scream sounds when I do the goon echo port

**Comment by Alek2ander** [comment]
:-1: :-1: :-1: Honk no that would be even worse

**Pull request closed without merging**
