### PR TITLE
supermatter anomaly generation can no longer be used to get anomaly cores

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

They'll poof on AnomalyNeutralize instead of dropping the core.

## Why It's Good For The Game

image

Sorry, Engi folks.

## Changelog
:cl:
balance: Supermatter anomalies no longer drop usable cores.
/:cl:

### CODE REVIEW

**Comment by Misha600** [comment]
But why

**Comment by tarlockgod** [comment]
Dont, its the only reason why anyone ever does autism with the SM.

**Comment by optimumtact** [comment]
If you're confused, see https://hackmd.io/@tgstation/r1tzxpwPL

**Comment by spessbro** [comment]
angry sm shard noises

**Comment by Misha600** [comment]
Can confirm, yesterday i had a shitton of fun getting anomalies from the SM as borg

**Comment by optimumtact** [comment]
@tarlockgod we are hoping to rebalance power to make running the SM near the edge a more valuable process, but nobody has taken up that task yet.

**Comment by spessbro** [comment]
Okay but for real. The fact that there's theoratically a way to produce anomalies using unstable supermatter shards is a very interesting idea and would functionally be very hard to maintain leading to a situation of the whole station blaming the ce and rd being blamed for being dumbasses which is very in character for ss13 in my humble opinion maybe make anomalies only have a limited chance to give you a core if you feel like mass producing them.

**Comment by san7890** [comment]
> Dont, its the only reason why anyone ever does autism with the SM.

You say that like people don't:
Intentionally singuloose the SM.
Intentionally tesloose the SM.
Run it on 90% co2 for shitloads of energy because ???
Fuel their piping fantasies.
And more!

**Comment by Iatots** [comment]
Can you rename them to micro-anomalies and have their sprite be smaller? A visual tell like that could help set expectations.

**Comment by tarlockgod** [comment]
> > Dont, its the only reason why anyone ever does autism with the SM.
> 
> You say that like people don't:
> Intentionally singuloose the SM.
> Intentionally tesloose the SM.
> Run it on 90% co2 for shitloads of energy because ???
> Fuel their piping fantasies.
> And more!

Thats just standart engi stuff, Anomaly farms are true autism

**Comment by LemonInTheDark** [comment]
> 
> 
> Dont, its the only reason why anyone ever does autism with the SM.

That really isn't the case.

**Comment by ATH1909** [comment]
> @tarlockgod we are hoping to rebalance power to make running the SM near the edge a more valuable process, but nobody has taken up that task yet.

Okay, then rebalance power first, THEN remove the current reason for even attempting to keep the SM on the edge.

**Comment by optimumtact** [comment]
no, I don't think I will

**Comment by CRITAWAKETS** [comment]
> no, I don't think I will

Hang on a minute, aren't you just a maintainer now and not headcoder?

**Comment by optimumtact** [comment]
image

**Comment by san7890** [comment]
> > no, I don't think I will
> 
> 
> 
> Hang on a minute, aren't you just a maintainer now and not headcoder?

If I didn't confuse the New Hire Log... It's no longer May 22nd to June 2nd.

**Comment by CRITAWAKETS** [comment]
> > > no, I don't think I will
> > 
> > 
> > Hang on a minute, aren't you just a maintainer now and not headcoder?
> 
> If I didn't confuse the New Hire Log... It's no longer May 22nd to June 2nd.

Oh, nice PR move. Dont even change your forum title back to headcoder that way you cant be held accountable on the forums, like last time with MSO.

**Comment by optimumtact** [comment]
What are you talking about? there is no head coder forum group, which means no title

**Comment by san7890** [comment]
image
image

time to get marked offtopic

**Comment by CRITAWAKETS** [comment]
> What are you talking about? there is no head coder forum group, which means no title

Oh, seems my memory failed me once again.

Still, nice move to get reddit off your back by retiring for less than 2 weeks and not having some sort of big message for when you actually come back

**Comment by MrDoomBringer** [comment]
For anyone confused, I recorded a quick chat I had with @optimumtact about this PR and his responses to some of the concerns people had
[Link here if you're interested   ](https://youtu.be/ZBFNx7bmSiM)

**Comment by FloranOtten** [comment]
> Can confirm, yesterday i had a shitton of fun getting anomalies from the SM as borg

If this is the incident I'm thinking of, you were the reason this PR was made.

**Comment by IndieanaJones** [comment]
So pyroclastic annomalies will no longer spawn when the SM gets fucked, basically removing the pyroclastic slimes from the game?  Super lame.

**Comment by TheMidnightRose** [comment]
As someone who does some of the autism SM engines and one of the ones to start the 90% Co2 meme engines. I do it more for the fun of seeing how high I can get the MeV before it starts to delam rather than the cores. 8750 MeV is my record before delam starts.

I would like the spawn rate toned down slightly but not outright removed. 

Making the anomaly cores unable to be used by science is fine, just toss a small export price on them, 100-200 credits for 'defunct anomaly cores' or something.

**Comment by Jared-Fogle** [comment]
> So pyroclastic annomalies will no longer spawn when the SM gets fucked, basically removing the pyroclastic slimes from the game? Super lame.

No. Everything will be the same except you can't *collect* the anomaly.

**Comment by Fikou** [comment]
why not make it spawn raw cores

**Comment by Rohesie** [comment]
There are many valid suggestions in here. The answer to them is that sure, PR those changes and if they align with the design doc they'll be merged.
The current state is an oversight deviating from where the stated design is headed.

**Comment by interestingusernam3** [comment]
>no, I don't think I will

[Reddit] detected.
[Security] alerted

**Comment by optimumtact** [comment]
begone

**Pull request merged**
