### PR TITLE
Makes the bandolier craftable

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Your favorite meme
tweak: the bandolier is now craftable
/:cl:

Made this because carrying ammo for makeshift shotguns was a pain. Hopefully they might actually see some use with this addition

### CODE REVIEW

**Comment by coiax** [comment]
FEATURE FROZEN

**Comment by Tacolizard** [comment]
not a feature

**Comment by Tacolizard** [comment]
well, mabye a feature

**Comment by Tacolizard** [comment]
fine

**Pull request closed without merging**
