### PR TITLE
Makes concussion grenade explosion smaller

### PR DESCRIPTION
**Pull request by Bawhoppen**
Its admin-only anyways right now, I do have plans for it though

also added myself to admins.txt

blame anturk if I didnt do that correctly

### CODE REVIEW

**Comment by KorPhaeron** [comment]
It actually spawns in caves.dmm

**Comment by Bawhoppen** [comment]
oh well not a big deal either way

**Comment by Zilenan91** [comment]
Aren't concussion grenades literally just reskinned minibombs?

**Comment by Bawhoppen** [comment]
yea they are smaller than syndiebombs now

**Comment by Zilenan91** [comment]
Do they still gib? It's really important that they do for the caves mission incase the zombies get loose.

**Comment by Bawhoppen** [comment]
here I'm going to go test some stuff now and tweak it a little

**Comment by Bawhoppen** [comment]
alright, I have chosen a good size explosion I think
it cannot gib bodies but in the future I plan to add an alternative nade that can gib stuff

**Comment by Zilenan91** [comment]
It needs to be able to gib for the caves mission because of the zombies.

**Comment by Bawhoppen** [comment]
why not just butcher them with a glass shard?

**Comment by Zilenan91** [comment]
That works, nevermind. I forgot you could gib entire human corpses with a puny shard of glass volvo pls

**Comment by Bawhoppen** [comment]
well they are rotting zombie corpses, not normal human corpses

**Comment by Zilenan91** [comment]
Still the same amount of meat just a bit bad and just as durable to damage

**Comment by tkdrg** [comment]
Conflicts, somehow.

**Comment by Bawhoppen** [comment]
what the fuck

**Comment by Bawhoppen** [comment]
huzzah

**Pull request merged**
