### PR TITLE
Fixes skeletons not healing burn damage by milk.

### LINKED ISSUE #77629: Milk does not heal burns on skeletons
Caused by https://github.com/tgstation/tgstation/pull/76184

Milk used to cure burn and brute damage on skeletons, now it does not.
When handling of milk was moved to liver, the burn healing was lost in process, probably because plasmamen and skeletons had different code for handling milk (plasmamen did not heal burns, skeletons did).

Changes:
old code for skeletons:
https://github.com/tgstation/tgstation/commit/6da96bef84257ba190fd2e42c2b9e5ebba8b6e7f#diff-6ec10b443b9782678e3b1855dbc88e3f89c86d49574fb55d03615bdffc50a00fL92
new code (chemical handling moved to liver)
https://github.com/tgstation/tgstation/blame/ccf4de21691c66775a3d7c695bf0679ed9c0aef3/code/modules/surgery/organs/internal/liver/liver_skeleton.dm#L42-L49C31

changes - old code healed bruises and burns, new code only heals bruises

specifically this line
old:
`H.heal_bodypart_damage(2.5 * REM * seconds_per_tick, 2.5 * REM * seconds_per_tick)`
new:
`organ_owner.heal_bodypart_damage(2.5 * REM * seconds_per_tick)`

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull Request
Closes https://github.com/tgstation/tgstation/issues/77629
## Changelog
:cl:
fix: Skeletons now heal burn damage with milk once again.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
This doesn't fully address the linked issue, as it stands this will now allow plasmamen to heal burn via brute which they could not do.

**Comment by Helg2** [comment]
i don't get it why they are able to heal by milk in the first place but okay

**Comment by Iamgoofball** [comment]
@Helg2 
fyHRF7h

**Comment by Serxule** [comment]
> i don't get it why they are able to heal by milk in the first place but okay

its a joke because its always been said that "drinking milk makes your bones strong"

**Comment by Serxule** [comment]
> I was questioning about plasmamen

ok well that wasnt obvious at all but plasmamen are a type of skeleton

**Comment by ExcessiveUseOfCobblestone** [comment]
The plasma goop gets in the way of the milk, making it inaccessible to some parts of the bone

**Comment by Serxule** [comment]
i was talking codewise, plasmamen are just skeleton with more downsides, lorewise plasmamen are pure plasma, milk wouldnt affect them

**Comment by Jacquerel** [comment]
lets fix the bug and debate the logic and balance considerations of plasmamen being able to heal with milk in another pr

**Pull request merged**
