### PR TITLE
Heat Exchange Manifolds

### PR DESCRIPTION
**Pull request by duncathan**
They're 3-way and 4-way pipe manifolds, except they're heat exchanging. wow

### CODE REVIEW

**Comment by Xhuis** [comment]
:+1:
### ___AT LAST___

**Comment by Razharas** [comment]
3way ones look like just an straight and bent ones overlap

**Comment by duncathan** [comment]
confession: this is the reason I did #11254 

@Razharas yeah that's actually exactly what the sprite is
if someone would like to make a better sprite they're more than welcome to

**Comment by Razharas** [comment]
http://s000.tinyupload.com/?file_id=56260280884684553368

**Comment by xxalpha** [comment]
Based

**Comment by WJohn** [comment]
http://www.mediafire.com/download/2sl06bdxqgkag6s/manifold_fixes.rar

Don't you ninja my offer!

**Comment by Lumipharon** [comment]
On the topic of atmos, I notice with some atmos machinery, like gas filters etc, you can't get certain configurations, because the gas that gets seperated/added only goes in a specific direction relative to the rest of the gas (Can't remember if it's left or right, but it only does one).

**Comment by duncathan** [comment]
@Lumipharon what do you mean? Can't you just flip the filter?

**Comment by xxalpha** [comment]
You can flip the filters.

**Comment by Lumipharon** [comment]
yes but the position is fixed, relative to the other output/input.

So with a filter, you have input on the bottom, output on the top, and filter out the left.
You can rotate it, but you can't change the filter to be right, relative to the input/output.

**Comment by duncathan** [comment]
@Lumipharon nah you totally can dude. There's a flip pipe object verb, use that on the pipe item before you wrench it in.

**Comment by Lumipharon** [comment]
Here is an HIGH QUALITY image to show you what I mean.
Here's all 8 direction vars of the same filter or whatever the fuck I was using, with the one in the 2nd row was where I tried to use the flip var, and nothing happened.

The sprites are in the files, and I haven't tried in game with this specific item, but at the very least in the map maker I can't get it.

**Comment by Razharas** [comment]
Post when its ready to merge

**Comment by WJohn** [comment]
The sprites haven't been swapped out yet. @duncathan could you do that please?

**Comment by Razharas** [comment]
@duncathan 
Cmon m8

**Comment by duncathan** [comment]
Haha holy shit I'm bad
I'll do this after class I swear

**Comment by Dorsisdwarf** [comment]
@duncathan 
wowsers how long is class for you

**Comment by duncathan** [comment]
@dorsidwarf
it ends at "I'm a piece of shit" o'clock

**Comment by duncathan** [comment]
Ah FUCK
Sprites sprites ffuck

**Pull request merged**
