### PR TITLE
Mesons work on lavaland again

### LINKED ISSUE #28776: Mining mesons should work again

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Mesons work on lavaland again.
/:cl:

Why: Our lighting system still just doesn't update fast enough at higher populations so you're constantly having to stop in the dark. The secret ruins have not materialized.

PR done properly this time I think

Fixes #28776

### CODE REVIEW

**Comment by WJohn** [comment]
maybe joan will take this as a challenge to rewrite/massively speed up our lighting.

fingers crossed!

**Comment by KorPhaeron** [comment]
Realistically there is not much Joan can do about our servers running slower with 70 people on them

**Comment by ChangelingRain** [comment]
I can ban everyone but the miners, that will help.

**Comment by KorPhaeron** [comment]
The other controversial thing we could do is give miners nvg

**Comment by GunHog** [comment]
But that is pointless because mesons work again! Miners do always take a set of NVG as standard kit when upgrading gear at Science!

**Comment by KorPhaeron** [comment]
I mean leave mesons busted but let miners use NVG instead so we can block sight with walls still

Obviously a big balance issue back on station if miners can see in the dark though

**Comment by Tacolizard** [comment]
@WJohn i mean, technically the reason lights update slowly is that they're throttled to run slowly, but if we removed the throttle it would probably still lag at higher pops.

**Comment by Xhuis** [comment]
Giving miners NVG that only work on lavaland seems like a good compromise here.. It both keeps ruins as unique and not trivial to find and solves the issue of being unable to see.

**Comment by Kromgar** [comment]
Can they be the fullbright variety of night vision?

**Comment by Xhuis** [comment]
I don't see why not.

**Comment by Repukan** [comment]
W H E R E
T H E
F U C K
A R E
T H E
S E C R E T 
R O O M S

**Comment by SgtxRootbeer** [comment]
why can't we just go back to mesons? i liked the old mesons...
maybe let the rnd nvg mesons work on lavaland with turfview?

**Comment by Repukan** [comment]
Bring our boys back home

**Comment by Yiu113** [comment]
What if you give them the NVG from the other PR, but make mesons work? That way, if they want mesons, they can go bug R&D for them, or get NVMesons later as an upgrade.

**Comment by Repukan** [comment]
Why are we nerfing miners even more behind the stupid gate of "make them RnD slaves" and "hidden rooms that will never be made!"

**Comment by YakumoChen** [comment]
@KorPhaeron does this give miner borgs Mesons again because they had it before mesons stopped working on lavaland

**Comment by KorPhaeron** [comment]
@YakumoChen 

I didn't remember to actually give it back to anyone at all come to think of it

**Pull request merged**
