### PR TITLE
Resprites kitsune masks and makes them adjustable

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
Resprites the kitsune mask, making it so it looks more foxy and fixing some consistency issues with the mob sprite such as the addition of the top stripe while making the color scheme consistent with other GAGS items.
Kitsune masks are also now adjustable by using them in-hand
image
dreamseeker_VQKSlC8mM8
dreamseeker_9hDiKmeBzY

## Why It's Good For The Game
Makes the mask look cleaner, consistent and better looking while giving players an option to adjust the mask at will, allowing for more customization options.

## Changelog
:cl: Hardly
image: Resprited kitsune masks
image: Kitsune masks are now adjustable. Use it in-hand!
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
Oh Hell Fucking Yes. Certainly out of scope for this PR, but is there any chance you could mess with the subtype or something in order to allow Kitsune masks to be used as internals when down? It'd be on the same level as QoL as the clown/mime masks allowing internals, and it'd be very fucking appreciated by me.

**Comment by Hardly3D** [comment]
I could give that a go on a separate PR, neck scarves also have internals so I'd imagine it'd probably make sense for this one to have one too.

**Comment by Sadboysuss** [comment]
Kitsune mask is just another mask, so it wouldn't make much sense for them to have internals unless the consistency was upheld with all the other masks

**Comment by carlarctg** [comment]
slippery slope

**Comment by ExcessiveUseOfCobblestone** [comment]
why do neck scarves have internals lol?

**Comment by carlarctg** [comment]
oh also. good sprites but the mask item rly doesn't look like a fox, it looks like a cat. usually the ears are taller and there's a pronounced snout at the bottom

**Comment by Wallemations** [comment]
> why do neck scarves have internals lol?

they _what?_ that makes zero sense

**Pull request merged**
