### PR TITLE
replaces ragin mages (deathmatch map) with a cooler map

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

image

port of https://github.com/fulpstation/fulpstation/pull/1159

## Why It's Good For The Game
og map was just a copypaste of the wizden idk whats so cool about that

## Changelog
:cl:
add: replaced the ragin mages deathmatch map with a new one
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
this really does not look like a good arena for combat at all

**Comment by MMMiracles** [comment]
map seems incredibly cramped for a PVP arena, lots of 1x1/2x2 spots that just funnel people/projectiles. i get its a meme map for ghosts to kill each other in but it honestly doesn't seem that fun to fight in?

**Comment by mc-oofert** [comment]
> map seems incredibly cramped for a PVP arena, lots of 1x1/2x2 spots that just funnel people/projectiles. i get its a meme map for ghosts to kill each other in but it honestly doesn't seem that fun to fight in?

most of the spells ignore these obstacles

**Comment by mc-oofert** [comment]
> map seems incredibly cramped for a PVP arena, lots of 1x1/2x2 spots that just funnel people/projectiles. i get its a meme map for ghosts to kill each other in but it honestly doesn't seem that fun to fight in?

i suppose this guy hasnt played the previous map

**Comment by sylvia-from-fulp-station** [comment]
we are so back #fulpstationsweep

**Comment by sylvia-from-fulp-station** [comment]
>lots of 1x1/2x2 spots that just funnel people/projectiles

you take a risk pushing for the OP wizard loot boohoo

**Comment by mc-oofert** [comment]
turns out most of the rooms were just copypastes of eachother so i redid the rooms a little

**Comment by SomeoneYouProbablyKnow** [comment]
On the one hand there's kinda no reason why we can't have two mage maps since there isnt much opportunity cost for deathmatch, it's self contained and silly. But on the other this map doesnt have those annoying fucking lootboxes

**Comment by WarerBrow** [comment]
could you please add some fire extinguishers to the map? every fucking match it becomes a chaotic fireburning mess, without a possibility to quickly put yourself out

**Comment by Xackii** [comment]
make it more flexible for movement

**Comment by Jacquerel** [comment]
> > map seems incredibly cramped for a PVP arena, lots of 1x1/2x2 spots that just funnel people/projectiles. i get its a meme map for ghosts to kill each other in but it honestly doesn't seem that fun to fight in?
> 
> i suppose this guy hasnt played the previous map

If you're replacing a shit map you should replace it with one which doesn't have the same problems.

**Comment by mc-oofert** [comment]
> > > map seems incredibly cramped for a PVP arena, lots of 1x1/2x2 spots that just funnel people/projectiles. i get its a meme map for ghosts to kill each other in but it honestly doesn't seem that fun to fight in?
> > 
> > 
> > i suppose this guy hasnt played the previous map
> 
> If you're replacing a shit map you should replace it with one which doesn't have the same problems.

most objects dont block projectiles

**Comment by Rex9001** [comment]
Why cant we have both?

**Comment by Xackii** [comment]
> Why cant we have both?

map vote in ragin mages

**Pull request closed without merging**
