### PR TITLE
Reworks metastation's xenobio

### LINKED ISSUE #19903: [Metastation] The vents in the xenobio kill room are messed up they are both exhaust no intake
image

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Metastation's xenobio has been slightly modified to avoid getting hit by some standard shuttles.
/:cl:

Fixes #19903
coiax's PR (#22669) had some points, but he bogged it down with a change to xenobio itself, and now I'm doing the same thing.
Notably; some shuttles would just fucking slam into it, that no longer happens+there's the mentioned getting-around-the-shuttle gap, and the air canister is now a large tank.

derp installation juliet 2017-01-03 210620

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Also that increasingly long glass hallway to xenobio got really on my nerves and now it's just a straight 5 tile thing fuck yeah

**Comment by TehZombehz** [comment]
That glass hallway always drove me insane. Thanks.

**Comment by GunHog** [comment]
The spare clothes closets from the other PR is a good idea, though. New life need not go naked!

**Comment by Metacide** [comment]
Looks very nice 👍

**Comment by coiax** [comment]
I'm fine with this

**Pull request merged**
