### PR TITLE
TOO SOON, EXECTUS

### PR DESCRIPTION
**Pull request by ghost**
I guess I've finally gone insane, because I've decided to take on the _monumental_ task of making an underwater station. The first iteration will simply be a submerged version of BoxStation with relevant edits, mainly to see if the concept will work and if people enjoy it.

Forum thread can be found [here](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=6980&p=187616#p187616) and design document can be found [here](https://docs.google.com/document/d/1hPUIwZKIrdnLkV3QXxdupStwCVhY0wnrAEvZBLQT2JI/edit?usp=sharing).

This is obviously DNM and will receive a tremendous amount of overhaul before it's ready for play. Anyone that wants to contribute should contact me on #coderbus.
# EDIT: I am closing this PR until I feel that the map has had enough time to be flesh itself out and become something tangible. I am not abandoning this, though.

### CODE REVIEW

**Comment by RemieRichards** [comment]
This is too soon to be making a PR.

**Comment by Xhuis** [comment]
Are you sure? I was told to do the same thing with shadowling, and I figured I would do this to let people track my progress.

**Comment by RemieRichards** [comment]
If it will motivate you, sure, keep it open, you already have the thread now.
But I'm of the idea that if a project dies silently without people getting excited, it's better than working people's hopes up.

**Comment by Incoming5643** [comment]
It's too late they're already hyped

**Comment by RemieRichards** [comment]
@Incoming5643 refer to
>you already have the thread now.

**Comment by Xhuis** [comment]
You make a good point and I don't want to give people the illusion that it's _READY RIGHT NOW GET HYPE AAAA_. I'll close it for now and re-open it once I have something worth showing off.

**Comment by PKPenguin321** [comment]
I'm hype

**Comment by X-TheDark** [comment]
I'm hype for the changes you'll have to do to atmos to handle water (and presumably, everything else) in a time-efficient manner.

**Comment by Xhuis** [comment]
Atmos will be unaffected. Water will not be handled through atmospherics but is its own separate entity.

**Pull request closed without merging**
