### PR TITLE
Fixes UO45 and MO19 for real.

### LINKED ISSUE #13030: UO45 and MO19 lockers are still invisible.
I see you decided to replace *some* of the lockers with default ones, but you realize I put custom made ones specifically to avoid having round-start items being spawned into those, right? So not only are some of the lockers still invisible, but all the lockers you replaced now have all the default equipment plus everything that was on that tile, leading to quite a few duped items.

Also one of the walls in UO45 is still a shuttle wall, and there's still a wall in front of one of the maint doors in the main lobby.

EDIT: And an extra wall next to the elevator bathroom.
EDIT2: And an extra wall next to the vendors in the lobby area.

Come on, man.

EDIT3: All the invisible lockers on MO19 are still invisible. This wasn't fixed at all! Additionally, all the indestructible walls that form the border of MO19 (and likely UO45) are bugged and look like default walls. You need to swap them with turf/indestructible/riveted walls, and then icon swap them all to "rock".

### PR DESCRIPTION
**Pull request by WJohn**
Fixes #13030 and everything listed in there.

These maps should be properly playable now.

### CODE REVIEW

**Comment by Aranclanos** [comment]
add an image of a before and after in the OP

**Comment by octareenroon91** [comment]
Consider adding drone shells to uo45 please.

**Comment by WJohn** [comment]
There's almost nothing different, aran. The only changes are that you can actually see the lockers now, as well as the invisible doors.

**Comment by Aranclanos** [comment]
add an image of a before and after in the OP

**Pull request merged**
