### PR TITLE
Mining Gear Resprite

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

a resprite of a lot of mining gear by meyhazah and onule
also resprites the ice miner demon from ice box by meyhazah
image

## Why It's Good For The Game

soul

## Changelog

:cl: MeyHaZah, Onule, Fikou
imageadd: mining gear resprite
/:cl:

### CODE REVIEW

**Comment by ArcaneDefence** [comment]
This touches a lot of sprites and has no pictures in the pr body :(

**Comment by Fikou** [comment]
> This touches a lot of sprites and has no pictures in the pr body :(

its 4 am ok theyll come tomorrow i need to sleep

**Comment by CRITAWAKETS** [comment]
I feel like most of these while looking technically better just end up looking worse than the current sprites. Especially the PKAs, the pickaxe and the jump boots. Also why is the advanced scanner isometric? Why is the kinetic crusher cut off at the end? Most of the outlines on the sprites are too harsh aswell.

**Comment by Mey-Ha-Zah** [comment]
> Also why is the advanced scanner isometric?.

Onule originally made two scanner sprites, one more like the original and the isometric. I figured, since there is no way to visually tell an advance scanner from a regular, to use both and give the isometric one to the adv. version. Personally I love it,. which is why I did it.

**Comment by CRITAWAKETS** [comment]
> Also look me in the eye honestly and tell me, a pair of jack boots with two white lines slapped onto it is a better design than the new jump boots.

Actually, it is. The new jump boots kinda look ugly and i think they're the worst resprite in this.

**Comment by AndroidMK2** [comment]
The "memento.on", "memento.off" is the memento mori talisman or something else?

**Comment by Mey-Ha-Zah** [comment]
> why was the previous jump boots sprite replaced it looked cooler image

unfortunately, there was a previous pr 2 years ago trying to give shoes that perspective which was when I believe that sprite was originally made. It was reverted and one of the maintainers said they didn't want shoes to have that perspective. These new boots were made by me to update the boots to Onule's new design but still be consistent with ss13 boot sprites as they are, which is why they may stand out a little bit. Admittedly I'm not AS good as Onule.

**Comment by Fikou** [comment]
> Why is the kinetic crusher cut off at the end? Most of the outlines on the sprites are too harsh aswell.

this is the case with the current sprite too and u never notice baby

**Review by Krysonism — APPROVED** [review]
Good sprites, if anything ends up looking off ingame we can always touch it up later.

**Pull request merged**
