### PR TITLE
Revert "[s] Prevents a certain kind of antag-rolling abuse."

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/tgstation#44056

Don't enforce "your" way to play the game on other players. Especially not through code.

### CODE REVIEW

**Comment by optimumtact** [comment]
gonna need that big ole ckey before you can contribute sorry bud.

**Comment by Conot** [comment]
Hi mrty

**Comment by HideAndSeekLOGIC** [comment]
do what normal people do and set captain to high and hos to medium before calling the shuttle at 20:00 sharp

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
@optimumtact stop selectively enforcing your made-up rules that aren't even written anywhere in CONTRIBUTING.MD. even so, i would never give such identifying info to a false god such as yourself.

**Comment by nightred** [comment]
Checking for valid roles on join is a good and valid check.
I agree with the original PR, and do not agree with this.

**Pull request closed without merging**
