### PR TITLE
Implants work on /living mobs

### PR DESCRIPTION
**Pull request by AnturK**
:cl:
add: Implants now work on animals.
/:cl:

This time actually working.

### CODE REVIEW

**Comment by jughu** [comment]
Inject cayenne with macrobomb the ultimate kamikaze fish

**Comment by Ratvar** [comment]
You now can deconvert Ian from being rev?Need some nerf

**Comment by Armhulen** [comment]
>rev fails to shock you
>implant him with adrenals
alright have fun with that station

**Comment by XDTM** [comment]
Inject Ian a macrobomb and watch the greyshit that kills him get gibbed

**Comment by ShadowDeath6** [comment]
branch name

**Comment by KorPhaeron** [comment]
Cool

**Pull request merged**
