### PR TITLE
Adds disablers for mechs

### PR DESCRIPTION
**Pull request by VileBeggar**
## About The Pull Request
Adds a simple disabler for mechs.

## Why It's Good For The Game
The stun rework yanked the tasers from mechs, making it so that the only non-lethal options that mechs have is flashbangs. This PR just adds disablers so that mechs have something else to take down people with without killing them.

## Changelog 
:cl: Vile Beggar
add: Mechs can now be equipped with disablers.
/:cl:

### CODE REVIEW

**Comment by Jimmius** [comment]
i don't like that you're making "actual PRs" that "improve the game".

what the hell man

**Comment by VileBeggar** [comment]
> 
> 
> i don't like that you're making "actual PRs" that "improve the game".
> 
> what the hell man

who said that this improves the game?

**Comment by WJohn** [comment]
The question needs to be asked if mechs need stun weaponry at all, as they are unable to make arrests or carry prisoners away.

Should they instead be focusing on being pure firepower, or should they reach a middle ground where they're able to do firepower *and* also be able to arrest people if ever we gave gygaxes the ability to use the odysseus sleeper? Does something that powerful like that deserve to also be able to engage in stun combat or would it be completely asinine?

**Comment by davethwave** [comment]
Honestly I don't see the reason why having some form of non lethal stun is a problem. Better than using a flashbang on everyone nearby.

**Comment by wesoda25** [comment]
Why would a mech need to detain anyone in the first place?

**Comment by ATH1909** [comment]
Maybe add a module that'd let mechs open or close lockers and/or a module that'd let them apply cuffs? They could then become a walking prison, which I think'd be pretty rad.

**Comment by wesoda25** [comment]
^ perfect idea of what not to do, that would become so horribly cancerous, now the shitty players mechs attract can valid hunt to peak performance.

**Comment by dr-bee** [comment]
I actually like the new stunless mechs. Mechs should be a fucking hammer. If you need to take out a person non-lethally dont bring a fucking tank.

**Comment by optimumtact** [comment]
I am open to the idea of mechs not having non lethal options

**Comment by GuyonBroadway** [comment]
Its so you can tell greytide mcshitler to stop toolboxing your mech in a way that doesn't cause every validhunter in a 30km radius to jump up your arse.

Cus lets face it those little fuckfaces will have "HELP DURAND ROGUE!!" in a copied to clipboard before they start toolboxing you so as to spam it the moment you decide to put an end to thier vandalism. Then mister "armoury in my backpack" will be more than happy to shoot mech ask questions later.

**Comment by davethwave** [comment]
The sprite seems to be invisible or missing for the disabler.

**Comment by VileBeggar** [comment]
@davethwave i didn't realize until now that it got lost while commiting stuff, and that's not epic imo

**Pull request merged**
