### PR TITLE
Added barricades to the old smelter on the asteroid.

### PR DESCRIPTION
**Pull request by Buggy123**
Oh god miners please stop using it.

But no really this is one of the best things asteroid station did, why haven't we done this on normal mining yet?

### CODE REVIEW

**Comment by lzimann** [comment]
Thought there was one already, even a note saying to use the ore machine on station.

**Comment by Buggy123** [comment]
There was a note, but not barricades. Also why the fuck didn't this compile?

**Comment by MrStonedOne** [comment]
You see how it says The Travis CI build could not complet... 

That's means it was an error trying to check, not that the check failed.

**Comment by Buggy123** [comment]
So, I can blame Travis?

**Comment by octareenroon91** [comment]
Barricades are too much. Maybe grilles?

Can we hide an ORM (board?) on z5?

**Comment by Buggy123** [comment]
Asteroid has barricades blocking the old ore smelter, I don't see how this is really a problem. I mean, its mining, it'd take 20 seconds to clear with a pickaxe, and it fits thematically.

**Pull request merged**
