### PR TITLE
makes the toy emagg look more obvious

### PR DESCRIPTION
**Pull request by improvedname**
changed the fake emagg you can get from the arcade machine to be more obvious
so you dont have people validing you over a emagg
because >forced to use a joke antag item is bad design because why would you be forced to use against a airlock and ruin the airlock in entirity just to know its real

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
the fake emag probbably shouldn't be exactly the same, but I think changing the sprite and description would be better than changing the name

**Comment by davethwave** [comment]
Please rename your pr to something else. Your going to get unnecessary hate due to that title.

**Comment by ExcessiveUseOfCobblestone** [comment]
I love how we have blatant antag items that are only differentiated by 3 letters in front of their name (and they don't ACTUALLY do anything) that people complain about when they get beat up to a pulp when they literally act like an antag with them.

**Comment by improvedname** [comment]
shouldnt be beaten up for something you won from arcade :(

**Comment by 81Denton** [comment]
The whole point of fake traitor items is that they look convincing and make valid hunters angry

**Comment by improvedname** [comment]
except it wont make validhunters angry but the person having this one because you can valid somoene over a toy and get away with it

**Comment by ExcessiveUseOfCobblestone** [comment]
Just seems like a copout to add 3 letters to an object's name but otherwise have it 1:1 in appearance, proceed to act like it's the real deal, then hide behind admins when you get canned for it.

The real solution would be to move blatant killbait/banbait items out of the arcade rather than going "look mods, it said toy how could they not have noticed????" In a game where there's a lot of information being processed exclusively through visuals (including text) with only 1 pair of eyes, especially when they're fixated on how you're purposely using the ~~traitor item~~ toy.

**Comment by RandomMarine** [comment]
Nobody's forcing you to pick the thing up.

**Comment by improvedname** [comment]
except the toy emagg is called like a emagg and has the same descirption like a emagg unless you get me one i just cant think of one

**Comment by CPTANT** [comment]
Just change the description.

**Comment by improvedname** [comment]
to what???

**Comment by MrDoomBringer** [comment]
👎 because you call it an "emagg". Why are there two "g"s? 

it's short for electromagnetic not electromaggnetic smh

**Comment by Tlaltecuhtli** [comment]
👎  because bad changelong

**Comment by MrDoomBringer** [comment]
Also 
>To what??

Just append something like "you notice 'made in spacechina' stamped on the back" or "closer inspection reveals the card to be a poorly painted piece of plastic"

**Comment by vuonojenmustaturska** [comment]
you're valid if you have this though, toy or not

**Comment by ExcessiveUseOfCobblestone** [comment]
Getting killed because you had a toy version of a syndicate item is so SS13 imo.

**Comment by improvedname** [comment]
oke how about dis

**Comment by Iamgoofball** [comment]
this is literally working as intended

**Comment by MrDoomBringer** [comment]
@BebeYoshi, you shouldn't have to risk irreversibly emagging equipment just to test if an item is a toy or not.

**Comment by Iamgoofball** [comment]
yeah just give it an inventory description like the rest of the toys then

**Comment by improvedname** [comment]
OKE FINE FINE I JUST VALID PEOPLE OVER TOYS

**Comment by BebeYoshi** [comment]
@MrDoomBringer I meant using in hand like pressing Z, clicking on it, I'm pretty sure it honks if you do that

**Comment by MrDoomBringer** [comment]
@BebeYoshi, oh. That might be a good idea, but I'm worried that people wouldn't think to use it in their hand, as there wouldn't be an IC reason to. (They would have to know beforehand, from looking at the code or something, that you can inhand the emag yo test it)

**Pull request closed without merging**
