### PR TITLE
TGUI buttons do not fully grey out while the UI is still updating

### PR DESCRIPTION
**Pull request by sohpeach**
## About The Pull Request
This allows the state of buttons to be seen when a TGUI's status is UI_UPDATE. That means if you take a step back from an open display, rest next to a display, are observing, etc., you will still be able to see the buttons without them all being greyed out.

The buttons get desaturated to indicate that they are unusable, but I'm not so sure about the appearance. I think it needs to be something else (pls help):
image
image (this middle one is the only change)
image

You'll also see that I modified `thermomachine.ract` to use state attributes instead of style attributes. Without this change, the disabled buttons would end up with undesired styling when they should be greyed out. I think there needs to be some confirmation on whether code should be using style or state attributes for this sort of thing.

At this point I have probably written more text here than code. It's a simple change.

## Why It's Good For The Game
If you've got the UI for something open you can already see most of its state (text, numbers, whatever.) I think it makes sense to see the state of buttons too.

It also makes observing a few machines such as filters or portable scrubbers better as you'll be able to see their settings.

## Changelog
:cl:
tweak: TGUI buttons do not fully grey out while the UI is still updating
/:cl:

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Good concept, the difference in the colors is a little hard to spot though. Grey and the soft blue we use are pretty close already, maybe halfway between is just not enough differentiation?

**Comment by optimumtact** [comment]
I don't get the point, the grey is to indicate unuseableness, and these buttons are effectively unuseable.

Why would it matter to be able to differentiate between unuseable due to difference and unuseable due to machine status from a distance?

**Comment by AnturK** [comment]
So you can tell what toggleable buttons are on. This is really only relevant for filters since they don't change the button in any other way.

**Comment by willox** [comment]
> I don't get the point, the grey is to indicate unuseableness, and these buttons are effectively unuseable.
> 
> Why would it matter to be able to differentiate between unuseable due to difference and unuseable due to machine status from a distance?

I got that sort of feeling towards the end of submitting this PR. Maybe there's some UI change that can be made specifically to the machines I wanted to make observable instead.

**Comment by optimumtact** [comment]
no it makes sense to be able to see what items are toggled, but I'd do it with a cross hatch instead.

so it'd be grey cross hatched with red if it's toggled off and grey cross hatched with green if it's toggled on

**Comment by willox** [comment]
The cross-hatching sounds like it'd look good, but I'm not sure about how to achieve it. What IE version is targeted?

**Comment by optimumtact** [comment]
I would say ie 11 realistically, ie9 if you wanted to include wine users

**Comment by optimumtact** [comment]
they use no frills mode though

**Comment by SpaceManiac** [comment]
Realistically Wine only goes up to IE8, but it's fine if a particular style doesn't appear if the interface still basically works.

**Comment by willox** [comment]
Ended up with this: 
image

I think it looks nice, but it's not easy to transition these sort of backgrounds. Apparently it can be done, but I'm not wizard enough at CSS for it.

**Pull request merged**
