### PR TITLE
Fixes away missions not loading

### PR DESCRIPTION
**Pull request by Cyberboss**
These take forEVER to load, holy shit. I need to move it out of initializations.

### CODE REVIEW

**Comment by WJohn** [comment]
but no one uses these

**Comment by Cyberboss** [comment]
Downstreams m8

**Comment by AnturK** [comment]
Yep, downstreams are the whole reason feature were not gutted completely yet.

**Comment by optimumtact** [comment]
Do you actually know of any downstream specifically using them, or is this just an accepted fact with no basis in reality?

**Comment by Cyberboss** [comment]
@Quadbreak does

**Pull request merged**
