### PR TITLE
[s] quack!?

### PR DESCRIPTION
**Pull request by Jordie0608**
test of https://github.com/blog/2247-improving-collaboration-with-forks

### CODE REVIEW

**Comment by Jalleo** [comment]
Image of a Duck.jpg)

**Comment by Incoming5643** [comment]
Not sure if I'd use this, but it's a neat feature for those of us without trust issues

**Comment by optimumtact** [comment]
It's mostly intended for noobs who don't understand how the standard github collab model works (you make a pr to my repo and then I make pr's back to your repo if I have suggestions for changes)

**Comment by Razharas** [comment]
You can now improve the balance in the goofs pr and merge it all in the browser
Nice

**Pull request closed without merging**
