### PR TITLE
Basic Space Dragon

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Converts Space Dragon from simple to basic mob.
Its behaviour should largely be the same, but as always it's not impossible something slipped through the cracks.
I made _two_ intentional changes though.

Change the first:
I made its wall tearing behaviour into a component, this also for two reasons.
The first reason is that it's much more reasonable than the wall smashing other mobs get and we probably _should_ go through and use this instead on several of them.
The second reason is so that I could make it visually cooler.

dreamseeker_gOdVoWhhyZ
Instead of one action bar after which a wall disappears, it's now three action bars with 1/3rd of the duration which progressively show the wall being damaged. If you're stood on the other side you can frantically try and weld it shut again while it is still being attacked, which I think is fun.

Change the second:
I refactored the existing "door prying" component used only by Faithless mobs and also put it on the Regal Rat (who should have been using it already).
I then also gave it to space dragons if _for some reason_ they would rather pry open a door rather than smash the wall next to the door. This doesn't seem like a notable balance change, given that they can destroy RWalls.

Side benefit is that as usual, all of the bespoke actions are now `mob_cooldowns` so you can give them to other mobs.

Other code changes:
Went through and made our three separate implementations of "breathing a line of fire" to actually share a typepath and implementation.
Added a check for "eating a mob extinguishes it" in the space dragon unit test, because I suspect it was broken (called `extinguish` instead of `extinguish_mob`).
I made mob actions require consciousness and not being incapacitated by default because I got tired of pasting this onto every ability, I actually checked which abilities this should affect this time I swear.

## Changelog

:cl:
refactor: Space Dragons are now basic mobs, please report any unexpected behaviour.
balance: You can now see that a space dragon is destroying a wall with a visual indicator of the wall being damaged.
balance: Space Dragons can pry open airlocks.
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
It'd be cool if you could add an animation of the fire breath (just a reskinned rust plume), but that might be out of the scope of this

**Review by san7890 — CHANGES_REQUESTED** [review]
some nits, some code issues because i woke up early and am bored

**Comment by IndieanaJones** [comment]
Very nice. Does fire breath and wing gust still work like it used to (ranged left-click and right click)?

**Comment by Jacquerel** [comment]
> Very nice. Does fire breath and wing gust still work like it used to (ranged left-click and right click)?

Yes

**Comment by moocowswag** [comment]
A slow wall tearing ability that we can give to mobs means we can finally curb down on obj damage which was inflated to extreme proportions because we had to make airlocks and other station structures hard to damage for regular crew but we couldnt gay baby jail mobs that cant get access ids.

This pr actually has a lot of potential to impact a lot of things (like how inflated obj damage on everything made space dragon portal so flimsy despite not being designed to be that way)

**Pull request merged**
