### PR TITLE
Greatly increases Pun Pun's abilities and strengths (using desk bells, cross stun immunity)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Pun Pun has a new AI, with it they received the following:
1. Instead of screeching/roaring/scratching/jumping/rolling, Pun Pun will instead sing/dance/bow/clear throat/sign.
2. Pun Pun now rings desk bells instead of finding random shit to pick up, and doesn't intentionally seek out weapons.
3. Pun Pun has a higher chance of giving people stuff in their hand, so the Bartender can give them a drink and let them go walking around.

Additionally:
* Pun Pun is now immune to being hardstunned by walking into them, giving them a little more bite for greytiders beating them up.
* Monkeys can now use desk bells.

## Why It's Good For The Game

I like Pun Pun and when Monkey AIs were originally added, there was a note about giving them a unique AI. Since we're slowly turning the poor monkey into an actual Bartender assistant, I find it thematic that they would ring the bell and give out drinks in their hand, as if the Bartender taught them themselves.

For the hardstun immunity, I mostly did it because I find it annoying for a Bartender to have to carefully navigate around Pun Pun to not knock them over and make them drop an instrument (or anything else) in their hand, but it also works as a buff to people trying to kill them. Pun pun is a unique monkey so I don't believe they should be as easy to kill as any other.

Desk bell addition was necessary for Pun Pun to use it.

## Changelog

:cl:
add: Pun Pun now gives stuff in their hand frequently and rings desk bells.
add: Pun Pun now has gentleman-like emotes, rather than screeching and roaring.
balance: Pun Pun no longer looks for weapons in their off time.
balance: Pun Pun is no longer vulnerable to stuns by being walked into.
qol: Monkeys can now use desk bells.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
tbh I think the game would be improved in general if the weird npc monkey hardstunning-upon-being-crossed mechanic was removed altogether, but maybe that's just me

**Comment by bluetshirtguy** [comment]
well, as annoying as it is he can be turned to burger quick enough if he rings the bell too much.

**Comment by Shadowflame909** [comment]
mfw i give punpun a tip and he gives it to the clown instead of the bartender

**Comment by Ghommie** [comment]
> tbh I think the game would be improved in general if the weird npc monkey hardstunning-upon-being-crossed mechanic was removed altogether, but maybe that's just me

It was originally meant to stumble monkeys that were trying to cross other monkeys (like when you walk into beepsky while it's chasing an animal) to stop them from swapping position with each other while chasing a target.

At some point, that's changed, either intentionally or not, which lead to monkeys getting stumbled upon being crossed by anyone instead of while crossing another monkey.

**Pull request merged**
