### PR TITLE
Fixing a 18.18% chance of gibs streaking 50 tiles away.

### LINKED ISSUE #53811: Butchering sometimes produces excessively long blood trails
Also known as: BLOOD METEORS
Issue reported from  Round ID: [146508](https://scrubby.melonmesa.com/round/146508) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

(it stopped when it hit a rockwall on the other side of hiero arena)
trail

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. 50 steps later.

## Why It's Good For The Game
This will close #53811.

## Changelog
:cl:
fix: Fixed a 18.18% chance of gibs streaking 50 tiles away... by canonizing it into an intentional 3% chance upon the request of the bunch of you on github.
/:cl:

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by TheBonded** [comment]
Just make it rarer, and keep it as a feature

**Comment by Losenis** [comment]
You don't realize what you're losing with this "fix" till you actually hear the shenanigans in comms as everyone spots the monkey gibs going all the way from main hallway to evac.

**Comment by TheBonded** [comment]
> You don't realize what you're losing with this "fix" till you actually hear the shenanigans in comms as everyone spots the monkey gibs going all the way from main hallway to evac.

Exactly. Just make this chance slightly rarer or leave it as is. It adds to the quirkiness of ss13

**Comment by ShizCalev** [comment]
I am definitely in favor of having this be a rare intentional occurrence.

**Comment by cacogen** [comment]
The odds of seeing this are already fairly low given the need for a long enough space but now people know about it they'll be doing it intentionally so I think it makes sense to make it rarer rather than remove it outright.

**Comment by Ghommie** [comment]
Upon request of the unanimous majority of the bunch of you, I decided to actually restrict this quirk to a 3% chance rather than outright remove it.

**Pull request merged**
