### PR TITLE
Suiciding with a gun blows your brain out

### PR DESCRIPTION
**Pull request by JJRcop**
:cl: JJRcop
add: Suiciding with a ballistic gun now actually blows your brain out.
/:cl:

You may have seen this message before:
before

But what happens? Well, you die for one, but, that's it... Your brain is ***still in your skull***. 
So, I fixed it. Here are some examples:

lawyer
It's hard being a lawyer, having to make sure the clown doesn't stay detained a second more than she needs to, but after lots of painful bickering back and forth, the detective lent his revolver. Now they won't need to listen to her anymore.

doctor
He just came out of the back, trying to hold a cultist down in a straight jacket, being subjected to the objective, irrefutable truth, spouting from their mouth. He decided he didn't want to live in a world where the blood god watches your every move.

bartender
Listening to your lame life story when she isn't even a counselor got to her head, then made a mess in the kitchen.

assistant
Oh... oh man I... Wow... Come on man, right in front of the bridge?

### CODE REVIEW

**Comment by JJRcop** [comment]
Probably a feature i guess

**Comment by Supermichael777** [comment]
are you feeling okay?

**Comment by JJRcop** [comment]
@Supermichael777 
engineer

**Comment by ShizCalev** [comment]
Darkest PR ever...

**Comment by Arianya** [comment]
If the brain hits a wall it should splatter the brain on to the wall as irremovable, pink-ish gibs.

They've suicided anyway so not like they were gonna come back into the round.

**Comment by XDTM** [comment]
Instead of splattering gibs on the landing point leave a trail of gibs until the brain

**Comment by FantasticFwoosh** [comment]
Ok calm down Kurt Cobain, but this is a nice immersion PR

**Comment by GunHog** [comment]
One of the best things about this game are the myriad ways of ending your own life! Also, a funny new way of self-braining that is ALMOST as good as ripping someone's head off with a surgical saw!

**Comment by nicbn** [comment]
Don't make the brain split out, only guts.

**Comment by RandomMarine** [comment]
I don't find it immersive at all to see the brain fly across the room whole and intact.

But it's hilarious so 👍

**Comment by Iamgoofball** [comment]
Put a gun in robotics for cyborg volunteers

**Comment by Kerbin-Fiber** [comment]
The russian revolver counts right? Blows your brains out too

**Comment by ShadowDeath6** [comment]
shooting yourself in the brain would destroy it though

**Review by Cyberboss — APPROVED** [review]

**Comment by DoctoreMad** [comment]
Do brain gibs look like gum?
Asking because I'm writing a novel, really.

**Comment by Artemiuz28** [comment]
As some already said, it should not just throw the brain away, but DESTROY IT. Or possibly make some new item with a sprite like "Damaged brain", which will appear after blowing your brains out.

**Pull request merged**
