### PR TITLE
Fixes butchered cats not dropping their ears and tails

### PR DESCRIPTION
**Pull request by jughu**
:)

:cl: Improvedname
tweak: cats now drop their ears and tail when butchered.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
this makes cargo cat factories produce 40% more credits than corgi factories add  a balance tag thanks

**Comment by jughu** [comment]
Who cares they can already make profit with just monkeys cat wunt hurto

**Comment by arsserpentarium** [comment]
Now we can craft cat'o'nine tails for erp!

**Comment by MrMaclang** [comment]
speedmerge needed

**Comment by Arianya** [comment]
brb butchering a cat so I can attach cat ears and a tail on people

**Comment by Grazyn** [comment]
Finally the CMO can butcher Runtime to become a catperson

**Comment by The-clown-known-as-Pepe** [comment]
👁 W 👁

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-4). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
