### PR TITLE
Makes gatling admin only

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
People are upset about this gun and I don't really have any good plan to balance it at this moment, so I am offering this PR as a temporary thing.

I think it's mostly fine in person vs person combat (2 hands+back, slowdown, doesn't stun, shots are weak) but it absolutely wrecks blob mode, and one gun is probably not as important as a game mode.

Downsides of the gun

-You move slow (doesn't matter vs a blob)

-Its inaccurate (doesn't matter vs a massive stationary target)

-Takes all hands+back (who cares vs blob)

-Does weak damage (it does double vs blob)

I'm not sure how to make it workable vs a blob, other than to say "you should have won before they got gatlings"

### CODE REVIEW

**Comment by GunHog** [comment]
Are you freaking serious? You are not even returning the SABR either? The Xray is as much of a blob killer as this one is, you do not need to be so kneejerk about this.

**Comment by KazeEspada** [comment]
This comes just a few tech levels before the xray.

**Comment by jughu** [comment]
The only thing that this makes OP is the fucking holdfire put a cooldown between bursts

**Comment by KazeEspada** [comment]
Its probably more of the lack of a need for charge, like you can stop xrays by killing the chargers.

**Comment by jughu** [comment]
Just make EMP's drain alot of their shit and make it knockdown poeple if they hold a item in second hand and try to shoot so poeple needs to be carefull

**Comment by jughu** [comment]
But really It isnt the lasers thats op its the hold fire without cooldown which let you cut you trough like a cake even the SABR wasnt that fast

**Comment by KorPhaeron** [comment]
@GunHog 

Not in the mood to be yelled at about them, need time to think of a better solution

**Comment by jughu** [comment]
Kor just make the gun overheat if hold it down how longer how more damage

**Comment by KorPhaeron** [comment]
I have to work on an overheat mechanic and figure out the numbers in that case. That takes longer than doing this

**Comment by Incoming5643** [comment]
if it's not there yet, add it to summon guns

**Comment by optimumtact** [comment]
The hand giveth and the hand taketh away

yall need to calm down

**Comment by KorPhaeron** [comment]
Not sure why this is getting thumbs down. I hate to kill my own stuff but it's not fair to throw an entire game mode out the window for it. Not happy about it but it seems like the best immediate action.

**Comment by GunHog** [comment]
My problem with this is that you took something away to give us this. You did not return what you took away.

**Comment by KorPhaeron** [comment]
I can put ths sabr back as well but I dont really feel comfortable with sabrs+roundstart pins

**Comment by PKPenguin321** [comment]
Sabrs suck anyways

**Comment by AdamElTablawy** [comment]
the option here is to rather than removing it nerf the speed output of the bursts severely OR snowflake something in to make it do it's normal damage versus blob.

But even then it's going to chew right through a blob, so it might end up having to be made fairly weak versus blobs just to stand a chance, increase the tech levels slightly, and give it some goddamn delay during and between bursts so you can't chain 500 lasers into a blob and call it a night

**Comment by Anonmare** [comment]
Laser Gatling should set you on fire if you fire it for too long tbh

**Comment by fizzle7** [comment]
Solution to all blob problems: "Get the worst possible uncooperative autistic crew every blob round and somehow magically force them to spread and go to mining and research and the others to stop the blob so you can get xrays and totally rektify le blobberino"
It's usually shortened to "get xrays lern to pley keke nub"

**Comment by LatD** [comment]
The main difference with x-ray guns and this gun vs blob is that x-ray gun is absolutely terrible against blobbernauts and blob spores. It does less damage than a laser gun and often ends up hitting the crew as well. This gun works pretty well against them and doesn't need recharge so in that way it's much stronger. 

I'd just add a power 8 required tech and leave it be. It would make it slower and harder to get than x-ray guns but still completely possible.

**Comment by KorPhaeron** [comment]
@LatD 

What does it take to get power 8? Is it something you can easily pull off during blob?

**Comment by Core0verload** [comment]
You had to DA broken bluespace power cell. Not the easiest thing to do, because you need a lot of charge-recharge cycles for it to break.

**Comment by Fox-McCloud** [comment]
I wouldn't bring the Sabr's back. Reason being, they're incredibly powerful, and science's niche should really be laser/energy based weapons---let cargo's "thing" be ballistics.

**Comment by LatD** [comment]
Bluespace batteries just need the DA upgraded which is most likely done at that point anyway. Then you can print them and after 1-4 deconstructions power should be 8. Using an exosuit fab also makes perfect batteries which would make it even faster. This is just a thing that would make it harder and slower to get but you don't need to break the batteries. Power tech also makes sense since it has some kind of internal power source.

**Comment by kevinz000** [comment]
Add something prototype-SMG like to R&D to compensate. This is quite the nerf as R&D doesn't have a spray and pray or a powerful weapon anymore :/

**Comment by Fox-McCloud** [comment]
If they get a "spray and pray" weapon, it should be something thematically coherent that fits in with this new design direction--slightly whacky, unique, and a design you can't acquire anywhere else---lightly also probably NOT an SMG, but laser/energy based. 

Let cargo be the ballistics department.

**Comment by KorPhaeron** [comment]
Well I guess nobody wants to merge this, and blob is winnable by ordering thousands of laser guns anyway, so I guess I'll make an overheat mechanic or something

**Pull request closed without merging**
