### PR TITLE
Improving upon the Metastation bar design

### PR DESCRIPTION
**Pull request by redmoogle**
Makes the Metastation bar less claustrophobic by making the art storage slightly smaller and pushing the machines up one.

**Changes:**
Moves the Dispensers and tables up one
Moves the art supply's around
Moves the firelock by the bar up one
Moves the air alarm by the bar down 1
Adds a window on the side of the bar
Add a little extra preparation space
Add a plant in the bar

**Picture/s:**

image

## Why It's Good For The Game
Makes the bar feel a lot less claustrophobic

:cl:
tweak: made the bar slightly bigger on Metastation
tweak: made the art storage slightly smaller on Metastation
rscadd: added plants and preparation space in the Metastation bar
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
Hopefully I haven't big brained myself

**Comment by TheChosenEvilOne** [comment]
Pictures please.

**Comment by redmoogle** [comment]
image
@TheChosenEvilOne

**Comment by redmoogle** [comment]
image
I just doubled brained myself help @TheChosenEvilOne

**Comment by TheChosenEvilOne** [comment]
> _maps/map_files/MetaStation/MetaStation.dmm:	step_y = -28
> step_x/step_y variables detected in maps, please remove them.
Travis failed.

**Comment by redmoogle** [comment]
shush shush I'm fixing it right now

**Comment by TheChosenEvilOne** [comment]
picture
picture2
make these part of the bar area.

**Comment by redmoogle** [comment]
that should be the last of modifcations @TheChosenEvilOne

**Comment by wesoda25** [comment]
claustro bar was better tbh

**Comment by redmoogle** [comment]
I thought about moving the art room entirely but there wasn't a good spot for it also merge conflict reee

**Comment by redmoogle** [comment]
what.

**Comment by redmoogle** [comment]
Someones going to have to help me with making the conflict go away

**Comment by redmoogle** [comment]
of course I closed it whoops

**Comment by Dennok** [comment]
What about this glass wondow to in 3 wall?

**Comment by redmoogle** [comment]
> 
> 
> What about this glass window to in 3 wall?

I'm going to assume you're talking about to wall between the main halls and drink machines and yeah I could do that but I also got to place down the newscaster and move the poster

**Comment by Akrilla** [comment]
I like it but the table under the newscaster seems a bit out of place. Seems just like an awkward, likely unused obstacle.

**Comment by redmoogle** [comment]
> 
> 
> I like it but the table under the newscaster seems a bit out of place. Seems just like an awkward, likely unused obstacle.

It's intended to be used as prep space and I could just remove it entirely

**Pull request merged**
