### PR TITLE
<oranges> what the fuck is the negation of zero

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by RemieRichards** [comment]
wouldn't even work anyway desu.

**Comment by Anonmare** [comment]
Man, that guy is really taking it out on Maianus. He's taking such a pounding yet he just takes it and gives as good as he receives.

**Comment by Iamgoofball** [comment]
@RemieRichards 
that's not what travis is saying

**Comment by Iamgoofball** [comment]
https://travis-ci.org/tgstation/tgstation/jobs/255188781

**Comment by RemieRichards** [comment]
compiling != working, you should know that.

**Comment by Iamgoofball** [comment]
we must testmerge to really put mainus to the test

**Comment by RemieRichards** [comment]
for example, if you wrote ```!0``` it would be replaced at compile time with the correct value, however:
```
var/A = 0
to_chat(world, !A)
```
The answer would remain 1, not the web url, you can't override operators like that, all you've done is given meaning to an exclamation mark char followed by a 0 char.

**Comment by Iamgoofball** [comment]
working as intended

**Comment by RemieRichards** [comment]
no it isn't, because you've not changed the value of the negation of 0, you've just said that ```!0``` these two symbols == a url on oranges website.

**Comment by Iamgoofball** [comment]
it's all about perspective

**Comment by RemieRichards** [comment]
```!goofball == GOOD```

**Comment by Iamgoofball** [comment]
working as intended

**Pull request closed without merging**
