### PR TITLE
Chasms will alert mobs below them when they form

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Feel like there should be some level of awareness for a mob when the ceiling explodes above them

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Was the scream noise & killing the tendril not enough warning?

Maybe you should put flashing lights on it.

**Comment by pudl** [comment]
@FantasticFwoosh gotta look out for the deaf players. up next is colorblind mode

**Comment by kevinz000** [comment]
lol
fwoosh doesn't read when kor said "BELOW THEM"
as in, you know, when the mobs fall through the chasm and falls onto the stuff below them?!!

**Comment by RemieRichards** [comment]
but kor DIDN'T say below them, he said above them.

**Comment by kevinz000** [comment]
Chasms will alert mobs below them when they form #30266
wait what?

**Comment by KorPhaeron** [comment]
The PR title says mobs below the chasm and the desc says the ceiling(chasm) above the mob, which is all consistent and correct

**Comment by kevinz000** [comment]
...
goddamnit im confused now.

**Comment by FantasticFwoosh** [comment]
Thats half true @pudl but there's already a lot of cue visually and audbily inserted. I understood what kor said about a ceiling, but that assumes that the ground beneath was a hollow chasm anyway at some point.

- Underground mining layer confirmed?

**Comment by Grazyn** [comment]
Because we lavaland underworld now. Kor has been working on it in secret but it's finally out of beta. Brace yourself, it's gonna be one HELL of a ride

**Comment by msgerbs** [comment]
I always kind of assumed that chasms formed _underneath_ mobs and that it was a hole you fell into (hence one moving onto one long after it forms will still kill you). This seems to imply that it's the opposite?

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
