### PR TITLE
Simplifies bullet calibers

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About The Pull Request

Pairs down most of the bullet calibers into light, medium, and heavy. There were a lot of them that were only used for one or two guns.

<details>
<summary>Summary of bullet calibers:</summary>

- Light Caliber Ballistic: Small bullets. Used by most automatic pistols and SMGs.
  - 9mm: Used by the Saber SMG, Uzi, stechkin, and the other syndicate pistol.
  - 9x19mm: Exclusive to the plastikov SMG.
  - 10mm: Exclusive to the surplus rifle
  - 7.12x82mm: Exclusive to the L6-SAW
  - 4.6x30mm: Exclusive to the security auto-rifle
  - .38: Used by the detective's revolver.
  - n762: Used by one of the russian revolver variants.
- Medium Caliber Ballistic: Midsized bullets. Used by a variety of guns.
  - .357: Used by the majority of the revolvers.
  - .45: Used by the C20-r SMG, tommygun, and M1911 pistol.
  - a556: Used by the M-90gl carbine and NT-ARG 'boarder'
  - a762: Used by bolt action rifles.
- Heavy Caliber Ballistic: Big bullets. Used by the sniper rifles and desert eagle. Basically a rename of the .50.
- Shotgun: Shotgun shells. Used by shotguns. Unchanged.
- Grenade: Grenades and bulky explosive rounds. Used by grenade launchers and the gyrojet pistol.
  - 40mm: Used by the grenade launchers.
  - .75: Exclusive to the gyrojet pistol.
- Rocket: Used by the rocket launcher. Basically a rename of the 84mm.
- Laser: Disposable laser cartridges. Used by the laser guns and laser minigun.
  - Laser: Used by laser guns.
  - Gatling: Used by the laser minigun. Folded into normal lasers.
- Energy: Energy lenses and emitters. Used by energy guns. Unchanged.
- Foam: Foam darts. Used by foam force and donksoft toy guns.  Unchanged.
- Arrow: Arrows. Exclusive to the bow. Unchanged.
- Harpoon: Harpoons. Exclusive to the harpoon gun. Unchanged.
- Hook: Meat hooks. Exclusive to the meat hook. Unchanged.
- Tentacle: Tentacles. Exclusive to the changeling's tentacle arm mutation. Unchanged
</details>

NOTE: _I have zero sense of game balance. Help._

## Why It's Good For The Game
- Crunches 24 calibers (16 ballistic) down to 13 calibers (6 ballistic).
- Ammo can be shared between guns. (Not sure if this is an upside or a downside honestly)
- People have been asking for this for a while.

## Changelog
:cl:
tweak: Bullet calibers have recently been standardized. Some guns are now fully capable of sharing ammunition with other guns.
code: Ballistic bullet calibers have been reduced to `LIGHT`, `MEDIUM`, `HEAVY`, and `SHOTGUN`.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Why is this good for the game?

**Comment by MrDoomBringer** [comment]
this is ridiculous lmao
also hell for balance
👎

**Comment by Low3** [comment]
Good in theory, but will need major rework of gun balance to work.

**Comment by itseasytosee** [comment]
How is this good in theory?

**Comment by TemporalOroboros** [comment]
@itseasytosee The coders have been talking about this for a while. I might as well do it myself so I can have some minimal influence over the process.
@MrDoomBringer I know, but it's going to happen at some point. I might as well give it a shot.
@Low3 I am aware. If you have any recommendations I will gladly try them.

**Comment by itseasytosee** [comment]
Could someone please explain to me why removing intricacy and realism from a game in exchange for nothing is a good idea?

**Comment by TemporalOroboros** [comment]
I'm as confused as you are, but the alternative is someone else making the same PR.

**Comment by itseasytosee** [comment]
This is incredibly confusing to me.

**Comment by necromanceranne** [comment]
Oh I thought this was generalizing damage at the same time and just renaming all these bullets into something generic, this is actually maybe not the way to do this if you wanna simply calibers.

You should probably aim to do something akin to a proposal by @Ryll-Ryll that just put all the bullets into a few limited categories of damage and calibers and keep them consistent across the board.

**Comment by MrDoomBringer** [comment]
@TemporalOroboros to clarify, have any _maintainers_ expressed significant interest in this? Because if it's just some coders who want this than their desires can be discarded

**Comment by TemporalOroboros** [comment]
@MrDoomBringer Last I checked oranges was one of the main proponents. I don't think I've really got a choice if I want any influence over the outcome.

**Comment by TemporalOroboros** [comment]
@MrDoomBringer Actually, I'm not all that sure. I'm pretty sure I've seen green names floating around the conversations over it. I'll have to ask.

**Comment by optimumtact** [comment]
don't open pr's you don't believe in in some weird ass attempt to get ahead of a supposed narrative

If a maintainer wants to actually change it, it won't matter if you open a PR or not

disappointed

**Comment by interestingusernam3** [comment]
T W E A K

**Pull request closed without merging**
