### PR TITLE
Revert "Settles the sabre/rapier debate once and for all"

### PR DESCRIPTION
**Pull request by Arianya**
:cl: Arianya
tweak: The sabre once again looks like a rapier. Don't think about that too hard.
/:cl:

Reverts tgstation/tgstation#31400

Reasoning: The new sprite is poorly drawn (wonky appearance, bad sheath) and the blade sprite itself breaks a "convention" (used loosely) of dedicated melee weapons having a / orientation. 

image

image

### CODE REVIEW

**Comment by WJohn** [comment]
Rotating the sprite takes literally one second to do, though I agree I'm not a huge fan of this sword sprite, it's not awful all things considered..

**Comment by vuonojenmustaturska** [comment]
why not contribute a better sprite instead?

**Comment by Arianya** [comment]
I see no reason to reinvent the wheel when the old sprite was perfectly fine.

**Comment by Repukan** [comment]
There's no such convention

**Comment by Arianya** [comment]
While theres clearly no "written in stone" convention, there's a clear precedent among our existing sprites.

There are some exceptions, notably the kitchen knife and chainsaw, but it holds true for the majority of melee weapons.

**Comment by Armhulen** [comment]
fix it yourself instead of reverting you dink

**Comment by Arianya** [comment]
@Armhulen Is there something wrong with the old "rapier" sprite that warrants fixing? I'm happy to put in the effort.

**Comment by calzilla1** [comment]
Tbh old sprite is better and has more contast

**Comment by WJohn** [comment]
Less contrast. It had less contrast. By definition it had less contrast.

**Comment by PopNotes** [comment]
what calzilla said, +1 from me

rapiers are cooler than sabres anyway

**Comment by KorPhaeron** [comment]
brightsabre

Do you mean you want something like that? It's not hard to rotate it and apply the colours from the rapier

**Comment by KorPhaeron** [comment]
brightsabre

I am not very good at spriting but it doesn't seem like it'd be difficult to rotate it/apply the rapier colours

**Comment by Arianya** [comment]
@KorPhaeron I agree its not a big ask to rotate it/apply the rapier colours but it still leaves a generally aesthetically unpleasing sabre/sheath combo.

**Comment by Supermichael777** [comment]
Its a proper saber, a slashing weapon tending towards quick motions with the wrist and elbow to produce the motion. Rapiers are more a stabbing weapon that's controlled from the wrist and shoulder with the thrust coming from the triceps and body movement.

Overall the captain would be far more likely to have a saber, the legitimate military weapon that stayed relevant up until the mass adoption of semiautomatic pistols in ww1(and on formal uniforms ever since) rather than the rapier, which died out in actual combat when drunks started dueling with pistols instead.

**Comment by uraniummeltdown** [comment]
Hell yes, the new sprite looks like ass.

**Comment by ExcessiveUseOfCobblestone** [comment]
This is a stupid bikeshed pr.

**Comment by PopNotes** [comment]
>This is a stupid bikeshed pr.

The original PR was a stupid bikeshed PR and this reverts it.

**Comment by Arianya** [comment]
I have no horses in the race as to whether its a sabre or a rapier or a kukri or a swiss army knife. I appreciate that you think it is @ExcessiveUseOfCobblestone, but if a maintainer or the headcoder said that its meant to be a kirpan then I'd accept that.

This PR is solely about the quality of the sprite, which is lesser to the old sprite. Thats not meant as a dig at Kor's codersprite, its just a fact of trying to sprite a curved blade in 32x32. The reason I call the old sprite a "rapier" is that I suspect it was originally sprited as a straight naval saber, which fits thematically, but was perceived to be a rapier due to the limitations of sprites.

Again, if theres anything about the old sprite that can be improved, I'm happy to put in the effort to improve it, but I don't see there being a good reason to start from a less pretty sprite simply to satisfy some weird drama llama I missed.

**Comment by optimumtact** [comment]
You can either fix the sabre sprite or close this PR, so I'll let you chose.

**Comment by Arianya** [comment]
Can I take option C and make a new straight sabre sprite?

**Comment by optimumtact** [comment]
As long as it doesn't look like a rapier and cause people to bikeshed over it

**Comment by Arianya** [comment]
Alrighty then.

**Comment by PopNotes** [comment]
what the fuck does bikeshedding mean here anyway
this game is built on insignificant fluff changes, it's the nature of the beast

**Comment by PopNotes** [comment]
Already a way better sprite, but the blade's tip looks kind of broken. 🤔 

Also, the comment oranges deleted was relevant to the discussion and didn't insult anybody. _Really makes you think._

**Comment by Bawhoppen** [comment]
popnotes is right

**Comment by Arianya** [comment]
Thats a classy sprite @Dorsisdwarf :smile:

I'm more then happy to use that as the base while redoing the sheath. Might fiddle with it a bit to give it a little more ornamentation, akin to the straight saber pic above. I agree the opaque handle looks better than the edgeless handle, though would need to mess with it in game to see how much of a difference it makes.

**Comment by PKPenguin321** [comment]
>changing the sprite instead of the name

**Comment by Bawhoppen** [comment]
What do you propose we change the name to Mr. PKP?

**Comment by PKPenguin321** [comment]
Well in kors PR his reason was "The captains sabre no longer looks like a rapier."
So why not just in that PR instead of changing the sprite change the name to rapier

**Comment by Bawhoppen** [comment]
Because it doesn't function like a rapier

**Comment by optimumtact** [comment]
We're not renaming it to rapier that is the end of that discussion

**Comment by optimumtact** [comment]
Closing in favour of #31615

**Pull request closed without merging**
