### PR TITLE
Adds the CRAZY HAMBURGER

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request

This adds a new burger for the Cooks to make. The CRAZY Hamburger. All you need is:
- Horse Meat (Actually just 2 pieces of steak)
- Red Hot Chilli Peppers (A single Chilli)
- Grass of Death (Cabbage)
- Oil from Iraq (15u Cooking Oil)
- Cheese from Sao Paolo from Brazil (2 cheese wedges)
- Bread made in Turkey (A Bun)
- A Flare + Green Crayon (For its flashy green smoke)

old sprite:
image

new sprite: 
crazy_hamburger_

## Is this spritecode?

OLD: Yes, yes it is. I made a slightly changed sprite and honestly would prefer a better-looking one tbh.
NEW: Nope, someone volunteered to sprite an actual CRAZY HAMBURGAR. Now it's no more spritecode.
## Why It's Good For The Game

https://www.youtube.com/watch?v=5af137qi_GM

## Changelog
:cl:
add: Added the CRAZY Hamburger as a craftable burger, for all the cooks who live in a society. Includes flashy green smoke.
/:cl:

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by ATH1909** [comment]
Would it be possible to make this produce green smoke under certain conditions?

**Comment by SgtHunk** [comment]
i can't promise anything, but if i do get the time i could try

**Comment by Krysonism** [comment]
The sprite is kind of sad.

I think for a novel food with no new effect it needs at least a cool sprite.

**Comment by SgtHunk** [comment]
@Krysonism Spritecode is no more
@ATH1909 Crazy Hamburger can now randomly produce a small cloud of green smoke

**Comment by AtlasRules** [comment]
it is horribal

**Pull request merged**
