### PR TITLE
Makes admins happier

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
fix: praying for antag now insta gibs you
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
> Doesn't compile

> Gibs ANYTHING that has the word antag in it

**Comment by ma44** [comment]
"hey man can i trade my anta-"
*gibbed*

it should check to see if you already have antag status, if you did then it should say you lost the grief lottery

**Comment by MoreRobustThanYou** [comment]
it now checks if you have antag status, plz reopen

**Comment by MoreRobustThanYou** [comment]
@Cyberboss I made it only do the givving if is_special_character is false

**Comment by kevinz000** [comment]
aren't you permabanned?

**Comment by Cyberboss** [comment]
Wrong PR

**Comment by MoreRobustThanYou** [comment]
@kevinz000 I still like to code >_<

**Pull request closed without merging**
