### PR TITLE
Gives zombies no hunger trait

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Zombies have no metabolism trait, so they cannot eat, but they still get hungry.
This means that overtime they will just begin to starve, destroying their mood, all while they can just sit and watch with no say over it.

## Why It's Good For The Game

An unavoidable slow drain to madness with no say over it whatsoever over it is a terrible thing to endure.

## Changelog
:cl:
fix: Zombies no longer get permanently hungry.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
make them eat brains

**Comment by ATH1909** [comment]
> make them eat brains

infectious zombies can use their claws to gain nutrition from eating corpses, but high-functioning ones... can't.

IMO, high-functioning zombies should either have the TRAIT_NOMETABOLISM trait removed from them or the TRAIT_NOHUNGER trait removed from them, but infectious zombies should keep their current trait list.

**Comment by JohnFulpWillard** [comment]
> 
> 
> > make them eat brains
> 
> infectious zombies can use their claws to gain nutrition from eating corpses, but high-functioning ones... can't.
> 
> IMO, high-functioning zombies should either have the TRAIT_NOMETABOLISM trait removed from them or the TRAIT_NOHUNGER trait removed from them, but infectious zombies should keep their current trait list.

Why should infectious zombies have no metabolism anyways? Not like they can pick food up.

**Comment by ATH1909** [comment]
> > > make them eat brains
> > 
> > 
> > infectious zombies can use their claws to gain nutrition from eating corpses, but high-functioning ones... can't.
> > IMO, high-functioning zombies should either have the TRAIT_NOMETABOLISM trait removed from them or the TRAIT_NOHUNGER trait removed from them, but infectious zombies should keep their current trait list.
> 
> Why should infectious zombies have no metabolism anyways? Not like they can pick food up.

their liver isn't alive to process reagents with

**Pull request merged**
