### PR TITLE
Fixes built APCs never getting an area

### PR DESCRIPTION
**Pull request by Cyberboss**
Whoever did this...
BAN HE!!!!

:cl: Cyberboss
fix: Built APCs now work again
/:cl:

Tagging #24510

### CODE REVIEW

**Comment by XDTM** [comment]
why would someone do this

**Comment by XDTM** [comment]
also high priority i can't build APCs at all right now

**Comment by KorPhaeron** [comment]
Jesus

**Comment by GunHog** [comment]
Using `src.` AND colons? Wowza.

**Comment by Incoming5643** [comment]
https://github.com/tgstation/tgstation/commit/f2c2a3b8c1342402b9313a35f7d2c33d6da96681

**Comment by AnturK** [comment]
Nice vintage shitcode.

**Pull request merged**
