### PR TITLE
Cauteries have heat, you can smoke with a space helmet

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Cauteries now have 'heat', like lighters, welders, etc.

You can smoke with a space helmet as long as you have internals on.

## Why It's Good For The Game

> Cauteries now have 'heat', like lighters, welders, etc.

Seems like an oversight. If an esword can do it so can a implement meant to sear wounds shut.

> You can smoke with a space helmet as long as you have internals on.

Space smoking is awesome.

## Changelog

:cl:
fix: Cauteries now have 'heat', like lighters, welders, etc.
qol: You can smoke with a space helmet as long as you have internals on.
/:cl:

### CODE REVIEW

**Comment by CoiledLamb** [comment]
you should atomize these to increase your GBP gains i think

**Comment by JohnFulpWillard** [comment]
if you're in a space suit in space, smoking a cig, i think it is weird that it does not affect the air you are breathing in at all

**Comment by carlarctg** [comment]
> if you're in a space suit in space, smoking a cig, i think it is weird that it does not affect the air you are breathing in at all

must we overcomplicate things ervery tim,e

**Comment by Loafin34** [comment]
smoking a cigarette in space should consume oxygen at a faster rate, requiring 20+ kpa instead of the 16.

**Pull request merged**
