### PR TITLE
Reverse revolver now comes in a box of hugs

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: A reverse revolver now comes in a box of hugs.
/:cl:

- You can now tell if the revolver you got in your surplus crate is a
REAL revolver, or a reverse one. Also, free hugbox.

Closes #23872. @Xhuis

### CODE REVIEW

**Comment by Xhuis** [comment]
h u g b o x

Yeah, this could work

**Comment by RandomMarine** [comment]
Can we make clowns start with a hugbox for their internals so that people won't meta HUGBOX = TRAITOR CLOWN

**Comment by kevinz000** [comment]
free @Haevacht

**Pull request merged**
