### PR TITLE
[GBP No Update] Smol brain forget that bananas have side sprite

### LINKED ISSUE #69089: Banana peel's inhands are (still) slightly wrong
## Reproduction:

The right facing and left facing inhands for banana peels is the same no matter which hand the peel is in

image

image

### PR DESCRIPTION
**Pull request by CursedBirb**
## About The Pull Request
I forget that bananas has side sprite
Fixes: #69089

## Why It's Good For The Game
Finally fixes wrong banana sprites

## Changelog

:cl:
fix: This time correct banana side sprite
/:cl:

### CODE REVIEW

**Comment by CursedBirb** [comment]
I have no idea what is going on

**Comment by Jolly-66** [comment]
Pull from upstream/master on whatever you're using, or fetch upstream/master. Your local might've been out of date.

**Comment by CursedBirb** [comment]
Gotta to it then and it will be last thing i do today as i really need some sleep

**Comment by Mooshimi** [comment]
please put 
Fixes: #69089
instead of just the number, in order to link it

**Comment by CursedBirb** [comment]
This is so weird

**Comment by dragomagol** [comment]
The failing lint likely isn't your fault, but you do have a conflict in `icons/mob/inhands/misc/food_righthand.dmi` that needs to be resolved

**Comment by CursedBirb** [comment]
God finally it worked

**Pull request merged**
