### PR TITLE
Meet the (New) Engineer! (Engineering Resprite Part 1)

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin, respriting a variety of clothing iconic to the engineering department!
In this PR, the changes include to:
- All Engineering Jumpsuits
- All Engineering Jumpskirts
- Insulated Gloves and Chief Engineer Gloves
- The Hazard Vest
- The Firesuit
- All of the hard hats!
image
image
 "But Entropy, you missed [X]!" Yeah that's bound to happen. I am aware that some things were ignored, such as the atmos fire suit, but they shall be done in a part two of this PR. Hopefully by covering 90% of the clothing, the 10% can be given the extra care it needs!
 
 Credits to: 
 - The Shiptest team for creating the original hardhat object icon
 - @SomeAngryMiner for creating the radiation suit for BayStation of which it was modified for the purposes of /tg/
 - @axietheaxolotl for some of the palettes, the worn versions of the work boots and more!

## Why It's Good For The Game
We near the full cleanup of the engineering department, and its part of the continued effort to make this game as clean as possible! Its also one of my favorite departments, and it was a blast to remake it :)

## Changelog

:cl: PositiveEntropy, Azlan, Axietheaxolotl
imageadd: Resprites all the Engineering Jumpsuits and Jumpskirts!
imageadd: Resprites the firesuit!
imageadd: Resprites all the hard hats!
imageadd: Resprites the insulated gloves and Chief Engineer gloves!
imageadd: Resprites the hazard vest!
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Hazmat suit is really sexy

**Comment by Sweettoothart** [comment]
The back of the chief engineer insuls sprites look like normal insuls

**Comment by Imaginos16** [comment]
> The back of the chief engineer insuls sprites look like normal insuls

Its an artifact of the original sprite. Basically imagine the CE glove has like a black front plate, hence its only black on the front, but yellow on the back.

**Comment by Fikou** [comment]
the insuls are WAAAY too light

**Comment by Sweettoothart** [comment]
> > The back of the chief engineer insuls sprites look like normal insuls
> 
> Its an artifact of the original sprite. Basically imagine the CE glove has like a black front plate, hence its only black on the front, but yellow on the back.

aaah that makes sense

**Comment by notfrying1pans** [comment]
imo workboots are a bit too blocky and the hivis vest doesnt have good contrast with the hazard suit

**Comment by MetalClone** [comment]
Spanking Hazmat suit, my only gripe is how the insulated gloves are no longer neon yellow.

**Pull request merged**
