### PR TITLE
Showers now properly clean hand of blood

### LINKED ISSUE #20674: Taking a shower does not clean your hands.
What it says on the tin. You must wash your hands separately in a sink to clean them of blood.

### PR DESCRIPTION
**Pull request by Cyberboss**
Wew

:cl: Cyberboss
fix: The shower is no longer adverse to cleaning your hands
fix: Your hands can now no longer spontaneously make your gloves bloody when you take them off
/:cl:

Fixes #20674

### CODE REVIEW

**Comment by optimumtact** [comment]
Please use a descriptive PR title

**Comment by CyberbossJHCB** [comment]
Fuck, I always miss it

**Comment by CyberbossJHCB** [comment]
Huh, don't merge this yet. I found a preexisting bug where the gloves can stay bloody after being washed when you take them off. http://imgur.com/GJUKyHk.png

**Review by phil235 — APPROVED** [review]
:+1:

**Comment by phil235** [comment]
@CyberbossJHCB This isn't really a bug, the shower washes the blood n your gloves but not on your hand. Unequipping your gloves requires you to touch the gloves with your stillbloodied hands which transfers blood on the gloves.

**Comment by CyberbossJHCB** [comment]
Ill test it again in a bit, but i'm pretty sure my hands weren't bloody when I removed them

**Comment by phil235** [comment]
You're correct. The issue is the bloody_hands var which is not set to zero when the human calls clean_blood() with gloves on. The var doesn't allow the distinction between bloody hands wearing clean gloves, clean hands with bloody gloves, and bloody hands with bloody gloves.

**Comment by CyberbossJHCB** [comment]
Why do I feel like my last commit is byond fucked?

**Comment by optimumtact** [comment]
that's not how you do merges, you've removed all the changes that other people made since the last pr

**Comment by nullbear** [comment]
Holy fuck i keep getting notifications for this one for some reason. Unwatching it.

**Pull request closed without merging**
