### PR TITLE
adds some grey sec jumpsuits to the sec wardrobe locker

### PR DESCRIPTION
**Pull request by PKPenguin321**
Yes

### CODE REVIEW

**Comment by KorPhaeron** [comment]
we don't need more locker bloat

**Comment by Supermichael777** [comment]
uniform lockers

**Comment by Cheridan** [comment]
why

**Comment by PKPenguin321** [comment]
requested in IRC by exalted12

**Comment by Cheridan** [comment]
That's nice and all but why did he request it
because basically:
bloats lockers for no reason, you can easily get a jumpsuit elsewhere
trap option; sec jumpsuits have melee protect that these alternates won't
they're called uniforms for a reason, sec needs to be easily identifiable by both crew (for protection) and antags.

**Comment by PKPenguin321** [comment]
Pretty sure these do have armor since they're a child of regular armor, they're just a remnant of the sprite war

**Comment by Exalted12** [comment]
I requested it for the following reasons,

-I have not found it available anywhere on the station.
-It doesn't bloat the security wardrobe locker that badly at all.
-I want it because I think it looks good. It's listed as a security uniform, so if melee protection is what you're concerned about, why not make it like the other security uniform that has the protection?
-As far as your concern about security being easily identifiable, I have yet to run into anyone who has not seen that I am obviously a security officer while wearing this uniform. It's black, red, grey and underneath armor, headgear and a security belt. It is painfully obvious that the person wearing it is a security officer.

**Comment by Cheridan** [comment]
oh nevermind i thought you were adding just normal assistant gray jumpsuits

**Comment by Steelpoint** [comment]
I honestly would prefer if we had consistency in uniform appearance and colour scheme. 

Not going to argue the issue, I just disagree with muddying the waters, so to speak.

👎

**Comment by Poojawa** [comment]
Make department suit vending machines, so you don't have a huge stockpile of 4 copies of each hat, scarf, hoodie, jumpsuit, pair of pants crammed in a locker.

**Comment by Exalted12** [comment]
I can understand the desire for consistency, but if you look at the uniforms side by side they aren't so different when wearing armor and the belt. I personally enjoy having a few different uniform options but that's just me.

I think department suit vending machines is a great idea, but I initially requested this from someone else, and don't want to nag too hard. (I should probably just learn how to do it myself)

**Comment by Poojawa** [comment]
Really not hard, just look at the Autodrobe's code, adjust the products to security stuff. Maybe make premium gear really fancy armor vests or w/e. Contraband can be one or two military belts or sommat.

**Comment by KorPhaeron** [comment]
If you want to add more stuff do what @Poojawa suggested please

**Pull request closed without merging**
