### PR TITLE
Attempts to track AI lawsets randomly and silently returning to Asimov

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Adds a check in the ai_laws datum's `Destroy()` proc, returning `QDEL_HINT_LETMELIVE` if an owner is still set and not qdeleted. Makes silicons clear the owner variable from their law datum before calling `Destroy` on it.

## Why It's Good For The Game
Under rare conditions, AI law datums are being deleted, which leads to a new default (Asimov) lawset being created anew. This causes confusion for Malf AIs (where law 0 is now missing) and also can cause strange inconsistencies where AIs just randomly become Asimov again.

The source of this issue is not yet known, so I have added a check to (hopefully) ensure that ai_law datums are only deleted from silicons when done through the proper channel (silicon itself being deleted too), and a stack trace to help track down the root cause.

## Changelog
:cl:
fix: AIs should no longer occasionally have their lawset randomly and silently returned to Asimov.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this is absolutely not a fix, it's papering over a bug and should not be merged

**Comment by zxaber** [comment]
The goal is that we get a stack_trace telling us where the issue actually is, while lessening the impact the bug has in the meantime.

**Comment by Watermelon914** [comment]
it's less of a fix, more of an attempt to track to the source of the problem. Branding it as a fix is probably a bad idea.

**Comment by Mothblocks** [comment]
Basically all `QDEL_HINT_LETMELIVE` is either tracking down incorrect deletions (which is fine, especially for bugs like this that happen in prod semi-frequently but without any clear reason why) or some old crap that should be removed.

I am totally fine with things like these to track down bugs.

**Pull request merged**
