### PR TITLE
Space cleaner removes the colour from items

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Space cleaner now removes artificial color from objects, turfs
and mobs.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Ruins the greentext item

**Comment by KorPhaeron** [comment]
Also you could clean off phylactery as lich

**Comment by MrPerson** [comment]
This will literally create a shitload of bugs we'll be solving for YEARS. Please don't.

Plus this is obviously a fucking feature.

**Comment by KorPhaeron** [comment]
Also I think pipes are coloured like this

**Comment by Incoming5643** [comment]
might bleach lizards

**Comment by PKPenguin321** [comment]
who's to say what you've all described as "bugs" aren't all features

lizard bleaching sounds good to me

**Comment by xxalpha** [comment]
color is not used like you think it is.

**Comment by PKPenguin321** [comment]
oh no i understand it's just that bleached lizards would be funny

**Comment by KorPhaeron** [comment]
This would cause bugs and is also probably a feature

**Comment by PKPenguin321** [comment]
also cleaning the paint off of pipes makes sense
only weird thing is greentext color but that's pretty much fine

**Comment by Mercenaryblue** [comment]
bleach spray when?

**Comment by KorPhaeron** [comment]
After the freeze

**Comment by Zilenan91** [comment]
He is right though, wizards would steal space cleaner and bleach their phylactery's and have them never be found. They'd bleech paper to be white.

**Comment by Mercenaryblue** [comment]
A check against phylactery bleaching would be easy to do, TBH.

**Pull request closed without merging**
