### PR TITLE
Black Fedora opens its inventory on-click like the Detective's Fedora

### PR DESCRIPTION
**Pull request by ThePainkiller**
**Tweak:** 
Instead of having to drag the sprite to your character to access its inventory, behaves the same as the Detective's Fedora opening its container on click. Considering some dets prefer the black variation for noir flavour rather than the brown standard one they just have to pass his flask from one hat to another and keep the same functionality. They cannot either draw candy corn from it nor alt click to quickly remove contents though, considering the Black Fedora also spawns on the bar on Metastation.
I had either this in mind or creating a new black detective's fedora variant on the det's cabinet that also had the flask inside it.

:cl:
tweak: Tweaked the inventory management of the black fedora to be more like the detective's
/:cl:

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Just remove the line instead of having a redundant assignment

**Comment by Cyberboss** [comment]
Also, see the pull request template to see how to format your changelog. What you put in it only needs to be a description of your changes without the "Why"

**Comment by ThePainkiller** [comment]
@Cyberboss You mean removing the "priority" line altogether will give the same effect as setting its value to TRUE?

**Comment by Cyberboss** [comment]
Yes, because that's how it's defined on the parent type

**Comment by ThePainkiller** [comment]
Thank you Jordan, I think I've edited my PR correctly now, please be patient with me as I'm a bit new with code :c

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
No problem, I tweaked your description to give it a proper changelog

**Comment by ThePainkiller** [comment]
Thank you! I'll take note to format any future PR's like so

**Pull request merged**
