### PR TITLE
Fixes item pixel placement

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by octareenroon91** [comment]
Fixes #25630 ?

**Comment by Cyberboss** [comment]
Yes, that's in the commit.

**Comment by octareenroon91** [comment]
I was a little short earlier:
The commit but not this PR showed as mentioning the bug on github.

**Comment by Cyberboss** [comment]
That will still close the issue once it's merged

**Comment by ChangelingRain** [comment]
Wow shit I forgot the important part of the proc.

**Pull request merged**
