### PR TITLE
Revert "Causes the emergency shuttle to play sounds upon launch and dock"

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Reverts tgstation/-tg-station#12743

It is painfully loud. I'd like this merged until it can be fixed, we shouldn't be subjecting players to actual physical pain while playing the mental anguish of spessmens is bad enough.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Phil is putting up a fix, it's a bug

**Comment by KorPhaeron** [comment]
I'm aware it was a bug but I didnt think anyone was gonna fix it till Xhuis got home so I was going to test merge this PR as a temporary measure

**Comment by RemieRichards** [comment]
It's a tiny fix, and Phil's already working on it, It can be speedmerged, no need for a test PR.

**Comment by KorPhaeron** [comment]
Alright

**Pull request closed without merging**
