### PR TITLE
Bump byond up to 514.1588

### PR DESCRIPTION
**Pull request by MrsTonedOne**
about to update the servers, gonna let tests run and see what happens.

### CODE REVIEW

**Comment by Jackal-boop** [comment]
Mso got high

**Comment by MrStonedOne** [comment]
This pr failed unit tests for admin lua.

It was agreed that admin lua failing was not going to be a blocker to progress when it was first coded. This has not changed.

This byond version is about to be deployed on the servers regardless of the lua break.

This pr is ready for merge.

**Comment by Mothblocks** [comment]
Admin Lua not working is not a blocker though we definitely should have a temporary fix for CI. SSlua should mark itself as initialized even if it can't load, or the test suite should explicitly ignore it. Long term plan can be figured out later.

I'll get that done tonight if either you or @Y0SH1M4S73R were not already planning on it.

**Comment by MrStonedOne** [comment]
I was gonna make a subsystem flag to exempt that subsystem from the check.

also lua works on windows still, its only the linux version having issues.

and also this might be fixable with a lua version change because there are prs and stuff.

also i left edits by maintainers enabled so you can update this pr with any other changes it turns out are needed.

**Comment by Mothblocks** [comment]
> I was gonna make a subsystem flag to exempt that subsystem from the check.

That's more or less the extent of what I was going to do, so go ahead. In the meantime I will investigate seeing if we can fix the issue in auxlua itself.

**Comment by Mothblocks** [comment]
The error is coming from auxtools: https://github.com/willox/auxtools/blob/cd481e4aefad069d36ba28f9e17912ea0ecaa603/auxtools/src/lib.rs#L299

There are updates on the signature this searches for on Windows, but none for Linux. CC @willox if you can look into that?

Like I said though definitely feel free to just ignore SSlua in CI for now. I want to figure out a long term solution to make sure that we would know if SSlua broke again in the future (just silencing it means we won't find out until someone happens to see it), but I obviously do not want to hold up this PR for it.

**Review by Mothblocks — APPROVED** [review]
I made it annoying (especially since it runs so many times), but not blocking. Will do what I can to get auxtools on Linux moving but I finished what I wanted to do.

**Pull request merged**
