### PR TITLE
[Meta] Minor Whiteship Edits

### PR DESCRIPTION
**Pull request by ghost**
* Replaces a random steel wall on the Whiteship with a titanium wall(the wall under the SPACE sign near the pinpointer sprite).

* Replaces an uncleanable remains pile with it's ash variant.

Screenshots:
Before:

After:

### CODE REVIEW

**Comment by MimicFaux** [comment]
Took me a good three minutes to find the replaced wall.

**Comment by Mark9013100** [comment]
whoops, I'll get a better screenshot

**Comment by PraiseRatvar** [comment]
still hard to find but for anyone who wants to know its at the top of the whiteship picture

**Comment by Armhulen** [comment]
@PraiseRatvar C H E A T E R

**Pull request merged**
