### PR TITLE
Refactor speculative/refundable power supply into a component, powernet expansion blockers into a signal, add signals for powernet changes, remove SMES rotation, slightly improve power units plus misc power cleanup

### PR DESCRIPTION
**Pull request by esainane**
## About The Pull Request

SMES units work by supplying and using their maximum output each power tick, and getting refunds on any power output not used. This behavior was hardcoded into powernet code, specifically looking for SMES machines, so using this behavior for other machines was difficult. This has been factored out into a component and signals, and now handles more complicated flows.

Powernet code worked by explicitly tracking the cases where a cable was under a SMES unit and where a cable was under a terminal, preventing powernet merging between the terminal and the SMES it was connected to, if it was connected to a SMES. This behavior was hardcoded with specifically SMES machines and specifically power terminals, literally using constants called `UNDER_SMES` and `UNDER_TERMINAL`, so using this behavior for other machines was difficult. This has been factored out into a component and signal.

SMES rotation has been removed. This left power terminals in broken states, and there was absolutely no functional use. Rotation only changed where it looked for a terminal, and:
 - Creating a terminal (by using wires on a SMES) always immediately linked it anyway.
 - On construction, a SMES already checks all cardinal directions for an existing terminal facing towards the SMES.

Energy/power units are slightly more accurate. `KILOJOULES` is at least a better descriptor than `JOULES`, and baking in tickrate conversion into these helpers was and is insane. This is going to take a lot of further effort, however.

## Why It's Good For The Game

Reusability in preparation for mechanical changes. Some sanity elsewhere.

## Changelog

:cl:
code: SMES machines can no longer be rotated. This had no functional use, as it simply changed where it was looking for an input power terminal. Adding an input power terminal always immediately connected anyway, and rotation broke terminal linkage, which resulted in weird states.
/:cl:

...plus a very large amount of not-player-facing changes

### CODE REVIEW

**Comment by Razharas** [comment]
Why are there both defines and global procs for energy type conversions?

**Comment by esainane** [comment]
Because there are multiple kinds of energy type. Some entities store potential energy as kJ; some just as J; some include tickrate assumptions; powernets operate in W; and the conversion defines always assume that they're converting to something that needs tickrate adjustments. The values of the conversion defines haven't been changed, they're just now being expressed in a way that makes this insanity explicit.

Quoting the commit message body from `JOULES->KILOJOULES, and document the nightmare`:

> These multipliers had tickrate conversion baked in, without documentation.
> This meant that if you wanted to know how many joules 5W was, it would tell
> you 2.5J... if that was the only problem with these multipliers. Additionally,
> `JOULES` really meant `KILOJOULES`, so you went up or down three orders of
> magnitude each time.

> We got away with this as (almost) every instance where power needed to be
> drained from storage, it went through the conversion exactly once,
> replicating the effect of `delta_time`, so the storage variable was updated
> correctly. Similarly, (almost) every time either unit needed to be
> displayed, it was displayed before any conversions from member values
> happened.

> Shout out to `display_energy(units)` which needed to convert a stored value
> from the stored unit (kJ) to basic joules so it could display the correct
> metric prefix. Rather than multiplying by a thousand, it converted kJ
> as if it were WattTicks (!) needing to be converted to Joules (!), then
> multiplying the result as if it were kJ needing to be converted to
> WattTicks, and finally displaying this as if it were J.

...so making use of the fact that the conversion defines increase the value by three orders of magnitude and apply a tickrate multiplier, then used the proc conversion which does not adjust the value by three orders of magnitude but undoes the tickrate multiplier, in order to get the value to increase by three orders of magnitude in the most ridiculous way possible

There does need to be a serious effort to clean that all up, but this PR has sort of exploded far beyond its original scope already

**Comment by Razharas** [comment]
My question was more in line of could they all be procs or all be defines

**Comment by esainane** [comment]
They could and probably should all be defines, though I'd prefer to do that properly (pick one unit for each kind of measurement and have everything use it) and in a later PR

**Comment by Razharas** [comment]
Its pure consistency issue, its better to use one type of things for all related problems(unit conversion) rather then remembering that to convert X to Y you need a define and from A to Z you need to call a proc

**Comment by ORCACommander** [comment]
would it be out of scope of this pr to investigate why cable layer 3 and 1 have their machine layer set to null and therefore not connect to anything besides the layer adapter?

**Comment by esainane** [comment]
We're currently blocked by the mapload rework commit making incorrect assumptions. I'm more tempted to revert that, and get on with reviewing what's currently done, since the scope has already exploded - and the title somewhat reflects that.

**Comment by esainane** [comment]
Removed description paragraph:


> Delay machine powernet connection until the `SSmachines` subsystem. Machines were inconsistent with how they indicated node use - some omitted `should_have_node`, some omitted the `Initialize` `connect_to_network`. All now consistently indicate `should_have_node`, and skip powernet connection at mapload, since as soon as `SSmachines` initialized it immediately `qdel`s all existing powernets. Cable connection is also delayed until this stage, being conceptually similar and neatly avoids race conditions and extra checks elsewhere.

**Comment by esainane** [comment]
Note that power terminal setup is still race safe, as the checks in Initialize were present before being made redundant by more coherent phases in setup

**Comment by esainane** [comment]
I was also under the impression that only layer 2 connecting to machines was intentional, is there an issue for that where discussion might be better suited?

**Comment by ORCACommander** [comment]
according to the blame data, the values were last adjusted under PR https://github.com/tgstation/tgstation/pull/49773
 they were changed from 1 to null. there is no supporting documentation that PR why it was it was done.
 
 Design goal of my maps downstream was to color code the wire network. Red for generation, Yellow for backbone blue for final mile.
 
 Currently no open issues on this subject unless you would rather i create one?

**Comment by optimumtact** [comment]
conflict in signals

**Comment by esainane** [comment]
just got out of hospital, I'll deal with it in the evening

**Comment by optimumtact** [comment]
small conflict

**Pull request closed without merging**
