### PR TITLE
Yar Har Fiddle Di Dee!

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

The space pirates have long since needed some love for their old, weathered sprites so I took it upon myself to give them some proper drip. I also fluffed the cutlass so it's not a banana with a hilt and gave the sailor uniform some love as well since it was similar in design to the pirate uniform just blue with brown pants.

Note the `hgpirate` sprites haven't been touched yet, I'm still trying to get information on them.

EDIT: Blue bandana alt was removed do to `Init` errors

EDIT: `hgpirate` got a quick pass over with some minor sprite changes and a new item for the `hgpiratecap`

## Proof of Testing

<details>
<summary>Screenshots</summary>
  
Bandanas in a Test Session
Screenshot 2023-06-24 224722

Full Pirate Drip in a Test Session
Screenshot 2023-06-24 224731

Energy Cutlass in a Test Session
Screenshot 2023-06-24 224830

Normal Cutlass in a Test Session
Screenshot 2023-06-24 224933

Pirate EVA suit in a Test Session
Screenshot 2023-06-24 225121

Pirate EVA drip 1
Screenshot 2023-06-24 012314

Pirate EVA drip 2
Screenshot 2023-06-24 181951

</details>

## Why It's Good For The Game

The sprites that the pirates use are old - these sprites are better than what the pirates currently have.

https://www.youtube.com/watch?v=i8ju_10NkGY
## Changelog
:cl:
add: Added new Pirate Boots
image: Added new Pirate Bandana sprites
image: Added new Pirate Hat sprites
image: Added new Pirate Uniform sprites
image: Added new Sailor Uniform sprites
image: Added new Pirate Coat sprites
image: Added new Pirate EVA gear sprites
image: Added new Cutlass sprites
image: Added new Energy Cutlass sprites
image: Added new `hgpirate` suit and hat sprites
/:cl:

### CODE REVIEW

**Comment by Jezzared** [comment]
Oh Hell. Fucking. Yes.

**Comment by necromanceranne** [comment]
Damn yo, those cutlasses look badass.

**Comment by EricZilla** [comment]
You should add what the PR is to the title before someone gets your ass lol

That said these look really good, love the bandanas

**Comment by SomeoneYouProbablyKnow** [comment]
For he's a jolly good fellow
For he's a jolly good fellow

**Review by Wallemations — APPROVED** [review]

**Review by san7890 — APPROVED** [review]

**Pull request merged**
