### PR TITLE
Buffsctticotd brcauze tricktx is the best xhem trivord is the

### PR DESCRIPTION
**Pull request by Iamgoofball**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: optional name here
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Tricorx was netffed tooooo hard

**Comment by AuroranAI** [comment]
image

**Comment by Iamgoofball** [comment]
Vhsck itnoyt guts i tevdtted goofchem
@mrstonedone @KorPhaeron @optimumtact @god @my-ex-girlfriend @me @you @vslemdr @valrmdt @valendr

@comma toooo

**Comment by JJRcop** [comment]
```
:cl: Iamgoofball
balance: Tricordrazine is now 4x more effective at healing.
del: Tricordrazine no longer has an overdose.
/:cl:
```

**Comment by Iamgoofball** [comment]
Yhis fuxes medical

**Comment by Iamgoofball** [comment]
@ausops uncsnt cobtronmt drinkpkstin im.dlnet

**Comment by ShadowDeath6** [comment]
How are doctors going to deal with clone damage if this doesn't fix it? :confused:

**Comment by SamSamsonthe3rd** [comment]
You having a stroke, mate?

**Comment by JJRcop** [comment]
@SamSamsonthe3rd He's not. 🍻

**Comment by Repukan** [comment]
Sorry I don't speak Italian

**Comment by Iamgoofball** [comment]
@giacom lookm howvfarnive come

**Comment by Iamgoofball** [comment]
@aranclanos xome vsck wrnmiss tou :(

**Comment by Armhulen** [comment]
<Mr_Bagil> REPO: Merging PR #32587...
<ZBot> "Buffsctticotd brcauze tricktx is the best xhem trivord is the" (#32587) by Iamgoofball - https://github.com/tgstation/tgstation/pull/32587

**Comment by ike709** [comment]
inb4 this is actually merged

**Comment by duncathan** [comment]
don't tempt me

**Comment by Jordie0608** [comment]
ok spidey

**Comment by Repukan** [comment]
They can't keep getting away with this.

**Comment by kevinz000** [comment]
jmad get off his account

**Comment by Mercenaryblue** [comment]
What the fuck why am I laughing so hard at this PR.

**Pull request closed without merging**
