### PR TITLE
Adds a Recipe for morphine to medicine

### PR DESCRIPTION
**Pull request by Ordonis**
:cl: OrdoM
rscadd: Adds morphine recipe to chemistry. 
rscdel: Removed ability for bartender to steal all morphine on the map
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
You want del or rscdel in your changelog

**Review by Cyberboss — DISMISSED** [review]

**Comment by Cyberboss** [comment]
If this gets merged remember to add the reciepe the wiki

**Comment by ma44** [comment]
Emagged chem dispensers can already straight up dispense morphine, up to 4 bottles of 30u of morphine from med vendors (and 4 pills of 30u morphine if hacked) 2 pills of 30u morphine from a wall mounted vendor and two bottles of morphine from a medical supplies crate.

Why would there need to be another way to make morphine, provided you can already get hundreds of units of it from vendors 1-2 screens away and barely use it all up unless you're mass producing aranesp, krokodil or neurotoxin?

**Comment by Iatots** [comment]
>unless you're mass producing aranesp, krokodil or neurotoxin

**Comment by Ordonis** [comment]
@ma44 
It seems strange for a medicine like morphine to be locked behind emagging/limited supply; also, I don't see a need for there to NOT be a way to make morphine, and I don't think we're going to be plagued with powergamers suddenly morphining the clown to death. Emagged chem dispensers also produce space drugs and miner's salve, but space drugs still have a recipe, as does miner's salve. 

I've never seen the supply of epinephrine bottles in the smart-dispensers at chem run out, but we likewise have a way to make epinephrine; furthermore, if someone DOES want to mass produce such things (for whatever reason), this gives them a way to do it, and if the bartender wants to make the drink, he can now actually do so without entering an area of the station he doesn't have access to get to by requesting that chemistry make him a bottle, rather than having to ask for a strictly limited resource.

**Comment by Iatots** [comment]
>required_reagents = list("carbon" = 2, "hydrogen" = 2, "nitrogen" = 1, "oxygen" = 1) + heating
This seems very easy to mass-produce, and also lacking in the pseudo-chemistry goofchems have.
I don't know how useful morphine is though, but I suppose it can't be very robust if nobody ever complained about the limited quantity.

**Comment by ma44** [comment]
With a vendor's 4 bottles of morphine (120u) , you can make 
360 units of aranesp
720 units of krokodil 
240 units of neurotoxin

If you were to count hacking the vendors, the number of chems you could make would also double up, as you can grind up the pills for morphine. 

# of vendors with 4 morphines per map

Pubby: 2 in medbay, 1 in virology, 1 at the escape shuttle area
Boxstation: 3 vendors in medbay, 1 in virology. 
Delta: 1 in escape, 1 in storage, 
Metastation: 2 of them somewhere
Omegastation: 1 somewhere, also boots a medical locker

**Comment by Ordonis** [comment]
@Iatots 

Certainly less robust than chloral-hydrate for any kind of mischief; also I have no objections to altering the recipe to make it more difficult. Honestly the recipe is simple because I've never seen any effective griffing with morphine specifically, and because morphine is a fairly simple chemical to synthesize; the Rice process is a straightforward enough thing to do. It's a sedative/painkiller; are there any goofenchems that would be expected in its production? I could also increase the amount of reagents while keeping the yield low.

**Comment by Ordonis** [comment]
I guess I don't understand the major reason not to have it be something chem can produce: if it's already easy to get, and isn't being abused, then there's no problem with an additional avenue to get it a-la epinephrine. If it wasn't easy to get, but isn't easy to abuse, then having a recipe makes sense to allow it to be easier to get. If it's not easy to get, but easy to abuse, then I agree that production should be difficult (though not necessarily impossible). If it's easy to get, and easy to abuse, the clown/greytide would be morphine-addicting everyone each round.

**Comment by ma44** [comment]
Epinephrine hasn't been changed ever since phil reorganized the files.

**Comment by 81Denton** [comment]
@Iatots Morphine is horribly unrobust compared to other stun/KO chems and pretty much only good for mixing. Balance wise, I don't see a reason why you shouldn't be able to mix it.

**Comment by epochayur** [comment]
@ma44 what point are you even trying to make, dude? "there's a lot of morphine already" yeah? and? why does that mean that it shouldn't be a chem recipe? if your issue is people doing nefarious things with it, there's already tons of it laying around for people to steal, and if the issue is keeping supplies limited, that's already clearly not a problem

**Comment by Ordonis** [comment]
I wasn't implying that it had been changed, only that it's damn near ubiquitous, doesn't tend to run out during rounds, but still has a recipe. Even if morphine doesn't tend to run out, there's no reason the supply has to be limited to emagging or a few bottles; in particular, bottles can be easily stolen/consumed by one determined bartender/greytider etc. whereas chem dispensers are somewhat more challenging to lift.

**Review by imtakingabreakdontatme — DISMISSED** [review]

**Comment by FantasticFwoosh** [comment]
I veto this change, it puts the final nail in the coffin in regards to botany sharing resources and being a supplier for chemistry when you remove the import of morphine from reishi plants.

Interdepartmental co-operation is dead.

**Comment by kevinz000** [comment]
Fwoosh veto implies you have power :^)

**Comment by FantasticFwoosh** [comment]
Power of free speech for the most part anyway.

**Comment by Ordonis** [comment]
@FantasticFwoosh 

Firstly I have never once seen botany supply chem with reishi, to the point where I did not even know the plant contained it. Secondly most interactions I have seen between botany and chem are as follows:
1.
B: Gib mutagen
C: Okay
2. 
B: Gib mutagen or I steal chem dispenser
C: No

Or variations on the theme. Botany can also grow: guns, teleportation, the best healing chems in the game, one of the best melee weapons in the game, grenades, drugs, and, occasionally, food. I think they're still incredibly strong as a department on their own and in terms of providing useful stuff to the station. Specifically for chemistry, they can still make frost oil and capsaicin, which I would argue are more commonly demanded chems.

**Comment by 81Denton** [comment]
Why do people unironically reply to Fwoosh

**Comment by FantasticFwoosh** [comment]
Xenobiology can make frost oil and caspacin too (amongst other things), you might be right in the observation that ties between the two departments have degraded through inactivity and powercreep of botany's capacities to just grunting & stealing the chem dispenser, but it furthers the problem to its own demise to simply move with the change and make botany just chemistry rather than try to amend it.

- Plus generalised additional worries with infinite morphine syringe shots.

**Comment by Ordonis** [comment]
Re: syringe shots, chloral as easy to make and far more robust. I'd be happy to make NEW chems which require botany's input (Nitrocellulose, anyone?), but without a nerf to botany and the reduction of unga dunga give dispenser, I don't think gating too much of anything on their behavior is a good idea.

**Comment by epochayur** [comment]
>fwoosh

**Comment by Iamgoofball** [comment]
ignore all fwooshpost

i disagree with this change because morphine is pretty powerful

**Comment by Teepeepee** [comment]
You can grow morphine out of reishi, as previously stated in this PR, I don't understand how botanists tend to steal the chem dispenser but it never crosses anyone's mind chemists can also steal a tray, some seeds and do their job just fine, since they have the mutagen and saltpetre machine anyways. I see how encouraging people to begin conflict is not a good idea, but we are totally fine making the botanist inclined to doing so for mutagen. Either keep consistent and force neurotoxin memers to hack a med machine, order from cargo, or in the edgest of cases just growing reishi themselves as they would need to do for omnizine if no botanist was online; or finally give botany a way to get mutagen without having to be at the mercy of the chemist or valid-hungry crew if they are forced to steal the dispenser. That's my grain of salt anyways.

**Comment by arsserpentarium** [comment]
I think,there should be more things,which requires botany input.

**Comment by Teepeepee** [comment]
Its not useless, growing their snowflake plants for their snowflake chems with the tools of the botanist (their trays, their seeds, their gene machine if necessary - with the added benefit of them actually having mutagen and saltpetre generation easily available) is the same restriction there is on botanists getting their progress more reliably than left4zed or EZ nutriment rng: through mutagen (also gated behind snowflake machine). If one of these is deemed unacceptable I say they are both; in which case either remove the restriction, accept people causing conflict to bypass it or do something in the middle like what you just said.

**Comment by 81Denton** [comment]
>i disagree with this change because morphine is pretty powerful
Morphine is plain mediocre compared to Chloral and the Neurotoxin drink.

>Why not to merge chemists and botanists?
Imagine chemists having nitroglycerin, amanitin, coniine and worse available every round. The absolute horror!

**Comment by FantasticFwoosh** [comment]
> Imagine chemists having nitroglycerin, amanitin, coniine and worse available every round. The absolute horror!

They both have equally horrid chemicals, particularly in strange plants randomisation of chems yielding sometimes ungodly results. The fact you don't talk about this being somewhat a reality since chemistry is literally across the hall from hydroponics most rounds (and a far away from garden on box standard) shows that either nobody asks (i know for a fact reed pestered botany for koibeans because he is a robust & respected chemist) and that it would be impractical to do it in the existing public gardening spaces.

- Replace the medical security office with a minimalist hydro tray setup with soil trays & split hydro/chemistry access, 

- flip the position of chemistry to be on the right hand side on box so that its the back-room for chemists to go inside and retrieve plants under a glass view of medical interior and reinforced wall with the hallway divided by two glass panelled doors. Botanists & chemists share this space though it is officially for chemistry's personal use, a lend-lease hydroponics room (botany aid to be repaid in kind back to the station in the form of medical chems)

That wasn't exactly what I was going for @arsserpentarium but its a option

**Comment by Ordonis** [comment]
I am an idiot and pushed the ketrazine update to this PR because tired, pls disregard

**Pull request merged**
