### PR TITLE
Centcom Supplypods now come with a ghost announcement + follow link

### PR DESCRIPTION
**Pull request by MrDoomBringer**
Now as an observer i can watch people get orbitally dunkt with greater ease
this is a toggleable option, of course

:cl: MrDoomBringer
tweak: Admins can now allow ghosts to follow the delivery of Centcom-launched supply pods
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
what about when it's spammed?

**Comment by davethwave** [comment]
Then toggle the option to off.

**Comment by MrDoomBringer** [comment]
image

**Comment by Dorsisdwarf** [comment]
does this send one alert with the "machinegun" mode or 5

**Comment by MrDoomBringer** [comment]
@Dorsisdwarf one

**Comment by optimumtact** [comment]
nothing wrong with me

**Pull request merged**
