### PR TITLE
makes armor respective helmet values the same part 57

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

you know when i did the original few prs i touched practically everything... except the basic armor and helmet
also does it for infiltrator suit and winter hood

## Why It's Good For The Game

consistency good

## Changelog
:cl:
balance: armor values on helmet and vest are now the same in the security and infiltrator pairs and winter hoods
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
why is there a need for this when helmets don't necesarily offer the same protection as armor

**Comment by Fikou** [comment]
> why is there a need for this when helmets don't necesarily offer the same protection as armor

because is good and all the other armors and helmets already have the same values

**Comment by Pugie** [comment]
hello yes hi when do armored winter coats get armored hoods

**Comment by necromanceranne** [comment]
@Qustinnus what do you mean, most of the helmets in the game are really high protection or equivalent since fikou's reworks. Stuff like the red SWAT helmets had been one of the highest valued helmets around with no paired body armor to go with them. 

People aim for the head because of misconceptions about stun chances and bullet deviation.

**Comment by Fikou** [comment]
> hello yes hi when do armored winter coats get armored hoods

done

**Comment by ExcessiveUseOfCobblestone** [comment]
I would prefer them to be different (less on head) but the current dynamic allows consistent headshots as if every person has 300 confirmed kills so this is the world we choose.

**Comment by Fikou** [comment]
> I would prefer them to be different (less on head) but the current dynamic allows consistent headshots as if every person has 300 confirmed kills so this is the world we choose.

they shouldnt be paired armors if they dont have the same armor values

**Comment by ExcessiveUseOfCobblestone** [comment]
Makes sense from gameplay considering there's no difference between shooting at the head or shooting at the body (our accuracy extends to does it connect to the sprite or not and you decide what part to hit) which is what I said earlier.

If we were going for a more immershun approach to accuracy we wouldn't need to align these in all cases, as the head piece (helmet or otherwise) may have a different MoC/coverage/thickness than its torso counterpart but still look aesthetically similar (or "pair" with said torso piece).

**Comment by Rohesie** [comment]
This seems ready for merge, unless if you'd like to block it in favor of a different way to handle armor, @ExcessiveUseOfCobblestone 

Personally I prefer the same-value approach else hitting the head is always the answer.
Or even head gear having higher values than body armor, but more serious consequences on damage.

**Comment by ExcessiveUseOfCobblestone** [comment]
no this is fine i just didn't want to merge until a compile checked passed but travis is gone :woozy:

**Pull request merged**
