### PR TITLE
vampires are a human subtype & have stomachs/lungs

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Vampires have stomachs and lungs.
They still don't have hunger.

Vampires are a human subtype.

Vamp bloodtype from "U"nknown to "V"ampire

## Why It's Good For The Game

For some stupid reason vampires lacked stomachs. Vampires drinking wine is a classic trope that currently results in vomit magically appearing below you.

Evidence of wine:

ielbiv4shad81

Vampires are a human subtype too like felinids because this resulted in dumb bugs like no screaming sound.

Vamp bloodtype from "U"nknown to "V"ampire

I mean if we haev these guys on halloween. We probably know their blood right. 

## Changelog

:cl:
fix: vampires are a human subtype & have stomachs/lungs
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
errmmm shut up idiot

**Comment by carlarctg** [comment]
@JohnFulpWillard im temp dbanned

**Comment by JohnFulpWillard** [comment]
> @JohnFulpWillard im temp dbanned

Vampire blood I assume is U for Universal, why change it off?

**Comment by carlarctg** [comment]
oh

well i think v looks cooler

**Comment by TheVekter** [comment]
> Vampire blood I assume is U for Universal, why change it off?

Makes sense that vampires wouldn't be universal donors, doesn't it?

Hell, I don't know if it's possible, but can we make it so that having enough vampire blood in your system converts you to one?

**Comment by carlarctg** [comment]
oos

**Comment by Xkallubar** [comment]
I never drink... Wine.

**Pull request merged**
