### PR TITLE
Changes the tank suicide act to bruteloss instead of gibbing.

### PR DESCRIPTION
**Pull request by Aranclanos**
aran we're just adding different texts to suicide its not like anything changes!
aran we're just making the suicides be a bit different changing the damage type, its not like anyone gets gibbed!

aaaaaaaaaAAAAAAAAAAAAAAAAAAAAA

### CODE REVIEW

**Comment by Lumipharon** [comment]
>no fun allowed

**Comment by RemieRichards** [comment]
it's this or learn not to suicide hopline every time you get a different map.

**Comment by Supermichael777** [comment]
> Bluespace commented 24 days ago
Don't hold back on suicides for balance reasons, feel free to destroy brains etc.
Remember, people can and will space themselves to suicide too, which entirely removes them, even if they're an objective.

all bluespaces fault

**Comment by Iamgoofball** [comment]
what the fuck is the problem with this

you literally are already perma out of the round with suicide anyways

why can't we have it be relatively interesting

**Comment by Zilenan91** [comment]
I wouldn't mind MORE suicides that gib people and generally cause a mess.

**Comment by AlexanderUlanH** [comment]
Aran's literally the new HG

**Comment by duncathan** [comment]
Aran is my favorite coder

**Comment by TechnoAlchemisto** [comment]
Yeah suicides that gib are stupid. GOod change.

**Comment by Kromgar** [comment]
Aran removing fun 4noraisin

WHY?

ITS SUICIDE THEY ARNT COMING BACK

**Comment by Bawhoppen** [comment]
if you are going to remove any suicides, dont remove the gib ones, remove the telebaton one cause that is BUGGED

**Comment by MrPerson** [comment]
Should be oxyloss because you're choking but w/e

**Comment by RemieRichards** [comment]
>ITS SUICIDE THEY ARNT COMING BACK

This argument holds no grounds when the people do it EVERY SINGLE ROUND

**Comment by lzimann** [comment]
People do it anyway Remie, with or without gibbing.

**Comment by RemieRichards** [comment]
Well the gibs aren't helping. But ideally yes, bans should be thrown out without mercy for this shit, gone on long enough.

**Comment by Iamgoofball** [comment]
>This argument holds no grounds when the people do it EVERY SINGLE ROUND

What's wrong with them suiciding?

>bans should be thrown out without mercy for this shit, gone on long enough.

Are you fucking dense? The point of suicide is "i dont want to play in this round, please don't revive/defib/clone me, and make sure anyone who had me as a target doesn't get redtext for it"

**Comment by Bawhoppen** [comment]
Remie, thats an adminstration thing and not a code thing. Don't remove the ability to do it

**Comment by RemieRichards** [comment]
@Iamgoofball 

1. it's roundstart, you don't want to play? don't play.
2. Slots.

**Comment by Iamgoofball** [comment]
>1. it's roundstart

That's a problem, you should of stated that. This can be fixed by adding a "wait till 15 minutes after round start" to suicide thing.

>2. slots
Typically, if someone's going to suicide, they disconnect within 5 minutes, give or take a few.

**Comment by Bawhoppen** [comment]
That is bullshit, people are allowed to suicide on here because we're not fucking bay

**Comment by Iamgoofball** [comment]
okay i'm a dumb dumb and apparently this was regarding roundstart suicides

**Comment by Bawhoppen** [comment]
and whats wrong with that?

**Comment by Iamgoofball** [comment]
@Bawhoppen when 50% of the players suicide because the map isn't de_dust2 there's a problem

**Comment by Bawhoppen** [comment]
ok you win the argument just because that joke was so good

**Comment by bgobandit** [comment]
like every meme this will die down soon

**Comment by SconesC** [comment]
"you iddnt want to play th fgame you are bannd"

**Comment by Lumipharon** [comment]
People roundstart suiciding in limited slots is a valid issue.
People suiciding like huge babies because of the map then complaining on the forums that the map is so bad because people suicide on them is also an issue.

How does changing the result of 1 specific type of suicide effect these in ANY way?

No one has actually said so far why gibbing suicide is bad as opposed to suicide itself.

**Comment by Shapsy** [comment]
Because gibbing is much showier than holding your breath and falling over, and gives you more attention, which people love

**Comment by Dorsisdwarf** [comment]
Also it makes the round look like the final stages of Cult within 30 seconds 


:-1: This feature is like a filter for shitters

**Comment by Jalleo** [comment]
Solution make a roundstart suicides list for admins to ban those cry babies asses. This aint the solution setup a easy way to ban the fucktards and to announce the idiots who did it.

**Comment by Bawhoppen** [comment]
doesnt a roundstart suicide list exist

**Comment by AlexanderUlanH** [comment]
Yes, it does.

**Comment by Jalleo** [comment]
@AlexanderUlanH ya sure it aint the logout one?

**Comment by Shadowlight213** [comment]
Reminder that gibbing negates the whole death after being implanted by xenos doesn't kill the embryo mechanic.

**Comment by Razharas** [comment]
How does removing gibbing solves the problem of roundstart suicides?
@Aranclanos

**Comment by Aranclanos** [comment]
what roundstart suicides

**Comment by Miauw62** [comment]
Just some powergamers being a baby about map rotation
Op 5-okt.-2015 21:36 schreef "Aranclanos" <notifications@github.com>:

**Comment by Razharas** [comment]
#codergate

**Comment by Lumipharon** [comment]
Literally no one has said why they want to remove gib suicides.
The only arguments that have been brought forth have to do with suicide in general.

**Comment by Bawhoppen** [comment]
yea whats with these shitty speedmerges

**Comment by Niknakflak** [comment]
This was good change

**Comment by duncathan** [comment]
>yea whats with these shitty speedmerges

dude what this wasn't a speedmerge
yolomerge yea but definitely not a speedmerge

**Comment by Bawhoppen** [comment]
@duncathan the discussion was definitely not over, thats why its a speedmerge

**Comment by duncathan** [comment]
@Bawhoppen you don't know what a speedmerge is then bruh
speedmerge is when something is merged before the 24 hour mark
this is a yolomerge

**Comment by Bawhoppen** [comment]
@duncathan would you argue against it being a bullshit merge?

**Comment by duncathan** [comment]
@Bawhoppen no I wouldn't, but that doesn't mean that it's a speedmerge
speedmerging without good reason is a bigger offense than some premature yolomerging, which is why I'm being so anal about the semantics here (also the fact that I'm p anal about semantics in the first place)

**Comment by feemjmeem** [comment]
i just fucking noticed this and i wrote it in the first place and I FUCKING ASKED FOR COMMENTS ABOUT WHETHER OR NOT SUICIDES SHOULD DO SHIT LIKE THAT and was given the go-ahead by bluespace and goofball

**Comment by feemjmeem** [comment]
who i understand aren't exactly the arbiters of behavior here, but the PR implementing this was up for a week before it was merged and nobody gave a fuck then

**Comment by duncathan** [comment]
For the record a go ahead from goofball is not the most reliable reasoning

**Comment by Lumipharon** [comment]
goof still has smg's with 42 round mags, and INCINDIARY instead of incendiary.

**Pull request merged**
