### PR TITLE
Flashes and Flashers

### PR DESCRIPTION
**Pull request by Ikarrus**
##### Machine Flashers
- No longer have a flat 4% burn out chance that was essentially making it useless even in calm times. Instead, they use the same cooldown system flashes have.
  - They have a "charge interval" of 30 seconds, as opposed to handheld flashes' 10.
##### Handheld Flashes
- AOE flash confusion time reduced to 1 tick
- Chance of burnout from overuse is increased
  - Successful rev conversions don't count as a "use", so revheads should still be able to convert without much worry.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
As much as this is needed I think we should look at either buffing security's sidearm, or reverting armor changes before we nerf their most powerful weapon.

**Comment by Lumipharon** [comment]
Honestly, nerf the handflash more.
It's a full screen BLIND, even with just 2s of confusion, that's more then enough time to cross the screen to either run away or apply axe to head, with a 2nd use of the flash for good measure.

Reduce the range, at the very least, and ideally, a CD.

Also, having a flash makes you ghetto protected from anyone using emp's, since it triggers the flash, blinding and confusing the attacker.

**Comment by Falamazeer** [comment]
Just remove the confuse altogether, Flashes worked fine before as a riot suppression, the blind was enough to get people to fuck off out of the area you wanted em fucked off from, except the most committed of rubberneckers.

And how increased are we talking for that burnout? because making them shitty is shitty.
Just reduce their effects, not fuck em up to the point nobody wants to play with them anymore.

**Comment by Ikarrus** [comment]
>And how increased are we talking for that burnout? 
+1% per use

**Comment by Falamazeer** [comment]
That's plenty reasonable, Still, it works better as a scatter tool if the people it get's used on are actually capable of scattering rather than a sad twitchy little circle

**Comment by Falamazeer** [comment]
Excellent, Can't wait to try it out in game, less spammable, and more utility, good on you.

**Pull request merged**
