### PR TITLE
Fixes headless mobs being flashbanged

### LINKED ISSUE #27273: Lack of head does not prevent flashbangs from working.
Same with tear gas.

Poor changelings.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes https://github.com/tgstation/tgstation/issues/27273

### CODE REVIEW

**Comment by swindly** [comment]
Changelings without heads should not be affected by flashbangs because they do not see or hear.
Changelings without heads should not be blind and deaf because __________

**Comment by Repukan** [comment]
Powercreep

**Comment by ShizCalev** [comment]
@swindly Changelings already are blind and deaf when they are missing their head, actually.

They are not mute however, which is slightly strange.

**Comment by ShizCalev** [comment]
@swindly Changelings already are blind and deaf when they lose their head, actually.

They are not mute however, which is slightly strange.

**Comment by kevinz000** [comment]
powercreep/pointless nerf to me

**Comment by AnturK** [comment]
I choose #27291 as a cleaner solution to the same problem so i'll be closing this.

**Pull request closed without merging**
