### PR TITLE
[RePR'd] Fixes metastation science/service delivery chutes causing fractures to anyone who enters.

### LINKED ISSUE #56651: Mapping issue with metastation science.
When you take the disposal system to science the window next to the disposal bin is too close to the outlet - the result is guaranteed fractures.

### PR DESCRIPTION
**Pull request by Potato-Masher**
Alright so apparently I'm clueless when it comes to fixing mapping merge conflicts so I just went ahead and remade my changes on a separate PR because there wasn't that much changed to begin with.
Refer to the previous PR #56769

## About The Pull Request
Fixes #56651 
Taking the disposals chutes from Metastation cargo to science's exterior output would spit you out and slam you into the directional window that was too close the the output, resulting in bone fractures. I've moved a few things around to ensure that the chute is at least usable without immediate risk of self injury.

I've also moved a crate out of the output of the service hall chute, as that also would cause fractures after exiting.

A few touch ups on the decals have also been made by adding those fancy colored siding decals to the edges of the output areas, just like what the new Meta science had. Why? I thought it looked nice.

## Why It's Good For The Game
Consistent with the other delivery chutes, which don't break your bones.

## Changelog
:cl: Potato Masher
fix: Taking Metastation's delivery chute to science and service should no longer cause bone fractures.
/:cl:

### CODE REVIEW

**Comment by Potato-Masher** [comment]
I'm honestly not sure why it says there are no more conflicts. I moved one crate and apparently it's good now(?).

**Comment by Potato-Masher** [comment]
@EOBGames All good here now, if you have the time to take a look.

**Comment by EOBGames** [comment]
Hey @Potato-Masher I can't see it in the screenshots- where was the produce console moved to?

**Comment by Potato-Masher** [comment]
> 
> 
> Hey Potato Masher I can't see it in the screenshots- where was the produce console moved to?

It wasn't moved at all, the crate was. Produce console is in the same spot.
I really do need to be more specific in these, don't I? Sorry again.

**Comment by EOBGames** [comment]
No that's fine, so long as it's still there then there's no issue

**Pull request merged**
