### PR TITLE
New PDAs 2: Revengeance

### PR DESCRIPTION
**Pull request by maxymax13**
## About The Pull Request
Sucks the soul out of PDAs, again. This time they don't look like shit. (hopefully)
Some tips given by Flareguy. Clear PDA was made by violently murdering Kryson's clear PDA resprite.

pdas
pda

updated
peedas

## Why It's Good For The Game
the clown pda was literally light pink and dark saturated fuschia

## Changelog
:cl: maxymax13, Flareguy, Kryson
imageadd: Completely resprited PDAs!
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
@Qustinnus you can only reject the unavoidable

**Comment by necromanceranne** [comment]
The military PDA could maybe use some menacing-up but otherwise looks pretty solid.

**Comment by maxymax13** [comment]
> 
> 
> The military PDA could maybe use some menacing-up but otherwise looks pretty solid.

there's a military pda? which one is that?

**Comment by CRITAWAKETS** [comment]
this looks terrible, what the hell is that shading

**Comment by CameronWoof** [comment]
I think these look really solid. Some of the colors are a little washed-out to my eyes (they don't read as shiny plastic casings), but the vast majority look great and they're all an upgrade from the original sprites.

**Comment by RaveRadbury** [comment]
It looks like you touched the alert overlay, but did you give the pAI overlay any love?

**Comment by Imaginos16** [comment]
> > The military PDA could maybe use some menacing-up but otherwise looks pretty solid.
> 
> there's a military pda? which one is that?

The Military PDA is the blood-red one at the very top right. This one is intended for Nuclear Operatives.

**Comment by MrDoomBringer** [comment]
the effort is really good and PDA sprites are in need of an upgrade, but I don't think this is the right direction

**Comment by MTandi** [comment]
The screen is already tiny, why would you make it smaller? I like the old ones more.

**Comment by bluetshirtguy** [comment]
you had the chance to give some of the pda's(like the clowns) more personality but you kept it almost the same as a brick, no thanks.

**Comment by Fikou** [comment]
the color changes you made are really weird and dont fit at all like security becoming fuckin orange and syndies a bright red
also the sprites on the left you posted on the discord seemed much better and they were 3/4 fitting with other object sprite changes in the game
image

**Comment by interestingusernam3** [comment]
This sucks ass.

**Comment by FloranOtten** [comment]
This is a step backwards imo. These are way less detailed and feel like something that came before our current PDA sprites, not after.

**Comment by Coastfront** [comment]
These actual cause me physical pain.

**Comment by Qustinnus** [comment]
I agree with fikou, I saw you post that image and I imagined you'd pick the left ones because they actually fit our style and look good. The ones you PR'ed don't really look good

**Comment by cacogen** [comment]
They do look more generic, but the change doesn't really add anything to justify it. It just looks worse. Desaturated. They do look like they'd remain consistent with most of the other sprites in the game though.

Once again, there are sprites to update in this game that have always looked like shit. Any change would look better. But I guess those aren't front and centre or fun to work on.

**Comment by MrDoomBringer** [comment]
> also the sprites on the left you posted on the discord seemed much better and they were 3/4 fitting with other object sprite changes in the game
> image

why would you not go with the left side ones they look great

**Comment by maxymax13** [comment]
> 
> 
> > also the sprites on the left you posted on the discord seemed much better and they were 3/4 fitting with other object sprite changes in the game
> > image
> 
> why would you not go with the left side ones they look great

because they looked like monitors from a gba pokemon game more than a pda

**Comment by Dorsisdwarf** [comment]
I was under the impression we were trying to replace our 2010 codersprites with modern high quality spriting, not vice versa.

**Review by Twaticus — CHANGES_REQUESTED** [review]
i said previously that i liked the resprites, but seeing the direct comparison gif points out some flaws. i think the outlines need some more contrast since they blend in too much on many of the pdas. plus some adjusting of the reds/blacks

**Comment by maxymax13** [comment]
will be adjusting palettes

**Comment by maxymax13** [comment]
im working on it i promise!!!!On Feb 13, 2021 21:42, "github-actions[bot]" <notifications@github.com> wrote:
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

**Comment by cacogen** [comment]
Can I be in charge of sprites? I promise you I will only allow improvements

**Comment by maxymax13** [comment]
is there anything else that stills look particularly doo doo? i know the red pdas are brighter but dark base colors would mean that all the shading just turns to undecipherable black, same reason the black pdas are brighter

**Comment by LemonInTheDark** [comment]
@Twaticus do you want this?

**Comment by cacogen** [comment]
Not trying to insult your work but they look flat and washed out. Like a worse version of what came before.

**Comment by Twaticus** [comment]
still the same problem as before, contrast between the base and outlines arent enough. might be better to revisit the palette from the scrapped version here.
> image

 i still really like the shape of the new ones its just those colors man. can try these again in the future when theyre ready

**Pull request closed without merging**
