### PR TITLE
New Drone Skin

### PR DESCRIPTION
**Pull request by RemieRichards**
New "Scout" drone skin (Name taken from the artist's post)
- Normal state (Skowron)
- Animated movement state (Skowron)
- Dead state (Myself)
- Hat + Worn hat states (Myself)

Not exactly an affront to the freeze as it's a small change that:
- Has been tested
- Has 0% chance to break anything important.

Drone lineup (New one in the middle):
dronelineup

tl;dr: cute.
@SkowronX pinging for attention.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
I like this one much better than the right-hand one

**Comment by RemieRichards** [comment]
Well we have some fans of the left sprite, mainly those who remember that state from NT.
We have some fans of the right most sprite.
And now we can have fans of the new sprite.

It's the reason I made the skin system generic enough to expand simply, lots of choice for everybody.

**Comment by SkowronX** [comment]
Funny thing is. That skin was for an event a while ago which unfortunately went disastrously wrong.

**Comment by WJohn** [comment]
The original left sprite is so ugly ;~;

The mid and right one are fantastic though :+1:

**Comment by GunHog** [comment]
One reason I love RR. She gives you the option to pick the sprite you want, satisfying the opinion of everyone except the people who are of the opinion that people should not have choices!

**Comment by Miauw62** [comment]
Right one looks very vague, imo. but vov

**Comment by RemieRichards** [comment]
## DO NOT COMMENT ON THE LEFT OR THE RIGHT ONE
THEY ARE ALREADY IN GAME!

**Comment by optimumtact** [comment]
REMOVE DRONES, REMOVE DRONES
REEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by MartiUK** [comment]
You've spelt appearance wrong all the way through the diff. 
grammarnazi

**Comment by RemieRichards** [comment]
doesn't matter.

**Comment by pudl** [comment]
i actually think the scout skin is the worst of the three. there's nothing wrong with adding it since it's optional, but i think it's pretty ugly

**Comment by cl159** [comment]
So cute.

**Pull request merged**
