### PR TITLE
Mekhi goes on the table

### PR DESCRIPTION
**Pull request by MrsTonedOne**
:cl:
balance: You no longer need an aggressive grab to table someone.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
:-1:

**Comment by YakumoChen** [comment]
lol

**Comment by TheDreamweaver** [comment]
:^)

**Comment by PKPenguin321** [comment]
:-1: but un-nerf table stuns

**Comment by Tlaltecuhtli** [comment]
op

**Comment by 81Denton** [comment]
What if this only applied to catpeople...

**Comment by Robustin** [comment]
This wouldn't be a big deal if you couldn't table someone from 100--->0 without them ever losing the stun.

**Comment by cebutris** [comment]
Citadel-Station-13/Citadel-Station-13#5222

**Comment by ExcessiveUseOfCobblestone** [comment]
> allowing ckey references in your code

disgusting

**Comment by Cyberboss** [comment]
this will be fun, honk

**Comment by Buggy123** [comment]
W E W L A D

**Comment by 81Denton** [comment]
M A D L A D
A
D
L
A
D

**Comment by Ordonis** [comment]
I blame Kevinz for any problems with this PR

**Comment by qbmax32** [comment]
Absolute 



Madman

**Comment by Nickvr628** [comment]
inb4 new meta is to build a table beside your target for instant stuns

**Comment by Bawhoppen** [comment]
If only emergency table parts was still a viable concept...

**Pull request merged**
