### PR TITLE
Bullets only directly damage the SM so much

### PR DESCRIPTION
**Pull request by Maurukas**
## About The Pull Request
Requested by @Mothblocks as an alternative to #62073

There is a broad consensus that being able to trigger an instantaneous delamination within the first few minutes of the round is not fun. The point has also been made that this is a valid antag strategy, and antag freedom is a policy. An antagonist has a legitimate reason to speed up a delamination, and if they invest the TC (or other effort), they should be able to do so.

## Why It's Good For The Game

This tries to strike a happy medium. The bullet damage to the crystal now drops off linearly. It receives full damage from bullets at full health, and drops to 0 damage at 700 (20% health). 700 is the emergency threshold where the crystal starts screaming for help on the common radio. Beyond this point the crystal needs to delaminate via the usual mechanisms that damage it.

This allows the antagonist to substantially accelerate a delamination, but gives the crew a chance to respond.

## Changelog

:cl:
balance: The super matter crystal can no longer be immediately delaminated by firing a gun into it, only brought close to the delamination threshold.

/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
image

**Comment by EricZilla** [comment]
> ah yes, the arbitrary reason of the crystal just ignoring bullet damage at 700 damage

We can make up lore for why it does this, obviously as it destabilizes its ability to absorb matter and do weird nonsense increases, so past a certain point, its absorbing so quickly that it doesnt matter how hard you hit it, its going to ignore it

**Comment by Mothblocks** [comment]
I'm also fine with something like that

**Comment by Maurukas** [comment]
Thank you for the feedback. Damage multiplier on bullets now drops off linearly like so. For reference, the crystal starts screaming at engineers at x=50, starts shooting angrybolts at x=550, screams in common at 700, and blows up at 900.

image

**Comment by Bawhoppen** [comment]
Perhaps something like: "The crystal structure tenses and hardens after the impact!"

**Comment by nianjiilical** [comment]
could make the crystal visibly light up and flash angry colors when it hits the 700 threshhold and justify it saying that it got hotter and more active and thus its absorbing more kinetic energy or something idk

**Pull request merged**
