### PR TITLE
spaces -> tabs in vendor code

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-changes space indentation to tabs

## Why It's Good For The Coders
-makes us look less ooga

## Changelog

:cl:
code: vendor code has less spaces and more tabs
/:cl:

### CODE REVIEW

**Review by Mothblocks — CHANGES_REQUESTED** [review]
if you're going to touch all this and make the blames jank anyway, you should at the very least fix them to be the proper indentation, that being only indenting up ONE level higher. e.g.

```dm
contraband = list(
    /obj/item/bad_item, // note them only going up once
    /obj/item/awful_item,
)

**Comment by Mooshimi** [comment]
> if you're going to touch all this and make the blames jank anyway, you should at the very least fix them to be the proper indentation, that being only indenting up ONE level higher. e.g.
> 
> ```dm
> contraband = list(
>     /obj/item/bad_item, // note them only going up once
>     /obj/item/awful_item,
> )
> ```

what does "make the blames jank" mean

**Comment by Mothblocks** [comment]
every time anyone edits a line, it goes on a git blame, making it harder to figure out when stuff actually changed. preferably unnecessary edits to these are kept minimal

**Comment by Mothblocks** [comment]
i'd ask for trailing commas too but this is fine

**Pull request merged**
