### PR TITLE
Resprites The HoS Greatcoat

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Alright, here's the situation:

This thing? Doesn't look good, and doesn't fit the overall aesthetics we're going for security as of late.
image

As a result, I've decided to resprite it, by utilizing the one BeeStation has as a base (added in PR: [Updates HoS Coat #3725](https://github.com/BeeStation/BeeStation-Hornet/pull/3725)), created by Naevii!
image

This PR also adds a matching object icon to the recently resprited Head of Security trenchcoat
image

## Why It's Good For The Game
Modernizing aesthetics is very important!

## Changelog

:cl: PositiveEntropy, Naevii
imageadd: Resprites the Head of Security Greatcoat!
imageadd: Resprites the object icon of the Head of Security Trenchcoat
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
wish the double buttons stayed

**Comment by Imaginos16** [comment]
> wish the double buttons stayed

Would've looked too cluttered

**Comment by Serxule** [comment]
i think bee has a sprite similar to this, looks good. although maybe have it extended a little lower or make it less slanted outwards, looks a bit like a skirt imo

**Comment by Imaginos16** [comment]
> i think bee has a sprite similar to this, looks good. although maybe have it extended a little lower or make it less slanted outwards, looks a bit like a skirt imo

The PR directly mentions the source being the Bee Station one.

**Comment by Serxule** [comment]
> The PR directly mentions the source being the Bee Station one.

i am infact blind

**Comment by Colovorat** [comment]
Honestly... Souling...

**Comment by Farquaar** [comment]
Stop trying to take away my double buttons. The old one actually looks like a greatcoat- this is just looks like the HoS' default jacket.

**Comment by Imaginos16** [comment]
There's an entire debate on what the hell consitutes a greatcoat on the bee PR and I’m not going to entertain it here. If you wanna learn about it, go read the original.

**Comment by Farquaar** [comment]
> 
> There's an entire debate on what the hell consitutes a greatcoat on the bee PR and I’m not going to entertain it here. If you wanna learn about it, go read the original.

I don't care what people on Bee think. I'm telling you that I don't like this sprite because it takes something unique and makes it generic and boring.

**Comment by Imaginos16** [comment]
lol

**Comment by Farquaar** [comment]
Snark all you want. You're taking the greatcoat, which was a unique style that covered the legs and gave the HoS a more "soviet commissar" look and replacing it with something that looks like the regular HoS jacket with the buttons done up. This new "greatcoat" doesn't even cover the legs.
image

**Comment by Twaticus** [comment]
the buttons are fine, but i dont like the flare at the bottom. what if it was longer like the original?

**Comment by Dorsisdwarf** [comment]
The object sprite doesnt match the on mob at all, is that just a recolour of the labcoat?

**Comment by Imaginos16** [comment]
> The object sprite doesnt match the on mob at all, is that just a recolour of the labcoat?

Did you not at any point grab the mob icon for the trenchcoat and compare it to the new object icon? Its almost the exact same

**Comment by cacogen** [comment]
>You're taking the greatcoat, which was a unique style that gave the HoS a more "soviet commissar" look

It's an homage to Human Revolution. These sprites look worse.

**Comment by bluetshirtguy** [comment]
where's the titty version to be in line with the hos's other wardrobe?

**Comment by Imaginos16** [comment]
Addressing Twaticus criticism, I've made it longer.

image

**Comment by cacogen** [comment]
It doesn't even look more modern than the old one.

**Pull request merged**
