### PR TITLE
Metastation shuttle rotation

### PR DESCRIPTION
**Pull request by coiax**
Modifies the Metastation map and shuttle to now dock on its side, bringing the shuttle and port into line with all the other servers, opening them up to exciting shuttle related memes.

image

image

### CODE REVIEW

**Comment by Metacide** [comment]
:+1: :+1: :+1:

**Comment by pudl** [comment]
screenshots, and why?

**Comment by Metacide** [comment]
So the shuttles on different maps are interchangeable and so can be varied more easily, I thought.

**Comment by Niknakflak** [comment]
I was gonna go eh but even the map maker himself supports it so :+1:

**Comment by TheNightingale** [comment]
Hijacking 101: emag shut the Escape doors, then smash into the Bridge area with a fire axe, climb over the tables, emag the console, done.

**Comment by coiax** [comment]
Calling that emergent gameplay.

**Comment by Niknakflak** [comment]
On the engine, there is a solid grey block instead of a corner diagonal

**Comment by coiax** [comment]
I know. I'm really shit at mapping. I couldn't find the current settings to make it appear, so I'm hoping someone less terrible will be able to fix it for me.

**Comment by Jordie0608** [comment]
Right click on an entity in the map editor's entity list and select 'Generate from Directions' to make copies of the selected entity with each icon in the icon file.

**Pull request merged**
