### PR TITLE
adds a new super dank meme to retardspeak

### PR DESCRIPTION
**Pull request by theOperand**

### CODE REVIEW

**Comment by SconesC** [comment]
3/10

**Comment by Xhuis** [comment]
conflicts with #9169 reee

**Comment by Miauw62** [comment]
then add it to #9169 you normie

**Comment by Dorsisdwarf** [comment]
Not gibbery enough 2/10 would not ethnic cleanse

**Comment by pudl** [comment]
not a funny meme 2.5/10

**Comment by Iamgoofball** [comment]
needs to only be enabled if lizards are compiled in just like with the grafittis

**Comment by freerealestate** [comment]
this bad meme got tired months ago, why put it in the code for us to have to endure for years to come

**Comment by optimumtact** [comment]
Where is PSHOOOOOOOOOOOM

**Comment by Cheridan** [comment]
butthurt lizard detected

**Comment by Miauw62** [comment]
memes are eternal

**Comment by freerealestate** [comment]
>butthurt lizard detected

never played one

**Pull request closed without merging**
