### PR TITLE
pod people now take more damage from plant-b-gone, fly people take more from pest spray

### PR DESCRIPTION
**Pull request by ghost**
lets at least have this small pretense of balance in our species because they're a god damn mess right now and the only good part of them are the halloween races and the golems

a lot more of my reasoning is in #32197

### CODE REVIEW

**Comment by Armhulen** [comment]
flypeople take like esword damage from swatters but pod people take 3 damage from plant b gone (THEY HEAL ONE TOXIN DAMAGE PER TICK BRO)

**Comment by The-clown-known-as-Pepe** [comment]
bad mutations from plant killer?
Doesn't make a lot of sense to me

maybe give them 2-3 mutations instead of one per tick of mutagen?

**Comment by DoctoreMad** [comment]
>20 toxin

Calm the fuck down

**Comment by XDTM** [comment]
>5 second kills

why even bother with the mutations

**Comment by Armhulen** [comment]
i should have done 30 damage but i'm nice. besides, it's super easy to dodge sprays.

**Comment by praisenarsie** [comment]
not if you're standing still

**Comment by XDTM** [comment]
oh yeah a chem instantly kills you but it's k cause it might not hit you

**Comment by DoctoreMad** [comment]
Wait didn't you already sperg about Plant people in a earlier PR?
Requesting I DED tag.

**Comment by Armhulen** [comment]
20 damage is not an instant kill, a bad mutation could be stuttering grow up

**Comment by DoctoreMad** [comment]
>grow up

Sides lost

**Comment by Armhulen** [comment]
DUDE 20 TOXIN DAMAGE LMAO

**Comment by Armhulen** [comment]
OH NO MY ROUNDSTART HEAL ALL DAMAGE TYPE RACE IS COUNTERED BY A RARE ITEM ONLY BOTANISTS HAVE ACCESS TOO WHAT THE FUCK

**Comment by Armhulen** [comment]
i could settle for 30 no mutation

**Comment by DoctoreMad** [comment]
This guy with a paper bag head walks up to you in a dark alley and screams



What do you do?

**Comment by XDTM** [comment]
Dude the damage is not on application it's on every reagent tick

**Comment by Slignerd** [comment]
It doesn't seem like the flypeople part is currently implemented.

**Comment by Armhulen** [comment]
@XDTM 	i thought it dealt the damage then left your system uuuuuuuuuh

**Pull request closed without merging**
