### PR TITLE
Adds admin antag-hud

### PR DESCRIPTION
**Pull request by lordpidey**
Upgrades the admin antag hud to also show changlings, traitors, abductors, abductees, and ninjas.

Right now, it's admin only, but I intend on using this in the demon gamemode (selling soul for "knowledge")

Given that it only effects admins, I feel no changelog is needed.

### CODE REVIEW

**Comment by lzimann** [comment]
looks good :+1:, any possibility of making it to gans aswell?

**Comment by lordpidey** [comment]
FUCK.  I screwed up on this.  I'll fix it tomorrow.

**Comment by Shadowlight213** [comment]
@lordpidey They mean gangs.

**Comment by lzimann** [comment]
yea gangs, my bad, didn't realize the typo

**Comment by lordpidey** [comment]
Aright, I've fixed the problems with it.

**Pull request merged**
