### PR TITLE
Buffs the Families Military officers

### PR DESCRIPTION
**Pull request by FloranOtten**
## About The Pull Request

This changes the Military's laser scattergun for an NT-ARG "Boarder" rifle.

## Why It's Good For The Game

The laser scattergun is shit. It is dogshit. It takes 5 shots at point blank range to crit someone. This means the National Guard is weaker than the previous tier. It is currently adventageous to go from 4 to 5 stars because the cops will be weaker. This PR gives them a better weapon, which is a direct upgrade from the FBI's weapon. 

## Changelog
:cl: 
balance: The Space Military has recently recieved guns, which have been described as being "Actually worth a damn"
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
there is a typo in your changelog, military is misspelled unless it was intentional

**Comment by FloranOtten** [comment]
> there is a typo in your changelog, military is misspelled unless it was intentional

This never happened

**Comment by Capsandi** [comment]
there is a typo in your PR title, military is misspelled unless it was intentional

**Comment by FloranOtten** [comment]
> there is a typo in your PR title, military is misspelled unless it was intentional

SHUSH

**Comment by Pugie** [comment]
Give. Them. The. Tank.

**Comment by FloranOtten** [comment]
> Give. Them. The. Tank.

this.  Straight port from TGMC if need be.

**Comment by necromanceranne** [comment]
Boarders are equivalent to giving them to m90's, so they're closer to a sending an op squad at the station.

I think the issue is with how piddly the scatterlaser rifle is compared to it's shotgun shell equivalent that is using weak lasers. I think I know a way to fix this.

**Comment by Doosteroni** [comment]
> Boarders are equivalent to giving them m90s

Actually boarders have a higher fire rate I think

**Comment by necromanceranne** [comment]
@Doosteroni same shots, and a fire rate of 2 to the boarders 1, while also having a spread. It only really means the boarder is a +1 on the m90, and the m90 is arguably one of the better guns even if it struggles to have a decent identity compared to the L6.

My point still stands, basically.

**Comment by FloranOtten** [comment]
> Boarders are equivalent to giving them to m90's, so they're closer to a sending an op squad at the station.
> 
> I think the issue is with how piddly the scatterlaser rifle is compared to it's shotgun shell equivalent that is using weak lasers. I think I know a way to fix this.

The issue is with how utterly weak the current national guard is. This doesn't make them that powerful, honestly. You cannot get more ammo for these, as far as I know. If you start spraying, with 4 bullets critting someone, you're going to be out of ammo right quick. They aren't like ops because they have none of the other gear. They have flashbangs, tear gas, a cool vest and this gun. No explosives, no medibots, no eswords, no nothing. As it stands, anyone with a shotgun can outfight the national guard.

Besides, even if they WERE ultra powerful after this, is that a problem? The stars should discourage random violence, and getting to 5 stars should be an extremely bad event.

**Comment by ExcessiveUseOfCobblestone** [comment]
@bobbahbrown i just got your starbound joke lol

**Comment by Doosteroni** [comment]
How about we give boarders their own mag so they make sense instead of using space p90 mags. The boarder is a pretty unfinished gun

**Comment by Doosteroni** [comment]
Staaaaaaaale

**Comment by FloranOtten** [comment]
god damn merge conflicts

**Comment by FloranOtten** [comment]
This no longer merge conflicts! Hooray!

**Comment by FloranOtten** [comment]
Redundant in the near future.

**Pull request closed without merging**
