### PR TITLE
Makes holoparasites vulnerable to EMPs

### PR DESCRIPTION
**Pull request by Thunder12345**
:cl:
tweak: Manufacturing cost concerns have resulted in newly produced holoparasites suffering a significant vulnerability to EMPs. Crews are now recommended to engage with the station's ion rifle.
/:cl:
Alternative solution to nerfing holoparasites, instead of increasing the cost, to give them a significant vulnerability.
Every hit from the ion rifle multiplies the damage_transfer of the stand by a factor of 1.15, and forces it to recall. Forced recalls will not respect the usual cooldown.

### CODE REVIEW

**Comment by KazeEspada** [comment]
50% of fucking traitors. Hooray!

**Comment by Shapsy** [comment]
I can't say I've ever been in a situation where I was being attacked by a holoparasite and had access to an ion rifle but not a laser gun, so I don't really know if this would ever really come into play in game

**Comment by Zilenan91** [comment]
It's for when you know they have a holo, because a tator who's going loud with a standard since standards are OP right now is probably gonna have a taser + stunbaton/prod, so they'll just run around stunning then having the parasite pop out and punch the dude to death then zipping back inside. It's honestly ridiculous how quick the snowball is if you munchkin a prod. Just stun an officer, have your parasite jump out, punch him to death before he can react, then shittily murderbone until you eventually get killed. The problem honestly lies with standards.

@Thunder12345 I assume the ion projectiles would affect the holo while it's inside of someone right?

**Comment by Thunder12345** [comment]
Yeah, I realised this is only just as effective as a laser, gonna change how it works tomorrow. Make it increase the stand's damage multiplier instead, so while not directly damaging, it makes the thing far more vulnerable

**Comment by Durkel** [comment]
Don't forget that there are other ways to get holos besides the injectors currently. (only available  one is the tarrot deck from the wizard academy away mission) but it wouldn't make sense for a emp to give a magic ghost problems.

**Comment by Fox-McCloud** [comment]
This is going to have zero actual impact on guardians.

There's, what? A single ion rifle in the armory and day to day crew don't have access to EMPs except for iron+uranium.

IMO, there's better ways to nerf these guys; like their melee damage, ranged attack cooldowns, heal delay, etc.

**Comment by KorPhaeron** [comment]
EMP is the most cancerous way in the world to balance something because its a massive AoE.

Having a fight come down to a binary question of "did you have the right gear? If so you win with little interaction. If not you're fucked" is terrible game design and boring for both sides 

Plus it makes no sense with the ghosts or biological versions.

I'd rather raise the price than do this because I have such a distaste for EMP balance in general.

And yeah if you are in the armory you already have shotguns or laserguns which both counter the parasite hard

**Comment by KorPhaeron** [comment]
>Just stun an officer

Wow its almost like the stun killed them and not the parasite. If you have access to a stun you can toolbox someone to death.

**Comment by KorPhaeron** [comment]
>Manufacturing cost concerns

Also they are aliens not manufactured please respect the deep lore

**Comment by Thunder12345** [comment]
Except they are quite clearly described as nanomachines in various places.

**Comment by KorPhaeron** [comment]
They're an alien race of sentient nanomachines that use organic creatures as hosts.

**Comment by Bawhoppen** [comment]
maybe make it so hitting the stand with a stun of any kind would stun the host and possibly damage aswell?

**Comment by Thunder12345** [comment]
Not really sensible to make so many changes at once. I'd rather let this one be in for a while and see how it works before looking at extra nerfs.

**Comment by Amemelius** [comment]
Holoparasites aren't OP. How the shit are standards OP, I've beaten at least two in recent mind with nothing but a toolbox and a welder 1v1?

**Comment by tkdrg** [comment]
Yeah I don't know, I don't think holoparasites are an issue right now, and EMP doesn't make a lot of sense either (both fluff-wise and for the general lack of EMPs on the loyalist side).

**Comment by tkdrg** [comment]
Closing because of the arguments presented here, feel free to ask another maintainer/headcoder to reopen if you disagree.

**Pull request closed without merging**
