### PR TITLE
Adds a medical laptop to Birdshot's morgue

### LINKED ISSUE #76792: Medical laptop is missing from Birdshot's morgue
Yeah, there really should be one there for consistency's sake. Part of Coroner's job is updating crew records when someone bites it, so they ideally should be able to do their job without needing to leave the morgue.

It's pretty small so it might require shuffling around things or expanding the space by a tile or two, but I'm sure we can fit one in somewhere.

### PR DESCRIPTION
**Pull request by dieamond13**
## About The Pull Request
This shuffles around a few things to fit a medical laptop in Birdshot's morgue.
Fixes #76792
## Why It's Good For The Game
Good for consistency between maps.
## Changelog
:cl:
fix: added a medical laptop to Birdshot morgue for consistency's sake
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
If you put "Fixes #76792" in the body of your PR, it'll automatically close my issue report when this is merged.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
You have put three laptops, not one 

image

**Review by MrMelbert — COMMENTED** [review]
Nitpick: Fix the floor siding decals around the morgue that you have moved

Also I would suggest swapping the location of the second tray with the vendor

image

**Comment by dieamond13** [comment]
> You have put three laptops, not one
> 
No idea how I managed to pull that off, seemed normal when I tested, but it should be fixed now along with the siding, I also swapped the vendor with the other tray so it looks nicer like you suggested.

**Review by MrMelbert — APPROVED** [review]

**Comment by MrMelbert** [comment]
Hey think you can address #76960 when you go to fix your merge conflicts?

**Comment by dieamond13** [comment]
just gonna close this because I haven't been able to work on it for a while and won't be able to for a few days

**Pull request closed without merging**
