### PR TITLE
Removes stupid fetish content.

### PR DESCRIPTION
**Pull request by Iamgoofball**
We don't need to legitimize stupid porn.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Isn't this byond members only.

**Comment by Iamgoofball** [comment]
@MrStonedOne I removed the BYOND member's stuff, but I also removed the random "lusty xenomorph maid" queen and drone that can spawn in gold slime cores(and often do)

**Comment by Iamgoofball** [comment]
admins also seem to enjoy spawning the fetish xenos and making them invincible and calling it an event

WJ got deadminned for using this to ERP

**Comment by KorPhaeron** [comment]
It's a parody of a paraody you baka

**Comment by Iamgoofball** [comment]
@KorPhaeron there's a difference between a parody and adding fetish content to the game sprited by a guy with a known fetish for xenomorphs, who forced it through by abusing his status as sprite lead

**Comment by KorPhaeron** [comment]
Figures a redditor like goof would remove /tg/ culture

**Comment by d4n0w4r** [comment]
save us kor

**Comment by anconfuzedrock** [comment]
I was excited for a second cuz I thought this removed ditigrades then I was dissapointed

**Comment by KorPhaeron** [comment]
Also the invincible versions of these spawn on Coiax's bar shuttle (along with an invincible bar drone), it's nothing to do with secret admin ERP conspiracies

**Comment by Durkel** [comment]
>We don't need to legitimize stupid porn.

>the same guy who added a gym from a gay porno.

What did he mean by this?

**Comment by Shadowlight213** [comment]
@Durkel Don't need to legitimize any but his he means

**Comment by PKPenguin321** [comment]
Leave leatherman alone

**Comment by Iamgoofball** [comment]
@KorPhaeron No, admins have been spawning them. I've joined many rounds where some admin thought a hillarious and original event was an invincible xenomorph maid

**Comment by Shapsy** [comment]
Goof you literally added a fetish leather suit didn't you

**Pull request closed without merging**
