### PR TITLE
Revert "Replaces Upgraded Cybernetic Ears with two new variants "

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Reverts tgstation/tgstation#75931

Redid the entire hearing chain and did it poorly.
No one could hear tcomms when alive for any reason.

### CODE REVIEW

**Comment by MrMelbert** [comment]
you should probably say in the pr body why you opened this

**Comment by TheVekter** [comment]
This is why we test shit

**Comment by Time-Green** [comment]
Goddammit

**Comment by Thunder12345** [comment]
150 hours of testing

**Comment by Time-Green** [comment]
@GPeckman

**Comment by MrMelbert** [comment]
with hindsight we should've testmerged a pr that touches the hearing chain to moderate degree

**Comment by Mothblocks** [comment]
Please figure out what specifically we can be unit testing in the future. Core stuff like this definitely needs coverage

**Comment by GPeckman** [comment]
Got a fix PR for this up here: https://github.com/tgstation/tgstation/pull/77353

**Comment by GPeckman** [comment]
> Please figure out what specifically we can be unit testing in the future. Core stuff like this definitely needs coverage

Unit testing is done for normal speech at a distance of 1, 5, and 10 tiles, but there is no unit testing for radio speech. I can look into adding unit testing for that.

**Comment by Time-Green** [comment]
Bug has been fixed, testmerges also work while closed until it hits live

**Comment by Mothblocks** [comment]
@GPeckman Yes please look into that

**Comment by Sealed101** [comment]
why is this still being test merged

**Comment by Time-Green** [comment]
Huh, no idea. Kinda expected it to automatically stop after the branch got deleted and or if a conflict arose from the fix

**Comment by GPeckman** [comment]
The fix wouldn't actually cause a merge conflict anyways, so that might be why.

**Pull request closed without merging**
