### PR TITLE
Improved Beach Away Mission

### PR DESCRIPTION
**Pull request by ishitbyabullet**
## About The Pull Request
This deletes the two old beach away missions which were either very small and or had broken invisible walls. To make up for this loss, there is now only one beach away mission which is bigger, uses the sprites made for the summerball 1-2 years ago, and has invisible walls that aren't scattered about randomly.
dreamseeker_2019-06-19_20-52-30

Besides that, there's just a bit more to do and explore however don't expect it to be as exciting as Snowdin.
## Why It's Good For The Game
Look at the old beach away missions. Those weren't very good. One was very small with a rock wall outline which makes it feel like the exact opposite of a beach. The other had walls that popped out of nowhere, invisible walls which were placed randomly, and it looked like it was one step away from being completely exposed to space.
## Changelog
:cl: Jerry Derpington, baldest of the balds
del: Nanotrasen has lost communication to two away mission sites that contained a beach for Nanotrasen employees.
add: Nanotrasen has been able to locate a new away mission site that ALSO has a beach. Nanotrasen employees will be able to enjoy the beach after all!
/:cl:

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
also if anyone thinks "**dude why would you do this if it's just rp**" then keep in mind that you have more chances at a fun away mission now instead of literally two beach away missions.

**Comment by granpawalton** [comment]
We should turn on the gateway for this away trip for a whole day so the server can have a summer vacation in game incase they are too poor to do it irl

**Comment by nicbn** [comment]
Turn gateway on and make anyone with southern hemisphere ip go to Snowdin instead for maximum vacation rp

**Comment by NoxVS** [comment]
Should probably remove the signpost while you are at it, it allows you to teleport back to the station.

**Comment by Tlaltecuhtli** [comment]
bro did you run map merger

**Comment by MMMiracles** [comment]
the fact the beach mission was remade twice and neither times did the idea 'make it into an island' ever surface is the most amazing part to me.

**Comment by FantasticFwoosh** [comment]
Its not really a island if you can walk all over the water like Jesus, i like the redesign but i think it just has too few things to pad it out featurewise/mechanically because the beach bum ruin does a passable job by comparison with lavaland right outside to explore and some bits of loot inside.

Its not like you can run to the beach to pick up sodium chloride & water, dig sandcastles, or cultivate coconuts in the open space to encourage work-busy crewmembers to stay for extended periods of time.

**Comment by ishitbyabullet** [comment]
@NoxVS Nah, not this one. It's a reskinned structure.

@MMMiracles They never had the proper sprites back then. It took until 2018 for them to exist.

@FantasticFwoosh This is true. Any and all beach away missions were pretty poor feature wise. The idea is that you only have ONE beach away mission that also looks like a beach, isn't broken, and isn't so small that anyone wonders why it isn't just a space ruin due to how tiny it is.

**Comment by Timonkeyn** [comment]
Why improve the away mission when you can't even access it

**Comment by ishitbyabullet** [comment]
@Timonkeyn because downstreams.

**Comment by optimumtact** [comment]
away missions are enabled on basil actually

**Pull request merged**
