### PR TITLE
Converts almost every single sound to mono 44.1khz, recuts some sounds.

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

As title, except a clarification: sounds that play with no source or direction are still stereo due to that the stereo will actually do something and not just be wasted space.

On a technical level, what I actually did was reexport (nearly) every single sound effect to mono 44.1khz sample rate Ogg at quality preset 5. This resulted in some _small_ increases in file size in some places but other than that reduced file size across the board.

A couple of sounds that were wavs for whatever reason were also converted to ogg, this resulted in some code changes to change the referenced sound effect.

Some sounds were also recut. The grille hit and punches in particular are common sounds that had large and noticeable gaps at the beginning.

All of this has resulted in the compiled rsc file going from 102.7 mb to 83.2 mb.

## Why It's Good For The Game

Free space with no (effective) drop in quality.
A standard for audio going forward. (that will be inevitably ignored)
Tighter sounds in some places.

## Changelog
:cl:
soundadd: Downmixed every sound to mono. This shouldn't have resulted in any changes in audio, byond downmixes anyways.
soundadd: Recut some sounds. Sounds shouldn't have large silent/noise gaps at the start anymore
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
416 hz is better

**Comment by nero1024** [comment]
Why 44.1KHz?

**Comment by SpaceManiac** [comment]
> Free space with no drop in quality.

What's the total drop in checkout size? What about the total drop in `.rsc` size?

**Comment by actioninja** [comment]
I'll do some more checks later but a quick comparison of compiles between branches is showing a 102.7 mb rsc file on master, and a 95 mb rsc file on the optimized branch.

**Comment by OverlyGeneric** [comment]
>tfw when achtungninjago converts every sound to mono but doesn't convert every stun to glorious stamina-based.

come on guys, goon is beating us in the "nerfing department"

**Comment by actioninja** [comment]
> Why 44.1KHz?

44.1KHz is a common audio sample rate standard due to it being the original CD sample rate standard. Also some code in the game assumes the sample rate of a file is 44.1khz.

**Comment by SpaceManiac** [comment]
> A standard for audio going forward. (that will be inevitably ignored)

If you care about this, write a script that can enforce the standard

**Comment by actioninja** [comment]
I don't really, I wasn't consistent myself. I didn't touch any file where the settings I was using resulted in 100kb+ more space taken up.

**Pull request merged**
