### PR TITLE
Changes deconversion font span from "big" to "command_headset" because "big" doesn't work.

### PR DESCRIPTION
**Pull request by silicons**
It isn't working in goonchat far as I can tell.

### CODE REVIEW

**Review by AnturK — CHANGES_REQUESTED** [review]
Fix the css instead.

**Comment by kevinz000** [comment]
@AnturK how

**Comment by kevinz000** [comment]
where's the tgui css?

**Comment by JJRcop** [comment]
@kevinz000
[interface/stylesheet.dm](https://github.com/tgstation/tgstation/blob/076c68961ef2732c881debbbf641c1cd232c0d7e/interface/stylesheet.dm#L144-L147)

**Comment by lzimann** [comment]
It is this [one](https://github.com/tgstation/tgstation/blob/master/code/modules/goonchat/browserassets/css/browserOutput.css). But keep both up to date.

**Pull request closed without merging**
