### PR TITLE
[Ready] Childproofs plastic flaps with windoors

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Crawl Gang
tweak: Plastic flaps that weren't protected by windoors now had them added to prevent players from just crawling through them.
/:cl:

Closes: #41347

I think this is a better solution than blocking players from crawling through. After all, most maps already had windoors in place at Mulebot delivery spots.

WIP, should be done around the weekend or so.

### CODE REVIEW

**Comment by kingoftheautism** [comment]
jesus thank god we have denton

seriously, that thing could kill disposals and mule bots, because no one wanted to bother with placing windoors under flaps

good pr

**Comment by yoyobatty** [comment]
Why not just add a PASS_FLAPS flag?

**Comment by XDTM** [comment]
because they're flaps, not magic barriers

**Comment by yoyobatty** [comment]
Just remove crawling, that was a mistake

**Comment by 81Denton** [comment]
It might also be a decent idea to make plastic flaps harder to remove than just using a screwdriver for 10 seconds. Even directional windows take more time/effort.

**Comment by yoyobatty** [comment]
Screwdriver, wrench, crowbar type thing?

**Comment by subject217** [comment]
since mapdiffbot is dead would you mind taking some pics of the edits you did?

**Comment by 81Denton** [comment]
Sure thing!

**Comment by 81Denton** [comment]
I had to shuffle some things around inside the Delta freezer; the flap there is now further south and the meat spikes/cooking oil vat/fire alarm/intercom moved. Everything is still accessible though.

Other than those changes, I only added windoors/r-windows to departments and adjusted piping/floor decals where neccessary.

delta-service
---
delta-medical
---
meta-atmos
---
delta-robotics
---
delta-engi

**Pull request merged**
