### PR TITLE
Gives Space Pirates a bonus to hijack speed on the shuttle, and allows them to hijack.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Gives Space Pirates a bonus to hijack speed on the shuttle. For if you find yourself stranded in a Nanotrasen port without a space-worthy vessel.

## Why It's Good For The Game

If a pirate pulls this off, they've got to be the best pirate I've ever seen.

## Changelog
:cl:
balance: Gives Space Pirates a bonus to hijack speed on the shuttle, and allows them to hijack.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
It should give the pirates a bonus in credits depending on how much the shuttle costs, hijack the battlecruiser for a big payday.

**Comment by MrMelbert** [comment]
pirates can't currently hijack so i'd note that you're giving them the ability to hijack in the first place

**Comment by Iamgoofball** [comment]
oh, I thought all antags could hijack

**Comment by MrMelbert** [comment]
The default hijack speed modifier is 0, if the modifier is 0, the antag can't hijack. So most antags can't hijack by default.

**Pull request merged**
