### PR TITLE
Establishes the patriarchy

### LINKED ISSUE #48389: Santa can be female
image

### PR DESCRIPTION
**Pull request by TiviPlus**
fixes #48389
##Changelog
:cl:
fix: Santa can no longer be female
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
not a bug, santa is a goatdemon and takes whatever form allures your more

**Comment by Shadowflame909** [comment]
Sorry TiviPlus. I showed optimumtact a comic they should not have seen

**Comment by Shadowflame909** [comment]
Sorry TiviPlus. I showed optimumtact a comic they should not have seen

**Comment by TiviPlus** [comment]
Oranges has killed sexism
long live oranges

**Pull request closed without merging**
