### PR TITLE
Singulo won't make rods out of lava, lava will keep burning extinguished stuff

### LINKED ISSUE #23074: A level 5+ singularity will rip metal rods from lava
BECAUSE IT'S ACTUALLY PLATING, HUEK

### LINKED ISSUE #23096: Lava doesn't reapply fire to things that are extinguished if they stay still
Using an extinguisher or having a water tank blow up and release water vapour will extinguish things on lava but it seems only humans reignite. They reignite when they move to another lava tile or if there is a burning human on the same tile as them.

### PR DESCRIPTION
**Pull request by XDTM**
Fixes #23074
Fixes #23096

### CODE REVIEW

**Comment by coiax** [comment]
Have you tested this

**Comment by XDTM** [comment]
Yup, no rods

**Comment by XDTM** [comment]
Bundled in a fix for #23096

**Comment by KorPhaeron** [comment]
Lava should probably be repathed from plating

**Pull request merged**
