### PR TITLE
(WIP) Moves several defines out of misc.dm into their own files

### PR DESCRIPTION
**Pull request by Mervill**
`code\__DEFINES\misc.md` is a little large, this is an attempt to make it smaller by promoting groups of 4 or more related defines to their own files. This makes some important things easier to find (resistances).

### CODE REVIEW

**Comment by Cyberboss** [comment]
We're gonna need defines subdirs soon if this keeps up :/

**Comment by ChangelingRain** [comment]
these can probably be compressed a bit into general files, like mob_defines.dm or something

**Comment by KorPhaeron** [comment]
Tell me when this is done and I'll reopen

**Comment by Mervill** [comment]
yeah sorry 😓 . For some reason organizing several hundred defines didn't keep my attention for long. I'll pick this up some time later.

**Pull request closed without merging**
