### PR TITLE
Paramedic access has been trimmed down to just Medical access, but they get an access key to buzz for broader access.

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request
Closes https://github.com/tgstation/tgstation/pull/84396 as it is an alternative PR.

Removes the broad general access of paramedics in favour of giving them an access key, like janitors have.

## Why It's Good For The Game

Paramedics have an obscene amount of access for a non-critical, non-security role. There are few other roles with the ability to simply walk into other departments like paramedics can. There is no other role but command roles that are able to simply enter _every_ department besides security at once from roundstart. This results in various.. problems.

Some of those problems include;
A) Being able to get access to other departmental gear without even asking anyone because they can simply walk in and take it.
B) Being able to walk into science and just start doing doing research without anyone in science having the power to bar them from getting at their console, they have access. (I swear this is the most annoying one to me personally because those rat fucks will always jump the queue to tools). 
C) Being able to walk into cargo and just start ordering shit and taking mining equipment because they also have access to that. I've had paramedics steal mining points from the boulder machines before, This is ridiculous.
D) They don't have to ask or acknowledge anyone in the departments they waltz into, because they don't answer to anyone but the CMO. The game gave them this access roundstart, and the other departments just have to put up with these dickheads coming in and taking things for medical/themselves. On a per round basis.

Paramedics are just Tider Plus, moreso than engineering, because at least there is a veneer of mischief when engineers come in and hack into your department. The game has given paramedics that access already. They don't have to even try, and you probably don't have a justifiable reason to kick them out most of the time since it isn't trespass if they are allowed in via their broad access.

Already mentioned in goofs PR, once they have various tools, they start becoming an even worse problem. They're able to turn what they have into just basically the strongest role in the game, period, for being able to do practically any kind of job or role they care to do at once. They're only meant to be saving people, but that isn't what their biggest strength is. It's running over other people occupying other roles to do things with nearly as much freedom as the captain with none of the responsibility or risk for their death. 

This also makes them exceptionally good at antagonism. They can enter into a lot of different departments, and since they're usually allowed in a whole host of places, they are also able to quickly enter a location, do bad shit, and get out in a way that normally wouldn't be possible for other roles. If you want to play heretic or do the side objectives for traitor, paramedic is the best option. You can go almost anywhere, and they have an excuse to be anywhere. 

This PR is not necessarily completely taking that away from them. It is instead trying to allow departments their ability to defend themselves from these bastards waltzing into their spaces and possibly shoving them out of the way to self serve.  If that means people die because paramedics are now slower to reach them, that is a reasonable price to pay for the health of the game and maintaining our departmental lines. Paramedics need to be leashed, even at the expense of rapid access to the injured.

## Changelog
:cl:
balance: Paramedics no longer have broad access to other departments.
balance: Paramedics have access keys, similar to a janitor.
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
so how does this access key work exactly? If it's just like the janitor key where a head of staff has to swipe it then that really sucks, and there should be some easier way of triggering it. If a head of staff has time to swipe that access thing then they have just as much time to just bring the body or let the paramedic in themself.

**Comment by necromanceranne** [comment]
https://github.com/tgstation/tgstation/pull/73768 Here is the PR that introduced the keyring.

**Review by Fikou — APPROVED** [review]
i like it i always wanted them to have it

**Comment by carlarctg** [comment]
Isn't the access key noticeably Jannie-themed? The janitor gets a keyring because it's the role closest to the concept of 'Groundskeeper', but Paramedics aren't known for having keyrings to random houses. It doesn't fit thematically.

**Comment by Zergspower** [comment]
This is a hilariously bad change trying solving a administrative issue, a paramedic isnt going to hunt down a head and wait while a corpse rots in a department they cant get into to give them ten minutes of access.

**Comment by necromanceranne** [comment]
> Nowhere in this PR is the content actually explained in detail. It's one ambiguous sentence and then five paragraphs of justification. (Apparently because the content changes are staggeringly small.)

It's not a very complicated change, even if the ramifications are pretty big for the actual role. It really is just two things. Reduced access, they get access keys to regain that access. Doesn't need much more than a sentence to explain.

> Isn't the access key noticeably Jannie-themed? The janitor gets a keyring because it's the role closest to the concept of 'Groundskeeper', but Paramedics aren't known for having keyrings to random houses. It doesn't fit thematically.

We call them 'paramedics' but really they're more like an on-site emergency medical staff. Those kinds of people in a large facility I feel would have keys for situations like this. There just isn't an elegant name for what they are.

> This swings the pendulum from Paramedics having AA to them having no access, which is better in some ways but still subpar as a solution. Presumably we do want them to be able to access departments in an emergency. Perhaps an utility that lets them temporarily EA a room if there's someone <50 HP with sensors in it?

I'm not going to do that myself, but I think a few suggestions got thrown around in coding discussion.

**Comment by necromanceranne** [comment]
> This is a hilariously bad change trying solving a administrative issue.

I'm an admin, this is not an administrative issue, this is purely a gameplay issue. If you mean to say 'why aren't we cracking down on paramedics entering other departments to take shit', its because we trust our coders to have given them this access for good reason, and we're not about to create further work for us to resolve a problem that my fellow admins will then say is a code issue. Because it is. If you can convince a headmin term to enforce stricter controls on paramedics even for our lower roleplay servers, then by all means give it a go. You're going to get nowhere fast, and I don't think it is the right approach.

> And wont this apply to all keyrings ??

We've already the potential for multiple access keys currently. Is it good that it updates all the keys globally? Probably not, but paramedics probably get less use out of it than janitors.

**Comment by JohnFulpWillard** [comment]
The keyring doesn’t fit thematically but it’s not really that big a deal, but I do have issue that they have no way to “buzz” for their broader access and any head giving keyring access will be giving to all of them. I think it would need some way for heads to be able to pick and choose which keyring is getting access, with some way to label one to the person (first thought is giving paramedics a PDA app that temporarily gives their ID access instead, but it doesn’t have to be).

**Comment by Zergspower** [comment]
> I'm an admin, this is not an administrative issue, this is purely a gameplay issue. If you mean to say 'why aren't we cracking down on paramedics entering other departments to take shit', its because we trust our coders to have given them this access for good reason, and we're not about to create further work for us to resolve a problem that my fellow admins will then say is a code issue. Because it is. By our rules, if you have access to a place, it isn't trespass.
> 
> If you can convince a headmin term to enforce stricter controls on paramedics even for our lower roleplay servers, then by all means give it a go. You're going to get nowhere fast, and I don't think it is the right approach.
> 
The solution presented however I dont see changing things at all, and would just encourage even more Jaws usage so they can actually save the guy in crit in science lobby or w/e. I havn't seen any of those issues present (downstream mind you) - But this really does cut their balls off on the actual paramedic aspect of their job

**Comment by Pickle-Coding** [comment]
Just ask the AI or department staff to open. Not that hard.

**Comment by MrMelbert** [comment]
I don't like the keyrind so I don't like this 

But in any case this is not intuitive as it stands, because if a head wants to give access to paramedics they have to 
`"Give Janitor Access"`

**Comment by necromanceranne** [comment]
You know, I could just take away the key and not deal with any of that, I think this PR works fine without it. But I know it'll be less popular, but god do I want to deal with this problem, but I also don't want to put in the effort of some kind of more complicated resolution to access keys.

**Comment by MrMelbert** [comment]
Ok but can you at the very least change the text in the card swipe from `Give Janitor Access` to `Give Keyring Access`

**Comment by necromanceranne** [comment]
That's entirely doable.

**Comment by Metekillot** [comment]
Regarding the science research thing, I have a beefy PR WIP for stricter access control on research on my fork I'm chipping at (research-server-expansion branch iirc), but paramedics being BlueTide gremlins needs to be addressed besides that

**Comment by Helg2** [comment]
Acess key generally sucks.

**Comment by necromanceranne** [comment]
> Regarding the science research thing, I have a beefy PR WIP for stricter access control on research on my fork I'm chipping at (server-controller-expansion branch), but paramedics being BlueTide gremlins needs to be addressed besides that

nice

**Comment by lessthnthree** [comment]
Instead of giving them a key ring, yet another thing to occupy a slot, why not make smacking the handheld crew monitor on an airlock function like the janitor key.

Fits better thematically too.

**Comment by MrMelbert** [comment]
> Instead of giving them a key ring, yet another thing to occupy a slot, why not make smacking the handheld crew monitor on an airlock function like the janitor key.
> 
> Fits better thematically too.

It would be doubly funny if it only gives you access to a department if it detects a member of that department is wounded

**Comment by lessthnthree** [comment]
> > Instead of giving them a key ring, yet another thing to occupy a slot, why not make smacking the handheld crew monitor on an airlock function like the janitor key.
> > Fits better thematically too.
> 
> It would be doubly funny if it only gives you access to a department if it detects a member of that department is wounded

Checking for that instead of having a head needing to activate the access ring is probably more useful anyways.

**Comment by wivernshy** [comment]
Why not just... limit access to the problem areas? A key ring defeats the purpose of paramedics entirely: to **quickly** and efficiently get to dead or dying people. This is neither of those. Don't get me wrong, I get that paramedics abusing their access is a huge problem and _does_ need a fix, but this doesn't feel like a good way to go about it considering how slow and clunky key rings are to use- much less get the department head to grant.

A better solution might be to limit access based on alert level, or at least make the keys faster and easier to use.  Automating it like LT3 and Melbert suggested is also a great idea.

**Comment by necromanceranne** [comment]
> > > Instead of giving them a key ring, yet another thing to occupy a slot, why not make smacking the handheld crew monitor on an airlock function like the janitor key.
> > > Fits better thematically too.
> > 
> > 
> > It would be doubly funny if it only gives you access to a department if it detects a member of that department is wounded
> 
> Checking for that instead of having a head needing to activate the access ring is probably more useful anyways.

Okay, but what limitations would need to be in place for that to not be effectively broader access to someone with a monitor? Do they have to be wounded by a certain percentage? What happens if someone is dead on sensors but isn't in a state that would be recoverable, just kept in the morgue, does that mean whoever has the monitor just gains access to the department? Do they then have to occupy the room you're accessing? They pop out of vendors, doesn't that just push the problem down to monitors as an access tool, the exact same problem that jaws of life may still be occupying but accessible from a much earlier point in the round?

**Comment by necromanceranne** [comment]
> Why not just... limit access to the problem areas? 

Our access levels are designed in such a way that there is not as much granularity as you would think. Mapping also plays a major part in this as well. Access to some department areas allow for more access to that departments equipment than others. Not every department has its lathes locked up in secure room. For access reasons, some of them are just in the middle of the department (cargo is almost always in the first immediate area of access).

If you're asking me to take out the problem areas, I already have. The problem areas just happen to be the whole goddamn department.

> A better solution might be to limit access based on alert level, or at least make the keys faster and easier to use. Automating it like LT3 and Melbert suggested is also a great idea.

What alert level, though? Blue is often auto-assigned at roundstart, so that pretty much means the PR has accomplished nothing. Red is a bit extreme just for individual instances of injury/death. 

Maybe a key that starts opening doors on a red alert is a more acceptable alternative...a little easier and more controllable. I'll probably look at that.

**Comment by DaydreamIQ** [comment]
I totally agree that paramedics are just assistant+ nowadays but I dunno if the jani key in its current state is the way to go. With janitors it's usually a non issue because since there's no rush heads can wander over to the button and give access for them to do whatever. Medical emergencies on the other hand seem kind of pointless for a head to move on over to the magic button that let's paramedics open the door after a long delay when let's be honest...they could drag the patient outside in that time. Perhaps making it something the AI can toggle and removing the time delay on using the keys could help? Or just go the paradise route where the keys work slowly but don't require a head to activate

**Comment by SomeRandomOwl** [comment]
> > Instead of giving them a key ring, yet another thing to occupy a slot, why not make smacking the handheld crew monitor on an airlock function like the janitor key.
> > Fits better thematically too.
> 
> It would be doubly funny if it only gives you access to a department if it detects a member of that department is wounded

I honestly think this is probally better, they only have access if there is a reason for them to. If someone on the monitor is injured they should have access to the department that person is in, though likely keep it to a threshold of like someone is hurt to near crit. Because god ive seen plenty of people walking around partially injured.

**Comment by NanoCats** [comment]
Any time one of them says "but I have access" I want to beat them to death immediately.

**Comment by EricZilla** [comment]
I'm pro this, honestly we do need some upgrades to the keyring code. We should have a keyfob app that lets you remotely activate keys via PDA for the heads, with captain allowed to do any

**Comment by lessthnthree** [comment]
I imagine any extra step it'd be (such as activating a button be it on the wall or PDA) that time will just instead be spent dragging the person out to the hallway or entirely to medbay. (If anyone notices them at all.)

**Comment by lessthnthree** [comment]
> > > Instead of giving them a key ring, yet another thing to occupy a slot, why not make smacking the handheld crew monitor on an airlock function like the janitor key.
> > > Fits better thematically too.
> > 
> > 
> > It would be doubly funny if it only gives you access to a department if it detects a member of that department is wounded
> 
> I honestly think this is probally better, they only have access if there is a reason for them to. If someone on the monitor is injured they should have access to the department that person is in, though likely keep it to a threshold of like someone is hurt to near crit. Because god ive seen plenty of people walking around partially injured.

Yeah when I said that I was thinking like, a check on the person's stat var, and if it's SOFT_CRIT or higher, allow the access.

Anything lower than that they could crawl to an airlock or something.

**Comment by Formerxboxgamer** [comment]
I think you’re on the right track for this, paramedic AA is a problem and it sucks. Do note though, that a situation wherein a paramedic is needed in a place is probably also a situation where the head of staff of the department cannot give them access. If there are people dead or being murdered, why would a head of staff step away to their office to give access? Alternatively if the station is totally borked and people are dead everywhere, who is going to buzz the paramed in?

I like making parameds less tider+, my suggestion would be to tie paramed access to alert level. Downstreams do similar stuff and it works well.

**Comment by DingleFlop** [comment]
> I think you’re on the right track for this, paramedic AA is a problem and it sucks. Do note though, that a situation wherein a paramedic is needed in a place is probably also a situation where the head of staff of the department cannot give them access. If there are people dead or being murdered, why would a head of staff step away to their office to give access? Alternatively if the station is totally borked and people are dead everywhere, who is going to buzz the paramed in?
> 
> I like making parameds less tider+, my suggestion would be to tie paramed access to alert level. Downstreams do similar stuff and it works well.

I personally REALLY like this idea! Alert-tied access means that people like the AI or heads can also help. If there's a medical emergency, the whole station can enter an emergency state to address it!

**Comment by Majorkite** [comment]
I can see parameds tiding being a problem. This is a poor solution as it doesn't actually address the problem. There is just now an extra step for the tider of faking a dead body being in the location. It instead hurts actual parameds trying to do their jobs at the time when they are most needed aka when the heads are being murdered, when the station is being blown up, when bodies are being hidden.

Moreover, everyone is pretending like the parameds real job isn't dead body recovery. Longer recovery times will translate to higher incidence of needing to do extra surgeries to revive someone due to organ rot, third degree burns, husking, etc. I dont think it'd be much, but enough to warrant thinking about before taking action.

The access based on alert level solution is cool and flavorful, but also flawed in that most of the time red alert is used for a reduced shuttle call timer rather than any of its other uses. Thus its used very sparingly. Blue alert is activated automatically nearly every shift so no real difference would occur. I don't think it'd be effective.

The best solution IMO is to introduce login screens to the science console and other problem computers so that randos cant waste valuable resources just because they got in the door. The med records console and security consoles already have this. 

Adding an additional access type for secure equipment area would also work for the locations that need to keep people out of advanced tools or suits or what have you. I know you said it won't solve that for all maps but it will solve it for most of them. Science lathe would be the biggest problem child, frankly I think them having access to the cargo lathe for stuff to go down and recover the miners is a good thing. 

To be honest, this is a shortsighted solution that would have a lot more negative impacts on the game than are first apparent. I don't think it should be implemented simply because of bad behavior on the part of a non majority. Getting people back into the game is a core part of the loop and messing with how that loop works should be handled with more care than is shown here.

**Comment by necromanceranne** [comment]
You know, this prs gonna have to get some changes so it might be a little unnecessary for it to remain open until those happen. I'll close it for now and just get back to it with a fresher approach and a bit of research on something someone suggested.

I'm telling you now that I'm probably not taking any routes that involve mapping solutions.

**Comment by axelzonvolt** [comment]
perhaps just simply add a new button to the command console to toggle emergency paramedic acccess. one that all the heads of staff (+silicons) can enable/disable as needed?

**Comment by necromanceranne** [comment]
Just also letting folk know that having consulted with mappers, it is probably _not_ reasonable to resolve it via mapping solutions. It would have to be from code solutions.

**Comment by Gmet1234** [comment]
Idea guy moment, maybe activating the medical emergency button on those request consoles (I think) could bring department access to the paramedics?

**Comment by billiumbillious** [comment]
i like some of the comments that say giving them automatic access to departments with a very injured person in it would be good.
They could also still tide much quicker than others if they're an antagonist by only getting through one door and chucking a corpse in, so it's not too bad of a nerf for them when they're a traitor.  Would most certainly be interesting imo

**Pull request closed without merging**
