### PR TITLE
Fixes misplaced area in Boxstation

### PR DESCRIPTION
**Pull request by Bawhoppen**
phew thank god we caught that

### CODE REVIEW

**Comment by lzimann** [comment]
Please specific, at least in the title, what is your pr exactly.

**Comment by Bawhoppen** [comment]
it changes a misplace area
I don't know what is going on with the semicolons but its probably fine

**Comment by coiax** [comment]
@Bawhoppen you realise with that PR title, I assumed it was memes.

**Comment by xxalpha** [comment]
Yeah, do describe map edits, TGM only makes the changes slightly more readable.

**Pull request merged**
