### PR TITLE
Buffs Bulldog shotgun stun time

### PR DESCRIPTION
**Pull request by ghost**
After seeing a few nuke op teams fail because of this (and being part of one of them), I feel that the Bulldog is almost useless now. It takes two shots to down someone, and they almost immediately pop right back up because of the high stamina recovery rate. Generally this makes it fail in combat unless your target is ill-prepared, and it's completely useless against crowds.

This PR attempts to fix that. Instead of taking two shots, stun rounds now take one hit to knock down the target and also do additional stamina damage. Because of the high stamina recovery rate, the stun generally doesn't last long in the first place. By making it a single-shot stun, the Bulldog assumes its original usability and makes it friendlier to stealth ops.

### CODE REVIEW

**Comment by paprka** [comment]
Close this PR, I'm working on rebalancing the bulldog.

**Comment by Xhuis** [comment]
What do you intend?

**Comment by paprka** [comment]
Basically exactly this, like it was before, one hit stun and no more burst. Burst fire fucks up dragon's breath and makes them runtime as well, actually, so I don't really have a choice there. It's basically exactly this though, but they'll be shooting a different projectile so it would conflict with this a lot.

**Comment by Xhuis** [comment]
Sounds good.

**Pull request closed without merging**
