### PR TITLE
Removes Classified Report from Blob gamemode

### PR DESCRIPTION
**Pull request by Shadowlight213**
Also removes a pointless unused var.

Keeping the actual report code in, so in the future if we add reports to other gamemodes, it can be re-added.
People immediately scream BLOB from the report. It's useless keeping it a secret if its the only roundtype the report is in.

### CODE REVIEW

**Comment by Lumipharon** [comment]
:+1:

**Comment by Bawhoppen** [comment]
:-1: It helps balance it out by giving humans a headstart, usually blob is better than the incompetent crew

**Comment by Shadowlight213** [comment]
@Bawhoppen people metagame the shit out of it due to it being the only classified report made by the game. I can change it so the confirmed outbreak timer happens at the same time the classified report would happen.

**Comment by Bawhoppen** [comment]
Do that and I'm happy.

**Comment by optimumtact** [comment]
The original blob creator specifically intended for these to be used to metagame that it was blob, so crew would know.

**Comment by Bawhoppen** [comment]
Yea I mean, it doesn't matter what the announcement is, just if there is one.

**Comment by Shadowlight213** [comment]
A side effect is that this would make the round time before nuke codes are sent be slightly less, but if the round takes that long, it doesn't matter

**Comment by MrPerson** [comment]
You should probably leave a comment on the send_intercept() proc itself that it's unused. Or better yet, remove it outright. It's stored in the git history so if we need it, it's still available.

**Comment by Shadowlight213** [comment]
@MrPerson Send intercept is also used to send the nuke codes

**Comment by MrPerson** [comment]
I meant the blob version

**Comment by KorPhaeron** [comment]
>someone adds something in as an IC way to convey OOC information
>years later people consider it "meta" instead of intentional

Never stops being funny

**Comment by RemieRichards** [comment]
@KorPhaeron this gamemode sends 2 scripts, and only this gamemode.
Of course people will figure that out AND abuse it.

**Comment by optimumtact** [comment]
it was intentional

**Comment by KorPhaeron** [comment]
That's my point @RemieRichards 

It isn't abuse, it's a "HEY THIS IS BLOB MODE" alert given in an IC manner.

**Comment by Lumipharon** [comment]
That's what the level 5 alert is for.

There is zero reason to have 2 reports that do the exact same thing, only with a pointless delay.

**Comment by Steelpoint** [comment]
What oranges said, the creator of this game mode fully intended for the classified report to be interpreted as a blob on station.

If we're going to remove this report, take the second report and have it be announced first at the time the first report would.

Then the balance is maintained, instead of giving the Blob a lot more time to fortify itself, more time than it would ever get.

**Comment by Xhuis** [comment]
I agree with the classified report's removal, but please keep the level 5 alert. Still, I'll miss admins making a classified announcement a couple minutes into a traitor round or something that says "you're a nerd".

**Comment by Nanotransistor** [comment]
:+1: :+1:

**Comment by Shadowlight213** [comment]
@Steelpoint that's exactly what I DID do. The level 5 biohazard alert now comes at the time it would take for the classified report to appear. The way this is done, the blob doesn't get any extra time before being announced. The only thing different in timing is the nuke codes will end up being sent slightly earlier.

@xhuis the level 5 biohazard alert is still there though.

@MrPerson the send_intercept () proc takes an argument which tells it whether to send the classified report or the nuke codes. I wanted to leave the proc itself intact so it was easy to re-integrate once another gamemode had its own report. I'll leave a comment on it but if you really think that part should be removed, I can do that.

**Comment by Fox-McCloud** [comment]
Might want to bump up the level 5 announcement so it occurs sooner then.

**Comment by Bawhoppen** [comment]
@Fox-McCloud The whole point is hes replacing the snowflake classified report with the level 5 announcement.

**Comment by Shadowlight213** [comment]
THE LEVEL 5 BIOHAZARD ANNOUNCMENT NOW OCCURS WHEN THE CLASSIFIED REPORT WOULD OCCUR BEFORE THE CHANGE. BLOB DOES NOT GET ANY EXTRA TIME BEFORE BEING ANNOUNCED.

**Comment by Shapsy** [comment]
This would only be balanced if you moved up the level five biohazard message

**Comment by Shadowlight213** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by optimumtact** [comment]
say it again capn, say it again

**Comment by CPTANT** [comment]
I think this would only be balanced if the current level five biohazard message moved up to be a level six biohazard message.

**Comment by Bawhoppen** [comment]
@CPTANT holy shit thats heresy

**Comment by Anonus** [comment]
Also it's not fucking possible because we don't have a soundfile for level 6, only level 5 and 7

**Comment by Shadowlight213** [comment]
@MrPerson I commented out more parts of the report. Is this better?

**Comment by MrPerson** [comment]
Yeah sure, I guess

**Comment by Shadowlight213** [comment]
@MrPerson @Razharas This is ready to be merged.

**Comment by optimumtact** [comment]
Might want to bump up the level 5 announcement so it occurs sooner then.

**Comment by Bawhoppen** [comment]
Isn't that literally the ENTIRE point of this

**Comment by optimumtact** [comment]
I just want to make sure the level 5 announcement is bumped so it occurs sooner

**Comment by Bawhoppen** [comment]
>THE LEVEL 5 BIOHAZARD ANNOUNCMENT NOW OCCURS WHEN THE CLASSIFIED REPORT WOULD OCCUR BEFORE THE CHANGE. BLOB DOES NOT GET ANY EXTRA TIME BEFORE BEING ANNOUNCED.

**Comment by optimumtact** [comment]
I just want to make sure that it occurs when the classified report does as that was an intentional announcement by the original developer.

**Comment by Shadowlight213** [comment]
Please no bully.

**Comment by MrStonedOne** [comment]
What? No! ok, i can see it, but can you at least make it so the level 5 announcement goes off at the time the classified report used to.

:^)

**Comment by tuypo1** [comment]
dident it used to not announce that the report had been printed

**Pull request merged**
