### PR TITLE
Drone Walking Sprites

### PR DESCRIPTION
**Pull request by Steelpoint**
:cl: 
tweak: All Drones now have a walking animation.
/:cl:

This PR adds walking animations to all the Drones that did not have any walking animations, them being.

* Base Maintenance Drone and all colour variations
* Syndicate Drone
* Hacked Scout Drone

Here's a gif of a grey Maintenance Drone. It looks better in motion.

animationdrone

Thanks for reading.

### CODE REVIEW

**Comment by Haevacht** [comment]
It's not a sec buff so 👍

**Comment by Steelpoint** [comment]
I was planning to hold off on this till after my other PR, since I prefer to go in one PR at a time. But since my other PR is stalling I decided to put this up.

**Comment by Emilc4h** [comment]
What about Cogscarabs? Too different? Or do they already have a walking animation? I'm normally too busy screeching and trying to smash them to notice.

**Comment by Steelpoint** [comment]
Cogscarabs already have walking animations.

The only Drone I missed, on inspection, is the Supermatter Drone. However that was due to a merge conflict and I missed copying that file over. I'll add that one in when I get a chance.

**Comment by WJohn** [comment]
The default drones have such awful sprites, I much prefer the other two options, but whatever.

**Comment by Steelpoint** [comment]
It really stood out to me, most people do go as the Repair or Scout Drone, but then seeing a Maintenance Drone running along looked odd since it would be the only one without a walking animation.

**Comment by WJohn** [comment]
Uh, barring a one pixel error on the south facing sprite, the sprite IS mirrored by all accounts.

And OF COURSE I'm going to notice this, I sprite, I pick up on this stuff much better than most people who play this game. Just mirror the legs.

**Comment by Steelpoint** [comment]
Updated the sprite issue.

New animation in the OP as a example.

**Comment by PKPenguin321** [comment]
Was just thinking about this yesterday :+1:

**Comment by coiax** [comment]
I really do need to finish wizard and supermatter drones.

**Pull request merged**
