### PR TITLE
Removes the old player panel verb that is no longer used

### PR DESCRIPTION
**Pull request by lzimann**
The list of mobs is already done in a better way by the javascript player panel. Also removed a commented proc there.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
?
Does this remove opening the player panel by right clicking a mob? I use that all the time

**Comment by MrStonedOne** [comment]
ya, this verb is what triggers the right click @lzimann, removing it removes that right click option.

**Comment by MrStonedOne** [comment]
you could set its category to null to disable it showing up in the verb list

**Comment by lzimann** [comment]
Meh, I forgot about right clicking. I will change the category later.

**Comment by lzimann** [comment]
Byond is dumb with verbs, with no category it creates a new tab called "commands", and if I set it hidden, it changes the order of the right click menu, so I guess whatever on this for now.

**Comment by MrStonedOne** [comment]
lzimann, listen to what i say god damn it

I said NULL category, not no category

**Comment by MrStonedOne** [comment]
category defaults to `""` not `null` if not specified.

**Comment by Cyberboss** [comment]
`category = "Tickets"` :honk:

**Comment by MrStonedOne** [comment]
http://www.byond.com/docs/ref/info.html#/verb/set/category

**Comment by lzimann** [comment]
Category as null changes the verb order on right click.

**Comment by Cyberboss** [comment]
Who cares tho?

**Comment by MrStonedOne** [comment]
oh poor naive cyberboss

admining is 80% muscle memory, admins bitch in asay every time a new verb is added that shifts the location of verbs around, but at least then its just a shift and still findable.

a flat out jump would just break their wittle brains

**Comment by PKPenguin321** [comment]
It's true

**Pull request closed without merging**
