### PR TITLE
Adds cross server adminhelp relaying

### PR DESCRIPTION
**Pull request by Shadowlight213**
Adds basic cross server message relay system. Currently setup to relay adminhelps to the other server in the case of no admins on a server.

Hopefully the system can be expanded to relay other kinds of messages.
Since the comms key is sent along with the message, the destination has to be unable to be changed in order to keep the key secret.

### CODE REVIEW

**Comment by optimumtact** [comment]
Because you can't manage to keep all the admins in the irc?

**Comment by Bawhoppen** [comment]
I have ahelped legit times before when no admins were on an no mins ever came from the IRC, also I have to like spam the supportbus to even get a min from there

**Comment by optimumtact** [comment]
I'm sure this will have such a huge affect on the status quo /sarcasm

**Comment by Shadowlight213** [comment]
Not everyone has multiple monitors and sees every ahelp that pops up in adminbus. Relating it to the other server increases their visibility and improves the likelihood of response.

**Comment by Dorsisdwarf** [comment]
I can't tell from the code what this actually looks like to an admin. Presumably there's something telling them it's not from their server and it looks visually distinct?

**Comment by peoplearestrange** [comment]
The issue with this is that if the server you're in is busy and (for the sake of example) you are the only one on, then you'll be spammed by messages you can't simply ignore like with IRC. This is not necessary a good thing if there is no way you can leave the current server (i.e. if your dealing with an ahelp/incident already or the server is currently extremely busy).

A toggle of this might be advisable if we REALLY need this.

Also does this look like a standard ahelp? Can we reply without switching servers? what kind of integration are we talking here?

**Comment by Shadowlight213** [comment]
Replying isn't supported yet. I'm hoping to add that eventually
The messages should look super similar to the IRC relayed messages. I did a small manually inputted test to show what the message would look like. No bwoink sound. it will show up, but it wont easily be mistaken for a regular ahelp.
test

**Comment by peoplearestrange** [comment]
That seems pretty reasonable, I assume the "ADMIN LOG" doesnt show up in the normal chat window right?

**Comment by Shadowlight213** [comment]
It actually does, because I'm using the message_admins proc. If needed, I can try making a proc to have it say "ADMIN RELAY:" or something.

**Pull request merged**
