### PR TITLE
Adds Advanced Stock Parts crate to cargo

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Cargo can now order an Advanced Stock Parts crate, which contains upgraded versions of normal machine components.
/:cl:

This contains the parts that R&D can normally research and make without any assistance, so this crate should be bought if R&D is unable or unwilling to simply produce them.
Should i add a RPED to the crate?

### CODE REVIEW

**Comment by Shapsy** [comment]
But then why would science research parts they already have widely available schematics for?

**Comment by XDTM** [comment]
We're talking about a company that has ERT/Deathsquad technology and doesn't share it with the stations.
Although now i kinda want to code research-locked crates.

**Comment by LaharlMontogmmery** [comment]
I'm actually OK with this.

Potentially, this allows cargo to create a new RnD lab if things in RnD went belly up (for example, bleb eating the lab.)

**Comment by Bawhoppen** [comment]
I don't like it, sounds pretty powercreepy

@LaharlMontogmmery they can already make basic machine parts from the autolathe

**Comment by Jalleo** [comment]
@XDTM redo this as research locked crates.

**Comment by XDTM** [comment]
Can do, i guess, but it's supposed to be used for those rounds where nobody is doing RnD, and requiring science access makes it pointless

**Comment by Hatfish** [comment]
It takes less than 3 minutes to get these parts in R&D with stuff from the protolathe, this doesn't exactly seem like powercreep to me.

**Comment by Jordie0608** [comment]
I don't think this is a good idea, ruins the point of having these as researchable.

**Comment by Cheridan** [comment]
What Jordie said. If these are getting added they have to be locked. Otherwise it's just going to be cargo making their own R&D to print guns with.

**Comment by PKPenguin321** [comment]
You can already make a ghetto R&D lab, iirc you just need to hack into tech storage and get the boards, then decon the maint sleeper and heater/freezer for parts

**Comment by ExcessiveUseOfCobblestone** [comment]
the autolathe can produce T1 parts, so you can easily setup your own CaRNDgo if you hack tech storage [which also nabs you free igloves usually]

**Comment by optimumtact** [comment]
As others have mentioned this simply replaces one jobs content without any difficulty in acquiring it when other more difficult but interesting methods exist.

**Pull request closed without merging**
