### PR TITLE
Fix 'Medical Delivery' windoor in Pubby

### LINKED ISSUE #39713: Pubby morgue windoor - wrong access
`req_access_txt` currently set to Kitchen. Should be `6` for Morgue.

````
/obj/machinery/door/window/southleft{
        base_state = "left";
        dir = 4;
        icon_state = "left";
        name = "Medbay Delivery";
        req_access_txt = "28"
        },
````

### PR DESCRIPTION
**Pull request by octareenroon91**
MULE delivery windoor in the morgue had kitchen access. Changed it to morgue.

Fixes  #39713

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Does it need its name updated as well?

**Comment by octareenroon91** [comment]
>Does it need its name updated as well?

Good question! The name is fine. It's located in the Morgue but it serves medbay's delivery needs.

>`area/crew_quarters/bar`

FUCK

**Comment by 81Denton** [comment]
I‘m surprised there aren‘t more of these considering that mappers need to set access and name manually

**Comment by octareenroon91** [comment]
This error came from copy-and-paste of a kitchen delivery/windoor tile.

Might be good motivation for adding or applying mapper-friendly types of windoor.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
