### PR TITLE
Fix ebow acceting pka modkits

### LINKED ISSUE #61840: PKA chasis modkits can be used to disguise ebow sprites and names
Reporting client version: 514.1557

## Round ID:
170576
If you discovered this issue from playing tgstation hosted servers:

## Testmerges:
- [tgui: Flex basis should be zero if grow is used](https://www.github.com/tgstation/tgstation/pull/61499)
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [Adds a second Detective slot.](https://www.github.com/tgstation/tgstation/pull/61400)
- [species changes part 1: lizards](https://www.github.com/tgstation/tgstation/pull/61440)
- [Buffs eye contact, adds "Shifty Eyes" quirk](https://www.github.com/tgstation/tgstation/pull/61711)
- [Fix old photos being lost(?)](https://www.github.com/tgstation/tgstation/pull/61835)

## Reproduction:
Acquire energy crossbow - either the mini syndie crossbow or the big illegal tech bow
Acquire either of the Proto-Kinetic-Accelerator chasis modkits
Apply modkit to crossbow
Your energy crossbow's inventory sprite and name is now that of a kinetic accelerator - you'll need to hold it in hand, fire it or examine it to determine that it is in fact still an energy crossbow.
Leave ebow in bag / suit storage because anyone searching you needs to specifically check it to realise it's not a PKA
In the case of security illegal tech big energy crossbows, it will also disguise the firing text, anyone who's watching will see you fire an ebow, but the chat window text will display you fired a kinetic accelerator. (Initial checks indicate that this does NOT confuse admin logging, yey)

Things the modkit does not effect
Ebow inhand sprite remains the same
Ebow projectile remains the same
Ebow sound remains the same
Ebow item size remains the same - PKA sprites look weird in pockets
Appears to only disguise itemsprite and object name, though anything drawn from object name (chat window log of weapon name, examine text) are also effected

### PR DESCRIPTION
**Pull request by kopoba**
## About The Pull Request
This pull request make ebow think that he has -1% of mod capacity because ebow is not pka but still pka. So you will be unable to slap modkits from pka to ebow. Its not best way to deal with issue but best i can afford. 

## Why It's Good For The Game
"Fix" bug
fixes https://github.com/tgstation/tgstation/issues/61840

## Changelog

:cl:
fix: fix ebow was able to accept pka modkits with 0 cost
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
I believe that, since they have 0% upgrade space, being able to disguise an ebow as a chassis PKA is a feature. this is because it does NOT change the inhand sprite, size, or description, so they are still easily discoverable, while giving them slightly more stealth during a surprise search or from afar.

**Comment by Fikou** [comment]
> I believe that, since they have 0% upgrade space, being able to disguise an ebow as a chassis PKA is a feature. this is because it does NOT change the inhand sprite, size, or description, so they are still easily discoverable, while giving them slightly more stealth during a surprise search or from afar.

stfu

**Comment by TheBonded** [comment]
> > I believe that, since they have 0% upgrade space, being able to disguise an ebow as a chassis PKA is a feature. this is because it does NOT change the inhand sprite, size, or description, so they are still easily discoverable, while giving them slightly more stealth during a surprise search or from afar.
> 
> stfu

I will never recover from this

**Comment by Watermelon914** [comment]
Personally, I don't like this solution but ebows are pretty hacky to have to use KA code.

**Pull request merged**
