### PR TITLE
(DRAFT FOR INPUT) Server controller expansion for research 

### PR DESCRIPTION
**Pull request by Metekillot**
### I intend to close this pull request and open a totally different one when I finish this so I axed the formatting.

Right now I'm reworking and expanding the research server controller and how research access works for the techweb.

My final goals, which I'll likely split into two PRs:

### PR ONE

1) All research interfaces report, which currently includes PDAs and the computer consoles. Right now only computer consoles report.
2) unless emagged or you have research access, you can't just walk in and start researching.
3) locked consoles require the highest access of the person who locked them. The hierarchy is as follows: Captain -> RD -> Research access 
4) groundwork for users being an entry in a similar manner as consoles, but working off IDs instead of mob objects
5) groundwork for better logging 

### PR TWO

1) Individual users can be locked out of using any research console by people with access to using the server controller (Captain, RD, those with emag capabilities)
2) individual nodes can be banned from being researched at the controller
3) nodes can be marked as prioritized, preventing research for anything but them and their prereqs
4) much more robust logging of console use and metrics, both in game and round by round 

Take a look at what I have so far and comment. Thanks! (This will not pass unit tests so ignore the fails)

american-psycho-what-do-you-think

### CODE REVIEW

**Comment by Sadboysuss** [comment]
I like it

**Comment by MrMelbert** [comment]
As a reminder, PRs are generally only supposed to be open when they're in a testmergable state, if you're just looking for feedback we have a few avenues (forums, dev projects, coding general, etc)

**Comment by Deadgebert** [comment]
logging is good, but i dislike locking research behind science access in general.
there are rounds where you could be completely locked out of doing a gimmick or having a necessary tool for your department because there are no active scientists, the acting cap traitor locks everything down, or they're instantly prioritizing some crazy research that's super deep into the tech tree.
there are no other methods available to get most of these items. it's adding a dependency on science that's similar to the station's dependency on the supermatter.

**Comment by Metekillot** [comment]
> As a reminder, PRs are generally only supposed to be open when they're in a testmergable state, if you're just looking for feedback we have a few avenues (forums, dev projects, coding general, etc)

I had bad luck with forums but I'll remember this in the future; thanks

**Comment by Metekillot** [comment]
> logging is good, but i dislike locking research behind science access in general.
> there are rounds where you could be completely locked out of doing a gimmick or having a necessary tool for your department because there are no active scientists, the acting cap traitor locks everything down, or they're instantly prioritizing some crazy research that's super deep into the tech tree that has no value to anyone except the single scientist who set it.
> there are no other methods available to get most of these items. it's adding a dependency on science that's similar to the station's dependency on the supermatter.
> 

Server controller access is restricted to RD, Cap, and AI. I'll be closing the PR pursuant to Melbert's advice to take the discussion somewhere appropriate

**Pull request closed without merging**
