### PR TITLE
Pun Pun is now playable as a station job trait.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request

This PR adds a station trait that makes Pun Pun playable, giving 'em the assistant assignment, and the clever mutation, which enables using advanced tool and reading. They're also prevented from being humanized, much like syndicate monkeys, and they also cannot speak Galactic Common, if you didn't know that already. Should they roll traitor, they're be able to buy syndicate monkey reinforcements and equipment, which they can also use, being a monkey themselves.

This is overall plan B when I started to realize making Ian playable in a good way was several folds more difficult and tiresome than I had anticipated.

Tested, it works smoothly.

## Why It's Good For The Game

I find the idea of a monkey job role somewhat unique, like, but not quite as much as, the Cargorilla. I don't think it hurts to deprive one or two rounds of the Pun Pun AI, like it doesn't hurt to deprive the cargo department of their sloth Citrus. Monkeys have some interesting traits, aside being unable to use machineries and read, which is something the role takes care of, otherwise Pun Pun would struggle to interact with many objects like a crewmember would. Overall, I think putting a player in the shoes (or perhaps the lack of thereof) of Pun Pun with a given role attached that ties them to the service department, not every shift but rarely, would make an enjoyable, if not fringe, addition to the game.

## Changelog

:cl:
add: A new station job trait, which allows you to play as Pun Pun.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Like Ian's adventure I'm a little reticent about this one; I simply think these things are more charming when they're _not_ AI controlled. I don't think that the way players are likely to RP as pun-pun the bar monkey (aka: mostly as if theyre playing as a mute human) are significantly less interesting than the mob is when it's under AI control and so I'd likely find any time this trait rolled to be a downgrade rather than an exciting addition to the game.

**Comment by Ghommie** [comment]
What are you on about? Pun Pun is entirely player-controlled here. The ai controller is automatically turned off when there's a client or mind datum.

**Comment by carlarctg** [comment]
Jacquerel means that he finds the concept of Pun Pun more interesting when it's not a player character, and this takes the charm out of him. I don't mind as station traits are rare.

What if it's his brother instead? Bun Bun.

**Comment by Jacquerel** [comment]
I put an extra "not" in that sentence by mistake which made it say the opposite of what I meant because im stupid

**Comment by carlarctg** [comment]
Does this handle the revenge of pun pun trait? It doesn't look like it. Would be funny if it made him murderous.

**Comment by Ghommie** [comment]
> I put an extra "not" in that sentence by mistake which made it say the opposite of what I meant because im stupid

Oh, fair then. But yeah, this is a station trait with minimum weight, so it shouldn't make the AI-controlled Pun Pun of every other round perceptibly less relevant.

**Comment by Ghommie** [comment]
> Does this handle the revenge of pun pun trait? It doesn't look like it. Would be funny if it made him murderous.

Well, I've left it as is. Unless nobody wants to join as Pun Pun roundstart, it'll works just peachy, only without the angry monkey ai controller. I'd also not want player-controlled Pun Pun to start attacking people in a frenzy. But I've had this fleeting thought of making 'Revenge of Pun Pun' give them a modest buff to their physiology datum, perhaps in a different PR.

**Comment by zxaber** [comment]
Why does it make Pun Pun an assistant, rather than bartender?

**Comment by Ghommie** [comment]
> Why does it make Pun Pun an assistant, rather than bartender?

Found it a bit more ironic to equate Pun Pun's intelligence to that of an assistant in the report and then follow up by making them one, but if people would rather see them working as a bartender, I'm good with that, as it kinda gives the monkey a purpose beside asshattery as an assistant.

**Comment by Ghommie** [comment]
Updated the job so Pun Pun is now a busser (waiter) instead of an assistant, meaning their job would be theorically catering and now just fuckall. They've also been given a mockery of the bartender's shotgun with a punny name, the 'Busser's Shot': single-shot, underpowered, with slight recoil and spread, though it fits backpack.

**Comment by LemonInTheDark** [comment]
I agree with jacq, there's a distinct charm to punpun being a fucking idiot for no reason and I like that, making it player controlled at roundstart doesn't really seem to add anything that something like sudden sentience doesn't already.

That said you're stuffing it with more and more soul as things go on here. Is this just like a "it would be cool"? I'm having a hard time justifying it to myself

**Comment by Terra1** [comment]
> Like Ian's adventure I'm a little reticent about this one; I simply think these things are more charming when they're _not_ player controlled. I don't think that the way players are likely to RP as pun-pun the bar monkey (aka: mostly as if theyre playing as a mute human) are significantly less interesting than the mob is when it's under AI control and so I'd likely find any time this trait rolled to be a downgrade rather than an exciting addition to the game.
> 
> Pun-pun being able to become a traitor is kind of funny though, almost makes it a shame that it is announced on the lobby screen that Pun-pun will be controlled by a player instead of it being a surprise.

Pun-Pun is the Chef's livestock in 9/10 rounds.

**Comment by Jacquerel** [comment]
Sorry man we left it a while but it doesn't look like anyone else is interested in arguing with me or potato

**Pull request closed without merging**
