### PR TITLE
Pulling icon en-speedening

### PR DESCRIPTION
**Pull request by MrPerson**
Made the little pulling icon on the bottom right corner of your screen update right away when you start or stop pulling instead of updating as part of life(). Or Move().

### CODE REVIEW

**Comment by xxalpha** [comment]
:speedboat:

**Comment by WJohn** [comment]
<3

**Comment by Fox-McCloud** [comment]
Finally! Yay.

Thanks for this.

**Comment by Miauw62** [comment]
literally change of the year

**Comment by WJohn** [comment]
More responsiveness! More responsiveness!

**Comment by phil235** [comment]
Works fine, except the pulling button icon disappears if you disconnect and reconnect while pulling a mob. You're still pulling the mob but the button is not there. This is a fairly minor bug though.

**Comment by PKPenguin321** [comment]
there's always the stop pulling verb, and that's kind of an obscure bug in the first place
more responsiveness like this is definitely worth a small bug. :+1:

**Comment by RandomMarine** [comment]
Does it reappear if you try pulling the same object or something else, Phil?

**Comment by phil235** [comment]
It doesn't reappear if you try pulling the same object again, but it does if it's another object.

**Comment by Cheridan** [comment]
More responsive, more optimized, less code. Basically a perfect PR.

**Comment by optimumtact** [comment]
Maybe add a login check for client in the pulling state.

**Pull request merged**
