### PR TITLE
Fix for robotic chest removing lungs

### LINKED ISSUE #15813: Augmenting someone's chest removes their lungs
### What is the problem?
Augmenting someone's chest removes their lungs, which means they can't breathe or speak, with no way for them to breathe
### Why is it a problem, or what should have happened?
Having a robo chest should simulate having lungs like it does for a heart, since they're kinda important
### How can the problem be reproduced?
Augment someone's chest

### PR DESCRIPTION
**Pull request by Core0verload**
Fixes #15813.

### CODE REVIEW

**Comment by phil235** [comment]
THe robotic chest is supposed to remove your heart afaik.

**Comment by Core0verload** [comment]
Supposed to, yes, but removing heart has no actual gameplay effect besides being non-defibable. 

Maybe i'll change that to replacing the heart/lungs with the robotic versions some day. But my sprites for robotic organs are still in #15707, and #15707 is stuck in merge hell.

**Comment by Supermichael777** [comment]
that pr is no where near merge hell. Merge hell is sitting a month before a conflicting pr is created and merged in less than 3 days

**Comment by phil235** [comment]
What about heart attack? Can you have one without a heart organ?

**Comment by Core0verload** [comment]
Yes.

**Pull request merged**
