### PR TITLE
Nuke the syndicate base

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
rscadd: The game will now recognize a successful detonation of the nuclear bomb in the syndicate base.
/:cl:

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Darwin award here I come.

**Comment by A-t48** [comment]
Wait, I thought server rules banned going to the Syndicate ship for shenanigans??

**Comment by jughu** [comment]
@A-t48 i mean if you somehow got the nuke code or the nuke is unanchored and you got a agent idd you fucking deserve it

**Comment by KingPhilipIII** [comment]
Well. If you're a xenoling and you absorb an agent after hitting them with a morphine syringe I guess you have everything you need, including an IC excuse to search for the shuttle(Since you just took all their memories.)

**Pull request merged**
