### PR TITLE
Unwrenching activated pumps,filters,mixers will automatically turn them off

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Unwrenching activated pumps,filters,mixers will automatically turn them off before unfastening them

## Why It's Good For The Game

MAKES life a bit easier for anyone changing atmos or sm setups roundstart
## Changelog

:cl:
qol: Wrenching activated pumps, mixers and filters will automatically turn them off before unfastening them
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Maybe this could be on rightclick since I believe its purpose is to stop people from accidentally screwing something up by unwrenching the wrong pipe

**Comment by Ghilker** [comment]
Yeah no, this should be on rclick at least.

**Comment by LemonInTheDark** [comment]
If you're going to do this you should make unwrenching active machinery dump their gas contents, with similar logic to pipes.
IDK how I feel about it being on right click, seems a bit too niche at first glance. Wonder if it wouldn't be better to just pick a path and stick to it.

**Comment by SmoSmoSmoSmok** [comment]
> Yeah no, this should be on rclick at least.

The point is to make removing active pumps and other pipe machinery only require 1 click rather than 2 clicks + ctrl making it no different than removing  a normal pipe, IS the right click that necessary

**Comment by Colovorat** [comment]
> > Yeah no, this should be on rclick at least.
> 
> The point is to make removing active pumps and other pipe machinery only require 1 click rather than 2 clicks + ctrl making it no different than removing a normal pipe, IS the right click that necessary

Yes, it can prevent sudden retardation of wrenching the wrong pipe

**Comment by Pickle-Coding** [comment]
There's like a 1.5-3 second delay to deconstruct a pipe, which is enough to prevent accidents I think.

**Comment by SmoSmoSmoSmok** [comment]
Yeah WHEN you go unwrench a pipe it doesnt unfasten immediately. there's this colorful bar that appears over pipe and you wait for the bar to fillup before it gets unfastened. Same deal with any pump/filter/mixer, this PR doesnt change or remove any of that

**Comment by SomeDongus** [comment]
This is good.

**Comment by timothymtorres** [comment]
> Yeah no, this should be on rclick at least.

Do this and quit c/p'ing the same code across all the different subtypes if possible.

**Review by timothymtorres — COMMENTED** [review]
You should move all the c/p code to the base object at `obj/machinery/atmospherics/components/binary`

**Review by Bawhoppen — COMMENTED** [review]
test: pls ignore this post

**Comment by MrStonedOne** [comment]
FYI: This PR got broke by github, and nobody can leave code comments on it.

**Comment by timothymtorres** [comment]
> FYI: This PR got broke by github, and nobody can leave code comments on it.

It's cursed!

**Review by Ghilker — COMMENTED** [review]
put the behaviour on r-click, remove the copypasted code and put it somewhere in the component parent

**Comment by timothymtorres** [comment]
unknown

Congratulations this PR somehow managed to break Github.  On discord me and several others tried to leave code reviews on your PR and were unable to.

Anyway, what @Ghilker said.  Move the code logic to `/obj/machinery/atmospherics/components/binary` and `/obj/machinery/atmospherics/components/trinary` objects and there will be less code bloat.  On top of this make sure `on = !on` is changed to `on = FALSE` since we want the atmos machines to always turn off.

**Comment by SmoSmoSmoSmok** [comment]
I JUST had an epiphany. THIS thing was never meant to be

**Pull request closed without merging**
