### PR TITLE
Removes pointless var on /mob

### PR DESCRIPTION
**Pull request by SuperNovaa41**
This variable was pretty useless, an if statement provides the same
behaviour

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]

**Comment by SuperNovaa41** [comment]
its more modular but nothing really uses it so i dont see a point for it, feel free to close it if you want its not that important

**Comment by CocaColaTastesGood** [comment]
you can avoid the if altogether with client.set_right_click_menu_mode(isobserver(src))

**Comment by SuperNovaa41** [comment]
Oh yea i 100% get the reason i was just trying to cleanup mob vars :)

**Comment by CocaColaTastesGood** [comment]
who cares about OOP standards

**Pull request closed without merging**
