### PR TITLE
restores legacy sends to SSChat

### LINKED ISSUE #47693: Missing chat if I late join
## Round ID:
123352 (for the screenshot, but it is not round-dependent) 

## Testmerges:
#46968

## Reproduction:
So, if I join Bagil or Event Hall EU mid-round, my entire chat box stays blank forever. But it _seems_ that if I actually witness the server setup steps, then my chatbox will be populated and work the rest of the round. Nothing else seems to be broken; I can open windows for consoles and machines without issue.

I have tried manually clearing (deleting) my cache, as well as a full reinstall of Byond. The issue has been occurring all day today, not just in any single round.

I have high suspicions this is being caused by #47653. I was not getting the problem at all on my local server, but I can make that one-line change to my local files and cause the issue pretty reliably. I've tested going back and forth, and only with `flags = SS_TICKER` on the chat subsystem can I reproduce the issue locally.

Screenshot of the problem:
image

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

A couple of users are having issues with goonchat failing to load so this is a fallback in the immediate send proc in the mean time.

Closes #47693 (sort of)

## Changelog
:cl:
fix: Chat is properly sent to legacy window if goonchat fails to load again.
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
Speedmerge pls.

**Comment by HomocidlePancakes** [comment]
Could you make it togglable?

**Comment by actioninja** [comment]
Why would it ever need to be toggleable, what the hell are you talking about?

**Comment by optimumtact** [comment]
>speedmerge
>doesn't compile

HOHOHOHWIOEFNERIOGjhrltgj uap9ners8ol

**Comment by HomocidlePancakes** [comment]
I know that le epic shotgun chat lag was fixed recently, but I have a pretty high average ping, so knowing that chat could lag you, I would rather permanently have it off just in case.

**Comment by actioninja** [comment]
I thought I pushed the building version but I typed [git somehow

**Comment by actioninja** [comment]
wrong fucking button

**Comment by actioninja** [comment]
I still don't actually know what the fuck you are talking about. this fixes chat lagging you.

**Comment by nemvar** [comment]
Maybe add logging?
@HomocidlePancakes not seeing chat isn't a viable solution to lag. This doesn't even have anything (well mostly) to do with latency, this fixes client freezes related to to_chat spams.

**Pull request merged**
