### PR TITLE
Disables Skewium mixing (until the client crashing bug is fixed)

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
fix: Skewium mixing has been disabled due to a client crashing bug.
/:cl:

Right now, Skewium locks up/crashes some clients and in some cases makes the OS stutter. IMO it should be disabled until someone figures out how to fix the bug.

Related issue: #37923

### CODE REVIEW

**Comment by optimumtact** [comment]
without a proper report of this to byond how can you even be sure it's not something related to the operation of your hardware or the configuration of your machine?

**Comment by 81Denton** [comment]
Yeah, that sounds more reasonable. Let's see what Lummox has to say

**Comment by Iamgoofball** [comment]
https://file.house/IcY3.webm

Close this.

**Comment by 81Denton** [comment]
How can I close something that is closed 🤔

**Comment by Iamgoofball** [comment]
fuck

**Pull request closed without merging**
