### PR TITLE
Nearly every single room on metastation has a giant fucking rafter holy shit

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Poggers? Pogged?

## Why It's Good For The Game

THE ASSISTANTS, THEY HIDE IN THE RAFTERS. FEAR THEM

## Changelog
:cl:
add: Fear the Assistants.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
:trollface:

**Comment by Paxilmaniac** [comment]
:trollface:

**Comment by Kylerace** [comment]
:trollface:

**Comment by itseasytosee** [comment]
:trollface:

**Comment by MrDoomBringer** [comment]
image
LGTM?

**Comment by Mothblocks** [comment]
:cl:

**Comment by itseasytosee** [comment]
But how are they supposed to get in the rafters 🤔

**Comment by ShibaInuLord** [comment]
:trollface:

**Comment by tralezab** [comment]
this makes the atmos subsystem vurp blood

**Comment by Mothblocks** [comment]
i liked it

**Comment by tralezab** [comment]
yeah it was actually cool

**Comment by Mothblocks** [comment]
theres the obvious of that it lets people into no access areas absurdly easily, but if you could solve that adding a new rafters maint is cool as shit. imagine if we had fire alarms on the ceiling that sprayed water lol

**Comment by MrDoomBringer** [comment]
sprinklerstation
based

**Comment by Mothblocks** [comment]
there's an entire dimension we're not making use of here, both physically and comedically

**Pull request closed without merging**
