### PR TITLE
Mech RCD rework

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
The mech RCD will now build at 5 tiles range (from 3), but build structures 1.5 slower than a normal RCD, 3 times slower than it used to be (2 times faster than a normal RCD)
This will make the mech RCD used for big construction projects, but not in combat.
## Why It's Good For The Game
Mech RCD shouldn't be able to Fortnite all over the crew and build structures WHILE WALKING and GETTING SHOT at 2 times the speed of a normal RCD.
I don't think fortnite-like gameplay is good for SS13, being able to build a box around your mech and get out for repairs/changing cells is absurd and destroys any weaknesses a mech has.
## Changelog
:cl: grungussuss
balance: The mech RCD has been reworked to build 3 times slower but at 2 tiles further.
/:cl:

### CODE REVIEW

**Comment by EnterTheJake** [comment]
Don't like this, Mechs using their environment to trap enemies is a cool strat that comes with the clear downside of losing one of your weapons.

I'm not even sure what you mean by "destroy every weakness the mech has".

 emp grenades go through walls. and once the wires are disabled the pilot is forced to go out to manually reset them.
 
 This screams skill issue to me ngl.

**Comment by EnterTheJake** [comment]
> > Don't like this, Mechs using their environment to trap enemies is a cool strat that comes with the clear downside of losing one of your weapons.
> > I'm not even sure what you mean by "destroy every weakness the mech has".
> > emp grenades go through walls. and once the wires are disabled the pilot is forced to go out to manually reset them.
> > This screams skill issue to me ngl.
> 
> they can still do that but it's now possible to counter it, building a wall in 1 second is literally fortnite

This makes the strat almost unusable in battle, and again it has counters, plenty of just go to chem and make a bunch of emp grenades, you can probably make a crate full of them in less than a minute.

**Comment by GuillaumePrata** [comment]
Mech fortniting has counters? Yes.

Is it fun to interact with mech fortniters, even when you have the counters in hand already? No.

We shouldn't let annoying metas stick around, we should strive to have combat be engaging for both sides and fortniting won't ever be.

**Comment by anclandor** [comment]
Bruh 2.5x slower than a handheld RCD?????  Are you kidding me nobody is ever going to use this for a "large construction project" if it is literally slower than EVERY alternative building strat.  Just make is so you can't use it while walking or something.

**Comment by CCC23** [comment]
yea ima be real no one in their right mind is EVER going to use a mech for a construction project

**Comment by githubuser4141** [comment]
Instead of nerfing the RCD, why not just make it unable to be mounted to mechs that aren't Clarke or Ripley? It's mounted to a big mech, so it's supposed to be more powerful then the hand-held version.

**Comment by Sadboysuss** [comment]
> Instead of nerfing the RCD, why not just make it unable to be mounted to mechs that aren't Clarke or Ripley? It's mounted to a big mech, so it's supposed to be more powerful then the hand-held version.

that's a good idea but let's see what maintainers think of this PR first

**Comment by Sadboysuss** [comment]
> Bruh 2.5x slower than a handheld RCD?????  Are you kidding me nobody is ever going to use this for a "large construction project" if it is literally slower than EVERY alternative building strat.  Just make is so you can't use it while walking or something.

The mech rcd can construct while moving and at a distance as many walls as they want at once so I disagree

**Comment by SimplySmiley123** [comment]
> > Bruh 2.5x slower than a handheld RCD?????  Are you kidding me nobody is ever going to use this for a "large construction project" if it is literally slower than EVERY alternative building strat.  Just make is so you can't use it while walking or something.
> 
> The mech rcd can construct while moving and at a distance as many walls as they want at once so I disagree

It's still a mech, a materials sink that could of been used to build without making the mech first already, without moving at a snail's pace and without the jankiness.
You can build your engineering projects before the mech is finished and slowly makes it's way to wherever you wanna build.

**Comment by Sakamoto4ka** [comment]
After power rework it kills cell very fast

**Comment by Sadboysuss** [comment]
PR body has been edited to reflect latest change

**Comment by githubuser4141** [comment]
> After power rework it kills cell very fast

No it doesn't in fact the new mech RCD uses way less power then it used to use. I'm pretty sure the mech has a 100x multiplier on it's cell, because a 40 MJ bluespace cell turns into 40 GJ in a mech to balance this.

**Comment by chemistrymain3** [comment]
> Having seen a video I think I can agree that individual walls maybe construct too fast right now; given that you can queue up a bunch of them you don't need individual ones to complete rapidly anyway.
> 
> Designating a large area and letting it construct over a few seconds is fine: this is a construction tool and it _should_ be impractical for use in the middle of a fight.
> 
> That said I also think that after your change it is slower than it needs to be.
> 
> My ideal solution is that a wall should construct in 3-4 seconds but anyone passing by who disagrees that there should be a wall here can cancel the construction by dealing any amount of damage to the construction animation hologram. 3-4 seconds is enough time for someone to be able to react and walk over.

Do you happen to have the video on hand?

**Comment by Jacquerel** [comment]
@Sadboysuss testing this locally it appears that RCDs operate using a "Frequent Use Debuff Modifier", meaning that constructing a second wall rapidly after the first will take three times as long.
If you make the initial build time quite long there should be no need to also apply this modifier, so please ensure we aren't double-dipping here.

You may be able to do that by setting `upgrade = RCD_UPGRADE_NO_FREQUENT_USE_COOLDOWN` on the internal RCD object used by the mech RCD.

**Comment by Jackal-boop** [comment]
> @Sadboysuss testing this locally it appears that RCDs operate using a "Frequent Use Debuff Modifier", meaning that constructing a second wall rapidly after the first will take three times as long. If you make the initial build time quite long there should be no need to also apply this modifier, so please ensure we aren't double-dipping here.
> 
> You may be able to do that by setting `upgrade = RCD_UPGRADE_NO_FREQUENT_USE_COOLDOWN` on the internal RCD object used by the mech RCD.

this sucks on normal RCDs its going to mega suck on mechs

**Comment by Sadboysuss** [comment]
lost interest

**Pull request closed without merging**
