### PR TITLE
Moves "catch this var/flag" code from obj/init and datum/new into the types that use it 

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

A pattern we often use is "Set this var, then we'll handle the rest"
This is normally fine, but in expensive code it ends up costing like 0.05 seconds. Lemme just move these out then

Totally optimizes away /obj/Initialize

We were spending like 0.15 seconds just checking for blueprints, obj flags and network ids
All these things can just be applied where they're wanted, saves time

Oh and I replaced object flags with a flags injector.

Requires a GenerateTag() call to set DF_USE_TAG, rather then doing a check in atom New

This is technically harder to use, but I don't really want people using tags, and it saves 0.15 seconds

Saves 0.5 seconds, makes init emissive blockers actually work (CURSED)

Ok so background. If an overlay is added with add_overlay, and not "managed" somehow, it will effectively never be removed, because nothing's tracking it.

Update_overlays uses the managed_overlays list/var (one of those) to do this.
I'm gonna piggyback off this to make emissive overlays actually like, respect overlay updates.

Oh and uh, I've saved maybe 0.5 seconds by caching the new emissive, and not using add_overlay. There's a chance this will lead to overlay corruption, but since we never readd the flattened, I think we'll be safe

### CODE REVIEW

**Comment by Kapu1178** [comment]
ah cool making code more complicated and less maintainable for literal fractions of a second of init time.

**Comment by Mothblocks** [comment]
What code is made less maintainable? What makes having literally every object check for something that a handful of stuff care about better than doing it more specifically? Get a grip. We have an init time on *local* of 60-90 seconds (depending on your computer's speed, and LOWMEMORYMODE), not to mention the compile time. We have already more or less proven that all optimizations we can get are going to be small, and will need to add up. If you aren't willing to save "fractions of a second" (in this case, 0.5 seconds), then you cannot make *any* optimizations or progress. Instead of dismissing the efforts of the people trying to make our dev cycles not unworkably slow, consider instead putting your money where your mouth is and helping out.

**Comment by Kapu1178** [comment]
>consider instead putting your money where your mouth is and helping out, especially if you can find a way to make a dent that isn't "literal fractions of a second" a piece.
image

image

lol. lmao, even.

**Comment by Mothblocks** [comment]
Yes, and on Club Penguin 13 we got init times down to below 20 seconds by cutting out half the game. 

I don't plan on arguing this, but either put your money where your mouth is or quit shitting on work like this.

**Pull request merged**
