### PR TITLE
[WIP] Fixes balding hair sprite, changes to a few other hair sprites

### PR DESCRIPTION
**Pull request by soapstain22**
## About The Pull Request

Has been on my mind for a long time and I wanted to contribute to the game since I started, so here it is.

## Why It's Good For The Game

Looks a lot nicer and more recognizable to their real world counterparts

## Changelog
:cl:
tweak: makes the Mohawk, reverse Mohawk, commando, hitop, and devils locks look like their real world counterparts
fix: fixed bald hair not reaching around the back, making it look like sideburns

/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
You deleted a lot of icons

**Comment by kriskog** [comment]
Likely making the changes to an old dmi, you seem to have deleted all the styles added in #43564.

**Comment by wesoda25** [comment]
bald

**Comment by soapstain22** [comment]
> You deleted a lot of icons

which ones got deleted?

**Comment by soapstain22** [comment]
> > You deleted a lot of icons
> 
> which ones got deleted?

wait i see what went wrong. ill fix it soon

**Comment by PKPenguin321** [comment]
to fix icon goofs:
- manually extract your modified icons from the .dmi through dreammaker
- manually download the original .dmi and replace your local one with it
- import your modified icons that you exported in step 1
- commit

**Comment by SpaceManiac** [comment]
Closing as Stale for being Work In Progress for over a week with no updates. If you want to continue work, reply here or ping a maintainer.

**Pull request closed without merging**
