### PR TITLE
Increases the Durand's Laser Resist to be the same as the Other Combat Mechs

### PR DESCRIPTION
**Pull request by KingkumaArt**
## About The Pull Request

So, when fixing the durand shield energy drain, I noticed something: The durand, aka the slow, "tough" mech, has a laser resist of 15. This may sound like a meaningless number to some, so I have made a list of things that share that resistance value.

- Sec Berets
- The Head of Personell's Winter Coat
- Ashwalker Bone Gloves and Boots

Additionally, here are some things that have more laser armor than a giant robot made of literal titanium.

- Gateway ATVs, Wizard Robes, and Laser Tag Uniforms (20)
- Basic Sec Armor Vests, Curator Indiana Jones Coat, Roman Centurion Costume, Phazon (25)
- The Captain's Winter Coat, Iron Knight Armor, Gygax, Ivanov, Ripley Mk2 (30)

Additionally, a comparison with the gygax, a rather glass-cannony mech reputation wise.

16 shots to kill a gygax (250hp, 30 laser armor)
18 shots to kill a durand (400hp, 15 laser armor)

Despite nearly double the HP, a durand dies in only 2 more laser shots.
With this pr, it takes 25 shots to kill a durand with a basic laser gun - which, honestly, I feel is fair, given its low speed making it very, very easy to land hits on.

## Why It's Good For The Game

The durand is fairly established as the slow, tough, tanky mech of ss13. However, versus the most common on-station weapon, lasers, it has the lowest resistance of any mech - lower than even the cargo power loader. Increasing the resist to 30 gives it the same resist as other stationside combat mechs in the game - the gygax and ivanov both have 30. This makes it easier for a player piloting a mech to know how dangerous lasers are, rather than getting into a durand and being confused why it died so fast despite being a "tanky" mech, as these resistances arent shown ingame anywhere.

Also the fact a giant mech is armored with effectively worse materials than the kevlar vests security wears makes no sense.

## Changelog
:cl: WebcomicArtist
balance: Durand's Laser Armor has been increased to 30, making it take the same amount of damage as the gygax, ripley mk2 and ivanov from lasers.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
So like, I agree with consistency, but I think comparing mech to the armor found on other objects or armor relevant for mobs isn't a terribly good comparison when you have differing 'health' values to contend with. 

A durand has 400 'hitpoints', so to speak, so it is difficult to compare it to the human's typical crit value of 100 hit points (though even that isn't exactly accurate either)

The reason it has this value might be several fold;
A) It got grandfathered in from the mech refactors.
B) Mechs used to have a mechanic called 'deflection', which completely negated an attack.
C) Mech armor plates used to increase this deflection. Now they increase armor.

While in the current state, it does have 15, it can go up to 35 with armor plates.

It isn't a huge deal, and this isn't meant to dissuade you, but it may be an explanation as to either why it has the value it does, or was not updated when the mechanics around mechs changed.

**Comment by KingkumaArt** [comment]
> I think its probably just best to analyze within mechs themselves. Or maybe taking a bit of a look at the history of mechs.

Fair. I just thought giving some gamewide data would help, but you have a point.

> While in the current state, it does have 15, it can go up to 45 with armor plates.

I've done full ranged armor tests with the new values, Durand takes 35 lasers to kill (gygax takes 20). Unless you roll a nav malfunction, then your hp may as well be zero.

**Comment by KingkumaArt** [comment]
Oh also - not in response to anyone in particular - I dont forsee this impacting the overall "balance" of the Durand in a major way, as most complaints about the Durand being overly strong are in regards to stuff like xenos, blob or dragon who don't have lasers and tend to have limited mobility. If anything it might make their lives easier, as there is now merit to use something besides melee armor on it now, meaning they might actually fight a ranged armor durand, which I think they could probably kill.

**Comment by Loafin34** [comment]
durand is the anti-kaiju armor. gygax is the "kill sec" armor

**Comment by Bibarra** [comment]
Wouldn't roboticists just continue to stack melee armor and laugh as they're even harder to kill? I'm not sure how taking away a weakness incentivizes players to stack something other than melee armor. Also pirates would not be able to engage a Durand.

**Comment by SimplySmiley123** [comment]
> Wouldn't roboticists just continue to stack melee armor and laugh as they're even harder to kill? I'm not sure how taking away a weakness incentivizes players to stack something other than melee armor. Also pirates would not be able to engage a Durand.

You're in a slow as all hell mech suit.
It's not exacly hard to land shots on a durand consistently, alongside the malfunctions erasing any threat of the affected mech.

**Comment by githubuser4141** [comment]
> Oh also - not in response to anyone in particular - I dont forsee this impacting the overall "balance" of the Durand in a major negative way, as most complaints about the Durand being overly strong are in regards to stuff like xenos, blob or dragon who don't have lasers and tend to have limited mobility.
> 
> ...If anything, it might make their lives easier, as there is now merit to use something besides melee armor on it now, meaning they might actually fight a ranged armor durand, which I think they could probably kill, if they dont engage it in maints or something.

You're forgetting about front and back armor, which are major factors into winning or losing a mech fight. If the pilot decides this isn't important, then they lose. A durand with it's front turned towards the enemy, specifically the one firing lasers at you, has 50% + 15% laser resist, (front armor is 0.5x damage, side is 1, back is 1.5x), so that'd be 10.6 damage per hit - the Durand breaks in 38 hits now, add some for misses/repair droids. 

You've just buffed the innate stats, this means there's less incentive to pick the melee armor.

I also think the in-lore rationale is, that combat mechs aren't as thick as you want to believe. You have to remember there's limited room for armor when they have to fit through a doorway, and have empty slots for utility equipment, which is probably also under some amount of armor. 

The Durand probably isn't as high-tech as the Gygax, mostly built from plain titanium and steel, which gives it good smack/stab protection, but it's not as resistant to bullets or lasers, compared to the Gygax's selective use of kevlar/hardened plastic/steel alloy/ceramic that means it can't take as many brute force attacks, but make it tougher against other attacks. If anything, I think the Gygax's laser and bullet resists should be buffed, and the Durand's bullet resists lowered.

**Comment by KingkumaArt** [comment]
> > Oh also - not in response to anyone in particular - I dont forsee this impacting the overall "balance" of the Durand in a major negative way, as most complaints about the Durand being overly strong are in regards to stuff like xenos, blob or dragon who don't have lasers and tend to have limited mobility.
> > ...If anything, it might make their lives easier, as there is now merit to use something besides melee armor on it now, meaning they might actually fight a ranged armor durand, which I think they could probably kill, if they dont engage it in maints or something.
> 
> You're forgetting about front and back armor.

The above tests were numbers from firing on front armor - and as stated before, if you roll nav malfunction, your 300 hp may as well be zero as you won't be able to attack or run away due to random controls. You don't have to set a mechs hp to 0 to have it effectively dead - each test I ran I had rolled all 5 malfunctions by the time the Durand frame actually broke.

> You've just buffed the innate stats, this means there's less incentive to pick the melee armor.

I assume you meant ranged armor here- if so, the reason why (imo) it makes ranged armor more appealing is because the Durand can achieve a respectable amount of ranged armor now - previously there wasn't any point doing it, as you could just build a gygax and get more ranged armor with extra speed, and speed is king in this game

> The Gygax's laser/bullet armor should probably be a raised a bit imho, so it's not completely useless. 
Imo, the gygax already outperforms the Durand in every regard combat wise besides xenos, spiders,  dragon and blob. Versus every other antagonist in the game, the gygax is better, because said you can axtually pursue said antagonist and not just get kited to death. Remember, there is no obligation to actually fight a mech when you see it, and the Durand is so slow that if you run from it it's basically useless in a lot of situations.

**Comment by githubuser4141** [comment]
> > You're forgetting about front and back armor.
> 
> The above tests were numbers from firing on front armor - and as stated before, if you roll nav malfunction, your 300 hp may as well be zero as you won't be able to attack or run away due to random controls. You don't have to set a mechs hp to 0 to have it effectively dead - each test I ran I had rolled all 5 malfunctions by the time the Durand frame actually broke.

Clearly wrong, because laser's damage (25) x 0.5 is 12.5, even discounting the Durand's actual armor, that's still a total of 32 hits before it breaks. 

Did you shoot an empty mech? The dir's might not be being set according to the sprite, try checking the mech's actual direction so you don't accidentally shoot the rear.

> > You've just buffed the innate stats, this means there's less incentive to pick the melee armor.
> 
> I assume you meant ranged armor here- if so, the reason why (imo) it makes ranged armor more appealing is because the Durand can achieve a respectable amount of ranged armor now - previously there wasn't any point doing it, as you could just build a gygax and get more ranged armor with extra speed, and speed is king in this game.

Yeah, ranged armor. I mean, now I know it's less necessary - so why would I even bother? It's still better to grab all melee armor, because melee is imho a bigger threat then projectiles which I can dodge, or soak with the front armor (mech directional armor doesn't work for item melee, but it does for mobs or projectiles). 

> > The Gygax's laser/bullet armor should probably be a raised a bit imho, so it's not completely useless.
> 
> Imo, the gygax already outperforms the Durand in every regard combat wise besides xenos, spiders, dragon and blob. Versus every other antagonist in the game, the gygax is better, because you can axtually pursue said antagonist and not just get kited to death. Remember, there is no obligation to actually fight a mech when you see it, and the Durand is so slow that if you run from it it's basically useless in a lot of situations.

I disagree, with a voice or BCI controlled overclock you're better off with the Durand still in most situations. You're tankier, your melee stuns people, putting them to sleep over just knocking them over and does more damage (25 vs 40), breaks walls more effectively, your forcefield can be used to soak high-damage attacks (say, revolvers or powerful ballistics) so you don't trigger a servo malfunction, with the generator module + ballistics even if you do run out of power, you won't stop moving and shooting. 

It's almost impossible to get "kited to death" in a Durand if you have all melee modules equipped, unless you lag out or something, I mean it's never happened to me once when fighting people with melee weapons. It's so easy to just strafe backwards and melee/shoot them, either stunning or slowing them down making them easy to finish off. 

If you're smart, especially if you have thermals, it's difficult to run from a Durand if it's got a RCD, you can literally wall off your own entrance, wall off other exits, wall off maints, etc. Most crew don't have the ability to instantly break walls on a whim. Example, your target's in the kitchen? Cool, put a wall in maints, blocking his maints exit. Enter the kitchen, walling off your entry, and wall off the other 1-2 exits. Great, now he's trapped and can't escape at all. (Tables will stun him, giving you ample time to shoot/punch him dead.)

**Comment by githubuser4141** [comment]
> A) It has the power hogging issue right now, B) if you got the malfunctions, that shield won't help you because it's directional and you inevitably loose controls if you reach malfunctions C) lasers don't have ammo issues, they do run out and gotta recharge, but they got no hurry considering you're in a Durand and will likely still be there when they're back with a charged gun.

Yeah.... it's supposed to be directional. I still wouldn't trust the average player to target the part uncovered by the shield tbh.
Yes, lasers have ammo issues as in they stop firing when they run out of ammo. That's an ammo issue, the shooter has to run back and find a probably un-upgraded charger. That's more then enough time for you to move away. It's only 10 or so seconds to fix the servo malfunction my man.

You're underestimating a Durand's speed, it can practically go anywhere it choses by smashing out walls or doors. Plus, RCDs exist to wall yourself back away, giving you time to repair/recharge. 

> You can't dodge the shots in a Durand. In a Gygax or a Phazon, you absolutely can, with Durand at best you can avoid one shot before several other shots connect with you, and the front armour doesn't matter considering it's way less of a health and armour issue and more of a malfunctions issue. You could be still well above half integrity, but RNGesus said "fuck your controls" and take the steering away from you.

What do you mean, I can't? Projectiles aren't hitscan, anything that's capable of moving can dodge them by moving out of the way. I'm playing on a 2021 budget celeron laptop and I can dodge projectiles just fine, it's called moving out the way. Heck it's easier in a slower mech because you have more control.

 Malfunctions only happen if you take 15 or more damage. You won't ever take a malfunction with frontal-hit lasers (10.5 damage for basic, or 12.7 for captain's), excecpt for heavy/pulse/accelerator laser.

> Never seen an overclock on a Durand but, even then it's still no Phazon, you aren't catching up to anyone in your Durand unless the person you're chasing in your mech has attention span of a fly, situational awareness of a boot and if all they have to deal with you is just melee and nothing to shoot you with, or even fucking _throw_ at you. In a Gygax you can catch up to them _once_ with your "sprint" at the cost of throwing out all of your mech's power for it.

Melee/throwing won't do squat to a durand though.. and humans don't have infinite HP, they slow down as their HP whittles down too. The idea of a mech is you're moving and shooting at the same time (difficult with the new mech-walks-into-its-own-bullets bug), you're not running in circles trying to cuff him or something. I don't disagree it's faster in a Phazon/Gygax but it's completely possible in a Durand. And this is assuming the target isn't wearing a slowing suit, is pre-damaged or there's firelocks in the way. 

> While getting away in a Durand... Yes, if you're a traitor with thermals, waste one of your slots for an RCD, got the best parts available to a station and if the crew is already too busy dying to something other then you or genuinely and unironically too stupid to catch up with a Durand out of all the mechs. Otherwise nope, one guy with a laser gun is enough to bully you. Meleeing a Durand is a gamble, using a laser gun is a no-brainer with how fucking spammable they are thanks to cargo and the nigh infinite ammo if there's any recharger nearby. And regardless, they don't need to kill your mech, they just need to proc a malfunction or run your charge out since they can just camp the only mech chargers on the station very easily.

I've been playing with mechs since 2020, and I've never seen anyone camp a charger with any success, and I almost always run a LMG + RCD on the Durand, recently accompanied by various rebalances and nerfs I've done laser or KA + RCD. I don't think you've played enough if you think the RCD is a "waste" to be honest. Don't let the one guy's laser hit you from the side/back, keep your front end facing him and actually fire back at him. He's gonna run out of ammo and probably health much quicker then you 99% of the time. When he's running for the charger, run after him, or take your time with the ranged, multitask RCD to put up walls so he's forced to engage you in CQC, when he comes close to you, RCD the exit away. Now he's stuck there with you. 

You don't even need T4 parts, T3 or even T2 parts is perfectly acceptable in mechs nowadays, it used to be that T1 == unuseable, T2 == 99% useless, T3 == okay, T4 == good, but even T1 is just barely acceptable now.

As long as there's still some charge left for RCD, I can easily recover by - wall myself into existing walls, so I don't use as much power, get out, screwdriver-crowbar, remove cell, get new cell from my full BSRPED, add new cell, get back inside. Presto I'm at full charge.

**Comment by KingkumaArt** [comment]
So, mostly unrelated to the above: Was doing some testing with the laser gun, and somehow, shooting a durand is giving me weird fractional damage values. One laser from the side did 21.3 damage which... shouldnt be a thing. Do mechs have their damage automatically decreased by 1/6th?

**Comment by KingkumaArt** [comment]
After doing some thinking, im probably gonna close this. If I do a durand buff it'll be involving the shield.

**Pull request closed without merging**
