### PR TITLE
More Suits resprites (Bonus: Chef/Bartender updates!)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Finally, my ultimate goal:
All Lawyer suits are now under suits.dmi. Having some suits in suits.dmi and some in civilian.dmi was just really really weird and confusing.

Also updated some more Service stuff, specifically the Chef and Bartender. Their uniform is the generic Service Buttondown, and their other gear has been updated. The Bartender, notably, now has a new item, the bowtie!

Full changelog:
- Adds Bowtie (and yes, it's in relevant vendors)
- Adds a greyscale Formal Jacket (the lawyer jackets but greyscaled)
- Removes `/obj/item/clothing/under/rank/civilian/chef` and `/obj/item/clothing/under/rank/civilian/bartender`; replaces them with `/obj/item/clothing/under/costume/buttondown/slacks/service`
- **Moves all Lawyer suit sprites to the suits.dmi**
- Converted `/obj/item/clothing/under/rank/civilian/lawyer/bluesuit` to use the same GAGS configs as the buttondown (path unchanged)
- Resprited all Lawyer suits (except galaxy ones)
- Resprited the Lawyer jackets to match (including a currently unused GAGS-palette one)
- Resprited the Chef Apron-Jacket and Hat
- Resprited the Botanist Overalls (and made them Greyscale)
- Updated the shirt on the Cook Jorts to be more up-to-date instead of being new pants on a super crusty old shirt sprite.
- Puts stuff into vendors

## Why It's Good For The Game
Sprote updates yahoo!

Chef/Bartender showed their age, and essentially had the same uniform. Now they look much more at home.
image
GAGS Suit jacket yippee!
image
This jacket was put into to the Bartender's vendor for the sake of allowing them their own gimmicks, such as this:
image
New greyscale overalls wahooo! Since they're greyscaled they're also in the clothesmate for anybody who really wants them.
image
The Lawyer suits just used an entirely different type of shading and it made them stick out weird... I'm not quite sure on reshaping their jackets but figured it's better to start with this and update them if requested.
image

As for moving Lawyer suits to suits.dmi... I just don't like them being split up. It makes it annoying to prevent duplicates or keep them all updated.
## Changelog
:cl:
add: Added the Bowtie! Bartenders start with one on, but they can also be found in the Bardrobe, Autodrobe, and Clothesmate. No need to tie it either, it's just a clip-on.
add: Added a Greyscale "Formal Jacket" of the style that most suits use, for crew who want to make their own using the buttondown shirt.
del: Removed the generic Cook/Bartender uniforms and changed them to use the Service buttondown w/ slacks.
image: updated the majority of Lawyer suit sprites, along with the Cook's Apron-Jacket and Hat, and updated/greyscaled Botany's Overalls! Also the Overalls are available in the clothesmate, and the Cook Jorts' shirt is less crusty.
/:cl:

### CODE REVIEW

**Comment by AdipemDragon** [comment]
thanks for making the bowtie a neck item instead of an accessory, so it'll work with the waistcoat

**Comment by Helg2** [comment]
> thanks for making the bowtie a neck item instead of an accessory, so it'll work with the waistcoat

You know you can put on multiple accesories?

**Comment by AdipemDragon** [comment]
> You know you can put on multiple accesories?

yes! but did you know that only the first one shows up visually? and the waiscoat is Kind Of A Huge Accessory, if you're planning a look around it you don't get much else wiggle room for other accessories

eitherway bowtie's nice

**Comment by Sealed101** [comment]
> yes! but did you know that only the first one shows up visually?

this sounds like a bug

**Comment by AdipemDragon** [comment]
> this sounds like a bug

say that to https://github.com/tgstation/tgstation/pull/76629

**Comment by Jezzared** [comment]
The default lawyer suits (blue and purples ones) are a reference to the main prosecutor and defense attorneys from Ace Attorney. Notably, Phoenix Wright (the blue suit) wears his suit jacket closed in most sprites.
images

**Comment by OrionTheFox** [comment]
> The default lawyer suits (blue and purples ones) are a reference to the main prosecutor and defense attorneys from Ace Attorney. Notably, Phoenix Wright (the blue suit) wears his suit jacket closed in most sprites. images

They're toggleable :trollface:

**Comment by Jezzared** [comment]
> They're toggleable :trollface:

Good! Works for me!

**Comment by necromanceranne** [comment]
oops deleted

This sprite seems to have been deleted, was that intentional?

**Review by Wallemations — APPROVED** [review]
looks fine to me

**Comment by OrionTheFox** [comment]
Marking this draft while I set up that GAGS formal jacket at the request of someone on discord. Might as well just bite the bullet and get it over with

**Comment by OrionTheFox** [comment]
Staying in a draft while another spriter plays with the purplebartender sprite a bit, but that's the only change left

**Comment by OrionTheFox** [comment]
> oops deleted
> 
> This sprite seems to have been deleted but not moved anywhere, was that intentional?

Was a duplicate of one in another file, not used in this one at all. Intentional.

**Comment by OrionTheFox** [comment]
Full-opening now, what's in is final. If the other spriter ever comes up with something it'll be in another PR, this one is more than servicable.
Leaving the baked in legs unless explicitly told otherwise because it's a reference outfit and I figure it should stay accurate to the reference
image

**Comment by OrionTheFox** [comment]
> @OrionTheFox you missed one
> 
> https://github.com/tgstation/tgstation/blob/4decc227c6253a3b7264c1ad0ba87e8452f0d926/code/game/objects/structures/crates_lockers/closets/job_closets.dm#L14
> 
> edit: while you're at it you may want to change `/obj/item/clothing/under/rank/civilian/bartender/purple` to `/obj/item/clothing/under/rank/civilian/purple_bartender` or something along those lines because the `/obj/item/clothing/under/rank/civilian/bartender/` subtype isn't being used and will be missing an icon.
> 
> edit edit: nevermind, I made a PR for it

Good catches, my B. Thanks for getting 'em

**Pull request merged**
