### PR TITLE
[NO GBP] Makes jetpack movement much smoother and prevents pushing off objects while using one

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request
Jetpacks will now prevent you from attempting to interact with objects near you in zero G, preventing you from pushing lockers and people around. This also makes jetpack movement ***much*** more smooth, as they will activate at your first move, preventing jerky movement when pushing off walls. Same applies to all wings which should help moth players with new spacemove.

Thanks to iusedtoplayxbox on discord for providing details regarding the issue.

## Why It's Good For The Game

Less jank = happier players

## Changelog
:cl:
qol: Jetpack movement is now much smoother
/:cl:

### CODE REVIEW

**Comment by JupiterJaeden** [comment]
Can we please just fix 100% of the issues and make jetpack movement not affected by the inertia system as you yourself suggested at one point? I'm not sure how hard this would be code wise but it is by far the best solution.

**Comment by LemonInTheDark** [comment]
> Can we please just fix 100% of the issues and make jetpack movement not affected by the inertia system as you yourself suggested at one point? I'm not sure how hard this would be code wise but it is by far the best solution.

This is non ideal because we do want to make space combat and movement more weird.
There's a few painpoints with this system, some of which are lag at highpop, some are just code issues (like this pr) and some are intentional added complexity/difficulty. 
That's why we are not just goin full intertia cull here, part of the point is making it a bit more complex.

Hope this clarifies intent a bit.

**Comment by JupiterJaeden** [comment]
> > Can we please just fix 100% of the issues and make jetpack movement not affected by the inertia system as you yourself suggested at one point? I'm not sure how hard this would be code wise but it is by far the best solution.
> 
> This is non ideal because we do want to make space combat and movement more weird. There's a few painpoints with this system, some of which are lag at highpop, some are just code issues (like this pr) and some are intentional added complexity/difficulty. That's why we are not just goin full intertia cull here, part of the point is making it a bit more complex.
> 
> Hope this clarifies intent a bit.

How is making space combat more frustrating good for the game.

**Comment by Metekillot** [comment]
It's bad for the sandbox to make one single course of action 'correct'. Previously, the Thing To Do was to kill gravity and get and advanced jetpack and you basically got free meth and no slip with the only downside being jetpack management.

Now, space move has upsides, downsides, and a much higher skill ceiling. So if you want to go go gamer gravgen C4, you have to be confident that you're a Robust Enough Dude to shift your move strategy to compensate for newtonian inertia.


DIGRESSION:  I think inertia should be added to moving along solid surfaces to be honest. Start slow, pick up speed, manage your speed. Gravity going out was formerly irritating and messy. I think it should totally change the dynamics of movement instead of just 'walk beside the wall for free max move speed'

**Comment by timothymtorres** [comment]
Does this fix #68275

**Comment by JupiterJaeden** [comment]
> It's bad for the sandbox to make one single course of action 'correct'. Previously, the Thing To Do was to kill gravity and get an advanced jetpack: you basically got free meth and no slip with the only downside being jetpack management.

I know it's a late reply but first of all, this really didn't happen that often except during nuke ops. And second of all, it was already fixed with the jetpack speed nerf that normalized the speed of all jetpacks.

**Comment by Yobrocharlie** [comment]
Hey there im here with criticism of this PR as somebody who has spent a couple hundred hours in space exploration and who uses a jetpack for probably 30 minutes to an hour every single shift i play.

Short story?
 This pr adds nothing to the game besides realism which doesn't make it good or maybe it pursues some grander coder vision idk.

Long story?
This PR makes space exploration or any endeavors where you will need to interact with space for extended periods of time significantly more painful, sure in the edge case where somebody decides to kill gravity and use the jetpack for movement still can quite easily do so if they've used the jetpack before all be it way with WAAAYYY more jank and way less intuitiveness than before however i do like the concept of being able to drift in space especially with fire extinguishers and such going faster and faster. But the fact that this extends to jetpacks is terrible because it just makes space exploration significantly more painful than it was before. For example sometimes if your dragging a crate behind you in space if you move to the side while pulling it there is a chance that it may just fling off in the direction you were going at mach 10 causing you to go on a 15 minute goose chase chasing down your crate of goodies. Or sometimes you dont even need to do this to cause a crate to fling off in a random direction if your just moving near it and sometimes the crate may hit you and break a limb which is horrendous not if a death sentence when your all out and alone in space.

I wish I could suggest a solution for fixing how jetpacks move in space but I firmly believe it more comes from a more fundamental flaw of trying to polish a brittle old statue, the polish didnt make it shine, it corroded it to make it less than it was.

**Comment by SmArtKar** [comment]
> Hey there im here with criticism of this PR as somebody who has spent a couple hundred hours in space exploration and who uses a jetpack for probably 30 minutes to an hour every single shift i play.
> 
> Short story? This pr adds nothing to the game besides realism which doesn't make it good or maybe it pursues some grander coder vision idk.

What you're describing is behavior pre-last PR, which found out a rather core issue of comsig ordering conditions between drift handlers and jetpacks. Nerfing jetpack speed sucks, not nerfing it ends up with rounds where those who get jetpacks are essentially invincible and everyone else eats shit. I'm still improving newphys, its not dead in the water

**Comment by Yobrocharlie** [comment]
> > Hey there im here with criticism of this PR as somebody who has spent a couple hundred hours in space exploration and who uses a jetpack for probably 30 minutes to an hour every single shift i play.
> > Short story? This pr adds nothing to the game besides realism which doesn't make it good or maybe it pursues some grander coder vision idk.
> 
> What you're describing is behavior pre-last PR, which found out a rather core issue of comsig ordering conditions between drift handlers and jetpacks. Nerfing jetpack speed sucks, not nerfing it ends up with rounds where those who get jetpacks are essentially invincible and everyone else eats shit. I'm still improving newphys, its not dead in the water

The behavior i was describing happened all last night.

The solution to making jetpacks work would be to give them a nerf indoors- not fucking take a shotgun to their kneecaps and render them completely unviable in any situation that requires any form of combat be it PVE or PVP, the change you decided to do sucks plain fucking sucks.

**Comment by Metekillot** [comment]
I plainly disagree with Yobro; I've had no trouble adapting the new inertia
mechanics for use in combat, but it has been a learning process, in
contrast to the previous implementation which was a plain buff that gave
jetpack users an obnoxious advantage in no gravity.

Skill issue.

**Pull request merged**
