### PR TITLE
[s] Fixes malf AIs being able to roundstart kill power instantly

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

### CODE REVIEW

**Comment by KorPhaeron** [comment]
But they can still explode the engineering apc or the smes or the particle acclerator?

I dont see why this is a fix or needed

**Comment by Iamgoofball** [comment]
We block blowing the supermatter shard too

**Comment by nicbn** [comment]
Don't block it blowing the sm. Blowing the sm is slow and loud, not a good malf AI tatic.

**Comment by KorPhaeron** [comment]
You dont see the differencr between giving googly eyes to a piece of the engine setup and giving googly eyes to the supermatter shard and having it walk off?

**Comment by ShizCalev** [comment]
Shard was blocked because it allowed the AI to explode a fair bit of the station with a single click, and also having a untouchable insta-gibbing on on contact machine roaming around was bad.

`the_singularitygen` doesn't fall into the category of critical equipment that can cause massive destruction instantly when blown up, there's a backup in engi storage, and cargo can order it another at any time (use a pac-man and some plasma to power to APC in cargonia if the AI has drained the power manually.)

**Comment by ShizCalev** [comment]
@nicbn The SM is already blocked. This is the list of machines that the AI is blacklisted from overloading (blowing up instantly) or overriding (making it come to life and attack people).

**Comment by Iamgoofball** [comment]
why the fuck is that the same list

**Comment by KorPhaeron** [comment]
Everything shizcalev said

**Pull request closed without merging**
