### PR TITLE
Fixes an oversight in the CE's hardsuit rad resistance

### LINKED ISSUE #43325: CE's jumpsuit + hardsuit is 100 Rad for body but not for head.
Taken from tgstation/code/modules/clothing/spacesuits/hardsuit.dm

> //Chief Engineer's hardsuit
/obj/item/clothing/head/helmet/space/hardsuit/engine/elite
	name = "advanced hardsuit helmet"
	desc = "An advanced helmet designed for work in a hazardous, low pressure environment. Shines with a high polish."
	icon_state = "hardsuit0-white"
	item_state = "ce_helm"
	item_color = "white"
	armor = list("melee" = 40, "bullet" = 5, "laser" = 10, "energy" = 5, "bomb" = 50, "bio" = 100, "rad" = 90, "fire" = 100, "acid" = 90)
	heat_protection = HEAD
	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT

> /obj/item/clothing/suit/space/hardsuit/engine/elite
	icon_state = "hardsuit-white"
	name = "advanced hardsuit"
	desc = "An advanced suit that protects against hazardous, low pressure environments. Shines with a high polish."
	item_state = "ce_hardsuit"
	armor = list("melee" = 40, "bullet" = 5, "laser" = 10, "energy" = 5, "bomb" = 50, "bio" = 100, "rad" = 90, "fire" = 100, "acid" = 90)
	heat_protection = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
	max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT
	helmettype = /obj/item/clothing/head/helmet/space/hardsuit/engine/elite
	jetpack = /obj/item/tank/jetpack/suit

In combination with tgstation/code/modules/clothing/under/jobs/engineering.dm

> /obj/item/clothing/under/rank/chief_engineer
	desc = "It's a high visibility jumpsuit given to those engineers insane enough to achieve the rank of \"Chief Engineer\". It has minor radiation shielding."
	name = "chief engineer's jumpsuit"
	icon_state = "chiefengineer"
	item_state = "gy_suit"
	item_color = "chief"
	armor = list("melee" = 0, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 10, "fire" = 80, "acid" = 40)
	resistance_flags = NONE

This looks like it means to give the CE full rad protection with jumpsuit and hardsuit. However without a mask that provides 10 rad protection for the head, CE is left with a very small opening for radiation. 

It would make sense for the CE to be able to walk around the engine room in a distinctive outfit as his peons lumber around in rad suits.

Not sure if this is a bug or working as intended. Could either change CE's hardsuit helmet to 100 rad or make the welding gas mask have 10 rad.

### PR DESCRIPTION
**Pull request by VileBeggar**
I hope it's an oversight at least.

Fixes #43325 
## Changelog
:cl: Vile Beggar
fix: Wearing the CE jumpsuit along with the advanced hardsuit will now fully protect you from radiation, as intended.
/:cl:

### CODE REVIEW

**Comment by Arianya** [comment]
It's not an oversight.

No station available hardsuit fully protects from rad, since doing so would make the actual rad suits meaningless.

**Comment by VileBeggar** [comment]
> 
> 
> It's not an oversight.
> 
> No station available hardsuit fully protects from rad, since doing so would make the actual rad suits meaningless.

well it's one of a kind hardsuit, only the CE gets it and if you're very lucky while space exploring you could fetch another one on pubby. besides, it's on the issue tracker /s

**Comment by Arianya** [comment]
The issue written isn't about the CE's hardsuit not having 100 rad resist instead of 90, it's about the fact that a jumpsuit + hardsuit combo doesn't provide 100 rad resist on the face (probably an oversight).

You could maybe justify adding a CE's gasmask that had 10 rad resist to compensate, though it'd equally be just as "correct" to say "tough, if you want full rad resistance wear the rad suit"

**Comment by GuppyLaxx** [comment]
"Fix" change this to balance instead

**Comment by Barhandar** [comment]
He's only touching the helmet so it's technically the oversight. Just wrongly phrased PR/changelog.

**Comment by Arianya** [comment]
No, he's touching the entire suit. The fact that the CE's uniform + hardsuit = 100 rad resistance doesn't mean its therefore okay to make the hardsuit 100 rad resistance. That's like saying we should just upgrade sec's body armour to have the combined brute defense of their uniform and their body armour.

**Comment by Barhandar** [comment]
He is literally only touching the helmet (and head area is not covered by the jumpsuit, hence "oversight", open up the code.

**Comment by subject217** [comment]
>as intended

There is literally nothing whatsoever to suggest that full rad protection is the intended behavior.

**Comment by Barhandar** [comment]
>There is literally nothing whatsoever to suggest that full rad protection is the intended behavior.

CE hardsuit is 90 rad and CE _jump_suit is 10 rad, giving 100% rad protection to CE everywhere but the head.

**Comment by CRITAWAKETS** [comment]
Its also kind of stupid how you can just wear a radsuit helmet, but not wear the full radsuit to have 100% protection.

As someone who plays CE a lot, this is a good change.

**Comment by subject217** [comment]
>CE hardsuit is 90 rad and CE jumpsuit is 10 rad, giving 100% rad protection to CE everywhere but the head.

That's not what "intended" means. I'm well aware of how its' resist works. If they really wanted 100% rad resist they would have just put it all on the suit anyways. Find literally anything from the person who made the CE suit that says it was intended to have full rad resist and then you can call it "intended". Otherwise this is a balance change, not a fix.

**Comment by necromanceranne** [comment]
This is largely semantics, all the same it is a change that solves a long standing problem with the CE hardsuit. Who cares if this was intentional or not. It's dumb and could use a change.

**Comment by Jimmius** [comment]
"we created this suit to be 100% rad proof, considering you're going to be standing next to something that kicks out more rads than the chernobyl reactor 10 minutes after meltdown."

"ok but where's the helmet?"

"the what?"

**Review by 81Denton — APPROVED** [review]
I am fine with this since the CE hardsuit is a unique head of staff item. There is no real point in making the CE wear a rad hood with his hardsuit.

**Pull request merged**
