### PR TITLE
Adds welding goggles to engivend

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: Engi-Vend machines now have welding goggles available.
tweak: Grouped Nano-Med/Engi-Vend items by category.
/:cl:

I added welding goggles to engi-vend machines (considering they're noncraftable). 
Lastly I grouped the contents of engi-vend and nano-med machines machines by type. 

Edit: Removed the RPD. Maybe adding an atmos protolathe in the future will be more acceptable?
Edit: #36083 got merged, removed pill bottles as well.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
This is textbook resource creep.

**Comment by Buggy123** [comment]
>This is textbook resource creep.

Eh relax, this is natural.

**Comment by 81Denton** [comment]
>This is textbook resource creep.

Is this sarcasm or is adding non-craftable items to a job specific vending machine resource creep to you

**Comment by Dorsisdwarf** [comment]
RPDs are atmos tech tools, why are they being added to the engivend which atmos techs arent allowed to use

**Comment by 81Denton** [comment]
Atmos techs have no vending machines, if they need more RPDs they could at least ask engineering for them.

**Comment by improvedname** [comment]
>non craftablle engineers can infinitly make rpds welding goggles doesnt matter since they make welding gas masks

**Comment by duncathan** [comment]
Please remove the RPDs.

**Comment by 81Denton** [comment]
@duncathan Alright, RPDs are gone.

**Comment by 81Denton** [comment]
#36083 got merged, I got rid of the pill bottles as well.

**Comment by Bawhoppen** [comment]
All I was saying, is making small PRs to add a little more for some job roundstart without removing anything to compensate, slowly degrades the value of whatever is being given. 
Adding RPDs to engis, make atmos techs a little more worthless. (yes I know this was removed)
Giving welding goggles to engineering, makes it all the less likely an engineer has to go to cargo and ask for a welding mask in their autolathe. 
Pill bottles are pretty inconsequential, but the principle still stands.
None of these things alone really are a big deal, but over time, lots of small additions of this scale will steadily keep coming (hence the term creep) and slowly and eventually build up and amount to being something significant.

**Pull request merged**
