### PR TITLE
Triples production of rice and flour

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

Uhhh, rice and flour gained from grinding will now be tripled. That's it.

## Why It's Good For The Game

Growing grains sucks, by tripling its output by 3 it will suck less.
## Changelog

:cl:
balance: We are now using space Monsanto brand rice/wheat seeds. Nutriment of both grains has been changed to 12% from 4%
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
@MTandi something to consider in #76205

**Comment by Mrfilms** [comment]
I like this change though it may upset botanists. I would recommend adding more functionality to rice stalks to balance this - perhaps as a feed for animals akin to wheat.

**Comment by jughu** [comment]
its not difficult its just the potency payoff and grinding each time when its a basic ingredient when you can stuff a beaker in biogen and just fill it with water or somehting to instantly make rice heaps

**Comment by carshalash** [comment]
> I like this change though it may upset botanists. I would recommend adding more functionality to rice stalks to balance this - perhaps as a feed for animals akin to wheat.

A decent use of rice is for making chickens with the cytology pods. (Maintainers please let me make the orderable cytology crate  for service, please)

**Comment by jughu** [comment]
i dunno why it would upset botanists all botanists do is just grow death plants and weed and stuff not needing to specially grow rice for the chef is a plus just keeping the biogen stocked

**Comment by carshalash** [comment]
> i dunno why it would upset botanists all botanists do is just grow death plants and weed and stuff not needing to specially grow rice for the chef is a plus just keeping the biogen stocked

we're meant to pretend that isn't the case :(

**Comment by DustanHache** [comment]
> i dunno why it would upset botanists all botanists do is just grow death plants and weed and stuff not needing to specially grow rice for the chef is a plus just keeping the biogen stocked

you will rapidly find a spear in your back from any selfrespecting chef before you get your death plants if that happens. either that, or they will loot botany for themselves.

**Comment by nukularpower** [comment]
This is a bad change that sets a precedent for worse ones.   Why not just add all food plants to the biogen?  why should botany exist at all?  Those death plant growin sods never do their jerbs anyways!    Just delete botany and have a biogenerator that assistants can throw maint trash into to get any plant type!

**Comment by optimumtact** [comment]
If you want it via other means, then cargo is the place you will have to go sorry.

**Comment by CMDR-Gungnir** [comment]
> This is a bad change that sets a precedent for worse ones. Why not just add all food plants to the biogen? why should botany exist at all? Those death plant growin sods never do their jerbs anyways! Just delete botany and have a biogenerator that assistants can throw maint trash into to get any plant type!

There's a difference between "I grow a tomato and then I can use it in tomato dishes" and whatever the fuck Rice and Flour have going on.

I think this is a good idea, and one we should do.

**Comment by carshalash** [comment]
> If you want it via other means, then cargo is the place you will have to go sorry.

Can I at least change the grinding quantity for rice so that it doesn't suck to grow?

**Comment by optimumtact** [comment]
I don't see any problem with that

**Comment by DustanHache** [comment]
> Can I at least change the grinding quantity for rice so that it doesn't suck to grow?
honestly, this is where we should be starting the conversation regarding plants to begin with. give us reasons to grow soy, wheat and rice beyond specific recipes that require the harvest itself!

**Comment by MrMelbert** [comment]
You can already get rice bypassing botany / via cargo, it's in the produce console

https://github.com/tgstation/tgstation/blob/b47d51837a852ca36d683526f55ee33e539ac8c4/code/game/machinery/computer/orders/order_items/cook/order_reagents.dm#L14-L17

Buff the default amount of nutriment in Rice so it grinds into more, it sucks right now

**Comment by MTandi** [comment]
In #76205 I will nerf biogen consumables to be 40% less filling (unless you purify it with another machine) than the default ones. They're synthetic and made of green sludge, that's why). Given this nerf, I believe it is fine to add it to biogen, since flour is already there. 

`reagents_add = list(/datum/reagent/consumable/nutriment = 0.04)`

But nutriment buff for wheat and rice would be nice. 4% is a bit too low, I'd suggest changing this to 8%.

**Comment by carshalash** [comment]
> In #76205 I will nerf biogen consumables to be 40% less filling than the default ones, unless you purify it with another machine. They're synthetic and made of green sludge, that's why. Given this nerf, I believe it is fine to add it to biogen, since flour is already there.
> 
> `reagents_add = list(/datum/reagent/consumable/nutriment = 0.04)`
> 
> But nutriment buff for wheat and rice would be nice. 4% is a bit too low, I'd suggest changing this to 10% or so.

I'll ping oranges about this later.

**Comment by ExcessiveUseOfCobblestone** [comment]
why does the biogen have items like flour/sugar in it when u can literally grow it from the same department

stinky af

**Comment by DustanHache** [comment]
> why does the biogen have items like flour/sugar in it when u can literally grow it from the same department
> 
> stinky af

sugar i agree on, but flour is very slow to produce from wheat.

**Comment by ExcessiveUseOfCobblestone** [comment]
> > why does the biogen have items like flour/sugar in it when u can literally grow it from the same department
> > stinky af
> 
> sugar i agree on, but flour is very slow to produce from wheat.

Why does the solution need to be to add it to the biogen vs. just buffing the flour production?

**Comment by carshalash** [comment]
Gimme a bit to double check that it works.

**Comment by carshalash** [comment]
So uhhhh, flour and rice have had their nutriment set to 12%. This effectively triples their output when grinding.

**Comment by MTandi** [comment]
> So uhhhh, flour and rice have had their nutriment set to 12%. This effectively triples their output when grinding.
> 
> Maints, let me know if you'll permit 20%, 

20 would make it as good as watermelon and pumpkin for biogen. It will be weird

**Comment by carshalash** [comment]
> > So uhhhh, flour and rice have had their nutriment set to 12%. This effectively triples their output when grinding.
> > Maints, let me know if you'll permit 20%,
> 
> 20 would make it as good as watermelon and pumpkin for biogen. It will be weird

Wheat and rice don't have perrenial.

**Comment by jughu** [comment]
biogen balance stops when you upgrade it anyways

**Pull request merged**
