### PR TITLE
Fixes the new action's permissions

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

It turns out there is another layer of fun when it comes to workflow actions. The more you know.

Adds the necessary YAML overrides for use in a restrictive default environment https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token

Fixes this with any luck
image

## Changelog
🥇

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
@Rohesie I suppose the round_linker action I modeled the config on already had perms? Anyway this change seems to be having the desired effect assuming github is restricting to read only for now because the workflow change is on my branch.
image

**Comment by Rohesie** [comment]
> 
> 
> @Rohesie I suppose the round_linker action I modeled the config on already had perms? Anyway this change seems to be having the desired effect assuming github is restricting to read only for now because the workflow change is on my branch.
> image
> It would make sense if the repo's action settings look like this:
> image

Don't think I have these perms. @Cyberboss , @ninjanomnom or @optimumtact should, being repo owners.

**Comment by Wayland-Smithy** [comment]
I bet if they check the repos Settings -> Actions it would look like my screenshot, since a) my original PR ran the action with all read perms for the GITHUB_TOKEN and b) this PR action has less perm scopes, but still read only. I only bring it up because I think that all indications so far point to this being the needed fix however I'm very new to this custom action meta aspect of github so confirming the setting should help increase confidence.

**Comment by Wayland-Smithy** [comment]
Upon further reading of that doc here: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#example-1-passing-the-github_token-as-an-input and of a sec lab post here https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ it is evident to me that the config was wrong all along and `on: pull_request_target` is what labeler type actions should be using for proper repo write perms. The `permissions:` YAML just limits the scope where all would be granted otherwise.

**Comment by Wayland-Smithy** [comment]
Updated the hash to the latest version that includes a fix for blank bodies causing null refs, and allows the removal of a trailing space after the offending emoji special for cyberboss.

**Pull request merged**
