### PR TITLE
Makes ei nath deal 175 brute and 175 burn damage instead of gibbing.

### PR DESCRIPTION
**Pull request by theOperand**
i ded pls nerf

### CODE REVIEW

**Comment by Ergovisavi** [comment]
Don't let your memes be dreams

But seriously, this ability is unfun to fight against and has little to no counterplay options. It's just bad. Yes, wizards are generally supposed to be overpowered, but instantly removing someone from the round 5ever in 0 seconds on a fast cooldown is just dumb.

**Comment by Cebasiz** [comment]
touch range is supposed to be the drawback but in practice touch range is incredibly easy to achieve with magic missile

no weapon the station has effectively fights this combination, especially if you throw in jaunt, oh my goodness

**Comment by Braincake** [comment]
For reference:

Honk

And for the record, I have no particular feelings towards this PR, one way or the other.

**Comment by Miauw62** [comment]
that is literally not relevant tho

**Comment by Anonus** [comment]
Make it also throw them away from the wizard violently, because that'd be cool.

**Comment by Steelpoint** [comment]
The point of Ei Nath is that you confirm the kill by gibbing the body, the spell itself takes a full minute to recharge because of that.

If you want a fast and efficent killing method you go for fire balls, if you want to absolutely ensure your targets never get back into the round then you use ei nath.

This is a bad change in my opinion, a change that is the definition of coding from anger.

**Comment by Dorsisdwarf** [comment]
Ei Nath's base cooldown should be increased to 90 seconds if you're salty. This is a classic and clunky spell which you're removing because, by your own admission, u mad

**Comment by Durkel** [comment]
Ei nath is garbage and needs to be changed or removed. a gibbing spell combined with a auto tracking stun and the antag with the most mobility is just horse shit.

Why is para+c4 bad when it took more skill, more effort, and more cost but this is perfectly fine? If you want a iconic wizard add some actual fucking spells with balance instead of more gimmick shit. (ie, cone of cold, making lightning bolt not shit, and may be a prismatic ray or something.)

**Comment by Steelpoint** [comment]
The only reason disintegrate is being signalled out is from the fact its a very commonly seen spell and that its all but a guaranteed attack that will keep you out of the round. 

The main difference between disintegrate and any other offensive spell the wizard has is that it takes a few extra seconds for any other spell to kill someone while disintegrate is instant but takes a minute to recharge.

**Comment by Jalleo** [comment]
I will say this ei nath would be better if it didnt deetroy all the items on a person when used. Apart from that ei nath is really more of a method to get a quick kill in a chaotic battle to remove the numbers against a single wiz.
A true balance would be the wiz having special robes which has protection scaled to server pop.
Seriously we cant easily balance the spells but we could balance how easily the main antag gets hurt.

**Comment by Incoming5643** [comment]
if you're going to rip out the soul of el nath you might as well kill the body. Leaving it in like this is just sad.

**Comment by Incoming5643** [comment]
I have an idea on how this might be improved, give me a day or two

**Comment by Miauw62** [comment]
im removing it because it's shitty, not because im mad.

it's not clunky at all. the reason melee range is a disadvantage in spacemans is because your opponent can disarm you and dunk you with whatever you're holding, but that is not the case for ei nath.
the only reason i'm not removing this entirely is because it is somewhat iconic. 

if you want a guaranteed kill you will now have to work a little harder for it, abloobloo. it still deals 350 damage that may or may not be affected by armor.

(lol i wrote this a few hours ago but forgot to hit the comment button)

**Comment by Steelpoint** [comment]
If your going to do this (And not post a feedback thread) then just gut Ei Nath from the game. Removing the gibbing aspect of it essentially removes the charm, intent and origin of the ability.

Also, post a feedback thread.

Seriously.

There's more people playing the game than me, myself and I.

They have opinions.

They are valid.

**Comment by Miauw62** [comment]
i actually genuinely forgot to make a feedback thread. sorry.
if incoming's idea works better, merge his. i'm leaving for two weeks tomorrow so i wont be here to update the PR, but i might be able to comment.

**Comment by Durkel** [comment]
The difference between instantly gibbing someone and hitting them with a fireball 4-5 times is much larger then you make it seem.

Think of it this way.

Fireball: six second cooldown. chance of a ko, chance of them catching on fire, and 20 brute damage. Has a high chance of blowing up in your face getting you killed, needs to be aimed.

Lighting bolt: 30 (40?) second cooldown, short stun, needs to be charged, varying damage, and doesn't work on those wearing insulated gloves.

mutate: 40 (60? fuck testing) second cooldown. Hulk+lasers, short peroid where you can't hulk out, eye lasers drain your hunger meter fast.

Ei nath: 60 second cooldown, instant gib, needs to be with in one tile range.

Lighting bolt is a complete joke when compared to something like ei nath, with only mutate and fireball being competitive. This is from a balance perspective, not just that fact getting blown the fuck up is zero fun.

**Comment by KorPhaeron** [comment]
>One guy vs 60 people
>How dare he be able to remove people from the round

As Durkel said at least give him real offensive spells other than EI NATH rather than simply ruining it.

**Comment by Steelpoint** [comment]
Well it took two fireballs to knock the Captain into crit and kill him from when I played last night.

Lightning Bult is unreliable and a gimmick and mutate's just a "get out of jail for free card" that turns you into a hulk.

Do fireball's gib bodies as well? They may have before but who knows what they do now.

Either way, this change really means that there's a chance your body might get cloned if the Wizard has not already blown up genetics.

In fact this might be a buff to Ei Nath as it means now you can steal anything off your victims body instead of it being lost (except for ID cards).

In fact this is actually a big buff to Ei Nath since the big no no on using it was that you would blow up most of the equipment your victim's held aside from their ID card.

**Comment by xxalpha** [comment]
More lethality, not less.

**Comment by Miauw62** [comment]
this is equal lethality, though.

**Comment by Anonus** [comment]
Doesn't lightning bolt stun you if you hold it too long? If it still does that it's bad, and if it actually does nothing to people wearing gloves then that should get changed, too.

**Comment by Anonus** [comment]
Also steelpoint is right, this is a buff to EI NATH because you can use it on a target holding a steal objective to get it easy.

**Comment by Dorsisdwarf** [comment]
EI NATH leaves a brain, thats all you need to get back into the round (but it should probbably drop kit

**Comment by Miauw62** [comment]
technically all you need to get back in the round is being already scanned at genetics so why dont we just remove it dropping a brain.

**Comment by SconesC** [comment]
ei nath leaves a brain

magic man is and always will be bullshit

**Comment by daman997** [comment]
its not like anyone actually works medbay during wiz anyways

**Comment by Xhuis** [comment]
salty

**Comment by Ikarrus** [comment]
>If you want a fast and efficent killing method you go for fire balls, if you want to absolutely ensure your targets never get back into the round then you use ei nath.

I see tou haven't tried to use fireballs lately, because they take forever to kill someone now.

**Comment by Dorsisdwarf** [comment]
:hurtrealbad:

**Comment by SconesC** [comment]
"they don't even gib anymore"

No instead they knock you out, ignite you, and destroy your clothing and shoes

**Comment by Anonus** [comment]
Don't fireballs do like 50 or so damage on a hit, with a chance of knocking out for longer than the cooldown plus fire?

**Comment by Ikarrus** [comment]
But they only deal light damage that doesnt shred clothes. 

They don't burn off until you're husked as well. 

Last time I tried fireball wizard I threw 3 of them directly into an assistant and he just got up and walked away. Its shit.

**Comment by KorPhaeron** [comment]
How do you propose loud wizards keep people dead then (short of killing everyone)?

Simply doing damage to a single target leaves their body to be easily patched and defibbed, probably in around the same time it takes EI NATH to recharge.

Loud wizards don't really have the time (or access, they travel via spell) to take people to the gibber either, they're generally being pursued by a large mob.

**Comment by Incoming5643** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4138#p103690

**Comment by WJohn** [comment]
This would actually be a useful buff, as it'd let you strip the bodies. Disintegrate's gibbing destroys some of the equipment you may need, making you fail your objective. Of course, it can be argued that it's meant to be situationally used to get rid of people you don't care for.

Of course, whether this spell actually DESERVES a buff or not I'm not gonna try to make a point for or against.

**Comment by WJohn** [comment]
Also, as others have asked, maybe we can keep the iconic "look" of this spell around in some way? Maybe make it leave a lightning trail and send them flying off into the distance. It won't be quite as dramatic as them EXPLODING, but it'll definitely still look very cool rather than just collapsing.

**Comment by Lumipharon** [comment]
>Last time I tried fireball wizard I threw 3 of them directly into an assistant and he just got up and walked away. Its shit. 

Last time I got fireballed, I was hit once at full health, and died as I was extinguishing the fire, because the KO was so long.


As for Ei-nath, I hnestly don't think the gibbing part is the problem.
What IS the problem, is that you can use it while stunned, and with no direct interaction with the target.
Anyone going near you is asking to be be gibbed.

If the wizard had to actually GRAB their target to be able to gib them, them it would be far, far less bullshit.
Sure, you'd be able to MM someone then ei-nath them still, but there would be no more gibbing people who are trying to cuff/kill you, while you are stunned on the floor, or running past someone and gibbing them.

**Comment by Fox-McCloud** [comment]
Ei Nath also leaves their brain for a reason...

**Comment by KorPhaeron** [comment]
The wizard needs to be able to fight while stunned though. It's one guy vs the entire station, a single stun shouldn't be the end of him

**Comment by bustygoku** [comment]
I agree but there's an anti-stun ability called mutate exactly for that Kor

**Comment by Lumipharon** [comment]
Every other spell they have works while stunned.

MM
Knockback
Jaunt
blink
teleport
just being HALK to ignre stuns completely, etc

The difference is, no other spell is a 1 click ggnore.

**Comment by Ergovisavi** [comment]
>Ei Nath leaves a brain!

...That you can pick up, put in your backpack and throw out an airlock shortly thereafter.

**Comment by bustygoku** [comment]
>not making brain cakes

**Comment by Fox-McCloud** [comment]
@Ergovisavi 

I think you misinterpreted what I was getting at; it wasn't so much that "see, you're not being taken out of the round forever!" ('cause I agree that that's what Ei Nath does).

It was more "this exists so that 'steal a brian' isn't virtually impossible."

**Comment by WJohn** [comment]
Even if the current ei nath leaves a brain it's still basically a guaranteed removal from the round. What are the odds that you, among the 20 ei nath'd victims, actually gets picked up by a doctor who has the time and resources to swap your brains out with a human'd monkey and either clone or defib you? Basically zero.

**Comment by Fox-McCloud** [comment]
@WJohn 

...I know. My point had nothing to with "SEE YOU'RE STILL IN THE ROUND!"; it was entirely "this exists because of the debrain objective".

**Comment by Steelpoint** [comment]
Don't forget that when stunned the attack only works if someone is right next to you.

So long as they keep that one tile distance from you you cannot do jack squat.

**Comment by Miauw62** [comment]
Yeah and what are they going to do with you if they can't come near you,
wait until your jaunt recharges so you can fuck off?
What I'm trying to achieve is to kill the cancerous ei nath+MM+jaunt combo,
because there is zero counterplay against it, you might as well gib a
random person every minute when wizard is picked. This probably doesn't
solve that, but at least it gives people a chance to get back into the
round and means the wizard has to make himself vulnerable if he wants to
permanently remove a body.
Op 13-jul.-2015 08:26 schreef "Steelpoint" <notifications@github.com>:

**Comment by Steelpoint** [comment]
If there's a clear and effective counterplay to any tactic a wizard chose's then wizards will simply fail.

A very good player who is a wizard is almost impossible to stop, irrespective if they are using disintegrate or fireball or whatever other spell. Wizard's fail because either the player makes a miscalculation and screws up or another very good player outplays them, usually involving powerful equipment like bombs or acid.

If this change goes through, then it will change almost nothing balance wise because you fail to understand how wizard's win. They win by being good players.

All this does is kill off a iconic ability because your angry over a some bad rounds with a good wizard player.

Because a good wizard player will make sure genetics is never allowed to clone the dead for example.

**Comment by Lumipharon** [comment]
If you're making this change to try stop ye olde ei-nath, MM, jaunt, blink combo, this does not do that. At all.
175 of brute AND burn makes it impractical to defib people, unless you've got two chemists literally shitting out patches non stop (also patches working on corpses is super fucking cheese).

So unless you have half a dozen cloners and/or up to your ears in borg bodies, this isn't goin to help keep people in the round.

It will only prevent the wizard from keeping a SPECIFIC person out of the round (throwing the brain away).

**Comment by Ergovisavi** [comment]
@Lumipharon 
You do realize that you can defib someone so long as they don't have 180+ Brute OR Burn? You can have 179 Brute and 179 Burn, and still be revived because it heals your limbs. Zapping someone with Shocking Grasp will just mean that someone can get them up with a defib, unless you go out of your way to damage the corpse thereafter.

**Comment by WJohn** [comment]
Or if that person has been sneezed on before being shocked.

**Comment by Steelpoint** [comment]
Also to retort Miauw.

The go to tactic in fighting wizards, for years, has been to use ranged weaponry on a lethal setting.

Stunning a Wizard is a waste of energy since the wizard would still be able to defend itself (even with fireballs!) and could easily teleport away at a moments notice. What you had to do was empty lethal weaponry on a wizard until it stopped moving. 

Walking up next to a wizard, and being killed, is no one's fault but your own for forgetting the wizard is one of the single most powerful beings in the game.

In short, and as you often say, git gud.

**Comment by Dorsisdwarf** [comment]
Agreed. The Wizard is, and should be, the single most deadly combat entity in the game (excluding ascendant shadowlings obviously). If you try and face a wizard alone, tough nuts. Wizards should be downed by either a swarm of bodies wielding toolboxes, too many to overcome, or a hail of laser fire, sometimes with an exploding hallway trap or maxcap jihad. The only comparable entity is the malf AI, which has little/no combat of it's own barring emergency mech downloads, but rather uses the station against the crew, and sits guarded by unstunnable weapons with the potential for an army of unstoppable killbots.

If you go up against a wizard alone, damn right he should permanently remove your ass from the game (If he remembers/can be bothered to pick up your brain). Some gamemodes can't be soloed with a stunprod and cablecuffs, and Wizard is definitely one of them. (Unless he's a memewizard who takes all the summons and Mindswap)

**Comment by KorPhaeron** [comment]
The best way to kill the MM+EI NATH combo is to add fun alternatives to it.

It used to be taken near 100% of wizard rounds, but after all the artefacts/global summons/new spells it's dropped to taking EI NATH in only 1/3 of rounds. 

Hating MM+EI NATH was my entire motivation for adding new things to wizard, but I never tried to remove it outright. If players want to play their 1vs60 that is their choice.

**Comment by Nanotransistor** [comment]
I would prefer if you guys stop nerfing shit after being killed by it.

**Comment by Miauw62** [comment]
So wizards should lose by being swarmed, but spells like Repulse are a
thing? Also, it's not like there aren't three separate spells plus an item
they get for free to teleport away.

And while losing by being swarmed to assistants with melee weapons while
the main tactic is lasering them from a distance, the all versus one antag
is also defeated by a single good player?

And it's not like ei nath+mm+jaunt requires any skill.
Maybe this isn't the best way to kill that cancercombo, but right now I'm
on vacation, so hopefully somebody else will think of a more elegant
solution.
(BTW, if this still allows you to be defibbed, that's not intended.)
Op 13-jul.-2015 18:01 schreef "Dorsisdwarf" <notifications@github.com>:

**Comment by Miauw62** [comment]
Also, Kor, there is no reason we can't both nerf this combo and add other
cool things, as evidenced by the lightning bolt buff in another PR.

(maybe adding wizardcrystals could also be used to encourage people taking
some of the underused spells by making them cheaper. You could also buff
them of course, but idk what you'd do for for example smoke)
Op 13-jul.-2015 18:04 schreef "KorPhaeron" <notifications@github.com>:

**Comment by Steelpoint** [comment]
I've been saying that for a long time now!

Swapping our Wizard Spell Points system for a Telecrystal like system would allow us to actual balance powers more effectively. 

Right now a smoke spell is as expensive as a disintegrate spell. Which means its impossible to balance abilities on based on purchasing them. 

That system might even allow us to balance out upgrading skills so its not as expensive to do so.

**Comment by Robustin** [comment]
Wizard is a shit concept wrapped up in a slew of shit mechanics. Solo antags will always have deep flaws that are almost impossible to remedy.

But we definitely expressed a desire for more lethality and this nerf stands in contrast to that. Nerfing Ei Nath isn't even going to come remotely close to fixing wizard and right there's far more broken shit in the wizard arsenal anyway.

People don't seem to grasp that if you make an antag capable of fighting 60 people alone, then the average crewmember's experience with that antag is going be "hopelessly steamrolled", ei nath doesn't change that at all. At the very least it gives wizards a chance to just bloody remove someone from the round so they don't have Mr. Patch & Shock bringing them back in 30 seconds.

**Comment by Miauw62** [comment]
The general lethality sentiment doesn't mean that we can't still remove or
fix broken shit. Wizard has many other less frustrating ways to kill people
with more counterplay.
Op 13-jul.-2015 20:02 schreef "Robustin" <notifications@github.com>:

**Comment by KorPhaeron** [comment]
Your change doesn't add any "counterplay" at all though, he can still instantly kill you from going near him (not that I believe it's a problem that someone tasked with killing 60 people all by himself with no extra durability can do so)

**Comment by bustygoku** [comment]
I think the proposed alternative "God Hand" change is much more well thought through.

**Comment by Lumipharon** [comment]
your change literally does nothing to fix the issue though.

Changing it so it requires a grab, or make the ei-nath hand attack thing, both would actually address the issue.

**Comment by Robustin** [comment]
Ei nath has just as much counterplay as any other decent combat spell setup. MM + Harmful spell is the same result with the same amount of counterplay, none beyond just staying the hell away from a wizard.

**Pull request closed without merging**
