### PR TITLE
balances 12g slugs

### PR DESCRIPTION
**Pull request by Timonkeyn**
## About The Pull Request

halfes the damage of 12g slugs
## Why It's Good For The Game

being put in orange just because you didnt dodge 1 bullet isnt fun now is it
## Changelog
:cl:Timonk
balance: halfs the damage of 12g slugs
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
if you want to not go orange why not set it to 55?

**Comment by wesoda25** [comment]
bad

**Comment by Dorsisdwarf** [comment]
Ided

**Comment by Timonkeyn** [comment]
why would you want a shotgun to do as much damage as a penetrator round

**Comment by Timonkeyn** [comment]
at the same range as a sniper rifle

**Comment by Timonkeyn** [comment]
another comparison: its as strong as a .357, you can load more of it into a riot shotgun than a revolver, which is pretty busted

**Comment by nemvar** [comment]
Set it to 39.9. The most based number of them all.

**Comment by MadmanMartian** [comment]
2 shots of a slug is enough to put you fairly far into crit. That seems a bit much for something presumably common.

How does it compare to other rounds?

**Comment by Timonkeyn** [comment]
> 2 shots of a slug is enough to put you fairly far into crit. That seems a bit much for something presumably common.
> 
> How does it compare to other rounds?

i just said that

**Comment by imsxz** [comment]
i agree with slug nerf but idk if this nerfis the way to go about it. slugs are the only shell worth using next to some of the tech shells.

**Comment by Timonkeyn** [comment]
> i agree with slug nerf but idk if this nerfis the way to go about it. slugs are the only shell worth using next to some of the tech shells.

i mean, buckshot 2 shots when you are in melee range

**Comment by MadmanMartian** [comment]
I'm asking because nerfing one thing will just make people move to the next thing. Get some number comparisons and try to predict where people will move to next

**Comment by dr-bee** [comment]
if you are going to nerf it, bring it down to 50, as mentioned above, this leaves it at a 2 shot down to unarmored targets but allows anyone with armor to survive 2.

A nerf really isnt needed however. Slugs are as powerful as a .357 yes but have the disadvantage of both the gun being bulky and the ammo being small. Shotguns also take significantly longer to reload than the .357 is with the speedloaders they can buy. Overall this makes slugs a powerful tool but not one that is as good as traitor gear, which is where I think it should be.

**Comment by Shapsy** [comment]
It's a shotgun, it's supposed to be dangerous

>being put in orange just because you didnt dodge 1 bullet isnt fun now is it

dying usually isn't fun, try avoiding it

**Comment by necromanceranne** [comment]
You can't even use slugs effectively in sawn-offs either so you will almost always see this coming if the guy has a shotgun and didn't get metaops and replace the buckshot magazines with slugs.

Also, speaking of the bulldog, worth considering that slugs are something you can get in nukie uploads at a price increase per magazine compared to buckshot, so why on earth would they ever buy them when a revolver exists? Why would they use slugs when their stechkins, which ops get free magazines to use, does the exact same amount of damage?

If the idea was that the slugs carried some other properties that made them appealing, like armor penetration or something, then maybe the damage reduction would make sense. This is just blatant ided without really considering the balance of the change in comparison to the balance of everything around it.

**Comment by optimumtact** [comment]
it's better off to balance the shotgun by making it required to be twohanded to fire.

**Comment by ishitbyabullet** [comment]
I'd like that if the inhand sprite would no longer look like you're holding a staff or big stick. While the new inhand sprite is nice, it can feel kinda weird tbh.

**Comment by Shirbu** [comment]
`/obj/item/projectile/bullet/c10mm
	name = "10mm bullet"
	damage = 30`
Shotgun slugs will become as weak as stetchkin pistol bullets.

**Comment by optimumtact** [comment]
action has a better two handed inhand, but doesn't want to do the work to make it an offhand

**Comment by Timonkeyn** [comment]
@optimumtact shotgun hand

it wont fly off that way

**Pull request closed without merging**
