### PR TITLE
Gives Syndicate cyborgs an operative pinpointer module

### PR DESCRIPTION
**Pull request by ghost**
~~I'm not sure why this didn't exist anyway. Syndicate cyborgs are made null and void if the rest of the ops are dead because they're stuck to guessing. They're a part of a nuke op team and as such they should have pinpointers.~~

This has been changed. Instead of nuclear disks, the pinpointer that borgs get leads to other nuke ops. This makes it easier for them to coordinate with their team while not removing their reliance on them.

### CODE REVIEW

**Comment by tkdrg** [comment]
I don't really agree with you, to be honest. Syndieborgs are already too good as is, I don't think we should be buffing them even more.

**Comment by Steelpoint** [comment]
I think the reason they did not get pin pointers is to make them still somewhat reliant on sticking with a Op player.

**Comment by Cheridan** [comment]
In the end, they're still reliant on an Op to use the disc on the nuke to win.

Syndiborgs need a nerf, but this is a basic navigation and usability thing.

**Comment by vista-** [comment]
I intended he syndieborg as a support role and not having a pinpointed kinda forces them to stick with ops. :-1:

**Comment by Miauw62** [comment]
i agree with vista, syndieborgs having to stay close to the ops is a good thing.

**Comment by Cheridan** [comment]
Vista, it's impossible for them to fulfill any role at all if they get separated and lost.

Maybe we could give them a different type of pinpointer, which points in the direction of the nearest Operative?

**Comment by Xhuis** [comment]
That doesn't make much sense to me. If operatives are alive, all they need to do is talk over the radio to coordinate with their team. It just doesn't seem sensible for a member of a nuclear squad to have no way of finding their objective. Yes, it's important to stick with the ops (because otherwise they die easily to EMP and flashes) but I feel that it's also important to have a way of finding their prime objective.

**Comment by tkdrg** [comment]
> they forgot their pinpointer

They deserve to lose, then. Incompetence shouldn't be rewarded. Syndieborgs are a tool, not a team member.

**Comment by Xhuis** [comment]
How about a pinpointer that draws heavily from the cyborg's power while active (say, 100 every two seconds)? That way if they stick with ops there's no change but they can also find the disk on their own (albeit at a heavy cost).

**Comment by SconesC** [comment]
Syndicate Cyborgs should not have a pinpointer.
They are a fire support unit for opening doors/killing the AI, not for hunting down the disk-holder and dragging them back to the team
If that was the case you could just buy 2 and send them off with pinpointers while the actual ops just murderbone up a storm

**Comment by TheVekter** [comment]
They can't even pick it up. No, I don't agree with this. I think they're already broken as it is. Don't give them a pinpointer they can't fucking drop.

**Comment by paprka** [comment]
:-1:

**Comment by Cheridan** [comment]
Due to some disagreement on this PR I've gone ahead and made a poll: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=2718

**Comment by Xhuis** [comment]
Working on an operative pinpointer now.

**Comment by Xhuis** [comment]
Just finished the operative pinpointer. It seems to have no issues ingame.

**Comment by Miauw62** [comment]
everybody seems to like this, so here we go.

**Pull request merged**
