### PR TITLE
HoP/QM have access to vault

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: The Quartermaster and HoP can now access the vault so they can use the bank machine.
/:cl:

Why: The bank machine and soon the global magic bluespace ore machine will be in the vault, the supply heads need access to those machines and nobody else ever uses the vault anyway.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
>the ore machine will be in the vault
🤣

**Comment by davethwave** [comment]
Those poor miners...

**Comment by SgtxRootbeer** [comment]
Didn't robustin or goofball try giving the qm access to the vault and everyone and their brother shot him down because powercreep or some shit?

Regardless, kor, re-enable coin accepting on the bank machine pls. Good disabled it because he was autistic and it needs fixing

**Comment by nichlas0010** [comment]
Might wanna remove the document objective for QM/HoP then

**Comment by 81Denton** [comment]
@KorPhaeron You'll have to remove `/obj/effect/mapping_helpers/airlock/locked` on vault door tiles as well so they don't start bolted. Otherwise they'd have to hack the door or steal the cap's command remote.

**Comment by YakumoChen** [comment]
>QM should have access to a command level room

>implication that the QM is a real head of staff

**Comment by Tlaltecuhtli** [comment]
qm is more head than a  cmo

**Comment by RandomMarine** [comment]
I can imagine all the IC-issues caused through confusion regarding whether or not the QM/HoP is allowed to ~~embezzle~~ repurpose the vault funds.

**Comment by ExcessiveUseOfCobblestone** [comment]
rename QM to Financial Administrator.

>Might wanna remove the document objective for QM/HoP then

Do we remove the slime extract/CE boots/etc. for the other jobs?

@KorPhaeron 

>Regardless, kor, re-enable coin accepting on the bank machine pls. Good disabled it because he was autistic and it needs fixing

**Comment by 81Denton** [comment]
Right I should read the code before commenting

**Comment by ExcessiveUseOfCobblestone** [comment]
No fun doing that.

**Comment by yoyobatty** [comment]
>vault
>strongest door in the game
>hard to even thermite into
>contains 1 tator objective
>and maybe a self destruct that nobody uses

I approve

**Comment by nichlas0010** [comment]
>Do we remove the slime extract/CE boots/etc. for the other jobs?

https://github.com/tgstation/tgstation/blob/2410681234c6fb8b0b21154e9d9913ee848889b4/code/game/gamemodes/objective_items.dm#L32

yes.

**Comment by Expletive** [comment]
I tried this with #27112, and people didn't like it. If you're doing this, won't the AI have to unbolt the doors? Unless you give the supply door remote the required access.

**Comment by BeeSting12** [comment]
@Expletive this pr makes the supply door remote have the access

whats really funny is i told kor the exact same thing on your PR. i dont even remember arguing on that but apparently i did

**Review by SpaceManiac — DISMISSED** [review]

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
