### PR TITLE
My daddy taught me to be proud of my moonlighting

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
fuck yes please merge

**Comment by LaharlMontogmmery** [comment]
Here, in /tg/station, we nurture our memes with love and compassion.

**Comment by Durkel** [comment]
>be coder
>maintainer spergs out on me and tries to whack me with a ban, all while screaming "REEEEEEEEEEEEEEEE, CODERS GET OUT"
>He gets sent to gulag for 1000 points to think on his behavior.

**Comment by Sligneris** [comment]
you should unironically add "minign deservs nuthin!!!" tbh

**Pull request closed without merging**
