### PR TITLE
Removes a extra assignment

### LINKED ISSUE #79739: the recipe for tirimol has its optimal temperature defined twice
as both 1 degree Kelvin and 900 degrees Kelvin

### PR DESCRIPTION
**Pull request by Bilbo367**
## About The Pull Request

Removes extra assignment, should have no functionality change.

## Why It's Good For The Game

Closes https://github.com/tgstation/tgstation/issues/79739

### CODE REVIEW

**Comment by Bilbo367** [comment]
This is my first PR

**Comment by san7890** [comment]
Thank you for the PR. The changelog is a player-facing thing, and the changelog the way you had it was completely useless information to have there (no fault of your own). Just best to leave it out imo, anyone who cares about the issue will notice that the report was closed.

**Comment by san7890** [comment]
it's not redundant, it's just that if a player uses the `changelog` verb in game and reads "removes extra assignment", it's not useful information at all (it's probably not even useful to coders).

However, something that would read "fix: Making tirimol should be more consistent." would certainly be more useful information for players to have. If you really want to, you can re-add the changelog field to your PR body and have something similar to this example I just gave you, but it's not truly necessary in this instance.

**Comment by Bilbo367** [comment]
Ok i understand much better now thanks!

**Pull request merged**
