### PR TITLE
Moves the smoke machine board back to Chemistry

### PR DESCRIPTION
**Pull request by Robustin**
What the fuck I didn't spend so long coding that shit so Bawhoppen could get his removal PR merged within 12 hours without even offering an explanation.

Fuck

That 

Shit

### CODE REVIEW

**Comment by Bawhoppen** [comment]
No kneejerk reverts is a repo policy

**Comment by Cyberboss** [comment]
Mmmm, hacking into tech storage isn't hard if they don't give it to you when you ask for em.

**Comment by Cyberboss** [comment]
Also that pr was open a whole day

**Comment by Bawhoppen** [comment]
Here's you explanation:
It's supposed to be engineer's jobs to build stuff. Not a chemist's. Adding it directly to chemistry is powergame 101.

Also it wasn't even a removal.

**Comment by Robustin** [comment]
What the fuck is even powergamey about it.

The most useful thing I found for it was mass carpeting and mass cleaning.

**Comment by jughu** [comment]
What people think that happened
Now they wont powercreep anymore

What auctally happened
Scientists rush tech tool storage for a boost

**Pull request closed without merging**
