### PR TITLE
Drone asses!

### PR DESCRIPTION
**Pull request by ghost**
Give drone the ability to photocopy their asses!

### CODE REVIEW

**Comment by Chocobro** [comment]
oh my god

**Comment by Cebasiz** [comment]
incredible, best PR in decades, 10/10 will drastically improve game

**Comment by Ahammer18** [comment]
mods pls sticky

**Comment by Miauw62** [comment]
as the original author of ass copy, :+1:

**Comment by RemieRichards** [comment]
As the adoptive mother of drones: :S

**Comment by bgobandit** [comment]
https://github.com/tgstation/-tg-station/issues/6664

**Comment by francinum** [comment]
:+1: X :100:

**Comment by Cheridan** [comment]
retarded

**Comment by Cheridan** [comment]
also
>that changelog

**Pull request merged**
