### PR TITLE
Cameras now use timSort instead of insertionsort

### PR DESCRIPTION
**Pull request by optimumtact**
Changes the camera sort to use sortTim instead of it's own handrolled insertion sort.

### CODE REVIEW

**Comment by BebeYoshi** [comment]
Good choice of sorting algorithm!

**Review by SpaceManiac — APPROVED** [review]

**Comment by SpaceManiac** [comment]
> \<Naksu> SpaceManiac: i'm not sure there's a positive performance impact to using sortTim() over an inlined sorting function
> \<Naksu> the timsort in theory has better scaling, but the whole system is a huge mess of creating procholder datum instances and proccalls
> \<Naksu> depending on the number of items in that list it's faster to sort it in-place with an unoptimized function than to call a proc to make a comparison even once

**Comment by optimumtact** [comment]
wow I can't even get a pr merged on my own repo

**Comment by optimumtact** [comment]
wow I can't even get a pr merged on my own repo

**Pull request closed without merging**
