### PR TITLE
Adds a message_admins() when a flamethrower is lit

### PR DESCRIPTION
**Pull request by tkdrg**
Griff etc

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Should make it only happen once per-flamethrower, other wise you get spam.

**Comment by tkdrg** [comment]
Done.

**Comment by FlavoredCactus** [comment]
Now what happens if someone uses someone else's lit flamethrower after it warned? what about a cooldown on warning?

**Comment by tkdrg** [comment]
Well, it's still logged to attack logs, etc. It just won't message admins anymore. But sure, I can add a cooldown later.

**Pull request merged**
