### PR TITLE
Circuitry lab changes

### PR DESCRIPTION
**Pull request by Garen7**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Garen
add: Added a cell charger to the circuitry lab on all stations.
add: Added a circuitry lab to the syndicate lavaland base.
tweak: Modified the meta station circuitry lab.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I added a cell charger to all the circuitry labs since if someone is making a lot of circuits then they will need to charge a cell for each circuit bot. I've even seen a scientist unwrench the cell charger from rnd to drag it to circuits so this is just to avoid the whole process of charging cells in rnd and make stealing all the starter cells less annoying.
I added a circuit lab to the syndicate lavaland base since the base has always been about experimenting with ingame systems so I thought it would fit in here. Circuit throwers can't throw humans so it shouldn't be able to help someone escape. The room has only whats needed since there wasn't much space on the map.
screenshot 4screenshot 5

I modified the metastation circuitry lab for a lot of reasons:
1. the library console would block you in if someones trying to baton you and the library console faced the wall so I moved it to somewhere where it looked and felt better.
2. people would run into the maint door a lot by accident which was a distraction and pretty annoying so I expanded the north room by one tile so I could move the door out of the corner
3. the windows lacked protective grills and would break a lot because of space debris, so I added a small protective grill.
screenshot 10

### CODE REVIEW

**Comment by AverageJoe82** [comment]
First time doing map work, I think I did the map merge right.

**Comment by SpaceManiac** [comment]
Maps merged fine. Did you mean to put a cell charger in the syndicate base too, or do you figure the rest of the base has enough? Otherwise looks good.

**Comment by AverageJoe82** [comment]
I was low on space and I didn't want to crowd people so I skipped on it. I figured you don't need lots of cells if you're just testing/making circuits. and also sweet

**Comment by 81Denton** [comment]
@AverageJoe82 If I was you, I'd just add a cell charger board (/obj/item/circuitboard/machine/cell_charger) to the syndie crate that has the circuit boards and stock parts. Then syndies can build a charger, if they ever need it.

**Comment by SpinnerMaster** [comment]
Awesome, comfy circuit experimentation now on lavaland!

**Comment by YakumoChen** [comment]
Can you give the syndie base the advanced disk by default?

**Comment by AverageJoe82** [comment]
The printers are already upgraded so there’s no need for the disks

**Pull request merged**
