### PR TITLE
Fixes chameleon projectors accepting bad sprites (most of the time)

### LINKED ISSUE #19364: Chameleon projector can copy broken sprites.
If you order a chameleon kit and projector, then you can just transform the item into any of the many broken sprites. After which, you just drop it & alt click to copy it. Afterwards you are basically impossible to find and kill.

### PR DESCRIPTION
**Pull request by silicons**
Fixes #19364

### CODE REVIEW

**Comment by PKPenguin321** [comment]
This won't cover cases where a dmi is modified without appropriately changing icon_state, which is where a lot of our broken sprites come from, so I don't know if this is a true fix. I still like this though because it prevents any broken sprites on erroneously accessible debug items that intentionally have no sprite. :+1:

**Comment by kevinz000** [comment]
@PKPenguin321 I don't know of a way to check for images that have nothing in them, so this is the best I can do I guess..

**Comment by AnturK** [comment]
icon_states() proc is a thing

**Comment by kevinz000** [comment]
@AnturK how would I use it to check for no sprite?

**Comment by AnturK** [comment]
```
if(icon_state in icon_states(icon))
 //do things
else
 //don't do things.
```

**Comment by kevinz000** [comment]
@optimumtact fixed kek.

**Pull request merged**
