### PR TITLE
IC OOC detection fixes

### LINKED ISSUE #13349: MAXIMUM GAME BREAKING SERVER CRASH BUG
incomingpls

@Incoming5643 anyway to fix this?

### LINKED ISSUE #13353: Hitting Yes on the Are you sure you want to say this in OOC for the IC in OOC safety doesn't actually send the message to OOC
@Incoming5643

### PR DESCRIPTION
**Pull request by Incoming5643**
emoji parsing now happens before IC OOC checks.

Fixes #13349

<s>Changes up how OOC checks to see that you agreed that a message isn't accidental IC.

<s>It now passes a special string, "|~|", in front of your message and runs it through OOC again. The string saves the message from further scrutiny, and is then cut off. A "cool kid" could manually insert the |~| to tell the parser to ignore the IC OOC check, but this is pretty much harmless. 

<s>Fixes #13353

### CODE REVIEW

**Comment by MrStonedOne** [comment]
You could actually fix easier by just making the ic/ooc check come after the emoji parser i think....

**Comment by Incoming5643** [comment]
Good idea but I think there's a slight issue with that:

The order right now is ICOOC check --> ooc log --> emoji parser. 

I think the ooc log has to be before the emoji parser because otherwise the message already includes an emoji that can't be in a plaintext log, but if we put the ICOOC check after the logging step it would record messages that might not actually end up being sent.

**Comment by MrStonedOne** [comment]
just make a var with the raw text to log

**Comment by Incoming5643** [comment]
the issue with ooc messages not sending if you said they weren't IC OOC has been resolved by being revealed as not an issue at all, and the fix has been dropped

**Pull request merged**
