### PR TITLE
Makes Nar-Sian magic more effective against servants

### PR DESCRIPTION
**Pull request by ghost**
A full list can be found below.
- Picking up an eldritch longsword will deal extreme brute damage to servants and force them to drop it.
- Sacrificial daggers add heparin to struck servants.
- Puttong on armor or robes will deal brute damage to servants and force it off of them.
- The Convert rune stuns servants for four seconds, successful or not.
- The Blood Boil rune deals 30 stamina damage to servants in addition to its normal damage.
- Stun talismans deal 15 brute damage to servants.
- Horror talismans confuse and flash the eyes of servants.

**Token: #18446**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
"servants" being ratvar dudes right?

**Comment by Xhuis** [comment]
Yeah

**Comment by KorPhaeron** [comment]
@coiax

Does more special role checks interfere with datum antags?

**Comment by coiax** [comment]
No, using clearly signposted iscultist, isservant_of_ratvar is fine, because the procs will stay. The backend ~~may~~ will change, but this is fine.

**Pull request merged**
