### PR TITLE
Removes duplicate chair on Meta

### LINKED ISSUE #54553: this chair on meta is still double stacked
## Reproduction:

image
image

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
This PR removes a duplicate chair on Metastation.

## Why It's Good For The Game
Closes: #54553

## Changelog
:cl: Denton
fix: Removed a duplicate chair on Metastation.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Improve don’t remove

**Comment by trollbreeder** [comment]
I agree with mr killer tomato, the chair should be moved somewhere else that isn't on top of another chair instead of deleted

**Comment by nightred** [comment]
> I agree with mr killer tomato, the chair should be moved somewhere else that isn't on top of another chair instead of deleted

It was moved to the trashcan.

**Review by Mothblocks — APPROVED** [review]
fucking backspace coders.....

**Pull request merged**
