### PR TITLE
Removes reference to New Zealand from Pavlova description.

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

Oranges called me a desert dwelling emu fucker. This is my revenge.

## Why It's Good For The Game

Uhhhhhhhhhhhhhhhhhh

## Changelog

:cl:
spellcheck: Flavor text adjustment to the dessert Pavlova.
/:cl:

### CODE REVIEW

**Comment by Blacklist897** [comment]
Silence permabanned

**Comment by carshalash** [comment]
> Silence permabanned

SEPARATION OF CHURCH AND STATE.

**Comment by MrMelbert** [comment]
Let him cook

**Comment by JohnFulpWillard** [comment]
you're risking all our jobs you don't know what you are doing

**Pull request closed without merging**
