### PR TITLE
Fixes the description for the mouse being incredibly rude, judgmental, and insulting towards mice, who are objectively adorable.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Fixes the description for the mouse being incredibly rude, judgmental, and insulting towards mice, who are objectively adorable.

## Why It's Good For The Game

I mean, just look at these little guys, aren't they just adorable? How can we be so mean to such friendly animals? We're nice to cats, we should be nice to mice too.

main-qimg-b0775b6713e6b02879543cc3ed9bbe21

## Changelog
:cl:
fix: Fixes the description for mice being incredibly rude, judgmental, and insulting towards mice, who are objectively adorable.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
image
you call this cute?

**Comment by Jamarkus127** [comment]
mice are actually fucking disease ridden rodents who shit everywhere, chew through wires, and eat all your food. fuck mice this PR is false.

**Comment by ArcaneDefence** [comment]
>fix

**Comment by ArcaneMusic** [comment]
Mice are fun adorable little rodenta. Rats are evil disease written monsters who spread the plague and have no value to society. We distinguished it in the code over a year ago

**Comment by Farquaar** [comment]
Leave the original description alone. The humour lies in the juxtaposition between the cute sprite and nasty words used to describe it.

**Comment by CRITAWAKETS** [comment]
Ew, a mouse lover? Mice are horrid pets and keep biting you when you try to handle em.
Rats are the truely cute rodents which awe so cwute :).

**Comment by Wallemations** [comment]
> image
> 
> you call this cute?


funnyanimals.zaybo.com

**Pull request merged**
