### PR TITLE
[READY] Reverts "Radiation suit lockers in atmos, moves pipe dispensers," and adds a 3rd atmos tech locker and rad locker to the incinerator.

### PR DESCRIPTION
**Pull request by pireamaineach**
Maybe tearing up things that have been there for ages and moving them into random places around the station when you could easily just put the thing you're replacing them with somewhere else.
Meaning MAYBE moving the pipe dispensers for the sake of rad lockers wasn't the best idea.

Meta:
MetaIncin
(Outdated image but left in place to contextualise conversation, scroll down for the updated version.)
Box:
BoxIncin

Pubby:
PubbyIncin

## Changelog
:cl:
add: Added a 3rd atmos tech locker and rad locker to the incinerators on Meta and Box, and an atmos tech locker to the incinerator on Pubby since it already had a rad-suit.
del: Reverts https://github.com/tgstation/tgstation/pull/43557
tweak: Makes the doors to the incinerator on meta require atmos access.
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
Mapdiffbot is still AWOL, please show how it looks like.

**Comment by pireamaineach** [comment]
Will in a minute I guess.

You only get the incinerator though because everything else is just reverts.

**Comment by pireamaineach** [comment]
@Barhandar 
She's done.

**Comment by MrFluffster** [comment]
Note that the incinerator on Meta and Box is open to ANYONE with maint access so any assistant can just come in and steal the rad suit. And the atmos locker to open it up later.

Very bad placement of the plasma tank on Box too. Being in a corner is fine but the console to the right of it kinda ruins the placement.

**Comment by Nickkoranda** [comment]
>Note that the incinerator on Meta and Box is open to ANYONE with maint access so any assistant can just come in and steal the rad suit. And the atmos locker to open it up later.

On meta the room between engineering and the gravity generator there is two rad suit storage, and anybody with maint access can steal them.

**Comment by MrFluffster** [comment]
> On meta the room between engineering and the gravity generator there is two rad suit storage, and anybody with maint access can steal them.

That is true, but the atmos locker point still stands and I don't think maint needs an extra rad suit.

**Comment by pireamaineach** [comment]
Honestly that's moreso reason to change that door's access. Actually, I'm fairly sure that door don't public maint access.

**Comment by MrFluffster** [comment]
> Honestly that's moreso reason to change that door's access. Actually, I'm fairly sure that door isn't public maint access.

It is, that's why it's common practice for atmos techs to put up a wall and atmos-access door in that area of maint. Main reason to steal an RCD really.

**Comment by pireamaineach** [comment]
Actually confirmed that's not the case, at least on box.

**Comment by pireamaineach** [comment]
Made some notable changes including fixing the fact that incinerator access on meta is public, posting pictures so.


Also added some flavour floor patterning on box and moved the toxins tank out of the corner.

**Comment by pireamaineach** [comment]
@MrFluffster 
Here she is, boss.
newboxincin

Fixed the door on meta too.

**Comment by ExcessiveUseOfCobblestone** [comment]
i'm merging this PR without the sas

**Comment by pireamaineach** [comment]
Thankies papa.

**Pull request merged**
