### PR TITLE
Vote System: Approval Voting

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
Approval Voting is a system in which voters can select as many maps as they want, instead of selecting only one.

Final tallies show how many votes each map received, and the winner is the map with the most support.

https://user-images.githubusercontent.com/83487515/218571565-73bbe5d1-8f91-440a-acaf-27ed0cc88bfb.mp4

## Why It's Good For The Game
First-past-the-post (our current voting system) has flaws such as creating a bunch of wasted votes, in that a large number of selections ultimately have no impact and for example, a map can win a 3 way race 11/10/10, even though 2/3 of the votes were not for that map. This leads to people having to vote strategically, and perhaps not what their true choice is.

Approval Voting solves this by instead allowing the player to select all the maps they would like to play, so they can vote for their true preferred choice, as well as alternates.

For example, a player that wants Metastation, is okay with Icebox, and doesn't want Delta may feel pressured to vote Icebox if it's in a 2 way race with Delta.

AV lets them vote for Meta, and Icebox or as many others as they want as their alternates and creates a more fair outcome of a map vote.

## Changelog

:cl: LT3
balance: Map votes are now calculated using AV (approval voting) instead of FPTP (first-past-the-post)
/:cl:

### CODE REVIEW

**Comment by castawaynont** [comment]
Joe Biden

**Comment by JohnFulpWillard** [comment]
Joe Biden

**Review by JohnFulpWillard — CHANGES_REQUESTED** [review]
It should be obvious what maps you've voted for then. Maybe make the button red and say 'Unvote' if you've voted for it?

Also you really gotta wait until after Feature Freeze for this

**Comment by optimumtact** [comment]
Does this maintain the functionality of previously run maps not appearing in the voting pool?

**Comment by lessthnthree** [comment]
> It should be obvious what maps you've voted for then. Maybe make the button red and say 'Unvote' if you've voted for it?
> 
> Also you really gotta wait until after Feature Freeze for this

Yeah, I left it a draft until March, but I wanted to get feedback on it.

Colored buttons would be nice, but that may require an entire rewrite of the voting menu is what I got in Discord, but if someone better with TGUI knows how, that'd be ideal.

> Does this maintain the functionality of previously run maps not appearing in the voting pool?

Yes, it makes no changes to the procs that determine the choices, just the submission of votes.

**Comment by JohnFulpWillard** [comment]
> Yeah, I left it a draft until March, but I wanted to get feedback on it.

Feature freezes by its intent is meant to give a break from dealing with & discussing features, making your feature during the freeze to discuss it only to just make us wait until march to give a yes/no answer is going against that.
You're free to re-open after the freeze is over.

**Comment by LemonInTheDark** [comment]
I'm not a huge fan of this, seems like it would lead to exclusion of maps, which we don't want. S why we block revotes sometimes and such.

**Pull request closed without merging**
