### PR TITLE
This kills the crab. Crab17 removal.

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

The crab17 was never really funny, it was given bloated stats to the point where people would have to spend around 10 minutes meleeing it to get rid of it. Its bugs were never fixed (i.e, using an ID on the crab before it deploys will leave the entire crew unable to remove credits from their ID for the rest of the round.  

## Why It's Good For The Game

Crab17 = bad for the game
Removing something bad for the game is good for the game.

## Changelog

:cl:
del: Removed crab17. 
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
this is a weird way of mourning someone's death

**Comment by san7890** [comment]
>Its bugs were never fixed (i.e, using an ID on the crab before it deploys will leave the entire crew unable to remove credits from their ID for the rest of the round.

Interesting point.

**Comment by the-orange-cow** [comment]
_Its bugs were never fixed (i.e, using an ID on the crab before it deploys will leave the entire crew unable to remove credits from their ID for the rest of the round._

Perhaps fixing the bug would be a more constructive alternative to removing it entirely?  Then again, I don't think I've seen that bug a single time, so it hardly seems to be affecting rounds that much.

**Comment by Mothblocks** [comment]
I think it's funny and I think your "why is this good for the game" is devoid of content

**Comment by Mothblocks** [comment]
> it was given bloated stats to the point where people would have to spend around 10 minutes meleeing it to get rid of it

That's because it was originally invincible to incentivize people to scan their IDs instead of brainlessly hitting it. I intend to bring that back with a balloon alert so everyone knows you are meant to scan your ID at some point.

**Comment by thgvr** [comment]
you should fix the bugs or limit it to 1, then

**Comment by carshalash** [comment]
> > it was given bloated stats to the point where people would have to spend around 10 minutes meleeing it to get rid of it
> 
> That's because it was originally invincible to incentivize people to scan their IDs instead of brainlessly hitting it. I intend to bring that back with a balloon alert so everyone knows you are meant to scan your ID at some point.

Seriously, put a limit on them to one per round if you absolutely must make them loud invincible meme machines.

**Comment by Farquaar** [comment]
I like Crab-17, but I also like the name of the PR
So I'm conflicted

**Pull request closed without merging**
