### PR TITLE
Adds eggnog

### PR DESCRIPTION
**Pull request by swindly**
:cl: Swindly
add: Adds eggnog. It can be made by mixing 5 parts rum, 5 parts cream, and 5 parts egg yolk.
/:cl:

So that people can revel better during ~~Christmas~~ the festive season.

### CODE REVIEW

**Comment by TehZombehz** [comment]
Now I can simulate something that reality refuses to make easy: Getting eggnog any time of the year.

**Comment by Mervill** [comment]
so long as I can valid anyone who drinks this damn substance

**Comment by Iamgoofball** [comment]
remove eggnog

**Comment by Mervill** [comment]
next someone will insist that eggs should be a playable race

**Comment by MimicFaux** [comment]
Delicious nectar.

**Comment by Nienhaus** [comment]
You need some sprites with that nog.
numqnbs
https://www.dropbox.com/s/s817zedrhz9xw4t/Misc%20drinks.dmi?dl=0
So I sprited two for you to choose from.

**Pull request merged**
