### PR TITLE
Better Slappin Animations

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request
current attack animations suck
this is better
spank

## Why It's Good For The Game

uuh

## Changelog
:cl:
add: big slapps
/:cl:

### CODE REVIEW

**Comment by Couls** [comment]
we goon now

**Comment by necromanceranne** [comment]
Looks like he's smashing his head against a window

**Comment by TheChosenEvilOne** [comment]
> Looks like he's smashing his head against a window

I too would be smashing my head against a window if I had to work in this hellhole of a station.

**Comment by Cyberboss** [comment]
Not a fan of the item animation changes tbh

**Comment by actioninja** [comment]
A lot can be tweaked about them, what don't you like about it?

**Comment by Cyberboss** [comment]
Mainly the fade in seems off

**Review by Rohesie — DISMISSED** [review]
Code checks

**Comment by Cyberboss** [comment]
Sorry, upon closer inspection, it's not the fade in, it's the scaling

**Comment by nemvar** [comment]
Maybe a slightly larger initial transform (~0.4), a faster approach (~4) and a faster fadeout (~3).
I also changed the initial pixel_x to +-14 and the initial pixel_y to +-12. (y is smaller because the human sprite directly borders the adjacent turf on the y axis)

The push to make the animation faster was to give it a less cartoony vibe. It made the item striking the target better sync up with the attack sound.

**Pull request merged**
