### PR TITLE
Fixes weakened/stunned/paralysis not going down naturally for aliens.

### LINKED ISSUE #8704: Alien leap is broken.
If you smash into a wall, you get weaken for 2, and it never goes down. Seems to happen on simulated and unsimulated areas, gravity or not. I tested this in the thunderdome, at least. Seems sorta inconsistent on where it happens, but I've definitely had this happen on the station a number of times recently. #8629 and #8644 have NOT been merged at the time of writing.

### PR DESCRIPTION
**Pull request by phil235**
Fixes #8704

### CODE REVIEW

**Comment by RemieRichards** [comment]
Perhaps leave a comment, so nobody else tries to clean it up again.

**Comment by phil235** [comment]
Meh, I don't think a warning comment is necessary, it was a really lazy mistake not checking the very definition of the proc I was using.

**Comment by WJohn** [comment]
Also funnily enough, I recall there being a few cases where I was standing up but could not move, yet could still leap to get around. I don't know how to replicate that one as that was during april fools so I passed it off as "everything is going to shit and everything is breaking".

**Comment by phil235** [comment]
Probably stunned since it's also not going down.

**Pull request merged**
