### PR TITLE
Revert Statpanel to use verbs instead of SendMessage

### PR DESCRIPTION
**Pull request by Gamer025**
## About The Pull Request
Reverts the statpanel back to using verbs instead of Topic calls.
This is done to prevent it hitting the topic limiter when you re(connect) to the server:
image

## Why It's Good For The Game
Calls from the statpanel getting blocked by the topic limiter is probably a bad thing.
Surprised it didn't break anything.
Stylemistake said reverting the statpanel to verbs is fine.

## Changelog

:cl:Gamer025
fix: You should no longer receive "Your previous action was ignored..." messages when you join a server
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
This doesn't seem right, seems more like there should be an exemption near roundstart for the topic limiter if it's such a major problem.

**Comment by Gamer025** [comment]
> This doesn't seem right, seems more like there should be an exemption near roundstart for the topic limiter if it's such a major problem.
> 
> exemption or increased limits

Couldn't this be abused by connection to the game, spamming a lot of topic calls, disconnecting and just repeating that over and over.
Stylemistake said that reverting this back to verbs sounds like a good idea to him.

**Comment by LemonInTheDark** [comment]
> This doesn't seem right, seems more like there should be an exemption near roundstart for the topic limiter if it's such a major problem.
> 
> exemption or increased limits

Agree
That or make a separate counter for panel commands, since we do kinda want to throttle people who spam them, yes?

**Comment by Gamer025** [comment]
> > This doesn't seem right, seems more like there should be an exemption near roundstart for the topic limiter if it's such a major problem.
> > exemption or increased limits
> 
> Agree That or make a separate counter for panel commands, since we do kinda want to throttle people who spam them, yes?

Well the problem with oranges idea is:
The panel doesn't just send all the tabs near round start but rather whenever a client connects, uses the Refresh-TGUI command, uses the Fix-Stat-Panel verb and probably a bunch of other cases
So increasing the limit only when the round starts or the client connects wouldn't be enough

A separate counter for the panel might be a good idea but I'm not sure if that wouldn't cause the whole topic limiter itself to cost more CPU time because now it first needs to check if the href is coming from the panel then use the panel config else use the default config and that for every single topic call
Maybe @stylemistake could also comment on this

**Comment by stylemistake** [comment]
> I'm not sure if that wouldn't cause the whole topic limiter itself to cost more CPU time because now it first needs to check if the href is coming from the panel.

I'm honestly not sure if it's a good idea to add ad-hoc code to topic limiter to specifically address the stat panel, because it's not sustainable, it's a lot more code and dependencies compared to verbs, and verbs aren't rate limited to begin with.

But the check is cheap, just check if href_list has stat_browser in its window_id.

**Pull request closed without merging**
