### PR TITLE
Rebalance of L6 SAW ammo choices

### PR DESCRIPTION
**Pull request by lilacrhododendron**
:cl:
balance: L6 SAW AP ammo now costs 9 TC per magazine, up from 6.
balance: L6 SAW incendiary ammo now deals 20 damage per shot, up from 15.
/:cl:

The intent of this change is to make ammo choice with the L6 SAW meaningful. It is not meant to dramatically affect the balance of the SAW as a whole, but rather make all ammo types worth considering as opposed to there being one clear winner.
Using ball ammo as a baseline for what the SAW's expected power is, here is a short overview:

- Incendiary ammo is seriously weak, it takes 2 full bursts with all shots hitting AND 1 shot from another burst or damage from the firestacks to down a completely unarmored target. If anyone has an extinguisher (or if you're fighting in space, very common for ops) this ammo goes from being really niche to worse than a C-20r.
- Hollow point ammo is very powerful against unarmored targets, but pretty much useless versus even normal Security Officer body armor. Considering your regular target (the Captain) and the people who protect them both wear body armor as standard, it's a pretty weird choice. You can manually aim for limbs to dish out some damage, but it's very unreliable.
- AP ammo has zero downsides, and is WAY better against targets wearing body armor compared to ball ammo. For the exact same price, AP is objectively better. The loss of 5 damage is completely irrelevant, as it will still crit through any body armor in the game in 3 hits.

Hollow point ammo was weird enough that I've just left it alone. I don't think adjusting the price or the damage or the armor pen of this ammo would help. Incendiary ammo has gone from 15 damage to 20, which lets it crit if you land 5 shots on an un-armored target. I think it could probably receive some other buff, but I don't want to make it cancer, and what I've done is a big help in turns of killing quickly. AP ammo has gone from 6 TC to 9 TC. The rationale behind this change is that I don't want to seriously affect the maximum killing power of the SAW, but I want to give players a reason to choose types of ammo besides AP. The exact value that I change it to here could be tweaked, but I figured I'd get some feedback first. 

The SAW is a weapon that generates a lot of salt and I've been very careful to avoid making this PR feel like an "i ded plz nerf" PR. Would very much appreciate input on the changes, and what I've intentionally chosen to leave unchanged.

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
By "avoiding to make it an ided" you've just made the PR kind of plain bad. By the fact you're not touching the main issue, at all. Maybe touch the gun that shoots 50 bullets that deal 45 damage each in a 3 round burst a little bit more? Like, y'know, you should of? Dunno about you man, but I love my sprays down the hallway that'll near instantly crit people. Although maybe I should buy that one sniper rifle that shoots 70 damage stun bullets every 4 seconds, that one's real fun, man, if only I could just, do what that gun does but better.

**Comment by subject217** [comment]
I already touched spraying down long hallways in a separate PR. What you consider the "main issue" is a non-issue to me, Nuke Ops are intended to have super-powerful weapons and it is an important part of their balance.

**Comment by subject217** [comment]
I might up the TC cost on AP ammo a bit more, but it makes a bigger difference than you think. A big part of the bullshit is that literally everyone and their brother uses AP ammo and nothing but it. 

Your suggestions are completely out of the scope of this PR and if you feel that strongly about the L6 SAW you can make your own PR and see what the maintainers think of it.

**Comment by Shadowflame909** [comment]
Why not wear bullet proof armor, and tase the ops?

**Comment by subject217** [comment]
Bulletproof armor is useless versus AP ammo. It does work pretty well versus the regular ammo.

**Comment by ExcessiveUseOfCobblestone** [comment]
what's the point of ballistic armor if we have ballistics that hardcounter ballistic armor lol

**Comment by subject217** [comment]
Because those ballistics are in the hands of people who are heavily outnumbered and on the offensive. It's only an issue because AP ammo is the DEFAULT choice, which is exactly what I'm trying to change.

**Comment by Bawhoppen** [comment]
Incendiary change seems fine, but AP should probably be given a downside to make it situationally useful, rather than just increasing the price.

**Comment by subject217** [comment]
I'm welcome to your wonderful situationally useful suggestions, it has certainly worked out well for HP ammo which is definitely not a dumpster fire that is impossible to balance.

**Pull request merged**
