### PR TITLE
Vote Panel Fixes: Allows Player Votes, Vertical Rendering for Voting List

### LINKED ISSUE #57886: New vote system doesn't separate ckeys in the viewer
## Reproduction:
Make a vote, watch people show up.
image

### LINKED ISSUE #57968: Players cannot start a restart vote
## Round ID:
[158993](https://scrubby.melonmesa.com/round/158993)

## Testmerges:
none

## Reproduction:
image
OOC > vote
Guess they don't have perms for it or something

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Closes #57968
Closes #57886

This now fixes two issues brought to my attention (thx @LemonInTheDark ). 
Players could not initiate a vote. The admin panel was not visible to them. This was a bit of a mistranslation from another station on my part, I was also expecting #57940 would pass (it didn't). 

The voting list was also being sent as a list of a list. This has been fixed and is now rendering properly.

- Players can now initiate votes
- Only Admins can disable voting types
- Trialmins and Admins can view voters, create custom votes, cancel votes.
- Added some jsdoc comments
- Fixed horizontal rendering of voters

## Why It's Good For The Game
- Democracy
- Helps with game flow a bit 
- Admins no longer have to squint at voting list

## Changelog
:cl:
add: Players can now initiate votes using the new vote panel (assuming CentCom allows it).
fix: Admins' voting list is now properly rendered
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Are you aware of https://github.com/tgstation/tgstation/issues/57886?

**Comment by jlsnow301** [comment]
> Are you aware of #57886?

I was not (it is a bit difficult to test locally). I can fix that here unless you want a separate PR for it

**Comment by LemonInTheDark** [comment]
Up to you, do whatever's easiest. I've been meaning to bug ya about it but I couldn't find your handle on discord

**Review by stylemistake — COMMENTED** [review]
Wait, this is a client-only change?

**Comment by jlsnow301** [comment]
> Wait, this is a client-only change?

yes

**Comment by jlsnow301** [comment]
Sorry,  it was a mistake I made in sending the data over. Tested it with no key + my byond key logged in. It is now showing the proper amount of voters + rendering them in a column

**Pull request merged**
