### PR TITLE
Updates and improves various xeno UI buttons.

### PR DESCRIPTION
**Pull request by WJohn**
The main changes are:

Spit, whisper, transfer plasma, melt with acid, larva hide, xeno hide, hunter leap.

Also fixes targeting the head in the bottom right showing the old xeno inventory head sprite on it.

### CODE REVIEW

**Comment by Xhuis** [comment]
THE LARVA ONE IS SO ADORABLEEEEEEE

**Comment by Anonus** [comment]
This will conflict with #13026 as a note

**Comment by WJohn** [comment]
Thats alright, should be easy to resolve.

**Comment by GunHog** [comment]
Guess you did not need me after all!

**Comment by Razharas** [comment]
@WJohn

**Pull request merged**
