### PR TITLE
Makes firelocks delete themselves on spawn so that we can see if it actually causes problems with atmospherics in practice instead of just on paper.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Makes firelocks delete themselves on spawn so that we can see if it actually causes problems with atmospherics in practice instead of just on paper.

## Why It's Good For The Game

oranges jokingly said to remove firelocks, I replied we can't do that because of atmos, but then realized "wait, is that actually true though or is it just something we cargo-cult about and haven't actually tested". So, here's a PR we can use to test what atmos performance is when we don't have firelocks.

Firelocks are, frankly, not an enjoyable experience to deal with. They can shut down due to what is frankly non-important air differences, and provide no gameplay to the players other than sometimes trapping you in a room that you're dying in due to poor fire alarm placement/lack of crowbars.

Or, alternatively, it just randomly flips out and activates because the air on the tile next to it is two degrees hotter than the other tiles.

I also don't think it even blocks fires reliably, either.

### CODE REVIEW

**Comment by Zytolg** [comment]
I ded plz remove pr

**Comment by nianjiilical** [comment]
i support testmerging this if only because it will be funny 

and theres even a small chance we learn something from it

**Comment by LemonInTheDark** [comment]
It's been tried before in a softer form here <https://github.com/tgstation/tgstation/pull/56571>
Leads to a paraplegic atmos system, and sudden large freezes.

**Comment by newfren** [comment]
just played a round on manuel with this and julia elliston cut the station in half with the toxins gun. That's going to cause problems ordinarily but in this round it meant there was no air anywhere at all. Very sad!

**Comment by Mothblocks** [comment]
Just for the record, Goof isn't testing balance, just performance of the atmos SS...I think.

**Comment by LemonInTheDark** [comment]
> 
> 
> Just for the record, Goof isn't testing balance, just performance of the atmos SS...I think.

There isn't really a good way to test that, since you're not really testing for total fire times, more "work performed". I'm not big brained enough to make a graph of that. 
A station being one big airspace when trying to work with a breach will cause issues, but they won't be like, td or cpu ones. Less work will be done until players move away from the area, at which point all connected airspace will slowly/quickly freeze, depending on the size of the hole. Can't really back that up outside of telling you to observe a highpop round with the atmos debugger on for a while. Wait for someone to make a hole near people and such.

**Pull request closed without merging**
