### PR TITLE
Reverts "Allows gender neutral humans in preferences"

### PR DESCRIPTION
**Pull request by AntifaBikeLockProfessor**
Reverts #44530

https://christiannews.net/2019/02/15/first-u-s-man-to-legally-identify-as-neither-renounces-transgenderism-i-am-and-have-always-been-male/

“I will not be a party to advancing harmful gender ideologies that are ruining lives, causing deaths and contributing to the sterilization and mutilation of gender-confused children,” he declared. “My history-making and landmark sex change to non-binary was a fraud based on the pseudoscience of gender identity. I am and have always been male. There should be no social or legal penalty for others to state that.”

“I figured I was a transgender woman. My thinking was, well, I’m not a male,” Shupe told reporters. “**I was in a deep, dark depression** because I had boxed myself into this male identity that I couldn’t stand anymore.”

Shupe said that he came to the realization that **he wasn’t receiving proper treatment for the psychotic issues** that he had sought help for in the first place, which included hallucinations, destructive behavior and paranoia.

As previously reported, the Bible teaches that all men are in the same predicament: All are born with the Adamic sin nature, having various inherent inclinations that are contrary to the law of God and being utterly incapable of changing themselves. It is why Jesus outlined in John 3:5-7 that men must be regenerated by the second birth, or they cannot see the kingdom of Heaven.

“But to men writhing in the grip of a sinful past, or paralyzed beyond writhing and indifferent, because [they are] hopeless, or because they have come to like their captivity, comes one whose name is ‘The Breaker,’ whose mission it is to proclaim liberty to the captives, and whose hand laid on the cords that bind a soul, causes them to drop harmless from the limbs and sets the bondsman free.”

Jesus declared in John 8, “Verily, verily, I say unto you: Whosoever committeth sin is the servant of sin. And the servant abideth not in the house forever, but the Son abideth ever. If the Son, therefore, shall make you free, ye shall be free indeed.”

### CODE REVIEW

**Comment by wesoda25** [comment]
its not worth it man. I don’t like this feature as much as you but I don’t think this is worth it

**Comment by granpawalton** [comment]
just wait till the end of pride month bc for somereason people associate mental disabilities with pride

**Comment by Whoneedspacee** [comment]
actually why though

**Comment by Qustinnus** [comment]
rip granpawalton

**Comment by 123chess456** [comment]
I think this PR violates the Github ToS for being transphobic.

**Comment by FantasticFwoosh** [comment]
There is nothing more :pill: than encoding the literal word of god into your collective community coding project.

**Comment by yclatious** [comment]
Fuck trannies and dab on crossdressers
*dab

**Comment by OverlyGeneric** [comment]
Please do not bring politics and religion into this game.

Goonstation added this and they haven't changed at all.

I respect your beliefs as a fellow Christain but isn't the Bible also about accepting others and turning your cheek the other way?

**Comment by granpawalton** [comment]
im pretty sure he put the bible part in as part of the meme

**Comment by ThatLing** [comment]
ok mr alt account

**Comment by Anonymous583** [comment]
get this trash off the server

**Comment by ishitbyabullet** [comment]
im pretty sure the pr would be denied based on solely the name even if you had literal proof from god that you're right about this.

also they/them isn't even related to transgenderism. a transgender identifies as male or female. that's not the same as saying you're a completely different gender.

**Comment by HomocidlePancakes** [comment]
image

Man, you seem to have very strong opinions, and yet, you lack the audacity to use your main account to represent them. Really makes you T H I N K.

**Comment by ishitbyabullet** [comment]
@HomocidlePancakes i think it would be possible to tell it was an alt simply due to the name.

who the fuck codes or would code for /tg/ with a name like that? no one. no one would.

**Comment by 81Denton** [comment]
tip

**Comment by HomocidlePancakes** [comment]
lol

**Comment by granpawalton** [comment]
they probably using an alt so they dont have to deal with sjws attacking them from either this server or github staff

**Comment by HomocidlePancakes** [comment]
Noone is going to attack you for disagreeing.

**Comment by tralezab** [comment]
where do you think we are

**Comment by ishitbyabullet** [comment]
@granpawalton yeah, that seems about right however i don't think that name is gonna convince anyone to not treat this as nothing but a shitpost.

**Comment by Anonymous583** [comment]
@HomocidlePancakes you clearly have never dealt with these types before

**Comment by OverlyGeneric** [comment]
meanwhile, I'm just sitting here wondering what the heck is going on and why people are fearmongering over this despite it won't change anything.

**Comment by ShiftyRail** [comment]
I'm just wondering which human sprite gender neutral folks get.

**Comment by HomocidlePancakes** [comment]
Sure, tell me more about your experiences with "these types".

**Comment by granpawalton** [comment]
image

i dont think youre wondering why i thing your just playing innocent but what do i know

**Comment by yclatious** [comment]
With a broken body and a battered mind
I look upon this place of thine
Filth I see, casuals many
All antsy over some garbage tranny

I dab on thee, I dab on thou
No matter who, no matter how
TG sucks, so I declare
Enjoy this freakshow fair

*Dab
*Dab
*Dab
*Dab
*Dab

**Comment by HomocidlePancakes** [comment]
One day while Andy was discovering his gender identity, Woody got Alt-right.

**Comment by 81Denton** [comment]
cringed and redditpilled

**Comment by granpawalton** [comment]
image

**Comment by wesoda25** [comment]
its stuff like this that makes me want to quit ss13

**Comment by HomocidlePancakes** [comment]
unknown

This is how I look irl. Brace thyself thot.

**Comment by subject217** [comment]
pssst if this bothers you that much maybe it's a good idea to quit

**Comment by Whoneedspacee** [comment]
>they wont attack you for disagreeing

my posts in the nonbinary pr really do beg to disagree

**Comment by yclatious** [comment]
If shitposting is enough to get you to consider quitting /ss/thirteen then you really gotta grow some tomatoes to replace the nuts you never had.

*Dab

**Comment by HomocidlePancakes** [comment]
Or maybe you should actually fight back if something is bothering you? That option exists

**Comment by granpawalton** [comment]
> 26 people agree with it 46 dont

> pssst if this bothers you that much maybe it's a good idea to quit

yea no we are the crazy ones

**Comment by HomocidlePancakes** [comment]
Actually, can we have someone rewrite WGW just based on what happened today?

**Comment by ishitbyabullet** [comment]
@HomocidlePancakes you do it.

**Comment by HomocidlePancakes** [comment]
Fuck it. Lessgo

**Comment by HomocidlePancakes** [comment]
Gonna do it myself. Propably will be cringe but whatever

**Comment by HomocidlePancakes** [comment]
Eh, too much effort. Just gonna shitpost

https://cdn.discordapp.com/attachments/331406079063883779/589541189552832512/image0-49-1.jpg

**Comment by yclatious** [comment]
Team Aristotle representing, Platofags begone.

**Comment by HomocidlePancakes** [comment]
But who is the best tomboy tho?

**Comment by yclatious** [comment]
The one you love brotha. The one you love.

**Comment by HomocidlePancakes** [comment]
I am taking over this thread and turning it in to a best girl discussion. Tomboy Edition.

Opening statement: Naoto from Persona 4 is the best tomboy.

**Comment by 81Denton** [comment]
based pancakes

**Comment by HomocidlePancakes** [comment]
I actually just realised I don’t remember that many tomboys besides Chie and Naoto. Ughhhh. Post tomboys?

**Comment by w779431h** [comment]
gamers are upset

**Comment by wesoda25** [comment]
> pssst if this bothers you that much maybe it's a good idea to quit

talking about the back and forth with PRs like this R*tard

**Comment by wesoda25** [comment]
but for real subject it makes me sad to see you acting like this on these PRs. I used to have a decent amount of respect for you but seeing you incapable of understanding that people can have different opinions than you is honestly just disappointing. its shit like this that makes me wanna quit (what I was talking about in the first place) because these PRs dredge out the shittiest side of everyone and at the end of the day I wonder if anyone is really happy. i guess thats what I get for trying to objectify people around their "based" opinions in an online atmos simulator, its all just very disheartening to me. maybe im having a moment of clarity right now, its probably so, and ill be clouded by emotions like the rest of you (and me last night) and not give a fuck in a couple hours. but for now, it really does sadden me to see everyone being complete and utter assholes to one another over something as trivial as this

**Comment by Qustinnus** [comment]
tbf shame on you for expecting anything decent from subject

**Comment by yclatious** [comment]
Who tf even remotely cares about being gender inclusive in a deathtrap space station filled with psychopaths? Come the fuck on boi. Who even remotely gets emotional over people liking/disliking it too? Shits so meaningless it makes me laugh when folks say they wanna quit due to it, oh no, a buncha nerds dont agree with me, time to quit ess ess 13.

Also you dorks having two times dislikes ratio on the OG pr and merging it is why we laugh at TeeGay non stop. You lads are a joke, Im just here to shittalk you all. *Dab

**Comment by HomocidlePancakes** [comment]
ARE YOU DERAILING MY BEST GIRL DISCUSSION? REEEEEEEEEEEEEEE

**Comment by granpawalton** [comment]
should just let dead PR die

**Comment by HomocidlePancakes** [comment]
I agree. Time to sleep

**Comment by nuklearcellphoneg** [comment]
OH I see the PR itself has a 41% increased chance of suicide.

**Comment by ahiaao** [comment]
> I respect your beliefs as a fellow Christain
First of all it is spelled Christian, not Christain. The Bible is not just about morals, but yes it does contain morals that you should follow.
>accepting others
I wouldn't say this is a key theme. Was God accepting of humanity when he caused the flood in Genesis? In Exodus, was God accepting of the Pharaoh keeping the Israelites as slaves? No, for not releasing them God caused Egypt to experience plagues until they were released. In Jonah, God sends him to deliver a message to Nineveh that they must stop being wicked else face destruction. The Nineveh people stopped being wicked so they were spared. This is also a common theme in the New Testament in which Jesus provides you a way to have your sin to be forgiven. Though do remember that there are sins which can not be forgiven, but that is beside the point. There is nothing in the Bible that states that you can't prevent people from self harm / mutilation, nor does it forbid you from trying to get someone help for there mental illnesses.
>turning your cheek the other way?
This is irrelevant. Do you expect OP to take a plane ride out to the author of the commit he is reverting and engage in violence? Instead he is taking the nonviolent route of submitting a PR to revert a change that to him negatively effected the software.

**Comment by FantasticFwoosh** [comment]
> its stuff like this that makes me want to quit ss13

I can sympathise and honestly id advocate it to anybody, least temporarily currently getting emotionally mashed up about clashing people people on drama community PR's/topics. Hostility is unreal.

I can't believe i got gitblocked from this repo almost over half a year ago for talking too much, wow this PR discussion is :hankey: Only well spoken post here is the bible-citing OP.

**Pull request closed without merging**
