### PR TITLE
resprites the forensic scanner, cargo tagger, and the RPED

### PR DESCRIPTION
**Pull request by pudl**
screenshots in a sec
credit to myself for the scanner
credit to @Nienhaus for cargo tagger
idk who did the RPED

 (disregard the scanner)

the green lines aren't normally symmetrical like that, it has a scrolling animation

### CODE REVIEW

**Comment by GunHog** [comment]
The scanner and tagger look okay, but that RPED looks plain and boring. Please do not include it. I omitted it from my port of its expansion from NT for that very reason.

**Comment by pudl** [comment]
boring > codersprite

**Comment by Chocobro** [comment]
screenshots where, demon

**Comment by pudl** [comment]
look

**Comment by Chocobro** [comment]
i see none

**Comment by pudl** [comment]
LOOK

**Comment by Nienhaus** [comment]
Thank god, my RPED looked like shit, I didn't even try with it. :+1:

**Comment by Chocobro** [comment]
identify
showmedemon

**Comment by Supermichael777** [comment]
ewww no those taggers look like shit, recolor the current ones if you want them to be more distinct

**Comment by Nienhaus** [comment]
rhqbjma
@Chocobro

**Comment by pudl** [comment]
lmao actually telling people to recolor sprites

**Comment by Chocobro** [comment]
you told me to recolour poppies
thankyou nienhaus git is being very silly
the cargo tagger looks like garbage
rped so-so

**Comment by Nienhaus** [comment]
Just so everyone is clear, this is the current RPED
eo9lecb

**Comment by pudl** [comment]
choco i told you to FIX the poppy recolor (it was literally orange) and you didnt

**Comment by Supermichael777** [comment]
i do agree that they probably need new sprites but these are in order boring, my grandpas e reader and a candy wraper. how the fuck are you even supost to hold those

**Comment by Nienhaus** [comment]
Well the new sprite does have a handle at the top, just going a different way.

**Comment by Chocobro** [comment]
the poppy recolour wasn't broken
also there are orange poppies http://en.wikipedia.org/wiki/Eschscholzia_californica

**Comment by pudl** [comment]
if it's a recolor, it's broken

**Comment by Chocobro** [comment]
i've got something you can break

**Comment by Cheridan** [comment]
Cargo tagger is terrible, the others are at least an improvement.

**Comment by Dorsisdwarf** [comment]
tagger bad, RPED boring, scanner sexy

**Comment by WJohn** [comment]
I quite like our current forensic scanner, as it's running a bit of a consistency trend with the analyzer and mining scanner. The cargo tagger's new sprite isn't fantastic but ANYTHING is better than the hideous piece of shit we have now. The RPED is strangely taking on the blue machine sprites we have, and while it's well done and I have no problem with the sprite, that style has so far only been used for stationary machines, it might confuse players a bit.

**Comment by pudl** [comment]
@WJohn it's completely inconsistent with the mining scanner and analyzer? the mining scanner and analyzer are ovular/rectangular things with a screen, the current forensic scanner is like a barcode scanner that's blue and weird looking.

**Comment by WJohn** [comment]
Oh, I might be mistaken with the one from bay or something.

**Comment by dannno** [comment]
this new RPED is way better

**Comment by WJohn** [comment]
This is the autopsy scanner from bay, I think it'd do much better as a forensic scanner here than what's proposed.

**Comment by dannno** [comment]
disagree, that thing looks like a literal turd

**Comment by WJohn** [comment]
Way better than the blue piece of shit we have right now, and has bonus points of consistency with our other scanners.

**Comment by dannno** [comment]
allura's proposed change is also better than the current one.
and better than bay's.

**Comment by pudl** [comment]
cargo tagger resprited by @Nienhaus

**Comment by PKPenguin321** [comment]
i'm ok with the current RPED, new one wouldn't hurt though
cargo tagger should definitely be changed
forensic scanner's okay except that i feel like it should look like something you point at things rather than hold and read

**Comment by Dorsisdwarf** [comment]
The new cargo tagger is neat. Makes it look like you're actually slapping on a tag instead of just waving a radar gun at it.

**Comment by SconesC** [comment]
I like the Cargo Tagger a lot, makes a lot more sense to literally be tagging things instead of waving a magical beeping gun at them 

Not a fan of the new RPED at all. Looks like a piece of stationary machinery. 

Not too keen on the Forensic Scanner either, honestly. I like the current sprite.

**Comment by Steelpoint** [comment]
I dislike the Forensic Scanner sprite.

However I like both the RPED and the Tagger sprites.

**Comment by MrSnapwalk** [comment]
;_; y u all so mean 2 meeee

(In all seriousness, I agree - my Forensics Scanner sprite was pretty bad. If you want a good one, check out Baystation's version.)

**Comment by Nienhaus** [comment]
It's okay @MrSnapwalk we still love you.

**Comment by pudl** [comment]
@MrSnapwalk we looked at bay's, it is legitimately godawful. it's like a poop shoe. a shoe of poop. your version is, in my opinion, truly beautiful

**Comment by WJohn** [comment]
Would it be better if the brown was made black instead?

**Comment by pudl** [comment]
no, there is no way to ever make it look not shit

**Comment by pudl** [comment]
i resprited it again

**Comment by pudl** [comment]
merge when

**Comment by GunHog** [comment]
Hopefully when the RPED sprite is reverted.

**Comment by pudl** [comment]
3 people don't want the new rped, 7 people do.
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by Supermichael777** [comment]
sprites are now acceptable merge it

**Comment by Nienhaus** [comment]
@GunHog the RPED sprite I made looks like shit, the one in this PR is much better.

**Pull request merged**
