### PR TITLE
Micros the lighting subsystem (Saves a second of init)

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Micros lighting objects, and their creation

We save a good bit of time by not walking space turfs adjacent to new objects. 
We also save some time with micros in the actual underlay update logic.

I swear dude we spend like 0.8 seconds of init applying the underlay. I want threaded maptick already

Micros lighting sources, and corner creation

A: Corners were being passed just A turf, and then expected to generatecorners based on that. This is pointless.
It is better to instead pass in the coords of the bottom left turf, and then build in a circle. This saves like 0.3 seconds

B: We use so many damn datum vars in corner application that we just do not need to. 
This resolves that, since it pissed me off. It's pointless. Lets cache em instead

There's some misc datum var caching going on here too. Lemme see...
Oh and a bit of shortcutting for a for loop, since it was a tad expensive on its own.

Also I removed the turfs list, because it does fucking nothing. Why is this still here.

All my little optimizations save about 1 second of init I think
Not great, but not bad, and plus actual lighting work is faster now too

## Why It's Good For The Game

Speed

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Testmerged on manuel

**Comment by LemonInTheDark** [comment]
broooooooooo

**Comment by optimumtact** [comment]
is it ready?

**Comment by LemonInTheDark** [comment]
it is ready

**Comment by optimumtact** [comment]
who asked

**Comment by LemonInTheDark** [comment]
mothblocks moment

**Pull request merged**
