### PR TITLE
[WIP]new beepsky smash

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
balance: beepsky smash no longer stuns on ingestion
balance: beepsky smash summons illusion beepskys that follow you and cause stamina damage (if you are an officer it gives you some hallucinations and slight stamina boost)
balance: updated the recipe(lime juice + quad sec + iron)
/:cl:
open for discussion and (((balance)))

- [ ] add more cool effects
- [ ]  things on OD?

### CODE REVIEW

**Comment by Angustmeta** [comment]
I see you already rebalanced the metabolization rate from 0.8 to 0.5, but I think you might as well put it to 0.4 to make it consistent with most of chems including neurotoxin.

**Comment by PKPenguin321** [comment]
>injestion

ingestion

**Comment by pizzatiger** [comment]
If all it does is spawn ghost beepsky's then I suggest you make them do the normal stuns. This way it keeps its origins of being a stunning drink while also being an avoidable stun

**Comment by ATH1909** [comment]
Since this PR nerfs Beepsky Smash, I don't see why you have to make it harder to craft.

Idea: Add an OD effect that makes illusory ED-209s spawn as well.

**Comment by davethwave** [comment]
Honestly as a bartender side main, I would say that the recipe change is a good idea considering the effects of the drink. But even then the drink is pretty easy to make with or without the recipe change.

**Comment by Tlaltecuhtli** [comment]
i changed the recipe because its more thematic

**Comment by Shadowflame909** [comment]
If it OD's Beepsky transforms into an ED-209 that starts shooting tasers at you (Or Disablers if ED-209's do that now)


Just make the OD threshold really high like 500 units

**Comment by ExcessiveUseOfCobblestone** [comment]
Is 11 days really necessary for a reagent edit?

**Pull request closed without merging**
