### PR TITLE
Adds quiet argument to playsound.

### PR DESCRIPTION
**Pull request by AnturK**
Sounds with quiet set to true won't go through walls, volume change with distance etc will still happen

Not sure we'll have some use out of it or not. 
Please give feedback.

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
how about adding an argument for how much sound decays through walls

**Comment by AnturK** [comment]
I need to get home to profile it because my first approximation is it would be too expensive, certainly for every single sound.

**Comment by ExcessiveUseOfCobblestone** [comment]
quiet should be fine, but if it bothers people it could be renamed to "soft"

**Review by Cyberboss — CHANGES_REQUESTED** [review]
soft makes more sense imo, or maybe penetrate_walls

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
