### PR TITLE
Removes the BWOINK from adminhelping

### PR DESCRIPTION
**Pull request by ghost**
happy 2018 fuckers

:cl: More Robust Than You
tweak: Adminhelps/pms should no longer give you lifelong PTSD
/:cl:

### CODE REVIEW

**Comment by imsxz** [comment]
why tho

**Comment by praisenarsie** [comment]
not funny 😠 close this

**Comment by ShiggyDiggyDo** [comment]
only shitters fear the bwoink, so it works as intended

**Comment by deathride58** [comment]
Is this a fuckin "i banne" pr

**Comment by ShizCalev** [comment]
No

**Pull request closed without merging**
