### PR TITLE
Remaps tram's ordnance

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
More of #65807, but in tram

## Why It's Good For The Game
Refer to #65807. Same goals and similar layout. Similar balance too except this one got an extra freezer. Because trains are kinda cool.

## Changelog
:cl:
expansion: Tram's ordnance got remapped.
/:cl:

### CODE REVIEW

**Review by san7890 — COMMENTED** [review]
Hey there,

Another friendly review. Now that I know how spoilers work, I'll put stuff into two categories.

<details>
<summary>The Important Stuff</summary>

image

This should all be /area/space.

image4

Missing the Mining Explore Area.

image
Reinforced wall here. It's quite funny, but I think you want plating as well as all of the power+atmos hookups. Also, storage should own that door.

image
Plating should be under these r-windows.
</details>

<details>
<summary>The Nitpicky Stuff</summary>

image

Not quite sure how I feel about these two canisters just hanging out here. Could have some better incorporation like the other canisters.

image

image

image

Few too many vents+scrubbers in the same area. Cramped. One is fine. I can get the utilitarian purpose of getting tritium out QUICK, but I think it might deserve some weighing of balance. One of both are fine.

image

I'm pretty sure you didn't touch this in your PR, but I happened to see this so... would you mind flipping the dir? Thankies.

image

Obj placement on this table could be a bit better I feel. If you're going for a more disordered look, that's fine, but it just clashes to me personally.

image

I personally feel that there should only be one "Lil Pump". Irreplacable, yet oh-so-lovable.

image

Does this light work if in this area? I have no clue how power for the mixing chamber works. Might need to move it to an adjacent wall (unless you've already tested this on local and it's fine).

Also, would be nice to have one or two newscasters around on the walls. Maybe a poster or two if you're feeling up to it.
</details>

Overall, it's still quite a good design. I don't really have any hang-ups beyond what I really noted. It's not quite as unique as Meta, but they can't all be weird clusterfucks. Good job.

**Comment by vincentiusvin** [comment]
A number of them addressed. Except the oxygen can. Can't really find a better place to stick them and its pretty minor so I'm not very bothered by this. Thanks for the time.

**Comment by Zytolg** [comment]
You're going to be asked for 2 things. 
PR Description, explain in detail what you're doing here.
PR Images. Show us what you're changing.

**Comment by vincentiusvin** [comment]
Don't backseat maintain. Or at least be nicer if you want to.
image

**Pull request merged**
