### PR TITLE
Tongueless humans cannot cast vocal spells, handless humans cannot invoke emote spells

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Humans without tongues cannot cast vocal spells
- Humans without hands cannot cast emote spells

## Why It's Good For The Game

It stands to reason if you cannot get the correct invocation to the spell out, you should not be able to cast. 

(I thought this was already the case and I broke it at some point, but honestly I'm not entirely sure.)

In other words, this opens up tongue removal as counter for heretic spellcasting, which I think is quite funny. If you get to that point, you already lost. 

This leaves slurring up in the air, it stays though, since it's close enough.

## Changelog

:cl: Melbert
balance: Humanoids without tongues cannot cast spells with vocal components
balance: Humanoids without arms cannot cast spells with emotive components
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
(Dare I suggest slurring/stuttering just has a percentage chance to fizzle spells)

**Comment by DaydreamIQ** [comment]
I'm assuming tounge still won't stop funny hand tho right?

**Comment by necromanceranne** [comment]
The funny hand has an invocation

**Comment by private-tristan** [comment]
Does this effect alien alloy golem wiz? Or does speaking into abductor chat work?

**Comment by Jacquerel** [comment]
> Does this effect alien alloy golem wiz? Or does speaking into abductor chat work?

alien alloy golems haven't existed for several months

**Comment by MrMelbert** [comment]
> (Dare I suggest slurring/stuttering just has a percentage chance to fizzle spells)

I was thinking like, you have a % chance of failing cast based on how accurate the message was to the actual invocation, but that's far too complex I think

(The idea of a wizard repeatedly sputtering out an invocation like one of those bad voice authorization "I am the wizard, my voice is my passport, verify me" until they get it right is hilarious, but may be a tad unfun)

**Comment by jlsnow301** [comment]
D&D energy. Can you make the feedback into balloon alerts?

**Comment by MrMelbert** [comment]
> Can you make the feedback into balloon alerts?

I'll put a pin in that for another pr because all of the can cast spell messages could be balloon'd but that's out of scope

**Comment by Ticklezcat** [comment]
But does it fix Advanced mimes being able to make and shoot finger guns with no arms?

**Comment by MrMelbert** [comment]
> But does it fix Advanced mimes being able to make and shoot finger guns with no arms?

it would yes

**Pull request merged**
