### PR TITLE
Makes jetpacks obtainable during space exploration

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This adds jetpacks to (non-empty) suit lockers in space ruins, making them obtainable during exploration instead of just from the station. A total of 10 ruins (13%) are affected by this change.

## Why It's Good For The Game

Currently, "AI, open jetpacks" is near synonymous with "AI, open EVA please" - or people might just ask for the latter and smash open the jetpack windoor if that seems easier.

Why do people do this? There's a few reasons, but I think one of the most key is...

Well, supposing one grabs the aux base's PKA before leaving the station. They'll probably be fine. Probably. But even with that they might get swarmed by carp and be unable to fend them off before a flurry of bites sends them into critical. At each gear step less than the PKA, this becomes more likely, down to fists or pacifism making even just 1 a serious threat or near certain death.

Obviously a jetpack's movement in general is advantageous, but especially the ability to outrun carp makes it a key exploration tool.

Yet it's also one that, in its standard form, just doesn't exist off station. This PR makes it possible to obtain them from space ruins, though leaving the station without is still playing roulette a bit.

I don't think this should really have balance impacts because, the way the game is played, it's essentially standard equipment for explorers anyways; and if someone wants a jetpack for other reasons (antag or not), going to space isn't an efficient way to get it.

But as a note, only 10 ruins are affected by this change. This represents around 13% of the ruins pool, so, given how large said pool is, this might not take off as much pressure from going to EVA as I hope (Especially on server configs with low ruin budgets or the North Star map, they still have a good chance of simply not spawning). But even so, I think it's a good idea for the possibility/path to exist.

## Changelog

:cl:
qol: jetpacks can now be found in some space ruins' (~13%) suit lockers, giving explorers an alternative path to obtain one.
/:cl:

### CODE REVIEW

**Comment by JusticeGoat** [comment]
Did you know you can build jetpacks via table craft?

**Comment by MrDoomBringer** [comment]
unique, public jetpacks that only work off of the station z-level would be a cool solution to this problem

**Comment by YehnBeep** [comment]
> public jetpacks that only work off of the station z-level would be a cool solution to this problem

Well, that's if you feel there's a balance problem. But this PR isn't addressing balance.

Supposing AI/command players stop opening EVA on a whim, there's still the aforementioned crafted jetpacks, cargo ordering, ions - and actual antags can of course just TC summon their advanced ions (and both ion types are much more suitable for station use than exploring).

As long as a culture is in place of opening EVA regularly, antags that want to stay stealthy can just ask like anyone else. Since (at least on the server I play on) it's very rare to catch an explorer without a jetpack anyways, affecting balance is neither a goal nor anticipated impact of this PR.

**Comment by atlasle** [comment]
great change

**Comment by Helg2** [comment]
I'm not sure that making jetpacks spawn in ruins manually is a good idea, everyone will just rush those 13 ruins for jetpacks after a bit of time to know the meta, like this happens with some gear in maints.
I would propose to make the suit storage units in specifically space ruins have a chance to spawn with a jetpack but i don't know how to do it.

**Comment by YehnBeep** [comment]
> I'm not sure that making jetpacks spawn in ruins manually is a good idea, everyone will just rush those 13 ruins for jetpacks after a bit of time to know the meta, like this happens with some gear in maints. I would propose to make the suit storage units in specifically space ruins have a chance to spawn with a jetpack but i don't know how to do it.

10 ruins. But I think that you're overestimating the desirability and ability of jetpacks to powergame, or again, people would just raid EVA. It's really not any harder than, "AI, open, I want to go exploring" or similar, but it's very rare that anyone wants them outside of the usually 1~2 explorers.

And when things like the elite syndie suit were out there - you'd need a jetpack to have a chance of ruin loot quickly anyways. Someone that's attitude is "Man, I GOTTA have that jetpack asap so I can powergame!" probably won't have the patience to try their luck at hitting one of the right ruins on the drift or using the iron rods method.

I very sincerely doubt anyone's going to rush ruins for what's routinely available on station as is.

**Comment by Helg2** [comment]
I didn't mean powergame, but the element of randomness.

**Comment by YehnBeep** [comment]
Hm. Well, I'm not sure anything can really be done about that. Even if there was something like "50% chance to spawn this", people would still know 'it has to be among these 10 ruins', but that would also directly hurt the goal of this PR since the already-relatively-unreliable option just becomes more unreliable. Also it would hurt further the chances even one could be found on North Star or a general low budget config.

I suppose a random spawner could be created and added to every ruin or near enough. That would make a bit less intuitive sense compared to finding them with the suits already out there IMO, but on the other hand, it could mean better odds for intrepid explorers willing to leave the station without already having a jetpack, and reduce relying on one of these 10 ruins spawning and being found.

More than one way to skin a cat... but that's not a method I know. I suppose if the maintainers go 'this idea is basically ok but do it that way,' I could try to figure it out.

**Comment by MTandi** [comment]
> > Did you know you can build jetpacks via table craft?
> 
> Yes. Given cooperation from engineering, or a willingness to break in, or just... rip up some station pipes if nothing else I guess.

You also know that pipes can be crafted from metal sheets in crafting menu too, right? 
So it's a recipe any assistant can handle with a basic set of tools with ease.

I love makeshift stuff and the more people use it the better. It is a perfect example of why SS13 is an amazing game - you can take an extinguisher from a wall frame (or you can craft it too), craft a couple of other things and you have a jetpack built from a pile of random crap.

This addition discourages people to explore crafting menu and makeshift tools. I think it would be better to make sure they have all components needed for crafting a jetpack on those ruins instead of ready-to-use jetpacks for metagaming.

**Comment by YehnBeep** [comment]
Didn't know pipes could be crafted that way actually, so that's pretty neat.

But... "metagaming"? Really?

And I wouldn't say that it does. Any on-station method of acquisition has the advantage of certainty of having one when leaving the station, rather than leaving it up to chance that you'll find the right ruin and - depending on how well prepared one is when leaving the station - perhaps meet their demise if they're unlucky in their encounters.

**Comment by nukularpower** [comment]
i imagine a system where there are, get this, "space pods" that can go off station z level without needing a jetpack - like, mountable machines you can fly around

Instead there will be a whole job, mechanic, dedicated to them

it is gonna be great, wait and see

**Comment by YehnBeep** [comment]
> i imagine a system where there are, get this, "space pods" that can go off station z level without needing a jetpack - like, mountable machines you can fly around
> 
> Instead there will be a whole job, mechanic, dedicated to them
> 
> it is gonna be great, wait and see

I've thought it would be really neat to have a dedicated job for exploration. A fulton pack or some derivative device for getting stuff back to science to research. A mining-like vendor with some progression stuff you could earn to finding those research items.

But that's all way above what I could make and, with so many against space, I'm not sure I could sell it even if I could make it.

If you're making something like that, I'll really look forward to seeing it.

**Comment by atlasle** [comment]
> i imagine a system where there are, get this, "space pods" that can go off station z level without needing a jetpack - like, mountable machines you can fly around
> 
> Instead there will be a whole job, mechanic, dedicated to them
> 
> it is gonna be great, wait and see--------------

I mean why not

**Comment by YehnBeep** [comment]
Well, was worth a try. Long live EVA.

**Pull request closed without merging**
