### PR TITLE
Adds Baldium, the opposite of Barber's Aid

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
This PR adds a chemical called Baldium, which does the opposite of Barber's Aid - it removes hair.

## Why It's Good For The Game
This will make for a good pranking chemical. Unlike the alopecia symptom, it doesn't spread by itself either.

## Changelog
:cl: Denton
add: Added a new chemical called Baldium. Mix radium, sulphuric acid and lye at 395 degrees, and you'll receive a chemical that removes hair when sprayed or splashed on.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
tfw clown adds a little of this to his lube

**Comment by trollbreeder** [comment]
> tfw clown adds a little of this to his lube

tfw clown has a prankmix of lube, colorful reagent, spray tan, and baldium
we should totally make a plant with these reagents, call it clownyflower

**Comment by CRITAWAKETS** [comment]
add a reaction with barber's aid

**Comment by wesoda25** [comment]
bald buff

**Comment by ishitbyabullet** [comment]
**baldies rise up**

**Comment by HomocidlePancakes** [comment]
Baldeeum

**Comment by itseasytosee** [comment]
Both of them should react to each other in a body into some other dumb chemical that makes your hairstyle change every tick or something dumb like that

**Comment by trollbreeder** [comment]
Idea: Baldium and barber's aid mixed together explodes violently into hair monsters that try to eat you and your co-workers.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
