### PR TITLE
Resprites the advanced military track suit

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Tin, redoes the unused(?) advanced military track suit and absolutely murders the fucking bloated palette, jesus christ.

199835738-b4430160-24f6-4f77-baf9-15dc158de2ca

## Why It's Good For The Game
HOly fucking shit you do not need these many COLORS
image
## Changelog
:cl:
imageadd: the advanced military tracksuit has been resprited.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
it comes in the russian surplus crates, keeping the camo would be nice though since it just looks like a basic jumpsuit

**Comment by Addust** [comment]
I think the tracksuit can be found in some space ruins

**Review by Twaticus — CHANGES_REQUESTED** [review]
much cleaner for sure but its also lost any uniqueness in the overall shape. you can get creative with it like adding the hood again or maybe even some pockets akin to the hos jumpsuit. somethin so its distinct from just another jumpsuit

**Comment by Ebin-Halcyon** [comment]
> much cleaner for sure but its also lost any uniqueness in the overall shape. you can get creative with it like adding the hood again or maybe even some pockets akin to the hos jumpsuit. somethin so its distinct from just another jumpsuit

Gotcha, i'll stuff some things back in.

**Comment by Imaginos16** [comment]
Twaticus said it looked good on discord, looks good to go

**Pull request merged**
