### PR TITLE
Revert "[BALANCE] HoS/ERT/DS Armour Buff | Revolver Armour Piercing"

### PR DESCRIPTION
**Pull request by Cheridan**
#10345

HoS shouldn't be nigh invincible to everything but revolvers (which not every antag has), stuns (we're trying to get away from stun dominance) and bombs (lol). SS13 is not a game which benefits from hard counters.

People weren't even supporting the PR in the first place, until it was forgotten about and merged by our sprite manager.

If the HoS armor does need a boost we can all talk about raising it a bit and meeting a happy medium.

### CODE REVIEW

**Comment by Ikarrus** [comment]
@Cheridan Can we also revert this that WJ also merged?

https://github.com/tgstation/-tg-station/pull/10384

**Comment by SconesC** [comment]
People HAVE been talking about it.

They're the HoS. 60 brute is to mitigate combat with simple mobs and retards with toolboxes.

**Comment by Anonus** [comment]
Talking is not the same thing as supporting.

**Comment by Dorsisdwarf** [comment]
I support it, it means that one shitface with a stunprod can't just pull it out when you're going for someone with your egun, switch to laser, and crit you in a single clip using just the prod stun.

**Comment by WJohn** [comment]
Why are you fully reverting the deathsquad stuff, they're supposed to be unstoppably powerful.

**Comment by Anonus** [comment]
They'll be similarly unstoppable even with less armor, given that they have nanites, which are basically adminordrazine or whatever.

**Comment by Lumipharon** [comment]
It was dumb to JUST unnerf these few bits of armor, when almos every other piece of armor in the game is still nerfed.

Like holy fuck, whether you agree with the changes or not, where the fuck is the consistancy?

**Comment by Steelpoint** [comment]
Ill comment later when I'm on a computer.

But Cheridan, people have been talking about and supporting these changes. The reason it was merged was that no other maintainer did their job and look at the PR and I waited two weeks until I seemed out for help getting it merged.

**Comment by Iamgoofball** [comment]
@Ikarrus 
What? Why? everyone approved of that change.

**Comment by Steelpoint** [comment]
The majority opinion has almost never mattered, which is why I find it hypocritical that Cheri is using the excuse of the majority opinion when he himself has been a enabler of unpopular PRs being merged. So long as you have power or influence you could merge almost anything.

**Comment by Steelpoint** [comment]
Finally I don't think Cherish understands or even looked at what values I unnerfed, I never touched the HoSs bomb defence, and I doubt anyone will ever be immune to bombs.

**Comment by Cheridan** [comment]
I didn't say he was immune to bombs, I said stuns and bombs were the only options left.

**Comment by Steelpoint** [comment]
Hence why I really should stop posting on my phone.

**Comment by Steelpoint** [comment]
@Lumipharon I was unnerfing other armour for consistency but that PR was closed.

I went out of my way to involve as many people as I could in the discussions, I even pinged every single maintainer and went onto IRC, I even kept posting in the PR long after discussion died. If anyone did not participate in that discussion then it's not from me trying to stealth merge my PR.

**Comment by Falamazeer** [comment]
Hey I wigged out on the first draft of this, but steelpoint put a lot of good thought into the final draft of  the HoS coat, I was highly critical, but the numbers arrived at in the end seemed pretty reasonable for what should be the second hardest non antag/silicon target on station after captain.

Please reconsider this rever-ception PR.

**Comment by Steelpoint** [comment]
In this very PR, aside from myself and Cheridan, two people support needing armour while four support  keeping the new values.

The values I made for the HoS are a good middle ground in my opinion, it means you can't just stun him and beat him to death with a null rod or toolbox. Yet the old values allow even a assistant with a bannna or stun prod to kill the HoS, let alone any antag with antag item.

**Comment by CPTANT** [comment]
:-1: 

The HoS is the one person on board of the station people are supposed to fear. This is a bad solution for a fundamental problem which is the dominance of stun combat.

**Comment by Robustin** [comment]
HoS is the station's final fucking boss most rounds. Captain's are more often just memesters who sit on the bridge thinking of the next random CRRAAAAAZZZYY way they can promote the clown, belittle your enemies, or recall the shuttle repeatedly because if the bridge isn't a hole to space or filled with burning plasma then you don't see a reason to leaver yet.

HoS is the final boss. He's the line in the sand that separates order from chaos, he's the guy that symbolizes the might and robustness of security at its best. His armor should absolutely be a very real and serious factor in a fight.

This is coming from someone who plays antagonists more often than the HoS, and probably plays either more than the rest of the coderbus combined. HoS should be a beast, not someone who just requires one additional hit-to-crit from most weapons.

**Comment by Dorsisdwarf** [comment]
Cheridan thinks of player feedback as a tool for getting his own stuff merged
Player feedback thinks of Cheridan as a tool for getting his own stuff merged.

**Comment by KorPhaeron** [comment]
@Robustin 
I'd say the captain is more the final boss since he has, you know, the key to destroying the entire station, as well as all access, and several traitor objectives on his person at any given time.

**Comment by Steelpoint** [comment]
@KorPhaeron as Scones pointed out on the forums, and I will quote.

> The Captain is the figurehead and the HoS is his right hand man and the long arm of Nanotrasen power. The Captain is not a warrior-king - He is capable, but is best suited to letting the fighters do the fighting.

> The Captain does not seek out conflict. The HoS does. The current HoS armor and Cap armor values are fairly similar, the only difference being that the HoS coats cover limbs.

The head of security is the best as being security, the captain is more of a jack of all trades person who delegates to his heads.

**Comment by KorPhaeron** [comment]
That's all well and good and lore friendly but it's an objective fact that killing the captain results in the station getting nuked in at least one game mode. I don't know how much more "final boss" you can get than that.

He's also far better equipped to deal with a psychotic AI, having insulated gloves, a hand tele (can't be bolted) the pinpointer, and access to blow the borgs.

Off topic but I'd love if the HoS could get all access so he doesn't have to beg the AI or captain to let him raid certain rooms.

**Comment by Dorsisdwarf** [comment]
HoS can damn well talk to the command staff if he wants all-access. Otherwise he'd be a captain with snazzier armor.

**Comment by Steelpoint** [comment]
Don't stray too far off topic, this is about armour for the HoS, ERT and DS not the HoS's access.

**Comment by Falamazeer** [comment]
Lore and starting inventory be damned, Don't ignore the fact that most captains fuck off and are impossible to reach and/or force to do their job, the HoS is also held to a higher standard than the captain policy wise, as he has the same standard of being a head and the added seccurity pressures as well.

It's supposed to be a rewarding but difficult job, have mercy cheridan

**Comment by Steelpoint** [comment]
I should note before the inevitable merge that I was banned from the coderbus IRC for wanting to discuss this PR.

**Comment by Cheridan** [comment]
Because I'm tired of your political ad hom bullshit, fuck off

**Comment by Cheridan** [comment]
actually i'm reopening this solely to make steelpoint madder; merge it or don't, i don't care

**Pull request merged**
