### PR TITLE
Revert "Better species environment handlers, and custom race body temperature"

### PR DESCRIPTION
**Pull request by Cyberboss**
Reverts tgstation/tgstation#48321

### CODE REVIEW

**Comment by TheSilverNuke** [comment]
What was wrong with it?

**Comment by Cyberboss** [comment]
image

**Comment by nightred** [comment]
Working on the fix.. we do not need suits being cookers.

**Comment by trollbreeder** [comment]
uh oh, spicy

**Comment by itseasytosee** [comment]
Please fix this

**Pull request merged**
