### PR TITLE
Light step quirk rebalance

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Removes the no bloody footprints part of light step and replaces it with quieter footsteps that cant be heard from quite as far away. Quirk price upped from 1 to 2.

## Why It's Good For The Game
This quirk is a no-brainer always get right now, because it is extremely useful. This rebalance makes it a bit more on theme, more situational and more expensive.
Should also make some more janitor work, which is always good!

## Changelog
:cl: Skoglol
balance: Light step no longer prevents bloody/oily footprints, instead gives you quieter footsteps. Price upped to 2, from 1.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Janitor nerf

Imagine the forced departmental cooperation as he has to fight chemistry for space cleaner

**Comment by Couls** [comment]
> Janitor nerf
> 
> Imagine the forced departmental cooperation as he has to fight chemistry for space cleaner

why do you think he gets a .357 on garbage day?

**Comment by kriskog** [comment]
Pro tip: Galoshes dont make bloody footprints.

**Comment by HomocidlePancakes** [comment]
>This quirk is a no-brainer always get right now, because it is extremely useful.

What? Why? How... You just don’t make floors dirty.

**Comment by SkeletalElite** [comment]
> > This quirk is a no-brainer always get right now, because it is extremely useful.
> 
> What? Why? How... You just don’t make floors dirty.

Yeah this kind of confused me. The most powerful thing about this quirk only applies if a slaughter demon is around, even then its whatever because slaughter demons usually drag bodies around to make stuff bloody anyways.

**Comment by ATH1909** [comment]
Why do you think that _Light Step_ needs a nerf? Yeah, not tracking blood everywhere is _nice_, but it hardly makes the Light Step quirk a "no-brainer" choice.

**Comment by Anonmare** [comment]
I use light step cause I hate footprints with a burning passion

**Comment by kriskog** [comment]
It's an easy powergamer staple, I should know as I've had it on since I started playing. Not tracking blood means your voilent bloody activities are much much easier to hide.

**Comment by Mickyan** [comment]
I'm biased since I made the footprints change but I'd agree with the price increase, the double nerf is excessive and just makes for a more boring quirk

**Comment by wesoda25** [comment]
> It's an easy powergamer staple, I should know as I've had it on since I started playing. Not tracking blood means your voilent bloody activities are much much easier to hide.

You can literally take off your shoes lol. Or use a bar of soap on them which takes 2 seconds. Time saved which is the point of the quirk.

**Comment by kriskog** [comment]
Both those things require resources available or give you other drawbacks

**Comment by Shadowflame909** [comment]
Don't tell him about scooters

**Comment by HomocidlePancakes** [comment]
Kriskog, you are spewing some din dum dumb right about now. You just don’t leave footprints. Yeah, it can be used to hide bodies, but it does not play that big of a role that you are presenting it to be. Honestly, this just makes you look like a massive tool.

**Comment by wesoda25** [comment]
> Both those things require resources available or give you other drawbacks

...ok? The drawback from the quirk is the negative traits you take to get it?

**Comment by ExcessiveUseOfCobblestone** [comment]
WAIT THIS PERK IS GOOD AGAINST BUBBLES??

**Comment by Shadowflame909** [comment]
That nerd makes his own blood

**Comment by ExcessiveUseOfCobblestone** [comment]
the meme used to be taking your shoes off to fight him but that at least puts you in the way of cacti btfo

**Comment by Shadowflame909** [comment]
Don't tell Cobby about the mounting a cleaning borg with VTEC since they don't take damage slowdowns strat

**Comment by Pugie** [comment]
Make sure to make family hierloom a positive qurik while you're at it.

**Comment by HomocidlePancakes** [comment]
That was a thing before Bubble rework, Cobby. It doesn’t work anymore.

**Comment by Pugie** [comment]
Also uh oh crime scene has no bloody footprints set all people with light step to arrest

**Comment by Pugie** [comment]
Also uh oh crime scene has no bloody footprints set all people with light step to arrest.

**Comment by carlarctg** [comment]
-----1 i like my shoes unbloodied

**Comment by AWalton** [comment]
Like there's not a trail of blood regardless if you've killed someone and/or dragged them away.

The reasoning is pretty poor, you could just as easily argue quieter steps is useful for illicit activities since you can ambush people or carry bodies through areas without those nearby being aware. Or argue any number of other quirks are useful for it. Why have positive quirks at all with that reasoning.

**Comment by kriskog** [comment]
I had a feeling you people are as reliant on this quirk as I am, it's why I made the PR. This part of it is clearly too strong if a nerf has this bad of a reaction.

It's still intended to be a positive quirk, but in a subtler way than for no reason requiring no cleanup after you make a mess. Did you all know you can tell shoe type from footprints? Bet you didnt since noone makes them anymore.

**Comment by Mickyan** [comment]
I dont even use this, plus "nobody makes footprints anymore"? You know that's not true at all.

Again I could agree with the points increase but I think you're grossly overestimating it's usefulness, it's trading a niche advantage for a permanent disadvantage, which is how quirks are generally balanced for. You should take a look at the "free points" quirks that get gamed a lot instead, like family heirloom, so that this one becomes less of a no-brainer.

**Comment by Fikou** [comment]
why increase the price and then nerf it??? why not just one or the other, that makes no sense

**Comment by nemvar** [comment]
@Shadowflame909 VTEC has been removed ages ago and also hasn't been working for at least a year before that.

**Comment by Shadowflame909** [comment]
Strat still works otherwise no one would roll mining borg

Also why is people disliking this PR a good thing. There doesn't even need to be examples of why that's a bad take

**Review by ninjanomnom — APPROVED** [review]

**Comment by Shadowflame909** [comment]
What a lame speedmerge. Not even a maintainer comment. Nigh a simple "looks good"

**Comment by ninjanomnom** [comment]
Discussion happens in more places than just github and I don't need to comment when other people have already had the arguments for various points for me. All I need to do is read.

**Comment by wesoda25** [comment]
> I had a feeling you people are as reliant on this quirk as I am, it's why I made the PR. This part of it is clearly too strong if a nerf has this bad of a reaction.
> 
> It's still intended to be a positive quirk, but in a subtler way than for no reason requiring no cleanup after you make a mess. Did you all know you can tell shoe type from footprints? Bet you didnt since noone makes them anymore.

Bro no ones reliant on this quirk at all, I’m just doing smoker + tagger currently. Its just a good quirk and nice to opt into at times. If you’re complaint was bubblegum powergaming I would understand, but the reasons you’re using are lame as fuck tbh, its a complete non issue. 

If anything quieter footsteps is better for antags, but no one cares because they use the quirk for cosmetic reasons.

**Comment by Anonmare** [comment]
I have never once noticed the sound of footsteps in a noticeable way to be honest.

**Comment by MCterra10** [comment]
Kriscog, cease now, these nerfs are getting out of hand!

**Comment by HomocidlePancakes** [comment]
I am late but whatever.

>Discussion happens in more places than just github and I don't need to comment when other people have already had the arguments for various points for me. All I need to do is read.

That’s cool and all, but we still don’t know your reasoning, we just know it *exists*. This isn’t any different from telling people to fuck off.

**Comment by ExcessiveUseOfCobblestone** [comment]
the fact it can ease bubblegum's fight is worth rebalancing it alone tbh.

**Pull request merged**
