### PR TITLE
Harvesters are now cultists and can scribe runes

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Harvesters are now cultists and can scribe runes.
/:cl:

This is a very roundabout way of making ratvar vs narsie more fair.

Also adjusted the mindless constructs created if a mob has no mind but is affected by nar-sie to include juggernauts, wraiths, and artificers.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
But then cultist will whine about being teamkilled by harvesters again

And it will completely ruin the round end report with harvester spam

**Comment by KorPhaeron** [comment]
>This is a very roundabout way of making ratvar vs narsie more fair.

This has literally never happened naturally and probably happen maybe once or twice naturally over the life span of this game. The chances of both teams simultaneously finishing their objective is almost zero, never mind the game mode where this could occur doesn't even exist.

**Comment by ChangelingRain** [comment]
Okay I've fixed infinite harvester spam; only harvesters that are actually ALIVE will be in the list of cultists, so all the dead harvesters, of which there will probably be quite a few, will not show up in the huge fucking list of cultists.

**Comment by ChangelingRain** [comment]
Wait this doesn't work at all may it rest in peace

**Pull request closed without merging**
