### PR TITLE
Refactors genetic damage component to be a status effect

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

The genetic damage component looked like a status effect, swam like a status effect, quacked like a status effect, but wasn't a status effect.

Irradiated component is also guilty of this, but it has the excuse of also getting applied to items. This one only applies to mobs though, so...

## Why It's Good For The Game

Easier to maintain code, that's about it.

## Changelog

Not player facing.

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
radiation rework still sucks btw

**Comment by Mothblocks** [comment]
you moved 70 lines of code to a different file. quit being a shithead

**Comment by ChungusGamer666** [comment]
> you moved 70 lines of code to a different file. quit being a shithead

title is obviously hyperbole, lay off the meth

**Comment by san7890** [comment]
can you at least rename the title of this PR to actually say the name of what you reworked

**Pull request merged**
