### PR TITLE
Airlocks animate faster

### PR DESCRIPTION
**Pull request by PopNotes**
🆑 PopNotes
imageadd: Airlocks animate faster. This doesn't change the time it takes to pass through an airlock, but it does visually match up much better so you don't just appear to glide through the airlock while it's half-open.
/🆑

### CODE REVIEW

**Comment by PopNotes** [comment]
there we go

**Comment by PraiseRatvar** [comment]
needs video/visual

**Comment by PopNotes** [comment]
slow/old:
 

fast/new:

**Comment by GunHog** [comment]
Someone should add more frames to smooth it out.

**Comment by Cyberboss** [comment]
That would be much appreciated

**Comment by ChangelingRain** [comment]
See #5936 for the original change reason, maybe decrease the amount of time they count as open for if you think it's too much, but I think this makes them too fast.

**Comment by PopNotes** [comment]
Except this is purely visual and doesn't change a single line of code.

**Comment by ChangelingRain** [comment]
That change was to match the visuals, though, so you should consider it while doing this.

**Comment by Tacolizard** [comment]
@PopNotes could you PLEASE do what @GunHog said? It probably wouldn't be that hard.

**Comment by DoctoreMad** [comment]
I would prefer the "its open when its fully open" option allows me to find the X in "X SPRITE = DOOR IS OPEN IN GAME CODE TERMS NOW" choice faster.

@Tacolizard But if he did what GunHog said then either nothing would change or this would be a balance change.

**Comment by PopNotes** [comment]
@Tacolizard Except it would be INCREDIBLY fucking tedious. Not difficult, tedious.

Going through literally every airlock sprite and setting the animation speed for the various opening/closing animations took me a good hour of nonstop monotony, I FEAR what it would be like to manually add in-betweens for every single airlock animation/overlay. Not going to happen.

**Comment by DoctoreMad** [comment]
THAT'S THE ENTIRE POINT OF THE PR

**Comment by Cyberboss** [comment]
There's two camps here from what I can tell:

1. Thinks 3/4 open should be open in terms of density
2. Thinks 100% should be open in terms of density

This PR is a purely visual change, but that mechanic is being altered from 1 to 2 with it. I personally have no opinion on it.

**Comment by YotaXP** [comment]
So what happens when the airlocks close?  Do they go dense immediately, or is there a delay?  If there is a delay, this change will be a problem.

**Comment by Cyberboss** [comment]
Airlock densities currently change halfway through their animation

**Comment by YotaXP** [comment]
>Airlock densities currently change halfway through their animation

Then it appears we have a problem.  Either the closing animation will need to be kept slow, the PR be dropped, or the delays be removed/changed.  Should probably get more player opinions.

**Comment by Bawhoppen** [comment]
It's still purely visual technically

**Comment by DoctoreMad** [comment]
I have been making little leeway in discovering why people are angry about the airlock animation change. I first theorized that they did not understand that this was purely a visual change, but I noticed some of them were coders who could look at the file commit.
Now I have a incredibly open mind for arguments so I'll try more prodding

@YotaXP 

>Then it appears we have a problem. Do X or Y.

That's a really vague statement that doesn't explain your problem with this PR. What IS your problem with the PR?

**Comment by Bawhoppen** [comment]
I think their problem is with the door closing, because if the animation is faster and you still want it to sync up with the density, the animation will have to not play right away, but you've still made it do so.

**Comment by ChangelingRain** [comment]
also if you don't adjust the door you'll have periods where it's open/closed and you can't close/open it for no apparent reason.

**Comment by YotaXP** [comment]
@DoctoreMad As in, the door may appear to be mostly closed, and yet is still passable.

**Comment by Bawhoppen** [comment]
@YotaXP Theoretically the animation would start with a delay before it began to open so it was in sync with density.

**Comment by optimumtact** [comment]
bikeshed

**Comment by Bawhoppen** [comment]
Having a feature work properly isn't bikeshedding.

**Comment by Cyberboss** [comment]
Good lord...

**Comment by WJohn** [comment]
This is cool with me.

**Comment by optimumtact** [comment]
Do the needful

**Comment by PopNotes** [comment]
what do

**Comment by optimumtact** [comment]
`regardless of when you want it to be dense you still need to update the open and close procs so it's properly open/closed when it appears to be`

this from joan?

**Comment by PopNotes** [comment]
so just what value should I change the open/close timers to

**Comment by optimumtact** [comment]
I dunno buddy, it's your pr

**Comment by jughu** [comment]
Biased citrus

**Comment by PopNotes** [comment]
okay but what do tho

**Comment by optimumtact** [comment]
I dunno ask joan

**Comment by ChangelingRain** [comment]
You need to update the timing on the open and close procs for airlocks, that's it

**Comment by DoctoreMad** [comment]
Guys, this is the thread that keeps me up at night.
The speed of the open and close procs was the factor that made him speed up the animation
The open and close procs ARE the speed of the animation. This PR is made with this express purpose.
If you dislike doors being, game-mechanic wise, closed only when they are closed, and open only when they fully open, you downvote this or something instead of pulling what you are pulling right now. I liked it because sprites are just sprites and this change makes it easier for me to translate "THIS DOOR IS OPEN=X SPRITE" and "THIS DOOR IS CLOSED=Y SPRITE" in my mind.

WHY

**Comment by PopNotes** [comment]
oh, huh

**Comment by DoctoreMad** [comment]
I didn't write a single lie but I still feel like I pranked orange guy.

**Comment by YotaXP** [comment]
@DoctoreMad What about the closing animation?  The animation appears to close faster, but that only means the door will APPEAR to be closed before it actually becomes unpassable.

**Comment by Bawhoppen** [comment]
It seems to work fine ingame I'd just stop worrying

**Comment by CPTANT** [comment]
I now have the feeling I am walking through closing doors that look closed but are actually still passable.

**Pull request merged**
