### PR TITLE
Double-Esword Blockrate Fix

### PR DESCRIPTION
**Pull request by Robustin**
Removes obsolete code for buffing twohanded block weapons, makes the double esword block properly at 75%

### CODE REVIEW

**Comment by KorPhaeron** [comment]
You realize that double eswords already roll twice to block because the offhand counts as a shield as well, right?

**Comment by Robustin** [comment]
No Kor clearly I DONT know that or I wouldn't have made this dumb PR, going to test it now just to be sure.

**Comment by Robustin** [comment]
Ok I learned several things from testing:
1) Double e-meme melee block rate is 50%
2) Chairs no longer block shit what the fuck
3) Swords in each hand block at 75%

**Comment by PKPenguin321** [comment]
Chairs only block unarmed attacks iirc

**Comment by Robustin** [comment]
Huh, that might be it then. Either way double-esword only block 50%. An esword in each hand blocked 75%, buff that dat shit.

**Comment by Bawhoppen** [comment]
why does it need a buff it doesn't need a buff

**Comment by TheNightingale** [comment]
The best buff it could receive would be "do 60 brute damage to anyone who tries to disarm you". Just slice their arm off.

**Comment by Robustin** [comment]
Baw, it needs a buff. It wasn't a great item when it was released years ago and its been shat on since then.

Telescopic batons, buffed melee knockdowns, more ballistic firearms for crews. Dbl-eswords when you can just get a sentient floating esword and personal life-saved called "Holoparasites" for 2 LESS TC means that you don't see people getting it unless they get it by accident in a crate/kit.

**Comment by KorPhaeron** [comment]
Maybe we should fix the bug that makes the offhand not count as a shield

**Comment by Robustin** [comment]
But Kor is it even a bug?

The code looks like it was designed to make sure you don't stop blocking if you switch to the "offhand" of a 2-handed weapon. It doesn't look like the intent was to make each "hand" of a two-handed weapon block independently like Sword+Sword does.

**Comment by Cheridan** [comment]
>Baw, it needs a buff. It wasn't a great item when it was released years ago and its been shat on since then.

to be fair when i added it it was a joke/show-off item with 0 benefit. then ergo turned it into this super block chance thing and they became meta

**Comment by KorPhaeron** [comment]
Looks like I bugged twohanded shield stuff in the block refactor.

**Comment by Robustin** [comment]
Isn't this just a smarter approach though? 

Have the item's blockchance represent... its blockchance? It actually works as described right now. If we went the method you're describing it becomes more obtuse and won't be obvious to anyone reading the code that offhands function as an invisible shield.

**Comment by KorPhaeron** [comment]
Fair point. Please delete the old offhand hit_reaction code from the file then. Starts at line 121.

**Comment by Robustin** [comment]
I made the change, I thought it was necessary to ensure the dblsword kept working if you switched to an offhand while wielding it.

**Pull request merged**
