### PR TITLE
Removes changeling leftover ability from evulutionlings, spiders.

### PR DESCRIPTION
**Pull request by improvedname**
Yeah so just extract string 5 people and spam spiders the rest of the round to make the crew scream

:cl: Improvedname
del: Removes spiderling spiderspread ability
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
i didnt die by it though kek

**Comment by GuppyLaxx** [comment]
# **nO.**

**Comment by improvedname** [comment]
Its a bad ability
it just ends in changelings spamming spiders in a secluded arena
and since the new changelings not requiring dna absorptions anymore this is just roundstart

**Comment by 81Denton** [comment]
i ded

**Comment by ExcessiveUseOfCobblestone** [comment]
why not just require req_dna to only work with absorption

**Comment by PKPenguin321** [comment]
I could make this only count absorption-gained DNA instead of DNA sting-gained DNA after I'm done with my overhaul PR if that'd be a better fix

**Comment by juanototo2** [comment]
# No

**Comment by Poojawa** [comment]
itt:

Changlings who stand in maint over a vent and spam spiders saying 'No'

8^)

**Comment by improvedname** [comment]
Also if anyone was asking what triggered this pr.
I was observing a round today.
Where a changeling kept spamming spiders and recalling the shuttle and then just gone back to spamming spiders thats all what he did

**Comment by PKPenguin321** [comment]
As I said I could make this require actual absorption and not DNA sting to make it balanced as intended. Removal is somewhat heavy handed

**Comment by improvedname** [comment]
It be appreciated pkp but be honest to yourself then its just bites dust and never used

**Comment by PKPenguin321** [comment]
can easily be lowered to like 3 absorptions then. i doubt it will *never* be used.

**Comment by improvedname** [comment]
3 absorptions sounds fine

**Comment by PKPenguin321** [comment]
ok. like i said i will hold off from doing it until my ling overhaul thing is done because >conflicts so yea

**Pull request closed without merging**
