### PR TITLE
Carp Expansion Pack [greyscaled]

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR ports Baystation color carps, credits to them.  In short, normal carps can now spawn in variety of colors, example image of some of the variants below:

CarpColors

UPDATE: I was asked to do this via greyscale, so I am giving updated image for comparison, with this method, we can have much more color variants, but they will look more alike:

NewGenerationReady

This only affects normal carps, not special ones like magicarps or megacarps, these retain their own unique sprite. There are also some pretty rare color variant for carps and our friendly Syndicate carp Cayenne has increased chance to get it.

## Why It's Good For The Game

Better aesthetics and immersion.

## Changelog
:cl: Arkatos
imageadd: Normal carps now spawn with a random color! There might even be some really rare color variant.. try asking Cayenne about it.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
different sprites but no special gameplay? sad

**Comment by ishitbyabullet** [comment]
Thought the bright purple one was removed and replaced.

I never heard anything about it however I just figured.

**Comment by Fikou** [comment]
hos fish on delta should get a chance too

**Comment by wesoda25** [comment]
Make them have different abilities like orange one ignites people it hits, blue injects cold sauce, etc etc

**Comment by ishitbyabullet** [comment]
Nah, just keep it simple.

There's multiple fish in real life however none of them inject lava just because they're red.

**Comment by Qustinnus** [comment]
guys you realize we can make them do special shit in a seperate PR right? not every PR has to contain 500 gameplay changes.

**Comment by ishitbyabullet** [comment]
Maybe they just want to make oranges not deny it because sprite bloat

**Comment by Qustinnus** [comment]
wtf is sprite bloat

**Comment by ishitbyabullet** [comment]
I don't have a real answer since i don't study sprite bloat however I believe that what you add needs to have some sort of purpose otherwise it will be removed.

**Comment by Qustinnus** [comment]
it makes the game look better and more polished I think that on its own is reason enough, else we might as well remove most haircuts and clothing sets from the game

**Comment by Shapsy** [comment]
Rare carp

**Comment by Tlaltecuhtli** [comment]
what we dont need is more socks

**Comment by HomocidlePancakes** [comment]
A shiny Magicarp...

**Comment by ExcessiveUseOfCobblestone** [comment]
why not just greyscale the body then color it up so we can have RAINBOW FEESH

**Comment by ExcessiveUseOfCobblestone** [comment]
> sprite bloat

???

**Comment by tralezab** [comment]
these are ugly

**Comment by optimumtact** [comment]
cobby is right, the correct way to do it is greyscale the body and use the color var

**Comment by Fikou** [comment]
> why not just greyscale the body then color it up so we can have RAINBOW FEESH

when will we do that for holoparas too

**Comment by optimumtact** [comment]
when you do it I guess

**Comment by Arkatos1** [comment]
I would do it with greyscale, but I am not sure how to achieve the exact colors and shading as it is on image above, I have modified white carp sprite to function as a base, but.. its not exactly what have I aimed for. From my tests:

greyscale carps

Any advice is appreciated.

**Comment by Arkatos1** [comment]
@optimumtact I have done it via greyscale, main post updated with new images for comparison.

**Comment by Krysonism** [comment]
These seem a little dark and low contrast. can you at least make the eye highlight much brighter?

**Comment by Arkatos1** [comment]
@Krysonism You are right, I have made a little lighter greyscale model and highlighted eyes. Main post updated with newest model, but I will leave comparison below:

OLD:
Greyscale carps

NEW:
LighterGreyscale

**Comment by knacker48** [comment]
The only problem I see is that it makes it less obvious if a carp is a magic carp. Ideally it would better if the magic carp had more obvious differences from regular carps(maybe some different designs or something), but barring that maybe you could remove the red coloured one?

**Comment by Arkatos1** [comment]
@knacker48 Very well, I have removed the red variant.

**Comment by habader** [comment]
you'd better be keeping the old purple carp as a random spawn

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> > why not just greyscale the body then color it up so we can have RAINBOW FEESH
> 
> when will we do that for holoparas too

wyci

**Pull request merged**
