### PR TITLE
New shuttle loan event + fixes

### LINKED ISSUE #7832: Centcomm supply shuttle loan doesn't actually bring anything on the shuttle
You get the message and supply points, but nothing is on the shuttle when it arrives.

To reproduce: have the shuttle be at centcomm. select loan to centcomm. once done, select send to station. be dissapointed when you find an empty shuttle.

This apparently was broken for a while and no one bothered reporting it.

### PR DESCRIPTION
**Pull request by Perakp**
- Fixes shuttle loan events not bringing anything to the station. The objects created for the event were destroyed at Centcom.
- Removes supply order crates from shuttle loan events. These were pretty unintuitive, as you needed to accept the crates separately.
- Adds a new shuttle loan event: Centcom wants you to help in a virus research program. I feel this is a more controlled way of bringing diseases on the station compared to the disease outbreak event.
- Fixes camera failure event
- Fixes spanish flu, adds spanish flu culture bottle

Fixes #7832

### CODE REVIEW

**Comment by Jalleo** [comment]
Nobody expects the Spanish flu

**Comment by Thunder12345** [comment]
Why not rework the resupply event to work properly rather than removing it?

**Comment by Dorsisdwarf** [comment]
Agreed, the resupply is a pleasant suprise for cargo instead of CLICK BUTONE TO DIE

**Comment by Perakp** [comment]
Tested that the supply shuttle actually works after the event with these changes. Could not reproduce #8790

**Pull request merged**
