### PR TITLE
Adds potassium iodide to NanoMed Plus

### PR DESCRIPTION
**Pull request by erwgd**
## About The Pull Request
This PR adds one potassium iodide bottle to NanoMed Plus vendors. The number of epinephrine bottles is reduced to 3.

_see history for earlier proposed changes_

NanoMed Plus:
1x anti-radiation bottle (30u potassium iodide)
3x epinephrine bottle (was 2x)

Fixed typos with pentetic acid items.

## Why It's Good For The Game
This will give Medbay something at roundstart for radiation.

This won't make any chemical bounties easier.

## Changelog
:cl: Erwgd
add: Swapped out an epinephrine bottle for potassium iodide in NanoMed Plus vending machines.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
so we take away the sleepers so you have to work with chem more and your first response is to add more chemicals at roundstart?

:joy:

**Comment by erwgd** [comment]
Think I'll trim this down to just potassium iodide.

**Comment by subject217** [comment]
almost like the idea of "working with chemistry" is pure conjecture and no amount of medbay nerfs will make it spontaneously start to happen...

**Comment by optimumtact** [comment]
it won't happen until it's forced to happen subject, don't know if you missed the memo

**Comment by subject217** [comment]
If you forcibly make Chemistry un-fun they'll stop playing Chemist and just compete for the two botanist slots. And at that point you might as well just give MDs Chemistry access or vice versa. Chemists don't help medbay because it's not fun. You can't really force people to do something that isn't fun ingame consistently every round without at least some sort of reward. Attempting to force the interaction is absolutely the worst way to go about this.

**Comment by erwgd** [comment]
More often than not, chemists do their best to supply Medbay with synthflesh and cryo mixes, which handle most situations well. Things like corazone and antihol aren't a priority when cheesing them is doable.

I'll trim this down a lot. A third salbutamol in the NanoMed Plus, 4 potassium iodides and 2 more in the wall-mounted vendors.

Chemicals are needed to limit radiation damage but it's often inflicted at large scales. A roundstart supply of potass iodide would help supplement the anti-rads chemists often make with their limited energy. Doctors can check in on the chemist for updates but letting them churn out what they can and calling Engineering for inducers is all they can really do right now.

**Comment by RaveRadbury** [comment]
Would it be too much to have some mannitol on-hand at round start? For people with the brain tumor quirk.

**Comment by necromanceranne** [comment]
Genetics starts with a bottle of mannitol and mutadone, which has several 50u pills of both. You don't NEED 50u of mutadone to remove mutations, and mannitol can be more reasonably separated out, so filching those is a good move.

**Comment by anconfuzedrock** [comment]
nanomed doesn't need potass iodide, it has charcoal. maybe the large ones.

Antihol has no place in the nanomed. it's an edge-case drug in every form. If you need it that bad, use a stasis bed and you have time!
corazone is lol

**Comment by Repukan** [comment]
If someone drinks enough alcohol to need antihol, that's just natural selection at work

**Comment by Angustmeta** [comment]
People are not stopping playing chemist any time soon. It's one of the contested "high" jobs on mid/highpop. 

Nanomed menu is bloated already with insulin and stuff imo.

**Comment by necromanceranne** [comment]
Just dodge the shotgun darts full of bacchus what the hell you can't dodge a bullet lol you deserve death

Also charcoal doesn't remove rads it just treats the toxins. Potassium iodine removes rads. That's more important than treating the symptoms. Though potassium iodine is literally two button presses so like if that is not being for by chemistry you have to consider demoting those chemists.

**Comment by Tlaltecuhtli** [comment]
potassium iodine sucks and the adv medkit has like 45u pentetic each, just buy it for only 599$

**Comment by ExcessiveUseOfCobblestone** [comment]
> Just dodge the shotgun darts full of bacchus what the hell you can't dodge a bullet lol you deserve death
> 
> Also charcoal doesn't remove rads it just treats the toxins. Potassium iodine removes rads. That's more important than treating the symptoms. Though potassium iodine is literally two button presses so like if that is not being for by chemistry you have to consider demoting those chemists.

charcoal plus shower lol

**Comment by ExcessiveUseOfCobblestone** [comment]
I forgot to remove salbu from roundstart btw whoops.

As for the purpose of this PR, i'm not really a fan. KI is super easy to make should someone have rads and Cora/Antihol are pretty niche for a generic startup vendor.

**Comment by AdamElTablawy** [comment]
tbh for all the hubbub oranges makes about chemistry the only chemicals chemistry makes are silver sulfadine, synthflesh, stypic powder, and mannitol

and rarely charcoal if someone comes in with severe toxin damage

anything else and the guy just goes into the cloner, usually. making medbay 'more reliant' on chemistry's advanced chemicals just means you won't ever see those advanced chemicals lmao. nothing wrong with adding potassium iodide to the medbay vendors.

**Comment by optimumtact** [comment]
that is exactly the situations we are trying to improve and it doesn't help if you keep adding reasons why they shouldn't need to actually do anything.

we're on a journey here not a fucking step change

**Comment by OverlyGeneric** [comment]
> that is exactly the situations we are trying to improve and it doesn't help if you keep adding reasons why they shouldn't need to actually do anything.
> 
> we're on a journey here not a fucking step change

it makes me wonder if chemistry would work better as a science-only department instead of a medical-only department.

 it could be connected to medical by a windoor or have a request console. 

i honestly don't know, orange lad.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'll accept bottles of KI in the medivends but for everyone you add you have to take something else away.

24 hours after this post me close if no update/response.

**Comment by ExcessiveUseOfCobblestone** [comment]
thanks for not touching salbu I would have cried

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
remove the prebuilts you are no longer using then this is okay to go :3

**Pull request merged**
