### PR TITLE
Hulks will be briefly knocked down by Judicial Explosions

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Hulks will be briefly knocked down by Judicial Explosions.
/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
Hulks are stun immune, live with it.

**Comment by PKPenguin321** [comment]
untitled

**Comment by swankcookie** [comment]
@PKPenguin321 noice

**Comment by ChangelingRain** [comment]
0/10 avatar is already angry and crying

**Comment by CPTANT** [comment]
brb looking for a picture of a very special snowflake.

**Comment by kilkun** [comment]
No.

**Comment by anconfuzedrock** [comment]
ITS TIME TO STOP

**Pull request closed without merging**
