### PR TITLE
Re-adds the Ian meat steal objective to the game, just like it used to be back in the day.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts #10022

## About The Pull Request

Reverts #10022

## Why It's Good For The Game

This was a classic objective, let's bring it back!

## Changelog
:cl:
add: Ian is now a traitor objective once again, just like the good old days.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
make it specifically ians meat and let cargo techs and qm have the objective

**Comment by nianjiilical** [comment]
you can put ian in your backpack so make ian himself also valid for the objective

**Comment by Qustinnus** [comment]
@TemporalOroboros you reckon we could make anything with Ian meat datum mat work somehow?

**Comment by PKPenguin321** [comment]
It would take like 2 seconds to make it actually require Ian's meat and not just any random corgi. 👎

**Comment by Ratvar** [comment]
It is not Why It's Good For Goof you are supposed to fill in, it is Why It's Good For The Game  
Ian related stuff means shitlers kill Ian fnr, people hunt shitlers, game is worse - so it is removed

**Comment by GoldenAlpharex** [comment]
You could've at least made it with some more effort put into it, by either making sure it's Ian meat in one way or another, this just feels like a lazy revert and I'm sure there was probably good reasons it was removed.

**Comment by Iatots** [comment]
The reason is corgi meat doesn't need to come from ian specifically, or a corgi at all. You can get it roundstart on any station, it's basically a free objective.

**Comment by necromanceranne** [comment]
The reason the other pr even occurred was because of the ease by which you can get corgi meat. Chefs can start the round with corgi meat. 

Just make Ian drop a subtype of corgi meat, and then make that the objective. 

Additionally, this does actually throw some policy problems into the mix here. While killing pets is already going to make you valid, killing Ian becomes not only valid, but also straight up self-antagging/powergaming if you do it enough or to prevent someone from completing that objective by destroying his dropped slab of meat. 

This is kind of a problem when an objective is not only attached to an animal that happens to die fairly often due to being very vulnerable, but the substance he drops is deliberately designed to be consumed. This is unlike all other HVTs which are very, very hard to destroy on accident but can be easily destroyed deliberately. 

Pretty much you're fucked either way on this objective for making it actually reasonable without it being highly unwieldly. A bad case of rose tinted glasses.

**Comment by Qustinnus** [comment]
just make it so you need ian's datum meat datum mat which should be made automatically when you butcher the fucker.

**Comment by Tlaltecuhtli** [comment]
but can you disguise ian s meat inside a burger?

**Comment by KingPhilipIII** [comment]
Make it want his pelt then, and make his pelt a unique object. It can't be destroyed as easily.

**Comment by coiax** [comment]
Pretty much agree with all of @necromanceranne's points.

Stealing Ian is a far more interesting objective, because it also means you need to keep him alive.

**Pull request closed without merging**
