### PR TITLE
Apply sticky items to yourself. So sticky.

### PR DESCRIPTION
**Pull request by sheldoniscool**
## About The Pull Request
You can now tape things to yourself by hitting yourself in grab mode.

## Why It's Good For The Game
Seems fun, opens up fun experimentation.

## Changelog
:cl:
add: You can now tape things to yourself by hitting yourself in grab mode.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
>only allowing harmless embeds from working

weak

**Comment by sheldoniscool** [comment]
> > only allowing harmless embeds from working
> 
> weak

I mean like I'm down to make it all but the problem is items like the edagger you might accidentally imbed into people which would really suck.

I totally will tho if that's what everyone wants.

**Comment by GuyonBroadway** [comment]
If you want to tape an edagger to yourself then you should know exactly what you are doing and what consequences should befall you.

**Comment by Ryll-Ryll** [comment]
My only concern is that since there's no sprite for it and you'd have to manually examine someone to see what's stuck to them, someone could tape a combat shotgun or five to themselves with super sticky tape to walk around strapped like Neo. Then again, you'd already be able to do that with a friend, and it's not like it's been an issue thus far.

**Comment by sheldoniscool** [comment]
> My only concern is that since there's no sprite for it and you'd have to manually examine someone to see what's stuck to them, someone could tape a combat shotgun or five to themselves with super sticky tape to walk around strapped like Neo. Then again, you'd already be able to do that with a friend, and it's not like it's been an issue thus far.

1. You can already do this, all I've done is allow people to stick the item to themselves.
2. The remove time for tape is pretty long so eh.
3. You can stick things to yourself using a teleporter or just have another person doing it.
4. Items on standard sticky tape have a very high chance of randomly falling out.

**Comment by Ryll-Ryll** [comment]
Yeah fair enough then

**Comment by necromanceranne** [comment]
Duct taping badoliers and the shotgun itself is basically free storage. Although, can you actually tape up storage containers?

**Comment by optimumtact** [comment]
Allowing you to tape 6 shotguns to yourself makes no sense.

This can't be merged until tape can only stick smaller items only.

**Comment by GuyonBroadway** [comment]
What if it took time and dealt damage to rip off a taped item scaling with its size.

Cus ripping a shotgun sized area of body hair in one go would damn near kill a man.

**Comment by sheldoniscool** [comment]
> Allowing you to tape 6 shotguns to yourself makes no sense.
> 
> This can't be merged until tape can only stick smaller items only.
> 
> edit:
> so, according to ships, sticky tape only lasts 30 seconds so its' fine.
> 
> Super sticky tape might be a problem, but we'll see.

1. I'm pretty sure ships is incorrect and is referring to value to rip off the item unless I'm mistaken.
2. That being said I still disagree with your assessment since you forget to take into account fall chance. On sticky tape the fall chance is 5% per tick I believe. Meaning there's 0 fuckin way you're going to even get 5 stuck to yourself without the first falling off within the first 10 seconds. I've tested, sticking 5 things on, first fell off within the first 10 seconds and all the others had fallen off within the next 2 minutes.
3. Like said previously, you can already do this using teleporters, or another person next to you.
4. I've seen no one use sticky tape besides myself.
5. You can do the same thing using a locker.
6. You have to spend the time to apply, remove, and get the tape.
7. Even with super sticky tape there's no way you're keeping 5 items on you with out at least one falling off every 30 seconds to minute.

**Pull request closed without merging**
