### PR TITLE
Cockroaches added to Meta and Box. 

### PR DESCRIPTION
**Pull request by KazeEspada**
Focus on maintenance, especially around food and trash. Also, there are some in engineering around the PA as a reference to being rad proof.

### CODE REVIEW

**Comment by Zilenan91** [comment]
Radroaches when?

**Comment by KazeEspada** [comment]
Sprites when.

**Comment by Bawhoppen** [comment]
pls no leave them special :-1:

**Comment by KazeEspada** [comment]
This was always the intention? How are they special? Now if we had the station wrecking monstrosities that VG has, I wouldn't add them to the map.

**Comment by Bawhoppen** [comment]
not everything needs to be there roundstart
cockroaches isn't /that/ big of a deal but its the mentality

**Comment by tkdrg** [comment]
I dunno the sprites really do kinda blow, I feel like they clash with the station a bit too much to be there roundstart

**Comment by Cheridan** [comment]
get better sprites then

**Comment by KorPhaeron** [comment]
Roaches being at the PA means they shove it wildly and fuck it up

Also they are still horribly sprited

**Pull request merged**
