### PR TITLE
Make cyro only use gas and generate heat when in use [DNM]

### PR DESCRIPTION
**Pull request by optimumtact**
In use is defined as having an occupant or having an open door

### CODE REVIEW

**Comment by optimumtact** [comment]
oranges continues his casualisation of gameplay, will it ever end? We have more at 7

**Comment by optimumtact** [comment]
fixes #9308

**Comment by Cheridan** [comment]
>oranges continues his casualisation of gameplay, will it ever end?

time to whine about this on singulo.io

**Comment by Razharas** [comment]
It shall check for being on not for occupant
So it shits shit while active without humie yes dont shits shit while humie is in but is no on

**Comment by optimumtact** [comment]
The only time this thing would ever heat up and be expelling waste gases in any large amount is if it's on and or there is a source of heat inside.

9539 is poop

**Comment by palpatine213** [comment]
Heating gas while it is open or occupied, regardless of being on or off makes sense.
Expelling that gas while it's not on doesn't.
Unless it's actually in use, the cryo gas doesn't do anything to the occupant. It would make sense that some valve would close when the cryotube was turned off.

**Comment by optimumtact** [comment]
Okay I think I understand what @palpatine213 is asking

@Razharas could you try to rephrase what your'e asking? I'm not sure I fully understand

**Comment by palpatine213** [comment]
@optimumtact Sorry, if I was confusing. What I was trying to say was that the cryotube should heat the gas of it is open or occupied, but probably should only actually expel gas if it is turned on.

**Comment by Razharas** [comment]
I think being on is the only state in which it should expel gas
Not when its open or when it has occupant without actually working

**Comment by optimumtact** [comment]
Alright, I'll take a look and see what I can do

**Comment by optimumtact** [comment]
Can we merge MSO's now and I'll come back and make something more sane later.

This is a big pain for medical players.

**Comment by tgstation-server** [comment]
Mine was already merged

**Pull request closed without merging**
