### PR TITLE
AutoDrobes now have a premium psychedelic jumpsuit

### PR DESCRIPTION
**Pull request by ghost**
## Why It's Good For The Game
psychedelic jumpsuit good

## Changelog
:cl:
add: AutoDrobes now have a premium psychedelic jumpsuit
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Eh

**Comment by tralezab** [comment]
If you can find a way to actually support this change other than outfit good, sure.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'd be okay with this if it was like annoyingly expensive to compensate for how annoying it is to look at.

**Comment by loserXD** [comment]
psychedelic jumpsuit good

**Pull request merged**
