### PR TITLE
Removes all security cameras from bathrooms and showers

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

This PR ensures that all Nanotrasen installations are compliant with the Title 18 U.S Code 1801 "Video Voyeurism Prevention Act" by removing all cameras from bathrooms and showers.
## Why It's Good For The Game

We could get seriously sued if anyone reports this to the feds.

Jokes aside, I think its better to have these areas unmonitored, to make them an area more suited for evil behavior. An area inbetween the untamed danger zone of maintenance and the relative safety of a public hallway. Somewhere where you can get a little privacy or jump someone if you don't have maintenance access. It's not like these bathrooms are getting used for pooping.

Also, I just found it really weird that our bathrooms all have security cameras in them.
## Changelog
:cl: Rhials
balance: All cameras in bathrooms and showers have been removed.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
Honestly, this is probably a mercy for the people viewing the cameras.

**Comment by Moltovz** [comment]
Come on Rhials, we know one has to stay in the captain's bathroom after *that* happened.

**Comment by Blacklist897** [comment]
bathroom moths and the time admins turned me into a blind hairless albino and rotated me 45 degrees 
prove that one cam must stay

**Comment by carlarctg** [comment]
keep on dorms 4

**Comment by drIcepop** [comment]
Huge AI nerf, bad PR

**Comment by carlarctg** [comment]
Huge AI nerf, good PR

**Comment by ShizCalev** [comment]
>It's not like these bathrooms are getting used for pooping.
Oh.

I feel a new mood event coming.....

**Review by Maurukas — APPROVED** [review]
Probably should have checked for this after engineers were caught installing glass bathroom stalls in one station.

**Comment by Maurukas** [comment]
Push a commit, the CI is being stupid.

**Pull request merged**
