### PR TITLE
Adds a delay to check if a wall is false/opening it

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Add a small delay for:
Checking if a wall is a false one/opening false walls.
Screwdriving false walls into real ones, and if you try to use a screwdriver on a normal wall.
Welding down false walls.

## Why It's Good For The Game
We often have a paramedic/greytider/security officer running down on maint and clicking on every wall looking for a hidden valid base.

The 2 seconds to search a wall/open a false wall by hand makes spam searching at random be a chore.
The screwdriver change needs to exist so people can't go using a screwdriver on walls until they see a text saying they turned a false wall into a real one.
Welding tool is for the same reason.

With these changes it is not viable to go randomly looking for bases in maint, but it doesn't get much in the way if you have a good reason to search an area for false walls.
It will also make hidden walls/bases a lot safer for the user unless someone catches you getting out of one while losing it's mid combat potential of spawning a wall between you and someone trying to catch you in a split second.
I'm sure that "spawning" a wall to hide behind when chased isn't what people expect from false walls.

## Changelog

:cl: Guillaume Prata
balance: It takes 2 seconds to check if a wall is false, this should cut on people spam clicking every wall in maintenance looking for valids.
balance: Screwdriving and welding down false and real walls also have a delay as they could work as easy false wall checking otherwise.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
This just feels like it'll make false walls significantly worse as a hideaway spot

Also this doesn't really solve the problem because you can still right-click a wall and if you see the tile underneath, you know it's fake

**Comment by GuillaumePrata** [comment]
> Also this doesn't really solve the problem because you can still right-click a wall and if you see the tile underneath, you know it's fake

Right clicking takes a second to load so I doubt people would go spamming it at random.

**Comment by Mothblocks** [comment]
Maybe significantly is dramatic but I still don't think I like this

**Comment by GuillaumePrata** [comment]
If people stop using them a future system of false walls remembering people that opened it and opening faster for them would fix the issue.

I just don't think 2 seconds will be that big of an issue unless people are running through multiple false walls or being closely chased.
Right now we can go through (or build) a false wall, close and screwdriver it into a real wall in a split second which feels more like abusing how our construction has different build times for the same thing.

**Comment by ATH1909** [comment]
2 seconds seems uncomfortably long. maybe 1 second, or even 0.5?

**Comment by MrDoomBringer** [comment]
> unless people are running through multiple false walls or being closely chased.

This has happened to me a number of times, and I've seen this situation happen to other people a number of times. What I haven't yet seen is someone obsessively checking every wall they come across to see if it's false. This PR fixes a problem that doesn't exist, and otherwise only serves to make this game even more of a wait-for-the-loading-bar-chore than it already is.

**Comment by Miczu555PL** [comment]
> What I haven't yet seen is someone obsessively checking every wall they come across to see if it's false. This PR fixes a problem that doesn't exist, and otherwise only serves to make this game even more of a wait-for-the-loading-bar-chore than it already is.

You haven't seen this because antags don't really do false walls much, because exactly it's easy for valudhunter to spamclick walls to find hidden ones.

_Why it also helps fulp enforce their rules, that only sec should check for false walls otherwise it's valudhunting._ 🤓

**Comment by BlueMemesauce** [comment]
I've never seen anyone check every wall for false walls; there's no reason to do that when its easier to just put on masons or use a map to check for changes. The other day on Terry, security randomly found the malf AI (before they even did anything malf) by passing through maint and noticing an out of place wall covering the room the core was hidden in. This is going to change nothing about how validhunters play the game except adding an unnecessary timer to wait for when a hidden wall is found.

**Comment by Mickyan** [comment]
I think in general we should start using stamina damage as a measure against spammable actions like this, you can put the damage as high or low depending on how many times an action warrants being used in a short timespan before taking a break and it will be irrelevant in most legitimate situations

**Comment by Pickle-Coding** [comment]
It doesn't make sense for someone to be able to push some big metal contraption with enough force to open it while running around slapping every wall.

Not sure if it's intentional or not, but mesons can reveal false walls if you can't see them.

**Comment by Watermelon914** [comment]
> This just feels like it'll make false walls significantly worse as a hideaway spot
> 
> Also this doesn't really solve the problem because you can still right-click a wall and if you see the tile underneath, you know it's fake

Could probably solve this by setting the mouse opacity of the tile underneath to be invisible until the false wall is opened up or destroyed

**Comment by private-tristan** [comment]
if a validhunter is looking for falsewalls why would they be spamclicking every wall instead of taking half a second to put on melsons??? there's no reason for there to be a delay 

the only good part of the PR is adding a delay to screwdrivering because of displaced grinder -> falsewall -> screwdriver

**Comment by GuillaumePrata** [comment]
> there's no reason to do that when its easier to just put on masons
> spamclicking every wall instead of taking half a second to put on melsons???

Man what quirk are you guys picking that gives roundstart mesons for any job? I want in on the validhunt fun!

**Comment by YuliceTheDruid** [comment]
> > there's no reason to do that when its easier to just put on masons
> > spamclicking every wall instead of taking half a second to put on melsons???
> 
> Man what quirk are you guys picking that gives roundstart mesons for any job? I want in on the validhunt fun!

There are four to six pairs of mesons for free in public mining, and they cost a quarter sheet of iron/glass to print at cargo

**Comment by GuillaumePrata** [comment]
> There are four to six pairs of mesons for free in public mining, and they cost a quarter sheet of iron/glass to print at cargo

We have way more crowbars around the station, they cost 1/10 of the metal of mesons and no glass at all.
We still didn't merge the PRs that let us open firelocks by hand.

The game tries to run on an item economy, but it completely fails on this regard because no one is going to go to lavaland/cargo/engineering (I would bet not even on icebox's public mining) to loot mesons if they hear there is a hidden cult base in medical maints.
They will use their roundstart pair of hands and click on walls there until they find it.

**Comment by ATH1909** [comment]
> I think in general we should start using stamina damage as a measure against spammable actions like this, you can put the damage as high or low depending on how many times an action warrants being used in a short timespan before taking a break and it will be irrelevant in most legitimate situations

would feel really lame to be unable to close a false wall behind you because you got batonged/disabler'd, though

**Comment by ATH1909** [comment]
> The game tries to run on an item economy, but it completely fails on this regard because no one is going to go to lavaland/cargo/engineering (I would bet not even on icebox's public mining) to loot mesons if they hear there is a hidden cult base in medical maints. They will use their roundstart pair of hands and spam click on random walls there until they find it.

???

mesons still improve the speed/reliability at which you can find a cult base immensely over checking walls by hand. the public mining base is 100% the first place you should look when searching for a cult base, so you can just spend 5 seconds to grab mesons while you're there.

**Comment by GuillaumePrata** [comment]
> mesons still improve the speed/reliability at which you can find a cult base immensely

Never said otherwise and these changes cement that as the go to way to find hidden bases.

> the public mining base is 100% the first place you should look when searching for a cult base

What this even has to do with the PR at this point? If people should go there first and grab mesons I guess you have no issues with these changes so thank you?

**Comment by wesoda25** [comment]
Uninformed change that makes the overall experience worse.

**Comment by GuillaumePrata** [comment]
> Uninformed change that makes the overall experience worse.

We can say this to any PR that we don't like, it doesn't add much to the conversation.

I made the PR because I think having harder to find hidden walls/bases is more beneficial to the game than an instant get away from the false walls without a delay we have now.
Hearing other's opinion on this side of it would be nice.

**Comment by SuperNovaa41** [comment]
> The 2 seconds to search a wall/open a false wall by hand makes spam searching at random be a chore.

do people really do this? i feel like ive never seen this done
also 2 seconds is crazy i dont like this at all. maybe a lesser delay would be nice? but im not really sure i like it in its entirety tbh

**Pull request closed without merging**
