### PR TITLE
All chainsaws can behead

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
- just moves the doomslayer chainsaw behavior down to all chainsaws
- chainsaws take 15 seconds to cut someone's head off.
- doomslayers chainsaws still take 2 seconds to cut someone's head off.
## Why It's Good For The Game
- beheading is cool, a cumbersome chainsaw that takes both hands and is loud is balanced enough to allow it.
## Changelog
:cl: grungussuss
balance: all chainsaws can now behead people
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
Yea this slaps. Just hope there are no obscure chainsaw type objects that gonna be found with this merged

**Comment by TheVekter** [comment]
Yeah, I get us not having it using normal shit because it was way too easy to just round remove someone, but it only makes sense that a chainsaw should be able to behead.

**Comment by Iamgoofball** [comment]
@Mothblocks this is working around your intentional decapitation removal

**Comment by SomeoneYouProbablyKnow** [comment]
Oh. I just kinda assumed this was mothblocks approved. Guess its time to get the popcorn

**Comment by MrMelbert** [comment]
> Mothblocks this is working around your intentional decapitation removal

image

**Comment by Rhials** [comment]
Fifteen seconds? Super unrealistic, I could do that in five, tops.

Will attach video proof shortly.

**(User was banned for this post)**

**Comment by DrAmazing343** [comment]
_This comment was marked as spam_

**Comment by Xackii** [comment]
15 seconds is to long

**Comment by githubuser4141** [comment]
> Fifteen seconds? Super unrealistic, I could do that in five, tops.
> 
> Will attach video proof shortly.
> 
> **(User was banned for this post)**

2 seconds is way too short, right? It should be like, 5-10 seconds maybe. IMHO, the demolition mod is pretty unrealistic, wood-cutting chainsaws aren't meant to cut things like steel.

**Comment by SomeoneYouProbablyKnow** [comment]
Well there's technically true realism like that but there's also realism as a short hand. Big chainsaw cut thing good, as seen in most all of media. 

but yea 15 seconds is way too long especially considering you are probably doing a rampage. How long is the amutation sheers? 5ish seconds? Aim for around that 4 to 7 range sounds fair to me

**Comment by DaCoolBoss** [comment]
Maybe we should just standardise the time to amputate and use the toolspeed variable to tweak individual items.

**Pull request merged**
