### PR TITLE
[Ready] True Blindness. Quirk now turns your whole screen black but now you may examine things with a cane.

### PR DESCRIPTION
**Pull request by Militaires**
### this is a difficulty setting, it doesnt affect you unless you pick the BLINDNESS quirk.
________
image
:cl: Basilman
add: Blindness quirk now turns your whole screen black but now you may examine things with a cane.
/:cl:

[why]: # to make the quirk more interesting, go big or go home.

### CODE REVIEW

**Comment by plapatin** [comment]
wonderful

**Comment by kingoftheautism** [comment]
great, now, the true test, **blind miner**

**Comment by Borisvanmemes** [comment]
I like it as-is tbh, could spit it into two quirks, true blindness and normal blindness.

**Comment by Militaires** [comment]
@borisvanmemes go big or go home :b:ussyboy

**Comment by Militaires** [comment]
you're always at the centre of the screen, the first time i tested this quirk i was able to eyeball it perfectly it's not hard at all

**Comment by Time-Green** [comment]
Could it be possible to add sound indicators? Like you can see where sound comes from?

**Comment by Militaires** [comment]
i now understand why people call tg hugbox

**Comment by ExcessiveUseOfCobblestone** [comment]
i mean just looking at a black screen for an hour doesn't really sound enjoyable

**Comment by Militaires** [comment]
it's not meant to be enjoyable

**Comment by Vidiveni** [comment]
Basically you will need to no-scope yourself.

**Comment by Militaires** [comment]
it's not meant to be a "fun challenge", i didnt add blindness for that reason, if you wanna play the game fake blind stab yourself in the eyes with a screwdriver or weld your eyes shut

**Comment by Militaires** [comment]
use your mouse to have byond display the name of the things you hover on, and use the location of the objects to figure out where you are on the map, and there you go bubba

**Comment by anconfuzedrock** [comment]
Time to talk about lifeweb
Lifeweb has 100% blindness where you can't see fuck, but lifeweb *does* have sound indicators of a small white ring on tiles you can't see, even if blind.

**Comment by nicbn** [comment]
Sound rings are awesome

**Comment by ExcessiveUseOfCobblestone** [comment]
Yeah, something adding a different dynamic to the game instead of "lol now you have a black screen" would be much more appreciated.

**Comment by Militaires** [comment]
the white tiles thing isnt even just a blindness deal they have that for everyone. yeah ok i would add that if i knew how without fucking directly with the playsound proc 

also cant you already do this based on stereo

**Comment by Militaires** [comment]
### thanks for volunteering to code sound rings everyone

**Comment by Militaires** [comment]
ok fine ill try

**Comment by ChangelingRain** [comment]
There is almost a 0% chance that this will be fun and, if merged, it's likely to get reverted.

**Comment by Militaires** [comment]
@ChangelingRain it's not meant to be fun

**Comment by Militaires** [comment]
### again if you wanna play normal """blindness""" you can achieve it very easily with a screwdriver

**Comment by Mickyan** [comment]
I find most people typically play games to have fun

I was going to say this removes any chances of anyone ever picking it but it's not like anyone's ever used this more than once anyway

**Comment by Militaires** [comment]
why would you turn a game up to max difficulty then complain about it not being fun? this is what's happening here.

**Comment by Mickyan** [comment]
there's fun in challenge and there's a reason why blindness works the way ti does

this is more akin to making the hardest difficulty of an FPS not giving you weapons and only allow you to walk backwards

**Comment by Daxxed** [comment]
> 
> 
> great, now, the true test, **blind miner**

I'm pretty experienced as a miner and I want to try this.
I think if you can manage to get to the GPS and it still shows you the interface then perhaps it might be possible to kill something like bubblegum or blood drunk miner.
The little fauna actually seem like a bigger challenge.
They have no gps signal, watcher will freeze you to death before you even figure out where it is.
A goliath will hook you without you even realising and a legion will probably kill you by the time you figure out where the little shits are coming from.
Will post results soon

**Comment by anconfuzedrock** [comment]
I have memory of killing smells the sec officer when he metaganged at me and I somehow won the fight while blind and the rush was so fucking good, I would love nothing more than to hijack a shuttle with a cane.

**Comment by Militaires** [comment]
@mickyan this quirk is only for people smart enough to realize hovering over objects makes byond display their names for you

**Comment by Mickyan** [comment]
I dont see the relevance but don't let me stop you from being a smartass

**Comment by Militaires** [comment]
it means you can basically fucking see

**Comment by Militaires** [comment]
it means you can basically fucking see

**Comment by ishitbyabullet** [comment]
If someone just coded lifeweb sound rings then it would be cool.

Until then, god bless your eyes if it's night time on and the only thing visible is the computer screen.

**Comment by ninjanomnom** [comment]
I'm with Joan on this one. If it were more interesting like some sort of echolocation vision then this would be worth something but as it is this is worthless.

**Comment by Militaires** [comment]
Bruh

**Comment by Militaires** [comment]
@ninjanomnom 

>I'm with Joan on this one. If it were more interesting like some sort of echolocation vision then this would be worth something but as it is this is worthless.

echolocation vision is something completely different, if you want that you can make that quirk, but this out of the scope of the pr, this just adds a  **COMPLETELY OPTIONAL** difficulty setting for the players who want it.

this is completely playable, i tested it on my server, i spawned in as det, got out of my office by hovering to find the airlock, walked outta sec, ran around the loop and checked the bar, went to chem, found and broke in the window then made some chemicals.

you keep citing "INTERESTING" but i really dont get it, not everything has to be revolutionary and weird, this is self explanatory and just because you dont find it interesting doesnt mean everyone doesnt as well, there is a niche in every playerbase who likes to play the game with extreme difficulty settings, like playing STALKER with the makarov only, this is designed for that niche, and is not for everyone **(HENCE BEING OPTIONAL)**

even if this is merged, it's completely harmless and doesn't affect the players who want to play normally.

**Comment by ninjanomnom** [comment]
I didn't say you should make this have echolocation vision, I was just saying this doesn't add anything interesting to the game besides a one off joke. Making the naturally blind have some unique way of navigating would be something to make it interesting.

I don't really have strong opinions on this one way or the other so if one of the other maintainers feels strong enough about it to add it then I don't see a problem. It's just not worth having in the code imo.

**Comment by Militaires** [comment]
@ninjanomnom you have your unique way of navigating, i added the cane for that reason (it lets you read examine things to gain more information about it while blind), you can also just use sound ques like airlocks opening to find out where you are on the map.

the game is plenty playable with the quirk, even if you personally cant play it like that.

**Pull request closed without merging**
