### PR TITLE
Upgraded the jaunter into the wormhole lifebelt

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: The Free Golems have developed the jaunter into the  wormhole
lifebelt, which automatically teleports the user when they fall in a
chasm or suffer a major medical emergency. Must be worn on the belt to work.
rscadd: "Yeah go do whatever" reads a note on the equipment vendor. Free Golems no longer have any restrictions on what they can purchase.
/:cl:

Wormhole lifebelt has been added to the mining voucher supplies.

Please don't mistake a random teleportation in crit for saving a user's
life, the Supply channel gets a notification, but suit sensors are
required to find them, and there's no guarantee the location picked is
safe (for example, the Toxins Test Site is a valid jaunt destination,
along with in the middle of the slime cages in Xenobiology).

To prevent Free Golems from purchasing lifebelts to get back to the station, a wormhole lifebelt will now target the Free Golem ship, either by beacon or by the gold statue.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
1. Golems don't get jaunters your cl is a meme

2. Hugbox

**Comment by KorPhaeron** [comment]
Hugbox

**Comment by Zilenan91** [comment]
Remove the supply comms message and it's good

Does this also save you from chasms?

**Comment by coiax** [comment]
Yes it does. Technically, it already has this feature, but that seems to be not very recognised. I'm hoping that renaming it to a lifebelt will attract more attention to this.

**Comment by PKPenguin321** [comment]
no but for real with any kind of passive heal this is like reactive armor on steroids

1. get hivelord heart passive heal
2. get into fight with traitor or something
3. get knocked into crit
4. magic hugbox belt flings you away from any and all danger forever and ever
5. get back up and be 100% fine
6. whip out another hugbox belt from your backpack and slap it on

i hate it :-1: if you want the chasm-saving feature of jaunters to be more obvious change their description to mention it or even move it to its own item or something

**Comment by Core0verload** [comment]
Maybe I'll make jaunter an assembly, so you can use it with HP sensor, or as a part of mousetrap grief device. Should be fun.

**Comment by coiax** [comment]
Except the reactive armour doesn't leave a giant portal behind allowing you to follow them to wherever they went. And doesn't stun on arrival. And if you have enough hivelord cores implanted to heal up, then you probably deserve to get back up.

Making a chasm saver its own item was unpopular due to "item bloat".

I'll increase the activation tick to 5 and remove the supply message.

**Comment by KorPhaeron** [comment]
Sorry but I said I'd close this before you even coded it.

Lavaland is miserable and and dangerous, but also the most popular job, so I'm just gonna assume people like miserable and dangerous for now

**Comment by coiax** [comment]
REEEEEEEEEEEEEEEEEEEEEEE

**Comment by coiax** [comment]
It costs a belt slot (so no explorer belt), it doesn't heal you, all it guarantees is getting your body back on station SOMEWHERE, no one knows that jaunters have chasm protection at the moment anyway, and this is undoing the stuff for the Free Golems anyway because they should have unrestricted access to the Mining Vendor anyway.

**Comment by coiax** [comment]
And even if it's being rejected on the crit activation grounds, that can be disabled, I'd still like the other structural changes merged.

**Comment by PKPenguin321** [comment]
>all it guarantees is getting your body back on station SOMEWHERE

Which is shit and hugbox

>this is undoing the stuff for the Free Golems anyway because they should have unrestricted access to the Mining Vendor

Automatic :-1: for that alone, golems jaunting to the station ezpz was bad and deliberately removed for a good reason

>It costs a belt slot (so no explorer belt),

Oh no I can't hold the pickaxe that I will literally never use, what a horrible tradeoff for never dying. Woe is me

**Comment by coiax** [comment]
> > this is undoing the stuff for the Free Golems anyway because they should have unrestricted access to the Mining Vendor
> Automatic :-1: for that alone, golems jaunting to the station ezpz was bad and deliberately removed for a good reason

10/10 for reading either the code or the description, this actually force targets the free golem ship if a golem uses it

**Pull request closed without merging**
