### PR TITLE
Fixes RCD airlocks making extra eletronics

### LINKED ISSUE #25319: RCD Creates extra set of Airlock Electronics
On Server revision compiled on: 2017-03-20
4c1d9131a358225584d4feed4bd3bb94c2c7b376 
No test merges present.

As an Engineering Cyborg and as a Station Engineer, I successfully created an airlock using the RCD, however, upon opening the airlock there are spare airlock electronics sitting on the ground.

### PR DESCRIPTION
**Pull request by Iamgoofball**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)
[]: # (See here for how to easily make a changelog: https://github.com/tgstation/tgstation/wiki/Changelogs. An example changelog has been provided below. Please edit or remove)

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 

fixes #25319

### CODE REVIEW

**Comment by coiax** [comment]
Maybe just remove the example changelog?

**Comment by optimumtact** [comment]
Can you fix your changelog please

**Comment by Supermichael777** [comment]
ow that title

**Comment by Militaires** [comment]
the somewhat accurate title pains goof greatly

**Pull request merged**
