### PR TITLE
More options for Induce Panic forced speech

### PR DESCRIPTION
**Pull request by ghost**
Induce panic's previous random forced speech had some odd sentences. This replaces them with new ones that fit the theme of panic better.

### CODE REVIEW

**Comment by Barhandar** [comment]
HELP needs to be capitalized, also add MAINT and DYING to it for the meme

**Comment by nemvar** [comment]
BLOW BORGS

**Comment by Shapsy** [comment]
HA the first thing I thought of when I saw "panic speech" was "I'm losing control of the situation"

it's a reference to a voice line from XCOM Enemy Within when you make one of the EXALT enemies panic https://www.youtube.com/watch?v=6CYIu8Bc9sY&t=45s

**Comment by py01** [comment]
didnt realize that line was a reference, i can add it back in. "blow borgs" would be funny but I have a feeling it would actually result in the borgs being blown without checking if they are rogue if you use induce panic near the cap

**Comment by GuyonBroadway** [comment]
Honestly tricking the crew into blowing the borgs sounds like the good kind of emergent gameplay. Decipt and trickery are sorely underused and under encouraged.

**Comment by Barhandar** [comment]
Very annoying for borgs, though.

**Comment by HomocidlePancakes** [comment]
>Very annoying for the borgs

Shit. Remove antag so borg no annoyed kk?

**Comment by py01** [comment]
I think there can be a compromise and have a "lock down borgs" line

**Comment by Akrilla** [comment]
Oh no! I am losing control of the situation! Wtf is that line

**Comment by py01** [comment]
New line: ":h AI lock down the borgs law 1!", time for salt

**Comment by PKPenguin321** [comment]
Not enough all caps

**Comment by Tlaltecuhtli** [comment]
:h sec rogue

**Comment by bgobandit** [comment]
CALL THE SHUTTLE

**Comment by AdamElTablawy** [comment]
add back the 'I'M LOSING CONTROL OF THE SITUATION' line as well.

**Comment by Shadowflame909** [comment]
I'm making Chocolate-Pudding at 3 AM!

**Comment by SpaceManiac** [comment]
removing "I'm losing control of the situation!!" is a sin

**Comment by optimumtact** [comment]
didn't someone get in game banned for saying it's revs ic?

**Comment by py01** [comment]
changed "Revs" to "Revolutionaries" which should be more IC. Also added back "I'm losing control of the situation!!"

**Comment by PKPenguin321** [comment]
last comment wasnt a joke, these are kind of unbelievable without some ALL CAPS

**Pull request merged**
