### PR TITLE
Reagent Analyzer

### PR DESCRIPTION
**Pull request by Deantwo**
As discussed in https://github.com/tgstation/-tg-station/pull/7402, a handheld reagent scanner is needed before https://github.com/tgstation/-tg-station/pull/7402 is a good idea.
So this is my attempt at making the handheld reagent scanner.

**Features:**
- Lists all reagents in the target atom. (beaker, bottle, pill, patch, mob, or turf)
- Warns if the amount of a reagent is over the overdose_threshold or addiction_threshold (or both).
- When scanning a mob, the amount of time until a reagent dissipates is calculated and shown.
- Warns when a mob is overdosed on a reagent.
- PDA reagent scanner also upgraded.

**Pictures:**
reagentanalyzer testingreagentanalyzer test3
reagentanalyzer testing 2

**To-do list:**
- [ ] A new sprite. (Anyone want to make one?)
- [ ] Figure out what the hell is up with the `afterattack` proc.
- [ ] Clumsiness/brain damage mess up.
- [ ] Placement on the map.
- [ ] Allow in medical belts.
- [ ] Added to Autolathe? (Or something?)
- [x] Talk with @Iamgoofball about his HealthAnalyzer update in https://github.com/tgstation/-tg-station/pull/7562.

**Feedback needed:**
- Look and feel of the scan result.
- More features? Less features?
  - Should It scan for viruses in the reagents/blood too? (just a "Contaminated" warning)
  - Remove scanning of people?
- Where should they be available from at round start? How many?
  - 3 in each _NanoMed Plus_?
  - 1 or 2 in chemistry?

**Future plans:**
- When starting work on the reagent database, I would like this to function as a handheld reagent database as well.

### CODE REVIEW

**Comment by RandomMarine** [comment]
Added to autolathe? Seems odd since med analyzers aren't there, though it'd be nice for cargo techs to have ready access to scanning suspicious pills/syringes that are stuffed down disposals.

**Comment by Deantwo** [comment]
Well, I have used an Autolathe maybe once over the last 2 years.
So I don't know much about it, but it is possible to make Spectrometers in the Autolathe I think?

**Comment by Niknakflak** [comment]
No, those are made by science protolathe. If this is added, spectrometers should be removed as they do the same thing but shittier because you have to use a syringe on them.

**Comment by Deantwo** [comment]
@Cheridan suggested that the Spectrometers should just be ditched in place for this.
And I have a few ideas about what to change with the HealthAnalyzer update in https://github.com/tgstation/-tg-station/pull/7562 that @Iamgoofball is working on.

**Comment by Niknakflak** [comment]
Good stuff

**Comment by AlexCrimson** [comment]
I agree, both Spectrometers should just be removed. They are not used for anything anymore. 

As for this new thing, maybe put 3-4 in each Nanomed vendor? Doctors can just grab one as needed then, but it would also be access-restricted so you wouldnt get random Assistants scanning everything for poison and screwing traitors. You could also put one in the Toxins Medkits, i guess.

**Comment by Deantwo** [comment]
Yeah that sounds like some good ideas.

As for a sprite, should I just use the Spectrometer's sprite? Or should we get something new so it isn't confused.
Trying to figure out who/where to ask about getting sprites done.

**Comment by Niknakflak** [comment]
The spectrometer sprites arent bad but yea players could get confused.  You could use the same sprites and just "update" the usage of the spectrometer or get a new sprite all together from nienhas, wjohnston, or post in the sprite request thread.

**Comment by RandomMarine** [comment]
Nobody ever uses the spectrometers, so I doubt there will be any confustion. Though, an analyzer should probably have a sprite more consistent with the health and gas ones. Heck, shouldn't be too hard to edit one of the spectro sprites for that purpose.

**Comment by Deantwo** [comment]
Updated with another example picture.

I am not sure I like the tag for when a chemical is over the addiction_threshold, it only appears when the dosage is high enough to be addictive, so having it say ```- addictive``` just seems weird.
Thoughts?

Also updated the *needed feedback* section. So some feedback on those would be nice too.

**Comment by Pennwick** [comment]
Maybe make two versions. One that just tells the amount of each in the bloodstream but none of the extra, its found in each toxin first aid kit, and maybe 2 in each vendor, it fits on a belt. Then have this one which gives all the info but does not fit on a belt and is more limited in availablity.

Less features would probably be better telling you a pill is too strong is a bit too much hand holding. Chemists should know what they're making and the details the ChemMaster database instead. It doesn't need to scan for viruses as health analizers already do that.

Availablity: I'd say go with 2 in chem and 1 in each med supply lockers with the defibulators and belts but also makable in chemistry at the same level the mass spec requires and if you include the weaker ones have one in each toxins first aid kit and the medivends.

To be honest I'm not sure it needs to be able to scan people at all, just buff the mass spec to skip the syringe step and give medbay a few by default instead of them needing research before they're usable.

**Comment by Deantwo** [comment]
Can also just make this not work on mobs and use the HealthAnalyzer for that.
Then this will be used only for scanning beaker, pills, patches, and so on.

**Comment by Jordie0608** [comment]
Changelog

**Comment by Dorsisdwarf** [comment]
This is pretty outdated due to medscanners doing this.
And it's rarely enough used anyway, let alone adding yet another box for them to carry about.

**Comment by Deantwo** [comment]
This item is a little out dated yeah, been busy with **Hazeron**.
Mostly this item is gonna be used for scanning OBJECT rather then people.
I think I may just remove the ability to scan people with this.

Most of all won't have much use before https://github.com/tgstation/-tg-station/pull/7402 is planned out a little better.

**Comment by Jalleo** [comment]
I think we should just obscure all the reagents and do this at the same time while making some sort of basic scanner of which non medical staff can acquire to know if its a complex chemical reagent(s) in there or if its just a plain simple reagent. (Good way to make conversation by usage of mechanic but people may hate it)

**Comment by Deantwo** [comment]
Yeah, talking with Goof was on the to-do list.
But the health analyzer change was merge either way.

So far I have this:
- Remove scanning of people
- Make a "budget" version
- Figure out https://github.com/tgstation/-tg-station/pull/7402

**Comment by Dorsisdwarf** [comment]
If this is for scanning objects only, then it's just a worse forensic scanner.

**Comment by Deantwo** [comment]
Never used the **forensic scanner** before.

**Comment by Razharas** [comment]
Any progress?
@Deantwo

**Comment by Dorsisdwarf** [comment]
Oh, by the way
Goofball added this to the chemist PDA or something.

**Comment by Deantwo** [comment]
>Oh, by the way
>Goofball added this to the chemist PDA or something.

Well, the Chemist PDA Cartridge already had/have a scanning feature, it was just only listing the reagents and not saying any thing about how much was in the target.
It could even scan people.

The work in this PR was to replace that PDA Cartridge feature to work the same way.
Much like how the Doctor's PDA Cartridge is a Health Analyser.

But I kinda haven't been around on SS13 or this PR for awhile, the return of [Hazeron](www.Hazeron.com) stole me.

**Comment by Cheridan** [comment]
I'll close this and maybe open a version myself or if someone else wants to take it up they're free to do so

**Comment by Deantwo** [comment]
> I'll close this and maybe open a version myself or if someone else wants to take it up they're free to do so

Sure thing. I am not gonna get it done my self sadly. Mostly because I can't figure out what people even wanted me to do with it.

And I have gonna not touched SS13 code for a while now, been too busy with other stuff.

Do ref this PR though. Would love to see what you end up with.

**Pull request closed without merging**
