### PR TITLE
Fixes Xenos being unable to remove vines

### PR DESCRIPTION
**Pull request by GunHog**
Xenos may now eat vines!
Fixes https://github.com/tgstation/tgstation/issues/16968

### CODE REVIEW

**Comment by coiax** [comment]
oh my god someone other than me is going to fix one of my issues <3

**Comment by GunHog** [comment]
Makes @WJohn happy, makes you happy, counts as my bugfix for WJ's Xeno buff, it is a win for all three of us!

**Comment by WJohn** [comment]
:+1: 
Does eating them make them fat?

I'd kinda like that. Xenos getting too fat from eating all their greens.

That'd be so stupid :D

**Comment by GunHog** [comment]
...if you make fat sprites...

**Comment by Archie700** [comment]
Who's surprised that WJohn has a fat fetish?

Oh wait.

**Comment by PKPenguin321** [comment]
>wj
>fat xenos
>>:D

oh god

**Pull request merged**
