### PR TITLE
Changeling vs Changeling

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Changelings can now have an objective to have more genomes than any other changeling, rather than a set target.
add: Changelings can now have an objective to absorb another changeling.
add: Changelings now get bonus genetic points for buying powers when they absorb another changeling. Their chem storage cap will also be increased.
add: Changelings absorbed by other changelings will lose all their powers, chems, and genetic points, making them unable to revive.
/:cl:

Why: Changelings are way too powerful when they're rolling around in an eight man death squad. This preserves the hive mind, but adds significant risk to to trusting other changelings, and a strong incentive to backstab them. I think a system of uneasy alliances will be much more entertaining than team changeling or forced solo changeling.

Things I'm considering changing:

2/3 chance of an objective explicitly hostile to other lings might be a bit high. Closer to 50/50 might be better.

Letting absorbed lings keep their absorb power so they can kill and absorb a ling for their powers back.

### CODE REVIEW

**Comment by Nabski89** [comment]
Pretty sure absorbed lings already were out of the game.

**Comment by KomradeSpectre** [comment]
I am completely for more antag v antag stuff, because it encourages a bit more backstabbing instead of CHANGELING OPS.

**Comment by bgobandit** [comment]
> Letting absorbed lings keep their absorb power so they can kill and absorb a ling for their powers back.

this is a good idea IMO, just on paper this looks like the meta might turn into lings removing each other from the round one by one until it becomes quasi-extended

**Comment by improvedname** [comment]
Btw there is a bug.
If you prepared your revive before you get absorbed. You can revive as an husk which shouldnt be possible because being absorbed should be end game for you

**Comment by KorPhaeron** [comment]
@PKPenguin321 

Was considering adding some sort of super ling powers at ~20 genetic points so if security feeds the changeling it can go nuts and eat them all easily

**Comment by zaracka** [comment]
> Changelings can now have an objective to have more genomes than any other changeling, rather than a set target.

What if they choose to kill more people instead of eliminating the competition?

Personally, I see changelings as an antagonist that starts out stealthy and goes loud once their presence is known. Maybe having 10 evolution points immediately is too easy/powerful. What if they started with fewer points and had to earn more by absorbing people?

> Changelings can now have an objective to absorb another changeling.

Traitors have this, so why not changelings.

> Changelings now get bonus genetic points for buying powers when they absorb another changeling. Their chem storage cap will also be increased.

This is neat. Maybe this should be the only way changelings can respec/readapt though.

> Changelings absorbed by other changelings will lose all their powers, chems, and genetic points, making them unable to revive.

Might be kind of harsh, but I like it. Although, wouldn't be bad preserving the must-gib nature of changelings either.

> Letting absorbed lings keep their absorb power so they can kill and absorb a ling for their powers back.

This could theoretically be used by two changeling buddies to max out the other's powers. Not everyone cares about greentext, could be an issue.

Just my two cents.

**Comment by KorPhaeron** [comment]
@zaracka 

>What if they choose to kill more people instead of eliminating the competition?

That's a gamble. You don't know if the other lings also have the same "eat as many as possible" objective or not. You'd have to trust their word that they only needed X amount and weren't trying to race you.

It's a valid way to win though.

**Comment by zaracka** [comment]
Fair enough.

**Comment by Shadowflame909** [comment]
What if we just remove them all together, changelings with the objective to kill other changelings usually just ignore there objectives because they know how much of a hassle it is to fight another changeling.

**Comment by ExcessiveUseOfCobblestone** [comment]
Please don't add the "absorb other ling" obj, it is incredibly frustrating to have to find someone that by design can be someone else at a drop of a hat*. They already compete indirectly with the arms race obj.

*This is of course unless you plan to have a way for lings to discern lings from humans pre-absorb.

**Comment by Shadowflame909** [comment]
>Please don't add the "absorb other ling" obj, it is incredibly frustrating to have to find someone that by design can be someone else at a drop of a hat

Honestly if I knew that I had to murder another changeling, and because it becomes the new meta. I think lings all together will just avoid green text. This isn't really a solution. I know this because, I've seen it before. ":G hey is anyone Shadow Mist?" ":G yeah I am.." ":g Guess i'm not gonna do my task today."

**Comment by KorPhaeron** [comment]
@Shadowflame909 @ExcessiveUseOfCobblestone it might end up terrible but it probably wont be worse than what we have now

**Comment by PKPenguin321** [comment]
Actually Cobby makes a really good point and it might actually be worse

**Comment by Shadowflame909** [comment]
It's worth a try. Just seems futile and pointless. It's kinda the same as removing ling hivemind all together. Just in a different way.

**Pull request merged**
