### PR TITLE
Boss tweaks

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Bubblegum and Colossus will both gib victims on death to prevent lings from cheesing them.

Fixed the shield effect lasting too long

### CODE REVIEW

**Comment by Kromgar** [comment]
Bubblegum? 

Also when the hell were colossi added?

**Comment by anconfuzedrock** [comment]
how do you even get past that shield

**Comment by KorPhaeron** [comment]
with a prog knife

**Comment by Kromgar** [comment]
Prog knife? Whats a prog knife

**Comment by Iamgoofball** [comment]
ur mom lol

**Comment by PKPenguin321** [comment]
>Whats a prog knife

kind of like a prog fork but sharper

**Comment by Kromgar** [comment]
OHOHOHO Evangelion joke

**Comment by KorPhaeron** [comment]
The real answer is the shield doesn't do anything but the icons already existed and seemed appropriate

**Pull request merged**
