### PR TITLE
Lichmode lukewarm fix

### LINKED ISSUE #12747: Lich phylactery beam thingy is permanent
It doesn't disappear until you revive and then it just moves. This is from experience.

### PR DESCRIPTION
**Pull request by Incoming5643**
Swaps the last bit of the lichmode Beam() relying on something other than a turf for a turf.

I was being dumb and tied an atom defined proc to a body set to be dusted instead of a turf that will surely exist in some form.

I think my machine is fucking with me, because whenever I test this stuff locally, it works.

Fixes #12747

### CODE REVIEW

**Comment by Incoming5643** [comment]
I've really been on fire lately

**Comment by GunHog** [comment]
Wow. I thought those were Revenant streams.

**Comment by Incoming5643** [comment]
It's the same sprite so yeah, I understand the confusion.

Golden lining here is it's good to see that beams work properly even over very long distances

**Comment by Anonus** [comment]
Here's a less purple and more green sprite for those.
It's shitty, but it's better than having purple.
http://puu.sh/l3inJ/a09fd19884.dmi
I made it in like 5 minutes

**Comment by Incoming5643** [comment]
My defense of using the revenant effect is both powers deal with moving lifeforce.

Anyway this is just a quickfix pull. I'm not gonna change anything here.

**Pull request merged**
