### PR TITLE
Removes drone filter

### LINKED ISSUE #20284: Drones can't see more than 1 tile of Ash Drakes
(Drone (729)) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): drones see only 1 tile of lesser ash drakes on both blank and static filters

Not supposed to be like that,I think.

### LINKED ISSUE #29717: Drone filter broken
dreamseeker_2017-08-04_19-30-15
roundid 74259
went on observer on roundstart, came back 20 minutes later and decide to pick drone > repair drone

### PR DESCRIPTION
**Pull request by ghost**
At this point, why not? I mean this fixes a higgs-bugson, so why notter? (also there's bound to be a piece of code i missed or need to change)

Fixes #29717 
Fixes #20284

:cl: FrozenGuy5/PraiseRatvar
tweak: Drones no longer have a visual filter! You can see the world like any other human!
/:cl:

### CODE REVIEW

**Comment by MimicFaux** [comment]
It helps reinforce the idea of 'ignore/non-interaction' As a drone, when the vision filter falters, I find myself painfully aware of all those things I should be otherwise ignoring.

**Comment by PraiseRatvar** [comment]
heres a really bad statement, by me:
you'll get used to it. ☺

**Comment by Iamgoofball** [comment]
:-1:

**Comment by tortellinitony** [comment]
Pfft..how do we expect people to follow their laws? Like what the heck, laws don't do shit, you need stuff like this to keep everyone in check. Also, we need to add something that checks if other silicons have something that doesn't allow them to interact with beings, and then add this filter to their vision if so.

**Comment by RandomMarine** [comment]
Vision filter drawbacks/issues:
- Makes it more of a chore to avoid interfering with people. E.G. Broken windows into a department. Can't tell at a glance if anybody inside is a department worker (Fix the window) or who broke in (Wait for them to leave first.)
- Simple mobs don't appear to change icon states. For instance, that means you can't tell at a glance if any given space carp is alive or dead.
- Mobs with over 32x32 icons are broken in general. Can you tell what the fuck this is? https://i.imgur.com/YXHJVoJ.png
Spoiler alert it's an ash drake.

Vision filter benefits:
- Flavor

I'll be happy if this goes.

**Comment by DoctoreMad** [comment]
All checks have failed
1 failing check

**Comment by PraiseRatvar** [comment]
@DoctoreMad fixed!! hopefully

**Comment by Iamgoofball** [comment]
1. You shouldn't care about people AT ALL.
2. Easily fixed. 
3. Also easily fixed

**Review by Cyberboss — APPROVED** [review]
I don't like this solution

**Comment by KorPhaeron** [comment]
I dont care either way

**Comment by PraiseRatvar** [comment]
🎬

**Comment by Iamgoofball** [comment]
@Cyberboss why'd you approve it then

**Comment by RemieRichards** [comment]
hes a dumb.

**Comment by RemieRichards** [comment]
also I made this, now we have my alt appearance system (that was fixed up to work using the atom hud system by whoever it was I forgot but I love you!) this filter system should be moved to that.

I disagree with the removal of it.

**Comment by RemieRichards** [comment]
@RandomMarine flavour was not the only nor primary reason and if you can't see that you must have a vision filter yourself.

**Comment by Cyberboss** [comment]
@Iamgoofball approval of code != approval of PR

**Comment by RandomMarine** [comment]
@RemieRichards 
Then go and explain. I play drone more than anything else and in my experience the filter is nothing but a pain in the ass that causes **more** incidents between drones and living players.

**Comment by RemieRichards** [comment]
The filter vastly reduces the amount of bullshit admins have to deal with.
with the filter, if a drone does something they can be straight up banned/jobbanned, its FAR less likely to be accidental given the filter.

**Comment by PraiseRatvar** [comment]
there's probably a way to make it so people who actually have hours on the server can have no filter but i have the mind of a potato so i wouldn't be able to figure it out

#29105 could probably change something but that's up to shadow's jurisdiction

**Comment by RandomMarine** [comment]
>if a drone does something they can be straight up banned/jobbanned, its FAR less likely to be accidental given the filter.

How does a feature that **limits information** cause less accidents?

**Comment by RemieRichards** [comment]
Exactly, it limits the drone.
If they can tell exactly who it is, what they seem to be doing, etc. they can react and interact with said person, which they're not supposed to do.

**Comment by RandomMarine** [comment]
In my experience the opposite occurs. I end up inadvertently stepping on the toes of people breaking into departments by repairing their damage, which cuts off their exit, just because it's hard to even tell who they are.

If the filter's gone, then I can tell at a glance that they're not supposed to be there and that I should go elsewhere until their business is done.

**Comment by KorPhaeron** [comment]
Remie is never going to let this get merged

**Comment by PraiseRatvar** [comment]
/shrug/

**Pull request closed without merging**
