### PR TITLE
Improved mini-uzi

### LINKED ISSUE #10164: Mini Uzi bolt is closed when ready to fire
Uzis are supposed to be open bolt, so the bolt should be open when it's ready to fire, and closed when it's not. Muh autism hurts because of this.

### PR DESCRIPTION
**Pull request by Thunder12345**
Changed sprites for the gun and magazine
Removed the ability to suppress the uzi
Fixes #10164

### CODE REVIEW

**Comment by WJohn** [comment]
That magazine looks awfully similar to the one the proto smg from R&D uses. Why not have them share both the same ammo type and magazines?

**Comment by Iamgoofball** [comment]
Why the fuck are you hiding balance changes in sprite PRs?

Don't do this shit

**Comment by Thunder12345** [comment]
>Hiding balance changes
It's like you didn't even read the description.
And WJ, I suggested doing that, but A: it would look like shit if both sizes of magazine had only one sprite per gun, and B: Scones complained about it making sci gangs too powerful

**Comment by bustygoku** [comment]
This doesn't look anything like an uzi anymore. It looks like a poorly edited protolathe smg.

Why not rename it too?

**Comment by Thunder12345** [comment]
That's what a description is for, maybe you should try reading it some time. Now, does anyone else have any actual comments about the sprites/suppressor thing?

**Comment by bustygoku** [comment]
A balance change and a subjective sprite change is up for discussion and I wouldn't call it an improvement.

**Comment by Iamgoofball** [comment]
Yeah, I wouldn't exactly call removing it's suppression ability as an improvement.

**Comment by Dorsisdwarf** [comment]
PR titles are not required to be total/ grammatically perfect descriptions of the content. We expect anyone who wants to comment on proposed changes to the codebase to be capable of actually reading and comprehending more than one line of text. It says it, right there, in the 5-line description that this change makes miniUZIs unsupressable. What else do you need?

**Comment by PKPenguin321** [comment]
actually dorsi that's the opposite of the truth
[https://tgstation13.org/wiki/Getting_Your_Pull_Accepted](Pull request requirement number six says:) 6. Clearly state what your pull request does [in the title].

**Comment by Dorsisdwarf** [comment]
If you're going to interpret that rule as "description goes in the title box", then every fix bundle should be denied because "atomic PR rule". Commit logs too, if you require maximum possible adherence must be a copy-pasted description, and everyone who ever abandons a project or leaves someone else to code a fix for their feature should have it reverted for not following the Coding Standards (which require you to maintain your own code).

Our rules get really fucking weird when you decide that "improves micro-Uzi" including a removal of supressors violates "state what your PR does in the title" or the equivalents

**Comment by Dorsisdwarf** [comment]
Oh wait, you misquoted the rule to support your argument. Good work.

```
6. Clearly state what your pull request does

Don't withhold information about your pull request. This will get your pull request delayed, and if it happens too often your pull request will be closed.

Suppose you fixed bug #1234 and changed the name and description of an item as a gag.

Bad:

In this PR I fixed bug #1234.

Acceptable:

In this PR I fixed bug #1234 and also modified the baton's name and description.
```

**Comment by bustygoku** [comment]
Calm down. The title is misleading and I noticed a trend, that's all.

For example: "Improves mini-uzi" doesn't imply anything about balance or sprite adjustments. It's a word usually suited for, say, improving the quality of the code, or what have you. Someone might be less inclined to click-through the PR and read the description if they think it's a simple improvement and not a real change to the weapon, the entire look of the gun, etc.

Sure, you could say, "that's on them", but this is basic courtesy I think to put more thought into your PR titles.

This has nothing to do with rules, I haven't even read the rules here yet and I know this is poor form.

**Comment by Lumipharon** [comment]
That sprite looks worse then the current one. It looks like someone has melted a stechkin.
Why remove the ability to suppress it? It's niche as fuck and far from OP.

**Comment by Dorsisdwarf** [comment]
For reference of viewers, Bustygoku's account is 2 days old, he has never made a contribution to any codebase, read the rules, read the Code Standards, commented elsewhere, or even pushed any code to his three 2-day old dummy forks. Despite this, he's been poking through month-old merged minor PRs of Thunder and is using one in which he actually did make a genuinely misleading title as ammo to attack him here over absolutely nothing. 

While I hate to accuse people of being dummy accounts, that really seems like a stretch that a brand new person has hopped onto github, made an empty fork, chased up merged PRs from three weeks before they joined github on a server whose codebase they claim to follow, and then made a baffling and pointless attack?

@Thunder12345 I agree with lumipharon, the actual miniUzi sprite, while looking more like a miniUzi, is a bit ugly

**Comment by bustygoku** [comment]
A lot of people browse this and not comment or make accounts, you know. I've been doing it for some time. I'm glad I come off like an experienced git user while exerting my common sense though.

**Comment by ExplosiveCrate** [comment]
I'll have to agree with everyone else, the sprite looks really bad. It looks like you took a Star Trek phaser and spray painted it black. There was nothing wrong with the old Uzi sprite.

And what the hell is up with removing the ability to silence them? Silenced Uzis aren't even rare in media, and I have legit never even seen an Uzi outside of Summon Guns. Much less one with a silencer. If it's a sprite problem, then it might be better to actually make sprites for a silenced Uzi than remove a harmless function that nobody uses and call it an improvement.

**Comment by phil235** [comment]
I prefer the old mini-uzi sprite to this one.

**Comment by Cheridan** [comment]
A better sprite (if it is better) isn't worth the gameplay impact of the loss of suppression.

**Pull request closed without merging**
