### PR TITLE
Added science berets.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

This PR adds some purple berets to the science vendrobe and the RD locker.

image

## Why It's Good For The Game

More cosmetics good !

## Changelog
:cl: Kathy Ryals
add: Nanotrasen has recently hired a new clothing company to design some stylish, science-themed beret ! The Research Director is provided with a free sample in his locker, and three more are available in your nearest Sci-Drobe !
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Prettt cute, would wear.

**Comment by Swiftkor** [comment]
Berets kinda seem like they should stay sec thing to me

**Comment by Farquaar** [comment]
Security clothing has a [military](https://en.wikipedia.org/wiki/Military_beret) theme, hence the security berets.
Science berets don't fit the theme of science department: labcoats and PPE. Is there even such a thing as a "science beret" in real life? Should every department have berets now?

**Comment by KathyRyals** [comment]
It's just cosmetics. It hurts no one. Berets look good.

**Comment by necromanceranne** [comment]
Mimes wear berets. Are they security now?

**Comment by Farquaar** [comment]
> 
> 
> It's just cosmetics. It hurts no one. Berets look good.

1. Oranges has put a freeze on alternative uniforms because there are way too many cosmetic items already. (https://tgstation13.org/phpBB/viewtopic.php?f=10&t=25875&p=550487)
2. By adding a science beret, you are making the military berets of security and the french berets for mimes less unique.

Listen, I like hats. I'm a TF2 player. But the science beret doesn't have any reason to be a thing.

**Comment by KathyRyals** [comment]
Is it an alternative uniform if they don't have a hat in the first place ?

**Comment by KathyRyals** [comment]
Legit question, all departments have hats except for science.

**Comment by Farquaar** [comment]
If you want to make a hat for science, implement a hat that makes sense. It won't be an easy task, since scientists simply don't wear hats (unless you count hazmat hoods), but it's lazy to just crib security's style with a simple recolour.

**Comment by Timberpoes** [comment]
I like 'em. Providing that it doesn't cross over the "alternative outfit ban" territory in which oranges is free to shoot me down in a flaming fire of pain, I can see these being a nice addition to the scidrobes in general.

**Comment by dendyd00m** [comment]
Security are already an exaggerated military LARP. Aren't they supposed to be glorified mall cops? Yet they have a diverse wardrobe of parade uniforms and alternate costume pieces to pick from. The HoS's locker is full of ridiculous authoritarian cosplay stuff. R&D is horrifically ugly. Giving them a beret takes nothing away from security.

People already regularly ask every round for security berets to recolour them, because they look nice, because they're a common and popular piece of headwear.

**Review by Twaticus — CHANGES_REQUESTED** [review]
love department berets but the berets with badges/pins should probably be kept to security only

**Review by Timberpoes — DISMISSED** [review]
Berets are cool and popular. I'm in favour of adding some departmental variants in general.

Of course, providing this also receives the Twaticus seal of approval and avoids the oranges smite of disapproval.

**Comment by ArcaneMusic** [comment]
@KathyRyals Alright, hear me out: so as to not go against the cosmetic freeze, why not make it a grayscale'd beret instead, and give it departmental recoloring with crayons/stamps similar to jumpsuits?
Fits the theme, you can make recolors based on the different departments, and it doesn't incur a sprite tax.

**Comment by KathyRyals** [comment]
I only made this beret BECAUSE science didn't have hats initially.

@ArcaneMusic that's a cool idea but I think it would make for ugly colours.

**Comment by itseasytosee** [comment]
I'm irrationally upset at this but upset none the less.

**Comment by bluetshirtguy** [comment]
cool hats

**Comment by optimumtact** [comment]
As per Twat, no merge sorry.

Also plus the alternate uniforms issue as discussed.

you'd be better of submitting a PR to make berets (sec ones) machine dyeable so you can have your science beret with some extra work IC.

**Comment by wesoda25** [comment]
BERET-CREEP

**Comment by kriskog** [comment]
The only acceptable science hat is a bedhead 1 locked wig

**Comment by wesoda25** [comment]
For real though, the less cosmetics (aka more uniform) the better, there is a very real difference when you look at characters on our server and paradise. At a certain point it’s just snowflake shit.

**Comment by Twaticus** [comment]
@optimumtact ah i just meant no to the pin/badge. i'd rather it just be a plain purple beret like the mime version

**Comment by KathyRyals** [comment]
@Twaticus I'm back on my computer and changing the badge right now.

**Comment by KathyRyals** [comment]
Berets are now plain purple berets.

**Comment by KathyRyals** [comment]
Also here is why I don't want to touch the current beret sprites : 
image

**Comment by itseasytosee** [comment]
Kathy orange already said no. If you really want it that bad you are gonna have to do the work to make it dyeable.

**Comment by KathyRyals** [comment]
> 
> 
> Kathy orange already said no. If you really want it that bad you are gonna have to do the work to make it dyeable.

No, oranges said it depends on Twaticus, Twaticus said yes but no badge.

**Comment by PKPenguin321** [comment]
scientists are nerds they arent allowed to have cool hats

**Review by Timberpoes — APPROVED** [review]
Do Not Merge is removed, so once again this gets my approval from the code side.

This PR still requires Twaticus' approval from the spriting side.

**Review by Twaticus — APPROVED** [review]

**Comment by itseasytosee** [comment]
How dare you

**Comment by Farquaar** [comment]
https://youtu.be/J0dWq7cRo30?t=200

**Pull request merged**
