### PR TITLE
Refactor Stat Panel styles and more TGUI-like appearance

### PR DESCRIPTION
**Pull request by AyIong**
## About The Pull Request
The PR came out a little bigger than I had planned, but creating separate ones for a couple of little things seemed unnecessary to me.

Let me start with the most important thing: Stat Panel now scales like TGchat and also looks closer to TGUI!
By default, the Stat Panel font size is tied to the chat font size, but this can be changed in a couple of clicks...

The rest of the changes are not as big:
1. Stat Panel styles are now more organised
2. The way themes are applied to Byond Skin has been refactored, if someone decides to make a new theme (maybe me), it won't be necessary to copy all the elements
3. NumberInput into the general chat settings tab, was changed to slider
4. Reoder tab buttons changed, they are more compact now
5. With the light theme, chat tabs now have a background when hovering/active tabbing
<details>
<summary>How it look's like</summary>

| New reorder tab buttons | Light Chat tabs | 
| - | - | 
| image | image |

</details>
<details>
<summary>General Preview</summary>

 https://github.com/user-attachments/assets/7647d584-c2fd-41b2-b2ee-c7ee61569d1f

</details>

## Why It's Good For The Game
More accessibility for owners of 2/4k monitors
Better appearance
NumberInput is behaving extremely strangely in chat

## Changelog

:cl:
add: Stat Panel now scales like a chat, depends on the font size. Defaults from the chat font size, but you can separate it.
refactor: Refactored Stat Panel styles and Byond skin theme applying. Stat Panel now looks more like a TGUI
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
The famine is rampant across the landscape and it's your fault for leaving us without pictures

**Comment by AyIong** [comment]
> The famine is rampant across the landscape and it's your fault for leaving us without pictures

Video better than pictures :high:
image

**Comment by tolliamlew** [comment]
The menu tabs("Status, MC, Admin, Debug," etc.) at the top are now forced into a scrollbar instead of stacking vertically, which is an issue for those who are using a narrower chat bar. This makes it incredibly unwieldy to swap between the panels, especially between status and any of the useful admin ones like Game and Tickets.

**Comment by AyIong** [comment]
> The menu tabs("Status, MC, Admin, Debug," etc.) at the top are now forced into a scrollbar

Fixed here - https://github.com/tgstation/tgstation/pull/85399

**Pull request merged**
