### PR TITLE
Tools are visible on belt sprites

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
tweak: Tools are now visible on belt sprites
/:cl:

capture

### CODE REVIEW

**Comment by Chronitonity** [comment]
That looks cluttered as hell

**Comment by MoreRobustThanYou** [comment]
The sprites are from paradise

**Comment by Armhulen** [comment]
that toolbelt is actually disgusting

**Comment by Chronitonity** [comment]
its a cool idea but it just looks like someone threw up all over a toolbelt

**Comment by PraiseRatvar** [comment]
maybe get someone to redo the sprites on the toolbelt?

**Comment by ShizCalev** [comment]
Sprite looks like ass but good idea.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
There's been no code change?

**Comment by dannno** [comment]
that looks awful

**Comment by dannno** [comment]
if you want to do this you have to make a sprite where the belt is laid out flat and then add the tools on top
ie.

**Comment by ChangelingRain** [comment]
idea good, sprites awful.

**Comment by BeeSting12** [comment]
The sprites awful, it reminds me of an alien-robot and if I saw it ingame I'd probably run and fire a few lasers to make sure it isn't chasing me.

**Comment by Steelpoint** [comment]
Do what the security belt does and only display sprites for two or three items.

Having all the engineering items on the belt really clutters it up.

**Comment by WJohn** [comment]
What everyone else said.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Do it like the sec belt or don't do it at all

**Comment by Cyberboss** [comment]
Closing in favor of @Xhuis's

**Pull request closed without merging**
