### PR TITLE
fixes birdshot disconnected area

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

changes literally 1 tile area

## Why It's Good For The Game

image

this is bad

## Changelog

CI isnt for players

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
Please explain how this fixes the issue so that mappers who encounter this in the future know the problem

**Comment by mc-oofert** [comment]
uhh dont put a 1 tile area in space that has absolutely no floor

**Review by Maurukas — APPROVED** [review]
Very good. Merge master and fix conflicts please.

**Comment by mc-oofert** [comment]
done

**Pull request merged**
