### PR TITLE
Revenants can now eat salt

### PR DESCRIPTION
**Pull request by PKPenguin321**
## About The Pull Request

Well not really, but they can dissipate it by scattering it to the wind using ghostly magicks. If they step on it the same thing will happen as before, but the salt will get destroyed. If they click on it, a do_after(10) will run and then they will dissipate it.

## Why It's Good For The Game

I got to roll revenant today, and within a minute of me getting found out, the crew used 1 salt-smoke to immediately deny me entrance to medbay permanently. Salt is pretty easy to apply and impossible to play around, which sucks, so I thought this would be a good change.
It's pretty noticeable and not very fast when a revenant eats through salt, so you'll know that one is coming if they try this.

## Changelog
:cl:
add: Revenants can now click on salt to scatter it to the wind after a very brief delay. They will do this automatically to any salt pile that they get stunned on.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
>within a minute of me getting found out, the crew used 1 salt-smoke to immediately deny me entrance to medbay permanently

never seen this, sounds like an uncommon occurrence

**Comment by FancyCyclops** [comment]
ided

**Comment by mrhugo13** [comment]
i guess the revs were just too _salty_ from that strategy

**Comment by PKPenguin321** [comment]
>never seen this, sounds like an uncommon occurrence

You've never seen a salt smoke? I had seen it before as a crewmember but never realized how hard it counters revs until I had it used on me

**Comment by tralezab** [comment]
yeah salt smoke can trap a revenant pretty easy. i'm not sure i'm 100% on board with this solution specifically, but in general it's really strong

**Comment by cacogen** [comment]
I've seen a lot of revenants, I haven't seen this strategy employed before

**Comment by Dawson1917** [comment]
The Defile ability gets rid of salt and holy water in a large area. It's still trivial for chemists to spam 0-second salt smoke grenades or spray bottles to trap you without there being any way for revenants to destroy chem dispensers

**Comment by AdamElTablawy** [comment]
The issue with revenant is either it faces an insurmountable obstacle like salt smoke that denies it the ability to do anything, or it becomes an obnoxious, permanent nightmare that nobody can track down and kill.

This makes salt easier than holy water to bypass, and the crew can just put holy water in the smoke machine instead for the same effect-easy, if the chaplain blesses a water tank.

I get your frustration, but this isn't gonna be a viable solution. You'd have to pretty much rework revenant some to move it out of the binary 'instantly stopped' or 'forever nuisance' kind of deal it has going on, and dispelling salt like this will just make the crew use holy water smoke instead.

**Comment by necromanceranne** [comment]
Can't it already remove salt with one of it's powers.

**Comment by ATH1909** [comment]
> Can't it already remove salt with one of it's powers.

Yep, it can use Defile to remove salt in an AoE. 

If revenant is floating inside a wall while that wall gets surrounded by salt, does it have any way to escape? It can't cast defile while inside of a wall.

**Comment by PKPenguin321** [comment]
>If revenant is floating inside a wall while that wall gets surrounded by salt, does it have any way to escape? It can't cast defile while inside of a wall.

Nope!

**Comment by Mickyan** [comment]
if you manage to trap a revenant then it deserves to be put in a bad spot, at best dissipating salt piles should reveal the revenant otherwise you're just removing the only tool the crew has to stop the grief ghost from ruining their day

**Comment by PKPenguin321** [comment]
>if you manage to trap a revenant

this is not difficult because of salt smoke

I'm starting to think I should instead remove salt smoke but I'm not sure how that would work

**Comment by Mickyan** [comment]
if you're going to be like that I can just suggest not hanging around the two jobs on the entire station that have access to the resources to stop you

**Comment by AdamElTablawy** [comment]
@Mickyan 

not feasible tbh they'll chase you around with salt smoke because they have nothing better to do, try playing a round to figure that out

if you want to limit salt some, you could do what goon did with it and make crossing a salt pile as a human eventually scatter it. you could also make salt require a minimum amount to be applied to the floor, so like rather than literally any amount of salt, increase the requirement, so that smoke grenades can't have quite as large of a radius

**Comment by PKPenguin321** [comment]
>if you're going to be like that

Any perceived offense is on your end because I meant none

>make crossing a salt pile as a human eventually scatter it

I think I like this idea more than what I've got in this PR, actually. I'll do that

**Pull request closed without merging**
