### PR TITLE
Fixes 512 compile reminders

### PR DESCRIPTION
**Pull request by ninjanomnom**
Fixed some code that was waiting on 512 and had compile time version checks

### CODE REVIEW

**Comment by SpaceManiac** [comment]
`#warn` not `#warning`

**Comment by ninjanomnom** [comment]
they both work

**Comment by SpaceManiac** [comment]
erf

**Comment by lzimann** [comment]
We either go 512 already or we wait, adding those checks is kinda of awful in my opinion. Someone can re-open if disagree and what not.

**Pull request merged**
