### PR TITLE
Adds pony race

### PR DESCRIPTION
**Pull request by optimumtact**
Adds the pony race to the master branch

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
why god

**Comment by Bawhoppen** [comment]
uh oranges are you okay

**Comment by optimumtact** [comment]
Whoops I pulled all of the april fools shit in

give me a bit

**Comment by PKPenguin321** [comment]
Why have you done this

**Comment by bgobandit** [comment]
meme pr

**Comment by 9600bauds** [comment]
I see the superior coderbase is hard at work in bringing the new and latest features

**Comment by Core0verload** [comment]
:+1: for the idea, but your PR is such a mess. Just copy my pony branch and push it in.

**Comment by Bawhoppen** [comment]
@Core0verload thats what I told him to do but he won't listen

**Comment by optimumtact** [comment]
@9600bauds, I'm sorry, did I hear you say, please port this to vg once you're done here?

**Comment by KorPhaeron** [comment]
Please clean up your PR, we simply can't merge it in this state

**Comment by optimumtact** [comment]
The heck, don't close it you meanie

**Pull request closed without merging**
