### PR TITLE
fixes the changeling tentacle inhands

### PR DESCRIPTION
**Pull request by ghost**
turns out the inhands were reversed

### CODE REVIEW

**Comment by lzimann** [comment]
proper title please

**Comment by PraiseRatvar** [comment]
why can't changelings be cripples?

also no need for a CHANGEBOG FOR A MINOR THING AAAAAAAAA

**Comment by MrStonedOne** [comment]
No need, sure,

Doesn't mean you can't anyways.

I want to see the day when every pr details what they did in the changelog.

**Comment by Cyberboss** [comment]
I agree, we need more categories though (Refactor, Configs, API changes, etc...(

**Comment by KorPhaeron** [comment]
@Cyberboss @MrStonedOne 

Can we get two tabs then? One for new features/big fixes, and another for minor tweaks/little fixes like this? The changelog is an unsorted mess and nobody would read it and be aware of new features if it was filled with "fixed the pixel offset of the corgi hat" for 100 lines

**Comment by Cyberboss** [comment]
Comment that in the changelog PR please

**Comment by optimumtact** [comment]
I removed teh changelog, this is an absolutely non player impacting change.

coders can review the git log for code related changes, there is no need to put them in the player changelog

**Pull request merged**
