### PR TITLE
Adds ear scratches for catpeople

### PR DESCRIPTION
**Pull request by Bajiru-no-Dansei**
:cl: Bajiru
add: Added ear scratches for catpeople
/:cl:

[why]: # More roleplay for people wishing to be catpeople/interact with them, is also cute.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Brand new account, throwaway name based on annie mays to prevent figuring out the ckey, just joined today and immediately PRs a feature for a controversial topic with a vague shield of "roleplaying"?

2/10, try again later.

**Comment by Bajiru-no-Dansei** [comment]
This isnt for drama

**Comment by Jared-Fogle** [comment]
Didn't even get the changelog syntax right

**Comment by Bajiru-no-Dansei** [comment]
How do I make it work??

**Comment by Militaires** [comment]
ass spanking emotes when

**Comment by Kawaii-Big-Boss** [comment]
>Drinking PR gets rejected and the creator gets banned
>Let's allow catgirl PRs though
absolute
state

**Comment by MMMiracles** [comment]
could you also make it so it force-wags their tail if they currently have one

thanks

**Comment by Bajiru-no-Dansei** [comment]
@MMMiracles Sure!

**Comment by Bajiru-no-Dansei** [comment]
Woops, closed by accident!

**Comment by deathride58** [comment]
Jesus christ, even Citadel doesn't stoop to this level of degeneracy

**Comment by Bajiru-no-Dansei** [comment]
Ear scratches now auto-trigger tail wagging.

**Comment by optimumtact** [comment]
No thank you

**Comment by nervere** [comment]
Madam headcoder oranges saves the day once again.

**Comment by epicmemename** [comment]
black pants legion army is here to demand you reopen this pr

**Comment by Bajiru-no-Dansei** [comment]
Awww

**Comment by Kawaii-Big-Boss** [comment]
@optimumtact 
>make comment regarding how this stays up despite the thirst PR getting banned
>based oranges closes this PR
>marks my comment as resolved

we need more of this on /tg/

**Comment by Anonmare** [comment]
I think this PR is worth considering

**Comment by epochayur** [comment]
gitban anime avis

**Comment by Cw3040** [comment]
we should honestly have this verb, and a positive moodlet to go with it

**Pull request closed without merging**
