### PR TITLE
Adds dance machine, drink dispensers, flavor to beach bum ruin

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: NanoTours is proud to announce that the Lavaland beach club has been outfitted with a dance machine, state of the art bar equipment and more.
/:cl:

The beach bum ruin was lacking in content other than "overdose on spraytan and suicide" or the classic "run off to lavaland and die".

I added booze/soda dispensers so people can mix drinks, a dance machine to well, dance, as well as aesthetic sunglasses because you're on a beach. Other than that I gave airlocks proper names and moved some items into the bar backroom.

Also a second beach bum spawner because there is now enough content to let an additional player live out the fantasy of being a fit, outgoing person.

### CODE REVIEW

**Comment by Borisvanmemes** [comment]
Dance machines are laggy messes last i checked, apart from that, this is a good idea!

**Comment by SpaceManiac** [comment]
Double-check that the dance machine is usable, I think it requires to be anchored.

**Comment by 81Denton** [comment]
Right, I should probably check access as well.

**Comment by 81Denton** [comment]
I replaced the danche machine with /indestructible, that also prevents miners from unwrenching and dragging it back to the station every other round.

**Comment by Shadowflame909** [comment]
What's the point. People just use this ruin to metagame and nothing else...

**Comment by DaxDupont** [comment]
Add drugs

**Comment by 81Denton** [comment]
@DaxDupont I'll add some special stuff to the cig vending machine

**Comment by 81Denton** [comment]
Alright so
- Added a /beach subtype of the cigarette vendor that stocks cannabis rollies and as a premium product, mindbreaker rollies. The other contraband products have been moved to premium since beach bums have money to pay for them.
- Added showers and extra lights. The middle of the beach is a bit dark, maybe an invisible floorlight would help?
- Moved the bartender spawn into the backroom, so it's no longer in the middle of the damn floor.

**Review by SpaceManiac — APPROVED** [review]
You can add an invisible floorlight if you think it's warranted, otherwise LGTM.

**Comment by improvedname** [comment]
Add a beach music track to dance machine

**Comment by 81Denton** [comment]
Tracks are managed by admins

**Pull request merged**
