### PR TITLE
Adjust Vortex Core Max and Beam Rifle recipe.

### PR DESCRIPTION
**Pull request by Redrover1760**
## About The Pull Request
Vortex cores were set to 1 max in order to specifically limit a beam rifle from ever being made more of in a round. This PR sets the amount of vortex cores needed for the Event Horizon Anti-Existential Beam Rifle to two, and increases the max Vortex cores capable of being made to 3 in order to give leeway to use vortex cores for other things and not have it only capped at 1. 

## Why It's Good For The Game
Still stops the ability to create multiple black hole rifles, but allows for more vortex cores to be made for other needs. 

## Changelog
:cl:
balance: Changed max refined vortex cores from 1 to 3. Changed the Event Horizon Anti-Existential Beam Rifle recipe to require 2 vortex cores.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
If you want to open the possibility of having both a stealth armor and a gun, the better solution is to not use magic numbers, but instead define it as ``(MAX_CORES_VORTEX - 1)`` so that the value is always permissive of more cores.

The choice of this value was always to future proof it in the event that someone wants to increase the cores, without opening the possibility of allowing more AEBRs into a round. 

If you want to add more vortex cores, it must not compromise this concession, because I cannot sit comfortable nor do I trust anyone in the future to not allow for more of this gun to enter a round. I would push to remove the gun outright than take that risk and I very much mean it.

**Comment by Redrover1760** [comment]
> If you want to open the possibility of having both a stealth armor and a gun, the better solution is to not use magic numbers, but instead define it as `(MAX_CORES_VORTEX - 1)` so that the value is always permissive of more cores but not of more guns. That's why I used the define at all.
> 
> The choice of this value was always to future proof it in the event that someone wants to increase the cores, without opening the possibility of allowing more AEBRs into a round. While this will continuously nerf the recipe for the gun, there is just no way the game can be healthy in a state where you can possess more than one. That is just the concession that has to be made every time that number goes up.
> 
> If you want to add more vortex cores, it must not compromise this concession, because I cannot sit comfortable nor do I trust anyone in the future to not allow for more of this gun to enter a round. I will push to remove the gun outright than take that risk and I very much mean it.

If the max number of vortex cores is increased say to like, 8, then it'd take a full 7 vortex cores to make a gun. I get you never want to see more than one, but I don't really think that's a good solution to this issue. 

My main issue is that vortex cores shouldn't be used as a limiting feature when they have other interactions, such as stealth anomaly armor, which means that the armor is gutted and literally unique unlike every other reactive armor that exists... I can make that change if you really want, but I don't see it as a good thing.

**Comment by necromanceranne** [comment]
Anomaly core locked equipment is designed with a few things in mind; A) how many cores in the recipe can be made in the given round, and B) how many it takes up overall to make. The more powerful, the lower the overall cores that can become available in the round, based on the number of cores it takes to make. Since this is, bar none, the strongest crew weapon in the game by a considerable margin (I don't care about the meme hammer), I always intended for it to eat all of the vortex cores to maintain its exclusivity, and maintain compliance with the design for anomaly items. 

If you think this design is restricting other possibilities, then remove the AEBR. It cannot reasonably co-exist with an increased availability of vortex cores unless it is always going to have to take the vast majority of them out of a round, and never permit more than one. The game's health cannot deal with multiple AEBRs in a round. I don't care if it means you have to choose between making more armors or an AEBR. _That's the point and I want players to make those decisions._

**Comment by Jacquerel** [comment]
To be clear "number of cores should never be used as a limiting feature" is the opposite of the intended purpose of anomaly cores, that's specifically what their purpose is.

**Comment by Time-Green** [comment]
I think this is okay. The beam rifle is limited by tator tech already and this makes it even a little bit harder to get, while also letting someone make like a reactive armor or something

**Pull request merged**
