### PR TITLE
[Merge Ready] Updates Map Merge

### PR DESCRIPTION
**Pull request by CorruptComputer**
Added a GUI that scans a directory for all files ending in .dmm

Screenshots:

### CODE REVIEW

**Comment by Miauw62** [comment]
this is really nice :+1:

**Comment by CorruptComputer** [comment]
I'm also pretty sure that this works with any byond game now as well, but I have no idea how thats useful.

**Comment by WJohn** [comment]
What does this change for us mappers? Is the map merger more competent in some way?

**Comment by CorruptComputer** [comment]
I just made it easier to use.

**Comment by d3athrow** [comment]
butts

**Comment by JJRcop** [comment]
Think you could include your source code like the old one had?

**Comment by JJRcop** [comment]
This does seem a little bit, strange... Did you intend to delete the old source code? It seems like you still use it.

**Comment by CorruptComputer** [comment]
It should be in the source folder, I just copied my entire project. I'll manually add it.

**Comment by JJRcop** [comment]
Okay it's still there github diff was fooling me

**Comment by JJRcop** [comment]
Uh, is that supposed to be in Source/bin/MapMerger, wouldn't it be better in Source/src, like the other files?

**Comment by CorruptComputer** [comment]
@Cheridan This is ready.

**Comment by Razharas** [comment]
Dont understand a single word of java but looks nice why not lets try what can go wrong right, RiGHT?

**Pull request merged**
