### PR TITLE
[NO GBP]Fixes some mapped SMES starting with low energy.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
Scales them all by up to 20 to account for removing the dumb SMESRATE define. This isn't a 100% conversion for every SMES because it would go beyond their capacity (old SMES use to duplicate cell energy, so they had a higher capacity than their cell parts imply). Also removes instances of varediting their capacity to fucking 1e+600 and replaces them with magical SMES.
## Why It's Good For The Game
So lavaland and crap don't instantly run out of power. Also I don't think we should be varediting anything to 1e+600.
## Changelog
:cl:
fix: Fixes lavaland SMES and other crap from not starting with enough energy.
fix: The pirate SMES are now magical instead of secretly infinite.
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
do the same with the pirate ships please 🙏 🙏 🙏

**Comment by Pickle-Coding** [comment]
> do the same with the pirate ships please 🙏 🙏 🙏 

I did it for all mapped SMES.

**Comment by san7890** [comment]
would you mind changing the really common ones like

```dm
/obj/machinery/power/smes{
	charge = 5e+007
	},
```

into a subtype, and then making an update paths to correct them all? we don't need a subtype for every single var-edit variation we see in maps, but i would appreciate it if the most common ones got corrected so we limit the number of de-syncs we see between code and maps in the future.

**Comment by Pickle-Coding** [comment]
Sure. I'll just have to figure out what these SMESes actually represent first.

**Comment by SyncIt21** [comment]
conflicts :(

**Comment by san7890** [comment]
```txt
loading _maps/map_files/tramstation/tramstation.dmm
_maps/map_files/tramstation/tramstation.dmm:19840:error: undefined type: /obj/machinery/power/full
_maps/map_files/tramstation/tramstation.dmm:19843:error: unknown type
_maps/map_files/tramstation/tramstation.dmm:21855:error: undefined type: /obj/machinery/power/full
_maps/map_files/tramstation/tramstation.dmm:21859:error: unknown type
_maps/map_files/tramstation/tramstation.dmm:[34](https://github.com/tgstation/tgstation/actions/runs/8457496584/job/23169599287?pr=82203#step:4:35)621:error: undefined type: /obj/machinery/power/full
_maps/map_files/tramstation/tramstation.dmm:34624:error: unknown type
_maps/map_files/tramstation/tramstation.dmm:58410:error: undefined type: /obj/machinery/power/full
_maps/map_files/tramstation/tramstation.dmm:58414:error: unknown type
```

lol

**Comment by SyncIt21** [comment]
...

**Pull request merged**
