### PR TITLE
Re-Added MetaStation, Updated MetaStation.v39K to MetaStation.v40B.dmm

### PR DESCRIPTION
**Pull request by Metacide**
MetaStation v40A
HD Image: https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-02-07%2018-10%20MetaStation.v40B%20Full.png

-Major updates to allow compatibility with current code, all done by Allura, as far as I'm aware.
-Addition of conveyor belt and cargo tagger from cargo bay to mailroom
-Changed the bridge to a dark-tile base, a more dramatic appearance
-Added a medical surplus storage room south-east of medbay
-Various small fixes and minor adjustments
-Mapmerge used (v39K->v40A->v40B)

Massive thanks to Allura, who has done more or less all the work keeping this up to date.

I haven't done this in a while, so please tell me if I made any mistakes with Git.

Once I'm sure this is formatted properly in the repo and working, it is my intent to maintain it for some time. Once I've made sure it's working I'd be looking towards doing a test on Basil/Badger, if at all possible. If anyone has any suggestions or comments, they're very welcome either here or (more visibly, perhaps) on the forums, and more info is on the wiki:

https://tgstation13.org/phpBB/viewtopic.php?f=11&t=399
http://tgstation13.org/wiki/index.php/MetaStation

### CODE REVIEW

**Comment by paprka** [comment]
:+1: welcome back

**Comment by Miauw62** [comment]
/Metacide gestures!/
*Metastation shudders and begins to move!*

**Comment by RemieRichards** [comment]
While I'm not a fan of what this will mean for Badger/Basil and my own play, I guess it's good to see you back.

**Comment by Metacide** [comment]
I heard that /vg/ had some sort of map vote system. Might be very nice to see an automated process like that on Badger/Basil one day, letting people choose maps appropriate for playercount and such.

**Comment by WJohn** [comment]
Praise be

**Comment by Anonus** [comment]
It's happening, it's happening!

**Comment by ike709** [comment]
luv u Metacide, welcome home

**Comment by pudl** [comment]
metacide, download the file i put up most recently. its completely updated for paprika's blood pr

**Comment by GunHog** [comment]
All Hail Metacide! The best station map returns! :+1:

**Comment by paprka** [comment]
Tinted windows aren't really hurting anything. They were bad before because of directional windows and not fulltile windows. You could have a window facing a wall but it would still block all directions and it was really, really broken.

**Comment by RemieRichards** [comment]
@GunHog >opinion

**Comment by Deantwo** [comment]
Remember to update the [wiki page](https://tgstation13.org/wiki/MetaStation) with the nice picture.
Also a picture with all pipes and wires would nice for [engineering/atmos reference](https://tgstation13.org/wiki/Station_Engineer#Engineering_Reference_Map).

**Comment by TZK13** [comment]
:+1: :+1: :+1:

**Comment by Metacide** [comment]
Updated the wiki and added a reference map.

**Comment by Deantwo** [comment]
Awesome! :+1:

**Comment by fj45** [comment]
Next to the HoP office in the hallway seems to be an out of place blast door.

**Comment by Metacide** [comment]
Thanks for the heads-up, will clear that up with the next update. :+1:

**Comment by Deantwo** [comment]
Only thing I still don't like with the other stations than BoxStation is that the plating in maintenance look like they are damaged even though they aren't.
I wasted a lot of welding fuel on that once, wondering why I couldn't fix them.

As far as I know a damaged plating actually leak air, so them looking that way is really weird.

**Comment by TZK13** [comment]
At a quick glance I don't see a clothesmate anywhere, if I'm right and it's not been added it should be in the locker room like it is on Box.

**Comment by Anonus** [comment]
Damaged plating doesn't leak air, that's a myth.

**Comment by Deantwo** [comment]
@Anonus still looks wrong in my eyes.

**Comment by ike709** [comment]
>At a quick glance I don't see a clothesmate anywhere, if I'm right and it's not been added it should be in the locker room like it is on Box.

NT's metastation does T_T

**Comment by Iamgoofball** [comment]
@Metacide 

no chem heaters in chemistry, they're needed for making some core chemicals

**Comment by paprka** [comment]
Please replacing pseudo damaged plating with actual damaged plating in maint. It's inconsistent with actual damaged plating seeing as how you can't repair it. Things this map needs to be up to snuff:

- IV drips in medical (see box)
- Some crates with an assortment of blood packs (again, see box)
- A better medical storage -- it's really disorganized right now thanks to allura's shit mapping but I'm sure you can make it organized again. Remove the 'reserve vat' beakers in there, they're useless and free large beakers which are supposed to be rare resources for chemists.

**Comment by TZK13** [comment]
There's already IV drips and freezers with blood packs on the map from what I can see but something I would like is a dedicated room for them.

**Comment by paprka** [comment]
Yeah, I see them now. It's a non-issue then, this can be merged as it's not fixing super priority issues. We should get this on basil ASAP, and also onto travis testing.

**Comment by Metacide** [comment]
I'll do some fixes this evening actually, make sure they work, then if anyone's willing I'd appreciate a pull sometime.

**Comment by samis** [comment]
Meta's back? yay, Metastation was always my favourite map.

**Comment by pudl** [comment]
i kept this map updated for almost a year, if i'm going to coerce any sort of "return" for the favor, it's leaving in the reserve tanks. they've shown to be useful on badger rounds that eff3 was running.

**Comment by paprka** [comment]
MDs aren't chemists, go back to goon. This map has been updated but never run on badger, so it's kind of a moot point and you wasted your time.

**Comment by Deantwo** [comment]
Yeah, I never understood the "reserve tanks" beakers.
Only really *Charcoal* and *Epinephrine* made sense because those you can use with a syringe.
But the *Styptic Powder* and *Silver Sulfadiazine* made little sense for anything other than to give to the chemists.
And as it is right now the venting machines are stocked up on all of those, so no it wasn't really of any use unless it is a very long round and no one wanted be a chemist for a few minutes.

**Comment by Metacide** [comment]
Ok, this is ready to go. Testing only revealed minor issues, all have been fixed as far as I'm aware.

**Comment by paprka** [comment]
Conflicts!

**Comment by Metacide** [comment]
Oh damn. Is it just the admins list commit?

**Comment by paprka** [comment]
No clue, pull from upstream

**Comment by Metacide** [comment]
Any idea how I can pull that commit out of this pull request?

**Comment by RemieRichards** [comment]
@Metacide that's far harder than just fixing the conflict.

**Comment by Metacide** [comment]
Should be ready now?

**Comment by Metacide** [comment]
Stellar, thanks very much. Updating the wiki and thread now.

**Comment by palpatine213** [comment]
@Metacide Got an error with the map just now while compiling after the merge. Bad path with the tequila bottle. It's named tequilla on the map, but tequila on the code.

**Comment by Deantwo** [comment]
#7568 fixed that spelling error.

**Comment by Metacide** [comment]
Fixed in pull request above, hopefully.

**Comment by Iamgoofball** [comment]
the meta begins

**Pull request merged**
