### PR TITLE
Adds Asteroid emergency shuttle to shuttle templates

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Adds Asteroid emergency shuttle to shuttle templates. It is a very oddly shaped one though, it might not be compatible with all stations.
/:cl:

image

### CODE REVIEW

**Comment by Kromgar** [comment]
Pics?

**Comment by xxalpha** [comment]
Ugly non smooth walls.

**Comment by pudl** [comment]
What a hideous creation please just redesign it to not have those atrocious airlocks

**Comment by coiax** [comment]
I mostly just like the 3 random empty closets.

**Comment by Iamgoofball** [comment]
8==========D

**Pull request merged**
