### PR TITLE
Mixing Drinks and Changing Lives - New Drinks

### PR DESCRIPTION
**Pull request by Sylphet**
## About The Pull Request

This PR adds several drinks that can be made in VA-11 HALL-A. It's a work in progress and anything might be changed based on what people think - helpful criticism is appreciated!

## Why It's Good For The Game

We already have three drinks from it merged - this adds fourteen more, each with original sprites, some of which are animated. It gives bartenders more options, and every drink added is easy to make, making the recipes easy for newer players to follow, or veteran players who don't feel like making anything complicated.

## Changelog
:cl:
add: Adds several of the drinks missing from VA-11 HALL-A. Time to mix drinks and change lives.
/:cl:

## Terrible Sprites
sprites_final

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Any cool effects or just fluff?

**Comment by Sylphet** [comment]
just fluff at the moment - each drink will have cool effects added if people are interested in this pr

**Comment by Angustmeta** [comment]
They all have wrong perspective (side), though many of our existing drinks do. 

Also I'd appreciate if you add them to the wiki if they get merged, as that would probably take me hours to do properly.

**Comment by Sylphet** [comment]
oh, yeah, i'll add them to the wiki within a few days if they're merged

**Comment by Tlaltecuhtli** [comment]
they look meh and dont have any use other than signaling other weebs about their anime knowledge

**Comment by Sylphet** [comment]
thank you, very cool

**Comment by Farquaar** [comment]
I can see you made an effort to condense the sprites from the original game, but some of those sprites are way too big. I mean, take a look at these side-by-side.
sprites

Not only are these sprites way taller (and in some cases, wider) than bottles, they're oversized compared to the VA-11 HALL-A drinks already in game. I can help fix some of these sprites if you'd like, but they really shouldn't be this huge.

**Comment by Sylphet** [comment]
thanks, that's helpful. first time sprinting so i wasn't really sure how big they needed to be - it shouldn't be too hard to fix though

**Comment by ExcessiveUseOfCobblestone** [comment]
how did we go from "takes a few drinks from this game, cool references" to "literally port every item from this game"? That seems to be a bit much imo...

**Comment by Sylphet** [comment]
it isn't literally every item, and i don't mind cutting a few of the similar ones if the number is a problem - the reason is that i think that adding so many works is because these fit the theme of a futuristic space station much more closely than a martini, and i want to expand on that. it's not really « haha, funny reference to anime game » so much as it's having new, strange looking, and stranger tasting future cocktails, i think.

**Comment by optimumtact** [comment]
We don't need more drinks.

**Pull request closed without merging**
