### PR TITLE
Allows you to wear the caution sign + new sprite for the caution sign

### PR DESCRIPTION
**Pull request by Nickkoranda**
## About The Pull Request

Allows you to wear the caution sign on your exosuit slot. Does not provide any additional stats* while being worn except having high fashion and spam pointing on yourself when people inevitably slip. 
Additionally the caution sign has been repathed from /obj/item/caution to /obj/item/clothing/suit/caution
*After much coercion I have been forced to add armor to the caution sign

Sprites
Sprites by @WJohn 
## Why It's Good For The Game

Allows janitors to become a portable sign, helping you realize that there are wet floors aloof.

## Changelog
:cl: blargety & WJohnston
imageadd: Caution sign resprited
add: You can now wear the caution sign on your armor slot
/:cl:

### CODE REVIEW

**Comment by Rowelll** [comment]
i love it

**Comment by shellspeed1** [comment]
Less excuses for people to bitch at the janitor for not having a sign out. Good idea.

**Comment by ExcessiveUseOfCobblestone** [comment]
should have some really minor brute armor tbh

**Comment by necromanceranne** [comment]
Time to wear this as rev janitor

**Pull request merged**
