### PR TITLE
if you give a monkey an instrument, it will begin playing the donkey kong theme

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

if you give a monkey an instrument, it will begin playing the donkey kong theme

## Why It's Good For The Game

This seems like a no brainer, ai subtrees were basically BORN for this amazing niche interaction. you can now have pun-pun be your bar musician!

https://www.youtube.com/watch?v=Xqf8jID9TsE

## Changelog

:cl:
add: Hand a monkey an instrument. It'll play a cool song!
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Review by Mothblocks — APPROVED** [review]

**Review by Mothblocks — APPROVED** [review]

**Review by Mothblocks — APPROVED** [review]

**Comment by BallastMonster** [comment]
merge

**Comment by GuillaumePrata** [comment]
Massive Pun Pun buff

**Comment by Nobelium-XVIII** [comment]
speedmerge

**Comment by GoldenAlpharex** [comment]
Lmao

**Comment by nianjiilical** [comment]
this is the single greatest pr i have seen in my year and a half of being a part of tgstation and i will now vote tralezab for headmin

**Review by Kylerace — APPROVED** [review]

**Comment by TheSmallBlue** [comment]
This is fucking amazing BUT, when I go bartender I usually start playing something on my instrument and then give the instrument to the bar monkey so that I can have both hands free while my music of choice still plays. Won't this break that?

**Comment by tralezab** [comment]
I will in the sense that the monkey will change your track, the solution is a bar jukebox or pun pun remembering what songs you hand to them obviously... which actually, as codemonkey told me to make this generic down to what songs the monkeys play, I could probably make that happen in a followup pr so you may still be allowed to have pun pun play music for you

In general I would really like if pun pun acted different ai-wise to most monkeys so they're like a cool butler bro you actually want around

**Comment by TheSmallBlue** [comment]
> In general I would really like if pun pun acted different ai-wise to most monkeys so they're like a cool butler bro you actually want around

PLEASE. I'm so tired of the little rascal just taking anything and everything it can get its grubby hands on like an ANIMAL. Not lovable at all.

**Review by Watermelon914 — APPROVED** [review]

**Comment by wesoda25** [comment]
I like doing that too? Could we just make it so that pun pun plays whatever you hand to them, default being DK if no song is loaded?

**Comment by tralezab** [comment]
@wesoda25 Sounds like a plan, consider it done. The only thing is that I'm planning that aforementioned Pun Pun ai pull request, I'm going to include it in that

**Pull request merged**
