### PR TITLE
Adds hourglass

### PR DESCRIPTION
**Pull request by AnturK**
Mostly for admin events but will add normal version source if i can get proper sprite.

New fancy sprite by @MrDoomBringer
Also makes SpinAnimation used in throwing use ANIMATION_PARALLEL

:cl:
add: Hourglasses now available in library game vending machine.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
for a proper sprite, how would the sprite reflect time passing? Just an on/off state? Or an animation that animates slower or faster depending on the time set by the hourglass?

**Comment by AnturK** [comment]
Right now it's just simple on/off + countdown for ghosts (or everyone if admin varedits). If someone bothered to make partial sprites i could adjust the code for it.

**Comment by MrDoomBringer** [comment]
@AnturK Hows this? https://i.imgur.com/GlQ5Dsw.gifv

**Comment by AnturK** [comment]
Looks great, can you send the dmi over ?

**Comment by MrDoomBringer** [comment]
@AnturK just sent it via discord

**Pull request merged**
