### PR TITLE
Fixes Disposal in Bar - Fixes #9619

### LINKED ISSUE #9619: Bar disposals don't work properly
Tested on latest revision as of time of posting.
feeb

From what I can tell, the disposal trunk is one tile too far to the right.
space station 13 2015-05-23 172154

### PR DESCRIPTION
**Pull request by Summoners**
Fixes #9619 

No need to panic, Bartenders, this issue has been solved.

### CODE REVIEW

**Comment by xxalpha** [comment]
This PR should have both of your map changes.

**Comment by Summoners** [comment]
@xxalpha, yeah I know. I however just got back to using Git and had a hard enough time with just this pull. I didn't want to mess that up somehow.

**Comment by xxalpha** [comment]
Fair enough. It's just good practice to keep all your map changes in one PR, it's a pain in the ass doing any map edits as it is.

**Comment by Cheridan** [comment]
getting fixed by another PR

**Pull request closed without merging**
