### PR TITLE
[WIP] Removes the /goon folder and replaces all Goonstation assets.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

As it says in the title.

This, once finished, will remove the /goon folder and everything in it, and replace the assets with free ones.

To-Do:

- [x] Replace the solar stuff.
- [x] Replace the punching bags
- [x] Replace the bank machine.
- [ ] Replace the exercise eqipment.
- [ ] Replace the weed.
- [x] Replace the dish driver.
- [x] Replace spring.ogg.
- [x] Replace FireAlarm.ogg.
- [ ] Send the /goon folder to hell.

Credits (so far):

Me: Dish drive sprites, solar sprites, bank machine screen.

Baystation: Punching bag sprites.

Screenshots:

Screenshot_136

Screenshot_150 9

Screenshot_156

Screenshot_146

## Why It's Good For The Game

The less nonfree assets we have, the better.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
why?

**Comment by Iamgoofball** [comment]
not gonna lie, these sprites kinda aren't good
chrome_MlaDg83ItZ
the goon ones look way better

**Comment by sergeirocks100** [comment]
Two reasons, mostly.

First, it gives me some spriting practice.

Secondly, i wouldn't mind there being less nonfree, restrictive assets in the codebase.

**Comment by KathrinBailey** [comment]
Showcase sprites in-game, otherwise no one gets to see an actual representation of how they look.
Sprites in the editor can look better/worse than sprites in-game.

**Comment by Fikou** [comment]
you need 4 dirs for the vault computer

**Comment by KathrinBailey** [comment]
> you need 4 dirs for the vault computer

I'm sure it only ever had 1 dir but it'd certainly be nice to have all 4 so there's less computer facing a wall awkwardness.

**Comment by sergeirocks100** [comment]
Screenshots added.

**Comment by Ghilker** [comment]
fix the changelog

also i like the sprites but the solars one, they seems off

**Comment by interestingusernam3** [comment]
https://youtu.be/9sJUDx7iEJw

**Comment by sergeirocks100** [comment]
As it turns out, spring.ogg seems to be this public domain sound i found on freesound.org: 

https://freesound.org/people/BMacZero/sounds/94131/

I would probably be okay just putting the existing spring.ogg in the regular sounds folder, but i'm replacing it anyways, just to be safe.

**Comment by Qustinnus** [comment]
@Iamgoofball you know why, needing to have a goon folder is bad.

**Comment by Qustinnus** [comment]
I'm not a big fan of the firealarm @sergeirocks100 Do you mind if I send you an alternate version?

**Comment by sergeirocks100** [comment]
Go ahead.

**Comment by Iamgoofball** [comment]
:-1: on the sound, I will revert that if it gets merged.

It's too similar to actual IRL fire alarms, which can and will result in Alarm Fatigue. Read up on it here.
https://en.wikipedia.org/wiki/Alarm_fatigue

We've denied PRs that change the fire alarm sound to realistic ones for this reason before.

**Comment by Tlaltecuhtli** [comment]
i dont think its the case when triggered fire alarms are integral part of the station flora

**Comment by tralezab** [comment]
Hahahaahah goon folder AUDIT

**Comment by maxymax13** [comment]
vaporizing some of the codebase's license hell is good, these sprites are completely horrid though

**Comment by sergeirocks100** [comment]
I think i'm going to replace the pickled egg suspended from the ceiling with something from Baystation.

The punching bag sprites there are under a CC-BY-SA license, so i don't think there should be an issue if i use them.

Meanwhile, i'm going to see if i can make the solar sprites look a little better.

**Comment by interestingusernam3** [comment]
This fire alarm sound is terrible, please don't.

**Comment by Iamgoofball** [comment]
This new weed sprite is awful, dude. It doesn't look like weed at all.

Paging @MrStonedOne and @Twaticus as our weed and sprite experts respectively, check the icon diffs in the github checks.

**Comment by LemonInTheDark** [comment]
While it's nice to clean up our odd assets and such, we shouldn't make replacing them with anything our goal. If they're getting yeeted it should be because there's a better replacement we've cooked up

**Comment by FloranOtten** [comment]
The vault ones are amazing. The weed ones look like frogs, and the solars look downright terrible.

**Comment by Krysonism** [comment]
I actually have a weed sprite ready. For the actual leaf at least.

CannabisVs64

**Comment by sergeirocks100** [comment]
After some thinking, i think i would be better off if i made all these sprite changes separate PRs rather than trying to do them all in one go.

I'm still keeping the PR open, as there's not much of a point to closing a drafted PR.

**Comment by Iamgoofball** [comment]
If you're not doing anything with this PR, just close it so it's not on the tracker.

**Pull request closed without merging**
