### PR TITLE
Adds bone setter and bone gel to medical holodeck

### LINKED ISSUE #79591: No bone gel or bone setter in Holodeck medbay (on metastation)
Reporting client version: 514.1589

## Round ID:
218353

## Testmerges:
- [Adds a Chat Reliability Layer](https://www.github.com/tgstation/tgstation/pull/79479)

## Reproduction:

Within the holodeck's medbay, there is no bonesetter or bone gel (This is on meta station. I am unsure if this is the case on other stations). It's probably just outdated.

image

### PR DESCRIPTION
**Pull request by Hoolny**
## About The Pull Request
kJ42f4e
Adds two missing things to holodeck
Closes #79591
## Why It's Good For The Game
Medical Holodeck should have all the medical tools for medical stuff
## Changelog
:cl:
fix: fixes holodeck missing medical tools
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
power creep /s

**Comment by SethLafuente** [comment]
> power creep /s

Oh no what will the ever so power increasing medic do with their bone setter such a deadly weapon capable of setting bones

**Comment by deathrobotpunch** [comment]
> > power creep /s
> 
> Oh no what will the ever so power increasing medic do with their bone setter such a deadly weapon capable of setting bones

I think they were just making a joke, if they weren’t then that would be too brain damaging to understand.

**Comment by SethLafuente** [comment]
> > > power creep /s
> > 
> > 
> > Oh no what will the ever so power increasing medic do with their bone setter such a deadly weapon capable of setting bones
> 
> I think they were just making a joke, if they weren’t then that would be too brain damaging to understand.

Yes I'm also joking....;.

**Comment by DATA-xPUNGED** [comment]
> > power creep /s
> 
> Oh no what will the ever so power increasing medic do with their bone setter such a deadly weapon capable of setting bones

I can already see it... roundstart safety override to get those BONESETTERS

**Comment by Vincent983** [comment]
no... they're going  to powergame rush the BONE GEL to snort it like the paint-sniffin gasoline-huffers they are

**Pull request merged**
