### PR TITLE
adds plumbing to box

### PR DESCRIPTION
**Pull request by anconfuzedrock**
This just adds a plumbing room to box very similar to meta's, and of course makes old chemistry the 'apothecary' that should totally be called the pharmacy. 
image

## Why It's Good For The Game
Time-green probably woulda added this if they weren't exhausted, every map should have the new plumbing. I had to slip it into maint below medbay, but I don't see that as much an issue. A bit of traffic from chemists going through a strip of maint should add """conflict""" but that died long ago.

Here's hoping I didn't screw up the map merger.

## Changelog
:cl:
add: Boxstation has a large chemistry room in maintenance similarly to metastation, and the old chemistry was made into the apothecary.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
I'm cool with you changing it to 'pharmacy', if you think it's more appropriate.

**Comment by anconfuzedrock** [comment]
Thanks, but I don't mind it all that much.

**Comment by FloranOtten** [comment]
That's fuckin' massive

**Comment by actioninja** [comment]
ok

**Pull request merged**
