### PR TITLE
Expand number of pipe layers from 3 to 5

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
dasr

More layers for autism projects all around the station
Notice! not all devices are allowed to use the new layers, only those you see in the picture can be layered to layer 0 and 4.

## Why It's Good For The Game
More freedom to do weird setups (and supercomputers)

## Changelog
:cl:
tweak: unlocked atmos full layer potential (now 5 layers avaiable instead of 3, not all objects can use the additional layers)
/:cl:

### CODE REVIEW

**Comment by trerri** [comment]
I hope you make valves in layer 4 be all the way north and ones in layer 0 be all the way south and 1 to 3 be in between states, and make pumps on layers 1 and 3 all the way south, and ones in layers 0 and 4 all the way north thus leaving the middle one alone and allowing for no hitboxes to overlap weirdly. All this assumes the components going south to north.
You should also take the opportunity to make it impossible to put H/E pipes on layers that aren't 2

**Comment by san7890** [comment]
the atmos tech in me is both excited and also going OH GOD OH FUCK WHAT THE FUCK OH NO OH FUCK OHHHHHH OHHHHHHHHHHHHHHHHHHHHHHH

**Comment by LemonInTheDark** [comment]
Jesus ghil.

Nothing looks out of the ordinary, I kinda understand the layer limits, it'd be hard to fit some of these sprites in that space, tho it'd be nice if it's possible.

Code checks out, all that.

**Comment by Ghilker** [comment]
sadly there is a limit on the sprites (32x32 pixels) and  it can't be moved over a certain amount :/ so the biggest ones are locked and can't be used in the other 2 layers, i'll try to work it out as best as i can but can't promise much on that part

**Comment by LemonInTheDark** [comment]
Yeah I figured, looks really good aside from that, finally more pipe layers for ~~sane uses~~ engi memes

**Comment by Fikou** [comment]
these arent coded in anywhere, mappers cant use them without wonky varedits :/

**Comment by Ghilker** [comment]
i know, the aim of the PR is to add the layers and make them functional

**Comment by LemonInTheDark** [comment]
conflict city

**Comment by Ghilker** [comment]
it was inevitable

**Pull request merged**
