### PR TITLE
Positronic Alert Consoles

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Adds positronic alert consoles, a terminal that ghosts can interact with once every 30 seconds to play a 'ping' and inform the roboticists that there are ghosts waiting for positronic brains.
usage

On Tram station:
tram

Original code by jjpark-kb (Jake Park)

## Why It's Good For The Game

Waiting the entire round for positronic brains that are never printed because the roboticists are forgetful ain't fun.

## Changelog
:cl:
add: Positronic alert consoles have been installed in all robotics labs, allowing positronic personalities to alert the roboticists that they're waiting for positronic brains to be printed.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Might be wise to make it like a 5 minute cooldown

**Comment by tf-4** [comment]
Can see what maintainers think. 30 seconds may be a bit low, yeah.

**Comment by Gandalf2k15** [comment]
Imagine being a roboticist and hearing **ping** every 30 seconds

**Comment by InsaneRed** [comment]
perhaps make it so the roboticists can turn it off if it gets annoying otherwise i think 30 seocnds is good

**Comment by necromanceranne** [comment]
It isn't even information that can be acted upon until roboticists can actually make positronics. As neat as it is, it probably needs to be inactive until positronic are actually researched.

**Comment by CRITAWAKETS** [comment]
should be only available once positronics are researched and put you on a forced queue that you cant opt out of (aside from random ghost role spawning) to be the next posibrain on the z-level.

**Comment by MrDoomBringer** [comment]
>As neat as it is, it probably needs to be inactive until positronic are actually researched.

Often times positronics might not get researched in the first place - I feel like this isn't the right solution

**Comment by dragomagol** [comment]
Not sure if this should be the way to go about it, but I'm a fan of the concept

**Comment by MrDoomBringer** [comment]
> Maybe it could be built in to the fabricator?

👍 Having a UI element on mech fabs that shows "Positronic Entities available: 4" or something would be less annoying and more useful. Could scope-expand this to a ghost action button that toggles whether or not they want to be a posibrain

**Comment by Twaticus** [comment]
> > Maybe it could be built in to the fabricator?
> 
> 👍 Having a UI element on mech fabs that shows "Positronic Entities available: 4" or something would be less annoying and more useful. Could scope-expand this to a ghost action button that toggles whether or not they want to be a posibrain

THIS. we have limited space on walls already and its only going to get stricter. we really dont need another wall mount for this

**Comment by tf-4** [comment]
Fair points. Will have a look into it

**Comment by techno0** [comment]
this is really cool, make this real in some way.

**Comment by tf-4** [comment]
> 
> 
> this is really cool, make this real in some way.

I'll bring it back with the suggestions made, when I get around to it

**Comment by JJRcop** [comment]
Drones are back, may want to consider those too.

**Pull request closed without merging**
