### PR TITLE
Auto coiled test of MetaStation

### PR DESCRIPTION
**Pull request by Mothblocks**
Replaces all of the cable coil on MetaStation with an automatically generated path connecting every APC to each other, plus a smidgen of manually placed coil to connect the APCs, and throwing some coil items on solars cause I didn't wanna do it

Idea is that this will eventually be an automatic part that happens in between loading the map for the first time-ish, and so mappers don't have to do this manually. Mappers will still be able to manually place coil in places where they actually want it etc etc etc and there's a ton here that needs to be adjusted to not look hideous, but I want to see if the fundamental idea works before committing to this further and writing the required DM implementation for this (right now this is pregenerated from a Jupyter notebook)

Seems to work fine locally

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
The future is now

**Comment by optimumtact** [comment]
there's no code

**Comment by Mothblocks** [comment]
@MrMelbert Yeah the naive coiling places it in a lot of pretty hideous places, it dumps some stuff in the holodeck area as well. 

It's hotwired directly to the engine right now more or less, that part was manual after Lemon helped me out to figure out how it even works.

This is not the version that would in a million years get merged, I just want to see that the rough concept and generation can work in a real round with real power usage before putting in work into actually making it halfway decent

**Comment by Mothblocks** [comment]
[auto_coil_prototype.zip](https://github.com/tgstation/tgstation/files/10290869/auto_coil_prototype.zip)

Here's the code that made it but we're not shipping this obvi

**Comment by Mothblocks** [comment]
It woooorks

**Pull request closed without merging**
