### PR TITLE
multitooled energy sword now alternates (slowly) between colors

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request
title
wow this took literally a single line of copypasted code to make

## Why It's Good For The Game

immersion is broken with a single color rainbowsword

## Changelog
:cl:
imageadd: rainbow esword now alternates colors, exactly like kindle kick shoes
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
show us

**Comment by carlarctg** [comment]
https://cdn.discordapp.com/attachments/409428587406557195/613959673933987860/2019-08-22_01-56-20.gif

not sure if this'll like, fuck with performance or something. hope not

**Comment by wesoda25** [comment]
honestly doesnt even seem that much slower (havent seen the other in a while tho). Might wanna make it even slower

**Comment by carlarctg** [comment]
it's literally copypasted straight from kindle shoes, i havent slowed it down at all

i'll slow it down if you want though

**Comment by nemvar** [comment]
Code is nonsense.

**Comment by carlarctg** [comment]
> Code is nonsense. Doesn't do what it's supposed to. If you are gonna copy pasta, at least know what you are actually copying and why.

sad

i'll reopen it if i find out how to do it betterer

**Pull request closed without merging**
