### PR TITLE
Adds a preference to mute Centcom, alert level, and VOX sounds

### PR DESCRIPTION
**Pull request by Shadowlight213**
Should be helpful to admins running clients in the background as they can set it so they only hear ahelps.

### CODE REVIEW

**Comment by neersighted** [comment]
Yes thank you

**Comment by Cheridan** [comment]
One thing you have to consider is that these kinds of messages can impart useful information. This isn't a huge problem in the case of Centcom/Alert levels since they're accompanied by a text readout, but Vox is not. If a player turns off these alerts because they're annoyed by them then they could miss vital information, and suddenly they're confused as to why everyone's yelling about aliens or whatever.

**Comment by Bawhoppen** [comment]
@Cheridan Players can mute their game from windows anyways. Just give a warning prompt for it.

**Comment by Shadowlight213** [comment]
@Cheridan I'm not certain how many bitflag toggles I can make. I could add another toggle specific to VOX I guess.

**Comment by Dorsisdwarf** [comment]
@Cheridan Then that's on them for turning off announcement sounds, isn't it? That's like saying that the ability to turn off admin music could result in someone missing that there's an event running, so music should be mandatory

**Comment by duncathan** [comment]
I really don't think it's worth the effort to prevent these players from muting then ingame when they could always just mute the game entirely

**Pull request merged**
