### PR TITLE
Add new sprites to handheld Gene Sequencer and handheld plant scanner

### PR DESCRIPTION
**Pull request by EricZilla**
## About The Pull Request
Updated Gene Scanner and Plant Scanner to better fit updated health analyzer appearance

## Why It's Good For The Game
Fits design precedents already in game, and updates a pair of VERY old sprites

## Changelog
:cl:
imageadd: Added new Gene Sequence Analyzer Sprite
imageadd: Added new Hydroponics Analyzer Sprite
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
image
Becomes...
image
And
image
Bonus Hydro

**Comment by maxymax13** [comment]
do imageadd: instead of add: so that you don't get on the feature coder shit list by the bot
also rename your PR (click the name) before mothblocks yells at you

**Comment by Mothblocks** [comment]
its too late

**Comment by Mothblocks** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Review by EricZilla — COMMENTED** [review]
Sorry about that, very new to github, definitely wont make such a simple mistake again, I thought renaming my version of the code would make it show up as GeneScanner under requests

**Review by Mothblocks — APPROVED** [review]
Good on my end, needs Twaticus for art pass.

**Pull request merged**
