### PR TITLE
 Fun with cloning Frankensteins

### PR DESCRIPTION
**Pull request by Incoming5643**
It's now possible for a body with limbs taken from other races to be cloned as that race instead of their own. The more of their body is replaced with foreign limbs the more likely this is to happen.

Fixes a bug where limbs attached to new owners would turn into the same kind of limbs as the owners if dropped again.

Currently untested. Scope of pull may increase at some later point.

### CODE REVIEW

**Comment by kevinz000** [comment]
So does this mean I can change my species now

**Comment by Incoming5643** [comment]
It's a bit of a crapshoot but yes. If you say, ripped off all of a liches limbs and replaced your own with them you'd have a 2 out of 3 chance to be cloned as a skeleton.

Kind want to make it so you can just throw a bunch of spare parts in a cloner with a brain and see what you get. Again, pull is very much in danger of massive feature creep.

**Comment by Jazaen** [comment]
You can do that without this PR, just plop your brain into a dead non-human and clone, or even defib if they aren't dead for long.

**Comment by bgobandit** [comment]
lizard intensifies

**Comment by Incoming5643** [comment]
It's also, I may point out, the first non magical way to bring a plasmameme back to life, but it sure as hell isn't easy, and they'd sacrifice their race in the process

**Comment by PKPenguin321** [comment]
That's technically not true because you could build a cloner in an atmosphere of pure plasma and it would work

**Comment by ShadowDeath6** [comment]
what happens if they have a bunch of husk limbs

**Comment by Incoming5643** [comment]
Pull shuttered due to needing to do something I find both way too much work and performance wise not worth it at all (give every limb an independent and desyncable version of dna) for gimmick behavior that realistically will almost never come into play.

Here lies another 2 am idea.

**Pull request closed without merging**
