### PR TITLE
New Eldritch Blade Sprites (and some minor fixes)

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request
I do my usual thing and make blades.

Screenshot 2020-06-22 09 39 21
Screenshot 2020-06-22 09 39 35
Screenshot 2020-06-22 09 39 42
Screenshot 2020-06-22 09 39 48

They have inhands. Also, I gave some flavour text to their description and some other heretic items.

Also I fixed a sprite error on the infiltrator cases (I think).

A lot of these were with some inspiration from @Krysonism, who also provided a lot of help and feedback and alternatives.

## Why It's Good For The Game

The blades actually can serve as a really good indicator for what the heretic might possess in terms of powers. Heretics play radically differently depending on their power choices, so seeing a molten sword, or a flesh covered sword, or a rusty blade can be a big clue to what to expect.

## Changelog
:cl:
add: Added new heretic blade sprites! One for the Ashen Blade, Rusted Blade and Flesh Blade
add: The blades have some descriptions now.
fix: Fixed some infiltrator toolbox sprites (hopefully).
tweak: Some eldritch items have had their descriptions and text altered to be a bit more legible and flavourful.
/:cl:

### CODE REVIEW

**Comment by EdgeLordExe** [comment]
i approve merge asap

**Comment by Rohesie** [comment]
@Twaticus

**Comment by Iamgoofball** [comment]
looking lit af

**Comment by MrDoomBringer** [comment]
that flesh sickle is sick

**Comment by Doosteroni** [comment]
Damn son this shit is on point

**Comment by necromanceranne** [comment]
I suppose in that case someone could change that fake cult dagger in the wizard ship too it.

**Comment by Rohesie** [comment]
Code looks fine, it just needs art review.

**Comment by Fikou** [comment]
they look really cool, but i feel like the ash blade is a bit too halloween-y, maybe instead of blacks with oranges something like grays with marks of orange, yellow, red

**Review by Twaticus — CHANGES_REQUESTED** [review]
first off these look really awesome great job
but after playing with it in-game i think the inhand sprite placements covering the body is pretty awkward

tested some alternatives which could be used in 64x64_lefthand & 64x64_righthand
dreammaker_dNJXXC0rHo
it could definitely just be me feeling this way though so its only a requested change so i can get your opinion on it before it gets merged. if youd like to keep the current version instead thats fine by me and we can consider this approved :+1:

**Comment by nemvar** [comment]
I'm not really qualified to comment on the looks but the rust and flesh sickle look pretty thin. Can you add some basically transparent pixels in these areas if they aren't already there?
image
It will not really alter the looks but make the item *way* easier to click when it's on the floor.

**Comment by Krysonism** [comment]
> I'm not really qualified to comment on the looks but the rust and flesh sickle look pretty thin. 

I think Edge specifically wants thin blades, my version the rust blade was rejected for being too thick. 

eldritch_blade_rust-export

**Comment by ShizCalev** [comment]
Since these can be put in the suit slot on cult robes (/obj/item/clothing/suit/hooded/cultrobes/eldritch), would you mind making a worn icon for them too? ♥

(They go in `icons\mob\clothing\belt_mirror.dmi`)

**Comment by necromanceranne** [comment]
I made some changes as requested, and also gave them a belt slot icon for each one.

**Review by Twaticus — CHANGES_REQUESTED** [review]
64x64_righthand side  sprites are backwards. rest are good :+1: 
New Canvasdwqdqwd

**Comment by necromanceranne** [comment]
Hecc

**Review by Twaticus — APPROVED** [review]
:tada:

**Pull request merged**
