### PR TITLE
UI sounds try 2

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
completes https://github.com/orgs/tgstation/projects/19/views/1?pane=issue&itemId=84390831

https://github.com/user-attachments/assets/da9536df-71af-4222-b0df-0ae5bdee96a8

## Why It's Good For The Game
It sounds cool!
## Changelog
:cl: grungussuss
sound: The lobby menu now click sounds.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I don't think this should be a pref, just adds maintenance load for something exclusively boomers like me will care about

**Comment by Iamgoofball** [comment]
@LemonInTheDark there is literally no reason to not have more detailed volume sliders on stuff, it's a common request from players

**Comment by Jamarkus127** [comment]
@LemonInTheDark I like having sliders so instead of adjusting the volume of the entire game I can adjust to preference. It was nice when we added the volume slider for when admins play music, so why not start by adding more for sound effects, ambiance, etc. 

Obviously dont go crazy by adding sliders for each specific sound effect, but some basic groupings would be a great addition. Though id group all sound effects into that slider instead of just menu button sound effects.

**Comment by LemonInTheDark** [comment]
> @LemonInTheDark there is literally no reason to not have more detailed volume sliders on stuff, it's a common request from players

This isn't being added for detailed control it's the same as any other ui/ux change that comes with a reversion pref that exists just in case 1% of the population 20 years from now wants to turn the feature off. it never works well. At least to my mind.

> @LemonInTheDark I like having sliders so instead of adjusting the volume of the entire game I can adjust to preference. It was nice when we added the volume slider for when admins play music, so why not start by adding more for sound effects, ambiance, etc.
> 
> Obviously dont go crazy by adding sliders for each specific sound effect, but some basic groupings would be a great addition. Though id group all sound effects into that slider instead of just menu button sound effects.

I am not against sliders as a concept, I think having granular control is often more of a patch then a solution (IE: what if instead of making the sounds actually balanced we made players do it for us). Also I think it'd lead to weird gamey behavior if detailed enough. No problem with what you suggest here I don't think would need to see implementation.

**Review by Ghommie — CHANGES_REQUESTED** [review]
The sounds are cool, but I don't think we need a pref for it (also as Oranges said in another PR, we'll end up having to make sounds thir own main tab at this rate), since they're very tolerable, unlike those that I hear from downstreams' modularized menus.

**Comment by Sadboysuss** [comment]
Okay, I will change it when I have the time

**Comment by Iamgoofball** [comment]
> I think having granular control is often more of a patch then a solution (IE: what if instead of making the sounds actually balanced we made players do it for us)

This is bad logic; "actually balanced" is literally subjective because players have a wide range of audio setups and headphones. There literally is no "perfect" balancing, because one size expressly does not fit all for every player's audio setup. There is zero harm to letting players configure their soundscape when it's not mission-critical audio. Please see the rest of the professional industry regarding this and how often players critique not having granular audio control.

@Sadboysuss Request some weigh in from @Mothblocks and @ninjanomnom please, they understand UX.

**Review by grungussuss — COMMENTED** [review]
removed pref

**Comment by Iamgoofball** [comment]
I'll just re-add the preference in a follow-up if everyone wants to pretend the last 30 years of game development aren't real or something, sure, whatever. Even DOOM had some volume controls.

**Comment by Sadboysuss** [comment]
> I'll just re-add the preference in a follow-up if everyone wants to pretend the last 30 years of game development aren't real or something, sure, whatever. Even DOOM had some volume controls.

I'm not gonna argue with a potato on this, I just want my sound added and potato convinced me this will be better, if mothblocks or ninjanomnom want the pref then sure I'll revert the commit

**Comment by Ghommie** [comment]
CI issues.

**Pull request merged**
