### PR TITLE
Combat/Stun (slip) overhaul staging, mobility flags, adds crawling

### PR DESCRIPTION
**Pull request by silicons**
Aiming to implement the framework oranges has detailed in https://tgstation13.org/phpBB/viewtopic.php?f=10&t=19102
Moves canmove to a bitflag in a new variable called mobility_flags, that will allow finer grain control of what someone can do codewise, for example, letting them move but not stand up, or stand up but not move.

Adds Immobilize()d status effect that freezes movement but does not prevent anything else.
Adds Paralyze()d which is oldstun "You can't do anything at all and knock down).
Stun() will now prevent any item/UI usage and movement (which is similar to before).
Knockdown() will now only knockdown without preventing item usage/movement.
People knocked down will be able to crawl at softcrit-speeds
Refactors some /mob variables and procs to /mob/living.
update_canmove() refactored to update_mobility() and will handle mobility_flags instead of the removed canmove 

:cl:
rscadd: Crawling is now possible if you are down but not stunned. Obviously, you will be slower.
/:cl:

### CODE REVIEW

**Comment by XDTM** [comment]
Is there a total stun without the knockdown component? I'd like to keep the paralysis nanites fuctionality that keeps people frozen in place.

**Comment by kevinz000** [comment]
@XDTM as of right now yep, it'll be Stun().

**Comment by Kagus** [comment]
Right, so... One thing I was wondering about with this overhaul, was stuff like banana peels which have a slip strength based on plant potency.

In particular, 0 potency bananas are _pretty frickin' funny_, because their slip strength is so low that the person never actually falls down or is stunned in place. _However_, because "slipping" makes you drop your items, walking over a 0 potency banana (which is tiny and very difficult to see, I might add) will cause you to fling everything in your hands out in front of you like a fucking spaz while you just stand there, upright and unstunned after completely overreacting over some corridor compost.

I'm just worried that this change will bulldoze such important cultural landmarks as 0 potency banana peels... And also probably some other things that actually have gameplay importance, I'unno.

**Comment by Mickyan** [comment]
Resting should work the same as knockdown otherwise people will have to knock themselves down to crawl under things which is silly

**Comment by kevinz000** [comment]
@Mickyan anything that causes you to lie down will let you crawl if you're not unable to move.. this includes resting.

**Comment by ExcessiveUseOfCobblestone** [comment]
You have weird naming conventions, I would have thought paralyze did stun's effect and vice versa.

Go full MOBA and change stun to root

**Comment by Cyberboss** [comment]
^

I wouldn't be opposed to removing the word "stun" from code entirely

**Comment by XDTM** [comment]
Or freezw, although we do have freon freezing too

**Comment by Qustinnus** [comment]
maybe irrelevant but what will happen to spots you can now crawl under that you previously couldnt get to? (flaps in particular)

**Comment by XDTM** [comment]
Wallflaps as a barrier make no ic sense tbh

**Comment by Mickyan** [comment]
plastic flaps have been needing more consideration for where and how they're placed cause they're laughably easy to deconstruct nowadays and there's a few known ways to bypass them already

**Comment by Kagus** [comment]
In gooncode you could just lie down, hit "stand up" and then slide through the flaps while your ritual of getting back on your feet was being processed.

By comparison, TG flaps are airtight. Which still makes zero fucking sense, but fuck it.

**Comment by ExcessiveUseOfCobblestone** [comment]
A Majority of flaps are windoor guarded anyways.

If this was a balance issue then they should have been covered during the PR which made them (de)constructable.

**Comment by Borisvanmemes** [comment]
When i first saw the title of the PR i was thinking it was a meme, then i saw that kev made it, OH GOD.

**Comment by PKPenguin321** [comment]
still dont really see how this improves combat

**Comment by Notamaniac** [comment]
I mean ideally this paves the way for less "rocket tag" stun gameplay, where instead of a taser insta downing you, fights are more drawn out and let the other person potentially respond, so lucky mcgreyshirt who managed to slip a sec officer for their taser has to put more work to get their taser, and if they do get it won't be able to gg people with a set of cable cuffs.

Alternatively this never gets worked on or changes stuns and slips makes everyone angry and force it to be reverted, leaving stuns to be the king of the ss13 weapon food pyramid.

**Comment by Jordie0608** [comment]
Hmm something's not right here.
capture

**Comment by Cyberboss** [comment]
Time_to_stop.jpg

**Comment by Cyberboss** [comment]
When will he learn to stop force pushing?

**Comment by kevinz000** [comment]
### Refactors are done. I'd rather get this merged faster than try to fine tune stuff like slips. The most obvious gameplay effect this pr has will be crawling, and I believe I made tiny tweaks but I can't find it Anything I missed or weird behavior should be reported.

**Comment by optimumtact** [comment]
conflicted

**Pull request merged**
