### PR TITLE
Reverts #45316, re-adding assimilation, but leaves it out of rotation.

### PR DESCRIPTION
**Pull request by StonebayKyle**
This reverts commit 718973fb9f8ecad25e41f63e4c722cc300d4d2b3.

## About The Pull Request

This PR is a lazy revert of #45316 which SHOULD NOT be merged in its current state.

I would take the gamemode out of rotation myself if I knew how.
This PR will need revision from somebody that knows what they're doing in order to take assimilation out of rotation before this is merged.

## Why It's Good For The Game

Assimilation is a disliked gamemode that isn't being reworked, just removed recently due to that. However, doing a removal of every bit of code relating to the gamemode is a mistake.

Assimilation should be taken out of rotation, not totally removed. Make it function much like clockwork cult or devils, where the admins can still choose to activate the gamemode or make individual hiveminds.

If the assimilation gamemode was totally removed, as it just recently was, it takes away any possibility of ever trying the gamemode again, even if ooc and admins collectively vote for it (like they occasionally do for clockwork). This will also allow a chance for a rework to happen in the distant future, if somebody is crazy enough to attempt that.

## Changelog
:cl:
add: Re-adds assimilation (hivemind) gamemode
del: Takes assimilation out of rotation, putting it in a similar position to the clockwork cult.
/:cl:

### CODE REVIEW

**Comment by AarontheIdiot** [comment]
why would anyone want to try this garbage again

**Comment by StonebayKyle** [comment]
I don't know, but you could say the same for Devils. And even that was left in code.

**Comment by actioninja** [comment]
I think there should be more of an initiative to gut out unused stuff instead of just leaving it in and adding yet more maintainability overhead just because maybe potentially someone might want to fix it possibly at some point in the future.

There's a lot of big refactors that have been made harder than they need to be by that a shitload of dead content needs to be updated and maintained at the same time as all the stuff that is actually used.

**Comment by optimumtact** [comment]
I have zero interest in carrying this gamemode on the supposed chance someone is working on it.

Let alone im firmly convinced we already have gamemodes.

**Pull request closed without merging**
