### PR TITLE
Fixed changeling augmented eyesight ability

### LINKED ISSUE #24086: changeling vision (augmented eyesight) is actually x-ray, cannot be turned off
It says on the wiki it's meant to be heat+dark, but it's straight up x-ray, combine with mesons for easy mode. 
Even if that were intended, it cannot be turned off.

### PR DESCRIPTION
**Pull request by msgerbs**
:cl: VexingRaven
fix: Changeling Augmented Eyesight ability now grants flash protection when toggled off
fix: Changeling Augmented Eyesight ability can now be toggled properly
fix: Changeling Augmented Eyesight ability is properly removed when readapting
/:cl:

Fixes #24086.

Note that I decided not to remove the x-ray part since it's been like this for so long it seems more like a balance change than a bugfix if I change that now. For whatever reason, it was underflowing the sight variable before, causing it to set sight to something like 65531 or something and granting x-ray vision. I'm unsure why, but my changes made it no longer underflow so I had to set the proper flags to make it x-ray again.

I'm willing to make it actually work as thermals though if maintainers think that would be better. (since that's what the ability was intended to be).

Also if anyone could help out, I'm not sure that I am using the right operator to unset the bitflags. I couldn't get it working any other way, but using XOR doesn't feel right for this case.

### CODE REVIEW

**Comment by BeeSting12** [comment]
I'd rather see it just be thermals, but that's just my opinion for the two cents it's worth. Changelings have been buffed enough already.

**Comment by msgerbs** [comment]
I can see your point but this isn't really a buff, this is the way it has been working since it was added as far as I know.

**Comment by BeeSting12** [comment]
I remember it was working as thermals and that seemed pretty fair to me. Somehow a bug made it into x-ray and I haven't used them since those few times that I experienced it when it was bugged. You'd be fixing a bug by making it into thermal vision. Plus changelings don't need more buffs.

**Comment by msgerbs** [comment]
Alright, well I'll wait for a maintainer to weigh in and if they agree it should be thermals then I can fix that too.

**Comment by kevinz000** [comment]
Uh can you make it so you can toggle either or turn them off completely? Because if you make it either/or it will be a meta test for lings who have it because if you flash someone without glasses you will know if they have the thermals or the flash on based on how they react.

**Comment by FantasticFwoosh** [comment]
- important to note: flashing lings are a easy way to incapacitate them, so yeah kevinz is relevant for the check but essentially you've given them a HUGE buff

No "I ded" changeling powercreeps please, flash vulnerability is a reliable way to fight against changelings because it relies you to put yourself in danger up close, or support a colleague in dunking a changeling by keeping it down even with adrenals.

- Does this also block pepperspray? Because its a huge nerf for officers vs lings

**Comment by msgerbs** [comment]
Alright fine, I'll make it actually work as thermals. As for the flash protection, you can't call that an "I ded" because that's how the ability was always intended to work. The description even says that. I'm not sure what you mean about flashes keeping lings down though, are flashes not affected by adrenals?

**Review by Cyberboss — COMMENTED** [review]
.

**Comment by BeeSting12** [comment]
Yeah, the original point was flash protection when toggled off and thermals when toggled on @FantasticFwoosh 
It would be a meta tell either way yeah, but that's what we call a "trade off"

**Comment by XDTM** [comment]
Fwoosh thermal is full nightvision and aug eyesight it IS meant to protect from flashes when off do you even know what you're talking about

**Comment by KorPhaeron** [comment]
Thanks

**Comment by msgerbs** [comment]
Oh, OK. I was going to fix it to actually be thermal instead. Maybe I should make an issue on that for discussion then make a new PR if people still want that corrected?

**Comment by KorPhaeron** [comment]
You don't need an issue open to propose a balance change

**Comment by msgerbs** [comment]
Forgive my newbness, how do I correctly go about that then? Just open a new PR with the change and let people debate there?

**Comment by KorPhaeron** [comment]
Basically yeah

**Comment by KorPhaeron** [comment]
I don't think the change is really needed though, you're correct that this has basically just become the default over the last 6 months and it hasn't been a big deal

**Pull request merged**
