### PR TITLE
Paper bins show the paper inside them

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request
Currently, paper bins have an icon that shows a written on piece of paper on top. This PR gives paper bins an icon that reflects their contents instead.

## Why It's Good For The Game

I dunno, it's just bugged me forever. I think other people will like it.

## Changelog
:cl: cacogen
qol: Paper bins show the paper inside them
add: Crafting recipes for improvised paper bundle, natural paper bundle and paper bin
qol: Many small improvements to paper bins (PR #57412 for details, boring)
/:cl:

<details>
<summary>Click to expand</summary>

### Bin overlays
- Adds 30 sheets to the paper bin when it spawns instead of producing new paper as needed (originally preserved this for performance but changed it after noticing cases where lower paper visually isn't there)
- Adds an overlay for each sheet of paper, including its overlays and colour (I don't know if this is going be ruinous performance wise or not matter at all)
- Paper overlays shift pixel every 8 sheets to give an impression of the stack increasing or decreasing
  - [x] Would like to figure out how to make it go on until overlay cap instead of artificially limiting it
    - Recalled child maths to make pixel shifting continue to overlay cap
- Adds a paper_bin_overlay var for paper bins, which is an icon adapted from the original sprite that goes over the paper overlay
- Any interaction involving physical contact (i.e. MouseDrop, attackby, attack_hand) checks if the bin has exceeded the overlay limit. If it has, the stack collapses to avoid the overlays being cut

### Paper bins
- Added ability to dump bins by using them in-hand (each object in contents makes it take 0.33 seconds longer)
- Removed extra space in bin examine() and it telling you when they're empty (obvious)
- Added messages to examine() that explain how to pick up paper bins and how to empty them
- Added metal sheetcrafting recipe for paper bins (2 metal)
- Added message if you click and drag it to a turf explaining to use it in-hand to dump it

### Code
- Uses LAZYLEN(papers) instead of total_sheets var
- Changes total_sheets var to starting_sheets (updates a couple of maps) for use when generating initial sheets
- Renames icon_states this PR touches to be immediately understandable
- Adds generate_paper() proc to bins that they use to create their paper
- Implements dump_contents() proc for bins
  - [x] Want to make it so you can dump these out by hand
  - [x] ~~Would like to see natural paper bundles retain their shape rather than spilling everywhere (pixel_x and pixel_y same as overlay)~~ Turns out object stacking order is dictated by some arcane magic I don't want to learn

### Natural paper bundle
- Adds wirecutter_act() to natural paper bundles to deconstruct them
- Makes natural paper bundles drop 2 brown cables when deconstructed
- Adds crafting recipe for natural paper bundle (30 natural paper, 2 cable), and an improvised paper bundle (1 paper, 2 cable)
  - [x] Need to figure out how to preserve paper used (parts var?)
- Names natural paper so it's referred to specifically in the crafting menu
- ~~Adds a jumbo paper bundle (1000 paper) that can be spawned by admins for joie de vivre (this collapses immediately if interacted with)~~ nope it could and usually would collapse into 1000 sheets which freezes your client for ages when you open the context menu over it
- Makes it so you can't put carbon paper into paper bundles, as it's wider than the overlay (could've added a wider overlay and switched to it when necessary but I could not be bothered)
- Adds a hint to the examine saying the cable holding it together can be cut (didn't know until I worked on this)
- Makes the overlay greyscale and copy the colour of the cable used to create it

</details>

### CODE REVIEW

**Comment by maxymax13** [comment]
YES

**Comment by maxymax13** [comment]
what if the y offset of the paper overlay slowly went down as more paper is taken from it?

**Comment by cacogen** [comment]
Yeah, that would look good and wouldn't be too hard I don't think. I could just use a switch statement and pick a different offset based on the number of pieces of paper.

**Comment by cacogen** [comment]
@maxymax13 

It's in. Natural paper bundles now decrease in size as they're used too.

**Comment by maxymax13** [comment]
what if natural paper bundles regressed to a cable coil or something when you take out the last paper so you could make new ones, also gives them a non-aesthetic reason to exist

**Comment by cacogen** [comment]
Okay, when you cut or snip a natural paper bundle it'll drop a brown power cable now. There's also crafting recipes for an improvised paper bundle (1 paper, 2 cable) and the natural paper bundle (30 natural paper, 2 cable). You can use the former to organise paper and the latter to quickly clean up bundles after they're snipped.

**Review by Twaticus — APPROVED** [review]

**Comment by maxymax13** [comment]
it would appear that paper bins are unobtainable apart from ones already on the map/shuttle and the TWO in a whole cargo crate. how does 2 iron sheets to craft into an empty bin sounds? then both types of paper container can be craftable.

**Comment by cacogen** [comment]
@maxymax13 
Okay, I added a simple sheet crafting recipe using two pieces of metal to make an empty bin.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Conflicts again

**Comment by cacogen** [comment]
I'm surprised you don't have any changes requested. I've thought about how to do a few things better since I last worked on this but I don't know when I'll get around to doing that. I've tested it extensively though and I'll be quick to fix any bugs that I might've overlooked.

I just need to test the new mousedrop component.

**Comment by cacogen** [comment]
Okay, I resolved the conflict and code overlap with the new drag_pickup component. I tested it, it works as expected.

**Comment by cacogen** [comment]
I wish you could bribe maintainers with GBP to review your pull requests

**Comment by maxymax13** [comment]
will you ever make that pr that ports the natural paper stack functionality from this 😭

**Comment by cacogen** [comment]
I have thought about it many times since telling you I would do it and I have no idea. Do you just mean crafting paper bundles?

**Pull request closed without merging**
