### PR TITLE
Adds mineral storage access to all jobs intended to be using a technology fabricator[read: 80% of the jobs]

### PR DESCRIPTION
**Pull request by silicons**
likely to be removed when distribution is put in, or the ORM gets moved inside when distribution is put in, but this is one of the chief complaints.

### CODE REVIEW

**Comment by newfren** [comment]
Is this every job on station except assistant

**Comment by kevinz000** [comment]
anyone in a department or a subdepartment

**Comment by Ratvar** [comment]
kevinz000 changed the title from Adds mineral storage access to all jobs intended to be using a technology fabricator to Adds mineral storage access to all  just now

**Comment by AlexTheSysop42** [comment]
Can mineral storeroom access be added via ID console?

**Comment by kevinz000** [comment]
tyes

**Comment by ExcessiveUseOfCobblestone** [comment]
He who presses the release all controls the universe

**Comment by Repukan** [comment]
or they could just, you know, ask cargo?

Or ask the HoP for extra access?

**Comment by Repukan** [comment]
Hey let's complain about validhunt behavior and then remove interactions and conflict from the crew!

**Comment by ExcessiveUseOfCobblestone** [comment]
Would be fair if that was true across the board and not just everyone but science/miners.

**Comment by kevinz000** [comment]
@Repukan all or nothing, what cobby said.

**Comment by Cyberboss** [comment]
I'm gonna push my self to do mineral distribution on Saturday. Hold off until I do

**Comment by Cyberboss** [comment]
It's gonna take at least a week to write, so push this through if you must

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss remove the tag

**Pull request merged**
