### PR TITLE
Makes some use of `CONDUCT_1` in grille and door attackby.

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Airlock attackby now uses `CONDUCT_1` to check if the mob should be shocked on attack
- Grille attackby now uses `CONDUCT_1` to check if the mob should be shocked on attack
- You don't leave a fingerprint on grilles you attack (?)
- Fire axe is now conductive (it's made of steel?)

## Why It's Good For The Game

- Consistency is nice.
   - If you have an item you don't expect to shock you, it shouldn't randomly zap you anyways.
   - Grilles are especially bad for this: It hard checked _glass shards_ when attacking, and _glass shards_ only. That's lame and nonsensical. All non-conductive weapons should resist a spark. 

## Changelog

:cl: Melbert
balance: Attacking a shocked door with an item that isn't conductive will not shock you.
balance: Attacking a shocked grille with any item that isn't conductive (not just glass shards) will not shock you.
balance: Attacking grilles with items no longer leaves behind a fingerprint on the grille (?).
balance: Fire axe is now conductive.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
maintainers add this

**Comment by private-tristan** [comment]
what objects are conductive? is it just metal items?

**Comment by TheBoondock** [comment]
Oh so prisoner could just cut shocked grille with a glass shards this whole time...

**Comment by MTandi** [comment]
@MrMelbert this doesn't make sense for the fire axe, since it has a wooden handle, despite your picture. We need to either update the sprite, or make the items with wooden handle non-conductive (this also includes pickaxe). @Livrah suggested that fire axe is quite important against malf AI, and this is a serious buff of AI tools.

**Comment by optimumtact** [comment]
> @MrMelbert this doesn't make sense for the fire axe, since it has a wooden handle, despite your picture. We need to either update the sprite, or make the items with wooden handle non-conductive (this also includes pickaxe). @Livrah suggested that fire axe is quite important against malf AI, and this is a serious buff of AI tools.

or we could just not care what livrah thinks

**Pull request merged**
