### PR TITLE
Removes Hulk from the game.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Replaces it with Laser Eyes, a mutation that doesn't destroy the game's balance.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
whoever thought infinite easily handed out stun immunity was good for the game is dumb

**Comment by Iamgoofball** [comment]
@KorPhaeron requesting test merge for a few weeks

**Comment by WJohn** [comment]
Doesn't laser eyes just let you shoot lasers indefinitely? And it's ranged. It's equally horrifically destructive. And you can't even see it. And how is this better exactly?????

**Comment by Iamgoofball** [comment]
That's ten times less bullshit than stun immunity and you know it.

**Comment by jughu** [comment]
@WJohn laser eyes decreases your hunger

**Comment by Cyberboss** [comment]
Oh boy this again

**Comment by Iamgoofball** [comment]
https://file.house/AU8g.png

did you need to do this

**Comment by praisenarsie** [comment]
no changelog

**Comment by XDTM** [comment]
👍 for removing hulk
👎 for replacing it with something worse

**Comment by WJohn** [comment]
I mean don't get me wrong, stun immunity and wall smashing is utter garbage too, but this really isn't any better in sheer destructive potential.

**Comment by Iamgoofball** [comment]
@WJohn You're an idiot if you think a laser gun is worse than fucking stun immunity, the centerpiece of our combat system.

**Comment by TheDreamweaver** [comment]
Goof, based on past conversations, I think you might have a definitions problem, in this case what balance means. What I think you need to work on, is this idea that outright removing things that seem to be unbalanced or things that seem to not work towards balance does mean you are making the better. I think this is a really good example, because as we can see in this example you clearly are frustrated at the current state of hulk and the power it gives others and the ease at which the power is received, but you acknowledge that just simply removing it would leave players discontent, so you vouch to replace it with a power that, coincidentally, is equally if not more powerful. What I believe to be the problem. and I've seen this in other situation which you bring up, is that a lot of times you have some valid complaints or realize something that has a significant degree of trueness to it, but then use this to justify handling the situation in an extreme or otherwise unneeded way that while possibly justifiable, doesn't actually solve the problem you brought up, or at least not without creating new problems. How to solve this? Not sure, and I think it depends on the situation. Maybe in this case, instead of out right removing things, create a more interesting and challenging approach to obtaining more powerful powers. This would not only solve the problem, but also create benefits that didn't previously exist, in this case by providing an additional challenge fro a job that's usually over in 10-15 minutes and adding new cool things to achieve for (in this case hulk and the previously unobtainable powers) which now adds new life to an aspect of the game that has been steadily growing mundane. Just an idea and something to think about.

In the end it comes down to the mindset of remembering that while pruning a tree can help its growth, if you keep chopping it up with out fertilizing it a bit as you go along, soon enough you be left without a real tree.

**Comment by Bawhoppen** [comment]
@TheDreamweaver Don't become Robustin

**Comment by TheDreamweaver** [comment]
@Bawhoppen Whats that mean

**Comment by Iamgoofball** [comment]
1. time gating hulk doesn't make it less OP
2. our entire combat system is based around stuns, with stun resistance having insane drawbacks otherwise

it's no wonder players want to keep OP shit

the "don't remove it just tweak how you get to it :)" method is a shit ideology that resulted in our current broken R&D setup

**Comment by Durkel** [comment]
Laser eyes is far worse now that hulk doesn't have stun hands anymore. That and genetics just needs a revamp to solve the issue of getting all powers with no down sides ten minutes in and then handing them out like candy.

**Comment by WJohn** [comment]
I'd be more in favor of having neither of these, to be honest.

**Comment by TheDreamweaver** [comment]
@Iamgoofball Would you not agree that there is currently loot in the game that is more powerful than a hulk, and yet those are simply gated too. I never said it had to be a time gate, or what the gate had to even be for that matter. Again this brings me to what I explained, which is solely removing things doesn't necessarily solve the problem that you're after, and only delays the inevitable. Theres always going to be something that has *relative* problems, at what point do you decide to tweak things instead of chopping down the whole tree.

**Comment by Bawhoppen** [comment]
@TheDreamweaver What that means, is to not write walls of text like Robustin does with every post.

**Comment by TheDreamweaver** [comment]
@Bawhoppen Sorry, didn't mean to be lengthy. I usually don't write much on git, but this was something I've seen happen consistently, so I figure I'd give my whole two cents, git it off my chest, and then be done with it. My apologies.

**Comment by Iamgoofball** [comment]
@TheDreamweaver Just because something else did it doesn't mean it was a good idea.

@Durkel Come on, you know that shit isn't worse than stun immunity. It's not even an infinite laser gun, it uses your hunger up which slows you down fast.

**Comment by TheDreamweaver** [comment]
@Iamgoofball And that's exactly my point. Where do we exactly draw the line? Do we remove everything that gives someone a significant advantage, even if they put in time or effort/robustness to obtain it? It's clearly not a black or white answer, as I'm sure you'll agree. Otherwise, we are eventually left with a stump of what we call a game. You got to feed it here and there and let it grow before pruning it, otherwise there's nothing left.

**Comment by TheDreamweaver** [comment]
And again, I hope you understand that I acknowledge the problems and concerns you're bringing up, and agree with them in a lot of aspects. It's just that I think we have to be careful about how we go about approaching them, otherwise we created a whole different set of problems.

**Comment by Noahnoah55** [comment]
@TheDreamweaver It was never hard to get hulk. Genetics is easy.

**Comment by TheDreamweaver** [comment]
@noahnoah55 Never said it's current state was. Read all my comments so far to understand what I'm saying.

**Comment by ChangelingRain** [comment]
Laser eye damage should scale with nutrition, not just drain it.

**Comment by PopNotes** [comment]
Here's an alternative: make hulk explode off all of your clothing and cause your backpack to rip open, changing your sprite into that super swole one people have been passing around the past few days

**Comment by Iamgoofball** [comment]
why would i rework an entire system just to deal with one problem mutation?

**Comment by TheDreamweaver** [comment]
Because as I've tried to point out to you multiple times now, if you define and handle problems the way you do continuously without re-nurturing the game a bit as you go along, you eventually release you aren't left with much, but by then it will be too late.

**Comment by PopNotes** [comment]
because it would be easy and funny

**Comment by Iamgoofball** [comment]
or instead we do chemo before people use this garbage as justification for other broken shit

**Comment by Dorsisdwarf** [comment]
good idea. we'll use that reasoning to pre-emptively deny the stupid forced memes you add into the game for shits while high too.

**Comment by jughu** [comment]
Make hulks get hungrier each  time they smash

**Comment by Dorsisdwarf** [comment]
Also hulk is a pretty old-ass feature and you're arguing like its this new thing you're rushing to nerf before it gets abused

**Comment by TheDreamweaver** [comment]
I'm done trying to explain it further. It seems you're pretty set in your ways of handling things in a "destroy everything that seems bad, but worry about the consequences later" and either refuse to acknowledge the consequences that come with continuously asking decisions this way, or just don't care. Only you can make that decision, and you have the right to decide either way, but just don't be surprised when people get tired of it and stop giving you an explanation for as to why they vote no on all your proposed changes.

**Comment by ChangelingRain** [comment]
I mean, you're still arguing like hulk isn't bad (`destroy everything that seems bad` like we don't know for a fact that hulk is a pile of crap as is)

**Comment by TheDreamweaver** [comment]
It would seem that you didn't read any of what I initially wrote, so I'll consider my previous comments a response to that, especially the initial one.

**Comment by jughu** [comment]
Just make hulks gain hunger for smashin shit

**Comment by TheDreamweaver** [comment]
In case it wasn't clear then, even though Id rather not spam this page by repeating myself, I acknowledged that hulk was not good for the game in its current state, both to due with the power given combined with the ease at which you get it. So again, not dismissing the problem, only criticizing Goof's method of dealing with said problems.

**Comment by sawrge** [comment]
Not reading this entire thread but this is a good pr

**Comment by Robustin** [comment]
Hulks have been nerfed to the point the only exist to stop the 2 worst things about SS13 combat: Stun spam and Wall spam. 

Hulks getting fresh attention because some people seem to think that it would be better to force people to decon walls for 10 minutes than have hulks smashing them up.

Theyre fine, I would much rather live in a world with hulks over a world where slip spam is an unbeatable defense.

**Comment by Iamgoofball** [comment]
I don't mind walls. This is about the stun immunity. Make

**Comment by Iamgoofball** [comment]
Wait are slips really the only problem

**Comment by TheDreamweaver** [comment]
"It's not my problem! But here's my problem..."
-Iamgoofball

**Comment by Supermichael777** [comment]
Dream all that more powerful than hulk time and skill gated loot is still shit because it IS time and skill gated guaranteeing the best items will be in the hands of someone very good at the game who then uses it to validate every antag solo or murdering the whole stations with area death storms and free lava.

Its just "rewards" for a very difficult bits of optional content instead of a job goal. Players are okay with it because, while it is massively disruptive, it is also very limited, tending to have little resistance to one solid taser hit or lucky assistant disarm. 

Hulk makes you immune to stuns, all escalation you have becomes lethal by default and you become immune to all but the most arcane stuns (sleep is about the only one hulks are vulnerable to and morphine is quite rare).  It can be swiftly and selectively handed out, can't be taken away without killing or acquiring chems, cant be used against you without getting it voluntarily form you, and as a cherry on top can be sabotaged to remove future access.  Its better than antag stun removals and immunity, the only one that comes close is lings and they are TIME limited on stun immunity. Hulks are immune, you just cant balance around 4 powers rolled into one

My solution is to just ditch the stun immunity and just give then smash.

**Comment by KorPhaeron** [comment]
It isn't just wall spam that hulks counteract though, it is any form of static defense or base in the game that gets ruined by the swarm of angry green assistants just walking in

**Comment by TheDreamweaver** [comment]
@Supermichael777 It's beginning to get real frustrating how you and most everyone else in this thread ignored my point. I agree that hulk in it's current state presents problems, what I did critique however (and what it seems that everyone responding to me is ignoring for whatever reason) is that the proposed solution of just aimlessly removing something that we deem to be unbalanced or pointless (as seen in the case of some of Goof's other pr's) doesn't solve the problem in the big picture and only creates other dilemmas in the long run. I'm not going to restate what these problems are, but I encourage you to go back and read my previous explanation in greater detail.

**Comment by TheDreamweaver** [comment]
Also, while still acknowledging that hulk is a problem, it seems that the real problem with hulk is when it gets put int the hands of the greytide, just like with anything else. There's a reason armory is locked up, and its not the syndis. While not saying a higher or more complex gate would fix the problem, it would at least fix *that* problem. Or maybe just make a handing out super powers to just anyone come with the same consequences if someone were to choose to hand out armory to anyone.

**Comment by Robustin** [comment]
@KorPhaeron 

Its pretty much the opposite of what you said, the moment "static defense" means something more than "slips and dense turf spam", i.e. shit that does damage, hulks become incredibly mediocre. 

Also besides the new CC which is almost certainly what prompted this latest kneejerk, what mode every involves a swarm of angry green assistants? Even in rev I haven't seen hulk swarms since AI learned how to sabotage it (and we made the injectors pretty useless) and hulks lost their stun hands.

Literally the only thing I've seen hulks do really well in the past few weeks is smash through CC wallspam. Once they break through either they are the first to fall to guardian constructs and ocular wardens... for a roughly equal amount of work meanwhile RND is churning out infinity ammo eguns that are far more useless en masse than hulks could ever hope to be.

**Comment by TechnoAlchemisto** [comment]
Robustin your argument has multiple logical fallacies, you call yourself a lawyer?

**Comment by Stealthkibbler** [comment]
@TechnoAlchemisto A lawyers job is to out-bullshit the opposing lawyer/prosecutor into submission using loopholes and outdated rules anyway. He does a good job of embodying that mentality.

I thought it initially appealing with idea of removing hulk but as Khor pointed out, it is one of the main ways of dealing with wall spam and obliterating reinforced bases that are otherwise impenetrable outside of chemical bombs or toxins. I liked Joans idea of nutrition affecting laser eyes and thought what if you lose Nutrition from smashing as Hulk? If you lose too much nutrition maybe your swole muscles atrophy to the point you have to chow down on more food than normal or you just straight up lose Hulk if you allow your nutrition to reach starving point.

**Comment by TheDreamweaver** [comment]
@stealthkibbler Wow finnaly someone with the capacity to think instead of just flailing about and screeching autisticly "muh balance" like everyone else in this thread

**Comment by Iamgoofball** [comment]
There's no such thing as outdated rules in law

**Comment by JohnMcLaime** [comment]
Reminder that hulks cant slip on lube either.

**Comment by Robustin** [comment]
My point still stands, the more "OP" that hulks feel, the stronger the sign that the mode's tactics need to evolve beyond wallspam and stunspam. 

Its endemic in this game but maybe, just maybe, we should focus more on diversifying defensive tools instead of throwing a shitfit everytime a hulk sprints over your slip traps, punches through your table spam, and slaps your unarmed ass to the ground because you thought obnoxious interior design was all you needed to win on defense in this game.

**Comment by evsey9** [comment]
Hulk is either used for:
A. Greytide/grief that is WAY worse because a department head CAN NOT deal with it using a telebaton - 75% of the cases
B. Cheesing antag bases - 25% of the cases.
Please remove hulk, it makes the life of a department head when genetics is giving out powers like candy HELL.

**Comment by KorPhaeron** [comment]
I would have thought robustin would be more sympathetic to complaints about hulk considering that unstunnable guys who can both see and smash through walls wandering around is a large part of what makes on station cult bases impossible

**Comment by Doppeltongue** [comment]
I'm not sure if this matters, but right now it seems like nobody really wants to do genetics on Bagil, since it's the only medbay role I see completely empty regularly on roundstart. I actually almost never see hulk at all now.

**Comment by PKPenguin321** [comment]
hahaha cant wait to hand out laser eyes to everybody

**Comment by TheDreamweaver** [comment]
@Doppeltongue That's because in it's current state, it's one of the most deceivingly boring jobs there is. Youre promised that your hard work pays off with these incredible powers, and that's not wrong, but it fails to give you the whole context of the situation. You spend a good 15 minutes clicking mindlessly at a console, slowly irradiating yourself, telling others to stop breaking your windows for to steal powers, reassuring the CMO you'll take care of those bodies piling up in cloning, waiting for RNG to finnaly give you rest, and then when you finnaly find it all, you irradiate yourself some more until all your new powers are all locked into your bodies DNA. This is it! All the power is yours, you've finnaly become the hero you were meant to be! Right? Wrong, because while the powers do seem fairly neat in it of themselves, you soon realize that without a clear antag at your reach, you're new found powers are useless (beside being a shitler, which should always be handled on the admin end, and not the coders, for obvious reasons), and if you do happen to stumble upon a situation where you might be of use, it's usually already set in motion towards whatever is going to happen anyways. Hulks definitely do present a problem in certain cases, but as always, Goof always refuses to look at the big picture, and will leave a dying system to die, because his problems are always more important than the rest.

**Comment by Anonymous583** [comment]
Good fucking PR, hulks are a cancer

**Comment by Firecage** [comment]
Eh, I would honestly have preferred splitting Hulk into two super powers.

**Comment by Qbopper** [comment]
>mfw I don't like hulks but it's a goof pr

fug

**Comment by Qustinnus** [comment]
good pr. merge this. hulks are shit and everyone knows it. and @TheDreamweaver all this "relative problem solving" crap is dumb. you can't make an absolute solution without re-working fucking everything so we can only do relative problem solving.

**Comment by Robustin** [comment]
I dont think any more hulk nerfs are necessary when you can kill them with improvised weaponry (spear+bola) but if there's one decent suggestion I've heard its that punches should drain nutrition so that you have to make an effort to stay fed or else you'll end up slow and slow hulks end up dead.

**Comment by TheDreamweaver** [comment]
@Qustinnus I'm sorry but that's bullshit. We should absolutely be looking at the bigger picture and seeing how a certain pr would affect the game in total, not just on the individual problem that the OP brings up. No where once did I say or imply a extensive game revision, and you know as well as I do that hardly any problems would require that. That doesn't mean however we shouldn't try to get to the root of the problem instead of making these quick and reactive changes that don't actually solve the problem, and possibly create new ones. I hate to say this, but for once Robustin is being more rational then half of you.

**Comment by TheDreamweaver** [comment]
Does this necessarily mean hulks should never be removed or should always stay in their current state? No, but I think we need to be weary about just giving in to another reactive good price just because we think it sound good in the moment, without actually first fixing the base problem.

**Comment by Qustinnus** [comment]
@TheDreamweaver how is this a "reactive change". we've seen hulk is shit for ages, we have reason to boot it.

also you're just as delusional as Robustin.

**Comment by TheDreamweaver** [comment]
Did you not read what I said? Is no one reading what I said? Where did I once say that Hulk didn't need a change? The "reactive" part is *how* it's being handled.

**Comment by Qustinnus** [comment]
it's shit and should be removed. its that simple.

**Comment by Qustinnus** [comment]
if you have a better solution go code it.

**Comment by TheDreamweaver** [comment]
Okay, brb as I remove everything else in this game that has ever presented a problem.

**Comment by TheDreamweaver** [comment]
I mean who cares what effect it has, right?

**Comment by Qustinnus** [comment]
you could remove your github account that would probably improve this codebase

**Comment by TheDreamweaver** [comment]
Well, I guess this is no longer a constructive conversation about improving the game (didn't really think it was to begin with to be honest). I'll leave you guys to make whatever decisions you want. It's become clear critiqued conversation isn't welcome here.

**Comment by duncathan** [comment]
I don't think hulks have ever been very fun really

**Comment by KorPhaeron** [comment]
I agree, I'm just not sure if laser eyes is the way to replace it

Really until genetics is changed or replaced we'll have the problem of any halfway decent power being given to everyone for free once you're done rolling the dice alone at your computer

Maybe making the scanner powers revert after a short time and the injectors give the permanent powers and the injectors cost uranium or something

**Comment by TechnoAlchemisto** [comment]
^ This, good take Kor!

**Comment by TheDreamweaver** [comment]
@KorPhaeron That's not a bad idea. I agree that Genetics needs some refactoring both to make it interesting again and to balance out the power it gives you.

**Comment by Militaires** [comment]
just port goongenetics dumbos, literally fixes all of the genetics issue + adds depth

**Comment by YakumoChen** [comment]
the wall smashing problem is way worse then the slip immunity problem because it makes any static defense into paper, and it ruins any mode that relies on it, like clock cult (though arguably it's a healthy counter since cult is encouraged to wall spam anyway), blood cult, blob, swarmers, rev (when security is forced to hole up), and any time ever the AI is subverted.

**Comment by Cyberboss** [comment]
Regardless,, this isn't the way to fix the issue

**Pull request closed without merging**
