### PR TITLE
Allows aliens to mine

### PR DESCRIPTION
**Pull request by AnturK**
What it says on the tin, always thought they should be able to make asteroid nests.
4 seconds delay

### CODE REVIEW

**Comment by Xhuis** [comment]
tunnel xenos rule

**Comment by AnturK** [comment]
Hmm, good point. I'll add the digging noise

**Comment by GunHog** [comment]
The potential for humans to enslave the aliens and force them to mine for them...I want to see this happen one day.

**Comment by WJohn** [comment]
Xeno ant farms :+1:

**Comment by duncathan** [comment]
I read this as "Allow aliens to mime" and got bizarrely scared

**Comment by bustygoku** [comment]
alien hunter looks as if a wall is in front of them.

**Pull request merged**
