### PR TITLE
Adds Ponies (not a joke)

### PR DESCRIPTION
**Pull request by Core0verload**
While the ponies were a playable race as a part of April Fools, I noticed that they had a lot of positive impact on any round they were in. For example, they reduced amount of antaghunting a lot - why hunt valid antags when you can hunt valid ponies? As antaghunting always was a major problem for /tg/station playerbase and no attempt to fix it was that successful before, this alone justifies merging this PR. 

Sadly, the players were unable to fully enjoy the ponies because of game-breaking April Fools things such as Auto GM or everytraitor game mode. But the feedback was positive anyway, so I think we should give them a chance.

You had to enable ponies race in config to actually make it roundstart.

Includes #16549.

### CODE REVIEW

**Comment by Niknakflak** [comment]
No

**Comment by RandomMarine** [comment]
No

**Comment by TrustyGun** [comment]
No

**Comment by Firecage** [comment]
Yes

**Comment by Incoming5643** [comment]
@firecage no

**Comment by Bawhoppen** [comment]
Shadowlights going to do this if you don't so :+1:

**Comment by Steelpoint** [comment]
I warned you this is what would happen when Lizards were made a round start race, but no one listened. 

happen

**Comment by Supermichael777** [comment]
yes but only if their not valid. so no.

**Comment by Hatfish** [comment]
You're a bit late for April Fools, mate.

**Comment by duncathan** [comment]
never

**Comment by Xhuis** [comment]
If we want validhuntable races, just add tajarans and make them validhuntable. It's funnier that way because they take more burn damage.

**Comment by duncathan** [comment]
I'd much rather have Tajaran than ponies

**Comment by lzimann** [comment]
make lizards valid

**Comment by Core0verload** [comment]
@Shadowlight213, your turn.

**Pull request closed without merging**
