### PR TITLE
AFK players will no longer default to continue playing during restart votes.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
:cl: 
tweak: AFK players will no longer default to continue playing during restart votes.
/:cl:

Non afk players will still default if they don't vote.

### CODE REVIEW

**Comment by WJohn** [comment]
Well. This should make restarting rounds about 1000x more likely.

**Comment by PKPenguin321** [comment]
:+1: Thank you. A lot of the time if most players die and it's a lagfest, many of them alt-tab, and miss restart votes

**Comment by bgobandit** [comment]
it still requires admin confirmation right?

**Comment by PKPenguin321** [comment]
Speaking of admin confirmation, it shouldn't be needed if the online admins are AFK

**Comment by kevinz000** [comment]
i ded pls restart

**Comment by MrStonedOne** [comment]
>Speaking of admin confirmation, it shouldn't be needed if the online admins are AFK

Do you think you are playing with children? When I coded the admin check i gave it both a check for afk, AND a check for rather or not the admin online had the power to restart the server manually themselves.

**Comment by Kromgar** [comment]
had rounds where admins refused to restart and it was laggy to all hell

**Comment by PKPenguin321** [comment]
oh shit mso, one step ahead of me

good stuff all around :+1:

**Comment by Bawhoppen** [comment]
BEST PR OF 2016 :+1:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:x:100:

**Pull request merged**
