### PR TITLE
Makes Limbs Small Weight (To Fit In Trashbags)

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
tweak: limbs are now small
/:cl:

its a pain when you are a janitor and the crew starts losing limbs in the hallway and you cant quick grab them with the trashbag
the head bodypart overwrites it to bulky so this doesnt change it

### CODE REVIEW

**Comment by nemvar** [comment]
:clap: Document :clap: Your :clap: Changes :clap: Properly :clap:

**Comment by bigfatbananacyclops** [comment]
now i can be a true serial killer...

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=EwJS-xXCeNY

**Comment by habader** [comment]
I think this also means chefs can make organ soup

**Comment by ExcessiveUseOfCobblestone** [comment]
A tlat PR with a obscure title/desc that upon looking at the code has a lot of other implications, my favorite!

**Review by SpaceManiac — APPROVED** [review]
Time for some fun, we can revert if there are weird unintended consequences

**Pull request merged**
