### PR TITLE
Standardized the corporate name

### PR DESCRIPTION
**Pull request by ShizCalev**
898 instances of Nanotrasen
53 instances of NanoTrasen

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
watch people argue that its NanoTrasen

**Comment by ShizCalev** [comment]
That's why I did it as a separate pr tbh lol

**Comment by Ratvar** [comment]
NaNoTrAsEn

**Comment by Qbopper** [comment]
as the official loremaster (tm) i hereby decree that this be merged immediately

**Comment by NewSta1** [comment]
There's a reason people say NT. It's NanoTrasen.

**Comment by ShizCalev** [comment]
@NewSta1 
3mmy7bd
3mmyam4

**Comment by Qbopper** [comment]
fuck you

**Comment by kilkun** [comment]
It's Nanotrasen according to the inventor of the word, Exadv1:

https://wiki.ss13.co/Old_Storyline

I agree NanoTrasen initially makes more sense because it's supposed to be the portmanteau of Nano (as in nanotechnology, although that doesn't make sense as Nanotrasen is a company that specializes in genetic engineering) and Trasen, the last name of the company's founder.

Unfortunately Trasen was completely fabricated by Bay in the Good Old Days and isn't actually a thing.

The more you know!

**Comment by optimumtact** [comment]
This is my lore

**Comment by kilkun** [comment]
your lore is bad lol :grinning:

**Comment by Jordie0608** [comment]
He got a really good inheritance deal.

**Comment by kilkun** [comment]
im jealous

**Pull request merged**
