### PR TITLE
Slightly improves visible and audible messages.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

send_message now uses defines instead of magic numbers.
slight code changes to audible_message and visual_message
You now get a message if you are blind and your PDA explodes.

## Changelog
:cl:
fix: You now get a message if your PDA explodes while you are holding it.
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good

**Comment by ShizCalev** [comment]
conflict

**Comment by nemvar** [comment]
Huh... doesn't the label usually get removed automatically?

**Comment by Qustinnus** [comment]
it usually gets added automatically, too.

**Pull request merged**
