### PR TITLE
Adds fishnets

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Adds fishnet socks in knee, thich and stocking lengths

image

## Why It's Good For The Game

More cosmetic choices, allows everyone to wear fishnets when they're currently only found as part of very specific clothing items

## Changelog
:cl:
add: Added new fishnet style socks, in a choice of three lengths
/:cl:

### CODE REVIEW

**Comment by Pinkufeck** [comment]
based pr

**Comment by MMMiracles** [comment]
how do you catch fish with these if your legs are inside the nets

**Comment by Thunder12345** [comment]
> how do you catch fish with these if your legs are inside the nets

That would be fishing nets, not fishnets

**Comment by tralezab** [comment]
Where are the fish

**Comment by Potato-Masher** [comment]
this is not the fishing content expansion I had in mind

**Comment by IndieanaJones** [comment]
0/10 fishless

**Comment by newfren** [comment]
what does it look like on a plasmaman

**Comment by Serxule** [comment]
didnt we already have these

**Comment by Cheshify** [comment]
PR has no fish

**Comment by LemonInTheDark** [comment]
This pr genuinely made me really disappointed I want to close it now

**Comment by Farquaar** [comment]
How do you catch fish with them if it's not an item? Am I missing something?

**Comment by jlsnow301** [comment]
i'd like to move to close this in 24h. while good for the fish jokes, it's not something I think is appropriate in game

**Comment by Thunder12345** [comment]
> i'd like to move to close this in 24h. while good for the fish jokes, it's not something I think is appropriate in game

What's wrong with it, they're just socks

**Comment by castawaynont** [comment]
awooga

**Comment by EuclidianGeometer** [comment]
People wear fishnet stockings in real life all the time without it being some sort of horny display. They're about as sexual as a short skirt or a tight outfit - which is to say, a little bit, but also something if I saw someone wearing at a restaurant, I would not give a shit or think it was weird.

**Comment by Acer202** [comment]
I thought I was about to see SEC officers chasing down troublemakers with big green nets on aluminum handles when I saw the title.

This is good too, though!

**Comment by Flurrieon** [comment]
why it's good for the game: "teehee :3c"

**Review by Imaginos16 — APPROVED** [review]
Its fine.

**Comment by IndieanaJones** [comment]
Horrible PR, not fish-related at all

**Pull request merged**
