### PR TITLE
Prevents cultist from summoning Nar-Sie when their sacrifice objective isn't complete.

### LINKED ISSUE #7921: Balance: Prevent Cultists from summoning Nar'sie before their Sacrifice objective is complete.
It makes logical sense after all. Why would Nar'sie grace the cultists with his presence if they can't even sacrifice one guy? Perhaps switch the objective order around with the sac objective first and the summon objective second so the cult doesn't get confused by this. It's hilariously easy to summon Nar'sie with the manifest ghost rune so this would help prevent abuse of that.
Issue is further highlighted here: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=2981

### PR DESCRIPTION
**Pull request by phil235**
fixes #7921

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Should technically read "Implements 7921" for posterity, as it's a feature request

**Comment by RemieRichards** [comment]
@Dorsisdwarf it has to be "fixes" otherwise it wont automatically close the issue.

**Comment by Incoming5643** [comment]
close
    closes
    closed
    fix
    fixes
    fixed
    resolve
    resolves
    resolved

All work, but most people here just used fixes

**Comment by RemieRichards** [comment]
Yes incoming, but the case here was fixes vs implements, the numerous synonyms are unimportant.

**Comment by optimumtact** [comment]
Hows is close a synonym for fixed m8?

**Comment by RemieRichards** [comment]
fix your mouth oranges.

**Comment by PKPenguin321** [comment]
As I said in the thread that inspired this, if the cultists cannot complete their original objective (singulo eats the sacrifice target or something) then they should still be able to summon nar'sie for the half victory.

**Comment by mikecari** [comment]
>half victory.
So they should summon a huge round-interrupting abomination that can literally be summoned with manifest ghosts in 5 seconds just so they can get their shitty "half-greentext"?
The problem here is that summoning Nar'sie on its own takes literally no effort on the cultists' part and gives them a false sense of victory.

**Comment by PKPenguin321** [comment]
Summoning Nar'Sie if the sacrifice target is impossible to sacrifice because of gibbing is something that has happened, does happen, happened to me personally, and is in no way shitty. It allows the cultists to bring closure to a round despite their target getting fucked up by something. Sounds like you just don't like Nar'Sie, which is your own issue.

**Comment by mikecari** [comment]
No, it's apparently not just "my issue" if there's a pull request for this already. Try thinking of the community for once.

**Comment by paprka** [comment]
Cults should get a new sac objective if the current one gets gibbed or something, but still, it's important that the cult keeps their target alive or intact until they sacrifice -- it's part of the game. Stalking a person and stuff. If you just expect to research all round and then assault the brig to steal the warden only to find out he got bored and fell asleep in his locker and you can't find him, that's on you for not getting him earlier.

**Comment by Cheridan** [comment]
Please keep discussion relevant to the actual PRs :/

**Comment by paprka** [comment]
:^/

**Pull request merged**
