### PR TITLE
Clown car fix second edition

### PR DESCRIPTION
**Pull request by lilacrhododendron**
closes https://github.com/tgstation/tgstation/pull/40249

This time I'm less stupid, hopefully. It all just works.

### CODE REVIEW

**Comment by Wilchenx** [comment]
image

**Comment by Qustinnus** [comment]
im not a black woman

**Comment by Wilchenx** [comment]
but you are a thottie neverless

**Comment by subject217** [comment]
\>coderbus
Good image though. the other PR got fucked up because I was being silly. There was nothing wrong with it and there's nothing wrong with this one. I would have re-opened it but I force pushed a revert because for some reason I forgot exactly what I was doing and I couldn't re-open it. So here we are.

**Comment by Qustinnus** [comment]
are you calling that developed independent black lady a thottie

**Comment by Wilchenx** [comment]
well she is portrayed by you

**Comment by Qustinnus** [comment]
image
i felt cute in this pic

**Comment by ExcessiveUseOfCobblestone** [comment]
> 2 line fix
>> 3 lines changed

What sorcery...

**Comment by Qustinnus** [comment]
i told him to add that later

**Pull request merged**
