### PR TITLE
Revert "Limit repository announcements to a whitelist, Discord announces to a blacklist"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#63179

This already exists in the config.

did you even look at `secrets.php`?

@Mothblocks 

https://github.com/tgstation/tgstation/blob/master/tools/WebhookProcessor/secret.php#L49-L74

### CODE REVIEW

**Comment by Mothblocks** [comment]
> did you even look at secrets.php?

No of course not, now please add `event-winter-ball-2021` to both blacklists

**Comment by optimumtact** [comment]
not much use if only you can edit it

**Comment by optimumtact** [comment]
@MrStonedOne are the relevant configurations in place?

**Comment by optimumtact** [comment]
@MrStonedOne are the relevant configurations in place?

**Comment by optimumtact** [comment]
@MrStonedOne is the config in place.

**Comment by optimumtact** [comment]
@MrStonedOne has the config change been made? You are the only person who can confirm this.

**Comment by optimumtact** [comment]
@MrStonedOne has the config change been made? You are the only person who can confirm this.

**Comment by optimumtact** [comment]
@MrStonedOne has the configuration been updated, you are the only person who can confirm this

**Comment by MrStonedOne** [comment]
oh, no, i forgot to label the configs and basically need to rebuild it from scratch, i'll try to get that here quickly

**Comment by Mothblocks** [comment]
Surely this shows why a blanket pattern is preferable considering we want to be able to spin up events with the `event-` prefix quickly

**Comment by optimumtact** [comment]
@MrStonedOne did the changes get made?

**Comment by optimumtact** [comment]
@MrStonedOne did the changes get made?

**Comment by Mothblocks** [comment]
the event got put on hiatus, revived, finished, and happened in the time it took for this pr to be up 😄

**Pull request closed without merging**
