### PR TITLE
Plasmamen can now man the bar

### PR DESCRIPTION
**Pull request by ChangelingRain**
# FIRSTPLASMAMANPR

:cl: Joan
tweak: Plasmamen can now man the bar.
/:cl:

### CODE REVIEW

**Comment by as334** [comment]
Pretty sure this is the 2nd m80

**Comment by Supermichael777** [comment]
At least the fifth dedicated pull.

**Comment by Shadowlight213** [comment]
>comparing plasmamen to boxes

For shame.

**Comment by Cheridan** [comment]
remember to put out flaming shots before you drink them, or you're going to have a bad time

**Pull request merged**
