### PR TITLE
Fixes monkey recyclers not connecting on box

### LINKED ISSUE #41792: Xenobio Cams Do Not Start Out Connected To The Recycler
#41276

Computers are likely being loaded before the recycler but I haven't done my homework yet.

### PR DESCRIPTION
**Pull request by kriskog**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Skoglol
fix: Monkey recyclers will now connect to console on box station.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Fixes #41792

The turf under the recycler had the wrong area assigned, which caused the area check to connect the recycler to fail. 

First time doing anything map related, someone please make sure I didn't fuck anything up.

### CODE REVIEW

**Comment by ma44** [comment]
> +0 -0 lines changed
:thinking:

**Comment by kriskog** [comment]
Oof.

**Comment by kriskog** [comment]
I don't even know anymore. I removed and reapplied the turf, saved and map merged. Git said  there was a modification, and it started working as expected. 

After this I reverted to master, and now that I rechecked, I don't see the different area name anymore and it stopped working. What.

Closing this for now.

**Comment by ExcessiveUseOfCobblestone** [comment]
lol'd

**Pull request closed without merging**
