### PR TITLE
Removes a loose power cable that fails tests in Icebox Maint

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
In the Electrical Maintenance area on Ice Box, there is a pair of SMESs that are used for emergency power. One of the SMESs has a single, loose power cable underneath it that does not connect to anything. It causes a test to fail on the CI suite, so I made a PR to remove it.

The test in question:
image

proof of testing:
image (Before)
image (After)
It's GONE.

## Why It's Good For The Game
I am annoyed by this single mapping error, and by resolving it, I have fixed every issue with ice box and we will never need to touch Ice Box again. (Looks at the camera)

## Changelog

:cl: ReturnToZender (hitting delete on a power cable)
del: Single loose power cable in icebox maintenance
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
I was astonished to find that TGstation did not require any proof of testing for their PRs. I went through all the effort to take images of what I'd done and then found out there was no section for it. Odd.

**Comment by ZephyrTFA** [comment]
well you see. we actually trust our contributors in most cases

**Comment by ReturnToZender** [comment]
> well you see. we actually trust our contributors in most cases

I appreciate the trust :)

**Comment by improvedname** [comment]
this is super ancient icebox thing but its also quite funny you can't place loose wires down without a powernet test fail

**Review by Maurukas — APPROVED** [review]
My bad on this one. I thought I got that before I pushed that branch.

**Pull request merged**
