### PR TITLE
Focuses the game more on roleplay.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Sounds and visuals distract from the chatbox and encourage a more gameplay focused experience. We need to go back to the text box, people should be looking at the text box more.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
oh fuck wrong githubbbb

eh this meme PR works here too

**Comment by Cyberboss** [comment]
I bet my next nuke roll this won't compile

**Comment by sawrge** [comment]
its always funny dude

**Comment by sawrge** [comment]
fucking faggot

**Comment by SgtxRootbeer** [comment]
the fruit?
opening a pr?

**Pull request closed without merging**
