### PR TITLE
Framework for holiday-specific poster spawns

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Creates a framework to spawn holiday-specific posters. Poster data is stored in the holiday datum, then applied to the poster on its initilization, to keep it organized. 

## Why It's Good For The Game
Holiday cheer!

## Changelog

:cl:
add: holiday specific posters (only a few now)
/:cl:

### CODE REVIEW

**Comment by etherware-novice** [comment]
why is enter default to create the pr

**Comment by Addust** [comment]
show us the icons

**Comment by etherware-novice** [comment]
holiday_poster_collage

**Comment by Wallemations** [comment]
The code doesn't compile correctly and it won't work because you forgot a `"`

**Comment by etherware-novice** [comment]
hi, can you put in a suggested change for that? i can only use mobile atm

**Review by MrMelbert — CHANGES_REQUESTED** [review]
here's your missing quotation mark, though this code will not compile even with it, since holidays are no longer tracked on ssevents

**Comment by etherware-novice** [comment]
oh where are they tracked

**Review by dragomagol — DISMISSED** [review]
We're trying to make sure that posters being added are, at maximum, 24px high in preparation for the wallening. Please compress these to that height.

**Comment by etherware-novice** [comment]
can you provide a poster frame please?

**Comment by dragomagol** [comment]
image

**Comment by etherware-novice** [comment]
holiday_poster_wallng

**Comment by etherware-novice** [comment]
image

**Comment by etherware-novice** [comment]
holiday_poster_wallng

**Pull request merged**
