### PR TITLE
Removes an arbitrarily-selected amount of wire colors

### PR DESCRIPTION
**Pull request by ChangelingRain**
Mostly long ones. `lightgoldenrodyellow` what the hell.
Also adds a gray and a navy.

### CODE REVIEW

**Comment by Jalleo** [comment]
Let the bikeshedding commence.

**Comment by ChangelingRain** [comment]
May we shred forever more.

**Comment by optimumtact** [comment]
Niknak's was first, please attempt to leave feedback on theirs first before making a new PR.

Thank you.

**Comment by ChangelingRain** [comment]
niknak does not appear to be taking feedback and I am incredulously petty

**Comment by optimumtact** [comment]
YOU ARE NOT HELPING

**Pull request closed without merging**
