### PR TITLE
Ports additional Felinid ears from Orbstation

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request
Adds 5 new ear options from Orbstation, originally PRed in lizardqueenlexi/orbstation#360. Sprites by @Or-Fi-S.

Big:
image

Coeurl (FFXIV Miqo'te style):
image

Fold:
image

Lynx:
image

Round:
image

Also makes it so the code guarantees that custom ears on a felinid actually count as felinid ears and not human ones, as the code wasn't checking properly when preferences were applied. There's probably a cleaner, more permanent way to do this and a refactor is needed somewhere down the line (man that sprite accessories file is getting long huh) but I'll leave that to a more competent coder.

## Why It's Good For The Game
More customization options are good also Cobby said I could

image

## Changelog
:cl:
add: Added 5 new Felinid ear options, ported from Orbstation! (Sprites by Or-Fi-S)
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
felinids specifically require @optimumtact's signoff, not just a maintainer

**Comment by TheVekter** [comment]
It's worth noting that, in discussing porting these, Jacquerel mentioned that they vaguely remember the spriter not wanting these ported for one reason or another. I've had difficulty locating Discord information for the spriter and they haven't contributed anything in literal years, so I feel like this is a matter of needing to just PR it and mention them and see if they object. If they do, I'll look at getting new sprites made. _Technically_ I don't need permission given how Orbstation's licensing is set up, but I'm not a dick, so.

Also another technicality is that @optimumtact needs to sign off on this since it's a felinid change but it's cosmetic only so I reckon I'm fine.

**Comment by DATA-xPUNGED** [comment]
It's stupid that even cosmetic changes needs to go through oranges, it's just new ears, cmon

**Comment by TheVekter** [comment]
Fixed an issue with the custom ears showing up once removed as just regular human ears thanks to @00-Steven.

**Review by optimumtact — APPROVED** [review]

**Review by Wallemations — APPROVED** [review]
I hate the hair you chose to display it on but yea sure

**Comment by TheVekter** [comment]
> I hate the hair you chose to display it on but yea sure

It sucks but I wanted hair that would make it easier to see the ears, it was this or bald

**Comment by ExcessiveUseOfCobblestone** [comment]
FRICK ORANGES

**Comment by necromanceranne** [comment]
big ear cat
F2RA9KPaoAAZMg_

**Comment by Thunder12345** [comment]
> > I hate the hair you chose to display it on but yea sure
> 
> It sucks but I wanted hair that would make it easier to see the ears, it was this or bald

Cat_Sphynx _Kittens _img_11

**Comment by 00-Steven** [comment]
So there's one more issue with this that should probably be solved before merging, and that's that cat ear organs are coded to set your dna's `features` and species' `mutant_bodyparts` to "Cat" so they can actually work:

https://github.com/tgstation/tgstation/blob/6361a2506df7053134c2a3f0985f17a9a58756cc/code/modules/surgery/organs/internal/ears/_ears.dm#L71-L77

Having this work properly in practice, especially with surgically removing/attaching them, is going to require changing this to account for the multiple possible values. Otherwise it'll just, Default to Default Cat Ears.
Refactoring this to work relatively sanely like external organs feels like a bad idea to do _Right Now_, so I'd propose either of two slightly hacky ways:

## Slightly Hacky Proposed Solutions

For both we first just add a new variable to `/obj/item/organ/internal/ears/cat` called let's say `variant`:
```dm
/obj/item/organ/internal/ears/cat
	(...)
	// Keeps track of which cat ears sprite is associated with this.
	var/variant = "Cat"
```
And when setting the features/mutant bodyparts, use _that_ instead:
```dm
ear_owner.dna.features["ears"] = ear_owner.dna.species.mutant_bodyparts["ears"] = variant
```
This lets us keep track of what it's *supposed* to be on the ears.

### Initialize Route

Then either extend `Initialize` to let us set this value:
```dm
(code/modules/surgery/organs/internal/ears/_ears.dm)
/obj/item/organ/internal/ears/cat/Initialize(mapload, variant_pref)
	. = ..()
	if(variant_pref)
		variant = variant_pref
```
And have `/datum/species/human/felinid/on_species_gain(...)` handle setting it:
```dm
(/code/modules/mob/living/carbon/human/species_types/felinid.dm)
/datum/species/human/felinid/on_species_gain(mob/living/carbon/carbon_being, datum/species/old_species, pref_load)
	if(ishuman(carbon_being))
		(...)
		if(target_human.dna.features["ears"] == "None")
			mutantears = /obj/item/organ/internal/ears
		else
			var/obj/item/organ/internal/ears/cat/ears = new(FALSE, target_human.dna.features["ears"])
			ears.Insert(target_human, movement_flags = DELETE_IF_REPLACED)
	return ..()
```

### Subtypes Route

Or create subtypes with different `variant` values, i.e.:
```dm
(code/modules/surgery/organs/internal/ears/_ears.dm)
/obj/item/organ/internal/ears/cat/big
	name = "big cat ears"
	variant = "Big"

/obj/item/organ/internal/ears/cat/fold
	name = "folded cat ears"
	variant = "Fold"

(...)
```
And have `/datum/species/human/felinid/on_species_gain(...)` handle picking it:
```dm
(/code/modules/mob/living/carbon/human/species_types/felinid.dm)
/datum/species/human/felinid/on_species_gain(mob/living/carbon/carbon_being, datum/species/old_species, pref_load)
	if(ishuman(carbon_being))
		(...)
		switch(target_human.dna.features["ears"])
			if("None")
				mutantears = /obj/item/organ/internal/ears
			if("Big")
				mutantears = var/obj/item/organ/internal/ears/cat/big
			if("Cat") // Actually the species default so prob unneeded
				mutantears = var/obj/item/organ/internal/ears/cat
			if("Fold")
				mutantears = var/obj/item/organ/internal/ears/cat/fold
			(...)
		if(ears)
			ears.Insert(target_human, movement_flags = DELETE_IF_REPLACED)
	return ..()
```
Or instead of an unwieldy switch statement having a list of which option corresponds to which cat ears subtype.

---

It's not particularly _clean_ either way, but it'd _work_:tm: for now, and _I_ think that's good enough for the scope of this pr.

**Comment by san7890** [comment]
> So there's one more issue with this that should probably be solved before merging, and that's that cat ear organs are coded to set your dna's `features` and species' `mutant_bodyparts` to "Cat" so they can actually work:

if you want to work on it (since you've given it a lot of thought) you can make a pull request with the functioning code to their fork targetting their branch (`cat-ears-expansion`)

**Comment by Wallemations** [comment]
I gave my ok so let the code maints merge it

**Comment by san7890** [comment]
they were trying to collaborate (i think) on working on the code but there was something about weirdness to doing a PR to vekter's repo... we can do a project branch or something before we merge it into master

**Comment by 00-Steven** [comment]
Mhmm, thanks San, we've worked out a thing already though o7
I've already got a tested-to-work albeit awkward solution written up, taking the aforementioned Initialize route

I don't particularly _like_ it, but it makes them actually work™️, and while I'd love to do a ears refactor it feels outside of the scope of this pr.
That and if I'd try to do one _right now_ I'd burn out _real bad_.
But yeah know the code here and whatever's fucky with it is my responsibility, not Vekter's o7

**Comment by san7890** [comment]
> I don't particularly like it, but it makes them actually work™️, and while I'd love to do a ears refactor it feels outside of the scope of this pr.
That and if I'd try to do one right now I'd burn out real bad.

i think the code is wonky but i think we've just inherited the framework. a good way to ensure you stay sane if you ever pursue another refactor of this stuff is to add screenshot tests of this stuff to ensure that ear stuff doesn't noticeably regress

**Pull request merged**
