### PR TITLE
Megafauna doesn't go in machines

### PR DESCRIPTION
**Pull request by DaedalusGame**
:cl:
fix: Prevents megafauna (and other large things like spiders and mulebots) from going into machines
/:cl:

The flight plan I just filed with the Agency lists me, my men, and Dr. Pavel here. But only one of you.

### CODE REVIEW

**Comment by Mark9013100** [comment]
LOTTA LOYALTY FOR A HIRED GUN.

**Comment by AlexTheSysop42** [comment]
>someone mentions bug on discord
>fix PRd within the hour

**Comment by DaedalusGame** [comment]
OR PERHAPS HE WAS WONDERING WHY YOU WOULD SHOOT A MEGAFAUNA BEFORE STUFFING IT INTO A SUIT STORAGE

**Comment by 81Denton** [comment]
IF I MERGE THIS, WILL YOU DIE?

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Fix your changelog

**Comment by Buggy123** [comment]
So you can... stuff megafauna into suit storages, cloner scanners, etc?

That's hilarious, keep it in!

**Comment by Thunder12345** [comment]
\>TFW you shut a drake in an SSU to prank the other miners

**Comment by DaedalusGame** [comment]
you can use this to bring megafauna onto the station safely

**Comment by Buggy123** [comment]
>safely
>you have to stuff it in a SUIT STORAGE

Being in melee range of a megafauna is never even remotely safe. A colossus will 1-shot you through armor at melee range. A drake or bubblegum will hit you for 40 armor-penetrating brute. They also instantly aggro at that sort of range.

**Comment by DaedalusGame** [comment]
remember when your fulton pr got closed

**Comment by Buggy123** [comment]
I'm still not convinced. How are you going to put a megafauna in a machine?

1: You can't drag the machine over it directly, because its anchored

2: All of their sprites are so big, that for anything that closes instantly (dna scanner) you have to alt click to close it even if they're over it, so that takes 1-2 seconds to load.

3: Stuffing them into a suit storage takes 3 seconds.

So no matter what, you're going to have to sit still next to the mega for a few seconds. And again, sitting still next to a megafauna is a **Bad Time**.

**Comment by DaedalusGame** [comment]
Instant Summons

**Comment by Buggy123** [comment]
Instant summons a... machine?

**Comment by Buggy123** [comment]
I honestly didn't know that. So if you put something in a locker and summon it, it summons the LOCKER?

**Comment by Kromgar** [comment]
This is like the edgiest of edge cases.

**Comment by PKPenguin321** [comment]
Fun removal

**Comment by DaedalusGame** [comment]
Cyberboss rejected the proper changelog so we can't call it that sorry

**Comment by Mey-Ha-Zah** [comment]
Call it no fun allowed.

I figured out you could instant-summons the suit containers, and I knew from past experience you could capture Megafauna in them, cause a Miner did that once with a bubblegum that was wrecking the base.

I've never even used it because I've almost never gotten instant summons as antag.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
