### PR TITLE
we wont be needing these mesons as miners anymor euh...

### PR DESCRIPTION
**Pull request by improvedname**
:cl: Improvedname
del: Goodbye mesons
/:cl:

### CODE REVIEW

**Comment by Kraseo** [comment]
at least it won't rub salt on the wound

**Review by Cyberboss — APPROVED** [review]

**Comment by Bawhoppen** [comment]
meme PR

**Comment by pizzatiger** [comment]
To be honest, I don't like this change, Mesons still have use of giving a tiny bit of night vision which is often quite useful.

**Comment by GunHog** [comment]
https://github.com/tgstation/tgstation/pull/28570

**Comment by Repukan** [comment]
Pls

**Pull request closed without merging**
