### PR TITLE
Moves most of world.dm

### PR DESCRIPTION
**Pull request by Cyberboss**
To a place where defines actually work!

### CODE REVIEW

**Comment by MrStonedOne** [comment]
did you run this?

**Comment by Cyberboss** [comment]
untitled

**Comment by optimumtact** [comment]
There's no reason to do this and it violates byond project layout expectations 👎

**Comment by Cyberboss** [comment]
Not being able to use defines in world.dm is a nuisance though

**Comment by AnturK** [comment]
Which way @tgstation/commit-access ?

Personally, i'm fine with the split.

**Pull request merged**
