### PR TITLE
Adds a 'TWANG' sound effect for guitars

### PR DESCRIPTION
**Pull request by MMMiracles**
Hitting something with a guitar now produces an oddly satisfying 'TWANG' noise. 
The sound itself is at 8.88 KB.

### CODE REVIEW

**Comment by Cheridan** [comment]
Sounds have to be CC0, we can't use Team Fortress sound effects in our game

**Comment by MMMiracles** [comment]
well fff i just assumed considering it was a f2p, lemme see if i can find a decent freeware alernative.

**Comment by WJohn** [comment]
I hope it's not nearly as loud as the sound you've displayed there, because holy shit ow

**Comment by MMMiracles** [comment]
if the new sound doesn't sound right then i'm just probably just gonna say fuck it and close the pr because the original one was what i was hoping for.

**Comment by Incoming5643** [comment]
Just because a game is free to play doesn't mean that the sound files weren't at one point paid for or produced in house and not for sale.

Also EL KABONG is iconic enough that I know there's probably a decent free version someone with a lot of excess guitars made at some point.

**Comment by Iamgoofball** [comment]
We could email valve and ask to use the TWANG.

**Comment by MMMiracles** [comment]
replaced awful placeholder with el kabong for now. i went ahead and asked for permission just incase of an off-chance they actually reply with permission to use the original sound.

**Comment by Cheridan** [comment]
Here's a CC0 sound clip of someone smashing a guitar on someone's skull https://www.freesound.org/people/AbuseArt/sounds/201111/

**Comment by tigercat2000** [comment]
@Cheridan I feel it should be noted that [Paradise](https://github.com/ParadiseSS13/Paradise) uses that exact sound for the guitar hit noise. Which is amusing.

**Pull request merged**
