### PR TITLE
MODsuit: unhardcoded parts

### LINKED ISSUE #69933: MOD helmets are deleting multiple times
## Round ID:
Tested locally

## Reproduction:

Equip admin outfit through right-click select equipment

Check runtimes

Runtime in garbage.dm, line 389: /obj/item/clothing/head/mod destroy proc was called multiple times, likely due to a qdel loop in the Destroy logic

<details>
  <summary>One of the runtime messages</summary>

```
proc name: qdel (/proc/qdel)
usr: Guest-463363279/(Harry Muggins)
usr.loc: (Command Hallway (113,127,2))
src: null
call stack:
qdel(the administrative MOD helmet (/obj/item/clothing/head/mod), 0)
the administrative MOD control... (/obj/item/mod/control/pre_equipped/administrative): Destroy(0)
the administrative MOD control... (/obj/item/mod/control/pre_equipped/administrative): Destroy(0)
the administrative MOD control... (/obj/item/mod/control/pre_equipped/administrative): Destroy(0)
the administrative MOD control... (/obj/item/mod/control/pre_equipped/administrative): Destroy(0)
qdel(the administrative MOD control... (/obj/item/mod/control/pre_equipped/administrative), 0)
the administrative MOD control... (/obj/item/mod/control/pre_equipped/administrative): on part deletion(the administrative MOD helmet (/obj/item/clothing/head/mod), 0)
the administrative MOD helmet (/obj/item/clothing/head/mod): SendSignal("parent_qdeleting", /list (/list))
qdel(the administrative MOD helmet (/obj/item/clothing/head/mod), 0)
Wardrobe (/datum/controller/subsystem/wardrobe): stash object(the administrative MOD helmet (/obj/item/clothing/head/mod))
...
/datum/select_equipment (/datum/select_equipment): ui data(Harry Muggins (/mob/living/carbon/human))
/datum/tgui (/datum/tgui): get payload(null, 1, null)
/datum/tgui (/datum/tgui): send update(null, null)
tgui (/datum/controller/subsystem/tgui): try update ui(Harry Muggins (/mob/living/carbon/human), /datum/select_equipment (/datum/select_equipment), /datum/tgui (/datum/tgui))
/datum/select_equipment (/datum/select_equipment): ui interact(Harry Muggins (/mob/living/carbon/human), /datum/tgui (/datum/tgui))
/datum/tgui (/datum/tgui): process(0.9, 1)
/datum/tgui (/datum/tgui): on act message("preview", /list (/list), /datum/ui_state/admin_state (/datum/ui_state/admin_state))
/datum/tgui (/datum/tgui): on message("act/preview", /list (/list), /list (/list))
tgui Topic(/list (/list))
Guest-463363279 (/client): Topic("type=act%2Fpreview&payload=%7B...", /list (/list), null)

```
</details>

The same runtime appears once for the dummy used to display the outfit in Select Equipment, and two more runtimes pop up if you actually equip the outfit.

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

This is drafted to make me finish it because its long overdue
unhardcodes modsuit parts - instead of helmet chestplate gauntlets boots, they will be able to be any parts, and everything is handled by a mod part datum interfacing between the modsuit and the part.
fixes #69933

## Why It's Good For The Game

This + making modules linked to the unhardcoded parts (this is coming next) lets us later do these:
- making suits that dont work on helmet chestplate etc, something like scarf glasses suit will be possible
- making the suits able to extend/retract parts while active without being a fucking mistake (skyrat moment)
- making the suits not turn off when you get delimbed

## Changelog

not player facing

### CODE REVIEW

**Comment by calliophis-maculiceps** [comment]
THE LAWYER TIE SUIT IS COMING

**Comment by theta060** [comment]
make tot suits not need boots or gloves so we can actually use the shit we buy

**Comment by Mothblocks** [comment]
It's been nearly a week since last commit and this is still drafted and failing tests, we have over 100 PRs up right now so I am closing this

Feel free to reopen when ready

**Comment by Fikou** [comment]
almost done, needs a rework of how we do some clothing rendering, ui fixes and implementing all the modules that modify your parts, but the backend for that is finished

**Comment by deathrobotpunch** [comment]
good PR yesterday I died as a miner to gibtonite and my mining modsuit turned off stopping the GPS from working

**Comment by Fikou** [comment]
> good PR yesterday I died as a miner to gibtonite and my mining modsuit turned off stopping the GPS from working

that module should work when the suit is off tbh

**Pull request closed without merging**
