### PR TITLE
Removes the Phobia Brain Trauma for being the most unfun trauma.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Removes the Phobia Brain Trauma for being the most unfun trauma.

## Why It's Good For The Game

This trauma fucking sucks.  It is not enjoyable. It does not provide a unique storytelling experience. It is like how Tourettes used to hard stun you for 60 seconds every two minutes. This makes me want to tear my fucking eyeballs out. I hate this trauma. I hate getting it. I hate rolling it as deep rooted. I hate it. It's so bad. It's fucking awful. It is the worst fucking part of the brain trauma system. It needs to go.

## Changelog
:cl:
del: Removes the Phobia Brain Trauma for being the most unfun trauma.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
Phobia is the point scream stun trauma, the one related to the words, right? I can understand the hate but I’ve always wished it could be reimplemented in a more interesting way since I like the IDEA of a phobia.

**Comment by Iamgoofball** [comment]
i hate it so much

**Comment by necromanceranne** [comment]
remember when curators used to have this roundstart for snakes?

**Comment by NargaInDisguise** [comment]
we didnt even say to bring this upstream, you just whole ass made this on tg to begin with

power move

**Comment by SimplySmiley123** [comment]
> Phobia is the point scream stun trauma, the one related to the words, right? I can understand the hate but I’ve always wished it could be reimplemented in a more interesting way since I like the IDEA of a phobia.

It can be fun when you can pick a specific phobia for your character to fit whatever you want to do with the character, but randomly getting smacked in the head and getting an irrational, blinding phobia of your lizard coworker for example out of the blue for no reason other then "lol lmao RNGesus hates you" ain't all that fun nor really interesting.

**Comment by MrMelbert** [comment]
Check out this awesome forum thread someone proposed for a rework of phobias to be less ass

https://tgstation13.org/phpBB/viewtopic.php?f=9&t=37909

**Comment by MrMelbert** [comment]
Also I feel like it doesn't need to be said but this PR is incredibly lazily done
- Doesn't remove any of the global lists or defines
- Doesn't remove the phobia quirk / prefs
- Doesn't remove references to phobia trauma elsewhere
- Doesn't remove the string file phobias use
- Doesn't even ***remove the file from the dme***

**Comment by Iamgoofball** [comment]
i like the idea about just removing the stun I think I'll do that

**Comment by LSommers** [comment]
image
IDED PR

**Pull request closed without merging**
