### PR TITLE
Lessens Inventory Storage Restrictions

### PR DESCRIPTION
**Pull request by Cheridan**

### CODE REVIEW

**Comment by GunHog** [comment]
I thought this was a serious PR :(

**Comment by Cheridan** [comment]
It is serious, though. Might as well save ourselves a few years of storage powercreep and get it out of the way.

**Comment by JJRcop** [comment]
Well, I guess if you see someone with a bag of holding, you know they want to make a singularity.

**Comment by Jalleo** [comment]
Vendors being put inside BoH when?

**Comment by PKPenguin321** [comment]
I know our storage system is really lenient at the moment but this is overkill

**Comment by optimumtact** [comment]
No

**Pull request closed without merging**
