### PR TITLE
Bedsheets now go in the neck slot

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Bedsheets are now worn in the neck slot, rather than the back slot.
/:cl:

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Now I can have bedsheets Ops without having to carry my backpack.

**Comment by jughu** [comment]
This will make wizards cooler too

**Comment by Fox-McCloud** [comment]
Shouldn't cloaks also go in this slot?

Of course, that would mean that their armor would probably have to be axed, or else it'll cause issues, but...

**Comment by PKPenguin321** [comment]
@Fox-McCloud https://github.com/tgstation/tgstation/pull/21418

**Comment by Fox-McCloud** [comment]
Derp

**Pull request merged**
