### PR TITLE
Replaces every single book sprite with better sprites

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
imageadd: Replaced every book sprite in the game with new, consistent versions.
imageadd: Except the one-use wizard spellbooks, which already got new sprites.
/:cl:

This includes bibles, books, anything that's book-shaped in general.
Also adds another possible library book sprite, white with no blue dot.

new
**^NEW^**
old
**^OLD^**

### CODE REVIEW

**Comment by Anonus** [comment]
Animated books are still animated and do the same stuff, so the robotics book, the burning bible, and the scientology bible all still do the same stuff.

**Comment by Durkel** [comment]
Do people even read the books?

**Comment by Anonus** [comment]
¯\\\_(ツ)_/¯
Not my problem.

**Comment by WJohn** [comment]
Big :+1: 

Very nice.

**Comment by xxalpha** [comment]
They look exactly the same.

**Comment by Anonus** [comment]
Fun fact; the only totally unchanged book was the necronomicon, because it was already pretty high quality.

**Comment by ike709** [comment]
:+1:

**Comment by KazeEspada** [comment]
Meh, not enough change. Also, readd the old hacking book as a bible option.

**Pull request merged**
