### PR TITLE
Neutralised anomalies respect the core limit

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

This PR changes it so that if you refine an anomaly by neutralising it, it respects the same limit on number of anomaly cores as refining one you bought from Cargo.
If it would produce an illegal core, it will create a mostly useless inert core which you can sell at cargo for 80% of the price of buying a raw core.

## Why It's Good For The Game

https://hackmd.io/@tgstation/r1tzxpwPL
This was a requirement in the original design doc which just never made it into the game.
We want to be able to control how many cores of each type can possibly exist in a round, as this is what allows them to have the "these items can be really busted" allowance.

## Changelog

:cl:
fix: Neutralising an anomaly cannot produce more anomaly cores than are supposed to exist in a single round
/:cl:

### CODE REVIEW

**Comment by DustanHache** [comment]
_Please, do continue disincentivizing the disarming of anomalies like they are handled 100% of the time the moment they spawn. While we're at it, lets make them all capable of entering the fail state and doing their major effects multiple times in a row!_

If it wasn't evident enough from sarcasm, this change is horrible. Most people ignore anomalies already unless anomaly neutralizers are being handed out like candy (spoilers, sci doesn't do that 90% of the time) and the other disarming method is so obscure, dangerous and convoluted that only the most prepared/experienced individuals know how it works. (aka, the gas analyzer method). The reward of 5 sheets of diamonds doesn't even BEGIN to compensate for the lost value outside of low risk cores like hallucination or bioscrambler, especially after the mining changes.
At least make the reward slightly more worthwhile, on par with what it would cost to buy the most expensive RAW core.

**Comment by Jacquerel** [comment]
the cap for most anomalies is 8 so this isnt realistically actually happning in rounds, this is just patching a hole we noticed

**Comment by carlarctg** [comment]
pls just make the anom core get rerolled into a random core iinstead

**Comment by DustanHache** [comment]
> the cap for most anomalies is 8 so this isnt realistically actually happening in rounds, this is just patching a hole we noticed nobody is buying 8 hallucination cores (why would they? you can't even use them for anything, so 5 diamonds would actually be an improvement)

hallucination cores can be used for reactive armor, which let me remind you gives you a intermittent damage ignore, turns you invisible, and spawns a distraction clone for you to absorb further hits. That's pretty good, if a bit underused due to it requiring science to actually make the armor instead of hiding in robotics, xenobio and toxins. I would also like to point out that a number of the rarer anomaly core caps are lower/being adjusted down by oncoming PRs, and this will inevitably impact them as well. In fact, it's more likely to impact them compared to hallucination cores simply because the holy trinity of grav/pyro/bluespace is stupidly common, and in the case of the last one actually worth disarming.

**Comment by Jacquerel** [comment]
ok well then yeah if your plan was to make 9 hallucination reactive armours by buying 8 and then hoping another would randomly spawn im preventing you from doing that sorry

**Comment by hiss1000** [comment]
I do agree with Dunstan that I am not really a fan of this change. Personally, I would keep anomalies bypassing the core limit as is. It helps differentiate neutralizing as a method of getting anomaly cores and helps make it feel as the 'legitimate' way of getting them whereas refining is a synthetic hack with obvious drawbacks in comparison. While unlikely to come up very much with the current limits, this could change as further anomaly gear is added and other limits are lowered. People already disarm them pretty infrequently, and this gives them an incentive to keep doing so. It adds a less convenient way to bypass a hard restriction, while still keeping said method limited by the relatively infrequent spawn of anomalies.

There's also the issue of player communication. Is the anomaly limit mentioned anywhere in game outside of the refiner? This is fine if the only place players encounter the limit is refining, but could cause confusion otherwise. If it is important to keep a hard-limit on the anomaly cores available, might there be an alternative method of doing so? Limiting anomaly spawns to the limits in question could help. This continues to incentivize disabling cores and refining them now as well, and means that if you see an anomaly spawn you at least know for sure you're going to get a core out of it.

**Comment by Exester509** [comment]
> > the cap for most anomalies is 8 so this isnt realistically actually happening in rounds, this is just patching a hole we noticed nobody is buying 8 hallucination cores (why would they? you can't even use them for anything, so 5 diamonds would actually be an improvement)
> 
> hallucination cores can be used for reactive armor, which let me remind you gives you a intermittent damage ignore, turns you invisible, and spawns a distraction clone for you to absorb further hits. That's pretty good, if a bit underused due to it requiring science to actually make the armor instead of hiding in robotics, xenobio and toxins. I would also like to point out that a number of the rarer anomaly core caps are lower/being adjusted down by oncoming PRs, and this will inevitably impact them as well. In fact, it's more likely to impact them compared to hallucination cores simply because the holy trinity of grav/pyro/bluespace is stupidly common, and in the case of the last one actually worth disarming.

For the record, stealth armor (the one that turns you invisible) can only be created with vortex or pyro anomaly cores. The rest of the armors have their own unique effects.

Also, the core limit is very high for most of the anomalies, and the chance of having to neutralize an anomaly while having expended all 8 cores is virtually zero.
For vortex and bluespace, which are the ones with a smaller limit being discussed, this would still barely affect them, though I agree that 5 diamonds is perhaps a bit too underwhelming for shutting down a black hole or a teleport anomaly. Perhaps a large stack of bluespace crystals for the bluespace one?

In any case, this is a consistency PR that makes a game mechanic work as intended. If the substitute rewards are too low, then feel free to PR a change for them.

**Comment by CRITAWAKETS** [comment]
Honestly I thought this was intended behavior. If someone's already made the core limit and happens to have an event that spawns the appropriate anomaly core coincide with this, then why not? Not exactly like bluespace and vortex anomalies are common anyway.

Also I feel if you're doing this anyway for design doc constraints, atleast be fun about it and make the drop for this rare event something more interesting than just 5 diamonds. Could be a joke like coalescing into a gold trophy, could be something actually useful.

**Comment by Helg2** [comment]
Well, anomalies get defused rarely enough, and with new chances of just getting nothing, it will lower even further.

**Comment by Jacquerel** [comment]
Instead of diamonds it now produces an item worth 80% of a different anomaly core if put on the cargo shuttle.

**Comment by optimumtact** [comment]
I'm sorry but this isnt up for debate.

**Pull request merged**
