### PR TITLE
Temperature pump buff.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
The temperature pump can now transfer heat with input up to 1.2e8 kelvin instead of 1e8.

## Why It's Good For The Game
Antinoblium+hypernoblium HFR fuel mix can reach 1.2e8, which makes it a legitimate obtainable temperature. This enables people to use temperature pumps from the maximum temperature obtainable by fusion.

## Changelog

:cl: AccountName5
balance: Temperature pump can now transfer heat with input up to 1.2e8 kelvin instead of 1e8.
/:cl:

### CODE REVIEW

**Comment by 170141183460469231731687303715884105727** [comment]
I have no idea why my commits from a previous PR is here, but I couldn't seem to remove them. I don't think it will change anything though.

**Comment by LemonInTheDark** [comment]
I don't want to raise this number. Not because 1.2 is going to cause problems, but because of the pattern it sets up.
if we keep raising the expected maximum temperature, it's at some point going to start to cause problems like the one this pr was solving https://github.com/tgstation/tgstation/pull/13864
I much prefer having a hardcap to having a number that slowly increases over time until it reaches the point that the game starts to break down at.

**Comment by 170141183460469231731687303715884105727** [comment]
@LemonInTheDark if I set fusion limit to 1.2e8, then lower the maximum multipliers for the HFR fuels so their limits are the same temperature (antinob hypernob is at 1.2 times the limit, and this would set it to 1), would it be safe to assume that number won't change anymore and I can set temperature pump limit to fusion limit?

Also what do you mean by your last sentence?

**Comment by LemonInTheDark** [comment]
> 
> 
> @LemonInTheDark if I set fusion limit to 1.2e8, then lower the maximum multipliers for the HFR fuels so their limits are the same temperature (antinob hypernob is at 1.2 times the limit, and this would set it to 1), would it be safe to assume that number won't change anymore and I can set temperature pump limit to fusion limit?

I'm not quite sure what you mean by this.
> 
> Also what do you mean by your last sentence?

I don't want to raise the limit because one thing goes above it slightly, because if we keep going with that pattern in a few years we'll reach the point where it's causing actual problems because the system isn't built to support temperatures that high.

1e8 seems like a sane limit to me, and I'd rather make things that go above it cooler rather then raise it.

**Comment by 170141183460469231731687303715884105727** [comment]
Closing because #61406 makes this obsolete.

**Pull request closed without merging**
