### PR TITLE
Updates irc link in the readme.md

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by duncathan** [comment]
:-1:

**Comment by Razharas** [comment]
@Cheridan

**Comment by Cheridan** [comment]
plz no mutinies

**Comment by duncathan** [comment]
What the fuck is going on

**Comment by GunHog** [comment]
In A.D. 2016, war were beginning.

**Comment by RemieRichards** [comment]
@GunHog 
>In A.D. 2016, war were beginning.

it's "was", gosh get your memes right.

**Comment by GunHog** [comment]
I like mine better. It seemed more fitting.

**Comment by xxalpha** [comment]
https://www.youtube.com/watch?v=MegkASUhaX4

**Pull request merged**
