### PR TITLE
Attempt to prevent the gateway from derailing rounds as much.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 
:cl: Dax Dupont
add: The station's gateway has been equipped with safeguards that prevent critical employees, the heads of staff, from abandoning the station. It also requires a Captain or CentCom level ID to engage the wormhole. These restrictions do not apply when an emergency state is detected.
admin: You can disable the safeguards by var editing the gateway and setting safeguards to 0. 
/:cl:

[why]: Since map template loading is getting revamped and people are remaking/adding away missions so that they are no longer loot pinatas, I figured I'd add a small stepping stone for turning on the gate, also preventing heads from leaving 4noraisin because they are critical to round progression.
I added the var override for admins so they can run events easier.

### CODE REVIEW

**Comment by kevinz000** [comment]
If heads of staff are abandoning the station to go on loot trips without regard for the station it can be dealt with administratively.
There is no need for a hardcoded lock. Even revheads can leave the station via mining shuttle if they wish (it's just a one-time warning message if they try, it succeeds on next press), I don't see why this should be any "stronger" in terms of protection.

**Comment by Incomptinence** [comment]
A captain leading an expedition is pretty captainly really.

**Comment by DaxDupont** [comment]
@kevinz000 apparently admins didn't want to deal with it before hence the removal of the away missions because "muh derailed rounds".

If people really want I can remove that part but keep the ID lock to turn it on.

**Comment by Iatots** [comment]
Wait, who are the usual suspects of "code solutions" and "administrative solutions" again?

**Comment by DaxDupont** [comment]
Actually, I have a better idea for away missions, let's make it more accessible.

**Pull request closed without merging**
