### PR TITLE
Fixes Teslas always doing the same movement pattern

### PR DESCRIPTION
**Pull request by Robustin**
Tesla movement is now independent of the last thing it zapped. It was never going to work since large-ball teslas (the only kind that exists now) would create a high likelihood that the Tesla would follow a fixed path based on the map. This meant that the tesla would always annihilate escape on Box but ended up ping ponging on AI sat until it flings another Z-level on meta.

:cl: Robustin
tweak: Tesla movement is now completely random.
/:cl:

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by Robustin** [comment]
I was really tempted to call this a fix but I knew it would just cause drama.

**Review by Cyberboss — APPROVED** [review]

**Comment by Bawhoppen** [comment]
Good change

**Comment by Cyberboss** [comment]
Pretty sure there's an issue for this somewhere @Robustin

**Comment by Robustin** [comment]
@Cyberboss 

Wasn't able to find one, it's a common enough complaint but people kinda forgot about it after we switched to the SM.

**Comment by Slignerd** [comment]
At least now hopefully tesla won't always get stuck on the solars

**Pull request merged**
