### PR TITLE
Codename Frosty Saviour- A New Medbay for Metastation

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
A complete remap of medbay on Metastation.
metamedoverview

Comes complete with:
3 standard operating rooms, and a larger surgical theatre:
surgery
A new Primary Treatment Centre, with 4 stasis beds and ample space to work with and a new storage room, with borg charger:
treatmentandstorage
A new cryogenics room and a freezer, for organs, blood and oxygen tanks:
cryogenicsandclinic
A redesigned CMO office, and a new break room:
cmoandbreak
A new morgue and small room for paramedics:
morgueandparamedic
A small miscellaneous section, perfect for further expansion or projects:
miscmedbay
An altered chemistry factory:
chemistry
A redesigned virology lab:
virology
And a number of small maintenance secrets, ready for the enterprising assistant, engineer, or traitor. 
[No image provided]

All in all, my hope with this new medbay is to make medbay a little bit less cramped, and to give more space for treatment. Hopefully it also looks a bit better than before. Any suggestions, feel free to hit me with them.

## Why It's Good For The Game
Gives more treatment space for meta's medbay.

## Changelog
:cl:
add: Metastation's medbay has received a long overdue redesign/expansion. Have fun exploring it!
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
you have some decals under the walls in the room beneath plumbing

**Comment by Iatots** [comment]
Maybe a bit nitpicky, but could you have the sec checkpoint scrubber attach east like the vent? Would provide more room for cryo expansion, especially from people without piping device.

**Comment by Yenwodyah** [comment]
Suggestion: In the breakroom, remove the window and re-add the maint door. Or make the windows into those frosted ones you can't see through. Reason is because the old breakroom was a great place to do antag stuff and it sucks to have good antag rooms removed.

**Comment by AWalton** [comment]
Five morgue trays is a bit low, I'd swap the bottom table for two more trays.

**Comment by Anonmare** [comment]
CMO's Office looks like it's missing a Requests Console. It's the thing used to make desk announcments.

**Comment by EOBGames** [comment]
> CMO's Office looks like it's missing a Requests Console. It's the thing used to make desk announcments.

it's got one, just below the window

**Comment by kriskog** [comment]
The other departments are going to get jealous :(

**Comment by Tlaltecuhtli** [comment]
why a medical kiosk in the middle of a access locked room? maybe swap it wih a medvendor as there is only 1 and before there were 2

**Comment by kriskog** [comment]
Doctors can use it to scan patients. It gives more info than the standard health scanner.

**Comment by Angustmeta** [comment]
You removed my favourite hidden room in the game; the triple tile one above virology. The one-tile corgi room is good but I think you can fit another hidden room like that.

**Comment by Tharcoonvagh** [comment]
I love it, keep up the good work!

**Comment by Tlaltecuhtli** [comment]
what kind of info isnt seen from health + chem scan?  doctor telling the dude in crit to swipe his credit card on the machine so he can localize where is the ninja star stuck at is dumb

**Comment by Mark9013100** [comment]
Absolutely fantastic design, you've got talent.

**Comment by kriskog** [comment]
Doctors can scan patients for free tlal, go try one before you knock it.

**Comment by evilcyborgmrt** [comment]
Looks great. Paramedic room looks kind of empty though. Perhaps some lockers or a crew monitoring console?

**Comment by BadSS13Player** [comment]
This only makes Meta more superior to all other maps.

**Comment by EOBGames** [comment]
> This only makes Meta more superior to all other maps.

don't worry about that, I've got big plans. _Big. Plans._

**Comment by Angustmeta** [comment]
Nicely done with the new hidden room solution and plumbing holopad. But I think pharmacy now has two holopads unless I see wrong.

**Comment by trollbreeder** [comment]
Merge conflicts possibly due to that spacemanDMM PR.

**Comment by Tlaltecuhtli** [comment]
> Doctors can scan patients for free tlal, go try one before you knock it.

i click man with either my free analyzer or my i phone app why do i need something that does nothing better except if you upgrade it? a medvendor  there makes more sense so johnny mc richman can buy his patch of libidor without having to break into medstorage

**Comment by anconfuzedrock** [comment]
why does it still have that awkward two lobbies with zero desks setup?

**Comment by kriskog** [comment]
Test merged on event hall for a bit.

Seems viro is missing a cycling airlock

**Comment by PKPenguin321** [comment]
i seriously hope you do donutstation next, it needs it way more than meta tbh 😳

**Comment by kriskog** [comment]
Donut station has an active mapper (owner).

**Comment by MarioWizard119** [comment]
This is very nice. Reminds me of delta’s design, with all of the extra equipment, but it’s not unnecessarily huge. I do have one suggestion, in chem factory and the pharmacy, if you could please swap the tables and the chemical heaters so that all the important chem machines are within arms length? It’s one of the things that’s aggravated me about certain maps.

**Comment by SpinnerMaster** [comment]
This is fantastic, it fixes nearly every gripe I have had with Meta's existing layout. You even added a paramedic room!

**Comment by ExcessiveUseOfCobblestone** [comment]
No defib mounts please (techbound) and I would prefer the 2 bottom stasis get replaced with normal beds: the idea is you have room for more stasis beds but they're not provided by free. Really hate the 4 free beds in Pubby when they already handhold pretty bad.

Does the charger charge defibs? I've always used the cell charger.

**Comment by kriskog** [comment]
There should be a stasis bed per MD slot, and it being too strong is something that should be changed about the stasis bed itself (I have plans very soon).

Defib wallmounts shouldnt be tech bound, they are a plate bolted to a wall. With the shift to defib first, I think we should be facilitating efficient use of defibs in medbay. I did request those by the way.

**Comment by ExcessiveUseOfCobblestone** [comment]
I disagree, maybe a total of beds/optables. The focus of stasis should prob be shifted to a heavy focus on anti-decay rather than a catch-all for anything bad that might be occurring to the user so the doc can twiddle their thumbs. 

The mounts are techbound because they aren't just for security, they auto-charge the defib as well. I've never had to bother with recharging a default defib due to the mount. In their current state they should not exist as map defaults. If they were just to lock the defib in place for security I'd be fine with their existence.

**Comment by Yenwodyah** [comment]
You can't actually interact with the table at the top left corner of the office room, it's blocked by the water cooler and the photocopier

**Review by kriskog — CHANGES_REQUESTED** [review]
Cut a couple of the stasis beds and replace with beds, leave two of the surgeries unfinished. table frame in one instead of table, no board in computers in both? Gives it the impression of being in the process og getting built for now. Also some busywork for the docs, the room for the facilities will be the biggest upgrade this time around. We can revisit adding a full complement once stasis nerfs and surgery table rework goes in.

**Comment by Someone212280** [comment]
This makes the solar room not work properly.  Having the control computer next to the door makes it impossible to connect the solars to the SMES input and computer without also connecting to the rest of the station. It could be fixed by swapping the computer and SMES positions or putting the door on the east side of the room.

**Comment by trollbreeder** [comment]
maybe add 2 stasis bed circuit boards so med doesn't have to yell at sci for cryotech like miners do for mining tech?

**Comment by Victor339** [comment]
How about copying the desk with windoors here? Nicer for asking people why they want to enter medbay, plus it allows you to take deliveries or give items to others.

**Comment by trollbreeder** [comment]
after a bit of discussion with some lads, i have a medbay layout "mock up", maybe you could use it
image

**Review by kriskog — CHANGES_REQUESTED** [review]
Few mapping things that needs fixing before merge, I've let him know directly on discord.

**Comment by Mickyan** [comment]
Some minor thoughts after finally checking it out
- Built smoke machine at roundstart might be problematic, but the jukebox definitely is since it's a lag machine
- I miss the recovery room near surgery, there doesn't seem to be a room suitable for holding SSD people
- The screen overlay on the computer in the maint gamer den doesn't look right
-Those two biosuit lockers south of the freezer room just kind of seem in the way for no particular reason, put them nex to the iv drip maybe?

**Review by kriskog — APPROVED** [review]

**Comment by Angustmeta** [comment]
Needs a linen bin.

**Comment by Victor239** [comment]
The room between the primary treatment centre and storage room could have some beds and be the new recovery room.

**Comment by kriskog** [comment]
There is a room with beds near the three surgeries

**Pull request merged**
