### PR TITLE
Adds Ocular Shield, a new changeling ability

### PR DESCRIPTION
**Pull request by ghost**
When used, this will project a shield over the changeling's eyes. This shield, while obvious, will protect the changeling from most vision-damaging or impairing methods, such as flashes and welding tools.

It costs one DNA point.

### CODE REVIEW

**Comment by RemieRichards** [comment]
could just make it an eye augment using @Core0verload 's system-thingy.
that way it doesn't have to literally be a pair of glasses.

**Comment by Xhuis** [comment]
It's intentional to be glasses, so as to be obvious to observers and prevent other glasses from being warn.

**Comment by WJohn** [comment]
I think we should frankly just be upgrading the eye augment thing, too, make it cost 2 points, and not bloat up the changeling's abilities.

**Comment by Xhuis** [comment]
The main weakness of Augmented Eyesight is that it makes you _more_ vulnerable to flashes. Including this into it would make it counter-intuitive.

**Comment by AlexCrimson** [comment]
Oh boy, more murderbone-enabling ling changes.

**Comment by Xhuis** [comment]
How does this enable murderbone?

**Comment by Anonus** [comment]
AH YES, PEOPLE ADDING MORE ABILITIES TO CHANGELINGS, EXCELLENT, JUST WHAT CHANGELING NEEDS, YUP

**Comment by Iamgoofball** [comment]
@Anonus 
@AlexCrimson 

what happened to "changeling is weak and boring solo buff when?"

**Comment by Xhuis** [comment]
that's the exact reason i made this

**Comment by Bluespace** [comment]
Seems fairly weak. Does it offer flashbang protection? Will it prevent eyestab? Can I cover it somehow?

**Comment by Xhuis** [comment]
It protects against flashbangs vision-wise (not hearing, though) and protects against eyestab, too. It can't be covered - it's meant to be obvious.

**Comment by Anonus** [comment]
Changeling needs buffs, yes, but giving it more abilities isn't a buff unless the ability is very useful, see; headslugs, which are actively a detriment to the changeling that buys them as it fucking kills you 5ever to spawn a tiny mob that will die very rapidly.

**Comment by Cheridan** [comment]
I'm kinda with @Bluespace here, this seems really niche.

**Comment by Core0verload** [comment]
How about making it use a changeling version of my implant and merging it with Augmented Eyesight? You can enable thermal vision OR welding shield, not both at the same time.

**Comment by Xhuis** [comment]
Support for this seems low, so it's into the trash bin.

**Pull request closed without merging**
