### PR TITLE
Adds missing fire proof status to some items (Mining suit and paranormal hardsuits)

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Stuff that stops fire damage shouldn't burn up

### CODE REVIEW

**Comment by GunHog** [comment]
None of the hardsuits or any suit with heat resistance should burn up, TBH. This is still better than nothing!

**Comment by KorPhaeron** [comment]
The engineering ones already don't, not sure about others

**Comment by GunHog** [comment]
Two hardsuits have FIRE_SUIT_MAX_TEMP_PROTECT (emergency fire suit, which generally allows survival in a fire for about 2-3 minutes if it does not burn away first)
- Mining hardsuit
- Prototype hardsuit
I believe those two to be an oversight by Phil, as he changed a lot of things at once.

The standard Syndicate hardsuit probably should not be destroyed by fire either, although it does not provide any protection. Purely opinion.

**Comment by KingPhilipIII** [comment]
WAIT MINING HARDSUITS HAVE FIRE RESISTANCE?! I CAN WALK IN LAVA WITH IT?!

THIS IS A GAME CHANGER.

**Comment by GunHog** [comment]
No, you cannot. The change here simply **stops your suit from burning up when you are on fire.** You cannot walk into lava with it (but if you do, you will not lose the suit unless you drop it in the lava) and survive. 

That is the only change Kor is making here; Preventing certain suits from being destroyed by fire or being on fire **lava will still destroy them if they enter it.** (But will not be lost if you are wearing it) Do not walk into lava with a mining hardsuit and expect to survive!

**Comment by KingPhilipIII** [comment]
My elation has been crushed. Dreams shattered. 

My point still stands however. Why can miners get a voidsuit anyway? It makes them move slower, and while I'm sure it has better armor than the explorer suit normally, fighting in Lavaland is more about not getting hit outright.

**Comment by Supermichael777** [comment]
also if you have to lavawalk a short distance use an extingisher twice
 you will die before you can roll the fire out

**Comment by Kevak** [comment]
Miners can get a hardsuit because there _Are_ asteroids in space that have mats. That's what I assume

**Pull request merged**
