### PR TITLE
Restores runtime to his original look

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
A 30% chance at spawn to be a genetically modified cat.

runtime

:cl: Kor
rscadd: Runtime now has a chance to spawn with a more classic look.
/:cl:

### CODE REVIEW

**Comment by KazeEspada** [comment]
You mean...

a gcat?

**Comment by duncathan** [comment]
:+1:

**Comment by KazeEspada** [comment]
Is that an espeon?

**Comment by ATDoop** [comment]
Yeah, it's espeon. It's why Runtime sometimes says "Esp!".

**Comment by Cheridan** [comment]
original cat do not steal

**Comment by KazeEspada** [comment]
# COPYRIGHT

**Comment by RemieRichards** [comment]
@KazeEspada GCAT is just the 4 DNA bases
Guanine
Cytosine
Adenine
Thymine

**Comment by KorPhaeron** [comment]
Original runtime was an espeon that ran in place ripped from somewhere else.

This is just a purple cat

**Comment by Thunder12345** [comment]
\>his
You uncultured swine, Runtime is female. Also Jesus that is ugly, leave her alone!

**Comment by PKPenguin321** [comment]
i think it's neat

**Comment by Core0verload** [comment]
The sprite is really ugly.

**Comment by WJohn** [comment]
I can't examine the sprite more closely at the moment so I can't tell if it's good or not.

**Comment by Nienhaus** [comment]
@WJohnson The sprite looks fine to me, looks better than most the other
SS13 sprites but I don't think it'll be a major problem.

**Comment by Iamgoofball** [comment]
>used to be an espeon

so thats why "esp!" is in the words list

**Comment by Cheridan** [comment]
It looks fine. Only problem is that the length of the tail looks kinda funny.

**Comment by KorPhaeron** [comment]
@Cheridan 

You look kinda funny

**Pull request merged**
