### PR TITLE
Fixes a misplaced wallmed in deltastation

### PR DESCRIPTION
**Pull request by combustor**
## About The Pull Request
Fixes a wallmed
image

## Why It's Good For The Game
Makes it usable without having to go to maints

## Changelog
:cl: Guestify
fix: Fixes a misplaced wallmed in delta station
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
that seems kind of intentional actually? Why does the break room need its own wallmed?

**Comment by YakumoChen** [comment]
For assistants to purchase medication discreetly, obviously

**Comment by YakumoChen** [comment]
Its like asking why there's a guaranteed medibot assembly right next to the vendor

**Comment by combustor** [comment]
> For assistants to purchase medication discreetly, obviously
I don't see how that's obvious, nor have I seen anyone use or mention it.

If it is intentional, feel free to close this

**Comment by YakumoChen** [comment]
it's certainly more visible and more likely to see use in maint than in a oft-unused break room (of medbay, no less), so I don't see how it's good for the game.

**Comment by MrDoomBringer** [comment]
I think this is intended to be in maint

**Comment by combustor** [comment]
> it's certainly more visible and more likely to see use in maint than in a oft-unused break room (of medbay, no less), so I don't see how it's good for the game.

Fair enough, first time I saw it in maints it looked weird and out of place, but I suppose having it in maints instead of the break room is better

**Pull request closed without merging**
