### PR TITLE
Reverts nerf gun bullet sprites

### PR DESCRIPTION
**Pull request by ghost**
Feedback for the new bullet sprites is massively negative, and it makes silenced guns much less effective as the bullets are easy to see. This keeps the other changes from #11837 in but removes the bullet sprites that literally everyone but Steelpoint didn't want.

### CODE REVIEW

**Comment by Anonus** [comment]
They look like nerf darts!

**Comment by Lumipharon** [comment]
Steel didn't listen mang.

**Comment by WJohn** [comment]
Bullets definitely need SOME new sprite from what we had originally, because they're damn near invisible. At least make them darker so you can see them against tiles better.

**Comment by Lumipharon** [comment]
I unno, I cant see bullets in real life very well either.

**Comment by bustygoku** [comment]
Isn't the entire point of using bullets in this game that they're hard to see thus better at suppressing people because you can't dodge them as easily without a shitload of luck? There's something to be said about a fear factor behind bullets vs the slightly more sterile lasers that NT uses normally

**Comment by Iamgoofball** [comment]
the bullets worked when we combined them with pixel projectiles

>dont work with silenced guns

then make silenced bullets the default bullet

and how about instead of continuing to argue that bullet sprites being the same color as the floor is "balance" we make a new bullet sprite that actually looks good

**Comment by WJohn** [comment]
Yeah things being invisible isn't fun to play against, and is not a good balancing mechanic here when we already lack so much basic feedback.

**Comment by optimumtact** [comment]
If you have a specific issue with silenced weapons you can change that sprite but this PR seems strange.

People will always bitch about a change for the first few days, thats why you need to gather feedback for at least a week or two before actually reacting

knee jerk reverts don't help

**Comment by Xhuis** [comment]
The problem with the new sprites is that nobody wanted them merged in the first place. Unlike bloody footprints, which people thought was good, unless I'm mistaken nobody commented favorably about the new sprites.

**Comment by Lumipharon** [comment]
Why do we have genetics, ninja and alien invisiblity then?

There's a difference between literally invisible, uncounterable shittery (like the ninja), and DIFFICULT to see.
I've heard almost nill (if any)complaints about bullet sprites in my time playing.

Also the change pretty much got snuck in along what was supposed to be just a bug fix + new sprite for the steelrifle.

**Comment by Iamgoofball** [comment]
@Lumipharon people playing on stretch to fit like me because 32x32 is too small, and 64x64 requires 1080p when I have 2x 1440x900 monitors can't see jack shit in terms of bullets

**Comment by Lumipharon** [comment]
If it really is a balance concern to you (why do you have such puny monitors), at the very least it shouldn't have been part of a pr that was supposed to a bug fix + sprite change for a gun, where it was explicitly said to remove balance changes from the pr.

Semi related, but guns should totally have a muzzle flare thing, which very briefly illuminates (slightly) the tile the shooter is on. And lasers should do the same thing for the projectile itself.

**Comment by Iamgoofball** [comment]
because no one sane expected a bullet sprite to be a big fuckin balance change

**Comment by Lumipharon** [comment]
Because if you read up in this pr the arguments against reverting the change are game balance ones.

I originally argued against changing the sprite because nerfshot is ugly, not balance - because I didnt think anyone considered the bullet sprite we've had forever an issue.

**Comment by Steelpoint** [comment]
Realism aside I think people need to be able to clearly see bullets.

If there is a problem with silencer weapons showing bullets we can look into making them fire bullets that use the old sprite.

**Comment by bustygoku** [comment]
Why do people need to be able to clearly see bullets?

Is feedback a problem when you get shot? Add some sounds for getting shot or make the screen flash red. Add ricochet sounds when they hit walls.

Literally anything is better than nerfgun bullets.

**Comment by Steelpoint** [comment]
By that logic why would people be able to see lasers, or any other projectile?

**Comment by Iamgoofball** [comment]
@bustygoku 
Why do people need to be able to clearly see e-swords?

Is feedback a problem when you get hit with one? Add some sounds for getting hit or make the screen flash red. Add sparks and a sound effect when they hit walls.

Literally anything is better than lightsaber swords.

**Comment by bustygoku** [comment]
Jokes aside, sparks flying off of walls when you hit them with eswords kind of sounds awesome

**Comment by Dorsisdwarf** [comment]
:+1:

goof is just having PTSD flashbacks back to when everyone was trying to revert his own stuff, dont mind the shitpost.

**Comment by Steelpoint** [comment]
Improve don't remove>?>?>

Seriously if the sprites are too nerf like then simply make them look better.

I think having very visible sprites is a positive change.

**Comment by ike709** [comment]
>Improve don't remove>?>?>

What do you think this PR is doing?

:+1: Death to nerf bullets

**Comment by MrPerson** [comment]
A better sprite would be nice but I'd rather have a functionally good sprite that looks shitty than a good looking dysfunctional one (the old one).

**Comment by Firecage** [comment]
I would rather have the dysfunctional old sprite than the current functional ugly one.

**Comment by phil235** [comment]
Having clearly visible bullets gives more feedback to the players, it is definitely a plus. I don't find the new sprite particularly ugly tbh but if it's too nerf like then making them darker would solve the problem.

**Comment by Steelpoint** [comment]
I never found the sprites to be bad, it's not like they have a blue tipped end to them.

Irrespective of the sprite used I feel we should be able to easily see bullets, we can see virtually any other projectile in the game easily barring bullets.

Prehaps making guns that have a silencer on fire the more subtle bullets might be a interesting approach.

**Comment by Dorsisdwarf** [comment]
Cough Cough It's Because Guns Were Never Intended To Be As Common As They Are Now

**Comment by Steelpoint** [comment]
More so we now have Gang mode where they heavily use ballistics as well, also the newer meta of using pistols and revolvers for traitors more often. In addition to the auto rifles.

**Comment by Cookiesndip** [comment]
Steelpoint - when I said that visibility for the bullets for the autorifles was a contributing factor in making it OP, I didn't mean to nerf every insanely expensive syndicate/gang ballistic by changing them from having a surprise/visibility factor to justify their high price (9 - 13 fucking TC) and limited ammo (no extra ammunition to begin with, and extra ammo costing crazy amounts of metal). I meant to only visually nerf the 4 free powerful autorifles security gets at roundstart, because anything that is standard issue shouldn't be as powerful as the autorifles are.

Why do you always do this?

**Comment by Steelpoint** [comment]
Dammed if I do, dammed if I don't. When I suggested only auto rifles take the new bullet sprites people called me out on making the guns snowflake in comparison to other auto rifles.

I still think all ballistics should have a obvious sprite. But we'll wait and see what the maintainers think.

**Comment by bustygoku** [comment]
Bullets are supposed to be hard to see so they're more subtle and harder to dodge if they're flying down a hallway offscreen, imo.

Then again, they used to be used by almost only syndicates, the people who relied on getting the jump on targets, COUGH COUGH

**Comment by Xhuis** [comment]
How about this:

* I have sidearms and low-med caliber guns use the old bullet sprites.
* Higher-caliber guns, like the SAW and the auto-rifles, use tracer bullets (i.e. the current sprite).

**Comment by Lumipharon** [comment]
"tracer rounds" Are not big yellow tubes.

Also steelrifles are only 9mm.

Please just revert this awful change, and then if people still have problems with the sprites that have existed for years yet never brought up, a pr specifically for changing it can be brought up.

**Comment by bustygoku** [comment]
I have to agree. Wasn't it like a hot issue with this codebase and coders bundling unrelated changes?

**Pull request merged**
