### PR TITLE
Makes it so that every shields can be shieldbashed, not just riot shields. Take Two

### PR DESCRIPTION
**Pull request by Singul0**
## About The Pull Request
This PR adds shieldbashing to every single shields, not just riotshields specifically. Various different sounds is made depending on the type of shield you shieldbash.

Also adds an energy shieldbash sound, for the e-shields. by editing the shieldbash.ogg.
## Why It's Good For The Game
It always bugged me why you could only shieldbash using riot shields specifically, even though there's really should be nothing stopping you from being able to do it on every shield types. This PR makes it so that the shieldbash feature is consistent across all shields, not just the riot shield specifically. reducing snowflake code.
## Changelog
:cl:
sound: adds sounds for energy shieldbashing
code: Shieldbashing feature is now consistent across all shield types
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
isnt this an element? /datum/element/disarm_attack

**Comment by optimumtact** [comment]
this was supposed to be a sec buff.

**Comment by alien3301** [comment]
Sec are usually the only people with shields anyway

**Comment by nikothedude** [comment]
and botanists

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
He's talking about the sound that you make when hitting a shield with a baton, not the element that lets you shove people with shields.

**Pull request merged**
