### PR TITLE
Readds the custom font option on goon chat

### PR DESCRIPTION
**Pull request by lzimann**
Client sided fonts, no harm.

### CODE REVIEW

**Comment by RandomMarine** [comment]
Now I can spessmen in daedric.

**Comment by PraiseRatvar** [comment]
Now I can spessmen in terminal.

**Comment by juanototo2** [comment]
Now I can spessmen in Wingdings.

**Comment by RandomMarine** [comment]
You can already spessmen in wingdings though.

**Comment by Iamgoofball** [comment]
@Cyberboss 
You still haven't explained why you removed this.

**Comment by ChangelingRain** [comment]
Players who want to make their game experience worse are not welcome here.

**Comment by PraiseRatvar** [comment]
what

**Comment by obscolene** [comment]
@ChangelingRain so why are you here

**Comment by Iamgoofball** [comment]
@Cheridan 

So far this feature has been:

1. silently removed with no reasoning provided to anyone
2. closed with vague reasoning

can this get reopened

**Comment by PKPenguin321** [comment]
Wait what why was this closed

**Pull request closed without merging**
