### PR TITLE
Changing bartender security icon + shoes to laceups

### PR DESCRIPTION
**Pull request by okaw**
Bartender requires schway soles. Bartender receives schway soles.

### CODE REVIEW

**Comment by Supermichael777** [comment]
Balance destroyed.:+1:

**Comment by Bawhoppen** [comment]
the barman isnt supposed to be fancy hes supposed to be a dunker :-1:

**Comment by Anonus** [comment]
This doesn't change the shoes the bartender spawns with, only the picture in the security records.

**Comment by okaw** [comment]
Whoops. Now I feel like a goof

**Comment by tkdrg** [comment]
Sure why not

**Pull request merged**
