### PR TITLE
Moves Meta drone bay to the main cargo bay

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

MetaStation's Drone Bay has been moved to be basically inside the normal cargo bay.
image

This bay starts slightly more prepared than others. You're still rewarded for going out of your way to set up exoscanners but now it's not literally obligatory, to reduce the effort entry cost.

To make room for it, the security cargo post was moved to the east of the mailing room:
image

The drone bay spot in maintenance has been cleared out by a gang of rowdy assistants, and turned into a drug den.
image
It also has a nod to its prior room usage up north with some misc. drone bay stuff.

This is my first real map PR and is likely to have dumb oversights.
## Changelog

> MetaStation's Drone Bay has been moved to be basically inside the normal cargo bay.

On all stations Drone Bay is shunted off into some ass corner where nobody even notices it exists. After using it a bunch I've realized it has some interesting cargo use cases, because it's a cooldown based activity you can often have it on in the background while doing other things. I wished to move it inside the bay to highlight its usefulness!

> To make room for it, the security cargo post was moved to the east of the mailing room:

The mail room is rather big for being such a non-used part of the station, so it won't be harmed by being trimmed down into the main five chutes. I've tried to keep everything important on the tables, but do let me know if I fucked up and missed something.

I also think it's funny to symbolize how Security has a weak hold on Cargo by having its security office almost completely cut off from the main area, but that's a post-hoc rationalization if anything.

> The drone bay spot in maintenance has been cleared out by a gang of rowdy assistants, and turned into a drug den.

Had to make use of the empty space somehow. This is a little funny den that might kickstart some hijinks. Meta's maint is pretty bland and hasn't had any real shakeups in a very long time, so adding a new PoI might cause some fun events.

:cl:
add: MetaStation's Drone Bay has been moved to be basically inside the normal cargo bay.
add: To make room for it, the security cargo post was moved to the east of the mailing room:
add: The drone bay spot in maintenance has been cleared out by a gang of rowdy assistants, and turned into a drug den.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
I wanted to do something similar to more stations but I wasn't ready for how exhausting one map change would be.

**Review by MrMelbert — COMMENTED** [review]
Good PR

Don't forget to remove that sign / change the door to a maintenance door / update access if necessary / remove that wayfinder landmark

image

**Comment by carlarctg** [comment]
> Good PR
> 
> Don't forget to remove that sign / change the door to a maintenance door / update access if necessary / remove that wayfinder landmark
> 
> image

The exodrone poster and door type are intentionally left there as a callback but I can undo that if that's a problem (It's always been AA)

**Comment by MrMelbert** [comment]
I guess you can keep the sign but I don't think the door color should stay it'll just confuse people

**Comment by carlarctg** [comment]
> While I'm not strictly opposed to this change, it does make it more challenging for assistants to easily do drone bay work with their roundstart access, which is a function of the maint drone bays I've always appreciated and with cargo being such a hotbed of mischief and potential weapons acquisition, not every HoP or QM is willing to give John Greyshirt the benefit of the doubt.

literally has never happened in the history of ever

**Comment by carlarctg** [comment]
cargo chat literally never ever usef ever

**Comment by MrMelbert** [comment]
> While I'm not strictly opposed to this change, it does make it more challenging for assistants to easily do drone bay work with their roundstart access, which is a function of the maint drone bays I've always appreciated and with cargo being such a hotbed of mischief and potential weapons acquisition, not every HoP or QM is willing to give John Greyshirt the benefit of the doubt.

to be honest I don't think "allowing assistants to tide into the drone bay" should be a design goal

**Comment by Admiral-Gigaton** [comment]
Im less so excited by cargo drone moving over, and more excited about DRUG LAB RP WOOOO

**Comment by TheVekter** [comment]
Yeah okay

I might actually have to learn how this feature works now

**Comment by axelzonvolt** [comment]
the sprite of the drug den APC doesn't match the other APC's featured in the other pictures. it IS the same type as the rest of them, right?

**Comment by Oxotnak** [comment]
Sec post actually feels like a second sec checkpoint from arrivals

**Comment by carlarctg** [comment]
> the sprite of the drug den APC doesn't match the other APC's featured in the other pictures. it IS the same type as the rest of them, right?

clueless

**Comment by carlarctg** [comment]
> Sec post actually feels like a second sec checkpoint from arrivals

it is what it is

**Comment by Iajret** [comment]
image
office chair missing? i mean, back in 2024 every single workplace enforced you to stand for the entirety of work day, but we are in a bright future now, arent we?

**Comment by carlarctg** [comment]
> image office chair missing? i mean, back in 2024 every single workplace enforced you to stand for the entirety of work day, but we are in a bright future now, arent we?

sadly nanotrasen forgot so the last shift moved it to the drone bay

**Pull request merged**
