### PR TITLE
Now renders external bodyparts on inorganic limbs

### LINKED ISSUE #60782: Android wings (maybe skeleton, maybe angel) are invisible but still function
## Round ID:
Tested downstream on Fulpstation

## Reproduction:
Become android usually through magic mirror

Drink wing potion and notice invisible but functioning wings

BONUS: Putting on a heck suit does not give you the normal message of your wings being covered and still function, and allowed me to freely move around in space. This wasn't tested with the new heck suit but it probably still works the same

### PR DESCRIPTION
**Pull request by Time-Green**
closes #60782

:cl: 
fix: external bodyparts now render on inorganic bodyparts (androids have visible wings)
/:cl:

### CODE REVIEW

**Comment by Mooshimi** [comment]
If this is good to go, please change closes to fixes in the first pr comment

**Comment by JohnFulpWillard** [comment]
this doesnt have the changes I made in #61570

**Comment by Mooshimi** [comment]
> If this is good to go, please change closes to fixes in the first pr comment



> this doesnt have the changes I made in #61570

It should be easy for them to just pull from upstream, right?

**Comment by JohnFulpWillard** [comment]
> It should be easy for them to just pull from upstream, right?

its just a merge conflict so they can probably just fix it in the browser, I just want to point it out so it doesnt get accidentally removed.

**Comment by necromanceranne** [comment]
honestly it'd be easier to just redo this pr yourselves if this has been sitting around so long without a merge conflict fix.

**Comment by Time-Green** [comment]
I'm not going to fix the merge conflict, sorry. I am starved for time as is and I don't feel comfortable webediting very sensitive code without some serious testing

Anyone should feel free to make a new PR with the fixed code

**Pull request closed without merging**
