### PR TITLE
MORE AUTISTIC BRAIN DAMAGE STUFF

### PR DESCRIPTION
**Pull request by ghost**
:cl: 
add: a few more autistic brain damage lines
/:cl:

### CODE REVIEW

**Comment by Kromgar** [comment]
addendum to feature freeze: Stop adding brain damage lines

**Comment by factoryman942** [comment]
Are the second and third indented or am i insane

**Comment by optimumtact** [comment]
fix the spacing

**Comment by Chronitonity** [comment]
fix them not being funny

**Comment by optimumtact** [comment]
@Chronitonity a bit late for that now

**Comment by Chronitonity** [comment]
its okay i still love you

**Comment by WJohn** [comment]
this is one day going to get more lines than any other file.

**Comment by Supermichael777** [comment]
all the other lines are done with spaces, change them all to tabs

**Comment by optimumtact** [comment]
this file is formatted to the js prettyprint standard, please abide by the restrictions

**Comment by nicbn** [comment]
Maybe in the future we will have 1MB only of brain damage lines.

**Comment by lzimann** [comment]
These are kinda bad

**Pull request closed without merging**
