### PR TITLE
Rename the beach hut to something with a little more colour

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by Cheridan** [comment]
sorry, encourages erp

**Comment by Core0verload** [comment]
There is a FUCKING MAP FREEZE going on, have anybody noticed it?

**Comment by optimumtact** [comment]
Fuck big whoop, if what's his face wants to refactor air turfs he should write some regex or other processor to do the map edits for him

**Comment by Impisi** [comment]
I propose we make the beach huts name randomized like the bar sign. That way we can have cuckshack and loveshack

**Comment by PKPenguin321** [comment]
Cuck shed*

**Comment by bgobandit** [comment]
*color

**Comment by Buggy123** [comment]
I think we should just remove the name entirely and be done with this mess.

**Comment by Impisi** [comment]
The people want memeshack.

**Comment by PKPenguin321** [comment]
the people want cuck shed

**Comment by Supermichael777** [comment]
Can we not?

**Comment by MMMiracles** [comment]
Make it pull from a list of names so we can have all the names.

**Comment by KorPhaeron** [comment]
Try again after the freeze

**Comment by optimumtact** [comment]
Excuse me I opened this before the freeze but they closed my branch

**Pull request closed without merging**
