### PR TITLE
Removes the shitty red faction poster and replaces it with two new ones.

### PR DESCRIPTION
**Pull request by theOperand**
What it says on the tin. New posters are space cube and backdoor xenos

xenoposter
cubeposter

### CODE REVIEW

**Comment by RemieRichards** [comment]
carrying on from the last PR, if you need to change the order of a state in a dmi:
* Copy it
* Click the state BEFORE the position you want it to go in
* Paste
* Delete the original you copy+pasted

**Comment by GunHog** [comment]
>Actual Xeno Porn

@WJohn must be pleased.

**Comment by bgobandit** [comment]
:+1:

maybe switch 34 and 36

**Comment by Miauw62** [comment]
why would i switch poster numbers

**Comment by Miauw62** [comment]
anyway i reorganized the dmi to be less messy

**Comment by duncathan** [comment]
The joke is rule 34 I think

**Pull request merged**
