### PR TITLE
Fixed hot coco and chocolate milk recipe conflict

### LINKED ISSUE #55587: Hot Coco and Chocolate Milk have a recipe conflict.
## Reproduction:

Try to make hot coco. Cry because chocolate milk steals the show.

```
/datum/chemical_reaction/chocolate_milk
	results = list(/datum/reagent/consumable/milk/chocolate_milk = 2)
	required_reagents = list(/datum/reagent/consumable/milk = 1, /datum/reagent/consumable/coco = 1)
	mix_message = "The color changes as the mixture blends smoothly."

/datum/chemical_reaction/hot_coco
	results = list(/datum/reagent/consumable/hot_coco = 5)
	required_reagents = list(/datum/reagent/consumable/milk = 5, /datum/reagent/consumable/coco = 1)
	required_temp = 320
```

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Fixes #55587.
Chocolate milk now requieres a sweetener. It is now mixed with milk, coco and sugar in 2:1:1 proportions or with milk, coco and astrotame in 40:20:1 proportions. 
Alternative to https://github.com/tgstation/tgstation/pull/55606.

## Why It's Good For The Game
Hot coco is now obtainable, chocolate milk recipe is changed in a way that makes sense (real chocolate milk usually has sweeteners). The astrotame recipe exists for consistency and to prevent future changes to the avaibility of sugar making chocolate milk extremely expensive to make in large amounts.

## Changelog
:cl:
fix: Chocolate milk has two new recipes: 2 milk : 1 coco : 1 sugar and 40 milk : 20 coco : 1 astrotame (60 units instead of 61). This makes hot coco obtainable.
/:cl:

### CODE REVIEW

**Comment by Donkie** [comment]
Isnt there a unit test that checks all recipes for impossible reactions?

**Comment by interestingusernam3** [comment]
>Isnt there a unit test that checks all recipes for impossible reactions?

If one exists it's clearly broken.

**Comment by Jared-Fogle** [comment]
hm, wouldnt it make more sense to make it so change the hot coco recipe to require heating chocolate milk?

**Comment by Jared-Fogle** [comment]
> Isnt there a unit test that checks all recipes for impossible reactions?

image

**Comment by MrMelbert** [comment]
hot cocoa can be made in game right now if you pre-heat the ingredients, yes. if you don't pre-heat it makes chocolate milk, if you do pre-heat it makes hot cocoa

**Comment by TemporalOroboros** [comment]
It would probably be more interesting to add a pair of reactions converting between hot chocolate and chocolate milk at the given temperature.

**Comment by LemonInTheDark** [comment]
Chose one, no point in keeping this open

**Pull request closed without merging**
