### PR TITLE
admin fax notifications

### PR DESCRIPTION
**Pull request by kawoppi**
## About The Pull Request
The idea of fax notifications was brought up [on the forums](https://tgstation13.org/phpBB/viewtopic.php?p=650996#p650996). This PR lets admins VV edit a fax machine in order to receive notifications for it.

View the variables of a fax machine and set `notify_admins_on_recieve` to 1 to receive notifications for it.

When this machine receives a fax a notification shows up in the info chat tab (same as prayers). You can also jump to the receiving machine so you can read the freshly faxed message.

Received faxes also show up in the request manager so you can keep track of who's been sending you faxes and when.

Fax machines with `notify_admins_on_recieve` enabled will have a green send button. Syndicate network machines will still show up red even with `notify_admins_on_recieve` enabled.

## Why It's Good For The Game
Fax machines make for an interesting form of communication between the station and centcom. Getting notified of incoming messages makes it much easier for admins to engage with players using fax machines. This way they don't need to wait at the machine or risk missing a message.

## Changelog

:cl:
admin: setting notify_admins_on_recieve to 1 on a fax machine allows you to receive notifications about incoming faxes in the info chat tab and the requests manager
/:cl:

### CODE REVIEW

**Comment by Striders13** [comment]
so brave

**Comment by twilightwanderer** [comment]
It's funny, but I literally just got into the business of being able to send faxes to the administration.
изображение

**Comment by twilightwanderer** [comment]
@kawoppi If you want to do the implementation, I would recommend doing the following:
- the ability to fill in administration sending addresses through a special list, so that upstreams can conveniently edit factions for their needs.
- make it possible to open and close visibility through an emag or card with captain access. Fax with access can be destroyed and it should be left possible to restore access.
- make the administration panel so they can reply to a message or send messages to any fax with a custom name.

**Comment by kawoppi** [comment]
It seems your implementation has more functionality to it so I think I'm gonna close this one

**Comment by twilightwanderer** [comment]
> It seems your implementation has more functionality to it so I think I'm gonna close this one

I'm sorry, I didn't mean to take away from your development, I was just hoping to help.

**Comment by kawoppi** [comment]
> I'm sorry, I didn't mean to take away from your development, I was just hoping to help.

Oh don't worry about it! I'm lazy and don't feel like adding much more to this PR yet. If you're making something that can also notify admins of faxes and with extra functionality on top of that then I think it's more useful to go with that instead.

**Pull request closed without merging**
