### PR TITLE
Adds a new map to the game

### PR DESCRIPTION
**Pull request by Kmc2000**
:cl: Kmc2000
add: Added a station smaller than two dorm rooms put together 
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

https://www.youtube.com/watch?v=1by0-nkKOTs

You thought my other pr was small didn't you
You thought that even that was unusably small on 50 pop
In fact, I thought https://github.com/tgstation/tgstation/pull/39363 was as small as I could physically make a station.
This one comfortably fits inside of cramstation.

It's new, it's small
And it's more efficient than ever.

A layer by layer comparison of the two stations:

This abomination not only fits into dorms:
It fits into two dorm bedrooms

The holodeck is about twice as big as this station:

This requires a bit more testing, but it worked on my machine.

### CODE REVIEW

**Comment by Kmc2000** [comment]
If you manage to beat this size, please reference this pr

**Comment by Qustinnus** [comment]
all you need is damn daniel hidden in your pr somewhere now

**Comment by Kmc2000** [comment]
Excuse me this is a serious PR

**Comment by plapatin** [comment]
he actually did it the absolute madman

**Comment by plapatin** [comment]
@Kmc2000 better go update those floor tiles

**Comment by Kmc2000** [comment]
Holy shit what this isn't dead??
Necro of the century

**Comment by optimumtact** [comment]
we have too many maps @Cyberboss finish your out of tree map thing

**Comment by Kmc2000** [comment]
Et tu, orange?

**Comment by plapatin** [comment]
no fun allowed

**Pull request closed without merging**
