### PR TITLE
PSHOOM

### PR DESCRIPTION
**Pull request by optimumtact**
PSHOOOOOOOOOOM

### CODE REVIEW

**Comment by Cheridan** [comment]
wow rude

**Comment by optimumtact** [comment]
PSHOOOOOOOOOOM?!?!?!

**Comment by PKPenguin321** [comment]
oh boy we can add our own inside jokes to the retard phrases now?

add mine, it's a pretty dank inside joke, it goes "Squirt squirt ring ring"

**Comment by optimumtact** [comment]
Sorry no player references allowed PKpenguin

**Comment by Cheridan** [comment]
PSHOOOM is the hottest new up-and-coming meme PKpenguin. We're just jumping on the bandwagon early.

**Comment by optimumtact** [comment]
PSHOOMMMMMMMMM is ready to PSSSHHHHHHHHHHOOOOOOOOOOM

**Comment by optimumtact** [comment]
PSHOOOM you very much

**Pull request merged**
