### PR TITLE
Add message to indicate infinite pizza

### LINKED ISSUE #64563: Infinite Pizza Bug
## Testmerges:

Round ID: [177547](https://scrubby.melonmesa.com/round/177547)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 935497a893364cfcb9f120e507dfc9ae8f09497d
The following pull requests are currently test merged:
#64280: 'Ballistic to Energy: Autorifles for Thermal Pistols' by necromanceranne at commit 0b61cefe06
#64448: 'Subsystems now track their avg and last tick allocations' by MrStonedOne at commit 2b60f7c0e9
#64500: 'Fix the mc getting completely fucked in the brain due to background ticker subsystems' by MrStonedOne at commit 21edc2e412

Local commit: 1f475ef74f23c46febb488ce74cc9b546fe04431
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

1. Order pizza from console
2. Receive pizza
3. Open box (I used default Z button) and get out pizza
4. Close the box (dont scrap it) (again, I used Z button)
5. return to step 3

Video: https://youtu.be/9oXcnDVqQXo

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

Fixes #64563

This adds a text description when infinite pizza is generated.

## Why It's Good For The Game

Less people creating bug reports for things that are intended.

## Changelog

:cl:
spellcheck: Add a message when infinite pizza is generated.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
imo this kind of ruins the mystery and vagueness of the infinipizza appearance but it's probably better to have at least this

**Review by MrMelbert — APPROVED** [review]

**Comment by cacogen** [comment]
Don't ruin it. Subtle magic like this is divine. If people are too dumb to realise they're too dumb to realise

**Comment by timothymtorres** [comment]
> Don't ruin it. Subtle magic like this is divine. If people are too dumb to realise they're too dumb to realise

You have the luxury of being a coder and code diving to discover this.  The rest of the playerbase does not.  Mooshimi already said there were several players ahelping about it because there is nothing in game to indicate the pizza should be doing this.

**Comment by cacogen** [comment]
I learned of this when somebody in-game was showing it off. You can tell it's different by examining it and seeing all the damage resistance messages showing it's indestructible. There's also a Centcom announcement that has a 50% chance to happen after it arrives.

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/460f5bebf7668204e1653ff0f47ec6f3ea95ac4e/code/modules/cargo/packs.dm#L1958-L1962

This still won't stop players from spamming bug reports thinking this is a bug.  You said yourself that someone had to show you it was intended since the lack of information doesn't indicate this.

**Comment by cacogen** [comment]
No, I said that somebody showed me there was an infinite pizza box you could get in pizza crates. That message hints at its existence. You ruin the magic of it by adding a message.

**Comment by AdipemDragon** [comment]
actually, I just realized, if this is made to happen everytime the pizza is re-oppened, it might get a bit chat spammy, is there a simple method to have it happen something like once per player seeing it for the first time?

**Comment by cacogen** [comment]
I thought it was a Centcom announcement. But you’re right, it’s a piece of paper at comms consoles only a few people will see. 

If it were an announcement more people would get why the box was producing infinite pizza, but then everyone would eventually know about it. The tell-don’t-show message this PR is adding is preferable.

Does it have to say “what the hell?” though? It’s very editorial. Can’t it just say something like, “There’s another pizza in the box!” and only if you’ve A) Opened it before and B) This is your first time reopening?

**Comment by Ryll-Ryll** [comment]
There's a simple solution to this: keep a running count of how many times it's been bitten, and roll `if(rand(bites_taken_since_revelation * 3))` on each bite to add one of a few random messages that read like `...wait a moment, how have you not even put a dent in this yet?` and `...why is there still so much pizza?` to the bite message, and reset the bite counter.

That way it's not overly spammy, and it implies that it takes a few chomps to actually notice the infiniteness of the pizza.

**Comment by YakumoChen** [comment]
> There's a simple solution to this: keep a running count of how many times it's been bitten, and roll `if(rand(bites_taken_since_revelation * 3))` on each bite to add one of a few random messages that read like `...wait a moment, how have you not even put a dent in this yet?` and `...why is there still so much pizza?` to the bite message, and reset the bite counter.
> 
> That way it's not overly spammy, and it implies that it takes a few chomps to actually notice the infiniteness of the pizza.

The box is infinite, not the pizzas

**Pull request merged**
