### PR TITLE
Changes a few messages nobody will bother to translate

### PR DESCRIPTION
**Pull request by ChangelingRain**

### CODE REVIEW

**Comment by Jordie0608** [comment]
`How hard is it to use a Driver that only takes two seconds to invoke?` into `How hard is it to use a Sigil, anyway? All it takes is dragging someone onto it.`

`How do they fail to use Dementia Doctrine, anyway?` into `How do they fail to use a Sigil of Accession, anyway?`

**Comment by ChangelingRain** [comment]
highly concealed lore

**Comment by Razharas** [comment]
Very inportant inded

**Comment by Razharas** [comment]
YOLO

**Pull request merged**
