### PR TITLE
Cabin Away Mission

### PR DESCRIPTION
**Pull request by KazeEspada**
Nestled in a tranquil forest is a wonder cabin hotel where the spacemen's can come to relax, play arcade games, talk, burn rubber, and DIE.

Featuring:
5 Large Hotel Rooms perfect for ERP(except for the windows and lack of door locks). They have carpets not shown in the pictures.
A fully stocked kitchen, bar, theatre, and medbay.
An eight ATV garage.
A convenient riot shotgun in the manager's office.
A sawmill, capable of gibbing the most foolish assistant, along with three chainsaws to harvest the forest.
Lastly, a RAGE CAGE. SO THAT BLOODY TOPLESS GREYSHIRTS CAN FIGHT EACH OTHER LIKE ANIMALS IN THE SNOWY WILDERNESS.

Also, the first map ever to use a procedurally generated terrain.
cabinfarshot
ragecage
lumbermill
frozen_lake

### CODE REVIEW

**Comment by Zilenan91** [comment]
sounds cool :+1:

**Comment by YakumoChen** [comment]
sounds fun but I feel like it will turn out similar to hotel where nobody ever uses it because 'there's no mission to go on, it's just an empty bunch of nothing'

**Comment by KazeEspada** [comment]
The saw mill gibs people, and theres a gibber that you can steal for traitory stuff. Also, this is better then nothing.

**Comment by WJohn** [comment]
This looks like hotel 2.0

That's not a good thing.

It also has the standard complete lack of detail that all away missions have, *which you should not be mimicking, it is shit mapping to do that*.

Where are all the wires, pipes, APCs, tile details and so on that the station has? Why is it that away missions go for the BARE MINIMUM of stuff? It's infuriating to look at.

An away mission should not meet the prerequisite of "it can be loaded without error" and be left at that. Raise the bar!

**Comment by TehZombehz** [comment]
Inb4 this is used to recreate the entire story from "Until Dawn." Also, sasquatch suit when?

**Comment by RemieRichards** [comment]
@WJohn this is a wooden shed.
why would it have area power controllers, and giant magnetic batteries?
it's a SHED.

**Comment by KazeEspada** [comment]
Its a cabin actually. Not a shed. Lumbermill is apcless. Cabin has one apc in maint.

**Comment by RemieRichards** [comment]
Any wooden building, regardless of size, is just a glorified shed.

**Comment by KazeEspada** [comment]
Also, how much detail can i pit into wood floors? Carpets?

**Comment by KazeEspada** [comment]
I'm gonna add bunnies, some carpets, and name the doors. Then, it should be ready.

**Comment by Ultimate-Chimera** [comment]
Woah. :+1:

**Pull request merged**
