### PR TITLE
[READY]Removes the 1 brute damage from organs (you can now hit people with tongues without killing them)

### PR DESCRIPTION
**Pull request by silicons**
Why is this even a thing?
I just want to spam tongues on everyone :(

### CODE REVIEW

**Comment by A-t48** [comment]
Does this still let you hit people with arms and legs?

**Comment by kevinz000** [comment]
It should, as they're bodyparts and not organs

**Comment by pubby** [comment]
`force = 0` is inherited from `/obj`; just remove the line it's redundant.

**Comment by kevinz000** [comment]
ah thanks

**Comment by kevinz000** [comment]
time to practice good pring and tag all my prs

**Comment by A-t48** [comment]
# **HUMAN HARM**

**Comment by A-t48** [comment]
Uh, that comment was totally supposed to go on the peaceborg changes. Oh well.

**Comment by Cheridan** [comment]
fine i guess??

**Pull request merged**
