### PR TITLE
Debug outfit updates

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Adds a new debug ID card with all the accesses and the cargo budget linked. Old one was missing ID console and syndicate access, and had the ERT commander name.
Adds cells to the tiered testing BRDPEDs.
Adds debug glasses, NV mesons with reagent scan, sec, med and diag hud. Alt click to toggle xray.

If you need other stuff added, let me know.

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
Add these as random maint loot with the spawn chance of 1%

**Comment by Ziiro** [comment]
Can't wait until these appear in Christmas presents next month

**Comment by kriskog** [comment]
Christmas is the best :grin:

**Comment by AdmiralPancakes1** [comment]
on the topic of the debug outfit, is there any reason why it uses a syndicate elite hardsuit and not an ERT hardsuit? I always end up swapping it out because the ERT suit is radproof and has no slowdown

**Comment by kriskog** [comment]
Because denton made it a syndie suit when he initially made it. Syndie suit has toggleable helmet for movespeed.

As for rad immunity, last time I changed it around I removed the geiger ticking from the debug suit, but kept rad armor where it was. I don't want to make the outfit immune to anything else, since it is intended for testing and world feedback is important for that.

That said, I might swap it out. Let me consider it.

**Comment by TheChosenEvilOne** [comment]
Change the RCD to the admin version

**Comment by Exavere** [comment]
**Admin Abuse Laughter Intensifies** But for real thanks for the update.

**Pull request merged**
