### PR TITLE
Fixes some atoms conduct electricity flag

### LINKED ISSUE #83229: Captains sabre doesnt conducts electricity
## Issue Summary
Sabre has 2 obj_flags var so it doesnt conducts electricity

## Round ID:
I didnt test it but i saw the code

### PR DESCRIPTION
**Pull request by RengaN02**
## About The Pull Request
Fixes: https://github.com/tgstation/tgstation/issues/83229
I think this code was done this way by a little mistake, and a metal sword should conduct electricity anyway (right?).

Gif
## Why It's Good For The Game
its a fix
## Changelog
:cl: Rengan
fix: Officers sabre and grilles now conducts electricity as it should.
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
it has a leather hilt so I don't think it would conduct electricity to your arm.

**Comment by RengaN02** [comment]
> it has a leather hilt so I don't think it would conduct electricity to your arm.

you are right but also fireaxe conducts electricty, it has wooden handle

screwdriver conducts electricity but it has plastic

**Comment by ShizCalev** [comment]
image
Another wrong one. 

Caused by #80033

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Get grilles too please.

**Comment by RengaN02** [comment]
> Get grilles too please.

👍

**Pull request merged**
