### PR TITLE
[WIP][DNM] PDA slots

### PR DESCRIPTION
**Pull request by ghost**
PDA slots, everyone!

:cl: More Robust Than You
add: PDA slots
/:cl:

for some reason i can't put shit into them, help please

### CODE REVIEW

**Comment by lzimann** [comment]
They already go on ID, belt and pocket slots, I can't see why you would need an extra special slot for it.

**Comment by Grazyn** [comment]
slot creep, it's an old chestnut

**Comment by jughu** [comment]
>port from paradise

**Comment by cebutris** [comment]
Don't forget that most suit storages can take PDAs

**Comment by kevinz000** [comment]
why are you trying to reimplement the ID slot owo

**Comment by kevinz000** [comment]
The only way this would be interesting is if ID didn't go into PDA and that seems like making PDAs less useful and making pda bombs weaker (they don't delete your ID if it's not in the PDA!).

**Comment by GunHog** [comment]
Unnecessary. This has no gain over the ID slot, and is therefore unnecessary.

**Comment by pudl** [comment]
awful idea, isnt this in bay though?

**Comment by KorPhaeron** [comment]
Uneeded and you should focus on your current prs before opening more unfinished ones

**Comment by Cyberboss** [comment]
Bad PR

**Comment by pudl** [comment]
isnt there a 24 hour rule 🤔

**Comment by Cyberboss** [comment]
@KorPhaeron 's gone rogue

**Comment by KorPhaeron** [comment]
I guess I could just put DNM and leave it open for a day and close it if thats become the new standard

**Comment by pudl** [comment]
yeah at least let MRTY argue his case and give him a chance

**Comment by KorPhaeron** [comment]
Sounds like a waste of time for everyone involved when there are 60 other prs that need attention and Cheridan has previously said no more inventory spots

**Comment by KorPhaeron** [comment]
KorPhaeron: Cyberboss can I still close PRs that have no justification in the OP without waiting 24 hours
Cyberboss: fine

**Comment by PraiseRatvar** [comment]
8 dislikes, yeah i think mrty would understand why this would be closed

**Comment by kevinz000** [comment]
mrty if you want to be serious about this there has to be strong justification of why people need a separate pda slot when your pda already goes in ID slot because there is currently literally none in the entire codebase.

**Pull request closed without merging**
