### PR TITLE
Fixes problems with icon overlays

### LINKED ISSUE #24951: Runtime in overlays.dm,137: Cannot read ''.dir
Runtime in overlays.dm,137: Cannot read ''.dir
usr: Amanda Clark (kofyan) (/mob/living/carbon/human)
usr.loc: The floor (140,136,1) (/turf/open/floor/plasteel/bar)

### PR DESCRIPTION
**Pull request by Cyberboss**
Icons don't have dirs

Also fixes the blood runtimes

Fixes #24951

@MrStonedOne @AnturK

### CODE REVIEW

**Comment by Poojawa** [comment]
This doesn't work. it breaks inhands updating.

**Comment by Cyberboss** [comment]
Hmmm

**Comment by optimumtact** [comment]
yooooooooooooo

**Comment by Cyberboss** [comment]
I literally have no idea why...

**Comment by Cyberboss** [comment]
@MrStonedOne thoughts?

**Comment by MrStonedOne** [comment]
No idea, how exactly are inhands broke?

**Comment by optimumtact** [comment]
@Poojawa care to extrapolate?

**Comment by Poojawa** [comment]
Oh hm. double checking the report I got pointed towards this, but a second double check just now was actually someplace else, my mistake!

**Comment by optimumtact** [comment]
We might run this through a test merge first before merging

@MrStonedOne

**Comment by DaxDupont** [comment]
udgagmt 1
It broke all the things

**Comment by Poojawa** [comment]
Hooray! I'm not crazy!

This time anyway.

**Comment by optimumtact** [comment]
@Cyberboss can you fix this? I will hold up all your other pr's until this is done reeeeeeeeeeeeee

**Comment by Cyberboss** [comment]
finnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnne

**Comment by Cyberboss** [comment]
Testmerged fine

**Pull request merged**
