### PR TITLE
Removes unneeded overhead from datum pooling

### LINKED ISSUE #12149: Performance and Odd Redundancy: Pooling
Currently with pooling, the specific datum/atom's Destroy() is called then the vars are resets on it.

That said, what makes zero sense is that when an atom/datum is pulled *out* of the pool the variables of it are reset again. This seems unnecessary as the vars were already reset prior to it being placed in the pool--likewise, its' not really possible for the vars to be modified while it's in the pool.

Performance wise, resetvars is actually quite expensive, so calling it twice on the same object/datum incurs significantly more overhead.

It makes sense to be cautious, but making a process more expensive than it should be (particularly when the whole aim of this system is to increase performance) seems a bit odd.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Protip: I did this from my phone
Fixes #12149

### CODE REVIEW

**Comment by clusterfack** [comment]
Implement my resetvariables performance increase. It limits looping in resetvars to a max of vars.len instead of vars.len * excluded.len, and removes initial.

**Comment by Fox-McCloud** [comment]
@clusterfack 

Care to link us, please?

**Comment by Razharas** [comment]
I pointed this thing out in @MrPerson pr but it was stated that its ok

**Comment by Fox-McCloud** [comment]
@Razharas 

Yeah, I remember you doing that and was concerned about it, too--I didn't know, until later, how damn expensive ResetVars was.

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/pull/5155/files

```
/datum/proc/createVariables()
	pooledvariables[type] = new/list()
	var/list/exclude = global.exclude + args

	for(var/key in vars)
		if(key in exclude)
			continue
		pooledvariables[type][key] = initial(vars[key])

/datum/proc/resetVariables()
	if(!pooledvariables[type])
		createVariables(args)

	for(var/key in pooledvariables[type])
		vars[key] = pooledvariables[type][key]

**Comment by Fox-McCloud** [comment]
@clusterfack 

Thanks man; much appreciated!

**Comment by Miauw62** [comment]
<+MrStonedOne> I once coded a pr on my phone while taking a dump at mcdonalds

**Pull request merged**
