### PR TITLE
alright who added a literal fucking fursuit, I WANT NAMES

### PR DESCRIPTION
**Pull request by Iamgoofball**
# THERE WILL BE BLOOD

### CODE REVIEW

**Comment by Iamgoofball** [comment]
This is merely a setback

**Comment by PsyCommando** [comment]
hasn't that been there for ages?

**Comment by calzilla1** [comment]
Isnt more like a footsie pajamas than a furfag suit?

**Comment by PKPenguin321** [comment]
its more like wearing the skins of your enemies edxcept they're corgis

**Comment by Poojawa** [comment]
Fursuits are fauxfur anyway.

**Pull request closed without merging**
