### PR TITLE
Babel virus

### PR DESCRIPTION
**Pull request by AnturK**
I was bored.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
This is pretty cool but probably a complete and irreversible round ender as written.

**Comment by Jordie0608** [comment]
But it's not accessible to players whatsoever.

**Comment by PKPenguin321** [comment]
This seems neat, should be brought back as a Level 5 Biohazard virus and restore original languages on cure

**Comment by KorPhaeron** [comment]
I didn't realize this also gave languages back on curing I agree this would probably work as a random event or wizard virus @AnturK 

I'd like to merge it if thats okay with you

**Comment by AnturK** [comment]
Sure, but you might want to wait for #26776 so i only have to redo this once.

**Comment by coiax** [comment]
We also have to check that having no languages doesn't cause runtimes

**Comment by Iamgoofball** [comment]
@KorPhaeron if you made the curator immune it would actually be pretty interesting

**Pull request closed without merging**
