### PR TITLE
Removes shuttle manipulator

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
This is backporting some improvements I made when porting tg shuttles to TGMC, the loading of shuttles shouldn't rely on a machine and instead should be done by the subsystem.  The shuttle manipulator ui will become an independent ui.

## Why It's Good For The Game
No longer will the game break without the shuttle manipulator and this hopefully is a QOL improvement for admins.

## Changelog
:cl:
admin: Removes shuttle manipulator.
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
Wait that machine *actually matters?*

Huh I thought it was just for show

**Comment by Dawson1917** [comment]
> 
> 
> Wait that machine _actually matters?_
> 
> Huh I thought it was just for show

it's for ordering admin-only and removed shuttles (escape shuttle and syndi, pirates, cargo, etc.) as well as fast travelling them

**Comment by Fikou** [comment]
wont this break centcomm map since that has manipulator

**Comment by spookydonut** [comment]
> 
> 
> wont this break centcomm map since that has manipulator

The typepath for it still exists I'll leave that to others to remove.

**Comment by ishitbyabullet** [comment]
Will it still be as easy to replace or place shuttles like before? It shouldn't be **ONLY CODERS WILL GET THIS** hard.

**Comment by spookydonut** [comment]
> 
> 
> Will it still be as easy to replace or place shuttles like before? It shouldn't be **ONLY CODERS WILL GET THIS** hard.

instead of clicking the shuttle manipulator you click open shuttle panel in the admin panel and get the exact same interface as before

**Comment by ishitbyabullet** [comment]
@spookydonut Oh.

Who uses the shuttle manipulator in centcom anyways? I thought it was just a cool decoraiton that has a neat gimmick function for admins.

Nevermind my concerns then

**Comment by ishitbyabullet** [comment]
Dude, don't remove it. That thing looks like it took a lot of effort to make and it's a cool decoration.

**Comment by SpaceManiac** [comment]
Thanks so much for doing the work to fix this, it's so dumb and bad that all this functionality is tied to a specific object sitting in CentCom.

I would encourage making the machine visual-only and leaving it there.

**Comment by spookydonut** [comment]
Done

**Comment by Addust** [comment]
you REALLY could've named it 'Removes shuttle manipulator machine and moves UI into admin panel'

**Comment by davethwave** [comment]
Tad late. Heck, four years too late at that...

**Pull request merged**
