### PR TITLE
Ordnance and Xenobiology QoL's for Wawastation

### PR DESCRIPTION
**Pull request by Singul0**
## About The Pull Request
Makes a couple of QoL additions to science sub-departments in Wawastation, The main part of the additions is adding a tramstation-esque oxygen chamber for more oxygen (especially important for the station's unique 3x3 burn chamber) into Ordnance.

But also adding critical need-to-have equipment for Ordnance and Xenobiology:
1. firefighting closet in ordnance itself
2. boxes of syringes and beakers 

image
## Why It's Good For The Game
Wawastation's ordnance is _this_ close to being a perfect ordnance room for an ordnance main, especially the 3x3 burn chamber. But the critical lack of a large oxygen supply makes the burn chamber more of an hinderance more than anything, this PR adds a large pool of oxygen chamber that ordnance can draw from to make use of their burn chamber most effectively. (while yes, there is a canister o2 tank hidden in maint, with the port located in the often forgotten auxillary storage with a non-descript green pump. due to the location and positioning of the tank and connector being horrible (I had to open up the map editor to notice it) it's pretty horrible to use, needing heavy overhaul or a bunch of tedious work to get the oxygen from the tanks to the burn mix)

There's also a lack of some critical equipment you need to use to do much of anything:
1. Firefighting closet in ordnance (mostly just the suit to modify the burn chamber scrubbers)
2. Beakers and syringes (this is the more pressing issue, considering how secluded xenobiology is to the rest of the station. procuring them is a massive hassle)
## Changelog
:cl:
qol: adds an oxygen chamber for wawastation ordnance
qol: adds some missing critical items needed to do ordnance and xenobiology
/:cl:

### CODE REVIEW

**Comment by Singul0** [comment]
I think I fucked the map...

**Comment by mc-oofert** [comment]
looks cramped and bad

**Comment by Singul0** [comment]
image
touched it up a teensy tiny bit

**Comment by MoonDeer728** [comment]
what the hell is wawastation

**Comment by JohnFulpWillard** [comment]
> what the hell is wawastation

A map in rotation

**Comment by MoonDeer728** [comment]
> > what the hell is wawastation
> 
> A map in rotation

why again?

**Comment by JohnFulpWillard** [comment]
Because we merged the PR that made and added it

**Comment by Ghommie** [comment]
Fix the merge conflicts and it'll be merged.

**Comment by Singul0** [comment]
> Fix the merge conflicts and it'll be merged.

@Ghommie Fixed!

**Comment by mc-oofert** [comment]
> Fix the merge conflicts and it'll be merged.

merge my cooler one

**Comment by Ghommie** [comment]
I had to merge one or the other and they looked both pretty ok so it was chance.

**Pull request merged**
