### PR TITLE
HERETICS: ASH ASCENSION NO LONGER KILLS THE USER

### LINKED ISSUE #52396: Heretics are killed by their own ash ascension ability
#### Round ID:
[142442](https://scrubby.melonmesa.com/round/142442) Basil. 

#### Reproduction:

1. Observe Mitch Jones successfully ascend as ash heretic. 
2. He activates his fire aura and nearly instantly enters crit and dies.

### PR DESCRIPTION
**Pull request by Djiq**
## About The Pull Request
OHS HIT OH FUCK OS HIT OF UCK. BIG BAD ON MY SIDE. 

## Why It's Good For The Game
Fixes #52396
Ash ascension abilities will not burn you to death anymore :agony:

## Changelog
:cl:
fix: Ash ascension no longer kills user.
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
typo in your changelog

**Comment by Iatots** [comment]
hmm so with the last commit, the eye of the storm is safe? Intersting...

**Comment by ATH1909** [comment]
speedmerge

**Comment by nightred** [comment]
This looks like it fixes #52396

**Comment by Dennok** [comment]
But now it dont burn mobs under/over you

**Pull request merged**
