### PR TITLE
Animated Spellbooks

### PR DESCRIPTION
**Pull request by Nabski89**
:cl: Spellbooks Take 2
imageadd: Magical Spellbooks are now animated.
/:cl:

[why]: Because magical books should have some magical effects.

cursebooks

See https://github.com/tgstation/tgstation/pull/37524 for where I was bad at making commits for comments.

### CODE REVIEW

**Comment by Ordonis** [comment]
Superb title, fellow contributor

**Comment by improvedname** [comment]
It kinda is animated too fast honestly atleast for forcewall and knock and instant summons i want to play the game in peace not get a seizure from it because i found a forcewall spellbook

**Comment by MrDoomBringer** [comment]
yeah i would slow anims on these by about half

**Review by WJohn — APPROVED** [review]
Harmless enough, sure.

**Comment by BlueNothing** [comment]
I thought this meant 'sentient' or 'staff of animation compatible' spellbooks, not spellbooks with an added graphics component.

**Pull request merged**
