### PR TITLE
Treaty of Paris of 1783

### PR DESCRIPTION
**Pull request by Iamgoofball**
fixed the problem

### CODE REVIEW

**Comment by Bawhoppen** [comment]
The Treaty of Paris isn't really the best example actually

**Comment by Iamgoofball** [comment]
the joke

your head

**Comment by SgtxRootbeer** [comment]
this is a creative way of solving the issue tho.
👍 good job, you weren't a fucking meme for once

**Comment by Bawhoppen** [comment]
no the joke doesn't go over my head because the US didn't exist formally before the treaty of paris don't give me that

**Comment by Bawhoppen** [comment]
yet armor american spelling did exist before this PR it doesn't make sense

**Comment by Dorsisdwarf** [comment]
Call it the treaty of Donk Repository 69 for all I care

**Review by Cyberboss — CHANGES_REQUESTED** [review]
No because performance

**Comment by Tacolizard** [comment]
will this lag the server if someone spams a giant text block of the word 'armor'

**Comment by CosmicScientist** [comment]
Just do a check on the string for any u's and on a 50%, remove them.

Then do a check on the string for any s's or zeds and on a 50%, swap them all to being one alone.

**Comment by RemieRichards** [comment]
@CosmicScientist that wold zre be fn

**Comment by Razharas** [comment]
>([^\s|o]+o)(r[fla\W]) => $1u$2 

for making things right
>([^\s|o]+o)u(r[fla\W]) => $1$2

 for making things wrong

**Comment by Iamgoofball** [comment]
>regex

wont that be even more costly

**Comment by Razharas** [comment]
>Caring about cost in a meme pr

You have sunk too low from the apex of the meme king's throne
Step it up

**Comment by RemieRichards** [comment]
Regex is not required, the find, replace, etc. procs that DM has for text *USE* regex internally.

**Pull request closed without merging**
