### PR TITLE
 Reebecult: Joan stealing things Xhuis hasn't finished yet edition

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
experiment: Clockcult now spawns on a massive base that they have to defend.
rscdel: Removed the Prolonging Prism scripture.
rscdel: Removed the Application tier; all scriptures in it have been moved to Scripts with appropriately adjusted costs.
rscdel: Removed the Tinkerer's Cache scripture and moved Replica Fabricators from Script to Driver.
rscadd: Sigils of Transmission now automatically drain power into a global power storage that clockwork structures will automatically use from.
balance: Sentinel's Compromise now uses Vitality to heal, and healing done without enough Vitality will be much less effective, converting 75% of the damage healed to toxin damage.
tweak: Vitality and Power are now tracked in the global alert.
balance: Vanguard now lasts for 25 seconds, from 20, stuns for 30% of the stuns absorbed, from 25%, and no longer stuns for double the time if a large amount of stuns were absorbed.
balance: Sigils of Transgression now stun for 3 seconds(if the target has no Belligerent) and apply Belligerent for 7 seconds.
experiment: Ocular Wardens now attack all nearby non-Servants, applying Belligerent and producing small amounts of Vitality.
balance: Changed Ocular Warden damage per second from 13.5 to 4. Changed Ocular Warden health from 25 to 60. Ocular Wardens will now produce Vitality equal to damage done.
wip: Ocular Wardens will still attack mechs at a rate of 25 damage a second, but will, obviously, not produce Vitality from those attacks.
imageadd: Ocular Wardens have new sprites.
balance: Geis bindings no longer decay faster if not pulled by a Servant.
tweak: When a person bound by Geis crosses a Sigil of Submission, the Geis binding will anchor itself and decay slower.
tweak: Removing Geis bindings is no longer instant and can be done by any Servant with a slab, not just the initiator.
wip: Geis no longer prevents you from taking actions, but you remain unable to recite scripture while the target is bound. In addition, dealing damage to a bound target will cause the bindings to decay much more rapidly.
balance: Cyborg Servants casting Geis will have bright purple eyes.
rscadd: You can now remove sigils by hitting them with a clockwork slab for a small refund.
balance: All cyborg Servants now have a cyborg fabricator, a ratvarian spear, and a normal, not-limited slab that has two cyborg-unique scriptures bound.
rscadd: Replaces Function Call and Fellowship Armory with Arcane Armory, a script scripture with the same cost as Function Call.
tweak: Arcane Armory permanently gives you the ability to summon and dismiss a Ratvarian spear(Summon Spear) and a set of clockwork armor(Call Cuirass). These abilities will follow you across mind transfers such as cloning, though you will only receive them if you are able to hold the spear.
balance: Ratvarian spears now last until dismissed or until thrown at someone and broken. Breaking a Ratvarian spear by throwing it at someone puts the Summon Spear action on a 30 second cooldown.
balance: Being hit with clockwork armor on will increase the duration of Vanguard slightly; 1.5 seconds with a full set of armor.
balance: The Ark of the Clockwork Justicar no longer needs to consume 15 of each component after being summoned to properly activate. Changed invokers required to summon the Ark from 6 to 3.
tweak: Clockwork Obelisks are now a Script rather than an Application, and their cost has been accordingly adjusted.
balance: Changed Obelisk gateway cost from 2000W to 1500W.
tweak: Spatial Gateway is now a Driver rather than an Application, and the cost has been accordingly adjusted.
balance: Spatial Gateway can now target and teleport to the Ark of the Clockwork Justicar.
tweak: Judicial Visors are now a Script rather than a Driver, and their cost has been accordingly adjusted.
tweak: Wraith Spectacles have had their vision decay rate massively reduced and their cost has been accordingly adjusted.
tweak: Tweaked component requirements for several scriptures.
/:cl:

space station 13 2017-08-16 132848

Welcome to Reebe, motherfuckers.

### CODE REVIEW

**Comment by optimumtact** [comment]
Xhuis is still testing his, please wait

**Comment by Xhuis** [comment]
As a point of thought, if you actually, you know, tried to help with what's existing already and cooperate instead of making your own completely different version, it might have helped a bit.

**Comment by ChangelingRain** [comment]
Realistically, the only one dealing with strife is you.

**Comment by optimumtact** [comment]
Joan are you okay?

**Comment by Cheridan** [comment]
its pretty basic etiquette to not do a similar but competing massive overhaul at the same time as someone else...

**Comment by Iamgoofball** [comment]
I found Joan:

**Pull request closed without merging**
