### PR TITLE
Stops defibs/cloners notifying suicides when people are trying to revive them

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Leave me alone I died on purpose

### CODE REVIEW

**Comment by Bawhoppen** [comment]
remove suicide status when

**Comment by SouDescolado** [comment]
Suicides because "hur dur i'm not antag" should be punished, or at least limited. Antag tokens exist for this.

**Comment by Dorsisdwarf** [comment]
Aren't maxed cloners able to clone suicides? I seem to remember that being added.

**Comment by Bawhoppen** [comment]
yes they can but if you suicide you don't want to be cloned anyways

**Comment by KorPhaeron** [comment]
>Aren't maxed cloners able to clone suicides? 

But why

**Comment by Dorsisdwarf** [comment]
I think goofball added it for t4 cloner

**Comment by KorPhaeron** [comment]
But why

**Comment by tkdrg** [comment]
it's goofball
don't expect logic
if you don't like it you can remove it

**Pull request merged**
