### PR TITLE
Door can now crush mech, dealing damage, just like with mobs.

### PR DESCRIPTION
**Pull request by phil235**

### CODE REVIEW

**Comment by WJohn** [comment]
Neat. It'd be nice to see doors unable to close if there was ANY dense object in them.

**Comment by Jalleo** [comment]
Thanks phil

**Comment by GunHog** [comment]
Not very useful, as it does not stun a mech and the damage is pretty weak. But, I am not against it.

**Comment by Jalleo** [comment]
Can mechs be stunned?

**Comment by Steelpoint** [comment]
No, mechs are unstunable. 

Best example is a Ion Gun, a hit from a Ion Gun will stun a Silicon but it won't stun a Mech, conversely a Ion Gun deals a lot more damage to a Mech than a Silicon.

**Comment by WJohn** [comment]
Oh, very nice then. Keep up the good work!

**Pull request merged**
