### PR TITLE
Allows removing materials from shell dispensers

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: You can now retrieve materials inserted in a Drone Shell Dispenser with a crowbar.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
can't wait for the SS drone armada to come in at full force to -1 this pr since they can no longer roundstart join scientist to fill the machine before committing suicide.

**Comment by Shadowlight213** [comment]
:-1:
:^)

**Comment by Militaires** [comment]
Did someone say putting the full stacks in the drone machine then suiciding?

:^)

**Comment by Shadowlight213** [comment]
I think they said replace the drone machine with the preloaded version :^)

**Comment by Militaires** [comment]
I think they said put all of rnd, EVA, robotic and engineering's metal and glass into the dispenser :^)

**Pull request merged**
