### PR TITLE
Adds a martial artist gi to the AutoDrobe.

### PR DESCRIPTION
**Pull request by dessysalta**
## About The Pull Request
On a dark and stormy night, @Cheshify asked in OOC if anyone would be down to make a martial arts gi of no known origin for an event idea they had.

Naturally, I decided to put my talent (CITATION NEEDED) to use, and I have both sprited and coded in (the latter with the help of Cheshify ofc) the aforementioned gi of no known origin.
<details>
<summary>Picture</summary>

gokuss13

</details>

## Why It's Good For The Game

image

## Changelog

:cl: dessysalta, Cheshify
add: Nanotrasen has added a martial artist gi to the AutoDrobe for those who want to go even further byond.
imageadd: Aforementioned gi sprites.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
finally a byond reference

**Comment by Shadowflame909** [comment]
I'm glad it wasn't a plain white one. Now time to tc trade for a recolored brimstone beam and I am WinRAR.

**Comment by dessysalta** [comment]
> I'm glad it wasn't a plain white one. Now time to tc trade for a recolored brimstone beam and I am WinRAR.

it's worth mentioning i want to make a recolorable version sometime down the line (or maybe even right now, if it's that easy). when that comes, prepare for even FUNNIER jokes featuring nondescript martial artists

**Comment by Cheshify** [comment]
I know this project did **drag on** a little longer than intended, but you stayed on the **ball** when it came to spriting. This is **super** work!

**Review by Imaginos16 — APPROVED** [review]
HEY, ITS ME, G- THE SPRITETAINER HERE TO APPROVE THE PR!

**Comment by optimumtact** [comment]
Finally, we have returned to byond's spiritual home and can make DBZ fan rips

**Pull request merged**
