### PR TITLE
Refactors Navigational Beacons

### LINKED ISSUE #38064: Navbeacons: can't be built/deconstructed
- Underfloor bot nav beacons (/obj/machinery/navbeacon) can't be built/deconstructed.
If just one beacon is sabotaged/broken, all patrolling bots will start pathing back and forth between the last intact one and the second to last one.

- There is no overview of roundstart beacon names and their transponder codes. If someone changes a beacon's name/transponder codes, there is no way to find out the proper ones short of opening the map file and looking for its `codes_txt` and `location`.

### PR DESCRIPTION
**Pull request by Profakos**
## About The Pull Request

This PR refactors navigational beacons. In detail, this PR does the following:

**General Interactions**

- You can now print boards. They are unlocked at Basic Robotics Research, and can be printed both at engineering and robotics.
- The constructed machine requires no stock parts. When constructed, the floor tile pops up, so you can actually interact with the device from the get go.
- Made interacting with it more standardized, you no longer have to screwdriver it to access the interface, instead you just click on it.
-  Screwdrivering is instead part of the regular screwdriver -> crowbar deconstruct process. However, you have to unlock the maintenance hatch through the UI first.
- You can now use wallets too, to unlock the control interface, using the GetID() proc.
- Interacting with tools uses balloon alerts where its possible.

**UI Interactions**

- New tgUI interface!
- Previously, you could put in anything as codes, and there was no guide in game about what codes and values were valid. This has been replaced by buttons with pop up text boxes, checkboxes and dropdowns.
- You can also reset the code values to roundstart values, or to blanks, if the beacon had none.
- InterfaceLockNoticeBox  component allows the silicons to unlock the controls

**Other backend changes**

- Autodocs vars and procs in the navigational beacon file.
- Added defines for the various nav beacon codes.
- The freq var on beacons and the beacon_frequency var on robots did absolutely nothing, so I have removed them, along with the map varedits, and the frequency define. Maybe in the future one can readd them, to make bots that only patrol specific areas (though you can still do that with good next patrol location tagging).
- Mulebots were using the navbeacon's direction itself to figure out the direction they have to put down crates, instead of the direction tag. Now the tag actually works, allowing me to remove a bunch of varedits. I did keep the beacon's direction as a fallback, in case no direction tag is set, which should be South always.
- I audited and touched up the directions tags that were not in line with the previous beacon directions (which caused things such as the mule trapping themselves behind the crate.
- Sadly, making it use the default screwdriver construction means it is no longer transparent in maps editors :pensive:

image

## Why It's Good For The Game

Closes #38064 . More items being constructable is more fun, and its better if you can use an item without checking the map about how it is supposed to work.

## Changelog

:cl:
refactor: Refactored navigational beacons, making them constructable, deconstructable, and generally easier to use
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
Christ this made me realize we gotta update that beacon sprite
I might do that later since it seems easy enough

**Comment by Profakos** [comment]
Oh, that would be nice. Also, I am going to remove the transparent sprites, as they will be fully unused.

**Comment by jlsnow301** [comment]
Good pr. I'd like for you to convert this to typescript and break the ui into subcomponents, it's a little verbose. 

Let me know if you need help doing this (via disc)

**Comment by Profakos** [comment]
Yeah sure, I can do that. I'll put this on draft until that is finished.

**Comment by Profakos** [comment]
I have broke it up a bit. I considered making a component for the buttons themselves, not sure if it is neccessary as it would still be verbose if i moved all those inputs into Props, but if you want to, I can do it, could be a good generic components.

**Comment by jlsnow301** [comment]
> I have broke it up a bit. I considered making a component for the buttons themselves, not sure if it is neccessary as it would still be verbose if i moved all those inputs into Props, but if you want to, I can do it, could be a good generic components.

much better ty

generic components a little bit overkill for the request, it's pretty good as is

**Comment by jlsnow301** [comment]
let's save this from merge conflict hell

**Comment by DAKKA-WAAAGH** [comment]
This is fantastic, thank you!

**Pull request merged**
