### PR TITLE
Merge skew mondays second merge skew

### PR DESCRIPTION
**Pull request by Time-Green**
This #72799 skewed with one of the AI PRs

MERGE SKEW MONDAYSSSSS

Shit also just shouldnt register signals in a getter

### CODE REVIEW

**Comment by Time-Green** [comment]
there is another

**Comment by Time-Green** [comment]
I have no idea why linters are going off but this fixes the merge skew

**Comment by Mothblocks** [comment]
image
??????????????????????????

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/pull/72893

this broke linters. its failing linters on master. how was this not picked up

**Comment by Mothblocks** [comment]
it failed linters when it was merged too. how the fuck did you auto merge it?
image

**Comment by Mothblocks** [comment]
image

**PLEASE DO NOT FORCE MERGE PULL REQUESTS WHEN WE ARE IN A MERGE SKEW OR YOU WILL CAUSE MORE**

**Comment by Time-Green** [comment]
> image
> 
> # **PLEASE DO NOT FORCE MERGE PULL REQUESTS WHEN WE ARE IN A MERGE SKEW OR YOU WILL CAUSE MORE**

OH GOD IM SORRY
also that makes 2 merge skews and one time green skew

**Comment by Mothblocks** [comment]
thats not a merge skew thats merging a pr that was broken

**Comment by Time-Green** [comment]
> thats not a merge skew thats merging a pr that was broken

yes a timegreen skew

**Comment by Time-Green** [comment]
I wont merge PRs anymore during a skew, I was so focused on the integration tests I missed the linters

**Comment by LemonInTheDark** [comment]
don't listen to big headcoder they just want ci to pass instead of wanting your health and success.
any pr can be merged, if it's broken you should force the codebase to bend to your will rather then vice versa

**Pull request merged**
