### PR TITLE
Re-adds title4 as lobby music

### PR DESCRIPTION
**Pull request by Buggy123**
Why was this removed in the first place? Reverts #28882.

[This is the song in question.](https://www.youtube.com/watch?v=QoUC23vl0y8) Though the ingame version is shortened.

:cl: 
Add: Nanotrasen has reviewed the Productivity Playlist used to invigorate crew before their shift starts, and noticed that a disgruntled employee removed a popular track. The track has been re-added, and the employee in question has had SpacePods surgically attached to their ears and set to loop the track.
/:cl:

### CODE REVIEW

**Comment by davethwave** [comment]
This be blessed.

**Comment by LemonInTheDark** [comment]
image
This person is always perfectly correct, and I agree wit- oh.

**Comment by JJRcop** [comment]
This sound is released under [CC BY-NC-SA 3.0][cc-license] and can be found on [Bandcamp][bc-page]

[cc-license]: https://creativecommons.org/licenses/by-nc-sa/3.0/
[bc-page]: https://bandcamp.zhaytee.net/track/absconditus

**Comment by wesoda25** [comment]
I like the song but the reasons for removal are valid. Its not fitting for a roundstart song bc its just building and won't go anywhere in the time given. 

imo much better suited as a song to be played while you're in space

**Comment by PKPenguin321** [comment]
no!

the "screeEEEEEEEEEEEEEE" at the start gave me ptsd

**Comment by kopoba** [comment]
@Buggy123 since you doing great work can you review ability to add https://shutterstacks.bandcamp.com/track/space-asshole to lobby?

**Comment by Farquaar** [comment]
This would probably better not as a lobby theme, but as an end-game theme when antagonists get greentext.

**Comment by optimumtact** [comment]
if you can get it added to the server via policy, then you can get it in the codebase.

**Comment by Twaticus** [comment]
pour one out for the dead homie

**Pull request closed without merging**
