### PR TITLE
adds documentation to autoimplanter code

### PR DESCRIPTION
**Pull request by PKPenguin321**
When this was suggested in the original pr I thought it was a joke but now I see the importance of it

### CODE REVIEW

**Comment by JJRcop** [comment]
This is hilarious

**Comment by A-t48** [comment]
I was...just about to propose adding a single use version of one to RD. :( Why?

**Comment by GunHog** [comment]
Because we would not be ALLOWED TO HAVE THEM if they did not require surgery!

**Comment by optimumtact** [comment]
This would only make sense if people actually read the comments

**Comment by PKPenguin321** [comment]
Please reopen this, at least this way whenever someone tries to open a PR to add these to R&D we can point them to this to shut them down without the need for further bickering

**Comment by PKPenguin321** [comment]
this wasnt a joke pr

**Comment by optimumtact** [comment]
no

**Comment by PKPenguin321** [comment]
It's happening again

https://github.com/tgstation/tgstation/pull/24344

Reopen this, it's a serious PR

**Comment by PKPenguin321** [comment]
SCREEEEEEEEEEEEEEEEEEE https://github.com/tgstation/tgstation/pull/38483

**Pull request closed without merging**
