### PR TITLE
only captain and centcomm commander now have loud headset

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
tweak: only the true leader of the station can use loud radio
/:cl:

yes cmo and rd arent that important to have them being loud 24/7 on radio and when 3-4 people have bold text at the same time it just makes bold text bad and less unique
they still have announcements which is fine enough for them
before: "somone with loud radio said "help maint" and then died must have been the cmo or some other useless head"
now: "oh shit that person is loud he must be the captian"

discussion forum thread here: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=22137 please keep what regards loudness in general  there while whats relevant to this speicifc pr here

### CODE REVIEW

**Comment by zxaber** [comment]
AI should keep it. It can be _very_ hard to herd the kindergartners we call a crew to fight a blob without large text.

You can always order an AI to stop abusing their bigtext.

**Comment by subject217** [comment]
AI shouldn't keep it, they have inflated egos and need to be taken down a notch

**Comment by Cyprex** [comment]
I disagree greatly with this, there are plenty of heads who use it responsibly. The AI especially needs it, and we already give them vox announcements and trust our players not to abuse it, why shouldn't they have loud voice?

**Comment by Arianya** [comment]
Yeah this is a bit kneejerk and random. At most there are 6 heads of staff (and a couple of spare headsets) and in situations where you have that many heads of staff being able to distinguish yourself is important.

**Comment by Cyprex** [comment]
If you are worried about heads of staff turning it on roundstart and never turning it off you could limit the amount they can use it. This could be achieved by putting a cooldown on the loud voice or better yet, Giving you, say, power for 5 messages at most, with +1 message per minute or some other interval of time if you have less than 5 stored.

**Comment by HomocidlePancakes** [comment]
Have heads being able to talk **LIKE THIS** only on their departmental channel. Have Cap and AI keep it as it is.

**Comment by nemvar** [comment]
AI should keep it. Loads of people already confuse pAIs, borgs and the AI on the radio. We should not make that worse. You are just salty that gooboi didn't turn his off.

If only you could mark a PR as an IC issue...

**Comment by imsxz** [comment]
99% of the time heads of staff have nothing of use to say and the other 1% they can use their desk announcement

**Comment by Cyprex** [comment]
@nemvar You can, it's called "I DED"

**Comment by necromanceranne** [comment]
I've had to repeatedly switch to loud text just to get a point across as AI because sometimes stuff gets missed in radio chatter, and you really do need to have people listen to you in an emergency situation. While the captain is important, the AI is actually integral to station co-ordination and communication and requires it. Otherwise the eye in the sky will get ignored. 

I've been told repeatedly to use loud text more often because I have a habit of not using it when I should.

Also, is nuke ops leaders retaining loud mode?

**Comment by Tlaltecuhtli** [comment]
ais can use announcements

**Comment by ATH1909** [comment]
Why not make the non-captain head of staff headsets have text that's bigger than normal text, but smaller than the captain's headset's text? 

I personally don't think that any change to the size of headset text at all is necessary, but that idea that I just proposed would be less painful than your idea, IMO.

**Comment by Tlaltecuhtli** [comment]
@HomocidlePancakes you can already talk in bold by adding !! at the end of your message

**Comment by knacker48** [comment]
@ATH1909 I'd like to see somone more along these lines. Making heads of staff less noticeable is not helping anyone

**Comment by Kierany9** [comment]
make big text only show up on the relative department channels, IE CE gets bigtext on the Engineering channel, CMO gets bigtext on the medical channel, etc. Captain still gets bigtext everywhere

it's useful when you're HOS for ordering your lackeys, and annoying when the RD is shitposting on common fnr

**Comment by JacksonCoder** [comment]
Heads need loud radio to coordinate things. It's just a fact. As CE, engineers only really listen to what I ask them to do if I'm speaking in big text. And it's a similar story for all other heads of staff. You need to have a way to get attention and make people recognize instantly that you are, in fact, the head of the department, if you want to make things happen. If you're really annoyed about how loud text clogs up the screen, there still are some options. For one, heads could have their radio text in a special color, or underlined, or maybe it just appears big on their department radio, etc.
But just straight up removing this vital element from almost all heads of staff is a really bad idea.

**Comment by ExcessiveUseOfCobblestone** [comment]
> make big text only show up on the relative department channels, IE CE gets bigtext on the Engineering channel, CMO gets bigtext on the medical channel, etc. Captain still gets bigtext everywhere
> 
> it's useful when you're HOS for ordering your lackeys, and annoying when the RD is shitposting on common fnr

> Have heads being able to talk **LIKE THIS** only on their departmental channel. Have Cap and AI keep it as it is.

These are fair compromises I think, unless you guys are saying heads need big text (in common) to coordinate.

**Comment by Tlaltecuhtli** [comment]
@ExcessiveUseOfCobblestone where is say handled

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/a9ca93b60dbf7b9f0fc5cbe94c406a2126312fee/code/game/objects/items/devices/radio/radio.dm#L208-L209

**Comment by ExcessiveUseOfCobblestone** [comment]
something like

```DM
if(use_command)
    if(istype(keyslot, /obj/item/encryptionkey/heads/captain) || istype(keyslot, /obj/item/encryptionkey/ai))
        spans |= SPAN_COMMAND
    else if(channel != RADIO_CHANNEL_COMMON)
        spans |= SPAN_COMMAND
```

maybe?

**Comment by Garen7** [comment]
The issue isn't that heads get loud text, the issue is the kind of people who play heads and spam chat with their shitty memes.

**Comment by Timonkeyn** [comment]
Imagine being the ai with small text, getting spammed away by all the vivas on the radio while getting attacked by nukies and having to go all the way to a comms console while dying to get attention

**Comment by Timonkeyn** [comment]
Also comms consoles have recharge times. So, if you get attacked just after announcing "suit sensors to maximum" you're fucked

**Comment by ExcessiveUseOfCobblestone** [comment]
> Also comms consoles have recharge times. So, if you get attacked just after announcing "suit sensors to maximum" you're fucked

if you're trying to type in the announcement console while getting attacked you're pretty much SOL to begin with.

Also for better or worse the code I posted would permit all heads to bigtext in command channel.

**Comment by Timonkeyn** [comment]
I'm talking about the ai

**Comment by zxaber** [comment]
Cobble's code, line two, has `/obj/item/encryptionkey/ai` at the end, which would give the AI their bigtext too.

**Comment by ShizCalev** [comment]
image

**Pull request closed without merging**
