### PR TITLE
Job glasses no longer override blindness or shortsighted eyewear.

### PR DESCRIPTION
**Pull request by CoffeeDragon16**
## About The Pull Request

I started on this with my PR #55387, but didn't expand it fully to all other quirks that have quirk clothing. Jobs with specific eyewear, like the Warden's HUDglasses, override quirk eyewear, creating situations like blindly fumbling your way to Medical for new glasses roundstart. This fully fixes the already-closed issue #55322.

## Why It's Good For The Game

Bug fixes good, no more blind stumbling or missing your blindfold.

## Changelog
:cl:
fix: Job eyewear no longer overrides quirk eyewear.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Should try to place old in backpack or something instead of trying to delete it (under the assumption that if your job has starting eyewear it is because it is needed for the job and should not require pulling from the maps “limited” roundstart supplies)

**Comment by CoffeeDragon16** [comment]
Well, you have to make yourself impaired to use that gear, so I don't think that happens enough to warrant the wasted space. I don't think I've seen anyone do much else with the old gear but trash it myself. None of the job eyewear is needed, either, just a convenience, so I feel like the inconvenience is just a part of the quirk.

**Comment by CoffeeDragon16** [comment]
i'll close this if #55807 extends to blind and not just nearsighted

**Comment by CoffeeDragon16** [comment]
azarak fixed it better than me

**Pull request closed without merging**
