### PR TITLE
More sprites

### PR DESCRIPTION
**Pull request by coiax**
[MORE SPRITES!](https://drive.google.com/drive/folders/0B5WnmAOjfSwocm1Dc1d4UHZkRWc)

### CODE REVIEW

**Comment by KorPhaeron** [comment]
There is no reason for most of these to be in their own dmis

**Comment by coiax** [comment]
More DMIs mean fewer merge conflicts.

**Comment by pudl** [comment]
why are you cluttering the codebase with shitty useless sprites

**Comment by PKPenguin321** [comment]
^

**Comment by Cheridan** [comment]
in a game with 5 perspectives already you somehow added a completely new one with the go board :V

**Comment by Cheridan** [comment]
anyway i think this kind of assorted spritery would be better suited to a forum thread or something, having a bunch of usused sprites in the code all in their own dmis isn't really needed

**Comment by coiax** [comment]
fiiiiiiiiiiiiiine

**Pull request closed without merging**
