### PR TITLE
Adds a disposal thing to throw items into the SME crystal

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Adds a disposal chute to throw items into the SME crystal
/:cl:

starting the engine with Poly is the only way

### CODE REVIEW

**Comment by Cyberboss** [comment]
@MoreRobustThanYou

**Comment by MoreRobustThanYou** [comment]
i'm too lazy

**Comment by PraiseRatvar** [comment]
wouldn't this fuck with people who want to add pipes in the sm chamber?

**Comment by MoreRobustThanYou** [comment]
why would you do that

**Comment by PraiseRatvar** [comment]
i've seen people do some weird shit with h/e pipes by putting them in the sm chamber and setting it up so cold loop has freon in it and cools the chamber by not dispensing freon however by doing some weird shit with temperature, idk but it seems pointless anyway to add a disposal chute into the sm and makes it easier for traitors to blow it up

**Comment by Tokiko1** [comment]
Be careful with this, you might be encouraging players to toss stuff in there just for fun, causing everyone nearby to get deadly radiation doses and/or starting the engine prematurely.

 My downvote is purely for suggesting birdmurder and does not reflect my opinion on the balance of this.

**Comment by MoreRobustThanYou** [comment]
@Tokiko1 but what else you do with poly when he screams "IT'S LOOSE" and scares everyone

**Comment by octareenroon91** [comment]
1. Why would disposals interfere with pipes? They might interfere with h/e because those are fickle.
2. Minimize structures in the SM chamber -- just a trunk or a disposals pipe, don't bother with a chute.
3. Even just a bare disposal line with no machines might be OK so it takes at least a little effort to start the delamination.

**Comment by kevinz000** [comment]
>banned for supermatter engine bullshit for god knows how many times

>prs something to get everyone else banned

lmao!

**Comment by RandomMarine** [comment]
Frills like this should be left for engineers to build if they feel like it.

**Comment by KorPhaeron** [comment]
Banbait

**Pull request closed without merging**
