### PR TITLE
deadly brain tumor now gives -3 points

### LINKED ISSUE #37446: Brain tumor trait is out of control
Round ID: # 87046 (but I've been seeing this for many rounds now).

Okay, so brain tumor went from free point to 10 minute permastun/blindness sentence. I can't even start growing mannitol plants before that point and not all chemists cooperate with you. I know this is part of the risk of taking this, but holy fuck its kinda too much. You may deem this not an issue, or intended, at least I'd like to hear from the administration before dropping my gimmick trait build.

As a side note, are traumas tracked anywhere? I feel like I get split personality all the time and its fucking annoying, every single one I've had doesn't want to cooperate or negotiate on what to do, one even welded me inside a pod and made the fuel run out so I couldn't get out (which is kinda okay since he wanted to survive but its still pretty dickish).

### PR DESCRIPTION
**Pull request by ghost**
This might seem insane and from the first pr where I added tumors people were worried that -3 points was too much but safe to say, brain tumor is lethal and i LOVE IT. sadly, there just isn't enough incentive to pick brain tumor as IF you get a heavy brain trauma you have to take surgery to fix it and taking surgery while the tumor is still in your brain killing you is pretty difficult, not gonna lie. so i think it's fair to just give it a bump in the right direction towards people who want to play a heavy risk reward playstyle.

ignore the first commit, i was a little bit more pompous when i started this pr

inspired by/closes #37446

### CODE REVIEW

**Comment by Repukan** [comment]
Or they could just. .

Not take it if they don't want to deal with it?

**Comment by Armhulen** [comment]
@Repukan i enjoy racing the clock to get chemotherapy set up for the round so you don't die, it's just that it's not worth it compared to the other traits you can pick

**Comment by Cyberboss** [comment]
>patch-77
STOP

**Comment by Iamgoofball** [comment]
please, I'm on patch 428

**Comment by Armhulen** [comment]
@Cyberboss IT'S A ONE LINE CHANGE CMOOOOON BE NICE

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact

**Comment by Armhulen** [comment]
Hi!!!

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact idk u got triggered when I said make the norevive trait -3 so i didn't know if that applied here.

**Comment by Armhulen** [comment]
@ExcessiveUseOfCobblestone Cobby stop trying to sink me!

**Pull request merged**
