### PR TITLE
Lets mimes write again

### PR DESCRIPTION
**Pull request by AverageUser67**
## About The Pull Request

Lets mimes write again without breaking their vow, letting various gimmicks be performed without vow-breaking.

## Why It's Good For The Game

Several people came out in protest of https://github.com/tgstation/tgstation/pull/74674, and this PR lets mimes write (and thus "draw"/make lists or menus/write contracts/write letters without having to tank their mood and lose their spells.
"But mimes can write with their cra-"
Frankly I don't see why that was made an exception while barring every other writing tool. You can just highlight the paper and read it, which just makes it frustrating when someone takes it/the container it's in/you drop it/it is dropped off you and the only method of writing for mimes is gone while there's a pen right fucking next to you.

## Changelog

:cl:
del: Mimes can write again, this will be reverted if it is heavily (ab)used
/:cl:

### CODE REVIEW

**Comment by AverageUser67** [comment]
I want to clarify that this is only here as an option incase https://github.com/tgstation/tgstation/pull/74674 doesn't work. This wasn't meant to be speedmerged (I'm actually against speedmerging unless it's a bug or oversight)

**Comment by BlueMemesauce** [comment]
I mean I would give it more time, it's only been 2 days

**Comment by Mothblocks** [comment]
no knee jerk reverts

**Comment by AverageUser67** [comment]
@BlueMemesauce I literally said this wasn't meant to be speedmerged
@Mothblocks Play mime on Manuel before and after #74674 and tell me again, but fair point

**Comment by Mothblocks** [comment]
I am not going to play mime on Manuel to tell you that ~2 days after a merge is made is not going to be enough time for the maintainer who merged it to suddenly disagree with themselves

**Comment by BlueMemesauce** [comment]
I mean the maintainer said "We'll see how it goes", which basically means they didn't fully agree with the PR and just wanted to test it out first.
But yea you can just wait before making the PR, theres not really a reason to make a PR early.

**Comment by optimumtact** [comment]
don't assume my position

**Pull request closed without merging**
