### PR TITLE
Adds the lipid extractor

### PR DESCRIPTION
**Pull request by Time-Green**
A machine that sucks fat from someone while giving them 'useful' tips.
At the end of the fat sucking cycle it dispenses the meat. It takes 90 nutrition for 1 slab of meat, and one slab of meat gives you about 50~ nutrition, so you can't get infinite meat.

People have 2 second to leave before the extraction starts. They can leave during the extraction cycle, unless the chef toggled the safety hatch.
The extractor does not go below starving and only starts sucking when someone is above well fed. 

Also this is the best sprite I think I've ever made 
:cl:
add: Adds the lipid extractor to the service protolathe arsenal
/:cl:
Why: The kitchen can always use some love, and this allows them to turn plants into meat by using replenishable human lifestock.

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Holy shit how much work did it take to change 1200 files

**Comment by Time-Green** [comment]
ignore that, I accidently commited to my master once

**Comment by PKPenguin321** [comment]
Kind of invalidates liposuction surgery and chems

**Comment by Time-Green** [comment]
liposuction and chems are easier made and used. The machine needs to be researched and built but can be used in a pinch

**Pull request closed without merging**
