### PR TITLE
More modular computer fixes and tweaks

### LINKED ISSUE #19950: Printing a Laptop Frame in the autolathe completely locks it up.
The autolathe will be permanently stuck busy, making it impossible to use or deconstruct.

### LINKED ISSUE #19951: There's no host side confirmation of a password on P2P File transfers.
The server Password field always says DISABLED, even when a valid password is set, and active.

### PR DESCRIPTION
**Pull request by Shadowlight213**
:cl: 
add: Added a laptop/tablet vendor to tool storage. Remember to bring your space cash!
add: Added a cargo pack of 5 tablet computers
fix: Fixed ntnet relay not updating icon properly
fix: portable drives now can have files transferred to them and be inserted correctly.
fix: autolathes will no longer lock up when printing laptop frames
/:cl:

Fixes #19950 
Fixes #19951

### CODE REVIEW

**Comment by Core0verload** [comment]
This would conflict so hard...

**Comment by Shadowlight213** [comment]
@core0verload sorry, but this fixes some pretty major bugs with the system.
I can remove the map edit if you really need it, but if you really are just throwing it out, fixing conflicts wouldn't be too hard.

**Comment by Core0verload** [comment]
Can you put 
> fix: Fixed ntnet relay not updating icon properly
fix: autolathes will no longer lock up when printing laptop frames

fixes in a separate PR?

Everything else is pretty much handled in my WIP PR.

**Comment by Core0verload** [comment]
nevermind, I pulled the fixes into my own PR

**Pull request closed without merging**
