### PR TITLE
Lets RCDs load reinforced glass and plasma rglass sheets

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: RCDs can now also be loaded with reinforced glass and reinforced plasma glass sheets.
/:cl:

If RCDs can be loaded with glass/metal/plasteel, it only makes sense for them to accept rglass and plasma rglass as well.

Rglass sheets add 6 matter (.5 metal, 1 glass). Plasma rglass sheets add 8 matter (1 metal, .5 glass, .5 plasma).

### CODE REVIEW

**Comment by Shadowflame909** [comment]
if the cmo gets a combat defib. I dont see why the CE doesnt spawn with a combat rcd

**Comment by 81Denton** [comment]
CMO doesn't get a combat defib, just the regular compact one

Anywho, off-topic

**Comment by AlexTheSysop42** [comment]
Rglass is .5 metal, 1 glass

Plasma rglass is .5 metal, 1 glass, 1 plasma

**Comment by Mark9013100** [comment]
@Shadowflame909 the combat RCD has like 500 points

**Comment by 81Denton** [comment]
It can also take down r-walls which just takes a dump on malf AIs

**Comment by Shadowflame909** [comment]
Ok, I have a better idea. Instead of the combat rcd what if it was just a "compact rcd" basically a regular rcd and everything but it can fit in backpacks and armored suit slots (or pockets if regular rcds already do that). One for the CE's locker only.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
