### PR TITLE
Moves AI Chamber APCs

### PR DESCRIPTION
**Pull request by TheSilverNuke**
Makes it a little less easy for vent crawlers to rush and destroy the AI by instantly GG'ing them.

## About The Pull Request

Moves the APC's from outside of the central AI core area to inside the windoors.

2020-04-17 03_43_27-Space Station 13
2020-04-17 03_45_22-Space Station 13

## Why It's Good For The Game

Many ventcrawlers such as morphs or xenos can bumrush the AI APC and instantly kill them. This isn't a feature on most maps, but Meta and Delta were exempt from this. This change would bring them in line.

## Changelog
:cl:
tweak: Moved the APC's on Delta and Meta
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
ai doesnt need to be antag proof, i ded

**Comment by TheSilverNuke** [comment]
This doesn't make them antag proof, just a little more resistant to random midrounds. The AI sat is hilariously easy for anyone to breach, but it's important for any normal round.

**Comment by Iamgoofball** [comment]
just what we needed to celebrate the return of the repository, an AI buff

**Comment by TheSilverNuke** [comment]
I have to redo this real fast

**Pull request closed without merging**
