### PR TITLE
Antag reputation rewards are now configurable

### PR DESCRIPTION
**Pull request by Cyberboss**
@PKPenguin321's idea

### CODE REVIEW

**Comment by Iamgoofball** [comment]
ah yes, because we need to shift more of our game balance into a location where we're not allowed to change it and instead have to rely on 3 people that are geared towards pandering to the masses, to the point of making our game balance a political platform

**Comment by PKPenguin321** [comment]
whether or not you roll antag depending on what jobs you picked in the last 15 rounds isnt really game balance

**Comment by Iamgoofball** [comment]
encouraging people to play certain jobs is indeed gameplay balance

**Review by ninjanomnom — CHANGES_REQUESTED** [review]
What mso said

**Comment by deathride58** [comment]
@Iamgoofball On servers that don't have public configs, this actually stops people from knowing which jobs actually give you antag rep, which allows the antag rep system to exist without making it attract the wrong kind of people to certain roles.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
