### PR TITLE
Dehydrator, machine version of drying rack

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

image

Added dehydrator, a machine version of drying rack.

Replaced the second fryer with this rack on some maps to be available roundstart.

Also changed the colors of Smart Fridge to be more in line with other kitchen appliances.

## Why It's Good For The Game

We have plenty of recipes requiring dried items, and it's silly that the chef has to break down a cafeteria table to build a rack for regular recipes.

## Changelog

:cl:
add: Dehydrator, a machine version of drying rack, with a circuit board and available on some kitchens roundstart.
image: Updated the color palette of Smart Fridge
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]

**Comment by HoodMilk** [comment]
711 hot dog roller gameplay

**Comment by LSommers** [comment]
God damn it, now I can't unsee it as a gas station hot dog warmer.

**Comment by Wallemations** [comment]
> God damn it, now I can't unsee it as a gas station hot dog warmer.
> 
> 

Smh it's clearly an air frier

**Comment by Loafin34** [comment]
based. maybe finally people will make beef jerky

**Pull request merged**
