### PR TITLE
Replaces the strangely sized buildshuttle plate

### PR DESCRIPTION
**Pull request by francinum**
It's now just a stripped out deltastation shuttle.

This is done so that the shuttle is both larger, and actually fits against escape in most stations.
:cl: Francinum
tweak: The shuttle build plate is now better sized for all stations.
/:cl:
New: https://file.house/ygA3.png
Old: https://file.house/IL3N.png

### CODE REVIEW

**Comment by praisenarsie** [comment]
picture

@ShizCalev @ninjanomnom

**Comment by francinum** [comment]
@praisenarsie Added.

**Review by ShizCalev — APPROVED** [review]

**Comment by DoctoreMad** [comment]
Holy shit its huge

**Comment by ShizCalev** [comment]
That's what she said.

**Comment by ACCount12** [comment]
That's waaaay too large for a buildable shuttle.

**Comment by francinum** [comment]
@ACCount12 It's the size of the delta station shuttle.

**Pull request merged**
