### PR TITLE
If you keybind "moan" and "resist" at the same time, then use your "moan" keybind, you get gibbed.

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

On the tin. Features a new bitflag system to ascertain an "intentional" emote's source, if it was typed out in chat (e.g. `*moan`) the behavioral strategy would fall completely flat. So, we just track the source via the bitflag. If this PR gets closed or reverted, I would greatly appreciate it if you were to keep the framework of intentionality in as it might be useful in the future, simply removing the interaction on the `/datum/emote/moan/can_run_emote()` proc. thanks.
## Why It's Good For The Game

You're being weird buddy. You should fix those binds. Positive Punishment is a powerful tool (or would it be negative punishment since we're removing your life? unsure). Powergamer. Neener neener.
## Changelog
:cl:
add: For some reason, spacemen everywhere who both moan and resist something at the same time have been getting gibbed. Would be worthwhile to change up those habits.
/:cl:
The system should be foolproof enough to where you don't get gibbed if you don't stringently meet the following criteria:
- The emote was not forced by the game, but must have been forced via you doing a keybind.
- The keybind is the same for resisting (which means that you _will_ be resisting since you did the keybind aforementioned)
- You're capable of doing the emote on your own volition otherwise.

### CODE REVIEW

**Comment by CCC23** [comment]
what

**Comment by Singul0** [comment]
????

**Comment by Acer202** [comment]
What

**Comment by Arctrooper8** [comment]
Won't this just actually cause bored assistants to cuff themselves and then repeatedly moan just to gib themselves?

**Comment by EricZilla** [comment]
> Won't this just actually cause bored assistants to cuff themselves and then repeatedly moan just to gib themselves?

They could do the same thing with an oxytank, at least this way you can do a funny pull my finger on someone

**Comment by san7890** [comment]
> Won't this just actually cause bored assistants to cuff themselves and then repeatedly moan just to gib themselves?

you won't actually be able to moan you just gib.

**Comment by Livrah** [comment]
what

**Comment by saprasam** [comment]
this kills the catboy

**Comment by PunishedHideo** [comment]
that's a feature to troll dumfucks

**Review by ZephyrTFA — CHANGES_REQUESTED** [review]
You say its a bitflag but then use `==` instead of `&`

**Comment by YuliceTheDruid** [comment]
Couldn't this be used as a method to commit suicide in scenarios where you otherwise wouldn't be able to normally and it would be advantageous to do so? (Xenos, cuffed in sec, cult conversions, force borging machine for malf ai)

**Comment by Arctrooper8** [comment]
> you won't actually be able to moan you just gib. you don't even need to cuff yourself either as long as you have the keybinds set you're donezo

Ah now I understand, finally we can have a gib keybind. Truly this is the greatest assistant buff of all time.

**Comment by Fikou** [comment]
what the fuck

**Comment by san7890** [comment]
Actually i just remembered I hated that meme "dab" PR circa 2019 where people spammed the emote to get out of handcuffs and I've realized I don't like this concept anymore. Maybe I'll split out the whole "what provoked this emote to fire" thing in a new PR but I just remembered that was a thing that I detested. Good luck

**Pull request closed without merging**
