### PR TITLE
PKAs start with outback pins by default

### PR DESCRIPTION
**Pull request by Metekillot**
## About The Pull Request

PKAs do 40 damage, unmodded, in low pressure areas. They do 10 if there's pressure. It is relatively simple to depressurize an area, and you are also free to be a menace in space if you get your hands on one. Adding mods to them makes them even more powerful; three cooldown mods, stacked, makes the PKA roughly as fast as swinging a melee weapon.

They can also be used as a burglary tool, since their explosive damage means they damage nearly every object that can suffer damage.

This is a change to PKAs, with respect to the many other immensely powerful options available to miners that put them roughly on par with most mid-to-late game antagonists.

Outback pins prevent you from firing on station. To use a PKA on station, they would need to secure an electronic pin instead.

## Why It's Good For The Game

Miners are overpowered. Make them steal or get an electronic firing pin to be ranged and overpowered.

## Changelog

Proto-kinetic accelerators now start with outback firing pins by default; can't fire on the station, mate!
:cl: Bisar
balance: Proto-kinetic accelerators now start with outback firing pins by default; can't fire on the station, mate!
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Miners already need to depressurise areas to make their weapon work onstation (if they are not a traitor), at which point they get a reasonably slow low-ranged gun. I'm not convinced this is a big deal.

**Review by Fikou — CHANGES_REQUESTED** [review]
Your "About the Pull Request" is a "Why It's Good For The Game" section and your "Why It's Good For The Game" is a random rambling

**Comment by Metekillot** [comment]
> Miners already need to depressurise areas to make their weapon work onstation (if they are not a traitor), at which point they get a reasonably slow low-ranged gun. I'm not convinced this is a big deal.

Well, no. It just lowers the damage to 10. And yes, unmodded, it is relatively slow. If you mod it with cooldown mods, it becomes quite fast. Roughly as fast as swinging a toolbox, if not slightly faster if you stack all 3 cooldown.

**Comment by Jacquerel** [comment]
> > Miners already need to depressurise areas to make their weapon work onstation (if they are not a traitor), at which point they get a reasonably slow low-ranged gun. I'm not convinced this is a big deal.
> 
> Well, no. It just lowers the damage to 10. And yes, unmodded, it is relatively slow. If you mod it with cooldown mods, it becomes quite fast. Roughly as fast as swinging a toolbox, if not slightly faster if you stack all 3 cooldown.

10 damage at 3 range once you have applied cooldown mods instead of range ones also is not a very big deal to me.

**Comment by Fikou** [comment]
> This would be a slight bother to traitor miners who actually buy the PKA modkit that reduces the pressure penalty

This PR doesn't address this bother, this makes it annoying for traitors to use their cool traitor tool as a cool traitor tool because they'll need to visit the armory at which point you might as well just grab the laser guns.

**Comment by Metekillot** [comment]
> Your "About the Pull Request" is a "Why It's Good For The Game" section and your "Why It's Good For The Game" is a random rambling

Committed suggestion from code review

**Comment by Jacquerel** [comment]
To put this in perspective, floor tiles have a throw force of 10, and can be thrown further than a PKA shoots and faster than a PKA fires.

**Comment by Metekillot** [comment]
> To put this in perspective, floor tiles have a throw force of 10, and can be thrown further than a PKA shoots and faster than a PKA fires.

Yes; throw tiles don't do explosive damage that breaks windows and door and bypasses most armor, and don't go up to 40 damage in low pressure.

And throwing weapons are notoriously bad.

**Comment by carlarctg** [comment]
Literally when has this been an issue? Ever? When's the last time a traitor miner used their PKA to murder the entire station? I don't understand. Did you look at the stats and construct an image of it being OP in your head?
What about the tot mod for pressure damage? How is this handling that? How are they going to use that with an outback pin?

Lasers are better than PKAs in almost every single way, modded or unmodded. This is such a weird PR.

What's so dreadful about the damage being labeled explosive? A fire axe costs 0 TC and breakd windows instantly.

**Comment by Jacquerel** [comment]
If a nonantagonist is depressurising the station in order to make their gun better then they are causing large amounts of collateral damage and you should probably ahelp about it. If they're an antagonist, they are doing their job. 
Having a slow-firing, low-range 10 ranged damage gun doesn't matter.

**Comment by Metekillot** [comment]
> Literally when has this been an issue? Ever? When's the last time a traitor miner used their PKA to murder the entire station? I don't understand. Did you look at the stats and construct an image of it being OP in your head? What about the tot mod for pressure damage? How is this handling that? How are they going to use that with an outback pin?
> 
> Lasers are better than PKAs in almost every single way, modded or unmodded. This is such a weird PR.
> 
> What's so dreadful about the damage being labeled explosive? A fire axe costs 0 TC and breakd windows instantly.

There are 2 or 3 fire axes on station; to break a door or grille with a fireaxe, you need to also have insulative resistance.

With a PKA, you need to mine for 5 minutes to get uranium, and you have a gun that fires fast enough to break down a door in less than a minute.

**Comment by Metekillot** [comment]
> Literally when has this been an issue? Ever? When's the last time a traitor miner used their PKA to murder the entire station? I don't understand. Did you look at the stats and construct an image of it being OP in your head? What about the tot mod for pressure damage? How is this handling that? How are they going to use that with an outback pin?
> 
> Lasers are better than PKAs in almost every single way, modded or unmodded. This is such a weird PR.
> 
> What's so dreadful about the damage being labeled explosive? A fire axe costs 0 TC and breakd windows instantly.

Also, just make the traitor PKA mod disable the safety check for the outback mod, then?

**Comment by Fikou** [comment]
> > Your "About the Pull Request" is a "Why It's Good For The Game" section and your "Why It's Good For The Game" is a random rambling
> 
> Committed suggestion from code review

About the Pull Request should be changes from the pull request, it should not delve deep into what the pka does and what it can be used for.
Ideally you would have something like
Protokinetic Accelerators (Other than cyborg and minebot ones) now have an outback firing pin, requiring the user to not be on the station z level to fire.
Anything that is meant to be an argument for why this should be added should be in "Why it's good for the game"

**Comment by Metekillot** [comment]
> > > Your "About the Pull Request" is a "Why It's Good For The Game" section and your "Why It's Good For The Game" is a random rambling
> > 
> > 
> > Committed suggestion from code review
> 
> About the Pull Request should be changes from the pull request, it should not delve deep into what the pka does and what it can be used for. Ideally you would have something like Protokinetic Accelerators (Other than cyborg and minebot ones) now have an outback firing pin, requiring the user to not be on the station z level to fire. Anything that is meant to be an argument for why this should be added should be in "Why it's good for the game"

I'll remember that in the future. Thanks for the heads up.

**Comment by sylvia-from-fulp-station** [comment]
> Miners are unreasonably good at fighting Space Dragons but that's basically it.
Hey miner is the closest thing to a dragon hunter job we have don't besmirch them.

**Pull request closed without merging**
