### PR TITLE
Radioactive Microlaser 

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
add: A stealth option for the traitor microlaser has been added. When used, it adds 30 seconds to the cooldown of the device.
/:cl:

https://tgstation13.org/phpBB/viewtopic.php?f=9&t=11789

People disliked having an easy tell on them when using it, but I didn't want to make it come without costs.

### CODE REVIEW

**Comment by Cyberboss** [comment]
No antag item changes

**Comment by Armhulen** [comment]
lol!

**Comment by nicbn** [comment]
2quick

**Comment by ExcessiveUseOfCobblestone** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Pull request closed without merging**
