### PR TITLE
[NO GBP] yield is no longer bread

### PR DESCRIPTION
**Pull request by flowercuco**
## About The Pull Request

yield is no longer bread and cake

## Why It's Good For The Game

yield is no longer bread and cake

### CODE REVIEW

**Comment by Time-Green** [comment]
Can you do the same for:
var/obj/item/food/pie/yield = 5
var/obj/item/food/cake/yield = 5
?

Also goddamn I should have seen this, but it just looked so natural

**Comment by flowercuco** [comment]
i forgot about the pie but remembered cake

**Comment by Fikou** [comment]
just remove the :cl:

**Comment by Thunder12345** [comment]
Leave the changelog in and let the players be mystified

**Pull request merged**
