### PR TITLE
Renames the organ thrower to the 'organizer' and clears up its description

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Renames the organ thrower to the 'organizer' and clears up its description.

## Why It's Good For The Game

The organ thrower is a very silly module, and i do like it, but did you know that it instantly replaces organs? As in, the organ is removed and swapped instantly? And it can store multiple, making organ manipulation surgeries eerily instant?

The description is funny, but it forsakes accuracy for amusement's sake. I did my best to keep it both funny and accurate, accurately describing its actual function now.

I also changed the name, because similarly, it wasn't very descriptive. Jacquerel suggested 'organizer' which is a hilarious pun and I'm all for it, even if it does also lack some accuracy which was supposed to be the intention of the PR.

## Changelog

:cl:
spellcheck: Renamed the organ thrower module to the 'organizer'
spellcheck: Made its description more accurate. Did you know it instantly replaces up to 5 organs in active surgery?
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
Tentatively suggest ReOrganizer as a name

**Comment by carlarctg** [comment]
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm idk

**Comment by Metekillot** [comment]
CARLARC YOU DIDNT UPDATE THE DMI FILES!
CARLARC!! THE UNIT TESTS!!!!

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
Oh, yeah, fix the icon states first, dangit.

**Pull request merged**
