### PR TITLE
Marauders will heal more of their host's damage on average

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Marauders will heal more of their host's damage, on average, per life tick.
/:cl:

It's now a maximum of 4 per tick, but if they have only brute damage, say, it'll heal 4 brute instead of 1 brute, as compared to the current 1 brute, 1 burn, 1 tox, 3 oxy heal.

### CODE REVIEW

**Comment by ma44** [comment]
You can also say "Instead of omnizine, nookies inside the mechs are healed with nanites!"

**Comment by ChangelingRain** [comment]
This is the same amount of healing under ideal conditions, but is just overall better all the time.

**Comment by XDTM** [comment]
Holy shit, 6 damage healing per tick, of any kind of damage, while also having a 400 health(+blocks) holoparasite is _kinda_ strong. Even if the healing only applies under 30 health, it still uncrits crazy fast, while the marauder is healing 2 life per tick itself.

**Comment by ChangelingRain** [comment]
This *is* per life tick, which is every 2 seconds; it's not actually that fast or powerful given that you can melee attack twice or fire a gun five times in that time. Even, like, punching is enough to keep them down.

**Comment by PKPenguin321** [comment]
FREEZE you cuck

**Comment by kilkun** [comment]
fuck da freeze eezy

**Comment by Kromgar** [comment]
>Holoparasites that heal peoples

Balanced

there's a reason Araki only had one character capable of healing... and there was only one capable  of self healing and he was the most broken person in the entire series

**Comment by ChangelingRain** [comment]
6 damage per life tick is not enough to keep you alive if you're being beaten up, as said above.

**Comment by KorPhaeron** [comment]
Its hard to consistently attack someone if their stand is body blocking and hitting you though

**Comment by PKPenguin321** [comment]
Yeah this is dumb

**Comment by jughu** [comment]
Why didnt we make maruaders just a subtype holoparasite and share the same health :thinking:

**Pull request merged**
