### PR TITLE
Resprites the Blade Heretic knives.

### PR DESCRIPTION
**Pull request by EnterTheJake**
## About The Pull Request

Changes the sprites on the action button for furious steel, and orbiting knives for Blade Heretic in general.

## Why It's Good For The Game

Blade Heretic Resprite

Kitchen utensils are kind of a lame fit for an eldritch acolyte, now they look like proper throwing knives.

## Changelog

:cl:
Image: Blade Heretic Knives have been resprited into proper throwing knives.
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
They're all pointing the wrong way.............

**Comment by Wallemations** [comment]
ALL THE OLD KNIVES POINT INWARD???

**Comment by EnterTheJake** [comment]
> ALL THE OLD KNIVES POINT INWARD???

Yìup.

**Comment by Ghommie** [comment]
@Wallemations willing to merge it?

**Review by Wallemations — APPROVED** [review]
It says I can't merge because conflicts but the sprite looks fine

**Pull request merged**
