### PR TITLE
Prevents the experimentor from cooling air below absolute zero.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
Adds max check for experimentor endothermic reaction. Also simplifies it a little, as the process of heating a portion of the air then merging it is no different than just heating the air with joule heating.

## Why It's Good For The Game
Negative temperature should not be possible in any circumstances, ever.

## Changelog

:cl:
fix: The experimentor can no longer create negative temperature.
code: Simplifies experimentor atmos interactions. Shouldn't have an impact in gameplay.
/:cl:

### CODE REVIEW

**Comment by TerraGS** [comment]
a machine so powerful it invents negative thermal potential

**Comment by moocowswag** [comment]
Im not entirely sure if chem application itself is more effective during lag because one time i used an acid foam grenade during a nukie round and people were casually sitting in it for over a minute.

**Comment by moocowswag** [comment]
The experimentor does do alot of weird things that probably need to be looked at.

**Comment by Kapu1178** [comment]
Really should have a temperature adjustment proc or macro to prevent this stuff

**Pull request merged**
