### PR TITLE
Readds gender reassignment

### PR DESCRIPTION
**Pull request by Core0verload**
I'm making another revert of PR that was hated by everyone and merged by a single maintainer. Because if I wouldn't do this, who will?

:cl: CoreOverload
fix: Gender Reassignment surgery is back.
/:cl:

The removal PR, #20148, was:
- A 100% meme PR by Goofball that somehow got merged for real.
- Marked as **[s]** without containing anything **secret** or **server security**.
- Quickmerged under 24h mark, **under 1h mark**, at night, without being a quickfix for a game-breaking issue.

This is an obvious maintainer abuse, and any two of the above are enough of a reason for instant revert.

### CODE REVIEW

**Comment by chanoc1** [comment]
ye sure why not

**Comment by Razharas** [comment]
>Only binary options available

This is so problematic
Putting constrains on peoples' feelings of their own body is fascism
Eww :-1:

**Comment by lzimann** [comment]
nah

**Comment by ChangelingRain** [comment]
I'm pretty sure the headmins are gonna close your pr~

**Comment by Shapsy** [comment]
well not like headmins have any intrinsic power in the codebase anyway (other than kor since he's ~design lead~)

my position on it is every time this comes up there's a massive shitstorm fight that comes from it, so while I never said it should be removed, I do feel like it's probably for the best we don't give the 5th rendition of this song and dance a chance to advance

**Comment by optimumtact** [comment]
You can make as many revert pr's as you want but this is a design decision.

Please do not continue to make reverts.

**Comment by Core0verload** [comment]
@optimumtact @AnturK @Jordie0608 @KorPhaeron @RemieRichards @WJohn 

Why do we have 24h for players to decide PR's fate if any button-mashing maintainer can just go "fuck all of you, i'm merging/closing it anyway"?

Why the fuck do we have A FUCKING 24H RULE if anyone can merge any shit under 24h with LITERALLY ZERO CONSEQUENCES? Without getting their maintainer buttons removed, without even getting their PR reverted.

We need a code of conduct for maintainers. Badly.

**Comment by optimumtact** [comment]
Because for the most part it's not usually abused in such an egregious manner 

one or two occasional times where someone forgets that speedmerging things silently causes more ruckus than just waiting and explaining and then firmly merging anyway is not worth overcomplicating our mostly unwritten guidelines

Installing all sorts of rulz is just hampering to the goal, which is to deliver ss13 feature bloat at maximum warp.

**Comment by Core0verload** [comment]
It's not a first time shit gets merged against people's will, and not the last. That's why we need real rules, not "there are some rules, but maintainers give no fucks about them".

**Comment by lzimann** [comment]
a lot of things that i didn't like got merged, all i can say is, get over it

**Comment by Iamgoofball** [comment]
>annexing Crimea was totally a design decision.

i laughed

**Pull request closed without merging**
