### PR TITLE
Adds three seashells to charlie station.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

title.

### CODE REVIEW

**Comment by nemvar** [comment]
Automatic citations for swearing next.

**Comment by loserXD** [comment]
what is this for

**Comment by Anonmare** [comment]
>He doesn't know how to use the seashells

:rofl: 
:rofl: 
:rofl:

**Comment by Mickyan** [comment]
What kind of degenerate puts a urinal next to a toilet anyway

**Comment by actioninja** [comment]
Can't believe this game breaking oversight made it in for so long.

**Pull request merged**
