### PR TITLE
[WIP]A New Year's Present: Mime Equality!

### PR DESCRIPTION
**Pull request by Buggy123**
For years, Mimes have been all but invisible under the shadow of the Clowns. For years, they've been suffering silently, the ignorant laughter and honking of Clowns all-consuming.

But I have a dream, a dream deeply rooted in the TGStation dream – one day this server will rise up and live up to its creed, "We hold these truths to be self evident: that all performers are created equal." I have a dream!

**And today! Today it comes true!**

# Presenting Mime Equality!
image
Don't worry, there's more than meets the eye. Turns out its rather hard to take a picture of something that's invisible, eh?

Now (or, once the PR is finished), Mimes have all of the same sorts of goodies that Clowns have:

- Their own rare mineral, Tranquillite, with unique properties! Rumor has it that it can be found in the depths of space, but take caution, for a asteroid filled with sound-dampening Tranquillite is also the perfect hideout...
- A mech to suit their sensibilities, the fearsome and elusive Reticence!
- All sorts of decor including permanent invisible walls, sound-dampening floors, and transparent floor tiles!
- New and exciting Mime-items to be printed from the protolathe!
- Tranquillite golems, embodying the perfect essence of Mimekind!

And beware, there are reports of a elite group of silent assassins hired by the syndicate. One day, you might just find yourself besieged by these masters of disguise and pantomime, seeking to silence your entire station!

And more!

This is a partial port of Paradise's [Tranquillite](https://github.com/ParadiseSS13/Paradise/pull/3767), which is itself a partial port of my original [Silencium PR](https://github.com/tgstation/tgstation/pull/14870). Most of the sprites are from Paradise, but I basically recoded all the rest from scratch.

Balance and content is definitely not final yet, I just wanted to get this out there before New Year. Suggestions and explanations as to why all of my code is nuclear-grade shitcode are welcomed.

To-do:

- [ ] Mime lavaland ruin
- [ ] Tranquillite floors dampen sound
- [ ] Fix the Reticence emote construction steps.
- [ ] Add more constructable items to the Mime research node
- [ ] Fix the invisible bugs
- [ ] Spruce things up a bit

### CODE REVIEW

**Comment by MCterra10** [comment]
speedmerge, new year is in 2 hours

**Comment by Buggy123** [comment]
>speedmerge, new year is in 2 hours

this kills the server

**Comment by Krysonism** [comment]
Nice, I love the reticence.

**Comment by Buggy123** [comment]
>Please code in mime ops

That's part of the PR; Mime Ops which start with full chameleon gear by default and get chameleon eshields and eswords.

**Comment by HomocidlePancakes** [comment]
>Mime golem

You did ask for permission, right?

**Comment by Buggy123** [comment]
>You did ask for permission, right?

From who?

**Comment by trollbreeder** [comment]
> > You did ask for permission, right?
> 
> From who?

Maintainers. Golems are technically an alien race.
Also, there's an antag freeze which i forgot about when i made the mime ops comment

**Comment by ninjanomnom** [comment]
Antag freeze, and break up this pr a bit. There's no reason to have all this in one pr instead of a bunch of small prs. Feel free to remake prs for the non antag parts of this.

**Pull request closed without merging**
