### PR TITLE
Moves cortical borer files into the miniantag folder

### PR DESCRIPTION
**Pull request by ghost**
Come ooon, people. I make this folder and then every time a miniantag gets added it gets neglected. :(

### CODE REVIEW

**Comment by Super3222** [comment]
I had that on the back of my mind after we rebased.

**Comment by Super3222** [comment]
I had that in the back of my mind after we rebased.

**Comment by Xhuis** [comment]
I have no idea why Travis failed.

**Comment by optimumtact** [comment]
CLICK THROUGH AND LOOK

**Comment by Armhulen** [comment]
NOT AN ANTAG REEEEEEEEEEEEEEEEEEEEE

**Comment by Xhuis** [comment]
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by KorPhaeron** [comment]
It's a xhuis randomly moving files and destroying their file history episode

**Comment by optimumtact** [comment]
its' a git mv so the history should be kept intact

also conflicts thanks to fixes kek

**Comment by Xhuis** [comment]
Conflicts are good.
@KorPhaeron Yes, when I implement a folder specifically to organize something and then it gets completely ignored, I tend to get a little upset.

**Comment by KorPhaeron** [comment]
@phil235

Should mob code even be in game modes?

**Comment by ChangelingRain** [comment]
#destroyfilehistory

**Comment by Xhuis** [comment]
woop woop

**Comment by phil235** [comment]
mob code goes in mob folder...

**Comment by Xhuis** [comment]
Since when have gamemode-specific mobs not gone in their own folder: I can count...
blob
clock cult
devil
bloodcult?

**Pull request merged**
