### PR TITLE
cakehat nerf

### PR DESCRIPTION
**Pull request by imsxz**
## About The Pull Request
2 line changes sue me

## Why It's Good For The Game

this overpowered weapon of mass destruction has reigned terror on gamers for far too long, there must be a stop to this evil so help me god
## Changelog
:cl:
balance: cakehat has been nerfed
tweak: cakehat sounds cooler
/:cl:

### CODE REVIEW

**Comment by loserXD** [comment]
cakehat nerf
cakehat nerf

**Comment by HomocidlePancakes** [comment]
Wow. Out of all the people I did not expect this nerf from you

**Comment by imsxz** [comment]
the biggest changes require the strongest wills

**Comment by HomocidlePancakes** [comment]
>Heat changed from 1000 to 999
Wat. Does this even do anything?

**Comment by Jimmius** [comment]
yes, it reduces the heat by 1, from 1000, to 999

**Comment by ExcessiveUseOfCobblestone** [comment]
bait

**Comment by imsxz** [comment]
>Cake hat. A hat of cake. Deals 15 burn. A single candle does about the same as a welding torch. Why? Why is this a thing? Fucking coderbus.

**Comment by ExcessiveUseOfCobblestone** [comment]
is there something that requires a min of `fire_act(1000)`?

**Comment by Suicidalpickles** [comment]
dont nerf my cakehat!!!!
im now gonna have to make a wall of text crying about how coder man bad, orange man bad and about separation of code and server!!!
this nerf would GREATLY render the cakehat useless for starters, like why even use it at this point now?
This pr is a huge nerf to me being an assistant main too, why would I be inclined to rush it if a welder is better than this heaping pile of garbage now?
if prs like this keep getting merged, im going to stop playing TG for good...

**Comment by anconfuzedrock** [comment]
Nerf the hat by making it burn off the hair of the wearer making them bald

**Comment by AnturK** [comment]
The solution is simple, make cakehat power only increase on user's birthday.

**Comment by necromanceranne** [comment]
Every round. Every fucking round I see some stupid assistant wearing this stupid fucking hat and I already know they going to kill me with it. I don't know how or when but it always happens and I'm so fucking sick of this overpowered piece of shit meme hat. Why the fuck do we even have it? This is the most broken item on the station and it just enables powergamers basically free kills on whoever they want. I want to throw it out an airlock every round but then I'll get banned for metagruding the admins bankrollers, because of course anyone who uses this hat is obviously the admins metafriends. Why else would THEY get ignored for getting the hat every round? /tg/ died the moment this thing got put into the game.

**Comment by 123chess456** [comment]
it's obvious this pr is gonna be orange-bussed to the merge line. oranges, you are the worst kind of human being: an egoistical loser who, despite being in a leadership position, doesn't bother to actually properly lead, and instead abuses his position to further his own opinions and goals you must've been abused as a child or something

**Pull request merged**
