### PR TITLE
Removes explosive lances

### PR DESCRIPTION
**Pull request by JJRcop**
## About The Pull Request

Explosive lances, which you can craft with a spear and a grenade, are removed from the game entirely.

## Why It's Good For The Game

I'm mostly indifferent. I made this PR because I saw some people complain about this in other PR comments but didn't want to make the PR themselves.

## Changelog
:cl: JJRcop
del: Removed explosive lances.
/:cl:

### Notes

I have intentionally made 2 commits for this PR.
 - The first one removes the crafting recipe but leaves the item (b47e6e8d33d9f86d76478f9dc8e186262c7b32c3)
 - The second one removes the item (541c73a33389542680e623a30977869ed6dfcc99)

Take a look at #42997. It's a good alternative.

Closes #42997

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
just remove their trow ability and have them as intended to use

**Comment by JJRcop** [comment]
Please keep posting feedback and discussion about this change. However, I will not modify this PR byond its original scope. Consider it immutable except for reverting 7425d156808df2f21c3b8c8cb065f1e23cebf521.

I encourage you to make your own PR containing changes if you wish to modify the behavior of the explosive lance. Don't try to convince *me*, convince each other. Then, turn your conclusions into actions.

**Comment by necromanceranne** [comment]
_Nuclear terrorism intensifies_

**Comment by knacker48** [comment]
What complaints did people have with explosive lances? I rarely see them used but that's just me

**Comment by nicbn** [comment]
I've never seen it get used

**Comment by py01** [comment]
They're mostly used by "powergamers" to oneshot wizards or nuke ops with a potassium water grenade lance. Many players avoid them due to being unsporting, but they often oneshot crit or kill the target when actually used.

**Comment by pizzatiger** [comment]
The (un)fun about them is due to how the code works, Even if you trying to catch them, there is a decent chance it embedded into you and will still explode!

**Comment by ExcessiveUseOfCobblestone** [comment]
the best solution tbh

**Comment by JohnMcLaime** [comment]
They could also one-two shot mechs or their pilots inside of them. Compare with the time that is taken in making one.

**Comment by Fox-McCloud** [comment]
We did this and it was honestly for the best.

Even if it only applies when you melee someone, there's still a numer of cheesy things you can do with them that honestly probably shouldn't be around.

**Pull request closed without merging**
