### PR TITLE
Adjust payday payout for most species (un-Fairer paydays)

### PR DESCRIPTION
**Pull request by Gamer025**
## About The Pull Request

Adds a payday_modifier variable to bank_accounts.
This can be used to increase or decrease the money a account receives each payday.

Also adds an payday_modifier to species.dm which defaults to 1 but I overwrote it in most species files to 0.75, expect for humans.
This means all crew members, expect humans, earn 25% less now.

EDIT: Cobby said its OK to PR this, just in case some maintainer sees this as race change which require maintainer approval:
image

## Why It's Good For The Game

Currently most people earn way too much money anyways. This PR fixes this at least by a bit.
However the main intend is to encourage roleplaying by adding a bit of racial conflict.
It also seems kinda realistic from an IC perspective that NT would try to save cost by paying non humans less.

## Changelog
:cl:
tweak: Nanotrasen checked the last few expenses reports and decided to reduce payday spending. Because of this, the salary of all non human employees has been reduced by 25%. Please consult your local Head of Personal for more information.
/:cl:

### CODE REVIEW

**Comment by pireamaineach** [comment]
Plasmaman wages are lower because of the upfront costs for N.T. of buying suits and plasma.

Everyone else is just worth less.

**Comment by Fikou** [comment]
this is implemented kind of stupidly, shouldnt everyone start at 0.75 and humans being snowflake 1 instead of setting the var on every species except human

**Comment by Gamer025** [comment]
> this is implemented kind of stupidly, shouldnt everyone start at 0.75 and humans being snowflake 1 instead of setting the var on every species except human

I did it that way initially but Floyd said that's a bad thing to do.
image
And thinking about it he is probably right, this seems "cleaner".

**Comment by Qustinnus** [comment]
if a modifier isn't 1 by default it isn't a modifier anymore. Then you're better off lowering the wages everywhere and making humans have 1.33 bonus modifier

**Comment by necromanceranne** [comment]
So if my boys in cargo aren't human, they drain less from the budget? Nice.

**Comment by ATH1909** [comment]
"This PR fixes this at least by a bit.
However the main intend is to encourage roleplaying by adding a bit of racial conflict."

Please do tell me how you're supposed to start a racial conflict with someone else over a game mechanic that they physically can't change via any in-game means (since (most) budget cards got yeeted).

This PR also fucks over nonhuman botanists (harder to buy strange seeds; the biggest issue here by far), nonhuman chemists (harder to buy reinforced plungers, which you need in order to get geyser chems (which currently use money as a time gate)), and nonhuman paramedics/doctors (harder to buy (half-decent) pinpointers and portable suit sensor monitors). It also makes it harder for moths to buy a welding helmet (so that they don't get bullied by everyone with a flash) from YouTools.

This just seems like yet another "haha, FUCK people who play races that I don't play! amirite, guys?" PR.

**Comment by optimumtact** [comment]
shouldn't the title be unfairer paydays?

**Comment by Kurgis** [comment]
> shouldn't the title be unfairer paydays?

Nanotrasen would never do anything unfair, if the employees are receiving lower wages it must be a fault at their end.

**Comment by ArcaneMusic** [comment]
This would also make it easier to implement heads of staff being able to give raises/dock pay a bit easier as well, which is very solid and very clean 👍

**Comment by lordpidey** [comment]
Make the multiplier .77 for the meme value.

**Comment by HomocidlePancakes** [comment]
.77 gonna look scuffed

**Comment by Nikitaw99** [comment]
since (supposedly) moths are better treated than other races or whatever, maybe they could have relatively higher paydays than other nonhumans; just an idea

**Comment by Gamer025** [comment]
> "This PR fixes this at least by a bit.
> However the main intend is to encourage roleplaying by adding a bit of racial conflict."
> 
> Please do tell me how you're supposed to start a racial conflict with someone else over a game mechanic that they physically can't change via any in-game means (since (most) budget cards got yeeted). This just seems like an excuse to make yet another "haha, FUCK people who play races that I don't play! amirite, guys?" PR.
> 
> This PR also fucks over nonhuman botanists (harder to buy strange seeds; the biggest issue here by far), nonhuman chemists (harder to buy reinforced plungers, which you need in order to get geyser chems (which currently use money as a time gate)), and nonhuman paramedics/doctors (harder to buy (half-decent) pinpointers and portable suit sensor monitors). It also makes it harder for moths to buy a welding helmet (so that they don't get bullied by everyone with a flash) from YouTools.
> 
> In short, this PR DOES have an effect on balance, and it's going to be harder to balance more mechanics around the economy system in the future if this PR gets merged.

So I just checked by joining a local server as non human botanist and I started with about 560 credits. Each payday gives you about 95 credits.
Welding helmets and strange seeds both cost 350 credits. This means that at roundstart you get enough money to buy 1 pack of strange seeds or a welding mask. This is with a low paying job (PAYCHECK_EASY which is 125).
Paydays happen every 5 minutes. This means as roundstart easy paying job you only need to wait 10 minutes to buy another welding mask or a pack of strange seeds. After 30 minutes into the round you are able to buy both seeds and a welding mask and this by literally doing nothing.

Although I agree that this PR affects balance (maybe I should change the changelog to balance instead of tweak?) I still think the PR is perfectly acceptable at the current economy situation. If someday in the feature economy gets reworked, so that payouts are more strict, the author of that rework might want to adjust the values of this PR but for now they seem fine.

**Comment by Gamer025** [comment]
> since (supposedly) moths are better treated than other races or whatever, maybe they could have relatively higher paydays than other nonhumans; just an idea

Hmm I never heard anything about NT treating moths better than other races.
I decided to just lower all races to 0.75 so that this isn't just some middle finger to certain races.
I assume NT just treats all non human races less equal then humans (for example the AI only needing to respond to human requests with its default lawset)

**Comment by GoldenAlpharex** [comment]
No offense, but why would we need to make it so there's even less incentive to play other races? It's like creating something cool and then adding so many drawbacks to it "For fun & Balance" that the only real reason you might want to actually do it is because you've grown attached to it. This PR, while making a bit of sense lore-wise, is, in my opinion, stupid gameplay-wise.

**Comment by Gamer025** [comment]
> No offense, but why would we need to make it so there's even less incentive to play other races? It's like creating something cool and then adding so many drawbacks to it "For fun & Balance" that the only real reason you might want to actually do it is because you've grown attached to it. This PR, while making a bit of sense lore-wise, is, in my opinion, stupid gameplay-wise.

While this PR definitively adds another drawback to non human races the drawback isn't that big.
The main reason as said is the lore aspect. Like NT already fits their AI with a lawset that only makes it follow human commands and they also prevent non humans from staffing any command position.
Im not sure who decided at what point that non human races should be treated less equal but this change just seems logical from an ingame perspective.
If economy was actually designed to be a very strict system where you can be happy if you are able to afford a few items in a round then I definitively wouldn't have made this PR. But currently money really isn't a problem. In case economy ever gets reworked (if not removed) then these values can easily be tweaked (and if needed removed / set to 1)

**Comment by pireamaineach** [comment]
based

**Comment by adamkad1** [comment]
woop woop, racial revolution

**Pull request merged**
