### PR TITLE
Adds a new silly tip.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

see title

## Why It's Good For The Game

sussus amogus

## Changelog
:cl:
spellcheck: Added a new trivia fact.
/:cl:

### CODE REVIEW

**Review by itseasytosee — APPROVED** [review]

**Review by JohnFulpWillard — APPROVED** [review]

**Comment by MrMelbert** [comment]
actionninja bait - oh nevermind

**Comment by LemonInTheDark** [comment]
Just realized this isn't a meme pr, so here's some explanation.

I don't like adding among us memes to the game, partially because players are really cringe about it right now, and partially because I just don't like the way it looks/ahhh I'm not sure how to phrase it, I guess this is more a personal asthetic thing, but even in the company of `Demoman takes skill.`, it seems in poor taste to me.

**Comment by wesoda25** [comment]
In other words no one wants to endorse this meme further

**Comment by OceanFish1** [comment]
literally 1984

**Pull request closed without merging**
