### PR TITLE
Adds the C-4 Remote Detonator for Nuke Ops

### PR DESCRIPTION
**Pull request by PKPenguin321**
The C-4 Remote Detonator. Slap a block of C-4 with it to tag that block. Use it in your hand to trigger that block.

Once triggered, the block will beep and display a red warning message to people nearby. Two seconds after triggering, the tagged C-4 will blow up. Tagged C-4 blocks also have a red display, instead of the usual green.

**NEEDS SPRITES.** I'm currently using sprites that I hijacked from Binding of Isaac.
Tagged C-4 Sprite:

tagged c4

PLACEHOLDER remote sprites (can't be used because licensing, only posting these to show what I'd like them to look like):
No C-4 tagged:
  doctor s_remote_icon
With a C-4 tagged:
remote detonator on sprite

:cl: PKPenguin321
rscadd: The C-4 Remote Detonator has been added to the traitor uplink. Use it on a block of C-4 to tag it, then press the button on the remote to detonate the C-4 quickly and from any distance.
/:cl:

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
We have signalers though we are breeding lazy traitors

**Comment by PKPenguin321** [comment]
I'm well aware. Signallers take more time to set up, but detonate instantly and without warning, and can be rigged to stuff like mousetraps. This is pretty much a downgrade from that, except that it's easier to set up.

**Comment by MMMiracles** [comment]
>paying 6 tc for something that is arguably worse in every way compared to current free method.

literally why would anyone buy this at all how can you be that lazy to not want to take an extra few seconds to screw a few signalers to C4.

**Comment by PKPenguin321** [comment]
the fun part is that you can buy the c4 bundle bag that has like 10 blocks in it and then buy this and then fart bombs everywhere

**Comment by Fox-McCloud** [comment]
Redundant when two signallers accomplish the same thing and are publicly available.

**Comment by AdamElTablawy** [comment]
i would like to introduce you to this concept of not spoonfeeding traitors everything they need in one uplink

**Comment by Supermichael777** [comment]
this sounds more like a tool for ops who might want pay for speed and can't get a large pile of signalers. also someone cant blow you up by guessing your favorite signaler combo

**Comment by PKPenguin321** [comment]
i think i should have gone with my original idea of making it a different bomb instead of adding onto C4 but idk

**Comment by PKPenguin321** [comment]
nah but you know what you guys are right, this is kind of an idiot idea. i don't wanna be that guy who holds onto his codebaby. rip

**Comment by Supermichael777** [comment]
NOOOOO this is a good idea flukes could use something like this

**Comment by PKPenguin321** [comment]
tbh it was kind of OP in testing, but hilarious to use
you could just hurl bombs everywhere that detonated really quickly
not a bad idea to reintroduce it as nuke ops only though

**Comment by AdamElTablawy** [comment]
eh, for ops I guess that's fine albiet I still hate the concept of ultimate mass-detonators instead of using signallers for everything, especially since signallers can backfire really badly if some cunt mass pulses

**Comment by MMMiracles** [comment]
If you can't be assed to change the signal a few notches then you fully deserve the potential backfire from a grayshirt spamming the default signal tbh.

**Comment by coiax** [comment]
@PKPenguin321 what about just giving red button this functionality?

It'd detonate all live C4, and you can do the tagging thing to detonate any unattached C4.

**Comment by PKPenguin321** [comment]
functionality is too strong to give to nuke ops for free, since the red button starts on the map
it's an odd balance
also this still needs sprites

**Comment by coiax** [comment]
It's something they start with for free that like half of nuke ops forget anyway.

**Comment by Lumipharon** [comment]
How can any of you say 'don't spoon feed antags' when ops literally get a red button that is the exact same thing only for syndie bombs?

I would be greatly opposed to this for traitors, but for ops however, who always have inventory and time issues, this is completely fine.

**Comment by PKPenguin321** [comment]
okay so i'm thinking that i might just remake this later maybe because right now i have a different project that i think will be cooler and don't wanna fuck with git conflicts

**Pull request closed without merging**
