### PR TITLE
[no gbp] renmoves bartender skillchip from chipped quuirk

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

job skillchip, combat skilchip, bad skilchip

## Why It's Good For The Game

combat is bad job is bad no quirk no good no no no, no quirk get combat no quirk get job contant, ver ybad not good

## Changelog

:cl:
fix: [no gbp] renmoves bartender skillchip from chipped quirk
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
Drunk coding is the best coding.

**Comment by SyncIt21** [comment]
> combat is bad job is bad no quirk no good no no no, no quirk get combat no quirk get job contant, ver ybad not good

What? Can you please put more effort into writing English including in your PR title

**Review by Fikou — APPROVED** [review]

**Comment by necromanceranne** [comment]
Become a god of combat with this one simple trick

**Comment by ju45he** [comment]
Can yuo make this available on the blackmarket so I can max my unarmed effectiveness without removing the bartender's special little skillchip?

**Comment by necromanceranne** [comment]
This should never have ended up as a quirk and I had no intent of it ever being available to anyone else. It never should be. Don't increase its availability.

**Comment by MrMelbert** [comment]
I didn't really want the musical skillchip to be that available either if you want to axe that one

**Comment by MrMelbert** [comment]
Actually I could go either way. I was just afraid of people being annoying with it

**Comment by carlarctg** [comment]
> Actually I could go either way. I was just afraid of people being annoying with it

same, but ghommie convinced me and i am honestly rather surprised at how not overused it is. we need to keep in mind that github overreactions and over-concern is very much a big thing

**Comment by carlarctg** [comment]
> > combat is bad job is bad no quirk no good no no no, no quirk get combat no quirk get job contant, ver ybad not good
> 
> What? Can you please put more effort into writing English including in your PR title

no

**Pull request merged**
