### PR TITLE
Unfucks interactions between hypnoflashes and conversion antags.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
The following interactions now occur:

Traitor cultists are no longer able to brainwash their fellow cultists with hypno-flashes or brainwashing surgery
Traitor revolutionary are no longer able to brainwash their fellow revolutionaries with brainwashing surgery

Traitors who are NOT cultists will now deconvert cultists when they brainwash or hypnoflash them
Traitors who are NOT revolutionaries will now deconvert revolutionaries when they brainwash or hypnoflash them
Head revs are immune to hypnoflashes (as would be typical of their training)

Being converted to a cultist removes brainwashing and hypnosis
Being converted to a revolutionary removes brainwashing and hypnosis (alternative to this is to make brainwashed individuals immune to being converted to the revolution)

Admins still have the power to do whatever.
## Why It's Good For The Game
Adds a point of tension between traitor and conversion antags, which is something that dynamic excels with. Unmudies waters when players are dealing with both a syndicate brainwasher and a conversion antag. Split loyalties lead to alot of confusion, and generally aren't very fun for the converted or the converter.
This maintains the ability for traitors to still brainwash whoever they want as long as they aren't on the same conversion team, which they shouldn't be doing anyways.
## Changelog
:cl: itseasytosee
balance: Hypnoflash/brainwashing now deconverts conversion antags
balance: You can not Hypnoflash/brainwash your fellow conversion antags.
balance: Being converted by a conversion antag now undoes hypnosis or brainwashing.
/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
brainwashed cultists can no longer summon the entire cult to the SM because the traitor told them to 😔

**Comment by DaydreamIQ** [comment]
Personally I think it's hilarious that a traitor or sec team with abductor research can mind control team antags to turn against each other. Sec already have to be super aware of any non-mindshielded or noncleared crew. So why not have the paranoia go both ways?

**Comment by DustanHache** [comment]
Why is hypnoflash being made into a counterplay against revs and cultists? if you’re going to make it deconvert team antagonists, you need a better reason for it that just “no teamwashing” because that is definitely an admin issue and not a code issue. even if you *did* make it into a code effect, it is vastly harder to meet the conditions for a hypnoflash than it is for a conversion and would render it even less useful in the few circumstances where it’s overriding directives came into play.

**Comment by itseasytosee** [comment]
> Why is hypnoflash being made into a counterplay against revs and cultists? if you’re going to make it deconvert team antagonists, you need a better reason for it that just “no teamwashing” because that is definitely an admin issue and not a code issue.
> 
>  even if you *did* make it into a code effect, it is vastly harder to meet the conditions for a hypnoflash than it is for a conversion and would render it even less useful in the few circumstances where it’s overriding directives came into play.

heres the thing: the hypnoflash already IS counterplay to conversion antags, because if you are hypnotized you are no longer working for your team. This PRs intention is to cut the bullshit and make it clear to players who's side they are on.

**Comment by DustanHache** [comment]
> > Why is hypnoflash being made into a counterplay against revs and cultists? if you’re going to make it deconvert team antagonists, you need a better reason for it that just “no teamwashing” because that is definitely an admin issue and not a code issue.
> > even if you _did_ make it into a code effect, it is vastly harder to meet the conditions for a hypnoflash than it is for a conversion and would render it even less useful in the few circumstances where it’s overriding directives came into play.
> 
> heres the thing: the hypnoflash already IS counterplay to conversion antags, because if you are hypnotized you are no longer working for your team. This PRs intention is to cut the bullshit and make it clear to players who's side they are on.

the only reason it is an effective counterplay is because of the element of surprise, and given the amount of setup required to do it the PR is vastly undermining a already underutilized traitor item in the name of “clarification”. 

other methods for countering revolutionaries and cult exist, with the latter in particular having an entire syndicate item dedicated to them (the syndicate tome) and the former having many soft-counters scattered among tot gear not including the newly added contacts. all this does is make one of the more insidious tactics impossible and discourages traitors from trying to undermine group antagonists from the inside.

**Comment by necromanceranne** [comment]
One traitor with a hypnoflashbang about to game end the entire cult summon in one fell swoop.

**Comment by itseasytosee** [comment]
> One traitor with a hypnoflashbang about to game end the entire cult summon in one fell swoop.

Yeah but, they could already do that with a hypnoflashbang.

**Comment by necromanceranne** [comment]
It ain't a knock. I look forward to someone pulling it off.

**Comment by ExcessiveUseOfCobblestone** [comment]
The syndicate tome was initially just used to give someone the ability to use the bible so they could larp as a chaplain without being traitor tested pre dynamic, the consequences of being holy relevant to cult are just a side effect.

Traitors shouldnt be trying to undermine group antags from the inside at least on TG, their allegiance to the group antag supercedes personal interest. 

I think something that doesnt have any real IC backing like a hud indicator telling you who your real teammates are shouldnt be thwarted by IC-backed actions like someone getting brainwashed. It would make more sense to just not have the indicator at all at that point to not give the false sense people are actually not on your team (i mean they are but due to admin technicality they are not...)

**Comment by DustanHache** [comment]
> The syndicate tome was initially just used to give someone the ability to use the bible so they could larp as a chaplain without being traitor tested pre dynamic, the consequences of being holy relevant to cult are just a side effect.
> 
> Traitors shouldnt be trying to undermine group antags from the inside at least on TG, their allegiance to the group antag supercedes personal interest.
> 
> I think something that doesnt have any real IC backing like a hud indicator telling you who your real teammates are shouldnt be thwarted by IC-backed actions like someone getting brainwashed. It would make more sense to just not have the indicator at all at that point to not give the false sense people are actually on your team (i mean they are but due to admin technicality they are not...)

let me clarify: if a traitor who is not a cultist hypnotizes a cultist into undermining the cult, that is currently okay because the hypnosis objective takes priority akin to AI laws. meanwhile, a traitor who is converted by cult *shouldnt* be doing hypnos on their own team unless the cult intends to do a sleeper agent shenanigan against security after having already been discovered. this is also true and if discovered is an administrative issue, not a code issue. if you want to debate that, I suggest you make it a policy discussion. to quote the current decision on antag objectives:
> Antagonist Directive Priorities
In situations where you wind up with multiple simultaneous antagonist assignments (i.e. a [Revolutionary](https://tgstation13.org/wiki/Revolution) and a [Traitor](https://tgstation13.org/wiki/Traitor)), your team goals, objectives, and directives should take precedence. Furthermore, if someone had to go out of their way to convert you to their team, their goals, objectives, and directives become the priority. Refer to the following flowchart:
Brainwashing/construct orders/[Silicon](https://tgstation13.org/wiki/AI) Laws -> [Cult](https://tgstation13.org/wiki/Cult) -> [Revs](https://tgstation13.org/wiki/Revolution) -> [Blood Brother](https://tgstation13.org/wiki/Blood_Brothers) -> [Wizard](https://tgstation13.org/wiki/Wizard) Apprentice/[Abductor](https://tgstation13.org/wiki/Abductor) Teams/Other niche antags -> [Nuke Ops](https://tgstation13.org/wiki/Nuclear_Emergency) -> [Traitors](https://tgstation13.org/wiki/Traitor)

**Comment by itseasytosee** [comment]
> The syndicate tome was initially just used to give someone the ability to use the bible so they could larp as a chaplain without being traitor tested pre dynamic, the consequences of being holy relevant to cult are just a side effect.
> 
> 
> 
> Traitors shouldnt be trying to undermine group antags from the inside at least on TG, their allegiance to the group antag supercedes personal interest. 
> 
> 
> 
> I think something that doesnt have any real IC backing like a hud indicator telling you who your real teammates are shouldnt be thwarted by IC-backed actions like someone getting brainwashed. It would make more sense to just not have the indicator at all at that point to not give the false sense people are actually on your team (i mean they are but due to admin technicality they are not...)

cobby you have put this into words better than I ever could

**Comment by ATH1909** [comment]
> Traitors shouldnt be trying to undermine group antags from the inside at least on TG, their allegiance to the group antag supercedes personal interest.

traitors who are in the cult shouldn't be brainwashing other cultists (because cult loyalty > traitor loyalty, but not brainwashing loyalty). a non-cultist traitor sending a trojan horse into the cult to sabotage them from the inside is cool, though. it's like poisoning a hivemind. removing their hud icon or their powers removes the point.

**Comment by ATH1909** [comment]
impossible under this PR:
hypnobackfire

**Comment by itseasytosee** [comment]
> a non-cultist traitor sending a trojan horse into the cult to sabotage them from the inside is cool, though. it's like poisoning a hivemind. removing their hud icon or their powers removes the point.

I don't even hate this dynamic. It has the potential to be cool. It's just that currently there is no framework to support this in a healthy way. Hell even an in game recognition to the player that if these hypnosis objectives go against their group antags objectives they are allowed to betray their teammates

`if(iscultist(target)
              brainwashtext += "If these goals do not align with the wishes of nar-sie, you must go against your cult allies to complete them`

What would be ideal would be to have some sort of cult-betrayal-detector-system where cultists can be purged from the cult (either by some manual or automated process) so that they can be exorcised if they are traitorous, but we get to a level of complexity that makes the situation seem overly important for it's scarcity of occurrence.

The most elegant solution I could imagine is the one I have PRed here.

**Comment by DustanHache** [comment]
> What would be ideal would be to have some sort of cult-betrayal-detector-system where cultists can be purged from the cult (either by some manual or automated process) so that they can be exorcised if they are traitorous, but we get to a level of complexity that makes the situation seem overly important for it's scarcity of occurrence.

… you mean a health analyzer? because the only two things that can override a cultist’s duty to their team are the hypnoflash and brainwash surgery. the former can be detected via health analyzer. both are cured with brain surgery if i remember right.

**Pull request closed without merging**
