### PR TITLE
Experimentor change

### PR DESCRIPTION
**Pull request by Bawhoppen**
Readds selfxeno to experimentor
To anyone who didn't know what selfxeno was you could potentially make yourself into a xeno hunter (only hunter not drones, so you can't make a hive) by using the experimentor
Alot of things could go wrong in this process such as you making yourself into a borg or killing yourself and you need pretty damn good RNG to be able to do this

### CODE REVIEW

**Comment by PKPenguin321** [comment]
FREE EZ SELF ANTAGGING MACHINE FOR INFINITE GRIEF
YES LETS READD IT BEST IDEA GOGOGO

**Comment by Jordie0608** [comment]
But why?

**Comment by Bawhoppen** [comment]
fun
besides xenobio can easily do this way more reliably anyways

**Comment by PKPenguin321** [comment]
Yes but it requires actual work this is *LITERALLY A "MASH ONE BUTTON UNTIL YOU GET ANTAG" MACHINE*

HOW ARE YOU THIS RETARDED HOLY SHIT REEEEDEEEEEEEEEEEEDDDD

**Comment by PKPenguin321** [comment]
REEEEEEEEEEEEEEEE

**Comment by Bawhoppen** [comment]
pkp you have to keep resupplying the machine with tons of meme fuel (stock parts) and not every stock part works
so many things can go wrong like you getting turned into a borg/killed and its a really low RNG chance

**Comment by Bawhoppen** [comment]
you're a singular xeno who doesn't even have enough plasma to plant weeds *citation needed

**Comment by Core0verload** [comment]
@PKPenguin321, now you know how I felt about your krav meme PR.

**Comment by Bawhoppen** [comment]
^

**Comment by Cheridan** [comment]
(02:14:30 AM) Cheridan: you know that the borg disease has a cure right
(02:14:38 AM) Bawhoppen: SHUT THE FUCK UP CHERI
(02:14:48 AM) Bawhoppen: THAT WAS SUPPOSED TO BE SLIPPED UNDER THE RUG

**Comment by Bawhoppen** [comment]
no logs allowed this is unjust
besides its annoying to cure in time before it takes you over and transforms you

**Comment by Fox-McCloud** [comment]
because this isn't going to be used to self-antag by shitters and murder half the crew because "lol I xeno".

**Comment by Bawhoppen** [comment]
you act like the entire crew can't take down a single xeno
its like 3 laser shots to kill it honestly
a greyshirt can make a flamethrower to immediately kill it

**Comment by Fox-McCloud** [comment]
>you act like the entire crew can't take down a single xeno

And you're assuming they're just going to sit in the chamber and wait for themselves to explode as opposed to finding some place in maintenance to grow to maurity then wreck havoc. Xeno event only spawn a single larva, and they don't get to choose where to spawn. This can easily spawn multiple, and they get, to a degree, to choose where they start off at.

**Comment by Bawhoppen** [comment]
I think you misunderstand how it works.
How it works is it sprays you with a gas that gives your character xeno microbes, which after a short bit transform you into a xeno HUNTER. There is no way to get huggers, become a queen or drone, or create any other xenos aswell.

**Comment by Fox-McCloud** [comment]
>I think you misunderstand how it works.

I stand corrected there. Even so, the amount of damage one hunter can wreck is.....very high, before stopped.

**Comment by Bawhoppen** [comment]
I don't think it would be that hard to take down a single xeno,
compared to the regular antags we have, 1 hunter just takes a few laser shots to be killed (and debrained for R&D)
a game of hunt the xeno isn't that big of a deal for highpop crew, especially when one assistant can make a flamer and easily roast them

**Comment by FantasticFwoosh** [comment]
Here was me actually hoping the experimentor would actually be rebalanced or replaced to be a meaningful machine to science rather than the crazy RNG wild ride slot casino that is that defunct and underused room.

**Comment by Bawhoppen** [comment]
I want to improve it later but for now I just wanted to get this back in

**Comment by Niknakflak** [comment]
:-1: shit

**Comment by PKPenguin321** [comment]
>le "he made a pr I don't like so ignore him meme"

Bawhoppen you genuinely have autism

**Comment by GunHog** [comment]
Good luck. I was forced to remove this after tons of admins rode me like a rented scooter. I changed it to acid for the lulz.

**Comment by Bawhoppen** [comment]
@PKPenguin321 what are you even talking about

**Comment by Bawhoppen** [comment]
also @GunHog tg is not the same game as it was back then
we have matured

**Comment by PKPenguin321** [comment]
yes we've grown out of fun fun is bad now
it's so bad in fact that let's add a feature that gives you FREE ANTAG FOR MASHING ONE BUTTON

**Comment by Bawhoppen** [comment]
PKP you need to constantly refuel it and not even with the same item, its difficult and annoying process to do with hazards along the way and possiblity of turning into a borg
its a low RNG chance

**Comment by PKPenguin321** [comment]
a low RNG chance that you keep rerolling for by mashing the same button
people did it before we removed it and they will do it again

**Comment by KorPhaeron** [comment]
Should I let this sit for 2 weeks until a random maintainer closes it or be the bad guy and close it now

**Comment by Fox-McCloud** [comment]
Be the bad guy you were secretly born to be, @KorPhaeron

**Comment by Bawhoppen** [comment]
@PKPenguin321 seriously
you have to keep feeding it new materials and it can reset and you have to find a different material then to use, and you can be killed/borged by the machine
back when it was still able to be done most rounds I tried to get it I didn't succeed and the shuttle came first or I died, and now since it can spray sulfuric acid, the chance is even lower than it was before

**Comment by Bawhoppen** [comment]
Okay. So what I have done is added a crapton of different lethal outcomes when attempting this process. This will make being able to do this successfully pretty damn rare. It would under normal circumstances be much safer and rational to just do xenobio and get some magicarp instead.
And before you think that if you just wear the biosuit you'll be safe, you're wrong. I added some of the goof pyrotechnic shit like Phlogiston to burn you alive potentially.

**Comment by GunHog** [comment]
@Bawhoppen Have a look at this: https://github.com/tgstation/-tg-station/compare/master...GunHog:Increases_Experimentor_Murderbone?expand=1

I changed smoke mechanics in the Experimenor here, but I did not want to upload it at the time. Feel free to test and use it. What this does is use proper smoke mechanics, in addition to _filling the entire chamber_. I always found it stupid that all I had to do to avoid getting gassed is make one step back.

**Ignore lines 331-334. Lube does not work properly with smoke in this case.**

**Comment by Bawhoppen** [comment]
ah thanks very nice will do probably

**Comment by GunHog** [comment]
Oh, update, I think the lube smoke DOES work. It was water smoke that was causing issues.

**Comment by YotaXP** [comment]
All these comments about it being "self-antagging".

Why would a researcher who turned themselves into a xeno be considered an antag?  Shouldn't they still be of their right mind, and accountable for harm they may inflict upon others?  If anything, it should be called "self-validing".

**Comment by TechnoAlchemisto** [comment]
I remember back in the day when this used to work and I could print a shit ton of stock parts from rnd and then go around killing people, those were the days

**Comment by Bawhoppen** [comment]
its like 5x times harder and dangerous now but I had to do that so theres a chance it would get merged

**Comment by TechnoAlchemisto** [comment]
i want to support this so I can abuse it again but i have to be self aware and know ill get pissed if I get killed by a player xeno

**Comment by Jordie0608** [comment]
@YotaXP You're right, it doesn't make them an antag. It however also doesn't stop them from doing this anyway and killing a bunch of people before they're banned by admins. This was a real pain before and it'll be one again

**Comment by Bawhoppen** [comment]
like I said I make it much harder to do successfully and not be poisoned/burned alive
it will in most cases probably be easier to just do xenobio than this

**Comment by PKPenguin321** [comment]
Even worse PR with the lethality changes, makes the experimentor incredibly shit to use at all since now it will kill you half the time

:-1: x 40 gorillion

**Comment by Bawhoppen** [comment]
are you autistic pkp
this is only for the gas mode anyways you retard

**Comment by PKPenguin321** [comment]
bawhoppen you are being awfully hypocritical calling me autistic like that :^)

**Comment by Bawhoppen** [comment]
i am legally autistic

**Comment by Bawhoppen** [comment]
okay well I begged every maintainer and they all said no so i guess I'm outta lucky
...
...
...
...
...
for now

**Pull request closed without merging**
