### PR TITLE
Adds New Sprite For AI Slipper

### PR DESCRIPTION
**Pull request by JohnTheDonut**
## **Adds New Sprite For AI Slipper**
Adds a proper sprite to the AI slipper, this is to remove the ugly looking green and grey motion sensors mainly located on AI Mini Satellites or depending on the map AI Room on station. The reason maps are edited here in this simple sprite change is because someone decided to var edit "icon_state" on every AI Slipper on all maps, this reverts this so that the new sprite will actually work and display. 

## **Images**
**New Sprite - Red Box**
**On Sprite**
on

**Off Sprite**
off

**Animation**
animation
_Gif looks jittery and has bad quality because of the recorder used._
## **Changelog**
:cl: Tofa01
Imageadd: Added new sprite for the AI Slipper.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
I am sad that it is not animated.. :(

**Comment by Anonmare** [comment]
Does the foam it makes still cause brute upon slipping?

**Comment by Tofa01** [comment]
I am yet expirenced enough to do animations with spriteing sadly I will possibly update this later when I learn to do that. Also I am unsure if it does brute damage I have just changed the spire to something better looking.

**Comment by Tofa01** [comment]
@GunHog Figured out how to make a animated sprite, uploading a GIF of what it looks like soon.

**Pull request merged**
