### PR TITLE
Adds Military Belts to the standard Uplink

### PR DESCRIPTION
**Pull request by SconesC**
They're pretty efficient and honestly cheap for the sheer amount of stuff they can hold.

Merciful inventory management for the traitors who need to carry a ton of extra magazines for their murder spree.

Excluded from Nuke because they get them for free and there is literally no reason to ever buy more.

### CODE REVIEW

**Comment by Aloraydrel** [comment]
Finally I can Murderbone™ with ease!

**Comment by Cebasiz** [comment]
not a bad idea. more options are always nice

now all you have to do is reduce the cost of the stechkin so i can justify using it :^)

**Comment by SconesC** [comment]
9 TC for supressable 4shot crit with autolathable magazines isn't bad

I could do with it being 6 instead

**Comment by Cebasiz** [comment]
well, 12 tc for the supressor.. which i don't really see a use for considering the inhand sprite is enough for anyone to dogpile you in seconds. as a defensive tool it's marginal; if you are caught at anywhere inside taser range at anytime you are toasted; even at stechkin optimal range (outside of taser) you can actually be beaten by a disabler;

i'd like to see the 'basic' traitor weapons become cheaper, so that more loadouts can afford basic self-defense options rather than simply having to rely on never being caught. it would tune up the amount of actual traitoring getting done, i think.

OT i guess, but esword should probably be cheaper too. it's pretty useless on it's own. no reflect chance, melee range, no stun, relatively low knockdown%

the belt's a good idea though, it's one of the best pieces of gear the nukeops get. are you going to make it the distinctive red color or should it be painted like a toolbelt?

**Comment by SconesC** [comment]
It's not exactly a stealth item

It's for people who want to go postal

**Comment by Cebasiz** [comment]
fair enough, it'll be good for anyone who can lathe ammo, especially for revolvers

entire belt full of revolver ammo

send help

**Comment by Lumipharon** [comment]
stechkin comes with a free suppressor, in traitor rounds afaik.

**Comment by Cebasiz** [comment]
whoa since when i bought one like a week ago

**Comment by Lumipharon** [comment]
Hm, there was a PR or something for it a while back - maybe never got merged?
I don't buy stechkins because they're overpriced either way.

**Comment by SconesC** [comment]
This is merge-ready by the way, I'm not making pistol changes in this PR

**Pull request merged**
