### PR TITLE
Removes north star gloves

### PR DESCRIPTION
**Pull request by improvedname**
Shitty brute ass forced meme
bad martial art literal standard holoparasite reskin but for yourself
Lags players out litteraly broken
spams chat fucking shitty

### CODE REVIEW

**Comment by deranging** [comment]
dont do it

**Comment by Shadowflame909** [comment]
I personally wish it did stamina damage, like a boxing glove. But I don't dig this removal.  Just make it less laggy.

**Comment by improvedname** [comment]
we cant keep shitty code in the codebase

**Comment by Shadowflame909** [comment]
Tell that to the spider that's in the HOS's office. Also *Insert comment about thing to make everyone offended*

**Comment by CitrusGender** [comment]
please add "i ded" to this.

**Comment by improvedname** [comment]
spider in hos office doesnt lag other players out with its main function though.

**Comment by Shadowflame909** [comment]
Then instead of removing it fix the lag?

**Comment by improvedname** [comment]
i dont see you opening a pr to fix said issue mr.

**Comment by improvedname** [comment]
so obviously you don't care

**Comment by Shadowflame909** [comment]
I still see you removing things you don't like under the guise of "bad bugs!1!" So obviously you don't care about the enjoyment of the game as long as you can't "win." Reee

**Comment by improvedname** [comment]
Again i don't see you opening a pr shadow.

**Comment by Shadowflame909** [comment]
Why would I open a PR to fix non-existant issues? You haven't filed an issue report?

**Comment by GuyonBroadway** [comment]
Huh, I didn't know this lagged people, in testing it worked fine...

**Comment by Shadowflame909** [comment]
It was a lie to give some claim to there "IM DED" PR.

**Comment by Jujumatic** [comment]
lmao get fucked salt bitch

**Comment by improvedname** [comment]
Omegalul

**Comment by ComradeNecron** [comment]
sounds like you were shocked

**Comment by epochayur** [comment]
great track record so far, improvedname

**Comment by 81Denton** [comment]
an effort was made

**Pull request closed without merging**
