### PR TITLE
Copper mineral

### PR DESCRIPTION
**Pull request by Renem0**
## About The Pull Request

Adds a Copper mineral to the game that can be mined. At the moment it will spawn roughly as often as silver minerals. The ore can be smelted, which will create a copper sheet. This sheet can then be used to create copper tiles, walls, airlocks, and doors. These objects will look orange with slight red tint. The copper door (mineral door) is also added to the list of possible doors that can appear when using the door wand. The copper material is available for mint, recycler, mech fabricator, although not used for mechs or otherwise yet. New sprites are of course included, and can be seen in the figures below.

copper

copper2

## Why It's Good For The Game

- Adds a new mineral for miners to mine.
- Gives the greytide that is too poor for silver or gold the ability to bling out their illegal dens with a dab of exotic orange.
- A new material for future use that could be implemented to be used for mech creation and possibly RnD tech. Other future uses could be for constructing items such as cable wire (makes more sense than metal at least), and possibly electronic circuits.

## Changelog
:cl: Renem0
add: Added copper mineral that can be mined. Roughly as common as silver, but worth only one third of silver in terms of points (5). The ore can be smelted into copper sheets.
add: The copper sheets can be used to build floor tiles, walls, doors, and airlocks. These will look orange with a red tint.
add: The door wand can now also spawn copper doors.
add: Added copper as a material to different machines such as recyclers, mech fabricators and RnD. Currently not used for any construction however.
imageadd: Added new sprites used for the different copper objects and turfs.
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
But why though? We already have way too many pointless materials.

**Comment by ninjanomnom** [comment]
If we had good systems in place for new materials getting automatically integrated into construction and such it'd be worth just adding a bunch of alternate materials but as it is we'll need a really good reason why any new material should be added over using an existing one.

**Comment by fludd12** [comment]
> systems in place for new materials getting automatically integrated into construction and such

🤔 
Why do you give me horrible ideas.

**Comment by ninjanomnom** [comment]
I consider it my job to try and bait people into coding refactors that make existing systems more generic

**Comment by Tlaltecuhtli** [comment]
@fludd12 no minecraft

**Comment by Renem0** [comment]
> If we had good systems in place for new materials getting automatically integrated into construction and such it'd be worth just adding a bunch of alternate materials but as it is we'll need a really good reason why any new material should be added over using an existing one.

That's fair reasoning in my book. In hindsight I should have guessed this add would do more harm than good at the moment.

**Comment by nero1024** [comment]
Make electronic items require copper. That should give it some more usage.

**Comment by fluffe9911** [comment]
In b4 someone destroys lavaland trying to mine copper

**Comment by PKPenguin321** [comment]
Circuits in circuit printers could totally use copper instead of glass

**Comment by ishitbyabullet** [comment]
Eh, just give it glass, copper, and metal for those that already had glass and metal. After that, add copper to wherever else it might be needed.

Honestly, this material makes me think two things:
1. oranges is gonna build anything he makes ingame with this primarily 
2. It reminds me of the wizard walls and floors in goonstation 2016.

**Comment by Daxxed** [comment]
Add tin and allow both to be smelted into bronze by throwing the ore on fire/lava.
Then add basic medieval weaponry and now ashlizards can pretend to be dorfs

**Comment by Barhandar** [comment]
>Add tin and allow both to be smelted into bronze by throwing the ore on fire/lava.
Then add basic medieval weaponry and now ashlizards can pretend to be dorfs

And this, kids, is why "design space" is not a valid excuse in itself.

**Comment by europaisch** [comment]
The sprites could be better - in particular, the floor and stack ones.

**Comment by improvedname** [comment]
Next up tin

**Comment by anconfuzedrock** [comment]
ooh, brass but ugly, (not) interesting.

**Comment by bigfatbananacyclops** [comment]
this is nice, more variety to mining, i would like if it had relation with conductibility in-game mechanics, this should clearly be a material for engineering,power stock parts

**Comment by SpaceManiac** [comment]
> If we had good systems in place for new materials getting automatically integrated into construction and such it'd be worth just adding a bunch of alternate materials but as it is we'll need a really good reason why any new material should be added over using an existing one.

Could you clarify what systems you think are lacking? It's already trivial to add crafting recipes for new materials, change `istype()`s in manually-coded construction, or add the new material to the requirements of a lathe design.

**Comment by ninjanomnom** [comment]
Those systems aren't automatic. Each additional material needs to be added manually to all such things and imposes a maintenance cost as a result. If we had a system where you basically just made a material type and it gets automatically integrated into building walls, doors, etc it'd be fine to add a new materials since each new material would add very little code and be contained.

As it is a new material changes swathes of code across the codebase and to merit such a thing I feel a material needs to have a good reason to exist beyond "it looks different"

**Comment by boodaliboo** [comment]
> In b4 someone destroys lavaland trying to mine some copper

hi fluffe owo

**Comment by habader** [comment]
have them carry shocks through them so you can use walls as wires and doors as switches and then walk into wall and fry your dick off

**Comment by FloranOtten** [comment]
> > But why though? We already have way too many pointless materials.
> 
> I would not call it pointless, but limited at the moment yes. It can also be expanded upon in future updates?


Well that's just pointless with extra steps.

**Comment by improvedname** [comment]
then we add a recipe to combine copper and tin for bronze

**Comment by ninjanomnom** [comment]
I'm not against new materials inherently but with our current code adding a new one needs a better reason than just cosmetics or displacing existing materials. This isn't a full denial of adding copper but take some time to discuss with people how it could be added in a more interesting way.

**Pull request closed without merging**
