### PR TITLE
Implements a new Announcements voice that we can generate new lines for. (NOT VOX)

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

This implements a new AI voice that we can use to generate new announcement audio from. The model ID for tacotron-2 usage is 11yNu27XK_x_1QCf5hghOhKXCZ0zau8uI if you take advantage of the /mlp/ board's voice colab notebooks. I don't know why /mlp/ is responsible, they just are.

## Why It's Good For The Game

We have a metric fuckton of announcements with zero voicelines, that just reuse a station beep or the Attention sound effect. This will allow us to implement new lines.

Examples of some of the audio:
meteors.ogg | https://file.house/kOs-.ogg
shuttlecalled.ogg | https://file.house/pxPi.ogg
animes.ogg | https://file.house/Gqb6.ogg

I am not 100% set on this voice, however. I have an alternative voice prepared that sounds like this, if the first voice is not a fit for /tg/station.
https://file.house/lRYJ.wav
https://file.house/dlTP.wav

## Changelog
:cl:
soundadd: The Announcements system has received a firmware update.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Why is it so.... gruff?

**Comment by zxaber** [comment]
Not a super huge fan of either of those. If we're gonna use any AI voice that learned from copy-written material, we should just use the Glados one.

https://vocaroo.com/1j0XX33arWU

Yeah, it's basically cheating, but at least it sounds like a standard sci-fi AI.

>I don't know why /mlp/ is responsible, they just are.

Word on the grapevine is they want to make more episodes or something and were like one of the few groups willing to put forth the work of isolating and tagging all the voice clips from a media/show.

**Comment by Archanial** [comment]
Sounds like robo tf2 soldier.

**Comment by HiKewne** [comment]
I don't... Hate them. They work, which, by itself, is simply amazing, but there's too much noise on the voicelines and it makes my head hurt.

Also, as much as I'd love to have soldier tell me the shuttle's been called, i don't think it fits into the game, and neither do the other voices. They work so good in imitating the emotion on the voice that isn't as robotic as I'd like them to.  On that side, i do prefer GLaDOS's voice by a lot.

**Comment by Pumpkinoe** [comment]
soldier tf2
also hurts my ears please just give us the glados one if you're really intent on changing them

**Comment by AnonymousNow** [comment]
Wait. The Soldier? Neat.

**Comment by tralezab** [comment]
really gotta remove the grating but i would appreciate... being able to choose between the two 😳 

i mean you can perfectly envision people who play this game picking both the anime one and the soldier one

**Comment by MMMiracles** [comment]
image
sexy announcer voicepack when

**Comment by Qustinnus** [comment]
god these sound awful. If I wanted to hear something like this I'd ask someone on Gmod to use stereo mix to play the Mann vs Machine audio or my little pony episodes through voice chat.

**Comment by Dorsisdwarf** [comment]
Like the idea, but neither of these voices sound like an announcement (or remotely good, ow my ears)

**Comment by trollbreeder** [comment]
I never knew i wanted the soldier from tf2 to scream "THE EMERGENCY SHUTTLE HAS BEEN CALLED" into my ear. Announcement voicepacks when?

**Comment by optimumtact** [comment]
we dont' need multiple announce voice packs this is just rsc bloat.

**Comment by Iamgoofball** [comment]
@optimumtact this isn't an addition, thsi is a replacement

**Comment by optimumtact** [comment]
sound shit, probably won't merge

**Comment by Anonmare** [comment]
I'd hopnestly go for either the GLaDOS or any of the Pony voices, since they're the most crisp and "natural" sounding. Heck, even the Narrator would work, but someone'd have to clean up the crust.

**Comment by HomocidlePancakes** [comment]
If it can say the N-word, I won’t mind it being a pony.

**Comment by CPTANT** [comment]
Thumbs up for the idea and mechanic, thumbs down for this particular voice.

Needs to be a lot slower and mellow with less crackling.

**Comment by trollbreeder** [comment]
if you can get it to speak like the original female announcer voice, and add new announcements and replace outdated ones (the radstorm one desperately needs a replacing), and get rid of the crunchyness, that'd be great

**Comment by AnonymousNow** [comment]
How long/intensive a process is it to make a voice pack for a system like this out of recorded audio, out of interest?

**Comment by Iamgoofball** [comment]
You need 60 to 120 minutes of audio and a few days.

**Comment by zxaber** [comment]
Depends a bit on which one you use (fifteen.ai has a character limit so you might need to string a few separate lines together in Audacity), but most of the actual work is just figuring out how to spell the words in a way that produces the pronunciation you want.

**Pull request closed without merging**
