### PR TITLE
fix weed hotspot

### LINKED ISSUE #17500: Hotspots are layered under alien weeds
Invisible fires killing aliens wew,

### PR DESCRIPTION
**Pull request by Iamgoofball**
fixes #17500

### CODE REVIEW

**Comment by ChangelingRain** [comment]
This is actually already fixed.

**Comment by KorPhaeron** [comment]
Wont this put people under it?

**Comment by Iamgoofball** [comment]
no it isn't?

weeds are at layer 5

hotspots are at layer 2.03

**Comment by Iamgoofball** [comment]
@KorPhaeron yeah, it looks cooler too

**Comment by ChangelingRain** [comment]
>weeds are at layer 5

did you even bother to check the layer????

**Comment by Iamgoofball** [comment]
>>>i was looking at vines not weeds

nice

**Pull request closed without merging**
