### PR TITLE
Monkeymode tweaks

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: During monkeymode, the shuttle will autocall after 45-60 minutes.
add: Monkeys now get a special little hud that tells them how many monkeys/infected people there are!
add: The heart of freedom now uses a status effect that lasts for ~25 seconds.
/:cl:

### CODE REVIEW

**Comment by Potato-Masher** [comment]
Can monkeys operate machinery? Because if so...

>load biomass into biogenerator 
>produce monkey cube x30 
>call to arms
>monkey screams echo the halls

**Comment by sawrge** [comment]
stop

**Comment by Buggy123** [comment]
Monkeymode replaces revs when?

**Comment by Buggy123** [comment]
Why?

**Comment by MoreRobustThanYou** [comment]
i'll reopen when i got this in a working state

**Comment by FantasticFwoosh** [comment]
Most machinery has dexterity checks, im not sure about the bio-generator, but im also quite confident they can't do manual xenobiology either if the console is too advanced for them.

- they might be able to make cubes out of already collected grey slimes though

**Comment by MoreRobustThanYou** [comment]
i managed to get the hud done, so i'll reopen it

**Comment by YakumoChen** [comment]
I have tried to make monkey cubes as a xeno before using xenobio machines, it doesn't work.

**Comment by FantasticFwoosh** [comment]
Its not a necessity if you just find a skill orientated way around it, like summoning NPC monkeys spontaneously out of vents on a long cooldown.

**Comment by praisenarsie** [comment]
y'know this would be way better if you replaced the monkeys with spiders

because i think monkey should stay what it was before until you decided to change it

**Comment by FantasticFwoosh** [comment]
I can't pull it back out (ntrhut), but i did have a thread on the forums that incorporated a vigilante gang tool esque system for monkey virus carriers that might fit in here.

With spiders it'd be adequate if it was attributable to midwives, since there does tend to be a significant amount of NPC spiders after the player populated ones dry up.

**Comment by Armhulen** [comment]
y'know this would be way better if you replaced the monkeys with spiders

because i think monkey should stay what it was before until you decided to change it

**Comment by MoreRobustThanYou** [comment]
It's not a second overhaul anymore, it's just tweaks now.

**Comment by GuppyLaxx** [comment]
So can you fix the fact you can't deconvert people at all or

**Comment by MoreRobustThanYou** [comment]
I mean, you can move someone's brain into a human. or just kill and clone when they get infected. or just kill the monkey and clone it

**Comment by GuppyLaxx** [comment]
So time to kill every person that gets bit, and make killing yourself the moment you get bit the meta, got it.
Seriously though, fix that.

**Comment by MoreRobustThanYou** [comment]
I purposely removed bananas curing jungle fever.

**Comment by Bawhoppen** [comment]
Bland changes that make the gamemode less dynamic, blahblah, you've heard me say it before

**Comment by Cyberboss** [comment]
@MoreRobustThanYou

**Comment by MoreRobustThanYou** [comment]
@Cyberboss no pc access rn, check this again in about 5-6h

**Comment by PKPenguin321** [comment]
reee i want this one

**Pull request closed without merging**
