### PR TITLE
Add flushed emoji

### PR DESCRIPTION
**Pull request by JJRcop**
it's a toilet

image

I just downscaled the toilet sprite

### CODE REVIEW

**Comment by plapatin** [comment]
nice

**Comment by ExcessiveUseOfCobblestone** [comment]
i was hoping it was going to be the veryflushed emoji on our discord

**Comment by Rowelll** [comment]
what if we kissed in github 😳

**Comment by ohsshoot** [comment]
> 
> 
> what if we kissed in github 😳

**Comment by PKPenguin321** [comment]
@ExcessiveUseOfCobblestone then the joke of this PR worked on u. u just got fricken beaned y ou idiot!!!

**Comment by ExcessiveUseOfCobblestone** [comment]
next: beaned emoji but it's just a picture of the soybean

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
