### PR TITLE
Gives the MegaSeed vendor some love; Gives the seeds categories and organizes them 

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.

## Why It's Good For The Game
Sorts the seeds out from one major category to the best of my ability.

They're now split up amongst Fruits, Vegetables, Flowers and Miscellaneous.

image

And yes, the contraband section still works.

## Changelog

:cl: Jolly
qol: MegaSeed vendors had their seeds distributed through 4 categories; Fruits, Vegetables, Flower and Miscellaneous. 
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
While tomatoes are technically fruits, they are also vegetables. Vegetable is a culinary distinction, not a botanical one.

As a solution to this conundrum, I propose that tomatoes have a 50% chance to be in either category, determined at the start of each round.

**Comment by Jolly-66** [comment]
I'm going to edit the list later to reflect what the seeds match in code.

**Comment by Jackal-boop** [comment]
> While tomatoes are technically fruits, they are also vegetables. Vegetable is a culinary distinction, not a botanical one.
> 
> As a solution to this conundrum, I propose that tomatoes have a 50% chance to be in either category, determined at the start of each round.

I support this

**Comment by Jolly-66** [comment]
So it turns out that this list is actually accurate, well, was for the most part.

I blame the other coders.

**Comment by AdipemDragon** [comment]
You may have forgotten the 5th category when you list said 5 in the changelog, unsure if that's an intentional fun guy joke

**Comment by Jolly-66** [comment]
> You may have forgotten the 5th category when you list said 5 in the changelog, unsure if that's an intentional fun guy joke (also, Thank you for the categorisation)

I sometimes forget what I make. Oops. Thank you no less.

**Comment by JohnFulpWillard** [comment]
> As a side note, I don't know if its me or TGUI, but mushroom and flower don't seem to work, and there aren't any similar ones I could use.

Sounds like it's you, please try to get them proper icons

**Comment by Jolly-66** [comment]
I'll make custom icons later in the week using tgfont.

**Pull request merged**
