### PR TITLE
Adds love triangle to valentines day event

### PR DESCRIPTION
**Pull request by JJRcop**
:cl:
tweak: Adds 4% chance when assigning a valentines day date to also assign someone else to the same date, but your date will still have you as their only date.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
You mean catfishing.

**Comment by kevinz000** [comment]
EVIL MAN

**Comment by KorPhaeron** [comment]
4% us pretty high

**Comment by XDTM** [comment]
Assuming ~50 people it's about 2 people with a fake valentine, and probably most people won't really care about the objective enough to notice, i think.

**Comment by dannno** [comment]
did you just hardcode cucks into the game with a random chance to be one

**Comment by FantasticFwoosh** [comment]
Adminnote - "Killed someone non-antag in the valentines day event because of a love triangle pairing, their response was that they were roleplaying a Tsundre character and therefore mad."

**Comment by Supermichael777** [comment]
its an objective your an antag

**Comment by KorPhaeron** [comment]
@optimumtact 

Didn't you say no to this

**Comment by PKPenguin321** [comment]
He sad no to any mention of the word "cuck"

**Comment by optimumtact** [comment]
I mean I have no strong opinion on the feature itself, but it's not like our players need any incentive to beat each other to death in a usual round anyway so I dont' see the point

**Pull request merged**
