### PR TITLE
2 new lavaland ambience tracks

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus 
 add: some ebic new lavaland ambience tracks.
/:cl:

cant sleep. making tracks yo.

https://vocaroo.com/3Jri4eIEJ9E

https://vocaroo.com/iN3NkeAX58w

### CODE REVIEW

**Comment by Niknakflak** [comment]
I made the original ambiance for lavaland.

First one using having that back beat kinda sucks as it is not ambient at all.  
Second one is quiet but fine I suppose.

Not that you'll do anything in response to this comment anyway though.

**Comment by Qustinnus** [comment]
If you want someone to do something with your comment maybe not act like a prick in it by saying the person wont acknowledge it anyways.

**Comment by Qustinnus** [comment]
and I added the other 8 tracks we use for mining lol

**Comment by Tlaltecuhtli** [comment]
make it play lustmord playlist lol

**Comment by trollbreeder** [comment]
Minecraft cave sounds

**Comment by Moja10** [comment]
Add the ability to pepeJAM with your carbon head because these are bangers

**Comment by jtroopa** [comment]
Kinda just wanna insert the lego rock raiders soundtrack for lavaland.

**Comment by Whoneedspacee** [comment]
On the subject of nik’s comment could you upload the first track without the back beat? Interested if it would sound more ominous somehow.

**Comment by tmtmtl30** [comment]
are these also slowed down bad apple excerpts

**Comment by Qustinnus** [comment]
no theyre slowed down ameno excerpts

**Pull request merged**
