### PR TITLE
Removes references and Cleanses hypocrisy

### PR DESCRIPTION
**Pull request by Niknakflak**
> TechnoAlchemist Wrote in PR #17425 
> 
> """i'd prefer references to it stayed more or less out of this game"""
> 
> "Only references to things I like are allowed"

Cleanses Hypocrisy

### CODE REVIEW

**Comment by Incoming5643** [comment]
One (1) unwarranted game reference is permissible per game series. 

Further references are only allowed if it meets one of the following conditions:

1. It lines up with the first reference
2. It makes thematic sense with space station 13
3. It's really clever/funny

**Comment by PKPenguin321** [comment]
this is a reference?

**Comment by Niknakflak** [comment]
http://darksouls.wikidot.com/gwyn-lord-of-cinder

**Comment by RemieRichards** [comment]
@PKPenguin321 
>Gwyn
>Ash

It's Dark Souls

**Comment by Incoming5643** [comment]
Space station 13 is the dark souls of references

**Comment by coiax** [comment]
@Niknakflak is lord of removing alcohol related references. Let no libation or liquor be exempt from their scorn.

**Comment by TechnoAlchemisto** [comment]
i'm sorry i didnt like a undertale reference niknak i had no idea you were so sensitive

**Comment by KorPhaeron** [comment]
Why are you removing the ash part though, ash being on lavaland is not a reference

**Comment by KorPhaeron** [comment]
I also hope you can see the difference between an otherwise normal/functional item having a subtle reference in the game/desc that nobody knew was a reference, and something like the undertale noises.

And I like undertale by the way, I've played more undertale than all the souls games put together.

**Comment by Niknakflak** [comment]
Do you want me to change the description

**Comment by MMMiracles** [comment]
what if we just, like, didn't touch it at all instead of trying to change it

**Comment by Niknakflak** [comment]
Can't do that, references need to be purged of course

**Comment by MMMiracles** [comment]
Ian is a reference to cowboy bebop remove corgis

**Comment by KorPhaeron** [comment]
It's a reference to erro's dog named Ian actually

**Comment by MMMiracles** [comment]
my entire life is a lie

**Comment by Niknakflak** [comment]
I have a corgi, does that make it a reference to my corgi too?

**Comment by KorPhaeron** [comment]
You added a corgi wheelchair in reference to your corgi, you're outta control

**Comment by Niknakflak** [comment]
No that was incoming, I didn't add that

**Comment by PKPenguin321** [comment]
close this PR
end this

**Comment by KorPhaeron** [comment]
I guess I gotta ban @Incoming5643 as well for adding references to his favourite anime, The Life of Niknak

**Comment by Archie700** [comment]
The Life of NikNak sounds like a pretty shit anime.

Perfect for /a/.

**Comment by Niknakflak** [comment]
what is /a/ and why is archie shitposting all over my PR, get back to observing deadchat

**Comment by KorPhaeron** [comment]
>what is /a/ 

someone get this redditor out of here

MODS

**Comment by Niknakflak** [comment]
We've been over this, I don't 4chan or reddit

**Comment by KorPhaeron** [comment]
MODS

**Comment by Iamgoofball** [comment]
DELETE THIS

**Comment by Archie700** [comment]
>what is /a/

Just when I think NikNak can't embarrass himself any further, he says things like this.

**Comment by Niknakflak** [comment]
That would be an insult, but it came from you.

**Comment by ike709** [comment]
Fighting over references, one of /tg/'s greatest memes.

**Comment by Incomptinence** [comment]
Eh nik naks right.

**Comment by PKPenguin321** [comment]
No he isnt

**Comment by AdamElTablawy** [comment]
Can we just remove niknak

**Comment by Niknakflak** [comment]
No

**Comment by Zilenan91** [comment]
Yes

**Comment by Niknakflak** [comment]
It's actually decided that we are removing Zilenan91 from the community.  Goodbye, you had your chance

**Comment by TechnoAlchemisto** [comment]
rip zil

**Comment by AdamElTablawy** [comment]
accurate tag

**Comment by MMMiracles** [comment]
hide niknak threads
ignore niknak posts
do not reply to niknak posters

**Comment by pudl** [comment]
niknak did nothing wrong

**Comment by Niknakflak** [comment]
Excuse me, I have two thumbs up, that is not universally disliked.  Please remove that blatantly false tag

**Comment by Jalleo** [comment]
Next up how should te miners uniform look like more news at those PRs. Tbh i dont care either way with this PR its all nuances. Cant we just all eat some cake or is the cake a lie?

**Comment by TechnoAlchemisto** [comment]
what

**Comment by KorPhaeron** [comment]
I was gonna just leave this forever until someone else closed it so you could be mad at someone else but I'm trying to clean the PR list so I'd rather skip to the end

**Pull request closed without merging**
