### PR TITLE
A handful of fixes.

### LINKED ISSUE #5101: Medbots won't target people on top of tables
Even when they could reach a dude, they'll never inject if he's on top of a table.

### LINKED ISSUE #6068: Ghosts can go through handheld teleporter portal, but not the stationary teleports around bridge or on AI sat.
A bit inconsistent.

### LINKED ISSUE #6109: AI hologram drifts in gravityless areas
Realism

### LINKED ISSUE #6288: Check antagonists does not list bursted blobs
Active blobs arent listed in Check antags

instead the message is something like this:
Blob   
Progress: 135/700 
Blob not found! 
Blob not found!

### LINKED ISSUE #13887: ghost ears in game pref window shows opposite of what is selected
reported by same guy name leo in dead chat

### PR DESCRIPTION
**Pull request by AnturK**
~~Fixes #6109~~
Fixes #6068
Fixes #6288
Fixes #13887
Fixes #5101

### CODE REVIEW

**Comment by Bawhoppen** [comment]
kor made a fix for the first one already though

**Comment by duncathan** [comment]
There's already a fix up for the holograms....

**Comment by AnturK** [comment]
Dang

**Comment by Bawhoppen** [comment]
i'm sorry but am I just on everyone's github ignore list?

**Comment by KorPhaeron** [comment]
@Anturk

Thanks for the blob fix

**Comment by swankcookie** [comment]
@Bawhoppen there was a long discussion on IRC..... and as it turns out, yes, you are.

**Comment by duncathan** [comment]
@bawhoppen nah I just started writing my reply before you posted yours

**Pull request merged**
