### PR TITLE
adds shoulder pads and kneepads to bulletproof armor

### PR DESCRIPTION
**Pull request by ghost**
None
ss 2015-01-24 at 06 23 01
Current
 ss 2015-01-24 at 06 23 35
New
 ss 2015-01-24 at 06 23 06

### CODE REVIEW

**Comment by Iamgoofball** [comment]
add a skateboard please/10

**Comment by Cheridan** [comment]
didn't you get rid of the kneepads yourself? :V

**Comment by TZK13** [comment]
The black armband makes it look lopsided, a more clear line between where the shoulder pad ends and where the armband begins would be nice.

**Comment by Lumipharon** [comment]
Honestly I prefer the bullet proof vest as is. Also the fact that it exists specifically as bullet proof armor makes it very strange that it has shoulder pads/knee pads, as they don't really strike me as the sort of thing that's "bullet proof". Also probably won't look so good with rolled down jumpsuits.

But eh, don't want to start more sprite drama.

**Comment by paprka** [comment]
neither do i meh it's not really a big deal

**Pull request closed without merging**
