### PR TITLE
Removes changeling teams and hivemind channel

### LINKED ISSUE #46476: Changeling team objective not the same
## Round ID:
118447

Note that I would rather see team objectives gone, but they should at least be the same. This round had the changeling team objectives different for all the lings (with more people added per ling.)

image

### LINKED ISSUE #53732: Changelings Getting Assigned Different Departments For Team Objectives.
## Reproduction: Literally every round where changelings get the team objective to impersonate people from a certain department, but NOT the heads of staff, as those apparently seem to be working the way they were intended to.

So, basically, as can be seen in this picture below, changelings get assigned different departments for the "same" team objective, or it might be different, who knows. Either way, it makes it simply and purely impossible to accomplish that objective, as they don't have enough changelings to impersonate all of these people.
image

Also a little weird, probably related to how changeling team objectives are made, the first changeling only gets one person to impersonate in the team objective, the second one gets a list of two, the third one, a list of three, so on and so forth. Who knows, might be possible to knock off two issues at once.

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Changeling is a very strong antagonist, and one of the complaints I always hear is that they are impossible to beat when teamed up. I agree with this, and have seen it in practice several times. Eventually I wish to try to flesh out changeling a bit, take it in another direction, but for now I propose we remove the team elements.

Removes team objectives.
Removes changeling hivemind channel.

This leaves the changelings unable to easily communicate, but they can still invest in the pheromone receptors if they wish to find the others and propose teamups. They also no longer have to ensure a team victory, something which have felt a bit weird for a solo antagonist for a while.

Closes #46476
Closes #53732

## Why It's Good For The Game
Less teaming changelings.

## Changelog
:cl: Skoglol
del: Removed changeling team objectives and hivemind chat channel. Now a pure solo antagonist, use pheromone receptors if you insist on teaming up.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
would be cool if you could still access hivemind with people you grab with that currently useless linglink ability but its good anyway

**Comment by wesoda25** [comment]
The entire point of it is that it's a double edged sword. From a code perspective, changelings are encouraged to hunt and absorb their brethren.

**Comment by kriskog** [comment]
And they still are encouraged to eat each other. I dont think encouraging teaming up is worth the "double edged sword".

Nobody used ling link before, noone would use it after this, its not worth keeping.

**Comment by BigGrease** [comment]
removing team objectives is GOOD because nobody did them, but removing the ling channel is just unnecessary. its important for lings to be able to communicate with one another. if you could amend this to perhaps make ling channel access a perk you can take in the dna shop, i would accept that, but that's still not great. there's no need to make a gameplay removal like this

**Comment by Iamgoofball** [comment]
I disagree with nerfing changelings like this. They're already the hard mode antag on MRP servers because players on MRP actually play the video game, communicate with each other about issues, and do their jobs properly. I've only managed to barely skate by as a changeling on MRP because of the hivemind channel and teamwork.

**Comment by ATH1909** [comment]
Removing the team objectives is fine, but removing ling chat just seems... unnecessary. They'll find each other via pheromone receptors anyway; at least with lingchat, they can at least ATTEMPT to do stealth-based gimmicks with each other (war lings will still be possible after this change, regardless of whether or not you keep lingchat).

**Comment by wesoda25** [comment]
I guess if your point is that the possibility of ling teams even existing isn’t worth the double-edged sword I can’t really disagree with it. Plus I guess if you think about it, whether or not lings team up or kill each other, it still results in something more difficult for the station to deal with. 

And lings aren’t hardmode anywhere, ESPECIALLY MRP.

**Comment by necromanceranne** [comment]
I'd also like to point out nothing inherently stops a ling or a traitor or any solo antag from teaming up with another antag and going to fucking town back to back. If somehow they don't end up killing each other for selfish reasons, the problem can still occur. Traitors in particular get syndicate encryption keys for this reason, and have some selfless items in their uplink to help with this, like the tome.

If you want to address antags teaming up, you aren't getting anywhere with the removal of ling chat, because it is still entirely possible even without the metachat aspect and they never needed it to do so to begin with, and requires a lot of the participating lings to be on-board with it in the first place to occur.

Ling teams were only cropping up because of dynamic, so frankly that's just a bug. We've not had ling teams in a long time outside of dynamic being buggy.

**Comment by Tharcoonvagh** [comment]
>flesh out

I see what you did there

**Comment by kriskog** [comment]
Everyone can team if they want, but we shouldnt:
- Encourage it via objectives
- Give them a free roundstart undetectable and always usable chat to coordinate

Thats the premise of this PR, teamers will team still but at least its harder for them to find each other instead of forming ling killsquads at 5 minutes into the round which is easily possible today.

**Comment by ATH1909** [comment]
Maybe we can increase the frequency of the "absorb another changeling" objective?

Maybe we can give EVERY changeling an "absorb another changeling" objective, making them sort of like hivemind hosts or IAA agents?

I feel like the solution here is to make teaming up with another changeling risky, rather than removing lingchat, since changelings can just use pheromone receptors to find each other anyway. Lingchat is nice to shitpost and talk about stuff in, sort of like borgchat.

**Comment by kriskog** [comment]
Pheromone receptors is not free, nor very stealthy. I am fine with them finding each others if that means a time and resource investment.

**Comment by necromanceranne** [comment]
Maybe lingchat could be purchased?

**Comment by Tlaltecuhtli** [comment]
people dont team cause they ling but because they friends lol

**Comment by Jared-Fogle** [comment]
These are like the TWO things I actually wanted to keep from changelings, if anything.

**Comment by JMoldy** [comment]
a suggestion for replacing ling-chat: Make changelings capable of spraying pheromone onto things / tiles / people that creates a visual colored UI cloud that only changelings can see, undetectable to the crew.  Perhaps letting science throw some changeling organs into the destructive analyzer allows them to produce HUDs to see them? Presumably the changelings would get a variety of different pheromones that convey simple ideas. "Danger" "Prey" "Friend", plus perhaps the name of anyone the changelings are able to get close enough to replicate the general scent of/recognize (touch? 3 tiles away?) In theory, this means a changeling could communicate with any other changelings on station by writing something as simple as
```
Urist McChemist   Friend
Anna Kobold        Prey
```
on four tiles in the station hallways and wait to see if anyone else responds.

**Comment by Pumpkinoe** [comment]
IIRC Lings can feel each other's DNA extraction prick things and I've personally teamed up with a changeling just by pricking each other in passing, so, it's still very easy and possible to team up with another changeling.

**Comment by kriskog** [comment]
Testmerged this for a couple rounds to make sure I didnt miss anything, its good to go.

**Comment by ExcessiveUseOfCobblestone** [comment]
The whole "I have a way to communicate globally to other people in my team without any trace or indication, and only  a situational downside that relies on my not-team to foil fellow antags instead of the crew" is a pretty bad mechanic I don't understand the allure behind wanting to retain it.

**Pull request merged**
