### PR TITLE
Bounty PR: See-through plasmaman visors + drawing smiley faces on said visors

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request

Sprite-wise, this changes every plasmaman helmet to be transparent and adds a side-mounted light for their flashlight instead of the spooky internal light. Code-wise, the helmets no longer hide the wearer's face and requires them to wear an additional mask to fully hide their identity. You can now also draw a smiley face on the helmet with a crayon, it can be washed off through most normal means (anything that sends the CLEAN_ACT signal). I didn't change the inv_flags of the mime/clown helmet since they're supposed to be a full-cover ordeal with the painted-on mask visual.

## Why It's Good For The Game

Cool visual to actually see the face through the visors + drawing smiley faces on the faces of those who lack the facial muscles to smile themselves.

## Changelog
:cl: MMMiracles
add: You can now draw on plasmaman helmets with a crayon to turn their frown upside-down.
tweak: Plasmaman visors are now transparent and given a side-mounted light.
balance: Plasmaman helmets no longer hide your identity when worn by themselves.
/:cl:

header

### CODE REVIEW

**Comment by MMMiracles** [comment]
oops i fucked up the dme gimmie a minute

**Comment by optimumtact** [comment]
why did you give them a light? please take that away or put it in another PR

**Comment by JJRcop** [comment]
This should draw a smiley face on the item too rather than just the on_mob sprite

**Comment by Michael-Ashfield** [comment]
> why did you give them a light? please take that away or put it in another PR

Plasmamen have always had a helmet mounted light

**Comment by optimumtact** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Cyprex** [comment]
Presumabely the rationale was fire helmets/hardhats and most hardsuit helmets already grant it, so the plasmamen helmet which they are forced to wear has it as well. It's not like light is that rare anyway.

**Comment by MMMiracles** [comment]
nah there's literally a comment that just says 'I just want the light feature of the hardsuit helmet'

**Comment by fludd12** [comment]
Feature proposal: Having a smiley face drawn on your helmet makes a matching smiley face overlay cover your screen; not enough to block gameplay to a huge degree, but enough to be slightly annoying.

**Comment by ATH1909** [comment]
Feature proposal: drawing a smiley face on the helmet makes it conceal your identity (again).

**Comment by pireamaineach** [comment]
Mask is far too transparent and the helmet doesn't hide plasmamen's masks, which now clip through the helmet. I don't see why the side-mounted light was necessary but it's fine conceptually, sprite is a bit too boxy.

Also I'm pissed this got merged in favour of welding screens.

**Comment by pireamaineach** [comment]
Also doesn't emulate the tint the mining helmet was supposed to have, so the plasmaman's face doesn't match the rest of the suit.

**Pull request merged**
