### PR TITLE
Painkiller and miner's salve kills pain

### PR DESCRIPTION
**Pull request by brotherbeyondd**
## About The Pull Request
Painkiller (the drink) and miner's salve now add painkiller values in reference to bone gel application so they help prevent fainting when using it in a rush.
Also changes black out to pass out when you pass out due to pain.

## Why It's Good For The Game
The usage of painkiller as a placebo is an important one (though horribly ineffective). This PR will fix that by allowing for that drink to be unique and not useless.
Miner's salve is also referenced as a 'strong painkiller' so this now causes it to match morphine in effectiveness at killing pain.
image

## Changelog
:cl:

balance: Painkiller (the drink) and miner's salve now kill pain as god intended! No more fainting during bonegel application.

/:cl:

### CODE REVIEW

**Comment by brotherbeyondd** [comment]
fuk

**Comment by optimumtact** [comment]
miner faction needs to get the hell out

**Comment by ilikesaying** [comment]
you can't stop the miners just as you can't stop the degeneracy in TGMC

**Comment by brotherbeyondd** [comment]
you cant stop progress oranges

**Comment by OnlineGirlfriend** [comment]
Painkiller is supposed to be useless. The pain it refers to is emotional pain.

**Comment by necromanceranne** [comment]
It's just a drink. But Miner's Salve is already numbing you to pain, so it makes sense that it would do that with more modern mechanical relevance.

**Comment by brotherbeyondd** [comment]
Placebo, duh!

**Comment by brotherbeyondd** [comment]
you fear progress

**Comment by optimumtact** [comment]
catbeanie

**Comment by brotherbeyondd** [comment]
im legally a coder and yet im banned from coding general hello????

**Pull request merged**
