### PR TITLE
Adds RNG subsystem

### PR DESCRIPTION
**Pull request by Cyberboss**
Follow up to #30087. See @MrPerson's writeup there

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I'll just repost what I posted there then:

This seems like needless performance overhead, to be honest. If seed tracking was actually implemented and utilized, I could see this potentially being viable (for those specific things that ***need*** to use it), but blatantly replacing all RNG with its own subsystem seems like needless overcomplexity and just decreasing performance for no good reason.

This doesn't seem, to me, that this would be necessary for the vast bulk of RNG systems, and only a very specific cases would actually benefit/need to use it.

Ultimately you're adding proc call overhead and the the operation cost of an entire subsystem for a single `prob` call. That comes across as just plain silly for the *vast* majority of cases.

**Comment by lordpidey** [comment]
Would it be possible to modify the pickweight() proc while we're already digging around in the RNG methods?

Right now pickweight will sometimes pick 0 weighted things, by setting their weight to 1. You'll also want to change the last if statement to if (total <= 0 && L[item])

Take a look at [https://github.com/tgstation/tgstation/pull/30241/files#diff-bf6373a7968b796e0b36875ef957c957R208](url) for how I did it

**Comment by Cyberboss** [comment]
I'm probably going to implement what you did in this PR when I get in

**Comment by JamieH** [comment]
Can we just do a feature request on BYOND so we can seed rand?

**Comment by Cyberboss** [comment]
It has one, and it's used here

**Comment by Cyberboss** [comment]
Bluh

**Pull request closed without merging**
