### PR TITLE
Improves the E.X.P.E.R.I-MENTOR

### PR DESCRIPTION
**Pull request by Buggy123**
The E.X.P.E.R.I-MENTOR is kinda shit atm, and the only reason anyone ever uses it is for the blood sacrifice error and discovering what strange objects do. And even if people did use it, the only useful or interesting things that happen are the errors, aside from special reactions with a small selection of items no one ever puts in it. Not only that, but no one upgrades it, because that REDUCES the chance of any of the interesting things happening.

Instead of decreasing the likelyhood of errors happening, upgrading it now INCREASES the chances.

However, upgrading it also decreases the likelyhood that it'll actually destroy the item, removing the chance completely at tier 4 parts.

:cl: 
rscchange: E.X.P.E.R.I-MENTOR is now more likely to have "errors" occur when upgrading.

rscchange: Upgrading the E.X.P.E.R.I-MENTOR now decreases the likelyhood of errors destroying items.
/:cl:

### CODE REVIEW

**Comment by Supermichael777** [comment]
finaly

**Comment by PKPenguin321** [comment]
okay why not :+1:

**Comment by Lumipharon** [comment]
This is very, very bad.

If there is no chance to destroy the item, then you can keep blood draining the same item to get level 10 in everything extremely fast and with zero effort.

**Comment by Buggy123** [comment]
Hmm... fair enough. Maybe increase it to 10% i guess?

**Comment by Buggy123** [comment]
I raised the minimum destroy chance to 4%, if you feel that this is still too low let me know.

**Comment by Lumipharon** [comment]
I can't really say without actually testing it, but currently it's extremely impractical to blood drain an item twice, and for good reason.

Being able to blood drain the same items lets you skip lots of shit in research, unlock other shit an generally just cheese the shit out of R&D.

**Comment by Buggy123** [comment]
keep in mind this is with tier 4 upgrades.

**Comment by Fox-McCloud** [comment]
While I share the concerns @Lumipharon has, the EXPERI-mentor is literally a usleess pile of garbage other than to cheese R&D levels and activate relics.

**Comment by Buggy123** [comment]
I'll run some numbers for a % chance to get a double blood-sac in a little bit.

**Comment by DaedalusGame** [comment]
all these ifs are without else branch, so multiple events can probably happen in parallel
consider the following

if 10% event1
if 20% event2
if 30% event3

0.1 * 0.2 = 0.02 = 2% chance for event1 and event2 to happen at once
and
0.1 * 0.2 * 0.3 = 0.006 = 0.6% chance for all events to happen simultaneously.
and
0.9 * 0.8 * 0.7 = 0.504 = 50.4% chance for no events to happen at all

cuss me out because i hardly paid attention in class on this topic.

**Comment by Buggy123** [comment]
Yes, but the thing is i'm not sure what happens when two events both happen at once, since typically only one can.

**Comment by DaedalusGame** [comment]
That's impossible. There's no check for reactions that already happened in any of these branches. Reactions should happen freely in parallel. Low chance, but it should work that way.

**Comment by Buggy123** [comment]
Strange, i've never seen 2 events at once with the experimentor.

**Comment by DaedalusGame** [comment]
maybe you've never seen it happen because nobody uses it??

**Comment by Lumipharon** [comment]
Yes I agree that the experimentor is a piece of shit that has no use outside of relics and R&D cheese, but this pr doesn't change that, it simply makes it better at cheesing R&D.

**Comment by bgobandit** [comment]
just restore telescience tbh

**Comment by Buggy123** [comment]
Telescience is OP to have roundstart, and I know this because when R&D builds it it's OP. It's fun, and requires a fair amount of work and luck (AKA mining doing shit), but it can instantly cuck rogue AIs, steal anything from anywhere, and more. We removed it for a reason.

I'll increase the chance of losing a item to 12%, that sounds like a nice number.

**Comment by Buggy123** [comment]
Is the destruction chance still too low? I could increase it more...

**Comment by duncathan** [comment]
@KorPhaeron your call

**Comment by KorPhaeron** [comment]
I don't know shit about RD so I am trusting @Lumipharon that this is a bad idea

**Comment by GunHog** [comment]
Well, if you go through with this...I can throw up a PR I have been doing to make the E.X.P.E.R.I-MENTOR gas malfunctions much more deadly!

**Comment by duncathan** [comment]
Kor said no

**Pull request closed without merging**
