### PR TITLE
More borgo skins

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Sprites provided by Korusho/Khal-Thrask
Also added the random unused engiborg icon and made some numbers that shouldve been defines defines

image

## Why It's Good For The Game

Killer style

## Changelog
:cl: TiviPlus/Korusho
add: New borg skins
/:cl:

### CODE REVIEW

**Comment by Tumesuo** [comment]
Can you port femboy borgs from skyrat next too

**Comment by trollbreeder** [comment]
I feel like these borg skins don't fit with the rest and are rather boring. All of them share a unique shape with the only change being color, which makes determining their module take a while. They kinda look like clock cult constructs.

**Comment by Tlaltecuhtli** [comment]
bakugan

**Comment by IndieanaJones** [comment]
They look like droidekas, and honestly look more like a secborg overall than an engie borg

**Comment by TiviPlus** [comment]
If someone wants the tread lights on sprites they can ping me I guess

**Pull request closed without merging**
