### PR TITLE
syriniver no longer kills your liver in 1 syringe hopefully

### PR DESCRIPTION
**Pull request by TotallyNotTimonk**
## About The Pull Request

makes syriniver not so deadly anymore
correct me about my misunderstanding of the code if im wrong
## Why It's Good For The Game

its stupid

## Changelog
:cl:

balance: Syriniver is no longer as deadly

/:cl:

### CODE REVIEW

**Comment by Pugie** [comment]
It's not even that strong a poison also this PR was made because author died to syriniver as wizard again and was also opened before the round was even over.

**Comment by TotallyNotTimonk** [comment]
>not a strong poison
>kills you in 1 syringe

**Comment by wesoda25** [comment]
ided pr from a fucking ban evader

**Comment by TotallyNotTimonk** [comment]
what ban

**Comment by wesoda25** [comment]
your github ban genius

**Comment by TotallyNotTimonk** [comment]
what are you talking about

**Comment by kriskog** [comment]
Please refer to https://tgstation13.org/phpBB/viewtopic.php?f=5&t=18660
>Timonk - another non contributor who posts useless spam comments

Dont evade bans please.

**Comment by TotallyNotTimonk** [comment]
the other one is suspended by github, not only tg

**Comment by ExcessiveUseOfCobblestone** [comment]
github isnt a partner, we are under its umbrella so we have to oblige by bans they dish out regardless of personal opinions on it.

**Comment by ATH1909** [comment]
For reference, if you are shot by a syringe full of pure syriniver while your liver has not been damaged yet, your liver will take only 20 points of damage.

**Comment by Pugie** [comment]
> For reference, if you are shot by a syringe full of pure syriniver while your liver has not been damaged yet, your liver will take only 20 points of damage.

Absolutely untrue 15u of syriniver will easily kill someone with no prior liver damage try it for yourself.

**Comment by optimumtact** [comment]
ban evading eh

**Pull request closed without merging**
