### PR TITLE
merging these into one pr

### PR DESCRIPTION
**Pull request by silicons**
Ports support for references, usr, src, and marked datum inputting for variables from VGstation.
Oh yeah, and GLOBAL PROCS!!
Credits to VG station.

### CODE REVIEW

**Comment by sawrge** [comment]
Please remove SDQL

**Comment by KorPhaeron** [comment]
>Please remove SDQL

**Comment by ma44** [comment]
Kevinz buffing admins again 👎

**Comment by ExcessiveUseOfCobblestone** [comment]
call suicide_act(/mob/living/carbon/human) on /obj/item/wrench/medical where (z != 5)

**Comment by MrStonedOne** [comment]
You removed some of our checkticks.

**Comment by FantasticFwoosh** [comment]
**SDQL PR's son! They harden in response to emotional trauma! You can't hurt me normies!**

**Pull request closed without merging**
