### PR TITLE
Made AI VOX audio files smaller sized

### PR DESCRIPTION
**Pull request by Davidj361**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl:
tweak: Made AI's audio VOX files smaller sized
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
Made the AI VOX audio files smaller by doing ffmpeg -i FILE -c:a libvorbis -ac 1 -ar 16000 -b:a 16k -speed 0 -threads 8 -y OUT

The files were originally 36 kbps, I changed it to 16 kbps to save space.
The folder size of VOX should go from 5.01 MiB to 3.6 MiB.

### CODE REVIEW

**Comment by ShizCalev** [comment]
Comparing the sounds side by side, there is a quality loss between the two. I don't think 1.5MB size reduction is worth it tbh.

**Comment by optimumtact** [comment]
are you comparing in game or out? because byonds pants on head FMOD soundsystem probably makes them sound the same

**Comment by Qustinnus** [comment]
not worth the 1.5mb.

**Comment by Davidj361** [comment]
I could make them 8 kpbs with 8000 Hz sample rate, but the quality is incredibly worse.
https://vocaroo.com/i/s0i5ACZFpJxp

**Comment by Qustinnus** [comment]
This already reduces quality notably. Its not worth the small gain, theres files on tg that have zero compression (besides being turned into an ogg) and are stereo (which is unnecessary for audio on TG) which could give way bigger savings.


And again, like I said, people can download the 1,5 mb

**Comment by ShizCalev** [comment]
#36492

**Pull request closed without merging**
