### PR TITLE
Adds arrow graffiti

### PR DESCRIPTION
**Pull request by AnturK**
Adds arrow graffiti. Also adds option to make graffiti oriented the same way as the user. Made body and arrow use this.

scrnshot1

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
We don't have the ability to make corpses face downwards, replace those sprites with the 'corpse on it's back' or whatever we actually do.

**Comment by dannno** [comment]
or don't because who cares

**Comment by Jordie0608** [comment]
Changelog

**Comment by Chocobro** [comment]
this is cool! :+1:
feature tag please

**Comment by xxalpha** [comment]
:+1:

**Pull request merged**
