### PR TITLE
Adds away areas to ghost teleport/ admin jump list

### PR DESCRIPTION
**Pull request by AnturK**

### CODE REVIEW

**Comment by Supermichael777** [comment]
feature freeze dude

**Comment by Bawhoppen** [comment]
feature freeze was already violated many times
its only formal at this point

**Comment by tkdrg** [comment]
No it wasn't, the PRs merged were opened before the freeze and thus not affected by it.

**Comment by duncathan** [comment]
@Bawhoppen seriously wtf are you on about

**Comment by Aranclanos** [comment]
after the freeze

**Comment by Cheridan** [comment]
It's not even a feature, it's a usability improvement

**Pull request merged**
