### PR TITLE
adds movement states for some cyborgs + borg jetpack improvement

### PR DESCRIPTION
**Pull request by ghost**
Miner borg jetpack now uses overlays instead of a different icon state.

Janitor borg bristles will only move when the borg is actually moving now.
rob1

Medical borg has a little propulsion for when it is hovering around in different directions.
rob2

Security cyborg has wheels now instead of skidding around on the ground. They are also animated for when it moves.
rob3

Mining borg treads move when it moves now.
rob4

### CODE REVIEW

**Comment by paprka** [comment]
Some of the gifs came out weird on github. I'm too lazy to capture new ones right now, whatev.

**Comment by paprka** [comment]
Gonna fix these gifs since they're so fucked up.

**Comment by paprka** [comment]
Also #7111

**Comment by GrayRachnid** [comment]
Why not give secborgs a treadmill? IIRC there's a sprite for it.

Those while look horrifying tbh.

**Comment by Steelpoint** [comment]
Treadmill or bust, sec borg looks bad.

There is a treadmill sec borg sprite, as I was the one to put it in.

Otherwise the rest is very good!

**Comment by GunHog** [comment]
Agreed on the Secborg, give that thing treads! I believe Mechoid made Secborgs with treads. Other than that, this is great :+1:

**Comment by hornygranny** [comment]
i don't like the secborg wheels

**Comment by RemieRichards** [comment]
the secborg wheels do look fugly. track pls.

**Comment by Steelpoint** [comment]
https://github.com/tgstation/-tg-station/pull/2993.

The sprites for the treaded sec borg is already in the game, here's the sprite.

https://camo.githubusercontent.com/63ec1b335211178cfdda017c14aed208275ebeec/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f363539353338392f323333353939322f30353961626231382d613438612d313165332d386135302d3731376666616263343166322e706e67

**Comment by ExplosiveCrate** [comment]
The secborg looks like you could give it a good kick and have it fall apart.

Otherwise pretty good.

**Comment by pudl** [comment]
i think that the mediborg would look good with wheels, not the secborg

**Comment by WJohn** [comment]
I like this a lot. But keep in mind the functional reason for their mobility. Engieborgs have little hooks for legs and can rotate their bodies independently for work in 0 G, secborgs have lots of office-chair wheels (and a comically high center of mass) to zoom around on the smooth tiling of the station, mining borgs have treadmills to help them with the rough, uneven terrain of the asteroid, and mediborgs float so they don't spread filth or blood anywhere.

**Comment by paprka** [comment]
someone can make wheels that look wider and less tiny like office chair wheels for the secborg, wj nailed it on the spot. The idea is having each borg have a unique mode of transportation to make them a lot more immediately identifiable if they were to have a custom paintjob (coming soon)

really though, if someone wants to make the wheels look better, or a different style of transportation for the secborg, be my guest.

**Comment by TZK13** [comment]
I don't like the idea of giving secborgs treads, that seems far too militaristic of a direction to take them aesthetically.

**Pull request closed without merging**
