### PR TITLE
The kinetic crusher can now gain bonus effects via trophies gained by killing bosses with it

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: The kinetic crusher can now gain bonus effects via trophy items gained by killing bosses with it.
rscadd: Yes, you do have to kill the boss primarily doing damage via the kinetic crusher, or you won't get the trophy item and the bonus effect it grants.
/:cl:

The effects are relatively minor;
The dragon trophy makes mark detonation do 5 damage to and push back every other mob within 2 tiles of you.
The bubblegum trophy makes melee hits do 2 more damage and heal you for 1. This effect is increased by 500% during mark detonation, so it does 10 and heals for 5 on mark det.
The colossus trophy causes your next destabilizing force after detonating a mark to do 15 damage but move slower.
The hierophant trophy creates a 1x3 temporary(7.5 second duration) indestructible wall on your turf on mark detonation. You, your projectiles, and things you're pulling can pass this wall.

### CODE REVIEW

**Comment by jughu** [comment]
What about the legion multiple target locks?

**Comment by ChangelingRain** [comment]
You can't kill legion with the crusher. At least, I don't think you can.

**Comment by jughu** [comment]
Thats what you can say about collusus but people manage to do it

**Comment by jughu** [comment]
And besides after this pr people WILL ans try this on legion give them their fun and not exclude it because you think its impossible

**Comment by ChangelingRain** [comment]
I know for a fact that colossus can be killed with a kinetic crusher. That's why I gave it the trophy.

**Comment by jughu** [comment]
You just need alot of patches BUT ITS POSSIBLE

**Comment by Kromgar** [comment]
So these are abilities that persist because byond trophies right?

**Comment by ChangelingRain** [comment]
They're not byond trophies. They do not persist.

**Comment by ChangelingRain** [comment]
And no, you can't cheat, you have to do over 60% of the boss's health with crusher damage

**Comment by KorPhaeron** [comment]
These are pretty weak considering how tough they are to obtain

**Comment by ChangelingRain** [comment]
Sure okay I'll just make them super good bonuses then

**Comment by ChangelingRain** [comment]
@Repukan hey look is this what you wanted

**Comment by Repukan** [comment]
Neat

**Pull request merged**
