### PR TITLE
Adds a new reaction to pink slimes

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds the gender change potion as the blood reaction of pink slimes. Pink slimes previously only had one reaction (pet slimes), and it's not exactly a barn burner.

This item changes up the gender var of any gendered mob/living. Including people. There are a few interesting applications of this item, mostly if your into animal husbandry (all generic animals unless programed otherwise are all the same gender) but mostly it's just here to fill the immensely niche gap the loss of gender reassignment surgery left. Also it's 2:30 am.

Also factors out the old human var gender_ambiguous, as that surgery was the only way to ever trigger it.

:cl:
add: A new slime reaction has been found for pink slimes using blood. The potion produced from this reaction can be used to change the gender of living things. Decently useful for animal husbandry, but otherwise mostly just for pranks/"""roleplay"""/enforcing a brutal regime composed entirely of female slime people.
/:cl:

### CODE REVIEW

**Comment by Cheridan** [comment]
>mostly it's just here to fill the immensely niche gap the loss of gender reassignment surgery left.

Genetics can easily change people's genders via Unique Identifiers:
ui genetics reference

**Comment by Incoming5643** [comment]
Was aware, the surgery's niche was technically the redundancy of being forced into genetics. Since xenobio is already spawning all the simple animals it seemed like a logic step to take at 2:30 am. Now you can get corgi puppies/kittens out of only generic corgis and cats.

**Comment by Jalleo** [comment]
But can you get calfs and toddler monkeys?

**Comment by Core0verload** [comment]
Nah, gender reassignment removal was a shit quickmerge. It will get reverted.

**Comment by Incoming5643** [comment]
honestly even if it does get reverted we should flesh out some of the less loved slimes anyway

**Pull request merged**
