### PR TITLE
Revert "Revert "Revert "Revert "Revert "Revert "Typos in syndicate uplink descriptions""""""

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#28008

### CODE REVIEW

**Comment by BeeSting12** [comment]
but thats an actual misspelling

**Comment by juanototo2** [comment]
**WEW LADS IT'S DESCENDED INTO WAR, BLOODY TRENCH FUCKING WARFARE**

**Comment by factoryman942** [comment]
yes

**Comment by factoryman942** [comment]
the cycle must go on

**Pull request closed without merging**
