### PR TITLE
Adds abs to all of the jumpsuit sprites that have a skirt variant

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
We have all collectively established that it is a good idea to add boobs to skirts, therefore it must be a good idea to add abs to those jumpsuits that have skirt varients

## Why It's Good For The Game
It's funny haha, I definitely am not horny for spaceman abs I just think it's funny for sure for sure. plus this was already on other sprites so it MUST be a good thing hahaha. I find body shape funny.

## Changelog

:cl: itseasytosee
add: Abs
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
you deleted the turtleneck

**Comment by tralezab** [comment]
9F697ABE-FB1F-4882-9342-E8E727F92162

**Comment by optimumtact** [comment]
malded

**Comment by Mothblocks** [comment]
image

**Comment by SomeDongus** [comment]
Why do female sprites get to boobs but male sprites don't even get to have balls? 🤬🤬🤬🤬🤬

**Pull request closed without merging**
