### PR TITLE
Movable atoms now call Entered() on their loc in New()

### PR DESCRIPTION
**Pull request by ChangelingRain**
This might cause a wild amount of bugs, but it's a good(?) idea(?)

### CODE REVIEW

**Comment by RemieRichards** [comment]
Isn't this automatic?
Also ```loc``` is an ```/atom```

**Comment by ChangelingRain** [comment]
I'd think it's automatic, but if you make a whatever on top of lava it doesn't start burning, so clearly it isn't...

**Comment by Ergovisavi** [comment]
>Alien weeds will now perpetually regenerate and burn on lava for all eternity

Uh....

**Comment by ChangelingRain** [comment]
Alien weeds don't ~perpetually~ regenerate, because they only spread once per weed tile!

**Comment by MrPerson** [comment]
Should maybe consider also calling Crossed() too. Also Moved()?

**Comment by optimumtact** [comment]
bad

**Comment by Razharas** [comment]
Apparently no bugs were found

**Comment by optimumtact** [comment]
There are soooooooo many bugs caused by this

case in point
https://file.house/lEPm.txt

items getting destroyed while still in their new, with no checks for them being qdeleted

**Comment by optimumtact** [comment]
literally the only way you could merge this was if every single new call was updated to check !qdeleted(src) after calling parent

**Comment by optimumtact** [comment]
basically this isn't the right way to do this.

You have to call moved as the absolute last step of each new, which really means you need some subsystem to queue up a post new proc or something, like a one tick process

**Pull request merged**
