### PR TITLE
Monkeys and aliums can now be defibbed

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
tweak: Monkeys and aliums can now be defibbed
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
But it was a fun idea

**Comment by Mercenaryblue** [comment]
It sounded like a good idea. Not sure why you would revive the alien, but hey.

**Comment by MoreRobustThanYou** [comment]
@Bawhoppen i dont feel like refactoring heart attacks to support monkeys and aliums!

**Comment by MoreRobustThanYou** [comment]
actually

**Comment by MoreRobustThanYou** [comment]
aghhh i need sleep

**Comment by jughu** [comment]
Doesnt it already support monkeys tho...

**Pull request closed without merging**
