### PR TITLE
Techwebs update: Protolathe/Circuit imprinters combined into techfabs!

### PR DESCRIPTION
**Pull request by silicons**
Doing my little update piece by piece because I'm lazy and because storage PR is going to conflict everything ever.

Techfabs do not link to RND consoles, and have their own interface for producing things.
RND production machinery code refactored.
Techwebs have categories views instead of just a goddamn design list.
Old machinery will be kept in, as some places will keep them. Read: Engineering, robotics, etc.

- [x] Map this stuff in
- [x] Bugtest

:cl:
experimental: Protolathes and circuit imprinters combined/changed to techfabs. All departments can now print related circuit boards. Engineering and science will keep their lathe/imprinter design by default at roundstart because they have specialized labs for those.
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
-1 make the engineers have to rebuild one more thing if RND explodes goddamnit i don't need u combining it in to 1
if we have 2 devices then engineers have more to rebiuld ok
it mak people lazy

**Comment by kevinz000** [comment]
@checkraisefold engineering and science are keeping the two machine design, the rest of departments have space constraints, this is basically upgrading their lathes. either this or they wouldn't have imprinters at all.

**Comment by Tlaltecuhtli** [comment]
any pictures or videos of how this "procedually generated tabs" look like

**Comment by arsserpentarium** [comment]
Return omni circuits imprinting to science,because engineers aren't doing a shit.

**Comment by Bawhoppen** [comment]
@arsserpentarium that's a textbook player issue

**Comment by arsserpentarium** [comment]
@Bawhoppen
Maybe,you're right. But it's way harder to find new players,than tweak access

**Comment by evsey9** [comment]
bring back omnicircuitprinting
engineering's job has ALWAYS been just fixing breaches and building walls and windows
it's hard to get science to do something for you, and impossible to get ENGINEERING to do anything for you

**Comment by kevinz000** [comment]
the issue of "whether science can make everything again" is to be brought up in another PR.

**Comment by arsserpentarium** [comment]
Mechanic job will work too.
But engi aint do shit.

**Comment by Robustin** [comment]
Merge this ASAP

**Review by ShizCalev — APPROVED** [review]
maps fine.

**Pull request merged**
