### PR TITLE
Half-Ports (????) the CMO turtleneck

### PR DESCRIPTION
**Pull request by VladinXXV**
## About The Pull Request
This adds the CMO turtleneck from [this PR by Michiyamenotehifunana](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/5307). I modified the sprites a little, made a skirt variant, and put them in a cargo crate.
image
I would be more than happy to put these in the CMO garment bag instead, but currently this is what I've been told I am allowed to do.
image

## Why It's Good For The Game
The CMO has ZERO alternate uniforms. The most variation in their wardrobe is choosing between their winter coat and their labcoat. This adds a very nice looking turtleneck so the CMO can finally join the rest of the heads of staff in having cool clothes.

## Changelog

:cl: Vladoricious and Michiyamenotehifunana
add: Added the CMO turtleneck and turtleneck skirt! Order them in the Medical section of cargo!
/:cl:

### CODE REVIEW

**Comment by VladinXXV** [comment]
is it still a port if i changed and added onto it??? hell if i know.

**Comment by LemonInTheDark** [comment]
Mind crediting them in the changelog?

**Comment by VladinXXV** [comment]
> Mind crediting them in the changelog?

I know there's a certain way to do that but I have no clue how to go about it.

**Comment by VladinXXV** [comment]
> > Mind crediting them in the changelog?
> 
> I know there's a certain way to do that but I have no clue how to go about it.

I think I got it?

**Comment by LemonInTheDark** [comment]
Make sure there's a space between your name and the :cl: bit, or it won't work
Should really fix that

**Pull request merged**
