### PR TITLE
Gave miners a brute patch at roundstart and some more appropriate medkits

### PR DESCRIPTION
**Pull request by ghost**
ss 2015-02-04 at 02 28 53

Miners also spawn with a brute damage (salglu) patch in their pocket when they spawn now. This is because at times monsters can be unavoidable on the western asteroid (good luck finding diamond on the east), and without telesci retrieval, you're basically completely fucked if you die. Patches go through hardsuits, so you can use this to heal yourself while retreating or to help you finish the mob. Monsters are still incredibly dangerous despite this, but bleeding is pretty unfair to miners and can really fuck them over without the salglu patch.

I also added an IV drip here and removed the sleeper. This is one of the few IV drips outside of medical. You can use this to replace blood and this also makes mining very attractive for cultists to establish a base on and research runes.

I added some medkits to mining maint and replaced the oxyloss kit with a brute kit.

Medical is ideally the best source of medicine, but expecting miners to crawl all the way back to the station for infusions is silly.

### CODE REVIEW

**Comment by TZK13** [comment]
Minor fluff thing but could you add a roller bed beside the IV drip, it looks a little empty in there and it makes sense.

**Comment by WJohn** [comment]
Rip sleeper.

**Comment by Incoming5643** [comment]
Protip: if you ever want pap to add something to your department, just put a sleeper there.

**Comment by pudl** [comment]
salglu patch

**Comment by paprka** [comment]
or it's powder whatever

**Comment by Iamgoofball** [comment]
>patch
>miners

**Comment by Jordie0608** [comment]
Changelog.

**Pull request merged**
