### PR TITLE
remaps podperson seed vault + removes gatfruit from its spawners

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

out of date pic
2024-11-17 14_03_24-Window
down here is not out of date
image

## Why It's Good For The Game

old ruin was getting a little old
gatfruit was added in 2013 as some sort of admin shitspawn thing and it definitely should not be accessible to miners or whoever else for little effort beyond finding the ruin to print a gun dealing 420 brute if you fire all 7 shells en masse
at max yield (10? idk) its 4200 (60 damage * 7 shells * 10 guns) brute in a bag per harvest

## Changelog
:cl:
balance: the podperson seed vault has received a remap, it is slightly larger and its spawners no longer have gatfruit
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
i, too, hate the sandbox

**Comment by mc-oofert** [comment]
> i, too, hate the sandbox

we shouldnt be letting people print .357 revolvers en masse via g(y)at(t)fruit because someone decided to bring the adminbus fruit added in 2013 to some random ass lavaland ruin

**Comment by SmArtKar** [comment]
Can podpeople themselves get out? Is the rock near the entrance also indestructible? I don't think that you should babyproof the ruin entirely tbh, that just makes it a very shitty and restrictive botanical sandbox

**Comment by mc-oofert** [comment]
you cant even get out of it right now youll instantly choke out

**Comment by DaydreamIQ** [comment]
I too absolutely despise miners looting the place for their easy to mass produce 60 force weapon that should've been iced ages ago. But having visitors is nice sometimes so the indestructible walls seems like overkill, just remove the seed packets imo

**Comment by Dawnseer** [comment]
Have you considered that perhaps instead of turning the ruin into a GBJ, you could just... remove the gatfruit seeds from the spawn?

**Comment by mc-oofert** [comment]
> Have you considered that perhaps instead of turning the ruin into a GBJ, you could just... remove the gatfruit seeds from the spawn?

both of these options work they have literally no reason to go out of the seed vault

**Comment by Dawnseer** [comment]
So their goal of turning lavaland into a nice lush green planet is just snipped then?

**Comment by mc-oofert** [comment]
> So their goal of turning lavaland into a nice lush green planet is just snipped then?

they cannot achieve this even right now theyll die literally immediately to atmos

**Comment by Dawnseer** [comment]
They have more than enough tools in there to survive the atmos. It's botany for crying out loud.

**Comment by Dawnseer** [comment]
I have literally watched them flourish outside their ruins before, planting stuff across lavaland.

**Comment by mc-oofert** [comment]
good for them ig guess lavaland atmos rng checked out

**Comment by SmArtKar** [comment]
> > Have you considered that perhaps instead of turning the ruin into a GBJ, you could just... remove the gatfruit seeds from the spawn?
> 
> both of these options work they have literally no reason to go out of the seed vault

I am against turning this into GBJ. Remove the seeds and leave it accessible both ways, so they can get visitors and possibly go outside themselves if they figure something out to not choke and die.

**Comment by carlarctg** [comment]
> > i, too, hate the sandbox
> 
> we shouldnt be letting people print .357 revolvers en masse via g(y)at(t)fruit because someone decided to bring the adminbus fruit added in 2013 to some random ass lavaland ruin

okay so change gatfruit not the pod ruin

**Comment by mc-oofert** [comment]
> > > i, too, hate the sandbox
> > 
> > 
> > we shouldnt be letting people print .357 revolvers en masse via g(y)at(t)fruit because someone decided to bring the adminbus fruit added in 2013 to some random ass lavaland ruin
> 
> okay so change gatfruit not the pod ruin

ok smart guy say that to the previous PRs by other guys that changed gatfruit

**Review by SmArtKar — CHANGES_REQUESTED** [review]
Leaving this as a request so that other maintainers don't miss it:
I am against turning the seed vault into an unpenetrable GBJ. Removing gatfruit seeds is enough, remove the NOTELEPORT flag and make the rock breakable. Having guests is nice and sometimes you can figure something out to not suffocate and die as soon as you go outside.

**Comment by mc-oofert** [comment]
> Leaving this as a request so that other maintainers don't miss it: I am against turning the seed vault into an unpenetrable GBJ. Removing gatfruit seeds is enough, remove the NOTELEPORT flag and make the rock breakable. Having guests is nice and sometimes you can figure something out to not suffocate and die as soon as you go outside.

i did this 4 hours ago fyi

**Comment by MrMelbert** [comment]
> ok smart guy say that to the previous PRs by other guys that changed gatfruit

The last pr to change gatfruit to be less overpowering was accepted they just let it stale out

**Comment by CCC23** [comment]
their is still other ways to obtain gatfruit through cargo :3

**Comment by Holinka4ever** [comment]
> Remove the NOTELEPORT flag and make the rock breakable.

Its understandable with teleport, but brekable rocks are just gonna fuck up the atmos in the place. Like, miner can non-intentionnaly grief the pod base and they walk away as nothing wrong has happen. By the way, for guests we have DOORS.

**Comment by mc-oofert** [comment]
> their is still other ways to obtain gatfruit through cargo :3 

ok??? what if I get rid of it from the exodrone spawner too??

**Comment by mc-oofert** [comment]
I need to reinforce the rocks a little so the miners can't just accidentally plasma cut and fill the ruin with bad gas but no clue how to draft on mobile

**Comment by DrAmazing343** [comment]
sovl destroyed. /tg/ has fallen.

**Comment by mc-oofert** [comment]
The revolver idea was pretty novel though I'll give it that

**Comment by ElGitificador** [comment]
revolver removal 2025 edition just dropped (i hate you)

**Comment by moocowswag** [comment]
What if we had a new type of gat fruit that was good in low atmos so pod people had a good lavaland weapon.

**Comment by githubuser4141** [comment]
What if gatfruit was changed into a one-shot, plasma/globule gun? It'd better reflect it's biological nature I think, with damage based on the plant's stats, rather than having it magically produce an actual manufactured gun complete with cartridges.

**Comment by LemonInTheDark** [comment]
I do not like the gatfruit aspect of this and think the reinforcing on its own is quite uninspired (why shouldn't miners be able to enter the ruin?)

**Comment by optimumtact** [comment]
#88051

**Pull request closed without merging**
