### PR TITLE
Gives the baguette a belt sprite.

### PR DESCRIPTION
**Pull request by nemvar**
## Why It's Good For The Game

Extra mime content.

## Changelog
:cl:
add: En guard! Wearing le baguette on your belt slot is now more stylish.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Could you add sprite to the captains sword sheath too?

**Comment by nemvar** [comment]
Pretty sure the sheath already has sprites.

**Comment by FantasticFwoosh** [comment]
Oh, my mistake then, i thought you could store baguettes **_within_** captain sword sheathes.

**Comment by RaveRadbury** [comment]
We just got belt/back equip for baguettes and horns, maybe baguettes within captain's saber sheathe soon?

**Comment by ATH1909** [comment]
> We just got belt/back equip for baguettes and horns, maybe baguettes within captain's saber sheathe soon?

Katanas (including toy ones) in saber sheathes when?

**Comment by knacker48** [comment]
Can I stick the captains sabre in my baguette?

**Comment by Anonmare** [comment]
hon hon hon hon

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
