### PR TITLE
Revert "Updates space-heater sprite to 3/4, updates icon"

### PR DESCRIPTION
**Pull request by praisenarsie**
Reverts tgstation/tgstation#33778

pr author didn't wanted it merged. wjohn said it needs improvements. oranges does a dum merge again.

### CODE REVIEW

**Comment by optimumtact** [comment]
rude, I'm going to bully you now

**Comment by praisenarsie** [comment]
revert was pointless anyway since pr author can just make a quick fix pr

**Comment by WJohn** [comment]
i did not want those space heaters to be merged.

**Comment by PKPenguin321** [comment]
Then reopen this @WJohn

**Comment by MrDoomBringer** [comment]
lmao i didnt want them merged either

**Pull request closed without merging**
