### PR TITLE
support for shoes with height  (git unfucked version)

### PR DESCRIPTION
**Pull request by Militaires**
this sat for 2 weeks and raz already reviewed it so can it not sit ANOTHER 2 weeks

edit: as of this edit this pr had sat for 3 fucking weeks in total where is @optimumtact when you need him

### CODE REVIEW

**Comment by kevinz000** [comment]
No

**Comment by Militaires** [comment]
@kevinz000 if i wanted to ask for a cuck's opinion i'd be in the science department not github

**Comment by FantasticFwoosh** [comment]
Ladies night high heels when.

**Comment by ShadowDimentio** [comment]
S T I L T S

**Comment by chanoc1** [comment]
pics when

**Pull request merged**
