### PR TITLE
Viro nerf

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl: nicbn
add: Toxic Compensation readded.
del: Brute and burn healing virus symptoms removed.
/:cl:

Closes #32387

The only way to do a brute and burn healing virus is by adding both toxic compensation and toxic filter.
And anyways the compensation works faster than the filter so it is not much profitable.
However many interesting symptoms like ocular restoration, mind restoration and self respiration still exist.

I also reorganized the symptoms files.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
why though?

**Comment by nicbn** [comment]
We keep virologist, we keep cool things and we keep kor away from removing the cool things from us. Total profit.

**Comment by ChangelingRain** [comment]
I don't think it matters how the healing works as long as it exists.

**Comment by nicbn** [comment]
But now it is harder to make it and it is no longer "free", as only half the toxin produced will be healed on the same tick, so you will end up needing to wait a while for the toxin to go away after your burns and bruises are gone.

**Comment by PKPenguin321** [comment]
I liked the idea of having one that turns brute into burn, one that turns burn into toxin, and one that turns toxin into oxygen

**Comment by nicbn** [comment]
@KorPhaeron Do you prefer this way or the way @PKPenguin321 suggested?

**Comment by KorPhaeron** [comment]
I prefer whichever method makes the virus a choice people have to consider rather than a passive no brainer that people will take with varying degrees of effectiveness 

Sure this halves the healing rate, but I'll still always take halved passive unlimited free healing vs no passive unlimited free healing

**Comment by YakumoChen** [comment]
Why don't we make the brute and burn switch between each other with the symptoms so you can't get rid of them without chems. Toxin healing is fine on its own since that damage is rare. nobreathe is also fine since its just worse internals.

**Comment by ExcessiveUseOfCobblestone** [comment]
if you're going to approach it this way, have 2 symptoms that turn brute and burn into toxin without a symptom that nullifies toxin.

You will already passively heal via vomiting but otherwise you'd still need to get it fixed. However I think tea or something heals tox so it's pretty easy to ratify and you don't have to stop for it

**Comment by Repukan** [comment]
Or we could stop trying to keep a non balanced system that nobody really gave a rat ass about until it was removed.

**Comment by XDTM** [comment]
Toxin is harder to heal generally so toxin compensation per se is worse, unless you deal half of the damage as toxin damage or something like that.

I think that conditional (ex. if you only have a certain chem, you're in space, you're breathing plasma, etc) healing, or healing with separate downsides (increased hunger, stamina damage, constant vomiting) would be better than just making it "You have to have two symptoms to heal instead of one, and it's slower", since that doesn't really solve the issues Kor wanted to solve.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'd much rather they just be removed outright or just switch between damages without actually healing on their own.

**Comment by nicbn** [comment]
What if the toxic filter dealt respiration damage?

**Comment by Mercenaryblue** [comment]
Couldn't we just nerf the passive regen from 12 to 3 per tick instead. Make it a slow healer, like a natural regeneration.

**Comment by Repukan** [comment]
The problem is the healing itself, not its ratios

**Comment by Mercenaryblue** [comment]
A slow heal doesn't prevent death, stuns, asphyxiation, poison, burns, and other stuff.
It simply rewards you for staying out of trouble for a long time.

**Comment by Doppeltongue** [comment]
Nobody complained about virology when the best healing virus was 3 brute, 3 burn, 3 tox, self resp, DNA restoration, and almost nobody even bothered with it. Why? Turns out that slow "unlimited" healing is GARBAGE in the game of stuns, and those values are only enough to save you from space without equipment. It's only now that you can hit 12 brute and 12 burn heal that people are complaining, because it means that it takes too much effort to kill people without preparation (requiring bladed weapons for limb removal, toxin damage, etc). Solution: nerf healing symptoms back to where they were before the massive buff. It's the difference between taking a full set of laser shots and healing to full in less than 10 seconds, and taking a few hits before ducking into maint for about a minute to heal up, which can also be done by people who have medical supplies.

And of course you'd take healing over non-healing. You'd take anything good over nothing. Found a gun on the ground? Into the backpack it goes! Found an ID card lying around, thanks! Found an emag? Time to grief people! Really seems like "I'm the Head Coder and the Headmin, you remove this in a way I like or I remove it anyways" type of deal.

Actual suggestions: Remove weight even and weight gain symptoms, make the brute/burn healing viruses cost nutrition as they heal, increasing greatly (non-proportionately) as they heal higher values per tick. It makes more sense that those things that basically grow you new flesh will cost you food to fuel their healing, people don't have enough reason to eat food anyways. Want to get into a fight? Better eat up or you'll be slowed down, which can make you a bigger target. 

Still not enough? Make it do stamina damage if you're too hungry. Want more? Make it cause you to faint if you're really really hungry and tired. That's right, healing too much without feeding yourself will cause you to enter a regenerative coma. If this sounds familiar, it's basically giving yourself Fungal TB without the vomiting if you don't eat before and during extended combat.

Also, increase the stealth values of all healing symptoms, so that it's easier to make harmful viruses that have one healing symptom. I did the math, and it turns out there's no way to get decent stats other than stealth on any virus that has enough stealth to bypass health HUDs and still kill people.

I've actually complained about no trade-offs right now, because there's just no reason to use tier 6 symptoms when the tier 8 exist as virology currently exists, due to the way stage speed works.

**Comment by ChangelingRain** [comment]
>Really seems like "I'm the Head Coder and the Headmin, you remove this in a way I like or I remove it anyways" type of deal.

He's also the design lead. This is his job.

**Comment by Doppeltongue** [comment]
I know, but using the viro buffs as an excuse to completely remove virology seems excessive. Also, without virology, where would spiders and xenos find unused monkeys lying around? Think of the poor, starving spiders and those lonely, single queens! You monster, how could you take away their nest?

**Comment by KorPhaeron** [comment]
@Doppeltongue Virology Lab isn't being removed though, just the dedicated job slot and the heal symptoms. The monkeys will still be there amid all the machines.

**Comment by Doppeltongue** [comment]
@KorPhaeron Hidden xeno buff, confirmed that WJohnson was behind this!

But really, what do you think about healing symptoms inflicting hunger levels comparable to fungal TB on yourself if you're overreliant on them? Removes both "unlimited" and "free" healing. Maybe make the higher tier symptoms scale worse so that there's a reason to use lower tier ones, especially if you make the tier 6 have -2 stage speed instead of -4, because right now there's no reason to use anything other than the brute/burn tier 8 and 15 stage speed worth of symptoms due to most values being rare.

**Comment by ExcessiveUseOfCobblestone** [comment]
Hunger isn't a good balancing mechanism when the downsides have been nerfed to negligible levels

**Comment by KorPhaeron** [comment]
The downside is the same as its always been for hunger (moving slow), which is a pretty substantial downside

**Comment by ExcessiveUseOfCobblestone** [comment]
Whoops I was thinking of how long it takes to actually get hungry

**Comment by Doppeltongue** [comment]
Slow movement is how a single xenobiology watcher solo killed a nuke op that blasted his way through 10+ people. Movement is the strongest part of most games, and I also suggested adding in a hunger-based fainting. Slow movement+selfsleep seems like a pretty harsh downside to me.

**Comment by KorPhaeron** [comment]
XDTM is working on something

**Pull request closed without merging**
