### PR TITLE
The great bucket buff and pill nerf

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscdel: Pills and patches are now 15u.
rscadd: Pill bottles can now hold 21 pills.
rscadd: Buckets are now 1000u.
rscadd: Water tanks and fuels tanks are now 100 000u.
rscadd: Beer kegs are now 5867u, CHUG CHUG CHUG CHUG.
/:cl:
- [ ] Adjust mop values
- [ ] Prevent buckets from being used in grenades
- [ ] Buckets lose their reagents when put in a backpack
- [ ] Buckets can be installed in an airlock for topkek pranks

Also some code tidying, while I was in the neighbourhood.

### CODE REVIEW

**Comment by WJohn** [comment]
oh my god he actually did it

**Comment by LatD** [comment]
So if you fill a bucket with acid and pour it on another mob, that mob just instantly melts? Honk

**Comment by phil235** [comment]
>bucket of acid to the face.


You got a whole lot of things to change that are linked to bucket amounts, like hydroponics trays.

**Comment by coiax** [comment]
> So if you fill a bucket with acid and pour it on another mob, that mob just instantly melts? Honk

Yes, well, I suppose if you can get 1000u of acid, then you will have approximately a bucket of acid. Perhaps I will make buckets dump their contents if placed into a backpack.

**Comment by phil235** [comment]
>Yes, well, I suppose if you can get 1000u of acid, then you will have approximately a bucket of acid. Perhaps I will make buckets dump their contents if placed into a backpack.

That wouldn't fix the problem and just piss players off.

**Comment by PKPenguin321** [comment]
you can make maxcap bombs with this

**Comment by PKPenguin321** [comment]
also what the fuck why the pill/patch nerf

**Comment by PKPenguin321** [comment]
what the fuck is that beer keg magic number

**Comment by PKPenguin321** [comment]
if this isn't a meme pr then i'm genuinely confused why you think any of this is a good idea

**Comment by xxalpha** [comment]
Redpills the pills

**Comment by MMMiracles** [comment]
a bucket now holds over 3x as much as a bluespace beaker.

a beaker that literally manipulates bluespace for its own capacity is out-shun by a metal bucket.

just let that sit in.

**Comment by xxalpha** [comment]
But you can't put the bucket in a grenade.

**Comment by WJohn** [comment]
Nor can you put the bucket in a chem dispenser/chem master. Filtering out the crap in it is impossible.

**Comment by coiax** [comment]
I mean, currently we have two pills containing more reagents than a literal bucket of water, and being able to contain the entire blood supply of a human in 14 pills. So you know, don't think that inconsistencies are unique to this PR. But we've got to start somewhere.

**Comment by PKPenguin321** [comment]
https://www.youtube.com/watch?v=_n5E7feJHw0

**Comment by Dorsisdwarf** [comment]
Reduce buckets to 200
Reduce tanks to 10,000 u

Balance here people

**Comment by Incoming5643** [comment]
you can put buckets in large grenades

**Comment by Shapsy** [comment]
This stuff was all fine balance wise, can we not change everything to completely arbitrary numbers to satiate one guy's autism

**Comment by MMMiracles** [comment]
chem dispensers/masters DO take buckets, literally all they check for is an a reagent_container with the OPEN_CONTAINER flag. 

this PR literally negates the purpose of beakers entirely, why ARE PEOPLE TAKING THIS PR SERIOUSLY AND POSITIVELY?

**Comment by AdamElTablawy** [comment]
>1000 units at roundstart

ohhhh boy chemists are going to have a fun time

**Comment by Core0verload** [comment]
+MEME PR tag

**Comment by Lumipharon** [comment]
Stop changing shit when you don't even know the mechanics.

**Comment by Core0verload** [comment]
He's just memeing. He takes shitty suggestions and does PRs on them to show how shitty they are.

**Comment by Jalleo** [comment]
@KorPhaeron SHUT THIS DOWN.

**Comment by coiax** [comment]
This is a serious PR in progress, so if you could uh, stop your endless complaints.

**Comment by optimumtact** [comment]
Slow the roll on the non feedback comments please

**Comment by Iamgoofball** [comment]
:+1:
can you make grenades support buckets too?

**Comment by optimumtact** [comment]
There's no oh my god why emojii for comments goof, so I'm leaving this comment instead

:scream: :fearful: :no_good:

**Comment by optimumtact** [comment]
This is... not popular

**Comment by coiax** [comment]
It's cool, I'll revisit it after datum antags.

**Pull request closed without merging**
