### PR TITLE
fix ntnet circuit components

### PR DESCRIPTION
**Pull request by Gurkenglas**
## About The Pull Request

Yeah so it turns out that someone wrote some ntnet components and didn't test them and then someone merged them and didn't test them so they never worked. Twice. So I went to fix it and it looks like someone wrote ntnet and didn't test it so it never worked. So here, have some marginally tested code. The first commit is the interesting one.

## Why It's Good For The Game

Components that don't work are embarassing.

## Changelog
:cl:
fix: The intern responsible for NTNet circuit components not working has been sacked.
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
Have you tested this? Are you sure that only circuits will recieve this message? That's pretty important yknow

**Comment by Gurkenglas** [comment]
I have tested that circuits receive this message; I observed it compute the target NTNet interfaces as the devices linked to the `SS13.CIRCUITS` network.

**Comment by Mothblocks** [comment]
NTNet code is so funky that I'm just going to keep merging these until they work

**Comment by Mothblocks** [comment]
Also as a sidenote if you expect maintainers to test every PR they merge you are nuts

**Pull request merged**
