### PR TITLE
Revert "[READY] Replaces the tesla/singulo on Pubby with a Supermatter"

### PR DESCRIPTION
**Pull request by carshalash**
Reverts tgstation/tgstation#42932

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
fantastic reasoning

**Comment by davethwave** [comment]
The stuff they added was not finished if you want a simple explanation.

**Comment by MrDoomBringer** [comment]
@davethwave then why not just finish it??? lmao ok

**Comment by zxaber** [comment]
Begun, the engineering wars have.

**Pull request closed without merging**
