### PR TITLE
Revert "Service Area Update"

### PR DESCRIPTION
**Pull request by carshalash**
This is nothing more than a massive pain in the ass for both the bartender and the chef, removing both of their abilities to be able to set up menus and food for whatever style they wish to provide. This PR only serves to try to force them both to share a single counter for god only knows what reason as well as  making their backrooms further away from their normal places of work.

The lack of the separation of the theater as well ruins things for the clown/mime and whoever else wants to be able to put on a show back there. I genuinely can't see how this improves anything for anyone.

### CODE REVIEW

**Comment by wesoda25** [comment]
Ew why was this merged in the first place

**Comment by carshalash** [comment]
God fucking knows.

**Review by ShizCalev — APPROVED** [review]

**Comment by ShizCalev** [comment]
i forgot to close it. my b.

**Comment by optimumtact** [comment]
I'm not going to approve a revert without at least a week of time of it being live.

**Pull request closed without merging**
