### PR TITLE
Adds an emagged flash to the surgical toolset arm implant

### PR DESCRIPTION
**Pull request by TheBonded**
## About The Pull Request
Allows you to emag the surgical toolset, because if you can emag the toolset one why not the surgical one?

## Why It's Good For The Game
more things to do with the emag

## Changelog
add: You can now emag the surgical toolset implant to unlock an integrated flash
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
Why a flash?

**Comment by TheBonded** [comment]
> Why a flash? 

Since the surgical arm already has a circular saw as a weapon, I thought adding a non weapon would make more sense. I chose the flash because I thought it would fit with the traitor mad doctor theme, flashing someone to kidnap them and force surgery on them.

**Comment by zxaber** [comment]
If anything, it should be a syringe.

**Comment by TheBonded** [comment]
> If anything, it should be a syringe.

Feels like a syringe would be too underpowered, maybe a hacked defib?

**Comment by zxaber** [comment]
A syringe you cannot drop or be disarmed of or have taken from you in a basic search would be underpowered?

**Comment by ExcessiveUseOfCobblestone** [comment]
ew

**Comment by TheBonded** [comment]
> A syringe you cannot drop or be disarmed of or have taken from you in a basic search would be underpowered?

Even so, a syringe that has a 3? second timer to inject someone and gives them a warning in huge red letters isn't super useful, and if you only need a syringe worth of chemicals just fill several syringes and hide em when not in use. Syringes can't be used offensively because of the timer so it wouldn't be worth buying an emag just to get a syringe you can easily get several of from asking medbay. You'd be better off buying a storage implant, putting beakers in it and using a syringe in your bag to take the chemicals out.

**Comment by Colovorat** [comment]
Maybe syringe with hypospray mechanic?

**Comment by moocowswag** [comment]
A syringe is like 15u of chems that nobody can take from you, sure youre limited to self use because they nerfed floor shove stuns but its still something if youre creative enough.

But if it really seems that underwhelming, add a small beaker ontop of it, the extra storage + being able to splash people/walls one time probably would make it worth an emag.

**Comment by PKPenguin321** [comment]
>Maybe syringe with hypospray mechanic?

^^^

**Comment by TheBonded** [comment]
> >Maybe syringe with hypospray mechanic?
> 
> ^^^
> this would actually be unique enough to be worth doing

I'll see what I can do

**Comment by Mothblocks** [comment]
Your changelog isn't formatted correctly.

**Comment by TheBonded** [comment]
> Your changelog isn't formatted correctly.

Good call, gonna close this pr anyways but I did not notice that

**Pull request closed without merging**
