### PR TITLE
Fixes nameless mechs

### LINKED ISSUE #40650: mech names accept not ascii chars
it doesnt generate runtimes or not create logs but it makes it invisible in ingame chat

### PR DESCRIPTION
**Pull request by deathride58**
Fixes #40650 
Mech code is decade-old spaghetti code but fixing that absolute mess is out of this PR's scope
Also reduces the change_name topic to ~~two~~ ~~three~~ four lines, down from five lines

:cl: deathride58
fix: Mechs now properly filter out non-ascii input, and can no longer have null names
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
refactor to obj/vehicle/sealed or bust @deathride58

**Comment by deathride58** [comment]
WYCI

**Comment by SpaceManiac** [comment]
When hitting "cancel", does the `null` properly filter through everything without runtimes?

**Comment by deathride58** [comment]
Pressing "cancel" resets the name to the mech's original name without any associated runtimes.

**Comment by SpaceManiac** [comment]
I would argue "Cancel" should do nothing rather than removing the name entirely

**Review by ninjanomnom — DISMISSED** [review]
What @SpaceManiac said

**Review by SpaceManiac — DISMISSED** [review]
Going through copytext/sanitize kills the `null`ness of the Cancel selection, that check needs to be before the rest

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
