### PR TITLE
Replaces Virologist room and job with a Fisherman and fishery (also completely annihilates viro machinery and advanced diseases)

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

Virologist has been replaced with a Fisherman job with a new outfit and icon

image

All stations have had their virology remodelled with a fishery
image
(also completely removes the pandemic and advanced diseases)
## Why It's Good For The Game

I do believe that, by removing advanced diseases and virology, we can achieve more engaging gameplay for viros/fishermen, via the magical power of fishing. With no advanced diseases nor the capability to make one, we no longer have to suffer to the average virologists 10 second death virus, with no real way to fight it without access.

Viruses are impossible to intuitively fight against if you dont have access or are sick with a virus that kills you in 20 seconds tops. Replacing this with fishing will provide far more engaging gameplay for viros than playing cookie clicker with beakers.
Indirectly also encourages the kitchen to seek out fishermen

## Changelog
:cl:
del: Pandemic machine, advanced diseases, virology, virologists
add: Fishery to replace virology, Fisherman to replace virologist
/:cl:

### CODE REVIEW

**Comment by Rex9001** [comment]
Fish doctor 2 electric bogaloo

**Comment by JohnFulpWillard** [comment]
This was funnier when it was actually adding fishing

**Comment by mc-oofert** [comment]
> This was funnier when it was actually adding fishing

mr.fun removal 1984s yet another pr

**Comment by ZephyrTFA** [comment]
Hold on, let them cook

**Comment by mc-oofert** [comment]
> Hold on, let them cook

WHAT COULD THEY POSSIBLY MEAN BY THIS

**Comment by KittyNoodle** [comment]
please god i would support any removal of diseases, if nanites had "no gameplay" then disease has negative gameplay, diseases spread incredibly fast on med-high pop and unlike in real life, where an immune system exists to provide a disease a deadline to spread, if one person gets infected they could theoretically spread it to everyone on the station. don't even get me started on the symptoms themselves, being stunlocked in medical while also on fire is the least fun thing imaginable, and removes any other interesting stories that might be happening by distracting everyone with the death virus of the round that inevitably forces a shuttle call

**Comment by Mothblocks** [comment]
it was only funny when wesoda did it

**Comment by moocowswag** [comment]
> please god i would support any removal of diseases, if nanites had "no gameplay" then disease has negative gameplay, diseases spread incredibly fast on med-high pop and unlike in real life, where an immune system exists to provide a disease a deadline to spread, if one person gets infected they could theoretically spread it to everyone on the station. don't even get me started on the symptoms themselves, being stunlocked in medical while also on fire is the least fun thing imaginable, and removes any other interesting stories that might be happening by distracting everyone with the death virus of the round that inevitably forces a shuttle call

It seems more like the problem with diseases is the lack of counterplay, we should look at ways to mitigate the symptoms of a disease so that a cure isnt the only short term solution.

**Comment by Sakamoto4ka** [comment]
B-)

**Pull request closed without merging**
