### PR TITLE
New Lavaland Station

### PR DESCRIPTION
**Pull request by ChangelingRain**
Updates mining station to a new design;
new new new buy it now

Fixes the gulag not having a conveyor switch(KOOOOOOOR)

:cl: Joan
rscadd: The mining station has been updated.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Current issue; like a whole bunch of these turfs don't have baseturfs set properly but I'm pinning that on kor

**Comment by KorPhaeron** [comment]
Maybe you should shift the gulag upwards a bit. A one tile lava gap is not that difficult to escape.

>3 mining lockers

Should probably be something else. That's a lot of free capsules.

>all these bright colours and lights everywhere

muh grimdark shithole aesthetic

>baseturfs not set

joan no we dont want space in lavaland aaaa

**Comment by KorPhaeron** [comment]
Thank you for preserving BRIDGES though I like the shape of the base

**Comment by KorPhaeron** [comment]
Not sure why you put the old stacking machine shit back either

**Comment by ChangelingRain** [comment]
This is basically the old mining station a la lavaland

**Comment by KorPhaeron** [comment]
We don't need those machines though they're just terrible sprawling versions of the ORM

**Comment by KorPhaeron** [comment]
Also this can't be merged until the aforementioned baseturf machine exists or you set it manually

**Comment by ChangelingRain** [comment]
We don't need them but they look cool
Kor get to work on the BASETURF MACHINE

**Comment by KazeEspada** [comment]
You could break into kor mining by walking around from the shuttle but you cant do that on this base.  

Also thanks making the base for three miners instead of two. Its supposed to have THREE lockers. Every thing in mining comes in threes.

**Comment by Supermichael777** [comment]
can we just replace the curent bridge city with this? It has the nice airlock that real humans can use without having to carry around batons to smack lesser miners into submision for tying the bridgelock at the wrong time.

**Comment by F-OS** [comment]
:+1:X:100: LOVE IT! this is perfect, makes me feel like lava land is not a death trap and brings back old www.ss13.eu memories!

**Comment by ChangelingRain** [comment]
Baseturfs corrected!

**Comment by TheWiznard** [comment]
know what the best part is



the shuttle is attached to the station


I like this a lot.

**Comment by Core0verload** [comment]
Will conflict the fuck out of #16577.

**Comment by Zilenan91** [comment]
Can you also remove the shitty mining machines because there's no reason to have them aside from people just not ever getting minerals to the station

**Comment by Saegrimr** [comment]
Did you make sure to add a stacking machine console in the gulag? Because theres no way to get the sheets out of it otherwise.

Otherwise just delete the stacking machine, its essentially useless.

**Comment by ChangelingRain** [comment]
It had one but the dir was wrong so it wouldn't connect and thus wouldn't work at all.
But Now It Works

**Comment by KorPhaeron** [comment]
Other issues

>medbay is overstocked

Too many medkits. There is an entire job dedicated to churning out patches. Go visit them some time.

>can't walk around the edges of the station outdoors

I just think this is fun/a good way for people to be able to break in and out.

**Comment by KorPhaeron** [comment]
Why do these coloured tiles agitate me more than anything else in this whole PR am I crazy

**Comment by ChangelingRain** [comment]
The stacking room, while it is wasted space is a good excuse to have the bridge like that, and it's not like the space it takes up would be anything but more lava.

**Comment by Saegrimr** [comment]
Yeah now that I think about it, the stacking machine has no more reason to even exist except as a material catcher for the crusher room. All stackable objects that move onto eachother auto-stack now, the conveyor belts do it all for you.

**Comment by KorPhaeron** [comment]
>undeclared changes

Joan pls

I mean they weren't terrible changes but that's a basic rule

**Pull request merged**
