### PR TITLE
Update github actions versions in the github workflows

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

As you may have noticed from the warnings in CI runs, Github is depreciating Node 12 since support for it was dropped in April. This is largely remedied by just updating the github action versions to v3. The parameters we use haven't changed their behavior. 

Note that multiple bespoke dependencies, such as `yogstation13/DreamAnnotate` haven't updated, so that might eventually break if Github completely drops Node 12.

## Why It's Good For The Game

Compatibility with changes in Github Actions

## Changelog

N/A

### CODE REVIEW

**Comment by Mothblocks** [comment]
CC @alexkar598 on DreamAnnotate using a deprecated node

**Review by Mothblocks — APPROVED** [review]

**Comment by alexkar598** [comment]
@Mothblocks @Tastyfish Thanks for the heads up! I'll get it updated before tomorrow and post a status update in here

**Comment by Tastyfish** [comment]
> @Mothblocks @Tastyfish Thanks for the heads up! I'll get it updated before tomorrow and post a status update in here

Awesome

**Comment by alexkar598** [comment]
`yogstation13/DreamAnnotate@v2` has been released using node16. No changes to the actual code. Ran a test or two and it seems to have accepted the new runtime.

**Comment by Tastyfish** [comment]
> `yogstation13/DreamAnnotate@v2` has been released using node16. No changes to the actual code. Ran a test or two and it seems to have accepted the new runtime.

Oh whoops, I reflexively updated my branch, not seeing #70493. Whatever.

**Pull request merged**
