### PR TITLE
Add the lore prefix for changelogs

### PR DESCRIPTION
**Pull request by optimumtact**
If someone has a small scroll sprite that fits with the rest of the changelog icons that would be

EGGXCELLENT

### CODE REVIEW

**Comment by Bawhoppen** [comment]
:scroll:

**Comment by optimumtact** [comment]
there's a small matter of copyright on that icon bawhoppen

**Comment by Cheridan** [comment]
hahahaha like anyone's ever going to do anything with ss13 lore

**Comment by Shapsy** [comment]
>not keeping up on the latest lore developments on IRC
l m a o

**Comment by Cheridan** [comment]
i went into #lorebus once and it was just some people circlejerking and talking about erping with phoebe lotsu so if that's the lore we're gonna get then you can keep it

**Comment by optimumtact** [comment]
ahah rekt

can I just clarify this is for changelogs that are just RP so you can ignore them safely

**Comment by Jordie0608** [comment]
I'm not sure I see the point in this, there shouldn't be an entry of just lore RP stuff in the changelog.

**Comment by optimumtact** [comment]
fine you bully

**Comment by duncathan** [comment]
I'm pretty sure the only lore change I've been around her was when Narsie became a girl

**Pull request closed without merging**
