### PR TITLE
Tasers and projectiles stun for the proper amount

### PR DESCRIPTION
**Pull request by ChangelingRain**
I should just leave it like this...

### CODE REVIEW

**Comment by Robustin** [comment]
Probably, 16s+ of stun for the baton just felt excessive.

**Comment by MrPerson** [comment]
Isn't this a balance change covered by the freeze?

**Comment by DoctoreMad** [comment]
Form what I understand the current stun time is a error in first place so no.

**Review by Cyberboss — APPROVED** [review]

**Comment by CPTANT** [comment]
Well this explains why I couldn't even cuff someone that I had just tazed.

**Comment by CosmicScientist** [comment]
Could you refer to your last PR #28524 as this is, I assume, fixing the numbers you missed? I thought this was an unnecessary buff (and was especially confused by the fix tag) until I looked into the file history.

**Comment by Bawhoppen** [comment]
soap is fucked too

**Pull request merged**
