### PR TITLE
Wendigo Resprite

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Tin, gives the Wendigo megafauna a brand new coat of paint, the mob sprite, trophy, and skull have been resprited as well, it also now has it's own unique death state. Also minorly updates the descriptions of a few items from the Wendigo to fit with their new looks.

Sprite-0003
## Why It's Good For The Game

Wowie zowie new sprites.
## Changelog
:cl:
imageadd: The wendigo has been resprited
/:cl:

### CODE REVIEW

**Review by axietheaxolotl — CHANGES_REQUESTED** [review]
ketchup blood
image
might be worth doing something darker/orange-y, e.g. ^

massive improvement regardless very nice 🤡

**Comment by Fikou** [comment]
image

**Comment by KittyNoodle** [comment]
Achievement textures changed?

**Comment by Serxule** [comment]
cool and good and h

**Comment by Jackal-boop** [comment]
holy shit

**Review by Imaginos16 — APPROVED** [review]
Approving this before I go on break, this better get merged.

**Pull request merged**
