### PR TITLE
Resprites the station bounced radio

### PR DESCRIPTION
**Pull request by ReinaCoder**
## About The Pull Request
resprites the station bounced radio
image

## Why It's Good For The Game
The old sprite was a noisy mess that was hard to tell what it actually was. Now it's much clearer that it's a radio walkie talkie thing 

## Changelog

:cl:
imageadd: The station bounced radio has been resprited
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
I think your changelog was sent a bit too early.

**Comment by castawaynont** [comment]
it looks like a remote, and less like a walky talky.

**Comment by thgvr** [comment]
could you perhaps provide a better screenshot on a table that is not so large, or with ambient occlusion disabled

**Comment by jacklecroy** [comment]
> it looks like a remote, and less like a walky talky.

Yeah it would look more like a walkie talkie with a larger single antenna and a different button layout.

**Comment by SmoSmoSmoSmok** [comment]
this is a best sprite i have seen in this gamee it looks like a cute mobile i am a string suporter of ur wirk this is an amaxzing exampl of ur amazing sprite work reinacoder :thumobsup:

**Comment by KommandantJackal** [comment]
Lacks the rugged feel of the current sprite. This looks too modern and lacks detail

**Pull request merged**
