### PR TITLE
Borgs synced to an AI using Doomsday will have their lights force-set to red and enabled to at least level 1

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
- Adds a variable for `lamp_doom` that keeps track of if the borg should be using doomsday lamp settings. Adds code that enables and disables this setting when the borg's AI activates doomsday, when doomsday is shut off for any reason, and if the borg syncs to (or loses sync with) an AI using doomsday. The `lamp_doom` var will override some things in `toggle_headlamp()`, forcing the lamp to be red and set to level one if it would be otherwise disabled. The only way for this light to shut off without affecting the doomsday or AI sync is for a nightmare to eat the bulb.

- Cleans up a small part of the doomsday code that is relevant to what I am changing.

## Why It's Good For The Game

- Gives some feedback that the borgs are *certainly* not crew-aligned. This shouldn't be a secret once doomsday alerts are playing, but it helps re-enforce that idea with some spooky visuals.

- Crucially, allows non-synced borgs to show the crew that they are not synced; if a borg has any color light aside from red while the countdown is going, you can be sure they're not on the AI's side. Of course, this goes both ways, and the AI can send it's borgs after the one that's showing the wrong color. Not-synced borgs can manually set themselves to use red and blend in, of course, so the AI can't necessarily use a red color alone to tell friend from foe.

## Changelog
:cl:
balance: Cyborgs synced to a Malf AI that activates Doomsday will now have their lamps forced to a red color and enabled to at least light level one. Stealth is no longer an option. Lamp options return to normal upon Doomsday deactivation, no matter the reason, or if the borg somehow loses sync with the AI.
/:cl:

TODO:
- [x] Full testing on a better computer
- [x] Make dead doomsday borgs turn their light off

image

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
Neat!

**Comment by carshalash** [comment]
Very neat

**Comment by RuneQuester** [comment]
Very spooky

**Comment by spookydonut** [comment]
@zxaber rebase/merge commit for working CI

**Pull request merged**
