### PR TITLE
Updates blood amount for alien/robot cleanables

### PR DESCRIPTION
**Pull request by Mickyan**
Forgot these for #40148, could have sworn they were subtypes but apparently not

### CODE REVIEW

**Comment by Mickyan** [comment]
Yeah.. I don't think I even checked these files beforehand since it seemed obvious that they would

I think I'll try to fix that next, I've never done something like that and seems like a good opportunity to practice, but I can't promise anything so I'd like to get this fix out of the way first

**Comment by ExcessiveUseOfCobblestone** [comment]
these aren't a subtype of blood hence the issue.

**Comment by Mickyan** [comment]
Yeeeeah I didn't think about having to fix all the maps at first.. still I'll consider it

Perfect example of mistakes coming to bite you in the ass years later

**Comment by ExcessiveUseOfCobblestone** [comment]
you should look at glass airlocks

**Pull request merged**
