### PR TITLE
Move NODROP_1, DROPDEL_1, ABSTRACT_1 and NOBLUDGEON_1 to item_flags where they belong

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
This PR also removes ABSTRACT_1 from various non-items (a smattering of effect subtypes), as it does nothing for non-items

:cl: Naksu
code: NODROP_1, DROPDEL_1, ABSTRACT_1 and NOBLUDGEON_1 have been moved to item_flags
tweak: brass handcuffs, meat hook and the chrono gun now conduct electricity.
/:cl:

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Typepaths where this PR changes flags from master, `crossover` is using new values

```diff
diff --git a/before b/after
index fd97e1a..d9e1129 100644
--- a/before
+++ b/after
@@ -332 +332 @@
-/obj/item/turret_control: flags_1=0, item_flags=0, crossover=768
+/obj/item/turret_control: flags_1=0, item_flags=0, crossover=896
@@ -459 +459 @@
-/obj/item/light_eater: flags_1=0, item_flags=0, crossover=832
+/obj/item/light_eater: flags_1=768, item_flags=0, crossover=512
@@ -462 +462 @@
-/obj/item/bloodcrawl: flags_1=0, item_flags=0, crossover=768
+/obj/item/bloodcrawl: flags_1=768, item_flags=0, crossover=0
@@ -492,2 +492,2 @@
-/obj/item/pickaxe/drill/cyborg: flags_1=0, item_flags=0, crossover=256
-/obj/item/pickaxe/drill/cyborg/diamond: flags_1=0, item_flags=0, crossover=256
+/obj/item/pickaxe/drill/cyborg: flags_1=32, item_flags=0, crossover=256
+/obj/item/pickaxe/drill/cyborg/diamond: flags_1=32, item_flags=0, crossover=256
@@ -1288,2 +1287,0 @@
-/obj/item/borg/upgrade/amop: flags_1=0, item_flags=0, crossover=0
-/obj/item/borg/upgrade/tboh: flags_1=0, item_flags=0, crossover=0
@@ -1724,7 +1722,7 @@
-/obj/item/construction/rcd: flags_1=32, item_flags=32, crossover=128
-/obj/item/construction/rcd/internal: flags_1=32, item_flags=32, crossover=128
-/obj/item/construction/rcd/arcd: flags_1=32, item_flags=32, crossover=128
-/obj/item/construction/rcd/combat: flags_1=32, item_flags=32, crossover=128
-/obj/item/construction/rcd/combat/admin: flags_1=32, item_flags=32, crossover=128
-/obj/item/construction/rcd/loaded: flags_1=32, item_flags=32, crossover=128
-/obj/item/construction/rcd/borg: flags_1=32, item_flags=32, crossover=128
+/obj/item/construction/rcd: flags_1=32, item_flags=32, crossover=0
+/obj/item/construction/rcd/internal: flags_1=32, item_flags=32, crossover=0
+/obj/item/construction/rcd/arcd: flags_1=32, item_flags=32, crossover=0
+/obj/item/construction/rcd/combat: flags_1=32, item_flags=32, crossover=0
+/obj/item/construction/rcd/combat/admin: flags_1=32, item_flags=32, crossover=0
+/obj/item/construction/rcd/loaded: flags_1=32, item_flags=32, crossover=0
+/obj/item/construction/rcd/borg: flags_1=32, item_flags=32, crossover=0
@@ -1737 +1735 @@
-/obj/item/pinpointer/syndicate_cyborg: flags_1=0, item_flags=0, crossover=256
+/obj/item/pinpointer/syndicate_cyborg: flags_1=32, item_flags=0, crossover=256
@@ -1755 +1752,0 @@
-/obj/item/mop/advanced/cyborg: flags_1=0, item_flags=0, crossover=0
@@ -1825,3 +1822,3 @@
-/obj/item/restraints/legcuffs/beartrap/mega_arachnid: flags_1=0, item_flags=0, crossover=64
-/obj/item/restraints/legcuffs/beartrap/energy: flags_1=0, item_flags=0, crossover=64
-/obj/item/restraints/legcuffs/beartrap/energy/cyborg: flags_1=0, item_flags=0, crossover=64
+/obj/item/restraints/legcuffs/beartrap/mega_arachnid: flags_1=32, item_flags=0, crossover=64
+/obj/item/restraints/legcuffs/beartrap/energy: flags_1=32, item_flags=0, crossover=64
+/obj/item/restraints/legcuffs/beartrap/energy/cyborg: flags_1=32, item_flags=0, crossover=64
@@ -1829 +1826 @@
-/obj/item/restraints/handcuffs/clockwork: flags_1=0, item_flags=0, crossover=64
+/obj/item/restraints/handcuffs/clockwork: flags_1=32, item_flags=0, crossover=64
@@ -1831,3 +1828,3 @@
-/obj/item/restraints/handcuffs/energy/cult: flags_1=0, item_flags=0, crossover=64
-/obj/item/restraints/handcuffs/energy/cult/used: flags_1=0, item_flags=0, crossover=64
-/obj/item/restraints/handcuffs/energy/used: flags_1=0, item_flags=0, crossover=64
+/obj/item/restraints/handcuffs/energy/cult: flags_1=32, item_flags=0, crossover=64
+/obj/item/restraints/handcuffs/energy/cult/used: flags_1=32, item_flags=0, crossover=64
+/obj/item/restraints/handcuffs/energy/used: flags_1=32, item_flags=0, crossover=64
@@ -3306,3 +3303,3 @@
-/obj/item/grenade/plastic: flags_1=0, item_flags=0, crossover=128
-/obj/item/grenade/plastic/x4: flags_1=0, item_flags=0, crossover=128
-/obj/item/grenade/plastic/c4: flags_1=0, item_flags=0, crossover=128
+/obj/item/grenade/plastic: flags_1=32, item_flags=0, crossover=128
+/obj/item/grenade/plastic/x4: flags_1=32, item_flags=0, crossover=128
+/obj/item/grenade/plastic/c4: flags_1=32, item_flags=0, crossover=128
@@ -3387 +3384 @@
-/obj/item/melee/cultblade/ghost: flags_1=0, item_flags=8, crossover=320
+/obj/item/melee/cultblade/ghost: flags_1=32, item_flags=8, crossover=320
@@ -5659 +5656 @@
-/obj/item/gun/magic/hook: flags_1=0, item_flags=8, crossover=128
+/obj/item/gun/magic/hook: flags_1=32, item_flags=8, crossover=128
@@ -5669 +5666 @@
-/obj/item/gun/magic/tentacle: flags_1=0, item_flags=8, crossover=960
+/obj/item/gun/magic/tentacle: flags_1=32, item_flags=8, crossover=960
@@ -5747,2 +5744,2 @@
-/obj/item/gun/ballistic/shotgun/boltaction/enchanted/arcane_barrage: flags_1=0, item_flags=8, crossover=64
-/obj/item/gun/ballistic/shotgun/boltaction/enchanted/arcane_barrage/blood: flags_1=0, item_flags=8, crossover=192
+/obj/item/gun/ballistic/shotgun/boltaction/enchanted/arcane_barrage: flags_1=32, item_flags=8, crossover=64
+/obj/item/gun/ballistic/shotgun/boltaction/enchanted/arcane_barrage/blood: flags_1=32, item_flags=8, crossover=192
@@ -5788 +5785 @@
-/obj/item/gun/energy/chrono_gun: flags_1=0, item_flags=8, crossover=320
+/obj/item/gun/energy/chrono_gun: flags_1=32, item_flags=0, crossover=320
@@ -5909 +5905,0 @@
-/obj/item/storage/bag/trash/bluespace/cyborg: flags_1=0, item_flags=32, crossover=0
```

**Comment by vuonojenmustaturska** [comment]
@SpaceManiac where'd you get a list like that

**Comment by SpaceManiac** [comment]
This Rust script with a git dependency on <a href="https://github.com/SpaceManiac/SpacemanDMM">SpacemanDMM</a>. Ran it before/after then diffed.

```rust
extern crate dreammaker as dm;
use dm::objtree::*;
fn main () {
    std::env::set_current_dir("../tgstation-upstream").unwrap();
    let ctx = dm::Context::default();
    let objtree = &ctx.parse_environment("tgstation.dme".as_ref()).unwrap();
    recurse(objtree, objtree.find("/obj/item").expect("no root"), &mut |ty| {
        print!("{}: ", ty.path);
        let mut flags_1 = ty.get_value("flags_1", objtree).expect("flags_1").constant.as_ref().expect("f1c").to_int().unwrap_or(0);
        let mut item_flags = ty.get_value("item_flags", objtree).expect("item_flags").constant.as_ref().expect("ofc").to_int().unwrap_or(0);

        let lhs =
            if flags_1 & (1<<1) != 0 { 1<<8 } else { 0 } |
            if flags_1 & (1<<2) != 0 { 1<<7 } else { 0 } |
            if flags_1 & (1<<6) != 0 { 1<<9 } else { 0 } |
            if flags_1 & (1<<10) != 0 { 1<<6 } else { 0 };
        flags_1 &= !((1<<1) | (1<<2) | (1<<6) | (1<<10));

        let rhs = item_flags & ((1<<6) | (1<<7) | (1<<8) | (1<<9));
        item_flags &= !rhs;

        let crossover = if rhs != 0 && lhs != 0 {
            panic!("flags_1={}, item_flags={}, lhs={}, rhs={}", flags_1, item_flags, lhs, rhs);
        } else if lhs != 0 {
            lhs
        } else {
            rhs
        };

        println!("flags_1={}, item_flags={}, crossover={}", flags_1, item_flags, crossover);
    });
}

fn recurse<F: FnMut(TypeRef)>(objtree: &ObjectTree, ty: TypeRef, f: &mut F) {
    f(ty);
    for child in ty.children(objtree) {
        recurse(objtree, child, f);
    }
}
```

**Comment by vuonojenmustaturska** [comment]
goofs: 
- light eater and bloodcrawl i forgot to rename the var to item_flags.
- forgot to check for flags_1 removals from parent, cyborg drills, borg syndi pinpointers, beartraps, plastic explosives, ghost swords, tentacles, arcane barrage specifically removed CONDUCT_1 they would otherwise inherit
- RCD i forgot NOBLUDGEON on, fixed.

changes:
- /obj/item/turret_control's NOBLUDGEON was originally in resistance flags, i moved it into item flags.
- brass handcuffs, meat hook, chrono gun should CONDUCT_1

**Comment by SpaceManiac** [comment]
Updated report with items newly added on master removed. I think each of these has been explained.

```diff
diff --git a/before b/after
index fd97e1a..5f1bb5b 100644
--- a/before
+++ b/after
@@ -332 +332 @@
-/obj/item/turret_control: flags_1=0, item_flags=0, crossover=768
+/obj/item/turret_control: flags_1=0, item_flags=0, crossover=896
@@ -1829 +1826 @@
-/obj/item/restraints/handcuffs/clockwork: flags_1=0, item_flags=0, crossover=64
+/obj/item/restraints/handcuffs/clockwork: flags_1=32, item_flags=0, crossover=64
@@ -1831,3 +1828,3 @@
-/obj/item/restraints/handcuffs/energy/cult: flags_1=0, item_flags=0, crossover=64
-/obj/item/restraints/handcuffs/energy/cult/used: flags_1=0, item_flags=0, crossover=64
-/obj/item/restraints/handcuffs/energy/used: flags_1=0, item_flags=0, crossover=64
+/obj/item/restraints/handcuffs/energy/cult: flags_1=32, item_flags=0, crossover=64
+/obj/item/restraints/handcuffs/energy/cult/used: flags_1=32, item_flags=0, crossover=64
+/obj/item/restraints/handcuffs/energy/used: flags_1=32, item_flags=0, crossover=64
@@ -5659 +5656 @@
-/obj/item/gun/magic/hook: flags_1=0, item_flags=8, crossover=128
+/obj/item/gun/magic/hook: flags_1=32, item_flags=8, crossover=128
@@ -5788 +5785 @@
-/obj/item/gun/energy/chrono_gun: flags_1=0, item_flags=8, crossover=320
+/obj/item/gun/energy/chrono_gun: flags_1=32, item_flags=0, crossover=320
```

**Comment by vuonojenmustaturska** [comment]
energy handcuffs were still conducting, fixed

**Comment by vuonojenmustaturska** [comment]
also a milestone added for your script

**Pull request merged**
