### PR TITLE
Removes Jetpacks From Icebox EVA

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Removes the two jetpacks from EVA on icebox, and replaces them with random items that were on the floor in EVA for some reason.

## Why It's Good For The Game
There's nowhere to use the jetpacks on icebox, why would you ever need them.
Also why were there these random things on the floor.

## Changelog
:cl:
tweak: replaced jetpacks in eva on icebox with those random things that were on the floor for some reason
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by optimumtact** [comment]
but what if the gravity runs out

**Comment by uomo91** [comment]
> but what if the gravity runs out

If it's on a planet/moon anyway, would you or the maintainers approve of somebody (maybe me) just PR giving it perma gravity and removing the generator?

**Comment by Jared-Fogle** [comment]
> would you or the maintainers approve of somebody (maybe me) just PR giving it perma gravity and removing the generator?

There is no gravity generator on Ice Box.

**Comment by uomo91** [comment]
Aw, did oranges bamboozle me?

**Comment by Paxilmaniac** [comment]
If the gravity runs out on icebox, you have bigger problems

**Comment by Spepbuthewranglesgithub** [comment]
sounds like the miners are getting out of hand

**Comment by Doosteroni** [comment]
The hull has been breached and the Gravity is leaking out!

**Review by uomo91 — APPROVED** [review]

**Pull request merged**
