### PR TITLE
Removes separated chemicals trait

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl:
del: removed the separated chemicals trait
/:cl:

I've been meaning to do this for a while. Separated chemicals is mainly used for botany explosives, which are a spammable one hit kill on almost everything. This has been especially bad since I fixed the bug that broke its interaction with squashing.

Botany will still have many tools without these instakills, especially after #42268. This should make botany's weapons both more balanced and more varied. 

Smokeplants will still be possible, but will require mutating traits into plants. 
In summary, botany needs a nerf in general, and this seems a good place to hit it.
note: EMPs will be lost as well

~~disclaimer: my children ded~~

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Seperated chemicals are used to make mannitol.

**Comment by 4dplanner** [comment]
> Seperated chemicals are used to make mannitol.

Why can't you just put all the ingredients in one plant?

**Comment by HomocidlePancakes** [comment]
Because plants have a capacity of 50u and it gets deleted if it gets mixed inside of the plant

**Comment by BebeYoshi** [comment]
It's used for smokes, death nettles memes, cleaning grenades and bombs as you mention. It also useful if you don't want to be spammed with the reaction sound for mutagen plants AND to disguise bad plants (aka making "healing plants")

**Comment by BebeYoshi** [comment]
You could argue that there is a "smoke" trait, but it's not realiable, and could be removed instead of the super useful separated chem. The only use to the smoke trait is not using 30%/60% of the plant for smoke reagent

**Comment by 4dplanner** [comment]
> Because plants have a capacity of 50u and it gets deleted if it gets mixed inside of the plant

25% sugar + 20% water + 5% hydrogen < 100%

**Comment by BebeYoshi** [comment]
They are also annoying to get before you have infinite mutagen and seeds due to not being a guarantee mutation,I usually use 2/3 seeds and 130u of mutagen to get it usually.

**Comment by HomocidlePancakes** [comment]
7% sugar from cherry, 4 % water from pineapple and 5% hydro from grass.

**Comment by HomocidlePancakes** [comment]
All of the other space is used up by healing chems

**Comment by 4dplanner** [comment]
Sorry, what's your problem here? Is it that you can't cram as many healing chems into one plant? You can make mannitol just fine.

**Comment by BebeYoshi** [comment]
> 7% sugar from cherry, 4 % water from pineapple and 5% hydro from grass.
You don't need separeted chem for that, and you also need to put banana juice in it so people won't get fat add 10% to it

**Comment by 4dplanner** [comment]
Actually just going to remove the trait so you don't randomly get it

**Comment by BebeYoshi** [comment]
Red Onions would be a good choice since onions smokes when you cut them and Red Onion is a mutation/better version of Onions

**Comment by 4dplanner** [comment]
You're right, moving it

**Comment by HomocidlePancakes** [comment]
gaia1
Ok so here is what i was talking about. I usually make this every botany shift and give out to crew. Without the seperated chems all of the mannitol just gets deleted

**Comment by BebeYoshi** [comment]
@HomocidlePancakes No it's mixed, it just not detected 'cause it was created by a reaction, not by the plant itself

**Comment by BebeYoshi** [comment]
Try grinding them

**Comment by 4dplanner** [comment]
Yeah, I should fix that scanner bug sometime

**Comment by HomocidlePancakes** [comment]
Well shit. I always though it was getting deleted.

**Comment by 4dplanner** [comment]
@BebeYoshi what do you think of this with the red onions buff?

**Comment by BebeYoshi** [comment]
It will make smokes easier since onions only have one mutation, but I can't think of any other plant that would make sense with it

**Comment by HomocidlePancakes** [comment]
Was there any reason why gaseous got locked up behind RNG? Or was it always like that.

**Comment by BebeYoshi** [comment]
@HomocidlePancakes having smoke trait would make it very easy to overload your plant with bad chems while not needing to worry about not having space for the smoke reagent, but without separeted chem it's impossible to make smokes without the smoke trait

**Comment by recurracy** [comment]
I'm not sure how I feel about this. Seperated chemicals has many more uses than just smoke.

**Comment by 4dplanner** [comment]
Such as?

**Comment by 4dplanner** [comment]
I'm willing to lose a bit of functionality for the cleanest way to balance, but if there's something genuinely important I've missed I'd like to know.

**Comment by Shadowflame909** [comment]
I'll miss Shock-Tomatos though.

STUNNING TOMATOS!

**Comment by BebeYoshi** [comment]
@Shadowflame909 You can still shock them with the Electrical Activity trait

**Comment by Daxxed** [comment]
Another good PR by 2ded4prescanner.
PS: Thank you, where do I deposit the bribe ?

**Comment by 4dplanner** [comment]
> Another good PR by 2ded4prescanner.
> PS: Thank you, where do I deposit the bribe ?

No bribe until you upvote

**Comment by 4dplanner** [comment]
> I can understand the removal of separated chemicals from glowberries, but does the trait need to be removed altogether? I don't think game balance would be negatively impacted by having separated chemicals in strange seeds every now and then.

It could then also be mutated by dropping 2u of mutagen in, I believe.

**Comment by Tlaltecuhtli** [comment]
make plants act as beakers for grenade assemblies

**Comment by 4dplanner** [comment]
> make plants act as beakers for grenade assemblies

good idea tbh

**Comment by necromanceranne** [comment]
Keeping it locked behind strange seeds is a perfectly fine way to keep it from being too much. But as it stands separated chemicals is too important not to have for botany in producing a lot of otherwise beneficial plants, and in comparison to chemistry, who can shit out high explosives at incredibly fast rates, this seems like it's excessive.

**Comment by ExcessiveUseOfCobblestone** [comment]
You don't need cryobeakers for most medicines I don't see why it's imperative to have cryoplants.

**Comment by 4dplanner** [comment]
> a lot of otherwise beneficial plants

Eh? Not many examples have been given, and even fewer with gaining gaseous decomp.

**Comment by Shadowflame909** [comment]
@BebeYoshi  Won't be my tesla shock tomatos though.

poor teslium and water

**Comment by OverlyGeneric** [comment]
This is wholly unnecessary and negative toward the contribution of the codebase.

I'm starting to get sick of these "balance" PRs that remove aspects that make the game interesting and fun.

It doesn't help that most of your PRs seem to be changing things you don't like rather than something that is critically broken or that you have contributed anything remotely of a new feature apart from a stale unfinished product.

-1

**Comment by duckay** [comment]
i don't get it, are you removing the trait or the trait from the glowshrooms?
you've confused me.

**Comment by duckay** [comment]
> The PR removes Separeted Chemical trait as a whole, so it removes it from glowberries and from the game so you can't get it randomly
Fair.

**Comment by AdamElTablawy** [comment]
tbh considering the insane shit you can usually get from strange seeds, it seems fine enough if you roll lucky on seeds to get separated chemicals, but having it be available through glowberries is plainly ridiculous since it's effectively just spammable, easy to make grenades that kill anyone they hit instantly like an explosive spear.

i'd favor leaving it in strange seeds instead of removing it from the game entirely.

**Comment by imsxz** [comment]
gaseous decomp is a pretty insane botany buff. not sure botany is in a place to need compensation buffs, it’s a xenobio tier role (leave em in their autism corner for 20 minutes and they become unkillable and can instakill) (yes you can do adv botany that quickly if you set out with a goal in mind and know how to properly abuse chem dispensers)

**Comment by AnonymousNow** [comment]
Correct me if I'm wrong, but doesn't this run the risk of stranding Lifegivers without a means of digging?

**Comment by 4dplanner** [comment]
> Correct me if I'm wrong, but doesn't this run the risk of stranding Lifegivers without a means of digging?

I believe they should always be able to mutate lemons to get explosive lemons.

**Comment by 4dplanner** [comment]
> not sure botany is in a place to need compensation buffs

You might be right, I need to think about this. Even without the red onion part smoke memes would still be possible, they'd just be higher effort.

**Comment by 4dplanner** [comment]
I think you're right, sorry botany mains

**Comment by BebeYoshi** [comment]
Thanks, once again!

**Comment by k-k-karma** [comment]
Botany is immensively overpowered and can instakill and stun with explosives.

**Comment by Shadowflame909** [comment]
Everything is overpowered and unless you nerf everything, there's always something to complain about.

Botany has a hellish lategame

Doctors have a Antagworthy Bannable lategame

and Greytiders can get Pulse Pistols and Nukie Hardsuits if they're persistant.

**Comment by ExcessiveUseOfCobblestone** [comment]
> botany has a hellish late-game

botany can be a powerhouse quite early in the round if you know what you're doing. Luckily, most people don't.

Also no tear would be lost if lances disappeared. None.

As for the PR, why not leave it in as a available gene from stranges? That's what is implied by your cl anyways 😏

**Comment by Shadowflame909** [comment]
Well, I don't even play Botany for the separated chem magical madness so I don't have much to complain about other than for my own temperamental sake.

You leave me with no choice cobblestone.

"Improve don't remove"

this pr is nothing but the last thing.

**Comment by 4dplanner** [comment]
Whoops, forgot to change the changelog. The reason I didn't leave it in for strange plants is because having botany randomly become extremely overpowered x% of rounds is bad game design, in my opinion.

**Comment by Shadowflame909** [comment]
What's the point of Strange Seeds being able to get Changeling Adrenals, Hell Water and the last needed element for Zombie-Powder then

**Comment by 4dplanner** [comment]
Just because it's already a thing doesn't mean it needs to be made even more extreme.

**Comment by ExcessiveUseOfCobblestone** [comment]
the gene is hardly comparable to adrenals/mutation tox tho, especially considering most applications are covered by other genes (smoke particularly) and plants (spicy lemons).

**Comment by 4dplanner** [comment]
There are fewer traits than chemicals, so you're much more likely to roll it. 

Explosive lemons are not a replacement for liquid contents at all - they have a timer, so are far less powerful and have a tiny explosion. 

I'd say also that spammable instakills are MORE powerful than mutation toxin.

**Comment by IllotAFV** [comment]
I’ve played a lot of rounds as a botanist. And I shall say, that separated chemicals is the most offensive trait in whole book of botany magic. It gives you the opportunity to make  teslium bombs, nitroglycerin bombs, smoke bombs, EMP bombs under 10-12 minutes mark. Half of these grandes are instant killers. If you play as chemist, you can make those too, but it takes way more resources than botany needs for the same. I’ve used this trait to actually help station only once, that’s it. And even when I don’t like this PR, I shall admit, that separated chemicals is super duper overpowered thing. Even stronger than late game miner or research director. I mean,  botany still can kill everyone under 15 mins mark even without this trait. It just takes more wise plays, than full bag of nitroglycerin tomatoes.

**Comment by AdamElTablawy** [comment]
@Shadowflame909 nothing to improve with botany that can't be improved only through a nerf

it's hilariously powerful if you have any idea what you're doing and significantly deadlier than literally any other department bar robotics with a mech

maxcaps? yeah, they can do that. instant kill throwing spears which you can fit 50  of in a bag and look like anything? yep. render the entire station impossible to see with glowshrooms? sure. a variety of lethal chemicals? yeah.

or have you forgotten the days when botanists would routinely wipe out the station with kudzu, spider spam and instant-gib tomatoes?

at least with separated chems gone, botanists are merely superior chemists with an infinite syringe gun who can apply a ridiculous amount of deadly reagents to you, instead of superior chemists with an infinite gyrojet pistol

**Comment by 4dplanner** [comment]
How are botanists making maxcaps, by the way? I hear this mentioned a lot, but I've never seen it.

**Comment by ExcessiveUseOfCobblestone** [comment]
Hmmm fair enough. I don't use cryoplants anyways ;)

**Comment by AdamElTablawy** [comment]
@4dplanner nitroglycerin is stupid powerful and metamaterial beakers are available almost instantly

two 150u reagent containers put together in a grenade will result in 300u of nitroglycerin and, accordingly, a fuckhuge explosion that if not maxcap is still sufficiently large to remove a decent portion of a department, and are absolutely trivial to mass produce since botany is the *only* department with access to the chemicals for nitro and those are easy to get

**Comment by imsxz** [comment]
probably injecting the chems of one thing into a noreact omega weed leaf or something, rather than harvesting maxcaps straight up. still not too hard to do.

**Comment by 4dplanner** [comment]
> Also no tear would be lost if lances disappeared. None.

off topic, but lances are one of the only good mech counters.

**Comment by ATH1909** [comment]
i ded

**Comment by habader** [comment]
i ded

**Comment by BebeYoshi** [comment]
At the end no matter the negative feedback it will just being up to maintainers like the auto cloning PR

**Comment by 4dplanner** [comment]
:)

**Comment by wesoda25** [comment]
On one hand some cool stuff might be removed from botany but on the other botany needs nerfs...

**Comment by imsxz** [comment]
>justifying unnecessary overpowered features with ided

i mean yeah overpowered stuff that is used for murder tends to kill people

**Comment by 4dplanner** [comment]
Fun fact: I have never died to botany explosives, as a cursory grep of the logs will show

**Comment by uBadush** [comment]
This will leave botany crippled, and will transfer people to powegame something else and cause you to nerf this something else as is happening now

**Comment by AdamElTablawy** [comment]
the thing is unlike the cloning pr the negative feedback soley consists of salty botany mains who are upset they can't whip out instant kill plants anymore for the single most overpowered department in the game

**Comment by uBadush** [comment]
No I'm not, you are just blinded it will leave botany in a super weak state towards aggressive methods, before applying this nerf you should look at adding stinging on attack by from hypodermic prickles because it's non existence now makes no sense and will make death nettles useful again or replacing separated with gaseous since smoke will be the only kind of grenade we will be able to make

**Comment by uBadush** [comment]
The thing is maintainers don't listen to community they just do whatever they want related to "balance"

**Comment by AdamElTablawy** [comment]
'super weak state'

you have superheal plants and access to stun resistance, instant thrown hypospray injectors, protection against cult magic, melee weapons that do 45 damage a hit or 30 damage and set you on fire depending on deathnettle or novaflower, access to bombs, gear-destroying plants you can fit 50 of in a bag, and access to traitor-only chemicals like curare and coiine, and kudzu.

you know what chemistry has

access to grenades and maybe a single-shot ranged weapon that doesn't work through hardsuits without R&D helping out, and access to chemicals botany can produce by itself with rare exception, some of which are less lethal, and all of which contain less in a single application than the others, and the aforementioned healing chemicals.

you know what engineering has?

fucking nothing but tools

you know what the bartender has? a shotgun. you know what cargo has? maybe guns if they order them.  you know what the janitor has? soap and a trashbag.

the literal only departments on par with botany in terms of insane bullshit they can pull out are science, which has always been hilariously OP, mining, assuming the miner is robust enough to kill all the megafauna for the phat loot, and robotics, with mechs.

yeah, no, it's not a super weak state. you still have access to stronger weapons than literally anyone else on the station has access to, including security barring that science actually researches weapons, and a variety of terrifying poisons, healing chemicals, stun resistance, hostile mobs, and more, and all of them are obtainable in an absolutely minimal amount of time.

you _don't_ need instant kill grenades, which you can fit 50 of in your bag, or mass-traitor poison smoke grenades, which you can fit 50 of in your bag, to remain powerful. you're already powerful as is.

and is it any wonder they aren't listening to the 'community', when the community opinion, so far, seems to be stupid as fuck?

**Comment by AdamElTablawy** [comment]
@HideAndSeekLOGIC it's stupid and overpowered

**Comment by DaydreamPuppeh** [comment]
Gross. Another nerf from 4dplanner

**Comment by OverlyGeneric** [comment]
@4dplanner If the problem is that it's too common. Add more traits. We could always use new traits for botany.

**Comment by AdamElTablawy** [comment]
@OverlyGeneric He already said that one, the problem isn't that it's too common, it's that it exists at all. Strange seeds being the things that contain separated chemicals instead of just glowberries was rejected for that reason-randomly getting it is still bad, if it's OP. 

And it is.

**Comment by imsxz** [comment]
sad to see this PR getting attacked by botany "mains" that copied someone elses cookie cutter explosive plant strat and never expanded on it themselves.

the only thing botanys even missing at this point is growable space suits but hey they get spaceproof species mutation toxins often enough anyways. i really dont see how anyone can argue that botany will be crippled with separated chems gone.

**Comment by PKPenguin321** [comment]
there was a botanist who had a tomato or something on the table that if you picked it up, even with gloves, it would instantly disappear and inject a fuckton of poison into you that would kill within a minute

**Comment by venomsnak** [comment]
> On one hand some cool stuff might be removed from botany but on the other botany needs nerfs...

most of the stuff botany uses is time sensitive along with separated chems unless you get the traits through  strange seeds and get a fast chemist. The change will only make for a duller botany experience and frankly it would've been simpler to just toss it into strange seeds and remove it from glowberries but this change is just a lazy way of dealing with it.

**Comment by optimumtact** [comment]
Holy shit you people are literally the worst. I don't know what you think this negative kind of comments to peoples PR's is doing, but it sure as shit doesn't make me see your point of view.

There's literally zero reasons to not merge this because most of you can't come up with a coherent argument beyond "you're bad" and "you died". If you think I don't listen to feedback it's because you're leaving the most incoherent, stupid feedback that is possible to give, if spent any time entertaining it I think I would lose brain cells.

I sure as hell am not going to give the time of day to people who's only response to a PR changing something they don't like is to drop their toys on the floor and scream super loudly in the hope somebody gives in because they're upset.

The people saying this destroys botany are literally out of their minds, and clearly only play the role to make fucking plant based grenades using this trait.

I'm sick and tired of chemistry reagent reactions being so overpowered and I will most likely be merging this PR and would welcome a bunch of resets on chemistry being so broken.

**Comment by uBadush** [comment]
if the OHK explosion is the problem remove nitroglycerin from botany not separated chemicals i agree this with @venomsnak that this is a lazy nerf, you can only get curare from strange seeds if you dont want it appearing blacklist from strange seeds, you cannot put 1000 poisons in the fruit, fruits have a limit of 100 uits of chemicals with densified and stinging only inject 20 per use so it can be used against you after you threw unless you put less than 20 units of poison, EMPs will turn impossible, carpet will turn impossible, tesla shock will turn impossible, smoke without gaseous trait will turn impossible, holy water bombs will turn impossible, if nitroglycerin is the problem remove nitroglycerin not sperataed chemicals

**Comment by 4dplanner** [comment]
All of those are good things except the sad loss of carpets

**Comment by duckay** [comment]
Hogging 100th comment for the fuck of it

**Comment by uBadush** [comment]
"all those are good things" no wtf

**Comment by ExcessiveUseOfCobblestone** [comment]
> The thing is maintainers don't listen to community they just do whatever they want related to "balance"

It's quite selfish to imply that because people scream loud enough they comprise a majority of the playerbase.

I don't think any maintainer asked for this PR, so there's obviously some community concern about the power levels of botany else this PR wouldn't exist. If you actually cared about the community (i'd like to think you do), you should instead suggest how you'd approach the grievance or even perhaps contribute your solution yourself. **Saying platitudes (i'm a victim of doing this myself) doesn't help anyone.**

That said, it's much easier to move forward with a finished PR than it is to move forward with just an idea (although you should always ask first so you don't waste time working on a PR imo).

**Comment by kriskog** [comment]
@4dplanner 
If you want to prevent botany from making instakilling nitroglycerin plants, can't you just adjust however much nitroglycerin you are able to make in a single plant? Since sulphuric acid isn't used in much else (that you can make directly in plants), you can reduce the available traits without affecting much else. 

Current amount of nitro per plant: 6.66u
Reduce sulphuric acid production to 10%:  4.44u
Reduce sulphuric acid production below 6.6%: 2.66u

The last option can be reduced to 0u by increasing the amount of oil you get from sunflowers.

This current change ruins a lot of the fun potential of botany, most of which is non-lethal. Bored botanists is how you get murderboning/griefing/absent botanists.


As a note, this doesn't affect me when antaggin as botanist. I usually just use smoke for fun stuff as non-antag, and don't use the nitro plants.

**Comment by 4dplanner** [comment]
All that would do is make them require slightly more tedious injection, instead of straight harvesting. This still allows you to carry hundreds of explosive lances. This is without even getting into nerfing potwater as well. 

Possibly more importantly, I just don't believe they a lot of fun potential in botany is from separated chemicals. As I've said, the only loss of non-nerfworthy content here is carpet explosions, which are not hugely important.

**Comment by uBadush** [comment]
The reason for nerf is nitroglycerin but he nerf lots of shit together cause lazy

**Comment by 4dplanner** [comment]
Lol

**Comment by ExcessiveUseOfCobblestone** [comment]
no no no.

Making huge explosions using outputs from plants: fine.

Making huge explosion plants: not fine.

**Comment by kriskog** [comment]
At most, you can get a 10/10 pot/water explosion from plants. This is barely enough to hurt, and is already balanced by available chemical traits. Anyway, if people are injecting stuff into the plants to make more nitro it isn't just something you can grow an infinite amount of anymore. Now it involves some preparation.

If that still isn't enough for you, how about changing how liquid contents handle explosive substances on squashing?

**Comment by ExcessiveUseOfCobblestone** [comment]
The issue is not that you can make bombs from botany. You've always been able to even before gene machine. I have no issue with that and personally don't want that to go.

The issue is that these bombs are primed and ready to roll straight off the vine.

If you want to add cryobeakers to the service lathe (if not already in) then feel free to do so.

**Comment by kriskog** [comment]
> The issue is that these bombs are primed and ready to roll straight off the vine.

So do something about that, specifically. Removing separated chems is a blanket change that hits a lot of different (and not problematic) use cases to fix a single use case. I've given reasonable suggestions, there are alternatives.

**Comment by ExcessiveUseOfCobblestone** [comment]
Does this explain it better?

Making [chemistry device] using outputs from plants: fine.

Making [chemistry device] plants: not fine.

None of your suggestions lower the "not fine" and in fact hurt the "fine" aspect. The PR, however, does the opposite.

**Comment by uBadush** [comment]
If even injecting fruits is not cool then chemistry grenades aren't cool either because you only need to fill beakers and even the basic grenade can handle 200 units, fruits 100 units  with densified chemicals, but now imagine the time spent injecting fruits with syringes and handling chemicals, saying that you can make hundreds of it is bullshit even chemistry grenades production would be faster and more effective since you can fill a beaker only by pressing one button "but dispensers units run out" bullshit you just need to replace the battery if you aren't brain dead you know that, still be able to inject fruits and make bombs should be fine because chemistry work equals and not one say shit, if not even making grenades this way is fine just remove explosives from the game

**Comment by uBadush** [comment]
Remove nitroglycerin but not separated chemicals

**Comment by kriskog** [comment]
Is this PR now about removing smoke as well? From what I can tell from the main post, this was done to prevent instakilling explosive plants.

My reduction in sacid production doesn't hurt the <fine> much, just plant another sacid plant in another tray to do your <fine> nitro mixing. Or use a chem dispenser, you'll most likely have one anyway.

**Comment by 4dplanner** [comment]
Gaseous decomposition is still in.

**Comment by kriskog** [comment]
Yes, in strange seeds. So you'll see it rarely, which might as well mean smoke is gone.

**Comment by 4dplanner** [comment]
You don't need strange seeds for it :^)

**Comment by uBadush** [comment]
Still in behind shitton of rng because you can't make using chemicals from fruits anymore

**Comment by ExcessiveUseOfCobblestone** [comment]
You can still make smoke grenades I literally just check

**Comment by 4dplanner** [comment]
> You can still make smoke grenades via botany I just checked. That's without Gaseous Decomp btw.

...how?

**Comment by ExcessiveUseOfCobblestone** [comment]
Not smoke grenade plants

**Comment by optimumtact** [comment]
@ExcessiveUseOfCobblestone high content count beakers are part of the problem with chemistry as well, so don't be running around adding more of them please

**Comment by optimumtact** [comment]
I assume he means you can print grenade casings and beakers and make grenades from the reagents harvested from plants

**Comment by ExcessiveUseOfCobblestone** [comment]
yes but how will I be able to make (nuclear) winter without them D:

**Comment by optimumtact** [comment]
You won't, which is the point

**Comment by ExcessiveUseOfCobblestone** [comment]
ima nuke u now

**Comment by Charredgp** [comment]
Looks like someone's mad that they got out-robusted by a botanist. :^)

**Comment by adamkad1** [comment]
> gaia1
> Ok so here is what i was talking about. I usually make this every botany shift and give out to crew. Without the seperated chems all of the mannitol just gets deleted
Fuggen normies not using Omega Weed to make epic healplant

**Comment by ExcessiveUseOfCobblestone** [comment]
lol it's 2019 you only need enough mutagen to make blumpkins.

**Comment by WaterStBlues** [comment]
>actually making blumpkins

**Comment by ExcessiveUseOfCobblestone** [comment]
> needs mutagen
> but chemists are gross
> tfw the bucket can't fit as a mask to catch your tears

I'm willing to get my hands dirty... are you?

**Comment by AnActualDog** [comment]
Hi, botany main here who played so much botany that he put a guide for it on the wiki back in the day.
First of all, let me say that the idea behind the nerf is more than justified - with the potassium-water reaction now being able to hullbreach, chemicals able to be injected into plants again and nitroglycerin plant grenades being the most OP (though risky) shit ever one cannot argue that the destructive potential of botany deserved a nerf. And don't forget about fucking killer tomatoes, too.
In my experience, the philosophy of botany is "you either die a top tier support class or live long enough to become a greentider"... or something like that. The root of that problem is twofold: Huge destructive potential and limited (if strong) support potential. Even if you, as a botanist, WANT to help others rather than greentide, you run out of ways to support pretty quickly and - again, in my experience: - once that happens the griefing begins.

The supporting tools of botany other than Ambrosia Gaia (ideally improved with Mannitol and other chems) have been taken from them one by one are:
-> Acid gas no longer has an impact on Blobs
-> Speedboost joints (Meth + Mannitol) no longer speed you up
-> Hypodermic Prickles no longer apply on-hit so things like quickly healing people by hitting them with your improved ambrosia or using holy water nettles as a weapon against the cult are out.
-> Because of the science rework, botanists no longer support research with Glowcaps and Ambrosia Gaia
-> (Bombs from botany could have theoretically been used to generate science points but noone ever did that.)
-> Supporting the chemists (trading for the dispenser) by giving them empty plants with seperated chems as grenade casings to inject stuff into first got removed when you could no longer inject chems (which got fixed) and now by removing seperated chems
-> Strange reagent takes ages to make and you can just clone people using pods so... meh?
And I am sure I am forgetting about some support-ability nerfs here somewhere, but you get the point.

On the other hand, the offensive abilities only got nerfed by reworking Hypodermic Prickles to no longer apply on-hit (good idea), but then liquid contents got changed to activate on-slip (making sneaky one-hit death mines VERY possible) which is arguably stronger than on-hit-prickles. Obviously without removing that feature something HAD to be done about explosives. Also keep in mind that Hypodermic Prickles also apply on slip now, but are still countered by hardsuits (= half the crew). Meanwhile you can counter gas by using internals, of course, but most will only consider this after they already have taken a healthy deep breath of tirizene or other fun poisons.

My point is that, logically, something HAD to be done about botanies offensive power - but WITHOUT "accidentally" further nerfing the already very limited support abilities. Personally, I would have nerfed the potassium contents in bananas and removed nitroglycerin from botany completely. If one would want to keep seperated chems removed you could still just make gasous decomposition more accessable, focusing the offensive meta to the "managable threat" that is gas (keep in mind, without seperated chems the "smoke" chemical becomes unusable within botany). Though I'd say a "compensation buff" within the offensive department is still not ideal for botany.

Here's what I would do to "fix" botany:
-> Bring back speedboost joints (drugs are great for distracting botanists from griefing)
-> Remove Killer Tomatoes or at least make them attack Podpeople too, it's just too strong
-> Keep seperated chems, remove nitroglycerin, nerf potassium contents in bananas
-> Remove being able to inject chems into plants so that they don't just manually work around the bomb nerf
-> Optionally add another support function (creating metals, perhaps) that wouldn't be much work

I know I am of course biased towards this, as a botany player myself, but I hope it gets recognized that I at least TRY to be objective towards this topic and that I seek to have a respectful argument about this rather than just screeching "Oranges man bad!" as I saw some doing.

**Comment by Shadowflame909** [comment]
Oranges man bad

**Comment by ExcessiveUseOfCobblestone** [comment]
why can't botany just be growing le epic plants instead of being protagonists?

Also they can make metal already and probably gold.

**Comment by AnActualDog** [comment]
>Botany
>Protagonist

I have yet to play a role that feels more like the underdog antihero / comedic relief villian than Botany.

NOW WATCH AND LEARN, HERE'S THE DEAL, HE'LL SLIP AND SLIDE ON THIS BANANA PEEL!

**Comment by ExcessiveUseOfCobblestone** [comment]
I mean yeah throwing tomatoes is pretty lultier but when you get past that and see that they're pretty much a better medical and they can delete people with super cute looking plants it's hard to consider them the underdog byond they're "suppose" to be since they're fluffed as growing crops for meals on a research station.

No other department has as much varying utility as botany does except RND before techwebs imo.

**Comment by AnActualDog** [comment]
I guess I should better explain why I feel this way. The reputation and "social role" botanists have on the station is very different from their potential. Ahem.

Looking at what they are capable of, botany is (or used to be) a constantly growing armory that should be feared by all and on a tight leash by security, the AI should keep an eye on what they are growing every now and then, improved Ambrosia should be a priority and tight cooperation with medbay is key.

In reality, Botany is filled with new players and memers. It is rare to see a competent one. Its even more rare to see them get anything done on Bagil. Their constant rivalry with the chemists each round has to be initiated by them since they practically need a chemical dispenser to be efficient at their job. Barely any Botanist knows how to build one themselves. So almost every shift there is a Botanist trying to steal the dispenser. Since they also practically HAVE to hack their vendors they always rush to tool storage at roundstart to get insuls and tools. So it is no surprise that their place on the social ladder of space is next to the assistant and the clown. More often than not they just want to get high on 1 potency weed. If they explore their capabilities beyond that they find many ways to prank and sometimes grief - and few to support others. Many master their own special breed of Ambrosia but beyond that it's chaos, especially because of the strange seeds. Which is why most botanists are very down with the clown and the heads of staff are not down at all with them.

Funfact / sidenote: Botanist is one of the few jobs where ligger coworkers have the highest chance of being bros. It lets their autism bloom and its actually a job you can do as a team. But since many coworkers are new you still better don't rely on them knowing what they are doing. Observe their competence and if you observe any, share a joint with them.

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't typically play bagil but I can see how botanist might be viewed as a newbie job (might even be supported in the wiki).

**Pull request merged**
