### PR TITLE
Adds a new prefab circuit

### PR DESCRIPTION
**Pull request by Carbonhell**
It's still WIP, most of the code should be ready but there are a few issues that i still need to iron out, mainly activators behaving erratically, and canUseTopic returning that i'm too far, apparently randomly, also the prefab Topic proc, specifically the input() call, does not show all components even though in VV the list had them.
Do not merge yet

:cl:
add: A new prefab circuit has been added. You can convert an assembly into a single circuit. To handle the new circuit pins, you need to prioritize, through the new wirer function, the pins you want to show up in the prefab circuit UI.
/:cl:

[why]: It's a very good mechanic to compress several circuits into one and making assemblies look cleaner

### CODE REVIEW

**Comment by Carbonhell** [comment]
Config change was an error, you can remove the config update label

**Comment by arsserpentarium** [comment]
could help very much.some subsystems are used very often and better to use them as modules.

**Comment by Xhuis** [comment]
💙

**Comment by Carbonhell** [comment]
@ACCount12 you did the initial JSON code right?Could you give me a hand,especially with safety related stuff?Don't want shit to break horribly

**Comment by ACCount12** [comment]
`validate_electronic_assembly` is where most of the safety checks happen. If you want to do any checks that are supposed to reject assembly on load, put them there.

**Comment by arsserpentarium** [comment]
@optimumtact
Why are you putting stale label 2 hours after last commit?

**Comment by duncathan** [comment]
stale

**Comment by optimumtact** [comment]
I'm psychic

**Comment by Carbonhell** [comment]
Wtf it isnt stale,i am testing it

**Pull request closed without merging**
