### PR TITLE
pdas now use their cells more

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

So one aspect of PDAs that I quite liked previously was managing and upgrading your power.
This was lost when all cell parts got removed, mostly, and now I'd like to re-add it.
PDAs and Tablets now use more power each second it's on
Programs being active/idle now take charge too.
And all this now takes ``seconds_per_tick`` into account.

Screenshots of APC use before and after having 6 programs open at once
image
image

PDA default power cells have a max charge of 1000, each cell use is around ``1.00970340315`` power, which is ``1.01013789399`` w/ 2 programs in idle and 1 active program (which is what PDAs are capable of). This means it takes about 990 ticks to fully drain your power, or about 50 minutes, at max use.

This is completely blasted away the moment you put anything beyond a t1 cell inside of it, which is unfortunate but what can you do about tiered parts being so poor.

The problem of no public PDA chargers are alleviated by https://github.com/tgstation/tgstation/pull/78600

### Update

The PDA flashlight being on now also drains the battery 25% times faster. PDA running out of charge now also turns the flashlight off.

## Why It's Good For The Game

You may or may not have to actually charge your PDA once in a round now, maybe. I liked this part of tablets and would like to see it brought back, managing your power to use your apps is important to ensure you're not just using all apps 24/7

Because this also adds the functionality to add/remove power cells again, it opens up to some minor little pranks/messing with people that isn't completely destroying their tools, as well as some minor upgradeability.

## Changelog

:cl:
balance: You can now remove and replace power cells from PDAs (with screwdriver).
balance: PDAs now drain their power cells harder, and also take into account active programs & their flashlight being on.
balance: PDAs running out of charge now turn their flashlights off.
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
Are PDAs chargeable in weapons chargers? I'm pretty sure tablets were, and we could add in like dorms chargers that can allow for ambiguous purposes.

**Comment by JohnFulpWillard** [comment]
> Are PDAs chargeable in weapons chargers? I'm pretty sure tablets were, and we could add in like dorms chargers that can allow for ambiguous purposes.

Yeah they are, and I wanted to add a charger in some public location for a long time now but never really wanted to do the map edit myself. I'll get around to it when I'm next able to.

**Comment by BurgerLUA** [comment]
> Are PDAs chargeable in weapons chargers? I'm pretty sure tablets were, and we could add in like dorms chargers that can allow for ambiguous purposes.
> 
> Also, borg PDAs pull from the borg's cell, right?

You can recharge a PDA in a microwave.

**Comment by lessthnthree** [comment]
> > Are PDAs chargeable in weapons chargers? I'm pretty sure tablets were, and we could add in like dorms chargers that can allow for ambiguous purposes.
> > Also, borg PDAs pull from the borg's cell, right?
> 
> You can recharge a PDA in a microwave.

This is like 90% complete, I just need to finish spritework.

**Comment by GPeckman** [comment]
Is there a way to charge PDAs _without_ a weapons charger? Most jobs don't really have easy access to one of those without hacking into a sec checkpoint (which is obviously not ideal).

**Comment by Loafin34** [comment]
fulp, did you make it so plasma/welding-fuel sabotaged cells explode inside a PDA?

**Comment by JohnFulpWillard** [comment]
I personally didnt add that but I assume it does something

**Comment by SkeletalElite** [comment]
pointless tedium. Needing to go click a recharger for 20 seconds every x minutes just to use your basic job tools doesn't add value to the gameplay loop.

**Comment by optimumtact** [comment]
> doesn't add value to the gameplay. 

Apart from the obvious being that it forces you to go out of closed department areas and mingle in public which is where most of the value of a multiplayer game is to be found (in other people), much like other similar issues like hunger and mood.

Why bother building a strawman if it's so easy to knock over.

**Comment by SkeletalElite** [comment]
> Apart from the obvious being that it forces you to go out of closed department areas

I find it much more likely that people will just move the one thats in the sec post somewhere where the whole department can access it without needing to leave, but we'll just have to see I guess

**Comment by moocowswag** [comment]
> I personally didnt add that but I assume it does something

I think the cells automatically detonate and qdel themselves whenever something tries to update their charge value (this is why old yellow slime cells insta detonated on injection) so im assuming you didnt have to do anything.

**Comment by YehnBeep** [comment]
> Apart from the obvious being that it forces you to go out of closed department areas and mingle in public which is where most of the value of a multiplayer game is to be found (in other people), much like other similar issues like hunger and mood.
> 
> Why bother building a strawman if it's so easy to knock over.

Speaking from experience on servers with long-running rounds, most people will just ignore their PDA going dead. Hunger and mood have penalties that are relevant moment-to-moment, while - even on TG's main servers - PDAs are things some people discard (or hide away if they don't want to be impersonated) even without power management worries.

That's not to say I'm against this, though. Higher capacity cells in PDAs is a pretty massive improvement for those that do use them.

**Comment by RedBaronFlyer** [comment]
I'd be okay with this if we had public places to charge PDAs. Arrivals, Departures, and the Bar/Kitchen seem like decent places

I don't even know where on earth I'd go to recharge my PDA anyways (besides the microwave of course)

**Review by ninjanomnom — APPROVED** [review]

**Comment by Mothblocks** [comment]
> > doesn't add value to the gameplay.
> 
> Apart from the obvious being that it forces you to go out of closed department areas and mingle in public which is where most of the value of a multiplayer game is to be found (in other people), much like other similar issues like hunger and mood.
> 
> Why bother building a strawman if it's so easy to knock over.

There are a thousand explicit and implicit mechanics that do this that aren't directly related to a tool that is primarily useful for socializing with people or otherwise interacting with the greater station

**Comment by isotope436** [comment]
theres a bug that causes the pdas to enter a state where their cells drain 10% each tick no matter the cell and it looks to be either entirely random or based on if you turn on the flashlight well a app is running either way it perma fucks the pda and makes them unuseable this pr also didnt add anything to gameplay to begin with and changes almost nothing in terms of functionality except making pdas more annoying and robotics have 2 minutes of extra stuff to do (giving new cells to people). Iv also heard a few people mention the headcoder didnt even see why this pr was needed so someone please either fix the bug or unmerge this so we can use pda's again because for the 5 jobs that actually see use in it (ESPECIALLY NUKIES) this pr is causing issues.

**Comment by LukasBeedellCodestuff** [comment]
I think I send like one pda message every 10 rounds. I don't really interact with the pda otherwise, it's going to be sad when I want to msg someone and I can't because most people will just ignore their pda charging as they're not going to break into places to charge it

**Comment by RedBaronFlyer** [comment]
> I think I send like one pda message every 10 rounds. I don't really interact with the pda otherwise, it's going to be sad when I want to msg someone and I can't because most people will just ignore their pda charging as they're not going to break into places to charge it

It's another example of forced crew interaction using the stick vs. using the carrot. It was the same with the mining PR to force miners to go through cargo to get their gear.

Realistically people are going to wordlessly do 99% of the work at the autolathe that got moved into the lobby (because the ORM would be unwrenched and pushed aside if cargo didn't) and bugging robotics because there aren't any public battery chargers IIRC. Which I guess technically counts as a victory. Most likely, it's going to be how you said where people are just gonna let their PDAs brick, which is what I already see on Manuel since the PDA being out of power gives no indication that the power is out of power, just that it's not working, leading to more confusion.

**Pull request merged**
