### PR TITLE
Makes Ratvar finding you as a target more spooky

### PR DESCRIPTION
**Pull request by ChangelingRain**
Ztow... Thoom... Thoom... Thoom...

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@Xhuis

**Comment by Xhuis** [comment]
I'll incorporate this little snippet into the PR that I'm about to make, just give me a sec.

**Comment by Xhuis** [comment]
#18085

**Comment by ChangelingRain** [comment]
I mean, you didn't need to? It doesn't conflict.

**Comment by KorPhaeron** [comment]
That's also true

**Comment by Xhuis** [comment]
I think it does due to changes in `clock_ratvar.dm`. If you really want this open though you can do so and I'll fix conflicts afterwards.

**Comment by ChangelingRain** [comment]
Alright, I'm pretty sure it won't conflict anyway because we aren't touching nearby lines

**Comment by Xhuis** [comment]
Good enough for me

**Pull request merged**
