### PR TITLE
Removes floor deconstruction hints and other hint-tweaks.

### PR DESCRIPTION
**Pull request by kingofkosmos**
## About The Pull Request
Removes deconstruction hints from floors. 
Changes deconstruction hints from span class `notice` to `info`.
Changes window deconstruction hints to a more in-gamey style: "...and could be deconstructed by **wrenching**." --> "There's only a couple of **bolts** keeping it intact."
Also an unrelated small tweak: Instances of `to_chat(user, text("` changed to `to_chat(user, "` in a few places. Caught my eye and seemed to be redundant.

## Why It's Good For The Game
Removing floor hints makes it much clearer to spam shift+click while trying to figure out the name of the jackity-saxing greytider, so instead of seeing this:
Capture

User would just see this:
Capture2

(I admit this is a hacky fix because I couldn't figure out how to stack a message that consists of more than one line, if there's a way to do that, let me know.)

The other things add consistency to span classes and adds immersion to window deconstruction hints.

## Changelog
:cl:
del: Removed floor deconstruction hints.
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
If you want it to stack you need to send the whole examine contents in single to_chat

**Comment by kingofkosmos** [comment]
Has that already been done with some messages where I could look for example? I haven't noticed any in-game.

**Comment by ExcessiveUseOfCobblestone** [comment]
instead of calling ..() directly you copypasta it in.

**Comment by Barhandar** [comment]
So THAT is what the "small crack" is about, not damage, but "hurr durr you can crowbar it".

**Comment by MrPerson** [comment]
Examine text is OOC. It's better to be clear that something can be crowbarred instead of vaguely implying that there's a gap. Bad descriptions like that are why old adventure games are so shitty to play.

**Comment by AnturK** [comment]
Doing it for turfs would be a good start.
Just turn examine into thin wrapper.

```
/turf/proc/get_examine_text(user,whatever)
 return <current examine but only returns the string>

/turf/examine(user)
 to_chat(user,get_examine_text(user))
```

**Comment by Tlaltecuhtli** [comment]
i always tought that message was an ass joke i think "tooltip" things should have a pref for disabling them

**Comment by Partheo** [comment]
I always thought the "**small crack**" message was comical and unhelpful anyway, so I like this change.

**Comment by Cyprex** [comment]
>Changes window deconstruction hints to a more in-gamey style: "...and could be deconstructed by wrenching." --> "There's only a couple of bolts keeping it intact."

I disagree, bolts are a lot less clear, especially to non-native english speakers.

**Comment by kingofkosmos** [comment]
> 
> 
> Doing it for turfs would be a good start.
> Just turn examine into thin wrapper.
> 
> ```
> /turf/proc/get_examine_text(user,whatever)
>  return <current examine but only returns the string>
> 
> /turf/examine(user)
>  to_chat(user,get_examine_text(user))
> ```

I'll look into this solution and update if I manage to do it this way. And if I do manage, I'll change the crack-message into something better, (I originally made that message, sorry).

**Comment by kingofkosmos** [comment]
> 
> 
> > Changes window deconstruction hints to a more in-gamey style: "...and could be deconstructed by wrenching." --> "There's only a couple of bolts keeping it intact."
> 
> I disagree, bolts are a lot less clear, especially to non-native english speakers.

If you have a better suggestion for the word "bolt" as to "use wrench", now's a good time to suggest  (but I'm guessing "nut" is out of the question). I'd preferably have them as hints, a little more vague than "use wrench to deconstruct".

**Comment by DaxDupont** [comment]
Please don't nut on the glass

**Comment by kingofkosmos** [comment]
I can't get the examine-wrapping to work. Could this be a temporary fix until I, or someone else, figures out how to wrap them properly?

**Comment by ExcessiveUseOfCobblestone** [comment]
can you explain "can't get it to work"?

**Comment by kingofkosmos** [comment]
I actually might have figured it out while I was trying to explain why it didn't work...

**Comment by ExcessiveUseOfCobblestone** [comment]
rubber duckby here

**Comment by kingofkosmos** [comment]
Couldn't figure it out. Perhaps it's a much easier task for someone else to make this work.

**Pull request closed without merging**
