### PR TITLE
Fixes urinals.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/tgstation/issues/20316.

don't look at the date pls

### CODE REVIEW

**Comment by Megamaw** [comment]
test your bugfixes you dunce

**Comment by bgobandit** [comment]
is there an error or something

**Comment by CrAzYPiLoT-SS13** [comment]
No, you literally delete the object as soon as it's fished out (and not
when delete it in a good way, rather null it out, eek)

**Comment by bgobandit** [comment]
that isn't the object, it's the variable on the urinal

**Comment by optimumtact** [comment]
Get a load of those two

**Pull request merged**
