### PR TITLE
AIs can now have their laws directly adjusted

### PR DESCRIPTION
**Pull request by Anonmare**
Also fixes the spark system while I'm here

## About The Pull Request
You can now slap AIs with your AI Modules to directly upload Laws, now you don't have to dither about with using AI Uploads when it's literally right in front of you.

Also fixed the spark system since it was using old procs.

## Why It's Good For The Game
If you can get in front of the AI, you deserve to be able to upload your laws to it. 

## Changelog
:cl:
add: AIs can now have their laws manually adjusted
fix: AIs now spark when hit, like they always should've done.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
IMO, a better way to do this would be to make carded AIs adopt the lawsets of any AI cores that they're transferred into.

That way, the process to directly modify an AI's laws would be to card the AI, screwdriver its core, pry out the reinforced glass, apply the law boards you want to apply, put the reinforced glass back in, screwdriver the core closed again, and put the AI back into its core... instead of just "teleport into the AI sat as an op and slap the AI once with a hacked law board, giving it no time to scream over even binary chat (which intellicarding it would let it do) before being subverted".

**Comment by itseasytosee** [comment]
My personal suggestion is directly being able to upload to carded AIs as you can see all their laws and kill them anyway.

**Comment by Shadowflame909** [comment]
I'd be fine wih any of these.

Like a wirecutter and a multitool. Alternatives!

**Review by spookydonut — CHANGES_REQUESTED** [review]
What stops an antag ai from logging out briefly to stop someone changing their laws

**Comment by Anonmare** [comment]
@ATH1909 That's really more of a balance problem with the launchpad and that method already exists, this is pure QoL.

@itseasytosee Already exists, the intellicarded AI needs its wireless enabled to recieve law uploads.

@spookydonut Nothing, just like there's nothing stopping you from logging out as a borg to prevent the exact same subversion. If you would please review https://github.com/tgstation/tgstation/blob/8ac03d0d80cf5837086075125b1ec79594d406c0/code/modules/mob/living/silicon/robot/robot_defense.dm#L146 - you'll find that this PR is consistent with the pre-existing code in place, with the obvious exceptions removed.

**Comment by ATH1909** [comment]
> @ATH1909 That's really more of a balance problem with the launchpad and that method already exists, this is pure QoL.

Yeah, but before when an op ganked you as an AI, you didn't suddenly join their team. This is a pretty big op buff (imagine the AI just bolting the captain in a room until the ops get there).

**Comment by spookydonut** [comment]
Fair enough.

**Comment by Anonmare** [comment]
@ATH1909 To be fair, OPs are probably in a good position to subvert an AI via the traditional tech storage theft way at a much lower TC cost. Most don't because they usually find it's cheaper to just kill the AI outright with one of the bombs they start with. Do note, however, that OPs are giving a not inconsequential number of TCs to pull the bluespace hack off so I suppose it will balance out by forcing them to give up on other utilities/weapons.

I think the issue lies with antagonists being able to teleport in front of AIs at all. I don't think most OPs will do this though because of how niche the launchapd would be for an OP. 
Besides, If you're really determined enough, you could replace the AI by buying a syndie MMI, slotting one of your OPs brains in it, bluespacing in front of the AI, card it, decon the montior and slot the MMI in and reconstruct it to make a syndie-loyal AI.

I do get your point, though I don't think it'll be the dominant strategy

**Pull request merged**
