### PR TITLE
Adds AI Software Upgrades to the Uplink (For Research Director) (Now featuring Roboticist!)

### PR DESCRIPTION
**Pull request by Eronymun**
## About The Pull Request
ohyeahembed

Does what it says on the tin. Adds the AI Combat Software Upgrades item to the uplink for purchase by Roboticist and Research Director. It cost ~10~ 16 TC and as is tradition with items that involve other players it can be refunded for it's full price.

Let me know if you want the cost adjusted. In my eyes 16 TC is a good price because you'll likely also have to buy a hacked AI module, and you have to physically travel to the AI core. There's also a chance through some law shenanigans that the AI turns on you, in which case this could become a detriment.
## Why It's Good For The Game

This item has been sitting in a dusty old ash lizard ruin for years and practically never sees use due to how difficult it is to reach, even more so for someone who happens to be a traitor and also happens to have the means to do something traitorous with it. At best I've seen it used as a haha have some upgrades for no reason sorta deal, and it's so rare I wouldn't be surprised if most players didn't even know it exist.

By putting it in the hands of the roboticist & research Director, we allow for subverted AI's with malf powers to become somewhat more common. Being that SS13 is a game about social deception, giving the AI more than one way to reasonably create hacked APCs will lead players to question whether the RD is the one behind the illicit activities, or if the AI is truly just malfunctioning.

This also opens up more gimmicks between the AI and RD/roboticist. Being that the RD and roboticist are supposed to be the bridge between humans and Silicons, I think this item fits well within their established roles. Gimmicks that involve more than one player conspiring is also good, since social interaction is part of what makes this game fun.
## Changelog

:cl:
add: Adds Combat Software Upgrades to the Research Director's Uplink (16TC)
/:cl:

### CODE REVIEW

**Comment by Eronymun** [comment]
Help I forgot how to add tags again!

**Comment by Jacquerel** [comment]
> Help I forgot how to add tags again!

```
:cl:
add: Added new mechanics or gameplay changes
qol: made something easier to use
/:cl:
```

replace with

```
:cl:
add: Adds Combat Software Upgrades to the Research Director's Uplink (10TC)
/:cl:
```

**Comment by Eronymun** [comment]
> > Help I forgot how to add tags again!
> 
> ```
> :cl:
> add: Added new mechanics or gameplay changes
> qol: made something easier to use
> /:cl:
> ```
> 
> replace with
> 
> ```
> :cl:
> add: Adds Combat Software Upgrades to the Research Director's Uplink (10TC)
> /:cl:
> ```

Thanks, also thank you Green-Time!

**Comment by Vect0r2** [comment]
This should be 20 TC. The ability to get a malf AI is something that is extremely powerful and expecting a little creativity to get one on your side should be required.

**Comment by DaydreamIQ** [comment]
Isn't there literally a final objective that gives the AI full malf? Having something like this kind of undermines its existence since why bother getting all the way to that objective when you can just subvert an AI while also using this

**Comment by Sadboysuss** [comment]
> Isn't there literally a final objective that gives the AI full malf? Having something like this kind of undermines its existence since why bother getting all the way to that objective when you can just subvert an AI while also using this

while it does make the final objective less unique - the final objective gives the AI a law 0 to follow the subverter's orders, while this combat upgrade disk could easily blow up in your face if you don't manage the AI's laws

**Comment by Sadboysuss** [comment]
but maybe give it a rep requirement

**Comment by Eronymun** [comment]
> This should be 20 TC. The ability to get a malf AI is something that is extremely powerful and expecting a little creativity to get one on your side should be required.

Yeah upon thinking about it further I probably want to raise it a bit more, though I want to leave enough room for at least 1 hacked AI module, I think.

> Isn't there literally a final objective that gives the AI full malf? Having something like this kind of undermines its existence since why bother getting all the way to that objective when you can just subvert an AI while also using this

I actually had zero clue about this because I've quite literally never seen it, and I've played a lot since final objectives have been merged. Uhhh I mean afaik these don't let you go delta where as the final objective might let you delta? Otherwise I think this is still good to go in the game, in general I'd like to see AI players more empowered to mess around with fun toys while conspiring with traitors.

**Comment by Y0SH1M4S73R** [comment]
> Uhhh I mean afaik these don't let you go delta where as the final objective might let you delta?

Combat upgraded AIs can delta, but are only allowed to if their laws permit it.

**Comment by Eronymun** [comment]
Changed cost from 10 to 16, enough for one 4 TC hacked AI module to go with it.

**Comment by DaydreamIQ** [comment]
> while it does make the final objective less unique - the final objective gives the AI a law 0 to follow the subverter's orders, while this combat upgrade disk could easily blow up in your face if you don't manage the AI's laws

So there's a little bit of confusion regarding that because I dont think its written anywhere clearly that the final objective malf has to follow its traitors orders. It might be hidden away somewhere but I can only find a specific thread on the topic that got closed in favour of the major silipol rewrite...so if that's true this ends up just being better than that because you get all the bells and whistles of a malf AI without it backstabbing you

**Comment by Jacquerel** [comment]
> > while it does make the final objective less unique - the final objective gives the AI a law 0 to follow the subverter's orders, while this combat upgrade disk could easily blow up in your face if you don't manage the AI's laws
> 
> So there's a little bit of confusion regarding that because I dont think its written anywhere clearly that the final objective malf has to follow its traitors orders. It might be hidden away somewhere but I can only find a specific thread on the topic that got closed in favour of the major silipol rewrite...so if that's true this ends up just being better than that because you get all the bells and whistles of a malf AI without it backstabbing you

The Final Objective gives the AI a protect objective for the traitor who applied it, notable because "objectives" cannot be removed by changing the AI's laws.

**Comment by zxaber** [comment]
>I actually had zero clue about this because I've quite literally never seen it, and I've played a lot since final objectives have been merged.

The Infect AI final objective was added later (it's still been around for a while), but you'd only see it when;
- A traitor randomly rolls it
- Said traitor happens to be working towards a final objective
- Said traitor doesn't get caught/killed/stonewalled during their crime spree

Truth be told, I haven't personally seen *any* final objective in some time now.

Anyway, this is limited to a singular job slot. Between the above randomness and this item's narrow focus, we probably have room for the two to coexist.

**Comment by EnterTheJake** [comment]
I think all of sci should be getting this, we don't want more incentives for people to antagroll as a head of staff or worse lowpop acting cap, they are already stacked with advantages as it is.

**Comment by Jacquerel** [comment]
I think this _does_ step on the toes of the final objective a bit, but to be honest that might just be a sign that the final objective is not all that exciting? I don't know, maybe we need a _second_ maintainer opinion on this.
Personally I wouldn't mind it being available to RD/Roboticist or even RD/Roboticist/Scientist also as suggested above.

**Comment by Eronymun** [comment]
> I think this _does_ step on the toes of the final objective a bit, but to be honest that might just be a sign that the final objective is not all that exciting?. That said this also I think usually incentivises building a secondary maintenance AI which I think is less exciting than subverting the existing one. I don't know, maybe we need a _second_ maintainer opinion on this
> 
> Personally I wouldn't mind it being available to RD/Roboticist or even RD/Roboticist/Scientist also as suggested above.

That's fair. In all honesty when I first heard it could be a final tot objective my very first thought was "i would be so disappointed I didn't get something cooler like battle cruiser". 

I limited it to RD mostly for flavor reasons, but I do think it helps make it not so common that you'll be seeing a nuke go off two rounds in a row if one sci member is good enough to feed their AI enough APCs. However, the opportunity cost of 16 TC is huge, so it probably won't be all that common anyway. I'll also give roboticist access to it since they are also in the trade of messing with AIs.

**Comment by Eronymun** [comment]
As for building AIs in maints, if they can get someone to go into a posi brain (probably pretty easy later in the game) then they are going to be behind on round time for building up their hacked APCs to spend on malf powers. IIRC if delta is the goal of the traitor then the AI will at least give out a pinpointer signal. 

Secondary AIs also don't sync to all the round start borgs, so there is some lost value there.

**Comment by Watermelon914** [comment]
I don't really agree with giving this to research directors, especially considering that we have a final objective that essentially makes the AI malfunctioning.

The AI basically gains full malfunctioning capabilities with no downside. It's okay-ish as a miner item because there isn't a guarantee that it'll exist in every round and it's relatively hard to obtain.

**Comment by Sadboysuss** [comment]
Aren't you supposed to slap DNM on it first?

**Pull request closed without merging**
