### PR TITLE
Simple mob alerts

### LINKED ISSUE #37820: Simplemobs recieve no notice of environmental damage.
[Round ID]: # Any round

[Testmerges]: # None responsible

[Reproduction]: # When playing as a minebot during a plasmaflood I noticed that I was taking damage from the pressure/high temperature without any visual notification.
Normally the player should have a small icon in the top right corner that either shows a thermometer/pressure warning so they know what is wrong and when they are safe again.

Since I cannot tell when I start or end taking damage I have to run far away to an area I know is safe or risk dying arbitrarily.

Note: I only confirmed this for minebots, but I believe the same bug occured in a previous round as a space carp, so I think it might be all simplemobs.

### LINKED ISSUE #48280: Some Simplemobs Don't See Indicators for Local Conditions That Hurt Them
I have a specific example here: if you're a sentient bee, you're vulnerable to damage from high temperatures, but your HUD won't indicate any sort of temperature shift whatsoever. This can leave you guessing as to why you're taking damage from seemingly nothing.

Since simplemobs are vulnerable or immune to different things, like a need for oxygen, cold, heat, pressure, fire etc., and we've recently added a generic push-pull button, it'd be great to see such additions here. I imagine that this is an oversight, not an actual bug, but still. Simple UI elements - like the existing generic ones we have - would be greatly useful in this scenario. Ideally we'd have variant HUD elements for things that we could detect, but are not needed/effective - for example, something immune to pressure damage being able to see the pressure indicator, but in a different colour/with a different border indicating it's for informational purposes, and not indicating a threat, but that's by the by to the issue here.

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

Simple mobs will now receive two new alerts about being in too hot/cold envinronment and about being in an unbreathable area. They will receive these alerts only if they are being damaged by them, as otherwise player playing as them could have no idea what is killing him.

**Example image:**

Alerts

Fixes #48280
Fixes #37820

## Why It's Good For The Game

Better experience playing as a simple mob.

## Changelog
:cl: Arkatos
add: Simple mobs will now receive an alert about being in too hot/cold environment.
add: Simple mobs will now receive an alert about choking to death.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
only took 7 years

**Comment by AnonymousNow** [comment]
What about pressure? Is that a factor?

**Comment by Arkatos1** [comment]
@AnonymousNow I have checked, and base simple mob is immune to pressure, so that should not be a problem.

**Comment by actioninja** [comment]
That simple mobs have all this fragmented bullshit should probably be fixed eventually but not really in scope of this pr imo

**Comment by optimumtact** [comment]
this really PISSES ME OFF

**Pull request merged**
