### PR TITLE
Changes the fucking smg sound

### PR DESCRIPTION
**Pull request by Buggy123**
I have no idea who thought it was a good idea to use-

*BEEP BEEP BEEP* WAKE UP

the one sound which almost everyone-

*BEEP BEEP BEEP* WAKE UP!

has been pavlovian-conditioned to associate with-

*BEEP BEEP BEEP* BITCH WAKE THE FUCK UP!

waking up before the sun rises, and then suffering for 8 hours, 5 days a week-

# *BEEP BEEP BEEP*

BUT ITS A TERRIBLE FUCKING IDEA!

This is the sound it's changed to: https://freesound.org/people/KlawyKogut/sounds/154934/

If you have a better idea I'm happy to accept it. Heres a abbreviated list of what I would consider a acceptable alternative to the current sound, to give you a feel for things:
1: a jumpscare scream
2: nails on a chalkboard
3: the bwoink noise
4: the Kevins ERP log
5: MAGIC MISSILE!
6: the entirety of the Bee movies audio track

### CODE REVIEW

**Comment by QualityVan** [comment]
according to all known laws of aviation, there is no way an smg should be able to fly

**Comment by Buggy123** [comment]
image
I see we have 4 sadomasochists here.

**Comment by ShizCalev** [comment]
smg_empty_alarm.ogg
>a clicking sound

**Comment by Buggy123** [comment]
if i change the sound name i have to do code edits as well, kinda pointless for such a small change.

**Comment by ShizCalev** [comment]
also that clip has tons of static in it

**Comment by Buggy123** [comment]
It sounds perfectly clear on my end.

**Comment by ShizCalev** [comment]
Just recorded these;
https://www.dropbox.com/sh/ic1zl56yh4zrv4p/AABTgh-Xgd1ypObWXbZDbDJka

**Comment by ShizCalev** [comment]
This will double up with the current empty firing sound.

nays have the vote.

**Comment by Buggy123** [comment]
masochists, all of you.

**Pull request closed without merging**
