### PR TITLE
Adds robotic voiceboxes as contraband in the Robotech Deluxe

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

The title explains most of it, really.

## Why It's Good For The Game

It's a bit sad that in order to let your fully augged patient speak like a robot, you have to wait for a meat-eor shower or use other esoteric means to give them the SPAN_ROBOT span. Now you can hack your vendor and make your patient an even better imitation of an android and/or add an extra element to your cardborg costume.

## Changelog
:cl: ATHATH
add: Added two robotic voiceboxes to the contraband section of the Robotech Deluxe.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
There's a comment in _vending.dmm that says that if I modify a vending machine's contents, I should also update its resupply canister charges in vending_items.dmm, but there's a comment in vending_items.dmm that says "Built automatically from the corresponding vending machine.", and it looks like the process has been automated or something now. Am I missing something here?

**Comment by SpaceManiac** [comment]
the "please update the resupply canister also" comment is outdated

**Comment by actioninja** [comment]
Does the robotic voice box have any effects besides just changing the way the text looks?

**Comment by optimumtact** [comment]
power creep

**Comment by shellspeed1** [comment]
> 
> 
> Does the robotic voice box have any effects besides just changing the way the text looks?

It might let the user speak the binary language. Not for sure on that.

**Comment by Dorsisdwarf** [comment]
Should probbably be sure on that because thats a pretty major difference

**Comment by Cyprex** [comment]
Could you remove the outdated comment as well?

**Comment by XDTM** [comment]
It gives the robot text, and allows the user to speak all known languages (some, even if known, are unpronounceable with normal tongues). No binary chat.

**Comment by Krysonism** [comment]
Economy integrate it by increasing the price to like 300 credits. 

We need more items like this but they won't do any good without a real cost.

**Comment by ATH1909** [comment]
I took Krysonism's suggestion and bumped up the price (is it 300 or 350 now? It doesn't really matter, I suppose).

**Comment by coiax** [comment]
> It gives the robot text, and allows the user to speak all known languages (some, even if known, are unpronounceable with normal tongues). No binary chat.

XDTM is right, but I feel I should point out that being able to speak a language is not the same as knowing it. So this doesn't turn you into the curator. (Curators bypass the "can speak" check.)

**Comment by shellspeed1** [comment]
I'm tempted to say add a pair of cybernetic ears for interpreting langauge honestly.

**Comment by dr-bee** [comment]
> 
> 
> I'm tempted to say add a pair of cybernetic ears for interpreting langauge honestly.

It would be worth adding just to give a cybernetic option for organ replacement, we currently dont have cybernetic versions of ears and stomachs. 

Adding this to techwebs at the advanced cybernetic organs node would be appreciated as well. Tongues dont take organ damage but hey, it would fit.

**Comment by ExcessiveUseOfCobblestone** [comment]
So in other words this allows omni-speaking in robot font BUT not omni-understanding?

I'd prefer if it was subtyped for vendor that just changed the font of your language, it doesn't make sense to partially learn a language based on what tongue you have.

**Comment by ATH1909** [comment]
> So in other words this allows omni-speaking in robot font BUT not omni-understanding?
> 
> I'd prefer if it was subtyped for vendor that just changed the font of your language, it doesn't make sense to partially learn a language based on what tongue you have.

The tongue is just CAPABLE of speaking those languages IF you know them. In other words, if there was a language that required you to speak outside of the human voice's normal speech range in order to properly speak it, the robotic tongue would let you do so.

**Comment by ATH1909** [comment]
> > It gives the robot text, and allows the user to speak all known languages (some, even if known, are unpronounceable with normal tongues). No binary chat.
> 
> XDTM is right, but I feel I should point out that being able to speak a language is not the same as knowing it. So this doesn't turn you into the curator. (Curators bypass the "can speak" check.)

I trust Colax here.

**Comment by coiax** [comment]
ATH1909 is right, and if the behaviour differs from that, it's a bug, not a feature. At least, it's not what I (original author/porter of languages) intended, given I made a clear distinction between being able to speak a language, and being able to understand.

**Pull request merged**
