### PR TITLE
fix WRONG half life reference that is INCORRECT

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

erm john black mesa was a scientist not an engineer

## Why It's Good For The Game

canon compliance

## Changelog

:cl:
spellcheck: you now owe that scientist a beer, not an engineer
/:cl:

### CODE REVIEW

**Comment by Exester509** [comment]
I thought this was intentional, since it's engineers who work with the glowing yellow crystal

**Comment by Autisem** [comment]
Gordan doesn't need to hear all this hes a highly trained professional

**Comment by carlarctg** [comment]
HOW IS THIS FAILING TESTS????

**Comment by ZephyrTFA** [comment]
this seems pointless

**Pull request closed without merging**
