### PR TITLE
[WIP]Improved gas miners, gave them a proper interface, and replaced all pre-filled atmos tanks with gas miners.

### PR DESCRIPTION
**Pull request by Buggy123**
Gas miners are machines which produce gas ~~from nothing~~ via bluespace technology using power. Currently, they're only ever seen on Kilostation and Donutstation, and they're used in place of the pre-pressurized atmos mixtanks that are just filled with a huge amount of gas round-start.

They're better than pre-filled mixtanks for several reasons:
- They better fit the demands of the station (gas to replace losses over time)
- They don't result in silly situations like "someone broke one window with a axe and now the entire station's replacement air is permanently gone
- They're a godsend for doing crazy atmos setups where you need tons of gas, and don't force atmos techs to choose between "hmm, should the entire station get to breath or should I make 500,000 moles of tritium"
- When it comes to aggressive uses, they don't make that much of a difference; you can already engulf the entire station in flame or flood the halls with N2O with the pre-filled atmos tanks.

This PR makes them constructable, gives them a proper control interface, lets you control the mixtank gas miners via the atmos supply tank control computers, and replaces all pre-pressurized tanks on all maps in rotation with gas miners.

Gas miners will consume a fair amount of power and must be connected directly to a wire node to function, and require both plasteel and bluespace crystals to complete. This should reduce instances of "lmao I'm going to build a plasma gas miner in the main hall.". Also, they aren't fireproof, and the AI can turn them off.

Note: Work in progress, several elements need to be completed and refined. Guaranteed 94% shitcode free.

UI(wip):

image

:cl: 
add: After several baffling reports of lumberjacks singlehandedly depriving stations of their entire oxygen supply, Nanotrasen has begun installing their latest station models with state-of-the-art bluespace gas miners.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
make it cost $ to run

**Comment by XDTM** [comment]
Feels like the wrong direction to go about acquiring gas, because if this ends up becoming the baseline it will get harder to move away from as people start relying on what is essentially infinite gas from nothing.
Could there be a bluespace gas harvesting station on lavaland from roundstart, instead? That way there would also be a variety of available gases from round to round, depending on lavaland's gas composition.

**Comment by HomocidlePancakes** [comment]
Gas mining station on lavaland sounds great, but it’s way too gimmicky. Atmostechs have their own duties to attend to, not to mention the sheer distance between atmos and LL makes it inconvenient.

Also, what’s wrong with having an “””””infinite””””” amount of base gasses?

**Comment by Buggy123** [comment]
The round-start supply of gas is, for practical purposes, infinite where it really matters. Stations start with about 1,000,000 moles of O2 and Nitrogen and similar amounts of CO2 and Plasma. That's enough to repressurize (with standard gas mine) over 12,000 tiles. Even with areas constantly being drained, with the default atmos setup it'll still take hours for the tanks to completely empty while trying to repressurize the area.

You can, however, take a fire axe, smash the three tank windows, and vent that entire air supply permanently within about 90 seconds of round start. And then the rest of the station realizes with creeping horror that the only practical way to repressurize the station after any breaches is to use the limited supply of canisters on the station, or set up a gas farm on lavaland.
(Meanwhile, that guy with a axe has smashed half of the external windows on the station, depressurizing part/all of arrivals, departures, security, science, dorms, the permabrig...)

This is kinda silly, right? Not really even from a balance perspective or fun perspective or anything, but that a guy with a axe can literally vent the entire primary gas reserve in seconds, with no way to replenish it.

And then along comes tritium production, BZ formation, etc, and you realize that the atmos techs can end up burning the entirety of the station's oxygen supply in less than a hour in the incinerator.

This is a bit more sane because it makes gas production a continuous, interruptable, repairable, and constructable process. It becomes a question of the number of breeches, the setup and configuration of atmos, whether or not someone has sabotaged and deconstructed the gas miners, etc. There's more interesting things that can be done on both sides of the equation and the major behavior like continuous breeches or re-pressurizing areas is pretty much the same.

Certainly, no one right now thinks "Oh no, I need to close up this breech or our limited supply of air will run out soon!".

**Comment by XDTM** [comment]
> Certainly, no one right now thinks "Oh no, I need to close up this breech or our limited supply of air will run out soon!".

Honestly it might be cool if it did happen, instead of taking it as written in stone. Reducing the initial gas supply and only having a constant flow of gas mix which might or might not have the necessary oxygen might be more interesting that the current situation.

> You can, however, take a fire axe, smash the three tank windows, and vent that entire air supply permanently within about 90 seconds of round start. 

I'd make venting the gas supply harder than fireaxing, but the option to do so should stay. It's a more interesting tactic than just throwing bombs around.

> This is a bit more sane because it makes gas production a continuous, interruptable, repairable, and constructable process.

It does, however, turn any "Where can i get this particular gas?/How do i get a LOT of this gas?/How do i move the gas i need here?" into "Can i build a gas miner?", undercutting game complexity. It also makes sabotage pretty much useless, as infinite gas supply is only one machine construction away from being back.

**Comment by Buggy123** [comment]
>I'd make venting the gas supply harder than fireaxing, but the option to do so should stay. It's a more interesting tactic than just throwing bombs around.

This does so, basically. Axe the window, break the miner, and you break the gas supply until someone can build a new one.

>It does, however, turn any "Where can i get this particular gas?/How do i get a LOT of this gas?/How do i move the gas i need here?" into "Can i build a gas miner?", undercutting game complexity. It also makes sabotage pretty much useless, as infinite gas supply is only one machine construction away from being back.

Kind of, I agree and I don't want that, but using a gas miner is still nontrivial. It vents gas directly into the air, so you have to set up a enclosed chamber with some means of collecting the gas.

Personally, I'd be fine with encouraging people to use the ones in the atmos chamber instead of creating more, but I'm not sure how to do that. Rebuilding them after destruction (and making them indestructible is lame) is important. As is the ability for the derelict, etc to create a gas supply from scratch which is literally impossible without some elaborate supermatter shennanigans, a cargo shuttle, a shuttle to lavaland, etc. All of which are also non-constructable.

Maybe a universal z-level limit or something? Every gas miner mining the same thing on a z-level takes from the same supply, so 2 miners just split their output between them?

**Comment by Dawson1917** [comment]
Removing the entire station's gas supply by deconstructing one r-wall or plasma window is too easy but gas miners remove any punishment from mass breaches or wasteful atmos techs using up the oxygen supply. As it stands you will almost never see the roundstart gas tanks run out of air even if half the station gets breached by bombs or meteors. There needs to be more changes so that the station doesn't start off with effectively limitless air, atmos can't burn it all away on their own, and more reason to go down to lavaland to fetch oxygen.

You may also want to make selecting gas type be done during construction so a borg can't switch the oxygen miner to plasma

**Comment by Buggy123** [comment]
> Removing the entire station's gas supply by deconstructing one r-wall or plasma window is too easy but gas miners remove any punishment from mass breaches or wasteful atmos techs using up the oxygen supply. As it stands you will almost never see the roundstart gas tanks run out of air even if half the station gets breached by bombs or meteors. There needs to be more changes so that the station doesn't start off with effectively limitless air, atmos can't burn it all away on their own, and more reason to go down to lavaland to fetch oxygen.

I have had more than one project where I specifically plan for using the entire atmos oxygen tank, and several times or I have used the oxygen tank (still filled) as a burntank since I was going to use it anyway. I have also had to wait for kilostation to be picked and get a long round because another project needs 5x-10x as much oxygen as the tank has. And any time I've made a BZ farm it usually uses the entire N2O supply in short order. And while harvesting oxygen from lavaland is possible (but NOT recommended, I know from experience that air alarm interfaces start to break down and crash games past 50+ scrubbers, and the lag becomes noticeable across the entire server), it is impossible to get N2O from lavaland, and plasma is only rarely present and only at extremely low concentrations.

Other sources technically exist, but are ineffective and hilarious (plumbing>gas reagent>smoke machine anyone? Ever see that used? I haven't.)

Discouraging burning away the entire gas supply is a bad thing because it ignores the fact that several intentional game mechanics require _more gas than the entire station has_.

>You may also want to make selecting gas type be done during construction so a borg can't switch the oxygen miner to plasma

Good point, I thought that doing that would need you to break into the tanks anyway so fixing it would be equal in difficulty to breaking it, but I forgot that AI and borgs can set it remotely. The round-start gas miners are now locked to their gas types.

**Comment by ninjanomnom** [comment]
What the fuck

Do not add more gas miners to normal places, do not make them *constructable*, do not make them *configurable*. This is exactly in the wrong direction towards gameplay where your actions don't matter *because we have infinite gas so who cares?*

We do not need to be catering to "crazy atmos setups", if they want to build it and they need more gas they need to either buy it or harvest it from some other source.

**Comment by MarioWizard119** [comment]
Dude, you can make ghetto gas miners with plumbing. 5u [gas you want here] , 1u potassium, 1u phosphorus, 1u sugar into a chemical tank will make a smoke cloud that generates moles into the tiles the smoke is on. Have that into a 1x1 sealed tile and a way to siphon it and you have your gas miner. You can do this with plasma too using unstable phlogiston, which generates 1000K plasma gas. Just make sure it doesn’t light so you can siphon it without clogging the pipes and you have your plasma source. You can do this with nitrous and carbon too, but it’s a bit slower and needs a bit more complicated setup. You don’t need the machines, the station has a way to make their own.

**Comment by trollbreeder** [comment]
24 hour rule

**Comment by duncathan** [comment]
yeah fuck this
effectively infinite gas at roundstart, like we already have, is lame
literally infinite gas is way lamer

**Pull request closed without merging**
