### PR TITLE
Revert "Adds the saltmine shuttle. (#35369)"

### PR DESCRIPTION
**Pull request by optimumtact**
This reverts commit c7ee29b5b08bdbe94c58605453c25926ee5b3010.
:cl: oranges
del: Removed the saltmine grief shuttle
/:cl:

I changed my mind and do not like it again, we should stop adding shitty gimmick shuttles that don't contain either
A) original content 
B) new sprites that make the shuttle worth having

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by MrDoomBringer** [comment]
@DaxDupont ill sprite something nice for your meme shuttle, kid. what'll it be

**Comment by optimumtact** [comment]
I'm not talking about a single fucking meme item, I'm talking about a properly themed shuttle that looks interesting and visually unique

**Comment by Armhulen** [comment]
@MrDoomBringer i guess you can drop dead on top of all of the dead references in that shuttle

**Comment by MoreRobustThanYou** [comment]
The branch name, though.

**Comment by MrDoomBringer** [comment]
>B) new sprites that make the shuttle worth having

when will the media stop lying to us

**Comment by optimumtact** [comment]
I've expanded the explanation

**Comment by DaxDupont** [comment]
It's locked behind revenants.
Also it's the only place where a fake emag exists, which i added.
No kneejerk revert PRs pls.
@MrDoomBringer Sprite me a statue of a catgirl and a moff with saltshakers

**Comment by DaxDupont** [comment]
Has someone actually ordered it yet?
Also @KorPhaeron look at this disaster

**Comment by DaxDupont** [comment]
I am guessing arm started crying because there's a reference to a man crying in as a description

**Comment by Xhuis** [comment]
It looks the saltmine shuttle has fulfilled its intended purpose

**Comment by DaedalusGame** [comment]
jesus xhuis can you please keep the savagery out of here

**Comment by chesse20** [comment]
downvote keep thus in the game

**Comment by DaedalusGame** [comment]
daxdupont alt detected

**Comment by Armhulen** [comment]
i'm not allowed to unleash my intense feelings of pride in this thread so i'll just quietly leave it at this being a good idea. I'm working on an eerie ghost shuttle with floating candles and chairs to replace the 'kill-a-revenant' requirement

**Comment by DaxDupont** [comment]
You can have both!
It's not like you can only have one shuttle unlock.
Making the shuttle unlock is as simple as adding:

if("revenant" in SSshuttle.shuttle_purchase_requirements_met)
since I already added the revenant adds to it code.

I was actually thinking of making more unique shuttles like a ashdrake lair looking one for killing an ashdrake.

**Comment by MrDoomBringer** [comment]
image
image
alrighty well here ya go. two 24k gold babes (wearing clothes for modesty)

also included: silver and gold edition
image

**Comment by Armhulen** [comment]
"I'm not talking about a single fucking meme item, I'm talking about a properly themed shuttle that looks interesting and visually unique"

**Comment by PKPenguin321** [comment]
😠 delete that post doombringer

**Comment by ExcessiveUseOfCobblestone** [comment]
No pepper mint meme @MrDoomBringer ? for shame!

**Comment by DaxDupont** [comment]
I'll probably rework the shuttle and turn it into a salt museum and remove the requirements to buying it

**Comment by ExcessiveUseOfCobblestone** [comment]
why remove the requirements let people show off their ghost-bustin

**Comment by Armhulen** [comment]
@ExcessiveUseOfCobblestone tell your men to lower their bows. i just said i was adding that!

**Comment by DaxDupont** [comment]
Good point

**Comment by ExcessiveUseOfCobblestone** [comment]
lol!

**Comment by Armhulen** [comment]
the museum sounds like a comfy ass shuttle and i love it don't make it rare! <3

**Comment by AlexTheSysop42** [comment]
> I'm talking about a properly themed shuttle that looks interesting and visually unique

Saltmine shuttle is both

**Comment by DaedalusGame** [comment]
ah yes the visual uniqueness of "it's the default shuttle but sideways and every square is covered with either salt or bullshit"

**Comment by DaxDupont** [comment]
@DaedalusGame actually it's not either or, every open turf has salt on it

**Comment by DaedalusGame** [comment]
actually one turf does not

**Comment by MrDoomBringer** [comment]
image
lmao dont even sweat it im already working on salt walls

**Comment by WJohn** [comment]
this thing is ridiculously hideous why the hell was this actually merged

**Comment by Buggy123** [comment]
IMO you merge it you live with it :-1:

**Comment by arsserpentarium** [comment]
Sorry,but looks like it is doing it's job.
Don't remove. Even if there is no original sprites, it was very well done for it's goal.

Still salt walls will be appreciated.

**Comment by improvedname** [comment]
When i heart saltmine i hoped on a asteroid with salt veins people have to mine

**Comment by BeeSting12** [comment]
in the middle of the salt shuttle should be a huge statue of robustin made of salt and every time you rub salt off he spouts a line from one of his forum posts

**Comment by DaedalusGame** [comment]
can we get a pr to remove the player ref rule just for this

**Comment by vuonojenmustaturska** [comment]
@WJohn "inspired by a lot of salt lately, I have made a shuttle that contains more or less everything that makes people angry. Nothing that actually functions though, well except the clock cult room that's just unending skewers." "Ugly was an requirement."

**Comment by MrDoomBringer** [comment]
goldsilver2

alright the old comment got deleted somehow so heres the statue again. added the orange and frog (corpse) this time
goldsilver2_big

**Comment by MrDoomBringer** [comment]
image
right-o i finished the salt walls. 


i actually didnt, as you can see i didnt bother to do the ones that didnt look important - a metaphor for codersalt!

**Comment by Cyberboss** [comment]
This shuttle is bad and yall should feel bad

**Comment by MrDoomBringer** [comment]
WHAT

**Comment by praisenarsie** [comment]
@MrDoomBringer you can readd it, just get it cooler sprites and make it more fun

**Pull request merged**
