### PR TITLE
[WIP] Adds Tajaran to the game

### PR DESCRIPTION
**Pull request by Iamgoofball**
WIP, needs sprites/porting of the say mod stuff.

i wanted #6666 but rip

### CODE REVIEW

**Comment by quaggaman555555** [comment]
Yay, my little nekos might get to come to spess with us~ Nya~

**Comment by quaggaman555555** [comment]
We need a maid job that only Tajaran can play as~

**Comment by FantasticFwoosh** [comment]
ITS TOO LATE, YOU COULD HAVE STOPPED THIS.

**Comment by piterskiy2** [comment]
this codebase has tajaran sprites

https://github.com/TauCetiStation/TauCetiClassic

**Pull request closed without merging**
