### PR TITLE
Donk Co. Microwave Shuttle

### PR DESCRIPTION
**Pull request by DAKKA-WAAAGH**
## About The Pull Request

Those crazy Donk Co. engineers are at it again. Now the crew aboard Space Station 13 might have the chance to be cooked at the grand temperature of 1413 Kelvin! Exciting.

It comes with a fully upgraded thermomachine and all the pipes you'll ever need! (Just don't bust open the plasma container)

**WARNING: THIS SHUTTLE CAN ONLY BE PURCHASED WITH AN EMAG!!**

## Why It's Good For The Game
More shuttles, more round-end variety! Plus, who doesn't enjoy being cooked alive?

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBEEPBEEPBEEPBEEP

## Changelog
:cl:
add: microwave shuttle
add: thermomachine subtype with t4 parts
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
> Where are the microwaves?

Your inside of it 😉

**Comment by wesoda25** [comment]
> > Where are the microwaves?
> 
> Your inside of it 😉

😨

**Comment by Thunder12345** [comment]
But where are the microwaves. This is clearly an oven.

**Comment by ArcaneMusic** [comment]
Yeah, this is using radiation to cook the objects therein, but there's a major flaw here, high heat air doesn't cook food. So by ss13 logic, this is not actually a microwave.

**Comment by DAKKA-WAAAGH** [comment]
> Yeah, this is using radiation to cook the objects therein, but there's a major flaw here, high heat air doesn't cook food. So by ss13 logic, this is not actually a microwave.

This is a code issue and I am legally obligated to point out that it's not my fault. 😄

**Comment by tralezab** [comment]
> > Yeah, this is using radiation to cook the objects therein, but there's a major flaw here, high heat air doesn't cook food. So by ss13 logic, this is not actually a microwave.
> 
> This is a code issue and I am legally obligated to point out that it's not my fault. 😄

And yet you did not fix that code issue

**Comment by LemonInTheDark** [comment]
> Yeah, this is using radiation to cook the objects therein, but there's a major flaw here, high heat air doesn't cook food. So by ss13 logic, this is not actually a microwave.

listen bro I tried but the chem players got mad at me

**Comment by Sealed101** [comment]
this does look more like an oven; if only we still had particle accelerators... 
also what about #73506

**Comment by DAKKA-WAAAGH** [comment]
> this does look more like an oven; if only we still had particle accelerators... also what about #73506

Oh that? I dunno, but any time I run this it works 100% of the time so I can close it.

**Comment by Zytolg** [comment]
Actually microwaves warm up food by causing the water within the food to vibrate. Since there is a lack of water and no manetron it isn't. What you have done is reinvented the convectional oven. A really large convectional oven. There will be cake and you will be baked.

**Comment by san7890** [comment]
sorry for taking a while to get back to you, but you must add this map to the configuration, see here for more information https://github.com/tgstation/tgstation/blob/master/.github/guides/MAPS_AND_AWAY_MISSIONS.md#configuration

mark ready for review when addressed

**Comment by optimumtact** [comment]
neither you or the maptainers seem incentivised to finish this

**Comment by optimumtact** [comment]
make a new pr when you are

**Pull request closed without merging**
