### PR TITLE
unbans beardbeard

### PR DESCRIPTION
**Pull request by Iamgoofball**
requested by everyone, this is a bugfix
gnrpo8x

### CODE REVIEW

**Comment by tedward1337** [comment]
Y

**Comment by Jordie0608** [comment]
feature freeze

**Comment by Cheridan** [comment]
separation between code and server is absolute

**Comment by tkdrg** [comment]
c-can i meme too

**Comment by Shapsy** [comment]
IT LIVES

**Comment by tkdrg** [comment]
THE SERVER IS MERGING WITH THE CODEBASE

**Comment by tedward1337** [comment]
Y

**Comment by Zilenan91** [comment]
GIANTS ARE REAWAKENING

THE END IS NIGH

**Comment by Iamgoofball** [comment]
d e a d
s e r v e r
s e p a r a t i o n

**Comment by tgstation-server** [comment]
Server seper- what

**Comment by bgobandit** [comment]
chelp

**Comment by Iamgoofball** [comment]
@mloc @god and @devil please provide feedback

**Comment by Zilenan91** [comment]
ALL OF THE TAGS

**Comment by Cheridan** [comment]
@Iamgoofball doesn't compile please update

**Comment by Iamgoofball** [comment]
;;;;;;;;;

**Pull request closed without merging**
