### PR TITLE
Adds a new UI style, Clockwork

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Added a new UI style, Clockwork.
/:cl:

truely, you expected nothing else

### CODE REVIEW

**Comment by kevinz000** [comment]
i want

**Comment by ShadowDeath6** [comment]
as long as it isn't forced on anyone

**Comment by ChangelingRain** [comment]
Fun fact this UI was built off of the operative UI style, but uses its own palette plus a little bit of red, making it the UI style with the least colors used *even if you include retro*

**Comment by Armhulen** [comment]
would be fun if you replaced the armor backgrounds with ratvar's armor but that's not noob friendly i guess?

**Comment by ChangelingRain** [comment]
Yeah I considered that but I'd have had to convert it to the UI style and that'd be, uh, a pain in the ass.

**Comment by Armhulen** [comment]
fair

**Pull request merged**
