### PR TITLE
Removes AFK check from revheads

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I've seen 3-4 revheads in the last week or two end because there was a lagspike, or someones game crashed, and though they come back within 10-30 seconds the round just instantly ends and it is terrible.

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by optimumtact** [comment]
instead of removing it, why wouldn't you increase the tolerance

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
@optimumtact Would have to remove the client check on is_considered_afk and it is used in a couple other places (so you get credit for killing the assistant who has logged out in traitor, for example)

**Comment by Jordie0608** [comment]
Cmon kor you can modify a proc; add an argument for duration and for if to check client.

**Comment by SgtxRootbeer** [comment]
>rev round ends in less than a minute
>Somehow, this is bad
:Thonk:

**Comment by ShizCalev** [comment]
reopens #29322 i guess?

**Comment by ShizCalev** [comment]
Atleast check for is_afk

**Comment by Cyberboss** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Alright I'll redo it

**Pull request closed without merging**
