### PR TITLE
Ends grey tiding, Assistant now requires 50 hours of gameplay as security

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by Cyberboss** [comment]
rude

**Comment by KorPhaeron** [comment]
It would probably actually improve the game if you started out with 5-10 assistant spawns or whatever, and it takes an hour of gameplay as any other job to earn a new assistant spawn

**Comment by MrStonedOne** [comment]
Re-announcing it

**Comment by KorPhaeron** [comment]
Gotta get those (You)s

**Pull request closed without merging**
