### PR TITLE
repaths plasteel tiles to iron

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

what the title says
i wasnt sure if it should be metal or iron i went with iron

## Why It's Good For The Game

its made of iron not plasteel!!

## Changelog
:cl:
spellcheck: repaths plasteel tiles to iron
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
This is the type of thing I thought would never be fixed

**Comment by Tlaltecuhtli** [comment]
the madman

**Comment by Pumpkinoe** [comment]
i will have to relearn my pathing again fikou.... you mapster

**Comment by coiax** [comment]
Do you have a regex or command that you used for the automated repathing that you can post?

**Comment by Fikou** [comment]
> Do you have a regex or command that you used for the automated repathing that you can post?

ctrl f /turf/open/floor/plasteel into /turf/open/floor/iron
theres an updatepaths script for it

**Comment by RaveRadbury** [comment]
The stacks they are made from are `metal`, `iron` is the ore. Consistency kinda dictates they be pathed to `metal`

**Comment by cacogen** [comment]
He fixed that too https://github.com/tgstation/tgstation/pull/56643

**Review by LemonInTheDark — APPROVED** [review]
Code's good, I don't think it's possible to review the map changes. Thoughts @EOBGames?
Did you just run it through a regex program? what was your method @Fikou

**Review by LemonInTheDark — APPROVED** [review]
Been so focused on how to review this I forget to think about wearther I like it or not, but I can say for sure it's good, you didn't miss anything and nothing else got changed, except one doubled up map id in crashedship.dmm. So fuck it, this'll do

**Comment by LemonInTheDark** [comment]
Sort the conflict, and we'll be good

**Pull request merged**
