### PR TITLE
Adds comments to _globals.dm

### PR DESCRIPTION
**Pull request by Cyberboss**
Help understanding

### CODE REVIEW

**Comment by optimumtact** [comment]
adds future lies

**Comment by SpaceManiac** [comment]
most of these are self-explanatory, and explaining something then saying "do not use" with no details about why it shouldn't be used seems pointless to me

**Comment by Cyberboss** [comment]
The do not uses are mainly for preventing people from using the internals.
Except for const (which was created for legacy reasons) and real (which
only master, config and subsystems should be using). Someone was asking in
coderbus how to use them so it's not entirely self explanatory

**Review by SpaceManiac — APPROVED** [review]
Good enough for me

**Pull request merged**
