### PR TITLE
Removes Soul Vessel, Cogscarab, and Anima Fragment Scriptures

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Removed the Soul Vessel, Cogscarab, and Anima Fragment Scriptures.
/:cl:

Don't worry, cogscarabs still spawn when ratvar is summoned.

But yeah, these are just kind of problematic; soul vessels let you get converted borgs and AIs from robotics at low cost, scarabs keep getting used for combat and being effective since they're tiny, and anima fragments are a relatively simple combat mob that cost a pretty large amount and aren't really effective enough to justify it.

Marauders get to stick around a bit, though! But only because removing them requires some combat tweaks so servants aren't weakened a ton in combat without them.

### CODE REVIEW

**Comment by Xhuis** [comment]
Yeah, this is a thing, it's fine to keep and I think it'll help with the direction we're going in.

**Comment by KingPhilipIII** [comment]
No more making scarabs and saying "Go autism fort for me" I guess. Actually have to do it myself now.

**Comment by InsaneHyena** [comment]
A surprise to be sure, but a welcome one.

**Comment by kevinz000** [comment]
Clock cult is already weak ree

**Comment by Ergovisavi** [comment]
I think in the end it's a good thing but the lack of ghosts getting to participate in the round again makes me a little sad.

Still, it's probably better in the long run.

**Comment by Xhuis** [comment]
Marauders still function as a ghost role. While I'll miss the ability for ghosts to get back in so easily, their current implementation is odd and can be greatly improved.

**Comment by calzilla1** [comment]
Doesnt this fall under the pusdo freeze?

**Comment by Xhuis** [comment]
Kor's stated that improvements to clockcult that I've okayed have leeway.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
