### PR TITLE
buffs milk (not a bug fix this time!)

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR buffs the maximum amount/volume of milk that a skeleton, bone golem, or plasmaman can have in their system before it starts to drip off of their bones to >10u instead of >=6u.

## Why It's Good For The Game

This is mostly just a quality of life improvement for skeletons who are trying to heal themselves with milk, reducing the number of milk sipping sessions that you'd need to heal off 25 points of brute damage (and 25 points of burn damage) from 2 (one one-sip sipping session every 26 seconds) to 1 (once two-sip sipping session every 50 seconds). Powergamers can still use vapes and the like to ignore the "The excess milk is dripping off your bones!" system and the system will still keep you from doping up on absurd amounts of milk after this PR, so I don't really see how this PR could cause much harm to the game's balance.

## Changelog
:cl: ATHATH
balance: Buffs the maximum amount/volume of milk that a skeleton, bone golem, or plasmaman can have in their system before it starts to drip off of their bones to >10u instead of >=6u.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
webeditor daily

**Comment by ExcessiveUseOfCobblestone** [comment]
i'm not looking at anymore multi-file/line webbit PRs from you

**Comment by PKPenguin321** [comment]
He just changed like 3 numbers, if anything that's the correct use of the webeditor

**Comment by Jordie0608** [comment]
It's not.

**Pull request merged**
