### PR TITLE
Syndiesthetics Part 1: Updating The Old!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Hello everyone! I hope you've been having a good april, though I'd imagine its been turbulent for most, regrettably.

Regardless of circumstances, I am happy to reveal my next big project! Instead of updating Central Command as I have been famed for, I am taking a look to a rather neglected part of the game: **The Syndicate!**

Currently, their aesthetics are outdated, and Part 1 of this PR aims to update them to newer and modernized appearances for all to enjoy LARPing as their favorite dark-clad maniacs! Credits to @axietheaxolotl for the Tactical Turtleneck, they're sweet.

image

This PR, also updates the really black suit, after me and @axietheaxolotl discussed between the current version and a different version of the tactical suit they created, opting to used the scrapped version to modernize a very bad sprite!
image

Finally, this PR removes the unused Trak_Suit mob sprite from syndicate.dmi- since it was not only entirely unused- but its effectively a dupe of the yellow star trek outfit which currently lies in trek.dmi. (It didn't even have an obj sprite, for your information).

## Why It's Good For The Game
The syndicate is a very important part of SS13, and its pivotal for its aesthetics to be modernized. This is Part 1 for a concept moving forward, to add new fresh outfits that represent each syndicate faction appropriately! This is for flavor and to make the Syndicate as a whole a more fleshed out organization when exploring!

## Changelog

:cl: PositiveEntropy, AxieTheAxolotl
imageadd: Resprites several syndicate outfits, particularly the Syndicate Coat, the Turtlenecks, and the Combat Uniform!
imageadd: Resprites and updates the Really Black Suits!
del: Removes the trak_suit from syndicate.dmi (it was a dupe and unused)
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
Blessed.

**Comment by tralezab** [comment]
sex.

**Comment by RuneQuester** [comment]
THE SYNDICATE *ALWAYS* WIN-Dan The Syndicate Man, 2056, shortly before being busted by several security officers working for brutal megacorp NT

**Comment by retlaw34** [comment]
Lovely

**Comment by VladinXXV** [comment]
pixel vomit camo pants begone

**Comment by Serxule** [comment]
what are the 2 rightmost ones? are those the fake turtlenecks?

**Comment by Imaginos16** [comment]
> what are the 2 rightmost ones? are those the fake turtlenecks?

Yes.

**Comment by red-creature** [comment]
honestly, even though that the sprites on the right keep the colours consistent between the pants and the skirt, i just think the skirt's shading is way too dark. it looks really iffy to me

**Comment by optimumtact** [comment]
>As a special treat after many back and forths regarding keeping the Syndicoat's iconic vest, I decided to make it a toggle! Simply alt-click the Syndicoat to either add or remove its vest!

Dont' do this kind of thing it just makes the RSC bigger so you can avoid soul posters, there will always be soul posters but the RSC can't be an infinite size, so stop doing it.

**Comment by Imaginos16** [comment]
> > As a special treat after many back and forths regarding keeping the Syndicoat's iconic vest, I decided to make it a toggle! Simply alt-click the Syndicoat to either add or remove its vest!
> 
> Dont' do this kind of thing it just makes the RSC bigger so you can avoid soul posters, there will always be soul posters but the RSC can't be an infinite size, so stop doing it.
> 
> either you and the sprite leads believe your sprite is better, or you don't.

I do in fact believe my sprite is better, I only did this because I found it'd be a neat functionality that would be easy to implement. If however, this is *really* consuming for the game, I won't object to remove it.

**Comment by Mey-Ha-Zah** [comment]
I think more cosmetics need style toggles. Would reduce the amount of items, but also increase cosmetic values of items.

**Comment by Imaginos16** [comment]
@optimumtact resolved your criticism.

**Comment by optimumtact** [comment]
beileve in yourself

**Review by Twaticus — APPROVED** [review]
😍

**Pull request merged**
