### PR TITLE
Add me as codeowner for unit tests

### PR DESCRIPTION
**Pull request by Mothblocks**

### CODE REVIEW

**Comment by Time-Green** [comment]
I don’t think that works for non-maintainers

**Comment by Jared-Fogle** [comment]
Check again 😄

**Comment by optimumtact** [comment]
an indication that time green lacks critical information

**Comment by Time-Green** [comment]
I can't see member status on my phone and I took a shot, oh well

**Review by Rohesie — APPROVED** [review]

**Pull request merged**
