### PR TITLE
Makes plasma more visible.

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Might be a bit overkill but I'm open to trying this

**Comment by Core0verload** [comment]
100% overkill.

**Comment by KazeEspada** [comment]
What ever is lethal levels of plasma, I use the overlay to try to determine if a room is safe to breath again.

**Comment by duncathan** [comment]
someone change the toxic level definition to be MOLES_PLASMA_VISIBLE because they are intended to be the same

**Comment by MrStonedOne** [comment]
I don't think that's wise.

The idea here is to solve the issue where plasma just suddenly goes away during excited group avging. This was happening because outside of the edges of visible plasma it was still spreading.

This also made it seem like atmos was running slower then it was, or that it was being jumpy.

**Comment by MrStonedOne** [comment]
Making alpha gas overlays and making it so gases are much more visible over all, that will replace this PR.

**Comment by duncathan** [comment]
that's a better idea

**Pull request closed without merging**
