### PR TITLE
Laser Carbine sprite and sound improvement

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Changes the laser carbine sprite and makes the orange laser sprite brighter (the laser carbine shot orange lasers from the start). Changes the laser2.ogg to a new sound that is now used by the laser carbine (can be heard in the video):

https://github.com/tgstation/tgstation/assets/42353186/cfaff327-335f-4e6b-9773-b1ce62600212

**NEW SPRITE:**
laser carbine big

**OLD SPRITE:**
old carbine
## Why It's Good For The Game
The laser carbine sprite must be improved, as in the original PR people wanted it to be "polished" so I did it. Polished the sprite without changing the core design.
image

New sounds give it a unique sound to distinguish it from other guns, it's also less noise-polluting than normal laser gun sound which is long and too beefy for a 10-burn damage gun.
## Changelog
:cl:
sound: laser2.ogg sound has been changed. Now laser carbine uses it.
image: Laser carbine and orange laser sprite have been improved.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
Love the sound, like the sprite, dislike the orange laser. It doesn't look good IMO.

**Comment by DrDiasyl** [comment]
> Love the sound, like the sprite, dislike the orange laser. It doesn't look good IMO.

It looked less bright in past, the laser carbine had orange laser from the start.

**Comment by SomeoneYouProbablyKnow** [comment]
i like the orange laser, makes it easy to identify. One thing that's bothering me is that the muzzle? and the projectiles are not the same colour.

**Comment by carlarctg** [comment]
The orange color just looks weird. I dont know what I'd replace it with, most other colors are taken already. Green, or pink perhaps? Orange makes me think of the portal gun or igniting lasers, not weak lasers.

**Comment by DrDiasyl** [comment]
> The orange color just looks weird. I dont know what I'd replace it with, most other colors are taken already. Green, or pink perhaps? Orange makes me think of the portal gun or igniting lasers, not weak lasers.

*The thing is, if I make it not orange the Oranges will DNM this PR immediately*

**Comment by GPeckman** [comment]
The new sprites and sounds have my approval.

**Comment by nikothedude** [comment]
the orange looks fine, wym

**Comment by MTandi** [comment]
I like the old one more. The new sprite looks like MP40.

**Comment by GPeckman** [comment]
> I like the old one more. The new sprite looks like MP40.

Screenshot 2023-10-09 182127

**Comment by DrDiasyl** [comment]
> I like the old one more. The new sprite looks like MP40.

Believe me or not (you can read original PR) but original sprite was the one based on MP-40 😆

**Comment by setaciocascarudo** [comment]
Why do the lasers come out of behind the player's chest....

**Comment by DrDiasyl** [comment]
> Why do the lasers come out of behind the player's chest.... 

The repository copy on my computer is acting funny.
But this has nothing to do with the PR.

**Review by Wallemations — APPROVED** [review]
based off what I've seen in the sprite chat it's probably gonna get resprited again after this but this is still an improvement

**Pull request merged**
