### PR TITLE
North Star fixes & captain office expansion

### PR DESCRIPTION
**Pull request by norsvenska**
## About The Pull Request

A collection of small edits to North Star:
> Captain's office has had an expansion, making more room and adding a photocopier, sofa, and table for decoration.
> Captain's quarters now have a scrubber and a vent
> Captain's bedroom now has a light, and no longer has multiple lightswitches
> Kitchen coldroom now has a vent
> Abandoned kitchen airlock now has an abandoned airlock helper
> Ordnance test lab's APC is now wired to the station (it was not previously)
> Mining dorms on the station have had their locks changed; they previously conflicted with the dorms on the Lavaland outpost
> Teleporter beacons in the teleporter room have been changed: one has been moved to the floor, the other has been disabled and left on the table
> One of the rooms in Hydroponics had the pipes for a vent but no vent. I added a vent.

## Why It's Good For The Game

Captain's office felt too small and there was unused space. It now feels a little nicer.
Kitchen coldroom was unable to cool itself back down after the door is open for too long. The new vent should remedy that.
The ordnance lab's APC was disconnected from the station's power network, so it would run out of power without intervention.
The mining dorms had the same IDs as those in Lavaland, so locking the door of a Lavaland dorm would also lock one on the station.
Using the teleporter to go to the teleporter room would dump you on a glass table.
The changes make it easier to play on North Star. I don't know what else to say.

## Changelog

:cl:
add: North Star's captain's office has been expanded! It now includes a sitting area as well as a photocopier and some cigars.
fix: Various minor changes in North Star
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
Can you show off a screenshot of the captain's office please? Everything else is a fix but that's a design change and we should probably be able to see it.

**Comment by norsvenska** [comment]
image_2023-04-26_115859277

**Comment by Cheshify** [comment]
So the way you're expanding it is fine, that grilled area is mostly a defensive thing that's used across the map. I just don't know how I feel about this also creating this weird 2x3 block of r-walls there. 
image
Can I suggest doing this, where you remove two of those r-walls (replace them with pod floors like the rest of maint!) and move that light upwards?
image

**Comment by norsvenska** [comment]
Yeah, that corner did feel a little off. How's this?
image

**Comment by Cheshify** [comment]
Yeah that looks fine to me

**Pull request merged**
