### PR TITLE
increases the energy consuption of disabler ammo by 60%

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
balance: disablers shots now consume 60% more power
/:cl:

the disabler (same for egun disable function) its extremly spammy 
3 hit to stun and 1 hit to slow is really fun  when you shoot 20 shots (or 40 by dual wielding) in succession

### CODE REVIEW

**Comment by Anonymous-Player** [comment]
Cool, post how long you've played Security.

**Comment by ExcessiveUseOfCobblestone** [comment]
Do you really need more than 10 shots? If you're that cruddy at aiming, even after they've been slowed, you can still follow up with a baton.

**Comment by Shadowflame909** [comment]
I say it's unfair to try and take down a lone sec officer and have to dodge 40 shots when getting hit with 1 is GG no rematch. Good change

**Comment by necromanceranne** [comment]
Time to arrest with rubbershot for increased EEfficiency.

**Comment by zxaber** [comment]
>Remove tazers
>Nerf disablers

Yeah lets just remove Security. That seems to be where we're headed.

**Comment by Shadowflame909** [comment]
C'mon. I know you don't think 40 slowdown shots down the halls makes for fair gameplay. With all the buffs sec has gotten (movespeed nerf which makes weapons and secways faster, slip nerf which no longer stuns, disarm nerf so it's harder to make them drop their weapon, wavedashing removal to allow sec to disable people who are resting without targeting them) is this nerf really so bad?

**Comment by GuyonBroadway** [comment]
1. Remove sec
2. Everyone spawns with a glock
3. Gun vendors for people to spend money on

2nd amendment station, DO IT!

**Comment by zxaber** [comment]
You want to know what I think, Shadow? I think antags are already overpowered, and weakening Sec is not making things better.

I think that trying to take on Sec should be dangerous and difficult, and that traitors should be encouraged to avoid direct confrontation unless they have worked to amass an overwhelming advantage (one that goes beyond just purchasing from the uplink).

**Comment by wesoda25** [comment]
lol no one plays sec already, now you wanna just limit it to the robust too. Tasers have like 5-6 shots, meaning with perfect aim you can drop a mob for ~7 seconds each. This would make it so that with perfect aim, you can drop 3 people tops, each for about 4 seconds.

**Comment by subject217** [comment]
i ded

**Comment by anconfuzedrock** [comment]
tasers could stun five people if you didn't miss. this is retarded. now lasers will be the best function.

**Comment by actioninja** [comment]
Too soon, wait a month or so to give people a chance to settle in and see how effective disablers actually are.

**Comment by wesoda25** [comment]
@actioninja everyone used disablers already aside from people ambushing others, nothing will change I’d assume.

**Comment by Shadowflame909** [comment]
@wesoda25 true but you can literally shoot down a hall 40 times and if you hit your target once you've won a conflict


is this really butter

**Comment by zxaber** [comment]
The question is why did you get into a situation where sec is shooting at you in the first place?

**Comment by Shadowflame909** [comment]
@actioninja 

We need more stealth traitor gear then nerd


It's really awful how the best things in the syndicate uplink are meant for going loud.


more stealth items when

**Comment by nicbn** [comment]
Oh yeah the buff murderboning antags needed

**Comment by 81Denton** [comment]
I agree with the sentiment, but feel that we should wait a while with further sec balance tweaks. Otherwise people won't have time to get used to the taser removal and it'll just feel like an unjustified punch in the dick to sec players.

**Comment by Tlaltecuhtli** [comment]
disablers were bad and spammy before the change its just that no one bothered to fix em before

**Comment by anconfuzedrock** [comment]
This change is balanced, for a server where literally only one player is doing anything wrong. Any more, and you might as well join the baton only master race, this is just reason to use the tempgun (and if you nerf the tempgun you’ve truly gone full retard)

**Comment by ExcessiveUseOfCobblestone** [comment]
> This change is balanced, for a server where literally only one player is doing anything wrong. Any more, and you might as well join the baton only master race, this is just reason to use the tempgun (and if you nerf the tempgun you’ve truly gone full retard)
> I’m not even certain this gun fully drains if you shoot every shot with the new energy cost.

12.5 shots so there's a half-shot "stored"

**Comment by anconfuzedrock** [comment]
Yeah, that’s weird as FUCK. Bad, and i’ll take any excuse to hate this PR more

**Comment by adamkad1** [comment]
> I say it's unfair to try and take down a lone sec officer and have to dodge 40 shots when getting hit with 1 is GG no rematch. Good change
> 
> Edit: Disliking every post in the thread doesn't make you right

i dont know about ya, but getting hit by one disabler shot does not slow you down right now, play sec more

**Comment by wesoda25** [comment]
Tempgun deserves all the nerfs it can get, don’t start that shit with me. Not disablers tho, especially with stun removal.

**Comment by adamkad1** [comment]
> Tempgun deserves all the nerfs it can get, don’t start that shit with me. Not disablers tho, especially with stun removal.

tempgun needs nerfs, but a desword toting adrenaline using tot does not huh?

**Comment by necromanceranne** [comment]
No because bolas exist to counter that

**Comment by wesoda25** [comment]
lol I’ve become a sec main of sorts, if you even use the temp gun you’re a little baby. I’d sooner be killed by a thousand desworders (btw flashbang or stun baton usually give you a fighting chance) before I touch a fucking temp gun. Temp gun is crazy OP fuck that little baby boy unrobust looking ass crutch weapon for all shitsec, I’m not even robust and even I don’t need that shit FUCK.

**Comment by subject217** [comment]
>i dont know about ya, but getting hit by one disabler shot does not slow you down right now, havent they like, nerfed disabler damage?

it does slow you down for around 5 seconds

it was unintended and as soon as I figure out a straightforward way to make disablers consistent again without hard reverting limb stamina damage it'll be out the door

**Comment by Shadowflame909** [comment]
Well, that's very great subject, and I hope it gets fixed

**Comment by anconfuzedrock** [comment]
Inb4 all officers carry 2 disablers

**Comment by ExcessiveUseOfCobblestone** [comment]
1 lamb every day or this PR comes back 

reopen after some time has passed from the stun changes, tissue reserves need to be resupplied before we do another ranged stun hit'n'run

**Pull request closed without merging**
