### PR TITLE
Donk Pocket pizza is back on the menu

### LINKED ISSUE #49373: Donk Pocket pizza no longer craftable
It appears that with the additon of the many new kinds of donk pockets, it's not possible to craft this pizza, which is a shame, since it has pretty good stats. Could someone modify the recipie, so that it accepts any kind of warmed donk pocket?

Issue reported from  Round ID: 130276 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request

fixes #49373

## Why It's Good For The Game

Who doesn't like a pizza with possibly pizza flavored donk-pockets on it?

## Changelog
:cl:
fix: Donk Pocket Pizza is back on the menu
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
did you test this

**Comment by Capsandi** [comment]
Yep, with berry donk pockets, heated em and used em to make a pizza

**Comment by RaveRadbury** [comment]
If you make gondola donk pocket pizza will there be any tell for the fate they are about to receive?

**Comment by improvedname** [comment]
But you always could make this pizza because you could make normal donk pockets???

**Comment by improvedname** [comment]
image

Never a bug you always could make normal donk pockets as a chef

Its called a donk pocket pizza, not a flavored donk pocket pizza

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=lco9Ki-5qfQ

**Comment by spookydonut** [comment]
> 
> 
> image
> 
> Never a bug you always could make normal donk pockets as a chef
> 
> Its called a donk pocket pizza, not a flavored donk pocket pizza

who the hell takes a screenshot of code

**Comment by improvedname** [comment]
Me

**Pull request merged**
