### PR TITLE
[READY] Adds the Dynamic Environment Interaction shuttle

### PR DESCRIPTION
**Pull request by Pumpkinoe**
## About The Pull Request
This PR adds a new, large emergency shuttle with a large biodome taking up the centre, filled with jungle life, and most importantly, monkeys. 
Featuring: 
- A medium sized cockpit
- A small brig
- A very small medbay at the back
- A quite large general area with a nice biodome in the center, with approximately 6 monkeys to start with, and trees!
- Extra monkeys on a table in the crew area, and two more boxes in command.
- Botany vendors, equipment and soil
- Bananas!
- All the features a regular shuttle would need.

Costs 8000 Cr.

## Why It's Good For The Game

A new, interesting shuttle that may prove interesting to interact with when escaping, such as including monkeys that may help or hinder your certain 'plans' aboard the escape shuttle.

image

## Changelog
:cl:
add: Added a new large emergency shuttle for purchase at 8000 Cr, the Dynamic Enviornment Interaction Shuttle. Try it out today and frolic with the monkeys!
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
First PR, so I hope I did this right.

**Comment by Pumpkinoe** [comment]
image
Pics!

**Comment by Tlaltecuhtli** [comment]
no gorillas?

**Comment by Fikou** [comment]
use mapmerge

**Comment by Pumpkinoe** [comment]
I will definitely map merge as soon as I figure out how I do that!

**Comment by trollbreeder** [comment]
damn you're a good mapper for a first timer

**Comment by Fikou** [comment]
i think the placement of the shuttle doors wont line up with most maps

**Comment by Pumpkinoe** [comment]
Lines up on box mostly so I think it works

**Comment by Pumpkinoe** [comment]
Oooooh deaaaaaaaaaaaaaaar. I'm wrangling up map merging right now. I thought it would be simpler. Please stand by for monkey merge.

**Comment by Pumpkinoe** [comment]
That didn't work, and now I'm sad. I'll figure this out in the morning, if not tonight.

**Comment by Pumpkinoe** [comment]
This hurts head. Give moment for moneky brain to fix.

**Comment by ATH1909** [comment]
Idea: What if you also put some monkified genetics injectors on this shuttle? Would that clash with the theme a bit too much?

Also, the lack of bananas in this shuttle saddens me. Maybe scatter some bananas around the monkey pen (and the shuttle in general), with perhaps an entire spare crate of them in the back/storage end of the shuttle? Would it be possible to put fully-grown banana trees in some of the dirt plots, or does new!botany not play too nicely with that kind of thing?

**Comment by TiviPlus** [comment]
> Idea: What if you also put some monkified genetics injectors on this shuttle? Would that clash with the theme a bit too much?

No. We all know what this would lead to

**Comment by Pumpkinoe** [comment]
The lack of bananas I will adress.
Monkified injectors I CONSIDERED, but I wanted people to enjoy the nature, not become it, so I omitted it.

**Comment by Pumpkinoe** [comment]
I think I am screwing this up big time. Stop me if I am.

**Comment by Pumpkinoe** [comment]
Aaaand now there's no map visible in the diff renders. What the fuck did I do? I feel like I'm going insane here, I'll fix this in the morning. Help please.

**Comment by Pumpkinoe** [comment]
Huge thanks for tivi for unscrewing all my screwups.

**Comment by Fikou** [comment]
> Lines up on box mostly so I think it works

mostly

**Comment by Pumpkinoe** [comment]
Yeah I may need to fix the doors
Shouldn't be an issue

**Comment by wesoda25** [comment]
The choice of windoors for the inclosure seems a bit odd, why not airlocks?

**Comment by Pumpkinoe** [comment]
I wanted a full glass feel, and most airlocks felt less glassy.

**Comment by Pumpkinoe** [comment]
Aaaand boom, now it lines up perfectly with Meta.

**Comment by Pumpkinoe** [comment]
Truthfully this had been ready for a while, so I guess I have to put the R-word in the title now.

**Comment by Pumpkinoe** [comment]
This isn't stale, it just needs review.

**Pull request merged**
