### PR TITLE
Removes a single roundstart active turf from z4

### PR DESCRIPTION
**Pull request by Core0verload**
I tried to remove actives from z2 too, but was unable to find the activation source.

### CODE REVIEW

**Comment by WJohn** [comment]
It's likely they're caused by shuttles that begin on z1, check the locations on box.

**Comment by Core0verload** [comment]
No, these turfs are on CTF arena.

**Comment by xxalpha** [comment]
Isn't CTF in z2?

**Comment by Core0verload** [comment]
Yes, CTF is on z2. There was one active on z4, I fixed it. But I was unable to do the same with z2 actives (there is a pair of them I think).

**Pull request merged**
