### PR TITLE
Adds smuggler's satchels to the game and traitor uplink

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Adds smuggler's satchels to the traitor uplink. Available for only
2 TC, you can stash them underneath a floor tile for hidden storage.
Each satchel also comes with a bunch of left over contraband. Scattered
across the station each round is a handful of satchels, also containing
contraband. Note that they do not have any persistence based features.
tweak: The "Aranesp" reagent has been renamed to "Smuggler's Run", and
is now marketed as an anti-disabler chemical. Its actual game effect is
unchanged, which is massively reducing stamina damage, at the cost of
minor toxin and oxygen damage.
tweak: The Squeak subsystem (responsible for putting mice in
maintenance) has been renamed to the Minor Mapping subsystem, for low
priority map stuff. The new contraband smuggler satchel spawning is also
done in this renamed subsystem.
admin: Admins can now spawn floorpill pill bottles, in various states of
fullness.
/:cl:

- A whole buttload of contraband pills now have specific appearances
and descriptions.
- Smuggler's satchels are now visible to observers, who can click on
them to see what's in them (just like any other bag).
- The "roundstart" trait on pills is now renamed to
"rename_with_volume", which more accurately describes what the var
actually does.

### CODE REVIEW

**Comment by subject217** [comment]
lol

**Comment by Vidiveni** [comment]
Don't rename aranesp please. I like the name aranesp. You could make a bar drink named smuggler's run instead.

**Comment by ATH1909** [comment]
Who's gonna pay 2 TC for semi-useless contraband that you can just get from searching Maintenance for two minutes?

The "you can hide storage under a floor tile" thing is pretty close to useless, as you'd have to have access to a crowbar (or another way of ripping up floor tiles) to access a buried satchel. Why not just hide it via "mundane" means (in a locker, in a toilet, under a plant, etc.), especially since smuggler's satchels are (debatably) MORE obvious than those "mundane" means of hiding things (because they'll stand out to anyone who's walking around with an active t-ray scanner)?

**Comment by coiax** [comment]
Traitor bought smuggler satchels come with a free crowbar and a floor tile, and the contraband is a mild bonus, not the main attraction.

**Comment by subject217** [comment]
if you don't want to pay 2 tc to hide stuff under floortiles, simply don't buy it. it's not going to be the SUPER BEST OPTION for every plan. it is more affordable than the alternatives, which is all it needs to be.

**Comment by Shardj** [comment]
> Who's gonna pay 2 TC for semi-useless contraband that you can just get from searching Maintenance for two minutes?

I would, absolutely great for hiding grenades in public places

**Comment by optimumtact** [comment]
can you not bundle changes, you were told to split these up by subject already.

**Pull request closed without merging**
