### PR TITLE
Puts back the changeturf part of PlaceOnTop()

### LINKED ISSUE #34027: Can't build walls or floors
Wow, I've seen players in game complain about this for the last 24 hours on almost every round, even had people contact me on discord about it and not one of them thought to make a report.

Currently walls cannot be created, adding metal to a wall girder causes it to disappear, and using an RCD does nothing (but does use units, make the noise and give you the text "You build a wall.")

Just found out an RCD in "deconstruct" mode DOES create a wall

If you put down a lattice and attempt to tile it then the floor and the lattice disappears.  If you then put another rod down on the same spot both a lattice and floor plate appear.

RCDs cannot make floors

Basically it is all badly broken.

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: ninjanomnom
fix: Turfs are construct-able again
/:cl:

Woops, I forgot about the changeturf part of PlaceOnTop while making it act the same as PlaceOnBottom.

Tested and working

closes #34013 
fixes #34027

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Strong early contender for fuck up of the year 2018

**Comment by DaxDupont** [comment]
Technically the fuck up was in 2017 no?

**Comment by ninjanomnom** [comment]
The first fuck up of the year is always the worst fuck up of the year. Until something worse comes along

**Comment by WJohn** [comment]
This would fix #33984 too, right? Same issue, I'm assuming.

**Comment by ninjanomnom** [comment]
no @WJohn they're different, I've explained before that space under shuttle turfs is something that was expected and can't be changed back to how it was before until shuttles are all loaded in as templates

**Pull request merged**
