### PR TITLE
Makes metallic hydrogen golems actually spaceproof

### LINKED ISSUE #59151: Metallic Hydrogen Golems not spaceproof
## Round ID:
[162370](https://scrubby.melonmesa.com/round/162370)

## Reproduction:
Golems made of Metallic Hydrogen are not immune to pressure (and/or temperature) damage from space exposure. 
This may be an issue specific to Metallic Hydrogen golems created through Pride's Mirror. Issue was found immediately after the transformation, since the mirror teleports you into space as it transforms you.

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
Metallic hydrogen golems are now spaceproof

## Why It's Good For The Game
Fixes #59151 , all other golems are spaceproof and golems should be spaceproof.

## Changelog
:cl:
fix: Metallic hydrogen golems are now actually spaceproof
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
H2 golems are purposely not space proof and can take cold damage, this should not be merged

**Comment by LemonInTheDark** [comment]
The lack of space proofing was a balance concern to offset the other strengths the things have (really shoulda left a comment or something about it)
I don't really like the idea of trading it out since I think it's a pretty unique weakness, but maybe some form of telegraph to the player would help here

**Comment by Mothblocks** [comment]
what

**Comment by LemonInTheDark** [comment]
I stand by what I said. Also damn he closed it

**Pull request closed without merging**
