### PR TITLE
adds immersive message to cuff breaking

### PR DESCRIPTION
**Pull request by PKPenguin321**
you can't break those cuffs

https://tgstation13.org/phpBB/viewtopic.php?f=9&t=6095

disclaimer: meme pr

### CODE REVIEW

**Comment by Zilenan91** [comment]
Oh wow you actually did it.

:+1:

**Comment by optimumtact** [comment]
it should make you say
"Am I being detained, I am a free citizen of the earth under natural law and you do not have the authority to hold me"

**Comment by Incoming5643** [comment]
:-1: You can't break those cuffs!

**Comment by KorPhaeron** [comment]
Having the same message every time someone breaks cuffs will be dumb

**Comment by PKPenguin321** [comment]
should i do the tactical reloading thing and make it a variety of meme messages

**Comment by KorPhaeron** [comment]
Sorry I'm on the other team now

**Comment by PKPenguin321** [comment]
rip

**Pull request closed without merging**
