### PR TITLE
Move Boxstation protolathe/youtool to engineering foyer

### LINKED ISSUE #41445: [BoxStation] Atmos doesn't have access to the department protolathe.
Atmos, despite being Engineering, is not allowed access to the engine room per the default access. However, this is where the department protolathe resides.

Pubby, Delta and Meta all have a shared access tool room containing a protolathe.

### PR DESCRIPTION
**Pull request by 0xJoey**
[Changelogs]: 
:cl: JoeyJo0
fix: Changed BoxStation Engineering door to Engineering Foyer door, to reflect the other stations.
/:cl:

Fixes #41445

[why]: As an atmos, I want to build freezers/heaters and use engineering tools. In the other stations, I can enter a shared tool storage. This is absent in BoxStation, however.

### CODE REVIEW

**Comment by Barhandar** [comment]
That glass around sec checkpoint isn't just to let sec see out of it, it's to let you break into there, which means surrounding it with machinery is against the point.

**Comment by subject217** [comment]
things being inconvenient and annoying is part of boxstation's map design. if you don't like it you should play on a different map.

**Comment by Bawhoppen** [comment]
@subject217 I would agree, but say moreso that other stations are too streamlined and not enough of "bare-minimum metal deathtraps"

**Comment by 81Denton** [comment]
@JoeyHaas You'll need to run mapmerge in order to get the PR approved. It's pretty simple:
1) Install Python 3.6 (anything below pything 3.7 is fine too)
2) Run tgstation\tools\hooks\install.bat
3) Now, git commit the map changes you did again.
4) Mapmerge will now run in the background and the result will only be a few line changes instead of thousands.

**Comment by 81Denton** [comment]
That aside, I don't understand the downvotes.

Things on Boxstation aren't inconvenient because of a design guideline, but because the map is outdated and hasn't received any of the updates Meta/Pubby/Delta have.

Keeping atmos techs from accessing their department's protolathe is definitely not intended and one of the annoyances that make Box unpopular.

**Comment by JoeyHaas** [comment]
@81Denton I had actually done this, but apparently it doesn't work with "git commit -a".

Anyways, it has been fixed.

**Comment by ShizCalev** [comment]
https://github.com/JoeyHaas/tgstation/pull/2

Made a small adjustment to maintain the current flow;
image

**Comment by JoeyHaas** [comment]
@ShizCalev Hmm, hadn't even thought of that possibility. Looks great!

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
