### PR TITLE
nerfs cakehat

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

nerfs cakehats heat from 999 to 998

## Why It's Good For The Game

Like, we all know how cakehat is broken, so i nerfed it

## Changelog
:cl:
balance: nerfs cakehat
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
Nice trips but also no

**Comment by nemvar** [comment]
wtf wtf

**Comment by Pugie** [comment]
reopen and merge wtf

**Comment by Rowelll** [comment]
cakehat needs a buff, not a nerf :(

**Comment by AcapitalA** [comment]
It would still be not enough, maybe give it meth speed too.

**Pull request closed without merging**
