### PR TITLE
Removes title4.ogg

### PR DESCRIPTION
**Pull request by Cyberboss**
Same reasons as I did not grief them

### CODE REVIEW

**Comment by Niknakflak** [comment]
*Older than title3
*if you revert it, I'll write a new one that will probably be decent but worse.
*Exists as the suspenseful one out of the titles
*not from a stupid movie or wherever the room is from

**Comment by GunHog** [comment]
What is wrong with this song? It seems perfectly fine to me.

**Comment by Niknakflak** [comment]
Grudge PR asked to be opened by leoz

**Comment by Cyberboss** [comment]
No, I just hate everything not title1-3

**Comment by PKPenguin321** [comment]
👍 i hate this song

**Comment by Vivalas** [comment]
Literally the best SS13 ambience / song.

**Comment by The-clown-known-as-Pepe** [comment]
this is a "goof" type PR

**Comment by lzimann** [comment]
conflicts @Cyberboss

**Comment by PKPenguin321** [comment]
That awful "SCREEEEEEEEEEEE" that the song starts with is basically the worst thing in the codebase and people will complain about it in OOC now and then say "who added this lobby song"

**Comment by lzimann** [comment]
i am going to merge this

**Pull request merged**
