### PR TITLE
Fixes water+gold slime extract spawning invisible "animal"s sometimes.

### LINKED ISSUE #11387: Gold Slime Cores are creating the base /simple_animal
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/simple_animal/simple_animal.dm

I know because I discovered one that was called animal and was invisible and chased its own tail.

### PR DESCRIPTION
**Pull request by phil235**
Fixes #11387

### CODE REVIEW

**Comment by Jalleo** [comment]
:+1: sorry for bad info on the issue report and from irc

**Comment by Jordie0608** [comment]
#11277 will already address this.

**Comment by bgobandit** [comment]
aw shit my bad

**Comment by phil235** [comment]
@Jordie0608 oh, I forgot about your PR. I'm closing this one then.

**Pull request closed without merging**
