### PR TITLE
Declaring War Stat Fix

### LINKED ISSUE #34261: `nuclear_challenge_mode` stat isn't being recorded
See: https://atlantaned.space/statbus/round.php?round=81660&file=newscaster.json#97b6036 (Op war declaration message) and: 
https://atlantaned.space/statbus/round.php?round=81660&stat=nuclear_challenge_mode (which is blank)

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Hopefully fixes #34261 

WARNING: WEBBITOR USAGE

### CODE REVIEW

**Comment by nfreader** [comment]
Aaaaahhhh! Change the version please!

**Comment by ExcessiveUseOfCobblestone** [comment]
It's a count ni:b::b:a

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Change the version, that's the whole point of the system

**Comment by Jordie0608** [comment]
#34265

**Pull request closed without merging**
