### PR TITLE
Makes the one pixel holes in grille and reinforced girder clickable.

### PR DESCRIPTION
**Pull request by phil235**
Makes cutting, screwing and hitting the grille less irritating

### CODE REVIEW

**Comment by Incoming5643** [comment]
Also makes fighting animated grills a lot more consistent

**Comment by WJohn** [comment]
Eh, why not :+1:

**Comment by Jordie0608** [comment]
Isn't mouse_opacity better for this?

**Comment by RemieRichards** [comment]
@Jordie0608 yes, @phil235 use ```mouse_opacity = 2```, don't just flood the grille with alpha.

**Comment by phil235** [comment]
If I use mouse_opacity I would have to add some lines to toggle mouse_opacity when the grille becomes broken and when it is repaired though.

**Comment by Jordie0608** [comment]
Why raz why

**Pull request merged**
