### PR TITLE
Tendril chests and mystery boxes can now be fished multiple times with a 30 minutes cooldown.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Someone told me chests and some other rare fishing loot should regenerate over time. I kind of agreed, just because the somewhat infrequent hour(s) long rounds can get a little dull if the content is expended.

This PR doesn't just affect the chests, it also gives cooldowns to a few limited materials from icemoon (8-10 minutes) as well as the megacarp from the space dragon rift (dunno why really) and the big fish nugget nessie (22 minutes).

## Why It's Good For The Game
It should be possible to get multiple chests during particularly long rounds as well as some other loot that you can't farm with explosives.

Maybe I'll bump up the regen time from 30 mins to whatever for the mystery box, idk.

## Changelog

:cl:
balance: Tendril chests and mystery boxes can now be fished multiple times with a 30 minutes cooldown.
balance: other previously fishing loot available in limited amount, such as adamantine and runite from plasma rivers, regenerate over time.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
should edit the "///One of a kind, rarely found by fishing in the ocean." on the mystery box to reflect it no longer being one-of-a-kind

(and also fix the typo in its description while you're there)

**Comment by carlarctg** [comment]
thank god you can only fish up 2 runite sheets i shudder to think what sick and twisted things could be done with it otherwise

**Comment by Eronymun** [comment]
Wait, is it thee mystery box that gives a random gun, but limited?

**Comment by Ghommie** [comment]
> Wait, is it thee mystery box that gives a random gun, but limited?

It's like that, but with its own pool of weaker rewards, mostly not guns.

**Pull request merged**
