### PR TITLE
Felinids now have their own tongue and accent

### PR DESCRIPTION
**Pull request by trerri**
## About The Pull Request

Felinids have a "cat tongue". This makes them turn L and R to W. It also makes them start words with Ny if they started with N.

## Why It's Good For The Game

Felinids need to be more unique. This adds a feature that is present in another typical species, lizards.

## Changelog
:cl:
add: Fewinids have a dedicated tongue owgan. It makes them speak wike this. Nya~!
/:cl:

### CODE REVIEW

**Review by 81Denton — COMMENTED** [review]
nyot a good idea

**Comment by kriskog** [comment]
> 
> 
> no

*nyo

**Comment by scarwolff** [comment]
MAKE THEM SUFFER

**Comment by Rohesie** [comment]
nyet

**Comment by TiviPlus** [comment]
nyein

**Comment by LemonInTheDark** [comment]
nyot in your lifetime

**Comment by Jared-Fogle** [comment]
> Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

Did you get prior approval?

**Comment by Couls** [comment]
nyot like this

**Comment by Timberpoes** [comment]
Whiwe I appweciate the effowt and I weawwy wike the idea of twiggewing aww the fewinid hatews, thewe's nyo way we awe gonna mewge this.

**Comment by itseasytosee** [comment]
As a human being who has never made faces with letters on the internet, I want to stick my hand in a wood chipper reading this Pr.

**Comment by scarwolff** [comment]
yeah bro but its ironic bro, its ironically suffering, thats the whole point of felinids is that they make everyone else suffer due to their ironic satire (also doing this might make other people playing them think otherwise, godspeed, speedmerge)

**Comment by scarwolff** [comment]
ORANG MAN NO

**Comment by Timberpoes** [comment]
OWANGE MAN YES!

**Pull request closed without merging**
