### PR TITLE
why the fuck does antitoxin remove reagants, that's what charcoal is fucking for

### PR DESCRIPTION
**Pull request by ghost**
:cl: more robust than you
tweak: Antitoxin is no longer a shitty version of charcoal
/:cl:

tl;dr: Charcoal is better at removing reagants, antitoxin is better at healing toxins

### CODE REVIEW

**Comment by Cyberboss** [comment]
2 Reasons:

Tricord
Recipes

**Comment by MoreRobustThanYou** [comment]
@Cyberboss does tricord remove reagants? no. So why should antitox?

**Comment by Bawhoppen** [comment]
What's wrong with two things have the same purpose?

**Comment by MoreRobustThanYou** [comment]
@Bawhoppen redundancy for no reason

**Comment by Cyberboss** [comment]
Then just make charcoal a child of antitoxin

**Comment by lordpidey** [comment]
Antitoxin only removes "toxins", but leaves other chemicals in, so if someone is ODing on tricord, you need charcoal, not antitoxin.

Meanwhile, if someone drank a beaker of hydrochloric acid, you'll want to give them kelotane+anti-toxin.

**Comment by Iamgoofball** [comment]
:-1: Stop nerfing goonchems you fat fuck

**Pull request closed without merging**
