### PR TITLE
[HC] Removes damage caps

### PR DESCRIPTION
**Pull request by Iamgoofball**
i can now beat a corpse up with a welder for as long as I want, it won't hit an arbitrary limit on damage now

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
So you can kill someone by breaking their legs?

**Comment by duncathan** [comment]
Nah that's another one. This one means that patch-defib is gonna take quite a few more patches than usual.

**Comment by Dorsisdwarf** [comment]
I meant, doesn't this mean you can keep hitting someone in an extremity to kill them if there's no cap?

**Comment by Iamgoofball** [comment]
Yeah, once I remove limb damage caps.

**Comment by WJohn** [comment]
The balancing point of having damage cap on legs was to prevent you from being able to kill someone strictly by aiming there, so armor has SOME relevance in the middle of combat. It's kinda arbitrary, sure, since you can easily aim at another limb and it's quite likely to hit them somewhere else, but still.

**Comment by Ergovisavi** [comment]
The thing about limb damage caps is that, yes, while they're logically there to stop you from bypassing armor, in reality targetting multiple limbs in combat is a shitty user experience, and we're better off simply having combat-effective armor cover all your limbs, and just removing the stupid cap.

**Comment by Shadowlight213** [comment]
Not hardcore enough. Add a second damage limit that makes the body gib when its reached.

**Comment by duncathan** [comment]
Guys this isn't about limbs

**Comment by optimumtact** [comment]
What shadowlight said

**Comment by freerealestate** [comment]
This is like being able to murder a guy in every shooter by shooting them in the foot enough times. It doesn't make sense.

**Comment by Lumipharon** [comment]
It would be better if we had dismemberment. But that is vapourware at this point sadly.

**Comment by Iamgoofball** [comment]
@freerealestate don't care, hardcore

**Comment by freerealestate** [comment]
You're making "hardcore" sound like "unfair/unbalanced shit".

**Comment by WJohn** [comment]
I think goofball is spiteful of people constantly pushing and shoving him around with buzzwords, so he's fighting back by going way overboard.

**Comment by duncathan** [comment]
goofball literally asked "what's hardcore branch" and got the response "danger meme"
he's only working with what he's been told

**Comment by Iamgoofball** [comment]
@WJohn dunc is right

i asked what it was

i perform what i was told

**Comment by Summoners** [comment]
HARDCOREEEEEEEEE :+1:

**Pull request closed without merging**
