### PR TITLE
Sigils of Transgression are brighter

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
balance: Sigils of Transgression are slightly brighter.
/:cl:

Old:

New:

I'm not actually sure anyone but me could see these before, ha ha.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
two pictures of black squares

**Comment by ChangelingRain** [comment]
why does everyone but me have a shit monitor, this is very confusing

**Comment by KorPhaeron** [comment]
Well I am shitposting from a phone and its a rainy day so the screen isnt very bright

**Comment by kevinz000** [comment]
don't worry kor i can see it i'm trained to see this stuff.

**Comment by Robustin** [comment]
Thanks for reading my suggestion - it will be pretty hard to strike a balance on this but having them not be invisible (although I can barely tell the difference) in darkness is a good step. 

The best solution is probably adding a limit per cultist because unless you have a pocket chaplain there's just no way to deal with stun rune spamming.

**Comment by ChangelingRain** [comment]
literally anyone can remove them, though, just hit them with any item or an open hand.

**Comment by Robustin** [comment]
wat

**Pull request merged**
