### PR TITLE
Adds additional variety to the human laugh sound.

### PR DESCRIPTION
**Pull request by Iamgoofball**
This should help with sound repetition.

### CODE REVIEW

**Comment by iskyp** [comment]
better alternative PR

**Comment by JJRcop** [comment]
[](https://www.youtube.com/watch?v=H47ow4_Cmk0)

**Comment by nicbn** [comment]
So that's why cyber wants to stop webedit prs

**Comment by ninjanomnom** [comment]
It almost wasn't a shitpost, should have just cut the sound a little better

**Comment by Iamgoofball** [comment]
Did I leave in the end bit

**Pull request closed without merging**
