### PR TITLE
Fixes ORM again.

### LINKED ISSUE #45748: ORM unlinkable to the Ore Silo
After the recent changes you can't link the ORM to an Ore Silo. Linking the Silo to other machines still works as normal. 
The issue was present even before the latest fix to the ORM during the period you couldn't insert IDs into it, latest merge then was at about #45374

## Reproduction:
- Become free golem, get your R&D, create Ore Silo from the circuit
- Link that to your imprinter and the protolathe to see it works just fine
- Attempt linkage to the ORM only to find out you attack it with the multitool instead

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

#45627 broke it.

Same fix as last time (#45522). Learn to properly resolve conflicts.

Fixes #45748

## Changelog
:cl:
fix: Fixed ORM/silo link AGAIN!! Stop breaking it reee!
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Didn't #45693 fix this?

**Comment by zxaber** [comment]
#45693 claims to have fixed it already. Is it _still_ broke?

**Comment by nemvar** [comment]
Different issue. #45693 fixed ID functionality. This fixes the multitool link thing.

**Comment by Qustinnus** [comment]
next person to break ORM triple dumb

**Pull request merged**
