### PR TITLE
Adds Bullet Embedding

### PR DESCRIPTION
**Pull request by Fhaxaris**
Makes bullets embed into a human upon hitting them. Armor will stop bullets from embedding, based on if the bullet pierced it or not. For comparison, a ninja star has an embed damage of four. 

- Most bullets have an embed damage of one.
- Incendiary bullets will never embed.
- Buckshot has less than one.
- Rifle bullets and very strong pistol bullets have two to four, depending on ammunition type. (Hollowpoint has high embed damage.)
- Bullets will embed when the bullet armor is less than or equal to ten. This is to stop non-combat hardsuits from making you immune to bullets embedding everywhere on your body.

## Why It's Good For The Game
It adds a game mechanic that will lead to new strategies. It also gives a reason to use HP ammo as the embed damage with it is much higher. I also think it is strange that bullets just hit you and cause bleeding, and that is the end of your suffering. It is not like it is a laser.

## Changelog
:cl:
add: Bullets will now embed into you unless your armor is powerful enough to stop it.
imageadd: Embedded bullet sprite
/:cl:

### CODE REVIEW

**Comment by SkeletalElite** [comment]
Cool idea mechnically. 

Although about thinking its weird that bullets only cause damage and bleeding- thats fairly realistic. In real life, removing bullets generally has a much higher short term risk than just leaving them in and are generally only removed due to possible long term effects like lead poisoning. 

https://tvtropes.org/pmwiki/pmwiki.php/Main/WeHaveToGetTheBulletOut

**Comment by Fhaxaris** [comment]
> remov boolet not good

):

**Comment by actioninja** [comment]
Why would you want to have ballistic guns be even stronger than they already are?

**Comment by Fhaxaris** [comment]
I think it is a cool mechanic. If the damage is too much I can always tweak it to be lower.

> Why would you want to have ballistic guns be even stronger than they already are?

I think it is a cool mechanic. If it makes ballistic weapons too strong or armor too important, it can be nerfed.

**Comment by kopoba** [comment]
So there is no random and if you get shot by Buckshot shell in close combat all 6 pellets will be embedded?

**Comment by necromanceranne** [comment]
It probably should be random if it isn't but it is cool. I actually disagree with actionninja, I feel like ballistic weaponry has always been weaker than lasers in fairly subtle ways (it's the lack of a reload mechanic and ease of recharge). The only ballistic weapons that are remotely powerful right now are shotguns, which I'd be very wary about making any stronger.

Having it be a chance to embed would likely make this mechanic far less severe.

**Comment by Tharcoonvagh** [comment]
Do you need to get EVERY bullet out? Like if someone empties a SAW into you, isn't that a bit too much?

**Comment by Dorsisdwarf** [comment]
If you're going down this route, shouldn't high-penetration / high damage bullets just blow straight through and not embed?

**Comment by CRITAWAKETS** [comment]
Huh. The scattershot for mechs is now going to instacrit people at close range. Neat.

**Comment by Fhaxaris** [comment]
> So there is no random and if you get shot by Buckshot shell in close combat all 6 pellets will be embedded?

All six pellets will be imbedded. It looks like I forgot to change the embed damage to .1 for the buchshot and scattershot.

> If you're going down this route, shouldn't high-penetration / high damage bullets just blow straight through and not embed?

Bullets that physically go through you like the ones on the syndicate shuttle don't embed. I don't think AP rounds should go through you.

It seems that having every bullet embed with 100% chance is too severe. I could make it some percentage instead. Having to remove every pellet is annoying. It also makes sense in the way that not every bullet embedded into you is harmful and has to be removed.

**Comment by Fox-McCloud** [comment]
Heyo, I feel I can shed light on this.

At one point in time we had bullet embedding on Paradise---lemme just say it's well and truly awful--even with a minor engagement, if you get hit by a single bullet, it means you're now on a clock; it made being a wizard or other solitary, high visibility antag absolutely awful.

And that was with a *chance* based embedding system.

I do imagine this could be applied to a specific subtype of bullets that do very little damage, up front, but stick in their target until removed via surgery...but having this on most/all bullets AND it's guaranteed? That'll be horrific. Just having it on most bullet+is chance based will be frustrating enough in most instances.

I think the idea is good, but how it plays out will be extremely frustrating, unless it just applies to a small variety of bullets.

**Comment by carlarctg** [comment]
this sounds incredibly frustrating to play against as some antagonist that needs to be on the go, like a loud traitor that didn't powergame armor or a wizard, a changeling, or etcetera the list piles on

i'd also suggest making changeling fleshmend and/or regenerate  pop out embedded bullets, that'd be a fun small interaction

**Comment by ATH1909** [comment]
I agree with what the above two comments are saying; this sounds like a baaaaaaaaaaad idea.

**Comment by Timonkeyn** [comment]
Imagine getting lagged by getting hit with buckshot then getting lagged by the embed text

**Comment by carlarctg** [comment]
holy fuck so much what timonkeyn said

buckshots are already effectively a taser because of the huge amount of text they send you, instantly a huge 👎 because this'll double the lag they'll give you

**Comment by cacogen** [comment]
look if hideo kojima can make it work so can we. we should add a pause function so you can pull the bullets out mid-battle

**Comment by Fhaxaris** [comment]
Alright many of the comments are pointing out that this is a bad idea so I probably going to close this, but first let me clarify a few things.
> Buckshot text will get doubled and make you lag even more

The embedding uses an alert (the things that pop up on the top right side of your screen) )instead of using chat, so it won't actually lag you out. 
> Removing bullets requires surgery.

You can remove bullets without surgery, it just does some damage. I dropped the unsafe removal damage multiplier to .25 for embedded bullets.

>Make changeling-fleshmend remove embedded bullets

antag freeze and I am pretty sure it already does that

**Comment by Tharcoonvagh** [comment]
do you need to get the bullets out one by one? if yes , then sadly i am against this idea

**Comment by Fhaxaris** [comment]
>  do you need to get the bullets out one by one? if yes , then sadly i am against this idea

why is that a problem? It takes nine seconds. Also, I am pretty sure you can remove multiple bullets at a time if they are in different limbs. When I make it a percent chance to occur, you should really only have a max of 2 bullets in you at a time. If you have more than that, you are almost certainly already dead.

**Comment by Timonkeyn** [comment]
Embedded things still generate text independently

**Comment by Fhaxaris** [comment]
It generates one line of text every several seconds, after it is embedded, which gives no text. There is no text upon it embedding into you, only the alert.

**Comment by Timonkeyn** [comment]
Yes and every embedded thing displays 1 line, lagging you every several seconds

**Comment by Fhaxaris** [comment]
That's not how that works. Each imbedded object doesn't hurt at a set interval, it is random. The chance of more than two embedded objects hurting at the same is very low.

**Comment by carlarctg** [comment]
it takes nine seconds to remove each single bullet? that is way too much time jesus, please make it at most 4 seconds because if you get hit with a barrage of bullets it's going to take literal ages to removes all of them

**Comment by Timonkeyn** [comment]
>Also why the hell does printing a bunch of messages into chat lag the game, how has that not been fixed?

Sounds like a byond problem

**Comment by Difrit** [comment]
Ballistic weapons are already crazy good, buffing them in this manner, even with RNG embeds, will just make them even more of a mess. Not sure why this is merited other than "other servers have it".

**Comment by Alek2ander** [comment]
>You can remove bullets without surgery,

Doesn't feel right to have this. Removing bullets is a neat trope, but you'd really expect to need some tools to dig them out.

Could be fun to have poisoned bullets that actually deal damage over time and have to be removed, but for the rest it's probably overkill.

**Comment by Fhaxaris** [comment]
It looks like no one wants this, at least how I currently have it set up. I will redo this but make it for hollow point ammo, when the antag freeze is over.

**Pull request closed without merging**
