### PR TITLE
makes space named space

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

### CODE REVIEW

**Comment by xxalpha** [comment]
:-1:

**Comment by Niknakflak** [comment]
:-1:

**Comment by optimumtact** [comment]
What on earth could you possibly find offensive about this?

**Comment by Fox-McCloud** [comment]
:+1: 

Spess

**Comment by Supermichael777** [comment]
memes

**Comment by Thunder12345** [comment]
:+50:

**Comment by Shapsy** [comment]
Unnecessary :-1:

**Comment by Iamgoofball** [comment]
why

**Comment by Miauw62** [comment]
nah

**Comment by Miauw62** [comment]
you should probs be able to tell nonspace tiles from space tiles by hovering over them, its not like thats a fast process.

**Comment by optimumtact** [comment]
You'd be able to tell by the fact you weren't freezing or choking to death on the lack of air

**Pull request closed without merging**
