### PR TITLE
Adds the Stone Mask

### PR DESCRIPTION
**Pull request by Iamgoofball**
How do you do, fellow players? This is one of those hip and trendy japanese annie mays you players like, right?

todo: needs sprites

### CODE REVIEW

**Comment by KomradeSpectre** [comment]
Boyo, this better make vampirism happen when worn.

**Comment by Ordonis** [comment]
I thought it was a decent PR, but it was YOU! GOOFBALL!

**Comment by DaedalusGame** [comment]
👎 it's not jojo's bizarre gamemode

**Comment by Iamgoofball** [comment]
@KomradeSpectre it does, yes

**Comment by 81Denton** [comment]
IS THAT A

**Comment by Iamgoofball** [comment]
@DaedalusGame 
https://github.com/tgstation/tgstation/pull/36186

**Comment by SpinnerMaster** [comment]
I REJECT MY HUMANITY GOOFBALL

**Comment by Potato-Masher** [comment]
Your Carp Form training avails you nothing... It's USELESS USELESS USELESS USELESS USELESS USELESS USELEEEESS!

**Comment by megatiger78** [comment]
does it make holoparaistes stronger if the user wears the mask at least once?

**Comment by Repukan** [comment]
WRYYYYYYYYYYYYYYYYYYYY

**Comment by Doppeltongue** [comment]
Aren't the masks activated by getting blood on them, not just by wearing them? Also, don't they stab into the wearer's head?

**Comment by Shadowflame909** [comment]
This is a necropolis lavaland treasure when.

**Comment by Potato-Masher** [comment]
This as lavaland loot doesn't actually sound like a terribad idea.

**Comment by Potato-Masher** [comment]
@Xhuis 
firefox_2018-03-05_23-38-16

I have you caught red-handed. You best remove that thumbs down right now.

**Comment by Xhuis** [comment]
I'm not against the PR content, I'm against it because it's *another* nondescript goof PR with a body that doesn't explain anything beyond a no-effort meme. People shouldn't have to codedive to read what a PR does at a glance.

**Comment by jknpj** [comment]
Is this a port from https://github.com/vgstation-coders/vgstation13/pull/9639 ?

**Comment by 81Denton** [comment]
@jknpj That one looks actually fleshed out compared to this PR

**Comment by Probe1** [comment]
Savage

**Comment by Spaceinaba** [comment]
the standard stand should get time stop if the user activates the stone mask with that stand

**Comment by Kromgar** [comment]
ADD IT TO NECROPOLIS CHESTS FOR THE LOVE OF GOD

**Comment by Shadowlight213** [comment]
You thought that it was a normal pr, but it was I, GOOFBALL!

**Comment by KomradeSpectre** [comment]
I'll take a crack at making a sprite for it when I get home. No promises though.

**Comment by KomradeSpectre** [comment]
Also, here's a suggestion, whenever it activates, make the user fall to the ground, and have it display a death message to everyone around them, and make it upon examine show they're dead, for about 4 seconds or so. Or, if you don't want to make them fall to the ground, have them stand up unable to move for 4 seconds, but do the same thing I mentioned where they appear to be dead.

**Comment by Qbopper** [comment]
goof stop making prs with no explanation as to what they do because this could actually be a fucking neat pr except i didn't read the code and you honestly shouldn't have to read the code to figure out what the pr does

**Comment by improvedname** [comment]
add a vampire megafauna

**Comment by Iamgoofball** [comment]
My GPU is fucking dead, this is on hold indefinitely

**Pull request closed without merging**
