### PR TITLE
Makes Suicide work while knocked out/restrained, removes Ghost verb

### PR DESCRIPTION
**Pull request by Iamgoofball**
just use suicide

Fixes #17887

### CODE REVIEW

**Comment by Iamgoofball** [comment]
WHY

**Comment by Incoming5643** [comment]
This is technically a buff to liches

**Comment by WJohn** [comment]
Uh wait what how'd that get removed??

Anyway there's gameplay reasons to prevent suicide while restrained, such as keeping someone alive (traitor objectives), xenos, or conversions that take time. Ghosting at least keeps them useable.

**Comment by Iamgoofball** [comment]
@Incoming5643 i'll make Lich respect suicide then

**Comment by PKPenguin321** [comment]
the functionality of suiciding/ghosting is literally a non-issue

**Comment by TechnoAlchemisto** [comment]
Yeah this is pointless

**Comment by Iamgoofball** [comment]
its a redundancy issue

**Comment by PKPenguin321** [comment]
not really

**Comment by Shadowlight213** [comment]
Wjohn has a point. You could suicide when hugged but before you get implanted to cuck xenos out of a host.

**Comment by Dorsisdwarf** [comment]
It is impossible to keep people alive foricbly with this change.

**Comment by MrStonedOne** [comment]
No, I want to be able to leave a body without killing it.

And as an admin, it would make shit much easier if i didn't have people suiciding when they wanted to stop playing and i needed to replace them for whatever reason.

**Comment by Bawhoppen** [comment]
did goof's git ban on PR close policy get removed cause i almost feel bad for him in this case if not

but yes this is retarded goof and you should know better

**Comment by Cheridan** [comment]
What if we removed ghost but kept the restrained limitation on suicide?

if you somehow really don't want to play anymore but aren't in a position to kill yourself just log out, its not like it matters.

**Comment by Jordie0608** [comment]
I think both ghost and suicide are fine as they are; both this and #17887 seem to be trying to address a non-issue.

**Comment by lzimann** [comment]
jordie is right

**Comment by Iamgoofball** [comment]
eh, I made this PR because you mentioned in the other PR that having redundant verbs was dumb

**Comment by bgobandit** [comment]
this is a bad idea

**Comment by MrStonedOne** [comment]
But it's not redundant. They do two different things, and that distinction is important.

**Comment by MrStonedOne** [comment]
As an admin, I don't see the point of making it so somebody can't abandon their body without killing it. It makes it much fucking easier for me to replace them if they keep the body alive.

When players ahelp that they need to leave an important role, they almost always ghost immediately after sending that ahelp.

So please look byond the most common use case that you see for ghost and suicide. ghost is not the suicide of "restrained", ghosting also leaves the body alive and gives it a special message. Its more akin to the ooc way of abandoning the round, with suicide being the ic way. Because one is easier for an admin to work with if they need to replace the person controlling the body, we need both.

**Pull request closed without merging**
