### PR TITLE
Fixes Donut Whiteship

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This PR is made to do bare bones fixing to the donutstation whiteship so that it is actually functional. It adds a pacman and 10 uranium so that you can actually generate power, a set of titanium so you can actually repair the shuttle walls, a few lattices to denote the edges of the ship area (which was previously unclear), some cabling to wire up power, and an air canister to fill the space with oxygen once you fix the ship.

**If anyone thinks this goes too far as a fix let me know and I'll tone it back.**

## Why It's Good For The Game

Since a whiteship for the map is spawned based on the pool of whiteships, I think it's good to make sure each of those whiteships are at least functional (albiet with a little bit of work to make them so). As it stands with the odds and complicated materials required, only people who are deliberately powergaming space exploration and very competent may gather the necessary materials beforehand, and I think the purpose of the whiteships are to find them, fix them, and take them back to the station where you can do better repairs. Newer players out exploring space won't understand what materials they'd need and will likely be frustrated and think it's their fault since every other ship is able to be flown. Also, not understanding the boundaries of the shuttle will create unintended frustration for any level of player, as work could be ruined when the shuttle changes location.

## Changelog
:cl:

fix: Makes the Donutstation Whiteship functional.

/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this is not a fix, you're adding a bunch of stuff to this shuttle.

leave it until after the freeze

**Comment by Dennok** [comment]
its time?

**Comment by optimumtact** [comment]
they can make a new pr any time if they want

**Comment by Cartographer-D** [comment]
> 
> 
> its time?

https://github.com/tgstation/tgstation/pull/55262
Already made and merged.

**Pull request closed without merging**
