### PR TITLE
makes tunguska meteor description more accurate

### PR DESCRIPTION
**Pull request by ghost**
if you saw a giant meteor near your face, wouldn't you be thinking "OH GOD FUCK SHIT SHIT FUCK" too?

:cl: More Robust Than You
tweak: The tunguska meteor's description is more accurate now.
/:cl:

### CODE REVIEW

**Comment by Xhuis** [comment]
The PR title is misleading, this is not a fix.

**Comment by DoctoreMad** [comment]
Okay nevermind stop making meme PRs

**Comment by MoreRobustThanYou** [comment]
@DoctoreMad 
if you saw a giant meteor near your face, wouldn't you be thinking "OH GOD FUCK SHIT SHIT FUCK" too?

**Comment by DoctoreMad** [comment]
Descriptions aren't what you're thinking, unless this game is actually marketed towards passive aggressive 14 year olds and descriptions are in reflection of that.
Even then that's a really boring description.

**Comment by lzimann** [comment]
don't have time for this crap

**Pull request closed without merging**
