### PR TITLE
Removes suicide check from positronic brains

### PR DESCRIPTION
**Pull request by ghost**
# About The Pull Request

This removes the suicide check from positronic brains.

# Why It's Good For The Game

There seems to be 2 arguments for why suicide should forbid ghost roles:
1. "If they suicided they didn't want to play"
2. "antag rolling"

So let's look at each.

And an addendum on scope: This is meant only to apply to ghost roles (and new characters from said roles); I do not wish to change that people are not allowed back onto the same character they suicided on.

## "Suiciders left the round of their own choice and shouldn't be allowed back in"

There are many, many ways in this game to end up with a character in a state that's nearly/effectively unplayable, even if the controlling player doesn't truly wish to completely leave. Some things can be resolved with competent medical or science staff, but competent staff are not always available in a round or might be beleaguered by round events.

Then there are a number of conditions/states which the game provides no path to resolve (save drastic measures like abandoning the character/body, of course).

Or one might have simply become stuck in a place where rescue is unlikely.

## Antag rolling

The problem here is this code does not particularly target antag rollers. It paints such a broad brush that it simply catches everyone whom might not know "No no, you have to **ghost** here, not suicide". Even if an antag roller is stopped once, they'll easily bypass it next time through the many, many means open to them - and if 'ghost' is made effectively the same as 'suicide', it simply punishes people who got stuck or similar even more.

Because of the wide range of means to kill oneself on a normal character, to effectively stop antag rolling requires discerning intent through context and patterns of one's actions. This might not be possible in code until General Intelligence is a solved problem, and if it is possible, this doesn't do it. It's a shotgun that kills everyone in the room and if there happened to be an antag roller there, well, even a stopped clock is right twice a day.

And then, of course, that the code was broken for so long would seem to indicate it's not done that much.

## Practical Impact and Design Philosophy

Just from my personal observations, even wanting into a posibrain is a niche thing usually only taken by a small number of the same players round-to-round. In practice, whether this PR is merged or not likely won't have a great impact on the game. But that could change if the philosophy behind this check is applied to a wider number of things.

If someone wants to die, it's not hard. Walk out an airlock. Into the supermatter. Blob, Xenos, or some other hazard present? Walk towards them. Step in front of a shuttle. Turn on internals and wait a bit. Countless other ways. Except, perhaps, if a character is disabled or crippled or stuck, in which case use of a verb may be necessary.

In other games with much narrower sets of mechanics, it may be possible to close certain paths on the assumption it would mostly be used for bad faith reasons. In SS13, the sheer number of ways in which a good faith character be "screwed" but not quite killed off, and which a bad faith actor can find to kill themselves while bypassing restrictions placed on verbs, means that I think this code's design philosophy is harmful to the game and its good faith players.

# Changelog

:cl:
del: Positronic brains no longer check for suicide verb use.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
I think the reason this is in is just because someone could theoretically "optimize" robotics by suiciding and then going into a posibrain instead of getting MMI'ed, but like, they can just die in other ways...

**Comment by YehnBeep** [comment]
> I think the reason this is in is just because someone could theoretically "optimize" robotics by suiciding and then going into a posibrain instead of getting MMI'ed, but like, they can just die in other ways...

This is mostly in response to a comment from the... head coder? So the bugfix can go in, and then they can decide "Now that it's working do we actually want it."

image

**Comment by optimumtact** [comment]
You've only removed the check from one thing, I think you misunderstood that was I was saying is that the position of "someone voluntarily suiciding is punished by preventing access to returning to the game" has been the codebase standard and that's what you should be changing or seeking to change.

Not that positronic brains specifically should not have the limitation.

**Comment by YehnBeep** [comment]
> You've only removed the check from one thing, I think you misunderstood that was I was saying is that the position of "someone voluntarily suiciding is punished by preventing access to returning to the game" has been the codebase standard and that's what you should be changing or seeking to change.
> 
> Not that positronic brains specifically should not have the limitation.

What other ghost roles have this limitation?

**Comment by YehnBeep** [comment]
> I did a quick search through all instances of TRAIT_SUICIDED and from what I found this is the ONLY ghost role you cannot get after suiciding.

Thank you for the assistance. If there's others later found, I'm willing to attempt to add them to this PR.

----

As to the design philosophy side, I very intentionally framed my arguments to not apply to only positronic brains, so I will probably leave them as is unless I find new information or realize I've overlooked something.

**Comment by optimumtact** [comment]
From memory it prevents cloning & revival surgery

**Comment by JohnFulpWillard** [comment]
I think one of the reasons supporting it is because people would prefer to suicide and take a posibrain than wait in surgery for debraining.

It's not too big an issue but if it's really necessary, preventing people from entering a posibrain for a certain period after their death would be good and catch the cases like manually killing yourself, would be way better than how it is now.

**Comment by optimumtact** [comment]
I'm saying if we remove it from this, we may as well remove it from those other options, the original intent was to make suicide irreversible, but that is no longer true.

**Comment by YehnBeep** [comment]
Ok hold on a moment. The reason I'm focusing on ghost roles is because... this is principally a ghost role? Not that I don't see JohnFulpWillard's point but before we get to that.

Cloning, as I understand it, was removed from the game before I started playing and I definitely haven't experienced it. But for reviving - I think it is far to say that a ghost role that starts you as a new character and warns you beforehand that "all past lives are forgotten" is not the same as reviving a suicided character?

My intent hasn't been to argue that suicided characters should now be revivable, on that same character. It is going into a new character/ghost role, that's where I think a suicide-verb-block would be harmful.

**Comment by optimumtact** [comment]
cloning is pod cloning in this context which is still a thing

**Comment by YehnBeep** [comment]
Ok, well, maybe I approached this from the wrong angle - maybe it should be a consistency issue instead of a design philosophy thing?

As I've understood it, a regular revival or something like botany's pod-person cloning is continuity of the same character. If someone suicides in that context, I think blocking revival is fair and probably even good - there I think it's fair to say using suicide indicates an intent to not return. In these cases, of course, ghosting also means you can't get back to the same character.

But going into a positronic brain, like other ghost roles, I've understood that to be a new character/continuity. So, maybe instead of approaching it as "suicide block is bad for ghost roles", I need to approach it from "positronic brains should be treated as a ghost role since they're not revival of a pre-existing character"? (At least, that's what the "You can no longer be revived, and all past lives will be forgotten!" prompt seemed to indicate to me?)

Am I closer to what the issue is with posibrains and the suicide verb here?

**Comment by zxaber** [comment]
> Positronic brains I suspect are tagged with this because borging was also prevented for suiciders from what I recall, although I haven't checked if that's true or not.

The suicide block for posibrains was introduced in #41336. Though it's listed as a fix, so perhaps it had been around beforehand and I'd never known it was intended.


It has been a long while, but IIRC you had defended the above PR in Coding-General on the Discord, with I believe the eventual intention that *all* ghost roles gain the block. That was never championed by anyone, though, so Posis are the only ghost role that rejects players who suicided in their prior life.

**Comment by Watermelon914** [comment]
> I'm saying if we remove it from this, we may as well remove it from those other options, the original intent was to make suicide irreversible, but that is no longer true.

Positronic brains are a new life though, I think it's more fair to consider them as a ghost role. The idea of suicide being irreversible can still exist whilst still letting you enter into a new life.

**Comment by ATH1909** [comment]
> I'm saying if we remove it from this, we may as well remove it from those other options, the original intent was to make suicide irreversible, but that is no longer true.

the way I always saw it was that suicide makes a *character* unrevivable. posibrains and ghost roles are entirely separate characters with no memories of your actions as other characters, so they shouldn't be blocked.

**Comment by YehnBeep** [comment]
Ok, so, seems the conversation's slowed here, so I'm going to mark this as ready for review with the following notes:

1. The top-post PR arguments are meant to apply to ghost-roles specifically blocking suicides. **Allowing people back on to the same character they suicided on is not something I wish to try to change.** It turns out the only ghost role that does this is posibrains it seems, but I would use the same argument if other ghost roles starting doing it.
3. Concerning a timer: I can see how like a 5 or 10 minute restriction on positronic brain entering would be a good idea to add a slight incentive to use medical/sci for brain removal and MMI. However, this isn't something I know how to do, and does still have the problem that ghosting would bypass it. So I'll leave this as is; if it's a hard requirement someone else will have to take this on.

Thank you for considering.

**Comment by jughu** [comment]
local people get role dont get anrag suicide check ai malf? spam auto sniffer prpbaly why the posibrains have those limitation

**Comment by YehnBeep** [comment]
> local people get role dont get anrag suicide check ai malf? spam auto sniffer prpbaly why the posibrains have those limitation

This is an argument addressed in the PR's main body. In short, I don't think punishing many good faith players is worth occasionally catching an antag roller that will then realize next time they'll can ghost or just walk out an airlock to bypass the restriction.

**Comment by jughu** [comment]
in the end its really a admin problem but suiciding is more obvious then jumping out of the airlock

**Comment by YehnBeep** [comment]
> in the end its really a admin problem but suiciding is more obvious then jumping out of the airlock

That's the core of it.

If someone happens to die a lot (by whatever means) when they don't get a roundstart/latejoin antag. And then just so happens to play posibrains/silicons _only_ when they're antags (or only goes for other ghost antags). An admin can look at this sort of situation, make the judgment call that this player's intent isn't good faith, and then apply an antag ban/silicon ban/whatever else is needed.

It's the sort of thing that seems hard to delegate to code.

**Pull request merged**
