### PR TITLE
Fixes Anime Names

### LINKED ISSUE #18655: Japanese anime button names are broke.
The chan and san part of the name isn't added after the dash, leaving the name looking like this
Monroe-

@KorPhaeron

### PR DESCRIPTION
**Pull request by RemieRichards**
casually forgetting that gender defines are numbers.

Fixes #18655

### CODE REVIEW

**Comment by Thunder12345** [comment]
What happens to mononyms, though?

**Comment by RemieRichards** [comment]
Those people are hitler.

**Comment by Cheridan** [comment]
ARIGATO REMIE-SEMPAI UGUUUUUUUU :jp:

**Comment by Niknakflak** [comment]
Good job remie-chan

**Pull request merged**
