### PR TITLE
Port salute emote sound from CM SS13

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
This adds a crisp sound to the salute emote that is from the Colonial Marines server.

## Why It's Good For The Game
Mah Immersion!

## Changelog
:cl: timothymtorres, Rahlzel
sound: Port salute emote sound from Colonial Marines SS13 attributed to Rahlzel
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
what license is it

**Comment by timothymtorres** [comment]
chrome_jC580SYZwO

**Comment by Fikou** [comment]
can you check if its otherwise indicated

**Comment by timothymtorres** [comment]
I already did before I made this PR and I saw no further attribution, even when I dived into the commit that added the sound.

**Comment by Fikou** [comment]
ok

**Comment by JohnFulpWillard** [comment]
https://creativecommons.org/licenses/by-sa/3.0/

You gotta give credit to the original authors especially in changelog please

**Comment by timothymtorres** [comment]
https://github.com/rahlzel was the contributor who merged the commit adding the sound back in June 2016 in https://gitlab.com/cmdevs/colonial-warfare/-/commit/7fc3e306c13850c0e5a77175870829d039b105d2

**Comment by DrDiasyl** [comment]
MilRP on TG?? SIR YES SIR!!

**Pull request merged**
