### PR TITLE
Adds new plasmaman internals that can be filled with plasma sheets (Based on #63383)

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
Adds advanced plasmaman internals based on the general idea in #63383, they can be filled by clicking on them with plasma sheets, with the following deviations from the original PR:
Instead of spawning a new tank, the tank is refilled, and any old gas in it is kept.
They are now actually creatable in-game, and also require research (Advanced Plasma Technology) as suggested by EricZilla.
Adds new (coder)sprites for them so that they are differentiable visually.

## Why It's Good For The Game
With longer rounds becoming more common, removes the need for plasmamen to visit atmos and ask an alive atmos tech (who might not even exist at times).

## Changelog

:cl:
expansion: Adds advanced plasmaman belt tanks that can be automatically refilled with plasma sheets! Printable at protolathes after researching advanced plasma technology.
imageadd: Adds sprites for advanced plasmaman belt tanks to make them differentiable from regular plasmaman belt tanks.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
450 moles at room temperature will lead to a pressure far higher than the target pressure of the tank, so it will never need to consume more than 1 plasma sheet I believe. Maybe the unused plasma could go in the air or something so it doesn't get wasted.

**Comment by RandomGamer123** [comment]
> 450 moles at room temperature will lead to a pressure far higher than the target pressure of the tank, so it will never need to consume more than 1 plasma sheet I believe. Maybe the unused plasma could go in the air or something so it doesn't get wasted.

Yeah in the vast majority of cases that's what happens, it just rounds up to the nearest sheet so 1 sheet will be consumed anyways, since well having plasma in the air after using this seems very harmful.

**Comment by LemonInTheDark** [comment]
> With longer rounds becoming more common, removes the need for plasmamen to visit atmos and ask an alive atmos tech (who might not even exist at times).

I don't think this is a bad thing for plasmamen to need to do. Could you explain why you feel differently?
Especially since this is basically 1 sheet of plasma for a full tank of gas, which is insane

**Comment by timothymtorres** [comment]
> I don't think this is a bad thing for plasmamen to need to do. Could you explain why you feel differently? 

You aren't guaranteed to have miners either.  There are only a few finite places on the station where plasma bars spawn.  The same with plasma air tanks.  Having more options to choose from is ideal.

> Especially since this is basically 1 sheet of plasma for a full tank of gas, which is insane

Agree.  Would recommend to just use the amount from when a solid bar of plasma gets gasified.  If that seems like it's too much, I'd then just lower it and deem the internals canister to have an inefficient method of converting plasma into gas.  You could even make this a unlockable item from R&D.

**Comment by LemonInTheDark** [comment]
> You aren't guaranteed to have miners either. There are only a few finite places on the station where plasma bars spawn. The same with plasma air tanks. Having more options to choose from is ideal.

Sure, it makes it easier, but there's been no argument for why that's a good thing. It's meant to be a pain, even if we give you two of the things. A buff with no discussion of why is just powercreep

**Comment by Pickle-Coding** [comment]
What if it was a greytider item that requires tider crafting and releases the unused plasma into the air (with a chance to spark and add firestacks to the plasmaman if it's refilled while the plasmaman is using the internals).

**Comment by RandomGamer123** [comment]
> > You aren't guaranteed to have miners either. There are only a few finite places on the station where plasma bars spawn. The same with plasma air tanks. Having more options to choose from is ideal.
> 
>
> Sure, it makes it easier, but there's been no argument for why that's a good thing. It's meant to be a pain, even if we give you two of the things. A buff with no discussion of why is just powercreep

I'd be fine with reducing it to a punitive amount to encourage going (or breaking into) atmos, but like even breaking into atmos isnt hard, but just an annoyance, and I see this as a QOL change for the most part and not a buff.

**Comment by LemonInTheDark** [comment]
Sure, but it's an annoyance that's intended, and if you've not done it hundreds of times it's interesting, for you and the engis.
Anything interesting will inevitably devolve into annoyance given enough repetition

**Comment by Unstagrav** [comment]
I’m commander Shepard and this is my favorite PR on the citadel 👍😍🗿

i don’t know what power creep is but nobody has bombed me with a plasmeme internals yet sooooo…????  maybe it’s not a power thing and just a quality of life update to make job simulator less annoying

10/10 pr would merge rght this second if I could

**Comment by RandomGamer123** [comment]
> Sure, but it's an annoyance that's intended, and if you've not done it hundreds of times it's interesting, for you and the engis. Anything interesting will inevitably devolve into annoyance given enough repetition

I would say it gets annoying quite a bit earlier than you say. From personal experience, most of the time atmos techs are either doing their own project or have disappeared from the engineering department entirely by the time refilling becomes an issue. In the former case the atmos techs are usually helpful, however although this does lead to player interaction, which is good, it's repetitive player interaction that makes both players have to stop what they are doing to fulfill a mundane task. In the latter case its extremely difficult to get ahold of one and I would consider hacking into it without anyone there to stop you and getting a pump up to get annoying quickly (and there's also another issue if you aren't fluent in how pipes work).

**Review by Twaticus — CHANGES_REQUESTED** [review]
icons/obj/tank.dmi - holder_oxygen_fr has a stray pixel
icons/mob/inhands/equipment/tanks_lefthand+tanks_righthand - plasmaman_tank_belt_advanced sprites are using the wrong color icons

**Comment by RandomGamer123** [comment]
> icons/obj/tank.dmi - holder_oxygen_fr has a stray pixel icons/mob/inhands/equipment/tanks_lefthand+tanks_righthand - plasmaman_tank_belt_advanced sprites are using the wrong color icons

Oops, yeah I'm not really that fluent in spriting things

**Review by Twaticus — CHANGES_REQUESTED** [review]
inhands/equipment/tanks_lefthand.dmi, plasmaman_tank_belt_advanced - still has the wrong icon

**Comment by LemonInTheDark** [comment]
I still don't want this, especially given the long lead time on it

**Review by Twaticus — APPROVED** [review]

**Comment by RandomGamer123** [comment]
Bump, also anyone with opinions that haven't already been mentioned feel free to raise a new point.

**Comment by LemonInTheDark** [comment]
Should have closed this earlier. I don't want to reduce the troubles of being a plasmaman any more then we already have, and this does that significantly

**Pull request closed without merging**
