### PR TITLE
Fixes inaccessible coffee and cigarettes in deltastation's engineering break room.

### PR DESCRIPTION
**Pull request by TheWolfbringer**
This is my first PR, sorry if there's anything wrong! 
## About The Pull Request
Moves the coffee machine and the cigarette and coffee spawners so you can reach them all.

## Why It's Good For The Game
Bugfix
## Changelog
:cl:

fix: You can now access the coffee beans and cigarettes at Deltastation's Engineering breakroom

/:cl:

### CODE REVIEW

**Review by san7890 — CHANGES_REQUESTED** [review]
Thanks for submitting your contribution. However, I reviewed the MapDiffBot Renders and noticed the following:

image

Your changes (dumping everything) onto a single tile looks very ugly and disorganized. I believe  a more appropriate fix would be to just shuffle around all of the items on the table (or rework the breakroom a bit) in order to make everything fit. You can have multiple things on the same table, but right now it just really does look like a mess. It shouldn't be too hard to accomplish, but I do believe it is necessary to do in order for this to be a good fix without introducing more issues of its own.

I'm going to mark your PR as a Draft for record-keeping purposes. Feel free to mark it as "Ready for Review" when this has been addressed. Everything else about your PR looks good, great job on that.

**Comment by TheWolfbringer** [comment]
> Thanks for submitting your contribution. However, I reviewed the MapDiffBot Renders and noticed the following:
> 
> image
> 
> Your changes (dumping everything) onto a single tile looks very ugly and disorganized. I believe a more appropriate fix would be to just shuffle around all of the items on the table (or rework the breakroom a bit) in order to make everything fit. You can have multiple things on the same table, but right now it just really does look like a mess. It shouldn't be too hard to accomplish, but I do believe it is necessary to do in order for this to be a good fix without introducing more issues of its own.
> 
> I'm going to mark your PR as a Draft for record-keeping purposes. Feel free to mark it as "Ready for Review" when this has been addressed. Everything else about your PR looks good, great job on that.

okay I'll go work on that

**Comment by TheWolfbringer** [comment]
> You don't need to keep merging master. In fact, for a mapping PR, it's probably detrimental to do that, since you won't be able to have the git hooks.
> 
> I also see that you're using Github.com to make this PR. I strongly encourage you follow the guide to mapping in order to know how to Git a bit better for future PRs: https://hackmd.io/@tgstation/SyVma0dS5

strongDMM crashes when I try to load anything so I am unable to use it

**Comment by san7890** [comment]
I would recommend trying out FastDMM then: https://fastdmm2.ss13.io/

**Comment by TheWolfbringer** [comment]
> I would recommend trying out FastDMM then: https://fastdmm2.ss13.io/

It is what I used to make this change!

**Pull request merged**
