### PR TITLE
No stray 0 in crayon ui

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Fixes a stray 0 in the crayon ui

## Why It's Good For The Game

There shouldn't be a stray 0 in the crayon ui

## Changelog
:cl:
fix: Removes a stray 0 in the crayon ui
/:cl:

Thank you skoglol for informing me of a stray 0 in the crayon ui

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Is 0 being considered non-falsey here or something?

**Comment by actioninja** [comment]
it's actually that the value is `"0"`. `"0"` seems to be considered falsey but JSX also seems to want to output the string to the dom. `"0"` when negated is implicitly converted to boolean true, negating again inverts that to a false.
Just your normal JS nonsense in other words.

**Comment by PKPenguin321** [comment]
>JS nonsense
That is absolutely insane

**Comment by SpaceManiac** [comment]
real explanation has nothing to do with `"0"`:

* `0 && <Stuff>` evaluates to `0` which is rendered as a number because you gotta be able to print the number 0
* `!!0 && <Stuff>` evaluates to `false && <Stuff>` evaluates to `false` which is rendered as nothing [specifically to enable this use case](https://react-cn.github.io/react/tips/false-in-jsx.html)

**Review by SpaceManiac — APPROVED** [review]

**Comment by actioninja** [comment]
This fix does work but it works for a completely different reason than I explained because I was understanding how this worked completely wrong, spacemaniac got it. I was misunderstanding the way that boolean expressions work in general and I actually learned something about most languages from this.

**Pull request merged**
