### PR TITLE
New positive event: Alien Blessings

### PR DESCRIPTION
**Pull request by tralezab**
:cl:
add: New rare event: Alien Blessings
/:cl:

Only merge this after #41724, it uses applying luck. WIP WIP WIP!

Why? The more events that go on, the less same-y rounds will be. coiax is adding a really cool luck system and I wanted to add some incentive to get the lucky trait.

What is it? A rare event that gives you a skill based on your job. They are not combat based, except maybe something for sec. I'll have to think about what they should get, I already made some combat based mistakes in this pr already.

### CODE REVIEW

**Comment by tralezab** [comment]
@4dplanner :(

**Comment by tralezab** [comment]
I had to think about the balance on this a lot, and I didn't want this to be something where "oop i'm lucky time to run away into oblivion and radio this!" and I definitely didn't want "i'm the chosen one but it really doesn't mean anything at all" I wanted it to be more of a "stand and fight at 30 health" thing. You can't really plan for it since it's really rare and you can easily waste it, Maybe I could add stun immunity for a small amount of time to allow for that to happen.

Also if you have good ideas for positive events you should totally tell me i'd be happy to hear it, it's really hard to come up with positive events. My first iteration was an odd message in your head to build something in maint which would give you an item/a spell, etc, and it had a 50/50 to give you traitor before announcing to the captain who was picked so the station would try to stop you. It didn't really work out at all.

**Comment by davethwave** [comment]
If your sec, your not supposed to harmbaton someone, if they are a traitor you won't have a problem, if they are a assistant or something, then just harmbaton him again and he will get stunned once more. Also harmbatoning someone to 5 health would usually mean your killing them wouldn't it?

**Comment by Therapist1** [comment]
I don’t think coming back from the brink of death is a very good idea, though smaller but still useful benefits will always be appreciated. Say, engineers could charge an APC by ‘rerouting’ emergency power (up to a point), assistants become able to tell the use of wires, doctors gain some form of advaced CPR that’s able to heal burn/brute, so they can get patients out of crit, command staff increase the mood of those they’re around through leadership. Just think of little things each job would enjoy to have.

**Comment by tralezab** [comment]
@Therapist1 i'd be happy to change it to a department based benefit, that sounds kinda cool. could you expand on your ideas a little bit and i'll think about if it's worth dropping this idea a bit more

@davethwave I considered adding stun absorbtion because of what 4dplanner said, i'm gonna commit that since it seems to be a reoccurring issue. I want this to be meaningful

**Comment by anconfuzedrock** [comment]
no matter how common or rare this is, this is going to be that thing that very rarely happens and either the person who gets it procced doesn't notice it at all, or someone who did nothing wrong is confused and incinerated because they lost a fight that they couldn't have prepared for, and the victor literally hadn't. This is like randomly electrocuting someone as an event, only even more frustrating for the loser.

**Comment by tralezab** [comment]
well. lets try going for Therapist1's idea. It's kinda cooler anyways

**Comment by Jalleo** [comment]
I got a idea. Lucky tools (all tools on this person when given this trait gain a very small improvement and get a sparkly overlay and name addition saying shiny or whatever. Its a nice but potentially irrelevant lucky chance.

**Comment by tralezab** [comment]
I'm going by departments, right now engineers would be able to reroute power. I'm not entirely sure what that entails beyond just giving it some emergency charge. Emagging? After some set time, the APC breaks? 🤔

**Comment by ExcessiveUseOfCobblestone** [comment]
I'd rather something a bit more mechanically interesting than *heh nothing personal kiddo* and the PR that this banked off of has been closed.

**Pull request closed without merging**
