### PR TITLE
Changes Loader Mod core text to include "non-airtight"

### LINKED ISSUE #64681: The QM's Loader MODsuit has nothing in its description to let the player know it isn't spaceworthy.
As a player who didn't already know, I had no reason whatsoever to believe it wasn't spaceworthy.

Non-loader modsuits are all spaceworthy.

Modsuits replaced hardsuits, which were all spaceworthy.

Only this one isn't. Just this one kind.  And its description leaves out that little detail.  In fact, it says, "Protects you from various environments."  How would someone not think that includes space?

A user should not have to learn these things only by word of mouth or trial and error. It should be documented.

FIX:

Write that it's not spaceworthy in its description, preferably in all caps.

### PR DESCRIPTION
**Pull request by Dr-Pope**
## About The Pull Request

Changes the Loader modcore text to better explain that it is not airtight or a sealed environment. 
fixes https://github.com/tgstation/tgstation/issues/64681

## Why It's Good For The Game

Makes it so it clearly states its not airtight and can't be used like all the other mod suits. I am not sure if this would be considered QOL so I just went with spellcheck

## Changelog

:cl:
spellcheck: Makes it so the loader modsuit says it is not airtight with examined.

/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
put "fixes #64681" to automatically close the issue when its merged
also im not sure on the grammar?

**Comment by Dr-Pope** [comment]
> im not sure on the grammar?
I can give you a couple different variations on how to word it.

**Comment by Dr-Pope** [comment]
I can give you a couple different variations on how to word it.

**Comment by Dr-Pope** [comment]
"An unsealed experimental motorized harness manufactured by Scarborough Arms for quick and efficient munition supplies"Instead we could do that, I think it sounds more coherent.

**Pull request merged**
