### PR TITLE
Fixes the broken Badminka Vodka sprite

### PR DESCRIPTION
**Pull request by TheVekter**
Also moves the hidden bottle somewhere more... hidden.

No bug report for this.

### CODE REVIEW

**Comment by Chocobro** [comment]
it was broken?

**Comment by Ikarrus** [comment]
Why not just add the bottle to the random loot table?

**Comment by TheVekter** [comment]
Because I have no idea how to do that! Also the loot table can put it
somewhere in plain view and I want it to be something special.

**Comment by Ikarrus** [comment]
I'm not sure how special it is if anyone can memorize where it spawns every round and make a beeline to it.

And loot tables are easy! Just ask coderbus!

**Comment by dannno** [comment]
>I'm not sure how special it is if anyone can memorize where it spawns every round and make a beeline to it.

yeah this

**Comment by pudl** [comment]
metacide hid his Meta-Cider pretty well and no one beelined to it

**Comment by Cheridan** [comment]
Well I'm gonna go ahead and merge this since the sprite needs to be fixed. Loot table stuff can be discussed in another PR.

**Pull request merged**
