### PR TITLE
Disallow doing surgery on yourself

### PR DESCRIPTION
**Pull request by MrPerson**
This doesn't solve the fact you can lie down with stuff in your hand (which isn't a bug imo) but it does stop people from cutting their brains out or giving themselves plastic surgery.
Fixes #4001

### CODE REVIEW

**Comment by Boredone** [comment]
How possible would it be to make doing surgery on yourself harder, and cause brute damage, succeed or fail instead?

**Comment by Supermichael777** [comment]
WHAT NO SOLO ROBOTICS AUGMENTS ARE A FEATURE DON'T TAKE THIS AWAY FROM US.
self-surgery is already dangerous because of the massive bleeding lack of care.

**Comment by optimumtact** [comment]
:trumpet: :skull:

**Comment by Incoming5643** [comment]
Honestly I like the bug better than the fix

**Comment by RemieRichards** [comment]
Yeah I'm a fan of this "bug", since all the valuable surgeries have downsides in large amounts of brute damage, so there's already risks to it.

**Comment by Marflowerose** [comment]
How is self-surgery a bug? People have done it legit in real life even before space stations and survived. You could make it mildly more difficult by fainting occasionally if not using morphine or other anesthetic.

**Comment by MrPerson** [comment]
Self surgery defeats the entire purpose of surgery, which is that you need to trust somebody else to do it. Frankly we need more things in the game that force you to involve other people so at to discourage lone wolf powergaming behavior.

**Comment by Marflowerose** [comment]
Then add the failchance and fainting to make it slower. Self-augmenting is already much slower than regular. That way people are greatly discouraged from doing self-surgery but it would still be an option in a pinch.

**Comment by AlexCrimson** [comment]
Yeah i hate seeing a Roboticist turn himself into an augmented human. Always seemed like powergaming to me.

**Comment by MrPerson** [comment]
Slower means people still do it, they just wait longer. Unless we're talking very slow, people will wait it out instead of risking their own life.

**Comment by Lumipharon** [comment]
What are you people talking about? The damage from self surgery isn't a down side at all (talking specifically about augmentation, since other surgery is very rare, an isn't done 6 times in a row), since the augmented part completely clears the damage.

**Comment by Incoming5643** [comment]
I was thinking of adding persistent bleeding to surgery (with it getting worse with failures) that would make (self)surgery outside of an area with access to blood a risky move. I think that it'd be a better solution to this because it'd still allow for desperation self surgery with even a lucky run dipping a player into "persistent 20 oxygen damage" land without letting people go nuts with full body auging without at least medbay support. Plus people would finally do the cauterize step at the end.

**Comment by RemieRichards** [comment]
@Lumipharon given that the method of fixing the damage is either a medkit or applying the limb (based on surgeries), and depending on how you do it, you'll have to perform the glitch with the rolledbed, which means that for some surgeries, if you weren't 100% health, you're literally risking death.

**Comment by Steelpoint** [comment]
What Remie said, if your not at 100% health you'll go into crit if you preform self surgery, so if RNG decides to deal damage to you then you'll have to abort and heal up.

I support being able to do surgery on yourself as I think its a unique and interesting aspect. However it may not be bad to make it slower/harder to preform self surgery.

**Comment by Miauw62** [comment]
I agree with MrPerson's view, to be honest. That said, if you're doing
surgery and you take off a headset you'll probably get robusted already.

I suggest increasing the failure chance if the subject you are operating on
is conscious.
Op 26-mrt.-2015 10:13 schreef "Steelpoint" <notifications@github.com>:

**Comment by optimumtact** [comment]
I suggest we fix the bug now and someone can work on a proper self surgery implementation and get in included?

**Comment by MrPerson** [comment]
If people want self-surgery, that's fine. Just close this pr and the referenced issue and make a new issue detailing what exactly should happen with buckling and item dropping and holding items while lying down. I would also suggest allowing some surgeries to be done on yourself and some can't.

I was going to do that as part of this PR but it was fairly complicated and it needs more work than a day to do.

**Comment by PKPenguin321** [comment]
just dropping in to say i like self-surgery as is, too

**Comment by ACCount12** [comment]
:-1: Stop removing fun, it's not much left.

**Comment by palpatine213** [comment]
Keep self surgery in please. sometimes you don't have the luxury of a second person to perform surgery on you like for example, a traitor or DA performing facial surgery to throw off their pursuers.

**Comment by hornygranny** [comment]
@Cheridan and I agree that there are some surgeries (appendix removal, implant removal) that should be possible to do on yourself, but in general no.

**Comment by Cheridan** [comment]
I think that self-surgery should be limited on certain cases. For example, augmenting your own leg makes sense but augmenting your own head (how do you see??) or arm (good luck performing surgery with one hand) do not.

**Pull request merged**
