### PR TITLE
[READY] New reality fracture (Heretic influences) textures.

### PR DESCRIPTION
**Pull request by Nebulacrity**
## About The Pull Request

Old:
ss13RealityFracture
New:
ss13RealitySmash
ss13PiercedIllusion

## Why It's Good For The Game
It looks better.

## Changelog
:cl:
imageadd: Updated the reality fractures (Heretic influences) to have nicer sprites.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I wanna touch it.

**Comment by Nebulacrity** [comment]
You have lost an arm!

What else you wish to do?

**Comment by Tharcoonvagh** [comment]
Hit it with a toolbox

**Comment by Nebulacrity** [comment]
You have lost the toolbox!
You have lost an arm!

What else you wish to do?

**Review by Twaticus — APPROVED** [review]
hell yeah

**Comment by Tharcoonvagh** [comment]
Go to robotics and replace your arms with a pair of chainsaws, then hit it again with both arms

**Comment by Nebulacrity** [comment]
You have died due to staring at it too long!

Game over!

**Pull request merged**
