### PR TITLE
Lowers heater and freezer power usage

### LINKED ISSUE #11534: Misc Science was using 400,000 watts I think because i ugpraded the cooler and  freezer
image

### PR DESCRIPTION
**Pull request by ghost**
Currently freezers and heaters can increase the power usage to insane numbers with upgraded parts, draining power from a room completely. I've seen medbay lose power on different stations just because the freezer was upgraded and no one knew the reason for it. 

This was originally left to make freezers as ghetto power sinks but I've never heard anyone use them as such, and even then they only eat power from the freezer's room's APC giving unexplained problems to the users. This same reason prevents freezers and heaters to be even used properly with best parts as all they do is eat power very fast.

Here are some tables about the current and new power usage for freezer:
freezer
and heater:
heater

The power usage is still kept relatively high but at least a single heater can't eat twice the power of the entire station.

Fixes #11534 and #9906

### CODE REVIEW

**Comment by CPTANT** [comment]
it also seems the freezer and heater keep using large amounts of power even if the gasses they heat are already at temperature. 
The cryo piping system is so small that it should always be at minimum temperature but upgrading the freezer still shuts down the power.

**Comment by Razharas** [comment]
Unlike our gas simulation our power simulation doesnt even pretend to try to be realistic
Its all magic completely

**Comment by LatD** [comment]
The exponential rise in power usage makes sense at least, which is why I thought that only changing the multiplier is enough

**Comment by CPTANT** [comment]
it makes sense from a physics point of view, but on the other hand no other upgraded machine has drawbacks like this severe despite being vastly more powerful.

**Comment by CPTANT** [comment]
also looking at that code, are freezers/heaters always calculating power costs based on an outside temperature of 20c or something? 

It makes WAY more sense if they only use power when actually heating the gas in the pipes.

**Comment by LatD** [comment]
Yes, they both compare the temperature to room temperature and take the power usage from that. Physically, this makes sense if you think it as heat radiation which is also proportional to the temperature difference and keeping the gas cold/hot requires more energy. This heat radiation just doesn't happen in the game. I don't know how atmos really works but at least cryo in medbay starts to warm slowly if the freezer is turned off.

If you assume the pipes to be perfect insulators and compare the target temperature to the gas temperature, the power usage changes a lot, starting with a high peak and then going slowly to 0. I wouldn't mind this but for now I just wanted to fix the medbay-breaking bug by forcing the power usage to a small fraction of the current one. But like you say, it doesn't really make sense for the power usage to go 50 times higher when keeping gas at constant temperature. The thing that explains this rise in code is the heat capacity efficiency but if it's kept stable, that shouldn't affect it.

**Comment by CPTANT** [comment]
Anyway, this loss to the outside shouldn't be multiplied by the power output.

I don't suddenly lose 50 times as much energy if a put a bigger heater in my system.

**Comment by CPTANT** [comment]
The correct formula would be:

Power = loss to the outside + iddle running cost + specific heat * dT/dt

**Comment by Jalleo** [comment]
Right i can explain the reason for this I found a bug which originally caused power able to be magically created from using one space heat and a TEG and reported it. The tier 4 stuff was added after this.

It was not done to be a powersink more to prevent half the station being powered by a space heater.

**Comment by LatD** [comment]
The powersink talk was in those issue reports which is why this wasn't fixed earlier. I also think that someone should remake that entire active_power function to be something better. I'm not familiar with atmos system or the atmos variables so I'll leave that to someone else. But until then I think this PR is a good way to quickly remove the worst bugs caused by this (which is the insane power usage with best parts).

**Comment by tkdrg** [comment]
I dunno, this fixes that "bug" but also reintroduces the issue with infinite power generation using an upgraded heater and a turbine.

**Comment by LatD** [comment]
How about fixing only the freezer then? It's the freezer that's usually causing the problems anyway (unpowering medbay)

**Comment by tkdrg** [comment]
Then someone would make a bug report about heaters and freezers being inconsistent and someone would fix it and we'd come full circle. I dunno, I just don't think this is an issue. But that's just my opinion.

**Comment by LatD** [comment]
With the turbine working as it is I'd say this is inconsistent always. Like CPTANT said, the power should be proportional to the gas temperature difference which would make them use much less power than with this PR. Currently the heater and freezer are just not even usable in any situation with the insane power consumption with the best parts.

If we can get any other opinions on this we can close or merge this, whatever the opinions are.

**Comment by tkdrg** [comment]
I think CPTANT's solution would be fine. It would in fact make them use much less power *when idle*, but it would also be an elegant way to solve the issue with the turbine, since it would constantly spend energy and be active. I wouldn't mind merging this if you changed the equation to something like that.

**Comment by LatD** [comment]
I don't know enough atmos to touch those variables. Currently the heater/freezer uses power even when there is no gas even connected to them. I'll close this but I hope someone makes some fix for this since it's still occasionally depowering medbay.

**Pull request closed without merging**
