### PR TITLE
Stop triggering myself when viewing fork code

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by optimumtact** [comment]
Does anyone know what this does?

**Comment by RemieRichards** [comment]
@optimumtact you can do:

```var/mob/M```
or 
```var/M as mob```

one of these is hitler and not allowed.

**Comment by optimumtact** [comment]
Yeah, thanks, MrPerson explained it some more in IRC as well

**Comment by RemieRichards** [comment]
cool cool

**Comment by xxalpha** [comment]
From what I know, this only works for verbs?

**Comment by optimumtact** [comment]
That's what MrP said as well, it's likely just copypasta

**Pull request merged**
