### PR TITLE
Adds Nien's HoS formal sprites so they dont look like a Prince suit.

### PR DESCRIPTION
**Pull request by theOperand**

### CODE REVIEW

**Comment by tkdrg** [comment]
@Miauw62 are you still working on this?

**Comment by Miauw62** [comment]
I should be.
Op 1-jan.-2015 16:17 schreef "tkdrg" <notifications@github.com>:

**Comment by Miauw62** [comment]
CONFLICTS RESOLVED MERGE HE POSTHASTE

**Comment by paprka** [comment]
Good job miauw you reverted a ton of things in uniform.dmi

**Comment by Steelpoint** [comment]
Yeah, this reverted a bunch of stuff.

**Pull request merged**
