### PR TITLE
Adds bee socks

### PR DESCRIPTION
**Pull request by Rowelll**
## About The Pull Request

bee. socks.
two versions. thigh high. knee high.

(preview)
https://imgur.com/a/y6ZofsG

## Why It's Good For The Game

h

## Changelog
:cl: Rowell
add: Added thigh-high and knee-high bee socks.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
@Suicidalpickles buff

**Comment by imsxz** [comment]
>anime pfp >sockposting

**Comment by Shadowflame909** [comment]
orange man predicted this as well

**Comment by Rowelll** [comment]
there is one more bee thing i want to make

**Comment by nemvar** [comment]
@Rowelll Beegirls when?

**Comment by Rowelll** [comment]
@nemvar hold my beer

**Comment by plapatin** [comment]
this pr is the bees knees

**Comment by Suicidalpickles** [comment]
BEE SOCKS BEE SOCKS BEE SOCKS
beegirls 2k19

**Comment by AffectedArc07** [comment]
Call them `Stockings (Bee)` and you get my thumbsup

**Comment by Rowelll** [comment]
meh.

**Comment by shellspeed1** [comment]
I am unsure if this qualifies as fetish content or not.

**Comment by Rowelll** [comment]
> I am unsure if this qualifies as fetish content or not.

h

**Comment by Akrilla** [comment]
SPEEDMERGE

**Comment by Rowelll** [comment]
yikes

**Pull request merged**
