### PR TITLE
Adds filling color and smoke taste to salami

### PR DESCRIPTION
**Pull request by OnlineGirlfriend**
## About The Pull Request

Salami now has a set filling color. Also gives smoke taste in addition to the taste of meat.

## Why It's Good For The Game

Previously salami would give random filling colors when added to other foods. Now it will be a consistent filling color.

## Changelog
:cl:
fix: salami filling color
tweak: salami taste
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by ExcessiveUseOfCobblestone** [comment]
we'll call the filling change a fix for your gbp issue 🤣

**Comment by PKPenguin321** [comment]
I didn't know we still had gbp

**Comment by kriskog** [comment]
> You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

:thinking:

Bring back gbp!

**Comment by OnlineGirlfriend** [comment]
My shame

**Comment by Tlaltecuhtli** [comment]
where is the smoke

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is now above zero (1). Feel free to make Feature/Tweak/Balance PRs.

**Comment by bobbahbrown** [comment]
@OnlineGirlfriend Sorry to ping you here, but you won a prize in our community coding raffle for February. If you have discord, can you contact me? bobbahbrown#0001

[Or you could contact me through the forums.](https://tgstation13.org/phpBB/viewtopic.php?f=5&t=25418)

**Pull request merged**
