### PR TITLE
Better slime and slime core icons

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

First part of xenobio rework, slime and slime core resprite, is here.
Slime icons are cancer and literally have 100/300(??!!) colors for plain/shiny slimes respectively. No, it's not a joke, actually exactly 100 and 300 colors PER SLIME COLOR)
Also removes some unused icons like eat states and platinum extract
image

Credits to Onule for the fiery slime sprite that I modified to make shiny slimes

## Changelog

:cl:SmArtKar, Onule
imageadd: Resprited all slimes and slime cores
imagedel: Removed unused slime and slime core icons
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
Are you missing adult slime dead icons?

**Comment by SmArtKar** [comment]
> Are you missing adult slime dead and nocore icons?

If you didn't know, there never were and won't be any adult slime dead and nocore icons because adult slimes become baby slimes upon death :)))

**Comment by TemporalOroboros** [comment]
Huh. I suppose that makes sense. Come to think of it I've never actually put a slime in the fridge and I think I assumed that the split on death was a ghost role pyroslime only think for some reason.

**Comment by TemporalOroboros** [comment]
I would like to note that the additional shading on the bluespace slimes distances them from the bases for the original palettes, but it's probably fine.

**Review by Imaginos16 — APPROVED** [review]

**Pull request merged**
