### PR TITLE
Puts the AI back in its place

### PR DESCRIPTION
**Pull request by pudl**
:cl: wrist
add: AI is back onstation. Gravity generator is now in the southeast corner of engineering.
/:cl:

EDIT: This isn't a nerf.

As we all discovered when this was live tested for a pretty good amount of time, this change is mostly balanced. Onstation AI is harder to kill by nuke ops or other antags that can steal a suit and attack it from space, given that it's in a public location, similarly to how the gravity generator is harder to sabotage right now in its current location.

Antagonist AI is weaker in response to this, because it's easier to hit it from the station. For subverted ais, it's still just as easy to fix them, because the upload has always been on station. But with the upload now being turned to the public hallway, it's easier to upload the access to subvert it... but now the AI can hear you subverting it because it's right next to the upload.

This pretty much means that the change isn't a nerf, it's a rebalance. And after we tested it for a while a lot of people told me it was a welcome change to the meta. There's nothing wrong with something like this since we can revert it a month down the line if it's too unbearable to manage, but I can pretty much guarantee that it'll be good, since it won a poll already.

### CODE REVIEW

**Comment by optimumtact** [comment]
This will probably get denied for the same reasons as last time

**Comment by pudl** [comment]
@optimumtact Last time Kor reverted it to avoid problems with the gravity generator. This time i moved the generator out of bombable range.

**Comment by KorPhaeron** [comment]
I also told Cheridan last night when he asked for you that this is still uncomfortably close to the singulo/tesla wiping it out as soon as its released.

I also have not played the game very much in the past month so I don't really feel invested to argue much about it, I'll leave the final decision up to someone else.

**Comment by pudl** [comment]
didnt even tell me about that time to kill cheridan who wants to help

**Comment by optimumtact** [comment]
Did you map merge?

**Comment by pudl** [comment]
yep

**Comment by nullbear** [comment]
The gravgen on this map change is not really any closer to sing than it is on meta.

**Review by francinum — CHANGES_REQUESTED** [review]
CANCER CUBE

**Comment by Incoming5643** [comment]
Too many sensitive structures too close together, same problem as before. Gravity would go out immediately on most/all engine releases (it may be literally unavoidable if it's the tesla).

**Comment by KorPhaeron** [comment]
Incoming has a point, the tesla was massively buffed since the last time this PR was made. I think the grav gen would be in range to just explode immediately.

**Comment by pudl** [comment]
As ive asked many, many times before, where would you think it could go instead

**Comment by KorPhaeron** [comment]
Maybe above chapel in that empty area.

It'd be kind of a weird place lore wise, but less disastrous from a gameplay standpoint

**Comment by pudl** [comment]
Can you give me a reference image? I dont know how you could access that area from the hallway, unless youre fine with the grav gen being connected to maintenance

**Comment by GunHog** [comment]
Please do not merge this. The Sat is a much nicer place that is also roomier and less cramped. There is not a need for this change.

**Comment by pudl** [comment]
It was already polled and it won by a landslide

**Comment by GunHog** [comment]
So did beards and returning Secborgs, yet here we are, without both: http://ss13.eu/tgdb/tg/ingamepolls.php (second and third entries)

**Comment by optimumtact** [comment]
beard and secborgs were removed as administrative hassles and poor designs, so player feedback was not considered as much.

**Comment by Iamgoofball** [comment]
@pudl polls ran 3 months ago do not reflect players now

**Comment by pudl** [comment]
yes it does

**Comment by WJohn** [comment]
I'd like to see this at the very least tried out for a little bit, maybe a few days. If nothing else it'll highlight the pros and cons of an on-station centralized AI versus an external sat.

**Comment by KorPhaeron** [comment]
We already did try this for a few days, its basically down to yelling opinions now

**Comment by pudl** [comment]
@KorPhaeron We tried it and the poll was in favor by quite a bit

**Comment by KorPhaeron** [comment]
Yeah exactly, was my point

**Comment by kevinz000** [comment]
>Nerfing AI further

**Comment by pudl** [comment]
@kevinz000 its not a nerf

**Review by tgstation-server — APPROVED** [review]

**Comment by pudl** [comment]
yas bitch yas

**Comment by Niknakflak** [comment]
Everytime Gunhog comments on an AI change, I ignore it because he's the steelpoint for science and AI.

**Comment by LaharlMontogmmery** [comment]
This again?

**Comment by GunHog** [comment]
That is quite poor reasoning. I am not nearly as extreme as Steelpoint ever was, and besides, you should judge PRs and comments on their merit, not simply the one who writes it. I find myself agreeing with people whom I dislike quite often. To close your mind and opinion based on the author and not the content is a very bigoted manner of thinking, NikNak. I do not know why you detest me so, I never did anything against you, did I?

**Comment by Jalleo** [comment]
I do not support this PR because it seriously weakens the gravity generator. The new placement will mean gravity is out a lot.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
SMES wiring in picture is incorrect, will result in AI losing power due to wires on the same grid connecting to both the SMES's input and output.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Gravity generator SMES has no wiring to its input terminal.

**Comment by Hatfish** [comment]
Didn't pretty much everyone agree that this was a horrible change the last time we moved the AI back on-station?

**Comment by pudl** [comment]
@ChangelingRain :thought_balloon: Weird, when i live tested the SMES charged fine for a while. Ill change it but Im not sure that youre correct. Additionally I ripped the wiring system almost directly from an earlier revision of Box, but it may have changed since then.

Im about to re explain my reasoning for why this isnt a nerf to the ai players in the OP, get ready everyone...

**Comment by pudl** [comment]
This science/ai hivemind shit pisses me off so much, dude, its even worse than the sec hateboner we got going on, someone makes any change to science and immediately theres a billion downthumbs by people who dont even fucking comment anything useful @kevinz000 @Chiefwaffles @feemjmeem @Fox-McCloud @Boggart @terror4000rus or dont read the comments @Hatfish. Unhelpful shit like that shouldnt be allowed on the github.

Hatfish, if you actually took time to read, no, in fact the majority agreed it was a fantastic change, you clod, so foh unless you want to give some legit criticism. Gun hog, thanks for being the one science player in the entire world who has the heart to give feedback (even if it isnt anything i can use) instead of being the silent shitheads ready to downthumb anything that hurts muh science :cry: 

Im gonna be real, science shit is more of a cancer than anything else in this codebase. The only people who are fine with science being so ridiculous and powercreeped are science players, and that happens to be so many likeminded people that cant take the idea of change, even something that isnt a nerf, just a rebalance, that coders and mappers cant do shit. Get the fuck out of my pr unless you have a solid reason for your disapproval. I dont give a shit about a downthumb unless it comes with feedback, @Cheridan @ChangelingRain @optimumtact yall shouldnt either, no clue why you follow such an unhelpful system that pretty much neutered the idea of feedback for prs. Its stupid.

**Comment by pudl** [comment]
That goes for approval too, @MrStonedOne @WJohn @optimumtact @Shadowlight213 why dont yall defend me or something if you approve of such a controversial change? Just your upthumb doesnt suddenly change peoples minds

**Comment by GunHog** [comment]
A satellite installation has much more room and freedom of design. The greater security has the drawback of being exposed to spaceborne antags, especially Syndieborgs, and escaped engines are notorious for going after the AI (which incentive to keep watch over it).

Stuffing the AI back into the station cuts out all of that to bare-function and minimum equipment placements. It is a severe limitation on design capability, as well as significantly cutting down on the AI's on defenses, making a significant nerf to antagonist AIs, removal of a teleporter setup, and making it gravely more difficult to employ creative tactics in relation to modifying the AI's areas to resist a crew assault or stealth maneuvers to lure the crew to a fortified but empty Sat. You cannot do that without a teleporter.

You are potentially killing some rather creative tactics and reducing its own defenses and available equipment to boot. The only advantage to this regression is increased protection for Asimov AIs in the form of being in the center of the station where both stealth and brute force are less effective. This will be nullified if the AI is instead placed near north of the Chapel, which is both vulnerable to space-borne antagonists AND station bound ones as well. 

This is a significant rebalance which has a greater loss than gain, the gain in either location being a faster crew response. The losses are explained above.

I do hope this is enough feedback to explain my reasoning; I will provide much more detail if you wish. 

Also, I do not feel that I am in some sort of "hivemind", but rather on one side of a fence.

**Comment by Niknakflak** [comment]
When someone is heavily biased towards a said job, of course they are going to have a biased opinion.  That is why I ignore it.

**Comment by feemjmeem** [comment]
I'm sorry that you're upset by people who have opinions other than yours. Here, let me tell you about them, since you asked.

One big bomb will take out the bridge, the AI, and the central hallway. A few smaller bombs, easily placed and RAPIDLY placed in this area, will have a similar effect. Even if it doesn't take out the AI, it will at least make it much easier to access.

There are 14 space suits on the station:

2 Sec HS
1 HoS HS
2 Eng HS
1 Atmo HS
1 CE HS
4 EVA suits
1 RD HS
1 Med HS
1 Cap's Suit

There are also a bunch of fur coats, fire suits, and coffee machines.

It is very possible to kill the AI when they're malf, and it happens quite frequently. When someone is assaulting the AI, the fact that it's on the satellite and that it has a lot of tools available actually lets it try to defend itself, and there are effective countermeasures against those defenses. It becomes a matter of outlasting and outguiling the opponent. I know this because I've been on both sides of it many times.

On the station, the only defense you had as a hostile AI was to relocate. The only defense you had as a 'good' AI was to hope security was paying enough attention to the station and to you that when you they inevitably bombed or rushed you, they were stopped before getting there. I can tell you that this didn't happen that often. I almost always died to ops when I was on-station, and I only die to ops in the satellite about 50% of the time -- it's an extra place they have to go out of their way to go to and prepare for which isn't really necessary most of the time because most of the time the AI is Asimov anyway.

Yes, it's really easy to buy a penetrator rifle and kill the AI from outside. But that's a plan that works more or less exclusively on the AI, whereas the central bombing or 'kill the AI on the way to the disk' plan works much, much more effectively, with much less investment, and as a result of being tried more frequently has been, in my experience, much more successful.

Next up: the upload. There are camera alerts for activity in the upload anyway. An AI worth their salt will probably take a look at those alerts if they think there's a risk. Hearing activity in the upload was nice, but it usually wasn't relevant, because you'd only be able to tell the difference between someone walking in there or walking in to any of the other places that were right next to you, being in the center, if the turrets were firing -- and nine times out of ten when someone's dumping a law on you, the turrets aren't firing anyway.

Having the upload away from the core also improves the ability of the crew to get in and reset a law without actually having to interact with the AI. If I'm an extremely malf AI, and I only have to defend one general location that I can patrol easily, that's gonna be a hell of a lot easier for me than if I have to split my attention between where I am and where people can affect me.

Similarly: having the gravity generator away from the general engineering department means that if something horrible goes down in engineering, it probably won't affect station gravity. Whereas putting it back into engineering means that every time the engineering department gets fucked -- and that's a lot -- gravity will go away in addition to everything else.  I'd make the argument that having gravgen in the center of the station makes more sense from a LOL THEME perspective, too, but other stations have it sitting any ol' place so that doesn't have to be consistent.

Is that a little clearer as to why I gave you a thumbs down?

**Comment by feemjmeem** [comment]
On an aside, becoming actively hostile to people who have opinions in your PRs is not really a good way to gain support from maintainers.

**Comment by GunHog** [comment]
>When someone is heavily biased towards a said job, of course they are going to have a biased opinion. That is why I ignore it.

I comment on mechanics and gameplay I understand best. I cannot tell you how to balance, for example, HoS, because I do not play HoS. It would be moronic of me to change something I do not play or understand. When I made the changes to Wizard's Fireball spell, I took as much feedback from my PR's comments as I could, because they knew things I did not, had perspectives I could not see. It is difficult to improve something you do not understand. I apologize for finding ways to improve things most familiar to me.

I of course get the feeling to discard opinions that oppose mine, but that would unwise, as I willingly exacerbate my own ignorance. It is little different from turning off my TV when I see a news report that exposes a scandal regarding my desired political candidate. I would be shutting out everything I dislike and proceed to live in my safe, warm little bubble.

Despite all the hate I get and somehow being my own meme, I read _all_ feedback I receive, including the spam. I prefer to know the reason why someone is against me, and perhaps that I may be wrong about something. There are those, of course, who will oppose **anything** I do or say based on who I am rather than the merit of my comments. There is nothing I can do to convince a person like that. Even so, if their comments include something I can use, I will consider it regardless. 

I know that I have a bias, and I try to moderate myself in my ideas as a result. I even ask Kor's opinion on a change before I begin coding it. I cannot do anything about my reputation at this point, however.

I still do not understand why you detest me so, I used to like you and value your opinions. It is a real shame that you cannot do the same for me.

**Comment by pudl** [comment]
@feemjmeem I was being actively hostile to the people who downthumb prs but dont leave any feedback to help the creator of the Pr. Ill comment on the entirety of your comment when im home

**Comment by PKPenguin321** [comment]
Reminder that the grav gen on meta is close the singulo/tesla and that's not that big of a deal

**Comment by feemjmeem** [comment]
@pudl Active hostility in a PR in general is the problem, not why you were doing it or to whom you were doing it and why you think it was justified. You did mention that you felt that because 'a poll' had selected your proposal that you figured it would get merged without a problem. How is that poll qualitatively different from someone giving a thumbs-up or thumbs-down on your PR?

**Comment by Iamgoofball** [comment]
Plus the poll was 2 to 3 months old

**Comment by pudl** [comment]
@feemjmeem The poll on the server was a census with no option to leave feedback, a census doesnt demand any feedback. The github is more like a survey, before we had up and downthumbs it was here to leave actual feedback. Now that we have the thumbs people forget what the github should be used for.

The poll being forced in the face of players made the average person more likely to vote because it was less voluntary. But the github on the contrary is a completely voluntary vote thats harder to access, so its more likely to draw people with stronger opinions instead of the silent majority. Thats what makes the poll a better indicator. Theres no voluntary response bias, or at the least, theres less of one.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not requiring a spacesuit to get to the autism fort known as AI sat is a pretty considerable nerf on the AI's part.

**Comment by pudl** [comment]
@ExcessiveUseOfCobblestone But on the contrary, now to access the AI to kill it you have to get at it from a public area. So even though theres a nerf, its balanced out.

**Comment by KorPhaeron** [comment]
It's far harder to kill a loyalist AI since sec can easily respond, far easier to kill a rogue AI since the whole station can reach it and it doesn't even have secborgs anymore

**Comment by pudl** [comment]
@ChangelingRain Fixed your complaints pls approve now

**Comment by Core0verload** [comment]
>I mean you don't need a space suit now if you use the tubes, but the tubes are easily sabotagable by a competent engiborg.

The same competent engiborg can RCD AI room floor and make it space.

**Comment by GunHog** [comment]
The AI could do the same thing without a borg using the Floorbot, which has also been removed. This change continues to be a strong downgrade, especially to layout and the AI's capabilities.

**Comment by pudl** [comment]
People have gotten used to the ai sat, when it was onstation there were plenty of strategies. Try filling your core with plasma, maybe? Or venting it to space, or putting shit tons of doors in the core? Thats what was done in the past

**Comment by KorPhaeron** [comment]
Secborgs still existed when it was on station, they had a huge impact on the game.

**Comment by pudl** [comment]
But the defense of the core relied on engineer borgs and the ai being clever. Secborgs have always been for conversion and for ais who arent clever enough to make their core nigh uninhabitable already.

Whenever you defend your core thru atmos or getting engiborgs to build ridiculous shit, secborgs arent needed. The purpose than secborgs filled after the core was designed well are fulfilled by the big white borgs, whatever theyre called.

Again, people keep bringing up hypotheticals that have been proven wrong by the live test. Clever AI players still lasted a while, it was just harder, not impossible. There were still some victories for the AI.

This is a change in the meta. Whenever AI was moved offstation, that was a change in the meta too, but if you look at the comments on that pr you see almost no one protested it. This is just changing back, and everyone is freaking out. Again, theres nothing wrong with merging this and keeping it around for a while (especially because it won the poll) and if it turns out that antag AI is absolutely unwinnable then we can go back. Several PRs have been merged under this same reasoning.

**Comment by feemjmeem** [comment]
I think the reason that no one protested that one and that people are protesting this one is that this is not a beneficial change.

**Comment by GunHog** [comment]
Why do you want this change in the first place?

**Comment by pudl** [comment]
After so long its been proven that the minisat wasnt a beneficial change, it was a balanced one that over time grew ridiculous.

So let me elaborate on that by addressing gun hogs comment. The original minisat was fine because it did nothing more than move the ai into space and flip flop the meta. AI is now harder to get whenever its rogue, but easier to attack by antags.

However in the past year or so the minisat was un necessarily buffed by gunhog and wj so that its become ridiculous. The AI is nearly impenetrable if you dont have a space suit, and even with a space suit its difficult because of the design of the core. Thats no fun.

AI players shouldnt be comfortable in their minisat free from attack and pretty much unkillable when antag, because every other antagonist doesnt have nearly the protection. Even nuke ops can be killed on a dime if they mess up. The AI of all antagonists has the biggest room for error because its so high in defense.

This pr changes the meta, it makes AI an uncomfortable job to play as antagonist because you can die just as easily as a traitor could, which i think makes sense, given you are also one of the most powerful antagonists because of your control of the station. I know that its pretty much effortless to cause huge damage just by flooding plasma and blowing lights. It can be fixed by an attentive engineering team, but its still pretty big damage with zero effort put into it, just because the AI is so powerful.

On the contrary this change makes AI more friendly to newer players again (although it still shouldnt be played by someone new, but someone who finally decides theyre ready to play the job after a month of playing and they turn antag off) because youre safer from attack. It makes more sense for a station AI to be heavily defended from attacks by rogue antagonists by being in the center of a station than it does for it to be floating off in space and hard to attack if it went rogue.

Thats why i want the change. Pretty much in summary, it changes the meta in a way that i feel is positive, and it makes more sense in general for it to be onstation.

**Comment by feemjmeem** [comment]
Do you plan on moving the AI into the station in all of the other maps as well? Most of them have satellites.

I'm also a little confused: you say that the AI in the satellite is too hard to attack when it's antag, but that it's also too hard to defend when it's not, necessitating moving it back into the station to allow 'new players' to play it?

Is it too well-defended or isn't it? 

I don't think I've ever played as an AI and felt 'safe in my core.' It's insanely easy for a syndiborg to rush in and open all the doors and kill me, or an emagged borg to do the same, or for a human to pick their way in towards me and I have _nothing I can do to them_ without outside help. So many very good strategies exist for taking out rogue AIs that it happens quite frequently.

I disagree with you that this change would be positive, and in my opinion it would actually be negative, from my experience both as an aggressor against AIs (rogue and otherwise) and as an AI (rogue and otherwise).

**Comment by feemjmeem** [comment]
Let me clarify: Yes, I have a ton of turrets, which don't do me a lick of good when someone is cutting their way in from the back of the satellite and knows the meta to keep from getting killed by them.

**Comment by pudl** [comment]
Your opening paragraph, thats exactly what im saying. When the AI is antag, its hard to access by the onstation crew because it can send borgs to defend it and kill people and also its generally hard to access since its in space except for crew with space suits as part of their job.

When youre not antag, you cant send borgs to defend yourself because you cant injure people and theres no borg to reliably stun and keep people at bay while help comes. Someone can drill into your back and kill you pretty easily. At least with antag, when someone is coming to attack you from the back, you can get a borg to come and stop them. That doesnt happen with normal AI.

I was saying that the ai is too safe in their core when theyre antag. That was kind of the point of my entire comment, maybe you skimmed it, i dont know. So your syndiborg comment is irrelevant, because i already addressed that as normal AI you arent safe. As antag you are.

**Comment by feemjmeem** [comment]
In my experience, even (and especially) when an AI is Asimov, the majority of the crew is NOT its friend. Arguably, this is the point of its existence: to act as a foil to the rest of the crew while still being completely subject to its demands.

Also, as I stated above, having the AI in a different location from the rest of the station gives the operatives a choice: they can devote resources to taking out the AI, or they can attack the station directly and hope that the AI is unable to hinder them (which is a safe bet most of the time, given roundstart Asimov, but is still a gamble). This, in my opinion, is a good game mechanic.

Similarly, in the case of a revolution, the AI is largely powerless, as it's really, really hard to stop an organized greytide. Putting the AI back on the station will take that powerlessness to an extreme, meaning that the very first thing anyone does during a revolution, or cult, or whatever, round is dive in on the AI and make sure that it can't hinder them. It will be extraordinarily easy with a mass of players.

Taking the AI off the station happened _a long time ago_. A lot of game modes that we play now either did not exist or were very different from when it was on the station. A lot of weapons and game mechanics came about because it was no longer on the station. The player antags were weaker when the AI was on the station (with the exception of the lack of the bomb cap, which is an even _older_ implementation).

I also disagree with your assertion that 'the AI on the satellite has been proven not to be beneficial.' When it first happened, I thought it was ridiculous and was very annoyed, both as an AI and as a non-AI player. Over time I've come to realize how much more sense it makes, for a lot of the reasons that I and others have said in this PR and in the PR you made previously about this same change (albeit with some differences).

The AI is very powerful, but is also extremely limited. It can't run away from you, and it can't really chase you. A good bomb could take it out. Two good bombs definitely will take it out. If the engine gets loose, there's a good chance it'll get taken out, even if the rest of the station doesn't.

All that having been said, and as both I and others have said, the gravity generator is still way too close to the engine, both in current metastation and your proposed changes to box. While catastrophic failure is the name of the game in SS13, everything failing at once without a player going out of their way to make it happened (with, say, a coordinated bombing campaign) is just a lame round.

**Comment by pudl** [comment]
A bomb attack cant take out all of engineering, i live tested.

You must not play basil because no, the gravity generator because close is not a big deal.

**Comment by feemjmeem** [comment]
Okay. Here's another item:

All of the game modes that involve the AI at all are built around the idea that the AI is harder to get to. Ratvar cult has a mode in which all the silicons have to be subverted. That will be killer simple to do on the station. Nuke ops have weapons _specifically designed_ to deal with the AI. 

This is a nerf unless all of the push and pull which has happened for two years since this change was implemented is also reverted or rebalanced.

**Comment by pudl** [comment]
Did you not play when this change was livetested? It was for about 2 weeks and it worked fine, ratvar was implemented then too.

**Comment by MrStonedOne** [comment]
I'm just gonna point out, ai was on the station until meta put it on a sat, then somebody did the same to box, the other maps were made after all of that.

I remember one map where the ai was inside science

**Comment by nullbear** [comment]
anti-ai charges are designed for double-r-walls, which are still present in this map change. And so would be unaffected.

ratvar conversion mode is arguably about the same either or. If a ratvar cultist gets to the ai sat, then they can happily convert all the silicons while the rest of the crew is unaware of their presence. But if the ai core is on-station, it's more likely that the crew will notice their presence.

ai on-station means crew is more likely to notice the presence of attacks AGAINST the ai, and is able to respond to it when the ai is like 'HELP SOMEONES BREACHING MY CORE' making it harder to break into the core as an antag, but easier if the core is antag.

ai off-station means the crew is unlikely to notice ANY attacks against the ai, and even when the ai calls out for help, they are unlikely to respond in time to do anything about it. AI off station is easier to break into as an antag, but marginally harder if the core is antag.

As for rev/gang rounds vs. the AI. In this map change, the upload is easier to access than the ai core is. Any revs or gang members breaking in would find it easier and more effective to upload 'heads are non-human' law as opposed to destroying the ai outright. As well, this is NOT a balance change, because on most station layouts, the ai upload is on-station already anyways.

Because of antag-ai defenses, it's a very minor, if anything, balance change to the 'difficulty' of an antag ai. But it does strengthen the defense of a non-antag ai, and promotes law-changes over ai destruction by antags.

**Comment by KorPhaeron** [comment]
@MrStonedOne 

I'm actually the one who put the AI in science. I agree that moving it off station led to awful map bloat and was power creep.

You can't just undo a giant change like that with no regard to how the rest of the game has developed in the past two years though, especially if you're cramming more critical systems into engineering.

>but meta has grav gen at engineering!

And it has tcomms on the AI sat, still less stuff in one place than this would be.

I don't think it should have been moved in the first place, but undoing it now is going to take a lot more work than this PR.

**Comment by pudl** [comment]
@KorPhaeron Alright, if this gets merged i will do more work to change things as problems arise and i know what needs changing.

**Comment by pudl** [comment]
Gonna comment here too for posterity, Joan is wrong about the gravity generator being wired incorrectly, so dont let that block the pr from being merged. I fixed her other issue

**Comment by kevinz000** [comment]
Don't get why people who havn't played in a super-long time should just come back and make a major balance change. This makes the AI really easy to attack as all that's protecting it is a few r-walls.

**Comment by Bawhoppen** [comment]
this is absolutely retarded as it always has been and will get denied and hated as it did last time

**Comment by pudl** [comment]
@Bawhoppen it won a poll last time

**Comment by feemjmeem** [comment]
you keep clicking like on your own posts

you act like this is a foregone conclusion

you can't stop talking about this poll that nobody else knows about

was the poll even on sybil or basil

when was it

were you playing on sybil or basil when it occurred?

show us on the station where the satellite touched you

this is absurd

**Comment by pudl** [comment]
@feemjmeem Alright i guess im done talking with you if youre gonna decide to ditch our constructive and intelligent conversation for dumbass ad hominem shit

**Comment by feemjmeem** [comment]
@pudl Please direct your attention to the following comment, which you posted prior to my initial comment in this thread.

https://github.com/tgstation/tgstation/pull/20529#issuecomment-247360522

This contains your statement of opinion about people with opinions who do not fully express them to your satisfaction. It also contains you referring to another poster in the thread as a 'clod,' in addition to a few other choice comments.

You continue to post in this PR as if, as I stated above, it is a foregone conclusion that this PR will be accepted, and act as if we are inconveniencing you by expressing subjective reasons why we feel the PR is a bad idea, and descriptions of objective issues with the change.

All of the statements and questions I made in my most recent post are relevant to and predicated by your behavior in this PR. I do not mean to attack you with "dumbass ad hominem shit," I mean to illustrate that this conversation is neither intelligent nor constructive at this point. Draw your own conclusions from that as regards how I feel about continuing it.

**Comment by pudl** [comment]
@feemjmeem I called out the people that do nothing but downthumb shit, because thats inherently harmful behavior. When youre leaving downthumbs but not expressing your opinion about it youre basically saying "fuck you" to the person who made the pr for no reason. Im going to say fuck you right back to those people because they arent helpful. And yeah its definitely intentional on their part, because that very comment is downvoted again by @Chiefwaffles who still hasnt left a comment.

I was perfectly fine with you and enjoying our discussion because you did exactly what i asked for, left your criticism and it helps me understand why people dont want the change. But what am i supposed to do about it when your only request is "dont do this pr"? Im not going to close it, because i still want this change regardless of the fact that you dont.

Im not commenting that this pr is definitely going to get merged, even when i was bargaining with Kor because i figured he wanted to close it i said "IF this pr gets merged," if you misread what i said to baw as if i was saying it will get merged, i wasnt. I was only pointing out that he was being stupid for calling it hated, because it wasnt. It was a popular change. And it would probably help my argument to point out that if you know nothing about the poll, it seems like you werent actually around to see the ai back on station and see that people enjoyed the change a lot. I was.

Its hard to sort the shit from the real shit. Im making a lot of shitty comments directed at other people but im maintaining composure with you. Thats all that really matters at the moment, so deciding to stoop down to everyone elses level and insult me. The worst part about your comment is the fact that is seriously shows how oblivious you actually were. Everyone here knows about the poll, no one has made any comment implying they dont know about it, youre just assuming no one knows because you dont know.

So yeah, if youre going to snap suddenly because i told baw about the poll, im not interested in talking with you anymore. And im probably going to take everything you said before that comment a lot less seriously.

**Comment by Incoming5643** [comment]
The era of getting this mad over mapping is long over

**Review by ChangelingRain — APPROVED** [review]

**Comment by Chiefwaffles** [comment]
If you're so intent on spamming my inbox, fine, here's my feedback:
I think it's a bad change.

That it. That's my opinion.

**Comment by optimumtact** [comment]
You can unsubscribe from a thread, I have because this pr will go nowhere and just get closed so it's a waste of time reading/arguing about it

**Comment by pudl** [comment]
@optimumtact Kor says he might pick you to choose if its merged or not, so you shouldnt be too negative about it

**Comment by kevinz000** [comment]
nice self-upthumbs :^)

**Comment by Boggart** [comment]
@pudl I didn't leave a comment with my downvote because I figured you'd understand that I didn't like the pull request.

Like Kor said: 
> Letting people who have not connected for literally over a year to make large balance changes seems a bit odd as well.

Yes, the AI used to be in the center of the station. But balance changes have been made and since then with it's current location in mind and the crew has new/more equipment at their disposal.

From the staff meeting room you can get into the core with a single broken window/grille (assuming you don't have access to the room) and one c4/thermite. Then introduce the AI and it's apc to your choice of emp or explosives. 

Also, unless I'm seeing wrong there's no slippers on the left or right of the core and the ones above/below look like they won't reach those spots leaving the AI even more open to attacks from the sides. I seem to remember those being there when the AI core was in the center.

**Comment by PKPenguin321** [comment]
Self up thumbing is fine so long as we continue to take reddit thumbs seriously

**Comment by Kromgar** [comment]
Traitor ais are now easy to kill with just some thermite only takes 2 tiles if you do it right

**Comment by pudl** [comment]
@kevinz000 Your mindset is exactly what im trying to act against. Look at the ai sat from before Wjohnston redesigned it. Theres a pic of it here. https://dl.dropboxusercontent.com/s/ob0up0zh9w1l1ae/fullbox.png

Notice something? It has two less turrets than my design. Now look at the pr for Wj's redesign that we currently use. https://github.com/tgstation/tgstation/pull/14263

Huh, not a single comment about the fact that it insanely buffed the AI core? Thats because people want buffs and they grow used to them so theyre harder to remove. Its called powercreep. People act like the idea of going back to how it used to be would be the end of the world, when we functioned perfectly fine before it. And no, the game hasnt changed so much that reverting to Steels ai core, for example, would break something.

The turret setup i made was livetested, and i have no clue how you could in any way think that its worse than wjs. The two turrets defending the upload computers can hit you from the door, just like the turrets on the current ai core. The ai core itself, has turrets that hit you from the door. If you step back to avoid them, theres a blast door that can be closed so the ai can defend itself.

Also the current ai core can also be done in with two ion blasts, because the apc is in the exact same place. The problem is that the ion rifle shouldnt even fucking exist in the first place, it sucks. @Cheridan @MrStonedOne back me up pls.

Also people keep ignoring what i mean when i say it isnt a nerf. The word "rebalance" exists for a reason. If you nerf one thing at the same time as buffing another, then its not a nerf, its a rebalance. Try reading the comments to see whats been insanely buffed for a second???

@Boggart I have played within the year, i last played the day i made this PR.

People keep acting like being safe should be a given, when any other antagonist isnt nearly as safe as traitor ai. How about we take this opportunity to be creative? Maybe vent your core to space, flood it with plasma, or have an engiborg to put a door on every tile? All of those solutions handle your problem. And dont try to say that the ai shouldnt have to go through that trouble, because it should. Just like every other antag it should have to do work to be safe, not just have it handed to it on a platter.

Also the slippers do fill the entire core.

@Kromgar Read above.

**Comment by Boggart** [comment]
The AI shouldn't be super safe but this is going to bring back the problem of being outed for core fortifications by being heard through the wall and/or the CE walking past with his scanner on meson mode.

Yes, you can kill the AI on the sat with the ion gun too, but it's not right next to such an easily broken into room.

**Comment by pudl** [comment]
How about we solve this solution: Remove the ion rifle from the armory, like everyone thinks it should be

**Comment by Bawhoppen** [comment]
allura just go away nobody wanted you to come back

go to hippie they will like your ideas of balance

**Comment by kevinz000** [comment]
But the thing is, the current AI core on box has the AI protected by a final door and turrets that can be set on lethal if it is subverted/traitorous for a last ditch attempt. This does not and puts it in ion rifle range. The secondary kill hallway APC is also protected behind windows so that you need to break into maintainence to hit it.

**Review by MrsTonedOne — APPROVED** [review]
So did you know that you can not edit or delete reviews?

**Comment by pudl** [comment]
@kevinz000 Something doesnt have to be onscreen to hit it. Run into the room, open the door before you get tased/hit, run back, shoot ion rifle through. Especially easy because the ion rifle can open doors

**Comment by nullbear** [comment]
Can the ion rifle open blast doors though?

**Comment by pudl** [comment]
I think so, but if it was changed then its still effortless, just shoot the door and crowbar it and its nigh instant regardless

**Comment by Cebasiz** [comment]
>edit: this is not a nerf
yes, it is

the layout is garbage, one engineer without even a hardsuit could get through this whole thing in like 30 seconds

the AI headsman brigade already ruined enough, please fuck off

**Comment by Supermichael777** [comment]
flip the ai cell around to face the wall

**Comment by ChangelingRain** [comment]
I think I can sum up the change as "buff to nonantag AI, huge nerf to antag AI."

**Comment by GunHog** [comment]
Sacrificing a much stronger design, size, robots, and defenses for reliability on players that do not really care much about it.  Loss of the second teleporter has not really been mentioned either. That was always the quick option to rescue a dead Asimov AI, so the current design is not exactly unreachable.

**Comment by optimumtact** [comment]
Fuck it, we'll run another poll and let the masses decide.

**Comment by nullbear** [comment]
antag ai's usually get borgs to pull them someplace more secure anyways tho

**Comment by Cebasiz** [comment]
which is possible because the AI's location is remote in the first place

your chance of being spotted on bagil lowpop with this setup is still probably over 50%

basically, this whole PR is fucking stupid because 1. it's a nerf masquerading as "just a change :^)" 
and 2. sillicons do not need more fucking nerfs, github has been beating a dead horse since secborg removal. countering sillicons is trivial, inexpensive, available to everyone and takes zero fucking time at all. further nerfs are ridiculous, playing antag AI is ALREADY masochism.

**Comment by pudl** [comment]
lol

**Comment by LaharlMontogmmery** [comment]
100 comment get!

Also, i'm against this PR. It is a full-on nerf, disguised as a change.
The only way this is a "buff" in in the case of nuke ops.

You honestly have to have something else to offer alongside with this change, if you want to make this through.

**Comment by pudl** [comment]
wrong

**Comment by pudl** [comment]
Im gonna fix these conflicts on a day that i dont have work and have energy

**Comment by pudl** [comment]
Probably thursday

**Comment by kevinz000** [comment]
Maybe he has been playing, and got dunked by an AI, so he decided to try to nerf it to shit :^)

**Pull request closed without merging**
