### PR TITLE
grep's for "recieve" typos

### PR DESCRIPTION
**Pull request by ShizCalev**
Just spellchecking some common mistakes.

### CODE REVIEW

**Comment by uaioy** [comment]
how did you recieve this information

**Comment by MrMelbert** [comment]
\>I before E spellchecking
\>Look Inside
\>Receive

**Comment by necromanceranne** [comment]
unit test?

**Comment by ZephyrTFA** [comment]
check grep is a CI test

**Comment by ZephyrTFA** [comment]
It may be my child but I hate it

**Pull request merged**
