### PR TITLE
[TMC] Replaces styptic powder with new cobby type 2 brute healer + titanium reagent and helper chem.

### PR DESCRIPTION
**Pull request by Krysonism**
### Test merge information
As i prepare this PR for the test merge, one thing i'd like to point out that this particular set of options for treating brute injuries is unlikely to be final in any way.

I'd especially like feedback on how this chem works as a emergency chem and for treating minor or moderate "in the field".

I'd also like to see how this works together with a public **cold shower/clonex** station for those who wish to get rid of their last bit of cell damage from field treatment.

The synthflesh recipe has been changed to use mitomidal instead of styptic for the purpose of this test, the recipe will probably be changed if this type of change gets merged.

## About The Pull Request

This PR introduces a new fast brute healer; **mitomidal**, that converts 20% of the damage healed into cell damage effectively reducing your max health until you can get proper treatment. This new chem is made with titanium from grinding sheets, hopefully this will help reduce the titanium surplus somewhat.

The new chem also has an interaction with rezadone because taking 0.5u rezadone while you are healing and removing all your cell damage was a bit cheap. 

Rezadone and mitomidal forms a new reagent; **hollstein's adduct**, that removes damage slowdown(as opposed to morphine which removes all slowdown), slowly heals clone damage and reduces dizziness.

I have also changed the check for required_container to an istype to allow subtypes to qualify. 

## Why It's Good For The Game

We do not yet have a type 2 brute healer we need for the new medical system, i think brute to clone conversion is an interesting option.

20% damage conversion is not that much when we consider how useful brute healing is, but i since clone damage is not easily healable outside of medbay this makes mitomidal a good emergency chem, but bad for extended use unless you have rezadone(or clonex and a shower) as you will be very frail from regular use.

Titanium is too abundant on the station and the introduction of the titanium reagent will hopefully help mitigate this.

The new required_container behaviour is more flexible and can be used to create reactions that can only take place in the body as seen here with Hollstein's adduct.

## Changelog
:cl:
add: Mitomidal, a new type 2 brute medicine
add: Titanium can now be ground to titanium powder.
balance: Styptic patches and gels are reformulated with mitomidal.
balance: Synthflesh is now made with mitomidal.
del: Styptic power is now unmixable.
code: The check for required_container is now an istype.
/:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
Hollstein's takes rezadone to make so the damage slowdown removal shouldn't be that controversial i think.

If Cobby takes issue with any of the numbers they can of course be changed.

**Comment by Detective-Google** [comment]
Maybe I missed it but how much brute/cycle does this actually heal?
Looks like 4 but do correct me if I'm wrong

**Comment by Krysonism** [comment]
4, but it deals 0.8 clone.

I am open do having it heal faster but deal more clone. I await clarification from Cobby about how he wants this class of medicine to behave.

Perf heals oxygen damage amazingly fast and deals 40% toxin, but it is hard to compare since oxy healing is less useful and clone damage more oppressive.

**Comment by Krysonism** [comment]
If anyone have a suggestion on how to make the overdose more interesting i am all ears.

**Comment by Dawson1917** [comment]
Cellular damage is fucking awful and any doctors who apply this on people will get lynched and spaced for not using proper brute healing chems. Interesting concept but I'm not dealing with the absolute bore that is cryo to resolve brute damage

**Comment by SpacePrius** [comment]
yet again, i think cobby's idea for categories are dumb, no medicine should do damage unless YOU make a mistake.

**Comment by py01** [comment]
Medicines that deal damage to you are intentionally easier to acquire, they are the ghetto variants. You aren't actually supposed to use these as a doctor unless chemistry is refusing to do its only job, or are making ghetto medicine in maint with a grinder.

**Comment by dr-bee** [comment]
This is a bad chem. It does a shitty version of styptic using chemicals that are honestly harder to find. The interaction with rezadone removes any real use this would have if used it medbay and the use of ammonia and titanium removes any real use it would have in ghetto medicine.

**Comment by Tlaltecuhtli** [comment]
why does injecting titanium give  no armor?

**Comment by Krysonism** [comment]
> 
> 
> Medicines that deal damage to you are intentionally easier to acquire, they are the ghetto variants. You aren't actually supposed to use these as a doctor unless chemistry is refusing to do its only job, or are making ghetto medicine in maint with a grinder.

Not true, read cobbys post.

**Comment by Krysonism** [comment]
> 
> 
> This is a bad chem. It does a shitty version of styptic using chemicals that are honestly harder to find. The interaction with rezadone removes any real use this would have if used it medbay and the use of ammonia and titanium removes any real use it would have in ghetto medicine.

Styptic is not long for this world in its current form. 

Also this can be ghetto crafted using a glowstick, lightbulb, fuel and titanium.

**Comment by GuyonBroadway** [comment]
-Deals clone damage
-Needs titanium

This will never be used as it's more inconvinent than a stint in a cryo cell.

**Comment by Krysonism** [comment]
> 
> 
> -Deals clone damage
> -Needs titanium
> 
> This will never be used as it's more inconvinent than a stint in a cryo cell.

I might swap the copper with titanium the the trophazole and mitomidal recipes.

This chem is not so much for the current medical system but is balanced around the future system, where clean healing chems are premium.

**Comment by CPTANT** [comment]
It's pretty hard to see what kind of effect this will have until styptic is actually changed. 

If styptic isn't changed this is just an inferior version that bloats the chemical list.

**Comment by ExcessiveUseOfCobblestone** [comment]
This is almost too premium to use reliably as a C2 given that I haven't really planned on giving cloning damage a C1 since it's already the most constraining damage type (although new rads are kinda insufferable so maybe there's a contender there for a cloning damage C2 lol).

I'd like to see C2 have a damage mechanism that would make sense to add a C1 OR to be combined with another C2 that eventually gets you to the point you can fix the remainder of the damage with a C1. 

In a perfect world C1s would grow independent of each other and you could use a combination of C2s to transfer damage to the most effective C1 you have available at the time. That or cough up the resources to make C3 investments.

**Comment by ExcessiveUseOfCobblestone** [comment]
maybe i should stop being a babby and just start meds from scratch.

**Comment by Fikou** [comment]
> maybe i should stop being a babby and just start meds from scratch.

do it bet you wont

**Comment by Krysonism** [comment]
The point of this chem is that you will have to live with a few points clone damage until you can get to cryox/clonex and a cold shower.

Requiring a tier 3 followup treatment for this particular chem makes interesting side treatment path that still fits into the new system.

The numbers could always be adjusted if you think 20% is too much

**Comment by CPTANT** [comment]
> 
> 
> maybe i should stop being a babby and just start meds from scratch.

Until someone draws out an actual plan for how meds should look as a whole these piecemeal PR's just don't make any sense.

**Comment by py01** [comment]
Can someone link to the cobby post that explains the terminology everyone is using?

**Comment by CRITAWAKETS** [comment]
hollstein's adduct is ridiculously OP. No damage slowdown with no downsides. The only other anti-damage slowdown stuff in the game are Legion Cores which are difficult to get along with possibly getting nerfed later as its currently very strong, and Muscle Stimulants which are only from strange seeds.

You know, the fact that you are merging code improvements with something this overpowered certainly does not help your credibility. Atleast atomize the reagent_container stuff so that if this gets denied, the thing that can be useful for other coders will still be in the game.

**Comment by Krysonism** [comment]
> 
> 
> hollstein's adduct is ridiculously OP. No damage slowdown with no downsides. The only other anti-damage slowdown stuff in the game are Legion Cores which are difficult to get along with possibly getting nerfed later as its currently very strong, and Muscle Stimulants which are only from strange seeds.
> 
> You know, the fact that you are merging code improvements with something this overpowered certainly does not help your credibility. Atleast atomize the reagent_container stuff so that if this gets denied, the thing that can be useful for other coders will still be in the game.

You have no crediblity if you are going to leave out that morphine is available roundstart and has a superior effect and a downside that can be easily mitigated.

**Comment by Dawson1917** [comment]
> You have no crediblity if you are going to leave out that morphine is available roundstart and has a superior effect and a downside that can be easily mitigated.

Morphine can only be in you for a very short time lest you get knocked out and has a visual screen effect so obnoxious that nobody ever uses it

**Comment by Shadowflame909** [comment]
>Clone damage

Aw man this is not epic at all. 

I hope in Cobby's perfect version of this Lings are removed from this game and traitors start off with 15 Telecrystals instead of 20.

This isn't epic

**Comment by necromanceranne** [comment]
You need rezadone which is hard to acquire without an emag to make hollstein's. Seems fine to me.

Also, I think people are WAY overblowing this chems lethality. 4 brute to .8 clone is completely unnoticable with about 5 units but you'll heal an immense amount of brute. Seems great to me as an emergency fix.

**Comment by bigfatbananacyclops** [comment]
I really hope the other old chems do not get removed, i think people dealing with this chems will be painful, because they will have to heal every damage the chems have healed, eventually turning into a cycle.

**Comment by SkeletalElite** [comment]
I dont think this chem should have the interaction with rezadone. Rezadone isn't exactly easy to acquire. If the chemists do actually manage to make it (which is very rare) then fine. yeah this will be powerful, but it requires quite a bit of effort to actually achieve for a relatively minor effect. The only reliable source of rezadone will be an upgraded mediborg but at that point you could also just use bicard since they have that too.

**Comment by necromanceranne** [comment]
I feel like the rezadone interaction is to prevent predosing this as a traitor to gain ridiculous amounts of regen. It would be extremely difficult to kill someone under the effects of both and having injected themselves with a miner syringe and has any amount of protective armor. All of which can be acquired with relative ease. (Seriously someone needs to address miner syringes)

**Comment by ExcessiveUseOfCobblestone** [comment]
can you add a commit that takes out stypic/silversulf for a testmerge? Won't do any good if people just avoid using it entirely.

**Comment by Krysonism** [comment]
What do I replace sulfa with?

Maybe replacing the bruise packs with 50u mitomidal minigels would be a better choice since it is supposed to be an emergency chem.

I think it would be a good fit for the white kits, since it allows a common crew members to heal themselves for about 100 brute relatively pain free, while disallowing extended rampages without first obtaining some cryox, clonex or rezadone.

I think if a testmerge that replaces styptic is attempted there would be immense backlash but gameplay would not change much due to the two other immensely powerful members of the axis of evil(salicylic and brute packs) being intact.

**Comment by Krysonism** [comment]
One thing I think is interesting with this chem is that I think many type 2 medicines will become a bit obsolete once the chemist makes the corresponding type 3, which can happen very quickly depending on the chemist. 

I think this avoids that by becoming a bit more relevant again late round due to having favourable interactions with pyrox, rezadone as well as cryox activation schemes.

**Comment by Krysonism** [comment]
I'd also like to point out that this can be ghetto crafted using a glowstick, lightbulb and titanium sheet(from the lathe or welding a shuttle type wall) and some fuel.

**Comment by ExcessiveUseOfCobblestone** [comment]
sorry not silver sulf.

Just want to be able to test this as if styp didn't exist (foreshadowing???)

**Comment by FloranOtten** [comment]
Cloning damage is a terrible idea. Not only is it cancer to fix, it's powerful like no other type of damage. It dusts you instead of crit. 

I can't read code and I don't know what 1*REAGENT METABOLIZATION means, so I'll just say it metabolizes at a rate of 1 per cycle. It'd now require about 120 units of the stuff to dust. a chemist with a repeating syringe gun can pump that out no problem, and from then you have to realize what it was, get to medbay and either hop into cryo for a few eternities, or chug charcoal THEN hop in cryo. Both of these cryo times are opportunities for the Chemist to kill you stone dead.

**Comment by ExcessiveUseOfCobblestone** [comment]
or they can just make one of the plentiful other chems that KO you and now you're at their mercy.

**Comment by SkeletalElite** [comment]
> or they can just make one of the plentiful other chems that KO you and now you're at their mercy.

at least the other chems don't literally permakill you without extra effort from the chemist to get rid of you.

**Comment by Krysonism** [comment]
I really don't see any way this would realistically dust you. 

Point me to the relevant code if you think otherwise.

**Comment by Krysonism** [comment]
As for its traitorous potential in general, it deals 1 brute and 0.8 clone when overdosed and makes you really dizzy. Not a great poison unless you are a medical traitor and want to feign incompetence.

Even then omnizine, thializid or rhigoxane are better choices.

**Comment by ExcessiveUseOfCobblestone** [comment]
only way it would is if you are using the cursed gambling machine that dusts you after reaching a certain damage threshold, I don't see any damage procs that prompt dusting from having too much clone damage.

**Comment by Krysonism** [comment]
clonedmg

Overdosing on this drug does not dust you, not even with supportive brute meds and CPR to remove the other damage types.

Even unloading a couple decloners into the mob did not dust it. 

Is this dusting thing even in the code i wonder or just a massive red herring?

**Comment by SkeletalElite** [comment]
> clonedmg
> 
> Overdosing on this drug does not dust you, not even with supportive brute meds and CPR to remove the other damage types.
> 
> Even unloading a couple decloners into the mob did not dust it.
> 
> Is this dusting thing even in the code i wonder or just a massive red herring?

Okay I guess its not a thing that exists. I still think it should be a different damage type and not clone damage, like toxin or something.

**Comment by wesoda25** [comment]
Do you guys mind actually preparing and balancing our medical system before forcing through all these changes? Chem system is in fucking shambles, stop adding things in small parts and make a real PR. Then it'll be easier to revert

**Comment by ExcessiveUseOfCobblestone** [comment]
Working on doing the chems from ground up so ima close this. If It's something i'm interested in afterwards i'll let you know.

**Pull request closed without merging**
