### PR TITLE
Trans Thigh-high and Knee-highs

### PR DESCRIPTION
**Pull request by sadkris**
## About The Pull Request

This literally just adds the sprites and entries for transgender thigh-highs and knee-highs as clothing options for socks.

## Why It's Good For The Game

Inclusivity, as we already have nonbinary and asexual-related clothing.

## Changelog

:cl:
add: Transgender-themed thigh-highs and knee-highs to the clothing options for socks
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by castawaynont** [comment]
goes hard

**Comment by LemonInTheDark** [comment]
Is this like, obtainable anywhere? do we just autolist socks in the preferences menu mothblocks

**Comment by LemonInTheDark** [comment]
Also for future don't pr from master it'll get you into trouble when you make another branch

**Comment by sadkris** [comment]
> Is this like, obtainable anywhere? do we just autolist socks in the preferences menu mothblocks

Essentially. Currently, it's just listed in the character appearance menu before you enter the shift

**Comment by sadkris** [comment]
Well, and changing at a dresser mid-round.

**Comment by LemonInTheDark** [comment]
Damn it mothblocks

**Comment by Mothblocks** [comment]
of course we do

**Comment by nianjiilical** [comment]
working on circuit coding while wearing them should give you a 0 strength positive moodlet

**Comment by bruhman8ghughug** [comment]
screenshit?

**Comment by Jackal-boop** [comment]
Based

**Review by Imaginos16 — APPROVED** [review]
Sprites are good, weird it wasn't a thing until now!

**Comment by BlueMemesauce** [comment]
Why not knee-high socks too?

**Comment by optimumtact** [comment]
> I know you only added thigh-high socks for the joke, but why not add knee-high socks too?

because it's bloat

**Comment by sadkris** [comment]
> I know you only added thigh-high socks for the joke, but why not add knee-high socks too?

Not enough motivation to make more sprites :>

**Comment by sadkris** [comment]
actually fuck it i'll do it now

**Comment by sadkris** [comment]
Pull request title and summary have been updated for my (distantly) imminent commit.

**Comment by sadkris** [comment]
We can rest easy now, knowing that both our knees and thighs are covered

**Comment by LemonInTheDark** [comment]
Pictures taken moments before disaster

**Comment by LemonInTheDark** [comment]
Fuck

**Comment by sadkris** [comment]
You sick fuck I have to wait another 12 minutes for these stupid-ass checks to finish

**Comment by sadkris** [comment]
On another note, I think it's just a false-positive. We'll see once these checks finish, but it's inconsistent with what I'm actually changing, so I think it's unrelated.

**Comment by LemonInTheDark** [comment]
image
brother these are error sprites

**Comment by sadkris** [comment]
It's completely unrelated to what I'm doing though, don't know how it could be related

**Comment by Mothblocks** [comment]
That's a brand new false positive if so

**Comment by sadkris** [comment]
Currently checking my local build to see if it's consistent

**Comment by Mothblocks** [comment]
Screenshot tests will finish in only a few minutes

**Comment by sadkris** [comment]
image

**Comment by sadkris** [comment]
hey look that thing i said was true was true, whaddyaknow

**Comment by Mothblocks** [comment]
It isn't that we didn't believe you but it's that this is the first time that has happened and it's very very concerning

**Comment by sadkris** [comment]
oh my god is the pull request about trans thigh-highs going to be the commit that reveals a glaring issue with the checks system

**Comment by Mothblocks** [comment]
Idk

**Comment by usnpeepoo** [comment]
Soulless -1

**Comment by optimumtact** [comment]
This is the dangers of bloating your PR!

**Comment by sadkris** [comment]
two sprites = bloat

**Comment by optimumtact** [comment]
1 sprite - pr works fine, no issues, was going to be merged

now, confusion, chaos, disaster!

**Comment by sadkris** [comment]
and 3 pending reviews!

**Comment by Bawhoppen** [comment]
How can one PR get so messed up

**Comment by toomykins** [comment]
the absolute state

**Comment by DeadliestDesire** [comment]
cringe

**Comment by Mothblocks** [comment]
why are you looking for several month old prs to get mad at loser

you have been banned from the repository

**Comment by pedr69** [comment]
are you... disagreeing with me over the internet? 
BANNED

**Comment by optimumtact** [comment]
yes you are

**Comment by Mothblocks** [comment]
only winners are allowed on the tg repository

**Comment by Bawhoppen** [comment]
this is a good Pr merge soon please

**Comment by toomykins** [comment]
I sure do love having my inbox spammed with transvestite shit

**Comment by Mothblocks** [comment]
no losers on my repository

**Comment by TheFakeElon** [comment]
the industrial revolution and it's consequences

**Pull request merged**
