### PR TITLE
Improved cakehat

### PR DESCRIPTION
**Pull request by Buggy123**
Now provides fire immunity and instantly kills anything.

### CODE REVIEW

**Comment by KazeEspada** [comment]
@Iamgoofball sniped you.

**Comment by Buggy123** [comment]
#16001 for lyfe

**Comment by KorPhaeron** [comment]
You missed the get sorry

**Comment by Buggy123** [comment]
#16000 @Iamgoofball

**Comment by PKPenguin321** [comment]
if there's any reason to bully goofball this is it tbh

**Comment by Xhuis** [comment]
Prankred 4Head

**Pull request closed without merging**
