### PR TITLE
removes slip damage

### PR DESCRIPTION
**Pull request by PKPenguin321**
im not actually sure if this pr will work but yeah this removes the stupid 5 damage you got when slipping because it was stupid

### CODE REVIEW

**Comment by PKPenguin321** [comment]
oh shit trips

**Comment by demonfiren** [comment]
>trips
>not slips

**Comment by MrPerson** [comment]
It might be interesting to keep the damage for some slips, although I couldn't think of any case where we might want that besides maybe a banana mutation.

**Comment by yackemflam** [comment]
Pretty dumb really. Why wouldn't you get hurt when slipping on water? If you are really butthurt about the 5 damage just eat a donut or a donk pocket

**Comment by PKPenguin321** [comment]
oh yeah dude this is totally i ded. 100%. i am *sooo* butthurt about 5 damage per slip.

don't be a fucking idiot lmao

**Comment by RandomMarine** [comment]
Slips. Now with 100% more asimov approval.

**Comment by xxalpha** [comment]
:-1:

**Comment by killerx09** [comment]
I'm pretty sure slipping damage was in the first place was because it was annoying.

**Comment by KazeEspada** [comment]
How about make it a percent chance of getting hurt, and then a tiny percentage of getting really hurt.

**Comment by Aloraydrel** [comment]
or just remove it tbh

**Comment by xxalpha** [comment]
>percent chance

No.

**Comment by Fox-McCloud** [comment]
lube should do damage when slipping; it always has.

I stated, quite emphatically, in the PR that increased slipping damage, that this was going to be problematic, one day.

Just make it do the original *two* (2) damage instead of this ridiculous 5.

**Comment by TheNightingale** [comment]
It's not about how much damage it does, it's about that it does damage. Asimov silicons cry whenever a Clown slips someone.

**Comment by Fox-McCloud** [comment]
That's why it should be *lube* only.

**Comment by PKPenguin321** [comment]
>10 thumbs up

i think this may be a record

**Comment by KorPhaeron** [comment]
hugbox

**Comment by PKPenguin321** [comment]
memebox

**Comment by Incomptinence** [comment]
Thank you it is just so fucking pointless.

**Pull request merged**
