### PR TITLE
Removes Meta medbay light switch

### PR DESCRIPTION
**Pull request by MidoriWroth**
## About The Pull Request

Removes the light switch in Meta Station's central medbay, as it was was tucked away at the very bottom of the area in chemical storage for some reason.

## Why It's Good For The Game

I've probably played hundreds of rounds on Meta station, and i had absolutely no idea the light switch for more than half of medbay's lights was for some reason tucked super far away in an entirely different room. This is a bit silly.

## Changelog

:cl:
fix: Removes the Meta central medbay light switch.
/:cl:

### CODE REVIEW

**Comment by MidoriWroth** [comment]
Uh I have no idea what that error means, does anyone else?

**Comment by Jolly-66** [comment]
> Uh I have no idea what that error means, does anyone else?

Unrelated to your PR
The infamous rats

**Comment by MidoriWroth** [comment]
> > Uh I have no idea what that error means, does anyone else?
> 
> Unrelated to your PR The infamous rats

Anything I can do or do I just gotta wait for someone to fix it?

**Comment by Jolly-66** [comment]
> Reply chain

🤷

**Comment by san7890** [comment]
You can have more than one light switch per area by the way. The checks will re-run if you add another commit to your branch.

**Review by san7890 — CHANGES_REQUESTED** [review]
I actually wanted to double-check my above comment, and you can have multiple light switches in a singular area all operate perfectly fine. Could you please keep the one in the chemical room, and maybe have another one in another "central" spot in medbay? It's ultimately up to you, but I just want to ensure that you knew about this.

**Comment by MidoriWroth** [comment]
> I actually wanted to double-check my above comment, and you can have multiple light switches in a singular area all operate perfectly fine. Could you please keep the one in the chemical room, and maybe have another one in another "central" spot in medbay? It's ultimately up to you, but I just want to ensure that you knew about this.

Yeah I was actually doing everything you said as we speak lmao

**Comment by MidoriWroth** [comment]
Alright what's the deal this time

**Comment by Jolly-66** [comment]
> Alright what's the deal this time

MapDiffBot (1)
AA will now come to this PR with a pitchfork and torch in hand (not really)

**Comment by MidoriWroth** [comment]
Yeah idk anymore lmao

**Comment by Son-of-Space** [comment]
Yes. Hallways don't have lightswitches. San can be wrong sometimes. : )

**Review by san7890 — CHANGES_REQUESTED** [review]
Apologies for sniping you with another change.

I was reminded of a conversation I had earlier... and yeah, hallways probably shouldn't have lightswitches in the first place. The whole thing with it being in that small chemical cubby room was probably a mistake/oversight, and it'd be nice for you to just rework this PR so that Medbay Central doesn't have _any_ light switches.

If they truly want no lights in Medbay (for whatever reason), they can leverage the APC.

**Comment by MidoriWroth** [comment]
> Apologies for sniping you with another change.
> 
> I was reminded of a conversation I had earlier... and yeah, hallways probably shouldn't have lightswitches in the first place. The whole thing with it being in that small chemical cubby room was probably a mistake/oversight, and it'd be nice for you to just rework this PR so that Medbay Central doesn't have _any_ light switches.
> 
> If they truly want no lights in Medbay (for whatever reason), they can leverage the APC.

How will people turn the lights on and off if there are no switches?

**Comment by san7890** [comment]
> How will people turn the lights on and off if there are no switches?

The APC.

**Comment by MidoriWroth** [comment]
> > How will people turn the lights on and off if there are no switches?
> 
> The APC.

I... don't think that's the best idea, honestly, especially when that shift start modifier happens where the lights start off or broke, people will have to wait for the AI/a borg/atmos tech to do it. Why remove the switches? That's just gonna be super inconvenient for everyone.

**Comment by san7890** [comment]
> I... don't think that's the best idea, honestly, especially when that shift start modifier happens where the lights start off or broke, people will have to wait for the AI/a borg/engi to do it. Why remove the switches? That's just gonna be super inconvenient for everyone.

It's a primary hallway in medbay. I've spoken with EOB (lead maptainer) about this same thing.

image

"Should be well lit at all times" is the key here. Having a light switch accessible to any jack and jill is not conducive to proper hallways. This PR probably won't go through in it's current state, I believe the addition of the light switch to that chemical storage cubby was an oversight, and I would greatly appreciate to see it corrected.

**Comment by san7890** [comment]
Was there a saving issue? You only removed one in commit 2a296d28a2b7fa081cf7b47a88e0e6a454e79dbe .

**Comment by MidoriWroth** [comment]
Sorry, I screwed up, gonna rework all this from scratch lmao

**Comment by san7890** [comment]
That's fine, best of luck.

**Pull request closed without merging**
