### PR TITLE
Compresses icons, all new/modified icons are required to be compressed

### PR DESCRIPTION
**Pull request by nicbn**
I used [oxipng](https://github.com/shssoichiro/oxipng) to compress most of the icons .

```
oxipng -o 4 -i 0 --keep zTXt -a -r <PATH>
```

It's now a requirement on `CONTRIBUTING.md` that all changed/new icons file must be losslessly compressed, with oxipng as a recommendation.

icons size: 37 MB -> 29 MB
rsc size: 82 MB -> 76 MB

### CODE REVIEW

**Comment by actioninja** [comment]
We could also just add this to some kind of automatic toolchain

**Comment by ShizCalev** [comment]
dmi churn

**Comment by PKPenguin321** [comment]
6 MB save is huge considering the number of times that gets distributed a day, nice

**Comment by nicbn** [comment]
We could probably save some more space by using `-Z` but it's really slow to use it in the whole icon folder at once

**Comment by SpaceManiac** [comment]
they are just going to get uncrushed as soon as anyone modifies them

**Comment by nicbn** [comment]
> I suggest requiring on CONTRIBUTING.md or something all changed/new icons file to be compressed, but that's outside of the scope of this PR.

**Comment by SpaceManiac** [comment]
It's in scope. It doesn't make sense to one-time crush all the icons; it only makes sense if doing so is both policy and enforceable. (Sounds do not see anywhere near as much edit activity.)

**Comment by nicbn** [comment]
Ok

**Comment by SpaceManiac** [comment]
Would it make sense to have a Git pre-commit hook to do this?
What about a Travis lint to check whether the icons are crushed or not? (Is oxipng/optipng/pngcrush idempotent?)
Is all this worth the extra installation effort it will impose on new spriters?

**Comment by actioninja** [comment]
I would hope at the barest minimum it would be easier than using mapmerger or completely automatic. Mapmerger is not particularly hard to use and it's enough to scare away a good amount of people looking to contribute.

**Comment by SpaceManiac** [comment]
The map merge script is automatic (after installing Python 3 and running a one-time .bat file), but it is incompatible with many GUI git clients, including GitHub Desktop (TortoiseGit is fine). A script for crushing PNG files would be in a similar position. It would also carry the dependency of the PNG crusher itself.

**Comment by nicbn** [comment]
> Would it make sense to have a Git pre-commit hook to do this?

I've never used Git hooks, but it may be a good idea.

> What about a Travis lint to check whether the icons are crushed or not? (Is oxipng/optipng/pngcrush idempotent?)

Yeah if oxipng compresses the file with `-o X`, compressing it again with `-o Y` with Y ≤ X won't modify the file. However, it may be quite expensive to ask Travis to run oxipng (even with `-o 2`) (and optipng and pngcrush are even slower).

> Is all this worth the extra installation effort it will impose on new spriters?

Well 6 MB savings are quite significant. `station_explosion.dmi` alone saved 868 KB, which is a lot of bytes for a single file. Some files got reduced to less than 5% of the original file size.
As for the effort, if someone compiles the tool for Linux for me (contact me via Discord in this case), I'll add Windows and Linux binaries to the tools of the repo.

**Comment by SpaceManiac** [comment]
Is there any subset of the icons that don't change very often and we can get good savings by compressing once? I don't want to just leave the savings on the table without consideration but the contributor burden might not be worth it

**Comment by nicbn** [comment]
I'll get back to this when I write a git hook for it

**Pull request closed without merging**
