### PR TITLE
removes erp cuffs

### PR DESCRIPTION
**Pull request by praisenarsie**
this was added 2 years ago btw

thanks to @spacedong the /tg/ codebase hater at hippie for finding this

### CODE REVIEW

**Comment by kevinz000** [comment]
No

**Comment by Mercenaryblue** [comment]
Yes.

**Comment by praisenarsie** [comment]
Yes

**Comment by dreamcrab** [comment]
YES ALSO

**Comment by Alecw155** [comment]
hard yes

**Comment by optimumtact** [comment]
it's not used so may as well

**Comment by Repukan** [comment]
Yes

**Comment by banthebantz** [comment]
Hard Y

**Review by ninjanomnom — APPROVED** [review]

**Comment by Hatfish** [comment]
Hard~ yes.

**Comment by Spacedong** [comment]
yes

**Comment by GuyonBroadway** [comment]
Yes

**Comment by Bawhoppen** [comment]
I mean it doesn't even have a working sprite and is literally no different than actual handcuffs so I guess it doesn't matter if it goes

But jeez, people have some obsession with anything related to ERP

**Comment by deathride58** [comment]
These have a much faster breakout time than normal cuffs. They're mainly there for adminbus. The only place where they see actual use by players is Citadel, but they see more use for crude clown pranks than actual ERP there.

**Comment by Bawhoppen** [comment]
Oh I guess they do have a working sprite it's just bad

**Comment by banthebantz** [comment]
pwvrlcr

**Comment by deathride58** [comment]
Fastest closed mirrored PR in Cit's history tbh

**Comment by GuyonBroadway** [comment]
image

**Comment by Hatterhat** [comment]
i knew kevinz was in the erp catspiracy, but not this deep in

**Comment by PKPenguin321** [comment]
HOly shit kev HAHAHAHAHA

**Pull request merged**
