### PR TITLE
Outpost45 update pain

### PR DESCRIPTION
**Pull request by Yobrocharlie**
## About The Pull Request

Outpost45 is as of now, over eight years old, and after so much time it has gotten very, very little attention, this fixes that and completely changes the gateway destination to have much more than it currently does both in terms of area to explore, story to learn, and stuff to grab.
## Why It's Good For The Game

As of right now outpost45 is the worst gateway destination and most people never even touch it once they see its ominous purple glow. Not only that but in a casual conversation in a ticket I was talking with an admin about it and they said "Well then if you don't like it anybody can contribute" and so I did. (Extreme thank you to pumpkin0, vekkter, and jolly for helping me learn how to PR, how to github, and how to map.)
## Changelog

Adds a small landing zone and expands on the already existing small un-inhabited now inhabited xenomorph nest and adds a few marine bodies. Something to note is that the end room loot for this gateway is heavy armor a heavy marine helm and a backpack powersource.
:cl:
add: Added more stuff to make outpost45 (the plasma gateway destination) not completely irrelevant and it now has fairly great stuff if you know your kiting or if your an experienced ruin diver.
/:cl:

### CODE REVIEW

**Comment by Yobrocharlie** [comment]
if this causes runtimes i will cry

**Comment by necromanceranne** [comment]
We've got a rogue CI failure ongoing at the moment, so your PR is going to fail until that is fixed. It's nothing necessarily related to your PR.

**Comment by ZephyrTFA** [comment]
Your linters are failing due to stacked cables.

**Comment by ZephyrTFA** [comment]
what da hell
image

**Comment by Yobrocharlie** [comment]
Let me fix my cable management

**Comment by Yobrocharlie** [comment]
fixed

**Comment by Yobrocharlie** [comment]
why is this a draft instead of just open?

**Comment by necromanceranne** [comment]
It got set to draft so that you could make the changes necessary to fix the linters. You can undraft it yourself, there should be a button somewhere on this page (if you're reading this on github and this comment).

**Comment by Yobrocharlie** [comment]
> It got set to draft so that you could make the changes necessary to fix the linters. You can undraft it yourself, there should be a button somewhere on this page (if you're reading this on github and this comment).

thanks

**Comment by Maurukas** [comment]
It does not look like you've pushed your changes yet.

**Comment by Yobrocharlie** [comment]
Can some mappers please look over this like seriously

**Review by Jolly-66 — COMMENTED** [review]
Btw

image

**Comment by Yobrocharlie** [comment]
Can somebody do me a favor and go bug the Mainers about this one or at least can I get a reason why this is being ignored

**Comment by Yobrocharlie** [comment]
Thanks jolly let me fix that, are there any problems besides that?

**Comment by Yobrocharlie** [comment]
it seems that github mightve been wrong about the space tile 
weird

**Comment by Yobrocharlie** [comment]
can somebody un-stale this?

**Comment by Yobrocharlie** [comment]
So uh

**Review by Maurukas — CHANGES_REQUESTED** [review]
Two issues. You have a large number of active turfs added around the changed area. This usually is caused by placing tiles with different starting atmospheres next to each other. Make sure you are using tiles with the same starting gasses:
image


Second, if you're going to rename the map file, you also need to update `config/awaymissionconfig.txt` with the new map file name.

**Comment by Yobrocharlie** [comment]
> Two issues. You have a large number of active turfs added around the changed area. This usually is caused by placing tiles with different starting atmospheres next to each other. Make sure you are using tiles with the same starting gasses: image
> 
> Second, if you're going to rename the map file, you also need to update `config/awaymissionconfig.txt` with the new map file name.

They have the exact same starting atmos according to strongDMM,

however the outpost45 atmos just seems especially fucked ever since there was the PR that removed custom atmos tiles.

it may be very possible to just not have non active tiles that are not the asteroid sand.

**Comment by Yobrocharlie** [comment]
Yup i just checked in strongDMM they have the exact same initial gas mix.

**Comment by Yobrocharlie** [comment]
I will need around 16 hours to resolve the merge conflicts

**Comment by Ghommie** [comment]
Sorry Github-actions, but this PR is staler than that loaf of bread I left in the shelf for a whole month that one time. It was still good for soup, but still...

**Pull request closed without merging**
