### PR TITLE
Adds "Map Edit" to the GBP values

### PR DESCRIPTION
**Pull request by Helianthus00**
## About The Pull Request
This adds "Map Edit" in as +2 GBP. Gives a small reward to those that actually do clean up maps, without relying on the "Fix" or other positive tags. This makes it unlikely to actually change GBP values in most cases, but in the small cases it'll give some sort of reward for dealing with likely map conflicts.

## Why It's Good For The Game
Incentivizes changing maps for the better. Better maps with more of the game features is certainly a good thing.

### CODE REVIEW

**Comment by Mothblocks** [comment]
"Map Edit" is automatically applied to everything that even grazes them, it's probably not a great idea to attach GBP to that.

Also, for the record, "Needs Add. Mapping" is a label we've used exactly once ever.

**Comment by Helianthus00** [comment]
> "Map Edit" is automatically applied to everything that even grazes them, it's probably not a great idea to attach GBP to that.
> 
> Also, for the record, "Needs Add. Mapping" is a label we've used exactly once ever.

What about reducing the Map Edit to +1 then? I still think it's worth rewarding people for touching the maps, at the very least because map conflicts are the absolute worst to fix. 

As for Needs Add. Mapping, it is underused currently, in my opinion. At least a few PRs could have had that attached. However, now that it isn't just a label and has points attached to it, there will be more of a reason to use it rather than just leaving a comment over it.

**Comment by SuperNovaa41** [comment]
> Also, for the record, "Needs Add. Mapping" is a label we've used exactly once ever.

It definitely needs to be used more. Cryopods is a big one I can think of off the top of my head that needed the tag

**Comment by Qustinnus** [comment]
it literaly will never ever do anything because any PR that needs mapping is a feature and features are -10 so it will have zero effect.

**Comment by Helianthus00** [comment]
> it literaly will never ever do anything because any PR that needs mapping is a feature and features are -10 so it will have zero effect.

Right. I forgot about the high vs low thing. Well, I can just change "Needs Add. Mapping" to -15 for the effect I was hoping for. Also, this means that keeping "Map Edit" at 2 is fine, since it won't result in a positive result of GBP unless their only positive is QoL or a grammar fix, which again I think is worth the extra 1 for having to deal with potential map conflicts.

**Comment by Qustinnus** [comment]
it seems a bit extreme, features already take up loads of effort and all you're gonna get is people low-effort shitting their features into maps.

**Comment by Helianthus00** [comment]
> it seems a bit extreme, features already take up loads of effort and all you're gonna get is people low-effort shitting their features into maps.

What is the point of a feature that requires map edits if it's not put into a map though?

**Comment by Qustinnus** [comment]
to be mapped in in the future.

just know that the more weight you put on feature coders to map in their features the more likely you'll see a larger push to move all but 1 map out of the repo.

**Comment by Helianthus00** [comment]
Then you get things like #49644 that are over a year old and still not in the game. Why waste time coding it in the first place if nobody will use it?

**Comment by Mothblocks** [comment]
What does that PR have to do with mapping? Waterworks is a player accessible feature.

**Comment by Helianthus00** [comment]
> What does that PR have to do with mapping? Waterworks is a player accessible feature.

I mean specifically the mapped portions of that pr. I only mention it by name because this pr I made today (#58599) is what made me think of how this is an issue. Cryopods are another good example though (as SuperNovaa41 brought up). Even if they do have a current pr up to add them, it's kind of dumb to require a mapper to use their own GBP in order to map in another person's feature when they could have just done it themselves. 

Maybe a "Map Feature" tag then at a -2? I don't really want to suggest adding tags, as that is completely out of my hands, but just anything to make this less of a burden on mappers who just want to add in those features that have been underutilized. At least that would not affect any featurecoders that did decide to map their things and it would make mappers who did decide to add in old features break even instead of -10.

**Comment by Qustinnus** [comment]
how would a mapper lose GBP for mapping something in

**Comment by Helianthus00** [comment]
> how would a mapper lose GBP for mapping something in

When it gets a "Feature" label, is that not how it works? Unless I am misunderstanding the system, that's the situation I am frustrated at. There are a bunch of map edit prs that get this label when it isn't necessarily adding a new feature. In general, it seems like the current tags do not fit well with map changes.

**Comment by Mothblocks** [comment]
Which ones do you consider not adding new features? What defines a feature is pretty broad.

**Comment by Helianthus00** [comment]
> Which ones do you consider not adding new features? What defines a feature is pretty broad.

#58599 and #58449 add existing features, not new ones. #58601 , #58271 , and #57403 I wouldn't consider features at all. Those are just from the past 2 months. I guess my entire point is, a code feature and a map feature are different and should be weighted as differently. My solution was to add the "Map Edit" label to reduce some of the negative of the normal "Feature" label, so that the feature label isn't quite as heavy on these map edits that aren't quite adding new features.

**Comment by JJRcop** [comment]
"Needs Addl. Mapping" should be a no merge kind of deal

**Comment by Qustinnus** [comment]
those tags are auto-added, if you ping someone like me "hey i made a map edit and it added the feature tag" it will obviously be removed. As soon as you type add in your pr title the bot will assume its a feature, its obviously not so just ask someone to remove it.

**Comment by Helianthus00** [comment]
As mothblocks said, what defines a feature is pretty broad. I want to be sure that we aren't actually considering those prs I linked to be features. If that is determined to be a "feature", fine, I just want the definition to be clearer when it comes to map edits. 

Though I do think that is a poor permanent solution towards that half of the issue and I still think giving "Map Edit" a +2 is a good idea.

**Comment by Qustinnus** [comment]
the point of the feature tag is disinsinuating feature coders, not make mappers pay a tax for bringing maps up to date, that would obviously be ridiculous and is not the point of the tag.

**Comment by Helianthus00** [comment]
Fair enough, removing "Needs Add. Mapping". I still think "Map Edits" deserve GBP though. At the very least, it's a small bit for those that spend their time mapping, and will likely get overwritten by the "Fix" or other tags anyway.

**Comment by Zytolg** [comment]
> Fair enough, removing "Needs Add. Mapping". I still think "Map Edits" deserve GBP though. At the very least, it's a small bit for those that spend their time mapping, and will likely get overwritten by the "Fix" or other tags anyway. Also gives feature coders more of an incentive to map their things in anyway, since it'll give them -8 instead of -10 overall for that feature, if they have no other positive tags.

Allow me, a Mapper, to disagree on this point. Unlike code changes where you either have a feature, or someone doing something (anything) to clean up some code, map changes are much more varied. Yes, we do have issues such as doublewires, and double pipes that deserve GBP when someone endeavors to fix them, but at the same time, we also have stylistic changes that don't necessarily effect the game (perhaps you want to add potted plants to cargo to make it look better). The latter isn't necessarily a feature, but it isn't a fix either. Of course we have full blown features like my Metastation Science rework, but the point here, is that mapedits take on a myriad of forms, and not all of them are necessarily directed towards stuff we want to fix. 

If a feature demands a map change, that map change should be included in the feature PR. In the case this doesn't happen though, and it is left to someone else to map something that should be in the game in- well, I think it's only fair that the mapper isn't punished for adding something intended to be in maps. This is of course a special case, and Maintainers can already negate GBP changes if they choose to do so with the GBP No Update tag. I don't see why we'd need to change that in the specific case. 

Finally in the case proposed here, I don't necessarily believe that incentivizing feature map edits with GBP ensures a quality change. For example, it's one thing to add something to a map (say you repurpose a small room in maint for your feature), however it's a completely different thing to work your addition into to map and have it feel like it belongs. We can shoehorn anything in, but it'll probably feel bad if we do that. It's a lot more challenging and time consuming to work things in to an already densely populated scene. It's also something that, once again, you can't really measure with a "Map Edit".

If you need help with mapping, we have mappers living under the coderbus in the mapbus on the discord. You might be able to even bribe one to make the changes for you with the prospect of #freeChangeNoGBPcost. GBP isn't too hard to gather up in any case either. Ultimately all major map edits are due to go through maptainer, but it'd be nice to make his life easier by ensuring that they are of the quality that the mapemperor demands.

**Comment by Mothblocks** [comment]
Yeah, I'm not really interested in map edits giving GBP as long as it's an automated label (which it should be).

Any PR that gets labelled Feature only because they use "add" (correctly) should have the Feature label removed from it from a maintainer (you're probably able to just ask, too). For example, I removed a "Feature" label from a PR the other day that just added laptop vendors to a few maps that didn't have one.

**Pull request closed without merging**
