### PR TITLE
Colossus's attack patterns are no longer always exactly the same

### PR DESCRIPTION
**Pull request by ChangelingRain**
They're generally similar but overall not nearly as predictable.

Spirals in general are less predictable as to where they start, and double spiral may produce two, non-overlapping spirals(ie; moving in the same direction)

Added a chance for the directional shot attack to fire at both cardinal and diagonal at once, but only do so twice, giving a bigger window for it to be attacked afterwards.
Directional shots also fire slightly faster.
## NO WAVEDASHING

Cleans up some code/makes it more readable at a glance.

### CODE REVIEW

**Comment by AnonymousNow** [comment]
Do you just watch people fight megafauna and nerf whatever methods they used afterwards?

I swear this is the third or fourth time I've seen a PR turn up with such suspicious timing.

**Comment by Darkgenerallord** [comment]
I swear to god any time I speak in OOC or deadchat about megafauna, it's recorded and then changed.

**Comment by ChangelingRain** [comment]
Haha was someone fighting a colossus just now that's hilarious but I wasn't actually on the server

**Comment by Darkgenerallord** [comment]
I literally just killed a colossus, yeah.

**Comment by Darkgenerallord** [comment]
Yep.

**Comment by Core0verload** [comment]
If you want to make megafauna unkillable, just slap `GODMODE` on them and end it.

**Comment by Darkgenerallord** [comment]
Also, yeah. This makes the colossus way too hard, to the point at which it's almost unfeasible.

**Comment by ChangelingRain** [comment]
What about this actually makes it hard? Not being able to immediately tell where the safe zones for the spiral attacks are?

**Comment by Darkgenerallord** [comment]
Yeah, the spirals. The spirals are pretty hard to dodge even knowing the safe zones, without knowing it's pretty much just a 'fuck you' once you get them below 400 health.

**Comment by Darkgenerallord** [comment]
Also uh, making it shoot cardinal and diagonal at once pretty much removes the one opportunity in which you can safely attack.

**Comment by ChangelingRain** [comment]
If it fires both at once, it has a larger window where you can attack it because it fires the same amount of bolts as them spread out. This wasn't actually clear from the PR description.

**Comment by Darkgenerallord** [comment]
I'm fine with that, then. Die/Judgement might be too dangerous with randomized safe spots, though I haven't been able to see it in game, so I can't judge it.

**Comment by PKPenguin321** [comment]
this does not actually prevent wavedashing

**Comment by KorPhaeron** [comment]
Punishing people for learning attack patterns seems weird

**Pull request closed without merging**
