### PR TITLE
Revert "Update GBP action from v1 to v1.1"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#57235
Maintainer request
Discord_TfkFewSsUT
24hourrule

### CODE REVIEW

**Comment by Timberpoes** [comment]
Shitposts go in the hut.

**Comment by Mothblocks** [comment]
this dude

**Comment by Kylerace** [comment]
we truly live in a society

**Comment by Kylerace** [comment]
:trollface:

**Pull request closed without merging**
