### PR TITLE
Removes an unnecessary file causing github security warnings on tgui, also updates/downgrades some dependencies to ensure a build

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
@neersighted thoughts?

The lock file was mrty's goof that somehow got merged. I'm not familiar enough with the npm ecosystem to go for a more comprehensive upgrade

DNM until i test this ingame

### CODE REVIEW

**Comment by neersighted** [comment]
`package-lock` is actually pretty important, and makes npm dependencies much more sane. I'll see about upgrading to a newer NPM and saner shrinkwrap file soon.

**Comment by Cyberboss** [comment]
Debatable whether to even bother acting on this since all js is client side anyway

**Comment by vuonojenmustaturska** [comment]
@neersighted package-lock was not actually contributed in a sane manner, it comes from mrty's dirty working dir

**Comment by optimumtact** [comment]
have you tried pressing the dismiss button you european

**Comment by CosmicScientist** [comment]
Europeans never click dismiss. We enjoy our ~~cookie~~ meaningless security warnings.

**Comment by AnturK** [comment]
Someone can readd clean lockfile later.

**Pull request merged**
