### PR TITLE
Woefully needed buff to cake hat

### PR DESCRIPTION
**Pull request by Incoming5643**
People who wear the lit cake hat will be inflicted with a disease that slowly turns them into a birthday cake. 
It can be cured at any point by taking the hat off, but why would you? SHIT IS SO FUCKING BITCHING.

http://www.ss13.eu/phpbb/viewtopic.php?f=3&t=3241

### CODE REVIEW

**Comment by Shadowlight213** [comment]
@duncathan @tkdrg Re-open this pr pls.

**Comment by PKPenguin321** [comment]
Holy fuck, why did this get closed??? This is fucking genius

**Comment by PKPenguin321** [comment]
Yyyyeeeeeeaaaaaaahhhhh

This has been open way more than 24 hours, merge immediately

**Comment by Shadowlight213** [comment]
@PKPenguin321 can't. Merge conflicts

**Comment by Miauw62** [comment]
smh tbh fam

**Comment by PKPenguin321** [comment]
cmon incoming you can fix it i believe in you

**Comment by Shadowlight213** [comment]
@Incoming5643 come one man. Best feature needs to be merged.

**Comment by duncathan** [comment]
conflicts AND failed travis :+1:

**Comment by Incoming5643** [comment]
N O T  W O R T H  T H E  J O K E

**Comment by PKPenguin321** [comment]
incoming please just remake it i beg you this is too good

**Comment by Shadowlight213** [comment]
@Incoming5643 pls. do it. pls.

**Pull request closed without merging**
