### PR TITLE
Fixes projectiles not hitting people resting, a bit of refactoring of how projectile target collision is done

### PR DESCRIPTION
**Pull request by silicons**
Everything now uses can_hit_target, some checks were moved around, living canpass moved to living movement, and check_bitfield() define helper now has extra () wrapping for peace of mind.

### CODE REVIEW

**Comment by subject217** [comment]
It was already nerfed. It working right now is a bug.

**Comment by WarRage333** [comment]
So if you shoot past someone(didn't click on their sprite) and they are resting they get hit?

Sounds dumb

**Comment by necromanceranne** [comment]
Thank goodness this was getting stupid.

**Comment by kevinz000** [comment]
Resting people NOT getting hit is the dumb thing and is a bug, and it's already been fixed once but broke again.
Hopefully this'll be the last time I have to fix it (or rewrite projectiles) before pixel movement is done.

**Comment by imsxz** [comment]
im a brainlet so if its not too much trouble id like to make sure, bullets wont hit stunned/dead/otherwise forced to crawl people right? only people that use the rest verb

**Comment by subject217** [comment]
that is the intended behavior imsxz

**Comment by kevinz000** [comment]
Bullets check for if the mob has STAND, MOVE, or USE ITEM flags, and will hit them if they have any of the three and are not in softcrit. This should make people Paralyze()d (hard stunned) not get hit, but getting just Stun()ed or Knockdown()ed still makes you bullet vulnerable, as Stun() makes you unable to use items but you are still standing (and therefore a dense mob which makes you skip these checks entirely) and Knockdown() forces you to the ground but you're still able to use items.
Immobilize() which nothing uses right now will also make you get hit as you are still standing and can use items.

**Comment by HomocidlePancakes** [comment]
Ok. Here is an epic idea to cuck warops. Fill a corridor with beds. Get monkeycubes from benoxeno/botany. Bucklecuff each one of them. Watch as their bullets hit the monkeys and just stunbaton them to death, or throw a water/potas explosive lance bacause it's unaffected by it.

**Comment by kevinz000** [comment]
@optimumtact On the projectile side, it has a permutated variable (that is admittedly bad because it makes things like looping piercing projectiles not hit someone twice but that can be fixed in a later PR to someday remove the variable entirely so that's temporary)
On the mob side, CanPass returns TRUE regardless of if the projectile hits or is dense so the turf movement code doesn't try to block the projectile a second time.

**Comment by kevinz000** [comment]
@optimumtact I put it in CanPass() to return true because I wanted can_hit_target() to determine whether the projectile should bump it, and if it returned true it might result in an infinite loop since projectiles just keep stepping towards their target even if something is blocking it, the trajectory won't make it forcemove across something blocking it, usually. However I haven't tested having it as TRUE so..

**Comment by HideAndSeekLOGIC** [comment]
At this point, this is more a feature than a bug since there is really no other way to have a chance of avoiding projectile spam without special items.

To those who are mad at the entire prospect of "I can't shoot three tasers worth of disablers down a hallway and cuff everyone involved at my leisure" or "I can't bother to take half a second to click someone literally crawling", come the fuck on. Resting doesn't make you anywhere near invincible but it does make you slow as fuck and it does put you at the mercy of someone who has a melee alternative (or, someone who has the ability to click things). All this doesn't even take into account that getting back up from a rest takes a few seconds of lying still, enough time for someone to shove a few lasers or a stunbaton up your ass. Or that landing even one disabler on that person essentially puts the tactical crawler into a standstill.

Either that or make clicking adjacent tiles to the resting person result in hits too, it'd still be a good compromise. Just, make laser spam down corridors at least somewhat survivable.

**Comment by subject217** [comment]
get this merged already so the crawl gang morons fuck off again

**Comment by ATH1909** [comment]
I personally like tactical crawling- it adds another element of skill to ranged combat, especially if you have access to smoke.

**Comment by kevinz000** [comment]
@optimumtact I uh, don't have a way of letting the projectile pass without returning true on canpass if the can_hit_target fails.

**Comment by HideAndSeekLOGIC** [comment]
@subject217 learn to aim you dumb fucking cunt

**Comment by subject217** [comment]
lol ok bye

**Comment by optimumtact** [comment]
@HideAndSeekLOGIC lose the language, only warning, next infraction will be a github ban.

**Comment by optimumtact** [comment]
@kevinz000 conflicts

**Comment by optimumtact** [comment]
you fucking goof, you changed the lineendings I HOPE YOUR FAMILY HAS A NICE CHRISTMAS

**Comment by optimumtact** [comment]
Still not keen on that bump hidden in the cross, but not sure if there's a better way to fix it

**Pull request merged**
