### PR TITLE
fix facehuggers & clean up facehugger attach code

### PR DESCRIPTION
**Pull request by forkingpath**
fix: facehugger attach code was difficult to understand and modify, streamlined it and extracted validation to its own proc
add: `isdevil()` define (checks for `/mob/living/carbon/true_devil` only)
:cl: karlnp
fix: made facehuggers work again
/:cl:

tested locally.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Your changelog name isn't your PR name

**Comment by karlnp** [comment]
OK. I followed the guide on the wiki this time and made it a username, but that page also doesn't seem to match PULL_REQUEST_TEMPLATE.md, so I don't know what the right thing to do it.

**Comment by Cyberboss** [comment]
:cl: karlnp

**Comment by Cyberboss** [comment]
Also, call me a shitcoder but I fail to see how that code breaks facehugging

**Comment by karlnp** [comment]
`if(!Corgi && !Carb.head)`
means 'if you're not a corgi and you're not wearing anything on your head', so facehugger attachment failed on all non-corgi non-hat-wearing targets.

**Comment by Cyberboss** [comment]
Oh shit, I thought that was the head LIMB.

**Comment by karlnp** [comment]
Yeah, easy mistake to make. I did it too until someone clarified in IRC.

**Comment by Armhulen** [comment]
>aliens have to put hats on hosts to facehug them
space station 13 is a special place

**Comment by MimicFaux** [comment]
Well shit. That explains why I was having so much trouble as a xeno.

**Pull request merged**
