### PR TITLE
New Captain Laser Sprite

### PR DESCRIPTION
**Pull request by 13spacemen**
## About The Pull Request
New obj sprite for the Cap's laser gun
By @DimWhat https://github.com/DimWhat

## Why It's Good For The Game
That sprite is ancient, the new one is a much needed improvement

I asked DimWhat for permission before making this PR

## Changelog

:cl:
imageadd: New captain laser gun sprite
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
If there is any improvement to be made, its making that square part of the front less square. And maybe reintroducing the blue stripe to break up the colours a bit.

**Comment by Arctrooper8** [comment]
Personally I think the old one is just superior. It's got a lot more detail and it feels like a lot of that detail has been lost in this new sprite. It also visually doesn't make sense for the cap's laser gun to be that sleek or fancy looking, it's the cap's antique gun and should seem old in some way.

**Comment by YakumoChen** [comment]
visually uninteresting, sprite unironically too clean for something that is supposed to be 'antique'. No detail, too boxy, missing the engraving-looking details on the receiver

**Comment by Zonespace27** [comment]
I like dim's work but the goon artstyle clashes here

**Comment by Colovorat** [comment]
Literal downgrade

**Comment by cacogen** [comment]
another resprite for its own sake where the sprite isn't an improvement (notice the lack of shading compared to the original)

**Comment by Dorsisdwarf** [comment]
Sprite would be very nice if it ditched the weird addition of a square nose and re-added the nice details into the center bar. 

And maybe toned down the bluewash the sprite is randomly dipped in, what are we making deus ex human revolution?

**Comment by Comxy** [comment]
What about the in-hand sprites though, don't they need an update according to this new sprite?

**Comment by Imaginos16** [comment]
> What about the in-hand sprites though, don't they need an update according to this new sprite?

Not necessarily. So long as it updates something, its merge-able. The fire axe got away with it for three months so...

**Comment by Imaginos16** [comment]
As for the PR itself, I'll leave it open for a little longer since I am personally conflicted. On the one hand, its definitely leagues better than what we have, but on the other, it could've been done with more grace.

I was gonna be ready to immediately shred the PR for being a goon icon, but so long as the creator itself consented to it and open sourced it, the goon folder shouldn't return thankfully.

**Comment by RuneQuester** [comment]
Ehh, I dont think its a very big improvement. The giant fucking battering ram at the front looks extremely awkward, though it has nicer sprite detail in general.

**Comment by Ryll-Ryll** [comment]
ngl the old version looks more like an upgrade of the proposed sprite than the other way around

**Comment by Imaginos16** [comment]
Since Twaticus gave no reply, and also considering the PR is also stale, and taking on top of the fact that I was mostly negative with the laser gun, I'm closing this, sorry.

**Pull request closed without merging**
