### PR TITLE
Byond509

### PR DESCRIPTION
**Pull request by neersighted**
Simply a fixed version of `tgstation/Byond509`.

All code by @RemieRichards and @MrPerson; I just fixed the conflicts.

Includes a tweak by me to fix speech bubble rotation:
image

### CODE REVIEW

**Comment by WJohn** [comment]
Please put Fixes #14664 in the OP.

**Comment by neersighted** [comment]
Its in the commit @WJohn, it will close the issue.

**Comment by WJohn** [comment]
Ah, I didn't know it would fix it from there. Good to know.

**Comment by Iamgoofball** [comment]
hnngh

:+1: x :100:

**Pull request merged**
