### PR TITLE
Rods now change sprite depending on how much in the stack

### PR DESCRIPTION
**Pull request by ghost**
ss 2015-02-02 at 12 20 12

yeah

### CODE REVIEW

**Comment by Deantwo** [comment]
Sure makes the Cook's use of them better.

**Comment by Jalleo** [comment]
:+1:

**Comment by phil235** [comment]
That would make picking up a single rod harder though.

**Comment by Jordie0608** [comment]
Could probably be done with overlays and pixel shifting but :+1: anyway.

**Comment by paprka** [comment]
that's a good idea jordie too bad i'm a shitcoder

**Comment by pudl** [comment]
dynamic as shit

**Comment by AnonymousNow** [comment]
Thanks, Pap.

**Comment by Tenebrosity** [comment]
I love shit like this, I don't know why. :+1:

**Comment by paprka** [comment]
conflix fixd

**Pull request merged**
