### PR TITLE
Comms agent buff

### PR DESCRIPTION
**Pull request by ghost**
Comms agents get a togglable robotic voicebox, private binary access, high volume mode, and the ability to speak over every channel via their headset.

### CODE REVIEW

**Comment by ATH1909** [comment]
Would it be possible to give them the ability to speak over all channels as well (instead of just hear(ing) them)?

**Comment by Arathianen** [comment]
Yes.

And also what athath said.

**Comment by Tharcoonvagh** [comment]
They can use the intercom to change to any channel except the syndi and CentCom. They need to activate the tcomm thing in the backroom first though.

Also yes.

**Comment by Shapsy** [comment]
That seems like a pretty massive buff to comms agent at the expense of everyone else, I think they're better off with limitations on impersonating heads of staff, silicons, and departmental radios.

**Comment by Tharcoonvagh** [comment]
S P E E D M E R G E

**Comment by Fhaxaris** [comment]
uh oh, antag freeze

**Comment by ExcessiveUseOfCobblestone** [comment]
Side-Antagonists / Hostile Ghost Roles fall under the umbrella of the Antag Freeze.

**Comment by Tharcoonvagh** [comment]
ruh roh shaggy

**Pull request closed without merging**
