### PR TITLE
Fixes disposal holders not moving

### LINKED ISSUE #14866: Disposals are broken
If you disposal yourself you just get stuck in the pipe.

### PR DESCRIPTION
**Pull request by tkdrg**
Fixes #14866
Closes #14878

### CODE REVIEW

**Comment by PKPenguin321** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Iamgoofball** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by neersighted** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by duncathan** [comment]
AAAAAAAAAAAÀAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Shadowlight213** [comment]
B

**Comment by PKPenguin321** [comment]
b is for blasphemy

**Comment by Shadowlight213** [comment]
C is for codercuck

**Pull request merged**
