### PR TITLE
Adjusts the No ERP poster description to be more subtle and reference the lore.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adjusts the No ERP poster description to be more subtle and reference the lore.

## Why It's Good For The Game

I think this is funnier than the previous description.

## Changelog

:cl:
spellcheck: Adjusts the No ERP poster description to be more subtle and reference the lore.
/:cl:

### CODE REVIEW

**Comment by Blacklist897** [comment]
Its not funny enough, its a shame player references are banned because we could have a memorial to our fallen terry comrades

**Comment by optimumtact** [comment]
this seems like straw clutching tbh goof.

**Comment by deathrobotpunch** [comment]
why tf would enterprise resource planning be banned?

**Comment by Iamgoofball** [comment]
stale b gone

**Comment by SmArtKar** [comment]
> this seems like straw clutching tbh goof.

its funnier than what we have rn tbh

**Pull request merged**
