### PR TITLE
[MDB IGNORE] 3/4th medkit sprites + firstaid > medkit

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

This PR updates our MEDKIT sprites to be more in line with the new art style that we have been heading in:
image

Secondly, it repaths and renames all instances of firstaid to medkit. This has been a massive gripe of mine for a while, now it's nice:
image

No one calls these things firstaid kits, everyone refers to them as medkits.

The "medical" medkit has now been renamed to the surgery medkit since that's what it specialises in.

Credits to [LiLJard](https://github.com/LiLJard) (original PR: https://github.com/TauCetiStation/TauCetiClassic/pull/8569) for the original sprites.

Credits to PositiveEntropy for the edited ones!

## Why It's Good For The Game

More sprite consistency and naming consistency is good for the game.

## Changelog

:cl:
imageadd: Medkit sprites have now been updated to proper 3/4th perpsective.
spellcheck: All instances of "firstaid" have been replaced with "medkit".
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
but medkits are already 3/4th

**Comment by SmArtKar** [comment]
^^^
Also these feel too bright and toxic, maybe you should make the color a bit dimmer and also make only a part of them colored

**Comment by Gandalf2k15** [comment]
> but medkits are already 3/4th

Sort of, it's hard to pinpoint what about them doesn't match our style, but let me give you an example:
image

**Comment by Gandalf2k15** [comment]
> ^^^ Also these feel too bright and toxic, maybe you should make the color a bit dimmer and also make only a part of them colored

Hmm, perhaps, I could dim them slightly.

**Review by JohnFulpWillard — APPROVED** [review]
doesnt change bot stuff directly so none of my business

**Comment by Gandalf2k15** [comment]
> ^^^ Also these feel too bright and toxic, maybe you should make the color a bit dimmer and also make only a part of them colored

image

How is this?

**Comment by SmArtKar** [comment]
> > ^^^ Also these feel too bright and toxic, maybe you should make the color a bit dimmer and also make only a part of them colored
> 
> image
> 
> How is this?

now it looks even worse tbh

**Comment by Wallemations** [comment]
The original sprites looked fine to me, the problem is the color scheme looks a bit too harsh.
You could look into less harsh color palettes, either on a palette website or by looking at other sprites' palettes.
A good place to look could be the toolboxes, using those kinda colors could work well.

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
While I am not against a resprite of medkits, those do not fit our approaching style as it currently stands. It may fit better on downstream since you lot have been using many sprites from Tau Ceti and Eris, but I would request a different style. If you can talk to me (PositiveEntropy/Imaginos) on discord, we could discuss further on what alterations we could make to keep us both pleased.

**Comment by Gandalf2k15** [comment]
Updated to specification.

**Comment by theOOZ** [comment]
I like them.

**Comment by SgtHunk** [comment]
[MDB IGNORE] is spelled wrong so MDB keeps running after each commit (and failing)

**Comment by Mothblocks** [comment]
I quite liked emergency medkits being an immediately obviously different shape from normal ones

**Comment by GoldenAlpharex** [comment]
My main gripe with them is the fact that the handle seems to be directly on the line that shows where the kit would open up, which feels wrong. Other than that, I could get used to these, even if I think I prefer the old ones.

**Comment by GoldenAlpharex** [comment]
> I quite liked emergency medkits being an immediately obviously different shape from normal ones

To be fair, they're visibly smaller, so I'd say it's still rather obvious, maybe there could be some sort of color difference to help, perhaps.

**Comment by iwishforducks** [comment]
I love the look of these. They could definitely use better painting, though- if that makes sense. The colors look fine themselves, just need to be painted differently. I don't know how they should look, though.

**Review by Twaticus — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
fucking conflicts

**Pull request merged**
