### PR TITLE
Fixes to power

### PR DESCRIPTION
**Pull request by CakeQ**
:cl: Cakey
mapping: Removed substations
/:cl:

### CODE REVIEW

**Comment by CakeQ** [comment]
Fuck's sake

**Comment by Cyberboss** [comment]
FUCKING WHAT??

**Comment by Cyberboss** [comment]
@optimumtact DON'T DRAG ME INTO THIS SHIT

**Comment by kevinz000** [comment]
cyberboss fix ur shit.

**Pull request closed without merging**
