### PR TITLE
Add Rapid Pipe Dispenser (RPD) to enginering protolathes.

### LINKED ISSUE #49443: You can only print RPDs in a hacked autolathe
Doesn't seem intended, I might as well add it to the engilathe later

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

Move RPD to engi protolathe

## Why It's Good For The Game

close #49443
RCD already in engilathe.

## Changelog
:cl:
add: Rapid Pipe Dispenser (RPD) now available only in enginering protolathes.
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
speedmerge now

**Review by spookydonut — DISMISSED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
should be a move instead of an add tbh 😏

**Comment by Dennok** [comment]
Why not remain it in autolathe too?

**Comment by ExcessiveUseOfCobblestone** [comment]
don't think the RCD is in the auto anymore and you can easily btfo the entire distro (in a more advanced way than just removing a pipe).

If you want to play with atmos mechanics you should be going to engineering for the ez tools instead of cargo's 3d printer.

**Pull request merged**
