### PR TITLE
Nanites that don't sync regularly have a chance of software errors

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

See title.
Every time the nanites fail a cloud sync (which is every 30 seconds), it has an 8% chance of causing an error to one of its programs, which will usually disrupt its functionality.

## Why It's Good For The Game

Discourages getting your nanites then destroying the cloud console to be safe from sabotage. While it was already a half-risk since shocks and EMPs could cause errors, it was easy enough to avoid these two sources and enjoy the benefits of having nanites fairly safely.
Now going off-cloud has very tangible risks, and the more it lasts the more damaging it becomes, especially if glitch programs start to accumulate.

## Changelog
:cl: XDTM
balance: Nanites who aren't regularly syncing to a cloud console have a chance of encountering software errors over time.
/:cl:

### CODE REVIEW

**Comment by MrPerson** [comment]
You identified the problem and solved it in a simple, elegant way that's very easy for players to understand. A+++ my dude

**Comment by davethwave** [comment]
I would say by adding a glitch thing for programs would make having anything complex and trigger related like speech and dermal button related be a nigh impossible depending on how often these occur, on a side make it happen for everyone I would say since the programs get repaired to their normal state later on and can lead to fun interesting stuff like a survivor in a nanite meltdown scenario if one was lucky.

**Comment by CRITAWAKETS** [comment]
Ah yes, so nanites are now so easy to sabotage that even if you prevent sabotage they will still be able to kill people.

Have you forgotten that Infective Exo-Locomotion and the newly added Nanite Sting exist? With those programs there is no way to "avoid" getting nanites. Also, nanites are basically impossible to get rid of when inside a person so theres no "removing the nanites from people" bullcrap. Nanites are already OP enough for both antag shittery and its own peaceful uses as it is.

Also, if you want people to not edit your cloud as an antag, just add the changes then remove the console.

**Comment by davethwave** [comment]
Don't exaggerate, nanites are fairly easy to get rid of now, either build a grill in the halls or ask someone from sci to remove them via a console since that's possible now I've heard.

**Comment by CRITAWAKETS** [comment]
How the hell does a grill in the halls contribute to removing nanites? Also, removing manually nanites from an entire station population is an outright ridiculous idea. Nanites can be so deadly that they just kill before you can even get them in the pod.

**Comment by davethwave** [comment]
Electric shock removes them, and the locomotive stuff is expensive to have running in the first place so you would have plenty of time to get rid of them one way or another. If worse gets to worse have a doc grind up some iron and uranium and have everyone huddle and boom there goes the majority of the problem.

**Comment by XDTM** [comment]
> Ah yes, so nanites are now so easy to sabotage that even if you prevent sabotage they will still be able to kill people.

The central theme for nanites is great power, at great risk (of sabotage, in this case). The way you prevent sabotage is by guarding the console, much like you would guard an AI upload for similar reasons.

> Have you forgotten that Infective Exo-Locomotion and the newly added Nanite Sting exist? With those programs there is no way to "avoid" getting nanites.

Exo is fairly hard to get, has a limited range, and is expensive to run; plus it is stopped by anything that would stop a virus infection (hardsuits and biosuits in particular). Treat it like an outbreak, if it happens.

> Also, nanites are basically impossible to get rid of when inside a person so theres no "removing the nanites from people" bullcrap.

Shocks and EMPs remove some nanites, repeat them enough and they'll be eradicated no matter what. I've heard that the EMP rifle is commonly used for this purpose, but grilles can be a ghetto solution as well.

> Also, if you want people to not edit your cloud as an antag, just add the changes then remove the console.

It's the main reason this PR exists, to give this tactic a significant downside.

**Comment by davethwave** [comment]
The thing with nanites is that despite how easy it is the remove them people just don't face that kind of threat often enough to properly react in time to do most of whats needed. Throwing yourself into a grill is not the most easiest of first choices you would think of to solve a problem after all.

**Comment by XDTM** [comment]
As for the deadliness, i'm considering a rework of the heart attack program, since even for nanites it's way too powerful if paired with infection.

**Comment by davethwave** [comment]
For that I have to agree on, it's way to cheap to run after all, and meltdown relies on your current volume of nanites so there WILL be survivors unlike the heart attack one. I would say to turn the heart attack thing into a glitch program depending on the defib. One the side I would ask to have the defib to be slightly more tolerant on it really working, Haven't ever actually had seen it go off successful for anyone when I do a on death sensor for it Though probably for a future PR.

**Comment by XDTM** [comment]
Hold up, looks like heartstop nanites aren't even researchable anyway

Has anyone actually obtained them ingame somehow?

**Comment by davethwave** [comment]
I don't think I've seen it actually be used so I presume we can't use it. Heard it was supposed to be researchable via syndi tech but haven't seen it either way.

**Comment by AdamElTablawy** [comment]
They aren't obtainable, no. 

Frankly, though, the idea of a nanite-eating chemical or something might be okay. There's already a virus that eats nanites, and when nanites go rogue there's not always enough time to start mixing EMPs (let alone the damage that causes to the station when you mix several) before people start exploding or being poisoned to death and so forth.

Also, side note, but hallucination nanites are OP as shit and better than all the other pacification nanites

**Review by actioninja — CHANGES_REQUESTED** [review]
why the tgui rebuild? you didn't change any uis

**Comment by XDTM** [comment]
During testing the program rules from my recent pr were missing until I rebuilt tgui. I threw it in in case it was somehow missing on upstream as well.

**Comment by actioninja** [comment]
conflict, you're going to need to rebuild it again anyways.

**Pull request merged**
