### PR TITLE
Improves dice code

### PR DESCRIPTION
**Pull request by Spess-Rando**
Did you know that a d20 that landed on a 5 was referred to as "d205"? Yeah, let's not do that.

Also, d2 dice are a real thing.  So I decided to replace the coin with an actual d2 die.

d2

Furthermore, most people without prior contact with tabletop games usually doesn't really know what a "d8" and others are supposed to refer to, so their object names should be a bit more informative now.

### CODE REVIEW

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
gbp farm lol

**Comment by RandomMarine** [comment]
>Furthermore, most people without prior contact with tabletop games usually doesn't really know what a "d20" and others are supposed to refer to, so their object names should be a bit clearer now.

This code branch may as well drop the /tg/ name at this point.

**Comment by ExcessiveUseOfCobblestone** [comment]
> at this point

**Comment by uraniummeltdown** [comment]
\>renaming the dice
Seriously don't do this

**Comment by nicbn** [comment]
Die is the thing people do
This thing is called a dice

**Comment by Slignerd** [comment]
Die is singular for dice.

**Comment by epochayur** [comment]
who the fuck doesn't know what a d20 is

**Comment by Iamgoofball** [comment]
>he doesn't know what a d20 is

**Comment by Slignerd** [comment]
Maybe I should have used a d8 as an example instead? It wouldn't make much of a difference, and yet I feel like the reactions wouldn't be the same.

**Comment by nicbn** [comment]
Dice is the singular for dice

**Comment by Slignerd** [comment]
firefox_2018-02-28_21-04-06

firefox_2018-02-28_21-04-50

Please learn grammar before trying to correct people on grammar.

**Comment by DaxDupont** [comment]
this is a dumb pr

**Comment by Iamgoofball** [comment]
everyone knows d + number = die w/ number sides

**Comment by KorPhaeron** [comment]
I want to apologize to everyone for not noticing and closing this PR earlier

/tg/ forever

**Comment by nicbn** [comment]
I'm not french

**Comment by Slignerd** [comment]
Okay, fine

**Comment by Slignerd** [comment]
Okay, fine.

I changed it back, and pushed it to my remote. It didn't update cause the PR is closed. It should change it back to current names once reopened.

**Pull request closed without merging**
