### PR TITLE
Removes MiniStation

### LINKED ISSUE #16326: Ministation: Does not contain some objective items.
The HoS Laser Gun does not appear on Ministation.

### LINKED ISSUE #16612: Cargo consoles do not work on ministation map
Playing on ministation map with most current update. Opening cargo consoles reveals nothing except a yellow bar at the top which says "loading". Stared at this for ten minutes before declaring cargo to be dead. Please fix, as lack of starting resources on ministation can only be supplemented by cargo, making it essential.

### PR DESCRIPTION
**Pull request by Okand37**
In favour of #22447 
Removes ministation : https://dl.dropboxusercontent.com/s/tm1jg6qnxo4fzai/Ministation%202015-01-25.png?dl=0
in favour of omegastation : https://drive.google.com/file/d/0B67Y0cE3wQneMWx0M2REOGxxbTQ/view
Closes #16612
Closes #16326

Please no mean words.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
*favor

**Comment by Haevacht** [comment]
It's favour you undignified wine.

**Comment by Armhulen** [comment]
it's favor in the places that matter

**Comment by optimumtact** [comment]
The only place that matters is mine

**Comment by xxalpha** [comment]
Why are you deleting ministation?

**Comment by Hatfish** [comment]
for what reason

**Comment by ChangelingRain** [comment]
#22307

**Comment by Okand37** [comment]
@xxalpha Its stated in the post. Its in favour of pr #22447 
@Hatfish As joan posted, someone already tried to remove birdboat; evidently, theer's a large number of indifference in whether it should be removed or not.

**Comment by TechnoAlchemisto** [comment]
But mini is cool

**Comment by optimumtact** [comment]
mini does not get updates

**Comment by ExcessiveUseOfCobblestone** [comment]
does mini even use lavaland?

**Comment by Jordie0608** [comment]
Yes

**Comment by Mervill** [comment]
If this gets merged, please close:

#16612

**Comment by hecksadecimal** [comment]
Mini was removed without Omega being ready. Any progress on that?

**Comment by Techbane** [comment]
Is this the appropriate place to grouse about Omega's wiring gaffes that leave half the station without power until you break into command areas to fix them, and atmospherics that apparently don't properly connect to most of the vents?

**Comment by Jordie0608** [comment]
No https://tgstation13.org/phpBB/viewtopic.php?f=11&t=8916

**Comment by AterSoul** [comment]
Where can I download this?

**Comment by ohnopigeons** [comment]
You can checkout the commit before this PR was merged

**Comment by AterSoul** [comment]
Can you just give me a link to the download? Im new to GitHub and do not even know what merging means... sorry for my ignorance.

**Comment by AterSoul** [comment]
Also I sometimes play ss13 in singleplayer. Can I just drop ministation into the /maps and play normally after compressing the file in dreammaker? Or is Smallstation not updated for the latest version of byond?

**Comment by optimumtact** [comment]
It might work, it might not, it's been a long time since it was used

**Comment by AterSoul** [comment]
Can anyone help me with the download????

**Comment by Jordie0608** [comment]
Grab the files from here
https://github.com/tgstation/tgstation/tree/c9f66573c58d9f263e55365327e67f169ed6b61e/_maps/map_files/MiniStation
They almost certain to not work with the current code.

**Comment by AterSoul** [comment]
@Jordie0608 Thank you kind sir.

**Pull request merged**
