### PR TITLE
space/basic in RandomZLevels and map_files

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

Mass replace space to space/basic in RandomZLevels and map_files

## Why It's Good For The Game

Maybe some optimize the map loader

### CODE REVIEW

**Comment by Dennok** [comment]
As i see.
Impact on the performance is imperceptible.

**Comment by Qustinnus** [comment]
Yes, I was thinking about transparency element, I will look into it more and make a PR. Component would eat too much memory

**Comment by Dennok** [comment]
Wrong PR comment? 

About transparency. 
As i know we have issue about mesons and open space. Since openspace add vis_content to self, it shown by mesons. 
I see only one way to fix this. Add atom that serves as level down visuals holder. 
But how mush this influence on performance?

**Comment by Qustinnus** [comment]
oh yeah my bad wrong PR. I was on my phone so I just tried looking for your "space" pr but ended on the wrong one.

I think adding an atom that serves as a level down visuals holder will add quite a big load to performance as we have a ton of open space theoretically. to the sum of multiple tens of thousands if we make space transparent

**Comment by Dennok** [comment]
Yes, 65025 turfs on one 255/255 map. and increment to amount of connected levels. 
Part of it is station floors/walls of, but it take like 1/3-1/2 of map (in best). all other is space.
For openspace it can be implemented to fix meson issue. since i made it change to space wariant if it has space under it.
Need testing.

**Comment by Qustinnus** [comment]
I will make a PR now for transparency element, maybe you can help review it and we can discuss it more on there?

**Comment by Dennok** [comment]
Better discus it in #53635
Element is good. Since i want has ability add transparent visuals to any turf for #52463

**Comment by Qustinnus** [comment]
yes, i want to add it to datum mats. will pr in 30 min or so

**Comment by Dennok** [comment]
code\datums\components\mirage_border.dm

what you think about it?

**Pull request closed without merging**
