### PR TITLE
Ladder radial menu.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

ladder radial menu

arrows

<details>
  <summary>old</summary>

ladder radial menu
</details>

## Why It's Good For The Game

radial menu cool

## Changelog
:cl:
add: Now ladders has radial menu
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
just make it an arrow up or an arrow down, the person is just visual clutter

**Comment by Dennok** [comment]
monkey ladder

**Comment by cacogen** [comment]
looked better with the abductor

**Comment by PKPenguin321** [comment]
monky

**Comment by HomocidlePancakes** [comment]
Color the arrows.

**Comment by Dennok** [comment]
> Color the arrows.

What color you want?
I find red and blue in icons

**Pull request merged**
