### PR TITLE
Makes chocolate less of an instant taser and more of a poison. 

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
balance: Coco now does not force puking on application and causes less disgust but is more aggressive with it's organ damage.
/:cl:

image
image

Player suggested, coder approved.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Ah fuck, forgot to stage a file, one sec.

**Comment by ATH1909** [comment]
Can you keep the message?

**Comment by GuyonBroadway** [comment]
Yes I can.

**Comment by GuyonBroadway** [comment]
There, that should about do it.

**Comment by Shadowflame909** [comment]
Your mortal weakness

**Review by 81Denton — DISMISSED** [review]

**Comment by Moonman121** [comment]
The first steps towards the felinid purge

**Comment by Cyprex** [comment]
Averages to 5 organ damage/tick with these changes, up from 2.25

**Comment by CRITAWAKETS** [comment]
i would say "holy shit thats OP", but actually impredezene does about the same level of damage but to the brain and for every species and requires less effort to obtain.

**Comment by Shadowflame909** [comment]
Even weaker considering it chooses a random organ, so your taking less specific organ damage compared to the brain damage crit

**Comment by GuyonBroadway** [comment]
It's more funny if they die slowly... 

Plus as much as I want to stick it to felinids... stun and done combat needs to die first.

I'd play a catgirl for a solid six months if it meant stun and done dies.

**Comment by mrhugo13** [comment]
mmmmmm yes.

forbidden brown.

**Pull request merged**
