### PR TITLE
Do not resuscitate is permanent

### LINKED ISSUE #44624: Your body will still be revived when you use Do Not Resuscitate

### PR DESCRIPTION
**Pull request by 4dplanner**
## About The Pull Request
fixes #44624

## Why It's Good For The Game
let's you trust the "soul has departed" message.
Alternate change would be to add different flavour text, but I think this is more consistent. If you choose to be out of the game (with that character), you choose to be out of the game.

## Changelog
:cl:
remove: you can no longer turn Do Not Resuscitate off.
/:cl:

### CODE REVIEW

**Comment by habader** [comment]
no please i need to abuse this bug more fuck

**Comment by FantasticFwoosh** [comment]
This reminds me of the guy who died after tatoo'ing 'D.N.R' over his neck for edgy art then subsequently got in a accident, for the same reasons i think a toggle opt in-and-out would be better in this case.

**Comment by kriskog** [comment]
If you ghost, it is permanent. If you choose to not be cloned, it should be permanent too. If you want to play the round after dying, don't DNR.

**Comment by ishitbyabullet** [comment]
ghosting being permanent? alright.
suicide being permanent? what the fuck
DNR being permanent? come the fuck on.

**Comment by 4dplanner** [comment]
I am open to being convinced if actual arguments are given

**Comment by ishitbyabullet** [comment]
I just dislike stuff that permanently makes you dead.

Only argument I can think of is if someone doesn't want to be revived at the moment however later on they do. I don't think you're able to deny being cloned anymore so that's a possible use for DNR not being permanent.

**Comment by actioninja** [comment]
If you don't want to be permanently dead, try not clicking the "this will make you permanently dead" button.

**Comment by ishitbyabullet** [comment]
Once/if the PR is merged, that makes sense.

Until then, this is what the verb says:
> You can now no longer be brought back into your body. You can undo this at any time by using the Do Not Resuscitate verb again.

I don't feel like it should be permanent if it isn't already.

**Comment by ExcessiveUseOfCobblestone** [comment]
An important distinction between suicide/ghosting vs DNR is that DNR is only when you're already dead. Suicide/Ghosting is "I do not want to play this character anymore" and should be final, DNR was PR'd explicitly as a "Please stop trying to revive me atm", mostly as a way to stop being forced back into the body as a zombie (although you may later want to be revived as one if say the maint tunnel you're trapped in is opened). I personally don't have an issue if someone wants to delay their revival so long as they realize that opens them up to being treated like they don't plan on coming back at all and admins enforce it as such.

In a perfect world, all bodies should go to morgue if DNR'd or No Soul so that way if the user wants to come back they can hop in the tray which beep beeps. That said, your body is still susceptible to being gibbed/cremated/funeral'd/etc. before hand and maybe even while you're beeping (I never ran into that issue).

**Comment by kriskog** [comment]
Currently, DNR corpses look exactly like catatonic corpses. In other words, always DNR if a traitor kills you so you look permadead and can come back to fuck him up later since he left your corpse whereever. Real gamers game the system at every turn, and this opens up for that kind of behaviour. 

I would be okay with a visual distinction between dnr corpses and catatonics, but I would still prefer DNR be permanent. If you wanna play the round, just don't DNR in the first place.

**Comment by 81Denton** [comment]
Radical opinion: If you don't want to be permanently dead, consider not clicking the "I want to be permanently dead" button.

**Pull request merged**
