### PR TITLE
Fixes #8529, confirmation check for BoH bombing

### LINKED ISSUE #8529: Putting a bag of holding in a bag of holding does not give you a confirmation prompt.
I swear to god we had one of these before.

### PR DESCRIPTION
**Pull request by Jordie0608**
Fixes #8529 by adding a simple yes/no check before BoH bombing.

### CODE REVIEW

**Comment by GunHog** [comment]
You...sure that is a good idea? Are you <b>SUUUUUUUUUUUUURE</b> you want to do that?

**Comment by optimumtact** [comment]
:-1: Let people be stupid if they want to

**Comment by Kelenius** [comment]
I remember aran complaining that it will let people put a bag into a bag, drop it, walk away, and confirm in safety a while ago.

**Comment by palpatine213** [comment]
Why make satchels cause a singulo? Isn't the idea of the boh sing to prevent infinite storage space? If the satchel can only hold ores it should be able to go in a boh.

**Comment by Lumipharon** [comment]
This thing called consistancy.

Also why handhold?

**Comment by Jordie0608** [comment]
If they're meant to work the same way they should fail catastrophically the same way.

**Comment by palpatine213** [comment]
So, if a satchel of holding is in a backpack, and that backpack is put into a boh, it's going to go sing right. It will give a confirm dialog if it's inside a backpack, or just if put directly?

**Comment by Kromgar** [comment]
PLEASE. Let this be added.

Also will you still be able to TK BoH bomb?

**Comment by RandomMarine** [comment]
https://github.com/tgstation/-tg-station/blob/master/code/game/objects/items/weapons/storage/bags.dm#L87
>It's been outfitted with anti-malfunction safety measures.

SoH not creating singulos is not an oversight. Worse, we suddenly change and we're going to have accidental singulos all over the place from miners that aren't aware of the change.

**Comment by Kromgar** [comment]
Also satchel into BoH should just send you to the astral plane

**Comment by Jordie0608** [comment]
Alright w/e soh causing singulos is gone.

@Xhuis could you weigh in on this

**Comment by Xhuis** [comment]
SoH being singulo-proof was intentional. Fluffwise they can only contain ores and reject other items - that's hinted in the description. At the most have it spawn an academy singulo that vanishes after a few seconds.

That's my two cents, but do what you want - it's your call.

**Comment by Kromgar** [comment]
Have it send the person to astral space *A little dimension on centcomm z-level that is "Bluespace" then send them back

**Comment by Miauw62** [comment]
Muh hugbox
Op 8-apr.-2015 20:01 schreef "phil235" <notifications@github.com>:

**Pull request merged**
