### PR TITLE
New sounds for gravity generator

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request
The gravity generator sounds like a machine now. It has a total of 3 mid loop clips as well as a start up and ending sound. These mid sounds do fade in and out between each other, but I spent half an hour listening to the thing in game and it blends very well with the station hum and other ambient noise.
The samples used are in the public domain, taken from a digitized collection of vintage samples.
The following is a recording of the game when standing 5 tiles to the left of the machine.
https://vocaroo.com/1koSoIdne81m
The best way to find out if its too quiet or loud is to hear it in game on your machine, since vocaroo dampens audio for some reason.

## Why It's Good For The Game

I've found that most of the sounds which cause players discomfort are some variant of noise over harmonic tone. So lets get rid of them.

## Changelog

:cl:
sound: New gravity generator sounds.
/:cl:

### CODE REVIEW

**Comment by AtomTheProphet** [comment]
These sounds do not fit at all.

**Comment by san7890** [comment]
the hissing and "breathing" of the machine doesn't really make sense here sadly

**Comment by Capsandi** [comment]
alright apparently its just the volume of the thing

**Comment by LemonInTheDark** [comment]
I like this personally

**Pull request closed without merging**
