### PR TITLE
Mutes now inform the mutee who muted them

### PR DESCRIPTION
**Pull request by neersighted**
That was easy
@Iamgoofball

### CODE REVIEW

**Comment by Firecage** [comment]
You should show Goof how to make a PR.

**Comment by CPTANT** [comment]
:-1: 

If there is anything that is supposed to be a stealthtool its mutesting.

Why is there a notification anyway, you are supposed to notice it when you talk.

**Comment by CPTANT** [comment]
I read mutesting instead of mutestring, so this came over weird.

**Comment by PKPenguin321** [comment]
RIP Goof

**Pull request merged**
