### PR TITLE
Gracious Retired Contributor Armhulen has Granted Fikou More Points (migrating gbp)

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

that account is now a ghost, should be okay to move it's points over right?
closes #58424

## Why It's Good For The Game

He gave me them :)

### CODE REVIEW

**Comment by Kylerace** [comment]
its for the best, its what he would have wanted

**Comment by Qustinnus** [comment]
i hope you enjoy your points on that branch ;)

**Comment by Qustinnus** [comment]
image

the branch that we surely use to keep gbp-balances ;^)

**Comment by tralezab** [comment]
reopen this NOW https://github.com/tgstation/gbp-action/issues/24

**Comment by Fikou** [comment]
closing in favor of #58426 he gives me more points there

**Pull request closed without merging**
