### PR TITLE
Removes deconverting cultists because that shit be boring and a newbie trap

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
experimental: Holy Water deconversion is no longer a thing. It was a newbie trap and it's faster to kill and clone.
fix: Fixes Holy Water code being a fucking mess and rolling its own metabolization for no reason.
/:cl:

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=14955

### CODE REVIEW

**Comment by Spaceinaba** [comment]
why dont you just fix the code instead of gutting the functionality

**Comment by Anonymous583** [comment]
No.

**Comment by Anonmare** [comment]
You don't fix a broken arm by cutting it off Goof

**Comment by scrubs2009** [comment]
Deconversion gives a motivation to do something besides kill anyone within 30ft of a tome.

**Comment by epochayur** [comment]
haha oh wow

**Comment by Iamgoofball** [comment]
@Spaceinaba I did fix the code, check dem optimizations.

@Anonymous583 Yes.

@Anonmare You know that removing limbs for medical reasons is a very common occurance, right?

@scrubs2009 Our players prefer killing and every time a decon attempt happens, the scenario that Kor brought up occurs.

**Comment by Iamgoofball** [comment]
@Cyberboss experimental tag doesnt seem to work

**Comment by Xhuis** [comment]
This is a bad PR. If we didn't want to give people different options, we'd remove the uplink and just spawn all traitors with a revolver and two speedloaders. Last I checked, cloning isn't a magical deconversion device. Come on now.

**Comment by Iamgoofball** [comment]
@Xhuis Killing someone and cloning them removes their antag.

Cult isnt about options, its about the metagame. All conversion modes are.

**Comment by Xhuis** [comment]
Starting in the [cloning pod file at line 135](https://github.com/tgstation/tgstation/blob/master/code/game/machinery/cloning.dm#L135), there is no mention of any kind of antagonist in the code for it; Ctrl+Fing the words "antag", "antagonist", and "cult" return zero results.

**Comment by Iamgoofball** [comment]
@lzimann This does include a code fix. Please re-add the tag so I get my points.

**Comment by Spaceinaba** [comment]
can we have a "bait" tag

**Comment by Iamgoofball** [comment]
ty

**Comment by DaedalusGame** [comment]
you don't get points if your pr doesn't get merged goof

**Comment by Iamgoofball** [comment]
@Xhuis Last time I checked, making a new mob/mind would eliminate the cult status.

**Comment by Iamgoofball** [comment]
@DaedalusGame did you read who the thread wanting deconvert removed was made by

**Comment by DaedalusGame** [comment]
probably a very stupid person

**Comment by Spaceinaba** [comment]
cant wait to get forcibly converted to cult and when I get caught I get murdered and removed from the round instead of getting to keep playing the game

**Comment by Xhuis** [comment]
Removing antagonist datums on transferring minds and bodies would eliminate the purpose of antagonist datums. I'll test this on a local server and report back.

**Comment by ExcessiveUseOfCobblestone** [comment]
There's some that are on body and some that are on mind

**Comment by Iamgoofball** [comment]
@Spaceinaba Disable cult in your prefs and it gives your mob to someone else when you get converted. Also, sometimes you lose the game. It happens.

@Xhuis Yeah, that's antag code for you. It's a mess. And the point of antag datums is to clean up antag code, not ensure you keep your antag between lives.

**Comment by Spaceinaba** [comment]
I'll give you one XD for that one goof

**Comment by Xhuis** [comment]
Cloning does not remove cult status.

**Comment by DaedalusGame** [comment]
cue post about how it should

**Comment by ExcessiveUseOfCobblestone** [comment]
now who on earth changed that!

**Comment by Robustin** [comment]
>KILL AND CLONING TO DECONVERT IS THE META ANYWAY

>its not the meta
>cloning doesnt deconvert
>holy water deconversion is getting buffed

gr8 b8

**Comment by ExcessiveUseOfCobblestone** [comment]
did you scroll down to the part where the deconversion part gets removed?

**Comment by Iamgoofball** [comment]
hm

i hate deconversion anyways so this works

**Comment by Iamgoofball** [comment]
deconvert encourages slow stealth rounds and we aint about that life

**Comment by DaedalusGame** [comment]
I have no idea what I'm doing but let's just make a pr anyway and if someone calls me out I'll just say I was planning this from the very beginning with some dumb reasoning

**Comment by Spaceinaba** [comment]
goof knows exactly what he's doing and it's all in the name of getting (you)'s just as it's always been

**Comment by Xhuis** [comment]
this means that this PR effectively removes deconverting cultists, so if you're set on that, then edit the title to reflect that there are no longer any conventional ways to deconvert them.

**Comment by Iamgoofball** [comment]
will do

**Comment by Iamgoofball** [comment]
it's done jim

**Comment by Iamgoofball** [comment]
@Spaceinaba if pretending that removing bad gameplay is a trolling effort, whatever helps you sleep at night I guess

**Comment by Spaceinaba** [comment]
Who's to say what's a trolling effort and what's not when you constantly make PR's where you delete cfg options and gut features

**Comment by Iamgoofball** [comment]
sometimes features are so shit they just need to go

**Comment by Spaceinaba** [comment]
heh

**Comment by DaedalusGame** [comment]
goofball would know what a bad feature looks like, as he keeps pr'ing them

**Comment by ExcessiveUseOfCobblestone** [comment]
@DaedalusGame you previously deconverted on being cloned so it's changed from "the very beginning" in goof's defense

**Comment by Buggy123** [comment]
(Looks at title in PR list)
Hmm, that sounds like a goof PR.
(Looks at name)
Yep, it's a goof PR.

**Comment by Incomptinence** [comment]
you might be thinking of killing and borging goof

**Comment by Anonmare** [comment]
@Incomptinence  Alot of people think about killing and borging goof

**Comment by KorPhaeron** [comment]
Redeem them with sword and fire

**Comment by Buggy123** [comment]
!(https://imgur.com/1zOvOKj.jpg)[]

**Comment by kevinz000** [comment]
:-1: ⛳️  🏌️ ⛳️

**Comment by Repukan** [comment]
Kill them all and let the Lord above sort them out.

**Comment by PKPenguin321** [comment]
i mean i kill them anyways but i dont see why this is needed

**Comment by BeeSting12** [comment]
based goof

**Comment by Iamgoofball** [comment]
@cyberboss m8 kor seemed to support this

**Comment by Xhuis** [comment]
`seemed`

**Comment by Iamgoofball** [comment]
I mean they made the thread asking for it and posted about fire and swords so

**Pull request closed without merging**
