### PR TITLE
fixes erroneous typecast

### PR DESCRIPTION
**Pull request by 4dplanner**
## Changelog
~~:cl:
code: removes unnecessary typecast
/:cl:~~

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
You sure a changelog is really needed for this?

**Comment by MrDoomBringer** [comment]
Also im p sure these kinda errors are fuckin everywhere. Honestly, i'm not even sure what effect a change like this has, I haven't had a chance to test it for myslef.

**Comment by 4dplanner** [comment]
It does absolutely nothing, no gameplay effects at all. PURE

**Review by SpaceManiac — APPROVED** [review]

**Comment by PKPenguin321** [comment]
this is a balance change

**Comment by 4dplanner** [comment]
Secretly nerfs xenobio

**Comment by PKPenguin321** [comment]
buffs*
lets you revive any mob that can process chems, including xenos and monkeys
not that im opposed to the change but this isnt a fix

**Comment by SpaceManiac** [comment]
> lets you revive any mob that can process chems, including xenos and monkeys

pretty sure this already works and that changing this type annotation does literally nothing

**Comment by ExcessiveUseOfCobblestone** [comment]
> > lets you revive any mob that can process chems, including xenos and monkeys
> 
> pretty sure this already works and that changing this type annotation does literally nothing

yes

**Pull request merged**
