### PR TITLE
Ice Spiders now use frost oil instead of toxin

### PR DESCRIPTION
**Pull request by ghost**
:cl: Armhulen
add: Frost Spiders now use Frost OIL!
/:cl:

It's really weird that we have some spiders just being immune to space for no real reason really other than snowdin, a removed map. I'd love to bring snowdin back so instead lets do something interesting!

Pros of frost oil:
Deadlier for sure
Slows after awhile
Cons of frost oil:
Delayed damage
Can be completely negated by coffee

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Armhulen** [comment]
i have a fix pr up ok

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Set it on their parent, `/mob/living/simple_animal/hostile/poison/giant_spider/ice` instead.

**Comment by DoctoreMad** [comment]
So Maintainers can close this PR if they want but do they NEED to?

**Comment by Armhulen** [comment]
they can always do that

**Comment by Armhulen** [comment]
uh, as for the pathing thing i don't think that'd work.

**Comment by JJRcop** [comment]
@DoctoreMad really the bot doesn't mean anything it's just trying to annoy @Armhulen, maintainers aren't given any more power than they had before just because he has -1 balance, but it's notifying them of the negative balance.

**Comment by Armhulen** [comment]
When will they give up and just give me infinite credits so I can go back to spreading my genius in this game??

**Comment by Anonmare** [comment]
Aren't Changelings immune to frost oil?

**Comment by Armhulen** [comment]
i'm really not sure. probably not?

**Comment by ShizCalev** [comment]
@Anonmare No, they are not immune to frost oil.

**Comment by optimumtact** [comment]
@JJRcop please don't spread misinformation, we can absolutely close the PR's of someone who goes into the negative.

**Comment by Armhulen** [comment]
you can close the prs of anyone

**Comment by Bawhoppen** [comment]
Yea but they can ignore the 24hr rule legally then

**Comment by DoctoreMad** [comment]
Okay so the closing of your PR is sped up by 24 hours!
If anyone was searching for the TGstation experience, THIS IS IT.

**Comment by JJRcop** [comment]
@optimumtact Yes that is correct, but you can do that even if they aren't negative. My point was that if a contributor has negative points, maintainers don't get any more or less power than they already have, since they can close any PR anyway, and I'm trying to point out the scare tactics of the bot comment.

**Comment by DoctoreMad** [comment]
Just because they TECHNICALLY CAN do something in the github page, doesn't mean they CAN do it without breaking our self imposed rules.
That's not hard

**Comment by Armhulen** [comment]
They can close it after 24 hours, they can close it whenever if my total is negative

**Comment by optimumtact** [comment]
Then look at it this way

the comment is likely to make the maintainers 

a) more likely to close your pr
b) less likely to listen to your whining about it

**Comment by Armhulen** [comment]
@ShizCalev I can't set it to it's parent because that's not how the pathing works. I guess I could redo the pathing to make the path `/mob/living/simple_animal/hostile/poison/giant_spider/ice/hunter`
instead of '/mob/living/simple_animal/hostile/poison/giant_spider/hunter/ice' as it is right now

**Comment by ShizCalev** [comment]
Oh right my bad.

Set it on normal ice spiders too please then.

**Comment by Armhulen** [comment]
OK, but they don't have any toxins

**Comment by jughu** [comment]
Call them frostbite spiders since snowdin gateaway ded

**Comment by ShizCalev** [comment]
>frostbite spiders

Holy fuck

**Comment by jughu** [comment]
image

**Comment by optimumtact** [comment]
copyright material removed due to DMCA

**Comment by DoctoreMad** [comment]
Yeah right.

**Comment by Armhulen** [comment]
@optimumtact what'd you remove?

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by JJRcop** [comment]
@Armhulen a picture of a spider

**Pull request merged**
