### PR TITLE
Adds atmos investigate_log

### PR DESCRIPTION
**Pull request by tkdrg**
Sort of ported from the /vg/ atmos logging by N3X15 in a PR whose number I don't remember but it's there somewhere.
Right now includes opening/closing pumps and opening/closing canisters.
Also adds a message_admins() when a plasma canister is opened.

### CODE REVIEW

**Comment by TheVekter** [comment]
>Also adds a message_admins() when a plasma canister is opened.

:+1: Thank you based TK, can we make that for N2O cans as well?

**Comment by tkdrg** [comment]
Sure, I'll do that later.

**Comment by RemieRichards** [comment]
@tkdrg you doing that in this PR is it good to go?

**Comment by tkdrg** [comment]
@RemieRichards It's ready now.

**Pull request merged**
