### PR TITLE
Guardian/Parasite Naming

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
They're now named with a zodiac sign + the colour. Wanted something similar to tarot cards and this is what came to mind.

Aires Green, Taurus Red, Gemini Black etc

Removes unused code related to the biological version (which will never exist at this rate)

New sprites by ausops

:cl: Kor
add: Guardians/Parasites are now named after constellations, and have new sprites from Ausops.
/:cl:

### CODE REVIEW

**Comment by Anonus** [comment]
>Not including Ophiuchus at a really low probability

**Comment by Jordie0608** [comment]
>Terran star signs in space

**Comment by KorPhaeron** [comment]
>earth doesn't exist in space settings

**Comment by Cebasiz** [comment]
neeeeerds

**Comment by Iamgoofball** [comment]
ehhh, i dunno about this

it's fun having the same holoparasite as the HoS who stole one from a traitor and then fucking people over with it wandering around pretending to be his

**Comment by Iamgoofball** [comment]
>colour in description

:-1:

**Comment by KorPhaeron** [comment]
They've always had the colour in the name though

**Comment by Iamgoofball** [comment]
>colo**u**r

**Comment by KorPhaeron** [comment]
@tkdrg 

Ready

**Pull request merged**
