### PR TITLE
Benches and Beds: An Aesthetic Revolution

### PR DESCRIPTION
**Pull request by EOBGames**
Remember: no ERP, ERP is banned by the constitution.

## About The Pull Request
Ports benches and double beds from Skyrat.
Also makes beds rotatable, between left and right facing.
Additionally, the benches have received the GAGS treatment, allowing for lots of sweet customisation.

## Why It's Good For The Game
Benches are a no-brainer for aesthetics and have a fairly wide range of uses straight off the bat. Double beds are more something I've personally wanted for a while- something more plush for the captain's quarters, hilbert's hotel, et cetera.

## Changelog

:cl:
add: The local branch of IDEA in New Vladivostok has new furniture stock: benches and double beds, ready to make your house into a home. Pick up some meatballs while you're there, too.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
> Double beds are more something I've personally wanted for a while

I know your game lizard man

**Comment by EOBGames** [comment]
> > Double beds are more something I've personally wanted for a while
> 
> I know your game lizard man

is it SS13?

**Comment by MMMiracles** [comment]
yooo DIRECTIONAL BED

**Comment by EOBGames** [comment]
> yooo DIRECTIONAL BED

two directions of pure sleeping power, baby

**Comment by interestingusernam3** [comment]
Obligatory

>Port from Skyrat

**Comment by axietheaxolotl** [comment]
as the original skyrat maker

very based

**Comment by axietheaxolotl** [comment]
> Remember: no ERP, ERP is banned by the constitution.

though this is kinda cringe, I only added them for ERP smh :trollface:

**Comment by EOBGames** [comment]
> as the original skyrat maker
> 
> very based

Ah, are you the original maker of both benches and beds, or just the beds? I'd like to add you into the changelog for attribution purposes.

**Comment by maxymax13** [comment]
why the beds lmao

**Comment by EOBGames** [comment]
> why the beds lmao also at least please give them north/south sprites these dirs are fucking lazy

because spacemen are not capable of lying up and down- hence there being no sprite for them

**Comment by axietheaxolotl** [comment]
> 
> 
> > as the original skyrat maker
> > very based
> 
> Ah, are you the original maker of both benches and beds, or just the beds? I'd like to add you into the changelog for attribution purposes.

Just the beds. Sprites was someone else.

**Comment by GoldenAlpharex** [comment]
> > why the beds lmao also at least please give them north/south sprites these dirs are fucking lazy
> 
> because spacemen are not capable of lying up and down- hence there being no sprite for them

Well, lying up would just be standing up and using your imagination, but I digress

**Comment by Krysonism** [comment]
Please post screenshots of the gags benches, preferably in a couple different colours.

**Comment by GoldenAlpharex** [comment]
Also, I think both of those were ported, I'm not 100% on this but I think the bed sprite comes from Polaris and the Bench sprites come from Eris?

**Comment by Twaticus** [comment]
cannot approve double beds in good faith

**Comment by Zytolg** [comment]
> cannot approve double beds in good faith

You will approve them
Not because we need them
Because _you_ want them

**Pull request closed without merging**
