### PR TITLE
Removes khaki pants

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Removes khaki pants. Replaces them with the tan version in one instance.

## Why It's Good For The Game

They are ALMOST a duplicate of tan pants. Like, two pixels difference.
image

## Changelog
:cl:
del: Khaki pants have been removed, replaced with tan pants where appropriate.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
the BELT is DIFFERENT ok

**Comment by ExcessiveUseOfCobblestone** [comment]
Belt bros

**Comment by iwishforducks** [comment]
can we keep khakis and remove tan pants? khakis are way funnier than "Tan Pants"

**Comment by Farquaar** [comment]
Typical kneejerk khaki nerf PR

**Comment by dawsonkeyes** [comment]
anti-khaki salt pr

**Comment by EricZilla** [comment]
Agreed that tan pants should go khakis should stay, how you didnt come to that conclusion yourself is baffling

**Comment by cacogen** [comment]
I always thought khaki was green? Anyway I'd just shift the hues to be more different instead of removing pant

**Review by Twaticus — CHANGES_REQUESTED** [review]
keep khaki remove tan

**Comment by tralezab** [comment]
DNM until twat's review is handled

**Comment by tralezab** [comment]
not really going anywhere

**Pull request closed without merging**
