### PR TITLE
Talk wheel

### PR DESCRIPTION
**Pull request by phil235**
The talk wheel is a feature to help players say small predetermined messages without having to stop to type in the chat bar. You want someone to stop moving but every time you stop walking to type in the chat the other guy gets out of your field of view. If this scenario feels familiar, you'll like the talk wheel.

The feature is currently only available for humans. The predetermined messages available are "Hi", "Bye", "Thanks", "Come", "Help", "Stop", "Get out", "Yes", "No". Sometimes the message has multiple versions ("Hi", "Hello" ; "Thanks", "Thank you" ; etc...). There is a one second cooldown between uses to avoid spam.

The talk wheel button is next to the craft button. Feature only available to humans currently.

I made the button to toggle the wheel activatable with the hotkey "H" or "CTRL+H".

Thoughts?

scrnshot1f

:cl: phil235
experiment: adds a talk button next to the crafting button. Clicking it makes a "wheel" appear around you with short predetermined messages that you click to say them. This lets you say common responses without having to type in the chat bar. Current messages available are:  "Hi", "Bye", "Thanks", "Come", "Help", "Stop", "Get out", "Yes", and "No". The talk button can be activated with the hotkey "H" or "CTRL+H"
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
unrobust non hotkey user detected

**Comment by PKPenguin321** [comment]
neat

**Comment by jughu** [comment]
Help help help help help help help wheres the ';help'?

**Comment by Yoshmaster** [comment]
get out

**Comment by jughu** [comment]
No i demand "; HELP"

**Comment by Yoshmaster** [comment]
Because lord forbid you need time to think about a reply to something that has happened in a role playing game

**Comment by Razharas** [comment]
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!
>Good game, well played!

**Comment by Razharas** [comment]
Also we need a wheel to buy syndie stuff as op

**Comment by Cheridan** [comment]
Which one is the paragon option

**Comment by MrStonedOne** [comment]
Needs a hotkey to trigger it so you don't have to move your mouse to one side of the screen then the other.

needs click modifiers for ; and .h

**Comment by ExcessiveUseOfCobblestone** [comment]
> screaming help
> not screaming your location

looks like you need to git gud :^)

**Comment by MrStonedOne** [comment]
also, you can use fancy maths to make this dynamic for any count of items

**Comment by TechnoAlchemisto** [comment]
>no punctuation 

why live

**Comment by Saegrimr** [comment]
>no CHELP

**Comment by Incoming5643** [comment]
Putting the button at the lower right corner defeats the point of having the options circle the player entirely.

**Comment by Shadowlight213** [comment]
Meh. encourages powergame. As Yoshmaster pointed out, isn't SS13 supposed to be a Roleplaying game?
Giving players literally canned responses is really stupid.

**Comment by Jalleo** [comment]
I would say remove help and make it soall of these are local not radio.

**Comment by Razharas** [comment]
How about instead of making them static make people be able to preset the typical responces they want + add a delay between two uses to avoid ironic spam

**Comment by Razharas** [comment]
And not 9 but say 3, should be enough

**Comment by phil235** [comment]
@TechnoAlchemisto The messages have punctuation.

@MrStonedOne Ok for hotkey, but being able to use the wheel over radio would make it too powergamey imo. And what do you mean by making it dynamic for items?

@Jalleo I won't add radio talk to the wheel, but I don't think removing "help" will do any good, people will just spam "stop" or whatever or message to indicate they need help.

**Comment by xxalpha** [comment]
I am only okay with things like "Wait", saying hi or thanks shouldn't be buttons.

**Comment by phil235** [comment]
@Razharas There's already a one second delay, and you can already spam a message with regular chat by reusing the last message. I thought about custom message, but there's a big issue with it, people can preset messages with people's name, so some powergamer can have a station bounced radio in his pocket and some message for people he thinks could attack him, like "Help, Urist McDorf is attacking me". And you could even add a location if you spend most of your time in a given department ("Help, Urist McDorf is attacking me in Cargo!")

**Comment by AnturK** [comment]
Worth a try. 
You did the square effect for some specific reason instead of radial ?

**Comment by phil235** [comment]
>You did the square effect for some specific reason instead of radial ?

Just because it seemed easier to add squares. :grinning:

**Comment by Wyzack** [comment]
I agree that adding radio usage would be far too powergamey. I think this is a cool idea, but i don't think catering to the shitters who cannot be assed to talk to their fellow man is great

**Comment by phil235** [comment]
>I think this is a cool idea, but i don't think catering to the shitters who cannot be assed to talk to their fellow man is great.

Personally, I see things the other way around, the people who do write full sentences in chat won't stop doing that if this talk wheel is added, but the shitters who never utter a word because they can't be bothered will finally start talking even if it's just simple sentences.

**Comment by Wyzack** [comment]
Good point. Good feature. Merge he. I am convinced

**Comment by phil235** [comment]
I added a hotkey: H and Ctrl+H for the talk wheel.

Apparently editing skin.dmf added plenty of other lines, I don't know why...

**Comment by AnturK** [comment]
DM does this unfortunately you have to add the wanted changes with some text editor.

**Comment by phil235** [comment]
Thanks @AnturK

**Comment by MrStonedOne** [comment]
as in make it dynamic space out the items by how many their are, allowing for more than 9 by just having it automagically increase the spacing,

**Comment by TheWulfe** [comment]
Opinions in terms of implementation:
1. Local chat only, radio is too powergamey
2. Delay to avoid spam

And design idea:
1. StoneOne's dynamic spacing idea for more than 9 slots
2. Just wandering if it's hypothetically possible to make customizable Talk Wheels if we added the ability to 'assign' a wheelspot to your own customized message. Like have a seperate tab for it in game preferences if it could be done. Obviously this would be in a way future version of this.

Concept example:
samplechattab

**Comment by TechnoAlchemisto** [comment]
Customizable would be a bad idea

**Comment by Iamgoofball** [comment]
Why techno

**Comment by phil235** [comment]
If you could only set those custom messages before roundstart I guess it could work, as long as we don't give people too many custom ones.

**Comment by TechnoAlchemisto** [comment]
The idea of people having a quick way of saying "AI I am being killed please track me" and having multiple permutations of this that you can set doesn't sit well with me. I can only imagine a lot of really annoying things you could do with this that would allow people to send larger, complex messages before their headsets are stripped. 

Of course, this could also be done with copy and paste messages but that's just one option for a message and if you do that you're a top tier shitter. 

Typing speed being a limiter for how much information you can get off is a pretty decent mechanic, and I think that this is a good idea up to a certain character limit (probably below 12-16 characters.

**Comment by TechnoAlchemisto** [comment]
( most of that is assuming it's radio capable - but the same arguments apply for when you're being dragged through the hall past people )

**Comment by ike709** [comment]
I like this, but I like the idea of customizing it before roundstart even more.

**Comment by optimumtact** [comment]
These are not messages sent over the radio, they're also inferior to keyboard macros which people already use, this just evens the playing field slightly.

**Comment by ike709** [comment]
@TechnoAlchemisto I can literally set keyboard macros for dozens of variants of "AI I am being killed please track me" and use them easier than pressing the talkwheel hotkey and clicking the option I want. This literally reduces the issue of "AI HELP" spam because although I _can_ set keyboard macros that can be used faster and repeatedly with buttonmashing, I'm also pretty lazy and would prefer just setting it up ingame, where a delay between uses can be implemented, as well as a max limit on the number of custom phrases you can set.

**Comment by Xhuis** [comment]
\>Not having a variant of "Out" being "NORMIES GET OUT REEEEEEEE"
Do you even try, phil?

**Comment by Supermichael777** [comment]
needs special messages for retards

**Comment by CosmicScientist** [comment]
>Also we need a wheel to buy syndie stuff as op

\>forgetting the I'M RELOADING meme

**Comment by pudl** [comment]
hugbox

**Comment by pudl** [comment]
Seriously though this isnt needed, it adds clutter and again its just hugbox shit, its not that hard to type something, and if youre getting owned so hard that you cant type out a full message without using the wheel, then the guy whos owning you deserves that guarantee of silence. It means they did something right

**Comment by Iamgoofball** [comment]
quality of life isn't hugbox

**Comment by MrStonedOne** [comment]
I'm on the fence about this.

I say we allow radio, and allow customizing, but add a slight delay, based on number of characters or something, (0.5ds per letter?, so `help` would be 0.2, but `help ai killing me` would be almost a full second)

**Comment by CosmicScientist** [comment]
I'd be fine with what MSO is saying about this. I know not everyone is the best ~~keyboard abuser~~ typer and after the delay goes through, it's still under the same cutoffs as normal speech when getting stunn-GLORF, weakened or otherwise interrupted through change in circumstance.

The only thing I can think of that would cause a little concern is the ability to powargarme and use this quick chat when going into battle to let someone know something is wrong, even more so if you can customise your options. The only thing I'd say that might sort that out is you can't cover every situation with customised options and on the fly typing is going to give better or crucial details to a situation the quick chat may not.

**Comment by Bawhoppen** [comment]
@pudl we don't want you coming back stay away

**Comment by phil235** [comment]
Alright, PR should be ready.
I made the wheel system generic, so future coders can make different wheel types.
I gave the talk wheel to aliens, monkeys and cyborgs.

**Comment by FantasticFwoosh** [comment]
; what's the plan operatives?

Setting your own would be the greatest next step for memes

**Comment by Yoshmaster** [comment]
@Supermichael777 That's the talk wheel

**Comment by optimumtact** [comment]
Just waiting on a test merge and then this will go in

@KorPhaeron @Jordie0608 @Shadowlight213 @lzimann @MrStonedOne

**Comment by optimumtact** [comment]
Haven't heard any bad things

**Comment by Chocobro** [comment]
phil!
:O

**Pull request merged**
