### PR TITLE
Adds briefcase with cash to uplink

### PR DESCRIPTION
**Pull request by fleure**
Adds a secure briefcase filled with 5000 space credits as a pointless badassery traitor and nuke-ops item. The briefcase is also slightly more robust (8->15 brute damage). Costs 2TC on account of the extra robustness.

Update: Changed to 1 TC

### CODE REVIEW

**Comment by ike709** [comment]
Now we just need cash to have an actual use.

**Comment by Alek2ander** [comment]
I imagine using this for exchanging documents... but any traitor can hack it in one second with an emag so it's useless :/

**Comment by vista-** [comment]
Station should have a way bigger cash reserve as well, so taters/nuke ops could hold a hostage/station for ransom - perhaps a steal X space credits objective as well? (Just some ideas for another PR)

**Comment by fleure** [comment]
@Alek2ander That's a wider problem with safes and secure briefcases in general, they are laughably insecure. I was thinking of maybe adding a hacking minigame, like mastermind or something, to add some element of time consumption or skill to open them, but that's for another PR.

This was just an idea from the minor suggestions thread for a briefcase with cash, which I thought was neat for RP opportunities. It is "pointless" after all, and just adds some RP fluff in case someone wants to try buying a high priority item from a head or something.

**Comment by TZK13** [comment]
/vg/station has neat syndie briefcases that you can hide items inside of and fire hidden guns out of but obviously that would make it a far more versatile item than this is currently.

Also don't make it 2 TCs the syndie cards are 1 TC and have 10 throwforce which is rather robust when you have an entire deck of them to throw.

**Comment by vista-** [comment]
You should [make it glow](https://www.youtube.com/watch?v=LRRKKKUAtoc)(emit a bit of light), just for fun.

**Comment by MrPerson** [comment]
More useless bullshit. Feature in search of a purpose.

:-1: 

We already have the syndie balloon for useless badassness, we don't need another.

**Comment by TZK13** [comment]
It's a briefcase full of money, it's good for RP, RP is good.

**Comment by ike709** [comment]
This PR is preparing us for not for the economy we deserve, but for the economy we need.

**Comment by Miauw62** [comment]
We're not losing anything by adding this, and money can be used for tator
gimmicks, so this is ok by me.
Op 8-jan.-2015 03:11 schreef "homsar" <notifications@github.com>:

**Comment by Fox-McCloud** [comment]
I don't see this is as useless at all; it's good for RP, for one.

For another--and those who don't care about RP, it's still an extremely cheap and highly effective melee weapon.

**Comment by Jordie0608** [comment]
>Jordie hoses down fleure with the changelog

**Comment by fleure** [comment]
I'll get a todo done soon, I wasn't aware of the new process.

Also would having gold in the briefcase make more sense? Gold at least has some functional use.

**Pull request merged**
