### PR TITLE
[ICEBOX STATION] Removed metal panneling under SM coolant pipes

### PR DESCRIPTION
**Pull request by Quietly12**
## About The Pull Request

Metal floors are currently positioned below the SM radiator piping on Icebox and this insulates the piping from cooling or radiating heat properly to the cold planet atmosphere.

image

This change removes those metal floor tiles, and replaces them with standard icebox terrain.

image

## Why It's Good For The Game

-While still not as cold as other stations, the cooling loop in icebox will now actually function.
-Eliminates potential atmospherics heat expansion/contraction cycles outside of the station for an unnecessary performance hit.
-Allows the AI to manage the SM temperatures on icebox without physical intervention
-Probably solves global warming.

After in map

## Changelog
:cl: Disco
del: [Icebox] SM exterior cooling pipes have had unnecessary thermal shielding removed
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Good first pr

**Comment by kriskog** [comment]
Hmm
image

Did you use map merger? What mapper did you use?

**Comment by Quietly12** [comment]
> 
> 
> Hmm
> image
> 
> Did you use map merger? What mapper did you use?

First map edit, just downloaded/modified the map in SDMM and saved then tested it.

**Comment by kriskog** [comment]
You should be running map merger as well, see https://tgstation13.org/wiki/Map_Merger

**Pull request merged**
