### PR TITLE
STOP BREAKING THE LAW, ASS HOLE

### PR DESCRIPTION
**Pull request by Cheridan**
\>Cepstral Personal voices are for personal use only and are NOT licensed for audio distribution. This means the audio you create is for your use only and cannot be shared with others or used in videos, presentations, or webpages. If you are interested in an audio distribution license, please contact sales.

### CODE REVIEW

**Comment by Thunder12345** [comment]
So that's where those phrases came from

**Comment by Aurantiaco** [comment]
AH PISS

**Comment by Aurantiaco** [comment]
We're gonna get sued for our space game oh fuck

**Comment by Iamgoofball** [comment]
Whoa hold up a second let's re-record these

**Comment by dannno** [comment]
FUCK

**Comment by Anonmare** [comment]
Cool meme

**Comment by Supermichael777** [comment]
are we sure this is the source of those sounds?

**Comment by Supermichael777** [comment]
Im going to use e-speak to generate some copyleft sounds gpl3

**Pull request closed without merging**
