### PR TITLE
Resprited jetpacks

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Resprites absolutely ancient jetpack sprites.

image

## Why It's Good For The Game

Current jetpack sprites are most likely from exadv era and look accordingly, lacking any shading or texture.

## Changelog
:cl:
image: Resprited all jetpacks
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]

**Review by Imaginos16 — APPROVED** [review]
Cute

**Comment by LSommers** [comment]
> i dont think the captain one uses the right colors to match with captain
> 
> looks like jeans honestly

the jortpack

**Comment by projectkepler-ru** [comment]
INCREDIBLY BASED

**Comment by SmArtKar** [comment]
> i dont think the captain one uses the right colors to match with captain
> 
> looks like jeans honestly

It uses captain MODsuit color palette, I know that you can't wear both at the same time but I tried to make it fit with his other space gear

**Comment by MTandi** [comment]
Sorry to say this, but:

```
icons/mob/clothing/back.dmi
icons/mob/inhands/equipment/jetpacks_lefthand.dmi
icons/mob/inhands/equipment/jetpacks_righthand.dmi
```

**Comment by SmArtKar** [comment]
I hate you (thanks for reminding me, I'll resprite these too then"

**Pull request merged**
