### PR TITLE
Icemoon Shorelines - Monster-Station Interaction Prevention Scheme

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

On production (as well as several complaints that I have heard), there were a few instances where very strong icemoon fauna would wander into station structures. This was especially apparent on the lower z-level, where prisoners (being next-to-completely-defenseless) got owned extremely hard by wandering fauna.

So, I looked at a few options of fixing it. Shutters will _not_ do, that just obfuscates the problem and muddies "secure" and "non-secure" areas. Nerfing the fauna didn't really feel right to me, and more chasms doesn't really help on the lower z-level. So, I came up with _The Shoreline_.

Basically, it's a new type of cave generator area that does not spawn any fauna or megafauna. I went through the mining z-levels of IceBox and I added roughly 4-5 tiles between the "wilderness" and the developed station/chasms. I put them next to chasms because sometimes, fauna would fall down when they generate on ledges with nowhere to go. While polar bears would die in the plasma river, the demonic watchers would just immediately aggro and take no plasma damage.

## Why It's Good For The Game

The results were very encouraging in my local tests. It still retains that level of danger for miners who plunge further into the depths, while allowing the rest of the station who aren't armed with the hyper-specific machinery to tackle such problems to not get owned. Icemoon fauna have not been balanced since their introduction in 2020, and I think this is the best change that currently reflects how we have the map structured.

## Changelog

:cl:
balance: Nanotrasen has now implemented a "buffer zone" on IceBoxStation between the wilderness portions of the moon and the parts where there is a station presence. Hopefully, you should see a lot less fauna try to make their way on station.
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
I don't believe that the area where it's guaranteed that no mobs are spawned should filter all the way down to the station, as there should still be inherent danger involving mob encounters when escaping from perma / the gulag. I would remove it here:
image

Otherwise I think this is a sensible fix to mobs wandering into station structures. I might explore making all the areas currently attached to station areas not have open turf attached to the genturf.

**Comment by san7890** [comment]
> I don't believe that the area where it's guaranteed that no mobs are spawned should filter all the way down to the station, as there should still be inherent danger involving mob encounters when escaping from perma / the gulag. I would remove it here

In local testing, it seems that sometimes the cave generator will automatically "compensate", and throw in much larger enclaves of hostile mobs just right next to the shoreline. If there is a clear path formed between the shoreline and the outer parts of the "wilderness", hostile mobs may automatically "wander" out to the shoreline during normal gameplay (but to a much lesser extent than what we see on production). Do keep in mind that the name "shoreline" is a teeny bit misleading, it still spawns in snow/rocky mountainside walls and blends with the rest of the genturfs to form caves (it's not flat). It's stronger in that area to prevent the amount of times they "wander" along the river and fall into chasms. I'll trim it down a bit in that area, but the shorelines should still be larger in that area to prevent the lava-river wandering.

**Comment by wesoda25** [comment]
I thought you were adding a monster sea but this is cool too

**Comment by Son-of-Space** [comment]
Another thing we might want to do at a later date is have the mobs not drop their loot if they're killed by the plasma river.

**Review by Son-of-Space — APPROVED** [review]

**Comment by notfrying1pans** [comment]
ive had a colossus spawn at the window next to the lowest mining area lol

**Review by Maurukas — APPROVED** [review]
Looks good. No introduced active turfs. I see no genturfs peeking through the snow or any other issues.

**Pull request merged**
