### PR TITLE
Separates ship ambience and area ambience

### PR DESCRIPTION
**Pull request by ghost**
This PR separates the two types of ambience, ship and area ambience, into two separate toggles. This means that you can hear specific ambience while not hearing the normal humming ship ambience.

I plan on adding more actual ambience to different areas in the future.

### CODE REVIEW

**Comment by Xhuis** [comment]
travis pls

**Comment by WJohn** [comment]
Does this help with #6155 a little bit?

**Comment by Xhuis** [comment]
Not sure

**Comment by Incoming5643** [comment]
Fuck the humming :+1:

**Pull request merged**
