### PR TITLE
Primitive Technology - Charcoal Pens

### PR DESCRIPTION
**Pull request by fludd12**
image

## About The Pull Request
This is a super minor change to help me get back into the process of coding, but I felt it was pretty cool and it fit with the rest of the primitive technology design plan! It simply adds a craftable pen made with a single piece of wood and some ash. It writes in a unique font with a dim grey color.

image

## Why It's Good For The Game

I just think it's neat. It also adds a new available font for paperwork, which is pretty cool, too.

## Changelog
:cl:Fel
add: You can now craft something vaguely like a pen out of some wood and ash.
/:cl:

### CODE REVIEW

**Review by optimumtact — APPROVED** [review]

**Comment by Ohagi-Chan** [comment]
Keep out! Colosssssussss thissss way!
Good change.

**Comment by nemvar** [comment]
make it edible. screw code quality. i wanna nibble charcoal crayon!!!

**Comment by ATH1909** [comment]
> make it edible. screw code quality. i wanna nibble charcoal crayon!!!

Make it give you doses of multiver when you nibble on it, as a reference to multiver's former name.

**Comment by itseasytosee** [comment]
^^^^^^^^^

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
