### PR TITLE
Fix slime potions used on simple mobs to inherit all language abilities from the user

### LINKED ISSUE #67171: Sentient xenobio creatures are expected to follow orders from a master they share no tongue with
Reporting client version: 514.1583

## Round ID:
[183488](https://scrubby.melonmesa.com/round/183488)

## Testmerges:
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:
Be selected for sentient giant spider
Only speak/understad insect language
Have no idea if you're being told to do something

Seems like a bit of an oversight to me? If I'm supposed to follow orders I need to be able to understand them. Could sentience grant common, or at least an understanding of common?

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

Fixes #67171

Slime sentience and transfer potions will now grant all language abilities from whoever used the potion even if the language is blocked for the simple mob.

## Why It's Good For The Game

Scientists can now properly communicate with their minions to give orders.

## Changelog

:cl:
fix: Fix slime potions used on simple mobs to inherit all language abilities from the user
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
Balance change which I appreciate. Before I would use telepathy, Slime link, or if my pet is Beno circuits

**Comment by Likteer** [comment]
> Balance change

Indeed, while this is unnecessarily tedious, I think I remember it was a conscious change done by someone silly.
The removal of simplemob ability to read might also be tied to that, as you wouldn't really be able to communicate with the antag ones before they mow you down.

**Comment by private-tristan** [comment]
wait, does this allow them to speak the language as well, if so, I can get a new curator gimick

**Comment by timothymtorres** [comment]
> wait, does this allow them to speak the language as well

It allows them to both speak and understand the language(s)

**Pull request merged**
