### PR TITLE
Admin only dual wielding

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Have to set a var on the human. In the future maybe wizards or ops could buy the ability.

Closes #13912

### CODE REVIEW

**Comment by Zilenan91** [comment]
>dual-wielded staff of chaos dreams are still alive

**Comment by KazeEspada** [comment]
:-1:

**Comment by KorPhaeron** [comment]
@duncathan 

Either this one or #13950

**Comment by PKPenguin321** [comment]
i don't get what's so game breaking about this but if we have to lock dual wielding away i'd rather this PR get merged

**Comment by Zilenan91** [comment]
Why'd you close this?

**Comment by PKPenguin321** [comment]
the revert got merged instead of this one

**Comment by kpeculier** [comment]
We need to bring back the dream. This needs to be merged instead of the revert.

**Comment by PKPenguin321** [comment]
You're about 3 months late on that

**Pull request closed without merging**
