### PR TITLE
[TESTMERGE ONLY] Revert "[READY]Refactors uplinks to a component!"

### PR DESCRIPTION
**Pull request by praisenarsie**
Reverts tgstation/tgstation#32624

### CODE REVIEW

**Comment by praisenarsie** [comment]
testmerge only, kevinz broke uplinks

**Comment by kevinz000** [comment]
it works fine ya nerd

**Comment by DoctoreMad** [comment]
You are wrong.

**Comment by WJohn** [comment]
This looks very cool. Was wondering if something to this effect would be possible to use in crew monitoring consoles? Since that's static and also doesn't work on other z levels and is kind of broken or laggy a lot of the time.

**Comment by praisenarsie** [comment]
wjohn are you high

**Comment by WJohn** [comment]
Uhhhh, wrong PR. I meant to say that in the minimaps one.

**Pull request closed without merging**
