### PR TITLE
Small usability addition to Genetics DNA console interface.

### PR DESCRIPTION
**Pull request by emptyexpression**
## About The Pull Request
Highlights which DNA blocks need to be completed.
Old:
old
New:
new

## Why It's Good For The Game
This change reduces geneticist eye-strain and frustration.

## Changelog
:cl:
add: Added simple indicator for incomplete DNA blocks
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Very nice

**Comment by Rasselbok** [comment]
Can they stay red until the gene is solved? Sometimes when brute-forcing them it's possible to lose track of which ones were unknown if you get distracted mid-project.

**Comment by Dennok** [comment]
> Can they stay red until the gene is solved? Sometimes when brute-forcing them it's possible to lose track of which ones were unknown if you get distracted mid-project after trying a few combinations.

Better make it blue or yellow.
But for this need make system that memorize state of gene before you touch it.

**Comment by cacogen** [comment]
powercreepdisguisedasqol

**Comment by Dennok** [comment]
Need add detector for wrong blocks like ag tc aa tt cc gg

**Pull request merged**
