### PR TITLE
Ascended rust heretics are able to revive from death if on rust

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR makes that rust heretics will be able to revive while they are on rusted turfs, don't have negative health and have a brain.

## Why It's Good For The Game

Rust path is kinda weak, and rust heretic ascencion is also weak compared to other heretic ascencions, so it needs buffs. Also making ascended rust heretics revive on rust sounds fun and looks... cinematic?

## Changelog

:cl:
add: Ascended rust heretics are able to revive while on rust and not too damaged
/:cl:

### CODE REVIEW

**Comment by SuperSlayer0** [comment]
> How exactly would they revive ? Like regen coma, they have to heal to full and then revive or is it a specific timer ?

They to be atleast not in crit health level, and also there is a 10 second timer to prevent them reviving immideately when killed.

**Comment by CursedBirb** [comment]
But is dead rust heretic still healed by rust tiles?

**Comment by SuperSlayer0** [comment]
> But is dead rust heretic still healed by rust tiles?

If i understand how all it works - yes

**Review by MrMelbert — CHANGES_REQUESTED** [review]
I'm not entirely sold on this concept but at least it should have a longer CD than 10 seconds

**Comment by Shadowflame909** [comment]
I don't know how useful this will be with the don't have negative health drawback. Considering how loud and obvious ascensions are. If you are critted, your going to be mobbed until your a pound of tenderized meat

**Pull request closed without merging**
