### PR TITLE
Remove cns

### PR DESCRIPTION
**Pull request by JoshAdamPowell**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by JoshAdamPowell** [comment]
hopefully this fucker compiles

**Comment by CRITAWAKETS** [comment]
uhhh can you like add a PR

**Comment by LemonInTheDark** [comment]
The urge to speed close, it's so strong

**Comment by cacogen** [comment]
My guy just delets a thing he doesn't like and submits the blank template fucking Chad

**Comment by Jared-Fogle** [comment]
you're gonna have to put some more effort into this one

**Comment by Sinestia** [comment]
Didn't he.. uhh... have a PR and description earlier?

**Comment by MrDoomBringer** [comment]
> hopefully this fucker compiles

you can compile locally

**Pull request closed without merging**
