### PR TITLE
Fixes wild west windows

### LINKED ISSUE #13098: Wildwest.dm has strange immortal windows
Near the start area. Not sure whats going on with them, they have odd sprites as well.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes #13098

No screencap because the map looks exactly the same, the windows just aren't bizzare immortal ones with dir 5

### CODE REVIEW

**Comment by WJohn** [comment]
While you're at it please fix wild west by throwing it out.

It's easily one of the worst away missions we have.

**Comment by Shadowlight213** [comment]
@WJohn It's actually one of the better ones, as its one of the few that are combat centric rather than lootfest.
If you want to remove terrible away missions, get rid of station collision and the syndicate listening post ones.

**Comment by Bawhoppen** [comment]
space hotel update when

**Comment by KorPhaeron** [comment]
@Wjohn

I know you dislike it but the combat ones are most popular.

The exploration ones are only fun a couple times before you've memorized the story and secrets

**Comment by KorPhaeron** [comment]
@Shadowlight213

I already disabled those 2 serverside

**Pull request merged**
