### PR TITLE
Tweaks to Sneeze. Medical Scanner nerf.

### PR DESCRIPTION
**Pull request by LanCartwright**
tweak: Sneeze now causes you lose sight and get stunned for a short amount of time
tweak: Sneeze stats have been nerfed.
tweak: Medical scanners no longer show possible cure.
/:cl:

This has been tested. It all works.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
bad

**Comment by KorPhaeron** [comment]
how do you cure then

**Comment by ma44** [comment]
@KorPhaeron you cure with PANDEMIC
Also SNEEZE + COUGH means twice the chance to drop items, which is cancerous

**Comment by LanCartwright** [comment]
Could make Sneeze not drop small items, and add 2 radius spread to coughing.

**Comment by Shadowlight213** [comment]
Sneeze having no downsides is insane, considering it completely bypasses the transmission stat.

**Comment by Kromgar** [comment]
>scanners no longer show cure

Bullshit

**Comment by LanCartwright** [comment]
Get good/get the PANDEMIC.

**Comment by Bawhoppen** [comment]
:+1: on first change
:neutral_face: on second
:+1: on the last change

**Comment by PKPenguin321** [comment]
this was rejected before, at least the sneeze parts, btw

**Comment by LanCartwright** [comment]
On second review, Sneezing is overwhelmingly overpowered because it just doesn't have downsides.

I really don't see better punitive ways to deal with sneeze. Previous ideas were randomly losing a symptom but even that was rejected.

**Comment by Kromgar** [comment]
But if everyone has cough and sneeze and are dropping shit it will royally fuck up the game

**Comment by LanCartwright** [comment]
Then get it cured.

**Comment by ma44** [comment]
bit hard to cure when your dropping blood samples (there must be blood in a beaker, not a syringe) and dropping the sample will spill it all over on the floor.

**Comment by Niknakflak** [comment]
Bad

**Comment by AlexCrimson** [comment]
If you are nerfing Sneeze(which is fine, its pretty much a staple symptom), could you buff other forms of transmission? Like make it easier to contract a disease from walking over blood and make the blood infectious for longer?

I actually like the Scanner change. There should be more emphasis on using the Pandemic machine. Its already stupidly easy to cure pretty much anything. Every cure can be found on the station at roundstart, and super lethal diseases end up having easy to make cures.

**Comment by Bawhoppen** [comment]
actually now that I think of it, rather than making sneezing drop you item like coughing, make it stun you very briefly

**Pull request closed without merging**
