### PR TITLE
Removes nonsense from turf destroy

### PR DESCRIPTION
**Pull request by AnturK**
Not even going to try to guess what weirdness it caused besides component cleanup.

### CODE REVIEW

**Comment by optimumtact** [comment]
isn't this important due to turfs not getting deleted but reused?

**Comment by Dennok** [comment]
Turf be deleted anyway here 
https://github.com/tgstation/tgstation/blob/master/code/game/turfs/change_turf.dm#L100
Question. what force delete it.

**Comment by optimumtact** [comment]
no I mean, when you delete a turf in byond, it just changes it's type.

It might be related to that special handling.

I'd check the blame history of this line if possible.

**Comment by optimumtact** [comment]
@Cyberboss you remember why you put this in ?

**Comment by Cyberboss** [comment]
image

Old me is dumb, kill it with fire.

**Pull request merged**
