### PR TITLE
Reverts "Quieter Highlander" (SCOTLAND FOREVER)

### PR DESCRIPTION
**Pull request by Iamgoofball**
# SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

# FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOORRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

### CODE REVIEW

**Comment by Armhulen** [comment]
:+1:

**Comment by calzilla1** [comment]
:+1:

**Comment by Cyberboss** [comment]
:+1:

**Comment by Repukan** [comment]
👍

**Comment by KingPhilipIII** [comment]
👍

**Comment by banthebantz** [comment]
👍

**Comment by banthebantz** [comment]
👍

**Comment by juanototo2** [comment]
👍

**Comment by FantasticFwoosh** [comment]
👍

**Comment by Tacolizard** [comment]
👍

**Comment by BeeSting12** [comment]
👍

**Comment by optimumtact** [comment]
denied

**Comment by Iamgoofball** [comment]
Fucking irish

**Comment by PKPenguin321** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=5&t=10933

**Pull request closed without merging**
