### PR TITLE
Replaces the Cut() usage in the processing lists from the different c…

### PR DESCRIPTION
**Pull request by Aranclanos**
…ontrollers for a Remove()

### CODE REVIEW

**Comment by optimumtact** [comment]
This is probably for the best, since when something removes itself from the list in it's process it will cause unexpected bugs

**Comment by WJohn** [comment]
I'm gonna guess this requires a processing tag but I have no idea!

**Comment by Chnkr** [comment]
isn't calling `remove` slower?

**Comment by Aranclanos** [comment]
doesn't matter if its slower or faster, its only triggered when there are nulls in the list.
Some objects also remove themselves from the list on their own process, ending up cutting the wrong item from the list or runtiming when it tries to remove a slot that is bigger than the list lenght.

**Pull request merged**
