### PR TITLE
Adds an organ storage bag to the syndicate medborg

### LINKED ISSUE #32434: Syndicate mediborgs are missing an organ bag.
See title,
Its not much of a problem in an nuclear emergency round as other ops usually exist, but is annoying when you get polymorphed into one and cant do surgery alone.

### PR DESCRIPTION
**Pull request by Anonmare**
Fixes #32434

:cl:
fix: Adds an organ storage bag to the syndicate medborg.
/:cl:

### CODE REVIEW

**Review by ShizCalev — DISMISSED** [review]

**Comment by ShizCalev** [comment]
Actually, they're also missing 

/obj/item/reagent_containers/dropper,
/obj/item/reagent_containers/glass/beaker/large,
/obj/item/reagent_containers/syringe,
/obj/item/surgicaldrill,
/obj/item/extinguisher/mini,
/obj/item/borg/cyborghug/medical,
/obj/item/borg/lollipop

**Comment by octareenroon91** [comment]
I don't disagree with the suggestion, but why would these even be on a syndicate cyborg?

/obj/item/borg/cyborghug/medical,
/obj/item/borg/lollipop

**Comment by GunHog** [comment]
Surgical drills are only useful for tooth implants, right? I do not think a Syndie-Medborg has a need for beakers, syringes, droppers, cyberhugs, or lollipops (unless they are poisoned), either. It does not really hurt anything to add them, though.

The mini-extinguisher would actually make a difference as a combat medic, though. Nuke Ops tend to deal with fire and explosions quite often.

**Comment by octareenroon91** [comment]
beaker/dropper/syringe: poison delivery.
beaker: fill with welder fuel, splash with harm intent.
hug module: does this pick up stunned people?

**Comment by KorPhaeron** [comment]
It already has a hypospray full of poison, giving it beakers etc would just be clutter

**Comment by octareenroon91** [comment]
It seems that the hug module gives the proper help-intent message for helping a prone human, but doesn't actually do anything.

**Pull request merged**
