### PR TITLE
[tm only] resprites borgs

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

fully resprites borgs, github for some reason doesn't want to embed images for some reason, so weird.

tm-only because I might've fucked up with animations.

<details>
<summary></summary>
  
:trollface: 

</details>

## Why It's Good For The Game

we like good looking things, right?
## Changelog
:cl: axietheaxolotl / viro
image: resprites borgs fully
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
Where is my zaku engi borg sprite?

**Comment by necromanceranne** [comment]
These are nice I don't see what the meme is.

**Comment by JohnFulpWillard** [comment]
PRs can be testmerged while closed so I'm closing this.
I dunno if this is meant to be a temporary TM and later ask for a full merge, but i know it was denied in the past https://github.com/tgstation/tgstation/pull/68444 so should get spritetainer approval to make a new pr

**Comment by EricZilla** [comment]
Its interesting to see the progress after just a year

**Pull request closed without merging**
