### PR TITLE
Fix coffee maker items teleporting to AI/Cyborg locations

### LINKED ISSUE #88136: AIs can take coffee from coffee machines, teleporting it to their core
### Client Version:

_No response_

### Issue Summary:

see title

### Round ID:

[243141](https://scrubby.melonmesa.com/round/243141)

### Test Merge Information:

_No response_

### Reproduction Steps:

be ai
click on a coffeemaker machine
click take cup
coffee has been teleported to your core

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
- Fixes #88136

Both AIs and cyborgs would have coffee maker interactions that result in an item (sugar packets, coffee cups, coffee pots, etc.) teleporting to their location. This was due to the `ALLOW_SILICON_REACH` being used which doesn't enforce a radius distance check for silicons.

## Why It's Good For The Game
Those pesky silicons can no longer steal coffee from humans.

## Changelog
:cl:
fix: Fix coffee maker items teleporting to AI/Cyborg locations
/:cl:

### CODE REVIEW

**Comment by Dawnseer** [comment]
My plans, foiled...

**Comment by TagGamerGang22** [comment]
No fun allowed...

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Linter

**Comment by timothymtorres** [comment]
The last CI test had the linter randomly fail. All that needed to be done was rerun the test.

**Comment by Ghommie** [comment]
I'm only merging this because borgs and AIs cannot drink coffee.

**Pull request merged**
