### PR TITLE
Potted plants now layer properly

### PR DESCRIPTION
**Pull request by ChangelingRain**
plants properly layer above most mobs by default

### CODE REVIEW

**Comment by lzimann** [comment]
FUN REMOVAL

**Comment by ChangelingRain** [comment]
no fun may remain

**Comment by ma44** [comment]
This makes sense; You can't run around while being inside of a pot, how would you even move at all?

**Comment by bobdobbington** [comment]
Extremely lame, rePR the fix without the salty nerf please

**Comment by optimumtact** [comment]
About time they got the nerf

**Comment by Firecage** [comment]
>Potted plants slows you down. 

>Can easily walk around with a backpack filled with 50 sheets of metal(enough to create 12 or so walls), 50 sheets of reinforced glass(enough to create 25 large and thick windows), 50 sheets of metal rods, and also a couple of other 50 sheets of minerals, carrying a toolbox in your left hand, carrying a robot shell in your right hand, while also somehow dragging a full sized human body behind you, while wearing metal armour.

**Comment by KorPhaeron** [comment]
I dont see a need for a slowdown considering they take both hands to carry

**Comment by Cheridan** [comment]
>Kor "Captain Potted Plant" Phaeron doesn't think potted plants need a slowdown

HMMMM :suspect:

**Comment by optimumtact** [comment]
Kor's, no sense of right or wrong.

**Comment by optimumtact** [comment]
Well the thumbs up beat the thumbs down, so please remove the slowdown nerf from this pr.

**Pull request merged**
