### PR TITLE
removes some unused sound files

### LINKED ISSUE #86983: round_start_sounds.txt is depreciated
### Client Version:

_No response_

### Issue Summary:

changelog from 2017 says:
```php
  Jambread/RemieRichards/Incoming5643:
  - server: There is a new system for title music accessible from config/title_music
      folder. This system allows for multiple rotating lobby music without bloating
      Git as well as map specific lobby music. See the readme.txt in config/title_music
      for full details.
  - config: The previous method of title music selection, strings/round_start_sounds.txt
      has been depreciated by this change.
```
yet we still have this text file.
It confuses contributors and players, perhaps we should get rid of it?

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

see `strings\round_start_sounds.txt`

and line 1 of `code\controllers\subsystem\ticker.dm`

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
closes https://github.com/tgstation/tgstation/issues/86983
partially handles https://github.com/tgstation/tgstation/issues/86856
transfers the files to the asset repo: https://github.com/tgstation/tgstation/issues/86856
### Removed files:
- title0.ogg
- title1.mod
- compressed_air1.ogg
- compressed_air2.ogg
- door_lock.ogg
## Why It's Good For The Game
lobby music is handled by the box, these used to be defaults, but we don't need it here if it's unused otherwise (there is still some left in the codebase itself, which are used ingame). 
By doing this, we can reduce the amount of files you have to download when cloning.
## Changelog
nothing player facing

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
there is no reason to remove title tracks, they are codebase defaults and we do not develop exclusively for the /tg/station servers.
removing unused audio also doesn't save space on anything, though it's a good idea for clutter. repos are downloaded in the form of chains of commits, each commit changing a set of files. This just adds a new (relative to code) large change removing the audio files

**Comment by CRITAWAKETS** [comment]
This PR saves about 2 MB off of a 101 MB folder. I'm not really feeling the size reductions on this one, chief.

**Comment by SmArtKar** [comment]
Don't think that much more needs to be said

**Comment by LemonInTheDark** [comment]
(the other unused sounds could be removed just fine, I am just mad about title tracks)

**Comment by Sadboysuss** [comment]
> (the other unused sounds could be removed just fine, I am just mad about title tracks)

I was gonna edit this pr but smartkar closed it, moved it to https://github.com/tgstation/tgstation/pull/88642

**Comment by LemonInTheDark** [comment]
copy

**Pull request closed without merging**
