### PR TITLE
Removes unsimulated turfs.

### PR DESCRIPTION
**Pull request by Aranclanos**
Moves shuttle turfs to paths under /turf/simulated/floor and /turf/simulated/wall
Players can now safely build on top of shuttle turfs
Fixes issue #1711
Adds several but not all paths for the different types of floor turfs, most of them in plasteel_floor.dm
The turf pathings are still in need of a deeper organization, but this is at least a start

### CODE REVIEW

**Comment by Aranclanos** [comment]
6 hours and a half

**Comment by ike709** [comment]
"Fixes issue #1711" won't close the issue. Try "Fixes #1711"

**Comment by Aranclanos** [comment]
TWO STEPS AHEAD OF YOU PRETTY BOY

**Comment by Lumipharon** [comment]
Wait, will this finally mean I don't have to move 20 frames onto the white ship with a ripley to build my autism ship anymore?

Neat.

On the topic of shuttles however, a couple of bugs I've noticed.
1: If you install cameras on the white ship, the AI can see them just fine.
If you move the ship, it could still see them just fine.
The it moved back, and they broke.
Moved to a different place and they worked again.

Dunno exactly what was going on there, maybe something to do with appear back on a z-level where they previously existed?

2: Atmos pipes work perfectly fine during and after transit, but disposal pipes don''t like travel - they break when you move, or so Francium told me.

**Comment by Aranclanos** [comment]
is that related to this pr or you're just rambling

**Comment by optimumtact** [comment]
You need to update the other maps

**Comment by HoaxIT** [comment]
:+1:

**Comment by CorruptComputer** [comment]
How does this effect atmos processing on centcom?

**Comment by Aranclanos** [comment]
atmos processing will be the same, there won't be overheads unless something activates the centcomm turfs

**Comment by Aranclanos** [comment]
rip

**Pull request closed without merging**
