### PR TITLE
Removes monkeycube and chocolate unwrapping

### PR DESCRIPTION
**Pull request by MrPerson**
Pointless time wasters that add nothing to the game experience. Also removed the two wrapped sprites for completeness.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>INB4 MASSIVE WAVE OF BIKESHEDDING

this is FINE it removes something that added nothing in the first place PLEASE DO NOT START A SHITSTORM OVER THIS please and thank you

**Comment by WJohn** [comment]
I really doubt anyone will miss this waste of time.

Now that that has been mentioned, EVERYONE is gonna bitch about it, just because.

**Comment by Iamgoofball** [comment]
This kills tactical unwraps. Yes, I'm serious.

**Comment by Zilenan91** [comment]
Can you still make Candy make candy wrapper waste after you've eaten them?

**Comment by MrPerson** [comment]
I didn't touch any part of the trash generation code

**Comment by optimumtact** [comment]
MUH TACTICAL UNWRAPS REEEEEEEEEEEEEEEEEe

**Comment by xxalpha** [comment]
Doesn't the wrap protect the monkey cubes from water and thus unwanted expansion?

**Comment by MrPerson** [comment]
If you don't want it to expand, don't put it in water

**Comment by Shapsy** [comment]
>not using the secret monkeycube technique

Smh

**Comment by Aloraydrel** [comment]
>trying to fight traitor
>He throws monkey cubes that are now unwrapped giving him the extra 0.05 of a second to spray water at them
>My taser shot gets blocked


Wooooooow

**Comment by Bawhoppen** [comment]
:-1: seriously you going to do this
don't give me the shit 'oh it contributed nothing' because thats complete bullshit

**Comment by PKPenguin321** [comment]
hahahha thanks bawhoppen for verifying my inb4, i knew i could count on you

**Comment by AdamElTablawy** [comment]
bawhoppen i know you like to shit your man-diaper over any change that adds or removes something but

its fucking wrapping paper it literally added one extra click

**Comment by Bawhoppen** [comment]
huh, that seems like what everyone else does when anyone ever makes a change

sometimes people forget this is an RP game

**Comment by PKPenguin321** [comment]
ONE CLICK REMOVED FROM WRAPPING MONKEY CUBES RP RUINED FOREVER

**Comment by AdamElTablawy** [comment]
>me sensually unwraps the monkey cube

# RUINED

**Comment by Bawhoppen** [comment]
I'm okay with the monkey wrappers being removed but chocolate wrappers actually do serve a real purpose

**Comment by PKPenguin321** [comment]
not really as far as i can tell from this code

**Comment by MrPerson** [comment]
Enlighten me, what purpose is that?

**Comment by Razharas** [comment]
Its ok

**Pull request merged**
