### PR TITLE
[DNM/Heavily WIP]Refactors how AI control checking works, adds click intercepting for cybernetic arm implants, but most importantly, cybernetic arm control interfaces/hacktools

### PR DESCRIPTION
**Pull request by silicons**
Heavily WIP.
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=10019
Description to come as soon as things get a bit more finalized, go to that thread for now.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Yaaay

**Comment by Militaires** [comment]
@oranges u behead me for a 95% finished wip PRs but kevinz does this and the gubbermint doesnt even turn a head rEEEEEEEEEE

**Comment by kevinz000** [comment]
@Militaires nyaaaa
Now he'll behead me.

**Comment by kevinz000** [comment]
Also to be fair I'm refactoring ai control which won't take more than a week if I don't run into trouble. The actual implant just calls ai attack.or whatever.

**Comment by kevinz000** [comment]
Too busy to do this this is not dead

**Pull request closed without merging**
