### PR TITLE
Desert Eagle Sprite Change

### PR DESCRIPTION
**Pull request by JStheguy**
:cl: JStheguy
imageadd: Changed Desert Eagle sprites, changed .50 AE magazine sprites, added Desert Eagle magazine overlay to icons/obj/guns/projectile.dmi.
tweak: The empty Desert Eagle sprite now only displays on an empty chamber. The existence or lack thereof of the magazine is rendered using an overlay instead.
/:cl:
image
Desert Eagle sprites.  Top row are the pre-existing Desert Eagle sprites. 2nd from top are sprites for Desert Eagles which have a bullet in the chamber and a magazine loaded. 3rd from top are sprites for Desert Eagles which have no bullet in the chamber and a magazine loaded. 4th and 5th from the top are the same as the 2nd and 3rd from the top, but with no magazine loaded. As mentioned in the changelog, the appearance of the magazine in the gun is accomplished using an overlay, to avoid doubling the number of sprites needed to display the various states a Desert Eagle can be in.
image
New .50 AE magazine sprites.

### CODE REVIEW

**Comment by RemieRichards** [comment]
>JS spriting
>TankNut thumbing up the PR

WHAT YEAR IS THIS!?

**Comment by xxalpha** [comment]
The ```CURRENT_YEAR```.

**Comment by WJohn** [comment]
These do look smaller than our current ones, though I prefer the colors that these have.

I dunno, I always feel like desert eagles should just be these monstrously large pistols with super thick barrels.

Anyway, 👍 for the empty chamber versions, at least.

**Comment by JStheguy** [comment]
Yeah, they are smaller than the current ones so that the empty chamber sprites fit.
But object sprites have never been accurate to the actual sizes of things anyways, the M1911 sprites are notably larger than the combat shotgun sprites.

**Comment by FantasticFwoosh** [comment]
Engravings offer you no tactical advantage whatsoever.

**Comment by Militaires** [comment]
@fantasticfwoosh you tend to twist your elbow to absorb the recoil





















.













that's more of a revolver technique


.

**Pull request merged**
