### PR TITLE
Adds a loose syndicate brand MMi to robo/rd/doctor/cmo traitors only for 2 tc

### PR DESCRIPTION
**Pull request by jughu**
Sometimes emagging a borg could leave serious damage to its interface being immediatly noticed when you tinker with the cyborg.
yes i know you can get this by buying a big ass black dufflebag which makes you scream out TRAITOR sometimes just having something loose apply better to jobs who already got the tools to tinker with people, while surgery bags apply more to people who don't have the tools.

## Changelog
:cl: Improvedname
add: RD/Roboticists/Cmo/Doctors can now buy a syndi brand MMi from their uplink for 2 tc
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
i know i got the wrong subtype will fix it when i get home from hospital

**Comment by AlinaStarkova** [comment]
you can probably allow medical doctors to buy it too, since they have the tools to brain an MMI and if they wish they can get a cyborg shell from maint

**Comment by moocowswag** [comment]
Are brains inside of the mmi obligated to assist you / not rat you out before being put into a borg shell?

If so this could also double as a fun way for traitors to turn people into circuit drones or making them into a sentient door or control the tram or something silly.

**Comment by jughu** [comment]
thats sadly out of the scope for the intention of the PR rn, i need to make an seperate PR for that honestly

**Comment by AlinaStarkova** [comment]
> Are brains inside of the mmi obligated to assist you / not rat you out before being put into a borg shell?
> 
> If so this could also double as a fun way for traitors to turn people into circuit drones or making them into a sentient door or control the tram or something silly.
> 
> It just seems like a big stepping stone for circuit related content as a byproduct.

MMIs do not have laws until borged. that said, you can turn the radio off of an MMI before putting a brain in so they can't yell over comma :)

**Comment by moocowswag** [comment]
> > Are brains inside of the mmi obligated to assist you / not rat you out before being put into a borg shell?
> > If so this could also double as a fun way for traitors to turn people into circuit drones or making them into a sentient door or control the tram or something silly.
> > It just seems like a big stepping stone for circuit related content as a byproduct.
> 
> MMIs do not have laws until borged. that said, you can turn the radio off of an MMI before putting a brain in so they can't yell over comma :)

Im aware but a syndicate mmi could be different similar to a posibrain in that the one who made/ordered it is supposed to be what they are aligned with. And turning off the radio wont stop someone from saying "x is bad reeeee" before being put into borg shell and hoping someone walks by to see the leftover runechat.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
