### PR TITLE
Flash confusion stacking clamped to 2x of power

### PR DESCRIPTION
**Pull request by silicons**
so 10 seconds in most cases unless admins custom proccall'd or something
@optimumtact

### CODE REVIEW

**Comment by kevinz000** [comment]
@optimumtact if you were actually joking close it you sounded serious

**Comment by obscolene** [comment]
now get rid of this filthy PR you devil

**Comment by optimumtact** [comment]
he did it better than me

**Comment by ExcessiveUseOfCobblestone** [comment]
Status effects should have an argument for stacking tbh.

**Comment by Wilchenx** [comment]
hey i got something nerfed again

**Pull request merged**
