### PR TITLE
Changes Icebox's Fore Maintenance and Service Hall.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Icebox suffers from Box's issues regarding it's service hall: It was really just thrown into maintenance with very little consideration. This works the service hall into an actual hallway behind most of the service rooms on icebox, and adds a bit more flavor to the surrounding icebox maint to boot.

The area behind the bar-theater-kitchen has been rolled into one large hallway alongside the service techlathe. 

The area where the old service hall was has been swapped out for 2 new rooms, a small "gamer hut" with an unfinished compuer frame and a civilian modular computer console.

The area to the left of the blast door assembly has been retrofitted into a small gym space.

The weird single window pane queue line has been swapped out for a railing based queue line.

The window hole between hydroponics and the library has been replaced with a "true" hole now.

To best view the changes, go to the "changes" tab for the PR and click MapDiffBot for cleaner screenshots.

## Why It's Good For The Game

Box station's mait was never all that well thought out, and the service hallway in particular has drawn my ire for the last time. This makes the whole zone a bit better laid out, while leaving the maintenance loop around the station intact from the holodeck to the chapel. Plus, now service will have a collective area to meet/congregate/start a book club/club a guy to death with a book that isn't just their backrooms.

## Changelog
:cl:
tweak: Icebox Maintenance, and Icebox Service Hallway have been rearranged to be more spacious.
/:cl:

### CODE REVIEW

**Comment by Twaticus** [comment]
decals on wood floors :woozy_face:

**Comment by Iatots** [comment]
What is this service area mania? Between this and midnightred's PR, it seems we have moved past the "everything must be like metastation" phase into the "everything must be like deltastation" one. No, the service staff doesn't need a well lit room to mingle in and post portaits of their favourite catgirls. They need a poorly lit tunnel to kill or be killed into. In that regard everything on the right side is good, if not for the random railings.
I have no idea what "window hole" you are referring to, I assume what you turned into the gym?
Also you are missing a pipe. 

As the maint portion does look better, I'd best like something like this:
e

note the missing pipe section.

**Comment by ArcaneMusic** [comment]
> What is this service area mania? Between this and midnightred's PR, it seems we have moved past the "everything must be like metastation" phase into the "everything must be like deltastation" one. No, the service staff doesn't need a well lit room to mingle in and post portaits of their favourite catgirls. They need a poorly lit tunnel to kill or be killed into. In that regard everything on the right side is good, if not for the random railings.
> I have no idea what "window hole" you are referring to, I assume what you turned into the gym?
> Also you are missing a pipe.
> 
> As the maint portion does look better, I'd best like something like this:
> e
> 
> note the missing pipe section.

Well, agree to disagree on the first point. Having a central room in each department to intermingle is nice and helps service feel like an actual collective "department" as opposed to a bunch of room someone threw next to each other.
Plus, Icebox doesn't have a painting gallery, and I had some empty walls, so it worked out.

**Comment by Angustmeta** [comment]
Is that a static or random living mouse in the gamer den? I wouldn't like hearing the squeeks every round. 

A firelocker in maint would be nice.

**Comment by Iatots** [comment]
> 
> 
> >    e
> 
> Well, agree to disagree on the first point. Having a central room in each department to intermingle is nice and helps service feel like an actual collective "department" as opposed to a bunch of room someone threw next to each other.
> Plus, Icebox doesn't have a painting gallery, and I had some empty walls, so it worked out.

Chef wants a break and a chat with the bartender? He sits at the bar.
Clown wants feedback on his routine? He can give a little rehearsal show, in the theatre or on the table between kitchen and bar.
The bar IS the mingling zone.

**Pull request merged**
