### PR TITLE
Removes i did not grief them

### PR DESCRIPTION
**Pull request by Niknakflak**
A shitty meme injected by goof, never fit in with the atmosphere of SS13 at all imo,
dumb meme that dirtied up the beautiful and amazing lobby sounds that already existed. 

See: https://github.com/tgstation/tgstation/pull/23880  

for some great opinions of people voicing support for removing of this joke lobby sound.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Iamgoofball** [comment]
This is also literally a server config

@lzimann mind closing this

**Comment by lzimann** [comment]
remove title4 too

**Comment by Niknakflak** [comment]
no, title4 is legacy and history and on a fair amount of other servers sitting in the role as the suspenseful role in the music lobby.

The room is a dumb joke shoehorned by goofball and now shoehorned to have this PR closed asap despite anonymousnow, oranges, kor, and more expressing previous positivism to this change

**Comment by Tacolizard** [comment]
i like title4.

**Comment by RandomMarine** [comment]
Back in the day all we had was robocop, the swingy theme, and a low chance of honk.

**Comment by Tacolizard** [comment]
>this is a better song then LOL ROBOCOP #stolen

you are a disgrace.

**Comment by lzimann** [comment]
title4 fucking sucks, there's nothing of legacy on it, I don't give about other servers

**Comment by Tacolizard** [comment]
i mean title4 isn't as good as the others but I do think it has value. It matches the environment well.

**Comment by Niknakflak** [comment]
This isn't about title4, this is about the room, fucking flute solo bullshit in the lobby

**Comment by Iamgoofball** [comment]
Yeah buddy, remove your sound babby if you're going to remove my soundbabby

**Comment by Tacolizard** [comment]
also the calm theme isn't stolen, it's a remix of the original robocop song.

**Comment by Niknakflak** [comment]
No, the room sucks.  Title4 does not

**Comment by Tacolizard** [comment]
except goof, the room is your soundbabby only. title4 is the collective soundbabby of many people.

**Comment by lzimann** [comment]
After listening to both, the room isn't even that bad, it's better than title4.

**Comment by Tacolizard** [comment]
except for people who recognize the room song, it feels extremely out of place in spess.

**Comment by Tacolizard** [comment]
WOAH THERE LZIMANN WHY DNM TAG

**Comment by Niknakflak** [comment]
he's injecting his personal opinion to basically do whatever he wants

**Comment by Tacolizard** [comment]
>**Maintainers**
>Maintainers are quality control. If a proposed pull request does not meet the mentioned quality specifications then it can be closed if you fail to satisfy them. Maintainers are required to give a reason for closing the pull request.
>Maintainers can revert your changes if they feel they are not worth maintaining or if they did not live up to the quality specifications.

huh doesn't seem like any code standards are being enforced by this DNM tag

**Comment by lzimann** [comment]
Anyway, this is not going anywhere. Feel free to prove me wrong @tgstation/commit-access

**Comment by Tacolizard** [comment]
>Maintainers are required to give a reason for closing the pull request.

**Comment by Iamgoofball** [comment]
he already did though, niknak refused to comply with this

**Comment by Tacolizard** [comment]
what reason did he give? because I don't see one anywhere.

**Comment by WJohn** [comment]
I myself never felt the room had anything to do with ss13. I get that the game is meant to be goofy and full of references of other sci-fi things, but the room is completely disconnected from that. I'd say remove it.

**Comment by Tacolizard** [comment]
well it's in lzimann's hands now. ((((even though he's not allowed to do this re))))

**Comment by Iamgoofball** [comment]
I understand reading comprehension is hard for people on the spectrum, but re-read what lzimann said in his posts

**Comment by Tacolizard** [comment]
>After listening to both, the room isn't even that bad, it's better than title4.

this is the closest thing he said to a reason, but it just reads like a casual observation. He didn't say 'I'm closing this because i like the room'

**Comment by lzimann** [comment]
Removing a sound for "no ambience" when none of our other lobbies provide this is not a really good excuse

**Comment by Niknakflak** [comment]
no ambiance was never referenced, its all about opinion here.  

If you think none of the other lobby musics add anything to this game, I don't know what to say to you here, if that's the case, you shouldn't be the one to make any calls about music at all if they have no relevance to you.

**Comment by Cyberboss** [comment]
24h for this one

**Comment by Tacolizard** [comment]
>lzimann removed the FUCK label just now

jeez leoz

**Comment by Armhulen** [comment]
cold

**Comment by Iamgoofball** [comment]
hexchat_2017-06-27_13-44-12

**Comment by Iamgoofball** [comment]
and for posterity when he tries to complain about screenshotting
hexchat_2017-06-27_13-49-55

**Comment by ExcessiveUseOfCobblestone** [comment]
Remove all lobby sounds except 1 and 2 like it was and should be.

**Comment by PKPenguin321** [comment]
@ExcessiveUseOfCobblestone no title3 is also good it was made just for our game and the creator of the remixed original song is happy about it too

this song can go though

**Comment by monkeyboyinc** [comment]
Honestly, I felt that The Room was a really good fit for Space Station 13. It's practically the theme song of "I tried really hard, yet failed completely in every way", something which I think we all experience often in this game.

**Comment by Bawhoppen** [comment]
Either we go full blown variety of lobby songs or have a limited meaningful selection, we can't just add random songs like this

**Comment by The-clown-known-as-Pepe** [comment]
The Room theme song is actually a really catchy tune, personally I want it to stay.

**Comment by Sligneris** [comment]
It's something from The Room?

It sounded like a medieval-style tune to me. Would perhaps belong on Lifeweb for example, but it doesn't seem like it fits SS13 much.

**Review by Cyberboss — APPROVED** [review]

**Comment by lzimann** [comment]
fuck this

**Pull request merged**
