### PR TITLE
Ghosts can now scan for radiation

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

"Toggle Radiation Scan" has been added to the ghost menu, allowing ghosts to scan for radiation.

## Why It's Good For The Game

Ghosts often miss out on seeing how much radiation is around in rounds where one person manages to irradiate everyone on this station. This PR fixes this much troubling issue.

## Changelog
:cl:NewSta
add: A toggle allowing ghosts to scan for radiation has been added
tweak: Ghosts now have cooldowns for gas and radiation scanning
code: Geiger counter's radiation scan is now in scanners.dm
/:cl:

### CODE REVIEW

**Comment by XDTM** [comment]
you need some kind of cooldown mechanism since it's apparently an expensive proc and spamming it on every click can cause lag

**Comment by europaisch** [comment]
> you need some kind of cooldown mechanism since it's apparently an expensive proc and spamming it on every click can cause lag

ok but how

**Comment by willox** [comment]
Is there any reason for `scanned` to be inside the observer rather being a normal variable in `/atom/proc/attack_ghost`?

**Comment by europaisch** [comment]
not really, I guess - good point

will fix that

**Comment by Repukan** [comment]
3.6 Roentgen, not good but not terrible

**Comment by Dorsisdwarf** [comment]
what happened to the old radiation vision

**Comment by europaisch** [comment]
> what happened to the old radiation vision

wdym

old features were not changed, I merely added a new one

**Comment by ninjanomnom** [comment]
There's a vision mode I made a while back for seeing radiation but I dont know if ghosts ever got it

**Comment by FloranOtten** [comment]
> 3.6 Roentgen, not good but not terrible

You didn't see the radiation vision. YOU DIDDENT. BECAUSE IT'S NOT. THERE.

**Comment by Repukan** [comment]
This man is delusional, take him to medbay

**Comment by optimumtact** [comment]
give them the radiation hud instead

**Comment by europaisch** [comment]
will do

**Pull request closed without merging**
