### PR TITLE
Adds in a gatling commando and AI assassin outfit. Tweaks the assassin outfit.

### PR DESCRIPTION
**Pull request by ma44**
NOTE THAT THIS IS SOME PRESETS FOR ADMIN SPAWN ONLY, THESE ARE NOT BUNDLES YOU CAN SPAWN WITH

Makes the assassin able to pursue or escape easier and also has a tool to quickly gib a body after shooting them with a .357 or eswording

The gatling commando is a DS commando that doesn't have a backpack; instead they are given a laser gatling gun. This provides immense firepower, expect they do not have much to offer besides that. 

The AI assassin comes with many useful tools (such as emp clusterbangs, AI uploads and a ion rifle) to deal with murderous AIs, mechs or regular borgs. Can also be paired with DS to help kill the traitorous station, break into areas and disable the enemies laser guns.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Adrenal is almost too much value

**Comment by ma44** [comment]
To be fair this is only spawned by the admin

**Comment by PKPenguin321** [comment]
outfits != bundles by the way

**Comment by ma44** [comment]
@PKPenguin321 im not trying to powergame that hard

**Comment by Niknakflak** [comment]
as an admin, I can say these are un-needed and dumb. 
The AI "assassin"~~retard~~ has a crossbow, that does toxin damage and literally nothing to silicons.  No flash, and no insulated gloves or toolbelt. 
And the other outfit is literally just a deathsquad but with a gattling gun which can be spawned easy as fuck. 
Outfits should be different enough that the point of them is that admins use the select equipment verb over the "spawn" verb.  They also shouldn't be dumb and not even put together well like these are.

**Comment by nullbear** [comment]
Code = fine.
Design = poor.

**Comment by Niknakflak** [comment]
checks failing probably means the code is not fine

**Pull request closed without merging**
