### PR TITLE
Update Toxins.dm

### PR DESCRIPTION
**Pull request by wassupninja**
Added a recipe. Simple, yet effective. Added generic poison.

### CODE REVIEW

**Comment by WJohn** [comment]
Doesn't this need an actual function someplace to make it do something? A recipe alone just means you'd have a chemical that does absolutely nothing.

**Comment by neersighted** [comment]
This PR does nothing. There is no "poison" reagent defined in the code.

**Comment by PKPenguin321** [comment]
>merging from master

you're gonna regret this

**Comment by wassupninja** [comment]
That's the beauty of it. It's a gag.

**Pull request closed without merging**
