### PR TITLE
Fake troll horns for even more awful, terrible Homestuck garbage.

### PR DESCRIPTION
**Pull request by ChahutMaenad**
[Changelogs]: Adds Fake Horns to the Autodrobe, which can be worn by players or corgis. Thanks to CRTXBacon for helping me understand what the hell I was looking at when I coded it in.

### CODE REVIEW

**Comment by 81Denton** [comment]
>>>>>>homestuck

**Comment by Ratvar** [comment]
horns should be cursed

**Comment by Tlaltecuhtli** [comment]
F U C K H O M E S T U C K R E F E R E N C E S

**Comment by ChahutMaenad** [comment]
i agree the author very dumb yes

**Comment by optimumtact** [comment]
This is a harbourstation dev alt account.

**Comment by CRTXBacon** [comment]
Actually this is no alt. I'm friends with him and know he can't dev with DM and has never even heard of harbourstation. If you suspect it's an alt because of the name, Chahut Maenad is a character in the homestuck universe.

**Comment by optimumtact** [comment]
Then what is this? said on the same day as this PR, a few hours before it was opened.

That is an incredibly unlikely coincidence

**Comment by optimumtact** [comment]
on top of that, not really interested in more homestuck references

**Comment by ChahutMaenad** [comment]
It is exactly what you've said, an incredibly unlikely coincidence. I conceived the original idea for troll horns and Ian compatibility at LEAST five months ago due to the pun 'Troll-Ian' popping to mind. Not until this entire shitfest have I even heard of Shezza or Harbourstation, and this is all a complete and total misunderstanding. I've been trying to contact you on Discord to clear it up, though you've yet to reply.

**Comment by optimumtact** [comment]
I don't respond to discord direct messages from people unless I know them, you're better off contacting me in public channels.

@Cyberboss @tgstation/commit-access thoughts?

**Comment by Cyberboss** [comment]
I'm one of the biggest closet Homestuck fans this codebase has but this
just lacks tact.

**Comment by ChahutMaenad** [comment]
I'm willing to provide any means of verification that I'm not whoever this Shezza guy is, if need be.

**Comment by PKPenguin321** [comment]
did we abolish the no references policy or something? why is this even being debated

**Comment by optimumtact** [comment]
1) i think they're a harbourstation dev alt

2) I don't like the thing

**Comment by ninjanomnom** [comment]
Being a harborstation dev doesn't even really matter. We just don't want this and this sort of feature addition is usually done as a shitpost so oranges is shitposting back.

**Comment by Iamgoofball** [comment]
>Joined 2 days ago

you know it's a common tactic to use a character name to get away with not being able to point out who someone is, and it's weird that you pointed your name out like that

**Pull request closed without merging**
