### PR TITLE
removes duplicate definition

### PR DESCRIPTION
**Pull request by PKPenguin321**
Fixes https://github.com/tgstation/tgstation/issues/17961

shouldnt have any effect on the actual game playerside

### CODE REVIEW

**Comment by ChangelingRain** [comment]
This is probably why gyrojets were so lethal.

**Comment by xxalpha** [comment]
If that ..() is calling the other definition, yeah.

**Comment by Giacom** [comment]
Pretty sure that what happens is if there is two definitions then BYOND will just use the first one it reads when compiling.

**Comment by RemieRichards** [comment]
@Giacom it actually allows for some really odd stuff.
these two definitions will actually live side by side perfectly fine, but like, the first ```..()``` goes to the second (or the first?) definition, and then any ```..()``` will go to any MORE side definitions, before finally going down the type tree.

You'd best ask @MrStonedOne he understands it better than I do.

**Pull request merged**
