### PR TITLE
You can now no longer use disposal bins from inside, as it was intended.

### PR DESCRIPTION
**Pull request by silicons**
Woops! Sorry about that.

### CODE REVIEW

**Comment by CitrusGender** [comment]
wait how did this happen

**Comment by GuppyLaxx** [comment]
no

**Comment by RandomMarine** [comment]
doodle

**Comment by vuonojenmustaturska** [comment]
does this actually matter, people have been able to self-disposal just fine

**Comment by YakumoChen** [comment]
it's not actually hard to do this while you're climbing in anyway

**Comment by Bluespace** [comment]
I didn't even know this changed.

**Comment by Buggy123** [comment]
Just leave it tbh.

**Comment by davethwave** [comment]
I just did it the turn it on while climbing in it method, never knew I could activate it from the inside.

**Review by Cyberboss — APPROVED** [review]

**Comment by Jalleo** [comment]
It used to work like this a long time ago. It was removed for very good reason.

**Comment by Buggy123** [comment]
>It used to work like this a long time ago. It was removed for very good reason.

Okay, but what is that reason? None of us have figured it out.

**Comment by YakumoChen** [comment]
Probably I guess so you can't just squat in the disposal bin and then have a choice to flush or crawl out when the coast is clear. Either you're hiding, or you're going down the tube.

**Comment by ExcessiveUseOfCobblestone** [comment]
Good fix, can’t wait to revert it after you get your gbp!

**Pull request merged**
