### PR TITLE
Fixes mutation toxin spam

### PR DESCRIPTION
**Pull request by Iamgoofball**
come on

its either this or remove the SCP and the syringe gun on odysseus

### CODE REVIEW

**Comment by AlexTheSysop42** [comment]
make it just the dangerous ones so you can still golemify yourself

**Comment by ma44** [comment]
The only real problematic mutation toxin is the slime one, at least all the other ones still allow you to play the game but now with some disadvantages/advantages (if that even exists)

**Comment by AlexTheSysop42** [comment]
nah, plasmaman is really bad too, it makes you basically uncloneable and usually instakills you as well

**Comment by Shadowflame909** [comment]
So just make oil slime mutations un spammable? Those are the dangerous ones.

**Comment by Iamgoofball** [comment]
These are those

**Comment by 81Denton** [comment]
Wouldn't something like if(method != TOUCH) and/or VAPOR solve the issue of smoke spam without completely removing them from the coffee machine?

**Comment by Iamgoofball** [comment]
no

you don't get to have free mutation toxin

i'm sorry but thats the way its gonna be

**Comment by Shadowflame909** [comment]
Remove mutation toxin gas all together? Do not merge this. Ruins the slime oil gas grenade gimmick. Which is encourage d as a tator on the wiki. No more I'm ded prs!

**Comment by Iamgoofball** [comment]
@Shadowflame909 you can still get it from slimes

**Comment by AlexTheSysop42** [comment]
No you cant

**Comment by KorPhaeron** [comment]
How do you even mutate into a robot anyway

**Comment by Shadowflame909** [comment]
Clockwork golem. Honk

**Comment by AlexTheSysop42** [comment]
>How do you even mutate into a robot anyway

Android mutation toxin

>these are those

No, oil just makes a boom. You're thinking of pre-rework green/black

**Comment by Iamgoofball** [comment]
Why???

**Comment by Iamgoofball** [comment]
@KorPhaeron can you reopen this

**Pull request closed without merging**
