### PR TITLE
Quieter title music is now played when the round ends

### PR DESCRIPTION
**Pull request by Cyberboss**
Why: Fun way to relax after the round ends

### CODE REVIEW

**Comment by Qustinnus** [comment]
kevinz please dont shoot up a school

**Comment by Shadowlight213** [comment]
Is this going to mess with the round end sounds?

**Comment by Cyberboss** [comment]
Nope

**Comment by optimumtact** [comment]
needs a pref like the lobby sound probably, or just piggyback on the lobby sound pref

**Comment by Cyberboss** [comment]
@optimumtact that proc already handles it

**Comment by optimumtact** [comment]
hah derp

**Pull request merged**
