### PR TITLE
[Delta] Fixes Bad Placement Of Virology Walls And Buttons

### LINKED ISSUE #23910: [Delta] Virology's entrance hall is blocked by a wall and lacking a second access button
Presumably caused by #23780, not too sure. Only noticed it this morning!

[Pictures probably help more than my bad explanations could.](http://image.prntscr.com/image/99e0fcfcfced4b8aa2387ce97e53390d.png)

### PR DESCRIPTION
**Pull request by JohnTheDonut**
## **Fixes Bad Placement Of Virology Walls And Buttons On Deltastation**
More then likely a the map merge tool did not properly merge the maps and this more then likely occurred when i added access buttons onto the Virology doors on Deltastation. This pull request should fix the weird placement of the walls and windows in the small hallway leading to virology.

## **Changelog**
:cl: Tofa01
fix: [Delta] Fixes virology doors and walls being incorrectly placed due to mapmerge issues.
/:cl:

## **Fixes #23910**

Do not merge if this is still here.

### CODE REVIEW

**Comment by Tofa01** [comment]
Ok...

**Comment by PKPenguin321** [comment]
bap?

**Comment by Tofa01** [comment]
Bap? Whats that mean?

**Comment by Tofa01** [comment]
Fixed PR Name, whoops.

**Comment by Tofa01** [comment]
Got it, for some reason there was a step_ in there instead of a pixel_

**Comment by Tofa01** [comment]
This is being weird, i think i have screwed up my branch will re open later.

**Pull request closed without merging**
