### PR TITLE
Changes code to single image of an Orange because why the fuck do we 

### PR DESCRIPTION
**Pull request by PepegaSandwich**
…have to wait for some idiots to remove things one by one?

Deletes a game, cause, apparently, its getting deleted anyway.
People are being let to do removals for no reason, despite the majority of other people being against all of this BS.
Why postpone this brain-damaged idiocracy?

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
The ultimate /tg/ PR.

**Comment by Mothblocks** [comment]
yes yes very funny person number 700 to make this pr

**Comment by DeadliestDesire** [comment]
> yes yes very funny person number 700 to make this pr

And you don't see this as an Issue?

**Comment by DeadliestDesire** [comment]
> They're a burgerstation player do'nt be mean
What in the 9 hells does it have to do with your policy of utter idiocracy?

**Comment by DeadliestDesire** [comment]
> They're a burgerstation player do'nt be mean

I think you must be ashamed to be a TG guy honestly at this point, cause, you know, Skyrat is more TG than TG you guys made.

**Comment by KittyNoodle** [comment]
Merge this ASAP to fuck with downstreams

**Comment by EricZilla** [comment]
> > They're a burgerstation player do'nt be mean
> 
> I think you must be ashamed to be a TG guy honestly at this point, cause, you know, Skyrat is more TG than TG you guys made.

lmao so salty you had to post twice

**Comment by optimumtact** [comment]
good idea

**Comment by CRITAWAKETS** [comment]
dude you're a complete and utter idiot

why didnt you make it just a link to a picture of an orange on an image hosting site

less bloat, and now its Games As A Service, which is the best modern trend of all time

its genius i tell you, genius

**Review by SuperNovaa41 — COMMENTED** [review]
LGTM

**Pull request closed without merging**
