### PR TITLE
Security Uniform Resprites

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Resprites a good chunk of Security uniforms, mostly the HoS'.

image

<details>
<summary>Warden Resprite</summary>

image

image

</details>

<details>
<summary>HoS Red Uniform Resprite (Now with 100% less piss gold.)</summary>

image

image

</details>

<details>
<summary>HoS Turtleneck Resprite (Now with 100% less ab-fitting ((why)), and 100% more tactical pants.)</summary>

image

image

</details>

<details>
<summary>Formal Uniform Resprite (All of them got re-done, not just the HoS, but I'm not screenshotting all of them.)</summary>

image

</details>

## Why It's Good For The Game

Things looking good is good, right?

## Changelog

:cl:
imageadd: New sprites for HoS Jumpsuit/Jumpskirt, and Turtleneck/Skirtleneck
imageadd: New sprites for Warden Jumpsuit/Jumpskirt
imageadd: New sprites for Sec's formal uniforms
/:cl:

### CODE REVIEW

**Comment by coldud13** [comment]
image

**Comment by CRITAWAKETS** [comment]
bro why does the warden's skirt have so much breast armor

**Comment by axietheaxolotl** [comment]
> bro why does the warden's skirt have so much breast armor

it's funny that's why

**Comment by iwishforducks** [comment]
nerfed hos' abs but buffed warden's boobs...

yeah okay......

**Comment by DrDiasyl** [comment]
> nerfed hos' abs but buffed warden's boobs...
> 
> yeah okay......

simp

**Comment by VladinXXV** [comment]
Booo, boo I say. The abs-fitting is the best part. And bulky pants bad. He's the HOS, not the clown.

**Comment by axietheaxolotl** [comment]
> The abs-fitting is the best part.

Stopped listening at that part.

**Comment by Serxule** [comment]
can you post an image of just the sprites on a human dummy or something? your hair and ears are in the way

**Comment by axietheaxolotl** [comment]
> can you post an image of just the sprites on a human dummy or something? your hair and ears are in the way

literally just click the collapsible bro

**Comment by SomeDongus** [comment]
>Pink Hair
>Felinid
>Sec

**Comment by axietheaxolotl** [comment]
y'all people really start sneeding over a singular pixel, zamn.

**Comment by optimumtact** [comment]
@Twaticus

**Review by Twaticus — CHANGES_REQUESTED** [review]
hosalt, right - hand space should be the uniform instead of a glove texture

hosalt, left - hand space empty

officerblue, officertan, wardenblue, wardentan, hosblue, hostan, right and left - hand space empty

hosalt_d, officerblue_d, officertan_d, wardenblue_d, wardentan_d, hosblue_d, hostan_d, right and left - same as previous, minus the cutout for the rolled sleeve

rwarden_skirt, rhos_skirt, hosalt_skirt, right and left - hand space should be the uniform instead of a glove texture

rwarden_skirt_d, rhos_skirt_d, every directional - missing skirt frill

hosalt_skirt_d, right and left - hand space should be the uniform instead of a glove texture

**Comment by optimumtact** [comment]
any offtopic here is getting sent to the gulag

**Comment by Serxule** [comment]
my only thought is, why are you making skirts give a literal hourglass body shape? that seems _really_ weird, especially with removing the abs.

**Comment by EricZilla** [comment]
Everything looks nice, I still dont like force boob on the clothing same as I didnt with HOP but thats personal preference.
As for the abs, did you not consider that most of the people who used the turtle neck would like that part? With most of these they are clear improvements but don't take away the hos' tactical abs

**Comment by DrDiasyl** [comment]
I agree with previous commentators, I don't like those huge boobs warden jumpskirts get. As with that discussion in Discord, maybe we should remove all boobs from all jumpskirts or make for all clothing a variant with them. Sprites look good anyway, although bulky pants on HOS turtleneck 😔

**Comment by Victor239** [comment]
Much better shading, I like. Whilst you're at it could you port these other security uniforms [from here](https://github.com/BeeStation/BeeStation-Hornet/pull/487), they've got much better versions of especially the red security officer jumpsuit, helmet and detective uniform.

**Review by Twaticus — CHANGES_REQUESTED** [review]
forgot one thing sorry
hosalt_skirt, font and back - sleeves were accidently extended and cover the hands a bit

**Comment by Sylphet** [comment]
Okay. New sprites are nice, but... why is it that some of the jumpskirts have ✨ _enhanced_ ✨  boobs while others have none at all ??

**Comment by axietheaxolotl** [comment]
>  As for the abs, did you not consider that most of the people who used the turtle neck would like that part? With most of these they are clear improvements but don't take away the hos' tactical abs

Okay, here's the reason the HoS' abs have to go. A. They look bad, this is the main reason. They're poorly done, look bad, and are just overall silly. B. It makes no sense anatomy wise, I'm not gonna post pictures of shirtless buff men here, but generally, abs go inwards. So something has to be very wrong with your anatomy if they're sticking out. That or you have a very poorly fitting shirt.

I won't be readding the abs, because most spriters I've talked to have been in-agreement, that built in abs are dumb. And unlike built in booba, which can A. Look good, and B. Has a place anatomy wise. Just generally doesn't fit. So I won't be readding ab shading, it's dumb.

**Comment by axietheaxolotl** [comment]
> my only thought is, why are you making skirts give a literal hourglass body shape?

It's funny, generally. People seem to think that I'm giving them massive boobs, but I'm not, in reality, it's a couple of darker shades, and one pixel sticking out from the side. It's not that much. Also generally, it looks good. SS13 has a generally cartoony design, and that's good. Having booba on uniforms is okay, I think. Eventually, we'll work out a system to put booba on things that aren't just built into the sprite, but for now. I don't have a problem with it, and spritetainers don't either. And as I like it, I'll be keeping it.

**Comment by axietheaxolotl** [comment]
> hosalt_skirt_d, right and left - hand space should be the uniform instead of a glove texture

hand spaces my be-loathed.... I'll get these done in a bit, and update the PR accordingly.

**Comment by itseasytosee** [comment]
>Eventually, we'll work out a system to put booba on things that aren't just built into the sprite

Uh oh bringing back fat code

**Comment by ExcessiveUseOfCobblestone** [comment]
is there not a concern that a masculine individual who wants to wear the jumpskirt will suddenly have breast augmentation?

**Comment by VladinXXV** [comment]
>Eventually, we'll work out a system to put booba on things that aren't just built into the sprite

This is already a thing, is the issue. So your added boob is entirely unnecessary, and only gets in the way of people who want to wear the skirt as a kilt. (like eoc said before me)
image
image

**Comment by DrDiasyl** [comment]
> >Eventually, we'll work out a system to put booba on things that aren't just built into the sprite
> 
> This is already a thing, is the issue. So your added boob is entirely unnecessary, and only gets in the way of people who want to wear the skirt as a kilt. (like eoc said before me)
> image
> image
> 

I guess we just should later make a PR which will fully delete all of the booba.

**Comment by Iamgoofball** [comment]
remove the bazongas and quit over-sexualizing spacemen on a server with children

**Comment by optimumtact** [comment]
Please stop talking about the boob pixels on the skirts, if a coder wants to add some kind of overlay support for it then they can, but otherwise it's a minor issue not worth complaining about and will not hold up the PR, please return to focusing on the quality of the sprites.

**Comment by DrDiasyl** [comment]
> Please stop talking about the boob pixels on the skirts, if a coder wants to add some kind of overlay support for it then they can, but otherwise it's a minor issue not worth complaining about and will not hold up the PR, please return to focusing on the quality of the sprites.

True

**Review by Twaticus — CHANGES_REQUESTED** [review]
lookin good, just a couple missed in the cleanup
hosalt_d, right and left - hands spaces 
wardentanclothes_d, right and left - hands spaces

**Comment by SinfulBliss** [comment]
The default HoS jumpsuit no longer has a corresponding sleeveless (adjust jumpsuit) version like it used to. It just rolls it all down like normal jumpsuits.

Pls fix

**Comment by Twaticus** [comment]
intended

**Pull request merged**
