### PR TITLE
The librarian backroom is cult neutral

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: The Librarian sometimes has a large brass spire in his
"Private Reading Room", rather than a dark and mysterious set of
archives.
/:cl:

- Librarian backroom can sometimes have a tinkerer's cache rather than a
cult archives. Because libraries support all kinds of book clubs.

### ARCHIVES MODE
image

### CACHE MODE
image

### CODE REVIEW

**Comment by jughu** [comment]
pics

**Comment by ChangelingRain** [comment]
Please do not give clockcult a free cache

**Comment by francinum** [comment]
Make it an obelisk if anything.

**Comment by coiax** [comment]
The problem with making it a random spawn chance, is that it doesn't happen all the time. I've rolled archives these last two rounds.

**Comment by Xhuis** [comment]
I still say you should use a fluff object that's identical to a tome in all but functionality. It's done with HoG objects. That might just be creator bias though.

**Comment by francinum** [comment]
At Least an obelisk isn't a free first level in scripture, the archives aren't nearly as useful.

**Comment by coiax** [comment]
Pictures have been provided.

**Comment by francinum** [comment]
Move the codex to the table. looks weird on the cache.

**Comment by KorPhaeron** [comment]
Cult stuff being in the backroom of the library makes sense because blood cult of, you know, books

The clock cult stuff is thematically nonsense for the librarian, and is only being proposed to "mirror" the blood cult. It's degrees removed instead of actually related.

**Comment by francinum** [comment]
Hell, if anything, it'd make more sense to give it to the chaplain.

**Comment by KorPhaeron** [comment]
Add a watchmaker job and you have to go to him to find out the station time and then he can have a clock cult cache as a "metabreaker" or whatever

**Comment by ShadowDeath6** [comment]
watchmaker job please

**Comment by Xhuis** [comment]
Remove the station time clock from PDAs and make it the watchmaker's job to modify PDAs to have it.
Can someone get a design doc going for this?

**Comment by jughu** [comment]
@korphaeron in that sense revert the computer printing out clock caches :^)

**Comment by jughu** [comment]
@francinum archieves can make lesser supply talismans 3 minute shuttle extenders i dont see how that isnt the most usefull thing

**Pull request closed without merging**
