### PR TITLE
Adds a new poster in the form of a movie poster: THE BLOOD GEOMETER

### PR DESCRIPTION
**Pull request by Pumpkinoe**
## About The Pull Request
This PR adds a new poster in the form of the Blood Geometer poster. This advertises a movie regaling the story of Ace Ironlungs, a fictional hardboiled detective who comes face to face with a dangerous bloodcult. Thrilling stuff! Examine it a little closer to inspect all that small print about who made it or stars in it. 

Sprite made by MetalClone - thank you so much for making it! I wrote the description for it.
Original inspiration poster art by Spessmenart 

image

## Why It's Good For The Game
Expands a teeny bit on the idea of having prior knowledge of the blood-cult in a fun way by having it be an in-universe movie. "I've seen these guys before! In the movie!"
Also, more poster variance is fun! Gives Tea over Tizira a proper movie-poster buddy. 

## Changelog
:cl:
add: A new movie's been making waves, and a poster about it has been seen once or twice aboard the station. Why's she called the Blood Geometer, anyways?
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
VERY cool!

**Comment by Pumpkinoe** [comment]
image
Here's the original inspiration if anyone's curious. Metalclone did a great job turning it into tiny little pixels!

**Comment by Kapu1178** [comment]
The artist is SpessmanArt.

**Comment by Pumpkinoe** [comment]
Yes :) Of the original art, made sure to mention that in the original post

**Comment by timothymtorres** [comment]
Can you add a picture of the pixel sprite to the OP

**Comment by Pumpkinoe** [comment]
Sure! Done now.

**Pull request merged**
