### PR TITLE
Fixes coin values

### PR DESCRIPTION
**Pull request by Momo8289**
## About The Pull Request

This brings coins values back from being severely undervalued after #75437. Coins are supposed to be made of and worth 400 units of mats, but the numbers weren't updated and so they were made of significantly less than that.

## Why It's Good For The Game

Brings coins back to what they're supposed to be worth.
## Changelog
:cl:
fix: After destroying unfathomable quantities of excess coins, their value is back to what it's supposed to be!
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
@ArcaneMusic Do you prefer the material values on these increase again, or the equation that calculates value per unit be changed?

**Comment by Momo8289** [comment]
Fixes #76052

**Comment by ArcaneMusic** [comment]
> @ArcaneMusic Do you prefer the material values on these increase again, or the equation that calculates value per unit be changed?

Yeah, the former, since the "density" of coins would have gone up, it stands to reason that the mineral's value_per_unit would increase instead. So, mineral quantity per coin can stay the same, but value increases.

**Comment by Momo8289** [comment]
> So, mineral quantity per coin can stay the same, but value increases.

Wait so do you want me to up the values of the coins?

**Review by ArcaneMusic — CHANGES_REQUESTED** [review]
Mulled it over, here's how I'd prefer this changed instead:
* Keep the coin material amount define so that it's equal to it's original proportion (Halfsheet * .4)
* Then change the `value_per_unit` so that it's equivalent to what it was before. For example, gold coins are supposed to be worth 25 credits (value_per_unit = 0.0625* 400 old units of material = 25 credits, so 25 / 20 = value_per_unit of **1.25**).

There might be an idea rolling around about changing the amount of materials in coins later, but for now lets keep the scope of this PR fixing the issue.

**Comment by Momo8289** [comment]
> * Keep the coin material amount define so that it's equal to it's original proportion (Halfsheet * .4)
> * Then change the `value_per_unit` so that it's equivalent to what it was before. For example, gold coins are supposed to be worth 25 credits (value_per_unit = 0.0625* 400 old units of material = 25 credits, so 25 / 20 = value_per_unit of **1.25**).

Will do. Should I adjust the `value_per_unit` of non-coinable materials too?

**Review by ArcaneMusic — APPROVED** [review]
Looks good. 👍

**Comment by Helg2** [comment]
image

**Pull request merged**
