### PR TITLE
Smoking DLC - Bad Lungs Pack

### LINKED ISSUE #61124: Cigars do not satiate nicotine cravings
## Round ID:
[168751](https://scrubby.melonmesa.com/round/168751), tested in thunderdome but is round independent.

## Reproduction:

Smoking a cigar for an extended amount of time will cause you to crave nicotine at such a rate that the cigar itself will not satiate it, leading to withdrawal symptoms.

This happens even in the span of a singular cigar, before it has completed being smoked.

Step 1. Obtain Cigar
Step 2. Light
Step 3. Place into mouth
Step 4. Wait

Eventually withdrawls will kick in and you'll begin shaking and craving nicotine despite actively smoking.

Probably beyond the scope of this issue, but cigars also shouldn't *technically* cause lung damage as you do not inhale the smoke into your lungs.

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This fixes #61124.  Havana cigars will not run out of nicotine while you are smoking them since I increased the nicotine amount.  As a result I also needed to boost the `chem_volume` higher so there is still room to inject other chems.

The smoker quirk has some new side effects for the players lungs.  Whoever takes the quirk suffers a 25% penalty towards their lungs max health and healing rate.  They also gain a 50% resistance when taking lung damage from smoking.

Lung damage has been modified for the following cigarette brands: (before all cigarettes did `1 lung damage`)

- Syndicate = `1.5`
- Shady Jims = `1.5`
- Xeno = `2`
- Little Timmy's Candy = `0.5`

## Why It's Good For The Game

Realism for smoking.  Smokers have bad lungs and these changes reflect this but also gives them a stronger tolerance against lung damage while smoking.  I also thought the more exotic and lethal brands of cigarettes should cause different amount lung damage compared to normal cigs.

## Changelog

:cl:
expansion: The smoker quirk has new side effects that cause a person's lungs to have 25% less max health and healing.  They also gain a 50% resistance from lung damage caused from smoking. 
expansion: Exotic cigarette brands now deal different amounts of lung damage. This applies to syndicate, shady jim's, xeno, and Little Timmy's Candy brands.  
fix: Fixed Havana cigars running out of nicotine. As a result of increasing the starting nicotine amount, the total `chem_volume` was increased to allow room for other chems to still be injected.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
let it be known that putting "realism" (fake justification) as the first word in your why section but also giving smokers innate resistance to lung damage has got me mildly miffed. also additionally miffed that you bundled a fix with content expansion for the quirk

**Comment by timothymtorres** [comment]
> let it be known that putting "realism" (fake justification) as the first word in your why section 

Eh, realism is fine.  Granted this is a sci-fi game with a lot of meme shenanigans, but there is a lot of content here that aims to replicate real life.  A nice mix of fantasy and realism is ideal. 

> but also giving smokers innate resistance to lung damage has got me mildly miffed

Except that this is how poisons work.  A person can develop tolerance over time that makes them partially immune. 

> also additionally miffed that you bundled a fix with content expansion for the quirk

The fix is relevant to smoking.  This PR affects smoking which also happened to include the quirk changes.

> (the different damage per cig type changes make sense though and are cool)

Glad to hear it.

**Comment by Time-Green** [comment]
Will this still just kill me in half an hour?

**Comment by tralezab** [comment]
the world's most eyeball emoji-able post?!

**Comment by Dorsisdwarf** [comment]
> > but also giving smokers innate resistance to lung damage has got me mildly miffed
> 
> Except that this is how poisons work. A person can develop tolerance over time that makes them partially immune.

1) This is how *some* poisons work. Most poisons either have no real resistance gain or just additively poison you more and more
2) Lung damage from smoking is not just a poison, it's major (and additive) physical damage above and beyond the natural healing ability of the lungs that leads to ongoing complications, and largely goes away if you stop it

That said, it's a nice bonus to the smoker trait so that they arent hacking out their lungs within 30 minutes just to not go insane.

**Comment by Farquaar** [comment]
The health/healing penalty is a notable balance change. Will the quirk point value be adjusted to account for this?

**Comment by tralezab** [comment]
> The health/healing penalty is a notable balance change. Will the quirk point value be adjusted to account for this?

no lawl

**Comment by Coastfront** [comment]
Aside from my own personal hatred of adding detrimental content in the name of realism (I personally just dont see how this type of realism adds to the game in terms of "fun") I feel like if we're gonna give the smoker trait the penalty of "you have half your lung hp get fucked" it should give the user more points.

**Comment by timothymtorres** [comment]
> Aside from my own personal hatred of adding detrimental content in the name of realism (I personally just dont see how this type of realism adds to the game in terms of "fun") I feel like if we're gonna give the smoker trait the penalty of "you have 1/4 of your lung hp gone get fucked" it should give more points
> 
> 
> 
> Edited a mistake i made while typing

Did you miss the part where I halved the damage they receive from smoking?  Overall they suffer _less_ lung damage the longer the round goes on but to offset this they have weaker lungs.  Make sense?

**Comment by Coastfront** [comment]
> > Aside from my own personal hatred of adding detrimental content in the name of realism (I personally just dont see how this type of realism adds to the game in terms of "fun") I feel like if we're gonna give the smoker trait the penalty of "you have 1/4 of your lung hp gone get fucked" it should give more points
> > Edited a mistake i made while typing
> 
> Did you miss the part where I halved the damage they receive from smoking? Overall they suffer _less_ lung damage the longer the round goes on but to offset this they have weaker lungs. Make sense?

There are also other scources of lung damage in the game, Such as certain powerful atmos gasses having lung damage as their tradeoff, and certain medicine overdoses dealing lung damage/just dealing lung damage non od. Smoker trait would permanantly make someone weaker to said things.

**Pull request merged**
