### PR TITLE
Fix syndicate toy C20r and L6 Saw not having riot darts 

### LINKED ISSUE #30614: Nuclear Operative toy C20rs and L6 saws no longer start with riot darts
#30531 

How to reproduce
1. Buy either a toy submachine gun or a toy machine gun from the nuclear operative uplink
2. Shoot it and realize there's only blue darts coming out. 

Sure you can spend 2 tc on 20 riot darts, but that's a pretty heavy nerf to the LMG.

### PR DESCRIPTION
**Pull request by msgerbs**
:cl: VexingRaven
fix: The syndicate have once again stocked the toy C20r and L6 Saw with riot darts.
/:cl:

Fixes #30614.

Partially reverts #30531.

The toy C20r and L6 saw were changed unnecessarily. Although toy riot versions were added, they were unnecessary because the C20r and L6 saw already had a syndicate firing pin and riot darts. A gun with a syndicate firing pin and toy darts makes no sense (plus those guns are used in a few other places I can't be bothered to change). Instead I added a variant of the unrestricted one with riot darts.

Everything previously used /obj/item/gun/ballistic/automatic/l6_saw/toy/ still uses /obj/item/gun/ballistic/automatic/l6_saw/toy/. This is a gun with a syndicate firing pin which it inherits from /obj/item/gun/ballistic/automatic/l6_saw.

Everything that previously used /obj/item/gun/ballistic/automatic/l6_saw/toy/unrestricted now uses /obj/item/gun/ballistic/automatic/l6_saw/toy/unrestricted/riot (except the toy donksoft vendor).

I know it doesn't make the most sense but it's the least disruptive way I could find to fix this without having a billion variants with different combinations of firing pin and magazine (half of which wouldn't be used) and changing every other reference to the base toy variants.

### CODE REVIEW

**Comment by msgerbs** [comment]
Ok I think I got the map edit right this time.

**Comment by Kerbin-Fiber** [comment]
Huh, when I made the vendor the Donksoft station vendor had no darts and the Syndibase one did

**weird**

**Comment by msgerbs** [comment]
The dart boxes in the vendor are fine. It's the base "toy C20r" and "toy L6 Saw" which either need riot darts, or everything using it needs to be refactored to use a syndicate variant. I chose what seemed like the easiest route.

**Comment by optimumtact** [comment]
they were changed because people wanted the l6 saw and c20r with unrestricted pins but non riot ammo, I guess these map paths were missed.

**Comment by msgerbs** [comment]
I agree, ideally all of the toy guns would have a base type which has toy darts and a standard firing pin, with a riot and syndicate subtype. But if I'm tackling that insanity for these 2 guns I'm going to do it for all of them for consistency sake (why didn't we do this from the start? Who knows...). For now this achieves the needed goal, the paths are just a little illogical (hence the comments).

**Comment by ma44** [comment]
You can still put riot darts in toy guns anyway, so the change wouldn't had worked that great anyway.

**Comment by msgerbs** [comment]
Just to be clear, the toy donksoft vendor still has guns with toy darts. I didn't change that. This only effects the syndicate toy guns with syndicate firing pins.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
