### PR TITLE
Fixes various skill bugs.

### LINKED ISSUE #47264: Energy bows and proto-kinetic accelerators recharge instantly
Normally they shoot, recharge, and can be fired again when recharged. Now that they recharge near instantly they become semi automatic with no ammo to worry about. Dear god

Issue reported from  Round ID: 121879 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Fixes https://github.com/tgstation/tgstation/issues/47264

## Changelog
:cl:
fix: Having no skill whatsoever in a thing now returns the worst possible skill modifier. Basically... PKAs now have a cooldown again.
fix: Starting to earn XP towards the first level of a skill no longer tell you that you got better at the skill since you factually didn't.
spellcheck: Fixes formatting when viewing skills.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
In addition, the undocumented balance change to mythril from the PR needs to get reverted, and the ebow needs to have the old recharge time formula instead of it being the same as the PKA.

**Comment by nemvar** [comment]
Mythril change wasn't actually undocumented just not atomized. Since it got merged anyways, there isn't actually a code argument for reverting it just a balance one.

Changing the formula for ebows is out of scope. WYCI?

**Comment by Qustinnus** [comment]
lol i literaly added mythril material why are you complaining about balance changes to an admin item (and very, very rarely, and only because i added it, a player item)

**Comment by Fikou** [comment]
> lol i literaly added mythril material why are you complaining about balance changes to an admin item (and very, very rarely, and only because i added it, a player item)

i added mythril material

**Comment by Qustinnus** [comment]
oh shit youre right >:^) i added mat datums though so checkmate atheist

**Comment by actioninja** [comment]
fastest speedmerge in the west

**Comment by Tharcoonvagh** [comment]
So can miners still use the ebow as an SMG?

**Pull request merged**
