### PR TITLE
Monthly lavaland removal

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Ghost roles and terrain generation both need to be heavily reworked.  The proposed solution is highly controversial so probably not going to happen. I will have more time and energy to think about this without a daily chorus of balance memes. I feel like I have been bogged down in such arguments for a while now instead of really going anywhere with it.

I doubt this will get merged but may as well try

### CODE REVIEW

**Comment by coiax** [comment]
actually, you know what, let's hear Kor out on this one, provided we set a time limit. We remove lavaland for one month while he takes care of his sick grandma's cats or whatever, and then it comes back.

**Comment by KorPhaeron** [comment]
That tag hurts

**Comment by xxalpha** [comment]
These tags are all appropriately warm colored.

**Comment by InsaneHyena** [comment]
> Kor giving it to whiners who got dunked by ash liggers and got buttmad

Kor, pls no

**Comment by Xhuis** [comment]
If the _creator_ of lavaland is concerned with the direction it's going, let him do what he wants with it.

**Comment by optimumtact** [comment]
You don't need to listen to the feedback personally, it belongs to all of us now, you can safely walk away from lavaland if you wish.

**Comment by optimumtact** [comment]
Frankly I'm having a hard time understanding how you think a removal will help either

**Comment by coiax** [comment]
Maybe we should trust the design lead on this

**Comment by xxalpha** [comment]
""""design"""" lead

**Comment by optimumtact** [comment]
Removing lavaland literally solves nothing, I understand Kor might be feeling stressed, but they should take some time off instead.

**Comment by TechnoAlchemisto** [comment]
Lavaland may have problems but the asteroid is boring and sucks. IMPROVE DON'T REMOVE AM I RIGHT GAMERS

**Comment by Kromgar** [comment]
Seriously i dont want to go back to Asteroid.

Lavaland is infinitely more fun. Even though i die way more often

**Comment by Aloraydrel** [comment]
Id take lavaland over boring asteroid

**Comment by Saegrimr** [comment]
I wouldn't mind seeing the roid back for a short time just to remind everyone of how much fun we could have been having in lava.

**Comment by Cebasiz** [comment]
nah, lavaland was a net benefit to the game.

>i got dunked by spearliggers!!!! ;_;

isn't enough to remove such a body of work.

**Comment by X-TheDark** [comment]
For the most part, I think people just want to keep it in because they have something to do as ghosts (spawn and murderbone others). Everybody loves free antag.

**Comment by swankcookie** [comment]
The gulag needs to be reworked. that is all.

**Comment by YakumoChen** [comment]
I'd like to see the ghost roles reworked.

**Comment by Xhuis** [comment]
People need to understand: this is the design lead. @KorPhaeron is the person we specifically nominated for deciding and implementing ways of making the game fun by adding new content that he deemed would extend longevity and make the server better as a whole.

If the person _we_ chose to make the game more fun is saying that he doesn't think something will be fun, we should probably humor him on this.

**Comment by KorPhaeron** [comment]
Give me back my meme tags

**Comment by optimumtact** [comment]
They're really bright, I'll give you some muted ones instead

**Comment by KorPhaeron** [comment]
Thanks

@Xhuis 

I can't be right all the time though, maintainers gotta keep me in check

**Comment by coiax** [comment]
My :+1: is not because I dislike lavaland currently; it's putting faith in Kor to think things through.

And yes, some asteroid would teach the crew what they're missing out on.

**Comment by KorPhaeron** [comment]
I dont think the people who dislike lavaland would actually miss out on anything, since they tend to avoid going there anyway and mostly get upset when it spills onto the station

**Comment by coiax** [comment]
I think this is one of the instances where the """design lead""" should actually be trusted, given Kor is basically maintainer of lavaland. Others have made large contributions, but Kor's still the person at the top of the pyramid/ladder

**Comment by TechnoAlchemisto** [comment]
this is one of those instances where we should intervene because kor is a god damn fool and cannot be trusted

**Comment by optimumtact** [comment]
Plus this doesn't resolve any of the issues at stake and is a complete step backwards for the server, so why would any of the maintainers merge it?

**Comment by Repukan** [comment]
Don't remove lavaland.

Or add ash drakes to the asteroid and I'm fine honestly. This server has the best mining experience I've the pleasure of playing because of how much conflict and variety you can find. You never know if you will find peaceful golems or war mongering mandingo lizards. The newest monsters are tough as fuck but even dying to them is fun.

**Comment by Bawhoppen** [comment]
I have yet to hear an actual argument why kor wants to remove lavaland

**Comment by callanrocks** [comment]
Remove ash walkers and whatever other free antag thing was added and it won't be too bad.

The biggest problem with it right now is that miners are dead most rounds and then murder lizards show up and start slaughting the crew, gibbing bodies and having unlimited attempts to do so.

**Comment by AlexCrimson** [comment]
No need to remove Lavaland. Its a really cool feature and gives Miners plenty to do. If Ash Walkers are really a problem, just disable them until you feel you can rework them into something more acceptable. Lavaland as a whole isnt the problem, right?

Out of curiosity, would it be possible to randomise the Mining map type like the station rotation thing? So it switches between Asteroid/Lavaland/Some other future map?

**Comment by Eaglendia** [comment]
how do you even get killed by an ashwalker

**Comment by callanrocks** [comment]
Spears outrange KA and can be spammed faster. Not to mention unlimited retries.

**Comment by Kromgar** [comment]
Asteroid is utter shit unless tendrils and other boss mobs get added to it then its decent.

**Comment by optimumtact** [comment]
I'd prefer #18770 to this and I'm not even sold on that

**Comment by coiax** [comment]
I think you've overreached by closing this. I'm a big fan of lavaland, and the asteroid is lame, but I think giving Kor space to plan out and design, rather than being drawn into every minor balance change is a good idea.

We're not removing the road, we're closing it for maintenance.
d.

**Pull request closed without merging**
