### PR TITLE
Updates the Rapier sprites

### PR DESCRIPTION
**Pull request by Lexorion**
Adds proper shading,makes the rapier prettier. Pic below shows the changes!
rapier old slash new

### CODE REVIEW

**Comment by evsey9** [comment]
yes

**Comment by evsey9** [comment]
man it looks so good and shiny

**Comment by Cheridan** [comment]
it looks worse. the outline's too bold, it's like a runescape icon or something.

**Comment by WJohn** [comment]
:+1: Big improvement.

**Comment by Thunder12345** [comment]
I think Cheri is right about the outline not really fitting, but the shading is way nicer so huge improvement overall

**Comment by TechnoAlchemisto** [comment]
black outlines look good

**Comment by WJohn** [comment]
The champion belt and crowns all use outlines and the same color palette, and those look nice.

**Comment by Supermichael777** [comment]
tbh wee need a straight yes or no on outlines.
some stulf with almost invisible sprites could use it, but it looks terible next to unoutlined sprites

**Comment by Cheridan** [comment]
The problem is just that the outline is black. Most sprites in the game don't use straight black, they use a darker shade of the color.

**Comment by Lexorion** [comment]
The outline isn't black,it's dark red (R51B0G0)

**Comment by ChangelingRain** [comment]
The dark red contrasts with the gold and makes it look like the outline is brown.
~~this comment is redundant because I've already told lexorion this~~

**Comment by Lexorion** [comment]
Edited the border a bit,updated the image in the op

**Pull request merged**
