### PR TITLE
Return of the Bagulo

### PR DESCRIPTION
**Pull request by SkeletalElite**
## About The Pull Request
BOH Bombing creates a singularity again

## Why It's Good For The Game
BOH Bombing was reduced to what it is today because of how easy it was to print 2 bags and end the round. Now that BOHs are very rare due to requiring anomaly cores and require more effort to acquire they should be  more powerful as it is something that only antags can do (unless it ends the round) and is guaranteed death for the antag.

This was PRd after BOHs were nerfed to require anomaly cores but was closed because it was too soon after the change. It's been a while since the change and @jared-fogle showed support for the change on the forums so I'm redoing the PR.

I hope I didn't fuck this up horribly

## Changelog
:cl:
add: BOH Bombs now create singularities again
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by Pugie** [comment]
They aren't that rare.  You can buy the bluespace cores from cargo, you can get two bluespace cores shift start in science.
Singularity was removed from cargo was it not? Isn't this more or less the same thing, toxins isnt exactly hard to do.

**Comment by SkeletalElite** [comment]
> They aren't that rare. You can buy the bluespace cores from cargo, you can get two bluespace cores shift start in science.
> Singularity was removed from cargo was it not? Isn't this more or less the same thing, toxins isnt exactly hard to do.

The difference is the cargo one can be made without killing yourself

**Comment by Pugie** [comment]
> > They aren't that rare. You can buy the bluespace cores from cargo, you can get two bluespace cores shift start in science.
> > Singularity was removed from cargo was it not? Isn't this more or less the same thing, toxins isnt exactly hard to do.
> 
> The difference is the cargo one can be made without killing yourself
> It's also rare enough that I haven't seen a BOH bomb used since the change. I rarely even see people make 1 BOH, much less 2.

expect that to change if you pr this :)

**Comment by MrMelbert** [comment]
maybe prevent the experimentor from being able to dupe BoH before merging this idk

**Comment by brotherbeyondd** [comment]
it only dupes inert BoH and mats arent really the issue

**Comment by D4C-420** [comment]
2 Blue space cores ain't hard to get (space ruins such as Hilbert's hotel are notable here and again cargo) and  its very easy to refine a core even if you don't know toxins (t3 lasers are all it takes along with a heater/cooler). This will just lead to some science man killing the entire station every time 2 bluespace cores pop up.

**Comment by wesoda25** [comment]
Frankly we’ve been spoiling players, there needs to be some more bullshit in this game.

**Comment by Misdoubtful** [comment]
Its really not that hard to get multiple cores or to factory produce inert BOH's. I like my potential round enders to require at least a little bit more telegraphing or effort to make. Maybe I'm outta touch idk. 

I mean it does require some effort I guess, its just not super apparent that someone is putting a bag in bag and making a singulo coupled with there being absolutely nothing you can do to stop them from doing a two second action to make a haha funny round ender. 

Maybe if there was a way to counter/destroy singulos easily (like throwing an explosive in it I wonder where I got this idea from hmm). Or a telegraphed 'struggle' progress bar of putting one in another, but then all you'd have to do is hide.

**Comment by optimumtact** [comment]
this is FAR too destructive to allow, even in the limited form

**Pull request closed without merging**
