### PR TITLE
Bicycle price increase, in line with THE LORE

### PR DESCRIPTION
**Pull request by Haevacht**
THE LORE SAYS ONE MILLION. THIS BRINGS IT IN LINE WITH THAT.

But seriously if that dude complaining is right this shit is a bit too strong to be at anything but absolute meme-tier.

Why: Brings the price inline with the source material again, putting the bike at meme-tier, where it should stay.

### CODE REVIEW

**Comment by Ninja137** [comment]
Tbh it's not even a price issue, it's that it allows you to move faster than adrenals, doesn't require free hands at all, doesn't have anything like the skateboard crash where you slam into shit and get knocked off, and is just all around something that if you can acquire it, you'd be retarded not to. 

As it currently is, you can 2h an Axe or a dual-esword and just hatefuck the station to death while rolling around at a thousand miles an hour on a bike that you can't even see the sprite for half the time.

**Comment by optimumtact** [comment]
goofcode

**Comment by Giacom** [comment]
Can I exchange a voucher for a bike?

**Comment by RandomMarine** [comment]
VOUCHER

Hell, a system for vouchers for cargo in general can be nice. Slap a voucher into the console to order free/discounted shit.

**Comment by jughu** [comment]
@ninja137 LOOK MOM NO HANDS!!!

**Comment by optimumtact** [comment]
This will have to stay expensive until someone fixes how absurdly powerful these are.

**Pull request merged**
