### PR TITLE
improves pda message immersion

### PR DESCRIPTION
**Pull request by Iamgoofball**
someone suggested this

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
can you make Pais send different ones?

**Comment by nicbn** [comment]
TL;DR: meme pr

**Comment by ExcessiveUseOfCobblestone** [comment]
This is just like the stupid brain damage line memes you spammed except when you have your next mental breakdown it's not going to be all consolidated to a single file.

**Comment by JStheguy** [comment]
goofball are you okay
blink once for no
blink twice for fuck no

**Comment by iskyp** [comment]
@evsey9 adds "Sent from my PDA" to the end of every PDA message

**Comment by PKPenguin321** [comment]
To the end of 1 in 100 PDA messages

**Pull request merged**
