### PR TITLE
The NTSS Independence- A Nostalgic Cruise Ship Shuttle

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Adds a new emergency shuttle, the NTSS Independence, ported from the 2019 Summer Ball map:
cruiseshuttlefinal
The original, for comparison:
cruiseshuttle
It costs 50000 credits, and doesn't come with medical facilities or a brig. It does, however, come with bar staff, who will (presumably) be happy to serve up some drinks.
I'm not sure who exactly made this shuttle, given the Summer Ball map was a collaborative effort, so if this is yours please let me know so I can credit you properly in the changelog.

## Why It's Good For The Game
New shuttles are fun, and this one in particular is a good callback to the Summer Ball.

## Changelog
:cl: EOBGames (Inept)
add: Rich captains can now hire out the NTSS Independence, a swanky cruise shuttle, to make their next evacuation cheerier!
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
another bar shuttle?

**Comment by Tlaltecuhtli** [comment]
white + brown + blue colors..... it looks meh

**Comment by Fikou** [comment]
seems like just another bar/luxury shuttle

**Comment by EgorDinamit** [comment]
It must have a brig area for prisoners, or you are encouraging death row for quite about everyone.

**Comment by necromanceranne** [comment]
We have several shuttles that lack a brig. If you execute someone because of a lack of shuttle brig instead of strapping a prisoner into a chair, that's an issue with you and not the shuttle.

**Comment by ATH1909** [comment]
> We have several shuttles that lack a brig. If you execute someone because of a lack of shuttle brig instead of strapping a prisoner into a chair, that's an issue with you and not the shuttle.

Doesn't being on a brig tile on the shuttle at the end of the round make you count as not escaping for the purposes of antag objectives?

**Comment by wesoda25** [comment]
i didnt go to that ball so its not nostalgic so it shouldnt be merged thx

**Comment by EOBGames** [comment]
I mean what anne said is correct, a fair few of our emergency shuttles don't have brigs. In the case of this shuttle I decided against adding one in the spirit of replicating the original as closely as possible.

**Comment by ishitbyabullet** [comment]
Oh hey, I made this

**Pull request merged**
