### PR TITLE
C4 planting takes 3 seconds, down from 5

### PR DESCRIPTION
**Pull request by Robustin**
C4 used to gib people and was one of the only ways to break bolted airlocks without tools or destroy certain machines. C4 throwing weapons were also viable.

Now all of that has changed. It doesn't make sense to keep the application timer so obnoxiously long. 

:cl: Robustin
tweak: c4 planting is now 40% faster
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
I think this is the wrong C4

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/d95e859e5d4e055a95f3246a9c0b7ae1bacb95f7/code/modules/uplink/uplink_item.dm#L974

**Comment by Robustin** [comment]
Thanks for catching that, see my latest commit name for my thoughts on the subject.

**Comment by ExcessiveUseOfCobblestone** [comment]
I want to say it has something to do with assembly setup, instead of adding them to wires you directly add it to the C4 itself.

**Comment by Iamgoofball** [comment]
>c4 code

**Comment by Bawhoppen** [comment]
why not

**Comment by Robustin** [comment]
Of course you merged the path change inspired by this PR before merging the one-line non-controversial fix.

**Comment by Bawhoppen** [comment]
you don't get a reputation by only doing the easy things in life

**Comment by Robustin** [comment]
Yes you do, its called being lazy and that reputation is very near and dear to me.

**Pull request merged**
