### PR TITLE
adds autosurgeon to rnd

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: 
add: autosurgeon can be unlocked with tech webs and printed in medical or sci lathes
/:cl:

### CODE REVIEW

**Comment by Grazyn** [comment]
Why add it to the science lathe? The have no use for it. Either add it to robotics fabricator or leave it to medical only

**Comment by ExcessiveUseOfCobblestone** [comment]
Why would add a way to mass produce an item that was literally made to forgo every downside to doing actual surgery?

**Comment by kevinz000** [comment]
if you want your [[[stuns are capped at 4 seconds]]] you should have to get surgury done for it, damnit.

**Comment by Repukan** [comment]
Powercreep

**Comment by 81Denton** [comment]
Whole point of implant surgery is that you need someone else to do it for you. Or just be a cool kid and implant yourself with a slime clone.

**Comment by Tlaltecuhtli** [comment]
oh well

**Comment by PKPenguin321** [comment]
HOLY SHIT STOP ADDING THIS TO R&D

**Comment by adamkad1** [comment]
lol

**Comment by ExcessiveUseOfCobblestone** [comment]
It's the newf// litmus test

**Pull request closed without merging**
