### PR TITLE
Grilles no longer try to defib people with no heart

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by Timonkeyn** [comment]
what

**Comment by optimumtact** [comment]
**GRILLES NO LONGER TRY TO DEFIB PEOPLE WITH NO HEART** @Timonkeyn

**Comment by Dawson1917** [comment]
please make grilles actually defib at some point so i can see "Dawson Kopper has died at Central Primary Hallway x4" whenever i walk into shock grilles open to space

**Comment by ExcessiveUseOfCobblestone** [comment]
really that proc should just fail on not having a heart tbh..

**Comment by optimumtact** [comment]
It's overloaded to also mean the non existence of a heart in species that require a heart. hence the second proc

**Pull request merged**
