### PR TITLE
adds clarification to flavor text in hunger symptom line

### PR DESCRIPTION
**Pull request by plapatin**
## About The Pull Request
travis is a liar don't listen to him
See title.
This is done in order to ensure nobody goes and actually kills someone over a bite of food. Y'know, because that's wrong.

## Why It's Good For The Game
Some players may believe this to be a sign that they are now an antagonist, which is not true.

## Changelog
:cl:
tweak: It is no longer possible to want to literally kill someone over a bite of food. It's just a figure of speech. Murder is wrong.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
add another one that says "my belly is neither round nor full"

**Comment by RaveRadbury** [comment]
I'm surprised that we aren't using the vernacular "I'd kill for a bite to eat" which is pretty straightforward and an everyday expression.

**Comment by PKPenguin321** [comment]
you dont understand, people NEED to mentally image the rotundness of my big, blubbery belly 😻

**Comment by optimumtact** [comment]
If you cater for the lowest common denominator, the lowest common denominator is all you will get.

It's a no from me

**Pull request closed without merging**
