### PR TITLE
Makes the "Ian's Adventure" station trait more interesting by making the dog deadchat controllable plus extra lives.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Makes the "Ian Adventure" station trait more interesting by giving him deadchat control (democracy mode, 3 seconds cooldown on inputs) and a couple extra lives* to survive early round tiding. 

*Basically, a new component that respawns the critter when he dies. The component itself is simple enough, but it sends a signal each respawn to allow other datums to expand this behavior how they want. I've contemplated adding a signal that can stop death, dusting and gibbing instead of respawning the mob at first but because `death()`, `dust()` and `gib()` were made with the assertion that the mob is always going to die I've quickly realized it'd require a refactor that's way too big and out of scope.

The deadchat control of corgis only include commands to change and drop hats, "speak" (random lines from the speak list of the mob) and spin (other than cardinal movement) for now. I'd have loved to add more complex commands (like, argumented) that can potentially be relayed to the AI controller, but I guess that'll have to wait until the thing gets refactored a little.

## Why It's Good For The Game
"Ian's Adventure" is a really bland station trait at the moment. All it does is move Ian somewhere else at the start of the round. Even by the station traits standard of being small things this is insignificant, and also pretty bad considering Ian is not actually going on an adventure since he lacks the initiative to do anything being an npc dog.
This PR aims to breath fresh air into this station trait and push it toward a slighty more engaging direction, though it relies on observers to work, while still being a small """"cute"""" station trait.

## Changelog

:cl:
expansion: The "Ian's Adventure" station trait now makes Ian deadchat controllable and gives him a couple extra lives (to survive early round tiding)
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
This would be better improved by making them able to vote every few minutes on where ian goes next and then just using the path finder to send ian off to there.

Along with a whistle for the HoP that sends ian running back to the last whistle call.

Deadchat control is just going to make ian a spaz.

**Comment by Ghommie** [comment]
> 
> This would be better improved by making them able to vote every few minutes on where ian goes next and then just using the path finder to send ian off to there, could randomly pick from the POI list for things on the same Z level.

It's a good idea, but I'm worried the path finder might lead Ian to dead ends quite often. There are a lot of airlocks around and Ian lacks the access to even walk through maintenance (though someone is working on a simple access component so that can be fixed ez pz)

> 
> Deadchat control is just going to make ian a spaz.

It's set on democracy mode, so only a single command (voted by relative majority) will be executed per cycle. We can expect Ian to not be as spastic as if it were controlled through anarchy mode and more so when only a few ghosts are orbiting him. He won't always act coherently, such is the charm of chat plays, but I believe both ideas could coexist without fundamental problems.

**Comment by KittyNoodle** [comment]
give ian aa during adventure or literally nothing will happen ever

**Comment by Likteer** [comment]
> 
> 
> give ian aa during adventure or literally nothing will happen ever

Also, pulse rifle

**Comment by optimumtact** [comment]
fuck it why not

**Pull request merged**
