### PR TITLE
Removes revolutions

### PR DESCRIPTION
**Pull request by optimumtact**
tip that wasn't accurate.

Revolutionary is more about who you convert (both in a meta sense of robust people) and their job accesses.

### CODE REVIEW

**Comment by Ziiro** [comment]
grudge code

**Comment by DinkleNH** [comment]
no thankies

**Comment by ishitbyabullet** [comment]
Oranges is the best hero unit you can deploy on the field.

**Comment by pigeonsk** [comment]
This is contradictory to Marxist-Leninist dialectics.

**Comment by Swiftkor** [comment]
almost gave me a heart attack there

**Comment by Borisvanmemes** [comment]
God i fucking wish that this PR really did remove revs.

**Comment by actioninja** [comment]
based orange man

**Review by Cyberboss — APPROVED** [review]

**Comment by ATH1909** [comment]
Isn't speedrevs a valid strat, though?

**Pull request merged**
