### PR TITLE
Removes the robbierotten suit

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Incoming5643** [comment]
When I say go, be ready to throw!

**Comment by Mark9013100** [comment]
It was his meme mister Goofball, HE WAS NUMBER ONE!

**Comment by PKPenguin321** [comment]
I don't mind this one tbh, just an outfit

**Comment by Cyberboss** [comment]
Removing content why?

**Comment by Militaires** [comment]
i love you

**Comment by GunHog** [comment]
>Removing content why?

He is on another tantrum is why.

**Comment by Iamgoofball** [comment]
i'm removing copyrighted content that 1. people dont use, and 2. jesus crhsit stop adding the meme of the motnh

**Comment by calzilla1** [comment]
Even though i hate that maymay, what better cloathing is to catch super-heros with???

**Comment by coiax** [comment]
It turns out that a blue and purple suit is copyrighted. I didn't know you could copyright the concept of a purple and blue suit, but apparently that's how copyright works.

**Comment by Militaires** [comment]
why

**Comment by Cyberboss** [comment]
CHERIDAN!

**Comment by optimumtact** [comment]
I like robbie rotten so I don't support this one

**Comment by dannno** [comment]
"copyrighted content" lmao nigga come on shut the fuck up

**Comment by KorPhaeron** [comment]
Just make it adminspawn

**Comment by Cheridan** [comment]
see this one doesnt seem to have any support so i'll close it

wow that was hard

**Pull request closed without merging**
