### PR TITLE
513.1536 is the stable BYOND version

### PR DESCRIPTION
**Pull request by Cyberboss**
Updates dependencies.sh to it.

### CODE REVIEW

**Review by stylemistake — APPROVED** [review]

**Comment by cacogen** [comment]
I don't suppose this tells people the most recent version the game can run with because of extools or whatever

**Comment by Cyberboss** [comment]
@cacogen come again? This is the recommended BYOND version to use for hosting /tg/

**Comment by cacogen** [comment]
The compiler stops you compiling if your BYOND version is out of date. But last I tried the latest version of BYOND wouldn't run /tg/ .dmb files because of extools and nothing tells you why. I was wondering if this changed that. But now I'm fairly certain it has nothing to do with it.

**Comment by SpaceManiac** [comment]
@cacogen See #56104

**Comment by cacogen** [comment]
@SpaceManiac Thanks.

**Pull request merged**
