### PR TITLE
Attention: Freeze on some icon files upcoming (1/17)

### PR DESCRIPTION
**Pull request by ghost**
I'm doing an inhand refactor as well as refactor on some very large files that are commonly added to.

icons/mob/items_lefthand.dmi
icons/mob/items_righthand.dmi
icons/mob/uniform.dmi
icons/mob/suit.dmi
icons/obj/guns.dmi
icons/obj/clothing/uniforms.dmi
icons/obj/clothing/suits.dmi

Don't touch these files until I've finished refactoring them in an upcoming PR. This freeze goes into effect Saturday January 17th.

Additionally, these PRs below need to be reviewed and either merged or closed with high priority so I can begin my work with minimal conflicts:
- [ ] https://github.com/tgstation/-tg-station/pull/6320
- [x] https://github.com/tgstation/-tg-station/pull/6594
- [x] https://github.com/tgstation/-tg-station/pull/6966
- [x] https://github.com/tgstation/-tg-station/pull/7034
- [ ] https://github.com/tgstation/-tg-station/pull/7035
- [x] https://github.com/tgstation/-tg-station/pull/7084

Listed from oldest PR to newest PR. Please finish these PRs up within the next couple days or you're going to be dealing with a fuckload of conflicts.

### CODE REVIEW

**Comment by optimumtact** [comment]
:ice_cream:

**Comment by paprka** [comment]
silly tag time

**Comment by paprka** [comment]
Updated OP and title. This freeze starts on 1/17. Feel free to merge stuff until then or open new PRs.

**Comment by ike709** [comment]
rainbow tags pls

**Comment by Cheridan** [comment]
sorry, this is a professional organization. we only tag things appropriately.

**Comment by ike709** [comment]
@Cheridan #6718

**Comment by Cheridan** [comment]
That is clearly an error on Github's part, I will have to send a ticket to their support. We would not use our tags so haphazardly. :tophat:

**Comment by tkdrg** [comment]
Chainsaws will still wait on dismemberment (ie a lot of time), so they'll be done after this.

**Comment by paprka** [comment]
kk

**Comment by Miauw62** [comment]
#6320 and #7035 are both not going to be merged for a while, and I'm waiting for Remie to merge #7084.

**Comment by RemieRichards** [comment]
Provided noone has any concerns, #7084 will go in today.

**Comment by JJRcop** [comment]
Tags you're missing: Fix, Maintainability - Hinders improvements

**Comment by ike709** [comment]
Every PR listed that'll be merged anytime soon has been merged, let the refactoring commence!

**Comment by paprka** [comment]
starting work on this, then. PR should be up by sunday provided I get enough time to work on it saturday (tomorrow)

**Comment by dannno** [comment]
So what exactly are you doing? Culling inhands? Or making it so that we can use more than 512?

**Comment by paprka** [comment]
Planned changes:

- Definitely splitting up guns.dmi into energyg.dmi and projectileg.dmi in a subfolder for icons/obj so we can have a fuckload of guns
- Definitely spitting up uniforms.dmi into jumpsuits.dmi and undersuits.dmi, jumpsuits will be 'onesies' and files in undersuits will be traditional suits/misc stuff like clown uniform.
- Definitely making an icons/mob/inhand subfolder.
- Definitely splitting up inhands into categorized files, inside /inhand (like guns, clothes, etc)
- **Possibly** making left hand inhands work by mirroring and pixel shifting right handed inhands, so we only need 1 inhand state for every item, and 1 inhand file for each category (all inhand sprites would be right handed) This kind of code is beyond my grasp, but if I can get help with it, it's a stretch goal for the project.

**Comment by dannno** [comment]
Nice. 10/10. Bout time.

**Comment by tkdrg** [comment]
I think inhand_state is a bit confusing since it's also used as the prefix for wearable items. But that's a minor complaint, keep up the good work.

**Pull request closed without merging**
