### PR TITLE
Add merge conflict markers to linter

### PR DESCRIPTION
**Pull request by Maurukas**
## About The Pull Request

Updates check_grep.sh with a case for the /obj mapmerge2 creates on merge conflicted tiles. You're supposed to fix all of these before you continue a merge, but there's zero warning if you don't clear them all. As a result they can end up in the commit pushed to github, and they can hide quite easily in a PR that otherwise looks fine.

CI should be rerun after the two remaining cleanup PRs are merged.

## Why It's Good For The Game

Your average map file is about 3 megabytes of raw text, or 160,000 lines. I don't want to have to read them all to prevent this from happening again.

### CODE REVIEW

**Comment by Zytolg** [comment]
This. We've just cleaned up several of these, and it takes longer when you have to comb the entire map for these little jerks. CI is going to help keep them that way.

**Review by LemonInTheDark — APPROVED** [review]
Yes

**Comment by Timberpoes** [comment]
I would not be opposed to speedmerging this.

Silent errors are bad and we probably shouldn't be merging any more mapping PRs until the errors this lint highlights are fixed?

**Review by Timberpoes — APPROVED** [review]

**Review by Mothblocks — CHANGES_REQUESTED** [review]
i updated ci and it doesnt pass

merge from upstream so it will

**Comment by Maurukas** [comment]
Not sure why the rest of the checks aren't running.

**Comment by LemonInTheDark** [comment]
Let's bounce

**Pull request merged**
