### PR TITLE
Windows now have the proper starting health

### PR DESCRIPTION
**Pull request by ChangelingRain**
@Cyberboss

### CODE REVIEW

**Comment by Cyberboss** [comment]
What? What's going on?

**Comment by lzimann** [comment]
Hm, what?

**Comment by ChangelingRain** [comment]
Reinforced, and in fact all, windows will start at 25 health without this.

**Comment by Cyberboss** [comment]
Why though?

**Comment by ChangelingRain** [comment]
Because they have a set obj_integrity, and your pr only sets it to max_integrity if obj_integrity isn't set???

**Comment by Cyberboss** [comment]
Ahh, yeah the way windows were would fuck with this yeah

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Speedmerging because kinda important

**Pull request merged**
