### PR TITLE
Fixes pestles

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Fixes a bug caused by #48901 which caused pestles to be uncraftable on the main servers due to the testmerge.
Allows for said testmerge without causing issues with crafting.

## Why It's Good For The Game

People will stop intermittently bringing this up in the discord, confusing me and ruining all discussion.
Also yaknow some people sometimes use this for things like ghetto chem, xeno shit, nerd stuff. Ehhh whatever.

## Changelog
:cl:
fix: Fixed pestles not being craft-able. 
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Not totally sure what's going on here, I get errors when copying the testmerge on my branch, so I assume that's part of it.

**Comment by ShizCalev** [comment]
shouldn't be an issue anymore?

**Comment by LemonInTheDark** [comment]
> shouldn't be an issue anymore?

It's a non-harmful fix, the only effect in a void is changing the order of the list.
And for some reason the vote-box pr is still test-merged, so I'm going to keep it up.

**Comment by optimumtact** [comment]
I have removed the votebox pr

**Comment by LemonInTheDark** [comment]
Mission accomplished boys

**Pull request closed without merging**
