### PR TITLE
Changes required access to install and run techweb

### PR DESCRIPTION
**Pull request by PrefabQuasar**
## About The Pull Request
Changes the required access to use the modular console research program to RND access, instead of only the RD being able to install it, and only heads being able to use it.

## Why It's Good For The Game
Scientists could not use the modular research console provided roundstart, and instead had to make the old console every single round.

## Changelog
:cl:

qol: scientists can now use the science program

/:cl:

### CODE REVIEW

**Comment by Y0SH1M4S73R** [comment]
As much as this feature is greatly desired because of how a mapping update kinda screwed R&D players over, this is still in violation of the freeze.

**Comment by JohnFulpWillard** [comment]
I don't understand this PR. RnD consoles were moved to RD's office and Bridge because it's Command's job to handle research, that's why you need Bridge access to use the Science app, and why Command tablets start with it installed. 
This is also re-locking Command out from using the app, who it was made to be used by.

**Comment by LemonInTheDark** [comment]
You don't know what you're getting yourself into. https://hackmd.io/@tgstation/Sy8W0nvv8#Research-and-Development-orange (This doc is slightly old, but it's still like, the goal of experisci and such. Idea being that different experiments are tied directly to their linked departments and etc etc)

Also feature freeze #60608

**Comment by PrefabQuasar** [comment]
welp, didn't know about those before making this, thanks for telling me though.

**Pull request closed without merging**
