### PR TITLE
Null rods defend better from clockcult stuff

### PR DESCRIPTION
**Pull request by ChangelingRain**
**NULL**, the Element of No-Selling your shit.

Can't Geis bind, Ratvarian Spears do less damage and won't stun if thrown at them, Sevtug and Nzcrentr don't affect the holder, and Mania Motors won't try to convert the holder.

### CODE REVIEW

**Comment by Supermichael777** [comment]
ocular wardens


That is all

**Comment by ChangelingRain** [comment]
ocular wardens don't even attack people holding null rods, silly

**Comment by AdamElTablawy** [comment]
now all we need to do is make it kill cogscarabs AoE 

or more rationally make it oneshot cogscarabs because god damn i hate the little infinite griefdrones

**Comment by Supermichael777** [comment]
cogs crabs are the worsrt fucking meme

Literally goodby armory

**Comment by KingPhilipIII** [comment]
You don't know suffering until you're a cultist with a few idiots to assist you and the AI opens ten chaplain slots. As far as cog scarabs, I think that's more of a player issue than a balance problem. The players choose to steal the weapons or go murder as builder drones.

**Comment by Mindustry** [comment]
why can drones even fire guns?

**Pull request merged**
