### PR TITLE
Adds tier 2 power cell to R&D

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

- Adds high-capacity power cell+ to R&D
- Renames it mega-capacity power cell
- Updates the stripes on top of the cell sprites to properly reflect their part ratings

## Why It's Good For The Game

There was talk in coderbus of removing this cell, despite its widespread use throughout the game, due to its snowflakiness because it isn't researchable in R&D. This fixes that by adding it to the Industrial Engineering node.

I think another reason it isn't taken seriously is it has a name similar to the 5k cells used only in APCs, as opposed to being its own standalone thing. But this is the tier 2 power cell, not the super capacity power cell as one might think. 

This attempts to remedy that by renaming it mega-capacity power cell, something that could conceivably come between high-capacity and super-capacity. If you have a better suggestion, please let me know.

Also updates cell sprites to have the correct number of stripes relating to their part rating. Aside from the high capacity power cell, they all had one too few.

## Changelog

:cl:
expansion: Tier 2 power cell is now in R&D under the Industrial Engineering node
fix: Power cells now have the correct number of stripes for their part rating
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
it's not meant to be buildable, it was specifcally added to map into the round for robos, to encourage borgs to come to them at roundstart.

**Comment by cacogen** [comment]
No, that isn't true.

https://github.com/tgstation/tgstation/pull/12434#issuecomment-148877859

**Comment by tralezab** [comment]
Supercaps show up after 10 minutes, these serve no purpose at all.

**Comment by cacogen** [comment]
I don't think he needs your help to kill my pull request in support of the other needlessly destructive one that has zero consideration for why these were added in the first place.

But you could say the same about high capacity power cells. You could say the same about any stock part that you unlock before better parts are unlocked in the node the super capacity power cell is in.

**Comment by optimumtact** [comment]
it is true, they were var edited on the maps, use your brain you malder

**Comment by cacogen** [comment]
No, the idea they were added to incentivise borgs to come to robotics roundstart is just some headcanon explanation you've either heard or come up with that's convenient to trot out here. 

Now you're altering it to say they were added via var-edits before the high-capacity power cell+ was introduced after what you've read there, as though you have any idea why the original mapper added 15k cells to robotics.

**Comment by zxaber** [comment]
I thought T2 cells were Supers.

High > Super > Hyper > Bluespace.
High+ doesn't have any reason to be manufacturable, since supers *do* come out fairly early. They're nice for robotics early on.

I don't like their removal either, but I don't think stuffing *another* cell into the exofab/protolathe is helpful.

**Comment by cacogen** [comment]
No. High capacity cells have a rating of 1, like the base cell. Super capacity cells have a rating of 3. Bluespace cells have a rating of 5. 

There's no good reason not to have it in the protolathe. 

Why are you even arguing this, if you don't want to see it gotten rid of?

**Comment by tralezab** [comment]
I've looked deep into the RND progression of cells and it's all insanely dumb. You start with 10k, unlock nothing with industrial, then unlock BOTH 20k and 30k with advanced power. Finally, you unlock 40k with bluespace. Super cells are just useless I guess lol, but the last thing we need with that clown progression is yet another cell

**Comment by necromanceranne** [comment]
>Super cells are just useless I guess lol, but the last thing we need with that clown progression is yet another cell

It's _maybe_ justified as 'the cell you build when you don't have materials', since it doesn't require anything more than iron and glass to construct. When miners all die before 10 minutes, I usually build that and a ripley to go mine as robo. It does the job.

**Comment by Thunder12345** [comment]
> edit: Also if we really wanna get into talking about how fucking stupid cells are, the bajillion subtypes of various cells including the cells used in firearms is a rabbit hole in of itself.

There's a whole refactor sitting right there by itself, I'll deal with that next

**Comment by cacogen** [comment]
>I've looked deep into the RND progression of cells 

No, you just had a quick look at what cells unlock in which nodes the way I did before I made this.

>You start with 10k, unlock nothing with industrial

So why do you think I've added it to Industrial Engineering? 


>then unlock BOTH 20k and 30k with advanced power.

Yes, and it's not only cells where multiple tiers of part are unlocked in the same node. As NecromancerAnne pointed out, the lower tiers are still useful if you don't have the materials for the higher tier.

**Comment by optimumtact** [comment]
okay im not going to argue with you, I know why they were added

**Comment by cacogen** [comment]
As usual, you're making things up to justify your position and insisting it's the truth despite all reason.

**Comment by optimumtact** [comment]
ok

**Pull request closed without merging**
