### PR TITLE
Valentines antagonists will now only show on the roundend if they failed their date

### LINKED ISSUE #42762: valentines are in the antag list
>wiz dies
round still goes on because valentines

i need my antag reroll

### PR DESCRIPTION
**Pull request by tralezab**
Roundend on valentines gets cluttered, this should make it a little bit shorter
kinda fixes #42762 but perhaps 

>That said, the mulligan system should check for a variable on the antag to signal that it can not count those as delaying round end tbh.

should be done as well.

:cl:
tweak: the game will now specifically call you out if you fail the date on valentines!
/:cl:

My other idea is checking if more than half the station completed their date, and changing if it shows who completed/failed based on the smaller group. In the face of complete chaos only these completed their dates/most managed to keep their dates except for these losers!

### CODE REVIEW

**Comment by ATH1909** [comment]
Eh, I like knowing who everyone's date was (and if they succeeded in keeping their date alive).

**Comment by ExcessiveUseOfCobblestone** [comment]
It should just list a couple as 1 entry instead of 2, I think there's some value in seeing who the pairs were whether they completed obj or not.

**Comment by ExcessiveUseOfCobblestone** [comment]
Oh wait I forgot it was wild west dating

**Comment by tralezab** [comment]
It is wild west correct

**Comment by tralezab** [comment]
I'll just do my list who dated well of not many did or list who failed if many dated well idea. It'd be pretty awesome to be the last few dates to survive a murderbone

**Comment by tralezab** [comment]
this isn't really the full fix to the issue and i'd have to do a lot of annoying things with antagonist teams to do it justice

**Pull request closed without merging**
