### PR TITLE
[s] adds actual logging to spray bottles

### PR DESCRIPTION
**Pull request by imsxz**
## About The Pull Request
adds logging to spraybottle usage. spraying in general is logged in game to track people spreading plasma/lube/whatever. theres transferring reagents to people via spraying logged in attack.

## Why It's Good For The Game
i had to deal with a ticket where this guy died and i just couldnt find out how???? so i checked any relevant log file/investigate file and there was fucking nothing. go figure he had pest killer in him, so i tested it in thunderdome with pest spray bottles and theres just????fucking?????nothing logged???how the fuck did this exist in this state for so long oh my god?????

## Changelog
:cl: Imsxz
admin: spray bottles are fully logged now
/:cl:

### CODE REVIEW

**Comment by imsxz** [comment]
dont mind the commits thats just me figuring out how git works

**Comment by MrDoomBringer** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by MrDoomBringer** [comment]
image

**Comment by imsxz** [comment]
ok its updated

**Comment by HomocidlePancakes** [comment]
Gonna go griff people with sprays before this gets merged AND THERE IS NUFFIN U CAN DO MUHAHAHAHAH

**Comment by Tlaltecuhtli** [comment]
admin can just get all sprays and check for fingerprints

**Pull request merged**
