### PR TITLE
Fixes the HoS multiphase gun to actually be useful.

### LINKED ISSUE #19397: HoS Multiphase gun now fires half the rounds at twice the cost.
I'm not aware if this is entirely a bug, but now the HoS laser is completely underpowered and almost completely useless. May need patching.

### PR DESCRIPTION
**Pull request by ChayseRamsay**
:cl: JakeRamsay007
fix: Changed the Multiphase Energy Gun cell to that of the pulse pistol, hopefully making it actually useful in the process.
/:cl:

Changes the cell to be the same as the pulse pistol.
Fixes #19397

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Won't that just give it a ton of taser shots?

Better to just give it a subtype of laser that takes less power

**Comment by ChayseRamsay** [comment]
I believe it had around 14-15 taser shots from a full charge. I'll have to test again, but in my honest opinion, since it's the HoS' one of a kind gun, that seems a pretty fair amount.

**Comment by Shapsy** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by lzimann** [comment]
14 taser shots is a LOT

**Comment by ChayseRamsay** [comment]
@KorPhaeron @lzimann I just tested it, modified shot counts from full charge are as follows.
Taser shots: 10
Laser shots: 20
Disabler shots: 40

**Comment by Zilenan91** [comment]
yeah that seems like quite a bit too many shots for his gun.

**Comment by Anonmare** [comment]
Yeeeaahhh even I think 40 disabler and 10 taser shots is a heck of a lot.
It'd make it straight up better than even the Advanced energy Guns and Captain's Laser in a short-term engagment

**Comment by Zilenan91** [comment]
In pretty much any engagement. You'd be able to stun and lase 2 or 3 people before you need a recharge, and that's with one gun.

**Comment by Fox-McCloud** [comment]
It is already useful....5 taser shots, 10 laser shots, and 20 disabler.

It's already Energy gun+

**Comment by TheNightingale** [comment]
The HoS _should_ be a significant threat. They're the Head of Security, after all. Assuming they're only using their multiphase and an egun (inventory space means carrying more is impractical), the HoS still doesn't have much of an edge over any other chump with a taser and laser gun.

Though I'm not sure if offensive buffs are the way to go about it; with stuns being as lethal as they are, giving the HoS more shots in their gun will still mean they get stunned and killed before they can react. Perhaps a single-use adrenal implant?

**Comment by Steelpoint** [comment]
To 'correct the record' the HoS lost one of his Energy Guns at the same time they were nerfed from being fantastic to meh. This left the HoS in a akward position which often resulted in HoS players taking weapons from the armoury to compensate for their significant loss in power.

My HoS Egun was added to adjust for this change, the HoS Egun is just a new Energy Gun but with a stun setting, not to mention the HoS Egun is still objectively worse than the original Energy Guns.

I would not mind boosting the amount of lethal rounds the HoS Egun gets.

**Comment by KorPhaeron** [comment]
@TheNightingale
>(inventory space means carrying more is impractical)

What game are you playing? You have a ridiculous amount of inventory space in SS13

I can (and do) carry at least 7 guns when I'm playing head of security, captain, or warden.

**Comment by Zilenan91** [comment]
Also... the HoS doesn't just have armory access because he could have a private space to jack off. If he needs firepower he can grab it.

**Comment by AdamElTablawy** [comment]
to be fair

as is the hos's tazer

literally has less tazer shots than an actual tazer

it DOES deserve a shot increase but not this much.

@Zilenan91 
so the hos should be forced to loot the armory that is for security personnel who are unarmed

to do his job with a tazer at the same level as a security officer because his tazer literally has less shots than an ordinary sec officer

**Comment by Zilenan91** [comment]
>implying the Warden gives officers eguns ever unless everything is dying

**Comment by AdamElTablawy** [comment]
@Zilenan91 
>implying the default state of everything is not 'exploding and on fire'

**Comment by ChayseRamsay** [comment]
@KorPhaeron But you shouldn't /have/ to carry seven guns. This is the whole point here. If you're carrying all of the guns and there's an emergency, what are the officers supposed to use?

**Comment by Zilenan91** [comment]
Nothing. Because wardens don't give officers guns unless things are exploding everywhere. They have their taser.

**Comment by ChayseRamsay** [comment]
@Zilenan91 A good warden should be distributing eguns to officers whenever there's traitors actively murdering people.

**Comment by jughu** [comment]
Zileman if you take all the guns and you get catched by culted/rev etc its pretty much done for security and thats why you dont carry the whole armoury in your backpack it aint smart if you miss the first gun you probaly gonna miss the second one too

**Comment by KorPhaeron** [comment]
Doesn't seem popular, sorry

**Pull request closed without merging**
