### PR TITLE
Attempts to fix space suit thermal protection.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

When you manually turn off you space suit thermal regulator, the suit's thermal protection also completely stops.

However, when space suit cells run out of charge, the thermal regulators stay on and the suit's thermal protection isn't wiped.

In the code's logic, while suits they DO stop regulating your temperature when their cells run out, they DON'T stop protecting it. Your temperature will never fall as long as you don't force a toggle of the thermal protection to off. Your natural biological processes will maintain your temperature instead of the suit.

This lead to a weird interaction where the following can be observed.
A suit with a dead power cell can still turn thermal regulators on. They will maintain your body temperature but will not regulate it. This includes a power cell with exactly 0 charge.
A suit with no power cell at all will not maintain your temperature at all or protect you from low temperature environments. It only protects from pressure.

Functionally, since the introduction of space suit power cells and the temperature regulation, space suits have not disabled their thermal protection when running out of power.

Pull out some reusable HUD-related code into a simple proc to allow refactoring of the existing code. Minor modifications to this code's logic path.

Automatically toggle thermal regulators off when cell doesn't have enough charge, removing thermal protection.

End result - When your space suit runs outta charge, your body temperature now falls and you take burn damage. This happens VERY slowly if you have an accompanying space helmet.

FIQuTVxngx

This is because space helmets do not require power to provide their thermal protection and thus a combination of a space helmet and unpowered space suit will allow [natural_bodytemperature_stabilization()](https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/life.dm) to maintain body temperature very effectively by shooting you back up out of the danger zone as soon as you get cold enough and take your 3 points of burn damage.

However, space helmets would have to be the topic of another PR as addressing that would be a fundamental balance change (should space helmets only provide thermal protection when worn alongside an appropriate space suit with thermal regulators on?)

## Why It's Good For The Game

My speciality - Fixing shit that never actually worked since its inception.

## Changelog
:cl:
fix: Due to a need to lower manufacturing costs, all space suits are now made of inferior thermal material and no longer maintain the wearer's temperature indefinitely after their cells run out of charge.
/:cl:

### CODE REVIEW

**Comment by nightred** [comment]
The RD and space ninja need processing on always this might cause them issues.

**Comment by Timberpoes** [comment]
> 
> 
> The RD and space ninja need processing on always this might cause them issues.

You are correct. Ninja suits processing does more than just regulate temperature. I'll look into this further. I'd have LIKED to run the processing loop more efficiently but I guess in this case I can just make sure the damn thing sets the thermal protection to off when it runs out of battery and call it a hacky-fix day.

**Comment by Timberpoes** [comment]
Re-did my approach based on the feedback about other space suits.

**Comment by Rohesie** [comment]
Is this tested locally and properly working?

**Comment by Timberpoes** [comment]
> 
> 
> Is this tested locally and properly working?

This has been tested locally via the ninja suit (which is now completely unmodified by this change), RD prototype hardsuit and standard suit from EVA storage.

The result can be seen in the attached animation to the PR. When the cell runs out of charge, thermal regulators and protections cease, and the suit goes from its powered 2 kelvin cold protection to its baseline unpowered cold protection. At this point the suit wearer starts to take damage in space very slowly (as their ordinary biological processes/metabolism kick in to re-heat them every time they take a tick of cold damage).

## process Proc
UI update logic has been pulled out to a new proc to allow the UI update to be called in more places. You'll note that the spacesuit UI now updates AFTER the game logic has been processed for all relevant code paths. Previous functionality was to update the UI BEFORE removing the charge from the space suit cell for thermal regulation. This meant the UI always lagged 1 processing tick behind the cell's charge state.

An additional code path (lines 85-89 of this PR) was added where the cell does not have enough charge to power the thermal regulator. This was the core bug I fixed in this PR. This code path toggles the thermal regulator off. I leveraged the logic inherent in cell.use() for this - I don't need to manually check cell.charge, if cell.use() returns false then the cell failed to subtract the requested charge for whatever reason and the thermal regulators should shut off. If it returns true, the appropriate charge was removed from the cell and the thermal regulators maintain temperature.

## toggle_spacesuit Proc
Added a simple logic switch here which was missing previously. If thermal protection is not on and there is no cell or the cell doesn't have enough charge to enable thermal protection, the proc returns early, preventing the suit's thermal protection from toggling on. This was needed as the spacesuit thermal regulation is also toggled on from code/datums/action.dm adding the action icon to the UI. Despite my process proc change, this being unchanged would allow me to constantly toggle the spacesuit thermals on manually between each processing tick (that would then disable it again) to retain the thermal protection when the suit cell was dead.

**Pull request merged**
