### PR TITLE
Adds a new HUD: The Detective UI!

### PR DESCRIPTION
**Pull request by kinneb**
## About The Pull Request
This PR adds the new HUD; The Detective UI
Originally made for fun, it was recieved well enough to make me publish it. Its designed to have a fun gimmick (That Being Noir Detectives), but still be easily readable at a glance!
image
image
## Why It's Good For The Game
New HUDs mean more customization options for players, and as far as I'm aware I think thats a pretty good thing!
## Changelog
:cl:
add: A new HUD, The 'Detective' UI
imageadd: All the spritework for said HUD.
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
Got better Combat mode icons than basic UI

**Comment by tralezab** [comment]
there's a lot of great stuff here, i love it, but holy shit
image
whatever's going on here has to be stopped

**Comment by kinneb** [comment]
> there's a lot of great stuff here, i love it, but holy shit image whatever's going on here has to be stopped

could you clarify? its meant to be a book, with a coffee stain on the right hand

**Comment by YakumoChen** [comment]
Oh that's a cigar on top of the book 'hands'

This looks disgustingly good

Only missed opportunity here is a trenchcoat for the suit slots

**Comment by tralezab** [comment]
> could you clarify? its meant to be a book, with a coffee stain on the right hand

now i see it, ok thats neat

**Pull request merged**
