### PR TITLE
Pseudo Feature Freeze

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
We have too many bugs and too many bikeshedding arguments about our latest conversion mode or redundant RD gun, it's time to try putting our energies elsewhere.

## Things that will be accepted during this freeze:

- Bug Fixes

- Refactors

- Improvements to civilian systems or gameplay or new features that you can use while not an antagonist without getting banned

## Things that won't be accepted:

- Balance changes (there can be incidental balance changes from otherwise acceptable PRs, but no "I buffed tasers" or "I nerfed eswords"). This includes changes/balancing under the guise of reverts/removals. If you feel strongly that we absolutely can not wait to change X feature because it is making the game unplayable PM me and if I agree I'll open a revert.

- New antagonist toys/types/etc

- New civilian stuff that can't realistically be used without being an antagonist or using it on an antagonist.

The freeze will last 1-2 months (We'll see how its going and how people are feeling in 30 days)

## Things that are exempt from this: 

- Xhuis redoing clock cult

- Robustin wrapping up his gang changes

- PRs opened before the freeze

## List of coding projects for the freeze (and you can skip the freeze if you finish one)

By which I mean you can make one or more balance or feature PRs if you finish something from this list, depending on how complex the project is

https://tgstation13.org/phpBB/viewtopic.php?f=5&t=11755

### CODE REVIEW

**Comment by Chocobro** [comment]
>pseudo feature freeze

>-Improvements to civilian systems or gameplay or new features that you can use while not an antagonist without getting banned
>new features

excuse me

**Comment by kyrahabattoir** [comment]
Yes please.

**Comment by RemieRichards** [comment]
@KorPhaeron please learn some basic Markdown, k thnx.

**Comment by KorPhaeron** [comment]
You enable me

**Comment by KorPhaeron** [comment]
@Chocobro 

http://www.dictionary.com/browse/pseudo

**Comment by Chocobro** [comment]
i request this be renamed to "pseudo feature freeze except for that one thing that's why there's pseudo in the name"

**Comment by outbools** [comment]
pls let this pseudo freeze last several years

**Comment by DoctoreMad** [comment]
>Robustin wrapping up his gang changes

Are you implying that shitshow will be merged, or just that its being allowed in by grandfather clause?

**Comment by KorPhaeron** [comment]
@DoctoreMad 

If he manages to make it fun it will be merged, otherwise gang will be axed

**Comment by Qbopper** [comment]
@KorPhaeron I remembered this thread but forgot about it until slig reminded me just now, I'm assuming this is a "balance change" so it's a ono go but wanted to double check anyways

https://tgstation13.org/phpBB/viewtopic.php?f=9&t=10613

**Comment by KorPhaeron** [comment]
No

**Comment by Robustin** [comment]
@KorPhaeron 

Why wasn't there an accurate warning on this?

I had a couple projects, including https://github.com/tgstation/tgstation/pull/28252, that I was wrapping up before the freeze and both the IRC message and your thread indicated that I had a couple days left at least. 

Honestly when I saw this PR go up I thought it was a freeze warning for people who don't trawl the forums because the idea of getting no warning on a freeze seemed absurd. Last freeze we laid out a specific date and time. This freeze all I get it "About 2 weeks" only to get my shit frozen 9 days later.

**Comment by Bawhoppen** [comment]
It's been as the coderbus's topic since it was first announced two weeks ago, not to mention the forum thread announcement. You had plenty of time.

**Comment by Robustin** [comment]
@Bawhoppen 

Did you even read what I typed? 9 days is much closer to "about 1 week" than the "about 2 weeks" we were notified about. The IRC announcement also didn't have yesterday as the freeze date (though people disagree about what date it WAS posted because of how it was phrased/posted).

**Comment by Bawhoppen** [comment]
I'm sorry but I wasn't counting days like you

**Comment by DoctoreMad** [comment]
Can someone make a list of roles that could use more stuff? I mean, I looked over in the wiki and I don't have much to say. I know that Scientists have negative priority and the Lawyer really needs some help due to lack of Devil rounds, but other than that?

**Comment by Bawhoppen** [comment]
How is it hard to figure out additions? Lawyer isn't one of them because their entire role relies on them interacting with people.

Here's just a few basic ideas:
More cooking stuff,
New medical systems,
Additional science mechanics
More engineering stuff and equipment,

Just think about possible ideas and do them, it's not that hard? 

Just don't add anything to R&D though

**Comment by GeneralGoose** [comment]
im more concerned about the commit

**Comment by KorPhaeron** [comment]
@GeneralGoose 

The PR is simply an announcement that the freeze is happening, every freeze going back to 2014 has had a one line joke (because we need a difference to open a pull request)

**Comment by Supermichael777** [comment]
Cooking is dependent on botany doing something other than weed or exotic deathnettle swords. It needs more of the stuff its reliant on botany for and a better interface(search when?).
People would riot if we implemented baymed or baymed lite and then whine about how sec broke their knees.
Science has 3 fleshed out mechanics, 1 unflushed turd, and one kitchen sink of stuff loosely gated behind how fast you can run through a checklist.

**Comment by Bawhoppen** [comment]
Wait what are the 3 fleshed out mechanics? I only count xenobio and toxins, and then the unflushed is experimentor I assume, and the final one is obviously R&D

**Comment by DoctoreMad** [comment]
Supermichael777 you're killing us here.

**Comment by TrustyGun** [comment]
Robotics perhaps?

**Comment by Supermichael777** [comment]
robotics is a part of science no matter what they say yes

**Comment by CosmicScientist** [comment]
Boop.
>The freeze will last 1-2 months (We'll see how its going and how people are feeling in 30 days)

Boop boop. How are people feeling?

**Comment by Bawhoppen** [comment]
bad and I want to die

that's unrelated though

We should probably continue this though it's working out well I think

**Comment by Supermichael777** [comment]
this freeze is not significantly improving bug numbers. feels itchy

**Comment by Bawhoppen** [comment]
It's meant to primarily improve core non-antag game mechanics, bugs are a secondary objective

**Comment by nicbn** [comment]
Isn't this supposed to be closed?

**Pull request closed without merging**
