### PR TITLE
Revert "Removes title4.ogg"

### PR DESCRIPTION
**Pull request by Niknakflak**
Reverts tgstation/tgstation#28882

### CODE REVIEW

**Comment by JJRcop** [comment]
Can someone other than @Cyberboss close this?
See https://github.com/tgstation/tgstation/pull/28912 for votes.

**Comment by Repukan** [comment]
Local admin in deep denial. 

More at 9

**Comment by JJRcop** [comment]
To be fair, #28940 happened.

**Comment by ExcessiveUseOfCobblestone** [comment]
The Lobby Music War / The Great War / The War to End All Wars

**Comment by ChangelingRain** [comment]
as good a song as this is, it's too long for the lobby AND is a low-quality version since it'd have been too large otherwise.
as such, it shouldn't have been a lobby song in the first place.

**Pull request closed without merging**
