### PR TITLE
Your funds are now actually able to be safe with CRAB-17. Removes the do_after from swiping your card on CRAB-17.

### LINKED ISSUE #60118: the movement of the crab-17 checkout machine interrupts the do_after() for cashing out with it
so you can basically only cash out if you've somehow pinned it into a single-tile space despite it moving like twice every second.

this is bad because it discourages actually interacting with the checkout machine the intended way (by making it an absolute bitch to do), which indirectly encourages just unga dunga bashing the checkout machine with a stick.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

See title.

## Why It's Good For The Game

Fixes #60118

## Changelog
:cl:
fix: Fixes not actually being able to cash out of CRAB-17 due to the device moving rapidly.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I think that the thing to remove here is the machine moving around, not the do_after().

if anything, the do_after() should be lengthened if we're making the machine not move around anymore.

**Comment by Mothblocks** [comment]
:-1: requiring multiple people pinning it down is a feature to me

**Comment by Mothblocks** [comment]
> I think that the thing to remove here is the machine moving around

this is also a feature and id like to keep it

**Comment by Iamgoofball** [comment]
ya ok

**Comment by Iamgoofball** [comment]
24 hour rule sorry

**Comment by Mothblocks** [comment]
i turned my clock 23 hours ahead

**Pull request closed without merging**
