### PR TITLE
Adds soy milk to biogenerator

### PR DESCRIPTION
**Pull request by kriskog**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Skoglol
tweak: Soy milk can now be produced in the biogenerator.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
I disagree with this, some things are sacred, soy should be collected from soy beans else what incentivises it.

@Vidiveni [contact me on discord please with a ping on /tg/ coding-general](https://discord.gg/b8Xh5r), as the PR creator for the enzyme in the biogen it'd be probably the most interactive method of helping me get a scope of the problem.

**Comment by kriskog** [comment]
@Vidiveni You are using it wrong. The enzyme has no option for bottle is added to whatever container you put in the machine.

**Comment by FantasticFwoosh** [comment]
I restrained myself from going in to correct you incase there was a code-problem, but essentially if you just detach the container from the biogenerator through the button, the reagents will be within it to the obvious maximum capacity of the container. Still get in  touch please if you have any further questions or issues.

- 10u of universal enzyme (or other choices of reagent like black pepper / milk ) = 10u _in the container_ 

Sort of like a pay-to-use chem-master for these reagents, afterwards you can place them into other containers or put them in a condiment master to get bottles. Personally i enjoy bottling milk into cardboard carton's for its own little drink-sprite.

**Comment by ExcessiveUseOfCobblestone** [comment]
The soyboys are coming with their plushie pitchforks and LED (but not too bright) torches

**Comment by Vidiveni** [comment]
Sounds like the enzyme is working as intended so I'll stop with the off-topics. I'll ping you on discord if I find any issues @FantasticFwoosh .

**Comment by BebeYoshi** [comment]
First we add Fluor to the biogenerato, then Soy Milk, why don't we just add all the unique nutriments and juices to the biogenerator? 
Basically don't try adding things for the biogenerator that can be already be achieved by common plants aka the ones at the crates/vendor

**Comment by Tlaltecuhtli** [comment]
doesnt the barman dispenser have the unique juices already

**Comment by Tlaltecuhtli** [comment]
doesnt the barman dispenser have the unique juices already

**Comment by optimumtact** [comment]
yeah please stop adding things that already have methods of generation in game to protolathes/autolathes/biogens

**Pull request closed without merging**
