### PR TITLE
Nerfs ocular wardens and mania motors

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Ocular Wardens do 17% less damage.
tweak: Mania Motors cause less brain damage and hallucinations.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
still waiting on ocular wardens damaging revenants

**Comment by Robustin** [comment]
Am I missing something... how was 3 damage per tick OP?

**Comment by Amemelius** [comment]
Through cover, and you often had 4-5 of them shooting at you while you're deconstructing objects because you can put a bunch in a pretty small area. On top of that, there's ten billion other spells being hurled at you that also pass cover.

You die very quickly.

**Comment by ChangelingRain** [comment]
Because per tick is about 5 times a second, they ignore cover that doesn't block vision, and it's not hard to have two of them overlapping.

**Comment by Robustin** [comment]
Since when is a tick .2 seconds, 4 tick stuns last 7 seconds. 

Also the game prevents you from putting them on the same screen, so no way are 4-5 of them shooting you at once.

Whatever though, clock cult has bigger issues.

**Pull request merged**
