### PR TITLE
Allows HoP to purge all IDs of their access, and implements a ID access recovery function in all PDAs

### PR DESCRIPTION
**Pull request by zxaber**
:cl: Zxaber
add: In order to cut down on costly emergency shuttles from stations overrun with All Access, the Head of Personnel can now purge access from every ID on the station.
add: PDAs now store ID access codes for backup, allowing them to restore access to blank ID cards. However, this function is only unlocked if an emergency access purge has been activated.
tweak: Due to the extra memory requirements of the backup function, PDA owner and owner job title are now stored in the PDA's ROM, and they cannot be altered once set. If you get a job change from the HoP, make sure you also ask for a replacement PDA!
/:cl:
I made a video to help demonstrate;
https://www.youtube.com/watch?v=arioXWHuHPE
Turn on CC for text.

As opposed to PKPenguin's detective HoP ideas, this is intended to be a heavy-handed method of dealing with the crew having all access once it has passed the point of "solve now or shuttle". All access tends to spread like a plague, especially due to the auxiliary ID consoles. As such, when faced with the task of keeping order against a grey tide that can go anywhere easily, Security and Command often opt for simply calling the shuttle and restarting the round. Allowing the Captain or HoP to purge access from everyone's IDs should help cut down the tide a bit.

After the purge, PDAs unlock their recovery mode (and give a helpful message), allowing them to update an ID with no job set, and giving access that the job is granted at shift start (using the same function that the ID console uses to assign default access). This means that anyone who wasn't participating in the all access shenanigans can simply recover their access quickly and are almost entirely unaffected. Anyone that did get extra access, legitimately or otherwise, will see their extra access lost. If they were granted this access by command staff, they will need to reacquire it again.

Custom (meme) job titles handed out, which are not listed in the jobs datum, will not be able to recover _any_ access, and the player will need to visit the HoP to restore their access, adding to the (potential) work load of the HoP themselves if they press the button. The PDA will give them their job title back, however.

In order to stop people from simply changing the title on their PDA, the PDA fields for owner and owner's job are now single-write. All starting PDAs already have these fields set.

In order to allow people to recover access to blank IDs, I had to remove the code where PDA's rejected IDs that didn't match their stored owner info. The end result of this is that you can someone else's ID in your PDA, and still have their access when opening doors. Since it's easy enough to just hide an ID in a pocket or somewhere else, I do not know if this is a big deal.

Golden IDs (The Cap's ID and the spare) are not affected. Whoever has one of these IDs will still have all access. That being said, because the Cap's special ID is not affected, PDAs with the job title set to Captain will also not enter recovery mode.

I would prefer this be test-merged first, since I'm dealing with some fairly critical parts of the game.

### CODE REVIEW

**Comment by optimumtact** [comment]
PKPenguins idea is good whereas yours is just more of a lame crew buff.

and you know how I feel about buffs

**Comment by zxaber** [comment]
PKPenguin's idea sounds like a lot of fun, but no one is gonna bother when it means you have to track down twenty separate people. This is intended to stop rounds ending for no other reason than rampant all access and security being fed up with it.

**Comment by PKPenguin321** [comment]
I appreciate what this is going for, but it impacts existing functionality with PDAs a bit much and the "access nuke" feature just seems way, way too easy to do. All access may as well not even exist with this

**Comment by PKPenguin321** [comment]
That aside though, if this goes through the PDA painter should be made into a PDA fabricator since they're now much more essential for even just basic access changes.

**Comment by zxaber** [comment]
I'm open to further restrictions. Someone did mention a requirement of red alert first, if that would help.

Ideally, it would be restricted to only being used when the only other option is giving up and calling the shuttle.

**Comment by Daxxed** [comment]
Just sounds like an easy way for a tider to guarantee he is the only one with all access.

**Comment by Teepeepee** [comment]
new meta will be stealing all access then using detomatrix cartridge to fuck over as many people as possible when they hit the big no more access button

**Comment by Teepeepee** [comment]
yeah it can already happen but you can avoid it by not putting your ID in your PDA, with this change even if you do that, once your PDA is gone and the no access button is pressed you're SOL, which inspires me to do it as tator

**Comment by PKPenguin321** [comment]
>lock it behind ID-swapper things you use to code red

This is a good idea

**Comment by lordpidey** [comment]
Also:  you should probably make sure cards upgraded by devil contracts should keep their access

**Comment by MrDoomBringer** [comment]
[**Link to PK's idea for those gamers who want to be in the know**](https://tgstation13.org/phpBB/viewtopic.php?f=9&t=21264&p=470540#p470540)

**Comment by Cyprex** [comment]
>This is intended to stop rounds ending for no other reason than rampant all access and security being fed up with it.
When does this actually happen?

**Pull request closed without merging**
