### PR TITLE
Adds a suicide_act to pens

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
I'm not sure what else I can say in the description

### CODE REVIEW

**Comment by xxalpha** [comment]
yes :1234:

**Comment by phil235** [comment]
:+1:

**Comment by Skrylar** [comment]
I chuckled.

**Comment by SconesC** [comment]
got a giggle from me

**Comment by as334** [comment]
:+1:

**Comment by francinum** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0CAcQjRxqFQoTCKna15XNksYCFYoRrAodGSwAeA&url=http%3A%2F%2Fgiphy.com%2Fsearch%2Fchuckle&ei=MD5_VamCOIqjsAWZ2IDABw&psig=AFQjCNHpQ31Iis5R6n9fCABLnhpHzQD7Nw&ust=1434488738990211

**Comment by freerealestate** [comment]
memes

**Pull request merged**
