### PR TITLE
Rebalances syndie and pirate simple animals.

### PR DESCRIPTION
**Pull request by WJohn**
I always felt these were kind of not terribly close to the real thing you'd experience when fighting these, so I changed them to be more accurate.

**Syndicate:**
-Melee
--100 hp, down from 170 (I could bump this up to 140 because of their 30% armor), melee minimum upped to 30 from 25 (always does 30). Armor pierce upped to 35 from 28 (same as regular esword.) Cannot freely move in space anymore.
--Space variant is unchanged. Can still move freely in space.
--Elite variant has 250 hp, down from 340 because that was absurdly durable when combined with their shield.

-Ranged
--Unchanged aside from loss of free space movement.
--Space variant has 170 hp, up from 100. Can still move freely in space.
--Elite variant has 250 hp, up from 200. Only fires one shot at a time as 3x buckshot burst fire is absurdly lethal.

**Pirate:**
-Melee
--Minimum upped to 30 from 25. Given armor pierce 35. Cannot freely move in space anymore. Reduced obj damage from 60 to default 40 (breaks structures less quickly when trying to get to you). Proper esword sounds.
--Space variant has updated sprites.

-Ranged
--Cannot freely move in space anymore, does not emit light anymore.
--Space variant has updated sprites. Can still move freely in space.

:cl: WJohnston
balance: Syndicate and pirate simple animals should have stats that more closely resemble fighting a human in those suits, with appropriate health, sounds, and space movement limitations.
imageadd: Pirates in space suits have more modern space suits.
/:cl:

Overall, this really shouldn't change how you go about fighting these all that much, just makes them a little more accurate to the real thing.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
they have a jetpack sprite they should move in space, also if they get baited in space they are fucked

**Comment by WJohn** [comment]
The space ones can still move around in space. The indoor ones cannot.

**Comment by 81Denton** [comment]
Removing rapidfire from ranged stormtroopers might make them weaker than regular troopers if you consider shot spread. 
IMO tweaking `rapid_fire_delay` that #39287 adds would be a better solution.

**Comment by WJohn** [comment]
They have increased health to compensate. 250 as opposed to the regular space one's 170. And yes, rapid fire delay is something I'm going to add once that one gets merged.

**Comment by Dorsisdwarf** [comment]
>nerfing melee npc mobs

are you high WJ, they're utterly pathetic already

**Comment by Bawhoppen** [comment]
IMO, we need to remove all simple-animal humanoids and replace them with something else.

**Comment by ExcessiveUseOfCobblestone** [comment]
Why do people use rebalance for nerf? Nothing was elevated because of this change.

**Comment by ExcessiveUseOfCobblestone** [comment]
Also the reason why they're beefed up is because they _aren't_ actual people and can be cheesed fairly easily.

**Comment by WJohn** [comment]
Further changes have been made. Ranged syndies now have a burst of 2 thanks to antur's changes (what a c20r can fire), and the elite shotgun syndies have a minimum distance of 3, meaning they will close the distance with you when they're about to fire which is *much* scarier. They do have an increased burst burst delay of 6, though, roughly the time it takes for a human to fire twice (leaning on the slow side).

Ranged pirates have also been dropped to 2 shots with a burst delay of 6 because they're easily the more dangerous type by a huge margin when firing a burst of 3 like that compared to melee ones. If you've got some suggestions on how to make these guys scarier without them completely breaking the rules of how players can actually fire guns, please let me know.

**Comment by 81Denton** [comment]
Dual wielding would definitely make them scarier. No clue if that can be done without spriting though.

**Comment by optimumtact** [comment]
`terribly close to the real thing`

what real thing, what crack pipe are you smoking from

**Pull request closed without merging**
