### PR TITLE
Zombie/limb refactors/fixes

### LINKED ISSUE #19969: Unable to cure zombism if zombified human is beheaded
Zombie code. I often play CMO as Delirium Faust. Encountered the zombie-code for the first time last night, figured out how to remove the tumor that causes Zombism. Unfortunately after a symptomatic victim of Zombism has been beheaded, it's impossible to reattach it to their body which makes curing the condition harder to treat with no logical reasoning. I'm speculating that the code converts the person into a playable mob or whatever, I ain't a coder so pardon my lack of knowledge here, that makes some surgical procedures impossible.

<i>(edited by phil235)</i>

### LINKED ISSUE #23783: Cutting off an infectious zombie's arm, then reattaching the arm doesn't give the zombie a claw back
I mean, this is an admirable attempt to circumvent the species restrictions.

### PR DESCRIPTION
**Pull request by QualityVan**
Fixes mounted chainsaws leaving a limb if acided
Adds species support for mutanthands, basically hard-equipped items like zombie claws
Fixes zombies not having claws on newly attached arms
Mobs manually set to zombie species revert to human when their infection is removed
Inserts organs back into the mob when a bodypart is reattached
No longer generates eyes or ears when a mob changes species without having a head
Gives zombies a claw when they somehow drop something from their hand

Fixes #23783, fixes #19969 (not really but it's fixed anyway and this'll make the bot close it)

### CODE REVIEW

**Comment by coiax** [comment]
@QualityVan could check for zombie claws after each life tick

**Comment by QualityVan** [comment]
Yeah but I really don't like that solution. I'll probably end up modifying human's doUnEquip.

**Comment by KingPhilipIII** [comment]
Stab people with your zombie stump.

**Comment by FantasticFwoosh** [comment]
Why not have zombie arms be a unique mutant race feature exclusive to romerol zombie transformations so its not obnoxious to swap arms with slime mutations?

> Check for zombie arm, if true perma equip the claw, cut off the arms and the zombie can't hurt you, equipping the zombie arm via surgery without a romerol organ just gives you the brute weapon?

**Comment by Razharas** [comment]
Id really prefer this to be a special limb instead of special item that is glued to normal hand

**Comment by QualityVan** [comment]
Razh, the thing about that is it opens up attaching regular limbs to infectious zombies when the initial problem was zombies being able to not have claws. It'd also open up the ability to put a zombie arm on an otherwise healthy person, which would be troublesome but possibly a feature. Or you'd have to create new arms every time one is attached or detached, which would be sad for frankensteining.

That being said, arms don't actually care at all about what they're holding at any point at the moment, so that'd be a bit of a refactor. 'Normal hands', as it were, don't exist.

**Comment by FantasticFwoosh** [comment]
Well all the claw does is inject romerol though from your 'production centre' in your head tumor doesn't it? So technically its a syringe arm/brute weapon.

Having a big claw arm isn't such a big or different thing if you wanted a ghetto armblade without emagging the limb grower.

**Comment by coiax** [comment]
It doesn't inject romerol, it implants a zombie tumour. The difference is that romerol doesn't work on dead people, while a zombie claw does.

**Pull request merged**
