### PR TITLE
Fixes singulos and reinforced floors

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Reinforced floors override the make_plating proc, and allow for a force flag to be sent to ignore their override. This flag wasn't being sent when the tile was pulled by the singularity, so it just spawned infinite rods.

## Why It's Good For The Game

I got bored, someone asked for a fix, so I did it. Also this is really stupid, and can cause hyperstrong balls really fast

## Changelog
:cl:
fix: The singularity no longer turns reinforced floor tiles into infinite rods
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
if you'd be so kind, add the force param to the rest of the procs too so folks don't override it with something else.

**Comment by LemonInTheDark** [comment]
Can do, it'll be just a bit tho, need to take a nap

**Comment by nemvar** [comment]
*poke*
still alive?

**Comment by Dennok** [comment]
Oh no. It must dont create rods instead of destroy reinforced floor. Problem in reinforced floor that create rods on unforced make_plating

**Pull request merged**
