### PR TITLE
Fixes some broken borg omnitools

### LINKED ISSUE #87641: Borgs wirecutters do not work on airlock wires ; borg cautery does not close surgery
### Client Version:

515.1645

### Issue Summary:

Spawn in as a medical borg.
Slam a human on your borg bed, open a tend wounds (brute) on em, run a step, try end the surgery with the cautery, get told "This step required a different tool!"

Similarlyish
Engi borg up to an airlock, screwdriver the panel open, try wirecuttering things, get told "You need wirecutters!"

### Round ID:

[241210](https://scrubby.melonmesa.com/round/241210)

### Test Merge Information:

- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

.

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
- Fixes #87641

TODO
- [x] Write unit tests for bog omnitool wrench
- [x] Write unit tests for bog omnitool screwdriver
- [x] Write unit tests for bog omnitool wirecutter
- [x] Write unit tests for borg omnitool crowbar
- [x] Write unit tests for borg omnitool multiool

Tests for engiborg omnitool for now

## Changelog
:cl:
fix: some broken borg omni tools should work again
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
Doesn't this break the new botany omnitools?

**Comment by Aliceee2ch** [comment]
yeah if you reverse it back to tool behaviour new botany omnitool won't work.

**Comment by SyncIt21** [comment]
> yeah if you reverse it back to tool behaviour new botany omnitool won't work.

This is a bug with your code then, why does tool behaviour break botany tools? After making changes to the core omnitool you should have retested everything.

I'll see what i can do

**Comment by Aliceee2ch** [comment]
> This is a bug with your code then, why does tool behaviour break botany tools? After making changes to the core omnitool you should have retested everything.
> 
> I'll see what i can do

botany omnitool won't work since your code using tool behaviour to display items and botany tools itself doesn't have tool_behaviour. tried to define new tool behaviours, but smartkar told we don't need new behaviours.
what if problem was in get_tool_behaviour string ive deleted?

**Comment by SyncIt21** [comment]
> botany omnitool won't work since your code using tool behaviour to display items and botany tools itself doesn't have tool_behaviour

I've kept your changes about displaying tool names & not their behaviours. That isn't a issue here the problem is tool behaviour is used for more than just displaying the name in the radial menu & when you deleted it the whole attack chain was effected.

I have not tested the botany tools yet and I'm pretty sure it will still work. I'll let you know

**Comment by Aliceee2ch** [comment]
alright, thanks for cooperation.

**Comment by Aliceee2ch** [comment]
hey, tested your code on local. yep, everything seems working as should be.
(including botany tools)

**Pull request merged**
