### PR TITLE
Adds much-needed enhanced crew entertainment :)

### PR DESCRIPTION
**Pull request by 00-Steven**
## About The Pull Request

Melbert's glorious new bitrunner streaming service has made progress by leaps and bounds in the crew entertainment sector
By its sheer existence, all of the crew's quality of life has been increased TREMENDOUSLY. For now they longer have to fluoride stare at their stock markets or xenobiology consoles, but can fluoride stare at the entertainment monitors instead!!
It's just the _perfect_ addition to our beloved streamer station 13.

And this, gave me _an amazing idea_.
Because, however great... 

### IT IS NOT ENOUGH.

Why limit ourselves to bitrunners? Really. What does a bitrunner do anyway?
Kill the same megafauna twenty times?
Have a downtime between runs of up to TEN MINUTES??
Die of brain damage, resulting in FOREVER DOWNTIME???

This simply cannot stand.
There is _much more_ entertainment to be found on the station!
_Much more_ thrills, _much more_ action!!
_Much more_ people to watch die of brain damage!!!

But, adding bodycams to _everyone_ would be ridiculous.
That's too many cameras to tab through, you simply wouldn't find any of the **ACTION**!
If we want action, there's three very simple categories that we need to look out for:

1. Security
2. Antagonists
3. Command (basically also antagonists)

So we add them.
_All of them._
**_ALL THE TIME._**

This is done by adding a new `bodycam_network` value to both job and antag datums, which defines whether a given job/antag should get a bodycam and on which network.
We then proceed to give them a bodycam and start broadcasting either on `after_spawn(...)`:
```dm
(code/modules/jobs/job_types/_job.dm, line 150-168)
/datum/job/proc/after_spawn(mob/living/spawned, client/player_client)
	(...)
	if(player_client && bodycam_network)
		spawned.AddComponent( \
			/datum/component/simple_bodycam, \
			camera_name = "[title] Bodycam", \
			c_tag = "[title] [spawned.real_name]", \
			network = bodycam_network, \
			emp_proof = TRUE, \
		)
		start_broadcasting_network(bodycam_network, null)
```
Or on antag datum `on_gain(...)`
```dm
(code/modules/antagonists/_common/antag_datum.dm, line 242-265)
/datum/antagonist/proc/on_gain()
	(...)
	apply_innate_effects()
	give_antag_moodies()
	give_antag_bodycam()

(code/modules/antagonists/_common/antag_datum.dm, line 371-383)
/**
 * Proc that assigns this antagonist's ascribed bodycam to the player.
 */
/datum/antagonist/proc/give_antag_bodycam()
	if(bodycam_network && owner.current)
		owner.current.AddComponent( \
			/datum/component/simple_bodycam, \
			camera_name = "[name] Bodycam", \
			c_tag = "[name] [owner.current.real_name]", \
			network = bodycam_network, \
			emp_proof = TRUE, \
		)
		start_broadcasting_network(bodycam_network, null)
```

For good measure, the RD, CE, and CMO telescreens include their own bodycams in addition to the department cams, and the bartender gets to see all heads at all times.

### The inherent problems

Now, however, this is an abnormal amount of shows to have on the station.
So it proceeded to show me an issue: whenever I added a second broadcast, spontaneously, the entertainment monitors would shut off. Only visually, but still off.
Looking into the code, this seemed to be caused by the following lines of code:
https://github.com/tgstation/tgstation/blob/0331c8eaf40b2bdd00942db981295804cda19fa9/code/game/machinery/computer/telescreen.dm#L70-L74
If it's supposed to be on and the icon is off, it turns on! But, it it's on and the icon is on, it ALSO turns off.
For maximum crew pleasure, we also haphazardly solve this by just adding a second check.
```dm
/obj/machinery/computer/security/telescreen/entertainment/proc/notify(on, announcement)
	if(on && icon_state == icon_state_off)
		icon_state = icon_state_on
	else if(!on && icon_state == icon_state_on)
		icon_state = icon_state_off
```
And, sadly, I was not able to find the time to include donation messages. I know, it's truly a shame.

That's all. That's all the problems. Truly.
Please enjoy your onboard 24/7 crew entertainment.
## Why It's Good For The Game

See, to move the story along, we have all these antagonists causing problems and security _also_ causing problems.
However! Sometimes, as your normal everyday crew, you will never encounter these problems! And that's clearly _oh so boring_!!

With this pr, we seek to resolve any and all issues one may have, by simply bringing all these problems directly to YOU, the CREW!
## Changelog
:cl:
balance: For enhanced crew entertainment, we have added more 'shows' to watch on the entertainment monitors. Use holochips on these monitors while adjacent to send donation messages!
fix: Fixed the entertainment monitor having its visuals get toggled each time a new broadcast was added.
/:cl:

### CODE REVIEW

**Comment by Rhials** [comment]
Finally, a way to observe while still racking up living hours.

Maybe the entertainment monitors shouldn’t be usable by people who have a camera in them?

**Comment by atlasle** [comment]
this would be a great feature if it was something that miners had by default

**Comment by 00-Steven** [comment]
> And, sadly, I was not able to find the time to include donation messages. I know, it's truly a shame.

I lied.

**Comment by uaioy** [comment]
finally i can donate to my favourite space streamers

**Comment by NanoCats** [comment]
> finally i can donate to my favourite space streamers

Honestly I wish someone had added donation effects as an april fools joke, donate credits to help or hurt the bitrunners.

**Comment by ophaq** [comment]
This shouldn't be april fools. This needs to happen as an official thing.

**Pull request closed without merging**
