### PR TITLE
kilo without hostile mobs

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

for testing purposes
mobs still in:
hos' carp and birdboat since they didnt seem to do much on other maps

## Why It's Good For The Game

we tryna figure out why kilo crashin

## Changelog
:cl:
add: kilo without mobs
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Bold.

**Comment by EOBGames** [comment]
> Bold.

well I suppose time will tell if this is bold and brash, or if it belongs in the trash

**Comment by Jared-Fogle** [comment]
image

at least ur honest

**Comment by Tlaltecuhtli** [comment]
only way this goes in if it replaces toxins test site on meta

**Comment by TreyWJ** [comment]
Would also like to mention that HoS’s pet immediately starts attacking anyone near him. Not sure about the others.

**Comment by EOBGames** [comment]
boldandbrash
What a shame

**Comment by NamelessFairy** [comment]
Few <ins>minor</ins> issues I found during the first round of the test merge on Terry.
<br>
Floating air alarm west of SM chamber.
image
<br>
All maint gas flow meters have connection errors. 
image
<br>
Pipe on the wrong layer in north toxins maint.
image

**Pull request closed without merging**
