### PR TITLE
Metastation: Added working drone shell dispenser to Showcase

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: A working drone shell dispenser is now on display in MetaStation's museum, displaying the virtue of the tireless little workers!
/:cl:

Metacide said it was cool.

### CODE REVIEW

**Comment by Metacide** [comment]
Lovely. :+1:

**Comment by Bawhoppen** [comment]
:-1: don't add it to the showroom

**Comment by coiax** [comment]
Metacide suggested the location. Take it up with him.

**Comment by Metacide** [comment]
After this gets added I'll add a few things of my own. If it doesn't comfortably fit there I can easily move it to research storage (maint east of break room) as coiax originally suggested, or the foyer, or wherever.

**Pull request merged**
