### PR TITLE
Make Lathe Design Names Capitalized Consistently

### PR DESCRIPTION
**Pull request by Penguaro**
:cl: Penguaro
tweak: The Design Names in the various machines are now capitalized consistently
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
As I was doing another PR, I saw that item names in the different fabricators were inconsistently capitalized.  Some were lower case, a mix, or all upper case. I just went through and made them all upper case like a title.

### CODE REVIEW

**Comment by XDTM** [comment]
Thanks, this always irked me

**Comment by Penguaro** [comment]
@XDTM Me too.

**Comment by ExcessiveUseOfCobblestone** [comment]
Thanks, this Always irked Me

**Comment by Penguaro** [comment]
@ExcessiveUseOfCobblestone Me too.

**Comment by lzimann** [comment]
Conflicts!

**Comment by Penguaro** [comment]
@lzimann Good to go...

**Pull request merged**
