### PR TITLE
Medical borg fix

### LINKED ISSUE #82709: Medical Cyborg upgrades stack
Reporting client version: 515.1636

## Issue Summary
Some medborg upgrades can be added to a borg multiple times, resulting in unintended effects.

Expanded hypospray: Each chem added refills to 30u, 5u at a time, but can go to 34u if it refills at 29u. Each expanded hypo adds 31u to the amount of each chem, resulting in me having 340u of each chem added by the expanded hypo. Very enjoyable, very useful, but the only ODs you have available from those chems are lackluster.

Piercing hypospray: Functionally no effect. You can have unlimited extra piercing hypo upgrades, but they have no effect unless you are hacked. A second piercing hypo makes your hacked hypo piercing, no effect from third piercing and beyond.

Defib: It's just extra defibs. This allows you to easily bypass the cooldown on defibs. With the defib wind up, there is no use for more than 2 defibs.

Surgical processor: Extra surgical processor. Unknown if they each have their own set of surgeries.

## Round ID:
[227334](https://scrubby.melonmesa.com/round/227334)

## Testmerges:
- [Alt click refactor](https://www.github.com/tgstation/tgstation/pull/82656)
- [Reworks targeting behavior to fall back onto proximity monitors. Refactors ai cooldowns a bit](https://www.github.com/tgstation/tgstation/pull/82640)
- [Makes the AI Controller subsystem use spatial grid instead of looping clients](https://www.github.com/tgstation/tgstation/pull/82686)

## Reproduction:
Be a medborg, just uh... Stick a bunch of copies of each module in yourself. It doesn't appear to be an issue with any modules not listed, and I did test each module, excluding illegal upgrades and borg expander.

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Closes https://github.com/tgstation/tgstation/issues/82709
## Why It's Good For The Game
bug fix
## Changelog
:cl: grungussuss
fix: fixed being able to install multiple of the same upgrade to medical cyborgs
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
nitpicking but why is the comment about the checking for already having the upgrade on the tochat and not the actual check for already having the upgrade?

**Comment by Sadboysuss** [comment]
> nitpicking but why is the comment about the checking for already having the upgrade on the tochat and not the actual check for already having the upgrade?

I could change it I guess if it bothers you lol

**Comment by ExcessiveUseOfCobblestone** [comment]
dw abt it im a sick freak

**Comment by Stiix72** [comment]
*cries in 360u rezadone hypospray*

**Pull request merged**
