### PR TITLE
Touches up the new toolboxes (increases toolbox size :D)

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin addressing a few criticisms:
-Makes its handle colored now, so bye bye silver handle
-The latch is now more cubical in shape
-Adjusted the shading
-Made them a bit bigger
image

Sprites done by @maxymax13 (thank you)

## Why It's Good For The Game
@ playerbase let us break bread and make amends

## Changelog

:cl: Kokonut (Maxymax13)
imageadd: Touches up the new toolboxes' appearance.
/:cl:

### CODE REVIEW

**Comment by MrStonedOne** [comment]
jesus christ what the fuck is that title

=P

**Comment by Imaginos16** [comment]
> jesus christ what the fuck is that title
> 
> =P

[#24001](https://github.com/tgstation/tgstation/pull/24001l)

**Comment by Burgermancoding** [comment]
very cool gamer

**Comment by Serxule** [comment]
they actually look like ss13 toolboxes, praise the toolbox lord

**Comment by VladinXXV** [comment]
The initial resprite was awful imo, but these are much better. Question, though. There's what I can only assume to be a "sparkle" in the corner of the ascended His Grace. Is that static, or animated?
image

**Comment by optimumtact** [comment]
we cannot keep going through this cycle

**Comment by Twaticus** [comment]
> The initial resprite was awful imo, but these are much better. Question, though. There's what I can only assume to be a "sparkle" in the corner of the ascended His Grace. Is that static, or animated? image

its animated. if you go to the checks tab at the top of the pr > icondiffbot > diffs - pull request > then open the dropdown under details, you can see direct comparisons and animations
image

**Comment by Sealed101** [comment]
still no triple latches in sight :(

**Comment by Imaginos16** [comment]
> we cannot keep going through this cycle

History repeats itself…

**Comment by Ryll-Ryll** [comment]
@Twaticus seemed to approve this at https://discord.com/channels/326822144233439242/326849939240124419/934990566775742504 and the change looks unanimously liked

**Pull request merged**
