### PR TITLE
Reverts Canister Wiring (#80265)

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Reverts #80265

It's a cool idea, but the ability to toggle valves/control pressure make this just a ttv but without the access issues we tie to that.
Eats into that space way too much.

Removing those but not the rest results in disappointment, so I'm just full removing this.
I am keeping the code quality changes, screentips, that sort of thing tho. That bit goes hard.
Also, refactored a few procs slightly to make them easier to read. Early returns, sane loops, etc.

## Why It's Good For The Game

Closes #80604
Cheap remote mass producible maxcaps are a bad idea actually
Sorry I didn't catch this in review, been resting for the week

## Changelog
:cl:
del: Removes the wires from canisters. It's a cool idea, but cheap controlled maxcaps are bad actually
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Review by Ghommie — APPROVED** [review]
immagine

**Comment by RikuTheKiller** [comment]
But it *isn't* a TTV.

It doesn't mix gas. You can't put it on your back.

And also these are less mass-producible than TTVs themselves.

**Comment by LemonInTheDark** [comment]
> It doesn't mix gas. (unless you literally get a hypernoblium crystal)

What does this mean

**Comment by Pickle-Coding** [comment]
> 
> 
> > It doesn't mix gas. (unless you literally get a hypernoblium crystal)
> 
> 
> 
> What does this mean

They're probably thinking of putting a singlecap mix inside a hypernoblium shielded canister. That's not necessary though, and is impractical. They can just put the fuel in the canister and the oxidiser in the oxygen tanks.

**Comment by Jackal-boop** [comment]
Maintainers knee-jerk revert?

**Comment by Deadgebert** [comment]
if you remove the ability to toggle valve or adjust pressure if a tank is inside the canister, the issue goes away

**Comment by SovietJenga** [comment]
after testing this in a real round you can in 20 minutes just make trit. heat the trit and oxy to 374 kelvin have trit in tank, oxy in canister and it will maxcap. its easily mass producible too.

**Comment by Jackal-boop** [comment]
> after testing this in a real round you can in 20 minutes just make trit. heat the trit and oxy to 374 kelvin have trit in tank, oxy in canister and it will maxcap. its easily mass producible too.

You can make a standard toxins maxcap in 20 mins aswell

**Comment by SovietJenga** [comment]
> You can make a standard toxins maxcap in 20 mins aswell

the problem is that unlike toxins maxcap i can make like 20 of these easily while toxins has like 5 and takes time to get more ttvs

**Comment by F-e-r-n** [comment]
I feel like just making canister wiring not work with a tank inside would be a better fix as it would still allow you to do timed release systems and could add more flavor to deathtrap builders and maybe help with some obscure atmosian nonsense.

improve dont remove yadda yadda yadda let me gas assistants in maints

**Comment by optimumtact** [comment]
The person who made the original PR was either knowingly making bombs easy to achieve in a canister, or didn't think through their PR enough.

either way it's on them to repair their PR and retry it.

**Comment by OverwatchVoice** [comment]
Nobody could've seen this coming

**Pull request merged**
