### PR TITLE
[Birdshot] Dorms Remap and Station Aesthetic Cleanup. 

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

Apparently I need to draft this right now to prove that this station still gets worked on.

The PR body will be a continuation of Monday's (March 27th 2024) maintainer bus discussion starting from here 
https://discord.com/channels/326822144233439242/808425762217656330/1244682970632163400

I hate having to link stuff to get a conversation going on with this whole thing when the topic is apparently about me not putting in enough evident work to a project of this repository, and in order to actually be involved in it. I have some strong words towards what occurred, but this isn't the place for them. Instead, I have the joy of finishing my Memorial Day weekend writing the defense for the trial of one **Birdshot Station**.

So let us get down into it, yeah?

Screenshot 2024-05-27 222957

Nobody in a position of responsibility, has made an effort to talk to me about Birdshot Station beyond the initial PR and the Engineering Update that went live this April. At best any of this is speculation based on my responses to the player bases tendency to hate on the map, at worst, it's made up. 

I Vekter has been the only one to really check in and even then not a whole lot of information regarding the station was acutally exchanged. 

Screenshot 2024-05-27 223531

People have sent me threats via discord over Birdshot station. These attitudes will likely never improve. I have weathered this slew of shit from day one. Early on I decided to take it all on to figure out how to sort any tangible feedback into smaller usable nuggets that when gathered together can marry my own goals for the station with a compromise. 

https://tgstation13.org/phpBB/viewtopic.php?f=11&t=33159

Most of the complaints in the thread were regarding engineering. Those ones got addressed when Engineering got its change. When I checked the Issues thread at the beginning of this month, Birdshot was 100% clear on issues. I have asked people time and time again to provide feedback in the respective forums/discord channel if something needs more immediate attention. 

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=35503&p=719169&hilit=Birdshot#p719169

This is a hate thread. I read through the whole thing during January and couldn't find anything that was actually going to be helpful to the improvement of the station. 

Screenshot 2024-05-27 224932
Bullshit.

Screenshot 2024-05-27 225050

After the engineering PR, I thought about why maps like Delta, Meta and Icebox have been successful long after their creators stopped working on them. It basically comes down to people like me coming along to add their own spin on it. People have been recently asking around about if they too can work on Birdshot, such as in this collection of messages on the 26th. 
https://discord.com/channels/326822144233439242/782914977874837515/1244757014723297310
There are people who earnestly want to improve Birdshot but are hesitant to do so because they think they will trample on my vision. Maybe they will, but why should that matter? When I PR'd Birdshot station I accepted that I would be handling over creative control to the contributor base. In the past month I've been trying to encourage others to modify what they want on the station. It's good for the community, it also helps me get even better ideas. **It shouldn't even be a question as to weather or not people can contribute to /tgstation/13.**

Screenshot 2024-05-27 225746

Listen, when I saw how controversial this station was, I accepted that it would probably get removed. I had a whole roadmap worked out and everything, yet for the first 6 months, life hit me hard. Even after that, I spun mud on the engineering changes as things just didn't do the station justice. Dozens if not Hundreds of hours of work, gone. I was happy to see a strong base of people that actually like the map, and the they kept it going for as long as it did. Thanks them, I actually was able to get out the engineering changes, and now I've been working on an overhaul that effects basically half of the station. It's a huge project, which is why people shouldn't feel like they're getting in my way. 
Further more I won't be insulted if you come out and simply say **"Hey, Birdshot isn't really a fit for where we want to take /tgstation/"**. Creative differences happen all the time. It is what it is. 

**What I will not accept are statements such as this.**

Screenshot 2024-05-27 230431

You cannot justify removing a station based on a conversation that has never happened. **This is insulting.** 
It wouldn't even matter what station was getting removed. It could be Birdshot or Metastation or Tramstation. The converstation with me never happened. If you want the station gone, just say you want it gone. 

Of course I owe it to the promise I originally made when I PR'd this station. That I would support this station until its death, hence this PR. 

Furthermore I genuinely want to have a conversation about this. I actually think it needs to happen at this point. This whole ordeal never would have happened if people just sat down and talked about the status of things. Lets talk about your wants and my wants. Collaboration opens new doors, and would do quite a bit to assuage concerns resulting from this whole thing. 

Screenshot 2024-05-27 231512

I should hope that Dorms counts, it was the worst part of the mess-ification of the station. Personally this isn't up to my normal standards, since I've been busy figuring out how Science should overlay in this space. That being said, I did say that I'd figure out a short-term dorms rework to someone at some point to bridge that gap. It's a shame that I have to rush this, but it seems like the station is on its way out if I don't do this. 

Anyways. That's what I have to say about this whole thing. I tried to say something in discord but I went ignored. I've also talked about things with people in some private channels. I've said enough here.

## Why It's Good For The Game

There are people who don't like Birdshot. There are people who like Birdshot. A common complaint from both sides was basically about the scattered floor tiles and the damaged floors/plating throughout the station. Another common complaint was on the topic of how dirty the station was. I'm not going to show the whole station map, but I've gone through and removed the enshittifcaiton tile by painstaking tile. Things on average should look nicer now, and a great deal less destroyed too. Windows are fixed, tables are now built. It looks a lot less like Detroit.

The big part of this change basically comprises of the 8 or so hours I spent rushjobbing a new layout for dorms. It's not my best work, but I'm satisfied enough with it to let it be a holdover for when Science will be moved there in the future. 
Screenshot 2024-05-27 194424
This is the WIP screenshot. The layout is done, but I need to spend a another day or two decorating and getting the essentials like wall mounts working. At which point, I'll undraft the PR.

I'm just going to talk about the future of the station now, since I want to clearly communicate what I intend to do. Dorms will become a Satellite connected to the station with Birdshots 3rd Tram. Science will relocate to the area that Dorms currently occupies, but some of it will also be on that Dorms Satellite. I have 0 clue what will be split up, but I'll do my best to make it work. Maint bridges and transit tubes will satisfy the other connection necessities. Some other things will happen along with this change as well. Arrivals will find isolation on the Dorms section, Medbay will expand, and the main station will shrink, but be a concentrated area of the primary jobs. 
Basically, we're going to be changing Command, Science, Dorms, Medical, Service, and other tiny things. 
It's a monumental task. I'd like to break it into chunks, but the Science and Dorms swap hits so much as collateral that it's just better to do it all in one go. 
Needless to say, it'll take some time. That doesn't mean I wont be free to work on things that are more important though. If things break or need to change, let me know so I can do 'em, or better yet, feel free to make your own mark on the station. Just because I have this big roadmap doesn't mean your work is going bye bye. It might be another year before I get to security, and in that time, someone might just do better than what I could. Same goes for any area on the station. I might incorporate science changes into the floorplan because the creators did such a great job. Sure, I'm doing my own thing, but that shouldn't discourage people from doing their own thing. The contributor base and collaboration are what have historically what have made /tgstation/ a fun game. 

## Changelog
:cl:
qol: Many Janitors have cleaned up Birdshot station. Permanently. 
qol: Loose floortiles on Birdshot Station have been properly affixed to the floor by the Engineering and Atmospherics Teams. 
fix: Birdshot Dorms have been reworked and incorporated the Holodeck Ship as an actual and permanent installment. Come visit our new and improved barber shop!
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
I really like birdshot and I don't understand all the hate towards it, good luck to you with your changes I hope you can get it back into rotation, tell me if I can help in any way, I have mapping experience.

**Comment by TheVekter** [comment]
I'm sad to see my "shuttle slammed into the side of the asteroid" holodeck go, but I get why that change probably needed to be made.

DM me on Discord if you want some help working on this. My tile placing game is unmatched.

**Comment by Deadgebert** [comment]
can i suggest making atmos usable too?

**Comment by TheVekter** [comment]
> can i suggest making atmos usable too?

Can you provide specific feedback? This isn't very helpful.

**Comment by Deadgebert** [comment]
> > can i suggest making atmos usable too?
> 
> Can you provide specific feedback? This isn't very helpful.


The main issue is the amount of workspace. Provide space for players to make their own projects, forcing people to dismantle walls to access extra space is too time consuming.

70e89e3ef85113a6b2ad49f64d7f6e23
if this is going to be treated as the primary way atmos techs are going to be getting gas, i'd suggest spacing them out a bit more and color coding
there should either be a mixing line or nothing from supply (picture above shows supply with pump instead of mixers). Current 'pure' line doesn't have much value and is often ignored or removed entirely.
it would be nice if the pipes were cleaned up a little, but it's not really necessary. 

I know zytolg doesn't like metamos, but it's pretty necessary. Keep things simple for the players, give lots of room, don't make things tedious. Rounds do not last very long and atmos stops working very quickly into a round, that extra time spent is too precious. The current iteration of the atmos department feels more intentionally time consuming than it does unique.

**Comment by EEASAS** [comment]
We are so back birdbros

**Comment by EEASAS** [comment]
Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/commons/fitness/recreation/entertainment) at Entertainment Center (147,167,2)! Please ensure that all space turfs are in an /area/space!
  Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/holodeck/rec_center) at Recreational Holodeck (145,168,2)! Please ensure that all space turfs are in an /area/space!
  Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/holodeck/rec_center) at Recreational Holodeck (146,168,2)! Please ensure that all space turfs are in an /area/space!
  Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/commons/fitness/recreation/entertainment) at Entertainment Center (147,168,2)! Please ensure that all space turfs are in an /area/space!
  Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/holodeck/rec_center) at Recreational Holodeck (141,169,2)! Please ensure that all space turfs are in an /area/space!
  Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/holodeck/rec_center) at Recreational Holodeck (142,169,2)! Please ensure tha

**Comment by Sadboysuss** [comment]
> Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/commons/fitness/recreation/entertainment) at Entertainment Center (147,167,2)! Please ensure that all space turfs are in an /area/space! Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/holodeck/rec_center) at Recreational Holodeck (145,168,2)! Please ensure that all space turfs are in an /area/space! Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/holodeck/rec_center) at Recreational Holodeck (146,168,2)! Please ensure that all space turfs are in an /area/space! Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/commons/fitness/recreation/entertainment) at Entertainment Center (147,168,2)! Please ensure that all space turfs are in an /area/space! Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/holodeck/rec_center) at Recreational Holodeck (141,169,2)! Please ensure that all space turfs are in an /area/space! Error: Space turf /turf/open/space/basic found in non-allowed area (/area/station/holodeck/rec_center) at Recreational Holodeck (142,169,2)! Please ensure tha

it's wip let him cook

**Comment by Zytolg** [comment]
Don't worry about errors until the PR is undrafted. This PR was made in an early state due to the situation described in the PR Body. I'm working on it as I have time in the work week, so it'll be done closer to the weekend. There's a ton going on.

**Comment by EEASAS** [comment]
> Don't worry about errors until the PR is undrafted. This PR was made in an early state due to the situation described in the PR Body. I'm working on it as I have time in the work week, so it'll be done closer to the weekend. There's a ton going on.

my bad :3c :3c :3c :3c

**Comment by DaydreamIQ** [comment]
Well if you really want general feedback, the fact so many places have regular windows instead of reinforced ones makes tiding such a pain in the ass. Like look at cargo for example
image
One dude with even a weak weapon like a crowbar could bust his way all the way into the QM's office without much effort

**Review by Maurukas — CHANGES_REQUESTED** [review]
This is a big delicious expansion of dorms. It opens it up a lot more as a place for player interaction, and it feels a lot less like an abandoned dead end that's an extension of maintenance. It's practically a small kingdom, and you could fortify it pretty well if you put your mind to it. It also provides some nice public connectivity between parts of the station that weren't very well connected before.

Isolated powernet in the Janitor's sweet new closet:
image
 
Suggestion: open up the holodeck with a few more windows. You've made the holodeck the centerpiece of this area, so you might want to open up its lines of sight a bit more:
image


One concern: You're giving up a lot of maintenance to do this expansion, and you're starting to develop a bit of Pubby Maintenance syndrome in this area. You've got a big expansive internal area surrounded by a tiny, crustlike corridor of maint. It doesn't have to be in this PR, but you may want to consider expanding maint to the north east in a future one.

**Comment by Zytolg** [comment]
Yeah, Maintenance will return in the future science update. I'll get the windows and powercables in

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
