### PR TITLE
Plushie love

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: You can now make plushies kiss each other!
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
freeze

**Comment by MoreRobustThanYou** [comment]
no techweebs got merged

**Comment by praisenarsie** [comment]
TEST IT
TEST IT
TEST IT
TEST IT
TEST IT
TEST IT
TEST IT
TEST IT
TEST IT

**Comment by lzimann** [comment]
Snowflake check for a stupid message. Use an emote or some shit instead of this.

**Comment by MoreRobustThanYou** [comment]
@lzimann fuck off leo

**Pull request closed without merging**
