### PR TITLE
Adds inhand improvised shotgun sprites

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Finally adds unique sprites to the improvised shotgun

## Why It's Good For The Game

improvised shotguns haven't had unique inhands for a while now so i decided to give them some unique ones.

## Changelog
:cl:
imageadd: Added inhands to the improvised shotgun.
/:cl:

image (hook shotguns gone)

### CODE REVIEW

**Comment by optimumtact** [comment]
power creep

**Review by actioninja — CHANGES_REQUESTED** [review]
split the inhands into a separate PR I'm not sold on the hook shotgun but the sprites look fine.

**Comment by Tlaltecuhtli** [comment]
weird //e comments also whats the purpose of this “hooker shotgun”?

**Comment by tralezab** [comment]
non atomized pr :^(

**Comment by carlarctg** [comment]
> weird //e comments also whats the purpose of this “hooker shotgun”?

i thought i removed those

"hooker shotgun" because i thought it'd be a neat idea. but i'll split the PR since ninja said so

**Comment by carlarctg** [comment]
> split the inhands into a separate PR I'm not sold on the hook shotgun but the sprites look fine.
@actioninja done

**Review by actioninja — DISMISSED** [review]

**Comment by carlarctg** [comment]
uh, what was in that review? didn't check the pr before committing and can't figure out how to view it now

**Comment by actioninja** [comment]
nothing I just fucked up, it was supposed to be an approve review.

**Review by actioninja — DISMISSED** [review]

**Comment by carlarctg** [comment]
fuck fuckity fuck fuck

someone make a pr to decentralize items and weapons please

**Comment by carlarctg** [comment]
uuuuuuuuuuuuuuuuhhhhhhhhh

**Comment by carlarctg** [comment]
merge conflicts (probably) fixed, which coincidentally made me remove some cross-branch contamination

thank you merge conflicts

**Comment by actioninja** [comment]
nice commits

**Pull request merged**
