### PR TITLE
Adds the vomit goose tshirt

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds the vomit goose tshirt

## Why It's Good For The Game

the assistant mascot needs some merch

## Changelog
:cl: Fikou
add: Nanotrasen Merch Co. has created a shirt for Birdboat, the assistants' mascot!
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
what the heck how did those stockings appear

**Comment by Tlaltecuhtli** [comment]
shouldnt have prd with your programmer socks on

**Comment by Krysonism** [comment]
I like geese.

**Comment by SgtxRootbeer** [comment]
Can we get an image?

**Comment by Fikou** [comment]
> Can we get an image?

click checks it shows the icon from icondiffbot

**Comment by plapatin** [comment]
my name is plapatin and i approve this pr

**Comment by YakumoChen** [comment]
is the goose the new bee meme

**Comment by Jordie0608** [comment]
I detest this meme, fight me nerds.

**Comment by Detective-Google** [comment]
>meme bad unga me close pr

Sure would be awkward if everyone just shit on someone making a 'meme bad unga' removal pr :^)

**Comment by Jordie0608** [comment]
geesebusters

**Pull request closed without merging**
