### PR TITLE
The supermatter will no longer irradiate mobs on other zlevels when it explodes.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Also fixes potentially being able to use rad collectors on... other zlevels to collect power from the supermatter or the singularity.
More bad use of get_dist()!

### CODE REVIEW

**Comment by KorPhaeron** [comment]
can we not change get_dist to check for z or is that a byond proc

**Comment by ChangelingRain** [comment]
I mean there might be a way to do it but that's not my area

**Comment by Jordie0608** [comment]
@KorPhaeron Yes it'd just be overriding the proc like any other.

**Comment by xxalpha** [comment]
Stop fixing this and report it on byond forums.

**Comment by RemieRichards** [comment]
@xxalpha nothing to report, it's correct.

```get_dist(locate(1,1,1), locate(1,1,2))``` returns 1, which *IS* correct, you're 1 above/below.

**Comment by xxalpha** [comment]
Should return -1 or something. Spatially it doesn't make sense to say two things in two different z levels are close to each other.

**Comment by RemieRichards** [comment]
@xxalpha in 3 dimensions, they are.
from what I know of DM functions involving coordinates there's some kind of datastructure that holds them, that has to be unpacked (Lummox's words), my guess is that ```get_dist()``` is literally just (written in DM cos fuck U I don't know C++):
```
/proc/get_dist(atom/A, atom/B)
    var/list/Acoords = unpackcoords(A.coords)
    var/list/Bcoords = unpackcoords(B.coords)
    return (abs(A["X"]-B["X"]) + abs(A["Y"]-B["Y"]) + abs(A["Z"]-B["Z"]))
```

**Pull request merged**
