### PR TITLE
Revert "Forcing the human liver to actually do its job v2"

### PR DESCRIPTION
**Pull request by 81Denton**
#37032 makes toxins cause liver failure. 
I assume it hasn't been tested, since ANY toxins, even the non-damaging or super low potency ones, will cause it now.

Examples:
1) Sleepypens straight up murder people
2) Peacekeeper borg dizzying/tiring solution quickly give people liver failure and kill them
3) TOXINLOVER species receive liver failure the same way, even though they're supposed to be immune to toxin damage
4) Another example: Mindbreaker toxin also causes liver failure.

This needs to be done differently, maybe go by ToxLoss received instead of just having toxins in your system.

Closes: #37164

### CODE REVIEW

**Comment by DaxDupont** [comment]
High priority

**Comment by vuonojenmustaturska** [comment]
As you've identified the problems with the current approach, I **very highly** recommend that you fix those problems instead of reverting the codebase to a broken state. 

For toxinlover species, unless the liver already interfaces with species data, I recommend making a subtype of a liver that gets assigned for TOXINLOVERs that removes the toxin purging functionality.

For the liver damage scaling, I've got no idea what is good but Winterous on discord had this to say:
image

You are of course free to choose which way is best.

**Comment by RandomMarine** [comment]
>I very highly recommend that you fix those problems instead of reverting the codebase to a broken state

It's a broken state regardless. Difference being this one changes it to broken without a gamebreaking issue at large.

**Comment by Barhandar** [comment]
It's far better to revert and then code working solution from scratch than to keep all-toxins-murder while trying to figure out how to fix that.

**Comment by 81Denton** [comment]
@vuonojenmustaturska I don't know enough about DM to fix it myself; someone else would have to do it.
It would still be broken after the revert, but people wouldn't die left and right at least.

**Pull request closed without merging**
