### PR TITLE
Prevents law uploads to AIs that are not in a core

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Creates a new AI select proc called "select_active_cored_ai", which filters out AIs that are not in a core before returning what "select_active_ai" would otherwise return. Replaces the latter proc with the former in the AI Upload code.

## Why It's Good For The Game
This is a two-birds solution to both situations where someone is law-spamming the AI, and situations where you _know_ someone nefarious has the boards for an Upload.

If someone is spamming the AI with nonsense laws, carding the AI will allow it some peace of mind while you deal with finding the uploader. You can core the AI momentarily, when you're ready, to reset the laws to something more coherent, and meanwhile give the AI a shell so that it can help out with tasks even if it cannot access cameras.

On the other side of things, if you know there's a traitor that has an upload, and you know they're going to upload harmful laws, the only current solutions you have are to camp an upload of your own, giving the AI Asimov every minute or so, or else killing the AI to prevent law changes (You can also send them to Lavaland, but seeing as a fix for this was merged, though it didn't work, I would consider this strategy a bug). This should only come into play if the uploader has been rather open about their intentions, or if a prior law change happened and was reverted. If the uploader in question has been stealthy about their actions, this PR shouldn't change much. Keeping an AI in a card has several downsides, and I would suspect the heads of staff would prefer the AI is able to track suspects or keep an eye on their borgs.

## Changelog
:cl: Zxaber
balance: AIs can no longer receive law changed from uploads if the AI is not in a core.
/:cl:

Alternative (or addition to) #43066. Doesn't help finding the uploader, but does make their upload useless for the short-term. Technically, you could already accomplish this by simply having the wireless off, but that prevents AIs from using shells. Ideally, I'd like to allow the AI to do _something_ while it's carded besides watching the captain do whatever captains do.

One of the concerns with 43066 is that it'll affect traitors more than intended. While this PR actually does cite traitors as part of the reasoning, I don't think it'll affect most subversions. Since, carding the AI means losing all the benefits that an AI brings, I think it'll only come up if the crew resets the AI, and there's reason to suspect that it's just going to be subverted again.

Finally, full disclosure, this does affect AIs in mechs, too. However, I believe that mechs are, or should be, balanced independently from this, and there are viable ways to attack an AI-controlled mech that don't include law changes. As I've said before, any traitor roboticist that abuses this could just as well have brainwashed people into following his orders and had them pilot the mechs instead (and in fact, could order them to build the mech too, freeing the robo up for doing other things).

### CODE REVIEW

**Comment by adamkad1** [comment]
now lets nerf any nonroundstart upload consoles to not be instant

**Comment by Pandemonium1778** [comment]
This is a change I can fully get behind, seen quite a few poor AI players have to suffer the back and forth conflict of two people spamming different lawsets at different uploads.

The only other thing I'd really like to see in addition to this is a way for players to track where an upload originated from, it's a definite pain when someone uses an abandoned area in maint to spam new laws to the AI with very little possibility for retaliation barring a thorough hunt for the alternative upload.

**Comment by 4dplanner** [comment]
Does this disable the traditional card ai, upload laws, use as pAI route?

**Comment by zxaber** [comment]
Only in that you can't change the laws while it's in a card. Either change the laws beforehand, or if you're building the AI from scratch, swipe the law boards on the core with the wires showing before you stuff the brain in, and the resulting AI will be pre-equipped with your laws.

**Comment by MrPerson** [comment]
TODO: Allow using AI Upload modules on an intellicard directly. Out of scope for this PR ofc

**Comment by wesoda25** [comment]
Isn’t this a thing already?? I know I’ve tried to upload laws to a carded AI before and it didn’t work.

**Comment by zxaber** [comment]
Currently, if wireless is disabled, you can't upload laws to the carded AI, but if they have wireless enabled, you can. This change makes it so that you can't upload to a carded AI even if wireless is enabled.

**Comment by wesoda25** [comment]
Whats the point then? Just disable wireless

**Comment by Cyprex** [comment]
I greatly disagree with this PR. Law uploads to carded AIs don't really do anything(The AI can't do anything with it anyway) and let you see the law changes in action, with this PR someone uploading laws can see that the AI was carded. Furthermore, how are you supposed to fix an AIs laws after carding it? If you really want to do this, make it so the person possessing the card can still upload laws somehow.

**Comment by zxaber** [comment]
@wesoda25
If wireless is off, the AI can't use a shell, or operate doors, or really do much of anything. The point of this is to allow the AI to do things while keeping it shielded from law changes.

@Cyprex
Law changes affect borgs too, and so saving the AI from the headache (and lag) of law spam also saves their borgs. Meanwhile, if you know an upload is about to be built, and you card the AI quickly enough to beat them, the borgs don't get subverted either.

Once you have the AI safely carded, you can coordinate with the Captain or RD to do a quick law change, or move the empty core to near an upload and do it yourself.

You are the second person to request applying laws to a card directly. No promises, the code for law changes is a bit messy, but I'll see what I can do.

**Comment by Cyprex** [comment]
Carded AIs can operate shells if wireless is on?

**Comment by Cyprex** [comment]
@zxaber This would likely be a terrible hack, but you might be able to check if a carded AI is present nearby for law changes

**Comment by zxaber** [comment]
Carded AIs can indeed operate shells if wireless is on.

For uploads, I might try to make it so that you can use the law boards directly on the card. You can do similar with unsynced borgs (use the board directly on the borg with their cover open) and when making new AIs (use the board on the unfinished core right after adding wires). I'm not sure yet, still contemplating it. It'll be in a different PR, though.

**Comment by Cyprex** [comment]
@zxaber This would likely be a terrible hack, but you might be able to check if a carded AI is present nearby for law changes

**Comment by Dorsisdwarf** [comment]
Could have sworn this used to be a thing, didnt know it was even possible

**Comment by Anonmare** [comment]
To be honest, inserting an AI into an integrity restorer ought to allow limited law-editing. Removing non-core laws and adding supplied laws would be the extent of what it should do.

**Comment by ExcessiveUseOfCobblestone** [comment]
> If someone is spamming the AI with nonsense laws, carding the AI will allow it some peace of mind while you deal with finding the uploader.

This is already true, and I find it a fair countermeasure to be able to subvert the AI while it's able to do AI-like things such as act as an all-access ID with bolt control. Et Tu AI?

If someone is spamming the AI with nonsense laws, carding the AI **and turning off wireless** will allow it some peace of mind while you deal with finding the uploader.

If there is a baddy, you can send the AI to the minecraft netherealm.

**Comment by zxaber** [comment]
There was a PR to make AIs on Lavaland unable to affect the station. The PR ultimately had no effect, but I'd assume doing so is somewhat of bug abuse.

Anyway, again, the point of this PR is to prevent uploads while wireless is on. It's not exactly fun to just sit in a backpack for half the round unable to do anything when you signed up for AI. Letting the AI at least control a shell, or be able to affect doors and machines nearby to help their carrier would be nice.

**Comment by ExcessiveUseOfCobblestone** [comment]
If it got closed it's a  valid tactic ;) 

> Anyway, again, the point of this PR is to prevent uploads while wireless is on. It's not exactly fun to just sit in a backpack for half the round unable to do anything when you signed up for AI. Letting the AI at least control a shell, or be able to affect doors and machines nearby to help their carrier would be nice.

Nor is being in a 2x3 room in perma or being walled off. You will sometimes be put in a situation that's out of your control, and you more/less sign up for it when you play a role that cannot move directly.

Much like what you said in the other PR, to which I agree with:

> Punishing [people trying to subvert] by making it so easy to powergame against seems not great.

Surely there's a saner way to handle man in maint with upload board than this, and if noone can come up with a better solution then perhaps as it is now is just fine.

**Comment by zxaber** [comment]
The reason I wanted to go with this system is _because_ it's not really powergame. For the crew, having the AI in a card is less advantageous than otherwise. Even if the AI gets a shell, two borgs is not worth more than a borg and a proper AI. Without a cored AI to watch the cameras, the Captain and Security lose the ability to track people, and regular folk lose the ability to call for help. If there's no current risk of subversion, it's better for everyone involved if the AI stays in the core. 

But at least, if carding the AI becomes necessary, we could give the AI a shell and let it carry on as a borg for the time being.

By the by, the PR I'm referring to is #41521, and was property merged. It just didn't actually work. The merge tells me that sending the AI to Lavaland and letting it still interact with the station is unintented.

**Comment by Tlaltecuhtli** [comment]
if a carded ai already has a switch to turn on/off law changes from what i understood, whats the point of the pr, ais are super easy to replace as they literally need some gold to print off a posibrain and some plasteel for the core, just emp spam and kill the suspected rogue ai and then print a new one at this point

**Comment by zxaber** [comment]
Because that's quite rude.

There _is_ a player behind that AI, you know. We don't have to validhunt everyone we can possibly justify validhunting.

**Comment by ShizCalev** [comment]
uploading to an intellicard'd AI with wireless enabled should be allowed imo.

**Comment by Barhandar** [comment]
>literally just subvert, card, give shell and now your personal AI is lawfix-proof

**Pull request closed without merging**
