### PR TITLE
Nerfs Tasers

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard Forver: Greytide Resistance
balance: Taser shot cost has been raised from 200 to 300. This lowers your amount of shots per charge from 5 to 3.
/:cl:

[why]: I know I'm gonna get shit for this, but I strongly feel like this is needed. The amount of stuns in this game is appalling. Stuns are basically a 1-shot kill, and ruin combat.

**Honestly I believe this could be nerfed down to 1 shot per charge, but I think that would be too controversial.**

### CODE REVIEW

**Comment by evsey9** [comment]
Encourages better aim

**Comment by KorPhaeron** [comment]
lmao

**Comment by evsey9** [comment]
Just use disablers

**Comment by Tacolizard** [comment]
@evsey9 Disablers have issues, but they are a MUCH more balanced method of stunning.

**Comment by Limski** [comment]
Hi, why not make tasers lose stun duration based on it's distance from the shot source? that makes more sense, dunno how well that is in terms of balance tho

**Comment by evsey9** [comment]
I was telling "use disablers" to people who disagree with the change.

**Comment by Robustin** [comment]
I can juke 5 taser shots, I cannot juke 20 disablers since landing 1-2 (2 if youre in perfect health) is a free follow up for the 2nd and 3rd hits. 

I would much rather cut disabler ammo to 15 than this Ided PR.

**Comment by Tacolizard** [comment]
Limski, that's an interesting idea, but most people who use tasers already use them at pretty close range.

**Comment by Tacolizard** [comment]
@Robustin This isn't an ided PR. 

Not everyone can juke 5 taser shots. Play a round and you'll see that sec is almost always using the taser mode. It is very powerful at close range.

**Comment by Robustin** [comment]
If you made taser's default the disabler function you'd see sec is almost always using the disabler mode.

I use taser because if I'm suddenly ambushed I need an immediate stun or I might be dead. If I'm chasing then I just spray 'n pray with the disabler because 95% of this game is either small rooms or 1-3 wide halls and just spamming the disablers into either of those environments will connect enough shots for the slow and then the easy followup.

**Comment by Tacolizard** [comment]
@Robustin That's the inspiration behind this PR. Tasers should be for close range defense/surprise arrests and disablers for everything else. This PR reduces your ability to spray out taser shots at longer ranges

**Comment by Repukan** [comment]
>Sec gets nerfed without compensation episode

Someone change the channel pls

**Comment by Tacolizard** [comment]
nerfing sec and then compensating them isn't really a nerf. 

People complain about stuns in this game more than almost anything.

**Comment by PKPenguin321** [comment]
>Disablers have issues, but they are a MUCH more balanced method of stunning.

Lol
This is just incorrect outright
Not speaking for this actual pr but if this is your reasoning this should be closed asap

**Comment by Tacolizard** [comment]
>Not speaking for this actual pr but if this is your reasoning this should be closed asap

>close pr you mabye like because you don't agree with the reasoning

I think disablers are slightly overpowered but they are better than tasers.

**Comment by PKPenguin321** [comment]
That is not true
Taser might counter disabler if you're fast but in basically every other case disablers are objectively better. Something like 5x the ammo, shoots through windows, after the first hit enough slowdown is applied to basically guarantee two more, the stun lasts longer and can be extended MUCH further for almost free with another disabler shot, and even if you by some miracle survive the 30 year stun from getting disabled you're left with crippling slowdown for the next full minute.
A taser just knocks you down for something like 5 seconds and that's it. Disablers being balanced is literally just a meme.

**Comment by MMMiracles** [comment]
Turn tasers into their real-life counterparts with the dart-like spring cartridges for ranged stunning. Balanced.

**Comment by GunHog** [comment]
> Turn tasers into their real-life counterparts with the dart-like spring cartridges for ranged stunning. Balanced.

Nah. Do this: https://youtu.be/gPvsUKZ1Cnc?t=10

**Comment by xxalpha** [comment]
Nerf them even more? BALANCE MEMES

**Comment by BeeSting12** [comment]
Security doesn't need this nerf. Or any nerf. But especially not this one.

**Comment by KorPhaeron** [comment]
This would be great and all but

A) Half our modes see security vastly outnumbered and the number of officers vs numbers of players varies wildly from round to round. They need enough ammo to take on multiple targets.

B) We have a bunch of enemies with anti-stun powers/shields designed around blocking tasers so you need followup shots

**Comment by Magikarpet** [comment]
20 disablers that have a faster firerate and are spammable that slow down targets while passing windows versus 5 or 3 taser shots

**Comment by CPTANT** [comment]
I still think the 2 shot taser was a way better solution than what we have now.

https://tgstation13.org/phpBB/viewtopic.php?f=9&t=5932

**Comment by WJohn** [comment]
This doesn't change how fundamentally broken yet vital stunning is, it just makes it more annoying and incentivizes them to carry more tasers with them. An instant stun is still an instant stun and the fight is over. Even if you have fewer shots it doesn't matter, ONE shot is still all it takes.

This is the laziest way to "fix" a problem and done in a way that doesn't even fix it.

**Comment by CosmicScientist** [comment]
>Turn tasers into their real-life counterparts with the dart-like spring cartridges for ranged stunning. Balanced.

Or gamify it and have one connection use up the entire charge and stun time is based on how much charge is left, only losing partial charge on each miss. Of course that just makes the taser a glorified one shot device and solves nothing. I'll shush now.

**Comment by ShadowDimentio** [comment]
STOP, JESUS STOP. SEC DOESN'T NEED THIS.

**Comment by Niknakflak** [comment]
If you're gonna go for the nerf, why not make it 4 instead of 3.  3 is just useless man, if you're gonna try to nerf, at least do it right

**Pull request closed without merging**
