### PR TITLE
Fixes a stray pixel on the packet of cheesie honkers

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About The Pull Request

Before
dreammaker_2021-04-18_13-11-05
After
dreammaker_2021-04-18_13-11-35
Before
dreammaker_2021-04-18_13-12-32
After
dreammaker_2021-04-18_13-12-41

## Why It's Good For The Game

A

image0-44-1

## Changelog
:cl: Swept smells
fix: Stray pixel on packet of cheesie honkers
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
soulless

**Comment by Farquaar** [comment]
speedmerge

**Review by Twaticus — APPROVED** [review]

**Comment by tommysalami3** [comment]
image

**Comment by Mothblocks** [comment]
conflicts

**Comment by SweptWasTaken** [comment]
> broooo

Sorry

**Pull request closed without merging**
