### PR TITLE
Changes the operating table to be an actual table.

### LINKED ISSUE #11211: Surgey tables block projectiles
Not ALL tables are tables.

### PR DESCRIPTION
**Pull request by Firecage**
As it says in the title. This changes to surgery table so it is actually a real table. You can now also make it by using a sheet of silver on a tableframe.

Fixes #11211 

:cl: Firecage
rscadd: NanoTrasen specialists has developed a new type of operating table. You can now make one yourself with only some rods and a sheet of silver!
/:cl:

### CODE REVIEW

**Comment by Bluespace** [comment]
pppppics

**Comment by Firecage** [comment]
.....Pics for....what?

**Comment by MMMiracles** [comment]
pics for the table, obviously.

**Comment by Firecage** [comment]
But it's the same table...

**Comment by Bluespace** [comment]
Ah shame I thought you were getting rid of the ass tier sprite

**Comment by Firecage** [comment]
I cannot into spriting.

**Comment by Bawhoppen** [comment]
@Bluespace >asstier sprite >literally best sprite on all of tg

**Comment by Alek2ander** [comment]
Make sure the ayylien table can't be deconstructed.

**Comment by Bawhoppen** [comment]
@Alek2ander or let it be? because its a fucking piece of metal not some infused magical hydro-singed plastitanium iridium alloy

**Comment by Alek2ander** [comment]
@Bawhoppen Because it can't be fixed afterwards

**Comment by Bawhoppen** [comment]
@Alek2ander IF IT IS GOING TO BE CONSTRUCTABLE NOW, THEN IT CAN

**Comment by Alek2ander** [comment]
@Bawhoppen The normal station operating table is constructable. Not the fancy pink ayylien one. Unless you want the station to be able to build pink tables or poor abductors getting stuck with the boring human table.

**Comment by Bawhoppen** [comment]
@Alek2ander just give them the normal table if they feel the need to fucking decon and rebuild it,
there are already countless snowflakey shit that can't be rebuilt on the actual station itself, no need to worry about rare ayylien event

**Comment by Firecage** [comment]
Aleksander. Well, mmm. We have two ores which the crew can't get except via admin intervention. I wonder if I can have the Ayylium stuff require one of those to be constructed...or at the very least the surgery table.

**Comment by Bawhoppen** [comment]
@Firecage we have like 10 more like, all at varying levels of completion and use

**Comment by Dorsisdwarf** [comment]
@Firecage 
The reason we have things on the station be constructable is so that if the heads declare that We Can Fix This, its not utter shit for the survivors of the department who cant do shit otherwise

We dont need to make ayylien tables deconstructable, because if there's an explosion in the ship large enough to take out the table, the ayys are dead or all their stuff is broken. They're aliens, not budget contractors on a budget station.

Also @Bawhoppen 
>dissing ausops sprites

**Comment by Bawhoppen** [comment]
@Dorsisdwarf whose sprite did I dis, in this pr atleast

**Comment by Firecage** [comment]
Okay. Abductor OP tables will now not be deconstructable.

**Comment by SweaterKittens** [comment]
:+1: Awesome! Now you can make secret surgery rooms or rebuild the main surgery room should you move it for some reason. Like to the Theatre so you can perform surgeries for public entertainment.

**Comment by MrStonedOne** [comment]
Please make a changelog,

You can add it to the PR's body rather then as a file now, see here: https://tgstation13.org/phpBB/viewtopic.php?f=5&t=5157

**Comment by phil235** [comment]
This fixes Surgey tables blocking projectiles.

**Comment by Firecage** [comment]
Like that @MrStonedOne ?

**Comment by MrStonedOne** [comment]
Yes, you can omit the name if you want, it will default to your github username, I added that for people like kor who tend to use a different name in their changelogs

**Comment by Firecage** [comment]
Thanks for the cool system MSO

**Comment by phil235** [comment]
@Firecage Did you make other map edits in this PR?

**Comment by Firecage** [comment]
@phil235 No, only changes the path of the OP table.

**Pull request merged**
