### PR TITLE
Slipping tweaks

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Slipping on lube now does 5 damage (previously 2) but only hits one body part per slip so it doesn't deal like .5 damage to each limb.

Slipping on water no longer deals damage

### CODE REVIEW

**Comment by Miauw62** [comment]
why does slipping do damage
can't it just be 0 damage

**Comment by joonoro** [comment]
A nerf was definitely in order. Kind of agree on making it do no damage though, being immobile for a while is already enough of a PITA.

**Comment by Zilenan91** [comment]
Yeah it's just an unneeded annoyance at best, why should falling down hurt you as much as getting punched?

**Comment by KorPhaeron** [comment]
A hard fall after sprinting down the hallway and losing your footing is painful.

**Comment by Zilenan91** [comment]
Well yeah but if I fall down after running I'm not gonna feel like somebody punched me in the arm as hard as they possibly could.

**Comment by Dorsisdwarf** [comment]
If I fall over 20 times, I will not die.

**Comment by Fox-McCloud** [comment]
traditionally only space lube slipping dealt damage...per tile you slipped over.

Regular slipping dealing damage is bullshit.

**Comment by PKPenguin321** [comment]
yeah i dont see why slipping has to do damage, it's kinda shitty honestly

**Comment by Cookiesndip** [comment]
Slipping never used to do damage. I don't know why that was added, just remove the damage because it's just annoying and suits no real purpose other than letting you slip people to death..

**Comment by Fox-McCloud** [comment]
I'll re-iterate: slipping on space lube has *always* dealt damage.

**Comment by Cookiesndip** [comment]
But slipping on water didn't.

**Comment by Fox-McCloud** [comment]
@Cookiesndip 

Correct.

**Comment by Aranclanos** [comment]
why slipping do damageeeeeeREEEEEEEEEEEEEEEEEEEE

**Comment by AnturK** [comment]
As far as i can tell this wasn't intended change. As #11189 doesn't mention it i assume it was just indentation error. And it's pretty awful.

**Comment by Aranclanos** [comment]
its a bug lmfao

**Comment by joonoro** [comment]
wow

**Comment by KorPhaeron** [comment]
@Aranclanos 

Fixed

**Comment by Fox-McCloud** [comment]
5 seems like a bit much, IMO; someone will only have to slip 20 tiles to put them into crit, which really isn't that much in the grand scheme of things.

**Comment by phil235** [comment]
Either make it do 0 damage or just 1or 2. 5 is too high.

**Comment by PKPenguin321** [comment]
make it 0 kor you can do it we all believe in you

**Comment by Zilenan91** [comment]
yeah fuck slipping doing damage

**Comment by Fox-McCloud** [comment]
Lube slipping has always done damage; it's only regular slipping that hasn't--which this PR is correcting---but it buffs the damage for lube slipping, in the process, from 2 to 5.

**Comment by PKPenguin321** [comment]
cool, cool, but water/banana/other slips shouldnt do damage

**Comment by Fox-McCloud** [comment]
Alright, so....originally, you never took damage from any type of slip---EXCEPT for being slipped by lube---in that case, you'd take 2 damage per turf slipped on.

Then some changes were made to slipping, and I believe this unintentionally enabled that 2 damage per turf slip for ALL types of slipping and not just lube.

This PR corrects that unintended change so that 99% of slipping doesn't cause damage anymore; only lube slipping will cause damage again (like it did).

That said, this damage is buffed from the original of 2 to a whopping 5.


IMO, slipping+damage for lube, only, should stay, but it shouldn't be buffed to 5 damage; it should stay at 2.

**Pull request merged**
