### PR TITLE
add Administration tag to gbp list, 2 points

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-adds "Administration" tag to gbp point list for 2 points

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
@tgstation/commit-access

**Comment by Mooshimi** [comment]
> @tgstation/commit-access

tfw it doesnt get anyone

**Comment by tralezab** [comment]
dawwwwwwwwwwwwww

**Review by Mothblocks — APPROVED** [review]
this likely won't do much FYI with the high vs low system we have, but it doesnt harm anything

**Review by spookydonut — APPROVED** [review]

**Review by Kylerace — APPROVED** [review]
good idea, id say it should be 2 though to offset content expansion more

**Review by stylemistake — APPROVED** [review]

**Review by Watermelon914 — APPROVED** [review]

**Review by Timberpoes — APPROVED** [review]
I make lots of administration PRs. Please contribute to my GBP pool so I can afford balance changes.

**Review by ghost — APPROVED** [review]

**Review by Fikou — CHANGES_REQUESTED** [review]
make it +10 i love administaraiton

**Review by LemonInTheDark — APPROVED** [review]
I hate the admin catgirl reading this

**Review by 81Denton — APPROVED** [review]

**Pull request merged**
