### PR TITLE
Removes the East and West sprites for lipstick and sets the default sprite to lipstick_upper

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
## About The Pull Request

Removes the east and west facing icons on the lips overlay.
When lipstick is applied, the default is lipstick upper instead of lipstick middle so that it's properly aligned to the human sprite.

## Why It's Good For The Game

Lipstick and the lips sprite is just a single pixel of color and it clashes with the overall sprite border of the human mob. I know it's hard to depict something like lips on a 32x32 sprite, but in this case minimalism for very minimalistic body features is better. I'll put a comparision. 

Also upper is where the human sprite lips are right now.

**Before:**
image

**After:**
image
image

## Changelog

:cl:
qol: Default lipstick position now matches the human sprite lips.
image: Lipstick east and west mob sprites removed. 
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
I'll be honest I don't really see the point in removing this single pixel from a thing that only changes a single pixel anyway.
"Clashing with the border" shouldn't matter all that much because the border is an extension of the skin's color, which would be covered by lipstick.
Also can you show a before/after for the front sprite since you said you moved the pixel?

**Comment by StrangeWeirdKitten** [comment]
> I'll be honest I don't really see the point in removing this single pixel from a thing that only changes a single pixel anyway. "Clashing with the border" shouldn't matter all that much because the border is an extension of the skin's color, which would be covered by lipstick. Also can you show a before/after for the front sprite since you said you moved the pixel?

Yeah, all I changed is the default alt-click of the lipstick. It can easily be set back to "lower" or "middle" but this is middle as a default.

image

**Comment by StrangeWeirdKitten** [comment]
Regarding the east west thing, it really sort of clashes in my eyes and seems like more of an errant pixel than what I'd associate with lipstick.

**Comment by SmArtKar** [comment]
This just feels like a downsgrade

**Comment by StrangeWeirdKitten** [comment]
Np

**Pull request closed without merging**
