### PR TITLE
Ballistic guns sound revamp

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
This revamps a lot of the sounds we have for guns and gives 4 types of guns their own unique sounds:
- bolt drop
- bolt cock back
- rack
- magazine insert
- magazine eject
- gunshots
- shell insert
- gun drop/pickup

#### Video demonstration of the sounds:
<details>
<summary>Shotguns</summary>
<br>

https://github.com/user-attachments/assets/124598a1-25bd-40dd-8749-c944b0163079
</details>
<details>
<summary>Pistols</summary>
<br>

https://github.com/user-attachments/assets/a9c575a1-39a4-4a63-b745-8c827b992c3a
</details>
<details>
<summary>SMGs</summary>
<br>

https://github.com/user-attachments/assets/0472d367-6c5d-420b-b7bb-1bd27c07715d

</details>

<details>
<summary>Rifles</summary>
<br>

https://github.com/user-attachments/assets/62c516c7-9235-4c1c-bef8-0ffb5edd897d

</details>

I also slightly changed the default rack sound but it was just a cut to make it shorter.
## Changelog
:cl: grungussuss
sound: shotguns have received new sounds
sound: SMGs have received new sounds
sound: Rifles have received new sounds
sound: Pistols have received new sounds
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
shotguns seem to have a bit of noise at the beginning? its really hard on ears ngl

**Comment by MatrixOne500** [comment]
It feels hit and miss. Many of the shotguns have a ton of reverb and earsplitting noise that I don't like, and the SMGs especially sounds very weak,, like paintball guns. I like the suppressed Makarov sound and some of the magazine and bolt sounds though. Overall I think it'll make the sounds "different" but not "better" so my vote is no on this

**Comment by SmArtKar** [comment]
> > shotguns seem to have a bit of noise at the beginning? its really hard on ears ngl
> 
> in which sound? gunshot?

yeah, the sounds in general are really grating on ears. Pistols also suffer from this issue, maybe you should tone it down a bit

**Comment by Sadboysuss** [comment]
gonna adjust some sounds after relistening

**Comment by carlarctg** [comment]
I don't think this fits TG honestly. TG is a wacky space station game and these are hyper realistic almost milsim sounds. They go in a direction of gunwank that I think is worse than the present sounds.

**Comment by EricZilla** [comment]
Something about the SMG firing sound is off, but I don't really know how to explain it. Doesnt sound like a gun?

Everything else sounds great

**Comment by Loafin34** [comment]
why is deagle using suppressed pistol sound? it should sound more like the APS. also, i think that the reload sounds shouldn't be added, ours are iconic enough.

**Comment by Sadboysuss** [comment]
> why is deagle using suppressed pistol sound? it should sound more like the APS. also, i think that the reload sounds shouldn't be added, ours are iconic enough.

oh shit I can see what you mean

**Comment by Exester509** [comment]
The SMGs sound very weak, kinda as if they were supressed.
Also, the deagle and 1911 being quieter than the makarov and APS (or Ansem, whatever is that third gun) is just wrong.
I like the shotguns and rifle ones though, I assume any guns not displayed don't have their sounds changed?

**Comment by Sadboysuss** [comment]
> I assume any guns not displayed don't have their sounds changed?

The guns in the demo are representations of weapon types, all of the weapons using that weapon type are changed.

**Comment by mc-oofert** [comment]
idk whats wrong about these sounds i just feel like they dont fit and are much more grating than the sound of lets say a makarov

**Pull request closed without merging**
