### PR TITLE
Adds the advanced medical scanner, gives one to the CMO

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: The CMO now has an advanced health analyzer in his closet! It can give more precise readings on the non-standard damage types.
/:cl:

Adds a little bit of improved equipment for the CMO, like the CE has, without much of a powerboost aside from being able to reveal a fake death.

Plus in the future some afflictions could be hidden to normal scanners but revealed to advanced, like hidden infections, zombie viruses, mutant organs, or syndicate implants.

Sprite:
health

### CODE REVIEW

**Comment by kevinz000** [comment]
*whispers: R&D*

**Comment by Armhulen** [comment]
the sprite sucks, make it something way cooler!

**Comment by DoctoreMad** [comment]
If the hypospray isn't in R&D why would this be

**Comment by XDTM** [comment]
this is like 5% better than a normal scanner, the reason i didn't put it in rnd is that i didn't want to mess with techwebs if they are somehow happening

also i feel offended @Armhulen i made it myself with three minutes of hard, hard work

**Comment by kevinz000** [comment]
do it techwebs is in debug hell

**Comment by QualityVan** [comment]
muh powercreep
fuck rnd
what's it show that regulars don't, radiation?

**Comment by XDTM** [comment]
oh radiation, good idea

**Comment by DoctoreMad** [comment]
_Inb4_ make it a antag objective to confirm the suspicion that heads of departments are super-crewmembers and not managers that should give their items to the most efficient crewmembers under them

**Comment by kevinz000** [comment]
>comparing an advanced health analyzer to a potentially one hit kill weapon
hm!

**Comment by DoctoreMad** [comment]
Why aren't advanced magboots in R&D

**Comment by kevinz000** [comment]
>comparing a fucking better health analyzer with better noslips

Hm!

**Comment by DoctoreMad** [comment]
Why life.

**Comment by SgtxRootbeer** [comment]
@DoctoreMad you can make the equivilent of advanced magboots with xenobio speed potions + normal magboots from rnd/eva

**Comment by Armhulen** [comment]
doth life

**Comment by XDTM** [comment]
Added eye, ear, and radiation status

**Comment by XDTM** [comment]
Also hallucinations

**Comment by Armhulen** [comment]
nice

**Comment by QualityVan** [comment]
we don't cotton to freaks 'round these parts

**Comment by Repukan** [comment]
RnD doesn't need it.

**Comment by AnonymousNow** [comment]
Gah, I should've moved in with the Medical HUDshades sooner. I'll have to add them once I'm done with my current project.

**Comment by DoctoreMad** [comment]
Yeah that part is always silly
CAN ADD SECSHUD TO SHADES
CAN'T ADD MEDHUD TO SHADES

**Comment by AnonymousNow** [comment]
The Medical HUDshades are in, I just keep forgetting to add them to maps (and I know fuckall about coding/BYOND, so it'll take me some time to figure out how when I get around to it).

**Comment by YakumoChen** [comment]
Hypo and adv mags aren't in rnd to discourage being able to make every traitor objective in research

**Comment by davethwave** [comment]
Honestly I think this would be good with techweb but not with the R&D we have now considering it would take longer to potentially get something like this along the many nodes of techweb as well as it would probably not be as popular as many people would think... I mean really, it's just a better health scanner and unless you want to be a special snowflake by having a better one than other people it has no real purpose as you can grasp your situation such as if you have brain damage and things like it by the SUBTLE hints the game gives you.

**Comment by FantasticFwoosh** [comment]
This reminds me when i talked to @Anonmare i think over discord about hidden diseases, nice to see its been atleast considered.

- Though from that discussion this is exactly the opposite of what was wanted, a powecrept med scanner, instead we were thinking of ways to make the spectrometer & advanced spectrometer relevant through detecting hidden advanced bloodbourne diseases.

**Comment by XDTM** [comment]
This has no effect on diseases, and the spectrometer idea is good

**Comment by davethwave** [comment]
Yeah, probably a good idea. I've seen a few items in R&D that are pretty useless.

**Comment by BeeSting12** [comment]
@AnonymousNow 
The guides on the wiki are good for mapping, PM me if you have questions on discord and I can help with the mapping aspect

**Comment by XDTM** [comment]
If you want to put stuff in head lockers you don't need to map though, it's a code change

**Comment by Qbopper** [comment]
you can do that or add them onto the map if you have a snowflake case where it can't be in a locker but you want it on the map

**Comment by optimumtact** [comment]
holy shit RnD players are annoying

**Comment by Qbopper** [comment]
wtf i like oranges now??

**Comment by davethwave** [comment]
what I mean is items that are not useful for the crew in general, not power game equipment...

**Pull request merged**
