### PR TITLE
Assault Pod Fix

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Trying to use \ref throws runtime errors (can't find the shuttle ID) and makes the pod unable to launch.

@tkdrg 

:cl: Kor
rscadd: Clicking the (F) follow link for AI speech will now make you orbit their camera eye.
/:cl:

### CODE REVIEW

**Comment by tkdrg** [comment]
Well, for starters, what's the runtime? The only situation I can think of where a `rand()` would work and a `\ref[src]` wouldn't is if `src` was null.

**Comment by KorPhaeron** [comment]
## WARNING: couldn't find dock with id: assault_pod([0x200ad8f]) in code/controllers/subsystem/shuttles.dm at line 82 src: Shuttles usr: Jace Evans.
runtime error: Exception thrown: request(): shuttle cannot dock (/exception)
proc name: request (/obj/docking_port/mobile/proc/request)
  source file: shuttle.dm,229
  usr: Jace Evans (/mob/living/carbon/human)
  src: the steel rain (/obj/docking_port/mobile/assault_pod)
  call stack:
the steel rain (/obj/docking_port/mobile/assault_pod): request(null)
the steel rain (/obj/docking_port/mobile/assault_pod): request(null)
Shuttles (/datum/subsystem/shuttle): moveShuttle("steel_rain", "assault_pod(\[0x200ad8f])", 1)
the syndicate assault pod cont... (/obj/machinery/computer/shuttle/syndicate/drop_pod): Topic("src=\[0x200f085];move=assault_...", /list (/list))
the syndicate assault pod cont... (/obj/machinery/computer/shuttle/syndicate/drop_pod): Topic("src=\[0x200f085];move=assault_...", /list (/list))
the syndicate assault pod cont... (/obj/machinery/computer/shuttle/syndicate/drop_pod): Topic("src=\[0x200f085];move=assault_...", /list (/list))
KorPhaeron (/client): Topic("src=\[0x200f085];move=assault_...", /list (/list), the syndicate assault pod cont... (/obj/machinery/computer/shuttle/syndicate/drop_pod))

**Comment by KorPhaeron** [comment]
@tkdrg

**Comment by tkdrg** [comment]
Quickmerge because it's an one character change to fix a major nukeops item.

**Pull request merged**
