### PR TITLE
Adjusts redpill.json

### PR DESCRIPTION
**Pull request by 81Denton**
Minor tweak to redpill.json since most races have their own native language now

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by HomocidlePancakes** [comment]
>What the fuck is CO2

Um, it’s supposed to be “What the fuck is carbon dioxide”. I am well (self) educated in this matter and you should do as I say.

**Comment by trollbreeder** [comment]
What the fuck is nitrogen?

**Comment by 81Denton** [comment]
@HomocidlePancakes uhhhh correct
I hope people will forgive me for changing the "550 years ago" part two days before new year's eve

**Comment by Tharcoonvagh** [comment]
How dare you

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
