### PR TITLE
Revert "[FEATURE] Emergency Response Team"

### PR DESCRIPTION
**Pull request by tkdrg**
This nuked the shuttle changes by Carn and broke all of them.
@steelpoint please test your stuff after solving conflicts 
@miauw62 please stop merging broken shit

Reverts tgstation/-tg-station#6705

### CODE REVIEW

**Comment by optimumtact** [comment]
Lets try and keep travis in a green state so this doesn't happen again.

**Comment by Steelpoint** [comment]
The problem is the fact that the maintainers take so damn long to merge PRs. I never even knew the shuttles were touched.

**Comment by Steelpoint** [comment]
Also Travis was always in the green, my best guess is that I accidentally overwrote the CentCom shuttle. I don't know how all the other shuttles broke since I did not touch them.

**Comment by paprka** [comment]
try compiling before you commit, travis doesn't check all the zlevels that's all

**Comment by tkdrg** [comment]
That's factually incorrect: Travis does test all the boxstation Z-levels.

**Comment by Steelpoint** [comment]
Nothing was broken as i did compile the code beforehand.

I'll work on a new PR when I get in a computer, but I expect it to be merged in a good time frame, not 5 days later.

**Comment by Miauw62** [comment]
I just merged it because nobody wanted to merge it, me included.
Op 11-jan.-2015 06:32 schreef "Steelpoint" <notifications@github.com>:

**Comment by tkdrg** [comment]
If nobody wanted to merge it, then, uh, why was it merged? I still dislike the idea and concept.

**Comment by Steelpoint** [comment]
My guess is because a lot of admins/players have supported the idea.

**Comment by Miauw62** [comment]
Yeah, I didn't want it to be held back forever and most dislikes were things that could be tweaked later.

**Pull request merged**
