### PR TITLE
New vent and scrubber sprites

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
imageadd: Added new vent and scrubber sprites by Partheo.
/:cl:

Credit to Partheo for the sprites.

Notice the starting/stopping animation.
image
image
image

### CODE REVIEW

**Comment by ike709** [comment]
Diff bot is broken again.

**Comment by ShizCalev** [comment]
Awesome!

I will ask though; would you mind readding the OFF wording to vent_map, dpvent_map, & scrub_map, as well as the downward arrow to vent_map_siphon_on? The grill areas of these sprites are only visible in DM and the text/arrow were in place to allow mappers to easily tell at a glance what was off / siphoning.

**Comment by Xhuis** [comment]
That's neat, I like these.

**Comment by ike709** [comment]
@ShizCalev Done

**Comment by epochayur** [comment]
the PR I never knew we needed, nice work though

**Comment by davethwave** [comment]
Definitely better looking than the stuff we have now.

**Comment by ACCount12** [comment]
I'm not sure on "Scrubbing" mode having this eyesore pulse animation. It would be better with a static sprite.

**Comment by ChangelingRain** [comment]
What's your tolerance for flashing things?
That sprite is much less glaring than the current one, and I'd almost say it's too subtle.

**Comment by CPTANT** [comment]
I once again wonder why there are vents that siphon air.....

**Comment by ike709** [comment]
Bot is still wrong.

**Comment by lzimann** [comment]
yea, gonna have to debug on why

**Comment by ACCount12** [comment]
>What's your tolerance for flashing things?

Pretty damn low, I use adblock so I don't have "ignore anything flashing" ingrained in my mind.

**Comment by GunHog** [comment]
These are lovely!

**Comment by CPTANT** [comment]
The blue one is a lot nicer!

**Comment by nicbn** [comment]
They move too fast, please make the animation slower by a bit

**Comment by Dorsisdwarf** [comment]
I love the new scrubber but I'm not sure about the vents.

**Comment by DoctoreMad** [comment]
I can't see anything wrong with the vents myself so either I'm being blind again or this is a case of subjective opinion, in which case dunno you mate.

**Comment by Partheo** [comment]
I made the sprites. These were originally for Yogs so I didn't bother to make the map versions you guys use with "off". I'm still working on tweaking these (as the PR on Yogstation is still open) mainly to make the vents less distracting. They look very nice, but as they are background objects, I was told that they don't have a place as rapidly animated fans. I do agree and I'm working on something more subtle.

Also, the code for the vents includes icon_state logic. I know that that has been avoided in the past, but since I'm a rookie coder, that's what I went with. If someone can find a better way to do it, be my guest.

**Comment by ShizCalev** [comment]
I'm a fan of the fans tbh.

**Comment by Xhuis** [comment]
🥁

**Comment by KorPhaeron** [comment]
These are kind of distracting as background/floor items. They're very flashy in their default operating state

**Comment by Partheo** [comment]
@korphareon the original PR is WIP and I'm working on fixing this. This was ported before I was done.

**Comment by Xhuis** [comment]
yeah IKE

**Comment by ike709** [comment]
¯\_(ツ)_/¯ 

I stole these from an FTL13 pull request that stole them from yogs. I didn't know they were wip.
I like them how they are anyways, though.

**Pull request merged**
