### PR TITLE
Syndicate temperature gun. Fixed branch.

### PR DESCRIPTION
**Pull request by ghost**
Adds Syndicate temperature gun. Uplink item for 14 tc. Works in two modes: bake and freeze. In freeze mode each beam decreases temperature of target. Also in slow mode slows target. In bake mode each beam increases temperature of target. Also in bake mode if target temperature is high enough, then sets target on fire. Has completed sprites (beams, sprites of weapon and in hand sprites). It has 8 shots. One shot deals ~40-50 burn damage over time. Shooting additional shots at the target does less damage. Something like ~8 freeze shots or ~2 bake shots(if target is unable to extinguish itself) should be enough to crit target. Also it recharges itself over time.
It is not boring and generic because:
It has interesting mechanics.
It is really different from original temperature gun. (It adds fixed value to temperature of target, instead of setting temperature of target to fixed value)
Created as weapon for long fights, for idea then traitor needs to escape alone or assassinate HoS.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
still big :-1: 
syndies really do not need more guns or weapons, and while this one is slightly less generic, it still is mostly uninspired and probably too much

**Comment by HunterMaksim** [comment]
One of the main points of this weapon, is that it mostly designed for traitors, not for nuke ops. It is balanced pretty well. Adding new balanced weapons makes gameplay as antags more interesting.

**Comment by AlexanderUlanH** [comment]
Not thematically different than the regular tempgun and the mechanical difference is pretty subtle. Also not a fan of giving traitors a weapon whose nieche is sustainability. Most traitor equipment is made to encourage traitors to commit a few crimes or murders and then to do their best to get away with it.

**Comment by HunterMaksim** [comment]
You are right, but i think that traitors need some kind of weapon whose nieche is sustainability. It makes  traitor think, how to get away. He can use agent ID-card and voice changer in order to get away. 
Also while not thematically different than the regular tempgun, it is not a big deal. People rarely make tempguns. And can regular tempgun ignite people?
STG is pretty balanced and can offer, not only damage, but really useful utility too. Traitor can use it to slow target down, for idea to get away from security after murdering someone. He can use it to distract enemies, for idea to ignite HoS, and get away, while security is trying to extinguish HoS.
STG can help traitor to create interesting situations for both traitor and crew.

**Comment by HunterMaksim** [comment]
Also why there is "Balance" label? Weapon is pretty balanced. It doesn't change original tempgun, it is even not child of it, in terms of code.

**Comment by Bawhoppen** [comment]
what do you mean why is there a balance label, this changes the balance of traitor whether you think its small or not

**Comment by HunterMaksim** [comment]
Alright then.

**Comment by ToGWtF** [comment]
#16104

**Comment by duncathan** [comment]
@HunterMaksim

**Comment by HunterMaksim** [comment]
I will fix merge conflict.

**Comment by KorPhaeron** [comment]
Stale, let me know if you finish it

**Pull request closed without merging**
