### PR TITLE
Ashwalker Improvements - Torches, Drying Racks, Seeds, and Smoke Pipes

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
This does the following:

- Replaces all of the lamps in the ashwalker ruin with torches (torches have ~30 mins of fuel)
- Leaves a single lamp in the center
- Adds 2 porcini seeds and an additional towercap seed
- Adds a crafting recipe to make smoke pipes using wood
- Changes drying racks to require no power

This allows Ashwalkers to make more torches if needed AND grow their own version of mushroom tobacco.  

## Why It's Good For The Game
Makes Ashwalkers more cavelike.

## Changelog
:cl:
add: Add torches, porcini mushroom seeds, towercap seeds to ash walker ruin.
add: Change drying racks to not require power.
add: Add crafting recipe for smoking pipe that uses wood
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
> * Replaces all of the lamps in the ashwalker ruin with torches (torches have ~30 mins of fuel)

this seems like a nerf especially since spears need to be wielded, while the amount of lanterns was excessive i dont think removing all of them is a good idea

**Comment by Jackal-boop** [comment]
Can torches be placed on the belt like lanterns? If they can't this is a huge nerf

**Comment by Serxule** [comment]
> Can torches be placed on the belt like lanterns? If they can't this is a huge nerf

afaik they become a bulky item that doesnt fit anywhere when activated/turned on, and they cant be turned off

**Comment by Sealed101** [comment]
either skeleton pirate torches are something else or i am going senile, as i clearly remember being able to pocket torches

**Comment by Jackal-boop** [comment]
Why is making ash walkers MORE cave like good for the game? They are already very cave like

**Comment by Jackal-boop** [comment]
Also I wouldn't put improvment in the name of the PR if you are removing lanterns...

**Comment by timothymtorres** [comment]
> Can torches be placed on the belt like lanterns? If they can't this is a huge nerf

They fit in pockets but are excluded from belts slots.

> afaik they become a bulky item that doesnt fit anywhere when activated/turned on, and they cant be turned off

They are the same size as flashlights and lanterns.  Having them lit does not change anything.

> Why is making ash walkers MORE cave like good for the game? They are already very cave like

It fits their lore.

**Pull request merged**
