### PR TITLE
Operative HUD Resprite - Lonely Boy

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

I SAW THIS LITTLE BABY-BITCH NANOTRASEN HUD (#70474) CREEPING UP ON **MY** GITHUB, AND I COULDN'T LET IT SLIDE.

SYNDICHADS STAY WINNING.

image

## Why It's Good For The Game

image

(the old HUD was a bad recolour) ((this is cooler))

## Changelog

:cl:
imageadd: BRAND SPANKING NEW SYNDICHAD OPERATIVE HUD RESPRITE.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
now make it only be enabled when you're a nukie, with no other option

**Comment by axietheaxolotl** [comment]
> now make it only be enabled when you're a nukie, with no other option

wyci

**Comment by axietheaxolotl** [comment]
> how does this make the bodyzone selector look when something is selected?
like any other
>  also the inhand selected indicator looks like it can be easily obstructed by a large enough item. are you sure the small blip in the corner will be enough for everyone using this hud to signify the active hand slot?
yes

**Comment by necromanceranne** [comment]
> > how does this make the bodyzone selector look when something is selected?
> 
> like any other

That's not really indicative of anything. If it's not clear where you're targeting, it's not really an improvement, and the doll can be pretty hard to use as it is for a few noisy huds. Could you show how that looks?

**Comment by TheGreatValvatorez** [comment]
the different between nanohud VS oprative hud rework is that nanohud doesn't kill of an already existing hud

**Comment by axietheaxolotl** [comment]
> the different between nanohud VS oprative hud rework is that nanohud doesn't kill of an already existing hud
wow! good thing I don't care!

**Comment by TheGreatValvatorez** [comment]
Yeah i guess you don't care but what im saying that the nanotrasen hud added a whole new hud then overriding another, you can just do the same for this and let people choose between old/new

**Comment by Mothblocks** [comment]
:-1: adding new ui was already hard enough with our current themes, we experienced this during combat mode, i dont like that we're making ui less consistent with each other making this process harder. i was in the works of removing every themed ui other than the default and glass and then letting you color.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
image
itt changing **_MY_** primary interface from being red w/ transparency to generic solid grey.

Hell no, make it a new option or bust. It looks nice, but don't force me to use a completely different UI without the ability to go back to what **I** _actually_ wanted. The nanohud didn't delete a different HUD to be added.

**Comment by axietheaxolotl** [comment]
>  itt changing MY primary interface from being red w/ transparency to generic solid grey.

why do i care/should i that it's your hud in the slightest.

changing this is no different from changing any other sprite, but you care now because it's something you've grown a symbiotic bond with, even though it doesn't matter. I will not waste my breath arguing with someone claiming that what amounts to a hud with a hue and saturation panel open in photoshop needed to be in the game taking up RSC space. we don't keep old sprites around for anything else, and this is no different from anything else.

**Comment by axietheaxolotl** [comment]
> 👎 adding new/changing existing pieces of the ui was already hard enough with our current themes, we experienced this during combat mode, i dont like that we're making ui less consistent with each other making this process harder. i was in the works of removing every themed ui other than the default and glass and then letting you color.

this, in reality, isn't much different from any other HUD. it doesn't move anything, it doesn't change anything. and it doesn't add anything. The only changes are in framing, which don't really matter all that much. It's an aesthetic change in the most literal sense possible.

**Comment by tralezab** [comment]
I don't see why this couldn't just be a new hud. I love the look, but it's not like the old one is outstandingly ugly in any way. Some people are going to prefer see through huds.

I hope this cool new hud isn't lost in all the squabble, call the old syndicate hud "retro syndicate" or something?

**Comment by axietheaxolotl** [comment]
> I don't see why this couldn't just be a new hud. I love the look, but it's not like the old one is outstandingly ugly in any way. Some people are going to prefer see through huds.

I mean, it could be a new HUD, sure. But _why_ does it need to be. It's not like the old one existing is bringing anything interesting to the table, as I elegantly described, it's midnight with a photoshop hue and saturation panel open. It doesn't really need to exist, it's boring and a waste of RSC space.

I could apply the same logic of "Well, why don't you keep the old HoP outfit around and call it "retro hop uniform" 'cause it doesn't really work like that. People just, for some reason, get more symbiotically attached to HUDs for some indecipherable Freudian reason.

**Comment by TheGreatValvatorez** [comment]
So people can stick with their old huds, theres no reason to completely rework it either, its just simpler to give them the choice between the two like goonstation has with their retro ui which is SUPER old

**Review by ShizCalev — CHANGES_REQUESTED** [review]
> I mean, it could be a new HUD, sure. But _why_ does it need to be. 

Just because you don't **_personally_** like the aesthetic of an existing HUD doesn't mean it needs to be arbitrarily deleted even though it still functions properly. **OTHER** people like the aesthetic is what I was trying to point out by saying the Operative HUD is the one that I use.

Just make this a new option, feel free to even rename the old one to retro or w/e like tralezab suggested. 

I won't budge on this. This is my stance, period.

**Comment by axietheaxolotl** [comment]
> [...] OTHER people like the aesthetic [...]

This has never once been an important factor. In the history of /tg/ spriting. Get a better argument.

**Comment by TheGreatValvatorez** [comment]
You have unlocked new trial.
Add it as a new HUD(Ultimate)

**Comment by Iamgoofball** [comment]
>i was in the works of removing every themed ui other than the default and glass and then letting you color.

did you know that when you don't communicate things to people or stay in the active development channels for a project, people can't magically divine what you are doing?

you don't get to tell the art team "no new UIs" after we literally just merged a new UI in #70474 and you haven't been around our development channels for a month and a half, this is a supreme level of disconnected from the day to day development

it is actually insulting to the work our artists are doing for you to swoop in and say things like this and expect to be taken seriously with some form of gravitas because you literally have not been involved in discussions in our art channel where the artists do their work since 5/25 of this year

Discord_g99Qgp6tv5

@Twaticus please intervene so art team time isn't wasted because the headcoder in absentia chose not to be involved in the basic development processes our codebase runs on(be active in our development channels) and is now upset that decisions were made without them being around

**Comment by Wallemations** [comment]
My previous recommendation of making the dot lights on the hand parts into more noticeable brackets still stands, but the whole hud looks very clean in general otherwise.

**Comment by TheGreatValvatorez** [comment]
then again you could have multiple huds and then let people color in whatever is the inner section to their preference

**Comment by Mothblocks** [comment]
get off the high horse, goof. not only is this something i have been talking about directly with art team for a long while before this, and not only was i publicly collecting data on the off shoot UIs that aren't compatible with recoloring like retro, but you are acting high and mighty over a comment that is explicitly non-blocking.

**Comment by Mothblocks** [comment]
> this, in reality, isn't much different from any other HUD. it doesn't move anything, it doesn't change anything. and it doesn't add anything. The only changes are in framing, which don't really matter all that much. It's an aesthetic change in the most literal sense possible.

it is a UI that can't possibly have a general system added to it and will always require manual intervention in order to add any new UI elements. that is my point. i want less of those, not more.

**Comment by Majorkite** [comment]
>I mean, it could be a new HUD, sure. But why does it need to be.

why does it have to be the ONLY option dude like what is this uno reverse card nonsense get real

**Comment by Iamgoofball** [comment]
>get off the high horse, goof. not only is this something i have been talking about directly with art team for a long while before this, and not only was i publicly collecting data on the off shoot UIs

and where is the publicly available documentation of these conversations with the art team, and the information from you about collecting data on "off-shoot UIs" that you discussed in a place that reasonable good faith contributors can see?

hidden conversations behind closed doors is not how this codebase is ran and it is not how we do things around here for precisely this reason

>but you are acting high and mighty over a comment that is explicitly non-blocking.

you are a headcoder, you saying things like ":-1: i was removing all themed UIs" in response to a PR about a themed UI is inherently blocking 

if you don't see that then please convene with oranges and ninjanomnom about the community understanding of what the headcoder role is and how your actions and statements as headcoder are interpreted by the maintainers and developers working on this project

>adding a new UI element should not require me to go through several uniquely aesthetic'd themes

this ship sailed when we got an art lead and stopped allowing codersprites to go to live, sorry that you had to find out this way but we're already well past the point of artists being required to be involved with the process

if you want to add clothing, the clothing has to pass the smell test of our art maintainers and art lead, you can't just slap some junk together in dreammaker in 5 seconds and ship it to master anymore, it's not 2015

when the wallening goes through, you will need an artist involved to make sprites that conform to the new perspective and artstyle the wallening is invoking for sprites on the map

our art team has regularly stepped in and said no to things that don't conform to the new aesthetics we're deploying across the codebase in preparation for and part of the wallening visual rework of SS13

i understand the frustration here, but at the end of the day "how much do I have to pay the artists to sprite this for me" is now a fundamental part of our development pipeline here at /tg/ and you should understand this if you're going to be trying to call shots on the art pipeline here at /tg/

**Comment by Iamgoofball** [comment]
i'm not asking you to start shit here i'm just asking you to acknowledge that what you perceive as idle off-hand comments have significantly more impact than you think they do on the development process because of your new role as headcoder

**Comment by Iamgoofball** [comment]
also if you won't read the rest of that comment i'll put the more important part in here:

>adding a new UI element should not require me to go through several uniquely aesthetic'd themes

this ship sailed when we got an art lead and stopped allowing codersprites to go to live, sorry that you had to find out this way but we're already well past the point of artists being required to be involved with the process

if you want to add clothing, the clothing has to pass the smell test of our art maintainers and art lead, you can't just slap some junk together in dreammaker in 5 seconds and ship it to master anymore, it's not 2015

when the wallening goes through, you will need an artist involved to make sprites that conform to the new perspective and artstyle the wallening is invoking for sprites on the map

our art team has regularly stepped in and said no to things that don't conform to the new aesthetics we're deploying across the codebase in preparation for and part of the wallening visual rework of SS13

i understand the frustration here, but at the end of the day "how much do I have to pay the artists to sprite this for me" is now a fundamental part of our development pipeline here at /tg/ and you should understand this if you're going to be trying to call shots on the art pipeline here at /tg/

**Comment by Twaticus** [comment]
> 👎 adding new/changing existing pieces of the ui was already hard enough with our current themes, we experienced this during combat mode, i dont like that we're making ui less consistent with each other making this process harder. 

yall should not have to worry about this stuff. if new ui elements are needed for huds just let us know we can take care of the sprite busywork

> i was in the works of removing every themed ui other than the default and glass and then letting you color.

now this i really like since all our current huds are just midnight recolors minus retro. but i dont see why a recolorable hud and new themed huds couldnt coexist. players could tweak the basic hud to the colors of their liking, or pick from a selection of crafted themed huds i think its a win-win

**Comment by Mothblocks** [comment]
the issue is one of dev UX. in the same way that we rarely see changes to maps ever since we decided to have five of them, having to update multiple UI themes makes every change to it far more frustrating and more likely to drop out

of course changes to UI come far less frequently than mapping ones would, but i have first and second hand experience with how frustrating it is to have to update every UI, especially retro, to add anything new, to the point where i just don't bother adding anything new

**Review by Twaticus — CHANGES_REQUESTED** [review]
as for the sprites itself, the active hand needs changes. it looks great on its own but in practice i just dont think it will work. too many items will cover the entire active hand indicator.

~~make it a new hud instead of a replacement for now until custom huds are a thing then you can rename it to operative if you want its no biggie~~

**Comment by Iamgoofball** [comment]
>of course changes to UI come far less frequently than mapping ones would, but i have first and second hand experience with how frustrating it is to have to update every UI, especially retro, to add anything new, to the point where i just don't bother adding anything new

we have an official spriting and mapping team, they can and will support us with getting new additions baked into the art/maps.

**Review by Imaginos16 — APPROVED** [review]
I approve of this spritework since this was an idea I wanted to put into practice ever since I've created the Trasen-Knox HUD (https://github.com/tgstation/tgstation/pull/70474),  as hinted by my quote:
>This is all as a step for upgrading and changing how the HUDs we interact with on a daily basis can be upgraded in the future to be more appealing visually!

While I really do not want to stoke the flames any further, you have to understand Mothblocks, that we as a sprite team exist specifically to not only improve the visuals of the game, but also help coders when they desire an artistic touch to their feature. I am legitimately, a ping away from helping you out with the biggest smile I can imagine.
>not only is this something i have been talking about directly with art team for a long while before this

This is the only other thing I genuinely have a problem with because in not a single moment from my recollection, do I remember you talking about HUDs with me or Twaticus, though admittedly we both have a bad memory. What I *do* remember however, is you discussing savefiles and what people have enabled or disabled. This is where you brought up the fact that a very small, undisclosed amount of people (this conversation was not public) had retro HUD on.

Finally, as Twaticus said, I don't see why us both cannot shoulder the burden to help coders when they need to. That's what we signed up for. We're not just merge bots for visuals. I think your idea can very well and easily coexist with my vision as well.

**Comment by Mothblocks** [comment]
> This is the only other thing I genuinely have a problem with because in not a single moment from my recollection, do I remember you talking about HUDs with me or Twaticus, though admittedly we both have a bad memory

To be fair it was probably a year ago at this point, I'm not mad

**Comment by Imaginos16** [comment]
> To be fair it was probably a year ago at this point, I'm not mad

Happens I guess.

**Comment by CRITAWAKETS** [comment]
> > [...] OTHER people like the aesthetic [...]
> 
> This has never once been an important factor.

...why shouldnt it be? main purpose of a proper art team for a server is to get a proper spriting direction that people enjoy, rather than whatever the spriter ends up doing

as for the sprites itself, it needs less contrast and brighter inlets/darker outlines for the equip regions (and a tinge of glowing green could be good), the syndicate's always had kind of a polymer look to it with some more "neon" lights, sometimes going on fluorescent.

also i have 0 fucking clue what mothblocks is saying about UX and themed UIs making things harder when the goal with greyscale UI is to make it so there's less UIs to manage and update, especially if it works with GAGS so that even the UIs with more pizazz work with it

**Comment by ShizCalev** [comment]
Outside of the previous review, some feedback on the UI itself;

image
This is great. Can easily tell at a glance that the hand on the left is active. 

image
This seems... a little confusing. Are the eyes selected here? If not, it seems like it would be difficult at a glance to tell exactly what you're targeting, which may present an issue. 




image
Looking at these, you can easily tell what your status is. You can't rest, you can't throw, combat mode is off. Clear, muted colors.
image
Looking at this, Right hand is active (outlined + shaded), left hand is offhand and empty. Clear, muted colors. 

image
The inventory seems... to have inconsistently contrasting elements compared to the rest of the HUD. Empty slots have heavy shading and bright outlines, which to me give them more of an appearance of actually having an item in them at quick glance, where as the actually occupied slots are just the items with no outlines, no shading, they seem more like background elements. 

It's gone from using the muted colors / embossed feel of the other HUD elements representing empty / off / disabled, and is instead using the highlighting which is meant to draw the eye in more.

**Comment by Fikou** [comment]
> I could apply the same logic of "Well, why don't you keep the old HoP outfit around and call it "retro hop uniform" 'cause it doesn't really work like that. It's a redesign, it's a new take, it's a refresh for the modern age. People just get more symbiotically attached to HUDs for some indecipherable Freudian reason.

no you cant, huds are viewable for the user only, its something their user will be seeing 24/7, and they want to see what they prefer. huds dont make ss13 ugly like how old clothing coexisting with new or whatever. theres no issue with a bunch of aesthetics options that are user only.
and for the "midnight but hue shifted" yeah it is, but it looks nice, and theres no customization. people just want red sometimes

@Mothblocks what prevents you from adding custom colored huds, with spriter curated ones like this one as unique themes for their enjoyers

**Comment by Mothblocks** [comment]
> @Mothblocks what prevents you from adding custom colored huds, with spriter curated ones like this one as unique themes for their enjoyers

you're missing the point. the point of multi colored huds is for one purpose and one purpose only: to lower the amount of dmis you have to edit when you add a new UI element to the game. that a player could customize it is just an obvious side benefit. that is why having spriter curated ones is something i am concerned about

**Comment by Fikou** [comment]
> > @Mothblocks what prevents you from adding custom colored huds, with spriter curated ones like this one as unique themes for their enjoyers
> 
> you're missing the point. the point of multi colored huds is for one purpose and one purpose only: to lower the amount of dmis you have to edit when you add a new UI element to the game. that a player could customize it is just an obvious side benefit. that is why having spriter curated ones is something i am concerned about

with first hand experience adding an ui element (i needed to replace the skills button with navigation for every hud) it wasnt that big of a deal, and i doubt we'll really see many fully themed uis, besides, everything has templates, and we also have a spriter team that could help

**Comment by optimumtact** [comment]
cool PR

**Comment by optimumtact** [comment]
note that if twat wants this to replace the original hud i'm open to that I don't see why it's a problem

**Comment by Twaticus** [comment]
this is a definite improvement from the original operative hud, im good with this being a replacement instead.

**Comment by LemonInTheDark** [comment]
> with first hand experience adding an ui element (i needed to replace the skills button with navigation for every hud) it wasnt that big of a deal, and i doubt we'll really see many fully themed uis, besides, everything has templates, and we also have a spriter team that could help

Agree
It's a little time consuming, but it's mostly just recolors. GAGS to squish some stuff down would be nice, but it doesn't need to be applied everywhere, and I don't think we need to limit hud creation just for its sake

**Comment by Mothblocks** [comment]
I definitely do not agree especially given how different this HUD is from the rest

**Comment by Timberpoes** [comment]
If it's cool and thematic and kicks a little visual ass, I think it allows players to enhance their game to have additional HUDs. The interface can help you immerse yourself in our game world and having some neat thematic options and handcrafted passion project alternatives can significantly enhance a game. Of course, providing the options to change them aren't buried away in nested submenus nobody ever looks at.

GAGS allows end-users to customise, but I sometimes feel like it also shoehorns assets into being generic enough so they can be recoloured.

To me, there's honestly little that can compare to a handcrafted art asset or set of art assets that have had time, care and genuine passion put into them by people. I think this is just as prudent even when it comes to UIs.

And on a more abstract level I see it as a part of developing skills and widening the contributor pool's collective talents. Giving room for good artists to flex their creativity promotes people developing their skills within our sphere of influence, with all the benfits that grants to the tgstation project.

I'm rambling because it's past 2am and I need sleep and I have work tomorrow, so I wish everyone an excellent [morning/day/afternoon/evening/night]. Hopefully I'm not just being a dumbass.

**Comment by Mothblocks** [comment]
I still don't agree on the cost of new UI elements, and even the hand crafted stuff gets dodgy if the original person isn't around to help with creating new ones. They look good but undoubtedly increase maintainability, and make creating anything related to UI less desirable, which I have first and second hand experience with. We have noticed similar effects with maps (except instead of inconsistencies with different contributors, it's inconsistencies in intent). The art team is very well intentioned and can be as helpful as they want to contributors but it is undoubtedly a dropoff point when a change you make needs to involve and block on several different people. Also I also am not even really talking about GAGS and was just referring to being able to color the backgrounds of stuff.

I understand the value of hand crafted assets and do think this looks very nice which is why I am not blocking this PR but rather just want people to consider that stuff like this isn't as simple and free as it seems.

**Comment by Wallemations** [comment]
I have but one extra question;

What does the 1976 Andrew Gold song _Lonely Boy_ off the album **What's Wrong With This Picture?** have to do with this PR, as the title implies?

This is imperative to my understanding of our HUD systems.

**Comment by improvedname** [comment]
i just dont like how everything is red when selected body parts etc red on shaded red feels weird can't that part just be green for more clarity

**Comment by optimumtact** [comment]
@ninjanomnom you're needed

**Comment by Mothblocks** [comment]
@optimumtact I am NOT blocking this or conflicting with you I am just frustrated

**Comment by axietheaxolotl** [comment]
image

selected items are now more apparent, as per spritetainer request

**Review by Twaticus — APPROVED** [review]

**Comment by Serxule** [comment]
replacing the current one with this isnt really a good idea (until greyscale/custom huds are in), it looks cool and all but there's way too much contrast and its very loud, and like shiz said

> The inventory seems... to have inconsistently contrasting elements compared to the rest of the HUD. Empty slots have heavy shading and bright outlines, which to me give them more of an appearance of actually having an item in them at quick glance, where as the actually occupied slots are just the items with no outlines, no shading, they seem more like background elements.
 It's gone from using the muted colors / embossed feel of the other HUD elements representing empty / off / disabled, and is instead using the highlighting which is meant to draw the eye in more and represent what you do have / can do.

**Comment by optimumtact** [comment]
@Twaticus this is with you

**Comment by TheGreatValvatorez** [comment]
> replacing the current one with this isnt really a good idea (until greyscale/custom huds are in), it looks cool and all but there's way too much contrast and its very loud, and like shiz said

won't be a issue if #70733 gets merged

**Pull request merged**
