### PR TITLE
Tram signal and station improvements

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
-New sprites for tram crossing signals in titanium, acting as an extension of the railing/decals in front of the tram, acting like an anchor for the end of the railing instead of the misaligned corner, with a more futuristic look.
-The speed of amber/red flashing is slowed a bit from current to be less distracting.
-Redo of the decals on the floor in front of the tram, it was leading you into the vending machine.
-Like any tram, the yellow hazard bump floor tiles in the station.
-Moved the vending machines to be flush with the wall.

image

## Why It's Good For The Game
Tram TLC, looks more space station-like
## Changelog
:cl: LT3
imageadd: New railing pillar tram crossing signals.
qol: Vending machines next to the tram are now against the wall.
fix: Tramstation floor decals no longer guide you to walk into the vending machines.
add: The tram stations now have no-slip hazard floor tiles so you don't accidentally slip and get smacked. Feel free to still run into it anyways, medbay has a counter now so they'll know.
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
> Is this the same green the lights already use? It feels more neon and sickly Might just be a consequence of it being a large unbroken strip now though

The old ones are #5FFF59 which are brighter, it's just having a strip now makes it stand out. Green and amber I reduced their brightness to account for that.

**Comment by Paxilmaniac** [comment]
These seem a fair bit lower in actual sprite quality than the old ones did, and the old ones were pretty fine looking already?

**Comment by lessthnthree** [comment]
The current one sticks out and the railing corner isn't even aligned.

image

**Comment by lessthnthree** [comment]
I did go and add some more shading to add a chunkiness to the sign.

image

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
Mmm, I don't like it much. Especially how the gradient is done on the signpost itself. That's a really bad practice with pixel art. Not to mention how the current one obeys perspective better than your proposition.

**Comment by lessthnthree** [comment]
> Mmm, I don't like it much. Especially how the gradient is done on the signpost itself. That's a really bad practice with pixel art. Not to mention how the current one obeys perspective better than your proposition.

I'll keep working on it. I want it to look like an extension of the railing.

**Comment by lessthnthree** [comment]
Better, new railing integrated sprite, smaller lightbar so it's not as bright.

**Comment by lessthnthree** [comment]
image

**Comment by lessthnthree** [comment]
Yeah I get the perspective issue now, I'll look at repositioning.

**Comment by lessthnthree** [comment]
Made the signals taller so characters can pass under it.

**Comment by lessthnthree** [comment]
Also added the decal wrapping everywhere else on Tram has

**Comment by AffectedArc07** [comment]
This PR flagged up some MDB2 fails for me to (get someone to) look into

**Comment by lessthnthree** [comment]
> This PR flagged up some MDB2 fails for me to (get someone to) look into

Yeah I just literally remapped it from scratch with a brand new tramstation.dmm from master a half hour ago.

**Comment by lessthnthree** [comment]
Fixed map merge conflict.

**Review by Mothblocks — APPROVED** [review]
@Imaginos16 Please re-review sprites

**Comment by Mothblocks** [comment]
Also conflicts

**Comment by lessthnthree** [comment]
> Also conflicts [again]

Yeah that just merged mail sorting PR made me have to edit and repush.

**Comment by lessthnthree** [comment]
@Mothblocks I've poked for a review, but keep having to update this as it sits here.

**Comment by LemonInTheDark** [comment]
image
is this meant to look like this

**Pull request merged**
