### PR TITLE
WALLENING MEGA TURBO XTREME FIX

### PR DESCRIPTION
**Pull request by Alomga**
### About The Pull Request

Wallening

### Why It's Good For The Game

The list of reasons on why it's good for the game is quite lengthy but lemme give out a short example

1. Improved visual clarity - All buttons, wallmounts, posters and the likes are extremely visible now, you can easily say what wall you're dealing with and don't need to constantly shift or alt click everywhere to interact with everything
2. Removes a lot of bugs - ALL OF THE WALLENING BUGS GONE IN A FLASH
3. Allows more maps to be used - Currently only Tram and Delta are playable, that is not good for the game, this one simple trick will allow you to use all of the maps we have to be played AND allows mappers for much more creativity than the current walls (especially that some left :v)
4. Doesn't make people sick - I dunno how about you guys but I value people's health and good time more than anything and this change allows them to play their spessman game without feeling sick from motion sickness
5. Improved looks (CONTROVERSIAL) - Now personally I find the wallening walls to be quite nice from purely artistic sense of things, even if they fail at basically any function and especially ore walls that never get made can be heckin bangers, but not everyone agrees with me and some find simple grey squares more pleasurable to the eyes
6. This isn't shoved down everyone's throat despite reaching 2:1 negative to positive reactions because I don't have a backing from maintainers who invested money and time into me only to then be allowed to make calls about merging this PR because "there's no better system"

### Final words

You might ask me: "Alo, is it really worth the gitban to make a shitpost PR reverting the wallening?"
And the answer is: No, fuck no, that's a horrible idea especially since I would dream that in the far future I'd learn coding enough to make contribitions to the game myself but we live laugh love, you can call this a result of extreme frustration with the fact the game I deeply loved for many years, even those during which I couldn't bring myself to play it, gotten a lot worse in my opinion due to ego project of 12+ people

### CODE REVIEW

**Comment by Sadboysuss** [comment]
gitban speedrun any%

**Comment by Pickle-Coding** [comment]
Just going to make this useless comment before it gets locked.

**Comment by DATA-xPUNGED** [comment]
> someone's ego project
Be accurate with your shitpost, TThe wallening was made by like 12 different people, you should account for this in your wording

**Comment by Alomga** [comment]
> > someone's ego project
> 
> Be accurate with your shitpost, TThe wallening was made by like 12 different people, you should account for this in your wording

Is it better?

**Comment by Jacquerel** [comment]
If I close this before oranges sees it the it is possible he might not gitban you for wasting everyone's time, good luck with your future contributions

**Comment by Alomga** [comment]
> If I close this before oranges sees it the it is possible he might not gitban you for wasting everyone's time, good luck with your future contributions

Lovely and thank you, hopefully next time if I ever make a PR (and will be able to) it will be an actual and good one that will do something for the game

**Comment by CliffracerX** [comment]
@Alomga begging you to leave this branch up for posterity so downstreams have something to work from for Last Stable TG

**Comment by Time-Green** [comment]
> @Alomga begging you to leave this branch up for posterity so downstreams have something to work from for Last Stable TG

That’s really not how that works

**Comment by Sadboysuss** [comment]
Just take the commit before wallening and cherry pick mirror prs you want? You don't need this branch as a base

**Comment by CliffracerX** [comment]
> > If I close this before oranges sees it the it is possible he might not gitban you for wasting everyone's time, good luck with your future contributions
> 
> it did not work

I've accidentally sent a couple nuclear bombs in PR form at you over the years, I don't think (1) meme PR about one of the most controversial changes ever is worth a gitban

**Comment by ZeWaka** [comment]
>no changelog

smh

**Pull request closed without merging**
