### PR TITLE
Self-CPR fix.

### LINKED ISSUE #54368: You can perform CPR on yourself
## Round ID:
Doesn't matter

## Testmerges:
doesnt matter

## Reproduction:
click yourself while in soft crit to stop yourself from dying

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title.

## Why It's Good For The Game
This will fix #54368. No more hamon breathing.

## Changelog
:cl:
fix: You can't perform CPR on yourself anymore.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
😏

**Review by Mothblocks — CHANGES_REQUESTED** [review]
test your code

**Comment by Ghommie** [comment]
I just couldn't fix that asinine mistake yesterday. Please spare me from testing such a simple early return. :joy:

**Comment by LemonInTheDark** [comment]
If you're fixing something please make sure it's properly fixed

**Pull request merged**
