### PR TITLE
Adds *dab to the game.

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title
:cl: Deitus:
add: Adds *dab emote
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
NO NO NO

**Comment by PKPenguin321** [comment]
FIRST

**Comment by PKPenguin321** [comment]
FUCK

**Comment by Qbopper** [comment]
STOP

**Comment by dannno** [comment]
Oh, slaps me on the knee.

**Comment by Armhulen** [comment]
HAHAHA

**Comment by Armhulen** [comment]
I'M FIRST FUCK YOU

**Comment by PKPenguin321** [comment]
I AM BANNING YOU

**Comment by Iamgoofball** [comment]
blame deitus

**Comment by BeeSting12** [comment]
no

**Comment by Earthykiller127** [comment]
Yes please!

Le DAB X  D haha DAB again HAHAH DAB, DAB, DAAB, haaHA X D

**Comment by jughu** [comment]
Not to be confused with *dap

**Comment by KorPhaeron** [comment]
literally reddit

**Comment by FantasticFwoosh** [comment]
This is why we can't have nice things. Nice mature community.

**Comment by gbasood** [comment]
>nice things
>dabbing
🤔

**Pull request closed without merging**
