### PR TITLE
Blacklists some incompatible quirks

### LINKED ISSUE #37669: you can take both pineapple traits at once
>like pineapple
>hate pineapple
???

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
fix: Certain incompatible quirks can no longer be taken together
/:cl:

Fixes #37669

### CODE REVIEW

**Comment by improvedname** [comment]
Some people just hate pineapple

**Comment by Therapist1** [comment]
Why are you including jolly, depression and apathetic? They function perfectly normal together, (Jolly and depression give you mood swings, apathetic reduces the effects of both.)

**Comment by Tlaltecuhtli** [comment]
what is bipolar

**Comment by Mickyan** [comment]
@Therapist1 It's used to cheese the mood system by using depression+apathetic, if you want mood swings make it it's own a quirk

**Comment by AlexTheSysop42** [comment]
Why are you blacklisting jolly then

**Pull request merged**
