### PR TITLE
New Heretic rune sprites & animations

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

I made some magic circle animations for a downstream antagonist (coming to tg 2023?) and people told me "Jacquerel heretic should also do something like this" so after several hours of madness now they do.

image

This PR redraws the Heretic Transmutation Rune, and adds new effects for drawing and unsummoning it.
The below videos are slightly outdated because the base colour is a tad lighter now but you'll get the idea.

https://user-images.githubusercontent.com/7483112/210192981-0a34f3f9-ec78-4332-8148-896886d4d344.mp4

The animation is the same if you use the Codex Cicatrix, just the gaps between steps are shorter.
Additionally, your rune effects are now coloured based on your heretic path.

https://user-images.githubusercontent.com/7483112/210192985-4bda65af-5655-43a2-9685-0ca4d1519c87.mp4

Now the only caveat I can think of here is that as the 30 second long drawing process now comes with flashy effects this _does_ make you potentially more visible to random people who wander into your secret den than previously, however as that would require them to overlook you standing completely still with a _burning hand_ I don't think that should be a massive issue. 
Nobody was relying on the extremely long action bar having no animation to draw runes in the middle of rooms full of people... right?

## Why It's Good For The Game

It looks cool.

## Changelog

:cl:
imageadd: New look and animations for the Heretic's transmutation rune
/:cl:

### CODE REVIEW

**Comment by trexter5555** [comment]
damn that looks cool

**Comment by improvedname** [comment]
would also be super cool if each heretic path had their own kind of circle

**Comment by Serxule** [comment]
i have a feeling the animations gonna break when the servers under heavy load or high TD

**Comment by Xander3359** [comment]
Holy fuck, making a boring aspect of heretic so much cooler just makes the antag that much more awesome to play.

**Comment by Jacquerel** [comment]
> would also be super cool if each heretic path had their own kind of circle

It would, unfortunately it's kind of a choice between "elaborate animation" and "multiple different designs" and I went with the former.
Also, it's completely possible to draw a rune _without_ having chosen a path, which you need to account for.

> i have a feeling the animations gonna break when the servers under heavy load or high TD

Likely true, though not a lot I can do about it. 
Fortunately the worst outcomes are "it suddenly finishes and looks a little weird" and "it looks done for a long time while the bar keeps filling", neither of which are too terrible.

**Comment by SomeoneYouProbablyKnow** [comment]
This is no doubt high quality but for some reason i like the old one more (might be the colors, not a fan of the jet black lines but you kinda need em for the animation i guess) but both are good so eh just leaving my 5 cent

**Review by Fikou — CHANGES_REQUESTED** [review]
delete the old ones

**Comment by axietheaxolotl** [comment]
me when #000 black :yum:

i didn't the know the heretic's powers extended to the power to literally break the fundamental laws of light. news to me.

**Comment by KittyNoodle** [comment]
the pure black actually fits really well, it feels alien and unnatural, like a hole in light and reality itself. perfect for an antagonist themed around the eldritch

**Comment by axietheaxolotl** [comment]
> the pure black actually fits really well, it feels alien and unnatural, like a hole in light and reality itself. perfect for an antagonist themed around the eldritch

Please shut up

**Comment by Jacquerel** [comment]
Someone commented on discord that it's not quite centered and this is unfortunately true but I can't centre it any _more_ without it slightly overlapping adjacent walls. It's _close_ at least.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
