### PR TITLE
KA now use the timer subsystem

### PR DESCRIPTION
**Pull request by coiax**
CHANGELOGS ARE FOR NERDS.

### CODE REVIEW

**Comment by xxalpha** [comment]
Some KA subtypes do not use cool down values that are multiples of 5.

**Comment by Fox-McCloud** [comment]
:-1: 

This won't work. THe timer subsystem fires ever 0.5 seconds, as such, it can only hit multiples of 5, naturally---the reason why this is a `spawn` is because it's a veryyyy precise timer, and the timer SS is awful at precision timers.

This being a spawn will have zero impacts on end-game performance and will actively negatively impact player experiences who play miner.

**Comment by xxalpha** [comment]
Yeah, KA shooting isn't even close to being one of the most called procs. It's a non issue.

**Comment by MrStonedOne** [comment]
well, after stoned mc, it will fire ever 2 byond ticks, so that won't be an issue =P

**Comment by RandomMarine** [comment]
Backend refactors really don't need a changelog entry.

**Comment by coiax** [comment]
I'm making this change because it was called an example of something that could use the timer subsystem. It's not like it's a difficult or ugly optimisation. I've tried it out, a regular KA feels the same to me, but I'm not in the group of hardcore miners. We can table the change until MC Stoned drops a hot new track. But I don't think outside of using fast process we can keep a decisecond accuracy

**Comment by Jordie0608** [comment]
I dislike this just for what you've done to the poor desc.

**Comment by xxalpha** [comment]
That description is too big anyways.

**Comment by MrStonedOne** [comment]
I dislike this just for what you've done to the poor desc.

**Comment by KorPhaeron** [comment]
This doesnt need a changelog

**Comment by optimumtact** [comment]
I'm not sure about this

MSO's subsystems tend to lag when lots of things happen and there is no priority yet so it might suddenly decide to hold teh timer subsystem up multiple ticks

**Comment by Thunder12345** [comment]
>>I dislike this just for what you've done to the poor desc.

**Comment by optimumtact** [comment]
Well if anything it will cause MSO to finish his timer changes

**Comment by Jordie0608** [comment]
>desc change

oranges confirmed for punch-card sympathizer

**Comment by KorPhaeron** [comment]
Stop ruining miner reeeee

**Comment by xxalpha** [comment]
Lavaland status: ruined.

:tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine: :tangerine:

**Comment by Fox-McCloud** [comment]
welp.

Now all KA's take 2 seconds to recharge.

**Pull request merged**
