### PR TITLE
Revert Hand Of God

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/-tg-station#11803
# NO CHANGELOG

### CODE REVIEW

**Comment by RemieRichards** [comment]
listen here you little

**Comment by Iamgoofball** [comment]
# CENSORSHIP

**Comment by Bawhoppen** [comment]
revert it because hog is still shit

**Comment by RemieRichards** [comment]
@Bawhoppen "hog is still shit"
that's your opinion buddy.

**Comment by Thunder12345** [comment]
Salty

**Comment by Shadowlight213** [comment]
Revert Bawhoppen

**Comment by Aloraydrel** [comment]
Hog is fun tbqh

**Comment by Iamgoofball** [comment]
tbvh fam hog is the best gamemode

**Pull request closed without merging**
