### PR TITLE
Healing symptoms no longer kill jellypeople

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Stops starlight condensation, plasma fixation and radioactive resonance from killing jellypeople

## Changelog
:cl:
fix: Healing symptoms no longer kill jellypeople
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
I think it's a feature and not a bug. Plus will it heal toxins now? Or just don't do anything to toxin damage

**Comment by SmArtKar** [comment]
> I think it's a feature and not a bug. Plus will it heal toxins now? Or just don't do anything to toxin damage

Right now it damages jellypeople with toxins, after this PR gets merged it will instead heal their tox damage like it does to everybody else

**Comment by ZephyrTFA** [comment]
The symptoms hurting jellypeople is intended

**Comment by Mothblocks** [comment]
if it wasnt intentional it is now

**Pull request closed without merging**
