### PR TITLE
Resprites face scarf to be more GAGS friendly

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
Resprites the face scarf to a lighter color scheme, allowing it to be colored more accurately than the older grey sprites.

dreamseeker_zcti15DW83

## Why It's Good For The Game
The older sprite was all grey which makes coloring it a bit of a hassle to get the desired color. This resprite should allow better customization.

## Changelog
:cl: Hardly
image: Resprited face scarf to be more GAGS friendly
/:cl:

### CODE REVIEW

**Comment by Hardly3D** [comment]
Not sure why bigon is showing as modified, I'm pretty confident I didn't touch it.

**Comment by necromanceranne** [comment]
It could be an era. It could be that your repo is out of date.

**Comment by MercuryArrow** [comment]
I need this in my life. Having to adjust the GAGs colour an order of magnitude lighter to match other things every time and being completely unable to make it white or bright yellow always irked me.

**Comment by EEASAS** [comment]
i have a request: can you make subtypes of this face scarf for different colors like black, red, purple etc so mappers can use them or they can be used in outfits

**Comment by Hardly3D** [comment]
> i have a request: can you make subtypes of this face scarf for different colors like black, red, purple etc so mappers can use them or they can be used in outfits

Interesting idea, I'll consider this in a separate PR.

(I did not forget about this, I'm just busy)

((I forgot about this))

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
