### PR TITLE
Revert "Legion soul now only heal when implanted" Lzimann did not do what Kor said he entirely gutted legion cores to only be useful if surgically implanted

### PR DESCRIPTION
**Pull request by Kromgar**
Reverts tgstation/tgstation#20352

Its pretty clear from what Kor said he thought you should be able to implant a legion core and use it as a free get out of crit card instead of infinite healing but Lzimann gutted the entirety of legion cores

What Kor Posted

> Maybe we could compromise and let you get one full heal out of the organ when implanted and you crit.

The issue in the Pr was infinite invisible healing from having it implanted not the fact you could use them on yourself

he didn't even remove stabilizing serum

PS: I can't code so i just made a revert pr cuz im bad

### CODE REVIEW

**Comment by Ninja137** [comment]
It's infinite healing in small enough amounts to be functionally irrelevant. The only time it saves you is if your attacker goes "Well, he's down, time to ignore him and run away for some reason".

You don't die to normal lavaland mobs, and the big ones gib you anyway.

**Comment by optimumtact** [comment]
The infinite healing is not coming back.

Other items gutted can be added back in this revert pr however if you can update it.

**Comment by TechnoAlchemisto** [comment]
This should probably just bring back the apply on use vs a full revert

**Comment by KorPhaeron** [comment]
Techno opened a good revert

**Pull request closed without merging**
