### PR TITLE
[WIP][DNM] Changes walls, girders, windows and grilles to kind-of-3/4

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: # 
:cl: nicbn
imageadd: Walls, girders, windows and grilles sprites have been changed.
/:cl:

This is far from done, but I want some feedback. I'll post some screenshots when it's ready.
I won't change the shuttle sprites for now.

Most of the sprites will look kind-of the same but 3/4, except for the clockwork one, the cult one and the reinforced one.

How reinforced will look like:

### CODE REVIEW

**Comment by MMMiracles** [comment]
i hope you're also ready to re-do every wall-mountable object as well or this is going to look like absolute ass in-game

**Comment by praisenarsie** [comment]
^

i suggest stop what you are doing right now nicbn

**Comment by nicbn** [comment]
I will do that later

**Comment by MMMiracles** [comment]
i hope 'later' happens in this pr, because else this isn't gonna go anywhere like past attempts

**Comment by praisenarsie** [comment]
you madman, also i have these walls if you want them or to adapt on them

dreammaker_2018-03-04_20-43-22

**Comment by TrustyGun** [comment]
Any pics ingame?

**Comment by nicbn** [comment]
I'll take pics later

@praisenarsie The ones I'm spriting are in a different format, compare to the reinforced one and you'll see they are shorter in the Z-axis and the north part is not hidden by the top.

**Comment by praisenarsie** [comment]
alright so can you actually not make the girders 3/4 dear god

no maintainer is stopping you right now because they'll know this isn't going to work, also i swear if you haven't changed the way smoothwalls work with your walls i'm gonna yell

**Comment by Kromgar** [comment]
This is a horrible idea

**Comment by Xhuis** [comment]
I will never support 3/4 turfs. :-1:

**Comment by nicbn** [comment]
The 3/4 superiority will never be scratched by your pointless pointlessness

**Comment by MMMiracles** [comment]
liking 3/4 perspective makes your opinion only worth 3/4th of a person

**Comment by MrDoomBringer** [comment]
@nicbn did you sprite these or are they ported from somewhere?

**Comment by praisenarsie** [comment]
he sprited them i'm fairly sure, the only place with 3/4 walls is goon

**Comment by Potato-Masher** [comment]
Colonial Marines also uses a funky perspective of walls.

**Comment by praisenarsie** [comment]
oh right but that's closed sourced and we all know that closed source repos suck except goon, goon chill because they released their shit twice

**Comment by WJohn** [comment]
This needs a whoooole fuckload of pictures of what it's like in game with every wall type, window, grille, lattice and so on.

**Comment by nicbn** [comment]
I cannot massively improve every wall sprite, sorry. Anyway I'm satisfied with the clockwork and reinforced ones.
Also, the walls shouldn't be polluted with details as they are just walls, and are everywhere. I'll take pictures after I finish sprinting everything.

**Comment by nicbn** [comment]
Also the work I'm putting on it is too much and the feedback is too bad, so I'll probably drop this

**Comment by Qustinnus** [comment]
@praisenarsie if you're gonna post someone else sprites try to credit them when you post them.

**Comment by ChangelingRain** [comment]
the clockwork ones are much lower quality, and the necropolis walls are, uh, fucking awful. they don't match the necropolis tile colors and gate colors, and they're way lower quality as well

**Comment by ChangelingRain** [comment]
also on top of that, reinforced walls no longer have deconstruction states, and nearly every nonstandard wall is just using a recolored version of the same template.

**Comment by Spaceinaba** [comment]
please god no 3/4ths machinery and stuff looks okay but dear fucking god dont do this to the walls I will literally quit the game

**Comment by Qbopper** [comment]
these sprites are very competent and look pretty good and I do not ever want to see them in SS13

**Comment by nicbn** [comment]
@ChangelingRain They will have deconstruction sprites, and these will even smooth with the walls

**Comment by nicbn** [comment]
Too much work for too much hate

**Comment by nicbn** [comment]
If anyone wants to use the sprites:

**Comment by Poojawa** [comment]
I, for one, actually don't mind it too terribly much. 

But I can understand the radical change.

**Comment by JStheguy** [comment]
The evil has been vanquished,
/tg/station is at peace.

**Pull request closed without merging**
