### PR TITLE
Diskstation map fixes.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Hopefully fixes the last remaining missing wires under doors.
Reworks engineering wiring so emitters have power from SMES.
Moves Medbay APC our of cryo and into maint as it was right next to the Cryo APC, causing confusion
Adds buttons for cargo warehouse door
@Strathcona

### CODE REVIEW

**Comment by WJohn** [comment]
Someone said that a bunch of assistants all spawned on the lobby screen. Did you forget to add assistant spawns? You should probably add those.

**Comment by Shadowlight213** [comment]
@Wjohnston I didn't make the map, so I don't know. I'd prefer to leave adding additional spawn points to the map maker, as I wouldn't know where to put them really. Also, I thought that when there are no avaliable spawn points, it would spawn people in the shuttle.

**Comment by Strathcona** [comment]
Hey all, I'll take a look at this today. Thanks for the heads up.

**Comment by KorPhaeron** [comment]
@Shadowlight213 @Strathcona 

One of you please add two of the new xenobio consoles to the lab

**Comment by Shadowlight213** [comment]
@KorPhaeron I added one. couldn't find a good place for a second one.
Also did some more fixes and tweaks based off of feedback from sybil.

**Comment by Strathcona** [comment]
@Shadowlight213 Can you post a changelog in the DiscStation thread?

**Pull request merged**
