### PR TITLE
Add Drone Shell to Protolathe

### PR DESCRIPTION
**Pull request by octareenroon91**
Make drone shell constructable from protolathe

### CODE REVIEW

**Comment by GunHog** [comment]
Not sure why this is really necessary, but I am not against it.

**Comment by optimumtact** [comment]
:-1: :x: :100: 

Please do not add everything to the RnD department

**Comment by KazeEspada** [comment]
Its already in the RnD department?

**Comment by optimumtact** [comment]
Right sorry, I meant protolathe

**Comment by Aloraydrel** [comment]
na add it

**Comment by optimumtact** [comment]
So help me god I will nerf the protolathe into the ground if this happens

My salt will make a mountain to the sky

**Comment by Zilenan91** [comment]
What about the autolathe?

**Comment by KorPhaeron** [comment]
Isn't the drone printing job/machine like one room away

**Comment by Lumipharon** [comment]
What is the purpose of this PR?

Literally, LITERALLY the only reason for this that I can see, is so that R&D can print their own drones without having to go to robotics, or make their own robofab.

**Comment by octareenroon91** [comment]
this is for drones not humans

**Comment by PKPenguin321** [comment]
Drones are capable of using an exofab

**Comment by coiax** [comment]
Drones have all access and no qualms about wandering into Robotics to use their machines, which are less trafficked than R&D anyway. I mean, I have no objections, I just don't really know why this is needed?

Mind you, R&D can print posibrains, don't know why they can do that.

**Comment by Xhuis** [comment]
What...? Why?

**Comment by KorPhaeron** [comment]
Octareenroon91> https://github.com/tgstation/-tg-station/pull/16733#issuecomment-207198689

KorPhaeron> hi
Octareenroon91> yes: this would help drone colonization elsewhere though
KorPhaeron> because protolathe allows disk transfer right
Octareenroon91> yep
KorPhaeron> alright that makes sense 
Octareenroon91> there are more twisted solutions, but I thought the one line change would somehow be least controversial

**Comment by coiax** [comment]
wait, Exosuit Fabricators don't allow Design Importing?

**Comment by KorPhaeron** [comment]
Design exporting is the important part I think. This lets you put the drones on a disk and crank them out of an autolathe somewhere

**Comment by GunHog** [comment]
Going on a tangent, why do we not just allow the autolathe to connect to the research network? If the RD does not want this for some reason, he can just walk into the rarely visited server room to deny access.

**Comment by coiax** [comment]
I feel like maybe instead of this PR we just make the drone fabricator circuit board be printable.

**Comment by coiax** [comment]
Although, what is the difference between what the exosuit fabricator can produce, and what the autolathe can produce?

The things they both produce are batteries, cybernetic implants, positronic brains. I see no problem with protolathes also producing drone shells, they don't seem that Roboticky?

**Comment by octareenroon91** [comment]
I made this PR so drones might be able to colonize the derelict with autolathe parts and a drone design disk.  There are more elaborate ways to get to the same point, but I think this one-line change does everything elegantly.

**Comment by YotaXP** [comment]
More drones = fun for all :+1: 

I already sneak into R&D to steal floor buffer upgrades.  Why not steal intellectual property as well?

**Comment by octareenroon91** [comment]
As it happens, the protolathe doesn't actually have a 'Misc' category, so you'd have to make use the R&D console's search utility.

The recent addition of drone fabricators to a few maps fills one purpose for this PR, though.

**Comment by YotaXP** [comment]
Ah.  If that's the case, then maybe it would be better to make a drone fab board available instead.

**Comment by KorPhaeron** [comment]
RD can already make drones 2 rooms away

RD can already make the mech fab already and print it in the same room

Drones already have an infinite on station spawner on half the maps anyway

So as far as RD powercreep, its not really noticeable. It will however allow you to bring drone tech disks to autolathes, which could result in some fun maybe. Overall the PR will probably have little impact, but the marginal rewards outweight the non existent risk.

**Comment by optimumtact** [comment]
protolathe nerfs it is then

**Pull request merged**
