### PR TITLE
Fixes blindfolds blinding when not over your eyes

### LINKED ISSUE #36312: Blindfolds blind you if you hold them
Issue reported from  Round ID: 84736 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: 84736.

[Reproduction]: Go to metastation medbay, find the blindfold on the table with the syringe gun, eyepatch, etc. After that, hold the blindfold. You have done the bug which basically makes you temporarily blind despite not wearing it.

### PR DESCRIPTION
**Pull request by silicons**
Fixes #36312

### CODE REVIEW

**Review by vuonojenmustaturska — DISMISSED** [review]

**Comment by SpaceManiac** [comment]
Need to check in `dropped` too, otherwise you'll be able to see again after dropping a second blindfold out of your hands.

**Comment by kevinz000** [comment]
changed to use ref of the blindfolds

**Comment by Qustinnus** [comment]
We need an unequipped proc instead of a dropped proc.

**Comment by XDTM** [comment]
Separation between equipping/unequipping and picking up/dropping for sure

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
