### PR TITLE
remove slowdown from firesuit

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Dunno if something that has THICKMATERIAL and fire resist and is commonly available should have zero downsides to wear---there's literally no reason to NOT wear this item now.

**Comment by Razharas** [comment]
What fox say

**Comment by Dorsisdwarf** [comment]
Do this for the atmos firesuits because they're rare and super-boss

**Comment by Jalleo** [comment]
Atmos firesuit no slowdown standard 0.5

**Pull request closed without merging**
