### PR TITLE
nukies get chest rigs too

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

Lets nukeops buy chest rigs because they couldn't for some reason.

## Why It's Good For The Game

>5 man nukie team
>reinforcements
>reinforcements op can't get buy a chest rig because nukies can't purchase them

No idea why they couldn't buy these but now they can.

## Changelog
:cl: zeroisthebiggay
tweak: Lets nukeops buy chest rigs.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
power crepe

**Comment by zeroisthebiggay** [comment]
> power crepe

i want to wear chest rigs in vr
>:^(

**Comment by kriskog** [comment]
> 
> 
> power crepe

Nukies get 6 free chest rigs in their base.

**Comment by loserXD** [comment]
there are only two

**Comment by zeroisthebiggay** [comment]
> there are only two

there's one in each of the five lockers below the uplink terminals room

**Pull request merged**
