### PR TITLE
Removes GPS's from Deep Storage and the Caravan Ambush

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Deletes the GPS's found inside the Deep Storage ruin and the Caravan Ambush ruin.

## Why It's Good For The Game

These two ruins are pure powergamer fodder due to how cheeseable they are combined with any GPS giving you direct coordinates for where to find them. All the loot is still there, but now a little bit more effort has to be put into finding either ruin.

## Changelog
:cl:
del: Removed GPS from the Deep Storage ruin and the Caravan Ambush ruin
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
Reference material.
image

**Comment by necromanceranne** [comment]
Deep Storage barely has anything that you can consider powergame material. Unless you want to call the plink rifle a powergame weapon, then cargo would be a menace every round rather than autorifles being kind of a joke.

The only items that stand out are the switchblade (combat knives from cargo match it), easy nightvision goggles, combat gloves and the ready access to a unupgraded autolathe. That's really about it. There is far, far stronger powergaming tools in other ruins like the derelict and the outpost. Deep Storage is just mostly good for forting.

**Comment by Dawson1917** [comment]
There's also the free illegal tech (already too easy to get) from the magazines inside the storage rooms, and those magazines pairing for easier killing with the like 3 different space ruins that give stetchkins.

Free guns for 0 effort is usually bad. And yes I consider guncargo bad.

**Comment by necromanceranne** [comment]
You need to find those stechkins first and frankly the removal of the signal to the caravan seems good enough.

It is far easier (and travel efficient and not wasting useful equipment) to bring one of the suspicious toolboxes from the derelict to science instead.

**Comment by FloranOtten** [comment]
Keep it in deep storage. There's absolutely nothing there that can be named to be powergamer material. Cargo can outdo it in every way. The only things there worth grabbing are the autorifle, the switchblade, the combat gloves and a stenchkin magazine for illegal tech. Of those, one is a decent gun that can be ordered from cargo, one is basically insuls except lightbulbs too, one is just a knife, and one is illegal tech. I think that for illegal tech, having to traverse space and find the GPS is pretty damn worth it.

**Comment by Dawson1917** [comment]
Guncargo is a mess lacking any semblance of balance and shouldn't be used to dictate how the rest of the game is designed.

**Comment by necromanceranne** [comment]
Okay but why is it influencing _this_ change despite any balance concerns with mass purchasable guns being accessible to cargo is something that needs to addressed in a completely separate PR. You can't apply that logic both ways. 

Do you not like specifically the WT550? Why not remove the gun instead? Maybe move the 9mm magazines over to the russian ruin (the one with the camera bug in it), which makes more sense given the APS is the only gun that takes those magazines. There are alternatives that remove the weaponry while keeping Deep Storage as a neat fortress to go hunker down in.

**Comment by Dawson1917** [comment]
I didn't make this PR to remove the unbalanced loot in these ruins. I made this PR to add an obstacle to powergamers who will rush to the chapel for its GPS and see if the ruins spawned, before grabbing a jetpack and spacesuit to go find them in <4 minutes. 
I'll look at removing or changing the loot in these ruins another time. Guncargo is also something I intend to change, or help change. I'm not sitting on my ass complaining without intention to (try to) fix what I think is unbalanced.

It's not hard to find deep storage for an autism fort even without constant GPS coordinates, and there are better options if you don't want to spend <10 minutes finding it in space.

**Comment by necromanceranne** [comment]
If you can remove a GPS you can remove a gun, mate. I really am not following your logic of balancing based on changes you want to see pushed into the game that don't exist yet, but I am also arguing you're going about this the wrong way and your logic is somewhat unsound. Keep the focus on the ruins, and don't bring in other matters like guncargo which has no relevance here. If the problem is the gun, then remove the gun. Not a means of locating it for a pre-constructed asteroid fort to use as a floor plan. Which we don't really have a good alternative for and gives people something to go look for and work on getting built up. Remember, you need to do round trips sometimes to get the thing actually worked on and constructed.

Also space flight via jetpacks makes it so much harder to just find random ruins without a bit of luck. You could be looking for this thing for more than 10 minutes. It could be the whole round if the z-levels align in an awkward way. At that point you might as well just use the whiteship and whiteship is fun, it's design shape doesn't lend itself very well to alterations for most of them. Especially on Pubby, which you can't even locate the ship itself via GPS.

**Comment by Shadowflame909** [comment]
Just wait till Economy Custom Vendor/ Pay 2 Fire pins get merged.

Then put them in vendors and have you pay to shoot them.

Space Greytiders will forever be balanced corporate greed. No matter how far away from the station they run.

**Comment by wesoda25** [comment]
This PR doesn’t improve the game in any way, but neither does it degrade from it. The space ruin isn’t some big issue, but whatever

**Comment by Dawson1917** [comment]
> 
> 
> Just wait till Economy Custom Vendor/ Pay 2 Fire pins get merged.
> 
> Then put them in vendors and have you pay to shoot them.
> 
> Space Greytiders will forever be balanced corporate greed. No matter how far away from the station they run.

You can beat and loot the entire Caravan z-level without bringing a gun, at roundstart. Ask if you want my pro gamer guide.

> 
> 
> This PR doesn’t improve the game in any way, but neither does it degrade from it. The space ruin isn’t some big issue, but whatever

Space powergaming is an issue. Not one that happens every round, but having a reliable way for any antag or nonantag to loot themselves an esword and 16 guns is pretty shit. These ruins, or at least the Caravan, would be long removed if not for the fact that space ruins are so fuckoff empty that the only "good" ruins all have at least one gun thrown in to satisfy people.

**Comment by Tlaltecuhtli** [comment]
make the pirates gib if you dont like the laser guns

**Comment by wesoda25** [comment]
But those weapons don’t outclass anything on the station. And a traitor could just as easily get those weapons using a brick of c4. More often than not I see those weapons used for weapon stores than anything else.

**Pull request merged**
