### PR TITLE
Multilayer cable hub

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

Another implementation of cable bridge
just cable with 
`cable_layer = CABLE_LAYER_1|CABLE_LAYER_2|CABLE_LAYER_3`

multilayer cable

Layers can be changed by radial menu.

radial ultilayer

adv multilayer

mlc1

hub1

hub 2

closes #49764
closes #49740

## Why It's Good For The Game

Cable layers cool

## Changelog
:cl:
add: Multilayer cable hub to connect different cable layers.
code: Renamed connect_wire() to Connect_cable()
code: Create Disconnect_cable() inverse to Connect_cable()
code: separate machinery_layer flag to determine machinery connection
del: Removed old cable bridge
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
You need to do closes #49740 instead of close#49740

**Comment by Dennok** [comment]
> You need to do closes #49740 instead of close#49740

i lose " "
 close #49740

**Comment by kriskog** [comment]
Im unsure why this was exclusive to the other one that it was seemingly closing? Consider if this is something you still want it, and fix merge conflicts.

**Comment by Dennok** [comment]
> Im unsure why this was exclusive to the other one that it was seemingly closing? Consider if this is something you still want it, and fix merge conflicts.

This already have #49740 in self
This remove cable bidge, soo after this merge #49764 no more need.

**Comment by optimumtact** [comment]
closed in favour of #49770 ?

**Comment by Dennok** [comment]
> closed in favour of #49770 ?

you mean #49773

**Comment by optimumtact** [comment]
right sorry.

**Pull request closed without merging**
