### PR TITLE
Revert "Better Slappin Animations"

### PR DESCRIPTION
**Pull request by carshalash**
The new attack animation looks REALLY bad and applies to everything, making it look like every mob/entity is just headbutting whatever they're hitting.

### CODE REVIEW

**Comment by optimumtact** [comment]
merged for only two days, knee jerk revert to a graphical change.

closing in 24 hours.

**Comment by trexter555** [comment]
i like the new animation tbh

**Comment by CoffeeDragon16** [comment]
The new animations are good and visually distinct and make it much easier to work out what's happening without reading logs faster than light.

**Comment by san7890** [comment]
spaceman go DONK

**Pull request closed without merging**
