### PR TITLE
Fixes up weather performance

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
By removing spawns.

It is a bit hacky but it runs much smoother now

Also fixes advanced darkness looking silly

### CODE REVIEW

**Comment by GunHog** [comment]
I wish we actually had something we could call 'weather'. Ion storms, rad storms, ether wind, etc.

**Comment by RemieRichards** [comment]
@GunHog so use the system?

**Comment by KorPhaeron** [comment]
Ash storms are weather! They just dont trigger yet

**Comment by GunHog** [comment]
I do not know how, RemieRichards, plus I would need...sprites and sound effects...

**Comment by duncathan** [comment]
Would you be able to accomplish this with `set waitfor`?

**Comment by KorPhaeron** [comment]
@duncathan 

Probably but I've never used that

**Comment by tkdrg** [comment]
I thought the reason this worked was because of a set waitfor=0 higher in the call chain?

**Pull request merged**
