### PR TITLE
Sorts the Greyscale Configs files and standardizes configs

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Drafted right now while I do the consistency work; the sorting itself is done though, and I figured that one would be the part nobody debates; if the standardization needs changing or isnt agreed on then the PR can just be the sorting

---

I've become a bit of a GAGSer, and have learned some ways to clean a lot of the work that ends up being done for it.

For example: a majority of the GAGS clothes we end up making always have a separate .json for the worn and object sprites, sometimes with separate .dmis for the worn and object sprites as well...
This can easily be avoided by having both .dmis with identically named icon states (similar to how non-GAGS clothes are done anyways) and making the "worn config" a **subtype** with the only difference being that it links to the worn.dmi

In case that didn't make any sense, here's an example of how it is currently for a majority of configs:
```
/datum/greyscale_config/bandana
	name = "Bandana"
	icon_file = 'icons/obj/clothing/masks.dmi'
	json_config = 'code/datums/greyscale/json_configs/bandana.json'

/datum/greyscale_config/bandana_worn
	name = "Worn Bandana"
	icon_file = 'icons/mob/clothing/mask.dmi'
	json_config = 'code/datums/greyscale/json_configs/bandana_worn.json'
```
And an example of how it could be done cleaner for this one specifically:
```
/datum/greyscale_config/bandana
	name = "Bandana"
	icon_file = 'icons/obj/clothing/masks.dmi'
	json_config = 'code/datums/greyscale/json_configs/bandana.json'

/datum/greyscale_config/bandana/worn
	name = "Worn Bandana"
	icon_file = 'icons/mob/clothing/mask.dmi'
```

A subtle change, but it really does make it all cleaner to sort through, especially when there's a lot of extremely similar items linking to the same thing over and over and over... like, every single encryption key config re-links to the .dmi individually rather than just being subtypes of the base /datum/greyscale_config/encryptionkey_basic and inheriting the .dmi link.

ADDITIONALLY, this method lets you easily compare all the subtypes to eachother or their base type, which is especially good for checking consistency between obj/worn sprites of clothes.

---

Speaking of sorting I couldn't do any of this with the files as they were (as one, big, unsorted file)...
So now it's been sorted into a greyscale_configs folder with assorted files for greyscale_clothes, greyscale_items, greyscale_objects..... you get it.

## Why It's Good For The Game
Code sorting, consistency in how it's done, easier to add more if the rest are more clean-cut and easy to follow.

## Changelog

:cl:
refactor: refactored some Greyscale Config code
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
How well does this play with mapping icons?  As more items get converted to GAGS, I see this creating a larger problem.

**Comment by OrionTheFox** [comment]
> How well does this play with mapping icons? As more items get converted to GAGS, I see this creating a larger problem.

Looking into that right now; it seems like as long as there's an icon in the file named the same as the icon_state (the one the config uses to assemble a greyscale sprite) it'll work. Screwdrivers were using it for forever; just looking at how interchangeable that really is

**Comment by OrionTheFox** [comment]
@timothymtorres Tested, zero issues as long as there's a "Default" sprite

SDMM shows the pre-made "screwdriver" sprite

StrongDMM_y96asS1vN5

Ingame shows the freshly assembled "screwdriver = screwdriver_grip + screwdriver_head" sprite
dreamseeker_Vjt23aDWtm

**Comment by Sealed101** [comment]
gags gang :+1: correct the labels if wrong

**Comment by OrionTheFox** [comment]
Ok there's
A lot more in here than 1 PR can handle. I'm gonnaaaaaaaa cut this up.

**Pull request closed without merging**
