### PR TITLE
Removes mutation/chromosomes storage limit from DNA consoles

### PR DESCRIPTION
**Pull request by Kelenius**
## About The Pull Request

DNA consoles now can store as many mutations and chromosomes as you want.

## Why It's Good For The Game

This change does not make genetics much stronger - the current limit of 6 mutations is enough to get Radioactive, Hulk, TK, X-ray, and Space Adaptation without issues, even without considering multiple consoles or disks. The storage limit only prevents the geneticists from also grabbing other neat mutations, if they don't want to bother with disks. And disks remain useful for keeping backups in case the AI or RD starts poking around. This is a QoL change.

Chromosome storage limit makes even less sense, because you can simply store an infinite amount of them in the ejected state anyway.

## Changelog
:cl:
tweak: DNA scanner can now store any amount of mutations and chromosomes.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
what about the mutation limits for disks?

also, good PR

**Comment by Kelenius** [comment]
Didn't touch disks, six mutations per disk is IMO fine.

**Comment by Fhaxaris** [comment]
based hulk anti-gamer pr

**Comment by ExcessiveUseOfCobblestone** [comment]
wonder how many mutations are in the pool for someone to put 6 as the gold standard.

@tralezab thoughts?

**Comment by Time-Green** [comment]
> wonder how many mutations are in the pool for someone to put 6 as the gold standard.
> 
> @ tralezab thoughts on pr?

I added in the limit when I reworked genetics. I wanted it as a form of resource management. Thing is that genetics ended up as such a dead end job nobody really wants to bother with it, and I get that. It's probably fine for now, at least till the next rework picks up

**Pull request merged**
