### PR TITLE
Adds triggering events from IRC as requested by HG

### PR DESCRIPTION
**Pull request by Shadowlight213**
hg|laptop: why cant i spawn meteors from IRC
hg|laptop: what kind of shitty coders do we have

@hornygranny your wish is my command

:cl: Badmins
add: Admins can now trigger random events from IRC. Be afraid. Be very afraid.
/:cl:

### CODE REVIEW

**Comment by Banana-Fist** [comment]
This is such a delightfully bad idea.

**Comment by JJRcop** [comment]
Maybe have a list events where it /msgs the invoker a list of all possible events

**Comment by Shapsy** [comment]
No

**Comment by GunHog** [comment]
This is such a delightfully **HORRIBLE** idea! Fund it! BADMIN GRIEFING FROM YOUR MOBILE DEVICE!!

**Comment by Shapsy** [comment]
The fact that you can somehow spin admins literally randomly griefing the servers without putting any effort into it as a good thing is the saddest thing I've seen all week

**Comment by PKPenguin321** [comment]
This is a meme pr

**Comment by KorPhaeron** [comment]
This is probably the most clever/awful pr of the year so far

**Comment by hornygranny** [comment]
:+1:

**Comment by MrStonedOne** [comment]
Now we just need `!centcomannounce` and `!SpawnThatNewThingThatIsGettingOverUsedDespiteKorTellingUsToStop`

**Comment by Shadowlight213** [comment]
I was uh actually going to close the pr at like 23 or so hours, since both Lzimann and Shaps (I can't actually seem to get a read on kor's opinion from his post) seem to hate it and I don't want to be deadminned.

**Pull request closed without merging**
