### PR TITLE
Improves catwalk sprites

### PR DESCRIPTION
**Pull request by ChangelingRain**
Before:

After:

### CODE REVIEW

**Comment by RemieRichards** [comment]
I prefer the more subdued yellow/orange for the catwalks.

**Comment by ChangelingRain** [comment]
Slightly darker alternative;

**Comment by RemieRichards** [comment]
That's better, but the orange just... just -works-

**Comment by Kromgar** [comment]
image

**Comment by Dorsisdwarf** [comment]
I prefer it like this, matching the hazard stripes

**Comment by uraniummeltdown** [comment]
I like the yellow-orange better, could make the warning stripes that color instead of changing the lattice

**Comment by calzilla1** [comment]
I like it

**Pull request merged**
