### PR TITLE
fixes cap suit fire immunity

### PR DESCRIPTION
**Pull request by jughu**
Silly guys helmet needs it too!

:cl: hyena
fix: fixes caps suit fire immunity
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

### CODE REVIEW

**Comment by jughu** [comment]
The HELMET didnt had the fire immunity so it just only had fire protection so it doesnt bufn into ashes

**Comment by jughu** [comment]
@korphaeron

**Comment by KorPhaeron** [comment]
Thanks

**Comment by kilkun** [comment]
thanks

**Comment by jughu** [comment]
thanks

**Comment by optimumtact** [comment]
rebalance or feature

**Comment by Kromgar** [comment]
Is oranges retarded? This is a bug. The helmet is missing the fire immunity of the main part of the armor

**Pull request merged**
