### PR TITLE
Repaths some alcoholic drinks under ethanol

### LINKED ISSUE #20604: Neurotoxin drink is not a path of alcoholics
Why. It's a drink.

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
fix: Atomic Bomb, Pan-Galactic Gargle Blaster, Neurotoxin and Hippie's Delight are now proper alcoholic drinks, and as such can disinfect, ignite, and be purged by antihol.
/:cl:

There should be no change in their behaviour when drunk; i set the boozepwr to 0 for all of them since they had custom drunkenness effects already.

Fixes #20604.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
I'm guessing the reason for this is that there's some kind of viro symptom that makes your body generate antihol, mekhi had it and got stunned by neurotoxin, then went to github to "i ded pls nerf"?

**Comment by kevinz000** [comment]
Remove the viro symptom if you want but antihol should work against it

**Comment by PKPenguin321** [comment]
Lmaoooo I knew it

**Comment by XDTM** [comment]
Why is an alcohol a better stunning chem than most of the poisons that can be made in chem

**Comment by CyberbossJHCB** [comment]
Because it's made with love and lost hope

**Comment by ExcessiveUseOfCobblestone** [comment]
alcohol is the best healing chem as well, just no one makes it.

**Comment by kevinz000** [comment]
No.. no it's not

**Pull request merged**
