### PR TITLE
Removes research scanners from cyborgs

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Security cyborg player told me he was using the scanner to search traitor items (pens, thermals, etc) with these since it showed illegal tech. Was identifying gang heads via this method.

Cyborgs have no hands they literally can not research things.

So it's an edge case of abuse vs no actual benefit I can think of. 

@GunHog do you have any objections?

### CODE REVIEW

**Comment by GunHog** [comment]
Bloody powergamers. Fine, remove it from them, then.

**Comment by Aranclanos** [comment]
how come all your prs have like 3 commits but only one line change

**Comment by Supermichael777** [comment]
because browser edditing lazyness

**Comment by Xhuis** [comment]
Logically, this *does* make sense...

**Comment by Ricotez** [comment]
since players can abuse this too, wouldn't it make more sense to have illegal tech not show up on scanners?

**Comment by GunHog** [comment]
Pointless, they have other techs that give them away as well. Only Scientists and Chemists have scanners in this case, who can only scan your items if you leave it out for them, Sec shows them to you for scanning (which a scientist can already do with the DA), or for some reason a scientist is searching someone. I am okay with removing them from borgs because Kor is right in saying they do not have much use for a scanner.

I really do not want to actually cause a negative impact on the feature because of a few powergamers. I will monitor this closely and *hope* certain jerkwads do not ruin things for the rest of us.

**Comment by Anonus** [comment]
I did this, I caused this PR.
I'm not sorry because goddamn why do secborgs need a foolproof way to ID traitor gear

**Comment by PKPenguin321** [comment]
i don't see why they need to be able to see illegal tech levels, especially considering that pretty much the only things with illegal tech are traitor items

**Pull request merged**
