### PR TITLE
Update space phonebooth's billboard [NO GBP]

### PR DESCRIPTION
**Pull request by rageguy505**
## About The Pull Request
Updated the icon on the space phonebooth billboard
## Why It's Good For The Game
It's the icon I meant to use. Must've missed it when billboards got updated while I was waiting for my Pr to merge.
image
## Changelog
:cl:

fix: Updated the billboard on the space phonebooth

/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
This is one of the sprites of all time. It has pixels in it.

**Comment by Twaticus** [comment]
hatred

**Comment by rageguy505** [comment]
huh what

**Comment by rageguy505** [comment]
> hatred

huh what

**Pull request merged**
