### PR TITLE
Adds a few more items to be able to fit in a wallet

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
So, there are a few items i feel like would be small enough to fit into a wallet, and would be handy from a gameplay perspetive
## Why It's Good For The Game
utility
## Changelog
:cl:
balance: more stuff can fit in wallet
/:cl:

### CODE REVIEW

**Comment by DAKKA-WAAAGH** [comment]
Should wallets really hold things like door remotes and stamps? I think that's pushing it a bit too far.

**Comment by newfren** [comment]
wallets were already able to hold stamps

door remotes seem fine? they're accessy

**Comment by Ryusenshu** [comment]
Im against getting Circuit boards and remotes into Wallets, it would make it way too strong
The other two things seem fine

**Comment by Jacquerel** [comment]
Maybe I'm just being picky but while I can _imagine_ having a flat stamp fit in a wallet with some difficulty, the Door Remote sprite really looks like there's no way you're getting it in there.

**Comment by etherware-novice** [comment]
> Im against getting Circuit boards and remotes into Wallets, it would make it way too strong
> 
> The other two things seem fine

wait why would circuits be op

**Comment by Ryusenshu** [comment]
> > Im against getting Circuit boards and remotes into Wallets, it would make it way too strong
> > The other two things seem fine
> 
> wait why would circuits be op

lathe board, circuit printer board and an ai upload could fit in there which is way too good in regards to inventory space

**Comment by Mothblocks** [comment]
i dont like any of these additions sorry

**Pull request closed without merging**
