### PR TITLE
Add inhand icons for security winter coat

### PR DESCRIPTION
**Pull request by Destrings2**
Add inhand icons for security winter coat

### CODE REVIEW

**Comment by lombardo2** [comment]
There are a lot of items that need inhand icons. This was listed in sprites needed so I made it first.

wintercoat

**Comment by KorPhaeron** [comment]
Thanks

**Comment by Thunder12345** [comment]
@lombardo2 Don't forget the rest of the winter coats

**Comment by lombardo2** [comment]
@Thunder12345 On it. I'll focus on inhand icons for now. We need a lot of them. Going to try and split the files first to have better organization

**Pull request merged**
