### PR TITLE
Added back moth screaming

### PR DESCRIPTION
**Pull request by Mothblocks**
The moth hivemind spoke in some cult round last night that we want our screams back.

[Changelogs]:

:cl:
add: Moths can now \*scream again, rejoice!
/:cl:

[why]: Moths are not moths without this scream.

### CODE REVIEW

**Comment by chesse20** [comment]
moths need screaming now

**Comment by MrDoomBringer** [comment]
fuck yes thank you

**Comment by TerraGS** [comment]
This is the best thing I've heard today.

**Comment by Spaceinaba** [comment]
this is retarded why on earth do you want more fucking sounds like *clap is annoying enough like seriously god no, this is even worse than some of the other moth screaming prs because your lazy ass didn't even bother to put a cooldown on the thing

**Comment by Jared-Fogle** [comment]
image

Buried deep within the confines of the spider web ridden CONTRIBUTING.md is this moth-discriminatory rule that I humbly ignore.

**Comment by GuppyLaxx** [comment]
just readd all scream sounds, but make it like hippie where you take some oxy damage every time

**Comment by cyclowns** [comment]
1. people definitely care. clapping is fucking annoying.
2. maybe this is subjective but moth screams are a hell of a lot more grating to the ears than clapping

**Comment by Dorsisdwarf** [comment]
this will be amusing for exactly 1 round

**Comment by Nabski89** [comment]
At least one person has been banned for spamming clap.

Put a cooldown on it.

**Comment by Jared-Fogle** [comment]
done

**Comment by optimumtact** [comment]
this isn't funny

**Pull request closed without merging**
