### PR TITLE
Hulks cannot be aggressive grabbed by strong grabbers anymore

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Hulks cannot be aggressive grabbed by strong grabbers anymore

## Why It's Good For The Game

> Hulks cannot be aggressive grabbed by strong grabbers anymore

Well you'd assume as a hulk that your grab protection extends to strong grabbing, but apparently that's not the case due to an oversight. The fixes to this would either be making strong grabbers attempt a grab rather than forcing one or doing a check in any grab upgrade attempt to stop that from happening. I did the latter.

## Changelog

:cl:
fix: Hulks cannot be aggressive grabbed by strong grabbers anymore
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I dont' think this is right

either the checks for grabability should happen before the entire grab chain activates, so that it applies no matter the grab level forced, or whatever is skiping the passive grab -> agressive chain needs fixing.

**Comment by carlarctg** [comment]
> I dont' think this is right
> 
> either the checks for grabability should happen before the entire grab chain activates, so that it applies no matter the grab level forced, or whatever is skiping the passive grab -> agressive chain needs fixing.
> 
> This is just going to let you passively grab people when they're supposed to be grab immune

Done!

**Comment by orthography** [comment]
CQC spiders were a mistake.

**Comment by SethLafuente** [comment]
> CQC spiders were a mistake.

A good mistake their hilarious

**Pull request merged**
