### PR TITLE
Fixes goonchat link bug

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Clicking a goonchat link will now instantly return focus to the game map. This means that the game will no longer eat your next input after you clicked a link

## Why It's Good For The Game

This makes the game feel more responsive and with no downside. Also removes an ugly function that was supposed to implement this feature.
This function was also causing some other issues, for example, it could cause you to take a screenshot with f2 although you have rebound it.

## Changelog
:cl:
fix: Clicking links in goonchat will no longer eat your next input.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
now you won't be able to move when goonchat is focused

**Comment by nemvar** [comment]
No? That function I removed straight up didn't work. You could already not move while goonchat was focused.

**Comment by optimumtact** [comment]
ok

**Comment by trollbreeder** [comment]
> ok, but i feel like tha tcode was important at one point

At one point, but not anymore.

**Review by SpaceManiac — APPROVED** [review]
- the bad if means the input proxying never worked
- nobody noticed for a long time
- refocusing the map after a click is better than trying to refocus+proxy key input

**Pull request merged**
