### PR TITLE
Replaces Function Call and Fellowship Armory with Arcane Armory

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Replaces Function Call and Fellowship Armory with Arcane Armory, a script scripture with the same cost as Function Call.
tweak: Arcane Armory permanently gives you the ability to summon and dismiss a Ratvarian spear(Summon Spear) and a set of clockwork armor(Call Cuirass). These abilities will follow you across mind transfers such as cloning, though you will only receive them if you are able to hold the spear.
balance: Ratvarian spears now last until dismissed or until thrown at someone and broken. Breaking a Ratvarian spear by throwing it at someone puts the Summon Spear action on a 30 second cooldown.
balance: Being hit with clockwork armor on will increase the duration of Vanguard slightly; 1.5 seconds with a full set of armor.
/:cl:

Effectively, every cultist has personal armor and a weapon with a bunch of synergy.
We're getting closer to the bit where I just get rid of caches entirely...

### CODE REVIEW

**Comment by drfino** [comment]
After you remove the caches, might I suggest a shift to a more demonic theme? Cults and mechanical stuff doesn't really go well together. I think it'd be better if the theme was a more traditional "runes drawn in blood" type of cult. 

I'd also like to see the "god" changed to a more spooky demon thing. I'd be happy to do some of the sprite work myself, if you're interested.

**Comment by MoreRobustThanYou** [comment]
@drfino NO, CLOCK CULT DOES NOT NEED TO BECOME A BLOOD CULT CLONE

fun fact: Clock Cult was based off of the Church of the Broken God from the SCP Foundation Wiki

**Comment by drfino** [comment]
@MoreRobustThanYou I'm actually fucking with them. I think removing clock features and reworking features to be like blood cult is a terrible direction for the mode. The general consensus for the current state of clock seems to be "remove clock."

I'd like it if all the cool shit they removed was re-added and reworked to be useful.

**Comment by MoreRobustThanYou** [comment]
Remove clock, readd slings.

**Pull request closed without merging**
