### PR TITLE
Mostly revert new graffiti sprites

### LINKED ISSUE #40638: spraycan menu extremly loading heavy and closes itself 50% of the times
it takes 40s of freezing to open the menu and it also closes itself half the times 

i blame tgui why do we use it

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
del: Most newly added graffiti have been removed due to performance issues
/:cl:
Closes #40638
I never had this issue, neither on local or on the live server, but if this is what happens on slower machines it looks pretty bad.

I don't know anything about TGUI and I'm not comfortable leaving this as is unless someone wants to step in to modify the crayon menu.

I left in a couple of small things from the original PR like fixing oriented drawings being called runes so it's not an exact revert

Brushes for free painting are still available

### CODE REVIEW

**Comment by Mickyan** [comment]
Actually you know what I'm going to keep the three brushes for freeform painting, but everything else needs to go

**Comment by Qustinnus** [comment]
TGUI takes a long ass time to handle big lists IIRC.

**Comment by JStheguy** [comment]
Can we just defenestrate TGUI already?

**Comment by Iamgoofball** [comment]
This is not an actual fix.

**Comment by AnturK** [comment]
Flatten these lists first, you're seriously overwrapping here.
dreamseeker_2018-10-03_14-29-47

**Comment by Mickyan** [comment]
@AnturK I have no idea what any of that means or what to do about it, I didn't make any of this I just added more following the code that was already there

**Comment by AnturK** [comment]
Primary slowness here is adding tons of buttons to the tree, you can alleviate it by 
a) Making this have some pages so less are displayed at once.
b) Changing these to drop down lists (combox/dropdown/whateveryoucallit). I don't think we have a styled version for these but shouldn't be too hard to add them.
c) Optimizing tgui (good luck)
Second issue is there's a lot of unnecessary wrapping in the data passed in.
Remove the wrapping lists so each category is just a single list. as in `list("letters",items=list(a,b,c))` instead of `list("letters",items=list(list(item="a"),list(item="b")))`

**Comment by Mickyan** [comment]
If I look into this (and I wont guarantee I'll figure out how to work with the UI) it'll take time I don't have at the moment, the graffiti PR was supposed to be my last project before going on a hiatus for a few weeks to focus on work

Needless to say I'm not exactly thrilled about undoing all the work I put into this but I feel responsible to at least try not leave it as it is, your choice whether to merge this or not but it's all I can do at the moment

**Comment by AnturK** [comment]
Take your time, this is not very critical. Alternative solution : Change this to radial with submenus.

**Pull request closed without merging**
