### PR TITLE
Fixes mobs without dexterity being able to remove pens from PDAs

### LINKED ISSUE #86703: Xenomorph can hold ID or pens in hand by removing them from a PDA.
### Client Version:

515.1462

### Issue Summary:

Xenomorphs can alt click or ctrl click to remove the ID and pen from the PDA and forcing it in their hand, but if these items are on the floor the warning "Your claws aren't capable of such fine manipulation!" is shown.

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

1. Drop a PDA with an ID and/or pen in it.
2. As a xenomorph, alt-click or ctrl-click the PDA and the item will be in your hands.
image

### PR DESCRIPTION
**Pull request by Metekillot**
## About The Pull Request
Bugfix for non dextrous mobs being able to use the PDA Ctrl click interaction 

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/86703 and similar 
## Changelog
:cl: Bisar
fix: fixed PDA Ctrl click not checking for dexterity 
/:cl:

### CODE REVIEW

**Comment by Metekillot** [comment]
Draft until I can do testing

**Comment by MrMelbert** [comment]
This seems like a potentially much broader problem, particularly with the `XENOMORPH_HOLDABLE` flag (IE, shouldn't the `put_in_hands` fail?)

**Comment by Metekillot** [comment]
> This seems like a potentially much broader problem, particularly with the `XENOMORPH_HOLDABLE` flag (IE, shouldn't the `put_in_hands` fail?)

Non dextrous mobs being able to pop stuff out of PDAs?

**Comment by MrMelbert** [comment]
> Non dextrous mobs being able to pop stuff out of PDAs?

Yes this is a part of the issue but logically the part of this code that puts the ID in the xenos hand should fail because xenos can't hold IDs

**Comment by Metekillot** [comment]
For some godless reason we have a call stack about ten procs deep for putting things in your hands, and someone overrode the wrong one for xenos instead of registering a signal proc on them that responds to the try_put_in_hand signal....

Anyway I'll keep this a draft while I knock this mess out

**Comment by Metekillot** [comment]
scope creeped

**Pull request closed without merging**
