### PR TITLE
Dough change

### PR DESCRIPTION
**Pull request by phil235**
Changes how dough and cakebatter are made to be a bit more realistic, they are now only done via chem reaction inside a container:
10water+15flour for dough
15flour+15eggyolk+5sugar for cake batter (alternatively for vegans 15 soymilk instead of the eggyolk).

Introduces egg yolk reagent
You can break eggs in glass reagent containers or blend them to get egg yolk.
Fixes breadslices sprites and other merge conflict bugs in food.dmi.
Change customizable snack maxvolume to 60. 
Buff nutriment amount in doughs to compensate for slower preparation method.

### CODE REVIEW

**Comment by Chocobro** [comment]
phil should we add a mixing bowl
or is that too realism

**Comment by Dorsisdwarf** [comment]
Don't forget egg whites so we can make meringues!

**Comment by phil235** [comment]
No need for a mixing bowl, we want everyone to be able to make dough if they have the ingredients, not the just the cook that has the Holy Mixing Bowl (only one on the station).

**Comment by phil235** [comment]
I changed egg breaking to only work on glass reagent (beaker, bowl, bucket,...), that way not all reagent_container will have an istype(egg) check on their attackby.

**Comment by Jalleo** [comment]
Makes sense why crack a egg and pour it into a soda can.

**Pull request merged**
