### PR TITLE
(Re?-) Adds Welcome sound to lobby after initialization completes

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

(Re?-) Adds Welcome sound to lobby after initialization completes!

I am fairly certain this was added at some point recently but it's not playing anymore. git blame isnt showing anything. maybe i shifted into an alternate dimension

## Why It's Good For The Game

Lets people know when the round's started up and they can change around their character or ready up. It's honestly crazy that lobby has no sounds to give a heads up if you're alt tabed coding or discording or something.

## Changelog

:cl:
sound: (Re?-) Adds Welcome sound to lobby after initialization completes
/:cl:

### CODE REVIEW

**Review by MrMelbert — COMMENTED** [review]
I went binary searching but I realized it's literally still there? Wat?

https://github.com/tgstation/tgstation/blob/2ca491e194b59426337db60641020680ae8a37b6/code/controllers/subsystem/ticker.dm#L286-L287

**Comment by Jacquerel** [comment]
> I went binary searching but I realized it's literally still there? Wat?
> 
> https://github.com/tgstation/tgstation/blob/2ca491e194b59426337db60641020680ae8a37b6/code/controllers/subsystem/ticker.dm#L286-L287

This is the roundstart sound, is it not?
Carlarc seems to be hallucinating some kind of sound when Initialisation ended but before the round starts (when we send the windows alert, if running locally), which as far as I can remember has never existed.

**Comment by carlarctg** [comment]
Thats the point it scares people and they come back and ready up. Its genius. Also fits with the existing notice of welcome to x

**Comment by Jacquerel** [comment]
I don't want this PR merged if it makes the same sound as the round actually starting

**Comment by carlarctg** [comment]
buw  egg h hit whii

**Pull request closed without merging**
