### PR TITLE
razors now count as being sharp items

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

see title

## Why It's Good For The Game

what could possibly go wrong?

## Changelog
:cl: ATHATH
balance: Razors are now sharp objects.
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
ATH I don't think you know what a razor looks like.
image
you can't cut yourself with one of these. Hell, I've probably tried. it'd be easier to cut a pizza using a fucking crowbar than using one of these razors. It can cut hair because hair goes into it. It's like saying "I couldn't think of an analogy this time but seriously look at the razor dude that can't cut anything except hair."

**Comment by ExcessiveUseOfCobblestone** [comment]
what will this do

**Comment by Shadowflame909** [comment]
> what will this do

barbers will now murder you

**Comment by Shadowflame909** [comment]
> what will this do

You can no longer trust the man making people bald in the halls

**Comment by Doosteroni** [comment]
Replace the sprite or add a new variant that’s a folding non-electric razor

**Comment by notfrying1pans** [comment]
> 
> 
> > what will this do
> 
> You can no longer trust the man making people bald in the halls

fuuuck i cant slip people and make them bald anymore? game sucks now bye

**Pull request closed without merging**
