### PR TITLE
Changes gondola round end sound so it's less loud

### PR DESCRIPTION
**Pull request by niceping**
closes #42060 

why: Some said "Hey, why remove gondola round end sound if you can just use Audacity to make it less earrape?"

Said and done, someone might still consider "twenty fucking gondolas on the bridge" part loud, but it should not able to perform earrape anymore. Or not with anyone at least

### CODE REVIEW

**Comment by tuypo1** [comment]
As I said on the last pr it only gets you once,  you have plenty of time to prepare for the ear rape when you hear the start of the announcement.

**Comment by kingoftheautism** [comment]
Still if 42060 gets merged gondola bridge will be removed. So its better to pitch it down rather than get it removed and complain when you had your earrape begone PR

**Comment by tuypo1** [comment]
I suppose compromise may be needed here.

**Comment by tralezab** [comment]
I don't know how good you'd have to be to audacity away the cringe but this isn't it

**Pull request closed without merging**
