### PR TITLE
Prevent mice from randomly spawning when we're running unit tests

### LINKED ISSUE #70360: Powernet test inconsistently fails
https://github.com/tgstation/tgstation/actions/runs/3200620257/jobs/5227741740

Error: /datum/powernet found with no power roundstart, connected to a cable at (166, 213, 2).

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

Issue report came through saying that we had inconsistent failures in regards to powernets being disconnected, but that's likely because mice will bite on cables- causing a powernet to become disconnected. This would create a false warning (because the map is perfectly fine otherwise) in a weird state that would only happen randomly and erratically.

So, if we compile with UNIT_TESTS flag set, let's prevent mice from introducing weird variables into our powernets unit test.

## Why It's Good For The Game

Fixes #70360.

I based this off mothblocks' comment here: https://github.com/tgstation/tgstation/issues/70360#issuecomment-1270854110, let me know if I should tackle it a different way somehow (I don't think there is a much better way).

## Changelog

Nothing that concerns players.

### CODE REVIEW

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Stop the mice spawning entirely on unit tests. We don't want *any* randomness.

**Comment by san7890** [comment]
> Stop the mice spawning entirely on unit tests. We don't want _any_ randomness.

I moved the UNIT_TESTS return to the proc that randomly spawns mice in during world initialization.

**Comment by Mothblocks** [comment]
I would wrap the inner of Initialize in the ifdef so we block random satchel spawning too

**Comment by san7890** [comment]
> I would wrap the inner of Initialize in the ifdef so we block random satchel spawning too

d8c17078c068cebf47274432be01de5a018b0f54 Is this what you meant?

**Review by Mothblocks — APPROVED** [review]

**Comment by optimumtact** [comment]
I think the correct answer might be to stop the SSnpc and AI subsystems stop executing while unit testing instead

**Comment by Mothblocks** [comment]
I think that might hide more errors than I'm comfortable with, at least without a separate isolated test for NPCs

**Comment by JohnFulpWillard** [comment]
I think it's more important to have AIs in unit testing than entirely out-of-out control mice spawning, AIs not working properly is something I hope would be immediately obvious.
Downside is we won't be able to tell if mice can properly bite a cable or not anymore

**Comment by Mothblocks** [comment]
Way way future idea: If everything uses new AI datums we can probably test complete coverage over every path in the behavior tree

**Comment by LemonInTheDark** [comment]
I'm upset.
This blocks the only source of an important hard delete in spatial grids, one that's almost impossible to debug.
It needed to have unit test stack traces inserted and caught, but that was never done, and now it's just masked totally.

The worst part is it was for a good fucking reason.
I'm malding

**Comment by LemonInTheDark** [comment]
> Stop the mice spawning entirely on unit tests. We don't want _any_ randomness.

Basically, I was using that randomness how dare you take him from me

**Pull request merged**
