### PR TITLE
Adds numerous boozepowers to the martian drinks.

### LINKED ISSUE #77566: All martian drinks have boozepwr of 20
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
All drinks, mixed or non-mixed, that were added in https://github.com/tgstation/tgstation/pull/75988, have boozepwr of 20. This is probably not intentional, because at least shochu says in its description that it has a higher alcohol content than sake (sake has boozepwr of 70) but it also doesn't make sense for all the other drinks to be the same

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

my family owns a liquor store so i made a bit of each of these and rated them all on a scale of 1-100 on how fucked up they were likely to make you for boozepower

These were all set at '20' boozepower for some reason. This fixes that.
## Why It's Good For The Game

fixes #77566
## Changelog
:cl:
fix: fixes all the martian drinks having 20 boozepower
/:cl:

### CODE REVIEW

**Comment by cnleth** [comment]
i think you missed the non-mixed drinks: rice beer, shochu, "Yūyake" (midori), coconut rum

**Comment by DeerJesus** [comment]
Oh wow I did. Yea I thought those ones had the correct boozepower as well.
I’ll add this ASAP

**Comment by san7890** [comment]
@EOBGames FYI - These look fine to you?

I'm also drafting this PR since you mentioned you wanted to add something else in an above comment, just mark "Ready for Review" when this PR is in a ready state.

**Comment by DeerJesus** [comment]
Thanks for setting it to draft! Normally I’d do it myself but I’ve been
dealing with a sick family.

The part about actually drinking the booze is a joke. I did calculate the
boozepower off the alcohol content if we accounted each unit as 1 part
though!

**Pull request merged**
