### PR TITLE
Resprites the fireaxe inhands, 3/4th-ifies the fire axe cabinet

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
What it says on the tin, resprites the fire axe inhands, worn, and in cabinet sprite to be inline with the obj sprite

https://user-images.githubusercontent.com/81479835/155901918-08cf6338-eb0b-464d-8bf3-4850a83c7858.mp4

3/4th-ified cabinet + breaking states

https://user-images.githubusercontent.com/81479835/156044884-14b5e477-6924-442f-9b18-4d65230f84ee.mp4

https://user-images.githubusercontent.com/81479835/156044923-3988b209-3ce5-4eee-a522-94f16c5a0744.mp4

## Why It's Good For The Game

less jarringly different sprites for the inhand and obj sprites.
Was asked to do this by Imaginos after I tinkered with an energy fire axe.

## Changelog

:cl:
imageadd: New fireaxe inhand, worn, and in cabinet sprites.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
the axehead looks a bit big but nice otherwise

**Review by Imaginos16 — APPROVED** [review]
Ebin

**Comment by bruhlookatthisdood** [comment]
the fire axe in cabinet looks like its just sticking out a bit.

**Comment by Ebin-Halcyon** [comment]
> the fire axe in cabinet looks like its just sticking out a bit.

o shit didn't even notice that, give me a second.

**Comment by bruhlookatthisdood** [comment]
very good

**Pull request merged**
