### PR TITLE
Maid costumes, the respritening

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Haha gotchu, april fools

haha gotchu again, it's an actual resprite and additions to the maid costume with a headband, arm covers or whatever you call them, and a neck cover.

Spin arounds of the sprites.
Content
Content2

## Why It's Good For The Game

TG is on a crusade to delete old sprites, or whatever. Someone has to do this at some point.

## Changelog

:cl:
imageadd: New and updated maid costume sprites
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
is this uh, is this a joke? I can't tell

**Comment by optimumtact** [comment]
image

**Comment by Ebin-Halcyon** [comment]
> is this uh, is this a joke? I can't tell

No, it's an unironic resprite. cause look at *this.*
image

**Review by Imaginos16 — APPROVED** [review]
Its an improvement, nothing more I can say

**Comment by trollertroll** [comment]
Old textures were based af doe

**Comment by lunarflu** [comment]
based, can you do this with xenomorphs as well?

**Comment by Ebin-Halcyon** [comment]
> based, can you do this with xenomorphs as well?

Oh yeah I completely forgot about the simplemob.

**Pull request merged**
