### PR TITLE
Requests console announcements no longer double HTML encode

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Currently, request console announcements double HTML encode. This makes them look extremely stupid when you use things like apostrophes. 

dreamseeker_2020-08-12T05-03-12

## Changelog
:cl:
fix: Request console announcements no longer double encode. This means, for example, you can use apostrophes.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
I'd make this change in `/minor_announce(` instead, and encode it only once if set to, instead of every time it's sent to a mob.

**Comment by optimumtact** [comment]
it's good practice to only do encoding at the moment of display @Rohesie 

because in the future, something might need the raw text to do a completely different type of decoding.

**Comment by Rohesie** [comment]
> 
> 
> it's good practice to only do encoding at the moment of display @Rohesie
> 
> because in the future, something might need the raw text to do a completely different type of decoding.

`/minor_announce(` is the moment of display

**Comment by optimumtact** [comment]
oh, cool, I thought it was the start of the announce chain.

**Comment by Jared-Fogle** [comment]
:+1: all around

**Pull request merged**
