### PR TITLE
Fixes /obj/effect/landmark/start failing to GC

### LINKED ISSUE #11359: /obj/effect/landmark/ doesn't qdel.
This happens if there is still a variable that points to that Object. in order to soft delete properly, the Object's destroy proc needs to clear up all references that point to it.

failed qdel log:
http://privatepaste.com/edc18b668d

### PR DESCRIPTION
**Pull request by Cyberboss**
It's like people don't understand how qdel works

Fixes #11359

### CODE REVIEW

**Comment by MrPerson** [comment]
I know for awhile they removed themselves from that list on Destroy() but that's just fucking wasteful as shit tbh. Also even when things were going great, there was always 2-4 that would fail to GC anyway.

Eventually I just gave up on fixing it and then later changes lead to all of them failing. Womp womp.

**Comment by Cyberboss** [comment]
They still remove themselves from this list in their Destroy though, which is the weirdest thing because it just doesn't work.

**Comment by Cyberboss** [comment]
NO I FOUND IT!!!!

**Comment by Cyberboss** [comment]
So here's what was happening

landmark/start/New
landmark/New -> Creates specific landmark
qdel(landmark)
landmark/start/Destroy -> Removed from start_landmarks_list (but it was never inserted)

Only AFTER landmark/New calls ..() did it add itself to the start_landmarks_list

**Pull request merged**
