### PR TITLE
Reworks Kilo Medbay

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Rearranges the Kilo medbay a little, including swapping of the front desk and sec outpost, cryo room and examination room, and turning the delivery room into a paramedic dispatch/front desk. 

Before:
image

After:
image

## Why It's Good For The Game
One of the most frustrating parts of Kilo has to be the medbay. The most heavily used room, the one with the stasis beds, is in one of the most highly trafficked areas. Both stasis beds are right next to each other. 
This moves the cryo to the main medbay room, where it is more accessible, and the stasis beds up to where cryo used to be so that MDs will stop getting jostled as often. 
The security outpost now has more visibility, paramedics have their own area, and kilo gets a second operating theatre!

## Changelog
:cl:
qol: Kilostation medbay has been renovated! The security checkpoint has been moved to face the lobby, the old sec checkpoint has been made into an operating theatre, cryogenics and the exam room have traded places, and the delivery office is now a paramedic dispatch!
/:cl:

### CODE REVIEW

**Comment by ArcaneDefence** [comment]
Still looks like it's distinctly kilo's, I'm a fan

**Comment by maxymax13** [comment]
why did you swap the main room where you have easy access to the medkits and pharmacy's fun beds with homo tubes and put the beds in the side storage room? all this will do is force you to run around in circles whenever you need something?
also? traffic? jostling? you shouldn't have to bastardize the lowpop map's lowpop centralized medbay for 70 pop sybil players doing 70 pop sybil things

**Comment by dragomagol** [comment]
> all this will do is force you to run around in circles whenever you need something?

I disagree, buying a bag from the vending machine and filling it up with tools is still viable.

> also? traffic? jostling? you shouldn't have to bastardize the lowpop map's lowpop centralized medbay for 70 pop sybil players doing 70 pop sybil things? why does kilo medbay's already compact medbay need a duplicate room?

Yes, Kilo is a lowpop map. But the reality is that it runs at all populations, and having two stasis beds next to each other, directly across from the main door is unpleasant even on lowpop when there's any kind of activity in medbay.

> pharmacy's fun beds

Not sure what you're referring to, but the beds by the pharmacy are still there. 

image

**Comment by Mothblocks** [comment]
If Inept doesn't say anything, I'm merging this when the merge conflicts are resolved.

**Comment by dragomagol** [comment]
She is ready

**Pull request merged**
