### PR TITLE
Reworks the minimap cache system and adds backup minimap files

### PR DESCRIPTION
**Pull request by Shadowlight213**
If minimap generation is disabled, the system will now first try to load the map from its cache, and failing that, try to load it from backup minimap files
Fixes bad asset file when loading from cache

Also adds a config for space ruin budgets because I was disabling it for testing. If it needs to be removed for pr atomization I can do that.

The backup minimaps don't really need to be updated, as they are fallback backups for the system being off.

:cl:
experiment: Minimaps will now try to load from a cache or backup file if minimap generation is disabled.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
runtime error: 
[00:26:52]bad resource file
[00:26:52]proc name: send asset (/proc/send_asset)
[00:26:52]  source file: asset_cache.dm,44
[00:26:52]  usr: C-H4D Mk.2 (/mob/living/silicon/ai)
[00:26:52]  src: null
[00:26:52]  usr.loc: the floor (150,32,1) (/turf/open/floor/bluegrid)
[00:26:52]  call stack:
[00:26:52]send asset(CHAD-BRO (/client), "minimap_1.png", 1)
[00:26:52]Minimap (/datum/subsystem/minimap): send(CHAD-BRO (/client))
[00:26:52]/datum/crewmonitor (/datum/crewmonitor): sendResources(CHAD-BRO (/client))
[00:26:52]/datum/crewmonitor (/datum/crewmonitor): show(C-H4D Mk.2 (/mob/living/silicon/ai), null)
[00:26:52]Crew Monitoring Console (/obj/screen/ai/crew_monitor): Click(null, "mapwindow.map", "icon-x=18;icon-y=22;left=1;scr...")

**Comment by Shadowlight213** [comment]
That should have been fixed with the second commit

**Comment by Shadowlight213** [comment]
@optimumtact that runtime is from basil. I only testmerged it on sybil.
The pr fixes that runtime.

**Comment by optimumtact** [comment]
Excuse me? that was from sybil's runtime log on the 11th?

**Comment by Shadowlight213** [comment]
Wait, really? I could have sworn it was in the bagil runtime logs for the 11th when I checked.
Anyways, that runtime should have been fixed with the second commit. It's caused by the crew monitor trying to send the minimap asset to the client, but the asset hadn't been registered/doesn't exist.
Actually I probably need to add some way to disable the map if the monitor is not on a zlevel with a minimap since it would still runtime.

**Comment by optimumtact** [comment]
Cool beans

**Comment by GunHog** [comment]
Locally testing this, I do not think coordinate plotting on the map is working.

image

**Comment by optimumtact** [comment]
did you turn your suit sensors on?

**Comment by optimumtact** [comment]
Also that's an unrelated bug by the way as this PR doesn't actually modify any of the report logic

**Comment by GunHog** [comment]
I am an idiot, problem was with me forgetting to set my sensors. It is working properly.

**Pull request merged**
