### PR TITLE
Mulebot nerf

### PR DESCRIPTION
**Pull request by coiax**
MULEBOTS OP.

Actual content in PR will follow.

Definite Tasks:
- [x] reduce mulebot damage to a 3 hit crit, rather than a 2 hit crit
- [ ] mulebots with their safeties disable make safety warning noises when moving
- [ ] mulebots slow down as they run people over, as the gunk in their wheels increases

Potential Ideas (WE WILL PICK A SUBSET OF THESE, THIS PR IS JUST TO GATHER FEEDBACK JEEZ):
- Make mulebot batteries actually matter
- Make mulebots running people over fill their wheels with blood, making them slower as they run over more people
- Lower mulebot damage to an unarmoured 3 hit crit rather than unarmoured 2 hit
- Dodge chance for mulebot run over
- Mulebots use more power/move slower on plating rather than floor tiles
- Mulebots with safeties disabled move slower, or just have loud alarms (bonus points for annoyance so people will shoot it)

Nuclear Option:
- Disable pAI control of mulebots

### CODE REVIEW

**Comment by TankNut** [comment]
Semi-nuclear option: Prevent mulebots from knocking people down and maybe tone down the damage to be less ridiculous.

**Comment by lzimann** [comment]
>Make mulebot batteries actually matter

This is really important, why even have batteries if you can stay the whole round and it will never end. It should cost more when running over bodies.

>Lower mulebot damage to an unarmoured 3 hit crit rather than unarmoured 2 hit

I believe this should happen regardless. Had full riot gear and mulebot didn't give a fuck.

**Comment by BananaSenor** [comment]
As the first one today who got the deathsquad called on him earlier:

Keep them as deadly as they are now, as it is a fun gimmick, but limit the amount of killing they can do to make them not murderboner material.

- High random chance to "spin the wheels" on a slippery corpse, making him waste a high amount of power, so that it runs out after a handful of assassinations
- Medium chance to get gibs in the gears, slowing it down
- Low chance to get entirely stuck on a body

But the largest problem was this one, I think:
- Have the hitbox of the mulebot not be blocked by a guy standing on it, somehow. Big problem was me blocking shots with my double esword

(and that no one tried the ion gun except the deathsquad)

**Comment by PKPenguin321** [comment]
:-1: Too many nerfs, pick a few

**Comment by ChangelingRain** [comment]
The attack does 30 to 90 damage per hit in increments of 6 damage it's fucking terrifying

**Comment by Fox-McCloud** [comment]
>The attack does 30 to 90 damage per hit in increments of 6 damage it's fucking terrifying

This. It's patently ridiculous. It not only does absurd damage, but weakens them, too--even if they're pumped full of anti-stun chems, the person is still 100% dead the moment they get hit.

**Comment by ChangelingRain** [comment]
The multipliers there should probably all be set to 0.5 which will result in 15-45 damage a hit, which is wayyyyyy less deadly

**Comment by LatD** [comment]
One possible nerf would be to remove the stun but keep the damage. Then whoever is on it would manually need to stun for the mulebot to kill. Along with that damage nerf of course.

**Comment by Fox-McCloud** [comment]
>One possible nerf would be to remove the stun but keep the damage. Then whoever is on it would manually need to stun for the mulebot to kill. Along with that damage nerf of course.

That would be good, IMO.

**Comment by BananaSenor** [comment]
>>One possible nerf would be to remove the stun but keep the damage. Then whoever is on it would >>manually need to stun for the mulebot to kill. Along with that damage nerf of course.
>That would be good, IMO.

Only if pAi controlled, please. Otherwise sending them through the hallways as rogue Cargo tech won't work anymore.

**Comment by Zilenan91** [comment]
OR

We nerf none of mulebots except for the damage because all the changes in the pr currently completely kill Mulebots by overnerfing them.

**Comment by lzimann** [comment]
Do you guys even read, they are some nerf ideas, not that everything WILL be implemented.

**Comment by Zilenan91** [comment]
In that case make them only able to kill people in three runs and also possibly change buckling to it to not be the snowflakiest thing in the universe so that the people on it can be hit.

**Comment by Shadowlight213** [comment]
I vote the nuclear option. Remove PAI mulebot control
It still lets mules be bloodthirsty kill machines, but they will be harder to control.

**Comment by Lumipharon** [comment]
Just remove pai control - it's super gay and honestly OP. Other nerfs are not needed.

**Comment by optimumtact** [comment]
What kind of unrobust scrub stands in front a mulebot ever?

**Comment by Zilenan91** [comment]
To be fair these things are very very fast if you hack them with the right wires

**Comment by stapler2025** [comment]
here we go removing danger from the station again

hugboxstation13

**Comment by Core0verload** [comment]
Mulebot can be stopped by any redshirt with a half of a brain and/or an ion rifle. If your secs cannot do anything, there are two words of wizdom for them:
# GIT GUD

**Comment by CPTANT** [comment]
Mulebots should be kept lethal, but its the PAI control that should be removed.

**Comment by phil235** [comment]
>Have the hitbox of the mulebot not be blocked by a guy standing on it, somehow. Big problem was me blocking shots with my double esword

Doesn't happen. Shooting at a mulebot with a guy holding a double esword always hits the mulebot.

But we could change it to behave like the janicart where a projectile bumping the cart always hits the driver instead of the cart itself.

**Comment by BananaSenor** [comment]
Just remove the ability to put a pAI in, and done. Never saw it used for anything but this.

**Comment by stapler2025** [comment]
this is literally an i ded kneejerk nerf reaction PR.

the ability to put a pAI in a mulebot has existed for quite a while now, and its not exactly common that a pAI get's put into a hacked mule.

**Comment by BananaSenor** [comment]
>the ability to put a pAI in a mulebot has existed for quite a while now, and its not exactly common that a pAI get's put into a hacked mule.

You did not play the last few days, did you?

**Comment by stapler2025** [comment]
I have, which is exactly why I said this is a "i ded pls nerf" PR.

The amount of times we've seen a pAI hacked mule vs the amount of time the ability has even been there, is extremely low.

Someone found something fun, so they're going to abuse it like it's a new feature, then it will gradually die off and people will forget.

SS13 is supposed to be about danger and paranoia, why the fuck do we keep trying to remove the danger and paranoia?

**Comment by AdamElTablawy** [comment]
i dunno about you but i don't see much paranoia in HITLER the Pai begging admins to play 'Move bitch get out the way' while ramming into the HoS over and over

**Comment by stapler2025** [comment]
You should always be wondering "is this thing going to kill me?"

Stop removing danger, goddamn.  Pretty soon we're all going to be in biosuits with NODROP boxing gloves, all the weapons will be practice guns, we'll have safety scissors, the cutlery will be removed, fireaxe's will be dull, there will be RWALLS on the outer edge of the station so you can't space people.

**Comment by AdamElTablawy** [comment]
yeah but there's a difference between 'is this thing going to kill me' and lolrandom PAI running through the halls killing people because after the fifth 'HELP MULEBOT *squish* you don't have to wonder if it's gonna kill you anymore

just remove pais in mulebots and bam, they're a lethal niche tool and a great way for AI's to kill people

**Comment by stapler2025** [comment]
nuclear option is stupidest option.

**Comment by stapler2025** [comment]
literally, remove fun because a mechanic needs fixed?  that's amazingly stupid and lazy.

how about you make it have a cooldown before it can change directions, say something about "the motors need to recalibrate before continuing"

then you don't have any more back and forth mulebot vs human action.

**Comment by Zilenan91** [comment]
That's what they planned to do. This is just a bandaid until that's done.

**Comment by stapler2025** [comment]
discussing other options in deadchat so that fun isn't removed:

Mulebot's can only be hacked by emagging them, which disables all safeties and lets them run people over.  Side effect to hacking them, it fizzles their motors and makes them 30% (debatable) slower than a stock mulebot would normally be, with the speed wires only disabling the motors entirely.  Could also make them use more battery than normal to compensate for having to "work harder" powering the motors since they've been fizzled.

**Comment by Zilenan91** [comment]
No.

Traitors should not be the only antag that can ever do sabotage.

**Comment by stapler2025** [comment]
Then enjoy your nuclear option when they flat out remove them.

**Comment by AdamElTablawy** [comment]
you literally countered a nuclear option of 'don't let pai's control them' to a nuclear option of 'limit it to only this singular gamemode on the off chance someone emags it'

**Comment by AdamElTablawy** [comment]
anyway, here's an idea

give mulebots a cooldown to running people over when pAI controlled

make mulebots flash green instead of red when pAI controlled and hacked

bam, people know 'MURDERBONER PAI' and pai's cant chain run people over with obnoxious stuns and ridiculous damage, but they can still dish out a heavy beating

**Comment by Robustin** [comment]
I think the post-murder slowdown is a good balance combined with some kind of visual/audio indicator that "TOUCHING THIS MULEBOT WILL GUARANTEE YOUR DEATH".

**Comment by AdamElTablawy** [comment]
justice helmet siren + temporary post murder slowdown

**Comment by ChangelingRain** [comment]
For coiax reminder; lines 658 and following determine damage, 646 determines stun; I'd suggest reducing both.

**Comment by AdamElTablawy** [comment]
ehhh but that guts mulebots when the only issue is pAI mulebots

**Comment by Lumipharon** [comment]
there is nothing wrong with non pai mulebot.
It has been perfectly not OP for literally years and years.

When the problem only arises under certain conditions, you nerf that, not the entire thing.

**Comment by Nanotransistor** [comment]
They were perfectly fine before the whole pAI bullshit. All these nerfs are terrible and unnecessary. Just  stop pAIs from being able to control the bots.

**Comment by stapler2025** [comment]
make it so pAI's can't control hacked mules...sometimes being put into a
mulebot is fun just to be cargos delivery bitch

**Comment by Shadowlight213** [comment]
Yeah, just remove Pais controlling hacked mules. Non controlled mules are perfectly balanced and have been for ages. It's only when the mulebot is controlled by a pai that it becomes an issue.
Make it depend on the pai rather than a client though, so you can have the occasional admin mulebot deathsquad.

**Comment by coiax** [comment]
I note that the angry shouting has died off. Does that mean people no longer desire a nerf, or have they just accepted the status quo as EDIBLE MEAT FOR THE MULE OVERLORDS

**Comment by lzimann** [comment]
i still want a nerf

**Comment by stapler2025** [comment]
i told you all what would happen.

it was "new"

it was "fun"


now its worn off and nobody cares anymore

**Comment by Mercenaryblue** [comment]
Idea: Have the pAI temporarily lose control if he hits a wall, or a human being when on cooldown
(Cooldown starts when the first guy gets run over.)
Kinda like the skateboards.

**Comment by coiax** [comment]
The angry mob has dispersed. Given enough people have complained that "nerfs aren't just for christmas, they're for life" I'm closing this.

**Pull request closed without merging**
