### PR TITLE
cardboard no longer can damage you

### PR DESCRIPTION
**Pull request by praisenarsie**
[why]: >cardboard >hurting you

### CODE REVIEW

**Comment by epochayur** [comment]
clearly someone has never gotten a cardboard cut

**Comment by JJRcop** [comment]
It should never damage you with force=0

**Comment by alexkar598** [comment]
Why are you wasting your pr points for that?

**Comment by pantherpusher** [comment]
Man cardboard cuts are the worst

**Comment by Spaceinaba** [comment]
how will I kill people with my life size cutout of danny devito now

**Pull request merged**
