### PR TITLE
Adds Turn Based Combat

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

https://github.com/tgstation/tgstation/assets/51863163/237e1bd7-cfe4-4ed4-9147-c76043d5b113

## Why It's Good For The Game

This will make combat more fair and thoughtful, and also less reliant on skill, thus encouraging roleplay

## Changelog

:cl: Melbert
add: Turn Based Combat
/:cl:

### CODE REVIEW

**Comment by Blacklist897** [comment]
no please no the player base cant handle it

**Comment by moocowswag** [comment]
does this make gloves of the north star and standard holoparasite cry.

**Comment by MrMelbert** [comment]
> does this make gloves of the north star and standard holoparasite cry.

holoparasites are good for action economy, it's an extra ally.

**Comment by moocowswag** [comment]
> holoparasites are good for action economy, it's an extra ally.

standard and ranged are reliant on their (extreme) attack speed, explosive probably has the most impact per hit (literally rng dice roll to win) and im assuming lightening and the chaos/atmos one is going to be a meme since lightening will continue to do damage faster than turns are taken.

**Comment by the-orange-cow** [comment]
You've just activated my trap card!

**Comment by Vect0r2** [comment]
> > holoparasites are good for action economy, it's an extra ally.
> 
> standard and ranged are reliant on their (extreme) attack speed, explosive probably has the most impact per hit (literally rng dice roll to win) and im assuming lightening and the chaos/atmos one is going to be a meme since lightening will continue to do damage faster than turns are taken.
> 
> Probably the bigger deal though is how this impacts ranged weapons, im just hoping someone starts their turn before the projectile hits them so they can dodge but also gotta worry about ranged weapons having much higher attack speed that they cant utilize.
> 
> Also are participants in combat selected based on radius or attacks made in combat? Judging by the video its radius so im assuming you can atleast escape from combat.
> 
> If a single valid hunter gets a hit on an antag they can just take their turn very slowly to prevent that antag from running away while everyone else runs across the station to get them.
> 
> This has neat flavor to it but it has potential to be the same level of "Don't actually invest yourself into the game during april fools" as captain using emergency meeting every round to teleport valids/murderbone as non antag.
> 
> Im mainly just talking about this here so anyone that does become involved in this mechanic can more easily connect the dots on how it impacts the game and know that standard holoparasite is once again the worst one.

It's april fools turn based combat I don't think the meta is on anybodies mind.

**Comment by moocowswag** [comment]
> It's april fools turn based combat I don't think the meta is on anybodies mind.

emergency meeting kind of proved otherwise.

**Comment by moocowswag** [comment]
are do_afters allowed to continue when its not your turn or is it paused....

or are they stopped entirely by the time freeze and you cant ever do a do_after in combat.

**Comment by DrDiasyl** [comment]
April fools are to be silly, enjoy it while you can as you won't ever see this kind of shit on normal days.

**Comment by K4rlox** [comment]
combat turns stack
cannot pick up items
combat counts towards passive mobs and catonics
combat counts towards GHOSTS (what)
shapeshifting during combat makes you bug out permenetly
ranged weapons dont work

**Comment by SomeoneYouProbablyKnow** [comment]
> plus the turn count is random, someone can get 11 turns when someone gets one, causing them to die

🙏 skill issue

**Comment by MrMelbert** [comment]
> the turn count is random, someone can get 11 turns when someone gets one, causing them to die

You can tell this guy dumped dex and has bad initiative

**Comment by Draggeru** [comment]
Bad PR, doesn't allow bonus actions or take AC into account

**Comment by ju45he** [comment]
what if this was a wizard ability or something

**Pull request closed without merging**
