### PR TITLE
Fixes SM getting energy when hit in space.

### LINKED ISSUE #28638: Supermatter in vacuum blows up super easily
Supermatter behaviour in vacuum is weird. When surrounded by all sides you can fire emitters all day without anything appearing to happen. I then placed one floor next to the supermatter and it instantly delaminated at 1000%

[img]http://i.imgur.com/0wGZ9y9.png[/img]

Supermatter should fail in vacuum, but this doesn't seem the intended reaction.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #28638

Not sure if this should also stop when there's no gas mix ?

### CODE REVIEW

**Comment by Cyberboss** [comment]
The only time something shouldn't have a gasmix is if its in a non-open turf so probably not

**Review by Cyberboss — DISMISSED** [review]

**Comment by ohnopigeons** [comment]
The SM wasn't in a spaceturf

**Comment by nicbn** [comment]
But the code checks for spaceturf. The correct to do is to stop it from working when there is no gas or at super-low pressure. Or even better, make it heat up faster when in low pressure and stop it from cooling down when there is no gas, what makes a bunch more sense.

**Comment by Tokiko1** [comment]
Check the issue too, I posted what goes horribly wrong in the code.

**Pull request merged**
