### PR TITLE
Replaces Taunting Tirade with a much more useful scripture

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Removed Taunting Tirade.
rscadd: Added Component Syphon, which transmutes all nearby nonservant corpses into components, which are automatically stored in the invoker's slab. The amount of components produced depends on the number of components in the slab and global cache.
wip: Component Syphon has the same cost as Taunting Tirade did.
/:cl:

It will only ever produce one component from mindless mobs(even if you do a bunch at once), which is probably not worth the capacitor cost.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
So this is an AOE gib?

**Comment by kevinz000** [comment]
Encourages killing and not converting tbf

**Comment by ChangelingRain** [comment]
Yes, it aoe gibs dead people, effectively. I might make it more kind and leave a brain but I'm not sure that'd matter. I could maybe make it a global list instead of gibbing and have it, husk or something but global list reeeeee

**Comment by scoopscoop** [comment]
I don't like this too much, taunting tirade is very fun to use, and the confusion is useful in preventing people from chasing you.

**Comment by Iamgoofball** [comment]
Yeah keep taunting just add both

**Comment by AdamElTablawy** [comment]
keep taunting tirade, it's useful situationally

also no, don't add reasons to kill and not convert as clock cult reee

**Comment by ShadowDeath6** [comment]
Make it so you can soulvessel brains if you couldn't already and have it make mobs drop their brains and it'd be less counterproductive

**Comment by Cheridan** [comment]
>also no, don't add reasons to kill and not convert as clock cult reee

Yeah, that was my first thought. This isn't clock-culty at all, this is full Narsie. 
Actually it's worse than Narsie, since when you sacrifice people as bloodcult they get soulstoned and get to be a construct.

**Pull request closed without merging**
