### PR TITLE
Fixes a grammar mistake on a circuit.

### PR DESCRIPTION
**Pull request by praisenarsie**

### CODE REVIEW

**Comment by Buggy123** [comment]
PRIORITY:CRITICAL

**Comment by MrDoomBringer** [comment]
>grammer PRs before new years

**Comment by praisenarsie** [comment]
>giving a shit about gbp

**Review by ShizCalev — APPROVED** [review]

**Review by ShizCalev — DISMISSED** [review]
ignore

**Comment by praisenarsie** [comment]
This will get closed in above referenced PR.

**Pull request closed without merging**
