### PR TITLE
Induce panic now has a chance to induce panic in real life

### PR DESCRIPTION
**Pull request by Kierany9**
## About The Pull Request

Induce panic now has a chance to induce panic in real life. The hivemind's psionic powers can extend beyond the screen and into *you*!

## Why It's Good For The Game

immersion

### CODE REVIEW

**Comment by adamkad1** [comment]
what kind of epilepsy inducing shenanigans you added?

**Comment by Barhandar** [comment]
He made it have a chance to play a bwoink.

**Comment by optimumtact** [comment]
This is reserved for admin stuff and the banhammer

**Comment by adamkad1** [comment]
oranges the fun hater strikes again

**Comment by PKPenguin321** [comment]
Thought for a second that this would just be a straight up screamer

**Comment by Kierany9** [comment]
bwoink > screamers

screamers are ass because there's nothing spooky about a loud noise if you don't add some low-tier jumpscare picture so the sound has some context. with bwoink, you don't even need to see anything because this'll instantly appear in your mind's eye:
### --Administrator Private Message--
**hey, why'd you do that?**

**Comment by knacker48** [comment]
We already have the banhammer in space ruins. This seems fine to me, provided it happens infrequently enough to so people don't miss real admin messages

**Pull request closed without merging**
