### PR TITLE
Suppress OD warnings for invalid pragmas

### LINKED ISSUE #82696: OpenDream Linter Consistently Warns On Missing Pragmas
## Issue Summary

This is showing up on every PR/CI Run.

image

I spoke about it in #maintainerbus and there are at least three options (please do add more alternate options if you have any good ideas).

1. Add a pragma or CLI-flag that makes it not warn on missing pragmas because it has the potential to lint on pragmas that exist outside of its namespace. This is the better option, but this would be up to the maintainers on OpenDream. MSO suggested having all OpenDream specific pragmas be prepended with `OD` (making it `OD-SoftReservedKeyword` as an example), but again, this is up to their maintainers.
2. Update our `od_annotator.py` to ignore `OD1002` codes (which are specifically designed to lint against unrecognized pragmas). This is only an option if number 1 doesn't work for any reason as it could cause issues down the line, but I'm mentioning it now because it is certainly an option.
3. Remove the TooManyArguments pragma. probably don't need it?

I'm a bit busy right now but I wanted to make sure I got it written down somewhere more public and eternal before I nag opendream maintainers about it (someone else can take up this mantle if they are so inclined). let's just get an issue regarding this on our tracker and we can just talk about it in this spot. i am operating on snail time sadly

### PR DESCRIPTION
**Pull request by ike709**
## About The Pull Request

Closes #82696 

This could have been fixed months ago but nobody mentioned it to me (and nobody reads our documentation or our announcements channel, apparently).

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
This was already fixed by removing the deprecated pragma

**Comment by ZephyrTFA** [comment]
Also I don't want to suppress these, when the pragma gets removed we should update ours to match

**Comment by san7890** [comment]
this will happen again though? it's not a matter of if but when, if you read the issue report. 516 will have `#pragma` of it's own

**Comment by san7890** [comment]
regardless removing the warning isn't a great idea and i agree with that but we will have issues with this later

**Comment by ike709** [comment]
@ZephyrTFA The point of this is to prevent OD from emitting `InvalidWarningCode` for BYOND's own pragmas, at least until OD refactors its pragmas to make it a non-issue.

**Comment by ike709** [comment]
Also speedcloses are inherently cringe.

**Comment by MrMelbert** [comment]
^

**Comment by ike709** [comment]
Nope, you don't get to quietly reopen this a month later after speedclosing it. I tried to fix this problem, I explained why it was a problem, and you left it closed. If you want this to be fixed you can either make your own PR or wait until OpenDream refactors pragmas.

**Pull request closed without merging**
