### PR TITLE
Fixes some ghost menu pirate shuttle spawns not working when clicked

### LINKED ISSUE #79480: Grey tide pirate pods
## Round ID:

https://github.com/fulpstation/fulpstation

## Reproduction:

 Grey tide pirate event happens and the ship spawns. There are pirate pods ghosts can see in the spawners menu, but they can't use the spawn or jump buttons for this role. The only way to spawn as a greytider pirate now is to jump to the pirate ship, locate a pod and click on it.

### PR DESCRIPTION
**Pull request by Hoolny**
## About The Pull Request
Space IRS
Interdyne
Tider
Pirates menus werent working because \improper wasent set up to work good in code
as shown here all I did was remove it and they work now
Uf53fdO
Closes #79480 
## Why It's Good For The Game
It's good for menus to work as intended and for bugs to be fixed I would say so myself
## Changelog
:cl:
fix: fixes some pirate ghost spawn menu not working
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Please be more specific in what you mean by "they weren't working", I cannot tell what bug this is supposed to be fixing.

**Comment by SethLafuente** [comment]
> Please be more specific in what you mean by "they weren't working", I cannot tell what bug this is supposed to be fixing.

I did say it closes the bug #79480

But to clearify it made it so when you pressed the following:
IRS
Interdyne
Assitant
Pirate types it did absolutely nothing it neither took you to their pods as shown here or let you play as them

**Comment by Jacquerel** [comment]
I think we could do with digging deeper here, _why_ does this fix the bug?
It seems like we'd prefer a fix which means that you do not need to name the ghost spawner in a specific way in order for it to work.

**Comment by SethLafuente** [comment]
> I think we could do with digging deeper here, _why_ does this fix the bug? It seems like we'd prefer a fix which means that you do not need to name the ghost spawner in a specific way in order for it to work.

I noticed when one of the ghost spawners has /improper before the name of it, it did not function I made the Interdyne and Assitant pirates and I don't recall giving them the /improper thing but they had it and when I removed it, it now works

I am not entirely sure why it fixes it or what \improper does

**Comment by Jacquerel** [comment]
now would be a good time to find out, because I don't want to merge this until you can explain to me why it fixes the bug

**Comment by SethLafuente** [comment]
> now would be a good time to find out, because I don't want to merge this until you can explain to me why it fixes the bug

image
For what I found by searching for what it might mean they are prefixes for names

Maybe is because when it has the prefix

image

I am unsure as to how I could have ever come to know what it means

**Comment by Jacquerel** [comment]
You probably want to look at what the ghost role button is doing and not what `improper` does, what we need ot know is why having `/improper` in the name stops it from working.

**Comment by Jacquerel** [comment]
did the most recent commit not actually fix the issue? why did you mark your own PR as "do not merge" and then never undraft it.,..

**Comment by SethLafuente** [comment]
> did the most recent commit not actually fix the issue? why did you mark your own PR as "do not merge" and then never undraft it.,..

I realized that what I did kinda fixed it but not the proper way and I'm still trying to figure out how to fix it

**Comment by Jacquerel** [comment]
> > did the most recent commit not actually fix the issue? why did you mark your own PR as "do not merge" and then never undraft it.,..
> 
> I realized that what I did kinda fixed it but not the proper way and I'm still trying to figure out how to fix it

That's true for your first commit but the followup one (marked "perhapos") seemed fine?

**Pull request closed without merging**
