### PR TITLE
Fixes dumping money bags into IDs

### PR DESCRIPTION
**Pull request by BadSS13Player**
Apparently, this just changes the code around a bit.

### CODE REVIEW

**Comment by kriskog** [comment]
This has been working in the past, what is wrong with it?

**Comment by BadSS13Player** [comment]
It doesn't work in-game as it should. Code-wise, the for loop var has a type of /obj/item/physical_money which isn't a base class of the things you can put in the moneybag. That path doesn't even seem to exist in the codebase.

**Comment by kriskog** [comment]
Thats just a variable name, its of the type obj/item.
They work on current master, but you need to put the card on the ground. It was a conscious decision by the guy who added it, since you are upending a sack of money on it.

**Comment by BadSS13Player** [comment]
I'm stupid

**Pull request closed without merging**
