### PR TITLE
makes tram console invincible

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
tram console is now invincible due to maintainer request

## Why It's Good For The Game
tram is cool stop griefing it

## Changelog
:cl:
balance: you can no longer destroy the tram control console. you cant grief as well as the tram can so stop breaking it out of jealousy
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
I requested it. The tram is, obviously, the staple of TramStation, so it's lame as hell when consistently, round after round, engineers just immediately take it apart round start.

This isn't unprecedented, the tram tiles itself are indestructible to my knowledge. Before the console, you had to click on the tiles of the tram to move it forward. The *indestructible* tiles. Moving it to a computer for UX purposes introduced this regression.

**Comment by Kylerace** [comment]
yeah what he said

**Comment by Fikou** [comment]
can you make it so it can still fall apart from explosions?

**Comment by Mothblocks** [comment]
You already can't blow up the tram itself AFAIK, that should all be its own PR IMO.

**Comment by MMMiracles** [comment]
I was hesitant on doing this initially since it let you do some funny memes with remote tram controls but if people are being sour sports and just dissembling the console then I guess it needs done

**Comment by Mothblocks** [comment]
@MMMiracles  If you make the computer a machine instead, then you could attach wires that could be pulsed to go to each part 😉

**Comment by TemporalOroboros** [comment]
@Mothblocks @MMMiracles Technically it wouldn't need to be a machine since wires are on `/atom`

**Comment by Mothblocks** [comment]
Moreso just that screwdrivering a computer not deconstructing it but instead opening something else is a bit weird, but oh well,. doesn't really matter.

**Pull request merged**
