### PR TITLE
make security have access to kinetic rifles

### PR DESCRIPTION
**Pull request by RangerIT**
## About The Pull Request

<This is a simple pull request, I've noticed that many SS13 servers have kinetic weaponry in their armory, no, i'm not talking about the riot shotguns, i would like to add some sci-fi kinetic rifles (with rubber and normal rounds) accessible in the armory. the sprites will be based on the MK18, but adding some red neon lights on the stock, and other sci-fi things, like an ammo counter. The rubber rounds will deal 10 brute damage, while the normal rounds will deal 25 damage, and they will sharpnel in the "victim"'s body. the rate of fire will be 1 rps. The rubber rounds will also deal 50 stamina damage, while the normal rounds will not deal any stamina damage  >

## Why It's Good For The Game

<They will add more action to game modes like nukeops, (the security autorifle sucks against che c-20 of the nuke ops, let's be clear.) but also, in game modes like traitor mode, they will make the round more suspicious, because when you hear a shoot you will not know if its the traitor or the officer that shoot. And I personally think security has too little weaponry, and a new gun would fit very well>

:cl:
add: Added more things

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
image
yeah uhhh what

**Comment by Dorsisdwarf** [comment]
You have definitely PR'd the wrong branch, possibly to the wrong codebase

**Comment by Dorsisdwarf** [comment]
I have been informed that this is a less amusing mistake than I initially believed

**Comment by ExcessiveUseOfCobblestone** [comment]
Desktop users

**Comment by drIcepop** [comment]
Speed merge

**Comment by Bawhoppen** [comment]
Oxford is that you?

**Pull request closed without merging**
