### PR TITLE
Gang Update 5

### LINKED ISSUE #9134: Cheesey spraycan tactics in Gang
d10_icon

Mildly Cheesy: People can tag the inside of rooms by spraying on the wall from the outside, meaning they never have to actually enter most territory to claim it, as most can be tagged from either the halls or maint.

Dangerously Cheesy: People who know the dark secret of APC areas can tag the ground under an APC to claim a territory without even giving a hint to the people inside they've been tagged.

### PR DESCRIPTION
**Pull request by Ikarrus**
#### Major Changes
- Capture goal reduced to 60%
- You must be in the territory physically to tag it now. So no more tagging everything from maint.
- Influence income changed to provide weaker gangs a bigger boost, while slowing down stronger gangs to promote opportunity for comebacks
- Gangs only earn influence on territories they have held on to since the previous Status Report (the income calculation every 5 minutes). This places more significance on defending your existing territory.
- Crayons and spraycans can now draw poseur tags (Fake gang tags) as graffiti.
#### Minor Changes
- Removed solars and shuttles, and the toxins test chamber from valid territory list
- Victory conditions are only checked during Status Reports.
- Bosses no longer receive territory updates real-time. They now get them all as a list of new and lost territories in the Status Update.
- You cannot tag tiles with APCs. No cheating, you maint crawlers.
- Goal is now a scalar var so it can be modified in-game for debugging/playtesting purposes
- Simplified some list checks for gang
- Fixed bug that allowed infinite spraycan use.
- Trying to tag an invalid area will just error out and return, instead of the ganger spraying regular grafiti and confusing them

Fixes #9134

### CODE REVIEW

**Comment by Jordie0608** [comment]
Chaaaangelog

**Comment by Ikarrus** [comment]
@Jordie0608 Thanks for the reminder

**Comment by WJohn** [comment]
Fixes #9134 then.

**Comment by Supermichael777** [comment]
That math is so much cleaner with strange station layouts. also you can actually change that for badminery without calculus.

**Comment by Iamgoofball** [comment]
Question, why was toxins testing excluded? Everyone forgets to toss the teleporter beacon.

**Comment by Ikarrus** [comment]
The idea is that you're supposed to be capturing the station. I don't want to include areas that you need a space suit to reach.

**Comment by Iamgoofball** [comment]
Alrighty then.

**Comment by AndroidSFV** [comment]
how long until people deconstruct APCs just to tag those locations?

**Pull request merged**
