### PR TITLE
fixes choking.dm runtime due to new viruses

### PR DESCRIPTION
**Pull request by LanCartwright**
Forgot about the change to stage speed causing possible SQRT(0

### CODE REVIEW

**Comment by phil235** [comment]
if only we were using a define...

**Comment by LanCartwright** [comment]
@phil235 I'd have to calculate defines for each virus which there isn't a proc for it (yet) to calculate the absolute minimum possible.

**Comment by optimumtact** [comment]
:clap:

**Comment by phil235** [comment]
Also, are you sure it can be 0 ? Can a symptom's stage speed be negative? Or am I missing something?

**Comment by LanCartwright** [comment]
Yes. I didn't realise this earlier on and theoretically in normal gameplay five symptoms with -4 stage speeds wouldn't be reasonable. -20 is (currently) the lowest stage speed.

**Comment by optimumtact** [comment]
LGTM now, will merge end of today

**Comment by Cheridan** [comment]
@oranges 

broken promises

**Pull request merged**
