### PR TITLE
Security, medical, and antag huds can now coexist

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Moved the security hud's icons down slightly to allow it to coexist with medical and antag huds.
/:cl:
slightly outdated
This screenshot is slightly outdated, as the chemical implant got moved to the left so that it wouldn't overlap with antag icons, but you get the idea.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Pics

**Comment by xxalpha** [comment]
Yea pics are important.

**Comment by Shadowlight213** [comment]
Neat. I already sorta used this in a hacky way by setting ghost medical hud first then activating antag hud which gave sec and antag. The medical icon would get blocked, but it isn't super important as it only really mattered for diseases.

**Comment by ChangelingRain** [comment]
I should note that the code currently doesn't support easily using all huds; at best, as an admin, you can have sec, med, and antag huds but not diagnostic.

**Comment by Dorsisdwarf** [comment]
ABsolute MaDMaN

**Pull request merged**
