### PR TITLE
Bumps `dependencies.sh` to 515.1633 Stable

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Two reasons for this.

1. It's the stable branch, so let's move it up. This PR will detect any issues that we might have with the latest 515.1633 as far as the codebase is concerned (the servers have been running 1633 for at least a week now).
2. ~~I'm fucking sick of seeing the Lua Scripting Notice in CI even though it was fixed a few days ago in #82074 (5624d9452413641b4c6d4b886cb116481186b8ac)
`image`~~

### CODE REVIEW

**Comment by san7890** [comment]
It's still failing???

```dm
## WARNING: Error initializing SSlua: FAILED (Couldn't find call_proc_by_id)
```

**Comment by san7890** [comment]
@Y0SH1M4S73R any clues why auxlua is still failing to intialize in CI?

**Comment by Y0SH1M4S73R** [comment]
> @Y0SH1M4S73R any clues why auxlua is still failing to intialize in CI?

According to watermelon, it's because the auxtools binary from the debug server is interfering with auxlua.
Not sure if that applies to CI, but if it starts an auxtools binary, then it would cause the init failure.

**Comment by san7890** [comment]
also we're getting this error in our CI runs, is this normal?

```txt
code/world.dm:22:warning (loop_checks): 0: Disabling loop_checks is dangerous and should only be used as a temporary debugging measure. Without these checks an infinite loop in your code can cause the world to hang. Proceed with caution.
```

**Comment by san7890** [comment]
Oh well, at least it won't be an issue when the DMAPI replacement comes along. Scratch out point two then.

**Pull request merged**
