### PR TITLE
[DNM][AWAITING POLICY]Integrity restorer can now remove a law zero.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request
@Timberpoes worked with me on this.
You can now remove the law zero from a carded AI, **but NOT combat upgrades / antagonist objectives**. You can then tango with an AI that is properly ASIMOV shackled but is /still/ bad. 

# I can't stress enough that this simply removes the law zero, the AI is still an antagonist with combat upgrades.

## Why It's Good For The Game

Non lethal way to subdue a malfunctioning AI. Opens up RP and gameplay opportunities. Round removing bad.

## Changelog
:cl: Timberpoes & Kathy Ryals
add: You can now remove a law zero from an AI by carding it, then using the AI restorer program on a modular computer / laptop.
/:cl:

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
You shouldn't be able remove peoples traitor status

**Comment by KathyRyals** [comment]
yes, that's why it doesn't.

**Comment by Fikou** [comment]
> Yes, that's why it doesn't. 

whats the difference between a non antag and an antag that has to listen to orders of everyone and cannot do shit
also adds even more confusion to silicon policy

**Comment by KathyRyals** [comment]
Same thing as traitors / wizard that gets borged. You have to follow your laws but can still do objectives if they are respecting your laws. Same policy as a wizard getting borged for example.

https://tgstation13.org/phpBB/viewtopic.php?f=33&t=1004#p20335

**Comment by Tharcoonvagh** [comment]
It technically does though! The difference between this and borging human antags is that (imo) putting a brain back in a body is easier than changing laws without anyone noticing.

**Comment by KathyRyals** [comment]
I think that's a cool feature ! Another antag could purposefuly work with the AI to free it and accomplish objectives together etc...
Also adding this option to remove law zero is 100% optional and if you don't like it, feel free to not use it and kill the AI. I just think some rounds could benefit from having a choice.

**Comment by Ryll-Ryll** [comment]
I feel like it's better that the AI has a solid reason to dig in its heels and attempt desperate last stands, rather than just take the easy way out and roll over to be pacified so they can stay alive if they're not sure if they can win. Like, yeah round removal sucks when it happens to you, but a malfunctioning AI hardwired to massacre the crew deciding to peacefully surrender and allow itself to be dominated again seems really jarring thematically.

**Comment by KathyRyals** [comment]
I feel like that's a player issue more than an issue with my PR ? An AI that tries his hardest to survive and gets killed will still have an opportunity to play IF THEY CHOOSE TO REMOVE THE LAW 0 and restore it ! And it can still be subverted, purged, etc..

**Comment by Dorsisdwarf** [comment]
How does this interact with the fact that the AI law 0 means nothing whatsoever beyond being a meta tell and traitor ais just do whatever they please as per normal antags ignoring objectives (As has been ruled every single time a wiseass tries to upload "Your objectives are to stop flooding plasma then kill yourself")

**Comment by zxaber** [comment]
According to the rules, malf AI isn't required to listen to the laws. Law zero exists for the benefit of players that check the AI to see the laws, and cyborgs.

So this doesn't prevent the AI from mass murder but it makes things more confusing for everyone else.

**Comment by Korusho** [comment]
I am conflicted by this. I see the positive and the negative, coming from the viewpoint of an AI player. 

However, giving the alternative to Captain's/RD's wiping you from existence, removal of the law may be the superior option.

Supported - Blaine Systems AI

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
Policy changes required prior to this PR, specifically the implication of what law 0 actually does.

**Comment by Fikou** [comment]
can u give the ai an option to dnr if they are dead or suicide if they are alive when their law 0 is removed so you dont have to be crew's sissy antag maid

**Comment by KathyRyals** [comment]
I have contacted the headmin team, will close this PR and open another one when I've been informed of a decision.

**Comment by Fikou** [comment]
i use arch linux btw

**Comment by ExcessiveUseOfCobblestone** [comment]
bruh u didnt need to close this pr hence why i added DNM (so I could take it off later)

REEEEEEEEEEEEEEEEEEEEEEE

**Comment by KathyRyals** [comment]
@ExcessiveUseOfCobblestone

**Comment by optimumtact** [comment]
there's no point in this being open until the policy is changed.

**Comment by ExcessiveUseOfCobblestone** [comment]
REEEEEEEEEEEEEEEEEEEEEEE

**Pull request closed without merging**
