### PR TITLE
Resprites revenant

### PR DESCRIPTION
**Pull request by MelokG000**
## About The Pull Request

Changes revenant sprite to Paradise station one
image

## Why It's Good For The Game

Old revenant looks shitty
## Changelog
:cl:
image: changed revenant sprite
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Not to be a soul poster but the old sprite looks like a spooky revenant while the new one is like, an NPC monk you might find in an RPG
The two eyes and relaxed pose make it look significantly friendlier and less ominous

**Comment by Livrah** [comment]
Omg Noita. 
Feels a same as about Space Dragon resprite. Even if new sprite is better, would be good to see the old sprite improvement instead.

**Comment by Xkallubar** [comment]
This sprite is worse imo. We have way too many cutesy sprites. If the sprite had to change I'd rather it be a scarier one.

**Comment by EricZilla** [comment]
While that sprite is objectively better, it doesn't suit the rev at all. If we had some kind of nonhostile ghost this guy would be lit for that. (Also credit the artist in ports)

**Comment by moocowswag** [comment]
the real question is if its harder or easier to click on

**Review by Wallemations — CHANGES_REQUESTED** [review]
This thing doesn't look like a scary ghost, it looks like a random dude in a robe you'd see in a party city

Old rev wasn't perfect but it was clearly a malevolent spirit, y'know? Even if this is a ghost it doesn't look evil.

If you could find some sort of balance between the palette of this one and the more spooky design of the old one then sure

Also I'm not sure if it's an icon diff bug or not but why are your idle and draining sprites flashing things when they otherwise shouldn't be?

**Comment by MercuryArrow** [comment]
I'm torn personally because on one hand, yeah, the spooky vibes on this are a little wanting. On the other hand, I've never really liked the "revenant as a weird upside down purple triangle blob with thick hands" look either.

I think a revenant visual redesign could be good but this isn't really it.

**Pull request closed without merging**
