### PR TITLE
mobile defibrillator mount

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

image
image

5 iron and 1 sheet of silver and 15 cable to craft

its a defib mount but mobile, thats basically it

## Why It's Good For The Game

good for maps where there are no good spots to place wall defib mounts
or if you cant or dont want to take off your backpack (maybe using a modsuit?) and theres no defib mount nearby

## Changelog
:cl:
add: mobile defibrillator mount
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
to be honest i feel the sprite would make more sense if it was a cart, like IRL. otherwise it just looks like a pole with a weird 2D panel on the top that you see on walls

**Comment by mc-oofert** [comment]
> to be honest i feel the sprite would make more sense if it was a cart, like IRL. otherwise it just looks like a pole with a weird 2D panel on the top that you see on walls
> 
> Also, Karen

i slapped 2 sprites together my ass does not know how to sprite

**Comment by Admiral-Gigaton** [comment]
> > to be honest i feel the sprite would make more sense if it was a cart, like IRL. otherwise it just looks like a pole with a weird 2D panel on the top that you see on walls
> > Also, Karen
> 
> i slapped 2 sprites together my ass does not know how to sprite

just noticed that you, mc-oofert, made it. guy take like one of the kitchen carts sprites (the food cart n shit) and recolor it, with maybe a few extra little bits, done

**Review by Wallemations — CHANGES_REQUESTED** [review]
Sprite should be a cart not a weird standing mount

**Comment by mc-oofert** [comment]
> Sprite should be a cart not a weird standing mount

well too fucking bad I'm not sprouting that

**Comment by SomeoneYouProbablyKnow** [comment]
I love power creep. The whole point of the defib is that's annoyting to carry, you either have to constantly swap to it or have your bag stolen. This just negates all the downsides as dragging this thing is so much more conventient than the alternatives. It's probably even more convenient than the actual belt defib (barring its use in combat).

Also yes spritebash a cart (The surgery cart is in the code just slap a defib in there) or ask someone else to do it we have a whole dedicated spriting channel in discord don't we

**Comment by mc-oofert** [comment]
> I love power creep. The whole point of the defib is that's annoyting to carry, you either have to constantly swap to it or have your bag stolen. This just negates all the downsides as dragging this thing is so much more conventient than the alternatives. It's probably even more convenient than the actual belt defib (barring its use in combat).

uhh you stink + theres a silly bug that retracts the defib if it moves while pulled that im calling a feature

**Comment by mc-oofert** [comment]
new codersprite


image
image

**Comment by SomeoneYouProbablyKnow** [comment]
> uhh you stink

I don't kink shame but you should should really stop sniffing people

> new codersprite

Heck yea

**Comment by Admiral-Gigaton** [comment]
yipee! new sprite that DOESNT look like dookie!

**Comment by SimplySmiley123** [comment]
> > I love power creep. The whole point of the defib is that's annoyting to carry, you either have to constantly swap to it or have your bag stolen. This just negates all the downsides as dragging this thing is so much more conventient than the alternatives. It's probably even more convenient than the actual belt defib (barring its use in combat).
> 
> uhh you stink + theres a silly bug that retracts the defib if it moves while pulled that im calling a feature

+ it's a dragged object that will likely get stolen if you try taking it out of medbay, or even in medbay because god knows people will try and steal it

**Comment by projectkepler-ru** [comment]
Can you make a penlite variant aswell?

**Comment by MrDoomBringer** [comment]
no the point is you get your backpack stolen bad bad bad bad

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
