### PR TITLE
New air alarm sprite

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Air alarm has a new sprite and no longer rotated, similar to APCs and other wall equipment and posters.

image

New animations:

dreamseeker_tSjHABktpW

## Why It's Good For The Game

The new sprite is a bit more compact to make it look better on side walls without rotation.

The rotation is removed because the sprite has words and to be consistent with all other wall-mounted equipment, like APCs, light switches, etc.

## Changelog

:cl:
image: Air alarm sprite and animations changed
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
Please make it rotate with the wall side it's on

**Comment by MTandi** [comment]
> Please make it rotate with the wall side it's on, the rotation is super helpful especially for AIs, who will see multiple rooms at once.

It's the main reason for this PR. Everything else is not rotated, but air alarms are. APCs follow the same logic. They belong to the side they are closer to.

**Comment by DATA-xPUNGED** [comment]
> > Please make it rotate with the wall side it's on, the rotation is super helpful especially for AIs, who will see multiple rooms at once.
> 
> It's the main reason for this PR. Everything else is not rotated, but air alarms are. APCs follow the same logic. They belong to the side they are closer to.

Aren't the airlock buttons also rotated?

**Comment by MTandi** [comment]
> Aren't the airlock buttons also rotated?

They are, and telescreens too for some reason.

**Comment by Wallemations** [comment]
> > Please make it rotate with the wall side it's on, the rotation is super helpful especially for AIs, who will see multiple rooms at once.
> 
> It's the main reason for this PR. Everything else is not rotated, but air alarms are. APCs follow the same logic. They belong to the side they are closer to.

Air alarms are much wider than APCs which makes them look really weird when they're not rotated

Also why aren't APCs rotated??? It makes sense to me that they should be.

**Comment by MTandi** [comment]
> Air alarms are much wider than APCs which makes them look really weird when they're not rotated

That's why I made a sprite that is less wide, 3 pixels to be exact. I had a smaller version but people said that it may be hard to click on.

image

> Also why aren't APCs rotated??? It makes sense to me that they should be.

First - they have status buttons, and you can tell what is enabled and what is not when you know the order. When you rotate APC, it would be hard to read this information.

And rotation is just bad in top down in general. It makes it harder to recognize objects, as you need to remember 3 things instead of one, unless they are symmetrical.

**Comment by Wallemations** [comment]
> And rotation is just bad in top down in general. It makes it harder to recognize objects, as you need to remember 3 things instead of one, unless they are symmetrical.
> 
> Also, anything with text should not be rotated. Those bluespace gas vendors also need a different sprite.

That's what the little light on the air alarm is for. Even if APCs have those little lights with orders to them, the only signal air alarms visually give is their status in color, which is far easier to see no matter the orientation.
While I'm a fan of making that screen bigger like you did, I'm not sold on the color palette used.

**Comment by MTandi** [comment]
> That's what the little light on the air alarm is for. Even if APCs have those little lights with orders to them, the only signal air alarms visually give is their status in color, which is far easier to see no matter the orientation.

Still, we need consistency. It just looks bad when sprites follow different styles.

If we had Zelda style walls, I would agree that everything should be rotated.

<details>
  <summary>Zelda style</summary>
image 
</details>

If we had 3/4 walls, everything should have 3 versions of directional sprite.

But we have flat walls right now and things should have one direction.

> While I'm a fan of making that screen bigger like you did, I'm not sold on the color palette used.

Please help me out on the palette if you know how exactly it can be improved.

**Comment by zxaber** [comment]
>If we had 3/4 walls, everything should have 3 versions of directional sprite.

Have you heard of our lord and savior, The Wallening™?

**Comment by Imaginos16** [comment]
Yeah, sorry. I really do not like this sprite.

**Comment by MTandi** [comment]
@Imaginos16 please take a look at the updated version.

**Pull request closed without merging**
