### PR TITLE
adds cakehat suicide

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
cakehat.

## Why It's Good For The Game
cakehat buff.

## Changelog
:cl: SuicidalPickles
add: Cakehat now has a suicide.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
hip

**Comment by ATH1909** [comment]
It should debrain you.

**Comment by tralezab** [comment]
@ATH1909 OR INVOLVE EATING THE CAKE

what has this world come to dude

**Comment by nemvar** [comment]
No seriously, this doesn't even put the cakehat on your head, nor does it turn it on.

**Comment by QualityVan** [comment]
doesn't account for the cakehat potentially being already lit

**Comment by Suicidalpickles** [comment]
im lazy, shitpost pr

**Pull request closed without merging**
