### PR TITLE
Changes ant desc & fixes ph requirements of ant breeding

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Further differentiates our ants from other possible ants.
Increases ant ph resistance when mating.
Adds some reaction flags I forgot to put in before.

## Why It's Good For The Game
It takes a good amount of sugar to breed ants, which raises the ph level, which I didn't account for.

## Changelog
:cl: Wallem
fix: ants have a higher tolerance to extreme ph levels when breeding. New ant desc.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Still forgot to credit the goon ant guy lmfao

**Comment by Wallemations** [comment]
> Still forgot to credit the goon ant guy lmao
> 
> (you need to edit your old changelog, ask in coderbus if you're unsure how)

goddamnit you're right, I'm way too tired for this. I'll go ask.

**Comment by Mothblocks** [comment]
you just edit the changelog yml file

**Comment by Mothblocks** [comment]
1 to 13 ph range zzz

**Comment by Wallemations** [comment]
> 1 to 13 ph range zzz

I can shrink it if you'd like, I felt the default was too restrictive.

**Comment by Wallemations** [comment]
Well that didn't function properly. Time to figure out how to fix changelog conflicts.

Also, I REALLY hope I'm crediting them correctly. I don't want to end up not crediting someone enough.

**Comment by Wallemations** [comment]
[#60330] fixes the changelog issue

**Pull request merged**
