### PR TITLE
[s] adds elite sec

### PR DESCRIPTION
**Pull request by Bawhoppen**
adds elite sec officer for april fools day

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Open april fools shit when its actually april fools

**Comment by YotaXP** [comment]
**BUG**
Just compiled and ran the branch.  Elite Security Officers show in the occupation preferences, but you can't actually raise or lower its priority.

**Comment by Bawhoppen** [comment]
@YotaXP 
>+	minimal_player_age = 1000000000

**Comment by F-OS** [comment]
i really dont think players are 27397.260274 centuries old

**Pull request merged**
