### PR TITLE
[Cere] QOL fixes

### LINKED ISSUE #27605: [Cerestation] Firelocks and blastdoors appearing above open airlocks.
One place this happens is primary tool storage by botany, it also happens in many many other places. The solution is to actually place the airlock above the firelock, I'm assuming you placed the firelocks above the airlocks kind of as an afterthought. This makes it impossible to shut airlocks behind you. 

@MMMiracles

### PR DESCRIPTION
**Pull request by ShizCalev**
Cargo -  Fixed status display locations in disposals room.
Sec - Added paper bins to a couple tables and station bounced radios to the sec lockers in the armory.
Robotics - Added health scanners (they were missing and you couldn't construct medibots.)
Bar - Added bartender's locker.
Engineering - Added more gloves.
Toxins - Added EOD closets
Research - Added cooling system and air vents to server room.
General - Added a few more fire extinguishers in the hallways.
Mining Dock - Removed mesons.
Maintenance - Scattered a few more pickaxes around.
Heads - Added keycard auth device to HOP's office.

Fixes #27605
Merges and fixes changes with #27612

### CODE REVIEW

**Comment by MMMiracles** [comment]
stop nullifying my local PRs DANGIT

also thanks

**Comment by MMMiracles** [comment]
I didn't notice that you gave toxins a freezer so this is an immediate negative on my part.

Toxins not having a round-start freezer is intentional and all whiny babies who need it for their round-start maxcaps can go build their own freezer if they need it so bad, or go the other multitude of routes for gaining chilled canisters.

**Comment by ShizCalev** [comment]
@MMMiracles Removed the freezer and also cleaned up some duplicate firelocks.

**Comment by MMMiracles** [comment]
Alright, no issues here then.

**Comment by ShizCalev** [comment]
Thanks for bringing that up by the way, just caught that there's no cooling system in the RD server room.

**Pull request merged**
