### PR TITLE
[wip]Experimental changes to !LAZY LIST HELPERS!, atom colors, req_access lists, and acted_explosions

### PR DESCRIPTION
**Pull request by silicons**
Tweaked atom_colours, req_access, req_one_acecss, acted_explosion lists to not be initialized/set to an empty list before it's actually necessary to have a list

Hopefully? optimized lazy list helpers.

### CODE REVIEW

**Comment by kevinz000** [comment]
Requesting testmerge on this, local testing isn't showing errors but you know, better safe than sorry?
Also, overlay changes dropped.

**Comment by Cyberboss** [comment]
>Hopefully?

Needs profiling

**Comment by kevinz000** [comment]
Can someone help me with how to profile lazy list helpers and lists in general properly? Bot32 gave me inconsistent results last time I did it.

**Comment by kevinz000** [comment]
LAZYINITLIST:
image

**Comment by kevinz000** [comment]
still profiling the rest

**Comment by kevinz000** [comment]
not worth

**Pull request closed without merging**
