### PR TITLE
Revolutionary Accessibility Tweaks

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Tweaks the colour of regular revolutionary hud sprites to be orange instead of red, at the request of @Jared-Fogle. I also straightened out the weird-ass bend in the R's leg, which I'm sure bugged everyone else as much as it bugged me.

## Why It's Good For The Game
_May_ help some people with colourblindness, and makes the colours more complementary.

## Changelog
:cl: Citoyen Inept-At-Job
tweak: Proclamation from the Committee of Public Safety, 13 Prairial DCCLXIX: Revolutionary huds have underwent some small tweaking for accessibility reasons, citoyens.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
i'm like 80% sure that i was misremembering orange/blue being better for accessibility vs red/blue, but also i just think it looks better 😛

**Comment by MrPerson** [comment]
You should include a screenshot in the PR body

**Comment by Rohesie** [comment]
@Twaticus

**Comment by cacogen** [comment]
where is that orange NPC image when you need it

**Comment by cacogen** [comment]
It's not often you make a PR that gets closed wordlessly by a maintainer

**Pull request closed without merging**
