### PR TITLE
Overlays for computers

### PR DESCRIPTION
**Pull request by Jordie0608**
This makes computer use overlays for screens and keyboards as well as removes some unused icons.
ai_core.dm moved out of computers directory as it is a structure.
I'm not sure why solar controllers aren't actually computers but I don't want to do path changes here so will address that later.
Before: 68.9 KB
before
After: 28.8 KB
after

### CODE REVIEW

**Comment by WJohn** [comment]
Oh hey, does this allow us to make computer screens full bright in pitch darkness? That'd be awesome.

**Comment by Jordie0608** [comment]
Would make that possible, but is not a feature of this PR.

**Comment by WJohn** [comment]
I'm hoping that becomes a thing, that'd be really cool!

**Comment by xxalpha** [comment]
:+1:

**Comment by GunHog** [comment]
We can take this chance to make a cooler looking computer frame.

**Comment by Dorsisdwarf** [comment]
I remember when I first suggested this coderbus told me "Why do that you wouldn't save any space"

**Comment by Kelenius** [comment]
>Solar controllers

Because they need to be put on a wire to work.

**Comment by WJohn** [comment]
Also jordie with both VV in game and map editing: Does this let us choose which computer screen and which keys we want? Or is that dependent on the computer path? I'd love to be able to mix and match some of these.

**Comment by xxalpha** [comment]
It looks like if you change 'icon_screen' and 'icon_keyboard' and then call update_icon() you can change the icons on the fly.

As for map editing, you need just to edit the vars.

**Comment by freerealestate** [comment]
:+1: Looks good.

**Pull request merged**
