### PR TITLE
adds headpatting

### PR DESCRIPTION
**Pull request by imsxz**
About The Pull Request
i made a PR just like this like a year or 2 ago and it got closed under dubious circumstances, especially since it had more upvotes than downvotes. this is a feature that the community wants. it is a 5 line change PR, not much to note on it, very simple.

Why It's Good For The Game
/tg/ is lacking in roleplay tailored mechanics and instead relies on the good graces of the players to interact politely with each other.

Changelog
:cl: imsxz
add: you can now pat carbon mobs on the head. 
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by wesoda25** [comment]
Thought this was gonna be another cock vore pr

**Comment by Doosteroni** [comment]
Please consider this an unfriendly reminder: This is cringe

**Comment by SweptWasTaken** [comment]
tenor

**Comment by imsxz** [comment]
poggers3

**Comment by itseasytosee** [comment]
Fuck this community,

**Comment by LemonInTheDark** [comment]
From #49143
```
#21352 - first attempt (closed)
#24062 - second attempt (merged)
#24066 - alternative to above (closed)
#24176 - maintainer has regrets revert attempt (closed)
#28028 - later revert attempt (merged)
#33841 - re-add attempt (closed)
```

**Comment by Jared-Fogle** [comment]
image

**Comment by GunHog** [comment]
> From #49143
> #21352 - first attempt (closed)
> #24062 - second attempt (merged)
> #24066 - alternative to above (closed)
> #24176 - maintainer has regrets revert attempt (closed)
> #28028 - later revert attempt (merged)
> #33841 - re-add attempt (closed)

You missed one: https://github.com/tgstation/tgstation/pull/23989
Make sure you disable maintainer edits to avoid getting memed!

**Comment by itseasytosee** [comment]
Picture this, Its the year 2134 and some poor soul has just discovered this old as shit game called Space Station 13. Obviously all the servers have been down for over a century, but he's found some old videos on the facebook-youtube conglomerate that have been archived. Now, this poor soul is a bit of a programing geek, and just finished a computer science degree. Perhaps they can download the sorce-code and run it themselves. They manage to find an archive of TG station's very own github and begin reading though some of the PRs and milestones. They notice a milestone named fuck up of the year, they kek at all the stupid things that have happened over the run of this game's development. They keep going through the years one by one engrosed in the comedy of times passed. When eventuly they reach fuck-up of the year 2020. They click on this PR, notice the sheer stupidity of this overdone non-joke and enter a confused rage. They quickly cross check your git-hub account and find other old online sight you were a part of. Eventuly They find your name and our date of death. They drive through the border between Canada and newfranceland, and eventually make it to the cemetery in which you are buried. And they piss on your fucking grave.
Is this really the legacy you want?

**Comment by Tharcoonvagh** [comment]
Sweet a new copypasta

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

your PR will be closed if you do not.

**Comment by optimumtact** [comment]
Can we not people

**Comment by Winterous** [comment]
This would need to change the text of the "been hugged" mood buff to be less specific, or change depending upon the most recent interaction.
"Warm cozy hugs are the best!" Doesn't make sense following a headpat, but just word replacing it with "Warm cozy headpats are the best!" make sense either.

**Comment by Doosteroni** [comment]
Dog my comment got like 6 laugh reactions I want to be reimbursed or so help me I will see you in court!

**Comment by imsxz** [comment]
image

**Review by CitrusGender — APPROVED** [review]
looks good, ready to pr.

**Comment by optimumtact** [comment]
Your PR has been closed due to having a misleading or incorrect title, adjust the title and ping me to reopen it or make a new PR with a properly descriptive title and body content.

**Comment by wesoda25** [comment]
Eww imsxz you’re not actually being serious are you?

**Comment by kriskog** [comment]
We like headpats

**Comment by Tharcoonvagh** [comment]
**FUCK**

**Comment by Doosteroni** [comment]
I have never once held such a disdain for one man until now. Damn you and your entire wretched bloodline Kriskog

**Comment by wesoda25** [comment]
Ewwwwww

**Comment by BloodyHuggable** [comment]
Where's the funny

**Comment by AtlasRules** [comment]
/tg/station and its consequences have been a mistake for the SS13 playerbase

**Comment by FargothUr** [comment]
This is a gateway to legalising erp

**Comment by itseasytosee** [comment]
oh well, we had a pretty good run.

**Comment by imsxz** [comment]
hypno3

**Comment by Winterous** [comment]
Plot twist: Bea Socks is IMSXZ on an alt, not wanting to ruin her hard-boiled reputation.

**Pull request merged**
