### PR TITLE
Moves the belt layer under the suit layer

### PR DESCRIPTION
**Pull request by ghost**
Pros:
Belts are attached to jumpsuits (they fall off when you take jumpsuits off) so this makes more sense
Belts/holsters and stuff don't go outside of suits or labcoats
Belts aren't strapped around space suit waists anymore which (subjectively) looks stupid
Belts aren't accessible via stripping when someone is wearing a space suit anyway, so it makes more sense

Cons:
Sort of stupid consistency issue with people using toolbelts INSIDE their space suit, but this isn't as much of a mindfuck as it is for belts to be attached to jumpsuits and unable to be stripped while the user has a space suit on
Impossible to tell what belt a user is wearing when they have a space suit on, which is already the case for examining them (space suits conceal the belt slot with the examine verb)

### CODE REVIEW

**Comment by WJohn** [comment]
Aren't ties and other clip-ons handled as overlays? Can't you mess with the layer they get when put on?

**Comment by paprka** [comment]
Holsters aren't ties and neither are toolebelts

**Comment by RemieRichards** [comment]
I don't like it, this isn't needed.

**Comment by paprka** [comment]
Well belts are under the suit layer as far as inventory and the strip panel goes so this is really something that should have been done ages ago. Suits conceal belts because they're attached to jumpsuits, so.

**Comment by Chocobro** [comment]
i'm for this.
we can explain getting tools from behind a hardsuit as hydraulic arms shooting it up and out the wrists. also hardsuit handjobs. woo woo :+1:

**Comment by dannno** [comment]
I was against this because of the hardsuit thing but it kinda makes more sense to do it like this soooooo

**Comment by Miauw62** [comment]
Won't this cause sprite clipping with your overlay secbelt thing?
Op 3-feb.-2015 14:34 schreef "dannno" <notifications@github.com>:

**Comment by xxalpha** [comment]
>Belts aren't strapped around space suit waists anymore which (subjectively) looks stupid

How would people with toolbelts reach their tools then?

**Comment by paprka** [comment]
the same way toolbelts are blocked from being stripped when underneath hardsuits

visual consistency is more important here, due to how the strip menu and strip flags are set up.

When you put on a hardsuit, your belt magically moves outside of the hardsuit, and when you remove your jumpsuit, it magically falls of your hardsuit. It's really stupid, a lot more stupid than 'how do they reach the toolz?'

**Comment by xxalpha** [comment]
>When you put on a hardsuit, your belt magically moves outside of the hardsuit, and when you remove your jumpsuit, it magically falls of your hardsuit. It's really stupid, a lot more stupid than 'how do they reach the toolz?'

This isn't really a problem, is it? You'd have to change a lot to achieve consistency, not just this small change.

**Comment by dannno** [comment]
this change is a net gain

**Comment by Fox-McCloud** [comment]
I don't like this either; visual communication is important, and this obscures it more than it clarifies it--mostly in the name of "realism". 

I'm all for realism, but sometimes it should take a backseat to better clarified visual communication to players. Yes, I know examine still exists and it's fairly easy to use, but it still requires incredibly more effort to do than just half glancing at someone and seeing the belt on them.

**Comment by paprka** [comment]
belts are obscured by hardsuits anyway, this has always been the case, just not visually

is this really a big deal, does knowing what's on someone's belt slot decide your fate 100% of the time or something?

news flash, people in engineer rigs might have toolbelts on, what else is new?

**Comment by Tenebrosity** [comment]
I like it overall :+1:

It is sort of annoying people can get their tools through their space suit but I wouldn't want that disabled and I think trying to make it so that putting a belt on after a space suit attaches it to the space suit would take too much effort and require snowflakey code

**Comment by Jordie0608** [comment]
Changelog.

**Comment by paprka** [comment]
Changelog.

**Comment by Stickymayhem** [comment]
Finally the detective with a secbelt won't look like a fucking weirdo

**Comment by Cheridan** [comment]
Honestly I'd just prefer if belts were the same visibility as they are now, but didn't fall off when you took your pants off. 

If I can take off my jumpsuit while keeping my spacesuit on, I can do the same with a belt.
Also lets people run around wearing nothing but a toolbelt :hotsprings: :love_hotel:

**Comment by phil235** [comment]
>which is already the case for examining them (space suits conceal the belt slot with the examine verb)
I tested it and that's not the case, you see the belt when examining a person w/ hardsuit.

The new belt layer is only nice for 'open' suits like detective vest, labcoat, wintercoat,etc). The better solution would be to make a layer for open suits and one for closed suits (hardsuits, armors) so that the belt appears in front of hardsuits but below labcoats.

(and having belts not hidden by hardsuits in the clothing window would be great I think)

Also, as cheri said, belt shouldn't fall off with your pants.

So overall, :-1: , not the right fix.

**Comment by paprka** [comment]
Examine not hiding your belt is the bug, not the strip menu hiding your belt. Exosuits intentionally have a flag to block stripping of belts

**Comment by paprka** [comment]
I got a better solution for this.

**Pull request closed without merging**
