### PR TITLE
[s] test new mdb with box and meta full renderings

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by iskyp** [comment]
get rid of the dick in morty message and maybe the new mdb will be ok

**Comment by Cyberboss** [comment]
@iskyp I'm going to change it to the entire S1E1 transcript b/c of you

**Comment by Cyberboss** [comment]
It's almost like [anyone can change it](https://github.com/tgstation/MapDiffBot/blob/master/MapDiffBot/Core/PayloadProcessor.cs#L273)

**Comment by iskyp** [comment]
yoU FUCKING BETTER NOT

**Pull request closed without merging**
