### PR TITLE
forensics spoofing tool (for traitors)

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

adds the forensics spoofing kit for 5tc to the uplink (is it really a kit if its only the item and instructions?)
image
image
image

silent mode: if off the scanner will make sounds and messages like a forensics scanner if used (Elliot Wardle points the forensic scanner at the reinforced wall and performs a forensic scan.)

scan mode:
scans stuff for NEWLY discovered fibers and fingerprint, stores them
the scanner may only hold 5 each of fibers and prints
the scanner reads sec records to display names next to fingerprints

apply mode:
it adds the fiber/fingerprint to whatever you use it on

## Why It's Good For The Game

as it is right now forensics scanners are basically a guaranteed "this guy is an antag" if they scan anything syndicate related and find your prints on it (or fibers). that is not ideal because you will spend the next 30 minutes of your time getting trolled in the permabrig by security

with this item you (traitor) get the benefit of the doubt which is good and makes detectives legit use their brain beyond CTRL+C CTRL+V on sec records

## Changelog
:cl:
add: forensics spoofing kit for traitors/whoever with an uplink
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
You can just c/p your fingerprint ID in the security records with another person's to frame them. All you need is an emag, sec ID, or smooth tongue.

**Comment by DaydreamIQ** [comment]
Isn't the silent mode kind of redundant when only people with sec access can get scanners? Meaning it's kind of suspicious to be carrying one in the first place

**Comment by CRITAWAKETS** [comment]
This feels like it's going to make forensics never get used for traitors and pretty much only heretics.

**Comment by deathrobotpunch** [comment]
> This feels like it's going to make forensics never get used for traitors and pretty much only heretics.

keep in mind that it’s 5 credits, most people won’t get it unless they need it.

**Comment by mc-oofert** [comment]
> This feels like it's going to make forensics never get used for traitors and pretty much only heretics.

who says traitors can't put prints on rifts

**Comment by mc-oofert** [comment]
> Isn't the silent mode kind of redundant when only people with sec access can get scanners? Meaning it's kind of suspicious to be carrying one in the first place

you can already catch nonantags carrying the wildest shit imaginable I doubt they'd check unless it's the sole thing

**Comment by mc-oofert** [comment]
> You can just c/p your fingerprint ID in the security records with another person's to frame them. All you need is an emag, sec ID, or smooth tongue.

you can avoid jumping through all of those hoops by paying 5tc

**Comment by mc-oofert** [comment]
probably could add soap to the kit to make it worth 5tc proper or whatever else not sure

**Comment by SomeoneYouProbablyKnow** [comment]
> This feels like it's going to make forensics never get used for traitors and pretty much only heretics.

Not really? I doubt many people would even use this item thus actually improving its effectiveness. Fewer detective who'd be able to catch something like that.
But also... that's the whole fantasy of being a detective, actually solving things, figuring out what's real and what's not. Otherwise rhey are just a busboy for the funnt valid scanner.
Sometimes people will fall for it, sometimes they won't. Most of the time detectives will continue as usuall.

**Comment by DrDiasyl** [comment]
> This feels like it's going to make forensics never get used for traitors and pretty much only heretics.

Soap can remove fingerprints and fibers from an item, and soap is *free.*
This spoofer won't change any balance that heavily, it will just make Traitor gameplay more interesting as framing is fun and will make Security learn not just to trust the prints.

**Comment by Likteer** [comment]
The solution to boring 1D forensics tool is an EVIL boring 1D forensics tool?

**Comment by mc-oofert** [comment]
> The solution to boring 1D forensics tool is an EVIL boring 1D forensics tool?

yeah

**Comment by DrDiasyl** [comment]
> The solution to boring 1D forensics tool is an EVIL boring 1D forensics tool?

Give a solution to the 'simplicity' of forensics then.

**Comment by mc-oofert** [comment]
idk wtf do you want from forensics anyway like if you remove the scanner and replace it with like using that cool white powder they use in those detective shows then thats practically the same thing as using a forensics scanner

you cant really do much with it because we have fingerprints and fibers at best we dont have like super detailed bone splinter simulation mechanics to check who got hit where with what and not have it be also a boring forensics tool (coroner)

**Comment by CRITAWAKETS** [comment]
> > This feels like it's going to make forensics never get used for traitors and pretty much only heretics.
> 
> who says traitors can't put prints on rifts

oh great so absolutely no forensics result can be trusted from now on since it could just point to the outright wrong person, wasting valuable time because our antags are all progression-based

guess detective was only meant to be security with a revolver anyway

**Comment by Loafin34** [comment]
it's 5 tc, usually syndicates are caught in the act or have already hidden the body, can't be that common

**Comment by uaioy** [comment]
> > > This feels like it's going to make forensics never get used for traitors and pretty much only heretics.
> > 
> > 
> > who says traitors can't put prints on rifts
> 
> oh great so absolutely no forensics result can be trusted from now on since it could just point to the outright wrong person, wasting valuable time because our antags are all progression-based
> 
> guess detective was only meant to be security with a revolver anyway

right now the forensic scanner utility makes the detective, not the other way around. if theres no detective then a sec off will just grab the forensic scanner and nothing will change, cause theres no need to actually investigate stuff when you can just grab the item that has a high chance to tell you who the antag is on 1 click

**Comment by Getonus** [comment]
Why would traitor use this, if the common strategy is just to kill detective before you get spotted

**Comment by DrDiasyl** [comment]
> Why would a traitor use this, if the common strategy is just to kill the detective before you get spotted 

Not everyone does and it is not that popular. There must be different ways of playing the game.
With such logic, most of the stealth Traitor gear is obsolete as you can just bomb all of the Brig

**Comment by SomeoneYouProbablyKnow** [comment]
Is it? Like actually is it? Because i dont think i've seen that happen all that often, and more often then not someone else is carrying the second scanner for no reason.

**Comment by mc-oofert** [comment]
name your byond ckeys so I can check which haters main security

**Comment by mc-oofert** [comment]
what's a dude gotta do for a review....

**Comment by mc-oofert** [comment]
guhhhhhhh

**Comment by uaioy** [comment]
damn PR is still open

**Comment by mc-oofert** [comment]
its been a month

**Pull request merged**
