### PR TITLE
Buffs the ultra ac

### PR DESCRIPTION
**Pull request by ghost**
Right now it deals less damage then the scattershot, is about as accurate as the scattershot, and doesn't have the stamina damage of the scattershot. This adds 2 more projectiles, bringing it up to 5 projectiles each doing 20 brute damage. This means, unlike the scattershot, it can instantly crit. It also does maintain better damage at range then the scattershot.

:cl: vcordie
tweak: Modifies the firing pin on the ultra ac 2, changing it to five round bursts.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
I dunno it's already extremely powerful. Its ability to spam it down a hallway in an effectively endless stream of bullets is fantastic at killing huge groups of people quickly.

**Comment by jughu** [comment]
Arent mech already strong enough jesus

**Comment by Robustin** [comment]
The scattershot should NOT be the baseline for mech weapon effectiveness. If anything the scattershot should have a few damage knocked off its pellets because of how unbeatable it is in close quarters (hint: 90% of the station is CQC). 

I like the idea of scattershot being the baseline for mech weapons as much as I like the idea of all other sec weapons brought up to the combat shotguns level of effectiveness.

**Comment by kevinz000** [comment]
>Thinks AC2 is bad<
>Wants instacrit AC2<
Dude, get good, as a science player I'm telling you you're just bad at mechs.

**Comment by optimumtact** [comment]
This is probably too powerful like this

**Pull request closed without merging**
