### PR TITLE
Slaughter demons rise up

### PR DESCRIPTION
**Pull request by Timonkeyn**
## About The Pull Request

makes the slaughter demon random event more common

## Why It's Good For The Game

they arent used outside of admin events and the wizard gamemode, but there is a random event for it. so why not make it more common?

## Changelog
:cl:That one Catboy
tweak: Nanotrasen Scouts have reported the Wizard Confederation to be massproducing Bottles of Blood! Beware!
/:cl:

### CODE REVIEW

**Comment by Timonkeyn** [comment]
goddammit

**Comment by Timonkeyn** [comment]
just to clarify, i didnt want that first commit in

**Comment by Timonkeyn** [comment]
easy fix brothers

**Comment by XDTM** [comment]
Their whole gameplay consists on murderboning the crew while avoiding the one guy with the combat shotgun, it's just going to ruin the game whenever it happens if demons aren't reworked first

**Comment by Michael-Ashfield** [comment]
I definatly wouldnt have it as rare as the blob event, blob isn't too rare to see and can be fairly easily killed.

**Comment by ExcessiveUseOfCobblestone** [comment]
we already have the murderbone event which is space dragon. I'm not really interested in 50 shades of red.

**Comment by FloranOtten** [comment]
The entire mode is just "Guy with superpowers runs around killing people for no reason until the person targeted has a shotgun". Not very fun for the crew.

**Comment by Shadowflame909** [comment]
@XDTM 
@ExcessiveUseOfCobblestone 

You guys are missing the bigger picture.

Their gimmick actually INCREASES involvement in otherwise overlooked jobs.

What do I mean? Take a look at the Bartender and Janitor. Cruelly shamed and bored all shift. One gets beaten up for cleaning with water, and the other gets pied and greytided until they whip out the shotgun.

This antagonist, like Devil. Makes jobs that are otherwise uncared for, more important and very valuable to keeping the station afloat.

I say, making more jobs have things to look forward to and face off against. Is a very good change indeed.

On the other end, I honestly want to replace it with a Laughter-Demon event and extremely boost its spawn chance and time. Probably the same as Xenos.

**Comment by FloranOtten** [comment]
> snip

Is the fun of two jobs worth sacrificing the fun of the many? Some people may like the event but others don't. I certainly don't, because the event boils down to semi-random death. There's no reason you got killed, you were just near a blood patch  that was hidden. Sorry.

**Comment by Shadowflame909** [comment]
Bro. Slaughter Demons are cheese tier.

I'll tell you the same thing I tell to everyone that gets solo'd by a slaughter-demon/devil.

DON'T MELEE IT. Think of it like bubblegum or a Bear in real life. The last thing you want to do is try and kick its ass mono on mono.

No. You play dirty. You throw floor tiles at it, you run past it as it'll eventually slowdown. You get soap/cleaner grenade to prevent them from jaunting/a mop since those can be printed now. 

The point is, some things just shouldn't be melee'd. It's not difficult or OP. It's just that you're using the wrong strategy. 

Now if you're going to melee it anyways. Go to the bar, drink a devils kiss, and wham it good. Because that drink will finish it off.

**Comment by ExcessiveUseOfCobblestone** [comment]
We don't need the occasional murderboning demon on top of whatever's currently in the round to make these jobs more involved/interesting.

Not every conflict requires a player controlled baddie.

**Comment by nemvar** [comment]
The perfect ghost role antag are swarmers. Why? Because they don't murderbone, they leave the murdering to the people that actually got a stake in all of this, the original crew. All the others are basically just a meatgrudgers and meatgamers dream.

The second best is blob, because the conflict is opt-in. A lone blob will never win, but with the help of the antag on the station, he stands a good chance of winning.

Third place goes to lone op because he isn't extremely overtuned and has the same counters as any normal person. He also usually ends the round instead of just continuing the round forever if he wins.

See what all of them have in common? All of them basically end the round if they win. You know what doesn't do that?? That's right, all the bad midrounds. Space Dragon? Xenos? Even ninja to an extent. If they win and the crew hasn't called the round tends to just float into boredom. Midrounds should create a threat to the entire station, instead of being a death sentence to those unfortunate to randomly stand in their way.

Slaughter demons are the single most boring antag in the game. They are a lot like chrono legionaires, just even more annoying. Before you even consider making them a usual midrounds, gives them some basic shit. It's embarrasing that we have simplemobs that are DESIGNED to be played by actual fucking humans and don't have a proper HUD. It's embarrasing that we have a fucking antag that deletes people from the round with usually only one or two hits (because if you are slowed, you are dead) and the entire warning that's about to happen is a small text message, at least give it an animation for christs sake, the icons are already in the code.

Thanks for listening to my rant.

P.S. to "DoN't MeLeE iT"
You don't have a lot of choice for engagement range, because the demon decides when it wants to engage and can literally teleport. Even just trying to say something while near (5 tiles) to a blood puddle can easily get you killed. Try mopping up blood while a demon is around and tell me how that went for ya.

**Comment by Shadowflame909** [comment]
So what your saying is...

This Wizard Antagonist should be able to evolve into Bubblegum after eating enough people...

**Comment by nemvar** [comment]
It evolving into bubbles after eating 70% of the crew honestly sounds better than the three powergamers trying to chase it down. I have played that demons that did that before.

The thing is that you can force every other antagonist into an engagement except maybe abductors and even then you have a better chance of doing it because they need cameras. And even abductors are easier to fight because they can suffer attrition by losing their baton. None of them have an instant 'get-out-of-jail-free' button, and be assured, the demons always has enough lemmings to eat to not suffer any attrition from engagements.

Saying that you even have ANY control over engagement range with a slaughter demon is redicioulous. The level of control you have is to literally move constantly or hide in your autism fort. You can't engage it at any range other than melee because the demon won't allow it.

It is a badly designed antags from a badly designed chaos mode. Don't bring make this shit common in normal rounds.

**Comment by Ziiro** [comment]
Eating something like 75% of living crew (or a number of bodies that have/had minds equal to this amount) it should just ascend to bubblegum and then end the round.

This would also mean that the wizard has to keep tabs on their demon or else they'll lose, too.

(Xenos should have more or less the same end state too, now that I think about it.)

**Comment by optimumtact** [comment]
You rise up, but fail to shatter the glass ceiling preventing you from reaching the station, curse the patiarchy

**Comment by Timonkeyn** [comment]
this is so sad
can we get an F

**Pull request closed without merging**
