### PR TITLE
Removes unused sprites from robots.dmi

### PR DESCRIPTION
**Pull request by Blacknas**
## About The Pull Request
Removes unused robot sprites in robots.dmi. The unused sprites are now in the github where unused sprites are stored.
These are the sprites that got removed:
unknown

## Why It's Good For The Game
Reduces the rsc size.

## Changelog
:cl: Balky Goat
del: Removed unused sprites in robots.dmi.
/:cl:

### CODE REVIEW

**Comment by bluetshirtguy** [comment]
Removing sec borg sprites is a sin since it's a borg that can be spawned in, unless you're also removing the code for it?

**Comment by YakumoChen** [comment]
> Removing sec borg sprites is a sin since it's a borg that can be spawned in, unless you're also removing the code for it?

Security module uses the treadless secborg sprite

**Comment by bluetshirtguy** [comment]
> > Removing sec borg sprites is a sin since it's a borg that can be spawned in, unless you're also removing the code for it?
> 
> Security module uses the treadless secborg sprite

Fair enough.

**Review by Twaticus — APPROVED** [review]
thank you!

**Comment by TerryTehCoder** [comment]
Correct me if i'm wrong, but can't the centcom borg model be loaded through the admin Borg Panel? Unless there's two centcom borg icons and i'm mixing them up.

**Comment by Blacknas** [comment]
> Correct me if i'm wrong, but can't the centcom borg model be loaded through the admin Borg Panel? Unless there's two centcom borg icons and i'm mixing them up.

The command cyborg which I want to remove does not have moving sprites nor the texture for when it toggles its light.

**Pull request merged**
