### PR TITLE
Fixes engine floor heat absorption

### LINKED ISSUE #16126: Heat absorbtion issue with engine floors.
### What is the problem?

The TEG Combustion chamber can barely hold heat.
### Why is it a problem, or what should have happened?

The hot co2 produced by plasma combustion should stay hot longer than a couple minutes
### How can the problem be reproduced?

On ministation, prepare a burn mix and light it on fire and notice the rapid temperature drop as soon as the fire is out.
### What revision did the problem happen on? (Helpful, but not required)

Tested on commit: 5fb22a9116330c1dd4c064cab9b34c921002511c

Tested some of it with Dunc, it appears that engine floor heat capapcity is almost infinite so any temperature increase on engine floors is essentially rounded away, leeching the temperature from the hot gas rapidly despite it's low thermal conductivity.

### PR DESCRIPTION
**Pull request by Buggy123**
Fixes #16126 

Tested and working, no problems.

### CODE REVIEW

**Comment by Miauw62** [comment]
youre changing a variable to 0

test this

**Comment by Buggy123** [comment]
I will but I can't at the moment.

Looking at the code it doesn't appear that this is ever used in division.

**Comment by KazeEspada** [comment]
>Touching an atmos var
>Its only one var change.

**Comment by kyrahabattoir** [comment]
That will essentially make engine floors heat proof. That's not the solution i was hoping for.

**Comment by Buggy123** [comment]
Yep, just tested it, everything works fine. The turfs still heat up/cool down, etc, no crashes or anything.

Now, what do you mean perfect insulation? I wasn't aware that heat was even transfered through floors.

**Comment by kyrahabattoir** [comment]
Have you checked the turf temperature or the gas mixture temperature?

**Comment by KorPhaeron** [comment]
@kyrahabattoir 

Do you want to go ahead and test this? I think you have a better grasp of atmos

**Comment by Buggy123** [comment]
>Have you checked the turf temperature or the gas mixture temperature?
Yes.

**Comment by kyrahabattoir** [comment]
@KorPhaeron I can always have a look, but i don't know if having zero heat loss is such a great idea considering the stations are not really equipped for cooling air.

If floors don't absorb heat anymore it won't radiate anymore either i believe.

**Comment by Buggy123** [comment]
This only changes reinforced floors. ONLY reinforced floors. As in, literally only the floors in burn rooms. Everything else is 100% unchanged.

A list of areas this affects:
The experimentor room
The toxins burn chamber
The toxins test site
The incinerator burn chamber
The science test area

That's it.

**Comment by kyrahabattoir** [comment]
With this change, anything that uses engine floors is completely adiabatic.

With two basic loads of 3/2 tox/oxy in the burn chamber it is now sitting at 72884.5°C and 85554.3 kPa

I got the TEG spiking at nearly 1MW with this, +- 4 times the normal.

I'm more concerned at what it does to toxins, and dealing with fires in general as the heat has essentially nowhere to go.

**Comment by Buggy123** [comment]
This only affects reinforced areas, the heat only has nowhere to go in dedicated burn chambers.

The increased TEG output sounds odd considering that burn mixes can easily get past 90,000°C currently anyway, unless it's changed in the past few months. a 2-1 tox-oxy mix usually gets above 90,000°C when making bombs in toxins.

**Comment by kyrahabattoir** [comment]
It kind of reduces the "skill" level to get high temperature since you can just pump up more burn mix and push the temperature higher and higher.

**Comment by Buggy123** [comment]
That's exactly how it used to work, at least. I haven't tried it recently but you used to be able to transfer some burning burnmix to a canister and get 90,000°C right off the bat.

**Comment by kyrahabattoir** [comment]
The real solution would be to come up with reasonable heat capacity/thermal conduction value for floors and adjust their melting point instead.

**Comment by Buggy123** [comment]
For just reinforced floors? I mean, being perfectly insulating sounds fine to me, reinforced walls are already perfectly insulating themselves.

Also didn't you just say you liked this idea in the issue report discussion?

**Comment by Buggy123** [comment]
I guess this whole thing only came up because I set engine floors to infinite heat_capacity because fusion kept melting them all and breaking any burnchambers.

**Comment by duncathan** [comment]
Setting their heat capacity to INFINITY only went through because I didn't have a proper understanding of the intricacies of conduction in LINDA. Buggy, your heart's in the right place here, but this isn't the fix we want. 
The real fix would be to find a heat capacity that doesn't melt under normal operating circumstances, but still heats up to prevent the loss of heat that's happening here.

**Comment by Buggy123** [comment]
I don't see why making reinforced floors mimic reinforced walls and be perfectly insulating is such a bad idea.

**Pull request closed without merging**
