### PR TITLE
Adds world/New/Reboot times to the log

### PR DESCRIPTION
**Pull request by Cyberboss**
This lets the coders know exactly how fast this shit is taking in the public logs

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Hardly important--likewise, even *defining* something to have a `Del` makes it hugely more expensive---even if it literally just `..()`

**Comment by RemieRichards** [comment]
Please do not define del.

**Comment by Jordie0608** [comment]
This is already logged at https://github.com/tgstation/tgstation/blob/master/code/world.dm#L227

**Comment by Cyberboss** [comment]
I know, but I'm looking for the exact times that our BYOND code starts and
stops running for profiling reasons.

On Feb 7, 2017 5:29 PM, "Jordie" <notifications@github.com> wrote:

This is already logged at https://github.com/tgstation/
tgstation/blob/master/code/world.dm#L227

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/23833#issuecomment-278163529>,
or mute the thread

**Pull request merged**
