### PR TITLE
Curveee

### PR DESCRIPTION
**Pull request by sack-lunch**
been a long time comming don'tchaknow?

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
What?

**Comment by sack-lunch** [comment]
sorry i got super fucking high and i was trying to merge into wayland's branch i have no clue what I am doing pls send help

**Comment by Farquaar** [comment]
> 
> 
> sorry i got super fucking high and i was trying to merge into wayland's branch i have no clue what I am doing pls send help

Smoking's bad for you, you know

**Comment by sack-lunch** [comment]
don't get high and play with gitbhub is the lesson learned today. weed and code must stay seperate.

**Comment by LemonInTheDark** [comment]
your sins are forgiven

**Comment by BallastMonster** [comment]
> Smoking's bad for you, you know
nerd

**Pull request closed without merging**
