### PR TITLE
[FLUFF] Changes "The Coderbus" bar sign description

### PR DESCRIPTION
**Pull request by Steelpoint**
Changes the description to the following.

"The separation between the bar and station is absolute, we will not listen to your platitudes any longer!"

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Should be "between the bar and the station" if anything, to keep it IC

**Comment by Steelpoint** [comment]
I suppose

**Comment by Cebasiz** [comment]
heh

**Comment by GunHog** [comment]
That description seems to be more suited to they "Greytide" barsign. A better coderbus meme would have something about never serving the same drink and being known for drama.

**Comment by Steelpoint** [comment]
Except its a jab at a coderbus/server related issue.

**Comment by Iamgoofball** [comment]
Just combine the two descriptions, use this one as a quote on the end.

**Comment by KorPhaeron** [comment]
"The separation between The Coderbus and station is absolute, we will not listen to your platitudes any longer. This is MY bar."

**Comment by xxalpha** [comment]
I think it's not fair to make these things when you are not part of coderbus.

**Comment by Cheridan** [comment]
Yeah I don't really think we should pay lipservice to a meme that exists just to make the dev team look bad. Things like the page at https://tgstation13.org/wiki/Fun are good natured humor, but this seems more like snarky political commentary.

**Comment by bustygoku** [comment]
"this is MY bar"

**Comment by Steelpoint** [comment]
What makes you part of the coderbus anyway? A lot of people in game call me a coder for my contributions to the game, so does that make me a coder?

Either way this is meant as a light hearted joke, the bar signs already make a few pokes at different groups and this one more relevant than the prior sign, imo.

I'm not emotionally attached to this PR though, but its just more amusing to me.

**Comment by Xhuis** [comment]
thumbsup

**Comment by GunHog** [comment]
> A lot of people in game call me a coder for my contributions to the game, so does that make me a coder?

Anyone who has had a PR merged recently can be called a coder. It is simply a title for the people who submit changes to the game. The admin rank however, refers to *maintainers*, the people with commit access (ability to merge PRs). Players tend to lump the two together, as it does make sense. A coder puts forth a change, but it is actually added on the approval of a maintainer. Because of this, no less than two coders are always responsible (with some exceptions) for a change made to the game.

**Comment by xxalpha** [comment]
You could start by being in #coderbus.

**Comment by bustygoku** [comment]
I prefer calling people who make changes to the game 'contributors' since it doesn't take programming (coding) knowledge to change a few values imo.

**Comment by Dorsisdwarf** [comment]
The official name for people who code but have never been maintainers is, in fact, Contributors, according to the credits screen.

**Comment by SconesC** [comment]
This is MY bar :+1:

**Comment by optimumtact** [comment]
Wear the badge with pride brothers and sisters

**Comment by Cheridan** [comment]
the separation between the code and the bad jokes is absolute

**Comment by Dorsisdwarf** [comment]
I got a PR pushed which made a suicide joke and an awful pun.

**Comment by optimumtact** [comment]
Wow Cheridan don't be so abusive

**Pull request closed without merging**
