### PR TITLE
Flash powder and sonic powder can now damage organs

### PR DESCRIPTION
**Pull request by sheldoniscool**
## About The Pull Request
Flash powder and Sonic powder can now damage organs.

## Why It's Good For The Game
Because it's dumb when massive reactions which can effect half the map don't damage your eyes/ears

## Changelog
:cl:
add: Flash powder and Sonic powder can now damage organs.
/:cl:

### CODE REVIEW

**Comment by msgerbs** [comment]
Yay so now when somebody sets off a homemade flashbang you can get permanent hearing/eye damage.

**Comment by sheldoniscool** [comment]
> Yay so now when somebody sets off a homemade flashbang you can get permanent hearing/eye damage.

Values can be tweaked but yeah - I might want to add a thing so the damage scales with range. So if the explosion is right on you you're blind but if it's super far it barely does anything.

**Comment by msgerbs** [comment]
Realism aside I think this is going to lead to shit gameplay. Flashbanging a crowd sends them all to medbay for ear and eye damage that might never get fixed because Medbay.

**Comment by sheldoniscool** [comment]
> Yay so now when somebody sets off a homemade flashbang you can get permanent hearing/eye damage.

Also this is obviously way worse than being killed by a homemade grenade

**Comment by msgerbs** [comment]
> 
> 
> > Yay so now when somebody sets off a homemade flashbang you can get permanent hearing/eye damage.
> 
> Also this is obviously way worse than being killed by a homemade grenade

I honestly see more effort put into fixing dead people than fixing people with other injuries, so...

**Comment by evilcyborgmrt** [comment]
This should only affect cat people cause they have big ears and sensitive eyes

**Comment by nikothedude** [comment]
Guys, flashbangs already damage eyes and ears. Have you never been flashbanged by a mech with a clusterbang before? You go blind and deaf almost instanty.

**Comment by optimumtact** [comment]
permabanned as an evasion alt, wait out the 24 day block on your main you got for being a dickhead

**Pull request closed without merging**
