### PR TITLE
the mime's invisible box lasts twice as long

### PR DESCRIPTION
**Pull request by plapatin**
## About The Pull Request
take a wild guess

## Why It's Good For The Game
mime's box is pretty worthless as-is, i'm not sure what the intended use of it is but whatever it is it lasts for way too short of a time to be useful in any capacity, so hopefully giving it a longer summon time will change that

## Changelog
:cl:
tweak: mime's invisible box lasts for twice as long now
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
it should be a permanent one-use spell

**Comment by bgobandit** [comment]
the intended use of the spell is to be able to steal and/or smuggle small items without being detected, such as:

- tator items
- IDs 
- the clown's banana peel that he stupidly left on the floor
- etc.

that said I don't mind it lasting longer, I didn't have a sense of what would be OP or not

**Comment by redmoogle** [comment]
> 
> 
> the intended use of the spell is to be able to steal and/or smuggle small items without being detected, such as:
> 
>     * tator items
> 
>     * IDs
> 
>     * the clown's banana peel that he stupidly left on the floor
> 
>     * etc.
> 
> 
> that said I don't mind it lasting longer, I didn't have a sense of what would be OP or not

do the items fall out once used up?

**Comment by bgobandit** [comment]
they currently do, I vaguely remember there being some issue with putting them in the mime's hands given the way spell timing works but I also could be senile

**Comment by necromanceranne** [comment]
The unfortunate thing is that it competes with Invisible Wall, and that spell is just really, really invaluable. Whatever would replace it would have to be really good.

Even this might not be it.

**Comment by ATH1909** [comment]
Make the box last until you cast the spell again.

**Pull request merged**
