### PR TITLE
Closes the Pool.

### LINKED ISSUE #15377: Pooling has Negative Performance
This may not be for every single pooled thing, but it wouldn't shock me if it was.

Here's a snapshot of breaking lights--keep in mind the pool was pre-filled before this test began, so as to stack things in pooling's favor:

http://www.hastebin.com/ufoceneyew.mel

Here's the same test, only two changes: the place-in-pool hint was removed for the spark effects and `PoolOrNew`  was axed for a plain old `new`: http://hastebin.com/afateyaruq.mel

so say the least, pooling is _significantly_ more expensive than non-pooling; not only in the creation of the actual object, but also in its destruction.

It strongly appears that, even with improvements to `ResetVars`, pooling still generates a net loss in performance over non-pooling.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
So @Fox-McCloud has been trying to warn us, to no avail for like 2 years now. I'm sorry we didn't listen to you when you first raised this alarm. I realllllly wanted to believe.

Basically, the cost of creating an item is less than 1 proc call overhead, so this can never be cheaper unless you inlined all of poolOrNew and GetFromPool OR you made pooling not call New() to remove the proc call overhead from New(), (but that would just cause more bugs and issues.)

todo:

~~fix compile errors from shit expecting this exists.~~ done
fixes #15377 (technically)

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
In addition to what @MrStonedOne said, letting an object garbage collect is by and far way way cheaper than placing it back in to the pool--even with the improvements to resetting variable from VG, it still comes out to be hugely expensive.

Back when the Tesla's beams were costly and taxing on server performance, Goofball tried pooling the beam effects vs letting them GC naturally. This change never went through, but had it, it would have been abundantly clear how expensive pooling is.

Pooling the beam effects would lug the server to a crawl vs letting them GC which wasn't really all that bad, at the end of the day.

**Comment by Kromgar** [comment]
image

**Comment by Cyberboss** [comment]
Closes #15377

**Comment by Iamgoofball** [comment]
# REST IN PEACE POOLING THE BEAMS

**Comment by Shadowlight213** [comment]
Did you try pooling the pool?

**Comment by MrStonedOne** [comment]
Under fox McCloud's test, 0.424 with pooling 0.099 without

**Comment by KorPhaeron** [comment]
@RemieRichards

**Comment by KorPhaeron** [comment]
I trust MSO with my life

**Pull request merged**
