### PR TITLE
Station Engineers Spawn With Industrial Welder 

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR makes it that Station Engineers spawn with a Industrial Welder (40 Units) in their toolbelt, instead of the standard Welder tool. 

Personally I'm a bit conflicted on this proposal but I wanted to propose it anyway. On the one hand I very often never see Engineers either grab a Industrial Welder, or use the secret poly technique to get the Expanded Industrial Welder, hence I think this would be a good change to further help make Engineers just that little better than Assistants.

But on the other hand it would discourage Engineers to check engineering for better tools and it blurs the line between more experienced Engineers and newer ones. 

I'd like to hear your thoughts.

:cl: Steelpoint
add: Station Engineers spawn with a Industrial Welder in their toolbelt. 
tweak: Engineering Welder Locker now only holds three standard Welders.
/:cl:

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
I don't think I agree with this. Engineers starting with a welder is supposed to be what sets them apart from the crew and it's piss easy to get a better welder if you know how

**Comment by Xhuis** [comment]
Gonna have to go with Cyber here; I think the efficient welders should be restricted to a small number.

**Comment by octareenroon91** [comment]
The 40s come from a hacked autolathe. It's the 80 and the experimental welder that are really premium.

**Comment by Steelpoint** [comment]
Engineers can easily get some 80s within Engineering already.

**Comment by Anonmare** [comment]
There are at most 4 upgraded industrial welding tools on the whole station as they come from hacked YouTools and cannot be acquired any other way.

**Comment by Jalleo** [comment]
Looks like a comms failure here. @Anonmare Steelpoint means the hacked autolathe welding tools of which there are four in every welding locker.

**Comment by Steelpoint** [comment]
Ok I think we are all fucking up our communication.

Engineers spawn with standard Welders (20 units).

In the singular Welding closet in Engineering, three Industrial Welders spawn in (40 units).

If you hack a Engi-Vend you can dispense two Expanded Industrial Welders (80 units).

I'm simply having Engineers spawn with a Industrial Welder (40) instead of a standard Welder (20), however the premium Expanded Industrial Welders (80) are still locked behind the hacked Engi-Vend.

**Comment by Tacolizard** [comment]
>On the one hand I very often never

>very often never

what did he mean by this?

**Comment by Bawhoppen** [comment]
This is blatant powercreep is it not?
(don't misunderstand me, powercreep can SOMETIMES be justified, I'm not sure about this case)

**Comment by CosmicScientist** [comment]
I never need a better welder.

Bleb might need to be considered with this change (although that round is won or lost based on a few individuals on both sides and mentality rather than kit alone).

What's wrong with just going to a fuel tank?

I understand you would want to make engies better than greyshirts but in general I find greys have to scrabble over tools or find them elsewhere (okay I have to do that when everyone else takes the last welder or crowbar). I'm not sure if it's necessary since engies are better by having an entire toolkit with a tool belt from the get go.

Another thing to think about is how this might increase engineering break ins (might not) for better kit and then general thievery from engineers. But that might be a good dynamic in itself to influence.


Me no know. What do engineering borgs have access to? Do any of the better welding tools affect burn damage or is it all 15 burn or whatever it is?

**Comment by Jordie0608** [comment]
I don't think this is a warranted change; status quo seems fine.

**Comment by InsaneHyena** [comment]
Power creep

**Comment by improvedname** [comment]
Tbh engineers already get then roundstart so why not

**Comment by KorPhaeron** [comment]
Pure balance change during freeze

**Comment by KorPhaeron** [comment]
If you want to put them in their belts and take them from their lockers I guess that would make sense though

**Comment by adamkad1** [comment]
what ze fuk is freeze anyway

**Comment by Steelpoint** [comment]
I'll make the changes when I get a chance

**Comment by Steelpoint** [comment]
The Welder Locker now only hold three normal Welders instead of Industrial Welders

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
