### PR TITLE
Adds the Medical Wrench

### PR DESCRIPTION
**Pull request by ChangelingRain**
To Dream, Efficiency, Meta, and Box stations.
MEDICAL

### CODE REVIEW

**Comment by GunHog** [comment]
Medical....wrench.....why? It looks like a normal wrench with a penlight strapped onto it! It does not even light up!

**Comment by Jazaen** [comment]
Memes.

**Comment by F-OS** [comment]
i was around for that history making meme, every ghost orbited the medical wrench, wow

**Comment by Zilenan91** [comment]
Can we make an actual medical wrench sprite rather than memes please

**Comment by Incomptinence** [comment]
Just an all white wrench with green stripe would be nice enough.

**Comment by ChangelingRain** [comment]
it says meme pr right on the thing and it's not like the 'actual sprite' would be much different, if it was it wouldn't be a meme

**Comment by Zilenan91** [comment]
So what was the real story of this meme?

**Comment by PKPenguin321** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=2&t=53&start=1300#p164681

**Comment by Bawhoppen** [comment]
the best kind of memes are the low-notice ones like this

anyone remember SUTTLE HERO

**Comment by coiax** [comment]
M E D I C A L W R E N C H

**Comment by Lumipharon** [comment]
ebin maymay.

**Pull request merged**
