### PR TITLE
xray nerf(aka blob buff)

### PR DESCRIPTION
**Pull request by Iamgoofball**
xrays r shite

### CODE REVIEW

**Comment by Xhuis** [comment]
https://www.youtube.com/watch?v=2k0SmqbBIpQ

**Comment by KorPhaeron** [comment]
>removing the irradiate to nerf them against blobs

??

**Comment by Iamgoofball** [comment]
it doubles as a blob buff

**Comment by Supermichael777** [comment]
just make them massively irradiate whoever is holding it when it fires

**Comment by KorPhaeron** [comment]
May as well remove xrays from RD if you're gonna nerf them so hard that you have to hit with every shot to kill a person

**Comment by Zilenan91** [comment]
...Does Blob need the buff?

**Comment by Supermichael777** [comment]
hell no

**Comment by Iamgoofball** [comment]
yes it does
blob has Global success rate (42%)

**Comment by Iamgoofball** [comment]
i havent played a round where mehki didn't have xrays in 10 minutes and the blobs both died within 5 minutes after that in ages too

**Comment by Zilenan91** [comment]
That's because blobs are bad not because the antag is too weak

**Comment by Iamgoofball** [comment]
then why do I see good blob players get their ass handed to them too

**Comment by Zilenan91** [comment]
Because being good at something shouldn't make you instantly win 100% of the time?

**Comment by GunHog** [comment]
Might the blob losses be a result of the huge nerf that happened to them? I.E. removing their ability to sabotage the station before bursting?

**Comment by Zilenan91** [comment]
Nah it's just people being bad and not knowing strategy. I can win 100% of the time as a Blob without sabotage. People just need to get better at it.

**Comment by Iamgoofball** [comment]
your choices are:
1. pop on not-R&D or mining, get fucked by xrays
2. pop on R&D or mining, get fucked because you popped in an open area and be spotted immediately

**Comment by Incoming5643** [comment]
42% is not a bad success rate

**Comment by Zilenan91** [comment]
Or pop in neither because everybody expects you to pop in those places and will instantly fuck you. It's literally strategy. If you can go unnoticed until the level 5 biohazard as a blob and can build up fast enough you are basically guaranteed to win if you can make blobbernauts. People need to get good.

**Comment by Iamgoofball** [comment]
if your choices are 
"r&d or mining"
and
"the rest of the station"

how do you pop on neither?????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by Cheridan** [comment]
The most important stat for blob isn't win rate, it's histogram. 
13/87 (15%, over 1 in 6) blob rounds end in failure in the first 20 minutes. 
After that you have a good chance of losing, up until 30-40 minutes when you tend to win.
After the 30-40 minute mark you get a big drop in success rates. This is x-ray lasers.

X-ray lasers shouldn't be a LOL GG BLOB U TRIED hard counter. But if you take them out without adding other counters, blob just becomes "swarm it in 20 minutes and win... or suffer a long, miserable, inevitable failure".

Stop trying to make well-intentioned but shitty changes without analyzing surrounding circumstances.

**Comment by Iamgoofball** [comment]
forgot about those

**Pull request closed without merging**
