### PR TITLE
Makes wild anomaly spawns more bearable

### PR DESCRIPTION
**Pull request by Time-Green**
## About The Pull Request

- Material anomaly will now self-delete after 1-4 relocations
- Bioscrambler now has a countdown like all other anomalies
- Increased anomaly lifetime from 99 seconds to 120
- Adds some more detonation effects where there were none (see: I abuse the circle effect jacq added (again))

## Why It's Good For The Game

Material anomalies can wreak insane havok throughout the station if it's not caught quickly. It's a cat and mouse game, which can get kinda frustrating (flashbacks to trying to get the anomaly but it constantly teleporting just before I get to it). I don't wanna kill the cat & mouse game, but putting a limit on it so the entire station doesn't suffer endlessly to pizza/snow/jungle toilets is a nice middle road.

Bioscramblers are actually beyond frustrating. If someone doesn't immediately go for them, they'll start locking on and noclipping through the entire station and mutating every single person for the rest of the shift. This would probably be less bad if the bioscrambler couldn't give every single organ (par some blacklisted), causing a lot of irreversible damage, spontaneous combustions, glitches and creeping rare organs and limbs into a round "for the lulz". (This doesn't fix the absolute organ slop that they cause, but reworking bioscramblers not to be shit is for later.) 

I've also given anomalies 20 extra seconds of runtime. Anomalies take 99 seconds, take 30 to announce (for most), giving scientists 69 seconds to get anomaly catching gear and navigate to the area and defuse it. It's always felt like just barely too little time, often not getting the anomaly even when I am beelining. It was usually enough from when we just had meta, but we got bigger and bigger maps. It also gives them more time to wreak havoc for chaos lovers.

## Changelog

:cl:
balance: Bioscramblers are no longer immortal
balance: Anomalies give 20 extra seconds to defuse! Or 20 extra seconds for them to reach havoc...
balance: Material anomalies only teleport 1-4 times before detonating
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Of all the anomalies, I think the most unbearable one is the gravity anomaly. Seems like it always just stunlocks anyone who gets too close.

**Comment by Time-Green** [comment]
> Of all the anomalies, I think the most unbearable one is the gravity anomaly. Seems like it always just stunlocks anyone who gets too close.

That one goes away by itself so it's sort of self-limiting, but yeah it can get pretty annoying if you dont manage to get it immediately (touching it hardstuns you???). I find trying to get inbetween the pulses helps.

**Comment by the-orange-cow** [comment]
> Of all the anomalies, I think the most unbearable one is the gravity anomaly. Seems like it always just stunlocks anyone who gets too close.

This.  There have been numerous times I have attempted go deal with them, and it's a crap shot on whether I can get the scan in(which can be difficult when there is so much junk covering the anomaly) or just get chain stunned.

**Comment by Time-Green** [comment]
@necromanceranne @the-orange-cow you guys got any suggestions to make them less annoying? I might as well

**Comment by the-orange-cow** [comment]
> @necromanceranne @the-orange-cow you guys got any suggestions to make them less annoying? I might as well

Possibly increasing the times between pulses slightly.

**Comment by necromanceranne** [comment]
I honestly think that and reducing the force of the throws. It doesn't _need_ to be as severe as it is. I think just trashing a room is annoying enough.

Also, that warbling affect around the anomaly? I think to this day it still intercepts clicks.

**Comment by Bibarra** [comment]
Shouldn't anomalies be punishing if you don't deal with them in a timely manner? What are the stats on anomalies getting defused versus left alone to detonate/cause trouble? The only anomaly that's difficult to deal with is the mentioned grav anomaly, and I personally like that you have a small chance to get killed by one. Bioscrambler and Material anomalies are the least frustrating to deal with. Just wait for the pulse, then go in and scan it. You can tell when a material anomaly is about to teleport by how much terrain it has converted.  I think anomalies, as they are now, allow for more avenues for interesting situations.

Would you be willing to at least make anomalies more punishing if they are allowed to pop? 20 more seconds is a good amount of time.

**Comment by MrMelbert** [comment]
The only one of these I don't like is the detonation visual warning. 
It being ambiguous makes it actually a threat, and also makes the act of defusing an anomaly rather tense - you're really counting your seconds as you run from science to the department.

**Comment by Time-Green** [comment]
> The only one of these I don't like is the detonation visual warning. It being ambiguous makes it actually a threat, and also makes the act of defusing an anomaly rather tense - you're really counting your seconds as you run from science to the department.

I think it can make for more exciting moments when you KNOW just how close you were, instead of just a "woops gone now". But also fair I guess

**Comment by Jackal-boop** [comment]
i think anomalies are fine as is. they give you about 70-90 seconds to get a neutralizer or a analyzer. which is enough time to trot across the station and ask the AI to open a door for you

**Comment by SargesC** [comment]
It doesnt help they are so common, like 3-5 every round and one of em is just a black hole that destroys an entire department and used to gib.

**Comment by QuiteLiterallyAnything** [comment]
> you guys got any suggestions to make them less annoying? I might as well

I'm not either of the people you @'d here, but might I suggest making it scannable by long-range analyzers and/or making magboots more effective against it?

Also, it doesn't seem like you've changed the announcement text for bioscramblers that implies they're 'immortal', and if you are to make them temporary like other anomalies then perhaps make them last a bit longer than the others? They were initially designed with being long-lasting in mind, after all.

**Comment by CRITAWAKETS** [comment]
Is making vortex anomalies on multi-z less annoying out of scope? Right now if a vortex anomaly spawns on the higher level of a multi-z map it's pretty much impossible to defuse it because the ground gives way and you don't just float over openspace.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Thought about it more and I don't really want the end-of-life animation 

If you want to keep the feeling of "wow that was close" we could maybe tweak the feedback message it gives you on defuse?  (`"The anomaly warbles and fades in an out of reality, and looks like it's about to explode, before compressing into a core and falling to the ground."`)

Or alternatively we could make the anomaly neutralizer flash red / beep if it detects an anomaly nearby that's about to explode (that way you still have a warning if using a neutralizer, but have to rely on prayer doing it ghetto)

**Comment by QuiteLiterallyAnything** [comment]
> Thought about it more and I don't really want the end-of-life animation
> 
> If you want to keep the feeling of "wow that was close" we could maybe tweak the feedback message it gives you on defuse? (`"The anomaly warbles and fades in an out of reality, and looks like it's about to explode, before compressing into a core and falling to the ground."`)
> 
> Or alternatively we could make the anomaly neutralizer flash red / beep if it detects an anomaly nearby that's about to explode (that way you still have a warning if using a neutralizer, but have to rely on prayer doing it ghetto)

The end-of-life animation looks pretty nice in my opinion. If you don't want it for functional reasons then (for the sake of aesthetic) why not just have it sped up significantly and played up at the last 2.5 or so seconds of the anomaly's life?

**Comment by MrMelbert** [comment]
> The end-of-life animation looks pretty nice in my opinion. If you don't want it for functional reasons then (for the sake of aesthetic) why not just have it sped up significantly and played at the last 2.5 or so seconds of the anomaly's life?

I mean, all the animation does is scale it up 3x, it's not particularly special

**Comment by QuiteLiterallyAnything** [comment]
> I mean, all the animation does is scale it up 3x, it's not particularly special
> 
> But also if you want to add an animation for neutralizing them / for the anomaly when it precisely expires / explodes feel free

Even if it's only a minor thing then that's still an improvement which makes the game just a bit better. Also, I'm probably not going to be directly contributing to /tg/station for a while myself— why not be resourceful and encourage the slight alteration of what you already have here? 

I understand your desire for quality control, but in the circumstance of open-source video game development that desire ought to be tempered with a staunch appreciation for volunteer efforts. I believe there is no better way to manifest such appreciation than by favoring the reappropriation of (relatively) bad ideas rather than the complete rejection of them.

**Comment by Absolucy** [comment]
suggestion: make the dimensional anomaly "burst" upon detonating, instantly transmuting a quite large area around it, like i did downstream, instead of just disappearing without a trace

```dm
/obj/effect/anomaly/dimensional/detonate()
	. = ..()
	if(!theme)
		return
	visible_message(span_bolddanger("[src] explodes, distorting the space around it in surreal ways!"))
	var/detonate_range = range + rand(5, 7)
	var/list/turf/target_turfs = spiral_range_turfs(detonate_range, src)
	for(var/turf/target in target_turfs)
		if(prob(15)) // the prob is so it looks more erratic
			continue
		theme.apply_theme(target)
```

**Review by MrMelbert — APPROVED** [review]

**Comment by Jacquerel** [comment]
> suggestion: make the dimensional anomaly "burst" upon detonating, instantly transmuting a quite large area around it, like i did downstream, instead of just disappearing without a trace
> 
> ```dm
> /obj/effect/anomaly/dimensional/detonate()
> 	. = ..()
> 	if(!theme)
> 		return
> 	visible_message(span_bolddanger("[src] explodes, distorting the space around it in surreal ways!"))
> 	var/detonate_range = range + rand(5, 7)
> 	var/list/turf/target_turfs = spiral_range_turfs(detonate_range, src)
> 	for(var/turf/target in target_turfs)
> 		if(prob(15)) // the prob is so it looks more erratic
> 			continue
> 		theme.apply_theme(target)
> ```

There's probably no reason to be using spiral_range_turfs in this code snippet as it seems like the list's order is not important

**Comment by Time-Green** [comment]
I’m not going to do any more additions in this PR

**Pull request merged**
