### PR TITLE
Cleanbot

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Removes the cleanbot bug work around

Also rebases the 511branch with current master. (but somehow fucks that up)

### CODE REVIEW

**Comment by Xhuis** [comment]
Oh my

**Comment by TechnoAlchemisto** [comment]
jesus christ

**Comment by optimumtact** [comment]
Can't merge a rebase back into itself, pushed via -f manually after reviewing diff

**Comment by optimumtact** [comment]
Also this got 23 commits behind in 24 hours!

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/compare/511branch?expand=1 to compare current diff, will likely drift very soon

**Pull request merged**
