### PR TITLE
Closets now initialize their contents on demand (more than 1.6 seconds of init time saved)

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Closets now initialize their contents once in `dump_contents()`. This saves more than 1.6 seconds of init time (all `/obj/structure/closet` now initialize in 84ms).

Not sure what assumptions this will break, there's a lot of closets, so separate PR.

:cl:
del: You can no longer see maint spawners before the round starts (but your rounds start faster now :) )
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Going to have a way to immediately initialize some contents, then make a unit test to make sure all steal objectives are available in closets immediately.

**Comment by Mothblocks** [comment]
Need to figure out what the deal with #59913 was

**Comment by Mothblocks** [comment]
Okay so that PR was prepping for two features that didn't really happen

**Comment by SuperSayu** [comment]
Thanks I hate it.

Ironically I was just porting code from old sayustation code to Orbstation which does extra roundstart randomization including pulling things out of closets, with some low probability, to create a slightly more organic lived in feel.  I was going to (probably will) offer it upstream since I did a lot of work to turn it from a one-file-wonder into a proper subsystem with configuration options.  Just running the code to parse the contents of things would require initializing the closets, so even though the randomization code takes a fraction of a second on its own it will undo almost all the savings you create here.

That said, aside from that specific niche problem that I went out of my way to create, I can't think of any other idea WHY this is stupid, even though I feel like it's stupid.

**Pull request merged**
