### PR TITLE
*Add a capacity upgrade for janitorial cyborg light replacers

### PR DESCRIPTION
**Pull request by lbnesquik**
## About The Pull Request
This is a researchable upgrade for janitorial cyborgs. It gives them slightly more than double the amount of lights, and it is researchable in the same suite of upgrades.

## Why It's Good For The Game
I often found myself wanting more lights, or wanting to fix small broken windows as a cyborg, and this PR adds a solution. 

## Changelog
:cl:
add: Add a capacity upgrade for janitorial cyborg light replacers
/:cl:

### CODE REVIEW

**Comment by OuroborusReporter** [comment]
Janitor borgs don't have screwdrivers - Are they just placing down unsecured windows?

**Comment by ZephyrTFA** [comment]
Janitor cyborgs should not be repairing windows. I am fine with an upgrade that lets you create light bulbs and tubes from energy and sets their custom materials to nil, but not actual glass from energy.

**Comment by lbnesquik** [comment]
> Janitor cyborgs should not be repairing windows. I am fine with an upgrade that lets you create light bulbs and tubes from energy and sets their custom materials to nil, but not actual glass from energy.

Well, I'm not sure how I'd do that. That was my preferred option, but unlike other stuff, lights aren't stacks of material, like for wires, tiles or so. I guess I could take another quick crack at it.

**Comment by Sealed101** [comment]
make an upgrade for the borg's light replacement tool that would either regenerate lights by itself with a moderate energy consumption increase or when it gets used when it's empty, for an energy cost of course

**Comment by Sadboysuss** [comment]
just make service borgs refill their lights from cyborg chargers if it doesn't do that already.

**Comment by lbnesquik** [comment]
I shifted this PR into an upgrade that simply adds a higher capacity replacer, kinda like how the advanced mops work.

**Comment by Ghommie** [comment]
Conflicts.

**Comment by lbnesquik** [comment]
> Conflicts.

Ough

**Pull request merged**
