### PR TITLE
Revert "Replaces Double Agents with Internal Affairs"

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I have not recieved much positive feedback and while people have good ideas on improving this concept I dont personally want to spend the time or energy doing so.

If nobody else opens a competing PR in the next few days I'd like this merged

### CODE REVIEW

**Comment by kevinz000** [comment]
>giving in to the murderboners

no stop.

**Comment by Armhulen** [comment]
every time i've been an IAA i hate it. You kill your target and you have only a couple options
sit around doing nothing until you get random searched and die
hide in a locker all shift for that sweet sweet greentext (shitty)
bait people into attacking you for them sweet sweet kills (super shitty)

**Comment by Robustin** [comment]
Not surprising, this community is not hard to predict. Some hybrid with both traitors and IAA's or incentivizing DA's not to murderbone with IC-mechanics would've worked.

DA isn't the worst though, since I nerfed it its literally traitor +2 but sometimes one or two traitors just focus on their objective so its a wash, the mode.

**Comment by PKPenguin321** [comment]
Maybe they'd work better as a side event to complement other modes.

**Comment by ExcessiveUseOfCobblestone** [comment]
Maybe DA just doesn't work with "antags get free reign" culture.

**Comment by Robustin** [comment]
DA's don't get sleepypen and start with 6TC, confirm your target's death with a PDA (which injects them with nanomagi... nanomachines that prevent cloning and collect an 8TC bounty.

"But Robustin m-m-muh fears of snowballing antags!"

Get over it. After I kill one other traitor in DA im typically holding 40TC in gear. For several months we let people important over 100,000TC from cargo. The fact is that TC doesn't grant immortality and it wouldn't hurt to limit its distribution so that people have an incentive to not murderbone the instant the round starts.

From an economics perspective is it even remotely surprising that when we give antags a full payout at roundstart that they play like they've got nothing to lose?

**Comment by lzimann** [comment]
So, is anyone doing anything on this?

**Comment by BeeSting12** [comment]
wait to merge this, 4dplanner's changes to the mode might make the mode fun

**Comment by PKPenguin321** [comment]
What BeeSting said

**Comment by ChangelingRain** [comment]
Yeah, those changes look interesting.

**Pull request closed without merging**
