### PR TITLE
Add a missing space in mechacode

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**

### CODE REVIEW

**Comment by Wilchenx** [comment]
deranged

**Comment by ExcessiveUseOfCobblestone** [comment]
Can someone tell him to quit this stuff?

He's progressed from having poor titles to intentionally misleading ones.

**Comment by praisenarsie** [comment]
\>telling a troll to quit

**Review by SpaceManiac — APPROVED** [review]
The fact that the old code confuses github's parser is enough to accept the change but please with the title

**Pull request merged**
