### PR TITLE
You can now hear the tesla from 4 screens away.

### PR DESCRIPTION
**Pull request by Iamgoofball**
If you still don't have warning that the tesla is loose after this, consider investing in speakers or a headset.

### CODE REVIEW

**Comment by Lumipharon** [comment]
Can you tell how far away it is?

**Comment by KazeEspada** [comment]
Can you hear a contained one from atmos?

**Comment by WJohn** [comment]
Maybe fix the core issue of teslas teleporting on top of you from a screen away and also killing you instantly from much further than that.

**Comment by Iamgoofball** [comment]
@KazeEspada No, because space nulls out all sounds, and there's no atmosphere in the containment, effectively making it space. You'll hear it as soon as the ball lands on a tile that has air, though, and you'll hear it super far.

@Lumipharon There's still audio fall off, so  you can judge how far it is by how loud it is.

@WJohn Bug MSO.

**Pull request merged**
