### PR TITLE
Ghosts and cameras can no longer randomly buzz the mulebot

### LINKED ISSUE #45594: Ghosts can make mulebots buzz
## Testmerges:
#45457 
#44639 
#45485 

## Reproduction:
Ghosts can make mulebots buzz by dragging their own sprite onto the mulebot.

image

### PR DESCRIPTION
**Pull request by tralezab**
fixes #45594

### CODE REVIEW

**Comment by Fikou** [comment]
bad pr

**Comment by redmoogle** [comment]
just have the buzz be on a timer for ghosts like they can only buzz it once a minute

**Comment by ike709** [comment]
Don't remove fun, just prevent it from being spammed.

**Comment by tralezab** [comment]
how about instead i make the chaplain a holy mulebot that only carries ghosts

**Pull request merged**
