### PR TITLE
Reverts removing wrappers

### PR DESCRIPTION
**Pull request by Bawhoppen**
come the fuck on stop meme-merging shit

### CODE REVIEW

**Comment by Shapsy** [comment]
ayy lmao

**Comment by PKPenguin321** [comment]
L M A O

**Comment by GunHog** [comment]
@Bawhoppen You should really try to save your influence to fight changes you truly and deeply oppose. Making PRs to revert something so insignificant makes you seem whiny and petty. It will hurt you when someone makes a really awful change in your mind. Your opinion will be brushed aside as the typical white noise expected from you.

TL;DR: Pick your battles.

**Comment by Aloraydrel** [comment]
Is this a meme pr

**Comment by PKPenguin321** [comment]
>Making PRs to revert something so insignificant makes you seem whiny and petty.

\>seem whiny and petty
\>implying baw isn't actually whiny and petty
:^)

**Comment by coiax** [comment]
Is this important? You can't even make wrapped monkey cubes. I feel like I'm missing some sort of important meme here.

**Comment by PKPenguin321** [comment]
No, see, without wrappers on pocket sized hyper realistic live monkeys that are dehydrated and compressed into cubes, RP can't exist. Right guys???????

**Comment by AdamElTablawy** [comment]
i for one support this change because i enjoyed wasting 0.01 seconds clicking on a monkey cube to unwrap it and plan to leave /tg/ forever now that i can't do it

oh wait

no i don't

because that's fucking retarded

**Comment by Man-Shroom-** [comment]
this is me commenting on this pr

smash that party popper!!!!

**Comment by Cheridan** [comment]
:put_litter_in_its_place:

**Comment by Bawhoppen** [comment]
I am serious about this
I don't care about the monkey cubes but i do legitimately care about the chocolate bars
reopen

**Pull request closed without merging**
