### PR TITLE
Host owns the config

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Oh boy

**Comment by Qustinnus** [comment]
do you even have write perms still?

**Comment by LemonInTheDark** [comment]
Do you get pings/review requests? I touched air.dm, which we co-own, in this pr #52493, but it doesn't seem to have pinged you

**Comment by optimumtact** [comment]
they're in the org so they should

**Comment by LemonInTheDark** [comment]
Floyd is in the org, but when he owned mat code or whatever it was he never got notified. Least from what I've heard

**Comment by optimumtact** [comment]
I guess you need write, so this PR is kind of pointless

**Comment by MrStonedOne** [comment]
No point deciding on this until the checks finish.

**Comment by Tharcoonvagh** [comment]
HES ASSUMING CONTROL

**Comment by Tharcoonvagh** [comment]
Well I mean hes the host so not like he needs it but whatevs

**Comment by cacogen** [comment]
He works in mysterious ways

**Pull request merged**
