### PR TITLE
Removes the virus symptoms of vitiligo and revitiligo.

### PR DESCRIPTION
**Pull request by harmonyn**
## About The Pull Request

Removes vitiligo and revitiligo as virus symptoms.

## Why It's Good For The Game

- These symptoms have no use to legit virologists and very little use to antagonists, their primary purpose is to griff, and not even the kind of griff that results in interesting "minor IC crime."
- Their other primary purpose is to set off a chain reaction of 3edgy racist memes that derail the round into permanent obnoxiousness.
- Even if someone actually does want to use it as a real symptom, the introduction of several new nonhuman species since 2015 (when these symptoms were added) makes it even more useless.
- Balance-wise, we are four years past 2015 and thus it seems as if we have enough symptoms at the same level that this should not overly affect virology balance.
- The creator himself said it was a "joke symptom I threw in as an afterthought": https://github.com/tgstation/tgstation/pull/7197

## Changelog
:cl: bandit
del: Nanotrasen has permanently cured some virus symptoms.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Oh my fucking god I already feel a shitstorm brewing.

**Comment by HomocidlePancakes** [comment]
People will just screech at you something along the lines of “can’t handle edgy humor lol” and “snowflake” and then a couple of people who have mastered efficiency of viro will post long threads proving you wrong

**Comment by Dawson1917** [comment]
Vitiligo and revitiligo are both very good buffing symptoms. Edgelords who use the viro slot just to make le coughing and black man virus should be messaged by admins for wasting a job slot.
I use neutered vitiligo to buff stealth (+2!!) and stage speed (+3). Revitiligo buffs resistance and transmission but is fairly weak in comparison to vitiligo.

If you want to remove buffing symptoms you should replace them with something of equal use. Don't make virology more shit than it already is.

**Comment by Ty-the-Smonk** [comment]
oh boy oh boy viro losing ways to buff their viruses

**Comment by Narcissisko** [comment]
The edgy part of this isn't that someone made you black. The edgy part of this is that the person who's actually getting it erased never plays as a black person and doesn't like being black.

**Comment by 81Denton** [comment]
>Their other primary purpose is to set off a chain reaction of 3edgy racist memes that derail the round into permanent obnoxiousness.

To me that sounds more like an IC/player base issue than something that needs to be addressed by removing code.
After all, we also have other inconveniencing, but harmless cosmetic symptoms like hair loss.

**Comment by Dawson1917** [comment]
> 
> 
> The edgy part of this isn't that someone made you black. The edgy part of this is that the person who's actually getting it erased never plays as a black person and doesn't like being black. You should add a word censor while you're at it that autobans people from saying ligger.

Don't beat around the bush. Everyone knows how obnoxious viros putting out a disease that just makes you black is, because everyone has seen it happen hundreds of times and is just a shit meme of "lol black people!!". This PR is just the wrong way to fix the problem because it nerfs good virologists.

**Comment by Angustmeta** [comment]
I have vitiligo in 29 viruses and revitiligo in 4. Most of them neutered.

**Comment by Narcissisko** [comment]
Well Mr Dawson, vitiligo is also a real disease that really does what the disease says it does in the game. It's not hurting anybody to be black either. I went to a military weapons forum and started talking about calomel and everybody got offended by the fact I even mentioned it.

81Denton said it best

**Comment by Fikou** [comment]
DUHHH
CIRNGE
DUHH
BRINGE

**Comment by Ty-the-Smonk** [comment]
I play a black character to black viruses dont effect me

**Comment by ATH1909** [comment]
This is definitely a virology nerf, as these symptoms are currently being used for stat buffing in many viruses (vitligo more than revitiligo, but still). If you're triggered that much, just take away their skin-altering effects, rename them to something boring, and leave them in the game as stat buffing-only symptoms (like viral evolutionary acceleration).

**Comment by 81Denton** [comment]
To add to that, if the amount of racism ingame is an issue I feel that the more efficient approach would be to change and enforce the server rules. 
Removing a skin color changing virus symptom is a bandaid at best.

**Comment by Ty-the-Smonk** [comment]
Id argue Hair loss is worse than skin color, just due to it making most people look the same

**Comment by wesoda25** [comment]
lol what are you saying viruses that lighten/darken a persons skin color are racist?? 

at the end of the day its just a goofy virus symptom with decent practical use. Would quite literally be a nerf to virology.

**Comment by Dawson1917** [comment]
@bgobandit if you replace the vitiligo and revitiligo with two other nonsense fluff symptoms that have identical stats I guarantee nobody will have a real argument against it. The stats themselves are important for virus buffing; the skin colour effect of the symptoms has no purpose outside of making race comments

**Comment by Ty-the-Smonk** [comment]
> @bgobandit if you replace vitiligo and revitiligo with two other nonsense fluff symptoms that have identical stats I guarantee nobody will have a real argument against it. The stats themselves are important for virus buffing; the skin colour effect of the symptoms has no purpose outside of making race comments

Honestly rev or vit combined with hairloss makes people kinda indistinguishable from each other but it will only really be used for race memes so yea

**Comment by Krysonism** [comment]
Jokes about race are a stable of comedy around the globe.

**Comment by Shadowflame909** [comment]
Michael Jackson had Vitiligo

Uncle Ruckus had Revitiligo.

Do you think that these folks should not be represented in this great space game? Bgobandit?

Also, it nerfs virology.

**Comment by Detective-Google** [comment]
I unironically use Vitiligo (neutered of course I'm not a shitter) in a lot of diseases, so I feel like outright removing it is a bad play, I would certainly agree that addressing server policy on racism/banning people who release dumb griff viruses is a better solution.

**Comment by optimumtact** [comment]
Yeahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

maybe come up with some replacements first

**Comment by PKPenguin321** [comment]
Simpsonitis that makes you yellow

**Comment by bgobandit** [comment]
I have no issue with replacing them with nonsense fluff symptoms and am happy to brainstorm on what those might be. 

Re: banning people -- as an admin, this is guaranteed to cause a massive shitstorm, and also, the thing is the chain reaction that turns the whole round into shit. A code solution is more feasible.

**Comment by PKPenguin321** [comment]
Instead of vitiligo making you brown skinned it literally makes you black skinned, as in pitch black darkness
Instead of revitiligo making you pink skinned it literally makes you white skinned, like blank sheet of paper fresh-snow-in-Antarctica white

**Comment by Michael-Ashfield** [comment]
I understand alot of players use it as a meme, but it has legitmate uses as an antag, which is re/vitiligo + hairchange + voice change. This virus makes it difficult to tell who is who and allows easy disguise and infiltration, as all you need is your agent ID to claim you are anybody, it also makes things difficult for the AI and security.
Perhaps make one of them a fluff virus and the other turns people a funky colour such as spraytan OD yellow, or a non human color (Space vitiligo?), this means the disguise trick still works, the stats remain same for all virologists and the racism meme virus cant be done.

**Comment by factoryman942** [comment]
what about a symptom that randomly adds colourful reagent to you?

**Comment by nemvar** [comment]
Yeah, outright removal is a tad harsh, they do have a place as buff symptoms in a lot of viruses.

**Comment by ExcessiveUseOfCobblestone** [comment]
Vitiligo is the 4th best symptom in terms of overall stats, tied with 2 others (assuming all stats are equal).

**Comment by tralezab** [comment]
which it should definitely not be for a symptom that only effects one species

**Comment by Ty-the-Smonk** [comment]
Idea just add a symptom that makes people change into lizards

**Comment by bgobandit** [comment]
How about this: Replaces these symptoms with the following two symptoms:
- Gives episodes of face-blindness (essentially the same thing as the quirk, people appear as Unknown, but episodic, and curable) 
- Randomly adds colorful reagent to you

Same buffing ability/strength/etc, the same general effect of making it harder to tell people apart.

**Comment by Dawson1917** [comment]
> 
> 
> How about this: Replaces these symptoms with the following two symptoms:
> 
>     * Gives episodes of face-blindness (essentially the same thing as the quirk, people appear as Unknown, but episodic, and curable)
> 
>     * Randomly adds colorful reagent to you
> 
> 
> Same buffing ability/strength/etc, the same general effect of making it harder to tell people apart.

These sound really good. The first one has use if you leave it unneutered, and the second has comedic effect that isn't just griff. #2 should swap colours more quickly on stage speed 5

**Comment by YakumoChen** [comment]
I can't believe this PR literally uses "It's [current year]" as an argument.

The main problem of the virus was that curing it didn't change your skin color back. Maybe make it actually do that?

**Comment by Detective-Google** [comment]
The problem is people used it to Griff for haha funny racism, and it was a grey area for admins, but, that being said, the symptom has really good stats regardless of Griff potential, I think the proposed replacements do a good job of carrying the stat bonus whilst still being fairly inconsequential.

**Comment by ExcessiveUseOfCobblestone** [comment]
> which it should definitely not be for a symptom that only effects one species

even when neutered?

It's almost mandated for stealth disease IIRC.

**Comment by kriskog** [comment]
If the symptoms are replaced with something of equal stats, I dont particularly care if we remove the unoriginal "make everyone black" virus. We still got the beard/hairloss flip flop viruses though, makes all the catgirls and anime hair players run you down in moments.

**Comment by Shadowflame909** [comment]
Uncle Ruckus really didn't have Revitiligo.

He just had a shit father.

**Comment by SkeletalElite** [comment]
If you don't like the harr harr everyone black joke, just make it so the skin color changing goes away after the virus is cured.

**Comment by 81Denton** [comment]
I don't see any value in keeping this PR open; this is at best a bandaid fix for inappropriate player behavior. Regardless, I'd suggest reverting the skin tone change when the virus is cured, or only making the skin tone change permanent once a certain stat threshold is reached.

Personally, I'd also be fine with a replacement symptom that (for example) randomly changes the skin tone or applies crayon coloring/colorful reagent.

**Comment by bgobandit** [comment]
https://github.com/tgstation/tgstation/pull/45297

**Pull request closed without merging**
