### PR TITLE
You can get haunted eightballs in the surplus crate

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: You can find haunted eightballs in the surplus crate.
/:cl:

Didn't realise that job specific items were surplus 0 by default.

### CODE REVIEW

**Comment by kevinz000** [comment]
What use is this item again for traitors?

**Comment by coiax** [comment]
Is my target nearby? Is my target dead? Does security know about me? Should I call the shuttle? Are the spacegods meming? Are there changelings on the station?

**Comment by KorPhaeron** [comment]
I think job specific items should stay specific, especially if they're going to be vaguely supernatural like this

**Comment by coiax** [comment]
*cough* his grace *cough*

**Comment by KorPhaeron** [comment]
If thats in surplus then it shouldnt be

**Comment by coiax** [comment]
It's a low surplus chance, but it's still there.

**Comment by PKPenguin321** [comment]
I agree with kor

**Comment by coiax** [comment]
@KorPhaeron but the surplus crate is literally "stuff we found at the back of the warehouse". His Grace has a low chance, so it's not going to be in every crate, but it'll turn up occasionally.

**Comment by KorPhaeron** [comment]
You caught me in one of my "I hate magic" moodswings sorry

**Pull request closed without merging**
