### PR TITLE
The unbonening (Removes BIO_JOINTED and BIO_BONE from snail and slime bodyparts)

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title.

The consequences: 

Slimes can no longer receive dislocations. This is a minor buff.
Snails can no longer receive blunt wounds, period. A blessing and a curse - while you cant break your arm, theres no bone to prevent swords from slashing through, meaning you are very easy to dismember. 2 hits from an esword can dismember an arm.
## Why It's Good For The Game

1. Snails are invertebrates, and it doesn't really make much sense why they have bones. 
2. I dont even know why I gave slimes joints. Theyre literally slime, arguabl teven MORE invertebrate than a snail.
## Changelog
:cl:
balance: Snails no longer receive blunt wounds, meaning sharp weapons can dismember them more easily
balance: Slimes can no longer receive dislocations
/:cl:

### CODE REVIEW

**Comment by Overuseddart** [comment]
Firstly your change log doesn’t even include the nerf. Secondly why nerf snails? They are wiz nerd only. 
(Can you make it so slimes can reattach their limbs? It’d be very helpful cause it takes a lot of slime to regenerate your limbs)

**Comment by nikothedude** [comment]
> Firstly your change log doesn’t even include the nerf. Secondly why nerf snails? They are wiz nerd only.

You think this is a nerf? This makes them inelihible for blunt wounds which can really debilitate. Its more of a rebalance.

**Comment by nikothedude** [comment]
Also, snails can be caused by magic mirrors, maintpills, or genetics

**Comment by Time-Green** [comment]
> Also, snails can be caused by magic mirrors, maintpills, or genetics

You almost gave me a heart attack, but no maintpills dont make snails

**Comment by Admiral-Gigaton** [comment]
*ahem*

boneless snail

boneless bone

boneless pizza

**Pull request merged**
