### PR TITLE
Makes the chemistry diamond NFPA compliant

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Here's the chart.
image

Why does ours have a number at the bottom? Who knows.
image

That's better.
image

## Why It's Good For The Game

Reinstates my immersion.

## Changelog
:cl:
fix: The chemistry diamond is now NFPA compliant
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
@EOBGames Chemist person, please tell me this PR is correct.

**Comment by Iamgoofball** [comment]
this PR is definitely correct

**Comment by GunHog** [comment]
Why are the numbers only 1? That department is basically a chemical plant where you can make explosives, highly flammable fuels, and deadly poisons!

**Comment by cacogen** [comment]
the numbers should be 5s

it needs a symbol

**Comment by tf-4** [comment]
It doesn't need a symbol, actually.
image

**Comment by tf-4** [comment]
Also, NT doesn't exactly hold safety to a high standard. So it's amusing (in a very fucking dry way) to have them super low

**Comment by optimumtact** [comment]
we should have https://file.house/fsHo.png because our community is corrosive to your sanity

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
