### PR TITLE
Hell's Broke Loose in Georgia

### LINKED ISSUE #50603: the grammar of this invocation text physically hurts me
https://cdn.discordapp.com/attachments/326831214667235328/702262048985317426/unknown.png

Having an "ain't" is fine, but it still needs an apostrophe, and either the rest of the sentence needs to be rephrased/restructured, or that "ain't have" needs to be replaced with a "haven't had".

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Closes #50603.

## Why It's Good For The Game
Less people being physically hurt by text seems good to me, no?

## Changelog
:cl: Inept
fix: "Devil, just come on back now if you ever want to try again, I told you once, you son of a bitch, I'm the best there's ever been."
/:cl:

### CODE REVIEW

**Review by Rohesie — APPROVED** [review]

**Comment by Qustinnus** [comment]
i'm almost at the point of closing Ath issues that are one word change requests that he could've changed with the time he took to write the issue itself.

**Comment by EOBGames** [comment]
well the good news is that you don't need to close that one

**Comment by HomocidlePancakes** [comment]
Can someone explain the reference to me?

**Comment by EOBGames** [comment]
The Devil went down to Georgia
He was looking for a soul to steal
He was in a bind
'Cause he was way behind
And he was willing to make a deal

**Comment by SumFaggotPlayTester** [comment]
Bubba get my golden fiddle.

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
