### PR TITLE
Parasite HUD and rebalancing

### LINKED ISSUE #12344: Guardian users retain their guardian verbs even if their Guardian dies
If they get revived after Guardian death they will still have a communication verb.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Remake of #12457 because I was getting git runtime errors trying to resolve the merge conflict

Dying with a parasite now turns you to dust.

Fixes #12344

The Chaos parasite now only ignites you if you are not already on fire, meaning it wont rapidly stack fire on you until its impossible to put out. It now has a slightly higher chance to teleport you on hit though.

The ranged parasites projectiles now bypass armour.

The Explosive types traps now are on a 20 second cooldown

The messages for the user taking damage from the transfer are now bolded, so they should be a bit easier to see in combat.

Adds the ability to toggle lights on/off (glowing).

Adds HUD buttons for manifest, recall, communicate, toggle, and toggle lights.

### CODE REVIEW

**Comment by Supermichael777** [comment]
body destruction seems a bit much.

**Comment by KorPhaeron** [comment]
@Supermichael777 

Don't buy one then

**Comment by Supermichael777** [comment]
im just saying none of their other gear has a massive downside external to its primary use(bombs can blow you up but they don't gib you when defused)

**Comment by KorPhaeron** [comment]
People have been complaining they're too good, so it's either

A) Raise the cost, which would limit traitor flexibility/creativity/the ability to fight alongside the stand if his gear is restricted

B)Nerf them and add a major drawback

I'd rather go with B

**Comment by KorPhaeron** [comment]
@razharas @remierichards @Jordie0608

Please review soon, its been 16 days and the firestack thing continues to be ridiculous and badly needs the nerf.

Other stuff is far less urgent but actual HUD buttons would be nice.

**Comment by RemieRichards** [comment]
Shouldn't have taken this long, this is fine.

**Comment by KorPhaeron** [comment]
Thanka

**Pull request merged**
