### PR TITLE
[s] [wip] [dnm] Abuses @tgstation-server.

### PR DESCRIPTION
**Pull request by JJRcop**
:cl:
soundadd: sounds like a good change
balance: restores balance to the force
refactor: when you factor in the fun
code: part of this is code
add: adds much needed happiness
typo: here is a god topy foe yuo
del: nothing is wrong here
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I don't know why people bother making shitposting PRs

**Comment by Armhulen** [comment]
agreed

**Comment by JJRcop** [comment]
You can do them when it's late so they stick around for a few hours, instead of the middle of the day, like I did.

**Comment by YakumoChen** [comment]
but they accomplish nothing but wasting the maintainers' time.

**Comment by JJRcop** [comment]
they accomplish entertainment!

**Pull request closed without merging**
