### PR TITLE
pAIs are now an essential part of any autism fort

### PR DESCRIPTION
**Pull request by ghost**
:cl: Reeeeimstupid
tweak: pAIs now quicker, making them an essential part of autism forts
/:cl:

REEEE

### CODE REVIEW

**Comment by chanoc1** [comment]
quicker what

**Comment by kevinz000** [comment]
Dude, stop.

**Comment by KorPhaeron** [comment]
@kevinz000 

Too late, I'm removing you from the admin team your personality cult on basil is out of control

**Comment by kevinz000** [comment]
:(

**Pull request closed without merging**
