### PR TITLE
ponies dont take damage from standing on glass

### PR DESCRIPTION
**Pull request by Supermichael777**
and its annoying

### CODE REVIEW

**Comment by Eaglendia** [comment]
Can you not make a balance pr for April Fools ponyshit

**Comment by Supermichael777** [comment]
can you not exist?

**Comment by Dorsisdwarf** [comment]
April fools will be over before this can be merged

**Comment by Supermichael777** [comment]
quickmergeasap

**Comment by Cheridan** [comment]
ponies are going on master after april fools, @Shadowlight213 said so don't bother him about it

**Comment by Supermichael777** [comment]
this is a fix to a bug ponies have hooves so glass woulden't hurt them!

**Comment by Supermichael777** [comment]
aparently the flag got changed to be non granular

**Comment by optimumtact** [comment]
![so angry]http://puu.sh/o2TwX/9d5bc469ab.png)

Much rage, many butthurt

**Pull request merged**
