### PR TITLE
Ports CEV closet icons

### PR DESCRIPTION
**Pull request by nicbn**
Oracle alternative:  #56351

## About The Pull Request

Ports CEV closet icons, with some adaptation (initials on command lockers and color of security locker).

Slowly make TG more visual appealing, you know.

## Why It's Good For The Game

image

image

image

image

image

## Changelog
:cl:
imageadd: Ported CEV locker icons
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Not sure if I like the look of these lockers, to be honest. It clashes a bit with the visual style of everything else around them.

**Comment by Qustinnus** [comment]
this clashes really hard and look bad even with CEV Eris' style imo

**Comment by nicbn** [comment]
The fault on the clash kind of lies on the other sprites to be honest, the previous closet sprites were quite bad. We could try to converge into a more CEV like art style for TG, but we have to start somewhere, and while we aren't finished of course there'll be clashes.

**Comment by Qustinnus** [comment]
these sprites are not good even if the art style fit IMO so basing our art-style on one port of cev eris sprites seems like a horrendous idea. If anything our art-style should be based on the new 3/4th walls we're getting.

**Comment by spessbro** [comment]
i love it speedmerge :metal:

**Comment by Sparkezel** [comment]
Security locker looks like syndicate

**Comment by SkeletalElite** [comment]
They look too shiny IMO

**Comment by Coastfront** [comment]
Bad.

**Comment by Kurgis** [comment]
> Security locker looks like syndicate

Likely due to it being the Syndicate locker, on Eris the Security lockers are all light and navy blue.

**Comment by maxymax13** [comment]
if i wanted to play a server whose art style is half pasted eris assets i'd play ss14

**Comment by cacogen** [comment]
It's a no from me

**Comment by MrDoomBringer** [comment]
they don't look great

**Comment by Twaticus** [comment]
im not interested in these sorry

**Pull request closed without merging**
