### PR TITLE
(Hopefully!) Final clockwork marauder balancing pass

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
balance: Clockwork marauders are now on harm intent.
balance: The Clockwork Marauder scripture now takes five seconds longer to invoke per marauder summoned in the last 20 seconds, capping at 30 extra seconds.
balance: Clockwork marauders no longer gain a health bonus when war is declared.
/:cl:

I say "final" because if they still cause trouble after this patch, I will likely end up removing them!

Marauder spam with no counter is boring for everyone but the marauders, and with this change it becomes very crippled if it's relied upon too much. Coupled with shield health, focusing down marauders is now an effective counter to spam, as the person creating them will by the end have to wait half a minute between each marauder, which is extremely slow!

In order to make them more in-line with other constructs and less painful to fight, they now collide with mobs ala harm intent instead of passing through them. **This currently has no effect until #32442 is merged, and if that isn't then I will make marauders non-flying to compensate!**

Finally, they no longer gain a health bonus when war is declared, which made them even more durable then they already are.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
I think the concept of "stands but they give host passive regen and don't kill the host if they lose" is more of the problem, not the time it takes to summon them which has 0 effect on their gameplay.

**Comment by Xhuis** [comment]
That implementation has been gone since the rework was merged.

**Comment by ExcessiveUseOfCobblestone** [comment]
perhaps having them act as stands in the fact they drain health of both would be a better approach then.

**Comment by Xhuis** [comment]
Their stand approach is completely gone, and has been for a long time. The role that summon time plays is that people can easily spam them as they die since it only takes five seconds to summon; if the crew can dispatch those marauders as they come, the flood will very quickly become a trickle as time ramps.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
