### PR TITLE
Redpills wirecutters

### PR DESCRIPTION
**Pull request by pudl**
Okayed by Wjohnston

### CODE REVIEW

**Comment by KorPhaeron** [comment]
reeee change

**Comment by RemieRichards** [comment]
Prefer the old(current) sprite.

**Comment by pudl** [comment]
Old sprite doesnt look like wirecutters

**Comment by Yiu113** [comment]
Some day someone's going to go to click the new ones and miss and it'll get them killed.

You'll have their blood on your hands.

**Comment by bgobandit** [comment]
this kills tactical wirecutters

**Comment by pudl** [comment]
Lol if that happens

**Comment by RemieRichards** [comment]
@Yiu113 only if it's on the floor, if it's in their inventory then the inventory slots will count as clicking it.

**Comment by ChangelingRain** [comment]
I don't like these they don't match the inhand sprite well

**Comment by pudl** [comment]
They match perfectly i dont know what youre talking about

**Comment by ChangelingRain** [comment]
Nooooo they don't I know this because I made the sprites for those and these don't match them!
They've got the same shading as the old sprites so you'd better update those inhands!

**Comment by pudl** [comment]
I dont know what youre talking about

**Comment by RemieRichards** [comment]
>object with shades of dark grey against a black background.

Cmon now.

**Comment by pudl** [comment]
It was like that in byond

**Comment by ike709** [comment]
m-muh tg culture :-1:

**Comment by Bawhoppen** [comment]
cancerous meme :-1:x:100:

**Comment by pudl** [comment]
Im going to sneak this into another pr

**Comment by Bawhoppen** [comment]
its not sneaking if you tell everyone

**Comment by PKPenguin321** [comment]
@KorPhaeron i am certain this does not agree with your design philosophy please close it

**Comment by pudl** [comment]
This pr will not be closed, its incredibly important canon fixing

**Comment by Cheridan** [comment]
i think it's really funny that nobody wanted our wire strippers to be named wire strippers in #17872
but nobody wants wire cutters to look like wire cutters either

you guys are crazy
you're right about this pr at least though, the old sprite is awful

**Comment by PKPenguin321** [comment]
we just want magic space cutters

**Comment by Dorsisdwarf** [comment]
Suggestion: change desc from "this cuts wires" to "this highly advanced futuristic tool is capable of both cutting and stripping wires. Crew are not trained in the latter."

**Comment by nachomeep** [comment]
i like this new sprite tho

**Comment by Poojawa** [comment]
> Im going to sneak this into another pr

The secret is out, he works for the US Congress.

**Comment by MrPerson** [comment]
The sprite on the right is the new one, right?

**Comment by Bawhoppen** [comment]
think so

**Comment by pudl** [comment]
@nachomeep If you like it then leave a dope thumbs up so im not universally disliked

**Comment by pudl** [comment]
Alright 4 people like this pr, that means 21% of all people like this pr. Please merge

**Comment by Bawhoppen** [comment]
3 people so sorry no merge

**Comment by pudl** [comment]
3 thumbs up and 1 person who commented that he liked it

**Comment by ChangelingRain** [comment]
I think this being closed has a self-evident reason.

**Pull request closed without merging**
