### PR TITLE
Allows you to var edit emitter projectiles

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Requested by @Ausops

### CODE REVIEW

**Comment by Thunder12345** [comment]
Emitters as mounted machine guns when

**Comment by Dorsisdwarf** [comment]
Can you make the rate of fire customisable as well?

**Comment by KorPhaeron** [comment]
Goofs upgrade system does that I think

**Comment by Thunder12345** [comment]
There's already vars for that, I think

**Comment by Robustin** [comment]
So I can finally build reflector obstacle courses in the central hall without getting BWOINKED for security getting emitter'd. 

#Itookacrewvote
#Helpingcrewgetrobust

**Comment by Iamgoofball** [comment]
@Dorsisdwarf Yeah, play with the settings adjusted by the upgrades, or use the admin var for upgrading the components.

**Comment by Jordie0608** [comment]
I'm pretty sure that, like guns, this'll only let you modify vars of the 'loaded' beam and'll be reset after that fires. Better than nothing, but worth noting.

**Comment by KorPhaeron** [comment]
@Jordie0608

Guns use some completely crazy system that loads each shell ino the chamber and then fires the projectile out of the shell. It resets because the casings arent edited so the projectiles they create arent.

Emitter just magics stuff into existence.

**Comment by Jordie0608** [comment]
Cursory look at the code suggests the same should happen regardless, emitters are still creating a new projectile each time. Haven't compared to the horror of guncode so obviously just guesswork; if it does work then that's some cool magic I guess.

**Comment by Fox-McCloud** [comment]
Oddly enough, energy weapons DID spawn their projectiles magically into existence at one point, until they got overhauled and unified.

To be honest, it's less complicated than the current system, which is basically coded to simulated how a real gun works.

**Pull request merged**
