### PR TITLE
Makes Hacked Laws Font Color Actually Readable

### PR DESCRIPTION
**Pull request by 13spacemen**
Altered the font color for hacked laws, (like the ones given by the hacked AI module) to be more readable especially on dark backgrounds

BEFORE
ailawbefore
AFTER
ailawsafter3
~~AFTER~~ OUTDATED
ailawsafter2

:cl:
qol: Changed the AI/borg hacked laws font color to be more readable
/:cl:

### CODE REVIEW

**Comment by nianjiilical** [comment]
maybe its just me but i actually find the before pic easier to read?

**Comment by Jacquerel** [comment]
Honestly as someone who is colourblind this is _better_ but still a little hard on the eyes. I know it's less of an "evil" colour but would a teal be possible or is that already used by ion laws?  
Alternately like, a much more pink red.

**Comment by timothymtorres** [comment]
Much better color choice than what was there previously.

**Comment by 13spacemen** [comment]
@Jacquerel I'll make it the same color as the zeroth laws then I guess, IIRC you can't even have both zeroth (emagged) and hacked laws at the same time as a borg since you can't upload to emagged borgs

**Pull request merged**
