### PR TITLE
Prevents harassing ghosts by spamming their brain in and out of an MMI a hundred times

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
fix: You can no longer harass ghosts by spamming with an MMI!
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Good tweak. Good tweak.

**Comment by KorPhaeron** [comment]
This looks pretty convoluted when you could just use world.time

**Comment by kingofkosmos** [comment]
This makes you able to spam the cooldown-text, should we avoid that?

Either way the cooldown could be done with just 3 lines or so:
https://github.com/tgstation/tgstation/blob/626302c1bf4bb2a37aa6508145751f6c4c78696d/code/game/gamemodes/miniantags/abduction/machinery/experiment.dm#L45-L47

**Comment by KorPhaeron** [comment]
stale

**Pull request closed without merging**
