### PR TITLE
supermatter delamination now spawns anomalies across the station

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
When a supermatter delaminates there will a blanket spawn of anomalies all across the station. 
The anomaly spawn will be determined by the power of the SM plus a good dose of randomness.
Half of the anomalies will spawn instantly, the other half will spawn overtime with a 5 to 10 second delay, some of those will have an extended delay from 5 to 15 minutes so be aware!
The spawned anomalies have longer lifespan than the regular ones that the SM spawns while dying or with high enough eer and might be more dangerous

## Why It's Good For The Game
Makes the engine failure more than just a hole in your department and will have lasting repercussions on the round

## Changelog

:cl:
expansion: supermatter delamination now spawns anomalies across the station, both instantly and overtime
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Won't this impinge on station engineer's extremely dangerous but amusing project to deliberately minimum-blast delam the supermatter to turn it into a tesla engine?

**Comment by GuillaumePrata** [comment]
> Won't this impinge on station engineer's extremely dangerous but amusing project to deliberately minimum-blast delam the supermatter to turn it into a tesla engine?

WTF I love this PR now

**Comment by Ghilker** [comment]
> Won't this impinge on station engineer's extremely dangerous but amusing project to deliberately minimum-blast delam the supermatter to turn it into a tesla engine?

changed for it to not trigger on tesla delaminations

**Comment by drIcepop** [comment]
Based Ghilker?

**Comment by Watermelon914** [comment]
Can you only make this apply for the station supermatter?

I don't think this should be causing supermatter shards to create anomalies on their delamination since they're not as significant at the station supermatter.

**Comment by Ghilker** [comment]
> Can you only make this apply for the station supermatter?
> 
> I don't think this should be causing supermatter shards to create anomalies on their delamination since they're not as significant at the station supermatter.

aight, will do it

**Comment by thgvr** [comment]
Maybe less dangerous anomalies should be common, spamming the station with flux anomalies because a new engineer made a mistake with one pipe sounds like a great way for people to want a shuttle even more after a delam

**Comment by Jolly-66** [comment]
Maybe have it scale with the delam percentage
The faster it drops, the more anomalies will spawn

I don't think a small hiccup or a "self contained" blast should vomit anomalies all over the station, but having it proportionate to the danger would be more interesting

**Comment by Timberpoes** [comment]
Sure. What's the worst that will happen?

**Comment by carshalash** [comment]
> Sure. What's the worst that will happen?

about that...

**Comment by mc-oofert** [comment]
Ends up making supermatter delamination an instant-shuttle-call matter because the station always blows up from the anomalies

**Comment by Redrover1760** [comment]
SM was already mandatory shuttle call, since alternative methods of power production was nerfed to the ground with turbine being exploded from SM, pacmans now totally garbage, and solars not being sufficient at all.

Then you add on anomalies too? Oof. Then again, PACMAN got nerfed after Anomalies were added, so I don't get people anyways.

**Pull request merged**
