### PR TITLE
Solve bikeshedding problem

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by RemieRichards** [comment]
:-1: :x: :100: No.

**Comment by KazeEspada** [comment]
I is confuzzled

**Comment by optimumtact** [comment]
we were having an argument in irc about use of this

**Comment by Supermichael777** [comment]
It would be better to have a note about what it does and why you needed it. not using features because byond's documentation is understandably dated is autistic.

**Comment by Cheridan** [comment]
Agree with Remie and Supermichael

**Comment by coiax** [comment]
BUT MUH CODING VALIDS

**Pull request closed without merging**
