### PR TITLE
Renames Credits to Yen

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Armhulen** [comment]
ew, weeb.

**Comment by lzimann** [comment]
gotta compile the tgui

**Comment by Bawhoppen** [comment]
dam good pr

**Comment by Bawhoppen** [comment]
better idea: make it randomly select the currency type

**Comment by Repukan** [comment]
Is this a Japanese Currency Unit reference?

**Comment by obscolene** [comment]
change it to chinese yuan

**Comment by Metallusions** [comment]
Nanotrasyen?

**Comment by Armhulen** [comment]
NANOTRA[B]EN.

**Comment by octareenroon91** [comment]
1000 nanos to the traßyen

**Comment by Mark9013100** [comment]
immoral anime culture

**Comment by PKPenguin321** [comment]
iamgoof🅱️all

**Comment by ExcessiveUseOfCobblestone** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by ma44** [comment]
I don't want Chinese lemons

**Comment by ShadowDeath6** [comment]
You missed an opportunity to call then shekels

**Comment by duncathan** [comment]
is this a meme?

**Comment by Iamgoofball** [comment]
no, not a meme

**Comment by duncathan** [comment]
ok

**Comment by PKPenguin321** [comment]
He lied

**Comment by lzimann** [comment]
At least do it correctly @Iamgoofball and compile the tgui.

**Comment by Jalleo** [comment]
Add a do not merge until goof compiles it.

**Comment by kevinz000** [comment]
goof is worth 1 yen

**Comment by Iamgoofball** [comment]
I can't compile it can someone do it for me

**Comment by Jordie0608** [comment]
I was going to merge this but then my hand slipped and I accidentally summoned a group of hyper-nationalist North Korean imperialists who seized control of is my computer, used it to close this PR and threw it into a lake for being a symbol of western decadence. Then they arrested the lake for collusion.
And lit it on fire.

**Comment by Repukan** [comment]
Help syndies emmaged Jordie's computer

**Pull request closed without merging**
