### PR TITLE
Shuttle Takeoff/Landing Animations

### PR DESCRIPTION
**Pull request by Cyberboss**
Re-make of #54483 

## About The Pull Request

Adds animated shuttle takeoffs and landings via `vis_contents` so you can actually see what's going on on them:

Previews (Apologies for massive gifs but I'm not rerecording):
https://cdn.discordapp.com/attachments/484170915253321734/767812127544573962/n4iyYCoQy3.gif
https://cdn.discordapp.com/attachments/484170915253321734/767812783390851100/pHZRl1Fj5M.gif
https://cdn.discordapp.com/attachments/484170915253321734/767820136139718716/ezgif.com-crop.mp4
https://cdn.discordapp.com/attachments/484170915253321734/767816450051801099/Y4s72p9kDA.gif

- Sets lighting objects to `VIS_HIDE`, it doesn't work with plane changes
- Fixes pubby supply shuttle's `port_direction`
- Makes `/obj/docking_port/var/preferred_direction` not flip itself by default

Original idea by @ninjanomnom 

## Why It's Good For The Game

The year is 2020 and shuttles still go *poof*

## Changelog
:cl:
add: Due to an increased number of station collisions, shuttles are now required to reach minimum safe distance from docks before entering/exiting hyperspace. <b>PLEASE DO NOT ATTEMPT TO BOARD THE SHUTTLE DURING THESE TRANSITION PERIODS.</b>
fix: When an admin edits the emergency shuttle's travel time, it will no longer be divided by 10.
/:cl:

Additional revisions to make.

- [ ] South dock alignment issues
- [ ] Rainbow hyperspace ripples (I forget what this meant)
- [ ] More robust animation for drydocks
- [ ] Ensure nuke ops rotation works correctly
- [ ] BYOS concerns here: https://github.com/tgstation/tgstation/pull/54483#issuecomment-713162497
- [ ] Test it doesn't still crash servers on BYOS/highpop

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
FUCK YEAH

**Comment by tralezab** [comment]
YEAH BABY WOOOOOOO

**Comment by necromanceranne** [comment]
"The year is 2020 and shuttles still go poof"

images (61)

**Review by Kylerace — CHANGES_REQUESTED** [review]

**Comment by Zytolg** [comment]
Ok the Syndie Bomb on the last one convinced me. This isn't the quality we need, but it's the quality we deserve.

**Comment by qbmax32** [comment]
depression

**Pull request closed without merging**
