### PR TITLE
removes bloat from magazines icons

### LINKED ISSUE #7798: Icon duplicates in the ammo magazine dmi
The code is also made in a way to support this
This needs to be fixed
Discovered a few minutes ago, the image is a proof(disregard the newer sprites, old are duplicating too)

image

### PR DESCRIPTION
**Pull request by ghost**
FIXED #7798

Duplicated icon states are bad

Also removed some leftover shit from uzis that caused runtimes

@Razharas

### CODE REVIEW

**Comment by Cheridan** [comment]
code ninja'd

**Comment by paprka** [comment]
sorry

**Comment by Razharas** [comment]
Wonderful

**Comment by WJohn** [comment]
I just noticed I rather stupidly designed the magazines, they need to empty out bottom up, not top to bottom like they are right now.

**Comment by paprka** [comment]
what does that have to do with this pr

**Comment by Razharas** [comment]
Nothing, ignore him

**Pull request merged**
