### PR TITLE
Telecomms Harddel Fix

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

Currently, telecomms machines store a hard reference to the last person to open the tgui. This can, in certain circumstances, lead to a hard delete. This PR just changes the reference into a weakref, so there should be no more risk of hard deletes.
## Changelog
:cl:
fix: Removed rare hard delete involving telecomms machines.
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
This PR is made obsolete by #79378

**Comment by AnturK** [comment]
Anyway, this works, but as seen in my pr the whole variable is redundant. Nothing actually needs that state.

**Comment by SyncIt21** [comment]
> Anyway, this works, but as seen in my pr the whole variable is redundant. Nothing actually needs that state.

Agreed. remove the user var and this should be mergeable

**Comment by GPeckman** [comment]
Alright, the operator variable has been removed entirely.

**Pull request merged**
