### PR TITLE
Make the GBP action work on forks with pull_request_target

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Worked on a local repo, and this is how things like auto labelers work.

There are security concerns, but they come through the fact that testing suites will run unsigned code, and that unsigned code now has access to repo secrets. This is not a concern here, as I am not running unsigned code, just reading labels of the PR and creating/updating the gbp-balances.toml file.

### CODE REVIEW

**Comment by Mothblocks** [comment]
Confirmed that this works on a local repo, where Timberpoes made a PR to a repo they don't have access to and received GBP for it:

https://github.com/Mothblocks/gbp-test/commit/f1c89a74077f0069b1672afe41acf73df4c29093

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
We may be able to go back to using `secrets.GITHUB_TOKEN` with this? Doubtful though.

**Comment by Mothblocks** [comment]
We should be able to yes, but we can do that after we figure out this works, or not even bother 🙂

**Comment by Cyberboss** [comment]
Hey, I'm fine with farming my commit count 😉

**Pull request merged**
