### PR TITLE
Fixes comms console cooldown being bypassable

### LINKED ISSUE #24578: Comms consoles don't have actual proper cooldowns
https://gyazo.com/98826596295f59c6f12e81a82f05d0f6

### PR DESCRIPTION
**Pull request by silicons**
Fixes #24578 - Comms console cooldown being bypassable.
Goddamnit

### CODE REVIEW

**Comment by AnturK** [comment]
Please give PR sensible title or it will have to be closed.

**Comment by kevinz000** [comment]
no fun allowed :3c

**Comment by lzimann** [comment]
this is a serious business

**Comment by XDTM** [comment]
Didn't we have a communications subsystem for this stuff now?

**Comment by Cyberboss** [comment]
We do, use that

**Pull request merged**
