### PR TITLE
EMERGENCY HOTFIX TO CHAMELEON LASER GUNS

### PR DESCRIPTION
**Pull request by silicons**
I DUN GOLFED!!

### CODE REVIEW

**Comment by Kraseo** [comment]
Hole in one!

**Comment by Sligneris** [comment]
88?

**Comment by coiax** [comment]
FIX CAMO LASER GUNS BEING AFFECTED BY EMP

**Comment by coiax** [comment]
@Sligneris no, it's two bees. Don't ask about projectile code, it's dark and mysterious.

**Comment by kevinz000** [comment]
@coiax they don't react on purpose because the server would probably get lagged if it did as it'll be grabbing shitloads of projectiles.

**Comment by Supermichael777** [comment]
wait do cammo laser guns shoot real lasers?

**Comment by Iamgoofball** [comment]
# looks like you didn't test for projectile bugs AGAIN, it's like hardlight bows all over again

**Comment by Iamgoofball** [comment]
how does it feel you little shit

**Comment by coiax** [comment]
> Goof telling people off for not testing their code

okay

**Comment by SgtxRootbeer** [comment]
Goof tests his code.... He tests to make sure it is suitably bugged beforehand.

**Comment by PKPenguin321** [comment]
Goof tests more than Kevin
>walking pAIs
>hardlight bows

**Comment by Iamgoofball** [comment]
@coiax this cuntbucket was telling me off about bugtesting and then LOOK AT THIS

**Comment by kevinz000** [comment]
@PKPenguin321 debatable

**Comment by Iamgoofball** [comment]
eat ass you 

# hypocrite

**Pull request merged**
