### PR TITLE
Cultural Beverages Returns: Tropical Freeze.

### PR DESCRIPTION
**Pull request by Hiynastrike**
## About The Pull Request

They're back. The Drinks that almost excited a generation of spacemen before I was told that August is bugfix month! Here is the old description:

This PR adds 6 new beverages themed after the 6 playable species along with a unique vending machine to sell them from. As I've been told during development to not make these combat focused to deter powergaming. All the drinks give is a solid mood buff and cool you down

-Humans | Spaceraid (Gatorade): a sports drink that the Terra Raiders claim was their key to victory during an American football game. Non-Humans refuse to stomach it out of principle.

-Lizards | Rattsi (Moxie): a soft drink that promises to bring the flavors of the Lizard homeworld across the galaxy. Other species aren't a fan of it's rodent based ingredients

-Moths | Fuzznet (Fernet con Coca/Inka Kola): an unusual blend of tea created by mothpeople, it's impossible for others to drink it's fibrous contents

-Ethereals | Electro (Tropico): a beverage made from the electricity enriched fruits of the Ethereal planet. You need to be an ethereal to appreciate it's deep and fruity flavor

-Plasmamen | Plazz (Kvass): a beverage that harkens back to an earlier time in Plasmaman history, one of endless possibilities as the race stared upwards at the stars.

-Felinids | Spring Nya (Pocari Sweat): a sports drink popular amongst Cat-people in Space Japan, many tourist from across the universe have come to try it, and have been left very disappointed and physically unwell

The Exotic Drink Machine:
-Sells 10 of each drink
-has it's own fancy sign animation

What's different from the original PR?

-Drink sprites are now larger and don't look like the size of liquor nips in comparison to a soda can
-Rattsi descriptions changed to meet common core requests.
-Fiberous is now Fibrous. This correct way of describing something as having the quality of many little fibers would ruin the game for everyone had it been spelt wrong, but now it's spelt right! Hooray!

## Why It's Good For The Game

I believe it fleshes out the universe when there's more products available on a station staffed with so many different alien species and the only snacks available are from Human dominated worlds that have general universal appeal.

## Changelog
:cl:
add: 6 new beverages
add: Exotic drinks vending machine designed to carry the 6 new beverages
add: Beverages also available from your local Robust Softdrinks machine
imageadd: each drink has it's own sprites for full and complete
imageadd: exotic drink machine has complete sprites and an animated sign
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
Look cool! would love to see some kinda picture to illustrate them. Would be kinda neat if the normal soda machine had one from the list randomly or something like that, so its a rare treat if you dont got the actual exotic vender

**Comment by Hiynastrike** [comment]
> Look cool! would love to see some kinda picture to illustrate them. Would be kinda neat if the normal soda machine had one from the list randomly or something like that, so its a rare treat if you dont got the actual exotic vender

image
I have this but these are the old graphics. The soda sprites are bigger https://i.imgur.com/qeVYa5B.png the vending machine sprites are the same, but I don't know mapping to add them.

**Review by ghost — CHANGES_REQUESTED** [review]
Don't add bespoke moodlets for drinks. There's a system for drinks to give moodlets already and honestly the idea of that was so that you'd go to the bar and get a drink from the bartender. So I don't like the idea of these giving mood in the first place.

**Comment by carshalash** [comment]
Eh, if you want it to be in line with bar content +2 mood would be fine. Leaving it at -3 for the wrong species would be good.

**Comment by Farquaar** [comment]
>Non-Humans refuse to stomach it out of principle.
Who are you to tell me that I can't play the lizard-version of Uncle Ruckus?

**Comment by AMonkeyThatCodes** [comment]
that sounds like a funny fucking gimmick

**Comment by KittyNoodle** [comment]
My only problem is that ethereals literally cannot taste at all, so they could not taste the cultural soda related to them

**Comment by AMonkeyThatCodes** [comment]
not true they just dont like the taste of normal human food.

**Comment by KittyNoodle** [comment]
`/obj/item/organ/tongue/ethereal
	name = "electric discharger"
	desc = "A sophisticated ethereal organ, capable of synthesising speech via electrical discharge."
	icon_state = "electrotongue"
	say_mod = "crackles"
	attack_verb_continuous = list("shocks", "jolts", "zaps")
	attack_verb_simple = list("shock", "jolt", "zap")
	sense_of_taste = FALSE `

Ethereal tongue code, notice the “sense_of_taste = FALSE”
Also there is no code that makes ethereals not like the taste of non-electric foods/drinks

**Comment by KittyNoodle** [comment]
BRB gonna go make a pr that actually makes ethereals have preferred foods

**Comment by KittyNoodle** [comment]
https://github.com/tgstation/tgstation/pull/61220 I actually did it

**Comment by tralezab** [comment]
make deviant taste let you enjoy every other sport drink

**Comment by carshalash** [comment]
> make deviant taste let you enjoy every other sport drink

Balance issues arise from that, unfortunately.

**Comment by Megamaw** [comment]
deviant tastes should be on a case by case basis.

moths usually hate fruity stuff. i can see a deviant moth enjoying electro, but hating fuzznet. and--

wait don't plasmament hate fruit

**Review by Twaticus — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
how do you get these?

Also I am not entirely sold on mood buffs, as im imagining the access to these drinks are likely going to be fairly easy to obtain.

**Comment by tralezab** [comment]
it conflicts, my friend. ready up your pr again when it's resolved

**Pull request closed without merging**
