### PR TITLE
Increased the range for combat visible messages

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: The range for seeing visible messages in combat is a tile higher.
/:cl:

Also it's a define so this is easier to change later(thanks philllll)

### CODE REVIEW

**Comment by Kraseo** [comment]
Can't we just revert this dumb attack log visibility thing? If I can see someone hitting someone else from 7 tiles away I should be able to see the attack logs.

**Comment by PKPenguin321** [comment]
what's the new range in this PR im too lazy to look at the code

**Comment by RemieRichards** [comment]
>what's the new range in this PR im too lazy to look at the code

Nobody tell him.

**Comment by PKPenguin321** [comment]
Too late I looked at the code anyways

**Comment by RemieRichards** [comment]
How's it too late? I didn't want anyone to tell you and nobody did.
you got japed into doing the thing you were lazy to do.
just like the rest of life!

**Comment by PKPenguin321** [comment]
Noooooo

**Comment by optimumtact** [comment]
Long term this should be exposed as as server config so they can adjust it without bothering us

**Pull request merged**
