### PR TITLE
Adds the goonchat SS

### PR DESCRIPTION
**Pull request by Cyberboss**
Aim is to reduce the number of output() calls by only composing and sending messages once per tick

Potential fix for #28875

### CODE REVIEW

**Comment by kevinz000** [comment]
but cyyybeeerboooossss now my screams for help will go out up to 0.05 seconds later!!!!!!

**Comment by optimumtact** [comment]
this is a terribly shit fix, goonchat does not do this on goon, figure out what we fucked up while we were porting it.

**Comment by optimumtact** [comment]
```
14:18 < oranges> Wirewraith: why would goonchat be so slow at updating it's DOm 
                 as to cause lag at lots of message output?
14:18 < oranges> IE can't be that bad
14:18 < Wirewraith> it doesnt
14:18 < oranges> #28875
14:18 < TheGhostOfWhibyl1> https://github.com/tgstation/tgstation/issues/28875 
                           - 'Goonchat has major lag issues when outputting 
                           many lines of text at once' by Tacolizard
14:19 < Wirewraith> maybe you shouldnt have fucked with my code???

```

**Comment by outbools** [comment]
Who would win:
-Entire open-source repo
-Single goon coder

**Comment by optimumtact** [comment]
The goon coder and his spaghetti code

**Comment by Jalleo** [comment]
I bet its because of one line somewhere.

**Comment by Cyberboss** [comment]
i hate this

**Pull request closed without merging**
