### PR TITLE
Prevent negative open positions in crew manifest

### PR DESCRIPTION
**Pull request by celotajstg**
## About The Pull Request

This is a hotfix for the new crew manifest. Because I forgot to add a check for whether there is more than 0 total positions available (assistants have -1) and whether total positions have a larger or equal number than current positions, there can be a negative number of open positions. This PR aims to prevent that from happening.

Roles with no position limit will now have an infinity icon. A tooltip has also been added to icons.

image

## Why It's Good For The Game

There shouldn't be a negative number of open positions, but currently it is possible.

## Changelog
:cl: Celotajs
fix: Prevented departments from having negative or undefined open positions in the crew manifest
/:cl:

### CODE REVIEW

**Comment by celotajstg** [comment]
Will remove the "non-assistant" part and replace it with a better solution right now, don't merge just yet.

**Comment by JJRcop** [comment]
> Will remove the "non-assistant" part and replace it with a better solution right now, don't merge just yet.

Check out this button just under the Reviewers category 
Screenshot_20210410_134700

**Comment by celotajstg** [comment]
Thanks for the advice!

The changes are now ready, and I have updated the pull request description.

**Comment by celotajstg** [comment]
To-fix:

image

**Comment by celotajstg** [comment]
Issue resolved
image

Changes are ready for merging.

**Comment by celotajstg** [comment]
Also the integration test failed due to Fermichem, it can be ignored.

**Comment by celotajstg** [comment]
Decided to rebase in order to ensure integration tests pass, as well as made a better commit message, as the scope of the fixes now applies not only to negative, but also undefined open positions.

Yet again though, the changes are ready for review and merging, I don't think I will make any further changes here.

**Review by stylemistake — COMMENTED** [review]
Use the `classes` helper, from common/react.

**Comment by celotajstg** [comment]
Done

**Pull request merged**
