### PR TITLE
Adds an alternate ling alert stinger that rarely plays when a player becomes a changeling

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

The ling alert noise is REALLY good. A lot of really gross and icky noises that really get you in the mood to play as a disgusting flesh creature. I listened to it a few times and thought to myself "hey, what about the OTHER noise that gets me in the mindset of body horror and gore?"

https://user-images.githubusercontent.com/28870487/209049455-f06ba66d-146a-4922-ad57-473deb330517.mp4
## Why It's Good For The Game

Jerma's chat nominated this one for best noise of 2022. The players will love it too.
## Changelog
:cl:
sound: Adds an alternate, rare ling alert sound.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
can you please rename it to alert wtf

**Comment by ChungusGamer666** [comment]
certified scorn moment

**Comment by Serxule** [comment]
**SCORN**

**Comment by SgtHunk** [comment]
changeling if it was good

**Comment by Mothblocks** [comment]
i don't get the reference + didn't laugh + don't know if we have the license

**Comment by SgtHunk** [comment]
> i don't get the reference + didn't laugh + don't know if we have the license 

https://youtu.be/U6wfkIVyLNA

**Comment by Mothblocks** [comment]
this is 12 minutes long

**Pull request closed without merging**
