### PR TITLE
Brings Ninja Adrenals closer to Traitor ones(without as much healing or stun resist)

### PR DESCRIPTION
**Pull request by Metroidlover**
:cl: MetroidLover
balance: The Spider Clan had finally updated their Adrenal injectors with better stimulants. However, the radium waste is still a problem
/:cl:

I've felt that Ninja Adrenals haven't really helped me whenever I get in a horrible situation, this should at least help a bit with a Ninja making a successful recovery(If the radium doesn't kill them after words)

If it feels that their should be a harsher punishment for it now, I can up the radium amount.

### CODE REVIEW

**Comment by FrostyFridge** [comment]
Thank goodness, we all knew Ninja really needed a buff.

**Comment by Borisvanmemes** [comment]
The last time i used i don't think i even took any real damage, this is unneeded imo.

**Comment by davethwave** [comment]
Perhaps replace the radium with polonium?

**Comment by Anonmare** [comment]
Polonium has extremely slow processing and is hyper deadly, even in small amounts

**Comment by davethwave** [comment]
I guess so, I've never tested it so I didn't know exactly HOW deadly it is concerning the amount of radiation it deals.

**Pull request merged**
