### PR TITLE
Add plasma xeno statue

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This adds a plasma xeno statue.  The sprite for this has been in the game for a while but has been unused.

## Why It's Good For The Game

More statue variety is good.  This will also be used in #60401 for random statue spawners.

## Changelog
:cl:
expansion: Added xeno plasma statue
/:cl:

### CODE REVIEW

**Comment by AMonkeyThatCodes** [comment]
make it actually craftable else its kind of useless

**Comment by timothymtorres** [comment]
> make it actually craftable else its kind of useless

Just use a chisel to make it like all the other statues.

**Comment by AMonkeyThatCodes** [comment]
oh its no longer a pre-defined list, fair enough.

**Comment by timothymtorres** [comment]
> oh its no longer a pre-defined list, fair enough.

Yeah statues are kinda funky right now.  Some are craftable, some are considered objects that you can pick up like marble busts, and others are from materials you can carve with a chisel.

**Pull request merged**
