### PR TITLE
Makes water wash colorful reagent off too

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Razharas** [comment]
Make them not colour ghosts also, cant wash ghosts

**Comment by Iamgoofball** [comment]
fixed in a diff. pr

**Comment by TZK13** [comment]
I told you so. :^)

**Comment by ike709** [comment]
rip rainbow ghosts, shall be missed.

**Comment by Razharas** [comment]
If something else uses colouring which is not tied to reagents water will still remove it

**Comment by Iamgoofball** [comment]
I so want to call that a feature

**Comment by Jordie0608** [comment]
Changelog ...i guess?

**Comment by Dorsisdwarf** [comment]
@Iamgoofball Can you please merge this? It's getting boring turning the entire station into hippies round after round

**Pull request merged**
