### PR TITLE
Blobs now have an animation when attacking a target

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
imageadd: Blob tiles now do an attack animation when failing to expand into a turf.
imageadd: Overmind-directed expansion is more visible than automatic expansion.
/:cl:

Updates a comment in blob_reagents.dm for accuracy.
Incidentally fixes bots to use the temporary overlays instead of setting all the vars on an overlay then deleting it.

### CODE REVIEW

**Comment by Zilenan91** [comment]
Pics?

**Comment by ChangelingRain** [comment]
Here's a pic of synchronous mesh attacking.
The correct reaction is "oh christ it's doing so much damage"
space station 13 2016-01-25 214732

**Comment by RemieRichards** [comment]
You're never destroying O, so it never goes back into the pool.

**Comment by duncathan** [comment]
temp overlays qdel themselves, @RemieRichards

**Comment by RemieRichards** [comment]
Ah it's ```/temp```, I only skipped the path and saw "effect" and "blob"

**Comment by ChangelingRain** [comment]
This is unrelated to the PR but I find it amusing that a system for arbitrary visual effects hasn't been used by anyone but me so far.
Maybe it'd because I made it and never really advertised its existence.

**Comment by Razharas** [comment]
This is how things like tablecrafting are happening
You gotta push it on someone else to use like phil a lot so it goes viral among coders

**Comment by ChangelingRain** [comment]
Yeah but it's designed to have no gameplay impact, just visuals, so the uses are limited to visual effects and that requires something that needs visuals in the first place.

**Pull request merged**
