### PR TITLE
Engineers can now use the ORM

### PR DESCRIPTION
**Pull request by ghost**
So Engineers can actually get that sweet plasma glass from the ORM!

:cl: More Robust Than You
balance: Engineers can now use the ORM
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Getting access to general materials like metal & glass is a big deal in itself

**Comment by MoreRobustThanYou** [comment]
Yeah

**Comment by Repukan** [comment]
Or you could use the common radio and ask for some?

**Comment by FantasticFwoosh** [comment]
Its about as secure as EVA and engineers probably won't explicitly over-use materials, open access ORM's would be a step too far.

**Comment by RandomMarine** [comment]
Miners rarely gather metal and glass, anyway.

**Comment by MoreRobustThanYou** [comment]
they usually do?

**Comment by SgtxRootbeer** [comment]
If I find gibtonite, I collect the metal and glass usually.

**Review by Cyberboss — APPROVED** [review]

**Comment by Repukan** [comment]
Access creep tbh.

If they want materials they could just ask or request from cargo or mining. You can literally order glass and metal, and the QM won't object to dispensing stuff unless you're being a shit.

**Comment by MoreRobustThanYou** [comment]
*but the plasma glass?*

**Comment by Repukan** [comment]
QM has access to the ORM, ask him for some. Make it buyable from cargo if it's such a rare occurrence. Access to the ORM makes about 5 people that can hog materials for autism projects instead of it going to RnD/Robotics.

**Comment by FantasticFwoosh** [comment]
I understand what you're saying about creep, but really its unpractical to rely on cargo/QM for materials when instead that's what mining is there for. If i want their attention i put in a order of 50 glass and metal from the requests console, not to bother them every ten minutes to clumsily release metal from the ORM.

> Engineers have a special level of ID, this is not greyshirts wearing yellow, if it was access free for all like you're trying to portray it, people would loot engineering not steal a engineers ID for orm access.

Most of the time there are no cargo techs,  or like real cargo staff they are idle minded and barely listen.

**Comment by RandomMarine** [comment]
@Repukan That would be feasible if scientists didn't regularly clean out the entire ORM for themselves.

**Comment by CPTANT** [comment]
It's pretty stupid that regular cargo techs don't have ORM access.

If they had they could actually perform their task of logistics.

**Comment by PraiseRatvar** [comment]
cargotechs would probably steal all the plasma and use it for points

unless these are smart cargotechs we are talking about

**Comment by FantasticFwoosh** [comment]
And yet scientists haul away all the minerals as @RandomMarine rightly points out and then store them inside the robotics lab/RnD where they likely wont be further used.

If people are going to be shitty, then a communal ORM everyone can use is a unpalatable but reasonable alternative.

**Comment by Hatfish** [comment]
Why even worry about access, just use the secret engie technique and get all the mats you would ever need out of the ORM.

**Comment by Repukan** [comment]
You complain about RnD hogging materials when that's literally it and robotics job. Other jobs such as Virology and bartender use materials too, and instead of giving them ORM access, they just ask cargo or the miners. Engineers can do the same

**Comment by CPTANT** [comment]
ORM should be a cargo only thing and they should be the ones to distribute the materials proportional to the needs of the station.

**Comment by FantasticFwoosh** [comment]
No its not @Repukan , that's being shitty€ and hoarding the ORM or even worse wrenching & pulling it away while showing 0 percent self restraint. 

There isn't a 'dump all' button on the ORM so why would scientists need to take 20 diamonds and the full contents of it by calling off the exact numbers?

**Comment by SgtxRootbeer** [comment]
Actually, @fantasticfwoosh
There is a "release all" button on the ORM. Maybe you haven't played a job that is dependent on it in a while?

**Comment by fludd12** [comment]
@Repukan By that logic, why do scientists have access to the ORM? Is it not Engineering's job as well to use materials? What about virology, is their job no longer "Use materials to make things?"

You can make the argument that *Engineering doesn't* need ORM access, but I feel like immediately turning around and saying *Science does* just seems like you're making a double-standard.

**Comment by Repukan** [comment]
>Comparing the department that has a forced symbiotic relationship with mining and cannot function without it working
>To the other department that does not need mining since they get a lot of materials roundstart and more scattered and stored in places for them to reach easily.

Fact of the matter is that engineering won't need plasma glass as compulsively as robotics or RnD need materials. Virology doesn't need materials to do their job either. 

RnD and Robotics are basically dead jobs if there's no miners/access to lavaland, hence them getting access to the ORM.

**Comment by Cyberboss** [comment]
@Repukan, Virology practically requires uranium

**Comment by Repukan** [comment]
Uranium is nice for the end game shit or more advanced symptoms, but even with no access to it you can still make viruses.

This is not the case with science

**Comment by fludd12** [comment]
>Even with no access to it, you can still make viruses.

Even with no access to materials, Science can still make pAIs.

**Comment by Repukan** [comment]
And I'm fairly confident in that everyone could agree that Science's job is not to mass produce pAIs, but rather upgrade machines around the station and tools crewmembers use as soon as possible.

**Comment by fludd12** [comment]
You can get to about the second highest upgrade level without use of a single piece of ore, but I do see your point. However, you only need about _one sheet_ of each ore to get to the highest upgrade level, and after that, maybe two sheets to actually produce enough parts to upgrade everything.

**Comment by Magikarpet** [comment]
you can screwdriver and crowbar open the machine anyways to steal all the resources lol

**Comment by FantasticFwoosh** [comment]
@SgtxRootbeer I forgot that was there because im usually moderate with my sheet expenditure and only bring as what is required.

I do play miner a lot more than i used to but it has been a while since i played science and made the rounds to collect minerals, hopefully post this pr gets merged i can also go check it out again

**Comment by ExcessiveUseOfCobblestone** [comment]
Any job that is informed materials have been added should have access to the ORM. This includes chemistry and viro.

**Comment by MimicFaux** [comment]
and bartender.

**Comment by FantasticFwoosh** [comment]
Maybe we should restrict access to the ORM on a material basis, saying that scientists & miners have full access, miners get everything besides diamond etc. etc.

**Comment by Cyberboss** [comment]
@KorPhaeron pls

**Comment by lzimann** [comment]
Kor never decided on this, so I'll decide myself. Engineers can already get plenty of materials that they can access, plus, all you have to do is ask a miner or a QM, maybe even add access to cargo techs(althought not so sure on that) to retreive it for you, or even a scientist if there's one around.

**Pull request closed without merging**
