### PR TITLE
replaces armblade with horrorform [THE THING IS BACK]

### PR DESCRIPTION
**Pull request by ghost**
I have reasoning! Changelings are, with all their powers, always extremely powerful. Replacing their main weapon with a three minute form that stuns when it's over and leaves them vulnerable while not horror formed will make changeling a much more interesting antagonist than (I'M YOU, TRAITOR, BUT WITH INVISIBLE ESWORDS AND FREE HEALING!)

okay well fleshmend still exists but you get the point, it's a step in the right direction

i need help balancing this and i'm MORE than open with any and all suggestions to balance downsides and upsides to the horror form.

### CODE REVIEW

**Comment by Armhulen** [comment]
committing the horror form commit give me a second

**Comment by Repukan** [comment]
You're tackling this wrong if you think this solved the problem with combat ling.

**Comment by Armhulen** [comment]
good point but i was vyying for making periods of weakness not always having an esword

**Comment by Armhulen** [comment]
also i'm gonna remake this pr because webeditor and then my computer crashed halfway through so um

**Comment by Repukan** [comment]
That'll be 0.25 GBP

**Comment by praisenarsie** [comment]
>webeditor for major prs

**Comment by Armhulen** [comment]
monika2

**Comment by RemieRichards** [comment]
@Armhulen I request you don't do this, I already have horrorform included in my goon ling port.

**Comment by Armhulen** [comment]
how close is that to completion i really hate lings right now

**Comment by RemieRichards** [comment]
I am at the cleanup phase, I'd say 80% done, and that was only a day's work.

**Comment by Armhulen** [comment]
finish it soon please, i trust you!

**Comment by Repukan** [comment]
That'll be 0.25 GBP sir, tip not included.

**Comment by Armhulen** [comment]
don't even post that

**Comment by Repukan** [comment]
Thank you for your business here's your change.

**Pull request closed without merging**
