### PR TITLE
Sleeping Carp changes

### PR DESCRIPTION
**Pull request by ghost**
- Sleeping Carp martial arts are generally more effective
- People with the Sleeping Carp martial art can no longer use ranged weaponry, but deflect all projectiles if they are not laying down and are not hulks

_This is all subject to change, but Sleeping Carp definitely needs a buff. I have never seen a Sleeping Carp gang win at all._

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>Sleeping Carp now deflect all projectiles if they aren't lying down

fuck yeah, i've always wanted to punch bullets out of the air

**Comment by Boredone** [comment]
Question. Does this happen right on recruitment or do they need the martial arts to not be able to shoot, and reflect ranged?
Also, does this include thrown stuff and throwing? Spray bottles?

**Comment by Xhuis** [comment]
@Boredone This happens right on recruitment. It only includes projectiles, not thrown items or sprayed reagents.

**Comment by Boredone** [comment]
I have a feeling Improvised Cannons will be their bane then, but that's rare enough to probably be fine.

**Comment by Zilenan91** [comment]
I think the projectile reflection should require reading the scroll, because currently, this might be huge meta for sec officers to shoot disablers down halls and see if anyone deflects them.

**Comment by Xhuis** [comment]
@Zilenan91 For one, meta of this caliber would be bannable. Second, the gangsters would just deflect the subsequent electrodes and could easily disarm the officer with one of the many stunning combos or even a spray can full of water.

**Comment by Shapsy** [comment]
Permanent invisible super riot shields? This sounds like it would be insanely frustrating to fight against

**Comment by PKPenguin321** [comment]
yeah but you still have stunbatons and such and they have no ranged options on you whatsoever

**Comment by Zilenan91** [comment]
OH DEFLECT OH SHIT. That's probably a bit much don't you think? Using magic fist powers to deflect tasers and/or bullets back at your enemies is way too strong, it doesn't even use up a hand slot like an eshield does. If it blocked it would be fine though, that's what I thought it did before.

**Comment by Iamgoofball** [comment]
please give sleeping carp members full body yakuza tats so you can tell if they are one of these nerds

**Comment by SconesC** [comment]
BLOCK or deflect

Because it should block

Not deflect

**Comment by MMMiracles** [comment]
Sweet jesus please add some sort of check to prevent them from having hulk with this. Unstunnable, insta-ko punches, deflect all projectiles oh god aaaaaaaaaa

**Comment by Xhuis** [comment]
I did some thinking overnight and I believe that if I restricted the projectile deflection to people with the martial art it would probably be much more balanced. When I thought about it, normal gang members usually just have a spray can and some weaponry unrelated to Gang.

**Comment by Xhuis** [comment]
I changed bullet deflection and no ranged weaponry to affect only people with the martial art. I also made the Blasto gang immune to explosions (I might change this to simply make explosions do less against them).

**Comment by Anonus** [comment]
>blasto suicide bombing

What do you think is going to happen?
Hint it's gonna be blasto walking at you, then maxpcap bombing in a space suit.

**Comment by SconesC** [comment]
sounds funny

**Comment by PKPenguin321** [comment]
wait is blasto a straight upgrade now

**Comment by Shadowlight213** [comment]
@Xhuis If they block or deflect all projectiles, please make hulk not work with it. Unstunnable laser proof gang members aren't fun.

**Comment by Xhuis** [comment]
@Shadowlight213 I will make hulks take damage from projectiles like normal.
@Anonus I intend to add gang-specific effects for most of, if not all, of the gangs that exist already.

**Comment by PKPenguin321** [comment]
donk members have an ability on a cooldown that automatically injects them with some omnizine (because donk pockets have omnizine when heated up idk)

omni members get some kind of passive eye upgrade (thermals or xray or a passive sechud or welding shields or something?)

what other gangs are there

**Comment by KorPhaeron** [comment]
I don't think one of the most popular/most well functioning modes needs a bunch of gimmicky bits that unbalance it one way or another.

There are other modes that need the attention a lot more, so why fix what isn't broken?

**Comment by Xhuis** [comment]
I removed the special effects from Blasto. If I ever decide to add gang-specific effects, it will be in another PR. For now, this is only for the Sleeping Carp.

**Comment by SconesC** [comment]
it's gangbangers not crime wizards

**Comment by Iamgoofball** [comment]
@SconesC what if you got bonus points for wearing your gang's color

**Comment by KorPhaeron** [comment]
Is there not a prettier way of doing this than checking for the mob having sleeping carp every time a human is shot?

At least generalize it to a reflect chance for all martial arts?

Or just make the bostaff a shield item

**Comment by Xhuis** [comment]
Bo staves are already a shield item.  I could probably generalize the reflect chance to martial arts as a whole.

**Comment by Xhuis** [comment]
I refactored projectile deflection. It now checks the martial art datum for a variable, deflection_chance, which is found in all martial arts. Currently it only affects the Sleeping Carp at, which has a deflection chance of 100% which means all projectiles will be deflected.

**Comment by Razharas** [comment]
So its kinda like hulk but not exactly hulk huh
Ok lets see how it goes

**Comment by tuypo1** [comment]
I did not even know this was a thing

**Pull request merged**
