### PR TITLE
Fixed orion trail so silicon can play

### LINKED ISSUE #62785: AIs can't play Orion trail.
## Testmerges:
#62771: 'Fix team antag HUDs displaying when they shouldn't, and the other way around' by Mothblocks at commit de9a58ae25
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 288695b981
#62727: 'Departmental Security Rework Option #1: Department First, Security Second' by Iamgoofball at commit 029f550f7e

## Reproduction:
1. Be AI.
2. See an Orion Trail arcade machine.
3. Open up the arcade menu and be unable to use any of the options.

### PR DESCRIPTION
**Pull request by Dr-Pope**
Changed the orion.dm and changed orion_event.dm so silicon can play orion trail

## About The Pull Request
Fixed an issue with silicon not being able to play orion trail. First time doing anything so might be messed up.

## Why It's Good For The Game
Bug fix is good
fixes #62785

## Changelog

:cl:Doctor Pope
fix: fixed an issue in orion.dm and orion_event.dm to let silicon play orion trail
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
fixes #62785

**Comment by Ghommie** [comment]
Too bad maint drones can't pick up toys.

**Comment by timothymtorres** [comment]
Did you test this with emag effects?  From the code it looks like an emagged arcade machine might gib the AI.

**Comment by LemonInTheDark** [comment]
oh come on

**Comment by Dr-Pope** [comment]
Pain

**Comment by timothymtorres** [comment]
I double checked the battle arcade code effects and it also gibs silicons when emagged.  Since the effects for all arcade types are consistent then everything should be gucci.

**Comment by Dr-Pope** [comment]
Oh nice so shouldn't be an issue then

**Pull request merged**
