### PR TITLE
Reworks/Rebalances stamina reagents

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Reworked most stamina chem to deal their stamina damage only on the chest. This results in them being much more effective at achieving their job.

EDIT: Alright, here we go again. I reworked a bunch of more stuff. The most important change is that I added a new reagent: Caffeine. You get caffeine by ingesting various coffee based baverages and energy drinks. Caffeine heals three stamina damage per tick. It's supposed to be what nicotine is for stun, but for stamina damage. Other than that I reworked most chemicals to use the new way of dealing damage and buffed/nerfed some of the old medicines against stamina damage.

You might be wondering why I bother to add a new reagent. The reasons are simple, I want a easily available chemical that treats stamina damage, but I also would rather avoid bloat and potentially opening the door to making people immune to stamina damage with chems alone. Caffeine is supposed to be to stamina damage like nicotine is towards stuns.

ALCOHOLS:
Beepsky's: Has been nerfed to only heal 5 stamina damage instead of 10.

Neurotoxin: Uses the new way of applying stamina damage. Also doesn't deal stamina damage on leaving your system.

Faniculli: Now deals 8 stamina damage when added.

Branca Mante: Now deals 10 stamina damage when added. Both (this and Faniculli) these values are fairly low, because higher amounts would make running around with a damp rag that carries both of these too strong.

Rum&Coke, Thirteen Loko, Whiskey Cola, Fernet Cola and Cuba Libre: These drinks now decay into caffein.

BLOB:
Will do this later when less people are messing with it. Code improvements have priority over this.

DRINKS:
Coffee, Cafe Latte, Gray Bull, Soy Latte, Space Cola, Dr.Gibb, Space mountain wind and Nuka Cola: Now decay into caffeine. Some of their effects have been removed, as they are also present in caffeine.

DRUGS:
NEW: Caffeine: Restores 3 stamina damage per tick, reduces drowsiness and wakes you up.

FOOD:
Entropic Polypnium: Uses the new way of applying stamina damage.

MEDICINE:
Ephedrine: Now heals 5 stamina damage instead of 1.

Epinephrine: Now heals 2 stamina damage. Overdose deals 10 on a 33 percent chance.

Stimulants: Now heals 10 deals stamina damage. The OD now deals 8 stamina damage on a 33% chance.

Earthsblood: Now heals 15 stamina damage instead of 30. 

Haloperidol: Now deals 3 stamina damage, canceling out natural regeneration.

Changeling adrenals: Now heals 5 stamina damage.

Modafinil: Now heals 2 stamina damage while not ODing. Removes the stamina damage from the OD.

TOXINS:
Tirizine: This reagent now initially deals 11 damage per tick to the chest. This number decrements by one each tick to a minimum of 2. This should make the damage peak at ~90 stamina damage, so it should not put people into stamcrit if didn't take damage beforehand. It also deals 15 stamina damage to each leg, meaning that both of them will be disabled after 4 ticks.

Sodium Thiopental: Uses the new way of applying stamina damage.

Bone Hurting Juice: Now deals 6 stamina damage per tick.

Coffee powder: Now decays into caffein.

OTHERS:
Stimulum: New heals 10 stamina damage per tick. This is the atmos buff we have all been waiting for.

Tiring solution: This now deals 10 stamina damage per tick to a maximum of 42 stamina damage. This is the chem that worries me the most. It might need some adjustments. Not because the amount of damage it deals is really a problem, but because it encourages validhunting borgies.

## Why It's Good For The Game

The stamina damage component of chem used to be almost completely nonfunctional. This fixes that. With the advent of glorious stamina based combat, it would be mean for chemistry to be left out.

## Changelog
:cl:
add: Adds a new reagent: Caffeine. It restores three stamina damage per tick, removes drowsiness and wakes you up. Causes jittering and cancels out the stamina gain when ODing.
add: Coffee, Cafe Latte, Gray Bull, Soy Latte, Space Cola, Dr.Gibb, Space Mountain Wind, Nuka Cola, Rum&Coke, Thirteen Loko, Whiskey Cola, Fernet Cola and Cuba Libre now decay into caffeine. Some of their effects have been removed as coffee covers those now.
balance: Reworks all stamina chems to mainly deal damage to the chest. This results in them being much more effective at incapacitating the target. Due to them being much more effective, a lot of numbers have been adjusted.
balance: Chems that got buffed: Neurotoxin, Fanciulli, Branca Menta, Ephedrine, Epinephrine, Stimulants, Changeling Adrenals, Modafinil, Stimulum, Tiring Solution, Tirizine, Sodium Thiopental, Bone Hurting Juice, Entropic Polypnium
balance: Chems that got nerfed: Beepsky Smash, Earthsblood, Haloperidol
balance: Reworked tirizine to rapidly disable someones legs.
add: Adds a new code only generic stamina toxin.
/:cl:

### CODE REVIEW

**Comment by Angustmeta** [comment]
Been looking forward to these changs. 

But reminder that bone-hurting juice was changed t0 0.4 metabolism here: #42600

Does stamina damage scale with metabolism or is stampwr = 12 always 12 stamina per tick? I believe `REM` is always 1 unless you have metabolism virus or something.

**Comment by necromanceranne** [comment]
Sleepy pen buff, very epic. It's initial payload has been trash since forever, and tirizine especially.

**Comment by HomocidlePancakes** [comment]
1)Sleepy pens are fukken gey
2)Does the leg stamina damage on tirizine also decrements by two each tick?

**Comment by Angustmeta** [comment]
There are also several other chems with either normal or OD-effects which deal stamina damage. For consistency it would be good if they eventually got similar treatments:

- Epinephrine OD
- Stimulants OD (not sure which one)
- Haloperidol (someone please fix drowsiness slowdown)
- Modafinil
- Tiring solution
- Entropic Polypnium (chance per tick)

**Comment by Daxxed** [comment]
>     * Epinephrine OD
Miners OD on this pretty often, I think even two survival pens in a few mins will OD you on this.
Also everyone spawns with a pen roundstart, lets not make the new stunmeta to steal someones epipen and inject both into someone.

**Comment by Angustmeta** [comment]
Legit concern but epinephrine OD is only prob(33) for 2.5 stamina which is way lower than natural regen.

**Comment by py01** [comment]
Peacekeeper has tiresolution which may need to get looked at.

**Comment by Tlaltecuhtli** [comment]
change the stamina healing drugs values too as they do stuff like 1 or 2 heal/tick which is bad

**Comment by Angustmeta** [comment]
I think stamina healing chems should still heal limbs though.

**Comment by nemvar** [comment]
Alright. Webedit extravaganca is done

**Comment by Barhandar** [comment]
Tirizene dropping legs turns sleepypen into discount parapen because you're mute and _can no longer move and hence escape_.

**Comment by necromanceranne** [comment]
compared to _you feel a tiny prick_

OH BETTER DRINK SOME COFFEE AND NOT GIVE A FUCK

**Comment by nemvar** [comment]
Tirizine used to peak at 10 stamina damage. It was completely useless. Sleepypen would have been better without it because there would be a higher chance you don't notice it.

Coffee also didn't used to regenerate stamina. I'm adding caffeine in this PR.

**Comment by AdamElTablawy** [comment]
separate the nerf to particular chems like haloperidol dol from the rest of the changes to how stamina works. otherwise this is a feature coming bundled with a nerf

**Comment by necromanceranne** [comment]
Imagine thinking you should be able to escape after a traitor uses an item meant to incapacitate you successfully.

**Comment by nemvar** [comment]
Not quite sure why it's over 500 removed lines. The file I deleted doesn't even exist on master.

**Comment by nemvar** [comment]
Heavily clashes with 4ds changes. Will close for now.

**Pull request closed without merging**
