### PR TITLE
Ticking the map dm's will force that map to load

### PR DESCRIPTION
**Pull request by Cyberboss**
@MrStonedOne

### CODE REVIEW

**Comment by XDTM** [comment]
hold on how do i switch maps for testing without these

**Comment by Cyberboss** [comment]
Server -> change map then reboot

**Comment by Cyberboss** [comment]
They already do nothing

**Comment by PKPenguin321** [comment]
So you HAVE to compile into a station and join in to switch maps? What's the point of runtimestation, then?

**Comment by Cyberboss** [comment]
Runtimestation still loads faster than any other map. Also, in order to
switch maps before starting now, you can copy the map.json to
data/next_map.json

**Comment by PKPenguin321** [comment]
Seems extra complicated

**Comment by xxalpha** [comment]
Delete this, what a terrible idea.

**Comment by MrStonedOne** [comment]
just make these files do some shit to override the station that is loaded unless some other shit is done to override them (ie change map)

**Comment by MrStonedOne** [comment]
ie, make it so the repo don't save the next/prev map files, and make these files control the default, for easier debugging and other shit.

**Comment by Cyberboss** [comment]
Lol @xxalpha I love how you care now AFTER the PR that changed this was merged #24171

**Comment by xxalpha** [comment]
Better late than never.

**Comment by MrStonedOne** [comment]
DNM until I update the server version of the updaters, i'll do that sometime tonight and then upload the test merge stuff

**Comment by Cyberboss** [comment]
While you're doing that, you should commit the server tools :^)

**Comment by MrStonedOne** [comment]
ready

**Pull request merged**
