### PR TITLE
Energy Guns Overlays

### PR DESCRIPTION
**Pull request by Jordie0608**
Refactored energy gun update_icon() to use overlays for charge, weapon state and flashlights.
Almost every energy gun's icon has been slightly modified, mostly changing the charge bar size/shape/position and adding a flashing diode.
Bits of code have been moved around for organization and temperature.dm was merged into special.dm

Before: 40KB
before
After: 25KB
after

Part 1 of ? to make all guns use overlays; projectile weapons are next.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Hero of the ages
Overlayer of men

**Comment by WJohn** [comment]
Thank you for this. :+1:

**Comment by phil235** [comment]
:+1:

**Comment by Steelpoint** [comment]
This should make editing guns a lot easier

:+1:

**Comment by Thunder12345** [comment]
:-1: Forces simple, boring charge meters, doesn't allow details such as changing colours

**Comment by WJohn** [comment]
So is ammo count now handled by the code?

**Comment by Steelpoint** [comment]
On second thought :-1: 

The animations feel off and the in hands don't change to reflect the current ammo count.

**Comment by Jordie0608** [comment]
@Thunder12345 Changing colors is still supported.

@WJohn No

@Steelpoint Handling of item_state will be done when the handling of icon_state is unified in a later PR.

**Comment by Fox-McCloud** [comment]
As much as it's nice to save on space...I don't personally think this is a good one for this, due to guns' nature. 

Don't really care for this at all.

**Comment by Steelpoint** [comment]
Is 15kb really worth this? It does make things less nice looking for a little bit of space.

**Comment by WJohn** [comment]
How exactly is ammo count displayed then, jordie? I'm not seeing ammo notches on all of these if there's any pixel shifting. Also yeah I guess this does cut down on freedom here.

**Comment by Fox-McCloud** [comment]
About the only way this would be interesting is if the overlays were displayed above the light layer, to make it look like they were "glowing"...but that's also going to have a bunch of other weird behaviors that go along with it.

**Comment by Jordie0608** [comment]
I'm afraid I don't really understand some of the complaints here; the only change in functionality is with the inhands, which I'll try to patch back in with a way that won't cause future issues. Aside from that however I'm at a bit of a loss to meant by "the animations feel off" and "due to gun's nature".

@WJohn It looks the same as guns do now with their charge bars displaying ammo shots left.

**Comment by Lumipharon** [comment]
http://i.imgur.com/sxNmEaQ.png

This is super fucking ugly. What is wrong with what we had?

**Comment by Fox-McCloud** [comment]
Ugly, unreadable what the gun looks like at a glance, wayyyy harder for spriters to create additional sprites, and a bit more difficult to maintain.

All to save a pathetic 15 KB.

Overlays made sense for screens, as they all have the same base, but guns are significantly different.

**Comment by PKPenguin321** [comment]
this is super necro, but this change is a pain in the ass to develop around and it would be nice if there was some kind of guide explaining how to use charge meters and stuff

**Comment by Steelpoint** [comment]
I will admit that this change stopped me from making a bunch of gun sprite changes as the fact there is little documentation on how this shit works put me off.

**Pull request merged**
