### PR TITLE
Monkeys can wear hats!

### PR DESCRIPTION
**Pull request by RemieRichards**
## MONKEY HATS!!!111!!!one!!!
- Monkeys can now wear any hat a human can
- Monkeys can now wear any MASK a human can (previously it was a select few they had icons for)
- All mask icons in /icons/mob/monkey.dmi have been removed (no longer needed)
- head item slot moved to /carbon, to be shared by monkey and human (only these two have the HUD icons to equip things in game, but feel free to badmin)
- Monkey icon changes: All directions lifted up 1 pixel, Side directions moved 1 pixel along the dir they face (West - west, East - east), this is to accommodate using human icons for all masks and hats.
  I'd argue the side sprite change is definitely an improvement, while the 1 pixel upwards is barely noticeable.

### CODE REVIEW

**Comment by dannno** [comment]
perfecto :+1:

**Comment by GunHog** [comment]
In before a monkey wears a drone as a hat, for two times the RR!

**Comment by PKPenguin321** [comment]
now we just need to be able to wear monkeys on our heads

**Comment by killerfgs** [comment]
human wearing a monkey wearing a drone when?

**Comment by xxalpha** [comment]
This changes everything. :tophat:

**Comment by Jordie0608** [comment]
But can monkeys wear changelogs?!?

**Comment by RemieRichards** [comment]
@Jordie0608 Not sure if it's my internet be a tool or github, but at the moment I actually can't push the changelog I made.

**Comment by RandomMarine** [comment]
Monkey wearing a drone wearing another drone wearing the shamebrero.

**Comment by Cheridan** [comment]
This changes EVERYTHING. :earth_asia: :boom:

**Comment by RemieRichards** [comment]
@tgstation/commit-access MONKEY HATS GUYS, MONKEY. HATS.

**Pull request merged**
