### PR TITLE
Fixes travis grep script to use PCRE to actually match things

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
Several of the greps were missing the `-P` switch which caused them to fail to match things
The EOL grep also wasn't working right so I replaced it with the one I added to TGMC

### CODE REVIEW

**Comment by spookydonut** [comment]
@ShizCalev @SpaceManiac

**Comment by SpaceManiac** [comment]
MetaStation.dmm has a weirdly big diff, how did you arrive at it?

Everything else looks good

**Comment by spookydonut** [comment]
> 
> 
> MetaStation.dmm has a weirdly big diff, how did you arrive at it?
> 
> Everything else looks good

Oh i probably havent updated the map backup for mapmerge

**Comment by SpaceManiac** [comment]
changes were dropped and meta is failing lint again

**Comment by spookydonut** [comment]
> 
> 
> changes were dropped and meta is failing lint again

@SpaceManiac fixed

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
