### PR TITLE
Makes all qdels do del() instead so the lazy spoiled kids these days understand what SS13 was like back in the good old days

### PR DESCRIPTION
**Pull request by Iamgoofball**
kids these days don't understand that when we wanted a bomb to go off we had to walk uphill both ways in the snow for 3 minutes while the server finished deleting stuff

let's testmerge this on terry for a round

### CODE REVIEW

**Comment by Jacquerel** [comment]
You can do troll testmerges without an open troll PR

**Comment by Iamgoofball** [comment]
amen

**Comment by carlarctg** [comment]
This is the most based PR I have ever seen

**Comment by ZephyrTFA** [comment]
too laggy, broke Terry and couldn't start

**Pull request closed without merging**
