### PR TITLE
Donutstation Tweaks

### LINKED ISSUE #42498: White ship is unable to travel to the station's z-level on Donutstation.
The white ship is unable to dock at station or even travel to the station's z-level on Donutstation.

image

### LINKED ISSUE #45077: The transit tube to telecomms on donut is non-functional
## Reproduction:

Watch the transit tube that should go to and from tcomms on donut. Notice how it never moves under any circumstance. Try to enter it and find yourself unable to.

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
- Fixes #45077 
- Fixes #42498
- Removes every single instance where a grille could end up on top an active wire in maintenance, making traveling maintenance a lot less of a hassle and less dangerous in general.
- Maintenance bar has been removed due to redundancy and closeness to the actual bar. Wait till season 10 of SS13: Battle Royale to find out what exciting changes will come to the map!
- Space-proof variants of the lizard critter has been added and are working diligently on the above-mentioned bullet-point.
- As part of the white shuttle fix, Donutstation now has a custom shuttle with deep _l o r e_ to explain what happened to the long-past crew.
- Small adjustments to the static loot part of the 'excess storage' rooms near departments.
- Some extra crates has been added around maintenance with respective maintenance loot spawners.

## Why It's Good For The Game
Bug fixes relating to the map and some added map content to keep things 'fresh'.

## Changelog
:cl: MMMiracles
add: Donutstation now has its own white shuttle with proper dock.
del: Donutstation's maintenance bar is under renovation.
tweak: Due to above renovations, the goose is temporarily loose.
tweak: Donutstation now has significantly less annoying maintenance grilles
/:cl:

Bar Maintenance:
image

Whiteship:
image
The loot spawner on the ship has a 25% chance of spawning a fully functional RIPLEY and a 75% chance of spawning the wreckage of one.

### CODE REVIEW

**Comment by actioninja** [comment]
> * Removes every single instance where a grille could end up on top an active wire in maintenance, making traveling maintenance a lot less of a hassle and less dangerous in general.

lame

**Comment by MMMiracles** [comment]
They were meant to be a hindrance when added originally, cables automatically shocking grilles made maintenance almost impossible for a regular crewmember to traverse without gloves which is not what I intended at all.

**Comment by actioninja** [comment]
That's fair and understandable but I'm going to complain anyways.
Mapdiffbot is down yet again so just post some pics of the changes and this will be good to go.

**Comment by TheChosenEvilOne** [comment]
if you haven't fixed the lamp in the experimentor lab, please do. Its annoying me way too much.

**Comment by MMMiracles** [comment]
There isnt a lamp in the experimentor room?

**Comment by TheChosenEvilOne** [comment]
@MMMiracles this is not a lamp is it then?
image

**Comment by optimumtact** [comment]
that's a banana

**Pull request merged**
