### PR TITLE
3/4 Plating

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Before:

After:

Changes the plating sprite to be 3/4 and smoothed, appearing sunken into the floor.

## Why It's Good For The Game

More depth to the floor. Going to fit the wallening walls better.

## Changelog

:cl:
image: New plating sprite
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
how does this look adjacent to non floor tiles? (like carpet, etc) It's obviously not the most common case but I am curious

**Comment by OrionTheFox** [comment]
> > how does this look adjacent to non floor tiles? (like carpet, etc) It's obviously not the most common case but I am curious
> 
> [image]

Catwalk tiles (bottom left) were intended to be the same 'layer' as plating, the grate overlay being the part at actual 'tile' height.
Not sure I like how it looks with this plating having a 'step up' to it, but I've no clue how to even start fixing that.

It looks nice otherwise tho

**Comment by zxaber** [comment]
Catwalk tiles being higher (like in this PR) will look nice when used inside main rooms. Anyway, since they can have piping underneath, it would probably be weird for them to somehow be flush with adjacent hull that runs the same pipes above.

**Comment by Rex9001** [comment]
I don't like how they look in space tbh

**Comment by MTandi** [comment]
> I don't like how they look in space tbh

It's not unrealistic though. 

image

**Comment by mc-oofert** [comment]
doesnt look good in the context of not being on wallening

**Comment by zxaber** [comment]
> doesnt look good in the context of not being on wallening

image

**Comment by Jacquerel** [comment]
This change looks good without wallening but I also don't love how isolated platings look in space, personally I think it'd be ideal if it "smoothed" with space tiles without applying the lip decal

**Comment by MTandi** [comment]
> it doesn't really make any sense that they'd be given a 1 inch "wall" connecting to nothing

I see the plating as a tub with small walls, there is no "wall" connecting to something, it's just the inner face of the sides visible due to the perspective.

**Comment by Jacquerel** [comment]
> > it doesn't really make any sense that they'd be given a 1 inch "wall" connecting to nothing
> 
> I see the plating as a tub with small walls, there is no "wall" connecting to something, it's just the inner face of the sides visible due to the perspective.

It doesn't make sense that they would construct it as a tub or anything with sides if it is in space
There is nothing for it to be "lower" than in these scenarios, it should only draw the "sides" in scenarios where it is smoothed with something on ground level, which space isn't.

**Comment by mc-oofert** [comment]
> > doesnt look good in the context of not being on wallening
> 
> -snip-

excuses bro excuses

**Comment by AMyriad** [comment]
I'm just scrolling by, but I don't see anybody pointing out why it looks jank.
From what I see, the edges/lines of smooth plating are asymmetrical on some sides, leaving more pixels of space between borders on some sides than others.

image

This is only a few pixels of difference, but it begins to stand out in irregularly shaped environments.

image image

**Comment by MTandi** [comment]
> I'm just scrolling by, but I don't see anybody pointing out why it looks jank. From what I see, the edges/lines of smooth plating are asymmetrical on some sides, leaving more pixels of space between borders on some sides than others.
>
> This is only a few pixels of difference, but it begins to stand out in irregularly shaped environments.

Sorry I don't understand what exactly is asymmetrical and looks bad to you. Please elaborate further.

**Comment by Jacquerel** [comment]
> jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDIwNDQsIm5iZiI6MTcyMTg0MTc0NCwicGF0aCI6Ii8xNDM5MDgwNDQvMzUxNzcwMzEyLWZlYThiY2QwLTFmNDAtNDY2Yy1iNDk1LWRiYWE4YWQ2MGUxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNzIyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzc4ZTkyMWRiNjRlMmY2NjQxMGNhNjg0YWUyOTNmYjRlMTQyYjVmZjFiNWY1MmM3OTE0MWFlNDY5YWIxMGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NL92wJ3S6fMsrrj9cOQQsFwBes71uHSUTjMdB4RhP7Y)

I think this only looks weird because you have a "raised area" which just contains a hole (pointless to have made a raised area there), if it was surrounded by floor tiles it would look fine.

**Comment by MTandi** [comment]
> I think this only looks weird because you have a "raised area" which just contains a hole (pointless to have made a raised area there), if it was surrounded by floor tiles it would look fine.

I see the plating as a box, open at the top. 
It is a box because it can contain cables and pipes that are inside the box.
By placing a tile on a plating, you're closing the box as with a lid.

I see no issue here, and the sprite makes sense even on space tiles. It would be nice to have an additional pixel or two at the bottom to show the outter wall of the box, but I don't think it can be solved easily.

And you can imagine that the box is narrowing to the bottom, that's why the face is not visible.

**Comment by Jacquerel** [comment]
> > I think this only looks weird because you have a "raised area" which just contains a hole (pointless to have made a raised area there), if it was surrounded by floor tiles it would look fine.
> 
> I see the plating as a box, open at the top. It is a box because it can contain cables and pipes that are inside the box. By placing a tile on a plating, you're closing the box as with a lid.
> 
> I see no issue here, and the sprite makes sense even on space tiles. It would be nice to have an additional pixel or two at the bottom to show the outter wall of the box, but I don't think it can be solved easily.
> 
> And you can imagine that the box is narrowing to the bottom, that's why the face is not visible.

You would not bother to construct the sides of the box if there's nothing to keep out, the sides only make sense when they border other floor tiles.
When they border space the sides should be open, when it borders floor or walls then the sides should be present.

**Comment by AMyriad** [comment]
> Sorry I don't understand what exactly is asymmetrical and looks bad to you. Please elaborate further.

> image

There is a 2-pixel gap from the corner edge on some sides, and a 1-pixel gap on others. See above ^

**Comment by moocowswag** [comment]
> There is a 2-pixel gap from the corner edge on some sides, and a 1-pixel gap on others. See above ^

I believe thats just an attempt at perspective, the lower corners are going to appear different from the higher corners and the left and right are mirrored.

**Comment by SimplySmiley123** [comment]
Not gonna lie I hate looking at these.

**Comment by MTandi** [comment]
> There is a 2-pixel gap from the corner edge on some sides, and a 1-pixel gap on others. See above ^

That is because this side is obscured on the bottom of the sprite due to the plating being sunk into the border of the sprite.

**Comment by Imaginos16** [comment]
I don't like this. There's nothing really much to my words to articulate my position, but this simply looks... *Off* for me. Normally floors should blend in with each other so that there's better cohesion with the station's environment. This really screws with the geometry, making it look distracting and awkward.

**Review by Wallemations — APPROVED** [review]
Tentatively approving this because I think it'll look better come August

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]

**Comment by DrDiasyl** [comment]
Wallening is upon us...

**Comment by LemonInTheDark** [comment]
> Tentatively approving this because I think it'll look better come August

worth testing/waiting then

**Comment by Twaticus** [comment]
im actually digging this idea a lot. but a couple things
i definitely want to wait until wallening is through + had some time to settle, then test this for a bit and see how it goes
big visual changes all around, theyd both need their own time for finding issues and tweaking so i dont want them in all at once

theres GOT to be a way around the space stuff its just not working together
also maybe once thats figured out it could be applied to grass aswell cause that also seems weird(also doesnt grass have frills or something? its not shown in the screenshot so idk if its been removed or is breaking)

**Comment by Jacquerel** [comment]
> (also doesnt grass have frills or something? its not shown in the screenshot so idk if its been removed or is breaking)

IIRC we have two kinds of grass turf, one with and one without, so that's presumably the one without

**Comment by ArcaneMusic** [comment]
Is there any chance we can get this PR updated with sprites against the new walls?

**Comment by deathrobotpunch** [comment]
why is this still up after the revert

**Comment by MTandi** [comment]
I have no clue how to make this look better with space tiles, I thought it makes sense (example below). Closing for now.

image

**Pull request closed without merging**
