### PR TITLE
3/4 MULEBot Sprites

### PR DESCRIPTION
**Pull request by 13spacemen**
PORTED FROM PARADISE

Adds 3/4 Mulebot Sprites
mules

:cl: atteria
imageadd: 3/4 sprites for MULEBots
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
why for me it doesn't seem 3/4

**Comment by 13spacemen** [comment]
> how do they look oriented other directions?

they only have 1 dir, but so do the current ones

**Review by Imaginos16 — APPROVED** [review]
Next time, actually add a link to the PR body that sends to the orignal PR. **Crediting the creator of the original sprite is generally a nice thing to do.**

For the record its this PR here: https://github.com/ParadiseSS13/Paradise/pull/17502

And its creator is Atteria, which I would very much like you to add it right beside the first :cl: so the changelog actually credits the correct person.

**Comment by VladinXXV** [comment]
No red lights (eyes) 😢 
you killed them
that side looks cool

**Comment by 13spacemen** [comment]
> No red lights (eyes) 😢 you killed them that aside looks cool

they do have red lights, check the sprites

**Comment by atteria** [comment]
That stretch-to-fit screenshot sure isn't flattering.

**Comment by notfrying1pans** [comment]
ngl these look way too flat

**Pull request merged**
