### PR TITLE
[MAP] Increases size and complexity of boxstation maint [Ready for review/merge]

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
This PR adds several new areas to box's maintenance, and edits some existing areas to make them either more interesting or more complicated to navigate, and attempts to reduce the number of chokepoints that people are funneled into.

LATEST IMAGES INCOMING

New north-west maint:
maintnorthwest
Includes a new area, the Observatory.
Reroutes traffic flow to lower the probbability of someone walking past while you absorb/convert/debrain/etc
Adds a monkey recycler +cubes to a hidden room, for assistants to take apart/mess around with/start illicit xenobio

New Aft maint:
southwest1
Adds a maint bar, accessible from the firefighting closet, above the old incinerator
Adds a sealed-off cut-through to engineering maint, lowering the "Corridor of death" effect in blob.
Adds a blob event spawnpoint to the old incinerator

engi
Reshuffles maint slightly to allow the maint bar to fit
Adds a supply closet butting up against the SMES storage's walls, because currently the SMESes are more protected than the singularity.

Virology Maint:
bio
Moves Biohazard Disposals Routing further south, and adds a winding corridor above it, perfect for xeno nests/assistant projects.
Adds an airlock to Biohazard Disposals Routing by request.

Science Maint:
sci
 Adds an additional room in science maint, near the old observatory, and gives it an airlock
Adds a blob spawn point to this room

Additionally adds an indestructible wall to the bomb range

### CODE REVIEW

**Comment by Anonus** [comment]
Image formatting! It's `!(texthere)[image link.com]`

**Comment by xxalpha** [comment]
Add a space airlock in maintenance south of the Medbay. The one that was there previously got removed.

**Comment by Incoming5643** [comment]
Sometimes dead end rooms in maint are a good thing, as it makes them less apt to be entered randomly on the way to something else. These changes are a bit of a nerf to cults/shadowlings/blobs as a result, and in general will making hiding harder.

**Comment by xxalpha** [comment]
I agree with incoming.

**Comment by SconesC** [comment]
>removes that one pocket in bar/chapel maint that the disk sometimes respawns in for epic funnies

**Comment by Jalleo** [comment]
I think there is more dead ends now

**Comment by SconesC** [comment]
I honestly don't think it's good to have maint for maint's sake, what we have now is fine.

**Comment by Cheridan** [comment]
The new mapping doesn't look very detailed, they just kinda look like empty tunnels. If we're going to go Meta we might as well go Full Meta

**Comment by WJohn** [comment]
Yeah I think a bunch more items would make it more interesting, but otherwise HUGE :+1:

**Comment by Durkel** [comment]
Ugly maintenance bloat just for the sake of having a bigger maintenance. Gross :-1:

**Comment by Dorsisdwarf** [comment]
Scones, this doesn't remove anything from bar/chapel maint, much less the blobpoint.

**Comment by Niknakflak** [comment]
It's hard to take an in-depth look on my phone but so many windows ahaaaa

**Comment by Dorsisdwarf** [comment]
Blame coderbus, they demanded windows for the window gods

**Comment by Cookiesndip** [comment]
Not fond of it. Feels like we're making maintenance more... 1-tile-wide tunnel-y, and making there be a couple designated 'HEY I'M KILLING/LINGING/HIDING PEOPLE' places to substitute.

Heck, there's even fewer splits than before, meaning it's pretty tough to lose security in maintenance. Top that off with more dead-ends, meaning it's easier to get cornered, and you have a recipe for disaster if you're trying to hide/dispose of bodies/etc.

Then there's the windows. God help us - carp, or one dude with an axe can make all of maintenance pretty much permanently uninhabitable in a minute or two.

Please don't merge.

**Comment by Dorsisdwarf** [comment]
@Cookiesndip 

Care to get specific? Again, this PR edits several areas, so if you make a vague sweeping statement, that's unhelpful.
I also fail to see how this makes maint "more 1x1 tunnel-y". Maint is already mostly 1 or 2-wide tunnels, and this only adds a single part which could be construed as such (To an area already tunnely)

Windows: Maint is full to the brim with windows already, especially in the areas I included. I'll post comparison pics with the current map soon.

**Comment by Dorsisdwarf** [comment]
Old
old
New
maintnorthwest

Old
old
New
southwest1

Old
old
New
bio

Old
old
New
sci

**Comment by OhEmGee** [comment]
Did you get rid of the atmos room in viromaint?
It isn't visible in the new map.

If so, why?

Atmos rooms are pretty useful in hiding bodies if you have access, or flooding specific areas with plasma. There should be more of em, not less.

**Comment by Dorsisdwarf** [comment]
The atmos cubbyhole was untouched, hence why I didn't expand the picture far forewards enough to include it in the 'New' image. Biohazard moved down, and the windy trash corner took it's place, atmos remained untouched

**Comment by MrStonedOne** [comment]
Don't put blob spawn points near fuel tanks. Its bad mkay. Otherwise I like it.

**Comment by Dorsisdwarf** [comment]
Me and jalleo are pretty sure that the grey tanks aren't meant to be connected to distro by default, due to their differently-colored piping. We thought they were for obtaining clean air if distro is compromised

**Pull request merged**
