### PR TITLE
New brain damage lines

### PR DESCRIPTION
**Pull request by ghost**
Adds some new rib-tickling brain damage lines, most are weed related
Reason for change is it's funny

:cl:
add: New brain damage lines!
/:cl:

### CODE REVIEW

**Comment by Aloraydrel** [comment]
Sir can you turn that toy off?

**Comment by ShadowDeath6** [comment]
10 jokes only ganja gods will get

**Comment by Repukan** [comment]
Zimbabwe

**Comment by optimumtact** [comment]
lame.

**Pull request closed without merging**
