### PR TITLE
Revert "New Lizard Sprites + Digitigrade Limbs "

### PR DESCRIPTION
**Pull request by LanCartwright**
Reverts tgstation/tgstation#20599

Day Zero it's full of game breaking bugs.
Poorly recieved and only tested for 5 minutes.
Cosmetic appearance is awful; doesn't match body parts at all. Artwork direction completely misaimed.

Was there even any point to the PR except add a unneeded cosmetic effect?

### CODE REVIEW

**Comment by WJohn** [comment]
there is literally a fix PR already up addressing all the bugs.

**Comment by LanCartwright** [comment]
Doesn't address the rest of the points that it really has no point, and it was poorly recieved and recieved no playtesting or test merging (from what I remember).

**Comment by Cuboos** [comment]
(besides the bugs) i don't get what the big deal is. Who cares if lizards get more appearance options than people?

**Comment by Militaires** [comment]
>Cosmetic appearance is awful; doesn't match body parts at all. Artwork direction completely misaimed.

according to who

>Poorly recieved and only tested for 5 minutes.

poorly recieved BY WHO.

nigga.

**Comment by WJohn** [comment]
Yeah I heard a ton of positive reviews, it'll die down shortly anyway.

**Comment by Incoming5643** [comment]
I knew this was coming but I didn't think it'd be you.

Where were you when I was making the initial pull?

I take personal offense to you saying it wasn't tested. You don't even want to know how many rounds I had to run this through locally to get it to this point.

Poorly recieved by who?

Pull could not be test merged due to it updating the save file version. Doing so and not ultimately merging the pull leads to problems.

**Comment by Cuboos** [comment]
Why not give humans a few more appearance options just to satisfy the special snowflakes complaining about special snowflakes?

**Comment by Incoming5643** [comment]
@Cuboos 
Would love to, but human body parts don't offer a lot of real estate for tatoos/scars. Only reason this stuff works for lizards is because it's "Allowed" to go off the sprite without looking weird.

**Comment by LanCartwright** [comment]
@Militaires @Incoming5643 
 https://tgstation13.org/phpBB/viewtopic.php?f=10&t=7951

I'm not concerned about snowflakiness, the PR was inherently flawed because it really had no point. It's really a lizard sprite change in disguise which is pointless. Running things locally are small changes. Big changes need to be tested.

**Comment by Incoming5643** [comment]
It... wasn't In disguise at all? 

"New Lizard Sprites"

It's right there in the title.

**Comment by LanCartwright** [comment]
What was the point of the PR? Just to change sprites? There's no real change at all. It's just added a pointless and buggy feature that doesn't fit theme at all; the legs are completely mismatched and doesn't match any art.

**Comment by Incoming5643** [comment]
>What was the point of the PR? Just to change sprites?

For the most part, yes. Notice how that's listed first in the title.

>It's just added a pointless and buggy feature that doesn't fit theme at all; the legs are completely mismatched and doesn't match any art.

The art was by the same guy who did all the previous lizard sprites we've used for years, by every definition it cannot mismatch the "theme" because @WJohn dictates what the theme IS here.

**Comment by LanCartwright** [comment]
Then his haitus made his work flawed and he needs time to readjust back to what he was previously doing.

This honestly seems like a stealth feature to readd removed features, which were removed for a reason.

**Comment by Incoming5643** [comment]
This feature has never existed before this pull. It'd not readding anything?

**Comment by LanCartwright** [comment]
There was a removal of several lizard cosmetics from months ago, it seems that something similar has snook it's way onto your PR.

**Comment by Incoming5643** [comment]
del: While there are some new bits, a few old bits have gone by the wayside, if your lizard has been affected by this the specific feature will be randomized until you pick a new setting.

WJohnston didn't resprite every feature, but the features lost this way were nearly impossible to notice like "light stripe" on body_markings or were rendered wholy redundant in the past like "Dark Tiger + Head" as opposed to "Dark Tiger". The stripes on the head had been removed with dismemberment.

**Comment by WJohn** [comment]
Lan what are you going on about right now?

**Comment by LanCartwright** [comment]
So the sprite job was half-done from the start?

I don't see the point of the only "feature" your PR had. The legs don't match the theme at all and it serves no purpose whatsoever.

**Comment by WJohn** [comment]
What THEME are you talking about here? There was no pre-established theme to start. Lizard sprites were completely up in the air about their design and style.

**Comment by LanCartwright** [comment]
The legs are completely mismatched and misalsigned. Even without a theme they do not fit the game.

**Comment by PKPenguin321** [comment]
>>Cosmetic appearance is awful; doesn't match body parts at all. Artwork direction completely misaimed.

>according to who

to me and hopefully anybody else with eyes
the things look atrocious

**Comment by Incoming5643** [comment]
Any subjective taste about the sprites is impossible to refute but also the worst possible argument to base a revert on (beyond having no argument at all).

**Comment by LanCartwright** [comment]
Even as you said, it's still buggy with various jumpsuits that you haven't fixed. It was hastily merged when it was clearly broken without testing.

**Comment by Incoming5643** [comment]
There was a time when 4 days to merge would be considered hasty, but we left that time a long time ago.

Your point can't stand as long as I'm willing to fix these problems (which I'm literally doing as we speak). 

If your argument is that no pr should ever be merged before it is 100% assuredly free of all potential bugs you should be creating revert prs for roughly 60% of all pulls these days.

**Comment by LanCartwright** [comment]
You're not fixing the sprites which don't fit and are atrocious.

**Comment by Incoming5643** [comment]
https://github.com/tgstation/tgstation/pull/20656#issuecomment-249331117

**Comment by LanCartwright** [comment]
Your fix doesn't address our points. It's not about what you think, or what I think, but what the players and the community think; that it doesn't fit the theme.

**Comment by WJohn** [comment]
I seriously don't know *what* you want me to fix with the sprites. Is there a problem with the anatomy? Can you please bring up a picture and circle in red what pixels are off? ANYTHING USEFUL?

WHAT THE HELL DOES THEME EVEN *MEAN*

**Comment by ChangelingRain** [comment]
https://github.com/tgstation/tgstation/pull/20656#issuecomment-249331117

**Comment by Supermichael777** [comment]
the side sprites are spaced too widely it looks unnatural

**Comment by WJohn** [comment]
I tried putting them closer together, believe me it looks much, much worse. This is the least ugly looking I could come up with.

**Comment by Iamgoofball** [comment]
you people think you've seen bad sprites?

**Comment by Cuboos** [comment]
Goof, no.

**Comment by Wyzack** [comment]
I also think these look retarded but can you please quit trying to justify your revert with claims of theme and shit when the reality is that you just don't like them? Unless you have ingame poll statistics to back this up or something it is pretty pretentious to claim you are enforcing the will of the community or whatever

**Comment by TehZombehz** [comment]
I'm glad these people aren't my congressmen.

**Comment by Wyzack** [comment]
I would also certainly agree that we really do not need even MORE lizard cosmetics but you also cannot dictate what volunteer coders do with their time

**Comment by Incoming5643** [comment]
Technically speaking my pull removed more cosmetics than it added.

**Comment by KorPhaeron** [comment]
Never thought I'd see the day that @LanCartwright was trying to revert a lizard nerf

**Comment by ChangelingRain** [comment]
I'll reopen this when jmad comes up with an argument that isn't instantly refuted and doesn't rely on subjective opinions.

**Comment by optimumtact** [comment]
Damn I wanted to close this

**Comment by optimumtact** [comment]
Hah, take that, now go and boil your heads

**Comment by Militaires** [comment]
classic oranges

**Comment by KorPhaeron** [comment]
>see github notification
>get excited because I've been trained by that notification dot across basically all websites now
>comment on week+ old PRs

Every time

**Comment by Cuboos** [comment]
N-N-N-N-NECRO POST

**Pull request closed without merging**
