### PR TITLE
Robots now speak in a different font.

### PR DESCRIPTION
**Pull request by Iamgoofball**
jpml9pk
looks better ingame and not stretched out due to printscreen

### CODE REVIEW

**Comment by dannno** [comment]
ew no

**Comment by CorruptComputer** [comment]
ew yes

**Comment by Anonus** [comment]
makes it even more impossible to impersonate the AI/10

**Comment by Iamgoofball** [comment]
adding a better font now

**Comment by Iamgoofball** [comment]
new font added

**Comment by Dorsisdwarf** [comment]
This doesn't affect NTSL impersonation, right?

**Comment by Iamgoofball** [comment]
@dorsisdwarf

you can't impersonate silicons over tcomms anyways as you can't override the "says, " shit with "states,  "

people will notice and then call "check tcomms traitor is about"

**Comment by CollenN** [comment]
Then what's the point of this?

**Comment by Iamgoofball** [comment]
@CollenN flavor and uniqueness

**Comment by Iamgoofball** [comment]
fucking wrong button shit

**Comment by dannno** [comment]
ok the new font is a bit better.

**Comment by GunHog** [comment]
@Iamgoofball if you were to integrate font selection into NTSL, then human to silicon and vice versa would be easily possible.

**Comment by Iamgoofball** [comment]
NTSL code is a scary beast and I don't know how most of NTSL works

**Comment by paprka** [comment]
EW YES FOREVER

BEEP BOOP

THIS IS NOT A BAD CHANGE

**Comment by ExplosiveCrate** [comment]
I actually like this.

Maybe adding the ability to choose font types when using a voice changer would be a good idea.

**Comment by Steelpoint** [comment]
:+1:

**Comment by KazeEspada** [comment]
Next we need toy voice changers that make your font look like this(like the Darth Vader voice changing masks?).

**Comment by Iamgoofball** [comment]
time to dehumanize

**Comment by Miauw62** [comment]
dehumanize he

**Comment by GunHog** [comment]
Do you, Goof or Meow, mind if I try to make an NTSL var for this?

**Comment by GunHog** [comment]
To be honest, I believe this implementation should have been applied to the *language* spoken instead of applied directly to the silicons. Anything spoken in "ROBOT" language would have the font. It would have made it easier for working it into NTSL as well. It would have made for an interesting traitor item as well. I am obviously posting this too late, though.

**Comment by RemieRichards** [comment]
@GunHog make a PR for that if it's what you believe to be better.

**Comment by GunHog** [comment]
This font does NOT look good in italics! (Binary)

**Comment by RemieRichards** [comment]
@GunHog post pic pls.

**Comment by GunHog** [comment]
screenshot 2015-01-21 11 52 05

**Comment by dannno** [comment]
looks ok.

**Comment by RemieRichards** [comment]
@GunHog looks like BYOND is butchering it.

**Comment by Steelpoint** [comment]
screenshot 2015-01-22 01 47 55

**Comment by dannno** [comment]
just make robotic talk non-italic for silicons

**Pull request merged**
