### PR TITLE
Thrownthing datum refactor: you can now throw stuff at mobs lying on the floor.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. I refactored it with the intention to allow thrown things to hit movables with no density (except those with the letpassthrow flag, otherwise it'll fuck with tables). 
I also expunged some procs that were only called in one place and moved the relative portions of code where the call was.
Some redundant finalize() calls were also removed. The `initial_target` is a weakref var, but I can change it to a movable one and use the `COMSIG_PARENT_QDELETING` signal to clear it if you want me to.

Oh yea, I have also tested it, though you can expect a few relatively small issues or oversights that'll get fixed as things go because this is a change to a core feature of the game.

## Why It's Good For The Game
Quality of life. Thrown projectiles currently only hit movables that a character can bump into, and that sucks.

## Changelog
:cl:
refactor: refactored the thrownthing datum a little.
qol: you can now throw stuff at movables with no density, such as mobs lying on the floor, mice, APCs, light bulbs etcetera etcetera.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
pog

will you have to directly click on a prone mob to hit it?

**Comment by newfren** [comment]
If you're lying down on a tile with a mouse, or a lightbulb, or whatever, which will it decide to hit? Does stuff hit a light even if it would not hit the wall the light is attached to?

**Comment by Ghommie** [comment]
> 
> 
> If you're lying down on a tile with a mouse, or a lightbulb, or whatever, which will it decide to hit? Does stuff hit a light even if it would not hit the wall the light is attached to?

Implying there aren't dense objects in the way that aren't tables and the such, it'll hit the movable you clicked on when throwing the thing. It's not random.
Also, light tubes and bulbs, aren't actually located on the wall turf but are offset to look like they're. Same for most wallmounted objects.

**Comment by newfren** [comment]
Ohhhh I was misunderstanding how this worked. So if you click past a dude lying down it'll still sail over him?

**Comment by Ghommie** [comment]
Yep.

**Review by Kylerace — CHANGES_REQUESTED** [review]

**Pull request merged**
