### PR TITLE
Revert "Adds petting for real"

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I felt some vague sense of guilt when I hit that merge button

### CODE REVIEW

**Comment by coiax** [comment]
>opening a revert PR for the PR you merged

**Comment by ChangelingRain** [comment]
KNEEJERK REVERT

**Comment by kevinz000** [comment]
why...

**Comment by optimumtact** [comment]
this is with @lzimann to decide

**Comment by JJRcop** [comment]
Reaction party!

**Comment by anconfuzedrock** [comment]
>petting can get in but not slappy hands

**Comment by PKPenguin321** [comment]
Right your wrongs

**Comment by ChemicalRascal** [comment]
@anconfuzedrock #makeSlapsGreatAgain

**Comment by Anonmare** [comment]
Please state why you would like this PR to be pulled

**Comment by Hatfish** [comment]
You made this decision, now you live with it!

**Comment by JJRcop** [comment]
🚲🏚

**Comment by coiax** [comment]
Unsubbing from this PR;.

**Comment by PKPenguin321** [comment]
Atone for your sins

**Comment by anconfuzedrock** [comment]
@ChemicalRascal I perfected slap fights it cant be better what more could you want

**Comment by Aloraydrel** [comment]
.pull kor

.pet kor

.ruffle kor

.stinky kor

**Comment by Thunder12345** [comment]
Kneejerk revert, close

**Comment by Grazyn** [comment]
\>revert PR not even a minute after you merged it

will the memes ever stop

**Comment by Razharas** [comment]
# Denied

We either have erp and patting or no erp and patting

**Comment by Razharas** [comment]
Oh its a revert

**Comment by Thunder12345** [comment]
Let's have no erp and petting then, and just close this

**Comment by ShadowDeath6** [comment]
Kor's best revert pr in centuries

**Comment by lzimann** [comment]
Ok this decision is all on me! It's kinda of a dumb feature imo since doesn't really add anything besides a new hug message, but it's harmless and it gives me a reason to punch people that try to do that with me! Plus, the amount of drama caused by a silly message was kinda too much when you stop to think about it so I'll just close this revert, if it gets really bad or someone try to add another snowflake bullshit(le slippery slope meme) I'll personally revert this myself.

**Pull request closed without merging**
