### PR TITLE
removes the beamrifle

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

removes the beamrifle
makes the pixelbeam icons used by the beamrifle white with 255 alpha, if someone wants to make theirs grey with random alpha they can use code they dont need to bake it into the sprite

## Why It's Good For The Game

it was in a sad state, it hasnt been maintained for years, its janky, has some not great code and its practically unused by crew, with it requiring anomaly cores

i plan to revisit it at some point with a new look at it, and some nice support from components like the new scope and whatnot

## Changelog

:cl:
del: removes the beamrifle
/:cl:

### CODE REVIEW

**Comment by Livrah** [comment]
>Lock something behind ridiculous timegates and resource gates
>Noone uses it because of above
>"its practically unused by crew", remove

**Comment by wesoda25** [comment]
> i plan to revisit it at some point with a new look at it, and some nice support from components like the new scope and whatnot

Why not just wait and replace it then?

**Comment by Fikou** [comment]
> > i plan to revisit it at some point with a new look at it, and some nice support from components like the new scope and whatnot
> 
> Why not just wait and replace it then?

it makes our click code worse

**Comment by tralezab** [comment]
i'd rather we start using it again, actually. it's incredibly unique and fun, truly one of the better guns in the game. huge mistake making it so annoying to manufacture that everyone stopped. anomaly core for a gun that you have to stay stationary to use, that gives a beam from your exact location? madness, I say!

**Comment by D4C-420** [comment]
The reason it goes unused is because it requires both advanced weapon tech and 2 anomaly cores which already have a myriad of other uses (flux has armor and its own gun, grav has its own gun and armor and modsuit moduales). Honestly just make it require a pyro core (im 99% sure pyro cores have like nothing tied to them) and your more likely to see people to use it even with the RND requirments.

**Comment by wesoda25** [comment]
> > > i plan to revisit it at some point with a new look at it, and some nice support from components like the new scope and whatnot
> 
> > 
> 
> > Why not just wait and replace it then?
> 
> 
> 
> it makes our click code worse

Like what's the cost? Is it preventing certain possibilities, slowing things down?

**Comment by Dorsisdwarf** [comment]
you got a bit of incorrect description mashed into your PR body i think

**Comment by castawaynont** [comment]
the beamrifle fucking sucks

**Comment by tralezab** [comment]
> the beamrifle fucking sucks

let's discuss!

**Comment by wesoda25** [comment]
The first and third are really what create the issue I think, the cool factor excuses the second. But it's just not worth going through all the effort (a considerable amount) to make something cool if there's a considerate risk of you losing it. Perhaps a bit more insurance might help? A way to set a fingerprint lock or something? Or custom use implants? Not a very good solution though.

**Comment by castawaynont** [comment]
the gun doesn't penetrate walls correctly in pierce mode, and the explosion effect just sets the area on fire.

**Comment by Fikou** [comment]
closing in favor of arm doing cool stuff

**Comment by WarlockD** [comment]
Oh my god, thats one hell of a runtime.  I don't think active_mousedown_item  is ever reset once its set.  What happens if you dispose of something that is in the client vars.

**Pull request closed without merging**
