### PR TITLE
New welder sprites and welder name, Fix experimental welder.

### LINKED ISSUE #9003: Upgraded Welding Tool cannot fit in Utility Belt
Reproduce: Hack U-Tool or spawn /weldingtool/hugetank, attempt to put it in a toolbelt

The upgraded welding tool is too big for the toolbelt.
toobig

### PR DESCRIPTION
**Pull request by Firecage**
Firstly, this changes the name of the Upgraded Welding Tool to the Upgraded Industrial Welding Tool.

Secondly, this adds unique sprites to both the upgraded industrial welding tool, and the experimental welding tool.

Upgraded Industrial Welder and Experimental welder:
<a href='http://rghost.net/6K4xfwVfV.view'></a>

Inhands:
http://rghost.net/6FlKRGMh7.view
http://rghost.net/6fpmYHzjm.view

Fixes #9003 

Experimental welding tool gif: http://imgur.com/TQQNcKX

Edit: This also fixes the Experimental Welding Tool so it works.

Edit3: Updated original sprites a 'lil bit.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Kinda ugly, no offense.

**Comment by Firecage** [comment]
*cries*

**Comment by pudl** [comment]
yeah thats hideous

**Comment by optimumtact** [comment]
Looks okay to me

**Comment by Firecage** [comment]
Yaaaaaaay

**Comment by Lumipharon** [comment]
The blue one looks like an uzi, the green one looks like some kind of toxic injector thing. 

What's wrong with the current sprites?

**Comment by Firecage** [comment]
@Lumipharon Lumi, current ones are the normal welder sprites.

**Comment by pudl** [comment]
theyre even worse now

**Comment by Firecage** [comment]
B-but...they are Wjohnston approved...

**Comment by WJohn** [comment]
I'm alright with these, though I'm probably biased to some degree. I also did not originally make these, it was someone else from the first forums whose name I can't remember.

**Comment by pudl** [comment]
now they're even double worse

**Comment by optimumtact** [comment]
Nobody is listening to you any more pudl

**Comment by pudl** [comment]
firecage is

**Comment by Firecage** [comment]
Nope

**Comment by GunHog** [comment]
I love these! :+1: Also, kudos for having a welded has an easily identified tank level sprite!

**Pull request merged**
