### PR TITLE
Removes the accounting console board from the sec lathe and moves it to the service lathe

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Removes the design for the accounting console circuit board. There is now a replacement circuit board in the HoP locker.

This PR is mainly meant to address a downstream issue, but I figure I should make the PR up here first. 
## Why It's Good For The Game
It's the HoPs job to monitor and handle the accounting console, not security's. This will encourage security to co-operate and talk with the HoP if they need to monitor purchases.
## Changelog
:cl:
balance: Moved the account console board to the service lathe
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
wheres the command departmental lathe

**Comment by JohnFulpWillard** [comment]
I think you should put it in service lathe instead

**Comment by softcerv** [comment]
> I think you should put it in service lathe instead

How so? Part of the intention with this PR was to make the boards for the console more scarce, but I'm not against that solution if you have a good reason behind it.

**Comment by Fikou** [comment]
your checks are failing because you didnt remove the design id

**Comment by softcerv** [comment]
> your checks are failing because you didnt remove the design id

shoot! Thank you for pointing that out!

**Comment by JohnFulpWillard** [comment]
> How so? Part of the intention with this PR was to make the boards for the console more scarce, but I'm not against that solution if you have a good reason behind it.

Your PR made it seem like security was printing it from their techfab so they can watch over this, no security personnel have access to Service so I thought it would be fine to lock it behind the HoP's department instead of the HoS'.

**Comment by RimiNosha** [comment]
It's a pretty powerful tool if the HoP knows basic bank forensics, and is also highly optional, so I'd even go as far as to just leave the console in their office with no spare board.

**Comment by softcerv** [comment]
> > How so? Part of the intention with this PR was to make the boards for the console more scarce, but I'm not against that solution if you have a good reason behind it.
> 
> Your PR made it seem like security was printing it from their techfab so they can watch over this, no security personnel have access to Service so I thought it would be fine to lock it behind the HoP's department instead of the HoS'.

Fair. I think I'd prefer to keep it scarce for now though. Especially for cargo orders, since there isn't any real counter-play to the console, If there was something that could screw with the monitoring like disposable credit/debit cards, I'd be more willing to have it be printable.

**Comment by YakumoChen** [comment]
The extreme degree to make this machine unrebuildable is silly when it has no direct game impact and is relatively easy to bypass (you can order by proxy or from cargo directly, which is not tracked)

**Comment by softcerv** [comment]
> The extreme degree to make this machine unrebuildable is silly when it has no direct game impact and is relatively easy to bypass (you can order by proxy or from cargo directly, which is not tracked)
> 
I would argue that the console should be treated like a HoP job item. No other job directly deals with finances the way that they do, besides the quartermaster maybe. It has direct game impact by allowing the user to monitor and find suspicious transactions, if this had no impact, I wouldn't be making this PR.

**Comment by ExcessiveUseOfCobblestone** [comment]
The telecoms big brother console is replaceable, and that's more damning than banking logs.

It should be in supply, and if you're really pressed about it's strength add a material cost.

**Comment by softcerv** [comment]
> The telecoms big brother console is replaceable, and that's more damning than banking logs.
> 
> It should be in supply, and if you're really pressed about it's strength add a material cost.

Don't you need to link that console with telecomms machinery?

**Comment by JohnFulpWillard** [comment]
> If there was something that could screw with the monitoring like disposable credit/debit cards, I'd be more willing to have it be printable.

I guess you can use a fake ID. I dunno how agent IDs work with these machines lol

> I would argue that the console should be treated like a HoP job item.

Other HoP job items in the past were made accessible to HoP's techfabs - https://github.com/tgstation/tgstation/pull/63081

> Don't you need to link that console with telecomms machinery?

You just need the key to log in, so you'd have to get the codes from the CE's office or Syndicate lavaland/space comms agent bases (or russian DJ?)

I think the board should be in the Service lathe, if Security is constantly breaking in to build the machine, I'd consider that an Admin issue.

**Comment by softcerv** [comment]
> I think the board should be in the Service lathe, if Security is constantly breaking in to build the machine, I'd consider that an Admin issue.

Can do.

**Pull request merged**
